In [1]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [14]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [17]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [18]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [19]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,1.075042,0.081641,-0.098422,-0.562251
1,0.242767,-0.395928,-1.209119,-0.562251
2,-1.461057,0.208583,0.280542,-0.202838
3,0.078112,-0.949323,-1.147026,-0.562251
4,-2.274305,1.555538,-0.568449,1.514080
...,...,...,...,...
134,0.827589,-0.217633,-0.671191,-0.562251
135,0.578577,1.572043,-0.163918,-0.562251
136,-0.329498,-0.648232,-0.445412,-0.562251
137,0.595927,1.711090,0.143137,-0.562251
138,0.574872,1.203504,-0.843364,-0.562251

In [20]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [21]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,-0.133381,0.800544,0.405980,-0.288893
1,-0.108854,-1.860610,-0.118774,1.182201
2,-0.704414,-0.754955,0.048037,0.033974
3,-1.307469,-1.134568,0.158761,-0.562251
4,-0.615466,-0.128772,0.685437,-0.562251
...,...,...,...,...
94,-0.085581,0.263605,-0.598102,-0.562251
95,-0.599161,-0.859260,0.472444,-0.562251
96,-0.425762,-1.598975,0.432435,-0.562251
97,0.637891,-0.499761,0.081495,-0.562251
98,-0.071514,-1.004520,-0.448243,-0.562251

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [22]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:05:04,495] A new study created in memory with name: no-name-becc15a4-3dfa-474d-8393-62be883e5fd0

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734

[I 2024-04-16 01:05:16,357] A new study created in memory with name: no-name-7dd2fa87-8c6e-40e9-99db-004a3906f0b5

Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:16,319] Trial 0 finished with value: 0.7358264523738474 and parameters: {}. Best is trial 0 with value: 0.7358264523738474.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7358264523738474], datetime_start=datetime.datetime(2024, 4, 16, 1, 5, 4, 657951), datetime_complete=datetime.datetime(2024, 4, 16, 1, 5, 16, 317569), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7358264523738474

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.17932951816141288
Fold 2 IBS: 0.15173912855888336
Fold 3 IBS: 0.17662964771229905
Fold 4 IBS: 0.15303709600503956
Fold 5 IBS: 0.19681553106978894
[I 2024-04-16 01:05:17,203] Trial 0 finished with value: 0.17151018430148474 and parameters: {}. Best is trial 0 with value: 0.17151018430148474.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17151018430148474], datetime_start=datetime.datetime(2024, 4, 16, 1, 5, 16, 433269), datetime_complete=datetime.datetime(2024, 4, 16, 1, 5, 17, 203079), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17151018430148474

In [23]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [24]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.172

#### Test

In [25]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [26]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.567
IBS score: 0.259

In [27]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [28]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [29]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:05:17,907] A new study created in memory with name: no-name-dea07611-7263-4e80-afa3-5efc23c5815d

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7151898734177216

[I 2024-04-16 01:05:18,415] A new study created in memory with name: no-name-3baece87-cb3c-4618-b2c4-044e4a07479c

Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:05:18,392] Trial 0 finished with value: 0.7238815925404183 and parameters: {}. Best is trial 0 with value: 0.7238815925404183.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7238815925404183], datetime_start=datetime.datetime(2024, 4, 16, 1, 5, 17, 976929), datetime_complete=datetime.datetime(2024, 4, 16, 1, 5, 18, 392048), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7238815925404183

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2139765155205475
Fold 2 IBS: 0.22157790435913943
Fold 3 IBS: 0.20453593833829126
Fold 4 IBS: 0.22473803160496592
Fold 5 IBS: 0.21812430497307525
[I 2024-04-16 01:05:19,028] Trial 0 finished with value: 0.21659053895920385 and parameters: {}. Best is trial 0 with value: 0.21659053895920385.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659053895920385], datetime_start=datetime.datetime(2024, 4, 16, 1, 5, 18, 548812), datetime_complete=datetime.datetime(2024, 4, 16, 1, 5, 19, 28582), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659053895920385

In [30]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.724
train_ibs:  0.217

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.578

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:05:19,422] A new study created in memory with name: no-name-4f335f19-d004-48b8-8e52-b4ce5f60a12e

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173

[I 2024-04-16 01:05:20,425] A new study created in memory with name: no-name-3fec6f31-e61e-40e0-ab66-e06146d6a6a3

Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:20,361] Trial 0 finished with value: 0.7357337800920462 and parameters: {}. Best is trial 0 with value: 0.7357337800920462.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7357337800920462], datetime_start=datetime.datetime(2024, 4, 16, 1, 5, 19, 488725), datetime_complete=datetime.datetime(2024, 4, 16, 1, 5, 20, 361192), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7357337800920462

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.17976231773999546
Fold 2 IBS: 0.15088281580357382
Fold 3 IBS: 0.17576178549951946
Fold 4 IBS: 0.15354534218421234
Fold 5 IBS: 0.19571810296360162
[I 2024-04-16 01:05:21,276] Trial 0 finished with value: 0.17113407283818055 and parameters: {}. Best is trial 0 with value: 0.17113407283818055.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17113407283818055], datetime_start=datetime.datetime(2024, 4, 16, 1, 5, 20, 483010), datetime_complete=datetime.datetime(2024, 4, 16, 1, 5, 21, 275759), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17113407283818055

In [36]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.171

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.257

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:05:22,054] A new study created in memory with name: no-name-011c9ef3-0a4a-4d9a-9a22-b77194339687

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:23,381] Trial 0 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7365995809578472.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:24,509] Trial 1 finished with value: 0.7367412285259652 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7367412285259652.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:25,739] Trial 2 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.7367412285259652.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:26,778] Trial 3 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:27,473] Trial 4 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:28,045] Trial 5 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:28,916] Trial 6 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:29,645] Trial 7 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:30,565] Trial 8 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:31,332] Trial 9 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:32,343] Trial 10 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:33,679] Trial 11 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.2462088027506373}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:34,798] Trial 12 finished with value: 0.7367412285259652 and parameters: {'l1_ratio': 0.2859395773567724}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:36,201] Trial 13 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.0418984240468101}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:37,382] Trial 14 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5677959089332557}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:38,142] Trial 15 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5936985909694869}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:38,959] Trial 16 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.864361866670343}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:40,601] Trial 17 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5698747240965845}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:41,732] Trial 18 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:42,447] Trial 19 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5837235145191467}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:43,173] Trial 20 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4084083564240419}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:44,034] Trial 21 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5658070076660593}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:44,704] Trial 22 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6334146666187299}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:45,666] Trial 23 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.49683291067694285}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961

Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:46,506] Trial 24 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.8080056249917272}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:47,276] Trial 25 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.628676464772803}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:48,418] Trial 26 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:49,725] Trial 27 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4956576670258191}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:50,590] Trial 28 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.7467529633091712}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:51,241] Trial 29 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6333140414043641}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:52,636] Trial 30 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5464339627757957}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:54,125] Trial 31 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.675609500608811}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:54,881] Trial 32 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5501220413991621}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:56,173] Trial 33 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4391573639688424}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:57,331] Trial 34 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.7353403195178041}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:58,188] Trial 35 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.3349958381129322}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:05:59,196] Trial 36 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.610216112150238}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:00,097] Trial 37 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.456319095620811}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:00,853] Trial 38 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5312361810707404}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:01,823] Trial 39 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6801269012586293}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:03,293] Trial 40 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.9971782991655923}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:04,008] Trial 41 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.584841748891064}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:04,973] Trial 42 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5112463449052407}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:05,832] Trial 43 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5788855830041136}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:06,942] Trial 44 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.779553936852023}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:09,148] Trial 45 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6650853818004321}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:10,550] Trial 46 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.456859333188761}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:11,721] Trial 47 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.9282652336267145}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:12,930] Trial 48 finished with value: 0.7358483713831081 and parameters: {'l1_ratio': 0.16956959855657594}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883

Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:13,763] Trial 49 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.355745098499332}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:14,502] Trial 50 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5938078108685914}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:15,203] Trial 51 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5434891196509528}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:16,374] Trial 52 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5704330167256882}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:17,272] Trial 53 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6565215671413143}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:18,617] Trial 54 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.7190285208337384}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:19,682] Trial 55 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4969258308336762}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:20,655] Trial 56 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4027182732671464}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:22,139] Trial 57 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:23,546] Trial 58 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.7057796999679327}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:25,182] Trial 59 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5276479696954601}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:27,114] Trial 60 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.45666550284417057}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:28,420] Trial 61 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5544831424966635}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:29,469] Trial 62 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.6007168103266693}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:30,497] Trial 63 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4802208480186365}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:31,524] Trial 64 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6487613961068895}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:32,390] Trial 65 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.56113299768527}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:33,520] Trial 66 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5220034162635022}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:34,221] Trial 67 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.6098649411479423}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:35,267] Trial 68 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.42775791734338775}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:36,680] Trial 69 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.48519294589141715}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:37,584] Trial 70 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.574885734810716}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:38,889] Trial 71 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5448419671094974}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:40,146] Trial 72 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.641587269359111}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:41,155] Trial 73 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5263345735221958}. Best is trial 3 with value: 0.7375799731147099.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:41,879] Trial 74 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5982272024150322}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:42,741] Trial 75 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.684187061855721}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:43,624] Trial 76 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.38238491516852535}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:44,368] Trial 77 finished with value: 0.7357337800920462 and parameters: {'l1_ratio': 0.7694598008142269}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:45,417] Trial 78 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5588056476602503}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:46,320] Trial 79 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4732691214823139}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:47,077] Trial 80 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5038862102409533}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:48,163] Trial 81 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6279138019705358}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:49,431] Trial 82 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6176557075060186}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:50,525] Trial 83 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5854029922564327}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:51,547] Trial 84 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5448056555193593}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:52,726] Trial 85 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6977202369205455}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:54,712] Trial 86 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.650616371328275}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:56,515] Trial 87 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5173181506179257}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:57,703] Trial 88 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.6071855188256182}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:58,811] Trial 89 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.574249267378581}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:06:59,731] Trial 90 finished with value: 0.7365995809578472 and parameters: {'l1_ratio': 0.6639865681836653}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:00,631] Trial 91 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.52367040287431}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:01,287] Trial 92 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5417733899579164}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:04,749] Trial 93 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4524106207385594}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:07,123] Trial 94 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5764563071532146}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:09,400] Trial 95 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.49887163858752953}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:13,627] Trial 96 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.6030924300037979}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:16,870] Trial 97 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.4726849564789628}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098

Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:19,768] Trial 98 finished with value: 0.7367141722489089 and parameters: {'l1_ratio': 0.036027940577462836}. Best is trial 3 with value: 0.7375799731147099.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173

[I 2024-04-16 01:07:22,474] A new study created in memory with name: no-name-a60bbca5-f993-4403-8fee-8a98f01b1c0f

Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:07:22,335] Trial 99 finished with value: 0.7375799731147099 and parameters: {'l1_ratio': 0.5547002051489062}. Best is trial 3 with value: 0.7375799731147099.


* Best trial for C-index:
 FrozenTrial(number=3, state=TrialState.COMPLETE, values=[0.7375799731147099], datetime_start=datetime.datetime(2024, 4, 16, 1, 5, 25, 747897), datetime_complete=datetime.datetime(2024, 4, 16, 1, 5, 26, 777172), params={'l1_ratio': 0.5513596376059829}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=3, value=None)


* Best Score for C-index:
 0.7375799731147099

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17961702079353403
Fold 2 IBS: 0.15095065897682072
Fold 3 IBS: 0.1758817854688703
Fold 4 IBS: 0.15358600376544532
Fold 5 IBS: 0.19566662202018217
[I 2024-04-16 01:07:24,502] Trial 0 finished with value: 0.1711404182049705 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.1711404182049705.
Fold 1 IBS: 0.17921854874687435
Fold 2 IBS: 0.1510190050679179
Fold 3 IBS: 0.17631580674739586
Fold 4 IBS: 0.1536432060050057
Fold 5 IBS: 0.1957526240358902
[I 2024-04-16 01:07:26,311] Trial 1 finished with value: 0.1711898381206168 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.1711404182049705.
Fold 1 IBS: 0.17913179009993588
Fold 2 IBS: 0.1510564341999031
Fold 3 IBS: 0.17641151273022218
Fold 4 IBS: 0.15370123481959697
Fold 5 IBS: 0.19578302112960017
[I 2024-04-16 01:07:27,452] Trial 2 finished with value: 0.17121679859585165 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.1711404182049705.
Fold 1 IBS: 0.17950936694795705
Fold 2 IBS: 0.15096123996728103
Fold 3 IBS: 0.17603790900022662
Fold 4 IBS: 0.15362305499858325
Fold 5 IBS: 0.1957529484163825
[I 2024-04-16 01:07:28,201] Trial 3 finished with value: 0.1711769038660861 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.1711404182049705.
Fold 1 IBS: 0.17962783640481902
Fold 2 IBS: 0.15095810132840695
Fold 3 IBS: 0.17587706210576617
Fold 4 IBS: 0.1535754065972
Fold 5 IBS: 0.19568212394575077
[I 2024-04-16 01:07:29,774] Trial 4 finished with value: 0.17114410607638858 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.1711404182049705.
Fold 1 IBS: 0.1793944210169786
Fold 2 IBS: 0.1509533559230009
Fold 3 IBS: 0.17613160564280286
Fold 4 IBS: 0.15361028060615242
Fold 5 IBS: 0.19570553816750666
[I 2024-04-16 01:07:30,798] Trial 5 finished with value: 0.1711590402712883 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.1711404182049705.
Fold 1 IBS: 0.17975707342468614
Fold 2 IBS: 0.15087899430625373
Fold 3 IBS: 0.17576400640512202
Fold 4 IBS: 0.15355086499342344
Fold 5 IBS: 0.19571075583330036
[I 2024-04-16 01:07:31,603] Trial 6 finished with value: 0.17113233899255714 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.17113233899255714.
Fold 1 IBS: 0.17961130496491828
Fold 2 IBS: 0.15094671258836356
Fold 3 IBS: 0.17588429690759524
Fold 4 IBS: 0.153591635474386
Fold 5 IBS: 0.19565839234932245
[I 2024-04-16 01:07:32,382] Trial 7 finished with value: 0.1711384684569171 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.17113233899255714.
Fold 1 IBS: 0.1794462415115528
Fold 2 IBS: 0.1509229511350988
Fold 3 IBS: 0.17606042554696372
Fold 4 IBS: 0.15360192311149304
Fold 5 IBS: 0.19567874705560714
[I 2024-04-16 01:07:33,006] Trial 8 finished with value: 0.1711420576721431 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.17113233899255714.
Fold 1 IBS: 0.1793550740696141
Fold 2 IBS: 0.15099592988663327
Fold 3 IBS: 0.17618779618342761
Fold 4 IBS: 0.15363961029167256
Fold 5 IBS: 0.19575869426943032
[I 2024-04-16 01:07:34,029] Trial 9 finished with value: 0.17118742094015554 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.17113233899255714.
Fold 1 IBS: 0.17975806707936154
Fold 2 IBS: 0.1508797183298985
Fold 3 IBS: 0.17576358524955538
Fold 4 IBS: 0.15354981786755562
Fold 5 IBS: 0.19571214853856062
[I 2024-04-16 01:07:34,945] Trial 10 finished with value: 0.17113266741298633 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.17113233899255714.
Fold 1 IBS: 0.17976157376228985
Fold 2 IBS: 0.15088227363582288
Fold 3 IBS: 0.175762100283785
Fold 4 IBS: 0.15354612510166502
Fold 5 IBS: 0.19571706116761425
[I 2024-04-16 01:07:35,842] Trial 11 finished with value: 0.1711338267902354 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.17113233899255714.
Fold 1 IBS: 0.17976086717358827
Fold 2 IBS: 0.15088175872604143
Fold 3 IBS: 0.17576239933455884
Fold 4 IBS: 0.1535468688454333
Fold 5 IBS: 0.19571607157631182
[I 2024-04-16 01:07:37,164] Trial 12 finished with value: 0.17113359313118673 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.17113233899255714.
Fold 1 IBS: 0.1797162722798874
Fold 2 IBS: 0.1509244626417831
Fold 3 IBS: 0.1757814181260437
Fold 4 IBS: 0.15355799575566537
Fold 5 IBS: 0.1956531842685916
[I 2024-04-16 01:07:37,906] Trial 13 finished with value: 0.17112666661439424 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 13 with value: 0.17112666661439424.
Fold 1 IBS: 0.1796568259913322
Fold 2 IBS: 0.15090779131195295
Fold 3 IBS: 0.17586449356058004
Fold 4 IBS: 0.1535750135626582
Fold 5 IBS: 0.19572373899741108
[I 2024-04-16 01:07:38,707] Trial 14 finished with value: 0.1711455726847869 and parameters: {'l1_ratio': 0.788973690956328}. Best is trial 13 with value: 0.17112666661439424.
Fold 1 IBS: 0.21356050626742182
Fold 2 IBS: 0.22074768515255813
Fold 3 IBS: 0.20395541229695352
Fold 4 IBS: 0.22410368851783416
Fold 5 IBS: 0.21745959802383039
[I 2024-04-16 01:07:39,237] Trial 15 finished with value: 0.2159653780517196 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 13 with value: 0.17112666661439424.
Fold 1 IBS: 0.17971409134325178
Fold 2 IBS: 0.15092298354323638
Fold 3 IBS: 0.17578235825766864
Fold 4 IBS: 0.15356011174996662
Fold 5 IBS: 0.19565009947373496
[I 2024-04-16 01:07:40,706] Trial 16 finished with value: 0.17112592887357167 and parameters: {'l1_ratio': 0.8461342967218289}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.17971668208983846
Fold 2 IBS: 0.15092474056935443
Fold 3 IBS: 0.17578124156221756
Fold 4 IBS: 0.15355759831918434
Fold 5 IBS: 0.19565376375760324
[I 2024-04-16 01:07:41,961] Trial 17 finished with value: 0.1711268052596396 and parameters: {'l1_ratio': 0.8532495550288585}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.1795287092734297
Fold 2 IBS: 0.15097481831178536
Fold 3 IBS: 0.17597318481647514
Fold 4 IBS: 0.1536107558849407
Fold 5 IBS: 0.19567954269187884
[I 2024-04-16 01:07:42,879] Trial 18 finished with value: 0.17115340219570194 and parameters: {'l1_ratio': 0.5810452262393446}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.17971843840836288
Fold 2 IBS: 0.15092593166940546
Fold 3 IBS: 0.17578048519389933
Fold 4 IBS: 0.15355589563963848
Fold 5 IBS: 0.1956562466921294
[I 2024-04-16 01:07:43,713] Trial 19 finished with value: 0.1711273995206871 and parameters: {'l1_ratio': 0.8581374179646931}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.17972681151385284
Fold 2 IBS: 0.1509316057542458
Fold 3 IBS: 0.17577688660102156
Fold 4 IBS: 0.15354779178851152
Fold 5 IBS: 0.1956680710616963
[I 2024-04-16 01:07:44,429] Trial 20 finished with value: 0.17113023334386562 and parameters: {'l1_ratio': 0.8821826837306465}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.1797160276055946
Fold 2 IBS: 0.15092429670650545
Fold 3 IBS: 0.17578152355617543
Fold 4 IBS: 0.15355823306815689
Fold 5 IBS: 0.1956528382642972
[I 2024-04-16 01:07:45,133] Trial 21 finished with value: 0.1711265838401459 and parameters: {'l1_ratio': 0.8514414790795631}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.1796516974198108
Fold 2 IBS: 0.15090398809376876
Fold 3 IBS: 0.17586671106085708
Fold 4 IBS: 0.15358044365019788
Fold 5 IBS: 0.1957164188496695
[I 2024-04-16 01:07:46,415] Trial 22 finished with value: 0.1711438518148608 and parameters: {'l1_ratio': 0.77578307880968}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.17954733697959863
Fold 2 IBS: 0.15091920073496098
Fold 3 IBS: 0.17596483811033806
Fold 4 IBS: 0.15359208062194665
Fold 5 IBS: 0.19570694133152572
[I 2024-04-16 01:07:47,357] Trial 23 finished with value: 0.17114607955567399 and parameters: {'l1_ratio': 0.6128322661275365}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.17973517430369992
Fold 2 IBS: 0.1509372765940042
Fold 3 IBS: 0.17577330448514702
Fold 4 IBS: 0.1535397202407962
Fold 5 IBS: 0.19567998758639338
[I 2024-04-16 01:07:48,305] Trial 24 finished with value: 0.17113309264200816 and parameters: {'l1_ratio': 0.9074974021704392}. Best is trial 16 with value: 0.17112592887357167.

Fold 1 IBS: 0.17964727559710011
Fold 2 IBS: 0.15090070946174614
Fold 3 IBS: 0.17586860056125767
Fold 4 IBS: 0.15358513339564106
Fold 5 IBS: 0.1957101009421332
[I 2024-04-16 01:07:49,693] Trial 25 finished with value: 0.17114236399157562 and parameters: {'l1_ratio': 0.7647388825054626}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.17959195732865083
Fold 2 IBS: 0.1509332457520489
Fold 3 IBS: 0.17595664209883857
Fold 4 IBS: 0.1536038983124461
Fold 5 IBS: 0.19573415329574262
[I 2024-04-16 01:07:51,296] Trial 26 finished with value: 0.1711639793575454 and parameters: {'l1_ratio': 0.6477441511102914}. Best is trial 16 with value: 0.17112592887357167.
Fold 1 IBS: 0.17970857045989355
Fold 2 IBS: 0.15091923918873767
Fold 3 IBS: 0.1757847418170072
Fold 4 IBS: 0.15356547507642446
Fold 5 IBS: 0.19564228408637446
[I 2024-04-16 01:07:52,720] Trial 27 finished with value: 0.17112406212568748 and parameters: {'l1_ratio': 0.8313376819651622}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.17973694186530573
Fold 2 IBS: 0.15093847512347702
Fold 3 IBS: 0.17577254890282498
Fold 4 IBS: 0.15353801707481096
Fold 5 IBS: 0.1956824763231554
[I 2024-04-16 01:07:53,818] Trial 28 finished with value: 0.17113369185791483 and parameters: {'l1_ratio': 0.9130241346530841}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.17962895599267928
Fold 2 IBS: 0.15095887431942634
Fold 3 IBS: 0.17587657297533457
Fold 4 IBS: 0.1535743087087913
Fold 5 IBS: 0.1956837311181241
[I 2024-04-16 01:07:55,720] Trial 29 finished with value: 0.1711444886228711 and parameters: {'l1_ratio': 0.7219658636811287}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.179699767669005
Fold 2 IBS: 0.15091326863770543
Fold 3 IBS: 0.17586130858806398
Fold 4 IBS: 0.15357404701499663
Fold 5 IBS: 0.1957342650905041
[I 2024-04-16 01:07:56,978] Trial 30 finished with value: 0.17115653140005502 and parameters: {'l1_ratio': 0.8087250707925157}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.17970975419924318
Fold 2 IBS: 0.1509200420349979
Fold 3 IBS: 0.17578423029720056
Fold 4 IBS: 0.15356432429185957
Fold 5 IBS: 0.19564396057318295
[I 2024-04-16 01:07:58,467] Trial 31 finished with value: 0.17112446227929684 and parameters: {'l1_ratio': 0.8344691515233844}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.17960636037220257
Fold 2 IBS: 0.1509432984895927
Fold 3 IBS: 0.175886474216777
Fold 4 IBS: 0.15359651583957928
Fold 5 IBS: 0.19565126515405587
[I 2024-04-16 01:07:59,921] Trial 32 finished with value: 0.1711367828144415 and parameters: {'l1_ratio': 0.6750821872293133}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.17974443808055873
Fold 2 IBS: 0.15086978953350666
Fold 3 IBS: 0.1757693504125137
Fold 4 IBS: 0.1535572698098275
Fold 5 IBS: 0.1956930205998604
[I 2024-04-16 01:08:01,749] Trial 33 finished with value: 0.1711267736872534 and parameters: {'l1_ratio': 0.9371865059078393}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.17963949925440945
Fold 2 IBS: 0.15089494466384265
Fold 3 IBS: 0.17587197748680342
Fold 4 IBS: 0.1535639900587707
Fold 5 IBS: 0.19569897539272063
[I 2024-04-16 01:08:03,154] Trial 34 finished with value: 0.1711338773713094 and parameters: {'l1_ratio': 0.7460166418323687}. Best is trial 27 with value: 0.17112406212568748.
Fold 1 IBS: 0.17970689864307565
Fold 2 IBS: 0.1509181053008999
Fold 3 IBS: 0.17578546464870717
Fold 4 IBS: 0.15356710112111874
Fold 5 IBS: 0.19563991562691402
[I 2024-04-16 01:08:04,430] Trial 35 finished with value: 0.1711234970681431 and parameters: {'l1_ratio': 0.8269524441171497}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17883454800376022
Fold 2 IBS: 0.15110901234043314
Fold 3 IBS: 0.1767003093668459
Fold 4 IBS: 0.15374746178466736
Fold 5 IBS: 0.19576962556800345
[I 2024-04-16 01:08:05,736] Trial 36 finished with value: 0.171232191412742 and parameters: {'l1_ratio': 0.07755657280239842}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17949685407310476
Fold 2 IBS: 0.15094868811850107
Fold 3 IBS: 0.17604521272106372
Fold 4 IBS: 0.1536076736599168
Fold 5 IBS: 0.19572865879532014
[I 2024-04-16 01:08:07,090] Trial 37 finished with value: 0.17116541747358133 and parameters: {'l1_ratio': 0.5263177327913215}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17970191722404322
Fold 2 IBS: 0.15091472659725963
Fold 3 IBS: 0.1757876213229113
Fold 4 IBS: 0.15357195151505323
Fold 5 IBS: 0.1957370637939949
[I 2024-04-16 01:08:08,013] Trial 38 finished with value: 0.17114265609065246 and parameters: {'l1_ratio': 0.814139656167237}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17928401748424794
Fold 2 IBS: 0.15100859166046193
Fold 3 IBS: 0.17625441482835508
Fold 4 IBS: 0.15366345782256746
Fold 5 IBS: 0.19575666742598227
[I 2024-04-16 01:08:09,244] Trial 39 finished with value: 0.17119342984432295 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17958887814242422
Fold 2 IBS: 0.15093111881901664
Fold 3 IBS: 0.17595788297398457
Fold 4 IBS: 0.1535764427603754
Fold 5 IBS: 0.1957300602694465
[I 2024-04-16 01:08:10,018] Trial 40 finished with value: 0.17115687659304948 and parameters: {'l1_ratio': 0.6422225235125675}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17974298495238897
Fold 2 IBS: 0.15086873116535146
Fold 3 IBS: 0.1757699696858603
Fold 4 IBS: 0.1535587918707696
Fold 5 IBS: 0.19569097791259693
[I 2024-04-16 01:08:10,805] Trial 41 finished with value: 0.17112629111739347 and parameters: {'l1_ratio': 0.9324088059231299}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17974403456639163
Fold 2 IBS: 0.15086949563405963
Fold 3 IBS: 0.17576952234036242
Fold 4 IBS: 0.15355769239250097
Fold 5 IBS: 0.19569245343623135
[I 2024-04-16 01:08:12,027] Trial 42 finished with value: 0.1711266396739092 and parameters: {'l1_ratio': 0.9358551685844427}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.1797469480158639
Fold 2 IBS: 0.150871617727353
Fold 3 IBS: 0.17576830753469674
Fold 4 IBS: 0.15355464252736944
Fold 5 IBS: 0.19569654737616812
[I 2024-04-16 01:08:13,762] Trial 43 finished with value: 0.17112761263629023 and parameters: {'l1_ratio': 0.9455487581117878}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17962789306586463
Fold 2 IBS: 0.15095814044880024
Fold 3 IBS: 0.1758770373451315
Fold 4 IBS: 0.1535753510243839
Fold 5 IBS: 0.19568220529230917
[I 2024-04-16 01:08:15,560] Trial 44 finished with value: 0.1711441254352979 and parameters: {'l1_ratio': 0.7196215885449297}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17905835623092686
Fold 2 IBS: 0.151028287344448
Fold 3 IBS: 0.17649215399462423
Fold 4 IBS: 0.15371570699475443
Fold 5 IBS: 0.19580462238841898
[I 2024-04-16 01:08:17,176] Trial 45 finished with value: 0.17121982539063452 and parameters: {'l1_ratio': 0.18074152502476082}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17970294994765124
Fold 2 IBS: 0.1509154270581908
Fold 3 IBS: 0.1757871738552715
Fold 4 IBS: 0.1535709452945764
Fold 5 IBS: 0.19573840789747182
[I 2024-04-16 01:08:18,148] Trial 46 finished with value: 0.17114298081063234 and parameters: {'l1_ratio': 0.8167652444349325}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.1797293338330422
Fold 2 IBS: 0.15093331619765588
Fold 3 IBS: 0.1757758049265232
Fold 4 IBS: 0.153545354971824
Fold 5 IBS: 0.19567162894943033
[I 2024-04-16 01:08:19,771] Trial 47 finished with value: 0.17113108777569513 and parameters: {'l1_ratio': 0.8896764455542575}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17975201961981013
Fold 2 IBS: 0.15087531220120756
Fold 3 IBS: 0.1757661510211417
Fold 4 IBS: 0.15355619591537467
Fold 5 IBS: 0.19570366789828117
[I 2024-04-16 01:08:20,623] Trial 48 finished with value: 0.17113066933116305 and parameters: {'l1_ratio': 0.9628835965862083}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17941790923879292
Fold 2 IBS: 0.1509703016616295
Fold 3 IBS: 0.17612160837733182
Fold 4 IBS: 0.15362853573435725
Fold 5 IBS: 0.1957383642793302
[I 2024-04-16 01:08:21,801] Trial 49 finished with value: 0.1711753438582883 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 35 with value: 0.1711234970681431.

Fold 1 IBS: 0.17970700862703434
Fold 2 IBS: 0.15091817989655337
Fold 3 IBS: 0.17578541708073786
Fold 4 IBS: 0.1535669941206311
Fold 5 IBS: 0.19564007146711287
[I 2024-04-16 01:08:23,244] Trial 50 finished with value: 0.17112353423841392 and parameters: {'l1_ratio': 0.827239601583696}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17970553221714716
Fold 2 IBS: 0.15091717852898873
Fold 3 IBS: 0.17578605580278628
Fold 4 IBS: 0.15356843080687638
Fold 5 IBS: 0.19574176735273358
[I 2024-04-16 01:08:24,653] Trial 51 finished with value: 0.17114379294170642 and parameters: {'l1_ratio': 0.8234003712590802}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17964176753949349
Fold 2 IBS: 0.15089662605437165
Fold 3 IBS: 0.17587099137263867
Fold 4 IBS: 0.15356177486974165
Fold 5 IBS: 0.19570222254923034
[I 2024-04-16 01:08:25,645] Trial 52 finished with value: 0.17113467647709518 and parameters: {'l1_ratio': 0.7513882197173816}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.1797190102468965
Fold 2 IBS: 0.1509263194748138
Fold 3 IBS: 0.17578023904371698
Fold 4 IBS: 0.15355534144255442
Fold 5 IBS: 0.19565705490763957
[I 2024-04-16 01:08:26,497] Trial 53 finished with value: 0.17112759302312427 and parameters: {'l1_ratio': 0.8597402337163358}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17973130137502696
Fold 2 IBS: 0.1509346504045331
Fold 3 IBS: 0.17577496192245848
Fold 4 IBS: 0.15354345553063709
Fold 5 IBS: 0.19567453120470416
[I 2024-04-16 01:08:27,724] Trial 54 finished with value: 0.17113178008747193 and parameters: {'l1_ratio': 0.895605757006741}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17965581771781747
Fold 2 IBS: 0.15090704355526582
Fold 3 IBS: 0.17586492915780905
Fold 4 IBS: 0.1535760799804213
Fold 5 IBS: 0.19572230050202957
[I 2024-04-16 01:08:28,685] Trial 55 finished with value: 0.17114523418266864 and parameters: {'l1_ratio': 0.7863472344357447}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17961846265905979
Fold 2 IBS: 0.15095165445365036
Fold 3 IBS: 0.1758811528603792
Fold 4 IBS: 0.15358458492310845
Fold 5 IBS: 0.1956686963973729
[I 2024-04-16 01:08:30,576] Trial 56 finished with value: 0.1711409102587141 and parameters: {'l1_ratio': 0.6994938590472165}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17972124319148963
Fold 2 IBS: 0.1509278337753742
Fold 3 IBS: 0.17577927840719446
Fold 4 IBS: 0.153553178533168
Fold 5 IBS: 0.1956602099167168
[I 2024-04-16 01:08:31,813] Trial 57 finished with value: 0.1711283487647886 and parameters: {'l1_ratio': 0.8660532692979819}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17975243867899596
Fold 2 IBS: 0.1508756174982223
Fold 3 IBS: 0.17576597302645036
Fold 4 IBS: 0.1535557535495056
Fold 5 IBS: 0.19570425591465818
[I 2024-04-16 01:08:32,615] Trial 58 finished with value: 0.17113080773356648 and parameters: {'l1_ratio': 0.9643428762229279}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.1797083766181721
Fold 2 IBS: 0.15091910771892775
Fold 3 IBS: 0.17578482560201963
Fold 4 IBS: 0.15356566356476123
Fold 5 IBS: 0.1956420095148066
[I 2024-04-16 01:08:33,479] Trial 59 finished with value: 0.17112399660373748 and parameters: {'l1_ratio': 0.8308269930274109}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17953361169683793
Fold 2 IBS: 0.15097836742410753
Fold 3 IBS: 0.1759709310102363
Fold 4 IBS: 0.15360571550462704
Fold 5 IBS: 0.1956869314262177
[I 2024-04-16 01:08:34,665] Trial 60 finished with value: 0.1711551114124053 and parameters: {'l1_ratio': 0.5892984254164416}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.1797080762201491
Fold 2 IBS: 0.15091890397872718
Fold 3 IBS: 0.17578495545724251
Fold 4 IBS: 0.1535659556905663
Fold 5 IBS: 0.19564158398652237
[I 2024-04-16 01:08:35,539] Trial 61 finished with value: 0.17112389506664147 and parameters: {'l1_ratio': 0.8300367366401068}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17970353136073453
Fold 2 IBS: 0.1509158214082163
Fold 3 IBS: 0.17578692201754342
Fold 4 IBS: 0.15357037895458978
Fold 5 IBS: 0.19573916447323259
[I 2024-04-16 01:08:36,394] Trial 62 finished with value: 0.17114316364286333 and parameters: {'l1_ratio': 0.8182504190706277}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17963755062635436
Fold 2 IBS: 0.15089350031961346
Fold 3 IBS: 0.17587282535648027
Fold 4 IBS: 0.15356589442004343
Fold 5 IBS: 0.19569605570468104
[I 2024-04-16 01:08:37,311] Trial 63 finished with value: 0.1711331652854345 and parameters: {'l1_ratio': 0.7414592443665516}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17965159958541957
Fold 2 IBS: 0.1509039155480474
Fold 3 IBS: 0.17586675340722038
Fold 4 IBS: 0.15358054733689877
Fold 5 IBS: 0.19571627912912473
[I 2024-04-16 01:08:38,106] Trial 64 finished with value: 0.17114381900134218 and parameters: {'l1_ratio': 0.7755354824895868}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17971168457678055
Fold 2 IBS: 0.15092135125585346
Fold 3 IBS: 0.1757833966769735
Fold 4 IBS: 0.15356244862430007
Fold 5 IBS: 0.19564669358260336
[I 2024-04-16 01:08:39,393] Trial 65 finished with value: 0.17112511494330218 and parameters: {'l1_ratio': 0.8396235458234331}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17961274518682058
Fold 2 IBS: 0.15094770698267385
Fold 3 IBS: 0.17588366354666812
Fold 4 IBS: 0.15359021550094915
Fold 5 IBS: 0.19566046695839845
[I 2024-04-16 01:08:40,558] Trial 66 finished with value: 0.17113895963510203 and parameters: {'l1_ratio': 0.6877594268728628}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17971138642557857
Fold 2 IBS: 0.15092114904510287
Fold 3 IBS: 0.17578352538918163
Fold 4 IBS: 0.15356273824702163
Fold 5 IBS: 0.19564627153701536
[I 2024-04-16 01:08:41,442] Trial 67 finished with value: 0.17112501412878003 and parameters: {'l1_ratio': 0.8388235384359204}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.1796592101835533
Fold 2 IBS: 0.15090955494460534
Fold 3 IBS: 0.17586346692851784
Fold 4 IBS: 0.1535793911741006
Fold 5 IBS: 0.195727130369868
[I 2024-04-16 01:08:42,375] Trial 68 finished with value: 0.17114775072012903 and parameters: {'l1_ratio': 0.7952338956042287}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17973742201019563
Fold 2 IBS: 0.15093880069128737
Fold 3 IBS: 0.17577234374681838
Fold 4 IBS: 0.1535646254613038
Fold 5 IBS: 0.19568315220822025
[I 2024-04-16 01:08:43,156] Trial 69 finished with value: 0.17113926882356506 and parameters: {'l1_ratio': 0.9145364177010361}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.1797249623211959
Fold 2 IBS: 0.15093035174732894
Fold 3 IBS: 0.1757776803067072
Fold 4 IBS: 0.15354957958361237
Fold 5 IBS: 0.19566546147880157
[I 2024-04-16 01:08:44,488] Trial 70 finished with value: 0.1711296070875292 and parameters: {'l1_ratio': 0.876763912674587}. Best is trial 35 with value: 0.1711234970681431.
Fold 1 IBS: 0.17970617040278564
Fold 2 IBS: 0.15091761137664553
Fold 3 IBS: 0.17578577966526995
Fold 4 IBS: 0.15356780970550454
Fold 5 IBS: 0.1956388836642709
[I 2024-04-16 01:08:45,576] Trial 71 finished with value: 0.17112325096289532 and parameters: {'l1_ratio': 0.8250557880797453}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17964729440682453
Fold 2 IBS: 0.150900723407571
Fold 3 IBS: 0.1758685924058767
Fold 4 IBS: 0.1535851134314047
Fold 5 IBS: 0.19571012783031155
[I 2024-04-16 01:08:46,591] Trial 72 finished with value: 0.17114237029639773 and parameters: {'l1_ratio': 0.7647852367906859}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17970975941810197
Fold 2 IBS: 0.15092004557456137
Fold 3 IBS: 0.17578422804259802
Fold 4 IBS: 0.15356431921929242
Fold 5 IBS: 0.19564396796351832
[I 2024-04-16 01:08:47,728] Trial 73 finished with value: 0.17112446404361442 and parameters: {'l1_ratio': 0.834483006535406}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17965696549413354
Fold 2 IBS: 0.15090789477193178
Fold 3 IBS: 0.17586443330610374
Fold 4 IBS: 0.15357486597573713
Fold 5 IBS: 0.19572393800023064
[I 2024-04-16 01:08:49,216] Trial 74 finished with value: 0.17114561950962734 and parameters: {'l1_ratio': 0.7893383827710738}. Best is trial 71 with value: 0.17112325096289532.

Fold 1 IBS: 0.179629267151078
Fold 2 IBS: 0.150959089149268
Fold 3 IBS: 0.17587643706925069
Fold 4 IBS: 0.15357400365471247
Fold 5 IBS: 0.1956841777174661
[I 2024-04-16 01:08:50,744] Trial 75 finished with value: 0.17114459494835504 and parameters: {'l1_ratio': 0.7226548259502308}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17959734661613208
Fold 2 IBS: 0.15093707446029403
Fold 3 IBS: 0.1759544122469034
Fold 4 IBS: 0.15359845573489758
Fold 5 IBS: 0.19574151389648767
[I 2024-04-16 01:08:52,156] Trial 76 finished with value: 0.17116576059094296 and parameters: {'l1_ratio': 0.6579092078440976}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.1797286640165961
Fold 2 IBS: 0.1509328619835906
Fold 3 IBS: 0.17577609206475558
Fold 4 IBS: 0.15354600188520437
Fold 5 IBS: 0.1956706843309654
[I 2024-04-16 01:08:53,954] Trial 77 finished with value: 0.17113086085622245 and parameters: {'l1_ratio': 0.8876747639518479}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.1797390112158137
Fold 2 IBS: 0.150939878259037
Fold 3 IBS: 0.17577166499299732
Fold 4 IBS: 0.15356295784302912
Fold 5 IBS: 0.1956853887914077
[I 2024-04-16 01:08:55,401] Trial 78 finished with value: 0.17113978022045698 and parameters: {'l1_ratio': 0.9195757437000658}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17970963976964466
Fold 2 IBS: 0.15091996442587924
Fold 3 IBS: 0.17578427973319527
Fold 4 IBS: 0.15356443551605228
Fold 5 IBS: 0.19564379852932906
[I 2024-04-16 01:08:56,791] Trial 79 finished with value: 0.17112442359482008 and parameters: {'l1_ratio': 0.8341654726402552}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17976065385809092
Fold 2 IBS: 0.15088160327954145
Fold 3 IBS: 0.17576248963295257
Fold 4 IBS: 0.1535470934108467
Fold 5 IBS: 0.1957157727948005
[I 2024-04-16 01:08:58,187] Trial 80 finished with value: 0.17113352259524645 and parameters: {'l1_ratio': 0.9938206208624321}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17970958038969112
Fold 2 IBS: 0.15091992415282687
Fold 3 IBS: 0.17578430538748355
Fold 4 IBS: 0.15356449323431687
Fold 5 IBS: 0.19564371443975592
[I 2024-04-16 01:08:59,654] Trial 81 finished with value: 0.17112440352081487 and parameters: {'l1_ratio': 0.8340079689561077}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17971939480961233
Fold 2 IBS: 0.15092658027371136
Fold 3 IBS: 0.1757800735389801
Fold 4 IBS: 0.1535549688270078
Fold 5 IBS: 0.1956575983787933
[I 2024-04-16 01:09:01,120] Trial 82 finished with value: 0.17112772316562097 and parameters: {'l1_ratio': 0.8608213010312128}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17969751722716407
Fold 2 IBS: 0.15091174219618753
Fold 3 IBS: 0.17586219516746007
Fold 4 IBS: 0.1535762424731582
Fold 5 IBS: 0.19573133358975486
[I 2024-04-16 01:09:02,621] Trial 83 finished with value: 0.17115580613074494 and parameters: {'l1_ratio': 0.8031282090286125}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17963569930175838
Fold 2 IBS: 0.15089212818145414
Fold 3 IBS: 0.17587363150834606
Fold 4 IBS: 0.15356770484299923
Fold 5 IBS: 0.19569340287756842
[I 2024-04-16 01:09:04,512] Trial 84 finished with value: 0.17113251334242524 and parameters: {'l1_ratio': 0.7371775125562481}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17972962460276112
Fold 2 IBS: 0.15093351337268565
Fold 3 IBS: 0.17577568030278748
Fold 4 IBS: 0.15354507418880778
Fold 5 IBS: 0.19567203896970523
[I 2024-04-16 01:09:06,121] Trial 85 finished with value: 0.17113118628734944 and parameters: {'l1_ratio': 0.8905480330433497}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17964793104031793
Fold 2 IBS: 0.150901195422438
Fold 3 IBS: 0.17586831641557005
Fold 4 IBS: 0.15358443779702638
Fold 5 IBS: 0.19571103782236196
[I 2024-04-16 01:09:07,732] Trial 86 finished with value: 0.17114258369954286 and parameters: {'l1_ratio': 0.7663572605921825}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17971004787510336
Fold 2 IBS: 0.15092024121323705
Fold 3 IBS: 0.17578410343348178
Fold 4 IBS: 0.15356403886178152
Fold 5 IBS: 0.19564437642960358
[I 2024-04-16 01:09:08,929] Trial 87 finished with value: 0.17112456156264147 and parameters: {'l1_ratio': 0.8352494735865839}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17975278900216188
Fold 2 IBS: 0.15087587272200345
Fold 3 IBS: 0.17576582425006532
Fold 4 IBS: 0.15355538378812775
Fold 5 IBS: 0.195704747441871
[I 2024-04-16 01:09:10,336] Trial 88 finished with value: 0.17113092344084588 and parameters: {'l1_ratio': 0.9655660156128469}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17970057008346144
Fold 2 IBS: 0.15091381289732494
Fold 3 IBS: 0.17578820530453548
Fold 4 IBS: 0.15357326460348847
Fold 5 IBS: 0.19573530999041602
[I 2024-04-16 01:09:11,636] Trial 89 finished with value: 0.17114223257584524 and parameters: {'l1_ratio': 0.8107383857357953}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17933154819371308
Fold 2 IBS: 0.1509787302414166
Fold 3 IBS: 0.1761978799954605
Fold 4 IBS: 0.15366210920711088
Fold 5 IBS: 0.19572544604467168
[I 2024-04-16 01:09:13,079] Trial 90 finished with value: 0.17117914273647455 and parameters: {'l1_ratio': 0.37119075933326773}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17971136504703403
Fold 2 IBS: 0.1509211345458242
Fold 3 IBS: 0.17578353461891716
Fold 4 IBS: 0.15356275901514263
Fold 5 IBS: 0.19564624127374733
[I 2024-04-16 01:09:14,260] Trial 91 finished with value: 0.17112500690013305 and parameters: {'l1_ratio': 0.8387662299470229}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17972431281609053
Fold 2 IBS: 0.15092991128833694
Fold 3 IBS: 0.17577795922541595
Fold 4 IBS: 0.15355020778232487
Fold 5 IBS: 0.1956645446519202
[I 2024-04-16 01:09:15,430] Trial 92 finished with value: 0.1711293871528177 and parameters: {'l1_ratio': 0.8748754886204533}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17965717372457896
Fold 2 IBS: 0.1509080492034556
Fold 3 IBS: 0.17586434337286896
Fold 4 IBS: 0.15357464569130916
Fold 5 IBS: 0.1957242350329078
[I 2024-04-16 01:09:17,111] Trial 93 finished with value: 0.17114568940502412 and parameters: {'l1_ratio': 0.7898833346735545}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17973580362679267
Fold 2 IBS: 0.1509377033212329
Fold 3 IBS: 0.17577303540614952
Fold 4 IBS: 0.15353911373182771
Fold 5 IBS: 0.1956808737842103
[I 2024-04-16 01:09:18,545] Trial 94 finished with value: 0.1711333059740426 and parameters: {'l1_ratio': 0.9094578869039874}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17970696096390118
Fold 2 IBS: 0.15091814756946048
Fold 3 IBS: 0.17578543769474358
Fold 4 IBS: 0.15356704049035408
Fold 5 IBS: 0.19564000393196979
[I 2024-04-16 01:09:19,448] Trial 95 finished with value: 0.1711235181300858 and parameters: {'l1_ratio': 0.8271151347909186}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17962256890797412
Fold 2 IBS: 0.15095448936618563
Fold 3 IBS: 0.1758793533068096
Fold 4 IBS: 0.1535805480355515
Fold 5 IBS: 0.19567460036877837
[I 2024-04-16 01:09:20,758] Trial 96 finished with value: 0.17114231199705982 and parameters: {'l1_ratio': 0.7081544473819479}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17913822899218423
Fold 2 IBS: 0.15101231282216634
Fold 3 IBS: 0.17640275988599954
Fold 4 IBS: 0.15368184041766372
Fold 5 IBS: 0.19571871641067426
[I 2024-04-16 01:09:21,771] Trial 97 finished with value: 0.17119077170573763 and parameters: {'l1_ratio': 0.2367441530189508}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17972093029473668
Fold 2 IBS: 0.15092762158181539
Fold 3 IBS: 0.1757794129670272
Fold 4 IBS: 0.1535534815205097
Fold 5 IBS: 0.19565976790340728
[I 2024-04-16 01:09:23,461] Trial 98 finished with value: 0.17112824285349926 and parameters: {'l1_ratio': 0.8651633904001758}. Best is trial 71 with value: 0.17112325096289532.
Fold 1 IBS: 0.17964851843646337
Fold 2 IBS: 0.15090163093985967
Fold 3 IBS: 0.1758680618333235
Fold 4 IBS: 0.15358381454499664

Fold 5 IBS: 0.19571187732417217
[I 2024-04-16 01:09:26,039] Trial 99 finished with value: 0.1711427806157631 and parameters: {'l1_ratio': 0.7678130961399826}. Best is trial 71 with value: 0.17112325096289532.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.17112325096289532], datetime_start=datetime.datetime(2024, 4, 16, 1, 8, 44, 496390), datetime_complete=datetime.datetime(2024, 4, 16, 1, 8, 45, 575037), params={'l1_ratio': 0.8250557880797453}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.17112325096289532

In [42]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.738
train_ibs:  0.171

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.5513596376059829)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.8250557880797453)

test_ibs:  0.257

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:09:27,246] A new study created in memory with name: no-name-5c721061-1922-4a49-a853-bae192e24925

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:09:39,113] Trial 0 finished with value: 0.7575203363732566 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:09:48,459] Trial 1 finished with value: 0.750478431579118 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:09:56,551] Trial 2 finished with value: 0.7520712510356254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:09:58,899] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:10:04,405] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:10:14,991] Trial 5 finished with value: 0.7462602486577217 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:10:25,848] Trial 6 finished with value: 0.7576976783760393 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:10:30,418] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 01:10:52,156] Trial 8 finished with value: 0.5380281690140845 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:11:04,500] Trial 9 finished with value: 0.748452073539184 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:11:05,658] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.40740851493126695, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:11:19,549] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.11379276107227315, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:11:35,554] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:11:39,566] Trial 13 finished with value: 0.7581182539062076 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 13 with value: 0.7581182539062076.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:11:41,749] Trial 14 finished with value: 0.7907144637948861 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0992244164616675, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:11:43,448] Trial 15 finished with value: 0.7816150812624114 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.8147833133306369, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:11:43,852] Trial 16 finished with value: 0.765813594477808 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.8484814588885312, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08082385841318356, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:11:46,099] Trial 17 finished with value: 0.7851258260885514 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16544550098450153, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:11:47,732] Trial 18 finished with value: 0.7834440402483949 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13294582901895255, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:11:50,471] Trial 19 finished with value: 0.7742809868075984 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9945705745432233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09964492104707659, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:11:51,980] Trial 20 finished with value: 0.7628622503029641 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.8673418291441284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37827446502466894, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:11:54,349] Trial 21 finished with value: 0.7872501961326841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.9624638447657676, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.8051643192488263
[I 2024-04-16 01:11:54,864] Trial 22 finished with value: 0.7873570802451841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.9336744347879812, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19282610776605333, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7488262910798122
[I 2024-04-16 01:11:55,335] Trial 23 finished with value: 0.7541962121280221 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.6843026151576985, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2504370920378234, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:11:56,537] Trial 24 finished with value: 0.7858778057568998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 50, 'oob_score': True, 'max_samples': 0.8085053499703132, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17035312846001988, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:11:59,675] Trial 25 finished with value: 0.7899316539935477 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.9171920870810285, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07664126778540013, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:12:02,178] Trial 26 finished with value: 0.7817663440763265 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.8983378428295576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06306617081281016, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:12:05,240] Trial 27 finished with value: 0.7856141531151757 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.7989579262543244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09596584472346859, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:12:08,108] Trial 28 finished with value: 0.7853982513847043 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.5360953547457009, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014347840876196644, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:12:08,966] Trial 29 finished with value: 0.7695772354631409 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.6977978899499365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2196223213316708, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:12:10,071] Trial 30 finished with value: 0.7981448890436417 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 82, 'oob_score': True, 'max_samples': 0.7311645169232817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.059569167808063095, 'warm_start': True}. Best is trial 30 with value: 0.7981448890436417.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:12:11,078] Trial 31 finished with value: 0.7982641653072841 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.745146001885883, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05174429879930956, 'warm_start': True}. Best is trial 31 with value: 0.7982641653072841.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7742616033755274
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:12:12,155] Trial 32 finished with value: 0.8032544311992128 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.7397628776532771, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04641084093066284, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:12:13,358] Trial 33 finished with value: 0.7999277380363321 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.7321956680996766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0042513284435347215, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 01:12:14,476] Trial 34 finished with value: 0.7980620370159766 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 74, 'oob_score': True, 'max_samples': 0.7190350277691129, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002617826444773601, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:12:15,433] Trial 35 finished with value: 0.8195885025512174 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.6491391650041388, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04473837361201603, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:12:16,905] Trial 36 finished with value: 0.8149421898615685 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6500614805101094, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.042163225365865975, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:12:18,533] Trial 37 finished with value: 0.8201548198575692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.6316988824284715, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03372830367211485, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:12:20,162] Trial 38 finished with value: 0.7864200685622795 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6475925530300135, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1261541633669147, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 01:12:21,927] Trial 39 finished with value: 0.7994601394099836 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.5500795764120797, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0407216828679674, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:12:24,451] Trial 40 finished with value: 0.8144744547521597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.5974594004293988, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03731085344043298, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:12:26,220] Trial 41 finished with value: 0.8146670383091891 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.5688957234666421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.038323603584419504, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:12:28,393] Trial 42 finished with value: 0.8217769675659046 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.565436601526051, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03253349071458341, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:12:30,434] Trial 43 finished with value: 0.8194179790264864 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.5414105158165579, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02824952898790397, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:12:32,361] Trial 44 finished with value: 0.7844759249669818 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.4812619709263958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0734121445676241, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:12:34,684] Trial 45 finished with value: 0.7812420451089397 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.4132359110524421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10574093555624242, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:12:40,285] Trial 46 finished with value: 0.742796454430003 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 277, 'oob_score': False, 'max_samples': 0.6435530257070258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02588599089196765, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:12:42,122] Trial 47 finished with value: 0.8020413535841735 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.513428105668999, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005073560345181239, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:12:48,130] Trial 48 finished with value: 0.7605416340753064 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.4250487747986099, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07826456635516901, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:12:51,116] Trial 49 finished with value: 0.7646180284055469 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.3288612699820465, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11977607788857622, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 01:12:54,020] Trial 50 finished with value: 0.7516085439508142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.6056621314066971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27891660351802283, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:12:56,512] Trial 51 finished with value: 0.8156329206993581 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.5653247525904954, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024675273648228607, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:12:59,366] Trial 52 finished with value: 0.8105679483498613 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.668807800129283, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023886857070088842, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:13:03,244] Trial 53 finished with value: 0.8092844755529726 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.5049892673780266, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0302062450326431, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:13:06,451] Trial 54 finished with value: 0.7837218500992189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 223, 'oob_score': False, 'max_samples': 0.5694355594036941, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08503386755881623, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:13:09,212] Trial 55 finished with value: 0.8023260161047514 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.6230580876154783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06106714571926695, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:13:19,541] Trial 56 finished with value: 0.7505163979885541 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.37386377532060755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020276597591653404, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 01:13:21,855] Trial 57 finished with value: 0.7370660000414045 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 265, 'oob_score': False, 'max_samples': 0.673626054002652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.32552397591019333, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:13:24,370] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.5859997242165991, 'max_features': None, 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:13:26,774] Trial 59 finished with value: 0.7738001567018483 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.4578032212133656, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14288340865089383, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:13:37,162] Trial 60 finished with value: 0.7576418826254305 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.5248616932098589, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09178626486905285, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:13:41,211] Trial 61 finished with value: 0.8121405300073643 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.5673407402421513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04324260858798204, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:13:44,200] Trial 62 finished with value: 0.8048963624250977 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.6136771186690915, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.061141393518585746, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:13:47,084] Trial 63 finished with value: 0.8129059673027221 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.5632723911430406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03896879562886681, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:13:51,910] Trial 64 finished with value: 0.8200972064136438 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.4849644523201697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015459623887936643, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:13:55,338] Trial 65 finished with value: 0.8200556403698938 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.4915234805630325, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01325985667696578, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:13:57,824] Trial 66 finished with value: 0.7991290530701981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.44421584072665865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01688809895377827, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:14:01,687] Trial 67 finished with value: 0.8455736642377335 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 01:14:07,746] Trial 68 finished with value: 0.8406053556611222 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'max_samples': 0.49738412507640734, 'max_features': None, 'min_weight_fraction_leaf': 0.002433553898016293, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:14:11,963] Trial 69 finished with value: 0.8316567836473476 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.38288786338976266, 'max_features': None, 'min_weight_fraction_leaf': 0.010924103557748996, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:14:15,885] Trial 70 finished with value: 0.8325253087831349 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.3768797583243322, 'max_features': None, 'min_weight_fraction_leaf': 0.007358190561024822, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:14:19,275] Trial 71 finished with value: 0.8074401022098655 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.2977376592001145, 'max_features': None, 'min_weight_fraction_leaf': 0.007777034521166985, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:14:24,060] Trial 72 finished with value: 0.8207621073356813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3758248033560092, 'max_features': None, 'min_weight_fraction_leaf': 0.0021403509786410697, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:14:29,411] Trial 73 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.37703659520841803, 'max_features': None, 'min_weight_fraction_leaf': 0.0030355880739053242, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:14:35,192] Trial 74 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.37759120849945615, 'max_features': None, 'min_weight_fraction_leaf': 0.005738060589732854, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:14:39,678] Trial 75 finished with value: 0.8064988630989438 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3512499599110515, 'max_features': None, 'min_weight_fraction_leaf': 0.0016091095350437782, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:14:44,780] Trial 76 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.2200825864677213, 'max_features': None, 'min_weight_fraction_leaf': 0.3808353622830714, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:14:50,508] Trial 77 finished with value: 0.7898601663797173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.38697496089808264, 'max_features': None, 'min_weight_fraction_leaf': 0.0678874889911297, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:14:55,964] Trial 78 finished with value: 0.7983796631750157 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.2971389951907717, 'max_features': None, 'min_weight_fraction_leaf': 0.0014283193772283813, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:15:01,832] Trial 79 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.3832306547359522, 'max_features': None, 'min_weight_fraction_leaf': 0.001325860823554314, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:15:24,151] Trial 80 finished with value: 0.7638486802036979 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.2259926589326255, 'max_features': None, 'min_weight_fraction_leaf': 0.051988057609908274, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:15:30,461] Trial 81 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.3902826764643792, 'max_features': None, 'min_weight_fraction_leaf': 0.01424010512203431, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:15:37,075] Trial 82 finished with value: 0.8037666314114749 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.35665467332899853, 'max_features': None, 'min_weight_fraction_leaf': 0.02723621966149422, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:15:41,690] Trial 83 finished with value: 0.7910748783864995 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.27364682713049737, 'max_features': None, 'min_weight_fraction_leaf': 0.003437924737021262, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 01:15:46,536] Trial 84 finished with value: 0.7981013668372744 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.42217891643501637, 'max_features': None, 'min_weight_fraction_leaf': 0.05691895142137581, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:15:50,607] Trial 85 finished with value: 0.8142696016233687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.44215445453616553, 'max_features': None, 'min_weight_fraction_leaf': 0.015948474032128478, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:15:55,939] Trial 86 finished with value: 0.8039740360073753 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 467, 'oob_score': False, 'max_samples': 0.34536985759892425, 'max_features': None, 'min_weight_fraction_leaf': 0.03379453130696234, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:16:01,668] Trial 87 finished with value: 0.8009672435320422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3948765985014735, 'max_features': None, 'min_weight_fraction_leaf': 0.049452906101561514, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:16:08,141] Trial 88 finished with value: 0.7958162763557586 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.3168310392190445, 'max_features': None, 'min_weight_fraction_leaf': 0.011197201541028177, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:16:13,201] Trial 89 finished with value: 0.8188472945459484 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.46056239467229443, 'max_features': None, 'min_weight_fraction_leaf': 0.02927897429150622, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:16:20,483] Trial 90 finished with value: 0.8280743039205017 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3677724129924504, 'max_features': None, 'min_weight_fraction_leaf': 0.0015288688784384722, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:16:27,436] Trial 91 finished with value: 0.8315449166262722 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.37527324355860175, 'max_features': None, 'min_weight_fraction_leaf': 0.00032873883511814225, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:16:34,722] Trial 92 finished with value: 0.8152302082764418 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.36969362389667315, 'max_features': None, 'min_weight_fraction_leaf': 0.020344390663164187, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:16:41,749] Trial 93 finished with value: 0.8013473051581448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.3234854377137636, 'max_features': None, 'min_weight_fraction_leaf': 0.034235535617443455, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:16:48,718] Trial 94 finished with value: 0.8317597304647398 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.40292152817878885, 'max_features': None, 'min_weight_fraction_leaf': 0.0013715257783006587, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:16:57,751] Trial 95 finished with value: 0.8054182483946754 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.43651122516239244, 'max_features': None, 'min_weight_fraction_leaf': 0.0516435889873805, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:17:04,819] Trial 96 finished with value: 0.781897576085816 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.40560294670004454, 'max_features': None, 'min_weight_fraction_leaf': 0.0001044161694674754, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:17:10,173] Trial 97 finished with value: 0.8076329995928095 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.33588267636278435, 'max_features': None, 'min_weight_fraction_leaf': 0.019808016366776694, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:17:26,530] Trial 98 finished with value: 0.7563224015679627 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.4120109800767605, 'max_features': None, 'min_weight_fraction_leaf': 0.0696147483073608, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:17:31,282] Trial 99 finished with value: 0.81879604728486 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.4642145775222535, 'max_features': None, 'min_weight_fraction_leaf': 0.04423293101031651, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.


* Best trial for C-index:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.8455736642377335], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 57, 882458), datetime_complete=datetime.datetime(2024, 4, 16, 1, 14, 1, 686814), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=67, value=None)


* Best Score for C-index:
 0.8455736642377335

[I 2024-04-16 01:17:31,316] A new study created in memory with name: no-name-2685266c-03f8-44fb-83d2-2dc3b95d1f9e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16912942286746
Fold 2 IBS: 0.15736700168879125
Fold 3 IBS: 0.17596810644035646
Fold 4 IBS: 0.21476462245142444
Fold 5 IBS: 0.18140709105634753
[I 2024-04-16 01:17:53,560] Trial 0 finished with value: 0.17972724890087594 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.17972724890087594.
Fold 1 IBS: 0.1695457408702072
Fold 2 IBS: 0.15431589011481192
Fold 3 IBS: 0.17931251537071569
Fold 4 IBS: 0.19778743079510175
Fold 5 IBS: 0.1838708756319808
[I 2024-04-16 01:18:00,303] Trial 1 finished with value: 0.1769664905565635 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-16 01:18:06,966] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-16 01:18:23,790] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-16 01:18:38,479] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.18261661077179908
Fold 2 IBS: 0.14215438755582593
Fold 3 IBS: 0.19825307809201306
Fold 4 IBS: 0.1894541695729735
Fold 5 IBS: 0.17258301646825175
[I 2024-04-16 01:18:53,486] Trial 5 finished with value: 0.17701225249217267 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.1793072949109339
Fold 2 IBS: 0.17146943238736864
Fold 3 IBS: 0.1801865051168754
Fold 4 IBS: 0.2169078691801737
Fold 5 IBS: 0.1927889640697635
[I 2024-04-16 01:19:10,383] Trial 6 finished with value: 0.18813201313302302 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.20628331122669447
Fold 2 IBS: 0.20810768242984765
Fold 3 IBS: 0.196178000210441
Fold 4 IBS: 0.21720909429106852
Fold 5 IBS: 0.2120048382129915
[I 2024-04-16 01:19:30,277] Trial 7 finished with value: 0.2079565852742086 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-16 01:19:58,633] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17251108291109596
Fold 2 IBS: 0.16372104609445076
Fold 3 IBS: 0.1752499545194017
Fold 4 IBS: 0.19923941269775702
Fold 5 IBS: 0.1807428948937162
[I 2024-04-16 01:20:06,250] Trial 9 finished with value: 0.17829287822328432 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2138914608019449
Fold 2 IBS: 0.22021134435777845
Fold 3 IBS: 0.20482550997958907
Fold 4 IBS: 0.22548051560881624
Fold 5 IBS: 0.21733795012904839
[I 2024-04-16 01:20:17,266] Trial 10 finished with value: 0.2163493561754354 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17089799911696577
Fold 2 IBS: 0.1343759168934981
Fold 3 IBS: 0.18019414575478068
Fold 4 IBS: 0.19691489378360008
Fold 5 IBS: 0.17134875048281803
[I 2024-04-16 01:20:18,065] Trial 11 finished with value: 0.17074634120633253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1938573372077058
Fold 2 IBS: 0.15264524705837576
Fold 3 IBS: 0.1835875292339129
Fold 4 IBS: 0.19186721611439267
Fold 5 IBS: 0.17242006747034438
[I 2024-04-16 01:20:20,319] Trial 12 finished with value: 0.17887547941694631 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.7748822387405266, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020197386275102834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1753396733634442
Fold 2 IBS: 0.14659590196214217
Fold 3 IBS: 0.18564941996432435
Fold 4 IBS: 0.19697957764971377
Fold 5 IBS: 0.1760898132139911
[I 2024-04-16 01:20:28,791] Trial 13 finished with value: 0.17613087723072313 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 110, 'oob_score': False, 'max_samples': 0.9282504676473301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18437150857335638
Fold 2 IBS: 0.13940627158607374
Fold 3 IBS: 0.19735408203235827
Fold 4 IBS: 0.19502160042084687
Fold 5 IBS: 0.17327657876201488
[I 2024-04-16 01:20:39,313] Trial 14 finished with value: 0.17788600827493004 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.9418551640023243, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1903120334095733
Fold 2 IBS: 0.13604392965192902
Fold 3 IBS: 0.20770281014511405
Fold 4 IBS: 0.21649791040859048
Fold 5 IBS: 0.17399213158709487
[I 2024-04-16 01:20:40,329] Trial 15 finished with value: 0.18490976304046036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.9969315225031997, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10400906232299456}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.17234717281067394
Fold 2 IBS: 0.168695961879054
Fold 3 IBS: 0.17428134482390595
Fold 4 IBS: 0.20512326820357737
Fold 5 IBS: 0.1858777602458117
[I 2024-04-16 01:20:45,350] Trial 16 finished with value: 0.1812651015926046 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.8254434867518305, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27558800117237026}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1701072167867666
Fold 2 IBS: 0.15066297678714172
Fold 3 IBS: 0.18453320195882447
Fold 4 IBS: 0.19299945063741186
Fold 5 IBS: 0.17720564069954053
[I 2024-04-16 01:21:20,261] Trial 17 finished with value: 0.17510169737393705 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.7509985501856506, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0026257659295356476}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18294194940487038
Fold 2 IBS: 0.14058077366331193
Fold 3 IBS: 0.19786106053237812
Fold 4 IBS: 0.19006278490632897
Fold 5 IBS: 0.17207512016650234
[I 2024-04-16 01:21:50,536] Trial 18 finished with value: 0.17670433773467834 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16955416166590404
Fold 2 IBS: 0.15212211732759853
Fold 3 IBS: 0.18191729427832115
Fold 4 IBS: 0.1920689530206985
Fold 5 IBS: 0.1791048456801592
[I 2024-04-16 01:22:15,281] Trial 19 finished with value: 0.1749534743945363 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6173177066935658, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1243900714081905}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17714686876701324
Fold 2 IBS: 0.16932933496556507
Fold 3 IBS: 0.17717541750009574
Fold 4 IBS: 0.19713572873566637
Fold 5 IBS: 0.1888282875493155
[I 2024-04-16 01:22:30,462] Trial 20 finished with value: 0.18192312750353118 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.3628004877999946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13255231046532823}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16913535340838307
Fold 2 IBS: 0.15272782624748996
Fold 3 IBS: 0.18157422278730082
Fold 4 IBS: 0.19159866778115425
Fold 5 IBS: 0.18035473161483767
[I 2024-04-16 01:22:50,894] Trial 21 finished with value: 0.17507816036783316 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6011378896362364, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04460079180106673}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17030810384993947
Fold 2 IBS: 0.15141739726332304
Fold 3 IBS: 0.18252438545010272
Fold 4 IBS: 0.19011356122343498
Fold 5 IBS: 0.178289463693237
[I 2024-04-16 01:23:21,572] Trial 22 finished with value: 0.17453058229600743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.6303687757401123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10192378722318633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17546673577503152
Fold 2 IBS: 0.15775731851311675
Fold 3 IBS: 0.1781524236691594
Fold 4 IBS: 0.18862200168076865
Fold 5 IBS: 0.1781929228483396
[I 2024-04-16 01:23:49,804] Trial 23 finished with value: 0.1756382804972832 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.47299192016675806, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11363003519604899}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17094376831357636
Fold 2 IBS: 0.1646895387119759
Fold 3 IBS: 0.1747842391429866
Fold 4 IBS: 0.19494361629603088
Fold 5 IBS: 0.1866353242437713
[I 2024-04-16 01:24:11,539] Trial 24 finished with value: 0.1783992973416682 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 20, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.6280222894166756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17647963073148}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16901499831887323
Fold 2 IBS: 0.1608317214516487
Fold 3 IBS: 0.1762379772561786
Fold 4 IBS: 0.19348054932052614
Fold 5 IBS: 0.18439435643852217
[I 2024-04-16 01:24:36,455] Trial 25 finished with value: 0.1767919205571498 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.4737896318177208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09514387992502697}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16929634538840924
Fold 2 IBS: 0.15790827738905253
Fold 3 IBS: 0.17685741513951483
Fold 4 IBS: 0.1967559497411602
Fold 5 IBS: 0.185385205701487
[I 2024-04-16 01:25:02,755] Trial 26 finished with value: 0.17724063867192474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.8171469856554013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23317683759042168}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17086891563968248
Fold 2 IBS: 0.1631508903913892
Fold 3 IBS: 0.17528408462417908
Fold 4 IBS: 0.19656070086825392
Fold 5 IBS: 0.1871180876095544
[I 2024-04-16 01:25:24,245] Trial 27 finished with value: 0.1785965358266118 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.69231778632942, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05016618054550538}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21403025999388117
Fold 2 IBS: 0.22062977018591617
Fold 3 IBS: 0.20516689505844507
Fold 4 IBS: 0.22458172975885837
Fold 5 IBS: 0.21781943709735221
[I 2024-04-16 01:25:33,205] Trial 28 finished with value: 0.21644561841889062 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.26154064534881144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1313308679038699}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1728058934917983
Fold 2 IBS: 0.16613273087140148
Fold 3 IBS: 0.1752425051862629
Fold 4 IBS: 0.19545037913945612
Fold 5 IBS: 0.18577836193667824
[I 2024-04-16 01:25:46,365] Trial 29 finished with value: 0.17908197412511942 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.590452735593326, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1894700331250358}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18009129126221046
Fold 2 IBS: 0.16991867934953306
Fold 3 IBS: 0.18118166421743642
Fold 4 IBS: 0.21329354235589876
Fold 5 IBS: 0.19503330809108468
[I 2024-04-16 01:25:58,955] Trial 30 finished with value: 0.18790369705523266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.2125304486051036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17449717368418352
Fold 2 IBS: 0.15873065763573396
Fold 3 IBS: 0.17799356833494584
Fold 4 IBS: 0.18990025142492684

Fold 5 IBS: 0.17698987901902175
[I 2024-04-16 01:26:13,863] Trial 31 finished with value: 0.1756223060197624 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.6141886010044044, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.050889504115644586}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17921499719523448
Fold 2 IBS: 0.14457659998302025
Fold 3 IBS: 0.18892068480933402
Fold 4 IBS: 0.1881785321534129
Fold 5 IBS: 0.17366220512930025
[I 2024-04-16 01:26:31,937] Trial 32 finished with value: 0.17491060385406038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.7145937356077748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.040680386261001684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17839650482493216
Fold 2 IBS: 0.14376103753095715
Fold 3 IBS: 0.19179232168292484
Fold 4 IBS: 0.19114956333888955
Fold 5 IBS: 0.17341358371378018
[I 2024-04-16 01:26:46,178] Trial 33 finished with value: 0.17570260221829676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7166906016039446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09227781345982045}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16932356014486769
Fold 2 IBS: 0.15500446673627225
Fold 3 IBS: 0.17911021415557007
Fold 4 IBS: 0.1924434421788033
Fold 5 IBS: 0.1827561791077991
[I 2024-04-16 01:26:59,763] Trial 34 finished with value: 0.17572757246466247 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6617651070453551, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03171407678135554}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17172138717448102
Fold 2 IBS: 0.1489493130650319
Fold 3 IBS: 0.18425400801471595
Fold 4 IBS: 0.1932643172167075
Fold 5 IBS: 0.17711273715249415
[I 2024-04-16 01:27:12,624] Trial 35 finished with value: 0.1750603525246861 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.7113768772571837, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15846671523399145}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17419660096638498
Fold 2 IBS: 0.14719187785917906
Fold 3 IBS: 0.18565125612910302
Fold 4 IBS: 0.19257551123464545
Fold 5 IBS: 0.17764557195591085
[I 2024-04-16 01:27:17,318] Trial 36 finished with value: 0.17545216362904464 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 165, 'oob_score': False, 'max_samples': 0.5150316876314238, 'max_features': None, 'min_weight_fraction_leaf': 0.07821728657119803}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16964600099214439
Fold 2 IBS: 0.15385862052455887
Fold 3 IBS: 0.18067679456916436
Fold 4 IBS: 0.19330218283868858
Fold 5 IBS: 0.18067145906944948
[I 2024-04-16 01:27:28,020] Trial 37 finished with value: 0.17563101159880112 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6558408084386204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026524892218781126}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21398210519775457
Fold 2 IBS: 0.22147310463890008
Fold 3 IBS: 0.20484795914030776
Fold 4 IBS: 0.22469082739864527
Fold 5 IBS: 0.21847043318447362
[I 2024-04-16 01:27:41,076] Trial 38 finished with value: 0.21669288591201624 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.5446753536916582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20739916362370578
Fold 2 IBS: 0.1396518555288153
Fold 3 IBS: 0.20101553841044428
Fold 4 IBS: 0.18775948197861053
Fold 5 IBS: 0.17175126099969984
[I 2024-04-16 01:27:56,263] Trial 39 finished with value: 0.18151546010825514 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.7867614811876313, 'max_features': None, 'min_weight_fraction_leaf': 0.11443308942980066}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18099751369940803
Fold 2 IBS: 0.14073570153984705
Fold 3 IBS: 0.19394522353389632
Fold 4 IBS: 0.1899027663588423
Fold 5 IBS: 0.17323048606648403
[I 2024-04-16 01:28:05,588] Trial 40 finished with value: 0.17576233823969556 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.5666383752254781, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07880882141692147}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1711305979532741
Fold 2 IBS: 0.14944644009789185
Fold 3 IBS: 0.1838255715011791
Fold 4 IBS: 0.19303788294761579
Fold 5 IBS: 0.17769110415876982
[I 2024-04-16 01:28:17,799] Trial 41 finished with value: 0.17502631933174614 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 312, 'oob_score': True, 'max_samples': 0.7412385222820266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16945209847062737}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1766253375339953
Fold 2 IBS: 0.14548886613385514
Fold 3 IBS: 0.18810559860305523
Fold 4 IBS: 0.18904619197923261
Fold 5 IBS: 0.17490826493381245
[I 2024-04-16 01:28:32,038] Trial 42 finished with value: 0.17483485183679015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.8639712154486969, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16678569984405386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2139789554890857
Fold 2 IBS: 0.22135558660927104
Fold 3 IBS: 0.2047725162249457
Fold 4 IBS: 0.22463102393551193
Fold 5 IBS: 0.21859845040133852
[I 2024-04-16 01:28:45,654] Trial 43 finished with value: 0.2166673065320306 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.8907059888796497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18785889346357237
Fold 2 IBS: 0.15285827950678846
Fold 3 IBS: 0.18232508298547248
Fold 4 IBS: 0.18846580968340798
Fold 5 IBS: 0.17332117086709029
[I 2024-04-16 01:29:00,658] Trial 44 finished with value: 0.17696584730126633 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.846059951367212, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14736137547860684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1824125215519607
Fold 2 IBS: 0.142066615195965
Fold 3 IBS: 0.1952477350951836
Fold 4 IBS: 0.19275254902170263
Fold 5 IBS: 0.17385783785418485
[I 2024-04-16 01:29:16,107] Trial 45 finished with value: 0.17726745174379938 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.7898763610119546, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11906682715479999}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16985840962071383
Fold 2 IBS: 0.16096525914717788
Fold 3 IBS: 0.18227104026957164
Fold 4 IBS: 0.20281275724564665
Fold 5 IBS: 0.1850460571787144
[I 2024-04-16 01:29:18,357] Trial 46 finished with value: 0.18019070469236487 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.6496915230774891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08221811754778048}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16980857091041326
Fold 2 IBS: 0.15719115142034723
Fold 3 IBS: 0.1767449129839921
Fold 4 IBS: 0.19510331227382113
Fold 5 IBS: 0.1831755952242518
[I 2024-04-16 01:29:36,741] Trial 47 finished with value: 0.17640470856256513 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.8914383434724882, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24824101632322468}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19349637716238946
Fold 2 IBS: 0.18021514079410297
Fold 3 IBS: 0.1797766992061227
Fold 4 IBS: 0.20805913242700583
Fold 5 IBS: 0.19958771263889286
[I 2024-04-16 01:29:50,436] Trial 48 finished with value: 0.19222701244570276 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.9967788477130068, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2029239852759813
Fold 2 IBS: 0.13716491759028818
Fold 3 IBS: 0.2084231173473227
Fold 4 IBS: 0.19129569538138264
Fold 5 IBS: 0.16960756021085094
[I 2024-04-16 01:30:07,171] Trial 49 finished with value: 0.18188305516116512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.6825737614746896, 'max_features': None, 'min_weight_fraction_leaf': 0.020427001696118233}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1847999347983001
Fold 2 IBS: 0.15364870601921565
Fold 3 IBS: 0.1822009992001216
Fold 4 IBS: 0.18809108511963865
Fold 5 IBS: 0.17414367995939478
[I 2024-04-16 01:30:11,738] Trial 50 finished with value: 0.17657688101933416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8644699746287099, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06989429005204871}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17038930280276898
Fold 2 IBS: 0.15348758465747694
Fold 3 IBS: 0.18016675506323593
Fold 4 IBS: 0.1938593087420373
Fold 5 IBS: 0.18099103292628088
[I 2024-04-16 01:30:23,222] Trial 51 finished with value: 0.17577879683836 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.727895633786626, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18327602934679604}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17451701150431106
Fold 2 IBS: 0.14671503382427162
Fold 3 IBS: 0.18683750953876657
Fold 4 IBS: 0.19257094181568649
Fold 5 IBS: 0.17615300496682904
[I 2024-04-16 01:30:38,242] Trial 52 finished with value: 0.17535870032997297 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.7478990221520405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14624323581313917}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17559006537700683
Fold 2 IBS: 0.16972487299848873
Fold 3 IBS: 0.17529653726657532
Fold 4 IBS: 0.19855196165239603
Fold 5 IBS: 0.1851918744321701
[I 2024-04-16 01:30:58,099] Trial 53 finished with value: 0.1808710623453274 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.8074226422105014, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27324344422148944}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17595680778437212
Fold 2 IBS: 0.17008267991566167
Fold 3 IBS: 0.17604437670258266
Fold 4 IBS: 0.19769140576353486
Fold 5 IBS: 0.18734084278780233
[I 2024-04-16 01:31:21,278] Trial 54 finished with value: 0.18142322259079072 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.5775945927656037, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2001668400822587}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16773815898136948
Fold 2 IBS: 0.1576076816374329
Fold 3 IBS: 0.17803399667907918
Fold 4 IBS: 0.19725085339663992
Fold 5 IBS: 0.18451260927365026
[I 2024-04-16 01:31:25,779] Trial 55 finished with value: 0.17702865999363437 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.6303629140203428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16685382022581927}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18003668325471714
Fold 2 IBS: 0.14323357247265056
Fold 3 IBS: 0.19283157086976438
Fold 4 IBS: 0.192092008764836
Fold 5 IBS: 0.17436160978254575
[I 2024-04-16 01:31:40,158] Trial 56 finished with value: 0.17651108902890275 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.7623102674577037, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09861841429774906}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17302493479017875
Fold 2 IBS: 0.1667969562590488
Fold 3 IBS: 0.17568508570553082
Fold 4 IBS: 0.1958388085038477
Fold 5 IBS: 0.18612204667403598
[I 2024-04-16 01:32:05,512] Trial 57 finished with value: 0.1794935663865284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.6746410572190499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19693288454187685
Fold 2 IBS: 0.16031608536235142
Fold 3 IBS: 0.18209014838073903
Fold 4 IBS: 0.18830938207544887
Fold 5 IBS: 0.1722123575079718
[I 2024-04-16 01:32:37,293] Trial 58 finished with value: 0.1799721715736776 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.9493525765812034, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.033039474629030334}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17638204755824788
Fold 2 IBS: 0.14724121981954666
Fold 3 IBS: 0.18830472263321374
Fold 4 IBS: 0.18908125561308473
Fold 5 IBS: 0.17501568142226698
[I 2024-04-16 01:32:48,189] Trial 59 finished with value: 0.175204985409272 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.706317491452594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.011952641009515354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17441654996325617
Fold 2 IBS: 0.16879198972806275
Fold 3 IBS: 0.1747308489003251
Fold 4 IBS: 0.19678299634235394
Fold 5 IBS: 0.18428329935051413
[I 2024-04-16 01:32:56,491] Trial 60 finished with value: 0.1798011368569024 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.4446079220615766, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13552790545628873}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1726966416095679
Fold 2 IBS: 0.14791648216625575
Fold 3 IBS: 0.18587926582625136
Fold 4 IBS: 0.19250544947641468
Fold 5 IBS: 0.1767138327798232
[I 2024-04-16 01:33:16,379] Trial 61 finished with value: 0.17514233437166257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.7350539425199517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15353880193597452}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1784711929725387
Fold 2 IBS: 0.14471049906571562
Fold 3 IBS: 0.19083362219368874
Fold 4 IBS: 0.19321298173368606

Fold 5 IBS: 0.17601995444169838
[I 2024-04-16 01:33:34,719] Trial 62 finished with value: 0.1766496500814655 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.6969767031486694, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11947149985769817}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17325965795999854
Fold 2 IBS: 0.16035062956465257
Fold 3 IBS: 0.17539882197990753
Fold 4 IBS: 0.193362443315604
Fold 5 IBS: 0.1796554283287958
[I 2024-04-16 01:33:53,750] Trial 63 finished with value: 0.17640539622979168 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 311, 'oob_score': True, 'max_samples': 0.6304198495967799, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16702154024396243}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17417602273955624
Fold 2 IBS: 0.1480464954861786
Fold 3 IBS: 0.1861637654245361
Fold 4 IBS: 0.19307278746213727
Fold 5 IBS: 0.17661238768457427
[I 2024-04-16 01:34:08,197] Trial 64 finished with value: 0.1756142917593965 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.8416513210854921, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16738759238643802}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1822613083064998
Fold 2 IBS: 0.1416365045076241
Fold 3 IBS: 0.1960788715196419
Fold 4 IBS: 0.19275645033338762
Fold 5 IBS: 0.1744182820015701
[I 2024-04-16 01:34:24,711] Trial 65 finished with value: 0.17743028333374472 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.7722883894951643, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0665684368743143}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17389086197303102
Fold 2 IBS: 0.16790129559912909
Fold 3 IBS: 0.1751507252355886
Fold 4 IBS: 0.19750324318227722
Fold 5 IBS: 0.18620949704754197
[I 2024-04-16 01:34:37,431] Trial 66 finished with value: 0.18013112460751357 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.5947629158546897, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20025339037463216}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17423384494498612
Fold 2 IBS: 0.14631335780890575
Fold 3 IBS: 0.18861958817402585
Fold 4 IBS: 0.19245950764813075
Fold 5 IBS: 0.175067247621942
[I 2024-04-16 01:35:01,822] Trial 67 finished with value: 0.1753387092395981 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.7217571884559283, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13013771636318264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17535705050457914
Fold 2 IBS: 0.15778179636614245
Fold 3 IBS: 0.17763073839385685
Fold 4 IBS: 0.19018833285814207
Fold 5 IBS: 0.17770479034207873
[I 2024-04-16 01:35:13,467] Trial 68 finished with value: 0.17573254169295985 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.5191868058797825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.047795726630053076}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17480337133090915
Fold 2 IBS: 0.16874159329787056
Fold 3 IBS: 0.17579652970954177
Fold 4 IBS: 0.1923367638029231
Fold 5 IBS: 0.18690613654154167
[I 2024-04-16 01:35:36,280] Trial 69 finished with value: 0.17971687893655724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.18576927332867577, 'max_features': 'log2', 'min_weight_fraction_leaf': 7.114682696795181e-05}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20781268631997615
Fold 2 IBS: 0.13838860575441492
Fold 3 IBS: 0.21122911345717027
Fold 4 IBS: 0.19170717046621447
Fold 5 IBS: 0.16987800654423307
[I 2024-04-16 01:35:59,145] Trial 70 finished with value: 0.18380311650840175 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.8126013453538647, 'max_features': None, 'min_weight_fraction_leaf': 0.10415283732963354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16897127550996938
Fold 2 IBS: 0.15333527019800122
Fold 3 IBS: 0.18108923812924368
Fold 4 IBS: 0.19125151911620464
Fold 5 IBS: 0.1804095239747975
[I 2024-04-16 01:36:24,471] Trial 71 finished with value: 0.17501136538564327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.5965842869794661, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04020616684856252}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16942384334835775
Fold 2 IBS: 0.1534316341977167
Fold 3 IBS: 0.18126076316917372
Fold 4 IBS: 0.1918304245116947
Fold 5 IBS: 0.1797086597106947
[I 2024-04-16 01:36:47,137] Trial 72 finished with value: 0.17513106498752753 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.64967240812612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042859490745800255}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17483538806839433
Fold 2 IBS: 0.15903414917848718
Fold 3 IBS: 0.178305987368802
Fold 4 IBS: 0.18895015857840794
Fold 5 IBS: 0.17674514740069427
[I 2024-04-16 01:37:12,197] Trial 73 finished with value: 0.17557416611895713 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 468, 'oob_score': False, 'max_samples': 0.614601651625123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08656637647813382}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685354387079355
Fold 2 IBS: 0.1519242369397579
Fold 3 IBS: 0.18329403645197254
Fold 4 IBS: 0.19121480234741198
Fold 5 IBS: 0.17959179151928248
[I 2024-04-16 01:37:47,339] Trial 74 finished with value: 0.17491206119327207 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.564394176347414, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0639505821191327}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16870518179470842
Fold 2 IBS: 0.1524006924636778
Fold 3 IBS: 0.1824052463489283
Fold 4 IBS: 0.19198874945374883
Fold 5 IBS: 0.17971814686012724
[I 2024-04-16 01:38:14,978] Trial 75 finished with value: 0.1750436033842381 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.5549716215197416, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06244978633063567}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17388421751906138
Fold 2 IBS: 0.1679541870820109
Fold 3 IBS: 0.17539898304019086
Fold 4 IBS: 0.1953143658823387
Fold 5 IBS: 0.18647747737304407
[I 2024-04-16 01:38:34,837] Trial 76 finished with value: 0.1798058461793292 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.5288500192319384, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016585234890071264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17761169418416847
Fold 2 IBS: 0.16895784550549822
Fold 3 IBS: 0.17542226135379532
Fold 4 IBS: 0.19549660202075014
Fold 5 IBS: 0.18743069872463708
[I 2024-04-16 01:38:49,613] Trial 77 finished with value: 0.18098382035776983 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.3800215746179153, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03735564012092016}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16818314645426713
Fold 2 IBS: 0.15369061634554518
Fold 3 IBS: 0.18213459050433092
Fold 4 IBS: 0.19123211966917278
Fold 5 IBS: 0.17979973767912885
[I 2024-04-16 01:39:16,570] Trial 78 finished with value: 0.17500804213048896 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.4897248144615137, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053996872945124036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1682237549262069
Fold 2 IBS: 0.15295334400832536
Fold 3 IBS: 0.18214608764478374
Fold 4 IBS: 0.19238806563941324
Fold 5 IBS: 0.18028732465861996
[I 2024-04-16 01:39:35,857] Trial 79 finished with value: 0.17519971537546983 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.49575398669591153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06405554874562534}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17507598055558485
Fold 2 IBS: 0.16867091079334554
Fold 3 IBS: 0.1744565827712509
Fold 4 IBS: 0.1954950968251498
Fold 5 IBS: 0.18635102171872073
[I 2024-04-16 01:39:55,565] Trial 80 finished with value: 0.18000991853281037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.43759421275648835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0533463490707784}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1714174399032279
Fold 2 IBS: 0.14887499618081926
Fold 3 IBS: 0.1849640281040515
Fold 4 IBS: 0.1899572218408997
Fold 5 IBS: 0.17713400076306418
[I 2024-04-16 01:40:14,192] Trial 81 finished with value: 0.17446953735841247 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5784234487575245, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10829522154445037}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16877649511183368
Fold 2 IBS: 0.1546883871779083
Fold 3 IBS: 0.18056083236056208
Fold 4 IBS: 0.19133957386634493
Fold 5 IBS: 0.18162520349661385
[I 2024-04-16 01:40:36,852] Trial 82 finished with value: 0.17539809840265258 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5722759399876282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10440976094597362}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685240734239476
Fold 2 IBS: 0.15222241351006804
Fold 3 IBS: 0.1822020345828932
Fold 4 IBS: 0.19079185577835267
Fold 5 IBS: 0.17960640446910925
[I 2024-04-16 01:41:02,072] Trial 83 finished with value: 0.17466935635287414 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.5451307479888213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0724192455670338}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17338079162104056
Fold 2 IBS: 0.15920893592551924
Fold 3 IBS: 0.17825449140901586
Fold 4 IBS: 0.18925769833312683
Fold 5 IBS: 0.17742455682194408
[I 2024-04-16 01:41:28,835] Trial 84 finished with value: 0.17550529482212932 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.5442180702857965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07567351514027787}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1690383568215189
Fold 2 IBS: 0.15230702588653305
Fold 3 IBS: 0.1822765777502009
Fold 4 IBS: 0.19170674176025757
Fold 5 IBS: 0.18006279876989542
[I 2024-04-16 01:41:53,025] Trial 85 finished with value: 0.17507830019768117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.5030563110008609, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09285296477077623}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17784444889141396
Fold 2 IBS: 0.14568494632276702
Fold 3 IBS: 0.18681231725936967
Fold 4 IBS: 0.18938575035357394
Fold 5 IBS: 0.17417653028434565
[I 2024-04-16 01:42:20,700] Trial 86 finished with value: 0.17478079862229406 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.6227373925109708, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11680143459253466}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17320771484108127
Fold 2 IBS: 0.1471439015418838
Fold 3 IBS: 0.1868119711290211
Fold 4 IBS: 0.191522355137527
Fold 5 IBS: 0.17549663792817793
[I 2024-04-16 01:42:47,599] Trial 87 finished with value: 0.17483651611553824 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.6363957788305546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1264522778930551}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.177279146128294
Fold 2 IBS: 0.14462990587422714
Fold 3 IBS: 0.18982364231541823
Fold 4 IBS: 0.19123959493668208
Fold 5 IBS: 0.17462972301152646
[I 2024-04-16 01:43:19,036] Trial 88 finished with value: 0.17552040245322958 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.643212285009443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11042020211203352}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18172829377621072
Fold 2 IBS: 0.15455308362712544
Fold 3 IBS: 0.18079631963918813
Fold 4 IBS: 0.1866909754534505
Fold 5 IBS: 0.17486062534932048
[I 2024-04-16 01:43:53,527] Trial 89 finished with value: 0.17572585956905906 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 379, 'oob_score': False, 'max_samples': 0.6745160130358284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13729294470437828}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17159615871766515
Fold 2 IBS: 0.1492340100734715
Fold 3 IBS: 0.18525391328974408
Fold 4 IBS: 0.19170238188043215
Fold 5 IBS: 0.17723852207113783
[I 2024-04-16 01:44:30,677] Trial 90 finished with value: 0.17500499720649015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6100442323266079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08381032204107067}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17439132896823156
Fold 2 IBS: 0.1476318214680082
Fold 3 IBS: 0.1865038949155308
Fold 4 IBS: 0.19098341263244506
Fold 5 IBS: 0.17516827480713895
[I 2024-04-16 01:44:58,136] Trial 91 finished with value: 0.17493574655827088 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.6220455817398846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12351605327621175}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17132240828700077
Fold 2 IBS: 0.14948366004568905
Fold 3 IBS: 0.1849774655279456
Fold 4 IBS: 0.19091977764974633
Fold 5 IBS: 0.17791613386648897
[I 2024-04-16 01:45:18,179] Trial 92 finished with value: 0.17492388907537415 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.5773252805729456, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1260508695586116}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17523723037867286
Fold 2 IBS: 0.1453570091149411
Fold 3 IBS: 0.18962747105019612
Fold 4 IBS: 0.19107181469212342

Fold 5 IBS: 0.1747309238915691
[I 2024-04-16 01:45:38,246] Trial 93 finished with value: 0.1752048898255005 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.5630698614554802, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0944985972942633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17026943747099219
Fold 2 IBS: 0.15255352423829832
Fold 3 IBS: 0.18160069813968083
Fold 4 IBS: 0.19096533404342483
Fold 5 IBS: 0.1822030877543707
[I 2024-04-16 01:45:57,198] Trial 94 finished with value: 0.17551841632935336 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.5751544947591161, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14409687866880386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17475332961241374
Fold 2 IBS: 0.14521126379405494
Fold 3 IBS: 0.18914044635556457
Fold 4 IBS: 0.19026828870845303
Fold 5 IBS: 0.1744104734429843
[I 2024-04-16 01:46:20,594] Trial 95 finished with value: 0.1747567603826941 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.5892575789175918, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11211324848978509}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21400356610903593
Fold 2 IBS: 0.22204327857369352
Fold 3 IBS: 0.20415553733700337
Fold 4 IBS: 0.2250379696399111
Fold 5 IBS: 0.21815296605159928
[I 2024-04-16 01:46:24,296] Trial 96 finished with value: 0.21667866354224863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.46700128900375126, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35031312034195705}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.173562295845494
Fold 2 IBS: 0.14742220750236526
Fold 3 IBS: 0.18545169450924154
Fold 4 IBS: 0.18866406353263676
Fold 5 IBS: 0.17639414796763403
[I 2024-04-16 01:46:45,729] Trial 97 finished with value: 0.1742988818714743 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.5401266728628165, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11341150154917841}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.179800528231758
Fold 2 IBS: 0.15504407580671617
Fold 3 IBS: 0.18062194922738495
Fold 4 IBS: 0.18693465453878075
Fold 5 IBS: 0.17539368811607456
[I 2024-04-16 01:47:09,529] Trial 98 finished with value: 0.1755589791841429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.5436809153821575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10940615561612807}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18678959754522786
Fold 2 IBS: 0.14275774495321747
Fold 3 IBS: 0.19217915320067025
Fold 4 IBS: 0.18335908765764633
Fold 5 IBS: 0.17253698272333465
[I 2024-04-16 01:47:33,475] Trial 99 finished with value: 0.1755245132160193 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.694819405505868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07480505292477731}. Best is trial 11 with value: 0.17074634120633253.


* Best trial for IBS:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.17074634120633253], datetime_start=datetime.datetime(2024, 4, 16, 1, 20, 17, 305521), datetime_complete=datetime.datetime(2024, 4, 16, 1, 20, 18, 56670), params={'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=11, value=None)


* Best Score for IBS:
 0.17074634120633253

In [48]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.846
train_ibs:  0.171

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=12,
                     max_samples=0.48042970450395145, min_samples_leaf=1,
                     min_samples_split=4,
                     min_weight_fraction_leaf=0.0025914663927405594,
                     n_estimators=289, random_state=123, warm_start=True)

test_cindex:  0.602

RandomSurvivalForest(max_depth=1, max_features='auto', max_leaf_nodes=18,
                     max_samples=0.7351810575897255, min_samples_leaf=11,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.008231293935378081,
                     n_estimators=2, random_state=123)

test_ibs:  0.233

In [52]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:47:35,924] A new study created in memory with name: no-name-258e7d2c-e9ca-42eb-bfd0-111fdaeb516c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:47:41,000] Trial 0 finished with value: 0.763120153205612 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:47:51,494] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:48:13,308] Trial 2 finished with value: 0.7549111845989632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:48:15,808] Trial 3 finished with value: 0.7581427541761773 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:48:24,248] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:48:31,816] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:48:34,525] Trial 6 finished with value: 0.7620861007898516 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:48:42,543] Trial 7 finished with value: 0.7433829385982176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.715962441314554
[I 2024-04-16 01:48:43,006] Trial 8 finished with value: 0.7526603922254165 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7206572769953051
[I 2024-04-16 01:48:59,027] Trial 9 finished with value: 0.7327992570997183 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:49:03,742] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:49:06,739] Trial 11 finished with value: 0.7610279984130963 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:49:10,449] Trial 12 finished with value: 0.7656344262692516 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:49:13,944] Trial 13 finished with value: 0.7565522092481783 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:49:17,222] Trial 14 finished with value: 0.7616650689919885 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7794117647058824

Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 01:49:19,309] Trial 15 finished with value: 0.7545769177214963 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 01:49:23,552] Trial 16 finished with value: 0.7335270596877141 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:49:26,765] Trial 17 finished with value: 0.7591715308548418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:49:31,311] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:49:34,188] Trial 19 finished with value: 0.7663281634231028 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 01:49:37,790] Trial 20 finished with value: 0.746722729311177 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8975839614288115, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:49:40,266] Trial 21 finished with value: 0.7629692767153701 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9830051091386647, 'min_weight_fraction_leaf': 0.11961357903200062}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:49:42,863] Trial 22 finished with value: 0.7628892919669691 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8609656753336752, 'min_weight_fraction_leaf': 0.15663178852989545}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:49:45,441] Trial 23 finished with value: 0.7509593791567746 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.737236690052532, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:49:47,826] Trial 24 finished with value: 0.7611911126952604 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9222263146213784, 'min_weight_fraction_leaf': 0.08957779552546857}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.859375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 01:49:49,575] Trial 25 finished with value: 0.7561901306130971 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8274383615832067, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:50:05,902] Trial 26 finished with value: 0.7444877442865183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6539680943502474, 'min_weight_fraction_leaf': 0.04317449484749}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:50:09,011] Trial 27 finished with value: 0.7566253755185277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9365238772272462, 'min_weight_fraction_leaf': 0.14306800767196773}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8415178571428571
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:50:10,831] Trial 28 finished with value: 0.7600206204906962 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7383223503010752, 'min_weight_fraction_leaf': 0.20900889157295355}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:50:16,164] Trial 29 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4766061840882204, 'min_weight_fraction_leaf': 0.25297594889320807}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:50:20,182] Trial 30 finished with value: 0.7619426335421767 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.09166005683798992}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:50:23,385] Trial 31 finished with value: 0.7601328692954678 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9462932212483206, 'min_weight_fraction_leaf': 0.12021009726526694}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:50:25,934] Trial 32 finished with value: 0.760869569103513 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9864877695110971, 'min_weight_fraction_leaf': 0.06164320836318145}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:50:28,438] Trial 33 finished with value: 0.7624746237982056 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9301489258006082, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:50:30,489] Trial 34 finished with value: 0.7567330098622376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9912043386887608, 'min_weight_fraction_leaf': 0.02249172399095729}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:50:40,011] Trial 35 finished with value: 0.7529807806767499 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.766068607890644, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:50:42,408] Trial 36 finished with value: 0.7591886238684845 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8553115001753557, 'min_weight_fraction_leaf': 0.22873450590105582}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 01:50:45,221] Trial 37 finished with value: 0.7555796977821257 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6217761713512069, 'min_weight_fraction_leaf': 0.12934411260414114}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:50:56,668] Trial 38 finished with value: 0.7535108102301846 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 428, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.04910893285740458}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:50:58,116] Trial 39 finished with value: 0.7553157338682244 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8005826243516873, 'min_weight_fraction_leaf': 0.07469351697759873}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:51:01,013] Trial 40 finished with value: 0.7605112688643425 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9569519035429586, 'min_weight_fraction_leaf': 0.2757731212264245}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:51:03,385] Trial 41 finished with value: 0.7609843014176124 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8687619648747806, 'min_weight_fraction_leaf': 0.15295888294766263}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:51:06,767] Trial 42 finished with value: 0.7638303926085905 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.906955015046886, 'min_weight_fraction_leaf': 0.10454210976347417}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8370535714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:51:10,239] Trial 43 finished with value: 0.7591740994887395 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8217177439443847, 'min_weight_fraction_leaf': 0.10552735389681006}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:51:12,939] Trial 44 finished with value: 0.7612405402767923 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9989309278077574, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:51:14,952] Trial 45 finished with value: 0.7628719194609885 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9091736520975473, 'min_weight_fraction_leaf': 0.0038012551219620827}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.7347417840375586
[I 2024-04-16 01:51:31,348] Trial 46 finished with value: 0.7501344600750558 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 359, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5368271784486555, 'min_weight_fraction_leaf': 0.10615317714605318}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 01:51:31,977] Trial 47 finished with value: 0.7516793229025998 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 31, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9594946112358607, 'min_weight_fraction_leaf': 0.17333335446497328}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:51:34,782] Trial 48 finished with value: 0.7562519939011765 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7685785296036635, 'min_weight_fraction_leaf': 0.13176023447811921}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5432900432900433
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5738396624472574
Fold 5 C-index: 0.460093896713615
[I 2024-04-16 01:51:37,424] Trial 49 finished with value: 0.5820501126470459 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8880373878399398, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:51:40,200] Trial 50 finished with value: 0.7630008769419695 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7034625855110039, 'min_weight_fraction_leaf': 0.07304621552955944}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:51:43,269] Trial 51 finished with value: 0.7612490374113632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7321671383859141, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:51:46,228] Trial 52 finished with value: 0.7629420794152763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6907063917898906, 'min_weight_fraction_leaf': 0.0661877659346652}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:51:50,549] Trial 53 finished with value: 0.7596563589778932 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 480, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9052538185294309, 'min_weight_fraction_leaf': 0.08508715956661925}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:51:53,463] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.577878588672621, 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:51:56,786] Trial 55 finished with value: 0.7704458139436589 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7999514777179073, 'min_weight_fraction_leaf': 0.035270943770753044}. Best is trial 55 with value: 0.7704458139436589.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:51:59,470] Trial 56 finished with value: 0.771384781079809 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7991467335557068, 'min_weight_fraction_leaf': 0.027992113153361142}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:52:10,502] Trial 57 finished with value: 0.74717809865806 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 248, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.79672071864693, 'min_weight_fraction_leaf': 0.016889715164357902}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:52:12,766] Trial 58 finished with value: 0.7677971640851675 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.828019859852415, 'min_weight_fraction_leaf': 0.03447642547531156}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:52:15,313] Trial 59 finished with value: 0.7697165233781805 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8346072695502785, 'min_weight_fraction_leaf': 0.0002567835070198393}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:52:18,058] Trial 60 finished with value: 0.7674757615164577 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 321, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6391411801898657, 'min_weight_fraction_leaf': 0.03561049450086254}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:52:20,516] Trial 61 finished with value: 0.7665829043736004 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6492185512714621, 'min_weight_fraction_leaf': 0.03617201704474487}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:52:23,110] Trial 62 finished with value: 0.7674728962234336 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 319, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5312924276275225, 'min_weight_fraction_leaf': 0.040385592930900376}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:52:25,620] Trial 63 finished with value: 0.7710730622821746 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5292658633860801, 'min_weight_fraction_leaf': 0.03711866587371772}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:52:27,985] Trial 64 finished with value: 0.7657902697781489 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.39806376813911337, 'min_weight_fraction_leaf': 0.03599381902829695}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:52:30,370] Trial 65 finished with value: 0.7621709115338706 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5323188905088267, 'min_weight_fraction_leaf': 0.010814253491385636}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:52:32,350] Trial 66 finished with value: 0.7691537029891617 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.49002509944053235, 'min_weight_fraction_leaf': 0.053181149195751426}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:52:34,239] Trial 67 finished with value: 0.7604151188182366 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.43798216039712035, 'min_weight_fraction_leaf': 0.0010098437298928856}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:52:35,902] Trial 68 finished with value: 0.7683829874029711 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6113081575629796, 'min_weight_fraction_leaf': 0.057217831184053644}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:52:37,856] Trial 69 finished with value: 0.7639295695425288 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5915899101823151, 'min_weight_fraction_leaf': 0.05522041323530981}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:52:40,418] Trial 70 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47632910975325155, 'min_weight_fraction_leaf': 0.35980997926626934}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:52:42,851] Trial 71 finished with value: 0.768254027368253 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6101916618563699, 'min_weight_fraction_leaf': 0.024998041606770292}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:52:44,861] Trial 72 finished with value: 0.7628057101379913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.32440915793159353, 'min_weight_fraction_leaf': 0.018643504112019715}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:52:46,594] Trial 73 finished with value: 0.7656587582763213 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5609478284070107, 'min_weight_fraction_leaf': 0.05622629784226072}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:52:48,583] Trial 74 finished with value: 0.7584779347240282 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5118014483585279, 'min_weight_fraction_leaf': 0.02563279470181265}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:52:51,030] Trial 75 finished with value: 0.7573932258116945 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6069046410719314, 'min_weight_fraction_leaf': 0.08378422745274237}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:53:00,542] Trial 76 finished with value: 0.7521751447219839 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.497864611352535, 'min_weight_fraction_leaf': 0.06709163220470778}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:01,889] Trial 77 finished with value: 0.7620487699772043 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 196, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6683682203156043, 'min_weight_fraction_leaf': 0.011300445410194197}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:53:03,777] Trial 78 finished with value: 0.760363871557148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.42677810376705305, 'min_weight_fraction_leaf': 0.052012092584961866}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:53:05,960] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7173081556448422, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:53:08,390] Trial 80 finished with value: 0.7683639336867342 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.35277360385569917, 'min_weight_fraction_leaf': 0.02852600943088988}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:10,213] Trial 81 finished with value: 0.7691928560351028 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3390678218166532, 'min_weight_fraction_leaf': 0.03153990098917725}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:12,052] Trial 82 finished with value: 0.7646076128469184 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 224, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3230507568153901, 'min_weight_fraction_leaf': 0.0014394857922413185}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:53:13,571] Trial 83 finished with value: 0.7614147057143738 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.23361689093258667, 'min_weight_fraction_leaf': 0.019775489029462356}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:53:15,218] Trial 84 finished with value: 0.7495893806395312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 260, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27445260818266226, 'min_weight_fraction_leaf': 0.09592965050134614}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:53:17,253] Trial 85 finished with value: 0.758556238262173 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3862488114937627, 'min_weight_fraction_leaf': 0.04471114770202597}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:53:18,894] Trial 86 finished with value: 0.7708567082564886 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 201, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.36377499756925225, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:53:22,588] Trial 87 finished with value: 0.7565355685297506 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3759670482683807, 'min_weight_fraction_leaf': 0.0767440911470792}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:53:27,682] Trial 88 finished with value: 0.7609903537745347 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.46073886535297426, 'min_weight_fraction_leaf': 0.05833982872177459}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:53:30,252] Trial 89 finished with value: 0.7699832161020457 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.295955749271664, 'min_weight_fraction_leaf': 0.010964572281232194}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:53:31,165] Trial 90 finished with value: 0.75952694664796 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27944226981321685, 'min_weight_fraction_leaf': 0.012928542240062478}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:53:33,847] Trial 91 finished with value: 0.7801238175459491 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3602425648795669, 'min_weight_fraction_leaf': 0.02981466940699433}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:53:36,738] Trial 92 finished with value: 0.7662740508689903 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.25077855422842626, 'min_weight_fraction_leaf': 0.04540069770937229}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:53:40,336] Trial 93 finished with value: 0.7619860192654835 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.34979442362410473, 'min_weight_fraction_leaf': 0.06734177243231611}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:42,070] Trial 94 finished with value: 0.7645085743822805 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.193678974775281, 'min_weight_fraction_leaf': 0.010805974584784796}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:44,458] Trial 95 finished with value: 0.7709939821242033 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30647854490295495, 'min_weight_fraction_leaf': 0.03078253598240698}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:46,724] Trial 96 finished with value: 0.7702698288265208 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3052686496163978, 'min_weight_fraction_leaf': 0.029515857916013147}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:53:49,229] Trial 97 finished with value: 0.7686062560974729 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30685683165847666, 'min_weight_fraction_leaf': 0.03193125520570377}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:53:51,595] Trial 98 finished with value: 0.7910857462403429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}. Best is trial 98 with value: 0.7910857462403429.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784

[I 2024-04-16 01:53:54,003] A new study created in memory with name: no-name-ca2d26ac-7cdb-40fe-ae52-e15062f5fe7c

Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:53:53,990] Trial 99 finished with value: 0.7902101231341658 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21478988941660257, 'min_weight_fraction_leaf': 0.0040275983337470555}. Best is trial 98 with value: 0.7910857462403429.


* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.7910857462403429], datetime_start=datetime.datetime(2024, 4, 16, 1, 53, 49, 239810), datetime_complete=datetime.datetime(2024, 4, 16, 1, 53, 51, 594851), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for C-index:
 0.7910857462403429

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1894050222499581
Fold 2 IBS: 0.18197094047238005
Fold 3 IBS: 0.18636461603352758
Fold 4 IBS: 0.19277723911134473
Fold 5 IBS: 0.19455867868991514
[I 2024-04-16 01:54:03,774] Trial 0 finished with value: 0.1890152993114251 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-16 01:54:16,382] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20172405646713062
Fold 2 IBS: 0.2032359255005334
Fold 3 IBS: 0.19513408046545
Fold 4 IBS: 0.2118539452893589
Fold 5 IBS: 0.20729390842542533
[I 2024-04-16 01:54:31,392] Trial 2 finished with value: 0.20384838322957965 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20209415878470963
Fold 2 IBS: 0.20376840661760706
Fold 3 IBS: 0.19482805354546556
Fold 4 IBS: 0.21132760062349532
Fold 5 IBS: 0.2062713273884813
[I 2024-04-16 01:54:34,850] Trial 3 finished with value: 0.2036579093919518 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-16 01:54:44,110] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-16 01:54:49,285] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1904913206168486
Fold 2 IBS: 0.18444679148666562
Fold 3 IBS: 0.1856399244213203
Fold 4 IBS: 0.19570316353343864
Fold 5 IBS: 0.19484476324380895
[I 2024-04-16 01:54:59,996] Trial 6 finished with value: 0.19022519266041643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.19248537415224085
Fold 2 IBS: 0.19105800071812176
Fold 3 IBS: 0.19070595715673386
Fold 4 IBS: 0.2001633927865564
Fold 5 IBS: 0.20070302537730883
[I 2024-04-16 01:55:05,402] Trial 7 finished with value: 0.19502315003819234 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20480968165568902
Fold 2 IBS: 0.20484102123135522
Fold 3 IBS: 0.1975354311772608
Fold 4 IBS: 0.21193929006953224
Fold 5 IBS: 0.20806725700632217
[I 2024-04-16 01:55:06,699] Trial 8 finished with value: 0.2054385362280319 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.2113464419407712
Fold 2 IBS: 0.2169269042702578
Fold 3 IBS: 0.2014624387193473
Fold 4 IBS: 0.2214616279249577
Fold 5 IBS: 0.21570168611580814
[I 2024-04-16 01:55:19,105] Trial 9 finished with value: 0.21337981979422843 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-16 01:55:29,717] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1959863918798848
Fold 2 IBS: 0.19656167181968498
Fold 3 IBS: 0.19210822980372252
Fold 4 IBS: 0.2085074674907661
Fold 5 IBS: 0.20360120107474317
[I 2024-04-16 01:55:37,605] Trial 11 finished with value: 0.1993529924137603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.18512904520321427
Fold 2 IBS: 0.1740527886135347
Fold 3 IBS: 0.1861816706148936
Fold 4 IBS: 0.1893061222535103
Fold 5 IBS: 0.18959027778216106
[I 2024-04-16 01:55:48,356] Trial 12 finished with value: 0.18485198089346278 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19581913848034474
Fold 2 IBS: 0.19606584700533666
Fold 3 IBS: 0.18996353898817178
Fold 4 IBS: 0.2052342771852341
Fold 5 IBS: 0.2042479606113508
[I 2024-04-16 01:55:59,380] Trial 13 finished with value: 0.19826615245408763 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19648331141303396
Fold 2 IBS: 0.1983397281797131
Fold 3 IBS: 0.19106070821891877
Fold 4 IBS: 0.20858865485637526
Fold 5 IBS: 0.20490088125230282
[I 2024-04-16 01:56:09,611] Trial 14 finished with value: 0.1998746567840688 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.18485198089346278.

Fold 1 IBS: 0.19593558348243098
Fold 2 IBS: 0.19875475852789654
Fold 3 IBS: 0.1903333352589917
Fold 4 IBS: 0.20748251302147644
Fold 5 IBS: 0.203704702028721
[I 2024-04-16 01:56:15,152] Trial 15 finished with value: 0.19924217846390332 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21249912881980682
Fold 2 IBS: 0.2205333193107399
Fold 3 IBS: 0.2035653160933136
Fold 4 IBS: 0.22350418932951804
Fold 5 IBS: 0.2173028001714802
[I 2024-04-16 01:56:27,381] Trial 16 finished with value: 0.21548095074497176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19183114805047974
Fold 2 IBS: 0.19128424686172338
Fold 3 IBS: 0.18814594086160835
Fold 4 IBS: 0.20499323686954313
Fold 5 IBS: 0.20021013474043506
[I 2024-04-16 01:56:33,509] Trial 17 finished with value: 0.1952929414767579 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-16 01:56:35,948] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.1938760896028742
Fold 2 IBS: 0.19481663520802522
Fold 3 IBS: 0.18987914648212936
Fold 4 IBS: 0.20616644798233227
Fold 5 IBS: 0.20329633873487413
[I 2024-04-16 01:56:43,557] Trial 19 finished with value: 0.19760693160204706 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.20735529929388963
Fold 2 IBS: 0.208787348599295
Fold 3 IBS: 0.20137982249029263
Fold 4 IBS: 0.22312888688520593
Fold 5 IBS: 0.21346429994402807
[I 2024-04-16 01:56:44,021] Trial 20 finished with value: 0.21082313144254225 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.190149663845766
Fold 2 IBS: 0.1836146541541013
Fold 3 IBS: 0.18617574190891484
Fold 4 IBS: 0.19484231855727627
Fold 5 IBS: 0.19454635613742202
[I 2024-04-16 01:56:51,693] Trial 21 finished with value: 0.18986574692069608 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.18788264608767696
Fold 2 IBS: 0.17893614961467227
Fold 3 IBS: 0.18648188730398177
Fold 4 IBS: 0.19163081844739127
Fold 5 IBS: 0.1923382065001444
[I 2024-04-16 01:56:59,225] Trial 22 finished with value: 0.18745394159077333 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.182703884521614
Fold 2 IBS: 0.16927944395517258
Fold 3 IBS: 0.18708643964817723
Fold 4 IBS: 0.18405528016378853
Fold 5 IBS: 0.18780835196581747
[I 2024-04-16 01:57:07,249] Trial 23 finished with value: 0.18218668005091396 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1895746301789297
Fold 2 IBS: 0.18039920275165355
Fold 3 IBS: 0.18517396368706437
Fold 4 IBS: 0.1961580074360814
Fold 5 IBS: 0.195878956164384
[I 2024-04-16 01:57:18,561] Trial 24 finished with value: 0.1894369520436226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19405738204668507
Fold 2 IBS: 0.19184743202663856
Fold 3 IBS: 0.19007884771101807
Fold 4 IBS: 0.20222541889504655
Fold 5 IBS: 0.20019121612149113
[I 2024-04-16 01:57:28,252] Trial 25 finished with value: 0.19568005936017588 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1940402932834844
Fold 2 IBS: 0.19432298692911043
Fold 3 IBS: 0.1892928247871703
Fold 4 IBS: 0.20429929982391268
Fold 5 IBS: 0.2021205628117341
[I 2024-04-16 01:57:39,743] Trial 26 finished with value: 0.19681519352708238 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19637495341237682
Fold 2 IBS: 0.1958296716242794
Fold 3 IBS: 0.19032854761836807
Fold 4 IBS: 0.20681694152044366
Fold 5 IBS: 0.2037201720927651
[I 2024-04-16 01:57:50,606] Trial 27 finished with value: 0.19861405725364661 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1975709578546784
Fold 2 IBS: 0.19829442573017972
Fold 3 IBS: 0.1915470690360173
Fold 4 IBS: 0.21031250675637114
Fold 5 IBS: 0.20365042057523824
[I 2024-04-16 01:57:58,573] Trial 28 finished with value: 0.20027507599049693 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.20387777006226956
Fold 2 IBS: 0.21044805665332703
Fold 3 IBS: 0.1968442774138352
Fold 4 IBS: 0.21672718054203935
Fold 5 IBS: 0.2104572520340109
[I 2024-04-16 01:58:05,171] Trial 29 finished with value: 0.20767090734109636 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.18218668005091396.

Fold 1 IBS: 0.18923073618097216
Fold 2 IBS: 0.17632006586851645
Fold 3 IBS: 0.18707067058836963
Fold 4 IBS: 0.19307240934736852
Fold 5 IBS: 0.19343354994654252
[I 2024-04-16 01:58:12,345] Trial 30 finished with value: 0.18782548638635385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1949036294792145
Fold 2 IBS: 0.1886371865011974
Fold 3 IBS: 0.19117863815442443
Fold 4 IBS: 0.2001198684681372
Fold 5 IBS: 0.19929856633981852
[I 2024-04-16 01:58:21,204] Trial 31 finished with value: 0.19482757778855841 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7284646777879923, 'min_weight_fraction_leaf': 0.03048718971899994}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.18836540230737153
Fold 2 IBS: 0.1781707184035029
Fold 3 IBS: 0.18564681721521098
Fold 4 IBS: 0.19277633701007463
Fold 5 IBS: 0.19331832607908583
[I 2024-04-16 01:58:28,014] Trial 32 finished with value: 0.18765552020304915 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8171100382086772, 'min_weight_fraction_leaf': 0.06242514513187879}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1837243286986642
Fold 2 IBS: 0.1726544375035722
Fold 3 IBS: 0.1857048039781507
Fold 4 IBS: 0.18788491866873833
Fold 5 IBS: 0.18954352546044614
[I 2024-04-16 01:58:37,694] Trial 33 finished with value: 0.18390240286191434 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.905569688846346, 'min_weight_fraction_leaf': 0.06699217911977255}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1801276242273068
Fold 2 IBS: 0.16520339426201733
Fold 3 IBS: 0.18553268896786967
Fold 4 IBS: 0.1845750159169672
Fold 5 IBS: 0.1835692206281775
[I 2024-04-16 01:58:47,366] Trial 34 finished with value: 0.1798015888004677 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.10969593086442025}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18049877857539035
Fold 2 IBS: 0.16663989287720696
Fold 3 IBS: 0.18469182662740596
Fold 4 IBS: 0.18574114889368326
Fold 5 IBS: 0.18477116270355273
[I 2024-04-16 01:58:58,268] Trial 35 finished with value: 0.18046856193544786 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 457, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9462418908074179, 'min_weight_fraction_leaf': 0.11750983562787085}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18037101974860273
Fold 2 IBS: 0.1669625142647935
Fold 3 IBS: 0.18453294697417297
Fold 4 IBS: 0.18631688561897877
Fold 5 IBS: 0.18678549330288546
[I 2024-04-16 01:59:09,546] Trial 36 finished with value: 0.18099377198188668 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.923638047949589, 'min_weight_fraction_leaf': 0.1257504807357439}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17994058405266816
Fold 2 IBS: 0.1669807265270973
Fold 3 IBS: 0.18438556878610593
Fold 4 IBS: 0.18645614257107018
Fold 5 IBS: 0.18554286319286462
[I 2024-04-16 01:59:20,432] Trial 37 finished with value: 0.18066117702596124 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.927527615447799, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18898732734511295
Fold 2 IBS: 0.1878387228485354
Fold 3 IBS: 0.18584838878907442
Fold 4 IBS: 0.20176513401286975
Fold 5 IBS: 0.1980065946518465
[I 2024-04-16 01:59:33,821] Trial 38 finished with value: 0.1924892335294878 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 413, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.22752773294338688}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17998400007564072
Fold 2 IBS: 0.1668284973568401
Fold 3 IBS: 0.1844288585354833
Fold 4 IBS: 0.1864703671417796
Fold 5 IBS: 0.18549779412503536
[I 2024-04-16 01:59:44,094] Trial 39 finished with value: 0.1806419034469558 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 395, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9298380017873809, 'min_weight_fraction_leaf': 0.12443904045417477}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.19739525553280404
Fold 2 IBS: 0.1991580825645237
Fold 3 IBS: 0.1908160522932353
Fold 4 IBS: 0.2108648699893906
Fold 5 IBS: 0.20525415655389037
[I 2024-04-16 01:59:51,008] Trial 40 finished with value: 0.2006976833867688 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8393239125172784, 'min_weight_fraction_leaf': 0.2776601558023945}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18022938402780667
Fold 2 IBS: 0.16672467510224806
Fold 3 IBS: 0.18478016395935146
Fold 4 IBS: 0.18505725419817942
Fold 5 IBS: 0.18499738141995034
[I 2024-04-16 02:00:02,295] Trial 41 finished with value: 0.1803577717415072 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9543142613189195, 'min_weight_fraction_leaf': 0.12203673286244354}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17977178159556786
Fold 2 IBS: 0.1648846924548364
Fold 3 IBS: 0.18522486265052154
Fold 4 IBS: 0.18475497257812473
Fold 5 IBS: 0.18410321441673297
[I 2024-04-16 02:00:15,043] Trial 42 finished with value: 0.17974790473915667 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9452765507108519, 'min_weight_fraction_leaf': 0.11124594841889346}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.19434886045869684
Fold 2 IBS: 0.1937482656990757
Fold 3 IBS: 0.18774938995929302
Fold 4 IBS: 0.2069666602426304
Fold 5 IBS: 0.20174569854155797
[I 2024-04-16 02:00:26,231] Trial 43 finished with value: 0.1969117749802508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503494540371628, 'min_weight_fraction_leaf': 0.16912809120322597}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.17791881709956506
Fold 2 IBS: 0.16086621549432498
Fold 3 IBS: 0.1866107993369831
Fold 4 IBS: 0.18206826755641561
Fold 5 IBS: 0.18254737423971062
[I 2024-04-16 02:00:36,388] Trial 44 finished with value: 0.17800229474539986 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996789958831329, 'min_weight_fraction_leaf': 0.1062495666001656}. Best is trial 44 with value: 0.17800229474539986.

Fold 1 IBS: 0.18107213977138975
Fold 2 IBS: 0.17375539456626857
Fold 3 IBS: 0.18442566650093445
Fold 4 IBS: 0.19068424307356363
Fold 5 IBS: 0.18831741970696433
[I 2024-04-16 02:00:46,326] Trial 45 finished with value: 0.18365097272382416 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9992649320581628, 'min_weight_fraction_leaf': 0.15624439720920977}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.19953982633918327
Fold 2 IBS: 0.19967504623742535
Fold 3 IBS: 0.19245042867286613
Fold 4 IBS: 0.2085347403492104
Fold 5 IBS: 0.20542311562702958
[I 2024-04-16 02:00:56,933] Trial 46 finished with value: 0.20112463144514292 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 471, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8649488262826621, 'min_weight_fraction_leaf': 0.10003378636590125}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18628122203639155
Fold 2 IBS: 0.18394244229194334
Fold 3 IBS: 0.18418434284415144
Fold 4 IBS: 0.2000447066326781
Fold 5 IBS: 0.19669443529653688
[I 2024-04-16 02:01:04,817] Trial 47 finished with value: 0.19022942982034025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 328, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9498767799232638, 'min_weight_fraction_leaf': 0.20999351713918613}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18671807379697955
Fold 2 IBS: 0.1852509952197599
Fold 3 IBS: 0.18550487325289164
Fold 4 IBS: 0.20047588792062881
Fold 5 IBS: 0.19727228734012894
[I 2024-04-16 02:01:15,207] Trial 48 finished with value: 0.19104442350607775 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.797873402462955, 'min_weight_fraction_leaf': 0.1860519578289726}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.1826607073352976
Fold 2 IBS: 0.175421589749594
Fold 3 IBS: 0.18312277636383603
Fold 4 IBS: 0.19167275635552322
Fold 5 IBS: 0.18980799753609187
[I 2024-04-16 02:01:28,846] Trial 49 finished with value: 0.18453716546806856 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 476, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.961215604578711, 'min_weight_fraction_leaf': 0.11365414847803179}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17958611811383737
Fold 2 IBS: 0.17743708698305577
Fold 3 IBS: 0.1852250945699171
Fold 4 IBS: 0.19623907958032022
Fold 5 IBS: 0.19263688422130817
[I 2024-04-16 02:01:32,717] Trial 50 finished with value: 0.18622485269368774 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7701980857578967, 'min_weight_fraction_leaf': 0.13552189689536387}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17789145417182875
Fold 2 IBS: 0.1616433832004363
Fold 3 IBS: 0.1864085525144377
Fold 4 IBS: 0.18238123808283335
Fold 5 IBS: 0.18355417475301875
[I 2024-04-16 02:01:43,448] Trial 51 finished with value: 0.17837576054451096 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 399, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9009463698475542, 'min_weight_fraction_leaf': 0.09217858789465802}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17799920113623321
Fold 2 IBS: 0.1605144874097507
Fold 3 IBS: 0.18702940084671463
Fold 4 IBS: 0.1819808205423802
Fold 5 IBS: 0.18038337030867524
[I 2024-04-16 02:01:51,728] Trial 52 finished with value: 0.1775814560487508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 354, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8951291579049074, 'min_weight_fraction_leaf': 0.08581751823710401}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17775260791357536
Fold 2 IBS: 0.16149694714321464
Fold 3 IBS: 0.18707407916258054
Fold 4 IBS: 0.18274340233986375
Fold 5 IBS: 0.18259760716876144
[I 2024-04-16 02:02:00,982] Trial 53 finished with value: 0.17833292874559917 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.09240390871992925}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17940640525802973
Fold 2 IBS: 0.16245697210383966
Fold 3 IBS: 0.1891181060291726
Fold 4 IBS: 0.18256414899356924
Fold 5 IBS: 0.18141515612084266
[I 2024-04-16 02:02:08,389] Trial 54 finished with value: 0.17899215770109078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8266050067672521, 'min_weight_fraction_leaf': 0.08824574600148365}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19512770880551733
Fold 2 IBS: 0.19505507233319871
Fold 3 IBS: 0.19092891056177175
Fold 4 IBS: 0.20445218046771954
Fold 5 IBS: 0.2016905007036287
[I 2024-04-16 02:02:16,227] Trial 55 finished with value: 0.19745087457436722 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8830194506473868, 'min_weight_fraction_leaf': 0.08551025986155897}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19639982363347272
Fold 2 IBS: 0.19605394572022347
Fold 3 IBS: 0.19089762812749347
Fold 4 IBS: 0.2039025193177431
Fold 5 IBS: 0.20198750112683878
[I 2024-04-16 02:02:22,710] Trial 56 finished with value: 0.19784828358515433 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8305267551869411, 'min_weight_fraction_leaf': 0.08769411360825642}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17994763927738225
Fold 2 IBS: 0.1548261798648236
Fold 3 IBS: 0.19395939238204377
Fold 4 IBS: 0.175460592586965
Fold 5 IBS: 0.1780360580615449
[I 2024-04-16 02:02:32,512] Trial 57 finished with value: 0.1764459724345519 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9047823438465082, 'min_weight_fraction_leaf': 0.052520359548060905}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.21397444187069029
Fold 2 IBS: 0.22136998164786137
Fold 3 IBS: 0.2048209672135687
Fold 4 IBS: 0.22466869218034594
Fold 5 IBS: 0.21857265758585154
[I 2024-04-16 02:02:40,477] Trial 58 finished with value: 0.21668134809966358 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8971095327680366, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17919617267498053
Fold 2 IBS: 0.15724293354129823
Fold 3 IBS: 0.18865418939534942
Fold 4 IBS: 0.17914737264855643
Fold 5 IBS: 0.17930084192384113
[I 2024-04-16 02:02:46,860] Trial 59 finished with value: 0.17670830203680515 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8551879186310293, 'min_weight_fraction_leaf': 0.052198438381039824}. Best is trial 57 with value: 0.1764459724345519.

Fold 1 IBS: 0.17659457791938485
Fold 2 IBS: 0.15948702371575116
Fold 3 IBS: 0.18725320428102982
Fold 4 IBS: 0.18157027728642194
Fold 5 IBS: 0.18138733472020935
[I 2024-04-16 02:02:55,822] Trial 60 finished with value: 0.17725848358455942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 346, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7897702249078459, 'min_weight_fraction_leaf': 0.017004106952235656}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17815851130122365
Fold 2 IBS: 0.15937759601308119
Fold 3 IBS: 0.18671233531081954
Fold 4 IBS: 0.18030514263303932
Fold 5 IBS: 0.18041925981213724
[I 2024-04-16 02:03:03,842] Trial 61 finished with value: 0.1769945690140602 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8618449302748573, 'min_weight_fraction_leaf': 0.05544116405394582}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.189985439243045
Fold 2 IBS: 0.18589864301215556
Fold 3 IBS: 0.1868011652028388
Fold 4 IBS: 0.1963593578324162
Fold 5 IBS: 0.19462526820614628
[I 2024-04-16 02:03:11,800] Trial 62 finished with value: 0.19073397469932035 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7867417360932117, 'min_weight_fraction_leaf': 0.05261239827242224}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17825665056431175
Fold 2 IBS: 0.15873188722190795
Fold 3 IBS: 0.18623232494405856
Fold 4 IBS: 0.1804776675580393
Fold 5 IBS: 0.18054470634521663
[I 2024-04-16 02:03:20,612] Trial 63 finished with value: 0.17684864732670685 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 370, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8646509137730156, 'min_weight_fraction_leaf': 0.021855538175638154}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17870866019509835
Fold 2 IBS: 0.15879041008416891
Fold 3 IBS: 0.1868471374565984
Fold 4 IBS: 0.17989027006562788
Fold 5 IBS: 0.18013032641306964
[I 2024-04-16 02:03:30,447] Trial 64 finished with value: 0.17687336084291264 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8648441638800866, 'min_weight_fraction_leaf': 0.01786212960035921}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17816324436800104
Fold 2 IBS: 0.16489393379706804
Fold 3 IBS: 0.18434438709838466
Fold 4 IBS: 0.1849311299136772
Fold 5 IBS: 0.18219012941004298
[I 2024-04-16 02:03:38,528] Trial 65 finished with value: 0.17890456491743478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 312, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.017748854587234637}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17911936362446912
Fold 2 IBS: 0.16110107360924447
Fold 3 IBS: 0.18681685101625886
Fold 4 IBS: 0.18222885762114663
Fold 5 IBS: 0.18129003273610622
[I 2024-04-16 02:03:44,182] Trial 66 finished with value: 0.17811123572144505 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7615860595939867, 'min_weight_fraction_leaf': 0.01711923253055358}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19752620497233223
Fold 2 IBS: 0.1978697596463517
Fold 3 IBS: 0.19204767218293306
Fold 4 IBS: 0.20544650914067045
Fold 5 IBS: 0.20224204696962983
[I 2024-04-16 02:03:51,793] Trial 67 finished with value: 0.19902643858238345 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6948127421387615, 'min_weight_fraction_leaf': 0.0007645315715799281}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18980037835825866
Fold 2 IBS: 0.18504474080399536
Fold 3 IBS: 0.18675479711869114
Fold 4 IBS: 0.19583872452973888
Fold 5 IBS: 0.1964614031322392
[I 2024-04-16 02:03:58,234] Trial 68 finished with value: 0.19078000878858464 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7554408511314311, 'min_weight_fraction_leaf': 0.05091993963276509}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19466218577890979
Fold 2 IBS: 0.19389682402255248
Fold 3 IBS: 0.1911241110746692
Fold 4 IBS: 0.2034533752298619
Fold 5 IBS: 0.20173582211641464
[I 2024-04-16 02:04:06,673] Trial 69 finished with value: 0.19697446364448162 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8049955125325536, 'min_weight_fraction_leaf': 0.06630598317301307}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18081283621129376
Fold 2 IBS: 0.16107815895963368
Fold 3 IBS: 0.18537244320497517
Fold 4 IBS: 0.18258777899134426
Fold 5 IBS: 0.1815710558255509
[I 2024-04-16 02:04:10,971] Trial 70 finished with value: 0.17828445463855955 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8704614691107458, 'min_weight_fraction_leaf': 0.03817571210017591}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.1784816385243448
Fold 2 IBS: 0.15527940159437076
Fold 3 IBS: 0.189332198745705
Fold 4 IBS: 0.17821728855635274
Fold 5 IBS: 0.17857494171269278
[I 2024-04-16 02:04:18,030] Trial 71 finished with value: 0.17597709382669321 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8554024477419847, 'min_weight_fraction_leaf': 0.025336147177118625}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17798712426248403
Fold 2 IBS: 0.15484687758413454
Fold 3 IBS: 0.19067949460417397
Fold 4 IBS: 0.17810023131975267
Fold 5 IBS: 0.17841198739744782
[I 2024-04-16 02:04:26,034] Trial 72 finished with value: 0.1760051430335986 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8330512937031878, 'min_weight_fraction_leaf': 0.018742428478884406}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17863483477490216
Fold 2 IBS: 0.1551139005400038
Fold 3 IBS: 0.18916719727949505
Fold 4 IBS: 0.17811149370150642
Fold 5 IBS: 0.1783525956517838
[I 2024-04-16 02:04:34,313] Trial 73 finished with value: 0.17587600438953827 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8535353080113882, 'min_weight_fraction_leaf': 0.02393524919371511}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17931869016352942
Fold 2 IBS: 0.15516920228584516
Fold 3 IBS: 0.19388065315077987
Fold 4 IBS: 0.17839512488731568
Fold 5 IBS: 0.17847323379272784
[I 2024-04-16 02:04:42,552] Trial 74 finished with value: 0.1770473808560396 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8501055473932629, 'min_weight_fraction_leaf': 0.028866969062217605}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.21400073415496554
Fold 2 IBS: 0.2208296768873117
Fold 3 IBS: 0.20504439468604338
Fold 4 IBS: 0.22482948519570425
Fold 5 IBS: 0.21793226667188703
[I 2024-04-16 02:04:49,118] Trial 75 finished with value: 0.21652731151918242 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.28939609623192764, 'min_weight_fraction_leaf': 0.38792353869222}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18092605908791307
Fold 2 IBS: 0.1626714178491272
Fold 3 IBS: 0.1886398695722679
Fold 4 IBS: 0.18093264680250482
Fold 5 IBS: 0.18045471816506836
[I 2024-04-16 02:04:54,660] Trial 76 finished with value: 0.17872494229537628 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827568227091456, 'min_weight_fraction_leaf': 0.07075108588012974}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17853049514002048
Fold 2 IBS: 0.1606985623136455
Fold 3 IBS: 0.18934483196588067
Fold 4 IBS: 0.18117152161929295
Fold 5 IBS: 0.18168995291214574
[I 2024-04-16 02:05:00,562] Trial 77 finished with value: 0.17828707279019707 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 253, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8619520401496605, 'min_weight_fraction_leaf': 0.0541974809924827}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19018486273820845
Fold 2 IBS: 0.18580998501512688
Fold 3 IBS: 0.18646870485036496
Fold 4 IBS: 0.20416606516994676
Fold 5 IBS: 0.1976686334381368
[I 2024-04-16 02:05:08,118] Trial 78 finished with value: 0.19285965024235677 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4023122117577047, 'min_weight_fraction_leaf': 0.011653305300887117}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18468957100688832
Fold 2 IBS: 0.16220991806931515
Fold 3 IBS: 0.18433081379618457
Fold 4 IBS: 0.17919815038465237
Fold 5 IBS: 0.18126334949504005
[I 2024-04-16 02:05:14,376] Trial 79 finished with value: 0.1783383605504161 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.03184523795085815}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17809409767141368
Fold 2 IBS: 0.16747623448062568
Fold 3 IBS: 0.18492844526895663
Fold 4 IBS: 0.18608517724457674
Fold 5 IBS: 0.18436399027788122
[I 2024-04-16 02:05:22,110] Trial 80 finished with value: 0.18018958898869078 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7484656416215983, 'min_weight_fraction_leaf': 0.04261824663727039}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17861172388733232
Fold 2 IBS: 0.15579353335819895
Fold 3 IBS: 0.1930699509858784
Fold 4 IBS: 0.17862157523488698
Fold 5 IBS: 0.17918780109521346
[I 2024-04-16 02:05:30,748] Trial 81 finished with value: 0.17705691691230202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 263, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8580633834636456, 'min_weight_fraction_leaf': 0.026226351015522897}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17739332474625047
Fold 2 IBS: 0.15403352099493925
Fold 3 IBS: 0.19030462796552475
Fold 4 IBS: 0.17855931327525473
Fold 5 IBS: 0.1790999880755793
[I 2024-04-16 02:05:38,822] Trial 82 finished with value: 0.1758781550115097 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8118689779244362, 'min_weight_fraction_leaf': 0.0010966926240786878}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1773851694171574
Fold 2 IBS: 0.16253921619926498
Fold 3 IBS: 0.18775729750357517
Fold 4 IBS: 0.1836022417123993
Fold 5 IBS: 0.18177710952263798
[I 2024-04-16 02:05:46,235] Trial 83 finished with value: 0.17861220687100693 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8057382985870164, 'min_weight_fraction_leaf': 0.009258817492808987}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1854433030470413
Fold 2 IBS: 0.17681758475146342
Fold 3 IBS: 0.18419070581251012
Fold 4 IBS: 0.19690664360230137
Fold 5 IBS: 0.19542658681834563
[I 2024-04-16 02:05:53,177] Trial 84 finished with value: 0.18775696480633236 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.00018800640948312233}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19527212215204012
Fold 2 IBS: 0.19258034396176488
Fold 3 IBS: 0.19043822340063868
Fold 4 IBS: 0.202063421121186
Fold 5 IBS: 0.2007148431354912
[I 2024-04-16 02:06:00,777] Trial 85 finished with value: 0.19621379075422415 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9164856547650563, 'min_weight_fraction_leaf': 0.04956990041330743}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1784741230904449
Fold 2 IBS: 0.16087953939758443
Fold 3 IBS: 0.1866329755757358
Fold 4 IBS: 0.18365448231497417
Fold 5 IBS: 0.1817122965130897
[I 2024-04-16 02:06:08,314] Trial 86 finished with value: 0.1782706833783658 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8799886531366731, 'min_weight_fraction_leaf': 0.0714128496838598}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18097049161570794
Fold 2 IBS: 0.1577854964552635
Fold 3 IBS: 0.18632859616594455
Fold 4 IBS: 0.17862370973831698
Fold 5 IBS: 0.1800955319809405
[I 2024-04-16 02:06:14,897] Trial 87 finished with value: 0.17676076519123468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8197308829626436, 'min_weight_fraction_leaf': 0.02805135094342286}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19437352689769452
Fold 2 IBS: 0.1865309874000275
Fold 3 IBS: 0.19048273944837096
Fold 4 IBS: 0.19874750141792227
Fold 5 IBS: 0.19780307418997603
[I 2024-04-16 02:06:21,990] Trial 88 finished with value: 0.19358756587079823 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 283, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8170223392194952, 'min_weight_fraction_leaf': 0.026015865108324397}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1843070555126035
Fold 2 IBS: 0.16138922163775485
Fold 3 IBS: 0.184029881060334
Fold 4 IBS: 0.18094300604589247
Fold 5 IBS: 0.18208306151695186
[I 2024-04-16 02:06:27,602] Trial 89 finished with value: 0.17855044515470733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.709051290189657, 'min_weight_fraction_leaf': 0.03884059880747235}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.18417873567489768
Fold 2 IBS: 0.17215507074054423
Fold 3 IBS: 0.18759974758071274
Fold 4 IBS: 0.1889870504957803
Fold 5 IBS: 0.18950903071510605
[I 2024-04-16 02:06:34,802] Trial 90 finished with value: 0.1844859270414082 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 262, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9722689668575789, 'min_weight_fraction_leaf': 0.013698489831834436}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17828049657703648
Fold 2 IBS: 0.15670442146325114
Fold 3 IBS: 0.1885595963781235
Fold 4 IBS: 0.17837564239035944
Fold 5 IBS: 0.17924664597888262
[I 2024-04-16 02:06:43,449] Trial 91 finished with value: 0.17623336055753064 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396105042050885, 'min_weight_fraction_leaf': 0.053257094236011215}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17808001067342502
Fold 2 IBS: 0.15510139507880186
Fold 3 IBS: 0.18938170342854968
Fold 4 IBS: 0.1775338584977204
Fold 5 IBS: 0.17890319352130446
[I 2024-04-16 02:06:50,784] Trial 92 finished with value: 0.17580003223996027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17659770951694037
Fold 2 IBS: 0.16139548906489803
Fold 3 IBS: 0.1883833499377513
Fold 4 IBS: 0.18122376165938103
Fold 5 IBS: 0.18108443878413408
[I 2024-04-16 02:06:57,767] Trial 93 finished with value: 0.17773694979262095 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7779337650340382, 'min_weight_fraction_leaf': 0.07493855611907659}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1788420501389833
Fold 2 IBS: 0.1563664608382856
Fold 3 IBS: 0.1914656292286683
Fold 4 IBS: 0.17846880498246692
Fold 5 IBS: 0.17925187035417264
[I 2024-04-16 02:07:03,515] Trial 94 finished with value: 0.17687896310851536 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8379618640137403, 'min_weight_fraction_leaf': 0.06135463764973173}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.18233221300286004
Fold 2 IBS: 0.1548941049902076
Fold 3 IBS: 0.1911036971629455
Fold 4 IBS: 0.17526110217876542
Fold 5 IBS: 0.17738838491733422
[I 2024-04-16 02:07:10,429] Trial 95 finished with value: 0.17619590045042255 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9112906365218221, 'min_weight_fraction_leaf': 0.035312691708068014}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.19307487236591833
Fold 2 IBS: 0.1896720972205889
Fold 3 IBS: 0.189921274941199
Fold 4 IBS: 0.19850258678674562
Fold 5 IBS: 0.19947771844377382
[I 2024-04-16 02:07:17,735] Trial 96 finished with value: 0.19412970995164514 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.915276824625892, 'min_weight_fraction_leaf': 0.043225362789876695}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17892075643860444
Fold 2 IBS: 0.15510444608753537
Fold 3 IBS: 0.19306794455023804
Fold 4 IBS: 0.17799888388058782
Fold 5 IBS: 0.1791674987979104
[I 2024-04-16 02:07:25,581] Trial 97 finished with value: 0.17685190595097522 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6707252385790339, 'min_weight_fraction_leaf': 0.03691531290573905}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.20874228003675835
Fold 2 IBS: 0.21425684765888878
Fold 3 IBS: 0.19860629371051958
Fold 4 IBS: 0.21913583881591187
Fold 5 IBS: 0.21337794366871632
[I 2024-04-16 02:07:34,355] Trial 98 finished with value: 0.210823840778159 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7396489612918897, 'min_weight_fraction_leaf': 0.3157312701103638}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1810496922027384
Fold 2 IBS: 0.15501841966956653
Fold 3 IBS: 0.19245123255364907
Fold 4 IBS: 0.17446547560484074
Fold 5 IBS: 0.17710424236035277
[I 2024-04-16 02:07:42,177] Trial 99 finished with value: 0.1760178124782295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8849892919469375, 'min_weight_fraction_leaf': 0.007259167100140962}. Best is trial 92 with value: 0.17580003223996027.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.17580003223996027], datetime_start=datetime.datetime(2024, 4, 16, 2, 6, 43, 466625), datetime_complete=datetime.datetime(2024, 4, 16, 2, 6, 50, 783133), params={'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=92, value=None)


* Best Score for IBS:
 0.17580003223996027

In [54]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.176

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=19, max_features=1, max_leaf_nodes=12,
                   max_samples=0.21404335777324493, min_samples_leaf=1,
                   min_samples_split=4,
                   min_weight_fraction_leaf=0.0013133682808468272,
                   n_estimators=405, random_state=123, warm_start=True)

C-index score: 0.572

ExtraSurvivalTrees(max_depth=14, max_features=None, max_leaf_nodes=6,
                   max_samples=0.8396800309305413, min_samples_leaf=5,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.02494499808293557,
                   n_estimators=305, oob_score=True, random_state=123)

IBS: 0.221

In [58]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 02:07:45,817] A new study created in memory with name: no-name-0586cbbe-ae78-4adc-9047-d88d54968e14

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:08:22,371] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:08:44,456] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:09:02,772] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:09:35,244] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:09:48,393] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:09:51,431] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:10:21,263] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:10:30,082] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:10:31,588] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 02:11:52,249] Trial 9 finished with value: 0.7610259439316011 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.7253521126760564
[I 2024-04-16 02:13:54,141] Trial 10 finished with value: 0.6762046627675529 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:16:12,294] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 02:18:07,323] Trial 12 finished with value: 0.7542227664538642 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:19:02,960] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:20:18,579] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:21:27,693] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:22:14,693] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:23:51,910] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:02,512] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:07,514] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:53,840] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 02:28:34,559] Trial 21 finished with value: 0.6762505605169181 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 02:30:07,423] Trial 22 finished with value: 0.713908524620727 and parameters: {'subsample': 0.8956069884856214, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2154325997461391, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.38657871816113815, 'max_features': 'auto', 'min_impurity_decrease': 5.581115247824534e-07, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:31:23,271] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7743503496065262, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.31930849090648333, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9663328483036315, 'min_weight_fraction_leaf': 0.441052304834414, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:32:18,585] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8969825748215434, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21976013005558012, 'n_estimators': 340, 'criterion': 'squared_error', 'ccp_alpha': 0.785180332493211, 'min_weight_fraction_leaf': 0.2669492013977464, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:33:26,637] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8840318412875596, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.27382248438555523, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 2.0183033060186855, 'min_weight_fraction_leaf': 0.33643534713187806, 'max_features': 'auto', 'min_impurity_decrease': 5.889654690360788e-06, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:34:36,890] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7565765917190008, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.4300954216773497, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6678836557349488, 'min_weight_fraction_leaf': 0.06207030473994396, 'max_features': 1, 'min_impurity_decrease': 7.622421032390112e-07, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:36:23,829] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.322970332048742, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 5.9472530603001, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 7.551787280023211e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:36:57,906] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.5232204998663266, 'n_estimators': 326, 'criterion': 'squared_error', 'ccp_alpha': 4.188554251555486, 'min_weight_fraction_leaf': 0.43612805409636834, 'max_features': 0.1, 'min_impurity_decrease': 3.2161459286083955e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:37:05,055] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.32499045544570565, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 2.694991982922698, 'min_weight_fraction_leaf': 0.37973053029520576, 'max_features': 'log2', 'min_impurity_decrease': 1.983769791843576e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:37:30,670] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.1618733123667288, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.29835074442775955, 'max_features': 'auto', 'min_impurity_decrease': 3.855449012555335e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:39:09,781] Trial 31 finished with value: 0.7183781009689083 and parameters: {'subsample': 0.9458857893837966, 'learning_rate': 0.016420196712320707, 'dropout_rate': 0.2035906465216125, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.36089352993330637, 'max_features': 'auto', 'min_impurity_decrease': 4.318534340206297e-07, 'validation_fraction': 0.9595045281115817, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 02:40:53,114] Trial 32 finished with value: 0.7475960929275194 and parameters: {'subsample': 0.8638126341310897, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.22569622133720652, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.019083703384414813, 'min_weight_fraction_leaf': 0.351646089861356, 'max_features': 'auto', 'min_impurity_decrease': 1.0352347378444166e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:42:30,124] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9565444847948921, 'learning_rate': 0.016942278074178134, 'dropout_rate': 0.26584476281814184, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.3586353681932053, 'max_features': 'auto', 'min_impurity_decrease': 1.3326513674306949e-07, 'validation_fraction': 0.8389914767654065, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:43:56,168] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7038358300021869, 'learning_rate': 0.026650337425697362, 'dropout_rate': 0.369220485987212, 'n_estimators': 472, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8672217172879074, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0420752279999204e-07, 'validation_fraction': 0.9169827663346786, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:45:09,781] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.8615302123878027, 'learning_rate': 0.016287667469869524, 'dropout_rate': 0.16621310899612352, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1524333738759642, 'min_weight_fraction_leaf': 0.16211724647631331, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:45:49,024] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6682496627875864, 'learning_rate': 0.030254735591726832, 'dropout_rate': 0.29166011812932907, 'n_estimators': 299, 'criterion': 'squared_error', 'ccp_alpha': 0.48701662298918014, 'min_weight_fraction_leaf': 0.24844276308137436, 'max_features': 'auto', 'min_impurity_decrease': 2.2923203534620568e-05, 'validation_fraction': 0.8152696073327098, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:46:22,279] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7883126136564298, 'learning_rate': 0.02225236619873, 'dropout_rate': 0.7511928761026783, 'n_estimators': 408, 'criterion': 'squared_error', 'ccp_alpha': 1.198246212835568, 'min_weight_fraction_leaf': 0.42198945643308866, 'max_features': None, 'min_impurity_decrease': 8.54824079758415e-06, 'validation_fraction': 0.36353542989298265, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:47:49,699] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0010786268484829992, 'dropout_rate': 0.4076069474884072, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.295727563116735, 'max_features': 'auto', 'min_impurity_decrease': 1.0214527419957568e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:49:09,203] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.041857701576065075, 'dropout_rate': 0.3444296796757608, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.49564059074376393, 'max_features': 1, 'min_impurity_decrease': 2.966650399906854e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:50:05,481] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5863013406787322, 'learning_rate': 0.007311607072090859, 'dropout_rate': 0.22290618957651392, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 0.5271854997531392, 'min_weight_fraction_leaf': 0.2674270064426415, 'max_features': 'auto', 'min_impurity_decrease': 2.2073664358493507e-07, 'validation_fraction': 0.6520524706411407, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 10}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6455399061032864
[I 2024-04-16 02:50:05,882] Trial 41 finished with value: 0.6429727820316606 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.01362396235680392, 'dropout_rate': 0.2062435369784147, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.01657550447328801, 'min_weight_fraction_leaf': 0.3505399688940837, 'max_features': 'auto', 'min_impurity_decrease': 3.2101990795082183e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6774891774891775
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7394366197183099
[I 2024-04-16 02:51:46,120] Trial 42 finished with value: 0.7155999282604174 and parameters: {'subsample': 0.8533107407997301, 'learning_rate': 0.007773927115663986, 'dropout_rate': 0.13112078909045524, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.002608770948556355, 'min_weight_fraction_leaf': 0.4128432753433128, 'max_features': 'auto', 'min_impurity_decrease': 5.944083612909987e-07, 'validation_fraction': 0.8846352497042296, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:37,465] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8537828670002746, 'learning_rate': 0.006387564095638705, 'dropout_rate': 0.14103084365529428, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.817694027019807, 'min_weight_fraction_leaf': 0.4055199685421495, 'max_features': 'auto', 'min_impurity_decrease': 1.0127188716001679e-07, 'validation_fraction': 0.8846775181555923, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:55:02,016] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9979692688170061, 'learning_rate': 0.018866368595143467, 'dropout_rate': 0.13470507680405208, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.1995459782383484, 'min_weight_fraction_leaf': 0.46282880746501454, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7785221066313981, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:56:39,955] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.9423581992051376, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.1841937912472535, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.415353860249426, 'min_weight_fraction_leaf': 0.21565594544774125, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.9726137478639892, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:56:50,144] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8422605515062627, 'learning_rate': 0.023740342140917903, 'dropout_rate': 0.9694253886674298, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 6.2946137459239395, 'min_weight_fraction_leaf': 0.32020062193032595, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0058604443673675e-07, 'validation_fraction': 0.8666993731020032, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:58:35,134] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.8213077858159359, 'learning_rate': 0.006066129837698666, 'dropout_rate': 0.2502078347914406, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 1.0929789618945918, 'min_weight_fraction_leaf': 0.37165158771817175, 'max_features': 'log2', 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.7292699872905781, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:59:15,294] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7434813106553043, 'learning_rate': 0.014252633864159536, 'dropout_rate': 0.10308804442602489, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 0.43583456106887075, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 'auto', 'min_impurity_decrease': 1.1669342789968816e-06, 'validation_fraction': 0.9922167438954732, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:59:32,793] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7918904765497661, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.46610361399140793, 'max_features': None, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8725986413596462, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:00:40,809] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9263228105960017, 'learning_rate': 0.03241286314321831, 'dropout_rate': 0.28503824367896063, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.3883012665777896, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 5.669547081135241e-07, 'validation_fraction': 0.21769072749948642, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7347417840375586
[I 2024-04-16 03:02:09,192] Trial 51 finished with value: 0.7185570650203711 and parameters: {'subsample': 0.8666208085311428, 'learning_rate': 0.010299237341157315, 'dropout_rate': 0.22486517268782114, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.01237319335130728, 'min_weight_fraction_leaf': 0.40520668278071015, 'max_features': 'auto', 'min_impurity_decrease': 4.3165690993230386e-07, 'validation_fraction': 0.9299180470052416, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7279411764705882
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 03:03:30,894] Trial 52 finished with value: 0.7047318894129233 and parameters: {'subsample': 0.862657875185063, 'learning_rate': 0.008306104796295998, 'dropout_rate': 0.2416732200644876, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.03660243985093782, 'min_weight_fraction_leaf': 0.42223276607292903, 'max_features': 'auto', 'min_impurity_decrease': 1.9405719092810494e-07, 'validation_fraction': 0.9395823090270392, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:05:08,785] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.967375882472721, 'learning_rate': 0.001394900878889816, 'dropout_rate': 0.1429837848690379, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.45374308869283775, 'min_weight_fraction_leaf': 0.4108404544677715, 'max_features': 'auto', 'min_impurity_decrease': 4.0655981745194066e-07, 'validation_fraction': 0.8259835575505652, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:55,760] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8134129014758551, 'learning_rate': 0.019733381620994493, 'dropout_rate': 0.18641432881009587, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.9596523069530926, 'min_weight_fraction_leaf': 0.2970013736941614, 'max_features': 'auto', 'min_impurity_decrease': 1.1580334563112213e-06, 'validation_fraction': 0.8996663522529539, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:07:48,241] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9195938698764112, 'learning_rate': 0.015173363534313505, 'dropout_rate': 0.3034930079612927, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.35259963018802765, 'min_weight_fraction_leaf': 0.36508275980555405, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.9545460877946491, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:09:03,690] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.5150383761242161, 'learning_rate': 0.004332984500606809, 'dropout_rate': 0.23996644019536584, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6264958328369468, 'min_weight_fraction_leaf': 0.3385656815459147, 'max_features': 'auto', 'min_impurity_decrease': 5.479611541769766e-07, 'validation_fraction': 0.9991586611408243, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 03:10:40,139] Trial 57 finished with value: 0.7056496649292628 and parameters: {'subsample': 0.8773751542246392, 'learning_rate': 0.008949552280352413, 'dropout_rate': 0.35136020576582316, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.001936457287774803, 'min_weight_fraction_leaf': 0.46006445679681335, 'max_features': 1, 'min_impurity_decrease': 4.834524920287448e-06, 'validation_fraction': 0.5189236064802895, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:12:19,902] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.6843244921733918, 'learning_rate': 0.0253510504546932, 'dropout_rate': 0.12033118040350205, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 1.625653153563989, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'auto', 'min_impurity_decrease': 1.5983704938418812e-07, 'validation_fraction': 0.7886847055500306, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:13:16,646] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.021369220605781735, 'dropout_rate': 0.4274904250363094, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.4410912197424578, 'max_features': 0.1, 'min_impurity_decrease': 3.251577586017116e-07, 'validation_fraction': 0.8548774558884649, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:13:34,019] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.18796169351263226, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 2.934583742024675, 'min_weight_fraction_leaf': 0.22745666702108258, 'max_features': 'log2', 'min_impurity_decrease': 1.7635925207609514e-06, 'validation_fraction': 0.8928900471979833, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:14:53,281] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.9082876532055691, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.22106826324294734, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22580244780696104, 'min_weight_fraction_leaf': 0.39038531498517337, 'max_features': 'auto', 'min_impurity_decrease': 6.513707268856941e-07, 'validation_fraction': 0.9307105316317981, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:16:30,905] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.9763302214447585, 'learning_rate': 0.01082289338801184, 'dropout_rate': 0.16671702405067812, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.7562237450148781, 'min_weight_fraction_leaf': 0.4020635676726066, 'max_features': 'auto', 'min_impurity_decrease': 9.006731163870761e-07, 'validation_fraction': 0.9167969646120265, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.744131455399061
[I 2024-04-16 03:18:08,726] Trial 63 finished with value: 0.7378685391643164 and parameters: {'subsample': 0.8703294082808486, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.2614766602947102, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.37595194847909125, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.9646429973127362, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:19:43,349] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7961678718772995, 'learning_rate': 0.015415575577593231, 'dropout_rate': 0.262554001169913, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.2777045506790212, 'min_weight_fraction_leaf': 0.33434502833689206, 'max_features': 'auto', 'min_impurity_decrease': 3.33975749875224e-07, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:21:12,627] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8385594937622445, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.30265220308227164, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.29056375204041135, 'min_weight_fraction_leaf': 0.28320128906700315, 'max_features': 'auto', 'min_impurity_decrease': 1.5031409606569138e-07, 'validation_fraction': 0.962588947418926, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:22:40,068] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8825125214383175, 'learning_rate': 0.01896416177644482, 'dropout_rate': 0.3845297883432178, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 2.1083391199212573, 'min_weight_fraction_leaf': 0.37068365181765817, 'max_features': 'auto', 'min_impurity_decrease': 2.926750067783851e-07, 'validation_fraction': 0.8532835495181553, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:23:56,364] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4585158632928328, 'learning_rate': 0.014185974978345665, 'dropout_rate': 0.20713420518497186, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.31472432527464905, 'max_features': 'sqrt', 'min_impurity_decrease': 4.927665175660364e-07, 'validation_fraction': 0.9061207180731781, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:25:12,034] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.9444579521154932, 'learning_rate': 0.003984164164187884, 'dropout_rate': 0.3349732603740458, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 1.078654850128927, 'min_weight_fraction_leaf': 0.1817947096952169, 'max_features': 'auto', 'min_impurity_decrease': 1.3822768751381375e-06, 'validation_fraction': 0.9998779842696178, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:25:59,986] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7351244679725103, 'learning_rate': 0.021607496405331474, 'dropout_rate': 0.6578270843665299, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.41822793529640967, 'max_features': 'auto', 'min_impurity_decrease': 7.981891756908656e-06, 'validation_fraction': 0.8252701554197789, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 03:27:16,735] Trial 70 finished with value: 0.7431871031407425 and parameters: {'subsample': 0.7696833733505561, 'learning_rate': 0.009479076517851487, 'dropout_rate': 0.27892959003506596, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.010016393064755276, 'min_weight_fraction_leaf': 0.38115268230138605, 'max_features': None, 'min_impurity_decrease': 1.0506244573812146e-07, 'validation_fraction': 0.7475037972329144, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7065727699530516
[I 2024-04-16 03:28:32,252] Trial 71 finished with value: 0.722533881479949 and parameters: {'subsample': 0.7726307722867607, 'learning_rate': 0.009349407530944867, 'dropout_rate': 0.272889788803047, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.43478396682346765, 'max_features': None, 'min_impurity_decrease': 1.417211124243175e-07, 'validation_fraction': 0.6051329974465358, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:29:58,589] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7701057123127394, 'learning_rate': 0.009957649760499912, 'dropout_rate': 0.27848137285412433, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.7357633085189087, 'min_weight_fraction_leaf': 0.37805750469189997, 'max_features': None, 'min_impurity_decrease': 1.0230782331935316e-07, 'validation_fraction': 0.6095946706874, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:31:02,056] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.82176382526325, 'learning_rate': 0.05058817311100894, 'dropout_rate': 0.23811185280532784, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.35666680166132303, 'min_weight_fraction_leaf': 0.4363333364980036, 'max_features': None, 'min_impurity_decrease': 1.4978008424793533e-07, 'validation_fraction': 0.6393756125190079, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:32:04,138] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6354098366620761, 'learning_rate': 0.013009902635057455, 'dropout_rate': 0.3101706081176934, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7099066346200665, 'min_weight_fraction_leaf': 0.4804502891962041, 'max_features': None, 'min_impurity_decrease': 2.271616193402817e-07, 'validation_fraction': 0.6862699083190502, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:33:19,020] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9104967643697162, 'learning_rate': 0.01724034992100258, 'dropout_rate': 0.26334849962817525, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.5692251904189567, 'min_weight_fraction_leaf': 0.35851813148439854, 'max_features': None, 'min_impurity_decrease': 2.0843558415731406e-07, 'validation_fraction': 0.5063775748030491, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:34:37,598] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5556564275523779, 'learning_rate': 0.0033204528527945613, 'dropout_rate': 0.3636837900816117, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3042363908259532, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.2249424139094463e-07, 'validation_fraction': 0.561045056767258, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:36:05,719] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7208569038924214, 'learning_rate': 0.026256982803923905, 'dropout_rate': 0.2305409399859041, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.9525490995769573, 'min_weight_fraction_leaf': 0.398138662499872, 'max_features': None, 'min_impurity_decrease': 3.9802168951657813e-07, 'validation_fraction': 0.7435745226595007, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.7723004694835681
[I 2024-04-16 03:37:05,967] Trial 78 finished with value: 0.7520537875882294 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.012134054211554952, 'dropout_rate': 0.17020981110797495, 'n_estimators': 371, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25792648841120175, 'max_features': None, 'min_impurity_decrease': 0.0002607692087694095, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 03:37:19,926] Trial 79 finished with value: 0.7612651729154684 and parameters: {'subsample': 0.5770898503146864, 'learning_rate': 0.005718089536250872, 'dropout_rate': 0.8831816560103296, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.006784676195889549, 'min_weight_fraction_leaf': 0.26783577777991785, 'max_features': None, 'min_impurity_decrease': 0.00026754667959111344, 'validation_fraction': 0.45556658035861064, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:37:30,684] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.005715181757518938, 'dropout_rate': 0.8564920404565602, 'n_estimators': 301, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.2585934440223751, 'max_features': None, 'min_impurity_decrease': 0.00022588848940598272, 'validation_fraction': 0.4281000770625221, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 03:37:20,397] Trial 81 finished with value: 0.7574041343834572 and parameters: {'subsample': 0.573469759644561, 'learning_rate': 0.00917313652468523, 'dropout_rate': 0.7551006664918564, 'n_estimators': 378, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025432538716388925, 'min_weight_fraction_leaf': 0.2330447322703676, 'max_features': None, 'min_impurity_decrease': 0.0003172843737611832, 'validation_fraction': 0.47647246663093756, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:38:11,077] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.6061238477976733, 'learning_rate': 0.012604022944147218, 'dropout_rate': 0.8294471229873877, 'n_estimators': 356, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5341063025845167, 'min_weight_fraction_leaf': 0.19664785169557314, 'max_features': None, 'min_impurity_decrease': 0.0007825748634975355, 'validation_fraction': 0.3806000784667706, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:38:23,710] Trial 83 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6535018868517685, 'learning_rate': 0.0014826800610252661, 'dropout_rate': 0.8992417742346922, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20169466462041857, 'min_weight_fraction_leaf': 0.22451223837031314, 'max_features': None, 'min_impurity_decrease': 0.0003609663069928288, 'validation_fraction': 0.4711031887993497, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:38:48,047] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.58189223841496, 'learning_rate': 0.008316297732970858, 'dropout_rate': 0.6818395627907664, 'n_estimators': 335, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.28172882309407266, 'max_features': None, 'min_impurity_decrease': 0.001202775121736422, 'validation_fraction': 0.38945203718855725, 'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 79 with value: 0.7612651729154684.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:39:08,154] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.6947678980383888, 'learning_rate': 0.06101724551624799, 'dropout_rate': 0.7652597742653805, 'n_estimators': 317, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5339563287597978, 'min_weight_fraction_leaf': 0.24506733493657065, 'max_features': None, 'min_impurity_decrease': 0.0001261040433430487, 'validation_fraction': 0.46765139398223676, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:39:26,022] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5329646889170038, 'learning_rate': 0.006001760143614843, 'dropout_rate': 0.8650393351469537, 'n_estimators': 381, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2772447793960837, 'min_weight_fraction_leaf': 0.2595916601449126, 'max_features': None, 'min_impurity_decrease': 8.277387430400139e-05, 'validation_fraction': 0.5331294902958005, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:40:09,458] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5772171688575647, 'learning_rate': 0.012297427382052604, 'dropout_rate': 0.5450508211122536, 'n_estimators': 389, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8948782241791482, 'min_weight_fraction_leaf': 0.30432090537719336, 'max_features': None, 'min_impurity_decrease': 0.000380077265080333, 'validation_fraction': 0.5815548971606083, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:40:14,632] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4900792232135173, 'learning_rate': 0.01688118268369649, 'dropout_rate': 0.9961303410511458, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 0.32151562869669414, 'min_weight_fraction_leaf': 0.22873481062830656, 'max_features': None, 'min_impurity_decrease': 0.0016050858690837527, 'validation_fraction': 0.47521875145819903, 'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 03:40:40,351] Trial 89 finished with value: 0.7615428784886943 and parameters: {'subsample': 0.6088139660412204, 'learning_rate': 0.007354720529210388, 'dropout_rate': 0.7165927205059781, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019083182133763817, 'min_weight_fraction_leaf': 0.16713831321323547, 'max_features': None, 'min_impurity_decrease': 6.11919023761631e-05, 'validation_fraction': 0.33082778557332754, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:41:03,532] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.6135996513302981, 'learning_rate': 0.0030759059571325367, 'dropout_rate': 0.714239153071518, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5934237823972953, 'min_weight_fraction_leaf': 0.15409787484394483, 'max_features': 1, 'min_impurity_decrease': 0.00026420223842921306, 'validation_fraction': 0.3182942803078493, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 03:41:45,908] Trial 91 finished with value: 0.7168916928997893 and parameters: {'subsample': 0.6770337747529735, 'learning_rate': 0.007750641496074201, 'dropout_rate': 0.49424724681798277, 'n_estimators': 365, 'criterion': 'friedman_mse', 'ccp_alpha': 0.15430903718460776, 'min_weight_fraction_leaf': 0.16791051943811458, 'max_features': None, 'min_impurity_decrease': 0.00012772803486333308, 'validation_fraction': 0.2316993389350888, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:42:04,290] Trial 92 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6546522174060683, 'learning_rate': 0.009421883094809201, 'dropout_rate': 0.8281440643598538, 'n_estimators': 347, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20594179048085923, 'min_weight_fraction_leaf': 0.1883593742681352, 'max_features': None, 'min_impurity_decrease': 0.0006394831666927118, 'validation_fraction': 0.2857429575523451, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 03:42:20,362] Trial 93 finished with value: 0.7646572367824584 and parameters: {'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:42:37,412] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.5329981668085512, 'learning_rate': 0.00588357274756517, 'dropout_rate': 0.9010663710372596, 'n_estimators': 398, 'criterion': 'friedman_mse', 'ccp_alpha': 0.795356671502603, 'min_weight_fraction_leaf': 0.2746770457528657, 'max_features': None, 'min_impurity_decrease': 4.317472301123062e-05, 'validation_fraction': 0.5341505661514357, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:42:52,084] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.6002877490535967, 'learning_rate': 0.0013964687008740234, 'dropout_rate': 0.913293216331538, 'n_estimators': 380, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4770423805467064, 'min_weight_fraction_leaf': 0.23547436381465842, 'max_features': 0.1, 'min_impurity_decrease': 6.5600170925824e-05, 'validation_fraction': 0.1768997582284634, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:43:04,608] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.5679830672067219, 'learning_rate': 0.014679960066405966, 'dropout_rate': 0.9491815550373798, 'n_estimators': 409, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0851736428778953, 'min_weight_fraction_leaf': 0.2093965001338856, 'max_features': 'log2', 'min_impurity_decrease': 0.0003929451723108634, 'validation_fraction': 0.4438191336127031, 'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 93 with value: 0.7646572367824584.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:43:27,337] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.6256579983686182, 'learning_rate': 0.019674657185705456, 'dropout_rate': 0.7920862318111374, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.09841883603325133, 'max_features': None, 'min_impurity_decrease': 0.0029478086506526746, 'validation_fraction': 0.4123056392425912, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:43:50,452] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5456143354363114, 'learning_rate': 0.012065355654311702, 'dropout_rate': 0.7084124127731201, 'n_estimators': 352, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8220715155379084, 'min_weight_fraction_leaf': 0.2513160795401591, 'max_features': None, 'min_impurity_decrease': 0.00015199016859086491, 'validation_fraction': 0.337785152154958, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-16 03:43:53,713] A new study created in memory with name: no-name-e28a9a47-5ca3-4e62-85cb-39fd586e7a9e

Fold 5 C-index: 0.5
[I 2024-04-16 03:43:53,688] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.599460814358584, 'learning_rate': 0.0043948047101492775, 'dropout_rate': 0.5980587986289647, 'n_estimators': 93, 'criterion': 'friedman_mse', 'ccp_alpha': 6.574588525520643, 'min_weight_fraction_leaf': 0.2853352301155438, 'max_features': None, 'min_impurity_decrease': 0.0002068890339707658, 'validation_fraction': 0.4936737452445755, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 93 with value: 0.7646572367824584.


* Best trial for C-index:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.7646572367824584], datetime_start=datetime.datetime(2024, 4, 16, 3, 42, 4, 295521), datetime_complete=datetime.datetime(2024, 4, 16, 3, 42, 20, 360858), params={'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=93, value=None)


* Best Score for C-index:
 0.7646572367824584

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:44:22,321] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:44:37,493] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:44:54,134] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:45:21,152] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:45:33,283] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:45:35,937] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:46:02,874] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:46:11,973] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:46:13,035] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21267714729986278
Fold 2 IBS: 0.21995458442119498
Fold 3 IBS: 0.2035491555712707
Fold 4 IBS: 0.22393486370134422
Fold 5 IBS: 0.21704380099016626
[I 2024-04-16 03:47:15,074] Trial 9 finished with value: 0.21543191039676776 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21361208429589837
Fold 2 IBS: 0.2211926211265032
Fold 3 IBS: 0.20422163542183314
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21784292940455638
[I 2024-04-16 03:48:55,197] Trial 10 finished with value: 0.21628654622010784 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:50:42,633] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21383702367729038
Fold 2 IBS: 0.22138950456459866
Fold 3 IBS: 0.20443495965406222
Fold 4 IBS: 0.22467340762574997
Fold 5 IBS: 0.21799662270999748
[I 2024-04-16 03:52:14,380] Trial 12 finished with value: 0.21646630364633973 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 03:52:58,973] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:54:14,482] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:55:20,091] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:55:56,059] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:57:23,984] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:58:06,713] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:58:13,478] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:59:29,917] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21372933425701268
Fold 2 IBS: 0.2215356606685715
Fold 3 IBS: 0.2044331250210804
Fold 4 IBS: 0.22465964732749286
Fold 5 IBS: 0.21808855196539592
[I 2024-04-16 04:00:58,462] Trial 21 finished with value: 0.2164892638479107 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21261860662587898
Fold 2 IBS: 0.2196324435594265

Fold 3 IBS: 0.20356521623761553
Fold 4 IBS: 0.22397661990425946
Fold 5 IBS: 0.21681927203314136
[I 2024-04-16 04:02:39,929] Trial 22 finished with value: 0.21532243167206438 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:03:58,748] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:04:45,230] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:05:31,135] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:06:42,185] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:06:48,198] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:07:12,180] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:08:17,394] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:08:42,457] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2135108348694222
Fold 2 IBS: 0.221167731954742
Fold 3 IBS: 0.20422105908762206
Fold 4 IBS: 0.22456358064764176
Fold 5 IBS: 0.21787287595995244
[I 2024-04-16 04:10:02,458] Trial 31 finished with value: 0.2162672165038761 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21277031226041587
Fold 2 IBS: 0.21977571218645117
Fold 3 IBS: 0.2037868553635057
Fold 4 IBS: 0.22437947964183458
Fold 5 IBS: 0.2169740152088292
[I 2024-04-16 04:11:13,485] Trial 32 finished with value: 0.2155372749322073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:11:58,502] Trial 33 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9175730211318314, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.23558036461669868, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 2.2672612842512112e-05, 'validation_fraction': 0.8391863465064515, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:12:48,989] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6818728654527908, 'learning_rate': 0.014570474664799389, 'dropout_rate': 0.39687420252491534, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9857366581537508, 'min_weight_fraction_leaf': 0.2451263696303153, 'max_features': 'sqrt', 'min_impurity_decrease': 7.173213136739857e-06, 'validation_fraction': 0.9231140468377321, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:13:04,510] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7474352307553052, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.29459319086620417, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 7.199479090473024e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:14:11,027] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.3498267997183648, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.2894426185614589, 'max_features': 'auto', 'min_impurity_decrease': 6.773052750173388e-05, 'validation_fraction': 0.7819324141806283, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:14:13,359] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.23919145342953393, 'max_features': None, 'min_impurity_decrease': 2.5414170052989375e-06, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:14:52,271] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8670579303141319, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.1728262906688144, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42202283765123816, 'min_weight_fraction_leaf': 0.35239546646921105, 'max_features': 'auto', 'min_impurity_decrease': 0.00017081434930634308, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:15:27,599] Trial 39 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8154589849054708, 'learning_rate': 0.006878494063124208, 'dropout_rate': 0.5323261217237781, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 1.1477698683125066, 'min_weight_fraction_leaf': 0.11023361948341703, 'max_features': 1, 'min_impurity_decrease': 1.7677159455067355e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:16:26,304] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.22290618957651392, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.5274073849776741, 'min_weight_fraction_leaf': 0.2739610635014299, 'max_features': 'auto', 'min_impurity_decrease': 2.272398816394983e-07, 'validation_fraction': 0.8717079478922802, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2111176339922491
Fold 2 IBS: 0.21706325506301344
Fold 3 IBS: 0.20271114308166202
Fold 4 IBS: 0.22388756035618385
Fold 5 IBS: 0.21496756928312347
[I 2024-04-16 04:17:43,007] Trial 41 finished with value: 0.21394943235524638 and parameters: {'subsample': 0.993176118879571, 'learning_rate': 0.01271988915310228, 'dropout_rate': 0.152367046323752, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.19182471840022747, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21394943235524638.
Fold 1 IBS: 0.21089915783305027
Fold 2 IBS: 0.21498627855376068
Fold 3 IBS: 0.2034648608532915
Fold 4 IBS: 0.22110504116581475
Fold 5 IBS: 0.21385442301724614
[I 2024-04-16 04:19:11,240] Trial 42 finished with value: 0.21286195228463267 and parameters: {'subsample': 0.9646924257252548, 'learning_rate': 0.012507391626216524, 'dropout_rate': 0.10802959125648778, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327408119788757, 'min_weight_fraction_leaf': 0.13510597987400375, 'max_features': 'auto', 'min_impurity_decrease': 1.0593992090305253e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:20:48,489] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828284890903175, 'learning_rate': 0.011543268886217308, 'dropout_rate': 0.11584589616484722, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.09682559138790292, 'max_features': 'auto', 'min_impurity_decrease': 1.0125868029922384e-07, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:22:01,750] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992870370700113, 'learning_rate': 0.022847552015173876, 'dropout_rate': 0.1556807870961761, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.1403134453903068, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21224782790603694
Fold 2 IBS: 0.2189260608342495
Fold 3 IBS: 0.20307124042767
Fold 4 IBS: 0.22313607826909793
Fold 5 IBS: 0.216439921823279
[I 2024-04-16 04:22:30,477] Trial 45 finished with value: 0.2147642258520667 and parameters: {'subsample': 0.8888212863898438, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.20487736976615575, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.027893207681183953, 'min_weight_fraction_leaf': 0.06753391487815072, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9448766575733668, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:22:45,094] Trial 46 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.016684121596597847, 'dropout_rate': 0.10891325683572217, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.04784747079432074, 'max_features': 0.1, 'min_impurity_decrease': 2.0166271580558924e-07, 'validation_fraction': 0.24435732275143762, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:23:04,049] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7729061863940228, 'learning_rate': 0.02995584278149796, 'dropout_rate': 0.19790330487666663, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.05716507411653311, 'max_features': 0.1, 'min_impurity_decrease': 1.0699422270078741e-07, 'validation_fraction': 0.9565097869700105, 'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:23:37,352] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8446010144291817, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.14247687075474555, 'n_estimators': 294, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 0.1, 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.8246274171002186, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:23:59,941] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6917414996198523, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.2874751071933402, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.08230947204902768, 'max_features': 0.1, 'min_impurity_decrease': 1.8211699167585496e-07, 'validation_fraction': 0.6513576271964052, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:24:18,776] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.019482931131151772, 'dropout_rate': 0.6676032114338903, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.013701950422388753, 'max_features': 'log2', 'min_impurity_decrease': 7.041814507237016e-07, 'validation_fraction': 0.7324600365192867, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2125423492162011
Fold 2 IBS: 0.21917859422188082
Fold 3 IBS: 0.20326597997084148
Fold 4 IBS: 0.22346421338690958
Fold 5 IBS: 0.21658511688910384
[I 2024-04-16 04:25:37,111] Trial 51 finished with value: 0.21500725073698734 and parameters: {'subsample': 0.9574902141624301, 'learning_rate': 0.013974517784402708, 'dropout_rate': 0.19663405810878032, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288632756573364, 'min_weight_fraction_leaf': 0.1845530130003769, 'max_features': 'sqrt', 'min_impurity_decrease': 5.505988736711189e-07, 'validation_fraction': 0.8981152080635156, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:26:57,370] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8963301244448798, 'learning_rate': 0.014496942793188729, 'dropout_rate': 0.149261379708028, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.3267109398107992, 'min_weight_fraction_leaf': 0.19350109364955276, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0314361105633666e-07, 'validation_fraction': 0.8673271583656655, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:27:54,752] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.937858776808653, 'learning_rate': 0.01317678110087918, 'dropout_rate': 0.20949679348390188, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.9371275797883157, 'min_weight_fraction_leaf': 0.16718449303286065, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0035393968280476e-07, 'validation_fraction': 0.9639725916044029, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:28:03,041] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5502453589475278, 'learning_rate': 0.005289059095661144, 'dropout_rate': 0.16758744743711101, 'n_estimators': 147, 'criterion': 'squared_error', 'ccp_alpha': 0.6055238018097719, 'min_weight_fraction_leaf': 0.1222904374725215, 'max_features': 'sqrt', 'min_impurity_decrease': 8.119424084486158e-07, 'validation_fraction': 0.8019436577478607, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21151156199161855
Fold 2 IBS: 0.21784621797452874

Fold 3 IBS: 0.20286393718880646
Fold 4 IBS: 0.22391249179729633
Fold 5 IBS: 0.21519882725417372
[I 2024-04-16 04:29:10,109] Trial 55 finished with value: 0.21426660724128474 and parameters: {'subsample': 0.9703353679292269, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.2676210325613897, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.036860238643527846, 'min_weight_fraction_leaf': 0.21798842867076448, 'max_features': None, 'min_impurity_decrease': 4.086647023052284e-07, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:29:59,367] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9556274374724505, 'learning_rate': 0.022777236721630217, 'dropout_rate': 0.36674252455714285, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.3101553395317078, 'min_weight_fraction_leaf': 0.21445816437013876, 'max_features': None, 'min_impurity_decrease': 4.99089267664694e-07, 'validation_fraction': 0.8444326224317742, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2111687028051771
Fold 2 IBS: 0.2144165092431595
Fold 3 IBS: 0.20113060921449374
Fold 4 IBS: 0.22322228050971296
Fold 5 IBS: 0.21261135031718192
[I 2024-04-16 04:30:00,639] Trial 57 finished with value: 0.21250989041794505 and parameters: {'subsample': 0.9885544496318819, 'learning_rate': 0.02570846317737359, 'dropout_rate': 0.11524078732039367, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.0019474604343284706, 'min_weight_fraction_leaf': 0.1539893411018015, 'max_features': None, 'min_impurity_decrease': 3.011740016899961e-07, 'validation_fraction': 0.8976605224112223, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:30:01,050] Trial 58 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9760257284010853, 'learning_rate': 0.044170756425452734, 'dropout_rate': 0.10695167335108825, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 0.7470878188226159, 'min_weight_fraction_leaf': 0.1623750980802567, 'max_features': None, 'min_impurity_decrease': 3.402621023187449e-07, 'validation_fraction': 0.8839190525574698, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:30:04,577] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8651178500686678, 'learning_rate': 0.031729459746086146, 'dropout_rate': 0.1294932593082019, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 2.4509996240950476, 'min_weight_fraction_leaf': 0.14999314729494934, 'max_features': None, 'min_impurity_decrease': 1.564084650521852e-07, 'validation_fraction': 0.996741201133535, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:30:12,193] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9167528164906635, 'learning_rate': 0.024844206422551217, 'dropout_rate': 0.10027142034172723, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 1.5027931264041994, 'min_weight_fraction_leaf': 0.1840765520407988, 'max_features': None, 'min_impurity_decrease': 0.026115039984674165, 'validation_fraction': 0.9013568181484788, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21273370328437058
Fold 2 IBS: 0.21868788641242787
Fold 3 IBS: 0.20291275785992635
Fold 4 IBS: 0.22394573517913938
Fold 5 IBS: 0.21633996486417809
[I 2024-04-16 04:31:26,094] Trial 61 finished with value: 0.21492400952000845 and parameters: {'subsample': 0.9931174804814122, 'learning_rate': 0.016529825628647618, 'dropout_rate': 0.1935981459085364, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.0813695010094894, 'min_weight_fraction_leaf': 0.12194954374946233, 'max_features': None, 'min_impurity_decrease': 1.1729202879091808e-06, 'validation_fraction': 0.9481060427790172, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:32:38,985] Trial 62 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9972168379620757, 'learning_rate': 0.028217399882747345, 'dropout_rate': 0.1806381271548384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.3084041748420949, 'min_weight_fraction_leaf': 0.12013391362008917, 'max_features': None, 'min_impurity_decrease': 1.1386618305709938e-06, 'validation_fraction': 0.9457754330032251, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21192094947972812
Fold 2 IBS: 0.21732792727914613
Fold 3 IBS: 0.20380983776958678
Fold 4 IBS: 0.22289315056880815
Fold 5 IBS: 0.21548234130166077
[I 2024-04-16 04:32:40,385] Trial 63 finished with value: 0.21428684127978598 and parameters: {'subsample': 0.9627141857439078, 'learning_rate': 0.019891228353589942, 'dropout_rate': 0.2615796624395084, 'n_estimators': 49, 'criterion': 'squared_error', 'ccp_alpha': 0.01736018686586977, 'min_weight_fraction_leaf': 0.04375001956932725, 'max_features': None, 'min_impurity_decrease': 2.9650355903328224e-07, 'validation_fraction': 0.9569907594316491, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:32:41,305] Trial 64 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9999396727165888, 'learning_rate': 0.018638455478477044, 'dropout_rate': 0.2603466948459836, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.002024697263514, 'min_weight_fraction_leaf': 0.044141253094182736, 'max_features': None, 'min_impurity_decrease': 2.608122256111053e-07, 'validation_fraction': 0.9599786586698028, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:32:43,444] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9663925144780658, 'learning_rate': 0.037231214360123326, 'dropout_rate': 0.32454189899564956, 'n_estimators': 65, 'criterion': 'squared_error', 'ccp_alpha': 0.35061828245011545, 'min_weight_fraction_leaf': 0.000243933620821285, 'max_features': None, 'min_impurity_decrease': 1.0838199976610403e-07, 'validation_fraction': 0.9980175670026158, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:32:44,218] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9019393211486977, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.14697195606329974, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.7042671412306138, 'min_weight_fraction_leaf': 0.07018529613097008, 'max_features': None, 'min_impurity_decrease': 3.137142110783047e-07, 'validation_fraction': 0.779814650235569, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:32:49,606] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.922035492452401, 'learning_rate': 0.02138812894899817, 'dropout_rate': 0.2208120967013012, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.09999708192212713, 'max_features': None, 'min_impurity_decrease': 1.467292826198341e-07, 'validation_fraction': 0.8460725291615868, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:32:51,297] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8097361669626262, 'learning_rate': 0.01637373351805548, 'dropout_rate': 0.2712783926055171, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.1308191878488825, 'min_weight_fraction_leaf': 0.02994710580328633, 'max_features': None, 'min_impurity_decrease': 1.0530798801381977e-06, 'validation_fraction': 0.9163895657291438, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:32:52,332] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8571881441778102, 'learning_rate': 0.0012168162419408535, 'dropout_rate': 0.42050912513013483, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 3.9712948739952747, 'min_weight_fraction_leaf': 0.12752076636262508, 'max_features': None, 'min_impurity_decrease': 4.3978604154583156e-07, 'validation_fraction': 0.964953947287593, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21002215842803912
Fold 2 IBS: 0.21297063105779915
Fold 3 IBS: 0.20313255536155353
Fold 4 IBS: 0.21999212755417724
Fold 5 IBS: 0.21255973126676214
[I 2024-04-16 04:33:03,292] Trial 70 finished with value: 0.21173544073366624 and parameters: {'subsample': 0.9468320464736178, 'learning_rate': 0.025309924459591012, 'dropout_rate': 0.1674120259573768, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010011659889289447, 'min_weight_fraction_leaf': 0.09294987278666268, 'max_features': None, 'min_impurity_decrease': 5.705070769293452e-06, 'validation_fraction': 0.8209425786658539, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21072608333691198
Fold 2 IBS: 0.21401453478291746
Fold 3 IBS: 0.20284454754508327
Fold 4 IBS: 0.22338804279177132
Fold 5 IBS: 0.21335338822747257
[I 2024-04-16 04:33:15,010] Trial 71 finished with value: 0.21286531933683134 and parameters: {'subsample': 0.9476651528090181, 'learning_rate': 0.024411666195060494, 'dropout_rate': 0.17430063929290213, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.026599566986409653, 'min_weight_fraction_leaf': 0.09751530095580928, 'max_features': None, 'min_impurity_decrease': 4.532054889066385e-06, 'validation_fraction': 0.8665443299833158, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:33:26,857] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9366080309436607, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.13262889403233624, 'n_estimators': 169, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6884427794811623, 'min_weight_fraction_leaf': 0.09471989813086933, 'max_features': None, 'min_impurity_decrease': 6.727144219685939e-06, 'validation_fraction': 0.7986403101682931, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:33:46,409] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8857292786754678, 'learning_rate': 0.026134449034871034, 'dropout_rate': 0.16958042534169554, 'n_estimators': 242, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3564153148878991, 'min_weight_fraction_leaf': 0.0675437991522329, 'max_features': None, 'min_impurity_decrease': 1.2822715066526718e-05, 'validation_fraction': 0.8508580960070242, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:33:57,118] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9667167267229794, 'learning_rate': 0.03460218408739485, 'dropout_rate': 0.23922069132815701, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9478289085025897, 'min_weight_fraction_leaf': 0.040648200160109275, 'max_features': None, 'min_impurity_decrease': 0.0004132854571878442, 'validation_fraction': 0.9118732389838691, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.2108264636051011
Fold 2 IBS: 0.21614741779802119
Fold 3 IBS: 0.20270071891532052
Fold 4 IBS: 0.22138908682592695
Fold 5 IBS: 0.21464613153207532
[I 2024-04-16 04:34:00,973] Trial 75 finished with value: 0.21314196373528901 and parameters: {'subsample': 0.9385875657011895, 'learning_rate': 0.03024192192848759, 'dropout_rate': 0.31026391284421334, 'n_estimators': 98, 'criterion': 'friedman_mse', 'ccp_alpha': 0.008766215704230302, 'min_weight_fraction_leaf': 0.088197239599825, 'max_features': 'log2', 'min_impurity_decrease': 2.34297511452969e-05, 'validation_fraction': 0.8182037482219422, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:34:14,189] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9478601603991035, 'learning_rate': 0.029703712882555727, 'dropout_rate': 0.30760503014637186, 'n_estimators': 217, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6031244247920138, 'min_weight_fraction_leaf': 0.08521606153633404, 'max_features': 'log2', 'min_impurity_decrease': 1.826805985778275e-05, 'validation_fraction': 0.7127838617807927, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:34:16,652] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.834194505922225, 'learning_rate': 0.023289065494024846, 'dropout_rate': 0.5946683576609367, 'n_estimators': 105, 'criterion': 'friedman_mse', 'ccp_alpha': 5.8752783688356525, 'min_weight_fraction_leaf': 0.10946812472698092, 'max_features': 'log2', 'min_impurity_decrease': 3.863869195457471e-05, 'validation_fraction': 0.8140600247331974, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:34:19,286] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9202091045129451, 'learning_rate': 0.019797687069268054, 'dropout_rate': 0.12670174450467558, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2910342652485194, 'min_weight_fraction_leaf': 0.15713001580184646, 'max_features': 'log2', 'min_impurity_decrease': 6.996091386072907e-06, 'validation_fraction': 0.7499357618644306, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:34:20,560] Trial 79 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9732609597246192, 'learning_rate': 0.027328730151233487, 'dropout_rate': 0.26312746311148777, 'n_estimators': 53, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3668553929390492, 'min_weight_fraction_leaf': 0.13178723776048706, 'max_features': 1, 'min_impurity_decrease': 3.5229801834435753e-06, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:34:25,830] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9344911008533908, 'learning_rate': 0.010633768390963052, 'dropout_rate': 0.3607582604573143, 'n_estimators': 130, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 'log2', 'min_impurity_decrease': 4.704228580458697e-05, 'validation_fraction': 0.8794203590137769, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21128104502826947
Fold 2 IBS: 0.2177939632602238
Fold 3 IBS: 0.202062918285923
Fold 4 IBS: 0.2220570307012409
Fold 5 IBS: 0.215203473940832
[I 2024-04-16 04:34:28,614] Trial 81 finished with value: 0.21367968624329783 and parameters: {'subsample': 0.883668494603156, 'learning_rate': 0.0320493886753143, 'dropout_rate': 0.22584451920971726, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038423779386081554, 'min_weight_fraction_leaf': 0.06634784234748042, 'max_features': 0.1, 'min_impurity_decrease': 1.4048004741754647e-05, 'validation_fraction': 0.9236349807357848, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.20983058110579608
Fold 2 IBS: 0.21307838506839907
Fold 3 IBS: 0.20156611960689727
Fold 4 IBS: 0.22102813568136667
Fold 5 IBS: 0.21191457851765924
[I 2024-04-16 04:34:31,422] Trial 82 finished with value: 0.2114835599960237 and parameters: {'subsample': 0.9775351216671477, 'learning_rate': 0.03625251959157783, 'dropout_rate': 0.2304960144192588, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017671076422469716, 'min_weight_fraction_leaf': 0.05682074279635106, 'max_features': None, 'min_impurity_decrease': 5.222380988059964e-06, 'validation_fraction': 0.8329660882357115, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:34:34,196] Trial 83 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.980690245556926, 'learning_rate': 0.031857704007181985, 'dropout_rate': 0.22968230522988387, 'n_estimators': 80, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8197918628434602, 'min_weight_fraction_leaf': 0.057928624179806834, 'max_features': None, 'min_impurity_decrease': 1.2599470077449364e-05, 'validation_fraction': 0.7797865611811227, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:34:40,703] Trial 84 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9075135722909342, 'learning_rate': 0.03559224920264127, 'dropout_rate': 0.16623286657907432, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.512352281665378, 'min_weight_fraction_leaf': 0.10287384413406744, 'max_features': 0.1, 'min_impurity_decrease': 5.529311462542002e-06, 'validation_fraction': 0.8246387147196982, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:34:49,523] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9399767088887255, 'learning_rate': 0.04090952135292814, 'dropout_rate': 0.15193033105151865, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3342330512314949, 'min_weight_fraction_leaf': 0.08669540229802705, 'max_features': 1, 'min_impurity_decrease': 1.6658136731423827e-05, 'validation_fraction': 0.8565340610034006, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 5}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:34:51,806] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.875251314446822, 'learning_rate': 0.054611780581555074, 'dropout_rate': 0.18611522621903143, 'n_estimators': 75, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23548502503527302, 'min_weight_fraction_leaf': 0.14949731859104587, 'max_features': None, 'min_impurity_decrease': 2.4419902202859148e-05, 'validation_fraction': 0.8919356176714629, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:34:52,695] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9722232383830184, 'learning_rate': 0.0372364299275435, 'dropout_rate': 0.3020378568783464, 'n_estimators': 28, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0716748672357443, 'min_weight_fraction_leaf': 0.17652784181036787, 'max_features': 'log2', 'min_impurity_decrease': 9.189811058262566e-06, 'validation_fraction': 0.9265266924948802, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:35:09,117] Trial 88 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.45521815335975935, 'learning_rate': 0.024635453467641497, 'dropout_rate': 0.22592407076200724, 'n_estimators': 225, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5932990711529844, 'min_weight_fraction_leaf': 0.05795880477433249, 'max_features': 0.1, 'min_impurity_decrease': 0.00010910005120952281, 'validation_fraction': 0.86583149343058, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 6}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.20406423720489414
Fold 2 IBS: 0.20607296701907554
Fold 3 IBS: 0.19811121797640907
Fold 4 IBS: 0.22011942798029224
Fold 5 IBS: 0.20776003972546755
[I 2024-04-16 04:35:13,130] Trial 89 finished with value: 0.2072255779812277 and parameters: {'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:35:16,844] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8590448841763807, 'learning_rate': 0.04392267936156322, 'dropout_rate': 0.13081530577107772, 'n_estimators': 94, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8187200341244589, 'min_weight_fraction_leaf': 0.1356329779047198, 'max_features': None, 'min_impurity_decrease': 6.919028711702198e-05, 'validation_fraction': 0.7579364095018994, 'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2139765219514961
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:35:22,086] Trial 91 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9464598565951264, 'learning_rate': 0.033436459700910935, 'dropout_rate': 0.1074479916910401, 'n_estimators': 111, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1567080004847236, 'min_weight_fraction_leaf': 0.21909447348643799, 'max_features': None, 'min_impurity_decrease': 3.232645761160545e-05, 'validation_fraction': 0.836686056082251, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:35:29,440] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9026696667848182, 'learning_rate': 0.028827888997212704, 'dropout_rate': 0.16259306451315403, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4965227315126272, 'min_weight_fraction_leaf': 0.22285254340641944, 'max_features': None, 'min_impurity_decrease': 0.00017018904827513644, 'validation_fraction': 0.796918264996305, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:35:31,688] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9798482306398367, 'learning_rate': 0.031825834623114814, 'dropout_rate': 0.2049131658034791, 'n_estimators': 69, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20667716682270093, 'min_weight_fraction_leaf': 0.2585203230729044, 'max_features': None, 'min_impurity_decrease': 3.0851445660062647e-06, 'validation_fraction': 0.9763122670150756, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2101879570260367
Fold 2 IBS: 0.21250628812533257
Fold 3 IBS: 0.20007025298318656
Fold 4 IBS: 0.22265647904327204
Fold 5 IBS: 0.21257939770958625
[I 2024-04-16 04:35:34,956] Trial 94 finished with value: 0.21160007497748282 and parameters: {'subsample': 0.9310591269229673, 'learning_rate': 0.02763334095363912, 'dropout_rate': 0.12795712192217606, 'n_estimators': 86, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05749842893076747, 'min_weight_fraction_leaf': 0.11026254544432534, 'max_features': 'auto', 'min_impurity_decrease': 5.8091196946415505e-05, 'validation_fraction': 0.9026577264245155, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:35:38,749] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9218225521402408, 'learning_rate': 0.02753178161235845, 'dropout_rate': 0.12793297330846434, 'n_estimators': 85, 'criterion': 'friedman_mse', 'ccp_alpha': 1.235276138540849, 'min_weight_fraction_leaf': 0.11051958866648452, 'max_features': 'auto', 'min_impurity_decrease': 6.515583307515859e-05, 'validation_fraction': 0.7292708592638782, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:35:39,421] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7993135167464014, 'learning_rate': 0.03108695961488799, 'dropout_rate': 0.14512603486936382, 'n_estimators': 24, 'criterion': 'friedman_mse', 'ccp_alpha': 0.49652833519783807, 'min_weight_fraction_leaf': 0.08008525725013409, 'max_features': 'auto', 'min_impurity_decrease': 4.444264351736355e-06, 'validation_fraction': 0.9242462136422857, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:35:52,442] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.845660486112679, 'learning_rate': 0.038767353066908594, 'dropout_rate': 0.18221216046279998, 'n_estimators': 200, 'criterion': 'friedman_mse', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.09201897280645036, 'max_features': 'auto', 'min_impurity_decrease': 0.0002353321351929941, 'validation_fraction': 0.8287626512220347, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:35:56,316] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8944546679246258, 'learning_rate': 0.036127203223985056, 'dropout_rate': 0.10388522337492916, 'n_estimators': 103, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8167233797377258, 'min_weight_fraction_leaf': 0.19553165108199336, 'max_features': 'auto', 'min_impurity_decrease': 1.7492280036351012e-05, 'validation_fraction': 0.899014721584761, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21406463377160456
Fold 2 IBS: 0.22130490881763304
Fold 3 IBS: 0.20441078654944964
Fold 4 IBS: 0.2243095706255849
Fold 5 IBS: 0.21724050836884118
[I 2024-04-16 04:35:56,581] Trial 99 finished with value: 0.21626608162662264 and parameters: {'subsample': 0.24110557495742024, 'learning_rate': 0.034155925108170324, 'dropout_rate': 0.12401586667496287, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004427324419918794, 'min_weight_fraction_leaf': 0.07004102983569523, 'max_features': 'auto', 'min_impurity_decrease': 3.069838649017234e-05, 'validation_fraction': 0.6766066266445131, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.


* Best trial for IBS:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.2072255779812277], datetime_start=datetime.datetime(2024, 4, 16, 4, 35, 9, 140009), datetime_complete=datetime.datetime(2024, 4, 16, 4, 35, 13, 128976), params={'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=89, value=None)


* Best Score for IBS:
 0.2072255779812277

In [60]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.765
train_ibs:  0.207

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.046986154574499193,
                                 dropout_rate=0.9141084507237711,
                                 learning_rate=0.005228819896792163,
                                 max_leaf_nodes=13,
                                 min_impurity_decrease=0.00017501601948817654,
                                 min_samples_leaf=15, min_samples_split=11,
                                 min_weight_fraction_leaf=0.2724947676380759,
                                 n_estimators=395, random_state=123,
                                 subsample=0.6128161811459047,
                                 validation_fraction=0.542037097833947)

C-index score: 0.579

GradientBoostingSurvivalAnalysis(ccp_alpha=0.019065157478907357,
                                 dropout_rate=0.10084377376256726,
                                 learning_rate=0.032246585462716706,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.552978044824526e-05,
                                 min_samples_leaf=9, min_samples_split=18,
                                 min_weight_fraction_leaf=0.21843803937299006,
                                 n_estimators=92, random_state=123,
                                 subsample=0.9081334064688743,
                                 validation_fraction=0.8292287698601738)

IBS: 0.218

In [64]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 04:35:59,424] A new study created in memory with name: no-name-0394b27d-e6da-4c13-a930-ace2a25bf38e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:36:00,332] Trial 0 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:36:07,667] Trial 1 finished with value: 0.6915224372703425 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:36:09,131] Trial 2 finished with value: 0.6951295602764356 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6951295602764356.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:36:11,119] Trial 3 finished with value: 0.700470556988902 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:36:14,111] Trial 4 finished with value: 0.6995459585964079 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:36:17,509] Trial 5 finished with value: 0.6866204764860286 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:36:18,866] Trial 6 finished with value: 0.689561652956617 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:36:19,166] Trial 7 finished with value: 0.6989539101188053 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:36:20,928] Trial 8 finished with value: 0.6934417965633555 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:36:25,993] Trial 9 finished with value: 0.6952660705767583 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 04:36:29,321] Trial 10 finished with value: 0.7005703272410927 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.10867980814121556, 'n_estimators': 299, 'learning_rate': 0.09279671898160717}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:36:32,982] Trial 11 finished with value: 0.6969556539693951 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.10580803679784617, 'n_estimators': 318, 'learning_rate': 0.09656492760401554}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 04:36:37,783] Trial 12 finished with value: 0.6996774700982356 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.107083606486404, 'n_estimators': 371, 'learning_rate': 0.09210877537520011}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:36:41,146] Trial 13 finished with value: 0.7039971044820788 and parameters: {'subsample': 0.19911958285971598, 'dropout_rate': 0.20951790452982805, 'n_estimators': 296, 'learning_rate': 0.08223799235112043}. Best is trial 13 with value: 0.7039971044820788.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:36:44,685] Trial 14 finished with value: 0.7111502809928003 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24580479907647002, 'n_estimators': 309, 'learning_rate': 0.0025916531369806137}. Best is trial 14 with value: 0.7111502809928003.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:36:48,954] Trial 15 finished with value: 0.7085967164139193 and parameters: {'subsample': 0.10123497548852628, 'dropout_rate': 0.27285675886808575, 'n_estimators': 344, 'learning_rate': 0.01041399690405663}. Best is trial 14 with value: 0.7111502809928003.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:36:55,575] Trial 16 finished with value: 0.7067234671141994 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.3009523413407027, 'n_estimators': 414, 'learning_rate': 0.0015978420809887592}. Best is trial 14 with value: 0.7111502809928003.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:37:01,794] Trial 17 finished with value: 0.7073018786356988 and parameters: {'subsample': 0.1398243358756775, 'dropout_rate': 0.7574099126710454, 'n_estimators': 408, 'learning_rate': 0.0036941896820761443}. Best is trial 14 with value: 0.7111502809928003.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:37:05,691] Trial 18 finished with value: 0.6970345508257922 and parameters: {'subsample': 0.32815271570962645, 'dropout_rate': 0.5881159084793368, 'n_estimators': 345, 'learning_rate': 0.0160150740748417}. Best is trial 14 with value: 0.7111502809928003.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:37:12,867] Trial 19 finished with value: 0.6987557369987656 and parameters: {'subsample': 0.2202898915217226, 'dropout_rate': 0.3156718779160812, 'n_estimators': 431, 'learning_rate': 0.01563167261765183}. Best is trial 14 with value: 0.7111502809928003.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:37:15,639] Trial 20 finished with value: 0.6997977919753454 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.22438470567364258, 'n_estimators': 245, 'learning_rate': 0.03827516477850919}. Best is trial 14 with value: 0.7111502809928003.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:37:20,916] Trial 21 finished with value: 0.710243055106287 and parameters: {'subsample': 0.12378866797437071, 'dropout_rate': 0.7075879968118339, 'n_estimators': 410, 'learning_rate': 0.0016108337344105245}. Best is trial 14 with value: 0.7111502809928003.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:37:26,706] Trial 22 finished with value: 0.7112039412516981 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.7501945956219019, 'n_estimators': 446, 'learning_rate': 0.010728356021136429}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:37:32,407] Trial 23 finished with value: 0.696092718396618 and parameters: {'subsample': 0.26606437776375036, 'dropout_rate': 0.7679424882113466, 'n_estimators': 452, 'learning_rate': 0.024115197614724897}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:37:36,459] Trial 24 finished with value: 0.7031237533506733 and parameters: {'subsample': 0.16824204654906352, 'dropout_rate': 0.9740261108007398, 'n_estimators': 397, 'learning_rate': 0.009330118660635838}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:37:43,950] Trial 25 finished with value: 0.6961416936829352 and parameters: {'subsample': 0.29503576600228787, 'dropout_rate': 0.6924632762598707, 'n_estimators': 495, 'learning_rate': 0.02082938874638609}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:37:49,768] Trial 26 finished with value: 0.6970028095761555 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.624128699333995, 'n_estimators': 451, 'learning_rate': 0.006989047841911983}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:37:54,256] Trial 27 finished with value: 0.6996947041349157 and parameters: {'subsample': 0.22541201594342303, 'dropout_rate': 0.8368873118701377, 'n_estimators': 385, 'learning_rate': 0.030307532796347948}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:37:58,530] Trial 28 finished with value: 0.7033115109120845 and parameters: {'subsample': 0.16797868494326035, 'dropout_rate': 0.6997719393568667, 'n_estimators': 326, 'learning_rate': 0.0012105719755584748}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:37:59,933] Trial 29 finished with value: 0.689561652956617 and parameters: {'subsample': 0.6377247263447686, 'dropout_rate': 0.528113503868086, 'n_estimators': 136, 'learning_rate': 0.012766362768081544}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:02,751] Trial 30 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.8739790489864521, 'dropout_rate': 0.7775448884191318, 'n_estimators': 261, 'learning_rate': 0.03500526163856756}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:38:07,212] Trial 31 finished with value: 0.7095817935433627 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.3755968586915731, 'n_estimators': 348, 'learning_rate': 0.010495499913599278}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:38:14,212] Trial 32 finished with value: 0.7066359321001938 and parameters: {'subsample': 0.1020527537827175, 'dropout_rate': 0.3989001250399369, 'n_estimators': 434, 'learning_rate': 0.018578545016073353}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:38:19,222] Trial 33 finished with value: 0.7031969196210228 and parameters: {'subsample': 0.16499587533380747, 'dropout_rate': 0.45721080222598387, 'n_estimators': 363, 'learning_rate': 0.008390503824508122}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:19,368] Trial 34 finished with value: 0.6907202982329093 and parameters: {'subsample': 0.23357974287632433, 'dropout_rate': 0.3571495847483449, 'n_estimators': 5, 'learning_rate': 0.024734341677464432}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:38:23,366] Trial 35 finished with value: 0.708323695813274 and parameters: {'subsample': 0.14192788598468545, 'dropout_rate': 0.6202436881632538, 'n_estimators': 294, 'learning_rate': 0.013718866742801124}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:38:30,321] Trial 36 finished with value: 0.6989539101188053 and parameters: {'subsample': 0.30986291207776295, 'dropout_rate': 0.5041730824421278, 'n_estimators': 459, 'learning_rate': 0.004999841632498594}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:38:36,595] Trial 37 finished with value: 0.7082822707925616 and parameters: {'subsample': 0.19601254122495787, 'dropout_rate': 0.20021509203043766, 'n_estimators': 398, 'learning_rate': 0.059207327336158105}. Best is trial 22 with value: 0.7112039412516981.

Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:38:38,864] Trial 38 finished with value: 0.6961416936829352 and parameters: {'subsample': 0.27261582706417964, 'dropout_rate': 0.8190477307045616, 'n_estimators': 231, 'learning_rate': 0.04270368088653838}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:38:42,048] Trial 39 finished with value: 0.6951295602764356 and parameters: {'subsample': 0.42175313697788064, 'dropout_rate': 0.3997102511114324, 'n_estimators': 277, 'learning_rate': 0.02944859066794525}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:45,272] Trial 40 finished with value: 0.6915224372703425 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.8887286631915676, 'n_estimators': 334, 'learning_rate': 0.007245098777585461}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:38:50,753] Trial 41 finished with value: 0.7077038592710622 and parameters: {'subsample': 0.10440609687561335, 'dropout_rate': 0.28375628797579017, 'n_estimators': 359, 'learning_rate': 0.010109447250747465}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:38:57,135] Trial 42 finished with value: 0.7066382040749655 and parameters: {'subsample': 0.15503211892248595, 'dropout_rate': 0.35383019781328473, 'n_estimators': 429, 'learning_rate': 0.01952489110584796}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:01,733] Trial 43 finished with value: 0.7075478429592879 and parameters: {'subsample': 0.10605635908821856, 'dropout_rate': 0.15923583048212644, 'n_estimators': 316, 'learning_rate': 0.0130161837842057}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:07,088] Trial 44 finished with value: 0.7029677370388989 and parameters: {'subsample': 0.19027813290615522, 'dropout_rate': 0.2696372855151824, 'n_estimators': 378, 'learning_rate': 0.026626953571799904}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:39:11,815] Trial 45 finished with value: 0.7024608105774928 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.43513557905493283, 'n_estimators': 349, 'learning_rate': 0.006309559839429986}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:21,294] Trial 46 finished with value: 0.7065506690609598 and parameters: {'subsample': 0.13597293873270822, 'dropout_rate': 0.24397303794470263, 'n_estimators': 479, 'learning_rate': 0.011950070396079851}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:39:24,570] Trial 47 finished with value: 0.6915224372703425 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.17354901474323, 'n_estimators': 277, 'learning_rate': 0.0187959426187142}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:39:30,439] Trial 48 finished with value: 0.7002240019007976 and parameters: {'subsample': 0.19734249726248343, 'dropout_rate': 0.708958520900678, 'n_estimators': 420, 'learning_rate': 0.07002270781061834}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:39:34,247] Trial 49 finished with value: 0.6979003516915931 and parameters: {'subsample': 0.3524538574119267, 'dropout_rate': 0.33192443256002235, 'n_estimators': 301, 'learning_rate': 0.0016753811606543417}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:38,658] Trial 50 finished with value: 0.7103305901202926 and parameters: {'subsample': 0.1317808068530858, 'dropout_rate': 0.9501582476866339, 'n_estimators': 386, 'learning_rate': 0.016764259876906357}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:42,777] Trial 51 finished with value: 0.7083917248158278 and parameters: {'subsample': 0.1233247075208542, 'dropout_rate': 0.9876353388152359, 'n_estimators': 387, 'learning_rate': 0.016231138642578163}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:46,481] Trial 52 finished with value: 0.707525923950027 and parameters: {'subsample': 0.14226753571861944, 'dropout_rate': 0.9285184857577364, 'n_estimators': 340, 'learning_rate': 0.0042004568677699}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:39:51,333] Trial 53 finished with value: 0.7021433611938106 and parameters: {'subsample': 0.18127468297869642, 'dropout_rate': 0.5815669629979552, 'n_estimators': 368, 'learning_rate': 0.008727856707145435}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:39:56,996] Trial 54 finished with value: 0.70148041842063 and parameters: {'subsample': 0.24778282139970031, 'dropout_rate': 0.9471873212605328, 'n_estimators': 404, 'learning_rate': 0.02188918277180668}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:03,568] Trial 55 finished with value: 0.6986606517191555 and parameters: {'subsample': 0.20857638261197597, 'dropout_rate': 0.736176834485233, 'n_estimators': 467, 'learning_rate': 0.012035914012030476}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:07,184] Trial 56 finished with value: 0.7076675715181453 and parameters: {'subsample': 0.13120936325663415, 'dropout_rate': 0.6555870719053609, 'n_estimators': 312, 'learning_rate': 0.0010043759807916914}. Best is trial 22 with value: 0.7112039412516981.

Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:13,060] Trial 57 finished with value: 0.6960955836896421 and parameters: {'subsample': 0.2865587655137405, 'dropout_rate': 0.835321001688947, 'n_estimators': 435, 'learning_rate': 0.01697327238358095}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:17,304] Trial 58 finished with value: 0.7050211936344255 and parameters: {'subsample': 0.1680374480808781, 'dropout_rate': 0.7875831557850044, 'n_estimators': 350, 'learning_rate': 0.0044734285371354635}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:23,491] Trial 59 finished with value: 0.7092845819586852 and parameters: {'subsample': 0.10169425500062534, 'dropout_rate': 0.8707574648386667, 'n_estimators': 443, 'learning_rate': 0.08322655251020356}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:40:29,993] Trial 60 finished with value: 0.6996947041349157 and parameters: {'subsample': 0.22524341239080908, 'dropout_rate': 0.8960901885370502, 'n_estimators': 483, 'learning_rate': 0.0806029617661395}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:40:35,512] Trial 61 finished with value: 0.7086014013865 and parameters: {'subsample': 0.1069022471980777, 'dropout_rate': 0.9467242548421735, 'n_estimators': 449, 'learning_rate': 0.06572137665407819}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:40:41,746] Trial 62 finished with value: 0.7066359321001938 and parameters: {'subsample': 0.12361224388219196, 'dropout_rate': 0.9468924328014086, 'n_estimators': 446, 'learning_rate': 0.06354935507861761}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:47,613] Trial 63 finished with value: 0.7040408014775628 and parameters: {'subsample': 0.16328264610629192, 'dropout_rate': 0.8626732581316854, 'n_estimators': 496, 'learning_rate': 0.07880051236430662}. Best is trial 22 with value: 0.7112039412516981.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:40:51,977] Trial 64 finished with value: 0.7120478231082381 and parameters: {'subsample': 0.10218130137857191, 'dropout_rate': 0.8703793504419942, 'n_estimators': 419, 'learning_rate': 0.09213034239034594}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:56,761] Trial 65 finished with value: 0.7082822707925616 and parameters: {'subsample': 0.14298925507841115, 'dropout_rate': 0.8009231409115243, 'n_estimators': 417, 'learning_rate': 0.08660420061326018}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:01,344] Trial 66 finished with value: 0.7040627204868236 and parameters: {'subsample': 0.18880415999582906, 'dropout_rate': 0.8584370314391144, 'n_estimators': 387, 'learning_rate': 0.09896876689440842}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 04:41:06,471] Trial 67 finished with value: 0.7005000262637673 and parameters: {'subsample': 0.2520698217617981, 'dropout_rate': 0.729179411014327, 'n_estimators': 413, 'learning_rate': 0.09027324752436579}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:12,204] Trial 68 finished with value: 0.7076185962318282 and parameters: {'subsample': 0.12953332890450958, 'dropout_rate': 0.9143009267270642, 'n_estimators': 470, 'learning_rate': 0.05037400013902345}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:41:16,917] Trial 69 finished with value: 0.6987557369987656 and parameters: {'subsample': 0.21940280439475393, 'dropout_rate': 0.8809377532108776, 'n_estimators': 400, 'learning_rate': 0.08650162637955829}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:17,563] Trial 70 finished with value: 0.7046993387705007 and parameters: {'subsample': 0.17283309872285502, 'dropout_rate': 0.9969638279429532, 'n_estimators': 86, 'learning_rate': 0.07321459102014137}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:41:25,146] Trial 71 finished with value: 0.7083456148225349 and parameters: {'subsample': 0.10752770291089753, 'dropout_rate': 0.839393383138753, 'n_estimators': 443, 'learning_rate': 0.06647276044589306}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:41:29,970] Trial 72 finished with value: 0.7085138663724944 and parameters: {'subsample': 0.10288630604966292, 'dropout_rate': 0.9628922473383871, 'n_estimators': 429, 'learning_rate': 0.07818895650214111}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:34,112] Trial 73 finished with value: 0.7067527953660273 and parameters: {'subsample': 0.1510135793190781, 'dropout_rate': 0.9206856904127814, 'n_estimators': 375, 'learning_rate': 0.09302083133163766}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:41:40,103] Trial 74 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.5422591864878894, 'dropout_rate': 0.6651975882706767, 'n_estimators': 461, 'learning_rate': 0.05317385032438769}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:44,909] Trial 75 finished with value: 0.7093501979634299 and parameters: {'subsample': 0.12528653691856095, 'dropout_rate': 0.752770356433498, 'n_estimators': 423, 'learning_rate': 0.0850272276745128}. Best is trial 64 with value: 0.7120478231082381.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:41:49,510] Trial 76 finished with value: 0.7048334360730143 and parameters: {'subsample': 0.15655192837805382, 'dropout_rate': 0.7657797357943857, 'n_estimators': 394, 'learning_rate': 0.08383283937402089}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:54,993] Trial 77 finished with value: 0.7013507265983591 and parameters: {'subsample': 0.20553116287610598, 'dropout_rate': 0.7398687316588946, 'n_estimators': 419, 'learning_rate': 0.0894165475954659}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:41:59,392] Trial 78 finished with value: 0.6952660705767583 and parameters: {'subsample': 0.4677702378827672, 'dropout_rate': 0.8063750778201401, 'n_estimators': 357, 'learning_rate': 0.0946052609785828}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:42:01,225] Trial 79 finished with value: 0.7076624342503497 and parameters: {'subsample': 0.12657503844948292, 'dropout_rate': 0.6364452391368739, 'n_estimators': 203, 'learning_rate': 0.0983514933405076}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:42:07,598] Trial 80 finished with value: 0.7040309792371866 and parameters: {'subsample': 0.1854362280948238, 'dropout_rate': 0.5796401124190165, 'n_estimators': 405, 'learning_rate': 0.07511177554841489}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:42:13,187] Trial 81 finished with value: 0.7056555399433311 and parameters: {'subsample': 0.11611305646296287, 'dropout_rate': 0.9372137432710993, 'n_estimators': 443, 'learning_rate': 0.08534751907894712}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:42:18,813] Trial 82 finished with value: 0.7112039412516981 and parameters: {'subsample': 0.10261956885400987, 'dropout_rate': 0.8774100822274666, 'n_estimators': 453, 'learning_rate': 0.06990448842150965}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:42:25,766] Trial 83 finished with value: 0.7085114533746852 and parameters: {'subsample': 0.1523574516282296, 'dropout_rate': 0.8773151532875069, 'n_estimators': 482, 'learning_rate': 0.08861933430119348}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:42:28,924] Trial 84 finished with value: 0.7068236896616051 and parameters: {'subsample': 0.13091333560970814, 'dropout_rate': 0.8299501058306785, 'n_estimators': 332, 'learning_rate': 0.0959989567960882}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:42:35,099] Trial 85 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.7195215413719104, 'dropout_rate': 0.6832398979465137, 'n_estimators': 460, 'learning_rate': 0.058804678432191115}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:42:43,523] Trial 86 finished with value: 0.705606564657014 and parameters: {'subsample': 0.17422455699020012, 'dropout_rate': 0.127233231736465, 'n_estimators': 426, 'learning_rate': 0.07006307905774899}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:42:47,598] Trial 87 finished with value: 0.7085114533746852 and parameters: {'subsample': 0.150388950826201, 'dropout_rate': 0.8526271044544553, 'n_estimators': 379, 'learning_rate': 0.07674993954937051}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:42:52,409] Trial 88 finished with value: 0.7110674309513754 and parameters: {'subsample': 0.10208731806738933, 'dropout_rate': 0.9002025579153877, 'n_estimators': 438, 'learning_rate': 0.0818760153521709}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:42:56,725] Trial 89 finished with value: 0.7004117594622088 and parameters: {'subsample': 0.20281903745355515, 'dropout_rate': 0.9041248637550549, 'n_estimators': 411, 'learning_rate': 0.006041813377825062}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:02,043] Trial 90 finished with value: 0.7075748992363441 and parameters: {'subsample': 0.12220170810840063, 'dropout_rate': 0.4206192501356678, 'n_estimators': 387, 'learning_rate': 0.010803235956644137}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:43:06,567] Trial 91 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.8961006358184125, 'dropout_rate': 0.9673034224276529, 'n_estimators': 434, 'learning_rate': 0.08188887328435959}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:13,664] Trial 92 finished with value: 0.7076185962318282 and parameters: {'subsample': 0.13510051628208827, 'dropout_rate': 0.8134239609460656, 'n_estimators': 455, 'learning_rate': 0.01470648440834058}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:43:19,639] Trial 93 finished with value: 0.7120478231082381 and parameters: {'subsample': 0.1012003476269077, 'dropout_rate': 0.7918326733438584, 'n_estimators': 437, 'learning_rate': 0.0036214861557067276}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:25,978] Trial 94 finished with value: 0.7111307749813487 and parameters: {'subsample': 0.10168571989980042, 'dropout_rate': 0.786858971581271, 'n_estimators': 472, 'learning_rate': 0.003276901841464499}. Best is trial 64 with value: 0.7120478231082381.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:32,883] Trial 95 finished with value: 0.7102868931248085 and parameters: {'subsample': 0.10055421208744673, 'dropout_rate': 0.8017404184591896, 'n_estimators': 475, 'learning_rate': 0.003505647963010264}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:39,768] Trial 96 finished with value: 0.7112453662724106 and parameters: {'subsample': 0.10076567793041669, 'dropout_rate': 0.780834450447211, 'n_estimators': 489, 'learning_rate': 0.0027651262612912414}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:47,777] Trial 97 finished with value: 0.7049066023433637 and parameters: {'subsample': 0.15653931845472954, 'dropout_rate': 0.7750749666399357, 'n_estimators': 498, 'learning_rate': 0.003698877547832585}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:55,159] Trial 98 finished with value: 0.7040627204868236 and parameters: {'subsample': 0.18130090256822093, 'dropout_rate': 0.7900274790323639, 'n_estimators': 486, 'learning_rate': 0.008397593428899702}. Best is trial 64 with value: 0.7120478231082381.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688

[I 2024-04-16 04:44:02,585] A new study created in memory with name: no-name-1405e471-0517-4835-85c0-c1139302bcc8

Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:44:02,569] Trial 99 finished with value: 0.7102649741155479 and parameters: {'subsample': 0.1006201678335455, 'dropout_rate': 0.7154703006010337, 'n_estimators': 469, 'learning_rate': 0.003043170983766654}. Best is trial 64 with value: 0.7120478231082381.


* Best trial for C-index:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.7120478231082381], datetime_start=datetime.datetime(2024, 4, 16, 4, 40, 47, 621753), datetime_complete=datetime.datetime(2024, 4, 16, 4, 40, 51, 977004), params={'subsample': 0.10218130137857191, 'dropout_rate': 0.8703793504419942, 'n_estimators': 419, 'learning_rate': 0.09213034239034594}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=64, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10218130137857191, 'dropout_rate': 0.8703793504419942, 'n_estimators': 419, 'learning_rate': 0.09213034239034594}


* Best Score for C-index:
 0.7120478231082381

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24692977896599883
Fold 2 IBS: 0.23367124240111953
Fold 3 IBS: 0.18592983540335206
Fold 4 IBS: 0.2632765971484762
Fold 5 IBS: 0.2101930209796324
[I 2024-04-16 04:44:03,441] Trial 0 finished with value: 0.2280000949797158 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.3168791384838904
Fold 2 IBS: 0.3218948725307976
Fold 3 IBS: 0.27592959166775866
Fold 4 IBS: 0.315408539471182
Fold 5 IBS: 0.30438829249434424
[I 2024-04-16 04:44:10,913] Trial 1 finished with value: 0.3069000869295946 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2753019447545149
Fold 2 IBS: 0.2982356241179488
Fold 3 IBS: 0.23068334408596278
Fold 4 IBS: 0.27397829249360633
Fold 5 IBS: 0.2568695041228669
[I 2024-04-16 04:44:12,428] Trial 2 finished with value: 0.26701374191497995 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2786819074278709
Fold 2 IBS: 0.2600472138747981
Fold 3 IBS: 0.23879047988199983
Fold 4 IBS: 0.2592722986281111
Fold 5 IBS: 0.21840002439276662
[I 2024-04-16 04:44:14,481] Trial 3 finished with value: 0.2510383848411093 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.28015948815542563
Fold 2 IBS: 0.28471090270389776
Fold 3 IBS: 0.24032974838077645
Fold 4 IBS: 0.2566553638796097
Fold 5 IBS: 0.2316186524918199
[I 2024-04-16 04:44:17,981] Trial 4 finished with value: 0.25869483112230585 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.30156654310213465
Fold 2 IBS: 0.3204353433554115
Fold 3 IBS: 0.2623263101041928
Fold 4 IBS: 0.3038662427158054
Fold 5 IBS: 0.2972845037916553
[I 2024-04-16 04:44:21,858] Trial 5 finished with value: 0.29709578861383995 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.23284347689671558
Fold 2 IBS: 0.202874467602479
Fold 3 IBS: 0.17322347591450493
Fold 4 IBS: 0.24151316943928927
Fold 5 IBS: 0.1909058630290115
[I 2024-04-16 04:44:23,509] Trial 6 finished with value: 0.20827209057640003 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20827209057640003.
Fold 1 IBS: 0.20841359719195401
Fold 2 IBS: 0.18500570168858935
Fold 3 IBS: 0.17412783878300364
Fold 4 IBS: 0.20964581935767979
Fold 5 IBS: 0.18381553554818797
[I 2024-04-16 04:44:23,897] Trial 7 finished with value: 0.19220169851388297 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.2500273900096136
Fold 2 IBS: 0.24252428811376492
Fold 3 IBS: 0.19155396122507418
Fold 4 IBS: 0.26800891557035394
Fold 5 IBS: 0.206728112867265
[I 2024-04-16 04:44:26,105] Trial 8 finished with value: 0.23176853355721433 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.3046029224708627
Fold 2 IBS: 0.32082834695628154
Fold 3 IBS: 0.2673578226321637
Fold 4 IBS: 0.3050114978922588
Fold 5 IBS: 0.2879788067536104
[I 2024-04-16 04:44:31,903] Trial 9 finished with value: 0.29715587934103543 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.21341107818060095
Fold 2 IBS: 0.22041244256787032
Fold 3 IBS: 0.20358827659270148
Fold 4 IBS: 0.22376802174886082
Fold 5 IBS: 0.2171830253408078
[I 2024-04-16 04:44:32,204] Trial 10 finished with value: 0.21567256888616831 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.2132850691785392
Fold 2 IBS: 0.22000460296162738
Fold 3 IBS: 0.20349124979478508
Fold 4 IBS: 0.22352663518317686
Fold 5 IBS: 0.2169388510633896
[I 2024-04-16 04:44:32,378] Trial 11 finished with value: 0.2154492816363036 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.2649085487462804
Fold 2 IBS: 0.2797956098039142
Fold 3 IBS: 0.21501861010468323
Fold 4 IBS: 0.269516915435845
Fold 5 IBS: 0.21652505532003755
[I 2024-04-16 04:44:33,111] Trial 12 finished with value: 0.24915294788215206 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.26365849597545205
Fold 2 IBS: 0.27755786474823224
Fold 3 IBS: 0.21375266267140264
Fold 4 IBS: 0.27739729053928086
Fold 5 IBS: 0.24947493405031224
[I 2024-04-16 04:44:36,695] Trial 13 finished with value: 0.25636824959693605 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.20569427667469156
Fold 2 IBS: 0.19327418056505236
Fold 3 IBS: 0.18069024590527896
Fold 4 IBS: 0.2080995790312972
Fold 5 IBS: 0.19490230571351805
[I 2024-04-16 04:44:37,343] Trial 14 finished with value: 0.19653211757796762 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.210409804816474
Fold 2 IBS: 0.21349058556283512
Fold 3 IBS: 0.19848530424265426
Fold 4 IBS: 0.21859880093918413
Fold 5 IBS: 0.21158479151159898
[I 2024-04-16 04:44:38,060] Trial 15 finished with value: 0.2105138574145493 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.20630685620006517
Fold 2 IBS: 0.20273931524283226
Fold 3 IBS: 0.18919005657291543
Fold 4 IBS: 0.21127743577400432
Fold 5 IBS: 0.20267124736055916
[I 2024-04-16 04:44:38,564] Trial 16 finished with value: 0.20243698223007528 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.23835959803032003
Fold 2 IBS: 0.21402340081247587
Fold 3 IBS: 0.17953828231829627
Fold 4 IBS: 0.25047212321042694
Fold 5 IBS: 0.19743222117495793
[I 2024-04-16 04:44:39,607] Trial 17 finished with value: 0.2159651251092954 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.23992452095154856
Fold 2 IBS: 0.21495595423038097
Fold 3 IBS: 0.1799986146183617
Fold 4 IBS: 0.24881181915281447
Fold 5 IBS: 0.1887847887770836
[I 2024-04-16 04:44:43,446] Trial 18 finished with value: 0.21449513954603786 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19220169851388297.
Fold 1 IBS: 0.20093920938209162

Fold 2 IBS: 0.17621580201176304
Fold 3 IBS: 0.17642037928014906
Fold 4 IBS: 0.1933021033103859
Fold 5 IBS: 0.18417216136826517
[I 2024-04-16 04:44:43,927] Trial 19 finished with value: 0.18620993107053097 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.20387936509804852
Fold 2 IBS: 0.1793124075420424
Fold 3 IBS: 0.17651390954439816
Fold 4 IBS: 0.19656951529579103
Fold 5 IBS: 0.18647847319032207
[I 2024-04-16 04:44:44,306] Trial 20 finished with value: 0.18855073413412043 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.2014156239858501
Fold 2 IBS: 0.186025328567609
Fold 3 IBS: 0.18124723411340657
Fold 4 IBS: 0.20164577976082107
Fold 5 IBS: 0.1923852965944346
[I 2024-04-16 04:44:44,807] Trial 21 finished with value: 0.19254385260442428 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.21289135072667675
Fold 2 IBS: 0.2192362843041557
Fold 3 IBS: 0.20256314478108844
Fold 4 IBS: 0.22230805658932015
Fold 5 IBS: 0.21635372756130705
[I 2024-04-16 04:44:44,989] Trial 22 finished with value: 0.21467051279250962 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.23618112190743049
Fold 2 IBS: 0.20448915443761134
Fold 3 IBS: 0.18500144243309885
Fold 4 IBS: 0.23272115987630482
Fold 5 IBS: 0.1768207624871139
[I 2024-04-16 04:44:46,159] Trial 23 finished with value: 0.20704272822831188 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.22412270848810453
Fold 2 IBS: 0.1908952941916656
Fold 3 IBS: 0.17076790246118903
Fold 4 IBS: 0.23054053553396578
Fold 5 IBS: 0.17895573468339276
[I 2024-04-16 04:44:46,611] Trial 24 finished with value: 0.19905643507166354 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.22135980506714256
Fold 2 IBS: 0.1845697626181813
Fold 3 IBS: 0.17134693759406197
Fold 4 IBS: 0.21838436671938202
Fold 5 IBS: 0.17818604703688692
[I 2024-04-16 04:44:47,281] Trial 25 finished with value: 0.19476938380713094 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.2664586813217101
Fold 2 IBS: 0.2507040082894473
Fold 3 IBS: 0.2366528926051191
Fold 4 IBS: 0.2354750422527525
Fold 5 IBS: 0.22137521539805052
[I 2024-04-16 04:44:48,515] Trial 26 finished with value: 0.2421331679734159 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.2553890165506429
Fold 2 IBS: 0.2466456254689822
Fold 3 IBS: 0.2030698880517768
Fold 4 IBS: 0.26509675916293274
Fold 5 IBS: 0.2071321951304051
[I 2024-04-16 04:44:50,957] Trial 27 finished with value: 0.23546669687294797 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.20531328758958778
Fold 2 IBS: 0.1923192977101289
Fold 3 IBS: 0.18553914516113976
Fold 4 IBS: 0.20629730735123383
Fold 5 IBS: 0.1964379330705869
[I 2024-04-16 04:44:51,380] Trial 28 finished with value: 0.19718139417653543 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.25186522298741737
Fold 2 IBS: 0.24845492076238285
Fold 3 IBS: 0.19433567299842514
Fold 4 IBS: 0.27098179405615386
Fold 5 IBS: 0.20109364910535815
[I 2024-04-16 04:44:52,367] Trial 29 finished with value: 0.23334625198194744 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.2330665600388519
Fold 2 IBS: 0.18958254715791947
Fold 3 IBS: 0.17586286009507707
Fold 4 IBS: 0.22333508249786657
Fold 5 IBS: 0.1790727700891593
[I 2024-04-16 04:44:53,037] Trial 30 finished with value: 0.20018396397577484 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.20192597821421124
Fold 2 IBS: 0.17925245864127606
Fold 3 IBS: 0.17693246714611857
Fold 4 IBS: 0.19955697306092265
Fold 5 IBS: 0.18757266024538874
[I 2024-04-16 04:44:53,419] Trial 31 finished with value: 0.18904810746158346 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.2036438224589056
Fold 2 IBS: 0.18999348990743456
Fold 3 IBS: 0.18067689586106764
Fold 4 IBS: 0.20066103940254612
Fold 5 IBS: 0.19015410752529469
[I 2024-04-16 04:44:53,722] Trial 32 finished with value: 0.1930258710310497 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.218509413910925
Fold 2 IBS: 0.17316742707096663
Fold 3 IBS: 0.173178141798903
Fold 4 IBS: 0.20876730832287213
Fold 5 IBS: 0.17854525726540685
[I 2024-04-16 04:44:54,197] Trial 33 finished with value: 0.19043350967381473 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.21134490777110404
Fold 2 IBS: 0.2124741646949405
Fold 3 IBS: 0.20117242879680738
Fold 4 IBS: 0.2188565718064687
Fold 5 IBS: 0.21362043912965564
[I 2024-04-16 04:44:54,408] Trial 34 finished with value: 0.21149370243979523 and parameters: {'subsample': 0.10904251030586302, 'dropout_rate': 0.8662195064551774, 'n_estimators': 3, 'learning_rate': 0.07766566220378217}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.26254409897286624
Fold 2 IBS: 0.26142634624635325
Fold 3 IBS: 0.21304885779869873
Fold 4 IBS: 0.26840863359298894
Fold 5 IBS: 0.2149242097575137
[I 2024-04-16 04:44:55,346] Trial 35 finished with value: 0.24407042927368416 and parameters: {'subsample': 0.27868485453535496, 'dropout_rate': 0.9999743696114711, 'n_estimators': 141, 'learning_rate': 0.06694317131672249}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.3214514212453817
Fold 2 IBS: 0.31842612254469355
Fold 3 IBS: 0.2780745284978492
Fold 4 IBS: 0.27100191496634607
Fold 5 IBS: 0.26652298660266704
[I 2024-04-16 04:44:59,805] Trial 36 finished with value: 0.2910953947713875 and parameters: {'subsample': 0.16326559473518704, 'dropout_rate': 0.8736174627174981, 'n_estimators': 421, 'learning_rate': 0.07993410500556083}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.2613925178705326
Fold 2 IBS: 0.2609067973308416
Fold 3 IBS: 0.2141926990139999
Fold 4 IBS: 0.2671551183060875
Fold 5 IBS: 0.21280820625378144
[I 2024-04-16 04:45:01,119] Trial 37 finished with value: 0.24329106775504866 and parameters: {'subsample': 0.23660873470356106, 'dropout_rate': 0.7990281623991888, 'n_estimators': 170, 'learning_rate': 0.05621431261796065}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.21809131094918027

Fold 2 IBS: 0.16157113568264034
Fold 3 IBS: 0.18180869186592977
Fold 4 IBS: 0.2047333534968014
Fold 5 IBS: 0.1741931240386079
[I 2024-04-16 04:45:01,839] Trial 38 finished with value: 0.18807952320663193 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 82, 'learning_rate': 0.0684395247111694}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.22633764950020804
Fold 2 IBS: 0.1753146373948459
Fold 3 IBS: 0.17881883861510856
Fold 4 IBS: 0.20168491431079613
Fold 5 IBS: 0.17197177530632424
[I 2024-04-16 04:45:02,699] Trial 39 finished with value: 0.19082556302545656 and parameters: {'subsample': 0.167666800643059, 'dropout_rate': 0.11471626893495929, 'n_estimators': 100, 'learning_rate': 0.050430345636818495}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.2422412002312995
Fold 2 IBS: 0.2157930776654539
Fold 3 IBS: 0.18031024557675085
Fold 4 IBS: 0.2534886449121738
Fold 5 IBS: 0.18564670364656027
[I 2024-04-16 04:45:03,284] Trial 40 finished with value: 0.21549597440644766 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.27073406810212547, 'n_estimators': 78, 'learning_rate': 0.07230355488087334}. Best is trial 19 with value: 0.18620993107053097.
Fold 1 IBS: 0.20693752097122656
Fold 2 IBS: 0.16974764858473398
Fold 3 IBS: 0.17324267100386312
Fold 4 IBS: 0.1927204113466328
Fold 5 IBS: 0.17133659300206425
[I 2024-04-16 04:45:03,762] Trial 41 finished with value: 0.18279696898170414 and parameters: {'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 56, 'learning_rate': 0.06615161558436967}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20293847830177036
Fold 2 IBS: 0.18357766203003745
Fold 3 IBS: 0.18037482363750096
Fold 4 IBS: 0.20271238078172635
Fold 5 IBS: 0.19011495729746888
[I 2024-04-16 04:45:04,062] Trial 42 finished with value: 0.1919436604097008 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.19807687454956896, 'n_estimators': 25, 'learning_rate': 0.05946433946285823}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2285910558434711
Fold 2 IBS: 0.18556994693949647
Fold 3 IBS: 0.17348377537491344
Fold 4 IBS: 0.22784907598952878
Fold 5 IBS: 0.17797113163263528
[I 2024-04-16 04:45:04,594] Trial 43 finished with value: 0.19869299715600902 and parameters: {'subsample': 0.31451686904054643, 'dropout_rate': 0.286459714252547, 'n_estimators': 50, 'learning_rate': 0.08722773956368673}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.26810729391665705
Fold 2 IBS: 0.21432929710161247
Fold 3 IBS: 0.2343032861483595
Fold 4 IBS: 0.23193149051052295
Fold 5 IBS: 0.2079982927338732
[I 2024-04-16 04:45:06,964] Trial 44 finished with value: 0.23133393208220504 and parameters: {'subsample': 0.13055820393157166, 'dropout_rate': 0.17293718310640144, 'n_estimators': 207, 'learning_rate': 0.06474202539730971}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2547537779222378
Fold 2 IBS: 0.21912691659412195
Fold 3 IBS: 0.20430227387045694
Fold 4 IBS: 0.25020180939641257
Fold 5 IBS: 0.19728688223679067
[I 2024-04-16 04:45:07,918] Trial 45 finished with value: 0.22513433200400396 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.32993790334399276, 'n_estimators': 115, 'learning_rate': 0.07226468386460667}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.22531593692515978
Fold 2 IBS: 0.18531062283111605
Fold 3 IBS: 0.17418019474335694
Fold 4 IBS: 0.2126670476153898
Fold 5 IBS: 0.1735960936470701
[I 2024-04-16 04:45:09,212] Trial 46 finished with value: 0.1942139791524185 and parameters: {'subsample': 0.2002446053403005, 'dropout_rate': 0.20488129986163572, 'n_estimators': 80, 'learning_rate': 0.05378014293554952}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.24562274502188527
Fold 2 IBS: 0.21364645615746872
Fold 3 IBS: 0.18685026060524998
Fold 4 IBS: 0.24845372130866922
Fold 5 IBS: 0.18379888547032364
[I 2024-04-16 04:45:10,990] Trial 47 finished with value: 0.2156744137127194 and parameters: {'subsample': 0.4539729299901746, 'dropout_rate': 0.1137868207525379, 'n_estimators': 178, 'learning_rate': 0.03623350794651181}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20490350211689695
Fold 2 IBS: 0.19920724740849075
Fold 3 IBS: 0.18923284125143605
Fold 4 IBS: 0.20449222226104663
Fold 5 IBS: 0.19872830164405222
[I 2024-04-16 04:45:11,237] Trial 48 finished with value: 0.19931282293638453 and parameters: {'subsample': 0.14176620493513847, 'dropout_rate': 0.23624837489749712, 'n_estimators': 18, 'learning_rate': 0.04963128845882498}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20547952605278474
Fold 2 IBS: 0.19463394001368048
Fold 3 IBS: 0.18261537320715654
Fold 4 IBS: 0.2082812797974064
Fold 5 IBS: 0.1963384925484811
[I 2024-04-16 04:45:11,647] Trial 49 finished with value: 0.19746972232390186 and parameters: {'subsample': 0.7553314841676608, 'dropout_rate': 0.4477251063775791, 'n_estimators': 45, 'learning_rate': 0.027854287270829683}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2775178330847401
Fold 2 IBS: 0.299747451908182
Fold 3 IBS: 0.23472252424874357
Fold 4 IBS: 0.2687103342199322
Fold 5 IBS: 0.24082425467221202
[I 2024-04-16 04:45:14,288] Trial 50 finished with value: 0.26430447962676196 and parameters: {'subsample': 0.3116445257158518, 'dropout_rate': 0.9501582476866339, 'n_estimators': 230, 'learning_rate': 0.05744040508254814}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.21988360207882832
Fold 2 IBS: 0.17431217222470238
Fold 3 IBS: 0.17270104638568878
Fold 4 IBS: 0.20463641353486528
Fold 5 IBS: 0.17927135590564597
[I 2024-04-16 04:45:14,912] Trial 51 finished with value: 0.19016091802594617 and parameters: {'subsample': 0.1037796415557007, 'dropout_rate': 0.9055146088732016, 'n_estimators': 60, 'learning_rate': 0.06727417418455452}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2989296208022043
Fold 2 IBS: 0.29512930046330016
Fold 3 IBS: 0.2549898991060707
Fold 4 IBS: 0.24818909590487848
Fold 5 IBS: 0.25279894324333285
[I 2024-04-16 04:45:17,845] Trial 52 finished with value: 0.2700073719039573 and parameters: {'subsample': 0.12715634150991195, 'dropout_rate': 0.8945471868538436, 'n_estimators': 283, 'learning_rate': 0.07041469798450695}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20322324210759266
Fold 2 IBS: 0.1918100106835177
Fold 3 IBS: 0.1815875682129071
Fold 4 IBS: 0.20403593320107904
Fold 5 IBS: 0.1946064941872063
[I 2024-04-16 04:45:18,107] Trial 53 finished with value: 0.19505264967846056 and parameters: {'subsample': 0.18448407025157104, 'dropout_rate': 0.9328624770007261, 'n_estimators': 17, 'learning_rate': 0.07578506954041273}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.23028430741770006
Fold 2 IBS: 0.17096930262288962
Fold 3 IBS: 0.18939821442036972
Fold 4 IBS: 0.2043222839090868
Fold 5 IBS: 0.17781054667177248
[I 2024-04-16 04:45:18,888] Trial 54 finished with value: 0.19455693100836374 and parameters: {'subsample': 0.12918878557323837, 'dropout_rate': 0.1464738011208001, 'n_estimators': 89, 'learning_rate': 0.08270475242185228}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2280983539938847
Fold 2 IBS: 0.19099960299207666
Fold 3 IBS: 0.1744704649669147
Fold 4 IBS: 0.2080796688839848
Fold 5 IBS: 0.1802166810626113
[I 2024-04-16 04:45:19,484] Trial 55 finished with value: 0.19637295437989444 and parameters: {'subsample': 0.21969252652930607, 'dropout_rate': 0.957476987777337, 'n_estimators': 64, 'learning_rate': 0.06367293488411112}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.21197397617619432
Fold 2 IBS: 0.17711639628837691
Fold 3 IBS: 0.1723602456437429
Fold 4 IBS: 0.20289829160372572
Fold 5 IBS: 0.18074905489539095
[I 2024-04-16 04:45:19,863] Trial 56 finished with value: 0.18901959292148615 and parameters: {'subsample': 0.2687814805867228, 'dropout_rate': 0.35699284194321085, 'n_estimators': 38, 'learning_rate': 0.06944602490457308}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.22604460486616126
Fold 2 IBS: 0.18933987855572929
Fold 3 IBS: 0.17358465858674554
Fold 4 IBS: 0.21393582420281765

Fold 5 IBS: 0.17811616534317862
[I 2024-04-16 04:45:20,303] Trial 57 finished with value: 0.19620422631092646 and parameters: {'subsample': 0.2718885877959942, 'dropout_rate': 0.3400190341028076, 'n_estimators': 46, 'learning_rate': 0.09297626863772185}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.23662970506901534
Fold 2 IBS: 0.19727329320405082
Fold 3 IBS: 0.1930525473184726
Fold 4 IBS: 0.22924643889195298
Fold 5 IBS: 0.18343607043154547
[I 2024-04-16 04:45:21,684] Trial 58 finished with value: 0.20792761098300744 and parameters: {'subsample': 0.15211700057388067, 'dropout_rate': 0.29749461681784134, 'n_estimators': 128, 'learning_rate': 0.052849112789723526}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20644167878414996
Fold 2 IBS: 0.2091292617508421
Fold 3 IBS: 0.19355020066897802
Fold 4 IBS: 0.21277104569319658
Fold 5 IBS: 0.2078375808249311
[I 2024-04-16 04:45:21,982] Trial 59 finished with value: 0.20594595354441955 and parameters: {'subsample': 0.1896407631695771, 'dropout_rate': 0.396089757940819, 'n_estimators': 11, 'learning_rate': 0.047267601674035827}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20584172567435124
Fold 2 IBS: 0.19180127756642001
Fold 3 IBS: 0.18153335358813993
Fold 4 IBS: 0.20585494434452176
Fold 5 IBS: 0.19116709713554733
[I 2024-04-16 04:45:22,469] Trial 60 finished with value: 0.19523967966179606 and parameters: {'subsample': 0.3436490623188294, 'dropout_rate': 0.4436621036466109, 'n_estimators': 37, 'learning_rate': 0.037667655525589566}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2089233659223736
Fold 2 IBS: 0.17030998572966566
Fold 3 IBS: 0.17421763909944618
Fold 4 IBS: 0.19628893915926152
Fold 5 IBS: 0.17109625273922505
[I 2024-04-16 04:45:23,052] Trial 61 finished with value: 0.1841672365299944 and parameters: {'subsample': 0.10675659945557253, 'dropout_rate': 0.24100969721783178, 'n_estimators': 61, 'learning_rate': 0.0684331774579588}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.24147500113135886
Fold 2 IBS: 0.1990407228032597
Fold 3 IBS: 0.19393002501117804
Fold 4 IBS: 0.22111285756598137
Fold 5 IBS: 0.18326312543277626
[I 2024-04-16 04:45:23,962] Trial 62 finished with value: 0.20776434638891086 and parameters: {'subsample': 0.14582532458972652, 'dropout_rate': 0.2297934305095696, 'n_estimators': 106, 'learning_rate': 0.06938674288496754}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2301406115482955
Fold 2 IBS: 0.16971061542942312
Fold 3 IBS: 0.17811233287690997
Fold 4 IBS: 0.2120253534084398
Fold 5 IBS: 0.17289141914813197
[I 2024-04-16 04:45:24,616] Trial 63 finished with value: 0.19257606648224007 and parameters: {'subsample': 0.2158462465276238, 'dropout_rate': 0.15924112104438742, 'n_estimators': 72, 'learning_rate': 0.07496411175439}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.1980447143118628
Fold 2 IBS: 0.1757310259604651
Fold 3 IBS: 0.17826401049264742
Fold 4 IBS: 0.19839268212198738
Fold 5 IBS: 0.18439639658197382
[I 2024-04-16 04:45:24,992] Trial 64 finished with value: 0.1869657658937873 and parameters: {'subsample': 0.10301529068312074, 'dropout_rate': 0.4988567405402422, 'n_estimators': 33, 'learning_rate': 0.05981282502203386}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2362659892867674
Fold 2 IBS: 0.19208481284278522
Fold 3 IBS: 0.18144965308356992
Fold 4 IBS: 0.22241983261989928
Fold 5 IBS: 0.17886412814037478
[I 2024-04-16 04:45:25,800] Trial 65 finished with value: 0.2022168831946793 and parameters: {'subsample': 0.17644011205647003, 'dropout_rate': 0.5570997308490753, 'n_estimators': 86, 'learning_rate': 0.06043126179895617}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20772038095295622
Fold 2 IBS: 0.1743847538619286
Fold 3 IBS: 0.1732644902636153
Fold 4 IBS: 0.1935882545529991
Fold 5 IBS: 0.18158166861445288
[I 2024-04-16 04:45:26,292] Trial 66 finished with value: 0.1861079096491904 and parameters: {'subsample': 0.13554215775252015, 'dropout_rate': 0.5040378850923285, 'n_estimators': 57, 'learning_rate': 0.04150247895904322}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.27321121394428316
Fold 2 IBS: 0.2607993818945804
Fold 3 IBS: 0.23813714126256047
Fold 4 IBS: 0.25295042898307646
Fold 5 IBS: 0.2171792019507428
[I 2024-04-16 04:45:30,374] Trial 67 finished with value: 0.24845547360704864 and parameters: {'subsample': 0.1369289632580445, 'dropout_rate': 0.4931101555252318, 'n_estimators': 321, 'learning_rate': 0.04138264467379664}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.3036484555481385
Fold 2 IBS: 0.28214024717419284
Fold 3 IBS: 0.2628454231827694
Fold 4 IBS: 0.24928020339365212
Fold 5 IBS: 0.24596002479048
[I 2024-04-16 04:45:37,523] Trial 68 finished with value: 0.2687748708178466 and parameters: {'subsample': 0.10360380362115428, 'dropout_rate': 0.5814277625587773, 'n_estimators': 496, 'learning_rate': 0.045563097111329866}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20500709755269472
Fold 2 IBS: 0.18447291620130202
Fold 3 IBS: 0.17672072713752124
Fold 4 IBS: 0.20649674010446548
Fold 5 IBS: 0.18758341689568736
[I 2024-04-16 04:45:37,981] Trial 69 finished with value: 0.19205617957833415 and parameters: {'subsample': 0.24420583391430062, 'dropout_rate': 0.7074571102999617, 'n_estimators': 55, 'learning_rate': 0.03338920960546608}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.31179917563371107
Fold 2 IBS: 0.3125154965028637
Fold 3 IBS: 0.2687239803660891
Fold 4 IBS: 0.2648727758006796
Fold 5 IBS: 0.25750711574342444
[I 2024-04-16 04:45:43,157] Trial 70 finished with value: 0.2830837088093536 and parameters: {'subsample': 0.18584001637236064, 'dropout_rate': 0.4869052821350482, 'n_estimators': 408, 'learning_rate': 0.06465786148033194}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20189277169535388
Fold 2 IBS: 0.19330922773571987
Fold 3 IBS: 0.1842325881345969
Fold 4 IBS: 0.20303794132932199
Fold 5 IBS: 0.19392592316523977
[I 2024-04-16 04:45:43,463] Trial 71 finished with value: 0.19527969041204649 and parameters: {'subsample': 0.14674718396005446, 'dropout_rate': 0.3666473532655053, 'n_estimators': 31, 'learning_rate': 0.04005867703547961}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.21375449643684302
Fold 2 IBS: 0.22051365229999786
Fold 3 IBS: 0.20382773814474373
Fold 4 IBS: 0.22420601973584234
Fold 5 IBS: 0.2175346601999126
[I 2024-04-16 04:45:43,666] Trial 72 finished with value: 0.21596731336346792 and parameters: {'subsample': 0.1624792234408945, 'dropout_rate': 0.42599695015551486, 'n_estimators': 1, 'learning_rate': 0.02887804962126994}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.24884400938948847
Fold 2 IBS: 0.22230670623196708
Fold 3 IBS: 0.2017988785003634
Fold 4 IBS: 0.2133711397731039
Fold 5 IBS: 0.19623207215721594
[I 2024-04-16 04:45:44,414] Trial 73 finished with value: 0.21651056121042775 and parameters: {'subsample': 0.12819906094063338, 'dropout_rate': 0.522228201630752, 'n_estimators': 99, 'learning_rate': 0.07830535290290408}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.1998992787885848
Fold 2 IBS: 0.17479375881465628
Fold 3 IBS: 0.17799109154658554
Fold 4 IBS: 0.19804033795613168
Fold 5 IBS: 0.1799560419158142
[I 2024-04-16 04:45:44,835] Trial 74 finished with value: 0.1861361018043545 and parameters: {'subsample': 0.10086780506047602, 'dropout_rate': 0.32640767931615744, 'n_estimators': 39, 'learning_rate': 0.0523116224602867}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.2055635474684533
Fold 2 IBS: 0.16789387380196955
Fold 3 IBS: 0.1721369810190793
Fold 4 IBS: 0.19699127996147794
Fold 5 IBS: 0.1728475850576181
[I 2024-04-16 04:45:45,360] Trial 75 finished with value: 0.18308665346171962 and parameters: {'subsample': 0.1020805283037595, 'dropout_rate': 0.2440244241800531, 'n_estimators': 65, 'learning_rate': 0.0529939124580232}. Best is trial 41 with value: 0.18279696898170414.
Fold 1 IBS: 0.20819041462280588
Fold 2 IBS: 0.16590386842151703
Fold 3 IBS: 0.17301541569518883
Fold 4 IBS: 0.20200297810324655
Fold 5 IBS: 0.1732421100437509
[I 2024-04-16 04:45:45,958] Trial 76 finished with value: 0.18447095737730185 and parameters: {'subsample': 0.10194070042445058, 'dropout_rate': 0.23111299681749958, 'n_estimators': 73, 'learning_rate': 0.05312229814845394}. Best is trial 41 with value: 0.18279696898170414.

Fold 1 IBS: 0.20857973644761613
Fold 2 IBS: 0.1699443446840626
Fold 3 IBS: 0.17229814826540152
Fold 4 IBS: 0.18923467234725175
Fold 5 IBS: 0.17149001199096955
[I 2024-04-16 04:45:46,581] Trial 77 finished with value: 0.18230938274706032 and parameters: {'subsample': 0.12220726626359973, 'dropout_rate': 0.3022992602914743, 'n_estimators': 67, 'learning_rate': 0.052951683263892116}. Best is trial 77 with value: 0.18230938274706032.
Fold 1 IBS: 0.24216819173841428
Fold 2 IBS: 0.20216193415298328
Fold 3 IBS: 0.19215980224541818
Fold 4 IBS: 0.23811111014860895
Fold 5 IBS: 0.18050576760623235
[I 2024-04-16 04:45:47,712] Trial 78 finished with value: 0.21102136117833142 and parameters: {'subsample': 0.20767510402915473, 'dropout_rate': 0.3088829531372439, 'n_estimators': 129, 'learning_rate': 0.05306134761655199}. Best is trial 77 with value: 0.18230938274706032.
Fold 1 IBS: 0.22260632680353415
Fold 2 IBS: 0.18964762214328523
Fold 3 IBS: 0.17055630609791816
Fold 4 IBS: 0.22240457037821182
Fold 5 IBS: 0.18313693963248504
[I 2024-04-16 04:45:48,413] Trial 79 finished with value: 0.19767035301108687 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.25319794255557226, 'n_estimators': 73, 'learning_rate': 0.044083194959463654}. Best is trial 77 with value: 0.18230938274706032.
Fold 1 IBS: 0.24232728231615944
Fold 2 IBS: 0.20051671880107083
Fold 3 IBS: 0.2006329649804183
Fold 4 IBS: 0.220190686150368
Fold 5 IBS: 0.18858929015975162
[I 2024-04-16 04:45:50,380] Trial 80 finished with value: 0.21045138848155362 and parameters: {'subsample': 0.1706639153996044, 'dropout_rate': 0.18385812878405627, 'n_estimators': 156, 'learning_rate': 0.05197323092794584}. Best is trial 77 with value: 0.18230938274706032.
Fold 1 IBS: 0.2146124093271831
Fold 2 IBS: 0.17294081957379967
Fold 3 IBS: 0.17189894301791206
Fold 4 IBS: 0.19818186349731212
Fold 5 IBS: 0.17360533984740628
[I 2024-04-16 04:45:50,904] Trial 81 finished with value: 0.18624787505272264 and parameters: {'subsample': 0.13152248522649243, 'dropout_rate': 0.22544886919864005, 'n_estimators': 64, 'learning_rate': 0.0578851162161816}. Best is trial 77 with value: 0.18230938274706032.
Fold 1 IBS: 0.20133729113924717
Fold 2 IBS: 0.17026912703967062
Fold 3 IBS: 0.17318481331710597
Fold 4 IBS: 0.1893527200928982
Fold 5 IBS: 0.1756566724938403
[I 2024-04-16 04:45:51,465] Trial 82 finished with value: 0.18196012481655247 and parameters: {'subsample': 0.12340146317823913, 'dropout_rate': 0.22794153979021223, 'n_estimators': 60, 'learning_rate': 0.048462228922252715}. Best is trial 82 with value: 0.18196012481655247.
Fold 1 IBS: 0.2031202940170728
Fold 2 IBS: 0.17302927998461384
Fold 3 IBS: 0.17255969099222987
Fold 4 IBS: 0.18632616175511085
Fold 5 IBS: 0.17464506916315603
[I 2024-04-16 04:45:51,933] Trial 83 finished with value: 0.18193609918243667 and parameters: {'subsample': 0.12485705742267929, 'dropout_rate': 0.26481642929201277, 'n_estimators': 57, 'learning_rate': 0.047702833771498435}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.21135799263117278
Fold 2 IBS: 0.17393432578177798
Fold 3 IBS: 0.1752497648722095
Fold 4 IBS: 0.18911441318043634
Fold 5 IBS: 0.1717861404037639
[I 2024-04-16 04:45:52,720] Trial 84 finished with value: 0.18428852737387208 and parameters: {'subsample': 0.12212329096253392, 'dropout_rate': 0.2605742682796709, 'n_estimators': 93, 'learning_rate': 0.046829241939434205}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.22450741932687698
Fold 2 IBS: 0.1800562142031599
Fold 3 IBS: 0.17962924371529534
Fold 4 IBS: 0.21112708353126397
Fold 5 IBS: 0.1746687676327092
[I 2024-04-16 04:45:53,588] Trial 85 finished with value: 0.19399774568186107 and parameters: {'subsample': 0.15791606254572427, 'dropout_rate': 0.27200249837266405, 'n_estimators': 104, 'learning_rate': 0.04874958436846046}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.23561131873833432
Fold 2 IBS: 0.19281839871797646
Fold 3 IBS: 0.18050118251419245
Fold 4 IBS: 0.2231223811982495
Fold 5 IBS: 0.17821822783789043
[I 2024-04-16 04:45:54,761] Trial 86 finished with value: 0.2020543018013286 and parameters: {'subsample': 0.23156717901682108, 'dropout_rate': 0.25071521496722815, 'n_estimators': 117, 'learning_rate': 0.04622389217355338}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.22146195518479198
Fold 2 IBS: 0.1673678113492015
Fold 3 IBS: 0.17697712896178933
Fold 4 IBS: 0.21525930819477973
Fold 5 IBS: 0.17278291529957804
[I 2024-04-16 04:45:55,803] Trial 87 finished with value: 0.1907698237980281 and parameters: {'subsample': 0.12271865940665135, 'dropout_rate': 0.197988970886231, 'n_estimators': 92, 'learning_rate': 0.05521383858552031}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.21378504331118858
Fold 2 IBS: 0.1847259870740397
Fold 3 IBS: 0.1723434976423815
Fold 4 IBS: 0.2147857379561042
Fold 5 IBS: 0.18098277388962078
[I 2024-04-16 04:45:56,300] Trial 88 finished with value: 0.19332460797466697 and parameters: {'subsample': 0.5241289482849429, 'dropout_rate': 0.21261078462564553, 'n_estimators': 56, 'learning_rate': 0.043527032256299385}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.2149325330167166
Fold 2 IBS: 0.1742251363909817
Fold 3 IBS: 0.1712795708017576
Fold 4 IBS: 0.2008087326563184
Fold 5 IBS: 0.17538825187457738
[I 2024-04-16 04:45:56,960] Trial 89 finished with value: 0.18732684494807034 and parameters: {'subsample': 0.18864283687797054, 'dropout_rate': 0.2688515958254538, 'n_estimators': 67, 'learning_rate': 0.04831269798881077}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.22593594507966341
Fold 2 IBS: 0.19640673401585126
Fold 3 IBS: 0.19348611304409766
Fold 4 IBS: 0.21138091609719037
Fold 5 IBS: 0.17784453735769465
[I 2024-04-16 04:45:58,351] Trial 90 finished with value: 0.20101084911889947 and parameters: {'subsample': 0.12462749523665824, 'dropout_rate': 0.3121052255474563, 'n_estimators': 138, 'learning_rate': 0.04949226064035689}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.2033876712907532
Fold 2 IBS: 0.19625130738052407
Fold 3 IBS: 0.18449891471340055
Fold 4 IBS: 0.2036754795523908
Fold 5 IBS: 0.1955219562524345
[I 2024-04-16 04:45:58,672] Trial 91 finished with value: 0.19666706583790064 and parameters: {'subsample': 0.1530776771535542, 'dropout_rate': 0.32919890172104127, 'n_estimators': 23, 'learning_rate': 0.05090144673246023}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.2077085284242696
Fold 2 IBS: 0.17534267876937557
Fold 3 IBS: 0.1720179417589251
Fold 4 IBS: 0.1984996759907646
Fold 5 IBS: 0.1756160341875212
[I 2024-04-16 04:45:59,347] Trial 92 finished with value: 0.1858369718261712 and parameters: {'subsample': 0.1726736413039105, 'dropout_rate': 0.2927101491043161, 'n_estimators': 78, 'learning_rate': 0.03574075984908321}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.21572259722677448
Fold 2 IBS: 0.1738831129579387
Fold 3 IBS: 0.17169277413039902
Fold 4 IBS: 0.20545594394419206
Fold 5 IBS: 0.1732736515046462
[I 2024-04-16 04:46:00,100] Trial 93 finished with value: 0.18800561595279008 and parameters: {'subsample': 0.20047219302380137, 'dropout_rate': 0.28187170741453327, 'n_estimators': 83, 'learning_rate': 0.03855261120662153}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.1983403625246863
Fold 2 IBS: 0.18385300695358342
Fold 3 IBS: 0.18089513536812923
Fold 4 IBS: 0.19734681668905713
Fold 5 IBS: 0.18710936920646304
[I 2024-04-16 04:46:00,594] Trial 94 finished with value: 0.18950893814838382 and parameters: {'subsample': 0.11969180693103666, 'dropout_rate': 0.24113649107427745, 'n_estimators': 51, 'learning_rate': 0.030333087846255456}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.20557907936552502
Fold 2 IBS: 0.17241707021314165
Fold 3 IBS: 0.1723074751132584
Fold 4 IBS: 0.1964998700868345
Fold 5 IBS: 0.1778080823483427
[I 2024-04-16 04:46:01,253] Trial 95 finished with value: 0.18492231542542045 and parameters: {'subsample': 0.17089604610246867, 'dropout_rate': 0.1754609458460174, 'n_estimators': 73, 'learning_rate': 0.03598332665371665}. Best is trial 83 with value: 0.18193609918243667.

Fold 1 IBS: 0.23957162447856908
Fold 2 IBS: 0.2116279809548012
Fold 3 IBS: 0.1829969605048687
Fold 4 IBS: 0.22906250124122637
Fold 5 IBS: 0.18381146611337082
[I 2024-04-16 04:46:02,257] Trial 96 finished with value: 0.20941410665856722 and parameters: {'subsample': 0.2906503742188524, 'dropout_rate': 0.21627122392159215, 'n_estimators': 109, 'learning_rate': 0.054487916689644846}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.20174967150385922
Fold 2 IBS: 0.18152252410983202
Fold 3 IBS: 0.17926438853781912
Fold 4 IBS: 0.19807000889983026
Fold 5 IBS: 0.1862867633778203
[I 2024-04-16 04:46:02,827] Trial 97 finished with value: 0.18937867128583222 and parameters: {'subsample': 0.15644204623115698, 'dropout_rate': 0.17846494250737677, 'n_estimators': 75, 'learning_rate': 0.022115499272652852}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.20621289427842387
Fold 2 IBS: 0.17587073239319495
Fold 3 IBS: 0.17447698010049484
Fold 4 IBS: 0.19856583741456169
Fold 5 IBS: 0.18059495143457563
[I 2024-04-16 04:46:03,632] Trial 98 finished with value: 0.1871442791242502 and parameters: {'subsample': 0.1765969816312869, 'dropout_rate': 0.13917579939772423, 'n_estimators': 93, 'learning_rate': 0.024206773193594246}. Best is trial 83 with value: 0.18193609918243667.
Fold 1 IBS: 0.24353066540196114
Fold 2 IBS: 0.2263021259360294
Fold 3 IBS: 0.18369909485922287
Fold 4 IBS: 0.25877552724221314
Fold 5 IBS: 0.2056164484182349
[I 2024-04-16 04:46:04,908] Trial 99 finished with value: 0.2235847723715323 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.29616681943805456, 'n_estimators': 161, 'learning_rate': 0.03615906830564851}. Best is trial 83 with value: 0.18193609918243667.


* Best trial for IBS:
 FrozenTrial(number=83, state=TrialState.COMPLETE, values=[0.18193609918243667], datetime_start=datetime.datetime(2024, 4, 16, 4, 45, 51, 470232), datetime_complete=datetime.datetime(2024, 4, 16, 4, 45, 51, 933010), params={'subsample': 0.12485705742267929, 'dropout_rate': 0.26481642929201277, 'n_estimators': 57, 'learning_rate': 0.047702833771498435}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=83, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.12485705742267929, 'dropout_rate': 0.26481642929201277, 'n_estimators': 57, 'learning_rate': 0.047702833771498435}


* Best Score for IBS:
 0.18193609918243667

In [66]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.712
train_ibs:  0.182

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8703793504419942,
                                              learning_rate=0.09213034239034594,
                                              n_estimators=419,
                                              random_state=123,
                                              subsample=0.10218130137857191)

C-index score: 0.575

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.26481642929201277,
                                              learning_rate=0.047702833771498435,
                                              n_estimators=57, random_state=123,
                                              subsample=0.12485705742267929)

IBS: 0.222

In [70]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [71]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.846   1.0
ExtraSurvivalTrees               0.791   2.0
GradientBoosting                 0.765   3.0
CoxElastic                       0.738   4.0
CoxPH                            0.736   5.5
CoxLasso                         0.736   5.5
CoxRidge                         0.724   7.0
ComponentwiseGradientBoosting    0.712   8.0

In [72]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxLasso                       0.171   2.0
CoxElastic                     0.171   2.0
Randomsurvivalforest           0.171   2.0
CoxPH                          0.172   4.0
ExtraSurvivalTrees             0.176   5.0
ComponentwiseGradientBoosting  0.182   6.0
GradientBoosting               0.207   7.0
CoxRidge                       0.217   8.0

In [73]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.602   1.0
GradientBoosting                 0.579   2.0
CoxRidge                         0.578   3.0
ComponentwiseGradientBoosting    0.575   4.0
ExtraSurvivalTrees               0.572   5.0
CoxPH                            0.567   6.0
CoxLasso                         0.566   7.5
CoxElastic                       0.566   7.5

In [74]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.218   1.0
CoxRidge                       0.221   2.5
ExtraSurvivalTrees             0.221   2.5
ComponentwiseGradientBoosting  0.222   4.0
Randomsurvivalforest           0.233   5.0
CoxLasso                       0.257   6.5
CoxElastic                     0.257   6.5
CoxPH                          0.259   8.0

In [77]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/standard/rent/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_standard_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [78]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-16