In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

In [14]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [15]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [16]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [17]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

# Feature Selection

In [18]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"shape_MajorAxisLength",                            
"LBP_120_PET",                                     
"LBP_201_PET",                   
"glszm_SmallAreaLowGrayLevelEmphasis_CT_c16",
"shape_Maximum3DDiameter",
"shape_SurfaceVolumeRatio",                  
"shape_Sphericity",               
"shape_Elongation",                           
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2"    
]

In [19]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [20]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [23]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [24]:
X_new

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,42.073251,0.140311,0.000062,0.029425,47.339202,0.251218,0.761164,0.600926,0.000959
1,24.613845,0.191058,0.000349,0.037915,28.106939,0.489853,0.697049,0.841579,0.002776
2,48.030294,0.126531,0.000000,0.008009,60.049979,0.278467,0.565792,0.772821,0.001179
3,25.589900,0.192388,0.000000,0.018398,32.572995,0.474018,0.684364,0.847727,0.002748
4,34.684750,0.202073,0.000399,0.013051,39.962482,0.563135,0.503142,0.831483,0.002309
...,...,...,...,...,...,...,...,...,...
134,33.069705,0.152626,0.000000,0.014938,37.696154,0.322021,0.742102,0.680294,0.001347
135,41.043692,0.142778,0.000079,0.011441,52.430907,0.227705,0.722918,0.758193,0.000850
136,36.618802,0.140582,0.000000,0.020431,42.743421,0.298398,0.652963,0.770113,0.001111
137,45.870392,0.156640,0.000054,0.019663,51.536395,0.252893,0.724255,0.628897,0.000935
138,30.363259,0.147644,0.000000,0.013864,39.408121,0.290461,0.722633,0.892637,0.000629

In [25]:
X_new_std

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,-0.098422,-0.476493,-0.315438,1.274405,-0.205326,-0.558082,1.075042,-0.681983,-0.496657
1,-1.209119,1.084993,1.967842,2.273964,-1.196220,1.585077,0.242767,1.006304,2.054251
2,0.280542,-0.900502,-0.805067,-1.246890,0.449566,-0.313359,-1.461057,0.523938,-0.187799
3,-1.147026,1.125919,-0.805067,-0.023759,-0.966118,1.442865,0.078112,1.049432,2.014276
4,-0.568449,1.423898,2.359078,-0.653294,-0.585393,2.243217,-2.274305,0.935477,1.398595
...,...,...,...,...,...,...,...,...,...
134,-0.671191,-0.097562,-0.805067,-0.431120,-0.702160,0.077795,0.827589,-0.125182,0.048554
135,-0.163918,-0.400566,-0.180035,-0.842806,0.057012,-0.769256,0.578577,0.421312,-0.649927
136,-0.445412,-0.468144,-0.805067,0.215575,-0.442112,-0.134362,-0.329498,0.504939,-0.282932
137,0.143137,0.025938,-0.374777,0.125178,0.010924,-0.543043,0.595927,-0.485754,-0.529934
138,-0.843364,-0.250857,-0.805067,-0.557574,-0.613955,-0.205649,0.574872,1.364493,-0.959367

In [26]:
MAASTRO_new

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,50.002093,0.122209,0.000026,0.010495,58.864251,0.215184,0.668072,0.765178,0.000768
1,41.753334,0.128976,0.000167,0.035018,48.723711,0.276092,0.669961,0.776540,0.001213
2,44.375483,0.137282,0.000000,0.012819,48.969378,0.298887,0.624081,0.697164,0.001176
3,46.115989,0.171595,0.000080,0.029974,55.226805,0.361096,0.577624,0.574636,0.001192
4,54.394967,0.128134,0.000035,0.013458,67.089492,0.251519,0.630933,0.633419,0.000766
...,...,...,...,...,...,...,...,...,...
94,34.218615,0.137194,0.000078,0.039092,43.520110,0.307574,0.671754,0.882411,0.001137
95,51.046869,0.137620,0.000054,0.015831,52.440442,0.289922,0.632189,0.535802,0.000962
96,50.417953,0.115099,0.000028,0.011031,57.671483,0.228184,0.645548,0.716610,0.000621
97,44.901412,0.117654,0.000000,0.019801,51.478151,0.223872,0.727488,0.665145,0.000947
98,36.574294,0.156924,0.000112,0.015813,43.485630,0.347373,0.672838,0.616262,0.001661

In [27]:
MAASTRO_new_std

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,0.405980,-1.033478,-0.596780,-0.954258,0.388474,-0.881698,-0.133381,0.470316,-0.764236
1,-0.118774,-0.825249,0.524128,1.932841,-0.133992,-0.334696,-0.108854,0.550025,-0.139994
2,0.048037,-0.569695,-0.805067,-0.680666,-0.121335,-0.129977,-0.704414,-0.006831,-0.191744
3,0.158761,0.486120,-0.170569,1.338998,0.201064,0.428717,-1.307469,-0.866418,-0.168865
4,0.685437,-0.851180,-0.525146,-0.605333,0.812259,-0.555379,-0.615466,-0.454030,-0.767510
...,...,...,...,...,...,...,...,...,...
94,-0.598102,-0.572399,-0.187979,2.412550,-0.402095,-0.051953,-0.085581,1.292755,-0.246354
95,0.472444,-0.559284,-0.373913,-0.326069,0.057503,-0.210490,-0.599161,-1.138850,-0.492861
96,0.432435,-1.252248,-0.581052,-0.891107,0.327020,-0.764952,-0.425762,0.129595,-0.971544
97,0.081495,-1.173644,-0.805067,0.141405,0.007923,-0.803671,0.637891,-0.231458,-0.513058
98,-0.448243,0.034704,0.087339,-0.328119,-0.403871,0.305474,-0.071514,-0.574392,0.488842

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [28]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:13:11,330] A new study created in memory with name: no-name-5af1276c-e721-4314-99b2-8f10d6764512

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429

[I 2024-04-16 01:13:28,393] A new study created in memory with name: no-name-93b9b893-8f15-42ca-9f1c-9ba26aa4a6f3

Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:13:28,382] Trial 0 finished with value: 0.7353909570603067 and parameters: {}. Best is trial 0 with value: 0.7353909570603067.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7353909570603067], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 11, 497359), datetime_complete=datetime.datetime(2024, 4, 16, 1, 13, 28, 382078), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7353909570603067

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.19333371135654168
Fold 2 IBS: 0.15067618719150463
Fold 3 IBS: 0.16491771324415705
Fold 4 IBS: 0.14041209978706223
Fold 5 IBS: 0.15824636706666786
[I 2024-04-16 01:13:29,022] Trial 0 finished with value: 0.1615172157291867 and parameters: {}. Best is trial 0 with value: 0.1615172157291867.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1615172157291867], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 28, 502183), datetime_complete=datetime.datetime(2024, 4, 16, 1, 13, 29, 21943), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1615172157291867

In [29]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [30]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.735
train_ibs:  0.162

#### Test

In [31]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [32]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.558
IBS score: 0.252

In [33]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:13:29,422] A new study created in memory with name: no-name-e5c69fcf-9dea-4f85-aba4-27ae92a1f337

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.7236286919831224

[I 2024-04-16 01:13:29,814] A new study created in memory with name: no-name-9737969a-741f-4fa6-8cb7-682c10a4d9b6

Fold 5 C-index: 0.7206572769953051
[I 2024-04-16 01:13:29,807] Trial 0 finished with value: 0.7179052903070173 and parameters: {}. Best is trial 0 with value: 0.7179052903070173.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7179052903070173], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 29, 499101), datetime_complete=datetime.datetime(2024, 4, 16, 1, 13, 29, 807236), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7179052903070173

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2139765126020755
Fold 2 IBS: 0.22157789890073135
Fold 3 IBS: 0.20453593468821316
Fold 4 IBS: 0.22473802683456762
Fold 5 IBS: 0.2181243002990223
[I 2024-04-16 01:13:30,197] Trial 0 finished with value: 0.216590534664922 and parameters: {}. Best is trial 0 with value: 0.216590534664922.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.216590534664922], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 29, 857808), datetime_complete=datetime.datetime(2024, 4, 16, 1, 13, 30, 197741), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.216590534664922

In [36]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.718
train_ibs:  0.217

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.585

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:13:30,611] A new study created in memory with name: no-name-df3e20dc-d8bf-4d10-8dcc-7cbed0b008e1

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764

[I 2024-04-16 01:13:31,792] A new study created in memory with name: no-name-2982a3b8-5f3e-4008-a200-fc1d6b3c0f80

Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:31,779] Trial 0 finished with value: 0.7362153329053951 and parameters: {}. Best is trial 0 with value: 0.7362153329053951.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7362153329053951], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 30, 664215), datetime_complete=datetime.datetime(2024, 4, 16, 1, 13, 31, 776222), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7362153329053951

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.19259004244708322
Fold 2 IBS: 0.15095293415067815
Fold 3 IBS: 0.16506977710039145
Fold 4 IBS: 0.14090021777600747
Fold 5 IBS: 0.15728492161183458
[I 2024-04-16 01:13:33,253] Trial 0 finished with value: 0.161359578617199 and parameters: {}. Best is trial 0 with value: 0.161359578617199.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.161359578617199], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 31, 832918), datetime_complete=datetime.datetime(2024, 4, 16, 1, 13, 33, 253236), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.161359578617199

In [42]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.161

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.556

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.251

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:13:34,222] A new study created in memory with name: no-name-68f3e1e5-e531-448e-a12a-5a5814549f4e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:35,832] Trial 0 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:37,580] Trial 1 finished with value: 0.7370321584848789 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:39,721] Trial 2 finished with value: 0.736166357619078 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:41,267] Trial 3 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:42,686] Trial 4 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:44,081] Trial 5 finished with value: 0.737081133771196 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:45,429] Trial 6 finished with value: 0.7362153329053951 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:47,593] Trial 7 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:49,354] Trial 8 finished with value: 0.7353495320395942 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:51,619] Trial 9 finished with value: 0.7353224757625381 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:53,517] Trial 10 finished with value: 0.7362153329053951 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:54,977] Trial 11 finished with value: 0.7353224757625381 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:56,224] Trial 12 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6978253640763652}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:57,342] Trial 13 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6189362712539238}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:58,383] Trial 14 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.8403787283021946}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:13:59,487] Trial 15 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5892251114089379}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:01,661] Trial 16 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.8361111870922124}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:03,096] Trial 17 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5632480038685016}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:05,469] Trial 18 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:07,312] Trial 19 finished with value: 0.736166357619078 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:08,881] Trial 20 finished with value: 0.7353224757625381 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:09,721] Trial 21 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7501344475278824}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:10,960] Trial 22 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5339346419626306}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:12,139] Trial 23 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.651954326927192}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671

Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:13,310] Trial 24 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7602371709740536}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:14,327] Trial 25 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.891573855041803}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:15,390] Trial 26 finished with value: 0.7362153329053951 and parameters: {'l1_ratio': 0.4514399534035586}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:16,396] Trial 27 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7284175098086105}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:17,559] Trial 28 finished with value: 0.7361882766283389 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:18,662] Trial 29 finished with value: 0.7362153329053951 and parameters: {'l1_ratio': 0.5124352690792928}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:19,557] Trial 30 finished with value: 0.736166357619078 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:20,615] Trial 31 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.6596525167637547}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:21,712] Trial 32 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6857443046675039}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:23,111] Trial 33 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.9061337786354179}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:24,428] Trial 34 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6058606419923311}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:25,758] Trial 35 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7874925212498598}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:27,509] Trial 36 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5411641129675752}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:28,834] Trial 37 finished with value: 0.7362153329053951 and parameters: {'l1_ratio': 0.4595613720024655}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:30,323] Trial 38 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7154003641818388}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:31,554] Trial 39 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.8929299852613041}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:33,291] Trial 40 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6249208315031473}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:34,905] Trial 41 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6974065769391812}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:36,026] Trial 42 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.651204305901999}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:37,101] Trial 43 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7801382834729624}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:38,391] Trial 44 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.8463092270988435}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:39,914] Trial 45 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5895482832037173}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:41,432] Trial 46 finished with value: 0.7353495320395942 and parameters: {'l1_ratio': 0.39434450152883677}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:42,986] Trial 47 finished with value: 0.7353495320395942 and parameters: {'l1_ratio': 0.49230249755013855}. Best is trial 0 with value: 0.7371957250622578.

Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:45,021] Trial 48 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:46,669] Trial 49 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.9505380767046984}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:47,934] Trial 50 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7193579141150094}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:49,577] Trial 51 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.6271636431064334}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:52,355] Trial 52 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6782914951568334}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:53,919] Trial 53 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.8268334901731347}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:55,599] Trial 54 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5477089845053262}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:57,130] Trial 55 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7471979487589616}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:14:58,809] Trial 56 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.6661311758467192}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:00,958] Trial 57 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6215400430626747}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:02,730] Trial 58 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5817625381876361}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:04,981] Trial 59 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7867155731311003}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:06,909] Trial 60 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7448266139567907}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:08,628] Trial 61 finished with value: 0.7353495320395942 and parameters: {'l1_ratio': 0.5115019231013023}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:11,305] Trial 62 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.6450607319043137}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:12,885] Trial 63 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6975448031675533}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:14,415] Trial 64 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5943841784661934}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:15,819] Trial 65 finished with value: 0.7362153329053951 and parameters: {'l1_ratio': 0.45945313564733314}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:17,548] Trial 66 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5581314645294639}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:19,646] Trial 67 finished with value: 0.7353224757625381 and parameters: {'l1_ratio': 0.10022359348974141}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:21,412] Trial 68 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7108181313858255}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:23,480] Trial 69 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5279758389755447}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:25,541] Trial 70 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6190167670320361}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:27,259] Trial 71 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6738121537448595}. Best is trial 0 with value: 0.7371957250622578.

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:29,457] Trial 72 finished with value: 0.7353495320395942 and parameters: {'l1_ratio': 0.4779945081186193}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:31,122] Trial 73 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.641247699738042}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:32,742] Trial 74 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6030690542690681}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:34,607] Trial 75 finished with value: 0.737081133771196 and parameters: {'l1_ratio': 0.4287223600521837}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:36,707] Trial 76 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7594301040483231}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:39,044] Trial 77 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5735926164633917}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:40,414] Trial 78 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.8060668631477719}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:41,670] Trial 79 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7215389397419747}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:43,039] Trial 80 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.531779278382202}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:44,434] Trial 81 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.8415433390288768}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:45,952] Trial 82 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6916309290120963}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:47,029] Trial 83 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7714724753913326}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:48,374] Trial 84 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7351076045661868}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:49,486] Trial 85 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.8644152289186137}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:50,657] Trial 86 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.6560355399332157}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:51,699] Trial 87 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.8004431456315502}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:53,576] Trial 88 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6065949525242393}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:55,664] Trial 89 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.815241224128888}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:57,108] Trial 90 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.9386223856552165}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:15:58,907] Trial 91 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.6825240572773039}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:00,024] Trial 92 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7455353888165118}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:01,918] Trial 93 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5539422560159201}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:05,114] Trial 94 finished with value: 0.7353224757625381 and parameters: {'l1_ratio': 0.20861297276894075}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:07,015] Trial 95 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.6335563579825483}. Best is trial 0 with value: 0.7371957250622578.

Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:08,484] Trial 96 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7064293773150284}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:09,686] Trial 97 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.7626044618582731}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:10,964] Trial 98 finished with value: 0.7363299241964569 and parameters: {'l1_ratio': 0.6627989087129681}. Best is trial 0 with value: 0.7371957250622578.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764

[I 2024-04-16 01:16:12,779] A new study created in memory with name: no-name-359d0de0-62e1-41a5-8682-9300a411a00c

Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:16:12,717] Trial 99 finished with value: 0.7371957250622578 and parameters: {'l1_ratio': 0.5842252560607772}. Best is trial 0 with value: 0.7371957250622578.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7371957250622578], datetime_start=datetime.datetime(2024, 4, 16, 1, 13, 34, 258043), datetime_complete=datetime.datetime(2024, 4, 16, 1, 13, 35, 830837), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.7371957250622578

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1924091236994006
Fold 2 IBS: 0.15100907458197557
Fold 3 IBS: 0.16515213945655605
Fold 4 IBS: 0.14095407602839238
Fold 5 IBS: 0.15716501008569841
[I 2024-04-16 01:16:15,306] Trial 0 finished with value: 0.16133788477040462 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.16133788477040462.
Fold 1 IBS: 0.19224040788134886
Fold 2 IBS: 0.1513100086548913
Fold 3 IBS: 0.16513327447848067
Fold 4 IBS: 0.14108395736695672
Fold 5 IBS: 0.1569966672751516
[I 2024-04-16 01:16:17,475] Trial 1 finished with value: 0.16135286313136585 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.16133788477040462.
Fold 1 IBS: 0.19225265245976847
Fold 2 IBS: 0.15136771001345142
Fold 3 IBS: 0.16511837524137413
Fold 4 IBS: 0.14110709736340937
Fold 5 IBS: 0.1569595401131213
[I 2024-04-16 01:16:20,399] Trial 2 finished with value: 0.16136107503822494 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.16133788477040462.
Fold 1 IBS: 0.19237738070166305
Fold 2 IBS: 0.15107271590669683
Fold 3 IBS: 0.1651702703772429
Fold 4 IBS: 0.14099871186269566
Fold 5 IBS: 0.1570548087557817
[I 2024-04-16 01:16:22,242] Trial 3 finished with value: 0.16133477752081604 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.16133477752081604.
Fold 1 IBS: 0.19242404472727093
Fold 2 IBS: 0.15100592477322483
Fold 3 IBS: 0.16515089164329463
Fold 4 IBS: 0.14093960290132815
Fold 5 IBS: 0.15719099452212132
[I 2024-04-16 01:16:25,060] Trial 4 finished with value: 0.161342291713448 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 3 with value: 0.16133477752081604.
Fold 1 IBS: 0.1923188596214172
Fold 2 IBS: 0.15117932693820527
Fold 3 IBS: 0.1651600317757817
Fold 4 IBS: 0.14103263299928784
Fold 5 IBS: 0.15708337879529266
[I 2024-04-16 01:16:27,265] Trial 5 finished with value: 0.16135484602599695 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 3 with value: 0.16133477752081604.
Fold 1 IBS: 0.19258249853584344
Fold 2 IBS: 0.15095479349112978
Fold 3 IBS: 0.16507689092731226
Fold 4 IBS: 0.1409031696128558
Fold 5 IBS: 0.15727179529396068
[I 2024-04-16 01:16:29,407] Trial 6 finished with value: 0.1613578295722204 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 3 with value: 0.16133477752081604.
Fold 1 IBS: 0.19240196948238011
Fold 2 IBS: 0.1510107531824369
Fold 3 IBS: 0.165152622709647
Fold 4 IBS: 0.140952034121176
Fold 5 IBS: 0.15715053059957046
[I 2024-04-16 01:16:32,068] Trial 7 finished with value: 0.1613335820190421 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 7 with value: 0.1613335820190421.
Fold 1 IBS: 0.19238542735871744
Fold 2 IBS: 0.15113066754097737
Fold 3 IBS: 0.16516519615110153
Fold 4 IBS: 0.14101258135836903
Fold 5 IBS: 0.1571090700261996
[I 2024-04-16 01:16:34,271] Trial 8 finished with value: 0.16136058848707296 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 7 with value: 0.1613335820190421.
Fold 1 IBS: 0.19235523391941012
Fold 2 IBS: 0.1512274719820786
Fold 3 IBS: 0.16515572841197126
Fold 4 IBS: 0.14103125238876407
Fold 5 IBS: 0.15701829948102028
[I 2024-04-16 01:16:36,241] Trial 9 finished with value: 0.16135759723664886 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 7 with value: 0.1613335820190421.
Fold 1 IBS: 0.1925839905903438
Fold 2 IBS: 0.15095449697539143
Fold 3 IBS: 0.1650749372107073
Fold 4 IBS: 0.14090248465226546
Fold 5 IBS: 0.15727168863352375
[I 2024-04-16 01:16:38,179] Trial 10 finished with value: 0.16135751961244632 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 7 with value: 0.1613335820190421.
Fold 1 IBS: 0.1921002854973763
Fold 2 IBS: 0.1515735626302408
Fold 3 IBS: 0.16489509503444505
Fold 4 IBS: 0.1412463996030073
Fold 5 IBS: 0.15679394936684882
[I 2024-04-16 01:16:40,958] Trial 11 finished with value: 0.16132185842638366 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19210818559840634
Fold 2 IBS: 0.15156858145137636
Fold 3 IBS: 0.16489796753759917
Fold 4 IBS: 0.1412421153153704
Fold 5 IBS: 0.15680283141001586
[I 2024-04-16 01:16:43,514] Trial 12 finished with value: 0.16132393626255365 and parameters: {'l1_ratio': 0.04736808959830728}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.21355817659658274
Fold 2 IBS: 0.22075847112249886
Fold 3 IBS: 0.2039712820983237
Fold 4 IBS: 0.22408506786330645
Fold 5 IBS: 0.21745523507221248
[I 2024-04-16 01:16:44,178] Trial 13 finished with value: 0.21596564655058487 and parameters: {'l1_ratio': 0.004536793701860359}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.1921367346944789
Fold 2 IBS: 0.15160906598527457
Fold 3 IBS: 0.16492311589818348
Fold 4 IBS: 0.14126762345162774
Fold 5 IBS: 0.15677111157043358
[I 2024-04-16 01:16:47,134] Trial 14 finished with value: 0.16134153031999965 and parameters: {'l1_ratio': 0.025872979672365074}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19214346827469644
Fold 2 IBS: 0.15148144036587527
Fold 3 IBS: 0.16505088757443262
Fold 4 IBS: 0.14120726988300095
Fold 5 IBS: 0.1568548402567624
[I 2024-04-16 01:16:49,539] Trial 15 finished with value: 0.16134758127095356 and parameters: {'l1_ratio': 0.13901336863085584}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19221727497063085
Fold 2 IBS: 0.15149375112725913
Fold 3 IBS: 0.16503753530600884
Fold 4 IBS: 0.14117409687228064
Fold 5 IBS: 0.15692398793885365
[I 2024-04-16 01:16:52,223] Trial 16 finished with value: 0.16136932924300662 and parameters: {'l1_ratio': 0.13624275734214056}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19231064986630647
Fold 2 IBS: 0.15132425609486164
Fold 3 IBS: 0.1651311669719029
Fold 4 IBS: 0.14109259372451297
Fold 5 IBS: 0.15697547019532795
[I 2024-04-16 01:16:54,812] Trial 17 finished with value: 0.1613668273705824 and parameters: {'l1_ratio': 0.27980822772479336}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19219314792792128
Fold 2 IBS: 0.15146477519620144
Fold 3 IBS: 0.1650191884813841
Fold 4 IBS: 0.14118780300229927
Fold 5 IBS: 0.15689831444488683
[I 2024-04-16 01:16:57,935] Trial 18 finished with value: 0.1613526458105386 and parameters: {'l1_ratio': 0.13219667268922902}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19216172952474433
Fold 2 IBS: 0.15154232478177607
Fold 3 IBS: 0.16491321871207953
Fold 4 IBS: 0.1412337615607139
Fold 5 IBS: 0.15681676956947319
[I 2024-04-16 01:17:00,464] Trial 19 finished with value: 0.16133356082975742 and parameters: {'l1_ratio': 0.08329909699602694}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.1922660093213748
Fold 2 IBS: 0.15138471489218697
Fold 3 IBS: 0.16511820596083748
Fold 4 IBS: 0.14114923649880234
Fold 5 IBS: 0.15695227569771483
[I 2024-04-16 01:17:03,183] Trial 20 finished with value: 0.1613740884741833 and parameters: {'l1_ratio': 0.20534668065344552}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19215458574294186
Fold 2 IBS: 0.15155758744999345
Fold 3 IBS: 0.16495242770402221
Fold 4 IBS: 0.14124246131652599
Fold 5 IBS: 0.15680193388276054
[I 2024-04-16 01:17:06,277] Trial 21 finished with value: 0.1613417992192488 and parameters: {'l1_ratio': 0.07457803044708419}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.21309386009778244
Fold 2 IBS: 0.21984831229155624
Fold 3 IBS: 0.16493421023384375
Fold 4 IBS: 0.22335885075096143
Fold 5 IBS: 0.155722373116403
[I 2024-04-16 01:17:07,933] Trial 22 finished with value: 0.19539152129810938 and parameters: {'l1_ratio': 0.009736061889810035}. Best is trial 11 with value: 0.16132185842638366.
Fold 1 IBS: 0.19213031830031066
Fold 2 IBS: 0.15147595271019906
Fold 3 IBS: 0.16499667600081724
Fold 4 IBS: 0.14118827001241308
Fold 5 IBS: 0.15681418585026652
[I 2024-04-16 01:17:09,837] Trial 23 finished with value: 0.1613210805748013 and parameters: {'l1_ratio': 0.11029047079437374}. Best is trial 23 with value: 0.1613210805748013.
Fold 1 IBS: 0.19230335851931124
Fold 2 IBS: 0.15129066539949787
Fold 3 IBS: 0.16513792885769488
Fold 4 IBS: 0.1410796871938025
Fold 5 IBS: 0.1569951994009031
[I 2024-04-16 01:17:11,766] Trial 24 finished with value: 0.1613613678742419 and parameters: {'l1_ratio': 0.3148818149709026}. Best is trial 23 with value: 0.1613210805748013.

Fold 1 IBS: 0.19224653568521086
Fold 2 IBS: 0.1514012960785
Fold 3 IBS: 0.16511102888971094
Fold 4 IBS: 0.14115758164128042
Fold 5 IBS: 0.15692934744828077
[I 2024-04-16 01:17:13,698] Trial 25 finished with value: 0.1613691579485966 and parameters: {'l1_ratio': 0.19986779381542577}. Best is trial 23 with value: 0.1613210805748013.
Fold 1 IBS: 0.19216832011525717
Fold 2 IBS: 0.15152482381793653
Fold 3 IBS: 0.16493778163834757
Fold 4 IBS: 0.14122630371616415
Fold 5 IBS: 0.15682357675923148
[I 2024-04-16 01:17:15,373] Trial 26 finished with value: 0.1613361612093874 and parameters: {'l1_ratio': 0.09330393750339382}. Best is trial 23 with value: 0.1613210805748013.
Fold 1 IBS: 0.1923201307567279
Fold 2 IBS: 0.15123003880949595
Fold 3 IBS: 0.1651550503840734
Fold 4 IBS: 0.14105230435301389
Fold 5 IBS: 0.15704828050001218
[I 2024-04-16 01:17:16,940] Trial 27 finished with value: 0.16136116096066466 and parameters: {'l1_ratio': 0.36900835392127096}. Best is trial 23 with value: 0.1613210805748013.
Fold 1 IBS: 0.19225601296779954
Fold 2 IBS: 0.15139321671564016
Fold 3 IBS: 0.16511359145783847
Fold 4 IBS: 0.14115168192391653
Fold 5 IBS: 0.15694231773061357
[I 2024-04-16 01:17:18,647] Trial 28 finished with value: 0.16137136415916165 and parameters: {'l1_ratio': 0.2025095518368651}. Best is trial 23 with value: 0.1613210805748013.
Fold 1 IBS: 0.19240587676536774
Fold 2 IBS: 0.15103480584772105
Fold 3 IBS: 0.16516597867360178
Fold 4 IBS: 0.14098018162273454
Fold 5 IBS: 0.15710647393135843
[I 2024-04-16 01:17:20,290] Trial 29 finished with value: 0.16133866336815672 and parameters: {'l1_ratio': 0.5855725205640325}. Best is trial 23 with value: 0.1613210805748013.
Fold 1 IBS: 0.1921674694288463
Fold 2 IBS: 0.15156711165532438
Fold 3 IBS: 0.16488227439427286
Fold 4 IBS: 0.14124683756248285
Fold 5 IBS: 0.15679849762631323
[I 2024-04-16 01:17:22,722] Trial 30 finished with value: 0.16133243813344791 and parameters: {'l1_ratio': 0.06176725679988401}. Best is trial 23 with value: 0.1613210805748013.
Fold 1 IBS: 0.19211958542927238
Fold 2 IBS: 0.1515199695500571
Fold 3 IBS: 0.16493436832269598
Fold 4 IBS: 0.14121630046376787
Fold 5 IBS: 0.15677090737947955
[I 2024-04-16 01:17:24,843] Trial 31 finished with value: 0.16131222622905456 and parameters: {'l1_ratio': 0.0794280106474206}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19222589249745903
Fold 2 IBS: 0.15146665446154325
Fold 3 IBS: 0.16507350680144733
Fold 4 IBS: 0.14115833785935034
Fold 5 IBS: 0.1568625716600906
[I 2024-04-16 01:17:27,415] Trial 32 finished with value: 0.16135739265597815 and parameters: {'l1_ratio': 0.15407760528465997}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19228651970336677
Fold 2 IBS: 0.15130762729711522
Fold 3 IBS: 0.1651350378399309
Fold 4 IBS: 0.14109002141246232
Fold 5 IBS: 0.15697048656632637
[I 2024-04-16 01:17:29,193] Trial 33 finished with value: 0.16135793856384031 and parameters: {'l1_ratio': 0.306560388921177}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19224885818874723
Fold 2 IBS: 0.15134010769636327
Fold 3 IBS: 0.16512581636101964
Fold 4 IBS: 0.1410962467673928
Fold 5 IBS: 0.15697564169390793
[I 2024-04-16 01:17:31,025] Trial 34 finished with value: 0.16135733414148618 and parameters: {'l1_ratio': 0.2549255900671562}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.21387243086305852
Fold 2 IBS: 0.2213742576035951
Fold 3 IBS: 0.20439534580808713
Fold 4 IBS: 0.224575823035611
Fold 5 IBS: 0.2179578041258731
[I 2024-04-16 01:17:31,757] Trial 35 finished with value: 0.21643513228724495 and parameters: {'l1_ratio': 0.00111713838428186}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19258636259491366
Fold 2 IBS: 0.1509726667874752
Fold 3 IBS: 0.16511086682082085
Fold 4 IBS: 0.14091428681249307
Fold 5 IBS: 0.1572434791236023
[I 2024-04-16 01:17:34,091] Trial 36 finished with value: 0.161365532427861 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19221319859798902
Fold 2 IBS: 0.15145436006975155
Fold 3 IBS: 0.1650944729282177
Fold 4 IBS: 0.14115607390945129
Fold 5 IBS: 0.15695153534472306
[I 2024-04-16 01:17:36,513] Trial 37 finished with value: 0.16137392817002652 and parameters: {'l1_ratio': 0.1697841258376892}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19213677219699196
Fold 2 IBS: 0.15154678610802982
Fold 3 IBS: 0.16496477986230018
Fold 4 IBS: 0.14124072377382396
Fold 5 IBS: 0.15680091553022724
[I 2024-04-16 01:17:39,108] Trial 38 finished with value: 0.16133799549427463 and parameters: {'l1_ratio': 0.08997775657886409}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19221836768183437
Fold 2 IBS: 0.15136735542144686
Fold 3 IBS: 0.16511987858179467
Fold 4 IBS: 0.14111352115704417
Fold 5 IBS: 0.15693736444320883
[I 2024-04-16 01:17:41,600] Trial 39 finished with value: 0.1613512974570658 and parameters: {'l1_ratio': 0.24372616700534455}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19213754096963825
Fold 2 IBS: 0.15154315258476614
Fold 3 IBS: 0.16490578727385946
Fold 4 IBS: 0.1412691553380633
Fold 5 IBS: 0.15676044972797956
[I 2024-04-16 01:17:44,574] Trial 40 finished with value: 0.16132321717886133 and parameters: {'l1_ratio': 0.0540142215557777}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19209871917679297
Fold 2 IBS: 0.1515679819552666
Fold 3 IBS: 0.16488766290698686
Fold 4 IBS: 0.1412471150792769
Fold 5 IBS: 0.1567977885264593
[I 2024-04-16 01:17:48,044] Trial 41 finished with value: 0.16131985352895653 and parameters: {'l1_ratio': 0.05178390796341566}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19221764193696597
Fold 2 IBS: 0.1514620989020046
Fold 3 IBS: 0.16501572450492724
Fold 4 IBS: 0.14118129606104102
Fold 5 IBS: 0.15682442984738512
[I 2024-04-16 01:17:51,656] Trial 42 finished with value: 0.16134023825046478 and parameters: {'l1_ratio': 0.12248076724953963}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19213643076889098
Fold 2 IBS: 0.15153602765126056
Fold 3 IBS: 0.1649148883455243
Fold 4 IBS: 0.14126852828837475
Fold 5 IBS: 0.15676357180305334
[I 2024-04-16 01:17:56,098] Trial 43 finished with value: 0.16132388937142078 and parameters: {'l1_ratio': 0.05967132226089084}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19220796208238877
Fold 2 IBS: 0.15141294760358878
Fold 3 IBS: 0.16509209408683995
Fold 4 IBS: 0.14115910217427133
Fold 5 IBS: 0.15694828963490925
[I 2024-04-16 01:17:59,822] Trial 44 finished with value: 0.16136407911639963 and parameters: {'l1_ratio': 0.16863037253768395}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19209020494160042
Fold 2 IBS: 0.1515797484564383
Fold 3 IBS: 0.16489612877619436
Fold 4 IBS: 0.14125164132411
Fold 5 IBS: 0.1567849245560896
[I 2024-04-16 01:18:05,545] Trial 45 finished with value: 0.16132052961088655 and parameters: {'l1_ratio': 0.04648364054593243}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19236125555823008
Fold 2 IBS: 0.15116068840967717
Fold 3 IBS: 0.1651641317619956
Fold 4 IBS: 0.14100651782507878
Fold 5 IBS: 0.1570685943801217
[I 2024-04-16 01:18:08,846] Trial 46 finished with value: 0.16135223758702066 and parameters: {'l1_ratio': 0.4590297364132472}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.1923621772420772
Fold 2 IBS: 0.15109375938980493
Fold 3 IBS: 0.165161914786926
Fold 4 IBS: 0.1409851296163984
Fold 5 IBS: 0.1571088925942294
[I 2024-04-16 01:18:12,575] Trial 47 finished with value: 0.16134237472588717 and parameters: {'l1_ratio': 0.5332122566861169}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.1921570240737253
Fold 2 IBS: 0.15150505301240438
Fold 3 IBS: 0.16501737484950782
Fold 4 IBS: 0.1412174872895213
Fold 5 IBS: 0.1567540971353333
[I 2024-04-16 01:18:15,934] Trial 48 finished with value: 0.16133020727209843 and parameters: {'l1_ratio': 0.11380051916578994}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19229834635087303
Fold 2 IBS: 0.15125300348472356
Fold 3 IBS: 0.16514512064804412
Fold 4 IBS: 0.14106526479380488

Fold 5 IBS: 0.15701796152708983
[I 2024-04-16 01:18:18,186] Trial 49 finished with value: 0.16135593936090709 and parameters: {'l1_ratio': 0.355745098499332}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19213004749485835
Fold 2 IBS: 0.1516050789806051
Fold 3 IBS: 0.16491435357809608
Fold 4 IBS: 0.14127121223801825
Fold 5 IBS: 0.15677031539860345
[I 2024-04-16 01:18:20,771] Trial 50 finished with value: 0.1613382015380362 and parameters: {'l1_ratio': 0.031172779494489454}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.192147532060445
Fold 2 IBS: 0.1515959806078035
Fold 3 IBS: 0.1649120166996046
Fold 4 IBS: 0.14126663770372325
Fold 5 IBS: 0.15676415266897656
[I 2024-04-16 01:18:24,929] Trial 51 finished with value: 0.1613372639481106 and parameters: {'l1_ratio': 0.04941055987304063}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19215096099775522
Fold 2 IBS: 0.15152443878761593
Fold 3 IBS: 0.16499817043361403
Fold 4 IBS: 0.14122945883194515
Fold 5 IBS: 0.15682744197319404
[I 2024-04-16 01:18:28,426] Trial 52 finished with value: 0.16134609420482487 and parameters: {'l1_ratio': 0.10149217902459388}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.2138389319251656
Fold 2 IBS: 0.22130868324372227
Fold 3 IBS: 0.20435011192955327
Fold 4 IBS: 0.22452358241033177
Fold 5 IBS: 0.21790422202929924
[I 2024-04-16 01:18:29,720] Trial 53 finished with value: 0.21638510630761446 and parameters: {'l1_ratio': 0.001478284820913868}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19225157323235292
Fold 2 IBS: 0.15142427124198615
Fold 3 IBS: 0.1651119917282591
Fold 4 IBS: 0.14117206051901196
Fold 5 IBS: 0.15691351165558332
[I 2024-04-16 01:18:33,782] Trial 54 finished with value: 0.1613746816754387 and parameters: {'l1_ratio': 0.17864914109214336}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19213500161689037
Fold 2 IBS: 0.15158836277257662
Fold 3 IBS: 0.16490901681010633
Fold 4 IBS: 0.1412591856873787
Fold 5 IBS: 0.15678127092635463
[I 2024-04-16 01:18:37,380] Trial 55 finished with value: 0.16133456756266135 and parameters: {'l1_ratio': 0.0383562404166812}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19244829997183488
Fold 2 IBS: 0.15099095298488135
Fold 3 IBS: 0.165149244085354
Fold 4 IBS: 0.1409493798531442
Fold 5 IBS: 0.15715867328319466
[I 2024-04-16 01:18:39,628] Trial 56 finished with value: 0.16133931003568183 and parameters: {'l1_ratio': 0.7636926705520951}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.19224619093618622
Fold 2 IBS: 0.15137338181847734
Fold 3 IBS: 0.16511662734908703
Fold 4 IBS: 0.14111075511925106
Fold 5 IBS: 0.15695097852022455
[I 2024-04-16 01:18:41,990] Trial 57 finished with value: 0.16135958674864526 and parameters: {'l1_ratio': 0.22485807552868214}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.1921966238035215
Fold 2 IBS: 0.15147638322669657
Fold 3 IBS: 0.16499846904003865
Fold 4 IBS: 0.1411933612864592
Fold 5 IBS: 0.1568004639622032
[I 2024-04-16 01:18:44,747] Trial 58 finished with value: 0.16133306026378383 and parameters: {'l1_ratio': 0.1193457737120769}. Best is trial 31 with value: 0.16131222622905456.
Fold 1 IBS: 0.1921117876570035
Fold 2 IBS: 0.15152510112153741
Fold 3 IBS: 0.1649286065844415
Fold 4 IBS: 0.14121864566922587
Fold 5 IBS: 0.15676161918639137
[I 2024-04-16 01:18:46,842] Trial 59 finished with value: 0.16130915204371993 and parameters: {'l1_ratio': 0.07874268754859727}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19242440101174724
Fold 2 IBS: 0.15103218444073616
Fold 3 IBS: 0.1651622185274375
Fold 4 IBS: 0.14096953745993185
Fold 5 IBS: 0.15713781702195392
[I 2024-04-16 01:18:48,971] Trial 60 finished with value: 0.1613452316923613 and parameters: {'l1_ratio': 0.6097637962339882}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19216252322238778
Fold 2 IBS: 0.15155216618473802
Fold 3 IBS: 0.1649052018037764
Fold 4 IBS: 0.14123783015116692
Fold 5 IBS: 0.15680929684464165
[I 2024-04-16 01:18:51,762] Trial 61 finished with value: 0.16133340364134213 and parameters: {'l1_ratio': 0.07525306002467237}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.1921496999856556
Fold 2 IBS: 0.15157387414571089
Fold 3 IBS: 0.16490462069396786
Fold 4 IBS: 0.14124709671695362
Fold 5 IBS: 0.15679854106145485
[I 2024-04-16 01:18:54,933] Trial 62 finished with value: 0.16133476652074855 and parameters: {'l1_ratio': 0.04296758954778088}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19221813713094751
Fold 2 IBS: 0.1514930795989901
Fold 3 IBS: 0.1650382589553533
Fold 4 IBS: 0.14117360110985436
Fold 5 IBS: 0.15692507133744613
[I 2024-04-16 01:18:58,899] Trial 63 finished with value: 0.1613696296265183 and parameters: {'l1_ratio': 0.13639118762334662}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19215638698712298
Fold 2 IBS: 0.15154603294861294
Fold 3 IBS: 0.16496172747418988
Fold 4 IBS: 0.14123690589516721
Fold 5 IBS: 0.15681244296757046
[I 2024-04-16 01:19:02,055] Trial 64 finished with value: 0.1613426992545327 and parameters: {'l1_ratio': 0.08278816071752053}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19219985399184553
Fold 2 IBS: 0.1516194198800887
Fold 3 IBS: 0.164906091069006
Fold 4 IBS: 0.14128079827858372
Fold 5 IBS: 0.1567482511716754
[I 2024-04-16 01:19:05,662] Trial 65 finished with value: 0.16135088287823987 and parameters: {'l1_ratio': 0.03043307130621105}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19222821929829387
Fold 2 IBS: 0.15146462953110046
Fold 3 IBS: 0.16507556735601536
Fold 4 IBS: 0.14115764251753624
Fold 5 IBS: 0.1568657557495244
[I 2024-04-16 01:19:08,371] Trial 66 finished with value: 0.16135836289049407 and parameters: {'l1_ratio': 0.1545566297048672}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19214216479037205
Fold 2 IBS: 0.15153051287313704
Fold 3 IBS: 0.16499155129536103
Fold 4 IBS: 0.14123454215413384
Fold 5 IBS: 0.15681734902748493
[I 2024-04-16 01:19:11,527] Trial 67 finished with value: 0.16134322402809778 and parameters: {'l1_ratio': 0.10048256442389696}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.192242648243028
Fold 2 IBS: 0.1514059961199197
Fold 3 IBS: 0.16511137747441415
Fold 4 IBS: 0.14112716239408316
Fold 5 IBS: 0.15692219061679938
[I 2024-04-16 01:19:13,946] Trial 68 finished with value: 0.16136187496964888 and parameters: {'l1_ratio': 0.1983514789734288}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19211316100904888
Fold 2 IBS: 0.15154277967837837
Fold 3 IBS: 0.16490564206526234
Fold 4 IBS: 0.1412262828314493
Fold 5 IBS: 0.1568292854721073
[I 2024-04-16 01:19:16,782] Trial 69 finished with value: 0.16132343021124923 and parameters: {'l1_ratio': 0.06434746919680041}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19216148438852312
Fold 2 IBS: 0.15160033301906142
Fold 3 IBS: 0.16493793601711915
Fold 4 IBS: 0.14125818786671487
Fold 5 IBS: 0.1566894327260199
[I 2024-04-16 01:19:19,747] Trial 70 finished with value: 0.1613294748034877 and parameters: {'l1_ratio': 0.02190338387516585}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19214531653605688
Fold 2 IBS: 0.15157327211041466
Fold 3 IBS: 0.16492791565371176
Fold 4 IBS: 0.1412581385801223
Fold 5 IBS: 0.15678170121224957
[I 2024-04-16 01:19:22,228] Trial 71 finished with value: 0.16133726881851101 and parameters: {'l1_ratio': 0.06667183533465723}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.1922082482599834
Fold 2 IBS: 0.15145350607596822
Fold 3 IBS: 0.16502998102533895
Fold 4 IBS: 0.14117929137116908
Fold 5 IBS: 0.15691374795578153
[I 2024-04-16 01:19:26,106] Trial 72 finished with value: 0.16135695493764823 and parameters: {'l1_ratio': 0.13470489505897437}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19215948355547907
Fold 2 IBS: 0.15157247589194753
Fold 3 IBS: 0.16492671286174473
Fold 4 IBS: 0.14125501280835973
Fold 5 IBS: 0.15679038507566623
[I 2024-04-16 01:19:29,827] Trial 73 finished with value: 0.16134081403863948 and parameters: {'l1_ratio': 0.06121646422038702}. Best is trial 59 with value: 0.16130915204371993.

Fold 1 IBS: 0.2137111823714941
Fold 2 IBS: 0.22105846696137302
Fold 3 IBS: 0.20417767609022433
Fold 4 IBS: 0.2243242021195586
Fold 5 IBS: 0.21769990553154817
[I 2024-04-16 01:19:30,758] Trial 74 finished with value: 0.21619428661483964 and parameters: {'l1_ratio': 0.002862886448580952}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.1921422768242721
Fold 2 IBS: 0.15153043397306656
Fold 3 IBS: 0.16499163725478483
Fold 4 IBS: 0.14123447588555174
Fold 5 IBS: 0.15681748493234385
[I 2024-04-16 01:19:33,633] Trial 75 finished with value: 0.1613432617740038 and parameters: {'l1_ratio': 0.10049559697143443}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19220519503408265
Fold 2 IBS: 0.1513921270806002
Fold 3 IBS: 0.1651076780140971
Fold 4 IBS: 0.14114448362721096
Fold 5 IBS: 0.1569643027170594
[I 2024-04-16 01:19:36,018] Trial 76 finished with value: 0.16136275729461008 and parameters: {'l1_ratio': 0.18858975508554424}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19228251578277344
Fold 2 IBS: 0.15130920430488584
Fold 3 IBS: 0.16512410290598709
Fold 4 IBS: 0.14110992105017844
Fold 5 IBS: 0.15693626579867556
[I 2024-04-16 01:19:38,108] Trial 77 finished with value: 0.1613524019685001 and parameters: {'l1_ratio': 0.26796955203151296}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19256813956630756
Fold 2 IBS: 0.1509573753851728
Fold 3 IBS: 0.1650891218145921
Fold 4 IBS: 0.14090939852856826
Fold 5 IBS: 0.15724784377483444
[I 2024-04-16 01:19:40,313] Trial 78 finished with value: 0.16135437581389506 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19218260832232195
Fold 2 IBS: 0.15145349771637265
Fold 3 IBS: 0.16503684232526514
Fold 4 IBS: 0.14118375478624043
Fold 5 IBS: 0.1569011021617317
[I 2024-04-16 01:19:42,626] Trial 79 finished with value: 0.16135156106238638 and parameters: {'l1_ratio': 0.14584848743104653}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19217141771421817
Fold 2 IBS: 0.151560345208938
Fold 3 IBS: 0.1649126585539825
Fold 4 IBS: 0.1412334440171884
Fold 5 IBS: 0.15674136914793874
[I 2024-04-16 01:19:45,373] Trial 80 finished with value: 0.16132384692845317 and parameters: {'l1_ratio': 0.043967738422172956}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19212653087924406
Fold 2 IBS: 0.15155703380843816
Fold 3 IBS: 0.16490476796048034
Fold 4 IBS: 0.14123593274555568
Fold 5 IBS: 0.15674182555695973
[I 2024-04-16 01:19:48,373] Trial 81 finished with value: 0.1613132181901356 and parameters: {'l1_ratio': 0.04830686453512056}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19217600330507867
Fold 2 IBS: 0.15154290333964995
Fold 3 IBS: 0.1649091059529604
Fold 4 IBS: 0.14123138728369164
Fold 5 IBS: 0.15681408326582108
[I 2024-04-16 01:19:51,583] Trial 82 finished with value: 0.16133469662944036 and parameters: {'l1_ratio': 0.07642474012940229}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19214856482501755
Fold 2 IBS: 0.1516301419687594
Fold 3 IBS: 0.16491430714752195
Fold 4 IBS: 0.14128595613164785
Fold 5 IBS: 0.1567409444590543
[I 2024-04-16 01:19:55,608] Trial 83 finished with value: 0.16134398290640023 and parameters: {'l1_ratio': 0.022806128434730594}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19214437989694164
Fold 2 IBS: 0.15151411231736425
Fold 3 IBS: 0.16500754765013917
Fold 4 IBS: 0.14122475871278323
Fold 5 IBS: 0.15683260810288982
[I 2024-04-16 01:19:59,402] Trial 84 finished with value: 0.1613446813360236 and parameters: {'l1_ratio': 0.11211746570704698}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19211815602355492
Fold 2 IBS: 0.1515552951454326
Fold 3 IBS: 0.16489468257150547
Fold 4 IBS: 0.141236252071588
Fold 5 IBS: 0.15682031533808846
[I 2024-04-16 01:20:02,857] Trial 85 finished with value: 0.1613249402300339 and parameters: {'l1_ratio': 0.052908173988322156}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19215149839095072
Fold 2 IBS: 0.1515494023334882
Fold 3 IBS: 0.16495805728629018
Fold 4 IBS: 0.14123846541146998
Fold 5 IBS: 0.156806574144148
[I 2024-04-16 01:20:06,244] Trial 86 finished with value: 0.16134079951326943 and parameters: {'l1_ratio': 0.08232739183070871}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19226204863247368
Fold 2 IBS: 0.15136038497720136
Fold 3 IBS: 0.16511978099937638
Fold 4 IBS: 0.14113744092481906
Fold 5 IBS: 0.15696889876827935
[I 2024-04-16 01:20:09,774] Trial 87 finished with value: 0.16136971086042998 and parameters: {'l1_ratio': 0.22997380642380671}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19223044586555182
Fold 2 IBS: 0.15146291215823418
Fold 3 IBS: 0.1650774164339978
Fold 4 IBS: 0.141156413873729
Fold 5 IBS: 0.1568706141792813
[I 2024-04-16 01:20:14,414] Trial 88 finished with value: 0.1613595605021588 and parameters: {'l1_ratio': 0.1549880409558666}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.1921000852491877
Fold 2 IBS: 0.15163711774779717
Fold 3 IBS: 0.16491461051808431
Fold 4 IBS: 0.1412944589877659
Fold 5 IBS: 0.15662199623280434
[I 2024-04-16 01:20:17,348] Trial 89 finished with value: 0.1613136537471279 and parameters: {'l1_ratio': 0.02058320288097457}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.1921585968079796
Fold 2 IBS: 0.15160536213833012
Fold 3 IBS: 0.16493961696718062
Fold 4 IBS: 0.14126180052718101
Fold 5 IBS: 0.1565928580599198
[I 2024-04-16 01:20:21,165] Trial 90 finished with value: 0.16131164690011826 and parameters: {'l1_ratio': 0.019829233422526717}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19209024421280455
Fold 2 IBS: 0.1516225330796692
Fold 3 IBS: 0.16493546219888028
Fold 4 IBS: 0.2225049142612669
Fold 5 IBS: 0.15635195613813255
[I 2024-04-16 01:20:24,878] Trial 91 finished with value: 0.1775010219781507 and parameters: {'l1_ratio': 0.01604620077732044}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19210665080886866
Fold 2 IBS: 0.15162318225140212
Fold 3 IBS: 0.16490759032434896
Fold 4 IBS: 0.14128287195115216
Fold 5 IBS: 0.15674511304130948
[I 2024-04-16 01:20:28,419] Trial 92 finished with value: 0.16133308167541627 and parameters: {'l1_ratio': 0.027634200482867455}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.1921989720779366
Fold 2 IBS: 0.15147466410897112
Fold 3 IBS: 0.16500038652862245
Fold 4 IBS: 0.14119200383837857
Fold 5 IBS: 0.15680349787543313
[I 2024-04-16 01:20:32,267] Trial 93 finished with value: 0.16133390488586838 and parameters: {'l1_ratio': 0.1196893645369305}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19211377833684087
Fold 2 IBS: 0.15151170139981554
Fold 3 IBS: 0.16494761726520005
Fold 4 IBS: 0.1412123577846055
Fold 5 IBS: 0.1567754526214023
[I 2024-04-16 01:20:34,867] Trial 94 finished with value: 0.16131218148157286 and parameters: {'l1_ratio': 0.08767713544765886}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19218536321383314
Fold 2 IBS: 0.15151281254199755
Fold 3 IBS: 0.16495568205988928
Fold 4 IBS: 0.1412164368648943
Fold 5 IBS: 0.15676204870441626
[I 2024-04-16 01:20:37,985] Trial 95 finished with value: 0.16132646867700612 and parameters: {'l1_ratio': 0.09519065616380568}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.21358738108455844
Fold 2 IBS: 0.22081575859859956
Fold 3 IBS: 0.20401066598748652
Fold 4 IBS: 0.22413074053667414
Fold 5 IBS: 0.21750193271264007
[I 2024-04-16 01:20:39,023] Trial 96 finished with value: 0.21600929578399172 and parameters: {'l1_ratio': 0.004215965915298901}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.1922070755800846
Fold 2 IBS: 0.15160616055991552
Fold 3 IBS: 0.16489986749610686
Fold 4 IBS: 0.14127515027177912
Fold 5 IBS: 0.15676300449303301
[I 2024-04-16 01:20:41,884] Trial 97 finished with value: 0.16135025168018383 and parameters: {'l1_ratio': 0.037249244590165806}. Best is trial 59 with value: 0.16130915204371993.
Fold 1 IBS: 0.19210715358380204
Fold 2 IBS: 0.1515281439762232
Fold 3 IBS: 0.1649268369589779
Fold 4 IBS: 0.14122116783232866

Fold 5 IBS: 0.15675610636337534
[I 2024-04-16 01:20:44,785] Trial 98 finished with value: 0.16130788174294142 and parameters: {'l1_ratio': 0.07833994485626661}. Best is trial 98 with value: 0.16130788174294142.
Fold 1 IBS: 0.1921899313200978
Fold 2 IBS: 0.15142680765304933
Fold 3 IBS: 0.1650794369327764
Fold 4 IBS: 0.14116786452124977
Fold 5 IBS: 0.15692753735916443
[I 2024-04-16 01:20:48,375] Trial 99 finished with value: 0.16135831555726754 and parameters: {'l1_ratio': 0.16479853152459903}. Best is trial 98 with value: 0.16130788174294142.


* Best trial for IBS:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.16130788174294142], datetime_start=datetime.datetime(2024, 4, 16, 1, 20, 41, 938570), datetime_complete=datetime.datetime(2024, 4, 16, 1, 20, 44, 784242), params={'l1_ratio': 0.07833994485626661}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=98, value=None)


* Best Score for IBS:
 0.16130788174294142

In [48]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.737
train_ibs:  0.161

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.558

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.07833994485626661)

test_ibs:  0.251

In [52]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:20:50,539] A new study created in memory with name: no-name-e98a47c0-a5ae-48bd-803c-f104343ea609

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:21:19,744] Trial 0 finished with value: 0.7461931710641112 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7461931710641112.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:21:37,302] Trial 1 finished with value: 0.7465463551747543 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7465463551747543.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:21:46,784] Trial 2 finished with value: 0.7422455937593112 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7465463551747543.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:21:50,505] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7465463551747543.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:21:55,602] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7465463551747543.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:22:16,618] Trial 5 finished with value: 0.7417663949240696 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.7465463551747543.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:22:34,797] Trial 6 finished with value: 0.7496512749980785 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 6 with value: 0.7496512749980785.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:22:42,978] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 6 with value: 0.7496512749980785.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 01:23:14,829] Trial 8 finished with value: 0.536150234741784 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 6 with value: 0.7496512749980785.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:23:38,100] Trial 9 finished with value: 0.7418021920757152 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 6 with value: 0.7496512749980785.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:23:39,507] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.40740851493126695, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 6 with value: 0.7496512749980785.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:23:48,153] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.11379276107227315, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 6 with value: 0.7496512749980785.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:23:58,509] Trial 12 finished with value: 0.7385171032626409 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.8206827027986038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 6 with value: 0.7496512749980785.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:24:18,938] Trial 13 finished with value: 0.7517077379096666 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.47497684741348173, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08474327360564854, 'warm_start': False}. Best is trial 13 with value: 0.7517077379096666.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:24:32,659] Trial 14 finished with value: 0.7739454410753426 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.47180184759431143, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0017902999721138846, 'warm_start': True}. Best is trial 14 with value: 0.7739454410753426.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:24:45,037] Trial 15 finished with value: 0.738698439310245 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.4747428535255964, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18655401147456613, 'warm_start': True}. Best is trial 14 with value: 0.7739454410753426.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:25:03,484] Trial 16 finished with value: 0.8189405998708015 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.824967518839032e-05, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:25:19,229] Trial 17 finished with value: 0.769584384224524 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.27271989967973836, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.013083767191886917, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:25:30,989] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.140467432205667, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:25:37,120] Trial 19 finished with value: 0.7376689308440276 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 419, 'oob_score': True, 'max_samples': 0.3750652437663408, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0024062964567727195, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:25:42,522] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.19341861559626783, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15603167163739984, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:25:51,152] Trial 21 finished with value: 0.7799230203191667 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.29423136040281306, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0587391455650732, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:25:59,966] Trial 22 finished with value: 0.8090397824229612 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.3461240398691545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042569668399179195, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:26:07,451] Trial 23 finished with value: 0.7954876452923184 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.3446124441244735, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06813381294417811, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:26:15,323] Trial 24 finished with value: 0.7991328334523489 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 450, 'oob_score': True, 'max_samples': 0.3651218180548735, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08081043348590129, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:26:25,126] Trial 25 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 450, 'oob_score': True, 'max_samples': 0.20193659652158727, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14180719472168826, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:26:33,234] Trial 26 finished with value: 0.815896299807464 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:26:38,653] Trial 27 finished with value: 0.8182310973628498 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.5366581083873809, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.045046685005436606, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:26:44,950] Trial 28 finished with value: 0.7493269134993177 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 334, 'oob_score': True, 'max_samples': 0.5415638318724526, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20025138718191268, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:26:52,483] Trial 29 finished with value: 0.7600306556843714 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.6893967692965806, 'max_features': None, 'min_weight_fraction_leaf': 0.23669752924582235, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:26:55,992] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.5678569702896432, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4101391151116046, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:27:02,733] Trial 31 finished with value: 0.8138432955071524 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.4110140220080125, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05516005867190663, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:27:09,756] Trial 32 finished with value: 0.7972854563469174 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.5288432021501348, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10831077212471385, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:27:16,601] Trial 33 finished with value: 0.8004431636185487 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.4148087530809058, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03666381384775158, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 01:27:23,938] Trial 34 finished with value: 0.7964923694562511 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.6662867850609673, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1330136977511121, 'warm_start': True}. Best is trial 16 with value: 0.8189405998708015.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:27:28,961] Trial 35 finished with value: 0.8217535506479614 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.7918229652627642, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08933486050277042, 'warm_start': True}. Best is trial 35 with value: 0.8217535506479614.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 01:27:32,496] Trial 36 finished with value: 0.8127511773522518 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.758173546793086, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0895873469659392, 'warm_start': True}. Best is trial 35 with value: 0.8217535506479614.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:27:36,226] Trial 37 finished with value: 0.7656797318353589 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.8106458896033096, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17602530673018993, 'warm_start': True}. Best is trial 35 with value: 0.8217535506479614.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:27:38,735] Trial 38 finished with value: 0.8018909373341065 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.9772941339313385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.033535853309688335, 'warm_start': True}. Best is trial 35 with value: 0.8217535506479614.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 01:27:41,377] Trial 39 finished with value: 0.802639140592784 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6220569630425845, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0788956189885762, 'warm_start': True}. Best is trial 35 with value: 0.8217535506479614.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:27:43,717] Trial 40 finished with value: 0.775541228541855 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 10, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.8420978362663503, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1345248113073543, 'warm_start': True}. Best is trial 35 with value: 0.8217535506479614.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:27:47,096] Trial 41 finished with value: 0.8237678541975472 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 464, 'oob_score': False, 'max_samples': 0.5142783170234119, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050129168038510384, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:27:52,079] Trial 42 finished with value: 0.8013098730472594 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.7250268016045542, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03202164241098193, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:27:56,135] Trial 43 finished with value: 0.8220483492348301 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.5143282301365409, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05765032292567238, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:27:59,870] Trial 44 finished with value: 0.8099322834613675 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.5844822060235745, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:28:04,024] Trial 45 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.4954607534061301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27768614719647955, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:28:13,724] Trial 46 finished with value: 0.7444634293043625 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.6285312552955167, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01697231104383085, 'warm_start': False}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:28:15,919] Trial 47 finished with value: 0.7815498530000827 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.5068348574187561, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0018692600074086347, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:28:27,445] Trial 48 finished with value: 0.7528279937074102 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.44020140617298, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06359640147582817, 'warm_start': False}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:28:30,234] Trial 49 finished with value: 0.7839589047178215 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.4471557871913627, 'max_features': None, 'min_weight_fraction_leaf': 0.12498882826515084, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:28:32,978] Trial 50 finished with value: 0.8182310973628498 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.6597097236895602, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0949941461487119, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7362869198312236
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:28:33,396] Trial 51 finished with value: 0.7639153195476476 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 1, 'oob_score': False, 'max_samples': 0.8817283240643521, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08958820607465828, 'warm_start': True}. Best is trial 41 with value: 0.8237678541975472.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 01:28:36,911] Trial 52 finished with value: 0.8331894396115633 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.7580452055190642, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024826694650770767, 'warm_start': True}. Best is trial 52 with value: 0.8331894396115633.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:28:40,430] Trial 53 finished with value: 0.8264775735575028 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.734311460459071, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015921363449271062, 'warm_start': True}. Best is trial 52 with value: 0.8331894396115633.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:28:43,678] Trial 54 finished with value: 0.8229631228332108 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.7686930388094032, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02013879938538209, 'warm_start': True}. Best is trial 52 with value: 0.8331894396115633.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:28:47,050] Trial 55 finished with value: 0.8246752185533607 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.7741923343382487, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02036042520301709, 'warm_start': True}. Best is trial 52 with value: 0.8331894396115633.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:29:01,842] Trial 56 finished with value: 0.7357496651880415 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.7182532763821678, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01832940489191254, 'warm_start': False}. Best is trial 52 with value: 0.8331894396115633.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:29:05,597] Trial 57 finished with value: 0.835814350781237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.874447206664403, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019229213985163113, 'warm_start': True}. Best is trial 57 with value: 0.835814350781237.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:29:11,015] Trial 58 finished with value: 0.8383898343693789 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.8736535931067805, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020479577996876015, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:29:14,791] Trial 59 finished with value: 0.8340632430381835 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.8716789586334717, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.031567810909688146, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:29:33,014] Trial 60 finished with value: 0.7307474435502657 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.8782750086533567, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.032309892464827565, 'warm_start': False}. Best is trial 58 with value: 0.8383898343693789.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 01:29:37,075] Trial 61 finished with value: 0.824096666008824 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.9503001956341246, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06984707699664106, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:29:41,506] Trial 62 finished with value: 0.8269088824446941 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.9395849509830608, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07160269258272596, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:29:45,296] Trial 63 finished with value: 0.8359630963197449 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.901612817556836, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012980756397805646, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:29:48,596] Trial 64 finished with value: 0.8351629114586888 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.9153113442581998, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005234279007793819, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:29:52,012] Trial 65 finished with value: 0.8360067933152289 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.9229557089713647, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002790032231397725, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:29:54,145] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9036435424773241, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48319510296987256, 'warm_start': True}. Best is trial 58 with value: 0.8383898343693789.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:29:59,028] Trial 67 finished with value: 0.8431661501534762 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.9866691037074751, 'max_features': None, 'min_weight_fraction_leaf': 0.0020124837617455996, 'warm_start': True}. Best is trial 67 with value: 0.8431661501534762.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:30:03,673] Trial 68 finished with value: 0.8414564674311352 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.998865246748535, 'max_features': None, 'min_weight_fraction_leaf': 0.0020823730284138357, 'warm_start': True}. Best is trial 67 with value: 0.8431661501534762.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:30:08,297] Trial 69 finished with value: 0.8422732930106192 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.9991887787607374, 'max_features': None, 'min_weight_fraction_leaf': 0.01084225451713395, 'warm_start': True}. Best is trial 67 with value: 0.8431661501534762.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:30:10,677] Trial 70 finished with value: 0.7636463957088047 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.9921529311944431, 'max_features': None, 'min_weight_fraction_leaf': 0.327019809881093, 'warm_start': True}. Best is trial 67 with value: 0.8431661501534762.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:30:14,509] Trial 71 finished with value: 0.8422784302784144 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.9654478015481393, 'max_features': None, 'min_weight_fraction_leaf': 0.006783941330178658, 'warm_start': True}. Best is trial 67 with value: 0.8431661501534762.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:30:18,594] Trial 72 finished with value: 0.8431442311442154 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 347, 'oob_score': False, 'max_samples': 0.9659677348656222, 'max_features': None, 'min_weight_fraction_leaf': 0.002128464605333111, 'warm_start': True}. Best is trial 67 with value: 0.8431661501534762.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:30:23,129] Trial 73 finished with value: 0.8422732930106192 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.9999686301139179, 'max_features': None, 'min_weight_fraction_leaf': 0.003032901241841112, 'warm_start': True}. Best is trial 67 with value: 0.8431661501534762.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:30:27,193] Trial 74 finished with value: 0.8443342998717501 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.9611562635758797, 'max_features': None, 'min_weight_fraction_leaf': 0.041195537758667834, 'warm_start': True}. Best is trial 74 with value: 0.8443342998717501.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:30:31,452] Trial 75 finished with value: 0.8469829497302414 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.9646728732070395, 'max_features': None, 'min_weight_fraction_leaf': 0.044222759114396916, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:30:35,798] Trial 76 finished with value: 0.8406511453022837 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 282, 'oob_score': False, 'max_samples': 0.9634182510332394, 'max_features': None, 'min_weight_fraction_leaf': 0.04262603260847503, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:30:40,559] Trial 77 finished with value: 0.8443855471328388 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.99337371157519, 'max_features': None, 'min_weight_fraction_leaf': 0.041660194975133465, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:30:44,120] Trial 78 finished with value: 0.8380928957508221 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'max_samples': 0.9711193324598064, 'max_features': None, 'min_weight_fraction_leaf': 0.04535848008559733, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:30:47,914] Trial 79 finished with value: 0.8362145091833065 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.9492075417934671, 'max_features': None, 'min_weight_fraction_leaf': 0.06312686428227712, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:30:58,589] Trial 80 finished with value: 0.7018200214736375 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 189, 'oob_score': False, 'max_samples': 0.8425686452925019, 'max_features': None, 'min_weight_fraction_leaf': 0.041476897651073354, 'warm_start': False}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:31:04,476] Trial 81 finished with value: 0.8432536851674819 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.9970696739874594, 'max_features': None, 'min_weight_fraction_leaf': 0.007449641006604108, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 01:31:10,717] Trial 82 finished with value: 0.8441707332943713 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9848494265857582, 'max_features': None, 'min_weight_fraction_leaf': 0.03406698653889818, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:31:15,359] Trial 83 finished with value: 0.8449852868990835 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.9732949125731181, 'max_features': None, 'min_weight_fraction_leaf': 0.0504973943283496, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 01:31:18,518] Trial 84 finished with value: 0.838863159041798 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.96693831243622, 'max_features': None, 'min_weight_fraction_leaf': 0.0772082695065876, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:31:22,914] Trial 85 finished with value: 0.8352341170264438 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 263, 'oob_score': False, 'max_samples': 0.9455936971396334, 'max_features': None, 'min_weight_fraction_leaf': 0.054293051660220845, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:31:25,505] Trial 86 finished with value: 0.7547905105898824 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9293161198472755, 'max_features': None, 'min_weight_fraction_leaf': 0.3635551959165382, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:31:28,681] Trial 87 finished with value: 0.8233954773338695 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.973440991508887, 'max_features': None, 'min_weight_fraction_leaf': 0.11659499151251854, 'warm_start': True}. Best is trial 75 with value: 0.8469829497302414.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:31:33,320] Trial 88 finished with value: 0.8470487067580237 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.8993211339337946, 'max_features': None, 'min_weight_fraction_leaf': 0.03137183941190353, 'warm_start': True}. Best is trial 88 with value: 0.8470487067580237.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:31:38,294] Trial 89 finished with value: 0.8288194625570613 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.9024363105560147, 'max_features': None, 'min_weight_fraction_leaf': 0.0508475429697864, 'warm_start': True}. Best is trial 88 with value: 0.8470487067580237.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:31:41,520] Trial 90 finished with value: 0.8426707271427023 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 208, 'oob_score': False, 'max_samples': 0.9293613585153347, 'max_features': None, 'min_weight_fraction_leaf': 0.037123798505651215, 'warm_start': True}. Best is trial 88 with value: 0.8470487067580237.

Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:31:44,807] Trial 91 finished with value: 0.8398728794504885 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.8409820060796438, 'max_features': None, 'min_weight_fraction_leaf': 0.03196789895391483, 'warm_start': True}. Best is trial 88 with value: 0.8470487067580237.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 01:31:47,390] Trial 92 finished with value: 0.8422997176633664 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.9281447597291108, 'max_features': None, 'min_weight_fraction_leaf': 0.034166649713493695, 'warm_start': True}. Best is trial 88 with value: 0.8470487067580237.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:31:51,066] Trial 93 finished with value: 0.8380756617141418 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.9807619402483303, 'max_features': None, 'min_weight_fraction_leaf': 0.06184238023472316, 'warm_start': True}. Best is trial 88 with value: 0.8470487067580237.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 01:31:57,998] Trial 94 finished with value: 0.8471977635687089 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.9498376638190301, 'max_features': None, 'min_weight_fraction_leaf': 0.04195793549164225, 'warm_start': True}. Best is trial 94 with value: 0.8471977635687089.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 01:32:03,594] Trial 95 finished with value: 0.834694997020186 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.9570260059582477, 'max_features': None, 'min_weight_fraction_leaf': 0.08285835238987191, 'warm_start': True}. Best is trial 94 with value: 0.8471977635687089.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 01:32:13,992] Trial 96 finished with value: 0.8487364704711039 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9830923957685131, 'max_features': None, 'min_weight_fraction_leaf': 0.04949739725380848, 'warm_start': True}. Best is trial 96 with value: 0.8487364704711039.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 01:32:20,643] Trial 97 finished with value: 0.8252514925969091 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9822385964751251, 'max_features': None, 'min_weight_fraction_leaf': 0.10392418122932431, 'warm_start': True}. Best is trial 96 with value: 0.8487364704711039.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 01:32:28,297] Trial 98 finished with value: 0.8423044434957404 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.8920099187955854, 'max_features': None, 'min_weight_fraction_leaf': 0.07205336093098008, 'warm_start': True}. Best is trial 96 with value: 0.8487364704711039.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.679324894514768

[I 2024-04-16 01:32:49,951] A new study created in memory with name: no-name-3d92dc49-154b-42c3-81f9-202a4fffec6e

Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:32:49,879] Trial 99 finished with value: 0.7137809820519726 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.8517398710624715, 'max_features': None, 'min_weight_fraction_leaf': 0.049263005556322716, 'warm_start': False}. Best is trial 96 with value: 0.8487364704711039.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.8487364704711039], datetime_start=datetime.datetime(2024, 4, 16, 1, 32, 3, 687527), datetime_complete=datetime.datetime(2024, 4, 16, 1, 32, 13, 988570), params={'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9830923957685131, 'max_features': None, 'min_weight_fraction_leaf': 0.04949739725380848, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=96, value=None)


* Best Score for C-index:
 0.8487364704711039

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16593595706612332
Fold 2 IBS: 0.16444672938384863
Fold 3 IBS: 0.17944660597750692
Fold 4 IBS: 0.20974725875320108
Fold 5 IBS: 0.17402672603122674
[I 2024-04-16 01:33:08,640] Trial 0 finished with value: 0.17872065544238133 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.17872065544238133.
Fold 1 IBS: 0.17406985370787456
Fold 2 IBS: 0.17216853935940474
Fold 3 IBS: 0.17847170787502725
Fold 4 IBS: 0.19660697798263804
Fold 5 IBS: 0.17823475334176966
[I 2024-04-16 01:33:13,646] Trial 1 finished with value: 0.17991036645334285 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.17872065544238133.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-16 01:33:16,025] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.17872065544238133.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-16 01:33:28,006] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.17872065544238133.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-16 01:33:36,771] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.17872065544238133.
Fold 1 IBS: 0.18506725950727493
Fold 2 IBS: 0.16436734020805635
Fold 3 IBS: 0.19199471867475257
Fold 4 IBS: 0.17726179238644882
Fold 5 IBS: 0.15947482805559038
[I 2024-04-16 01:33:52,023] Trial 5 finished with value: 0.17563318776642461 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.17563318776642461.
Fold 1 IBS: 0.1800207765131884
Fold 2 IBS: 0.17323253910533404
Fold 3 IBS: 0.17939544412653965
Fold 4 IBS: 0.21731424380639183
Fold 5 IBS: 0.19054658280189857
[I 2024-04-16 01:34:04,686] Trial 6 finished with value: 0.18810191727067052 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.17563318776642461.
Fold 1 IBS: 0.20840302416208434
Fold 2 IBS: 0.21323060355829798
Fold 3 IBS: 0.19922066252361775
Fold 4 IBS: 0.21826115615869723
Fold 5 IBS: 0.21198650372915423
[I 2024-04-16 01:34:21,700] Trial 7 finished with value: 0.2102203900263703 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.17563318776642461.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-16 01:34:39,780] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.17563318776642461.
Fold 1 IBS: 0.18041391279214516
Fold 2 IBS: 0.17634652189076547
Fold 3 IBS: 0.18031410160234013
Fold 4 IBS: 0.19758172177863592
Fold 5 IBS: 0.18438358048041129
[I 2024-04-16 01:34:44,962] Trial 9 finished with value: 0.1838079677088596 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.17563318776642461.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-16 01:35:11,742] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.17563318776642461.
Fold 1 IBS: 0.17974867468101383
Fold 2 IBS: 0.16198082603560118
Fold 3 IBS: 0.18338543068484517
Fold 4 IBS: 0.17767574312819592
Fold 5 IBS: 0.16401531651502158
[I 2024-04-16 01:35:30,367] Trial 11 finished with value: 0.17336119820893553 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18128779257333932
Fold 2 IBS: 0.1643311302001333
Fold 3 IBS: 0.18798700074974117
Fold 4 IBS: 0.17737814516258701
Fold 5 IBS: 0.16288702488079682
[I 2024-04-16 01:35:44,507] Trial 12 finished with value: 0.17477421871331952 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.7702835685563957, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10911904675719894}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1826247163256264
Fold 2 IBS: 0.16427230407298787
Fold 3 IBS: 0.1876967139893472
Fold 4 IBS: 0.17963442589256928
Fold 5 IBS: 0.16199141724965882
[I 2024-04-16 01:36:00,990] Trial 13 finished with value: 0.1752439155060379 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.808080171371073, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12477571656275745}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17607185386577143
Fold 2 IBS: 0.17614851432148743
Fold 3 IBS: 0.17786573555039237
Fold 4 IBS: 0.19198852200652516
Fold 5 IBS: 0.17740408582123
[I 2024-04-16 01:36:10,087] Trial 14 finished with value: 0.17989574231308128 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 174, 'oob_score': False, 'max_samples': 0.9462130143995143, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2812321272168262}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1841180496727476
Fold 2 IBS: 0.16410287275143956
Fold 3 IBS: 0.19075179216257976
Fold 4 IBS: 0.17796454105002452
Fold 5 IBS: 0.16194900240236995
[I 2024-04-16 01:36:36,811] Trial 15 finished with value: 0.17577725160783228 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.9934437595017299, 'max_features': 'log2', 'min_weight_fraction_leaf': 2.899107782011745e-05}. Best is trial 11 with value: 0.17336119820893553.

Fold 1 IBS: 0.18130491452036293
Fold 2 IBS: 0.16284772973945366
Fold 3 IBS: 0.18505521318235307
Fold 4 IBS: 0.17772698651919488
Fold 5 IBS: 0.165151863823414
[I 2024-04-16 01:36:52,734] Trial 16 finished with value: 0.1744173415569557 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.7702473623171299, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12075256052520705}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17489870736358631
Fold 2 IBS: 0.16928727490766157
Fold 3 IBS: 0.18011186395420806
Fold 4 IBS: 0.1840623761517602
Fold 5 IBS: 0.17721814019932391
[I 2024-04-16 01:37:15,323] Trial 17 finished with value: 0.177115672515308 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.630638062800632, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16972242261821868}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.2139736842383025
Fold 2 IBS: 0.22107082253020785
Fold 3 IBS: 0.204991024601255
Fold 4 IBS: 0.22467918658765335
Fold 5 IBS: 0.21849788794571504
[I 2024-04-16 01:37:43,651] Trial 18 finished with value: 0.2166425211806268 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25385028637917034}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.19102752866320716
Fold 2 IBS: 0.17190180954577683
Fold 3 IBS: 0.19177230678743137
Fold 4 IBS: 0.18554172679814557
Fold 5 IBS: 0.15755279103529246
[I 2024-04-16 01:38:00,573] Trial 19 finished with value: 0.17955923256597067 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.8492616275036513, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05073999368638868}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17690683736532686
Fold 2 IBS: 0.16120163951221078
Fold 3 IBS: 0.1829339592432516
Fold 4 IBS: 0.18336379349347184
Fold 5 IBS: 0.16739994193779215
[I 2024-04-16 01:38:10,434] Trial 20 finished with value: 0.17436123431041067 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.749383512412799, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12996433494321102}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17335420229991735
Fold 2 IBS: 0.16171198874599865
Fold 3 IBS: 0.18335966728602798
Fold 4 IBS: 0.1857757882704546
Fold 5 IBS: 0.16643775273590494
[I 2024-04-16 01:38:19,071] Trial 21 finished with value: 0.1741278798676607 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.759909340018672, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14264286470921295}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17392867366915343
Fold 2 IBS: 0.16295734726863315
Fold 3 IBS: 0.1794812187188672
Fold 4 IBS: 0.18457392173959972
Fold 5 IBS: 0.17047648483818958
[I 2024-04-16 01:38:26,370] Trial 22 finished with value: 0.1742835292468886 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.7684823368486184, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1553526330909028}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17629004769239634
Fold 2 IBS: 0.164838958844734
Fold 3 IBS: 0.1803050958411834
Fold 4 IBS: 0.1884050685104693
Fold 5 IBS: 0.173688442620815
[I 2024-04-16 01:38:32,945] Trial 23 finished with value: 0.17670552270191958 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.8880006001237042, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20452409754060477}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18837819522513738
Fold 2 IBS: 0.16378358525951106
Fold 3 IBS: 0.1988382193756793
Fold 4 IBS: 0.22576817566301077
Fold 5 IBS: 0.19887979517268004
[I 2024-04-16 01:38:33,546] Trial 24 finished with value: 0.1951295941392037 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.6087519785625448, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1597178710276382}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18570189971255596
Fold 2 IBS: 0.18138766984809487
Fold 3 IBS: 0.17975225715207255
Fold 4 IBS: 0.199809336006346
Fold 5 IBS: 0.19001704820556203
[I 2024-04-16 01:38:37,827] Trial 25 finished with value: 0.18733364218492626 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.6988933058757706, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23484221138706707}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1735201942798994
Fold 2 IBS: 0.1608540457367032
Fold 3 IBS: 0.18029595407286905
Fold 4 IBS: 0.1850546558447323
Fold 5 IBS: 0.16941286193607247
[I 2024-04-16 01:38:46,096] Trial 26 finished with value: 0.17382754237405526 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.8295143131097767, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08115116339685219}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17309739500653726
Fold 2 IBS: 0.17345293435471376
Fold 3 IBS: 0.18068406694386988
Fold 4 IBS: 0.18693209623371032
Fold 5 IBS: 0.1751484707923027
[I 2024-04-16 01:38:57,455] Trial 27 finished with value: 0.1778629926662268 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 241, 'oob_score': True, 'max_samples': 0.9809265612849287, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031782053346907604}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18382720359923338
Fold 2 IBS: 0.16497328375854875
Fold 3 IBS: 0.1865643468229736
Fold 4 IBS: 0.1828261805509945
Fold 5 IBS: 0.1642801210468378
[I 2024-04-16 01:39:14,642] Trial 28 finished with value: 0.17649422715571764 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.8447554172655477, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07136907812459226}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1714952421692772
Fold 2 IBS: 0.1678431897763127
Fold 3 IBS: 0.1777714105703195
Fold 4 IBS: 0.19775617025666578
Fold 5 IBS: 0.17427298618948603
[I 2024-04-16 01:39:19,459] Trial 29 finished with value: 0.17782779979241226 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.6930070097212643, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.079630053057064}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17846640657916682
Fold 2 IBS: 0.15825988632867125
Fold 3 IBS: 0.19317848751019764
Fold 4 IBS: 0.18645464913759902
Fold 5 IBS: 0.16657368269479078
[I 2024-04-16 01:39:41,405] Trial 30 finished with value: 0.1765866224500851 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.48647997680034993, 'max_features': None, 'min_weight_fraction_leaf': 0.1048950209075476}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17474596614538332
Fold 2 IBS: 0.16495020348852027
Fold 3 IBS: 0.18202162986263887
Fold 4 IBS: 0.18802996482273537

Fold 5 IBS: 0.174421852678517
[I 2024-04-16 01:39:48,979] Trial 31 finished with value: 0.17683392339955897 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.7983356867961283, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1847177555601581}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17600208099339373
Fold 2 IBS: 0.17729776794042784
Fold 3 IBS: 0.17705951526759542
Fold 4 IBS: 0.19409996550095074
Fold 5 IBS: 0.17996400193707593
[I 2024-04-16 01:39:55,781] Trial 32 finished with value: 0.18088466632788874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 129, 'oob_score': True, 'max_samples': 0.7398519463537357, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14512201637701944}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18069568024347987
Fold 2 IBS: 0.1606144039968049
Fold 3 IBS: 0.18517248554032023
Fold 4 IBS: 0.17932660257820288
Fold 5 IBS: 0.1661112284603249
[I 2024-04-16 01:40:03,803] Trial 33 finished with value: 0.17438408016382656 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 184, 'oob_score': False, 'max_samples': 0.9175772077306465, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0976306402076579}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17331775358791374
Fold 2 IBS: 0.17221546401007679
Fold 3 IBS: 0.1766545989324939
Fold 4 IBS: 0.19802608172833935
Fold 5 IBS: 0.17600478237223088
[I 2024-04-16 01:40:07,793] Trial 34 finished with value: 0.17924373612621092 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 76, 'oob_score': True, 'max_samples': 0.6047943063740322, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15060806901050003}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1893760437669026
Fold 2 IBS: 0.16801687401999701
Fold 3 IBS: 0.19405863894711484
Fold 4 IBS: 0.17947312665237786
Fold 5 IBS: 0.15939450706051933
[I 2024-04-16 01:40:19,020] Trial 35 finished with value: 0.17806383808938234 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.8073221754315246, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04009637316350356}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18808280751276363
Fold 2 IBS: 0.18092685938835945
Fold 3 IBS: 0.1791655245503523
Fold 4 IBS: 0.1975802543671825
Fold 5 IBS: 0.18906681384248505
[I 2024-04-16 01:40:29,995] Trial 36 finished with value: 0.1869644519322286 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.7150609477406464, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24727866644687418}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1656530814040677
Fold 2 IBS: 0.16505568663625328
Fold 3 IBS: 0.17951301388202054
Fold 4 IBS: 0.2106659042908146
Fold 5 IBS: 0.17574517388150007
[I 2024-04-16 01:40:41,722] Trial 37 finished with value: 0.17932657201893126 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.6819654770799645, 'max_features': None, 'min_weight_fraction_leaf': 0.21576287816723366}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.21405979183456664
Fold 2 IBS: 0.22134616759026554
Fold 3 IBS: 0.20482546981011263
Fold 4 IBS: 0.22466277376011096
Fold 5 IBS: 0.21878786984825932
[I 2024-04-16 01:40:47,948] Trial 38 finished with value: 0.216736414568663 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.646030967727055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18728771255172824
Fold 2 IBS: 0.18272675860500207
Fold 3 IBS: 0.1789007706405906
Fold 4 IBS: 0.19725530063734897
Fold 5 IBS: 0.18901939684878816
[I 2024-04-16 01:41:04,014] Trial 39 finished with value: 0.1870379878566916 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.5357385409851093, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09155946855447043}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.19036650393997703
Fold 2 IBS: 0.15914938846866664
Fold 3 IBS: 0.2043837641034105
Fold 4 IBS: 0.19715618723482733
Fold 5 IBS: 0.17364960901309434
[I 2024-04-16 01:41:12,596] Trial 40 finished with value: 0.18494109055199517 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.8746134430162564, 'max_features': None, 'min_weight_fraction_leaf': 0.1736297545269136}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17865841327889165
Fold 2 IBS: 0.16410943000910827
Fold 3 IBS: 0.18260397367275952
Fold 4 IBS: 0.18161608424593476
Fold 5 IBS: 0.16677276003813052
[I 2024-04-16 01:41:24,755] Trial 41 finished with value: 0.17475213224896496 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 208, 'oob_score': False, 'max_samples': 0.7522621456418814, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13484836064950567}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1819241492690806
Fold 2 IBS: 0.16611217047399346
Fold 3 IBS: 0.1855489374503899
Fold 4 IBS: 0.1845363114616588
Fold 5 IBS: 0.1652553330589052
[I 2024-04-16 01:41:33,635] Trial 42 finished with value: 0.17667538034280558 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 155, 'oob_score': False, 'max_samples': 0.8101100121509739, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13075917314706695}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.21403441158048137
Fold 2 IBS: 0.2215292637789835
Fold 3 IBS: 0.20484598236206142
Fold 4 IBS: 0.22474258551896667
Fold 5 IBS: 0.21849704273149162
[I 2024-04-16 01:41:47,149] Trial 43 finished with value: 0.2167298571943969 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.7285770590652783, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18158864509337053
Fold 2 IBS: 0.1591356420863584
Fold 3 IBS: 0.17990917102328588
Fold 4 IBS: 0.18600152300230083
Fold 5 IBS: 0.1616333201760537
[I 2024-04-16 01:41:53,066] Trial 44 finished with value: 0.17365366027627388 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.5805927055810932, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0615898394950674}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18891228231488377
Fold 2 IBS: 0.18377224259493513
Fold 3 IBS: 0.1713854942355469
Fold 4 IBS: 0.18693298095106756
Fold 5 IBS: 0.1675214445403763
[I 2024-04-16 01:41:54,492] Trial 45 finished with value: 0.17970488892736194 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.47014562258191284, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05902292069648839}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1982705844879591
Fold 2 IBS: 0.19960224319279832
Fold 3 IBS: 0.19247749218088753
Fold 4 IBS: 0.2068527424228859
Fold 5 IBS: 0.1991901404116177
[I 2024-04-16 01:42:04,579] Trial 46 finished with value: 0.19927864053922967 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.1873692143114088, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020993213835924618}. Best is trial 11 with value: 0.17336119820893553.

Fold 1 IBS: 0.17444209352625056
Fold 2 IBS: 0.16213459687962897
Fold 3 IBS: 0.18658029015341887
Fold 4 IBS: 0.19096052126724972
Fold 5 IBS: 0.160743603219205
[I 2024-04-16 01:42:08,122] Trial 47 finished with value: 0.1749722210091506 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.5836246358507913, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08838589682559546}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.21394896398369084
Fold 2 IBS: 0.22096284686613055
Fold 3 IBS: 0.20483718884499716
Fold 4 IBS: 0.2248454593696118
Fold 5 IBS: 0.21856174512063364
[I 2024-04-16 01:42:13,582] Trial 48 finished with value: 0.2166312408370128 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.3075018204661719, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17515747861829142
Fold 2 IBS: 0.16178738886746258
Fold 3 IBS: 0.1842277714209381
Fold 4 IBS: 0.1821463990322942
Fold 5 IBS: 0.16723547678659123
[I 2024-04-16 01:42:54,852] Trial 49 finished with value: 0.17411090294511553 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 473, 'oob_score': True, 'max_samples': 0.9299250381576527, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19097954246344295}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18853355544023864
Fold 2 IBS: 0.16098026550734698
Fold 3 IBS: 0.20569185766486345
Fold 4 IBS: 0.19198971091170636
Fold 5 IBS: 0.17211310182077905
[I 2024-04-16 01:43:54,483] Trial 50 finished with value: 0.1838616982689869 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.929787353906635, 'max_features': None, 'min_weight_fraction_leaf': 0.19124416650471548}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1860970951531588
Fold 2 IBS: 0.167426461634716
Fold 3 IBS: 0.1930860203221253
Fold 4 IBS: 0.1808009036033356
Fold 5 IBS: 0.15891213065133442
[I 2024-04-16 01:44:42,611] Trial 51 finished with value: 0.17726452227293402 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 433, 'oob_score': True, 'max_samples': 0.9591259851218886, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10943364059061653}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1769098158778613
Fold 2 IBS: 0.15965855872788445
Fold 3 IBS: 0.18439739485017279
Fold 4 IBS: 0.17993980386576963
Fold 5 IBS: 0.1659262667850953
[I 2024-04-16 01:45:13,920] Trial 52 finished with value: 0.17336636802135671 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 468, 'oob_score': True, 'max_samples': 0.8521356447670636, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1637513639159529}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17531315767907252
Fold 2 IBS: 0.16062064718460095
Fold 3 IBS: 0.18422107433318252
Fold 4 IBS: 0.18156757069050355
Fold 5 IBS: 0.16650854016427807
[I 2024-04-16 01:45:41,118] Trial 53 finished with value: 0.17364619801032752 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 467, 'oob_score': True, 'max_samples': 0.8369099289055242, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16917310347078668}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17759072009576998
Fold 2 IBS: 0.17713463952675956
Fold 3 IBS: 0.17772291487556657
Fold 4 IBS: 0.19075707855492197
Fold 5 IBS: 0.17919913264649093
[I 2024-04-16 01:46:08,605] Trial 54 finished with value: 0.18048089713990179 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.8908237434352259, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27406150492166537}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17429588925632356
Fold 2 IBS: 0.1616703470724681
Fold 3 IBS: 0.18386944919222517
Fold 4 IBS: 0.182137051229041
Fold 5 IBS: 0.16716018682509018
[I 2024-04-16 01:46:39,477] Trial 55 finished with value: 0.1738265847150296 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.8398096597511415, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17573756955285064}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.19371170248139086
Fold 2 IBS: 0.1714268073948903
Fold 3 IBS: 0.19679800133886302
Fold 4 IBS: 0.18211596233405442
Fold 5 IBS: 0.15774608559238248
[I 2024-04-16 01:47:09,427] Trial 56 finished with value: 0.18035971182831623 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.8478181830608817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05447926065700506}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1745464167860879
Fold 2 IBS: 0.1697368220306827
Fold 3 IBS: 0.18094290218478343
Fold 4 IBS: 0.1873368888823032
Fold 5 IBS: 0.17351247259102617
[I 2024-04-16 01:47:34,339] Trial 57 finished with value: 0.17721510049497669 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.8291002414804649, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17414333250507247
Fold 2 IBS: 0.1625401342050302
Fold 3 IBS: 0.18374294245071437
Fold 4 IBS: 0.18072882083806724
Fold 5 IBS: 0.16857166550534936
[I 2024-04-16 01:48:04,249] Trial 58 finished with value: 0.17394537910084673 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.7939007785450483, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1707699073948621}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18675313991960005
Fold 2 IBS: 0.16394331948752014
Fold 3 IBS: 0.19194419510565922
Fold 4 IBS: 0.1771366870785516
Fold 5 IBS: 0.16123105802465157
[I 2024-04-16 01:48:34,705] Trial 59 finished with value: 0.17620167992319652 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.8653685075836288, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11703773294285884}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.19764986608942323
Fold 2 IBS: 0.1606361100535177
Fold 3 IBS: 0.18574571149087102
Fold 4 IBS: 0.18211506898780183
Fold 5 IBS: 0.1756209028910076
[I 2024-04-16 01:48:48,369] Trial 60 finished with value: 0.1803535319025243 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.9026958911166222, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07228025744303784}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17440512656949678
Fold 2 IBS: 0.16332725694458797
Fold 3 IBS: 0.18264950790308812
Fold 4 IBS: 0.18073118018912343
Fold 5 IBS: 0.1692125208673153
[I 2024-04-16 01:49:06,209] Trial 61 finished with value: 0.17406511849472234 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.7800913669036267, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17439547726632637}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17493873399503998
Fold 2 IBS: 0.16771314564481213
Fold 3 IBS: 0.18105432052078455
Fold 4 IBS: 0.18570546271660257

Fold 5 IBS: 0.1716386754696866
[I 2024-04-16 01:49:23,658] Trial 62 finished with value: 0.17621006766938516 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 421, 'oob_score': True, 'max_samples': 0.8259912471429802, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2092308756694655}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17415213320463757
Fold 2 IBS: 0.1617279283932607
Fold 3 IBS: 0.18375007806639526
Fold 4 IBS: 0.18093667575423525
Fold 5 IBS: 0.16750194117016448
[I 2024-04-16 01:49:43,838] Trial 63 finished with value: 0.17361375131773865 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.7851415216753531, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16951944917135664}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18036142871724786
Fold 2 IBS: 0.16206396844925125
Fold 3 IBS: 0.18781212626686797
Fold 4 IBS: 0.17915001647895526
Fold 5 IBS: 0.1622409955821385
[I 2024-04-16 01:50:02,888] Trial 64 finished with value: 0.17432570709889217 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 480, 'oob_score': True, 'max_samples': 0.9576477724124899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15872882713251257}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17789284496429097
Fold 2 IBS: 0.16191500768578923
Fold 3 IBS: 0.18566896028722785
Fold 4 IBS: 0.17734356660374662
Fold 5 IBS: 0.16622613728972102
[I 2024-04-16 01:50:16,088] Trial 65 finished with value: 0.17380930336615513 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 366, 'oob_score': True, 'max_samples': 0.6488534440953598, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11476464950263754}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1870969672703536
Fold 2 IBS: 0.17958626688711093
Fold 3 IBS: 0.1795994856364485
Fold 4 IBS: 0.19684476634118167
Fold 5 IBS: 0.18863189105718806
[I 2024-04-16 01:50:26,810] Trial 66 finished with value: 0.18635187543845655 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.6607353276260642, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23134302975587284}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17409744948083475
Fold 2 IBS: 0.16596931453383384
Fold 3 IBS: 0.18304262321562387
Fold 4 IBS: 0.18259893728418486
Fold 5 IBS: 0.17356562479236787
[I 2024-04-16 01:50:40,995] Trial 67 finished with value: 0.17585478986136907 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.502074047372613, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11913961364978265}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1757248748820866
Fold 2 IBS: 0.16120618422606947
Fold 3 IBS: 0.18500081928141404
Fold 4 IBS: 0.18067412651571207
Fold 5 IBS: 0.16637404974331882
[I 2024-04-16 01:50:53,593] Trial 68 finished with value: 0.17379601092972022 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.7089654363336375, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13812933957523427}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1756748810942779
Fold 2 IBS: 0.16634140295135041
Fold 3 IBS: 0.18124144798330719
Fold 4 IBS: 0.1827097486963872
Fold 5 IBS: 0.1721780207786078
[I 2024-04-16 01:51:10,312] Trial 69 finished with value: 0.1756291003007861 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 439, 'oob_score': True, 'max_samples': 0.5697913148602067, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14168083862147451}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.18007155890275447
Fold 2 IBS: 0.16389603124786653
Fold 3 IBS: 0.18882435797010683
Fold 4 IBS: 0.17698677579833322
Fold 5 IBS: 0.16161089894899394
[I 2024-04-16 01:51:26,867] Trial 70 finished with value: 0.174277924573611 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.7107968536309395, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10090007884512593}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17662829103315958
Fold 2 IBS: 0.17512025620516244
Fold 3 IBS: 0.17926794349438485
Fold 4 IBS: 0.18689503788115872
Fold 5 IBS: 0.17945663018520872
[I 2024-04-16 01:51:42,981] Trial 71 finished with value: 0.17947363175981484 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 472, 'oob_score': True, 'max_samples': 0.6192804557634485, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18288199965565913}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.1752214203073353
Fold 2 IBS: 0.1658311563210981
Fold 3 IBS: 0.1820125329030602
Fold 4 IBS: 0.18256069208889036
Fold 5 IBS: 0.1709976220299376
[I 2024-04-16 01:52:00,025] Trial 72 finished with value: 0.1753246847300643 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.6748344395483544, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1558349813726731}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17528685382605905
Fold 2 IBS: 0.17152288128188978
Fold 3 IBS: 0.18084646101471433
Fold 4 IBS: 0.18555237954146425
Fold 5 IBS: 0.17558188399821179
[I 2024-04-16 01:52:16,639] Trial 73 finished with value: 0.1777580919324678 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 419, 'oob_score': True, 'max_samples': 0.7328161691537924, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19887565248334166}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17921535323916485
Fold 2 IBS: 0.16183575175988751
Fold 3 IBS: 0.18602036223070065
Fold 4 IBS: 0.17747261424373917
Fold 5 IBS: 0.16454145695047107
[I 2024-04-16 01:52:34,305] Trial 74 finished with value: 0.17381710768479264 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.7796502573764761, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1272813677745335}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17513310047575845
Fold 2 IBS: 0.16174891353365733
Fold 3 IBS: 0.18485013536425407
Fold 4 IBS: 0.1794003892069887
Fold 5 IBS: 0.16641641295961893
[I 2024-04-16 01:52:51,016] Trial 75 finished with value: 0.17350979030805552 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.6610621433779309, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13314589399462864}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.19454838128819144
Fold 2 IBS: 0.172596994474733
Fold 3 IBS: 0.19194390285697757
Fold 4 IBS: 0.17644623347173188
Fold 5 IBS: 0.15647445494393486
[I 2024-04-16 01:53:08,556] Trial 76 finished with value: 0.17840199340711374 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.6424079640733715, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04334169451229605}. Best is trial 11 with value: 0.17336119820893553.
Fold 1 IBS: 0.17296237805843961
Fold 2 IBS: 0.16420594150496526
Fold 3 IBS: 0.18214621442383438
Fold 4 IBS: 0.18244505660027668
Fold 5 IBS: 0.17108440286061696
[I 2024-04-16 01:53:21,110] Trial 77 finished with value: 0.17456879868962658 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.591316565305972, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14165354734877494}. Best is trial 11 with value: 0.17336119820893553.

Fold 1 IBS: 0.17324342127994388
Fold 2 IBS: 0.16145074542296425
Fold 3 IBS: 0.1833602919336159
Fold 4 IBS: 0.1795050214021496
Fold 5 IBS: 0.16745400415861386
[I 2024-04-16 01:53:35,377] Trial 78 finished with value: 0.17300269683945751 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.5519676952991933, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11560830509081324}. Best is trial 78 with value: 0.17300269683945751.
Fold 1 IBS: 0.18308493469262166
Fold 2 IBS: 0.17752781133054824
Fold 3 IBS: 0.17865493574690022
Fold 4 IBS: 0.1934599594730117
Fold 5 IBS: 0.1827420656656263
[I 2024-04-16 01:53:48,824] Trial 79 finished with value: 0.18309394138174165 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 402, 'oob_score': True, 'max_samples': 0.5136803098501763, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1642883023885139}. Best is trial 78 with value: 0.17300269683945751.
Fold 1 IBS: 0.17822390557699
Fold 2 IBS: 0.1629274166266681
Fold 3 IBS: 0.18746436356122798
Fold 4 IBS: 0.17664665377885141
Fold 5 IBS: 0.16332932320115745
[I 2024-04-16 01:54:04,819] Trial 80 finished with value: 0.17371833254897898 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 447, 'oob_score': True, 'max_samples': 0.5499501306636879, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08783654374276298}. Best is trial 78 with value: 0.17300269683945751.
Fold 1 IBS: 0.1797034633464289
Fold 2 IBS: 0.16265640799182163
Fold 3 IBS: 0.18339735307415594
Fold 4 IBS: 0.17374271357500615
Fold 5 IBS: 0.16314930008296671
[I 2024-04-16 01:54:19,128] Trial 81 finished with value: 0.17252984761407586 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.445270111861485, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06757159569733719}. Best is trial 81 with value: 0.17252984761407586.
Fold 1 IBS: 0.17570724046011846
Fold 2 IBS: 0.16390715047739868
Fold 3 IBS: 0.1826232141354789
Fold 4 IBS: 0.17768847863476225
Fold 5 IBS: 0.16697886647504812
[I 2024-04-16 01:54:35,695] Trial 82 finished with value: 0.17338099003656127 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.43747267054497224, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08656278189454192}. Best is trial 81 with value: 0.17252984761407586.
Fold 1 IBS: 0.17690667347391553
Fold 2 IBS: 0.1629925471489981
Fold 3 IBS: 0.18276952891028436
Fold 4 IBS: 0.17557038389120264
Fold 5 IBS: 0.16627872993710158
[I 2024-04-16 01:54:49,106] Trial 83 finished with value: 0.17290357267230044 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': True, 'max_samples': 0.40418270037290716, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06780655100775425}. Best is trial 81 with value: 0.17252984761407586.
Fold 1 IBS: 0.17721481147523496
Fold 2 IBS: 0.16236679953092079
Fold 3 IBS: 0.18259665613217885
Fold 4 IBS: 0.17502612567219689
Fold 5 IBS: 0.16452301222777777
[I 2024-04-16 01:55:02,842] Trial 84 finished with value: 0.17234548100766184 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.4032700521243227, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.009607090472791888}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17545832624969115
Fold 2 IBS: 0.16621650129869284
Fold 3 IBS: 0.1825768473053911
Fold 4 IBS: 0.17648425184613994
Fold 5 IBS: 0.167127570081318
[I 2024-04-16 01:55:14,490] Trial 85 finished with value: 0.1735726993562466 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.36688710141779635, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010939489854681766}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17648307148187467
Fold 2 IBS: 0.16394854277771526
Fold 3 IBS: 0.1830243434851835
Fold 4 IBS: 0.17665304411995827
Fold 5 IBS: 0.1660380788073987
[I 2024-04-16 01:55:28,939] Trial 86 finished with value: 0.17322941613442608 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 412, 'oob_score': True, 'max_samples': 0.390021403657243, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012886586000764939}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.1778551692923231
Fold 2 IBS: 0.16615147212122838
Fold 3 IBS: 0.1822014815180903
Fold 4 IBS: 0.17773159939240787
Fold 5 IBS: 0.16640177343118132
[I 2024-04-16 01:55:40,907] Trial 87 finished with value: 0.1740682991510462 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.44384501300234463, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030033625979607348}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17507750845157236
Fold 2 IBS: 0.166601235566493
Fold 3 IBS: 0.1814140736134392
Fold 4 IBS: 0.1768065158008608
Fold 5 IBS: 0.16677601961540256
[I 2024-04-16 01:55:52,008] Trial 88 finished with value: 0.1733350706095536 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.3713253093015969, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003443067028496033}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17641371335463976
Fold 2 IBS: 0.16666353189098668
Fold 3 IBS: 0.1795297441844377
Fold 4 IBS: 0.1765026292717228
Fold 5 IBS: 0.16669708111892617
[I 2024-04-16 01:56:04,781] Trial 89 finished with value: 0.1731613399641426 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 393, 'oob_score': True, 'max_samples': 0.3440607259141253, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.009749590804527027}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.1759437859598813
Fold 2 IBS: 0.16645269420486605
Fold 3 IBS: 0.1798978229415642
Fold 4 IBS: 0.1773737324117427
Fold 5 IBS: 0.16727219161786427
[I 2024-04-16 01:56:15,658] Trial 90 finished with value: 0.17338804542718372 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.34098417669970743, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006823524636589124}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17729239889532536
Fold 2 IBS: 0.16189827616903082
Fold 3 IBS: 0.18245662352217593
Fold 4 IBS: 0.1755933174298341
Fold 5 IBS: 0.16466783435401905
[I 2024-04-16 01:56:28,918] Trial 91 finished with value: 0.17238169007407705 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.40599887698440185, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018397574634742127}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17566448898033146
Fold 2 IBS: 0.1725091651214727
Fold 3 IBS: 0.1794070996866764
Fold 4 IBS: 0.18148653775726176
Fold 5 IBS: 0.17177136188793668
[I 2024-04-16 01:56:38,213] Trial 92 finished with value: 0.1761677306867358 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 393, 'oob_score': True, 'max_samples': 0.27809012693090446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.025054397633810514}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17653995731146221
Fold 2 IBS: 0.1653816837014894
Fold 3 IBS: 0.18330958963981986
Fold 4 IBS: 0.1788688200233299

Fold 5 IBS: 0.16853370354637134
[I 2024-04-16 01:56:47,663] Trial 93 finished with value: 0.17452675084449457 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.39259915650398747, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0007655640662008745}. Best is trial 84 with value: 0.17234548100766184.
Fold 1 IBS: 0.17728796339095554
Fold 2 IBS: 0.1618275633358139
Fold 3 IBS: 0.18252336449392226
Fold 4 IBS: 0.17492094283521942
Fold 5 IBS: 0.1646569791557643
[I 2024-04-16 01:56:56,831] Trial 94 finished with value: 0.17224336264233508 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.401310433648782, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017290020666363863}. Best is trial 94 with value: 0.17224336264233508.
Fold 1 IBS: 0.17621008692601267
Fold 2 IBS: 0.16633045186007256
Fold 3 IBS: 0.18126863223857298
Fold 4 IBS: 0.18117789607614626
Fold 5 IBS: 0.17102784570801755
[I 2024-04-16 01:57:05,843] Trial 95 finished with value: 0.17520298256176442 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.40086016751976805, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01796266112637955}. Best is trial 94 with value: 0.17224336264233508.
Fold 1 IBS: 0.18757386481365138
Fold 2 IBS: 0.18369977922849565
Fold 3 IBS: 0.18177433001789325
Fold 4 IBS: 0.1972919352959476
Fold 5 IBS: 0.18820575374049853
[I 2024-04-16 01:57:15,802] Trial 96 finished with value: 0.18770913261929728 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.27862832144429955, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.037217558921652225}. Best is trial 94 with value: 0.17224336264233508.
Fold 1 IBS: 0.1771650297027054
Fold 2 IBS: 0.16510353444351725
Fold 3 IBS: 0.183282637665176
Fold 4 IBS: 0.17597978174624318
Fold 5 IBS: 0.16374703002346563
[I 2024-04-16 01:57:28,957] Trial 97 finished with value: 0.17305560271622147 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.35852014821524875, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04959420900948179}. Best is trial 94 with value: 0.17224336264233508.
Fold 1 IBS: 0.1777975380786596
Fold 2 IBS: 0.16521746556625724
Fold 3 IBS: 0.18197888293925849
Fold 4 IBS: 0.17521556005894928
Fold 5 IBS: 0.1644460448674012
[I 2024-04-16 01:57:39,783] Trial 98 finished with value: 0.17293109830210515 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.36621889090917237, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04769987771754522}. Best is trial 94 with value: 0.17224336264233508.
Fold 1 IBS: 0.17488241928999843
Fold 2 IBS: 0.16972025619909795
Fold 3 IBS: 0.18074954080103614
Fold 4 IBS: 0.17643401936842754
Fold 5 IBS: 0.1675984091121536
[I 2024-04-16 01:57:52,233] Trial 99 finished with value: 0.17387692895414272 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.33714070756118625, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.049034302088424776}. Best is trial 94 with value: 0.17224336264233508.


* Best trial for IBS:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.17224336264233508], datetime_start=datetime.datetime(2024, 4, 16, 1, 56, 47, 673590), datetime_complete=datetime.datetime(2024, 4, 16, 1, 56, 56, 830686), params={'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.401310433648782, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017290020666363863}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for IBS:
 0.17224336264233508

In [54]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.849
train_ibs:  0.172

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=15, max_features=None, max_leaf_nodes=17,
                     max_samples=0.9830923957685131, min_samples_leaf=4,
                     min_samples_split=11,
                     min_weight_fraction_leaf=0.04949739725380848,
                     n_estimators=283, random_state=123, warm_start=True)

test_cindex:  0.555

RandomSurvivalForest(max_depth=11, max_features='log2', max_leaf_nodes=15,
                     max_samples=0.401310433648782, min_samples_leaf=7,
                     min_samples_split=13,
                     min_weight_fraction_leaf=0.017290020666363863,
                     n_estimators=397, oob_score=True, random_state=123)

test_ibs:  0.226

In [58]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [60]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:57:58,647] A new study created in memory with name: no-name-0da87e23-a934-499f-9984-0cf852fcf2bd

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:58:00,918] Trial 0 finished with value: 0.7545221749618177 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:58:05,871] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:58:15,014] Trial 2 finished with value: 0.7028515093698544 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 01:58:15,939] Trial 3 finished with value: 0.702372125814296 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:58:20,020] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:58:24,484] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:58:26,367] Trial 6 finished with value: 0.7536807061030867 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:58:31,209] Trial 7 finished with value: 0.7234672955147796 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 01:58:31,551] Trial 8 finished with value: 0.7274413323734006 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 01:58:43,565] Trial 9 finished with value: 0.6822939708469005 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:58:47,396] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:58:49,368] Trial 11 finished with value: 0.718329566911612 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7545221749618177.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:58:52,053] Trial 12 finished with value: 0.7836335847164032 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:58:54,405] Trial 13 finished with value: 0.7308643567558468 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:58:56,307] Trial 14 finished with value: 0.7272634589095528 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6708860759493671

Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:58:57,552] Trial 15 finished with value: 0.7300192908165389 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6385281385281385
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:59:00,087] Trial 16 finished with value: 0.7134117264225257 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:59:01,893] Trial 17 finished with value: 0.7270936671723746 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:59:04,559] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:59:06,504] Trial 19 finished with value: 0.7245491930463168 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.5432900432900433
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5931372549019608
Fold 4 C-index: 0.580168776371308
Fold 5 C-index: 0.5727699530516432
[I 2024-04-16 01:59:06,756] Trial 20 finished with value: 0.5779624912372767 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 01:59:08,836] Trial 21 finished with value: 0.7591143750973541 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:59:11,270] Trial 22 finished with value: 0.7581040613704112 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:59:13,665] Trial 23 finished with value: 0.7334651192200246 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4354485106193713, 'min_weight_fraction_leaf': 0.02923560760429222}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:59:15,998] Trial 24 finished with value: 0.7180051580268406 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.34950482438457253, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:59:18,639] Trial 25 finished with value: 0.7440115069350647 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6363223369371479, 'min_weight_fraction_leaf': 0.004408180869012377}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:59:34,178] Trial 26 finished with value: 0.7091986963750962 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 494, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6041191076422192, 'min_weight_fraction_leaf': 0.06050836672641209}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:59:36,452] Trial 27 finished with value: 0.7177322784492328 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4912235374460364, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:59:38,154] Trial 28 finished with value: 0.7152657965891425 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7093054331237321, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6428571428571429
Fold 2 C-index: 0.6808035714285714
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6518987341772152
Fold 5 C-index: 0.6643192488262911
[I 2024-04-16 01:59:39,646] Trial 29 finished with value: 0.6750345629872558 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.37188286366136036, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 12 with value: 0.7836335847164032.

Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 01:59:41,812] Trial 30 finished with value: 0.7060338585019901 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.23596047192138714, 'min_weight_fraction_leaf': 0.09139810961881356}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 01:59:44,030] Trial 31 finished with value: 0.755245734941248 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5115588937941487, 'min_weight_fraction_leaf': 0.028675344107944124}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 01:59:46,329] Trial 32 finished with value: 0.7614144250870416 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4999135158398872, 'min_weight_fraction_leaf': 0.03283979494132459}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6255411255411255
Fold 2 C-index: 0.6629464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7018779342723005
[I 2024-04-16 01:59:48,207] Trial 33 finished with value: 0.6889455225963057 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 402, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.41913893375158834, 'min_weight_fraction_leaf': 0.06090578079474394}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:59:50,572] Trial 34 finished with value: 0.7680384831609753 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5276637014749268, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:59:55,730] Trial 35 finished with value: 0.7397238984006705 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5263412089067883, 'min_weight_fraction_leaf': 0.12132570942744575}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 02:00:06,097] Trial 36 finished with value: 0.6859931384829657 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 487, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.26003093908167757, 'min_weight_fraction_leaf': 0.07928403710470798}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:00:10,604] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5805417214896214, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 02:00:12,411] Trial 38 finished with value: 0.7403812067785671 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4667621597771344, 'min_weight_fraction_leaf': 0.0017830073681559051}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 02:00:23,486] Trial 39 finished with value: 0.7414211549220411 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8234703848097623, 'min_weight_fraction_leaf': 0.03799279161962574}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 02:00:25,933] Trial 40 finished with value: 0.6992132319061598 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.3903433327373315, 'min_weight_fraction_leaf': 0.11661679083948807}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 02:00:28,865] Trial 41 finished with value: 0.7625505222835013 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6284957906861912, 'min_weight_fraction_leaf': 0.048080576415530464}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:00:31,410] Trial 42 finished with value: 0.7693378648887391 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5470674972033914, 'min_weight_fraction_leaf': 0.051508896845072455}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:00:34,070] Trial 43 finished with value: 0.771096522897397 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5508768136302323, 'min_weight_fraction_leaf': 0.05058295913548107}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:00:37,430] Trial 44 finished with value: 0.7214924114510388 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5412802397734282, 'min_weight_fraction_leaf': 0.08029766022449972}. Best is trial 12 with value: 0.7836335847164032.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 02:00:40,181] Trial 45 finished with value: 0.7710868391263215 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 441, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.73384986702474, 'min_weight_fraction_leaf': 0.06107235835101944}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 02:00:41,298] Trial 46 finished with value: 0.7336534700996883 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7517985599701852, 'min_weight_fraction_leaf': 0.16861544496990513}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 02:00:49,611] Trial 47 finished with value: 0.7194472857134231 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 452, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7360169238712537, 'min_weight_fraction_leaf': 0.06365926789627255}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 02:00:53,470] Trial 48 finished with value: 0.7658282401600649 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 378, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9432027278500553, 'min_weight_fraction_leaf': 0.09907430792400711}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 02:00:55,895] Trial 49 finished with value: 0.699616579925865 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8388559086349276, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:00:58,164] Trial 50 finished with value: 0.7226709767279413 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9284553407997799, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 12 with value: 0.7836335847164032.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 02:01:02,049] Trial 51 finished with value: 0.7915109119710705 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.017319970761468517}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 02:01:06,392] Trial 52 finished with value: 0.785366865104524 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 417, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9463366132624874, 'min_weight_fraction_leaf': 0.021135260569454493}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:01:10,335] Trial 53 finished with value: 0.7286844271817869 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 398, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9281084411266491, 'min_weight_fraction_leaf': 0.01949803387366868}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 02:01:14,966] Trial 54 finished with value: 0.7749597119597932 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 419, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9517366697991381, 'min_weight_fraction_leaf': 0.01567414371889609}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 02:01:19,350] Trial 55 finished with value: 0.7767476982202791 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9670369929184901, 'min_weight_fraction_leaf': 0.01585058387608433}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 02:01:23,901] Trial 56 finished with value: 0.7505930560687621 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 333, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9969700666990196, 'min_weight_fraction_leaf': 0.01593436762263868}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 02:01:28,620] Trial 57 finished with value: 0.7748283389272662 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 366, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9636583004132044, 'min_weight_fraction_leaf': 0.015060339251230518}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 02:01:38,954] Trial 58 finished with value: 0.7324952297326003 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 361, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9021849571274223, 'min_weight_fraction_leaf': 0.017878083955335293}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 02:01:42,283] Trial 59 finished with value: 0.7724037343831031 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 283, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9601307766014657, 'min_weight_fraction_leaf': 0.00015183512754611203}. Best is trial 51 with value: 0.7915109119710705.

Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:01:45,731] Trial 60 finished with value: 0.7131004729725404 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 340, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8658611828589435, 'min_weight_fraction_leaf': 0.2583710069782479}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 02:01:48,195] Trial 61 finished with value: 0.7504370397569877 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9558514609686554, 'min_weight_fraction_leaf': 0.0004376378082063641}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 02:01:51,438] Trial 62 finished with value: 0.7758767600866827 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 319, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9556055644502253, 'min_weight_fraction_leaf': 0.02001760696446866}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 02:01:55,706] Trial 63 finished with value: 0.7815351060195874 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9116967278778296, 'min_weight_fraction_leaf': 0.02475995109263976}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 02:02:00,213] Trial 64 finished with value: 0.7747430784417692 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9048877559621522, 'min_weight_fraction_leaf': 0.022272602173385614}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 02:02:03,836] Trial 65 finished with value: 0.7762625906048899 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 317, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8509276072953407, 'min_weight_fraction_leaf': 0.07820286971775577}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:02:07,108] Trial 66 finished with value: 0.7770091152070482 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 268, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8567259578594748, 'min_weight_fraction_leaf': 0.07646261093997261}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 02:02:10,562] Trial 67 finished with value: 0.7648483002984172 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7918119241062582, 'min_weight_fraction_leaf': 0.07653797606436943}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:02:13,286] Trial 68 finished with value: 0.7735022147483607 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 238, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8441605925987908, 'min_weight_fraction_leaf': 0.07422087136160446}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 02:02:16,710] Trial 69 finished with value: 0.7842764281598795 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 309, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8654319243627412, 'min_weight_fraction_leaf': 0.048115844890583404}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 02:02:25,780] Trial 70 finished with value: 0.7278396472610341 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9107188996373348, 'min_weight_fraction_leaf': 0.04942353479061798}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 02:02:29,774] Trial 71 finished with value: 0.7640533937281943 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 317, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8600666154620139, 'min_weight_fraction_leaf': 0.10785215479995364}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:02:33,801] Trial 72 finished with value: 0.764833931554761 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 355, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8141486577615175, 'min_weight_fraction_leaf': 0.08992359990892933}. Best is trial 51 with value: 0.7915109119710705.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 02:02:37,644] Trial 73 finished with value: 0.8069693647568753 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 325, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9950335822264791, 'min_weight_fraction_leaf': 0.04299270642842414}. Best is trial 73 with value: 0.8069693647568753.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 02:02:40,766] Trial 74 finished with value: 0.8104647617649305 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 278, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9995822130663723, 'min_weight_fraction_leaf': 0.03767897791249608}. Best is trial 74 with value: 0.8104647617649305.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 02:02:43,611] Trial 75 finished with value: 0.8075696952876354 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 270, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9855384728805915, 'min_weight_fraction_leaf': 0.041369181169624056}. Best is trial 74 with value: 0.8104647617649305.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 02:02:46,011] Trial 76 finished with value: 0.8114496978713366 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 229, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9885600753858905, 'min_weight_fraction_leaf': 0.04260610891133887}. Best is trial 76 with value: 0.8114496978713366.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 02:02:48,187] Trial 77 finished with value: 0.8125280406008333 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 187, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9893633118498868, 'min_weight_fraction_leaf': 0.0432442139539608}. Best is trial 77 with value: 0.8125280406008333.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 02:02:50,682] Trial 78 finished with value: 0.8139813434409569 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 189, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9998215085018789, 'min_weight_fraction_leaf': 0.04318257190425022}. Best is trial 78 with value: 0.8139813434409569.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 02:02:52,895] Trial 79 finished with value: 0.8301333923575752 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 180, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9968632918374983, 'min_weight_fraction_leaf': 0.03324939216387568}. Best is trial 79 with value: 0.8301333923575752.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 02:02:55,050] Trial 80 finished with value: 0.8175400844789852 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 188, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9991088056852343, 'min_weight_fraction_leaf': 0.04275619942684842}. Best is trial 79 with value: 0.8301333923575752.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 02:02:57,333] Trial 81 finished with value: 0.8190015309029656 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 187, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9995623643353031, 'min_weight_fraction_leaf': 0.04015394882070913}. Best is trial 79 with value: 0.8301333923575752.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 02:02:59,200] Trial 82 finished with value: 0.8129767603000616 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 177, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9982505216593187, 'min_weight_fraction_leaf': 0.04133547658104543}. Best is trial 79 with value: 0.8301333923575752.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 02:03:01,193] Trial 83 finished with value: 0.7905645355923532 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 181, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9985957222382407, 'min_weight_fraction_leaf': 0.0667615786423453}. Best is trial 79 with value: 0.8301333923575752.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 02:03:02,743] Trial 84 finished with value: 0.8177089293471971 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9806840702199586, 'min_weight_fraction_leaf': 0.0398444321695863}. Best is trial 79 with value: 0.8301333923575752.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 02:03:04,144] Trial 85 finished with value: 0.7689814034821534 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 119, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9349332754074978, 'min_weight_fraction_leaf': 0.09669988479518213}. Best is trial 79 with value: 0.8301333923575752.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 02:03:06,215] Trial 86 finished with value: 0.8364629248107611 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 201, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9778804597491059, 'min_weight_fraction_leaf': 0.03313516954756932}. Best is trial 86 with value: 0.8364629248107611.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 02:03:08,424] Trial 87 finished with value: 0.7960715118800077 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 196, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9762442285109508, 'min_weight_fraction_leaf': 0.05842066958263123}. Best is trial 86 with value: 0.8364629248107611.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 02:03:12,049] Trial 88 finished with value: 0.7387713814192268 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8873968124495799, 'min_weight_fraction_leaf': 0.09014232060997421}. Best is trial 86 with value: 0.8364629248107611.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:03:14,446] Trial 89 finished with value: 0.7079415032354373 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 221, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9269569524472059, 'min_weight_fraction_leaf': 0.31995603043358334}. Best is trial 86 with value: 0.8364629248107611.

Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 02:03:16,254] Trial 90 finished with value: 0.7655148401521746 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 169, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.975230928116839, 'min_weight_fraction_leaf': 0.11216554969906518}. Best is trial 86 with value: 0.8364629248107611.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 02:03:18,625] Trial 91 finished with value: 0.828331037353433 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 203, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9974101521831956, 'min_weight_fraction_leaf': 0.03322487718781129}. Best is trial 86 with value: 0.8364629248107611.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 02:03:20,852] Trial 92 finished with value: 0.8317526747728865 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 203, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9786945658103637, 'min_weight_fraction_leaf': 0.03570912366902745}. Best is trial 86 with value: 0.8364629248107611.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 02:03:24,234] Trial 93 finished with value: 0.7878496764108649 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 198, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9216758841481814, 'min_weight_fraction_leaf': 0.06609293477531045}. Best is trial 86 with value: 0.8364629248107611.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 02:03:25,790] Trial 94 finished with value: 0.8391593658728016 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 80, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9766144605477189, 'min_weight_fraction_leaf': 0.030383657143011084}. Best is trial 94 with value: 0.8391593658728016.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 02:03:27,225] Trial 95 finished with value: 0.8266715588324505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 76, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8879053712835177, 'min_weight_fraction_leaf': 0.031069509584259462}. Best is trial 94 with value: 0.8391593658728016.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 02:03:28,304] Trial 96 finished with value: 0.7618778273558406 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 65, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8877835380432261, 'min_weight_fraction_leaf': 0.032173132347870684}. Best is trial 94 with value: 0.8391593658728016.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 02:03:29,606] Trial 97 finished with value: 0.8022672583028576 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.941326339360069, 'min_weight_fraction_leaf': 0.055299161388144696}. Best is trial 94 with value: 0.8391593658728016.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 02:03:30,274] Trial 98 finished with value: 0.8386660420339224 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9644072760987261, 'min_weight_fraction_leaf': 0.007895150261811743}. Best is trial 94 with value: 0.8391593658728016.

[I 2024-04-16 02:03:30,799] A new study created in memory with name: no-name-a0341bd5-d11a-4b83-b75d-36ceba6dd617

Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.6852678571428571
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:03:30,780] Trial 99 finished with value: 0.70687449725429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 16, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9736046275769301, 'min_weight_fraction_leaf': 0.20875086240286844}. Best is trial 94 with value: 0.8391593658728016.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.8391593658728016], datetime_start=datetime.datetime(2024, 4, 16, 2, 3, 24, 244515), datetime_complete=datetime.datetime(2024, 4, 16, 2, 3, 25, 789645), params={'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 80, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9766144605477189, 'min_weight_fraction_leaf': 0.030383657143011084}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.8391593658728016

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19253813568047395
Fold 2 IBS: 0.1890143265597397
Fold 3 IBS: 0.18399117374299914
Fold 4 IBS: 0.19039745430254038
Fold 5 IBS: 0.18618298052948526
[I 2024-04-16 02:03:37,810] Trial 0 finished with value: 0.18842481416304768 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-16 02:03:47,150] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.2081619740168843
Fold 2 IBS: 0.21335249164553943
Fold 3 IBS: 0.19791249440659664
Fold 4 IBS: 0.21645969228749617
Fold 5 IBS: 0.2088939994860925
[I 2024-04-16 02:03:55,578] Trial 2 finished with value: 0.20895613036852181 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.20951944111661355
Fold 2 IBS: 0.2155467443764039
Fold 3 IBS: 0.20043734021562323
Fold 4 IBS: 0.2196955915089044
Fold 5 IBS: 0.21197309083463922
[I 2024-04-16 02:03:58,182] Trial 3 finished with value: 0.21143444161043687 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-16 02:04:05,138] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-16 02:04:08,489] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.19179519196772749
Fold 2 IBS: 0.18921197342090923
Fold 3 IBS: 0.1845949572375171
Fold 4 IBS: 0.19302451607758053
Fold 5 IBS: 0.18845798500919972
[I 2024-04-16 02:04:15,877] Trial 6 finished with value: 0.1894169247425868 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.20432852346553582
Fold 2 IBS: 0.20544394372296482
Fold 3 IBS: 0.19455196017772247
Fold 4 IBS: 0.20923029828019124
Fold 5 IBS: 0.2024590246372511
[I 2024-04-16 02:04:20,479] Trial 7 finished with value: 0.2032027500567331 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.2064567329881415
Fold 2 IBS: 0.21478837022341057
Fold 3 IBS: 0.20027155214756473
Fold 4 IBS: 0.2198520855491969
Fold 5 IBS: 0.21054967310153455
[I 2024-04-16 02:04:21,426] Trial 8 finished with value: 0.21038368280196967 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.21302110554706358
Fold 2 IBS: 0.218889138323361
Fold 3 IBS: 0.2029981174481188
Fold 4 IBS: 0.2230484562622431
Fold 5 IBS: 0.21642210207274
[I 2024-04-16 02:04:32,894] Trial 9 finished with value: 0.2148757839307053 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-16 02:04:42,124] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.2030695462428324
Fold 2 IBS: 0.20441284886966296
Fold 3 IBS: 0.1942440178609656
Fold 4 IBS: 0.20968773216867373
Fold 5 IBS: 0.20138556589574375
[I 2024-04-16 02:04:48,575] Trial 11 finished with value: 0.20255994220757573 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.18842481416304768.
Fold 1 IBS: 0.1875015176684846
Fold 2 IBS: 0.17846599222057502
Fold 3 IBS: 0.18162384315344435
Fold 4 IBS: 0.18056790162197256
Fold 5 IBS: 0.1767298746647286
[I 2024-04-16 02:04:57,288] Trial 12 finished with value: 0.18097782586584102 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.2017822338206345
Fold 2 IBS: 0.20133147147889602
Fold 3 IBS: 0.19186735669882868
Fold 4 IBS: 0.20703339274022814
Fold 5 IBS: 0.19891639086347623
[I 2024-04-16 02:05:05,830] Trial 13 finished with value: 0.2001861691204127 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.20317466277152793
Fold 2 IBS: 0.20344358736086304
Fold 3 IBS: 0.19198535612547707
Fold 4 IBS: 0.20877369956604533
Fold 5 IBS: 0.2019399862537706
[I 2024-04-16 02:05:12,565] Trial 14 finished with value: 0.20186345841553677 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.18097782586584102.

Fold 1 IBS: 0.2009860924778935
Fold 2 IBS: 0.20253705419647441
Fold 3 IBS: 0.19227162112345852
Fold 4 IBS: 0.2064576102237238
Fold 5 IBS: 0.20075790744250557
[I 2024-04-16 02:05:17,580] Trial 15 finished with value: 0.20060205709281118 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.21310431813273892
Fold 2 IBS: 0.21985090013949052
Fold 3 IBS: 0.20391385644902058
Fold 4 IBS: 0.22335349047416186
Fold 5 IBS: 0.21745423224025956
[I 2024-04-16 02:05:27,688] Trial 16 finished with value: 0.21553535948713426 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.1968515699674832
Fold 2 IBS: 0.1926343178211174
Fold 3 IBS: 0.18437729383139792
Fold 4 IBS: 0.20149013169831276
Fold 5 IBS: 0.19266300557690633
[I 2024-04-16 02:05:34,600] Trial 17 finished with value: 0.19360326377904352 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-16 02:05:37,430] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.20128824580250043
Fold 2 IBS: 0.2022065290901975
Fold 3 IBS: 0.19165373066927688
Fold 4 IBS: 0.20592964849459786
Fold 5 IBS: 0.198777818788429
[I 2024-04-16 02:05:44,570] Trial 19 finished with value: 0.1999711945690003 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.21424296812963653
Fold 2 IBS: 0.2178303343560476
Fold 3 IBS: 0.20074928041102014
Fold 4 IBS: 0.21512815109204678
Fold 5 IBS: 0.21812569940884796
[I 2024-04-16 02:05:44,982] Trial 20 finished with value: 0.21321528667951978 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.19213955447063208
Fold 2 IBS: 0.18838212829893144
Fold 3 IBS: 0.18492536947217292
Fold 4 IBS: 0.1917429248336813
Fold 5 IBS: 0.18832923310902305
[I 2024-04-16 02:05:52,756] Trial 21 finished with value: 0.18910384203688818 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.1912314302378172
Fold 2 IBS: 0.18521274361169773
Fold 3 IBS: 0.18259988475995131
Fold 4 IBS: 0.18705280394439855
Fold 5 IBS: 0.18421266463426525
[I 2024-04-16 02:06:00,285] Trial 22 finished with value: 0.18606190543762602 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.18097782586584102.
Fold 1 IBS: 0.18681957614030412
Fold 2 IBS: 0.17837635533740862
Fold 3 IBS: 0.1786085080225434
Fold 4 IBS: 0.1757120542063733
Fold 5 IBS: 0.17341053219133523
[I 2024-04-16 02:06:08,778] Trial 23 finished with value: 0.17858540517959293 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.1954854052650422
Fold 2 IBS: 0.18628326254622088
Fold 3 IBS: 0.18488981381096287
Fold 4 IBS: 0.19039160201289473
Fold 5 IBS: 0.1870728083959556
[I 2024-04-16 02:06:16,884] Trial 24 finished with value: 0.18882457840621528 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.20305622202512452
Fold 2 IBS: 0.20489403647157617
Fold 3 IBS: 0.19407712450884188
Fold 4 IBS: 0.20684118463843146
Fold 5 IBS: 0.2000408664719397
[I 2024-04-16 02:06:24,894] Trial 25 finished with value: 0.20178188682318274 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.1994281208306251
Fold 2 IBS: 0.20099315155265213
Fold 3 IBS: 0.19037184242032865
Fold 4 IBS: 0.20294467905580452
Fold 5 IBS: 0.19578790910242178
[I 2024-04-16 02:06:37,135] Trial 26 finished with value: 0.1979051405923664 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.2012293488528363
Fold 2 IBS: 0.20209398521310695
Fold 3 IBS: 0.1913197124207275
Fold 4 IBS: 0.20618041160733544
Fold 5 IBS: 0.1996711242977101
[I 2024-04-16 02:06:47,113] Trial 27 finished with value: 0.20009891647834327 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.20192615763275698
Fold 2 IBS: 0.20147995870856042
Fold 3 IBS: 0.18830195924493215
Fold 4 IBS: 0.21122691320422882
Fold 5 IBS: 0.1997471965630791
[I 2024-04-16 02:06:52,256] Trial 28 finished with value: 0.2005364370707115 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.2083382011583748
Fold 2 IBS: 0.21401402968875932
Fold 3 IBS: 0.19893042919947412
Fold 4 IBS: 0.2183684691353802
Fold 5 IBS: 0.2098484109353834
[I 2024-04-16 02:06:56,163] Trial 29 finished with value: 0.20989990802347439 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.17858540517959293.

Fold 1 IBS: 0.19574948384138363
Fold 2 IBS: 0.18320445235447416
Fold 3 IBS: 0.18399571264411738
Fold 4 IBS: 0.18818584834971439
Fold 5 IBS: 0.1847924741624137
[I 2024-04-16 02:07:02,658] Trial 30 finished with value: 0.18718559427042067 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.2012130462314688
Fold 2 IBS: 0.19251954390900003
Fold 3 IBS: 0.1894012799573833
Fold 4 IBS: 0.199635572696493
Fold 5 IBS: 0.19581363629423457
[I 2024-04-16 02:07:09,738] Trial 31 finished with value: 0.19571661581771593 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7284646777879923, 'min_weight_fraction_leaf': 0.03048718971899994}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.1944911168079995
Fold 2 IBS: 0.1847424060733084
Fold 3 IBS: 0.1842692269026361
Fold 4 IBS: 0.18916435946536722
Fold 5 IBS: 0.1848012081444241
[I 2024-04-16 02:07:16,405] Trial 32 finished with value: 0.18749366347874707 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8171100382086772, 'min_weight_fraction_leaf': 0.06242514513187879}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.20110551053564574
Fold 2 IBS: 0.20198472584530403
Fold 3 IBS: 0.1914970389389298
Fold 4 IBS: 0.2071994379270833
Fold 5 IBS: 0.19935593489024328
[I 2024-04-16 02:07:25,202] Trial 33 finished with value: 0.20022852962744123 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5149627281114163, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.17858540517959293.
Fold 1 IBS: 0.19348110872534524
Fold 2 IBS: 0.16967797142490681
Fold 3 IBS: 0.1825744563601421
Fold 4 IBS: 0.16186985579965582
Fold 5 IBS: 0.15807931374855896
[I 2024-04-16 02:07:35,440] Trial 34 finished with value: 0.17313654121172178 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9212572489283476, 'min_weight_fraction_leaf': 0.027004406871740803}. Best is trial 34 with value: 0.17313654121172178.
Fold 1 IBS: 0.1897258753624611
Fold 2 IBS: 0.16879614092830506
Fold 3 IBS: 0.18205543595332557
Fold 4 IBS: 0.16171943062620497
Fold 5 IBS: 0.16056708955637633
[I 2024-04-16 02:07:48,488] Trial 35 finished with value: 0.17257279448533464 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9309730009379946, 'min_weight_fraction_leaf': 0.06944032885941434}. Best is trial 35 with value: 0.17257279448533464.
Fold 1 IBS: 0.18979701500086266
Fold 2 IBS: 0.16850526068086383
Fold 3 IBS: 0.18273510699138373
Fold 4 IBS: 0.1617703208223416
Fold 5 IBS: 0.16022524897176782
[I 2024-04-16 02:07:59,713] Trial 36 finished with value: 0.17260659049344393 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9349737959027588, 'min_weight_fraction_leaf': 0.06897665469252873}. Best is trial 35 with value: 0.17257279448533464.
Fold 1 IBS: 0.18367686017880552
Fold 2 IBS: 0.1691549065823607
Fold 3 IBS: 0.17852072736664806
Fold 4 IBS: 0.17107059970941707
Fold 5 IBS: 0.16946862934443402
[I 2024-04-16 02:08:10,904] Trial 37 finished with value: 0.1743783446363331 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9221801639396415, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 35 with value: 0.17257279448533464.
Fold 1 IBS: 0.18354942164943483
Fold 2 IBS: 0.1692717603232513
Fold 3 IBS: 0.17962262430414144
Fold 4 IBS: 0.17356977498735102
Fold 5 IBS: 0.17093534153670473
[I 2024-04-16 02:08:20,376] Trial 38 finished with value: 0.17538978456017668 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.1270317704976861}. Best is trial 35 with value: 0.17257279448533464.
Fold 1 IBS: 0.1912276060049087
Fold 2 IBS: 0.18461269943034764
Fold 3 IBS: 0.18217797156915788
Fold 4 IBS: 0.19122632539505638
Fold 5 IBS: 0.18825073799686054
[I 2024-04-16 02:08:32,324] Trial 39 finished with value: 0.18749906807926622 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 467, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.927974430369323, 'min_weight_fraction_leaf': 0.2150204152808745}. Best is trial 35 with value: 0.17257279448533464.
Fold 1 IBS: 0.18376950397486422
Fold 2 IBS: 0.17535146003610066
Fold 3 IBS: 0.1798870126331722
Fold 4 IBS: 0.18136639913987143
Fold 5 IBS: 0.17766545362215794
[I 2024-04-16 02:08:42,517] Trial 40 finished with value: 0.1796079658812333 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9227359291211079, 'min_weight_fraction_leaf': 0.16383226255035407}. Best is trial 35 with value: 0.17257279448533464.
Fold 1 IBS: 0.184115606898067
Fold 2 IBS: 0.17283902748381863
Fold 3 IBS: 0.179871181343843
Fold 4 IBS: 0.17637610675430312
Fold 5 IBS: 0.17294807462729805
[I 2024-04-16 02:08:53,389] Trial 41 finished with value: 0.17722999942146597 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8397268662959272, 'min_weight_fraction_leaf': 0.12855108804095228}. Best is trial 35 with value: 0.17257279448533464.
Fold 1 IBS: 0.19025941959980533
Fold 2 IBS: 0.16793669645459533
Fold 3 IBS: 0.18297417870352434
Fold 4 IBS: 0.161237322897757
Fold 5 IBS: 0.16043776477510402
[I 2024-04-16 02:09:03,177] Trial 42 finished with value: 0.1725690764861572 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.933195037561673, 'min_weight_fraction_leaf': 0.07109144942897555}. Best is trial 42 with value: 0.1725690764861572.
Fold 1 IBS: 0.18863236695449323
Fold 2 IBS: 0.16612071992045008
Fold 3 IBS: 0.1807012083990291
Fold 4 IBS: 0.16414404247700887
Fold 5 IBS: 0.16325407223012417
[I 2024-04-16 02:09:13,462] Trial 43 finished with value: 0.1725704819962211 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 442, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9415702495654658, 'min_weight_fraction_leaf': 0.08320966486724668}. Best is trial 42 with value: 0.1725690764861572.
Fold 1 IBS: 0.18936714422700343
Fold 2 IBS: 0.165654813502232
Fold 3 IBS: 0.17988207652424465
Fold 4 IBS: 0.16574244955695872
Fold 5 IBS: 0.16311985504417056
[I 2024-04-16 02:09:24,625] Trial 44 finished with value: 0.17275326777092187 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 426, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9530738870185149, 'min_weight_fraction_leaf': 0.0859945622534305}. Best is trial 42 with value: 0.1725690764861572.

Fold 1 IBS: 0.18805213459148196
Fold 2 IBS: 0.1681544887707249
Fold 3 IBS: 0.18188248727268916
Fold 4 IBS: 0.16335868140621157
Fold 5 IBS: 0.16065070124373665
[I 2024-04-16 02:09:36,918] Trial 45 finished with value: 0.17241969865696888 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9991372338226472, 'min_weight_fraction_leaf': 0.0747513303047341}. Best is trial 45 with value: 0.17241969865696888.
Fold 1 IBS: 0.20355292029098285
Fold 2 IBS: 0.204107363403046
Fold 3 IBS: 0.19458831147904218
Fold 4 IBS: 0.2080676178213458
Fold 5 IBS: 0.20054223894272527
[I 2024-04-16 02:09:46,443] Trial 46 finished with value: 0.20217169038742844 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9939662245230365, 'min_weight_fraction_leaf': 0.06863371055783322}. Best is trial 45 with value: 0.17241969865696888.
Fold 1 IBS: 0.19946790119993107
Fold 2 IBS: 0.1992318938760364
Fold 3 IBS: 0.18695146993371348
Fold 4 IBS: 0.2062626495482987
Fold 5 IBS: 0.19660596481716025
[I 2024-04-16 02:09:52,877] Trial 47 finished with value: 0.197703975875028 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 8, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8563084395162766, 'min_weight_fraction_leaf': 0.09732809537960536}. Best is trial 45 with value: 0.17241969865696888.
Fold 1 IBS: 0.1854085072582782
Fold 2 IBS: 0.1760727338626953
Fold 3 IBS: 0.18188902561598516
Fold 4 IBS: 0.18043471745364814
Fold 5 IBS: 0.17873956410755984
[I 2024-04-16 02:10:02,634] Trial 48 finished with value: 0.18050890965963334 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7981660874427287, 'min_weight_fraction_leaf': 0.15096828649717384}. Best is trial 45 with value: 0.17241969865696888.
Fold 1 IBS: 0.1850960914308788
Fold 2 IBS: 0.17217942828142205
Fold 3 IBS: 0.1815436990993473
Fold 4 IBS: 0.17915557131198578
Fold 5 IBS: 0.17547548150109793
[I 2024-04-16 02:10:12,560] Trial 49 finished with value: 0.1786900543249464 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 436, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.956812319085093, 'min_weight_fraction_leaf': 0.05511975928844108}. Best is trial 45 with value: 0.17241969865696888.
Fold 1 IBS: 0.1852568957239127
Fold 2 IBS: 0.1647403025131312
Fold 3 IBS: 0.18090911809350446
Fold 4 IBS: 0.16722384123057044
Fold 5 IBS: 0.16300386711034517
[I 2024-04-16 02:10:15,915] Trial 50 finished with value: 0.1722268049342928 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8933146603625428, 'min_weight_fraction_leaf': 0.08218798849465357}. Best is trial 50 with value: 0.1722268049342928.
Fold 1 IBS: 0.1858642963161282
Fold 2 IBS: 0.16271481161518048
Fold 3 IBS: 0.18080220121023635
Fold 4 IBS: 0.16497275035441908
Fold 5 IBS: 0.16385421335666425
[I 2024-04-16 02:10:18,934] Trial 51 finished with value: 0.17164165457052566 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 120, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8949711629363306, 'min_weight_fraction_leaf': 0.08881715885165918}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18489445100256888
Fold 2 IBS: 0.16548958355918078
Fold 3 IBS: 0.180171411109994
Fold 4 IBS: 0.16980421347651392
Fold 5 IBS: 0.166268571259829
[I 2024-04-16 02:10:22,342] Trial 52 finished with value: 0.1733256460816173 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 136, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8931017774106289, 'min_weight_fraction_leaf': 0.0924784870388018}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.2080431115560733
Fold 2 IBS: 0.21276023066017385
Fold 3 IBS: 0.1941423574490982
Fold 4 IBS: 0.2162688213311144
Fold 5 IBS: 0.20974980927505515
[I 2024-04-16 02:10:24,392] Trial 53 finished with value: 0.20819286605430296 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 76, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7645640286121316, 'min_weight_fraction_leaf': 0.32112215016899026}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.21397282735715992
Fold 2 IBS: 0.22114084432131537
Fold 3 IBS: 0.2047392140778624
Fold 4 IBS: 0.22461132731338662
Fold 5 IBS: 0.21889363522840471
[I 2024-04-16 02:10:27,258] Trial 54 finished with value: 0.2166715696596258 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 123, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8862579175953955, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.2093836128585439
Fold 2 IBS: 0.21376676854064314
Fold 3 IBS: 0.19969293215939002
Fold 4 IBS: 0.2178317176618898
Fold 5 IBS: 0.2096172730952141
[I 2024-04-16 02:10:32,330] Trial 55 finished with value: 0.21005846086313618 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9980202951138161, 'min_weight_fraction_leaf': 0.18172363488683785}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.20730506199726242
Fold 2 IBS: 0.21101894643797
Fold 3 IBS: 0.19800906589706901
Fold 4 IBS: 0.21646176058562788
Fold 5 IBS: 0.20678317031481572
[I 2024-04-16 02:10:37,244] Trial 56 finished with value: 0.207915601046549 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 175, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8348594511454608, 'min_weight_fraction_leaf': 0.1095599477938516}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19490511351218034
Fold 2 IBS: 0.1696808580604419
Fold 3 IBS: 0.18063366736157616
Fold 4 IBS: 0.16351646036313894
Fold 5 IBS: 0.16615089526785262
[I 2024-04-16 02:10:39,031] Trial 57 finished with value: 0.17497739891303798 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 62, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9585760551977901, 'min_weight_fraction_leaf': 0.05393121349573394}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18735288627681937
Fold 2 IBS: 0.18038079294957718
Fold 3 IBS: 0.18254358239856114
Fold 4 IBS: 0.1823482390175821
Fold 5 IBS: 0.17706028944755284
[I 2024-04-16 02:10:44,702] Trial 58 finished with value: 0.18193715801801852 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 221, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8992034001294561, 'min_weight_fraction_leaf': 0.07905876723612895}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18715355207183476
Fold 2 IBS: 0.17515309211908114
Fold 3 IBS: 0.17923490234330436
Fold 4 IBS: 0.18148861468515226
Fold 5 IBS: 0.17798835201324656
[I 2024-04-16 02:10:47,609] Trial 59 finished with value: 0.18020370264652383 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 91, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7895531182175657, 'min_weight_fraction_leaf': 0.14108604160490362}. Best is trial 51 with value: 0.17164165457052566.

Fold 1 IBS: 0.1958742848832495
Fold 2 IBS: 0.16658576851987503
Fold 3 IBS: 0.18445996749161686
Fold 4 IBS: 0.1639381964146127
Fold 5 IBS: 0.15665286759755212
[I 2024-04-16 02:10:51,426] Trial 60 finished with value: 0.17350221698138124 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8720069627631468, 'min_weight_fraction_leaf': 0.012040362487536843}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.2032968814717009
Fold 2 IBS: 0.16957221694600605
Fold 3 IBS: 0.18138481693412806
Fold 4 IBS: 0.16894879325917614
Fold 5 IBS: 0.1607009374338522
[I 2024-04-16 02:10:52,128] Trial 61 finished with value: 0.17678072920897267 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 12, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.951483670539142, 'min_weight_fraction_leaf': 0.07044272881112172}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18355535757798797
Fold 2 IBS: 0.17551564561208405
Fold 3 IBS: 0.1798879313067344
Fold 4 IBS: 0.17083892330396605
Fold 5 IBS: 0.16807943947510456
[I 2024-04-16 02:11:03,037] Trial 62 finished with value: 0.17557545945517541 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 483, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9656204116662644, 'min_weight_fraction_leaf': 0.05250679926753399}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18467332297395628
Fold 2 IBS: 0.1678562610155063
Fold 3 IBS: 0.1800632495985095
Fold 4 IBS: 0.16538936903140114
Fold 5 IBS: 0.16466353859892618
[I 2024-04-16 02:11:13,960] Trial 63 finished with value: 0.17252914824365986 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9000105799352534, 'min_weight_fraction_leaf': 0.09256382284540263}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18434937785614722
Fold 2 IBS: 0.16850067405135696
Fold 3 IBS: 0.17911322092688708
Fold 4 IBS: 0.16928092406517684
Fold 5 IBS: 0.16726202579245536
[I 2024-04-16 02:11:22,981] Trial 64 finished with value: 0.1737012445384047 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 382, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9005268369231949, 'min_weight_fraction_leaf': 0.10972910599035178}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18954700136134264
Fold 2 IBS: 0.16638601155154412
Fold 3 IBS: 0.17705864560355106
Fold 4 IBS: 0.16919918930900663
Fold 5 IBS: 0.16566669133743855
[I 2024-04-16 02:11:25,858] Trial 65 finished with value: 0.17357150783257658 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 112, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8263768472419275, 'min_weight_fraction_leaf': 0.09096952081464799}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.20195975427431845
Fold 2 IBS: 0.20146648873034684
Fold 3 IBS: 0.18781037347211646
Fold 4 IBS: 0.20846694715880357
Fold 5 IBS: 0.20121221798509298
[I 2024-04-16 02:11:37,440] Trial 66 finished with value: 0.20018315632413564 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 442, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8629598969194199, 'min_weight_fraction_leaf': 0.2772702088742331}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.21340833669527104
Fold 2 IBS: 0.21978478850428027
Fold 3 IBS: 0.20416786799796927
Fold 4 IBS: 0.2237193888327045
Fold 5 IBS: 0.21754893152111013
[I 2024-04-16 02:11:48,610] Trial 67 finished with value: 0.21572586271026703 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 485, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.27371576989282936, 'min_weight_fraction_leaf': 0.1254981790415977}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.20020554861497675
Fold 2 IBS: 0.20035646496287882
Fold 3 IBS: 0.1916580571557437
Fold 4 IBS: 0.21407466203412448
Fold 5 IBS: 0.20149621482377128
[I 2024-04-16 02:11:49,578] Trial 68 finished with value: 0.201558189518299 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 29, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.978346026643418, 'min_weight_fraction_leaf': 0.04089899157544339}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.21329926439247726
Fold 2 IBS: 0.21935660843032392
Fold 3 IBS: 0.2035815045064257
Fold 4 IBS: 0.22312239197847528
Fold 5 IBS: 0.21683112967606458
[I 2024-04-16 02:11:58,558] Trial 69 finished with value: 0.21523817979675336 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9097025276818902, 'min_weight_fraction_leaf': 0.3665146894445257}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18775822106761608
Fold 2 IBS: 0.1796066530808953
Fold 3 IBS: 0.18058741228159492
Fold 4 IBS: 0.18595601734981013
Fold 5 IBS: 0.18351031515652658
[I 2024-04-16 02:12:05,861] Trial 70 finished with value: 0.1834837237872886 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 328, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8093114050677033, 'min_weight_fraction_leaf': 0.17029115681578091}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19052444703145668
Fold 2 IBS: 0.168924567184524
Fold 3 IBS: 0.1841010436813747
Fold 4 IBS: 0.16260261686744223
Fold 5 IBS: 0.16094724324224888
[I 2024-04-16 02:12:09,871] Trial 71 finished with value: 0.17341998360140928 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 167, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.937043652087699, 'min_weight_fraction_leaf': 0.0696979099320262}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.1885928875206687
Fold 2 IBS: 0.16887852429029282
Fold 3 IBS: 0.17997282533072545
Fold 4 IBS: 0.16339275517303656
Fold 5 IBS: 0.16083958315833763
[I 2024-04-16 02:12:20,482] Trial 72 finished with value: 0.17233531509461222 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 451, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8658038292417524, 'min_weight_fraction_leaf': 0.07813836666294671}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.1958210816199523
Fold 2 IBS: 0.1726417996753676
Fold 3 IBS: 0.18682503595048797
Fold 4 IBS: 0.15962953607299926
Fold 5 IBS: 0.15817949721226154
[I 2024-04-16 02:12:31,262] Trial 73 finished with value: 0.17461939010621372 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 450, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8688266877806515, 'min_weight_fraction_leaf': 0.0211330850302315}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18561794938889078
Fold 2 IBS: 0.16508890632672438
Fold 3 IBS: 0.17867845385815623
Fold 4 IBS: 0.16551627125480844
Fold 5 IBS: 0.1639795960111319
[I 2024-04-16 02:12:43,011] Trial 74 finished with value: 0.17177623536794234 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 422, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996935677644583, 'min_weight_fraction_leaf': 0.09585515657733794}. Best is trial 51 with value: 0.17164165457052566.

Fold 1 IBS: 0.18861014255452424
Fold 2 IBS: 0.1845345537529862
Fold 3 IBS: 0.18346887733887327
Fold 4 IBS: 0.18717174704010517
Fold 5 IBS: 0.18266022048955657
[I 2024-04-16 02:12:52,733] Trial 75 finished with value: 0.1852891082352091 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 422, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9911930954780681, 'min_weight_fraction_leaf': 0.09946408845915759}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19999952895742903
Fold 2 IBS: 0.19525046896204418
Fold 3 IBS: 0.18771598274655127
Fold 4 IBS: 0.20216609938880742
Fold 5 IBS: 0.1939284836539042
[I 2024-04-16 02:13:01,158] Trial 76 finished with value: 0.19581211274174723 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.382179738522886, 'min_weight_fraction_leaf': 0.11561144058604561}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19059979093882856
Fold 2 IBS: 0.16264385444737578
Fold 3 IBS: 0.17915330069520083
Fold 4 IBS: 0.16808211619846603
Fold 5 IBS: 0.16682166150252403
[I 2024-04-16 02:13:10,738] Trial 77 finished with value: 0.17346014475647906 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9680523339779566, 'min_weight_fraction_leaf': 0.08527679685306255}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18271256236931455
Fold 2 IBS: 0.1688471563474602
Fold 3 IBS: 0.1795861238239339
Fold 4 IBS: 0.17279741673458004
Fold 5 IBS: 0.17117633165915636
[I 2024-04-16 02:13:19,165] Trial 78 finished with value: 0.175023918186889 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 360, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9999643667568361, 'min_weight_fraction_leaf': 0.13934281512577182}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19115597981346752
Fold 2 IBS: 0.16520118225214436
Fold 3 IBS: 0.1825065473805442
Fold 4 IBS: 0.16086053681380008
Fold 5 IBS: 0.161643510331898
[I 2024-04-16 02:13:25,002] Trial 79 finished with value: 0.1722735513183708 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 241, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.90193126827419, 'min_weight_fraction_leaf': 0.04927444826135055}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19273026700298676
Fold 2 IBS: 0.1651237486292963
Fold 3 IBS: 0.18194667269991746
Fold 4 IBS: 0.15995953147712452
Fold 5 IBS: 0.161695825553235
[I 2024-04-16 02:13:30,539] Trial 80 finished with value: 0.172291209072512 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 237, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.906608196253182, 'min_weight_fraction_leaf': 0.048784800330011494}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19160036328137797
Fold 2 IBS: 0.1649181678661526
Fold 3 IBS: 0.18228172011573482
Fold 4 IBS: 0.16069657010161925
Fold 5 IBS: 0.1617769913756656
[I 2024-04-16 02:13:37,915] Trial 81 finished with value: 0.17225476254811006 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 236, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9052319616890554, 'min_weight_fraction_leaf': 0.0459472624510847}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19401205250903064
Fold 2 IBS: 0.16538361168406396
Fold 3 IBS: 0.18173494335387133
Fold 4 IBS: 0.16207941406634505
Fold 5 IBS: 0.15934165949079865
[I 2024-04-16 02:13:44,610] Trial 82 finished with value: 0.17251033622082193 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 246, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8474159105369471, 'min_weight_fraction_leaf': 0.04305715458415086}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19724577650710157
Fold 2 IBS: 0.16078094379862753
Fold 3 IBS: 0.18211632245361567
Fold 4 IBS: 0.16646877448727274
Fold 5 IBS: 0.16608776291090638
[I 2024-04-16 02:13:50,834] Trial 83 finished with value: 0.1745399160315048 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 240, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8519873574849514, 'min_weight_fraction_leaf': 0.049517312010809916}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.1895121392743429
Fold 2 IBS: 0.1751558700194539
Fold 3 IBS: 0.18118722310146315
Fold 4 IBS: 0.17992547713770432
Fold 5 IBS: 0.1775667372647166
[I 2024-04-16 02:13:57,411] Trial 84 finished with value: 0.1806694893595362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.012830813455518623}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.2029905822054353
Fold 2 IBS: 0.20154499195798403
Fold 3 IBS: 0.19234486884378324
Fold 4 IBS: 0.20629987559589477
Fold 5 IBS: 0.19759540668548647
[I 2024-04-16 02:14:03,075] Trial 85 finished with value: 0.20015514505771675 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 245, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.762762135767835, 'min_weight_fraction_leaf': 0.035441768906323536}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.1975119353658237
Fold 2 IBS: 0.16100030088174058
Fold 3 IBS: 0.18395078151136154
Fold 4 IBS: 0.16030167329196554
Fold 5 IBS: 0.16727146222197786
[I 2024-04-16 02:14:09,497] Trial 86 finished with value: 0.17400723065457385 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 276, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.82250375224754, 'min_weight_fraction_leaf': 0.0026870311185277773}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19362274012896388
Fold 2 IBS: 0.16734489049861695
Fold 3 IBS: 0.185453795856003
Fold 4 IBS: 0.16202317493814888
Fold 5 IBS: 0.1589926055223975
[I 2024-04-16 02:14:14,349] Trial 87 finished with value: 0.17348744138882605 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 204, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8771221645973168, 'min_weight_fraction_leaf': 0.025107185572375124}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.1935066708296699
Fold 2 IBS: 0.17907633887026103
Fold 3 IBS: 0.18430212682234376
Fold 4 IBS: 0.18777226708404274
Fold 5 IBS: 0.18355851940925377
[I 2024-04-16 02:14:19,680] Trial 88 finished with value: 0.18564318460311421 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9068197450314681, 'min_weight_fraction_leaf': 0.04527192336231282}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19420229054548963
Fold 2 IBS: 0.1673914747064346
Fold 3 IBS: 0.18403943510592494
Fold 4 IBS: 0.16219802462461594
Fold 5 IBS: 0.16216281814028985
[I 2024-04-16 02:14:24,302] Trial 89 finished with value: 0.173998808624551 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 195, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8454629097676154, 'min_weight_fraction_leaf': 0.061737502787967996}. Best is trial 51 with value: 0.17164165457052566.

Fold 1 IBS: 0.19091350642673613
Fold 2 IBS: 0.17241215632395923
Fold 3 IBS: 0.1790391638097396
Fold 4 IBS: 0.17759959680796716
Fold 5 IBS: 0.172995935264056
[I 2024-04-16 02:14:30,434] Trial 90 finished with value: 0.17859207172649164 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 257, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7723359182067533, 'min_weight_fraction_leaf': 0.03269650735672842}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19076745166131998
Fold 2 IBS: 0.16416395573150727
Fold 3 IBS: 0.18090486926599017
Fold 4 IBS: 0.16213093075559837
Fold 5 IBS: 0.16216887109996253
[I 2024-04-16 02:14:37,957] Trial 91 finished with value: 0.17202721570287566 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 264, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9099973273615812, 'min_weight_fraction_leaf': 0.056016366598885474}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19048780992423908
Fold 2 IBS: 0.16662170893490105
Fold 3 IBS: 0.18205187364402192
Fold 4 IBS: 0.1618691905650026
Fold 5 IBS: 0.16103860806934978
[I 2024-04-16 02:14:45,003] Trial 92 finished with value: 0.17241383822750286 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 268, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9166241566748304, 'min_weight_fraction_leaf': 0.05728909983061797}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18913702194083662
Fold 2 IBS: 0.1653954735633357
Fold 3 IBS: 0.18076693048045417
Fold 4 IBS: 0.16453841418817644
Fold 5 IBS: 0.16248557980486578
[I 2024-04-16 02:14:52,124] Trial 93 finished with value: 0.17246468399553375 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 271, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.91545949150744, 'min_weight_fraction_leaf': 0.07838514504566094}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.1942249736636019
Fold 2 IBS: 0.16797495138365484
Fold 3 IBS: 0.18194452512541787
Fold 4 IBS: 0.1652084677121724
Fold 5 IBS: 0.16238109757968666
[I 2024-04-16 02:14:57,010] Trial 94 finished with value: 0.17434680309290673 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 206, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9712216852139879, 'min_weight_fraction_leaf': 0.05700231869924561}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.2005618768056638
Fold 2 IBS: 0.20040845846768018
Fold 3 IBS: 0.19079639063712844
Fold 4 IBS: 0.2016992470827619
Fold 5 IBS: 0.1954552605775703
[I 2024-04-16 02:15:03,544] Trial 95 finished with value: 0.19778424671416092 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 297, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8885925951282676, 'min_weight_fraction_leaf': 0.015863579780834337}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18849548473824015
Fold 2 IBS: 0.1625856620037129
Fold 3 IBS: 0.17983597962124162
Fold 4 IBS: 0.1686390464943716
Fold 5 IBS: 0.16813070223110596
[I 2024-04-16 02:15:11,073] Trial 96 finished with value: 0.17353737501773445 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 313, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.948169546568547, 'min_weight_fraction_leaf': 0.10350911333352135}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.18982282205683007
Fold 2 IBS: 0.16494129784460015
Fold 3 IBS: 0.1821486740768206
Fold 4 IBS: 0.16395752492394416
Fold 5 IBS: 0.16133015095954203
[I 2024-04-16 02:15:17,123] Trial 97 finished with value: 0.1724400939723474 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 231, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8807605976222587, 'min_weight_fraction_leaf': 0.06139301826179978}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.1900230535852906
Fold 2 IBS: 0.16590108158512185
Fold 3 IBS: 0.1820659636552667
Fold 4 IBS: 0.1661143211652872
Fold 5 IBS: 0.16239482089215998
[I 2024-04-16 02:15:24,159] Trial 98 finished with value: 0.17329984817662528 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 268, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.977251913480659, 'min_weight_fraction_leaf': 0.07827214885214179}. Best is trial 51 with value: 0.17164165457052566.
Fold 1 IBS: 0.19210711018328833
Fold 2 IBS: 0.16657106769997526
Fold 3 IBS: 0.1810358391778413
Fold 4 IBS: 0.1652330261785315
Fold 5 IBS: 0.16262398549922008
[I 2024-04-16 02:15:29,062] Trial 99 finished with value: 0.1735142057477713 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 191, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9432812447468042, 'min_weight_fraction_leaf': 0.04984579553016549}. Best is trial 51 with value: 0.17164165457052566.


* Best trial for IBS:
 FrozenTrial(number=51, state=TrialState.COMPLETE, values=[0.17164165457052566], datetime_start=datetime.datetime(2024, 4, 16, 2, 10, 15, 922898), datetime_complete=datetime.datetime(2024, 4, 16, 2, 10, 18, 933654), params={'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 120, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8949711629363306, 'min_weight_fraction_leaf': 0.08881715885165918}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=51, value=None)


* Best Score for IBS:
 0.17164165457052566

In [61]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [62]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.839
train_ibs:  0.172

#### Test

In [63]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [64]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=7, max_features='auto', max_leaf_nodes=14,
                   max_samples=0.9766144605477189, min_samples_leaf=2,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.030383657143011084,
                   n_estimators=80, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.574

ExtraSurvivalTrees(max_depth=11, max_features=None, max_leaf_nodes=7,
                   max_samples=0.8949711629363306, min_samples_leaf=2,
                   min_samples_split=10,
                   min_weight_fraction_leaf=0.08881715885165918,
                   n_estimators=120, oob_score=True, random_state=123)

IBS: 0.222

In [65]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [66]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 02:15:30,266] A new study created in memory with name: no-name-f6d81090-3117-4321-b6ab-c182a12550de

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:16:08,012] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:16:27,618] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:16:46,971] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:17:16,479] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:17:28,819] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:17:31,673] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:18:01,753] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:18:09,968] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:18:10,930] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7723004694835681
[I 2024-04-16 02:19:26,198] Trial 9 finished with value: 0.7400172900202723 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7400172900202723.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.7253521126760564
[I 2024-04-16 02:21:22,921] Trial 10 finished with value: 0.6762046627675529 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7400172900202723.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:23:34,058] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7400172900202723.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7769953051643192
[I 2024-04-16 02:25:24,591] Trial 12 finished with value: 0.7476370623899082 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:20,044] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:27:33,901] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:28:42,052] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:29:29,687] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:31:04,727] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:33:14,787] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:33:20,108] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:34:08,482] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 02:35:50,917] Trial 21 finished with value: 0.6762505605169181 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 02:37:22,717] Trial 22 finished with value: 0.713908524620727 and parameters: {'subsample': 0.8956069884856214, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2154325997461391, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.38657871816113815, 'max_features': 'auto', 'min_impurity_decrease': 5.581115247824534e-07, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:38:39,097] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7743503496065262, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.31930849090648333, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9663328483036315, 'min_weight_fraction_leaf': 0.441052304834414, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:35,934] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8969825748215434, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21976013005558012, 'n_estimators': 340, 'criterion': 'squared_error', 'ccp_alpha': 0.785180332493211, 'min_weight_fraction_leaf': 0.2669492013977464, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.7476370623899082.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:40:43,238] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8840318412875596, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.27382248438555523, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 2.0183033060186855, 'min_weight_fraction_leaf': 0.33643534713187806, 'max_features': 'auto', 'min_impurity_decrease': 5.889654690360788e-06, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:41:52,347] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7565765917190008, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.4300954216773497, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6678836557349488, 'min_weight_fraction_leaf': 0.06207030473994396, 'max_features': 1, 'min_impurity_decrease': 7.622421032390112e-07, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:43:36,846] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.322970332048742, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 5.9472530603001, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 7.551787280023211e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:44:11,875] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.5232204998663266, 'n_estimators': 326, 'criterion': 'squared_error', 'ccp_alpha': 4.188554251555486, 'min_weight_fraction_leaf': 0.43612805409636834, 'max_features': 0.1, 'min_impurity_decrease': 3.2161459286083955e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:44:19,542] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.32499045544570565, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 2.694991982922698, 'min_weight_fraction_leaf': 0.37973053029520576, 'max_features': 'log2', 'min_impurity_decrease': 1.983769791843576e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:44:44,191] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.1618733123667288, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.29835074442775955, 'max_features': 'auto', 'min_impurity_decrease': 3.855449012555335e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 02:46:25,342] Trial 31 finished with value: 0.717439133832758 and parameters: {'subsample': 0.9458857893837966, 'learning_rate': 0.016420196712320707, 'dropout_rate': 0.2035906465216125, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.36089352993330637, 'max_features': 'auto', 'min_impurity_decrease': 4.318534340206297e-07, 'validation_fraction': 0.9595045281115817, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 02:48:09,294] Trial 32 finished with value: 0.7458278388260926 and parameters: {'subsample': 0.8638126341310897, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.22569622133720652, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.019083703384414813, 'min_weight_fraction_leaf': 0.351646089861356, 'max_features': 'auto', 'min_impurity_decrease': 1.0352347378444166e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:49:44,419] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9565444847948921, 'learning_rate': 0.016942278074178134, 'dropout_rate': 0.26584476281814184, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.3586353681932053, 'max_features': 'auto', 'min_impurity_decrease': 1.3326513674306949e-07, 'validation_fraction': 0.8389914767654065, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:51:12,211] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7038358300021869, 'learning_rate': 0.026650337425697362, 'dropout_rate': 0.369220485987212, 'n_estimators': 472, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8672217172879074, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0420752279999204e-07, 'validation_fraction': 0.9169827663346786, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:52:24,860] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.8615302123878027, 'learning_rate': 0.016287667469869524, 'dropout_rate': 0.16621310899612352, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1524333738759642, 'min_weight_fraction_leaf': 0.16211724647631331, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:03,811] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6682496627875864, 'learning_rate': 0.030254735591726832, 'dropout_rate': 0.29166011812932907, 'n_estimators': 299, 'criterion': 'squared_error', 'ccp_alpha': 0.48701662298918014, 'min_weight_fraction_leaf': 0.24844276308137436, 'max_features': 'auto', 'min_impurity_decrease': 2.2923203534620568e-05, 'validation_fraction': 0.8152696073327098, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 12 with value: 0.7476370623899082.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:37,672] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7883126136564298, 'learning_rate': 0.02225236619873, 'dropout_rate': 0.7511928761026783, 'n_estimators': 408, 'criterion': 'squared_error', 'ccp_alpha': 1.198246212835568, 'min_weight_fraction_leaf': 0.42198945643308866, 'max_features': None, 'min_impurity_decrease': 8.54824079758415e-06, 'validation_fraction': 0.36353542989298265, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:55:05,452] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0010786268484829992, 'dropout_rate': 0.4076069474884072, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.295727563116735, 'max_features': 'auto', 'min_impurity_decrease': 1.0214527419957568e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:56:26,947] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.041857701576065075, 'dropout_rate': 0.3444296796757608, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.49564059074376393, 'max_features': 1, 'min_impurity_decrease': 2.966650399906854e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:57:23,732] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5863013406787322, 'learning_rate': 0.007311607072090859, 'dropout_rate': 0.22290618957651392, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 0.5271854997531392, 'min_weight_fraction_leaf': 0.2674270064426415, 'max_features': 'auto', 'min_impurity_decrease': 2.2073664358493507e-07, 'validation_fraction': 0.6520524706411407, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 10}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6455399061032864
[I 2024-04-16 02:57:24,219] Trial 41 finished with value: 0.6429727820316606 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.01362396235680392, 'dropout_rate': 0.2062435369784147, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.01657550447328801, 'min_weight_fraction_leaf': 0.3505399688940837, 'max_features': 'auto', 'min_impurity_decrease': 3.2101990795082183e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6774891774891775
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 02:59:03,266] Trial 42 finished with value: 0.718030196142218 and parameters: {'subsample': 0.8533107407997301, 'learning_rate': 0.007773927115663986, 'dropout_rate': 0.13112078909045524, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.002608770948556355, 'min_weight_fraction_leaf': 0.4128432753433128, 'max_features': 'auto', 'min_impurity_decrease': 5.944083612909987e-07, 'validation_fraction': 0.8846352497042296, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:00:54,837] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8537828670002746, 'learning_rate': 0.006387564095638705, 'dropout_rate': 0.14103084365529428, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.817694027019807, 'min_weight_fraction_leaf': 0.4055199685421495, 'max_features': 'auto', 'min_impurity_decrease': 1.0127188716001679e-07, 'validation_fraction': 0.8846775181555923, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:02:20,949] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9979692688170061, 'learning_rate': 0.018866368595143467, 'dropout_rate': 0.13470507680405208, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.1995459782383484, 'min_weight_fraction_leaf': 0.46282880746501454, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7785221066313981, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:52,283] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.9423581992051376, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.1841937912472535, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.415353860249426, 'min_weight_fraction_leaf': 0.21565594544774125, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.9726137478639892, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:04:02,136] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8422605515062627, 'learning_rate': 0.023740342140917903, 'dropout_rate': 0.9694253886674298, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 6.2946137459239395, 'min_weight_fraction_leaf': 0.32020062193032595, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0058604443673675e-07, 'validation_fraction': 0.8666993731020032, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:05:42,140] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.8213077858159359, 'learning_rate': 0.006066129837698666, 'dropout_rate': 0.2502078347914406, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 1.0929789618945918, 'min_weight_fraction_leaf': 0.37165158771817175, 'max_features': 'log2', 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.7292699872905781, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:21,235] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7434813106553043, 'learning_rate': 0.014252633864159536, 'dropout_rate': 0.10308804442602489, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 0.43583456106887075, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 'auto', 'min_impurity_decrease': 1.1669342789968816e-06, 'validation_fraction': 0.9922167438954732, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 12 with value: 0.7476370623899082.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:37,947] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7918904765497661, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.46610361399140793, 'max_features': None, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8725986413596462, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:07:43,027] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9263228105960017, 'learning_rate': 0.03241286314321831, 'dropout_rate': 0.28503824367896063, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.3883012665777896, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 5.669547081135241e-07, 'validation_fraction': 0.21769072749948642, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6774891774891775
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 03:09:06,417] Trial 51 finished with value: 0.718030196142218 and parameters: {'subsample': 0.8666208085311428, 'learning_rate': 0.010299237341157315, 'dropout_rate': 0.22486517268782114, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.01237319335130728, 'min_weight_fraction_leaf': 0.40520668278071015, 'max_features': 'auto', 'min_impurity_decrease': 4.3165690993230386e-07, 'validation_fraction': 0.9299180470052416, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 03:10:26,530] Trial 52 finished with value: 0.7040867246224248 and parameters: {'subsample': 0.862657875185063, 'learning_rate': 0.008306104796295998, 'dropout_rate': 0.2416732200644876, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.03660243985093782, 'min_weight_fraction_leaf': 0.42223276607292903, 'max_features': 'auto', 'min_impurity_decrease': 1.9405719092810494e-07, 'validation_fraction': 0.9395823090270392, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:12:05,688] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.967375882472721, 'learning_rate': 0.001394900878889816, 'dropout_rate': 0.1429837848690379, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.45374308869283775, 'min_weight_fraction_leaf': 0.4108404544677715, 'max_features': 'auto', 'min_impurity_decrease': 4.0655981745194066e-07, 'validation_fraction': 0.8259835575505652, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:13:54,099] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8134129014758551, 'learning_rate': 0.019733381620994493, 'dropout_rate': 0.18641432881009587, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.9596523069530926, 'min_weight_fraction_leaf': 0.2970013736941614, 'max_features': 'auto', 'min_impurity_decrease': 1.1580334563112213e-06, 'validation_fraction': 0.8996663522529539, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:14:43,175] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9195938698764112, 'learning_rate': 0.015173363534313505, 'dropout_rate': 0.3034930079612927, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.35259963018802765, 'min_weight_fraction_leaf': 0.36508275980555405, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.9545460877946491, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:15:56,327] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.5150383761242161, 'learning_rate': 0.004332984500606809, 'dropout_rate': 0.23996644019536584, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6264958328369468, 'min_weight_fraction_leaf': 0.3385656815459147, 'max_features': 'auto', 'min_impurity_decrease': 5.479611541769766e-07, 'validation_fraction': 0.9991586611408243, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6784037558685446
[I 2024-04-16 03:17:28,720] Trial 57 finished with value: 0.6491212741032489 and parameters: {'subsample': 0.8773751542246392, 'learning_rate': 0.008949552280352413, 'dropout_rate': 0.35136020576582316, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.001936457287774803, 'min_weight_fraction_leaf': 0.46006445679681335, 'max_features': 1, 'min_impurity_decrease': 4.834524920287448e-06, 'validation_fraction': 0.5189236064802895, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:19:04,460] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.6843244921733918, 'learning_rate': 0.0253510504546932, 'dropout_rate': 0.12033118040350205, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 1.625653153563989, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'auto', 'min_impurity_decrease': 1.5983704938418812e-07, 'validation_fraction': 0.7886847055500306, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:19:59,482] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.021369220605781735, 'dropout_rate': 0.4274904250363094, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.4410912197424578, 'max_features': 0.1, 'min_impurity_decrease': 3.251577586017116e-07, 'validation_fraction': 0.8548774558884649, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:20:13,936] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.18796169351263226, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 2.934583742024675, 'min_weight_fraction_leaf': 0.22745666702108258, 'max_features': 'log2', 'min_impurity_decrease': 1.7635925207609514e-06, 'validation_fraction': 0.8928900471979833, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 12 with value: 0.7476370623899082.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:21:35,075] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.9082876532055691, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.22106826324294734, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22580244780696104, 'min_weight_fraction_leaf': 0.39038531498517337, 'max_features': 'auto', 'min_impurity_decrease': 6.513707268856941e-07, 'validation_fraction': 0.9307105316317981, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:23:12,558] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.9763302214447585, 'learning_rate': 0.01082289338801184, 'dropout_rate': 0.16671702405067812, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.7562237450148781, 'min_weight_fraction_leaf': 0.4020635676726066, 'max_features': 'auto', 'min_impurity_decrease': 9.006731163870761e-07, 'validation_fraction': 0.9167969646120265, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 03:24:49,141] Trial 63 finished with value: 0.7409560481756035 and parameters: {'subsample': 0.8703294082808486, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.2614766602947102, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.37595194847909125, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.9646429973127362, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:26:22,690] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7961678718772995, 'learning_rate': 0.015415575577593231, 'dropout_rate': 0.262554001169913, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.2777045506790212, 'min_weight_fraction_leaf': 0.33434502833689206, 'max_features': 'auto', 'min_impurity_decrease': 3.33975749875224e-07, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:27:54,155] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8385594937622445, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.30265220308227164, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.29056375204041135, 'min_weight_fraction_leaf': 0.28320128906700315, 'max_features': 'auto', 'min_impurity_decrease': 1.5031409606569138e-07, 'validation_fraction': 0.962588947418926, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:29:20,353] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8825125214383175, 'learning_rate': 0.01896416177644482, 'dropout_rate': 0.3845297883432178, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 2.1083391199212573, 'min_weight_fraction_leaf': 0.37068365181765817, 'max_features': 'auto', 'min_impurity_decrease': 2.926750067783851e-07, 'validation_fraction': 0.8532835495181553, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:30:36,627] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4585158632928328, 'learning_rate': 0.014185974978345665, 'dropout_rate': 0.20713420518497186, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.31472432527464905, 'max_features': 'sqrt', 'min_impurity_decrease': 4.927665175660364e-07, 'validation_fraction': 0.9061207180731781, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:31:50,534] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.9444579521154932, 'learning_rate': 0.003984164164187884, 'dropout_rate': 0.3349732603740458, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 1.078654850128927, 'min_weight_fraction_leaf': 0.1817947096952169, 'max_features': 'auto', 'min_impurity_decrease': 1.3822768751381375e-06, 'validation_fraction': 0.9998779842696178, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:32:34,037] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7351244679725103, 'learning_rate': 0.021607496405331474, 'dropout_rate': 0.6578270843665299, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.41822793529640967, 'max_features': 'auto', 'min_impurity_decrease': 7.981891756908656e-06, 'validation_fraction': 0.8252701554197789, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7582159624413145
[I 2024-04-16 03:33:47,478] Trial 70 finished with value: 0.7387997107342263 and parameters: {'subsample': 0.7696833733505561, 'learning_rate': 0.009479076517851487, 'dropout_rate': 0.27892959003506596, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.010016393064755276, 'min_weight_fraction_leaf': 0.38115268230138605, 'max_features': None, 'min_impurity_decrease': 1.0506244573812146e-07, 'validation_fraction': 0.7475037972329144, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6731601731601732
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 03:35:00,599] Trial 71 finished with value: 0.7093912860327197 and parameters: {'subsample': 0.7726307722867607, 'learning_rate': 0.009349407530944867, 'dropout_rate': 0.272889788803047, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.43478396682346765, 'max_features': None, 'min_impurity_decrease': 1.417211124243175e-07, 'validation_fraction': 0.6051329974465358, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:36:20,445] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.8428422230969325, 'learning_rate': 0.01331722405101492, 'dropout_rate': 0.23553989617782028, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.7319078134182367, 'min_weight_fraction_leaf': 0.38176105098156154, 'max_features': None, 'min_impurity_decrease': 1.0230782331935316e-07, 'validation_fraction': 0.6865031786074132, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:37:26,350] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.6388012925828102, 'learning_rate': 0.05058817311100894, 'dropout_rate': 0.17684002011933098, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.3525715430721856, 'min_weight_fraction_leaf': 0.3546586377729009, 'max_features': None, 'min_impurity_decrease': 2.1058795352301393e-07, 'validation_fraction': 0.7570165302670715, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:38:29,683] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8702188248200012, 'learning_rate': 0.007506009311421697, 'dropout_rate': 0.3101706081176934, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7061413987952186, 'min_weight_fraction_leaf': 0.4804502891962041, 'max_features': None, 'min_impurity_decrease': 4.35639363899407e-07, 'validation_fraction': 0.6438380550226332, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 03:40:19,790] Trial 75 finished with value: 0.7228935719452207 and parameters: {'subsample': 0.9205768668635214, 'learning_rate': 0.01724034992100258, 'dropout_rate': 0.12703135634048596, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.008770821860897261, 'min_weight_fraction_leaf': 0.2583508212385103, 'max_features': 'auto', 'min_impurity_decrease': 2.2530818348445326e-07, 'validation_fraction': 0.7975908289157518, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:42:19,480] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5556564275523779, 'learning_rate': 0.005501397538590462, 'dropout_rate': 0.12045522900957169, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.494374465745327, 'min_weight_fraction_leaf': 0.2550469541040272, 'max_features': 'auto', 'min_impurity_decrease': 2.339316587158401e-07, 'validation_fraction': 0.7976980274311595, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:44:01,849] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8285592654175189, 'learning_rate': 0.028484074857794688, 'dropout_rate': 0.15163486664463413, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.9525490995769573, 'min_weight_fraction_leaf': 0.1953272024141306, 'max_features': 1, 'min_impurity_decrease': 1.5484280514656853e-07, 'validation_fraction': 0.7272783273373051, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:45:18,186] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.9063586725553313, 'learning_rate': 0.012134054211554952, 'dropout_rate': 0.2614305553858645, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.2877817990193558, 'min_weight_fraction_leaf': 0.23706598947269453, 'max_features': 'auto', 'min_impurity_decrease': 0.0002607692087694095, 'validation_fraction': 0.8504502896331346, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:45:34,720] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7948647229444274, 'learning_rate': 0.0011929024714651838, 'dropout_rate': 0.8831816560103296, 'n_estimators': 372, 'criterion': 'friedman_mse', 'ccp_alpha': 1.812067956922833, 'min_weight_fraction_leaf': 0.2793975904949615, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7657294452038914, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:47:00,434] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8890927796212522, 'learning_rate': 0.017685317600779724, 'dropout_rate': 0.3616106017512225, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.00846169990235135, 'max_features': 'log2', 'min_impurity_decrease': 2.607076310858583e-06, 'validation_fraction': 0.8768831507049978, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7377450980392157
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 03:48:30,631] Trial 81 finished with value: 0.7121195580089441 and parameters: {'subsample': 0.9236004713650326, 'learning_rate': 0.00968012864029484, 'dropout_rate': 0.19317184218100655, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.025581316251923916, 'min_weight_fraction_leaf': 0.39842986398243446, 'max_features': 'auto', 'min_impurity_decrease': 8.153971628018849e-07, 'validation_fraction': 0.9436075044523529, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:49:49,714] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9711088741393996, 'learning_rate': 0.016959750689893874, 'dropout_rate': 0.22387756751818047, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.5284544931001979, 'min_weight_fraction_leaf': 0.3296749847290039, 'max_features': 'auto', 'min_impurity_decrease': 2.803859813004287e-07, 'validation_fraction': 0.9165663182888988, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:51:08,919] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.8588094548799884, 'learning_rate': 0.024046857018968235, 'dropout_rate': 0.28615445184158467, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.20089223716639956, 'min_weight_fraction_leaf': 0.37632960512573244, 'max_features': 'auto', 'min_impurity_decrease': 1.061960871455446e-07, 'validation_fraction': 0.972910080889146, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:51:13,643] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9339388239138908, 'learning_rate': 0.02047893800466072, 'dropout_rate': 0.13700529261902988, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.15653086076945935, 'max_features': 'auto', 'min_impurity_decrease': 4.111554064907662e-07, 'validation_fraction': 0.7097749915557681, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:52:39,561] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8092718106614992, 'learning_rate': 0.012848027091144987, 'dropout_rate': 0.15940696244434913, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.5287591071816778, 'min_weight_fraction_leaf': 0.3460945781028973, 'max_features': None, 'min_impurity_decrease': 1.8112895315979708e-07, 'validation_fraction': 0.829722204894956, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:53:21,782] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9977186683667504, 'learning_rate': 0.01643691937471203, 'dropout_rate': 0.20449130533664522, 'n_estimators': 320, 'criterion': 'squared_error', 'ccp_alpha': 1.1534394935007504, 'min_weight_fraction_leaf': 0.2624568767275207, 'max_features': 'auto', 'min_impurity_decrease': 7.285380226858245e-07, 'validation_fraction': 0.8859493848449271, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:54:28,584] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.8920180078912573, 'learning_rate': 0.007122869439923404, 'dropout_rate': 0.2476081212796895, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.23445311086406953, 'min_weight_fraction_leaf': 0.36640706900902675, 'max_features': 'sqrt', 'min_impurity_decrease': 2.5193561901399193e-07, 'validation_fraction': 0.9493589395358732, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:55:13,466] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.5871103815942053, 'learning_rate': 0.0037494845817999545, 'dropout_rate': 0.5230918657019101, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8438259888659008, 'min_weight_fraction_leaf': 0.22249763456163346, 'max_features': 'auto', 'min_impurity_decrease': 5.893818707257488e-07, 'validation_fraction': 0.8065637998747761, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 12 with value: 0.7476370623899082.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7863849765258216
[I 2024-04-16 03:56:48,771] Trial 89 finished with value: 0.7512822268569335 and parameters: {'subsample': 0.7639525884887477, 'learning_rate': 0.03173728343640762, 'dropout_rate': 0.10424287148225743, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.0188293664905176, 'min_weight_fraction_leaf': 0.3120175734494814, 'max_features': 'auto', 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.652629801149938, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:58:24,924] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.7599739144747745, 'learning_rate': 0.04036726707699087, 'dropout_rate': 0.12975357632977724, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.5654718194151017, 'min_weight_fraction_leaf': 0.30261730053217684, 'max_features': 'auto', 'min_impurity_decrease': 1.4263141271201017e-07, 'validation_fraction': 0.628629705058674, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7863849765258216
[I 2024-04-16 03:59:56,617] Trial 91 finished with value: 0.7447871993292365 and parameters: {'subsample': 0.7214368083611578, 'learning_rate': 0.026113366646528753, 'dropout_rate': 0.10126967325345793, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.03819290033816998, 'min_weight_fraction_leaf': 0.28864883630713, 'max_features': 'auto', 'min_impurity_decrease': 3.6226453630013443e-07, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:01:34,043] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.6808030227437264, 'learning_rate': 0.03131724401005454, 'dropout_rate': 0.10091914470074144, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.2757962185828937, 'min_weight_fraction_leaf': 0.29035183308664614, 'max_features': 'auto', 'min_impurity_decrease': 1.0024255068481983e-07, 'validation_fraction': 0.554998181143127, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7816901408450704
[I 2024-04-16 04:03:02,783] Trial 93 finished with value: 0.7511010167936929 and parameters: {'subsample': 0.7132864327094246, 'learning_rate': 0.02549990552696341, 'dropout_rate': 0.12194257773957672, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.047072876702360524, 'min_weight_fraction_leaf': 0.30715990407955346, 'max_features': 'auto', 'min_impurity_decrease': 1.803390499665587e-07, 'validation_fraction': 0.48997061894680816, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 17}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:04:34,909] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.6536628953873999, 'learning_rate': 0.03319174822229316, 'dropout_rate': 0.11894154469368327, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.443541827074434, 'min_weight_fraction_leaf': 0.3074067892716564, 'max_features': 'auto', 'min_impurity_decrease': 1.9024809738543997e-07, 'validation_fraction': 0.45558082735556127, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 17}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:05:51,683] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.7150900106796909, 'learning_rate': 0.028224413465146942, 'dropout_rate': 0.15247106201453, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.7737335259813289, 'min_weight_fraction_leaf': 0.27370655050516296, 'max_features': 'auto', 'min_impurity_decrease': 2.9882674622106415e-07, 'validation_fraction': 0.49617319899841605, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 14}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:07:14,021] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.6972920587046472, 'learning_rate': 0.02673446336745923, 'dropout_rate': 0.1723932907588553, 'n_estimators': 461, 'criterion': 'friedman_mse', 'ccp_alpha': 6.529680928658118, 'min_weight_fraction_leaf': 0.2533586538964265, 'max_features': 'auto', 'min_impurity_decrease': 1.2855856079888391e-07, 'validation_fraction': 0.5302087266687322, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 16}. Best is trial 89 with value: 0.7512822268569335.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 04:08:49,862] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.7710238807463037, 'learning_rate': 0.0354485400473523, 'dropout_rate': 0.11313799233343443, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.32699666489884094, 'max_features': 1, 'min_impurity_decrease': 1.9355982129496465e-07, 'validation_fraction': 0.39482281992882556, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.6299019607843137
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6455399061032864
[I 2024-04-16 04:09:52,475] Trial 98 finished with value: 0.5963070702924195 and parameters: {'subsample': 0.6146822333144227, 'learning_rate': 0.023565296893826033, 'dropout_rate': 0.1348865425080738, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.18579735183893453, 'min_weight_fraction_leaf': 0.2877050540408782, 'max_features': 'auto', 'min_impurity_decrease': 1.0233080267147593e-06, 'validation_fraction': 0.6694877968157132, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 89 with value: 0.7512822268569335.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-16 04:11:24,251] A new study created in memory with name: no-name-e8de943f-f29b-4fd3-a2fe-492e31ba0d38

Fold 5 C-index: 0.5
[I 2024-04-16 04:11:24,227] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.7405842022057684, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.10216550214025771, 'n_estimators': 496, 'criterion': 'squared_error', 'ccp_alpha': 1.0605262665238058, 'min_weight_fraction_leaf': 0.3103248511879828, 'max_features': 0.1, 'min_impurity_decrease': 3.645248963438711e-07, 'validation_fraction': 0.4628358665835832, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 89 with value: 0.7512822268569335.


* Best trial for C-index:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.7512822268569335], datetime_start=datetime.datetime(2024, 4, 16, 3, 55, 13, 487127), datetime_complete=datetime.datetime(2024, 4, 16, 3, 56, 48, 770122), params={'subsample': 0.7639525884887477, 'learning_rate': 0.03173728343640762, 'dropout_rate': 0.10424287148225743, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.0188293664905176, 'min_weight_fraction_leaf': 0.3120175734494814, 'max_features': 'auto', 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.652629801149938, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=89, value=None)


* Best Score for C-index:
 0.7512822268569335

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:11:45,256] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:11:57,027] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:12:10,613] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:12:30,749] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:12:38,276] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:12:40,401] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:13:00,903] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:13:06,549] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:13:07,280] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.2126622573215235
Fold 2 IBS: 0.21992988889085427
Fold 3 IBS: 0.20365400515110998
Fold 4 IBS: 0.2237830775914246
Fold 5 IBS: 0.2169728112658951
[I 2024-04-16 04:14:02,253] Trial 9 finished with value: 0.21540040804416147 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21361208429589837
Fold 2 IBS: 0.2211926211265032
Fold 3 IBS: 0.20422163542183314
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21784292940455638
[I 2024-04-16 04:15:26,834] Trial 10 finished with value: 0.21628654622010784 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:16:59,095] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21383044894221342
Fold 2 IBS: 0.22138041390759172
Fold 3 IBS: 0.20446100117247107
Fold 4 IBS: 0.22465634226561815
Fold 5 IBS: 0.21799995311901774
[I 2024-04-16 04:18:15,427] Trial 12 finished with value: 0.2164656318813824 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:18:51,475] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:19:59,208] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:20:59,190] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:21:33,757] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:22:48,012] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:23:29,157] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:23:35,398] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:24:43,496] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.2136819353119561
Fold 2 IBS: 0.22153254169163264
Fold 3 IBS: 0.20438589708295674
Fold 4 IBS: 0.22463609477728466
Fold 5 IBS: 0.21804870032025284
[I 2024-04-16 04:25:59,239] Trial 21 finished with value: 0.21645703383681658 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21301647282500003
Fold 2 IBS: 0.22019379674237288

Fold 3 IBS: 0.2039542897153266
Fold 4 IBS: 0.22400679936177248
Fold 5 IBS: 0.21724019501089953
[I 2024-04-16 04:27:17,361] Trial 22 finished with value: 0.2156823107310743 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:28:19,261] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:29:01,264] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:29:39,692] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:30:22,064] Trial 26 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:30:28,765] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:30:41,070] Trial 28 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:31:31,918] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:32:36,646] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21324867831122796
Fold 2 IBS: 0.2210727702014205
Fold 3 IBS: 0.20416936232206076
Fold 4 IBS: 0.22440972849809465
Fold 5 IBS: 0.2176218000119759
[I 2024-04-16 04:33:44,252] Trial 31 finished with value: 0.21610446786895593 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21259056219107933
Fold 2 IBS: 0.2200452839963651
Fold 3 IBS: 0.20384971770105653
Fold 4 IBS: 0.22467968548983738
Fold 5 IBS: 0.21687846920551446
[I 2024-04-16 04:34:50,498] Trial 32 finished with value: 0.21560874371677058 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:35:29,734] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:36:22,824] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:36:34,211] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:37:25,264] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:37:28,849] Trial 37 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:37:40,970] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:38:24,283] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:38:59,174] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21293335022475482
Fold 2 IBS: 0.21962467829036364
Fold 3 IBS: 0.20383646022644486
Fold 4 IBS: 0.22436879973057128
Fold 5 IBS: 0.21687343009620755
[I 2024-04-16 04:40:14,848] Trial 41 finished with value: 0.21552734371366844 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.2128434949348226
Fold 2 IBS: 0.2197445281669847
Fold 3 IBS: 0.20380236718655756
Fold 4 IBS: 0.22423310371920208
Fold 5 IBS: 0.21682812934715617
[I 2024-04-16 04:41:30,950] Trial 42 finished with value: 0.21549032467094462 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:42:52,518] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:44:04,424] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:44:28,245] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.2131511704392072
Fold 2 IBS: 0.2205714992279961
Fold 3 IBS: 0.20398082608566667
Fold 4 IBS: 0.22408999167048244
Fold 5 IBS: 0.21751788644616954
[I 2024-04-16 04:45:39,773] Trial 46 finished with value: 0.21586227477390438 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:46:05,698] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:46:06,020] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:46:23,265] Trial 49 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:46:57,919] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.2128936887525744
Fold 2 IBS: 0.2201021120058267
Fold 3 IBS: 0.20381433864634468
Fold 4 IBS: 0.2237371941204276
Fold 5 IBS: 0.2169599561547686
[I 2024-04-16 04:48:07,277] Trial 51 finished with value: 0.2155014579359884 and parameters: {'subsample': 0.7654204482217829, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.16919816074383062, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288631843664816, 'min_weight_fraction_leaf': 0.1689933524541079, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0415032179614574e-06, 'validation_fraction': 0.8197275960031745, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21347836828226838
Fold 2 IBS: 0.22090352752413928
Fold 3 IBS: 0.20418762602022425
Fold 4 IBS: 0.22421086713506475
Fold 5 IBS: 0.21762718735367084
[I 2024-04-16 04:49:03,683] Trial 52 finished with value: 0.2160815152630735 and parameters: {'subsample': 0.5053435062182351, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.036600491313384984, 'min_weight_fraction_leaf': 0.17248176220266245, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6630249663545005e-06, 'validation_fraction': 0.7333914400675312, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:50:11,602] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4631663309031124, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.15315671922192206, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.19064788811176675, 'max_features': 'sqrt', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:50:28,922] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9017461575502412, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.8266353856620614, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.09319645554340197, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01937053717718396, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:51:18,473] Trial 55 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.20419816136861105, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 1.5125790196698774, 'min_weight_fraction_leaf': 0.21953014805517473, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.9659902853562541, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:51:57,110] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.2887765610954624, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23996644019536584, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.1313980673113705, 'max_features': 'auto', 'min_impurity_decrease': 4.350989437370722e-07, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:52:34,090] Trial 57 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6446884806787394, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5891903890315894, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.20021426582615917, 'max_features': 1, 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.8789871257745913, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 1}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:53:19,298] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9579507989353487, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.37031334062735055, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.2892805623291713, 'max_features': 'auto', 'min_impurity_decrease': 1.1543063953853995e-06, 'validation_fraction': 0.8234456145260549, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:53:56,006] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7291830079861774, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.3259416667709019, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.15797670971031227, 'max_features': 0.1, 'min_impurity_decrease': 2.556545341406747e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:55:01,711] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8610396134059503, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.10121382681282606, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6172084806681395e-06, 'validation_fraction': 0.7207277422863438, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21318278956820846
Fold 2 IBS: 0.22059635338255584
Fold 3 IBS: 0.20400443758354048
Fold 4 IBS: 0.22407950431510054
Fold 5 IBS: 0.21751964874712099
[I 2024-04-16 04:56:00,862] Trial 61 finished with value: 0.21587654671930526 and parameters: {'subsample': 0.793547371538957, 'learning_rate': 0.007879497950871669, 'dropout_rate': 0.1821518797890488, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.15642403295274038, 'max_features': 'sqrt', 'min_impurity_decrease': 9.882732394296688e-07, 'validation_fraction': 0.8276127057468522, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-16 04:56:53,331] Trial 62 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7797256328740491, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.13598930179576962, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.30303680983206904, 'min_weight_fraction_leaf': 0.1446235360050935, 'max_features': 'sqrt', 'min_impurity_decrease': 1.4865063577465509e-06, 'validation_fraction': 0.8523008424522974, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 3}. Best is trial 9 with value: 0.21540040804416147.
Fold 1 IBS: 0.21172675553106307
Fold 2 IBS: 0.21820210514413754
Fold 3 IBS: 0.20294148936096745
Fold 4 IBS: 0.22241818339172176
Fold 5 IBS: 0.21583035134803544
[I 2024-04-16 04:57:55,447] Trial 63 finished with value: 0.21422377695518507 and parameters: {'subsample': 0.692943712947337, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.17342319762993127, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.018273771249527872, 'min_weight_fraction_leaf': 0.22065906606210625, 'max_features': 'sqrt', 'min_impurity_decrease': 4.701162926978375e-07, 'validation_fraction': 0.9637568180927849, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 63 with value: 0.21422377695518507.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:58:51,214] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5929610408366162, 'learning_rate': 0.018936131124414023, 'dropout_rate': 0.2752721072737339, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.21641604442433082, 'max_features': 'log2', 'min_impurity_decrease': 5.301233747286273e-07, 'validation_fraction': 0.9558565998681479, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 63 with value: 0.21422377695518507.
Fold 1 IBS: 0.21242621876516282
Fold 2 IBS: 0.21947395270158115
Fold 3 IBS: 0.20357457643416324
Fold 4 IBS: 0.22311281266743388
Fold 5 IBS: 0.21652251929831706
[I 2024-04-16 04:59:36,820] Trial 65 finished with value: 0.21502201597333165 and parameters: {'subsample': 0.6875174527450749, 'learning_rate': 0.012023060911592005, 'dropout_rate': 0.22795240768926875, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.002725697901156024, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'sqrt', 'min_impurity_decrease': 3.55046666349273e-07, 'validation_fraction': 0.97604137777707, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 63 with value: 0.21422377695518507.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:00:14,711] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5392724474754766, 'learning_rate': 0.01461816521127875, 'dropout_rate': 0.22076051954616932, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.8099144041738244, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1843050264198749e-07, 'validation_fraction': 0.9678192460592685, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 63 with value: 0.21422377695518507.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:01:01,557] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.680855021230625, 'learning_rate': 0.004919883070534993, 'dropout_rate': 0.17168408254323692, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 1.1816384768705075, 'min_weight_fraction_leaf': 0.34044765865690435, 'max_features': 'sqrt', 'min_impurity_decrease': 3.64223716991965e-07, 'validation_fraction': 0.8999244727163287, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 63 with value: 0.21422377695518507.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:01:58,886] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.631241891272345, 'learning_rate': 0.02020874707209061, 'dropout_rate': 0.1336766605116729, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.41011501927208094, 'min_weight_fraction_leaf': 0.24647880871939204, 'max_features': 'sqrt', 'min_impurity_decrease': 6.322991940675055e-05, 'validation_fraction': 0.9998887733080241, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 63 with value: 0.21422377695518507.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:02:47,849] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7135254180093732, 'learning_rate': 0.012248299332324651, 'dropout_rate': 0.19754284273790385, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 8.536647141347391, 'min_weight_fraction_leaf': 0.06312724514848703, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7045057168188712e-07, 'validation_fraction': 0.8826997574671581, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 63 with value: 0.21422377695518507.
Fold 1 IBS: 0.21002762309586814
Fold 2 IBS: 0.21654985625637382
Fold 3 IBS: 0.20035870999918015
Fold 4 IBS: 0.2209570730406635
Fold 5 IBS: 0.2139292417680387
[I 2024-04-16 05:03:14,896] Trial 70 finished with value: 0.21236450083202488 and parameters: {'subsample': 0.6697553991712434, 'learning_rate': 0.04108545825236161, 'dropout_rate': 0.157870754346634, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 0.01008607715535667, 'min_weight_fraction_leaf': 0.36010549235644373, 'max_features': 'sqrt', 'min_impurity_decrease': 6.020485734459976e-07, 'validation_fraction': 0.9226664131821254, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17}. Best is trial 70 with value: 0.21236450083202488.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:03:39,388] Trial 71 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6693819637756059, 'learning_rate': 0.05614284288525828, 'dropout_rate': 0.15702034457154107, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 0.3433049873026723, 'min_weight_fraction_leaf': 0.40287687493722335, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2517278890323607e-07, 'validation_fraction': 0.923069188536789, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 18}. Best is trial 70 with value: 0.21236450083202488.
Fold 1 IBS: 0.20781742008539436
Fold 2 IBS: 0.21478974076980414
Fold 3 IBS: 0.20089208648504095
Fold 4 IBS: 0.2191441985610538
Fold 5 IBS: 0.21190721530207055
[I 2024-04-16 05:03:55,818] Trial 72 finished with value: 0.21091013224067273 and parameters: {'subsample': 0.579108878367126, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.23378840152554475, 'n_estimators': 253, 'criterion': 'squared_error', 'ccp_alpha': 0.004831107387468772, 'min_weight_fraction_leaf': 0.0015800417965165306, 'max_features': 'sqrt', 'min_impurity_decrease': 6.579953359019444e-07, 'validation_fraction': 0.9731455730491394, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15}. Best is trial 72 with value: 0.21091013224067273.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 05:04:03,003] Trial 73 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.5738428655793422, 'learning_rate': 0.0455181825324083, 'dropout_rate': 0.2708381428022939, 'n_estimators': 178, 'criterion': 'squared_error', 'ccp_alpha': 0.7356197491930363, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'sqrt', 'min_impurity_decrease': 6.58667712639121e-07, 'validation_fraction': 0.972769287060676, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15}. Best is trial 72 with value: 0.21091013224067273.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:04:18,787] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.610489574830858, 'learning_rate': 0.032958214117911146, 'dropout_rate': 0.18551172008521094, 'n_estimators': 246, 'criterion': 'squared_error', 'ccp_alpha': 0.32446200678005266, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': 'sqrt', 'min_impurity_decrease': 5.374331420183998e-07, 'validation_fraction': 0.8012079282588516, 'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 72 with value: 0.21091013224067273.
Fold 1 IBS: 0.20341478093090953
Fold 2 IBS: 0.20718682729697907
Fold 3 IBS: 0.1978641016443405
Fold 4 IBS: 0.21298697167153186
Fold 5 IBS: 0.2050750249968235
[I 2024-04-16 05:04:30,545] Trial 75 finished with value: 0.2053055413081169 and parameters: {'subsample': 0.7502548769009864, 'learning_rate': 0.042720745162224044, 'dropout_rate': 0.1275141855309227, 'n_estimators': 211, 'criterion': 'squared_error', 'ccp_alpha': 0.008881048751772307, 'min_weight_fraction_leaf': 0.0019249398442275649, 'max_features': 'sqrt', 'min_impurity_decrease': 1.4841199014468956e-06, 'validation_fraction': 0.9292395816115496, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 19}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-16 05:04:43,505] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7377433445113766, 'learning_rate': 0.04227508733964815, 'dropout_rate': 0.12054212552469006, 'n_estimators': 227, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 1.519894793077156e-06, 'validation_fraction': 0.7624020372100926, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 19}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:04:50,196] Trial 77 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.5357913465602108, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.311272991332878, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.9488717637120231, 'min_weight_fraction_leaf': 0.016779792096412772, 'max_features': 'sqrt', 'min_impurity_decrease': 3.886076395376554e-06, 'validation_fraction': 0.9332646380443554, 'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 17}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:05:05,525] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.042310590623507095, 'dropout_rate': 0.20493634659141233, 'n_estimators': 258, 'criterion': 'squared_error', 'ccp_alpha': 0.6105960162167562, 'min_weight_fraction_leaf': 0.3605529124352196, 'max_features': 'sqrt', 'min_impurity_decrease': 1.479347670147013e-07, 'validation_fraction': 0.6268100243156249, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 20}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:05:11,677] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6556755894076554, 'learning_rate': 0.04888327282253199, 'dropout_rate': 0.2388558503599949, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 1.2524497244520345, 'min_weight_fraction_leaf': 0.04113224555419862, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8943091429953467e-07, 'validation_fraction': 0.977567066615012, 'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 19}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:05:25,691] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5798764678210022, 'learning_rate': 0.03706720456424117, 'dropout_rate': 0.13589869338601626, 'n_estimators': 209, 'criterion': 'friedman_mse', 'ccp_alpha': 1.6871260135053152, 'min_weight_fraction_leaf': 0.43974848442562914, 'max_features': 'sqrt', 'min_impurity_decrease': 4.368877169617307e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 18}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.20622008274382175
Fold 2 IBS: 0.21185862737506567
Fold 3 IBS: 0.1997629842339375
Fold 4 IBS: 0.21744626779282247
Fold 5 IBS: 0.20967943684166193
[I 2024-04-16 05:05:39,526] Trial 81 finished with value: 0.20899347979746188 and parameters: {'subsample': 0.6260301990571575, 'learning_rate': 0.04319851444329214, 'dropout_rate': 0.16612954129964122, 'n_estimators': 225, 'criterion': 'squared_error', 'ccp_alpha': 0.025430672498214735, 'min_weight_fraction_leaf': 0.06345013344773306, 'max_features': 'sqrt', 'min_impurity_decrease': 8.793833883889345e-07, 'validation_fraction': 0.9436075044523529, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 15}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:05:59,688] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6273390704313797, 'learning_rate': 0.0429969229245396, 'dropout_rate': 0.1765222266353391, 'n_estimators': 273, 'criterion': 'squared_error', 'ccp_alpha': 0.28871114184771784, 'min_weight_fraction_leaf': 0.026852877951295945, 'max_features': 'sqrt', 'min_impurity_decrease': 9.342696243943243e-07, 'validation_fraction': 0.8667986330985562, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 14}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:06:12,857] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7552901824095473, 'learning_rate': 0.03851338582845188, 'dropout_rate': 0.21935952874051431, 'n_estimators': 224, 'criterion': 'squared_error', 'ccp_alpha': 0.6304491263941222, 'min_weight_fraction_leaf': 0.05645786104371703, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9809084585170996e-06, 'validation_fraction': 0.9326957028723006, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 15}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-16 05:06:29,016] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6703992456695949, 'learning_rate': 0.05973265280023778, 'dropout_rate': 0.26306735024272265, 'n_estimators': 246, 'criterion': 'squared_error', 'ccp_alpha': 0.260805512028014, 'min_weight_fraction_leaf': 0.001558043192133509, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3729270104959905e-06, 'validation_fraction': 0.9026414126213622, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 16}. Best is trial 75 with value: 0.2053055413081169.
Fold 1 IBS: 0.19916326632684384
Fold 2 IBS: 0.20154886853126658
Fold 3 IBS: 0.19723439928037215
Fold 4 IBS: 0.21343583293294813
Fold 5 IBS: 0.20218640392034457
[I 2024-04-16 05:06:39,267] Trial 85 finished with value: 0.20271375419835502 and parameters: {'subsample': 0.7143944677204213, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.10222990117299577, 'n_estimators': 198, 'criterion': 'squared_error', 'ccp_alpha': 0.011135358074445665, 'min_weight_fraction_leaf': 0.08015424199560361, 'max_features': None, 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9861365780200455, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 12}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 05:06:48,417] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6309219646788968, 'learning_rate': 0.04612493250081603, 'dropout_rate': 0.12481309430977197, 'n_estimators': 192, 'criterion': 'squared_error', 'ccp_alpha': 0.9972188151587362, 'min_weight_fraction_leaf': 0.0807528630639937, 'max_features': None, 'min_impurity_decrease': 1.380283855102211e-07, 'validation_fraction': 0.9801980106663806, 'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 10}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:07:11,381] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7048418338219802, 'learning_rate': 0.03521531749355734, 'dropout_rate': 0.14357979287175945, 'n_estimators': 295, 'criterion': 'squared_error', 'ccp_alpha': 0.5905565281607869, 'min_weight_fraction_leaf': 0.04900355997010612, 'max_features': None, 'min_impurity_decrease': 2.616222201627108e-07, 'validation_fraction': 0.943754827411582, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:07:17,064] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5987701753734233, 'learning_rate': 0.050213780826442185, 'dropout_rate': 0.1938411005791284, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 0.3180081639828751, 'min_weight_fraction_leaf': 0.01874802778250728, 'max_features': None, 'min_impurity_decrease': 1.0777511909570898e-07, 'validation_fraction': 0.9901236820423219, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 13}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:07:26,747] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6527388011508777, 'learning_rate': 0.040439796125094664, 'dropout_rate': 0.10443260106024366, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.03244081322125107, 'max_features': None, 'min_impurity_decrease': 5.30678441883285e-07, 'validation_fraction': 0.4039382570278104, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:07:46,088] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4802555730928496, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.28853898566939823, 'n_estimators': 322, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.08269727416655862, 'max_features': 1, 'min_impurity_decrease': 3.782489990908363e-07, 'validation_fraction': 0.8833335288417331, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 16}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.20517976258844045
Fold 2 IBS: 0.20951080052148185
Fold 3 IBS: 0.1994802122084956
Fold 4 IBS: 0.2171074748113988
Fold 5 IBS: 0.20946112775306694
[I 2024-04-16 05:07:59,715] Trial 91 finished with value: 0.20814787557657674 and parameters: {'subsample': 0.713484445382553, 'learning_rate': 0.053025153385305904, 'dropout_rate': 0.1621415121924383, 'n_estimators': 217, 'criterion': 'squared_error', 'ccp_alpha': 0.038163834133555535, 'min_weight_fraction_leaf': 0.07192813387619737, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2471607424667414e-07, 'validation_fraction': 0.913183512671589, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 17}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:08:12,011] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7290357428250976, 'learning_rate': 0.062477297818953774, 'dropout_rate': 0.15682456839576192, 'n_estimators': 221, 'criterion': 'squared_error', 'ccp_alpha': 0.19747740396734947, 'min_weight_fraction_leaf': 0.11081081202125179, 'max_features': 'sqrt', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.9121521599081056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 17}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:08:19,384] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6880962324087546, 'learning_rate': 0.053513930147255716, 'dropout_rate': 0.22984961845617088, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.5244391111186764, 'min_weight_fraction_leaf': 0.0740082597172341, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2448140747061408e-07, 'validation_fraction': 0.9573411608656431, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 18}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:08:27,156] Trial 94 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6122283283478056, 'learning_rate': 0.04735664173487125, 'dropout_rate': 0.12125722539723183, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.8483153057933714, 'min_weight_fraction_leaf': 0.012965726304668648, 'max_features': 0.1, 'min_impurity_decrease': 5.320908710593958e-07, 'validation_fraction': 0.8489617069460854, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 20}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.20888981105735194
Fold 2 IBS: 0.2144107956920543
Fold 3 IBS: 0.20110752595433504
Fold 4 IBS: 0.2191317840105306
Fold 5 IBS: 0.213882474433263
[I 2024-04-16 05:08:36,409] Trial 95 finished with value: 0.21148447822950697 and parameters: {'subsample': 0.5696673724290117, 'learning_rate': 0.04367885634168647, 'dropout_rate': 0.19685573714950988, 'n_estimators': 202, 'criterion': 'squared_error', 'ccp_alpha': 0.06872696147782141, 'min_weight_fraction_leaf': 0.05740399978278235, 'max_features': 'sqrt', 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9999725284837788, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 05:08:44,373] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5510219457804204, 'learning_rate': 0.04489966508109901, 'dropout_rate': 0.2517918295115368, 'n_estimators': 198, 'criterion': 'squared_error', 'ccp_alpha': 0.21759271023185817, 'min_weight_fraction_leaf': 0.05723976000311999, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5905901548977565e-07, 'validation_fraction': 0.9695884299099399, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 13}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 05:08:56,130] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5213660085273766, 'learning_rate': 0.040276005178535, 'dropout_rate': 0.20043240961556408, 'n_estimators': 238, 'criterion': 'friedman_mse', 'ccp_alpha': 1.338114196472308, 'min_weight_fraction_leaf': 0.3239725702100567, 'max_features': 'sqrt', 'min_impurity_decrease': 3.227122594103294e-07, 'validation_fraction': 0.9979145301537344, 'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 12}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 05:09:06,106] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5774463052417914, 'learning_rate': 0.03259365818918761, 'dropout_rate': 0.16147536527459164, 'n_estimators': 214, 'criterion': 'squared_error', 'ccp_alpha': 0.5371511633704872, 'min_weight_fraction_leaf': 0.06815145467064293, 'max_features': 'log2', 'min_impurity_decrease': 1.0337833800654106e-07, 'validation_fraction': 0.9131603889834665, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 85 with value: 0.20271375419835502.
Fold 1 IBS: 0.1987094518543999
Fold 2 IBS: 0.20375872099343909

Fold 3 IBS: 0.19654120805549916
Fold 4 IBS: 0.20962124167390286
Fold 5 IBS: 0.20124873409085406
[I 2024-04-16 05:09:23,792] Trial 99 finished with value: 0.201975871333619 and parameters: {'subsample': 0.7090975652007764, 'learning_rate': 0.05019766261164787, 'dropout_rate': 0.10216550214025771, 'n_estimators': 257, 'criterion': 'squared_error', 'ccp_alpha': 0.0045100477558669, 'min_weight_fraction_leaf': 0.09258479081501242, 'max_features': 'sqrt', 'min_impurity_decrease': 8.264881459144936e-07, 'validation_fraction': 0.6748895535913024, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 15}. Best is trial 99 with value: 0.201975871333619.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.201975871333619], datetime_start=datetime.datetime(2024, 4, 16, 5, 9, 6, 115873), datetime_complete=datetime.datetime(2024, 4, 16, 5, 9, 23, 791252), params={'subsample': 0.7090975652007764, 'learning_rate': 0.05019766261164787, 'dropout_rate': 0.10216550214025771, 'n_estimators': 257, 'criterion': 'squared_error', 'ccp_alpha': 0.0045100477558669, 'min_weight_fraction_leaf': 0.09258479081501242, 'max_features': 'sqrt', 'min_impurity_decrease': 8.264881459144936e-07, 'validation_fraction': 0.6748895535913024, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 15}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for IBS:
 0.201975871333619

In [67]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [68]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.751
train_ibs:  0.202

#### Test

In [69]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [70]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0188293664905176,
                                 criterion='squared_error',
                                 dropout_rate=0.10424287148225743,
                                 learning_rate=0.03173728343640762, max_depth=9,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=1.3598537758171917e-07,
                                 min_samples_leaf=11, min_samples_split=17,
                                 min_weight_fraction_leaf=0.3120175734494814,
                                 n_estimators=469, random_state=123,
                                 subsample=0.7639525884887477,
                                 validation_fraction=0.652629801149938)

C-index score: 0.576

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0045100477558669,
                                 criterion='squared_error',
                                 dropout_rate=0.10216550214025771,
                                 learning_rate=0.05019766261164787,
                                 max_depth=15, max_features='sqrt',
                                 max_leaf_nodes=17,
                                 min_impurity_decrease=8.264881459144936e-07,
                                 min_samples_leaf=6, min_samples_split=3,
                                 min_weight_fraction_leaf=0.09258479081501242,
                                 n_estimators=257, random_state=123,
                                 subsample=0.7090975652007764,
                                 validation_fraction=0.6748895535913024)

IBS: 0.217

In [71]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [72]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [73]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 05:09:37,868] A new study created in memory with name: no-name-2cc4e40e-032f-43d3-afd7-cd2c5fbfb160

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:09:38,516] Trial 0 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:09:43,889] Trial 1 finished with value: 0.6915224372703425 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:09:44,974] Trial 2 finished with value: 0.6951295602764356 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6951295602764356.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:09:46,434] Trial 3 finished with value: 0.700470556988902 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:09:48,567] Trial 4 finished with value: 0.6985655664395451 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:09:51,231] Trial 5 finished with value: 0.6866204764860286 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:09:52,426] Trial 6 finished with value: 0.689561652956617 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:09:52,678] Trial 7 finished with value: 0.6989539101188053 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:09:54,155] Trial 8 finished with value: 0.6924614044064927 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:09:58,260] Trial 9 finished with value: 0.6952660705767583 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 05:10:00,984] Trial 10 finished with value: 0.7005703272410927 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.10867980814121556, 'n_estimators': 299, 'learning_rate': 0.09279671898160717}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:10:03,859] Trial 11 finished with value: 0.6969556539693951 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.10580803679784617, 'n_estimators': 318, 'learning_rate': 0.09656492760401554}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 05:10:08,437] Trial 12 finished with value: 0.6996774700982356 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.107083606486404, 'n_estimators': 371, 'learning_rate': 0.09210877537520011}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:10:11,499] Trial 13 finished with value: 0.699453286314607 and parameters: {'subsample': 0.19911958285971598, 'dropout_rate': 0.20951790452982805, 'n_estimators': 296, 'learning_rate': 0.08223799235112043}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:10:12,139] Trial 14 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6961621784434218, 'n_estimators': 102, 'learning_rate': 0.0025916531369806137}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:10:14,199] Trial 15 finished with value: 0.6978294573960153 and parameters: {'subsample': 0.38900149510125237, 'dropout_rate': 0.26628060677168897, 'n_estimators': 230, 'learning_rate': 0.08062057432672834}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:10:19,272] Trial 16 finished with value: 0.7074160176315457 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.20001360320690656, 'n_estimators': 411, 'learning_rate': 0.08820363883892024}. Best is trial 16 with value: 0.7074160176315457.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:10:24,611] Trial 17 finished with value: 0.7047944240501108 and parameters: {'subsample': 0.17085174271948028, 'dropout_rate': 0.25949828021864363, 'n_estimators': 440, 'learning_rate': 0.09772435226236928}. Best is trial 16 with value: 0.7074160176315457.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:10:29,424] Trial 18 finished with value: 0.7073699076382526 and parameters: {'subsample': 0.13920564377019537, 'dropout_rate': 0.32791160693259247, 'n_estimators': 430, 'learning_rate': 0.08531512033723122}. Best is trial 16 with value: 0.7074160176315457.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:10:34,278] Trial 19 finished with value: 0.7066211110613226 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.34721836740782674, 'n_estimators': 401, 'learning_rate': 0.08684988472507524}. Best is trial 16 with value: 0.7074160176315457.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:10:38,341] Trial 20 finished with value: 0.6970806608190854 and parameters: {'subsample': 0.30794140712521173, 'dropout_rate': 0.5777838682216713, 'n_estimators': 420, 'learning_rate': 0.06551866052750378}. Best is trial 16 with value: 0.7074160176315457.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:10:42,262] Trial 21 finished with value: 0.7075064179385753 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.34554217275710253, 'n_estimators': 382, 'learning_rate': 0.08197456727164983}. Best is trial 21 with value: 0.7075064179385753.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 05:10:45,744] Trial 22 finished with value: 0.7075600781974729 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.32828508242025334, 'n_estimators': 353, 'learning_rate': 0.08119823176270143}. Best is trial 22 with value: 0.7075600781974729.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:10:48,939] Trial 23 finished with value: 0.6994727923260585 and parameters: {'subsample': 0.22021061983459486, 'dropout_rate': 0.42243343078237217, 'n_estimators': 349, 'learning_rate': 0.0774943612743643}. Best is trial 22 with value: 0.7075600781974729.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:10:53,220] Trial 24 finished with value: 0.7083964097884085 and parameters: {'subsample': 0.1003062325172735, 'dropout_rate': 0.19012024616538375, 'n_estimators': 388, 'learning_rate': 0.09951021992091309}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:10:57,210] Trial 25 finished with value: 0.6995459585964079 and parameters: {'subsample': 0.27977547818030657, 'dropout_rate': 0.2983353088901004, 'n_estimators': 343, 'learning_rate': 0.09940034344567995}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:11:02,350] Trial 26 finished with value: 0.6988173998184827 and parameters: {'subsample': 0.36213172886276845, 'dropout_rate': 0.20162626963644442, 'n_estimators': 375, 'learning_rate': 0.04334229078151381}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:11:06,488] Trial 27 finished with value: 0.7004873387303673 and parameters: {'subsample': 0.21032309919779046, 'dropout_rate': 0.9861686560685959, 'n_estimators': 456, 'learning_rate': 0.06181261096505867}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:11:08,937] Trial 28 finished with value: 0.70748963619711 and parameters: {'subsample': 0.15162731096574183, 'dropout_rate': 0.4669560307696445, 'n_estimators': 279, 'learning_rate': 0.07167326611869856}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:11:12,472] Trial 29 finished with value: 0.6985655664395451 and parameters: {'subsample': 0.24911505406242038, 'dropout_rate': 0.352401474207872, 'n_estimators': 323, 'learning_rate': 0.09155977690686619}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:11:16,734] Trial 30 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.6518308083993644, 'dropout_rate': 0.3892024351052794, 'n_estimators': 394, 'learning_rate': 0.07795052447670538}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:11:19,205] Trial 31 finished with value: 0.703765508902146 and parameters: {'subsample': 0.15495471297924188, 'dropout_rate': 0.507217270567623, 'n_estimators': 270, 'learning_rate': 0.07086435013358193}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:11:21,559] Trial 32 finished with value: 0.7072967413679033 and parameters: {'subsample': 0.10563060399701435, 'dropout_rate': 0.5988434987978708, 'n_estimators': 284, 'learning_rate': 0.05969102100690944}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:11:24,651] Trial 33 finished with value: 0.7074406609107929 and parameters: {'subsample': 0.16420935289576255, 'dropout_rate': 0.46097365529123796, 'n_estimators': 324, 'learning_rate': 0.06848184893462936}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:11:26,705] Trial 34 finished with value: 0.6978708824167279 and parameters: {'subsample': 0.3190070374155396, 'dropout_rate': 0.42347275266168155, 'n_estimators': 246, 'learning_rate': 0.0737579698125586}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:11:30,554] Trial 35 finished with value: 0.6985655664395451 and parameters: {'subsample': 0.22096763477060216, 'dropout_rate': 0.5116681609427478, 'n_estimators': 384, 'learning_rate': 0.08129167893680202}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:11:38,354] Trial 36 finished with value: 0.6979735179619425 and parameters: {'subsample': 0.43092545164422086, 'dropout_rate': 0.30428761097278945, 'n_estimators': 497, 'learning_rate': 0.08793239753187249}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:11:39,614] Trial 37 finished with value: 0.7066135607957181 and parameters: {'subsample': 0.1399382342907446, 'dropout_rate': 0.1930342824710988, 'n_estimators': 155, 'learning_rate': 0.07555947765367145}. Best is trial 24 with value: 0.7083964097884085.

Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:11:42,886] Trial 38 finished with value: 0.695248836540078 and parameters: {'subsample': 0.2711106835858654, 'dropout_rate': 0.6515731633509281, 'n_estimators': 342, 'learning_rate': 0.06766859442184275}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:11:48,196] Trial 39 finished with value: 0.7012361353072973 and parameters: {'subsample': 0.1899832825436063, 'dropout_rate': 0.7545555141153719, 'n_estimators': 460, 'learning_rate': 0.05598015324329953}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:11:50,531] Trial 40 finished with value: 0.6995776998460449 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.1585668555692103, 'n_estimators': 251, 'learning_rate': 0.09387139898717081}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:11:53,603] Trial 41 finished with value: 0.7030604093207 and parameters: {'subsample': 0.1591303684395594, 'dropout_rate': 0.44774151196520373, 'n_estimators': 310, 'learning_rate': 0.0696751921300793}. Best is trial 24 with value: 0.7083964097884085.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:11:57,533] Trial 42 finished with value: 0.7100870387945125 and parameters: {'subsample': 0.13703446663684343, 'dropout_rate': 0.46441307244593527, 'n_estimators': 342, 'learning_rate': 0.06554863987210734}. Best is trial 42 with value: 0.7100870387945125.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:12:01,435] Trial 43 finished with value: 0.7064942845320757 and parameters: {'subsample': 0.1251840133686262, 'dropout_rate': 0.3836769535493768, 'n_estimators': 357, 'learning_rate': 0.06377251858545947}. Best is trial 42 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:12:01,566] Trial 44 finished with value: 0.6836793000154404 and parameters: {'subsample': 0.24976343237158286, 'dropout_rate': 0.5020020877800176, 'n_estimators': 3, 'learning_rate': 0.04450424844427492}. Best is trial 42 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:12:04,944] Trial 45 finished with value: 0.703765508902146 and parameters: {'subsample': 0.19438769521144972, 'dropout_rate': 0.295844522167053, 'n_estimators': 284, 'learning_rate': 0.0838153822258107}. Best is trial 42 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:12:08,773] Trial 46 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.7988464910663153, 'dropout_rate': 0.5457035825957337, 'n_estimators': 386, 'learning_rate': 0.055039080701147665}. Best is trial 42 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:12:12,645] Trial 47 finished with value: 0.6967193734168816 and parameters: {'subsample': 0.31878416095186135, 'dropout_rate': 0.23961931471348202, 'n_estimators': 331, 'learning_rate': 0.0733567368946923}. Best is trial 42 with value: 0.7100870387945125.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:12:16,762] Trial 48 finished with value: 0.7101038205359779 and parameters: {'subsample': 0.1004172298398558, 'dropout_rate': 0.42954172343750424, 'n_estimators': 366, 'learning_rate': 0.018199888637109668}. Best is trial 48 with value: 0.7101038205359779.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:12:22,262] Trial 49 finished with value: 0.7118405595353751 and parameters: {'subsample': 0.10839247716960626, 'dropout_rate': 0.4148160175378507, 'n_estimators': 443, 'learning_rate': 0.00524351186486742}. Best is trial 49 with value: 0.7118405595353751.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:12:27,529] Trial 50 finished with value: 0.7005875612777729 and parameters: {'subsample': 0.2383039508065598, 'dropout_rate': 0.4268777031143342, 'n_estimators': 438, 'learning_rate': 0.009175995739004631}. Best is trial 49 with value: 0.7118405595353751.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:12:33,456] Trial 51 finished with value: 0.707528336947836 and parameters: {'subsample': 0.10379732140728655, 'dropout_rate': 0.3819296290232555, 'n_estimators': 479, 'learning_rate': 0.016769783329425858}. Best is trial 49 with value: 0.7118405595353751.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:12:39,856] Trial 52 finished with value: 0.6993582010349968 and parameters: {'subsample': 0.18125415739724074, 'dropout_rate': 0.3883878855164189, 'n_estimators': 475, 'learning_rate': 0.017226968179982278}. Best is trial 49 with value: 0.7118405595353751.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:12:44,723] Trial 53 finished with value: 0.7073479886289918 and parameters: {'subsample': 0.1403016617848029, 'dropout_rate': 0.4869631469548196, 'n_estimators': 413, 'learning_rate': 0.02533961737383027}. Best is trial 49 with value: 0.7118405595353751.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:12:51,154] Trial 54 finished with value: 0.7071578180697715 and parameters: {'subsample': 0.11916465106129585, 'dropout_rate': 0.1506646479052033, 'n_estimators': 486, 'learning_rate': 0.0027062199623674923}. Best is trial 49 with value: 0.7118405595353751.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:12:57,740] Trial 55 finished with value: 0.7039993764568503 and parameters: {'subsample': 0.17942294123686497, 'dropout_rate': 0.24095594349460925, 'n_estimators': 456, 'learning_rate': 0.009598179429519177}. Best is trial 49 with value: 0.7118405595353751.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:13:02,306] Trial 56 finished with value: 0.7126844413919151 and parameters: {'subsample': 0.11004058121439181, 'dropout_rate': 0.3170885754967726, 'n_estimators': 364, 'learning_rate': 0.017271336468030765}. Best is trial 56 with value: 0.7126844413919151.

Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:13:06,790] Trial 57 finished with value: 0.6988098495528781 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.3157297807712154, 'n_estimators': 409, 'learning_rate': 0.037166660584215444}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:13:10,395] Trial 58 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.8995542733815092, 'dropout_rate': 0.5896570998286765, 'n_estimators': 360, 'learning_rate': 0.019055712004307324}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:13:15,593] Trial 59 finished with value: 0.6996947041349157 and parameters: {'subsample': 0.2167102263492233, 'dropout_rate': 0.4219377956209893, 'n_estimators': 427, 'learning_rate': 0.00964292476367798}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:18,586] Trial 60 finished with value: 0.7089603140969511 and parameters: {'subsample': 0.13430262452064712, 'dropout_rate': 0.2719187825939736, 'n_estimators': 302, 'learning_rate': 0.02977519290114758}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:21,172] Trial 61 finished with value: 0.7099407062538139 and parameters: {'subsample': 0.12976714617687563, 'dropout_rate': 0.26035445276891556, 'n_estimators': 303, 'learning_rate': 0.027487028337491424}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:23,852] Trial 62 finished with value: 0.7047188447819523 and parameters: {'subsample': 0.14587415213142532, 'dropout_rate': 0.2808215562660019, 'n_estimators': 310, 'learning_rate': 0.026561813552234723}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:27,349] Trial 63 finished with value: 0.7029872430503505 and parameters: {'subsample': 0.1764686468513155, 'dropout_rate': 0.2402990576816543, 'n_estimators': 303, 'learning_rate': 0.030451868909265233}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:32,458] Trial 64 finished with value: 0.7055627266384924 and parameters: {'subsample': 0.140704292404385, 'dropout_rate': 0.17510254334925499, 'n_estimators': 369, 'learning_rate': 0.02104610784121672}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:34,167] Trial 65 finished with value: 0.7028945707685494 and parameters: {'subsample': 0.20071753863807137, 'dropout_rate': 0.13283899373874214, 'n_estimators': 204, 'learning_rate': 0.013751188744788019}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:37,915] Trial 66 finished with value: 0.7038968819346731 and parameters: {'subsample': 0.1340712660098652, 'dropout_rate': 0.22203089715473467, 'n_estimators': 332, 'learning_rate': 0.03588851435237967}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:13:43,120] Trial 67 finished with value: 0.6996947041349157 and parameters: {'subsample': 0.23804418258049242, 'dropout_rate': 0.2726742448788483, 'n_estimators': 395, 'learning_rate': 0.02922455425136813}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:13:46,783] Trial 68 finished with value: 0.7101038205359779 and parameters: {'subsample': 0.10342000793284072, 'dropout_rate': 0.35910796186561394, 'n_estimators': 371, 'learning_rate': 0.004273056088458481}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:13:49,636] Trial 69 finished with value: 0.7045362244883366 and parameters: {'subsample': 0.16883209613150935, 'dropout_rate': 0.36024381851697507, 'n_estimators': 257, 'learning_rate': 0.00496593037049949}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:51,751] Trial 70 finished with value: 0.7119014905675394 and parameters: {'subsample': 0.13024849715167272, 'dropout_rate': 0.3300007443740935, 'n_estimators': 225, 'learning_rate': 0.005698621542185112}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:53,902] Trial 71 finished with value: 0.7100552975448757 and parameters: {'subsample': 0.13170555425218272, 'dropout_rate': 0.33353305446938153, 'n_estimators': 238, 'learning_rate': 0.005163036601524486}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:13:55,972] Trial 72 finished with value: 0.7090795903605935 and parameters: {'subsample': 0.11492318606593618, 'dropout_rate': 0.3333736301879982, 'n_estimators': 228, 'learning_rate': 0.006201935034604303}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:13:57,459] Trial 73 finished with value: 0.7003512807252594 and parameters: {'subsample': 0.21114691697535828, 'dropout_rate': 0.3635610485183579, 'n_estimators': 185, 'learning_rate': 0.013099217086797685}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:13:59,512] Trial 74 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.5382812555221466, 'dropout_rate': 0.4091088026352, 'n_estimators': 230, 'learning_rate': 0.0013879487154421352}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:00,638] Trial 75 finished with value: 0.7080455379448333 and parameters: {'subsample': 0.16669975135727025, 'dropout_rate': 0.4620315789464893, 'n_estimators': 148, 'learning_rate': 0.013105164586959851}. Best is trial 56 with value: 0.7126844413919151.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:14:03,204] Trial 76 finished with value: 0.7091699906676232 and parameters: {'subsample': 0.1247312399263396, 'dropout_rate': 0.33187678412738364, 'n_estimators': 270, 'learning_rate': 0.00651881377128646}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:14:06,139] Trial 77 finished with value: 0.7089845050809835 and parameters: {'subsample': 0.10014730057619756, 'dropout_rate': 0.5302187590665071, 'n_estimators': 342, 'learning_rate': 0.004513850820377264}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:08,146] Trial 78 finished with value: 0.7029872430503505 and parameters: {'subsample': 0.1575211577304117, 'dropout_rate': 0.4362562079493504, 'n_estimators': 239, 'learning_rate': 0.02298754828076891}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:09,984] Trial 79 finished with value: 0.7012170815910602 and parameters: {'subsample': 0.1947691453333329, 'dropout_rate': 0.4059887532370735, 'n_estimators': 219, 'learning_rate': 0.011377463957427975}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:14:13,086] Trial 80 finished with value: 0.6951709852971482 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.36094300425805653, 'n_estimators': 286, 'learning_rate': 0.01714916766769374}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:14:16,642] Trial 81 finished with value: 0.7091699906676232 and parameters: {'subsample': 0.11922040800547168, 'dropout_rate': 0.3092845543353835, 'n_estimators': 261, 'learning_rate': 0.007571831646519823}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:19,556] Trial 82 finished with value: 0.7091624404020186 and parameters: {'subsample': 0.12729624128137862, 'dropout_rate': 0.3428262753886999, 'n_estimators': 273, 'learning_rate': 0.007190506751878746}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:24,061] Trial 83 finished with value: 0.7021214421845497 and parameters: {'subsample': 0.15953886992491265, 'dropout_rate': 0.3184729094514102, 'n_estimators': 370, 'learning_rate': 0.014900814930854623}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:14:27,425] Trial 84 finished with value: 0.7023628600048587 and parameters: {'subsample': 0.23032995014965402, 'dropout_rate': 0.3712075934851208, 'n_estimators': 316, 'learning_rate': 0.003769747147177719}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:14:30,258] Trial 85 finished with value: 0.6979003516915931 and parameters: {'subsample': 0.3499070610936068, 'dropout_rate': 0.29061116023478994, 'n_estimators': 290, 'learning_rate': 0.010753340024941287}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:14:31,717] Trial 86 finished with value: 0.6885812607997542 and parameters: {'subsample': 0.6711178801487496, 'dropout_rate': 0.40044433994893036, 'n_estimators': 190, 'learning_rate': 0.0013305970519246419}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:14:33,936] Trial 87 finished with value: 0.7083480278203439 and parameters: {'subsample': 0.12423005150639038, 'dropout_rate': 0.340162162959039, 'n_estimators': 244, 'learning_rate': 0.021012506022157595}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:14:35,249] Trial 88 finished with value: 0.6979169924100208 and parameters: {'subsample': 0.26071699628810074, 'dropout_rate': 0.44977747836430715, 'n_estimators': 171, 'learning_rate': 0.006469007458902873}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 05:14:36,920] Trial 89 finished with value: 0.7065479447909733 and parameters: {'subsample': 0.1006267636405256, 'dropout_rate': 0.47930899246048, 'n_estimators': 213, 'learning_rate': 0.048254594751542076}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 05:14:40,069] Trial 90 finished with value: 0.7057822254495406 and parameters: {'subsample': 0.1868366649070135, 'dropout_rate': 0.21910224125856817, 'n_estimators': 335, 'learning_rate': 0.011743041008338503}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:14:42,236] Trial 91 finished with value: 0.7091699906676232 and parameters: {'subsample': 0.12384390667406053, 'dropout_rate': 0.31138579087364465, 'n_estimators': 271, 'learning_rate': 0.007942716844929441}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:44,277] Trial 92 finished with value: 0.7055627266384924 and parameters: {'subsample': 0.15217943218245938, 'dropout_rate': 0.2508862128799094, 'n_estimators': 259, 'learning_rate': 0.008111193086381932}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 05:14:46,372] Trial 93 finished with value: 0.7091699906676232 and parameters: {'subsample': 0.12137029682502766, 'dropout_rate': 0.3264795301295895, 'n_estimators': 264, 'learning_rate': 0.005043029955105829}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:49,927] Trial 94 finished with value: 0.7055627266384924 and parameters: {'subsample': 0.15001897852814466, 'dropout_rate': 0.30119061111436196, 'n_estimators': 353, 'learning_rate': 0.0023899341701148578}. Best is trial 56 with value: 0.7126844413919151.

Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:14:53,526] Trial 95 finished with value: 0.6993582010349968 and parameters: {'subsample': 0.17767376928641182, 'dropout_rate': 0.3947448823441918, 'n_estimators': 378, 'learning_rate': 0.015358230665555719}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:14:56,590] Trial 96 finished with value: 0.7081820482451558 and parameters: {'subsample': 0.1269813903392837, 'dropout_rate': 0.26567115050913775, 'n_estimators': 320, 'learning_rate': 0.011191614413700042}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:15:01,703] Trial 97 finished with value: 0.6986094044580667 and parameters: {'subsample': 0.1988660333024171, 'dropout_rate': 0.3731852725656812, 'n_estimators': 402, 'learning_rate': 0.020518434486899283}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 05:15:04,205] Trial 98 finished with value: 0.7072943283700942 and parameters: {'subsample': 0.14093930255748632, 'dropout_rate': 0.3504935888024146, 'n_estimators': 295, 'learning_rate': 0.007104435402372574}. Best is trial 56 with value: 0.7126844413919151.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697

[I 2024-04-16 05:15:05,788] A new study created in memory with name: no-name-523502f6-14e8-48c6-bb25-3251e9283c4e

Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 05:15:05,773] Trial 99 finished with value: 0.7062407699428821 and parameters: {'subsample': 0.10067607915823903, 'dropout_rate': 0.8459565404966409, 'n_estimators': 240, 'learning_rate': 0.01852997613975714}. Best is trial 56 with value: 0.7126844413919151.


* Best trial for C-index:
 FrozenTrial(number=56, state=TrialState.COMPLETE, values=[0.7126844413919151], datetime_start=datetime.datetime(2024, 4, 16, 5, 12, 57, 792103), datetime_complete=datetime.datetime(2024, 4, 16, 5, 13, 2, 305853), params={'subsample': 0.11004058121439181, 'dropout_rate': 0.3170885754967726, 'n_estimators': 364, 'learning_rate': 0.017271336468030765}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=56, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11004058121439181, 'dropout_rate': 0.3170885754967726, 'n_estimators': 364, 'learning_rate': 0.017271336468030765}


* Best Score for C-index:
 0.7126844413919151

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24692977896599883
Fold 2 IBS: 0.23367124240111953
Fold 3 IBS: 0.18592983540335206
Fold 4 IBS: 0.2632765971484762
Fold 5 IBS: 0.2101930209796324
[I 2024-04-16 05:15:06,538] Trial 0 finished with value: 0.2280000949797158 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.3168791384838904
Fold 2 IBS: 0.3218948725307976
Fold 3 IBS: 0.27592959166775866
Fold 4 IBS: 0.315408539471182
Fold 5 IBS: 0.30438829249434424
[I 2024-04-16 05:15:11,948] Trial 1 finished with value: 0.3069000869295946 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2753019447545149
Fold 2 IBS: 0.2982356241179488
Fold 3 IBS: 0.23068334408596278
Fold 4 IBS: 0.27397829249360633
Fold 5 IBS: 0.25684924696430295
[I 2024-04-16 05:15:13,303] Trial 2 finished with value: 0.26700969048326717 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2786819074278709
Fold 2 IBS: 0.2600472138747981
Fold 3 IBS: 0.23882358787102978
Fold 4 IBS: 0.2592722986281111
Fold 5 IBS: 0.2182835718315773
[I 2024-04-16 05:15:14,787] Trial 3 finished with value: 0.2510217159266774 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.27967272034047036
Fold 2 IBS: 0.28471090270389776
Fold 3 IBS: 0.23985228996640132
Fold 4 IBS: 0.2562837019187784
Fold 5 IBS: 0.2309276099395795
[I 2024-04-16 05:15:16,994] Trial 4 finished with value: 0.2582894449738255 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.30156654310213465
Fold 2 IBS: 0.3204353433554115
Fold 3 IBS: 0.2623263101041928
Fold 4 IBS: 0.3038662427158054
Fold 5 IBS: 0.2972845037916553
[I 2024-04-16 05:15:05,411] Trial 5 finished with value: 0.29709578861383995 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.23284347689671558
Fold 2 IBS: 0.202874467602479
Fold 3 IBS: 0.17322347591450493
Fold 4 IBS: 0.24151316943928927
Fold 5 IBS: 0.1909058630290115
[I 2024-04-16 05:15:06,574] Trial 6 finished with value: 0.20827209057640003 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20827209057640003.
Fold 1 IBS: 0.20841359719195401
Fold 2 IBS: 0.18500570168858935
Fold 3 IBS: 0.17412783878300364
Fold 4 IBS: 0.20964581935767979
Fold 5 IBS: 0.18389770396679075
[I 2024-04-16 05:15:06,865] Trial 7 finished with value: 0.1922181321976035 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.2500273900096136
Fold 2 IBS: 0.24252428811376492
Fold 3 IBS: 0.19169795532346123
Fold 4 IBS: 0.26800891557035394
Fold 5 IBS: 0.20674266811943262
[I 2024-04-16 05:15:08,456] Trial 8 finished with value: 0.23180024342732528 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.3046029224708627
Fold 2 IBS: 0.32082834695628154
Fold 3 IBS: 0.26752591253808156
Fold 4 IBS: 0.3050114978922588
Fold 5 IBS: 0.28810913599911264
[I 2024-04-16 05:15:12,350] Trial 9 finished with value: 0.2972155631713194 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.21341107818060095
Fold 2 IBS: 0.22041244256787032
Fold 3 IBS: 0.20358827659270148
Fold 4 IBS: 0.22376802174886082
Fold 5 IBS: 0.2171830253408078
[I 2024-04-16 05:15:12,555] Trial 10 finished with value: 0.21567256888616831 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.2131898560857691
Fold 2 IBS: 0.22000460296162738
Fold 3 IBS: 0.20348419225803208
Fold 4 IBS: 0.22352663518317686
Fold 5 IBS: 0.2169388510633896
[I 2024-04-16 05:15:12,714] Trial 11 finished with value: 0.215428827510399 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.2649085487462804
Fold 2 IBS: 0.2797956098039142
Fold 3 IBS: 0.21547582765233256
Fold 4 IBS: 0.269516915435845
Fold 5 IBS: 0.215822468931253
[I 2024-04-16 05:15:13,308] Trial 12 finished with value: 0.249103874113925 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.26365849597545205
Fold 2 IBS: 0.27755786474823224
Fold 3 IBS: 0.21375266267140264
Fold 4 IBS: 0.27739729053928086
Fold 5 IBS: 0.24947493405031224
[I 2024-04-16 05:15:15,751] Trial 13 finished with value: 0.25636824959693605 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.20569427667469156
Fold 2 IBS: 0.19327418056505236
Fold 3 IBS: 0.18069024590527896
Fold 4 IBS: 0.2080995790312972
Fold 5 IBS: 0.19490230571351805
[I 2024-04-16 05:15:16,285] Trial 14 finished with value: 0.19653211757796762 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.210409804816474
Fold 2 IBS: 0.21349058556283512
Fold 3 IBS: 0.1985155340163065
Fold 4 IBS: 0.21856174646948462
Fold 5 IBS: 0.21159186703086064
[I 2024-04-16 05:15:16,702] Trial 15 finished with value: 0.21051390757919214 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.20630685620006517
Fold 2 IBS: 0.20273931524283226
Fold 3 IBS: 0.18919005657291543
Fold 4 IBS: 0.21127743577400432
Fold 5 IBS: 0.20267124736055916
[I 2024-04-16 05:15:17,054] Trial 16 finished with value: 0.20243698223007528 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.23835959803032003
Fold 2 IBS: 0.21402340081247587
Fold 3 IBS: 0.17953828231829627
Fold 4 IBS: 0.25047212321042694
Fold 5 IBS: 0.19743222117495793
[I 2024-04-16 05:15:18,477] Trial 17 finished with value: 0.2159651251092954 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.23992452095154856
Fold 2 IBS: 0.21495595423038097
Fold 3 IBS: 0.18009687426129353
Fold 4 IBS: 0.24881181915281447
Fold 5 IBS: 0.18879449197689388
[I 2024-04-16 05:15:20,949] Trial 18 finished with value: 0.21451673211458627 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.1922181321976035.
Fold 1 IBS: 0.20210457556978584
Fold 2 IBS: 0.17661974827833785

Fold 3 IBS: 0.17559695146919774
Fold 4 IBS: 0.19136347113687585
Fold 5 IBS: 0.18238485830356638
[I 2024-04-16 05:15:21,304] Trial 19 finished with value: 0.18561392095155274 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20385002842262298
Fold 2 IBS: 0.17898541076661173
Fold 3 IBS: 0.17678497782327718
Fold 4 IBS: 0.1964113675862836
Fold 5 IBS: 0.18635022380429012
[I 2024-04-16 05:15:21,587] Trial 20 finished with value: 0.18847640168061713 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20152752504533955
Fold 2 IBS: 0.186025328567609
Fold 3 IBS: 0.18245538571556968
Fold 4 IBS: 0.19968663830097044
Fold 5 IBS: 0.19044129437999457
[I 2024-04-16 05:15:21,827] Trial 21 finished with value: 0.19202723440189665 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21205582422749808
Fold 2 IBS: 0.21583888403632293
Fold 3 IBS: 0.20173644884289824
Fold 4 IBS: 0.2204758634921401
Fold 5 IBS: 0.2148929895721433
[I 2024-04-16 05:15:21,991] Trial 22 finished with value: 0.21300000203420053 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.9919822999492534, 'n_estimators': 4, 'learning_rate': 0.042274123196352986}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.24005519973194164
Fold 2 IBS: 0.2049567574643235
Fold 3 IBS: 0.18582470837505527
Fold 4 IBS: 0.2402678200879745
Fold 5 IBS: 0.17807238500379088
[I 2024-04-16 05:15:22,758] Trial 23 finished with value: 0.2098353741326172 and parameters: {'subsample': 0.20060522420089708, 'dropout_rate': 0.9544358989560502, 'n_estimators': 140, 'learning_rate': 0.04186582141545488}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21717963622535313
Fold 2 IBS: 0.180917876643808
Fold 3 IBS: 0.17131402660235046
Fold 4 IBS: 0.21154025047599964
Fold 5 IBS: 0.177449104629405
[I 2024-04-16 05:15:23,069] Trial 24 finished with value: 0.19168017891538325 and parameters: {'subsample': 0.21087377170392102, 'dropout_rate': 0.934488873956264, 'n_estimators': 50, 'learning_rate': 0.06359840805809217}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.24874961039100094
Fold 2 IBS: 0.23427810681191236
Fold 3 IBS: 0.19680879776009227
Fold 4 IBS: 0.2577938349609485
Fold 5 IBS: 0.19499119603369655
[I 2024-04-16 05:15:23,565] Trial 25 finished with value: 0.2265243091915301 and parameters: {'subsample': 0.2217965007715769, 'dropout_rate': 0.7983613774962235, 'n_estimators': 82, 'learning_rate': 0.08664806118200213}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.27443214879803096
Fold 2 IBS: 0.27217387363354867
Fold 3 IBS: 0.23435994042193695
Fold 4 IBS: 0.25772674529450035
Fold 5 IBS: 0.2191696827863668
[I 2024-04-16 05:15:24,390] Trial 26 finished with value: 0.2515724781868767 and parameters: {'subsample': 0.1970663383107968, 'dropout_rate': 0.89397617546164, 'n_estimators': 150, 'learning_rate': 0.0841974838810202}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.30767439638688954
Fold 2 IBS: 0.30951199341569313
Fold 3 IBS: 0.2666711010388477
Fold 4 IBS: 0.2600786689235578
Fold 5 IBS: 0.25980938443484164
[I 2024-04-16 05:15:27,527] Trial 27 finished with value: 0.28074910883996596 and parameters: {'subsample': 0.16696086345822864, 'dropout_rate': 0.8988310304064844, 'n_estimators': 410, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.28226038327992725
Fold 2 IBS: 0.301134483758219
Fold 3 IBS: 0.24173146966460093
Fold 4 IBS: 0.2759370918236562
Fold 5 IBS: 0.24766471360011952
[I 2024-04-16 05:15:28,941] Trial 28 finished with value: 0.2697456284253046 and parameters: {'subsample': 0.28798613296602027, 'dropout_rate': 0.7753950220583815, 'n_estimators': 228, 'learning_rate': 0.06492070456061831}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.24352615785195733
Fold 2 IBS: 0.22219190432975094
Fold 3 IBS: 0.18129461091848134
Fold 4 IBS: 0.2553119589042743
Fold 5 IBS: 0.1913509737986603
[I 2024-04-16 05:15:29,505] Trial 29 finished with value: 0.21873512116062485 and parameters: {'subsample': 0.4268613546591912, 'dropout_rate': 0.9430576733480622, 'n_estimators': 105, 'learning_rate': 0.05399626242596553}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2056276036063031
Fold 2 IBS: 0.18397243792827364
Fold 3 IBS: 0.1756018176547451
Fold 4 IBS: 0.20624570556529742
Fold 5 IBS: 0.18667774292165032
[I 2024-04-16 05:15:29,852] Trial 30 finished with value: 0.1916250615352539 and parameters: {'subsample': 0.255590967415097, 'dropout_rate': 0.8317683674434488, 'n_estimators': 55, 'learning_rate': 0.035279499789761234}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2055875822464025
Fold 2 IBS: 0.1849213051974537
Fold 3 IBS: 0.17598415646895477
Fold 4 IBS: 0.2053637952506559
Fold 5 IBS: 0.18752900511333512
[I 2024-04-16 05:15:30,169] Trial 31 finished with value: 0.19187716885536038 and parameters: {'subsample': 0.21630271621226355, 'dropout_rate': 0.829025152197055, 'n_estimators': 54, 'learning_rate': 0.034656609251772795}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20326114554100033
Fold 2 IBS: 0.18967335769785207
Fold 3 IBS: 0.17948923370412553
Fold 4 IBS: 0.2052456257663074
Fold 5 IBS: 0.19084151823487883
[I 2024-04-16 05:15:30,421] Trial 32 finished with value: 0.19370217618883281 and parameters: {'subsample': 0.2547170911552691, 'dropout_rate': 0.9314017141433415, 'n_estimators': 33, 'learning_rate': 0.0479940910776742}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20363320295007173
Fold 2 IBS: 0.1794720917645107
Fold 3 IBS: 0.1768537819762967
Fold 4 IBS: 0.20026446977313425
Fold 5 IBS: 0.183306171479459
[I 2024-04-16 05:15:30,831] Trial 33 finished with value: 0.18870594358869447 and parameters: {'subsample': 0.15123432487131955, 'dropout_rate': 0.9814479432419315, 'n_estimators': 79, 'learning_rate': 0.02655818639526184}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21735815890067609
Fold 2 IBS: 0.17736253489641965
Fold 3 IBS: 0.17247166926879848
Fold 4 IBS: 0.2028416477874531
Fold 5 IBS: 0.17668615460726503
[I 2024-04-16 05:15:31,763] Trial 34 finished with value: 0.18934403309212244 and parameters: {'subsample': 0.13866826859575646, 'dropout_rate': 0.7389511771372612, 'n_estimators': 146, 'learning_rate': 0.022493844619571622}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2169081838822504
Fold 2 IBS: 0.18177368815244985
Fold 3 IBS: 0.17361887852474633
Fold 4 IBS: 0.2132627210540104
Fold 5 IBS: 0.17613798371852046
[I 2024-04-16 05:15:32,670] Trial 35 finished with value: 0.19234029106639547 and parameters: {'subsample': 0.13936506068446242, 'dropout_rate': 0.9999719052455961, 'n_estimators': 172, 'learning_rate': 0.023048782790281344}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2142786459185333
Fold 2 IBS: 0.17821595135764368
Fold 3 IBS: 0.1722468793531377
Fold 4 IBS: 0.2010480739507009
Fold 5 IBS: 0.17559979586751356
[I 2024-04-16 05:15:33,483] Trial 36 finished with value: 0.18827786928950582 and parameters: {'subsample': 0.16806503731483008, 'dropout_rate': 0.5201820662991501, 'n_estimators': 129, 'learning_rate': 0.022377618063917252}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21367138678284034
Fold 2 IBS: 0.18161742716090903
Fold 3 IBS: 0.1723698301381215
Fold 4 IBS: 0.206586398722815
Fold 5 IBS: 0.18113351838182923
[I 2024-04-16 05:15:33,953] Trial 37 finished with value: 0.19107571223730302 and parameters: {'subsample': 0.3171412829123914, 'dropout_rate': 0.47096246897520044, 'n_estimators': 87, 'learning_rate': 0.028811820403570124}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2016583291333657
Fold 2 IBS: 0.19198819384810561
Fold 3 IBS: 0.1842184369034613

Fold 4 IBS: 0.19970147648879832
Fold 5 IBS: 0.19379867220842292
[I 2024-04-16 05:15:34,671] Trial 38 finished with value: 0.19427302171643077 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.2908235532799638, 'n_estimators': 117, 'learning_rate': 0.01019431388894447}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.23308107527388047
Fold 2 IBS: 0.18915589279847106
Fold 3 IBS: 0.17859698469690719
Fold 4 IBS: 0.21592434119861256
Fold 5 IBS: 0.17571592320871024
[I 2024-04-16 05:15:36,589] Trial 39 finished with value: 0.19849484343531631 and parameters: {'subsample': 0.167666800643059, 'dropout_rate': 0.531096799684823, 'n_estimators': 267, 'learning_rate': 0.019230973079348387}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2526994588964834
Fold 2 IBS: 0.23678037479229275
Fold 3 IBS: 0.19647581845865703
Fold 4 IBS: 0.26532918185085924
Fold 5 IBS: 0.19634674564701443
[I 2024-04-16 05:15:37,656] Trial 40 finished with value: 0.2295263159290614 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.1585668555692103, 'n_estimators': 164, 'learning_rate': 0.04678525077397254}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21593737576456346
Fold 2 IBS: 0.17820566793644482
Fold 3 IBS: 0.1718701068047231
Fold 4 IBS: 0.20816086518932747
Fold 5 IBS: 0.17597320276688413
[I 2024-04-16 05:15:38,414] Trial 41 finished with value: 0.19002944369238856 and parameters: {'subsample': 0.1722576155155166, 'dropout_rate': 0.7332075473444788, 'n_estimators': 131, 'learning_rate': 0.02304899716547951}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2156125713214088
Fold 2 IBS: 0.18327467728780547
Fold 3 IBS: 0.1718350520848397
Fold 4 IBS: 0.2133633635601884
Fold 5 IBS: 0.17934720678128765
[I 2024-04-16 05:15:38,872] Trial 42 finished with value: 0.192686574207106 and parameters: {'subsample': 0.2548814611479326, 'dropout_rate': 0.5236639807793886, 'n_estimators': 81, 'learning_rate': 0.037206901139887304}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2336370007459461
Fold 2 IBS: 0.19223643157735051
Fold 3 IBS: 0.18269366233848908
Fold 4 IBS: 0.21617476053877382
Fold 5 IBS: 0.1776055922155473
[I 2024-04-16 05:15:39,973] Trial 43 finished with value: 0.20046948948322138 and parameters: {'subsample': 0.1457644964128255, 'dropout_rate': 0.8740514902722564, 'n_estimators': 191, 'learning_rate': 0.027633234880330062}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21165656392074378
Fold 2 IBS: 0.21685828344743036
Fold 3 IBS: 0.20121898419742273
Fold 4 IBS: 0.22120910443342257
Fold 5 IBS: 0.2144053464042495
[I 2024-04-16 05:15:40,161] Trial 44 finished with value: 0.2130696564806538 and parameters: {'subsample': 0.10313456755127373, 'dropout_rate': 0.5724958885118183, 'n_estimators': 19, 'learning_rate': 0.008452417814559184}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2402147176147427
Fold 2 IBS: 0.21736543026320584
Fold 3 IBS: 0.1795211545771554
Fold 4 IBS: 0.2505041963049279
Fold 5 IBS: 0.19353655418322777
[I 2024-04-16 05:15:41,742] Trial 45 finished with value: 0.21622841058865191 and parameters: {'subsample': 0.42510137241345053, 'dropout_rate': 0.41536594505380947, 'n_estimators': 234, 'learning_rate': 0.02274904980797578}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21312417781322754
Fold 2 IBS: 0.17729021026698866
Fold 3 IBS: 0.17141149120666452
Fold 4 IBS: 0.2048836513721606
Fold 5 IBS: 0.17676231489091584
[I 2024-04-16 05:15:42,765] Trial 46 finished with value: 0.18869436910999143 and parameters: {'subsample': 0.17138383057667347, 'dropout_rate': 0.3388086440368722, 'n_estimators': 156, 'learning_rate': 0.019215219362605413}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2066554104106091
Fold 2 IBS: 0.1847690107280302
Fold 3 IBS: 0.1764013762659986
Fold 4 IBS: 0.20451048377539566
Fold 5 IBS: 0.186515277640396
[I 2024-04-16 05:15:43,455] Trial 47 finished with value: 0.19177031176408593 and parameters: {'subsample': 0.2900611638222566, 'dropout_rate': 0.34697207582586104, 'n_estimators': 106, 'learning_rate': 0.018184217448441647}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.23019332319744445
Fold 2 IBS: 0.1838007734448157
Fold 3 IBS: 0.17658511023898174
Fold 4 IBS: 0.22966490827601097
Fold 5 IBS: 0.18049791668156648
[I 2024-04-16 05:15:44,535] Trial 48 finished with value: 0.20014840636776388 and parameters: {'subsample': 0.23714879936852107, 'dropout_rate': 0.19701471782839963, 'n_estimators': 158, 'learning_rate': 0.030507866196174044}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2224585018136294
Fold 2 IBS: 0.17690341355036962
Fold 3 IBS: 0.17352540514978096
Fold 4 IBS: 0.20853890595733388
Fold 5 IBS: 0.17403110805579836
[I 2024-04-16 05:15:45,016] Trial 49 finished with value: 0.19109146690538242 and parameters: {'subsample': 0.18177642816834552, 'dropout_rate': 0.3424101549408848, 'n_estimators': 70, 'learning_rate': 0.058356325156788194}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20567020786658194
Fold 2 IBS: 0.19095989614862408
Fold 3 IBS: 0.1811062814830664
Fold 4 IBS: 0.2052468648330231
Fold 5 IBS: 0.19219656199661903
[I 2024-04-16 05:15:46,291] Trial 50 finished with value: 0.1950359624655829 and parameters: {'subsample': 0.3400458531012662, 'dropout_rate': 0.2651995573852989, 'n_estimators': 185, 'learning_rate': 0.007688211105648254}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.21150950228829715
Fold 2 IBS: 0.17725759516703452
Fold 3 IBS: 0.17308894075440007
Fold 4 IBS: 0.1983294334478471
Fold 5 IBS: 0.17863574138991542
[I 2024-04-16 05:15:47,089] Trial 51 finished with value: 0.18776424260949887 and parameters: {'subsample': 0.1422401972634589, 'dropout_rate': 0.6786610300406142, 'n_estimators': 137, 'learning_rate': 0.019000902208336497}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2353680290775318
Fold 2 IBS: 0.1936850427827619
Fold 3 IBS: 0.18447311284307646
Fold 4 IBS: 0.21948239213202464
Fold 5 IBS: 0.17934145703939675
[I 2024-04-16 05:15:48,497] Trial 52 finished with value: 0.2024700067749583 and parameters: {'subsample': 0.1443935089801384, 'dropout_rate': 0.6840515291093091, 'n_estimators': 214, 'learning_rate': 0.02622174563834176}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20763713664248268
Fold 2 IBS: 0.17481125753825139
Fold 3 IBS: 0.173579289833097
Fold 4 IBS: 0.1956711219824923
Fold 5 IBS: 0.1794905868309365
[I 2024-04-16 05:15:49,264] Trial 53 finished with value: 0.186237878565452 and parameters: {'subsample': 0.18329931737132202, 'dropout_rate': 0.11241993952388482, 'n_estimators': 124, 'learning_rate': 0.018710706678993896}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.209392302538297
Fold 2 IBS: 0.18763352486847026
Fold 3 IBS: 0.17489650705384863
Fold 4 IBS: 0.2098547184575316
Fold 5 IBS: 0.18846934856854997
[I 2024-04-16 05:15:50,001] Trial 54 finished with value: 0.19404928029733948 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.10411649300803834, 'n_estimators': 123, 'learning_rate': 0.016095926849344196}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2051717290736261
Fold 2 IBS: 0.19930575508207082
Fold 3 IBS: 0.188617845838254
Fold 4 IBS: 0.2080036720393016
Fold 5 IBS: 0.19884138563768952
[I 2024-04-16 05:15:51,342] Trial 55 finished with value: 0.1999880775341884 and parameters: {'subsample': 0.20218830483801442, 'dropout_rate': 0.4957943543733721, 'n_estimators': 202, 'learning_rate': 0.004374164529914685}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20149271228991822
Fold 2 IBS: 0.18889278562953882
Fold 3 IBS: 0.18244888486656366
Fold 4 IBS: 0.20049688644353011
Fold 5 IBS: 0.1906099178737196
[I 2024-04-16 05:15:51,969] Trial 56 finished with value: 0.1927882374206541 and parameters: {'subsample': 0.12953200081844046, 'dropout_rate': 0.43133620980368764, 'n_estimators': 103, 'learning_rate': 0.013165623613836445}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2349578647415557
Fold 2 IBS: 0.20380486273154313
Fold 3 IBS: 0.17937307284553167

Fold 4 IBS: 0.23524556713861994
Fold 5 IBS: 0.18175978216705466
[I 2024-04-16 05:15:53,932] Trial 57 finished with value: 0.20702822992486106 and parameters: {'subsample': 0.287480927064245, 'dropout_rate': 0.310570838083683, 'n_estimators': 256, 'learning_rate': 0.019746883319291475}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20873751439183064
Fold 2 IBS: 0.2098077449702301
Fold 3 IBS: 0.19579887472650773
Fold 4 IBS: 0.21662065248561807
Fold 5 IBS: 0.20963911462011556
[I 2024-04-16 05:15:54,107] Trial 58 finished with value: 0.2081207802388604 and parameters: {'subsample': 0.2341458361742736, 'dropout_rate': 0.6276973088855227, 'n_estimators': 13, 'learning_rate': 0.03237151215124951}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20156112265850423
Fold 2 IBS: 0.18998875782566582
Fold 3 IBS: 0.1802717139071199
Fold 4 IBS: 0.20048365943759167
Fold 5 IBS: 0.1891019830466934
[I 2024-04-16 05:15:54,381] Trial 59 finished with value: 0.19228144737511502 and parameters: {'subsample': 0.17067073242395692, 'dropout_rate': 0.2214117970877909, 'n_estimators': 38, 'learning_rate': 0.03951641923789499}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2651485733633336
Fold 2 IBS: 0.28174636234305717
Fold 3 IBS: 0.21533848098786595
Fold 4 IBS: 0.27781186213369946
Fold 5 IBS: 0.25283144919138556
[I 2024-04-16 05:15:55,105] Trial 60 finished with value: 0.25857534560386836 and parameters: {'subsample': 0.786659079511644, 'dropout_rate': 0.6609581012621187, 'n_estimators': 136, 'learning_rate': 0.07200825617838875}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.22735099164216052
Fold 2 IBS: 0.1854208282317905
Fold 3 IBS: 0.1734428710203579
Fold 4 IBS: 0.20600748339784566
Fold 5 IBS: 0.17501159547754122
[I 2024-04-16 05:15:55,652] Trial 61 finished with value: 0.19344675395393918 and parameters: {'subsample': 0.16141468165650946, 'dropout_rate': 0.863737770180308, 'n_estimators': 77, 'learning_rate': 0.05093075837323216}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20982246029964519
Fold 2 IBS: 0.17513921377239364
Fold 3 IBS: 0.17359638892619925
Fold 4 IBS: 0.19558075876749922
Fold 5 IBS: 0.17795320346317314
[I 2024-04-16 05:15:56,289] Trial 62 finished with value: 0.18641840504578208 and parameters: {'subsample': 0.12499925839087661, 'dropout_rate': 0.5810517322226594, 'n_estimators': 98, 'learning_rate': 0.02576764526691875}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20321568500278
Fold 2 IBS: 0.19232250962988404
Fold 3 IBS: 0.18523178814850277
Fold 4 IBS: 0.20243996333024494
Fold 5 IBS: 0.19408223686538664
[I 2024-04-16 05:15:57,022] Trial 63 finished with value: 0.19545843659535966 and parameters: {'subsample': 0.12424828187457437, 'dropout_rate': 0.5971015134927581, 'n_estimators': 97, 'learning_rate': 0.01160921406167613}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.20645294839626802
Fold 2 IBS: 0.1818552764202155
Fold 3 IBS: 0.17577387957396973
Fold 4 IBS: 0.20079981479410644
Fold 5 IBS: 0.18231079957085009
[I 2024-04-16 05:15:57,785] Trial 64 finished with value: 0.18943854375108196 and parameters: {'subsample': 0.18949195807404198, 'dropout_rate': 0.5633522624471919, 'n_estimators': 116, 'learning_rate': 0.0169897099777497}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.232401312455578
Fold 2 IBS: 0.19849878009772562
Fold 3 IBS: 0.1776872958906119
Fold 4 IBS: 0.2360570675567082
Fold 5 IBS: 0.1802773419875682
[I 2024-04-16 05:15:58,720] Trial 65 finished with value: 0.2049843595976384 and parameters: {'subsample': 0.23191670243956938, 'dropout_rate': 0.6931497092197401, 'n_estimators': 152, 'learning_rate': 0.03183925784133908}. Best is trial 19 with value: 0.18561392095155274.
Fold 1 IBS: 0.2061387309224875
Fold 2 IBS: 0.1726109681645299
Fold 3 IBS: 0.17325540563455355
Fold 4 IBS: 0.1925150992729512
Fold 5 IBS: 0.1800641772479191
[I 2024-04-16 05:15:59,111] Trial 66 finished with value: 0.18491687624848824 and parameters: {'subsample': 0.10059671085024957, 'dropout_rate': 0.5090402212478303, 'n_estimators': 57, 'learning_rate': 0.04467193626943396}. Best is trial 66 with value: 0.18491687624848824.
Fold 1 IBS: 0.20621359983054394
Fold 2 IBS: 0.17157893981531316
Fold 3 IBS: 0.1725773816973107
Fold 4 IBS: 0.189360788021124
Fold 5 IBS: 0.17522330654388457
[I 2024-04-16 05:15:59,545] Trial 67 finished with value: 0.18299080318163527 and parameters: {'subsample': 0.10333209447138711, 'dropout_rate': 0.49850977325022405, 'n_estimators': 65, 'learning_rate': 0.04631124758197062}. Best is trial 67 with value: 0.18299080318163527.
Fold 1 IBS: 0.21130487355644256
Fold 2 IBS: 0.16981755820344724
Fold 3 IBS: 0.17204147771235032
Fold 4 IBS: 0.19513863682219232
Fold 5 IBS: 0.17564821617275186
[I 2024-04-16 05:15:59,992] Trial 68 finished with value: 0.18479015249343686 and parameters: {'subsample': 0.10273572869697785, 'dropout_rate': 0.5140970309112008, 'n_estimators': 70, 'learning_rate': 0.047374569803455766}. Best is trial 67 with value: 0.18299080318163527.
Fold 1 IBS: 0.21067826441016232
Fold 2 IBS: 0.17017263597390045
Fold 3 IBS: 0.17306043998966555
Fold 4 IBS: 0.18652088599207006
Fold 5 IBS: 0.17432018574780653
[I 2024-04-16 05:16:00,417] Trial 69 finished with value: 0.182950482422721 and parameters: {'subsample': 0.11475041979172002, 'dropout_rate': 0.3807796999833377, 'n_estimators': 65, 'learning_rate': 0.045515105216989676}. Best is trial 69 with value: 0.182950482422721.
Fold 1 IBS: 0.20487304572009524
Fold 2 IBS: 0.17228001090749612
Fold 3 IBS: 0.17309069499293658
Fold 4 IBS: 0.1889294807584525
Fold 5 IBS: 0.17594227824224337
[I 2024-04-16 05:16:00,811] Trial 70 finished with value: 0.18302310212424477 and parameters: {'subsample': 0.10617517238513516, 'dropout_rate': 0.38472485941701706, 'n_estimators': 62, 'learning_rate': 0.045497323863201516}. Best is trial 69 with value: 0.182950482422721.
Fold 1 IBS: 0.2053001934545391
Fold 2 IBS: 0.17212417041974995
Fold 3 IBS: 0.17299969349899713
Fold 4 IBS: 0.18898131001695936
Fold 5 IBS: 0.175617522836202
[I 2024-04-16 05:16:01,227] Trial 71 finished with value: 0.18300457804528952 and parameters: {'subsample': 0.10668055558010346, 'dropout_rate': 0.3844943177047123, 'n_estimators': 62, 'learning_rate': 0.04654782306312724}. Best is trial 69 with value: 0.182950482422721.
Fold 1 IBS: 0.20248655680153596
Fold 2 IBS: 0.1726250826282818
Fold 3 IBS: 0.17343837092248
Fold 4 IBS: 0.19095093508123184
Fold 5 IBS: 0.177170490654899
[I 2024-04-16 05:16:01,665] Trial 72 finished with value: 0.18333428721768572 and parameters: {'subsample': 0.10286752196477046, 'dropout_rate': 0.4692494918434249, 'n_estimators': 57, 'learning_rate': 0.04604353554172354}. Best is trial 69 with value: 0.182950482422721.
Fold 1 IBS: 0.20280093141619907
Fold 2 IBS: 0.1719903669561345
Fold 3 IBS: 0.17318359282356832
Fold 4 IBS: 0.19036291976938366
Fold 5 IBS: 0.17640353458729488
[I 2024-04-16 05:16:02,157] Trial 73 finished with value: 0.1829482691105161 and parameters: {'subsample': 0.10332112973711333, 'dropout_rate': 0.3922743117809352, 'n_estimators': 56, 'learning_rate': 0.048630972593506766}. Best is trial 73 with value: 0.1829482691105161.
Fold 1 IBS: 0.20322417859779407
Fold 2 IBS: 0.18945487536050043
Fold 3 IBS: 0.18512561120990983
Fold 4 IBS: 0.20217760795346956
Fold 5 IBS: 0.19449202378019817
[I 2024-04-16 05:16:02,431] Trial 74 finished with value: 0.1948948593803744 and parameters: {'subsample': 0.10087136438666996, 'dropout_rate': 0.3708730214632796, 'n_estimators': 25, 'learning_rate': 0.04712714319856336}. Best is trial 73 with value: 0.1829482691105161.
Fold 1 IBS: 0.21577807233232474
Fold 2 IBS: 0.1713494445616201
Fold 3 IBS: 0.17275765575947674
Fold 4 IBS: 0.18985576596476134
Fold 5 IBS: 0.1733372662026927
[I 2024-04-16 05:16:02,892] Trial 75 finished with value: 0.18461564096417515 and parameters: {'subsample': 0.1245135493739909, 'dropout_rate': 0.45350311301358787, 'n_estimators': 65, 'learning_rate': 0.057035555733371504}. Best is trial 73 with value: 0.1829482691105161.
Fold 1 IBS: 0.2155175516375289
Fold 2 IBS: 0.17179101621616125
Fold 3 IBS: 0.17335014934012588
Fold 4 IBS: 0.1892411455981349
Fold 5 IBS: 0.1725177286876416
[I 2024-04-16 05:16:03,319] Trial 76 finished with value: 0.1844835182959185 and parameters: {'subsample': 0.12399358208155303, 'dropout_rate': 0.449350356472916, 'n_estimators': 70, 'learning_rate': 0.05576099830746171}. Best is trial 73 with value: 0.1829482691105161.

Fold 1 IBS: 0.2123118865289582
Fold 2 IBS: 0.18711899052237113
Fold 3 IBS: 0.17344631354825793
Fold 4 IBS: 0.20915818709182382
Fold 5 IBS: 0.18581168448565522
[I 2024-04-16 05:16:03,592] Trial 77 finished with value: 0.19356941243541326 and parameters: {'subsample': 0.5189609406746745, 'dropout_rate': 0.4517032081036193, 'n_estimators': 39, 'learning_rate': 0.05699325023464598}. Best is trial 73 with value: 0.1829482691105161.
Fold 1 IBS: 0.21245690064091996
Fold 2 IBS: 0.1716813809222342
Fold 3 IBS: 0.1726090449523327
Fold 4 IBS: 0.1987968002916969
Fold 5 IBS: 0.17435871466828684
[I 2024-04-16 05:16:04,034] Trial 78 finished with value: 0.18598056829509413 and parameters: {'subsample': 0.1289194344931569, 'dropout_rate': 0.3814766477624397, 'n_estimators': 66, 'learning_rate': 0.05240930822810723}. Best is trial 73 with value: 0.1829482691105161.
Fold 1 IBS: 0.21183884213778528
Fold 2 IBS: 0.21744879587985189
Fold 3 IBS: 0.2006226196411385
Fold 4 IBS: 0.22028923854047944
Fold 5 IBS: 0.21454807860958472
[I 2024-04-16 05:16:04,175] Trial 79 finished with value: 0.21294951496176795 and parameters: {'subsample': 0.2057791209301667, 'dropout_rate': 0.4037952845593772, 'n_estimators': 3, 'learning_rate': 0.054654554830290636}. Best is trial 73 with value: 0.1829482691105161.
Fold 1 IBS: 0.20986722619491455
Fold 2 IBS: 0.16979721438517006
Fold 3 IBS: 0.17303425425505958
Fold 4 IBS: 0.1971587127847552
Fold 5 IBS: 0.1777409048722851
[I 2024-04-16 05:16:04,500] Trial 80 finished with value: 0.1855196624984369 and parameters: {'subsample': 0.13201875232532148, 'dropout_rate': 0.45663283746468936, 'n_estimators': 45, 'learning_rate': 0.06605949501619998}. Best is trial 73 with value: 0.1829482691105161.
Fold 1 IBS: 0.21113326460027115
Fold 2 IBS: 0.17002998692775023
Fold 3 IBS: 0.1732619063710145
Fold 4 IBS: 0.18530781156218518
Fold 5 IBS: 0.17436844874065577
[I 2024-04-16 05:16:04,918] Trial 81 finished with value: 0.1828202836403754 and parameters: {'subsample': 0.11322510865716894, 'dropout_rate': 0.4821718850558442, 'n_estimators': 61, 'learning_rate': 0.04926624335505633}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.20169680325373546
Fold 2 IBS: 0.18716064237550947
Fold 3 IBS: 0.18123778855472214
Fold 4 IBS: 0.19937003658497224
Fold 5 IBS: 0.19022926139770763
[I 2024-04-16 05:16:05,140] Trial 82 finished with value: 0.1919389064333294 and parameters: {'subsample': 0.12149815699280223, 'dropout_rate': 0.4257453703640979, 'n_estimators': 24, 'learning_rate': 0.059811060303323574}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.21165649441047743
Fold 2 IBS: 0.17726875560876293
Fold 3 IBS: 0.17295113299852585
Fold 4 IBS: 0.1983333903835475
Fold 5 IBS: 0.17467129278784327
[I 2024-04-16 05:16:05,502] Trial 83 finished with value: 0.18697621323783137 and parameters: {'subsample': 0.15639665803740724, 'dropout_rate': 0.47949464329828495, 'n_estimators': 61, 'learning_rate': 0.04993770804816989}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.22045990158959977
Fold 2 IBS: 0.17925449647933214
Fold 3 IBS: 0.17311510151358836
Fold 4 IBS: 0.21139593390065145
Fold 5 IBS: 0.1735959080841943
[I 2024-04-16 05:16:06,114] Trial 84 finished with value: 0.19156426831347323 and parameters: {'subsample': 0.19362162616575168, 'dropout_rate': 0.45168836137421364, 'n_estimators': 87, 'learning_rate': 0.043574042225613153}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.30392894487339717
Fold 2 IBS: 0.30058900625782053
Fold 3 IBS: 0.26543298796075554
Fold 4 IBS: 0.24916886273685293
Fold 5 IBS: 0.25489230945748037
[I 2024-04-16 05:16:12,510] Trial 85 finished with value: 0.2748024222572613 and parameters: {'subsample': 0.153425179909418, 'dropout_rate': 0.31789421395851514, 'n_estimators': 475, 'learning_rate': 0.05005409314030352}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.3027552154028647
Fold 2 IBS: 0.28778041272354243
Fold 3 IBS: 0.2644642037918195
Fold 4 IBS: 0.24710191658311262
Fold 5 IBS: 0.24695892042772644
[I 2024-04-16 05:16:17,163] Trial 86 finished with value: 0.26981213378581315 and parameters: {'subsample': 0.11718925209334458, 'dropout_rate': 0.3694317729301785, 'n_estimators': 413, 'learning_rate': 0.05614487519647115}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.20825907413746614
Fold 2 IBS: 0.18109599916453348
Fold 3 IBS: 0.17246315732310852
Fold 4 IBS: 0.20669186648270463
Fold 5 IBS: 0.17949026886719135
[I 2024-04-16 05:16:17,540] Trial 87 finished with value: 0.1896000731950008 and parameters: {'subsample': 0.2092765632952705, 'dropout_rate': 0.54525987823831, 'n_estimators': 49, 'learning_rate': 0.052777473156083186}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.21375039806739118
Fold 2 IBS: 0.17326254552801815
Fold 3 IBS: 0.17444552135503738
Fold 4 IBS: 0.19039177825187048
Fold 5 IBS: 0.1723187628144789
[I 2024-04-16 05:16:18,233] Trial 88 finished with value: 0.1848338012033592 and parameters: {'subsample': 0.1194174011316751, 'dropout_rate': 0.40077127064851126, 'n_estimators': 91, 'learning_rate': 0.044730073265934193}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.20423161376958784
Fold 2 IBS: 0.20558339855018148
Fold 3 IBS: 0.19088363444560716
Fold 4 IBS: 0.20786126494340013
Fold 5 IBS: 0.2043318759916598
[I 2024-04-16 05:16:18,414] Trial 89 finished with value: 0.20257835754008732 and parameters: {'subsample': 0.1539537896512725, 'dropout_rate': 0.44104688852180995, 'n_estimators': 12, 'learning_rate': 0.06308684561270288}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.20276484490523766
Fold 2 IBS: 0.19143999867181044
Fold 3 IBS: 0.18139271342609217
Fold 4 IBS: 0.20246795619190386
Fold 5 IBS: 0.19055205129509117
[I 2024-04-16 05:16:18,715] Trial 90 finished with value: 0.19372351289802708 and parameters: {'subsample': 0.18384181164023536, 'dropout_rate': 0.4859790633626181, 'n_estimators': 37, 'learning_rate': 0.03686107479028736}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.21647746743844812
Fold 2 IBS: 0.16938361264445062
Fold 3 IBS: 0.17251915799955755
Fold 4 IBS: 0.2019496583172619
Fold 5 IBS: 0.1749850510372613
[I 2024-04-16 05:16:19,176] Trial 91 finished with value: 0.18706298948739591 and parameters: {'subsample': 0.11434015397971983, 'dropout_rate': 0.5040588985594309, 'n_estimators': 71, 'learning_rate': 0.04792175230330966}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.21091535026505787
Fold 2 IBS: 0.17534346329791023
Fold 3 IBS: 0.17403618713595118
Fold 4 IBS: 0.20059998224796763
Fold 5 IBS: 0.1738855540074451
[I 2024-04-16 05:16:19,577] Trial 92 finished with value: 0.18695610739086638 and parameters: {'subsample': 0.14428418349190342, 'dropout_rate': 0.46637559832227504, 'n_estimators': 66, 'learning_rate': 0.04569332065726326}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.20150708580027288
Fold 2 IBS: 0.18754822490223197
Fold 3 IBS: 0.1843614853426568
Fold 4 IBS: 0.20167781765040227
Fold 5 IBS: 0.19375899596339724
[I 2024-04-16 05:16:19,836] Trial 93 finished with value: 0.19377072193179226 and parameters: {'subsample': 0.10136450245610529, 'dropout_rate': 0.41200689746521035, 'n_estimators': 30, 'learning_rate': 0.04148237213671}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.20696107551851978
Fold 2 IBS: 0.17197692181450702
Fold 3 IBS: 0.17310083584755004
Fold 4 IBS: 0.1954173558605779
Fold 5 IBS: 0.17694741771907518
[I 2024-04-16 05:16:20,211] Trial 94 finished with value: 0.18488072135204597 and parameters: {'subsample': 0.12798657448164702, 'dropout_rate': 0.38008476823204806, 'n_estimators': 55, 'learning_rate': 0.049272576837657005}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.22541931507070517
Fold 2 IBS: 0.18170125022269387
Fold 3 IBS: 0.17364254292974465
Fold 4 IBS: 0.20328170968992845
Fold 5 IBS: 0.17431084410607714
[I 2024-04-16 05:16:20,708] Trial 95 finished with value: 0.19167113240382985 and parameters: {'subsample': 0.16150325531709211, 'dropout_rate': 0.535228096299213, 'n_estimators': 76, 'learning_rate': 0.051583459887411774}. Best is trial 81 with value: 0.1828202836403754.
Fold 1 IBS: 0.20665162905984888

Fold 2 IBS: 0.17123814838553747
Fold 3 IBS: 0.17269115495453874
Fold 4 IBS: 0.18475235232092624
Fold 5 IBS: 0.17313385137825504
[I 2024-04-16 05:16:21,248] Trial 96 finished with value: 0.18169342721982126 and parameters: {'subsample': 0.10080401063092843, 'dropout_rate': 0.3564078078462598, 'n_estimators': 84, 'learning_rate': 0.039295022656166335}. Best is trial 96 with value: 0.18169342721982126.
Fold 1 IBS: 0.27573287205708735
Fold 2 IBS: 0.2714531332947983
Fold 3 IBS: 0.23591311125478967
Fold 4 IBS: 0.25811998045479884
Fold 5 IBS: 0.23209888832642764
[I 2024-04-16 05:16:24,362] Trial 97 finished with value: 0.25466359707758035 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.31372183756474226, 'n_estimators': 328, 'learning_rate': 0.04015331233811272}. Best is trial 96 with value: 0.18169342721982126.
Fold 1 IBS: 0.22218380231437124
Fold 2 IBS: 0.18900802159589356
Fold 3 IBS: 0.1705539059758543
Fold 4 IBS: 0.22288816270765116
Fold 5 IBS: 0.18390427105879292
[I 2024-04-16 05:16:24,870] Trial 98 finished with value: 0.19770763273051262 and parameters: {'subsample': 0.6256495106817341, 'dropout_rate': 0.2754117312151251, 'n_estimators': 84, 'learning_rate': 0.03773161485635139}. Best is trial 96 with value: 0.18169342721982126.
Fold 1 IBS: 0.21437178286237804
Fold 2 IBS: 0.1868974008575985
Fold 3 IBS: 0.17228530252808472
Fold 4 IBS: 0.21460932205716682
Fold 5 IBS: 0.18695890741970617
[I 2024-04-16 05:16:25,188] Trial 99 finished with value: 0.19502454314498685 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.43419374581955783, 'n_estimators': 45, 'learning_rate': 0.05478497327406729}. Best is trial 96 with value: 0.18169342721982126.


* Best trial for IBS:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.18169342721982126], datetime_start=datetime.datetime(2024, 4, 16, 5, 16, 20, 713582), datetime_complete=datetime.datetime(2024, 4, 16, 5, 16, 21, 248105), params={'subsample': 0.10080401063092843, 'dropout_rate': 0.3564078078462598, 'n_estimators': 84, 'learning_rate': 0.039295022656166335}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=96, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10080401063092843, 'dropout_rate': 0.3564078078462598, 'n_estimators': 84, 'learning_rate': 0.039295022656166335}


* Best Score for IBS:
 0.18169342721982126

In [74]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [75]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.713
train_ibs:  0.182

#### Test

In [76]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [77]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3170885754967726,
                                              learning_rate=0.017271336468030765,
                                              n_estimators=364,
                                              random_state=123,
                                              subsample=0.11004058121439181)

C-index score: 0.576

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3564078078462598,
                                              learning_rate=0.039295022656166335,
                                              n_estimators=84, random_state=123,
                                              subsample=0.10080401063092843)

IBS: 0.229

In [78]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [79]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.849   1.0
ExtraSurvivalTrees               0.839   2.0
GradientBoosting                 0.751   3.0
CoxElastic                       0.737   4.0
CoxLasso                         0.736   5.0
CoxPH                            0.735   6.0
CoxRidge                         0.718   7.0
ComponentwiseGradientBoosting    0.713   8.0

In [80]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxLasso                       0.161   1.5
CoxElastic                     0.161   1.5
CoxPH                          0.162   3.0
Randomsurvivalforest           0.172   4.5
ExtraSurvivalTrees             0.172   4.5
ComponentwiseGradientBoosting  0.182   6.0
GradientBoosting               0.202   7.0
CoxRidge                       0.217   8.0

In [81]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
CoxRidge                         0.585   1.0
GradientBoosting                 0.576   2.5
ComponentwiseGradientBoosting    0.576   2.5
ExtraSurvivalTrees               0.574   4.0
CoxPH                            0.558   5.5
CoxElastic                       0.558   5.5
CoxLasso                         0.556   7.0
Randomsurvivalforest             0.555   8.0

In [82]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.217   1.0
CoxRidge                       0.221   2.0
ExtraSurvivalTrees             0.222   3.0
Randomsurvivalforest           0.226   4.0
ComponentwiseGradientBoosting  0.229   5.0
CoxLasso                       0.251   6.5
CoxElastic                     0.251   6.5
CoxPH                          0.252   8.0

In [85]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/standard/plsr/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_standard_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [86]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-16