In [27]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [28]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [29]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [30]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [31]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [32]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [33]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.07
LBP_003_PET                                                      0.00 0.98      0.03
LBP_012_CT                                                       0.00 0.97      0.04
LBP_012_PET                                                      0.00 0.98      0.03
LBP_021_CT                                                       0.00 0.98      0.02
LBP_021_PET                                                      0.00 0.95      0.08
LBP_030_CT                                                       0.00 1.00      0.01
LBP_030_PET                                                      0.00 0.96      0.05
LBP_102_CT                                                       0.00 0.95      0.08
LBP_102_PET                                                      0.00 0.97      0.05
LBP_111_CT                                                       0.02 0.88      0.18
LBP_111_PET                                                      0.01 0.91      0.14
LBP_120_CT                                                       0.00 0.98      0.03
LBP_120_PET                                                      0.00 0.97      0.04
LBP_201_CT                                                       0.01 0.93      0.10
LBP_201_PET                                                      0.00 0.99      0.02
LBP_210_CT                                                       0.00 0.94      0.08
LBP_210_PET                                                      0.01 0.92      0.12
LBP_300_CT                                                       0.00 0.98      0.04
LBP_300_PET                                                      0.02 0.90      0.15
first_order_10Percentile_CT                                      0.00 0.96      0.06
first_order_10Percentile_PET                                     0.00 0.96      0.06
first_order_90Percentile_CT                                      0.00 0.98      0.04
first_order_90Percentile_PET                                     0.00 0.98      0.03
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 1.00      0.00
first_order_Entropy_CT_c16                                       0.00 0.99      0.02
first_order_Entropy_PET_b2                                       0.00 0.98      0.02
first_order_Entropy_PET_c04                                      0.00 0.98      0.02
first_order_InterquartileRange_CT                                0.01 0.94      0.09
first_order_InterquartileRange_PET                               0.00 1.00      0.00
first_order_Kurtosis_CT                                          0.00 0.99      0.02
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.00 0.97      0.04
first_order_Maximum_PET                                          0.00 0.99      0.01
first_order_MeanAbsoluteDeviation_CT                             0.00 1.00      0.00
first_order_MeanAbsoluteDeviation_PET                            0.00 0.98      0.02
first_order_Mean_CT                                              0.00 0.99      0.01
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.99      0.02
first_order_Median_PET                                           0.00 0.97      0.04
first_order_Minimum_CT                                           0.00 1.00      0.00
first_order_Minimum_PET                                          0.03 0.87      0.20
first_order_Range_CT                                             0.00 0.98      0.03
first_order_Range_PET                                            0.00 0.99      0.02
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.98      0.03
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 1.00      0.00
first_order_RootMeanSquared_CT                                   0.00 0.99      0.01
first_order_RootMeanSquared_PET                                  0.00 1.00      0.01
first_order_Skewness_CT                                          0.00 0.97      0.05
first_order_Skewness_PET                                         0.00 0.96      0.06
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.95      0.08
first_order_Uniformity_CT_c16                                    0.00 0.97      0.05
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 0.99      0.02
first_order_Variance_CT                                          0.00 0.99      0.01
first_order_Variance_PET                                         0.00 0.98      0.03
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_CT_c16                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 1.00      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.99      0.02
glcm_ClusterProminence_d_1_CT_b20                                0.00 0.99      0.01
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.96      0.06
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.96      0.07
glcm_ClusterProminence_d_1_PET_c04                               0.01 0.93      0.10
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_c16                                     0.00 0.99      0.01
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.95      0.08
glcm_ClusterShade_d_1_PET_c04                                    0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_b20                                  0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.98      0.03
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.02
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.99      0.01
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.01
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.01
glcm_Contrast_d_1_PET_b2                                         0.00 0.99      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.98      0.03
glcm_Correlation_d_1_CT_b20                                      0.00 1.00      0.01
glcm_Correlation_d_1_CT_c16                                      0.01 0.94      0.10
glcm_Correlation_d_1_PET_b2                                      0.00 0.98      0.04
glcm_Correlation_d_1_PET_c04                                     0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_b20                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.02
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_b20                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_b2                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.97      0.05
glcm_Id_d_1_CT_b20                                               0.00 0.99      0.01
glcm_Id_d_1_CT_c16                                               0.00 1.00      0.01
glcm_Id_d_1_PET_b2                                               0.00 0.99      0.02
glcm_Id_d_1_PET_c04                                              0.00 0.99      0.01
glcm_Idm_d_1_CT_b20                                              0.00 0.99      0.01
glcm_Idm_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idm_d_1_PET_c04                                             0.00 0.99      0.01
glcm_Idmn_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_c16                                             0.00 0.98      0.02
glcm_Idmn_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Idmn_d_1_PET_c04                                            0.00 0.98      0.02
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idn_d_1_CT_c16                                              0.00 0.99      0.01
glcm_Idn_d_1_PET_b2                                              0.00 1.00      0.00
glcm_Idn_d_1_PET_c04                                             0.00 0.99      0.01
glcm_Imc1_d_1_CT_b20                                             0.00 0.95      0.08
glcm_Imc1_d_1_CT_c16                                             0.01 0.92      0.11
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.02
glcm_Imc2_d_1_CT_b20                                             0.01 0.94      0.09
glcm_Imc2_d_1_CT_c16                                             0.00 0.98      0.03
glcm_Imc2_d_1_PET_b2                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.95      0.08
glcm_InverseVariance_d_1_CT_b20                                  0.00 0.97      0.05
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_b2                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.00
glcm_JointAverage_d_1_CT_b20                                     0.00 0.99      0.01
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_b2                                     0.00 0.98      0.02
glcm_JointAverage_d_1_PET_c04                                    0.00 1.00      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.96      0.07
glcm_JointEnergy_d_1_CT_c16                                      0.00 0.99      0.02
glcm_JointEnergy_d_1_PET_b2                                      0.00 0.98      0.03
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.95      0.07
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.01 0.94      0.10
glcm_MCC_d_1_CT_c16                                              0.00 0.96      0.05
glcm_MCC_d_1_PET_b2                                              0.00 0.98      0.03
glcm_MCC_d_1_PET_c04                                             0.00 0.98      0.03
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.98      0.03
glcm_MaximumProbability_d_1_CT_c16                               0.00 0.96      0.07
glcm_MaximumProbability_d_1_PET_b2                               0.00 0.96      0.06
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.95      0.08
glcm_SumAverage_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_b2                                       0.00 0.98      0.02
glcm_SumAverage_d_1_PET_c04                                      0.00 1.00      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.99      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_b2                                       0.00 0.98      0.03
glcm_SumEntropy_d_1_PET_c04                                      0.00 1.00      0.01
glcm_SumSquares_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumSquares_d_1_CT_c16                                       0.00 0.98      0.03
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_c04                                      0.00 1.00      0.01
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.01 0.94      0.09
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 0.97      0.04
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 0.96      0.06
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.05
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.98      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.96      0.06
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.96      0.06
gldm_DependenceVariance_d_1_CT_c16                               0.01 0.93      0.11
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.96      0.06
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.98      0.02
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.98      0.02
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 0.98      0.02
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 1.00      0.00
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.98      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.95      0.08
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.98      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.96      0.05
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.95      0.08
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 0.96      0.06
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.03
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.95      0.07
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.01 0.94      0.09
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.98      0.04
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.98      0.03
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.01 0.92      0.12
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.97      0.04
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.01 0.92      0.13
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.99      0.01
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.97      0.05
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.97      0.04
glrlm_GrayLevelNonUniformity_CT_c16                              0.01 0.94      0.10
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.98      0.03
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.98      0.02
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.95      0.08
glrlm_GrayLevelVariance_PET_b2                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_PET_c04                                  0.00 0.97      0.05
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.00 0.99      0.01
glrlm_HighGrayLevelRunEmphasis_CT_c16                            0.00 0.99      0.01
glrlm_HighGrayLevelRunEmphasis_PET_b2                            0.00 0.98      0.03
glrlm_HighGrayLevelRunEmphasis_PET_c04                           0.00 0.96      0.06
glrlm_LongRunEmphasis_CT_b20                                     0.00 0.97      0.04
glrlm_LongRunEmphasis_CT_c16                                     0.00 0.96      0.06

In [34]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [35]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic      p  -log2(p)
LBP_003_CT                                                       0.16   0.69      0.53
LBP_003_PET                                                      0.13   0.72      0.48
LBP_012_CT                                                       0.03   0.86      0.21
LBP_012_PET                                                      0.11   0.75      0.42
LBP_021_CT                                                       2.78   0.10      3.39
LBP_021_PET                                                      0.02   0.90      0.15
LBP_030_CT                                                       0.06   0.81      0.30
LBP_030_PET                                                      0.00   0.98      0.02
LBP_102_CT                                                       0.04   0.85      0.24
LBP_102_PET                                                      1.17   0.28      1.84
LBP_111_CT                                                       0.06   0.80      0.32
LBP_111_PET                                                      0.07   0.79      0.33
LBP_120_CT                                                       0.06   0.81      0.30
LBP_120_PET                                                      0.00   1.00      0.00
LBP_201_CT                                                       1.42   0.23      2.10
LBP_201_PET                                                      0.36   0.55      0.87
LBP_210_CT                                                       0.69   0.41      1.30
LBP_210_PET                                                      0.06   0.81      0.31
LBP_300_CT                                                       0.06   0.81      0.30
LBP_300_PET                                                      0.18   0.67      0.58
first_order_10Percentile_CT                                      0.06   0.80      0.32
first_order_10Percentile_PET                                     0.40   0.53      0.93
first_order_90Percentile_CT                                      0.75   0.39      1.37
first_order_90Percentile_PET                                     0.00   1.00      0.00
first_order_Energy_CT                                            0.00   0.99      0.02
first_order_Energy_PET                                           0.71   0.40      1.32
first_order_Entropy_CT_b20                                       0.01   0.92      0.12
first_order_Entropy_CT_c16                                       0.13   0.72      0.48
first_order_Entropy_PET_b2                                       0.03   0.85      0.23
first_order_Entropy_PET_c04                                      0.01   0.91      0.13
first_order_InterquartileRange_CT                                0.19   0.66      0.60
first_order_InterquartileRange_PET                               0.01   0.93      0.11
first_order_Kurtosis_CT                                          0.00   1.00      0.00
first_order_Kurtosis_PET                                         0.00   0.95      0.08
first_order_Maximum_CT                                           0.23   0.63      0.67
first_order_Maximum_PET                                          0.00   0.97      0.04
first_order_MeanAbsoluteDeviation_CT                             0.02   0.89      0.17
first_order_MeanAbsoluteDeviation_PET                            0.01   0.93      0.11
first_order_Mean_CT                                              0.00   0.95      0.07
first_order_Mean_PET                                             0.01   0.93      0.11
first_order_Median_CT                                            0.00   1.00      0.00
first_order_Median_PET                                           0.00   1.00      0.00
first_order_Minimum_CT                                           0.00   0.95      0.07
first_order_Minimum_PET                                          1.59   0.21      2.27
first_order_Range_CT                                             0.13   0.72      0.48
first_order_Range_PET                                            0.00   0.97      0.04
first_order_RobustMeanAbsoluteDeviation_CT                       0.04   0.85      0.24
first_order_RobustMeanAbsoluteDeviation_PET                      0.01   0.92      0.12
first_order_RootMeanSquared_CT                                   0.01   0.93      0.11
first_order_RootMeanSquared_PET                                  0.00   0.95      0.07
first_order_Skewness_CT                                          0.30   0.58      0.78
first_order_Skewness_PET                                         0.00   0.99      0.02
first_order_TotalEnergy_CT                                       0.00   0.99      0.02
first_order_TotalEnergy_PET                                      0.71   0.40      1.32
first_order_Uniformity_CT_b20                                    0.11   0.75      0.42
first_order_Uniformity_CT_c16                                    0.06   0.81      0.31
first_order_Uniformity_PET_b2                                    0.00   0.97      0.04
first_order_Uniformity_PET_c04                                   0.01   0.93      0.10
first_order_Variance_CT                                          0.02   0.90      0.15
first_order_Variance_PET                                         0.10   0.75      0.42
glcm_Autocorrelation_d_1_CT_b20                                  0.03   0.87      0.21
glcm_Autocorrelation_d_1_CT_c16                                  0.04   0.84      0.25
glcm_Autocorrelation_d_1_PET_b2                                  0.05   0.82      0.28
glcm_Autocorrelation_d_1_PET_c04                                 0.00   1.00      0.00
glcm_ClusterProminence_d_1_CT_b20                                0.04   0.83      0.26
glcm_ClusterProminence_d_1_CT_c16                                0.09   0.77      0.38
glcm_ClusterProminence_d_1_PET_b2                                2.52   0.11      3.16
glcm_ClusterProminence_d_1_PET_c04                               0.01   0.92      0.12
glcm_ClusterShade_d_1_CT_b20                                     1.36   0.24      2.04
glcm_ClusterShade_d_1_CT_c16                                     0.14   0.71      0.50
glcm_ClusterShade_d_1_PET_b2                                     6.64   0.01      6.65
glcm_ClusterShade_d_1_PET_c04                                    0.17   0.68      0.56
glcm_ClusterTendency_d_1_CT_b20                                  0.08   0.78      0.36
glcm_ClusterTendency_d_1_CT_c16                                  0.11   0.74      0.44
glcm_ClusterTendency_d_1_PET_b2                                  0.11   0.75      0.42
glcm_ClusterTendency_d_1_PET_c04                                 0.01   0.91      0.14
glcm_Contrast_d_1_CT_b20                                         0.00   0.97      0.04
glcm_Contrast_d_1_CT_c16                                         0.04   0.84      0.25
glcm_Contrast_d_1_PET_b2                                         0.00   0.96      0.06
glcm_Contrast_d_1_PET_c04                                        0.01   0.93      0.10
glcm_Correlation_d_1_CT_b20                                      0.06   0.81      0.30
glcm_Correlation_d_1_CT_c16                                      0.37   0.54      0.88
glcm_Correlation_d_1_PET_b2                                      0.01   0.93      0.10
glcm_Correlation_d_1_PET_c04                                     0.00   0.98      0.02
glcm_DifferenceAverage_d_1_CT_b20                                0.01   0.91      0.13
glcm_DifferenceAverage_d_1_CT_c16                                0.00   0.96      0.06
glcm_DifferenceAverage_d_1_PET_b2                                0.05   0.83      0.27
glcm_DifferenceAverage_d_1_PET_c04                               0.00   0.99      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00   0.98      0.03
glcm_DifferenceEntropy_d_1_CT_c16                                0.00   0.96      0.07
glcm_DifferenceEntropy_d_1_PET_b2                                0.00   0.94      0.08
glcm_DifferenceEntropy_d_1_PET_c04                               0.04   0.84      0.25
glcm_DifferenceVariance_d_1_CT_b20                               0.00   0.96      0.06
glcm_DifferenceVariance_d_1_CT_c16                               0.07   0.80      0.33
glcm_DifferenceVariance_d_1_PET_b2                               0.00   0.99      0.01
glcm_DifferenceVariance_d_1_PET_c04                              0.03   0.85      0.23
glcm_Id_d_1_CT_b20                                               0.03   0.87      0.20
glcm_Id_d_1_CT_c16                                               0.00   1.00      0.00
glcm_Id_d_1_PET_b2                                               0.08   0.77      0.37
glcm_Id_d_1_PET_c04                                              0.00   0.95      0.07
glcm_Idm_d_1_CT_b20                                              0.03   0.87      0.20
glcm_Idm_d_1_CT_c16                                              0.00   0.99      0.02
glcm_Idm_d_1_PET_b2                                              0.07   0.79      0.33
glcm_Idm_d_1_PET_c04                                             0.00   0.97      0.05
glcm_Idmn_d_1_CT_b20                                             0.05   0.82      0.29
glcm_Idmn_d_1_CT_c16                                             0.03   0.86      0.21
glcm_Idmn_d_1_PET_b2                                             0.64   0.42      1.24
glcm_Idmn_d_1_PET_c04                                            0.01   0.94      0.09
glcm_Idn_d_1_CT_b20                                              0.02   0.88      0.18
glcm_Idn_d_1_CT_c16                                              0.00   0.98      0.03
glcm_Idn_d_1_PET_b2                                              0.09   0.76      0.40
glcm_Idn_d_1_PET_c04                                             0.00   0.98      0.03
glcm_Imc1_d_1_CT_b20                                             0.00   0.96      0.05
glcm_Imc1_d_1_CT_c16                                             0.44   0.51      0.97
glcm_Imc1_d_1_PET_b2                                             0.02   0.90      0.16
glcm_Imc1_d_1_PET_c04                                            0.00   0.98      0.03
glcm_Imc2_d_1_CT_b20                                             0.07   0.79      0.35
glcm_Imc2_d_1_CT_c16                                             0.98   0.32      1.63
glcm_Imc2_d_1_PET_b2                                             0.06   0.80      0.32
glcm_Imc2_d_1_PET_c04                                            0.01   0.92      0.11
glcm_InverseVariance_d_1_CT_b20                                  0.02   0.88      0.19
glcm_InverseVariance_d_1_CT_c16                                  0.01   0.92      0.12
glcm_InverseVariance_d_1_PET_b2                                  0.17   0.68      0.56
glcm_InverseVariance_d_1_PET_c04                                 0.02   0.88      0.19
glcm_JointAverage_d_1_CT_b20                                     0.00   0.97      0.05
glcm_JointAverage_d_1_CT_c16                                     0.13   0.72      0.47
glcm_JointAverage_d_1_PET_b2                                     0.01   0.92      0.13
glcm_JointAverage_d_1_PET_c04                                    0.00   0.98      0.03
glcm_JointEnergy_d_1_CT_b20                                      0.29   0.59      0.77
glcm_JointEnergy_d_1_CT_c16                                      0.06   0.80      0.31
glcm_JointEnergy_d_1_PET_b2                                      0.01   0.92      0.13
glcm_JointEnergy_d_1_PET_c04                                     0.01   0.92      0.12
glcm_JointEntropy_d_1_CT_b20                                     0.00   0.98      0.03
glcm_JointEntropy_d_1_CT_c16                                     0.11   0.73      0.44
glcm_JointEntropy_d_1_PET_b2                                     0.04   0.85      0.24
glcm_JointEntropy_d_1_PET_c04                                    0.01   0.91      0.13
glcm_MCC_d_1_CT_b20                                              0.05   0.83      0.27
glcm_MCC_d_1_CT_c16                                              0.04   0.85      0.24
glcm_MCC_d_1_PET_b2                                              0.00   0.96      0.05
glcm_MCC_d_1_PET_c04                                             0.04   0.84      0.25
glcm_MaximumProbability_d_1_CT_b20                               0.07   0.79      0.34
glcm_MaximumProbability_d_1_CT_c16                               0.03   0.87      0.20
glcm_MaximumProbability_d_1_PET_b2                               0.06   0.80      0.32
glcm_MaximumProbability_d_1_PET_c04                              0.00   0.97      0.04
glcm_SumAverage_d_1_CT_b20                                       0.00   0.97      0.05
glcm_SumAverage_d_1_CT_c16                                       0.13   0.72      0.47
glcm_SumAverage_d_1_PET_b2                                       0.01   0.92      0.13
glcm_SumAverage_d_1_PET_c04                                      0.00   0.98      0.03
glcm_SumEntropy_d_1_CT_b20                                       0.00   0.98      0.03
glcm_SumEntropy_d_1_CT_c16                                       0.15   0.70      0.51
glcm_SumEntropy_d_1_PET_b2                                       0.04   0.85      0.23
glcm_SumEntropy_d_1_PET_c04                                      0.03   0.85      0.23
glcm_SumSquares_d_1_CT_b20                                       0.07   0.80      0.33
glcm_SumSquares_d_1_CT_c16                                       0.08   0.77      0.37
glcm_SumSquares_d_1_PET_b2                                       0.10   0.75      0.42
glcm_SumSquares_d_1_PET_c04                                      0.01   0.91      0.13
gldm_DependenceEntropy_d_1_CT_b20                                0.11   0.74      0.43
gldm_DependenceEntropy_d_1_CT_c16                                0.36   0.55      0.87
gldm_DependenceEntropy_d_1_PET_b2                                0.01   0.93      0.11
gldm_DependenceEntropy_d_1_PET_c04                               0.46   0.50      1.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.08   0.78      0.36
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.11   0.75      0.42
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.67   0.41      1.27
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.04   0.84      0.24
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00   0.96      0.05
gldm_DependenceNonUniformity_d_1_CT_c16                          1.71   0.19      2.38
gldm_DependenceNonUniformity_d_1_PET_b2                          0.07   0.80      0.33
gldm_DependenceNonUniformity_d_1_PET_c04                         0.14   0.71      0.50
gldm_DependenceVariance_d_1_CT_b20                               1.43   0.23      2.11
gldm_DependenceVariance_d_1_CT_c16                               0.01   0.94      0.09
gldm_DependenceVariance_d_1_PET_b2                               0.01   0.93      0.10
gldm_DependenceVariance_d_1_PET_c04                              0.75   0.38      1.38
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.39   0.53      0.91
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.30   0.58      0.78
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.01   0.91      0.14
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00   0.99      0.02
gldm_GrayLevelVariance_d_1_CT_b20                                0.01   0.90      0.15
gldm_GrayLevelVariance_d_1_CT_c16                                0.02   0.90      0.16
gldm_GrayLevelVariance_d_1_PET_b2                                0.09   0.76      0.39
gldm_GrayLevelVariance_d_1_PET_c04                               0.00   0.96      0.06
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.05   0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.03   0.85      0.23
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.05   0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00   0.97      0.04
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.01   0.90      0.15
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.05   0.82      0.28
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.16   0.69      0.53
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00   0.97      0.04
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.27   0.60      0.73
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.02   0.88      0.19
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.08   0.78      0.36
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00   0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.03   0.87      0.21
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.05   0.83      0.27
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.05   0.82      0.29
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.23   0.63      0.66
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.11   0.74      0.43
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00   0.95      0.07
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00   0.96      0.06
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.05   0.83      0.27
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.02   0.89      0.17
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00   0.95      0.07
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.08   0.78      0.36
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00   0.98      0.03
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.22   0.64      0.65
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.01   0.93      0.10
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.24   0.63      0.67
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.06   0.81      0.31
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.06   0.80      0.32
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.03   0.87      0.21
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.37   0.54      0.88
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.30   0.58      0.78
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.04   0.84      0.26
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.17   0.68      0.55
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00   0.95      0.08
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.15   0.70      0.52
glrlm_GrayLevelNonUniformity_CT_b20                              0.00   1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.57   0.45      1.15
glrlm_GrayLevelNonUniformity_PET_b2                              0.04   0.83      0.26
glrlm_GrayLevelNonUniformity_PET_c04                             0.00   0.99      0.01
glrlm_GrayLevelVariance_CT_b20                                   0.00   0.97      0.04
glrlm_GrayLevelVariance_CT_c16                                   0.01   0.92      0.12
glrlm_GrayLevelVariance_PET_b2                                   0.10   0.75      0.41
glrlm_GrayLevelVariance_PET_c04                                  0.10   0.75      0.42
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.03   0.87      0.21

In [36]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['glcm_ClusterShade_d_1_PET_b2',
       'glrlm_LongRunLowGrayLevelEmphasis_CT_c16',
       'glszm_GrayLevelNonUniformity_PET_c04',
       'glszm_LargeAreaEmphasis_CT_c16',
       'glszm_LargeAreaLowGrayLevelEmphasis_CT_c16',
       'glszm_ZoneVariance_CT_c16'],
      dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [37]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [38]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [39]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [40]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [41]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [42]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [43]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [44]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [46]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [47]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

In [48]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data[vif_data['VIF'] > 100000]

                           feature           VIF
0                 shape_Elongation  2.096355e+11
1                   shape_Flatness  3.609232e+11
2            shape_LeastAxisLength  2.691126e+12
3            shape_MajorAxisLength  7.524811e+12
4    shape_Maximum2DDiameterColumn  2.124339e+13
..                             ...           ...
369                    LBP_111_PET  5.922282e+11
370                    LBP_120_PET  3.305758e+11
371                    LBP_201_PET  1.508996e+12
372                    LBP_210_PET  1.369708e+12
373                    LBP_300_PET  7.392136e+09

[374 rows x 2 columns]

# Standardization

In [49]:
original_X = X.copy()

In [50]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

# Standardize non-categorical and then concat with the categorical
scaler = StandardScaler()  
X_std = scaler.fit_transform(X)
X_std = pd.DataFrame(X_std, columns=X_columns, index=X_index)

In [51]:
# Standardize the numeric part 
X_MAASTRO_column = X_MAASTRO.columns
X_MAASTRO_index = X_MAASTRO.index

X_MAASTRO_std = scaler.transform(X_MAASTRO)

# Change the standardized part into a dataframe 
X_MAASTRO_std = pd.DataFrame(X_MAASTRO_std, columns=X_MAASTRO_column, index=X_MAASTRO_index)

In [52]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [53]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:40:48,895] A new study created in memory with name: no-name-40d4a3c1-121a-4576-a354-100423593b61
python(82517) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-16 01:40:51,155] Trial 0 failed with parameters: {} because of the following error: LinAlgError('Matrix is singular.').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_81654/4028431732.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 449, in fit
    delta = solve(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 220, in solve
    _solve_check(n, info)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[W 2024-04-16 01:40:51,178] Trial 0 failed with value None.

LinAlgError: Matrix is singular.

In [54]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

LinAlgError: Matrix is singular.

In [58]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [59]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:49:41,247] A new study created in memory with name: no-name-1c0b5bf8-4789-415d-bef5-63c0383f64cf

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7151898734177216

[I 2024-04-16 09:49:42,050] A new study created in memory with name: no-name-e60780e9-76d8-4aa9-840e-96f4a5091e04

Fold 5 C-index: 0.6971830985915493
[I 2024-04-16 09:49:42,040] Trial 0 finished with value: 0.6979794327008101 and parameters: {}. Best is trial 0 with value: 0.6979794327008101.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6979794327008101], datetime_start=datetime.datetime(2024, 4, 16, 9, 49, 41, 346876), datetime_complete=datetime.datetime(2024, 4, 16, 9, 49, 42, 38938), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6979794327008101

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651743727053
Fold 2 IBS: 0.22157791159752618
Fold 3 IBS: 0.20453593920513286
Fold 4 IBS: 0.22473803623356947
Fold 5 IBS: 0.21812430785364773
[I 2024-04-16 09:49:43,081] Trial 0 finished with value: 0.21659054246542936 and parameters: {}. Best is trial 0 with value: 0.21659054246542936.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054246542936], datetime_start=datetime.datetime(2024, 4, 16, 9, 49, 42, 198811), datetime_complete=datetime.datetime(2024, 4, 16, 9, 49, 43, 80688), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054246542936

In [61]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [62]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.698
train_ibs:  0.217

#### Test

In [63]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [64]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.586

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [65]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [66]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:49:43,538] A new study created in memory with name: no-name-6bf5df5a-4149-4905-9669-7f50ef02adfa

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.48214285714285715
Fold 3 C-index: 0.46078431372549017
Fold 4 C-index: 0.5738396624472574

[I 2024-04-16 09:49:48,577] A new study created in memory with name: no-name-2871781a-bef6-4cb0-8807-43c3cf535e81

Fold 5 C-index: 0.5821596244131455
[I 2024-04-16 09:49:48,557] Trial 0 finished with value: 0.5409974127578712 and parameters: {}. Best is trial 0 with value: 0.5409974127578712.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5409974127578712], datetime_start=datetime.datetime(2024, 4, 16, 9, 49, 43, 602182), datetime_complete=datetime.datetime(2024, 4, 16, 9, 49, 48, 556718), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5409974127578712

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.3951989555259915
Fold 2 IBS: 0.4946714020030033
Fold 3 IBS: 0.42816946690567437
Fold 4 IBS: 0.33291518222236205
Fold 5 IBS: 0.3096472267208097
[I 2024-04-16 09:49:55,048] Trial 0 finished with value: 0.39212044667556817 and parameters: {}. Best is trial 0 with value: 0.39212044667556817.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.39212044667556817], datetime_start=datetime.datetime(2024, 4, 16, 9, 49, 48, 620984), datetime_complete=datetime.datetime(2024, 4, 16, 9, 49, 55, 47450), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.39212044667556817

In [67]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [68]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.541
train_ibs:  0.392

#### Test

In [69]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [70]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.5

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.43

In [71]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [72]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:49:57,567] A new study created in memory with name: no-name-7e57dc36-46bd-46d3-98f0-5192775006d0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.5
Fold 3 C-index: 0.4950980392156863
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 09:50:01,236] Trial 0 finished with value: 0.5666626737568397 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.5666626737568397.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5491071428571429
Fold 3 C-index: 0.5980392156862745
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:50:03,571] Trial 1 finished with value: 0.6058402500451388 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6058402500451388.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5491071428571429
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:50:06,023] Trial 2 finished with value: 0.6134103666993953 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.5343137254901961
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:50:09,865] Trial 3 finished with value: 0.5823968714132762 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.5
Fold 3 C-index: 0.4950980392156863
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 09:50:14,130] Trial 4 finished with value: 0.5666626737568397 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5357142857142857
Fold 3 C-index: 0.5245098039215687
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:50:17,183] Trial 5 finished with value: 0.5866729472709358 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.47767857142857145
Fold 3 C-index: 0.47058823529411764
Fold 4 C-index: 0.5822784810126582
Fold 5 C-index: 0.6009389671361502
[I 2024-04-16 09:50:21,112] Trial 6 finished with value: 0.5431799678574164 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.5
Fold 3 C-index: 0.4950980392156863
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 09:50:24,593] Trial 7 finished with value: 0.5666626737568397 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.5294117647058824
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:50:27,234] Trial 8 finished with value: 0.5832431662676254 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.53125
Fold 3 C-index: 0.5196078431372549
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 09:50:30,070] Trial 9 finished with value: 0.5875434331093172 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.6134103666993953.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:50:32,054] Trial 10 finished with value: 0.6391595259069931 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.6391595259069931.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 09:50:32,635] Trial 11 finished with value: 0.7014836715979443 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.7014836715979443.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:50:33,743] Trial 12 finished with value: 0.7073708888407955 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 09:50:34,197] Trial 13 finished with value: 0.7013961365839387 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:50:37,658] Trial 14 finished with value: 0.6211603728510643 and parameters: {'l1_ratio': 0.14337364566668}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 09:50:38,131] Trial 15 finished with value: 0.7032204105973416 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:50:41,008] Trial 16 finished with value: 0.6132767216920967 and parameters: {'l1_ratio': 0.21667088249320593}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.5446428571428571
Fold 3 C-index: 0.5931372549019608
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 09:50:43,965] Trial 17 finished with value: 0.6040401670157682 and parameters: {'l1_ratio': 0.305421948361187}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:50:45,908] Trial 18 finished with value: 0.6306090170958738 and parameters: {'l1_ratio': 0.10592027039041071}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.48660714285714285
Fold 3 C-index: 0.47058823529411764
Fold 4 C-index: 0.5822784810126582
Fold 5 C-index: 0.5868544600938967
[I 2024-04-16 09:50:51,203] Trial 19 finished with value: 0.5464777850636843 and parameters: {'l1_ratio': 0.9947379076423366}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5758928571428571
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:50:53,996] Trial 20 finished with value: 0.6165458014110521 and parameters: {'l1_ratio': 0.1697322474598469}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 09:50:54,595] Trial 21 finished with value: 0.7014836715979443 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 09:50:56,585] Trial 22 finished with value: 0.6464907762080504 and parameters: {'l1_ratio': 0.057979425955040985}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 09:50:56,943] Trial 23 finished with value: 0.7004571694477886 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 12 with value: 0.7073708888407955.

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:50:58,704] Trial 24 finished with value: 0.6229190308597222 and parameters: {'l1_ratio': 0.13208343776906337}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.5401785714285714
Fold 3 C-index: 0.5686274509803921
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:01,031] Trial 25 finished with value: 0.5963674148162968 and parameters: {'l1_ratio': 0.3370963772856702}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 09:51:03,388] Trial 26 finished with value: 0.6104183952629334 and parameters: {'l1_ratio': 0.20688108474704453}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:06,148] Trial 27 finished with value: 0.6332771729658166 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5446428571428571
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:51:09,041] Trial 28 finished with value: 0.6098493536865954 and parameters: {'l1_ratio': 0.25028937407525237}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.49107142857142855
Fold 3 C-index: 0.5049019607843137
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 09:51:12,518] Trial 29 finished with value: 0.5599696846436593 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 09:51:14,619] Trial 30 finished with value: 0.6629830376695971 and parameters: {'l1_ratio': 0.05188661085205767}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 09:51:15,077] Trial 31 finished with value: 0.7004571694477886 and parameters: {'l1_ratio': 0.00012661512081217803}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 09:51:16,764] Trial 32 finished with value: 0.6463761849169886 and parameters: {'l1_ratio': 0.0590523030616818}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5758928571428571
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:51:19,332] Trial 33 finished with value: 0.6165458014110521 and parameters: {'l1_ratio': 0.16797374302867765}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 09:51:20,746] Trial 34 finished with value: 0.6657538290847547 and parameters: {'l1_ratio': 0.04199244318346156}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.5089285714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 09:51:23,088] Trial 35 finished with value: 0.5693849421808951 and parameters: {'l1_ratio': 0.638407091943248}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:25,059] Trial 36 finished with value: 0.6230555411600449 and parameters: {'l1_ratio': 0.1267646661152233}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5491071428571429
Fold 3 C-index: 0.5980392156862745
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:51:27,706] Trial 37 finished with value: 0.6058402500451388 and parameters: {'l1_ratio': 0.27624996967028986}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.4955357142857143
Fold 3 C-index: 0.4950980392156863
Fold 4 C-index: 0.6033755274261603
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:51:31,181] Trial 38 finished with value: 0.5633113373147116 and parameters: {'l1_ratio': 0.8102383761012125}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.5392156862745098
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:33,661] Trial 39 finished with value: 0.5834504298404883 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:51:35,922] Trial 40 finished with value: 0.613943261545854 and parameters: {'l1_ratio': 0.1878786381007522}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 09:51:36,260] Trial 41 finished with value: 0.7023275534544845 and parameters: {'l1_ratio': 0.008409175935282488}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 09:51:37,468] Trial 42 finished with value: 0.6999958005212166 and parameters: {'l1_ratio': 0.037490519428612895}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:39,819] Trial 43 finished with value: 0.6362183494364049 and parameters: {'l1_ratio': 0.08986056310065166}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 09:51:40,275] Trial 44 finished with value: 0.7004571694477886 and parameters: {'l1_ratio': 0.002224925056076751}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:42,808] Trial 45 finished with value: 0.6220751490031822 and parameters: {'l1_ratio': 0.1306027436723486}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.5892857142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:51:45,865] Trial 46 finished with value: 0.6383617540437463 and parameters: {'l1_ratio': 0.07829575158550738}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.53125
Fold 3 C-index: 0.5196078431372549
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 09:51:49,265] Trial 47 finished with value: 0.5875434331093172 and parameters: {'l1_ratio': 0.39975219214474955}. Best is trial 12 with value: 0.7073708888407955.

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 09:51:50,616] Trial 48 finished with value: 0.7008616013870175 and parameters: {'l1_ratio': 0.036675112124032225}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.5357142857142857
Fold 3 C-index: 0.5637254901960784
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:53,385] Trial 49 finished with value: 0.594494165516577 and parameters: {'l1_ratio': 0.3467452999146196}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.5267857142857143
Fold 3 C-index: 0.5294117647058824
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:55,340] Trial 50 finished with value: 0.5841360234104825 and parameters: {'l1_ratio': 0.47241766561900594}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 09:51:55,690] Trial 51 finished with value: 0.7032204105973416 and parameters: {'l1_ratio': 0.006311801453215545}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:51:57,236] Trial 52 finished with value: 0.6362183494364049 and parameters: {'l1_ratio': 0.08976384127675989}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 09:51:58,617] Trial 53 finished with value: 0.7046271537026941 and parameters: {'l1_ratio': 0.029688754152825993}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5758928571428571
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:52:00,608] Trial 54 finished with value: 0.6176407848589768 and parameters: {'l1_ratio': 0.1578020576532674}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:02,462] Trial 55 finished with value: 0.6297432162300729 and parameters: {'l1_ratio': 0.11190337170268685}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.5401785714285714
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:04,242] Trial 56 finished with value: 0.6089760025551898 and parameters: {'l1_ratio': 0.23862384123931288}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 09:52:05,770] Trial 57 finished with value: 0.6658413640987603 and parameters: {'l1_ratio': 0.04627845289750653}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 09:52:06,927] Trial 58 finished with value: 0.7046271537026941 and parameters: {'l1_ratio': 0.0292087833110701}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:52:08,398] Trial 59 finished with value: 0.6392546111866034 and parameters: {'l1_ratio': 0.07748904381770845}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 09:52:10,168] Trial 60 finished with value: 0.6140992778576285 and parameters: {'l1_ratio': 0.19500920557340767}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:10,999] Trial 61 finished with value: 0.7065050879749946 and parameters: {'l1_ratio': 0.027411909792402746}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 09:52:12,562] Trial 62 finished with value: 0.7046271537026941 and parameters: {'l1_ratio': 0.03297960174930781}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 09:52:13,847] Trial 63 finished with value: 0.6999958005212166 and parameters: {'l1_ratio': 0.03722530933569025}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:15,993] Trial 64 finished with value: 0.6230555411600449 and parameters: {'l1_ratio': 0.12524704351673455}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:52:17,812] Trial 65 finished with value: 0.641100804209267 and parameters: {'l1_ratio': 0.06933423153637847}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:52:19,703] Trial 66 finished with value: 0.619377523858374 and parameters: {'l1_ratio': 0.15437220082758205}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 09:52:21,178] Trial 67 finished with value: 0.7036881865665439 and parameters: {'l1_ratio': 0.03432146587868362}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:23,047] Trial 68 finished with value: 0.6306090170958738 and parameters: {'l1_ratio': 0.10585769991440544}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 09:52:24,243] Trial 69 finished with value: 0.7008616013870175 and parameters: {'l1_ratio': 0.036783630139033824}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:52:25,915] Trial 70 finished with value: 0.6401204120524042 and parameters: {'l1_ratio': 0.06688968094597025}. Best is trial 12 with value: 0.7073708888407955.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:27,088] Trial 71 finished with value: 0.7083512809976582 and parameters: {'l1_ratio': 0.025164283254476998}. Best is trial 71 with value: 0.7083512809976582.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:28,151] Trial 72 finished with value: 0.7065050879749946 and parameters: {'l1_ratio': 0.027827555802252914}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 09:52:29,219] Trial 73 finished with value: 0.7055661208388444 and parameters: {'l1_ratio': 0.028431585453955417}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:30,808] Trial 74 finished with value: 0.6297432162300729 and parameters: {'l1_ratio': 0.11166497528444252}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 09:52:32,530] Trial 75 finished with value: 0.6463761849169886 and parameters: {'l1_ratio': 0.060322463092681466}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:33,974] Trial 76 finished with value: 0.6352379572795421 and parameters: {'l1_ratio': 0.09141729101077001}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:34,600] Trial 77 finished with value: 0.7025198575191758 and parameters: {'l1_ratio': 0.02232347334420572}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:52:36,014] Trial 78 finished with value: 0.615652944268195 and parameters: {'l1_ratio': 0.17486763068397032}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 09:52:37,504] Trial 79 finished with value: 0.6185336420018339 and parameters: {'l1_ratio': 0.15586292560804332}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:52:38,757] Trial 80 finished with value: 0.6426520576220245 and parameters: {'l1_ratio': 0.06398487175585263}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 09:52:39,527] Trial 81 finished with value: 0.7046271537026941 and parameters: {'l1_ratio': 0.029745851153293923}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:40,140] Trial 82 finished with value: 0.701539465362313 and parameters: {'l1_ratio': 0.023101448423929014}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 09:52:40,546] Trial 83 finished with value: 0.7004571694477886 and parameters: {'l1_ratio': 0.0012286086866209155}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:41,736] Trial 84 finished with value: 0.6324332911092767 and parameters: {'l1_ratio': 0.09977175895656665}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:43,081] Trial 85 finished with value: 0.6229190308597222 and parameters: {'l1_ratio': 0.13257827709423287}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 09:52:44,269] Trial 86 finished with value: 0.6629830376695971 and parameters: {'l1_ratio': 0.050606978504896934}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:45,501] Trial 87 finished with value: 0.7083512809976582 and parameters: {'l1_ratio': 0.02473699915236134}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:47,124] Trial 88 finished with value: 0.6391595259069931 and parameters: {'l1_ratio': 0.08277689721657219}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.5
Fold 3 C-index: 0.49019607843137253
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 09:52:49,120] Trial 89 finished with value: 0.5655871963203667 and parameters: {'l1_ratio': 0.7258154676867495}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:49,788] Trial 90 finished with value: 0.701539465362313 and parameters: {'l1_ratio': 0.02404548493546527}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 09:52:50,859] Trial 91 finished with value: 0.6511686916780359 and parameters: {'l1_ratio': 0.05418951476245992}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:51,476] Trial 92 finished with value: 0.701539465362313 and parameters: {'l1_ratio': 0.02337989390425975}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 09:52:53,353] Trial 93 finished with value: 0.641100804209267 and parameters: {'l1_ratio': 0.0706575594512131}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:52:54,867] Trial 94 finished with value: 0.6229950624230957 and parameters: {'l1_ratio': 0.11841065690411981}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.48660714285714285
Fold 3 C-index: 0.49019607843137253
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 09:52:58,559] Trial 95 finished with value: 0.5561356510302138 and parameters: {'l1_ratio': 0.9190946752122768}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75

Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 09:52:59,253] Trial 96 finished with value: 0.7025198575191758 and parameters: {'l1_ratio': 0.02222533919898446}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 09:53:00,751] Trial 97 finished with value: 0.6648609719418975 and parameters: {'l1_ratio': 0.04699964147828871}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 09:53:01,146] Trial 98 finished with value: 0.7004571694477886 and parameters: {'l1_ratio': 0.0015828444660384265}. Best is trial 71 with value: 0.7083512809976582.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6540084388185654

[I 2024-04-16 09:53:02,828] A new study created in memory with name: no-name-6d3dd71a-0987-4ca8-b9ab-02c04bf55d23

Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 09:53:02,813] Trial 99 finished with value: 0.622140765007927 and parameters: {'l1_ratio': 0.14151882795491944}. Best is trial 71 with value: 0.7083512809976582.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.7083512809976582], datetime_start=datetime.datetime(2024, 4, 16, 9, 52, 25, 919983), datetime_complete=datetime.datetime(2024, 4, 16, 9, 52, 27, 81521), params={'l1_ratio': 0.025164283254476998}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=71, value=None)


* Best Score for C-index:
 0.7083512809976582

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.3553857989151826
Fold 2 IBS: 0.4113662233415645
Fold 3 IBS: 0.39839830737353576
Fold 4 IBS: 0.2999338715886926
Fold 5 IBS: 0.2525302607069104
[I 2024-04-16 09:53:05,007] Trial 0 finished with value: 0.34352289238517714 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.34352289238517714.
Fold 1 IBS: 0.3403896464980156
Fold 2 IBS: 0.34222993397115575
Fold 3 IBS: 0.2895050096292098
Fold 4 IBS: 0.2615594971797559
Fold 5 IBS: 0.22664790373670732
[I 2024-04-16 09:53:06,658] Trial 1 finished with value: 0.29206639820296887 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.29206639820296887.
Fold 1 IBS: 0.3319522647575167
Fold 2 IBS: 0.33499782694450664
Fold 3 IBS: 0.274212031131214
Fold 4 IBS: 0.25714328930631974
Fold 5 IBS: 0.22706925204032463
[I 2024-04-16 09:53:08,138] Trial 2 finished with value: 0.28507493283597635 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.3475661912833359
Fold 2 IBS: 0.3770840710595826
Fold 3 IBS: 0.3647686880445716
Fold 4 IBS: 0.28106557331155385
Fold 5 IBS: 0.23741071129211413
[I 2024-04-16 09:53:10,143] Trial 3 finished with value: 0.32157904699823164 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.358614046831325
Fold 2 IBS: 0.4158286371852042
Fold 3 IBS: 0.4009697622048838
Fold 4 IBS: 0.3042513229208936
Fold 5 IBS: 0.2549601970430482
[I 2024-04-16 09:53:11,995] Trial 4 finished with value: 0.3469247932370709 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.3478260765608865
Fold 2 IBS: 0.3579841246456976
Fold 3 IBS: 0.3265341310233856
Fold 4 IBS: 0.27161552883977697
Fold 5 IBS: 0.2299076759005879
[I 2024-04-16 09:53:13,842] Trial 5 finished with value: 0.3067735073940669 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.3905912545616689
Fold 2 IBS: 0.490490871007091
Fold 3 IBS: 0.41756070662187417
Fold 4 IBS: 0.3307931353604585
Fold 5 IBS: 0.30076822036341944
[I 2024-04-16 09:53:16,599] Trial 6 finished with value: 0.3860408375829024 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.3545330839815488
Fold 2 IBS: 0.4099047260449264
Fold 3 IBS: 0.3969485873306014
Fold 4 IBS: 0.29816236319666944
Fold 5 IBS: 0.251193442471152
[I 2024-04-16 09:53:18,677] Trial 7 finished with value: 0.3421484406049796 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.3470097659666608
Fold 2 IBS: 0.3658907208643069
Fold 3 IBS: 0.3434391331678279
Fold 4 IBS: 0.2755022059404465
Fold 5 IBS: 0.23298645904002607
[I 2024-04-16 09:53:20,423] Trial 8 finished with value: 0.31296565699585366 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.3471128934634308
Fold 2 IBS: 0.35434863405688016
Fold 3 IBS: 0.31687719868261977
Fold 4 IBS: 0.2695219171030469
Fold 5 IBS: 0.2287601905014011
[I 2024-04-16 09:53:22,106] Trial 9 finished with value: 0.3033241667614758 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.28507493283597635.
Fold 1 IBS: 0.29404109310837667
Fold 2 IBS: 0.2937366868132668
Fold 3 IBS: 0.22868501295507704
Fold 4 IBS: 0.24539531181336152
Fold 5 IBS: 0.23504291008109535
[I 2024-04-16 09:53:23,545] Trial 10 finished with value: 0.2593802029542355 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.2593802029542355.
Fold 1 IBS: 0.2134534664413671
Fold 2 IBS: 0.22091007376766633
Fold 3 IBS: 0.20362276527350207
Fold 4 IBS: 0.22412788393999766
Fold 5 IBS: 0.21727386593822973
[I 2024-04-16 09:53:23,831] Trial 11 finished with value: 0.2158776110721526 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2652042810310431
Fold 2 IBS: 0.2202047585901288
Fold 3 IBS: 0.1892114416874911
Fold 4 IBS: 0.22349806245306297
Fold 5 IBS: 0.2275270887024649
[I 2024-04-16 09:53:24,744] Trial 12 finished with value: 0.22512912649283817 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.21377613493095837
Fold 2 IBS: 0.22132661942480844
Fold 3 IBS: 0.2041797714639946
Fold 4 IBS: 0.224506646460254
Fold 5 IBS: 0.21779515233380034
[I 2024-04-16 09:53:25,131] Trial 13 finished with value: 0.21631686492276314 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3163193675446187
Fold 2 IBS: 0.3208906932112309
Fold 3 IBS: 0.25623136564978033
Fold 4 IBS: 0.2517826490297527
Fold 5 IBS: 0.23120292267547174
[I 2024-04-16 09:53:26,801] Trial 14 finished with value: 0.27528539962217086 and parameters: {'l1_ratio': 0.15622422014607515}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.21368960624212088
Fold 2 IBS: 0.221216072008341
Fold 3 IBS: 0.20402844221238625
Fold 4 IBS: 0.22440535427663955
Fold 5 IBS: 0.21765260589042365
[I 2024-04-16 09:53:27,165] Trial 15 finished with value: 0.21619841612598228 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3362082724075269
Fold 2 IBS: 0.33867995470925955
Fold 3 IBS: 0.28089273242507584
Fold 4 IBS: 0.2591756513596953
Fold 5 IBS: 0.22667962605535735
[I 2024-04-16 09:53:29,571] Trial 16 finished with value: 0.288327247391383 and parameters: {'l1_ratio': 0.25222274699079106}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3084236204417847
Fold 2 IBS: 0.3127466868474357
Fold 3 IBS: 0.24843584896804213
Fold 4 IBS: 0.24996713820210084
Fold 5 IBS: 0.23324180573174094
[I 2024-04-16 09:53:31,183] Trial 17 finished with value: 0.27056302003822086 and parameters: {'l1_ratio': 0.12995487925685328}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.34457935153024055
Fold 2 IBS: 0.34612612281586563
Fold 3 IBS: 0.29983978202923295
Fold 4 IBS: 0.26466287950648115
Fold 5 IBS: 0.22658812658198194
[I 2024-04-16 09:53:33,010] Trial 18 finished with value: 0.29635925249276046 and parameters: {'l1_ratio': 0.32442763221765025}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.39380337725047154
Fold 2 IBS: 0.4938904910165856
Fold 3 IBS: 0.4262116109244794
Fold 4 IBS: 0.33260333109274637
Fold 5 IBS: 0.30632027286240426
[I 2024-04-16 09:53:36,025] Trial 19 finished with value: 0.3905658166293374 and parameters: {'l1_ratio': 0.9950322275102852}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.32089617159629913
Fold 2 IBS: 0.32467452170184713
Fold 3 IBS: 0.2605690687186139
Fold 4 IBS: 0.2530089450413926
Fold 5 IBS: 0.22988939222607593
[I 2024-04-16 09:53:37,473] Trial 20 finished with value: 0.2778076198568457 and parameters: {'l1_ratio': 0.1727127145900301}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.21358239609218785
Fold 2 IBS: 0.22107732750345238
Fold 3 IBS: 0.20384296798260026
Fold 4 IBS: 0.22427865733220848
Fold 5 IBS: 0.21747557181721933
[I 2024-04-16 09:53:37,786] Trial 21 finished with value: 0.21605138414553365 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.21361840419233846
Fold 2 IBS: 0.22112414968357025
Fold 3 IBS: 0.2039050144715136
Fold 4 IBS: 0.22432136014122375
Fold 5 IBS: 0.21753508658167173
[I 2024-04-16 09:53:38,166] Trial 22 finished with value: 0.21610080301406356 and parameters: {'l1_ratio': 0.008242879725625268}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2985196422153246
Fold 2 IBS: 0.3003155835458803
Fold 3 IBS: 0.2350789339698251
Fold 4 IBS: 0.24701019253225218
Fold 5 IBS: 0.23486611926122497
[I 2024-04-16 09:53:39,723] Trial 23 finished with value: 0.2631580943049014 and parameters: {'l1_ratio': 0.0978346993365231}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.29144606517136423
Fold 2 IBS: 0.2898374863531701
Fold 3 IBS: 0.22497713172389444
Fold 4 IBS: 0.24449867294772737
Fold 5 IBS: 0.2349170917931257
[I 2024-04-16 09:53:40,936] Trial 24 finished with value: 0.25713528959785636 and parameters: {'l1_ratio': 0.07668620941751356}. Best is trial 11 with value: 0.2158776110721526.

Fold 1 IBS: 0.3192240074992903
Fold 2 IBS: 0.32344762238161084
Fold 3 IBS: 0.2590595935986579
Fold 4 IBS: 0.2526430043357355
Fold 5 IBS: 0.23033566460273056
[I 2024-04-16 09:53:42,315] Trial 25 finished with value: 0.276941978483605 and parameters: {'l1_ratio': 0.16690584651330848}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3747824246078294
Fold 2 IBS: 0.4360107780095121
Fold 3 IBS: 0.40648779968059867
Fold 4 IBS: 0.31897369761290323
Fold 5 IBS: 0.2660194668146372
[I 2024-04-16 09:53:44,413] Trial 26 finished with value: 0.3604548333450961 and parameters: {'l1_ratio': 0.8401513352750697}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.32520772497458367
Fold 2 IBS: 0.32868353816868084
Fold 3 IBS: 0.26491020503681695
Fold 4 IBS: 0.2545661773871685
Fold 5 IBS: 0.22863061131601403
[I 2024-04-16 09:53:45,765] Trial 27 finished with value: 0.2803996513766528 and parameters: {'l1_ratio': 0.19058100336990122}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3450937647368275
Fold 2 IBS: 0.34693964268031025
Fold 3 IBS: 0.30150494376225534
Fold 4 IBS: 0.2649319962944007
Fold 5 IBS: 0.22660762678553933
[I 2024-04-16 09:53:47,314] Trial 28 finished with value: 0.29701559485186657 and parameters: {'l1_ratio': 0.3306317027335334}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.28725952699509383
Fold 2 IBS: 0.28244848161590147
Fold 3 IBS: 0.21884711808613053
Fold 4 IBS: 0.24300058163240146
Fold 5 IBS: 0.23420987107156482
[I 2024-04-16 09:53:48,600] Trial 29 finished with value: 0.25315311588021844 and parameters: {'l1_ratio': 0.06575009779706541}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.21392357030246514
Fold 2 IBS: 0.22151213701897732
Fold 3 IBS: 0.20444104310437586
Fold 4 IBS: 0.2246773184254358
Fold 5 IBS: 0.2180374486947014
[I 2024-04-16 09:53:48,873] Trial 30 finished with value: 0.2165183035091911 and parameters: {'l1_ratio': 0.001179495256951958}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2139687746076524
Fold 2 IBS: 0.22156832036671278
Fold 3 IBS: 0.20452202632904073
Fold 4 IBS: 0.2247291756375174
Fold 5 IBS: 0.21811161037325075
[I 2024-04-16 09:53:49,162] Trial 31 finished with value: 0.2165799814628348 and parameters: {'l1_ratio': 0.00017175891605923643}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.28936081783158857
Fold 2 IBS: 0.28627685275412956
Fold 3 IBS: 0.2221136617969077
Fold 4 IBS: 0.24390685362915748
Fold 5 IBS: 0.23461711953048692
[I 2024-04-16 09:53:50,362] Trial 32 finished with value: 0.25525506110845403 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3339026177219873
Fold 2 IBS: 0.33670528473672945
Fold 3 IBS: 0.2772084769776256
Fold 4 IBS: 0.2580399169600834
Fold 5 IBS: 0.226883491010177
[I 2024-04-16 09:53:52,005] Trial 33 finished with value: 0.2865479574813205 and parameters: {'l1_ratio': 0.23820558034646938}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.306833686546338
Fold 2 IBS: 0.3109722071958462
Fold 3 IBS: 0.24626033057974198
Fold 4 IBS: 0.24938954558046014
Fold 5 IBS: 0.2336391041776724
[I 2024-04-16 09:53:53,472] Trial 34 finished with value: 0.26941897481601174 and parameters: {'l1_ratio': 0.12430185157472462}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2823478071583599
Fold 2 IBS: 0.27328287161928
Fold 3 IBS: 0.21136936347796156
Fold 4 IBS: 0.2413761792887159
Fold 5 IBS: 0.23319014594304835
[I 2024-04-16 09:53:54,749] Trial 35 finished with value: 0.24831327349747312 and parameters: {'l1_ratio': 0.05418308109354888}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.34929136888675094
Fold 2 IBS: 0.3889510334869231
Fold 3 IBS: 0.37749312674254176
Fold 4 IBS: 0.28585836911581525
Fold 5 IBS: 0.24146944730765796
[I 2024-04-16 09:53:57,130] Trial 36 finished with value: 0.32861266910793774 and parameters: {'l1_ratio': 0.5981321870977077}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3319406588782364
Fold 2 IBS: 0.33497374464605073
Fold 3 IBS: 0.2741862457414406
Fold 4 IBS: 0.2571383832872591
Fold 5 IBS: 0.22706865199146847
[I 2024-04-16 09:53:59,072] Trial 37 finished with value: 0.285061536908891 and parameters: {'l1_ratio': 0.22685407993659737}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.34093637166226864
Fold 2 IBS: 0.342625225276533
Fold 3 IBS: 0.2906029898591325
Fold 4 IBS: 0.2618137852249935
Fold 5 IBS: 0.22660182265586026
[I 2024-04-16 09:54:01,256] Trial 38 finished with value: 0.29251603893575756 and parameters: {'l1_ratio': 0.29029311374746675}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.30414399365283534
Fold 2 IBS: 0.30758471287801087
Fold 3 IBS: 0.24278252219135024
Fold 4 IBS: 0.24862516026296563
Fold 5 IBS: 0.23415807038601633
[I 2024-04-16 09:54:02,951] Trial 39 finished with value: 0.26745889187423566 and parameters: {'l1_ratio': 0.11556385448784456}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2740463165486659
Fold 2 IBS: 0.2196177465815663
Fold 3 IBS: 0.1995769652483601
Fold 4 IBS: 0.2229848687766104
Fold 5 IBS: 0.23085409861807146
[I 2024-04-16 09:54:03,954] Trial 40 finished with value: 0.22941599915465485 and parameters: {'l1_ratio': 0.03794387353216893}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2136076035050295
Fold 2 IBS: 0.2211101291654703
Fold 3 IBS: 0.20388637734082707
Fold 4 IBS: 0.2243085674017609
Fold 5 IBS: 0.21751724111572318
[I 2024-04-16 09:54:04,356] Trial 41 finished with value: 0.21608598370576218 and parameters: {'l1_ratio': 0.008501596444785927}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2779719700017684
Fold 2 IBS: 0.2646774312622019
Fold 3 IBS: 0.20504990518534488
Fold 4 IBS: 0.22270454336660425
Fold 5 IBS: 0.23208423983346285
[I 2024-04-16 09:54:05,405] Trial 42 finished with value: 0.24049761792987648 and parameters: {'l1_ratio': 0.044860980654491144}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3276408040054442
Fold 2 IBS: 0.3307993313873969
Fold 3 IBS: 0.2676306242977615
Fold 4 IBS: 0.25537526834667673
Fold 5 IBS: 0.22807016693077187
[I 2024-04-16 09:54:06,946] Trial 43 finished with value: 0.28190323899361025 and parameters: {'l1_ratio': 0.20168830957488737}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.30372882530377054
Fold 2 IBS: 0.30698851295930063
Fold 3 IBS: 0.24229344958093788
Fold 4 IBS: 0.24849937959199117
Fold 5 IBS: 0.23420836534218611
[I 2024-04-16 09:54:08,284] Trial 44 finished with value: 0.26714370655563724 and parameters: {'l1_ratio': 0.11410813840060524}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2733382068197012
Fold 2 IBS: 0.2196746855565374
Fold 3 IBS: 0.19847827075287228
Fold 4 IBS: 0.2230342207392001
Fold 5 IBS: 0.23060718115284634
[I 2024-04-16 09:54:09,102] Trial 45 finished with value: 0.2290265130042315 and parameters: {'l1_ratio': 0.03675330291539553}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.21397085890403758
Fold 2 IBS: 0.2215709031555444
Fold 3 IBS: 0.20452577034275468
Fold 4 IBS: 0.2247315614497797
Fold 5 IBS: 0.21811502856322718
[I 2024-04-16 09:54:09,397] Trial 46 finished with value: 0.21658282448306868 and parameters: {'l1_ratio': 0.00012552275929817412}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3475233343003217
Fold 2 IBS: 0.3566039138187821
Fold 3 IBS: 0.32216836085030454
Fold 4 IBS: 0.27077812952852465
Fold 5 IBS: 0.22946251225322822
[I 2024-04-16 09:54:11,072] Trial 47 finished with value: 0.30530725015023225 and parameters: {'l1_ratio': 0.4099728635635762}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3814867584143324
Fold 2 IBS: 0.46692602171260605
Fold 3 IBS: 0.4094311400929737
Fold 4 IBS: 0.3281991142844378
Fold 5 IBS: 0.27766221170800626
[I 2024-04-16 09:54:13,679] Trial 48 finished with value: 0.37274104924247126 and parameters: {'l1_ratio': 0.908082736959313}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.34781919812974166
Fold 2 IBS: 0.37255551311148727
Fold 3 IBS: 0.3572275784348
Fold 4 IBS: 0.27857709281663284
Fold 5 IBS: 0.23578482060323264
[I 2024-04-16 09:54:15,630] Trial 49 finished with value: 0.3183928406191789 and parameters: {'l1_ratio': 0.52518055791966}. Best is trial 11 with value: 0.2158776110721526.

Fold 1 IBS: 0.31156633973707326
Fold 2 IBS: 0.3163865528172471
Fold 3 IBS: 0.2516857469278973
Fold 4 IBS: 0.2507081100985178
Fold 5 IBS: 0.2325148444425551
[I 2024-04-16 09:54:17,168] Trial 50 finished with value: 0.2725723188046581 and parameters: {'l1_ratio': 0.14081250399003042}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2973879286502772
Fold 2 IBS: 0.29867786958963066
Fold 3 IBS: 0.23332104975980586
Fold 4 IBS: 0.24660822050948716
Fold 5 IBS: 0.2349169293427148
[I 2024-04-16 09:54:18,769] Trial 51 finished with value: 0.26218239957038314 and parameters: {'l1_ratio': 0.09420281977278813}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.26528647509818026
Fold 2 IBS: 0.22019990932883693
Fold 3 IBS: 0.18930339998606083
Fold 4 IBS: 0.2234937826734629
Fold 5 IBS: 0.22756144788673846
[I 2024-04-16 09:54:20,011] Trial 52 finished with value: 0.22516900299465586 and parameters: {'l1_ratio': 0.026036492952643504}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2139265859084932
Fold 2 IBS: 0.2215158950707063
Fold 3 IBS: 0.2044464326491869
Fold 4 IBS: 0.2246807846412922
Fold 5 IBS: 0.21804239776659692
[I 2024-04-16 09:54:20,431] Trial 53 finished with value: 0.2165224192072551 and parameters: {'l1_ratio': 0.0011119713721689985}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2916849474326033
Fold 2 IBS: 0.29029224348860555
Fold 3 IBS: 0.22538200507413644
Fold 4 IBS: 0.24460883906252717
Fold 5 IBS: 0.23493977317446085
[I 2024-04-16 09:54:21,716] Trial 54 finished with value: 0.25738156164646664 and parameters: {'l1_ratio': 0.07740320848586947}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3148161480381365
Fold 2 IBS: 0.3193453152010012
Fold 3 IBS: 0.25486284018861394
Fold 4 IBS: 0.25149376912080024
Fold 5 IBS: 0.2317462557470309
[I 2024-04-16 09:54:23,473] Trial 55 finished with value: 0.27445286565911653 and parameters: {'l1_ratio': 0.15104665384220223}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.365194723223674
Fold 2 IBS: 0.42241273844227106
Fold 3 IBS: 0.4035758947491912
Fold 4 IBS: 0.31124264155319864
Fold 5 IBS: 0.2595254619141091
[I 2024-04-16 09:54:26,526] Trial 56 finished with value: 0.3523902919764888 and parameters: {'l1_ratio': 0.7636926705520951}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.3493736561351946
Fold 2 IBS: 0.3909084769212468
Fold 3 IBS: 0.3793246732875237
Fold 4 IBS: 0.28655763742664864
Fold 5 IBS: 0.2419910218251405
[I 2024-04-16 09:54:29,107] Trial 57 finished with value: 0.3296310931191508 and parameters: {'l1_ratio': 0.60368611969731}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.28147554786409634
Fold 2 IBS: 0.271687410050109
Fold 3 IBS: 0.2100890473129737
Fold 4 IBS: 0.22241920812500487
Fold 5 IBS: 0.23302618934535513
[I 2024-04-16 09:54:30,169] Trial 58 finished with value: 0.2437394805395078 and parameters: {'l1_ratio': 0.05218399485649368}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.30208763063754374
Fold 2 IBS: 0.30518851411341125
Fold 3 IBS: 0.24006435199558077
Fold 4 IBS: 0.24798928962306568
Fold 5 IBS: 0.23447672340363038
[I 2024-04-16 09:54:31,676] Trial 59 finished with value: 0.2659613019546464 and parameters: {'l1_ratio': 0.10896524733345284}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.32305603133802197
Fold 2 IBS: 0.32705463941853263
Fold 3 IBS: 0.2630228603109594
Fold 4 IBS: 0.25382021432519725
Fold 5 IBS: 0.22922817950475935
[I 2024-04-16 09:54:33,387] Trial 60 finished with value: 0.2792363849794941 and parameters: {'l1_ratio': 0.18232778261059474}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2139008305234023
Fold 2 IBS: 0.22148375219702898
Fold 3 IBS: 0.20440046133421744
Fold 4 IBS: 0.22465114927160665
Fold 5 IBS: 0.21800012106833896
[I 2024-04-16 09:54:33,734] Trial 61 finished with value: 0.21648726287891887 and parameters: {'l1_ratio': 0.0016900529599569347}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2703941151493883
Fold 2 IBS: 0.2198753417892803
Fold 3 IBS: 0.19497766227442054
Fold 4 IBS: 0.22320886614989396
Fold 5 IBS: 0.22961649604714102
[I 2024-04-16 09:54:34,893] Trial 62 finished with value: 0.22761449628202485 and parameters: {'l1_ratio': 0.03260322208604846}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.29509345471128107
Fold 2 IBS: 0.2952219813921118
Fold 3 IBS: 0.23025082690326093
Fold 4 IBS: 0.24576259283559768
Fold 5 IBS: 0.23497300154433876
[I 2024-04-16 09:54:36,710] Trial 63 finished with value: 0.26026037147731806 and parameters: {'l1_ratio': 0.0871140483822536}. Best is trial 11 with value: 0.2158776110721526.
Fold 1 IBS: 0.2130768227388257
Fold 2 IBS: 0.220391781921351
Fold 3 IBS: 0.18587848018444383
Fold 4 IBS: 0.22366364266655286
Fold 5 IBS: 0.22626591317983102
[I 2024-04-16 09:54:37,477] Trial 64 finished with value: 0.21385532813820088 and parameters: {'l1_ratio': 0.02223660968544375}. Best is trial 64 with value: 0.21385532813820088.
Fold 1 IBS: 0.2862443246240615
Fold 2 IBS: 0.28070941292220913
Fold 3 IBS: 0.21733005261218222
Fold 4 IBS: 0.24267925164204984
Fold 5 IBS: 0.23400970975927904
[I 2024-04-16 09:54:38,741] Trial 65 finished with value: 0.25219455031195637 and parameters: {'l1_ratio': 0.06337735528326191}. Best is trial 64 with value: 0.21385532813820088.
Fold 1 IBS: 0.3120171873780517
Fold 2 IBS: 0.3168512353326364
Fold 3 IBS: 0.2521914889708549
Fold 4 IBS: 0.2508138251776375
Fold 5 IBS: 0.232418397088153
[I 2024-04-16 09:54:40,521] Trial 66 finished with value: 0.2728584267894667 and parameters: {'l1_ratio': 0.1421813581118076}. Best is trial 64 with value: 0.21385532813820088.
Fold 1 IBS: 0.26939764182804443
Fold 2 IBS: 0.21993295222267817
Fold 3 IBS: 0.19398336301547217
Fold 4 IBS: 0.22325921894318448
Fold 5 IBS: 0.22926691688500409
[I 2024-04-16 09:54:42,055] Trial 67 finished with value: 0.22716801857887664 and parameters: {'l1_ratio': 0.03142460985819022}. Best is trial 64 with value: 0.21385532813820088.
Fold 1 IBS: 0.2955529666318691
Fold 2 IBS: 0.2960378957697911
Fold 3 IBS: 0.230966307904252
Fold 4 IBS: 0.24594655771318333
Fold 5 IBS: 0.23493379147444532
[I 2024-04-16 09:54:43,966] Trial 68 finished with value: 0.26068750389870815 and parameters: {'l1_ratio': 0.08865107948799372}. Best is trial 64 with value: 0.21385532813820088.
Fold 1 IBS: 0.2886186199793487
Fold 2 IBS: 0.2850530738065405
Fold 3 IBS: 0.22099396053057815
Fold 4 IBS: 0.24362874605064744
Fold 5 IBS: 0.2345050417593919
[I 2024-04-16 09:54:46,315] Trial 69 finished with value: 0.25455988842530136 and parameters: {'l1_ratio': 0.06947938577210323}. Best is trial 64 with value: 0.21385532813820088.
Fold 1 IBS: 0.21325765402134061
Fold 2 IBS: 0.22064246052230793
Fold 3 IBS: 0.1810277123343914
Fold 4 IBS: 0.22388718437912777
Fold 5 IBS: 0.2242466552923365
[I 2024-04-16 09:54:47,110] Trial 70 finished with value: 0.21261233330990087 and parameters: {'l1_ratio': 0.01736084474951622}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.34689074434269085
Fold 2 IBS: 0.36304622459558133
Fold 3 IBS: 0.33902976274693547
Fold 4 IBS: 0.27478756460580217
Fold 5 IBS: 0.2322313056896254
[I 2024-04-16 09:54:48,930] Trial 71 finished with value: 0.31119712039612707 and parameters: {'l1_ratio': 0.46549292546878684}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.2646054503337045
Fold 2 IBS: 0.22024354587584122
Fold 3 IBS: 0.1885258185310306
Fold 4 IBS: 0.22353231915468327
Fold 5 IBS: 0.2272858471522192
[I 2024-04-16 09:54:49,710] Trial 72 finished with value: 0.22483859620949573 and parameters: {'l1_ratio': 0.025167036759012357}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.21305781671210652
Fold 2 IBS: 0.22036504885119676
Fold 3 IBS: 0.18637137481302543
Fold 4 IBS: 0.2236399123413965
Fold 5 IBS: 0.226458650081345
[I 2024-04-16 09:54:50,357] Trial 73 finished with value: 0.21397856055981404 and parameters: {'l1_ratio': 0.02276246076885206}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.26524981366121303
Fold 2 IBS: 0.22020215348220287
Fold 3 IBS: 0.1892564700875748
Fold 4 IBS: 0.2234957631961997
Fold 5 IBS: 0.22754460549546882
[I 2024-04-16 09:54:51,325] Trial 74 finished with value: 0.2251497611845318 and parameters: {'l1_ratio': 0.02599170196108446}. Best is trial 70 with value: 0.21261233330990087.

Fold 1 IBS: 0.2820537811446324
Fold 2 IBS: 0.27281077815346333
Fold 3 IBS: 0.2109882464190534
Fold 4 IBS: 0.2413619551337872
Fold 5 IBS: 0.2331403453989755
[I 2024-04-16 09:54:52,893] Trial 75 finished with value: 0.24807102124998237 and parameters: {'l1_ratio': 0.05358076471620459}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.30453887168064997
Fold 2 IBS: 0.30815924821000296
Fold 3 IBS: 0.2433574571045309
Fold 4 IBS: 0.24874086065274206
Fold 5 IBS: 0.2340943831783615
[I 2024-04-16 09:54:54,710] Trial 76 finished with value: 0.2677781641652575 and parameters: {'l1_ratio': 0.11688592011583543}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.2975855759165154
Fold 2 IBS: 0.2989747817947932
Fold 3 IBS: 0.2336129432464095
Fold 4 IBS: 0.24665078013932817
Fold 5 IBS: 0.23491117225580493
[I 2024-04-16 09:54:56,191] Trial 77 finished with value: 0.26234705067057024 and parameters: {'l1_ratio': 0.09484096699800859}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.2832874717952138
Fold 2 IBS: 0.27508300662843904
Fold 3 IBS: 0.21259529724238113
Fold 4 IBS: 0.24161299785142704
Fold 5 IBS: 0.23338299667426465
[I 2024-04-16 09:54:57,765] Trial 78 finished with value: 0.2491923540383451 and parameters: {'l1_ratio': 0.056154594426113154}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.31976783757629657
Fold 2 IBS: 0.3238712748175293
Fold 3 IBS: 0.25950674104470567
Fold 4 IBS: 0.25271595014383774
Fold 5 IBS: 0.23021621552508018
[I 2024-04-16 09:54:59,324] Trial 79 finished with value: 0.2772156038214899 and parameters: {'l1_ratio': 0.16873833591661092}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.3288544069389245
Fold 2 IBS: 0.33229582764042553
Fold 3 IBS: 0.2695713348161254
Fold 4 IBS: 0.25607237474250827
Fold 5 IBS: 0.22774648113297766
[I 2024-04-16 09:55:01,523] Trial 80 finished with value: 0.2829080850541923 and parameters: {'l1_ratio': 0.20900770265017402}. Best is trial 70 with value: 0.21261233330990087.
Fold 1 IBS: 0.21336369418193357
Fold 2 IBS: 0.22078644487730825
Fold 3 IBS: 0.17834268575313886
Fold 4 IBS: 0.2240164223462217
Fold 5 IBS: 0.2228953588570705
[I 2024-04-16 09:55:02,367] Trial 81 finished with value: 0.2118809212031346 and parameters: {'l1_ratio': 0.014604550367388038}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.21314592553912912
Fold 2 IBS: 0.22048835486624138
Fold 3 IBS: 0.18396001919752852
Fold 4 IBS: 0.22374954238995154
Fold 5 IBS: 0.22553542129497384
[I 2024-04-16 09:55:03,142] Trial 82 finished with value: 0.21337585265756487 and parameters: {'l1_ratio': 0.020346495772194363}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.21321251942478822
Fold 2 IBS: 0.22058050678392674
Fold 3 IBS: 0.1821739549451835
Fold 4 IBS: 0.22383176512448247
Fold 5 IBS: 0.2248156136339154
[I 2024-04-16 09:55:03,901] Trial 83 finished with value: 0.21292287198245927 and parameters: {'l1_ratio': 0.018556673131907286}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.26520650277792174
Fold 2 IBS: 0.22020462235959307
Fold 3 IBS: 0.18921382625126182
Fold 4 IBS: 0.22349794221172864
Fold 5 IBS: 0.2275279891475626
[I 2024-04-16 09:55:04,796] Trial 84 finished with value: 0.22513017654961356 and parameters: {'l1_ratio': 0.025942435289177855}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.2897811234712039
Fold 2 IBS: 0.2872452586595424
Fold 3 IBS: 0.2228729274642744
Fold 4 IBS: 0.24403387466133084
Fold 5 IBS: 0.23469326459700204
[I 2024-04-16 09:55:06,243] Trial 85 finished with value: 0.2557252897706707 and parameters: {'l1_ratio': 0.07258967981743379}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.309346411957021
Fold 2 IBS: 0.31364972876378167
Fold 3 IBS: 0.2493510217322471
Fold 4 IBS: 0.25021474125086296
Fold 5 IBS: 0.23309515942047562
[I 2024-04-16 09:55:07,858] Trial 86 finished with value: 0.27113141262487767 and parameters: {'l1_ratio': 0.1329534085767487}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.2788935867195924
Fold 2 IBS: 0.266416697146693
Fold 3 IBS: 0.20611976991186942
Fold 4 IBS: 0.22263595388787602
Fold 5 IBS: 0.23228881847087035
[I 2024-04-16 09:55:08,978] Trial 87 finished with value: 0.24127096522738026 and parameters: {'l1_ratio': 0.04659463145552023}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.2133249848100837
Fold 2 IBS: 0.22073413722161653
Fold 3 IBS: 0.17925404152510507
Fold 4 IBS: 0.2239694004660173
Fold 5 IBS: 0.22341015410333406
[I 2024-04-16 09:55:09,744] Trial 88 finished with value: 0.21213854362523135 and parameters: {'l1_ratio': 0.01560220116353024}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.2987931583602701
Fold 2 IBS: 0.300773916129951
Fold 3 IBS: 0.235535113645308
Fold 4 IBS: 0.2470883061560307
Fold 5 IBS: 0.2348262152453625
[I 2024-04-16 09:55:11,165] Trial 89 finished with value: 0.26340334190738446 and parameters: {'l1_ratio': 0.09875514437241753}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.3460314614356911
Fold 2 IBS: 0.349326464111141
Fold 3 IBS: 0.30810018085698027
Fold 4 IBS: 0.2669077388870686
Fold 5 IBS: 0.22681763604584015
[I 2024-04-16 09:55:12,954] Trial 90 finished with value: 0.29943669626734426 and parameters: {'l1_ratio': 0.3542794117283368}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.21317174873311578
Fold 2 IBS: 0.22052419448641317
Fold 3 IBS: 0.18326391332362427
Fold 4 IBS: 0.22378149064570904
Fold 5 IBS: 0.22526642757943047
[I 2024-04-16 09:55:13,729] Trial 91 finished with value: 0.21320155495365856 and parameters: {'l1_ratio': 0.019648812454214938}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.21312750593926916
Fold 2 IBS: 0.22046270815634422
Fold 3 IBS: 0.18448253027651237
Fold 4 IBS: 0.22372670349395116
Fold 5 IBS: 0.2257472803042863
[I 2024-04-16 09:55:14,343] Trial 92 finished with value: 0.21350934563407264 and parameters: {'l1_ratio': 0.020847002685525435}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.2130330101097826
Fold 2 IBS: 0.2203300445017655
Fold 3 IBS: 0.18700397433377536
Fold 4 IBS: 0.22360887130450988
Fold 5 IBS: 0.22669337628825556
[I 2024-04-16 09:55:15,062] Trial 93 finished with value: 0.2141338553076178 and parameters: {'l1_ratio': 0.02345275146452141}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.2787012927563687
Fold 2 IBS: 0.2661435048867818
Fold 3 IBS: 0.20589485555529222
Fold 4 IBS: 0.22264712569662662
Fold 5 IBS: 0.23231381077976374
[I 2024-04-16 09:55:16,163] Trial 94 finished with value: 0.2411401179349666 and parameters: {'l1_ratio': 0.046311124145537425}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.21310984965776936
Fold 2 IBS: 0.2204380595102493
Fold 3 IBS: 0.18500863319384353
Fold 4 IBS: 0.22370477157566954
Fold 5 IBS: 0.22593247427185015
[I 2024-04-16 09:55:16,787] Trial 95 finished with value: 0.21363875764187634 and parameters: {'l1_ratio': 0.021329016258098868}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.28744318522773576
Fold 2 IBS: 0.28283080843098135
Fold 3 IBS: 0.21917918291934047
Fold 4 IBS: 0.24308294348480994
Fold 5 IBS: 0.23424692410081413
[I 2024-04-16 09:55:18,702] Trial 96 finished with value: 0.2533566088327363 and parameters: {'l1_ratio': 0.06625973716999328}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.2940068312718284
Fold 2 IBS: 0.2936774849273784
Fold 3 IBS: 0.22867372225094254
Fold 4 IBS: 0.24538658190340626
Fold 5 IBS: 0.23504583384883201
[I 2024-04-16 09:55:20,376] Trial 97 finished with value: 0.2593580908404775 and parameters: {'l1_ratio': 0.08370991782409644}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.30387893069660693
Fold 2 IBS: 0.30716516390617127
Fold 3 IBS: 0.24248063402464606
Fold 4 IBS: 0.24854284622644401
Fold 5 IBS: 0.2342260119194439
[I 2024-04-16 09:55:21,884] Trial 98 finished with value: 0.26725871735466245 and parameters: {'l1_ratio': 0.11455454541915662}. Best is trial 81 with value: 0.2118809212031346.
Fold 1 IBS: 0.21327248754975878
Fold 2 IBS: 0.2206627338481146
Fold 3 IBS: 0.18065242817680185
Fold 4 IBS: 0.22390534409049398

Fold 5 IBS: 0.2240565139267466
[I 2024-04-16 09:55:22,498] Trial 99 finished with value: 0.21250990151838317 and parameters: {'l1_ratio': 0.01697082373681321}. Best is trial 81 with value: 0.2118809212031346.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2118809212031346], datetime_start=datetime.datetime(2024, 4, 16, 9, 55, 1, 530603), datetime_complete=datetime.datetime(2024, 4, 16, 9, 55, 2, 367003), params={'l1_ratio': 0.014604550367388038}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=81, value=None)


* Best Score for IBS:
 0.2118809212031346

In [73]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [74]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.708
train_ibs:  0.212

#### Test

In [75]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [76]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.025164283254476998)

test_cindex : 0.586

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.014604550367388038)

test_ibs:  0.221

In [77]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [78]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:55:23,016] A new study created in memory with name: no-name-fb9a45c8-a99f-45d8-9aa6-fcb72591811a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 09:55:57,908] Trial 0 finished with value: 0.7030408096722214 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 09:56:04,527] Trial 1 finished with value: 0.6866757853240973 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 09:56:09,246] Trial 2 finished with value: 0.6865628369372352 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:56:10,898] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:56:12,017] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 09:56:19,672] Trial 5 finished with value: 0.6875588573976407 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 09:56:46,129] Trial 6 finished with value: 0.7003915574155236 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:56:48,484] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-16 09:56:58,398] Trial 8 finished with value: 0.5220657276995305 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 09:57:03,736] Trial 9 finished with value: 0.6843546579233972 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:57:04,420] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7030408096722214.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 09:57:24,038] Trial 11 finished with value: 0.7129880534930061 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 11 with value: 0.7129880534930061.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 09:57:48,569] Trial 12 finished with value: 0.7136148495363072 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4617373338142137, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 12 with value: 0.7136148495363072.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 09:58:06,912] Trial 13 finished with value: 0.7038198416451461 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.430322282186733, 'max_features': None, 'min_weight_fraction_leaf': 0.1716937452680298, 'warm_start': False}. Best is trial 12 with value: 0.7136148495363072.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 09:58:09,460] Trial 14 finished with value: 0.7602465352824544 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.3957120070742282, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.089729602908424, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8526785714285714

Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 09:58:12,954] Trial 15 finished with value: 0.7343450964479536 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.25141113328809755, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08807762154599924, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:14,461] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.14975474925617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08683497083568477, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:17,854] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.2626050058723245, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09309567321799868, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:22,946] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.3309803154711108, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 09:58:27,223] Trial 19 finished with value: 0.7340057280550107 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.20097738776716928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004060792657387402, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:29,709] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 338, 'oob_score': True, 'max_samples': 0.35693963129044115, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2193383546745456, 'warm_start': True}. Best is trial 14 with value: 0.7602465352824544.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 09:58:33,727] Trial 21 finished with value: 0.7779048552353404 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.21528073308536597, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003731938697099116, 'warm_start': True}. Best is trial 21 with value: 0.7779048552353404.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 09:58:38,413] Trial 22 finished with value: 0.752249027173715 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.21351240485158024, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05645873540440379, 'warm_start': True}. Best is trial 21 with value: 0.7779048552353404.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:41,375] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.10559201477694438, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0543102792101534, 'warm_start': True}. Best is trial 21 with value: 0.7779048552353404.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 09:58:44,922] Trial 24 finished with value: 0.8128881217878812 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.5202247887132748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055102552661176425, 'warm_start': True}. Best is trial 24 with value: 0.8128881217878812.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 09:58:49,106] Trial 25 finished with value: 0.8467871740018396 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.5294667085607988, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0009549918209556772, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 09:58:54,687] Trial 26 finished with value: 0.8357998254083719 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030815899349523192, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 09:58:59,046] Trial 27 finished with value: 0.8154314118311712 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.5366581083873809, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04171876755905933, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 09:59:01,063] Trial 28 finished with value: 0.7398099516796621 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.5323444883008067, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12312681780325545, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:59:04,434] Trial 29 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.7488754310335448, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4166359773604548, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 09:59:11,684] Trial 30 finished with value: 0.7457160010311196 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.6638952960819583, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.21039766295115211, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 09:59:17,279] Trial 31 finished with value: 0.8228219119541365 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 447, 'oob_score': True, 'max_samples': 0.5119028984984925, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04799860054302019, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 09:59:21,815] Trial 32 finished with value: 0.8283539838162529 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.5077512231481354, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03147207521246989, 'warm_start': True}. Best is trial 25 with value: 0.8467871740018396.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 09:59:27,454] Trial 33 finished with value: 0.8478361859257715 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.8584661298748817, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0013006402560399475, 'warm_start': True}. Best is trial 33 with value: 0.8478361859257715.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 09:59:32,106] Trial 34 finished with value: 0.8422439465988829 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.8051060893851159, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0025452104786982815, 'warm_start': True}. Best is trial 33 with value: 0.8478361859257715.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 09:59:35,279] Trial 35 finished with value: 0.8479190359671964 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.851099838620899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0006376549948954823, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 09:59:37,491] Trial 36 finished with value: 0.8357733598958312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.8488502380681998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 09:59:39,055] Trial 37 finished with value: 0.7493589594949148 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.838509019374533, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11746503943647707, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 09:59:41,264] Trial 38 finished with value: 0.8269487899780733 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.983590036262626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0747020966452816, 'warm_start': True}. Best is trial 35 with value: 0.8479190359671964.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 09:59:45,147] Trial 39 finished with value: 0.8488165780826342 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 366, 'oob_score': False, 'max_samples': 0.8540574611869531, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.003840718247711571, 'warm_start': True}. Best is trial 39 with value: 0.8488165780826342.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 09:59:46,577] Trial 40 finished with value: 0.7838958563538545 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 255, 'oob_score': False, 'max_samples': 0.6968308474648358, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1433423288180575, 'warm_start': True}. Best is trial 39 with value: 0.8488165780826342.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 09:59:50,044] Trial 41 finished with value: 0.8339513578572 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.8146887408542629, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00030843677515235353, 'warm_start': True}. Best is trial 39 with value: 0.8488165780826342.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 09:59:52,972] Trial 42 finished with value: 0.8527456969756898 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.8942734851141386, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019055206736150496, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 09:59:55,493] Trial 43 finished with value: 0.8329513212195849 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.8879208843012818, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024852775173615727, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 09:59:57,584] Trial 44 finished with value: 0.8284000938095459 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.971999569566476, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0698334924574171, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9578059071729957
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:00:00,653] Trial 45 finished with value: 0.8518750701142708 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9104218782867626, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024937549243351627, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 10:00:07,436] Trial 46 finished with value: 0.6796157756689281 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1067722201468298, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 10:00:09,680] Trial 47 finished with value: 0.832163823891929 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.7669727046770091, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03264002904034867, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 10:00:19,511] Trial 48 finished with value: 0.6819362044806578 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.8722529283282636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06413914181540917, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 10:00:20,539] Trial 49 finished with value: 0.7669851463413936 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.9459839136267338, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27564743124552793, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 10:00:23,461] Trial 50 finished with value: 0.8514951495112056 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.917967126420836, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02319686989352488, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 10:00:26,321] Trial 51 finished with value: 0.8489438569070961 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9289683360127683, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023119305249152552, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:00:28,885] Trial 52 finished with value: 0.8368758936093602 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.9275960987240828, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027445561377387837, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:00:30,365] Trial 53 finished with value: 0.8341782684645521 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.9963955115386218, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07497043940676032, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:00:32,217] Trial 54 finished with value: 0.8398435330387523 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.7837298182053988, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02193560985062079, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 10:00:34,034] Trial 55 finished with value: 0.8219440143194507 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.9517190573290379, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10034820978930141, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:00:37,738] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.7182532763821678, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4854877691508544, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 10:00:38,901] Trial 57 finished with value: 0.7672408301883777 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.9040778587892617, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03837565066969165, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 10:00:41,000] Trial 58 finished with value: 0.7948120286056691 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.8249820267316494, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01929205978496117, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 10:00:51,545] Trial 59 finished with value: 0.8255623295039989 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.8851281818695599, 'max_features': None, 'min_weight_fraction_leaf': 0.13481929816020052, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 10:00:55,092] Trial 60 finished with value: 0.6647990426822765 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.5822185880662518, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08420948524085664, 'warm_start': False}. Best is trial 42 with value: 0.8527456969756898.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:00:58,156] Trial 61 finished with value: 0.8506580861327173 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.8606110350218901, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015110313973031744, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 10:01:00,885] Trial 62 finished with value: 0.8300902705204353 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 333, 'oob_score': False, 'max_samples': 0.9591404172905456, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052973041467924364, 'warm_start': True}. Best is trial 42 with value: 0.8527456969756898.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9578059071729957
Fold 5 C-index: 0.9530516431924883
[I 2024-04-16 10:01:04,315] Trial 63 finished with value: 0.8610676139692007 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.9230175999956005, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.042893630067511276, 'warm_start': True}. Best is trial 63 with value: 0.8610676139692007.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 10:01:07,289] Trial 64 finished with value: 0.8375002766548523 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.9053029008061164, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0456198017341522, 'warm_start': True}. Best is trial 63 with value: 0.8610676139692007.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.9411764705882353
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:01:07,757] Trial 65 finished with value: 0.862830086693586 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 21, 'oob_score': False, 'max_samples': 0.9333236086463597, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02092334357643291, 'warm_start': True}. Best is trial 65 with value: 0.862830086693586.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:01:10,275] Trial 66 finished with value: 0.8385902613042819 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.9302682395779636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06527850624266292, 'warm_start': True}. Best is trial 65 with value: 0.862830086693586.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.9509803921568627
Fold 4 C-index: 0.9704641350210971
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:01:10,916] Trial 67 finished with value: 0.8657942252331653 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.9913887161519704, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018844036271850925, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5064935064935064
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:01:11,217] Trial 68 finished with value: 0.8174509885641156 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 8, 'oob_score': False, 'max_samples': 0.9989888731321823, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017648709064596993, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:01:11,841] Trial 69 finished with value: 0.8423287573429021 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 65, 'oob_score': False, 'max_samples': 0.887987247235582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04202274734020557, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8427230046948356
[I 2024-04-16 10:01:12,180] Trial 70 finished with value: 0.7782611486627746 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 3, 'oob_score': False, 'max_samples': 0.9627766912202452, 'max_features': None, 'min_weight_fraction_leaf': 0.1928493145321546, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:01:12,725] Trial 71 finished with value: 0.8611111724953842 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.9346836401527917, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01764397901477166, 'warm_start': True}. Best is trial 67 with value: 0.8657942252331653.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.9241071428571429
Fold 3 C-index: 0.9411764705882353
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:01:13,337] Trial 72 finished with value: 0.8673945949552773 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.978021668649595, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017507956127588386, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:01:13,952] Trial 73 finished with value: 0.8423948256428619 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 53, 'oob_score': False, 'max_samples': 0.9500892988572575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057332316418011384, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:01:14,684] Trial 74 finished with value: 0.8269197321386292 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9756907704831479, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08223919145457521, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.577922077922078
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 10:01:14,992] Trial 75 finished with value: 0.7295696268020816 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.919061026360145, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35481417747069804, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 10:01:15,953] Trial 76 finished with value: 0.8656574036606651 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 92, 'oob_score': False, 'max_samples': 0.9821338123357319, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0386998813751704, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 10:01:17,085] Trial 77 finished with value: 0.8575007319010522 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9820410736083862, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04031426725454558, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9483568075117371
[I 2024-04-16 10:01:18,146] Trial 78 finished with value: 0.8613008907593895 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 99, 'oob_score': False, 'max_samples': 0.9870196811414806, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04316121707142663, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9389671361502347
[I 2024-04-16 10:01:19,056] Trial 79 finished with value: 0.8581373501847294 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.982100579279894, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03947436058443923, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 10:01:34,129] Trial 80 finished with value: 0.6882224644262152 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.996557008225936, 'max_features': None, 'min_weight_fraction_leaf': 0.09397968262050733, 'warm_start': False}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:01:35,007] Trial 81 finished with value: 0.8491747206994761 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 78, 'oob_score': False, 'max_samples': 0.9688899122872592, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.045053504997941765, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:01:35,988] Trial 82 finished with value: 0.833424193596789 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.9839430534728586, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06330005525600567, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 10:01:36,478] Trial 83 finished with value: 0.8519766625997554 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.9425371719661932, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03632534485337897, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:01:37,367] Trial 84 finished with value: 0.8342928597556141 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 87, 'oob_score': False, 'max_samples': 0.9707179242624712, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07502533547645525, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:01:38,382] Trial 85 finished with value: 0.843360078962459 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 98, 'oob_score': False, 'max_samples': 0.9999603856937841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04591706500803319, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9436619718309859
[I 2024-04-16 10:01:39,779] Trial 86 finished with value: 0.8504787873998202 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.9508012356542417, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01106819826749143, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 10:01:40,251] Trial 87 finished with value: 0.8033762770898729 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 56, 'oob_score': False, 'max_samples': 0.9393248272694704, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0585651420807417, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 10:01:40,715] Trial 88 finished with value: 0.8083928266115115 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.8788991859381762, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10989569253629844, 'warm_start': True}. Best is trial 72 with value: 0.8673945949552773.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:01:41,102] Trial 89 finished with value: 0.8710610216955061 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.9776940371468902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03508377856391107, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:01:41,583] Trial 90 finished with value: 0.8578165857665454 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.9637994442455189, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011418176135514232, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.

Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:01:42,063] Trial 91 finished with value: 0.8434168286757482 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.9684043724798074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03304632175550328, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:01:42,546] Trial 92 finished with value: 0.8439347614602981 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.9379025342651837, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0080128467059435, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 10:01:42,979] Trial 93 finished with value: 0.7775838399834235 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.921219997977047, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23116679435682758, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:01:43,720] Trial 94 finished with value: 0.8416362068255558 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.9808103888471272, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01357145766778422, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:01:44,213] Trial 95 finished with value: 0.8567356149578261 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 23, 'oob_score': False, 'max_samples': 0.9008882936748592, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050931523296795955, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 10:01:44,735] Trial 96 finished with value: 0.8123444935843995 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.9567182017832458, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032219267251555404, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 10:01:45,057] Trial 97 finished with value: 0.8206951097591665 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 12, 'oob_score': False, 'max_samples': 0.8306888663828067, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07102483582015064, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9662447257383966
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:01:45,642] Trial 98 finished with value: 0.858633677785933 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 44, 'oob_score': False, 'max_samples': 0.8752095179234526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015337889322115085, 'warm_start': True}. Best is trial 89 with value: 0.8710610216955061.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7468354430379747

[I 2024-04-16 10:02:52,752] A new study created in memory with name: no-name-155121ec-73f9-4a8a-a742-cfa4454977db

Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 10:02:52,721] Trial 99 finished with value: 0.6714410654454491 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 135, 'oob_score': False, 'max_samples': 0.8773141075149282, 'max_features': None, 'min_weight_fraction_leaf': 0.031973101293928885, 'warm_start': False}. Best is trial 89 with value: 0.8710610216955061.


* Best trial for C-index:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.8710610216955061], datetime_start=datetime.datetime(2024, 4, 16, 10, 1, 40, 720072), datetime_complete=datetime.datetime(2024, 4, 16, 10, 1, 41, 102211), params={'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.9776940371468902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03508377856391107, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=89, value=None)


* Best Score for C-index:
 0.8710610216955061

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1909314497468114
Fold 2 IBS: 0.1838756947663154
Fold 3 IBS: 0.1815068818887493
Fold 4 IBS: 0.19707523042251168
Fold 5 IBS: 0.1912952641441048
[I 2024-04-16 10:03:19,127] Trial 0 finished with value: 0.18893690419369852 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20853319279195734
Fold 2 IBS: 0.18485634190294598
Fold 3 IBS: 0.18461398747386223
Fold 4 IBS: 0.1877281956699156
Fold 5 IBS: 0.21188684258082258
[I 2024-04-16 10:03:20,235] Trial 1 finished with value: 0.19552371208390076 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-16 10:03:20,906] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-16 10:03:23,373] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-16 10:03:25,279] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21548891686111923
Fold 2 IBS: 0.18020165037882038
Fold 3 IBS: 0.18803723401151992
Fold 4 IBS: 0.16918458189908994
Fold 5 IBS: 0.21190068797606287
[I 2024-04-16 10:03:30,074] Trial 5 finished with value: 0.19296261422532246 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.19294818685700066
Fold 2 IBS: 0.18635164797102344
Fold 3 IBS: 0.18167455180137812
Fold 4 IBS: 0.20513583275335814
Fold 5 IBS: 0.2066717152663197
[I 2024-04-16 10:03:43,450] Trial 6 finished with value: 0.194556386929816 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21224269880602273
Fold 2 IBS: 0.2141019684670013
Fold 3 IBS: 0.20009412298826473
Fold 4 IBS: 0.21863959904131022
Fold 5 IBS: 0.21558345426998946
[I 2024-04-16 10:03:46,383] Trial 7 finished with value: 0.21213236871451766 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-16 10:03:51,074] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20967175046992442
Fold 2 IBS: 0.18823479945265645
Fold 3 IBS: 0.18938652891539456
Fold 4 IBS: 0.19233411841816767
Fold 5 IBS: 0.2128466160365194
[I 2024-04-16 10:03:52,455] Trial 9 finished with value: 0.1984947626585325 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-16 10:03:59,192] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20619739601295609
Fold 2 IBS: 0.20334035647220894
Fold 3 IBS: 0.1911208062859065
Fold 4 IBS: 0.20396163181367089
Fold 5 IBS: 0.2115767925024512
[I 2024-04-16 10:04:03,413] Trial 11 finished with value: 0.20323939661743876 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2129281659837464
Fold 2 IBS: 0.18052307192750347
Fold 3 IBS: 0.19384199684749281
Fold 4 IBS: 0.16605951351765671
Fold 5 IBS: 0.20750897373210847
[I 2024-04-16 10:04:10,015] Trial 12 finished with value: 0.19217234440170156 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9944667777599061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10294337889507951}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.22525022980227782
Fold 2 IBS: 0.17353533245380492
Fold 3 IBS: 0.2186524977667984
Fold 4 IBS: 0.16891548073075577
Fold 5 IBS: 0.195621507153405
[I 2024-04-16 10:05:14,668] Trial 13 finished with value: 0.19639500958140838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.9694270540157217, 'max_features': None, 'min_weight_fraction_leaf': 0.1530029930440125}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20207016804160097
Fold 2 IBS: 0.18676975489553133
Fold 3 IBS: 0.1859149971296697
Fold 4 IBS: 0.18527924758332295
Fold 5 IBS: 0.2121788775815752
[I 2024-04-16 10:05:19,375] Trial 14 finished with value: 0.19444260904634003 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.7631177214580046, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21229864789095249}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.23195220862648563
Fold 2 IBS: 0.17801482955351014
Fold 3 IBS: 0.2238672203869343
Fold 4 IBS: 0.17050279887387504
Fold 5 IBS: 0.19954112067881152
[I 2024-04-16 10:05:50,594] Trial 15 finished with value: 0.20077563562392334 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.9970673523205843, 'max_features': None, 'min_weight_fraction_leaf': 0.09604984749674861}. Best is trial 0 with value: 0.18893690419369852.

Fold 1 IBS: 0.20734234035106477
Fold 2 IBS: 0.19501278136445316
Fold 3 IBS: 0.19189186563894495
Fold 4 IBS: 0.20108964805923063
Fold 5 IBS: 0.21696638887997266
[I 2024-04-16 10:05:55,507] Trial 16 finished with value: 0.20246060485873324 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8184724465806228, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31376919111755797}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2044812145296246
Fold 2 IBS: 0.1892546993686875
Fold 3 IBS: 0.1828749961924705
Fold 4 IBS: 0.18912670463318382
Fold 5 IBS: 0.2139231124295064
[I 2024-04-16 10:05:59,159] Trial 17 finished with value: 0.19593214543069454 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.3060837787360696, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005619770510688432}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20139160726914623
Fold 2 IBS: 0.18585932800995397
Fold 3 IBS: 0.1861218453981356
Fold 4 IBS: 0.17860006262773243
Fold 5 IBS: 0.21242561284402064
[I 2024-04-16 10:06:05,779] Trial 18 finished with value: 0.19287969122979776 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.680642613858846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12812974712655775}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.19475177999010934
Fold 2 IBS: 0.1806621111583486
Fold 3 IBS: 0.20798143410401362
Fold 4 IBS: 0.18842371294257598
Fold 5 IBS: 0.193632305175787
[I 2024-04-16 10:06:20,875] Trial 19 finished with value: 0.1930902686741669 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.8923233540949727, 'max_features': None, 'min_weight_fraction_leaf': 0.22336599579981053}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20817199028963768
Fold 2 IBS: 0.1944729659806337
Fold 3 IBS: 0.19194057745960344
Fold 4 IBS: 0.19612566987348856
Fold 5 IBS: 0.21820445689560775
[I 2024-04-16 10:06:24,303] Trial 20 finished with value: 0.2017831320997942 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.7871968885021372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34030385853489}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20308184281641078
Fold 2 IBS: 0.18787487745449374
Fold 3 IBS: 0.18644008925665942
Fold 4 IBS: 0.17992150803863177
Fold 5 IBS: 0.21291813326735048
[I 2024-04-16 10:06:30,289] Trial 21 finished with value: 0.19404729016670924 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.6572584969235378, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14838827402273672}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20654820321735085
Fold 2 IBS: 0.18962828737601528
Fold 3 IBS: 0.185529015857085
Fold 4 IBS: 0.1883836481555542
Fold 5 IBS: 0.2126687891109743
[I 2024-04-16 10:06:35,553] Trial 22 finished with value: 0.19655158874339593 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.46195099482658086, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10498907050446149}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20481511212109618
Fold 2 IBS: 0.1844344269805195
Fold 3 IBS: 0.19010112321844747
Fold 4 IBS: 0.1869176995788077
Fold 5 IBS: 0.2115140936991531
[I 2024-04-16 10:06:41,518] Trial 23 finished with value: 0.19555649111960477 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.6264034454811965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1320111380928695}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2092170982707326
Fold 2 IBS: 0.18289973319337763
Fold 3 IBS: 0.1919325961094944
Fold 4 IBS: 0.16823270962284748
Fold 5 IBS: 0.21044728631185722
[I 2024-04-16 10:06:47,574] Trial 24 finished with value: 0.19254588470166184 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.719949031993126, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.047830597712283124}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2290576901691574
Fold 2 IBS: 0.17488066885927944
Fold 3 IBS: 0.21244798204721357
Fold 4 IBS: 0.1603090486630914
Fold 5 IBS: 0.1970567986118096
[I 2024-04-16 10:07:37,496] Trial 25 finished with value: 0.19475043767011027 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.7351782445421919, 'max_features': None, 'min_weight_fraction_leaf': 0.04415795390433877}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2121221369156162
Fold 2 IBS: 0.17877099581032507
Fold 3 IBS: 0.18754679403766977
Fold 4 IBS: 0.16742425771531183
Fold 5 IBS: 0.20985771345552479
[I 2024-04-16 10:07:41,540] Trial 26 finished with value: 0.19114437958688954 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.8988182112124266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042097403512899145}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20686889245887538
Fold 2 IBS: 0.1884083338020966
Fold 3 IBS: 0.18876792339211537
Fold 4 IBS: 0.18514060806030716
Fold 5 IBS: 0.21563289269901484
[I 2024-04-16 10:07:44,511] Trial 27 finished with value: 0.19696373008248186 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.9352174038267842, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1848211474281298}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2102390531465248
Fold 2 IBS: 0.19154600711242953
Fold 3 IBS: 0.1897192957913833
Fold 4 IBS: 0.19302593080209796
Fold 5 IBS: 0.2126485490317729
[I 2024-04-16 10:07:47,914] Trial 28 finished with value: 0.1994357671768417 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.835160294304069, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24988045818731303}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2076850643866418
Fold 2 IBS: 0.19039634048388074
Fold 3 IBS: 0.18805324142901297
Fold 4 IBS: 0.18708234280984531
Fold 5 IBS: 0.20808498184621124
[I 2024-04-16 10:07:50,211] Trial 29 finished with value: 0.19626039419111846 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.899280299131193, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03665012005683188}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20493578440458557
Fold 2 IBS: 0.18241197625185288
Fold 3 IBS: 0.19204977253497849
Fold 4 IBS: 0.18098544383534507
Fold 5 IBS: 0.21220160549991307
[I 2024-04-16 10:07:51,613] Trial 30 finished with value: 0.19451691650533504 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 98, 'oob_score': False, 'max_samples': 0.9941488361918993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16827524032488794}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21287229922024917
Fold 2 IBS: 0.18118028230968794
Fold 3 IBS: 0.19442622412409546
Fold 4 IBS: 0.16510921719597976
Fold 5 IBS: 0.21193514194112287
[I 2024-04-16 10:07:59,538] Trial 31 finished with value: 0.19310463295822702 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.8464896605652109, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057598037551301065}. Best is trial 0 with value: 0.18893690419369852.

Fold 1 IBS: 0.20878411136352604
Fold 2 IBS: 0.18596824822942906
Fold 3 IBS: 0.19066800479976556
Fold 4 IBS: 0.17194213397317673
Fold 5 IBS: 0.20965199730588724
[I 2024-04-16 10:08:05,267] Trial 32 finished with value: 0.1934028991343569 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.7212112540749575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10884764482583958}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.26672933578367825
Fold 2 IBS: 0.17260981802328967
Fold 3 IBS: 0.218462235370602
Fold 4 IBS: 0.17492701943122574
Fold 5 IBS: 0.1712325610179695
[I 2024-04-16 10:08:09,581] Trial 33 finished with value: 0.20079219392535302 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 19, 'oob_score': True, 'max_samples': 0.6049706297065969, 'max_features': None, 'min_weight_fraction_leaf': 0.01786422641292886}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.2169857185382466
Fold 2 IBS: 0.17663452883651862
Fold 3 IBS: 0.19651528599307333
Fold 4 IBS: 0.1636190754494162
Fold 5 IBS: 0.21255587036122034
[I 2024-04-16 10:08:14,882] Trial 34 finished with value: 0.19326209583569504 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.9447229736600063, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0757592075819458}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21316734022588915
Fold 2 IBS: 0.18026213073590652
Fold 3 IBS: 0.19473913010599572
Fold 4 IBS: 0.16964617097320425
Fold 5 IBS: 0.2099274130167616
[I 2024-04-16 10:08:20,887] Trial 35 finished with value: 0.19354843701155144 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.8021292339953092, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04491877876683002}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21398404476907304
Fold 2 IBS: 0.2213161761944828
Fold 3 IBS: 0.20488054697385918
Fold 4 IBS: 0.2246644996137753
Fold 5 IBS: 0.21853149612739048
[I 2024-04-16 10:08:25,637] Trial 36 finished with value: 0.21667535273571614 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 374, 'oob_score': True, 'max_samples': 0.5753896028655068, 'max_features': None, 'min_weight_fraction_leaf': 0.40732906376297884}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.20659830129520304
Fold 2 IBS: 0.18385914614148338
Fold 3 IBS: 0.19016216373439407
Fold 4 IBS: 0.17123880715306228
Fold 5 IBS: 0.21120851794107792
[I 2024-04-16 10:08:31,062] Trial 37 finished with value: 0.19261338725304414 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.6964969230154789, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08458648773948732}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.21136283326206354
Fold 2 IBS: 0.18356207109099051
Fold 3 IBS: 0.18380554812391878
Fold 4 IBS: 0.17036515364813978
Fold 5 IBS: 0.2102540447203662
[I 2024-04-16 10:08:35,259] Trial 38 finished with value: 0.19186993016909576 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.4953139253289448, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03213232318563604}. Best is trial 0 with value: 0.18893690419369852.
Fold 1 IBS: 0.19530028285277534
Fold 2 IBS: 0.18103597363741977
Fold 3 IBS: 0.19055271974611424
Fold 4 IBS: 0.17599814929084945
Fold 5 IBS: 0.19710966192966495
[I 2024-04-16 10:08:48,328] Trial 39 finished with value: 0.18799935749136473 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 190, 'oob_score': False, 'max_samples': 0.5208817292734901, 'max_features': None, 'min_weight_fraction_leaf': 0.12110152747008576}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2139862133124592
Fold 2 IBS: 0.2215286962880667
Fold 3 IBS: 0.2048896857470274
Fold 4 IBS: 0.22483605023926195
Fold 5 IBS: 0.21848105410604549
[I 2024-04-16 10:08:50,007] Trial 40 finished with value: 0.21674433993857217 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.44676149019096106, 'max_features': None, 'min_weight_fraction_leaf': 0.23842072140001497}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2009860240135767
Fold 2 IBS: 0.18034071969915927
Fold 3 IBS: 0.19435159603275015
Fold 4 IBS: 0.1739979095620913
Fold 5 IBS: 0.19815837872213873
[I 2024-04-16 10:09:07,341] Trial 41 finished with value: 0.1895669256059432 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.5061856948956256, 'max_features': None, 'min_weight_fraction_leaf': 0.11169740239883391}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.228097670669022
Fold 2 IBS: 0.1749977426980276
Fold 3 IBS: 0.1954046550227859
Fold 4 IBS: 0.1627916445243243
Fold 5 IBS: 0.19529585517632986
[I 2024-04-16 10:09:30,626] Trial 42 finished with value: 0.19131751361809793 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5079379573053203, 'max_features': None, 'min_weight_fraction_leaf': 0.026318069624792054}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.21400582170048152
Fold 2 IBS: 0.2212482026565116
Fold 3 IBS: 0.205116493458099
Fold 4 IBS: 0.2247062721100724
Fold 5 IBS: 0.21830660590584794
[I 2024-04-16 10:09:32,588] Trial 43 finished with value: 0.21667667916620248 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.37770293147318823, 'max_features': None, 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19583153004447376
Fold 2 IBS: 0.17911352312673134
Fold 3 IBS: 0.1940263304775934
Fold 4 IBS: 0.1786128101414542
Fold 5 IBS: 0.19758751595069282
[I 2024-04-16 10:09:42,571] Trial 44 finished with value: 0.1890343419481891 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 137, 'oob_score': False, 'max_samples': 0.5215068036754404, 'max_features': None, 'min_weight_fraction_leaf': 0.12548156505108574}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20016280258876293
Fold 2 IBS: 0.18106442587863425
Fold 3 IBS: 0.1817907647526564
Fold 4 IBS: 0.1985749666148987
Fold 5 IBS: 0.20971747943219898
[I 2024-04-16 10:09:46,093] Trial 45 finished with value: 0.19426208785343027 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 122, 'oob_score': False, 'max_samples': 0.3837754218314978, 'max_features': None, 'min_weight_fraction_leaf': 0.17659447211135293}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19608238087631935
Fold 2 IBS: 0.17861720429508926
Fold 3 IBS: 0.19796756489608158
Fold 4 IBS: 0.18158631252973012
Fold 5 IBS: 0.19724266192510972
[I 2024-04-16 10:09:56,217] Trial 46 finished with value: 0.19029922490446602 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.5602811177430677, 'max_features': None, 'min_weight_fraction_leaf': 0.12838422086973741}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19729763464906347
Fold 2 IBS: 0.16564154574645254
Fold 3 IBS: 0.19496992988930276
Fold 4 IBS: 0.188463746593695
Fold 5 IBS: 0.19590518681404473
[I 2024-04-16 10:10:00,607] Trial 47 finished with value: 0.1884556087385117 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.549833569332551, 'max_features': None, 'min_weight_fraction_leaf': 0.12900539608380052}. Best is trial 39 with value: 0.18799935749136473.

Fold 1 IBS: 0.2015902982015954
Fold 2 IBS: 0.1857104387603733
Fold 3 IBS: 0.1790267886123672
Fold 4 IBS: 0.19557127495348786
Fold 5 IBS: 0.20398058535823538
[I 2024-04-16 10:10:02,715] Trial 48 finished with value: 0.19317587717721182 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.5260405815006272, 'max_features': None, 'min_weight_fraction_leaf': 0.21390971396804748}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2145391454105467
Fold 2 IBS: 0.22377474389972024
Fold 3 IBS: 0.20445767011409766
Fold 4 IBS: 0.22686036777266955
Fold 5 IBS: 0.2243610480605514
[I 2024-04-16 10:10:03,070] Trial 49 finished with value: 0.21879859505151708 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.26830717105159463, 'max_features': None, 'min_weight_fraction_leaf': 0.14767412671365485}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20005417967793443
Fold 2 IBS: 0.18085907927728326
Fold 3 IBS: 0.18581136458405717
Fold 4 IBS: 0.19912498551548968
Fold 5 IBS: 0.2109545583240917
[I 2024-04-16 10:10:06,751] Trial 50 finished with value: 0.19536083347577127 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.5952614036305829, 'max_features': None, 'min_weight_fraction_leaf': 0.2798858457285205}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20076463657446927
Fold 2 IBS: 0.17713877093292119
Fold 3 IBS: 0.19996192389062428
Fold 4 IBS: 0.18121132742738624
Fold 5 IBS: 0.19572402265390276
[I 2024-04-16 10:10:17,969] Trial 51 finished with value: 0.19096013629586076 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.5577690942008394, 'max_features': None, 'min_weight_fraction_leaf': 0.12192044372727744}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1965900685059138
Fold 2 IBS: 0.18294591457379972
Fold 3 IBS: 0.1839564616023395
Fold 4 IBS: 0.19468395450865694
Fold 5 IBS: 0.20915752471790008
[I 2024-04-16 10:10:20,485] Trial 52 finished with value: 0.193466784781722 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.47223606642136245, 'max_features': None, 'min_weight_fraction_leaf': 0.19930586110679174}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19053943720172403
Fold 2 IBS: 0.18766910427757014
Fold 3 IBS: 0.1781113837658672
Fold 4 IBS: 0.1885299079588205
Fold 5 IBS: 0.20605183718762635
[I 2024-04-16 10:10:28,598] Trial 53 finished with value: 0.19018033407832163 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 170, 'oob_score': False, 'max_samples': 0.4126678500571366, 'max_features': None, 'min_weight_fraction_leaf': 0.12643674241667632}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20601886283438436
Fold 2 IBS: 0.1817223144274711
Fold 3 IBS: 0.18985236916813075
Fold 4 IBS: 0.17101045403398027
Fold 5 IBS: 0.20269562569299265
[I 2024-04-16 10:10:41,938] Trial 54 finished with value: 0.19025992523139182 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.4257775164744506, 'max_features': None, 'min_weight_fraction_leaf': 0.08411093295534}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19459726930679694
Fold 2 IBS: 0.18297242221796922
Fold 3 IBS: 0.1965180423739642
Fold 4 IBS: 0.17875447156988206
Fold 5 IBS: 0.19484700232226768
[I 2024-04-16 10:10:54,145] Trial 55 finished with value: 0.18953784155817602 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.6395078607296397, 'max_features': None, 'min_weight_fraction_leaf': 0.15889763539063495}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1882079873320902
Fold 2 IBS: 0.17893510442701313
Fold 3 IBS: 0.18768488465792385
Fold 4 IBS: 0.19786494939978266
Fold 5 IBS: 0.19517745378652535
[I 2024-04-16 10:10:58,654] Trial 56 finished with value: 0.18957407592066705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.6383861034558203, 'max_features': None, 'min_weight_fraction_leaf': 0.19322310512139276}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19299807491899834
Fold 2 IBS: 0.18365494631669205
Fold 3 IBS: 0.1877472060862737
Fold 4 IBS: 0.18335325539123815
Fold 5 IBS: 0.19776713087091158
[I 2024-04-16 10:11:13,218] Trial 57 finished with value: 0.18910412271682278 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.6100018518887674, 'max_features': None, 'min_weight_fraction_leaf': 0.15840214758179427}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20739704645746
Fold 2 IBS: 0.18780635854882632
Fold 3 IBS: 0.18701677075522546
Fold 4 IBS: 0.1836166948150953
Fold 5 IBS: 0.21415553404975177
[I 2024-04-16 10:11:15,298] Trial 58 finished with value: 0.19599848092527175 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.6639277088940287, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15215857760776447}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19040076453809218
Fold 2 IBS: 0.18363877768088577
Fold 3 IBS: 0.18685481091428083
Fold 4 IBS: 0.18608582839272733
Fold 5 IBS: 0.19596627174135858
[I 2024-04-16 10:11:28,037] Trial 59 finished with value: 0.18858929065346894 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.6141962522920374, 'max_features': None, 'min_weight_fraction_leaf': 0.16569628029180983}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19728417814617552
Fold 2 IBS: 0.1848259343000363
Fold 3 IBS: 0.18020836278748756
Fold 4 IBS: 0.19937482047392596
Fold 5 IBS: 0.2020282375792895
[I 2024-04-16 10:11:33,561] Trial 60 finished with value: 0.19274430665738299 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.5963407401950178, 'max_features': None, 'min_weight_fraction_leaf': 0.2259745892736023}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19057325218977889
Fold 2 IBS: 0.18756815083836095
Fold 3 IBS: 0.1764902290639015
Fold 4 IBS: 0.19414138806493458
Fold 5 IBS: 0.19954577838438423
[I 2024-04-16 10:11:42,903] Trial 61 finished with value: 0.189663759708272 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.5322501774355544, 'max_features': None, 'min_weight_fraction_leaf': 0.16473932045402911}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2018497163128481
Fold 2 IBS: 0.1772483574047875
Fold 3 IBS: 0.20635720214178183
Fold 4 IBS: 0.17564544580494643
Fold 5 IBS: 0.19458335182903166
[I 2024-04-16 10:12:04,283] Trial 62 finished with value: 0.1911368146986791 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.690008488050583, 'max_features': None, 'min_weight_fraction_leaf': 0.1470861922108762}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19064418333065583
Fold 2 IBS: 0.18865306264594373
Fold 3 IBS: 0.18796770034223975
Fold 4 IBS: 0.19052254543799213
Fold 5 IBS: 0.19585413668160062
[I 2024-04-16 10:12:11,129] Trial 63 finished with value: 0.19072832568768644 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.6215475330033557, 'max_features': None, 'min_weight_fraction_leaf': 0.17501707768999425}. Best is trial 39 with value: 0.18799935749136473.

Fold 1 IBS: 0.1928095274883131
Fold 2 IBS: 0.1829210242425621
Fold 3 IBS: 0.19880360343847653
Fold 4 IBS: 0.1863866229226835
Fold 5 IBS: 0.1951582078859148
[I 2024-04-16 10:12:26,805] Trial 64 finished with value: 0.19121579719558998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 188, 'oob_score': False, 'max_samples': 0.775924036717329, 'max_features': None, 'min_weight_fraction_leaf': 0.20625622507811242}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19101081770652317
Fold 2 IBS: 0.18371867374090417
Fold 3 IBS: 0.1824200640830827
Fold 4 IBS: 0.19925148398280748
Fold 5 IBS: 0.19796558416349588
[I 2024-04-16 10:12:36,770] Trial 65 finished with value: 0.19087332473536267 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.6380685376962676, 'max_features': None, 'min_weight_fraction_leaf': 0.1379890948874851}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1961693420915139
Fold 2 IBS: 0.18615725230494348
Fold 3 IBS: 0.1819983398530402
Fold 4 IBS: 0.19777910918822209
Fold 5 IBS: 0.20858166806712258
[I 2024-04-16 10:12:42,747] Trial 66 finished with value: 0.19413714230096843 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.5795795619141482, 'max_features': None, 'min_weight_fraction_leaf': 0.25843319308808477}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20756228991444287
Fold 2 IBS: 0.18241014181886153
Fold 3 IBS: 0.19010780605990774
Fold 4 IBS: 0.1965188911328108
Fold 5 IBS: 0.2165228499983226
[I 2024-04-16 10:12:44,062] Trial 67 finished with value: 0.19862439578486912 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.5272795412017645, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18877241981072748}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20184305095794017
Fold 2 IBS: 0.1787309749723237
Fold 3 IBS: 0.20120678595418764
Fold 4 IBS: 0.1742316565111679
Fold 5 IBS: 0.201516055621083
[I 2024-04-16 10:13:01,294] Trial 68 finished with value: 0.19150570480334048 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.4839695093257508, 'max_features': None, 'min_weight_fraction_leaf': 0.09899473983366885}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19755614540805655
Fold 2 IBS: 0.18177535693963126
Fold 3 IBS: 0.20403660662298992
Fold 4 IBS: 0.1787311115843317
Fold 5 IBS: 0.1965089126275851
[I 2024-04-16 10:13:23,730] Trial 69 finished with value: 0.1917216266365189 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.7420524473335729, 'max_features': None, 'min_weight_fraction_leaf': 0.17368349136374633}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19473380707808208
Fold 2 IBS: 0.18358627266893093
Fold 3 IBS: 0.1958997961194511
Fold 4 IBS: 0.18138380012465705
Fold 5 IBS: 0.197366737447653
[I 2024-04-16 10:13:45,708] Trial 70 finished with value: 0.19059408268775482 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.6489452374894027, 'max_features': None, 'min_weight_fraction_leaf': 0.15841991648450945}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20365881101077704
Fold 2 IBS: 0.1766635333908709
Fold 3 IBS: 0.1993723191750982
Fold 4 IBS: 0.174992812149042
Fold 5 IBS: 0.19926969814851359
[I 2024-04-16 10:14:06,082] Trial 71 finished with value: 0.19079143477486035 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.5595698482795526, 'max_features': None, 'min_weight_fraction_leaf': 0.11106694826397323}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19961023365297115
Fold 2 IBS: 0.17879413625764815
Fold 3 IBS: 0.1946529980492873
Fold 4 IBS: 0.172974660208681
Fold 5 IBS: 0.19533108806851757
[I 2024-04-16 10:14:17,707] Trial 72 finished with value: 0.18827262324742106 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.5134747414571056, 'max_features': None, 'min_weight_fraction_leaf': 0.1165099939333998}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2406658422448618
Fold 2 IBS: 0.17543636765365264
Fold 3 IBS: 0.20872262379305262
Fold 4 IBS: 0.1582660703515272
Fold 5 IBS: 0.19305772551331746
[I 2024-04-16 10:14:48,206] Trial 73 finished with value: 0.19522972591128235 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.6983010650965532, 'max_features': None, 'min_weight_fraction_leaf': 0.06449301509276852}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19712103206343998
Fold 2 IBS: 0.17660849812337273
Fold 3 IBS: 0.20208369494673262
Fold 4 IBS: 0.17445202335805232
Fold 5 IBS: 0.19445977234046177
[I 2024-04-16 10:14:56,289] Trial 74 finished with value: 0.18894500416641186 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.6110803063418331, 'max_features': None, 'min_weight_fraction_leaf': 0.09204014156660344}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19432597845488106
Fold 2 IBS: 0.1842349926772866
Fold 3 IBS: 0.17663862700419186
Fold 4 IBS: 0.18869159471341404
Fold 5 IBS: 0.1973738153761847
[I 2024-04-16 10:15:01,001] Trial 75 finished with value: 0.18825300164519165 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 110, 'oob_score': False, 'max_samples': 0.4564581127887277, 'max_features': None, 'min_weight_fraction_leaf': 0.09124814911718805}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19230824727470416
Fold 2 IBS: 0.17979735372963127
Fold 3 IBS: 0.17444978919585724
Fold 4 IBS: 0.18891860783041628
Fold 5 IBS: 0.20640760960543755
[I 2024-04-16 10:15:04,906] Trial 76 finished with value: 0.18837632152720932 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.4493825077620159, 'max_features': None, 'min_weight_fraction_leaf': 0.07484643760885143}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.2096553878490079
Fold 2 IBS: 0.19546776810936306
Fold 3 IBS: 0.18466297504921592
Fold 4 IBS: 0.2027457827860734
Fold 5 IBS: 0.2159279265126386
[I 2024-04-16 10:15:05,754] Trial 77 finished with value: 0.2016919680612598 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.44623638751286704, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08351576114037278}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20288745878228068
Fold 2 IBS: 0.18021364044634894
Fold 3 IBS: 0.18544008572673462
Fold 4 IBS: 0.1954523164372797
Fold 5 IBS: 0.20662987774761257
[I 2024-04-16 10:15:07,630] Trial 78 finished with value: 0.1941246758280513 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.34348495165141796, 'max_features': None, 'min_weight_fraction_leaf': 0.07160945459759985}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.20051892419249925
Fold 2 IBS: 0.16576553460873114
Fold 3 IBS: 0.17900575343589448
Fold 4 IBS: 0.21493954058739861

Fold 5 IBS: 0.19832262248550672
[I 2024-04-16 10:15:08,851] Trial 79 finished with value: 0.19171047506200603 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.4577545127391126, 'max_features': None, 'min_weight_fraction_leaf': 0.09781938022887349}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.19426839896125792
Fold 2 IBS: 0.17981710691108702
Fold 3 IBS: 0.17861065931527556
Fold 4 IBS: 0.19911223696785046
Fold 5 IBS: 0.2081704718696194
[I 2024-04-16 10:15:11,480] Trial 80 finished with value: 0.19199577480501806 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 99, 'oob_score': False, 'max_samples': 0.40696501409993335, 'max_features': None, 'min_weight_fraction_leaf': 0.05418386307803515}. Best is trial 39 with value: 0.18799935749136473.
Fold 1 IBS: 0.1928921274877498
Fold 2 IBS: 0.17968754745319848
Fold 3 IBS: 0.1856899889798534
Fold 4 IBS: 0.17837447428728506
Fold 5 IBS: 0.198631389144611
[I 2024-04-16 10:15:18,728] Trial 81 finished with value: 0.18705510547053955 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.5144714895930234, 'max_features': None, 'min_weight_fraction_leaf': 0.1183473468834669}. Best is trial 81 with value: 0.18705510547053955.
Fold 1 IBS: 0.19498785748501332
Fold 2 IBS: 0.18416000234892713
Fold 3 IBS: 0.1749811263553196
Fold 4 IBS: 0.19243209083637866
Fold 5 IBS: 0.2042109093465032
[I 2024-04-16 10:15:21,941] Trial 82 finished with value: 0.19015439727442837 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.4814517826261244, 'max_features': None, 'min_weight_fraction_leaf': 0.09388371332845069}. Best is trial 81 with value: 0.18705510547053955.
Fold 1 IBS: 0.196572591750229
Fold 2 IBS: 0.17992831027310296
Fold 3 IBS: 0.1912315696277225
Fold 4 IBS: 0.18222555877807528
Fold 5 IBS: 0.19873701220967457
[I 2024-04-16 10:15:30,702] Trial 83 finished with value: 0.18973900852776088 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.5487216062543878, 'max_features': None, 'min_weight_fraction_leaf': 0.11933876697393087}. Best is trial 81 with value: 0.18705510547053955.
Fold 1 IBS: 0.18928116916252316
Fold 2 IBS: 0.17681207829778872
Fold 3 IBS: 0.18036591522167056
Fold 4 IBS: 0.19071008027550745
Fold 5 IBS: 0.1968400042365038
[I 2024-04-16 10:15:33,741] Trial 84 finished with value: 0.18680184943879874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.5072704415810627, 'max_features': None, 'min_weight_fraction_leaf': 0.13923559758770704}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.19635077420451166
Fold 2 IBS: 0.16965044412515498
Fold 3 IBS: 0.18051935687673434
Fold 4 IBS: 0.19261116494168012
Fold 5 IBS: 0.2029196071758891
[I 2024-04-16 10:15:35,895] Trial 85 finished with value: 0.18841026946479403 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 51, 'oob_score': False, 'max_samples': 0.4328219024747799, 'max_features': None, 'min_weight_fraction_leaf': 0.13506145126211014}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.2118790715218371
Fold 2 IBS: 0.18649002683647467
Fold 3 IBS: 0.18683588827455805
Fold 4 IBS: 0.20089312342129093
Fold 5 IBS: 0.2113793647760344
[I 2024-04-16 10:15:37,289] Trial 86 finished with value: 0.19949549496603905 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 47, 'oob_score': False, 'max_samples': 0.34070435538857635, 'max_features': None, 'min_weight_fraction_leaf': 0.14319233231910872}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.19246098793488453
Fold 2 IBS: 0.14417757029810832
Fold 3 IBS: 0.19013491268897229
Fold 4 IBS: 0.20432510462782214
Fold 5 IBS: 0.20794628568704515
[I 2024-04-16 10:15:37,702] Trial 87 finished with value: 0.1878089722473665 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 4, 'oob_score': False, 'max_samples': 0.4322924864630003, 'max_features': None, 'min_weight_fraction_leaf': 0.1115168177522978}. Best is trial 84 with value: 0.18680184943879874.
Fold 1 IBS: 0.19090029461234054
Fold 2 IBS: 0.14137499469636072
Fold 3 IBS: 0.1812986156169945
Fold 4 IBS: 0.207189515156582
Fold 5 IBS: 0.1920780785637807
[I 2024-04-16 10:15:38,099] Trial 88 finished with value: 0.18256829972921168 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.4387811941970341, 'max_features': None, 'min_weight_fraction_leaf': 0.11484074874869586}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.1943419444091425
Fold 2 IBS: 0.15233546024160036
Fold 3 IBS: 0.18773534658058533
Fold 4 IBS: 0.2073548214922775
Fold 5 IBS: 0.20084896018721313
[I 2024-04-16 10:15:38,685] Trial 89 finished with value: 0.18852330658216374 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.4337687502966132, 'max_features': None, 'min_weight_fraction_leaf': 0.06543133288022018}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.22601211378830166
Fold 2 IBS: 0.23023726982761436
Fold 3 IBS: 0.21891610644565596
Fold 4 IBS: 0.21627736857389285
Fold 5 IBS: 0.21447814217631173
[I 2024-04-16 10:15:38,966] Trial 90 finished with value: 0.22118420016235532 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 3, 'oob_score': False, 'max_samples': 0.37200101251335593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07632016824081125}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.2031710494812762
Fold 2 IBS: 0.16277512848511938
Fold 3 IBS: 0.18279796790018857
Fold 4 IBS: 0.19635097053183548
Fold 5 IBS: 0.21148201052572227
[I 2024-04-16 10:15:40,046] Trial 91 finished with value: 0.19131542538482837 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.39839348368477034, 'max_features': None, 'min_weight_fraction_leaf': 0.1077523273534647}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.19236727730692432
Fold 2 IBS: 0.17971654848915258
Fold 3 IBS: 0.17691334078269377
Fold 4 IBS: 0.19493487111241187
Fold 5 IBS: 0.19796548040061543
[I 2024-04-16 10:15:42,192] Trial 92 finished with value: 0.18837950361835962 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 64, 'oob_score': False, 'max_samples': 0.4924231584508079, 'max_features': None, 'min_weight_fraction_leaf': 0.13667336203315236}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.19352514327853118
Fold 2 IBS: 0.18116170295711229
Fold 3 IBS: 0.17842605559273972
Fold 4 IBS: 0.19526873278026627
Fold 5 IBS: 0.1975533434467797
[I 2024-04-16 10:15:44,533] Trial 93 finished with value: 0.18918699561108582 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 20, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.49548416980447385, 'max_features': None, 'min_weight_fraction_leaf': 0.11434274596559542}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.19662678661285796
Fold 2 IBS: 0.18002758970706242
Fold 3 IBS: 0.18252512585918226
Fold 4 IBS: 0.2005080205374747
Fold 5 IBS: 0.20057411855259485
[I 2024-04-16 10:15:45,820] Trial 94 finished with value: 0.19205232825383445 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.46704862070515885, 'max_features': None, 'min_weight_fraction_leaf': 0.08985062448642944}. Best is trial 88 with value: 0.18256829972921168.

Fold 1 IBS: 0.19946297870294474
Fold 2 IBS: 0.1787195203639327
Fold 3 IBS: 0.18978142216242233
Fold 4 IBS: 0.19366785888566598
Fold 5 IBS: 0.20885493662651164
[I 2024-04-16 10:15:47,097] Trial 95 finished with value: 0.19409734334829548 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 16, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.43465916069396443, 'max_features': None, 'min_weight_fraction_leaf': 0.14266992337047604}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.21394879098507638
Fold 2 IBS: 0.22071767868681683
Fold 3 IBS: 0.204663570980379
Fold 4 IBS: 0.22456834280613222
Fold 5 IBS: 0.21820813733001868
[I 2024-04-16 10:15:47,996] Trial 96 finished with value: 0.21642130415768462 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.2533979604399289, 'max_features': None, 'min_weight_fraction_leaf': 0.13387701169883912}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.21396124342871353
Fold 2 IBS: 0.22122834841340494
Fold 3 IBS: 0.20452977366874636
Fold 4 IBS: 0.22481229988409993
Fold 5 IBS: 0.2178285026005057
[I 2024-04-16 10:15:48,866] Trial 97 finished with value: 0.2164720335990941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.5052035799981648, 'max_features': None, 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.20092800237475308
Fold 2 IBS: 0.16438642104717785
Fold 3 IBS: 0.18331492320780918
Fold 4 IBS: 0.19098858919975734
Fold 5 IBS: 0.21618831164728108
[I 2024-04-16 10:15:49,568] Trial 98 finished with value: 0.1911612494953557 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 15, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.4548224820450948, 'max_features': None, 'min_weight_fraction_leaf': 0.1035182522031739}. Best is trial 88 with value: 0.18256829972921168.
Fold 1 IBS: 0.21383386308421298
Fold 2 IBS: 0.2200257502519249
Fold 3 IBS: 0.20425687587883834
Fold 4 IBS: 0.22452054619512135
Fold 5 IBS: 0.21752026236388408
[I 2024-04-16 10:15:50,762] Trial 99 finished with value: 0.21603145955479636 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.3646962100401976, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 88 with value: 0.18256829972921168.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.18256829972921168], datetime_start=datetime.datetime(2024, 4, 16, 10, 15, 37, 711306), datetime_complete=datetime.datetime(2024, 4, 16, 10, 15, 38, 99009), params={'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.4387811941970341, 'max_features': None, 'min_weight_fraction_leaf': 0.11484074874869586}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.18256829972921168

In [79]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [80]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.871
train_ibs:  0.183

#### Test

In [81]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [82]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=8, max_features='auto', max_leaf_nodes=17,
                     max_samples=0.9776940371468902, min_samples_split=9,
                     min_weight_fraction_leaf=0.03508377856391107,
                     n_estimators=19, random_state=123, warm_start=True)

test_cindex:  0.628

RandomSurvivalForest(max_depth=17, max_features=None, max_leaf_nodes=9,
                     max_samples=0.4387811941970341, min_samples_leaf=15,
                     min_samples_split=14,
                     min_weight_fraction_leaf=0.11484074874869586,
                     n_estimators=5, random_state=123)

test_ibs:  0.226

In [83]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [84]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [85]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 10:15:51,192] A new study created in memory with name: no-name-aff9ee24-a011-45da-9bf0-d87d9261b0bb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 10:15:52,215] Trial 0 finished with value: 0.7473957621833802 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:15:54,425] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 10:15:59,460] Trial 2 finished with value: 0.6923003209128187 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 10:16:00,274] Trial 3 finished with value: 0.7413714438756912 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:16:02,869] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:16:04,797] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 10:16:05,874] Trial 6 finished with value: 0.732293770804161 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 10:16:08,705] Trial 7 finished with value: 0.6734752861581592 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 10:16:08,966] Trial 8 finished with value: 0.7390137804420783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6103286384976526
[I 2024-04-16 10:16:14,696] Trial 9 finished with value: 0.6536058926723091 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:16:16,653] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 10:16:17,140] Trial 11 finished with value: 0.7248022715139639 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13639294401318086}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 10:16:17,754] Trial 12 finished with value: 0.738919783054472 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.12081901960613745}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.538961038961039
Fold 2 C-index: 0.6852678571428571
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6737089201877934
[I 2024-04-16 10:16:17,958] Trial 13 finished with value: 0.6572495141146298 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 7, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7093678865761541, 'min_weight_fraction_leaf': 0.22382320879779793}. Best is trial 0 with value: 0.7473957621833802.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 10:16:19,608] Trial 14 finished with value: 0.8155995223580931 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.08844623426024902}. Best is trial 14 with value: 0.8155995223580931.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8987341772151899

Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 10:16:21,413] Trial 15 finished with value: 0.8175678569374233 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 10:16:22,514] Trial 16 finished with value: 0.7175541981326802 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.89699542693011, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:16:23,991] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.14923859685882634, 'min_weight_fraction_leaf': 0.19291420116320776}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 10:16:30,331] Trial 18 finished with value: 0.6918780011802125 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 219, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8864397155885823, 'min_weight_fraction_leaf': 0.0011986328064286234}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 10:16:31,519] Trial 19 finished with value: 0.7150367802836787 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3872109746184179, 'min_weight_fraction_leaf': 0.06841061583155703}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:16:32,960] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 371, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6674617762374991, 'min_weight_fraction_leaf': 0.4096697647298415}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 10:16:34,175] Trial 21 finished with value: 0.7705821650610357 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8915767644233141, 'min_weight_fraction_leaf': 0.08195092579029489}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 10:16:36,889] Trial 22 finished with value: 0.8131242613173569 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8806702750475447, 'min_weight_fraction_leaf': 0.0853931201588063}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 10:16:39,100] Trial 23 finished with value: 0.7943607256594918 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9341500043945721, 'min_weight_fraction_leaf': 0.17794205149320266}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 10:16:41,352] Trial 24 finished with value: 0.8122314041744998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.996241305116031, 'min_weight_fraction_leaf': 0.04979027572818695}. Best is trial 15 with value: 0.8175678569374233.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:16:44,543] Trial 25 finished with value: 0.8353010848093593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8365322692071835, 'min_weight_fraction_leaf': 0.030976654928121905}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 10:16:56,415] Trial 26 finished with value: 0.6938412342440664 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8432409992602206, 'min_weight_fraction_leaf': 0.02898048784225954}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8591549295774648
[I 2024-04-16 10:16:58,274] Trial 27 finished with value: 0.8136023118221501 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7138942545087488, 'min_weight_fraction_leaf': 0.027613753152892502}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 10:16:59,332] Trial 28 finished with value: 0.7738447531802879 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 243, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7067616351924364, 'min_weight_fraction_leaf': 0.15462169599864348}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 10:17:00,400] Trial 29 finished with value: 0.7394671851138874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 342, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6331179010773698, 'min_weight_fraction_leaf': 0.10457848931222141}. Best is trial 25 with value: 0.8353010848093593.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 10:17:01,698] Trial 30 finished with value: 0.6952756411321559 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.21007556306018008}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 10:17:03,332] Trial 31 finished with value: 0.8109658972018442 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7335324657551858, 'min_weight_fraction_leaf': 0.025638936264718012}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8967136150234741
[I 2024-04-16 10:17:05,571] Trial 32 finished with value: 0.8258846366631387 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 454, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9206859827921332, 'min_weight_fraction_leaf': 0.07830549040677996}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 10:17:07,346] Trial 33 finished with value: 0.752143038287942 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9312265778306535, 'min_weight_fraction_leaf': 0.09779873758442217}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 10:17:09,469] Trial 34 finished with value: 0.8237631510650582 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 419, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8502925518169527, 'min_weight_fraction_leaf': 0.07190376521891352}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 10:17:12,018] Trial 35 finished with value: 0.6805975493975609 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8479407413376732, 'min_weight_fraction_leaf': 0.2727797492864307}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 10:17:22,098] Trial 36 finished with value: 0.7042474047675116 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 419, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7665754532614238, 'min_weight_fraction_leaf': 0.05998425415499972}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:17:23,491] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6168907596043948, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 10:17:24,898] Trial 38 finished with value: 0.7712053322439204 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.48791124460782864, 'min_weight_fraction_leaf': 0.11636327504384883}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 10:17:30,027] Trial 39 finished with value: 0.6866596996178657 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9454171110339408, 'min_weight_fraction_leaf': 0.16103442323742076}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 10:17:31,535] Trial 40 finished with value: 0.73136266775953 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8248201121352144, 'min_weight_fraction_leaf': 0.062324276491539266}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 10:17:33,142] Trial 41 finished with value: 0.8194462435049387 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9532794241644034, 'min_weight_fraction_leaf': 0.08780433668579535}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 10:17:35,348] Trial 42 finished with value: 0.8161218223168293 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9925634601195337, 'min_weight_fraction_leaf': 0.011813467862108337}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 10:17:37,356] Trial 43 finished with value: 0.8277187329169176 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9526082362533064, 'min_weight_fraction_leaf': 0.04745958703609952}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 10:17:38,660] Trial 44 finished with value: 0.8061876207151526 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9584447959914432, 'min_weight_fraction_leaf': 0.042996535753400594}. Best is trial 25 with value: 0.8353010848093593.

Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 10:17:39,802] Trial 45 finished with value: 0.7453193052128062 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 315, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7943188724004586, 'min_weight_fraction_leaf': 0.13248513273448603}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 10:17:41,251] Trial 46 finished with value: 0.7484591428509685 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 414, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8628193765768433, 'min_weight_fraction_leaf': 0.10117431862592552}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 10:17:44,976] Trial 47 finished with value: 0.6898405522600619 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9678182278668181, 'min_weight_fraction_leaf': 0.04505624352097245}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 10:17:47,469] Trial 48 finished with value: 0.7805504590529708 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 387, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7579522296203552, 'min_weight_fraction_leaf': 0.014387233594138467}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 10:17:48,771] Trial 49 finished with value: 0.7647035593034277 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9238974310190072, 'min_weight_fraction_leaf': 0.23849933216996128}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 10:17:50,133] Trial 50 finished with value: 0.6991075412401303 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9957902969950577, 'min_weight_fraction_leaf': 0.12248746772427224}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 10:17:51,920] Trial 51 finished with value: 0.8293064151056295 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 351, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9215454148342977, 'min_weight_fraction_leaf': 0.08156726752603399}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 10:17:53,752] Trial 52 finished with value: 0.8252797596290984 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 315, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9167408381067254, 'min_weight_fraction_leaf': 0.06667579377107945}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:17:55,677] Trial 53 finished with value: 0.8278627934828447 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9035701569637378, 'min_weight_fraction_leaf': 0.04859656248662959}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:17:57,876] Trial 54 finished with value: 0.8352140020905686 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9125432991997491, 'min_weight_fraction_leaf': 0.03206288242066289}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:17:59,629] Trial 55 finished with value: 0.8289524986399364 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 240, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.797364748691682, 'min_weight_fraction_leaf': 0.03710106747804083}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 10:18:00,481] Trial 56 finished with value: 0.7823862339632688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 10:18:01,654] Trial 57 finished with value: 0.8321404095277231 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8192002992527245, 'min_weight_fraction_leaf': 0.03955892145134048}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 10:18:06,057] Trial 58 finished with value: 0.7041901514005171 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 167, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6659973923607253, 'min_weight_fraction_leaf': 0.027230063640658893}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 10:18:07,449] Trial 59 finished with value: 0.8286971643711862 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 194, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7850187786845839, 'min_weight_fraction_leaf': 8.414791031117336e-05}. Best is trial 25 with value: 0.8353010848093593.

Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:18:08,156] Trial 60 finished with value: 0.8339962837677252 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7803239385177003, 'min_weight_fraction_leaf': 0.005453058174879628}. Best is trial 25 with value: 0.8353010848093593.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:18:09,029] Trial 61 finished with value: 0.8421154836916532 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 131, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.806720965637479, 'min_weight_fraction_leaf': 0.0015497906295155323}. Best is trial 61 with value: 0.8421154836916532.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:18:09,865] Trial 62 finished with value: 0.8412359074004486 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 121, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.807914741169143, 'min_weight_fraction_leaf': 0.017275515706874415}. Best is trial 61 with value: 0.8421154836916532.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:18:10,538] Trial 63 finished with value: 0.8418841701577955 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7471161630300795, 'min_weight_fraction_leaf': 0.02164269686952123}. Best is trial 61 with value: 0.8421154836916532.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 10:18:11,390] Trial 64 finished with value: 0.8425402944529242 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7444072631782004, 'min_weight_fraction_leaf': 0.019461022888333096}. Best is trial 64 with value: 0.8425402944529242.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:18:12,447] Trial 65 finished with value: 0.8421939282528357 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 111, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7409613764589495, 'min_weight_fraction_leaf': 0.017696281413854598}. Best is trial 64 with value: 0.8425402944529242.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 10:18:13,566] Trial 66 finished with value: 0.8440112453188864 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7424477137148021, 'min_weight_fraction_leaf': 0.021932301189429612}. Best is trial 66 with value: 0.8440112453188864.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:18:14,453] Trial 67 finished with value: 0.8479116267246294 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7307848129741745, 'min_weight_fraction_leaf': 0.016035187560656326}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:18:15,249] Trial 68 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 115, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6903237979510266, 'min_weight_fraction_leaf': 0.35364036783604025}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 10:18:15,935] Trial 69 finished with value: 0.7934960061594778 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 77, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5906341058203064, 'min_weight_fraction_leaf': 0.05853231432954687}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:18:16,389] Trial 70 finished with value: 0.8370199541752875 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 42, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.746202010308237, 'min_weight_fraction_leaf': 0.01718513441911046}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 10:18:16,778] Trial 71 finished with value: 0.8315863683193498 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 28, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7286910789490153, 'min_weight_fraction_leaf': 0.021392176623630743}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9107981220657277
[I 2024-04-16 10:18:17,814] Trial 72 finished with value: 0.845010691191986 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 130, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6877705225452767, 'min_weight_fraction_leaf': 0.016534328495177237}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:18:18,752] Trial 73 finished with value: 0.8464476262798024 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 124, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6950988475816776, 'min_weight_fraction_leaf': 0.0008685229148859483}. Best is trial 67 with value: 0.8479116267246294.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:18:19,713] Trial 74 finished with value: 0.8555893751688586 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 132, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6774440080108878, 'min_weight_fraction_leaf': 0.004532767529812777}. Best is trial 74 with value: 0.8555893751688586.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 10:18:20,735] Trial 75 finished with value: 0.834080320445655 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 141, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5277241651577844, 'min_weight_fraction_leaf': 0.00034951661289149213}. Best is trial 74 with value: 0.8555893751688586.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 10:18:23,517] Trial 76 finished with value: 0.6621863920044102 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 141, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6900957324692815, 'min_weight_fraction_leaf': 0.05551936393621635}. Best is trial 74 with value: 0.8555893751688586.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:18:24,497] Trial 77 finished with value: 0.858408551105818 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 85, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6427403214768266, 'min_weight_fraction_leaf': 0.011137087979573197}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:18:25,279] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 90, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.645711194297668, 'min_weight_fraction_leaf': 0.41218066030994116}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 10:18:25,979] Trial 79 finished with value: 0.8173293044101382 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 63, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6063283426127006, 'min_weight_fraction_leaf': 0.03219406437302813}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6572769953051644
[I 2024-04-16 10:18:26,928] Trial 80 finished with value: 0.6802368592860896 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 101, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6797865329606951, 'min_weight_fraction_leaf': 0.30841556955373983}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9061032863849765
[I 2024-04-16 10:18:27,920] Trial 81 finished with value: 0.8423825904046769 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7131028174450602, 'min_weight_fraction_leaf': 0.009906725312419967}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:18:29,233] Trial 82 finished with value: 0.8462213089907028 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 155, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7220615522106731, 'min_weight_fraction_leaf': 0.01596811650239777}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8685446009389671
[I 2024-04-16 10:18:30,203] Trial 83 finished with value: 0.8266385730616012 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 159, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6391133175097252, 'min_weight_fraction_leaf': 0.039630933710605595}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:18:31,330] Trial 84 finished with value: 0.845886314298163 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7149268731531023, 'min_weight_fraction_leaf': 0.010204531997757376}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 10:18:32,423] Trial 85 finished with value: 0.7966870936124656 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 143, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5571788120979523, 'min_weight_fraction_leaf': 0.052349117710787846}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 10:18:33,001] Trial 86 finished with value: 0.7768163367147537 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 59, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5862744605305834, 'min_weight_fraction_leaf': 0.07101851576926227}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 10:18:33,699] Trial 87 finished with value: 0.6790163744147233 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 89, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6750432673914222, 'min_weight_fraction_leaf': 0.015105478852784723}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 10:18:36,454] Trial 88 finished with value: 0.6689726915499177 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 170, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7071205580703166, 'min_weight_fraction_leaf': 0.034641210394640964}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 10:18:37,855] Trial 89 finished with value: 0.8275515269804254 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 210, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6231287731677, 'min_weight_fraction_leaf': 0.0272446470925741}. Best is trial 77 with value: 0.858408551105818.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 10:18:38,938] Trial 90 finished with value: 0.8052128181213003 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 156, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6593243539845698, 'min_weight_fraction_leaf': 0.056494043546166495}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-16 10:18:40,163] Trial 91 finished with value: 0.8440803173811705 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 128, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7225655744279161, 'min_weight_fraction_leaf': 0.013637383517672729}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9535864978902954
Fold 5 C-index: 0.9342723004694836
[I 2024-04-16 10:18:41,210] Trial 92 finished with value: 0.8571108480345735 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 127, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7279610537008266, 'min_weight_fraction_leaf': 0.008737769636097927}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9578059071729957
Fold 5 C-index: 0.9295774647887324
[I 2024-04-16 10:18:42,112] Trial 93 finished with value: 0.8551425134552435 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7278711689328157, 'min_weight_fraction_leaf': 0.00826825686537057}. Best is trial 77 with value: 0.858408551105818.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9248826291079812
[I 2024-04-16 10:18:43,483] Trial 94 finished with value: 0.866733060426232 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7692755291164257, 'min_weight_fraction_leaf': 0.006944921267975795}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 10:18:44,714] Trial 95 finished with value: 0.8445142185952648 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7669577786786118, 'min_weight_fraction_leaf': 0.044649174116016065}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.892018779342723
[I 2024-04-16 10:18:45,684] Trial 96 finished with value: 0.8396585023010648 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 148, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.684661981274086, 'min_weight_fraction_leaf': 0.008786170259833718}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 10:18:46,795] Trial 97 finished with value: 0.8279858779359974 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.69951914293224, 'min_weight_fraction_leaf': 0.03894786555507988}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.92018779342723
[I 2024-04-16 10:18:47,713] Trial 98 finished with value: 0.8490282471357398 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6503126145421575, 'min_weight_fraction_leaf': 0.0007737014426484837}. Best is trial 94 with value: 0.866733060426232.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7974683544303798

[I 2024-04-16 10:18:48,842] A new study created in memory with name: no-name-fadb0dc4-dd4b-49f8-a116-d8a619be9001

Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 10:18:48,821] Trial 99 finished with value: 0.7792227629070073 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 170, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5365720508426045, 'min_weight_fraction_leaf': 0.004358450234500475}. Best is trial 94 with value: 0.866733060426232.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.866733060426232], datetime_start=datetime.datetime(2024, 4, 16, 10, 18, 42, 124943), datetime_complete=datetime.datetime(2024, 4, 16, 10, 18, 43, 483048), params={'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7692755291164257, 'min_weight_fraction_leaf': 0.006944921267975795}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.866733060426232

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.20324441808559623
Fold 2 IBS: 0.1951588328187537
Fold 3 IBS: 0.19070420150494224
Fold 4 IBS: 0.19874690830095737
Fold 5 IBS: 0.21043314938440771
[I 2024-04-16 10:18:52,938] Trial 0 finished with value: 0.19965750201893145 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.19965750201893145.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-16 10:18:58,562] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.19965750201893145.
Fold 1 IBS: 0.20420205971539113
Fold 2 IBS: 0.1912585061325825
Fold 3 IBS: 0.18653624989741915
Fold 4 IBS: 0.18761526375944965
Fold 5 IBS: 0.2069146602615986
[I 2024-04-16 10:19:03,442] Trial 2 finished with value: 0.1953053479532882 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.20893596688851945
Fold 2 IBS: 0.19051701187606018
Fold 3 IBS: 0.18955624451377623
Fold 4 IBS: 0.1909289943501129
Fold 5 IBS: 0.20700072377138612
[I 2024-04-16 10:19:05,357] Trial 3 finished with value: 0.197387788279971 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-16 10:19:09,393] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-16 10:19:11,468] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.20565604200336957
Fold 2 IBS: 0.1984154995749487
Fold 3 IBS: 0.19127221043732198
Fold 4 IBS: 0.20318673337184806
Fold 5 IBS: 0.2114491354913557
[I 2024-04-16 10:19:15,610] Trial 6 finished with value: 0.2019959241757688 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21033134855617358
Fold 2 IBS: 0.21628633133422068
Fold 3 IBS: 0.2012050801829807
Fold 4 IBS: 0.2178792316620616
Fold 5 IBS: 0.21649960246279268
[I 2024-04-16 10:19:18,142] Trial 7 finished with value: 0.21244031883964584 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.2120398563907811
Fold 2 IBS: 0.19006412590155936
Fold 3 IBS: 0.18594102315027772
Fold 4 IBS: 0.19174839772207844
Fold 5 IBS: 0.21188341229500296
[I 2024-04-16 10:19:18,942] Trial 8 finished with value: 0.19833536309193991 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21319807558872467
Fold 2 IBS: 0.21979786241557914
Fold 3 IBS: 0.20373457069650647
Fold 4 IBS: 0.2237435946433909
Fold 5 IBS: 0.21834175061840702
[I 2024-04-16 10:19:24,731] Trial 9 finished with value: 0.21576317079252166 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.2139727346768592
Fold 2 IBS: 0.2213120202940904
Fold 3 IBS: 0.20503568053719107
Fold 4 IBS: 0.2245613118501098
Fold 5 IBS: 0.21766314539351875
[I 2024-04-16 10:19:31,016] Trial 10 finished with value: 0.21650897855035384 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21030497940211074
Fold 2 IBS: 0.19290206618360403
Fold 3 IBS: 0.19556818516782043
Fold 4 IBS: 0.19882387041781702
Fold 5 IBS: 0.2119717933704952
[I 2024-04-16 10:19:32,245] Trial 11 finished with value: 0.20191417890836946 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.20706972434681659
Fold 2 IBS: 0.19699623140204683
Fold 3 IBS: 0.18982889221830407
Fold 4 IBS: 0.19862716585283102
Fold 5 IBS: 0.20846386022396718
[I 2024-04-16 10:19:33,961] Trial 12 finished with value: 0.20019717480879312 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.21602403915542812
Fold 2 IBS: 0.22135942967444958
Fold 3 IBS: 0.207522129090302
Fold 4 IBS: 0.22681102026289354
Fold 5 IBS: 0.2196363896884173
[I 2024-04-16 10:19:34,222] Trial 13 finished with value: 0.21827060157429812 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.1768405475625161}. Best is trial 2 with value: 0.1953053479532882.
Fold 1 IBS: 0.2066392480842299
Fold 2 IBS: 0.18785902454116382
Fold 3 IBS: 0.1885942421588505
Fold 4 IBS: 0.1788911402119244
Fold 5 IBS: 0.20431026187277884
[I 2024-04-16 10:19:35,755] Trial 14 finished with value: 0.1932587833737895 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8615610863035676, 'min_weight_fraction_leaf': 0.00662188941038383}. Best is trial 14 with value: 0.1932587833737895.

Fold 1 IBS: 0.20959115925098934
Fold 2 IBS: 0.177742818125481
Fold 3 IBS: 0.19464554067335235
Fold 4 IBS: 0.1636648885496132
Fold 5 IBS: 0.19935152208595006
[I 2024-04-16 10:19:40,378] Trial 15 finished with value: 0.1889991857370772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.0023088139988564262}. Best is trial 15 with value: 0.1889991857370772.
Fold 1 IBS: 0.21154186523364313
Fold 2 IBS: 0.1735802006784233
Fold 3 IBS: 0.1912219340060055
Fold 4 IBS: 0.1616965665766284
Fold 5 IBS: 0.19959277710979445
[I 2024-04-16 10:19:45,012] Trial 16 finished with value: 0.18752666872089896 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8957765840335672, 'min_weight_fraction_leaf': 0.010191311991891749}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.2091620042024494
Fold 2 IBS: 0.19801258235187924
Fold 3 IBS: 0.19122454802730907
Fold 4 IBS: 0.20232133278486802
Fold 5 IBS: 0.2151637052938854
[I 2024-04-16 10:19:47,932] Trial 17 finished with value: 0.20317683453207822 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9042785918294833, 'min_weight_fraction_leaf': 0.42038595995868033}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.21392851730727483
Fold 2 IBS: 0.2203112302740686
Fold 3 IBS: 0.20531706619567533
Fold 4 IBS: 0.22509036885374237
Fold 5 IBS: 0.21706040157641074
[I 2024-04-16 10:19:52,183] Trial 18 finished with value: 0.21634151684143438 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 312, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.22508105757456376}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20737708257366003
Fold 2 IBS: 0.19609767402580006
Fold 3 IBS: 0.18819938430471037
Fold 4 IBS: 0.20114004954392087
Fold 5 IBS: 0.2160102452576919
[I 2024-04-16 10:19:55,275] Trial 19 finished with value: 0.20176488714115665 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895543806821031, 'min_weight_fraction_leaf': 0.3097789443945588}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20350526528548746
Fold 2 IBS: 0.1982406915490011
Fold 3 IBS: 0.18876305026521908
Fold 4 IBS: 0.20043423378955613
Fold 5 IBS: 0.21482167675282082
[I 2024-04-16 10:19:59,805] Trial 20 finished with value: 0.20115298352841693 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8867517870122669, 'min_weight_fraction_leaf': 0.3678346055590361}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20919624684418117
Fold 2 IBS: 0.18900125773576712
Fold 3 IBS: 0.18773554697157677
Fold 4 IBS: 0.1917518862972034
Fold 5 IBS: 0.21122350951612398
[I 2024-04-16 10:20:01,718] Trial 21 finished with value: 0.1977816894729705 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8638184920383039, 'min_weight_fraction_leaf': 0.006217904257385862}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20780417605287888
Fold 2 IBS: 0.1882276018836113
Fold 3 IBS: 0.18544272265859707
Fold 4 IBS: 0.1829868094290558
Fold 5 IBS: 0.20717739840838342
[I 2024-04-16 10:20:05,000] Trial 22 finished with value: 0.1943277416865053 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9916304513453179, 'min_weight_fraction_leaf': 0.04142928400152037}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20109565009641497
Fold 2 IBS: 0.18094793231494766
Fold 3 IBS: 0.1937268937497428
Fold 4 IBS: 0.169009702983042
Fold 5 IBS: 0.19936047028886142
[I 2024-04-16 10:20:08,448] Trial 23 finished with value: 0.18882812988660175 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8538011958709324, 'min_weight_fraction_leaf': 0.013387254497520491}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.19457759163477775
Fold 2 IBS: 0.18792017350002727
Fold 3 IBS: 0.18490451457597312
Fold 4 IBS: 0.18484796411143414
Fold 5 IBS: 0.20342560527330505
[I 2024-04-16 10:20:11,921] Trial 24 finished with value: 0.19113516981910345 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7063615578289446, 'min_weight_fraction_leaf': 0.09753635397668133}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20505987377954846
Fold 2 IBS: 0.1783437638943379
Fold 3 IBS: 0.19502663651026692
Fold 4 IBS: 0.16888712557905158
Fold 5 IBS: 0.19936260036326842
[I 2024-04-16 10:20:15,767] Trial 25 finished with value: 0.18933600002529466 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8862362117578689, 'min_weight_fraction_leaf': 0.043860428079719994}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.20176453553034204
Fold 2 IBS: 0.18135156347758707
Fold 3 IBS: 0.19087086985496254
Fold 4 IBS: 0.1735135267565779
Fold 5 IBS: 0.19937116775114117
[I 2024-04-16 10:20:24,036] Trial 26 finished with value: 0.18937433267412213 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 360, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9394823781600602, 'min_weight_fraction_leaf': 0.1647525192290286}. Best is trial 16 with value: 0.18752666872089896.
Fold 1 IBS: 0.19492411516971328
Fold 2 IBS: 0.18097482376757582
Fold 3 IBS: 0.19106644620180185
Fold 4 IBS: 0.17049571801587696
Fold 5 IBS: 0.19801397361945633
[I 2024-04-16 10:20:28,734] Trial 27 finished with value: 0.18709501535488485 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8191666066640952, 'min_weight_fraction_leaf': 0.09646653508544777}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20208702878992982
Fold 2 IBS: 0.19166074112978226
Fold 3 IBS: 0.1844014838460033
Fold 4 IBS: 0.18676803790959648
Fold 5 IBS: 0.20623856857749273
[I 2024-04-16 10:20:33,602] Trial 28 finished with value: 0.1942311720505609 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 314, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8334931071137727, 'min_weight_fraction_leaf': 0.088560330847152}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.197211862541379
Fold 2 IBS: 0.17905640106995538
Fold 3 IBS: 0.18853806208802265
Fold 4 IBS: 0.17482419472113186
Fold 5 IBS: 0.20296059811142658
[I 2024-04-16 10:20:39,597] Trial 29 finished with value: 0.18851822370638308 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7276031224679027, 'min_weight_fraction_leaf': 0.10829907781144071}. Best is trial 27 with value: 0.18709501535488485.

Fold 1 IBS: 0.2081043148093001
Fold 2 IBS: 0.20420509768667056
Fold 3 IBS: 0.1962340623978483
Fold 4 IBS: 0.2096506990203624
Fold 5 IBS: 0.21353357787911675
[I 2024-04-16 10:20:43,284] Trial 30 finished with value: 0.20634555035865962 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7314863609037403, 'min_weight_fraction_leaf': 0.10563608457720963}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.19730717896052297
Fold 2 IBS: 0.18529441321477938
Fold 3 IBS: 0.18533366129064377
Fold 4 IBS: 0.18248960193133745
Fold 5 IBS: 0.20221423911324402
[I 2024-04-16 10:20:49,252] Trial 31 finished with value: 0.19052781890210552 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6216891695240637, 'min_weight_fraction_leaf': 0.06291410320510718}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.19898317991982656
Fold 2 IBS: 0.18002409337384578
Fold 3 IBS: 0.18862277222324778
Fold 4 IBS: 0.17331221595669444
Fold 5 IBS: 0.1991038102552761
[I 2024-04-16 10:20:54,207] Trial 32 finished with value: 0.18800921434577814 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7623736719965445, 'min_weight_fraction_leaf': 0.0321952074579447}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.1991986657356779
Fold 2 IBS: 0.1815149249243747
Fold 3 IBS: 0.1872127920748621
Fold 4 IBS: 0.1764430725221634
Fold 5 IBS: 0.20202426211852528
[I 2024-04-16 10:21:00,875] Trial 33 finished with value: 0.1892787434751207 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7600744603373085, 'min_weight_fraction_leaf': 0.15599210206825725}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20103382861142927
Fold 2 IBS: 0.19282964416498558
Fold 3 IBS: 0.1870859874481926
Fold 4 IBS: 0.196226382758684
Fold 5 IBS: 0.2123300166052512
[I 2024-04-16 10:21:07,717] Trial 34 finished with value: 0.19790117191770853 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.47644913459202465, 'min_weight_fraction_leaf': 0.06966651301171624}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20779030731749934
Fold 2 IBS: 0.20307190870749472
Fold 3 IBS: 0.1962710157037756
Fold 4 IBS: 0.21081039601280466
Fold 5 IBS: 0.2132998921564787
[I 2024-04-16 10:21:12,959] Trial 35 finished with value: 0.2062487039796106 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 293, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6176859663338274, 'min_weight_fraction_leaf': 0.10956820043618563}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.21290730554088733
Fold 2 IBS: 0.21811017960573384
Fold 3 IBS: 0.20259067726637844
Fold 4 IBS: 0.22217655091339963
Fold 5 IBS: 0.2176672935324032
[I 2024-04-16 10:21:17,797] Trial 36 finished with value: 0.2146904013717605 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8179384621484631, 'min_weight_fraction_leaf': 0.0350871457115}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20937538943889084
Fold 2 IBS: 0.1976588452266711
Fold 3 IBS: 0.19445670151606664
Fold 4 IBS: 0.20487984959052633
Fold 5 IBS: 0.21266809601522105
[I 2024-04-16 10:21:20,654] Trial 37 finished with value: 0.20380777635747518 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.727246384588029, 'min_weight_fraction_leaf': 0.12859608190892008}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20530011772785173
Fold 2 IBS: 0.19803832641530136
Fold 3 IBS: 0.18877575404214447
Fold 4 IBS: 0.2041315572944101
Fold 5 IBS: 0.21433733406277344
[I 2024-04-16 10:21:24,343] Trial 38 finished with value: 0.2021166179084962 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.18743659703875493}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.2126855497240101
Fold 2 IBS: 0.21939483841221513
Fold 3 IBS: 0.204514596423358
Fold 4 IBS: 0.2241774075643293
Fold 5 IBS: 0.21770096331347819
[I 2024-04-16 10:21:27,164] Trial 39 finished with value: 0.21569467108747814 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 227, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5177303386477011, 'min_weight_fraction_leaf': 0.2437702761952286}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20205635314852127
Fold 2 IBS: 0.1779550910748468
Fold 3 IBS: 0.19199273466468036
Fold 4 IBS: 0.16938184753905136
Fold 5 IBS: 0.2016814036986973
[I 2024-04-16 10:21:34,070] Trial 40 finished with value: 0.18861348602515943 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 425, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7599898043769167, 'min_weight_fraction_leaf': 0.04836923196673275}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20353704880860568
Fold 2 IBS: 0.17829121646794985
Fold 3 IBS: 0.1934981237320483
Fold 4 IBS: 0.16969026055921907
Fold 5 IBS: 0.20110029965603304
[I 2024-04-16 10:21:40,773] Trial 41 finished with value: 0.18922338984477122 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7760359149297024, 'min_weight_fraction_leaf': 0.05040101778889726}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20482842806207383
Fold 2 IBS: 0.1759182336741199
Fold 3 IBS: 0.1924090734725373
Fold 4 IBS: 0.16621668500349204
Fold 5 IBS: 0.20008837310029803
[I 2024-04-16 10:21:47,470] Trial 42 finished with value: 0.18789215866250425 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.07308613146326948}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.19842848181510805
Fold 2 IBS: 0.18062994551768752
Fold 3 IBS: 0.19088081768989523
Fold 4 IBS: 0.17229498637104404
Fold 5 IBS: 0.19881715613809028
[I 2024-04-16 10:21:52,824] Trial 43 finished with value: 0.18821027750636501 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8119352159878038, 'min_weight_fraction_leaf': 0.08910421030553545}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.2124764225213534
Fold 2 IBS: 0.21791314037114443
Fold 3 IBS: 0.2020724966160973
Fold 4 IBS: 0.22110609114819313
Fold 5 IBS: 0.2175856606149026
[I 2024-04-16 10:21:56,192] Trial 44 finished with value: 0.21423076225433818 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8109881601003952, 'min_weight_fraction_leaf': 0.02764976413213125}. Best is trial 27 with value: 0.18709501535488485.

Fold 1 IBS: 0.2057886310768082
Fold 2 IBS: 0.19693079192071614
Fold 3 IBS: 0.19129734861332404
Fold 4 IBS: 0.19629616500268943
Fold 5 IBS: 0.21038967978117093
[I 2024-04-16 10:22:00,712] Trial 45 finished with value: 0.20014052327894177 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 486, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9606319416987669, 'min_weight_fraction_leaf': 0.06471432252401287}. Best is trial 27 with value: 0.18709501535488485.
Fold 1 IBS: 0.20934463006342957
Fold 2 IBS: 0.16626348855382878
Fold 3 IBS: 0.19117275286807775
Fold 4 IBS: 0.1653610699678058
Fold 5 IBS: 0.19753335331998537
[I 2024-04-16 10:22:05,542] Trial 46 finished with value: 0.18593505895462542 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.925572429448618, 'min_weight_fraction_leaf': 0.08676721083273177}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20078459799720833
Fold 2 IBS: 0.17648515464578451
Fold 3 IBS: 0.19226229201317951
Fold 4 IBS: 0.17044349838265743
Fold 5 IBS: 0.1988228675530043
[I 2024-04-16 10:22:10,014] Trial 47 finished with value: 0.1877596821183668 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 264, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9213571492568404, 'min_weight_fraction_leaf': 0.13981998741957938}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20777470701020084
Fold 2 IBS: 0.19819806121913253
Fold 3 IBS: 0.19206408523089602
Fold 4 IBS: 0.20455345941908806
Fold 5 IBS: 0.21359199143332838
[I 2024-04-16 10:22:13,690] Trial 48 finished with value: 0.20323646086252917 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 268, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9948675206762962, 'min_weight_fraction_leaf': 0.14355467192528748}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20833920868185066
Fold 2 IBS: 0.19641978742053248
Fold 3 IBS: 0.19089914369604163
Fold 4 IBS: 0.19551044582583754
Fold 5 IBS: 0.21209727532100356
[I 2024-04-16 10:22:15,358] Trial 49 finished with value: 0.20065317218905315 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9302954535353424, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20772600832510035
Fold 2 IBS: 0.1742560953767108
Fold 3 IBS: 0.18899681699563198
Fold 4 IBS: 0.17664643353661777
Fold 5 IBS: 0.20207162913086515
[I 2024-04-16 10:22:18,759] Trial 50 finished with value: 0.18993939667298523 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9554972202974833, 'min_weight_fraction_leaf': 0.07893980965459402}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2175228940538217
Fold 2 IBS: 0.16882647052353114
Fold 3 IBS: 0.19262466994453928
Fold 4 IBS: 0.16127708924491224
Fold 5 IBS: 0.19790007020123332
[I 2024-04-16 10:22:24,923] Trial 51 finished with value: 0.18763023879360755 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.906363786004768, 'min_weight_fraction_leaf': 0.01993763032727272}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.1994294701749906
Fold 2 IBS: 0.18271153506347773
Fold 3 IBS: 0.1877412420614239
Fold 4 IBS: 0.1779301349070125
Fold 5 IBS: 0.20347444570159795
[I 2024-04-16 10:22:27,479] Trial 52 finished with value: 0.19025736558170053 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9180205789374659, 'min_weight_fraction_leaf': 0.208464530420868}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2143294788132567
Fold 2 IBS: 0.16871602133484195
Fold 3 IBS: 0.18923830444515657
Fold 4 IBS: 0.16447114425777135
Fold 5 IBS: 0.1979457995777836
[I 2024-04-16 10:22:32,501] Trial 53 finished with value: 0.18694014968576203 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.882994548404635, 'min_weight_fraction_leaf': 0.0192164714981712}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21491661558194466
Fold 2 IBS: 0.16865192696486195
Fold 3 IBS: 0.18911632922455485
Fold 4 IBS: 0.164322793559542
Fold 5 IBS: 0.19780078494724415
[I 2024-04-16 10:22:37,633] Trial 54 finished with value: 0.18696169005562951 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8791259750871762, 'min_weight_fraction_leaf': 0.021612413990603922}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21165029134764404
Fold 2 IBS: 0.21713184039980743
Fold 3 IBS: 0.2020959160332439
Fold 4 IBS: 0.2196516953463444
Fold 5 IBS: 0.2174205266346621
[I 2024-04-16 10:22:40,528] Trial 55 finished with value: 0.2135900539523404 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8732977999719564, 'min_weight_fraction_leaf': 0.0218387875769675}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2079119279717199
Fold 2 IBS: 0.17452040666804391
Fold 3 IBS: 0.18897194723766658
Fold 4 IBS: 0.17595369607084504
Fold 5 IBS: 0.20128067491490945
[I 2024-04-16 10:22:44,990] Trial 56 finished with value: 0.18972773057263695 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 306, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.843782187611387, 'min_weight_fraction_leaf': 0.021841146008507534}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20727371387572535
Fold 2 IBS: 0.18581142935300873
Fold 3 IBS: 0.18420810577126234
Fold 4 IBS: 0.1826954923475708
Fold 5 IBS: 0.20414460425521397
[I 2024-04-16 10:22:47,819] Trial 57 finished with value: 0.19282666912055624 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8940258738700295, 'min_weight_fraction_leaf': 0.006298394024379893}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21401047841123993
Fold 2 IBS: 0.22071750963432682
Fold 3 IBS: 0.20490008002784188
Fold 4 IBS: 0.22480148510035142
Fold 5 IBS: 0.21794170884649433
[I 2024-04-16 10:22:50,811] Trial 58 finished with value: 0.21647425240405088 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 253, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.28101469689358977, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2260705108377443
Fold 2 IBS: 0.16842595034518754
Fold 3 IBS: 0.19588890831987768
Fold 4 IBS: 0.15796822714732367
Fold 5 IBS: 0.19732972937931428
[I 2024-04-16 10:22:58,037] Trial 59 finished with value: 0.18913666520588948 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9752510141915198, 'min_weight_fraction_leaf': 0.00018268589057236773}. Best is trial 46 with value: 0.18593505895462542.

Fold 1 IBS: 0.207285461038795
Fold 2 IBS: 0.1927181173372502
Fold 3 IBS: 0.1875847073262801
Fold 4 IBS: 0.18626542533097468
Fold 5 IBS: 0.21021231166082874
[I 2024-04-16 10:23:01,517] Trial 60 finished with value: 0.19681320453882573 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 303, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9034006727918623, 'min_weight_fraction_leaf': 0.05252660219522337}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22222320857283578
Fold 2 IBS: 0.16627488261932677
Fold 3 IBS: 0.1907907801291295
Fold 4 IBS: 0.15665311269211
Fold 5 IBS: 0.19448240192170554
[I 2024-04-16 10:23:07,584] Trial 61 finished with value: 0.18608487718702152 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9365705541234135, 'min_weight_fraction_leaf': 0.031783148716693396}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21973293186989468
Fold 2 IBS: 0.16637936737733827
Fold 3 IBS: 0.19084524745309966
Fold 4 IBS: 0.15860503455855104
Fold 5 IBS: 0.1960405475543053
[I 2024-04-16 10:23:14,675] Trial 62 finished with value: 0.1863206257626378 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8532460059088829, 'min_weight_fraction_leaf': 0.02556027420253138}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21238622298854687
Fold 2 IBS: 0.16823306514375236
Fold 3 IBS: 0.19013144832783335
Fold 4 IBS: 0.16590277189776537
Fold 5 IBS: 0.1970812292594398
[I 2024-04-16 10:23:22,936] Trial 63 finished with value: 0.18674694752346754 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8424289412976247, 'min_weight_fraction_leaf': 0.035176521776568326}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21251914188212104
Fold 2 IBS: 0.16818501271313005
Fold 3 IBS: 0.19002328427487689
Fold 4 IBS: 0.1664131535050948
Fold 5 IBS: 0.19696216365791347
[I 2024-04-16 10:23:32,569] Trial 64 finished with value: 0.18682055120662727 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8468079509014251, 'min_weight_fraction_leaf': 0.056675259960032524}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21335380335193527
Fold 2 IBS: 0.16775952418293757
Fold 3 IBS: 0.18982870088983628
Fold 4 IBS: 0.1660804448667969
Fold 5 IBS: 0.19752793426971405
[I 2024-04-16 10:23:40,044] Trial 65 finished with value: 0.18691008151224403 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.033593279538543006}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2068314777271677
Fold 2 IBS: 0.1818823653044113
Fold 3 IBS: 0.1867008108426068
Fold 4 IBS: 0.17981107312892297
Fold 5 IBS: 0.20387830728635054
[I 2024-04-16 10:23:45,799] Trial 66 finished with value: 0.19182080685789185 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 353, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8472356401950124, 'min_weight_fraction_leaf': 0.0529366596136866}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20910483652280304
Fold 2 IBS: 0.17971015740109278
Fold 3 IBS: 0.18400026782476006
Fold 4 IBS: 0.17665742258292663
Fold 5 IBS: 0.20576920507641572
[I 2024-04-16 10:23:50,140] Trial 67 finished with value: 0.19104837788159965 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9444982451072708, 'min_weight_fraction_leaf': 0.03899677855324381}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20648940063369117
Fold 2 IBS: 0.19534295455434322
Fold 3 IBS: 0.188144538063623
Fold 4 IBS: 0.1949169470370693
Fold 5 IBS: 0.21053498455388758
[I 2024-04-16 10:23:54,099] Trial 68 finished with value: 0.19908576496852284 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7877895913453183, 'min_weight_fraction_leaf': 0.08102747544818781}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20394166174782688
Fold 2 IBS: 0.19677346569963913
Fold 3 IBS: 0.1891515065612692
Fold 4 IBS: 0.20045487618638197
Fold 5 IBS: 0.21575779723377045
[I 2024-04-16 10:23:58,725] Trial 69 finished with value: 0.20121586148577753 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 348, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8640937048774974, 'min_weight_fraction_leaf': 0.35844113234477204}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22147390576901926
Fold 2 IBS: 0.16878361070952955
Fold 3 IBS: 0.19289742131501394
Fold 4 IBS: 0.15642450822458037
Fold 5 IBS: 0.19573438642899904
[I 2024-04-16 10:24:06,439] Trial 70 finished with value: 0.18706276648942843 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9698512970131481, 'min_weight_fraction_leaf': 0.06206444655888782}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2124760152458227
Fold 2 IBS: 0.16848172025498606
Fold 3 IBS: 0.18992014324883777
Fold 4 IBS: 0.1661336629114953
Fold 5 IBS: 0.19710870332529623
[I 2024-04-16 10:24:14,781] Trial 71 finished with value: 0.1868240489972876 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 364, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8456035306116515, 'min_weight_fraction_leaf': 0.03120135154758281}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20761621244028333
Fold 2 IBS: 0.18073216921965327
Fold 3 IBS: 0.18760014895363192
Fold 4 IBS: 0.17874893912085807
Fold 5 IBS: 0.2039376815310608
[I 2024-04-16 10:24:22,006] Trial 72 finished with value: 0.19172703025309748 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8291126566575869, 'min_weight_fraction_leaf': 0.04256934859560442}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20211788261215158
Fold 2 IBS: 0.19294690613170354
Fold 3 IBS: 0.18803486936318167
Fold 4 IBS: 0.19413860771999508
Fold 5 IBS: 0.2102569188255651
[I 2024-04-16 10:24:28,007] Trial 73 finished with value: 0.19749903693051937 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.846356865587186, 'min_weight_fraction_leaf': 0.2814399755208377}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20536086673630327
Fold 2 IBS: 0.17349069261053238
Fold 3 IBS: 0.1911214435179867
Fold 4 IBS: 0.17057554919102758
Fold 5 IBS: 0.20023229606825985
[I 2024-04-16 10:24:35,202] Trial 74 finished with value: 0.18815616962482198 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7862604176864406, 'min_weight_fraction_leaf': 0.03192322260543996}. Best is trial 46 with value: 0.18593505895462542.

Fold 1 IBS: 0.22613938863893251
Fold 2 IBS: 0.17078566610790855
Fold 3 IBS: 0.1918060554350325
Fold 4 IBS: 0.1609525872259648
Fold 5 IBS: 0.19576638517676706
[I 2024-04-16 10:24:45,614] Trial 75 finished with value: 0.1890900165169211 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6854858143225422, 'min_weight_fraction_leaf': 0.014781978409836638}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20539145272671636
Fold 2 IBS: 0.19530699928990344
Fold 3 IBS: 0.18948528388235533
Fold 4 IBS: 0.19829570272263905
Fold 5 IBS: 0.21090398924576984
[I 2024-04-16 10:24:49,816] Trial 76 finished with value: 0.1998766855734768 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8663542569451897, 'min_weight_fraction_leaf': 0.06164950444687135}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20654354205828143
Fold 2 IBS: 0.17481441674697265
Fold 3 IBS: 0.190269325626355
Fold 4 IBS: 0.1769715113695994
Fold 5 IBS: 0.20037808458125742
[I 2024-04-16 10:24:55,486] Trial 77 finished with value: 0.18979537607649316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9399264729381039, 'min_weight_fraction_leaf': 0.10623157459313898}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2065942499274735
Fold 2 IBS: 0.19961139432967556
Fold 3 IBS: 0.1894644134677184
Fold 4 IBS: 0.20244453199859094
Fold 5 IBS: 0.21574470591763428
[I 2024-04-16 10:25:01,909] Trial 78 finished with value: 0.20277185912821852 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9999311602709532, 'min_weight_fraction_leaf': 0.4401997700779695}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20965660103993905
Fold 2 IBS: 0.21451072548088435
Fold 3 IBS: 0.2008395703355506
Fold 4 IBS: 0.21812402366212838
Fold 5 IBS: 0.2171583261557509
[I 2024-04-16 10:25:06,694] Trial 79 finished with value: 0.21205784933485067 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 359, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.744066131242477, 'min_weight_fraction_leaf': 0.0003126429952054685}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.19920711484535378
Fold 2 IBS: 0.1727542533999705
Fold 3 IBS: 0.198159865775465
Fold 4 IBS: 0.16954739238056218
Fold 5 IBS: 0.1930221685631568
[I 2024-04-16 10:25:08,291] Trial 80 finished with value: 0.18653815899290166 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 54, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8861080232545328, 'min_weight_fraction_leaf': 0.08125126316020383}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20442121006254585
Fold 2 IBS: 0.17137671300656207
Fold 3 IBS: 0.1975998202082012
Fold 4 IBS: 0.17524013402906885
Fold 5 IBS: 0.20426389074330129
[I 2024-04-16 10:25:09,722] Trial 81 finished with value: 0.19058035360993586 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 49, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8924014900526624, 'min_weight_fraction_leaf': 0.08895593181563541}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.203359031317457
Fold 2 IBS: 0.17507697438294065
Fold 3 IBS: 0.19434783445230705
Fold 4 IBS: 0.18058791137985974
Fold 5 IBS: 0.2012314104175464
[I 2024-04-16 10:25:11,381] Trial 82 finished with value: 0.19092063239002216 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 72, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8437598446832416, 'min_weight_fraction_leaf': 0.035990855986975975}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.19219159084396767
Fold 2 IBS: 0.17334766089986578
Fold 3 IBS: 0.23524594127404763
Fold 4 IBS: 0.19902956101664537
Fold 5 IBS: 0.18842503110492315
[I 2024-04-16 10:25:11,743] Trial 83 finished with value: 0.19764795702788993 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 2, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.922118731830056, 'min_weight_fraction_leaf': 0.0731545299433685}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20428511342436048
Fold 2 IBS: 0.1799896301725076
Fold 3 IBS: 0.19388724212464398
Fold 4 IBS: 0.16511001105053083
Fold 5 IBS: 0.19735867420569436
[I 2024-04-16 10:25:17,571] Trial 84 finished with value: 0.18812613419554744 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7909804561731724, 'min_weight_fraction_leaf': 0.11700828810083208}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2084578775348877
Fold 2 IBS: 0.19426457594186483
Fold 3 IBS: 0.18723611667351553
Fold 4 IBS: 0.19465436303183162
Fold 5 IBS: 0.20935163978665147
[I 2024-04-16 10:25:20,824] Trial 85 finished with value: 0.19879291459375023 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8719624179281165, 'min_weight_fraction_leaf': 0.051803457363457664}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22544247042865825
Fold 2 IBS: 0.1630256513468111
Fold 3 IBS: 0.19256909998854008
Fold 4 IBS: 0.15361651395715145
Fold 5 IBS: 0.19523852469599223
[I 2024-04-16 10:25:28,752] Trial 86 finished with value: 0.1859784520834306 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 315, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.946980497925672, 'min_weight_fraction_leaf': 0.029863072952735582}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.211698666811812
Fold 2 IBS: 0.1694289503007478
Fold 3 IBS: 0.19473357708600428
Fold 4 IBS: 0.16005631916809057
Fold 5 IBS: 0.199773102803706
[I 2024-04-16 10:25:31,844] Trial 87 finished with value: 0.18713812323407214 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 122, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9539230969817603, 'min_weight_fraction_leaf': 0.09652136904782926}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.22020171827988244
Fold 2 IBS: 0.16926990713298445
Fold 3 IBS: 0.192284914228334
Fold 4 IBS: 0.15728200170563308
Fold 5 IBS: 0.19628056361797028
[I 2024-04-16 10:25:41,914] Trial 88 finished with value: 0.18706382099296087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 389, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9726994171981167, 'min_weight_fraction_leaf': 0.08008172538980439}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20869335287489973
Fold 2 IBS: 0.18877635099296655
Fold 3 IBS: 0.18545543987934543
Fold 4 IBS: 0.17645918166901373
Fold 5 IBS: 0.21071300836085144
[I 2024-04-16 10:25:44,829] Trial 89 finished with value: 0.19401946675541537 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 239, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9218401474143084, 'min_weight_fraction_leaf': 0.031265444034943385}. Best is trial 46 with value: 0.18593505895462542.

Fold 1 IBS: 0.20699759070252
Fold 2 IBS: 0.18410685277890454
Fold 3 IBS: 0.18353461706009355
Fold 4 IBS: 0.17619715129676206
Fold 5 IBS: 0.20499796617822919
[I 2024-04-16 10:25:48,981] Trial 90 finished with value: 0.1911668356033019 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8225840845043781, 'min_weight_fraction_leaf': 0.05864804834976011}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.217351763728157
Fold 2 IBS: 0.16945843188909548
Fold 3 IBS: 0.19034007843019582
Fold 4 IBS: 0.16244329382110362
Fold 5 IBS: 0.19781268762530857
[I 2024-04-16 10:25:55,182] Trial 91 finished with value: 0.1874812510987721 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8861509812631121, 'min_weight_fraction_leaf': 0.014224520657611844}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21696045553773013
Fold 2 IBS: 0.1704866822169904
Fold 3 IBS: 0.19085468141611783
Fold 4 IBS: 0.16103376128943614
Fold 5 IBS: 0.19876434589766828
[I 2024-04-16 10:26:02,680] Trial 92 finished with value: 0.18761998527158857 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9049528527068132, 'min_weight_fraction_leaf': 0.04231066950649405}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.21196935165584188
Fold 2 IBS: 0.16722659903939105
Fold 3 IBS: 0.18987039220392843
Fold 4 IBS: 0.16499345338196442
Fold 5 IBS: 0.19764939088148178
[I 2024-04-16 10:26:09,426] Trial 93 finished with value: 0.1863418374325215 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9366747152403195, 'min_weight_fraction_leaf': 0.027802926132591547}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2059404253018163
Fold 2 IBS: 0.19380402974059494
Fold 3 IBS: 0.1876033430944384
Fold 4 IBS: 0.18405168741196726
Fold 5 IBS: 0.20458819720505517
[I 2024-04-16 10:26:14,230] Trial 94 finished with value: 0.1951975365507744 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9495699974520388, 'min_weight_fraction_leaf': 0.02871372240989487}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2094685066050624
Fold 2 IBS: 0.16927915291225965
Fold 3 IBS: 0.1924577643225916
Fold 4 IBS: 0.16602944533090672
Fold 5 IBS: 0.1957721996217021
[I 2024-04-16 10:26:19,182] Trial 95 finished with value: 0.18660141375850448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9791039731673459, 'min_weight_fraction_leaf': 0.04549233298877235}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20755395439739033
Fold 2 IBS: 0.1763119523991306
Fold 3 IBS: 0.19451944450840733
Fold 4 IBS: 0.1665181624649935
Fold 5 IBS: 0.1980829739408134
[I 2024-04-16 10:26:24,383] Trial 96 finished with value: 0.18859729754214705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 252, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9801531481203417, 'min_weight_fraction_leaf': 0.07059907684587055}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20778648807186673
Fold 2 IBS: 0.17421281284427612
Fold 3 IBS: 0.19712933488182183
Fold 4 IBS: 0.1640966839457895
Fold 5 IBS: 0.20039762446205991
[I 2024-04-16 10:26:29,531] Trial 97 finished with value: 0.1887245888411628 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9277927488483547, 'min_weight_fraction_leaf': 0.04722615213705901}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.20725528002259883
Fold 2 IBS: 0.1985207548275814
Fold 3 IBS: 0.18902050026034625
Fold 4 IBS: 0.20014645511817541
Fold 5 IBS: 0.21107782417383592
[I 2024-04-16 10:26:32,550] Trial 98 finished with value: 0.20120416288050755 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 263, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9830419480731235, 'min_weight_fraction_leaf': 0.011263511832006995}. Best is trial 46 with value: 0.18593505895462542.
Fold 1 IBS: 0.2017930721181439
Fold 2 IBS: 0.18583437036224545
Fold 3 IBS: 0.18941659088417465
Fold 4 IBS: 0.1839889537529638
Fold 5 IBS: 0.2037986821166232
[I 2024-04-16 10:26:36,458] Trial 99 finished with value: 0.1929663338468302 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4230786458254288, 'min_weight_fraction_leaf': 0.05722085597839154}. Best is trial 46 with value: 0.18593505895462542.


* Best trial for IBS:
 FrozenTrial(number=46, state=TrialState.COMPLETE, values=[0.18593505895462542], datetime_start=datetime.datetime(2024, 4, 16, 10, 22, 0, 722081), datetime_complete=datetime.datetime(2024, 4, 16, 10, 22, 5, 540712), params={'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.925572429448618, 'min_weight_fraction_leaf': 0.08676721083273177}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=46, value=None)


* Best Score for IBS:
 0.18593505895462542

In [86]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [87]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.867
train_ibs:  0.186

#### Test

In [88]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [89]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=14, max_features='auto', max_leaf_nodes=18,
                   max_samples=0.7692755291164257, min_samples_leaf=2,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.006944921267975795,
                   n_estimators=182, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.616

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=3,
                   max_samples=0.925572429448618, min_samples_leaf=5,
                   min_samples_split=17,
                   min_weight_fraction_leaf=0.08676721083273177,
                   n_estimators=272, random_state=123, warm_start=True)

IBS: 0.214

In [90]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [91]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 10:26:38,389] A new study created in memory with name: no-name-999ec6b9-c88b-478e-82c0-ab211c8f9a67

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:27:09,273] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:27:22,250] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:27:38,029] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:28:16,847] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:28:30,287] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:28:33,858] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:28:52,927] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:28:58,108] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:28:59,199] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 10:29:55,195] Trial 9 finished with value: 0.7148887835576376 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7148887835576376.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 10:31:15,903] Trial 10 finished with value: 0.6739494649137633 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7148887835576376.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:32:42,577] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7148887835576376.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.795774647887324
[I 2024-04-16 10:33:55,340] Trial 12 finished with value: 0.7399996696599189 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:28,960] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:35:14,735] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:06,797] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:33,089] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:37:28,191] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:38:43,883] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:38:48,322] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:23,557] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 10:40:33,402] Trial 21 finished with value: 0.6762505605169181 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 10:41:34,845] Trial 22 finished with value: 0.7204995689745777 and parameters: {'subsample': 0.8956069884856214, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2154325997461391, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.38657871816113815, 'max_features': 'auto', 'min_impurity_decrease': 5.581115247824534e-07, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:42:27,340] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7743503496065262, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.31930849090648333, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9663328483036315, 'min_weight_fraction_leaf': 0.441052304834414, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:43:11,864] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8969825748215434, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21976013005558012, 'n_estimators': 340, 'criterion': 'squared_error', 'ccp_alpha': 0.785180332493211, 'min_weight_fraction_leaf': 0.2669492013977464, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:43:57,690] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8840318412875596, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.27382248438555523, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 2.0183033060186855, 'min_weight_fraction_leaf': 0.33643534713187806, 'max_features': 'auto', 'min_impurity_decrease': 5.889654690360788e-06, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:44:39,024] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7565765917190008, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.4300954216773497, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6678836557349488, 'min_weight_fraction_leaf': 0.06207030473994396, 'max_features': 1, 'min_impurity_decrease': 7.622421032390112e-07, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:45:39,104] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.322970332048742, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 5.9472530603001, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 7.551787280023211e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:45:58,408] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.5232204998663266, 'n_estimators': 326, 'criterion': 'squared_error', 'ccp_alpha': 4.188554251555486, 'min_weight_fraction_leaf': 0.43612805409636834, 'max_features': 0.1, 'min_impurity_decrease': 3.2161459286083955e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:46:03,210] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.32499045544570565, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 2.694991982922698, 'min_weight_fraction_leaf': 0.37973053029520576, 'max_features': 'log2', 'min_impurity_decrease': 1.983769791843576e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:46:21,496] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.1618733123667288, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.29835074442775955, 'max_features': 'auto', 'min_impurity_decrease': 3.855449012555335e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.744131455399061
[I 2024-04-16 10:47:21,999] Trial 31 finished with value: 0.7065394554594882 and parameters: {'subsample': 0.9458857893837966, 'learning_rate': 0.016420196712320707, 'dropout_rate': 0.2035906465216125, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.36089352993330637, 'max_features': 'auto', 'min_impurity_decrease': 4.318534340206297e-07, 'validation_fraction': 0.9595045281115817, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 10:48:23,266] Trial 32 finished with value: 0.7338746949532662 and parameters: {'subsample': 0.8638126341310897, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.22569622133720652, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.019083703384414813, 'min_weight_fraction_leaf': 0.351646089861356, 'max_features': 'auto', 'min_impurity_decrease': 1.0352347378444166e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:49:04,051] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8787207656433499, 'learning_rate': 0.025630755044466963, 'dropout_rate': 0.2619733844963128, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.3487071420031831, 'max_features': 'auto', 'min_impurity_decrease': 1.3326513674306949e-07, 'validation_fraction': 0.855139201184975, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:49:47,700] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7038358300021869, 'learning_rate': 0.016887189012329846, 'dropout_rate': 0.37019259462044524, 'n_estimators': 472, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8672217172879074, 'min_weight_fraction_leaf': 0.4224409922525036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0476374112133879e-07, 'validation_fraction': 0.9083519198432543, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:50:41,447] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.8534970531902419, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.29894506704091134, 'n_estimators': 429, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1524333738759642, 'min_weight_fraction_leaf': 0.16211724647631331, 'max_features': None, 'min_impurity_decrease': 8.53144724712845e-07, 'validation_fraction': 0.8123223724670843, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:51:14,021] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6682496627875864, 'learning_rate': 0.008294153240894362, 'dropout_rate': 0.14303426030295235, 'n_estimators': 312, 'criterion': 'squared_error', 'ccp_alpha': 0.48701662298918014, 'min_weight_fraction_leaf': 0.24844276308137436, 'max_features': 'auto', 'min_impurity_decrease': 1.0611200051423029e-05, 'validation_fraction': 0.6528075856343438, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:52:18,681] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7883126136564298, 'learning_rate': 0.03053220011751144, 'dropout_rate': 0.21915428448310503, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.198246212835568, 'min_weight_fraction_leaf': 0.2937098339627597, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.36353542989298265, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:52:37,658] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.022165709324438794, 'dropout_rate': 0.7673236646699829, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.4820963556426466, 'max_features': 'auto', 'min_impurity_decrease': 2.4453569806717e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:52:59,515] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.01319475669500773, 'dropout_rate': 0.4241449034531136, 'n_estimators': 345, 'criterion': 'squared_error', 'ccp_alpha': 2.0500352682881138, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:53:42,546] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5863013406787322, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.34949562340400464, 'n_estimators': 415, 'criterion': 'squared_error', 'ccp_alpha': 0.5271854997531392, 'min_weight_fraction_leaf': 0.415431900491221, 'max_features': 'auto', 'min_impurity_decrease': 2.2073664358493507e-07, 'validation_fraction': 0.7117322595758466, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 10:54:43,412] Trial 41 finished with value: 0.7277354181838703 and parameters: {'subsample': 0.9412170634308962, 'learning_rate': 0.016796866360623053, 'dropout_rate': 0.20081359178715893, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.01657550447328801, 'min_weight_fraction_leaf': 0.3505399688940837, 'max_features': 'auto', 'min_impurity_decrease': 9.905607188997223e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.744131455399061
[I 2024-04-16 10:55:38,691] Trial 42 finished with value: 0.7253442328364919 and parameters: {'subsample': 0.9171766984451564, 'learning_rate': 0.007773927115663986, 'dropout_rate': 0.2396004577204922, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.0083279040311737, 'min_weight_fraction_leaf': 0.36341209364761096, 'max_features': 'auto', 'min_impurity_decrease': 8.600111371198923e-07, 'validation_fraction': 0.9483049107677477, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:56:36,710] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.9108232635752186, 'learning_rate': 0.008003076263430912, 'dropout_rate': 0.16429624388711278, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 1.148366461475106, 'min_weight_fraction_leaf': 0.3638040744851804, 'max_features': 'auto', 'min_impurity_decrease': 8.346293016478022e-06, 'validation_fraction': 0.9399411414156236, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:57:29,108] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9989761273684051, 'learning_rate': 0.00565702820673318, 'dropout_rate': 0.23815552262133566, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 1.8660544568187023, 'min_weight_fraction_leaf': 0.32701048366833557, 'max_features': 'auto', 'min_impurity_decrease': 9.164976275637937e-07, 'validation_fraction': 0.8820072870943625, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:58:24,141] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8626347512538699, 'learning_rate': 0.020184095116582045, 'dropout_rate': 0.1399746504160479, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 6.649876339233933, 'min_weight_fraction_leaf': 0.41535848381884183, 'max_features': 0.1, 'min_impurity_decrease': 1.758780255854688e-05, 'validation_fraction': 0.965992193119439, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:58:31,156] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.9600435779641728, 'learning_rate': 0.030307000616944805, 'dropout_rate': 0.9694253886674298, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.5293904611088607, 'min_weight_fraction_leaf': 0.3707204535290808, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013554285626863527, 'validation_fraction': 0.8433619277880944, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 20}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6502347417840375
[I 2024-04-16 10:58:48,680] Trial 47 finished with value: 0.6837407748517323 and parameters: {'subsample': 0.8232452491390325, 'learning_rate': 0.0010864400202530565, 'dropout_rate': 0.19509781722453806, 'n_estimators': 246, 'criterion': 'squared_error', 'ccp_alpha': 0.09577969393946249, 'min_weight_fraction_leaf': 0.4612510836743603, 'max_features': 'auto', 'min_impurity_decrease': 2.290718019355971e-06, 'validation_fraction': 0.9987850848994776, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:58:49,038] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9205853887854631, 'learning_rate': 0.015063288166862612, 'dropout_rate': 0.6996455537664029, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 1.234909174722316, 'min_weight_fraction_leaf': 0.3468414050166919, 'max_features': None, 'min_impurity_decrease': 1.1980803500659586e-06, 'validation_fraction': 0.789476910449492, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:58:59,259] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.8584821913791967, 'learning_rate': 0.04184187217123891, 'dropout_rate': 0.5876831898987365, 'n_estimators': 279, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3158222061342544, 'min_weight_fraction_leaf': 0.31138294902869135, 'max_features': 'log2', 'min_impurity_decrease': 5.926066318715653e-07, 'validation_fraction': 0.9027576817684192, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:59:49,169] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.970830915699766, 'learning_rate': 0.008517040180540838, 'dropout_rate': 0.11630369695875253, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.6764289629319513, 'min_weight_fraction_leaf': 0.22751653971684832, 'max_features': 'auto', 'min_impurity_decrease': 4.971000534416321e-06, 'validation_fraction': 0.9492160383375527, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 11:00:31,596] Trial 51 finished with value: 0.7251886212920475 and parameters: {'subsample': 0.7962239992639443, 'learning_rate': 0.022072089207892297, 'dropout_rate': 0.24568799595260493, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.012353393991434636, 'min_weight_fraction_leaf': 0.3966155265905691, 'max_features': 'auto', 'min_impurity_decrease': 2.1936100454733836e-07, 'validation_fraction': 0.8455432081663881, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 11:01:19,566] Trial 52 finished with value: 0.7305458194801607 and parameters: {'subsample': 0.8040225491688882, 'learning_rate': 0.022140218438295653, 'dropout_rate': 0.24737218107101291, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.03660198360294675, 'min_weight_fraction_leaf': 0.3884889792121647, 'max_features': 'auto', 'min_impurity_decrease': 2.2796958064199354e-07, 'validation_fraction': 0.854324003727559, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:02:13,242] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.7871371108234366, 'learning_rate': 0.023042656989511353, 'dropout_rate': 0.25313788059133613, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.9311410844850458, 'min_weight_fraction_leaf': 0.4094624681121705, 'max_features': 'auto', 'min_impurity_decrease': 1.770926710327986e-07, 'validation_fraction': 0.8394982011711836, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:02:29,488] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8216003600781934, 'learning_rate': 0.018771949946189165, 'dropout_rate': 0.8506831202560587, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.48953881004914557, 'min_weight_fraction_leaf': 0.2730613968304923, 'max_features': 'auto', 'min_impurity_decrease': 2.4544669130589735e-07, 'validation_fraction': 0.8744022302982001, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:03:15,922] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9137725083286111, 'learning_rate': 0.03334997201384794, 'dropout_rate': 0.29231716916379974, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.400772188710969, 'min_weight_fraction_leaf': 0.4998387701732778, 'max_features': 'auto', 'min_impurity_decrease': 1.1484691000127718e-07, 'validation_fraction': 0.7499576977802935, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:04:09,062] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.7301701043140242, 'learning_rate': 0.07563239727117915, 'dropout_rate': 0.18285747474549977, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 1.3142104786505762, 'min_weight_fraction_leaf': 0.398818501696366, 'max_features': 'auto', 'min_impurity_decrease': 1.37107675515093e-06, 'validation_fraction': 0.9769184491065465, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 11:04:57,129] Trial 57 finished with value: 0.7130737733674322 and parameters: {'subsample': 0.8447974448466777, 'learning_rate': 0.026300674571633445, 'dropout_rate': 0.3933140501049528, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.0019231547695728619, 'min_weight_fraction_leaf': 0.4497752574786321, 'max_features': 'auto', 'min_impurity_decrease': 3.0397473583824277e-07, 'validation_fraction': 0.9043607687797511, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:05:30,143] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8001260306807542, 'learning_rate': 0.04035739114123531, 'dropout_rate': 0.34309202286041174, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 7.96887264775278, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 1, 'min_impurity_decrease': 2.548222090790957e-06, 'validation_fraction': 0.8368053032017708, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:06:13,876] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9386320465614315, 'learning_rate': 0.0046218127846011405, 'dropout_rate': 0.23726258582704846, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9495956426269169, 'min_weight_fraction_leaf': 0.3507587728220414, 'max_features': 0.1, 'min_impurity_decrease': 5.327348003678687e-07, 'validation_fraction': 0.7937489212794213, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 18}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:06:45,197] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.7457764864101614, 'learning_rate': 0.013913019847381093, 'dropout_rate': 0.2802313234402579, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 2.8029484350487133, 'min_weight_fraction_leaf': 0.2614148759574215, 'max_features': 'auto', 'min_impurity_decrease': 1.9564560597564265e-07, 'validation_fraction': 0.8811459545611348, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:07:32,647] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8807242730119922, 'learning_rate': 0.011237316919845534, 'dropout_rate': 0.21913936290206518, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.4933072636379361, 'min_weight_fraction_leaf': 0.3875891410631565, 'max_features': 'auto', 'min_impurity_decrease': 9.882732394296688e-07, 'validation_fraction': 0.9372322610150985, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 11:08:29,374] Trial 62 finished with value: 0.7295264107604176 and parameters: {'subsample': 0.9069044656671411, 'learning_rate': 0.01643486305639612, 'dropout_rate': 0.16523918422475894, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.022435687471224874, 'min_weight_fraction_leaf': 0.37553845203078473, 'max_features': 'auto', 'min_impurity_decrease': 5.889332196421936e-07, 'validation_fraction': 0.9275594296798731, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:09:29,680] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.9801560241682516, 'learning_rate': 0.02043806262474091, 'dropout_rate': 0.1375051834367063, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.7183706920220042, 'min_weight_fraction_leaf': 0.3699000085884939, 'max_features': 'auto', 'min_impurity_decrease': 3.9039071549423344e-07, 'validation_fraction': 0.9934903904178206, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:10:16,120] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9277442486522394, 'learning_rate': 0.01565980187000121, 'dropout_rate': 0.10698873156508726, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 0.3045978164453682, 'min_weight_fraction_leaf': 0.33394184808274385, 'max_features': 'auto', 'min_impurity_decrease': 1.4496904143040433e-06, 'validation_fraction': 0.919872382223042, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 11:11:10,011] Trial 65 finished with value: 0.669905005917179 and parameters: {'subsample': 0.8389348527747851, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.1831917670580087, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.002774117008967604, 'min_weight_fraction_leaf': 0.30504352196445944, 'max_features': 'log2', 'min_impurity_decrease': 7.298411535762544e-07, 'validation_fraction': 0.9673516401919608, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:12:00,259] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8803601425460227, 'learning_rate': 0.02454986182406897, 'dropout_rate': 0.2457020680116681, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 1.0543834057431296, 'min_weight_fraction_leaf': 0.39762979335749954, 'max_features': 'auto', 'min_impurity_decrease': 1.062308544034983e-07, 'validation_fraction': 0.8856930810090413, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:12:46,244] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.9039131398456093, 'learning_rate': 0.005393688405155129, 'dropout_rate': 0.30991266215324687, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.7765508574580127, 'min_weight_fraction_leaf': 0.4319443057218696, 'max_features': 'auto', 'min_impurity_decrease': 0.04710428475886704, 'validation_fraction': 0.7743163230527812, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:13:38,995] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6800178109385019, 'learning_rate': 0.02933409598200374, 'dropout_rate': 0.17928084108359857, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.6074461301183274, 'min_weight_fraction_leaf': 0.4780015649862437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.013697139277504513, 'validation_fraction': 0.8638940835250288, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:14:16,036] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7692672682208916, 'learning_rate': 0.01769416030307426, 'dropout_rate': 0.27876204748733485, 'n_estimators': 374, 'criterion': 'friedman_mse', 'ccp_alpha': 0.286953040189292, 'min_weight_fraction_leaf': 0.2913187893803262, 'max_features': 'auto', 'min_impurity_decrease': 2.1481238791541268e-07, 'validation_fraction': 0.9566923161441689, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:15:03,434] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.8100461387280435, 'learning_rate': 0.009720778256433736, 'dropout_rate': 0.1582247006910296, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.32462660328254567, 'max_features': 'auto', 'min_impurity_decrease': 4.620887402185137e-07, 'validation_fraction': 0.8233170212984697, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:15:55,806] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.8895178823933076, 'learning_rate': 0.0141589777741273, 'dropout_rate': 0.19713266114650715, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.26273325094178557, 'min_weight_fraction_leaf': 0.3798826712848097, 'max_features': 'auto', 'min_impurity_decrease': 5.75677082319795e-07, 'validation_fraction': 0.9240897742855856, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 11:16:42,772] Trial 72 finished with value: 0.7362433481107317 and parameters: {'subsample': 0.8642777625557101, 'learning_rate': 0.02186591972980013, 'dropout_rate': 0.22937371721341443, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.004815838793413725, 'min_weight_fraction_leaf': 0.35789966830713343, 'max_features': 'auto', 'min_impurity_decrease': 1.5921848241604391e-07, 'validation_fraction': 0.9292016960714522, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:16:52,753] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8636670131007999, 'learning_rate': 0.03250475281963551, 'dropout_rate': 0.22773314504043318, 'n_estimators': 178, 'criterion': 'squared_error', 'ccp_alpha': 0.7340529855138669, 'min_weight_fraction_leaf': 0.35875610620029763, 'max_features': 'auto', 'min_impurity_decrease': 1.625419403219883e-07, 'validation_fraction': 0.9704103462569147, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:17:45,601] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.9442631157989567, 'learning_rate': 0.021290745338913994, 'dropout_rate': 0.2680216449479869, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.6201513737559716, 'min_weight_fraction_leaf': 0.335188908651544, 'max_features': 'auto', 'min_impurity_decrease': 3.513254689525364e-07, 'validation_fraction': 0.18271784653855216, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 11:18:23,534] Trial 75 finished with value: 0.7260941507877564 and parameters: {'subsample': 0.8321594525103285, 'learning_rate': 0.05118727647103342, 'dropout_rate': 0.32340656921315775, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.008839136595664831, 'min_weight_fraction_leaf': 0.3770321771415034, 'max_features': 'auto', 'min_impurity_decrease': 1.6809052999382329e-07, 'validation_fraction': 0.9136795904227917, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:19:03,231] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.8394003484184053, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.33024491820993, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 0.3152854263053759, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 0.0004591155005280019, 'validation_fraction': 0.9138168401699509, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:19:38,859] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9753940115175919, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.2959323288697957, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.283213839796126, 'min_weight_fraction_leaf': 0.1508392399442322, 'max_features': 1, 'min_impurity_decrease': 1.0435805071795419e-07, 'validation_fraction': 0.9927089836547902, 'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 11}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:20:22,075] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.9259347360875612, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.3915655480454143, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.9809253886223749, 'min_weight_fraction_leaf': 0.3733741757380721, 'max_features': 'auto', 'min_impurity_decrease': 1.5055551845496619e-07, 'validation_fraction': 0.9291562047924866, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:21:20,646] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8989541367720106, 'learning_rate': 0.06143531661227892, 'dropout_rate': 0.12785764143532674, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.6703560127430094, 'min_weight_fraction_leaf': 0.35485369908449244, 'max_features': 0.1, 'min_impurity_decrease': 8.782239961636543e-07, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:22:03,460] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04966610548933414, 'dropout_rate': 0.1648630717352459, 'n_estimators': 431, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.4045734888864501, 'max_features': 'auto', 'min_impurity_decrease': 3.191262319869447e-07, 'validation_fraction': 0.8923340974201528, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6029411764705882
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 11:22:51,809] Trial 81 finished with value: 0.6744664286969589 and parameters: {'subsample': 0.8204753653660055, 'learning_rate': 0.04319851444329214, 'dropout_rate': 0.2121998392139111, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.02534349958176617, 'min_weight_fraction_leaf': 0.19125171416337036, 'max_features': 'auto', 'min_impurity_decrease': 2.565945077766206e-07, 'validation_fraction': 0.9541426339705571, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:23:43,904] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.8644226713292206, 'learning_rate': 0.018537386015478913, 'dropout_rate': 0.25663963968872483, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.28961979264370374, 'min_weight_fraction_leaf': 0.42326153107157766, 'max_features': 'auto', 'min_impurity_decrease': 1.675412775388128e-07, 'validation_fraction': 0.8621305841831005, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:24:17,493] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7358074146930308, 'learning_rate': 0.025706300160214, 'dropout_rate': 0.22968230522988387, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.49700068111119755, 'min_weight_fraction_leaf': 0.38468084627630217, 'max_features': 'auto', 'min_impurity_decrease': 4.1067211462896935e-07, 'validation_fraction': 0.8206125715100036, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6629464285714286
Fold 3 C-index: 0.6936274509803921
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.687793427230047
[I 2024-04-16 11:24:20,156] Trial 84 finished with value: 0.6801102414539131 and parameters: {'subsample': 0.42529357448835425, 'learning_rate': 0.02762233475108975, 'dropout_rate': 0.20280079758879627, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 0.20868220613127783, 'min_weight_fraction_leaf': 0.3160345364912664, 'max_features': 'auto', 'min_impurity_decrease': 6.38504114422443e-07, 'validation_fraction': 0.7210112012398474, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 11:24:58,277] Trial 85 finished with value: 0.7302130922224155 and parameters: {'subsample': 0.7970928489554175, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.3033612838692909, 'n_estimators': 397, 'criterion': 'squared_error', 'ccp_alpha': 0.011240889643051085, 'min_weight_fraction_leaf': 0.34141609928683797, 'max_features': 'auto', 'min_impurity_decrease': 1.9571285619395883e-06, 'validation_fraction': 0.6711551666986062, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:25:40,658] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.7801819526684379, 'learning_rate': 0.04588676944797367, 'dropout_rate': 0.357396641130168, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.4506190457160326, 'min_weight_fraction_leaf': 0.34072181196437984, 'max_features': 'log2', 'min_impurity_decrease': 1.8472872213713208e-06, 'validation_fraction': 0.6189549502198839, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:26:10,820] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.6437268568076402, 'learning_rate': 0.06917862456904772, 'dropout_rate': 0.30671889534310337, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 1.0467343938198086, 'min_weight_fraction_leaf': 0.36233395118072964, 'max_features': 'sqrt', 'min_impurity_decrease': 5.495613028050001e-06, 'validation_fraction': 0.9483334737685223, 'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:26:50,517] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.962719081727985, 'learning_rate': 0.03821268022738647, 'dropout_rate': 0.4180635358371704, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7258523809610303, 'min_weight_fraction_leaf': 0.3460523584882933, 'max_features': 'auto', 'min_impurity_decrease': 3.0700401682957075e-06, 'validation_fraction': 0.6833916423614368, 'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:27:14,248] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.8357489060156716, 'learning_rate': 0.0484285379083209, 'dropout_rate': 0.27310144029573485, 'n_estimators': 310, 'criterion': 'squared_error', 'ccp_alpha': 2.209004069839297, 'min_weight_fraction_leaf': 0.28633856037020633, 'max_features': 'auto', 'min_impurity_decrease': 1.012846054245825e-06, 'validation_fraction': 0.9999095319465745, 'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:27:40,760] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.8746630223915809, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.3306578048242935, 'n_estimators': 330, 'criterion': 'squared_error', 'ccp_alpha': 4.633272020962325, 'min_weight_fraction_leaf': 0.3779481569897128, 'max_features': None, 'min_impurity_decrease': 8.00355252800393e-05, 'validation_fraction': 0.9050973139966927, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 8}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 11:28:22,462] Trial 91 finished with value: 0.7157332482337333 and parameters: {'subsample': 0.7933548327638641, 'learning_rate': 0.003312019603128164, 'dropout_rate': 0.2507679538048139, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.03780967061735356, 'min_weight_fraction_leaf': 0.39772958841171435, 'max_features': 'auto', 'min_impurity_decrease': 2.499487061211126e-07, 'validation_fraction': 0.8580115400818135, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:29:10,565] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.7561961860443563, 'learning_rate': 0.023527180352486913, 'dropout_rate': 0.16479361613280366, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.43394239821505587, 'min_weight_fraction_leaf': 0.42562332923735957, 'max_features': 'auto', 'min_impurity_decrease': 1.6938318820779942e-06, 'validation_fraction': 0.9701449564634904, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:29:44,177] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8059949627822843, 'learning_rate': 0.01234024470004173, 'dropout_rate': 0.29267203803789943, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.20319330870280422, 'min_weight_fraction_leaf': 0.365699391779537, 'max_features': 'auto', 'min_impurity_decrease': 1.6653350619746936e-07, 'validation_fraction': 0.9355041944373461, 'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:30:16,979] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.6999082025869978, 'learning_rate': 0.017219979911559023, 'dropout_rate': 0.373035235690205, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 6.420837118226172, 'min_weight_fraction_leaf': 0.40883838967583214, 'max_features': 'auto', 'min_impurity_decrease': 4.6709965065070267e-07, 'validation_fraction': 0.887860002388832, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:31:07,839] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5105271208530126, 'learning_rate': 0.007748724766312231, 'dropout_rate': 0.23543004659865058, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.5595582823457022, 'min_weight_fraction_leaf': 0.2213775810637544, 'max_features': 'auto', 'min_impurity_decrease': 1.0829272877301445e-06, 'validation_fraction': 0.6772676512149463, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7769953051643192
[I 2024-04-16 11:31:56,382] Trial 96 finished with value: 0.7256628426099365 and parameters: {'subsample': 0.9098985521833942, 'learning_rate': 0.052234132276152874, 'dropout_rate': 0.21111234228536274, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.03142354075915592, 'min_weight_fraction_leaf': 0.3283302077126804, 'max_features': 'auto', 'min_impurity_decrease': 1.3235311220249993e-07, 'validation_fraction': 0.8042400059038284, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 12 with value: 0.7399996696599189.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:32:34,797] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.901549774839904, 'learning_rate': 0.0518850036895118, 'dropout_rate': 0.49263846952113033, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8327347493373075, 'min_weight_fraction_leaf': 0.30244388210473977, 'max_features': 'auto', 'min_impurity_decrease': 1.4238172259761717e-07, 'validation_fraction': 0.7814800742737378, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:33:18,409] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.946617594291913, 'learning_rate': 0.06132823148390858, 'dropout_rate': 0.20690053299878008, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.25682935609263036, 'min_weight_fraction_leaf': 0.32255361828136364, 'max_features': 1, 'min_impurity_decrease': 3.172670658418841e-07, 'validation_fraction': 0.7982829558993232, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 12 with value: 0.7399996696599189.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.5654008438818565

[I 2024-04-16 11:34:03,326] A new study created in memory with name: no-name-5974970e-bee3-4ba7-bd85-cd251f585333

Fold 5 C-index: 0.7629107981220657
[I 2024-04-16 11:34:03,306] Trial 99 finished with value: 0.6977749461751669 and parameters: {'subsample': 0.998129126621856, 'learning_rate': 0.00967252777219979, 'dropout_rate': 0.18568433870901738, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004394117663473222, 'min_weight_fraction_leaf': 0.3369308574386013, 'max_features': 'auto', 'min_impurity_decrease': 8.018566601368315e-06, 'validation_fraction': 0.7574519027338645, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 12 with value: 0.7399996696599189.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.7399996696599189], datetime_start=datetime.datetime(2024, 4, 16, 10, 32, 42, 586477), datetime_complete=datetime.datetime(2024, 4, 16, 10, 33, 55, 338667), params={'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=12, value=None)


* Best Score for C-index:
 0.7399996696599189

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:34:19,460] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:34:26,196] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:34:34,290] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:34:53,899] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:35:00,914] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:35:02,804] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:35:13,735] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:35:16,485] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:35:16,874] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.2128537475974278
Fold 2 IBS: 0.22024902992742937
Fold 3 IBS: 0.2036757896357088
Fold 4 IBS: 0.22379989362838207
Fold 5 IBS: 0.21720663584018296
[I 2024-04-16 11:35:48,027] Trial 9 finished with value: 0.2155570193258262 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21361208429589837
Fold 2 IBS: 0.22119337423142857
Fold 3 IBS: 0.20422163542183314
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21784773839776864
[I 2024-04-16 11:36:35,276] Trial 10 finished with value: 0.21628765863973537 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:37:28,392] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.2138342515802909
Fold 2 IBS: 0.22140255954991353
Fold 3 IBS: 0.20446094529787798
Fold 4 IBS: 0.22465623055238298
Fold 5 IBS: 0.2179885030861713
[I 2024-04-16 11:38:12,164] Trial 12 finished with value: 0.2164684980133273 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 11:38:30,210] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:39:12,468] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:39:40,119] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:39:55,630] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:40:28,976] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:40:45,038] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:40:48,363] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:41:21,283] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21368081158317526
Fold 2 IBS: 0.22153122053697344
Fold 3 IBS: 0.20438589708295674
Fold 4 IBS: 0.22463565682317985
Fold 5 IBS: 0.21798450581810203
[I 2024-04-16 11:41:54,309] Trial 21 finished with value: 0.21644361836887746 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21302790139502722
Fold 2 IBS: 0.2203859020701612

Fold 3 IBS: 0.2039525932207316
Fold 4 IBS: 0.22401636959265878
Fold 5 IBS: 0.21723302548509774
[I 2024-04-16 11:42:33,970] Trial 22 finished with value: 0.2157231583527353 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:43:09,033] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:43:31,767] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:43:52,137] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:44:09,204] Trial 26 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:44:11,612] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:44:17,155] Trial 28 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:44:37,924] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:45:12,537] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21326862978576686
Fold 2 IBS: 0.2210813893462159
Fold 3 IBS: 0.20416936232206076
Fold 4 IBS: 0.224409146213765
Fold 5 IBS: 0.2174662620955696
[I 2024-04-16 11:45:47,876] Trial 31 finished with value: 0.21607895795267562 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21265462725075449
Fold 2 IBS: 0.2204257334985705
Fold 3 IBS: 0.20397494518039208
Fold 4 IBS: 0.22436470362658575
Fold 5 IBS: 0.2171702564147175
[I 2024-04-16 11:46:24,094] Trial 32 finished with value: 0.21571805319420406 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:46:46,283] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 11:47:09,821] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:47:18,516] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:47:45,013] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:47:48,362] Trial 37 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:47:59,891] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:48:17,011] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:48:40,444] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21343972924860297
Fold 2 IBS: 0.22040213418324436
Fold 3 IBS: 0.20422553455737508
Fold 4 IBS: 0.223054763444453
Fold 5 IBS: 0.217277332164069
[I 2024-04-16 11:49:20,151] Trial 41 finished with value: 0.21567989871954887 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21319951383922744
Fold 2 IBS: 0.2203384834690888
Fold 3 IBS: 0.20412438325013108
Fold 4 IBS: 0.22368658846556563
Fold 5 IBS: 0.21713298280303828
[I 2024-04-16 11:50:00,056] Trial 42 finished with value: 0.21569639036541025 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:50:48,435] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:51:28,009] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:51:38,412] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21367772856775613
Fold 2 IBS: 0.22135025645802206
Fold 3 IBS: 0.20434795802913167
Fold 4 IBS: 0.22452690894235955
Fold 5 IBS: 0.21798015093325962
[I 2024-04-16 11:52:07,738] Trial 46 finished with value: 0.2163766005861058 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:52:26,057] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:52:26,256] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 11:52:34,191] Trial 49 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 11:52:56,000] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.2131461429175361
Fold 2 IBS: 0.2208495886734572
Fold 3 IBS: 0.20421136524084818
Fold 4 IBS: 0.22451211402844548
Fold 5 IBS: 0.21752021771340435
[I 2024-04-16 11:53:32,178] Trial 51 finished with value: 0.21604788571473826 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.213580508502216
Fold 2 IBS: 0.22096543904993846
Fold 3 IBS: 0.20426426298705622
Fold 4 IBS: 0.22452441731877534
Fold 5 IBS: 0.21764616670366058
[I 2024-04-16 11:54:08,003] Trial 52 finished with value: 0.21619615891232935 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:54:43,849] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:55:17,473] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:55:44,229] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 11:56:04,611] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:56:28,270] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 11:56:54,667] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 11:57:16,020] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:57:33,501] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:58:09,587] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9319260511303565, 'learning_rate': 0.006981217524957076, 'dropout_rate': 0.2694290399109642, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.2266262530125842, 'min_weight_fraction_leaf': 0.2262208916321135, 'max_features': 'auto', 'min_impurity_decrease': 6.393438969585487e-06, 'validation_fraction': 0.968342815685117, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2155570193258262.
Fold 1 IBS: 0.21261827944826023
Fold 2 IBS: 0.21980190055259302
Fold 3 IBS: 0.20384635335083123
Fold 4 IBS: 0.22428599240586905
Fold 5 IBS: 0.21675480287088003
[I 2024-04-16 11:58:43,962] Trial 62 finished with value: 0.21546146572568672 and parameters: {'subsample': 0.9972198040262032, 'learning_rate': 0.008659221224759001, 'dropout_rate': 0.18470289302046516, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.022476866600004634, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 3.745982455886227e-06, 'validation_fraction': 0.9275220875852723, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:58:55,815] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9899309662352432, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 11:59:25,699] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9658825052862857, 'learning_rate': 0.010845363858236992, 'dropout_rate': 0.13571080979315037, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.3681339382709387, 'min_weight_fraction_leaf': 0.15534331606940482, 'max_features': 'log2', 'min_impurity_decrease': 8.60046486145071e-06, 'validation_fraction': 0.9205869937759958, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21299720012323184
Fold 2 IBS: 0.21967979851217223
Fold 3 IBS: 0.2038040121811597
Fold 4 IBS: 0.2242157275656328
Fold 5 IBS: 0.21668589828394494
[I 2024-04-16 12:00:02,033] Trial 65 finished with value: 0.21547652733322833 and parameters: {'subsample': 0.9661607708539444, 'learning_rate': 0.008868026173365113, 'dropout_rate': 0.17835638219464384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.002725826040487267, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:00:30,741] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9998769833869746, 'learning_rate': 0.003967598379054899, 'dropout_rate': 0.17654958266634313, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.8981368148483696, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'auto', 'min_impurity_decrease': 7.140027633149786e-05, 'validation_fraction': 0.6362228335648394, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 12:00:55,464] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8945386029541793, 'learning_rate': 0.01494075298406419, 'dropout_rate': 0.209071801122636, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1837261226658302, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5552258602982892e-05, 'validation_fraction': 0.7259068897097584, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-16 12:01:37,355] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.843502945752621, 'learning_rate': 0.02075147594960792, 'dropout_rate': 0.16252263519114862, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.057901034918407895, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.6846740503948187, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:02:05,921] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.01037165919107231, 'dropout_rate': 0.19004731427008625, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.34303232955200197, 'min_weight_fraction_leaf': 0.3579731281150166, 'max_features': 'auto', 'min_impurity_decrease': 0.00014344627836102727, 'validation_fraction': 0.7769648880006281, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 12:02:44,645] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6499145948799803, 'learning_rate': 0.008667614598934925, 'dropout_rate': 0.2379061541841675, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.6762661413605899, 'min_weight_fraction_leaf': 0.2053436289550881, 'max_features': None, 'min_impurity_decrease': 2.7112245092072337e-05, 'validation_fraction': 0.5272974695233066, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.21365420908986738
Fold 2 IBS: 0.2209721070161024
Fold 3 IBS: 0.2043021502572646
Fold 4 IBS: 0.22456249898531583
Fold 5 IBS: 0.2176782657279134
[I 2024-04-16 12:03:25,448] Trial 71 finished with value: 0.21623384621529276 and parameters: {'subsample': 0.9554665295189709, 'learning_rate': 0.004772306432110387, 'dropout_rate': 0.30773217080297294, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.019537053946387287, 'max_features': 'auto', 'min_impurity_decrease': 3.603782675882374e-06, 'validation_fraction': 0.8818766703918308, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 62 with value: 0.21546146572568672.
Fold 1 IBS: 0.2103768252217124
Fold 2 IBS: 0.21850284034383607
Fold 3 IBS: 0.20294546345453016
Fold 4 IBS: 0.22323961452248642
Fold 5 IBS: 0.2153595452182885
[I 2024-04-16 12:04:04,693] Trial 72 finished with value: 0.2140848577521707 and parameters: {'subsample': 0.9233416329717381, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.12211037740366137, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004815836437462028, 'min_weight_fraction_leaf': 0.2452551786385524, 'max_features': 'auto', 'min_impurity_decrease': 1.5300590715832769e-06, 'validation_fraction': 0.974284387349558, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.2140848577521707.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:04:12,836] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.916509573532907, 'learning_rate': 0.01366625897147706, 'dropout_rate': 0.10211108319082117, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.35137810274202946, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'auto', 'min_impurity_decrease': 5.253021283264037e-07, 'validation_fraction': 0.9862680394354211, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 72 with value: 0.2140848577521707.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:04:46,254] Trial 74 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.98093897605085, 'learning_rate': 0.01711555655405715, 'dropout_rate': 0.13243922080536136, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.7083433911466146, 'min_weight_fraction_leaf': 0.24361782259873882, 'max_features': 'auto', 'min_impurity_decrease': 1.0928587879200682e-06, 'validation_fraction': 0.8125486143795312, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 72 with value: 0.2140848577521707.
Fold 1 IBS: 0.20177055563075577
Fold 2 IBS: 0.209535009765422
Fold 3 IBS: 0.196660791504323
Fold 4 IBS: 0.21686059369436475
Fold 5 IBS: 0.20762944158941038
[I 2024-04-16 12:05:14,630] Trial 75 finished with value: 0.2064912784368552 and parameters: {'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 12:05:39,812] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8788463737285552, 'learning_rate': 0.0916936247639216, 'dropout_rate': 0.16070017323462005, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.32254979446846543, 'max_features': 'auto', 'min_impurity_decrease': 1.6370541352867706e-06, 'validation_fraction': 0.7514206020918085, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268

Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 12:06:01,516] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9277566139958084, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.19520203577374073, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.27180012569333806, 'max_features': 1, 'min_impurity_decrease': 6.5181445049333515e-06, 'validation_fraction': 0.6076036057733984, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 12:06:20,842] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9641397901643791, 'learning_rate': 0.08426314282635561, 'dropout_rate': 0.1247743198402547, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 0.30089158245836867, 'min_weight_fraction_leaf': 0.28488038648314357, 'max_features': 'auto', 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.6689444692488747, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:06:41,780] Trial 79 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9058167204807939, 'learning_rate': 0.07449175092046981, 'dropout_rate': 0.2195581561902862, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 0.5632393945180738, 'min_weight_fraction_leaf': 0.3103740193108716, 'max_features': 0.1, 'min_impurity_decrease': 9.7137748926677e-06, 'validation_fraction': 0.849557227325558, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 12:07:05,421] Trial 80 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04033855340571721, 'dropout_rate': 0.17133798886674423, 'n_estimators': 423, 'criterion': 'friedman_mse', 'ccp_alpha': 1.024900175040304, 'min_weight_fraction_leaf': 0.2650334083023682, 'max_features': 'auto', 'min_impurity_decrease': 5.230611844746115e-06, 'validation_fraction': 0.7958053728402417, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.213006975409325
Fold 2 IBS: 0.22058981150149234
Fold 3 IBS: 0.2038292466524223
Fold 4 IBS: 0.2241672122172358
Fold 5 IBS: 0.2173545648278883
[I 2024-04-16 12:07:39,065] Trial 81 finished with value: 0.21578956212167277 and parameters: {'subsample': 0.7840956251329788, 'learning_rate': 0.008693963960519305, 'dropout_rate': 0.24759233856802285, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2888444623370858, 'max_features': 'auto', 'min_impurity_decrease': 1.9009142355302227e-06, 'validation_fraction': 0.9214054941984873, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:08:21,689] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8257398205366486, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.1461667964581519, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.1946035339480217, 'max_features': 'auto', 'min_impurity_decrease': 2.6687516010357667e-06, 'validation_fraction': 0.8952878298653584, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 12:08:44,688] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.981472556868282, 'learning_rate': 0.0030220411792046976, 'dropout_rate': 0.1911593145934642, 'n_estimators': 375, 'criterion': 'squared_error', 'ccp_alpha': 0.8179280838957377, 'min_weight_fraction_leaf': 0.48985212977722026, 'max_features': 'auto', 'min_impurity_decrease': 3.455195546201241e-05, 'validation_fraction': 0.938557669326888, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:09:10,252] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8647540438080621, 'learning_rate': 0.08343776887241991, 'dropout_rate': 0.22709419020503996, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5507721391645963, 'min_weight_fraction_leaf': 0.24659978585785525, 'max_features': 'log2', 'min_impurity_decrease': 1.5548907893179703e-07, 'validation_fraction': 0.979412404338395, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:09:51,982] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7329827146706644, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.10328003473955753, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2872262650985504, 'min_weight_fraction_leaf': 0.2118047441439845, 'max_features': 'auto', 'min_impurity_decrease': 7.161280890174719e-07, 'validation_fraction': 0.8326344162343784, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:10:20,480] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.968028637803562, 'learning_rate': 0.012332676724282343, 'dropout_rate': 0.3116356702759888, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.20691530526186325, 'min_weight_fraction_leaf': 0.17880882745231644, 'max_features': 'sqrt', 'min_impurity_decrease': 4.559575312773901e-06, 'validation_fraction': 0.5736364556858768, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:11:04,324] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.586845457594135, 'learning_rate': 0.015087793813163719, 'dropout_rate': 0.1289037142883289, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 1.7523211277779085, 'min_weight_fraction_leaf': 0.1388142878843003, 'max_features': 'auto', 'min_impurity_decrease': 3.1579639125192316e-07, 'validation_fraction': 0.9007381558442704, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 9}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:11:30,271] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9384285478087404, 'learning_rate': 0.008432408233149245, 'dropout_rate': 0.2555430411709441, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 0.5917857287890423, 'min_weight_fraction_leaf': 0.30147465751502, 'max_features': 'auto', 'min_impurity_decrease': 1.3322358120453633e-06, 'validation_fraction': 0.7530800224575359, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:12:09,610] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8566436667378682, 'learning_rate': 0.01150450588881658, 'dropout_rate': 0.1670492025845379, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.16544408115726048, 'max_features': 'auto', 'min_impurity_decrease': 1.2718861827092477e-05, 'validation_fraction': 0.999916960516484, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 12:12:31,973] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9108486830124928, 'learning_rate': 0.07073008964456817, 'dropout_rate': 0.2036613424933201, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.12697803926229267, 'max_features': None, 'min_impurity_decrease': 8.395207931535954e-05, 'validation_fraction': 0.8697930286831252, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21298041191430933
Fold 2 IBS: 0.22048509717101197
Fold 3 IBS: 0.2037935347009234
Fold 4 IBS: 0.22416608987358
Fold 5 IBS: 0.21726205535451415
[I 2024-04-16 12:13:11,593] Trial 91 finished with value: 0.21573743780286775 and parameters: {'subsample': 0.7918122624467706, 'learning_rate': 0.008764883268716819, 'dropout_rate': 0.23147171525582408, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.28864883630713, 'max_features': 'auto', 'min_impurity_decrease': 2.433769869200532e-06, 'validation_fraction': 0.9330807112636796, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21273002612666614
Fold 2 IBS: 0.22020162175537994
Fold 3 IBS: 0.20375739205646468
Fold 4 IBS: 0.22398391162161366
Fold 5 IBS: 0.21696727449411685
[I 2024-04-16 12:13:55,461] Trial 92 finished with value: 0.21552804521084826 and parameters: {'subsample': 0.7970612869259553, 'learning_rate': 0.006846874820718422, 'dropout_rate': 0.14896704674181122, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.048376779302453654, 'min_weight_fraction_leaf': 0.2632936345144107, 'max_features': 'auto', 'min_impurity_decrease': 2.1668791988162493e-06, 'validation_fraction': 0.962264255678676, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 12:14:43,031] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8863794702939648, 'learning_rate': 0.005644515103436926, 'dropout_rate': 0.1511320088851303, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.8672812842462059, 'min_weight_fraction_leaf': 0.2631664572752167, 'max_features': 'auto', 'min_impurity_decrease': 9.594887622043012e-07, 'validation_fraction': 0.9597976992445604, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:15:20,137] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7555668093579782, 'learning_rate': 0.003024128821367058, 'dropout_rate': 0.18020067991764227, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.5370821041135924, 'min_weight_fraction_leaf': 0.3269802231121252, 'max_features': 'auto', 'min_impurity_decrease': 5.453652008067023e-07, 'validation_fraction': 0.9064168309630759, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:15:55,319] Trial 95 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8285555969881634, 'learning_rate': 0.0011500826880246348, 'dropout_rate': 0.1263312272620864, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.0677877027733826, 'min_weight_fraction_leaf': 0.23754287719496792, 'max_features': 'auto', 'min_impurity_decrease': 1.5717571529922772e-06, 'validation_fraction': 0.9416814543721681, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:16:35,417] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7078782825524117, 'learning_rate': 0.024032062736360556, 'dropout_rate': 0.21333201870671714, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.23399465857880092, 'min_weight_fraction_leaf': 0.2509877726726459, 'max_features': 'auto', 'min_impurity_decrease': 4.132954919887874e-06, 'validation_fraction': 0.966821915092678, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 12:23:43,069] Trial 97 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9362560013369767, 'learning_rate': 0.0062939849492930095, 'dropout_rate': 0.25430805534041345, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.20566514949538883, 'min_weight_fraction_leaf': 0.2189843961179572, 'max_features': 1, 'min_impurity_decrease': 8.03183490237945e-06, 'validation_fraction': 0.8835944049341534, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 12:25:08,814] Trial 98 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.979668618259463, 'learning_rate': 0.016116253930051894, 'dropout_rate': 0.15171316016644432, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 0.526527014614438, 'min_weight_fraction_leaf': 0.27830242472777905, 'max_features': 'auto', 'min_impurity_decrease': 2.2015056170379928e-06, 'validation_fraction': 0.8376875978231397, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 75 with value: 0.2064912784368552.
Fold 1 IBS: 0.21217724232754462
Fold 2 IBS: 0.21947402353962686
Fold 3 IBS: 0.2021045597995369
Fold 4 IBS: 0.22160198829426855

Fold 5 IBS: 0.2170864632573697
[I 2024-04-16 12:25:40,404] Trial 99 finished with value: 0.21448885544366933 and parameters: {'subsample': 0.8012390519326651, 'learning_rate': 0.05269659590897164, 'dropout_rate': 0.27553624278288036, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 0.004383883527848379, 'min_weight_fraction_leaf': 0.353628504086837, 'max_features': 0.1, 'min_impurity_decrease': 8.641052711851521e-07, 'validation_fraction': 0.6285370472109972, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.2064912784368552.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.2064912784368552], datetime_start=datetime.datetime(2024, 4, 16, 12, 4, 46, 256407), datetime_complete=datetime.datetime(2024, 4, 16, 12, 5, 14, 629775), params={'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.2064912784368552

In [92]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [93]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.74
train_ibs:  0.206

#### Test

In [94]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [95]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.058133567268478875,
                                 criterion='squared_error',
                                 dropout_rate=0.2527776031497929,
                                 learning_rate=0.0012227187192111223,
                                 max_depth=1, max_features='auto',
                                 max_leaf_nodes=20,
                                 min_impurity_decrease=1.5094636128058346e-06,
                                 min_samples_leaf=15, min_samples_split=20,
                                 min_weight_fraction_leaf=0.2151989029549357,
                                 n_estimators=489, random_state=123,
                                 subsample=0.873850481285158,
                                 validation_fraction=0.9945176333416724)

C-index score: 0.618

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008810810992982535,
                                 criterion='squared_error',
                                 dropout_rate=0.1693875032679634,
                                 learning_rate=0.08843409287484169,
                                 max_features='auto', max_leaf_nodes=15,
                                 min_impurity_decrease=5.157320437854681e-06,
                                 min_samples_leaf=16, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29044798941528627,
                                 n_estimators=403, random_state=123,
                                 subsample=0.8646743646205938,
                                 validation_fraction=0.7489142536117352)

IBS: 0.215

In [96]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [97]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [98]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 12:26:20,799] A new study created in memory with name: no-name-08374a21-617b-4f92-a4ff-c5835938cf01

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:26:23,111] Trial 0 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:26:41,631] Trial 1 finished with value: 0.6915224372703425 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:26:46,660] Trial 2 finished with value: 0.6951295602764356 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6951295602764356.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:26:52,106] Trial 3 finished with value: 0.700470556988902 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:27:15,508] Trial 4 finished with value: 0.6985655664395451 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:27:36,527] Trial 5 finished with value: 0.6866204764860286 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:27:40,372] Trial 6 finished with value: 0.689561652956617 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:27:41,361] Trial 7 finished with value: 0.6970759758465048 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:28:08,651] Trial 8 finished with value: 0.6924614044064927 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:37:25,532] Trial 9 finished with value: 0.6952660705767583 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 3 with value: 0.700470556988902.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 12:37:36,484] Trial 10 finished with value: 0.7005703272410927 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.10867980814121556, 'n_estimators': 299, 'learning_rate': 0.09279671898160717}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 12:37:45,973] Trial 11 finished with value: 0.6969556539693951 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.10580803679784617, 'n_estimators': 318, 'learning_rate': 0.09656492760401554}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 12:37:55,555] Trial 12 finished with value: 0.6996774700982356 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.107083606486404, 'n_estimators': 371, 'learning_rate': 0.09210877537520011}. Best is trial 10 with value: 0.7005703272410927.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:38:03,240] Trial 13 finished with value: 0.701141050027687 and parameters: {'subsample': 0.19911958285971598, 'dropout_rate': 0.20951790452982805, 'n_estimators': 296, 'learning_rate': 0.08223799235112043}. Best is trial 13 with value: 0.701141050027687.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:38:12,806] Trial 14 finished with value: 0.7072701373860618 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24580479907647002, 'n_estimators': 309, 'learning_rate': 0.0025916531369806137}. Best is trial 14 with value: 0.7072701373860618.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 12:38:22,195] Trial 15 finished with value: 0.7071018858361023 and parameters: {'subsample': 0.10123497548852628, 'dropout_rate': 0.27285675886808575, 'n_estimators': 344, 'learning_rate': 0.01041399690405663}. Best is trial 14 with value: 0.7072701373860618.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 12:38:33,812] Trial 16 finished with value: 0.706194659949589 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.3009523413407027, 'n_estimators': 414, 'learning_rate': 0.0015978420809887592}. Best is trial 14 with value: 0.7072701373860618.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:38:47,174] Trial 17 finished with value: 0.7037435898928852 and parameters: {'subsample': 0.1398243358756775, 'dropout_rate': 0.7574099126710454, 'n_estimators': 408, 'learning_rate': 0.0036941896820761443}. Best is trial 14 with value: 0.7072701373860618.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:38:57,590] Trial 18 finished with value: 0.6970345508257922 and parameters: {'subsample': 0.32815271570962645, 'dropout_rate': 0.5881159084793368, 'n_estimators': 345, 'learning_rate': 0.0160150740748417}. Best is trial 14 with value: 0.7072701373860618.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:39:12,350] Trial 19 finished with value: 0.6978167698626153 and parameters: {'subsample': 0.2202898915217226, 'dropout_rate': 0.3156718779160812, 'n_estimators': 431, 'learning_rate': 0.01563167261765183}. Best is trial 14 with value: 0.7072701373860618.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:39:20,593] Trial 20 finished with value: 0.6988588248391951 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.22438470567364258, 'n_estimators': 245, 'learning_rate': 0.03827516477850919}. Best is trial 14 with value: 0.7072701373860618.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:39:35,558] Trial 21 finished with value: 0.7100870387945125 and parameters: {'subsample': 0.11014863416226671, 'dropout_rate': 0.3058920522870888, 'n_estimators': 410, 'learning_rate': 0.0016108337344105245}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:39:50,610] Trial 22 finished with value: 0.7071336270857392 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.4009997446986495, 'n_estimators': 446, 'learning_rate': 0.010728356021136429}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:40:05,941] Trial 23 finished with value: 0.7012142162980364 and parameters: {'subsample': 0.1850567218204376, 'dropout_rate': 0.4352461825666898, 'n_estimators': 452, 'learning_rate': 0.024115197614724897}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:40:24,727] Trial 24 finished with value: 0.6996975694279397 and parameters: {'subsample': 0.27607637066649166, 'dropout_rate': 0.3843531704773764, 'n_estimators': 397, 'learning_rate': 0.009330118660635838}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:40:49,040] Trial 25 finished with value: 0.7029019800111166 and parameters: {'subsample': 0.165350832395609, 'dropout_rate': 0.528565711666221, 'n_estimators': 495, 'learning_rate': 0.02082938874638609}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:41:04,892] Trial 26 finished with value: 0.6978784326823324 and parameters: {'subsample': 0.2958189169734158, 'dropout_rate': 0.19070894585460196, 'n_estimators': 451, 'learning_rate': 0.006989047841911983}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:41:17,129] Trial 27 finished with value: 0.6979417767123057 and parameters: {'subsample': 0.41837107426637904, 'dropout_rate': 0.6340112818214192, 'n_estimators': 385, 'learning_rate': 0.030307532796347948}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:41:26,915] Trial 28 finished with value: 0.7004435007118457 and parameters: {'subsample': 0.23402725659148405, 'dropout_rate': 0.3392114399479871, 'n_estimators': 326, 'learning_rate': 0.0012105719755584748}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:41:30,612] Trial 29 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.4175950896276197, 'n_estimators': 136, 'learning_rate': 0.012766362768081544}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:41:38,740] Trial 30 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.6503422690541019, 'dropout_rate': 0.3538766187028065, 'n_estimators': 261, 'learning_rate': 0.03500526163856756}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:41:50,636] Trial 31 finished with value: 0.7072701373860618 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.273733363160737, 'n_estimators': 348, 'learning_rate': 0.010495499913599278}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:42:04,693] Trial 32 finished with value: 0.7028507327500281 and parameters: {'subsample': 0.1553995948714062, 'dropout_rate': 0.26346465887556664, 'n_estimators': 434, 'learning_rate': 0.018578545016073353}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 12:42:17,396] Trial 33 finished with value: 0.7071750521064517 and parameters: {'subsample': 0.10123848117934434, 'dropout_rate': 0.48095898939081394, 'n_estimators': 363, 'learning_rate': 0.008390503824508122}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:42:27,018] Trial 34 finished with value: 0.7012902478614097 and parameters: {'subsample': 0.23055604612336722, 'dropout_rate': 0.4965220627116055, 'n_estimators': 284, 'learning_rate': 0.00525028800731036}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:42:38,493] Trial 35 finished with value: 0.7072309843401209 and parameters: {'subsample': 0.166546907208094, 'dropout_rate': 0.1867523943429737, 'n_estimators': 350, 'learning_rate': 0.02878182268086671}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:42:45,889] Trial 36 finished with value: 0.7063409924902878 and parameters: {'subsample': 0.17126329995999146, 'dropout_rate': 0.16827279756671865, 'n_estimators': 231, 'learning_rate': 0.04201048654688215}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 12:42:57,999] Trial 37 finished with value: 0.6997977919753454 and parameters: {'subsample': 0.3159033114532558, 'dropout_rate': 0.23444389314452685, 'n_estimators': 323, 'learning_rate': 0.026060007154574648}. Best is trial 21 with value: 0.7100870387945125.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:42:59,553] Trial 38 finished with value: 0.6995315898527518 and parameters: {'subsample': 0.23557094034920928, 'dropout_rate': 0.1525802414016249, 'n_estimators': 46, 'learning_rate': 0.06267653306005645}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:43:18,500] Trial 39 finished with value: 0.6960685274125858 and parameters: {'subsample': 0.4137092791396724, 'dropout_rate': 0.29699687311164197, 'n_estimators': 384, 'learning_rate': 0.01715036845928685}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:43:36,713] Trial 40 finished with value: 0.6952246455560458 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.1585668555692103, 'n_estimators': 280, 'learning_rate': 0.027917659768795684}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:44:00,890] Trial 41 finished with value: 0.7028726517592888 and parameters: {'subsample': 0.13882130076067578, 'dropout_rate': 0.4666143370948693, 'n_estimators': 356, 'learning_rate': 0.007601581274038189}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:44:25,439] Trial 42 finished with value: 0.7029677370388989 and parameters: {'subsample': 0.137045724868691, 'dropout_rate': 0.9772717282714597, 'n_estimators': 365, 'learning_rate': 0.012298149008811715}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:44:45,874] Trial 43 finished with value: 0.7012361353072973 and parameters: {'subsample': 0.19643844105523972, 'dropout_rate': 0.2468795347856033, 'n_estimators': 316, 'learning_rate': 0.020893711848536962}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:44:46,374] Trial 44 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.25912417313193603, 'dropout_rate': 0.7514358707131008, 'n_estimators': 3, 'learning_rate': 0.005551409390444416}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 12:45:08,153] Trial 45 finished with value: 0.7062360849703015 and parameters: {'subsample': 0.10617537873643577, 'dropout_rate': 0.3375758390878158, 'n_estimators': 338, 'learning_rate': 0.014042886131651092}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:45:31,828] Trial 46 finished with value: 0.7020580981545765 and parameters: {'subsample': 0.18433946211134455, 'dropout_rate': 0.28463990771133574, 'n_estimators': 301, 'learning_rate': 0.021055784114094193}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:45:57,751] Trial 47 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.3835832180379174, 'n_estimators': 377, 'learning_rate': 0.007489775341203839}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:46:31,426] Trial 48 finished with value: 0.7045362244883366 and parameters: {'subsample': 0.13755875964894368, 'dropout_rate': 0.19701471782839963, 'n_estimators': 414, 'learning_rate': 0.04612781817326261}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:47:11,949] Trial 49 finished with value: 0.6970759758465048 and parameters: {'subsample': 0.3519083882463058, 'dropout_rate': 0.1364983591710222, 'n_estimators': 476, 'learning_rate': 0.0016753811606543417}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:47:48,532] Trial 50 finished with value: 0.7012488228406972 and parameters: {'subsample': 0.27903432170530373, 'dropout_rate': 0.1998070691532423, 'n_estimators': 393, 'learning_rate': 0.03263281538320787}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:48:28,997] Trial 51 finished with value: 0.708114019242602 and parameters: {'subsample': 0.10877157891355023, 'dropout_rate': 0.39887916424524683, 'n_estimators': 424, 'learning_rate': 0.011119196763412748}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:48:58,544] Trial 52 finished with value: 0.7065431187953554 and parameters: {'subsample': 0.12801991613896832, 'dropout_rate': 0.4799607726405747, 'n_estimators': 354, 'learning_rate': 0.010971278376071565}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:49:51,198] Trial 53 finished with value: 0.7013093015776465 and parameters: {'subsample': 0.18894203617812574, 'dropout_rate': 0.324035621687082, 'n_estimators': 424, 'learning_rate': 0.00444224235677061}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:50:40,808] Trial 54 finished with value: 0.699431367305346 and parameters: {'subsample': 0.20463848930825373, 'dropout_rate': 0.5196225462094849, 'n_estimators': 471, 'learning_rate': 0.016252521692896472}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:51:15,040] Trial 55 finished with value: 0.7071336270857392 and parameters: {'subsample': 0.10764307884729801, 'dropout_rate': 0.43628782234969476, 'n_estimators': 407, 'learning_rate': 0.00903271655406296}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:51:37,421] Trial 56 finished with value: 0.7020800171638373 and parameters: {'subsample': 0.16248542694762952, 'dropout_rate': 0.3734476483005279, 'n_estimators': 307, 'learning_rate': 0.0010087867855488077}. Best is trial 21 with value: 0.7100870387945125.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 12:52:03,378] Trial 57 finished with value: 0.7071260768201346 and parameters: {'subsample': 0.10157248860328094, 'dropout_rate': 0.26195319213881374, 'n_estimators': 337, 'learning_rate': 0.07586937026396535}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:52:34,057] Trial 58 finished with value: 0.6959515231237148 and parameters: {'subsample': 0.24497318175810665, 'dropout_rate': 0.5803264623491258, 'n_estimators': 376, 'learning_rate': 0.022725264660662742}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:52:57,080] Trial 59 finished with value: 0.70380920589763 and parameters: {'subsample': 0.15604621069028282, 'dropout_rate': 0.2943520998832086, 'n_estimators': 285, 'learning_rate': 0.014573073816105708}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:53:11,833] Trial 60 finished with value: 0.7003512807252594 and parameters: {'subsample': 0.2041420856999968, 'dropout_rate': 0.3561994922664912, 'n_estimators': 198, 'learning_rate': 0.018503299313181485}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:53:49,575] Trial 61 finished with value: 0.7081676795014996 and parameters: {'subsample': 0.12568959635007076, 'dropout_rate': 0.4119916213634749, 'n_estimators': 449, 'learning_rate': 0.011424895016868915}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:54:31,888] Trial 62 finished with value: 0.7063922397513763 and parameters: {'subsample': 0.13631626396695795, 'dropout_rate': 0.40854586425118766, 'n_estimators': 471, 'learning_rate': 0.004761399604301435}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:55:03,342] Trial 63 finished with value: 0.7064555837813498 and parameters: {'subsample': 0.13048439281811408, 'dropout_rate': 0.45609437436079164, 'n_estimators': 441, 'learning_rate': 0.009797064864380828}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:55:34,912] Trial 64 finished with value: 0.7028726517592888 and parameters: {'subsample': 0.15845931066299146, 'dropout_rate': 0.227816901916626, 'n_estimators': 406, 'learning_rate': 0.05654920167755849}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:56:22,182] Trial 65 finished with value: 0.7004654197211064 and parameters: {'subsample': 0.21453523740554384, 'dropout_rate': 0.3141296249005915, 'n_estimators': 423, 'learning_rate': 0.01360001182412449}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:57:04,386] Trial 66 finished with value: 0.7071336270857392 and parameters: {'subsample': 0.10044174310716016, 'dropout_rate': 0.42103966430590295, 'n_estimators': 459, 'learning_rate': 0.025218009062488424}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 12:57:30,112] Trial 67 finished with value: 0.7021531834341866 and parameters: {'subsample': 0.1714740427527781, 'dropout_rate': 0.5577136994917086, 'n_estimators': 363, 'learning_rate': 0.004327703540213826}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:57:57,530] Trial 68 finished with value: 0.7080725942218894 and parameters: {'subsample': 0.1248153576359606, 'dropout_rate': 0.49263709885384904, 'n_estimators': 393, 'learning_rate': 0.00782692097727565}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 12:58:34,642] Trial 69 finished with value: 0.6951537512604677 and parameters: {'subsample': 0.26399987010283776, 'dropout_rate': 0.6244059966054039, 'n_estimators': 401, 'learning_rate': 0.028690505713963668}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 12:59:08,035] Trial 70 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.5622516492989015, 'dropout_rate': 0.1806794570956778, 'n_estimators': 435, 'learning_rate': 0.011721905432308785}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 12:59:41,863] Trial 71 finished with value: 0.7082091045222121 and parameters: {'subsample': 0.11693245217372568, 'dropout_rate': 0.4955874475011776, 'n_estimators': 392, 'learning_rate': 0.007078793620571429}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:00:08,740] Trial 72 finished with value: 0.7055483578948363 and parameters: {'subsample': 0.13409084738145716, 'dropout_rate': 0.5106014997450612, 'n_estimators': 391, 'learning_rate': 0.003088313752790504}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:00:36,163] Trial 73 finished with value: 0.7002752491618862 and parameters: {'subsample': 0.17661618844868837, 'dropout_rate': 0.44466617716565454, 'n_estimators': 332, 'learning_rate': 0.006675954446929436}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:01:13,808] Trial 74 finished with value: 0.704609390758686 and parameters: {'subsample': 0.12456980827695728, 'dropout_rate': 0.5482170244721637, 'n_estimators': 492, 'learning_rate': 0.018026788082895637}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:01:41,079] Trial 75 finished with value: 0.7037165336158289 and parameters: {'subsample': 0.15182770206700677, 'dropout_rate': 0.1329168580577978, 'n_estimators': 348, 'learning_rate': 0.010416339338419834}. Best is trial 21 with value: 0.7100870387945125.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:02:16,798] Trial 76 finished with value: 0.6978167698626153 and parameters: {'subsample': 0.20726572604578375, 'dropout_rate': 0.36621100369842535, 'n_estimators': 416, 'learning_rate': 0.007559534583851789}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:02:50,564] Trial 77 finished with value: 0.6986606517191555 and parameters: {'subsample': 0.2249541411816587, 'dropout_rate': 0.2669960943752657, 'n_estimators': 457, 'learning_rate': 0.015051564043857246}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 13:03:15,718] Trial 78 finished with value: 0.698014942982655 and parameters: {'subsample': 0.29793318031156685, 'dropout_rate': 0.40024678599927327, 'n_estimators': 376, 'learning_rate': 0.0033618884711360073}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:03:37,428] Trial 79 finished with value: 0.7037384526250896 and parameters: {'subsample': 0.11988377215157917, 'dropout_rate': 0.21551479240268345, 'n_estimators': 314, 'learning_rate': 0.036705780296877884}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 13:04:02,428] Trial 80 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.4684093524980193, 'dropout_rate': 0.4957628239134494, 'n_estimators': 392, 'learning_rate': 0.012742836642978853}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:04:27,582] Trial 81 finished with value: 0.699431367305346 and parameters: {'subsample': 0.17816262372506345, 'dropout_rate': 0.4585181807773151, 'n_estimators': 364, 'learning_rate': 0.008358831255867567}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:04:49,748] Trial 82 finished with value: 0.702099523175289 and parameters: {'subsample': 0.15229753238646737, 'dropout_rate': 0.33087360070318905, 'n_estimators': 349, 'learning_rate': 0.006471087864775283}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:05:09,986] Trial 83 finished with value: 0.7072287123653493 and parameters: {'subsample': 0.11715812832028902, 'dropout_rate': 0.4819386703063981, 'n_estimators': 386, 'learning_rate': 0.020323922872501787}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:05:36,051] Trial 84 finished with value: 0.7073237976449595 and parameters: {'subsample': 0.12341768738919337, 'dropout_rate': 0.2463277881377591, 'n_estimators': 421, 'learning_rate': 0.02075669374114978}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:05:59,360] Trial 85 finished with value: 0.7029238990203774 and parameters: {'subsample': 0.18689957642309896, 'dropout_rate': 0.23298373731436203, 'n_estimators': 428, 'learning_rate': 0.02291844348512984}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 13:06:25,252] Trial 86 finished with value: 0.7029140767800013 and parameters: {'subsample': 0.14442758139811304, 'dropout_rate': 0.2504374407155566, 'n_estimators': 449, 'learning_rate': 0.011713412311550285}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:06:47,535] Trial 87 finished with value: 0.7037384526250896 and parameters: {'subsample': 0.12302002892254844, 'dropout_rate': 0.17971650523934474, 'n_estimators': 418, 'learning_rate': 0.016347157088937168}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 13:07:14,878] Trial 88 finished with value: 0.689561652956617 and parameters: {'subsample': 0.6350482367083102, 'dropout_rate': 0.28148319265496974, 'n_estimators': 484, 'learning_rate': 0.0013418198212998013}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 13:07:37,785] Trial 89 finished with value: 0.7005414512844798 and parameters: {'subsample': 0.2476304184508672, 'dropout_rate': 0.3884510928888704, 'n_estimators': 403, 'learning_rate': 0.018894919673559614}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 13:07:51,987] Trial 90 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.7147405584008215, 'dropout_rate': 0.35133452467973236, 'n_estimators': 266, 'learning_rate': 0.005681106775735836}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:08:12,578] Trial 91 finished with value: 0.7090334803673005 and parameters: {'subsample': 0.11934031514956886, 'dropout_rate': 0.4246135093679103, 'n_estimators': 383, 'learning_rate': 0.027109204190921873}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:08:37,718] Trial 92 finished with value: 0.7020800171638373 and parameters: {'subsample': 0.16916966958183466, 'dropout_rate': 0.4126642645305066, 'n_estimators': 439, 'learning_rate': 0.026307523650715238}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 13:08:58,071] Trial 93 finished with value: 0.707038541806129 and parameters: {'subsample': 0.10126464195698669, 'dropout_rate': 0.316091835206065, 'n_estimators': 380, 'learning_rate': 0.04039873958278781}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:09:18,915] Trial 94 finished with value: 0.7072287123653493 and parameters: {'subsample': 0.12341005773373076, 'dropout_rate': 0.42561697837730134, 'n_estimators': 371, 'learning_rate': 0.010093877759800782}. Best is trial 21 with value: 0.7100870387945125.

Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:09:36,870] Trial 95 finished with value: 0.7002481928848299 and parameters: {'subsample': 0.1533051032069533, 'dropout_rate': 0.5282758365517621, 'n_estimators': 327, 'learning_rate': 0.0334083503330145}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:10:03,192] Trial 96 finished with value: 0.7055483578948363 and parameters: {'subsample': 0.19501923530867007, 'dropout_rate': 0.29915837260684836, 'n_estimators': 461, 'learning_rate': 0.08791879465920027}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 13:10:25,624] Trial 97 finished with value: 0.7064141587606372 and parameters: {'subsample': 0.14462710914276247, 'dropout_rate': 0.1437665485108484, 'n_estimators': 394, 'learning_rate': 0.027974877305327436}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 13:10:32,742] Trial 98 finished with value: 0.7082091045222121 and parameters: {'subsample': 0.12022571472892578, 'dropout_rate': 0.12022507807312265, 'n_estimators': 139, 'learning_rate': 0.013649872339230127}. Best is trial 21 with value: 0.7100870387945125.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663

[I 2024-04-16 13:10:39,209] A new study created in memory with name: no-name-34dbfcce-f367-4757-9dfa-80494cfb849d

Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 13:10:39,150] Trial 99 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.5779843006160138, 'n_estimators': 139, 'learning_rate': 0.014233222481951812}. Best is trial 21 with value: 0.7100870387945125.


* Best trial for C-index:
 FrozenTrial(number=21, state=TrialState.COMPLETE, values=[0.7100870387945125], datetime_start=datetime.datetime(2024, 4, 16, 12, 39, 20, 598227), datetime_complete=datetime.datetime(2024, 4, 16, 12, 39, 35, 556371), params={'subsample': 0.11014863416226671, 'dropout_rate': 0.3058920522870888, 'n_estimators': 410, 'learning_rate': 0.0016108337344105245}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=21, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11014863416226671, 'dropout_rate': 0.3058920522870888, 'n_estimators': 410, 'learning_rate': 0.0016108337344105245}


* Best Score for C-index:
 0.7100870387945125

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24692977896599883
Fold 2 IBS: 0.23367124240111953
Fold 3 IBS: 0.18592983540335206
Fold 4 IBS: 0.2632765971484762
Fold 5 IBS: 0.2101930209796324
[I 2024-04-16 13:10:45,549] Trial 0 finished with value: 0.2280000949797158 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.3168791384838904
Fold 2 IBS: 0.3218948725307976
Fold 3 IBS: 0.27592959166775866
Fold 4 IBS: 0.315408539471182
Fold 5 IBS: 0.30438829249434424
[I 2024-04-16 13:11:13,463] Trial 1 finished with value: 0.3069000869295946 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2753019447545149
Fold 2 IBS: 0.2982356241179488
Fold 3 IBS: 0.23068334408596278
Fold 4 IBS: 0.27397829249360633
Fold 5 IBS: 0.25684924696430295
[I 2024-04-16 13:11:22,721] Trial 2 finished with value: 0.26700969048326717 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2786819074278709
Fold 2 IBS: 0.2600472138747981
Fold 3 IBS: 0.23882358787102978
Fold 4 IBS: 0.2592722986281111
Fold 5 IBS: 0.2182835718315773
[I 2024-04-16 13:11:34,169] Trial 3 finished with value: 0.2510217159266774 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2789680361121065
Fold 2 IBS: 0.28471090270389776
Fold 3 IBS: 0.23948666083462447
Fold 4 IBS: 0.2562837019187784
Fold 5 IBS: 0.2273619565211416
[I 2024-04-16 13:11:48,274] Trial 4 finished with value: 0.2573622516181097 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.30156654310213465
Fold 2 IBS: 0.3204353433554115
Fold 3 IBS: 0.2623263101041928
Fold 4 IBS: 0.3038662427158054
Fold 5 IBS: 0.2972845037916553
[I 2024-04-16 13:12:06,402] Trial 5 finished with value: 0.29709578861383995 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.23284347689671558
Fold 2 IBS: 0.202874467602479
Fold 3 IBS: 0.17322347591450493
Fold 4 IBS: 0.24151316943928927
Fold 5 IBS: 0.1909058630290115
[I 2024-04-16 13:12:15,676] Trial 6 finished with value: 0.20827209057640003 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20827209057640003.
Fold 1 IBS: 0.20841359719195401
Fold 2 IBS: 0.18500570168858935
Fold 3 IBS: 0.17412783878300364
Fold 4 IBS: 0.20964581935767979
Fold 5 IBS: 0.18523331863966783
[I 2024-04-16 13:12:18,439] Trial 7 finished with value: 0.19248525513217893 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.2500273900096136
Fold 2 IBS: 0.24252428811376492
Fold 3 IBS: 0.19169795532346123
Fold 4 IBS: 0.26800891557035394
Fold 5 IBS: 0.20674266811943262
[I 2024-04-16 13:12:30,364] Trial 8 finished with value: 0.23180024342732528 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.3046029224708627
Fold 2 IBS: 0.32082834695628154
Fold 3 IBS: 0.26733861086225763
Fold 4 IBS: 0.3050114978922588
Fold 5 IBS: 0.2884806457432024
[I 2024-04-16 13:12:54,815] Trial 9 finished with value: 0.2972524047849726 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.21341107818060095
Fold 2 IBS: 0.22041244256787032
Fold 3 IBS: 0.20358827659270148
Fold 4 IBS: 0.22376802174886082
Fold 5 IBS: 0.2171830253408078
[I 2024-04-16 13:12:56,238] Trial 10 finished with value: 0.21567256888616831 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.2131898560857691
Fold 2 IBS: 0.22000460296162738
Fold 3 IBS: 0.20348419225803208
Fold 4 IBS: 0.22352663518317686
Fold 5 IBS: 0.2169388510633896
[I 2024-04-16 13:12:56,607] Trial 11 finished with value: 0.215428827510399 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.2649085487462804
Fold 2 IBS: 0.27910298172213
Fold 3 IBS: 0.21547582765233256
Fold 4 IBS: 0.269516915435845
Fold 5 IBS: 0.2156340458252758
[I 2024-04-16 13:13:01,646] Trial 12 finished with value: 0.24892766387637275 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.26365849597545205
Fold 2 IBS: 0.27755786474823224
Fold 3 IBS: 0.21375266267140264
Fold 4 IBS: 0.27739729053928086
Fold 5 IBS: 0.24947493405031224
[I 2024-04-16 13:13:18,586] Trial 13 finished with value: 0.25636824959693605 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.20569427667469156
Fold 2 IBS: 0.19327418056505236
Fold 3 IBS: 0.18069024590527896
Fold 4 IBS: 0.2080995790312972
Fold 5 IBS: 0.19490230571351805
[I 2024-04-16 13:13:24,110] Trial 14 finished with value: 0.19653211757796762 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.210409804816474
Fold 2 IBS: 0.21349058556283512
Fold 3 IBS: 0.1985155340163065
Fold 4 IBS: 0.21856174646948462
Fold 5 IBS: 0.2116375341523675
[I 2024-04-16 13:13:27,729] Trial 15 finished with value: 0.21052304100349356 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.20630685620006517
Fold 2 IBS: 0.20273931524283226
Fold 3 IBS: 0.18919005657291543
Fold 4 IBS: 0.21127743577400432
Fold 5 IBS: 0.20267124736055916
[I 2024-04-16 13:13:30,756] Trial 16 finished with value: 0.20243698223007528 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.23835959803032003
Fold 2 IBS: 0.21402340081247587
Fold 3 IBS: 0.17953828231829627
Fold 4 IBS: 0.25047212321042694
Fold 5 IBS: 0.19743222117495793
[I 2024-04-16 13:13:37,433] Trial 17 finished with value: 0.2159651251092954 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.23992452095154856
Fold 2 IBS: 0.21495595423038097
Fold 3 IBS: 0.18009687426129353
Fold 4 IBS: 0.24881181915281447
Fold 5 IBS: 0.18903245869258709
[I 2024-04-16 13:14:00,353] Trial 18 finished with value: 0.2145643254577249 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19248525513217893.
Fold 1 IBS: 0.2021259476312318

Fold 2 IBS: 0.17879461279451767
Fold 3 IBS: 0.17573163203218803
Fold 4 IBS: 0.19119338501096567
Fold 5 IBS: 0.18498574070536566
[I 2024-04-16 13:14:03,372] Trial 19 finished with value: 0.1865662636348538 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.20385002842262298
Fold 2 IBS: 0.17898541076661173
Fold 3 IBS: 0.177518113027334
Fold 4 IBS: 0.1979575811954832
Fold 5 IBS: 0.18783103572217225
[I 2024-04-16 13:14:05,611] Trial 20 finished with value: 0.18922843382684484 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.20107429217460354
Fold 2 IBS: 0.186025328567609
Fold 3 IBS: 0.18218745670213524
Fold 4 IBS: 0.20090706949452952
Fold 5 IBS: 0.19364926572166022
[I 2024-04-16 13:14:09,490] Trial 21 finished with value: 0.1927686825321075 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.21289135072667675
Fold 2 IBS: 0.2192362843041557
Fold 3 IBS: 0.20256314478108844
Fold 4 IBS: 0.22230805658932015
Fold 5 IBS: 0.21635372756130705
[I 2024-04-16 13:14:09,816] Trial 22 finished with value: 0.21467051279250962 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.23708682933847808
Fold 2 IBS: 0.20411180700958567
Fold 3 IBS: 0.18521649133151546
Fold 4 IBS: 0.22900869613667912
Fold 5 IBS: 0.17815051204094456
[I 2024-04-16 13:14:16,850] Trial 23 finished with value: 0.20671486717144058 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.22412270848810453
Fold 2 IBS: 0.1908952941916656
Fold 3 IBS: 0.17076790246118903
Fold 4 IBS: 0.23054053553396578
Fold 5 IBS: 0.1791781259966363
[I 2024-04-16 13:14:19,810] Trial 24 finished with value: 0.19910091333431226 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.22104049859904298
Fold 2 IBS: 0.1845697626181813
Fold 3 IBS: 0.171869292415374
Fold 4 IBS: 0.2182289571138028
Fold 5 IBS: 0.1794251542138473
[I 2024-04-16 13:14:24,114] Trial 25 finished with value: 0.19502673299204967 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.26315991461939425
Fold 2 IBS: 0.251978470209898
Fold 3 IBS: 0.23271064216908657
Fold 4 IBS: 0.22234197098407749
Fold 5 IBS: 0.21451110047981498
[I 2024-04-16 13:14:31,939] Trial 26 finished with value: 0.23694041969245427 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.25537532111682654
Fold 2 IBS: 0.24639152367929454
Fold 3 IBS: 0.20330381468053177
Fold 4 IBS: 0.26509675916293274
Fold 5 IBS: 0.20468510476749555
[I 2024-04-16 13:14:43,647] Trial 27 finished with value: 0.23497050468141625 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.20527495893711703
Fold 2 IBS: 0.1923192977101289
Fold 3 IBS: 0.18569841819626018
Fold 4 IBS: 0.2063890017855301
Fold 5 IBS: 0.1987721547693016
[I 2024-04-16 13:14:45,830] Trial 28 finished with value: 0.19769076627966756 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.25186522298741737
Fold 2 IBS: 0.24845492076238285
Fold 3 IBS: 0.19440108192909572
Fold 4 IBS: 0.27098179405615386
Fold 5 IBS: 0.2012576333551763
[I 2024-04-16 13:14:51,342] Trial 29 finished with value: 0.23339213061804523 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.2330665600388519
Fold 2 IBS: 0.18958254715791947
Fold 3 IBS: 0.17562341060021416
Fold 4 IBS: 0.2231198608530349
Fold 5 IBS: 0.17942400302117853
[I 2024-04-16 13:29:51,808] Trial 30 finished with value: 0.2001632763342398 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.20152086260197935
Fold 2 IBS: 0.17925245864127606
Fold 3 IBS: 0.1779752579597176
Fold 4 IBS: 0.1984841468259268
Fold 5 IBS: 0.1885834535382215
[I 2024-04-16 13:29:53,182] Trial 31 finished with value: 0.18916323591342427 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.2034563655600113
Fold 2 IBS: 0.18999348990743456
Fold 3 IBS: 0.1813864736795483
Fold 4 IBS: 0.20066103940254612
Fold 5 IBS: 0.19073119646244754
[I 2024-04-16 13:29:54,310] Trial 32 finished with value: 0.19324571300239754 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.21866270441789398
Fold 2 IBS: 0.1711571541630259
Fold 3 IBS: 0.17360253671732068
Fold 4 IBS: 0.19960732449787755
Fold 5 IBS: 0.17755703415819266
[I 2024-04-16 13:29:56,341] Trial 33 finished with value: 0.18811735079086217 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.21134490777110404
Fold 2 IBS: 0.2124741646949405
Fold 3 IBS: 0.19947910525310025
Fold 4 IBS: 0.2188565718064687
Fold 5 IBS: 0.21362043912965564
[I 2024-04-16 13:29:56,694] Trial 34 finished with value: 0.21115503773105382 and parameters: {'subsample': 0.10904251030586302, 'dropout_rate': 0.8662195064551774, 'n_estimators': 3, 'learning_rate': 0.07766566220378217}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.26215924412786523
Fold 2 IBS: 0.26142634624635325
Fold 3 IBS: 0.21333959381290407
Fold 4 IBS: 0.26840863359298894
Fold 5 IBS: 0.21087989518898054
[I 2024-04-16 13:45:03,681] Trial 35 finished with value: 0.2432427425938184 and parameters: {'subsample': 0.27868485453535496, 'dropout_rate': 0.9999743696114711, 'n_estimators': 141, 'learning_rate': 0.06694317131672249}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.31801903549259186
Fold 2 IBS: 0.31850389820468317
Fold 3 IBS: 0.2768825720358129
Fold 4 IBS: 0.2690166734606147
Fold 5 IBS: 0.26403091868880973
[I 2024-04-16 13:49:19,994] Trial 36 finished with value: 0.2892906195765025 and parameters: {'subsample': 0.16326559473518704, 'dropout_rate': 0.8736174627174981, 'n_estimators': 421, 'learning_rate': 0.07993410500556083}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.26123034714252413
Fold 2 IBS: 0.2609067973308416
Fold 3 IBS: 0.21321387061292466
Fold 4 IBS: 0.2671551183060875
Fold 5 IBS: 0.21092211191886873
[I 2024-04-16 13:49:26,032] Trial 37 finished with value: 0.24268564906224932 and parameters: {'subsample': 0.23660873470356106, 'dropout_rate': 0.7990281623991888, 'n_estimators': 170, 'learning_rate': 0.05621431261796065}. Best is trial 19 with value: 0.1865662636348538.
Fold 1 IBS: 0.2190285825827486
Fold 2 IBS: 0.15696944499547258

Fold 3 IBS: 0.17687063215564577
Fold 4 IBS: 0.19142503805165928
Fold 5 IBS: 0.17771887919295226
[I 2024-04-16 13:49:29,771] Trial 38 finished with value: 0.18440251539569572 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 82, 'learning_rate': 0.0684395247111694}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.23012380534879587
Fold 2 IBS: 0.17206085972010163
Fold 3 IBS: 0.17890276059875942
Fold 4 IBS: 0.20856260698376405
Fold 5 IBS: 0.17199961045343268
[I 2024-04-16 13:49:33,625] Trial 39 finished with value: 0.19232992862097073 and parameters: {'subsample': 0.3132620855006216, 'dropout_rate': 0.11471626893495929, 'n_estimators': 77, 'learning_rate': 0.06892741183938003}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2621725369284015
Fold 2 IBS: 0.26403894140234485
Fold 3 IBS: 0.20945772199901574
Fold 4 IBS: 0.2737981466224617
Fold 5 IBS: 0.21418882926872254
[I 2024-04-16 13:49:39,490] Trial 40 finished with value: 0.24473123524418927 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.27073406810212547, 'n_estimators': 110, 'learning_rate': 0.08603457614657108}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2184207553387651
Fold 2 IBS: 0.17427805242799588
Fold 3 IBS: 0.17253587612369042
Fold 4 IBS: 0.1886276175634911
Fold 5 IBS: 0.1747808933456154
[I 2024-04-16 13:49:43,378] Trial 41 finished with value: 0.1857286389599116 and parameters: {'subsample': 0.14186326848857284, 'dropout_rate': 0.24159494757459665, 'n_estimators': 56, 'learning_rate': 0.06842845994744125}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.22008875402016237
Fold 2 IBS: 0.16118141529171465
Fold 3 IBS: 0.17829290790268262
Fold 4 IBS: 0.20292932050455156
Fold 5 IBS: 0.1778181942889707
[I 2024-04-16 13:49:47,166] Trial 42 finished with value: 0.1880621184016164 and parameters: {'subsample': 0.10316949011693997, 'dropout_rate': 0.19807687454956896, 'n_estimators': 81, 'learning_rate': 0.06911254892370094}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2764334452023296
Fold 2 IBS: 0.24442347998533606
Fold 3 IBS: 0.2362020081166815
Fold 4 IBS: 0.24053600457131113
Fold 5 IBS: 0.2067318545926361
[I 2024-04-16 13:49:58,495] Trial 43 finished with value: 0.24086535849365892 and parameters: {'subsample': 0.1662617724194161, 'dropout_rate': 0.21348524642098904, 'n_estimators': 202, 'learning_rate': 0.0726352652201749}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2604917776437938
Fold 2 IBS: 0.22356317240980722
Fold 3 IBS: 0.2248826501805259
Fold 4 IBS: 0.24895388122524006
Fold 5 IBS: 0.20204587514501984
[I 2024-04-16 13:50:06,156] Trial 44 finished with value: 0.23198747132087738 and parameters: {'subsample': 0.21390837882764044, 'dropout_rate': 0.20101401396422397, 'n_estimators': 172, 'learning_rate': 0.06523605428553468}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.24758337408235334
Fold 2 IBS: 0.22459674334571958
Fold 3 IBS: 0.18625722818474322
Fold 4 IBS: 0.2568622389724023
Fold 5 IBS: 0.19101280426925527
[I 2024-04-16 13:50:10,224] Trial 45 finished with value: 0.2212624777708947 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.295844522167053, 'n_estimators': 88, 'learning_rate': 0.07358829455007394}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.22915814387431366
Fold 2 IBS: 0.18438436224089505
Fold 3 IBS: 0.18169178483408235
Fold 4 IBS: 0.2068115487634011
Fold 5 IBS: 0.17519988249685678
[I 2024-04-16 13:50:13,438] Trial 46 finished with value: 0.1954491444419098 and parameters: {'subsample': 0.14485404068604799, 'dropout_rate': 0.3312246704393865, 'n_estimators': 66, 'learning_rate': 0.08365083008051383}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2336101729009036
Fold 2 IBS: 0.16537250564712072
Fold 3 IBS: 0.19207898216561076
Fold 4 IBS: 0.1986089715571676
Fold 5 IBS: 0.18357182710964493
[I 2024-04-16 13:50:20,078] Trial 47 finished with value: 0.1946484918760895 and parameters: {'subsample': 0.10113996760134518, 'dropout_rate': 0.13911133506878087, 'n_estimators': 123, 'learning_rate': 0.0622210649734474}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.20547826447274276
Fold 2 IBS: 0.18438082642696052
Fold 3 IBS: 0.17757200517198868
Fold 4 IBS: 0.20887957089195924
Fold 5 IBS: 0.18848869528002174
[I 2024-04-16 13:50:21,357] Trial 48 finished with value: 0.1929598724487346 and parameters: {'subsample': 0.2487580783092397, 'dropout_rate': 0.19701471782839963, 'n_estimators': 19, 'learning_rate': 0.09182402211019655}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.23181807848997826
Fold 2 IBS: 0.18830322026697965
Fold 3 IBS: 0.1799299438457726
Fold 4 IBS: 0.22730292456487247
Fold 5 IBS: 0.17698730920566644
[I 2024-04-16 13:50:26,031] Trial 49 finished with value: 0.20086829527465389 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.4402540309495773, 'n_estimators': 102, 'learning_rate': 0.051717833751605366}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2889412476272311
Fold 2 IBS: 0.27844794476657675
Fold 3 IBS: 0.25024893393572084
Fold 4 IBS: 0.2552547397931789
Fold 5 IBS: 0.2234198786641813
[I 2024-04-16 13:50:37,160] Trial 50 finished with value: 0.25926254895737777 and parameters: {'subsample': 0.3066964070298052, 'dropout_rate': 0.17538138388138197, 'n_estimators': 230, 'learning_rate': 0.07966264522754796}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.21917750452042478
Fold 2 IBS: 0.16563269253311136
Fold 3 IBS: 0.17264636250371082
Fold 4 IBS: 0.19133884222796765
Fold 5 IBS: 0.17853770418433418
[I 2024-04-16 13:50:39,813] Trial 51 finished with value: 0.18546662119390972 and parameters: {'subsample': 0.1422401972634589, 'dropout_rate': 0.10079252980319817, 'n_estimators': 56, 'learning_rate': 0.07018211474264216}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.21971605355363413
Fold 2 IBS: 0.16771819297766788
Fold 3 IBS: 0.17281025495683439
Fold 4 IBS: 0.19251122281200475
Fold 5 IBS: 0.17521089816780278
[I 2024-04-16 13:50:42,373] Trial 52 finished with value: 0.18559332449358876 and parameters: {'subsample': 0.14223803588393702, 'dropout_rate': 0.10510137537932576, 'n_estimators': 57, 'learning_rate': 0.06926018955996141}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.28096750186914604
Fold 2 IBS: 0.22338824605078478
Fold 3 IBS: 0.2496857414141581
Fold 4 IBS: 0.21542598743987917
Fold 5 IBS: 0.2107898600013819
[I 2024-04-16 13:50:54,715] Trial 53 finished with value: 0.23605146735507 and parameters: {'subsample': 0.15091648652899717, 'dropout_rate': 0.10187914564083042, 'n_estimators': 276, 'learning_rate': 0.0705232778594808}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2264282177763513
Fold 2 IBS: 0.18295218530040652
Fold 3 IBS: 0.17130997581843713
Fold 4 IBS: 0.22730261297473436
Fold 5 IBS: 0.17557608178121276
[I 2024-04-16 13:50:56,915] Trial 54 finished with value: 0.19671381473022842 and parameters: {'subsample': 0.7123271512684496, 'dropout_rate': 0.1495897230999219, 'n_estimators': 49, 'learning_rate': 0.07714657691990995}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2016523152323051
Fold 2 IBS: 0.19727341954188565
Fold 3 IBS: 0.18288671963355707
Fold 4 IBS: 0.20519106423654848
Fold 5 IBS: 0.1969634191370901
[I 2024-04-16 13:50:57,939] Trial 55 finished with value: 0.1967933875562773 and parameters: {'subsample': 0.19235835223177755, 'dropout_rate': 0.25712307227065867, 'n_estimators': 20, 'learning_rate': 0.058792439227992585}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.24217565627790597
Fold 2 IBS: 0.18439531168908357
Fold 3 IBS: 0.19444776307279835
Fold 4 IBS: 0.21465421179381516
Fold 5 IBS: 0.1823829505118782
[I 2024-04-16 13:51:01,859] Trial 56 finished with value: 0.20361117866909625 and parameters: {'subsample': 0.13601443571906321, 'dropout_rate': 0.23034344131063678, 'n_estimators': 83, 'learning_rate': 0.09032997715983931}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2235152593971129
Fold 2 IBS: 0.1754255447651504

Fold 3 IBS: 0.1720321274763833
Fold 4 IBS: 0.20269242936659473
Fold 5 IBS: 0.17347750016357924
[I 2024-04-16 13:51:04,355] Trial 57 finished with value: 0.1894285722337641 and parameters: {'subsample': 0.22308046590336078, 'dropout_rate': 0.16382075159292628, 'n_estimators': 54, 'learning_rate': 0.07586937026396535}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.24723459364971187
Fold 2 IBS: 0.2044357530332651
Fold 3 IBS: 0.20292788668222125
Fold 4 IBS: 0.223528759028567
Fold 5 IBS: 0.1832818904315015
[I 2024-04-16 13:51:10,653] Trial 58 finished with value: 0.21228177656505337 and parameters: {'subsample': 0.2849097248903497, 'dropout_rate': 0.12541109823464971, 'n_estimators': 133, 'learning_rate': 0.06314379319286169}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.22470401483207397
Fold 2 IBS: 0.18044827895656998
Fold 3 IBS: 0.1770853252772186
Fold 4 IBS: 0.22051345390766136
Fold 5 IBS: 0.17624589843250807
[I 2024-04-16 13:51:14,890] Trial 59 finished with value: 0.19579939428120638 and parameters: {'subsample': 0.14188316689464764, 'dropout_rate': 0.33799719021891794, 'n_estimators': 103, 'learning_rate': 0.04739254727118543}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2664074079841191
Fold 2 IBS: 0.264099368264975
Fold 3 IBS: 0.21800596330121338
Fold 4 IBS: 0.26247629491230584
Fold 5 IBS: 0.2140113570596523
[I 2024-04-16 13:51:22,077] Trial 60 finished with value: 0.24500007830445308 and parameters: {'subsample': 0.3436490623188294, 'dropout_rate': 0.23691479339743635, 'n_estimators': 153, 'learning_rate': 0.07018729343441713}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.22018585502122723
Fold 2 IBS: 0.16282433998221824
Fold 3 IBS: 0.17547209069218397
Fold 4 IBS: 0.19595417882459099
Fold 5 IBS: 0.17738338772374027
[I 2024-04-16 13:51:25,024] Trial 61 finished with value: 0.18636397044879213 and parameters: {'subsample': 0.12774966686031303, 'dropout_rate': 0.17157804364515114, 'n_estimators': 72, 'learning_rate': 0.06622321266742605}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.22206043821021132
Fold 2 IBS: 0.17138602616080847
Fold 3 IBS: 0.17658655553172878
Fold 4 IBS: 0.1991987749741228
Fold 5 IBS: 0.17573314722965477
[I 2024-04-16 13:51:28,051] Trial 62 finished with value: 0.18899298842130524 and parameters: {'subsample': 0.18096067094147122, 'dropout_rate': 0.17387134679643484, 'n_estimators': 70, 'learning_rate': 0.07275892105863323}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.20517642307261616
Fold 2 IBS: 0.19790324731318623
Fold 3 IBS: 0.18799412287181624
Fold 4 IBS: 0.2068758591940843
Fold 5 IBS: 0.20002794599290669
[I 2024-04-16 13:51:28,930] Trial 63 finished with value: 0.19959551968892192 and parameters: {'subsample': 0.13059108799625255, 'dropout_rate': 0.10356912698776774, 'n_estimators': 15, 'learning_rate': 0.06438003890136722}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.21104574098293008
Fold 2 IBS: 0.1743809765521462
Fold 3 IBS: 0.17249265370300756
Fold 4 IBS: 0.2041276353638025
Fold 5 IBS: 0.17818434010328238
[I 2024-04-16 13:51:30,943] Trial 64 finished with value: 0.18804626934103377 and parameters: {'subsample': 0.20153509278421144, 'dropout_rate': 0.29130372801223314, 'n_estimators': 44, 'learning_rate': 0.059505140523123674}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2085641752584418
Fold 2 IBS: 0.17616452823211376
Fold 3 IBS: 0.173550336113845
Fold 4 IBS: 0.2025431400396639
Fold 5 IBS: 0.18016484351373666
[I 2024-04-16 13:51:33,027] Trial 65 finished with value: 0.1881974046315602 and parameters: {'subsample': 0.20385035399235038, 'dropout_rate': 0.285642335246679, 'n_estimators': 44, 'learning_rate': 0.053043947781164114}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2095368555831298
Fold 2 IBS: 0.18160460486493588
Fold 3 IBS: 0.17294878926115564
Fold 4 IBS: 0.20471565494738553
Fold 5 IBS: 0.18043171103891875
[I 2024-04-16 13:51:35,018] Trial 66 finished with value: 0.1898475231391051 and parameters: {'subsample': 0.25269796143726253, 'dropout_rate': 0.38451580884291076, 'n_estimators': 42, 'learning_rate': 0.06075287229046976}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2643224175733689
Fold 2 IBS: 0.23160578302038953
Fold 3 IBS: 0.22612242435702218
Fold 4 IBS: 0.23131986614826947
Fold 5 IBS: 0.20108129797881152
[I 2024-04-16 13:51:54,212] Trial 67 finished with value: 0.23089035781557232 and parameters: {'subsample': 0.1706329568609385, 'dropout_rate': 0.14088854643153187, 'n_estimators': 321, 'learning_rate': 0.036558247951431325}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.21351004549764144
Fold 2 IBS: 0.21935820722732538
Fold 3 IBS: 0.2037864943966872
Fold 4 IBS: 0.22395096311162527
Fold 5 IBS: 0.21686659906602154
[I 2024-04-16 13:51:54,603] Trial 68 finished with value: 0.21549446185986015 and parameters: {'subsample': 0.13092716011608707, 'dropout_rate': 0.4936851052300081, 'n_estimators': 1, 'learning_rate': 0.0582375351466085}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2161873573554078
Fold 2 IBS: 0.16652372023182296
Fold 3 IBS: 0.17276313939629154
Fold 4 IBS: 0.19631879265080307
Fold 5 IBS: 0.17689689633428443
[I 2024-04-16 13:51:57,510] Trial 69 finished with value: 0.18573798119372195 and parameters: {'subsample': 0.17427377303929523, 'dropout_rate': 0.1665265284254126, 'n_estimators': 60, 'learning_rate': 0.0668624432927924}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.31506742774617225
Fold 2 IBS: 0.29428102091387054
Fold 3 IBS: 0.27149743237320134
Fold 4 IBS: 0.2445673255002672
Fold 5 IBS: 0.23360893999295837
[I 2024-04-16 13:52:21,785] Trial 70 finished with value: 0.27180442930529397 and parameters: {'subsample': 0.16867686484183628, 'dropout_rate': 0.17624843792855271, 'n_estimators': 408, 'learning_rate': 0.07996711454725015}. Best is trial 38 with value: 0.18440251539569572.
Fold 1 IBS: 0.2207970826094004
Fold 2 IBS: 0.16315401507025756
Fold 3 IBS: 0.17195491089686146
Fold 4 IBS: 0.19000976829180546
Fold 5 IBS: 0.17421326228651735
[I 2024-04-16 13:52:25,488] Trial 71 finished with value: 0.18402580783096845 and parameters: {'subsample': 0.19896402919062606, 'dropout_rate': 0.12961833118929164, 'n_estimators': 60, 'learning_rate': 0.06699228139866219}. Best is trial 71 with value: 0.18402580783096845.
Fold 1 IBS: 0.21187725672550933
Fold 2 IBS: 0.16103737585624903
Fold 3 IBS: 0.17412071887475286
Fold 4 IBS: 0.19495499899473126
Fold 5 IBS: 0.1760862970430504
[I 2024-04-16 13:52:28,933] Trial 72 finished with value: 0.1836153294988586 and parameters: {'subsample': 0.12320236346719246, 'dropout_rate': 0.13536522321689456, 'n_estimators': 68, 'learning_rate': 0.06692618586228362}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.22772806105071394
Fold 2 IBS: 0.16645579805969637
Fold 3 IBS: 0.18291908006844096
Fold 4 IBS: 0.19202338737878524
Fold 5 IBS: 0.17817294386615776
[I 2024-04-16 13:52:34,901] Trial 73 finished with value: 0.18945985408475885 and parameters: {'subsample': 0.13156189813522945, 'dropout_rate': 0.12999823799105892, 'n_estimators': 96, 'learning_rate': 0.06552555944095279}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.23735483775016253
Fold 2 IBS: 0.21017853871067146
Fold 3 IBS: 0.17695729408002372
Fold 4 IBS: 0.24790138016674565
Fold 5 IBS: 0.18432754625210407
[I 2024-04-16 13:52:38,512] Trial 74 finished with value: 0.21134391939194147 and parameters: {'subsample': 0.7948212261000067, 'dropout_rate': 0.23237800375099293, 'n_estimators': 71, 'learning_rate': 0.07175218331061978}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.22960632531305458
Fold 2 IBS: 0.17403672913793305
Fold 3 IBS: 0.17383037098930326
Fold 4 IBS: 0.20858843161783833
Fold 5 IBS: 0.1749438942597382
[I 2024-04-16 13:52:41,698] Trial 75 finished with value: 0.19220115026357348 and parameters: {'subsample': 0.22978092620400964, 'dropout_rate': 0.1557985394573569, 'n_estimators': 60, 'learning_rate': 0.07531885239494358}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.23394980714644545

Fold 2 IBS: 0.17136294720501474
Fold 3 IBS: 0.1942205278629809
Fold 4 IBS: 0.18836548573686962
Fold 5 IBS: 0.18371776191244502
[I 2024-04-16 13:52:47,423] Trial 76 finished with value: 0.19432330597275116 and parameters: {'subsample': 0.12565758748945094, 'dropout_rate': 0.1008354138446842, 'n_estimators': 115, 'learning_rate': 0.06744663662796715}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.2122887185855283
Fold 2 IBS: 0.18559325172580513
Fold 3 IBS: 0.17394637292345108
Fold 4 IBS: 0.21069765756694586
Fold 5 IBS: 0.18280497330673373
[I 2024-04-16 13:52:49,610] Trial 77 finished with value: 0.1930661948216928 and parameters: {'subsample': 0.549746960211358, 'dropout_rate': 0.18609046599680273, 'n_estimators': 36, 'learning_rate': 0.06375434111629431}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.2368850951432027
Fold 2 IBS: 0.2028084971050872
Fold 3 IBS: 0.1912826057200971
Fold 4 IBS: 0.2040995320657804
Fold 5 IBS: 0.180053379848087
[I 2024-04-16 13:52:54,249] Trial 78 finished with value: 0.20302582197645086 and parameters: {'subsample': 0.16376120231096009, 'dropout_rate': 0.21479998057844538, 'n_estimators': 88, 'learning_rate': 0.0831837804241962}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.20452091155030377
Fold 2 IBS: 0.182975816949132
Fold 3 IBS: 0.1787399957078331
Fold 4 IBS: 0.2046689280848674
Fold 5 IBS: 0.1885883975416969
[I 2024-04-16 13:52:55,676] Trial 79 finished with value: 0.19189880996676661 and parameters: {'subsample': 0.2647948164552401, 'dropout_rate': 0.12466828052816062, 'n_estimators': 26, 'learning_rate': 0.06803581530419511}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.21861848050603805
Fold 2 IBS: 0.16192997187995672
Fold 3 IBS: 0.17198766768297505
Fold 4 IBS: 0.1946057974297024
Fold 5 IBS: 0.1742888493730214
[I 2024-04-16 13:52:59,142] Trial 80 finished with value: 0.1842861533743387 and parameters: {'subsample': 0.18846220787555074, 'dropout_rate': 0.14030017497322128, 'n_estimators': 59, 'learning_rate': 0.07497292867499944}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.21707519127989297
Fold 2 IBS: 0.1682048167604984
Fold 3 IBS: 0.172087580074055
Fold 4 IBS: 0.2020214538416694
Fold 5 IBS: 0.17666739085663366
[I 2024-04-16 13:53:02,169] Trial 81 finished with value: 0.18721128656254987 and parameters: {'subsample': 0.1844452330553255, 'dropout_rate': 0.15338799709287165, 'n_estimators': 58, 'learning_rate': 0.07171419297633509}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.22280566128845844
Fold 2 IBS: 0.1666619539239231
Fold 3 IBS: 0.17804140396484017
Fold 4 IBS: 0.18135862008436518
Fold 5 IBS: 0.17267919392596498
[I 2024-04-16 13:53:05,782] Trial 82 finished with value: 0.18430936663751038 and parameters: {'subsample': 0.15179518067190306, 'dropout_rate': 0.12550386608809208, 'n_estimators': 73, 'learning_rate': 0.07516444667116107}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.20404444385157505
Fold 2 IBS: 0.19971259500662297
Fold 3 IBS: 0.1891934047822345
Fold 4 IBS: 0.20569898904030878
Fold 5 IBS: 0.20099649081099305
[I 2024-04-16 13:53:06,662] Trial 83 finished with value: 0.19992918469834686 and parameters: {'subsample': 0.22128472480495118, 'dropout_rate': 0.1377326496899521, 'n_estimators': 12, 'learning_rate': 0.07535844698653568}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.20443632352101063
Fold 2 IBS: 0.1732577478985964
Fold 3 IBS: 0.17498946336784246
Fold 4 IBS: 0.1896329522215414
Fold 5 IBS: 0.1785730211745253
[I 2024-04-16 13:53:08,348] Trial 84 finished with value: 0.18417790163670325 and parameters: {'subsample': 0.15782219649143608, 'dropout_rate': 0.12399783271954713, 'n_estimators': 32, 'learning_rate': 0.07884812667200451}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.20531582313684033
Fold 2 IBS: 0.17649686962688535
Fold 3 IBS: 0.17507578489743322
Fold 4 IBS: 0.19349308090748574
Fold 5 IBS: 0.18456835438410807
[I 2024-04-16 13:53:10,087] Trial 85 finished with value: 0.18698998259055055 and parameters: {'subsample': 0.14736454966631027, 'dropout_rate': 0.12159367078996092, 'n_estimators': 30, 'learning_rate': 0.08160857630783308}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.24498184018360283
Fold 2 IBS: 0.19508823020693186
Fold 3 IBS: 0.20520811071453185
Fold 4 IBS: 0.2226387559091405
Fold 5 IBS: 0.18805414434011916
[I 2024-04-16 13:53:15,566] Trial 86 finished with value: 0.21119421627086524 and parameters: {'subsample': 0.15513169968756263, 'dropout_rate': 0.2554947990993826, 'n_estimators': 109, 'learning_rate': 0.07789160958223988}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.23741052414415517
Fold 2 IBS: 0.20045364009630556
Fold 3 IBS: 0.19076440904226127
Fold 4 IBS: 0.21198358633794492
Fold 5 IBS: 0.17977407867699416
[I 2024-04-16 13:53:20,454] Trial 87 finished with value: 0.2040772476595322 and parameters: {'subsample': 0.19501634161398365, 'dropout_rate': 0.21285368046676167, 'n_estimators': 83, 'learning_rate': 0.08470862171288643}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.20753325908385908
Fold 2 IBS: 0.17278292398884595
Fold 3 IBS: 0.17360280062432723
Fold 4 IBS: 0.1983686582729745
Fold 5 IBS: 0.18137379799496417
[I 2024-04-16 13:53:22,621] Trial 88 finished with value: 0.18673228799299418 and parameters: {'subsample': 0.2839606931616282, 'dropout_rate': 0.1009579109281902, 'n_estimators': 35, 'learning_rate': 0.06967295840519373}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.22931462014817464
Fold 2 IBS: 0.17043737262176917
Fold 3 IBS: 0.174839104489101
Fold 4 IBS: 0.19595536479073253
Fold 5 IBS: 0.17492563007777867
[I 2024-04-16 13:53:25,574] Trial 89 finished with value: 0.18909441842551117 and parameters: {'subsample': 0.24593760440448553, 'dropout_rate': 0.14120381569860857, 'n_estimators': 53, 'learning_rate': 0.09057773912746316}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.2354497912362797
Fold 2 IBS: 0.18007886904579207
Fold 3 IBS: 0.19853560644883056
Fold 4 IBS: 0.21893105550512784
Fold 5 IBS: 0.1859836269877836
[I 2024-04-16 13:53:31,453] Trial 90 finished with value: 0.2037957898447628 and parameters: {'subsample': 0.12434637064786674, 'dropout_rate': 0.1912168817442258, 'n_estimators': 95, 'learning_rate': 0.08761710129486994}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.2213424076116293
Fold 2 IBS: 0.16769359340183532
Fold 3 IBS: 0.17714692540850463
Fold 4 IBS: 0.2036052897929585
Fold 5 IBS: 0.1769779800602846
[I 2024-04-16 13:53:34,909] Trial 91 finished with value: 0.18935323925504247 and parameters: {'subsample': 0.17756906755832302, 'dropout_rate': 0.15692654787906246, 'n_estimators': 68, 'learning_rate': 0.0743177526539924}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.2174685785168919
Fold 2 IBS: 0.16323261289321278
Fold 3 IBS: 0.1770329579010761
Fold 4 IBS: 0.2017571704925053
Fold 5 IBS: 0.1741176190619812
[I 2024-04-16 13:53:37,772] Trial 92 finished with value: 0.18672178777313347 and parameters: {'subsample': 0.21150781633485646, 'dropout_rate': 0.11957703453224162, 'n_estimators': 57, 'learning_rate': 0.09716959562006876}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.2040821583553086
Fold 2 IBS: 0.196425656002405
Fold 3 IBS: 0.1871073799699254
Fold 4 IBS: 0.2033060874938666
Fold 5 IBS: 0.19665325585418114
[I 2024-04-16 13:53:38,722] Trial 93 finished with value: 0.19751490753513734 and parameters: {'subsample': 0.15571157524606255, 'dropout_rate': 0.16195972358261923, 'n_estimators': 13, 'learning_rate': 0.07863856829659394}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.1975384707893045
Fold 2 IBS: 0.18005591980153923
Fold 3 IBS: 0.17755542649908365
Fold 4 IBS: 0.20549303098819618
Fold 5 IBS: 0.18621047179899247
[I 2024-04-16 13:53:40,200] Trial 94 finished with value: 0.1893706639754232 and parameters: {'subsample': 0.11839698633775655, 'dropout_rate': 0.18619257295551966, 'n_estimators': 27, 'learning_rate': 0.07373785395072796}. Best is trial 72 with value: 0.1836153294988586.
Fold 1 IBS: 0.2197559587776388
Fold 2 IBS: 0.16780085454686616

Fold 3 IBS: 0.1786201819401681
Fold 4 IBS: 0.1730106628597333
Fold 5 IBS: 0.1769335760691037
[I 2024-04-16 13:53:44,020] Trial 95 finished with value: 0.18322424683870203 and parameters: {'subsample': 0.10113592213603971, 'dropout_rate': 0.12650276574260835, 'n_estimators': 75, 'learning_rate': 0.07005155964295467}. Best is trial 95 with value: 0.18322424683870203.
Fold 1 IBS: 0.24361216774620978
Fold 2 IBS: 0.18983481001075334
Fold 3 IBS: 0.21205828714477906
Fold 4 IBS: 0.1712402193849143
Fold 5 IBS: 0.19545836210091558
[I 2024-04-16 13:53:51,088] Trial 96 finished with value: 0.2024407692775144 and parameters: {'subsample': 0.10436272208850539, 'dropout_rate': 0.12665776901745035, 'n_estimators': 134, 'learning_rate': 0.08154732519464149}. Best is trial 95 with value: 0.18322424683870203.
Fold 1 IBS: 0.2261988766991688
Fold 2 IBS: 0.17895050409910299
Fold 3 IBS: 0.17889485274253647
Fold 4 IBS: 0.2076135194010375
Fold 5 IBS: 0.1758505273629191
[I 2024-04-16 13:53:55,174] Trial 97 finished with value: 0.193501656060953 and parameters: {'subsample': 0.1496315790362069, 'dropout_rate': 0.21000279741188874, 'n_estimators': 75, 'learning_rate': 0.07090823829920229}. Best is trial 95 with value: 0.18322424683870203.
Fold 1 IBS: 0.24786278787358818
Fold 2 IBS: 0.19101418327170086
Fold 3 IBS: 0.19026436489299844
Fold 4 IBS: 0.2236530543219743
Fold 5 IBS: 0.17857248602978623
[I 2024-04-16 13:54:00,064] Trial 98 finished with value: 0.20627337527800957 and parameters: {'subsample': 0.6256495106817341, 'dropout_rate': 0.10722276462184306, 'n_estimators': 94, 'learning_rate': 0.07640960841841683}. Best is trial 95 with value: 0.18322424683870203.
Fold 1 IBS: 0.2159402897968344
Fold 2 IBS: 0.16084542670614288
Fold 3 IBS: 0.1769544862421722
Fold 4 IBS: 0.20282091506726588
Fold 5 IBS: 0.17640184176590293
[I 2024-04-16 13:54:03,999] Trial 99 finished with value: 0.18659259191566363 and parameters: {'subsample': 0.11633529866884976, 'dropout_rate': 0.14447205824071618, 'n_estimators': 81, 'learning_rate': 0.06256005534429794}. Best is trial 95 with value: 0.18322424683870203.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.18322424683870203], datetime_start=datetime.datetime(2024, 4, 16, 13, 53, 40, 206432), datetime_complete=datetime.datetime(2024, 4, 16, 13, 53, 44, 19573), params={'subsample': 0.10113592213603971, 'dropout_rate': 0.12650276574260835, 'n_estimators': 75, 'learning_rate': 0.07005155964295467}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=95, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10113592213603971, 'dropout_rate': 0.12650276574260835, 'n_estimators': 75, 'learning_rate': 0.07005155964295467}


* Best Score for IBS:
 0.18322424683870203

In [99]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [100]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.71
train_ibs:  0.183

#### Test

In [101]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [102]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3058920522870888,
                                              learning_rate=0.0016108337344105245,
                                              n_estimators=410,
                                              random_state=123,
                                              subsample=0.11014863416226671)

C-index score: 0.576

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.12650276574260835,
                                              learning_rate=0.07005155964295467,
                                              n_estimators=75, random_state=123,
                                              subsample=0.10113592213603971)

IBS: 0.246

In [103]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [104]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.871   1.0
ExtraSurvivalTrees               0.867   2.0
GradientBoosting                 0.740   3.0
ComponentwiseGradientBoosting    0.710   4.0
CoxElastic                       0.708   5.0
CoxRidge                         0.698   6.0
CoxLasso                         0.541   7.0

In [105]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.183   1.5
ComponentwiseGradientBoosting  0.183   1.5
ExtraSurvivalTrees             0.186   3.0
GradientBoosting               0.206   4.0
CoxElastic                     0.212   5.0
CoxRidge                       0.217   6.0
CoxLasso                       0.392   7.0

In [106]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.628   1.0
GradientBoosting                 0.618   2.0
ExtraSurvivalTrees               0.616   3.0
CoxRidge                         0.586   4.5
CoxElastic                       0.586   4.5
ComponentwiseGradientBoosting    0.576   6.0
CoxLasso                         0.500   7.0

In [107]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.214   1.0
GradientBoosting               0.215   2.0
CoxRidge                       0.221   3.5
CoxElastic                     0.221   3.5
Randomsurvivalforest           0.226   5.0
ComponentwiseGradientBoosting  0.246   6.0
CoxLasso                       0.430   7.0

In [108]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/standard/no_selection/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_standard_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

from datetime import date

current_date = date.today()
print(current_date)