In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from lifelines import CoxPHFitter
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
response_OUS.isna().sum().sum()

0

In [4]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [5]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [6]:
# Check null values in D3
clinical_train.isnull().sum().sum()

0

In [7]:
clinical_train

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,event_OS
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,...,0.029974,0.815962,0.000000,0.002035,0.140311,0.000062,0.009991,0.000370,114.312329,0
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,...,0.059728,0.707300,0.000000,0.008732,0.191058,0.000349,0.023402,0.000699,111.846575,0
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,...,0.039463,0.819828,0.000034,0.002518,0.126531,0.000000,0.009452,0.000414,49.479452,1
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,...,0.061133,0.716212,0.000000,0.003296,0.192388,0.000000,0.018879,0.000899,17.589041,1
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,...,0.058589,0.696493,0.000199,0.008968,0.202073,0.000399,0.029892,0.001395,66.739726,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,...,0.029444,0.804831,0.000000,0.001442,0.152626,0.000000,0.009734,0.000361,42.805479,0
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,...,0.046451,0.792151,0.000000,0.004094,0.142778,0.000079,0.011810,0.000630,42.739726,0
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,...,0.016316,0.832202,0.000000,0.000914,0.140582,0.000000,0.009137,0.000522,42.312329,0
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,...,0.038862,0.787588,0.000000,0.003144,0.156640,0.000054,0.011978,0.000705,42.246575,0
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,...,0.011577,0.830670,0.000000,0.000978,0.147644,0.000000,0.008642,0.000408,42.049315,0

## Test dataset: MAASTRO

In [8]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [9]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [10]:
rows_with_nan = response_MAASTRO[response_MAASTRO.isna().any(axis=1)]

print("Rows with NaN values:")
print(rows_with_nan)

Rows with NaN values:
    patient_id  OS  OS_event  LRC  LRC_event  DFS  DFS_event
10          11 NaN       NaN  NaN        NaN  NaN        NaN
20          21 NaN       NaN  NaN        NaN  NaN        NaN
31          32 NaN       NaN  NaN        NaN  NaN        NaN
51          52 NaN       NaN  NaN        NaN  NaN        NaN
83          84 NaN       NaN  NaN        NaN  NaN        NaN
86          87 NaN       NaN  NaN        NaN  NaN        NaN

In [11]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

In [12]:
MAASTRO_D3

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,1,55,0,0,1,0,0,1,1,1,...,0.000026,0.001181,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341
1,2,55,0,0,1,0,0,0,0,0,...,0.000056,0.002735,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335
2,3,55,0,0,1,0,0,0,0,1,...,0.000286,0.001888,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229
3,4,61,1,0,0,0,1,1,0,1,...,0.000160,0.003037,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240
4,6,70,0,0,1,0,0,1,1,1,...,0.000071,0.000881,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.000000,0.000544,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078
95,111,63,0,0,0,0,1,0,0,1,...,0.000109,0.000869,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489
96,112,63,0,0,1,0,0,1,1,1,...,0.000000,0.000734,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141
97,113,54,0,0,1,0,0,1,1,0,...,0.000114,0.001640,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038
98,114,62,0,0,0,1,0,1,0,0,...,0.000000,0.000225,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337

In [13]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(MAASTRO_D3['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: [5, 9, 11, 21, 32, 36, 46, 52, 65, 76, 78, 81, 84, 87, 92]

In [14]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: []

In [15]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [16]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [17]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [18]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [19]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [20]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 388)
y_train:  (139,)

(99, 390)

# Feature Selection: RENT

In [21]:
selected_features = ["hpv_related",
                    "uicc8_III-IV",
                    "shape_Sphericity",
                    "oropharynx",
                    "LBP_102_PET",
                    "pack_years"]


# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [22]:
original_X = X.copy()

In [23]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [24]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [25]:
X_new

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,0.0,0.0,0.761164,1,0.000000,0.000000
1,0.0,0.0,0.697049,0,0.000000,27.404795
2,0.0,1.0,0.565792,0,0.000034,41.019178
3,0.0,0.0,0.684364,0,0.000000,37.500000
4,0.0,0.0,0.503142,0,0.000199,53.000000
...,...,...,...,...,...,...
134,1.0,0.0,0.742102,1,0.000000,0.000000
135,1.0,1.0,0.722918,1,0.000000,0.000000
136,1.0,0.0,0.652963,1,0.000000,39.498630
137,1.0,1.0,0.724255,1,0.000000,71.527397
138,1.0,1.0,0.722633,1,0.000000,2.250000

In [26]:
X_new_std

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,0.0,0.0,0.704475,1,0.000000,-0.747766
1,0.0,0.0,0.101791,0,0.000000,0.159774
2,0.0,1.0,-1.132016,0,0.524263,0.610629
3,0.0,0.0,-0.017443,0,0.000000,0.494088
4,0.0,0.0,-1.720923,0,3.028668,1.007387
...,...,...,...,...,...,...
134,1.0,0.0,0.525285,1,0.000000,-0.747766
135,1.0,1.0,0.344965,1,0.000000,-0.747766
136,1.0,0.0,-0.312609,1,0.000000,0.560275
137,1.0,1.0,0.357529,1,0.000000,1.620942
138,1.0,1.0,0.342282,1,0.000000,-0.673255

In [27]:
MAASTRO_new

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,1,0,0.668072,1,0.000026,0
1,0,1,0.669961,1,0.000167,20
2,0,1,0.624081,1,0.000057,6
3,0,1,0.577624,0,0.000000,45
4,1,0,0.630933,1,0.000000,59
...,...,...,...,...,...,...
94,0,1,0.671754,0,0.000000,55
95,0,1,0.632189,0,0.000000,174
96,1,1,0.645548,1,0.000000,0
97,1,0,0.727488,1,0.000000,0
98,0,1,0.672838,0,0.000000,40

In [28]:
MAASTRO_new_std

,hpv_related,uicc8_III-IV,shape_Sphericity,oropharynx,LBP_102_PET,pack_years
0,1,0,-0.170593,1,0.398737,-0.747766
1,0,1,-0.152832,1,2.544568,-0.085444
2,0,1,-0.584101,1,0.869691,-0.549070
3,0,1,-1.020797,0,0.000000,0.742458
4,1,0,-0.519690,1,0.000000,1.206084
...,...,...,...,...,...,...
94,0,1,-0.135979,0,0.000000,1.073619
95,0,1,-0.507883,0,0.000000,5.014436
96,1,1,-0.382318,1,0.000000,-0.747766
97,1,0,0.387916,1,0.000000,-0.747766
98,0,1,-0.125793,0,0.000000,0.576878

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [29]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:13,839] A new study created in memory with name: no-name-13674658-0219-4cbd-aaf4-447381815ed8

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7946428571428571

[I 2024-04-19 14:32:21,239] A new study created in memory with name: no-name-b20e5e83-0fa6-4158-bb7a-2d16a468160b

Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:21,220] Trial 0 finished with value: 0.7737571035318616 and parameters: {}. Best is trial 0 with value: 0.7737571035318616.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7737571035318616], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 14, 133870), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 21, 219469), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7737571035318616

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1373367791207223
Fold 2 IBS: 0.17153895698332647
Fold 3 IBS: 0.18224864083271736
Fold 4 IBS: 0.18669684505649792
Fold 5 IBS: 0.22978024900389662
[I 2024-04-19 14:32:21,611] Trial 0 finished with value: 0.1815202941994321 and parameters: {}. Best is trial 0 with value: 0.1815202941994321.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1815202941994321], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 21, 275452), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 21, 610999), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1815202941994321

In [30]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.774
train_ibs:  0.182

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.587
IBS score: 0.278

In [34]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [35]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:22,372] A new study created in memory with name: no-name-a6b0fcf1-f098-4082-831e-73b8f6d50901

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-19 14:32:22,654] A new study created in memory with name: no-name-716049f5-6614-4379-a550-d6e5f7898c03

Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6924882629107981
[I 2024-04-19 14:32:22,648] Trial 0 finished with value: 0.6914921458340058 and parameters: {}. Best is trial 0 with value: 0.6914921458340058.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6914921458340058], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 22, 428441), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 22, 648269), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6914921458340058

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2139765170081932
Fold 2 IBS: 0.22157791027035073
Fold 3 IBS: 0.20453594896703353
Fold 4 IBS: 0.2247380375796925
Fold 5 IBS: 0.2181243109094921
[I 2024-04-19 14:32:22,983] Trial 0 finished with value: 0.21659054494695237 and parameters: {}. Best is trial 0 with value: 0.21659054494695237.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054494695237], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 22, 745361), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 22, 983244), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054494695237

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.691
train_ibs:  0.217

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.558

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:23,624] A new study created in memory with name: no-name-619d60c6-f71e-4f41-a103-65df373ddd27

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798

[I 2024-04-19 14:32:24,116] A new study created in memory with name: no-name-1dbdf3da-708a-484d-8e4a-f1617fceb1eb

Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:24,104] Trial 0 finished with value: 0.7729788376800661 and parameters: {}. Best is trial 0 with value: 0.7729788376800661.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7729788376800661], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 23, 720353), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 24, 104027), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7729788376800661

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1379525564764891
Fold 2 IBS: 0.17259998000254334
Fold 3 IBS: 0.18072683268151377
Fold 4 IBS: 0.18569936734572245
Fold 5 IBS: 0.22816096227886445
[I 2024-04-19 14:32:24,768] Trial 0 finished with value: 0.18102793975702663 and parameters: {}. Best is trial 0 with value: 0.18102793975702663.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18102793975702663], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 24, 189204), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 24, 768195), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18102793975702663

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.773
train_ibs:  0.181

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.59

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.273

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:32:25,251] A new study created in memory with name: no-name-9e6e320c-b9aa-4b05-9a1d-f08dcb0388cf

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:25,849] Trial 0 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7720859805372091.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:26,334] Trial 1 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7720859805372091.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:26,901] Trial 2 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.7721735155512147.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:27,291] Trial 3 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.7721735155512147.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:27,645] Trial 4 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.7721735155512147.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:28,164] Trial 5 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.7721735155512147.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:28,676] Trial 6 finished with value: 0.7729788376800661 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:29,396] Trial 7 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:30,112] Trial 8 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:30,861] Trial 9 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:31,319] Trial 10 finished with value: 0.7729788376800661 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:32,098] Trial 11 finished with value: 0.7729788376800661 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:32,667] Trial 12 finished with value: 0.7729788376800661 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:33,233] Trial 13 finished with value: 0.7719984455232034 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.7729788376800661.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:34,010] Trial 14 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:32:34,187] Trial 15 finished with value: 0.6938818293002219 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:32:34,334] Trial 16 finished with value: 0.6938818293002219 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:34,905] Trial 17 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.1989440786901095}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:35,642] Trial 18 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.13163248337204814}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:36,100] Trial 19 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.11710798977210826}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:36,622] Trial 20 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.11991364850596369}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:37,425] Trial 21 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.11508371095417902}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:37,980] Trial 22 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.3004259280835774}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:38,583] Trial 23 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.1124690541840564}. Best is trial 14 with value: 0.7730663726940719.

Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:39,364] Trial 24 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.17175907635020055}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:40,118] Trial 25 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.3033674563887191}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:41,480] Trial 26 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.07348485814554673}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:42,164] Trial 27 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.2401444883273624}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:42,830] Trial 28 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.37132291705385245}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:43,531] Trial 29 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.06482816083620058}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:44,125] Trial 30 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.17105869390939887}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:44,775] Trial 31 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.1130786932348311}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:45,453] Trial 32 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.0590523030616818}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:46,061] Trial 33 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.24797739277896408}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:46,994] Trial 34 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:47,981] Trial 35 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.3349958381129322}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:49,598] Trial 36 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.5411641129675752}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:51,571] Trial 37 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.11818787729675109}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:52,559] Trial 38 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.27008968462240884}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:53,839] Trial 39 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:55,306] Trial 40 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.693737464241221}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:55,806] Trial 41 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.11577418005988488}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:56,747] Trial 42 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.21460182535570804}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:57,618] Trial 43 finished with value: 0.7192004074357015 and parameters: {'l1_ratio': 0.038058811550811394}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:32:58,919] Trial 44 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.14669042112442024}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:00,065] Trial 45 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.085657465721598}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:01,129] Trial 46 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.21133087403092338}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:01,542] Trial 47 finished with value: 0.7192004074357015 and parameters: {'l1_ratio': 0.026777384016078057}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312

Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:02,148] Trial 48 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:03,054] Trial 49 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.1545469903233332}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:03,480] Trial 50 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:04,146] Trial 51 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.06347035003891145}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:04,578] Trial 52 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.10357602924835954}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:33:04,697] Trial 53 finished with value: 0.6938818293002219 and parameters: {'l1_ratio': 0.002427106063338999}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:05,099] Trial 54 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.05804748144593171}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:05,777] Trial 55 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.14105803527266514}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:06,848] Trial 56 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.1913835152401668}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:07,593] Trial 57 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.26688630567674976}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:08,892] Trial 58 finished with value: 0.7469060351413292 and parameters: {'l1_ratio': 0.0402625586289817}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:09,498] Trial 59 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.08701756275960781}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:09,820] Trial 60 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.13831035640514766}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:10,365] Trial 61 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.09784884480011165}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:11,085] Trial 62 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.19546522751273815}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:11,595] Trial 63 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.12814313047139508}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:12,130] Trial 64 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.23009826843084052}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:12,707] Trial 65 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.3357491630525026}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:13,257] Trial 66 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.174845554796585}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:13,725] Trial 67 finished with value: 0.7729788376800661 and parameters: {'l1_ratio': 0.9415445204645163}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:14,231] Trial 68 finished with value: 0.7192004074357015 and parameters: {'l1_ratio': 0.03798110237495479}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:15,034] Trial 69 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.08504553854768994}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:15,580] Trial 70 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.16740982618413716}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:16,026] Trial 71 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.060691414587805}. Best is trial 14 with value: 0.7730663726940719.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:16,384] Trial 72 finished with value: 0.7058075502928444 and parameters: {'l1_ratio': 0.01661694712208961}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:17,477] Trial 73 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.11401738190254039}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:18,331] Trial 74 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.06536467186294007}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:19,111] Trial 75 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.1353111182678217}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:19,996] Trial 76 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.10343416846806248}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:20,694] Trial 77 finished with value: 0.7469060351413292 and parameters: {'l1_ratio': 0.04030628336692056}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:33:20,914] Trial 78 finished with value: 0.6938818293002219 and parameters: {'l1_ratio': 0.00022754140067660078}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:21,639] Trial 79 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.23061108705538996}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:22,235] Trial 80 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.19280710873509518}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:22,818] Trial 81 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.11538201164645659}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:23,358] Trial 82 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.07503256275627598}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:23,827] Trial 83 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.1618153774196507}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:24,272] Trial 84 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.13340475141961683}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:24,694] Trial 85 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:25,214] Trial 86 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.052602226728183835}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:25,690] Trial 87 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.09306982152259317}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:26,144] Trial 88 finished with value: 0.7192004074357015 and parameters: {'l1_ratio': 0.02716491169515256}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:26,550] Trial 89 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.26069536651704683}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:27,370] Trial 90 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.17793707905620115}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:28,056] Trial 91 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.14663738366882823}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:28,669] Trial 92 finished with value: 0.7720859805372091 and parameters: {'l1_ratio': 0.11558040491055024}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:29,254] Trial 93 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.1512405586739107}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:29,771] Trial 94 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.2143011540610461}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:30,286] Trial 95 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.07709575140405084}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7794117647058824

Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:30,804] Trial 96 finished with value: 0.771193123394352 and parameters: {'l1_ratio': 0.28889705370132207}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:31,314] Trial 97 finished with value: 0.7721735155512147 and parameters: {'l1_ratio': 0.12502702974381275}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:31,814] Trial 98 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.09049059108619213}. Best is trial 14 with value: 0.7730663726940719.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798

[I 2024-04-19 14:33:32,424] A new study created in memory with name: no-name-4efa4d0a-4430-4888-a0fa-3fb857f8f0ea

Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:33:32,413] Trial 99 finished with value: 0.7730663726940719 and parameters: {'l1_ratio': 0.051531122336805416}. Best is trial 14 with value: 0.7730663726940719.


* Best trial for C-index:
 FrozenTrial(number=14, state=TrialState.COMPLETE, values=[0.7730663726940719], datetime_start=datetime.datetime(2024, 4, 19, 14, 32, 33, 253707), datetime_complete=datetime.datetime(2024, 4, 19, 14, 32, 34, 10011), params={'l1_ratio': 0.1015556329868651}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=14, value=None)


* Best Score for C-index:
 0.7730663726940719

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.13797076460579477
Fold 2 IBS: 0.17237767238545068
Fold 3 IBS: 0.1806649161740025
Fold 4 IBS: 0.18572867986550837
Fold 5 IBS: 0.22808900243690983
[I 2024-04-19 14:33:32,939] Trial 0 finished with value: 0.18096620709353323 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.18096620709353323.
Fold 1 IBS: 0.13797371195892438
Fold 2 IBS: 0.17327116971653533
Fold 3 IBS: 0.18062869781956573
Fold 4 IBS: 0.18575912095842703
Fold 5 IBS: 0.22793075681445532
[I 2024-04-19 14:33:33,502] Trial 1 finished with value: 0.18111269145358155 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.18096620709353323.
Fold 1 IBS: 0.1379785930621418
Fold 2 IBS: 0.17333767103026063
Fold 3 IBS: 0.18054443579449886
Fold 4 IBS: 0.18574442131862182
Fold 5 IBS: 0.22799850336404315
[I 2024-04-19 14:33:33,927] Trial 2 finished with value: 0.18112072491391323 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.18096620709353323.
Fold 1 IBS: 0.13795157855953824
Fold 2 IBS: 0.17272567487575993
Fold 3 IBS: 0.18055448481994557
Fold 4 IBS: 0.18573966337862513
Fold 5 IBS: 0.22797605494931875
[I 2024-04-19 14:33:34,884] Trial 3 finished with value: 0.1809894913166375 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.18096620709353323.
Fold 1 IBS: 0.13795732175923017
Fold 2 IBS: 0.1722899071629329
Fold 3 IBS: 0.18057512420675426
Fold 4 IBS: 0.185749810532854
Fold 5 IBS: 0.22814540830717253
[I 2024-04-19 14:33:35,842] Trial 4 finished with value: 0.18094351439378878 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.18094351439378878.
Fold 1 IBS: 0.1379553001887805
Fold 2 IBS: 0.17303152398381183
Fold 3 IBS: 0.18054358933521666
Fold 4 IBS: 0.18571954991974027
Fold 5 IBS: 0.22797280451572177
[I 2024-04-19 14:33:36,572] Trial 5 finished with value: 0.1810445535886542 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.18094351439378878.
Fold 1 IBS: 0.13795960229987536
Fold 2 IBS: 0.1725758062969932
Fold 3 IBS: 0.18069183954448526
Fold 4 IBS: 0.18568731798766
Fold 5 IBS: 0.22812428988392125
[I 2024-04-19 14:33:37,061] Trial 6 finished with value: 0.181007771202587 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 4 with value: 0.18094351439378878.
Fold 1 IBS: 0.13797789231130042
Fold 2 IBS: 0.17236341969842095
Fold 3 IBS: 0.18063592122806135
Fold 4 IBS: 0.18571749541039842
Fold 5 IBS: 0.22805823853094898
[I 2024-04-19 14:33:37,639] Trial 7 finished with value: 0.18095059343582603 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 4 with value: 0.18094351439378878.
Fold 1 IBS: 0.13795418754232533
Fold 2 IBS: 0.17285554084698068
Fold 3 IBS: 0.18061641031106004
Fold 4 IBS: 0.1857278911887935
Fold 5 IBS: 0.2280434825472311
[I 2024-04-19 14:33:38,166] Trial 8 finished with value: 0.18103950248727813 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 4 with value: 0.18094351439378878.
Fold 1 IBS: 0.1379339938164456
Fold 2 IBS: 0.17308986516861474
Fold 3 IBS: 0.1805636405177133
Fold 4 IBS: 0.1857472316423774
Fold 5 IBS: 0.2279952772830529
[I 2024-04-19 14:33:38,862] Trial 9 finished with value: 0.18106600168564077 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 4 with value: 0.18094351439378878.
Fold 1 IBS: 0.1379582670659085
Fold 2 IBS: 0.17258037610141336
Fold 3 IBS: 0.1806984644850036
Fold 4 IBS: 0.1856895997358231
Fold 5 IBS: 0.22813123396543852
[I 2024-04-19 14:33:39,546] Trial 10 finished with value: 0.18101158827071742 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 4 with value: 0.18094351439378878.
Fold 1 IBS: 0.1379515958057898
Fold 2 IBS: 0.17222184078878877
Fold 3 IBS: 0.18060030889686557
Fold 4 IBS: 0.18567334378522993
Fold 5 IBS: 0.22801774199382854
[I 2024-04-19 14:33:40,066] Trial 11 finished with value: 0.1808929662541005 and parameters: {'l1_ratio': 0.729739426971179}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795496810827163
Fold 2 IBS: 0.17223945676066713
Fold 3 IBS: 0.18058556158551345
Fold 4 IBS: 0.18575351641088178
Fold 5 IBS: 0.22800184886789635
[I 2024-04-19 14:33:40,563] Trial 12 finished with value: 0.18090707034664605 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379656916925634
Fold 2 IBS: 0.1723680520785685
Fold 3 IBS: 0.1806608840337396
Fold 4 IBS: 0.18574862323660563
Fold 5 IBS: 0.22807889097930822
[I 2024-04-19 14:33:41,554] Trial 13 finished with value: 0.18096442840415705 and parameters: {'l1_ratio': 0.8201470233818768}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796512377469822
Fold 2 IBS: 0.17355705062588148
Fold 3 IBS: 0.18057385300523715
Fold 4 IBS: 0.18574859558569565
Fold 5 IBS: 0.2280277172383097
[I 2024-04-19 14:33:42,518] Trial 14 finished with value: 0.18117446804596443 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795683622112917
Fold 2 IBS: 0.17239433064252388
Fold 3 IBS: 0.180700617813519
Fold 4 IBS: 0.1856768822939019
Fold 5 IBS: 0.22812101825842337
[I 2024-04-19 14:33:43,061] Trial 15 finished with value: 0.18096993704589945 and parameters: {'l1_ratio': 0.8389443966320497}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379252977585932
Fold 2 IBS: 0.1726015166159584
Fold 3 IBS: 0.1806602557091021
Fold 4 IBS: 0.18569759285704626
Fold 5 IBS: 0.2280867324760968
[I 2024-04-19 14:33:43,450] Trial 16 finished with value: 0.18099427908335936 and parameters: {'l1_ratio': 0.5865650657568056}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795612611953378
Fold 2 IBS: 0.17239644567703766
Fold 3 IBS: 0.18070380854282106
Fold 4 IBS: 0.185678091987842
Fold 5 IBS: 0.2281244003724601
[I 2024-04-19 14:33:44,069] Trial 17 finished with value: 0.1809717745399389 and parameters: {'l1_ratio': 0.8404875022955411}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796543362838443
Fold 2 IBS: 0.17258074018522038
Fold 3 IBS: 0.18058651083942004
Fold 4 IBS: 0.18572660111502387
Fold 5 IBS: 0.22800808972358486
[I 2024-04-19 14:33:44,593] Trial 18 finished with value: 0.1809734750983267 and parameters: {'l1_ratio': 0.6117132794623986}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13793233919014158
Fold 2 IBS: 0.172287672759039
Fold 3 IBS: 0.18068692693718894
Fold 4 IBS: 0.1857064842720987
Fold 5 IBS: 0.2281096508235473
[I 2024-04-19 14:33:45,779] Trial 19 finished with value: 0.18094461479640309 and parameters: {'l1_ratio': 0.7667069175591638}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13792510032718422
Fold 2 IBS: 0.17248743746738987
Fold 3 IBS: 0.18070817497170166
Fold 4 IBS: 0.18573051674986207
Fold 5 IBS: 0.2281452899411396
[I 2024-04-19 14:33:46,555] Trial 20 finished with value: 0.1809993038914555 and parameters: {'l1_ratio': 0.9136727860846251}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796345834252485
Fold 2 IBS: 0.17231120208293058
Fold 3 IBS: 0.1806946773061022
Fold 4 IBS: 0.18574015670813213
Fold 5 IBS: 0.2281188285241434
[I 2024-04-19 14:33:47,418] Trial 21 finished with value: 0.18096566459276664 and parameters: {'l1_ratio': 0.708821341587738}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794378996436288
Fold 2 IBS: 0.17252267093617224
Fold 3 IBS: 0.1806747791530694
Fold 4 IBS: 0.1856760554286823
Fold 5 IBS: 0.22810009005112908
[I 2024-04-19 14:33:48,117] Trial 22 finished with value: 0.18098347710668317 and parameters: {'l1_ratio': 0.6440782750334072}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379450468230872
Fold 2 IBS: 0.1722532472939405
Fold 3 IBS: 0.18062942308171556
Fold 4 IBS: 0.1856844861177594
Fold 5 IBS: 0.2280486449597099
[I 2024-04-19 14:33:48,552] Trial 23 finished with value: 0.18091216965524254 and parameters: {'l1_ratio': 0.7418014829840944}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13798325824122462
Fold 2 IBS: 0.17231645314032754
Fold 3 IBS: 0.180582607012717
Fold 4 IBS: 0.18572132215854498
Fold 5 IBS: 0.22815077292399893
[I 2024-04-19 14:33:49,044] Trial 24 finished with value: 0.1809508826953626 and parameters: {'l1_ratio': 0.7851498838067288}. Best is trial 11 with value: 0.1808929662541005.

Fold 1 IBS: 0.1379339545809031
Fold 2 IBS: 0.17245799283377966
Fold 3 IBS: 0.1806645318212113
Fold 4 IBS: 0.18571532257538148
Fold 5 IBS: 0.22809951388565317
[I 2024-04-19 14:33:49,612] Trial 25 finished with value: 0.18097426313938575 and parameters: {'l1_ratio': 0.891573855041803}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379542845650902
Fold 2 IBS: 0.17275025042442463
Fold 3 IBS: 0.18068891302173123
Fold 4 IBS: 0.185735417795691
Fold 5 IBS: 0.22796451924283198
[I 2024-04-19 14:33:50,123] Trial 26 finished with value: 0.18101867700995383 and parameters: {'l1_ratio': 0.5479632818643458}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.21317323573569238
Fold 2 IBS: 0.22046998099861367
Fold 3 IBS: 0.18062771724693177
Fold 4 IBS: 0.22411935984071088
Fold 5 IBS: 0.22793413168944957
[I 2024-04-19 14:33:50,539] Trial 27 finished with value: 0.21326488510227964 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794831406600597
Fold 2 IBS: 0.17282844536512287
Fold 3 IBS: 0.18063798737744707
Fold 4 IBS: 0.18573709342459369
Fold 5 IBS: 0.22806643217482792
[I 2024-04-19 14:33:51,069] Trial 28 finished with value: 0.18104365448159948 and parameters: {'l1_ratio': 0.48729150312932057}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794367757584045
Fold 2 IBS: 0.172258526696051
Fold 3 IBS: 0.18063636536032654
Fold 4 IBS: 0.18568714253616214
Fold 5 IBS: 0.22805601218576418
[I 2024-04-19 14:33:51,582] Trial 29 finished with value: 0.18091634487082886 and parameters: {'l1_ratio': 0.7447306188753937}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794359455594735
Fold 2 IBS: 0.1725213205187053
Fold 3 IBS: 0.18067557178756988
Fold 4 IBS: 0.18567638731567981
Fold 5 IBS: 0.2281009319779931
[I 2024-04-19 14:33:52,075] Trial 30 finished with value: 0.1809835612311791 and parameters: {'l1_ratio': 0.6443828448381688}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794535135968797
Fold 2 IBS: 0.17225227472081694
Fold 3 IBS: 0.1806280679423995
Fold 4 IBS: 0.18568396756145383
Fold 5 IBS: 0.2280472067992582
[I 2024-04-19 14:33:52,462] Trial 31 finished with value: 0.18091137367672327 and parameters: {'l1_ratio': 0.7412321246739983}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796622919396592
Fold 2 IBS: 0.17233081229138797
Fold 3 IBS: 0.180683383927832
Fold 4 IBS: 0.18573580200955275
Fold 5 IBS: 0.22810683864956754
[I 2024-04-19 14:33:52,941] Trial 32 finished with value: 0.18096461321446125 and parameters: {'l1_ratio': 0.7040996569746504}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13792621685529532
Fold 2 IBS: 0.17248371202192156
Fold 3 IBS: 0.1807026641391693
Fold 4 IBS: 0.18572859847329784
Fold 5 IBS: 0.22813951119968198
[I 2024-04-19 14:33:53,508] Trial 33 finished with value: 0.18099614053787322 and parameters: {'l1_ratio': 0.9108283058505737}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13797568118899317
Fold 2 IBS: 0.1723386237534851
Fold 3 IBS: 0.18061618871625174
Fold 4 IBS: 0.18573322268986744
Fold 5 IBS: 0.22803148042931926
[I 2024-04-19 14:33:53,921] Trial 34 finished with value: 0.18093903935558334 and parameters: {'l1_ratio': 0.7998883635837057}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13793278558528857
Fold 2 IBS: 0.1724538317383371
Fold 3 IBS: 0.18057563581223124
Fold 4 IBS: 0.18569477203381846
Fold 5 IBS: 0.22799399020899286
[I 2024-04-19 14:33:54,627] Trial 35 finished with value: 0.18093020307573365 and parameters: {'l1_ratio': 0.6616703524903292}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13793716006411633
Fold 2 IBS: 0.17312378327486228
Fold 3 IBS: 0.18064659761487784
Fold 4 IBS: 0.18573730121374518
Fold 5 IBS: 0.2279290313733695
[I 2024-04-19 14:33:55,184] Trial 36 finished with value: 0.18107477470819422 and parameters: {'l1_ratio': 0.34583284155425353}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796461639457366
Fold 2 IBS: 0.1727028762221368
Fold 3 IBS: 0.18065075300466601
Fold 4 IBS: 0.185719231274531
Fold 5 IBS: 0.228078434243221
[I 2024-04-19 14:33:56,132] Trial 37 finished with value: 0.1810231822278257 and parameters: {'l1_ratio': 0.5353552334072459}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379474246400222
Fold 2 IBS: 0.17241361519638804
Fold 3 IBS: 0.18059861054173657
Fold 4 IBS: 0.18569293363101097
Fold 5 IBS: 0.22818507546051173
[I 2024-04-19 14:33:56,964] Trial 38 finished with value: 0.1809675318939339 and parameters: {'l1_ratio': 0.8598478847078105}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379511864242215
Fold 2 IBS: 0.17222256062866953
Fold 3 IBS: 0.1806021271388674
Fold 4 IBS: 0.1856740397420223
Fold 5 IBS: 0.22801967226543562
[I 2024-04-19 14:33:57,724] Trial 39 finished with value: 0.18089391723984327 and parameters: {'l1_ratio': 0.7304824129775314}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13792409941867909
Fold 2 IBS: 0.17264891304685864
Fold 3 IBS: 0.18066509613605505
Fold 4 IBS: 0.18569963383568536
Fold 5 IBS: 0.22809187571519365
[I 2024-04-19 14:33:58,378] Trial 40 finished with value: 0.18100592363049434 and parameters: {'l1_ratio': 0.5882729555579936}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794207650098936
Fold 2 IBS: 0.1722643169990342
Fold 3 IBS: 0.1806434945530728
Fold 4 IBS: 0.18568987029044734
Fold 5 IBS: 0.2280635771354023
[I 2024-04-19 14:33:59,138] Trial 41 finished with value: 0.1809206670957892 and parameters: {'l1_ratio': 0.7477603074967138}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13797962759667978
Fold 2 IBS: 0.17235203626934448
Fold 3 IBS: 0.18062887414278883
Fold 4 IBS: 0.18571477660421318
Fold 5 IBS: 0.22805075747193843
[I 2024-04-19 14:33:59,883] Trial 42 finished with value: 0.18094521441699296 and parameters: {'l1_ratio': 0.6820853602902013}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795619353540017
Fold 2 IBS: 0.17228173736358535
Fold 3 IBS: 0.18058012642979254
Fold 4 IBS: 0.18575158656297053
Fold 5 IBS: 0.22799607697847182
[I 2024-04-19 14:34:00,533] Trial 43 finished with value: 0.18091314417404408 and parameters: {'l1_ratio': 0.7214933214056996}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13797776275814924
Fold 2 IBS: 0.1725139258158453
Fold 3 IBS: 0.18073709420882708
Fold 4 IBS: 0.18574411882461309
Fold 5 IBS: 0.22818626951702112
[I 2024-04-19 14:34:01,328] Trial 44 finished with value: 0.18103183422489116 and parameters: {'l1_ratio': 0.9343177578718784}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13797914330377486
Fold 2 IBS: 0.17232847659579617
Fold 3 IBS: 0.18060095788704733
Fold 4 IBS: 0.18572778262636894
Fold 5 IBS: 0.22801507669435428
[I 2024-04-19 14:34:01,770] Trial 45 finished with value: 0.1809302874214683 and parameters: {'l1_ratio': 0.7930889705357962}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795903327223633
Fold 2 IBS: 0.17348543131984995
Fold 3 IBS: 0.18057527592870828
Fold 4 IBS: 0.18568813946416515
Fold 5 IBS: 0.22803142028025836
[I 2024-04-19 14:34:02,403] Trial 46 finished with value: 0.18114786005304362 and parameters: {'l1_ratio': 0.21133087403092338}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795948135133776
Fold 2 IBS: 0.17254088652287902
Fold 3 IBS: 0.18061126279464843
Fold 4 IBS: 0.1857362213962828
Fold 5 IBS: 0.22803438532884915
[I 2024-04-19 14:34:02,896] Trial 47 finished with value: 0.18097644747879943 and parameters: {'l1_ratio': 0.6204890152739069}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794652291297188
Fold 2 IBS: 0.17241656882525747
Fold 3 IBS: 0.18060302770420217
Fold 4 IBS: 0.1856944735913846
Fold 5 IBS: 0.2281893362370117
[I 2024-04-19 14:34:03,514] Trial 48 finished with value: 0.18096998585416557 and parameters: {'l1_ratio': 0.8619031648167028}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13792965112726271
Fold 2 IBS: 0.17291700313809077
Fold 3 IBS: 0.18063774199584517
Fold 4 IBS: 0.1856760703049341
Fold 5 IBS: 0.22807164449484507
[I 2024-04-19 14:34:04,149] Trial 49 finished with value: 0.18104642221219558 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794118337236738

Fold 2 IBS: 0.1722673980591959
Fold 3 IBS: 0.18064747294080516
Fold 4 IBS: 0.18569139236793886
Fold 5 IBS: 0.22806779841617478
[I 2024-04-19 14:34:04,590] Trial 50 finished with value: 0.1809230490312964 and parameters: {'l1_ratio': 0.7494606434304015}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796012934285062
Fold 2 IBS: 0.1722875465945281
Fold 3 IBS: 0.18070825626762008
Fold 4 IBS: 0.1857453921322719
Fold 5 IBS: 0.22813324336951613
[I 2024-04-19 14:34:05,280] Trial 51 finished with value: 0.18096691354135735 and parameters: {'l1_ratio': 0.7145748209714864}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796758000120174
Fold 2 IBS: 0.17236247178263364
Fold 3 IBS: 0.18065242499042497
Fold 4 IBS: 0.1857456486956535
Fold 5 IBS: 0.22806991991642278
[I 2024-04-19 14:34:06,273] Trial 52 finished with value: 0.18095960907726732 and parameters: {'l1_ratio': 0.8162426669043343}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13792697652376057
Fold 2 IBS: 0.17240576078866707
Fold 3 IBS: 0.18060108375233758
Fold 4 IBS: 0.1857046740090755
Fold 5 IBS: 0.22802124941237822
[I 2024-04-19 14:34:06,800] Trial 53 finished with value: 0.1809319488972438 and parameters: {'l1_ratio': 0.6713329613747265}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379535509423647
Fold 2 IBS: 0.17222930153135588
Fold 3 IBS: 0.18059162842494386
Fold 4 IBS: 0.18575574886137539
Fold 5 IBS: 0.22800852609658662
[I 2024-04-19 14:34:07,343] Trial 54 finished with value: 0.1809077511713253 and parameters: {'l1_ratio': 0.7262109170412537}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13793263735572603
Fold 2 IBS: 0.1726471968576229
Fold 3 IBS: 0.18063064253736508
Fold 4 IBS: 0.18568571715179044
Fold 5 IBS: 0.22805525785429528
[I 2024-04-19 14:34:07,977] Trial 55 finished with value: 0.18099029035135994 and parameters: {'l1_ratio': 0.5763083404810454}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13797192053637236
Fold 2 IBS: 0.1725319392295772
Fold 3 IBS: 0.18063110894085765
Fold 4 IBS: 0.18566630506215567
Fold 5 IBS: 0.228214009131205
[I 2024-04-19 14:34:08,672] Trial 56 finished with value: 0.18100305658003357 and parameters: {'l1_ratio': 0.9487928053661077}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795810136917824
Fold 2 IBS: 0.1725321798984246
Fold 3 IBS: 0.1806168382452104
Fold 4 IBS: 0.18573838804713103
Fold 5 IBS: 0.22804030736299327
[I 2024-04-19 14:34:09,544] Trial 57 finished with value: 0.1809771629845875 and parameters: {'l1_ratio': 0.622497054899819}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13792900749427356
Fold 2 IBS: 0.17229828822620602
Fold 3 IBS: 0.1807018170016808
Fold 4 IBS: 0.1857121785835994
Fold 5 IBS: 0.22812364211402883
[I 2024-04-19 14:34:09,927] Trial 58 finished with value: 0.1809529866839577 and parameters: {'l1_ratio': 0.7734026256905541}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794443036852275
Fold 2 IBS: 0.17242344641012902
Fold 3 IBS: 0.18061330519107155
Fold 4 IBS: 0.18569805615162566
Fold 5 IBS: 0.22819924818418055
[I 2024-04-19 14:34:10,767] Trial 59 finished with value: 0.1809756972611059 and parameters: {'l1_ratio': 0.8667193314642576}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796592352523138
Fold 2 IBS: 0.17236736653465412
Fold 3 IBS: 0.18065984523594314
Fold 4 IBS: 0.18574825797770667
Fold 5 IBS: 0.22807778935068604
[I 2024-04-19 14:34:11,441] Trial 60 finished with value: 0.18096383652484427 and parameters: {'l1_ratio': 0.8196657511727646}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.1379540313234762
Fold 2 IBS: 0.17223274548877365
Fold 3 IBS: 0.1805894964104149
Fold 4 IBS: 0.1857549920423608
Fold 5 IBS: 0.22800626242783498
[I 2024-04-19 14:34:12,159] Trial 61 finished with value: 0.1809075055385721 and parameters: {'l1_ratio': 0.7253489483774119}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794663023065104
Fold 2 IBS: 0.17224696557382968
Fold 3 IBS: 0.18062237854346996
Fold 4 IBS: 0.18568179038649807
Fold 5 IBS: 0.22804116859187157
[I 2024-04-19 14:34:13,283] Trial 62 finished with value: 0.18090778666526405 and parameters: {'l1_ratio': 0.7388502735738973}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13798582661692443
Fold 2 IBS: 0.17240155913237892
Fold 3 IBS: 0.18060372568800176
Fold 4 IBS: 0.18570569319936467
Fold 5 IBS: 0.22802405507407114
[I 2024-04-19 14:34:13,841] Trial 63 finished with value: 0.1809441719421482 and parameters: {'l1_ratio': 0.672342032379511}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796439046824016
Fold 2 IBS: 0.17231779155245927
Fold 3 IBS: 0.18069087726441221
Fold 4 IBS: 0.18573869147195565
Fold 5 IBS: 0.22811479415962976
[I 2024-04-19 14:34:14,759] Trial 64 finished with value: 0.18096530898333943 and parameters: {'l1_ratio': 0.707226204954347}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13793153521016852
Fold 2 IBS: 0.17229027907204814
Fold 3 IBS: 0.18069051872883932
Fold 4 IBS: 0.1857078579278344
Fold 5 IBS: 0.2281116512983993
[I 2024-04-19 14:34:15,966] Trial 65 finished with value: 0.18094636844745793 and parameters: {'l1_ratio': 0.7683124740594898}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795009114482149
Fold 2 IBS: 0.17222476560954708
Fold 3 IBS: 0.18060699287169885
Fold 4 IBS: 0.1856759021046509
Fold 5 IBS: 0.22802483758859474
[I 2024-04-19 14:34:16,721] Trial 66 finished with value: 0.1808965178638626 and parameters: {'l1_ratio': 0.7324773738130989}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13794222824609054
Fold 2 IBS: 0.17251187102372073
Fold 3 IBS: 0.18068111507667603
Fold 4 IBS: 0.1856787083674633
Fold 5 IBS: 0.22810681977226546
[I 2024-04-19 14:34:17,471] Trial 67 finished with value: 0.18098414849724323 and parameters: {'l1_ratio': 0.6465201446914314}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796783801439216
Fold 2 IBS: 0.17272056108375278
Fold 3 IBS: 0.18063887233280496
Fold 4 IBS: 0.1857141916432627
Fold 5 IBS: 0.22806580379225264
[I 2024-04-19 14:34:18,334] Trial 68 finished with value: 0.18102145337329303 and parameters: {'l1_ratio': 0.531536424890876}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13796031188387564
Fold 2 IBS: 0.1723839951472221
Fold 3 IBS: 0.1806850102345263
Fold 4 IBS: 0.18567096455094775
Fold 5 IBS: 0.22810447276436793
[I 2024-04-19 14:34:19,235] Trial 69 finished with value: 0.18096095091618797 and parameters: {'l1_ratio': 0.8314691665369074}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13797829801480657
Fold 2 IBS: 0.17262270754237563
Fold 3 IBS: 0.18068128791379678
Fold 4 IBS: 0.18570646115947226
Fold 5 IBS: 0.22810907947649445
[I 2024-04-19 14:34:20,224] Trial 70 finished with value: 0.18101956682138912 and parameters: {'l1_ratio': 0.5940518975678285}. Best is trial 11 with value: 0.1808929662541005.
Fold 1 IBS: 0.13795253604802904
Fold 2 IBS: 0.17222202010460633
Fold 3 IBS: 0.18059613373353342
Fold 4 IBS: 0.18567174563643662
Fold 5 IBS: 0.22801330942055958
[I 2024-04-19 14:34:20,885] Trial 71 finished with value: 0.18089114898863298 and parameters: {'l1_ratio': 0.728038448531083}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13797730098964286
Fold 2 IBS: 0.17233387344727766
Fold 3 IBS: 0.1806089540476748
Fold 4 IBS: 0.18573067696497278
Fold 5 IBS: 0.22802380393262855
[I 2024-04-19 14:34:22,030] Trial 72 finished with value: 0.18093492187643934 and parameters: {'l1_ratio': 0.796693347234838}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13797747993212786
Fold 2 IBS: 0.17236071565436709
Fold 3 IBS: 0.18063759639123048
Fold 4 IBS: 0.18571814167031328
Fold 5 IBS: 0.22806001675980145
[I 2024-04-19 14:34:23,051] Trial 73 finished with value: 0.18095079008156806 and parameters: {'l1_ratio': 0.6855241041920943}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379558883402946
Fold 2 IBS: 0.1722795257410006
Fold 3 IBS: 0.1805814798754941
Fold 4 IBS: 0.18575206715100906
Fold 5 IBS: 0.22799751431197546
[I 2024-04-19 14:34:24,131] Trial 74 finished with value: 0.18091329508395476 and parameters: {'l1_ratio': 0.7220351615184883}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13793222335368288

Fold 2 IBS: 0.17228804826669653
Fold 3 IBS: 0.18068744438450812
Fold 4 IBS: 0.18570668216898698
Fold 5 IBS: 0.22811019959471515
[I 2024-04-19 14:34:24,788] Trial 75 finished with value: 0.18094491955371791 and parameters: {'l1_ratio': 0.7669378472415054}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13795115831753071
Fold 2 IBS: 0.17222261005831627
Fold 3 IBS: 0.18060225198128796
Fold 4 IBS: 0.18567408752668435
Fold 5 IBS: 0.22801980479837397
[I 2024-04-19 14:34:25,553] Trial 76 finished with value: 0.18089398253643868 and parameters: {'l1_ratio': 0.7305334769066221}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13793924934409754
Fold 2 IBS: 0.17249122456910568
Fold 3 IBS: 0.18069320770917602
Fold 4 IBS: 0.18568377175417458
Fold 5 IBS: 0.22811966221055005
[I 2024-04-19 14:34:26,330] Trial 77 finished with value: 0.18098542311742077 and parameters: {'l1_ratio': 0.6512273624253421}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13796730530823723
Fold 2 IBS: 0.1723482650058066
Fold 3 IBS: 0.1806790001064125
Fold 4 IBS: 0.1857341114965444
Fold 5 IBS: 0.22810218388461453
[I 2024-04-19 14:34:26,919] Trial 78 finished with value: 0.18096617316032307 and parameters: {'l1_ratio': 0.702282075995447}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13798181968160264
Fold 2 IBS: 0.17232065205767616
Fold 3 IBS: 0.1805890197724806
Fold 4 IBS: 0.18572358003928488
Fold 5 IBS: 0.22815703596556622
[I 2024-04-19 14:34:28,188] Trial 79 finished with value: 0.1809544215033221 and parameters: {'l1_ratio': 0.7879080109423557}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379443541214229
Fold 2 IBS: 0.17268260486478587
Fold 3 IBS: 0.18058348592961915
Fold 4 IBS: 0.18575101069694577
Fold 5 IBS: 0.22800688589379212
[I 2024-04-19 14:34:29,305] Trial 80 finished with value: 0.18099366830131317 and parameters: {'l1_ratio': 0.5606272953641664}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379480392414039
Fold 2 IBS: 0.17223885262474803
Fold 3 IBS: 0.18061611275167275
Fold 4 IBS: 0.18567939250099927
Fold 5 IBS: 0.22803451817883297
[I 2024-04-19 14:34:30,516] Trial 81 finished with value: 0.18090338305953138 and parameters: {'l1_ratio': 0.7362429617875076}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13795828555338616
Fold 2 IBS: 0.17253334257081265
Fold 3 IBS: 0.18061609398042
Fold 4 IBS: 0.18573809882899764
Fold 5 IBS: 0.2280395168567712
[I 2024-04-19 14:34:31,734] Trial 82 finished with value: 0.18097706755807752 and parameters: {'l1_ratio': 0.6222283269617681}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13797555036317632
Fold 2 IBS: 0.17234804960730649
Fold 3 IBS: 0.1806454370646509
Fold 4 IBS: 0.18572116637715044
Fold 5 IBS: 0.22806833935658458
[I 2024-04-19 14:34:33,038] Trial 83 finished with value: 0.18095170855377374 and parameters: {'l1_ratio': 0.688641997981858}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13794581760962107
Fold 2 IBS: 0.17225081035651182
Fold 3 IBS: 0.1806259934481757
Fold 4 IBS: 0.18568317372419027
Fold 5 IBS: 0.2280450051684064
[I 2024-04-19 14:34:34,286] Trial 84 finished with value: 0.18091016006138105 and parameters: {'l1_ratio': 0.7403620492035949}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13795187755998367
Fold 2 IBS: 0.17240912428929275
Fold 3 IBS: 0.18071268191478893
Fold 4 IBS: 0.18568533431168596
Fold 5 IBS: 0.22814283032753688
[I 2024-04-19 14:34:35,850] Trial 85 finished with value: 0.18098036968065764 and parameters: {'l1_ratio': 0.8498347754459898}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13797232005735324
Fold 2 IBS: 0.172348499879112
Fold 3 IBS: 0.18063121216638794
Fold 4 IBS: 0.18573818741608863
Fold 5 IBS: 0.22804741930644348
[I 2024-04-19 14:34:37,254] Trial 86 finished with value: 0.18094752776507705 and parameters: {'l1_ratio': 0.8065969132681898}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13795130574778344
Fold 2 IBS: 0.17222235078980264
Fold 3 IBS: 0.1806015971473974
Fold 4 IBS: 0.18567383688191472
Fold 5 IBS: 0.22801910962331495
[I 2024-04-19 14:34:38,311] Trial 87 finished with value: 0.18089364003804265 and parameters: {'l1_ratio': 0.7302657033063533}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13793469683061998
Fold 2 IBS: 0.17245553474478117
Fold 3 IBS: 0.18066087933261
Fold 4 IBS: 0.18571405023501167
Fold 5 IBS: 0.22809568172563668
[I 2024-04-19 14:34:39,618] Trial 88 finished with value: 0.18097216857373188 and parameters: {'l1_ratio': 0.8897678952672066}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13793567908840348
Fold 2 IBS: 0.17227681867466996
Fold 3 IBS: 0.1806720152168221
Fold 4 IBS: 0.18570078090559508
Fold 5 IBS: 0.22809383470414737
[I 2024-04-19 14:34:41,261] Trial 89 finished with value: 0.1809358257179276 and parameters: {'l1_ratio': 0.7601054383144153}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379323229878932
Fold 2 IBS: 0.17245058312620948
Fold 3 IBS: 0.18057746180667933
Fold 4 IBS: 0.18569556001381088
Fold 5 IBS: 0.22799615948957755
[I 2024-04-19 14:34:42,563] Trial 90 finished with value: 0.1809304174848341 and parameters: {'l1_ratio': 0.6624300420959587}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13795488066254713
Fold 2 IBS: 0.17223883055115327
Fold 3 IBS: 0.18058594951296966
Fold 4 IBS: 0.18575365414320802
Fold 5 IBS: 0.22800226081472483
[I 2024-04-19 14:34:43,624] Trial 91 finished with value: 0.1809071151369206 and parameters: {'l1_ratio': 0.7238297254162178}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.137973917533896
Fold 2 IBS: 0.17240005423607482
Fold 3 IBS: 0.18065209049451747
Fold 4 IBS: 0.18572373290014335
Fold 5 IBS: 0.22807540111759056
[I 2024-04-19 14:34:44,841] Trial 92 finished with value: 0.18096503925644444 and parameters: {'l1_ratio': 0.6913078543246678}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379258880084861
Fold 2 IBS: 0.17230819105978862
Fold 3 IBS: 0.18070558303649917
Fold 4 IBS: 0.18571687979927642
Fold 5 IBS: 0.22813845017088408
[I 2024-04-19 14:34:46,313] Trial 93 finished with value: 0.1809589984149869 and parameters: {'l1_ratio': 0.7797743230601308}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379508445363758
Fold 2 IBS: 0.17222316194072848
Fold 3 IBS: 0.18060364578632943
Fold 4 IBS: 0.1856746210151699
Fold 5 IBS: 0.2280212844507662
[I 2024-04-19 14:34:47,691] Trial 94 finished with value: 0.18089471154587394 and parameters: {'l1_ratio': 0.7311040155019282}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379384749242306
Fold 2 IBS: 0.17228962452138152
Fold 3 IBS: 0.18065954414820112
Fold 4 IBS: 0.18569601042495884
Fold 5 IBS: 0.22808060539654595
[I 2024-04-19 14:34:48,722] Trial 95 finished with value: 0.1809328518830636 and parameters: {'l1_ratio': 0.7546625818028201}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13794306411424812
Fold 2 IBS: 0.1725176534592885
Fold 3 IBS: 0.18067772362056034
Fold 4 IBS: 0.18567728831784736
Fold 5 IBS: 0.22810321758931534
[I 2024-04-19 14:34:49,774] Trial 96 finished with value: 0.18098378942025195 and parameters: {'l1_ratio': 0.645210999544968}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.13795635147583335
Fold 2 IBS: 0.17339274672613936
Fold 3 IBS: 0.1806123557068116
Fold 4 IBS: 0.18569515138138426
Fold 5 IBS: 0.2279139197105791
[I 2024-04-19 14:34:51,157] Trial 97 finished with value: 0.18111410500014952 and parameters: {'l1_ratio': 0.2367441530189508}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379679637800008
Fold 2 IBS: 0.1723529360175836
Fold 3 IBS: 0.18067631836208337
Fold 4 IBS: 0.18573307727403252
Fold 5 IBS: 0.2280993361682869
[I 2024-04-19 14:34:52,630] Trial 98 finished with value: 0.18096592632039746 and parameters: {'l1_ratio': 0.7011743199470367}. Best is trial 71 with value: 0.18089114898863298.
Fold 1 IBS: 0.1379583440437133
Fold 2 IBS: 0.17238984345164307
Fold 3 IBS: 0.18069384489450205
Fold 4 IBS: 0.18567431438565588
Fold 5 IBS: 0.22811383868784402
[I 2024-04-19 14:34:53,541] Trial 99 finished with value: 0.18096603709267164 and parameters: {'l1_ratio': 0.8356857185324946}. Best is trial 71 with value: 0.18089114898863298.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.18089114898863298], datetime_start=datetime.datetime(2024, 4, 19, 14, 34, 20, 227987), datetime_complete=datetime.datetime(2024, 4, 19, 14, 34, 20, 884944), params={'l1_ratio': 0.728038448531083}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.18089114898863298

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.773
train_ibs:  0.181

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.1015556329868651)

test_cindex : 0.589

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.728038448531083)

test_ibs:  0.273

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:34:54,338] A new study created in memory with name: no-name-57ad5f98-2a45-44b7-a672-a3879b67e009

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:35:02,406] Trial 0 finished with value: 0.7439398371546546 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7439398371546546.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:35:08,717] Trial 1 finished with value: 0.7591482736873416 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7591482736873416.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:35:13,764] Trial 2 finished with value: 0.7606119754868026 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:35:15,385] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:35:17,415] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:35:25,053] Trial 5 finished with value: 0.7603758525566178 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:35:31,514] Trial 6 finished with value: 0.7405153318884403 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:35:34,610] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6830985915492958
[I 2024-04-19 14:35:49,789] Trial 8 finished with value: 0.5366197183098592 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:35:57,636] Trial 9 finished with value: 0.7507634649590724 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:35:58,451] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:01,282] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.11379276107227315, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14507778190604323, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.6784037558685446
[I 2024-04-19 14:36:06,240] Trial 12 finished with value: 0.759657659255699 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.8397501717174567, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1526809711702289, 'warm_start': False}. Best is trial 2 with value: 0.7606119754868026.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:36:18,158] Trial 13 finished with value: 0.7606747453515516 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.4777069141417742, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08255864378493685, 'warm_start': False}. Best is trial 13 with value: 0.7606747453515516.
Fold 1 C-index: 0.8441558441558441
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 14:36:24,659] Trial 14 finished with value: 0.8109248858865415 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.433652139551181, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09639289018164084, 'warm_start': True}. Best is trial 14 with value: 0.8109248858865415.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8059071729957806

Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:36:30,990] Trial 15 finished with value: 0.8120274196000707 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 480, 'oob_score': True, 'max_samples': 0.4470849120697906, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08807762154599924, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:37,388] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20791692251205332, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 14:36:46,394] Trial 17 finished with value: 0.7976464367331724 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.4399216700525951, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09373644341192987, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:36:53,818] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.20703029814340784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 15 with value: 0.8120274196000707.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:36:58,745] Trial 19 finished with value: 0.8265809184741336 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.5423771062394208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004060792657387402, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:37:03,259] Trial 20 finished with value: 0.8129491526995407 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.5530588908263404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012087063184877466, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 14:37:08,843] Trial 21 finished with value: 0.8070713442754045 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 395, 'oob_score': True, 'max_samples': 0.5331904924758448, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002825613326749862, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:37:13,368] Trial 22 finished with value: 0.811168575681622 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 345, 'oob_score': True, 'max_samples': 0.542464108386217, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.059334415549051514, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:37:19,495] Trial 23 finished with value: 0.8039802018637243 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.6910951920927286, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 14:37:23,601] Trial 24 finished with value: 0.8026197460945188 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 366, 'oob_score': True, 'max_samples': 0.7981951741169113, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05493240148875182, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 14:37:31,931] Trial 25 finished with value: 0.8088685620117511 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 438, 'oob_score': True, 'max_samples': 0.34586218128841145, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04420235989758884, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:37:36,546] Trial 26 finished with value: 0.8101588552729314 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 319, 'oob_score': True, 'max_samples': 0.5125743041583606, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12228642345499363, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:37:41,173] Trial 27 finished with value: 0.8083955122916929 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.4008125694786513, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06694268404263193, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:37:47,654] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.28554491078673616, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18644610161808028, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.829004329004329
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.7300469483568075
[I 2024-04-19 14:37:52,688] Trial 29 finished with value: 0.7993114743141945 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.25087036098392035, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8058035714285714

Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:37:59,024] Trial 30 finished with value: 0.7825128767653189 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.5856012699634701, 'max_features': None, 'min_weight_fraction_leaf': 0.029048761893088054, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:05,474] Trial 31 finished with value: 0.810324693825082 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.5365082685042595, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0654723504402752, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:38:10,289] Trial 32 finished with value: 0.8080877103592699 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 338, 'oob_score': True, 'max_samples': 0.6504737764206872, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1172197135916975, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 14:38:14,826] Trial 33 finished with value: 0.8119151002837803 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.5004197933079609, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004045278256424187, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 14:38:18,080] Trial 34 finished with value: 0.8022488262797298 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.7540080692642186, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0026126520645429994, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.859375
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7065727699530516
[I 2024-04-19 14:38:22,513] Trial 35 finished with value: 0.8028133206434165 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.4869028387236237, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03356017213763633, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:30,548] Trial 36 finished with value: 0.8137930345560808 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.5806041358482964, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09878284329225405, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 14:38:36,306] Trial 37 finished with value: 0.8053811675645152 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.5941013680617477, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18331972361078192, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:41,223] Trial 38 finished with value: 0.8130096314364901 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 377, 'oob_score': True, 'max_samples': 0.6475925530300135, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.125647509156449, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:38:48,286] Trial 39 finished with value: 0.8102832688043693 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.7528827145160659, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11956830452103788, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:52,497] Trial 40 finished with value: 0.8119854012611057 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.6258126140944148, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13820665027837545, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:38:56,532] Trial 41 finished with value: 0.8120562955566836 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 427, 'oob_score': True, 'max_samples': 0.6430681875119886, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09513285163974278, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:39:02,809] Trial 42 finished with value: 0.8106579156565784 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.6544563584865999, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16620722985299802, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 14:39:07,152] Trial 43 finished with value: 0.8128223261702938 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 380, 'oob_score': True, 'max_samples': 0.5833432046167292, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07744725117728736, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:39:10,215] Trial 44 finished with value: 0.8240002976181964 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.5629090828815575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.033267077598237715, 'warm_start': True}. Best is trial 19 with value: 0.8265809184741336.

Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:39:11,436] Trial 45 finished with value: 0.8354299997280554 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.7222470002244752, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02758707213523423, 'warm_start': True}. Best is trial 45 with value: 0.8354299997280554.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:39:18,683] Trial 46 finished with value: 0.7621782075607598 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.711033292420012, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03832673976162945, 'warm_start': False}. Best is trial 45 with value: 0.8354299997280554.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:20,254] Trial 47 finished with value: 0.8379758730182945 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.811827965552719, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0397637496684009, 'warm_start': True}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.6784037558685446
[I 2024-04-19 14:39:24,781] Trial 48 finished with value: 0.7783577371004157 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.8593063971491026, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:39:25,783] Trial 49 finished with value: 0.8372202579633127 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.8972484642218534, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0327604324021709, 'warm_start': True}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:26,781] Trial 50 finished with value: 0.8253861622202813 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.9096856594317103, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029307161033806137, 'warm_start': True}. Best is trial 47 with value: 0.8379758730182945.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:39:27,923] Trial 51 finished with value: 0.8389765029741616 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.8986357837935047, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024993977023469782, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:29,332] Trial 52 finished with value: 0.8245203613544803 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.9124850953685916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04879452780445224, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:30,825] Trial 53 finished with value: 0.8337062595342356 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.9694832891754099, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015955854377574904, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:39:32,535] Trial 54 finished with value: 0.8352747469836732 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.9935491799919282, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020146928359000567, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.816017316017316
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.715962441314554
[I 2024-04-19 14:39:33,249] Trial 55 finished with value: 0.8047552793747526 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9708055320222673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2886607381144328, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:39:36,106] Trial 56 finished with value: 0.7638417419837513 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.8678517557171848, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07411749661885492, 'warm_start': False}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:39:36,826] Trial 57 finished with value: 0.8282529435054788 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.9985441496885937, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01901125299992976, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:39:38,095] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.8145341274347522, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:39:39,172] Trial 59 finished with value: 0.8318354232323248 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9516241459944998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05390302950490697, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.

Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:39:44,231] Trial 60 finished with value: 0.7386192570027899 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.8830302677685383, 'max_features': None, 'min_weight_fraction_leaf': 0.02065339921258332, 'warm_start': False}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:39:45,342] Trial 61 finished with value: 0.8246763776662547 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.9409535283967405, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.047223304275625946, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 14:39:45,741] Trial 62 finished with value: 0.8368825259483523 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 80, 'oob_score': False, 'max_samples': 0.9909255399113079, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.060564401380638525, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 14:39:46,040] Trial 63 finished with value: 0.7825978814514832 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 6, 'oob_score': False, 'max_samples': 0.7844442872738223, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07818306234119168, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:39:46,652] Trial 64 finished with value: 0.8252017222471089 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.9918256787191303, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10415283732963354, 'warm_start': True}. Best is trial 51 with value: 0.8389765029741616.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 14:39:47,803] Trial 65 finished with value: 0.850810598717193 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 162, 'oob_score': False, 'max_samples': 0.9251279109757057, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.019010366401718107, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:39:49,274] Trial 66 finished with value: 0.8237692928027791 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 149, 'oob_score': False, 'max_samples': 0.8186797133263478, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0629749207386761, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:39:50,405] Trial 67 finished with value: 0.8469788396322564 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.8893544255690964, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04237609813040883, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:39:51,946] Trial 68 finished with value: 0.8451838938706814 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 171, 'oob_score': False, 'max_samples': 0.8988316045578264, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04015517700521556, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:39:52,962] Trial 69 finished with value: 0.8136234170405224 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 174, 'oob_score': False, 'max_samples': 0.8890913885107056, 'max_features': None, 'min_weight_fraction_leaf': 0.08146316173254077, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:39:55,195] Trial 70 finished with value: 0.8417155531396825 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.8475532039854673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05203981948991963, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:39:56,293] Trial 71 finished with value: 0.8417864474352603 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 208, 'oob_score': False, 'max_samples': 0.8387359054999836, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051012972615410906, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:39:57,355] Trial 72 finished with value: 0.8460911197571948 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.8510701595136323, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04331038965359059, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 14:39:58,541] Trial 73 finished with value: 0.806078855349657 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.843455667095306, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22468940578387384, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:39:59,566] Trial 74 finished with value: 0.8381298968476351 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 166, 'oob_score': False, 'max_samples': 0.7811372579146033, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04577888728654514, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 14:40:00,976] Trial 75 finished with value: 0.8445002610032812 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.77879915845995, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052692419697654425, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:40:02,117] Trial 76 finished with value: 0.8239275810893248 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.9253437470676411, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09157034665642794, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 14:40:03,486] Trial 77 finished with value: 0.818559528099802 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.8452233186529318, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10693595316796478, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7746478873239436
[I 2024-04-19 14:40:05,068] Trial 78 finished with value: 0.8345691951070127 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.8663345910785444, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06998068246155405, 'warm_start': True}. Best is trial 65 with value: 0.850810598717193.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 14:40:06,221] Trial 79 finished with value: 0.8588740048767525 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.9300001709197038, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010539444733445168, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:40:09,779] Trial 80 finished with value: 0.7469622182087312 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9306954403565874, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00944936004342359, 'warm_start': False}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 14:40:10,397] Trial 81 finished with value: 0.847042774426745 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8321608537496396, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05291006399805884, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 14:40:11,218] Trial 82 finished with value: 0.8452599254340548 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 129, 'oob_score': False, 'max_samples': 0.8309783929675763, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057729619505577534, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 14:40:11,855] Trial 83 finished with value: 0.8200841775307183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.7717196481942752, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0875767297078974, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 14:40:12,849] Trial 84 finished with value: 0.8327260084004102 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 127, 'oob_score': False, 'max_samples': 0.8165695024214783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06657177909241849, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 14:40:15,134] Trial 85 finished with value: 0.8102640740650952 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 234, 'oob_score': False, 'max_samples': 0.8728473103783598, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.133559317330891, 'warm_start': True}. Best is trial 79 with value: 0.8588740048767525.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-19 14:40:16,702] Trial 86 finished with value: 0.8614689944763463 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.9236490757653891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010422824460162315, 'warm_start': True}. Best is trial 86 with value: 0.8614689944763463.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 14:40:17,949] Trial 87 finished with value: 0.8622552628889608 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.9017137434558457, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009335947817559209, 'warm_start': True}. Best is trial 87 with value: 0.8622552628889608.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 14:40:18,897] Trial 88 finished with value: 0.8592718913040507 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.9553890504349966, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01343493318439802, 'warm_start': True}. Best is trial 87 with value: 0.8622552628889608.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.812206572769953
[I 2024-04-19 14:40:19,731] Trial 89 finished with value: 0.8708692541993539 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.9504102015210659, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005622697057305325, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.

Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.812206572769953
[I 2024-04-19 14:40:21,234] Trial 90 finished with value: 0.8647159758569469 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.9549690830627591, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0017681714272393418, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:22,237] Trial 91 finished with value: 0.8684591568681477 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.9467174603025613, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.000357919052720701, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:23,148] Trial 92 finished with value: 0.8685081321544648 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.9591642670541899, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.001426642359487633, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 14:40:24,319] Trial 93 finished with value: 0.8693934390317173 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.966922664758307, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009895599648824556, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8169014084507042
[I 2024-04-19 14:40:25,280] Trial 94 finished with value: 0.8649424341690841 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 140, 'oob_score': False, 'max_samples': 0.9609201057168953, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.001468170125009595, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:26,452] Trial 95 finished with value: 0.8676152750116076 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.95795807976842, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009743899191851731, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8309859154929577
[I 2024-04-19 14:40:27,904] Trial 96 finished with value: 0.8651734364307645 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.9538745845573819, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00012379416671484157, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 14:40:29,159] Trial 97 finished with value: 0.8631423511397136 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 112, 'oob_score': False, 'max_samples': 0.9736020641672304, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0007829840722098722, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 14:40:30,381] Trial 98 finished with value: 0.8649741754187209 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 116, 'oob_score': False, 'max_samples': 0.9730526944242506, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0006645944868734748, 'warm_start': True}. Best is trial 89 with value: 0.8708692541993539.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.759493670886076

[I 2024-04-19 14:40:32,992] A new study created in memory with name: no-name-43b912ea-baf2-4d00-b3e9-050b3b768411

Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:40:32,935] Trial 99 finished with value: 0.7497501026375315 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.9633553447224135, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0004913833796426825, 'warm_start': False}. Best is trial 89 with value: 0.8708692541993539.


* Best trial for C-index:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.8708692541993539], datetime_start=datetime.datetime(2024, 4, 19, 14, 40, 18, 907841), datetime_complete=datetime.datetime(2024, 4, 19, 14, 40, 19, 729992), params={'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.9504102015210659, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005622697057305325, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=89, value=None)


* Best Score for C-index:
 0.8708692541993539

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.15503862232024684
Fold 2 IBS: 0.20319522914269622
Fold 3 IBS: 0.16094379999407013
Fold 4 IBS: 0.21722873875655557
Fold 5 IBS: 0.21797473174077578
[I 2024-04-19 14:40:38,828] Trial 0 finished with value: 0.1908762243908689 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.1908762243908689.
Fold 1 IBS: 0.16023986534508597
Fold 2 IBS: 0.19395474779329328
Fold 3 IBS: 0.16031454555886046
Fold 4 IBS: 0.172975897394729
Fold 5 IBS: 0.21839987819842274
[I 2024-04-19 14:40:40,244] Trial 1 finished with value: 0.1811769868580783 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-19 14:40:41,572] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-19 14:40:45,046] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-19 14:40:49,061] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1811769868580783.
Fold 1 IBS: 0.14278358406907793
Fold 2 IBS: 0.19104640617810376
Fold 3 IBS: 0.15974893241908267
Fold 4 IBS: 0.18141967914714624
Fold 5 IBS: 0.22121445756197555
[I 2024-04-19 14:40:54,154] Trial 5 finished with value: 0.17924261187507723 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.161597390642804
Fold 2 IBS: 0.18052431610529135
Fold 3 IBS: 0.1631233125564435
Fold 4 IBS: 0.20510649473259498
Fold 5 IBS: 0.21388060000563539
[I 2024-04-19 14:40:59,712] Trial 6 finished with value: 0.18484642280855385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.2050222602246388
Fold 2 IBS: 0.21196256700109892
Fold 3 IBS: 0.19801617201361535
Fold 4 IBS: 0.21703121438219325
Fold 5 IBS: 0.21483387012842806
[I 2024-04-19 14:41:06,171] Trial 7 finished with value: 0.20937321674999487 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-19 14:41:13,589] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.16227187704741966
Fold 2 IBS: 0.19895001932730885
Fold 3 IBS: 0.16307017198323448
Fold 4 IBS: 0.18243397369874165
Fold 5 IBS: 0.22211493856720746
[I 2024-04-19 14:41:15,921] Trial 9 finished with value: 0.18576819612478243 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-19 14:41:28,001] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.16167166624429669
Fold 2 IBS: 0.19975517981664714
Fold 3 IBS: 0.16217391101285217
Fold 4 IBS: 0.18340741460691287
Fold 5 IBS: 0.22014455054252774
[I 2024-04-19 14:41:30,682] Trial 11 finished with value: 0.1854305444446473 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.17924261187507723.
Fold 1 IBS: 0.15436227307322545
Fold 2 IBS: 0.16812264606605484
Fold 3 IBS: 0.1668135896070915
Fold 4 IBS: 0.18231932534867584
Fold 5 IBS: 0.21206553267457903
[I 2024-04-19 14:41:31,344] Trial 12 finished with value: 0.17673667335392534 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.16382584729538796
Fold 2 IBS: 0.17521532591980685
Fold 3 IBS: 0.15763547423070334
Fold 4 IBS: 0.1717422819826182
Fold 5 IBS: 0.22893054225444412
[I 2024-04-19 14:41:31,860] Trial 13 finished with value: 0.17946989433659208 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.13679579990869306
Fold 2 IBS: 0.19651928520774983
Fold 3 IBS: 0.1694839231074501
Fold 4 IBS: 0.1999193220016897
Fold 5 IBS: 0.2267438646767405
[I 2024-04-19 14:41:37,021] Trial 14 finished with value: 0.18589243898046465 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.6604916334814492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15853645607219177
Fold 2 IBS: 0.20189929103624463
Fold 3 IBS: 0.1608119755898733
Fold 4 IBS: 0.1820464920885326
Fold 5 IBS: 0.21895053955870955
[I 2024-04-19 14:41:39,932] Trial 15 finished with value: 0.18444895086911037 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.9932150048245644, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 12 with value: 0.17673667335392534.

Fold 1 IBS: 0.1593432071804868
Fold 2 IBS: 0.18470339624712676
Fold 3 IBS: 0.16698177556471644
Fold 4 IBS: 0.180792674404145
Fold 5 IBS: 0.20901591888190207
[I 2024-04-19 14:41:44,845] Trial 16 finished with value: 0.18016739445567542 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.3880731320622045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14354526791362227}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1431329027168723
Fold 2 IBS: 0.192606100465973
Fold 3 IBS: 0.16096025503705205
Fold 4 IBS: 0.1800427051718361
Fold 5 IBS: 0.22000275896336244
[I 2024-04-19 14:41:48,309] Trial 17 finished with value: 0.17934894447101918 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7684587619660335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07846592181777899}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15828497701664868
Fold 2 IBS: 0.19094047729173333
Fold 3 IBS: 0.16478431794285392
Fold 4 IBS: 0.18013393126296717
Fold 5 IBS: 0.21372814719524458
[I 2024-04-19 14:41:54,941] Trial 18 finished with value: 0.18157437014188954 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.6155156742664507, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20223993640525578}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.145874799734907
Fold 2 IBS: 0.19006447697293846
Fold 3 IBS: 0.157631315791433
Fold 4 IBS: 0.1823508976780345
Fold 5 IBS: 0.22218523046185243
[I 2024-04-19 14:41:58,330] Trial 19 finished with value: 0.1796213441278331 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.9278494961686778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0609880983110333}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.2139806105643647
Fold 2 IBS: 0.22113198382608237
Fold 3 IBS: 0.20548411196241553
Fold 4 IBS: 0.22540867568268688
Fold 5 IBS: 0.22093604111363307
[I 2024-04-19 14:41:58,825] Trial 20 finished with value: 0.2173882846298365 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15255459851620035}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1428420485538219
Fold 2 IBS: 0.19500500641554602
Fold 3 IBS: 0.16115458912765243
Fold 4 IBS: 0.18061443281138267
Fold 5 IBS: 0.22224502464077223
[I 2024-04-19 14:42:03,274] Trial 21 finished with value: 0.18037222030983507 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.785671932218293, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07161808244089383}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14296405531408032
Fold 2 IBS: 0.19177179514644152
Fold 3 IBS: 0.15927758125915448
Fold 4 IBS: 0.1808847371851522
Fold 5 IBS: 0.22032216222106416
[I 2024-04-19 14:42:10,631] Trial 22 finished with value: 0.17904406622517854 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.7749562798368443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10178877697443975}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14707704217070555
Fold 2 IBS: 0.19296053302861266
Fold 3 IBS: 0.15860815717511959
Fold 4 IBS: 0.1756673928184354
Fold 5 IBS: 0.2186190898465956
[I 2024-04-19 14:42:16,802] Trial 23 finished with value: 0.17858644300789375 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.61065075684492, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11274888594607943}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1549849803727723
Fold 2 IBS: 0.19343051718377605
Fold 3 IBS: 0.16348725920313262
Fold 4 IBS: 0.1777777283451117
Fold 5 IBS: 0.2137533565000379
[I 2024-04-19 14:42:22,899] Trial 24 finished with value: 0.18068676832096614 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.4692800239107102, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12639289502798687}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15718380108809815
Fold 2 IBS: 0.1976454051603366
Fold 3 IBS: 0.16226226891683035
Fold 4 IBS: 0.18080242684221
Fold 5 IBS: 0.2162799050847899
[I 2024-04-19 14:42:29,234] Trial 25 finished with value: 0.182834761418453 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8406026866609635, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24993364534378779}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15771873835489275
Fold 2 IBS: 0.19023382194650093
Fold 3 IBS: 0.16365929792020448
Fold 4 IBS: 0.1787939562959426
Fold 5 IBS: 0.2136831208204194
[I 2024-04-19 14:42:38,286] Trial 26 finished with value: 0.18081778706759205 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 387, 'oob_score': True, 'max_samples': 0.5944888086713157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18694537021299862}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14099386282516427
Fold 2 IBS: 0.19582399906742431
Fold 3 IBS: 0.16050960774816828
Fold 4 IBS: 0.18223942802821255
Fold 5 IBS: 0.22402442658444502
[I 2024-04-19 14:42:45,990] Trial 27 finished with value: 0.18071826485068287 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 478, 'oob_score': False, 'max_samples': 0.7174807745789797, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03664484999616455}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15580004521225302
Fold 2 IBS: 0.20254131551814122
Fold 3 IBS: 0.16107959686305065
Fold 4 IBS: 0.18098672789974116
Fold 5 IBS: 0.2176267905015391
[I 2024-04-19 14:42:51,807] Trial 28 finished with value: 0.18360689519894502 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 329, 'oob_score': False, 'max_samples': 0.9030031356045858, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2406109046286073}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14071536776497978
Fold 2 IBS: 0.19819914620451093
Fold 3 IBS: 0.16575033532308145
Fold 4 IBS: 0.20889881217652972
Fold 5 IBS: 0.22299803183237982
[I 2024-04-19 14:42:57,346] Trial 29 finished with value: 0.18731233866029634 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'max_samples': 0.7845045619974171, 'max_features': None, 'min_weight_fraction_leaf': 0.09855221444207077}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.16002774237581896
Fold 2 IBS: 0.18683558884573473
Fold 3 IBS: 0.16577275045657922
Fold 4 IBS: 0.18096610245297262
Fold 5 IBS: 0.21131585347597298
[I 2024-04-19 14:43:03,832] Trial 30 finished with value: 0.18098360752141568 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.48499476459228075, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17165882318444542}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14661984211302434
Fold 2 IBS: 0.19040617257347817
Fold 3 IBS: 0.15793510062766122
Fold 4 IBS: 0.17751570456376692

Fold 5 IBS: 0.2171431998129361
[I 2024-04-19 14:43:08,614] Trial 31 finished with value: 0.17792400393817337 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.6683617295863028, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11208498314187895}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.14711946655783312
Fold 2 IBS: 0.19006811981061228
Fold 3 IBS: 0.158033991341854
Fold 4 IBS: 0.17821885585463562
Fold 5 IBS: 0.21747675580865514
[I 2024-04-19 14:43:14,025] Trial 32 finished with value: 0.17818343787471802 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.6782402761258088, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10884764482583958}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1474328186504624
Fold 2 IBS: 0.19259498221393614
Fold 3 IBS: 0.15795841613235134
Fold 4 IBS: 0.17745516090691443
Fold 5 IBS: 0.21625626652249946
[I 2024-04-19 14:43:18,802] Trial 33 finished with value: 0.17833952888523275 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.6380124138892346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1189732582125783}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15948385941427884
Fold 2 IBS: 0.18769199521863572
Fold 3 IBS: 0.16403388589269344
Fold 4 IBS: 0.18257947334659205
Fold 5 IBS: 0.21450637597218802
[I 2024-04-19 14:43:23,855] Trial 34 finished with value: 0.18165911796887763 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.6726532177661799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2251916436608714}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1527840160148196
Fold 2 IBS: 0.19361784261961817
Fold 3 IBS: 0.16037241997963297
Fold 4 IBS: 0.17720989960942962
Fold 5 IBS: 0.21567737421089322
[I 2024-04-19 14:43:27,994] Trial 35 finished with value: 0.17993231048687872 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.6958024881475661, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15526578903551527}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.1495804224236111
Fold 2 IBS: 0.19664350123671276
Fold 3 IBS: 0.15980072072200688
Fold 4 IBS: 0.20836388088105945
Fold 5 IBS: 0.2175031377137174
[I 2024-04-19 14:43:33,581] Trial 36 finished with value: 0.18637833259542153 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.5283332481798079, 'max_features': None, 'min_weight_fraction_leaf': 0.044978813116971286}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.17948718327518784
Fold 2 IBS: 0.1855219493025254
Fold 3 IBS: 0.17917885113266052
Fold 4 IBS: 0.1993029074636634
Fold 5 IBS: 0.21034029430841172
[I 2024-04-19 14:43:38,952] Trial 37 finished with value: 0.1907662370964898 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 358, 'oob_score': False, 'max_samples': 0.6276557954964254, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3061039000862159}. Best is trial 12 with value: 0.17673667335392534.
Fold 1 IBS: 0.15661598821174844
Fold 2 IBS: 0.18099374290546613
Fold 3 IBS: 0.16056570273038615
Fold 4 IBS: 0.173520384737327
Fold 5 IBS: 0.2112864793482218
[I 2024-04-19 14:43:40,397] Trial 38 finished with value: 0.17659645958662992 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.5404961912265821, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13164371997111113}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15279702941122428
Fold 2 IBS: 0.1852912041403366
Fold 3 IBS: 0.16254825455165697
Fold 4 IBS: 0.21563451624021923
Fold 5 IBS: 0.22173066711304368
[I 2024-04-19 14:43:42,592] Trial 39 finished with value: 0.18760033429129613 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 65, 'oob_score': True, 'max_samples': 0.5654897132978893, 'max_features': None, 'min_weight_fraction_leaf': 0.17578457681767043}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.21401738267348
Fold 2 IBS: 0.22212281068128384
Fold 3 IBS: 0.20411785316675118
Fold 4 IBS: 0.2250185725596484
Fold 5 IBS: 0.21786510844986806
[I 2024-04-19 14:43:43,679] Trial 40 finished with value: 0.2166283455062063 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.4892253834151762, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35210438834668367}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15673635985911968
Fold 2 IBS: 0.18776720178111944
Fold 3 IBS: 0.1625245998152057
Fold 4 IBS: 0.17509766672928898
Fold 5 IBS: 0.2230481537229173
[I 2024-04-19 14:43:44,637] Trial 41 finished with value: 0.18103479638153022 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.7211499367298436, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13945648129078753}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.16031145123847687
Fold 2 IBS: 0.18489487535508187
Fold 3 IBS: 0.16352949348257792
Fold 4 IBS: 0.1793312795010288
Fold 5 IBS: 0.21962028205847042
[I 2024-04-19 14:43:46,808] Trial 42 finished with value: 0.1815374763271272 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.6618138034584838, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21012440108534947}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.21399267693312002
Fold 2 IBS: 0.2213254436436494
Fold 3 IBS: 0.20493733196399228
Fold 4 IBS: 0.22477485140199815
Fold 5 IBS: 0.21850002024759857
[I 2024-04-19 14:43:51,683] Trial 43 finished with value: 0.2167060648380717 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.5559082679990999, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15763333718597522
Fold 2 IBS: 0.18946498026638786
Fold 3 IBS: 0.1640954832662605
Fold 4 IBS: 0.18057851328055438
Fold 5 IBS: 0.21214817798156052
[I 2024-04-19 14:43:55,352] Trial 44 finished with value: 0.1807840983961477 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.3922116786764539, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12652167060168643}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.14574358301409038
Fold 2 IBS: 0.18520421873321122
Fold 3 IBS: 0.159750763477992
Fold 4 IBS: 0.17678570525615497
Fold 5 IBS: 0.21918320691794135
[I 2024-04-19 14:43:56,948] Trial 45 finished with value: 0.17733349547987798 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 73, 'oob_score': False, 'max_samples': 0.6437769166332294, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.055766377871647954}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.14276448775275122
Fold 2 IBS: 0.18930516812631212
Fold 3 IBS: 0.16189134421049114
Fold 4 IBS: 0.186974329188472
Fold 5 IBS: 0.221627633907641
[I 2024-04-19 14:43:58,514] Trial 46 finished with value: 0.1805125926371335 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.7501920619277364, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005596142934225855}. Best is trial 38 with value: 0.17659645958662992.

Fold 1 IBS: 0.16189795049200065
Fold 2 IBS: 0.2002316521231612
Fold 3 IBS: 0.1632441421719029
Fold 4 IBS: 0.17861160833008888
Fold 5 IBS: 0.21900022601901006
[I 2024-04-19 14:44:01,299] Trial 47 finished with value: 0.18459711582723273 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 130, 'oob_score': True, 'max_samples': 0.5217274207107006, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0488148159561139}. Best is trial 38 with value: 0.17659645958662992.
Fold 1 IBS: 0.15250696953387413
Fold 2 IBS: 0.1814915271847653
Fold 3 IBS: 0.16047524829592633
Fold 4 IBS: 0.17246364113740187
Fold 5 IBS: 0.2120974321417849
[I 2024-04-19 14:44:02,810] Trial 48 finished with value: 0.1758069636587505 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.5834369548668846, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08607344906290776}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.18399137027492896
Fold 2 IBS: 0.14854679599542248
Fold 3 IBS: 0.16343617668803176
Fold 4 IBS: 0.2223773711931148
Fold 5 IBS: 0.22636174662264597
[I 2024-04-19 14:44:03,134] Trial 49 finished with value: 0.18894269215482878 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 4, 'oob_score': False, 'max_samples': 0.4550345699238961, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022622499289481568}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.16455265902707955
Fold 2 IBS: 0.1965083208336287
Fold 3 IBS: 0.16451051522511953
Fold 4 IBS: 0.17728891078135361
Fold 5 IBS: 0.2163079500419723
[I 2024-04-19 14:44:04,471] Trial 50 finished with value: 0.18383367118183075 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.5737944419595882, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08451392510353656}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15071625573830963
Fold 2 IBS: 0.18460734052017344
Fold 3 IBS: 0.16552122466638863
Fold 4 IBS: 0.17102996454525876
Fold 5 IBS: 0.21923820221488102
[I 2024-04-19 14:44:05,201] Trial 51 finished with value: 0.1782225975370023 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 30, 'oob_score': False, 'max_samples': 0.6706911247196152, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0605338406261604}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1445887052296234
Fold 2 IBS: 0.19163667483807043
Fold 3 IBS: 0.15871016442813063
Fold 4 IBS: 0.18096361572381503
Fold 5 IBS: 0.22016081855184566
[I 2024-04-19 14:44:07,964] Trial 52 finished with value: 0.17921199575429703 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.8167276513075985, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09508026921275371}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15128279716921353
Fold 2 IBS: 0.18421225825345372
Fold 3 IBS: 0.16094457240386933
Fold 4 IBS: 0.1747029882196963
Fold 5 IBS: 0.2159672551858531
[I 2024-04-19 14:44:09,490] Trial 53 finished with value: 0.1774219742464172 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7026582320629128, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1408695751577253}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14977274691350523
Fold 2 IBS: 0.18449090096080561
Fold 3 IBS: 0.15838810732867745
Fold 4 IBS: 0.17502499987124556
Fold 5 IBS: 0.2177331567520814
[I 2024-04-19 14:44:10,984] Trial 54 finished with value: 0.17708198236526304 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 71, 'oob_score': False, 'max_samples': 0.702094189676402, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13510300196836886}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.21391367727655866
Fold 2 IBS: 0.22130552686371494
Fold 3 IBS: 0.20466557365274923
Fold 4 IBS: 0.2251461971072556
Fold 5 IBS: 0.21815328818720434
[I 2024-04-19 14:44:12,537] Trial 55 finished with value: 0.21663685261749652 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 65, 'oob_score': False, 'max_samples': 0.30569308510483195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16899129494126047}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14794352047999373
Fold 2 IBS: 0.1867255826178164
Fold 3 IBS: 0.15781589234508472
Fold 4 IBS: 0.18074045637859848
Fold 5 IBS: 0.22374090490131107
[I 2024-04-19 14:44:14,892] Trial 56 finished with value: 0.1793932713445609 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 6, 'n_estimators': 112, 'oob_score': False, 'max_samples': 0.879444109988293, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13470054580065446}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.153486989472442
Fold 2 IBS: 0.1715548982083498
Fold 3 IBS: 0.16344271985956446
Fold 4 IBS: 0.17712008356884695
Fold 5 IBS: 0.21745433370738948
[I 2024-04-19 14:44:15,566] Trial 57 finished with value: 0.17661180496331857 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 23, 'oob_score': False, 'max_samples': 0.7282100656023017, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07655091511728596}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.16144209598905285
Fold 2 IBS: 0.1815896007749345
Fold 3 IBS: 0.1677595521888748
Fold 4 IBS: 0.17445285608860042
Fold 5 IBS: 0.21548852871481017
[I 2024-04-19 14:44:16,510] Trial 58 finished with value: 0.18014652675125456 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.6004502714901225, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07832314685348683}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.214008383838558
Fold 2 IBS: 0.22125535334545718
Fold 3 IBS: 0.20441570884664864
Fold 4 IBS: 0.2248729650769993
Fold 5 IBS: 0.21859234574887557
[I 2024-04-19 14:44:17,542] Trial 59 finished with value: 0.21662895137130772 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 50, 'oob_score': False, 'max_samples': 0.8039035916436577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15116058308414781
Fold 2 IBS: 0.19010685308448416
Fold 3 IBS: 0.15921555402954687
Fold 4 IBS: 0.1758241519699497
Fold 5 IBS: 0.21941180429322477
[I 2024-04-19 14:44:19,743] Trial 60 finished with value: 0.17914378929227065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 90, 'oob_score': False, 'max_samples': 0.7454628587344282, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03520152790244757}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1526413960796701
Fold 2 IBS: 0.18645852391414078
Fold 3 IBS: 0.15822345833190693
Fold 4 IBS: 0.17303496454957462
Fold 5 IBS: 0.21655753966687788
[I 2024-04-19 14:44:21,403] Trial 61 finished with value: 0.17738317650843405 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 82, 'oob_score': False, 'max_samples': 0.6289677761062582, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.059410727521315064}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1590126948439196
Fold 2 IBS: 0.1898679222749424
Fold 3 IBS: 0.15920693723516843
Fold 4 IBS: 0.17226826221440894
Fold 5 IBS: 0.21733734946090885
[I 2024-04-19 14:44:23,328] Trial 62 finished with value: 0.17953863320586966 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.644088856909565, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05829996975014435}. Best is trial 48 with value: 0.1758069636587505.

Fold 1 IBS: 0.1528522544145544
Fold 2 IBS: 0.1883938076545454
Fold 3 IBS: 0.16059370160325126
Fold 4 IBS: 0.17447839059286202
Fold 5 IBS: 0.21675029793203757
[I 2024-04-19 14:44:26,224] Trial 63 finished with value: 0.17861369043945013 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.5082465499234735, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0848024624668733}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.16166621880208873
Fold 2 IBS: 0.1731632023212488
Fold 3 IBS: 0.1700340266068216
Fold 4 IBS: 0.17478280891532624
Fold 5 IBS: 0.2135771701385966
[I 2024-04-19 14:44:26,883] Trial 64 finished with value: 0.17864468535681638 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.588577514842217, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029696753747332764}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15226980414323507
Fold 2 IBS: 0.1904347394866864
Fold 3 IBS: 0.1605337458277561
Fold 4 IBS: 0.17671108399046023
Fold 5 IBS: 0.21709095294853806
[I 2024-04-19 14:44:29,235] Trial 65 finished with value: 0.17940806527933517 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 151, 'oob_score': False, 'max_samples': 0.4391883761451292, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0019436716080326738}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15087935942359007
Fold 2 IBS: 0.18390851133540326
Fold 3 IBS: 0.16379719608490256
Fold 4 IBS: 0.17968412180473498
Fold 5 IBS: 0.2240244980954591
[I 2024-04-19 14:44:30,069] Trial 66 finished with value: 0.18045873734881798 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.7609560416710082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06842133552739199}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1558074789577083
Fold 2 IBS: 0.18722632225085167
Fold 3 IBS: 0.16159655655925312
Fold 4 IBS: 0.16917480755091616
Fold 5 IBS: 0.21354958676323274
[I 2024-04-19 14:44:31,245] Trial 67 finished with value: 0.1774709504163924 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.6267429736060568, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09105542838308342}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.17364872253614366
Fold 2 IBS: 0.15737339829303196
Fold 3 IBS: 0.16379208774353307
Fold 4 IBS: 0.23824328185876364
Fold 5 IBS: 0.24178798668037754
[I 2024-04-19 14:44:31,576] Trial 68 finished with value: 0.19496909542236995 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 3, 'oob_score': False, 'max_samples': 0.7228587248646963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1890063288879738}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15966698806014762
Fold 2 IBS: 0.18791845126646142
Fold 3 IBS: 0.16261440793417092
Fold 4 IBS: 0.17667786489520682
Fold 5 IBS: 0.2152670823717742
[I 2024-04-19 14:44:33,237] Trial 69 finished with value: 0.1804289589055522 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.543209078895594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05620109695773104}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1570428068335575
Fold 2 IBS: 0.18826892481676916
Fold 3 IBS: 0.1597447797237805
Fold 4 IBS: 0.21802893791899966
Fold 5 IBS: 0.22665540976667467
[I 2024-04-19 14:44:35,156] Trial 70 finished with value: 0.1899481718119563 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.6952614611558205, 'max_features': None, 'min_weight_fraction_leaf': 0.01720171332096783}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15193941721605494
Fold 2 IBS: 0.16957357743067134
Fold 3 IBS: 0.16526614890964453
Fold 4 IBS: 0.1769941217403735
Fold 5 IBS: 0.21733382223407408
[I 2024-04-19 14:44:35,781] Trial 71 finished with value: 0.17622141750616366 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.7017127863520985, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11111990363388535}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15471588553820462
Fold 2 IBS: 0.175595402237788
Fold 3 IBS: 0.16412303860759403
Fold 4 IBS: 0.16805347186108316
Fold 5 IBS: 0.22165913912193214
[I 2024-04-19 14:44:36,630] Trial 72 finished with value: 0.1768293874733204 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.6470567310792946, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10917264390259916}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1547285443273455
Fold 2 IBS: 0.1705821951734832
Fold 3 IBS: 0.16229298906840267
Fold 4 IBS: 0.17912777778208328
Fold 5 IBS: 0.22090115929133103
[I 2024-04-19 14:44:37,348] Trial 73 finished with value: 0.17752653312852912 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 21, 'oob_score': False, 'max_samples': 0.85019697586559, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15225633959052098}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14815060765380272
Fold 2 IBS: 0.18241413181965807
Fold 3 IBS: 0.1606712671489576
Fold 4 IBS: 0.17842742048127724
Fold 5 IBS: 0.21697254526971396
[I 2024-04-19 14:44:38,449] Trial 74 finished with value: 0.17732719447468193 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.8047800018974197, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10778874404043165}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.1469867890691063
Fold 2 IBS: 0.184688673863672
Fold 3 IBS: 0.16007700050509954
Fold 4 IBS: 0.1807947800022811
Fold 5 IBS: 0.2186358205264877
[I 2024-04-19 14:44:39,966] Trial 75 finished with value: 0.1782366127933293 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.7983294757920592, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11423443734656469}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15062426985063293
Fold 2 IBS: 0.18275104221698302
Fold 3 IBS: 0.1625841691591965
Fold 4 IBS: 0.17732598337077415
Fold 5 IBS: 0.22160004933715005
[I 2024-04-19 14:44:40,586] Trial 76 finished with value: 0.1789771027869473 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 23, 'oob_score': False, 'max_samples': 0.8808289102754578, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10147448896528224}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14079003455549632
Fold 2 IBS: 0.2125171943300117
Fold 3 IBS: 0.14779544612407422
Fold 4 IBS: 0.18350856296996673
Fold 5 IBS: 0.2890375336957307
[I 2024-04-19 14:44:40,788] Trial 77 finished with value: 0.19472975433505596 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 1, 'oob_score': False, 'max_samples': 0.9398626428958133, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12925472203884794}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15400882363151763
Fold 2 IBS: 0.18556210083481944
Fold 3 IBS: 0.16306339114640434
Fold 4 IBS: 0.1708618011653215
Fold 5 IBS: 0.21747945160392373
[I 2024-04-19 14:44:41,650] Trial 78 finished with value: 0.17819511367639734 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.73687467988926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15265100902782777}. Best is trial 48 with value: 0.1758069636587505.

Fold 1 IBS: 0.14805872849452492
Fold 2 IBS: 0.1844394959428906
Fold 3 IBS: 0.1592084284475042
Fold 4 IBS: 0.18049902936533177
Fold 5 IBS: 0.21718793826468474
[I 2024-04-19 14:44:42,698] Trial 79 finished with value: 0.17787872410298725 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 50, 'oob_score': False, 'max_samples': 0.8221486447141937, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10873595340811325}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.15361491788372222
Fold 2 IBS: 0.19642745280621465
Fold 3 IBS: 0.16095616456284817
Fold 4 IBS: 0.22665346294232952
Fold 5 IBS: 0.2385594621067867
[I 2024-04-19 14:44:44,357] Trial 80 finished with value: 0.19524229206038027 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.7659640622029704, 'max_features': None, 'min_weight_fraction_leaf': 0.18307985478389613}. Best is trial 48 with value: 0.1758069636587505.
Fold 1 IBS: 0.14735125128835888
Fold 2 IBS: 0.17915060038924285
Fold 3 IBS: 0.15735531842391617
Fold 4 IBS: 0.17321978755547224
Fold 5 IBS: 0.21987213301468717
[I 2024-04-19 14:44:46,491] Trial 81 finished with value: 0.17538981813433546 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.5785272262773831, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08332907721465231}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15686372741336968
Fold 2 IBS: 0.16853213202759856
Fold 3 IBS: 0.16021812296349014
Fold 4 IBS: 0.17850429579193322
Fold 5 IBS: 0.21672769815568546
[I 2024-04-19 14:44:47,217] Trial 82 finished with value: 0.17616919527041544 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 15, 'oob_score': False, 'max_samples': 0.692337944685701, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12395808558776586}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.1619159012046828
Fold 2 IBS: 0.172967625777035
Fold 3 IBS: 0.16616817679060802
Fold 4 IBS: 0.17519719536230008
Fold 5 IBS: 0.2136815813112948
[I 2024-04-19 14:44:47,983] Trial 83 finished with value: 0.17798609608918414 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.5912315360628527, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16341574246423887}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15219102989663316
Fold 2 IBS: 0.1931818826697778
Fold 3 IBS: 0.16363363156099103
Fold 4 IBS: 0.17684428624029014
Fold 5 IBS: 0.2238144077409702
[I 2024-04-19 14:44:48,974] Trial 84 finished with value: 0.18193304762173246 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.70205360291002, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07361353921311417}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14779347159431672
Fold 2 IBS: 0.18302126268994853
Fold 3 IBS: 0.15831126962954525
Fold 4 IBS: 0.17419982728982455
Fold 5 IBS: 0.22078364119120042
[I 2024-04-19 14:44:51,042] Trial 85 finished with value: 0.17682189447896707 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.6895741253559994, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12125813943953494}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15433137239477093
Fold 2 IBS: 0.1845089608942651
Fold 3 IBS: 0.15984805434510146
Fold 4 IBS: 0.17282358032069636
Fold 5 IBS: 0.21614898495352275
[I 2024-04-19 14:44:53,123] Trial 86 finished with value: 0.17753219058167133 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.5659494458629141, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1223612964744446}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15320761117765
Fold 2 IBS: 0.16911910783647088
Fold 3 IBS: 0.15873999775129646
Fold 4 IBS: 0.17780232042694763
Fold 5 IBS: 0.23317669899032065
[I 2024-04-19 14:44:53,711] Trial 87 finished with value: 0.17840914723653714 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.6525715451525812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08433804187851579}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14758802752060363
Fold 2 IBS: 0.18799906778249217
Fold 3 IBS: 0.15830210488322033
Fold 4 IBS: 0.17672037551964595
Fold 5 IBS: 0.21952158849614914
[I 2024-04-19 14:44:56,706] Trial 88 finished with value: 0.17802623284042224 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.5095861562397511, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09677529418377355}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15761250784722478
Fold 2 IBS: 0.1814054872245867
Fold 3 IBS: 0.16584233239405852
Fold 4 IBS: 0.16767018453439145
Fold 5 IBS: 0.22146798826374336
[I 2024-04-19 14:44:57,603] Trial 89 finished with value: 0.17879970005280094 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.6769922636306419, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1451548892042033}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14225743331275637
Fold 2 IBS: 0.19311487496624619
Fold 3 IBS: 0.1610077847000388
Fold 4 IBS: 0.2027754944511087
Fold 5 IBS: 0.2208802693629259
[I 2024-04-19 14:45:01,388] Trial 90 finished with value: 0.1840071713586152 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 165, 'oob_score': False, 'max_samples': 0.607664424098672, 'max_features': None, 'min_weight_fraction_leaf': 0.045915615112569044}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14937090293105826
Fold 2 IBS: 0.1816257040714749
Fold 3 IBS: 0.15849883981566143
Fold 4 IBS: 0.17537352974098414
Fold 5 IBS: 0.21719851706081347
[I 2024-04-19 14:45:02,772] Trial 91 finished with value: 0.17641349872399845 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 62, 'oob_score': False, 'max_samples': 0.6967245615106861, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13205280276099104}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.1484194947660909
Fold 2 IBS: 0.18213568383529022
Fold 3 IBS: 0.15611185913104791
Fold 4 IBS: 0.17651662327051712
Fold 5 IBS: 0.21861518814139327
[I 2024-04-19 14:45:04,901] Trial 92 finished with value: 0.17635976982886786 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.727101025098758, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1216006136267095}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14859900392331132
Fold 2 IBS: 0.18369789790102672
Fold 3 IBS: 0.15609573510939495
Fold 4 IBS: 0.17628004615360646
Fold 5 IBS: 0.21935184075240627
[I 2024-04-19 14:45:06,488] Trial 93 finished with value: 0.17680490476794913 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.7270159996917693, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12117072039376087}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15296344734440717
Fold 2 IBS: 0.18695996166974396
Fold 3 IBS: 0.15774179335171973
Fold 4 IBS: 0.17295458943222297

Fold 5 IBS: 0.21759783800196422
[I 2024-04-19 14:45:08,700] Trial 94 finished with value: 0.1776435259600116 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.7242593013645032, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14462066268912804}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.15162608620389867
Fold 2 IBS: 0.19121869268171396
Fold 3 IBS: 0.15836366628343707
Fold 4 IBS: 0.17826802865577213
Fold 5 IBS: 0.21920067113279704
[I 2024-04-19 14:45:11,366] Trial 95 finished with value: 0.17973542899152378 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 137, 'oob_score': False, 'max_samples': 0.772556078583092, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1631127999140187}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.16352525950573188
Fold 2 IBS: 0.18296538734873047
Fold 3 IBS: 0.16292268280332917
Fold 4 IBS: 0.18527611582158968
Fold 5 IBS: 0.2102778391441335
[I 2024-04-19 14:45:12,237] Trial 96 finished with value: 0.18099345692470292 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7421638972276217, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27874856663178627}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14512419897865786
Fold 2 IBS: 0.18937606809462942
Fold 3 IBS: 0.1579550636324128
Fold 4 IBS: 0.178991393386047
Fold 5 IBS: 0.21788411235607089
[I 2024-04-19 14:45:15,753] Trial 97 finished with value: 0.1778661672895636 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.7192270960501082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0897267677897641}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.1622971916445904
Fold 2 IBS: 0.200805063034386
Fold 3 IBS: 0.16315956100577864
Fold 4 IBS: 0.17924308868529154
Fold 5 IBS: 0.2205431637812717
[I 2024-04-19 14:45:17,935] Trial 98 finished with value: 0.18520961363026364 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.7488605581621807, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13339402708275627}. Best is trial 81 with value: 0.17538981813433546.
Fold 1 IBS: 0.14463564057781775
Fold 2 IBS: 0.19495198337921166
Fold 3 IBS: 0.16337600930555288
Fold 4 IBS: 0.18532359128908554
Fold 5 IBS: 0.2233191921995693
[I 2024-04-19 14:45:19,716] Trial 99 finished with value: 0.18232128335024742 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 81, 'oob_score': False, 'max_samples': 0.7892849711265231, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07204462112879095}. Best is trial 81 with value: 0.17538981813433546.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.17538981813433546], datetime_start=datetime.datetime(2024, 4, 19, 14, 44, 44, 364054), datetime_complete=datetime.datetime(2024, 4, 19, 14, 44, 46, 489921), params={'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.5785272262773831, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08332907721465231}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=81, value=None)


* Best Score for IBS:
 0.17538981813433546

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.871
train_ibs:  0.175

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [58]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=14, max_features='auto', max_leaf_nodes=15,
                     max_samples=0.9504102015210659, min_samples_leaf=2,
                     min_samples_split=9,
                     min_weight_fraction_leaf=0.005622697057305325,
                     n_estimators=144, random_state=123, warm_start=True)

test_cindex:  0.618

RandomSurvivalForest(max_depth=6, max_leaf_nodes=10,
                     max_samples=0.5785272262773831, min_samples_leaf=8,
                     min_samples_split=11,
                     min_weight_fraction_leaf=0.08332907721465231,
                     random_state=123)

test_ibs:  0.223

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [61]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 14:45:20,932] A new study created in memory with name: no-name-972bb78b-4747-4189-84ef-0d698e051982

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:45:22,324] Trial 0 finished with value: 0.7766254315304948 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:45:25,996] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:45:31,930] Trial 2 finished with value: 0.7569164638091417 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:45:32,531] Trial 3 finished with value: 0.7635299204691358 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:45:34,668] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:45:38,110] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7766254315304948.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:45:40,636] Trial 6 finished with value: 0.7772891060912281 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:45:44,982] Trial 7 finished with value: 0.7519117264565756 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 14:45:45,368] Trial 8 finished with value: 0.7605913297992336 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:45:55,286] Trial 9 finished with value: 0.7628491337417315 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:45:58,215] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6549295774647887
[I 2024-04-19 14:45:59,944] Trial 11 finished with value: 0.7715029724308078 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.7772891060912281.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:46:01,816] Trial 12 finished with value: 0.786055160528368 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:04,093] Trial 13 finished with value: 0.7678260059919524 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:06,151] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:46:07,869] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.786055160528368.

Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:10,188] Trial 16 finished with value: 0.7660839887017223 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8333333333333334
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6314553990610329
[I 2024-04-19 14:46:11,970] Trial 17 finished with value: 0.7725320603816497 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 14:46:12,901] Trial 18 finished with value: 0.7707238158922624 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:13,828] Trial 19 finished with value: 0.7702023650511113 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:15,390] Trial 20 finished with value: 0.7705868341436966 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:46:16,936] Trial 21 finished with value: 0.77730861210268 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7953586497890295
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:19,421] Trial 22 finished with value: 0.7727018170758798 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5833816310769062, 'min_weight_fraction_leaf': 0.10633258814265802}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:21,366] Trial 23 finished with value: 0.7784699433429022 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7310231778151053, 'min_weight_fraction_leaf': 0.013477785996217753}. Best is trial 12 with value: 0.786055160528368.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:46:22,999] Trial 24 finished with value: 0.787567401918222 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7197381019543724, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 24 with value: 0.787567401918222.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:46:24,921] Trial 25 finished with value: 0.7919233215012451 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.876735501897294, 'min_weight_fraction_leaf': 0.04480374820150253}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:46:32,268] Trial 26 finished with value: 0.7554146737302354 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8701610988033271, 'min_weight_fraction_leaf': 0.06018738864873575}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:46:33,505] Trial 27 finished with value: 0.7556220783261358 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:34,445] Trial 28 finished with value: 0.7851334631812174 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9575314635792546, 'min_weight_fraction_leaf': 0.04083350928166579}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:46:36,221] Trial 29 finished with value: 0.780411221645176 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9279195082568442, 'min_weight_fraction_leaf': 0.07252328844834334}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:46:37,559] Trial 30 finished with value: 0.7755367694331334 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7131454297229517, 'min_weight_fraction_leaf': 0.09210752384530588}. Best is trial 25 with value: 0.7919233215012451.

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:38,623] Trial 31 finished with value: 0.7852867552230053 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8438862458923003, 'min_weight_fraction_leaf': 0.03902180415717787}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:46:39,990] Trial 32 finished with value: 0.7827112716348635 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8332385731539106, 'min_weight_fraction_leaf': 0.027416055450601745}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:40,674] Trial 33 finished with value: 0.766409530310771 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 158, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8572071692366157, 'min_weight_fraction_leaf': 0.06748325843685211}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:46:41,606] Trial 34 finished with value: 0.7539146675785664 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 239, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.997814568983562, 'min_weight_fraction_leaf': 0.12436915097441914}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:46:42,861] Trial 35 finished with value: 0.7606421761235977 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 139, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.912266890066162, 'min_weight_fraction_leaf': 0.24235302278015497}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:46:48,244] Trial 36 finished with value: 0.7520315960384705 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 339, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6967226649720313, 'min_weight_fraction_leaf': 0.048301638211746496}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:46:49,560] Trial 37 finished with value: 0.787043732021407 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7790217874657425, 'min_weight_fraction_leaf': 0.0860355981837791}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:46:51,504] Trial 38 finished with value: 0.7696677376359059 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.48791124460782864, 'min_weight_fraction_leaf': 0.0801615592088104}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:46:58,897] Trial 39 finished with value: 0.7536168626756364 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 364, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7898418765076363, 'min_weight_fraction_leaf': 0.11157601621505114}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:47:00,437] Trial 40 finished with value: 0.7635654829607169 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6333788332887427, 'min_weight_fraction_leaf': 0.16594433686505833}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:01,407] Trial 41 finished with value: 0.785989441806642 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7620488800258761, 'min_weight_fraction_leaf': 0.027676500905582244}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:02,004] Trial 42 finished with value: 0.7907671275288182 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 91, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7754857501009593, 'min_weight_fraction_leaf': 0.022639239663285127}. Best is trial 25 with value: 0.7919233215012451.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:47:02,741] Trial 43 finished with value: 0.8018034514086029 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9378855450065084, 'min_weight_fraction_leaf': 0.017387160098159254}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 14:47:03,237] Trial 44 finished with value: 0.7626036408663857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 73, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7976715718652303, 'min_weight_fraction_leaf': 0.13247133428022156}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:03,981] Trial 45 finished with value: 0.765601201865858 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 82, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7559143250033664, 'min_weight_fraction_leaf': 0.08994451801308195}. Best is trial 43 with value: 0.8018034514086029.

Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:47:04,243] Trial 46 finished with value: 0.7898793033761585 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6678646968753718, 'min_weight_fraction_leaf': 0.05891279435507671}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.7987012987012987
Fold 2 C-index: 0.6941964285714286
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-19 14:47:04,539] Trial 47 finished with value: 0.7323875186349034 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 2, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6679397381454423, 'min_weight_fraction_leaf': 0.02148191909872358}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6408450704225352
[I 2024-04-19 14:47:05,189] Trial 48 finished with value: 0.7610259615240121 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 49, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9463412504225213, 'min_weight_fraction_leaf': 0.3399047172380002}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:05,865] Trial 49 finished with value: 0.7801271498891135 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 106, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5836783796663053, 'min_weight_fraction_leaf': 0.05902698170708356}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:06,269] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.2737091230315036}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8116883116883117
Fold 2 C-index: 0.6361607142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5915492957746479
[I 2024-04-19 14:47:06,481] Trial 51 finished with value: 0.726916646231095 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 1, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8110439696436671, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:07,183] Trial 52 finished with value: 0.7879600483607436 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 117, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7483106974669713, 'min_weight_fraction_leaf': 0.002297495788120843}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:08,034] Trial 53 finished with value: 0.7890625820742729 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 129, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7007511417838951, 'min_weight_fraction_leaf': 0.0013747037483597818}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:08,562] Trial 54 finished with value: 0.78448034520215 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 119, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6161650292854159, 'min_weight_fraction_leaf': 0.005195745122904563}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:09,175] Trial 55 finished with value: 0.7860694265550432 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 81, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6836250238686925, 'min_weight_fraction_leaf': 0.01968098833169956}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:09,930] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 133, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7500159556912651, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8376623376623377
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6408450704225352
[I 2024-04-19 14:47:10,381] Trial 57 finished with value: 0.7602738453726035 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 30, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8823994002805076, 'min_weight_fraction_leaf': 0.004687560117461877}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:47:12,357] Trial 58 finished with value: 0.7510126441539192 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 98, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6087241852990865, 'min_weight_fraction_leaf': 0.025994916170817187}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:13,114] Trial 59 finished with value: 0.7670460140976276 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 64, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6724790116541645, 'min_weight_fraction_leaf': 5.044215225983792e-05}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:13,963] Trial 60 finished with value: 0.7779774239312087 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 172, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8154018570576436, 'min_weight_fraction_leaf': 0.06061652770492859}. Best is trial 43 with value: 0.8018034514086029.

Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:47:14,613] Trial 61 finished with value: 0.7980460426767831 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 93, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7308291502564501, 'min_weight_fraction_leaf': 0.041167639802806265}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:15,185] Trial 62 finished with value: 0.7774861913192643 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.537144845100827, 'min_weight_fraction_leaf': 0.029116858539921832}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:47:15,715] Trial 63 finished with value: 0.7972972460998532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 126, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7283633534707481, 'min_weight_fraction_leaf': 0.04541440737984728}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 14:47:16,067] Trial 64 finished with value: 0.7704534152840053 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 26, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7017441977663603, 'min_weight_fraction_leaf': 0.1020463678010651}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.829004329004329
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6314553990610329
[I 2024-04-19 14:47:16,809] Trial 65 finished with value: 0.773451973801563 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 137, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9333430776387115, 'min_weight_fraction_leaf': 0.4134291052499814}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 14:47:17,395] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 65, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8707697064569014, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:18,463] Trial 67 finished with value: 0.7876236479778057 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 155, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9023529495393777, 'min_weight_fraction_leaf': 0.07201355123747381}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:19,131] Trial 68 finished with value: 0.7852435105227362 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 46, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.04126730233993369}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:47:19,703] Trial 69 finished with value: 0.8011773897065917 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7273515106813977, 'min_weight_fraction_leaf': 0.05284452070827268}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8333333333333334
Fold 2 C-index: 0.6897321428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.636150234741784
[I 2024-04-19 14:47:21,635] Trial 70 finished with value: 0.7511283246138534 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 88, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.834906956075858, 'min_weight_fraction_leaf': 0.05486511182190622}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:22,512] Trial 71 finished with value: 0.7749144347685427 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6455263748184987, 'min_weight_fraction_leaf': 0.01406965747820355}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:23,160] Trial 72 finished with value: 0.7819923966280138 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 59, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7308740974688083, 'min_weight_fraction_leaf': 0.040892682928865644}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:23,870] Trial 73 finished with value: 0.7775865438235133 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7768223340027555, 'min_weight_fraction_leaf': 0.07544218623936463}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 14:47:24,523] Trial 74 finished with value: 0.8014094733340589 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.970607413962485, 'min_weight_fraction_leaf': 0.03242680345175293}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7911392405063291
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:25,012] Trial 75 finished with value: 0.769099741673035 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 106, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9841844662150304, 'min_weight_fraction_leaf': 0.09823806741925431}. Best is trial 43 with value: 0.8018034514086029.

Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 14:47:25,420] Trial 76 finished with value: 0.7745536932985807 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 31, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9239434202011361, 'min_weight_fraction_leaf': 0.11933626233578211}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:25,754] Trial 77 finished with value: 0.7855277187618592 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9645534638498757, 'min_weight_fraction_leaf': 0.033013807411716084}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:26,341] Trial 78 finished with value: 0.7916652629625084 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.81446503479005, 'min_weight_fraction_leaf': 0.05858385951756177}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8308823529411765
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:26,735] Trial 79 finished with value: 0.7721250842108995 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 76, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8240784041644889, 'min_weight_fraction_leaf': 0.08113175369933603}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:27,558] Trial 80 finished with value: 0.7819334243122038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8621383905551123, 'min_weight_fraction_leaf': 0.017981219707984775}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 14:47:28,152] Trial 81 finished with value: 0.7894873545294875 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 94, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8902326274844327, 'min_weight_fraction_leaf': 0.05660051590199361}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.7911392405063291
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:28,481] Trial 82 finished with value: 0.7796262249936361 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 58, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8021748345495684, 'min_weight_fraction_leaf': 0.06326319264983851}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 14:47:29,037] Trial 83 finished with value: 0.7815602149302321 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 108, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9670037749682452, 'min_weight_fraction_leaf': 0.04727227790003351}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7953586497890295
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:29,460] Trial 84 finished with value: 0.7673175282771336 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 42, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7396870843483736, 'min_weight_fraction_leaf': 0.08898518693898708}. Best is trial 43 with value: 0.8018034514086029.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 14:47:29,930] Trial 85 finished with value: 0.8041070984788672 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 70, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8476085844987526, 'min_weight_fraction_leaf': 0.03326421194628475}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 14:47:30,709] Trial 86 finished with value: 0.7870532410033658 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 144, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8496294339105882, 'min_weight_fraction_leaf': 0.035555616803382525}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 14:47:34,577] Trial 87 finished with value: 0.7532383759959518 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.93595530867521, 'min_weight_fraction_leaf': 0.016380716801170345}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.816017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7742616033755274
Fold 5 C-index: 0.6408450704225352
[I 2024-04-19 14:47:35,500] Trial 88 finished with value: 0.7531225570667172 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 77, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9071908205264589, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:36,220] Trial 89 finished with value: 0.7814385432611918 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 124, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7706846873578284, 'min_weight_fraction_leaf': 0.048298161975799433}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8051948051948052
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 14:47:36,662] Trial 90 finished with value: 0.7721818359104285 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9998511806246988, 'min_weight_fraction_leaf': 0.07267615605976058}. Best is trial 85 with value: 0.8041070984788672.

Fold 1 C-index: 0.8246753246753247
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 14:47:36,950] Trial 91 finished with value: 0.790008574683054 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 15, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7849096528006341, 'min_weight_fraction_leaf': 0.030415157337554115}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 14:47:37,881] Trial 92 finished with value: 0.8006289355074921 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 72, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7842305799006279, 'min_weight_fraction_leaf': 0.031581852960146074}. Best is trial 85 with value: 0.8041070984788672.
Fold 1 C-index: 0.8225108225108225
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 14:47:38,910] Trial 93 finished with value: 0.8089579504713926 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 102, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8797548257330544, 'min_weight_fraction_leaf': 0.016155917164710452}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 14:47:39,562] Trial 94 finished with value: 0.8054066212296682 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 69, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8684665766132931, 'min_weight_fraction_leaf': 0.01520501163055084}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8095238095238095
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 14:47:40,389] Trial 95 finished with value: 0.7970800167098396 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 103, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8814092235554671, 'min_weight_fraction_leaf': 0.011818046281800824}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 14:47:41,202] Trial 96 finished with value: 0.8016186976095158 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 110, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8863766024930939, 'min_weight_fraction_leaf': 0.016663029023952246}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 14:47:42,021] Trial 97 finished with value: 0.7746861990553852 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8530408080789232, 'min_weight_fraction_leaf': 0.012237463120232602}. Best is trial 93 with value: 0.8089579504713926.
Fold 1 C-index: 0.8181818181818182
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 14:47:42,699] Trial 98 finished with value: 0.8160429569565227 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 68, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9554816381741302, 'min_weight_fraction_leaf': 0.026333169142875475}. Best is trial 98 with value: 0.8160429569565227.

[I 2024-04-19 14:47:43,358] A new study created in memory with name: no-name-a833dc16-8466-46b6-a441-e4b7c041f137

Fold 1 C-index: 0.8138528138528138
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 14:47:43,260] Trial 99 finished with value: 0.81059250622079 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 67, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9572705727248035, 'min_weight_fraction_leaf': 0.03267161037635903}. Best is trial 98 with value: 0.8160429569565227.


* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.8160429569565227], datetime_start=datetime.datetime(2024, 4, 19, 14, 47, 42, 167727), datetime_complete=datetime.datetime(2024, 4, 19, 14, 47, 42, 698215), params={'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 68, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9554816381741302, 'min_weight_fraction_leaf': 0.026333169142875475}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for C-index:
 0.8160429569565227

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.15331808879740202
Fold 2 IBS: 0.222926809068137
Fold 3 IBS: 0.16873053393274628
Fold 4 IBS: 0.15901193437964076
Fold 5 IBS: 0.23009035684346238
[I 2024-04-19 14:47:49,060] Trial 0 finished with value: 0.18681554460427768 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-19 14:47:57,290] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.168869624633049
Fold 2 IBS: 0.2095319681530086
Fold 3 IBS: 0.17387462883519067
Fold 4 IBS: 0.17607018679729425
Fold 5 IBS: 0.21823846331824107
[I 2024-04-19 14:48:05,351] Trial 2 finished with value: 0.1893169743473567 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.1702791557232537
Fold 2 IBS: 0.20661953446628545
Fold 3 IBS: 0.17493262806105533
Fold 4 IBS: 0.1766439453303021
Fold 5 IBS: 0.2175305564424761
[I 2024-04-19 14:48:07,893] Trial 3 finished with value: 0.18920116400467454 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-19 14:48:14,082] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-19 14:48:17,183] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18681554460427768.
Fold 1 IBS: 0.15379016945716226
Fold 2 IBS: 0.22217988049119108
Fold 3 IBS: 0.16821042912650647
Fold 4 IBS: 0.15825490490421495
Fold 5 IBS: 0.23095581916469532
[I 2024-04-19 14:48:23,368] Trial 6 finished with value: 0.18667824062875404 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.18667824062875404.
Fold 1 IBS: 0.15797367672389057
Fold 2 IBS: 0.2105735852385178
Fold 3 IBS: 0.17043395686966864
Fold 4 IBS: 0.16710050505563723
Fold 5 IBS: 0.22255440287284375
[I 2024-04-19 14:48:27,719] Trial 7 finished with value: 0.1857272253521116 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1706840906561748
Fold 2 IBS: 0.20832030276387237
Fold 3 IBS: 0.17670034233157944
Fold 4 IBS: 0.17781636300010176
Fold 5 IBS: 0.21997982323680884
[I 2024-04-19 14:48:28,453] Trial 8 finished with value: 0.19070018439770745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1823139020794423
Fold 2 IBS: 0.20738012964651717
Fold 3 IBS: 0.18186365068989283
Fold 4 IBS: 0.19310256206045615
Fold 5 IBS: 0.21422428265990107
[I 2024-04-19 14:48:37,156] Trial 9 finished with value: 0.19577690542724194 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.2139976337400846
Fold 2 IBS: 0.22078850566211056
Fold 3 IBS: 0.20468678510920732
Fold 4 IBS: 0.2246562137512858
Fold 5 IBS: 0.21763185598455237
[I 2024-04-19 14:48:39,102] Trial 10 finished with value: 0.21635219884944812 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 98, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.21752764504502275, 'min_weight_fraction_leaf': 0.20722772178871404}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15257958360664922
Fold 2 IBS: 0.22451002050856136
Fold 3 IBS: 0.16796200044670512
Fold 4 IBS: 0.15943292856491
Fold 5 IBS: 0.2314772049086562
[I 2024-04-19 14:48:43,472] Trial 11 finished with value: 0.18719234760709638 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 296, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17619400334161145
Fold 2 IBS: 0.20715079705418202
Fold 3 IBS: 0.17809607429453234
Fold 4 IBS: 0.18249119187305823
Fold 5 IBS: 0.21663453645181943
[I 2024-04-19 14:48:47,279] Trial 12 finished with value: 0.19211332060304068 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 214, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.2683866363584086, 'min_weight_fraction_leaf': 0.0005781139040304361}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15947567965793366
Fold 2 IBS: 0.22354986457490156
Fold 3 IBS: 0.16956362213133028
Fold 4 IBS: 0.16329441120378663
Fold 5 IBS: 0.2292440849614746
[I 2024-04-19 14:48:52,438] Trial 13 finished with value: 0.18902553250588533 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638655338226161, 'min_weight_fraction_leaf': 0.16922765932800388}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.2139242004833309
Fold 2 IBS: 0.22063339342953675
Fold 3 IBS: 0.20543327096798636
Fold 4 IBS: 0.22521858786986126
Fold 5 IBS: 0.2170716312878449
[I 2024-04-19 14:48:56,060] Trial 14 finished with value: 0.21645621680771204 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.07318050492704681}. Best is trial 7 with value: 0.1857272253521116.

Fold 1 IBS: 0.21397899766980513
Fold 2 IBS: 0.22119491249175238
Fold 3 IBS: 0.20501286878802247
Fold 4 IBS: 0.2247338457207233
Fold 5 IBS: 0.21814874287282784
[I 2024-04-19 14:49:01,415] Trial 15 finished with value: 0.2166138735086262 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 379, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.33528007217980527, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1513347225448683
Fold 2 IBS: 0.2222444435875969
Fold 3 IBS: 0.16799009245760868
Fold 4 IBS: 0.15755653814584675
Fold 5 IBS: 0.23161411047983665
[I 2024-04-19 14:49:08,782] Trial 16 finished with value: 0.18614798144315142 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6536453784519287, 'min_weight_fraction_leaf': 0.03818486015953676}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17617003718377808
Fold 2 IBS: 0.20294108117243945
Fold 3 IBS: 0.17742316755687063
Fold 4 IBS: 0.18785483606044212
Fold 5 IBS: 0.21375615024178732
[I 2024-04-19 14:49:18,099] Trial 17 finished with value: 0.19162905444306352 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 493, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8884180578214513, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16865902885414047
Fold 2 IBS: 0.19944340022849147
Fold 3 IBS: 0.17297763434162985
Fold 4 IBS: 0.17989185130999089
Fold 5 IBS: 0.22524482271210727
[I 2024-04-19 14:49:18,938] Trial 18 finished with value: 0.189243347489272 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 23, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.635457264859255, 'min_weight_fraction_leaf': 0.18605021589393816}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15424481414316563
Fold 2 IBS: 0.2212212157229542
Fold 3 IBS: 0.1683518141271408
Fold 4 IBS: 0.15823989006317227
Fold 5 IBS: 0.23060481783556233
[I 2024-04-19 14:49:21,602] Trial 19 finished with value: 0.18653251037839905 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 141, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6831327987735002, 'min_weight_fraction_leaf': 0.05567354271014018}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17488320088597403
Fold 2 IBS: 0.2094654753630573
Fold 3 IBS: 0.17895757287032865
Fold 4 IBS: 0.18123361279768233
Fold 5 IBS: 0.21774048491415354
[I 2024-04-19 14:49:26,011] Trial 20 finished with value: 0.19245606936623919 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 242, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8746512426406728, 'min_weight_fraction_leaf': 0.1092354718367409}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15378605399995207
Fold 2 IBS: 0.22093132354955883
Fold 3 IBS: 0.1679875038588519
Fold 4 IBS: 0.15750989935836693
Fold 5 IBS: 0.23209317117666156
[I 2024-04-19 14:49:28,122] Trial 21 finished with value: 0.18646159038867824 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6647253837986332, 'min_weight_fraction_leaf': 0.0514767164471617}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15390173460785092
Fold 2 IBS: 0.22339921499689297
Fold 3 IBS: 0.16936165765323366
Fold 4 IBS: 0.15792320213465816
Fold 5 IBS: 0.23290418382799433
[I 2024-04-19 14:49:30,050] Trial 22 finished with value: 0.187497998644126 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 72, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7012203687886621, 'min_weight_fraction_leaf': 0.041265940360740716}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16481494551087472
Fold 2 IBS: 0.21400919181835748
Fold 3 IBS: 0.17231389309603723
Fold 4 IBS: 0.17004175880120334
Fold 5 IBS: 0.22166234418445716
[I 2024-04-19 14:49:36,114] Trial 23 finished with value: 0.18856842668218599 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 332, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.44236466344473546, 'min_weight_fraction_leaf': 0.13411382575564806}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.14989033038186125
Fold 2 IBS: 0.22347622030948472
Fold 3 IBS: 0.16746937404638448
Fold 4 IBS: 0.15684196724060495
Fold 5 IBS: 0.23314467495929328
[I 2024-04-19 14:49:39,368] Trial 24 finished with value: 0.18616451338752574 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 157, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8787281207754778, 'min_weight_fraction_leaf': 0.04917014729703097}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.17524520008249128
Fold 2 IBS: 0.2069363358295505
Fold 3 IBS: 0.1781979071739044
Fold 4 IBS: 0.1818142113750091
Fold 5 IBS: 0.21708691401871724
[I 2024-04-19 14:49:42,991] Trial 25 finished with value: 0.19185611369593453 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 179, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8972910445185178, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1525093976343376
Fold 2 IBS: 0.2243407574335712
Fold 3 IBS: 0.16893011944691214
Fold 4 IBS: 0.15892740602279673
Fold 5 IBS: 0.23068081255511538
[I 2024-04-19 14:49:50,504] Trial 26 finished with value: 0.18707769861854662 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 248, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8529504122040699, 'min_weight_fraction_leaf': 0.09666572299489368}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.18231155824547537
Fold 2 IBS: 0.25824896647503714
Fold 3 IBS: 0.1689307270871101
Fold 4 IBS: 0.15329557771600297
Fold 5 IBS: 0.30065918160355315
[I 2024-04-19 14:49:50,994] Trial 27 finished with value: 0.21268920222543578 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 1, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9946457249155709, 'min_weight_fraction_leaf': 0.031166036698169683}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1719212396011742
Fold 2 IBS: 0.2559012768635498
Fold 3 IBS: 0.16710877095920373
Fold 4 IBS: 0.16244867407963692
Fold 5 IBS: 0.23995002223176268
[I 2024-04-19 14:49:54,532] Trial 28 finished with value: 0.19946599674706547 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9484789033538706, 'min_weight_fraction_leaf': 0.16298179421858316}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16403135832618315
Fold 2 IBS: 0.20899818717971916
Fold 3 IBS: 0.17288618041423
Fold 4 IBS: 0.1731834369538113
Fold 5 IBS: 0.2179090439033289
[I 2024-04-19 14:50:00,304] Trial 29 finished with value: 0.1874016413554545 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.73650015077135, 'min_weight_fraction_leaf': 0.08962850536510933}. Best is trial 7 with value: 0.1857272253521116.

Fold 1 IBS: 0.1585529260071
Fold 2 IBS: 0.218153010449042
Fold 3 IBS: 0.17021896151952115
Fold 4 IBS: 0.16343124711768475
Fold 5 IBS: 0.2311751417053347
[I 2024-04-19 14:50:03,040] Trial 30 finished with value: 0.18830625735973652 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 116, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8258632202024414, 'min_weight_fraction_leaf': 0.20241101766143602}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15420880459120728
Fold 2 IBS: 0.22137976081415967
Fold 3 IBS: 0.16774275391760834
Fold 4 IBS: 0.15688252726853427
Fold 5 IBS: 0.23380379197752338
[I 2024-04-19 14:50:05,523] Trial 31 finished with value: 0.18680352771380657 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 108, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6146551753104116, 'min_weight_fraction_leaf': 0.03593211426266471}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15579896140988755
Fold 2 IBS: 0.2222407852093063
Fold 3 IBS: 0.1692610730939769
Fold 4 IBS: 0.1606323064011862
Fold 5 IBS: 0.2308936445065212
[I 2024-04-19 14:50:09,039] Trial 32 finished with value: 0.1877653541241756 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 220, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7415269845526361, 'min_weight_fraction_leaf': 0.08044503719481133}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1546873596354472
Fold 2 IBS: 0.22227957519958622
Fold 3 IBS: 0.1687522326739948
Fold 4 IBS: 0.15908052920324967
Fold 5 IBS: 0.2322216282397852
[I 2024-04-19 14:50:10,842] Trial 33 finished with value: 0.18740426499041263 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 77, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5078862514536379, 'min_weight_fraction_leaf': 0.057248685594014664}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.1355139041880366
Fold 2 IBS: 0.2329599823177983
Fold 3 IBS: 0.16632631710096546
Fold 4 IBS: 0.16103445768167077
Fold 5 IBS: 0.2330686919937605
[I 2024-04-19 14:50:18,987] Trial 34 finished with value: 0.18578067065644635 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 404, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.02890474097529236}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.15421148476075414
Fold 2 IBS: 0.2450546663166637
Fold 3 IBS: 0.16500281729172725
Fold 4 IBS: 0.15525641050084926
Fold 5 IBS: 0.23927895639791555
[I 2024-04-19 14:50:28,430] Trial 35 finished with value: 0.19176086705358197 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9010743484673644, 'min_weight_fraction_leaf': 0.025515731497252444}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.14579782574171335
Fold 2 IBS: 0.24019828814288097
Fold 3 IBS: 0.16528410789334966
Fold 4 IBS: 0.15647595192127317
Fold 5 IBS: 0.2362427262131217
[I 2024-04-19 14:50:35,949] Trial 36 finished with value: 0.18879977998246777 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.936140510899361, 'min_weight_fraction_leaf': 0.12300175093789192}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.16545965140525298
Fold 2 IBS: 0.20989079407877548
Fold 3 IBS: 0.17286590058344356
Fold 4 IBS: 0.17304528094098826
Fold 5 IBS: 0.2182125077630938
[I 2024-04-19 14:50:44,288] Trial 37 finished with value: 0.1878948269543108 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 496, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9929376104209421, 'min_weight_fraction_leaf': 0.08616912220218276}. Best is trial 7 with value: 0.1857272253521116.
Fold 1 IBS: 0.13319828194243652
Fold 2 IBS: 0.22067121132296855
Fold 3 IBS: 0.16980000428003392
Fold 4 IBS: 0.16339522222882116
Fold 5 IBS: 0.22988296728768715
[I 2024-04-19 14:50:51,977] Trial 38 finished with value: 0.18338953741238945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 388, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8228713264596608, 'min_weight_fraction_leaf': 0.021895469287462357}. Best is trial 38 with value: 0.18338953741238945.
Fold 1 IBS: 0.13407560849543151
Fold 2 IBS: 0.2184148968621707
Fold 3 IBS: 0.17037492797043788
Fold 4 IBS: 0.16329611374791547
Fold 5 IBS: 0.2293623793340135
[I 2024-04-19 14:51:01,457] Trial 39 finished with value: 0.18310478528199378 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7898418765076363, 'min_weight_fraction_leaf': 0.020295911430938566}. Best is trial 39 with value: 0.18310478528199378.
Fold 1 IBS: 0.1304595556946257
Fold 2 IBS: 0.21558129315141517
Fold 3 IBS: 0.1721506143770424
Fold 4 IBS: 0.16618098384472219
Fold 5 IBS: 0.232949867879073
[I 2024-04-19 14:51:09,754] Trial 40 finished with value: 0.1834644629893757 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8371469247434516, 'min_weight_fraction_leaf': 0.015333852381823724}. Best is trial 39 with value: 0.18310478528199378.
Fold 1 IBS: 0.1325510554909969
Fold 2 IBS: 0.2176238888953884
Fold 3 IBS: 0.17146304984695035
Fold 4 IBS: 0.16383374018977762
Fold 5 IBS: 0.2308327762523128
[I 2024-04-19 14:51:18,349] Trial 41 finished with value: 0.18326090213508522 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 397, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8365147515392561, 'min_weight_fraction_leaf': 0.0016134071172678316}. Best is trial 39 with value: 0.18310478528199378.
Fold 1 IBS: 0.1314765695473778
Fold 2 IBS: 0.21139893346492042
Fold 3 IBS: 0.17223202101447635
Fold 4 IBS: 0.16376170833130235
Fold 5 IBS: 0.2321519720232104
[I 2024-04-19 14:51:27,667] Trial 42 finished with value: 0.18220424087625745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 391, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0013385721334536593}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13234737070073235
Fold 2 IBS: 0.21215429864404478
Fold 3 IBS: 0.17435282545530972
Fold 4 IBS: 0.16448123531500952
Fold 5 IBS: 0.23186786723530756
[I 2024-04-19 14:51:38,311] Trial 43 finished with value: 0.1830407194700808 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.00986096435937783}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14573824767156937
Fold 2 IBS: 0.2269412087537974
Fold 3 IBS: 0.16700435711423492
Fold 4 IBS: 0.16110065048481265
Fold 5 IBS: 0.2275276021025756
[I 2024-04-19 14:51:47,812] Trial 44 finished with value: 0.18566241322539798 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7911148199774719, 'min_weight_fraction_leaf': 0.020298655113375193}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.1350712935921733
Fold 2 IBS: 0.21575795396259614
Fold 3 IBS: 0.1719895889282686
Fold 4 IBS: 0.1639662174932425
Fold 5 IBS: 0.23179177468347978
[I 2024-04-19 14:52:01,489] Trial 45 finished with value: 0.18371536573195205 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7218458884001862, 'min_weight_fraction_leaf': 0.002908146688295732}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14405258172603636
Fold 2 IBS: 0.23510729165077407
Fold 3 IBS: 0.1652427330079092
Fold 4 IBS: 0.15610840831496184
Fold 5 IBS: 0.23462655467653304
[I 2024-04-19 14:52:10,135] Trial 46 finished with value: 0.1870275138752429 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 302, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7776896970279629, 'min_weight_fraction_leaf': 0.07225176694113553}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.21398697998771213
Fold 2 IBS: 0.22127076737509105
Fold 3 IBS: 0.204787245275916
Fold 4 IBS: 0.22464881989432967
Fold 5 IBS: 0.21857520577957465
[I 2024-04-19 14:52:19,645] Trial 47 finished with value: 0.21665380366252468 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 394, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5904360153291681, 'min_weight_fraction_leaf': 0.3242490493516816}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13680395735472003
Fold 2 IBS: 0.22883482339604239
Fold 3 IBS: 0.16837032388359582
Fold 4 IBS: 0.16000280315702775
Fold 5 IBS: 0.23281835611744003
[I 2024-04-19 14:52:29,713] Trial 48 finished with value: 0.1853660527817652 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8173484857489409, 'min_weight_fraction_leaf': 0.002401342777620552}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13753821864219098
Fold 2 IBS: 0.23322348156627426
Fold 3 IBS: 0.16650806858521439
Fold 4 IBS: 0.1593799860463597
Fold 5 IBS: 0.23477137343321255
[I 2024-04-19 14:52:37,522] Trial 49 finished with value: 0.18628422565465036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 358, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7602887007952065, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15407248993307796
Fold 2 IBS: 0.22331629611552672
Fold 3 IBS: 0.1686714717607006
Fold 4 IBS: 0.15910078917701373
Fold 5 IBS: 0.2294913527439736
[I 2024-04-19 14:52:49,036] Trial 50 finished with value: 0.18693047994605855 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 472, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8011524070042025, 'min_weight_fraction_leaf': 0.11371575955383911}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1292216590267733
Fold 2 IBS: 0.21535411859936704
Fold 3 IBS: 0.17364904066602752
Fold 4 IBS: 0.16832365810331645
Fold 5 IBS: 0.2341441204420188
[I 2024-04-19 14:52:58,205] Trial 51 finished with value: 0.18413851936750064 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 386, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8352773277741904, 'min_weight_fraction_leaf': 0.010409670541832795}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13661159522077607
Fold 2 IBS: 0.22298661504884923
Fold 3 IBS: 0.16890853299422418
Fold 4 IBS: 0.1613954589676683
Fold 5 IBS: 0.2291533277019588
[I 2024-04-19 14:53:07,436] Trial 52 finished with value: 0.1838111059866953 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 415, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8458630302918712, 'min_weight_fraction_leaf': 0.01883240853652938}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13285458221796065
Fold 2 IBS: 0.21324749338721247
Fold 3 IBS: 0.17437963072354587
Fold 4 IBS: 0.16754288596076145
Fold 5 IBS: 0.23216541507275276
[I 2024-04-19 14:53:15,035] Trial 53 finished with value: 0.18403800147244667 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 323, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7577087751903085, 'min_weight_fraction_leaf': 0.000926159316582905}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.21398748827861494
Fold 2 IBS: 0.2213335310951656
Fold 3 IBS: 0.20482302058163068
Fold 4 IBS: 0.2246762316540462
Fold 5 IBS: 0.218633693603778
[I 2024-04-19 14:53:23,303] Trial 54 finished with value: 0.2166907930426471 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6998643604561993, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15684384954039604
Fold 2 IBS: 0.21072872508349033
Fold 3 IBS: 0.1711788355891401
Fold 4 IBS: 0.16750388333602365
Fold 5 IBS: 0.2207016957578281
[I 2024-04-19 14:53:33,056] Trial 55 finished with value: 0.18539139786137562 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 432, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8588849365765647, 'min_weight_fraction_leaf': 0.05896276160735314}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13335973626684947
Fold 2 IBS: 0.21271799937980282
Fold 3 IBS: 0.1737325173775082
Fold 4 IBS: 0.16972405794405904
Fold 5 IBS: 0.2302689198189833
[I 2024-04-19 14:53:41,223] Trial 56 finished with value: 0.18396064615744057 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8050664718975571, 'min_weight_fraction_leaf': 0.026833183895911005}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13578108773552988
Fold 2 IBS: 0.22632586746444205
Fold 3 IBS: 0.17049332866303846
Fold 4 IBS: 0.16295298688829166
Fold 5 IBS: 0.23190382583631666
[I 2024-04-19 14:53:54,022] Trial 57 finished with value: 0.18549141931752372 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9066780831980561, 'min_weight_fraction_leaf': 0.04825981077573133}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1683187097373053
Fold 2 IBS: 0.24961534223709086
Fold 3 IBS: 0.16725029953662748
Fold 4 IBS: 0.16137357744447564
Fold 5 IBS: 0.24019843915652014
[I 2024-04-19 14:54:00,599] Trial 58 finished with value: 0.1973512736224039 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 278, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7227803228076407, 'min_weight_fraction_leaf': 0.099078961783115}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1783190622135976
Fold 2 IBS: 0.2019195895167403
Fold 3 IBS: 0.17861669574113284
Fold 4 IBS: 0.19082466174796836
Fold 5 IBS: 0.21301617946309295
[I 2024-04-19 14:54:09,863] Trial 59 finished with value: 0.1925392377365064 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 400, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9154352108935407, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.2139754605574802
Fold 2 IBS: 0.22128037493850963
Fold 3 IBS: 0.2049770044390806
Fold 4 IBS: 0.22468785016066256
Fold 5 IBS: 0.21820838836670314
[I 2024-04-19 14:54:20,961] Trial 60 finished with value: 0.21662581569248723 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.36612707136592737, 'min_weight_fraction_leaf': 0.2583710069782479}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13013980993149055
Fold 2 IBS: 0.21254887098310069
Fold 3 IBS: 0.17298441817166582
Fold 4 IBS: 0.16679488873081466
Fold 5 IBS: 0.2331102795997352
[I 2024-04-19 14:54:31,158] Trial 61 finished with value: 0.18311565348336137 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.775335953046553, 'min_weight_fraction_leaf': 0.00045996407747498497}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13907195085309992
Fold 2 IBS: 0.21746762441111264
Fold 3 IBS: 0.16991510579967217
Fold 4 IBS: 0.15698374953129748
Fold 5 IBS: 0.23092538229655435
[I 2024-04-19 14:54:42,282] Trial 62 finished with value: 0.1828727625783473 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7787336396982455, 'min_weight_fraction_leaf': 0.017049830964679567}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1461188072960583
Fold 2 IBS: 0.22297900373273485
Fold 3 IBS: 0.16819976748506882
Fold 4 IBS: 0.15627618251565928
Fold 5 IBS: 0.23056956630332018
[I 2024-04-19 14:54:52,483] Trial 63 finished with value: 0.18482866546656826 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 444, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.678914723196093, 'min_weight_fraction_leaf': 0.04051041185799438}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14922574781371922
Fold 2 IBS: 0.22336475015918203
Fold 3 IBS: 0.16766178110975566
Fold 4 IBS: 0.15767068769791207
Fold 5 IBS: 0.23077234127935545
[I 2024-04-19 14:55:00,788] Trial 64 finished with value: 0.1857390616119849 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7713563855654119, 'min_weight_fraction_leaf': 0.06466991810410304}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14196208017906697
Fold 2 IBS: 0.2203160952261016
Fold 3 IBS: 0.16893179777335507
Fold 4 IBS: 0.15654829756987573
Fold 5 IBS: 0.23125479899469772
[I 2024-04-19 14:55:11,986] Trial 65 finished with value: 0.18380261394861944 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.864019446775118, 'min_weight_fraction_leaf': 0.020950931739883927}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.21398363959846292
Fold 2 IBS: 0.2213068815502648
Fold 3 IBS: 0.20479920501202484
Fold 4 IBS: 0.22460863917083987
Fold 5 IBS: 0.2185893774573315
[I 2024-04-19 14:55:21,027] Trial 66 finished with value: 0.21665754855778477 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 435, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7911774756119411, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13566262450549949
Fold 2 IBS: 0.22523097017228863
Fold 3 IBS: 0.1692529598506911
Fold 4 IBS: 0.16290360566513454
Fold 5 IBS: 0.2327855372814568
[I 2024-04-19 14:55:30,162] Trial 67 finished with value: 0.18516713949501412 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7040452866645146, 'min_weight_fraction_leaf': 0.03968181972003887}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.16008903506031189
Fold 2 IBS: 0.20990936542664898
Fold 3 IBS: 0.1710695781803909
Fold 4 IBS: 0.1692741204721933
Fold 5 IBS: 0.2193567141991828
[I 2024-04-19 14:55:40,591] Trial 68 finished with value: 0.18593976266774556 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 458, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6460661483169103, 'min_weight_fraction_leaf': 0.05305571318039014}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14500196660262785
Fold 2 IBS: 0.22366958452892438
Fold 3 IBS: 0.16742407600195655
Fold 4 IBS: 0.1572461938806611
Fold 5 IBS: 0.23079281055431064
[I 2024-04-19 14:55:49,436] Trial 69 finished with value: 0.1848269263136961 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.741240523146211, 'min_weight_fraction_leaf': 0.014363934694956563}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15565332542931426
Fold 2 IBS: 0.24424811320133
Fold 3 IBS: 0.16435796348117546
Fold 4 IBS: 0.1566817157931589
Fold 5 IBS: 0.2377253059342244
[I 2024-04-19 14:55:55,285] Trial 70 finished with value: 0.1917332847678406 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 309, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8177202192771716, 'min_weight_fraction_leaf': 0.14671642748692168}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13181210182662045
Fold 2 IBS: 0.21744681600276494
Fold 3 IBS: 0.17176144698256085
Fold 4 IBS: 0.16552083875779053
Fold 5 IBS: 0.23275188447099712
[I 2024-04-19 14:56:04,889] Trial 71 finished with value: 0.18385861760814678 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8752727565742746, 'min_weight_fraction_leaf': 0.013546840661669626}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13664759508087293
Fold 2 IBS: 0.22296192467878798
Fold 3 IBS: 0.16930394076001695
Fold 4 IBS: 0.16231046577236227
Fold 5 IBS: 0.2282230432378881
[I 2024-04-19 14:56:15,079] Trial 72 finished with value: 0.18388939390598566 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8300877285214284, 'min_weight_fraction_leaf': 0.000532465790500053}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1346239998187586
Fold 2 IBS: 0.2204553274012152
Fold 3 IBS: 0.17118693884148742
Fold 4 IBS: 0.1634267645182296
Fold 5 IBS: 0.23111125243954722
[I 2024-04-19 14:56:23,003] Trial 73 finished with value: 0.1841608566038476 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8385554538360707, 'min_weight_fraction_leaf': 0.02810646380908776}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13390629681190472
Fold 2 IBS: 0.22698907202199678
Fold 3 IBS: 0.16758540501869873
Fold 4 IBS: 0.16229762462247163
Fold 5 IBS: 0.23484910404396492
[I 2024-04-19 14:56:32,960] Trial 74 finished with value: 0.18512550050380736 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7679190465908351, 'min_weight_fraction_leaf': 0.04679539158320054}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.1331805487459175
Fold 2 IBS: 0.21624338660783993
Fold 3 IBS: 0.1727837835092345
Fold 4 IBS: 0.16512709360909275
Fold 5 IBS: 0.23118212185240014
[I 2024-04-19 14:56:41,836] Trial 75 finished with value: 0.18370338686489696 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8812725582045702, 'min_weight_fraction_leaf': 0.014257699585348107}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14741275991375746
Fold 2 IBS: 0.22339111860096061
Fold 3 IBS: 0.16719852475388572
Fold 4 IBS: 0.1582361988967138
Fold 5 IBS: 0.23150079709187427
[I 2024-04-19 14:56:51,924] Trial 76 finished with value: 0.18554787985143836 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9673284169048014, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13394514154804674
Fold 2 IBS: 0.22177341115829846
Fold 3 IBS: 0.1690998786333866
Fold 4 IBS: 0.1657199477195138
Fold 5 IBS: 0.2305753710893013
[I 2024-04-19 14:57:00,451] Trial 77 finished with value: 0.1842227500297094 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9168074120653801, 'min_weight_fraction_leaf': 0.03429632080601785}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.16413207966902973
Fold 2 IBS: 0.20870718072258884
Fold 3 IBS: 0.17225544487357397
Fold 4 IBS: 0.17091089695041697
Fold 5 IBS: 0.21843171590077987
[I 2024-04-19 14:57:10,517] Trial 78 finished with value: 0.18688746362327788 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 481, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.06370344940214184}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1382247674913111
Fold 2 IBS: 0.2295727476203514
Fold 3 IBS: 0.1658109826697085
Fold 4 IBS: 0.159159006573788
Fold 5 IBS: 0.23538729964754349
[I 2024-04-19 14:57:20,130] Trial 79 finished with value: 0.18563096080054048 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 399, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.014909561272874527}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13345318600069242
Fold 2 IBS: 0.2165231635919131
Fold 3 IBS: 0.1731131915609491
Fold 4 IBS: 0.16900944810071544
Fold 5 IBS: 0.2316592394775838
[I 2024-04-19 14:57:30,632] Trial 80 finished with value: 0.18475164574637076 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 435, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7913828686899125, 'min_weight_fraction_leaf': 0.030163021360446518}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1321868314739457
Fold 2 IBS: 0.21527742532287938
Fold 3 IBS: 0.17246309786070207
Fold 4 IBS: 0.16556602486759034
Fold 5 IBS: 0.23185115051411426
[I 2024-04-19 14:57:39,432] Trial 81 finished with value: 0.18346890600784635 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8625539830672827, 'min_weight_fraction_leaf': 0.012219864563902087}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13001719869154457
Fold 2 IBS: 0.2163459254145058
Fold 3 IBS: 0.1719780027952196
Fold 4 IBS: 0.16474752365476744
Fold 5 IBS: 0.23403653328857743
[I 2024-04-19 14:57:48,628] Trial 82 finished with value: 0.18342503676892297 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 380, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.853725608486768, 'min_weight_fraction_leaf': 0.0007996961404084738}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13578697454596114
Fold 2 IBS: 0.2246792962521539
Fold 3 IBS: 0.16863613920292866
Fold 4 IBS: 0.16184068798076107
Fold 5 IBS: 0.23375626030677646
[I 2024-04-19 14:57:58,635] Trial 83 finished with value: 0.18493987165771625 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 406, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7513579683315326, 'min_weight_fraction_leaf': 0.042687170612983744}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14484272608511417
Fold 2 IBS: 0.2275675689794216
Fold 3 IBS: 0.16879529591083986
Fold 4 IBS: 0.15869000696689647
Fold 5 IBS: 0.2309434178220489
[I 2024-04-19 14:58:06,904] Trial 84 finished with value: 0.18616780315286424 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.00018702205865286415}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14630444194152487
Fold 2 IBS: 0.22324111246816955
Fold 3 IBS: 0.1684723371673193
Fold 4 IBS: 0.15748383644833983
Fold 5 IBS: 0.231655949614702
[I 2024-04-19 14:58:15,106] Trial 85 finished with value: 0.18543153552801112 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 329, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8089058835146683, 'min_weight_fraction_leaf': 0.031070527698653497}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.1336389770470042
Fold 2 IBS: 0.21912133230982853
Fold 3 IBS: 0.17125886949107771
Fold 4 IBS: 0.16302470803937694
Fold 5 IBS: 0.2310738851368272
[I 2024-04-19 14:58:25,561] Trial 86 finished with value: 0.18362355440482295 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 421, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7233398752849178, 'min_weight_fraction_leaf': 0.022456483517807643}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.15634749785775387
Fold 2 IBS: 0.20826490568132278
Fold 3 IBS: 0.1703584026567209
Fold 4 IBS: 0.16718116492468904
Fold 5 IBS: 0.22001159218206368
[I 2024-04-19 14:58:34,424] Trial 87 finished with value: 0.18443271266051003 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 353, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8238894970817884, 'min_weight_fraction_leaf': 0.05065759927412933}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14098048147522685
Fold 2 IBS: 0.23531327208330835
Fold 3 IBS: 0.16474065680610048
Fold 4 IBS: 0.1582355080734531
Fold 5 IBS: 0.23518291464789914
[I 2024-04-19 14:58:45,332] Trial 88 finished with value: 0.1868905666171976 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 455, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8446434140866994, 'min_weight_fraction_leaf': 0.08240102500283404}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13361909066838437
Fold 2 IBS: 0.22419453913237133
Fold 3 IBS: 0.17100752556815316
Fold 4 IBS: 0.1660035667866496
Fold 5 IBS: 0.2323807291125235
[I 2024-04-19 14:58:55,737] Trial 89 finished with value: 0.18544109025361638 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9488800447976891, 'min_weight_fraction_leaf': 0.000806200076917006}. Best is trial 42 with value: 0.18220424087625745.

Fold 1 IBS: 0.12988717417010312
Fold 2 IBS: 0.21111739221808115
Fold 3 IBS: 0.17281260544267968
Fold 4 IBS: 0.16744968489433068
Fold 5 IBS: 0.23530465742353276
[I 2024-04-19 14:59:02,170] Trial 90 finished with value: 0.18331430282974548 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 317, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7774148609541289, 'min_weight_fraction_leaf': 0.011005982719496389}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.12951620582034926
Fold 2 IBS: 0.210867217186133
Fold 3 IBS: 0.17327356003962616
Fold 4 IBS: 0.16765928672732763
Fold 5 IBS: 0.2351767398201044
[I 2024-04-19 14:59:09,838] Trial 91 finished with value: 0.1832986019187081 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 322, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7781808052399918, 'min_weight_fraction_leaf': 0.01374012670873183}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.13365970503909627
Fold 2 IBS: 0.2203990045693183
Fold 3 IBS: 0.1719809794463351
Fold 4 IBS: 0.1659275988455526
Fold 5 IBS: 0.2310461126564287
[I 2024-04-19 14:59:15,754] Trial 92 finished with value: 0.1846026801113462 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7850185292906079, 'min_weight_fraction_leaf': 0.03722989027730587}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.12777378019441304
Fold 2 IBS: 0.2103658906995854
Fold 3 IBS: 0.17326068363598274
Fold 4 IBS: 0.1681953545772438
Fold 5 IBS: 0.2351533313692652
[I 2024-04-19 14:59:24,141] Trial 93 finished with value: 0.18294980809529804 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 328, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7779587706658339, 'min_weight_fraction_leaf': 0.009311683805295526}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14857803579143394
Fold 2 IBS: 0.20918836940525298
Fold 3 IBS: 0.1688618315206691
Fold 4 IBS: 0.16374621373038312
Fold 5 IBS: 0.22223318272254292
[I 2024-04-19 14:59:30,912] Trial 94 finished with value: 0.1825215266340564 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6743157809017337, 'min_weight_fraction_leaf': 0.022016337499591185}. Best is trial 42 with value: 0.18220424087625745.
Fold 1 IBS: 0.14318063826069696
Fold 2 IBS: 0.20900427100439892
Fold 3 IBS: 0.16849069305388098
Fold 4 IBS: 0.1615555973109128
Fold 5 IBS: 0.2229893711651227
[I 2024-04-19 14:59:37,858] Trial 95 finished with value: 0.1810441141590025 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7098772062937373, 'min_weight_fraction_leaf': 0.012799049735992758}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.16025790354872743
Fold 2 IBS: 0.21063171316283893
Fold 3 IBS: 0.17113063455571145
Fold 4 IBS: 0.1694766923206728
Fold 5 IBS: 0.22010196737994892
[I 2024-04-19 14:59:44,795] Trial 96 finished with value: 0.1863197821935799 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6948087465011815, 'min_weight_fraction_leaf': 0.0592892883568545}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.18027221741116026
Fold 2 IBS: 0.20868443032134176
Fold 3 IBS: 0.1805960012942096
Fold 4 IBS: 0.19192844137806864
Fold 5 IBS: 0.21569000579227957
[I 2024-04-19 14:59:51,756] Trial 97 finished with value: 0.19543421923941198 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7271967081655182, 'min_weight_fraction_leaf': 0.02654927328611698}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.15658766261322524
Fold 2 IBS: 0.20896735975747097
Fold 3 IBS: 0.16973603267155693
Fold 4 IBS: 0.16879223967676366
Fold 5 IBS: 0.22161586321168347
[I 2024-04-19 14:59:58,778] Trial 98 finished with value: 0.18513983158614006 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6737745771706081, 'min_weight_fraction_leaf': 0.0434038722130365}. Best is trial 95 with value: 0.1810441141590025.
Fold 1 IBS: 0.1662721546014814
Fold 2 IBS: 0.2096645157784754
Fold 3 IBS: 0.1738820252882844
Fold 4 IBS: 0.17586626741763942
Fold 5 IBS: 0.2187259900953022
[I 2024-04-19 15:00:07,060] Trial 99 finished with value: 0.18888219063623657 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 305, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7500938622905841, 'min_weight_fraction_leaf': 0.10104599371859008}. Best is trial 95 with value: 0.1810441141590025.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.1810441141590025], datetime_start=datetime.datetime(2024, 4, 19, 14, 59, 30, 920486), datetime_complete=datetime.datetime(2024, 4, 19, 14, 59, 37, 857112), params={'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7098772062937373, 'min_weight_fraction_leaf': 0.012799049735992758}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=95, value=None)


* Best Score for IBS:
 0.1810441141590025

In [62]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.816
train_ibs:  0.181

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=11, max_leaf_nodes=13,
                   max_samples=0.9554816381741302, min_samples_leaf=1,
                   min_samples_split=17,
                   min_weight_fraction_leaf=0.026333169142875475,
                   n_estimators=68, random_state=123, warm_start=True)

C-index score: 0.656

ExtraSurvivalTrees(max_depth=13, max_features=1, max_leaf_nodes=11,
                   max_samples=0.7098772062937373, min_samples_leaf=1,
                   min_samples_split=14,
                   min_weight_fraction_leaf=0.012799049735992758,
                   n_estimators=288, oob_score=True, random_state=123,
                   warm_start=True)

IBS: 0.214

In [66]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 15:00:09,672] A new study created in memory with name: no-name-be8abf21-629a-4b4c-9349-1d82acb93c86

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:00:46,667] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:01:06,549] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:01:26,426] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:01:58,493] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:09,944] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:13,350] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:44,997] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:58,118] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:02:59,895] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.8376623376623377
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.6690140845070423
[I 2024-04-19 15:04:31,811] Trial 9 finished with value: 0.7471201964999683 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 15:06:45,155] Trial 10 finished with value: 0.6769991466942861 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:09:14,868] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.803030303030303
Fold 2 C-index: 0.6986607142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 15:11:21,835] Trial 12 finished with value: 0.7331503156498502 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:12:21,209] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:13:48,472] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:15:04,589] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:15:54,097] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:17:38,575] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:19:59,276] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:20:04,676] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:20:56,419] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 15:22:52,561] Trial 21 finished with value: 0.6596743990023763 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7471201964999683.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7362869198312236
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 15:24:37,907] Trial 22 finished with value: 0.7520782207516631 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:25:57,576] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:27:12,727] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.7520782207516631.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:28:00,280] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.636150234741784
[I 2024-04-19 15:29:38,781] Trial 26 finished with value: 0.5848042633437757 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:31:12,988] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:32:25,975] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:33:14,475] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:34:18,967] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6103286384976526
[I 2024-04-19 15:36:11,782] Trial 31 finished with value: 0.6975838362663174 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:38:01,580] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9113568740147856, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.1444594228310892, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 1.6183832787391992, 'min_weight_fraction_leaf': 0.4304319218036696, 'max_features': 'auto', 'min_impurity_decrease': 1.0277484189219154e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:39:37,774] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9728428556912192, 'learning_rate': 0.015742740923125064, 'dropout_rate': 0.30020186346124766, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.4958404435609285, 'max_features': 'auto', 'min_impurity_decrease': 2.2786499479002052e-07, 'validation_fraction': 0.8344453462672722, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:40:51,994] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.8496036715186095, 'learning_rate': 0.009253864701923034, 'dropout_rate': 0.22658656718653286, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.641857272630336, 'min_weight_fraction_leaf': 0.43629024868714544, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9168532630851701, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:41:09,007] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6806458891075314, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.4078621112435248, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3706867126320781, 'max_features': None, 'min_impurity_decrease': 7.8587698841458e-07, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:42:37,191] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.9551502281749775, 'learning_rate': 0.026078126474550274, 'dropout_rate': 0.34789169882120996, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.40891402270131877, 'min_weight_fraction_leaf': 0.2325827619040188, 'max_features': 'auto', 'min_impurity_decrease': 7.145093229830912e-06, 'validation_fraction': 0.6747809687204889, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.7520782207516631.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:42:42,696] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7371581418455209, 'learning_rate': 0.0145417341576766, 'dropout_rate': 0.16172130996739253, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.3174537146690439, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.9548743578197549, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:43:02,651] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.8063221166350547, 'learning_rate': 0.006424315075939495, 'dropout_rate': 0.7673236646699829, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 9.162989248724866, 'min_weight_fraction_leaf': 0.14601082900734919, 'max_features': 'auto', 'min_impurity_decrease': 1.1529415174162498e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:44:25,323] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.8852748015168422, 'learning_rate': 0.02975783779377629, 'dropout_rate': 0.2673592786040255, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1216454788806307, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 8.588272604740831e-07, 'validation_fraction': 0.7628102853958754, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:45:22,989] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5809866593286652, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.20816102573612866, 'n_estimators': 353, 'criterion': 'squared_error', 'ccp_alpha': 3.7898554763179284, 'min_weight_fraction_leaf': 0.4711996214427754, 'max_features': 'auto', 'min_impurity_decrease': 2.3584088371991464e-07, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5821596244131455
[I 2024-04-19 15:45:23,385] Trial 41 finished with value: 0.6152707311185872 and parameters: {'subsample': 0.9964498482283193, 'learning_rate': 0.004158109708816752, 'dropout_rate': 0.13644226542045526, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4011310798872364, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.9993318631652353, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:47:18,262] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.10858843727097561, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.415120560514267, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:48:06,488] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.919916216831853, 'learning_rate': 0.0016321845585985228, 'dropout_rate': 0.16429624388711278, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.471921644995546, 'min_weight_fraction_leaf': 0.3704175909956657, 'max_features': 'auto', 'min_impurity_decrease': 0.0009050261380449993, 'validation_fraction': 0.8779568222622545, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:49:04,348] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.015327765728784649, 'dropout_rate': 0.6859431566383477, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.2679892492803537, 'min_weight_fraction_leaf': 0.2706416993480579, 'max_features': 'auto', 'min_impurity_decrease': 8.738793222106795e-07, 'validation_fraction': 0.9744834265061879, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 15:50:27,549] Trial 45 finished with value: 0.7210598007254247 and parameters: {'subsample': 0.8612793275132423, 'learning_rate': 0.008591203396202965, 'dropout_rate': 0.20237082649972205, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.09266970930573763, 'min_weight_fraction_leaf': 0.4478112124993417, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.798828420958444, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:50:37,820] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8576868620948644, 'learning_rate': 0.021769927230194788, 'dropout_rate': 0.9694253886674298, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.45430295635160706, 'max_features': 0.1, 'min_impurity_decrease': 2.0131584568637675e-06, 'validation_fraction': 0.7976029227783121, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:51:06,066] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7056873961179977, 'learning_rate': 0.00929853233926034, 'dropout_rate': 0.3140351257259953, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.49464896810642006, 'max_features': 0.1, 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.6179698437276481, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:52:31,702] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7837245323509484, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.21043558082214228, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.4617743734350054, 'min_weight_fraction_leaf': 0.45246089314517907, 'max_features': 0.1, 'min_impurity_decrease': 4.221379974644956e-07, 'validation_fraction': 0.863214331971344, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 22 with value: 0.7520782207516631.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:53:09,469] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.6507081753968225, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.26780621294484797, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 1.378218906104398, 'min_weight_fraction_leaf': 0.2916489694540698, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6845184717076465, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:54:26,221] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.03353370774351387, 'dropout_rate': 0.3787195779305788, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.7561621193902213, 'min_weight_fraction_leaf': 0.47814765735031256, 'max_features': 0.1, 'min_impurity_decrease': 1.6961878462023105e-07, 'validation_fraction': 0.8310153288008191, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7520782207516631.
Fold 1 C-index: 0.8203463203463204
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.7827004219409283
Fold 5 C-index: 0.6596244131455399
[I 2024-04-19 15:56:32,241] Trial 51 finished with value: 0.772553488789639 and parameters: {'subsample': 0.9590755303360702, 'learning_rate': 0.001263628446733103, 'dropout_rate': 0.13293847894616523, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 51 with value: 0.772553488789639.
Fold 1 C-index: 0.8268398268398268
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6643192488262911
[I 2024-04-19 15:58:21,547] Trial 52 finished with value: 0.7782542196646564 and parameters: {'subsample': 0.9309483691931049, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.1309992574789837, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.036615235505588, 'min_weight_fraction_leaf': 0.4052806656624778, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8184597843569143e-07, 'validation_fraction': 0.8992446934973449, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 15:59:39,247] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9119792149240027, 'learning_rate': 0.0011619738930768678, 'dropout_rate': 0.12019527221159815, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.33436888398209985, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0912509934146174e-06, 'validation_fraction': 0.7204767494493249, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:00:06,768] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9422391559777883, 'learning_rate': 0.006469543850280348, 'dropout_rate': 0.8266353856620614, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.46449392886564433, 'min_weight_fraction_leaf': 0.20818644825744925, 'max_features': 'sqrt', 'min_impurity_decrease': 3.17346833824979e-07, 'validation_fraction': 0.8741639290304148, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:01:21,867] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8715328822130523, 'learning_rate': 0.011790338191706525, 'dropout_rate': 0.23926982708415356, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.4008945876330496, 'min_weight_fraction_leaf': 0.44051010658711054, 'max_features': 'sqrt', 'min_impurity_decrease': 5.615119149330365e-07, 'validation_fraction': 0.7887577239921508, 'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:02:58,612] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8015434219726096, 'learning_rate': 0.04061736247319854, 'dropout_rate': 0.1937709311352404, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.037591557618962, 'min_weight_fraction_leaf': 0.41307911755286036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.854323715915516e-06, 'validation_fraction': 0.907633472782051, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 52 with value: 0.7782542196646564.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6690140845070423
[I 2024-04-19 16:03:34,231] Trial 57 finished with value: 0.781123328823093 and parameters: {'subsample': 0.47167111494444647, 'learning_rate': 0.018997287630538016, 'dropout_rate': 0.5891903890315894, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.007297661499282945, 'min_weight_fraction_leaf': 0.37949114392069716, 'max_features': 'sqrt', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.5599065409082953, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 57 with value: 0.781123328823093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:04:26,651] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.42473576655735995, 'learning_rate': 0.018900335501351662, 'dropout_rate': 0.6195846181212514, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.7489235673712139, 'min_weight_fraction_leaf': 0.37172290689803544, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.5649807819209639, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 57 with value: 0.781123328823093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:04:58,291] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.4705271187560865, 'learning_rate': 0.021814358601443318, 'dropout_rate': 0.7119170684357518, 'n_estimators': 374, 'criterion': 'squared_error', 'ccp_alpha': 1.429314535364776, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': 'sqrt', 'min_impurity_decrease': 5.188349818876903e-07, 'validation_fraction': 0.4822753579684245, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 57 with value: 0.781123328823093.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:05:38,392] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.5340859352401606, 'learning_rate': 0.025149879907566695, 'dropout_rate': 0.6358545234388486, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.8721071580406399, 'min_weight_fraction_leaf': 0.2617324012356312, 'max_features': 'sqrt', 'min_impurity_decrease': 3.1935923441647085e-07, 'validation_fraction': 0.41178016017445873, 'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.781123328823093.

Fold 1 C-index: 0.8484848484848485
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7573839662447257
Fold 5 C-index: 0.6690140845070423
[I 2024-04-19 16:06:26,915] Trial 61 finished with value: 0.7834342129005446 and parameters: {'subsample': 0.319800669455551, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.5959135142579131, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.3768225293955428, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9022954194826543e-07, 'validation_fraction': 0.9463803671108196, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 61 with value: 0.7834342129005446.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.687793427230047
[I 2024-04-19 16:07:18,179] Trial 62 finished with value: 0.7856240407595962 and parameters: {'subsample': 0.26730245398299407, 'learning_rate': 0.005570953859927015, 'dropout_rate': 0.5689698891552257, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.022377389338332464, 'min_weight_fraction_leaf': 0.3409131872515221, 'max_features': 'sqrt', 'min_impurity_decrease': 1.85269269758306e-07, 'validation_fraction': 0.9450344863737145, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 62 with value: 0.7856240407595962.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:08:13,079] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.21664597025713805, 'learning_rate': 0.012813076208169889, 'dropout_rate': 0.5693919318511333, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.4119356056831134, 'min_weight_fraction_leaf': 0.3347054705435437, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8279573515116132e-07, 'validation_fraction': 0.9497483584074397, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 62 with value: 0.7856240407595962.
Fold 1 C-index: 0.8484848484848485
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:09:15,528] Trial 64 finished with value: 0.786026040547988 and parameters: {'subsample': 0.34331456059062987, 'learning_rate': 0.005335751023510593, 'dropout_rate': 0.5293390090928782, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.0425951526045976, 'min_weight_fraction_leaf': 0.38936421852537745, 'max_features': 'sqrt', 'min_impurity_decrease': 3.017573951575898e-07, 'validation_fraction': 0.8901592560354066, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 64 with value: 0.786026040547988.
Fold 1 C-index: 0.8441558441558441
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6784037558685446
[I 2024-04-19 16:10:17,693] Trial 65 finished with value: 0.7897581704037714 and parameters: {'subsample': 0.3390231900132655, 'learning_rate': 0.005751881948804041, 'dropout_rate': 0.5630376022581163, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.002745627425376866, 'min_weight_fraction_leaf': 0.3871530270040246, 'max_features': 'sqrt', 'min_impurity_decrease': 6.694579707208464e-07, 'validation_fraction': 0.18033435762270877, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:10:55,319] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.3211741793059686, 'learning_rate': 0.00520162993595177, 'dropout_rate': 0.5728129835100113, 'n_estimators': 358, 'criterion': 'squared_error', 'ccp_alpha': 0.3310950042218784, 'min_weight_fraction_leaf': 0.38274388203487975, 'max_features': 'sqrt', 'min_impurity_decrease': 2.724029141952152e-06, 'validation_fraction': 0.3085811036906729, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 6}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:12:01,166] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.23594984519111556, 'learning_rate': 0.005404142410171992, 'dropout_rate': 0.4929299984506029, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 1.1937792228430404, 'min_weight_fraction_leaf': 0.3475526868546416, 'max_features': 'sqrt', 'min_impurity_decrease': 6.424725819821063e-07, 'validation_fraction': 0.2826913354575118, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:13:05,089] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.34683185742787537, 'learning_rate': 0.09805784604547818, 'dropout_rate': 0.5384700399262299, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.7692354450958495, 'min_weight_fraction_leaf': 0.41749893021198126, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0616801934559534e-06, 'validation_fraction': 0.23471568192107903, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:14:13,783] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.2861177658813064, 'learning_rate': 0.017944099553551186, 'dropout_rate': 0.43389463986071763, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 6.319375173875926, 'min_weight_fraction_leaf': 0.3792527429968225, 'max_features': 'sqrt', 'min_impurity_decrease': 1.496310137618593e-07, 'validation_fraction': 0.13907775132396938, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 15}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:15:15,189] Trial 70 finished with value: 0.7847059641860278 and parameters: {'subsample': 0.3774724270129156, 'learning_rate': 0.011124381782250005, 'dropout_rate': 0.650277108598025, 'n_estimators': 484, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010159515082891972, 'min_weight_fraction_leaf': 0.362344472986224, 'max_features': 'sqrt', 'min_impurity_decrease': 2.747211987721928e-07, 'validation_fraction': 0.8434879817738963, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:16:17,205] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.3772867510834654, 'learning_rate': 0.009873817799557231, 'dropout_rate': 0.638940448874788, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2585767773696627, 'min_weight_fraction_leaf': 0.3593001481583254, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6411726759754516e-07, 'validation_fraction': 0.892722402960641, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 65 with value: 0.7897581704037714.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:17:15,193] Trial 72 finished with value: 0.7900631070431706 and parameters: {'subsample': 0.42289594631245, 'learning_rate': 0.003999192670171843, 'dropout_rate': 0.5771575036069397, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004870343735235726, 'min_weight_fraction_leaf': 0.3982179938524501, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0115746656852655e-07, 'validation_fraction': 0.8408360882819792, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:17:58,725] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.4161743419322261, 'learning_rate': 0.01646575593094526, 'dropout_rate': 0.5934540934399337, 'n_estimators': 393, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6105529211816056, 'min_weight_fraction_leaf': 0.4064927557251237, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0373937877450991e-07, 'validation_fraction': 0.8429645916964783, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:19:02,960] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.3677729229747588, 'learning_rate': 0.006293476681503581, 'dropout_rate': 0.5119552573516976, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3244777939229942, 'min_weight_fraction_leaf': 0.33489971298250326, 'max_features': 'sqrt', 'min_impurity_decrease': 4.223038253919878e-07, 'validation_fraction': 0.7344816284775862, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:19:53,802] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.2903900357122111, 'learning_rate': 0.012973381912704278, 'dropout_rate': 0.6645294261386104, 'n_estimators': 433, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8094042116304128, 'min_weight_fraction_leaf': 0.3587496831264275, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0390269391384854e-07, 'validation_fraction': 0.8568404234029825, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:20:34,010] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.44036493992983516, 'learning_rate': 0.003895017959761613, 'dropout_rate': 0.7235352189729908, 'n_estimators': 460, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3011411348311229, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 6.551998916484513e-07, 'validation_fraction': 0.35120610496528537, 'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:21:12,320] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5030732468010138, 'learning_rate': 0.010318303683782707, 'dropout_rate': 0.55495865381036, 'n_estimators': 374, 'criterion': 'friedman_mse', 'ccp_alpha': 2.2261370357947867, 'min_weight_fraction_leaf': 0.3946892587694452, 'max_features': 'sqrt', 'min_impurity_decrease': 1.477390188984205e-07, 'validation_fraction': 0.8226290169133673, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:21:20,395] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.25891843939074943, 'learning_rate': 0.013618481172327222, 'dropout_rate': 0.5929458556614376, 'n_estimators': 163, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0768522145163504, 'min_weight_fraction_leaf': 0.42107281791067985, 'max_features': 'sqrt', 'min_impurity_decrease': 2.5818809372490893e-07, 'validation_fraction': 0.1709569658480536, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:22:37,630] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.12891422333306404, 'learning_rate': 0.007724344499863844, 'dropout_rate': 0.44904550180852654, 'n_estimators': 486, 'criterion': 'friedman_mse', 'ccp_alpha': 0.005965678681071493, 'min_weight_fraction_leaf': 0.3933038023418368, 'max_features': None, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.037974227411897016, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:23:25,233] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.3144678268216224, 'learning_rate': 0.003933423769250072, 'dropout_rate': 0.5376517061433939, 'n_estimators': 416, 'criterion': 'friedman_mse', 'ccp_alpha': 4.739756973970751, 'min_weight_fraction_leaf': 0.3656961834749051, 'max_features': 1, 'min_impurity_decrease': 0.000321859747788374, 'validation_fraction': 0.8934322384554279, 'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:24:15,886] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.3574265068335679, 'learning_rate': 0.0012397272499832656, 'dropout_rate': 0.6729323707765625, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.6406854872661993, 'min_weight_fraction_leaf': 0.3798799998701948, 'max_features': 'sqrt', 'min_impurity_decrease': 1.857443105250775e-07, 'validation_fraction': 0.9565934036182363, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.8398268398268398
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 16:25:25,343] Trial 82 finished with value: 0.7753168921014978 and parameters: {'subsample': 0.40555469208261735, 'learning_rate': 0.006717506934730347, 'dropout_rate': 0.6309816700892386, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.018184135202982572, 'min_weight_fraction_leaf': 0.34175759184922644, 'max_features': 'sqrt', 'min_impurity_decrease': 4.4229121687330197e-07, 'validation_fraction': 0.9310412285264067, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 16:26:37,004] Trial 83 finished with value: 0.6925176672072417 and parameters: {'subsample': 0.4021210454834687, 'learning_rate': 0.00967440772841731, 'dropout_rate': 0.6168787838223372, 'n_estimators': 496, 'criterion': 'friedman_mse', 'ccp_alpha': 0.19967719155635735, 'min_weight_fraction_leaf': 0.3451328688427247, 'max_features': 'sqrt', 'min_impurity_decrease': 4.502255281481611e-07, 'validation_fraction': 0.9235910988376809, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:27:07,299] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.46939653554524097, 'learning_rate': 0.007513599522063374, 'dropout_rate': 0.821691123019113, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5540358584093127, 'min_weight_fraction_leaf': 0.3037992576953221, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0775924853240628e-06, 'validation_fraction': 0.9688665543922645, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 72 with value: 0.7900631070431706.

Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 16:28:07,884] Trial 85 finished with value: 0.7729809585587262 and parameters: {'subsample': 0.38573804052349686, 'learning_rate': 0.052741323552683156, 'dropout_rate': 0.6921135637698407, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01112533755039441, 'min_weight_fraction_leaf': 0.32360543928998425, 'max_features': 'sqrt', 'min_impurity_decrease': 1.376498986419818e-07, 'validation_fraction': 0.7732538542931726, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:28:56,972] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.4471491324763385, 'learning_rate': 0.08767662742937916, 'dropout_rate': 0.6433246180507093, 'n_estimators': 484, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5208204158471001, 'min_weight_fraction_leaf': 0.4258155364780357, 'max_features': 'log2', 'min_impurity_decrease': 3.3108218532416555e-07, 'validation_fraction': 0.9302527299193313, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:29:13,687] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.3059124344357447, 'learning_rate': 0.017000056781688845, 'dropout_rate': 0.5753138611140339, 'n_estimators': 266, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8939721870634515, 'min_weight_fraction_leaf': 0.39766156297021943, 'max_features': 'sqrt', 'min_impurity_decrease': 7.257875823452126e-07, 'validation_fraction': 0.8942531173715377, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:30:03,633] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.3390640822352382, 'learning_rate': 0.020951330544439258, 'dropout_rate': 0.5009856651818354, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 8.088457238075051, 'min_weight_fraction_leaf': 0.40810963176734805, 'max_features': 'sqrt', 'min_impurity_decrease': 2.329078771156988e-07, 'validation_fraction': 0.8535804780735345, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:30:46,087] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.501210787330669, 'learning_rate': 0.004039454116789691, 'dropout_rate': 0.5315084686509086, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.262115769740312, 'min_weight_fraction_leaf': 0.3550762826973989, 'max_features': 'sqrt', 'min_impurity_decrease': 5.000296444465733e-07, 'validation_fraction': 0.6577544168504801, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:31:34,914] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3969009416299629, 'learning_rate': 0.011038951399379136, 'dropout_rate': 0.5911491931771738, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 1.20306042705909, 'min_weight_fraction_leaf': 0.3395185145856917, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3085362819964039e-06, 'validation_fraction': 0.9980112998955034, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.8354978354978355
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 16:32:19,534] Trial 91 finished with value: 0.7683617021461335 and parameters: {'subsample': 0.3710685773618577, 'learning_rate': 0.05060252500154345, 'dropout_rate': 0.7112267377565065, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038311453954747145, 'min_weight_fraction_leaf': 0.32399238617651593, 'max_features': 'sqrt', 'min_impurity_decrease': 1.2898230424577564e-07, 'validation_fraction': 0.76803640233329, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:32:51,252] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.24560298186792678, 'learning_rate': 0.05793741709178523, 'dropout_rate': 0.7425784246769499, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5955982791717448, 'min_weight_fraction_leaf': 0.32582543700307265, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0039386816564054e-07, 'validation_fraction': 0.8298125376468664, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:33:25,746] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.19114788292027068, 'learning_rate': 0.006759108786508056, 'dropout_rate': 0.6823186731821831, 'n_estimators': 435, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3763825346182167, 'min_weight_fraction_leaf': 0.36623610433160614, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2785210161928306e-07, 'validation_fraction': 0.877327076579441, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5985915492957746
[I 2024-04-19 16:34:14,588] Trial 94 finished with value: 0.6395846180049679 and parameters: {'subsample': 0.423015330597536, 'learning_rate': 0.0437490470487491, 'dropout_rate': 0.6521695143575769, 'n_estimators': 484, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23680614346106993, 'min_weight_fraction_leaf': 0.37828079175958235, 'max_features': None, 'min_impurity_decrease': 1.3449106353124824e-07, 'validation_fraction': 0.7831338496745038, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:35:03,993] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.2663705028170775, 'learning_rate': 0.05047840916818071, 'dropout_rate': 0.6198131665729131, 'n_estimators': 467, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6518567922515498, 'min_weight_fraction_leaf': 0.3069519947028543, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.8159365517337362, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 72 with value: 0.7900631070431706.
Fold 1 C-index: 0.8311688311688312
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.6924882629107981
[I 2024-04-19 16:35:36,719] Trial 96 finished with value: 0.7912820517273182 and parameters: {'subsample': 0.38604321258984187, 'learning_rate': 0.05396213117321635, 'dropout_rate': 0.6934300990357392, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.030433464476024484, 'min_weight_fraction_leaf': 0.38729753243593296, 'max_features': 1, 'min_impurity_decrease': 3.7676942671090066e-07, 'validation_fraction': 0.9213195792266449, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 96 with value: 0.7912820517273182.

Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:36:21,681] Trial 97 finished with value: 0.5469155844155844 and parameters: {'subsample': 0.334801811655963, 'learning_rate': 0.06226809094817951, 'dropout_rate': 0.5562831195117867, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.22723942954454154, 'min_weight_fraction_leaf': 0.3898326763187332, 'max_features': 1, 'min_impurity_decrease': 7.784668787793484e-05, 'validation_fraction': 0.9343491435456887, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 96 with value: 0.7912820517273182.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 16:37:01,757] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5704320380294472, 'learning_rate': 0.014236947521345914, 'dropout_rate': 0.46833983664280443, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.9743600736120059, 'min_weight_fraction_leaf': 0.4403782284758478, 'max_features': 1, 'min_impurity_decrease': 4.1978650730403767e-07, 'validation_fraction': 0.9737989432872376, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 96 with value: 0.7912820517273182.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-19 16:37:37,562] A new study created in memory with name: no-name-468ae07c-2ea6-45e2-9cdf-3bce6b1fceb4

Fold 5 C-index: 0.5
[I 2024-04-19 16:37:37,432] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.44973533951085454, 'learning_rate': 0.06941318862082362, 'dropout_rate': 0.6076064350817783, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.7029501932062083, 'min_weight_fraction_leaf': 0.4081649924422779, 'max_features': 1, 'min_impurity_decrease': 7.911599321468388e-07, 'validation_fraction': 0.9037866359790525, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 96 with value: 0.7912820517273182.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7912820517273182], datetime_start=datetime.datetime(2024, 4, 19, 16, 35, 4, 4579), datetime_complete=datetime.datetime(2024, 4, 19, 16, 35, 36, 716701), params={'subsample': 0.38604321258984187, 'learning_rate': 0.05396213117321635, 'dropout_rate': 0.6934300990357392, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.030433464476024484, 'min_weight_fraction_leaf': 0.38729753243593296, 'max_features': 1, 'min_impurity_decrease': 3.7676942671090066e-07, 'validation_fraction': 0.9213195792266449, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 7}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7912820517273182

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:38:14,372] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:38:32,838] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:38:47,121] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:39:09,405] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:39:20,000] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:39:22,477] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:39:49,907] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:39:58,349] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:39:59,509] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21260169564761522
Fold 2 IBS: 0.2208117276566402
Fold 3 IBS: 0.20334487960536277
Fold 4 IBS: 0.22388122768542051
Fold 5 IBS: 0.217665915754874
[I 2024-04-19 16:41:04,571] Trial 9 finished with value: 0.21566108926998254 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21360363678959007
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.20421474792063551
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21803455300047256
[I 2024-04-19 16:42:35,135] Trial 10 finished with value: 0.21637936117854983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 16:44:00,471] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21383760159283438
Fold 2 IBS: 0.22154057816926387
Fold 3 IBS: 0.20441416271188637
Fold 4 IBS: 0.22468479705215127
Fold 5 IBS: 0.21808800811495244
[I 2024-04-19 16:45:19,757] Trial 12 finished with value: 0.2165130295282177 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-19 16:45:54,546] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:46:52,975] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:47:41,153] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:48:08,772] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:49:29,395] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:50:09,205] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:50:15,758] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:51:27,367] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21390574994112835
Fold 2 IBS: 0.22156131309595062
Fold 3 IBS: 0.2045078758011969
Fold 4 IBS: 0.22466878152435252
Fold 5 IBS: 0.21808456363125545
[I 2024-04-19 16:52:45,764] Trial 21 finished with value: 0.21654565679877677 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21250390766170438
Fold 2 IBS: 0.22090992293124842

Fold 3 IBS: 0.20322775423820424
Fold 4 IBS: 0.22409416642697289
Fold 5 IBS: 0.21764473279143468
[I 2024-04-19 16:54:05,922] Trial 22 finished with value: 0.2156760968099129 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 16:55:03,847] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:55:41,403] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:56:17,551] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 16:57:10,990] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:57:16,445] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:57:35,701] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 16:58:23,328] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 16:58:45,608] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21355264316168573
Fold 2 IBS: 0.22149663133331596
Fold 3 IBS: 0.2042721330591835
Fold 4 IBS: 0.2245750034693936
Fold 5 IBS: 0.21801491575167778
[I 2024-04-19 16:59:45,690] Trial 31 finished with value: 0.21638226535505134 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.2129290559388716
Fold 2 IBS: 0.22124897719545888
Fold 3 IBS: 0.20355672808732653
Fold 4 IBS: 0.2242978455111631
Fold 5 IBS: 0.21777645297475517
[I 2024-04-19 17:00:45,271] Trial 32 finished with value: 0.21596181194151506 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 17:01:29,406] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:02:17,811] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:02:28,438] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:03:28,396] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:03:30,077] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:04:03,249] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-19 17:04:42,775] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:05:24,495] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.2132255688615536
Fold 2 IBS: 0.22128032488867244
Fold 3 IBS: 0.20387628490474263
Fold 4 IBS: 0.22433695432297887
Fold 5 IBS: 0.21781307301495534
[I 2024-04-19 17:06:26,145] Trial 41 finished with value: 0.2161064411985806 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21292377393992548
Fold 2 IBS: 0.2210315141123993
Fold 3 IBS: 0.20354491815270298
Fold 4 IBS: 0.2240992473287711
Fold 5 IBS: 0.21771341609424547
[I 2024-04-19 17:07:29,998] Trial 42 finished with value: 0.21586257392560887 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:08:38,445] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:09:28,350] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21349094495081627
Fold 2 IBS: 0.22124593056297892
Fold 3 IBS: 0.204117127502029
Fold 4 IBS: 0.22430959830372146
Fold 5 IBS: 0.21795638009371607
[I 2024-04-19 17:10:25,124] Trial 45 finished with value: 0.21622399628265235 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:11:26,710] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:11:53,500] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:11:53,939] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:12:08,918] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:13:06,662] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21352229431826772
Fold 2 IBS: 0.22126527530151524
Fold 3 IBS: 0.20414449796344677
Fold 4 IBS: 0.22431579388786133
Fold 5 IBS: 0.2179677238529516
[I 2024-04-19 17:13:51,279] Trial 51 finished with value: 0.21624311706480853 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 17:14:54,387] Trial 52 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 9 with value: 0.21566108926998254.
Fold 1 IBS: 0.2126658954267114
Fold 2 IBS: 0.22068287915798293
Fold 3 IBS: 0.20338530082480633
Fold 4 IBS: 0.22347723643576087
Fold 5 IBS: 0.21769588001309007
[I 2024-04-19 17:16:00,574] Trial 53 finished with value: 0.21558143837167032 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:17:37,909] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:19:57,511] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:22:18,811] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 17:25:36,373] Trial 57 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:29:48,843] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 17:33:04,484] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 17:34:39,956] Trial 60 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-19 17:37:01,410] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21325207586655212
Fold 2 IBS: 0.22108799107389968
Fold 3 IBS: 0.20389758437073804
Fold 4 IBS: 0.2241108961061006
Fold 5 IBS: 0.21791219598548248
[I 2024-04-19 17:39:08,022] Trial 62 finished with value: 0.21605214868055458 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 17:41:23,544] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 53 with value: 0.21558143837167032.
Fold 1 IBS: 0.2125800253180546
Fold 2 IBS: 0.220545116087081
Fold 3 IBS: 0.20312883355084663
Fold 4 IBS: 0.22358482732038532
Fold 5 IBS: 0.21775488310537955
[I 2024-04-19 17:43:25,425] Trial 64 finished with value: 0.21551873707634944 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 18:44:59,712] Trial 65 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.5880558715407225, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.03983864282382592, 'max_features': 0.1, 'min_impurity_decrease': 2.999919245030034e-07, 'validation_fraction': 0.8593144487131367, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 18:59:51,238] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9998769156045215, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.650983074619535, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 0.1, 'min_impurity_decrease': 4.636270239719423e-07, 'validation_fraction': 0.7909756969364712, 'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 19:01:31,852] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8945047973351204, 'learning_rate': 0.030289682188722505, 'dropout_rate': 0.6300169361769032, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.0031545307195375498, 'max_features': 0.1, 'min_impurity_decrease': 1.5144854860302472e-07, 'validation_fraction': 0.9159589204002132, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:03:11,945] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9645805834192783, 'learning_rate': 0.023218721503037675, 'dropout_rate': 0.5615571763998418, 'n_estimators': 423, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.05843575268694585, 'max_features': 0.1, 'min_impurity_decrease': 1.2087272488994307e-06, 'validation_fraction': 0.9686699003754374, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:04:27,878] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.99887024513786, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.7428831629900855, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.030031923886697245, 'max_features': 'sqrt', 'min_impurity_decrease': 4.97276861765846e-07, 'validation_fraction': 0.8281891917990171, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 20}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:06:48,482] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027338251310163056, 'dropout_rate': 0.7089882443645275, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.08410192190838273, 'max_features': 0.1, 'min_impurity_decrease': 1.0751704306840592e-07, 'validation_fraction': 0.7453979565756876, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21378585210531365
Fold 2 IBS: 0.22151188719103732
Fold 3 IBS: 0.2043538062983644
Fold 4 IBS: 0.22466944012296305
Fold 5 IBS: 0.21807495402516008
[I 2024-04-19 19:09:18,833] Trial 71 finished with value: 0.21647918794856774 and parameters: {'subsample': 0.9414985144334991, 'learning_rate': 0.003968115896613653, 'dropout_rate': 0.5823696005202688, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.26779541644842847, 'max_features': 'auto', 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9713376306080728, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 64 with value: 0.21551873707634944.
Fold 1 IBS: 0.21220418833650798
Fold 2 IBS: 0.22042207263837602
Fold 3 IBS: 0.20285738449953122
Fold 4 IBS: 0.22332862827581526
Fold 5 IBS: 0.21723149356958285
[I 2024-04-19 19:12:19,042] Trial 72 finished with value: 0.21520875346396268 and parameters: {'subsample': 0.9498773753497436, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.25030187864168324, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.05064701957266815, 'max_features': 'auto', 'min_impurity_decrease': 2.3215203093247524e-06, 'validation_fraction': 0.936460972995549, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:12:34,843] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.920760761939223, 'learning_rate': 0.016102732082041646, 'dropout_rate': 0.6213012350523704, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.06465519957873159, 'max_features': 'auto', 'min_impurity_decrease': 5.468956659515511e-06, 'validation_fraction': 0.8662757832984233, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 19:15:55,796] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8230892029035446, 'learning_rate': 0.05987785583368638, 'dropout_rate': 0.20192375679043018, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.05188888002939977, 'max_features': None, 'min_impurity_decrease': 2.7222990554600103e-06, 'validation_fraction': 0.9331744008199012, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:16:44,836] Trial 75 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.87711326947114, 'learning_rate': 0.011349868098961852, 'dropout_rate': 0.7982182448702262, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 1.194698393798027, 'min_weight_fraction_leaf': 0.015743638868849746, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.9957073825551704, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 18}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:20:45,697] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9717998493529779, 'learning_rate': 0.020285254602452306, 'dropout_rate': 0.16945167389703747, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.0962621052112238, 'max_features': 'auto', 'min_impurity_decrease': 6.135353898848802e-07, 'validation_fraction': 0.8995225231338432, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 19:23:57,458] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6527746876723795, 'learning_rate': 0.009617814274368723, 'dropout_rate': 0.23464360454432553, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.5872217111247551, 'min_weight_fraction_leaf': 0.12767889602965304, 'max_features': 1, 'min_impurity_decrease': 1.4509408420175117e-05, 'validation_fraction': 0.9291496186906082, 'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 5}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-19 19:27:03,494] Trial 78 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.014013205775387057, 'dropout_rate': 0.13859848186436124, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.29419286253457877, 'min_weight_fraction_leaf': 0.052943967521367895, 'max_features': 0.1, 'min_impurity_decrease': 2.1434329740740177e-07, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:30:20,341] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9126207967170201, 'learning_rate': 0.0011753775837182534, 'dropout_rate': 0.29054025396825206, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8367973848765441, 'min_weight_fraction_leaf': 0.0018798299029973327, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.5338124134897904, 'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 19:31:39,949] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9710627523470323, 'learning_rate': 0.017685317600779724, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'log2', 'min_impurity_decrease': 1.0915642738877587e-06, 'validation_fraction': 0.8033655207154786, 'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21321043899438455
Fold 2 IBS: 0.2213401465932955
Fold 3 IBS: 0.20383192383279608
Fold 4 IBS: 0.22447154865937347
Fold 5 IBS: 0.21791922647063378
[I 2024-04-19 19:35:08,776] Trial 81 finished with value: 0.21615465691009667 and parameters: {'subsample': 0.9579178853393634, 'learning_rate': 0.006802404808842085, 'dropout_rate': 0.2523609841831704, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2563778007434269, 'max_features': 'auto', 'min_impurity_decrease': 1.475357902881004e-06, 'validation_fraction': 0.9513185761421921, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:38:26,329] Trial 82 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9453987712590168, 'learning_rate': 0.009537962827339893, 'dropout_rate': 0.1892865857241059, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.22662729175199345, 'max_features': 'auto', 'min_impurity_decrease': 2.05835958734699e-06, 'validation_fraction': 0.9745676430715979, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-19 19:40:24,680] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8909479551758591, 'learning_rate': 0.00450277377622531, 'dropout_rate': 0.6877929836754342, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.2701739605759479, 'max_features': 'auto', 'min_impurity_decrease': 3.5210043901131074e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.2139613284871823
Fold 2 IBS: 0.22156741247576545
Fold 3 IBS: 0.20450210614863562
Fold 4 IBS: 0.22472322474865014
Fold 5 IBS: 0.2181147167734584
[I 2024-04-19 19:44:17,415] Trial 84 finished with value: 0.21657375772673843 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.013253369992371197, 'dropout_rate': 0.24027487512818702, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.17631296272227048, 'max_features': 'auto', 'min_impurity_decrease': 1.4523274478524455e-07, 'validation_fraction': 0.913099981360701, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.2129673111888308
Fold 2 IBS: 0.2209790270026334
Fold 3 IBS: 0.20363805672766896
Fold 4 IBS: 0.2240878382781251
Fold 5 IBS: 0.21772834196710608
[I 2024-04-19 19:47:15,060] Trial 85 finished with value: 0.21588011503287285 and parameters: {'subsample': 0.770335172495693, 'learning_rate': 0.007723843561328281, 'dropout_rate': 0.3134955782796943, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.20250430497823585, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.8427627969606453, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 19:49:18,515] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6258266362144153, 'learning_rate': 0.03629425342023726, 'dropout_rate': 0.2984129682976939, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 0.9973471047062721, 'min_weight_fraction_leaf': 0.21352096515716423, 'max_features': 'sqrt', 'min_impurity_decrease': 7.922266013019743e-07, 'validation_fraction': 0.6826441761790084, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:51:57,028] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5620710546480945, 'learning_rate': 0.008505210809908712, 'dropout_rate': 0.3819983711228876, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.4306337003019733, 'min_weight_fraction_leaf': 0.2041372504844265, 'max_features': 'auto', 'min_impurity_decrease': 0.0003255828305135596, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 19:54:35,143] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.011111179381597284, 'dropout_rate': 0.3196243460718578, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 1.3457840140168202, 'min_weight_fraction_leaf': 0.026102976372990007, 'max_features': 0.1, 'min_impurity_decrease': 4.1842504540759167e-07, 'validation_fraction': 0.8468844412711507, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 8}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 19:56:47,409] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6969649633096852, 'learning_rate': 0.015358704013366007, 'dropout_rate': 0.5090990897137027, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 1.5765552790097783, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 2.1650730397688694e-07, 'validation_fraction': 0.8757107738634061, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 20:00:16,624] Trial 90 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7306151097727858, 'learning_rate': 0.0030759059571325367, 'dropout_rate': 0.20732155805323632, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.08382061902052879, 'max_features': 'auto', 'min_impurity_decrease': 6.014966438611826e-07, 'validation_fraction': 0.8287281797305409, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.213282442813215
Fold 2 IBS: 0.22113214368705078
Fold 3 IBS: 0.20394981416693883
Fold 4 IBS: 0.22428599721965942
Fold 5 IBS: 0.21790194149489853
[I 2024-04-19 20:04:06,811] Trial 91 finished with value: 0.21611046787635252 and parameters: {'subsample': 0.5185673050184334, 'learning_rate': 0.005831718220267968, 'dropout_rate': 0.2673714840258141, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.24422274988904982, 'max_features': 'auto', 'min_impurity_decrease': 9.079922261639684e-07, 'validation_fraction': 0.9411775770096612, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 20:05:21,848] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.978365732192231, 'learning_rate': 0.0076954842205835, 'dropout_rate': 0.23183821297416474, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.49211647913049955, 'min_weight_fraction_leaf': 0.23688053465240513, 'max_features': 'auto', 'min_impurity_decrease': 4.418613834721915e-06, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 20:09:10,994] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.32126879099869027, 'learning_rate': 0.011783539264009723, 'dropout_rate': 0.2795436425709962, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.20362952808416507, 'min_weight_fraction_leaf': 0.2585448454100403, 'max_features': 'auto', 'min_impurity_decrease': 2.0333609492231826e-06, 'validation_fraction': 0.9108508896652943, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 20:12:47,365] Trial 94 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9172531776495569, 'learning_rate': 0.01908907573521863, 'dropout_rate': 0.25483149782519043, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.6843293477116347, 'min_weight_fraction_leaf': 0.2228851842323061, 'max_features': None, 'min_impurity_decrease': 3.256681709458039e-06, 'validation_fraction': 0.9452356876786695, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 20:16:11,304] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8687843698527852, 'learning_rate': 0.0056488981484495914, 'dropout_rate': 0.33894348143511804, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.9601205383555245, 'min_weight_fraction_leaf': 0.2819750333077766, 'max_features': 'auto', 'min_impurity_decrease': 7.045012035510386e-06, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 17}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.2136208609230697
Fold 2 IBS: 0.22134365318813834
Fold 3 IBS: 0.2042334222298263
Fold 4 IBS: 0.22441515929806466
Fold 5 IBS: 0.21802029480715251
[I 2024-04-19 20:19:35,817] Trial 96 finished with value: 0.21632667808925032 and parameters: {'subsample': 0.950254432591521, 'learning_rate': 0.0022102389630717766, 'dropout_rate': 0.1723932907588553, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.04286122246886014, 'max_features': 0.1, 'min_impurity_decrease': 1.4068682575292907e-06, 'validation_fraction': 0.7629864192147846, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 20:22:01,997] Trial 97 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9794281118885965, 'learning_rate': 0.07256682880833759, 'dropout_rate': 0.31363079093592194, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.43382189055208925, 'min_weight_fraction_leaf': 0.23620687573013183, 'max_features': 'auto', 'min_impurity_decrease': 0.001290583661990368, 'validation_fraction': 0.8431515725718495, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 20:25:57,698] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034099191841783, 'learning_rate': 0.022872500438115773, 'dropout_rate': 0.11590233860021854, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.23384794026040234, 'min_weight_fraction_leaf': 0.2938783217761457, 'max_features': 1, 'min_impurity_decrease': 2.598305776222351e-07, 'validation_fraction': 0.8923308676191493, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 72 with value: 0.21520875346396268.
Fold 1 IBS: 0.21161311616211623
Fold 2 IBS: 0.2200506929100543

Fold 3 IBS: 0.2023614521860876
Fold 4 IBS: 0.2231898890507258
Fold 5 IBS: 0.2170482819994517
[I 2024-04-19 20:27:39,066] Trial 99 finished with value: 0.2148526864616871 and parameters: {'subsample': 0.8333920238412017, 'learning_rate': 0.02538174390008161, 'dropout_rate': 0.4577965489047534, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 0.004367047248614303, 'min_weight_fraction_leaf': 0.18072249935794454, 'max_features': 'auto', 'min_impurity_decrease': 4.472271308488144e-07, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 99 with value: 0.2148526864616871.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.2148526864616871], datetime_start=datetime.datetime(2024, 4, 19, 20, 25, 57, 706241), datetime_complete=datetime.datetime(2024, 4, 19, 20, 27, 39, 65185), params={'subsample': 0.8333920238412017, 'learning_rate': 0.02538174390008161, 'dropout_rate': 0.4577965489047534, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 0.004367047248614303, 'min_weight_fraction_leaf': 0.18072249935794454, 'max_features': 'auto', 'min_impurity_decrease': 4.472271308488144e-07, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for IBS:
 0.2148526864616871

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.215

#### Test

In [70]:
  # y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.030433464476024484,
                                 criterion='squared_error',
                                 dropout_rate=0.6934300990357392,
                                 learning_rate=0.05396213117321635, max_depth=7,
                                 max_features=1, max_leaf_nodes=10,
                                 min_impurity_decrease=3.7676942671090066e-07,
                                 min_samples_leaf=11, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38729753243593296,
                                 n_estimators=424, random_state=123,
                                 subsample=0.38604321258984187,
                                 validation_fraction=0.9213195792266449)

C-index score: 0.63

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004367047248614303,
                                 criterion='squared_error',
                                 dropout_rate=0.4577965489047534,
                                 learning_rate=0.02538174390008161, max_depth=5,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=4.472271308488144e-07,
                                 min_samples_leaf=14, min_samples_split=3,
                                 min_weight_fraction_leaf=0.18072249935794454,
                                 n_estimators=399, random_state=123,
                                 subsample=0.8333920238412017,
                                 validation_fraction=0.9580200141092102)

IBS: 0.22

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 20:28:14,176] A new study created in memory with name: no-name-015d58cd-203a-4156-9e43-726d6691d6eb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:28:16,362] Trial 0 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.7136894859079793.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:28:36,752] Trial 1 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.7136894859079793.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 20:28:40,618] Trial 2 finished with value: 0.7146284530441296 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7146284530441296.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:28:45,747] Trial 3 finished with value: 0.7118115516356788 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.7146284530441296.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:28:53,783] Trial 4 finished with value: 0.7109186944928216 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 2 with value: 0.7146284530441296.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:29:03,356] Trial 5 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 2 with value: 0.7146284530441296.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:29:07,468] Trial 6 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 2 with value: 0.7146284530441296.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:29:08,264] Trial 7 finished with value: 0.7127966287651222 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 2 with value: 0.7146284530441296.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:29:13,599] Trial 8 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 2 with value: 0.7146284530441296.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 20:29:29,443] Trial 9 finished with value: 0.7155674201802797 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 9 with value: 0.7155674201802797.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:29:45,013] Trial 10 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.9974588415748801, 'n_estimators': 496, 'learning_rate': 0.0017980531969980576}. Best is trial 9 with value: 0.7155674201802797.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:29:56,849] Trial 11 finished with value: 0.7155309939580624 and parameters: {'subsample': 0.17483690134082513, 'dropout_rate': 0.7091521021576341, 'n_estimators': 356, 'learning_rate': 0.0959256231821037}. Best is trial 9 with value: 0.7155674201802797.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:30:09,378] Trial 12 finished with value: 0.7208431147139158 and parameters: {'subsample': 0.11906980919548266, 'dropout_rate': 0.7520052788206826, 'n_estimators': 382, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.7208431147139158.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:30:22,689] Trial 13 finished with value: 0.7216408865771629 and parameters: {'subsample': 0.1148582532234806, 'dropout_rate': 0.8143837692949045, 'n_estimators': 405, 'learning_rate': 0.09856704475293049}. Best is trial 13 with value: 0.7216408865771629.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:30:34,267] Trial 14 finished with value: 0.719909284845561 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7107774760011644, 'n_estimators': 368, 'learning_rate': 0.09980516828660305}. Best is trial 13 with value: 0.7216408865771629.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:30:41,826] Trial 15 finished with value: 0.7127966287651222 and parameters: {'subsample': 0.27442921636853534, 'dropout_rate': 0.8012314176810971, 'n_estimators': 287, 'learning_rate': 0.08616677729964022}. Best is trial 13 with value: 0.7216408865771629.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:30:56,705] Trial 16 finished with value: 0.7207577132053813 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.6268648704514393, 'n_estimators': 410, 'learning_rate': 0.08419726075804436}. Best is trial 13 with value: 0.7216408865771629.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:31:09,623] Trial 17 finished with value: 0.7137770209219849 and parameters: {'subsample': 0.35492106308132126, 'dropout_rate': 0.8384493320704152, 'n_estimators': 418, 'learning_rate': 0.08712060902857512}. Best is trial 13 with value: 0.7216408865771629.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:31:18,072] Trial 18 finished with value: 0.7108725844995286 and parameters: {'subsample': 0.21704421580096545, 'dropout_rate': 0.9500219447069638, 'n_estimators': 320, 'learning_rate': 0.09229610999398304}. Best is trial 13 with value: 0.7216408865771629.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:31:32,814] Trial 19 finished with value: 0.7118990866496844 and parameters: {'subsample': 0.37351945568220557, 'dropout_rate': 0.7683864204868823, 'n_estimators': 431, 'learning_rate': 0.08253305039935499}. Best is trial 13 with value: 0.7216408865771629.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:31:43,779] Trial 20 finished with value: 0.7164238511009196 and parameters: {'subsample': 0.179916923106687, 'dropout_rate': 0.5923165972699604, 'n_estimators': 337, 'learning_rate': 0.03973446561107324}. Best is trial 13 with value: 0.7216408865771629.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:31:58,885] Trial 21 finished with value: 0.7217284215911685 and parameters: {'subsample': 0.11014863416226671, 'dropout_rate': 0.6080226687634136, 'n_estimators': 410, 'learning_rate': 0.08088713232161321}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:32:14,902] Trial 22 finished with value: 0.7207577132053813 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.7357425097532323, 'n_estimators': 436, 'learning_rate': 0.09944054052531529}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:32:29,184] Trial 23 finished with value: 0.7109186944928216 and parameters: {'subsample': 0.303934983232125, 'dropout_rate': 0.5932531530509244, 'n_estimators': 389, 'learning_rate': 0.08013909093253938}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 20:32:37,647] Trial 24 finished with value: 0.7164746460667931 and parameters: {'subsample': 0.20547691465781653, 'dropout_rate': 0.8168861354051056, 'n_estimators': 303, 'learning_rate': 0.0908939362316281}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:32:55,588] Trial 25 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.9684217810899436, 'dropout_rate': 0.528565711666221, 'n_estimators': 457, 'learning_rate': 0.06267837256822405}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:33:03,780] Trial 26 finished with value: 0.7146698780648421 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.6560828093583356, 'n_estimators': 245, 'learning_rate': 0.07733372178258963}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:33:16,136] Trial 27 finished with value: 0.7153702926737073 and parameters: {'subsample': 0.16351183385205548, 'dropout_rate': 0.9199449431335885, 'n_estimators': 389, 'learning_rate': 0.09163283687145944}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:33:25,981] Trial 28 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.6076053914036648, 'dropout_rate': 0.7820948576216806, 'n_estimators': 328, 'learning_rate': 0.09401269450569924}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:33:26,766] Trial 29 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.3347169239810594, 'n_estimators': 28, 'learning_rate': 0.0666011974000343}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:33:28,704] Trial 30 finished with value: 0.7108725844995286 and parameters: {'subsample': 0.24274641910586908, 'dropout_rate': 0.6771740855279038, 'n_estimators': 93, 'learning_rate': 0.016814619253793885}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:33:44,064] Trial 31 finished with value: 0.7217284215911685 and parameters: {'subsample': 0.10830824814364959, 'dropout_rate': 0.6093310925785583, 'n_estimators': 400, 'learning_rate': 0.0831939904475785}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:34:02,918] Trial 32 finished with value: 0.718221068837266 and parameters: {'subsample': 0.15656626314847416, 'dropout_rate': 0.5982874610928377, 'n_estimators': 456, 'learning_rate': 0.08742979230529027}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:34:17,689] Trial 33 finished with value: 0.7128380537858348 and parameters: {'subsample': 0.2988690436767305, 'dropout_rate': 0.48095898939081394, 'n_estimators': 394, 'learning_rate': 0.07159889880779748}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 20:34:32,813] Trial 34 finished with value: 0.7180993795758145 and parameters: {'subsample': 0.12482891186239875, 'dropout_rate': 0.7499303450773485, 'n_estimators': 437, 'learning_rate': 0.07797237347543617}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:34:53,381] Trial 35 finished with value: 0.715535678930643 and parameters: {'subsample': 0.22146898936999776, 'dropout_rate': 0.43975685710717877, 'n_estimators': 474, 'learning_rate': 0.09933923968955222}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:35:04,596] Trial 36 finished with value: 0.7191600359734163 and parameters: {'subsample': 0.1494038838640815, 'dropout_rate': 0.8609957892683956, 'n_estimators': 373, 'learning_rate': 0.05895241767831559}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:35:16,254] Trial 37 finished with value: 0.7127966287651222 and parameters: {'subsample': 0.3186887150652707, 'dropout_rate': 0.4840655483537707, 'n_estimators': 347, 'learning_rate': 0.06820661555312825}. Best is trial 21 with value: 0.7217284215911685.

Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 20:35:24,601] Trial 38 finished with value: 0.7144727505582698 and parameters: {'subsample': 0.2426785762118624, 'dropout_rate': 0.13272164755980653, 'n_estimators': 261, 'learning_rate': 0.07341163028968031}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 20:35:27,994] Trial 39 finished with value: 0.7116875903994557 and parameters: {'subsample': 0.19457273105148687, 'dropout_rate': 0.545457595342022, 'n_estimators': 145, 'learning_rate': 0.08805878681634485}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:35:37,409] Trial 40 finished with value: 0.7118990866496844 and parameters: {'subsample': 0.43044010998923515, 'dropout_rate': 0.20013020077502125, 'n_estimators': 293, 'learning_rate': 0.08016160901752395}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:35:52,292] Trial 41 finished with value: 0.7207577132053813 and parameters: {'subsample': 0.10479725148020806, 'dropout_rate': 0.6393237799103046, 'n_estimators': 414, 'learning_rate': 0.08423789141734}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:36:06,751] Trial 42 finished with value: 0.7216505703482385 and parameters: {'subsample': 0.10336654058602983, 'dropout_rate': 0.6049528189428636, 'n_estimators': 405, 'learning_rate': 0.09510808697719654}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:36:26,580] Trial 43 finished with value: 0.7209186939820742 and parameters: {'subsample': 0.15786333505550354, 'dropout_rate': 0.4059475361418808, 'n_estimators': 457, 'learning_rate': 0.09502113764975752}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:36:48,136] Trial 44 finished with value: 0.7181749588439729 and parameters: {'subsample': 0.16453101988422877, 'dropout_rate': 0.32166583157428047, 'n_estimators': 465, 'learning_rate': 0.09320367556955882}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:37:09,779] Trial 45 finished with value: 0.7145552867737802 and parameters: {'subsample': 0.2570318974432916, 'dropout_rate': 0.401619063287554, 'n_estimators': 479, 'learning_rate': 0.07619273839326327}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 20:37:33,460] Trial 46 finished with value: 0.7171384934304035 and parameters: {'subsample': 0.1483830276906788, 'dropout_rate': 0.25312738150980274, 'n_estimators': 493, 'learning_rate': 0.0888973534782918}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:37:48,728] Trial 47 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.6945617668617625, 'dropout_rate': 0.5103146934099234, 'n_estimators': 407, 'learning_rate': 0.09534166083585982}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:38:07,482] Trial 48 finished with value: 0.7146334518426246 and parameters: {'subsample': 0.1925730848744018, 'dropout_rate': 0.4263071220305721, 'n_estimators': 439, 'learning_rate': 0.08231594181894807}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:38:20,012] Trial 49 finished with value: 0.7181259835576559 and parameters: {'subsample': 0.1459758352137601, 'dropout_rate': 0.5697422917120915, 'n_estimators': 361, 'learning_rate': 0.04472289264854639}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:38:38,823] Trial 50 finished with value: 0.7118990866496844 and parameters: {'subsample': 0.28025107294767726, 'dropout_rate': 0.37111166980667065, 'n_estimators': 449, 'learning_rate': 0.09625011741401299}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:38:51,202] Trial 51 finished with value: 0.7208431147139158 and parameters: {'subsample': 0.12415679892427402, 'dropout_rate': 0.6983773969550371, 'n_estimators': 374, 'learning_rate': 0.09736879914334319}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:39:05,327] Trial 52 finished with value: 0.7145552867737802 and parameters: {'subsample': 0.21849575523554307, 'dropout_rate': 0.7273704791657846, 'n_estimators': 419, 'learning_rate': 0.09092162809614963}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:39:18,534] Trial 53 finished with value: 0.7198822285685048 and parameters: {'subsample': 0.10826411265965066, 'dropout_rate': 0.6304596182284844, 'n_estimators': 382, 'learning_rate': 0.09550171540184518}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:39:32,114] Trial 54 finished with value: 0.717377186980726 and parameters: {'subsample': 0.18587657381606318, 'dropout_rate': 0.6752903379042274, 'n_estimators': 402, 'learning_rate': 0.0855246092820617}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 20:39:41,714] Trial 55 finished with value: 0.7146284530441296 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.8131096094448964, 'n_estimators': 348, 'learning_rate': 0.0997126245400615}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:39:50,201] Trial 56 finished with value: 0.7191553510008356 and parameters: {'subsample': 0.1369238375588182, 'dropout_rate': 0.8866473080276548, 'n_estimators': 311, 'learning_rate': 0.09090128675280526}. Best is trial 21 with value: 0.7217284215911685.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:40:06,030] Trial 57 finished with value: 0.7118990866496844 and parameters: {'subsample': 0.3357063179210369, 'dropout_rate': 0.5726642496592249, 'n_estimators': 426, 'learning_rate': 0.08167580021323008}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:40:21,534] Trial 58 finished with value: 0.711696960344617 and parameters: {'subsample': 0.2226212859529874, 'dropout_rate': 0.9853580884988968, 'n_estimators': 498, 'learning_rate': 0.08860113299160241}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 20:40:39,289] Trial 59 finished with value: 0.7216966803415314 and parameters: {'subsample': 0.10187028158812442, 'dropout_rate': 0.5065802886056728, 'n_estimators': 449, 'learning_rate': 0.09384928359588694}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:40:58,002] Trial 60 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.8149554136487304, 'dropout_rate': 0.5147065240775213, 'n_estimators': 476, 'learning_rate': 0.030388384293041026}. Best is trial 21 with value: 0.7217284215911685.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:41:14,466] Trial 61 finished with value: 0.723574614613832 and parameters: {'subsample': 0.10718290653750012, 'dropout_rate': 0.6140864163365967, 'n_estimators': 441, 'learning_rate': 0.09358014693300638}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:41:31,066] Trial 62 finished with value: 0.7165113861149252 and parameters: {'subsample': 0.17780927992540438, 'dropout_rate': 0.6197615249304782, 'n_estimators': 446, 'learning_rate': 0.09344687189972214}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:41:46,644] Trial 63 finished with value: 0.7145336815904338 and parameters: {'subsample': 0.1352012330950751, 'dropout_rate': 0.46428357030299394, 'n_estimators': 404, 'learning_rate': 0.08588761122128942}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:42:02,651] Trial 64 finished with value: 0.7207577132053813 and parameters: {'subsample': 0.10194217199609162, 'dropout_rate': 0.5654734211342488, 'n_estimators': 424, 'learning_rate': 0.09688704424136352}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:42:20,529] Trial 65 finished with value: 0.718221068837266 and parameters: {'subsample': 0.15961499507941568, 'dropout_rate': 0.6029393806176394, 'n_estimators': 463, 'learning_rate': 0.09059016521801061}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:42:38,986] Trial 66 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.6194399591985713, 'dropout_rate': 0.40471898924420924, 'n_estimators': 448, 'learning_rate': 0.010808482740950733}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:42:58,800] Trial 67 finished with value: 0.7199260665870264 and parameters: {'subsample': 0.13665485985804104, 'dropout_rate': 0.6531052755616016, 'n_estimators': 478, 'learning_rate': 0.07851212652645694}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:43:05,333] Trial 68 finished with value: 0.7155724189787749 and parameters: {'subsample': 0.1997422148077056, 'dropout_rate': 0.5052208393647382, 'n_estimators': 228, 'learning_rate': 0.07086606898531744}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:43:20,221] Trial 69 finished with value: 0.7117701266149663 and parameters: {'subsample': 0.2492218535994984, 'dropout_rate': 0.5431091622515001, 'n_estimators': 393, 'learning_rate': 0.08403050744828938}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:43:39,158] Trial 70 finished with value: 0.7191553510008356 and parameters: {'subsample': 0.17290251928691425, 'dropout_rate': 0.3135027298737797, 'n_estimators': 435, 'learning_rate': 0.09977926712527085}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:43:51,802] Trial 71 finished with value: 0.7208431147139158 and parameters: {'subsample': 0.11768208180151028, 'dropout_rate': 0.7666206890814887, 'n_estimators': 382, 'learning_rate': 0.09358752719669214}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:44:06,558] Trial 72 finished with value: 0.7207577132053813 and parameters: {'subsample': 0.1027600737280707, 'dropout_rate': 0.7151226714181969, 'n_estimators': 422, 'learning_rate': 0.08935910282941038}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:44:17,061] Trial 73 finished with value: 0.7199260665870264 and parameters: {'subsample': 0.134283868167862, 'dropout_rate': 0.6982053394597243, 'n_estimators': 339, 'learning_rate': 0.09702527429681357}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:44:27,940] Trial 74 finished with value: 0.7173552679714652 and parameters: {'subsample': 0.16815051066305886, 'dropout_rate': 0.7886996638363634, 'n_estimators': 361, 'learning_rate': 0.09348661281807298}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:44:39,937] Trial 75 finished with value: 0.7126359274807672 and parameters: {'subsample': 0.22000689829823805, 'dropout_rate': 0.8488975178729159, 'n_estimators': 397, 'learning_rate': 0.08716898008422172}. Best is trial 61 with value: 0.723574614613832.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 20:44:58,239] Trial 76 finished with value: 0.7155674201802797 and parameters: {'subsample': 0.5080184978396685, 'dropout_rate': 0.4521422957052628, 'n_estimators': 462, 'learning_rate': 0.09741124556756729}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:45:13,853] Trial 77 finished with value: 0.7207577132053813 and parameters: {'subsample': 0.1001158475630001, 'dropout_rate': 0.6004515342870113, 'n_estimators': 415, 'learning_rate': 0.07600549156311016}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:45:33,244] Trial 78 finished with value: 0.7207699484435663 and parameters: {'subsample': 0.1326089168081283, 'dropout_rate': 0.6697199418134897, 'n_estimators': 484, 'learning_rate': 0.09115633252871437}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:45:34,915] Trial 79 finished with value: 0.7153559239300511 and parameters: {'subsample': 0.1866176118553311, 'dropout_rate': 0.7484412429712285, 'n_estimators': 79, 'learning_rate': 0.0942844479099778}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:45:39,685] Trial 80 finished with value: 0.7198114752959646 and parameters: {'subsample': 0.1561555778758734, 'dropout_rate': 0.526632530347687, 'n_estimators': 185, 'learning_rate': 0.08057943159462978}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:45:52,274] Trial 81 finished with value: 0.7207918674528273 and parameters: {'subsample': 0.12713036168160846, 'dropout_rate': 0.6423475987390944, 'n_estimators': 376, 'learning_rate': 0.09772712102770198}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 20:46:03,834] Trial 82 finished with value: 0.7208431147139158 and parameters: {'subsample': 0.12158924451295243, 'dropout_rate': 0.6904462682229132, 'n_estimators': 365, 'learning_rate': 0.09744022437516098}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:46:17,552] Trial 83 finished with value: 0.7191600359734163 and parameters: {'subsample': 0.1540487679514091, 'dropout_rate': 0.8325545721971954, 'n_estimators': 430, 'learning_rate': 0.09977389673583323}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 20:46:30,937] Trial 84 finished with value: 0.7174550382236559 and parameters: {'subsample': 0.20740481612010414, 'dropout_rate': 0.6172087370228597, 'n_estimators': 386, 'learning_rate': 0.09504663064538675}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:46:46,116] Trial 85 finished with value: 0.7190383467119648 and parameters: {'subsample': 0.1205877161525186, 'dropout_rate': 0.5766533272852146, 'n_estimators': 409, 'learning_rate': 0.09168730435379961}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:47:02,130] Trial 86 finished with value: 0.7117844953586225 and parameters: {'subsample': 0.2798300675289019, 'dropout_rate': 0.7329080289735795, 'n_estimators': 445, 'learning_rate': 0.06372583418560197}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:47:14,312] Trial 87 finished with value: 0.7164699610942126 and parameters: {'subsample': 0.17641717376062477, 'dropout_rate': 0.7009188621496587, 'n_estimators': 376, 'learning_rate': 0.08411502552212835}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:47:30,929] Trial 88 finished with value: 0.7182163838646854 and parameters: {'subsample': 0.14801669117720412, 'dropout_rate': 0.6535122302581835, 'n_estimators': 452, 'learning_rate': 0.0864188618461583}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7276995305164319
[I 2024-04-19 20:47:40,676] Trial 89 finished with value: 0.712750518771829 and parameters: {'subsample': 0.23777152449072686, 'dropout_rate': 0.7660999785846249, 'n_estimators': 331, 'learning_rate': 0.08845843261517053}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:47:56,070] Trial 90 finished with value: 0.7190383467119648 and parameters: {'subsample': 0.12044969967116251, 'dropout_rate': 0.5536436943789375, 'n_estimators': 404, 'learning_rate': 0.09246934967417846}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:48:07,652] Trial 91 finished with value: 0.7199041475777656 and parameters: {'subsample': 0.11943314674370761, 'dropout_rate': 0.7701547895088143, 'n_estimators': 355, 'learning_rate': 0.09425470160466023}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 20:48:19,707] Trial 92 finished with value: 0.7174331192143951 and parameters: {'subsample': 0.19758102598304425, 'dropout_rate': 0.7983593959740477, 'n_estimators': 383, 'learning_rate': 0.05324895734809211}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 20:48:33,014] Trial 93 finished with value: 0.7207116032120883 and parameters: {'subsample': 0.10129505949984906, 'dropout_rate': 0.7495894107072967, 'n_estimators': 395, 'learning_rate': 0.09598596537094817}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:48:47,419] Trial 94 finished with value: 0.7200990031095664 and parameters: {'subsample': 0.15574766834409748, 'dropout_rate': 0.8877860604644333, 'n_estimators': 433, 'learning_rate': 0.09260024010054478}. Best is trial 61 with value: 0.723574614613832.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 20:49:04,364] Trial 95 finished with value: 0.7171143024463712 and parameters: {'subsample': 0.12117720622279574, 'dropout_rate': 0.48763681320618524, 'n_estimators': 416, 'learning_rate': 0.08978297618669814}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 20:49:12,512] Trial 96 finished with value: 0.7182163838646854 and parameters: {'subsample': 0.14455904742343717, 'dropout_rate': 0.718658499050651, 'n_estimators': 278, 'learning_rate': 0.09721805486458271}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:49:31,598] Trial 97 finished with value: 0.718221068837266 and parameters: {'subsample': 0.16639237393164402, 'dropout_rate': 0.5855426041214473, 'n_estimators': 468, 'learning_rate': 0.09847939334452536}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 20:49:44,129] Trial 98 finished with value: 0.717377186980726 and parameters: {'subsample': 0.1816785214825618, 'dropout_rate': 0.6151283952965843, 'n_estimators': 369, 'learning_rate': 0.0829655765158483}. Best is trial 61 with value: 0.723574614613832.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663

[I 2024-04-19 20:49:58,199] A new study created in memory with name: no-name-7d317635-147a-47ec-a374-371cd28713aa

Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 20:49:58,184] Trial 99 finished with value: 0.7136894859079793 and parameters: {'subsample': 0.4257224849620003, 'dropout_rate': 0.8279367293864704, 'n_estimators': 439, 'learning_rate': 0.09443167269959896}. Best is trial 61 with value: 0.723574614613832.


* Best trial for C-index:
 FrozenTrial(number=61, state=TrialState.COMPLETE, values=[0.723574614613832], datetime_start=datetime.datetime(2024, 4, 19, 20, 40, 58, 12587), datetime_complete=datetime.datetime(2024, 4, 19, 20, 41, 14, 466090), params={'subsample': 0.10718290653750012, 'dropout_rate': 0.6140864163365967, 'n_estimators': 441, 'learning_rate': 0.09358014693300638}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=61, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10718290653750012, 'dropout_rate': 0.6140864163365967, 'n_estimators': 441, 'learning_rate': 0.09358014693300638}


* Best Score for C-index:
 0.723574614613832

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23942271613843466
Fold 2 IBS: 0.23317848666127475
Fold 3 IBS: 0.21043224126881901
Fold 4 IBS: 0.2627413120655669
Fold 5 IBS: 0.2088844422588817
[I 2024-04-19 20:50:00,688] Trial 0 finished with value: 0.23093183967859537 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.23093183967859537.
Fold 1 IBS: 0.3225408117277589
Fold 2 IBS: 0.32189237562862166
Fold 3 IBS: 0.3082550680451809
Fold 4 IBS: 0.3152651041057157
Fold 5 IBS: 0.3046807334754616
[I 2024-04-19 20:50:21,401] Trial 1 finished with value: 0.31452681859654774 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.23093183967859537.
Fold 1 IBS: 0.28955417815657714
Fold 2 IBS: 0.2992916550922806
Fold 3 IBS: 0.2625223949154919
Fold 4 IBS: 0.2793781357317349
Fold 5 IBS: 0.26926725982651517
[I 2024-04-19 20:50:25,537] Trial 2 finished with value: 0.2800027247445199 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.23093183967859537.
Fold 1 IBS: 0.29005383381536876
Fold 2 IBS: 0.3008487602509511
Fold 3 IBS: 0.2681542448213887
Fold 4 IBS: 0.27987404736350585
Fold 5 IBS: 0.2744505370585484
[I 2024-04-19 20:50:30,892] Trial 3 finished with value: 0.28267628466195255 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.23093183967859537.
Fold 1 IBS: 0.2888652072843919
Fold 2 IBS: 0.3026698382039291
Fold 3 IBS: 0.26804197475861397
Fold 4 IBS: 0.28115902820747907
Fold 5 IBS: 0.2765557224261771
[I 2024-04-19 20:50:39,380] Trial 4 finished with value: 0.2834583541761183 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.23093183967859537.
Fold 1 IBS: 0.31149085822449785
Fold 2 IBS: 0.3204039646090136
Fold 3 IBS: 0.304021431034549
Fold 4 IBS: 0.3032899768975731
Fold 5 IBS: 0.2968638928198015
[I 2024-04-19 20:50:49,827] Trial 5 finished with value: 0.30721402471708703 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.23093183967859537.
Fold 1 IBS: 0.21764403156351286
Fold 2 IBS: 0.20264709709911605
Fold 3 IBS: 0.19244206297697874
Fold 4 IBS: 0.24090901161401929
Fold 5 IBS: 0.19041091163397286
[I 2024-04-19 20:50:54,494] Trial 6 finished with value: 0.20881062297752 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20881062297752.
Fold 1 IBS: 0.19530604351420444
Fold 2 IBS: 0.18656815657666925
Fold 3 IBS: 0.1835517662181085
Fold 4 IBS: 0.21144100221037349
Fold 5 IBS: 0.1901713463532055
[I 2024-04-19 20:50:55,646] Trial 7 finished with value: 0.19340766297451223 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.24600350326224746
Fold 2 IBS: 0.24353765123764928
Fold 3 IBS: 0.21666906267640182
Fold 4 IBS: 0.2674224092128543
Fold 5 IBS: 0.21376767568569888
[I 2024-04-19 20:51:01,247] Trial 8 finished with value: 0.23748006041497036 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.3133923691665398
Fold 2 IBS: 0.3209967414979614
Fold 3 IBS: 0.30566205554616416
Fold 4 IBS: 0.30673461810199476
Fold 5 IBS: 0.29990526063699724
[I 2024-04-19 20:51:17,174] Trial 9 finished with value: 0.3093382089899315 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.2128886771329591
Fold 2 IBS: 0.22041746827332745
Fold 3 IBS: 0.20371507622252658
Fold 4 IBS: 0.2237771082655921
Fold 5 IBS: 0.21719902637866145
[I 2024-04-19 20:51:18,048] Trial 10 finished with value: 0.21559947125461335 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.21257406488322583
Fold 2 IBS: 0.22001717603804508
Fold 3 IBS: 0.20386485568847693
Fold 4 IBS: 0.2234486245538933
Fold 5 IBS: 0.2168716025171396
[I 2024-04-19 20:51:18,623] Trial 11 finished with value: 0.21535526473615613 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.278009916371811
Fold 2 IBS: 0.28363864912452263
Fold 3 IBS: 0.24548332427137776
Fold 4 IBS: 0.27812443833899253
Fold 5 IBS: 0.25004673900131563
[I 2024-04-19 20:51:20,831] Trial 12 finished with value: 0.2670606134216039 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.27097660686814823
Fold 2 IBS: 0.2771979490504694
Fold 3 IBS: 0.23979271550272055
Fold 4 IBS: 0.2772718910025073
Fold 5 IBS: 0.24789677015981626
[I 2024-04-19 20:51:29,930] Trial 13 finished with value: 0.26262718651673234 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.19390840649546687
Fold 2 IBS: 0.19333008828178766
Fold 3 IBS: 0.18670105535073672
Fold 4 IBS: 0.20811509030714898
Fold 5 IBS: 0.195183209307254
[I 2024-04-19 20:51:31,737] Trial 14 finished with value: 0.19544756994847884 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.2069619226355941
Fold 2 IBS: 0.21382317145787383
Fold 3 IBS: 0.19928608856512564
Fold 4 IBS: 0.21874929874692298
Fold 5 IBS: 0.21245820504914184
[I 2024-04-19 20:51:33,308] Trial 15 finished with value: 0.21025573729093167 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.1982831688800865
Fold 2 IBS: 0.20279664668541308
Fold 3 IBS: 0.1923604283351481
Fold 4 IBS: 0.21138450932830422
Fold 5 IBS: 0.20288324042130967
[I 2024-04-19 20:51:34,642] Trial 16 finished with value: 0.2015415987300523 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.2250651244278544
Fold 2 IBS: 0.2137758878636472
Fold 3 IBS: 0.1997480428160151
Fold 4 IBS: 0.2497930363895449
Fold 5 IBS: 0.1965709716221325
[I 2024-04-19 20:51:37,280] Trial 17 finished with value: 0.21699061262383884 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.22605194567498593
Fold 2 IBS: 0.2181673210498043
Fold 3 IBS: 0.20248824109764296
Fold 4 IBS: 0.255011097988929
Fold 5 IBS: 0.19585726839309797
[I 2024-04-19 20:51:47,094] Trial 18 finished with value: 0.21951517484089203 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19340766297451223.
Fold 1 IBS: 0.18700220875272577

Fold 2 IBS: 0.18403148263985214
Fold 3 IBS: 0.1794640168289826
Fold 4 IBS: 0.20530510535013138
Fold 5 IBS: 0.19099563016620663
[I 2024-04-19 20:51:48,167] Trial 19 finished with value: 0.1893596887475797 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19149264401294455
Fold 2 IBS: 0.18706319876174624
Fold 3 IBS: 0.18151616590927064
Fold 4 IBS: 0.20627633661512726
Fold 5 IBS: 0.19535824476576305
[I 2024-04-19 20:51:49,274] Trial 20 finished with value: 0.19234131801297033 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19131235337562966
Fold 2 IBS: 0.19128086039557748
Fold 3 IBS: 0.1841970439756356
Fold 4 IBS: 0.2060462029855898
Fold 5 IBS: 0.19662556381580787
[I 2024-04-19 20:51:50,277] Trial 21 finished with value: 0.19389240490964807 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.21198576675686934
Fold 2 IBS: 0.2192486563965627
Fold 3 IBS: 0.2032033974567237
Fold 4 IBS: 0.2222842490602751
Fold 5 IBS: 0.21629342497904955
[I 2024-04-19 20:51:50,862] Trial 22 finished with value: 0.21460309892989607 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.22494671535359992
Fold 2 IBS: 0.22065477400024597
Fold 3 IBS: 0.1970752189367511
Fold 4 IBS: 0.256692310985262
Fold 5 IBS: 0.19852749643139342
[I 2024-04-19 20:51:54,026] Trial 23 finished with value: 0.2195793031414505 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20872896456519532
Fold 2 IBS: 0.19363503789391787
Fold 3 IBS: 0.18768540468189915
Fold 4 IBS: 0.22993815392808942
Fold 5 IBS: 0.18728512230044847
[I 2024-04-19 20:51:55,215] Trial 24 finished with value: 0.20145453667391006 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.21129903551444676
Fold 2 IBS: 0.1916529349319393
Fold 3 IBS: 0.18297739002233432
Fold 4 IBS: 0.22850467464791718
Fold 5 IBS: 0.18729315177582606
[I 2024-04-19 20:51:56,864] Trial 25 finished with value: 0.2003454373784927 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.24236368759878218
Fold 2 IBS: 0.2726012112369128
Fold 3 IBS: 0.24188951946762544
Fold 4 IBS: 0.2780905711876254
Fold 5 IBS: 0.2644423392282727
[I 2024-04-19 20:51:59,913] Trial 26 finished with value: 0.2598774657438437 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2554189550037376
Fold 2 IBS: 0.25884419526681307
Fold 3 IBS: 0.22531297476839296
Fold 4 IBS: 0.2748286551467932
Fold 5 IBS: 0.2278653645295643
[I 2024-04-19 20:52:05,990] Trial 27 finished with value: 0.2484540289430602 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19535333205811867
Fold 2 IBS: 0.19761715462425813
Fold 3 IBS: 0.18871272597730077
Fold 4 IBS: 0.20902975091988596
Fold 5 IBS: 0.20306423621864558
[I 2024-04-19 20:52:07,122] Trial 28 finished with value: 0.19875543995964182 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2510866593991242
Fold 2 IBS: 0.2515971564775272
Fold 3 IBS: 0.22167260493411775
Fold 4 IBS: 0.2705170447873235
Fold 5 IBS: 0.21671704864354033
[I 2024-04-19 20:52:09,722] Trial 29 finished with value: 0.2423181028483266 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.21516795685038675
Fold 2 IBS: 0.20079363435509123
Fold 3 IBS: 0.1903573359498175
Fold 4 IBS: 0.2481447078758546
Fold 5 IBS: 0.19071569679128447
[I 2024-04-19 20:52:11,529] Trial 30 finished with value: 0.2090358663644869 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18791779404155043
Fold 2 IBS: 0.18609124113532682
Fold 3 IBS: 0.18096083642293181
Fold 4 IBS: 0.2069471146607423
Fold 5 IBS: 0.19241356466505027
[I 2024-04-19 20:52:12,447] Trial 31 finished with value: 0.19086611018512034 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19140354148142574
Fold 2 IBS: 0.19158408129522905
Fold 3 IBS: 0.18556268757417993
Fold 4 IBS: 0.20700867559257016
Fold 5 IBS: 0.1996601490185045
[I 2024-04-19 20:52:13,278] Trial 32 finished with value: 0.19504382699238187 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19794141856397104
Fold 2 IBS: 0.18307450275079984
Fold 3 IBS: 0.1765734602387373
Fold 4 IBS: 0.2295836791627767
Fold 5 IBS: 0.18793731124715599
[I 2024-04-19 20:52:14,723] Trial 33 finished with value: 0.19502207439268818 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20860586647722973
Fold 2 IBS: 0.2153575714035304
Fold 3 IBS: 0.20065703036500854
Fold 4 IBS: 0.22010576129566078
Fold 5 IBS: 0.21317970668244174
[I 2024-04-19 20:52:15,293] Trial 34 finished with value: 0.21158118724477423 and parameters: {'subsample': 0.31478192981222664, 'dropout_rate': 0.8275723231432607, 'n_estimators': 3, 'learning_rate': 0.07736389899612653}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2998628457791082
Fold 2 IBS: 0.3192605377316156
Fold 3 IBS: 0.30118550450500514
Fold 4 IBS: 0.30157204511160834
Fold 5 IBS: 0.2997303240709462
[I 2024-04-19 20:52:26,846] Trial 35 finished with value: 0.3043222514396567 and parameters: {'subsample': 0.16380438916747353, 'dropout_rate': 0.9999123570428878, 'n_estimators': 422, 'learning_rate': 0.05562786447029076}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.24450759778156403
Fold 2 IBS: 0.24524857774608627
Fold 3 IBS: 0.21705357281061252
Fold 4 IBS: 0.26978818858480136
Fold 5 IBS: 0.21169632641545102
[I 2024-04-19 20:52:30,079] Trial 36 finished with value: 0.23765885266770304 and parameters: {'subsample': 0.2831662236414486, 'dropout_rate': 0.7241481829027506, 'n_estimators': 143, 'learning_rate': 0.04884168927440709}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.24004183224892492
Fold 2 IBS: 0.23634576834564683
Fold 3 IBS: 0.2131739439883281
Fold 4 IBS: 0.2631044071522301
Fold 5 IBS: 0.20900153768070906
[I 2024-04-19 20:52:33,813] Trial 37 finished with value: 0.2323334978831678 and parameters: {'subsample': 0.5576285050776038, 'dropout_rate': 0.895091897129315, 'n_estimators': 170, 'learning_rate': 0.03638521957777931}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20779628745049195
Fold 2 IBS: 0.19531150653383356

Fold 3 IBS: 0.19014918624192317
Fold 4 IBS: 0.24978463432611944
Fold 5 IBS: 0.19584476340890472
[I 2024-04-19 20:52:35,959] Trial 38 finished with value: 0.20777727559225453 and parameters: {'subsample': 0.24276783442088262, 'dropout_rate': 0.13272164755980653, 'n_estimators': 87, 'learning_rate': 0.06952328337469094}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19338706777728606
Fold 2 IBS: 0.18922224442798738
Fold 3 IBS: 0.18465392240622586
Fold 4 IBS: 0.2095057018732719
Fold 5 IBS: 0.1917921429574166
[I 2024-04-19 20:52:36,838] Trial 39 finished with value: 0.19371221588843754 and parameters: {'subsample': 0.3645779440068705, 'dropout_rate': 0.9451944095204212, 'n_estimators': 32, 'learning_rate': 0.055414173921640594}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1938766062087041
Fold 2 IBS: 0.19294131275618495
Fold 3 IBS: 0.18743576949243462
Fold 4 IBS: 0.20765416654906
Fold 5 IBS: 0.1966197339957858
[I 2024-04-19 20:52:37,918] Trial 40 finished with value: 0.1957055178004339 and parameters: {'subsample': 0.4306300092933272, 'dropout_rate': 0.27073406810212547, 'n_estimators': 48, 'learning_rate': 0.028415559992356662}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19665300226358914
Fold 2 IBS: 0.18715554361555237
Fold 3 IBS: 0.18360216443866229
Fold 4 IBS: 0.21295543283177362
Fold 5 IBS: 0.18852682667202292
[I 2024-04-19 20:52:38,883] Trial 41 finished with value: 0.19377859396432007 and parameters: {'subsample': 0.5521411444134304, 'dropout_rate': 0.9446504650465772, 'n_estimators': 40, 'learning_rate': 0.0541725202595718}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19735243509934508
Fold 2 IBS: 0.2004547830025763
Fold 3 IBS: 0.19038406338541286
Fold 4 IBS: 0.21131590118519974
Fold 5 IBS: 0.20536245772351755
[I 2024-04-19 20:52:39,555] Trial 42 finished with value: 0.2009739280792103 and parameters: {'subsample': 0.15473768272058921, 'dropout_rate': 0.8907998143433291, 'n_estimators': 18, 'learning_rate': 0.04730970062429182}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.24384474331779663
Fold 2 IBS: 0.24076865435345532
Fold 3 IBS: 0.2132967797578001
Fold 4 IBS: 0.26879239303557
Fold 5 IBS: 0.21015017756199855
[I 2024-04-19 20:52:41,681] Trial 43 finished with value: 0.23537054960532414 and parameters: {'subsample': 0.3605410037994342, 'dropout_rate': 0.9464159812480104, 'n_estimators': 113, 'learning_rate': 0.05934370367503163}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2177051487174064
Fold 2 IBS: 0.19867862299592348
Fold 3 IBS: 0.1866113682291428
Fold 4 IBS: 0.23689418050875743
Fold 5 IBS: 0.18877522179360692
[I 2024-04-19 20:52:43,189] Trial 44 finished with value: 0.2057329084489674 and parameters: {'subsample': 0.21341615105758052, 'dropout_rate': 0.8073069210425599, 'n_estimators': 79, 'learning_rate': 0.05240738459435649}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19376061393138475
Fold 2 IBS: 0.1921572350949126
Fold 3 IBS: 0.18659085644069245
Fold 4 IBS: 0.2081147440001719
Fold 5 IBS: 0.19673933352144393
[I 2024-04-19 20:52:43,881] Trial 45 finished with value: 0.19547255659772111 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.868651349104605, 'n_estimators': 21, 'learning_rate': 0.06684355856532022}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.26006374725192166
Fold 2 IBS: 0.2631355651442905
Fold 3 IBS: 0.22958936799426735
Fold 4 IBS: 0.27408003590463853
Fold 5 IBS: 0.23298546850960056
[I 2024-04-19 20:52:48,007] Trial 46 finished with value: 0.2519708369609437 and parameters: {'subsample': 0.5965242161704707, 'dropout_rate': 0.7690304521858167, 'n_estimators': 203, 'learning_rate': 0.03970265207097222}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.22120740167489522
Fold 2 IBS: 0.20697885108311181
Fold 3 IBS: 0.19558874393983472
Fold 4 IBS: 0.24545261546379896
Fold 5 IBS: 0.1940472556683423
[I 2024-04-19 20:52:49,059] Trial 47 finished with value: 0.2126549735659966 and parameters: {'subsample': 0.6926155531919815, 'dropout_rate': 0.7318011215840461, 'n_estimators': 57, 'learning_rate': 0.08063451221472408}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2072052064162487
Fold 2 IBS: 0.1904428570748318
Fold 3 IBS: 0.18465334506663922
Fold 4 IBS: 0.22653246228712437
Fold 5 IBS: 0.18676954429494685
[I 2024-04-19 20:52:51,076] Trial 48 finished with value: 0.1991206830279582 and parameters: {'subsample': 0.3096099833563881, 'dropout_rate': 0.5758773874350814, 'n_estimators': 106, 'learning_rate': 0.030462335954124765}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2822102511488822
Fold 2 IBS: 0.2910627769583346
Fold 3 IBS: 0.2537367899112689
Fold 4 IBS: 0.2778038638987042
Fold 5 IBS: 0.27012711343272683
[I 2024-04-19 20:52:58,169] Trial 49 finished with value: 0.2749881590699833 and parameters: {'subsample': 0.15102302027105324, 'dropout_rate': 0.6978527778541695, 'n_estimators': 272, 'learning_rate': 0.05014804814946632}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2540204512906103
Fold 2 IBS: 0.2532928156170901
Fold 3 IBS: 0.22262948712643613
Fold 4 IBS: 0.27205913571153223
Fold 5 IBS: 0.2247631185643851
[I 2024-04-19 20:53:01,834] Trial 50 finished with value: 0.24535300166201077 and parameters: {'subsample': 0.48193062030532147, 'dropout_rate': 0.45943208590211054, 'n_estimators': 168, 'learning_rate': 0.04496140913662158}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.196586236014137
Fold 2 IBS: 0.18721300772221183
Fold 3 IBS: 0.1835994725496962
Fold 4 IBS: 0.2131873822161407
Fold 5 IBS: 0.1882715575493962
[I 2024-04-19 20:53:02,676] Trial 51 finished with value: 0.19377153121031637 and parameters: {'subsample': 0.5355561921107888, 'dropout_rate': 0.9521587905907255, 'n_estimators': 39, 'learning_rate': 0.05534564210715891}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.196730916096748
Fold 2 IBS: 0.19956782016775293
Fold 3 IBS: 0.18992498920978962
Fold 4 IBS: 0.20972896847219183
Fold 5 IBS: 0.20032100581128123
[I 2024-04-19 20:53:03,302] Trial 52 finished with value: 0.1992547399515527 and parameters: {'subsample': 0.7508121314262817, 'dropout_rate': 0.9600633898082516, 'n_estimators': 15, 'learning_rate': 0.06371039346206121}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1963260842750414
Fold 2 IBS: 0.1869274228771799
Fold 3 IBS: 0.18350068020983193
Fold 4 IBS: 0.2120231163078518
Fold 5 IBS: 0.18760513535099632
[I 2024-04-19 20:53:04,174] Trial 53 finished with value: 0.19327648780418027 and parameters: {'subsample': 0.6081578962933406, 'dropout_rate': 0.9159732834221895, 'n_estimators': 38, 'learning_rate': 0.0577930546978069}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2226548466472657
Fold 2 IBS: 0.20867108268451506
Fold 3 IBS: 0.19573169615154012
Fold 4 IBS: 0.24646195242022964
Fold 5 IBS: 0.1954186823089113
[I 2024-04-19 20:53:05,366] Trial 54 finished with value: 0.21378765204249234 and parameters: {'subsample': 0.6272222181244915, 'dropout_rate': 0.8823845840705826, 'n_estimators': 66, 'learning_rate': 0.07051077241549432}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.213307256620462
Fold 2 IBS: 0.22025589106620894
Fold 3 IBS: 0.20404777435045954
Fold 4 IBS: 0.22414504875791483
Fold 5 IBS: 0.2172256444286708
[I 2024-04-19 20:53:05,886] Trial 55 finished with value: 0.21579632304474322 and parameters: {'subsample': 0.12757592380452934, 'dropout_rate': 0.914455333208875, 'n_estimators': 1, 'learning_rate': 0.03499086450498484}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.23419031363347573
Fold 2 IBS: 0.22643495762697596
Fold 3 IBS: 0.20740028149137082
Fold 4 IBS: 0.25895791146551045
Fold 5 IBS: 0.20646419298665145
[I 2024-04-19 20:53:07,570] Trial 56 finished with value: 0.2266895314407969 and parameters: {'subsample': 0.7212011080007239, 'dropout_rate': 0.8438955180004126, 'n_estimators': 100, 'learning_rate': 0.05741100200450465}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2077923827311879
Fold 2 IBS: 0.19165837131470082
Fold 3 IBS: 0.1862465764499067

Fold 4 IBS: 0.22689079236666937
Fold 5 IBS: 0.18664061340044533
[I 2024-04-19 20:53:08,794] Trial 57 finished with value: 0.19984574725258203 and parameters: {'subsample': 0.5941008044918863, 'dropout_rate': 0.8145211095831743, 'n_estimators': 76, 'learning_rate': 0.04361786189303573}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2682466343232404
Fold 2 IBS: 0.2787824438907526
Fold 3 IBS: 0.23921027812662599
Fold 4 IBS: 0.2777408841763473
Fold 5 IBS: 0.24597873082417693
[I 2024-04-19 20:53:22,905] Trial 58 finished with value: 0.26199179426822866 and parameters: {'subsample': 0.26673471749953837, 'dropout_rate': 0.971121079564111, 'n_estimators': 498, 'learning_rate': 0.01939068551573221}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19376635289913924
Fold 2 IBS: 0.189719893658391
Fold 3 IBS: 0.18505133023430217
Fold 4 IBS: 0.20843304746625627
Fold 5 IBS: 0.1926255656956176
[I 2024-04-19 20:53:23,671] Trial 59 finished with value: 0.19391923799074126 and parameters: {'subsample': 0.4996282107459886, 'dropout_rate': 0.9113921780591948, 'n_estimators': 32, 'learning_rate': 0.05153317019190097}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.22622551124618678
Fold 2 IBS: 0.21522084966619245
Fold 3 IBS: 0.20085534937516697
Fold 4 IBS: 0.25109626819131187
Fold 5 IBS: 0.19763481531891386
[I 2024-04-19 20:53:26,134] Trial 60 finished with value: 0.21820655875955436 and parameters: {'subsample': 0.7836093360313852, 'dropout_rate': 0.6790635452190785, 'n_estimators': 131, 'learning_rate': 0.03835155769161802}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20266547244634725
Fold 2 IBS: 0.1879796284897969
Fold 3 IBS: 0.18412011597209021
Fold 4 IBS: 0.22124040030102618
Fold 5 IBS: 0.18643206193938236
[I 2024-04-19 20:53:27,069] Trial 61 finished with value: 0.19648753582972858 and parameters: {'subsample': 0.5167555193843152, 'dropout_rate': 0.998840517352031, 'n_estimators': 45, 'learning_rate': 0.06320141249811989}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20059810759702915
Fold 2 IBS: 0.18742385960408375
Fold 3 IBS: 0.18376044905048586
Fold 4 IBS: 0.21789442528693212
Fold 5 IBS: 0.18625521446949148
[I 2024-04-19 20:53:28,006] Trial 62 finished with value: 0.19518641120160446 and parameters: {'subsample': 0.6535971603418478, 'dropout_rate': 0.9372863854386199, 'n_estimators': 46, 'learning_rate': 0.058047159876127345}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19423703248659824
Fold 2 IBS: 0.19391199502983283
Fold 3 IBS: 0.18667377700617235
Fold 4 IBS: 0.20827653324922238
Fold 5 IBS: 0.19686017946388917
[I 2024-04-19 20:53:28,724] Trial 63 finished with value: 0.19599190344714298 and parameters: {'subsample': 0.3504578523578731, 'dropout_rate': 0.8595260521037198, 'n_estimators': 24, 'learning_rate': 0.053114622008679134}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19158682223871512
Fold 2 IBS: 0.1841759619143569
Fold 3 IBS: 0.17980364552561026
Fold 4 IBS: 0.21965000134296464
Fold 5 IBS: 0.18763089487023712
[I 2024-04-19 20:53:29,882] Trial 64 finished with value: 0.1925694651783768 and parameters: {'subsample': 0.1934598132104548, 'dropout_rate': 0.9633994217153925, 'n_estimators': 62, 'learning_rate': 0.04639412435815079}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20142546881816395
Fold 2 IBS: 0.18635672946784904
Fold 3 IBS: 0.18103612271761266
Fold 4 IBS: 0.21731334365562305
Fold 5 IBS: 0.18732193156356614
[I 2024-04-19 20:53:31,226] Trial 65 finished with value: 0.194690719244563 and parameters: {'subsample': 0.2005155395576778, 'dropout_rate': 0.6317092503496928, 'n_estimators': 67, 'learning_rate': 0.04176370439359285}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20257711430130568
Fold 2 IBS: 0.1955108139487245
Fold 3 IBS: 0.18131012733501914
Fold 4 IBS: 0.23130303827086662
Fold 5 IBS: 0.18952119394455097
[I 2024-04-19 20:53:32,871] Trial 66 finished with value: 0.2000444575600934 and parameters: {'subsample': 0.12690564630368148, 'dropout_rate': 0.7564766114006339, 'n_estimators': 85, 'learning_rate': 0.04820850213427399}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.27401635791133916
Fold 2 IBS: 0.28369050497303283
Fold 3 IBS: 0.2458631844200772
Fold 4 IBS: 0.2786039779446923
Fold 5 IBS: 0.25161848810710385
[I 2024-04-19 20:53:40,341] Trial 67 finished with value: 0.26675850267124906 and parameters: {'subsample': 0.23794962754503102, 'dropout_rate': 0.966660902421291, 'n_estimators': 321, 'learning_rate': 0.03318141487687266}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2959072043344444
Fold 2 IBS: 0.3147169774329635
Fold 3 IBS: 0.2908086845203311
Fold 4 IBS: 0.28983848059132755
Fold 5 IBS: 0.2928776810839601
[I 2024-04-19 20:53:52,122] Trial 68 finished with value: 0.2968298055926053 and parameters: {'subsample': 0.1724090824921748, 'dropout_rate': 0.9106774948547876, 'n_estimators': 423, 'learning_rate': 0.045595872034508635}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2039273630831135
Fold 2 IBS: 0.21008524217041943
Fold 3 IBS: 0.19705483955357048
Fold 4 IBS: 0.2167896609591263
Fold 5 IBS: 0.21090325662961634
[I 2024-04-19 20:53:52,706] Trial 69 finished with value: 0.20775207247916921 and parameters: {'subsample': 0.18890607008448618, 'dropout_rate': 0.5018363684466683, 'n_estimators': 10, 'learning_rate': 0.0408699328315649}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18877565628801282
Fold 2 IBS: 0.1843141006917746
Fold 3 IBS: 0.1789365136210923
Fold 4 IBS: 0.20556325574986634
Fold 5 IBS: 0.19115698939503123
[I 2024-04-19 20:53:53,917] Trial 70 finished with value: 0.18974930314915545 and parameters: {'subsample': 0.10656913291044298, 'dropout_rate': 0.867726384884077, 'n_estimators': 56, 'learning_rate': 0.03762925945735515}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18801903242945014
Fold 2 IBS: 0.18559728125968292
Fold 3 IBS: 0.17981715127885808
Fold 4 IBS: 0.2047653633806184
Fold 5 IBS: 0.1913326630010224
[I 2024-04-19 20:53:55,030] Trial 71 finished with value: 0.1899062982699264 and parameters: {'subsample': 0.11770953947682869, 'dropout_rate': 0.8761038474718528, 'n_estimators': 52, 'learning_rate': 0.03714339999753337}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18915673209148892
Fold 2 IBS: 0.18476003182836295
Fold 3 IBS: 0.1796783542735232
Fold 4 IBS: 0.20522895243695038
Fold 5 IBS: 0.19160003058378347
[I 2024-04-19 20:53:56,203] Trial 72 finished with value: 0.19008482024282178 and parameters: {'subsample': 0.10287767653903332, 'dropout_rate': 0.7929977045301531, 'n_estimators': 55, 'learning_rate': 0.03739563279581675}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19132245693249747
Fold 2 IBS: 0.1926915738901398
Fold 3 IBS: 0.1845483507352878
Fold 4 IBS: 0.20541205312087524
Fold 5 IBS: 0.19762021543991592
[I 2024-04-19 20:53:57,346] Trial 73 finished with value: 0.19431893002374323 and parameters: {'subsample': 0.10367584965310937, 'dropout_rate': 0.7955369817293524, 'n_estimators': 55, 'learning_rate': 0.025339068632050384}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19259136646185507
Fold 2 IBS: 0.18416706336797922
Fold 3 IBS: 0.17799975656501849
Fold 4 IBS: 0.2121118494800826
Fold 5 IBS: 0.18832346515196297
[I 2024-04-19 20:53:58,731] Trial 74 finished with value: 0.19103870020537966 and parameters: {'subsample': 0.13124891650606269, 'dropout_rate': 0.8731909027582333, 'n_estimators': 73, 'learning_rate': 0.03674475649074673}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19674147186893587
Fold 2 IBS: 0.1906155647386125
Fold 3 IBS: 0.1793623688255282
Fold 4 IBS: 0.22185158819995057
Fold 5 IBS: 0.18761613329643795
[I 2024-04-19 20:54:00,560] Trial 75 finished with value: 0.195237425385893 and parameters: {'subsample': 0.13363586107322345, 'dropout_rate': 0.8597125303810731, 'n_estimators': 96, 'learning_rate': 0.03705456568469312}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19814916642995403
Fold 2 IBS: 0.19525205054033254
Fold 3 IBS: 0.17944046723071355
Fold 4 IBS: 0.22999781079354395

Fold 5 IBS: 0.18850998676923908
[I 2024-04-19 20:54:02,874] Trial 76 finished with value: 0.19826989635275663 and parameters: {'subsample': 0.12630568358802877, 'dropout_rate': 0.8840084345145566, 'n_estimators': 124, 'learning_rate': 0.03271685219727702}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18940730445015777
Fold 2 IBS: 0.18561723422967616
Fold 3 IBS: 0.1792229738858936
Fold 4 IBS: 0.2055836548297881
Fold 5 IBS: 0.1921637886082129
[I 2024-04-19 20:54:04,220] Trial 77 finished with value: 0.19039899120074572 and parameters: {'subsample': 0.10014660118586548, 'dropout_rate': 0.8443946246731343, 'n_estimators': 72, 'learning_rate': 0.02825007388476382}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18932330340882508
Fold 2 IBS: 0.18926985095602739
Fold 3 IBS: 0.18192504040822394
Fold 4 IBS: 0.20484414608336163
Fold 5 IBS: 0.19515133549350383
[I 2024-04-19 20:54:05,714] Trial 78 finished with value: 0.1921027352699884 and parameters: {'subsample': 0.10199933765496583, 'dropout_rate': 0.8275062951227752, 'n_estimators': 76, 'learning_rate': 0.021988098548460084}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1930606746231858
Fold 2 IBS: 0.18790977966244074
Fold 3 IBS: 0.18260213015080165
Fold 4 IBS: 0.20660183014103506
Fold 5 IBS: 0.194751520171668
[I 2024-04-19 20:54:07,322] Trial 79 finished with value: 0.19298518694982625 and parameters: {'subsample': 0.16578451632221242, 'dropout_rate': 0.8234932980848235, 'n_estimators': 78, 'learning_rate': 0.021847064249626545}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19840435795368896
Fold 2 IBS: 0.2040001784719756
Fold 3 IBS: 0.1914323697972937
Fold 4 IBS: 0.21041953876761124
Fold 5 IBS: 0.20651556681613242
[I 2024-04-19 20:54:09,551] Trial 80 finished with value: 0.20215440236134036 and parameters: {'subsample': 0.10216922559396695, 'dropout_rate': 0.8426606906110224, 'n_estimators': 111, 'learning_rate': 0.007039353779474462}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1930457661879633
Fold 2 IBS: 0.18635763660869603
Fold 3 IBS: 0.1814868495212824
Fold 4 IBS: 0.20764619369798573
Fold 5 IBS: 0.1928942111735995
[I 2024-04-19 20:54:11,055] Trial 81 finished with value: 0.1922861314379054 and parameters: {'subsample': 0.14993676577936285, 'dropout_rate': 0.7837949823717368, 'n_estimators': 72, 'learning_rate': 0.027155336652944964}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1968132621863213
Fold 2 IBS: 0.18553189819991053
Fold 3 IBS: 0.18046928385910802
Fold 4 IBS: 0.21268661571664738
Fold 5 IBS: 0.18905811954057253
[I 2024-04-19 20:54:12,876] Trial 82 finished with value: 0.19291183590051195 and parameters: {'subsample': 0.14533771954457558, 'dropout_rate': 0.7729227414662975, 'n_estimators': 91, 'learning_rate': 0.029610078030023225}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19281200510976945
Fold 2 IBS: 0.1962918454061045
Fold 3 IBS: 0.18678003072367677
Fold 4 IBS: 0.2072054089336736
Fold 5 IBS: 0.1994929762236334
[I 2024-04-19 20:54:14,251] Trial 83 finished with value: 0.19651645327937153 and parameters: {'subsample': 0.12485705742267929, 'dropout_rate': 0.7498781950774163, 'n_estimators': 70, 'learning_rate': 0.016667492254363266}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20832242269284212
Fold 2 IBS: 0.19312301548755662
Fold 3 IBS: 0.18520338156200444
Fold 4 IBS: 0.23197461674448994
Fold 5 IBS: 0.18690188479456712
[I 2024-04-19 20:54:16,733] Trial 84 finished with value: 0.20110506425629202 and parameters: {'subsample': 0.21980592674611535, 'dropout_rate': 0.8746857427139761, 'n_estimators': 132, 'learning_rate': 0.028017628259546432}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1922630194603401
Fold 2 IBS: 0.19392334466294417
Fold 3 IBS: 0.18554637777890504
Fold 4 IBS: 0.20651068143480816
Fold 5 IBS: 0.19808617937601186
[I 2024-04-19 20:54:17,843] Trial 85 finished with value: 0.19526592054260186 and parameters: {'subsample': 0.10236666178275439, 'dropout_rate': 0.797649261341329, 'n_estimators': 49, 'learning_rate': 0.02619292923500433}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1916659213759877
Fold 2 IBS: 0.18144577470120285
Fold 3 IBS: 0.18027387322798005
Fold 4 IBS: 0.21517914130479537
Fold 5 IBS: 0.18934176533882963
[I 2024-04-19 20:54:19,565] Trial 86 finished with value: 0.19158129518975914 and parameters: {'subsample': 0.1722965890195455, 'dropout_rate': 0.3232340824764945, 'n_estimators': 83, 'learning_rate': 0.03137955935528175}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.2352646985965093
Fold 2 IBS: 0.24043899601044316
Fold 3 IBS: 0.2017837820978419
Fold 4 IBS: 0.2719231886601066
Fold 5 IBS: 0.22547903733334076
[I 2024-04-19 20:54:26,184] Trial 87 finished with value: 0.23497794053964838 and parameters: {'subsample': 0.1677344353169537, 'dropout_rate': 0.22153669566523881, 'n_estimators': 238, 'learning_rate': 0.03556292961683008}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20195012839575877
Fold 2 IBS: 0.20817668288802027
Fold 3 IBS: 0.19493621708883774
Fold 4 IBS: 0.21331446599751785
Fold 5 IBS: 0.2096958892843233
[I 2024-04-19 20:54:27,056] Trial 88 finished with value: 0.2056146767308916 and parameters: {'subsample': 0.1756169214565967, 'dropout_rate': 0.38064416490088476, 'n_estimators': 27, 'learning_rate': 0.0215676140596985}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18896531251251358
Fold 2 IBS: 0.18370321993050873
Fold 3 IBS: 0.17547320503484018
Fold 4 IBS: 0.21289987546627573
Fold 5 IBS: 0.190695927509944
[I 2024-04-19 20:54:28,924] Trial 89 finished with value: 0.19034750809081646 and parameters: {'subsample': 0.13360665877080907, 'dropout_rate': 0.22023811696478135, 'n_estimators': 84, 'learning_rate': 0.03173732176626525}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1904588847308977
Fold 2 IBS: 0.1820630561479629
Fold 3 IBS: 0.17561367095816655
Fold 4 IBS: 0.21451348309993962
Fold 5 IBS: 0.19010907576782635
[I 2024-04-19 20:54:30,832] Trial 90 finished with value: 0.1905516341409586 and parameters: {'subsample': 0.1419126137052824, 'dropout_rate': 0.19732329979422356, 'n_estimators': 89, 'learning_rate': 0.030961406801389323}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1937368572158752
Fold 2 IBS: 0.18255804403233244
Fold 3 IBS: 0.17536957317685983
Fold 4 IBS: 0.219798868564982
Fold 5 IBS: 0.18858658447425553
[I 2024-04-19 20:54:33,178] Trial 91 finished with value: 0.19200998549286102 and parameters: {'subsample': 0.13523197998136433, 'dropout_rate': 0.1816278275922235, 'n_estimators': 107, 'learning_rate': 0.031046275416648887}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19026345155855612
Fold 2 IBS: 0.18172745528320053
Fold 3 IBS: 0.17357217969819172
Fold 4 IBS: 0.21855758197366434
Fold 5 IBS: 0.18938541709857612
[I 2024-04-19 20:54:35,054] Trial 92 finished with value: 0.19070121712243776 and parameters: {'subsample': 0.12099413227120714, 'dropout_rate': 0.2360389529832501, 'n_estimators': 87, 'learning_rate': 0.037822198996312256}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.1875592020234544
Fold 2 IBS: 0.18495702366380343
Fold 3 IBS: 0.18066622244209024
Fold 4 IBS: 0.20638103324628726
Fold 5 IBS: 0.19510450012007635
[I 2024-04-19 20:54:36,256] Trial 93 finished with value: 0.19093359629914236 and parameters: {'subsample': 0.11629149070607792, 'dropout_rate': 0.27229375963074853, 'n_estimators': 55, 'learning_rate': 0.037367962209726754}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18901226713237076
Fold 2 IBS: 0.1867359671590443
Fold 3 IBS: 0.18177504123187127
Fold 4 IBS: 0.20522052196140123
Fold 5 IBS: 0.19629235279705168
[I 2024-04-19 20:54:37,475] Trial 94 finished with value: 0.19180723005634787 and parameters: {'subsample': 0.11946514460941712, 'dropout_rate': 0.25812250161199846, 'n_estimators': 53, 'learning_rate': 0.03423827022943611}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.22143441069051187
Fold 2 IBS: 0.21897890733870734
Fold 3 IBS: 0.19975187511403822
Fold 4 IBS: 0.25725723370546333

Fold 5 IBS: 0.20014255507293266
[I 2024-04-19 20:54:41,246] Trial 95 finished with value: 0.2195129963843307 and parameters: {'subsample': 0.22312870945580054, 'dropout_rate': 0.18446795693693951, 'n_estimators': 157, 'learning_rate': 0.039295794278161086}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19992479383400288
Fold 2 IBS: 0.20517405006053488
Fold 3 IBS: 0.19391089824160457
Fold 4 IBS: 0.21217526772368775
Fold 5 IBS: 0.20713449631139202
[I 2024-04-19 20:54:41,961] Trial 96 finished with value: 0.20366390123424444 and parameters: {'subsample': 0.1912179760870773, 'dropout_rate': 0.22408550586961065, 'n_estimators': 15, 'learning_rate': 0.04302122604055191}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.19731564490295572
Fold 2 IBS: 0.18212229764194593
Fold 3 IBS: 0.17940905442950114
Fold 4 IBS: 0.22963273523465397
Fold 5 IBS: 0.18885746554699534
[I 2024-04-19 20:54:44,111] Trial 97 finished with value: 0.19546743955121043 and parameters: {'subsample': 0.1516274853882422, 'dropout_rate': 0.31372183756474226, 'n_estimators': 97, 'learning_rate': 0.03790062958143788}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.18991532143977022
Fold 2 IBS: 0.18825887293557353
Fold 3 IBS: 0.1825147601851393
Fold 4 IBS: 0.20545288143952264
Fold 5 IBS: 0.19860733855560914
[I 2024-04-19 20:54:45,431] Trial 98 finished with value: 0.19294983491112294 and parameters: {'subsample': 0.11797570660224695, 'dropout_rate': 0.2910696142571321, 'n_estimators': 57, 'learning_rate': 0.02946852567796991}. Best is trial 19 with value: 0.1893596887475797.
Fold 1 IBS: 0.20913728358151293
Fold 2 IBS: 0.21618299718855674
Fold 3 IBS: 0.19477496408847556
Fold 4 IBS: 0.25900607841980927
Fold 5 IBS: 0.2082675524726613
[I 2024-04-19 20:54:50,237] Trial 99 finished with value: 0.21747377515020316 and parameters: {'subsample': 0.1446056036507585, 'dropout_rate': 0.10220283524273781, 'n_estimators': 187, 'learning_rate': 0.040330745957785984}. Best is trial 19 with value: 0.1893596887475797.


* Best trial for IBS:
 FrozenTrial(number=19, state=TrialState.COMPLETE, values=[0.1893596887475797], datetime_start=datetime.datetime(2024, 4, 19, 20, 51, 47, 101009), datetime_complete=datetime.datetime(2024, 4, 19, 20, 51, 48, 167102), params={'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=19, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}


* Best Score for IBS:
 0.1893596887475797

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.724
train_ibs:  0.189

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6140864163365967,
                                              learning_rate=0.09358014693300638,
                                              n_estimators=441,
                                              random_state=123,
                                              subsample=0.10718290653750012)

C-index score: 0.556

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9930703343219778,
                                              learning_rate=0.04096883532946153,
                                              n_estimators=51, random_state=123,
                                              subsample=0.10013306718236009)

IBS: 0.229

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [80]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.871   1.0
ExtraSurvivalTrees               0.816   2.0
GradientBoosting                 0.791   3.0
CoxPH                            0.774   4.0
CoxLasso                         0.773   5.5
CoxElastic                       0.773   5.5
ComponentwiseGradientBoosting    0.724   7.0
CoxRidge                         0.691   8.0

In [81]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.175   1.0
CoxLasso                       0.181   3.0
CoxElastic                     0.181   3.0
ExtraSurvivalTrees             0.181   3.0
CoxPH                          0.182   5.0
ComponentwiseGradientBoosting  0.189   6.0
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [82]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.656   1.0
GradientBoosting                 0.630   2.0
Randomsurvivalforest             0.618   3.0
CoxLasso                         0.590   4.0
CoxElastic                       0.589   5.0
CoxPH                            0.587   6.0
CoxRidge                         0.558   7.0
ComponentwiseGradientBoosting    0.556   8.0

In [83]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.214   1.0
GradientBoosting               0.220   2.0
CoxRidge                       0.221   3.0
Randomsurvivalforest           0.223   4.0
ComponentwiseGradientBoosting  0.229   5.0
CoxLasso                       0.273   6.5
CoxElastic                     0.273   6.5
CoxPH                          0.278   8.0

In [84]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/robust/rent/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_robust_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [85]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-19