In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

## Test dataset: MAASTRO

In [5]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [6]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [7]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [8]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [9]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [10]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [11]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [12]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [13]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [14]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [15]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

### COX PLSR

In [16]:
# Choose features from the result of Cox PLSR in R
plsr = [
"uicc8_III-IV",
"cavum_oris",
"hpv_related",
"charlson",
"shape_MajorAxisLength",
"shape_Elongation",
"hypopharynx"
]

In [17]:
X_plsr = X.loc[:, plsr]
X_new = X_plsr.copy()

In [18]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, plsr]

# Standardization

In [19]:
# Copy the original X for later 
original_X = X.copy()

In [20]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [21]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [22]:
X_new

,uicc8_III-IV,cavum_oris,hpv_related,charlson,shape_MajorAxisLength,shape_Elongation,hypopharynx
0,0.0,0,0.0,0,42.073251,0.600926,0
1,0.0,0,0.0,1,24.613845,0.841579,0
2,1.0,1,0.0,1,48.030294,0.772821,0
3,0.0,0,0.0,1,25.589900,0.847727,0
4,0.0,0,0.0,1,34.684750,0.831483,0
...,...,...,...,...,...,...,...
134,0.0,0,1.0,0,33.069705,0.680294,0
135,1.0,0,1.0,0,41.043692,0.758193,0
136,0.0,0,1.0,1,36.618802,0.770113,0
137,1.0,0,1.0,1,45.870392,0.628897,0
138,1.0,0,1.0,0,30.363259,0.892637,0

In [23]:
X_new_std

,uicc8_III-IV,cavum_oris,hpv_related,charlson,shape_MajorAxisLength,shape_Elongation,hypopharynx
0,0.0,0,0.0,0,0.059912,-0.485459,0
1,0.0,0,0.0,1,-0.755402,0.666232,0
2,1.0,1,0.0,1,0.338093,0.337179,0
3,0.0,0,0.0,1,-0.709822,0.695653,0
4,0.0,0,0.0,1,-0.285114,0.617917,0
...,...,...,...,...,...,...,...
134,0.0,0,1.0,0,-0.360532,-0.105628,0
135,1.0,0,1.0,0,0.011834,0.267171,0
136,0.0,0,1.0,1,-0.194798,0.324219,0
137,1.0,0,1.0,1,0.237230,-0.351598,0
138,1.0,0,1.0,0,-0.486917,0.910577,0

In [24]:
MAASTRO_new

,uicc8_III-IV,cavum_oris,hpv_related,charlson,shape_MajorAxisLength,shape_Elongation,hypopharynx
0,0,0,1,1,50.002093,0.765178,0
1,1,0,0,0,41.753334,0.776540,0
2,1,0,0,1,44.375483,0.697164,0
3,1,0,0,1,46.115989,0.574636,0
4,0,0,1,1,54.394967,0.633419,0
...,...,...,...,...,...,...,...
94,1,0,0,0,34.218615,0.882411,0
95,1,0,0,1,51.046869,0.535802,0
96,1,0,1,1,50.417953,0.716610,0
97,0,0,1,0,44.901412,0.665145,0
98,1,0,0,0,36.574294,0.616262,1

In [25]:
MAASTRO_new_std

,uicc8_III-IV,cavum_oris,hpv_related,charlson,shape_MajorAxisLength,shape_Elongation,hypopharynx
0,0,0,1,1,0.430171,0.300600,0
1,1,0,0,0,0.044973,0.354974,0
2,1,0,0,1,0.167421,-0.024893,0
3,1,0,0,1,0.248699,-0.611274,0
4,0,0,1,1,0.635308,-0.329957,0
...,...,...,...,...,...,...,...
94,1,0,0,0,-0.306881,0.861639,0
95,1,0,0,1,0.478960,-0.797117,0
96,1,0,1,1,0.449591,0.068172,0
97,0,0,1,0,0.191981,-0.178126,0
98,1,0,0,0,-0.196876,-0.412064,1

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [26]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:46:42,382] A new study created in memory with name: no-name-93769e59-ea6e-47a3-bf51-1d23e769ddae

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-17 13:46:44,728] A new study created in memory with name: no-name-31f3a0d1-0432-44c4-8f38-86740c41d83c

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:44,716] Trial 0 finished with value: 0.7856995180201451 and parameters: {}. Best is trial 0 with value: 0.7856995180201451.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7856995180201451], datetime_start=datetime.datetime(2024, 4, 17, 13, 46, 42, 424231), datetime_complete=datetime.datetime(2024, 4, 17, 13, 46, 44, 715132), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7856995180201451

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1621371716412286
Fold 2 IBS: 0.1554762462247702
Fold 3 IBS: 0.12492102173294406
Fold 4 IBS: 0.13624116793254798
Fold 5 IBS: 0.22992325081669146
[I 2024-04-17 13:46:44,876] Trial 0 finished with value: 0.16173977166963643 and parameters: {}. Best is trial 0 with value: 0.16173977166963643.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.16173977166963643], datetime_start=datetime.datetime(2024, 4, 17, 13, 46, 44, 748454), datetime_complete=datetime.datetime(2024, 4, 17, 13, 46, 44, 876091), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.16173977166963643

In [27]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [28]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.786
train_ibs:  0.162

#### Test

In [29]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [30]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.614
IBS score: 0.251

In [31]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [32]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [33]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:46:44,966] A new study created in memory with name: no-name-25dfb8a6-7c0a-4ca0-8791-cfb7596b7e0d

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-17 13:46:45,030] A new study created in memory with name: no-name-645eee19-66d2-4123-8ecf-9156d195cd9e

Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7112676056338029
[I 2024-04-17 13:46:45,028] Trial 0 finished with value: 0.7160060514829768 and parameters: {}. Best is trial 0 with value: 0.7160060514829768.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7160060514829768], datetime_start=datetime.datetime(2024, 4, 17, 13, 46, 44, 980216), datetime_complete=datetime.datetime(2024, 4, 17, 13, 46, 45, 28572), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7160060514829768

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651990447034
Fold 2 IBS: 0.22157790861385837
Fold 3 IBS: 0.20453594300033467
Fold 4 IBS: 0.22473803563950742
Fold 5 IBS: 0.21812430988324932
[I 2024-04-17 13:46:45,126] Trial 0 finished with value: 0.21659054340828404 and parameters: {}. Best is trial 0 with value: 0.21659054340828404.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054340828404], datetime_start=datetime.datetime(2024, 4, 17, 13, 46, 45, 47652), datetime_complete=datetime.datetime(2024, 4, 17, 13, 46, 45, 125985), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054340828404

In [34]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [35]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.716
train_ibs:  0.217

#### Test

In [36]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [37]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.611

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [38]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [39]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:46:45,204] A new study created in memory with name: no-name-c84a86ad-1dcd-4a09-86a2-8899d26e3d3f

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815

[I 2024-04-17 13:46:45,364] A new study created in memory with name: no-name-9affe03c-8b4f-47a2-8a94-05f765e22fa2

Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:45,362] Trial 0 finished with value: 0.7831355378826356 and parameters: {}. Best is trial 0 with value: 0.7831355378826356.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7831355378826356], datetime_start=datetime.datetime(2024, 4, 17, 13, 46, 45, 223213), datetime_complete=datetime.datetime(2024, 4, 17, 13, 46, 45, 362544), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7831355378826356

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16292158130041123
Fold 2 IBS: 0.15660891622574832
Fold 3 IBS: 0.12530869869579714
Fold 4 IBS: 0.13550835255873864
Fold 5 IBS: 0.2298637021937879
[I 2024-04-17 13:46:45,515] Trial 0 finished with value: 0.16204225019489665 and parameters: {}. Best is trial 0 with value: 0.16204225019489665.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.16204225019489665], datetime_start=datetime.datetime(2024, 4, 17, 13, 46, 45, 380484), datetime_complete=datetime.datetime(2024, 4, 17, 13, 46, 45, 515244), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.16204225019489665

In [40]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [41]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.783
train_ibs:  0.162

#### Test

In [42]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [43]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.619

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.248

In [44]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [45]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:46:45,611] A new study created in memory with name: no-name-5aea4676-d26b-492a-8e3f-92209cb21c1f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:45,771] Trial 0 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:45,907] Trial 1 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,043] Trial 2 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,165] Trial 3 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,281] Trial 4 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,405] Trial 5 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,527] Trial 6 finished with value: 0.7840283950254927 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,644] Trial 7 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,769] Trial 8 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:46,898] Trial 9 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:47,016] Trial 10 finished with value: 0.7840283950254927 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:47,166] Trial 11 finished with value: 0.7656974550545674 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:47,318] Trial 12 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.21309581087335225}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:47,446] Trial 13 finished with value: 0.7840283950254927 and parameters: {'l1_ratio': 0.743964055575976}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:47,592] Trial 14 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.21599024455432275}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:47,765] Trial 15 finished with value: 0.7840283950254927 and parameters: {'l1_ratio': 0.820763570686791}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:47,913] Trial 16 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.5880713606511995}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:48,049] Trial 17 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.35870521424355084}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:48,170] Trial 18 finished with value: 0.7345286238857364 and parameters: {'l1_ratio': 0.039318771596377255}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:48,299] Trial 19 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:48,428] Trial 20 finished with value: 0.7840283950254927 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:48,575] Trial 21 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.26843065456411686}. Best is trial 0 with value: 0.7849212521683497.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:48,748] Trial 22 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.13361135845786085}. Best is trial 22 with value: 0.7859016443252125.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:49,012] Trial 23 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.1124690541840564}. Best is trial 22 with value: 0.7859016443252125.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286

Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:49,182] Trial 24 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.1170295107004102}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:49,331] Trial 25 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.12355427757000426}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:49,486] Trial 26 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.11881900182625091}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:49,646] Trial 27 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.15294537242057224}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 13:46:49,749] Trial 28 finished with value: 0.7177668719394596 and parameters: {'l1_ratio': 0.025469879651079566}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:49,890] Trial 29 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.3307203768972654}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:50,054] Trial 30 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.1573756751081235}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:50,207] Trial 31 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:50,362] Trial 32 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.08136477993218522}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:50,519] Trial 33 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.19310078425264537}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:50,667] Trial 34 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.3044725907324346}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 13:46:50,717] Trial 35 finished with value: 0.719639075625712 and parameters: {'l1_ratio': 0.0016646641563191067}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:50,860] Trial 36 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.25307162868630584}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:51,035] Trial 37 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.07798314466656901}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:51,207] Trial 38 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.18404468288294262}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:51,331] Trial 39 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:51,465] Trial 40 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.2705989592091768}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:51,626] Trial 41 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.08827540682368501}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:51,782] Trial 42 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.1487860536843228}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:51,947] Trial 43 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.06947589307142489}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:52,105] Trial 44 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.16655904762637716}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:52,257] Trial 45 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.099820444786656}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 13:46:52,303] Trial 46 finished with value: 0.719639075625712 and parameters: {'l1_ratio': 0.00014092907427663837}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:52,439] Trial 47 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.23625786276913957}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429

Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:52,577] Trial 48 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.37534590273406454}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:52,743] Trial 49 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.06313647075764142}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:52,916] Trial 50 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.31297686520002327}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:53,110] Trial 51 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.08676691135259856}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:53,260] Trial 52 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.19106455742613765}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:53,400] Trial 53 finished with value: 0.7656974550545674 and parameters: {'l1_ratio': 0.04203532993526567}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:53,560] Trial 54 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.13883160035581293}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:53,741] Trial 55 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.22175594841305862}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:53,962] Trial 56 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.10660788804562292}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:54,165] Trial 57 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.07300520320823406}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:54,335] Trial 58 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.5503819226045732}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 13:46:54,494] Trial 59 finished with value: 0.7335896567495862 and parameters: {'l1_ratio': 0.03097059791799127}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:54,633] Trial 60 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.1706260767598933}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:54,782] Trial 61 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.20168477408364632}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:54,938] Trial 62 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.12171367626772121}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:55,083] Trial 63 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.18044627726076976}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:55,224] Trial 64 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.23383024342924416}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:55,387] Trial 65 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.1436169890065124}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:55,556] Trial 66 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.06145452007472046}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:55,739] Trial 67 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.10969010771057763}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 13:46:55,877] Trial 68 finished with value: 0.7177668719394596 and parameters: {'l1_ratio': 0.02571932268911499}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:56,063] Trial 69 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.2841405425465938}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:56,256] Trial 70 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.16568052017643914}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:56,505] Trial 71 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.08210506381697003}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229

Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:56,745] Trial 72 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.09933871445503087}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:56,903] Trial 73 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.1369602849130146}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:57,063] Trial 74 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.19535938664729027}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:57,228] Trial 75 finished with value: 0.7345286238857364 and parameters: {'l1_ratio': 0.0397803180394764}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:57,369] Trial 76 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.6785247601103999}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:57,513] Trial 77 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.4120884713136076}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:57,665] Trial 78 finished with value: 0.7840283950254927 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:57,805] Trial 79 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.2541515122138295}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 13:46:57,850] Trial 80 finished with value: 0.719639075625712 and parameters: {'l1_ratio': 0.0006155210982383974}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:58,009] Trial 81 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.06498680169543752}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:58,174] Trial 82 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.08803220129713485}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:58,327] Trial 83 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.12389517733638361}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:58,603] Trial 84 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.05447313739750752}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:58,787] Trial 85 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.1615274208102702}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:58,962] Trial 86 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.08579540666223237}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:59,119] Trial 87 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.11954506505946154}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 13:46:59,214] Trial 88 finished with value: 0.714195443368031 and parameters: {'l1_ratio': 0.019446311945580247}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:59,388] Trial 89 finished with value: 0.7849212521683497 and parameters: {'l1_ratio': 0.2176274013471826}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:59,619] Trial 90 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.15599735412181573}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:46:59,828] Trial 91 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.10029415978105571}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:47:00,150] Trial 92 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.06531946863297894}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:47:00,315] Trial 93 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.18212442468223156}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:47:00,478] Trial 94 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.13745831117178828}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815

Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:47:00,691] Trial 95 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.10451336013808811}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 13:47:00,801] Trial 96 finished with value: 0.714195443368031 and parameters: {'l1_ratio': 0.02028229035681206}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:47:00,988] Trial 97 finished with value: 0.7656974550545674 and parameters: {'l1_ratio': 0.04806567404513119}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:47:01,167] Trial 98 finished with value: 0.7867945014680696 and parameters: {'l1_ratio': 0.07905892847298394}. Best is trial 24 with value: 0.7867945014680696.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882

[I 2024-04-17 13:47:01,399] A new study created in memory with name: no-name-8dd3d46f-62c0-453b-a9f5-af36533b7df1

Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:47:01,395] Trial 99 finished with value: 0.7859016443252125 and parameters: {'l1_ratio': 0.20825093905976622}. Best is trial 24 with value: 0.7867945014680696.


* Best trial for C-index:
 FrozenTrial(number=24, state=TrialState.COMPLETE, values=[0.7867945014680696], datetime_start=datetime.datetime(2024, 4, 17, 13, 46, 49, 14208), datetime_complete=datetime.datetime(2024, 4, 17, 13, 46, 49, 182132), params={'l1_ratio': 0.1170295107004102}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=24, value=None)


* Best Score for C-index:
 0.7867945014680696

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16285644648646216
Fold 2 IBS: 0.15585311565238952
Fold 3 IBS: 0.12511836909907842
Fold 4 IBS: 0.1355541847291143
Fold 5 IBS: 0.22928182727591367
[I 2024-04-17 13:47:01,602] Trial 0 finished with value: 0.1617327886485916 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.1617327886485916.
Fold 1 IBS: 0.16267368313562722
Fold 2 IBS: 0.154658326768194
Fold 3 IBS: 0.12477067271879583
Fold 4 IBS: 0.135680354593449
Fold 5 IBS: 0.2283905057414276
[I 2024-04-17 13:47:01,781] Trial 1 finished with value: 0.16123470859149874 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.16123470859149874.
Fold 1 IBS: 0.16262991500323248
Fold 2 IBS: 0.15444309239207518
Fold 3 IBS: 0.12472492724276149
Fold 4 IBS: 0.13574382309167732
Fold 5 IBS: 0.22834896398733434
[I 2024-04-17 13:47:02,027] Trial 2 finished with value: 0.16117814434341615 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.1627723450434112
Fold 2 IBS: 0.15545874706457258
Fold 3 IBS: 0.12500063815990195
Fold 4 IBS: 0.1356106579876451
Fold 5 IBS: 0.22897460283459836
[I 2024-04-17 13:47:02,259] Trial 3 finished with value: 0.16156339821802584 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.16284437375359687
Fold 2 IBS: 0.15594796941566536
Fold 3 IBS: 0.12512923613378127
Fold 4 IBS: 0.13556204103707165
Fold 5 IBS: 0.2292870733003016
[I 2024-04-17 13:47:02,417] Trial 4 finished with value: 0.16175413872808334 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.1627212382705722
Fold 2 IBS: 0.15507575783590108
Fold 3 IBS: 0.12488538380869184
Fold 4 IBS: 0.13564543841205876
Fold 5 IBS: 0.22867488674176847
[I 2024-04-17 13:47:02,622] Trial 5 finished with value: 0.16140054101379847 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.16292805283878195
Fold 2 IBS: 0.15647717925209262
Fold 3 IBS: 0.12530197138071594
Fold 4 IBS: 0.13550425697786725
Fold 5 IBS: 0.22982687774023075
[I 2024-04-17 13:47:02,784] Trial 6 finished with value: 0.1620076676379377 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.16286300920575672
Fold 2 IBS: 0.15582781036983825
Fold 3 IBS: 0.12511270879602987
Fold 4 IBS: 0.13555002726576446
Fold 5 IBS: 0.22924956832541343
[I 2024-04-17 13:47:02,954] Trial 7 finished with value: 0.16172062479256055 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.16274619980910074
Fold 2 IBS: 0.15525426231803546
Fold 3 IBS: 0.12494348105662896
Fold 4 IBS: 0.13562837245594392
Fold 5 IBS: 0.22882346347865032
[I 2024-04-17 13:47:03,231] Trial 8 finished with value: 0.16147915582367187 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.16275448001446086
Fold 2 IBS: 0.15499008751483376
Fold 3 IBS: 0.1248638526479312
Fold 4 IBS: 0.13567481533331102
Fold 5 IBS: 0.22863643724777408
[I 2024-04-17 13:47:03,476] Trial 9 finished with value: 0.16138393455166217 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.16117814434341615.
Fold 1 IBS: 0.1624650423984623
Fold 2 IBS: 0.1540445171717469
Fold 3 IBS: 0.12461128036614535
Fold 4 IBS: 0.13581748727660084
Fold 5 IBS: 0.227986225659771
[I 2024-04-17 13:47:03,802] Trial 10 finished with value: 0.16098491057454528 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.21372783315958502
Fold 2 IBS: 0.2205357589669191
Fold 3 IBS: 0.20401036910822443
Fold 4 IBS: 0.22403621504739837
Fold 5 IBS: 0.21747289755779137
[I 2024-04-17 13:47:03,875] Trial 11 finished with value: 0.21595661476798367 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.16246522209991837
Fold 2 IBS: 0.15404296306711865
Fold 3 IBS: 0.12461102734047956
Fold 4 IBS: 0.13581715409426742
Fold 5 IBS: 0.2281165961877154
[I 2024-04-17 13:47:04,078] Trial 12 finished with value: 0.1610105925578999 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.21391121098163624
Fold 2 IBS: 0.2213042734815996
Fold 3 IBS: 0.20439804479560017
Fold 4 IBS: 0.2245541455061555
Fold 5 IBS: 0.21795293517000777
[I 2024-04-17 13:47:04,159] Trial 13 finished with value: 0.21642412198699984 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.16257952474640341
Fold 2 IBS: 0.1541973237645385
Fold 3 IBS: 0.12465627853205957
Fold 4 IBS: 0.13576627002590674
Fold 5 IBS: 0.22818866051625236
[I 2024-04-17 13:47:04,404] Trial 14 finished with value: 0.16107761151703212 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.16257724971035548
Fold 2 IBS: 0.1542177576598776
Fold 3 IBS: 0.12465964027464779
Fold 4 IBS: 0.13577054858819015
Fold 5 IBS: 0.22821284563944305
[I 2024-04-17 13:47:04,707] Trial 15 finished with value: 0.1610876083745028 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.16255124488439537
Fold 2 IBS: 0.15420301939176698
Fold 3 IBS: 0.12465306596525477
Fold 4 IBS: 0.13578410108814698
Fold 5 IBS: 0.2280937670656492
[I 2024-04-17 13:47:05,005] Trial 16 finished with value: 0.16105703967904267 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.16266662584238717
Fold 2 IBS: 0.15468171770849803
Fold 3 IBS: 0.12477490261754215
Fold 4 IBS: 0.13568500963508193
Fold 5 IBS: 0.22842004897148963
[I 2024-04-17 13:47:05,231] Trial 17 finished with value: 0.16124566095499976 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 10 with value: 0.16098491057454528.
Fold 1 IBS: 0.16244695077677582
Fold 2 IBS: 0.15394346352842528
Fold 3 IBS: 0.12459040362892973
Fold 4 IBS: 0.13581567165756667
Fold 5 IBS: 0.22804716970335057
[I 2024-04-17 13:47:05,533] Trial 18 finished with value: 0.16096873185900962 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.1629240420148532
Fold 2 IBS: 0.1564938847779055
Fold 3 IBS: 0.12530624751146693
Fold 4 IBS: 0.1355068648846123
Fold 5 IBS: 0.22985032118526424
[I 2024-04-17 13:47:05,719] Trial 19 finished with value: 0.16201627207482044 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.1626739574972174
Fold 2 IBS: 0.154522682728177
Fold 3 IBS: 0.12473203926001865
Fold 4 IBS: 0.13571595835953248
Fold 5 IBS: 0.22830975213818222
[I 2024-04-17 13:47:05,986] Trial 20 finished with value: 0.16119087799662557 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.1624809482605433
Fold 2 IBS: 0.15406508404674166
Fold 3 IBS: 0.12461464777376655
Fold 4 IBS: 0.1357856874518862
Fold 5 IBS: 0.22801224050040328
[I 2024-04-17 13:47:06,257] Trial 21 finished with value: 0.1609917216066682 and parameters: {'l1_ratio': 0.08499433228302328}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16243309118142654
Fold 2 IBS: 0.15395166999548482
Fold 3 IBS: 0.12458969261549636
Fold 4 IBS: 0.13582631713337606
Fold 5 IBS: 0.2280435148805162
[I 2024-04-17 13:47:06,490] Trial 22 finished with value: 0.16096885716126003 and parameters: {'l1_ratio': 0.06198923218141986}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.2139280206857156
Fold 2 IBS: 0.22137472801444857
Fold 3 IBS: 0.20443355285115108
Fold 4 IBS: 0.22460151145197976
Fold 5 IBS: 0.21799703692854128
[I 2024-04-17 13:47:06,570] Trial 23 finished with value: 0.21646696998636727 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16261243348242313
Fold 2 IBS: 0.1543675628924489
Fold 3 IBS: 0.12470564239994686
Fold 4 IBS: 0.13575501404597912
Fold 5 IBS: 0.22829674372287165
[I 2024-04-17 13:47:06,785] Trial 24 finished with value: 0.16114747930873394 and parameters: {'l1_ratio': 0.20495632796046423}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16276158591132725
Fold 2 IBS: 0.15491411638935762

Fold 3 IBS: 0.12484560235349428
Fold 4 IBS: 0.13566093624797182
Fold 5 IBS: 0.22863259234209302
[I 2024-04-17 13:47:07,078] Trial 25 finished with value: 0.1613629666488488 and parameters: {'l1_ratio': 0.3735924863066886}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16249693451768032
Fold 2 IBS: 0.15407471575191606
Fold 3 IBS: 0.12462167412724169
Fold 4 IBS: 0.13580216133773948
Fold 5 IBS: 0.22812398693462033
[I 2024-04-17 13:47:07,306] Trial 26 finished with value: 0.16102389453383958 and parameters: {'l1_ratio': 0.09964738096662551}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16269465518844656
Fold 2 IBS: 0.15471860628416437
Fold 3 IBS: 0.12479095106679061
Fold 4 IBS: 0.13570277321265398
Fold 5 IBS: 0.228515782642803
[I 2024-04-17 13:47:07,532] Trial 27 finished with value: 0.1612845536789717 and parameters: {'l1_ratio': 0.3095665171510701}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16261819911919156
Fold 2 IBS: 0.1543484671235953
Fold 3 IBS: 0.12470250247909997
Fold 4 IBS: 0.13575136650443598
Fold 5 IBS: 0.22827435790535988
[I 2024-04-17 13:47:07,779] Trial 28 finished with value: 0.16113897862633655 and parameters: {'l1_ratio': 0.2025095518368651}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16282377399274228
Fold 2 IBS: 0.1556010512414171
Fold 3 IBS: 0.1250464720934406
Fold 4 IBS: 0.13557633356258936
Fold 5 IBS: 0.2290665663931304
[I 2024-04-17 13:47:08,005] Trial 29 finished with value: 0.16162283945666395 and parameters: {'l1_ratio': 0.6009870305519948}. Best is trial 18 with value: 0.16096873185900962.
Fold 1 IBS: 0.16244826919696911
Fold 2 IBS: 0.15393226859636763
Fold 3 IBS: 0.12458865018063979
Fold 4 IBS: 0.1358131452378054
Fold 5 IBS: 0.22803399941325442
[I 2024-04-17 13:47:08,270] Trial 30 finished with value: 0.16096326652500728 and parameters: {'l1_ratio': 0.06639229704275984}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16240885590411078
Fold 2 IBS: 0.15388271994164182
Fold 3 IBS: 0.12457377142348566
Fold 4 IBS: 0.22214174152439833
Fold 5 IBS: 0.22798885817531356
[I 2024-04-17 13:47:08,516] Trial 31 finished with value: 0.17819918939379004 and parameters: {'l1_ratio': 0.04614974199010863}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1625891853816025
Fold 2 IBS: 0.1543111238965424
Fold 3 IBS: 0.12466873507222243
Fold 4 IBS: 0.1357699460124679
Fold 5 IBS: 0.22817925114970877
[I 2024-04-17 13:47:08,736] Trial 32 finished with value: 0.16110364830250878 and parameters: {'l1_ratio': 0.16517164587757982}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16244392685183068
Fold 2 IBS: 0.15397003364157208
Fold 3 IBS: 0.12459461968754043
Fold 4 IBS: 0.1358219290855748
Fold 5 IBS: 0.2280544102124488
[I 2024-04-17 13:47:08,969] Trial 33 finished with value: 0.16097698389579335 and parameters: {'l1_ratio': 0.06805221062336887}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16269618479162526
Fold 2 IBS: 0.1546040462188871
Fold 3 IBS: 0.12475341926347458
Fold 4 IBS: 0.13570189837869392
Fold 5 IBS: 0.22836940505288686
[I 2024-04-17 13:47:09,261] Trial 34 finished with value: 0.16122499074111354 and parameters: {'l1_ratio': 0.2644078791453887}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1627357203753366
Fold 2 IBS: 0.15477970825030404
Fold 3 IBS: 0.12481115355937926
Fold 4 IBS: 0.13567704144488965
Fold 5 IBS: 0.22855719323897478
[I 2024-04-17 13:47:09,541] Trial 35 finished with value: 0.16131216337377685 and parameters: {'l1_ratio': 0.3333359983708827}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16287667604107028
Fold 2 IBS: 0.15627681161421825
Fold 3 IBS: 0.12521669755567114
Fold 4 IBS: 0.13553803731477973
Fold 5 IBS: 0.22957916479810433
[I 2024-04-17 13:47:09,878] Trial 36 finished with value: 0.16189747746476874 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1624167220149522
Fold 2 IBS: 0.1538990007869941
Fold 3 IBS: 0.12457785536228161
Fold 4 IBS: 0.22189013082296383
Fold 5 IBS: 0.22799995870250978
[I 2024-04-17 13:47:10,132] Trial 37 finished with value: 0.17815673353794031 and parameters: {'l1_ratio': 0.05074141466052713}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1625671109948539
Fold 2 IBS: 0.15428463413465965
Fold 3 IBS: 0.12465887552277123
Fold 4 IBS: 0.13574381343471972
Fold 5 IBS: 0.22817260007767623
[I 2024-04-17 13:47:10,393] Trial 38 finished with value: 0.16108540683293615 and parameters: {'l1_ratio': 0.15211505537906378}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16262483510393483
Fold 2 IBS: 0.15437675176362411
Fold 3 IBS: 0.12470716412876834
Fold 4 IBS: 0.13571425263191939
Fold 5 IBS: 0.22830751188928805
[I 2024-04-17 13:47:10,674] Trial 39 finished with value: 0.16114610310350694 and parameters: {'l1_ratio': 0.20615221526639127}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16275873346177874
Fold 2 IBS: 0.1552074613599327
Fold 3 IBS: 0.1249181907020528
Fold 4 IBS: 0.13561992455488547
Fold 5 IBS: 0.22876392001863602
[I 2024-04-17 13:47:10,920] Trial 40 finished with value: 0.16145364601945716 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16249940855213016
Fold 2 IBS: 0.1540538224944029
Fold 3 IBS: 0.1246181950480913
Fold 4 IBS: 0.13579704025037934
Fold 5 IBS: 0.2280984169825687
[I 2024-04-17 13:47:11,209] Trial 41 finished with value: 0.16101337666551446 and parameters: {'l1_ratio': 0.09824665512892417}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1624284438306557
Fold 2 IBS: 0.15395448629858494
Fold 3 IBS: 0.12458667103405625
Fold 4 IBS: 0.22178606440536655
Fold 5 IBS: 0.22792956880126133
[I 2024-04-17 13:47:11,501] Trial 42 finished with value: 0.17813704687398496 and parameters: {'l1_ratio': 0.05264706250780881}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16243944477478928
Fold 2 IBS: 0.15401961320401136
Fold 3 IBS: 0.12458113552310285
Fold 4 IBS: 0.13581344149786437
Fold 5 IBS: 0.22800325519992443
[I 2024-04-17 13:47:11,768] Trial 43 finished with value: 0.16097137803993844 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.2133045166811298
Fold 2 IBS: 0.15392581505104802
Fold 3 IBS: 0.12457584924032751
Fold 4 IBS: 0.2228299303209853
Fold 5 IBS: 0.22792968751191164
[I 2024-04-17 13:47:12,006] Trial 44 finished with value: 0.18851315976108046 and parameters: {'l1_ratio': 0.03370261242502054}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16250474074699214
Fold 2 IBS: 0.15408138377882727
Fold 3 IBS: 0.12462936278429024
Fold 4 IBS: 0.13577453368910508
Fold 5 IBS: 0.22811896479292076
[I 2024-04-17 13:47:12,256] Trial 45 finished with value: 0.16102179715842707 and parameters: {'l1_ratio': 0.11586477977261425}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16259629301001194
Fold 2 IBS: 0.15429997646505347
Fold 3 IBS: 0.12468837894565378
Fold 4 IBS: 0.13576538143791408
Fold 5 IBS: 0.22825059563171252
[I 2024-04-17 13:47:12,531] Trial 46 finished with value: 0.16112012509806917 and parameters: {'l1_ratio': 0.1853826892392648}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16267225239277006
Fold 2 IBS: 0.15452795891786142
Fold 3 IBS: 0.12473343551665841
Fold 4 IBS: 0.13571702824243695
Fold 5 IBS: 0.228316416447105
[I 2024-04-17 13:47:12,863] Trial 47 finished with value: 0.16119341830336636 and parameters: {'l1_ratio': 0.23971145636476637}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1624336011318727
Fold 2 IBS: 0.15394733468126465
Fold 3 IBS: 0.12458900421935822
Fold 4 IBS: 0.1358253830211085
Fold 5 IBS: 0.22803837138041186
[I 2024-04-17 13:47:13,266] Trial 48 finished with value: 0.16096673888680318 and parameters: {'l1_ratio': 0.061812111190260595}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.21387373769566956
Fold 2 IBS: 0.22114714949670286
Fold 3 IBS: 0.20431885028438262
Fold 4 IBS: 0.2244484658241761
Fold 5 IBS: 0.21785463997512214
[I 2024-04-17 13:47:13,354] Trial 49 finished with value: 0.2163285686552107 and parameters: {'l1_ratio': 0.005040986123852953}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16276895440999806
Fold 2 IBS: 0.15547175486231826
Fold 3 IBS: 0.1250033798482385

Fold 4 IBS: 0.1356128361089927
Fold 5 IBS: 0.22900989840060168
[I 2024-04-17 13:47:13,559] Trial 50 finished with value: 0.16157336472602984 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1624333373693897
Fold 2 IBS: 0.15394957663637424
Fold 3 IBS: 0.12458936001812733
Fold 4 IBS: 0.13582586609568248
Fold 5 IBS: 0.2280410313774311
[I 2024-04-17 13:47:13,814] Trial 51 finished with value: 0.16096783429940092 and parameters: {'l1_ratio': 0.06190359682979441}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16253247777451776
Fold 2 IBS: 0.1541462203291175
Fold 3 IBS: 0.12463992403596175
Fold 4 IBS: 0.1357894968359305
Fold 5 IBS: 0.22817219180657222
[I 2024-04-17 13:47:14,041] Trial 52 finished with value: 0.16105606215641993 and parameters: {'l1_ratio': 0.12090276396547626}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16241206809075606
Fold 2 IBS: 0.1539383242205832
Fold 3 IBS: 0.12458407575657889
Fold 4 IBS: 0.22181705106658495
Fold 5 IBS: 0.22804662344124357
[I 2024-04-17 13:47:14,248] Trial 53 finished with value: 0.17815962851514933 and parameters: {'l1_ratio': 0.05207923766627566}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1625890094264634
Fold 2 IBS: 0.15426432759851913
Fold 3 IBS: 0.12467693643767416
Fold 4 IBS: 0.13573941290367314
Fold 5 IBS: 0.2282388848907048
[I 2024-04-17 13:47:14,462] Trial 54 finished with value: 0.1611017142514069 and parameters: {'l1_ratio': 0.17054978197059553}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.162538632668513
Fold 2 IBS: 0.15409259160252828
Fold 3 IBS: 0.12463113332267384
Fold 4 IBS: 0.13577690599935105
Fold 5 IBS: 0.22813213472332358
[I 2024-04-17 13:47:14,720] Trial 55 finished with value: 0.16103427966327793 and parameters: {'l1_ratio': 0.11670054053890752}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1628231208933999
Fold 2 IBS: 0.15604000552224997
Fold 3 IBS: 0.12517856633770744
Fold 4 IBS: 0.1355144875067506
Fold 5 IBS: 0.22940472267934928
[I 2024-04-17 13:47:14,941] Trial 56 finished with value: 0.16179218058789144 and parameters: {'l1_ratio': 0.7636926705520951}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16247019699978973
Fold 2 IBS: 0.15400077029233572
Fold 3 IBS: 0.12460414020075547
Fold 4 IBS: 0.13580880141515422
Fold 5 IBS: 0.2280657750137664
[I 2024-04-17 13:47:15,166] Trial 57 finished with value: 0.1609899367843603 and parameters: {'l1_ratio': 0.08139947872514244}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.2133843344340035
Fold 2 IBS: 0.15386313819334427
Fold 3 IBS: 0.12456487171631112
Fold 4 IBS: 0.22305860481586803
Fold 5 IBS: 0.227996970430737
[I 2024-04-17 13:47:15,425] Trial 58 finished with value: 0.1885735839180528 and parameters: {'l1_ratio': 0.029602001630610462}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16258006878810433
Fold 2 IBS: 0.15419244555628708
Fold 3 IBS: 0.12465548106807764
Fold 4 IBS: 0.13576513189697031
Fold 5 IBS: 0.22818288445953025
[I 2024-04-17 13:47:15,634] Trial 59 finished with value: 0.1610752023537939 and parameters: {'l1_ratio': 0.1430939775662408}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.21385260834475814
Fold 2 IBS: 0.2210585163973207
Fold 3 IBS: 0.2042741731087951
Fold 4 IBS: 0.22438882379663644
Fold 5 IBS: 0.21779922763639445
[I 2024-04-17 13:47:15,729] Trial 60 finished with value: 0.21627466985678095 and parameters: {'l1_ratio': 0.006082242166408208}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16245631574303965
Fold 2 IBS: 0.15398532586331024
Fold 3 IBS: 0.12459925777296202
Fold 4 IBS: 0.1358160640315093
Fold 5 IBS: 0.22806059102130796
[I 2024-04-17 13:47:15,933] Trial 61 finished with value: 0.16098351088642582 and parameters: {'l1_ratio': 0.07447039571087796}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.1624565652449014
Fold 2 IBS: 0.15398319028896618
Fold 3 IBS: 0.12459891772300806
Fold 4 IBS: 0.13581560599285436
Fold 5 IBS: 0.22805805779392482
[I 2024-04-17 13:47:16,216] Trial 62 finished with value: 0.16098246740873096 and parameters: {'l1_ratio': 0.07436596259052439}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16250432817714214
Fold 2 IBS: 0.15408533183962317
Fold 3 IBS: 0.12462999015481611
Fold 4 IBS: 0.13577536941248805
Fold 5 IBS: 0.22812360463320847
[I 2024-04-17 13:47:16,396] Trial 63 finished with value: 0.1610237248434556 and parameters: {'l1_ratio': 0.11615799472914044}. Best is trial 30 with value: 0.16096326652500728.
Fold 1 IBS: 0.16242477122354923
Fold 2 IBS: 0.1539219333237547
Fold 3 IBS: 0.12458313991637818
Fold 4 IBS: 0.135827502539996
Fold 5 IBS: 0.22801814652789712
[I 2024-04-17 13:47:16,623] Trial 64 finished with value: 0.16095509870631503 and parameters: {'l1_ratio': 0.05598508620980326}. Best is trial 64 with value: 0.16095509870631503.
Fold 1 IBS: 0.21335497065368217
Fold 2 IBS: 0.15393598806438885
Fold 3 IBS: 0.12457659744901683
Fold 4 IBS: 0.22297454885383222
Fold 5 IBS: 0.22794800033505824
[I 2024-04-17 13:47:16,831] Trial 65 finished with value: 0.18855802107119568 and parameters: {'l1_ratio': 0.03110728303957434}. Best is trial 64 with value: 0.16095509870631503.
Fold 1 IBS: 0.16262312024966066
Fold 2 IBS: 0.15430868215059912
Fold 3 IBS: 0.12468427099866836
Fold 4 IBS: 0.13574923635333774
Fold 5 IBS: 0.22826725351268695
[I 2024-04-17 13:47:17,117] Trial 66 finished with value: 0.16112651265299055 and parameters: {'l1_ratio': 0.17549895890174197}. Best is trial 64 with value: 0.16095509870631503.
Fold 1 IBS: 0.1626887296325823
Fold 2 IBS: 0.15447707055493895
Fold 3 IBS: 0.12473066510046651
Fold 4 IBS: 0.1357069847512184
Fold 5 IBS: 0.22836520091019671
[I 2024-04-17 13:47:17,401] Trial 67 finished with value: 0.1611937301898806 and parameters: {'l1_ratio': 0.23190071796652573}. Best is trial 64 with value: 0.16095509870631503.
Fold 1 IBS: 0.16250409935847865
Fold 2 IBS: 0.15412650596263294
Fold 3 IBS: 0.12461173685559138
Fold 4 IBS: 0.1357877907110543
Fold 5 IBS: 0.22807462966261602
[I 2024-04-17 13:47:17,716] Trial 68 finished with value: 0.16102095251007467 and parameters: {'l1_ratio': 0.09569489249902617}. Best is trial 64 with value: 0.16095509870631503.
Fold 1 IBS: 0.16293787337437837
Fold 2 IBS: 0.15643637320497075
Fold 3 IBS: 0.12529181038834505
Fold 4 IBS: 0.13549788248748215
Fold 5 IBS: 0.22977438085895885
[I 2024-04-17 13:47:17,903] Trial 69 finished with value: 0.16198766406282702 and parameters: {'l1_ratio': 0.9521436965777794}. Best is trial 64 with value: 0.16095509870631503.
Fold 1 IBS: 0.162577469068778
Fold 2 IBS: 0.15421578463978305
Fold 3 IBS: 0.12465931417791762
Fold 4 IBS: 0.13577013553606096
Fold 5 IBS: 0.22821051109363694
[I 2024-04-17 13:47:18,154] Trial 70 finished with value: 0.16108664290323532 and parameters: {'l1_ratio': 0.1452858022745173}. Best is trial 64 with value: 0.16095509870631503.
Fold 1 IBS: 0.1624252478001383
Fold 2 IBS: 0.15397972783087197
Fold 3 IBS: 0.1245907679779213
Fold 4 IBS: 0.13581156460351473
Fold 5 IBS: 0.22796150778734367
[I 2024-04-17 13:47:18,391] Trial 71 finished with value: 0.160953763199958 and parameters: {'l1_ratio': 0.05355583928772211}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.1624055768917992
Fold 2 IBS: 0.153962893365034
Fold 3 IBS: 0.12458412834565254
Fold 4 IBS: 0.22241955986088757
Fold 5 IBS: 0.22796489556506155
[I 2024-04-17 13:47:18,659] Trial 72 finished with value: 0.17826741080568698 and parameters: {'l1_ratio': 0.04110541553069312}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16244651675621796
Fold 2 IBS: 0.15399281766659573
Fold 3 IBS: 0.12459629001199828
Fold 4 IBS: 0.13579879399129724
Fold 5 IBS: 0.22795802774299578
[I 2024-04-17 13:47:18,913] Trial 73 finished with value: 0.160958489233821 and parameters: {'l1_ratio': 0.06371546131251565}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.2139124772677946
Fold 2 IBS: 0.2213095814636946
Fold 3 IBS: 0.20440072000234197
Fold 4 IBS: 0.2245577144651022
Fold 5 IBS: 0.21795625719583137
[I 2024-04-17 13:47:19,030] Trial 74 finished with value: 0.21642735007895295 and parameters: {'l1_ratio': 0.0031363393293553435}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16249209737153683
Fold 2 IBS: 0.15407799903874145

Fold 3 IBS: 0.12461678026567687
Fold 4 IBS: 0.13578865586683128
Fold 5 IBS: 0.2280285692912383
[I 2024-04-17 13:47:19,293] Trial 75 finished with value: 0.16100082036680494 and parameters: {'l1_ratio': 0.08574176873451331}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16252833558230145
Fold 2 IBS: 0.154183024867559
Fold 3 IBS: 0.12464602153595039
Fold 4 IBS: 0.1357958899958188
Fold 5 IBS: 0.2280907143900187
[I 2024-04-17 13:47:19,597] Trial 76 finished with value: 0.1610487972743297 and parameters: {'l1_ratio': 0.12390315666114743}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.2133842635603898
Fold 2 IBS: 0.15386332158249336
Fold 3 IBS: 0.12456490067016217
Fold 4 IBS: 0.22305840203192154
Fold 5 IBS: 0.22799718809217512
[I 2024-04-17 13:47:19,821] Trial 77 finished with value: 0.18857361518742838 and parameters: {'l1_ratio': 0.029605630293830613}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.1626013379903515
Fold 2 IBS: 0.15433295522417576
Fold 3 IBS: 0.12469380660442873
Fold 4 IBS: 0.1357305388935232
Fold 5 IBS: 0.22826536231191533
[I 2024-04-17 13:47:20,055] Trial 78 finished with value: 0.1611248002048789 and parameters: {'l1_ratio': 0.18931197917651812}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16249342578050496
Fold 2 IBS: 0.1541054376816035
Fold 3 IBS: 0.12462667937146249
Fold 4 IBS: 0.135807328623304
Fold 5 IBS: 0.22803125399653568
[I 2024-04-17 13:47:20,373] Trial 79 finished with value: 0.16101282509068213 and parameters: {'l1_ratio': 0.10170288073210698}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16270983901272704
Fold 2 IBS: 0.15456162058641731
Fold 3 IBS: 0.12474698056761832
Fold 4 IBS: 0.13569434160727603
Fold 5 IBS: 0.22842439960382047
[I 2024-04-17 13:47:20,618] Trial 80 finished with value: 0.16122743627557184 and parameters: {'l1_ratio': 0.25720043961303646}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16243570918882802
Fold 2 IBS: 0.15392944252520302
Fold 3 IBS: 0.12458616769459972
Fold 4 IBS: 0.13582098434028
Fold 5 IBS: 0.2280171356502198
[I 2024-04-17 13:47:20,880] Trial 81 finished with value: 0.16095788787982612 and parameters: {'l1_ratio': 0.06109036203570631}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16242101154633723
Fold 2 IBS: 0.15395381532060678
Fold 3 IBS: 0.12458820296684014
Fold 4 IBS: 0.13579800877970813
Fold 5 IBS: 0.22805597066373895
[I 2024-04-17 13:47:21,118] Trial 82 finished with value: 0.16096340185544625 and parameters: {'l1_ratio': 0.05718002403815478}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.2134267503564642
Fold 2 IBS: 0.15388065409950624
Fold 3 IBS: 0.20337167032012649
Fold 4 IBS: 0.22317988224178223
Fold 5 IBS: 0.22802244389968698
[I 2024-04-17 13:47:21,287] Trial 83 finished with value: 0.20437628018351323 and parameters: {'l1_ratio': 0.02743425915945926}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16245054851576443
Fold 2 IBS: 0.1540342396832713
Fold 3 IBS: 0.12458566392618597
Fold 4 IBS: 0.13580854628619443
Fold 5 IBS: 0.22801126973231553
[I 2024-04-17 13:47:21,585] Trial 84 finished with value: 0.16097805362874634 and parameters: {'l1_ratio': 0.06557056096348465}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16257376025465262
Fold 2 IBS: 0.15424922387198733
Fold 3 IBS: 0.1246648686577667
Fold 4 IBS: 0.13577625398401427
Fold 5 IBS: 0.22812775189819154
[I 2024-04-17 13:47:21,854] Trial 85 finished with value: 0.1610783717333225 and parameters: {'l1_ratio': 0.14853004088837785}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.1625176999355928
Fold 2 IBS: 0.15407570060053025
Fold 3 IBS: 0.12462490713295091
Fold 4 IBS: 0.13578844194964973
Fold 5 IBS: 0.2281069491310856
[I 2024-04-17 13:47:22,109] Trial 86 finished with value: 0.16102273974996187 and parameters: {'l1_ratio': 0.10734569666902379}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16243070134511384
Fold 2 IBS: 0.15399565264866225
Fold 3 IBS: 0.12459349208537138
Fold 4 IBS: 0.13581542659998702
Fold 5 IBS: 0.22798250652405752
[I 2024-04-17 13:47:22,369] Trial 87 finished with value: 0.1609635558406384 and parameters: {'l1_ratio': 0.05416878227070927}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.21354119265332194
Fold 2 IBS: 0.21975250738315222
Fold 3 IBS: 0.20361478561686874
Fold 4 IBS: 0.22350629102800187
Fold 5 IBS: 0.22794640134921915
[I 2024-04-17 13:47:22,492] Trial 88 finished with value: 0.2176722356061128 and parameters: {'l1_ratio': 0.021623780210252228}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16243342313386555
Fold 2 IBS: 0.1540008322356178
Fold 3 IBS: 0.12459594024137256
Fold 4 IBS: 0.13580908266797329
Fold 5 IBS: 0.22797951437632674
[I 2024-04-17 13:47:22,731] Trial 89 finished with value: 0.1609637585310312 and parameters: {'l1_ratio': 0.05905305653859047}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.1626622951842908
Fold 2 IBS: 0.15442292454515308
Fold 3 IBS: 0.12471492839093826
Fold 4 IBS: 0.1357243732826806
Fold 5 IBS: 0.2283381937779997
[I 2024-04-17 13:47:22,934] Trial 90 finished with value: 0.16117254303621248 and parameters: {'l1_ratio': 0.21236068339177577}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16242916158468879
Fold 2 IBS: 0.1539488301433267
Fold 3 IBS: 0.12458576029023617
Fold 4 IBS: 0.22179697342100277
Fold 5 IBS: 0.22805908003263195
[I 2024-04-17 13:47:23,177] Trial 91 finished with value: 0.1781639610943773 and parameters: {'l1_ratio': 0.05244711785823956}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.1624799001226744
Fold 2 IBS: 0.15405820142559387
Fold 3 IBS: 0.1246161080904858
Fold 4 IBS: 0.13580936928948328
Fold 5 IBS: 0.22812024633263434
[I 2024-04-17 13:47:23,437] Trial 92 finished with value: 0.16101676505217433 and parameters: {'l1_ratio': 0.09137886474519771}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16255507105535258
Fold 2 IBS: 0.15416884451375745
Fold 3 IBS: 0.12464743592966014
Fold 4 IBS: 0.1357777843719141
Fold 5 IBS: 0.22817800053727838
[I 2024-04-17 13:47:23,683] Trial 93 finished with value: 0.1610654272815925 and parameters: {'l1_ratio': 0.13163155768610282}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16280034459962334
Fold 2 IBS: 0.15571863654015758
Fold 3 IBS: 0.12506613186774063
Fold 4 IBS: 0.13559147672939934
Fold 5 IBS: 0.229111632268145
[I 2024-04-17 13:47:23,845] Trial 94 finished with value: 0.16165764440101318 and parameters: {'l1_ratio': 0.6383625844584513}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16244264183445117
Fold 2 IBS: 0.15402295569531593
Fold 3 IBS: 0.12460133453204028
Fold 4 IBS: 0.13580593297581342
Fold 5 IBS: 0.22799700714444646
[I 2024-04-17 13:47:24,099] Trial 95 finished with value: 0.16097397443641345 and parameters: {'l1_ratio': 0.06506419879202224}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.2135702447168658
Fold 2 IBS: 0.21987450272774206
Fold 3 IBS: 0.20367643245287545
Fold 4 IBS: 0.2235889696671382
Fold 5 IBS: 0.22795974571257843
[I 2024-04-17 13:47:24,224] Trial 96 finished with value: 0.21773397905543995 and parameters: {'l1_ratio': 0.020157457122736963}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.162428766395533
Fold 2 IBS: 0.1539519438846756
Fold 3 IBS: 0.12458626132788035
Fold 4 IBS: 0.2217909766513051
Fold 5 IBS: 0.22806277105848383
[I 2024-04-17 13:47:24,454] Trial 97 finished with value: 0.17816414386357557 and parameters: {'l1_ratio': 0.05255702372632895}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.16278408719966594
Fold 2 IBS: 0.15511236356955152
Fold 3 IBS: 0.12490415615013467
Fold 4 IBS: 0.13565611263601765
Fold 5 IBS: 0.22875140458336457
[I 2024-04-17 13:47:24,676] Trial 98 finished with value: 0.16144162482774688 and parameters: {'l1_ratio': 0.4400719712910535}. Best is trial 71 with value: 0.160953763199958.
Fold 1 IBS: 0.1626045973812013
Fold 2 IBS: 0.15425278998898964
Fold 3 IBS: 0.12466998711753591
Fold 4 IBS: 0.13575867230567668
Fold 5 IBS: 0.22822897257594715
[I 2024-04-17 13:47:24,909] Trial 99 finished with value: 0.16110300387387017 and parameters: {'l1_ratio': 0.1589183911052428}. Best is trial 71 with value: 0.160953763199958.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.160953763199958], datetime_start=datetime.datetime(2024, 4, 17, 13, 47, 18, 157264), datetime_complete=datetime.datetime(2024, 4, 17, 13, 47, 18, 391303), params={'l1_ratio': 0.05355583928772211}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.160953763199958

In [46]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [47]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.787
train_ibs:  0.161

#### Test

In [48]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [49]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.1170295107004102)

test_cindex : 0.617

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.05355583928772211)

test_ibs:  0.247

In [50]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [51]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:47:25,139] A new study created in memory with name: no-name-cd514159-06b8-4a9e-898f-33770b1b14e3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7112676056338029
[I 2024-04-17 13:47:26,797] Trial 0 finished with value: 0.7639407489522982 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7639407489522982.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7018779342723005
[I 2024-04-17 13:47:29,197] Trial 1 finished with value: 0.7844578169847171 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7844578169847171.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.7065727699530516
[I 2024-04-17 13:47:30,375] Trial 2 finished with value: 0.7820722264496974 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7844578169847171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:47:30,764] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7844578169847171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:47:31,362] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7844578169847171.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7206572769953051
[I 2024-04-17 13:47:32,969] Trial 5 finished with value: 0.7942292246563611 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7942292246563611.
Fold 1 C-index: 0.6688311688311688
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7723004694835681
[I 2024-04-17 13:47:34,835] Trial 6 finished with value: 0.7897263897130838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7942292246563611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:47:35,768] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7942292246563611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:47:38,319] Trial 8 finished with value: 0.539906103286385 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7942292246563611.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:47:39,709] Trial 9 finished with value: 0.7793051396558235 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7942292246563611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:47:39,934] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7942292246563611.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7394366197183099
[I 2024-04-17 13:50:19,236] Trial 11 finished with value: 0.7807640649737909 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.4557494463783111, 'max_features': None, 'min_weight_fraction_leaf': 0.018281586236884743, 'warm_start': False}. Best is trial 5 with value: 0.7942292246563611.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 13:50:22,542] Trial 12 finished with value: 0.7984979988121604 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.47265100602672383, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 12 with value: 0.7984979988121604.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7018779342723005
[I 2024-04-17 13:50:25,657] Trial 13 finished with value: 0.7944987781332731 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.4760095384782845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13020722281466507, 'warm_start': False}. Best is trial 12 with value: 0.7984979988121604.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7253521126760564
[I 2024-04-17 13:50:26,890] Trial 14 finished with value: 0.811228519836272 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.4391402204481904, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13719917472199386, 'warm_start': True}. Best is trial 14 with value: 0.811228519836272.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:50:27,970] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.3234055992507959, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18467389142073792, 'warm_start': True}. Best is trial 14 with value: 0.811228519836272.

Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6924882629107981
[I 2024-04-17 13:50:29,063] Trial 16 finished with value: 0.7510797884284428 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.17576991206596454, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0844290597343094, 'warm_start': True}. Best is trial 14 with value: 0.811228519836272.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:50:30,205] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.378960381234881, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20515024926941233, 'warm_start': True}. Best is trial 14 with value: 0.811228519836272.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.6808035714285714
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7362869198312236
Fold 5 C-index: 0.687793427230047
[I 2024-04-17 13:50:31,153] Trial 18 finished with value: 0.699656437377622 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.7823137374876089, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.811228519836272.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:50:31,544] Trial 19 finished with value: 0.8183647662050282 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.5230131583792007, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08330777153463197, 'warm_start': True}. Best is trial 19 with value: 0.8183647662050282.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.744131455399061
[I 2024-04-17 13:50:31,940] Trial 20 finished with value: 0.8127594074794215 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 145, 'oob_score': True, 'max_samples': 0.5363305100948074, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15152733591351075, 'warm_start': True}. Best is trial 19 with value: 0.8183647662050282.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.7394366197183099
[I 2024-04-17 13:50:32,308] Trial 21 finished with value: 0.8116078984795753 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 141, 'oob_score': True, 'max_samples': 0.5332208403528198, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1522304147549408, 'warm_start': True}. Best is trial 19 with value: 0.8183647662050282.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.8700980392156863
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 13:50:32,743] Trial 22 finished with value: 0.7819248475861601 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.5654136228444365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24212863718288316, 'warm_start': True}. Best is trial 19 with value: 0.8183647662050282.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 13:50:33,106] Trial 23 finished with value: 0.8203111817750974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 138, 'oob_score': True, 'max_samples': 0.6723738979117114, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0756164970810112, 'warm_start': True}. Best is trial 23 with value: 0.8203111817750974.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8897058823529411
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.7934272300469484
[I 2024-04-17 13:50:33,241] Trial 24 finished with value: 0.823796809887507 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.680833989937944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06473370576033237, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8946078431372549
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.744131455399061
[I 2024-04-17 13:50:33,371] Trial 25 finished with value: 0.8156362371526027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 14, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06858338705159753, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7488262910798122
[I 2024-04-17 13:50:33,628] Trial 26 finished with value: 0.8190159101453187 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 66, 'oob_score': True, 'max_samples': 0.8482709774413286, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7816901408450704
[I 2024-04-17 13:50:33,938] Trial 27 finished with value: 0.8196281601021095 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.839124645015142, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04810535800309272, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7535211267605634
[I 2024-04-17 13:50:34,044] Trial 28 finished with value: 0.811953814370689 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 15, 'oob_score': True, 'max_samples': 0.9909136035056136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002394613286081433, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6971830985915493
[I 2024-04-17 13:50:34,247] Trial 29 finished with value: 0.8036666701964987 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.7032086343279219, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0500764115931356, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:50:34,743] Trial 30 finished with value: 0.8198259172467509 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.7923805704425285, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18579705931910293, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.

Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7535211267605634
[I 2024-04-17 13:50:35,269] Trial 31 finished with value: 0.8188869501106006 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.8314158504579381, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1894074705194179, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:50:35,613] Trial 32 finished with value: 0.8232875291642451 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.7411057479667147, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10836239136605069, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:50:36,232] Trial 33 finished with value: 0.8171451898965716 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.7529073868972556, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10656676048415722, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 13:50:36,587] Trial 34 finished with value: 0.8028199243238033 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.7020999325113813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23387156044456767, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7769953051643192
[I 2024-04-17 13:50:36,696] Trial 35 finished with value: 0.8164231945067366 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 33, 'oob_score': False, 'max_samples': 0.7763044624380299, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18275399844911377, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7676056338028169
[I 2024-04-17 13:50:37,170] Trial 36 finished with value: 0.8174749332543921 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.6537899790453084, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1083831226147138, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.6688311688311688
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.7676056338028169
[I 2024-04-17 13:50:37,387] Trial 37 finished with value: 0.7895072041604532 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 98, 'oob_score': False, 'max_samples': 0.7284164033466412, 'max_features': None, 'min_weight_fraction_leaf': 0.1664001462600279, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:50:37,979] Trial 38 finished with value: 0.815925792917209 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 163, 'oob_score': True, 'max_samples': 0.810357312668476, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1193696402374883, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7394366197183099
[I 2024-04-17 13:50:38,298] Trial 39 finished with value: 0.8091646945006306 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 17, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.8985386799671641, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2635408988115671, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7018779342723005
[I 2024-04-17 13:50:39,025] Trial 40 finished with value: 0.7973741572837827 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 255, 'oob_score': True, 'max_samples': 0.6085634853344043, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21780798949737265, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7488262910798122
[I 2024-04-17 13:50:39,271] Trial 41 finished with value: 0.8172895867045501 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 81, 'oob_score': True, 'max_samples': 0.8782922199992342, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07176685762108728, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.7676056338028169
[I 2024-04-17 13:50:39,449] Trial 42 finished with value: 0.8142629724056107 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 41, 'oob_score': True, 'max_samples': 0.9417179472466567, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.037654371997938724, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:50:39,776] Trial 43 finished with value: 0.8204514171266004 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.6695348071210157, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08582295344445659, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:50:40,425] Trial 44 finished with value: 0.8232840994953226 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.6800854493531205, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08760028850181989, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.5865800865800865
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 13:50:40,518] Trial 45 finished with value: 0.7256150108303423 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.6555230098085061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08906052763239937, 'warm_start': True}. Best is trial 24 with value: 0.823796809887507.

Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 13:50:41,015] Trial 46 finished with value: 0.7843855104725239 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 90, 'oob_score': False, 'max_samples': 0.6140792212310926, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009196446881453907, 'warm_start': False}. Best is trial 24 with value: 0.823796809887507.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7769953051643192
[I 2024-04-17 13:50:41,374] Trial 47 finished with value: 0.8241402370199445 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.6919949495708789, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1285068269357227, 'warm_start': True}. Best is trial 47 with value: 0.8241402370199445.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6924882629107981
[I 2024-04-17 13:50:42,318] Trial 48 finished with value: 0.7843353979219525 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.7328934312351427, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12701793378831855, 'warm_start': False}. Best is trial 47 with value: 0.8241402370199445.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:50:42,751] Trial 49 finished with value: 0.8209649957893983 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.6882399003565132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02782723807808289, 'warm_start': True}. Best is trial 47 with value: 0.8241402370199445.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:50:43,097] Trial 50 finished with value: 0.8182938336033938 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.7011525185323663, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030676635902573517, 'warm_start': True}. Best is trial 47 with value: 0.8241402370199445.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:50:43,738] Trial 51 finished with value: 0.8264990666601653 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.6296551934195939, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09896664906640082, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7934272300469484
[I 2024-04-17 13:50:44,275] Trial 52 finished with value: 0.8243619899296044 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.5729495249015716, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05882987948052075, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.7535211267605634
[I 2024-04-17 13:50:44,988] Trial 53 finished with value: 0.8147080950242623 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.5807523757017186, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13735776883947876, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:50:45,609] Trial 54 finished with value: 0.8101392465444986 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 167, 'oob_score': True, 'max_samples': 0.5024341909026488, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10179150190099107, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:50:46,188] Trial 55 finished with value: 0.8215059354752128 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 126, 'oob_score': True, 'max_samples': 0.6309286175692076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05991975206243512, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:50:46,730] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.5749187362473557, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.43424909816356316, 'warm_start': False}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7488262910798122
[I 2024-04-17 13:50:47,419] Trial 57 finished with value: 0.8130034130866564 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.6178881276462869, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16603575276052346, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:50:48,709] Trial 58 finished with value: 0.7958286622644325 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.7493270728054753, 'max_features': None, 'min_weight_fraction_leaf': 0.0982398336713016, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7018779342723005
[I 2024-04-17 13:50:49,377] Trial 59 finished with value: 0.8026382652284564 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 201, 'oob_score': True, 'max_samples': 0.42924431328730067, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14769066654189877, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:50:51,069] Trial 60 finished with value: 0.7915724516439099 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.5508151660317097, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12280505817755942, 'warm_start': False}. Best is trial 51 with value: 0.8264990666601653.

Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:50:51,476] Trial 61 finished with value: 0.8196060821936515 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.6333878035320637, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.061027206430973924, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:50:51,857] Trial 62 finished with value: 0.8195865761821999 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 119, 'oob_score': True, 'max_samples': 0.6287976428494042, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06531837735278404, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:50:52,404] Trial 63 finished with value: 0.8162006331974109 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.591625739338884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08655906867764564, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:50:52,767] Trial 64 finished with value: 0.817764435674268 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.7490387729763592, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04947445012675288, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:50:53,375] Trial 65 finished with value: 0.8157669317423075 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.4991479086268497, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03461192720494798, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 13:50:54,070] Trial 66 finished with value: 0.8114427304252875 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.647119762455174, 'max_features': None, 'min_weight_fraction_leaf': 0.07068374214024646, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7629107981220657
[I 2024-04-17 13:50:54,537] Trial 67 finished with value: 0.8193406322885076 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 128, 'oob_score': True, 'max_samples': 0.6888160126097528, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01507472491490712, 'warm_start': True}. Best is trial 51 with value: 0.8264990666601653.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:50:54,858] Trial 68 finished with value: 0.827501377826289 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 53, 'oob_score': True, 'max_samples': 0.7227199672725352, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10754518872974402, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7723004694835681
[I 2024-04-17 13:50:55,106] Trial 69 finished with value: 0.818375340662854 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 52, 'oob_score': True, 'max_samples': 0.7726300856584892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13985940970116384, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:50:55,252] Trial 70 finished with value: 0.8200519859721066 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 33, 'oob_score': False, 'max_samples': 0.7171250777372281, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11680959780552032, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 13:50:55,598] Trial 71 finished with value: 0.8230992072269354 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.8051116441449984, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09769820898654093, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:50:55,935] Trial 72 finished with value: 0.8250992830559021 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.8131403465849452, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1002121123511186, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8799019607843137
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.687793427230047
[I 2024-04-17 13:50:56,210] Trial 73 finished with value: 0.7956658379733034 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 61, 'oob_score': True, 'max_samples': 0.8622901466699457, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3136324910319987, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8799019607843137
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:50:56,366] Trial 74 finished with value: 0.8125417144442503 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.8114335153569149, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11262346576177501, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7535211267605634
[I 2024-04-17 13:50:56,694] Trial 75 finished with value: 0.8186400792103419 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.765303246946707, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1598227810133493, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8102678571428571

Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:50:56,794] Trial 76 finished with value: 0.7726165317623831 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 2, 'oob_score': True, 'max_samples': 0.728452881528101, 'max_features': None, 'min_weight_fraction_leaf': 0.07717773297338491, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:50:57,149] Trial 77 finished with value: 0.8231014996316034 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.6882532669367537, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1282405156063804, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:50:57,379] Trial 78 finished with value: 0.8063557593331827 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 46, 'oob_score': True, 'max_samples': 0.5495913032004546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04260068787857707, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7065727699530516
[I 2024-04-17 13:50:58,470] Trial 79 finished with value: 0.7940935741141948 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 152, 'oob_score': True, 'max_samples': 0.6778492173255701, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09515210850245007, 'warm_start': False}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:50:58,906] Trial 80 finished with value: 0.8216991665464708 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 113, 'oob_score': True, 'max_samples': 0.5947497973463185, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11030120046841957, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7629107981220657
[I 2024-04-17 13:50:59,282] Trial 81 finished with value: 0.824544805442234 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 98, 'oob_score': True, 'max_samples': 0.7118502436657191, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13484301529661624, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7629107981220657
[I 2024-04-17 13:50:59,739] Trial 82 finished with value: 0.8182383760810763 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 142, 'oob_score': True, 'max_samples': 0.7168254680758399, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13977468257772754, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.744131455399061
[I 2024-04-17 13:51:00,043] Trial 83 finished with value: 0.8109329979743076 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.792683176936813, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17283024379149542, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:51:00,318] Trial 84 finished with value: 0.8198643648937557 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 63, 'oob_score': True, 'max_samples': 0.8276166343254929, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07878834208601623, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.744131455399061
[I 2024-04-17 13:51:00,713] Trial 85 finished with value: 0.8152233015525858 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.7343880289580333, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14911840643352892, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7676056338028169
[I 2024-04-17 13:51:01,048] Trial 86 finished with value: 0.8174749332543921 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.65848920592783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05821209225407768, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:51:01,359] Trial 87 finished with value: 0.8219788487122104 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.7025563852359685, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08962957464805468, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.7723004694835681
[I 2024-04-17 13:51:01,532] Trial 88 finished with value: 0.8096867300057028 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.7532884197918288, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12048813903650538, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:51:01,665] Trial 89 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 16, 'oob_score': True, 'max_samples': 0.16405866867269464, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38529641442156126, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7112676056338029
[I 2024-04-17 13:51:02,095] Trial 90 finished with value: 0.80816822273813 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.6514095102169866, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20437142557820703, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.

Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:51:02,439] Trial 91 finished with value: 0.8221211074747409 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 94, 'oob_score': True, 'max_samples': 0.6969164421545264, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12709283659817414, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:51:02,692] Trial 92 finished with value: 0.8229004901608935 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.6771150529499408, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1063180766166534, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7582159624413145
[I 2024-04-17 13:51:03,187] Trial 93 finished with value: 0.8171613070988943 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.78439170006876, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13012559880446267, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.8192488262910798
[I 2024-04-17 13:51:03,430] Trial 94 finished with value: 0.8008244141511447 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 40, 'oob_score': True, 'max_samples': 0.6139961906548315, 'max_features': None, 'min_weight_fraction_leaf': 0.07707142500197284, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:51:03,943] Trial 95 finished with value: 0.8192500730822807 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.7348860054413432, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10005418625517054, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8602941176470589
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 13:51:04,668] Trial 96 finished with value: 0.7851491703668616 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 94, 'oob_score': True, 'max_samples': 0.6716532298074749, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1353659583355501, 'warm_start': False}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7488262910798122
[I 2024-04-17 13:51:05,177] Trial 97 finished with value: 0.8143401301670442 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.6349510031284872, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15625227666751315, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.744131455399061
[I 2024-04-17 13:51:05,488] Trial 98 finished with value: 0.8135479478668077 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.5618380658830533, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06726663619308826, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.

[I 2024-04-17 13:51:05,769] A new study created in memory with name: no-name-92339888-2129-4d00-8e0a-82f72c394f17

Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 13:51:05,761] Trial 99 finished with value: 0.8171218586706956 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.7159479651581833, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11322919556672878, 'warm_start': True}. Best is trial 68 with value: 0.827501377826289.


* Best trial for C-index:
 FrozenTrial(number=68, state=TrialState.COMPLETE, values=[0.827501377826289], datetime_start=datetime.datetime(2024, 4, 17, 13, 50, 54, 544403), datetime_complete=datetime.datetime(2024, 4, 17, 13, 50, 54, 858082), params={'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 53, 'oob_score': True, 'max_samples': 0.7227199672725352, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10754518872974402, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=68, value=None)


* Best Score for C-index:
 0.827501377826289

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1757612068581427
Fold 2 IBS: 0.19303635131530453
Fold 3 IBS: 0.1576192785132537
Fold 4 IBS: 0.14997303978328688
Fold 5 IBS: 0.2132119338573129
[I 2024-04-17 13:51:07,752] Trial 0 finished with value: 0.17792036206546014 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.17792036206546014.
Fold 1 IBS: 0.16946008246215602
Fold 2 IBS: 0.1840365446236086
Fold 3 IBS: 0.16292682143849532
Fold 4 IBS: 0.16236046665755424
Fold 5 IBS: 0.21091640569909917
[I 2024-04-17 13:51:08,249] Trial 1 finished with value: 0.17794006417618266 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.17792036206546014.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-17 13:51:08,605] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.17792036206546014.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-17 13:51:10,019] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.17792036206546014.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-17 13:51:11,084] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.17792036206546014.
Fold 1 IBS: 0.17219117372055262
Fold 2 IBS: 0.16508891085759259
Fold 3 IBS: 0.1452593139216613
Fold 4 IBS: 0.14403777625905323
Fold 5 IBS: 0.20645422125388568
[I 2024-04-17 13:51:12,590] Trial 5 finished with value: 0.16660627920254908 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17781737122981395
Fold 2 IBS: 0.19770463119912987
Fold 3 IBS: 0.15996481637990165
Fold 4 IBS: 0.1627466158385431
Fold 5 IBS: 0.21765067537263796
[I 2024-04-17 13:51:14,050] Trial 6 finished with value: 0.1831768220040053 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.21281012894014736
Fold 2 IBS: 0.2185080875958452
Fold 3 IBS: 0.2003901631995242
Fold 4 IBS: 0.21895899249680384
Fold 5 IBS: 0.21493001577719129
[I 2024-04-17 13:51:15,779] Trial 7 finished with value: 0.2131194776019024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-17 13:51:18,536] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.1700413489564881
Fold 2 IBS: 0.19011143083697996
Fold 3 IBS: 0.1631015241060508
Fold 4 IBS: 0.16364206513318907
Fold 5 IBS: 0.21278927525694658
[I 2024-04-17 13:51:19,114] Trial 9 finished with value: 0.1799371288579309 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-17 13:51:22,295] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17296480485170387
Fold 2 IBS: 0.16708233065176736
Fold 3 IBS: 0.14878575209588776
Fold 4 IBS: 0.14928730333788062
Fold 5 IBS: 0.20625638740640256
[I 2024-04-17 13:51:24,244] Trial 11 finished with value: 0.16887531566872843 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17231415201172084
Fold 2 IBS: 0.1671496713067244
Fold 3 IBS: 0.14793919951411053
Fold 4 IBS: 0.14786235032496128
Fold 5 IBS: 0.20666692400816533
[I 2024-04-17 13:51:25,844] Trial 12 finished with value: 0.1683864594331365 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.7702835685563957, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10911904675719894}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17465515985786692
Fold 2 IBS: 0.1676391300779759
Fold 3 IBS: 0.14398835082336994
Fold 4 IBS: 0.14160982097137098
Fold 5 IBS: 0.2083913732698679
[I 2024-04-17 13:51:27,282] Trial 13 finished with value: 0.16725676700009035 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.9390560748601342, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0903297954919296}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17677351292692217
Fold 2 IBS: 0.16971306285833584
Fold 3 IBS: 0.14669972165384598
Fold 4 IBS: 0.14649351183293982
Fold 5 IBS: 0.2115043910927978
[I 2024-04-17 13:51:28,224] Trial 14 finished with value: 0.17023684007296833 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.9266642747734682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17232599177627478
Fold 2 IBS: 0.18496255431208164
Fold 3 IBS: 0.16129323167259607
Fold 4 IBS: 0.1610943683709469
Fold 5 IBS: 0.20652112076646997
[I 2024-04-17 13:51:29,567] Trial 15 finished with value: 0.1772394533796739 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.9965734283570571, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 5 with value: 0.16660627920254908.

Fold 1 IBS: 0.17472940263785772
Fold 2 IBS: 0.1694187117024534
Fold 3 IBS: 0.14531489845064355
Fold 4 IBS: 0.14533807046253996
Fold 5 IBS: 0.21094571819297459
[I 2024-04-17 13:51:30,550] Trial 16 finished with value: 0.16914936028929384 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8244863604817951, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09668995910437887}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.1721035403859099
Fold 2 IBS: 0.18123739146686044
Fold 3 IBS: 0.16157263164424132
Fold 4 IBS: 0.16254321402581198
Fold 5 IBS: 0.2074423177046641
[I 2024-04-17 13:51:32,222] Trial 17 finished with value: 0.17697981904549756 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16327303877358781}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17536802517145733
Fold 2 IBS: 0.19166560207692504
Fold 3 IBS: 0.16578124096472527
Fold 4 IBS: 0.17260415215302838
Fold 5 IBS: 0.20881630390960645
[I 2024-04-17 13:51:35,091] Trial 18 finished with value: 0.1828470648551485 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.18639745256999626
Fold 2 IBS: 0.16437925673635242
Fold 3 IBS: 0.1368285806874424
Fold 4 IBS: 0.15098301143752646
Fold 5 IBS: 0.22361393954350553
[I 2024-04-17 13:51:35,265] Trial 19 finished with value: 0.17244044819496462 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.2815352098491377, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0014752007295319863}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17438862853275677
Fold 2 IBS: 0.17063786029152023
Fold 3 IBS: 0.14889593876925963
Fold 4 IBS: 0.14723295071338632
Fold 5 IBS: 0.20728558619553236
[I 2024-04-17 13:51:36,256] Trial 20 finished with value: 0.16968819290049109 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.9925562892876347, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14864961680613484}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17375046521077067
Fold 2 IBS: 0.16642921502507427
Fold 3 IBS: 0.14477966429492495
Fold 4 IBS: 0.14100770768737922
Fold 5 IBS: 0.2087211647565258
[I 2024-04-17 13:51:37,923] Trial 21 finished with value: 0.16693764339493497 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.790141466623, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07786459814086755}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.1752093880841524
Fold 2 IBS: 0.16750814636758085
Fold 3 IBS: 0.14348249099688218
Fold 4 IBS: 0.13979240144330643
Fold 5 IBS: 0.21028439026430337
[I 2024-04-17 13:51:39,456] Trial 22 finished with value: 0.16725536343124503 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.8299765323253162, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07438313252492994}. Best is trial 5 with value: 0.16660627920254908.
Fold 1 IBS: 0.17756392096698018
Fold 2 IBS: 0.1638373843744703
Fold 3 IBS: 0.13523888629939027
Fold 4 IBS: 0.13549500903656858
Fold 5 IBS: 0.20820117441447844
[I 2024-04-17 13:51:41,755] Trial 23 finished with value: 0.16406727501837753 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.8134865144757608, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.044499398714530014}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.1731006569810648
Fold 2 IBS: 0.1650458092367454
Fold 3 IBS: 0.14846665099254483
Fold 4 IBS: 0.14812871118570203
Fold 5 IBS: 0.20829988331414848
[I 2024-04-17 13:51:43,830] Trial 24 finished with value: 0.1686083423420411 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.6345619841264796, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05076228838069387}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.1706626805027339
Fold 2 IBS: 0.18336212794977122
Fold 3 IBS: 0.1594598336039505
Fold 4 IBS: 0.16125311580746104
Fold 5 IBS: 0.20861376465626089
[I 2024-04-17 13:51:46,293] Trial 25 finished with value: 0.1766703045040355 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.7713037181074996, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20583275248961533}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.17259866441865895
Fold 2 IBS: 0.17287193901607104
Fold 3 IBS: 0.15422330539268955
Fold 4 IBS: 0.15461625493599182
Fold 5 IBS: 0.20687371973136856
[I 2024-04-17 13:51:48,620] Trial 26 finished with value: 0.172236776698956 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.6805624799876795, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1376002922416853}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.1749915044560668
Fold 2 IBS: 0.163650994795389
Fold 3 IBS: 0.13363469830479935
Fold 4 IBS: 0.1363909268065199
Fold 5 IBS: 0.21245374962943978
[I 2024-04-17 13:51:50,975] Trial 27 finished with value: 0.16422437479844296 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.5850652507393906, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03429775533830964}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.17346995855852687
Fold 2 IBS: 0.1649384610517855
Fold 3 IBS: 0.1449105992056606
Fold 4 IBS: 0.14325120278096948
Fold 5 IBS: 0.20707194399392773
[I 2024-04-17 13:51:53,229] Trial 28 finished with value: 0.16672843311817404 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.5887337168089669, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02713013980424927}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.21397492943896443
Fold 2 IBS: 0.22148116838783852
Fold 3 IBS: 0.2048935401295178
Fold 4 IBS: 0.22461711717675403
Fold 5 IBS: 0.21858319029049303
[I 2024-04-17 13:51:55,724] Trial 29 finished with value: 0.21670998908471356 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.463741832603615, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.17242815640361528
Fold 2 IBS: 0.17189104701874514
Fold 3 IBS: 0.1529064534882093
Fold 4 IBS: 0.15302274731015633
Fold 5 IBS: 0.2072360450266866
[I 2024-04-17 13:51:57,978] Trial 30 finished with value: 0.17149688984948253 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.697959546969956, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031679609431212674}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.17380435784150194
Fold 2 IBS: 0.16510611830212787
Fold 3 IBS: 0.14293839007215145
Fold 4 IBS: 0.143095806534506

Fold 5 IBS: 0.20629952789346637
[I 2024-04-17 13:52:00,268] Trial 31 finished with value: 0.1662488401287507 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 409, 'oob_score': False, 'max_samples': 0.5937734971360611, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.045073432551245296}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.17221494847375315
Fold 2 IBS: 0.16332057162458086
Fold 3 IBS: 0.13924621253579658
Fold 4 IBS: 0.13955671627374916
Fold 5 IBS: 0.20848447341582182
[I 2024-04-17 13:52:02,915] Trial 32 finished with value: 0.16456458446474032 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.5048409346506281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.041946651269943944}. Best is trial 23 with value: 0.16406727501837753.
Fold 1 IBS: 0.1745623497267235
Fold 2 IBS: 0.16440573616437704
Fold 3 IBS: 0.1342278157226142
Fold 4 IBS: 0.13686108419179618
Fold 5 IBS: 0.20760066492644688
[I 2024-04-17 13:52:07,170] Trial 33 finished with value: 0.16353153014639157 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.4887801648969498, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00046034060496186885}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.17466265581756782
Fold 2 IBS: 0.16312500172768038
Fold 3 IBS: 0.13535001501502536
Fold 4 IBS: 0.13699350497333473
Fold 5 IBS: 0.20810574399832504
[I 2024-04-17 13:52:10,173] Trial 34 finished with value: 0.16364738430638665 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.49427627530825324, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.000978958653477871}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.1702695555353552
Fold 2 IBS: 0.1675948088592134
Fold 3 IBS: 0.1470280642011989
Fold 4 IBS: 0.1454741361721188
Fold 5 IBS: 0.2057172214096009
[I 2024-04-17 13:52:13,906] Trial 35 finished with value: 0.16721675723549742 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.33680656313743607, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010082465935464534}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.1739760136119494
Fold 2 IBS: 0.1887246936083781
Fold 3 IBS: 0.1634373913632462
Fold 4 IBS: 0.1692958612945836
Fold 5 IBS: 0.20931301556348877
[I 2024-04-17 13:52:16,481] Trial 36 finished with value: 0.18094939508832925 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.5060704695356878, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16998061577811324}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.17261419437612824
Fold 2 IBS: 0.1824646110978426
Fold 3 IBS: 0.15280132606213886
Fold 4 IBS: 0.1462194607801729
Fold 5 IBS: 0.20430501905299148
[I 2024-04-17 13:52:20,166] Trial 37 finished with value: 0.1716809222738548 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.23019401729836142, 'max_features': None, 'min_weight_fraction_leaf': 0.005401880251169437}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.21396758322061143
Fold 2 IBS: 0.2211952764008762
Fold 3 IBS: 0.20494239588720717
Fold 4 IBS: 0.22469065857682538
Fold 5 IBS: 0.2185776956211647
[I 2024-04-17 13:52:22,069] Trial 38 finished with value: 0.21667472194133697 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.405348775786905, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.1861569316812006
Fold 2 IBS: 0.16948430962477942
Fold 3 IBS: 0.15984750619725976
Fold 4 IBS: 0.14120705841295578
Fold 5 IBS: 0.20528693671324721
[I 2024-04-17 13:52:25,493] Trial 39 finished with value: 0.17239654852588857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 446, 'oob_score': True, 'max_samples': 0.4440027657980192, 'max_features': None, 'min_weight_fraction_leaf': 0.09957812268116864}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.2139836796820501
Fold 2 IBS: 0.22146299859751445
Fold 3 IBS: 0.20483973744319572
Fold 4 IBS: 0.2246654997484141
Fold 5 IBS: 0.21846172991421797
[I 2024-04-17 13:52:34,989] Trial 40 finished with value: 0.21668272907707847 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.5426978990195253, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42173492582961203}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.17226117765912224
Fold 2 IBS: 0.1625676152315982
Fold 3 IBS: 0.1385369274406274
Fold 4 IBS: 0.13901334231570306
Fold 5 IBS: 0.20764226740572767
[I 2024-04-17 13:52:38,327] Trial 41 finished with value: 0.1640042660105557 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.5181596362642569, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04220284209656211}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.17071301219808585
Fold 2 IBS: 0.16574659911505732
Fold 3 IBS: 0.14688041356883985
Fold 4 IBS: 0.14698712399361322
Fold 5 IBS: 0.2068764752109743
[I 2024-04-17 13:52:41,078] Trial 42 finished with value: 0.16744072481731412 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.46978314314039393, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.061073800820265686}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.21397457715045345
Fold 2 IBS: 0.22126895413394354
Fold 3 IBS: 0.2048977528518698
Fold 4 IBS: 0.22462016788888553
Fold 5 IBS: 0.21829769289756365
[I 2024-04-17 13:52:43,339] Trial 43 finished with value: 0.2166118289845432 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.36202851108062717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.1724016095479849
Fold 2 IBS: 0.16340372986870189
Fold 3 IBS: 0.14218684413539234
Fold 4 IBS: 0.1400800442400054
Fold 5 IBS: 0.20844621246963851
[I 2024-04-17 13:52:45,567] Trial 44 finished with value: 0.16530368805234458 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.5872987425934688, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.033701973750637694}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.17041401035113143
Fold 2 IBS: 0.18191960851261757
Fold 3 IBS: 0.1589859902689779
Fold 4 IBS: 0.16224137885943643
Fold 5 IBS: 0.20984199767201017
[I 2024-04-17 13:52:48,473] Trial 45 finished with value: 0.1766805971328347 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.5172890166610269, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12670881953582797}. Best is trial 33 with value: 0.16353153014639157.
Fold 1 IBS: 0.17500479863151178
Fold 2 IBS: 0.1666678046965096
Fold 3 IBS: 0.1307675194330973
Fold 4 IBS: 0.13415754463485957
Fold 5 IBS: 0.2039037379405597
[I 2024-04-17 13:52:50,777] Trial 46 finished with value: 0.16210028106730762 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.7269130301544231, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0016874189679422016}. Best is trial 46 with value: 0.16210028106730762.

Fold 1 IBS: 0.1971354741691935
Fold 2 IBS: 0.16636863415022685
Fold 3 IBS: 0.1692145952249857
Fold 4 IBS: 0.1441551060476205
Fold 5 IBS: 0.21183108033751186
[I 2024-04-17 13:52:53,389] Trial 47 finished with value: 0.17774097798590768 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.7284286912916192, 'max_features': None, 'min_weight_fraction_leaf': 0.007042646978595906}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.173257616030805
Fold 2 IBS: 0.16712747227278846
Fold 3 IBS: 0.15059712575175793
Fold 4 IBS: 0.14859926861378026
Fold 5 IBS: 0.20428399666953267
[I 2024-04-17 13:52:55,771] Trial 48 finished with value: 0.16877309586773287 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.6356303622551829, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06957737393432194}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17230849078433128
Fold 2 IBS: 0.18750676793522889
Fold 3 IBS: 0.16157510113828594
Fold 4 IBS: 0.16407996685308382
Fold 5 IBS: 0.2080960270013975
[I 2024-04-17 13:52:58,696] Trial 49 finished with value: 0.17871327074246549 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.8830858283511519, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1145328278031017}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.18366628399234328
Fold 2 IBS: 0.1981587421911074
Fold 3 IBS: 0.17229055253348163
Fold 4 IBS: 0.18440217464060638
Fold 5 IBS: 0.2081858897164948
[I 2024-04-17 13:53:01,684] Trial 50 finished with value: 0.1893407286148067 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.48297781181574606, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08619734067591672}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17265385422469087
Fold 2 IBS: 0.1634341379490952
Fold 3 IBS: 0.1391011455364774
Fold 4 IBS: 0.13595260649614826
Fold 5 IBS: 0.2091151342647036
[I 2024-04-17 13:53:04,471] Trial 51 finished with value: 0.16405137569422307 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.5587757362402723, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020178838620627998}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17174237899858086
Fold 2 IBS: 0.16276737850406053
Fold 3 IBS: 0.13872411691963604
Fold 4 IBS: 0.1371158529009817
Fold 5 IBS: 0.20863952966848243
[I 2024-04-17 13:53:06,994] Trial 52 finished with value: 0.1637978513983483 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.5524970729311146, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020512048879587415}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17147395061067564
Fold 2 IBS: 0.16336118859391136
Fold 3 IBS: 0.1338846354760037
Fold 4 IBS: 0.13654826863427044
Fold 5 IBS: 0.2063246653816776
[I 2024-04-17 13:53:09,417] Trial 53 finished with value: 0.16231854173930776 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.5611150729457646, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.018357552133448196}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17158903737621597
Fold 2 IBS: 0.16208821011227129
Fold 3 IBS: 0.13910645158690102
Fold 4 IBS: 0.13943159250783577
Fold 5 IBS: 0.20465342559416144
[I 2024-04-17 13:53:11,982] Trial 54 finished with value: 0.16337374343547711 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.4284394266785483, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01980767524190226}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.1709559421666828
Fold 2 IBS: 0.16312991938304533
Fold 3 IBS: 0.14075703987344373
Fold 4 IBS: 0.1389488892289298
Fold 5 IBS: 0.20494312603081877
[I 2024-04-17 13:53:15,367] Trial 55 finished with value: 0.16374698333658408 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.430440673072358, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01970688869186972}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17219252721070455
Fold 2 IBS: 0.1604956507407156
Fold 3 IBS: 0.13853531559837332
Fold 4 IBS: 0.1415279524453452
Fold 5 IBS: 0.20205562740478056
[I 2024-04-17 13:53:18,855] Trial 56 finished with value: 0.16296141467998385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.36900663594693134, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0014199487862695823}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.16931943989130052
Fold 2 IBS: 0.1638205331407707
Fold 3 IBS: 0.1419032936014657
Fold 4 IBS: 0.14484189885613788
Fold 5 IBS: 0.20242546818192816
[I 2024-04-17 13:53:22,355] Trial 57 finished with value: 0.1644621267343206 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.26646127666984304, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0032663682812829726}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.1749525469823034
Fold 2 IBS: 0.18345901894832714
Fold 3 IBS: 0.16310291763149623
Fold 4 IBS: 0.1677106042303233
Fold 5 IBS: 0.20559286351705805
[I 2024-04-17 13:53:27,406] Trial 58 finished with value: 0.17896359026190162 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.21498292601030225, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05892883950767641}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17346159652655874
Fold 2 IBS: 0.16111462211998379
Fold 3 IBS: 0.14084850004552088
Fold 4 IBS: 0.13984582849654412
Fold 5 IBS: 0.20405664560921796
[I 2024-04-17 13:53:31,242] Trial 59 finished with value: 0.1638654385595651 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 226, 'oob_score': True, 'max_samples': 0.36488522986076855, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002725663820059806}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.1699890268262378
Fold 2 IBS: 0.1733136133855083
Fold 3 IBS: 0.15544751601474976
Fold 4 IBS: 0.1561858469979774
Fold 5 IBS: 0.20729476297206306
[I 2024-04-17 13:53:35,129] Trial 60 finished with value: 0.17244615323930726 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.3885706286654244, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0728490896085337}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17102863457129183
Fold 2 IBS: 0.16389989215212042
Fold 3 IBS: 0.13842838407543878
Fold 4 IBS: 0.13899771505032166
Fold 5 IBS: 0.20426259675537112
[I 2024-04-17 13:53:39,657] Trial 61 finished with value: 0.16332344452090877 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.44005142592674895, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023156778457186278}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17053639148154295
Fold 2 IBS: 0.16425334556553842
Fold 3 IBS: 0.14353915362858916
Fold 4 IBS: 0.14388497887622637

Fold 5 IBS: 0.2024415952436482
[I 2024-04-17 13:53:42,968] Trial 62 finished with value: 0.16493109295910902 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.31219984631291253, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022790585175757945}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17181009881095452
Fold 2 IBS: 0.1699080534892515
Fold 3 IBS: 0.15451888340009945
Fold 4 IBS: 0.15244603875471305
Fold 5 IBS: 0.20463195755314145
[I 2024-04-17 13:53:46,003] Trial 63 finished with value: 0.17066300640163198 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.373917735738639, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05547383035537368}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17280736029182792
Fold 2 IBS: 0.163335639159834
Fold 3 IBS: 0.13398784191869542
Fold 4 IBS: 0.13836616580779174
Fold 5 IBS: 0.20244001316491897
[I 2024-04-17 13:53:49,128] Trial 64 finished with value: 0.1621874040686136 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.4194060195757382, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0006770968706593487}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.1708586701308317
Fold 2 IBS: 0.16319689912871801
Fold 3 IBS: 0.14471947253739426
Fold 4 IBS: 0.1384610683809554
Fold 5 IBS: 0.20648643805656985
[I 2024-04-17 13:53:51,241] Trial 65 finished with value: 0.16474450964689386 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.44511562016389633, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030642022247708164}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.1883581654860774
Fold 2 IBS: 0.16577859010127194
Fold 3 IBS: 0.1573966705340573
Fold 4 IBS: 0.1416981888689294
Fold 5 IBS: 0.20266661060025115
[I 2024-04-17 13:53:53,850] Trial 66 finished with value: 0.17117964511811742 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.41280817367618283, 'max_features': None, 'min_weight_fraction_leaf': 0.09609697574559717}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.16850591080304067
Fold 2 IBS: 0.16933954860915457
Fold 3 IBS: 0.1486726860012081
Fold 4 IBS: 0.1491602858863945
Fold 5 IBS: 0.20530997075904114
[I 2024-04-17 13:53:56,376] Trial 67 finished with value: 0.1681976804117678 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.3336984520081442, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0491116187188261}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17106060464967376
Fold 2 IBS: 0.17179177163168408
Fold 3 IBS: 0.15169469842135497
Fold 4 IBS: 0.15247966777112895
Fold 5 IBS: 0.20669451254064297
[I 2024-04-17 13:53:58,442] Trial 68 finished with value: 0.17074425100289695 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.45653364586165796, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07944914978001236}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.1720465595889355
Fold 2 IBS: 0.16625065482633775
Fold 3 IBS: 0.14968762346873157
Fold 4 IBS: 0.14707723560435423
Fold 5 IBS: 0.20066677263972918
[I 2024-04-17 13:54:01,615] Trial 69 finished with value: 0.16714576922561766 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.2884313591012646, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02307304964355896}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.21399120599405605
Fold 2 IBS: 0.2211954299671783
Fold 3 IBS: 0.20496131898817696
Fold 4 IBS: 0.2247265843904145
Fold 5 IBS: 0.21854865070936863
[I 2024-04-17 13:54:05,089] Trial 70 finished with value: 0.2166846380098389 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.4209864966788735, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3130483102127055}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17466576869075623
Fold 2 IBS: 0.16133096959176102
Fold 3 IBS: 0.13479589268400374
Fold 4 IBS: 0.13681847925577634
Fold 5 IBS: 0.20696392631429214
[I 2024-04-17 13:54:09,394] Trial 71 finished with value: 0.16291500730731792 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 329, 'oob_score': False, 'max_samples': 0.49216833010419697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00011395542858928104}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17253186211300037
Fold 2 IBS: 0.16459057065745808
Fold 3 IBS: 0.13677801275116708
Fold 4 IBS: 0.1408347988810959
Fold 5 IBS: 0.2042188815878821
[I 2024-04-17 13:54:14,251] Trial 72 finished with value: 0.1637908251981207 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.47789080456231203, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017209777740524634}. Best is trial 46 with value: 0.16210028106730762.
Fold 1 IBS: 0.17136570009747953
Fold 2 IBS: 0.16508087057285892
Fold 3 IBS: 0.13340671076631166
Fold 4 IBS: 0.13321892478383945
Fold 5 IBS: 0.202437019135789
[I 2024-04-17 13:54:17,842] Trial 73 finished with value: 0.16110184507125572 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.3940770016576495, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0005154226962176161}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17176693869769163
Fold 2 IBS: 0.16339378797719456
Fold 3 IBS: 0.1462953420902186
Fold 4 IBS: 0.14378695498183183
Fold 5 IBS: 0.2046300073607065
[I 2024-04-17 13:54:21,501] Trial 74 finished with value: 0.16597460622152863 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.37407968512510337, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03493959288321994}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.21400759527171764
Fold 2 IBS: 0.22109936713232756
Fold 3 IBS: 0.2050151483154846
Fold 4 IBS: 0.22487720878310943
Fold 5 IBS: 0.21817869366940618
[I 2024-04-17 13:54:24,374] Trial 75 finished with value: 0.2166356026344091 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.33169812261088494, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3727417770181875}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17089986180431296
Fold 2 IBS: 0.16351458349963682
Fold 3 IBS: 0.1476244474836954
Fold 4 IBS: 0.14660507742839773
Fold 5 IBS: 0.2059092379967172
[I 2024-04-17 13:54:27,688] Trial 76 finished with value: 0.16691064164255204 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.39170614603470666, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04849612170633196}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.1713918489791698
Fold 2 IBS: 0.16052016695043744
Fold 3 IBS: 0.13957760003479233
Fold 4 IBS: 0.1384471409965617
Fold 5 IBS: 0.20561305232502408
[I 2024-04-17 13:54:31,001] Trial 77 finished with value: 0.1631099618571971 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.43038556518424426, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01836009939321484}. Best is trial 73 with value: 0.16110184507125572.

Fold 1 IBS: 0.16919228147273832
Fold 2 IBS: 0.17252035375702687
Fold 3 IBS: 0.15545488892248155
Fold 4 IBS: 0.15513587788347408
Fold 5 IBS: 0.20384083862390687
[I 2024-04-17 13:54:33,733] Trial 78 finished with value: 0.17122884813192554 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.3514556475353373, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06420539756634373}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17840279861798333
Fold 2 IBS: 0.19366925370365148
Fold 3 IBS: 0.16628254344058807
Fold 4 IBS: 0.1755191675136859
Fold 5 IBS: 0.20917537027659575
[I 2024-04-17 13:54:36,940] Trial 79 finished with value: 0.1846098267105009 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.6586689721518522, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23707791750201884}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.2180531958803259
Fold 2 IBS: 0.15427016556513748
Fold 3 IBS: 0.14990888855474327
Fold 4 IBS: 0.1341491795865673
Fold 5 IBS: 0.19819395980336904
[I 2024-04-17 13:54:38,567] Trial 80 finished with value: 0.17091507787802862 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.6130329622867392, 'max_features': None, 'min_weight_fraction_leaf': 0.04390595386993183}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17155809467560967
Fold 2 IBS: 0.16213495213078447
Fold 3 IBS: 0.13822200455789457
Fold 4 IBS: 0.13971711553889857
Fold 5 IBS: 0.2034802511854867
[I 2024-04-17 13:54:42,281] Trial 81 finished with value: 0.1630224836177348 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.43745925146164594, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011105194299162324}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17143384182888702
Fold 2 IBS: 0.1609872534015793
Fold 3 IBS: 0.13273026795263337
Fold 4 IBS: 0.1388454640465283
Fold 5 IBS: 0.20315253083812873
[I 2024-04-17 13:54:46,131] Trial 82 finished with value: 0.16142987161355132 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.5269336365083663, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013205633062217587}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17107438419488807
Fold 2 IBS: 0.16371383803115133
Fold 3 IBS: 0.12954782662051026
Fold 4 IBS: 0.1378640727106434
Fold 5 IBS: 0.2036960278820436
[I 2024-04-17 13:54:50,008] Trial 83 finished with value: 0.16117922988784733 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.5267123586095075, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0013447388040423646}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.1745982404095167
Fold 2 IBS: 0.16255255008676622
Fold 3 IBS: 0.12990520217151585
Fold 4 IBS: 0.13831994608777692
Fold 5 IBS: 0.20524100307414922
[I 2024-04-17 13:54:54,160] Trial 84 finished with value: 0.16212338836594498 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'max_samples': 0.5317352538175792, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009848793081479049}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17131536454625887
Fold 2 IBS: 0.16025740054176993
Fold 3 IBS: 0.1386109232294977
Fold 4 IBS: 0.13874644447691517
Fold 5 IBS: 0.20784103887012115
[I 2024-04-17 13:54:57,688] Trial 85 finished with value: 0.16335423433291257 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.5219510464285518, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.037132417716990246}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.1707677063426923
Fold 2 IBS: 0.17319126406040428
Fold 3 IBS: 0.15512987750672488
Fold 4 IBS: 0.15671317758290634
Fold 5 IBS: 0.20783225804406302
[I 2024-04-17 13:55:01,587] Trial 86 finished with value: 0.17272685670735816 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.53132458662168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.001371624458922844}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.1764132137615647
Fold 2 IBS: 0.1667098042104897
Fold 3 IBS: 0.12934097486516283
Fold 4 IBS: 0.13588517761905308
Fold 5 IBS: 0.20712834920683404
[I 2024-04-17 13:55:05,146] Trial 87 finished with value: 0.16309550393262087 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.581976391470536, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01261672022953534}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17383684979392042
Fold 2 IBS: 0.16245593909944078
Fold 3 IBS: 0.1360952782357795
Fold 4 IBS: 0.13585281232580745
Fold 5 IBS: 0.20957667662879248
[I 2024-04-17 13:55:10,319] Trial 88 finished with value: 0.16356351121674811 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 368, 'oob_score': True, 'max_samples': 0.570986496986507, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.033040975858983766}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17789013205139506
Fold 2 IBS: 0.19317087069791136
Fold 3 IBS: 0.1659412567469996
Fold 4 IBS: 0.17468872995145918
Fold 5 IBS: 0.20874368653489095
[I 2024-04-17 13:55:13,919] Trial 89 finished with value: 0.18408693519653124 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.5015652074543766, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18295213200889737}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17291272695969193
Fold 2 IBS: 0.16346393687669775
Fold 3 IBS: 0.14241620510473432
Fold 4 IBS: 0.1404239838549435
Fold 5 IBS: 0.209335354823957
[I 2024-04-17 13:55:18,291] Trial 90 finished with value: 0.16571044152400488 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 381, 'oob_score': False, 'max_samples': 0.6156254448617924, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05497692684985529}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17303392955989214
Fold 2 IBS: 0.1597417745249047
Fold 3 IBS: 0.13483275111739637
Fold 4 IBS: 0.1351644035404971
Fold 5 IBS: 0.20641536289442458
[I 2024-04-17 13:55:22,209] Trial 91 finished with value: 0.16183764432742298 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.4625191200933657, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011294244554922846}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.1722479390856593
Fold 2 IBS: 0.15933784829507983
Fold 3 IBS: 0.13514219749993428
Fold 4 IBS: 0.13535204629624084
Fold 5 IBS: 0.20627913584969468
[I 2024-04-17 13:55:26,099] Trial 92 finished with value: 0.1616718334053218 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.46563691466273716, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0007076809397331841}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17442019698526248
Fold 2 IBS: 0.16239927283478145
Fold 3 IBS: 0.13350099063650855
Fold 4 IBS: 0.13785559759094976

Fold 5 IBS: 0.20635483370375807
[I 2024-04-17 13:55:29,931] Trial 93 finished with value: 0.16290617835025206 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.5422942375084822, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.012802544117543141}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17176456286813024
Fold 2 IBS: 0.16324995065853418
Fold 3 IBS: 0.1379990506096137
Fold 4 IBS: 0.13820954686984363
Fold 5 IBS: 0.20786497976045762
[I 2024-04-17 13:55:33,259] Trial 94 finished with value: 0.16381761815331589 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.538718115810859, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013582457774989606}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17101111168768682
Fold 2 IBS: 0.16064316812490875
Fold 3 IBS: 0.13779251439731222
Fold 4 IBS: 0.138235790316554
Fold 5 IBS: 0.20708988745698848
[I 2024-04-17 13:55:37,062] Trial 95 finished with value: 0.16295449439669002 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.46488542496839014, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03261209587056904}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17277445032967728
Fold 2 IBS: 0.1637010629644639
Fold 3 IBS: 0.13868298045394534
Fold 4 IBS: 0.1377833545342825
Fold 5 IBS: 0.20976510059658218
[I 2024-04-17 13:55:40,339] Trial 96 finished with value: 0.16454138977579022 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.5574573211765218, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.041360118520331994}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17216166304417524
Fold 2 IBS: 0.1668062345545592
Fold 3 IBS: 0.133049602277158
Fold 4 IBS: 0.1363713128505052
Fold 5 IBS: 0.20779045535631105
[I 2024-04-17 13:55:43,018] Trial 97 finished with value: 0.16323585361654175 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 263, 'oob_score': False, 'max_samples': 0.604116703692037, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011815539994301355}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17262509805412066
Fold 2 IBS: 0.16632641471996112
Fold 3 IBS: 0.145536710684095
Fold 4 IBS: 0.1460103378394619
Fold 5 IBS: 0.20745140314300542
[I 2024-04-17 13:55:46,255] Trial 98 finished with value: 0.1675899928881288 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.7212000061868313, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06711783150072304}. Best is trial 73 with value: 0.16110184507125572.
Fold 1 IBS: 0.17246378102851845
Fold 2 IBS: 0.16105412438992733
Fold 3 IBS: 0.13493017498343848
Fold 4 IBS: 0.1392294426488597
Fold 5 IBS: 0.20897902827086495
[I 2024-04-17 13:55:52,533] Trial 99 finished with value: 0.16333131026432177 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'max_samples': 0.5135218655075561, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02930113811631076}. Best is trial 73 with value: 0.16110184507125572.


* Best trial for IBS:
 FrozenTrial(number=73, state=TrialState.COMPLETE, values=[0.16110184507125572], datetime_start=datetime.datetime(2024, 4, 17, 13, 54, 14, 259680), datetime_complete=datetime.datetime(2024, 4, 17, 13, 54, 17, 841462), params={'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.3940770016576495, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0005154226962176161}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=73, value=None)


* Best Score for IBS:
 0.16110184507125572

In [52]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [53]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.828
train_ibs:  0.161

#### Test

In [54]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [55]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=16, max_features='auto', max_leaf_nodes=6,
                     max_samples=0.7227199672725352, min_samples_leaf=9,
                     min_samples_split=3,
                     min_weight_fraction_leaf=0.10754518872974402,
                     n_estimators=53, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.634

RandomSurvivalForest(max_depth=20, max_leaf_nodes=8,
                     max_samples=0.3940770016576495, min_samples_leaf=1,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.0005154226962176161,
                     n_estimators=317, random_state=123)

test_ibs:  0.212

In [56]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [57]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [58]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:55:53,884] A new study created in memory with name: no-name-abbaae04-c027-4d7f-98f6-1a9d4bb2bbc8

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 13:55:55,138] Trial 0 finished with value: 0.8003942147208484 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.8003942147208484.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:58,459] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.8003942147208484.
Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6690140845070423
[I 2024-04-17 13:56:04,851] Trial 2 finished with value: 0.7815574682441089 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.8003942147208484.
Fold 1 C-index: 0.7943722943722944
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 13:56:05,328] Trial 3 finished with value: 0.79148548554578 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.8003942147208484.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:07,621] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.8003942147208484.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:10,343] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.8003942147208484.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:56:12,233] Trial 6 finished with value: 0.8037242254719681 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 13:56:15,980] Trial 7 finished with value: 0.7723844119569738 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6924882629107981
[I 2024-04-17 13:56:16,207] Trial 8 finished with value: 0.7978026547901775 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:56:25,445] Trial 9 finished with value: 0.7786940737818004 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:28,518] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 13:56:29,892] Trial 11 finished with value: 0.786891257459239 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 13:56:31,627] Trial 12 finished with value: 0.8010969013044852 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 13:56:33,182] Trial 13 finished with value: 0.7950411127270403 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:34,455] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:35,384] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 6 with value: 0.8037242254719681.

Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6784037558685446
[I 2024-04-17 13:56:36,867] Trial 16 finished with value: 0.7894942357159722 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6455399061032864
[I 2024-04-17 13:56:38,012] Trial 17 finished with value: 0.7815737891779023 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 13:56:38,531] Trial 18 finished with value: 0.7660569067454207 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 13:56:39,075] Trial 19 finished with value: 0.8023031584552329 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7943722943722944
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 13:56:39,506] Trial 20 finished with value: 0.7882188860730437 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6315809443915289, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6924882629107981
[I 2024-04-17 13:56:39,967] Trial 21 finished with value: 0.8000706477180737 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5714762089757675, 'min_weight_fraction_leaf': 0.022958663817377156}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:56:40,644] Trial 22 finished with value: 0.7985692089198928 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 201, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8891438439916699, 'min_weight_fraction_leaf': 0.08761267626836403}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 13:56:41,678] Trial 23 finished with value: 0.8032548131247831 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.693714188909504, 'min_weight_fraction_leaf': 0.04814654754133644}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6784037558685446
[I 2024-04-17 13:56:42,590] Trial 24 finished with value: 0.7939898083984399 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7182027160168346, 'min_weight_fraction_leaf': 0.11241212838535851}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7018779342723005
[I 2024-04-17 13:56:43,565] Trial 25 finished with value: 0.8007432379425132 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 311, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.48030428590735824, 'min_weight_fraction_leaf': 0.052542863913365906}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 13:56:48,069] Trial 26 finished with value: 0.7695674722424667 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6888988904813458, 'min_weight_fraction_leaf': 0.04762335481390857}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 13:56:48,652] Trial 27 finished with value: 0.7893090276354305 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5982071696653312, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.8602941176470589
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6549295774647887
[I 2024-04-17 13:56:49,377] Trial 28 finished with value: 0.7865114700761259 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 233, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8562851117410581, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 13:56:50,601] Trial 29 finished with value: 0.8000796306301903 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.737037744328822, 'min_weight_fraction_leaf': 0.10386261975214663}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.687793427230047
[I 2024-04-17 13:56:50,972] Trial 30 finished with value: 0.7860715975153251 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 81, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5266816339342503, 'min_weight_fraction_leaf': 0.07555623946953316}. Best is trial 6 with value: 0.8037242254719681.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 13:56:52,414] Trial 31 finished with value: 0.7973768682175864 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.43716218120232875, 'min_weight_fraction_leaf': 0.0011988413006669512}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 13:56:53,614] Trial 32 finished with value: 0.7945944323287589 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 414, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8484058481228222, 'min_weight_fraction_leaf': 0.02744295677203029}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 13:56:54,910] Trial 33 finished with value: 0.7971691682394283 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.527493679418052, 'min_weight_fraction_leaf': 0.03595443892194146}. Best is trial 6 with value: 0.8037242254719681.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:56:56,387] Trial 34 finished with value: 0.809904519231638 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.679103030672201, 'min_weight_fraction_leaf': 0.0702862139906186}. Best is trial 34 with value: 0.809904519231638.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:56:58,561] Trial 35 finished with value: 0.8087605604973962 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6598870395465077, 'min_weight_fraction_leaf': 0.08277503774291324}. Best is trial 34 with value: 0.809904519231638.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.687793427230047
[I 2024-04-17 13:57:03,588] Trial 36 finished with value: 0.7802470841656814 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 347, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7024312244603714, 'min_weight_fraction_leaf': 0.1207593380530316}. Best is trial 34 with value: 0.809904519231638.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 13:57:05,712] Trial 37 finished with value: 0.8041147001029622 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 341, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.614404808547176, 'min_weight_fraction_leaf': 0.08609581856676353}. Best is trial 34 with value: 0.809904519231638.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.687793427230047
[I 2024-04-17 13:57:08,215] Trial 38 finished with value: 0.7952240732351872 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 398, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5943048963617699, 'min_weight_fraction_leaf': 0.08560370351189081}. Best is trial 34 with value: 0.809904519231638.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 13:57:14,536] Trial 39 finished with value: 0.7750551390145517 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5088420932382233, 'min_weight_fraction_leaf': 0.15885224072249213}. Best is trial 34 with value: 0.809904519231638.
Fold 1 C-index: 0.803030303030303
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-17 13:57:17,441] Trial 40 finished with value: 0.786938730864394 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8000462598508886, 'min_weight_fraction_leaf': 0.29917729980916974}. Best is trial 34 with value: 0.809904519231638.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:57:19,534] Trial 41 finished with value: 0.8145358724131155 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 321, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6719110202495086, 'min_weight_fraction_leaf': 0.0658018724000394}. Best is trial 41 with value: 0.8145358724131155.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:57:21,701] Trial 42 finished with value: 0.813409147715554 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 341, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7522022696793795, 'min_weight_fraction_leaf': 0.06917773744182334}. Best is trial 41 with value: 0.8145358724131155.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 13:57:24,010] Trial 43 finished with value: 0.796086917157177 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 341, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.748007608287863, 'min_weight_fraction_leaf': 0.12121009423675572}. Best is trial 41 with value: 0.8145358724131155.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:57:25,926] Trial 44 finished with value: 0.8145772974338279 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6643013488395957, 'min_weight_fraction_leaf': 0.06664885592483487}. Best is trial 44 with value: 0.8145772974338279.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:57:27,776] Trial 45 finished with value: 0.8099459442523506 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 287, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6632737903001757, 'min_weight_fraction_leaf': 0.06235117451420063}. Best is trial 44 with value: 0.8145772974338279.

Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 13:57:29,265] Trial 46 finished with value: 0.7969514891079367 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 231, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7673695282387065, 'min_weight_fraction_leaf': 0.13082099172814932}. Best is trial 44 with value: 0.8145772974338279.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8700980392156863
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 13:57:33,485] Trial 47 finished with value: 0.781713237978379 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 290, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6692895902262289, 'min_weight_fraction_leaf': 0.17072396295712208}. Best is trial 44 with value: 0.8145772974338279.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:57:35,170] Trial 48 finished with value: 0.8175307091426014 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.829008986787267, 'min_weight_fraction_leaf': 0.059628071741119684}. Best is trial 48 with value: 0.8175307091426014.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:57:36,900] Trial 49 finished with value: 0.8207473166579067 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 240, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9458158813535599, 'min_weight_fraction_leaf': 0.05658877285345012}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.7206572769953051
[I 2024-04-17 13:57:38,277] Trial 50 finished with value: 0.8080415648974059 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 198, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9431160500166029, 'min_weight_fraction_leaf': 0.10202266600369568}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:57:40,177] Trial 51 finished with value: 0.8186574338401627 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.832493967533906, 'min_weight_fraction_leaf': 0.021932153584766564}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:57:41,769] Trial 52 finished with value: 0.8196597450062862 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8430431300377264, 'min_weight_fraction_leaf': 0.024134328089030682}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 13:57:43,319] Trial 53 finished with value: 0.8198987498287862 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 243, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9234026890515932, 'min_weight_fraction_leaf': 0.0202277861597837}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 13:57:44,956] Trial 54 finished with value: 0.8197622395284634 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 247, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9219726374206688, 'min_weight_fraction_leaf': 0.02187201681902332}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 13:57:46,540] Trial 55 finished with value: 0.7948889196434501 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 241, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9126042905278795, 'min_weight_fraction_leaf': 0.018866874224968022}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:57:48,296] Trial 56 finished with value: 0.800469062201454 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 257, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8357146577558993, 'min_weight_fraction_leaf': 0.016874566722939854}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 13:57:49,739] Trial 57 finished with value: 0.8102770305921361 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9923425592884548, 'min_weight_fraction_leaf': 0.02113277740467148}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:57:50,955] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 177, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9204951847493408, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 13:57:54,292] Trial 59 finished with value: 0.7659053255656142 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 222, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8770615030986633, 'min_weight_fraction_leaf': 0.04064863052366163}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7987012987012987
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.636150234741784
[I 2024-04-17 13:57:55,890] Trial 60 finished with value: 0.7850181650724763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 251, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9476448172112852, 'min_weight_fraction_leaf': 0.3722051923440325}. Best is trial 49 with value: 0.8207473166579067.

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:57:57,655] Trial 61 finished with value: 0.8121383241460087 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 277, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8190948078406838, 'min_weight_fraction_leaf': 0.05058995327028053}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:57:59,590] Trial 62 finished with value: 0.8139208593127846 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 293, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8668277083443913, 'min_weight_fraction_leaf': 0.014579627748907994}. Best is trial 49 with value: 0.8207473166579067.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7816901408450704
[I 2024-04-17 13:58:00,980] Trial 63 finished with value: 0.823904603130414 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9310466567850909, 'min_weight_fraction_leaf': 0.03445435954159896}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.8700980392156863
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 13:58:02,346] Trial 64 finished with value: 0.7917585477155902 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 16, 'n_estimators': 197, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9627821487475758, 'min_weight_fraction_leaf': 0.040060881336985835}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7206572769953051
[I 2024-04-17 13:58:03,343] Trial 65 finished with value: 0.8111302111729473 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9998441206785411, 'min_weight_fraction_leaf': 0.006498564100188819}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.715962441314554
[I 2024-04-17 13:58:04,425] Trial 66 finished with value: 0.8076720084944787 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 148, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9309257517290298, 'min_weight_fraction_leaf': 0.10199435303010793}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:58:05,678] Trial 67 finished with value: 0.7920567449009134 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9009593230872917, 'min_weight_fraction_leaf': 0.029574006232674976}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7018779342723005
[I 2024-04-17 13:58:07,154] Trial 68 finished with value: 0.7964736244584546 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 215, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8179501094519361, 'min_weight_fraction_leaf': 0.03174442144724798}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:58:09,118] Trial 69 finished with value: 0.7977519310451939 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 266, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8918698919798764, 'min_weight_fraction_leaf': 0.054708476149808546}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7253521126760564
[I 2024-04-17 13:58:10,922] Trial 70 finished with value: 0.8095927331855934 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9696784516551027, 'min_weight_fraction_leaf': 0.002241178756706416}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:58:12,694] Trial 71 finished with value: 0.8194356996919581 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 249, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8591106600277836, 'min_weight_fraction_leaf': 0.05656778845478006}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 13:58:14,398] Trial 72 finished with value: 0.8201379339803798 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 249, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7835834161418749, 'min_weight_fraction_leaf': 0.04364140759525974}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 13:58:16,480] Trial 73 finished with value: 0.8194403846645386 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 306, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.784664104089537, 'min_weight_fraction_leaf': 0.04451600655641251}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:58:18,668] Trial 74 finished with value: 0.822394248668527 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 253, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7898946797403141, 'min_weight_fraction_leaf': 0.038498055916206135}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 13:58:20,486] Trial 75 finished with value: 0.8050624464197582 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 269, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7971981745647765, 'min_weight_fraction_leaf': 0.04101119969937943}. Best is trial 63 with value: 0.823904603130414.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6690140845070423
[I 2024-04-17 13:58:25,046] Trial 76 finished with value: 0.7713246956183728 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 309, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7833983197750771, 'min_weight_fraction_leaf': 0.08192970559783491}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:58:26,633] Trial 77 finished with value: 0.8217893716344866 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8846752999377016, 'min_weight_fraction_leaf': 0.014381559903413034}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6502347417840375
[I 2024-04-17 13:58:27,886] Trial 78 finished with value: 0.7807020809506966 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 169, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9324136142457896, 'min_weight_fraction_leaf': 0.4401997700779695}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.744131455399061
[I 2024-04-17 13:58:29,450] Trial 79 finished with value: 0.803670774903261 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 224, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.012262392327819968}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 13:58:31,197] Trial 80 finished with value: 0.8081826012711119 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 188, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.879665258579424, 'min_weight_fraction_leaf': 0.09647303625041381}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:58:32,998] Trial 81 finished with value: 0.823320528271277 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 253, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9061521728293286, 'min_weight_fraction_leaf': 0.038422125427499065}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:58:34,525] Trial 82 finished with value: 0.8218820439162877 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 210, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9668678444355818, 'min_weight_fraction_leaf': 0.030501296211723566}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:58:36,039] Trial 83 finished with value: 0.8227259257728278 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 213, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9670037749682452, 'min_weight_fraction_leaf': 0.0327519506664784}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:58:37,393] Trial 84 finished with value: 0.8218820439162877 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 203, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9623263969086014, 'min_weight_fraction_leaf': 0.000364441863272405}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.7987012987012987
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 13:58:38,864] Trial 85 finished with value: 0.7814766441674482 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 205, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9627973809036172, 'min_weight_fraction_leaf': 0.25739092010414}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:58:40,066] Trial 86 finished with value: 0.8235140138649992 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 152, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9639063684181275, 'min_weight_fraction_leaf': 0.0019205351920419597}. Best is trial 63 with value: 0.823904603130414.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:58:41,416] Trial 87 finished with value: 0.8276575326073636 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 173, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9798075821263643, 'min_weight_fraction_leaf': 0.004485732268536071}. Best is trial 87 with value: 0.8276575326073636.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 13:58:44,019] Trial 88 finished with value: 0.7708754881553588 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9776622715939088, 'min_weight_fraction_leaf': 0.005071749910510608}. Best is trial 87 with value: 0.8276575326073636.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:58:44,962] Trial 89 finished with value: 0.8205993029069518 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 119, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9991595652754525, 'min_weight_fraction_leaf': 0.0008048587829465422}. Best is trial 87 with value: 0.8276575326073636.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:58:46,006] Trial 90 finished with value: 0.8194547534081948 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 133, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9516672876101435, 'min_weight_fraction_leaf': 0.031803061425384874}. Best is trial 87 with value: 0.8276575326073636.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:58:47,379] Trial 91 finished with value: 0.8243746774630043 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 168, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9771109297909376, 'min_weight_fraction_leaf': 0.03468240161173551}. Best is trial 87 with value: 0.8276575326073636.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 13:58:48,688] Trial 92 finished with value: 0.825488714627166 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 156, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.973440360423963, 'min_weight_fraction_leaf': 0.011373710654083685}. Best is trial 87 with value: 0.8276575326073636.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7394366197183099
[I 2024-04-17 13:58:50,059] Trial 93 finished with value: 0.8143589154571373 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 164, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9622897607333422, 'min_weight_fraction_leaf': 0.0776332883264241}. Best is trial 87 with value: 0.8276575326073636.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:58:51,462] Trial 94 finished with value: 0.8225889631772901 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 186, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9734233801014748, 'min_weight_fraction_leaf': 0.03113897539586619}. Best is trial 87 with value: 0.8276575326073636.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:58:52,885] Trial 95 finished with value: 0.8286327874964311 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 186, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9786700473362971, 'min_weight_fraction_leaf': 0.03145482687545106}. Best is trial 95 with value: 0.8286327874964311.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 13:58:53,698] Trial 96 finished with value: 0.7965520400772832 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 101, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9753271555376999, 'min_weight_fraction_leaf': 0.06916859741383904}. Best is trial 95 with value: 0.8286327874964311.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 13:58:54,992] Trial 97 finished with value: 0.8225162492021557 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 187, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9041907547495653, 'min_weight_fraction_leaf': 0.05049210655528752}. Best is trial 95 with value: 0.8286327874964311.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7488262910798122
[I 2024-04-17 13:58:56,118] Trial 98 finished with value: 0.8161222584383759 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 150, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9085254751107317, 'min_weight_fraction_leaf': 0.05565099354523202}. Best is trial 95 with value: 0.8286327874964311.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8396624472573839

[I 2024-04-17 13:58:57,406] A new study created in memory with name: no-name-7b2ae598-c8d1-4361-89c3-83bbd7db0af9

Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 13:58:57,396] Trial 99 finished with value: 0.825050307769585 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 188, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9345363202117135, 'min_weight_fraction_leaf': 0.030392244851727705}. Best is trial 95 with value: 0.8286327874964311.


* Best trial for C-index:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.8286327874964311], datetime_start=datetime.datetime(2024, 4, 17, 13, 58, 51, 468199), datetime_complete=datetime.datetime(2024, 4, 17, 13, 58, 52, 884518), params={'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 186, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9786700473362971, 'min_weight_fraction_leaf': 0.03145482687545106}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=95, value=None)


* Best Score for C-index:
 0.8286327874964311

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16856943394682772
Fold 2 IBS: 0.18696902309959862
Fold 3 IBS: 0.15784297442649983
Fold 4 IBS: 0.15890198295223276
Fold 5 IBS: 0.22335094881065098
[I 2024-04-17 13:59:01,421] Trial 0 finished with value: 0.17912687264716198 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-17 13:59:07,539] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.18398102181294035
Fold 2 IBS: 0.19738168382771512
Fold 3 IBS: 0.175864889724
Fold 4 IBS: 0.18407766241315393
Fold 5 IBS: 0.216914801727385
[I 2024-04-17 13:59:12,762] Trial 2 finished with value: 0.19164401190103889 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.18724308962473374
Fold 2 IBS: 0.19994281953840837
Fold 3 IBS: 0.17975174839144475
Fold 4 IBS: 0.18964793827918552
Fold 5 IBS: 0.21622086451872133
[I 2024-04-17 13:59:14,495] Trial 3 finished with value: 0.19456129207049874 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-17 13:59:19,212] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-17 13:59:21,675] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.16987200997194205
Fold 2 IBS: 0.18858478395310593
Fold 3 IBS: 0.15922594936203682
Fold 4 IBS: 0.16068805008521167
Fold 5 IBS: 0.2241663182654798
[I 2024-04-17 13:59:26,612] Trial 6 finished with value: 0.18050742232755526 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.17049073993829192
Fold 2 IBS: 0.18746650297752585
Fold 3 IBS: 0.1627083512077915
Fold 4 IBS: 0.16626236389410554
Fold 5 IBS: 0.21964137201869097
[I 2024-04-17 13:59:29,593] Trial 7 finished with value: 0.18131386600728114 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.1910328010831044
Fold 2 IBS: 0.201622576462118
Fold 3 IBS: 0.17987225868615894
Fold 4 IBS: 0.19426296857262199
Fold 5 IBS: 0.21293741460315418
[I 2024-04-17 13:59:30,233] Trial 8 finished with value: 0.1959456038814315 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.19022214179341873
Fold 2 IBS: 0.20700613140410362
Fold 3 IBS: 0.18454016003574458
Fold 4 IBS: 0.19812622861947393
Fold 5 IBS: 0.21541856076559218
[I 2024-04-17 13:59:37,280] Trial 9 finished with value: 0.1990626445236666 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-17 13:59:42,506] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.17643776742537137
Fold 2 IBS: 0.19339167984144662
Fold 3 IBS: 0.16929308525592154
Fold 4 IBS: 0.17676155138329885
Fold 5 IBS: 0.21935324115180105
[I 2024-04-17 13:59:47,414] Trial 11 finished with value: 0.18704746501156788 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.17912687264716198.
Fold 1 IBS: 0.1636467711197972
Fold 2 IBS: 0.18389903726274148
Fold 3 IBS: 0.15031447463723777
Fold 4 IBS: 0.14818286804214428
Fold 5 IBS: 0.2262840696926422
[I 2024-04-17 13:59:53,392] Trial 12 finished with value: 0.17446544415091259 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.1720180226508594
Fold 2 IBS: 0.19466615485271194
Fold 3 IBS: 0.16707164400838603
Fold 4 IBS: 0.17237839946528988
Fold 5 IBS: 0.22085862368680836
[I 2024-04-17 13:59:59,120] Trial 13 finished with value: 0.18539856893281112 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.17294440684404594
Fold 2 IBS: 0.19609428194345413
Fold 3 IBS: 0.1689063567746027
Fold 4 IBS: 0.17378151300440325
Fold 5 IBS: 0.22091314338794477
[I 2024-04-17 14:00:03,617] Trial 14 finished with value: 0.18652794039089016 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.17446544415091259.

Fold 1 IBS: 0.17396935489267823
Fold 2 IBS: 0.1945926773741061
Fold 3 IBS: 0.16796433696179078
Fold 4 IBS: 0.17271937628063858
Fold 5 IBS: 0.22150186052142384
[I 2024-04-17 14:00:06,963] Trial 15 finished with value: 0.18614952120612752 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.19802766762520618
Fold 2 IBS: 0.21164957045051908
Fold 3 IBS: 0.1924782030535108
Fold 4 IBS: 0.2115300259883924
Fold 5 IBS: 0.21431860266176206
[I 2024-04-17 14:00:12,987] Trial 16 finished with value: 0.2056008139558781 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.17236487485570462
Fold 2 IBS: 0.22620597730302258
Fold 3 IBS: 0.16432794015004007
Fold 4 IBS: 0.159920354255507
Fold 5 IBS: 0.23908951663204941
[I 2024-04-17 14:00:16,599] Trial 17 finished with value: 0.19238173263926472 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-17 14:00:18,434] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.17268040093520562
Fold 2 IBS: 0.19554094421095838
Fold 3 IBS: 0.1673158999144127
Fold 4 IBS: 0.1722386387267873
Fold 5 IBS: 0.22195071461372923
[I 2024-04-17 14:00:22,958] Trial 19 finished with value: 0.18594531968021863 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.20213397316843795
Fold 2 IBS: 0.20938349369100334
Fold 3 IBS: 0.17427253610712223
Fold 4 IBS: 0.20229538785139312
Fold 5 IBS: 0.21652761531191628
[I 2024-04-17 14:00:23,252] Trial 20 finished with value: 0.20092260122597455 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.16962582282327726
Fold 2 IBS: 0.18934464983594845
Fold 3 IBS: 0.15883187536424154
Fold 4 IBS: 0.16055071247789324
Fold 5 IBS: 0.22422223073314027
[I 2024-04-17 14:00:28,356] Trial 21 finished with value: 0.18051505824690015 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.16801534370613
Fold 2 IBS: 0.18911683295967036
Fold 3 IBS: 0.16060698894747055
Fold 4 IBS: 0.1613083116566513
Fold 5 IBS: 0.22373906700531332
[I 2024-04-17 14:00:33,911] Trial 22 finished with value: 0.1805573088550471 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.16739300574109645
Fold 2 IBS: 0.18663060146311125
Fold 3 IBS: 0.15684384902143042
Fold 4 IBS: 0.15847838797429228
Fold 5 IBS: 0.22473307941247808
[I 2024-04-17 14:00:38,488] Trial 23 finished with value: 0.1788157847224817 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.16872441904333413
Fold 2 IBS: 0.18772494054202227
Fold 3 IBS: 0.15861928684154347
Fold 4 IBS: 0.15948848679063596
Fold 5 IBS: 0.22311432469003586
[I 2024-04-17 14:00:42,624] Trial 24 finished with value: 0.17953429158151435 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.17478111922628423
Fold 2 IBS: 0.19030211077292386
Fold 3 IBS: 0.16678780855144104
Fold 4 IBS: 0.17081698049522695
Fold 5 IBS: 0.21835782374814464
[I 2024-04-17 14:00:46,313] Trial 25 finished with value: 0.18420916855880415 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.17157869592318226
Fold 2 IBS: 0.19519577681278205
Fold 3 IBS: 0.16636403688049525
Fold 4 IBS: 0.17135100056206065
Fold 5 IBS: 0.2216450292373035
[I 2024-04-17 14:00:52,815] Trial 26 finished with value: 0.18522690788316476 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8454924050883471, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.1730609344609621
Fold 2 IBS: 0.1954362857180107
Fold 3 IBS: 0.1693764158430473
Fold 4 IBS: 0.17551298158277004
Fold 5 IBS: 0.21966542071429349
[I 2024-04-17 14:00:55,460] Trial 27 finished with value: 0.18661040766381673 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.17217120266751867
Fold 2 IBS: 0.23249137354728278
Fold 3 IBS: 0.16596757082136332
Fold 4 IBS: 0.1615591660108797
Fold 5 IBS: 0.23662306497442726
[I 2024-04-17 14:01:00,993] Trial 28 finished with value: 0.19376247560429433 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.10561943508937117}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.17559290299607086
Fold 2 IBS: 0.19703983608043646
Fold 3 IBS: 0.1706332186218874
Fold 4 IBS: 0.18216544936342413
Fold 5 IBS: 0.21354986011390825
[I 2024-04-17 14:01:07,369] Trial 29 finished with value: 0.18779625343514544 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.17446544415091259.

Fold 1 IBS: 0.17403611604271424
Fold 2 IBS: 0.19528122214997157
Fold 3 IBS: 0.1682737691725757
Fold 4 IBS: 0.17431224647317028
Fold 5 IBS: 0.22003391698754424
[I 2024-04-17 14:01:13,298] Trial 30 finished with value: 0.18638745416519523 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.16740215580950432
Fold 2 IBS: 0.1870998484969457
Fold 3 IBS: 0.1565756547463698
Fold 4 IBS: 0.15710585664080282
Fold 5 IBS: 0.22435467702622547
[I 2024-04-17 14:01:18,280] Trial 31 finished with value: 0.17850763854396962 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7359152304070016, 'min_weight_fraction_leaf': 0.08655997300539783}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.1680123301590812
Fold 2 IBS: 0.18773001411874127
Fold 3 IBS: 0.15769285782904416
Fold 4 IBS: 0.15950623840043734
Fold 5 IBS: 0.2239919924058126
[I 2024-04-17 14:01:23,398] Trial 32 finished with value: 0.1793866865826233 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.618283894727248, 'min_weight_fraction_leaf': 0.07716716290582956}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.18290169452146857
Fold 2 IBS: 0.19736509584007372
Fold 3 IBS: 0.17646302174955117
Fold 4 IBS: 0.18506889131205886
Fold 5 IBS: 0.21567493374424895
[I 2024-04-17 14:01:28,517] Trial 33 finished with value: 0.19149472743348026 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8125920153130402, 'min_weight_fraction_leaf': 0.12995854366525855}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.161716169901359
Fold 2 IBS: 0.1841530299078216
Fold 3 IBS: 0.15037702759094967
Fold 4 IBS: 0.14962405541298707
Fold 5 IBS: 0.22678545349572005
[I 2024-04-17 14:01:32,674] Trial 34 finished with value: 0.1745311472617675 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6862833758870215, 'min_weight_fraction_leaf': 0.03963928663346105}. Best is trial 12 with value: 0.17446544415091259.
Fold 1 IBS: 0.16022373550040409
Fold 2 IBS: 0.1817101807735328
Fold 3 IBS: 0.14592477414478683
Fold 4 IBS: 0.1459997719990437
Fold 5 IBS: 0.2253315847558946
[I 2024-04-17 14:01:36,883] Trial 35 finished with value: 0.1718380094347324 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6699891298567331, 'min_weight_fraction_leaf': 0.035087014488190155}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.1604395097650441
Fold 2 IBS: 0.17830803151949925
Fold 3 IBS: 0.149377930048239
Fold 4 IBS: 0.14725258131252936
Fold 5 IBS: 0.22675106039456996
[I 2024-04-17 14:01:39,916] Trial 36 finished with value: 0.17242582260797631 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 222, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7119928375141668, 'min_weight_fraction_leaf': 0.03598599955769185}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.16026084824592926
Fold 2 IBS: 0.18303475406523495
Fold 3 IBS: 0.15255315875154685
Fold 4 IBS: 0.15518589363947208
Fold 5 IBS: 0.22708949124390349
[I 2024-04-17 14:01:42,769] Trial 37 finished with value: 0.17562482918921735 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 209, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5201827001456041, 'min_weight_fraction_leaf': 0.030440421568832744}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.16259492609122517
Fold 2 IBS: 0.18537140423955145
Fold 3 IBS: 0.15418260085176774
Fold 4 IBS: 0.15442823714504303
Fold 5 IBS: 0.22602616265200612
[I 2024-04-17 14:01:45,667] Trial 38 finished with value: 0.17652066619591872 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 174, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6896630776765292, 'min_weight_fraction_leaf': 0.055105941879107515}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.17717938978623596
Fold 2 IBS: 0.1907430910766764
Fold 3 IBS: 0.171998817354182
Fold 4 IBS: 0.17893297698520133
Fold 5 IBS: 0.21581955817462592
[I 2024-04-17 14:01:48,624] Trial 39 finished with value: 0.18693476667538433 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 134, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.410386003197307, 'min_weight_fraction_leaf': 0.03239655244521619}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.17425698191992273
Fold 2 IBS: 0.195008179737701
Fold 3 IBS: 0.1673125238406885
Fold 4 IBS: 0.17180053619736718
Fold 5 IBS: 0.22032470291156772
[I 2024-04-17 14:01:53,733] Trial 40 finished with value: 0.1857405849214494 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 290, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.582361238397278, 'min_weight_fraction_leaf': 0.11804226902106194}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.15740358509223892
Fold 2 IBS: 0.1807668301766173
Fold 3 IBS: 0.1508037095092436
Fold 4 IBS: 0.15138972624303204
Fold 5 IBS: 0.22415267694529045
[I 2024-04-17 14:01:56,828] Trial 41 finished with value: 0.17290330559328443 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 227, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4986002280250411, 'min_weight_fraction_leaf': 0.0038112810882329137}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.15570131803033851
Fold 2 IBS: 0.18162440913797098
Fold 3 IBS: 0.1480824299119151
Fold 4 IBS: 0.14999218919670532
Fold 5 IBS: 0.22466819495096546
[I 2024-04-17 14:02:00,374] Trial 42 finished with value: 0.17201370824557907 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 231, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.444674248871581, 'min_weight_fraction_leaf': 0.0017515297839367158}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.1596352425922571
Fold 2 IBS: 0.17974519817167137
Fold 3 IBS: 0.14804370860920082
Fold 4 IBS: 0.14849287683463816
Fold 5 IBS: 0.22335149562755854
[I 2024-04-17 14:02:04,056] Trial 43 finished with value: 0.1718537043670652 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 234, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.32905528972204146, 'min_weight_fraction_leaf': 0.007759295188642418}. Best is trial 35 with value: 0.1718380094347324.
Fold 1 IBS: 0.17534317651379994
Fold 2 IBS: 0.18737267416628617
Fold 3 IBS: 0.16491809898466944
Fold 4 IBS: 0.17262114069762136
Fold 5 IBS: 0.2137112018165079
[I 2024-04-17 14:02:09,820] Trial 44 finished with value: 0.18279325843577696 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 237, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.2920922356649062, 'min_weight_fraction_leaf': 0.02139099888296111}. Best is trial 35 with value: 0.1718380094347324.

Fold 1 IBS: 0.1576705560383145
Fold 2 IBS: 0.1822547945562819
Fold 3 IBS: 0.145232345938588
Fold 4 IBS: 0.14600743348144415
Fold 5 IBS: 0.225516129704015
[I 2024-04-17 14:02:15,643] Trial 45 finished with value: 0.17133625194372873 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 234, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.43514597742187, 'min_weight_fraction_leaf': 0.002921383171058025}. Best is trial 45 with value: 0.17133625194372873.
Fold 1 IBS: 0.16543939753834064
Fold 2 IBS: 0.18388164982951516
Fold 3 IBS: 0.15627011252742087
Fold 4 IBS: 0.15694020536835582
Fold 5 IBS: 0.2276949726422081
[I 2024-04-17 14:02:19,603] Trial 46 finished with value: 0.17804526758116812 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 175, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4288876101939958, 'min_weight_fraction_leaf': 0.05348147888161767}. Best is trial 45 with value: 0.17133625194372873.
Fold 1 IBS: 0.17089619335177136
Fold 2 IBS: 0.19059124014111198
Fold 3 IBS: 0.16331995574560276
Fold 4 IBS: 0.16508919620703472
Fold 5 IBS: 0.2234269842314075
[I 2024-04-17 14:02:25,190] Trial 47 finished with value: 0.18266471393538566 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 266, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.3596018571227857, 'min_weight_fraction_leaf': 0.05842399755408602}. Best is trial 45 with value: 0.17133625194372873.
Fold 1 IBS: 0.16932160043842867
Fold 2 IBS: 0.18667139126433194
Fold 3 IBS: 0.16108697298208588
Fold 4 IBS: 0.1621156589944646
Fold 5 IBS: 0.22344340288861478
[I 2024-04-17 14:02:30,415] Trial 48 finished with value: 0.18052780531358517 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 187, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.23437322737219127, 'min_weight_fraction_leaf': 0.02415705336411941}. Best is trial 45 with value: 0.17133625194372873.
Fold 1 IBS: 0.2139379179196569
Fold 2 IBS: 0.22092593759292176
Fold 3 IBS: 0.204933221944477
Fold 4 IBS: 0.22470266584254844
Fold 5 IBS: 0.21829680176475608
[I 2024-04-17 14:02:33,997] Trial 49 finished with value: 0.216559309012872 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 139, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.28037436744612876, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 45 with value: 0.17133625194372873.
Fold 1 IBS: 0.2140187082002053
Fold 2 IBS: 0.221467401771937
Fold 3 IBS: 0.20485784691468575
Fold 4 IBS: 0.22477307691968645
Fold 5 IBS: 0.21854823193545075
[I 2024-04-17 14:02:38,527] Trial 50 finished with value: 0.21673305314839308 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 244, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5413850252306419, 'min_weight_fraction_leaf': 0.3176441381502019}. Best is trial 45 with value: 0.17133625194372873.
Fold 1 IBS: 0.1586819094608343
Fold 2 IBS: 0.17928392759963163
Fold 3 IBS: 0.1474081187186357
Fold 4 IBS: 0.14679589245605537
Fold 5 IBS: 0.22360373656762608
[I 2024-04-17 14:02:42,552] Trial 51 finished with value: 0.17115471696055662 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 223, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4608866493822255, 'min_weight_fraction_leaf': 0.0006000321707642147}. Best is trial 51 with value: 0.17115471696055662.
Fold 1 IBS: 0.16417013837655364
Fold 2 IBS: 0.18633812413465095
Fold 3 IBS: 0.15423893149735662
Fold 4 IBS: 0.15346212482699192
Fold 5 IBS: 0.2256979223629148
[I 2024-04-17 14:02:47,705] Trial 52 finished with value: 0.1767814482396936 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 271, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3653796651771336, 'min_weight_fraction_leaf': 0.019157826110156446}. Best is trial 51 with value: 0.17115471696055662.
Fold 1 IBS: 0.16890087721327507
Fold 2 IBS: 0.18954128478791646
Fold 3 IBS: 0.15967599717083925
Fold 4 IBS: 0.16375757042784006
Fold 5 IBS: 0.22418790664950541
[I 2024-04-17 14:02:51,492] Trial 53 finished with value: 0.18121272724987522 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 237, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.471007225556923, 'min_weight_fraction_leaf': 0.06726125391606544}. Best is trial 51 with value: 0.17115471696055662.
Fold 1 IBS: 0.1570736595162063
Fold 2 IBS: 0.17895220517871332
Fold 3 IBS: 0.1434156649100424
Fold 4 IBS: 0.14378895758730792
Fold 5 IBS: 0.2236231073292102
[I 2024-04-17 14:02:56,461] Trial 54 finished with value: 0.16937071890429603 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 221, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.43930869651952953, 'min_weight_fraction_leaf': 0.004435376496863014}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1756210259214143
Fold 2 IBS: 0.19280296171285669
Fold 3 IBS: 0.16799457285524239
Fold 4 IBS: 0.17556062040975973
Fold 5 IBS: 0.21684422779674645
[I 2024-04-17 14:03:02,812] Trial 55 finished with value: 0.18576468173920388 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 158, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.45075354713551197, 'min_weight_fraction_leaf': 0.005080454620147434}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.17749913987893162
Fold 2 IBS: 0.1989066402639834
Fold 3 IBS: 0.1711749599448904
Fold 4 IBS: 0.17760407844731094
Fold 5 IBS: 0.2188931751478681
[I 2024-04-17 14:03:07,882] Trial 56 finished with value: 0.1888155987365969 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 274, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4128783247845903, 'min_weight_fraction_leaf': 0.017989556610790772}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1668911831030968
Fold 2 IBS: 0.18539744357932805
Fold 3 IBS: 0.1416052320661665
Fold 4 IBS: 0.14135701229878125
Fold 5 IBS: 0.23248102684215421
[I 2024-04-17 14:03:13,775] Trial 57 finished with value: 0.17354637957790536 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 320, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3364468862792985, 'min_weight_fraction_leaf': 0.004869344666887538}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.17388708269667758
Fold 2 IBS: 0.192320724939328
Fold 3 IBS: 0.16837488384652236
Fold 4 IBS: 0.1744907876386643
Fold 5 IBS: 0.2190633815893359
[I 2024-04-17 14:03:17,542] Trial 58 finished with value: 0.18562737214210562 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 195, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.04864689604834348}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.21400286341070587
Fold 2 IBS: 0.2214051793428304
Fold 3 IBS: 0.20457043653432208
Fold 4 IBS: 0.2247108285225116
Fold 5 IBS: 0.21856682695513113
[I 2024-04-17 14:03:20,622] Trial 59 finished with value: 0.21665122695310018 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 104, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.44175083566271006, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 54 with value: 0.16937071890429603.

Fold 1 IBS: 0.18119331875762684
Fold 2 IBS: 0.19945961417160082
Fold 3 IBS: 0.17386579559292806
Fold 4 IBS: 0.18335508271677708
Fold 5 IBS: 0.21758328735458493
[I 2024-04-17 14:03:25,316] Trial 60 finished with value: 0.19109141971870353 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 248, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.19892992997964112, 'min_weight_fraction_leaf': 0.06728588768996817}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1614351110786523
Fold 2 IBS: 0.1826286159456077
Fold 3 IBS: 0.1514993289026967
Fold 4 IBS: 0.15264281381011963
Fold 5 IBS: 0.2249499445361135
[I 2024-04-17 14:03:29,652] Trial 61 finished with value: 0.17463116285463795 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 222, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3848273798295146, 'min_weight_fraction_leaf': 0.03461748003513793}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.15970131878187188
Fold 2 IBS: 0.1770928780746495
Fold 3 IBS: 0.15141919786654354
Fold 4 IBS: 0.1539830278919923
Fold 5 IBS: 0.22486938204435655
[I 2024-04-17 14:03:33,770] Trial 62 finished with value: 0.17341316093188275 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 215, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.30926761860374113, 'min_weight_fraction_leaf': 0.017893860627421532}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.15988548416341497
Fold 2 IBS: 0.18319150265187367
Fold 3 IBS: 0.14610214649277317
Fold 4 IBS: 0.1473045811237037
Fold 5 IBS: 0.22322926604367263
[I 2024-04-17 14:03:38,118] Trial 63 finished with value: 0.17194259609508764 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 256, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.39403389452783044, 'min_weight_fraction_leaf': 0.00011308682224195343}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.15866611029641053
Fold 2 IBS: 0.1812673067058855
Fold 3 IBS: 0.14818373976060015
Fold 4 IBS: 0.14799807675337617
Fold 5 IBS: 0.22510439017854594
[I 2024-04-17 14:03:42,563] Trial 64 finished with value: 0.1722439247389637 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 256, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.47426863088045057, 'min_weight_fraction_leaf': 0.0015194447737984862}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1761525549749534
Fold 2 IBS: 0.1960217249536224
Fold 3 IBS: 0.16981029144425067
Fold 4 IBS: 0.1764286381673275
Fold 5 IBS: 0.2193785238239107
[I 2024-04-17 14:03:47,933] Trial 65 finished with value: 0.18755834667281296 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 285, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.39776825726493326, 'min_weight_fraction_leaf': 0.10305051503887361}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.2139770072236192
Fold 2 IBS: 0.22117996496277922
Fold 3 IBS: 0.2050138827985368
Fold 4 IBS: 0.2248079566468109
Fold 5 IBS: 0.21829337757073755
[I 2024-04-17 14:03:53,163] Trial 66 finished with value: 0.21665443784049673 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.32895593463805156, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16071679156134494
Fold 2 IBS: 0.18112711685526584
Fold 3 IBS: 0.14588095929545838
Fold 4 IBS: 0.14531488727338002
Fold 5 IBS: 0.22690851339036647
[I 2024-04-17 14:03:58,264] Trial 67 finished with value: 0.1719896536751631 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 313, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.45573378133306947, 'min_weight_fraction_leaf': 0.0005794542994115985}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16855430075286465
Fold 2 IBS: 0.18913542002397835
Fold 3 IBS: 0.16066960428679994
Fold 4 IBS: 0.16122350503648086
Fold 5 IBS: 0.22535641128903622
[I 2024-04-17 14:04:03,861] Trial 68 finished with value: 0.180987848277832 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 301, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.35822869031202215, 'min_weight_fraction_leaf': 0.046981834511900696}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16821045492969092
Fold 2 IBS: 0.19015719654719315
Fold 3 IBS: 0.13781298140915937
Fold 4 IBS: 0.14188402001754485
Fold 5 IBS: 0.2370406817073609
[I 2024-04-17 14:04:11,485] Trial 69 finished with value: 0.17502106692218983 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 314, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.603041439020981, 'min_weight_fraction_leaf': 0.07080354903023808}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1766273263225313
Fold 2 IBS: 0.1951624805913385
Fold 3 IBS: 0.16971662395559436
Fold 4 IBS: 0.17717988303621285
Fold 5 IBS: 0.21935104271402206
[I 2024-04-17 14:04:17,669] Trial 70 finished with value: 0.1876074713239398 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 193, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5645419966141069, 'min_weight_fraction_leaf': 0.15556754145439744}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.15657128623127223
Fold 2 IBS: 0.18176825118022955
Fold 3 IBS: 0.14371006744632417
Fold 4 IBS: 0.1451451096221523
Fold 5 IBS: 0.22578684682578762
[I 2024-04-17 14:04:24,499] Trial 71 finished with value: 0.17059631226115318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 255, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.43423140707545976, 'min_weight_fraction_leaf': 0.017280441853106725}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.15713550147131722
Fold 2 IBS: 0.17792417273643385
Fold 3 IBS: 0.14385266756334575
Fold 4 IBS: 0.14433004288372198
Fold 5 IBS: 0.22682300966178548
[I 2024-04-17 14:04:32,030] Trial 72 finished with value: 0.17001307886332084 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 255, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5094462524625463, 'min_weight_fraction_leaf': 0.023991840943401916}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.15825507859687765
Fold 2 IBS: 0.18069455850795596
Fold 3 IBS: 0.1459521173082861
Fold 4 IBS: 0.14662065493285606
Fold 5 IBS: 0.22451417787785313
[I 2024-04-17 14:04:37,570] Trial 73 finished with value: 0.17120731744476578 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 254, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4221304717899444, 'min_weight_fraction_leaf': 0.022409416065902063}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1571217320878166
Fold 2 IBS: 0.17601463130078307
Fold 3 IBS: 0.14227056447648578
Fold 4 IBS: 0.14368180605140848
Fold 5 IBS: 0.22834549880610386
[I 2024-04-17 14:04:42,310] Trial 74 finished with value: 0.16948684654451956 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 207, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5265592912951441, 'min_weight_fraction_leaf': 0.026801251316310854}. Best is trial 54 with value: 0.16937071890429603.

Fold 1 IBS: 0.1710934246390583
Fold 2 IBS: 0.18514706849496712
Fold 3 IBS: 0.15982746349670793
Fold 4 IBS: 0.16688100680245713
Fold 5 IBS: 0.21734234000579852
[I 2024-04-17 14:04:47,052] Trial 75 finished with value: 0.1800582606877978 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 203, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5118766388173772, 'min_weight_fraction_leaf': 0.028141334637192594}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16515141877161646
Fold 2 IBS: 0.1850313180620979
Fold 3 IBS: 0.15552022048760814
Fold 4 IBS: 0.15702862487164565
Fold 5 IBS: 0.22563306053778293
[I 2024-04-17 14:04:53,540] Trial 76 finished with value: 0.17767292854615024 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 280, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4800834218004426, 'min_weight_fraction_leaf': 0.04615622799452371}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.172311702727504
Fold 2 IBS: 0.19118169929847786
Fold 3 IBS: 0.16380366914013272
Fold 4 IBS: 0.1690488486396908
Fold 5 IBS: 0.2214705595804748
[I 2024-04-17 14:04:58,341] Trial 77 finished with value: 0.18356329587725606 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 181, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5252690729078053, 'min_weight_fraction_leaf': 0.09299908730083525}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16704860548872905
Fold 2 IBS: 0.18585463470136035
Fold 3 IBS: 0.1577839122575479
Fold 4 IBS: 0.16326551470749695
Fold 5 IBS: 0.21871688646577497
[I 2024-04-17 14:05:04,897] Trial 78 finished with value: 0.17853391072418184 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.4262372505863887, 'min_weight_fraction_leaf': 0.02108822621632133}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16712386860515394
Fold 2 IBS: 0.18690110991860076
Fold 3 IBS: 0.15697039859795714
Fold 4 IBS: 0.1594638883772324
Fold 5 IBS: 0.22423464902013623
[I 2024-04-17 14:05:10,599] Trial 79 finished with value: 0.1789387829038161 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 250, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6216748405848975, 'min_weight_fraction_leaf': 0.08042034148637302}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16255467707321392
Fold 2 IBS: 0.18211201469351684
Fold 3 IBS: 0.15664523484701875
Fold 4 IBS: 0.15773832094933993
Fold 5 IBS: 0.22286401662042987
[I 2024-04-17 14:05:14,664] Trial 80 finished with value: 0.17638285283670388 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 158, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5577069146466593, 'min_weight_fraction_leaf': 0.03642123076921129}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.15920578550571532
Fold 2 IBS: 0.17937097285419346
Fold 3 IBS: 0.14397054247369936
Fold 4 IBS: 0.14412012457952092
Fold 5 IBS: 0.22480059530899682
[I 2024-04-17 14:05:20,041] Trial 81 finished with value: 0.17029360414442518 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 214, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.49103783272982476, 'min_weight_fraction_leaf': 0.01628287285332668}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16614156754196152
Fold 2 IBS: 0.18607208161588204
Fold 3 IBS: 0.1553154997568706
Fold 4 IBS: 0.1571120023376597
Fold 5 IBS: 0.22578573983077094
[I 2024-04-17 14:05:25,033] Trial 82 finished with value: 0.178085378216629 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.49287139718296463, 'min_weight_fraction_leaf': 0.060295180051271574}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.18587790615177993
Fold 2 IBS: 0.20500194428680799
Fold 3 IBS: 0.1796146607326236
Fold 4 IBS: 0.1935849189094178
Fold 5 IBS: 0.21508812538088962
[I 2024-04-17 14:05:30,145] Trial 83 finished with value: 0.1958335110923038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 204, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5199701804971207, 'min_weight_fraction_leaf': 0.2113346050152473}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.17785789025639606
Fold 2 IBS: 0.20251578816253016
Fold 3 IBS: 0.17286110349465206
Fold 4 IBS: 0.18344043016008588
Fold 5 IBS: 0.21795420921712502
[I 2024-04-17 14:05:36,274] Trial 84 finished with value: 0.19092588425815785 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4624302032555415, 'min_weight_fraction_leaf': 0.01646303165885393}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.21400410805961104
Fold 2 IBS: 0.22117819751741874
Fold 3 IBS: 0.20497581014106028
Fold 4 IBS: 0.22468677837739337
Fold 5 IBS: 0.21869865343461573
[I 2024-04-17 14:05:41,009] Trial 85 finished with value: 0.21670870950601984 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 230, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4282394019437027, 'min_weight_fraction_leaf': 0.265925538442723}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16071024362117145
Fold 2 IBS: 0.18471736220407672
Fold 3 IBS: 0.1504354861086477
Fold 4 IBS: 0.1514709739556419
Fold 5 IBS: 0.22478603247060064
[I 2024-04-17 14:05:46,531] Trial 86 finished with value: 0.1744240196720277 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 294, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4895043098895196, 'min_weight_fraction_leaf': 0.03965212135834947}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1687580313110033
Fold 2 IBS: 0.18549022368210885
Fold 3 IBS: 0.15707028594891886
Fold 4 IBS: 0.15976062530348215
Fold 5 IBS: 0.2253667962971966
[I 2024-04-17 14:05:51,845] Trial 87 finished with value: 0.17928919250854197 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 218, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6553104524047875, 'min_weight_fraction_leaf': 0.02681186628043718}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16236071194789264
Fold 2 IBS: 0.1813207369100043
Fold 3 IBS: 0.14776651231790208
Fold 4 IBS: 0.1479346216665247
Fold 5 IBS: 0.22681051329990973
[I 2024-04-17 14:05:56,045] Trial 88 finished with value: 0.1732386192284467 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.585334887436042, 'min_weight_fraction_leaf': 0.014036703997877856}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16447768650038186
Fold 2 IBS: 0.1847610812300238
Fold 3 IBS: 0.1553464129628715
Fold 4 IBS: 0.1563238391665899
Fold 5 IBS: 0.2246118744952478
[I 2024-04-17 14:06:02,873] Trial 89 finished with value: 0.17710417887102295 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 273, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.541108451024334, 'min_weight_fraction_leaf': 0.05628265498133405}. Best is trial 54 with value: 0.16937071890429603.

Fold 1 IBS: 0.16516760895709928
Fold 2 IBS: 0.1844083930646581
Fold 3 IBS: 0.13378241933973636
Fold 4 IBS: 0.13815322880559427
Fold 5 IBS: 0.22955692785142726
[I 2024-04-17 14:06:09,452] Trial 90 finished with value: 0.17021371560370308 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 262, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.41453164831674366, 'min_weight_fraction_leaf': 0.029911077163684654}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1653205855276024
Fold 2 IBS: 0.18394175946551414
Fold 3 IBS: 0.1340975511411521
Fold 4 IBS: 0.13821860324428945
Fold 5 IBS: 0.22996106804044042
[I 2024-04-17 14:06:14,325] Trial 91 finished with value: 0.1703079134837997 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 257, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.41475250564025906, 'min_weight_fraction_leaf': 0.02994828493486766}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16548487128391925
Fold 2 IBS: 0.18497829562138823
Fold 3 IBS: 0.13403283883099112
Fold 4 IBS: 0.13816862277127342
Fold 5 IBS: 0.23016259605133418
[I 2024-04-17 14:06:21,734] Trial 92 finished with value: 0.17056544491178122 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 252, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4117713093724468, 'min_weight_fraction_leaf': 0.028803204516531695}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16606208019547974
Fold 2 IBS: 0.1876116909729342
Fold 3 IBS: 0.1387623878028608
Fold 4 IBS: 0.14463556113172196
Fold 5 IBS: 0.23908835585583157
[I 2024-04-17 14:06:27,159] Trial 93 finished with value: 0.17523201519176562 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 260, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.41169639729378993, 'min_weight_fraction_leaf': 0.04779942003683858}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16601289672485028
Fold 2 IBS: 0.18544680840366548
Fold 3 IBS: 0.13306686604517948
Fold 4 IBS: 0.13761116541991564
Fold 5 IBS: 0.2337899914499903
[I 2024-04-17 14:06:32,285] Trial 94 finished with value: 0.17118554560872026 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 245, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.36965773572536564, 'min_weight_fraction_leaf': 0.0282218182589962}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16887946951207555
Fold 2 IBS: 0.2143267065847675
Fold 3 IBS: 0.163220249141914
Fold 4 IBS: 0.1604815893349145
Fold 5 IBS: 0.2290649139830795
[I 2024-04-17 14:06:37,044] Trial 95 finished with value: 0.18719458571135023 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3660552592148366, 'min_weight_fraction_leaf': 0.11832275507008035}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.21371331342196517
Fold 2 IBS: 0.22131342210580932
Fold 3 IBS: 0.2047559754208684
Fold 4 IBS: 0.22430652752200614
Fold 5 IBS: 0.21830660590584794
[I 2024-04-17 14:06:40,840] Trial 96 finished with value: 0.21647916887529944 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 18, 'n_estimators': 202, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.37814380207349346, 'min_weight_fraction_leaf': 0.07544415070739649}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.16671886020567317
Fold 2 IBS: 0.17957743518975508
Fold 3 IBS: 0.13676971752508751
Fold 4 IBS: 0.13920237111956682
Fold 5 IBS: 0.23163959040669913
[I 2024-04-17 14:06:45,278] Trial 97 finished with value: 0.17078159488935635 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 225, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3425323929283193, 'min_weight_fraction_leaf': 0.030926139256762367}. Best is trial 54 with value: 0.16937071890429603.
Fold 1 IBS: 0.1749025367214369
Fold 2 IBS: 0.17364877396693615
Fold 3 IBS: 0.12560917994631432
Fold 4 IBS: 0.13475158589919223
Fold 5 IBS: 0.22471910887869176
[I 2024-04-17 14:06:49,462] Trial 98 finished with value: 0.16672623708251427 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 194, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4593899319291545, 'min_weight_fraction_leaf': 0.013192089384711253}. Best is trial 98 with value: 0.16672623708251427.
Fold 1 IBS: 0.16354268782925596
Fold 2 IBS: 0.21081728959155946
Fold 3 IBS: 0.16164184615918084
Fold 4 IBS: 0.1566097601295279
Fold 5 IBS: 0.23619915288131313
[I 2024-04-17 14:06:52,857] Trial 99 finished with value: 0.18576214731816745 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 190, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3515258787478331, 'min_weight_fraction_leaf': 0.08849856459972993}. Best is trial 98 with value: 0.16672623708251427.


* Best trial for IBS:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.16672623708251427], datetime_start=datetime.datetime(2024, 4, 17, 14, 6, 45, 284160), datetime_complete=datetime.datetime(2024, 4, 17, 14, 6, 49, 461483), params={'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 194, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4593899319291545, 'min_weight_fraction_leaf': 0.013192089384711253}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for IBS:
 0.16672623708251427

In [59]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.829
train_ibs:  0.167

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=18, max_features=None, max_leaf_nodes=11,
                   max_samples=0.9786700473362971, min_samples_leaf=2,
                   min_samples_split=13,
                   min_weight_fraction_leaf=0.03145482687545106,
                   n_estimators=186, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.62

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=13,
                   max_samples=0.4593899319291545, min_samples_leaf=1,
                   min_weight_fraction_leaf=0.013192089384711253,
                   n_estimators=194, random_state=123)

IBS: 0.244

In [63]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [64]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:06:54,752] A new study created in memory with name: no-name-7beded0d-f3fc-4494-9c7f-3d9a4a841612

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:07:31,434] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:07:59,208] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:08:21,211] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:09:04,798] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:09:19,982] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:09:23,797] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:10:01,058] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:10:12,692] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:10:14,031] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 14:11:49,480] Trial 9 finished with value: 0.7591992996245486 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 14:14:17,094] Trial 10 finished with value: 0.6989250862300543 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:17:04,014] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 14:19:10,663] Trial 12 finished with value: 0.7461534891108423 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:20:17,285] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:22:01,521] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:23:22,925] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:24:14,888] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:26:03,647] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:28:34,210] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:28:41,228] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:29:38,083] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 14:31:30,408] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6525821596244131
[I 2024-04-17 14:33:17,887] Trial 22 finished with value: 0.7412410929055004 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:34:48,653] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:36:05,834] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:36:52,710] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 14:38:29,198] Trial 26 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:40:12,829] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:41:32,608] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:42:28,009] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:43:32,980] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 14:45:38,246] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:47:43,940] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:49:11,519] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:50:59,801] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:51:23,281] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:53:16,087] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:53:19,671] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:54:02,102] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:55:04,007] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:56:39,633] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-17 14:56:40,051] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6502347417840375
[I 2024-04-17 14:56:50,471] Trial 42 finished with value: 0.7338182267185549 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:01,723] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:28,315] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:40,599] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:57:51,417] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:58:34,998] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:58:53,474] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:59:45,571] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:59:50,331] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 14:59:51,109] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:59:51,832] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 15:00:01,761] Trial 53 finished with value: 0.7568108385471565 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:00:11,181] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:00:13,265] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:02:47,059] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:02:56,542] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:03:12,155] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:05:07,993] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:05:49,055] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:05:52,654] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 15:06:11,150] Trial 62 finished with value: 0.6997689680865944 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:06:33,161] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.13592280861310782, 'n_estimators': 192, 'criterion': 'squared_error', 'ccp_alpha': 0.733686110808502, 'min_weight_fraction_leaf': 0.25062495105887606, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.9944542811487016, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:06:50,526] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9187783486953396, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 178, 'criterion': 'squared_error', 'ccp_alpha': 0.36688086798361713, 'min_weight_fraction_leaf': 0.35183901814733526, 'max_features': 'auto', 'min_impurity_decrease': 3.299702263155327e-07, 'validation_fraction': 0.9264223190540628, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 15:07:00,675] Trial 65 finished with value: 0.7018786727279446 and parameters: {'subsample': 0.9664785962080902, 'learning_rate': 0.011722172098720455, 'dropout_rate': 0.1011352011272833, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.002720474374027445, 'min_weight_fraction_leaf': 0.3770484241588561, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8800483891911463, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:07:32,542] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.885696821597521, 'learning_rate': 0.016950546740898867, 'dropout_rate': 0.10421110317491636, 'n_estimators': 225, 'criterion': 'squared_error', 'ccp_alpha': 0.8254786252963416, 'min_weight_fraction_leaf': 0.45906723804378347, 'max_features': 'auto', 'min_impurity_decrease': 0.0001571311880544454, 'validation_fraction': 0.8763260736370284, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7591992996245486.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 15:07:40,380] Trial 67 finished with value: 0.7652702698852926 and parameters: {'subsample': 0.9449634937948884, 'learning_rate': 0.022450060078644873, 'dropout_rate': 0.4308859881762669, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.04366182843696066, 'min_weight_fraction_leaf': 0.4203837252588317, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002929228884372661, 'validation_fraction': 0.6847776431749146, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 67 with value: 0.7652702698852926.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:07:48,150] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8508914266547543, 'learning_rate': 0.0271877376773079, 'dropout_rate': 0.4587925300849697, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4064170808897855, 'min_weight_fraction_leaf': 0.42082481983216546, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003862592715164256, 'validation_fraction': 0.6927602784856939, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 67 with value: 0.7652702698852926.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:07:54,122] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.8117437406527579, 'learning_rate': 0.021732361644044403, 'dropout_rate': 0.32707285953985127, 'n_estimators': 101, 'criterion': 'squared_error', 'ccp_alpha': 2.165381857742337, 'min_weight_fraction_leaf': 0.4008202205161851, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003807366321009408, 'validation_fraction': 0.4814297515359772, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 67 with value: 0.7652702698852926.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:01,121] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.9588179877977443, 'learning_rate': 0.03404571509920987, 'dropout_rate': 0.5164505989784269, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 1.1547936717217182, 'min_weight_fraction_leaf': 0.23609717988742163, 'max_features': 'sqrt', 'min_impurity_decrease': 9.903776966049311e-05, 'validation_fraction': 0.6007139278650676, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 67 with value: 0.7652702698852926.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6596244131455399
[I 2024-04-17 15:08:06,499] Trial 71 finished with value: 0.763314938651517 and parameters: {'subsample': 0.9998058628904551, 'learning_rate': 0.012217196514323809, 'dropout_rate': 0.272889788803047, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.37665810495618246, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0007202807121114636, 'validation_fraction': 0.7901595950688891, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 67 with value: 0.7652702698852926.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:11,028] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9044139888705314, 'learning_rate': 0.012179198274788102, 'dropout_rate': 0.4337945478119803, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 0.2919408922724437, 'min_weight_fraction_leaf': 0.3583073377101208, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000654957772418829, 'validation_fraction': 0.6255625028149949, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 67 with value: 0.7652702698852926.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:21,223] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9648647232705697, 'learning_rate': 0.018544888734491664, 'dropout_rate': 0.3840392496719551, 'n_estimators': 145, 'criterion': 'squared_error', 'ccp_alpha': 0.7317858789979383, 'min_weight_fraction_leaf': 0.33547968716778687, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012138641204268545, 'validation_fraction': 0.7472232153782647, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 67 with value: 0.7652702698852926.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:25,260] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.9372578852362602, 'learning_rate': 0.013894133166299519, 'dropout_rate': 0.27304995305013646, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2685355623284117, 'min_weight_fraction_leaf': 0.4794532356771624, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0015770193056312545, 'validation_fraction': 0.6862699083190502, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 67 with value: 0.7652702698852926.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.8946078431372549
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.687793427230047
[I 2024-04-17 15:08:26,869] Trial 75 finished with value: 0.7993613365985303 and parameters: {'subsample': 0.6001028949487068, 'learning_rate': 0.023239756862861477, 'dropout_rate': 0.6757649295445344, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.008819927083844869, 'min_weight_fraction_leaf': 0.1942611713172168, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0021237516252394237, 'validation_fraction': 0.7847712019774569, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:28,117] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5878712745727869, 'learning_rate': 0.022147062407290335, 'dropout_rate': 0.6243222457264906, 'n_estimators': 41, 'criterion': 'squared_error', 'ccp_alpha': 0.6031429897420305, 'min_weight_fraction_leaf': 0.2068351704428001, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0035277422265958588, 'validation_fraction': 0.7993048924737626, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:29,906] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5357913465602108, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.758978120963316, 'n_estimators': 59, 'criterion': 'squared_error', 'ccp_alpha': 0.9646030158291333, 'min_weight_fraction_leaf': 0.18921739871886467, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002999937798485588, 'validation_fraction': 0.7387915108714895, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:31,359] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.6708593402641205, 'learning_rate': 0.04479053769496956, 'dropout_rate': 0.638335760687531, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 1.406985156632589, 'min_weight_fraction_leaf': 0.22324854378798265, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01123762072699069, 'validation_fraction': 0.6870714509747361, 'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:32,819] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.48483411726905057, 'learning_rate': 0.024257161323518392, 'dropout_rate': 0.8479916513561038, 'n_estimators': 59, 'criterion': 'friedman_mse', 'ccp_alpha': 1.812067956922833, 'min_weight_fraction_leaf': 0.16909333970802584, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7749694068106482, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 9}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:37,774] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6431481526757131, 'learning_rate': 0.009039793267160097, 'dropout_rate': 0.684566586558272, 'n_estimators': 112, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.18502266407543982, 'max_features': None, 'min_impurity_decrease': 0.0020012217758738067, 'validation_fraction': 0.8312616498046783, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 15:08:46,707] Trial 81 finished with value: 0.7707388914535976 and parameters: {'subsample': 0.9039357395720827, 'learning_rate': 0.016412003133033586, 'dropout_rate': 0.235339636468323, 'n_estimators': 122, 'criterion': 'squared_error', 'ccp_alpha': 0.02521776434594261, 'min_weight_fraction_leaf': 0.43294529918678526, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005704051848755918, 'validation_fraction': 0.8571795971165943, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:08:56,216] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.6137454684751019, 'learning_rate': 0.015676364815988084, 'dropout_rate': 0.5603615855034783, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.2451713250089625, 'min_weight_fraction_leaf': 0.1521377130243636, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005515193402134184, 'validation_fraction': 0.8566748455657475, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:09:02,670] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9027681881288449, 'learning_rate': 0.01822534426227402, 'dropout_rate': 0.23612530486703057, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 0.6434011455925561, 'min_weight_fraction_leaf': 0.4535984691770081, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012304179362636906, 'validation_fraction': 0.7995996886618921, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:10:11,626] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.19323478605220312, 'learning_rate': 0.027444520178208, 'dropout_rate': 0.6818395627907664, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.4701678092057134, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012453998142192364, 'validation_fraction': 0.7122301629842086, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.7993613365985303.

Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6971830985915493
[I 2024-04-17 15:10:12,947] Trial 85 finished with value: 0.7763791455779057 and parameters: {'subsample': 0.7371540479848577, 'learning_rate': 0.03342214021657085, 'dropout_rate': 0.2995405522798756, 'n_estimators': 29, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.4252299956617621, 'max_features': 1, 'min_impurity_decrease': 0.0002644011718832551, 'validation_fraction': 0.5539761240279264, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:10:14,685] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5884601342315053, 'learning_rate': 0.040138798831481366, 'dropout_rate': 0.30893486797722186, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.47555134849711456, 'min_weight_fraction_leaf': 0.4364165414676263, 'max_features': 1, 'min_impurity_decrease': 7.875370120501562e-05, 'validation_fraction': 0.5578771254458135, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:10:15,818] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7385740014789494, 'learning_rate': 0.0312585002522818, 'dropout_rate': 0.34702434797629267, 'n_estimators': 28, 'criterion': 'squared_error', 'ccp_alpha': 0.2573732802753831, 'min_weight_fraction_leaf': 0.42552427194253917, 'max_features': 1, 'min_impurity_decrease': 0.00046483208476230805, 'validation_fraction': 0.5194095572435395, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:10:18,967] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.8144964035305952, 'learning_rate': 0.01892201466815226, 'dropout_rate': 0.26657671560049273, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.1132554775232983, 'min_weight_fraction_leaf': 0.40413170006799326, 'max_features': 1, 'min_impurity_decrease': 0.0002424717222698867, 'validation_fraction': 0.5645759290645115, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:11:58,153] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.6891977708878514, 'learning_rate': 0.0224547626143628, 'dropout_rate': 0.2836120574219838, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.6289674109876843, 'min_weight_fraction_leaf': 0.27088299579805813, 'max_features': 1, 'min_impurity_decrease': 0.000303780768720358, 'validation_fraction': 0.6355737074700468, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:12:01,916] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.8640340113061721, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.32536772451946044, 'n_estimators': 76, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8512083959536265, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 0.1, 'min_impurity_decrease': 0.0007297148480119136, 'validation_fraction': 0.6732774756210603, 'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 15:12:13,804] Trial 91 finished with value: 0.7572345555995782 and parameters: {'subsample': 0.940543807018674, 'learning_rate': 0.009567024476933025, 'dropout_rate': 0.22710075500504756, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03760721937190585, 'min_weight_fraction_leaf': 0.4178541230198032, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009910717111428719, 'validation_fraction': 0.9197960790172954, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:12:21,019] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.924651475781888, 'learning_rate': 0.010356392157077806, 'dropout_rate': 0.2232733649777798, 'n_estimators': 104, 'criterion': 'squared_error', 'ccp_alpha': 0.20594179048085923, 'min_weight_fraction_leaf': 0.43386698908744314, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002573681751392315, 'validation_fraction': 0.9680316212431762, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:12:25,609] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.7678131035383085, 'learning_rate': 0.007776290790885781, 'dropout_rate': 0.30303355573944185, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.4610108941546788, 'min_weight_fraction_leaf': 0.41645906098318164, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012431389762873359, 'validation_fraction': 0.9065369938983409, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:12:26,800] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.5171830029999889, 'learning_rate': 0.0040166651424204955, 'dropout_rate': 0.3807313546610083, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.17457432007548962, 'min_weight_fraction_leaf': 0.48614852982593815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000244482530540027, 'validation_fraction': 0.9292904570302956, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:14:22,229] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8773563262480757, 'learning_rate': 0.02532898715676993, 'dropout_rate': 0.2528468518834252, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.5672123325935469, 'min_weight_fraction_leaf': 0.4613801112278463, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004351478423019476, 'validation_fraction': 0.45070104952373863, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-17 15:16:07,594] Trial 96 finished with value: 0.7555246671595266 and parameters: {'subsample': 0.8405253503495475, 'learning_rate': 0.016377171831941345, 'dropout_rate': 0.20374332906527465, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.031157726907107337, 'min_weight_fraction_leaf': 0.4485286950695694, 'max_features': 'log2', 'min_impurity_decrease': 0.0008739967635656416, 'validation_fraction': 0.7602436149101085, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 16}. Best is trial 75 with value: 0.7993613365985303.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:16:11,867] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.836158306860711, 'learning_rate': 0.01621127932999071, 'dropout_rate': 0.8479620532477699, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.4456457753678166, 'max_features': 'log2', 'min_impurity_decrease': 0.0009336689160945996, 'validation_fraction': 0.7598751254996176, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 12}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:16:12,323] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.7344061665966882, 'learning_rate': 0.020410071578111352, 'dropout_rate': 0.2839093344920812, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.3996467995504147, 'max_features': 'log2', 'min_impurity_decrease': 0.00047224200123682086, 'validation_fraction': 0.827056945015729, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 18}. Best is trial 75 with value: 0.7993613365985303.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.810126582278481

[I 2024-04-17 15:17:09,316] A new study created in memory with name: no-name-03e7ea20-e551-4e10-8087-e0252ce4f674

Fold 5 C-index: 0.7018779342723005
[I 2024-04-17 15:17:09,292] Trial 99 finished with value: 0.7866223191492192 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.35892734289616185, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 0.004507602823243077, 'min_weight_fraction_leaf': 0.21338193670151887, 'max_features': 'log2', 'min_impurity_decrease': 0.0018373817798183923, 'validation_fraction': 0.7282328797470141, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 75 with value: 0.7993613365985303.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.7993613365985303], datetime_start=datetime.datetime(2024, 4, 17, 15, 8, 25, 265557), datetime_complete=datetime.datetime(2024, 4, 17, 15, 8, 26, 868643), params={'subsample': 0.6001028949487068, 'learning_rate': 0.023239756862861477, 'dropout_rate': 0.6757649295445344, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.008819927083844869, 'min_weight_fraction_leaf': 0.1942611713172168, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0021237516252394237, 'validation_fraction': 0.7847712019774569, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for C-index:
 0.7993613365985303

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:17:50,493] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:18:11,209] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:18:33,340] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:19:08,275] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:19:20,382] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:19:23,480] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:19:54,191] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:20:02,996] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:20:04,125] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21268052044682917
Fold 2 IBS: 0.22067641048711592
Fold 3 IBS: 0.20350542889008158
Fold 4 IBS: 0.2231764930709189
Fold 5 IBS: 0.2176406915459263
[I 2024-04-17 15:21:26,907] Trial 9 finished with value: 0.2155359088881744 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443048985744143
Fold 5 IBS: 0.21803455300047256
[I 2024-04-17 15:23:29,096] Trial 10 finished with value: 0.21634130830268453 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:25:44,388] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21383641111136248
Fold 2 IBS: 0.22149689711703552
Fold 3 IBS: 0.20443482423916606
Fold 4 IBS: 0.22455454418948897
Fold 5 IBS: 0.21808680588487855
[I 2024-04-17 15:27:49,197] Trial 12 finished with value: 0.21648189650838628 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 15:28:49,117] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:30:38,625] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:32:14,670] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:33:05,860] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:35:14,105] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:36:17,728] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:36:30,658] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:38:33,334] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21373110319832214
Fold 2 IBS: 0.22152908047801065
Fold 3 IBS: 0.2044398850544662
Fold 4 IBS: 0.22470638007273172
Fold 5 IBS: 0.21807877811120815
[I 2024-04-17 15:40:32,429] Trial 21 finished with value: 0.21649704538294778 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2155359088881744.
Fold 1 IBS: 0.21260045167561253
Fold 2 IBS: 0.22070308241276262

Fold 3 IBS: 0.20352285540462065
Fold 4 IBS: 0.222937390832894
Fold 5 IBS: 0.21766902548369965
[I 2024-04-17 15:42:32,429] Trial 22 finished with value: 0.2154865611619179 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:44:21,865] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:45:34,171] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:46:40,132] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 15:48:25,932] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:48:39,397] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:49:18,175] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:50:49,075] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:51:26,979] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.2135093106849736
Fold 2 IBS: 0.22139977250283238
Fold 3 IBS: 0.20422680488437314
Fold 4 IBS: 0.2244144325480169
Fold 5 IBS: 0.21802056137064452
[I 2024-04-17 15:53:20,216] Trial 31 finished with value: 0.2163141763981681 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21283443105017621
Fold 2 IBS: 0.22117069719731833
Fold 3 IBS: 0.203701511518681
Fold 4 IBS: 0.22313138602580632
Fold 5 IBS: 0.21781108697486912
[I 2024-04-17 15:55:08,356] Trial 32 finished with value: 0.2157298225533702 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:56:25,345] Trial 33 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9175730211318314, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.23558036461669868, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 2.2672612842512112e-05, 'validation_fraction': 0.8391863465064515, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 15:57:41,718] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6818728654527908, 'learning_rate': 0.014570474664799389, 'dropout_rate': 0.39687420252491534, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9857366581537508, 'min_weight_fraction_leaf': 0.2451263696303153, 'max_features': 'sqrt', 'min_impurity_decrease': 7.173213136739857e-06, 'validation_fraction': 0.9231140468377321, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:58:03,384] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7474352307553052, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.29459319086620417, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 7.199479090473024e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:59:37,208] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.3498267997183648, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.2894426185614589, 'max_features': 'auto', 'min_impurity_decrease': 6.773052750173388e-05, 'validation_fraction': 0.7819324141806283, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 15:59:40,460] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.23919145342953393, 'max_features': None, 'min_impurity_decrease': 2.5414170052989375e-06, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:00:36,924] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8670579303141319, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.1728262906688144, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42202283765123816, 'min_weight_fraction_leaf': 0.35239546646921105, 'max_features': 'auto', 'min_impurity_decrease': 0.00017081434930634308, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:01:27,964] Trial 39 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8154589849054708, 'learning_rate': 0.006878494063124208, 'dropout_rate': 0.5323261217237781, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 1.1477698683125066, 'min_weight_fraction_leaf': 0.11023361948341703, 'max_features': 1, 'min_impurity_decrease': 1.7677159455067355e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:02:54,044] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.22290618957651392, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.5274073849776741, 'min_weight_fraction_leaf': 0.2739610635014299, 'max_features': 'auto', 'min_impurity_decrease': 2.272398816394983e-07, 'validation_fraction': 0.8717079478922802, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 22 with value: 0.2154865611619179.
Fold 1 IBS: 0.21124266704296782
Fold 2 IBS: 0.2202676295389528
Fold 3 IBS: 0.2024366872388908
Fold 4 IBS: 0.22127520965371827
Fold 5 IBS: 0.2171200751081455
[I 2024-04-17 16:05:03,541] Trial 41 finished with value: 0.21446845371653503 and parameters: {'subsample': 0.993176118879571, 'learning_rate': 0.01271988915310228, 'dropout_rate': 0.152367046323752, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.19182471840022747, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21446845371653503.
Fold 1 IBS: 0.21101946562722945
Fold 2 IBS: 0.21813396280637293
Fold 3 IBS: 0.2016000375693819
Fold 4 IBS: 0.2196649341266407
Fold 5 IBS: 0.21613057006918912
[I 2024-04-17 16:07:24,198] Trial 42 finished with value: 0.21330979403976286 and parameters: {'subsample': 0.9646924257252548, 'learning_rate': 0.012507391626216524, 'dropout_rate': 0.10802959125648778, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327408119788757, 'min_weight_fraction_leaf': 0.13510597987400375, 'max_features': 'auto', 'min_impurity_decrease': 1.0593992090305253e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 16:10:01,479] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828284890903175, 'learning_rate': 0.011543268886217308, 'dropout_rate': 0.11584589616484722, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.09682559138790292, 'max_features': 'auto', 'min_impurity_decrease': 1.0125868029922384e-07, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-17 16:11:52,300] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992870370700113, 'learning_rate': 0.022847552015173876, 'dropout_rate': 0.1556807870961761, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.1403134453903068, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.2125645258346338
Fold 2 IBS: 0.22018161964251412
Fold 3 IBS: 0.2031089706247819
Fold 4 IBS: 0.22244912786929444
Fold 5 IBS: 0.21730858129617295
[I 2024-04-17 16:12:33,630] Trial 45 finished with value: 0.21512256505347946 and parameters: {'subsample': 0.8888212863898438, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.20487736976615575, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.027893207681183953, 'min_weight_fraction_leaf': 0.06753391487815072, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9448766575733668, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:12:55,848] Trial 46 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.016684121596597847, 'dropout_rate': 0.10891325683572217, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.04784747079432074, 'max_features': 0.1, 'min_impurity_decrease': 2.0166271580558924e-07, 'validation_fraction': 0.24435732275143762, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:13:27,735] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7729061863940228, 'learning_rate': 0.02995584278149796, 'dropout_rate': 0.19790330487666663, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.05716507411653311, 'max_features': 0.1, 'min_impurity_decrease': 1.0699422270078741e-07, 'validation_fraction': 0.9565097869700105, 'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:14:27,938] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8446010144291817, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.14247687075474555, 'n_estimators': 294, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 0.1, 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.8246274171002186, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:15:03,406] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6917414996198523, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.2874751071933402, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.08230947204902768, 'max_features': 0.1, 'min_impurity_decrease': 1.8211699167585496e-07, 'validation_fraction': 0.6513576271964052, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 16:15:34,143] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.019482931131151772, 'dropout_rate': 0.6676032114338903, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.013701950422388753, 'max_features': 'log2', 'min_impurity_decrease': 7.041814507237016e-07, 'validation_fraction': 0.7324600365192867, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21265098751431113
Fold 2 IBS: 0.22023550988114693
Fold 3 IBS: 0.20318417941356073
Fold 4 IBS: 0.22280959887540525
Fold 5 IBS: 0.21754505058611065
[I 2024-04-17 16:17:35,241] Trial 51 finished with value: 0.21528506525410696 and parameters: {'subsample': 0.9574902141624301, 'learning_rate': 0.013974517784402708, 'dropout_rate': 0.19663405810878032, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288632756573364, 'min_weight_fraction_leaf': 0.1845530130003769, 'max_features': 'sqrt', 'min_impurity_decrease': 5.505988736711189e-07, 'validation_fraction': 0.8981152080635156, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:19:37,561] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8963301244448798, 'learning_rate': 0.014496942793188729, 'dropout_rate': 0.149261379708028, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.3267109398107992, 'min_weight_fraction_leaf': 0.19350109364955276, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0314361105633666e-07, 'validation_fraction': 0.8673271583656655, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:21:19,857] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.937858776808653, 'learning_rate': 0.01317678110087918, 'dropout_rate': 0.20949679348390188, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.9371275797883157, 'min_weight_fraction_leaf': 0.16718449303286065, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0035393968280476e-07, 'validation_fraction': 0.9639725916044029, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:21:33,868] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5502453589475278, 'learning_rate': 0.005289059095661144, 'dropout_rate': 0.16758744743711101, 'n_estimators': 147, 'criterion': 'squared_error', 'ccp_alpha': 0.6055238018097719, 'min_weight_fraction_leaf': 0.1222904374725215, 'max_features': 'sqrt', 'min_impurity_decrease': 8.119424084486158e-07, 'validation_fraction': 0.8019436577478607, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21149115656929574
Fold 2 IBS: 0.22061155778446703

Fold 3 IBS: 0.20287635124596737
Fold 4 IBS: 0.22157930195318806
Fold 5 IBS: 0.21757113828505154
[I 2024-04-17 16:23:30,289] Trial 55 finished with value: 0.21482590116759398 and parameters: {'subsample': 0.9703353679292269, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.2676210325613897, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.036860238643527846, 'min_weight_fraction_leaf': 0.21798842867076448, 'max_features': None, 'min_impurity_decrease': 4.086647023052284e-07, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:24:47,535] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9556274374724505, 'learning_rate': 0.022777236721630217, 'dropout_rate': 0.36674252455714285, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.3101553395317078, 'min_weight_fraction_leaf': 0.21445816437013876, 'max_features': None, 'min_impurity_decrease': 4.99089267664694e-07, 'validation_fraction': 0.8444326224317742, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.2111687028051771
Fold 2 IBS: 0.2192670012219273
Fold 3 IBS: 0.20113060921449374
Fold 4 IBS: 0.21823429253204232
Fold 5 IBS: 0.21737983024811217
[I 2024-04-17 16:24:49,984] Trial 57 finished with value: 0.21343608720435053 and parameters: {'subsample': 0.9885544496318819, 'learning_rate': 0.02570846317737359, 'dropout_rate': 0.11524078732039367, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.0019474604343284706, 'min_weight_fraction_leaf': 0.1539893411018015, 'max_features': None, 'min_impurity_decrease': 3.011740016899961e-07, 'validation_fraction': 0.8976605224112223, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:24:50,975] Trial 58 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9760257284010853, 'learning_rate': 0.044170756425452734, 'dropout_rate': 0.10695167335108825, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 0.7470878188226159, 'min_weight_fraction_leaf': 0.1623750980802567, 'max_features': None, 'min_impurity_decrease': 3.402621023187449e-07, 'validation_fraction': 0.8839190525574698, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:24:58,218] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8651178500686678, 'learning_rate': 0.031729459746086146, 'dropout_rate': 0.1294932593082019, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 2.4509996240950476, 'min_weight_fraction_leaf': 0.14999314729494934, 'max_features': None, 'min_impurity_decrease': 1.564084650521852e-07, 'validation_fraction': 0.996741201133535, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:25:10,170] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9167528164906635, 'learning_rate': 0.024844206422551217, 'dropout_rate': 0.10027142034172723, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 1.5027931264041994, 'min_weight_fraction_leaf': 0.1840765520407988, 'max_features': None, 'min_impurity_decrease': 0.026115039984674165, 'validation_fraction': 0.9013568181484788, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21273370328437058
Fold 2 IBS: 0.2209400117762394
Fold 3 IBS: 0.20291275785992635
Fold 4 IBS: 0.2221801252368877
Fold 5 IBS: 0.21772394248518598
[I 2024-04-17 16:26:59,973] Trial 61 finished with value: 0.215298108128522 and parameters: {'subsample': 0.9931174804814122, 'learning_rate': 0.016529825628647618, 'dropout_rate': 0.1935981459085364, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.0813695010094894, 'min_weight_fraction_leaf': 0.12194954374946233, 'max_features': None, 'min_impurity_decrease': 1.1729202879091808e-06, 'validation_fraction': 0.9481060427790172, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:28:50,618] Trial 62 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9972168379620757, 'learning_rate': 0.028217399882747345, 'dropout_rate': 0.1806381271548384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.3084041748420949, 'min_weight_fraction_leaf': 0.12013391362008917, 'max_features': None, 'min_impurity_decrease': 1.1386618305709938e-06, 'validation_fraction': 0.9457754330032251, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21199538046555141
Fold 2 IBS: 0.21927513318508043
Fold 3 IBS: 0.20224071177058792
Fold 4 IBS: 0.22058703644615904
Fold 5 IBS: 0.21687348826704012
[I 2024-04-17 16:28:52,491] Trial 63 finished with value: 0.21419435002688378 and parameters: {'subsample': 0.9627141857439078, 'learning_rate': 0.019891228353589942, 'dropout_rate': 0.2615796624395084, 'n_estimators': 49, 'criterion': 'squared_error', 'ccp_alpha': 0.01736018686586977, 'min_weight_fraction_leaf': 0.04375001956932725, 'max_features': None, 'min_impurity_decrease': 2.9650355903328224e-07, 'validation_fraction': 0.9569907594316491, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:28:53,870] Trial 64 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9587518146305004, 'learning_rate': 0.019802180649912862, 'dropout_rate': 0.2603466948459836, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 1.002024697263514, 'min_weight_fraction_leaf': 0.044285609862845736, 'max_features': None, 'min_impurity_decrease': 2.720232704210543e-07, 'validation_fraction': 0.9023407544716895, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:28:55,541] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8951181311729837, 'learning_rate': 0.037231214360123326, 'dropout_rate': 0.32454189899564956, 'n_estimators': 48, 'criterion': 'squared_error', 'ccp_alpha': 0.4113923217247418, 'min_weight_fraction_leaf': 0.00011246718145094259, 'max_features': None, 'min_impurity_decrease': 1.381949767966752e-07, 'validation_fraction': 0.8558515608716643, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-17 16:28:55,988] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9342515202646464, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.2288776012135632, 'n_estimators': 7, 'criterion': 'squared_error', 'ccp_alpha': 0.7042671412306138, 'min_weight_fraction_leaf': 0.0708576995244338, 'max_features': None, 'min_impurity_decrease': 5.049204052683285e-07, 'validation_fraction': 0.779814650235569, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 42 with value: 0.21330979403976286.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:29:03,508] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9699873838014033, 'learning_rate': 0.012103946738880062, 'dropout_rate': 0.14222380728521514, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.030567908908384282, 'max_features': 'sqrt', 'min_impurity_decrease': 1.094611645458025e-07, 'validation_fraction': 0.8187342892372662, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 16:29:04,599] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8066950165330748, 'learning_rate': 0.023377362681528607, 'dropout_rate': 0.15894248115081894, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 1.0894868734364265, 'min_weight_fraction_leaf': 0.09777832680789011, 'max_features': 1, 'min_impurity_decrease': 3.2013908424881626e-07, 'validation_fraction': 0.9728405359487509, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:29:06,732] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8529548190627155, 'learning_rate': 0.0012168162419408535, 'dropout_rate': 0.42050912513013483, 'n_estimators': 61, 'criterion': 'squared_error', 'ccp_alpha': 0.7384649181664461, 'min_weight_fraction_leaf': 0.2085136183735176, 'max_features': None, 'min_impurity_decrease': 1.7154437160377624e-07, 'validation_fraction': 0.9083572843679635, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.2119179897288693
Fold 2 IBS: 0.2191674672228582
Fold 3 IBS: 0.20228306257317225
Fold 4 IBS: 0.22135483925598565
Fold 5 IBS: 0.2171062746828305
[I 2024-04-17 16:29:10,249] Trial 70 finished with value: 0.21436592669274318 and parameters: {'subsample': 0.9256610134215202, 'learning_rate': 0.027187396607684697, 'dropout_rate': 0.2698281084334899, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01011709803992732, 'min_weight_fraction_leaf': 0.15633989047262453, 'max_features': 0.1, 'min_impurity_decrease': 6.342045680536371e-07, 'validation_fraction': 0.9963961862738748, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.21217214060359357
Fold 2 IBS: 0.21985130456369942
Fold 3 IBS: 0.20280227763692915
Fold 4 IBS: 0.22199491370408642
Fold 5 IBS: 0.2172618986174987
[I 2024-04-17 16:29:13,556] Trial 71 finished with value: 0.21481650702516145 and parameters: {'subsample': 0.9191145215668692, 'learning_rate': 0.028803620179149808, 'dropout_rate': 0.308958719403514, 'n_estimators': 77, 'criterion': 'friedman_mse', 'ccp_alpha': 0.026599566986409653, 'min_weight_fraction_leaf': 0.15399848016813225, 'max_features': 0.1, 'min_impurity_decrease': 5.855723294143886e-07, 'validation_fraction': 0.9916810781214654, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 42 with value: 0.21330979403976286.
Fold 1 IBS: 0.2108416751744239
Fold 2 IBS: 0.2177257307112813
Fold 3 IBS: 0.20094569686466818
Fold 4 IBS: 0.21971917957422668
Fold 5 IBS: 0.21660088360885354
[I 2024-04-17 16:29:17,743] Trial 72 finished with value: 0.21316663318669074 and parameters: {'subsample': 0.9163996694308585, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.2700967141743007, 'n_estimators': 87, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791400710493756, 'min_weight_fraction_leaf': 0.155227755776175, 'max_features': 0.1, 'min_impurity_decrease': 2.7153758955492077e-07, 'validation_fraction': 0.9936760144532607, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:29:21,040] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9288897705401948, 'learning_rate': 0.03411408397308106, 'dropout_rate': 0.2722486347578293, 'n_estimators': 77, 'criterion': 'friedman_mse', 'ccp_alpha': 0.35137250856599767, 'min_weight_fraction_leaf': 0.1495872461746581, 'max_features': 0.1, 'min_impurity_decrease': 7.270118939912425e-07, 'validation_fraction': 0.9925633875202848, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:29:27,748] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9126870857191455, 'learning_rate': 0.04271327854752515, 'dropout_rate': 0.3083593342668366, 'n_estimators': 120, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6348591831690735, 'min_weight_fraction_leaf': 0.15810053074507613, 'max_features': 0.1, 'min_impurity_decrease': 3.626343412672233e-07, 'validation_fraction': 0.979557353406547, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-17 16:29:30,144] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8293713781851788, 'learning_rate': 0.02908256354003201, 'dropout_rate': 0.37158886582886624, 'n_estimators': 64, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3272014920640867, 'min_weight_fraction_leaf': 0.20024829748849934, 'max_features': 0.1, 'min_impurity_decrease': 1.290830214046723e-06, 'validation_fraction': 0.964167888344054, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 6}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 16:29:34,141] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9737708379828696, 'learning_rate': 0.040314448903926776, 'dropout_rate': 0.3433203488764059, 'n_estimators': 89, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.17163640619790976, 'max_features': 0.1, 'min_impurity_decrease': 3.1330804284170225e-06, 'validation_fraction': 0.9291290438093902, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:29:35,201] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8782627345221757, 'learning_rate': 0.05513764082997855, 'dropout_rate': 0.3076595483575353, 'n_estimators': 30, 'criterion': 'friedman_mse', 'ccp_alpha': 5.8752783688356525, 'min_weight_fraction_leaf': 0.1353755115318474, 'max_features': 0.1, 'min_impurity_decrease': 4.688347284022185e-06, 'validation_fraction': 0.995904541155469, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:29:38,821] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9362147727385395, 'learning_rate': 0.02736082926046323, 'dropout_rate': 0.26541734467806316, 'n_estimators': 77, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2910342652485194, 'min_weight_fraction_leaf': 0.22600697495173297, 'max_features': 'log2', 'min_impurity_decrease': 2.73345967920419e-07, 'validation_fraction': 0.9235701874070005, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 16:29:46,158] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9100835469049136, 'learning_rate': 0.036156542494890344, 'dropout_rate': 0.23372149213636637, 'n_estimators': 115, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8315019131728741, 'min_weight_fraction_leaf': 0.09644449915291103, 'max_features': 0.1, 'min_impurity_decrease': 1.678382435082819e-06, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:29:47,956] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9699827601278878, 'learning_rate': 0.04790733894070888, 'dropout_rate': 0.49040987944703684, 'n_estimators': 50, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.18340034254353382, 'max_features': None, 'min_impurity_decrease': 0.000321859747788374, 'validation_fraction': 0.9690149558573901, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21255615970957292
Fold 2 IBS: 0.22018197557064625
Fold 3 IBS: 0.2032666002943422
Fold 4 IBS: 0.22259861051669197
Fold 5 IBS: 0.2173563047177038
[I 2024-04-17 16:30:02,421] Trial 81 finished with value: 0.21519193016179142 and parameters: {'subsample': 0.8927745843584889, 'learning_rate': 0.020283778850589053, 'dropout_rate': 0.21396485912215418, 'n_estimators': 171, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038423779386081554, 'min_weight_fraction_leaf': 0.1296287192043128, 'max_features': 0.1, 'min_impurity_decrease': 1.6509092118135291e-07, 'validation_fraction': 0.9511936913819414, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:30:03,304] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992895000371431, 'learning_rate': 0.0327395865430866, 'dropout_rate': 0.2466802901818147, 'n_estimators': 23, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2419414804705902, 'min_weight_fraction_leaf': 0.10781763151993767, 'max_features': 0.1, 'min_impurity_decrease': 2.449159030109621e-07, 'validation_fraction': 0.8801112134114132, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:30:30,168] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9466967523746362, 'learning_rate': 0.025478798687217884, 'dropout_rate': 0.12884895722070694, 'n_estimators': 230, 'criterion': 'friedman_mse', 'ccp_alpha': 0.49569834088416487, 'min_weight_fraction_leaf': 0.06385027845598873, 'max_features': 0.1, 'min_impurity_decrease': 4.307156806430546e-07, 'validation_fraction': 0.9337797805112966, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:30:34,117] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8713614633320048, 'learning_rate': 0.01695307836373483, 'dropout_rate': 0.5754887354513003, 'n_estimators': 99, 'criterion': 'friedman_mse', 'ccp_alpha': 0.21221167138928693, 'min_weight_fraction_leaf': 0.15557279172395266, 'max_features': 0.1, 'min_impurity_decrease': 1.0213739171793835e-07, 'validation_fraction': 0.8444003184883642, 'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21316096671858398
Fold 2 IBS: 0.2200401684829796
Fold 3 IBS: 0.2037460993475453
Fold 4 IBS: 0.22322212498163954
Fold 5 IBS: 0.21774547963144003
[I 2024-04-17 16:30:34,596] Trial 85 finished with value: 0.2155829678324377 and parameters: {'subsample': 0.9184414149075565, 'learning_rate': 0.020978535360278536, 'dropout_rate': 0.28673324116416354, 'n_estimators': 4, 'criterion': 'friedman_mse', 'ccp_alpha': 0.011135359211459884, 'min_weight_fraction_leaf': 0.09067054112209766, 'max_features': 0.1, 'min_impurity_decrease': 9.047919329662994e-07, 'validation_fraction': 0.9997702077342705, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:30:38,238] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9489486546497419, 'learning_rate': 0.030277706141007506, 'dropout_rate': 0.17306006860746767, 'n_estimators': 75, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9940266517886238, 'min_weight_fraction_leaf': 0.22016139144079294, 'max_features': 1, 'min_impurity_decrease': 1.4445561308953809e-07, 'validation_fraction': 0.9177840963140179, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-17 16:30:40,534] Trial 87 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9760021338029566, 'learning_rate': 0.016208416182919065, 'dropout_rate': 0.32600326863583723, 'n_estimators': 61, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5951339757090965, 'min_weight_fraction_leaf': 0.19181514509052383, 'max_features': 0.1, 'min_impurity_decrease': 6.163336213153e-07, 'validation_fraction': 0.9607088960762235, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:30:49,148] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8232139007469851, 'learning_rate': 0.010782972747315857, 'dropout_rate': 0.22297892077473458, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 1.660863996319751, 'min_weight_fraction_leaf': 0.035580888639540356, 'max_features': None, 'min_impurity_decrease': 2.1793463266511972e-07, 'validation_fraction': 0.894565648621358, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:30:50,562] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8535484633772966, 'learning_rate': 0.03949586140355399, 'dropout_rate': 0.26821996041255114, 'n_estimators': 41, 'criterion': 'squared_error', 'ccp_alpha': 1.1917037663435968, 'min_weight_fraction_leaf': 0.17574893192422542, 'max_features': 'log2', 'min_impurity_decrease': 4.344142999314639e-07, 'validation_fraction': 0.8624882565770394, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:30:56,521] Trial 90 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7850349664677921, 'learning_rate': 0.024979952118886106, 'dropout_rate': 0.13081530577107772, 'n_estimators': 101, 'criterion': 'squared_error', 'ccp_alpha': 0.8282836547229422, 'min_weight_fraction_leaf': 0.2024600343544593, 'max_features': 0.1, 'min_impurity_decrease': 1.5250319081941967e-07, 'validation_fraction': 0.9450791570667698, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21237675973546286
Fold 2 IBS: 0.22003784588549294
Fold 3 IBS: 0.20313178251734024
Fold 4 IBS: 0.22237815716493686
Fold 5 IBS: 0.21729624772606843
[I 2024-04-17 16:31:11,573] Trial 91 finished with value: 0.2150441586058603 and parameters: {'subsample': 0.8875951290864955, 'learning_rate': 0.020649416193930417, 'dropout_rate': 0.20240702029634142, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03883954104401819, 'min_weight_fraction_leaf': 0.13202282670823812, 'max_features': 0.1, 'min_impurity_decrease': 1.8979101561532492e-07, 'validation_fraction': 0.9699980604871171, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-17 16:31:29,906] Trial 92 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.890460993167054, 'learning_rate': 0.022870695757079517, 'dropout_rate': 0.16649834635279426, 'n_estimators': 194, 'criterion': 'friedman_mse', 'ccp_alpha': 0.19747742321360495, 'min_weight_fraction_leaf': 0.1093831247784104, 'max_features': 0.1, 'min_impurity_decrease': 2.5796772328311703e-07, 'validation_fraction': 0.9718972735976402, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:31:42,652] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9323986237949874, 'learning_rate': 0.01999319824042314, 'dropout_rate': 0.19288156429477699, 'n_estimators': 158, 'criterion': 'friedman_mse', 'ccp_alpha': 0.46998443532770284, 'min_weight_fraction_leaf': 0.13347234137486122, 'max_features': 0.1, 'min_impurity_decrease': 2.0124452872995606e-07, 'validation_fraction': 0.9224496069531118, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 16:33:11,511] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9823871083063405, 'learning_rate': 0.015427148804564828, 'dropout_rate': 0.24297221319414372, 'n_estimators': 457, 'criterion': 'friedman_mse', 'ccp_alpha': 0.232952640705807, 'min_weight_fraction_leaf': 0.14688044882183482, 'max_features': 0.1, 'min_impurity_decrease': 1.2896919812412857e-07, 'validation_fraction': 0.9730517488038497, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 16:33:26,312] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2544345960099228, 'learning_rate': 0.018219702195342125, 'dropout_rate': 0.3036129310190463, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5677355902425925, 'min_weight_fraction_leaf': 0.08591562171001486, 'max_features': 'auto', 'min_impurity_decrease': 3.4451047661509324e-07, 'validation_fraction': 0.9999740662096565, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.2129092575879055
Fold 2 IBS: 0.2203267410823
Fold 3 IBS: 0.20358811497725723
Fold 4 IBS: 0.2229605019595935
Fold 5 IBS: 0.21759412646885248
[I 2024-04-17 16:33:29,194] Trial 96 finished with value: 0.21547574841518174 and parameters: {'subsample': 0.48032209804466314, 'learning_rate': 0.007243389030518873, 'dropout_rate': 0.21172533637129795, 'n_estimators': 54, 'criterion': 'squared_error', 'ccp_alpha': 0.030854839169471092, 'min_weight_fraction_leaf': 0.1663428203123265, 'max_features': None, 'min_impurity_decrease': 7.972225931652719e-07, 'validation_fraction': 0.9504850458180756, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:33:39,892] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.38054192896008343, 'learning_rate': 0.027291398901545715, 'dropout_rate': 0.8479620532477699, 'n_estimators': 269, 'criterion': 'friedman_mse', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.25929692184864234, 'max_features': 0.1, 'min_impurity_decrease': 4.7577481394965577e-07, 'validation_fraction': 0.8903017764367833, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 16:34:01,038] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9553681357308647, 'learning_rate': 0.031994184932983526, 'dropout_rate': 0.18084292132623428, 'n_estimators': 211, 'criterion': 'squared_error', 'ccp_alpha': 0.9673820053861225, 'min_weight_fraction_leaf': 0.013482365007357576, 'max_features': None, 'min_impurity_decrease': 3.2806535249753844e-07, 'validation_fraction': 0.9145623830117893, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 72 with value: 0.21316663318669074.
Fold 1 IBS: 0.21130358960356846
Fold 2 IBS: 0.21830519479917238
Fold 3 IBS: 0.20179606051936078
Fold 4 IBS: 0.2200046103490216
Fold 5 IBS: 0.21671211632449325
[I 2024-04-17 16:34:05,499] Trial 99 finished with value: 0.2136243143191233 and parameters: {'subsample': 0.912603744024235, 'learning_rate': 0.012751091781211518, 'dropout_rate': 0.14666812330933382, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.004367037757384062, 'min_weight_fraction_leaf': 0.07318365179892175, 'max_features': 'auto', 'min_impurity_decrease': 1.87063350575156e-07, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 6}. Best is trial 72 with value: 0.21316663318669074.


* Best trial for IBS:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.21316663318669074], datetime_start=datetime.datetime(2024, 4, 17, 16, 29, 13, 561068), datetime_complete=datetime.datetime(2024, 4, 17, 16, 29, 17, 742390), params={'subsample': 0.9163996694308585, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.2700967141743007, 'n_estimators': 87, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791400710493756, 'min_weight_fraction_leaf': 0.155227755776175, 'max_features': 0.1, 'min_impurity_decrease': 2.7153758955492077e-07, 'validation_fraction': 0.9936760144532607, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=72, value=None)


* Best Score for IBS:
 0.21316663318669074

In [65]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.799
train_ibs:  0.213

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008819927083844869,
                                 criterion='squared_error',
                                 dropout_rate=0.6757649295445344,
                                 learning_rate=0.023239756862861477,
                                 max_depth=1, max_features='sqrt',
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=0.0021237516252394237,
                                 min_samples_leaf=18, min_samples_split=17,
                                 min_weight_fraction_leaf=0.1942611713172168,
                                 n_estimators=53, random_state=123,
                                 subsample=0.6001028949487068,
                                 validation_fraction=0.7847712019774569)

C-index score: 0.638

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004791400710493756,
                                 dropout_rate=0.2700967141743007,
                                 learning_rate=0.04131861156773751, max_depth=6,
                                 max_features=0.1, max_leaf_nodes=17,
                                 min_impurity_decrease=2.7153758955492077e-07,
                                 min_samples_leaf=14, min_samples_split=18,
                                 min_weight_fraction_leaf=0.155227755776175,
                                 n_estimators=87, random_state=123,
                                 subsample=0.9163996694308585,
                                 validation_fraction=0.9936760144532607)

IBS: 0.22

In [69]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [70]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [71]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 16:34:07,073] A new study created in memory with name: no-name-0a6fedd0-0381-431e-90e3-39c295d6a36c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:08,482] Trial 0 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:19,655] Trial 1 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:21,792] Trial 2 finished with value: 0.6827756028260995 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6827756028260995.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:24,759] Trial 3 finished with value: 0.6854541742546709 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6854541742546709.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:29,486] Trial 4 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:36,279] Trial 5 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:38,720] Trial 6 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:34:39,363] Trial 7 finished with value: 0.6837145699622498 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:42,225] Trial 8 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:34:50,321] Trial 9 finished with value: 0.6827756028260995 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:34:56,119] Trial 10 finished with value: 0.6874610685616894 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6874610685616894.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 16:35:02,704] Trial 11 finished with value: 0.7116637977984107 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7116637977984107.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 16:35:08,759] Trial 12 finished with value: 0.7134956220774182 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:35:16,436] Trial 13 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:35:22,206] Trial 14 finished with value: 0.6965394734207724 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:35:27,359] Trial 15 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:35:36,471] Trial 16 finished with value: 0.700989390391402 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:35:44,697] Trial 17 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:35:48,440] Trial 18 finished with value: 0.6854541742546709 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.7134956220774182.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:35:49,648] Trial 19 finished with value: 0.7010959791216443 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:35:59,613] Trial 20 finished with value: 0.6882663906905411 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:35:59,945] Trial 21 finished with value: 0.6963639510975463 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.7075879968118339, 'n_estimators': 12, 'learning_rate': 0.09417886707495288}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:36:01,027] Trial 22 finished with value: 0.6992641548426368 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.7646900707403661, 'n_estimators': 92, 'learning_rate': 0.09079561778768044}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:36:06,229] Trial 23 finished with value: 0.6855002842479639 and parameters: {'subsample': 0.18416659954432174, 'dropout_rate': 0.5772650959496687, 'n_estimators': 311, 'learning_rate': 0.06498100052925637}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:36:07,673] Trial 24 finished with value: 0.6873274235543908 and parameters: {'subsample': 0.2045297048439274, 'dropout_rate': 0.9686347225905483, 'n_estimators': 133, 'learning_rate': 0.07843777531541643}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:36:10,552] Trial 25 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.4132414033804696, 'dropout_rate': 0.8139553387854312, 'n_estimators': 231, 'learning_rate': 0.09478486238393272}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:36:12,341] Trial 26 finished with value: 0.6863931413908211 and parameters: {'subsample': 0.2942732104482271, 'dropout_rate': 0.5707562654379044, 'n_estimators': 150, 'learning_rate': 0.08146277028320098}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:36:16,328] Trial 27 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.6426159203387378, 'n_estimators': 280, 'learning_rate': 0.04133902891970489}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:36:22,673] Trial 28 finished with value: 0.6827756028260995 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.3080593480767576, 'n_estimators': 338, 'learning_rate': 0.09352800640830385}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:36:23,736] Trial 29 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 101, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 16:36:24,465] Trial 30 finished with value: 0.6908527421325262 and parameters: {'subsample': 0.1573472469684153, 'dropout_rate': 0.16903977002361698, 'n_estimators': 57, 'learning_rate': 0.016814619253793885}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:36:34,577] Trial 31 finished with value: 0.6947613094006627 and parameters: {'subsample': 0.21310341738752459, 'dropout_rate': 0.1381631874772056, 'n_estimators': 413, 'learning_rate': 0.08798142250506455}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:36:46,205] Trial 32 finished with value: 0.7018551912572027 and parameters: {'subsample': 0.2108624467137336, 'dropout_rate': 0.10260832409315873, 'n_estimators': 467, 'learning_rate': 0.09927457031402288}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:36:57,621] Trial 33 finished with value: 0.698398353976836 and parameters: {'subsample': 0.14640475436912043, 'dropout_rate': 0.19334485216893893, 'n_estimators': 470, 'learning_rate': 0.09966997282956479}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:37:05,570] Trial 34 finished with value: 0.6873735335476838 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.2978953399112947, 'n_estimators': 388, 'learning_rate': 0.06996282877216126}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:37:08,835] Trial 35 finished with value: 0.7029962846984205 and parameters: {'subsample': 0.10531930558713169, 'dropout_rate': 0.5012736330834714, 'n_estimators': 232, 'learning_rate': 0.07461987923632134}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:37:21,216] Trial 36 finished with value: 0.6863931413908211 and parameters: {'subsample': 0.32682843496689273, 'dropout_rate': 0.19399309980141916, 'n_estimators': 496, 'learning_rate': 0.07318831003811152}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 16:37:24,706] Trial 37 finished with value: 0.6903193949908527 and parameters: {'subsample': 0.15341314138701748, 'dropout_rate': 0.47096246897520044, 'n_estimators': 237, 'learning_rate': 0.07767873407402504}. Best is trial 12 with value: 0.7134956220774182.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:37:27,320] Trial 38 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.24127903257141559, 'dropout_rate': 0.37281071596569393, 'n_estimators': 189, 'learning_rate': 0.08285381104305417}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 16:37:32,379] Trial 39 finished with value: 0.6863884564182405 and parameters: {'subsample': 0.314034710745663, 'dropout_rate': 0.13241076213324454, 'n_estimators': 287, 'learning_rate': 0.06892741183938003}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:37:38,678] Trial 40 finished with value: 0.6910929758700673 and parameters: {'subsample': 0.153994887081676, 'dropout_rate': 0.2862352927725973, 'n_estimators': 333, 'learning_rate': 0.0910858110196729}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:37:40,821] Trial 41 finished with value: 0.700400563311274 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.5064130400928429, 'n_estimators': 172, 'learning_rate': 0.09510908972174754}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:37:43,646] Trial 42 finished with value: 0.6863470313975281 and parameters: {'subsample': 0.19683570010431722, 'dropout_rate': 0.6458410381814093, 'n_estimators': 213, 'learning_rate': 0.09642375067347132}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:37:50,972] Trial 43 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.4380477179641039, 'dropout_rate': 0.8807769026841397, 'n_estimators': 449, 'learning_rate': 0.08940933209512604}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:37:55,561] Trial 44 finished with value: 0.7022323875902814 and parameters: {'subsample': 0.13326295226620088, 'dropout_rate': 0.14430190263087336, 'n_estimators': 259, 'learning_rate': 0.08429244803416144}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:38:00,117] Trial 45 finished with value: 0.6991766198286313 and parameters: {'subsample': 0.17572235589015067, 'dropout_rate': 0.1043186622541777, 'n_estimators': 263, 'learning_rate': 0.08179192203221856}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:38:03,963] Trial 46 finished with value: 0.699359240122247 and parameters: {'subsample': 0.13656050229303682, 'dropout_rate': 0.217336053780198, 'n_estimators': 239, 'learning_rate': 0.07635421514953118}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 16:38:12,476] Trial 47 finished with value: 0.6863884564182405 and parameters: {'subsample': 0.24168475249593438, 'dropout_rate': 0.15017371456135958, 'n_estimators': 386, 'learning_rate': 0.055720653442315984}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:38:18,589] Trial 48 finished with value: 0.6827756028260995 and parameters: {'subsample': 0.5590545924472794, 'dropout_rate': 0.25791879381373917, 'n_estimators': 325, 'learning_rate': 0.08446047516076069}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:38:23,192] Trial 49 finished with value: 0.6873274235543908 and parameters: {'subsample': 0.27648534587899776, 'dropout_rate': 0.1304931000922671, 'n_estimators': 272, 'learning_rate': 0.04420179108291779}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:38:25,987] Trial 50 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6943542321654076, 'dropout_rate': 0.42581631326037594, 'n_estimators': 205, 'learning_rate': 0.09110417865390581}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 16:38:32,220] Trial 51 finished with value: 0.7125566549412679 and parameters: {'subsample': 0.12360178179157141, 'dropout_rate': 0.10116345134336863, 'n_estimators': 305, 'learning_rate': 0.09746838899970885}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 16:38:37,532] Trial 52 finished with value: 0.7078568204620217 and parameters: {'subsample': 0.13637380813559394, 'dropout_rate': 0.10407876109588823, 'n_estimators': 295, 'learning_rate': 0.09950377701118984}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:38:43,044] Trial 53 finished with value: 0.7048695339981403 and parameters: {'subsample': 0.12235314965386802, 'dropout_rate': 0.1665799768728255, 'n_estimators': 302, 'learning_rate': 0.08725090671305964}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:38:48,351] Trial 54 finished with value: 0.6955590812639096 and parameters: {'subsample': 0.1696678906728003, 'dropout_rate': 0.21344995201840233, 'n_estimators': 299, 'learning_rate': 0.09209678862847312}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:38:55,658] Trial 55 finished with value: 0.7002716032765559 and parameters: {'subsample': 0.13039903354075824, 'dropout_rate': 0.18226800835487564, 'n_estimators': 360, 'learning_rate': 0.08714976073183868}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:39:01,133] Trial 56 finished with value: 0.6910832920989918 and parameters: {'subsample': 0.1815019193325193, 'dropout_rate': 0.264808936035714, 'n_estimators': 306, 'learning_rate': 0.0964371862085767}. Best is trial 12 with value: 0.7134956220774182.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:39:07,678] Trial 57 finished with value: 0.7068446870555221 and parameters: {'subsample': 0.10154220214843619, 'dropout_rate': 0.3342159459494831, 'n_estimators': 345, 'learning_rate': 0.0997291184079334}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:39:14,466] Trial 58 finished with value: 0.6873735335476838 and parameters: {'subsample': 0.232654900810588, 'dropout_rate': 0.33189243444570327, 'n_estimators': 352, 'learning_rate': 0.09772966121712592}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:39:22,590] Trial 59 finished with value: 0.7020158925415577 and parameters: {'subsample': 0.13949375083321575, 'dropout_rate': 0.1671796581517604, 'n_estimators': 381, 'learning_rate': 0.0998582191898498}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 16:39:28,674] Trial 60 finished with value: 0.6911247171197042 and parameters: {'subsample': 0.18398840006517186, 'dropout_rate': 0.23301618801900387, 'n_estimators': 324, 'learning_rate': 0.09210169317886324}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:39:33,208] Trial 61 finished with value: 0.6982376526924811 and parameters: {'subsample': 0.10813910467145653, 'dropout_rate': 0.5221373506993093, 'n_estimators': 285, 'learning_rate': 0.08735412463201261}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:39:40,404] Trial 62 finished with value: 0.7080761808037694 and parameters: {'subsample': 0.1274026073268983, 'dropout_rate': 0.12023288036792137, 'n_estimators': 352, 'learning_rate': 0.09400559962635692}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:39:47,308] Trial 63 finished with value: 0.7071833236609123 and parameters: {'subsample': 0.1308716913944263, 'dropout_rate': 0.12173749511082893, 'n_estimators': 348, 'learning_rate': 0.09560284586307954}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:39:54,346] Trial 64 finished with value: 0.7027941583933529 and parameters: {'subsample': 0.2044254625313129, 'dropout_rate': 0.10084502080325047, 'n_estimators': 349, 'learning_rate': 0.09393410754971043}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:40:03,236] Trial 65 finished with value: 0.7010498691283512 and parameters: {'subsample': 0.16384152652783815, 'dropout_rate': 0.13283899373874214, 'n_estimators': 403, 'learning_rate': 0.09671722918660462}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:40:10,942] Trial 66 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.2544490852713979, 'dropout_rate': 0.20525003146333348, 'n_estimators': 369, 'learning_rate': 0.010808482740950733}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:40:17,705] Trial 67 finished with value: 0.694788365677719 and parameters: {'subsample': 0.2187994851655431, 'dropout_rate': 0.13386480557384356, 'n_estimators': 339, 'learning_rate': 0.09258113278356832}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:40:23,667] Trial 68 finished with value: 0.7002445469994998 and parameters: {'subsample': 0.13535261392783132, 'dropout_rate': 0.1732763823078357, 'n_estimators': 318, 'learning_rate': 0.08013968863723875}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:40:31,202] Trial 69 finished with value: 0.6827756028260995 and parameters: {'subsample': 0.8584661298748817, 'dropout_rate': 0.11954140078035906, 'n_estimators': 341, 'learning_rate': 0.08931128331794293}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 16:40:41,403] Trial 70 finished with value: 0.690185749983554 and parameters: {'subsample': 0.18695877933252175, 'dropout_rate': 0.2435373677786457, 'n_estimators': 438, 'learning_rate': 0.030541753347826425}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:40:47,135] Trial 71 finished with value: 0.7048648490255597 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.15972975864072841, 'n_estimators': 303, 'learning_rate': 0.09996994937752976}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 16:40:52,543] Trial 72 finished with value: 0.6955814525683854 and parameters: {'subsample': 0.1547987955834935, 'dropout_rate': 0.15871471673602622, 'n_estimators': 293, 'learning_rate': 0.09447551482130623}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:40:58,513] Trial 73 finished with value: 0.6984397789975485 and parameters: {'subsample': 0.12709038659790928, 'dropout_rate': 0.1973856372025119, 'n_estimators': 318, 'learning_rate': 0.09705200300053905}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:41:03,344] Trial 74 finished with value: 0.7058228698779467 and parameters: {'subsample': 0.10099983845623818, 'dropout_rate': 0.12824589730559405, 'n_estimators': 274, 'learning_rate': 0.0854954061088792}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:41:08,361] Trial 75 finished with value: 0.7060422302196945 and parameters: {'subsample': 0.10198222090518944, 'dropout_rate': 0.11761517476312061, 'n_estimators': 272, 'learning_rate': 0.08551494626967074}. Best is trial 12 with value: 0.7134956220774182.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 16:41:16,441] Trial 76 finished with value: 0.7077422291709597 and parameters: {'subsample': 0.1621933109439123, 'dropout_rate': 0.10064271403610489, 'n_estimators': 363, 'learning_rate': 0.09404919893163159}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 16:41:25,798] Trial 77 finished with value: 0.6938032885482757 and parameters: {'subsample': 0.2951035205810285, 'dropout_rate': 0.10440159877217844, 'n_estimators': 399, 'learning_rate': 0.09464228408558689}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 16:41:33,806] Trial 78 finished with value: 0.6929979664194241 and parameters: {'subsample': 0.1624349566635479, 'dropout_rate': 0.28362270767234354, 'n_estimators': 371, 'learning_rate': 0.08968754780519873}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 16:41:41,574] Trial 79 finished with value: 0.6938908235622813 and parameters: {'subsample': 0.19947774297593907, 'dropout_rate': 0.1848027308834786, 'n_estimators': 363, 'learning_rate': 0.09759823513118498}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:41:48,149] Trial 80 finished with value: 0.6983522439835429 and parameters: {'subsample': 0.15550831074917026, 'dropout_rate': 0.14551640290417903, 'n_estimators': 332, 'learning_rate': 0.09235280160555125}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 16:41:55,390] Trial 81 finished with value: 0.7105544456068298 and parameters: {'subsample': 0.12933104931221556, 'dropout_rate': 0.10103359806294485, 'n_estimators': 349, 'learning_rate': 0.09008942910298617}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 16:42:02,777] Trial 82 finished with value: 0.7107784909211581 and parameters: {'subsample': 0.13012815999103441, 'dropout_rate': 0.10175673175511836, 'n_estimators': 353, 'learning_rate': 0.0955061043108689}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:42:10,493] Trial 83 finished with value: 0.7000965332485448 and parameters: {'subsample': 0.2235249807412677, 'dropout_rate': 0.10570385198744335, 'n_estimators': 358, 'learning_rate': 0.08944098921734583}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:42:18,834] Trial 84 finished with value: 0.7010769254054076 and parameters: {'subsample': 0.1387727300600159, 'dropout_rate': 0.15450528071865655, 'n_estimators': 377, 'learning_rate': 0.09458351805127078}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:42:28,005] Trial 85 finished with value: 0.7038159755709282 and parameters: {'subsample': 0.1856730498532294, 'dropout_rate': 0.12166088476278845, 'n_estimators': 399, 'learning_rate': 0.09738066686233819}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:42:34,712] Trial 86 finished with value: 0.6873735335476838 and parameters: {'subsample': 0.26327590564123055, 'dropout_rate': 0.21368023110334972, 'n_estimators': 328, 'learning_rate': 0.09043010578639135}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:42:40,806] Trial 87 finished with value: 0.6965740799634332 and parameters: {'subsample': 0.1730831372528218, 'dropout_rate': 0.14678116506499447, 'n_estimators': 318, 'learning_rate': 0.08317420261771254}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:42:50,246] Trial 88 finished with value: 0.7097934137917148 and parameters: {'subsample': 0.12554891348207922, 'dropout_rate': 0.10094823167912124, 'n_estimators': 390, 'learning_rate': 0.09257963152124685}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 16:43:02,498] Trial 89 finished with value: 0.6899184599689566 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.10235579098260814, 'n_estimators': 438, 'learning_rate': 0.09267457674785469}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:43:11,907] Trial 90 finished with value: 0.6965441583933529 and parameters: {'subsample': 0.14896070242203524, 'dropout_rate': 0.19115633484636477, 'n_estimators': 386, 'learning_rate': 0.06614579056733322}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 16:43:21,804] Trial 91 finished with value: 0.7116176878051177 and parameters: {'subsample': 0.12390846758748335, 'dropout_rate': 0.12572913607716735, 'n_estimators': 413, 'learning_rate': 0.09570394311397323}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:43:31,599] Trial 92 finished with value: 0.7059788861897213 and parameters: {'subsample': 0.12474271767060352, 'dropout_rate': 0.1421677119184425, 'n_estimators': 413, 'learning_rate': 0.08070443809531894}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:43:42,064] Trial 93 finished with value: 0.69215121926986 and parameters: {'subsample': 0.20507423427347374, 'dropout_rate': 0.16644710020453718, 'n_estimators': 430, 'learning_rate': 0.08834184976487461}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 16:43:51,243] Trial 94 finished with value: 0.7066743020000914 and parameters: {'subsample': 0.16576191591413314, 'dropout_rate': 0.1260789509040807, 'n_estimators': 390, 'learning_rate': 0.09325178879571827}. Best is trial 12 with value: 0.7134956220774182.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:43:59,721] Trial 95 finished with value: 0.6837145699622498 and parameters: {'subsample': 0.7789769183267152, 'dropout_rate': 0.17549205875164936, 'n_estimators': 370, 'learning_rate': 0.09814528574021013}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 16:44:03,241] Trial 96 finished with value: 0.6930440764127173 and parameters: {'subsample': 0.12691138617324052, 'dropout_rate': 0.9806455021652567, 'n_estimators': 250, 'learning_rate': 0.0906452567536974}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 16:44:11,628] Trial 97 finished with value: 0.6846074271051068 and parameters: {'subsample': 0.612363547521257, 'dropout_rate': 0.22443099991793836, 'n_estimators': 358, 'learning_rate': 0.09567319556448589}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 16:44:17,228] Trial 98 finished with value: 0.6975054968339789 and parameters: {'subsample': 0.15186050916654883, 'dropout_rate': 0.14812461915074668, 'n_estimators': 294, 'learning_rate': 0.08474060237325136}. Best is trial 12 with value: 0.7134956220774182.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697

[I 2024-04-17 16:44:23,348] A new study created in memory with name: no-name-bb5d437b-0955-4151-8f75-2f5e68bb4fb7

Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 16:44:23,325] Trial 99 finished with value: 0.6937157535342701 and parameters: {'subsample': 0.38382516035402403, 'dropout_rate': 0.10033353523975334, 'n_estimators': 311, 'learning_rate': 0.0974962029100855}. Best is trial 12 with value: 0.7134956220774182.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.7134956220774182], datetime_start=datetime.datetime(2024, 4, 17, 16, 35, 2, 711461), datetime_complete=datetime.datetime(2024, 4, 17, 16, 35, 8, 759174), params={'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=12, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}


* Best Score for C-index:
 0.7134956220774182

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24543748741914098
Fold 2 IBS: 0.1405338101856315
Fold 3 IBS: 0.18697326858781385
Fold 4 IBS: 0.16775139091313182
Fold 5 IBS: 0.17827637475993605
[I 2024-04-17 16:44:24,839] Trial 0 finished with value: 0.18379446637313085 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.18379446637313085.
Fold 1 IBS: 0.3157615176698962
Fold 2 IBS: 0.20190722980642198
Fold 3 IBS: 0.2678976054481912
Fold 4 IBS: 0.22991414941715288
Fold 5 IBS: 0.22404939786874414
[I 2024-04-17 16:44:36,290] Trial 1 finished with value: 0.24790598004208125 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.18379446637313085.
Fold 1 IBS: 0.2736129440677976
Fold 2 IBS: 0.15707190816246405
Fold 3 IBS: 0.22879666183542074
Fold 4 IBS: 0.18867264027279448
Fold 5 IBS: 0.19563137215598986
[I 2024-04-17 16:44:38,427] Trial 2 finished with value: 0.20875710529889338 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.18379446637313085.
Fold 1 IBS: 0.2771997655106299
Fold 2 IBS: 0.15729065998827407
Fold 3 IBS: 0.23545382045131766
Fold 4 IBS: 0.1921504200089056
Fold 5 IBS: 0.1982039339432372
[I 2024-04-17 16:44:41,404] Trial 3 finished with value: 0.21205971998047288 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.18379446637313085.
Fold 1 IBS: 0.27768898432062017
Fold 2 IBS: 0.16043831790343865
Fold 3 IBS: 0.23057086243101685
Fold 4 IBS: 0.19045217727963806
Fold 5 IBS: 0.19906339259942757
[I 2024-04-17 16:44:45,720] Trial 4 finished with value: 0.21164274690682827 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.18379446637313085.
Fold 1 IBS: 0.29964122631726436
Fold 2 IBS: 0.1878056773183997
Fold 3 IBS: 0.2574969382796915
Fold 4 IBS: 0.21329821324502493
Fold 5 IBS: 0.2149823601666817
[I 2024-04-17 16:44:50,947] Trial 5 finished with value: 0.23464488306541248 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.18379446637313085.
Fold 1 IBS: 0.23142715981972764
Fold 2 IBS: 0.14020134419639138
Fold 3 IBS: 0.17434091728570247
Fold 4 IBS: 0.16499451502981663
Fold 5 IBS: 0.17255928987989916
[I 2024-04-17 16:44:53,271] Trial 6 finished with value: 0.17670464524230747 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.20863999462061755
Fold 2 IBS: 0.16154257629021015
Fold 3 IBS: 0.1746464096825675
Fold 4 IBS: 0.17739422005849975
Fold 5 IBS: 0.17829129299277888
[I 2024-04-17 16:44:53,823] Trial 7 finished with value: 0.18010289872893476 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.2483266230281813
Fold 2 IBS: 0.1401929849316447
Fold 3 IBS: 0.19251476242547735
Fold 4 IBS: 0.16900467122297533
Fold 5 IBS: 0.1811459477105733
[I 2024-04-17 16:44:56,617] Trial 8 finished with value: 0.1862369978637704 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.30275986043779984
Fold 2 IBS: 0.18701437107825822
Fold 3 IBS: 0.2597240373707255
Fold 4 IBS: 0.21641775686815998
Fold 5 IBS: 0.21614181605549684
[I 2024-04-17 16:45:04,396] Trial 9 finished with value: 0.23641156836208807 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.20772531582303522
Fold 2 IBS: 0.20018154594302628
Fold 3 IBS: 0.1928504517900763
Fold 4 IBS: 0.2078734653595557
Fold 5 IBS: 0.2022046845086669
[I 2024-04-17 16:45:09,315] Trial 10 finished with value: 0.20216709268487207 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 328, 'learning_rate': 0.0017980531969980576}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.21324338103957954
Fold 2 IBS: 0.2187816989920569
Fold 3 IBS: 0.2034669027189844
Fold 4 IBS: 0.22270221433629056
Fold 5 IBS: 0.21688096109805854
[I 2024-04-17 16:45:09,581] Trial 11 finished with value: 0.215015031636994 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.23593916618489372
Fold 2 IBS: 0.13676942893311805
Fold 3 IBS: 0.17886387515530264
Fold 4 IBS: 0.16520550442082588
Fold 5 IBS: 0.17579057351290664
[I 2024-04-17 16:45:10,214] Trial 12 finished with value: 0.1785137096414094 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.2662715463170697
Fold 2 IBS: 0.1508017049605072
Fold 3 IBS: 0.21865672086582724
Fold 4 IBS: 0.18178182923608668
Fold 5 IBS: 0.19212822376816957
[I 2024-04-17 16:45:11,425] Trial 13 finished with value: 0.20192800502953206 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.4001159443378324, 'n_estimators': 109, 'learning_rate': 0.09856277651579823}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.2646974340026183
Fold 2 IBS: 0.15008077807138925
Fold 3 IBS: 0.2175480172891617
Fold 4 IBS: 0.18059003640363347
Fold 5 IBS: 0.19159744867706086
[I 2024-04-17 16:45:12,514] Trial 14 finished with value: 0.20090274288877272 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 102, 'learning_rate': 0.09964553963945819}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.20879336506072377
Fold 2 IBS: 0.21008675821516737
Fold 3 IBS: 0.19624893046532058
Fold 4 IBS: 0.21414452036339848
Fold 5 IBS: 0.21062775173218778
[I 2024-04-17 16:45:13,140] Trial 15 finished with value: 0.2079802651673596 and parameters: {'subsample': 0.10294255497547983, 'dropout_rate': 0.29557448514938967, 'n_estimators': 49, 'learning_rate': 0.00882614648800595}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.24006317304091596
Fold 2 IBS: 0.13626023399449894
Fold 3 IBS: 0.1800888531770764
Fold 4 IBS: 0.16582142970456173
Fold 5 IBS: 0.17693952924383008
[I 2024-04-17 16:45:16,526] Trial 16 finished with value: 0.1798346438321766 and parameters: {'subsample': 0.29391461974521166, 'dropout_rate': 0.7899949638176231, 'n_estimators': 271, 'learning_rate': 0.02047377291427832}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.27113815957075044
Fold 2 IBS: 0.15038876996909303
Fold 3 IBS: 0.22588725612476018
Fold 4 IBS: 0.18522616321613544
Fold 5 IBS: 0.19500088993059858
[I 2024-04-17 16:45:18,599] Trial 17 finished with value: 0.20552824776226752 and parameters: {'subsample': 0.6340507845187373, 'dropout_rate': 0.10421921753457947, 'n_estimators': 165, 'learning_rate': 0.08223463771239999}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.21045951245541303
Fold 2 IBS: 0.21032766773669437
Fold 3 IBS: 0.198123007755858
Fold 4 IBS: 0.2157768849156953
Fold 5 IBS: 0.2102550113099756
[I 2024-04-17 16:45:18,903] Trial 18 finished with value: 0.20898841683472727 and parameters: {'subsample': 0.8187174952613757, 'dropout_rate': 0.5643051003990627, 'n_estimators': 7, 'learning_rate': 0.04217501697666381}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.3073097658358001

Fold 2 IBS: 0.17864957876196913
Fold 3 IBS: 0.26166561006271827
Fold 4 IBS: 0.2201305954349429
Fold 5 IBS: 0.21615036620181424
[I 2024-04-17 16:45:24,462] Trial 19 finished with value: 0.23678118325944894 and parameters: {'subsample': 0.38793667853472646, 'dropout_rate': 0.22827203020188386, 'n_estimators': 324, 'learning_rate': 0.08697733590757546}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.21460957699186584
Fold 2 IBS: 0.15203436467055678
Fold 3 IBS: 0.17224234724087079
Fold 4 IBS: 0.17149898083734882
Fold 5 IBS: 0.17345777825397396
[I 2024-04-17 16:45:26,075] Trial 20 finished with value: 0.17676860959892324 and parameters: {'subsample': 0.6102628884762309, 'dropout_rate': 0.5558690358940764, 'n_estimators': 149, 'learning_rate': 0.017331004877487094}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.21318490797122427
Fold 2 IBS: 0.15475321350865665
Fold 3 IBS: 0.1731329507408618
Fold 4 IBS: 0.17295939262836466
Fold 5 IBS: 0.17437814582988778
[I 2024-04-17 16:45:27,491] Trial 21 finished with value: 0.17768172213579903 and parameters: {'subsample': 0.6165496196241105, 'dropout_rate': 0.9754161103921428, 'n_estimators': 142, 'learning_rate': 0.016867151673453804}. Best is trial 6 with value: 0.17670464524230747.
Fold 1 IBS: 0.2242997157515352
Fold 2 IBS: 0.14354645673711794
Fold 3 IBS: 0.17184625963844227
Fold 4 IBS: 0.1664477563286043
Fold 5 IBS: 0.1717520710333597
[I 2024-04-17 16:45:29,930] Trial 22 finished with value: 0.1755784518978119 and parameters: {'subsample': 0.637312396919241, 'dropout_rate': 0.9832511198723066, 'n_estimators': 221, 'learning_rate': 0.01557109179501204}. Best is trial 22 with value: 0.1755784518978119.
Fold 1 IBS: 0.25110781075056304
Fold 2 IBS: 0.14235482172782263
Fold 3 IBS: 0.1953334807296709
Fold 4 IBS: 0.17046763584089888
Fold 5 IBS: 0.18296656440375952
[I 2024-04-17 16:45:32,775] Trial 23 finished with value: 0.188446062690543 and parameters: {'subsample': 0.8112423090302406, 'dropout_rate': 0.37293535681418793, 'n_estimators': 220, 'learning_rate': 0.03310431104757328}. Best is trial 22 with value: 0.1755784518978119.
Fold 1 IBS: 0.22636308841989666
Fold 2 IBS: 0.142154873630937
Fold 3 IBS: 0.17231641213836943
Fold 4 IBS: 0.1657729450785895
Fold 5 IBS: 0.17183979465462493
[I 2024-04-17 16:45:35,464] Trial 24 finished with value: 0.17568942278448352 and parameters: {'subsample': 0.5954984634734557, 'dropout_rate': 0.9859451830394055, 'n_estimators': 252, 'learning_rate': 0.01448783706935496}. Best is trial 22 with value: 0.1755784518978119.
Fold 1 IBS: 0.21393570298103468
Fold 2 IBS: 0.15348400859929853
Fold 3 IBS: 0.17275438486522565
Fold 4 IBS: 0.17220824562050757
Fold 5 IBS: 0.1741588400137992
[I 2024-04-17 16:45:38,757] Trial 25 finished with value: 0.17730823641597313 and parameters: {'subsample': 0.7320627570787249, 'dropout_rate': 0.9916995260298861, 'n_estimators': 291, 'learning_rate': 0.008500348756543277}. Best is trial 22 with value: 0.1755784518978119.
Fold 1 IBS: 0.2643530220090812
Fold 2 IBS: 0.14995713457258758
Fold 3 IBS: 0.21611087025239847
Fold 4 IBS: 0.1801693650080918
Fold 5 IBS: 0.1914806257142286
[I 2024-04-17 16:45:44,428] Trial 26 finished with value: 0.20041420351127753 and parameters: {'subsample': 0.8884184224793716, 'dropout_rate': 0.8431258169529487, 'n_estimators': 392, 'learning_rate': 0.025444778839443953}. Best is trial 22 with value: 0.1755784518978119.
Fold 1 IBS: 0.2094687830537356
Fold 2 IBS: 0.20723250162787044
Fold 3 IBS: 0.1966661215598729
Fold 4 IBS: 0.21360502222314964
Fold 5 IBS: 0.20737266606986127
[I 2024-04-17 16:45:46,812] Trial 27 finished with value: 0.20686901890689793 and parameters: {'subsample': 0.5910572852733517, 'dropout_rate': 0.9616696052542918, 'n_estimators': 221, 'learning_rate': 0.0017614966933636959}. Best is trial 22 with value: 0.1755784518978119.
Fold 1 IBS: 0.2578934946279376
Fold 2 IBS: 0.14563145026371158
Fold 3 IBS: 0.20603218627075062
Fold 4 IBS: 0.17507397675403327
Fold 5 IBS: 0.18742573886243366
[I 2024-04-17 16:45:49,636] Trial 28 finished with value: 0.19441136935577333 and parameters: {'subsample': 0.6979357816206372, 'dropout_rate': 0.8057005308369737, 'n_estimators': 241, 'learning_rate': 0.03545838957871889}. Best is trial 22 with value: 0.1755784518978119.
Fold 1 IBS: 0.2220469475799799
Fold 2 IBS: 0.14496246012265981
Fold 3 IBS: 0.17166231162406828
Fold 4 IBS: 0.16703293281052767
Fold 5 IBS: 0.1718486743247899
[I 2024-04-17 16:45:53,374] Trial 29 finished with value: 0.1755106652924051 and parameters: {'subsample': 0.7857505125766191, 'dropout_rate': 0.9274030360741924, 'n_estimators': 311, 'learning_rate': 0.010431917245654097}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2290954478577545
Fold 2 IBS: 0.14065898374108143
Fold 3 IBS: 0.17371811323940803
Fold 4 IBS: 0.16517938256645362
Fold 5 IBS: 0.17229198427711703
[I 2024-04-17 16:45:59,240] Trial 30 finished with value: 0.1761887823363629 and parameters: {'subsample': 0.5505664343378067, 'dropout_rate': 0.9143610608584156, 'n_estimators': 415, 'learning_rate': 0.009668404738741998}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.23548319588735686
Fold 2 IBS: 0.13891415411496838
Fold 3 IBS: 0.17725649446040134
Fold 4 IBS: 0.16508735102935929
Fold 5 IBS: 0.17405796026299059
[I 2024-04-17 16:46:05,757] Trial 31 finished with value: 0.1781598311510153 and parameters: {'subsample': 0.5412532361873578, 'dropout_rate': 0.9191592028182312, 'n_estimators': 436, 'learning_rate': 0.010895341865255391}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2401220018822294
Fold 2 IBS: 0.13811421001658594
Fold 3 IBS: 0.18199038035289794
Fold 4 IBS: 0.16587394238314634
Fold 5 IBS: 0.176538336416309
[I 2024-04-17 16:46:11,213] Trial 32 finished with value: 0.18052777421023375 and parameters: {'subsample': 0.4068628433881887, 'dropout_rate': 0.9135648839998726, 'n_estimators': 386, 'learning_rate': 0.014315456103459467}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.20945133338040675
Fold 2 IBS: 0.16113206733310803
Fold 3 IBS: 0.17503842067047687
Fold 4 IBS: 0.17768120465141324
Fold 5 IBS: 0.17761771491820713
[I 2024-04-17 16:46:15,213] Trial 33 finished with value: 0.1801841481907224 and parameters: {'subsample': 0.7855767105539486, 'dropout_rate': 0.7941197951164535, 'n_estimators': 306, 'learning_rate': 0.006578705865729413}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.24205378882958936
Fold 2 IBS: 0.139724922010222
Fold 3 IBS: 0.18311641858620187
Fold 4 IBS: 0.16629625784852484
Fold 5 IBS: 0.1772675893203264
[I 2024-04-17 16:46:21,461] Trial 34 finished with value: 0.1816917953189729 and parameters: {'subsample': 0.6633031657379367, 'dropout_rate': 0.9408608198597097, 'n_estimators': 433, 'learning_rate': 0.013055048392216231}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2516769955361262
Fold 2 IBS: 0.14246003699057536
Fold 3 IBS: 0.19591802163542651
Fold 4 IBS: 0.1708644189568643
Fold 5 IBS: 0.18312068958330394
[I 2024-04-17 16:46:26,028] Trial 35 finished with value: 0.18880803254045928 and parameters: {'subsample': 0.5675661383369696, 'dropout_rate': 0.9999681317784256, 'n_estimators': 354, 'learning_rate': 0.020546163603378954}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.20538762944247327
Fold 2 IBS: 0.18015220002474042
Fold 3 IBS: 0.1825524458232508
Fold 4 IBS: 0.191606433664109
Fold 5 IBS: 0.18860625116935745
[I 2024-04-17 16:46:29,259] Trial 36 finished with value: 0.1896609920247862 and parameters: {'subsample': 0.4514725871892843, 'dropout_rate': 0.8692393080564307, 'n_estimators': 261, 'learning_rate': 0.004828719279422358}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.3066384105678845
Fold 2 IBS: 0.19411064266270375
Fold 3 IBS: 0.26222054871533695
Fold 4 IBS: 0.22039361168945013
Fold 5 IBS: 0.21926931221599716
[I 2024-04-17 16:46:36,422] Trial 37 finished with value: 0.24052650517027452 and parameters: {'subsample': 0.6989172971100809, 'dropout_rate': 0.8374055765137145, 'n_estimators': 440, 'learning_rate': 0.059207327336158105}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2950049780615895

Fold 2 IBS: 0.1816061154024669
Fold 3 IBS: 0.2540361428973788
Fold 4 IBS: 0.20902566039470935
Fold 5 IBS: 0.21104928161932168
[I 2024-04-17 16:46:45,226] Trial 38 finished with value: 0.23014443567509324 and parameters: {'subsample': 0.525489298855873, 'dropout_rate': 0.7592515401114239, 'n_estimators': 492, 'learning_rate': 0.04117059612157671}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.26527484844671456
Fold 2 IBS: 0.15047213618254998
Fold 3 IBS: 0.21754707587700448
Fold 4 IBS: 0.18073341212504015
Fold 5 IBS: 0.19187243117143413
[I 2024-04-17 16:46:49,868] Trial 39 finished with value: 0.20117998076054863 and parameters: {'subsample': 0.7558079539823906, 'dropout_rate': 0.8890898259545601, 'n_estimators': 353, 'learning_rate': 0.028863709537211436}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.229163612652874
Fold 2 IBS: 0.14092389806545633
Fold 3 IBS: 0.1731926585867215
Fold 4 IBS: 0.16527603623773815
Fold 5 IBS: 0.17221215834324385
[I 2024-04-17 16:46:51,735] Trial 40 finished with value: 0.17615367277720678 and parameters: {'subsample': 0.661549123059024, 'dropout_rate': 0.941104583175129, 'n_estimators': 188, 'learning_rate': 0.02105299259227386}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22904056069023604
Fold 2 IBS: 0.1409656886336985
Fold 3 IBS: 0.17312898646281866
Fold 4 IBS: 0.16528792761800667
Fold 5 IBS: 0.1721894118933866
[I 2024-04-17 16:46:53,642] Trial 41 finished with value: 0.17612251505962928 and parameters: {'subsample': 0.6542661288650128, 'dropout_rate': 0.9486201637755585, 'n_estimators': 188, 'learning_rate': 0.02097046727914029}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22967644933012074
Fold 2 IBS: 0.14074093556384984
Fold 3 IBS: 0.17340160816631436
Fold 4 IBS: 0.1652079886138159
Fold 5 IBS: 0.1723094466343085
[I 2024-04-17 16:46:55,570] Trial 42 finished with value: 0.17626728566168187 and parameters: {'subsample': 0.6661128961332728, 'dropout_rate': 0.9485888122496814, 'n_estimators': 189, 'learning_rate': 0.02123917718609718}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22690430873081435
Fold 2 IBS: 0.14198246883204493
Fold 3 IBS: 0.17247929457418615
Fold 4 IBS: 0.16563116451858959
Fold 5 IBS: 0.1718798532214672
[I 2024-04-17 16:46:58,241] Trial 43 finished with value: 0.17577541797542046 and parameters: {'subsample': 0.6963794735376584, 'dropout_rate': 0.9968921250779946, 'n_estimators': 239, 'learning_rate': 0.015596804269515098}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22717907510282195
Fold 2 IBS: 0.1416320317830338
Fold 3 IBS: 0.17286459477479132
Fold 4 IBS: 0.1654993255290065
Fold 5 IBS: 0.17192997425211604
[I 2024-04-17 16:47:01,135] Trial 44 finished with value: 0.17582100028835393 and parameters: {'subsample': 0.7763685416532411, 'dropout_rate': 0.8592972652356786, 'n_estimators': 248, 'learning_rate': 0.015189064044544426}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2603906141348798
Fold 2 IBS: 0.1468735559078013
Fold 3 IBS: 0.20909536860047728
Fold 4 IBS: 0.17671934781916054
Fold 5 IBS: 0.18893323558924507
[I 2024-04-17 16:47:03,728] Trial 45 finished with value: 0.1964024244103128 and parameters: {'subsample': 0.8637977557416442, 'dropout_rate': 0.9979313258156364, 'n_estimators': 242, 'learning_rate': 0.037329267737742845}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.23234789018564178
Fold 2 IBS: 0.13997325717226047
Fold 3 IBS: 0.17547488458486432
Fold 4 IBS: 0.16496007188704045
Fold 5 IBS: 0.1730162066542154
[I 2024-04-17 16:47:07,291] Trial 46 finished with value: 0.1771544620968045 and parameters: {'subsample': 0.7188080555928051, 'dropout_rate': 0.8727376221835748, 'n_estimators': 283, 'learning_rate': 0.01544680608958179}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2514176445884138
Fold 2 IBS: 0.1425633476645523
Fold 3 IBS: 0.1964160657486998
Fold 4 IBS: 0.17090288739155254
Fold 5 IBS: 0.18342832628670602
[I 2024-04-17 16:47:10,137] Trial 47 finished with value: 0.18894565433598492 and parameters: {'subsample': 0.9152071145455637, 'dropout_rate': 0.8351859782364506, 'n_estimators': 242, 'learning_rate': 0.030077849133222045}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2954669954678399
Fold 2 IBS: 0.18366682347749516
Fold 3 IBS: 0.2543662497830588
Fold 4 IBS: 0.20918975380044763
Fold 5 IBS: 0.21202739944404522
[I 2024-04-17 16:47:14,203] Trial 48 finished with value: 0.2309434443945773 and parameters: {'subsample': 0.8006597710759349, 'dropout_rate': 0.7596951083905511, 'n_estimators': 303, 'learning_rate': 0.06708859300433782}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.20535993925610985
Fold 2 IBS: 0.18239107513866054
Fold 3 IBS: 0.18418749802169768
Fold 4 IBS: 0.19381834409845847
Fold 5 IBS: 0.18995044180828075
[I 2024-04-17 16:47:17,192] Trial 49 finished with value: 0.19114145966464147 and parameters: {'subsample': 0.7651529105520385, 'dropout_rate': 0.4528296068001064, 'n_estimators': 220, 'learning_rate': 0.00524351186486742}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2570293561623635
Fold 2 IBS: 0.14522877175373475
Fold 3 IBS: 0.2048888445559342
Fold 4 IBS: 0.1744266875908166
Fold 5 IBS: 0.1870059905149995
[I 2024-04-17 16:47:21,553] Trial 50 finished with value: 0.1937159301155697 and parameters: {'subsample': 0.8378438668107311, 'dropout_rate': 0.8857718163580371, 'n_estimators': 331, 'learning_rate': 0.025274624223263785}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.21412258815385457
Fold 2 IBS: 0.15325040422687536
Fold 3 IBS: 0.17279920415803643
Fold 4 IBS: 0.1724484438901362
Fold 5 IBS: 0.174050172015507
[I 2024-04-17 16:47:23,688] Trial 51 finished with value: 0.17733416248888192 and parameters: {'subsample': 0.6402932427066074, 'dropout_rate': 0.9537786085960437, 'n_estimators': 206, 'learning_rate': 0.012054434764812843}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.23621161425232803
Fold 2 IBS: 0.13952156916954556
Fold 3 IBS: 0.1776433092777302
Fold 4 IBS: 0.16511592522436935
Fold 5 IBS: 0.17434719960987455
[I 2024-04-17 16:47:26,679] Trial 52 finished with value: 0.17856792350676953 and parameters: {'subsample': 0.6992122371080971, 'dropout_rate': 0.9262339742407725, 'n_estimators': 260, 'learning_rate': 0.018532993522334385}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22884030839680908
Fold 2 IBS: 0.14102091082599572
Fold 3 IBS: 0.1731608780183437
Fold 4 IBS: 0.16522281166397876
Fold 5 IBS: 0.17219246253477982
[I 2024-04-17 16:47:28,291] Trial 53 finished with value: 0.1760874742879814 and parameters: {'subsample': 0.7610300396419557, 'dropout_rate': 0.9680251646114105, 'n_estimators': 165, 'learning_rate': 0.02387649559822652}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2506278270585653
Fold 2 IBS: 0.1421573904349426
Fold 3 IBS: 0.19425758608504723
Fold 4 IBS: 0.1702594014536769
Fold 5 IBS: 0.1829591073971292
[I 2024-04-17 16:47:29,992] Trial 54 finished with value: 0.18805226248587223 and parameters: {'subsample': 0.7697474923818121, 'dropout_rate': 0.9750542713529474, 'n_estimators': 152, 'learning_rate': 0.04660146298026138}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22874613218937728
Fold 2 IBS: 0.1409348551873404
Fold 3 IBS: 0.17353751245318388
Fold 4 IBS: 0.1652763753514127
Fold 5 IBS: 0.17220418985582395
[I 2024-04-17 16:47:33,436] Trial 55 finished with value: 0.17613981300742765 and parameters: {'subsample': 0.5947514259815363, 'dropout_rate': 0.8955284466930257, 'n_estimators': 283, 'learning_rate': 0.014029469023228953}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.21291755432279633
Fold 2 IBS: 0.2184375082915841
Fold 3 IBS: 0.2027749061453062
Fold 4 IBS: 0.2222598203673667
Fold 5 IBS: 0.21572478834363204
[I 2024-04-17 16:47:34,245] Trial 56 finished with value: 0.21442291549413706 and parameters: {'subsample': 0.731713659414502, 'dropout_rate': 0.9983717785297445, 'n_estimators': 83, 'learning_rate': 0.0010087351570029265}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.23176005144576747
Fold 2 IBS: 0.14011089989305936

Fold 3 IBS: 0.17509139432661858
Fold 4 IBS: 0.16496597424322587
Fold 5 IBS: 0.17289856346959426
[I 2024-04-17 16:47:36,095] Trial 57 finished with value: 0.1769653766756531 and parameters: {'subsample': 0.96492509495326, 'dropout_rate': 0.8251715381087623, 'n_estimators': 175, 'learning_rate': 0.02458639392990227}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.20567506841359517
Fold 2 IBS: 0.1754507394590557
Fold 3 IBS: 0.1807971692927999
Fold 4 IBS: 0.18821099956298334
Fold 5 IBS: 0.18538568611262302
[I 2024-04-17 16:47:38,834] Trial 58 finished with value: 0.18710393256821142 and parameters: {'subsample': 0.8995542733815092, 'dropout_rate': 0.8547461907712806, 'n_estimators': 233, 'learning_rate': 0.005999698403657619}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.23409900493697242
Fold 2 IBS: 0.13964613861471284
Fold 3 IBS: 0.1766724220851995
Fold 4 IBS: 0.16499514157855344
Fold 5 IBS: 0.17362095292993807
[I 2024-04-17 16:47:42,495] Trial 59 finished with value: 0.17780673202907527 and parameters: {'subsample': 0.8415678154063193, 'dropout_rate': 0.7029820695798581, 'n_estimators': 273, 'learning_rate': 0.01679386498386604}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.2203182131534261
Fold 2 IBS: 0.14622611761389706
Fold 3 IBS: 0.17159735700825787
Fold 4 IBS: 0.16783576623089966
Fold 5 IBS: 0.17204690915529014
[I 2024-04-17 16:47:46,927] Trial 60 finished with value: 0.17560487263235416 and parameters: {'subsample': 0.6953234557226419, 'dropout_rate': 0.6121214744948075, 'n_estimators': 310, 'learning_rate': 0.009979679638089253}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.20541083164260285
Fold 2 IBS: 0.17903136650564921
Fold 3 IBS: 0.1821601181850118
Fold 4 IBS: 0.19081013783468412
Fold 5 IBS: 0.18717287498760052
[I 2024-04-17 16:47:48,409] Trial 61 finished with value: 0.1889170658311097 and parameters: {'subsample': 0.7190765250632887, 'dropout_rate': 0.6506337176922956, 'n_estimators': 129, 'learning_rate': 0.009924076411227355}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22815824369147117
Fold 2 IBS: 0.14129109870124715
Fold 3 IBS: 0.17317843874004732
Fold 4 IBS: 0.16533724511102602
Fold 5 IBS: 0.17205369794407863
[I 2024-04-17 16:47:53,113] Trial 62 finished with value: 0.17600374483757406 and parameters: {'subsample': 0.6944643999465044, 'dropout_rate': 0.5862098584550022, 'n_estimators': 313, 'learning_rate': 0.012420254077174704}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.20554585526916516
Fold 2 IBS: 0.1771018357462107
Fold 3 IBS: 0.18171384301535012
Fold 4 IBS: 0.18961826165007167
Fold 5 IBS: 0.18644037254103935
[I 2024-04-17 16:47:58,435] Trial 63 finished with value: 0.18808403364436738 and parameters: {'subsample': 0.6182349561142566, 'dropout_rate': 0.4516671118247977, 'n_estimators': 324, 'learning_rate': 0.00412777296900681}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22442420194239432
Fold 2 IBS: 0.14321680027824737
Fold 3 IBS: 0.17204251353486247
Fold 4 IBS: 0.16620458633793164
Fold 5 IBS: 0.17175270693021272
[I 2024-04-17 16:48:03,254] Trial 64 finished with value: 0.1755281618047297 and parameters: {'subsample': 0.6868003393434807, 'dropout_rate': 0.5221502506243636, 'n_estimators': 309, 'learning_rate': 0.011313921676156278}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.21037262354382108
Fold 2 IBS: 0.159281200271832
Fold 3 IBS: 0.17433289272760122
Fold 4 IBS: 0.17640159727310303
Fold 5 IBS: 0.1766615653167616
[I 2024-04-17 16:48:07,950] Trial 65 finished with value: 0.1794099758266238 and parameters: {'subsample': 0.576735595353071, 'dropout_rate': 0.508123904575333, 'n_estimators': 292, 'learning_rate': 0.007330255030153264}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.23227474311371413
Fold 2 IBS: 0.13925258430791126
Fold 3 IBS: 0.17537025705437007
Fold 4 IBS: 0.16496478271718362
Fold 5 IBS: 0.17298346428264036
[I 2024-04-17 16:48:11,431] Trial 66 finished with value: 0.17696916629516388 and parameters: {'subsample': 0.5155211276050521, 'dropout_rate': 0.5310938799111113, 'n_estimators': 253, 'learning_rate': 0.01733823699818149}. Best is trial 29 with value: 0.1755106652924051.
Fold 1 IBS: 0.22318428071470423
Fold 2 IBS: 0.14399227754809113
Fold 3 IBS: 0.17185162284262015
Fold 4 IBS: 0.1666448522108369
Fold 5 IBS: 0.17176662129168083
[I 2024-04-17 16:48:17,096] Trial 67 finished with value: 0.17548793092158665 and parameters: {'subsample': 0.6310778902466356, 'dropout_rate': 0.5884682743769717, 'n_estimators': 347, 'learning_rate': 0.009757789452695311}. Best is trial 67 with value: 0.17548793092158665.
Fold 1 IBS: 0.22421272131780165
Fold 2 IBS: 0.142762407115212
Fold 3 IBS: 0.1719530106661353
Fold 4 IBS: 0.1662772863022148
Fold 5 IBS: 0.17206609938560036
[I 2024-04-17 16:48:23,569] Trial 68 finished with value: 0.17545430495739284 and parameters: {'subsample': 0.476140125399786, 'dropout_rate': 0.5942005075381153, 'n_estimators': 371, 'learning_rate': 0.009488948096395217}. Best is trial 68 with value: 0.17545430495739284.
Fold 1 IBS: 0.22723608633101505
Fold 2 IBS: 0.14098604583947366
Fold 3 IBS: 0.17247519382652046
Fold 4 IBS: 0.16557691730745444
Fold 5 IBS: 0.17204452525276973
[I 2024-04-17 16:48:31,487] Trial 69 finished with value: 0.17566375371144666 and parameters: {'subsample': 0.45722606795855614, 'dropout_rate': 0.4846293886190308, 'n_estimators': 368, 'learning_rate': 0.010354733373124245}. Best is trial 68 with value: 0.17545430495739284.
Fold 1 IBS: 0.2191753341189961
Fold 2 IBS: 0.14653319059639663
Fold 3 IBS: 0.17141336632263576
Fold 4 IBS: 0.16843768693806402
Fold 5 IBS: 0.17273085149723133
[I 2024-04-17 16:48:37,985] Trial 70 finished with value: 0.17565808589466475 and parameters: {'subsample': 0.4274734731136844, 'dropout_rate': 0.5843241875012491, 'n_estimators': 371, 'learning_rate': 0.008227552186261713}. Best is trial 68 with value: 0.17545430495739284.
Fold 1 IBS: 0.22385491619372325
Fold 2 IBS: 0.14294455933077738
Fold 3 IBS: 0.17188687024847982
Fold 4 IBS: 0.16639960013280355
Fold 5 IBS: 0.1720439057867743
[I 2024-04-17 16:48:44,229] Trial 71 finished with value: 0.17542597033851165 and parameters: {'subsample': 0.4643924082564528, 'dropout_rate': 0.6006316310099185, 'n_estimators': 372, 'learning_rate': 0.009371584699345254}. Best is trial 71 with value: 0.17542597033851165.
Fold 1 IBS: 0.20537757279483007
Fold 2 IBS: 0.17994386108969238
Fold 3 IBS: 0.18261828278799833
Fold 4 IBS: 0.19195724092213912
Fold 5 IBS: 0.1888865627414889
[I 2024-04-17 16:48:50,768] Trial 72 finished with value: 0.18975670406722975 and parameters: {'subsample': 0.4173954109486725, 'dropout_rate': 0.6022877133330322, 'n_estimators': 386, 'learning_rate': 0.0032720642719625513}. Best is trial 71 with value: 0.17542597033851165.
Fold 1 IBS: 0.21520840777530367
Fold 2 IBS: 0.1514164644408612
Fold 3 IBS: 0.17182101669780353
Fold 4 IBS: 0.1712191003302043
Fold 5 IBS: 0.17501607486796206
[I 2024-04-17 16:48:56,181] Trial 73 finished with value: 0.17693621282242694 and parameters: {'subsample': 0.3375578452122586, 'dropout_rate': 0.6296669843408516, 'n_estimators': 346, 'learning_rate': 0.007720922219382392}. Best is trial 71 with value: 0.17542597033851165.
Fold 1 IBS: 0.22478907612792248
Fold 2 IBS: 0.14155745681300744
Fold 3 IBS: 0.1698727189529701
Fold 4 IBS: 0.16630546471590388
Fold 5 IBS: 0.1734068792424261
[I 2024-04-17 16:49:03,715] Trial 74 finished with value: 0.175186319170446 and parameters: {'subsample': 0.22537252419144232, 'dropout_rate': 0.5791496160294716, 'n_estimators': 411, 'learning_rate': 0.008905079139999657}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.23417697284974462
Fold 2 IBS: 0.13664270813924037
Fold 3 IBS: 0.17383800016404474
Fold 4 IBS: 0.16472326259085335
Fold 5 IBS: 0.17437489517452262
[I 2024-04-17 16:49:11,502] Trial 75 finished with value: 0.17675116778368113 and parameters: {'subsample': 0.2606374960205483, 'dropout_rate': 0.4203137318908757, 'n_estimators': 407, 'learning_rate': 0.011399784777526505}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.20576257633347045
Fold 2 IBS: 0.18892384889470792

Fold 3 IBS: 0.1869284710217294
Fold 4 IBS: 0.1989285447631815
Fold 5 IBS: 0.19451667349807425
[I 2024-04-17 16:49:17,155] Trial 76 finished with value: 0.1950120229022327 and parameters: {'subsample': 0.5015222453077708, 'dropout_rate': 0.5299478773071792, 'n_estimators': 341, 'learning_rate': 0.0027779562936136393}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.2553470639685611
Fold 2 IBS: 0.14008958962779353
Fold 3 IBS: 0.19022108651736022
Fold 4 IBS: 0.17026980953216966
Fold 5 IBS: 0.19279670916022976
[I 2024-04-17 16:49:25,660] Trial 77 finished with value: 0.18974485176122285 and parameters: {'subsample': 0.13666979131481322, 'dropout_rate': 0.6722323033044297, 'n_estimators': 459, 'learning_rate': 0.019440814750300062}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.21683329566249418
Fold 2 IBS: 0.15072164418999306
Fold 3 IBS: 0.17055564345481652
Fold 4 IBS: 0.1703049714714073
Fold 5 IBS: 0.1750120026120774
[I 2024-04-17 16:49:33,088] Trial 78 finished with value: 0.1766855114781577 and parameters: {'subsample': 0.2392746789855642, 'dropout_rate': 0.6121622872252206, 'n_estimators': 410, 'learning_rate': 0.006859474654913551}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.3107525202091441
Fold 2 IBS: 0.18885503616369284
Fold 3 IBS: 0.2642014011363007
Fold 4 IBS: 0.2242449069687491
Fold 5 IBS: 0.2197295724083119
[I 2024-04-17 16:49:39,745] Trial 79 finished with value: 0.24155668737723973 and parameters: {'subsample': 0.3717913364541795, 'dropout_rate': 0.5024650704341913, 'n_estimators': 378, 'learning_rate': 0.07928761288306473}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.23375463216035136
Fold 2 IBS: 0.13905304566660054
Fold 3 IBS: 0.17598173775725398
Fold 4 IBS: 0.1649674052443508
Fold 5 IBS: 0.17350807366006046
[I 2024-04-17 16:49:46,132] Trial 80 finished with value: 0.17745297889772343 and parameters: {'subsample': 0.47168706390324106, 'dropout_rate': 0.33755895169352984, 'n_estimators': 361, 'learning_rate': 0.012658251252041517}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.22799412089301682
Fold 2 IBS: 0.14126818577202577
Fold 3 IBS: 0.17317078582117107
Fold 4 IBS: 0.16538839078942233
Fold 5 IBS: 0.17204883172563842
[I 2024-04-17 16:49:52,823] Trial 81 finished with value: 0.1759740630002549 and parameters: {'subsample': 0.6286798046184252, 'dropout_rate': 0.5632934362495964, 'n_estimators': 395, 'learning_rate': 0.009838103922682076}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.21770363666724213
Fold 2 IBS: 0.14807657185645906
Fold 3 IBS: 0.17152748545151378
Fold 4 IBS: 0.16932802928492072
Fold 5 IBS: 0.17317864652798365
[I 2024-04-17 16:49:59,141] Trial 82 finished with value: 0.17596287395762386 and parameters: {'subsample': 0.4309164884621165, 'dropout_rate': 0.5778254136977031, 'n_estimators': 373, 'learning_rate': 0.007799605673278505}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.20556241516876048
Fold 2 IBS: 0.17659568655504918
Fold 3 IBS: 0.18121725026884195
Fold 4 IBS: 0.18915870775949423
Fold 5 IBS: 0.18612371572769507
[I 2024-04-17 16:50:06,538] Trial 83 finished with value: 0.1877315550959682 and parameters: {'subsample': 0.5539629771983925, 'dropout_rate': 0.6421886730626755, 'n_estimators': 426, 'learning_rate': 0.003201026465765638}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.20557436833171466
Fold 2 IBS: 0.17627412548395152
Fold 3 IBS: 0.1792023436062308
Fold 4 IBS: 0.18766703114019462
Fold 5 IBS: 0.1871334762661355
[I 2024-04-17 16:50:11,624] Trial 84 finished with value: 0.18717026896564543 and parameters: {'subsample': 0.21465418499497835, 'dropout_rate': 0.6981768351508916, 'n_estimators': 319, 'learning_rate': 0.004760690092542802}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.21807990283549086
Fold 2 IBS: 0.1475589639663729
Fold 3 IBS: 0.17127549458635977
Fold 4 IBS: 0.16914006597330802
Fold 5 IBS: 0.17367488468576806
[I 2024-04-17 16:50:17,007] Trial 85 finished with value: 0.17594586240945992 and parameters: {'subsample': 0.3499070610936068, 'dropout_rate': 0.5852124106309645, 'n_estimators': 340, 'learning_rate': 0.008662746936343127}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.23641625574678968
Fold 2 IBS: 0.13862695195591085
Fold 3 IBS: 0.17857402181491233
Fold 4 IBS: 0.1651781782858425
Fold 5 IBS: 0.17476598935540383
[I 2024-04-17 16:50:22,923] Trial 86 finished with value: 0.17871227943177184 and parameters: {'subsample': 0.4813379894780069, 'dropout_rate': 0.5505020114356582, 'n_estimators': 356, 'learning_rate': 0.013955682407338405}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.24944415631190694
Fold 2 IBS: 0.13749250583287018
Fold 3 IBS: 0.18729687007480952
Fold 4 IBS: 0.16762868548055454
Fold 5 IBS: 0.18526200807957882
[I 2024-04-17 16:50:29,987] Trial 87 finished with value: 0.18542484515594398 and parameters: {'subsample': 0.1846823016660744, 'dropout_rate': 0.6682436593230737, 'n_estimators': 401, 'learning_rate': 0.018427588121668052}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.2267032305581089
Fold 2 IBS: 0.1419155408721995
Fold 3 IBS: 0.1726544898835415
Fold 4 IBS: 0.1656254196503341
Fold 5 IBS: 0.17187470385163092
[I 2024-04-17 16:50:35,468] Trial 88 finished with value: 0.175754676963163 and parameters: {'subsample': 0.6776067801195832, 'dropout_rate': 0.6114539643815001, 'n_estimators': 335, 'learning_rate': 0.0111342862908453}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.20732348067971806
Fold 2 IBS: 0.1991495985548526
Fold 3 IBS: 0.1918052816753586
Fold 4 IBS: 0.20649983982569722
Fold 5 IBS: 0.20146690951271184
[I 2024-04-17 16:50:45,517] Trial 89 finished with value: 0.20124902204966766 and parameters: {'subsample': 0.43985906846893874, 'dropout_rate': 0.19302419427878476, 'n_estimators': 456, 'learning_rate': 0.0014128534689924477}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.2609020546178341
Fold 2 IBS: 0.1456219412190388
Fold 3 IBS: 0.21040180457079408
Fold 4 IBS: 0.17726849121878063
Fold 5 IBS: 0.18920306424729805
[I 2024-04-17 16:50:52,528] Trial 90 finished with value: 0.19667947117474913 and parameters: {'subsample': 0.39284008349341526, 'dropout_rate': 0.7470809649551995, 'n_estimators': 422, 'learning_rate': 0.022132926571482348}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.225217211703496
Fold 2 IBS: 0.1421116836472144
Fold 3 IBS: 0.17212372753190935
Fold 4 IBS: 0.16605563121333416
Fold 5 IBS: 0.17195490136856303
[I 2024-04-17 16:50:58,902] Trial 91 finished with value: 0.1754926310929034 and parameters: {'subsample': 0.46426861921390467, 'dropout_rate': 0.49057564599137743, 'n_estimators': 371, 'learning_rate': 0.009684471622440297}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.2221068575491969
Fold 2 IBS: 0.14416827613414065
Fold 3 IBS: 0.17161635162532118
Fold 4 IBS: 0.1670198962517616
Fold 5 IBS: 0.17195760217127698
[I 2024-04-17 16:51:05,270] Trial 92 finished with value: 0.17537379674633946 and parameters: {'subsample': 0.514974704887948, 'dropout_rate': 0.5274793503053491, 'n_estimators': 376, 'learning_rate': 0.008788809083990427}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.23584484670281627
Fold 2 IBS: 0.13896592813461467
Fold 3 IBS: 0.17753112316501893
Fold 4 IBS: 0.16512376520384348
Fold 5 IBS: 0.17405575286477107
[I 2024-04-17 16:51:09,970] Trial 93 finished with value: 0.1783042832142129 and parameters: {'subsample': 0.5312044776495501, 'dropout_rate': 0.43103650480825306, 'n_estimators': 305, 'learning_rate': 0.015776067959261945}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.21299253359773643
Fold 2 IBS: 0.15471309159319202
Fold 3 IBS: 0.17314305805772381
Fold 4 IBS: 0.17322272938078404
Fold 5 IBS: 0.1751189806530396
[I 2024-04-17 16:51:16,581] Trial 94 finished with value: 0.17783807865649517 and parameters: {'subsample': 0.5740143250909806, 'dropout_rate': 0.4876047768482908, 'n_estimators': 385, 'learning_rate': 0.006189932404296139}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.23387871644249938
Fold 2 IBS: 0.13879146460752725

Fold 3 IBS: 0.17650989370961295
Fold 4 IBS: 0.1649768179384022
Fold 5 IBS: 0.17358752615653894
[I 2024-04-17 16:51:22,264] Trial 95 finished with value: 0.17754888377091613 and parameters: {'subsample': 0.49260763697644044, 'dropout_rate': 0.5264582292092028, 'n_estimators': 352, 'learning_rate': 0.013128187171003648}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.2866906463342198
Fold 2 IBS: 0.1673131983448597
Fold 3 IBS: 0.2449845962777135
Fold 4 IBS: 0.20002389838361384
Fold 5 IBS: 0.2037766350360634
[I 2024-04-17 16:51:27,247] Trial 96 finished with value: 0.22055779487529406 and parameters: {'subsample': 0.308291704410664, 'dropout_rate': 0.4736950461791585, 'n_estimators': 316, 'learning_rate': 0.054487916689644846}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.2641416731850371
Fold 2 IBS: 0.1496045701947549
Fold 3 IBS: 0.2159079716925395
Fold 4 IBS: 0.17958191559776393
Fold 5 IBS: 0.19139670221522273
[I 2024-04-17 16:51:33,425] Trial 97 finished with value: 0.20012656657706365 and parameters: {'subsample': 0.6111691740353818, 'dropout_rate': 0.5363908039426202, 'n_estimators': 364, 'learning_rate': 0.02760932068585472}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.22972670473788318
Fold 2 IBS: 0.1407340180016549
Fold 3 IBS: 0.1739254449671554
Fold 4 IBS: 0.16513887760797377
Fold 5 IBS: 0.17235899966047816
[I 2024-04-17 16:51:40,192] Trial 98 finished with value: 0.17637680899502908 and parameters: {'subsample': 0.6444509430196261, 'dropout_rate': 0.5526018375429977, 'n_estimators': 392, 'learning_rate': 0.010376542958461204}. Best is trial 74 with value: 0.175186319170446.
Fold 1 IBS: 0.2079873814493664
Fold 2 IBS: 0.16499575008448444
Fold 3 IBS: 0.17644545535264208
Fold 4 IBS: 0.1803834657341507
Fold 5 IBS: 0.17946930904758535
[I 2024-04-17 16:51:46,655] Trial 99 finished with value: 0.18185627233364582 and parameters: {'subsample': 0.7423100199314099, 'dropout_rate': 0.5123889458623918, 'n_estimators': 377, 'learning_rate': 0.004874304788084134}. Best is trial 74 with value: 0.175186319170446.


* Best trial for IBS:
 FrozenTrial(number=74, state=TrialState.COMPLETE, values=[0.175186319170446], datetime_start=datetime.datetime(2024, 4, 17, 16, 48, 56, 186932), datetime_complete=datetime.datetime(2024, 4, 17, 16, 49, 3, 715068), params={'subsample': 0.22537252419144232, 'dropout_rate': 0.5791496160294716, 'n_estimators': 411, 'learning_rate': 0.008905079139999657}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=74, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.22537252419144232, 'dropout_rate': 0.5791496160294716, 'n_estimators': 411, 'learning_rate': 0.008905079139999657}


* Best Score for IBS:
 0.175186319170446

In [72]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [73]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.713
train_ibs:  0.175

#### Test

In [74]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [75]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10707700162921632,
                                              learning_rate=0.09635955935176935,
                                              n_estimators=311,
                                              random_state=123,
                                              subsample=0.11211713718471546)

C-index score: 0.6

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5791496160294716,
                                              learning_rate=0.008905079139999657,
                                              n_estimators=411,
                                              random_state=123,
                                              subsample=0.22537252419144232)

IBS: 0.233

In [76]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [77]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.829   1.0
Randomsurvivalforest             0.828   2.0
GradientBoosting                 0.799   3.0
CoxElastic                       0.787   4.0
CoxPH                            0.786   5.0
CoxLasso                         0.783   6.0
CoxRidge                         0.716   7.0
ComponentwiseGradientBoosting    0.713   8.0

In [78]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxElastic                     0.161   1.5
Randomsurvivalforest           0.161   1.5
CoxPH                          0.162   3.5
CoxLasso                       0.162   3.5
ExtraSurvivalTrees             0.167   5.0
ComponentwiseGradientBoosting  0.175   6.0
GradientBoosting               0.213   7.0
CoxRidge                       0.217   8.0

In [79]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.638   1.0
Randomsurvivalforest             0.634   2.0
ExtraSurvivalTrees               0.620   3.0
CoxLasso                         0.619   4.0
CoxElastic                       0.617   5.0
CoxPH                            0.614   6.0
CoxRidge                         0.611   7.0
ComponentwiseGradientBoosting    0.600   8.0

In [80]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.212   1.0
GradientBoosting               0.220   2.0
CoxRidge                       0.221   3.0
ComponentwiseGradientBoosting  0.233   4.0
ExtraSurvivalTrees             0.244   5.0
CoxElastic                     0.247   6.0
CoxLasso                       0.248   7.0
CoxPH                          0.251   8.0

In [81]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/robust/plsr/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_robust_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [82]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-17