In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D3 
clinical_train.isnull().sum().sum()

0

### COX assumption in Train data

In [6]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.97      0.05
LBP_003_PET                                                      0.00 0.97      0.05
LBP_012_CT                                                       0.00 0.96      0.06
LBP_012_PET                                                      0.01 0.94      0.09
LBP_021_CT                                                       0.00 0.98      0.04
LBP_021_PET                                                      0.01 0.94      0.10
LBP_030_CT                                                       0.00 0.99      0.02
LBP_030_PET                                                      0.00 0.98      0.02
LBP_102_CT                                                       0.00 0.96      0.05
LBP_102_PET                                                      0.01 0.92      0.12
LBP_111_CT                                                       0.00 0.95      0.07
LBP_111_PET                                                      0.00 1.00      0.00
LBP_120_CT                                                       0.00 0.98      0.03
LBP_120_PET                                                      0.00 0.99      0.02
LBP_201_CT                                                       0.00 0.97      0.04
LBP_201_PET                                                      0.00 0.97      0.04
LBP_210_CT                                                       0.00 1.00      0.01
LBP_210_PET                                                      0.00 1.00      0.00
LBP_300_CT                                                       0.00 0.97      0.04
LBP_300_PET                                                      0.01 0.94      0.09
MTV                                                              0.00 0.98      0.04
SUVpeak                                                          0.00 0.98      0.02
TLG                                                              0.00 0.99      0.02
age                                                              0.00 0.97      0.05
cavum_oris                                                       0.00 0.99      0.02
charlson                                                         0.02 0.90      0.15
female                                                           0.00 0.96      0.06
first_order_10Percentile_CT                                      0.00 0.98      0.03
first_order_10Percentile_PET                                     0.00 1.00      0.01
first_order_90Percentile_CT                                      0.00 0.98      0.04
first_order_90Percentile_PET                                     0.00 0.99      0.01
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 1.00      0.00
first_order_Entropy_CT_c16                                       0.00 1.00      0.00
first_order_Entropy_PET_b2                                       0.00 1.00      0.00
first_order_Entropy_PET_c04                                      0.00 1.00      0.00
first_order_InterquartileRange_CT                                0.00 0.97      0.04
first_order_InterquartileRange_PET                               0.00 0.99      0.01
first_order_Kurtosis_CT                                          0.00 0.95      0.08
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.00 0.99      0.02
first_order_Maximum_PET                                          0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_PET                            0.00 0.99      0.02
first_order_Mean_CT                                              0.00 0.99      0.02
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.98      0.03
first_order_Median_PET                                           0.00 0.99      0.01
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.01 0.94      0.09
first_order_Range_CT                                             0.00 0.99      0.01
first_order_Range_PET                                            0.00 0.99      0.02
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.98      0.04
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 1.00      0.00
first_order_RootMeanSquared_CT                                   0.00 0.98      0.03
first_order_RootMeanSquared_PET                                  0.00 0.99      0.01
first_order_Skewness_CT                                          0.00 0.98      0.03
first_order_Skewness_PET                                         0.00 1.00      0.00
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.97      0.05
first_order_Uniformity_CT_c16                                    0.00 0.99      0.01
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 1.00      0.00
first_order_Variance_CT                                          0.00 1.00      0.01
first_order_Variance_PET                                         0.00 1.00      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_CT_c16                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.99      0.01
glcm_ClusterProminence_d_1_CT_b20                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.98      0.03
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.97      0.05
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.97      0.04
glcm_ClusterShade_d_1_CT_c16                                     0.00 1.00      0.01
glcm_ClusterShade_d_1_PET_b2                                     0.01 0.93      0.11
glcm_ClusterShade_d_1_PET_c04                                    0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.99      0.02
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.99      0.01
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.01
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 1.00      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.99      0.02
glcm_Correlation_d_1_CT_c16                                      0.00 0.95      0.07
glcm_Correlation_d_1_PET_b2                                      0.00 0.98      0.03
glcm_Correlation_d_1_PET_c04                                     0.00 0.99      0.02
glcm_DifferenceAverage_d_1_CT_b20                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_c16                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_PET_b2                                0.00 1.00      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceVariance_d_1_CT_b20                               0.00 1.00      0.01
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_b2                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.98      0.02
glcm_Id_d_1_CT_b20                                               0.00 0.99      0.02
glcm_Id_d_1_CT_c16                                               0.00 1.00      0.00
glcm_Id_d_1_PET_b2                                               0.00 1.00      0.01
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idm_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00 1.00      0.01
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Idmn_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_c16                                             0.00 0.99      0.01
glcm_Idmn_d_1_PET_b2                                             0.00 1.00      0.01
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 0.98      0.03
glcm_Idn_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.01
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Imc1_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_c16                                             0.01 0.94      0.10
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Imc2_d_1_CT_b20                                             0.00 1.00      0.01
glcm_Imc2_d_1_CT_c16                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.98      0.02
glcm_InverseVariance_d_1_CT_b20                                  0.00 1.00      0.00
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_PET_b2                                  0.00 1.00      0.01
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.01
glcm_JointAverage_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointAverage_d_1_PET_b2                                     0.00 1.00      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 0.99      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.97      0.04
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_b2                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.97      0.04
glcm_MCC_d_1_CT_c16                                              0.00 0.95      0.07
glcm_MCC_d_1_PET_b2                                              0.00 0.99      0.01
glcm_MCC_d_1_PET_c04                                             0.00 0.98      0.02
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.96      0.06
glcm_MaximumProbability_d_1_CT_c16                               0.00 1.00      0.00
glcm_MaximumProbability_d_1_PET_b2                               0.00 0.99      0.01
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.99      0.01
glcm_SumAverage_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumAverage_d_1_PET_b2                                       0.00 1.00      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.99      0.02
glcm_SumSquares_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumSquares_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumSquares_d_1_PET_c04                                      0.00 0.99      0.01
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 1.00      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.04
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.97      0.05
gldm_DependenceVariance_d_1_CT_c16                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 1.00      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.03
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 1.00      0.00
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 1.00      0.00
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.00
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.02
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.01 0.93      0.10
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.99      0.01
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.98      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_b20                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_c16                                   0.00 1.00      0.01
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.01

In [7]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [8]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.07
LBP_003_PET                                                      0.08 0.77      0.37
LBP_012_CT                                                       0.00 0.95      0.07
LBP_012_PET                                                      0.18 0.67      0.57
LBP_021_CT                                                       0.15 0.69      0.53
LBP_021_PET                                                      0.01 0.94      0.09
LBP_030_CT                                                       0.00 0.99      0.01
LBP_030_PET                                                      0.03 0.86      0.21
LBP_102_CT                                                       0.02 0.89      0.17
LBP_102_PET                                                      0.69 0.41      1.30
LBP_111_CT                                                       0.01 0.93      0.11
LBP_111_PET                                                      0.00 0.98      0.03
LBP_120_CT                                                       0.01 0.92      0.12
LBP_120_PET                                                      0.01 0.91      0.14
LBP_201_CT                                                       0.04 0.84      0.25
LBP_201_PET                                                      1.08 0.30      1.74
LBP_210_CT                                                       0.13 0.72      0.47
LBP_210_PET                                                      0.06 0.81      0.30
LBP_300_CT                                                       0.03 0.87      0.19
LBP_300_PET                                                      0.23 0.63      0.67
MTV                                                              0.00 0.98      0.03
SUVpeak                                                          0.01 0.91      0.14
TLG                                                              0.00 0.97      0.05
age                                                              0.11 0.74      0.43
cavum_oris                                                       0.35 0.55      0.85
charlson                                                         1.37 0.24      2.05
female                                                           2.09 0.15      2.76
first_order_10Percentile_CT                                      0.16 0.69      0.54
first_order_10Percentile_PET                                     0.00 0.96      0.06
first_order_90Percentile_CT                                      0.28 0.60      0.74
first_order_90Percentile_PET                                     0.01 0.94      0.08
first_order_Energy_CT                                            0.00 0.95      0.07
first_order_Energy_PET                                           0.02 0.89      0.17
first_order_Entropy_CT_b20                                       0.00 0.95      0.08
first_order_Entropy_CT_c16                                       0.01 0.94      0.09
first_order_Entropy_PET_b2                                       0.00 0.99      0.01
first_order_Entropy_PET_c04                                      0.00 0.99      0.02
first_order_InterquartileRange_CT                                0.00 0.99      0.02
first_order_InterquartileRange_PET                               0.04 0.85      0.23
first_order_Kurtosis_CT                                          0.00 0.95      0.07
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.04 0.83      0.26
first_order_Maximum_PET                                          0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_CT                             0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_PET                            0.00 0.97      0.04
first_order_Mean_CT                                              0.01 0.93      0.11
first_order_Mean_PET                                             0.01 0.92      0.11
first_order_Median_CT                                            0.20 0.65      0.61
first_order_Median_PET                                           0.01 0.93      0.11
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.02 0.88      0.19
first_order_Range_CT                                             0.03 0.87      0.20
first_order_Range_PET                                            0.01 0.93      0.10
first_order_RobustMeanAbsoluteDeviation_CT                       0.18 0.67      0.57
first_order_RobustMeanAbsoluteDeviation_PET                      0.02 0.88      0.18
first_order_RootMeanSquared_CT                                   0.01 0.91      0.13
first_order_RootMeanSquared_PET                                  0.01 0.93      0.11
first_order_Skewness_CT                                          0.04 0.84      0.25
first_order_Skewness_PET                                         0.00 0.99      0.02
first_order_TotalEnergy_CT                                       0.00 0.95      0.07
first_order_TotalEnergy_PET                                      0.02 0.89      0.17
first_order_Uniformity_CT_b20                                    0.00 0.97      0.04
first_order_Uniformity_CT_c16                                    0.00 0.97      0.04
first_order_Uniformity_PET_b2                                    0.02 0.90      0.15
first_order_Uniformity_PET_c04                                   0.01 0.93      0.10
first_order_Variance_CT                                          0.00 1.00      0.00
first_order_Variance_PET                                         0.00 0.95      0.07
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.97      0.05
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.95      0.07
glcm_ClusterProminence_d_1_CT_b20                                0.03 0.86      0.22
glcm_ClusterProminence_d_1_CT_c16                                0.01 0.93      0.11
glcm_ClusterProminence_d_1_PET_b2                                0.02 0.88      0.19
glcm_ClusterProminence_d_1_PET_c04                               0.03 0.86      0.22
glcm_ClusterShade_d_1_CT_b20                                     0.11 0.74      0.42
glcm_ClusterShade_d_1_CT_c16                                     0.02 0.89      0.16
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.99      0.01
glcm_ClusterShade_d_1_PET_c04                                    0.06 0.81      0.31
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.96      0.06
glcm_ClusterTendency_d_1_CT_c16                                  0.01 0.91      0.14
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.95      0.08
glcm_ClusterTendency_d_1_PET_c04                                 0.08 0.78      0.36
glcm_Contrast_d_1_CT_b20                                         0.00 0.98      0.02
glcm_Contrast_d_1_CT_c16                                         0.02 0.89      0.17
glcm_Contrast_d_1_PET_b2                                         0.00 0.97      0.04
glcm_Contrast_d_1_PET_c04                                        0.00 0.98      0.04
glcm_Correlation_d_1_CT_b20                                      0.05 0.82      0.28
glcm_Correlation_d_1_CT_c16                                      0.29 0.59      0.77
glcm_Correlation_d_1_PET_b2                                      0.00 0.97      0.04
glcm_Correlation_d_1_PET_c04                                     0.00 0.96      0.05
glcm_DifferenceAverage_d_1_CT_b20                                0.01 0.92      0.13
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.95      0.08
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.96      0.06
glcm_DifferenceAverage_d_1_PET_c04                               0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_b20                                0.01 0.93      0.10
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.97      0.05
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.95      0.07
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_c16                               0.02 0.88      0.18
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.99      0.02
glcm_Id_d_1_CT_b20                                               0.05 0.83      0.27
glcm_Id_d_1_CT_c16                                               0.00 0.96      0.05
glcm_Id_d_1_PET_b2                                               0.01 0.93      0.11
glcm_Id_d_1_PET_c04                                              0.00 0.96      0.06
glcm_Idm_d_1_CT_b20                                              0.05 0.83      0.27
glcm_Idm_d_1_CT_c16                                              0.00 0.97      0.04
glcm_Idm_d_1_PET_b2                                              0.01 0.94      0.09
glcm_Idm_d_1_PET_c04                                             0.00 0.97      0.05
glcm_Idmn_d_1_CT_b20                                             0.02 0.90      0.15
glcm_Idmn_d_1_CT_c16                                             0.02 0.90      0.15
glcm_Idmn_d_1_PET_b2                                             0.01 0.93      0.11
glcm_Idmn_d_1_PET_c04                                            0.00 0.98      0.03
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.01
glcm_Idn_d_1_CT_c16                                              0.00 0.96      0.06
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idn_d_1_PET_c04                                             0.00 0.97      0.04
glcm_Imc1_d_1_CT_b20                                             0.04 0.85      0.24
glcm_Imc1_d_1_CT_c16                                             0.34 0.56      0.84
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc1_d_1_PET_c04                                            0.00 0.96      0.07
glcm_Imc2_d_1_CT_b20                                             0.09 0.77      0.38
glcm_Imc2_d_1_CT_c16                                             0.13 0.72      0.48
glcm_Imc2_d_1_PET_b2                                             0.01 0.94      0.09
glcm_Imc2_d_1_PET_c04                                            0.01 0.93      0.11
glcm_InverseVariance_d_1_CT_b20                                  0.18 0.67      0.58
glcm_InverseVariance_d_1_CT_c16                                  0.01 0.91      0.14
glcm_InverseVariance_d_1_PET_b2                                  0.03 0.87      0.20
glcm_InverseVariance_d_1_PET_c04                                 0.01 0.91      0.13
glcm_JointAverage_d_1_CT_b20                                     0.00 0.98      0.02
glcm_JointAverage_d_1_CT_c16                                     0.00 0.97      0.04
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.01 0.93      0.10
glcm_JointEnergy_d_1_CT_b20                                      0.01 0.93      0.11
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.03 0.86      0.22
glcm_JointEnergy_d_1_PET_c04                                     0.02 0.90      0.16
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.02 0.90      0.15
glcm_JointEntropy_d_1_PET_b2                                     0.00 0.97      0.05
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.96      0.06
glcm_MCC_d_1_CT_c16                                              0.01 0.94      0.08
glcm_MCC_d_1_PET_b2                                              0.00 1.00      0.00
glcm_MCC_d_1_PET_c04                                             0.00 0.99      0.01
glcm_MaximumProbability_d_1_CT_b20                               0.01 0.92      0.11
glcm_MaximumProbability_d_1_CT_c16                               0.02 0.89      0.17
glcm_MaximumProbability_d_1_PET_b2                               0.04 0.85      0.23
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.95      0.07
glcm_SumAverage_d_1_CT_b20                                       0.00 0.98      0.02
glcm_SumAverage_d_1_CT_c16                                       0.00 0.97      0.04
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.01 0.93      0.10
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.95      0.08
glcm_SumEntropy_d_1_CT_c16                                       0.01 0.91      0.14
glcm_SumEntropy_d_1_PET_b2                                       0.00 0.96      0.05
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.98      0.03
glcm_SumSquares_d_1_CT_b20                                       0.00 0.96      0.05
glcm_SumSquares_d_1_CT_c16                                       0.01 0.93      0.11
glcm_SumSquares_d_1_PET_b2                                       0.00 0.95      0.08
glcm_SumSquares_d_1_PET_c04                                      0.08 0.78      0.36
gldm_DependenceEntropy_d_1_CT_b20                                0.11 0.74      0.44
gldm_DependenceEntropy_d_1_CT_c16                                0.05 0.83      0.27
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.95      0.07
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.10 0.75      0.42
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.02
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.01 0.92      0.12
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_PET_b2                          0.01 0.90      0.15
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 0.99      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.52 0.47      1.09
gldm_DependenceVariance_d_1_CT_c16                               0.17 0.68      0.55
gldm_DependenceVariance_d_1_PET_b2                               0.07 0.80      0.33
gldm_DependenceVariance_d_1_PET_c04                              0.07 0.78      0.35
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.97      0.05
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.01 0.94      0.09
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.94      0.08
gldm_GrayLevelVariance_d_1_PET_c04                               0.05 0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.02
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.95      0.07
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.02 0.88      0.18
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.03 0.86      0.22
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.01 0.92      0.11
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.03 0.86      0.22
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.01 0.94      0.09
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.03 0.86      0.22
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.08
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.06 0.81      0.30
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.03 0.86      0.21
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.94      0.08
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.02 0.89      0.17
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.01 0.91      0.13
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.07 0.79      0.33
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.96      0.06
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.02 0.89      0.16
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01 0.92      0.13
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.01 0.94      0.08
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.03 0.86      0.22
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.22 0.64      0.65
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 1.00      0.00
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.95      0.08
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.96      0.06
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 1.00      0.01
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.95      0.07
glrlm_GrayLevelNonUniformity_CT_c16                              0.06 0.81      0.30
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.99      0.01
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.95      0.08
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.96      0.06
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.96      0.06

In [9]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

## Test dataset: MAASTRO

In [10]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [11]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [12]:
# Need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [13]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [14]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [15]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [16]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [17]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [18]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [19]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [20]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = RobustScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [23]:
# Divide the X_MAASTRO into numerical part and categorical part 
X_MAASTRO_categorical = X_MAASTRO[categorical_columns]
X_MAASTRO_numeric = X_MAASTRO.drop(categorical_columns, axis=1)

# Save the column name and index of the numeric part
X_MAASTRO_numeric_columns = X_MAASTRO_numeric.columns
X_MAASTRO_numeric_index = X_MAASTRO_numeric.index

In [24]:
# Standardize the numeric part 
X_MAASTRO_numeric_std = scaler.transform(X_MAASTRO_numeric)

# Change the standardized part into a dataframe 
X_MAASTRO_numeric_std = pd.DataFrame(X_MAASTRO_numeric_std, columns=X_MAASTRO_numeric_columns, index=X_MAASTRO_numeric_index)

# Concat the standardized part with the categorical part 
X_MAASTRO_std = pd.concat([X_MAASTRO_categorical, X_MAASTRO_numeric_std], axis=1)

# Change the column order of X_MAASTRO_std
X_MAASTRO_std = X_MAASTRO_std[original_X.columns]

In [25]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [26]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:47:12,102] A new study created in memory with name: no-name-71d5a103-aac7-4a28-85ba-6bbd324c38a4

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-17 13:47:12,390] Trial 0 failed with parameters: {} because of the following error: ValueError('search direction contains NaN or infinite values').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_1413/4166082094.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 454, in fit
    raise ValueError("search direction contains NaN or infinite values")
ValueError: search direction contains NaN or infinite values
[W 2024-04-17 13:47:12,393] Trial 0 failed with value None.

ValueError: search direction contains NaN or infinite values

In [27]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {}

In [28]:
# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [29]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [30]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [31]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [34]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [35]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:50:43,355] A new study created in memory with name: no-name-6a676896-0cf9-40cf-99de-c18541662832

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.6372549019607843

[I 2024-04-17 13:50:43,840] A new study created in memory with name: no-name-d9219d17-9278-4a77-a309-e3ee5f2d2c55

Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.5774647887323944
[I 2024-04-17 13:50:43,834] Trial 0 finished with value: 0.6505821991392386 and parameters: {}. Best is trial 0 with value: 0.6505821991392386.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6505821991392386], datetime_start=datetime.datetime(2024, 4, 17, 13, 50, 43, 389242), datetime_complete=datetime.datetime(2024, 4, 17, 13, 50, 43, 834553), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6505821991392386

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651830695444
Fold 2 IBS: 0.22157791625059692
Fold 3 IBS: 0.20453594280733517
Fold 4 IBS: 0.22473802997425457
Fold 5 IBS: 0.21812431597978285
[I 2024-04-17 13:50:44,270] Trial 0 finished with value: 0.21659054466378475 and parameters: {}. Best is trial 0 with value: 0.21659054466378475.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054466378475], datetime_start=datetime.datetime(2024, 4, 17, 13, 50, 43, 880608), datetime_complete=datetime.datetime(2024, 4, 17, 13, 50, 44, 270696), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054466378475

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.651
train_ibs:  0.217

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.592

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:50:44,947] A new study created in memory with name: no-name-087afed9-a03d-490f-9279-007bc35aea46

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058

[I 2024-04-17 13:50:45,854] A new study created in memory with name: no-name-1aa0a6ba-a2e4-49fc-b662-43f97cb57627

Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:50:45,820] Trial 0 finished with value: 0.706327046815744 and parameters: {}. Best is trial 0 with value: 0.706327046815744.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.706327046815744], datetime_start=datetime.datetime(2024, 4, 17, 13, 50, 44, 980220), datetime_complete=datetime.datetime(2024, 4, 17, 13, 50, 45, 820067), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.706327046815744

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21388429370731754
Fold 2 IBS: 0.1585758545159384
Fold 3 IBS: 0.15832262210958478
Fold 4 IBS: 0.27197836239155776
Fold 5 IBS: 0.20706497029738247
[I 2024-04-17 13:50:46,647] Trial 0 finished with value: 0.20196522060435615 and parameters: {}. Best is trial 0 with value: 0.20196522060435615.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20196522060435615], datetime_start=datetime.datetime(2024, 4, 17, 13, 50, 45, 875533), datetime_complete=datetime.datetime(2024, 4, 17, 13, 50, 46, 647739), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20196522060435615

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.706
train_ibs:  0.202

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.597

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.221

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:50:46,815] A new study created in memory with name: no-name-da201069-1f85-4466-aae8-dc79d4d843e6

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:50:47,704] Trial 0 finished with value: 0.7117757136242396 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7117757136242396.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:50:48,488] Trial 1 finished with value: 0.7153028518819318 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7153028518819318.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:50:49,206] Trial 2 finished with value: 0.7125442957049593 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.7153028518819318.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:50:49,888] Trial 3 finished with value: 0.7152999865889077 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.7153028518819318.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:50:50,495] Trial 4 finished with value: 0.7117757136242396 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.7153028518819318.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:50:51,162] Trial 5 finished with value: 0.7152124515749021 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.7153028518819318.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:50:51,841] Trial 6 finished with value: 0.7079658352425071 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.7153028518819318.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:50:52,543] Trial 7 finished with value: 0.7126195954807797 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.7153028518819318.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:50:53,239] Trial 8 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 8 with value: 0.7161928437317648.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:50:53,897] Trial 9 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 8 with value: 0.7161928437317648.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:50:54,563] Trial 10 finished with value: 0.7047217523535128 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 8 with value: 0.7161928437317648.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:50:55,184] Trial 11 finished with value: 0.7152124515749021 and parameters: {'l1_ratio': 0.4221803406726559}. Best is trial 8 with value: 0.7161928437317648.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 13:50:55,861] Trial 12 finished with value: 0.716238953725058 and parameters: {'l1_ratio': 0.5222247444015665}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:50:56,528] Trial 13 finished with value: 0.7125781704600672 and parameters: {'l1_ratio': 0.5711930655936097}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:50:57,186] Trial 14 finished with value: 0.70950953838966 and parameters: {'l1_ratio': 0.8887005110166508}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 13:50:57,639] Trial 15 finished with value: 0.6672813211088096 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:50:58,300] Trial 16 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.30518868850921266}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:50:58,980] Trial 17 finished with value: 0.7125781704600672 and parameters: {'l1_ratio': 0.6043437060624984}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:50:59,650] Trial 18 finished with value: 0.709380578354942 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:00,347] Trial 19 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.4686899435891718}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:01,004] Trial 20 finished with value: 0.7058000950830096 and parameters: {'l1_ratio': 0.15523641724239506}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:01,650] Trial 21 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.4834331461835271}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:02,306] Trial 22 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.5016475493598125}. Best is trial 12 with value: 0.716238953725058.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:02,999] Trial 23 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.352181905423733}. Best is trial 23 with value: 0.717085700874622.

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:03,817] Trial 24 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.3525262253351147}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:04,466] Trial 25 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.32881905267396466}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:05,111] Trial 26 finished with value: 0.7125442957049593 and parameters: {'l1_ratio': 0.22313754734009067}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:05,762] Trial 27 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.3493262875011306}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:06,501] Trial 28 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:07,116] Trial 29 finished with value: 0.7125442957049593 and parameters: {'l1_ratio': 0.23541188749756042}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:51:07,735] Trial 30 finished with value: 0.7038317605036796 and parameters: {'l1_ratio': 0.119907523145895}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:08,387] Trial 31 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.36163472104060657}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:08,979] Trial 32 finished with value: 0.7153028518819318 and parameters: {'l1_ratio': 0.2771705397587284}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:09,656] Trial 33 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.35581051477616127}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:51:10,306] Trial 34 finished with value: 0.7050466135334991 and parameters: {'l1_ratio': 0.18223020608106505}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:10,954] Trial 35 finished with value: 0.7153028518819318 and parameters: {'l1_ratio': 0.28405603855336464}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:11,588] Trial 36 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.3709522097382032}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:51:12,225] Trial 37 finished with value: 0.7125781704600672 and parameters: {'l1_ratio': 0.6194166284751581}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:12,921] Trial 38 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.3965137069504508}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:13,542] Trial 39 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:14,171] Trial 40 finished with value: 0.7133881775614993 and parameters: {'l1_ratio': 0.2469899069587328}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:14,772] Trial 41 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.35570753305688546}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:15,392] Trial 42 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.31879019479532683}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:16,040] Trial 43 finished with value: 0.7152124515749021 and parameters: {'l1_ratio': 0.4251883147861656}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:16,748] Trial 44 finished with value: 0.7071024831268348 and parameters: {'l1_ratio': 0.19122121680907503}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:17,368] Trial 45 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.40798469366798756}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 13:51:18,036] Trial 46 finished with value: 0.716238953725058 and parameters: {'l1_ratio': 0.5296312468775739}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:18,690] Trial 47 finished with value: 0.714322459725069 and parameters: {'l1_ratio': 0.2686754907915291}. Best is trial 23 with value: 0.717085700874622.

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:19,328] Trial 48 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.33659813406040173}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:51:20,018] Trial 49 finished with value: 0.6981197926179338 and parameters: {'l1_ratio': 0.05663011584206612}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:20,740] Trial 50 finished with value: 0.7152124515749021 and parameters: {'l1_ratio': 0.4358244534444967}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:21,416] Trial 51 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.36622175763960324}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:22,092] Trial 52 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.3169978896284231}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:22,722] Trial 53 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.3643267025542451}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:23,387] Trial 54 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.4000718445229422}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:24,102] Trial 55 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.2956623629125545}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:24,810] Trial 56 finished with value: 0.7144561047323676 and parameters: {'l1_ratio': 0.5549026919064575}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:25,427] Trial 57 finished with value: 0.7098685895694118 and parameters: {'l1_ratio': 0.20937514376418376}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:26,067] Trial 58 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.47162991188473535}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:26,759] Trial 59 finished with value: 0.7050023232197626 and parameters: {'l1_ratio': 0.14515720694354467}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:27,449] Trial 60 finished with value: 0.7133420675682063 and parameters: {'l1_ratio': 0.25828460121268837}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:28,127] Trial 61 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.357329783962197}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:28,791] Trial 62 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.3338439538631166}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:29,466] Trial 63 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.38053042663255354}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:30,170] Trial 64 finished with value: 0.7152124515749021 and parameters: {'l1_ratio': 0.4388353365761247}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 13:51:30,840] Trial 65 finished with value: 0.716238953725058 and parameters: {'l1_ratio': 0.510515240589232}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:31,522] Trial 66 finished with value: 0.7153028518819318 and parameters: {'l1_ratio': 0.34200606006278367}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:32,199] Trial 67 finished with value: 0.7153028518819318 and parameters: {'l1_ratio': 0.290200077539566}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:32,961] Trial 68 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.38791372797245005}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:51:33,686] Trial 69 finished with value: 0.7087607418127302 and parameters: {'l1_ratio': 0.9521436965777794}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:34,371] Trial 70 finished with value: 0.717036725588305 and parameters: {'l1_ratio': 0.4482309875742869}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:35,043] Trial 71 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.35647058250926816}. Best is trial 23 with value: 0.717085700874622.

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:35,739] Trial 72 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.41463500396855246}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:36,429] Trial 73 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.30622399473292095}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:37,096] Trial 74 finished with value: 0.7133881775614993 and parameters: {'l1_ratio': 0.24406975675345172}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:37,709] Trial 75 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.36847363393571986}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:38,418] Trial 76 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.4700504927865202}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:51:39,075] Trial 77 finished with value: 0.7125781704600672 and parameters: {'l1_ratio': 0.5897656721978001}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:39,738] Trial 78 finished with value: 0.7153028518819318 and parameters: {'l1_ratio': 0.2827469592561193}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:40,437] Trial 79 finished with value: 0.7098685895694118 and parameters: {'l1_ratio': 0.2096201099964446}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:41,149] Trial 80 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.3175442349516614}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:41,859] Trial 81 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.35527522972786524}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:42,542] Trial 82 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.38883418965845207}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:43,176] Trial 83 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.41456631129058885}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:43,883] Trial 84 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.3709290255426036}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:44,577] Trial 85 finished with value: 0.7153028518819318 and parameters: {'l1_ratio': 0.343764250965636}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:45,243] Trial 86 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.4939482094701635}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:45,951] Trial 87 finished with value: 0.714322459725069 and parameters: {'l1_ratio': 0.2714392745081262}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:46,640] Trial 88 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.30478425653543284}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:51:47,406] Trial 89 finished with value: 0.711639203323917 and parameters: {'l1_ratio': 0.6473549536624406}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:48,121] Trial 90 finished with value: 0.7161928437317648 and parameters: {'l1_ratio': 0.4539929923564017}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:48,834] Trial 91 finished with value: 0.717085700874622 and parameters: {'l1_ratio': 0.3585607924494992}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:49,536] Trial 92 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.4093705820382668}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:50,257] Trial 93 finished with value: 0.7144589700253915 and parameters: {'l1_ratio': 0.32572111363342887}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:50,969] Trial 94 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.3937696976593799}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:51,779] Trial 95 finished with value: 0.7161053087177592 and parameters: {'l1_ratio': 0.37358919138256547}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931

Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:51:52,513] Trial 96 finished with value: 0.7119122239245622 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:53,221] Trial 97 finished with value: 0.7161467337384717 and parameters: {'l1_ratio': 0.3466823389979336}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 13:51:53,905] Trial 98 finished with value: 0.7152124515749021 and parameters: {'l1_ratio': 0.4244214591509469}. Best is trial 23 with value: 0.717085700874622.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697

[I 2024-04-17 13:51:54,561] A new study created in memory with name: no-name-393360b1-9c45-4b53-bcdf-e7f73302f77a

Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 13:51:54,549] Trial 99 finished with value: 0.7124492104253491 and parameters: {'l1_ratio': 0.2518056066632922}. Best is trial 23 with value: 0.717085700874622.


* Best trial for C-index:
 FrozenTrial(number=23, state=TrialState.COMPLETE, values=[0.717085700874622], datetime_start=datetime.datetime(2024, 4, 17, 13, 51, 2, 309590), datetime_complete=datetime.datetime(2024, 4, 17, 13, 51, 2, 999616), params={'l1_ratio': 0.352181905423733}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=23, value=None)


* Best Score for C-index:
 0.717085700874622

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21388436919013662
Fold 2 IBS: 0.15916880039525647
Fold 3 IBS: 0.1608534236085006
Fold 4 IBS: 0.24119149140634347
Fold 5 IBS: 0.2068242913152905
[I 2024-04-17 13:51:55,308] Trial 0 finished with value: 0.1963844751831055 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.1963844751831055.
Fold 1 IBS: 0.2138847246005204
Fold 2 IBS: 0.16260871942873492
Fold 3 IBS: 0.1647087664941015
Fold 4 IBS: 0.2290336517349254
Fold 5 IBS: 0.2077575455483112
[I 2024-04-17 13:51:56,082] Trial 1 finished with value: 0.19559868156131868 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.19559868156131868.
Fold 1 IBS: 0.21388488162509872
Fold 2 IBS: 0.16433562477400576
Fold 3 IBS: 0.16576586117353376
Fold 4 IBS: 0.224940465607407
Fold 5 IBS: 0.2082372732694083
[I 2024-04-17 13:51:56,832] Trial 2 finished with value: 0.1954328212898907 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.1954328212898907.
Fold 1 IBS: 0.21388443459292844
Fold 2 IBS: 0.15910212601253487
Fold 3 IBS: 0.16170146142445777
Fold 4 IBS: 0.23617429832265027
Fold 5 IBS: 0.20704939427782212
[I 2024-04-17 13:51:57,565] Trial 3 finished with value: 0.19558234292607868 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.1954328212898907.
Fold 1 IBS: 0.21388436124452687
Fold 2 IBS: 0.15926787902063327
Fold 3 IBS: 0.16073856240864995
Fold 4 IBS: 0.24247110510819633
Fold 5 IBS: 0.20678546372546136
[I 2024-04-17 13:51:58,347] Trial 4 finished with value: 0.19662947430149355 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.1954328212898907.
Fold 1 IBS: 0.21388452956315143
Fold 2 IBS: 0.1598665223282879
Fold 3 IBS: 0.16279321555106113
Fold 4 IBS: 0.2329103840606754
Fold 5 IBS: 0.2069685596028883
[I 2024-04-17 13:51:59,084] Trial 5 finished with value: 0.19528464222121283 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 5 with value: 0.19528464222121283.
Fold 1 IBS: 0.2138842971062154
Fold 2 IBS: 0.15860552178674872
Fold 3 IBS: 0.1584495932298483
Fold 4 IBS: 0.267946457971336
Fold 5 IBS: 0.20690997392144117
[I 2024-04-17 13:51:59,890] Trial 6 finished with value: 0.20115916880311788 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 5 with value: 0.19528464222121283.
Fold 1 IBS: 0.21388437341413574
Fold 2 IBS: 0.1591320373348092
Fold 3 IBS: 0.16092139947713127
Fold 4 IBS: 0.24055217757179828
Fold 5 IBS: 0.2068415037916343
[I 2024-04-17 13:52:00,653] Trial 7 finished with value: 0.19626629831790177 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 5 with value: 0.19528464222121283.
Fold 1 IBS: 0.2138844804780509
Fold 2 IBS: 0.1593861572083325
Fold 3 IBS: 0.16228868529343535
Fold 4 IBS: 0.23419445727186333
Fold 5 IBS: 0.20705020349314932
[I 2024-04-17 13:52:01,467] Trial 8 finished with value: 0.19536079674896628 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 5 with value: 0.19528464222121283.
Fold 1 IBS: 0.2138845618055211
Fold 2 IBS: 0.16048872413284773
Fold 3 IBS: 0.16324086714106575
Fold 4 IBS: 0.2323230575984638
Fold 5 IBS: 0.207169686654231
[I 2024-04-17 13:52:02,388] Trial 9 finished with value: 0.19542137946642588 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 5 with value: 0.19528464222121283.
Fold 1 IBS: 0.2138858706631304
Fold 2 IBS: 0.17094648657379843
Fold 3 IBS: 0.16951781347804543
Fold 4 IBS: 0.2103380791997716
Fold 5 IBS: 0.21007765415701907
[I 2024-04-17 13:52:03,266] Trial 10 finished with value: 0.19495318081435298 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 10 with value: 0.19495318081435298.
Fold 1 IBS: 0.2138906455289287
Fold 2 IBS: 0.1807786472857186
Fold 3 IBS: 0.20440600257881725
Fold 4 IBS: 0.19820394367109234
Fold 5 IBS: 0.21479475161767125
[I 2024-04-17 13:52:04,251] Trial 11 finished with value: 0.20241479813644564 and parameters: {'l1_ratio': 0.02533011697459009}. Best is trial 10 with value: 0.19495318081435298.
Fold 1 IBS: 0.21388822100765595
Fold 2 IBS: 0.17801673042618865
Fold 3 IBS: 0.17254499585148528
Fold 4 IBS: 0.20413567557490594
Fold 5 IBS: 0.2132762594771304
[I 2024-04-17 13:52:05,588] Trial 12 finished with value: 0.19637237646747324 and parameters: {'l1_ratio': 0.04108903480556085}. Best is trial 10 with value: 0.19495318081435298.
Fold 1 IBS: 0.21388496762835263
Fold 2 IBS: 0.16517285314199054
Fold 3 IBS: 0.16624935601684407
Fold 4 IBS: 0.22250344684973836
Fold 5 IBS: 0.20849329438308442
[I 2024-04-17 13:52:06,784] Trial 13 finished with value: 0.19526078360400198 and parameters: {'l1_ratio': 0.20377078100488127}. Best is trial 10 with value: 0.19495318081435298.
Fold 1 IBS: 0.21388511023705645
Fold 2 IBS: 0.1663907868304713
Fold 3 IBS: 0.1670640772314972
Fold 4 IBS: 0.2188522276384564
Fold 5 IBS: 0.20895435921874714
[I 2024-04-17 13:52:07,695] Trial 14 finished with value: 0.1950293122312457 and parameters: {'l1_ratio': 0.1742372865621757}. Best is trial 10 with value: 0.19495318081435298.
Fold 1 IBS: 0.21388544505661275
Fold 2 IBS: 0.16874421279741528
Fold 3 IBS: 0.1683251532350455
Fold 4 IBS: 0.21348663586629177
Fold 5 IBS: 0.20951651632404067
[I 2024-04-17 13:52:08,583] Trial 15 finished with value: 0.1947915926558812 and parameters: {'l1_ratio': 0.12988387421184971}. Best is trial 15 with value: 0.1947915926558812.
Fold 1 IBS: 0.2138855741450092
Fold 2 IBS: 0.16945765731800316
Fold 3 IBS: 0.1687016927885298
Fold 4 IBS: 0.21204250537400002
Fold 5 IBS: 0.2097254932169942
[I 2024-04-17 13:52:09,442] Trial 16 finished with value: 0.19476258456850729 and parameters: {'l1_ratio': 0.11823936501764254}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388464785150718
Fold 2 IBS: 0.16184816748656958
Fold 3 IBS: 0.16404718291096823
Fold 4 IBS: 0.23071351452765665
Fold 5 IBS: 0.2075256395477654
[I 2024-04-17 13:52:10,217] Trial 17 finished with value: 0.1956038304648934 and parameters: {'l1_ratio': 0.32802241476497884}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.2138854323682841
Fold 2 IBS: 0.16867051490880944
Fold 3 IBS: 0.16828532613673622
Fold 4 IBS: 0.2136296672819878
Fold 5 IBS: 0.2095026808324267
[I 2024-04-17 13:52:10,987] Trial 18 finished with value: 0.19479472430564884 and parameters: {'l1_ratio': 0.13115208894634783}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.2139022317894273
Fold 2 IBS: 0.22157360888786964
Fold 3 IBS: 0.20442719211022625
Fold 4 IBS: 0.22382181981099158
Fold 5 IBS: 0.216248563745383
[I 2024-04-17 13:52:11,565] Trial 19 finished with value: 0.21599468326877957 and parameters: {'l1_ratio': 0.008219662059075025}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388441333816596
Fold 2 IBS: 0.15904397288526162
Fold 3 IBS: 0.16145597220557964
Fold 4 IBS: 0.2376957994218982
Fold 5 IBS: 0.2069870832590685
[I 2024-04-17 13:52:12,462] Trial 20 finished with value: 0.19581344822199478 and parameters: {'l1_ratio': 0.5914245950308872}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388547405963504
Fold 2 IBS: 0.168915425941818
Fold 3 IBS: 0.16841404457762293
Fold 4 IBS: 0.21308372183921623
Fold 5 IBS: 0.20955470112341365
[I 2024-04-17 13:52:13,329] Trial 21 finished with value: 0.19477067350834115 and parameters: {'l1_ratio': 0.12707424674685658}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388473494178573
Fold 2 IBS: 0.16271590928508683
Fold 3 IBS: 0.164793644810925
Fold 4 IBS: 0.2287813133275214
Fold 5 IBS: 0.2077845141377889
[I 2024-04-17 13:52:14,127] Trial 22 finished with value: 0.1955920233006216 and parameters: {'l1_ratio': 0.28137504211317865}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388564790657863
Fold 2 IBS: 0.16984968394312652
Fold 3 IBS: 0.16888395117706437
Fold 4 IBS: 0.21149176649432136
Fold 5 IBS: 0.20984120052492305
[I 2024-04-17 13:52:14,891] Trial 23 finished with value: 0.19479045000920278 and parameters: {'l1_ratio': 0.1124690541840564}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388491494924788
Fold 2 IBS: 0.16467360241819445
Fold 3 IBS: 0.1659499784332547
Fold 4 IBS: 0.2240297559347377
Fold 5 IBS: 0.2083223822768281
[I 2024-04-17 13:52:15,769] Trial 24 finished with value: 0.19537212680245258 and parameters: {'l1_ratio': 0.21736087814603194}. Best is trial 16 with value: 0.19476258456850729.

Fold 1 IBS: 0.21388664449810943
Fold 2 IBS: 0.17415098459380943
Fold 3 IBS: 0.1710197787221419
Fold 4 IBS: 0.2077756372328316
Fold 5 IBS: 0.21106836087702271
[I 2024-04-17 13:52:16,769] Trial 25 finished with value: 0.19558028118478302 and parameters: {'l1_ratio': 0.06756100018912164}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388461106227552
Fold 2 IBS: 0.16136483931571033
Fold 3 IBS: 0.16369840206833908
Fold 4 IBS: 0.23142567200158498
Fold 5 IBS: 0.20740945596574717
[I 2024-04-17 13:52:17,933] Trial 26 finished with value: 0.1955565960827314 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388527447177116
Fold 2 IBS: 0.16758270103472897
Fold 3 IBS: 0.167757772915696
Fold 4 IBS: 0.21580089819830942
Fold 5 IBS: 0.2092761998158501
[I 2024-04-17 13:52:18,901] Trial 27 finished with value: 0.1948605692872711 and parameters: {'l1_ratio': 0.14926618171209116}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388430000113584
Fold 2 IBS: 0.15863360620990527
Fold 3 IBS: 0.15855836242042853
Fold 4 IBS: 0.2653743842998451
Fold 5 IBS: 0.20681210496487284
[I 2024-04-17 13:52:19,704] Trial 28 finished with value: 0.2006525515792375 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388476160055123
Fold 2 IBS: 0.1630237198500642
Fold 3 IBS: 0.1649981865428407
Fold 4 IBS: 0.22815592554394154
Fold 5 IBS: 0.20787541874761556
[I 2024-04-17 13:52:20,449] Trial 29 finished with value: 0.19558760245700263 and parameters: {'l1_ratio': 0.269628205513332}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388607587000857
Fold 2 IBS: 0.17193217418301154
Fold 3 IBS: 0.17001011429905666
Fold 4 IBS: 0.20949017169431908
Fold 5 IBS: 0.21028066034202533
[I 2024-04-17 13:52:21,215] Trial 30 finished with value: 0.19511983927768423 and parameters: {'l1_ratio': 0.08757801619814892}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388521141666367
Fold 2 IBS: 0.16713544879377917
Fold 3 IBS: 0.16751683040112947
Fold 4 IBS: 0.21689794039954668
Fold 5 IBS: 0.20915349720826706
[I 2024-04-17 13:52:21,957] Trial 31 finished with value: 0.1949177856438772 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388567293361108
Fold 2 IBS: 0.16997941674400388
Fold 3 IBS: 0.16896364590963148
Fold 4 IBS: 0.21131681777631245
Fold 5 IBS: 0.20987943992044425
[I 2024-04-17 13:52:22,717] Trial 32 finished with value: 0.19480499865680062 and parameters: {'l1_ratio': 0.11063575860849978}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.2138848320620159
Fold 2 IBS: 0.16381052196182003
Fold 3 IBS: 0.165472558979913
Fold 4 IBS: 0.22620167237351876
Fold 5 IBS: 0.20811623650777508
[I 2024-04-17 13:52:23,461] Trial 33 finished with value: 0.19549716437700854 and parameters: {'l1_ratio': 0.24281594732388131}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21391721255292812
Fold 2 IBS: 0.22157047213766218
Fold 3 IBS: 0.20445258106971018
Fold 4 IBS: 0.224311221433028
Fold 5 IBS: 0.21813666812919782
[I 2024-04-17 13:52:23,943] Trial 34 finished with value: 0.21647763106450527 and parameters: {'l1_ratio': 0.0037772681753269755}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388465888140767
Fold 2 IBS: 0.16196064266188426
Fold 3 IBS: 0.16414158939445778
Fold 4 IBS: 0.2304954878985553
Fold 5 IBS: 0.20755544820629301
[I 2024-04-17 13:52:24,754] Trial 35 finished with value: 0.1956075654085196 and parameters: {'l1_ratio': 0.32128045438633224}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.213884323499145
Fold 2 IBS: 0.15890943670542573
Fold 3 IBS: 0.15943165605774504
Fold 4 IBS: 0.2530754193060665
Fold 5 IBS: 0.2067458510386084
[I 2024-04-17 13:52:25,623] Trial 36 finished with value: 0.19840933732139815 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388504396434987
Fold 2 IBS: 0.16585949299087127
Fold 3 IBS: 0.16671464350482498
Fold 4 IBS: 0.2203924143320638
Fold 5 IBS: 0.20875334129802325
[I 2024-04-17 13:52:26,820] Trial 37 finished with value: 0.19512098721802665 and parameters: {'l1_ratio': 0.18682792683948743}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388449874161955
Fold 2 IBS: 0.1595343705390496
Fold 3 IBS: 0.162455339510555
Fold 4 IBS: 0.23359233146327452
Fold 5 IBS: 0.20702355660468416
[I 2024-04-17 13:52:28,619] Trial 38 finished with value: 0.19529801937183658 and parameters: {'l1_ratio': 0.45771876757877905}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388443190442696
Fold 2 IBS: 0.1590912638501747
Fold 3 IBS: 0.16166922770779402
Fold 4 IBS: 0.2363622517896411
Fold 5 IBS: 0.20704136325934305
[I 2024-04-17 13:52:33,780] Trial 39 finished with value: 0.19560970770227598 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388678506943376
Fold 2 IBS: 0.17461157134821073
Fold 3 IBS: 0.17121108523438172
Fold 4 IBS: 0.20744424631103073
Fold 5 IBS: 0.21132629904075428
[I 2024-04-17 13:52:35,881] Trial 40 finished with value: 0.19569599740076227 and parameters: {'l1_ratio': 0.0639292283416876}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388550582609897
Fold 2 IBS: 0.16909271822822922
Fold 3 IBS: 0.1685091555055672
Fold 4 IBS: 0.2127915443445282
Fold 5 IBS: 0.20960940875918138
[I 2024-04-17 13:52:36,769] Trial 41 finished with value: 0.194777666532721 and parameters: {'l1_ratio': 0.12413186537228227}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388551269728448
Fold 2 IBS: 0.16912937101272482
Fold 3 IBS: 0.16852901358993827
Fold 4 IBS: 0.21272436623683508
Fold 5 IBS: 0.20962146312994534
[I 2024-04-17 13:52:37,523] Trial 42 finished with value: 0.1947779453333456 and parameters: {'l1_ratio': 0.12351307692928809}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388485337023996
Fold 2 IBS: 0.16404033889834538
Fold 3 IBS: 0.16560099298452924
Fold 4 IBS: 0.22566827296867553
Fold 5 IBS: 0.20817587879098592
[I 2024-04-17 13:52:38,259] Trial 43 finished with value: 0.19547406740255518 and parameters: {'l1_ratio': 0.23572250405128312}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388625290971056
Fold 2 IBS: 0.17269082670940955
Fold 3 IBS: 0.1703659159478419
Fold 4 IBS: 0.2088650491254996
Fold 5 IBS: 0.21047826471204123
[I 2024-04-17 13:52:39,023] Trial 44 finished with value: 0.1952572618809006 and parameters: {'l1_ratio': 0.08020174180679346}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.2138850748562121
Fold 2 IBS: 0.16611730480926887
Fold 3 IBS: 0.16688271366120244
Fold 4 IBS: 0.2196241696915432
Fold 5 IBS: 0.20885606228333942
[I 2024-04-17 13:52:39,864] Trial 45 finished with value: 0.19507306506031322 and parameters: {'l1_ratio': 0.18074152502476082}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388768524898152
Fold 2 IBS: 0.17698794316063435
Fold 3 IBS: 0.17216702356779326
Fold 4 IBS: 0.20559016076777933
Fold 5 IBS: 0.21276104703181814
[I 2024-04-17 13:52:40,674] Trial 46 finished with value: 0.19627877195540133 and parameters: {'l1_ratio': 0.047460004053920854}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388458079727196
Fold 2 IBS: 0.1608224830838945
Fold 3 IBS: 0.1634316445651023
Fold 4 IBS: 0.23199356138561114
Fold 5 IBS: 0.20729605884722965
[I 2024-04-17 13:52:41,456] Trial 47 finished with value: 0.1954856657358219 and parameters: {'l1_ratio': 0.375956744467147}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.2138856258442328
Fold 2 IBS: 0.16973434809812474
Fold 3 IBS: 0.1688328314198906
Fold 4 IBS: 0.21162840768365684
Fold 5 IBS: 0.2098096956953032
[I 2024-04-17 13:52:42,227] Trial 48 finished with value: 0.19477818174824163 and parameters: {'l1_ratio': 0.11413571784863555}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388469945089175
Fold 2 IBS: 0.1623271045038768
Fold 3 IBS: 0.16449428466208885
Fold 4 IBS: 0.2296433804597519
Fold 5 IBS: 0.20768795967148324
[I 2024-04-17 13:52:42,997] Trial 49 finished with value: 0.1956074857496185 and parameters: {'l1_ratio': 0.2986914434548803}. Best is trial 16 with value: 0.19476258456850729.

Fold 1 IBS: 0.21388481103829365
Fold 2 IBS: 0.1635776383794378
Fold 3 IBS: 0.16534058181800254
Fold 4 IBS: 0.2268193955278957
Fold 5 IBS: 0.20804684108284635
[I 2024-04-17 13:52:43,796] Trial 50 finished with value: 0.19553385356929517 and parameters: {'l1_ratio': 0.2502435094853836}. Best is trial 16 with value: 0.19476258456850729.
Fold 1 IBS: 0.21388558340209102
Fold 2 IBS: 0.16950659347353192
Fold 3 IBS: 0.16872663625043585
Fold 4 IBS: 0.21193990109863584
Fold 5 IBS: 0.20974120742218041
[I 2024-04-17 13:52:44,563] Trial 51 finished with value: 0.194759984329375 and parameters: {'l1_ratio': 0.11748326911570342}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388527732510756
Fold 2 IBS: 0.16760320538408446
Fold 3 IBS: 0.16776826690118662
Fold 4 IBS: 0.21575459111337
Fold 5 IBS: 0.20928166030074472
[I 2024-04-17 13:52:45,293] Trial 52 finished with value: 0.19485860020489867 and parameters: {'l1_ratio': 0.1488949868435126}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138849724825398
Fold 2 IBS: 0.1652182810036751
Fold 3 IBS: 0.16628119823281146
Fold 4 IBS: 0.22237747412019232
Fold 5 IBS: 0.20850789243558754
[I 2024-04-17 13:52:46,115] Trial 53 finished with value: 0.19525396365496123 and parameters: {'l1_ratio': 0.20260303301532323}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138855214061542
Fold 2 IBS: 0.16917724788507796
Fold 3 IBS: 0.16855431568199356
Fold 4 IBS: 0.21260854557331846
Fold 5 IBS: 0.20963488690759316
[I 2024-04-17 13:52:46,951] Trial 54 finished with value: 0.19477210349082746 and parameters: {'l1_ratio': 0.12273751444873798}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388437705748195
Fold 2 IBS: 0.15910866538347643
Fold 3 IBS: 0.16098021243135463
Fold 4 IBS: 0.240194994698345
Fold 5 IBS: 0.20685227088501937
[I 2024-04-17 13:52:47,698] Trial 55 finished with value: 0.19620410409113548 and parameters: {'l1_ratio': 0.6751302644579473}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388847683090412
Fold 2 IBS: 0.17839019228401934
Fold 3 IBS: 0.17270847410425771
Fold 4 IBS: 0.20349162315450356
Fold 5 IBS: 0.21350401508639733
[I 2024-04-17 13:52:48,481] Trial 56 finished with value: 0.1963965562920164 and parameters: {'l1_ratio': 0.03859934637670906}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388527396420887
Fold 2 IBS: 0.16757947992240055
Fold 3 IBS: 0.1677559016648167
Fold 4 IBS: 0.21580644936550894
Fold 5 IBS: 0.20927522395093553
[I 2024-04-17 13:52:49,293] Trial 57 finished with value: 0.19486046577357413 and parameters: {'l1_ratio': 0.1493324036045417}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138860949255912
Fold 2 IBS: 0.17201668943339263
Fold 3 IBS: 0.17005213464439264
Fold 4 IBS: 0.20941214488797238
Fold 5 IBS: 0.21030413724155558
[I 2024-04-17 13:52:50,184] Trial 58 finished with value: 0.19513424022658088 and parameters: {'l1_ratio': 0.08672056767253691}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388493415127266
Fold 2 IBS: 0.16485501150474216
Fold 3 IBS: 0.16605618750621126
Fold 4 IBS: 0.22345689105942784
Fold 5 IBS: 0.20838816343526034
[I 2024-04-17 13:52:50,930] Trial 59 finished with value: 0.19532823753138284 and parameters: {'l1_ratio': 0.21220343184671603}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2139154259534003
Fold 2 IBS: 0.22157067138254166
Fold 3 IBS: 0.20444966552301674
Fold 4 IBS: 0.22427644426337398
Fold 5 IBS: 0.21813705913714468
[I 2024-04-17 13:52:51,420] Trial 60 finished with value: 0.21646985325189547 and parameters: {'l1_ratio': 0.004088828318257937}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388562902094602
Fold 2 IBS: 0.16974859823620433
Fold 3 IBS: 0.16884019188799235
Fold 4 IBS: 0.2116085221180428
Fold 5 IBS: 0.20981295190828222
[I 2024-04-17 13:52:52,237] Trial 61 finished with value: 0.19477917863429356 and parameters: {'l1_ratio': 0.11389273481105755}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388552373318534
Fold 2 IBS: 0.16919256714474315
Fold 3 IBS: 0.16856101373886206
Fold 4 IBS: 0.21258214763810984
Fold 5 IBS: 0.20963889511587205
[I 2024-04-17 13:52:52,995] Trial 62 finished with value: 0.19477202947415448 and parameters: {'l1_ratio': 0.12253191157104826}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138851461132869
Fold 2 IBS: 0.1666618251253922
Fold 3 IBS: 0.1672340244054324
Fold 4 IBS: 0.21811076617337402
Fold 5 IBS: 0.2090303888333342
[I 2024-04-17 13:52:53,746] Trial 63 finished with value: 0.19498443013016392 and parameters: {'l1_ratio': 0.16810004068556078}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388744879344215
Fold 2 IBS: 0.17643483864421242
Fold 3 IBS: 0.17193170133141641
Fold 4 IBS: 0.20608039933475525
Fold 5 IBS: 0.2124075571611705
[I 2024-04-17 13:52:54,540] Trial 64 finished with value: 0.19614838905299936 and parameters: {'l1_ratio': 0.05092376969027011}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138853722558911
Fold 2 IBS: 0.16827184205625623
Fold 3 IBS: 0.1680919664089951
Fold 4 IBS: 0.21433785357150603
Fold 5 IBS: 0.20944512620004035
[I 2024-04-17 13:52:55,419] Trial 65 finished with value: 0.1948064320985378 and parameters: {'l1_ratio': 0.13750972134743858}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388600308706598
Fold 2 IBS: 0.1715965662419469
Fold 3 IBS: 0.16984669953843098
Fold 4 IBS: 0.20978883633844408
Fold 5 IBS: 0.21019291543710267
[I 2024-04-17 13:52:56,230] Trial 66 finished with value: 0.19506220412859815 and parameters: {'l1_ratio': 0.09101276235755824}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388508873882167
Fold 2 IBS: 0.1662251057999748
Fold 3 IBS: 0.1669552719039665
Fold 4 IBS: 0.21930217801815044
Fold 5 IBS: 0.20890105640417034
[I 2024-04-17 13:52:57,073] Trial 67 finished with value: 0.19505374017301674 and parameters: {'l1_ratio': 0.1781327708288951}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388479649023392
Fold 2 IBS: 0.1634146877543466
Fold 3 IBS: 0.16524296918408943
Fold 4 IBS: 0.22722259874042497
Fold 5 IBS: 0.20800130680675546
[I 2024-04-17 13:52:58,048] Trial 68 finished with value: 0.19555327179517007 and parameters: {'l1_ratio': 0.25565358213883527}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138894095590766
Fold 2 IBS: 0.1795592045413592
Fold 3 IBS: 0.20440365789685538
Fold 4 IBS: 0.20098054400390356
Fold 5 IBS: 0.21413004768967014
[I 2024-04-17 13:52:58,848] Trial 69 finished with value: 0.202592572738173 and parameters: {'l1_ratio': 0.03156032679037282}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138849404725745
Fold 2 IBS: 0.16491528934956026
Fold 3 IBS: 0.1660909664678654
Fold 4 IBS: 0.2232621130445057
Fold 5 IBS: 0.20840880489797578
[I 2024-04-17 13:52:59,799] Trial 70 finished with value: 0.19531242284649633 and parameters: {'l1_ratio': 0.2105584276882883}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388573163271288
Fold 2 IBS: 0.17027347237098
Fold 3 IBS: 0.16914235742937664
Fold 4 IBS: 0.21108561064739156
Fold 5 IBS: 0.20995563119038735
[I 2024-04-17 13:53:00,777] Trial 71 finished with value: 0.19486856065416971 and parameters: {'l1_ratio': 0.10655928212431943}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138855412178912
Fold 2 IBS: 0.1692837412486855
Fold 3 IBS: 0.1686111179779359
Fold 4 IBS: 0.21239491140237762
Fold 5 IBS: 0.20966867983083406
[I 2024-04-17 13:53:01,597] Trial 72 finished with value: 0.19476879833554486 and parameters: {'l1_ratio': 0.121008601189031}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388682486914584
Fold 2 IBS: 0.1747339524410114
Fold 3 IBS: 0.17126305986726353
Fold 4 IBS: 0.20736564434424268
Fold 5 IBS: 0.21139490329842758
[I 2024-04-17 13:53:02,385] Trial 73 finished with value: 0.1957288769640182 and parameters: {'l1_ratio': 0.06296952616030684}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388544399421092
Fold 2 IBS: 0.16873706449078094
Fold 3 IBS: 0.1683218336743435
Fold 4 IBS: 0.21349979445029846
Fold 5 IBS: 0.20951518686893908
[I 2024-04-17 13:53:03,158] Trial 74 finished with value: 0.19479186469571458 and parameters: {'l1_ratio': 0.12998913014855162}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388470729713813

Fold 2 IBS: 0.16239750342334874
Fold 3 IBS: 0.16456201974352128
Fold 4 IBS: 0.22945154984812816
Fold 5 IBS: 0.20770967185975572
[I 2024-04-17 13:53:04,044] Trial 75 finished with value: 0.1956010904343784 and parameters: {'l1_ratio': 0.29468292253424555}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388502233310006
Fold 2 IBS: 0.16566965231804723
Fold 3 IBS: 0.1665909613525107
Fold 4 IBS: 0.22097489860294398
Fold 5 IBS: 0.20867617295680735
[I 2024-04-17 13:53:04,920] Trial 76 finished with value: 0.19515934151268186 and parameters: {'l1_ratio': 0.19133788941063262}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388517825050982
Fold 2 IBS: 0.16689172117757953
Fold 3 IBS: 0.16736821993035889
Fold 4 IBS: 0.21750519282022215
Fold 5 IBS: 0.20909360240651484
[I 2024-04-17 13:53:06,000] Trial 77 finished with value: 0.19494878291703704 and parameters: {'l1_ratio': 0.1629557902167686}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388639622944478
Fold 2 IBS: 0.1732567097925353
Fold 3 IBS: 0.17063238943399725
Fold 4 IBS: 0.2084056015151154
Fold 5 IBS: 0.21060519285222712
[I 2024-04-17 13:53:06,921] Trial 78 finished with value: 0.19535725796466397 and parameters: {'l1_ratio': 0.07507073912161163}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21389081734060766
Fold 2 IBS: 0.1809123909719523
Fold 3 IBS: 0.20440632720353288
Fold 4 IBS: 0.1979223366936304
Fold 5 IBS: 0.21485480474054733
[I 2024-04-17 13:53:07,845] Trial 79 finished with value: 0.20239733539005417 and parameters: {'l1_ratio': 0.02464587065410441}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138853891126074
Fold 2 IBS: 0.16839118818662138
Fold 3 IBS: 0.16814785591887335
Fold 4 IBS: 0.21412878975399485
Fold 5 IBS: 0.2094605429918249
[I 2024-04-17 13:53:08,871] Trial 80 finished with value: 0.1948027531927844 and parameters: {'l1_ratio': 0.13566614567323354}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138855940016849
Fold 2 IBS: 0.16956513168301246
Fold 3 IBS: 0.16875501243987012
Fold 4 IBS: 0.21184526182542915
Fold 5 IBS: 0.20975798631097986
[I 2024-04-17 13:53:09,788] Trial 81 finished with value: 0.1947617972521953 and parameters: {'l1_ratio': 0.11662918325251556}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138857784335848
Fold 2 IBS: 0.17050270225739197
Fold 3 IBS: 0.16927559809528292
Fold 4 IBS: 0.21081069491830848
Fold 5 IBS: 0.21000170841879467
[I 2024-04-17 13:53:10,686] Trial 82 finished with value: 0.19489529642467257 and parameters: {'l1_ratio': 0.10351586133705698}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388491060890566
Fold 2 IBS: 0.16462938633549978
Fold 3 IBS: 0.16592551521286464
Fold 4 IBS: 0.22415573775338216
Fold 5 IBS: 0.20830701467069865
[I 2024-04-17 13:53:11,762] Trial 83 finished with value: 0.19538051291627018 and parameters: {'l1_ratio': 0.21856136514533217}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388557531508096
Fold 2 IBS: 0.16946448777081746
Fold 3 IBS: 0.16870485214165337
Fold 4 IBS: 0.21203179096903615
Fold 5 IBS: 0.20972749216500136
[I 2024-04-17 13:53:12,977] Trial 84 finished with value: 0.19476283967231786 and parameters: {'l1_ratio': 0.11814326531913051}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388688999342143
Fold 2 IBS: 0.1749296047308597
Fold 3 IBS: 0.1713457476974495
Fold 4 IBS: 0.2072567377740651
Fold 5 IBS: 0.2114937211939137
[I 2024-04-17 13:53:14,003] Trial 85 finished with value: 0.1957825402779419 and parameters: {'l1_ratio': 0.06145863612499422}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388517324852638
Fold 2 IBS: 0.16685538427326246
Fold 3 IBS: 0.16734758603968172
Fold 4 IBS: 0.21758549014222212
Fold 5 IBS: 0.20908390758875353
[I 2024-04-17 13:53:15,602] Trial 86 finished with value: 0.19495150825848923 and parameters: {'l1_ratio': 0.1637358341864951}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.2138859649544402
Fold 2 IBS: 0.17141579879870283
Fold 3 IBS: 0.16975320325730586
Fold 4 IBS: 0.20994817341712468
Fold 5 IBS: 0.2101532786880409
[I 2024-04-17 13:53:16,891] Trial 87 finished with value: 0.1950312838231229 and parameters: {'l1_ratio': 0.09292048367209163}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.213884863898325
Fold 2 IBS: 0.1641517948832143
Fold 3 IBS: 0.1656631151883869
Fold 4 IBS: 0.2254161515356238
Fold 5 IBS: 0.20819911732696053
[I 2024-04-17 13:53:18,335] Trial 88 finished with value: 0.1954630085665021 and parameters: {'l1_ratio': 0.23236775984510674}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388979326653854
Fold 2 IBS: 0.1799775216398628
Fold 3 IBS: 0.2044043875762606
Fold 4 IBS: 0.20000713601638406
Fold 5 IBS: 0.2143785307509676
[I 2024-04-17 13:53:19,578] Trial 89 finished with value: 0.20253147385000272 and parameters: {'l1_ratio': 0.029335965941427025}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388539220606453
Fold 2 IBS: 0.168415562292642
Fold 3 IBS: 0.16815750040639074
Fold 4 IBS: 0.2140937959148392
Fold 5 IBS: 0.209463504157841
[I 2024-04-17 13:53:21,146] Trial 90 finished with value: 0.1948031509955555 and parameters: {'l1_ratio': 0.13533312805299305}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388503496980088
Fold 2 IBS: 0.16578178011505806
Fold 3 IBS: 0.16666382597373583
Fold 4 IBS: 0.2206366193686469
Fold 5 IBS: 0.2087210303246388
[I 2024-04-17 13:53:22,976] Trial 91 finished with value: 0.1951376581503761 and parameters: {'l1_ratio': 0.188677322807765}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388557329293595
Fold 2 IBS: 0.1694533107862801
Fold 3 IBS: 0.1686993889991095
Fold 4 IBS: 0.21205071529769778
Fold 5 IBS: 0.20972403520263921
[I 2024-04-17 13:53:25,387] Trial 92 finished with value: 0.19476260471573253 and parameters: {'l1_ratio': 0.11830944440944538}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388632535142477
Fold 2 IBS: 0.172982127937419
Fold 3 IBS: 0.17050249424919256
Fold 4 IBS: 0.20863688398029848
Fold 5 IBS: 0.21054311480444793
[I 2024-04-17 13:53:27,139] Trial 93 finished with value: 0.19531018926455657 and parameters: {'l1_ratio': 0.07752490583400298}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388434759353217
Fold 2 IBS: 0.159311234765262
Fold 3 IBS: 0.16031028781359338
Fold 4 IBS: 0.24531579415147767
Fold 5 IBS: 0.20671920655099993
[I 2024-04-17 13:53:28,639] Trial 94 finished with value: 0.197108174174973 and parameters: {'l1_ratio': 0.7627599976984654}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388523788367178
Fold 2 IBS: 0.16732786402531016
Fold 3 IBS: 0.16761699533375557
Fold 4 IBS: 0.2164320510969107
Fold 5 IBS: 0.20920064334744362
[I 2024-04-17 13:53:30,259] Trial 95 finished with value: 0.19489255833741836 and parameters: {'l1_ratio': 0.15419393681407917}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388452612163614
Fold 2 IBS: 0.15980028852357026
Fold 3 IBS: 0.16274336560206246
Fold 4 IBS: 0.23298049526373837
Fold 5 IBS: 0.20697096610298188
[I 2024-04-17 13:53:32,069] Trial 96 finished with value: 0.19527592832279783 and parameters: {'l1_ratio': 0.4267622685092021}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388567950315202
Fold 2 IBS: 0.17001311945141598
Fold 3 IBS: 0.16898435761473835
Fold 4 IBS: 0.21128025606014678
Fold 5 IBS: 0.20988982273829673
[I 2024-04-17 13:53:34,094] Trial 97 finished with value: 0.19481064707354998 and parameters: {'l1_ratio': 0.11016427289815275}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388545726176889
Fold 2 IBS: 0.16881485790648362
Fold 3 IBS: 0.1683627992797716
Fold 4 IBS: 0.21331071030128199
Fold 5 IBS: 0.20953137529036747
[I 2024-04-17 13:53:35,796] Trial 98 finished with value: 0.19478104000793472 and parameters: {'l1_ratio': 0.12868666374997623}. Best is trial 51 with value: 0.194759984329375.
Fold 1 IBS: 0.21388749841965957
Fold 2 IBS: 0.17655216928419978
Fold 3 IBS: 0.1719962933283064
Fold 4 IBS: 0.20597715090042126
Fold 5 IBS: 0.21247213850328067
[I 2024-04-17 13:53:38,068] Trial 99 finished with value: 0.1961770500871735 and parameters: {'l1_ratio': 0.05015662482142473}. Best is trial 51 with value: 0.194759984329375.


* Best trial for IBS:
 FrozenTrial(number=51, state=TrialState.COMPLETE, values=[0.194759984329375], datetime_start=datetime.datetime(2024, 4, 17, 13, 52, 43, 800948), datetime_complete=datetime.datetime(2024, 4, 17, 13, 52, 44, 563216), params={'l1_ratio': 0.11748326911570342}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=51, value=None)


* Best Score for IBS:
 0.194759984329375

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.717
train_ibs:  0.195

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.352181905423733)

test_cindex : 0.597

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.11748326911570342)

test_ibs:  0.221

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 13:53:38,519] A new study created in memory with name: no-name-c230e67a-c35f-40d1-ab50-98ec5e49a278

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 13:54:04,068] Trial 0 finished with value: 0.7366032203169602 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 13:54:09,407] Trial 1 finished with value: 0.7181620567966567 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6948356807511737
[I 2024-04-17 13:54:14,452] Trial 2 finished with value: 0.7150860129299454 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:54:15,334] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:54:16,517] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 13:54:23,448] Trial 5 finished with value: 0.7100749491193421 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:54:49,593] Trial 6 finished with value: 0.727952663180055 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:54:51,675] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6056338028169014
[I 2024-04-17 13:54:57,809] Trial 8 finished with value: 0.5211267605633803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 13:55:02,245] Trial 9 finished with value: 0.7080431320407382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:55:02,725] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 13:55:18,849] Trial 11 finished with value: 0.7380484783177279 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 11 with value: 0.7380484783177279.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 13:55:41,994] Trial 12 finished with value: 0.7438602547617209 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4617373338142137, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 13:56:02,285] Trial 13 finished with value: 0.7433165908059199 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.430322282186733, 'max_features': None, 'min_weight_fraction_leaf': 0.1716937452680298, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:05,908] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.4652312819220314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3866899818434614, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:15,007] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.27229846028530913, 'max_features': None, 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.

Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6032863849765259
[I 2024-04-17 13:56:18,177] Trial 16 finished with value: 0.6633327721070438 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': None, 'min_weight_fraction_leaf': 0.1048543527585735, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:26,605] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.1424705672746025, 'max_features': None, 'min_weight_fraction_leaf': 0.20205510510599584, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 13:56:30,696] Trial 18 finished with value: 0.7335541813688149 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5392320730567087, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07958856082174798, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.5892018779342723
[I 2024-04-17 13:56:31,141] Trial 19 finished with value: 0.6638449108877411 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.5137509360533721, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16593096906146954, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:37,504] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8114307622571267, 'max_features': None, 'min_weight_fraction_leaf': 0.41597694280469266, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 13:56:52,834] Trial 21 finished with value: 0.7398700280611442 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.3990347915810166, 'max_features': None, 'min_weight_fraction_leaf': 0.14443114491291786, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:56:59,110] Trial 22 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.21351240485158024, 'max_features': None, 'min_weight_fraction_leaf': 0.2441929681165364, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 13:57:13,095] Trial 23 finished with value: 0.7271164711934142 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.3756805451824067, 'max_features': None, 'min_weight_fraction_leaf': 0.13775089899883528, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:57:21,797] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36406078817327137, 'max_features': None, 'min_weight_fraction_leaf': 0.1822392883483817, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 13:57:27,475] Trial 25 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.4837577457111593, 'max_features': None, 'min_weight_fraction_leaf': 0.27111099648458864, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:57:31,465] Trial 26 finished with value: 0.7952997362091728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.425133711322363, 'max_features': None, 'min_weight_fraction_leaf': 0.07929595127017089, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 13:57:33,649] Trial 27 finished with value: 0.7439785302441695 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.5634050049825258, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07348058796691775, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 13:57:35,394] Trial 28 finished with value: 0.7606780234987396 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.5671295227568508, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002810616935067567, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:57:37,103] Trial 29 finished with value: 0.7861497989039858 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06647154253337151, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7981220657276995
[I 2024-04-17 13:57:38,688] Trial 30 finished with value: 0.7826158421682422 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.670660906330469, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008496584402552174, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8571428571428571

Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 13:57:40,335] Trial 31 finished with value: 0.7936613975238874 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.7258118850709611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020186907613437947, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8169014084507042
[I 2024-04-17 13:57:41,527] Trial 32 finished with value: 0.7892741864327053 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 149, 'oob_score': True, 'max_samples': 0.7060378252364139, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04618667534698639, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 13:57:42,793] Trial 33 finished with value: 0.8006493236932368 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 155, 'oob_score': True, 'max_samples': 0.7605972338377621, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046274896708941554, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 13:57:43,995] Trial 34 finished with value: 0.7998566890977854 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.7633408434752601, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04380970481841874, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8356807511737089
[I 2024-04-17 13:57:44,712] Trial 35 finished with value: 0.803331848306836 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.7948212261000067, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10423395463781872, 'warm_start': True}. Best is trial 35 with value: 0.803331848306836.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 13:57:45,285] Trial 36 finished with value: 0.81388019672447 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8091332552149437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10837446978579603, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 13:57:45,871] Trial 37 finished with value: 0.8138484554748331 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.8220720793755758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09608472875949194, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8075117370892019
[I 2024-04-17 13:57:46,441] Trial 38 finished with value: 0.794834129497761 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8537902740382926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09525205057743304, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.863849765258216
[I 2024-04-17 13:57:47,005] Trial 39 finished with value: 0.8134528027162501 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9833072699349469, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10393928454601242, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8591549295774648
[I 2024-04-17 13:57:47,687] Trial 40 finished with value: 0.8193359257510359 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 79, 'oob_score': False, 'max_samples': 0.9974049101283982, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11156682941225779, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8309859154929577
[I 2024-04-17 13:57:48,265] Trial 41 finished with value: 0.8034774490599819 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9999220055692117, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12045420312726329, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 13:57:48,819] Trial 42 finished with value: 0.809391720026152 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.9881165529835445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12443985149382927, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8685446009389671
[I 2024-04-17 13:57:49,308] Trial 43 finished with value: 0.8118099200814217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.9912995656748597, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12253835631192889, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7535211267605634
[I 2024-04-17 13:57:49,588] Trial 44 finished with value: 0.7512725179741098 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.9192360586272437, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09432875921172784, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.8169014084507042
[I 2024-04-17 13:57:49,960] Trial 45 finished with value: 0.7805310602984772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 35, 'oob_score': False, 'max_samples': 0.8671059553512112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22329822046282632, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 13:57:50,652] Trial 46 finished with value: 0.7374183107739604 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 123, 'oob_score': False, 'max_samples': 0.9536184653009308, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1531269560181571, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 13:57:51,123] Trial 47 finished with value: 0.821440909099989 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.8733003039936599, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12467981297687225, 'warm_start': True}. Best is trial 47 with value: 0.821440909099989.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 13:57:51,808] Trial 48 finished with value: 0.8304915258944628 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.8813820217761629, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06296378903734845, 'warm_start': True}. Best is trial 48 with value: 0.8304915258944628.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 13:57:52,555] Trial 49 finished with value: 0.8329500051937337 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.8805367238926652, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057195379787481515, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 13:57:53,333] Trial 50 finished with value: 0.8314528643350888 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.9009010945275224, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.054961351160765004, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 13:57:54,415] Trial 51 finished with value: 0.8313163540347663 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.8934638023278324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03450702765653768, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 13:57:55,554] Trial 52 finished with value: 0.8320214536162119 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.8797580746407682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024666679991640003, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 13:57:56,357] Trial 53 finished with value: 0.829623312030853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 118, 'oob_score': False, 'max_samples': 0.8886913182351664, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038639798107064416, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 13:57:57,449] Trial 54 finished with value: 0.8269793471449424 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.8943965597615428, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02658068365989562, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 13:57:58,351] Trial 55 finished with value: 0.8314821925869167 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.9394960211783968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03414063784444427, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 13:57:59,800] Trial 56 finished with value: 0.8291458931503687 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.9464163990983746, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05957529961744705, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 13:58:01,067] Trial 57 finished with value: 0.837497279418745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8375194335284916, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028965413024752612, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8732394366197183
[I 2024-04-17 13:58:02,194] Trial 58 finished with value: 0.8257460337171384 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.8473410457317984, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023049662318096596, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 13:58:03,473] Trial 59 finished with value: 0.8490112951451346 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9190157687794943, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013504221373780535, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 13:58:05,250] Trial 60 finished with value: 0.8462284069610924 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9302291542086784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020986391606638635, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 13:58:06,982] Trial 61 finished with value: 0.8471575518568665 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9319335934099356, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0028492650677599558, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 13:58:09,033] Trial 62 finished with value: 0.8424040571187227 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.9488273152669577, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006993125885435061, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 13:58:11,398] Trial 63 finished with value: 0.8459918151364014 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.9558680489418835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00656722209863304, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 13:58:13,675] Trial 64 finished with value: 0.8560377835959099 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9511852166403515, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006787286025552868, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 13:58:15,912] Trial 65 finished with value: 0.8543281008735688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.959702372838177, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0021045537516321865, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 13:58:18,367] Trial 66 finished with value: 0.846986714506221 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9606657832305625, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009645713200115154, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 13:58:20,811] Trial 67 finished with value: 0.8422965637980504 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 282, 'oob_score': False, 'max_samples': 0.9696946680213249, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015463863160716843, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 13:58:23,677] Trial 68 finished with value: 0.8400810425063071 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.9226346461200242, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013757163062800108, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6995305164319249
[I 2024-04-17 13:58:24,779] Trial 69 finished with value: 0.735120849138696 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9207461742012929, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3619470610261025, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 13:58:25,965] Trial 70 finished with value: 0.7199549229649882 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.9621462391123464, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4708820505432424, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 13:58:27,816] Trial 71 finished with value: 0.8477117723943335 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.95365805085536, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006547106868712814, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 13:58:30,777] Trial 72 finished with value: 0.8468137779836808 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.9218265096398339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002129212342459046, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 13:58:33,101] Trial 73 finished with value: 0.8355677775332243 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.7855691032277902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015061828643737101, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-17 13:58:34,655] Trial 74 finished with value: 0.8441728577198884 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9254876714681857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0812631651455817, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 13:58:37,150] Trial 75 finished with value: 0.8362371866524855 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.9681737785400921, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015964899054660966, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 13:58:39,483] Trial 76 finished with value: 0.84313576068201 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.8305113746650353, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0426275461746545, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 13:58:41,464] Trial 77 finished with value: 0.8568403814547748 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.9144336511700586, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01595057842588041, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-17 13:58:43,271] Trial 78 finished with value: 0.8419192289956712 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9116776901842412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07343560570014901, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 13:58:45,206] Trial 79 finished with value: 0.8328178212078037 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.8605744759700164, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023396832105227285, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 13:58:46,953] Trial 80 finished with value: 0.7687749931412297 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.969349688986363, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2986900237576432, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 13:58:49,224] Trial 81 finished with value: 0.8508482566919376 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9412070505938585, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01576257355000931, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 13:58:51,571] Trial 82 finished with value: 0.8416282042647364 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.9068065686971891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.016797956013047826, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8732394366197183
[I 2024-04-17 13:58:53,409] Trial 83 finished with value: 0.8318825303180803 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.6153744430709406, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04832190639289941, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 13:58:55,404] Trial 84 finished with value: 0.8433724935297382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.9399975078027157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0345364942691951, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 13:58:57,138] Trial 85 finished with value: 0.8358557576420413 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9737845589861637, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01634294636489071, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 13:58:59,406] Trial 86 finished with value: 0.8377019506647049 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.8518058828861286, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05107482426381401, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 13:59:07,977] Trial 87 finished with value: 0.7178329643580474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.9965938454935799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.034448975293513207, 'warm_start': False}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 13:59:10,258] Trial 88 finished with value: 0.8457089722953801 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.9085692767397662, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0697346803584661, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 13:59:13,420] Trial 89 finished with value: 0.836101128647378 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 375, 'oob_score': False, 'max_samples': 0.7981108690303841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012687139847991694, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 13:59:15,279] Trial 90 finished with value: 0.858196741029675 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9399104719362167, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04454154696608814, 'warm_start': True}. Best is trial 90 with value: 0.858196741029675.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 13:59:17,058] Trial 91 finished with value: 0.8594063157686616 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.9393175331158453, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0004448382541777079, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 13:59:19,048] Trial 92 finished with value: 0.8504093975391417 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.9511651006370562, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023794967159176263, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 13:59:20,860] Trial 93 finished with value: 0.8507722251285642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.9393138993988948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04166845875792434, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-17 13:59:22,765] Trial 94 finished with value: 0.864047670519609 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-17 13:59:24,467] Trial 95 finished with value: 0.8462994805857642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 226, 'oob_score': False, 'max_samples': 0.9851260930666599, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0877741788827067, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 13:59:25,886] Trial 96 finished with value: 0.8456767787505284 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.9046678790431277, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05908913791760474, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8169014084507042
[I 2024-04-17 13:59:27,018] Trial 97 finished with value: 0.7824887018130806 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.9994611759628653, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04096131539525037, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 13:59:34,347] Trial 98 finished with value: 0.7022847020297285 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9435261125804136, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025743264975163525, 'warm_start': False}. Best is trial 94 with value: 0.864047670519609.

[I 2024-04-17 13:59:35,668] A new study created in memory with name: no-name-4205b759-c1c6-4b1d-ad88-40118c5a27d8

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9061032863849765
[I 2024-04-17 13:59:35,652] Trial 99 finished with value: 0.8374434398307532 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8689674666549045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04663818112580286, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.864047670519609], datetime_start=datetime.datetime(2024, 4, 17, 13, 59, 20, 871197), datetime_complete=datetime.datetime(2024, 4, 17, 13, 59, 22, 765162), params={'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=94, value=None)


* Best Score for C-index:
 0.864047670519609

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18324615167630967
Fold 2 IBS: 0.1973414798718171
Fold 3 IBS: 0.16795049053724004
Fold 4 IBS: 0.18912813741469703
Fold 5 IBS: 0.2061164871654968
[I 2024-04-17 14:00:09,411] Trial 0 finished with value: 0.18875654933311214 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20345329363741022
Fold 2 IBS: 0.1866704968763983
Fold 3 IBS: 0.18211060269283327
Fold 4 IBS: 0.18446935355917493
Fold 5 IBS: 0.20613420199922336
[I 2024-04-17 14:00:10,992] Trial 1 finished with value: 0.19256758975300803 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-17 14:00:11,885] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-17 14:00:14,937] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-17 14:00:17,312] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20630791540283333
Fold 2 IBS: 0.18077183063689325
Fold 3 IBS: 0.18637698687972554
Fold 4 IBS: 0.15939882886870535
Fold 5 IBS: 0.2113504541273204
[I 2024-04-17 14:00:23,789] Trial 5 finished with value: 0.18884120318309558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.18286701090322455
Fold 2 IBS: 0.18771259904008297
Fold 3 IBS: 0.1679729459105892
Fold 4 IBS: 0.19488974663997188
Fold 5 IBS: 0.2131586526955741
[I 2024-04-17 14:00:42,368] Trial 6 finished with value: 0.18932019103788852 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20907943912609248
Fold 2 IBS: 0.2142874391649597
Fold 3 IBS: 0.20035786531447508
Fold 4 IBS: 0.22002960031246824
Fold 5 IBS: 0.21626779318082703
[I 2024-04-17 14:00:46,487] Trial 7 finished with value: 0.2120044274197645 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-17 14:00:53,045] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20357073593273053
Fold 2 IBS: 0.18780891594621849
Fold 3 IBS: 0.18460304549691883
Fold 4 IBS: 0.1856640301109529
Fold 5 IBS: 0.20794919209811308
[I 2024-04-17 14:00:54,850] Trial 9 finished with value: 0.19391918391698676 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-17 14:01:02,970] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20470418186342312
Fold 2 IBS: 0.20409550521820866
Fold 3 IBS: 0.19035125570755929
Fold 4 IBS: 0.20279707515139048
Fold 5 IBS: 0.2139020077116487
[I 2024-04-17 14:01:08,039] Trial 11 finished with value: 0.203170005130446 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20586437433035337
Fold 2 IBS: 0.18045352650478874
Fold 3 IBS: 0.18471158232105125
Fold 4 IBS: 0.1564532839984733
Fold 5 IBS: 0.21278485149213985
[I 2024-04-17 14:01:17,110] Trial 12 finished with value: 0.1880535237293613 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9944667777599061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10294337889507951}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.21738156589672325
Fold 2 IBS: 0.18148498524761636
Fold 3 IBS: 0.20328771782225072
Fold 4 IBS: 0.16200397997147525
Fold 5 IBS: 0.20246860054845137
[I 2024-04-17 14:03:10,688] Trial 13 finished with value: 0.1933253698973034 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.9694270540157217, 'max_features': None, 'min_weight_fraction_leaf': 0.1530029930440125}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19707033841317873
Fold 2 IBS: 0.1876771636325187
Fold 3 IBS: 0.1818736950861829
Fold 4 IBS: 0.179566358950222
Fold 5 IBS: 0.2109513215570391
[I 2024-04-17 14:03:19,727] Trial 14 finished with value: 0.19142777552782828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.7631177214580046, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21229864789095249}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.22655147877004286
Fold 2 IBS: 0.18326284905513224
Fold 3 IBS: 0.2097169134350128
Fold 4 IBS: 0.16586651259722404
Fold 5 IBS: 0.20952385709991683
[I 2024-04-17 14:04:22,309] Trial 15 finished with value: 0.19898432219146575 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.9970673523205843, 'max_features': None, 'min_weight_fraction_leaf': 0.09604984749674861}. Best is trial 12 with value: 0.1880535237293613.

Fold 1 IBS: 0.20378808796262518
Fold 2 IBS: 0.19365995427708668
Fold 3 IBS: 0.1882413702928391
Fold 4 IBS: 0.19759396434280763
Fold 5 IBS: 0.21553362503994042
[I 2024-04-17 14:04:35,796] Trial 16 finished with value: 0.19976340038305979 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8184724465806228, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31376919111755797}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20035161627096812
Fold 2 IBS: 0.18410251599192942
Fold 3 IBS: 0.18211883476245105
Fold 4 IBS: 0.18801743258981968
Fold 5 IBS: 0.21327804714656015
[I 2024-04-17 14:04:43,037] Trial 17 finished with value: 0.19357368935234567 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.3060837787360696, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005619770510688432}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19808389265211931
Fold 2 IBS: 0.18205953021252363
Fold 3 IBS: 0.185875813422921
Fold 4 IBS: 0.17434571756518558
Fold 5 IBS: 0.212414509617453
[I 2024-04-17 14:04:57,684] Trial 18 finished with value: 0.19055589269404052 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.680642613858846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12812974712655775}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19002039864329462
Fold 2 IBS: 0.18942385941547232
Fold 3 IBS: 0.18799087691719493
Fold 4 IBS: 0.18284504372921612
Fold 5 IBS: 0.20840823704233402
[I 2024-04-17 14:05:35,174] Trial 19 finished with value: 0.1917376831495024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.8923233540949727, 'max_features': None, 'min_weight_fraction_leaf': 0.22336599579981053}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20241484728756806
Fold 2 IBS: 0.19065053491089928
Fold 3 IBS: 0.18779471719312824
Fold 4 IBS: 0.19480082717000774
Fold 5 IBS: 0.21868104809372813
[I 2024-04-17 14:05:41,405] Trial 20 finished with value: 0.19886839493106628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.7871968885021372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34030385853489}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20741632570728089
Fold 2 IBS: 0.1780845098687536
Fold 3 IBS: 0.1846122378972077
Fold 4 IBS: 0.1564868201189816
Fold 5 IBS: 0.21131308248390057
[I 2024-04-17 14:05:51,621] Trial 21 finished with value: 0.18758259521522488 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.6541307441098512, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06381773403573333}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21885274316469258
Fold 2 IBS: 0.17828077601342465
Fold 3 IBS: 0.1880861120963736
Fold 4 IBS: 0.15017691808187725
Fold 5 IBS: 0.208661756520607
[I 2024-04-17 14:06:07,768] Trial 22 finished with value: 0.18881166117539502 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6139693116960656, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04453049413403026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19871040202258342
Fold 2 IBS: 0.184765649243245
Fold 3 IBS: 0.18498703463344066
Fold 4 IBS: 0.18599311903171908
Fold 5 IBS: 0.21143993706602787
[I 2024-04-17 14:06:13,451] Trial 23 finished with value: 0.1931792283994032 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20038924075539685
Fold 2 IBS: 0.18852724912576502
Fold 3 IBS: 0.1847265574388743
Fold 4 IBS: 0.19388302387911258
Fold 5 IBS: 0.21617210096544462
[I 2024-04-17 14:06:24,086] Trial 24 finished with value: 0.1967396344329187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.4295396819868078, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16813485936717243}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.23819448878865138
Fold 2 IBS: 0.18859860435971892
Fold 3 IBS: 0.19682793240255014
Fold 4 IBS: 0.15957526364066002
Fold 5 IBS: 0.20198931781322124
[I 2024-04-17 14:09:23,225] Trial 25 finished with value: 0.19703712140096036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.7297972378004723, 'max_features': None, 'min_weight_fraction_leaf': 0.04981104107775003}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.2010034177138824
Fold 2 IBS: 0.182735296255063
Fold 3 IBS: 0.18466236755017185
Fold 4 IBS: 0.17246211363358033
Fold 5 IBS: 0.21643410204328975
[I 2024-04-17 14:09:32,187] Trial 26 finished with value: 0.19145945943919745 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.8472363371748154, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10973545356505882}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.1964328885601889
Fold 2 IBS: 0.18809613601862848
Fold 3 IBS: 0.1818420692920181
Fold 4 IBS: 0.17399619732336324
Fold 5 IBS: 0.2111836724460323
[I 2024-04-17 14:09:47,079] Trial 27 finished with value: 0.19031019272804622 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9331113837900542, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2386001330983712}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19854249756198333
Fold 2 IBS: 0.18810793646188287
Fold 3 IBS: 0.18308123282699756
Fold 4 IBS: 0.18681900970293147
Fold 5 IBS: 0.21245937503700765
[I 2024-04-17 14:09:55,464] Trial 28 finished with value: 0.19380201031816058 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.5883566242401418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1845919041664691}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19840416643063166
Fold 2 IBS: 0.18537155668553762
Fold 3 IBS: 0.18344052151498125
Fold 4 IBS: 0.17492059658908363
Fold 5 IBS: 0.21086762605161444
[I 2024-04-17 14:10:07,443] Trial 29 finished with value: 0.19060089345436973 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.6774353138386819, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.22252593046960736
Fold 2 IBS: 0.1888838348535354
Fold 3 IBS: 0.19671883214571217
Fold 4 IBS: 0.162697984958246
Fold 5 IBS: 0.1971675681434196
[I 2024-04-17 14:10:48,425] Trial 30 finished with value: 0.19359883011410411 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.04202783134992163}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.218645817549917
Fold 2 IBS: 0.17984916123604971
Fold 3 IBS: 0.18930240115766292
Fold 4 IBS: 0.1502748627436339
Fold 5 IBS: 0.20680109594224744
[I 2024-04-17 14:11:03,279] Trial 31 finished with value: 0.18897466772590218 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6145656696996076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028279638075097074}. Best is trial 21 with value: 0.18758259521522488.

Fold 1 IBS: 0.20444739845582136
Fold 2 IBS: 0.17446698341767913
Fold 3 IBS: 0.1910994493903993
Fold 4 IBS: 0.1668825886510828
Fold 5 IBS: 0.21103427734544067
[I 2024-04-17 14:11:13,031] Trial 32 finished with value: 0.18958613945208463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.6325115094238634, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0760629688237641}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21394095082970305
Fold 2 IBS: 0.18957239420831615
Fold 3 IBS: 0.18237897227425182
Fold 4 IBS: 0.17846689832832333
Fold 5 IBS: 0.2185435449686763
[I 2024-04-17 14:11:14,024] Trial 33 finished with value: 0.19658055212185413 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.7088178154422675, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12510702348081404}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21814598296546053
Fold 2 IBS: 0.1806418667764422
Fold 3 IBS: 0.185193327742374
Fold 4 IBS: 0.14930927407248543
Fold 5 IBS: 0.20730315585697304
[I 2024-04-17 14:11:31,361] Trial 34 finished with value: 0.18811872148274703 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.5179281521096981, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03287535020826214}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20068393107082932
Fold 2 IBS: 0.18004564547293722
Fold 3 IBS: 0.1813279250878163
Fold 4 IBS: 0.16606271502196493
Fold 5 IBS: 0.2133678565084531
[I 2024-04-17 14:11:42,929] Trial 35 finished with value: 0.1882976146324002 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.5205069556471076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08931012896561974}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19921865381139617
Fold 2 IBS: 0.1879147544934006
Fold 3 IBS: 0.18415951307165418
Fold 4 IBS: 0.17928295771289782
Fold 5 IBS: 0.21187622162524927
[I 2024-04-17 14:11:49,079] Trial 36 finished with value: 0.19249042014291962 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.34556748843479757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08517804478502394}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20689459020742101
Fold 2 IBS: 0.18578195800005948
Fold 3 IBS: 0.18062395532410724
Fold 4 IBS: 0.16979980454141178
Fold 5 IBS: 0.20913380244139584
[I 2024-04-17 14:11:57,121] Trial 37 finished with value: 0.19044682210287905 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.19350535662381702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02562193860216446}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20164172687027268
Fold 2 IBS: 0.179042406474406
Fold 3 IBS: 0.18484112426907948
Fold 4 IBS: 0.15977140249838878
Fold 5 IBS: 0.2120612409546842
[I 2024-04-17 14:12:09,167] Trial 38 finished with value: 0.18747158021336624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.5607171176186949, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06539515726225846}. Best is trial 38 with value: 0.18747158021336624.
Fold 1 IBS: 0.20421151305171514
Fold 2 IBS: 0.17932735612158596
Fold 3 IBS: 0.17928162605465459
Fold 4 IBS: 0.16526541395746405
Fold 5 IBS: 0.2090081959308534
[I 2024-04-17 14:12:21,958] Trial 39 finished with value: 0.18741882102325463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.3617667691015132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052772428028015156}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2022159312451902
Fold 2 IBS: 0.1848488680529207
Fold 3 IBS: 0.17740255174053524
Fold 4 IBS: 0.1726825614136245
Fold 5 IBS: 0.213121743730351
[I 2024-04-17 14:12:32,688] Trial 40 finished with value: 0.19005433123652432 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.3736866960473132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05524155311927098}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.22304701735374977
Fold 2 IBS: 0.19262749474927982
Fold 3 IBS: 0.18617094771467074
Fold 4 IBS: 0.16090440652263122
Fold 5 IBS: 0.2060830161959264
[I 2024-04-17 14:12:45,580] Trial 41 finished with value: 0.1937665765072516 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.26471791598500466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008610506287772067}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.19780135900892157
Fold 2 IBS: 0.1857789376740191
Fold 3 IBS: 0.1799971131723769
Fold 4 IBS: 0.1804099527573313
Fold 5 IBS: 0.21177881228015194
[I 2024-04-17 14:12:59,327] Trial 42 finished with value: 0.19115323497856015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.5034748057992058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13666482964507704}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21400092589198996
Fold 2 IBS: 0.2214210103976947
Fold 3 IBS: 0.2048692155883072
Fold 4 IBS: 0.22463234501283708
Fold 5 IBS: 0.2185873987821863
[I 2024-04-17 14:13:06,553] Trial 43 finished with value: 0.21670217913460305 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.4788775563231737, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20231241634002334
Fold 2 IBS: 0.18036495206092895
Fold 3 IBS: 0.1818599860701185
Fold 4 IBS: 0.16340196628946066
Fold 5 IBS: 0.21378560467248073
[I 2024-04-17 14:13:19,227] Trial 44 finished with value: 0.18834498508660244 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.5506248755449263, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0721857441783233}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1973845412708107
Fold 2 IBS: 0.18124870301190693
Fold 3 IBS: 0.1810814354603528
Fold 4 IBS: 0.1707551433320944
Fold 5 IBS: 0.2119250973889522
[I 2024-04-17 14:13:34,563] Trial 45 finished with value: 0.18847898409282343 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.5775224127982328, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10537693884726008}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21070983930823925
Fold 2 IBS: 0.18608759362092114
Fold 3 IBS: 0.18204123382213788
Fold 4 IBS: 0.16642669368966861
Fold 5 IBS: 0.21219350314332874
[I 2024-04-17 14:13:49,244] Trial 46 finished with value: 0.19149177271685913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.26128950045955984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02835891103553452}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20296038593675553
Fold 2 IBS: 0.1835795355330322
Fold 3 IBS: 0.18270515601508316
Fold 4 IBS: 0.17696688246148076
Fold 5 IBS: 0.2124434684430158
[I 2024-04-17 14:13:57,605] Trial 47 finished with value: 0.19173108567787348 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.39724110016399944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06776177948204519}. Best is trial 39 with value: 0.18741882102325463.

Fold 1 IBS: 0.21397545241919333
Fold 2 IBS: 0.22060585341756236
Fold 3 IBS: 0.20519466411613427
Fold 4 IBS: 0.2248054198587066
Fold 5 IBS: 0.21758241895615993
[I 2024-04-17 14:14:06,034] Trial 48 finished with value: 0.2164327617535513 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.1840472657347053, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20733215663048163
Fold 2 IBS: 0.19840873877308707
Fold 3 IBS: 0.1896647344947966
Fold 4 IBS: 0.2057146078926162
Fold 5 IBS: 0.2152447795126918
[I 2024-04-17 14:14:11,873] Trial 49 finished with value: 0.20327300346073468 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.4611544071310423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02536063881705921}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.204879944056226
Fold 2 IBS: 0.18198982906903266
Fold 3 IBS: 0.1813060638484819
Fold 4 IBS: 0.16283844353857155
Fold 5 IBS: 0.21363299219754156
[I 2024-04-17 14:14:23,048] Trial 50 finished with value: 0.18892945454197077 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.5416005248904892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0034087820600749476}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2004109367454522
Fold 2 IBS: 0.18404020643987526
Fold 3 IBS: 0.18234193379348762
Fold 4 IBS: 0.17143012200567861
Fold 5 IBS: 0.21239169444633466
[I 2024-04-17 14:14:32,992] Trial 51 finished with value: 0.19012297868616568 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.5290774243115414, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09439815236719598}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20363791714493526
Fold 2 IBS: 0.18084498958548437
Fold 3 IBS: 0.1865787886727044
Fold 4 IBS: 0.15958133230330762
Fold 5 IBS: 0.21346890098280094
[I 2024-04-17 14:14:45,318] Trial 52 finished with value: 0.18882238573784652 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.646747773042784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08961848913350215}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20381819322938977
Fold 2 IBS: 0.18114674744033232
Fold 3 IBS: 0.18113417018982886
Fold 4 IBS: 0.1618949090102553
Fold 5 IBS: 0.21456765862332783
[I 2024-04-17 14:15:01,922] Trial 53 finished with value: 0.18851233569862683 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.5080082016246513, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06630490839370301}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2042758448261322
Fold 2 IBS: 0.18877763887578689
Fold 3 IBS: 0.18209755324442445
Fold 4 IBS: 0.19391559310720333
Fold 5 IBS: 0.2159060762300408
[I 2024-04-17 14:15:10,906] Trial 54 finished with value: 0.1969945412567175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.38392655290485045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1447625548982195}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2034151090750003
Fold 2 IBS: 0.18176049250213502
Fold 3 IBS: 0.1857336365331899
Fold 4 IBS: 0.1788179124206326
Fold 5 IBS: 0.2129610073834551
[I 2024-04-17 14:15:20,333] Trial 55 finished with value: 0.1925376315828826 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.5872802927086659, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046825551317268566}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20422176706868694
Fold 2 IBS: 0.1924062351097664
Fold 3 IBS: 0.18544969707631245
Fold 4 IBS: 0.1984840238620755
Fold 5 IBS: 0.21497590518150314
[I 2024-04-17 14:15:28,148] Trial 56 finished with value: 0.19910752565966888 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.4154965081431159, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18037694403417448}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2059789858573675
Fold 2 IBS: 0.1967683996639164
Fold 3 IBS: 0.18831908034352698
Fold 4 IBS: 0.20147608897626476
Fold 5 IBS: 0.21654528774605497
[I 2024-04-17 14:15:35,007] Trial 57 finished with value: 0.20181756851742616 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7776350329623957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3781865060679536}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20703604925067237
Fold 2 IBS: 0.18243435974189295
Fold 3 IBS: 0.18268181766890698
Fold 4 IBS: 0.20149520002925903
Fold 5 IBS: 0.21479477144824155
[I 2024-04-17 14:15:38,580] Trial 58 finished with value: 0.1976884396277946 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.32208030951555616, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11116699744055775}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21121978023043514
Fold 2 IBS: 0.17834386764399476
Fold 3 IBS: 0.18431619963737042
Fold 4 IBS: 0.15794559160168345
Fold 5 IBS: 0.211915583151784
[I 2024-04-17 14:15:55,921] Trial 59 finished with value: 0.18874820445305357 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.706317491452594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06164379588338738}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1966264720209345
Fold 2 IBS: 0.18597478555674649
Fold 3 IBS: 0.1786448987547083
Fold 4 IBS: 0.16171860015636114
Fold 5 IBS: 0.20668689381001223
[I 2024-04-17 14:16:56,525] Trial 60 finished with value: 0.18593033005975254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.4446079220615766, 'max_features': None, 'min_weight_fraction_leaf': 0.09271318262887082}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2024856806183152
Fold 2 IBS: 0.18195716111018798
Fold 3 IBS: 0.18480931433897935
Fold 4 IBS: 0.16237325049629045
Fold 5 IBS: 0.20714210552628523
[I 2024-04-17 14:17:58,617] Trial 61 finished with value: 0.18775350241801164 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 306, 'oob_score': True, 'max_samples': 0.44685465277095665, 'max_features': None, 'min_weight_fraction_leaf': 0.08682673693183435}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2284531812120082
Fold 2 IBS: 0.1948622570457934
Fold 3 IBS: 0.18812485157230974
Fold 4 IBS: 0.16088214458625358
Fold 5 IBS: 0.20190289439703843
[I 2024-04-17 14:19:31,714] Trial 62 finished with value: 0.19484506576268068 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.4515303316200064, 'max_features': None, 'min_weight_fraction_leaf': 0.037039554766136004}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2252402779389061
Fold 2 IBS: 0.1862300882985594
Fold 3 IBS: 0.18602106947089103
Fold 4 IBS: 0.17312433407761857
Fold 5 IBS: 0.1889042172268272
[I 2024-04-17 14:21:07,591] Trial 63 finished with value: 0.19190399740256042 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.41265009702186795, 'max_features': None, 'min_weight_fraction_leaf': 0.016364606682246152}. Best is trial 60 with value: 0.18593033005975254.

Fold 1 IBS: 0.18697650055709675
Fold 2 IBS: 0.18964751614322145
Fold 3 IBS: 0.17157067951262514
Fold 4 IBS: 0.17048079186700552
Fold 5 IBS: 0.20812563312237994
[I 2024-04-17 14:21:57,264] Trial 64 finished with value: 0.18536022424046578 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.36087148528744895, 'max_features': None, 'min_weight_fraction_leaf': 0.10501492814170305}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.185980269157479
Fold 2 IBS: 0.18929665176523391
Fold 3 IBS: 0.17261558628019577
Fold 4 IBS: 0.17528863593015434
Fold 5 IBS: 0.20987976574068176
[I 2024-04-17 14:22:33,945] Trial 65 finished with value: 0.18661218177474898 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.35503340896452096, 'max_features': None, 'min_weight_fraction_leaf': 0.10944245403951429}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18694115431926822
Fold 2 IBS: 0.1908501583998164
Fold 3 IBS: 0.17205632092618067
Fold 4 IBS: 0.18203552427470343
Fold 5 IBS: 0.21326387492637428
[I 2024-04-17 14:23:08,292] Trial 66 finished with value: 0.1890294065692686 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.3614405881665075, 'max_features': None, 'min_weight_fraction_leaf': 0.12510407630083206}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397879618526044
Fold 2 IBS: 0.22095626300254492
Fold 3 IBS: 0.2049272671362546
Fold 4 IBS: 0.2246487203312697
Fold 5 IBS: 0.21797754042983516
[I 2024-04-17 14:23:17,594] Trial 67 finished with value: 0.21649771741703297 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.277566908191509, 'max_features': None, 'min_weight_fraction_leaf': 0.16326642133899677}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18701806869001636
Fold 2 IBS: 0.19002615779169066
Fold 3 IBS: 0.17109529332077666
Fold 4 IBS: 0.17558286313646593
Fold 5 IBS: 0.20866467885193285
[I 2024-04-17 14:23:52,546] Trial 68 finished with value: 0.1864774123581765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.3339648956191334, 'max_features': None, 'min_weight_fraction_leaf': 0.10534737249789848}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.213990042339758
Fold 2 IBS: 0.22081844148187832
Fold 3 IBS: 0.2049164994171005
Fold 4 IBS: 0.22451019970461408
Fold 5 IBS: 0.2178161153197119
[I 2024-04-17 14:24:00,011] Trial 69 finished with value: 0.21641025965261257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.22058879264036, 'max_features': None, 'min_weight_fraction_leaf': 0.14500630501117967}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397438613021721
Fold 2 IBS: 0.22116611565870514
Fold 3 IBS: 0.20499774371165358
Fold 4 IBS: 0.22471498188046043
Fold 5 IBS: 0.21823664145637212
[I 2024-04-17 14:24:06,989] Trial 70 finished with value: 0.21661797376748168 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.34596416260173934, 'max_features': None, 'min_weight_fraction_leaf': 0.2703111919415455}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18924036720156343
Fold 2 IBS: 0.18779280930051329
Fold 3 IBS: 0.17209448151288856
Fold 4 IBS: 0.17958207486087677
Fold 5 IBS: 0.211566257073253
[I 2024-04-17 14:24:37,169] Trial 71 finished with value: 0.18805519798981898 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.31453931029426085, 'max_features': None, 'min_weight_fraction_leaf': 0.1045230982104525}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19657952397027323
Fold 2 IBS: 0.19022838128535594
Fold 3 IBS: 0.1708771341601037
Fold 4 IBS: 0.17168544722624235
Fold 5 IBS: 0.20713375074665116
[I 2024-04-17 14:25:09,304] Trial 72 finished with value: 0.1873008474777253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.2926475761323768, 'max_features': None, 'min_weight_fraction_leaf': 0.07798192572483449}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19885306195698255
Fold 2 IBS: 0.18210548225096054
Fold 3 IBS: 0.17731375226506932
Fold 4 IBS: 0.16883406032672896
Fold 5 IBS: 0.20809348652266163
[I 2024-04-17 14:25:34,682] Trial 73 finished with value: 0.18703996866448058 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.2870778190236743, 'max_features': None, 'min_weight_fraction_leaf': 0.05561809788206867}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.193787788585605
Fold 2 IBS: 0.18733247875335163
Fold 3 IBS: 0.17837994780791747
Fold 4 IBS: 0.1744246643744868
Fold 5 IBS: 0.21343920626735596
[I 2024-04-17 14:25:59,514] Trial 74 finished with value: 0.1894728171577434 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.22588589287949842, 'max_features': None, 'min_weight_fraction_leaf': 0.05443689708608288}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18723429594597044
Fold 2 IBS: 0.18527389087754653
Fold 3 IBS: 0.17197014707614233
Fold 4 IBS: 0.1772724521433817
Fold 5 IBS: 0.21429754155065364
[I 2024-04-17 14:26:26,043] Trial 75 finished with value: 0.1872096655187389 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.2998143519691557, 'max_features': None, 'min_weight_fraction_leaf': 0.1075330144825516}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1941066110336133
Fold 2 IBS: 0.18509351343143435
Fold 3 IBS: 0.17110131699959152
Fold 4 IBS: 0.18270444973194716
Fold 5 IBS: 0.21156937371299012
[I 2024-04-17 14:26:47,246] Trial 76 finished with value: 0.1889150529819153 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.28316698675748087, 'max_features': None, 'min_weight_fraction_leaf': 0.12059869029554741}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397695237476239
Fold 2 IBS: 0.22118615223089322
Fold 3 IBS: 0.2050313552835387
Fold 4 IBS: 0.2247532956416355
Fold 5 IBS: 0.21820980850510233
[I 2024-04-17 14:26:54,017] Trial 77 finished with value: 0.21663151280718643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.3371898508848934, 'max_features': None, 'min_weight_fraction_leaf': 0.2048303246846501}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.195733817221237
Fold 2 IBS: 0.18784802284526486
Fold 3 IBS: 0.1763445138354909
Fold 4 IBS: 0.17500708454376265
Fold 5 IBS: 0.20952700605055732
[I 2024-04-17 14:27:26,871] Trial 78 finished with value: 0.18889208889926254 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.29504437594758753, 'max_features': None, 'min_weight_fraction_leaf': 0.07587622273136602}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21396670472446544
Fold 2 IBS: 0.22085379157505564
Fold 3 IBS: 0.20493941845669997
Fold 4 IBS: 0.22470262306501207
Fold 5 IBS: 0.21714959439503256
[I 2024-04-17 14:27:35,361] Trial 79 finished with value: 0.21632242644325314 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.13307661238331164, 'max_features': None, 'min_weight_fraction_leaf': 0.11597487641803922}. Best is trial 64 with value: 0.18536022424046578.

Fold 1 IBS: 0.2139852535910293
Fold 2 IBS: 0.22079135086710738
Fold 3 IBS: 0.2049571432154721
Fold 4 IBS: 0.22449984942587378
Fold 5 IBS: 0.21784420818016068
[I 2024-04-17 14:27:43,525] Trial 80 finished with value: 0.21641556105592863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.23317876663764808, 'max_features': None, 'min_weight_fraction_leaf': 0.13195032778351135}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18698963922132994
Fold 2 IBS: 0.19117908340974094
Fold 3 IBS: 0.1716425830420473
Fold 4 IBS: 0.1706227695034198
Fold 5 IBS: 0.20890166136319582
[I 2024-04-17 14:28:16,590] Trial 81 finished with value: 0.1858671473079468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.3619448678095568, 'max_features': None, 'min_weight_fraction_leaf': 0.10057070644705586}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1890967403784016
Fold 2 IBS: 0.18652324224983566
Fold 3 IBS: 0.17238080905282963
Fold 4 IBS: 0.16710329314707312
Fold 5 IBS: 0.209650785925764
[I 2024-04-17 14:28:52,429] Trial 82 finished with value: 0.18495097415078082 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.3624030825154118, 'max_features': None, 'min_weight_fraction_leaf': 0.09714741335387223}. Best is trial 82 with value: 0.18495097415078082.
Fold 1 IBS: 0.1869379635607008
Fold 2 IBS: 0.1840979377124555
Fold 3 IBS: 0.1723208864840007
Fold 4 IBS: 0.16624305438296152
Fold 5 IBS: 0.20739680918357425
[I 2024-04-17 14:29:35,605] Trial 83 finished with value: 0.18339933026473856 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.39234117831739307, 'max_features': None, 'min_weight_fraction_leaf': 0.09956600887465704}. Best is trial 83 with value: 0.18339933026473856.
Fold 1 IBS: 0.1886542770417182
Fold 2 IBS: 0.18606078762892803
Fold 3 IBS: 0.17038230752313355
Fold 4 IBS: 0.1646204973275064
Fold 5 IBS: 0.20651428479641726
[I 2024-04-17 14:30:14,106] Trial 84 finished with value: 0.1832464308635407 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19155628917728368
Fold 2 IBS: 0.1801885982714529
Fold 3 IBS: 0.17804730003931615
Fold 4 IBS: 0.1693620308491127
Fold 5 IBS: 0.20783919776163526
[I 2024-04-17 14:30:42,891] Trial 85 finished with value: 0.18539868321976014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.3968957116262019, 'max_features': None, 'min_weight_fraction_leaf': 0.095219664847033}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18538493455740376
Fold 2 IBS: 0.18576229943013492
Fold 3 IBS: 0.17402978107752123
Fold 4 IBS: 0.18507755128123915
Fold 5 IBS: 0.21358478244911275
[I 2024-04-17 14:31:02,873] Trial 86 finished with value: 0.18876786975908236 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.38638292055767265, 'max_features': None, 'min_weight_fraction_leaf': 0.17872796639110672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19006306497707842
Fold 2 IBS: 0.1859568983552553
Fold 3 IBS: 0.17526064526770588
Fold 4 IBS: 0.16110281294560094
Fold 5 IBS: 0.20520872126963988
[I 2024-04-17 14:31:43,492] Trial 87 finished with value: 0.18351842856305606 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.4051015506296675, 'max_features': None, 'min_weight_fraction_leaf': 0.09713693453540154}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19767011171898427
Fold 2 IBS: 0.17964734520295073
Fold 3 IBS: 0.1836195742480708
Fold 4 IBS: 0.1667956970154799
Fold 5 IBS: 0.2070890710759274
[I 2024-04-17 14:32:14,430] Trial 88 finished with value: 0.1869643598522826 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.4334251281469186, 'max_features': None, 'min_weight_fraction_leaf': 0.09492515708957672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18447989656323524
Fold 2 IBS: 0.1882071335854152
Fold 3 IBS: 0.17009416602918556
Fold 4 IBS: 0.18175070837886942
Fold 5 IBS: 0.21200575266539284
[I 2024-04-17 14:32:40,092] Trial 89 finished with value: 0.18730753144441964 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.40662933261411155, 'max_features': None, 'min_weight_fraction_leaf': 0.14538592818664145}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18291200990480525
Fold 2 IBS: 0.18829799983042705
Fold 3 IBS: 0.174582652991839
Fold 4 IBS: 0.1734065332761776
Fold 5 IBS: 0.2073726719246909
[I 2024-04-17 14:33:19,254] Trial 90 finished with value: 0.18531437358558794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.46906936332717275, 'max_features': None, 'min_weight_fraction_leaf': 0.1301923106019002}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18483018153750577
Fold 2 IBS: 0.18822465780769382
Fold 3 IBS: 0.1731074140071581
Fold 4 IBS: 0.17188948389568984
Fold 5 IBS: 0.20714468645851628
[I 2024-04-17 14:34:00,832] Trial 91 finished with value: 0.18503928474131276 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.47678737384020253, 'max_features': None, 'min_weight_fraction_leaf': 0.1325172709355868}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18950832462950518
Fold 2 IBS: 0.18701656820376608
Fold 3 IBS: 0.17893499023469356
Fold 4 IBS: 0.17722915182580176
Fold 5 IBS: 0.20663881973138198
[I 2024-04-17 14:34:37,345] Trial 92 finished with value: 0.18786557092502973 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.49169288583702514, 'max_features': None, 'min_weight_fraction_leaf': 0.13392414841790756}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19861247726074407
Fold 2 IBS: 0.17973057843635412
Fold 3 IBS: 0.185421278409284
Fold 4 IBS: 0.16412850305110133
Fold 5 IBS: 0.20541831001893
[I 2024-04-17 14:35:33,504] Trial 93 finished with value: 0.1866622294352827 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4745011682049886, 'max_features': None, 'min_weight_fraction_leaf': 0.09685737891379577}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19722640593255503
Fold 2 IBS: 0.18658267818572852
Fold 3 IBS: 0.17931575780016162
Fold 4 IBS: 0.15937059058391914
Fold 5 IBS: 0.20605274303785986
[I 2024-04-17 14:36:17,032] Trial 94 finished with value: 0.1857096351080448 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.4244190509544878, 'max_features': None, 'min_weight_fraction_leaf': 0.08390492642221409}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18486260175817798
Fold 2 IBS: 0.18637157071560814
Fold 3 IBS: 0.17201029045136673
Fold 4 IBS: 0.18278192459752535
Fold 5 IBS: 0.21486338860156232
[I 2024-04-17 14:36:40,428] Trial 95 finished with value: 0.1881779552248481 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.3768152460146832, 'max_features': None, 'min_weight_fraction_leaf': 0.16125627455265384}. Best is trial 84 with value: 0.1832464308635407.

Fold 1 IBS: 0.19987889711029083
Fold 2 IBS: 0.18568352389906653
Fold 3 IBS: 0.18380646487398802
Fold 4 IBS: 0.16033813976360883
Fold 5 IBS: 0.20642365546571148
[I 2024-04-17 14:37:30,050] Trial 96 finished with value: 0.18722613622253315 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 363, 'oob_score': False, 'max_samples': 0.4255182801365352, 'max_features': None, 'min_weight_fraction_leaf': 0.08056036420837291}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19365837237754394
Fold 2 IBS: 0.183435405665406
Fold 3 IBS: 0.18008910470800357
Fold 4 IBS: 0.17339462295545943
Fold 5 IBS: 0.20781358095494984
[I 2024-04-17 14:37:59,432] Trial 97 finished with value: 0.18767821733227258 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4693979321374093, 'max_features': None, 'min_weight_fraction_leaf': 0.1201270975782226}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18503478594867145
Fold 2 IBS: 0.1888913820526276
Fold 3 IBS: 0.1708577577733008
Fold 4 IBS: 0.18063206055766248
Fold 5 IBS: 0.214156204168513
[I 2024-04-17 14:38:22,268] Trial 98 finished with value: 0.18791443810015507 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.3850920531360686, 'max_features': None, 'min_weight_fraction_leaf': 0.1315399576273898}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.20344124949745349
Fold 2 IBS: 0.18698507294354125
Fold 3 IBS: 0.1879934856478453
Fold 4 IBS: 0.1880278288749208
Fold 5 IBS: 0.2133922668795308
[I 2024-04-17 14:38:29,442] Trial 99 finished with value: 0.19596798076865835 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.40653139828572354, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08424550739812792}. Best is trial 84 with value: 0.1832464308635407.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.1832464308635407], datetime_start=datetime.datetime(2024, 4, 17, 14, 29, 35, 615311), datetime_complete=datetime.datetime(2024, 4, 17, 14, 30, 14, 104873), params={'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.1832464308635407

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.864
train_ibs:  0.183

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [58]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=11, max_features='auto', max_leaf_nodes=15,
                     max_samples=0.9847467855272036, min_samples_leaf=4,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.04749646122417352,
                     n_estimators=230, random_state=123, warm_start=True)

test_cindex:  0.629

RandomSurvivalForest(max_depth=2, max_features=None, max_leaf_nodes=7,
                     max_samples=0.3902292236281065, min_samples_leaf=4,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.0959966989881746,
                     n_estimators=344, random_state=123)

test_ibs:  0.205

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [61]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 14:38:43,541] A new study created in memory with name: no-name-9fb45f90-7b94-470f-8bed-5b9c09a15c88

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:38:45,388] Trial 0 finished with value: 0.7784578545189774 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:38:49,579] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 14:38:59,211] Trial 2 finished with value: 0.7601142724144229 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:39:00,203] Trial 3 finished with value: 0.802961090796227 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:03,835] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:08,105] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 14:39:10,537] Trial 6 finished with value: 0.7670018279196149 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6150234741784038
[I 2024-04-17 14:39:16,450] Trial 7 finished with value: 0.6820130047188975 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:39:17,231] Trial 8 finished with value: 0.7996535923726207 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.5539906103286385
[I 2024-04-17 14:39:28,417] Trial 9 finished with value: 0.6684380652697066 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:30,126] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6737089201877934
[I 2024-04-17 14:39:30,518] Trial 11 finished with value: 0.7252477001554444 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 14:39:31,181] Trial 12 finished with value: 0.7795687852038334 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 14:39:32,180] Trial 13 finished with value: 0.7859770734903794 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:33,302] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:33,849] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.40889055344541997}. Best is trial 3 with value: 0.802961090796227.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 14:39:34,642] Trial 16 finished with value: 0.7903520467896392 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.884183184043622, 'min_weight_fraction_leaf': 0.10581506507448754}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:35,925] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.37217752523657055, 'min_weight_fraction_leaf': 0.19947678741058694}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:39:36,779] Trial 18 finished with value: 0.7422562391542786 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 21, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6674013857794929, 'min_weight_fraction_leaf': 0.0023155280568105674}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:39:37,846] Trial 19 finished with value: 0.7919172217583121 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 177, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.35588501080184637}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-17 14:39:38,650] Trial 20 finished with value: 0.7884100418072868 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7140167187076433, 'min_weight_fraction_leaf': 0.28881891871571913}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 14:39:40,248] Trial 21 finished with value: 0.7828532818336494 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8819344617828546, 'min_weight_fraction_leaf': 0.3430677365625254}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-17 14:39:41,384] Trial 22 finished with value: 0.7949143304625697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8606079420302547, 'min_weight_fraction_leaf': 0.37164871595060495}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:42,379] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8095519124644711, 'min_weight_fraction_leaf': 0.44720270469880896}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:43,701] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6043934042800692, 'min_weight_fraction_leaf': 0.3984329214033346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7181372549019608
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6455399061032864
[I 2024-04-17 14:39:44,387] Trial 25 finished with value: 0.7173359925057237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9355023621313151, 'min_weight_fraction_leaf': 0.21828153747802176}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 14:39:48,860] Trial 26 finished with value: 0.75455954833675 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 172, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7429676103800898, 'min_weight_fraction_leaf': 0.2902550218399806}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 14:39:49,401] Trial 27 finished with value: 0.7870695134161543 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 32, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.07430019929598344}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 14:39:50,252] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 110, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6203838276523786, 'min_weight_fraction_leaf': 0.49397030324411406}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 14:39:52,118] Trial 29 finished with value: 0.7664099905509458 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7463806142458222, 'min_weight_fraction_leaf': 0.12619621560869665}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:39:53,421] Trial 30 finished with value: 0.7959507907686649 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9444316884960255, 'min_weight_fraction_leaf': 0.10548580221002543}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8235294117647058

Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 14:39:54,800] Trial 31 finished with value: 0.8023701302106281 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9175308644810205, 'min_weight_fraction_leaf': 0.1088935662786611}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:39:56,105] Trial 32 finished with value: 0.7950579336258078 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 211, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9467713628420997, 'min_weight_fraction_leaf': 0.08138167552522578}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 14:39:57,623] Trial 33 finished with value: 0.8061356825263047 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.937124800917338, 'min_weight_fraction_leaf': 0.10798501652350923}. Best is trial 33 with value: 0.8061356825263047.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 14:40:01,057] Trial 34 finished with value: 0.8069410046551562 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9924586053612823, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 34 with value: 0.8069410046551562.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8309859154929577
[I 2024-04-17 14:40:05,345] Trial 35 finished with value: 0.8337706480426819 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 307, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.99537727544732, 'min_weight_fraction_leaf': 0.04956730948759107}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:40:16,719] Trial 36 finished with value: 0.7482461120884926 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9947891025922952, 'min_weight_fraction_leaf': 0.040945703784245044}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8591549295774648
[I 2024-04-17 14:40:22,315] Trial 37 finished with value: 0.847904896492382 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.989290011992841, 'min_weight_fraction_leaf': 0.02856480473176247}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8544600938967136
[I 2024-04-17 14:40:28,028] Trial 38 finished with value: 0.8469659293562317 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9932170620443503, 'min_weight_fraction_leaf': 0.050004592573005685}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:40:45,850] Trial 39 finished with value: 0.7495415406312282 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9915601275040028, 'min_weight_fraction_leaf': 0.03663352433082424}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 14:40:52,658] Trial 40 finished with value: 0.8357412545967835 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.02508749840989511}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8403755868544601
[I 2024-04-17 14:40:58,865] Trial 41 finished with value: 0.8293587936722526 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47059202334413597, 'min_weight_fraction_leaf': 0.028824885734288947}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:41:05,697] Trial 42 finished with value: 0.8460265073711295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47951227685883335, 'min_weight_fraction_leaf': 0.013760080445973905}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 14:41:10,841] Trial 43 finished with value: 0.818279225092199 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3956943544905941, 'min_weight_fraction_leaf': 0.06238579527271516}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8544600938967136
[I 2024-04-17 14:41:17,012] Trial 44 finished with value: 0.8360856192344845 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 443, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4206894066469547, 'min_weight_fraction_leaf': 0.022459821558201455}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 14:41:24,805] Trial 45 finished with value: 0.8420095331119368 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5190626877291048, 'min_weight_fraction_leaf': 0.009502780876316706}. Best is trial 37 with value: 0.847904896492382.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 14:41:31,108] Trial 46 finished with value: 0.8220544611789512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.517469689795079, 'min_weight_fraction_leaf': 0.07841045931780831}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 14:41:50,968] Trial 47 finished with value: 0.7254847827232809 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 414, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.32086266244117334, 'min_weight_fraction_leaf': 0.01763716368072068}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8450704225352113
[I 2024-04-17 14:41:57,360] Trial 48 finished with value: 0.8350464295509287 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 460, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4023308297410664, 'min_weight_fraction_leaf': 0.003079257502260936}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 14:42:02,820] Trial 49 finished with value: 0.8397048390094625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 368, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5566958033733842, 'min_weight_fraction_leaf': 0.05919578966108157}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 14:42:07,395] Trial 50 finished with value: 0.8168300522124603 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 355, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5346285785794207, 'min_weight_fraction_leaf': 0.05949010437559907}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:42:13,889] Trial 51 finished with value: 0.8426559761897272 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4307713618159553, 'min_weight_fraction_leaf': 0.0006143407440005848}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.863849765258216
[I 2024-04-17 14:42:19,855] Trial 52 finished with value: 0.8261414109558636 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.2944027889978438, 'min_weight_fraction_leaf': 0.0025196302934173548}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 14:42:24,551] Trial 53 finished with value: 0.7977685626836676 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.17582352730772366, 'min_weight_fraction_leaf': 0.061407856338507316}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7276995305164319
[I 2024-04-17 14:42:30,233] Trial 54 finished with value: 0.7531047646128582 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 473, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.44561277075368966, 'min_weight_fraction_leaf': 0.08811499948097072}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 14:42:38,273] Trial 55 finished with value: 0.8665875045053596 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5744229763504507, 'min_weight_fraction_leaf': 0.016027842870494274}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 14:42:42,881] Trial 56 finished with value: 0.6951645058986333 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.015257524234107825}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 14:42:49,826] Trial 57 finished with value: 0.8481318045459971 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6103451470664683, 'min_weight_fraction_leaf': 0.047571291705527236}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 14:42:54,151] Trial 58 finished with value: 0.7701604423354131 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.59366729390164, 'min_weight_fraction_leaf': 0.14674774348708902}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6807511737089202
[I 2024-04-17 14:43:14,834] Trial 59 finished with value: 0.758267844731695 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6716331483015671, 'min_weight_fraction_leaf': 0.04950449980370537}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 14:43:20,113] Trial 60 finished with value: 0.8025306955794198 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6374430422021584, 'min_weight_fraction_leaf': 0.16819923331696962}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 14:43:27,940] Trial 61 finished with value: 0.8267317399171535 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49232023541877573, 'min_weight_fraction_leaf': 0.00145953757858059}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 14:43:32,701] Trial 62 finished with value: 0.8414621270800418 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 402, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4565775326135385, 'min_weight_fraction_leaf': 0.0216071430745067}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8779342723004695
[I 2024-04-17 14:43:39,701] Trial 63 finished with value: 0.8515511699906788 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.574595322070414, 'min_weight_fraction_leaf': 0.04569685903621326}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8544600938967136
[I 2024-04-17 14:43:46,078] Trial 64 finished with value: 0.8397072520072715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5869227943626324, 'min_weight_fraction_leaf': 0.04476269499363313}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 14:43:51,847] Trial 65 finished with value: 0.8070528716762316 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5714061896889552, 'min_weight_fraction_leaf': 0.09443804061211797}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 14:43:57,507] Trial 66 finished with value: 0.8117060028439325 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4269898374784659, 'min_weight_fraction_leaf': 0.06693452124581281}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 14:44:01,610] Trial 67 finished with value: 0.8090148375189878 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 375, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8415815579585453, 'min_weight_fraction_leaf': 0.03102886731531589}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:44:06,513] Trial 68 finished with value: 0.724330800854678 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6969921866106945, 'min_weight_fraction_leaf': 0.08996201441410404}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8685446009389671
[I 2024-04-17 14:44:11,678] Trial 69 finished with value: 0.8410235474195836 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6336109184394701, 'min_weight_fraction_leaf': 0.04462823296429158}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 14:44:16,086] Trial 70 finished with value: 0.7949235593846933 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9130147369001846, 'min_weight_fraction_leaf': 0.25717771363652614}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 14:44:23,958] Trial 71 finished with value: 0.8504560046599232 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5168055835891595, 'min_weight_fraction_leaf': 0.012986169067804712}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8967136150234741
[I 2024-04-17 14:44:30,986] Trial 72 finished with value: 0.8519584263631383 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5366958727104124, 'min_weight_fraction_leaf': 0.016031857840163272}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 14:44:37,694] Trial 73 finished with value: 0.8207791294121825 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5266040099828285, 'min_weight_fraction_leaf': 0.07379071659454789}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-17 14:44:45,257] Trial 74 finished with value: 0.8657901849373276 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.556218611994605, 'min_weight_fraction_leaf': 0.026708566480428787}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.812206572769953
[I 2024-04-17 14:44:49,574] Trial 75 finished with value: 0.8181142885767413 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.569175138136116, 'min_weight_fraction_leaf': 0.049779903595510204}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7136150234741784
[I 2024-04-17 14:45:08,434] Trial 76 finished with value: 0.7457830837322044 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.61013169816922, 'min_weight_fraction_leaf': 0.032654970370419666}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 14:45:13,719] Trial 77 finished with value: 0.813252260011932 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6556499931697389, 'min_weight_fraction_leaf': 0.11468485034119792}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 14:45:18,899] Trial 78 finished with value: 0.8054529568030716 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5407839514816556, 'min_weight_fraction_leaf': 0.13017998804408376}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:45:26,388] Trial 79 finished with value: 0.8680221676184047 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9631780533456042, 'min_weight_fraction_leaf': 0.022603700176597446}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 14:45:31,503] Trial 80 finished with value: 0.796736053008863 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5088492830088868, 'min_weight_fraction_leaf': 0.02502911966074306}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9295774647887324
[I 2024-04-17 14:45:39,199] Trial 81 finished with value: 0.882207251893772 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9615950289600182, 'min_weight_fraction_leaf': 0.03679139394563669}. Best is trial 81 with value: 0.882207251893772.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 14:45:46,217] Trial 82 finished with value: 0.8858022781309804 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9436619718309859
[I 2024-04-17 14:45:53,778] Trial 83 finished with value: 0.8652682964140128 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9609090906034798, 'min_weight_fraction_leaf': 0.01406330393712882}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 14:46:01,925] Trial 84 finished with value: 0.8614808250890755 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9134206211086566, 'min_weight_fraction_leaf': 0.01387175275139686}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 14:46:05,972] Trial 85 finished with value: 0.8498449433258773 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9573743509441937, 'min_weight_fraction_leaf': 0.037220356101627605}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-17 14:46:10,155] Trial 86 finished with value: 0.8063147993763705 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9691139339019299, 'min_weight_fraction_leaf': 0.013557733109048805}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:46:16,738] Trial 87 finished with value: 0.8606583123370746 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9145533784322645, 'min_weight_fraction_leaf': 0.07241658060725681}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:46:36,380] Trial 88 finished with value: 0.7577736506359624 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.91048505123246, 'min_weight_fraction_leaf': 0.07341369185217136}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 14:46:39,987] Trial 89 finished with value: 0.7985598378397373 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8690506465331735, 'min_weight_fraction_leaf': 0.189066433472832}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6713615023474179
[I 2024-04-17 14:46:43,610] Trial 90 finished with value: 0.7685681160339142 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8972668164493001, 'min_weight_fraction_leaf': 0.31515481216778163}. Best is trial 82 with value: 0.8858022781309804.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9483568075117371
[I 2024-04-17 14:46:50,728] Trial 91 finished with value: 0.862597275251046 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9707802904512073, 'min_weight_fraction_leaf': 0.024021851910904807}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-17 14:46:57,746] Trial 92 finished with value: 0.8605776934106274 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9280981755055671, 'min_weight_fraction_leaf': 0.023404006766994168}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-17 14:47:03,185] Trial 93 finished with value: 0.8582896374728435 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 320, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499587877144377, 'min_weight_fraction_leaf': 0.03127381290624083}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9014084507042254
[I 2024-04-17 14:47:09,242] Trial 94 finished with value: 0.8665655880498362 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666217297893754, 'min_weight_fraction_leaf': 0.058324374733458}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8873239436619719
[I 2024-04-17 14:47:15,093] Trial 95 finished with value: 0.8664219797791237 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9706033105898769, 'min_weight_fraction_leaf': 0.06930608338875063}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6901408450704225
[I 2024-04-17 14:47:18,726] Trial 96 finished with value: 0.7713977049757649 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9653170534920801, 'min_weight_fraction_leaf': 0.05657719832813177}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8497652582159625
[I 2024-04-17 14:47:23,394] Trial 97 finished with value: 0.8459290116474474 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9660782335192536, 'min_weight_fraction_leaf': 0.10022719516204912}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-17 14:47:29,849] Trial 98 finished with value: 0.8772114347448893 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470976294421786, 'min_weight_fraction_leaf': 0.037342531882997666}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907

[I 2024-04-17 14:47:35,465] A new study created in memory with name: no-name-52f025b6-1f2f-434e-b925-f33e0bffc57a

Fold 5 C-index: 0.8826291079812206
[I 2024-04-17 14:47:35,447] Trial 99 finished with value: 0.8535852615977915 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9441404618918096, 'min_weight_fraction_leaf': 0.08095118320482457}. Best is trial 82 with value: 0.8858022781309804.


* Best trial for C-index:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.8858022781309804], datetime_start=datetime.datetime(2024, 4, 17, 14, 45, 39, 209293), datetime_complete=datetime.datetime(2024, 4, 17, 14, 45, 46, 216842), params={'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for C-index:
 0.8858022781309804

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19573874032428965
Fold 2 IBS: 0.19215300245103015
Fold 3 IBS: 0.18577123192698092
Fold 4 IBS: 0.18877405090465085
Fold 5 IBS: 0.2108069355911196
[I 2024-04-17 14:47:41,864] Trial 0 finished with value: 0.19464879223961423 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-17 14:47:51,171] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.18661490821092397
Fold 2 IBS: 0.18849796485994302
Fold 3 IBS: 0.16935693688351927
Fold 4 IBS: 0.16616413385030462
Fold 5 IBS: 0.21353095384309942
[I 2024-04-17 14:48:00,296] Trial 2 finished with value: 0.18483297952955807 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18461528870168228
Fold 2 IBS: 0.19204843106240665
Fold 3 IBS: 0.16690491265843854
Fold 4 IBS: 0.1668314734874405
Fold 5 IBS: 0.21495543742143608
[I 2024-04-17 14:48:03,736] Trial 3 finished with value: 0.18507110866628082 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-17 14:48:11,570] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-17 14:48:15,549] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19873722451693057
Fold 2 IBS: 0.19705874496937723
Fold 3 IBS: 0.1849295300703863
Fold 4 IBS: 0.19065127758534944
Fold 5 IBS: 0.21038780527035808
[I 2024-04-17 14:48:23,773] Trial 6 finished with value: 0.1963529164824803 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2092186818635856
Fold 2 IBS: 0.2146879015458582
Fold 3 IBS: 0.2003062385248317
Fold 4 IBS: 0.21667734530345348
Fold 5 IBS: 0.2164099945650469
[I 2024-04-17 14:48:31,135] Trial 7 finished with value: 0.2114600323605552 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18257976996986042
Fold 2 IBS: 0.19411505967038614
Fold 3 IBS: 0.17136720904530045
Fold 4 IBS: 0.17268722966186423
Fold 5 IBS: 0.21366089922807047
[I 2024-04-17 14:48:32,596] Trial 8 finished with value: 0.18688203351509633 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21317294453259816
Fold 2 IBS: 0.21979053165324058
Fold 3 IBS: 0.20367290529718618
Fold 4 IBS: 0.22322856514743522
Fold 5 IBS: 0.21829561184880927
[I 2024-04-17 14:48:46,305] Trial 9 finished with value: 0.2156321116958539 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2139727346768592
Fold 2 IBS: 0.2213120202940904
Fold 3 IBS: 0.20503568053719107
Fold 4 IBS: 0.2245613118501098
Fold 5 IBS: 0.21766314539351875
[I 2024-04-17 14:48:59,518] Trial 10 finished with value: 0.21650897855035384 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19343732165265656
Fold 2 IBS: 0.18906543074097565
Fold 3 IBS: 0.17814248070868705
Fold 4 IBS: 0.17824816439818994
Fold 5 IBS: 0.2121006857387383
[I 2024-04-17 14:49:01,895] Trial 11 finished with value: 0.1901988166478495 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1889048827611632
Fold 2 IBS: 0.19557019296937925
Fold 3 IBS: 0.1711785441540699
Fold 4 IBS: 0.1739105142666198
Fold 5 IBS: 0.21378813670908908
[I 2024-04-17 14:49:05,546] Trial 12 finished with value: 0.18867045417206424 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21602403915542812
Fold 2 IBS: 0.22135942967444958
Fold 3 IBS: 0.207522129090302
Fold 4 IBS: 0.22681102026289354
Fold 5 IBS: 0.2196363896884173
[I 2024-04-17 14:49:06,096] Trial 13 finished with value: 0.21827060157429812 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.1768405475625161}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1908749026630227
Fold 2 IBS: 0.1928239743663976
Fold 3 IBS: 0.16705801079598037
Fold 4 IBS: 0.15060359337075535
Fold 5 IBS: 0.22085198243745763
[I 2024-04-17 14:49:09,304] Trial 14 finished with value: 0.18444249272672272 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8615610863035676, 'min_weight_fraction_leaf': 0.00662188941038383}. Best is trial 14 with value: 0.18444249272672272.

Fold 1 IBS: 0.18383586845275063
Fold 2 IBS: 0.2000835973214874
Fold 3 IBS: 0.15349960014749967
Fold 4 IBS: 0.13669669509253474
Fold 5 IBS: 0.23424660843190576
[I 2024-04-17 14:49:18,765] Trial 15 finished with value: 0.18167247388923563 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.0023088139988564262}. Best is trial 15 with value: 0.18167247388923563.
Fold 1 IBS: 0.1860236953856494
Fold 2 IBS: 0.2016030715036904
Fold 3 IBS: 0.155469005191737
Fold 4 IBS: 0.13731033566044606
Fold 5 IBS: 0.22747010982683524
[I 2024-04-17 14:49:27,939] Trial 16 finished with value: 0.1815752435136716 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8957765840335672, 'min_weight_fraction_leaf': 0.010191311991891749}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17998535045197436
Fold 2 IBS: 0.18813498335112747
Fold 3 IBS: 0.17047606760378545
Fold 4 IBS: 0.18020967518371683
Fold 5 IBS: 0.21407585022837167
[I 2024-04-17 14:49:33,897] Trial 17 finished with value: 0.18657638536379517 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9042785918294833, 'min_weight_fraction_leaf': 0.42038595995868033}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.21392851730727483
Fold 2 IBS: 0.2203112302740686
Fold 3 IBS: 0.20531706619567533
Fold 4 IBS: 0.22509036885374237
Fold 5 IBS: 0.21706040157641074
[I 2024-04-17 14:49:41,198] Trial 18 finished with value: 0.21634151684143438 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 312, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.22508105757456376}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1780064255903332
Fold 2 IBS: 0.1911276300331187
Fold 3 IBS: 0.16786438905278223
Fold 4 IBS: 0.1726113214449123
Fold 5 IBS: 0.21667391270579664
[I 2024-04-17 14:49:46,598] Trial 19 finished with value: 0.18525673576538862 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895543806821031, 'min_weight_fraction_leaf': 0.3097789443945588}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17575403131452658
Fold 2 IBS: 0.20366539827290087
Fold 3 IBS: 0.1659331777904529
Fold 4 IBS: 0.16662123172048018
Fold 5 IBS: 0.2231823176617039
[I 2024-04-17 14:49:54,499] Trial 20 finished with value: 0.18703123135201288 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8867517870122669, 'min_weight_fraction_leaf': 0.3678346055590361}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18848376456042643
Fold 2 IBS: 0.18922500536261308
Fold 3 IBS: 0.1744885363823047
Fold 4 IBS: 0.16595205181867084
Fold 5 IBS: 0.2141373046342922
[I 2024-04-17 14:49:56,967] Trial 21 finished with value: 0.18645733255166147 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8638184920383039, 'min_weight_fraction_leaf': 0.006217904257385862}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18773929580856016
Fold 2 IBS: 0.18598260697487606
Fold 3 IBS: 0.16906412373747556
Fold 4 IBS: 0.16368622468310087
Fold 5 IBS: 0.21228289069902992
[I 2024-04-17 14:50:02,629] Trial 22 finished with value: 0.18375102838060853 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9916304513453179, 'min_weight_fraction_leaf': 0.04142928400152037}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18853550770642435
Fold 2 IBS: 0.18431558910147325
Fold 3 IBS: 0.1692342266159003
Fold 4 IBS: 0.161355478193544
Fold 5 IBS: 0.21536507583817294
[I 2024-04-17 14:50:08,852] Trial 23 finished with value: 0.18376117549110296 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.971566349397283, 'min_weight_fraction_leaf': 0.048431151398292585}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18850231376560317
Fold 2 IBS: 0.18839766190435636
Fold 3 IBS: 0.17219466449743842
Fold 4 IBS: 0.169776646003973
Fold 5 IBS: 0.21215306500728826
[I 2024-04-17 14:50:13,138] Trial 24 finished with value: 0.18620487023573185 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9955995613709457, 'min_weight_fraction_leaf': 0.09809641655746978}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1921961203281156
Fold 2 IBS: 0.18453047987592264
Fold 3 IBS: 0.16816775310750728
Fold 4 IBS: 0.16025534556804477
Fold 5 IBS: 0.21319844694890142
[I 2024-04-17 14:50:20,119] Trial 25 finished with value: 0.18366962916569834 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8862362117578689, 'min_weight_fraction_leaf': 0.041224153446454304}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17583280457561398
Fold 2 IBS: 0.22475673220665077
Fold 3 IBS: 0.15629098950451684
Fold 4 IBS: 0.1521771664224135
Fold 5 IBS: 0.23338728904188227
[I 2024-04-17 14:50:32,222] Trial 26 finished with value: 0.1884889963502155 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 360, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7252723068238901, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.20101808740413787
Fold 2 IBS: 0.19364223596866614
Fold 3 IBS: 0.1581801817697089
Fold 4 IBS: 0.13490957896358
Fold 5 IBS: 0.22061607552916476
[I 2024-04-17 14:50:49,059] Trial 27 finished with value: 0.18167323192705154 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.845241798302616, 'min_weight_fraction_leaf': 0.027493332139652292}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18622176253816625
Fold 2 IBS: 0.1999255042061287
Fold 3 IBS: 0.15584044840112993
Fold 4 IBS: 0.13526516764544533
Fold 5 IBS: 0.22802733572495915
[I 2024-04-17 14:51:04,633] Trial 28 finished with value: 0.18105604370316586 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8292254352883182, 'min_weight_fraction_leaf': 0.0850371679063824}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.17657957905072683
Fold 2 IBS: 0.22919795735904133
Fold 3 IBS: 0.15929222778603266
Fold 4 IBS: 0.15524572509143825
Fold 5 IBS: 0.23445783766810277
[I 2024-04-17 14:51:15,983] Trial 29 finished with value: 0.19095466539106837 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7274266056837884, 'min_weight_fraction_leaf': 0.10433587359666342}. Best is trial 28 with value: 0.18105604370316586.

Fold 1 IBS: 0.18973195855840097
Fold 2 IBS: 0.19901752012782084
Fold 3 IBS: 0.1553163395473765
Fold 4 IBS: 0.13719070606611738
Fold 5 IBS: 0.22779776404493374
[I 2024-04-17 14:51:28,202] Trial 30 finished with value: 0.18181085766892985 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 305, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8220971907615917, 'min_weight_fraction_leaf': 0.076444606879153}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.2164877455822723
Fold 2 IBS: 0.18827035681808446
Fold 3 IBS: 0.16565039781780372
Fold 4 IBS: 0.1417428766421557
Fold 5 IBS: 0.21575647924950747
[I 2024-04-17 14:51:53,724] Trial 31 finished with value: 0.18558157122196473 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 394, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9184090898444338, 'min_weight_fraction_leaf': 0.024048041704110457}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.19225590417182326
Fold 2 IBS: 0.19791478229895018
Fold 3 IBS: 0.15389649317000442
Fold 4 IBS: 0.13656122267395734
Fold 5 IBS: 0.2252432881883185
[I 2024-04-17 14:52:06,242] Trial 32 finished with value: 0.18117433810061073 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 339, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8398341558075527, 'min_weight_fraction_leaf': 0.07586243370778376}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.190099017520626
Fold 2 IBS: 0.19508386306537273
Fold 3 IBS: 0.15693141894064483
Fold 4 IBS: 0.1365814363126798
Fold 5 IBS: 0.2242513991199539
[I 2024-04-17 14:52:18,290] Trial 33 finished with value: 0.18058942699185546 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 328, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7393625680125055, 'min_weight_fraction_leaf': 0.0754095802252665}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1755388893326841
Fold 2 IBS: 0.22138923578766054
Fold 3 IBS: 0.15690295668954182
Fold 4 IBS: 0.1534002161724209
Fold 5 IBS: 0.23198506769187896
[I 2024-04-17 14:52:26,930] Trial 34 finished with value: 0.18784327313483729 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6411042409555412, 'min_weight_fraction_leaf': 0.1529713735680485}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18263254865306666
Fold 2 IBS: 0.20049141147500113
Fold 3 IBS: 0.1589092797218102
Fold 4 IBS: 0.13938245171749084
Fold 5 IBS: 0.22964090743188564
[I 2024-04-17 14:52:45,165] Trial 35 finished with value: 0.1822113197998509 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7381816364515512, 'min_weight_fraction_leaf': 0.09309533777806683}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20497295855599004
Fold 2 IBS: 0.20576214803730022
Fold 3 IBS: 0.19198391113255453
Fold 4 IBS: 0.20085090326245184
Fold 5 IBS: 0.21341213707903006
[I 2024-04-17 14:52:53,060] Trial 36 finished with value: 0.2033964116134653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 329, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6138083294843051, 'min_weight_fraction_leaf': 0.0629620770536272}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19527602912356506
Fold 2 IBS: 0.19485558505510198
Fold 3 IBS: 0.18174564019749553
Fold 4 IBS: 0.1886871891677721
Fold 5 IBS: 0.21159832776451956
[I 2024-04-17 14:53:01,724] Trial 37 finished with value: 0.19443255426169087 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 415, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5042351390354268, 'min_weight_fraction_leaf': 0.11525786573963492}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.2123324981539864
Fold 2 IBS: 0.21873675502636114
Fold 3 IBS: 0.2026801887391686
Fold 4 IBS: 0.2224371860221609
Fold 5 IBS: 0.2175210624415119
[I 2024-04-17 14:53:06,705] Trial 38 finished with value: 0.21474153807663776 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7775660926270328, 'min_weight_fraction_leaf': 0.20133705660393178}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396615975925184
Fold 2 IBS: 0.22136475473478168
Fold 3 IBS: 0.2049150370158522
Fold 4 IBS: 0.22458804795980403
Fold 5 IBS: 0.21835431962555002
[I 2024-04-17 14:53:18,147] Trial 39 finished with value: 0.21663766381904798 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 8, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3933070032512962, 'min_weight_fraction_leaf': 0.26079682823609596}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19711707736031672
Fold 2 IBS: 0.19196214561471756
Fold 3 IBS: 0.18237907022466343
Fold 4 IBS: 0.1838407369325067
Fold 5 IBS: 0.21066154976207546
[I 2024-04-17 14:53:25,495] Trial 40 finished with value: 0.19319211597885597 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.06421109758861666}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18187508975758154
Fold 2 IBS: 0.20470571701119905
Fold 3 IBS: 0.15462214843892588
Fold 4 IBS: 0.13791700485858222
Fold 5 IBS: 0.23199241229585657
[I 2024-04-17 14:53:36,191] Trial 41 finished with value: 0.18222247447242906 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 287, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9487776860553198, 'min_weight_fraction_leaf': 0.0012764688125286236}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18083474896839194
Fold 2 IBS: 0.20655297055486127
Fold 3 IBS: 0.1560859878078812
Fold 4 IBS: 0.13735104264690487
Fold 5 IBS: 0.2318981646914065
[I 2024-04-17 14:53:51,301] Trial 42 finished with value: 0.18254458293388914 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 410, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9263396365475575, 'min_weight_fraction_leaf': 0.07533198780818874}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.179220247667936
Fold 2 IBS: 0.20803479971941155
Fold 3 IBS: 0.15642984958925052
Fold 4 IBS: 0.1381823380575358
Fold 5 IBS: 0.23098585177667733
[I 2024-04-17 14:54:00,648] Trial 43 finished with value: 0.18257061736216224 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8260902726928496, 'min_weight_fraction_leaf': 0.12086835806486591}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20295458389503712
Fold 2 IBS: 0.18760128987987226
Fold 3 IBS: 0.16259754916275176
Fold 4 IBS: 0.13943881701142766
Fold 5 IBS: 0.21929671791406735
[I 2024-04-17 14:54:12,354] Trial 44 finished with value: 0.18237779157263123 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 269, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.755115496265169, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.21196016007242774
Fold 2 IBS: 0.21737810285668177
Fold 3 IBS: 0.20221519268515586
Fold 4 IBS: 0.21985834792032022
Fold 5 IBS: 0.21707100228614096
[I 2024-04-17 14:54:16,677] Trial 45 finished with value: 0.21369656116414532 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 226, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5998350649536632, 'min_weight_fraction_leaf': 0.05464331917294846}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18076053104236317
Fold 2 IBS: 0.2172100382529918
Fold 3 IBS: 0.15472808053026357
Fold 4 IBS: 0.14511587127121353
Fold 5 IBS: 0.2339666086051307
[I 2024-04-17 14:54:22,837] Trial 46 finished with value: 0.18635622594039253 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8402810693773478, 'min_weight_fraction_leaf': 0.144161655351996}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18818806948138703
Fold 2 IBS: 0.18585276291120573
Fold 3 IBS: 0.16931029735325712
Fold 4 IBS: 0.16495818665843412
Fold 5 IBS: 0.21221551295471194
[I 2024-04-17 14:54:29,524] Trial 47 finished with value: 0.1841049658717992 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9302813606785956, 'min_weight_fraction_leaf': 0.08930568525499841}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18928681061078317
Fold 2 IBS: 0.19449353516562573
Fold 3 IBS: 0.15782262613968703
Fold 4 IBS: 0.13927270133528777
Fold 5 IBS: 0.22728509464662824
[I 2024-04-17 14:54:43,792] Trial 48 finished with value: 0.1816321535796024 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 374, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7058374194287877, 'min_weight_fraction_leaf': 0.021185992511726287}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20695865791961138
Fold 2 IBS: 0.18446003189676
Fold 3 IBS: 0.1637203264374506
Fold 4 IBS: 0.14167171912108306
Fold 5 IBS: 0.21852048251093703
[I 2024-04-17 14:54:59,889] Trial 49 finished with value: 0.18306624357716844 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6944137175640025, 'min_weight_fraction_leaf': 0.023748345961229673}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20395296501568036
Fold 2 IBS: 0.20356332435883023
Fold 3 IBS: 0.19198232817565247
Fold 4 IBS: 0.20503408115744123
Fold 5 IBS: 0.212977623601451
[I 2024-04-17 14:55:10,108] Trial 50 finished with value: 0.20350206446181107 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.1282263128781066}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1892478776386835
Fold 2 IBS: 0.1985691975751118
Fold 3 IBS: 0.1551366953595447
Fold 4 IBS: 0.13797047291334816
Fold 5 IBS: 0.2247976743236853
[I 2024-04-17 14:55:23,306] Trial 51 finished with value: 0.18114438356207468 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7991896596470566, 'min_weight_fraction_leaf': 0.020902281449632076}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18966875407315306
Fold 2 IBS: 0.20026668125593905
Fold 3 IBS: 0.1581902551783595
Fold 4 IBS: 0.1446898271378981
Fold 5 IBS: 0.22398935878186912
[I 2024-04-17 14:55:34,961] Trial 52 finished with value: 0.18336097528544376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7963262944115481, 'min_weight_fraction_leaf': 0.06178807863600248}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1808545696000534
Fold 2 IBS: 0.2092001659472061
Fold 3 IBS: 0.1569134957561024
Fold 4 IBS: 0.14354275776617909
Fold 5 IBS: 0.23138632547295945
[I 2024-04-17 14:55:44,665] Trial 53 finished with value: 0.1843794629085001 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6795691608327338, 'min_weight_fraction_leaf': 0.028449876548026755}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18963311160047724
Fold 2 IBS: 0.20900009168815242
Fold 3 IBS: 0.15966211681395587
Fold 4 IBS: 0.14477830095268193
Fold 5 IBS: 0.2227272285777302
[I 2024-04-17 14:55:57,723] Trial 54 finished with value: 0.18516016992659953 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8793032020733721, 'min_weight_fraction_leaf': 0.07859078488282405}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1844153405050917
Fold 2 IBS: 0.20329447035960194
Fold 3 IBS: 0.156445527494686
Fold 4 IBS: 0.1385632327057539
Fold 5 IBS: 0.2286479785748904
[I 2024-04-17 14:56:09,262] Trial 55 finished with value: 0.18227330992800478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615617181298988, 'min_weight_fraction_leaf': 0.0463333928046309}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21398416445233792
Fold 2 IBS: 0.22128642959017203
Fold 3 IBS: 0.20479170826088208
Fold 4 IBS: 0.22465474077969866
Fold 5 IBS: 0.21866500422066165
[I 2024-04-17 14:56:18,144] Trial 56 finished with value: 0.21667640946075045 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7048250986458913, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19154362908633138
Fold 2 IBS: 0.19025716940029977
Fold 3 IBS: 0.164641271809976
Fold 4 IBS: 0.1535983543533534
Fold 5 IBS: 0.21130984092669008
[I 2024-04-17 14:56:25,821] Trial 57 finished with value: 0.18227005311533012 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6509352527427404, 'min_weight_fraction_leaf': 0.01668177754116703}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1834614522490023
Fold 2 IBS: 0.20274762979546487
Fold 3 IBS: 0.1558259112444169
Fold 4 IBS: 0.13699785208498225
Fold 5 IBS: 0.227941946402463
[I 2024-04-17 14:56:38,674] Trial 58 finished with value: 0.18139495835526587 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 361, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8149000200033439, 'min_weight_fraction_leaf': 0.1073613839314761}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18264043127662102
Fold 2 IBS: 0.20563295068882514
Fold 3 IBS: 0.15774830297383735
Fold 4 IBS: 0.1409283130574975
Fold 5 IBS: 0.2302026151594693
[I 2024-04-17 14:56:53,051] Trial 59 finished with value: 0.18343052263125006 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 433, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.806842099370764, 'min_weight_fraction_leaf': 0.11194912742691053}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.1940353275621495
Fold 2 IBS: 0.19268012360689624
Fold 3 IBS: 0.18110607070067974
Fold 4 IBS: 0.18845548212963192
Fold 5 IBS: 0.2126254989546211
[I 2024-04-17 14:57:00,062] Trial 60 finished with value: 0.1937805005907957 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 305, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8575527275336559, 'min_weight_fraction_leaf': 0.18982981109623043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1881809892682945
Fold 2 IBS: 0.19390719781855054
Fold 3 IBS: 0.1588739037458674
Fold 4 IBS: 0.1367801254919651
Fold 5 IBS: 0.2266847482237021
[I 2024-04-17 14:57:13,286] Trial 61 finished with value: 0.18088539290967592 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615189086372551, 'min_weight_fraction_leaf': 0.04095649181576018}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1876754810451395
Fold 2 IBS: 0.19768374549602719
Fold 3 IBS: 0.15918815613876297
Fold 4 IBS: 0.13767028389195304
Fold 5 IBS: 0.22732368447379522
[I 2024-04-17 14:57:26,101] Trial 62 finished with value: 0.18190827020913558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 354, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7661278291112643, 'min_weight_fraction_leaf': 0.08934183246037483}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18158763535398614
Fold 2 IBS: 0.2058728330109782
Fold 3 IBS: 0.15634716717840097
Fold 4 IBS: 0.1393411349809578
Fold 5 IBS: 0.2305445348222664
[I 2024-04-17 14:57:40,398] Trial 63 finished with value: 0.18273866106931788 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8238233376692735, 'min_weight_fraction_leaf': 0.05246336243742043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17660125627972975
Fold 2 IBS: 0.19950632480062638
Fold 3 IBS: 0.16593947035609424
Fold 4 IBS: 0.1676045776632834
Fold 5 IBS: 0.2238259008995345
[I 2024-04-17 14:57:50,784] Trial 64 finished with value: 0.18669550599985366 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8942985122180038, 'min_weight_fraction_leaf': 0.3739424140604035}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17841559751185995
Fold 2 IBS: 0.2181576301923148
Fold 3 IBS: 0.15699607135742621
Fold 4 IBS: 0.14279995324086395
Fold 5 IBS: 0.23321351389303
[I 2024-04-17 14:58:00,951] Trial 65 finished with value: 0.185916553239099 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 321, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.157443472337933}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396919511710527
Fold 2 IBS: 0.22118312582133598
Fold 3 IBS: 0.20498660484161652
Fold 4 IBS: 0.22465182954726737
Fold 5 IBS: 0.218115813183982
[I 2024-04-17 14:58:09,260] Trial 66 finished with value: 0.21658131370226147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18873872659716473
Fold 2 IBS: 0.18791922078055107
Fold 3 IBS: 0.16453860462735764
Fold 4 IBS: 0.15207602931399142
Fold 5 IBS: 0.20920273391154215
[I 2024-04-17 14:58:18,298] Trial 67 finished with value: 0.18049506304612142 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7471014922297948, 'min_weight_fraction_leaf': 0.03879604091198421}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.18615572700917984
Fold 2 IBS: 0.1920922899342238
Fold 3 IBS: 0.1645126632956227
Fold 4 IBS: 0.15374635033745812
Fold 5 IBS: 0.21328354527729806
[I 2024-04-17 14:58:27,274] Trial 68 finished with value: 0.1819581151707565 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7411630198194591, 'min_weight_fraction_leaf': 0.0741944771835793}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.19221322343005157
Fold 2 IBS: 0.18747725704463866
Fold 3 IBS: 0.16271946974327306
Fold 4 IBS: 0.14893868190888562
Fold 5 IBS: 0.21053329237786875
[I 2024-04-17 14:58:36,226] Trial 69 finished with value: 0.18037638490094354 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873531668221723, 'min_weight_fraction_leaf': 0.03743740450038523}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19123449448406776
Fold 2 IBS: 0.18634187192427262
Fold 3 IBS: 0.16568962439316362
Fold 4 IBS: 0.14733219858236207
Fold 5 IBS: 0.2124042387639548
[I 2024-04-17 14:58:44,815] Trial 70 finished with value: 0.18060048562956416 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7884602797651743, 'min_weight_fraction_leaf': 0.03984902133772039}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19415415468436753
Fold 2 IBS: 0.1861415676999523
Fold 3 IBS: 0.16573890197473515
Fold 4 IBS: 0.14488999289270504
Fold 5 IBS: 0.2125204407894076
[I 2024-04-17 14:58:53,558] Trial 71 finished with value: 0.18068901160823353 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7819431269555398, 'min_weight_fraction_leaf': 0.03595825517448436}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.18984009710041735
Fold 2 IBS: 0.18778536549020883
Fold 3 IBS: 0.16555752286430367
Fold 4 IBS: 0.15132302702120518
Fold 5 IBS: 0.21187635057748866
[I 2024-04-17 14:59:02,955] Trial 72 finished with value: 0.18127647261072471 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 379, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7158237789595601, 'min_weight_fraction_leaf': 0.038892933150377174}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19217054361716007
Fold 2 IBS: 0.18605477551854072
Fold 3 IBS: 0.1657195529075007
Fold 4 IBS: 0.1499033271314654
Fold 5 IBS: 0.21296314297306798
[I 2024-04-17 14:59:12,156] Trial 73 finished with value: 0.18136226842954697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7776848187295278, 'min_weight_fraction_leaf': 0.041701970157165584}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.1919591413798442
Fold 2 IBS: 0.18680709380802085
Fold 3 IBS: 0.16611125142067912
Fold 4 IBS: 0.14880604710483025
Fold 5 IBS: 0.20779386416865475
[I 2024-04-17 14:59:20,912] Trial 74 finished with value: 0.18029547957640585 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 297, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7429251540613239, 'min_weight_fraction_leaf': 0.034122782806489685}. Best is trial 74 with value: 0.18029547957640585.

Fold 1 IBS: 0.20438643925191893
Fold 2 IBS: 0.1844312624795873
Fold 3 IBS: 0.17002168747641047
Fold 4 IBS: 0.14791525733420058
Fold 5 IBS: 0.21362624602582111
[I 2024-04-17 14:59:30,058] Trial 75 finished with value: 0.18407617851358768 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651148142523113, 'min_weight_fraction_leaf': 0.0005666053087619444}. Best is trial 74 with value: 0.18029547957640585.
Fold 1 IBS: 0.19306514020322818
Fold 2 IBS: 0.1842925536567217
Fold 3 IBS: 0.16281493341095712
Fold 4 IBS: 0.15026196851923793
Fold 5 IBS: 0.20907571723485416
[I 2024-04-17 14:59:37,716] Trial 76 finished with value: 0.1799020626049998 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6121072626884605, 'min_weight_fraction_leaf': 0.0375652827686181}. Best is trial 76 with value: 0.1799020626049998.
Fold 1 IBS: 0.19533191990808643
Fold 2 IBS: 0.18454077801628752
Fold 3 IBS: 0.16320484107502187
Fold 4 IBS: 0.14544314028091127
Fold 5 IBS: 0.2072692252418508
[I 2024-04-17 14:59:45,216] Trial 77 finished with value: 0.17915798090443158 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6024939881120506, 'min_weight_fraction_leaf': 0.03546615930788915}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18979383260600338
Fold 2 IBS: 0.18481018797624196
Fold 3 IBS: 0.16409936588525315
Fold 4 IBS: 0.1553259082203432
Fold 5 IBS: 0.21243305321372438
[I 2024-04-17 14:59:53,041] Trial 78 finished with value: 0.18129246958031323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.06309017855153265}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.1918516718483265
Fold 2 IBS: 0.18449081490872005
Fold 3 IBS: 0.1634428327969914
Fold 4 IBS: 0.14997364872576785
Fold 5 IBS: 0.20763662708758918
[I 2024-04-17 15:00:01,479] Trial 79 finished with value: 0.17947911907347897 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5944767216434486, 'min_weight_fraction_leaf': 0.03643432579651321}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19348005656430173
Fold 2 IBS: 0.18296399211241365
Fold 3 IBS: 0.16491035077279387
Fold 4 IBS: 0.1455645707584685
Fold 5 IBS: 0.21079082139142424
[I 2024-04-17 15:00:10,673] Trial 80 finished with value: 0.1795419583198804 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5738838339262928, 'min_weight_fraction_leaf': 0.01238447949116667}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19385166663658865
Fold 2 IBS: 0.1878440819583883
Fold 3 IBS: 0.165800948446184
Fold 4 IBS: 0.1476511958697635
Fold 5 IBS: 0.21025560153134265
[I 2024-04-17 15:00:19,165] Trial 81 finished with value: 0.1810806988884534 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5619354088357825, 'min_weight_fraction_leaf': 0.01565582556320865}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18524833693093437
Fold 2 IBS: 0.19165170252652822
Fold 3 IBS: 0.16392769525776144
Fold 4 IBS: 0.15846496418540476
Fold 5 IBS: 0.2094683241817906
[I 2024-04-17 15:00:25,884] Trial 82 finished with value: 0.1817522046164839 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 232, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4638072011147492, 'min_weight_fraction_leaf': 0.05201742843067371}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19237185503026552
Fold 2 IBS: 0.18676559841777626
Fold 3 IBS: 0.16407017518328942
Fold 4 IBS: 0.1449765914249507
Fold 5 IBS: 0.20892364253609055
[I 2024-04-17 15:00:35,499] Trial 83 finished with value: 0.1794215725184745 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5992998998564371, 'min_weight_fraction_leaf': 0.011892575602326625}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19394142912089907
Fold 2 IBS: 0.18287172537269059
Fold 3 IBS: 0.16363670208229797
Fold 4 IBS: 0.14366900591399753
Fold 5 IBS: 0.20892071259321834
[I 2024-04-17 15:00:43,110] Trial 84 finished with value: 0.1786079150166207 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 255, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5921978094028723, 'min_weight_fraction_leaf': 0.010779734440848038}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1934701576048722
Fold 2 IBS: 0.18356601291714442
Fold 3 IBS: 0.16350384856124178
Fold 4 IBS: 0.14362897455716736
Fold 5 IBS: 0.20935617313715904
[I 2024-04-17 15:00:50,303] Trial 85 finished with value: 0.17870503335551696 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 250, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.595683013252236, 'min_weight_fraction_leaf': 0.005599104949055786}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.191846570784011
Fold 2 IBS: 0.18680840183499514
Fold 3 IBS: 0.1640377893844091
Fold 4 IBS: 0.14812980552665286
Fold 5 IBS: 0.21175031324864774
[I 2024-04-17 15:00:58,902] Trial 86 finished with value: 0.18051457615574318 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 254, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5360572837412131, 'min_weight_fraction_leaf': 0.01185351158382457}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-17 15:01:06,664] Trial 87 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5878837691778286, 'min_weight_fraction_leaf': 0.008079079463688634}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1914457217244506
Fold 2 IBS: 0.18052086391051203
Fold 3 IBS: 0.16215789222067095
Fold 4 IBS: 0.15081933866613106
Fold 5 IBS: 0.20784710369879605
[I 2024-04-17 15:01:14,147] Trial 88 finished with value: 0.1785581840441121 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-17 15:01:22,042] Trial 89 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.585692212182858, 'min_weight_fraction_leaf': 0.0008838182441561699}. Best is trial 88 with value: 0.1785581840441121.

Fold 1 IBS: 0.19250257566167933
Fold 2 IBS: 0.18261531719008467
Fold 3 IBS: 0.16180974496548703
Fold 4 IBS: 0.14890218044290915
Fold 5 IBS: 0.2130135609453814
[I 2024-04-17 15:01:27,735] Trial 90 finished with value: 0.1797686758411083 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 202, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5935532822743834, 'min_weight_fraction_leaf': 0.007362099342399538}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19466401388017032
Fold 2 IBS: 0.18486336673650017
Fold 3 IBS: 0.16588446237479346
Fold 4 IBS: 0.1465134541216928
Fold 5 IBS: 0.21287370502296324
[I 2024-04-17 15:01:35,102] Trial 91 finished with value: 0.18095980042722398 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 197, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5826023797451899, 'min_weight_fraction_leaf': 0.00862038165347273}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19077050579200147
Fold 2 IBS: 0.18831329801859226
Fold 3 IBS: 0.16406961249991853
Fold 4 IBS: 0.14929003357858256
Fold 5 IBS: 0.21018706108863028
[I 2024-04-17 15:01:44,007] Trial 92 finished with value: 0.18052610219554502 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 252, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5070555008286651, 'min_weight_fraction_leaf': 0.009333694056201223}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.1942451581816268
Fold 2 IBS: 0.1830703742457603
Fold 3 IBS: 0.16097178413138724
Fold 4 IBS: 0.14654845241459755
Fold 5 IBS: 0.2121967833645088
[I 2024-04-17 15:01:52,260] Trial 93 finished with value: 0.17940651046757616 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 221, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5934768503177845, 'min_weight_fraction_leaf': 0.014878777313562812}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19736082973729024
Fold 2 IBS: 0.18309515782891686
Fold 3 IBS: 0.16366471911833752
Fold 4 IBS: 0.14526303100181923
Fold 5 IBS: 0.21417837651704477
[I 2024-04-17 15:01:56,963] Trial 94 finished with value: 0.18071242284068173 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 165, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6349033637819771, 'min_weight_fraction_leaf': 0.019343000331144743}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18578897328440416
Fold 2 IBS: 0.19239898124845878
Fold 3 IBS: 0.1616809082216946
Fold 4 IBS: 0.15362867068252217
Fold 5 IBS: 0.21229660365479858
[I 2024-04-17 15:02:05,707] Trial 95 finished with value: 0.18115882741837566 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 217, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5448232910672774, 'min_weight_fraction_leaf': 0.025610081517443647}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18377286728444794
Fold 2 IBS: 0.18906137730159184
Fold 3 IBS: 0.162592162450128
Fold 4 IBS: 0.15646349234384718
Fold 5 IBS: 0.21273640937582883
[I 2024-04-17 15:02:12,342] Trial 96 finished with value: 0.18092526175116874 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 200, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5166375602788441, 'min_weight_fraction_leaf': 0.01004295110119176}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19320716981789404
Fold 2 IBS: 0.1833817504678623
Fold 3 IBS: 0.16276222353530903
Fold 4 IBS: 0.15005917812838457
Fold 5 IBS: 0.21149567165602431
[I 2024-04-17 15:02:20,007] Trial 97 finished with value: 0.18018119872109484 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 230, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5810941412605699, 'min_weight_fraction_leaf': 0.028715470907523112}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19665218645247226
Fold 2 IBS: 0.18461786549962422
Fold 3 IBS: 0.16585865869273442
Fold 4 IBS: 0.14468826763530046
Fold 5 IBS: 0.20808627775303898
[I 2024-04-17 15:02:28,631] Trial 98 finished with value: 0.17998065120663406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.558904433592998, 'min_weight_fraction_leaf': 0.0007593749444425981}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19225977892006962
Fold 2 IBS: 0.19011577254533654
Fold 3 IBS: 0.1738613054687569
Fold 4 IBS: 0.1638041351036002
Fold 5 IBS: 0.2130479662700931
[I 2024-04-17 15:02:33,622] Trial 99 finished with value: 0.18661779166157128 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4718103481231686, 'min_weight_fraction_leaf': 0.013594026171513878}. Best is trial 88 with value: 0.1785581840441121.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.1785581840441121], datetime_start=datetime.datetime(2024, 4, 17, 15, 1, 6, 670257), datetime_complete=datetime.datetime(2024, 4, 17, 15, 1, 14, 146425), params={'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.1785581840441121

In [62]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.886
train_ibs:  0.179

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=9, max_features=None, max_leaf_nodes=14,
                   max_samples=0.965941994806725, min_samples_split=7,
                   min_weight_fraction_leaf=0.017267854864073284,
                   n_estimators=336, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.662

ExtraSurvivalTrees(max_depth=9, max_features=0.1, max_leaf_nodes=20,
                   max_samples=0.5945245081220258, min_samples_leaf=4,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.006841645987133443,
                   n_estimators=279, oob_score=True, random_state=123,
                   warm_start=True)

IBS: 0.2

In [66]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 15:02:40,753] A new study created in memory with name: no-name-d71c9e2d-d4c3-4255-92c1-434ea5662e51

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:03:37,957] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:04:01,559] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:04:31,198] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:05:43,985] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:06:08,220] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:06:15,059] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:06:50,210] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:07:00,126] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:07:01,635] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7230046948356808
[I 2024-04-17 15:08:54,409] Trial 9 finished with value: 0.7375077219334873 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 15:12:03,387] Trial 10 finished with value: 0.6769991466942861 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:15:05,409] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.715962441314554
[I 2024-04-17 15:17:45,295] Trial 12 finished with value: 0.7180894810070741 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:19:03,394] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:20:47,362] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:22:46,261] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:23:42,336] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:25:41,256] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:28:36,157] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:28:47,440] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:30:05,709] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6384976525821596
[I 2024-04-17 15:32:48,289] Trial 21 finished with value: 0.6596743990023763 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7447257383966245
Fold 5 C-index: 0.6830985915492958
[I 2024-04-17 15:35:24,118] Trial 22 finished with value: 0.7577518089481858 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:37:30,430] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:39:57,110] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:41:12,495] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 15:43:02,130] Trial 26 finished with value: 0.5295120936590003 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:45:05,950] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:46:42,293] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:47:51,690] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:49:38,911] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 15:52:34,942] Trial 31 finished with value: 0.6975838362663174 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:55:21,268] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9113568740147856, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.1444594228310892, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 1.6183832787391992, 'min_weight_fraction_leaf': 0.4304319218036696, 'max_features': 'auto', 'min_impurity_decrease': 1.0277484189219154e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:57:38,099] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9728428556912192, 'learning_rate': 0.015742740923125064, 'dropout_rate': 0.30020186346124766, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.4958404435609285, 'max_features': 'auto', 'min_impurity_decrease': 2.2786499479002052e-07, 'validation_fraction': 0.8344453462672722, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:59:15,243] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.8496036715186095, 'learning_rate': 0.009253864701923034, 'dropout_rate': 0.22658656718653286, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.641857272630336, 'min_weight_fraction_leaf': 0.43629024868714544, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9168532630851701, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 15:59:43,587] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6806458891075314, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.4078621112435248, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3706867126320781, 'max_features': None, 'min_impurity_decrease': 7.8587698841458e-07, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:02:16,251] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.9551502281749775, 'learning_rate': 0.026078126474550274, 'dropout_rate': 0.34789169882120996, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.40891402270131877, 'min_weight_fraction_leaf': 0.2325827619040188, 'max_features': 'auto', 'min_impurity_decrease': 7.145093229830912e-06, 'validation_fraction': 0.6747809687204889, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:02:28,229] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7371581418455209, 'learning_rate': 0.0145417341576766, 'dropout_rate': 0.16172130996739253, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.3174537146690439, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.9548743578197549, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:03:17,070] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.8063221166350547, 'learning_rate': 0.006424315075939495, 'dropout_rate': 0.7673236646699829, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 9.162989248724866, 'min_weight_fraction_leaf': 0.14601082900734919, 'max_features': 'auto', 'min_impurity_decrease': 1.1529415174162498e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:05:12,361] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.8852748015168422, 'learning_rate': 0.02975783779377629, 'dropout_rate': 0.2673592786040255, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1216454788806307, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 8.588272604740831e-07, 'validation_fraction': 0.7628102853958754, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:06:45,571] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5809866593286652, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.20816102573612866, 'n_estimators': 353, 'criterion': 'squared_error', 'ccp_alpha': 3.7898554763179284, 'min_weight_fraction_leaf': 0.4711996214427754, 'max_features': 'auto', 'min_impurity_decrease': 2.3584088371991464e-07, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5821596244131455
[I 2024-04-17 16:06:46,167] Trial 41 finished with value: 0.6152707311185872 and parameters: {'subsample': 0.9964498482283193, 'learning_rate': 0.004158109708816752, 'dropout_rate': 0.13644226542045526, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4011310798872364, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.9993318631652353, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:09:57,920] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.10858843727097561, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.415120560514267, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:11:03,566] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.919916216831853, 'learning_rate': 0.0016321845585985228, 'dropout_rate': 0.16429624388711278, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.471921644995546, 'min_weight_fraction_leaf': 0.3704175909956657, 'max_features': 'auto', 'min_impurity_decrease': 0.0009050261380449993, 'validation_fraction': 0.8779568222622545, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:12:51,216] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.015327765728784649, 'dropout_rate': 0.6859431566383477, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.2679892492803537, 'min_weight_fraction_leaf': 0.2706416993480579, 'max_features': 'auto', 'min_impurity_decrease': 8.738793222106795e-07, 'validation_fraction': 0.9744834265061879, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.6126760563380281
[I 2024-04-17 16:14:47,579] Trial 45 finished with value: 0.7169525524273146 and parameters: {'subsample': 0.8612793275132423, 'learning_rate': 0.008591203396202965, 'dropout_rate': 0.20237082649972205, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.09266970930573763, 'min_weight_fraction_leaf': 0.4478112124993417, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.798828420958444, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:15:01,045] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8576868620948644, 'learning_rate': 0.021769927230194788, 'dropout_rate': 0.9694253886674298, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.45430295635160706, 'max_features': 0.1, 'min_impurity_decrease': 2.0131584568637675e-06, 'validation_fraction': 0.7976029227783121, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:15:32,401] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7056873961179977, 'learning_rate': 0.00929853233926034, 'dropout_rate': 0.3140351257259953, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.49464896810642006, 'max_features': 0.1, 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.6179698437276481, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:17:18,111] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7837245323509484, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.21043558082214228, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.4617743734350054, 'min_weight_fraction_leaf': 0.45246089314517907, 'max_features': 0.1, 'min_impurity_decrease': 4.221379974644956e-07, 'validation_fraction': 0.863214331971344, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:18:09,207] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.6507081753968225, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.26780621294484797, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 1.378218906104398, 'min_weight_fraction_leaf': 0.2916489694540698, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6845184717076465, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:19:46,455] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.03353370774351387, 'dropout_rate': 0.3787195779305788, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.7561621193902213, 'min_weight_fraction_leaf': 0.47814765735031256, 'max_features': 0.1, 'min_impurity_decrease': 1.6961878462023105e-07, 'validation_fraction': 0.8310153288008191, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6244131455399061
[I 2024-04-17 16:22:26,924] Trial 51 finished with value: 0.6982448681347772 and parameters: {'subsample': 0.9590755303360702, 'learning_rate': 0.001263628446733103, 'dropout_rate': 0.13293847894616523, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6338028169014085
[I 2024-04-17 16:24:57,849] Trial 52 finished with value: 0.7007875648598147 and parameters: {'subsample': 0.9309483691931049, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.1309992574789837, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.036615235505588, 'min_weight_fraction_leaf': 0.4052806656624778, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8184597843569143e-07, 'validation_fraction': 0.8992446934973449, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:26:42,242] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9119792149240027, 'learning_rate': 0.0011619738930768678, 'dropout_rate': 0.12019527221159815, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.33436888398209985, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0912509934146174e-06, 'validation_fraction': 0.7204767494493249, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:27:17,155] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9422391559777883, 'learning_rate': 0.006469543850280348, 'dropout_rate': 0.8266353856620614, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.46449392886564433, 'min_weight_fraction_leaf': 0.20818644825744925, 'max_features': 'sqrt', 'min_impurity_decrease': 3.17346833824979e-07, 'validation_fraction': 0.8741639290304148, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:28:55,457] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8715328822130523, 'learning_rate': 0.011790338191706525, 'dropout_rate': 0.23926982708415356, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.4008945876330496, 'min_weight_fraction_leaf': 0.44051010658711054, 'max_features': 'sqrt', 'min_impurity_decrease': 5.615119149330365e-07, 'validation_fraction': 0.7887577239921508, 'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:31:00,393] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8015434219726096, 'learning_rate': 0.04061736247319854, 'dropout_rate': 0.1937709311352404, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.037591557618962, 'min_weight_fraction_leaf': 0.41307911755286036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.854323715915516e-06, 'validation_fraction': 0.907633472782051, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6619718309859155
[I 2024-04-17 16:31:46,473] Trial 57 finished with value: 0.694941105261048 and parameters: {'subsample': 0.47167111494444647, 'learning_rate': 0.018997287630538016, 'dropout_rate': 0.5891903890315894, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.007297661499282945, 'min_weight_fraction_leaf': 0.37949114392069716, 'max_features': 'sqrt', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.5599065409082953, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:33:53,028] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8972461919118405, 'learning_rate': 0.09671804411942064, 'dropout_rate': 0.10627978332234836, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.7590888481670788, 'min_weight_fraction_leaf': 0.25730821949204663, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9487716255435797, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:35:34,590] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.8358264770513102, 'learning_rate': 0.022823901724539096, 'dropout_rate': 0.28631447973846014, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.429314535364776, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': None, 'min_impurity_decrease': 5.131055724938468e-07, 'validation_fraction': 0.8437837761372522, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:36:33,525] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.0056069075336912105, 'dropout_rate': 0.3357871821335161, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 2.523299286625464, 'min_weight_fraction_leaf': 0.339521597129798, 'max_features': 'sqrt', 'min_impurity_decrease': 2.9638541699067996e-07, 'validation_fraction': 0.6410967521884806, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:38:25,561] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.1843386992247676, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.22729228144381666, 'min_weight_fraction_leaf': 0.4037400789999268, 'max_features': 1, 'min_impurity_decrease': 1.310082490250357e-07, 'validation_fraction': 0.9622895789424137, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 16:40:11,860] Trial 62 finished with value: 0.7272773109470696 and parameters: {'subsample': 0.9756177414915416, 'learning_rate': 0.00487963758524286, 'dropout_rate': 0.14510716910347804, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.023608499803350655, 'min_weight_fraction_leaf': 0.22961838496572504, 'max_features': 0.1, 'min_impurity_decrease': 1.6297128321880156e-07, 'validation_fraction': 0.8969787245486088, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:41:54,320] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.9288654416933328, 'learning_rate': 0.013829624766460978, 'dropout_rate': 0.13653478929605453, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.7247405887368557, 'min_weight_fraction_leaf': 0.22479730957902153, 'max_features': 0.1, 'min_impurity_decrease': 5.575423017349267e-07, 'validation_fraction': 0.8936351824952593, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:43:32,808] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.3944303299889498, 'learning_rate': 0.005756823204408979, 'dropout_rate': 0.2327252655551748, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.30460031424817835, 'min_weight_fraction_leaf': 0.1885535376775951, 'max_features': 0.1, 'min_impurity_decrease': 3.354219995894836e-07, 'validation_fraction': 0.9295137020256315, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 16:45:23,068] Trial 65 finished with value: 0.7220969706866847 and parameters: {'subsample': 0.8628229894737177, 'learning_rate': 0.008827661920605995, 'dropout_rate': 0.19214391420812213, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.002774143765696062, 'min_weight_fraction_leaf': 0.19849959041931706, 'max_features': 0.1, 'min_impurity_decrease': 2.5741032571081618e-06, 'validation_fraction': 0.81580153800389, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:47:19,142] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.7758851752296808, 'learning_rate': 0.009751888770788269, 'dropout_rate': 0.19122550095328222, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.898614500640199, 'min_weight_fraction_leaf': 0.15180913487925937, 'max_features': 0.1, 'min_impurity_decrease': 2.693782393576339e-06, 'validation_fraction': 0.8022828972461258, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:48:56,803] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8737277188190908, 'learning_rate': 0.017575803118928604, 'dropout_rate': 0.24650681062055632, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.184288941522344, 'min_weight_fraction_leaf': 0.20306006951316619, 'max_features': 0.1, 'min_impurity_decrease': 1.2046523007672827e-06, 'validation_fraction': 0.7485906145710193, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:50:11,134] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.819932305524277, 'learning_rate': 0.09136620662883123, 'dropout_rate': 0.21544296697082643, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5667792373547914, 'min_weight_fraction_leaf': 0.24594914856187006, 'max_features': 0.1, 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.8633504402260139, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:51:16,943] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5360295416604122, 'learning_rate': 0.026072943824179864, 'dropout_rate': 0.15995252701068877, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 6.315803860540386, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 0.1, 'min_impurity_decrease': 4.676506095993518e-06, 'validation_fraction': 0.8221337964376644, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:52:21,212] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.7391884515801697, 'learning_rate': 0.0131539926632262, 'dropout_rate': 0.4370458221877003, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.3030856819564138, 'min_weight_fraction_leaf': 0.04227011624339991, 'max_features': 'log2', 'min_impurity_decrease': 4.094308088527539e-05, 'validation_fraction': 0.7311035029930464, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6854460093896714
[I 2024-04-17 16:54:07,669] Trial 71 finished with value: 0.7057455222887223 and parameters: {'subsample': 0.8958059912610585, 'learning_rate': 0.00404243977738313, 'dropout_rate': 0.13685925262610546, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.27174017051065336, 'max_features': 0.1, 'min_impurity_decrease': 1.6903767334797878e-07, 'validation_fraction': 0.893021390165449, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 16:55:59,739] Trial 72 finished with value: 0.7255383448051743 and parameters: {'subsample': 0.9033994568982797, 'learning_rate': 0.008576558002904872, 'dropout_rate': 0.1796601786158867, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.0049265702435675185, 'min_weight_fraction_leaf': 0.2698684133835347, 'max_features': 0.1, 'min_impurity_decrease': 2.520131654025212e-07, 'validation_fraction': 0.9039347234285049, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:57:44,335] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9030072931863139, 'learning_rate': 0.00868732713600762, 'dropout_rate': 0.2744775845272275, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8157217970730618, 'min_weight_fraction_leaf': 0.2706425923382264, 'max_features': 0.1, 'min_impurity_decrease': 1.5060083036338323e-07, 'validation_fraction': 0.8429645916964783, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:57:54,865] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8551098377950185, 'learning_rate': 0.017852326043636436, 'dropout_rate': 0.18670893655691517, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.3282745678695592, 'min_weight_fraction_leaf': 0.2216310042184134, 'max_features': 0.1, 'min_impurity_decrease': 0.00020700246413734948, 'validation_fraction': 0.7700706578571286, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 16:59:10,865] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.8885953564344566, 'learning_rate': 0.003923453373901735, 'dropout_rate': 0.25497810906198315, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 4.774324490228468, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 1.0309115243736615e-07, 'validation_fraction': 0.9298417275031959, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:00:55,266] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9671878335188347, 'learning_rate': 0.010137963140872869, 'dropout_rate': 0.1720967582787876, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.6017992226500892, 'min_weight_fraction_leaf': 0.2343670795832099, 'max_features': 0.1, 'min_impurity_decrease': 4.1389285578024635e-07, 'validation_fraction': 0.4666209889121972, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:02:32,631] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7817997136792754, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.21878505744240392, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 2.226175878213271, 'min_weight_fraction_leaf': 0.11673456101680679, 'max_features': 0.1, 'min_impurity_decrease': 2.278338706941225e-07, 'validation_fraction': 0.8870735397490029, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:03:39,272] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.85971117635256, 'learning_rate': 0.020702169760542934, 'dropout_rate': 0.10184607865359452, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 1.1613144933398152, 'min_weight_fraction_leaf': 0.28827493961902323, 'max_features': 0.1, 'min_impurity_decrease': 1.0554012317973208e-06, 'validation_fraction': 0.7800831726807022, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:04:42,269] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7085303006120247, 'learning_rate': 0.007203573027836778, 'dropout_rate': 0.3309372439616984, 'n_estimators': 405, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7098465234455584, 'min_weight_fraction_leaf': 0.16909333970802584, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9874471393466349, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:06:10,131] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.43152853207212877, 'learning_rate': 0.012535821130981227, 'dropout_rate': 0.28829477813771426, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.29587735180979763, 'min_weight_fraction_leaf': 0.1932252614573767, 'max_features': None, 'min_impurity_decrease': 2.607076310858583e-06, 'validation_fraction': 0.2486636150723724, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 17:07:54,267] Trial 81 finished with value: 0.7232266055095437 and parameters: {'subsample': 0.9310152909641193, 'learning_rate': 0.004901464536992707, 'dropout_rate': 0.14649845200705908, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.0401224705257143, 'min_weight_fraction_leaf': 0.2140884860716641, 'max_features': 0.1, 'min_impurity_decrease': 3.294643059864092e-07, 'validation_fraction': 0.9215349695607397, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:09:45,452] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9804673759889536, 'learning_rate': 0.003705242334357205, 'dropout_rate': 0.15221754469070822, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.6905373562188476, 'min_weight_fraction_leaf': 0.214345215244296, 'max_features': 0.1, 'min_impurity_decrease': 1.535249456479472e-07, 'validation_fraction': 0.9202835513583518, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:11:19,507] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9176538987097111, 'learning_rate': 0.0076523566881114835, 'dropout_rate': 0.22968230522988387, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.20240849843431086, 'min_weight_fraction_leaf': 0.2383259127009152, 'max_features': 0.1, 'min_impurity_decrease': 4.399657878596901e-07, 'validation_fraction': 0.9767059181287342, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:12:39,821] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8255635604133957, 'learning_rate': 0.0036977258275946636, 'dropout_rate': 0.20402072590631012, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5198465206932167, 'min_weight_fraction_leaf': 0.15653086076945935, 'max_features': 0.1, 'min_impurity_decrease': 7.178610075896741e-07, 'validation_fraction': 0.8482804900297096, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7745098039215687

Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.676056338028169
[I 2024-04-17 17:14:57,155] Trial 85 finished with value: 0.7189891256993891 and parameters: {'subsample': 0.8918331608196582, 'learning_rate': 0.015605784733698558, 'dropout_rate': 0.14750634204389826, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.30357930249568654, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9997678373401905, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:16:59,279] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10092948452566086, 'learning_rate': 0.01532810679048379, 'dropout_rate': 0.17099114695337342, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.876197483648788, 'min_weight_fraction_leaf': 0.3015328988188304, 'max_features': 'auto', 'min_impurity_decrease': 1.6482137590771691e-06, 'validation_fraction': 0.9342270075718234, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:17:39,679] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5929593460046293, 'learning_rate': 0.016822571784752067, 'dropout_rate': 0.19867600397015794, 'n_estimators': 263, 'criterion': 'squared_error', 'ccp_alpha': 0.23496207633721847, 'min_weight_fraction_leaf': 0.24832976306734728, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.9659857207632909, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:19:45,063] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9310702721088772, 'learning_rate': 0.009959700506785971, 'dropout_rate': 0.2555430411709441, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 8.088457238075051, 'min_weight_fraction_leaf': 0.22631747365745694, 'max_features': 'auto', 'min_impurity_decrease': 2.710852350800199e-07, 'validation_fraction': 0.7056533437856146, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:21:43,624] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.975612460964084, 'learning_rate': 0.012850444381300855, 'dropout_rate': 0.11846749927359909, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 1.425464889112629, 'min_weight_fraction_leaf': 0.1784633449883898, 'max_features': 'auto', 'min_impurity_decrease': 5.921522228604161e-07, 'validation_fraction': 0.9996319172531741, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:23:43,155] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.34045768877643007, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.15210696274519644, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9372956395735829, 'min_weight_fraction_leaf': 0.13514216761654674, 'max_features': 1, 'min_impurity_decrease': 3.412090206574042e-07, 'validation_fraction': 0.5798720476990769, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7183098591549296
[I 2024-04-17 17:25:58,792] Trial 91 finished with value: 0.7299130919568267 and parameters: {'subsample': 0.8979069506313946, 'learning_rate': 0.008101193305888026, 'dropout_rate': 0.14427259297048306, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.05667376231617895, 'min_weight_fraction_leaf': 0.2662831727524566, 'max_features': 'auto', 'min_impurity_decrease': 2.2001283077718922e-07, 'validation_fraction': 0.8878992829265958, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:28:03,533] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8025284770642525, 'learning_rate': 0.008198746448650564, 'dropout_rate': 0.17658024519117366, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4944517626406935, 'min_weight_fraction_leaf': 0.281932786781083, 'max_features': 'auto', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.8240961218884286, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:30:14,985] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.866078324832748, 'learning_rate': 0.011107826666625974, 'dropout_rate': 0.15001558634639325, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.20618034747646607, 'min_weight_fraction_leaf': 0.26022589277342434, 'max_features': 'auto', 'min_impurity_decrease': 1.2653383309827397e-07, 'validation_fraction': 0.8676712222376753, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:31:59,893] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.8418316701841008, 'learning_rate': 0.006152062924759251, 'dropout_rate': 0.2291019421217302, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.6324588657889718, 'min_weight_fraction_leaf': 0.4804568203093911, 'max_features': 'auto', 'min_impurity_decrease': 9.38303925215205e-07, 'validation_fraction': 0.9086059943821162, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:34:15,313] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.87747934958027, 'learning_rate': 0.0012139304758565887, 'dropout_rate': 0.12498646666495616, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.3715046104772777, 'min_weight_fraction_leaf': 0.208961689017974, 'max_features': 'auto', 'min_impurity_decrease': 2.382313770891545e-07, 'validation_fraction': 0.3818872933371859, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6446078431372549
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7089201877934272
[I 2024-04-17 17:35:58,299] Trial 96 finished with value: 0.696510102322911 and parameters: {'subsample': 0.94218553177403, 'learning_rate': 0.020033817173644677, 'dropout_rate': 0.3058190228136884, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.030434277972844224, 'min_weight_fraction_leaf': 0.19188954018236168, 'max_features': 'auto', 'min_impurity_decrease': 3.679493950049724e-07, 'validation_fraction': 0.9459755275340084, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:36:18,371] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.9071107405480169, 'learning_rate': 0.013884656270412483, 'dropout_rate': 0.8479620532477699, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 1.069614033248094, 'min_weight_fraction_leaf': 0.32699666489884094, 'max_features': 'log2', 'min_impurity_decrease': 5.25058355616678e-07, 'validation_fraction': 0.8836386308311208, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-17 17:37:31,178] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.9531544060001753, 'learning_rate': 0.008555926298082998, 'dropout_rate': 0.20235805532585233, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 0.7543795415309705, 'min_weight_fraction_leaf': 0.30398885673134707, 'max_features': 'auto', 'min_impurity_decrease': 1.0466185221530527e-07, 'validation_fraction': 0.9694358139640935, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.5654008438818565

[I 2024-04-17 17:39:00,858] A new study created in memory with name: no-name-5d6f520e-73ac-4c4e-9beb-1c2e693a1a13

Fold 5 C-index: 0.6103286384976526
[I 2024-04-17 17:39:00,824] Trial 99 finished with value: 0.6663823683373736 and parameters: {'subsample': 0.9976459171012907, 'learning_rate': 0.024328086787534252, 'dropout_rate': 0.36361374787631456, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.004395791161995251, 'min_weight_fraction_leaf': 0.353628504086837, 'max_features': 'auto', 'min_impurity_decrease': 1.5812750205075571e-07, 'validation_fraction': 0.8128875839784486, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.


* Best trial for C-index:
 FrozenTrial(number=22, state=TrialState.COMPLETE, values=[0.7577518089481858], datetime_start=datetime.datetime(2024, 4, 17, 15, 32, 48, 299960), datetime_complete=datetime.datetime(2024, 4, 17, 15, 35, 24, 117897), params={'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=22, value=None)


* Best Score for C-index:
 0.7577518089481858

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:39:33,666] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:39:47,659] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:40:06,015] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:40:52,722] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:41:08,089] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:41:12,694] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:41:36,489] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:41:43,143] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:41:44,037] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21278960135067226
Fold 2 IBS: 0.22075148425471117
Fold 3 IBS: 0.20356154640252785
Fold 4 IBS: 0.22366437810992945
Fold 5 IBS: 0.2175108694850557
[I 2024-04-17 17:42:54,316] Trial 9 finished with value: 0.2156555759205793 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21360363678959007
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.20421474792063551
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21803455300047256
[I 2024-04-17 17:44:44,057] Trial 10 finished with value: 0.21637936117854983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 17:46:32,062] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2138334609344149
Fold 2 IBS: 0.22151322501680365
Fold 3 IBS: 0.20446062477316612
Fold 4 IBS: 0.2246559027106978
Fold 5 IBS: 0.2180563962052136
[I 2024-04-17 17:48:02,814] Trial 12 finished with value: 0.2165039219280592 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 17:48:41,341] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:50:03,224] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:51:00,778] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:51:30,369] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:52:41,757] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:53:21,296] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:53:29,786] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 17:54:40,614] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21367586546116044
Fold 2 IBS: 0.22153601357644734
Fold 3 IBS: 0.20438542163118117
Fold 4 IBS: 0.22463472155111044
Fold 5 IBS: 0.2180079529732588
[I 2024-04-17 17:55:51,293] Trial 21 finished with value: 0.21644799503863163 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21300133805358812
Fold 2 IBS: 0.22092783506924327

Fold 3 IBS: 0.20392740109457028
Fold 4 IBS: 0.22400556985244785
Fold 5 IBS: 0.2175786554209321
[I 2024-04-17 17:57:16,892] Trial 22 finished with value: 0.2158881598981563 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:58:31,807] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 17:59:19,985] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 18:00:03,479] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 18:00:41,859] Trial 26 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:00:46,706] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:00:58,591] Trial 28 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:01:42,218] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:02:45,578] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2132673053926921
Fold 2 IBS: 0.22138150435074114
Fold 3 IBS: 0.20416936232206076
Fold 4 IBS: 0.224409146213765
Fold 5 IBS: 0.2177869543616682
[I 2024-04-17 18:03:54,560] Trial 31 finished with value: 0.2162028545281854 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21250908818560812
Fold 2 IBS: 0.22112061913596615
Fold 3 IBS: 0.20357254804690844
Fold 4 IBS: 0.22431509484129145
Fold 5 IBS: 0.21754679795245008
[I 2024-04-17 18:13:57,130] Trial 32 finished with value: 0.2158128296324448 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 18:14:18,353] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 18:40:05,864] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 18:40:14,438] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 19:40:45,696] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 19:40:48,785] Trial 37 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 20:05:32,194] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 20:52:26,611] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 21:39:31,571] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21343873621972445
Fold 2 IBS: 0.22049446029877326
Fold 3 IBS: 0.20337828484272225
Fold 4 IBS: 0.22303639527565466
Fold 5 IBS: 0.21729676723732877
[I 2024-04-17 22:16:52,761] Trial 41 finished with value: 0.21552892877484067 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.2131030184453258
Fold 2 IBS: 0.22050327285628324
Fold 3 IBS: 0.2033673824751969
Fold 4 IBS: 0.22363217726195525
Fold 5 IBS: 0.21724767258898225
[I 2024-04-17 22:17:30,242] Trial 42 finished with value: 0.2155707047255487 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:18:12,262] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:18:48,761] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:19:00,701] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21368294038898764
Fold 2 IBS: 0.22138561655450684
Fold 3 IBS: 0.2042880559361189
Fold 4 IBS: 0.22453830345531042
Fold 5 IBS: 0.21794750132893198
[I 2024-04-17 22:19:29,569] Trial 46 finished with value: 0.21636848353277113 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:19:45,294] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:19:45,466] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:19:52,338] Trial 49 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 22:20:11,682] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21305615407340403
Fold 2 IBS: 0.22124588111973337
Fold 3 IBS: 0.20390302508767316
Fold 4 IBS: 0.22446365006496424
Fold 5 IBS: 0.21777819332443837
[I 2024-04-17 22:20:43,135] Trial 51 finished with value: 0.21608938073404263 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21352169783850614
Fold 2 IBS: 0.22120550026908148
Fold 3 IBS: 0.20396949286236565
Fold 4 IBS: 0.22452441731877534
Fold 5 IBS: 0.2178146994022686
[I 2024-04-17 22:21:14,963] Trial 52 finished with value: 0.21620716153819944 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:21:44,028] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:22:13,227] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:22:36,819] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:22:55,446] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:23:15,486] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:23:39,606] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:23:57,059] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:24:12,114] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:24:44,484] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9319260511303565, 'learning_rate': 0.006981217524957076, 'dropout_rate': 0.2694290399109642, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.2266262530125842, 'min_weight_fraction_leaf': 0.2262208916321135, 'max_features': 'auto', 'min_impurity_decrease': 6.393438969585487e-06, 'validation_fraction': 0.968342815685117, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21261827944826023
Fold 2 IBS: 0.2212835131478303
Fold 3 IBS: 0.20384635335083123
Fold 4 IBS: 0.22428599240586905
Fold 5 IBS: 0.21722666261844198
[I 2024-04-17 22:25:15,229] Trial 62 finished with value: 0.21585216019424655 and parameters: {'subsample': 0.9972198040262032, 'learning_rate': 0.008659221224759001, 'dropout_rate': 0.18470289302046516, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.022476866600004634, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 3.745982455886227e-06, 'validation_fraction': 0.9275220875852723, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:25:25,592] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9899309662352432, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:25:51,593] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9658825052862857, 'learning_rate': 0.010845363858236992, 'dropout_rate': 0.13571080979315037, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.3681339382709387, 'min_weight_fraction_leaf': 0.15534331606940482, 'max_features': 'log2', 'min_impurity_decrease': 8.60046486145071e-06, 'validation_fraction': 0.9205869937759958, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21299720012323184
Fold 2 IBS: 0.22115174939969934
Fold 3 IBS: 0.2038040121811597
Fold 4 IBS: 0.2242157275656328
Fold 5 IBS: 0.21734625390047366
[I 2024-04-17 22:26:24,723] Trial 65 finished with value: 0.21590298863403948 and parameters: {'subsample': 0.9661607708539444, 'learning_rate': 0.008868026173365113, 'dropout_rate': 0.17835638219464384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.002725826040487267, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:26:50,642] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9998769833869746, 'learning_rate': 0.003967598379054899, 'dropout_rate': 0.17654958266634313, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.8981368148483696, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'auto', 'min_impurity_decrease': 7.140027633149786e-05, 'validation_fraction': 0.6362228335648394, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:27:11,744] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8945386029541793, 'learning_rate': 0.01494075298406419, 'dropout_rate': 0.209071801122636, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1837261226658302, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5552258602982892e-05, 'validation_fraction': 0.7259068897097584, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-17 22:27:47,221] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.843502945752621, 'learning_rate': 0.02075147594960792, 'dropout_rate': 0.16252263519114862, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.057901034918407895, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.6846740503948187, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:28:11,870] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.01037165919107231, 'dropout_rate': 0.19004731427008625, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.34303232955200197, 'min_weight_fraction_leaf': 0.3579731281150166, 'max_features': 'auto', 'min_impurity_decrease': 0.00014344627836102727, 'validation_fraction': 0.7769648880006281, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:28:40,675] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6499145948799803, 'learning_rate': 0.008667614598934925, 'dropout_rate': 0.2379061541841675, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.6762661413605899, 'min_weight_fraction_leaf': 0.2053436289550881, 'max_features': None, 'min_impurity_decrease': 2.7112245092072337e-05, 'validation_fraction': 0.5272974695233066, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21365379061917414
Fold 2 IBS: 0.22138264547298084
Fold 3 IBS: 0.2043021502572646
Fold 4 IBS: 0.22456249898531583
Fold 5 IBS: 0.2178752609515109
[I 2024-04-17 22:29:13,004] Trial 71 finished with value: 0.21635526925724924 and parameters: {'subsample': 0.9554665295189709, 'learning_rate': 0.004772306432110387, 'dropout_rate': 0.30773217080297294, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.019537053946387287, 'max_features': 'auto', 'min_impurity_decrease': 3.603782675882374e-06, 'validation_fraction': 0.8818766703918308, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21009179135163386
Fold 2 IBS: 0.21999119714274143
Fold 3 IBS: 0.2019997974702572
Fold 4 IBS: 0.22308677215739936
Fold 5 IBS: 0.2164934631302429
[I 2024-04-17 22:29:48,323] Trial 72 finished with value: 0.21433260425045497 and parameters: {'subsample': 0.9233416329717381, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.12211037740366137, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004815836437462028, 'min_weight_fraction_leaf': 0.2452551786385524, 'max_features': 'auto', 'min_impurity_decrease': 1.5300590715832769e-06, 'validation_fraction': 0.974284387349558, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:29:55,424] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.916509573532907, 'learning_rate': 0.01366625897147706, 'dropout_rate': 0.10211108319082117, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.35137810274202946, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'auto', 'min_impurity_decrease': 5.253021283264037e-07, 'validation_fraction': 0.9862680394354211, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:30:26,028] Trial 74 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.98093897605085, 'learning_rate': 0.01711555655405715, 'dropout_rate': 0.13243922080536136, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.7083433911466146, 'min_weight_fraction_leaf': 0.24361782259873882, 'max_features': 'auto', 'min_impurity_decrease': 1.0928587879200682e-06, 'validation_fraction': 0.8125486143795312, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.20063679042123642
Fold 2 IBS: 0.2148812250636474
Fold 3 IBS: 0.19380589049848737
Fold 4 IBS: 0.21616853881208678
Fold 5 IBS: 0.21227770638433743
[I 2024-04-17 22:30:52,843] Trial 75 finished with value: 0.20755403023595909 and parameters: {'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:31:19,187] Trial 76 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8704877196117842, 'learning_rate': 0.0916936247639216, 'dropout_rate': 0.13042337037884444, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2722270315020332, 'max_features': 'auto', 'min_impurity_decrease': 1.6370541352867706e-06, 'validation_fraction': 0.9218092808039015, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:31:38,551] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7865219593038091, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.25073094184082545, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.2846220433570537, 'min_weight_fraction_leaf': 0.32348748582358233, 'max_features': 1, 'min_impurity_decrease': 2.1196884133822008e-06, 'validation_fraction': 0.854746843935587, 'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:31:53,130] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.74450491092411, 'learning_rate': 0.08426314282635561, 'dropout_rate': 0.21845035750510394, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 0.3013998603131079, 'min_weight_fraction_leaf': 0.28488038648314357, 'max_features': 'auto', 'min_impurity_decrease': 4.969807589794284e-06, 'validation_fraction': 0.5953526855291732, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:32:16,392] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.07449175092046981, 'dropout_rate': 0.10061598571006734, 'n_estimators': 422, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8368147401670278, 'min_weight_fraction_leaf': 0.3103740193108716, 'max_features': 0.1, 'min_impurity_decrease': 1.5059537626102993e-07, 'validation_fraction': 0.8973370541013407, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-17 22:32:42,435] Trial 80 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8235918523200412, 'learning_rate': 0.04033855340571721, 'dropout_rate': 0.16425961502490374, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 1.694844319118747, 'min_weight_fraction_leaf': 0.2647465108562044, 'max_features': 'log2', 'min_impurity_decrease': 2.9198051926565164e-07, 'validation_fraction': 0.9949359598698552, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21270616661412084
Fold 2 IBS: 0.22114894326985232
Fold 3 IBS: 0.2033654110159561
Fold 4 IBS: 0.2242783032190139
Fold 5 IBS: 0.21754308206787823
[I 2024-04-17 22:33:21,403] Trial 81 finished with value: 0.21580838123736426 and parameters: {'subsample': 0.9683433550626522, 'learning_rate': 0.008693963960519305, 'dropout_rate': 0.1932014858120802, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2888444623370858, 'max_features': 'auto', 'min_impurity_decrease': 1.789620202740983e-05, 'validation_fraction': 0.938473425448535, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:33:54,159] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9762052388738753, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.19741538666007516, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.534138531195614, 'min_weight_fraction_leaf': 0.24700237584705395, 'max_features': 'auto', 'min_impurity_decrease': 7.152609841250385e-06, 'validation_fraction': 0.9388911144407316, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:34:30,539] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8945279252278314, 'learning_rate': 0.012088994568921815, 'dropout_rate': 0.154422708294762, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.1988546603429769, 'min_weight_fraction_leaf': 0.2902454191677818, 'max_features': 'auto', 'min_impurity_decrease': 3.133577694489401e-05, 'validation_fraction': 0.8395709442103857, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:34:58,432] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9340088491306221, 'learning_rate': 0.020145328722091006, 'dropout_rate': 0.23069098430626017, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5566102523015541, 'min_weight_fraction_leaf': 0.3043408977845187, 'max_features': 'auto', 'min_impurity_decrease': 5.245144153489441e-06, 'validation_fraction': 0.961947672530741, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:35:31,695] Trial 85 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.003151086314395833, 'dropout_rate': 0.12604720621824386, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 1.0429257766218587, 'min_weight_fraction_leaf': 0.13299714491615983, 'max_features': 'auto', 'min_impurity_decrease': 9.411442401014158e-06, 'validation_fraction': 0.9351152476505527, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:35:58,091] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.998032487033103, 'learning_rate': 0.015189890476328648, 'dropout_rate': 0.1929808152262999, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.25850792206277284, 'min_weight_fraction_leaf': 0.19547135211860373, 'max_features': 'sqrt', 'min_impurity_decrease': 7.182497909387456e-07, 'validation_fraction': 0.9008555229787725, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:36:16,861] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.586845457594135, 'learning_rate': 0.007791310814930576, 'dropout_rate': 0.2576203464314456, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 0.5970165508324569, 'min_weight_fraction_leaf': 0.3246889883811851, 'max_features': 'auto', 'min_impurity_decrease': 1.2915207513275362e-06, 'validation_fraction': 0.7941466165973634, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:36:38,399] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9047974654661481, 'learning_rate': 0.053489441535809173, 'dropout_rate': 0.15111205819257206, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 0.8515398041309932, 'min_weight_fraction_leaf': 0.21790404115359022, 'max_features': 'auto', 'min_impurity_decrease': 2.7145979471070252e-06, 'validation_fraction': 0.8752408074269059, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:37:12,054] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8838515048108662, 'learning_rate': 0.01150450588881658, 'dropout_rate': 0.3106345257277401, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.181177839559219, 'max_features': 'auto', 'min_impurity_decrease': 1.2718861827092477e-05, 'validation_fraction': 0.9760648785366552, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-17 22:37:55,812] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.960313946457138, 'learning_rate': 0.02326628275454888, 'dropout_rate': 0.2094619744215954, 'n_estimators': 470, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.16213094006522927, 'max_features': None, 'min_impurity_decrease': 8.384298759153104e-07, 'validation_fraction': 0.8362867621481024, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21278867450434957
Fold 2 IBS: 0.22123796611209143
Fold 3 IBS: 0.20385360063526636
Fold 4 IBS: 0.22428500781668678
Fold 5 IBS: 0.2173590980603734
[I 2024-04-17 22:38:30,410] Trial 91 finished with value: 0.21590486942575354 and parameters: {'subsample': 0.974845880068985, 'learning_rate': 0.008764883268716819, 'dropout_rate': 0.18635760945321272, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.2754894562810546, 'max_features': 'auto', 'min_impurity_decrease': 4.2012810231263196e-05, 'validation_fraction': 0.6282967667391103, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:39:04,265] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9396947823626011, 'learning_rate': 0.004368164180849998, 'dropout_rate': 0.1759357421598699, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.25915463409396067, 'min_weight_fraction_leaf': 0.25965914250337996, 'max_features': 'auto', 'min_impurity_decrease': 8.321039301525785e-05, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20443254583780004
Fold 2 IBS: 0.21704992653232766
Fold 3 IBS: 0.20021814328282203
Fold 4 IBS: 0.21936269502578284
Fold 5 IBS: 0.2126381390950113
[I 2024-04-17 22:39:36,700] Trial 93 finished with value: 0.2107402899547488 and parameters: {'subsample': 0.9636218550527925, 'learning_rate': 0.08324257203844727, 'dropout_rate': 0.22319965814002635, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.04690043062719928, 'min_weight_fraction_leaf': 0.23684277621975902, 'max_features': 'auto', 'min_impurity_decrease': 1.548140174949508e-05, 'validation_fraction': 0.7388312145266367, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-17 22:40:09,121] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9216100363199584, 'learning_rate': 0.08937987875028564, 'dropout_rate': 0.2226719596812821, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.5370821041135924, 'min_weight_fraction_leaf': 0.23931318130410523, 'max_features': 'auto', 'min_impurity_decrease': 1.9804047777777935e-05, 'validation_fraction': 0.9344757106941509, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-17 22:40:44,912] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9505720618597318, 'learning_rate': 0.08804335553847131, 'dropout_rate': 0.2858426054482697, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.3311905561863823, 'min_weight_fraction_leaf': 0.1453679981012504, 'max_features': 'auto', 'min_impurity_decrease': 9.665752514196455e-06, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:41:14,259] Trial 96 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9806046119279813, 'learning_rate': 0.08726220388438458, 'dropout_rate': 0.2508258253233333, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.0842424782139257, 'min_weight_fraction_leaf': 0.2509877726726459, 'max_features': 'auto', 'min_impurity_decrease': 4.132954919887874e-06, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-17 22:41:36,387] Trial 97 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9139721535827401, 'learning_rate': 0.0956243686002578, 'dropout_rate': 0.11551248506043046, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.20602145594384874, 'min_weight_fraction_leaf': 0.21288677009944212, 'max_features': 1, 'min_impurity_decrease': 5.099166934714435e-07, 'validation_fraction': 0.6982085459927765, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-17 22:42:08,850] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.881458897433829, 'learning_rate': 0.0818716069302554, 'dropout_rate': 0.1602397729595261, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.7476516282703678, 'min_weight_fraction_leaf': 0.29398452840523387, 'max_features': 'auto', 'min_impurity_decrease': 2.2015056170379928e-06, 'validation_fraction': 0.9116047571236726, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20960061935285024
Fold 2 IBS: 0.21745644638172798

Fold 3 IBS: 0.20030580413616672
Fold 4 IBS: 0.21827950204883104
Fold 5 IBS: 0.2160767264619057
[I 2024-04-17 22:42:33,320] Trial 99 finished with value: 0.21234381967629634 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.07921297533010697, 'dropout_rate': 0.36361374787631456, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.004455045338579978, 'min_weight_fraction_leaf': 0.23447872920034368, 'max_features': 0.1, 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.4378698142708704, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.20755403023595909], datetime_start=datetime.datetime(2024, 4, 17, 22, 30, 26, 32885), datetime_complete=datetime.datetime(2024, 4, 17, 22, 30, 52, 843117), params={'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.20755403023595909

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.208

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0339977959383996,
                                 criterion='squared_error',
                                 dropout_rate=0.2075412325353082,
                                 learning_rate=0.010706280861824496,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=3.3602815261835675e-07,
                                 min_samples_leaf=13, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4472167339801619,
                                 n_estimators=445, random_state=123,
                                 subsample=0.9030031356045858,
                                 validation_fraction=0.9350158433232643)

C-index score: 0.618

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008810810992982535,
                                 criterion='squared_error',
                                 dropout_rate=0.1693875032679634,
                                 learning_rate=0.08843409287484169,
                                 max_features='auto', max_leaf_nodes=15,
                                 min_impurity_decrease=5.157320437854681e-06,
                                 min_samples_leaf=16, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29044798941528627,
                                 n_estimators=403, random_state=123,
                                 subsample=0.8646743646205938,
                                 validation_fraction=0.7489142536117352)

IBS: 0.213

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-17 22:42:45,720] A new study created in memory with name: no-name-350242cd-9097-4150-8ca0-4198759199d3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:42:48,493] Trial 0 finished with value: 0.6944636137409307 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6944636137409307.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:43:01,874] Trial 1 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6944636137409307.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:43:06,061] Trial 2 finished with value: 0.6961513774540109 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6961513774540109.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:43:10,992] Trial 3 finished with value: 0.7007896875828404 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7007896875828404.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:43:17,660] Trial 4 finished with value: 0.7089630000608811 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7089630000608811.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:43:26,504] Trial 5 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7089630000608811.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:43:30,848] Trial 6 finished with value: 0.6934832215840679 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7089630000608811.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:43:32,120] Trial 7 finished with value: 0.6979735179619425 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7089630000608811.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 22:43:37,246] Trial 8 finished with value: 0.6963829730339437 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7089630000608811.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:43:48,905] Trial 9 finished with value: 0.6954440058977934 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7089630000608811.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 22:43:56,508] Trial 10 finished with value: 0.7078385473380912 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 4 with value: 0.7089630000608811.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 22:44:04,882] Trial 11 finished with value: 0.7242391503514646 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:44:12,632] Trial 12 finished with value: 0.7108952262163881 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.2495649826842376, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 22:44:22,148] Trial 13 finished with value: 0.6963001229925186 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:44:31,190] Trial 14 finished with value: 0.7160294116512065 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24475605651992097, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:44:40,302] Trial 15 finished with value: 0.6981439030173732 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.6890184489677957, 'n_estimators': 365, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 22:44:51,590] Trial 16 finished with value: 0.7231529077781292 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.10221023026090809, 'n_estimators': 423, 'learning_rate': 0.08463638125592773}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7934272300469484
[I 2024-04-17 22:45:03,538] Trial 17 finished with value: 0.7188724264402271 and parameters: {'subsample': 0.2738903405395941, 'dropout_rate': 0.1019684592707394, 'n_estimators': 445, 'learning_rate': 0.0834370349684546}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:45:14,276] Trial 18 finished with value: 0.7009146944325307 and parameters: {'subsample': 0.34810348568738264, 'dropout_rate': 0.7033122086799477, 'n_estimators': 430, 'learning_rate': 0.08274653862258437}. Best is trial 11 with value: 0.7242391503514646.

Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 22:45:24,540] Trial 19 finished with value: 0.7066289725991046 and parameters: {'subsample': 0.19816662555708264, 'dropout_rate': 0.34721836740782674, 'n_estimators': 400, 'learning_rate': 0.08909215792368923}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:45:32,109] Trial 20 finished with value: 0.7017096010027538 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.1874011856184571, 'n_estimators': 301, 'learning_rate': 0.06551866052750378}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:45:44,422] Trial 21 finished with value: 0.713343531143312 and parameters: {'subsample': 0.23883126807324034, 'dropout_rate': 0.12395834975058428, 'n_estimators': 446, 'learning_rate': 0.08054438682658777}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 22:45:56,033] Trial 22 finished with value: 0.7098452688422328 and parameters: {'subsample': 0.32332502309762223, 'dropout_rate': 0.10707277604295147, 'n_estimators': 419, 'learning_rate': 0.08906623037882347}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:46:10,008] Trial 23 finished with value: 0.7075628024674593 and parameters: {'subsample': 0.17983149131070258, 'dropout_rate': 0.2169651477117805, 'n_estimators': 457, 'learning_rate': 0.07817104103315589}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 22:46:21,164] Trial 24 finished with value: 0.7152972557927042 and parameters: {'subsample': 0.10082506787612186, 'dropout_rate': 0.3140787854660392, 'n_estimators': 397, 'learning_rate': 0.09116015767131479}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:46:35,823] Trial 25 finished with value: 0.7116015138530818 and parameters: {'subsample': 0.27961521867530886, 'dropout_rate': 0.1453672170265101, 'n_estimators': 496, 'learning_rate': 0.07863489086649084}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:46:45,782] Trial 26 finished with value: 0.7009146944325307 and parameters: {'subsample': 0.4154241705504771, 'dropout_rate': 0.2968233742660247, 'n_estimators': 324, 'learning_rate': 0.060589579418639364}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:46:53,558] Trial 27 finished with value: 0.707699312767782 and parameters: {'subsample': 0.17080406159902112, 'dropout_rate': 0.9861686560685959, 'n_estimators': 258, 'learning_rate': 0.06923715110439763}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 22:47:04,783] Trial 28 finished with value: 0.7008415281621814 and parameters: {'subsample': 0.4146906469347543, 'dropout_rate': 0.18804677832052086, 'n_estimators': 411, 'learning_rate': 0.04284904312427481}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:47:05,634] Trial 29 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.6611065916050776, 'dropout_rate': 0.4175950896276197, 'n_estimators': 28, 'learning_rate': 0.09528773825271981}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 22:47:08,377] Trial 30 finished with value: 0.7069993504541316 and parameters: {'subsample': 0.22987674803141853, 'dropout_rate': 0.3147626016045193, 'n_estimators': 93, 'learning_rate': 0.0842026511952143}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 22:47:17,623] Trial 31 finished with value: 0.7172460843605826 and parameters: {'subsample': 0.125155377187584, 'dropout_rate': 0.17842788952606506, 'n_estimators': 348, 'learning_rate': 0.09354109144068656}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 22:47:26,297] Trial 32 finished with value: 0.7128653804752748 and parameters: {'subsample': 0.17871830086608953, 'dropout_rate': 0.1770907215473853, 'n_estimators': 343, 'learning_rate': 0.09214772080187031}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:47:36,637] Trial 33 finished with value: 0.7097501835626226 and parameters: {'subsample': 0.29860205579569726, 'dropout_rate': 0.10062708073380387, 'n_estimators': 388, 'learning_rate': 0.07188872272574334}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:47:49,639] Trial 34 finished with value: 0.7130023430708123 and parameters: {'subsample': 0.14154027296706004, 'dropout_rate': 0.18176727348379584, 'n_estimators': 454, 'learning_rate': 0.0763541162592114}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:47:56,990] Trial 35 finished with value: 0.7031630448659147 and parameters: {'subsample': 0.223378688176412, 'dropout_rate': 0.5333294823429767, 'n_estimators': 279, 'learning_rate': 0.08481514107177617}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:48:02,864] Trial 36 finished with value: 0.7014970591390579 and parameters: {'subsample': 0.591115859980263, 'dropout_rate': 0.1424338129612857, 'n_estimators': 224, 'learning_rate': 0.09368950169803325}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:48:11,486] Trial 37 finished with value: 0.7013121668706706 and parameters: {'subsample': 0.21655697520498404, 'dropout_rate': 0.6198740536882945, 'n_estimators': 331, 'learning_rate': 0.059207327336158105}. Best is trial 11 with value: 0.7242391503514646.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:48:26,120] Trial 38 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.8179022915704841, 'dropout_rate': 0.46319782172467416, 'n_estimators': 475, 'learning_rate': 0.07288612365177065}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:48:29,914] Trial 39 finished with value: 0.6978708824167279 and parameters: {'subsample': 0.3183823327210974, 'dropout_rate': 0.22897359886270768, 'n_estimators': 145, 'learning_rate': 0.06741260221639067}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:48:42,042] Trial 40 finished with value: 0.7075847214767202 and parameters: {'subsample': 0.15369721382009435, 'dropout_rate': 0.2858906592462564, 'n_estimators': 434, 'learning_rate': 0.0853652247702959}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:48:51,292] Trial 41 finished with value: 0.7170973388220748 and parameters: {'subsample': 0.10476476918607368, 'dropout_rate': 0.22152070664281126, 'n_estimators': 354, 'learning_rate': 0.09825612209750595}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 22:49:01,364] Trial 42 finished with value: 0.7236510550588896 and parameters: {'subsample': 0.10371111181017878, 'dropout_rate': 0.16010049887419808, 'n_estimators': 382, 'learning_rate': 0.09516580496428079}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:49:11,269] Trial 43 finished with value: 0.7188877380803695 and parameters: {'subsample': 0.1407105750300053, 'dropout_rate': 0.16799912452101284, 'n_estimators': 379, 'learning_rate': 0.09188617833857958}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7934272300469484
[I 2024-04-17 22:49:21,379] Trial 44 finished with value: 0.7125670849710734 and parameters: {'subsample': 0.2604587195563551, 'dropout_rate': 0.1497527113284679, 'n_estimators': 379, 'learning_rate': 0.08951219679204844}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:49:33,585] Trial 45 finished with value: 0.7067189206109192 and parameters: {'subsample': 0.17980086021893574, 'dropout_rate': 0.3692704021926727, 'n_estimators': 418, 'learning_rate': 0.02274904980797578}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 22:49:47,420] Trial 46 finished with value: 0.7152925708201238 and parameters: {'subsample': 0.14856562452608105, 'dropout_rate': 0.14222047525893244, 'n_estimators': 465, 'learning_rate': 0.08204482650836435}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:49:58,731] Trial 47 finished with value: 0.7017924510441789 and parameters: {'subsample': 0.24893591396344392, 'dropout_rate': 0.27761161755419983, 'n_estimators': 380, 'learning_rate': 0.008209618821055878}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:50:06,431] Trial 48 finished with value: 0.7212116294758556 and parameters: {'subsample': 0.20180803397026764, 'dropout_rate': 0.10493174400801568, 'n_estimators': 282, 'learning_rate': 0.07636730545478901}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 22:50:14,337] Trial 49 finished with value: 0.7095196335961571 and parameters: {'subsample': 0.1376380492776858, 'dropout_rate': 0.20960059631780176, 'n_estimators': 286, 'learning_rate': 0.07604223197769483}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:50:23,825] Trial 50 finished with value: 0.7057926410081692 and parameters: {'subsample': 0.20356889945940781, 'dropout_rate': 0.7527484444635378, 'n_estimators': 323, 'learning_rate': 0.08820705590793061}. Best is trial 11 with value: 0.7242391503514646.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 22:50:30,136] Trial 51 finished with value: 0.7249023343109265 and parameters: {'subsample': 0.1902469006919563, 'dropout_rate': 0.10034833702437368, 'n_estimators': 242, 'learning_rate': 0.09570993541362999}. Best is trial 51 with value: 0.7249023343109265.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 22:50:35,890] Trial 52 finished with value: 0.7140825054798658 and parameters: {'subsample': 0.20200688203952913, 'dropout_rate': 0.15484825866880525, 'n_estimators': 220, 'learning_rate': 0.09943761246589973}. Best is trial 51 with value: 0.7249023343109265.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 22:50:42,791] Trial 53 finished with value: 0.727241537346555 and parameters: {'subsample': 0.1336560313158617, 'dropout_rate': 0.10193518245198506, 'n_estimators': 255, 'learning_rate': 0.09477772623342627}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 22:50:48,972] Trial 54 finished with value: 0.7072720572288624 and parameters: {'subsample': 0.9377000314940434, 'dropout_rate': 0.10198492860331942, 'n_estimators': 242, 'learning_rate': 0.09591007537328615}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 22:50:53,244] Trial 55 finished with value: 0.7043334665589602 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.13487719598593945, 'n_estimators': 167, 'learning_rate': 0.08746054008246393}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 22:50:58,220] Trial 56 finished with value: 0.7033559396951216 and parameters: {'subsample': 0.34564191047715326, 'dropout_rate': 0.25336216375340165, 'n_estimators': 197, 'learning_rate': 0.09476830126879632}. Best is trial 53 with value: 0.727241537346555.

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-17 22:51:04,307] Trial 57 finished with value: 0.7135148590952289 and parameters: {'subsample': 0.1015245425282236, 'dropout_rate': 0.20270407446105362, 'n_estimators': 241, 'learning_rate': 0.08081623516743677}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:51:11,886] Trial 58 finished with value: 0.7049117396111592 and parameters: {'subsample': 0.29464264101380383, 'dropout_rate': 0.1253410844238017, 'n_estimators': 292, 'learning_rate': 0.04123136082326221}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 22:51:18,342] Trial 59 finished with value: 0.7204651048736971 and parameters: {'subsample': 0.2485118283599727, 'dropout_rate': 0.12555647927901623, 'n_estimators': 251, 'learning_rate': 0.0998582191898498}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-17 22:51:24,863] Trial 60 finished with value: 0.695402580877081 and parameters: {'subsample': 0.4439613138829449, 'dropout_rate': 0.8216282776289219, 'n_estimators': 266, 'learning_rate': 0.05286688874951598}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 22:51:33,062] Trial 61 finished with value: 0.7186551996039505 and parameters: {'subsample': 0.24189609551034247, 'dropout_rate': 0.12445519946512404, 'n_estimators': 313, 'learning_rate': 0.09989944043362611}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:51:40,071] Trial 62 finished with value: 0.7245705161835881 and parameters: {'subsample': 0.18601868798656038, 'dropout_rate': 0.10037393362275317, 'n_estimators': 271, 'learning_rate': 0.0966297911971503}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 22:51:46,977] Trial 63 finished with value: 0.7175094211901523 and parameters: {'subsample': 0.1741553860450218, 'dropout_rate': 0.16476602500283072, 'n_estimators': 275, 'learning_rate': 0.09048769902887006}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 22:51:52,904] Trial 64 finished with value: 0.7239633671747764 and parameters: {'subsample': 0.19457720403489742, 'dropout_rate': 0.10072521628393856, 'n_estimators': 232, 'learning_rate': 0.09527245302317154}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 22:51:58,771] Trial 65 finished with value: 0.7182582177670823 and parameters: {'subsample': 0.13226856009148047, 'dropout_rate': 0.19547583894868198, 'n_estimators': 230, 'learning_rate': 0.09615529244718551}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 22:52:03,393] Trial 66 finished with value: 0.7084851288851819 and parameters: {'subsample': 0.16865819523904038, 'dropout_rate': 0.23749396622654995, 'n_estimators': 182, 'learning_rate': 0.08748042687576059}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:52:08,665] Trial 67 finished with value: 0.7263896529291956 and parameters: {'subsample': 0.1252695985091989, 'dropout_rate': 0.16100125953682667, 'n_estimators': 207, 'learning_rate': 0.09317615447216816}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 22:52:14,323] Trial 68 finished with value: 0.726348227908483 and parameters: {'subsample': 0.12514136737157186, 'dropout_rate': 0.15436109201249193, 'n_estimators': 200, 'learning_rate': 0.09359720162235907}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 22:52:19,359] Trial 69 finished with value: 0.7165019727562332 and parameters: {'subsample': 0.1251050847119988, 'dropout_rate': 0.2628665797622993, 'n_estimators': 199, 'learning_rate': 0.09202016115732693}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-17 22:52:22,799] Trial 70 finished with value: 0.7118237777939098 and parameters: {'subsample': 0.15905809875089325, 'dropout_rate': 0.33189267451016913, 'n_estimators': 142, 'learning_rate': 0.09679876716761551}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 22:52:27,944] Trial 71 finished with value: 0.7199488467731863 and parameters: {'subsample': 0.1076503841642071, 'dropout_rate': 0.15893503541383888, 'n_estimators': 212, 'learning_rate': 0.09405919154788}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:52:34,736] Trial 72 finished with value: 0.7075242427397708 and parameters: {'subsample': 0.18459104564827827, 'dropout_rate': 0.2006040673366351, 'n_estimators': 262, 'learning_rate': 0.09019492510913318}. Best is trial 53 with value: 0.727241537346555.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:52:39,346] Trial 73 finished with value: 0.7281920079333375 and parameters: {'subsample': 0.1258089240401944, 'dropout_rate': 0.1299008937623471, 'n_estimators': 177, 'learning_rate': 0.09675768886605675}. Best is trial 73 with value: 0.7281920079333375.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7934272300469484
[I 2024-04-17 22:52:43,433] Trial 74 finished with value: 0.7187139971306438 and parameters: {'subsample': 0.22268695697700674, 'dropout_rate': 0.12799468090123317, 'n_estimators': 163, 'learning_rate': 0.09712953375265218}. Best is trial 73 with value: 0.7281920079333375.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:52:47,780] Trial 75 finished with value: 0.714141023514221 and parameters: {'subsample': 0.15194780327496976, 'dropout_rate': 0.5154917592158309, 'n_estimators': 183, 'learning_rate': 0.08674536598273279}. Best is trial 73 with value: 0.7281920079333375.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 22:52:51,325] Trial 76 finished with value: 0.72904917064153 and parameters: {'subsample': 0.12850189742120152, 'dropout_rate': 0.10064271403610489, 'n_estimators': 119, 'learning_rate': 0.09170799123141873}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 22:52:53,427] Trial 77 finished with value: 0.7183337970352406 and parameters: {'subsample': 0.1268755290441423, 'dropout_rate': 0.17930459634200863, 'n_estimators': 81, 'learning_rate': 0.09193584626049074}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 22:52:56,371] Trial 78 finished with value: 0.7149966883137313 and parameters: {'subsample': 0.15574532676194625, 'dropout_rate': 0.22330814537547425, 'n_estimators': 122, 'learning_rate': 0.08368224936174853}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:52:58,483] Trial 79 finished with value: 0.7100075063413265 and parameters: {'subsample': 0.12467935958765353, 'dropout_rate': 0.1392498613537317, 'n_estimators': 79, 'learning_rate': 0.07909002604136996}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7887323943661971
[I 2024-04-17 22:53:02,365] Trial 80 finished with value: 0.719621223017157 and parameters: {'subsample': 0.27361169821334147, 'dropout_rate': 0.12295875368348205, 'n_estimators': 151, 'learning_rate': 0.09276761315226226}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:53:07,279] Trial 81 finished with value: 0.7228608334612472 and parameters: {'subsample': 0.18656191560627108, 'dropout_rate': 0.10103359806294485, 'n_estimators': 204, 'learning_rate': 0.08957173376835977}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 22:53:12,889] Trial 82 finished with value: 0.7123988334211138 and parameters: {'subsample': 0.2133597445733849, 'dropout_rate': 0.16998763447097437, 'n_estimators': 232, 'learning_rate': 0.09663902834303742}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 22:53:15,848] Trial 83 finished with value: 0.7067972241490641 and parameters: {'subsample': 0.16291664993895788, 'dropout_rate': 0.6202793429199533, 'n_estimators': 125, 'learning_rate': 0.08586461575234071}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.755868544600939
[I 2024-04-17 22:53:20,268] Trial 84 finished with value: 0.7024360262752081 and parameters: {'subsample': 0.5972580083143042, 'dropout_rate': 0.1473286747697672, 'n_estimators': 187, 'learning_rate': 0.09779934715192204}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:53:26,174] Trial 85 finished with value: 0.7184069633055901 and parameters: {'subsample': 0.1896750687146967, 'dropout_rate': 0.11770642639691106, 'n_estimators': 241, 'learning_rate': 0.09306076789752205}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 22:53:31,377] Trial 86 finished with value: 0.7246804225020694 and parameters: {'subsample': 0.12207431225257359, 'dropout_rate': 0.10103591217022476, 'n_estimators': 212, 'learning_rate': 0.09404837945218628}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7699530516431925
[I 2024-04-17 22:53:36,667] Trial 87 finished with value: 0.7192191039124932 and parameters: {'subsample': 0.1232350824959768, 'dropout_rate': 0.19068151719896453, 'n_estimators': 214, 'learning_rate': 0.046295896439199104}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 22:53:39,206] Trial 88 finished with value: 0.7201361520393827 and parameters: {'subsample': 0.14260057769020787, 'dropout_rate': 0.15055625532348316, 'n_estimators': 105, 'learning_rate': 0.08961704759893699}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:53:43,092] Trial 89 finished with value: 0.7172270306443458 and parameters: {'subsample': 0.10078761794298294, 'dropout_rate': 0.1695635140465683, 'n_estimators': 159, 'learning_rate': 0.09347218948141942}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:53:50,549] Trial 90 finished with value: 0.7075138271811424 and parameters: {'subsample': 0.23316093509584873, 'dropout_rate': 0.21111934212317293, 'n_estimators': 301, 'learning_rate': 0.09825724194096754}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 22:53:56,997] Trial 91 finished with value: 0.7221073519117367 and parameters: {'subsample': 0.16316437034629927, 'dropout_rate': 0.10369075904826937, 'n_estimators': 256, 'learning_rate': 0.0950218168092507}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.784037558685446
[I 2024-04-17 22:54:01,811] Trial 92 finished with value: 0.7211702044551431 and parameters: {'subsample': 0.20018845353367531, 'dropout_rate': 0.13605204225065046, 'n_estimators': 195, 'learning_rate': 0.08784152057952986}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-17 22:54:07,324] Trial 93 finished with value: 0.7121308116189635 and parameters: {'subsample': 0.14074705591232378, 'dropout_rate': 0.41200689746521035, 'n_estimators': 229, 'learning_rate': 0.09147364780111847}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-17 22:54:13,843] Trial 94 finished with value: 0.7014970591390579 and parameters: {'subsample': 0.7630755401354222, 'dropout_rate': 0.1260789509040807, 'n_estimators': 271, 'learning_rate': 0.08226958537482197}. Best is trial 76 with value: 0.72904917064153.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7746478873239436
[I 2024-04-17 22:54:19,762] Trial 95 finished with value: 0.7273780476468776 and parameters: {'subsample': 0.12040906608454006, 'dropout_rate': 0.114592190617148, 'n_estimators': 243, 'learning_rate': 0.09781230693594138}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-17 22:54:26,046] Trial 96 finished with value: 0.7136509171003367 and parameters: {'subsample': 0.11503911508987967, 'dropout_rate': 0.18269122214767758, 'n_estimators': 251, 'learning_rate': 0.09851551527819559}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 22:54:30,102] Trial 97 finished with value: 0.7182582177670823 and parameters: {'subsample': 0.12567047140600945, 'dropout_rate': 0.15657479377275324, 'n_estimators': 171, 'learning_rate': 0.03184901175247192}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7793427230046949
[I 2024-04-17 22:54:35,075] Trial 98 finished with value: 0.7235192297311477 and parameters: {'subsample': 0.17061059211744017, 'dropout_rate': 0.12063783769501396, 'n_estimators': 207, 'learning_rate': 0.08585403649064428}. Best is trial 76 with value: 0.72904917064153.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705

[I 2024-04-17 22:54:36,897] A new study created in memory with name: no-name-7af668de-8f20-4158-bf75-698ec6787185

Fold 5 C-index: 0.7652582159624414
[I 2024-04-17 22:54:36,894] Trial 99 finished with value: 0.7182143797485606 and parameters: {'subsample': 0.1447394701460575, 'dropout_rate': 0.14392537619661439, 'n_estimators': 57, 'learning_rate': 0.09430855083496184}. Best is trial 76 with value: 0.72904917064153.


* Best trial for C-index:
 FrozenTrial(number=76, state=TrialState.COMPLETE, values=[0.72904917064153], datetime_start=datetime.datetime(2024, 4, 17, 22, 52, 47, 785060), datetime_complete=datetime.datetime(2024, 4, 17, 22, 52, 51, 325608), params={'subsample': 0.12850189742120152, 'dropout_rate': 0.10064271403610489, 'n_estimators': 119, 'learning_rate': 0.09170799123141873}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=76, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.12850189742120152, 'dropout_rate': 0.10064271403610489, 'n_estimators': 119, 'learning_rate': 0.09170799123141873}


* Best Score for C-index:
 0.72904917064153

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24543748741914098
Fold 2 IBS: 0.23317848666127475
Fold 3 IBS: 0.18721324013097929
Fold 4 IBS: 0.2627413120655669
Fold 5 IBS: 0.2088844422588817
[I 2024-04-17 22:54:39,649] Trial 0 finished with value: 0.2274909937071687 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.3157615176698962
Fold 2 IBS: 0.32189237562862166
Fold 3 IBS: 0.2788861650869375
Fold 4 IBS: 0.3152651041057157
Fold 5 IBS: 0.3046807334754616
[I 2024-04-17 22:54:52,120] Trial 1 finished with value: 0.3072971791933265 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.2736129440677976
Fold 2 IBS: 0.2992916550922806
Fold 3 IBS: 0.2344928921000292
Fold 4 IBS: 0.2750087278739297
Fold 5 IBS: 0.2592818752777806
[I 2024-04-17 22:54:56,176] Trial 2 finished with value: 0.26833761888236357 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.2771997655106299
Fold 2 IBS: 0.2738997354359799
Fold 3 IBS: 0.23937090990720106
Fold 4 IBS: 0.2632441371572647
Fold 5 IBS: 0.22620425465104954
[I 2024-04-17 22:55:01,010] Trial 3 finished with value: 0.255983760532425 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.277366146333423
Fold 2 IBS: 0.28640483968813457
Fold 3 IBS: 0.24286300840279776
Fold 4 IBS: 0.25637095669208554
Fold 5 IBS: 0.2388362833463886
[I 2024-04-17 22:55:07,419] Trial 4 finished with value: 0.26036824689256594 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.29964122631726436
Fold 2 IBS: 0.3204039646090136
Fold 3 IBS: 0.2615357263447192
Fold 4 IBS: 0.3032899768975731
Fold 5 IBS: 0.2968638928198015
[I 2024-04-17 22:55:15,897] Trial 5 finished with value: 0.29634695739767436 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2274909937071687.
Fold 1 IBS: 0.23142715981972764
Fold 2 IBS: 0.20264709709911605
Fold 3 IBS: 0.17325615036677913
Fold 4 IBS: 0.24090901161401929
Fold 5 IBS: 0.19041091163397286
[I 2024-04-17 22:55:20,180] Trial 6 finished with value: 0.207730066106723 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.207730066106723.
Fold 1 IBS: 0.2076748777046715
Fold 2 IBS: 0.18513286928098505
Fold 3 IBS: 0.17458570926946737
Fold 4 IBS: 0.20959901500077463
Fold 5 IBS: 0.1862362339629645
[I 2024-04-17 22:55:21,469] Trial 7 finished with value: 0.1926457410437726 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.2483266230281813
Fold 2 IBS: 0.24322669159502178
Fold 3 IBS: 0.19314995217139108
Fold 4 IBS: 0.26660384269502313
Fold 5 IBS: 0.2066592338505478
[I 2024-04-17 22:55:26,383] Trial 8 finished with value: 0.231593268668033 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.30275986043779984
Fold 2 IBS: 0.32087941820266896
Fold 3 IBS: 0.2666014584900397
Fold 4 IBS: 0.3048081958481441
Fold 5 IBS: 0.29108906842572163
[I 2024-04-17 22:55:37,775] Trial 9 finished with value: 0.2972276002808748 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.21343330133003716
Fold 2 IBS: 0.22041746827332745
Fold 3 IBS: 0.2036139107282693
Fold 4 IBS: 0.2237771082655921
Fold 5 IBS: 0.21719902637866145
[I 2024-04-17 22:55:38,514] Trial 10 finished with value: 0.2156881629951775 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.21324338103957954
Fold 2 IBS: 0.22001717603804508
Fold 3 IBS: 0.20389467112141196
Fold 4 IBS: 0.2234486245538933
Fold 5 IBS: 0.2168716025171396
[I 2024-04-17 22:55:38,832] Trial 11 finished with value: 0.21549509105401388 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.2629915675140106
Fold 2 IBS: 0.28040766616045343
Fold 3 IBS: 0.21604618761489602
Fold 4 IBS: 0.2692560226887386
Fold 5 IBS: 0.2261140037791945
[I 2024-04-17 22:55:41,362] Trial 12 finished with value: 0.25096308955145863 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.26195181678854607
Fold 2 IBS: 0.2771979490504694
Fold 3 IBS: 0.21031993833068025
Fold 4 IBS: 0.2772718910025073
Fold 5 IBS: 0.24789677015981626
[I 2024-04-17 22:55:48,388] Trial 13 finished with value: 0.25492767306640385 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.2055469233365125
Fold 2 IBS: 0.19333008828178766
Fold 3 IBS: 0.18149798595746378
Fold 4 IBS: 0.20811509030714898
Fold 5 IBS: 0.195183209307254
[I 2024-04-17 22:55:50,613] Trial 14 finished with value: 0.19673465943803337 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.21056124354783895
Fold 2 IBS: 0.21352681391995132
Fold 3 IBS: 0.19869725603155575
Fold 4 IBS: 0.21866975920639684
Fold 5 IBS: 0.21197217386793427
[I 2024-04-17 22:55:52,450] Trial 15 finished with value: 0.21068544931473543 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.20646294925281175
Fold 2 IBS: 0.20279664668541308
Fold 3 IBS: 0.18998554437644108
Fold 4 IBS: 0.21138450932830422
Fold 5 IBS: 0.20288324042130967
[I 2024-04-17 22:55:53,970] Trial 16 finished with value: 0.20270257801285596 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.23688660254063618
Fold 2 IBS: 0.2137758878636472
Fold 3 IBS: 0.17666285067548287
Fold 4 IBS: 0.2497930363895449
Fold 5 IBS: 0.1965709716221325
[I 2024-04-17 22:55:57,832] Trial 17 finished with value: 0.21473786981828874 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.2380300059980365
Fold 2 IBS: 0.2158098095196536
Fold 3 IBS: 0.18048207133130295
Fold 4 IBS: 0.24859599562150908
Fold 5 IBS: 0.1892581484020015
[I 2024-04-17 22:56:07,110] Trial 18 finished with value: 0.21443520617450074 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.1926457410437726.
Fold 1 IBS: 0.20427482822698922
Fold 2 IBS: 0.17862676264130528

Fold 3 IBS: 0.1756675093735378
Fold 4 IBS: 0.1919155264975053
Fold 5 IBS: 0.1849348585772
[I 2024-04-17 22:56:08,452] Trial 19 finished with value: 0.18708389706330752 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.20469079919009717
Fold 2 IBS: 0.18161183535879627
Fold 3 IBS: 0.17748752476067053
Fold 4 IBS: 0.19624326076516657
Fold 5 IBS: 0.18897994630034004
[I 2024-04-17 22:56:09,723] Trial 20 finished with value: 0.18980267327501413 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.2007782118192034
Fold 2 IBS: 0.18907326747918482
Fold 3 IBS: 0.18316466708155035
Fold 4 IBS: 0.20173113876039855
Fold 5 IBS: 0.19356091069665493
[I 2024-04-17 22:56:10,762] Trial 21 finished with value: 0.19366163916739842 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.21284271933368631
Fold 2 IBS: 0.2192486563965627
Fold 3 IBS: 0.20302325984715375
Fold 4 IBS: 0.2222842490602751
Fold 5 IBS: 0.21629342497904955
[I 2024-04-17 22:56:11,091] Trial 22 finished with value: 0.2147384619233455 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.2348419715879879
Fold 2 IBS: 0.20624263476173474
Fold 3 IBS: 0.1853394669894191
Fold 4 IBS: 0.23567866055313483
Fold 5 IBS: 0.18014881049008352
[I 2024-04-17 22:56:14,867] Trial 23 finished with value: 0.20845030887647203 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.22248320058398224
Fold 2 IBS: 0.19085270418692715
Fold 3 IBS: 0.17172708052628663
Fold 4 IBS: 0.22993815392808942
Fold 5 IBS: 0.18072688201070727
[I 2024-04-17 22:56:16,462] Trial 24 finished with value: 0.19914560424719854 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.22163073147317996
Fold 2 IBS: 0.18475804653138572
Fold 3 IBS: 0.17286482380348905
Fold 4 IBS: 0.21686238088626522
Fold 5 IBS: 0.17843967250191495
[I 2024-04-17 22:56:19,437] Trial 25 finished with value: 0.19491113103924698 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.2633947443622279
Fold 2 IBS: 0.245184395136671
Fold 3 IBS: 0.23237355156675002
Fold 4 IBS: 0.22405305851253723
Fold 5 IBS: 0.22698039229086447
[I 2024-04-17 22:56:23,350] Trial 26 finished with value: 0.2383972283738101 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.25339191360213825
Fold 2 IBS: 0.2498493688007318
Fold 3 IBS: 0.2029452062831183
Fold 4 IBS: 0.2630090606503658
Fold 5 IBS: 0.20734807889638746
[I 2024-04-17 22:56:29,285] Trial 27 finished with value: 0.2353087256465483 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.20540859953998852
Fold 2 IBS: 0.19442982296416572
Fold 3 IBS: 0.18594830345561808
Fold 4 IBS: 0.206717064225803
Fold 5 IBS: 0.1996976390620323
[I 2024-04-17 22:56:30,456] Trial 28 finished with value: 0.19844028584952153 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.24931739081681506
Fold 2 IBS: 0.24842622998621017
Fold 3 IBS: 0.1946776213480084
Fold 4 IBS: 0.2705170447873235
Fold 5 IBS: 0.20622206353272252
[I 2024-04-17 22:56:33,322] Trial 29 finished with value: 0.23383207009421594 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.23178079376152108
Fold 2 IBS: 0.19117054345731327
Fold 3 IBS: 0.17718902139182244
Fold 4 IBS: 0.22759567423861712
Fold 5 IBS: 0.18082644481172494
[I 2024-04-17 22:56:35,689] Trial 30 finished with value: 0.20171249553219978 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.20065600149446114
Fold 2 IBS: 0.18291603856307093
Fold 3 IBS: 0.17916491706898358
Fold 4 IBS: 0.2001470133972414
Fold 5 IBS: 0.18850835585229017
[I 2024-04-17 22:56:37,175] Trial 31 finished with value: 0.19027846527520947 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.2025251158810651
Fold 2 IBS: 0.18691261216235297
Fold 3 IBS: 0.18144207949231633
Fold 4 IBS: 0.20233570641861667
Fold 5 IBS: 0.19448786955792033
[I 2024-04-17 22:56:38,193] Trial 32 finished with value: 0.19354067670245428 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.18708389706330752.
Fold 1 IBS: 0.2154552192518687
Fold 2 IBS: 0.17121205139926823
Fold 3 IBS: 0.1736328194289806
Fold 4 IBS: 0.19283361768241072
Fold 5 IBS: 0.17754418530389224
[I 2024-04-17 22:56:39,937] Trial 33 finished with value: 0.1861355786132841 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 33 with value: 0.1861355786132841.
Fold 1 IBS: 0.21111843046231343
Fold 2 IBS: 0.21588330178052892
Fold 3 IBS: 0.19943421783538148
Fold 4 IBS: 0.21864973429916335
Fold 5 IBS: 0.21352235961056626
[I 2024-04-17 22:56:40,311] Trial 34 finished with value: 0.2117216087975907 and parameters: {'subsample': 0.10904251030586302, 'dropout_rate': 0.8662195064551774, 'n_estimators': 3, 'learning_rate': 0.07766566220378217}. Best is trial 33 with value: 0.1861355786132841.
Fold 1 IBS: 0.2608195033187159
Fold 2 IBS: 0.26762077174587684
Fold 3 IBS: 0.21669168431022803
Fold 4 IBS: 0.26490195547888185
Fold 5 IBS: 0.22006731578496502
[I 2024-04-17 22:56:43,734] Trial 35 finished with value: 0.24602024612773352 and parameters: {'subsample': 0.27868485453535496, 'dropout_rate': 0.9999743696114711, 'n_estimators': 141, 'learning_rate': 0.06694317131672249}. Best is trial 33 with value: 0.1861355786132841.
Fold 1 IBS: 0.31875352587949346
Fold 2 IBS: 0.3201739538292168
Fold 3 IBS: 0.2745202578839064
Fold 4 IBS: 0.27387015804355697
Fold 5 IBS: 0.2736289412967777
[I 2024-04-17 22:56:54,738] Trial 36 finished with value: 0.29218936738659024 and parameters: {'subsample': 0.16326559473518704, 'dropout_rate': 0.8736174627174981, 'n_estimators': 421, 'learning_rate': 0.07993410500556083}. Best is trial 33 with value: 0.1861355786132841.
Fold 1 IBS: 0.25917632591228085
Fold 2 IBS: 0.2609248284281908
Fold 3 IBS: 0.2166103831499354
Fold 4 IBS: 0.26518679388858324
Fold 5 IBS: 0.2219955047890129
[I 2024-04-17 22:56:59,971] Trial 37 finished with value: 0.24477876723360065 and parameters: {'subsample': 0.23660873470356106, 'dropout_rate': 0.7990281623991888, 'n_estimators': 170, 'learning_rate': 0.05621431261796065}. Best is trial 33 with value: 0.1861355786132841.
Fold 1 IBS: 0.2211542339512011
Fold 2 IBS: 0.15532299471548047

Fold 3 IBS: 0.1777438933250101
Fold 4 IBS: 0.19404071579693005
Fold 5 IBS: 0.17992947278624782
[I 2024-04-17 22:57:02,140] Trial 38 finished with value: 0.1856382621149739 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 82, 'learning_rate': 0.0684395247111694}. Best is trial 38 with value: 0.1856382621149739.
Fold 1 IBS: 0.2301128250403564
Fold 2 IBS: 0.17234930369004173
Fold 3 IBS: 0.1786611224369967
Fold 4 IBS: 0.2083426816157661
Fold 5 IBS: 0.18005256755486432
[I 2024-04-17 22:57:04,169] Trial 39 finished with value: 0.19390370006760504 and parameters: {'subsample': 0.1669627464432204, 'dropout_rate': 0.11471626893495929, 'n_estimators': 82, 'learning_rate': 0.06892741183938003}. Best is trial 38 with value: 0.1856382621149739.
Fold 1 IBS: 0.26127361158239537
Fold 2 IBS: 0.2702117097774595
Fold 3 IBS: 0.21315070084074397
Fold 4 IBS: 0.2757159479700989
Fold 5 IBS: 0.2205628674854048
[I 2024-04-17 22:57:06,860] Trial 40 finished with value: 0.24818296753122052 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.27073406810212547, 'n_estimators': 112, 'learning_rate': 0.08603457614657108}. Best is trial 38 with value: 0.1856382621149739.
Fold 1 IBS: 0.21333019654237578
Fold 2 IBS: 0.1694220368918866
Fold 3 IBS: 0.16800614379286943
Fold 4 IBS: 0.1878852510438249
Fold 5 IBS: 0.17480743402128074
[I 2024-04-17 22:57:08,507] Trial 41 finished with value: 0.1826902124584475 and parameters: {'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 58, 'learning_rate': 0.06842845994744125}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.21294279749606151
Fold 2 IBS: 0.17019815271277783
Fold 3 IBS: 0.1731288009784489
Fold 4 IBS: 0.20493010799111977
Fold 5 IBS: 0.1770150437385983
[I 2024-04-17 22:57:10,174] Trial 42 finished with value: 0.1876429805834013 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.19807687454956896, 'n_estimators': 64, 'learning_rate': 0.06911254892370094}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.2757373192244659
Fold 2 IBS: 0.2607934097941264
Fold 3 IBS: 0.23800594241829395
Fold 4 IBS: 0.24870956680460624
Fold 5 IBS: 0.23396766810723724
[I 2024-04-17 22:57:15,052] Trial 43 finished with value: 0.251442781269746 and parameters: {'subsample': 0.20979862666572763, 'dropout_rate': 0.21348524642098904, 'n_estimators': 198, 'learning_rate': 0.0726352652201749}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.22693486364345375
Fold 2 IBS: 0.18059139073363592
Fold 3 IBS: 0.1745575599098608
Fold 4 IBS: 0.2193685130893947
Fold 5 IBS: 0.17526554849482853
[I 2024-04-17 22:57:16,670] Trial 44 finished with value: 0.19534357517423476 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.20101401396422397, 'n_estimators': 63, 'learning_rate': 0.06523605428553468}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.24864207644217515
Fold 2 IBS: 0.23457995517531988
Fold 3 IBS: 0.1931238835425645
Fold 4 IBS: 0.2591423949714222
Fold 5 IBS: 0.1974709524611482
[I 2024-04-17 22:57:19,132] Trial 45 finished with value: 0.22659185251852598 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.295844522167053, 'n_estimators': 96, 'learning_rate': 0.07358829455007394}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.2508833077420966
Fold 2 IBS: 0.22220591380459848
Fold 3 IBS: 0.21887706297897477
Fold 4 IBS: 0.24474562372987513
Fold 5 IBS: 0.2100630905146779
[I 2024-04-17 22:57:22,192] Trial 46 finished with value: 0.22935499975404458 and parameters: {'subsample': 0.14485404068604799, 'dropout_rate': 0.3312246704393865, 'n_estimators': 127, 'learning_rate': 0.08365083008051383}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.25823519807403505
Fold 2 IBS: 0.2202577108282652
Fold 3 IBS: 0.21933785975058553
Fold 4 IBS: 0.2320707637095868
Fold 5 IBS: 0.2069064342099497
[I 2024-04-17 22:57:26,346] Trial 47 finished with value: 0.22736159331448444 and parameters: {'subsample': 0.24463732973960714, 'dropout_rate': 0.13911133506878087, 'n_estimators': 175, 'learning_rate': 0.0622210649734474}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.19876170222063283
Fold 2 IBS: 0.18595132758349378
Fold 3 IBS: 0.17981863242122464
Fold 4 IBS: 0.1967078660018511
Fold 5 IBS: 0.19242895715814567
[I 2024-04-17 22:57:26,967] Trial 48 finished with value: 0.1907336970770696 and parameters: {'subsample': 0.10041210259629582, 'dropout_rate': 0.19701471782839963, 'n_estimators': 18, 'learning_rate': 0.09182402211019655}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.22554775032788899
Fold 2 IBS: 0.18464429897327903
Fold 3 IBS: 0.1726364057649019
Fold 4 IBS: 0.22283582309833438
Fold 5 IBS: 0.18207143861226857
[I 2024-04-17 22:57:28,881] Trial 49 finished with value: 0.19754714335533458 and parameters: {'subsample': 0.317047365475798, 'dropout_rate': 0.4402540309495773, 'n_estimators': 75, 'learning_rate': 0.051717833751605366}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.28479062388344156
Fold 2 IBS: 0.2562162827866381
Fold 3 IBS: 0.24731530877319746
Fold 4 IBS: 0.2419538685391266
Fold 5 IBS: 0.24887551099973496
[I 2024-04-17 22:57:34,614] Trial 50 finished with value: 0.2558303189964278 and parameters: {'subsample': 0.1830774219227035, 'dropout_rate': 0.17538138388138197, 'n_estimators': 230, 'learning_rate': 0.07966264522754796}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.21010825090120375
Fold 2 IBS: 0.16897012272317627
Fold 3 IBS: 0.1708845169913034
Fold 4 IBS: 0.19303516390872374
Fold 5 IBS: 0.18225491280502945
[I 2024-04-17 22:57:35,920] Trial 51 finished with value: 0.18505059346588731 and parameters: {'subsample': 0.1422401972634589, 'dropout_rate': 0.10079252980319817, 'n_estimators': 49, 'learning_rate': 0.07018211474264216}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.2158418038452445
Fold 2 IBS: 0.16930084833762463
Fold 3 IBS: 0.17116977548320733
Fold 4 IBS: 0.18903359562855004
Fold 5 IBS: 0.17803894228120742
[I 2024-04-17 22:57:37,439] Trial 52 finished with value: 0.18467699311516678 and parameters: {'subsample': 0.13494378844422814, 'dropout_rate': 0.10510137537932576, 'n_estimators': 59, 'learning_rate': 0.06926018955996141}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.28288236355987806
Fold 2 IBS: 0.21847675885193776
Fold 3 IBS: 0.24935372108583392
Fold 4 IBS: 0.22221290472258226
Fold 5 IBS: 0.24628691713949746
[I 2024-04-17 22:57:44,304] Trial 53 finished with value: 0.2438425330719459 and parameters: {'subsample': 0.14863982748363808, 'dropout_rate': 0.10187914564083042, 'n_estimators': 276, 'learning_rate': 0.07644499460442745}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.2225078927379004
Fold 2 IBS: 0.18797259457368376
Fold 3 IBS: 0.17128012103156776
Fold 4 IBS: 0.22549666468219204
Fold 5 IBS: 0.17920612441126121
[I 2024-04-17 22:57:45,637] Trial 54 finished with value: 0.19729267948732104 and parameters: {'subsample': 0.7123271512684496, 'dropout_rate': 0.1469933982907719, 'n_estimators': 49, 'learning_rate': 0.07105739554621304}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.20159103570325065
Fold 2 IBS: 0.19545719189005537
Fold 3 IBS: 0.18814317476184295
Fold 4 IBS: 0.20572308776907441
Fold 5 IBS: 0.20056342819170453
[I 2024-04-17 22:57:46,295] Trial 55 finished with value: 0.1982955836631856 and parameters: {'subsample': 0.12744461040189287, 'dropout_rate': 0.25227527653590254, 'n_estimators': 18, 'learning_rate': 0.058792439227992585}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.23549485408240572
Fold 2 IBS: 0.17663926385669818
Fold 3 IBS: 0.18515506504549803
Fold 4 IBS: 0.21513505854512668
Fold 5 IBS: 0.1791259399513439
[I 2024-04-17 22:57:48,823] Trial 56 finished with value: 0.19831003629621452 and parameters: {'subsample': 0.21188455005588142, 'dropout_rate': 0.13179976620229178, 'n_estimators': 103, 'learning_rate': 0.0641028486764566}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.2366977773273201
Fold 2 IBS: 0.18854370730838502

Fold 3 IBS: 0.1939186074484014
Fold 4 IBS: 0.2132464949688479
Fold 5 IBS: 0.18111813126890497
[I 2024-04-17 22:57:50,860] Trial 57 finished with value: 0.2027049436643719 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.23806025997264035, 'n_estimators': 81, 'learning_rate': 0.08927098403763303}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.21967163466408127
Fold 2 IBS: 0.1817845467825258
Fold 3 IBS: 0.1718116182769781
Fold 4 IBS: 0.21134882526508325
Fold 5 IBS: 0.178176570422679
[I 2024-04-17 22:57:52,267] Trial 58 finished with value: 0.1925586390822695 and parameters: {'subsample': 0.2849097248903497, 'dropout_rate': 0.17854033983790962, 'n_estimators': 52, 'learning_rate': 0.06792721960100616}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.20555111235130516
Fold 2 IBS: 0.2055417194065782
Fold 3 IBS: 0.19122632129312667
Fold 4 IBS: 0.2100252252563886
Fold 5 IBS: 0.20550842113648382
[I 2024-04-17 22:57:52,860] Trial 59 finished with value: 0.20357055988877648 and parameters: {'subsample': 0.19280210316989804, 'dropout_rate': 0.1599945319557546, 'n_estimators': 15, 'learning_rate': 0.047995048145847055}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.30260929924850716
Fold 2 IBS: 0.31084956754917165
Fold 3 IBS: 0.26728473033896943
Fold 4 IBS: 0.26573121972845387
Fold 5 IBS: 0.26727306359213127
[I 2024-04-17 22:58:00,764] Trial 60 finished with value: 0.28274957609144663 and parameters: {'subsample': 0.2490257490592003, 'dropout_rate': 0.320245548964296, 'n_estimators': 319, 'learning_rate': 0.07454832842064382}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.2196652466925002
Fold 2 IBS: 0.18369433892796294
Fold 3 IBS: 0.17422286477408222
Fold 4 IBS: 0.2072263447905633
Fold 5 IBS: 0.17589225458336172
[I 2024-04-17 22:58:02,410] Trial 61 finished with value: 0.19214020995369405 and parameters: {'subsample': 0.17305081470095895, 'dropout_rate': 0.375136566118901, 'n_estimators': 64, 'learning_rate': 0.06842220294262286}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.22815542517493032
Fold 2 IBS: 0.1667032799133066
Fold 3 IBS: 0.1816473547100083
Fold 4 IBS: 0.2006047012754153
Fold 5 IBS: 0.1818730646331206
[I 2024-04-17 22:58:04,619] Trial 62 finished with value: 0.1917967651413562 and parameters: {'subsample': 0.1342292818449894, 'dropout_rate': 0.10031395553515703, 'n_estimators': 89, 'learning_rate': 0.07011431096636607}. Best is trial 41 with value: 0.1826902124584475.
Fold 1 IBS: 0.20484745028426124
Fold 2 IBS: 0.1684593854929479
Fold 3 IBS: 0.1692747073328027
Fold 4 IBS: 0.17931866280493863
Fold 5 IBS: 0.17993430883779774
[I 2024-04-17 22:58:05,698] Trial 63 finished with value: 0.18036690295054963 and parameters: {'subsample': 0.1060053487431015, 'dropout_rate': 0.23127988418023382, 'n_estimators': 38, 'learning_rate': 0.08155387781044005}. Best is trial 63 with value: 0.18036690295054963.
Fold 1 IBS: 0.21240483799940627
Fold 2 IBS: 0.16432833903987873
Fold 3 IBS: 0.16948100712158579
Fold 4 IBS: 0.1771893007541963
Fold 5 IBS: 0.1782017519920781
[I 2024-04-17 22:58:06,804] Trial 64 finished with value: 0.180321047381429 and parameters: {'subsample': 0.10180710042129003, 'dropout_rate': 0.22493611916715012, 'n_estimators': 40, 'learning_rate': 0.09743269447662792}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.2158805770114877
Fold 2 IBS: 0.16903421596638618
Fold 3 IBS: 0.16954309446297816
Fold 4 IBS: 0.18777977625758463
Fold 5 IBS: 0.17744301798776316
[I 2024-04-17 22:58:07,816] Trial 65 finished with value: 0.18393613633723999 and parameters: {'subsample': 0.1348839454118233, 'dropout_rate': 0.2226696810853981, 'n_estimators': 35, 'learning_rate': 0.09657359215516455}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22779713706361782
Fold 2 IBS: 0.18147720959313812
Fold 3 IBS: 0.17184835361666992
Fold 4 IBS: 0.20334788169825696
Fold 5 IBS: 0.18019513378828342
[I 2024-04-17 22:58:09,058] Trial 66 finished with value: 0.19293314315199325 and parameters: {'subsample': 0.21995641524120108, 'dropout_rate': 0.22271190452360984, 'n_estimators': 44, 'learning_rate': 0.09973045543351286}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.21210176109007312
Fold 2 IBS: 0.18698368407792879
Fold 3 IBS: 0.17417843888371987
Fold 4 IBS: 0.21297556972502177
Fold 5 IBS: 0.18638330293562919
[I 2024-04-17 22:58:09,855] Trial 67 finished with value: 0.19452455134247454 and parameters: {'subsample': 0.8036527117288321, 'dropout_rate': 0.27509529884825623, 'n_estimators': 25, 'learning_rate': 0.09490401293367616}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.21309277813688046
Fold 2 IBS: 0.21797566261096651
Fold 3 IBS: 0.20320643623771767
Fold 4 IBS: 0.22312740270163917
Fold 5 IBS: 0.21567682370134103
[I 2024-04-17 22:58:10,158] Trial 68 finished with value: 0.21461582067770898 and parameters: {'subsample': 0.12955584019903935, 'dropout_rate': 0.29831628233275864, 'n_estimators': 1, 'learning_rate': 0.0962514739613329}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.21125311963470775
Fold 2 IBS: 0.17894252158828264
Fold 3 IBS: 0.1713390197688576
Fold 4 IBS: 0.20299389079355468
Fold 5 IBS: 0.18114730311123142
[I 2024-04-17 22:58:11,085] Trial 69 finished with value: 0.1891351709793268 and parameters: {'subsample': 0.18890607008448618, 'dropout_rate': 0.23851494482862293, 'n_estimators': 32, 'learning_rate': 0.08203348038736819}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.3131682272591902
Fold 2 IBS: 0.2892518403708641
Fold 3 IBS: 0.2714253318148901
Fold 4 IBS: 0.2408200971495939
Fold 5 IBS: 0.2709140135016406
[I 2024-04-17 22:58:22,881] Trial 70 finished with value: 0.2771159020192358 and parameters: {'subsample': 0.14078324522545957, 'dropout_rate': 0.16568782063879947, 'n_estimators': 408, 'learning_rate': 0.0901481447435182}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.23097135561629842
Fold 2 IBS: 0.15082119946746947
Fold 3 IBS: 0.18620352302293233
Fold 4 IBS: 0.19146145500333925
Fold 5 IBS: 0.18469384937306144
[I 2024-04-17 22:58:24,889] Trial 71 finished with value: 0.18883027649662015 and parameters: {'subsample': 0.10674377544765791, 'dropout_rate': 0.12961833118929164, 'n_estimators': 73, 'learning_rate': 0.09940908227593069}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.2066681851135183
Fold 2 IBS: 0.16960985839914391
Fold 3 IBS: 0.1703877828520537
Fold 4 IBS: 0.2029467766548087
Fold 5 IBS: 0.17828323644053587
[I 2024-04-17 22:58:26,123] Trial 72 finished with value: 0.18557916789201212 and parameters: {'subsample': 0.16219429367798271, 'dropout_rate': 0.1782286970000978, 'n_estimators': 39, 'learning_rate': 0.0865861861672653}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.215214285879969
Fold 2 IBS: 0.162985586627941
Fold 3 IBS: 0.17235640960342394
Fold 4 IBS: 0.20121838073424614
Fold 5 IBS: 0.17838892770085352
[I 2024-04-17 22:58:27,471] Trial 73 finished with value: 0.18603271810928673 and parameters: {'subsample': 0.18597033136891927, 'dropout_rate': 0.1753261848588733, 'n_estimators': 38, 'learning_rate': 0.09325827522149316}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20268084289847754
Fold 2 IBS: 0.19476540289987593
Fold 3 IBS: 0.1845680015472209
Fold 4 IBS: 0.20344027843432377
Fold 5 IBS: 0.1984301867177412
[I 2024-04-17 22:58:28,261] Trial 74 finished with value: 0.19677694249952787 and parameters: {'subsample': 0.1549331134802546, 'dropout_rate': 0.34578330340113894, 'n_estimators': 14, 'learning_rate': 0.08880318604659877}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22546495703846037
Fold 2 IBS: 0.17116786443707926
Fold 3 IBS: 0.1748122904187679
Fold 4 IBS: 0.1863140161427983
Fold 5 IBS: 0.17662749582325543
[I 2024-04-17 22:58:29,793] Trial 75 finished with value: 0.18687732477207225 and parameters: {'subsample': 0.1270645713264064, 'dropout_rate': 0.22744316060692982, 'n_estimators': 50, 'learning_rate': 0.08580196757868053}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.24879638066547688
Fold 2 IBS: 0.20952768757836004
Fold 3 IBS: 0.21181716134682574

Fold 4 IBS: 0.24665592028691383
Fold 5 IBS: 0.19968789391964245
[I 2024-04-17 22:58:32,660] Trial 76 finished with value: 0.22329700875944378 and parameters: {'subsample': 0.16179134803259218, 'dropout_rate': 0.419783783711314, 'n_estimators': 109, 'learning_rate': 0.08167091626897967}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20604843080214338
Fold 2 IBS: 0.17946418794018407
Fold 3 IBS: 0.1748760996782727
Fold 4 IBS: 0.20466159091160982
Fold 5 IBS: 0.1858390531142425
[I 2024-04-17 22:58:33,584] Trial 77 finished with value: 0.1901778724892905 and parameters: {'subsample': 0.2243276930985941, 'dropout_rate': 0.12071886742003879, 'n_estimators': 29, 'learning_rate': 0.07730762793455846}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.2578625406880957
Fold 2 IBS: 0.18836967898386145
Fold 3 IBS: 0.22090659208224933
Fold 4 IBS: 0.2174243607349852
Fold 5 IBS: 0.21571453745097394
[I 2024-04-17 22:58:36,825] Trial 78 finished with value: 0.22005554198803315 and parameters: {'subsample': 0.12287626673759706, 'dropout_rate': 0.15485763416692047, 'n_estimators': 128, 'learning_rate': 0.09760139500608556}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.2457522106806641
Fold 2 IBS: 0.20106833968622131
Fold 3 IBS: 0.20240303091569015
Fold 4 IBS: 0.2355529034689702
Fold 5 IBS: 0.18678232975270265
[I 2024-04-17 22:58:39,074] Trial 79 finished with value: 0.21431176290084966 and parameters: {'subsample': 0.1973180142174715, 'dropout_rate': 0.26293784447643637, 'n_estimators': 90, 'learning_rate': 0.08731485555810001}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22067632466373324
Fold 2 IBS: 0.17624927344904337
Fold 3 IBS: 0.17202719749610798
Fold 4 IBS: 0.21730049556767378
Fold 5 IBS: 0.17806821771202486
[I 2024-04-17 22:58:40,199] Trial 80 finished with value: 0.19286430177771663 and parameters: {'subsample': 0.2613932849707703, 'dropout_rate': 0.202064330173782, 'n_estimators': 40, 'learning_rate': 0.09263526846391419}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.21206096002623742
Fold 2 IBS: 0.16527031854312244
Fold 3 IBS: 0.17152985432196619
Fold 4 IBS: 0.19537672299398604
Fold 5 IBS: 0.1804932498218216
[I 2024-04-17 22:58:41,239] Trial 81 finished with value: 0.18494622114142673 and parameters: {'subsample': 0.17490524646533434, 'dropout_rate': 0.1788569220537291, 'n_estimators': 37, 'learning_rate': 0.09291995762116567}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22279354778537835
Fold 2 IBS: 0.17554115294750422
Fold 3 IBS: 0.17478776997555606
Fold 4 IBS: 0.202818848417891
Fold 5 IBS: 0.17938830039368828
[I 2024-04-17 22:58:42,875] Trial 82 finished with value: 0.19106592390400357 and parameters: {'subsample': 0.1656748302619644, 'dropout_rate': 0.18324255894296368, 'n_estimators': 61, 'learning_rate': 0.09477390252988176}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20618787778791522
Fold 2 IBS: 0.20737334236667984
Fold 3 IBS: 0.19458903750594153
Fold 4 IBS: 0.20914694811834128
Fold 5 IBS: 0.2095612343608334
[I 2024-04-17 22:58:43,293] Trial 83 finished with value: 0.20537168802794223 and parameters: {'subsample': 0.1022824556934966, 'dropout_rate': 0.30041751871331024, 'n_estimators': 7, 'learning_rate': 0.0913551297402999}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.2406978879167472
Fold 2 IBS: 0.19226053087271278
Fold 3 IBS: 0.18361068587581464
Fold 4 IBS: 0.22085390790874676
Fold 5 IBS: 0.17823291284527523
[I 2024-04-17 22:58:45,176] Trial 84 finished with value: 0.20313118508385936 and parameters: {'subsample': 0.5584624909113933, 'dropout_rate': 0.1433195777587662, 'n_estimators': 73, 'learning_rate': 0.08256461132797006}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20412215530632952
Fold 2 IBS: 0.175837007929629
Fold 3 IBS: 0.17345372993073394
Fold 4 IBS: 0.19091887782695993
Fold 5 IBS: 0.18665221543172858
[I 2024-04-17 22:58:46,033] Trial 85 finished with value: 0.18619679728507618 and parameters: {'subsample': 0.14658213602932155, 'dropout_rate': 0.11636134246427338, 'n_estimators': 28, 'learning_rate': 0.08439809320755474}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22353557331790747
Fold 2 IBS: 0.19019522014201537
Fold 3 IBS: 0.17272389219558867
Fold 4 IBS: 0.20458846720388746
Fold 5 IBS: 0.18046866924291438
[I 2024-04-17 22:58:47,454] Trial 86 finished with value: 0.19430236442046267 and parameters: {'subsample': 0.1821705123939037, 'dropout_rate': 0.21489682302184204, 'n_estimators': 55, 'learning_rate': 0.08783605043610347}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20420957831239944
Fold 2 IBS: 0.16757815971005602
Fold 3 IBS: 0.17452317203439577
Fold 4 IBS: 0.18972035804809262
Fold 5 IBS: 0.1774250190372056
[I 2024-04-17 22:58:48,613] Trial 87 finished with value: 0.1826912574284299 and parameters: {'subsample': 0.1205205879501397, 'dropout_rate': 0.24877711982098155, 'n_estimators': 40, 'learning_rate': 0.07961148176611225}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.21397750476088379
Fold 2 IBS: 0.17317974573185793
Fold 3 IBS: 0.1741774701631789
Fold 4 IBS: 0.2025172492081561
Fold 5 IBS: 0.17643267859074482
[I 2024-04-17 22:58:49,710] Trial 88 finished with value: 0.1880569296909643 and parameters: {'subsample': 0.20440862881305094, 'dropout_rate': 0.2523499457097179, 'n_estimators': 39, 'learning_rate': 0.08033770369557307}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.2053567552269537
Fold 2 IBS: 0.1963782022446877
Fold 3 IBS: 0.1849555341029256
Fold 4 IBS: 0.20553127953020076
Fold 5 IBS: 0.19657994800597778
[I 2024-04-17 22:58:50,206] Trial 89 finished with value: 0.1977603438221491 and parameters: {'subsample': 0.22932405066568767, 'dropout_rate': 0.18531333494965943, 'n_estimators': 11, 'learning_rate': 0.09754500839459641}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.2353312300846258
Fold 2 IBS: 0.19216420592093555
Fold 3 IBS: 0.19418414260148123
Fold 4 IBS: 0.2173094717033464
Fold 5 IBS: 0.18422474022161592
[I 2024-04-17 22:58:52,684] Trial 90 finished with value: 0.20464275810640098 and parameters: {'subsample': 0.1262577279641907, 'dropout_rate': 0.2835003991831958, 'n_estimators': 99, 'learning_rate': 0.07534883276700306}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22040145861193025
Fold 2 IBS: 0.17894337632091195
Fold 3 IBS: 0.17883975353017603
Fold 4 IBS: 0.20537140725693795
Fold 5 IBS: 0.1771852770180485
[I 2024-04-17 22:58:54,491] Trial 91 finished with value: 0.19214825454760093 and parameters: {'subsample': 0.11999853831426363, 'dropout_rate': 0.5129929513238454, 'n_estimators': 69, 'learning_rate': 0.07168332505298398}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22601376497950812
Fold 2 IBS: 0.17776760281474657
Fold 3 IBS: 0.17768824307819173
Fold 4 IBS: 0.2025868905995876
Fold 5 IBS: 0.17656953368316938
[I 2024-04-17 22:58:56,571] Trial 92 finished with value: 0.1921252070310407 and parameters: {'subsample': 0.1440485007553197, 'dropout_rate': 0.24181782931525808, 'n_estimators': 82, 'learning_rate': 0.06402109960446176}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20475187706504125
Fold 2 IBS: 0.18731137885032467
Fold 3 IBS: 0.18007827170477764
Fold 4 IBS: 0.20080651028223812
Fold 5 IBS: 0.19373356431659264
[I 2024-04-17 22:58:57,263] Trial 93 finished with value: 0.19333632044379484 and parameters: {'subsample': 0.17178762815637874, 'dropout_rate': 0.2104547169433691, 'n_estimators': 20, 'learning_rate': 0.07869481904781718}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.21840289347880504
Fold 2 IBS: 0.15540488564914912
Fold 3 IBS: 0.1759194525708696
Fold 4 IBS: 0.19455030853454355
Fold 5 IBS: 0.17976914633202942
[I 2024-04-17 22:58:58,719] Trial 94 finished with value: 0.18480933731307936 and parameters: {'subsample': 0.10209271466962214, 'dropout_rate': 0.1504404216498022, 'n_estimators': 53, 'learning_rate': 0.09459054530030528}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.21383222307084906
Fold 2 IBS: 0.1687687954776852
Fold 3 IBS: 0.17489987803973867
Fold 4 IBS: 0.19605853904417397

Fold 5 IBS: 0.17731417034945413
[I 2024-04-17 22:59:00,201] Trial 95 finished with value: 0.18617472119638018 and parameters: {'subsample': 0.1574638138642586, 'dropout_rate': 0.15912282102770056, 'n_estimators': 52, 'learning_rate': 0.09300288337363928}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20382017098407673
Fold 2 IBS: 0.16319103881220723
Fold 3 IBS: 0.17046677831779045
Fold 4 IBS: 0.20185197772656355
Fold 5 IBS: 0.18388128331588338
[I 2024-04-17 22:59:01,289] Trial 96 finished with value: 0.18464224983130428 and parameters: {'subsample': 0.11389291137795171, 'dropout_rate': 0.1513089117226007, 'n_estimators': 38, 'learning_rate': 0.09026893567244454}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.20092420283967471
Fold 2 IBS: 0.18463472486015584
Fold 3 IBS: 0.17458222345731694
Fold 4 IBS: 0.19582668698716618
Fold 5 IBS: 0.1854345602840061
[I 2024-04-17 22:59:02,013] Trial 97 finished with value: 0.18828047968566394 and parameters: {'subsample': 0.11561443017962356, 'dropout_rate': 0.3212552426504853, 'n_estimators': 22, 'learning_rate': 0.09500831145565551}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.23291497030133765
Fold 2 IBS: 0.17840817791413485
Fold 3 IBS: 0.17592867252086788
Fold 4 IBS: 0.21641464555063408
Fold 5 IBS: 0.17604783025438303
[I 2024-04-17 22:59:03,414] Trial 98 finished with value: 0.1959428593082715 and parameters: {'subsample': 0.6340595518294957, 'dropout_rate': 0.1392716217479098, 'n_estimators': 53, 'learning_rate': 0.09078133686786893}. Best is trial 64 with value: 0.180321047381429.
Fold 1 IBS: 0.22375975013340513
Fold 2 IBS: 0.16387339087092628
Fold 3 IBS: 0.17779286543809364
Fold 4 IBS: 0.18843720733120942
Fold 5 IBS: 0.18526423794694236
[I 2024-04-17 22:59:05,114] Trial 99 finished with value: 0.18782549034411536 and parameters: {'subsample': 0.10064643807992914, 'dropout_rate': 0.10097204350567876, 'n_estimators': 66, 'learning_rate': 0.09800772316634063}. Best is trial 64 with value: 0.180321047381429.


* Best trial for IBS:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.180321047381429], datetime_start=datetime.datetime(2024, 4, 17, 22, 58, 5, 700077), datetime_complete=datetime.datetime(2024, 4, 17, 22, 58, 6, 804383), params={'subsample': 0.10180710042129003, 'dropout_rate': 0.22493611916715012, 'n_estimators': 40, 'learning_rate': 0.09743269447662792}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=64, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10180710042129003, 'dropout_rate': 0.22493611916715012, 'n_estimators': 40, 'learning_rate': 0.09743269447662792}


* Best Score for IBS:
 0.180321047381429

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.729
train_ibs:  0.18

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10064271403610489,
                                              learning_rate=0.09170799123141873,
                                              n_estimators=119,
                                              random_state=123,
                                              subsample=0.12850189742120152)

C-index score: 0.58

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.22493611916715012,
                                              learning_rate=0.09743269447662792,
                                              n_estimators=40, random_state=123,
                                              subsample=0.10180710042129003)

IBS: 0.237

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [80]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.886   1.0
Randomsurvivalforest             0.864   2.0
GradientBoosting                 0.758   3.0
ComponentwiseGradientBoosting    0.729   4.0
CoxElastic                       0.717   5.0
CoxLasso                         0.706   6.0
CoxRidge                         0.651   7.0

In [81]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.179   1.0
ComponentwiseGradientBoosting  0.180   2.0
Randomsurvivalforest           0.183   3.0
CoxElastic                     0.195   4.0
CoxLasso                       0.202   5.0
GradientBoosting               0.208   6.0
CoxRidge                       0.217   7.0

In [82]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.662   1.0
Randomsurvivalforest             0.629   2.0
GradientBoosting                 0.618   3.0
CoxLasso                         0.597   4.5
CoxElastic                       0.597   4.5
CoxRidge                         0.592   6.0
ComponentwiseGradientBoosting    0.580   7.0

In [83]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.200   1.0
Randomsurvivalforest           0.205   2.0
GradientBoosting               0.213   3.0
CoxRidge                       0.221   5.0
CoxLasso                       0.221   5.0
CoxElastic                     0.221   5.0
ComponentwiseGradientBoosting  0.237   7.0

In [84]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/robust/no_selection/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_robust_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [85]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-17