In [1]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import PowerTransformer

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [14]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Yeo-Johnson Transformation

In [16]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [17]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [18]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,1.124852,0.125487,0.072022,-0.784694
1,0.161153,-0.358143,-1.421627,-0.784694
2,-1.401990,0.250624,0.444135,0.236612
3,-0.012817,-0.946686,-1.314128,-0.784694
4,-1.982774,1.502519,-0.468644,1.784568
...,...,...,...,...
134,0.823106,-0.175124,-0.601731,-0.784694
135,0.532655,1.517088,0.002519,-0.784694
136,-0.421265,-0.622476,-0.316986,-0.784694
137,0.552472,1.639161,0.314722,-0.784694
138,0.528431,1.187641,-0.839594,-0.784694

In [19]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [20]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,-0.228627,0.816980,0.557388,0.033184
1,-0.204032,-1.995319,0.050605,1.682719
2,-0.770221,-0.736265,0.221607,0.693043
3,-1.281223,-1.151240,0.329735,-0.784694
4,-0.689674,-0.085023,0.794695,-0.784694
...,...,...,...,...
94,-0.180591,0.304443,-0.506427,-0.784694
95,-0.674760,-0.848664,0.615633,-0.784694
96,-0.513250,-1.682811,0.580714,-0.784694
97,0.600661,-0.466149,0.254712,-0.784694
98,-0.166374,-1.007217,-0.320388,-0.784694

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [21]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:09:42,635] A new study created in memory with name: no-name-f8ac055a-36cb-4324-ac86-71b1652da0a9

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7341772151898734

[I 2024-04-16 01:10:02,034] A new study created in memory with name: no-name-e7dce323-0925-4d30-a6ed-5b8463d3a1d5

Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:02,017] Trial 0 finished with value: 0.7413282913937062 and parameters: {}. Best is trial 0 with value: 0.7413282913937062.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7413282913937062], datetime_start=datetime.datetime(2024, 4, 16, 1, 9, 42, 804098), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 2, 15459), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7413282913937062

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.17729223997811025
Fold 2 IBS: 0.1563208701196685
Fold 3 IBS: 0.17242156247569246
Fold 4 IBS: 0.16843736811635485
Fold 5 IBS: 0.20228114907240044
[I 2024-04-16 01:10:03,104] Trial 0 finished with value: 0.17535063795244532 and parameters: {}. Best is trial 0 with value: 0.17535063795244532.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17535063795244532], datetime_start=datetime.datetime(2024, 4, 16, 1, 10, 2, 83138), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 3, 103816), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17535063795244532

In [22]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [23]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.741
train_ibs:  0.175

#### Test

In [24]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [25]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.56
IBS score: 0.264

In [26]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [27]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [28]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:10:03,673] A new study created in memory with name: no-name-954dc7d1-d89f-44c7-82c0-b39f2cbef0b2

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687

[I 2024-04-16 01:10:04,499] A new study created in memory with name: no-name-d678922c-651e-4bcb-9f67-fa3871285227

Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:10:04,470] Trial 0 finished with value: 0.7232935869123901 and parameters: {}. Best is trial 0 with value: 0.7232935869123901.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7232935869123901], datetime_start=datetime.datetime(2024, 4, 16, 1, 10, 3, 893094), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 4, 469914), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7232935869123901

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651518813013
Fold 2 IBS: 0.22157790765592797
Fold 3 IBS: 0.20453593880864498
Fold 4 IBS: 0.22473803370121878
Fold 5 IBS: 0.21812430704714597
[I 2024-04-16 01:10:05,250] Trial 0 finished with value: 0.2165905404802136 and parameters: {}. Best is trial 0 with value: 0.2165905404802136.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2165905404802136], datetime_start=datetime.datetime(2024, 4, 16, 1, 10, 4, 542141), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 5, 250476), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2165905404802136

In [29]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [30]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.723
train_ibs:  0.217

#### Test

In [31]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [32]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.57

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [33]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [34]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:10:06,008] A new study created in memory with name: no-name-f27d6a5a-5a88-4df0-a516-5492148cce84

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734

[I 2024-04-16 01:10:07,036] A new study created in memory with name: no-name-5a67748c-8526-40b6-8c38-531483a0d833

Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:07,028] Trial 0 finished with value: 0.7421336135225577 and parameters: {}. Best is trial 0 with value: 0.7421336135225577.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7421336135225577], datetime_start=datetime.datetime(2024, 4, 16, 1, 10, 6, 67854), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 7, 27980), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7421336135225577

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1779043098246738
Fold 2 IBS: 0.15504261131624741
Fold 3 IBS: 0.17188827223778808
Fold 4 IBS: 0.16854859140993816
Fold 5 IBS: 0.20132009844395674
[I 2024-04-16 01:10:07,952] Trial 0 finished with value: 0.17494077664652083 and parameters: {}. Best is trial 0 with value: 0.17494077664652083.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.17494077664652083], datetime_start=datetime.datetime(2024, 4, 16, 1, 10, 7, 69467), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 7, 952319), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.17494077664652083

In [35]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [36]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.742
train_ibs:  0.175

#### Test

In [37]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [38]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.561

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.262

In [39]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [40]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:10:08,559] A new study created in memory with name: no-name-6e0761dc-f1a3-4421-b82e-a7c61004cf6a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:09,518] Trial 0 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:10,466] Trial 1 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:11,406] Trial 2 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:13,012] Trial 3 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:14,114] Trial 4 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:15,557] Trial 5 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:16,570] Trial 6 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:17,696] Trial 7 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:18,647] Trial 8 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:19,637] Trial 9 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:20,565] Trial 10 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:21,514] Trial 11 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:22,793] Trial 12 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:24,256] Trial 13 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.8178071080614558}. Best is trial 0 with value: 0.7421336135225577.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:25,595] Trial 14 finished with value: 0.7421555325318184 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:10:26,173] Trial 15 finished with value: 0.726710364570146 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:10:26,720] Trial 16 finished with value: 0.726710364570146 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:27,559] Trial 17 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.1989440786901095}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:28,621] Trial 18 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.5859218723993685}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:29,538] Trial 19 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.1381692417541623}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:30,853] Trial 20 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:32,520] Trial 21 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.5905060859777884}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:37,098] Trial 22 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.6211849927954638}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:38,735] Trial 23 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.8504278211576997}. Best is trial 14 with value: 0.7421555325318184.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:39,602] Trial 24 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.6776130739315861}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:40,815] Trial 25 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.3339178579541805}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:41,886] Trial 26 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.7685574200470692}. Best is trial 14 with value: 0.7421555325318184.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:42,960] Trial 27 finished with value: 0.7431359246886812 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 27 with value: 0.7431359246886812.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:44,471] Trial 28 finished with value: 0.7422701238228804 and parameters: {'l1_ratio': 0.13244204373977508}. Best is trial 27 with value: 0.7431359246886812.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:46,266] Trial 29 finished with value: 0.7422701238228804 and parameters: {'l1_ratio': 0.09782192730809623}. Best is trial 27 with value: 0.7431359246886812.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:47,728] Trial 30 finished with value: 0.7431359246886812 and parameters: {'l1_ratio': 0.08776466578483758}. Best is trial 27 with value: 0.7431359246886812.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:49,788] Trial 31 finished with value: 0.7422701238228804 and parameters: {'l1_ratio': 0.09882582051546042}. Best is trial 27 with value: 0.7431359246886812.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:51,557] Trial 32 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.18538686663719506}. Best is trial 27 with value: 0.7431359246886812.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:53,403] Trial 33 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.2744453426928596}. Best is trial 27 with value: 0.7431359246886812.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:56,116] Trial 34 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.06342138075355325}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:10:58,326] Trial 35 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.0683344135092746}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:00,351] Trial 36 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.048228868493022964}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:02,206] Trial 37 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.048124676153225805}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:03,771] Trial 38 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.03384859509331414}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:04,979] Trial 39 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.26711141046490927}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:06,434] Trial 40 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.2255413981648162}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:08,175] Trial 41 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.04361523969761801}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:09,869] Trial 42 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.04891179745246506}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:11,092] Trial 43 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.16504678302400444}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:12,564] Trial 44 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.055372480922944715}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:11:13,078] Trial 45 finished with value: 0.726710364570146 and parameters: {'l1_ratio': 0.003595022943499726}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:14,431] Trial 46 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.34291267707472417}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:15,970] Trial 47 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.1426102255542931}. Best is trial 34 with value: 0.744001725554482.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:17,192] Trial 48 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.04789647795907515}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:18,125] Trial 49 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:19,423] Trial 50 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.2311229033161103}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:20,411] Trial 51 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.04055863440079485}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:21,298] Trial 52 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.05741190972731476}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:11:21,632] Trial 53 finished with value: 0.7275542464266861 and parameters: {'l1_ratio': 0.001306267661420904}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:23,033] Trial 54 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.13832094749192683}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:24,382] Trial 55 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.19701142850924033}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:25,340] Trial 56 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.07038493261069548}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:26,553] Trial 57 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.029667104803927064}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:27,656] Trial 58 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.11030888845248547}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:28,971] Trial 59 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.1597157446924673}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:30,920] Trial 60 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.23699706922240232}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:32,298] Trial 61 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.03284552138967742}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:33,775] Trial 62 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.06671305675047365}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:35,174] Trial 63 finished with value: 0.7422701238228804 and parameters: {'l1_ratio': 0.11757595111856019}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:36,331] Trial 64 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.027762787057419518}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:37,241] Trial 65 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.07693657175234324}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:11:37,661] Trial 66 finished with value: 0.7275542464266861 and parameters: {'l1_ratio': 0.00036235791288150715}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:38,532] Trial 67 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.17527020062217666}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:39,374] Trial 68 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.5291212647580814}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:40,728] Trial 69 finished with value: 0.7421336135225577 and parameters: {'l1_ratio': 0.9399011051788413}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:41,796] Trial 70 finished with value: 0.7422701238228804 and parameters: {'l1_ratio': 0.11960951880417053}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:42,991] Trial 71 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.07425921203672739}. Best is trial 34 with value: 0.744001725554482.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:44,713] Trial 72 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.04221676663961268}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:46,162] Trial 73 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.06058584633618238}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:47,211] Trial 74 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.09968770271378188}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:48,338] Trial 75 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.028220565108551154}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:49,405] Trial 76 finished with value: 0.7422701238228804 and parameters: {'l1_ratio': 0.1496463461128409}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:51,178] Trial 77 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.12562884848149397}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:52,436] Trial 78 finished with value: 0.7430213333976192 and parameters: {'l1_ratio': 0.08066889522832607}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:54,032] Trial 79 finished with value: 0.7380455772723845 and parameters: {'l1_ratio': 0.021791681783771045}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:55,135] Trial 80 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.31367987266780684}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:56,503] Trial 81 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.05308572933338293}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:58,067] Trial 82 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.0411846764829102}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:11:59,840] Trial 83 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.05731837359676724}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:01,012] Trial 84 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.09304421615887598}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:02,150] Trial 85 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.20926625767821566}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:03,189] Trial 86 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.16641409306137536}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:12:03,705] Trial 87 finished with value: 0.7275542464266861 and parameters: {'l1_ratio': 0.0003285494185073165}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:04,953] Trial 88 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.1140334798190429}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:06,183] Trial 89 finished with value: 0.7380455772723845 and parameters: {'l1_ratio': 0.024157690007653845}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:07,218] Trial 90 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.08446531947541283}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:08,239] Trial 91 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.04973973699538567}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:09,352] Trial 92 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.047360104486521365}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:10,368] Trial 93 finished with value: 0.7389384344152417 and parameters: {'l1_ratio': 0.02429494335896844}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:11,267] Trial 94 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.07973101612752595}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:12,129] Trial 95 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.13644176948367934}. Best is trial 34 with value: 0.744001725554482.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:13,054] Trial 96 finished with value: 0.7422701238228804 and parameters: {'l1_ratio': 0.09829905834407042}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:13,805] Trial 97 finished with value: 0.7239763132031204 and parameters: {'l1_ratio': 0.017912383092734664}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:14,826] Trial 98 finished with value: 0.744001725554482 and parameters: {'l1_ratio': 0.06060795113013872}. Best is trial 34 with value: 0.744001725554482.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173

[I 2024-04-16 01:12:16,019] A new study created in memory with name: no-name-ab248e06-c0cd-417e-b0b2-06f6e1eab2b7

Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:12:16,006] Trial 99 finished with value: 0.7412897316660176 and parameters: {'l1_ratio': 0.15427911972721128}. Best is trial 34 with value: 0.744001725554482.


* Best trial for C-index:
 FrozenTrial(number=34, state=TrialState.COMPLETE, values=[0.744001725554482], datetime_start=datetime.datetime(2024, 4, 16, 1, 10, 53, 450926), datetime_complete=datetime.datetime(2024, 4, 16, 1, 10, 56, 115691), params={'l1_ratio': 0.06342138075355325}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=34, value=None)


* Best Score for C-index:
 0.744001725554482

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17773835852772943
Fold 2 IBS: 0.1550120702715064
Fold 3 IBS: 0.17191349212398738
Fold 4 IBS: 0.1686465365477962
Fold 5 IBS: 0.20125460574969775
[I 2024-04-16 01:12:16,904] Trial 0 finished with value: 0.17491301264414344 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17740207527100574
Fold 2 IBS: 0.1550051342160191
Fold 3 IBS: 0.17206496653003014
Fold 4 IBS: 0.16887110007253892
Fold 5 IBS: 0.201283526483594
[I 2024-04-16 01:12:17,898] Trial 1 finished with value: 0.17492536051463756 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17733304969015584
Fold 2 IBS: 0.15508564163582447
Fold 3 IBS: 0.1721011248853764
Fold 4 IBS: 0.16891594462206458
Fold 5 IBS: 0.2013016264124419
[I 2024-04-16 01:12:18,955] Trial 2 finished with value: 0.17494747744917266 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17765364740889258
Fold 2 IBS: 0.1550045116818586
Fold 3 IBS: 0.17198089015794088
Fold 4 IBS: 0.1687204932313228
Fold 5 IBS: 0.20131782678845211
[I 2024-04-16 01:12:19,829] Trial 3 finished with value: 0.1749354738536934 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17774440262408817
Fold 2 IBS: 0.15501524971614722
Fold 3 IBS: 0.17191548466666437
Fold 4 IBS: 0.16863400560880626
Fold 5 IBS: 0.20127019963962375
[I 2024-04-16 01:12:20,775] Trial 4 finished with value: 0.17491586845106596 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17753970885443499
Fold 2 IBS: 0.15499389389379623
Fold 3 IBS: 0.17199846921961165
Fold 4 IBS: 0.16878313704197465
Fold 5 IBS: 0.20126042988798867
[I 2024-04-16 01:12:21,520] Trial 5 finished with value: 0.17491512777956122 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17790094787480346
Fold 2 IBS: 0.1550410444271223
Fold 3 IBS: 0.17188732633666157
Fold 4 IBS: 0.16855511271038343
Fold 5 IBS: 0.20131269645860958
[I 2024-04-16 01:12:22,648] Trial 6 finished with value: 0.17493942556151607 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17773516570521225
Fold 2 IBS: 0.15502293513290785
Fold 3 IBS: 0.17191243844329243
Fold 4 IBS: 0.16865319333491688
Fold 5 IBS: 0.20124632830785316
[I 2024-04-16 01:12:23,938] Trial 7 finished with value: 0.17491401218483651 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17759334974634094
Fold 2 IBS: 0.15499875036633873
Fold 3 IBS: 0.17197080274639423
Fold 4 IBS: 0.16875404705813243
Fold 5 IBS: 0.20133288988996276
[I 2024-04-16 01:12:25,040] Trial 8 finished with value: 0.17492996796143384 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17752341975716923
Fold 2 IBS: 0.1549849476148783
Fold 3 IBS: 0.17202789183786604
Fold 4 IBS: 0.1688210171034514
Fold 5 IBS: 0.20130485722827426
[I 2024-04-16 01:12:25,944] Trial 9 finished with value: 0.17493242670832787 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.1779015842872729
Fold 2 IBS: 0.155041340892261
Fold 3 IBS: 0.17188750548285933
Fold 4 IBS: 0.1685538763696504
Fold 5 IBS: 0.20131409951618998
[I 2024-04-16 01:12:26,800] Trial 10 finished with value: 0.1749396813096467 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17774572861310659
Fold 2 IBS: 0.1550159585771702
Fold 3 IBS: 0.17191592121032548
Fold 4 IBS: 0.16863126872321815
Fold 5 IBS: 0.20127360762217114
[I 2024-04-16 01:12:27,938] Trial 11 finished with value: 0.17491649694919834 and parameters: {'l1_ratio': 0.7247200352819855}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17774546430384638
Fold 2 IBS: 0.15501581723530602
Fold 3 IBS: 0.1719158342084172
Fold 4 IBS: 0.16863181391765775
Fold 5 IBS: 0.20127292868300198
[I 2024-04-16 01:12:28,845] Trial 12 finished with value: 0.17491637166964585 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17772627071349345
Fold 2 IBS: 0.15500806984923918
Fold 3 IBS: 0.17194856927019977
Fold 4 IBS: 0.16869553650807217
Fold 5 IBS: 0.20128778564468866
[I 2024-04-16 01:12:29,727] Trial 13 finished with value: 0.17493324639713864 and parameters: {'l1_ratio': 0.6189362712539238}. Best is trial 0 with value: 0.17491301264414344.
Fold 1 IBS: 0.17781936191993641
Fold 2 IBS: 0.1550228086671958
Fold 3 IBS: 0.17187889745200632
Fold 4 IBS: 0.16859453184551182
Fold 5 IBS: 0.2012487404367253
[I 2024-04-16 01:12:30,673] Trial 14 finished with value: 0.17491286806427514 and parameters: {'l1_ratio': 0.8403787283021946}. Best is trial 14 with value: 0.17491286806427514.
Fold 1 IBS: 0.21354067838633897
Fold 2 IBS: 0.22096273268037248
Fold 3 IBS: 0.20398733703111105
Fold 4 IBS: 0.2242408051811026
Fold 5 IBS: 0.21759498004847774
[I 2024-04-16 01:12:31,097] Trial 15 finished with value: 0.21606530666548057 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.17491286806427514.
Fold 1 IBS: 0.17781994203195933
Fold 2 IBS: 0.1550230634794936
Fold 3 IBS: 0.17187907873571492
Fold 4 IBS: 0.16859336963635982
Fold 5 IBS: 0.2012501830808939
[I 2024-04-16 01:12:32,121] Trial 16 finished with value: 0.17491312739288434 and parameters: {'l1_ratio': 0.8431112134784231}. Best is trial 14 with value: 0.17491286806427514.
Fold 1 IBS: 0.17781935936293453
Fold 2 IBS: 0.15502280734510387
Fold 3 IBS: 0.17187889665288536
Fold 4 IBS: 0.1685945369699936
Fold 5 IBS: 0.20124873407603525
[I 2024-04-16 01:12:32,926] Trial 17 finished with value: 0.17491286688139054 and parameters: {'l1_ratio': 0.8403667186917597}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17781334073602245
Fold 2 IBS: 0.15503148162704147
Fold 3 IBS: 0.17192283475229553
Fold 4 IBS: 0.16860664116694343
Fold 5 IBS: 0.20132469707171746
[I 2024-04-16 01:12:33,865] Trial 18 finished with value: 0.17493979907080406 and parameters: {'l1_ratio': 0.8129126688408415}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17782206842698653
Fold 2 IBS: 0.15502416400942803
Fold 3 IBS: 0.17187974340403692
Fold 4 IBS: 0.1685891162288545
Fold 5 IBS: 0.20125546635758895
[I 2024-04-16 01:12:34,852] Trial 19 finished with value: 0.174914111685379 and parameters: {'l1_ratio': 0.8532624399550491}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.1778338087637761
Fold 2 IBS: 0.1550306263419679
Fold 3 IBS: 0.17188361982883602
Fold 4 IBS: 0.16857856882099906
Fold 5 IBS: 0.20128612678401328
[I 2024-04-16 01:12:35,640] Trial 20 finished with value: 0.1749225501079185 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17781250956480432
Fold 2 IBS: 0.15503108090368536
Fold 3 IBS: 0.17192258706860827
Fold 4 IBS: 0.16860831943754506
Fold 5 IBS: 0.20132278697241054
[I 2024-04-16 01:12:36,374] Trial 21 finished with value: 0.17493945678941072 and parameters: {'l1_ratio': 0.8092449428502105}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17767448003772887
Fold 2 IBS: 0.15500704147193545
Fold 3 IBS: 0.1719479235106508
Fold 4 IBS: 0.1686998999004829
Fold 5 IBS: 0.2012828203480544
[I 2024-04-16 01:12:37,236] Trial 22 finished with value: 0.17492243305377048 and parameters: {'l1_ratio': 0.6128453100882165}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17782909299695118
Fold 2 IBS: 0.15502819233859375
Fold 3 IBS: 0.17188216443888782
Fold 4 IBS: 0.16857688964303771
Fold 5 IBS: 0.20127464756538405
[I 2024-04-16 01:12:38,081] Trial 23 finished with value: 0.1749181973965709 and parameters: {'l1_ratio': 0.8922174171284465}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17780732200119964
Fold 2 IBS: 0.15502380623666626
Fold 3 IBS: 0.17192103933549335
Fold 4 IBS: 0.16861883102761227
Fold 5 IBS: 0.20131082823351212
[I 2024-04-16 01:12:38,762] Trial 24 finished with value: 0.17493636536689672 and parameters: {'l1_ratio': 0.7869936796878455}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17771605303600302

Fold 2 IBS: 0.15500852885765679
Fold 3 IBS: 0.1719488571285054
Fold 4 IBS: 0.1686935937965669
Fold 5 IBS: 0.20128999680939944
[I 2024-04-16 01:12:39,690] Trial 25 finished with value: 0.1749314059256263 and parameters: {'l1_ratio': 0.6216865350760052}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17783371963862415
Fold 2 IBS: 0.15503058028416897
Fold 3 IBS: 0.17188359234076203
Fold 4 IBS: 0.16857875987108376
Fold 5 IBS: 0.20128591032348828
[I 2024-04-16 01:12:40,445] Trial 26 finished with value: 0.17492251249162544 and parameters: {'l1_ratio': 0.9167426588025347}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17780146768030844
Fold 2 IBS: 0.15502092537573706
Fold 3 IBS: 0.1719189655031944
Fold 4 IBS: 0.16863076980848457
Fold 5 IBS: 0.20129725442279459
[I 2024-04-16 01:12:41,203] Trial 27 finished with value: 0.17493387655810383 and parameters: {'l1_ratio': 0.7631358125417971}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17772627016139156
Fold 2 IBS: 0.15501370799571088
Fold 3 IBS: 0.1719524103147191
Fold 4 IBS: 0.16867187806155043
Fold 5 IBS: 0.2013147063337741
[I 2024-04-16 01:12:42,148] Trial 28 finished with value: 0.1749357945734292 and parameters: {'l1_ratio': 0.6541474849953819}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.1776472042148202
Fold 2 IBS: 0.1550011501838706
Fold 3 IBS: 0.17197842954205103
Fold 4 IBS: 0.16873465294878273
Fold 5 IBS: 0.2013016592968364
[I 2024-04-16 01:12:43,070] Trial 29 finished with value: 0.17493261923727219 and parameters: {'l1_ratio': 0.5344391410951219}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17741002430484853
Fold 2 IBS: 0.15497179923616977
Fold 3 IBS: 0.1720686231180329
Fold 4 IBS: 0.1688920647970403
Fold 5 IBS: 0.20130796489626718
[I 2024-04-16 01:12:44,060] Trial 30 finished with value: 0.1749300952704717 and parameters: {'l1_ratio': 0.29707347992095656}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17782347225941017
Fold 2 IBS: 0.15502529935178913
Fold 3 IBS: 0.17188042680395108
Fold 4 IBS: 0.1685847446676789
Fold 5 IBS: 0.20126089584963122
[I 2024-04-16 01:12:44,878] Trial 31 finished with value: 0.17491496778649213 and parameters: {'l1_ratio': 0.8639496175523173}. Best is trial 17 with value: 0.17491286688139054.
Fold 1 IBS: 0.17781845035090396
Fold 2 IBS: 0.15502233746874625
Fold 3 IBS: 0.17187861253071676
Fold 4 IBS: 0.1685963596812991
Fold 5 IBS: 0.20124647183001368
[I 2024-04-16 01:12:45,681] Trial 32 finished with value: 0.17491244637233597 and parameters: {'l1_ratio': 0.8361163936206244}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17789557267697903
Fold 2 IBS: 0.15503377141808225
Fold 3 IBS: 0.17188549221957392
Fold 4 IBS: 0.16856557761802565
Fold 5 IBS: 0.20130081098390698
[I 2024-04-16 01:12:46,417] Trial 33 finished with value: 0.17493624498331356 and parameters: {'l1_ratio': 0.9513468415258088}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17779993677003517
Fold 2 IBS: 0.15502017311469643
Fold 3 IBS: 0.17191850601980158
Fold 4 IBS: 0.16863390589431823
Fold 5 IBS: 0.20129371973564292
[I 2024-04-16 01:12:47,109] Trial 34 finished with value: 0.17493324830689888 and parameters: {'l1_ratio': 0.7571036956420296}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17782904706248176
Fold 2 IBS: 0.15502816866015698
Fold 3 IBS: 0.17188215025298498
Fold 4 IBS: 0.16857698012419314
Fold 5 IBS: 0.20127453548992594
[I 2024-04-16 01:12:48,056] Trial 35 finished with value: 0.17491817631794854 and parameters: {'l1_ratio': 0.8919797788413555}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17766271482499438
Fold 2 IBS: 0.15501398192713592
Fold 3 IBS: 0.1719438486587319
Fold 4 IBS: 0.1687007669178328
Fold 5 IBS: 0.20125133221216923
[I 2024-04-16 01:12:49,097] Trial 36 finished with value: 0.17491452890817283 and parameters: {'l1_ratio': 0.5767628082180243}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17773086856746875
Fold 2 IBS: 0.15501604595313687
Fold 3 IBS: 0.17195385718288442
Fold 4 IBS: 0.1686621937188832
Fold 5 IBS: 0.2013257496829126
[I 2024-04-16 01:12:50,184] Trial 37 finished with value: 0.17493774302105716 and parameters: {'l1_ratio': 0.6697205263544034}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17713428816986673
Fold 2 IBS: 0.15539984377143437
Fold 3 IBS: 0.1722068777103421
Fold 4 IBS: 0.1690940063746691
Fold 5 IBS: 0.20135369447260396
[I 2024-04-16 01:12:51,450] Trial 38 finished with value: 0.17503774209978323 and parameters: {'l1_ratio': 0.0788162861613429}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17757989460149678
Fold 2 IBS: 0.15499154387727204
Fold 3 IBS: 0.17200344613972454
Fold 4 IBS: 0.16878455105149112
Fold 5 IBS: 0.20129798689224732
[I 2024-04-16 01:12:52,767] Trial 39 finished with value: 0.17493148451244636 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1779042762735685
Fold 2 IBS: 0.15504259566995648
Fold 3 IBS: 0.17188826280370753
Fold 4 IBS: 0.16854865637031768
Fold 5 IBS: 0.20132002469493954
[I 2024-04-16 01:12:54,078] Trial 40 finished with value: 0.17494076316249796 and parameters: {'l1_ratio': 0.999804740263537}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778171129228034
Fold 2 IBS: 0.15503330182609495
Fold 3 IBS: 0.17187819437398036
Fold 4 IBS: 0.16859904493015415
Fold 5 IBS: 0.20124313966328114
[I 2024-04-16 01:12:55,190] Trial 41 finished with value: 0.1749141587432628 and parameters: {'l1_ratio': 0.829931318390943}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17790384207007168
Fold 2 IBS: 0.15503269728509447
Fold 3 IBS: 0.1718848537683711
Fold 4 IBS: 0.16857000719975382
Fold 5 IBS: 0.20129582997772022
[I 2024-04-16 01:12:56,446] Trial 42 finished with value: 0.17493744606020226 and parameters: {'l1_ratio': 0.9394547098794599}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17774632193440182
Fold 2 IBS: 0.15501627594205192
Fold 3 IBS: 0.1719161164862501
Fold 4 IBS: 0.16863004550219338
Fold 5 IBS: 0.20127513102805883
[I 2024-04-16 01:12:58,069] Trial 43 finished with value: 0.17491677817859122 and parameters: {'l1_ratio': 0.7270786045171711}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17782461390897125
Fold 2 IBS: 0.15502588623292218
Fold 3 IBS: 0.17188078030189224
Fold 4 IBS: 0.16858249138682443
Fold 5 IBS: 0.2012636951859651
[I 2024-04-16 01:12:59,364] Trial 44 finished with value: 0.17491549340331505 and parameters: {'l1_ratio': 0.8695618779204835}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17780721714550407
Fold 2 IBS: 0.15502375458096382
Fold 3 IBS: 0.1719210080179628
Fold 4 IBS: 0.16861904415950324
Fold 5 IBS: 0.20131058584635286
[I 2024-04-16 01:13:00,822] Trial 45 finished with value: 0.17493632195005737 and parameters: {'l1_ratio': 0.7865549663861001}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1777423471139575
Fold 2 IBS: 0.15501415197231339
Fold 3 IBS: 0.17191480759487568
Fold 4 IBS: 0.16863825691257328
Fold 5 IBS: 0.20126490740178302
[I 2024-04-16 01:13:02,849] Trial 46 finished with value: 0.17491489419910058 and parameters: {'l1_ratio': 0.71152923091366}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17782078753600167
Fold 2 IBS: 0.15502350091205425
Fold 3 IBS: 0.17187934290242424
Fold 4 IBS: 0.16859167713126696
Fold 5 IBS: 0.20125228660677233
[I 2024-04-16 01:13:04,676] Trial 47 finished with value: 0.17491351901770388 and parameters: {'l1_ratio': 0.8471219293069866}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17789758065479672
Fold 2 IBS: 0.1550347276616431
Fold 3 IBS: 0.17188605972009396
Fold 4 IBS: 0.16856166871266645
Fold 5 IBS: 0.20130525833669155
[I 2024-04-16 01:13:06,475] Trial 48 finished with value: 0.17493705901717835 and parameters: {'l1_ratio': 0.9621514818698591}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.177799998828041
Fold 2 IBS: 0.1550202035999657
Fold 3 IBS: 0.17191852465124702
Fold 4 IBS: 0.16863377865649004
Fold 5 IBS: 0.20129386429313556
[I 2024-04-16 01:13:07,837] Trial 49 finished with value: 0.17493327400577588 and parameters: {'l1_ratio': 0.7573466060641182}. Best is trial 32 with value: 0.17491244637233597.

Fold 1 IBS: 0.1777363161349135
Fold 2 IBS: 0.15502350795079944
Fold 3 IBS: 0.17191281828569827
Fold 4 IBS: 0.1686507917871518
Fold 5 IBS: 0.2012493140163311
[I 2024-04-16 01:13:08,939] Trial 50 finished with value: 0.17491454963497882 and parameters: {'l1_ratio': 0.6890155968874181}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17781901340404105
Fold 2 IBS: 0.15502262848620885
Fold 3 IBS: 0.17187878852776323
Fold 4 IBS: 0.16859523044538952
Fold 5 IBS: 0.20124787333406283
[I 2024-04-16 01:13:10,918] Trial 51 finished with value: 0.17491270683949306 and parameters: {'l1_ratio': 0.8387446189209664}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17781491267112218
Fold 2 IBS: 0.1550322398267501
Fold 3 IBS: 0.1719233029529743
Fold 4 IBS: 0.16860347162500414
Fold 5 IBS: 0.20123764810107314
[I 2024-04-16 01:13:12,250] Trial 52 finished with value: 0.17492231503538475 and parameters: {'l1_ratio': 0.8199294640662467}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17783430974454534
Fold 2 IBS: 0.1550308852773765
Fold 3 IBS: 0.17188377432901594
Fold 4 IBS: 0.1685774952647504
Fold 5 IBS: 0.20128734317911068
[I 2024-04-16 01:13:13,834] Trial 53 finished with value: 0.17492276155895975 and parameters: {'l1_ratio': 0.9199570578641031}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17782826174822403
Fold 2 IBS: 0.15502776393513906
Fold 3 IBS: 0.17188190769665831
Fold 4 IBS: 0.16857852775514648
Fold 5 IBS: 0.2012726186206224
[I 2024-04-16 01:13:15,213] Trial 54 finished with value: 0.17491781595115805 and parameters: {'l1_ratio': 0.8879343236625807}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778102097962621
Fold 2 IBS: 0.15502522967349822
Fold 3 IBS: 0.17192190132100135
Fold 4 IBS: 0.16861297156851487
Fold 5 IBS: 0.2013174933374243
[I 2024-04-16 01:13:19,140] Trial 55 finished with value: 0.17493756113934017 and parameters: {'l1_ratio': 0.7992463261813852}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17781891830617505
Fold 2 IBS: 0.15502257932750815
Fold 3 IBS: 0.17187875880432615
Fold 4 IBS: 0.1685954211179873
Fold 5 IBS: 0.20124763667967271
[I 2024-04-16 01:13:20,631] Trial 56 finished with value: 0.17491266284713386 and parameters: {'l1_ratio': 0.8382996993489938}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17780812068611435
Fold 2 IBS: 0.15501883361870583
Fold 3 IBS: 0.1719176864512447
Fold 4 IBS: 0.16863950907370343
Fold 5 IBS: 0.20128735507086723
[I 2024-04-16 01:13:21,952] Trial 57 finished with value: 0.1749343009801271 and parameters: {'l1_ratio': 0.7465564848840303}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17780851937279712
Fold 2 IBS: 0.15502439625082995
Fold 3 IBS: 0.1719213968637924
Fold 4 IBS: 0.16861639909226428
Fold 5 IBS: 0.20131359423002948
[I 2024-04-16 01:13:23,123] Trial 58 finished with value: 0.17493686116194263 and parameters: {'l1_ratio': 0.7920339113366599}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17748542092026706
Fold 2 IBS: 0.1549861639055921
Fold 3 IBS: 0.17202135572282723
Fold 4 IBS: 0.16882360479693698
Fold 5 IBS: 0.20134626851774629
[I 2024-04-16 01:13:24,106] Trial 59 finished with value: 0.17493256277267394 and parameters: {'l1_ratio': 0.3635438827822911}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17773913946464
Fold 2 IBS: 0.15501248614937035
Fold 3 IBS: 0.17191374972882606
Fold 4 IBS: 0.16864491229495485
Fold 5 IBS: 0.20125662612291645
[I 2024-04-16 01:13:25,857] Trial 60 finished with value: 0.17491338275214155 and parameters: {'l1_ratio': 0.6993985322826789}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17781917966722283
Fold 2 IBS: 0.15502271443883592
Fold 3 IBS: 0.17187884049251437
Fold 4 IBS: 0.16859489713577347
Fold 5 IBS: 0.2012482870320379
[I 2024-04-16 01:13:26,803] Trial 61 finished with value: 0.1749127837532769 and parameters: {'l1_ratio': 0.8395234889241093}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778218586381663
Fold 2 IBS: 0.15502405537115307
Fold 3 IBS: 0.17187967788695052
Fold 4 IBS: 0.1685895354032137
Fold 5 IBS: 0.20125494584331768
[I 2024-04-16 01:13:27,681] Trial 62 finished with value: 0.17491401462856024 and parameters: {'l1_ratio': 0.8522513528800142}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778319475352251
Fold 2 IBS: 0.1550296649531158
Fold 3 IBS: 0.17188304564346119
Fold 4 IBS: 0.16858256253801934
Fold 5 IBS: 0.20128160246236093
[I 2024-04-16 01:13:28,731] Trial 63 finished with value: 0.17492176462643644 and parameters: {'l1_ratio': 0.9072088779049889}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17772430079592716
Fold 2 IBS: 0.15501270802022293
Fold 3 IBS: 0.17195178976060146
Fold 4 IBS: 0.1686760425060326
Fold 5 IBS: 0.2013099598410091
[I 2024-04-16 01:13:29,893] Trial 64 finished with value: 0.17493496018475865 and parameters: {'l1_ratio': 0.6476674987803593}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778166737630686
Fold 2 IBS: 0.15503308978755787
Fold 3 IBS: 0.17187805703416095
Fold 4 IBS: 0.16859992757228415
Fold 5 IBS: 0.20124204453826577
[I 2024-04-16 01:13:31,011] Trial 65 finished with value: 0.17491395853906747 and parameters: {'l1_ratio': 0.8279179129882649}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17780333939214085
Fold 2 IBS: 0.15502184571734312
Fold 3 IBS: 0.1719195268888119
Fold 4 IBS: 0.16862693297979334
Fold 5 IBS: 0.2013016032368378
[I 2024-04-16 01:13:32,434] Trial 66 finished with value: 0.1749346496429854 and parameters: {'l1_ratio': 0.7706250835527501}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778961913960369
Fold 2 IBS: 0.1550340659914622
Fold 3 IBS: 0.171885667127667
Fold 4 IBS: 0.16856436841975683
Fold 5 IBS: 0.20130218228958807
[I 2024-04-16 01:13:34,161] Trial 67 finished with value: 0.17493649504490222 and parameters: {'l1_ratio': 0.9546530799943637}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778236799144349
Fold 2 IBS: 0.1550254060720742
Fold 3 IBS: 0.1718804910332931
Fold 4 IBS: 0.16858433459759836
Fold 5 IBS: 0.20126140525703934
[I 2024-04-16 01:13:35,934] Trial 68 finished with value: 0.174915063374888 and parameters: {'l1_ratio': 0.864965662321457}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778359200141998
Fold 2 IBS: 0.1550317180175394
Fold 3 IBS: 0.17188427078119295
Fold 4 IBS: 0.1685740486669881
Fold 5 IBS: 0.20129124894457837
[I 2024-04-16 01:13:37,719] Trial 69 finished with value: 0.17492344128489973 and parameters: {'l1_ratio': 0.9288314438927333}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778259307208651
Fold 2 IBS: 0.15502656361977876
Fold 3 IBS: 0.17188118740708172
Fold 4 IBS: 0.16857989605296655
Fold 5 IBS: 0.20126692010401445
[I 2024-04-16 01:13:39,880] Trial 70 finished with value: 0.17491609958094131 and parameters: {'l1_ratio': 0.8761157749814029}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17781746237587798
Fold 2 IBS: 0.15503347057605843
Fold 3 IBS: 0.17187830364778892
Fold 4 IBS: 0.16859834290608244
Fold 5 IBS: 0.20124401074538942
[I 2024-04-16 01:13:41,594] Trial 71 finished with value: 0.17491431805023944 and parameters: {'l1_ratio': 0.8315396111701744}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17781232248850942
Fold 2 IBS: 0.1550309907279051
Fold 3 IBS: 0.17192253130967114
Fold 4 IBS: 0.16860869740020384
Fold 5 IBS: 0.2013223568292641
[I 2024-04-16 01:13:43,337] Trial 72 finished with value: 0.17493937975111074 and parameters: {'l1_ratio': 0.8084234258087681}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17774752214940456
Fold 2 IBS: 0.15501743716870592
Fold 3 IBS: 0.17191683010675218
Fold 4 IBS: 0.1686453796220385
Fold 5 IBS: 0.20128069263017268
[I 2024-04-16 01:13:45,008] Trial 73 finished with value: 0.17492157233541478 and parameters: {'l1_ratio': 0.7358169044017294}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17782960466950146
Fold 2 IBS: 0.15502845613681426
Fold 3 IBS: 0.17188232244587337
Fold 4 IBS: 0.16857588207475932

Fold 5 IBS: 0.20127589565325266
[I 2024-04-16 01:13:47,063] Trial 74 finished with value: 0.17491843219604022 and parameters: {'l1_ratio': 0.8948721301308191}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17790106930857522
Fold 2 IBS: 0.1550411009903398
Fold 3 IBS: 0.17188736052271278
Fold 4 IBS: 0.16855487673687006
Fold 5 IBS: 0.20131296424349196
[I 2024-04-16 01:13:49,158] Trial 75 finished with value: 0.17493947436039797 and parameters: {'l1_ratio': 0.9814493707942191}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.1778056319312043
Fold 2 IBS: 0.15502297389888584
Fold 3 IBS: 0.17192053439630495
Fold 4 IBS: 0.16862226951632467
Fold 5 IBS: 0.20130691818719307
[I 2024-04-16 01:13:51,407] Trial 76 finished with value: 0.17493566558598256 and parameters: {'l1_ratio': 0.7799741126138751}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17729275937943842
Fold 2 IBS: 0.15508949346144105
Fold 3 IBS: 0.17211152226867815
Fold 4 IBS: 0.16895850589559958
Fold 5 IBS: 0.20136035871665614
[I 2024-04-16 01:13:53,593] Trial 77 finished with value: 0.17496252794436268 and parameters: {'l1_ratio': 0.19328346899350535}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17760757382886463
Fold 2 IBS: 0.15499729448193483
Fold 3 IBS: 0.1719759608381273
Fold 4 IBS: 0.16872239659342592
Fold 5 IBS: 0.20128293554095258
[I 2024-04-16 01:13:54,934] Trial 78 finished with value: 0.17491723225666106 and parameters: {'l1_ratio': 0.5160283831230956}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17766828790492403
Fold 2 IBS: 0.15500364303806616
Fold 3 IBS: 0.17194578117401413
Fold 4 IBS: 0.1686887561546509
Fold 5 IBS: 0.20126629844734334
[I 2024-04-16 01:13:56,364] Trial 79 finished with value: 0.1749145533437997 and parameters: {'l1_ratio': 0.5933865341035967}. Best is trial 32 with value: 0.17491244637233597.
Fold 1 IBS: 0.17781806694594943
Fold 2 IBS: 0.1550221393589588
Fold 3 IBS: 0.1718784926719454
Fold 4 IBS: 0.1685971290443546
Fold 5 IBS: 0.20124551704100216
[I 2024-04-16 01:13:57,472] Trial 80 finished with value: 0.17491226901244206 and parameters: {'l1_ratio': 0.8343350205981689}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17782012866991775
Fold 2 IBS: 0.15502316002043415
Fold 3 IBS: 0.17187913705355512
Fold 4 IBS: 0.16859299588764445
Fold 5 IBS: 0.20125064704225382
[I 2024-04-16 01:13:58,757] Trial 81 finished with value: 0.17491321373476104 and parameters: {'l1_ratio': 0.8439936614820248}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.1778109056108407
Fold 2 IBS: 0.15502557288126437
Fold 3 IBS: 0.17192210886670575
Fold 4 IBS: 0.16861156270279468
Fold 5 IBS: 0.2013190963043736
[I 2024-04-16 01:14:00,018] Trial 82 finished with value: 0.17493784927319583 and parameters: {'l1_ratio': 0.8022485712502226}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17782544655457788
Fold 2 IBS: 0.1550263145004929
Fold 3 IBS: 0.17188103773992544
Fold 4 IBS: 0.16858084985134608
Fold 5 IBS: 0.20126573485107693
[I 2024-04-16 01:14:01,941] Trial 83 finished with value: 0.17491587669948383 and parameters: {'l1_ratio': 0.8736959019789658}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.1778327362717056
Fold 2 IBS: 0.1550300722469987
Fold 3 IBS: 0.17188328900387928
Fold 4 IBS: 0.16858086909671746
Fold 5 IBS: 0.20128352074626524
[I 2024-04-16 01:14:04,543] Trial 84 finished with value: 0.17492209747311324 and parameters: {'l1_ratio': 0.9114303278498148}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.1778196238802127
Fold 2 IBS: 0.15502294412368053
Fold 3 IBS: 0.17187897931756135
Fold 4 IBS: 0.16859400693190624
Fold 5 IBS: 0.2012493919923364
[I 2024-04-16 01:14:06,478] Trial 85 finished with value: 0.17491298924913945 and parameters: {'l1_ratio': 0.8416106963711606}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17780360228235564
Fold 2 IBS: 0.15502197503736734
Fold 3 IBS: 0.17191960570402667
Fold 4 IBS: 0.16862640798165654
Fold 5 IBS: 0.20130221336210302
[I 2024-04-16 01:14:08,038] Trial 86 finished with value: 0.17493476087350182 and parameters: {'l1_ratio': 0.7716872280657733}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.1778152388291836
Fold 2 IBS: 0.1550323971997125
Fold 3 IBS: 0.1718776081679326
Fold 4 IBS: 0.16860281471013414
Fold 5 IBS: 0.2012384629154565
[I 2024-04-16 01:14:09,180] Trial 87 finished with value: 0.17491330436448388 and parameters: {'l1_ratio': 0.8213986987788378}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17774726503141974
Fold 2 IBS: 0.1550167806295968
Fold 3 IBS: 0.17191642680777958
Fold 4 IBS: 0.16863131475735668
Fold 5 IBS: 0.2012775505915425
[I 2024-04-16 01:14:10,185] Trial 88 finished with value: 0.17491786756353905 and parameters: {'l1_ratio': 0.7308553421911089}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17790398409137975
Fold 2 IBS: 0.15503276695690288
Fold 3 IBS: 0.17188489521251024
Fold 4 IBS: 0.16856972013648794
Fold 5 IBS: 0.20129633588047177
[I 2024-04-16 01:14:11,635] Trial 89 finished with value: 0.17493754045555052 and parameters: {'l1_ratio': 0.9402183860405299}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.1778205162794825
Fold 2 IBS: 0.1550233605503473
Fold 3 IBS: 0.17187925815850633
Fold 4 IBS: 0.16859221994432722
Fold 5 IBS: 0.20125161270677347
[I 2024-04-16 01:14:12,758] Trial 90 finished with value: 0.17491339352788737 and parameters: {'l1_ratio': 0.8458315420458872}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.177828153960517
Fold 2 IBS: 0.15502770839837307
Fold 3 IBS: 0.17188187440058741
Fold 4 IBS: 0.168578740281572
Fold 5 IBS: 0.2012723554067903
[I 2024-04-16 01:14:13,992] Trial 91 finished with value: 0.17491776648956797 and parameters: {'l1_ratio': 0.887381607388998}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17782274923698851
Fold 2 IBS: 0.15502451665515743
Fold 3 IBS: 0.1718799573958391
Fold 4 IBS: 0.16858775661584147
Fold 5 IBS: 0.20125715479395898
[I 2024-04-16 01:14:15,209] Trial 92 finished with value: 0.1749144269395571 and parameters: {'l1_ratio': 0.8565582765201664}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.1778118157851776
Fold 2 IBS: 0.15503074651524806
Fold 3 IBS: 0.17192238026339335
Fold 4 IBS: 0.1686097215424373
Fold 5 IBS: 0.2013211913513883
[I 2024-04-16 01:14:16,322] Trial 93 finished with value: 0.17493917109152893 and parameters: {'l1_ratio': 0.8062056401961809}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17780876548721342
Fold 2 IBS: 0.15501916003088712
Fold 3 IBS: 0.17191788633222865
Fold 4 IBS: 0.1686381414220267
Fold 5 IBS: 0.20128890836924876
[I 2024-04-16 01:14:17,383] Trial 94 finished with value: 0.17493457232832094 and parameters: {'l1_ratio': 0.7491041549912586}. Best is trial 80 with value: 0.17491226901244206.
Fold 1 IBS: 0.17781769286967514
Fold 2 IBS: 0.1550219461127698
Fold 3 IBS: 0.1718783757173837
Fold 4 IBS: 0.1685978800178822
Fold 5 IBS: 0.20124458513134688
[I 2024-04-16 01:14:18,493] Trial 95 finished with value: 0.17491209596981155 and parameters: {'l1_ratio': 0.8326034206112033}. Best is trial 95 with value: 0.17491209596981155.
Fold 1 IBS: 0.1777304435572434
Fold 2 IBS: 0.15501582968948555
Fold 3 IBS: 0.1719537235786392
Fold 4 IBS: 0.1686630864932173
Fold 5 IBS: 0.20132473135780965
[I 2024-04-16 01:14:19,517] Trial 96 finished with value: 0.174937562935279 and parameters: {'l1_ratio': 0.6682544752145108}. Best is trial 95 with value: 0.17491209596981155.
Fold 1 IBS: 0.17780802047853334
Fold 2 IBS: 0.1550241503842992
Fold 3 IBS: 0.17192124791779595
Fold 4 IBS: 0.16861741196018112
Fold 5 IBS: 0.20131244217549965
[I 2024-04-16 01:14:20,678] Trial 97 finished with value: 0.17493665458326185 and parameters: {'l1_ratio': 0.7899270257887823}. Best is trial 95 with value: 0.17491209596981155.
Fold 1 IBS: 0.17783098549774803
Fold 2 IBS: 0.1550291684002698
Fold 3 IBS: 0.17188274873874715
Fold 4 IBS: 0.16857316590261215
Fold 5 IBS: 0.2012792606913694
[I 2024-04-16 01:14:21,863] Trial 98 finished with value: 0.1749190658461493 and parameters: {'l1_ratio': 0.9021067524191018}. Best is trial 95 with value: 0.17491209596981155.

Fold 1 IBS: 0.17781752431167402
Fold 2 IBS: 0.15503349816380735
Fold 3 IBS: 0.1718783230139951
Fold 4 IBS: 0.16859821851160697
Fold 5 IBS: 0.20124416510113766
[I 2024-04-16 01:14:23,686] Trial 99 finished with value: 0.1749143458204442 and parameters: {'l1_ratio': 0.8318252313874105}. Best is trial 95 with value: 0.17491209596981155.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.17491209596981155], datetime_start=datetime.datetime(2024, 4, 16, 1, 14, 17, 395691), datetime_complete=datetime.datetime(2024, 4, 16, 1, 14, 18, 493279), params={'l1_ratio': 0.8326034206112033}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=95, value=None)


* Best Score for IBS:
 0.17491209596981155

In [41]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [42]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.744
train_ibs:  0.175

#### Test

In [43]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [44]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.06342138075355325)

test_cindex : 0.56

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.8326034206112033)

test_ibs:  0.262

In [45]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [46]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:14:24,443] A new study created in memory with name: no-name-14a58355-cc6b-4d83-b696-f10415170781

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:14:37,578] Trial 0 finished with value: 0.7575203363732566 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:14:48,821] Trial 1 finished with value: 0.750478431579118 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:14:59,585] Trial 2 finished with value: 0.7520712510356254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:15:02,915] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:15:09,804] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:15:26,933] Trial 5 finished with value: 0.7462602486577217 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7575203363732566.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:15:43,771] Trial 6 finished with value: 0.7576976783760393 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:15:50,025] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 01:16:13,977] Trial 8 finished with value: 0.5380281690140845 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:16:29,358] Trial 9 finished with value: 0.748452073539184 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:16:31,397] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.40740851493126695, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:16:55,665] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.11379276107227315, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:17:22,485] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 6 with value: 0.7576976783760393.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:17:30,829] Trial 13 finished with value: 0.7581182539062076 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 13 with value: 0.7581182539062076.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:17:35,045] Trial 14 finished with value: 0.7907144637948861 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0992244164616675, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:17:38,160] Trial 15 finished with value: 0.7816150812624114 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.8147833133306369, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:17:39,108] Trial 16 finished with value: 0.765813594477808 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.8484814588885312, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08082385841318356, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:17:43,112] Trial 17 finished with value: 0.7851258260885514 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16544550098450153, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:17:47,142] Trial 18 finished with value: 0.7834440402483949 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13294582901895255, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:17:54,666] Trial 19 finished with value: 0.7742809868075984 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9945705745432233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09964492104707659, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:17:58,616] Trial 20 finished with value: 0.7628622503029641 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.8673418291441284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37827446502466894, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:18:05,404] Trial 21 finished with value: 0.7872501961326841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.9624638447657676, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8459821428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.8051643192488263
[I 2024-04-16 01:18:07,605] Trial 22 finished with value: 0.7873570802451841 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.9336744347879812, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19282610776605333, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7488262910798122
[I 2024-04-16 01:18:09,317] Trial 23 finished with value: 0.7541962121280221 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 18, 'oob_score': True, 'max_samples': 0.6843026151576985, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2504370920378234, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:18:13,140] Trial 24 finished with value: 0.7858778057568998 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 50, 'oob_score': True, 'max_samples': 0.8085053499703132, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17035312846001988, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:18:18,480] Trial 25 finished with value: 0.7899316539935477 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.9171920870810285, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07664126778540013, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:18:23,820] Trial 26 finished with value: 0.7817663440763265 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.8983378428295576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06306617081281016, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:18:32,067] Trial 27 finished with value: 0.7856141531151757 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.7989579262543244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09596584472346859, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:18:40,581] Trial 28 finished with value: 0.7853982513847043 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.5360953547457009, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014347840876196644, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:18:42,071] Trial 29 finished with value: 0.7695772354631409 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.6977978899499365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2196223213316708, 'warm_start': True}. Best is trial 14 with value: 0.7907144637948861.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:18:44,975] Trial 30 finished with value: 0.7981448890436417 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 82, 'oob_score': True, 'max_samples': 0.7311645169232817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.059569167808063095, 'warm_start': True}. Best is trial 30 with value: 0.7981448890436417.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7658227848101266
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:18:47,494] Trial 31 finished with value: 0.7982641653072841 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.745146001885883, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05174429879930956, 'warm_start': True}. Best is trial 31 with value: 0.7982641653072841.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7742616033755274
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:18:50,222] Trial 32 finished with value: 0.8032544311992128 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.7397628776532771, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04641084093066284, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:18:53,117] Trial 33 finished with value: 0.7999277380363321 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.7321956680996766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0042513284435347215, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 01:18:56,404] Trial 34 finished with value: 0.7980620370159766 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 74, 'oob_score': True, 'max_samples': 0.7190350277691129, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002617826444773601, 'warm_start': True}. Best is trial 32 with value: 0.8032544311992128.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:18:59,210] Trial 35 finished with value: 0.8195885025512174 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.6491391650041388, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04473837361201603, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:19:03,249] Trial 36 finished with value: 0.8149421898615685 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6500614805101094, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.042163225365865975, 'warm_start': True}. Best is trial 35 with value: 0.8195885025512174.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:19:07,357] Trial 37 finished with value: 0.8201548198575692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.6316988824284715, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03372830367211485, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:19:11,759] Trial 38 finished with value: 0.7864200685622795 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6475925530300135, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1261541633669147, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8169014084507042
[I 2024-04-16 01:19:16,866] Trial 39 finished with value: 0.7994601394099836 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.5500795764120797, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0407216828679674, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:19:20,344] Trial 40 finished with value: 0.8144744547521597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.5974594004293988, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03731085344043298, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:19:25,600] Trial 41 finished with value: 0.8146670383091891 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.5688957234666421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.038323603584419504, 'warm_start': True}. Best is trial 37 with value: 0.8201548198575692.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:19:31,927] Trial 42 finished with value: 0.8217769675659046 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.565436601526051, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03253349071458341, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:19:36,528] Trial 43 finished with value: 0.8194179790264864 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 314, 'oob_score': False, 'max_samples': 0.5414105158165579, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02824952898790397, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:19:41,405] Trial 44 finished with value: 0.7844759249669818 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.4812619709263958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0734121445676241, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:19:46,725] Trial 45 finished with value: 0.7812420451089397 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.4132359110524421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10574093555624242, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:20:06,794] Trial 46 finished with value: 0.742796454430003 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 277, 'oob_score': False, 'max_samples': 0.6435530257070258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02588599089196765, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:20:14,767] Trial 47 finished with value: 0.8020413535841735 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.513428105668999, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005073560345181239, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:20:33,592] Trial 48 finished with value: 0.7605416340753064 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.4250487747986099, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07826456635516901, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:20:40,224] Trial 49 finished with value: 0.7646180284055469 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.3288612699820465, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11977607788857622, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 01:20:46,109] Trial 50 finished with value: 0.7516085439508142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.6056621314066971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27891660351802283, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:20:52,490] Trial 51 finished with value: 0.8156329206993581 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.5653247525904954, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024675273648228607, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:20:58,037] Trial 52 finished with value: 0.8105679483498613 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.668807800129283, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023886857070088842, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:21:08,057] Trial 53 finished with value: 0.8092844755529726 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.5049892673780266, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0302062450326431, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:21:12,312] Trial 54 finished with value: 0.7837218500992189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 223, 'oob_score': False, 'max_samples': 0.5694355594036941, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08503386755881623, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:21:18,369] Trial 55 finished with value: 0.8023260161047514 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.6230580876154783, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06106714571926695, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:21:33,098] Trial 56 finished with value: 0.7505163979885541 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.37386377532060755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020276597591653404, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 01:21:37,033] Trial 57 finished with value: 0.7370660000414045 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 265, 'oob_score': False, 'max_samples': 0.673626054002652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.32552397591019333, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:21:41,038] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.5859997242165991, 'max_features': None, 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:21:43,914] Trial 59 finished with value: 0.7738001567018483 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.4578032212133656, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14288340865089383, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:21:58,907] Trial 60 finished with value: 0.7576418826254305 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.5248616932098589, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09178626486905285, 'warm_start': False}. Best is trial 42 with value: 0.8217769675659046.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:22:03,423] Trial 61 finished with value: 0.8121405300073643 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.5673407402421513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04324260858798204, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:22:07,862] Trial 62 finished with value: 0.8048963624250977 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.6136771186690915, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.061141393518585746, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:22:10,836] Trial 63 finished with value: 0.8129059673027221 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.5632723911430406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03896879562886681, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:22:15,519] Trial 64 finished with value: 0.8200972064136438 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.4849644523201697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015459623887936643, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:22:18,998] Trial 65 finished with value: 0.8200556403698938 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.4915234805630325, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01325985667696578, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:22:23,984] Trial 66 finished with value: 0.7991290530701981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.44421584072665865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01688809895377827, 'warm_start': True}. Best is trial 42 with value: 0.8217769675659046.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.9014084507042254
[I 2024-04-16 01:22:27,604] Trial 67 finished with value: 0.8455736642377335 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 01:22:34,259] Trial 68 finished with value: 0.8406053556611222 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'max_samples': 0.49738412507640734, 'max_features': None, 'min_weight_fraction_leaf': 0.002433553898016293, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:22:40,767] Trial 69 finished with value: 0.8316567836473476 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.38288786338976266, 'max_features': None, 'min_weight_fraction_leaf': 0.010924103557748996, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:22:46,406] Trial 70 finished with value: 0.8325253087831349 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.3768797583243322, 'max_features': None, 'min_weight_fraction_leaf': 0.007358190561024822, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:22:51,374] Trial 71 finished with value: 0.8074401022098655 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.2977376592001145, 'max_features': None, 'min_weight_fraction_leaf': 0.007777034521166985, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:23:01,763] Trial 72 finished with value: 0.8207621073356813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3758248033560092, 'max_features': None, 'min_weight_fraction_leaf': 0.0021403509786410697, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:23:12,368] Trial 73 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.37703659520841803, 'max_features': None, 'min_weight_fraction_leaf': 0.0030355880739053242, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:23:23,389] Trial 74 finished with value: 0.8216059891922214 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.37759120849945615, 'max_features': None, 'min_weight_fraction_leaf': 0.005738060589732854, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:23:34,866] Trial 75 finished with value: 0.8064988630989438 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.3512499599110515, 'max_features': None, 'min_weight_fraction_leaf': 0.0016091095350437782, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:23:41,958] Trial 76 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.2200825864677213, 'max_features': None, 'min_weight_fraction_leaf': 0.3808353622830714, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:23:49,369] Trial 77 finished with value: 0.7898601663797173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.38697496089808264, 'max_features': None, 'min_weight_fraction_leaf': 0.0678874889911297, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:23:56,016] Trial 78 finished with value: 0.7983796631750157 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.2971389951907717, 'max_features': None, 'min_weight_fraction_leaf': 0.0014283193772283813, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:24:01,449] Trial 79 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.3832306547359522, 'max_features': None, 'min_weight_fraction_leaf': 0.001325860823554314, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:24:29,219] Trial 80 finished with value: 0.7638486802036979 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.2259926589326255, 'max_features': None, 'min_weight_fraction_leaf': 0.051988057609908274, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:24:36,041] Trial 81 finished with value: 0.8206035395567974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.3902826764643792, 'max_features': None, 'min_weight_fraction_leaf': 0.01424010512203431, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:24:45,816] Trial 82 finished with value: 0.8037666314114749 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.35665467332899853, 'max_features': None, 'min_weight_fraction_leaf': 0.02723621966149422, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:24:51,421] Trial 83 finished with value: 0.7910748783864995 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.27364682713049737, 'max_features': None, 'min_weight_fraction_leaf': 0.003437924737021262, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 01:25:02,965] Trial 84 finished with value: 0.7981013668372744 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 482, 'oob_score': False, 'max_samples': 0.42217891643501637, 'max_features': None, 'min_weight_fraction_leaf': 0.05691895142137581, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:25:11,853] Trial 85 finished with value: 0.8142696016233687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.44215445453616553, 'max_features': None, 'min_weight_fraction_leaf': 0.015948474032128478, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:25:18,864] Trial 86 finished with value: 0.8039740360073753 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 467, 'oob_score': False, 'max_samples': 0.34536985759892425, 'max_features': None, 'min_weight_fraction_leaf': 0.03379453130696234, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:25:24,718] Trial 87 finished with value: 0.8009672435320422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3948765985014735, 'max_features': None, 'min_weight_fraction_leaf': 0.049452906101561514, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:25:30,659] Trial 88 finished with value: 0.7958162763557586 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.3168310392190445, 'max_features': None, 'min_weight_fraction_leaf': 0.011197201541028177, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:25:35,010] Trial 89 finished with value: 0.8188472945459484 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.46056239467229443, 'max_features': None, 'min_weight_fraction_leaf': 0.02927897429150622, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 01:25:38,673] Trial 90 finished with value: 0.8280743039205017 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.3677724129924504, 'max_features': None, 'min_weight_fraction_leaf': 0.0015288688784384722, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:25:42,038] Trial 91 finished with value: 0.8315449166262722 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.37527324355860175, 'max_features': None, 'min_weight_fraction_leaf': 0.00032873883511814225, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:25:48,021] Trial 92 finished with value: 0.8152302082764418 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.36969362389667315, 'max_features': None, 'min_weight_fraction_leaf': 0.020344390663164187, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:25:52,197] Trial 93 finished with value: 0.8013473051581448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.3234854377137636, 'max_features': None, 'min_weight_fraction_leaf': 0.034235535617443455, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:25:56,983] Trial 94 finished with value: 0.8317597304647398 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.40292152817878885, 'max_features': None, 'min_weight_fraction_leaf': 0.0013715257783006587, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.8309859154929577
[I 2024-04-16 01:26:01,643] Trial 95 finished with value: 0.8054182483946754 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.43651122516239244, 'max_features': None, 'min_weight_fraction_leaf': 0.0516435889873805, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:26:05,198] Trial 96 finished with value: 0.781897576085816 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.40560294670004454, 'max_features': None, 'min_weight_fraction_leaf': 0.0001044161694674754, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:26:08,412] Trial 97 finished with value: 0.8076329995928095 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.33588267636278435, 'max_features': None, 'min_weight_fraction_leaf': 0.019808016366776694, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:26:24,330] Trial 98 finished with value: 0.7563224015679627 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.4120109800767605, 'max_features': None, 'min_weight_fraction_leaf': 0.0696147483073608, 'warm_start': False}. Best is trial 67 with value: 0.8455736642377335.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8333333333333334

[I 2024-04-16 01:26:28,048] A new study created in memory with name: no-name-c2a5a656-e2e0-470e-9477-639e61584390

Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8403755868544601
[I 2024-04-16 01:26:28,026] Trial 99 finished with value: 0.81879604728486 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.4642145775222535, 'max_features': None, 'min_weight_fraction_leaf': 0.04423293101031651, 'warm_start': True}. Best is trial 67 with value: 0.8455736642377335.


* Best trial for C-index:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.8455736642377335], datetime_start=datetime.datetime(2024, 4, 16, 1, 22, 24, 10890), datetime_complete=datetime.datetime(2024, 4, 16, 1, 22, 27, 589496), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.48042970450395145, 'max_features': None, 'min_weight_fraction_leaf': 0.0025914663927405594, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=67, value=None)


* Best Score for C-index:
 0.8455736642377335

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16912942286746
Fold 2 IBS: 0.15736700168879125
Fold 3 IBS: 0.17596810644035646
Fold 4 IBS: 0.21476462245142444
Fold 5 IBS: 0.18140709105634753
[I 2024-04-16 01:26:40,170] Trial 0 finished with value: 0.17972724890087594 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.17972724890087594.
Fold 1 IBS: 0.1695457408702072
Fold 2 IBS: 0.15431589011481192
Fold 3 IBS: 0.17931251537071569
Fold 4 IBS: 0.19778743079510175
Fold 5 IBS: 0.1838708756319808
[I 2024-04-16 01:26:43,601] Trial 1 finished with value: 0.1769664905565635 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-16 01:26:45,559] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-16 01:26:54,860] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-16 01:27:00,758] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.18261661077179908
Fold 2 IBS: 0.14215438755582593
Fold 3 IBS: 0.19825307809201306
Fold 4 IBS: 0.1894541695729735
Fold 5 IBS: 0.17258301646825175
[I 2024-04-16 01:27:09,307] Trial 5 finished with value: 0.17701225249217267 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.1793072949109339
Fold 2 IBS: 0.17146943238736864
Fold 3 IBS: 0.1801865051168754
Fold 4 IBS: 0.2169078691801737
Fold 5 IBS: 0.1927889640697635
[I 2024-04-16 01:27:17,199] Trial 6 finished with value: 0.18813201313302302 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.20628331122669447
Fold 2 IBS: 0.20810768242984765
Fold 3 IBS: 0.196178000210441
Fold 4 IBS: 0.21720909429106852
Fold 5 IBS: 0.2120048382129915
[I 2024-04-16 01:27:30,638] Trial 7 finished with value: 0.2079565852742086 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-16 01:27:44,420] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17251108291109596
Fold 2 IBS: 0.16372104609445076
Fold 3 IBS: 0.1752499545194017
Fold 4 IBS: 0.19923941269775702
Fold 5 IBS: 0.1807428948937162
[I 2024-04-16 01:27:47,287] Trial 9 finished with value: 0.17829287822328432 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.2138914608019449
Fold 2 IBS: 0.22021134435777845
Fold 3 IBS: 0.20482550997958907
Fold 4 IBS: 0.22548051560881624
Fold 5 IBS: 0.21733795012904839
[I 2024-04-16 01:27:53,140] Trial 10 finished with value: 0.2163493561754354 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.1769664905565635.
Fold 1 IBS: 0.17089799911696577
Fold 2 IBS: 0.1343759168934981
Fold 3 IBS: 0.18019414575478068
Fold 4 IBS: 0.19691489378360008
Fold 5 IBS: 0.17134875048281803
[I 2024-04-16 01:27:53,843] Trial 11 finished with value: 0.17074634120633253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1938573372077058
Fold 2 IBS: 0.15264524705837576
Fold 3 IBS: 0.1835875292339129
Fold 4 IBS: 0.19186721611439267
Fold 5 IBS: 0.17242006747034438
[I 2024-04-16 01:27:54,832] Trial 12 finished with value: 0.17887547941694631 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.7748822387405266, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020197386275102834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1753396733634442
Fold 2 IBS: 0.14659590196214217
Fold 3 IBS: 0.18564941996432435
Fold 4 IBS: 0.19697957764971377
Fold 5 IBS: 0.1760898132139911
[I 2024-04-16 01:27:58,342] Trial 13 finished with value: 0.17613087723072313 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 110, 'oob_score': False, 'max_samples': 0.9282504676473301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18437150857335638
Fold 2 IBS: 0.13940627158607374
Fold 3 IBS: 0.19735408203235827
Fold 4 IBS: 0.19502160042084687
Fold 5 IBS: 0.17327657876201488
[I 2024-04-16 01:28:04,366] Trial 14 finished with value: 0.17788600827493004 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.9418551640023243, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1903120334095733
Fold 2 IBS: 0.13604392965192902
Fold 3 IBS: 0.20770281014511405
Fold 4 IBS: 0.21649791040859048
Fold 5 IBS: 0.17399213158709487
[I 2024-04-16 01:28:05,370] Trial 15 finished with value: 0.18490976304046036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 5, 'oob_score': False, 'max_samples': 0.9969315225031997, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10400906232299456}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.17234717281067394
Fold 2 IBS: 0.168695961879054
Fold 3 IBS: 0.17428134482390595
Fold 4 IBS: 0.20512326820357737
Fold 5 IBS: 0.1858777602458117
[I 2024-04-16 01:28:08,920] Trial 16 finished with value: 0.1812651015926046 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.8254434867518305, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27558800117237026}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1701072167867666
Fold 2 IBS: 0.15066297678714172
Fold 3 IBS: 0.18453320195882447
Fold 4 IBS: 0.19299945063741186
Fold 5 IBS: 0.17720564069954053
[I 2024-04-16 01:28:21,201] Trial 17 finished with value: 0.17510169737393705 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.7509985501856506, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0026257659295356476}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18294194940487038
Fold 2 IBS: 0.14058077366331193
Fold 3 IBS: 0.19786106053237812
Fold 4 IBS: 0.19006278490632897
Fold 5 IBS: 0.17207512016650234
[I 2024-04-16 01:28:37,212] Trial 18 finished with value: 0.17670433773467834 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16955416166590404
Fold 2 IBS: 0.15212211732759853
Fold 3 IBS: 0.18191729427832115
Fold 4 IBS: 0.1920689530206985
Fold 5 IBS: 0.1791048456801592
[I 2024-04-16 01:28:49,291] Trial 19 finished with value: 0.1749534743945363 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6173177066935658, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1243900714081905}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17714686876701324
Fold 2 IBS: 0.16932933496556507
Fold 3 IBS: 0.17717541750009574
Fold 4 IBS: 0.19713572873566637
Fold 5 IBS: 0.1888282875493155
[I 2024-04-16 01:29:00,098] Trial 20 finished with value: 0.18192312750353118 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.3628004877999946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13255231046532823}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16913535340838307
Fold 2 IBS: 0.15272782624748996
Fold 3 IBS: 0.18157422278730082
Fold 4 IBS: 0.19159866778115425
Fold 5 IBS: 0.18035473161483767
[I 2024-04-16 01:29:15,893] Trial 21 finished with value: 0.17507816036783316 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.6011378896362364, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04460079180106673}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17030810384993947
Fold 2 IBS: 0.15141739726332304
Fold 3 IBS: 0.18252438545010272
Fold 4 IBS: 0.19011356122343498
Fold 5 IBS: 0.178289463693237
[I 2024-04-16 01:29:32,715] Trial 22 finished with value: 0.17453058229600743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.6303687757401123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10192378722318633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17546673577503152
Fold 2 IBS: 0.15775731851311675
Fold 3 IBS: 0.1781524236691594
Fold 4 IBS: 0.18862200168076865
Fold 5 IBS: 0.1781929228483396
[I 2024-04-16 01:29:46,334] Trial 23 finished with value: 0.1756382804972832 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.47299192016675806, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11363003519604899}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17094376831357636
Fold 2 IBS: 0.1646895387119759
Fold 3 IBS: 0.1747842391429866
Fold 4 IBS: 0.19494361629603088
Fold 5 IBS: 0.1866353242437713
[I 2024-04-16 01:29:58,029] Trial 24 finished with value: 0.1783992973416682 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 20, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.6280222894166756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17647963073148}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16901499831887323
Fold 2 IBS: 0.1608317214516487
Fold 3 IBS: 0.1762379772561786
Fold 4 IBS: 0.19348054932052614
Fold 5 IBS: 0.18439435643852217
[I 2024-04-16 01:30:11,304] Trial 25 finished with value: 0.1767919205571498 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.4737896318177208, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09514387992502697}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16929634538840924
Fold 2 IBS: 0.15790827738905253
Fold 3 IBS: 0.17685741513951483
Fold 4 IBS: 0.1967559497411602
Fold 5 IBS: 0.185385205701487
[I 2024-04-16 01:30:21,744] Trial 26 finished with value: 0.17724063867192474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.8171469856554013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23317683759042168}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17086891563968248
Fold 2 IBS: 0.1631508903913892
Fold 3 IBS: 0.17528408462417908
Fold 4 IBS: 0.19656070086825392
Fold 5 IBS: 0.1871180876095544
[I 2024-04-16 01:30:35,376] Trial 27 finished with value: 0.1785965358266118 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.69231778632942, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05016618054550538}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21403025999388117
Fold 2 IBS: 0.22062977018591617
Fold 3 IBS: 0.20516689505844507
Fold 4 IBS: 0.22458172975885837
Fold 5 IBS: 0.21781943709735221
[I 2024-04-16 01:30:43,194] Trial 28 finished with value: 0.21644561841889062 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.26154064534881144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1313308679038699}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1728058934917983
Fold 2 IBS: 0.16613273087140148
Fold 3 IBS: 0.1752425051862629
Fold 4 IBS: 0.19545037913945612
Fold 5 IBS: 0.18577836193667824
[I 2024-04-16 01:30:59,559] Trial 29 finished with value: 0.17908197412511942 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.590452735593326, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1894700331250358}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18009129126221046
Fold 2 IBS: 0.16991867934953306
Fold 3 IBS: 0.18118166421743642
Fold 4 IBS: 0.21329354235589876
Fold 5 IBS: 0.19503330809108468
[I 2024-04-16 01:31:16,318] Trial 30 finished with value: 0.18790369705523266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.2125304486051036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17449717368418352
Fold 2 IBS: 0.15873065763573396
Fold 3 IBS: 0.17799356833494584
Fold 4 IBS: 0.18990025142492684

Fold 5 IBS: 0.17698987901902175
[I 2024-04-16 01:31:31,025] Trial 31 finished with value: 0.1756223060197624 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.6141886010044044, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.050889504115644586}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17921499719523448
Fold 2 IBS: 0.14457659998302025
Fold 3 IBS: 0.18892068480933402
Fold 4 IBS: 0.1881785321534129
Fold 5 IBS: 0.17366220512930025
[I 2024-04-16 01:31:50,191] Trial 32 finished with value: 0.17491060385406038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.7145937356077748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.040680386261001684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17839650482493216
Fold 2 IBS: 0.14376103753095715
Fold 3 IBS: 0.19179232168292484
Fold 4 IBS: 0.19114956333888955
Fold 5 IBS: 0.17341358371378018
[I 2024-04-16 01:32:19,201] Trial 33 finished with value: 0.17570260221829676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7166906016039446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09227781345982045}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16932356014486769
Fold 2 IBS: 0.15500446673627225
Fold 3 IBS: 0.17911021415557007
Fold 4 IBS: 0.1924434421788033
Fold 5 IBS: 0.1827561791077991
[I 2024-04-16 01:32:45,131] Trial 34 finished with value: 0.17572757246466247 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6617651070453551, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03171407678135554}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17172138717448102
Fold 2 IBS: 0.1489493130650319
Fold 3 IBS: 0.18425400801471595
Fold 4 IBS: 0.1932643172167075
Fold 5 IBS: 0.17711273715249415
[I 2024-04-16 01:33:03,830] Trial 35 finished with value: 0.1750603525246861 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.7113768772571837, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15846671523399145}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17419660096638498
Fold 2 IBS: 0.14719187785917906
Fold 3 IBS: 0.18565125612910302
Fold 4 IBS: 0.19257551123464545
Fold 5 IBS: 0.17764557195591085
[I 2024-04-16 01:33:13,439] Trial 36 finished with value: 0.17545216362904464 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 165, 'oob_score': False, 'max_samples': 0.5150316876314238, 'max_features': None, 'min_weight_fraction_leaf': 0.07821728657119803}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16964600099214439
Fold 2 IBS: 0.15385862052455887
Fold 3 IBS: 0.18067679456916436
Fold 4 IBS: 0.19330218283868858
Fold 5 IBS: 0.18067145906944948
[I 2024-04-16 01:33:25,162] Trial 37 finished with value: 0.17563101159880112 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.6558408084386204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026524892218781126}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21398210519775457
Fold 2 IBS: 0.22147310463890008
Fold 3 IBS: 0.20484795914030776
Fold 4 IBS: 0.22469082739864527
Fold 5 IBS: 0.21847043318447362
[I 2024-04-16 01:33:44,886] Trial 38 finished with value: 0.21669288591201624 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.5446753536916582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20739916362370578
Fold 2 IBS: 0.1396518555288153
Fold 3 IBS: 0.20101553841044428
Fold 4 IBS: 0.18775948197861053
Fold 5 IBS: 0.17175126099969984
[I 2024-04-16 01:34:08,879] Trial 39 finished with value: 0.18151546010825514 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.7867614811876313, 'max_features': None, 'min_weight_fraction_leaf': 0.11443308942980066}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18099751369940803
Fold 2 IBS: 0.14073570153984705
Fold 3 IBS: 0.19394522353389632
Fold 4 IBS: 0.1899027663588423
Fold 5 IBS: 0.17323048606648403
[I 2024-04-16 01:34:22,569] Trial 40 finished with value: 0.17576233823969556 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.5666383752254781, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07880882141692147}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1711305979532741
Fold 2 IBS: 0.14944644009789185
Fold 3 IBS: 0.1838255715011791
Fold 4 IBS: 0.19303788294761579
Fold 5 IBS: 0.17769110415876982
[I 2024-04-16 01:34:36,537] Trial 41 finished with value: 0.17502631933174614 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 312, 'oob_score': True, 'max_samples': 0.7412385222820266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16945209847062737}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1766253375339953
Fold 2 IBS: 0.14548886613385514
Fold 3 IBS: 0.18810559860305523
Fold 4 IBS: 0.18904619197923261
Fold 5 IBS: 0.17490826493381245
[I 2024-04-16 01:35:02,468] Trial 42 finished with value: 0.17483485183679015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.8639712154486969, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16678569984405386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2139789554890857
Fold 2 IBS: 0.22135558660927104
Fold 3 IBS: 0.2047725162249457
Fold 4 IBS: 0.22463102393551193
Fold 5 IBS: 0.21859845040133852
[I 2024-04-16 01:35:29,023] Trial 43 finished with value: 0.2166673065320306 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.8907059888796497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18785889346357237
Fold 2 IBS: 0.15285827950678846
Fold 3 IBS: 0.18232508298547248
Fold 4 IBS: 0.18846580968340798
Fold 5 IBS: 0.17332117086709029
[I 2024-04-16 01:35:52,042] Trial 44 finished with value: 0.17696584730126633 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.846059951367212, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14736137547860684}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1824125215519607
Fold 2 IBS: 0.142066615195965
Fold 3 IBS: 0.1952477350951836
Fold 4 IBS: 0.19275254902170263
Fold 5 IBS: 0.17385783785418485
[I 2024-04-16 01:36:13,086] Trial 45 finished with value: 0.17726745174379938 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.7898763610119546, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11906682715479999}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16985840962071383
Fold 2 IBS: 0.16096525914717788
Fold 3 IBS: 0.18227104026957164
Fold 4 IBS: 0.20281275724564665
Fold 5 IBS: 0.1850460571787144
[I 2024-04-16 01:36:15,514] Trial 46 finished with value: 0.18019070469236487 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.6496915230774891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08221811754778048}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16980857091041326
Fold 2 IBS: 0.15719115142034723
Fold 3 IBS: 0.1767449129839921
Fold 4 IBS: 0.19510331227382113
Fold 5 IBS: 0.1831755952242518
[I 2024-04-16 01:36:42,518] Trial 47 finished with value: 0.17640470856256513 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 479, 'oob_score': False, 'max_samples': 0.8914383434724882, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24824101632322468}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19349637716238946
Fold 2 IBS: 0.18021514079410297
Fold 3 IBS: 0.1797766992061227
Fold 4 IBS: 0.20805913242700583
Fold 5 IBS: 0.19958771263889286
[I 2024-04-16 01:37:07,724] Trial 48 finished with value: 0.19222701244570276 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.9967788477130068, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.2029239852759813
Fold 2 IBS: 0.13716491759028818
Fold 3 IBS: 0.2084231173473227
Fold 4 IBS: 0.19129569538138264
Fold 5 IBS: 0.16960756021085094
[I 2024-04-16 01:37:39,811] Trial 49 finished with value: 0.18188305516116512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.6825737614746896, 'max_features': None, 'min_weight_fraction_leaf': 0.020427001696118233}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1847999347983001
Fold 2 IBS: 0.15364870601921565
Fold 3 IBS: 0.1822009992001216
Fold 4 IBS: 0.18809108511963865
Fold 5 IBS: 0.17414367995939478
[I 2024-04-16 01:37:51,682] Trial 50 finished with value: 0.17657688101933416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8644699746287099, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06989429005204871}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17038930280276898
Fold 2 IBS: 0.15348758465747694
Fold 3 IBS: 0.18016675506323593
Fold 4 IBS: 0.1938593087420373
Fold 5 IBS: 0.18099103292628088
[I 2024-04-16 01:38:16,519] Trial 51 finished with value: 0.17577879683836 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.727895633786626, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18327602934679604}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17451701150431106
Fold 2 IBS: 0.14671503382427162
Fold 3 IBS: 0.18683750953876657
Fold 4 IBS: 0.19257094181568649
Fold 5 IBS: 0.17615300496682904
[I 2024-04-16 01:38:33,485] Trial 52 finished with value: 0.17535870032997297 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.7478990221520405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14624323581313917}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17559006537700683
Fold 2 IBS: 0.16972487299848873
Fold 3 IBS: 0.17529653726657532
Fold 4 IBS: 0.19855196165239603
Fold 5 IBS: 0.1851918744321701
[I 2024-04-16 01:38:53,311] Trial 53 finished with value: 0.1808710623453274 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.8074226422105014, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27324344422148944}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17595680778437212
Fold 2 IBS: 0.17008267991566167
Fold 3 IBS: 0.17604437670258266
Fold 4 IBS: 0.19769140576353486
Fold 5 IBS: 0.18734084278780233
[I 2024-04-16 01:39:27,569] Trial 54 finished with value: 0.18142322259079072 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.5775945927656037, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2001668400822587}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16773815898136948
Fold 2 IBS: 0.1576076816374329
Fold 3 IBS: 0.17803399667907918
Fold 4 IBS: 0.19725085339663992
Fold 5 IBS: 0.18451260927365026
[I 2024-04-16 01:39:31,680] Trial 55 finished with value: 0.17702865999363437 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.6303629140203428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16685382022581927}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18003668325471714
Fold 2 IBS: 0.14323357247265056
Fold 3 IBS: 0.19283157086976438
Fold 4 IBS: 0.192092008764836
Fold 5 IBS: 0.17436160978254575
[I 2024-04-16 01:39:47,870] Trial 56 finished with value: 0.17651108902890275 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.7623102674577037, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09861841429774906}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17302493479017875
Fold 2 IBS: 0.1667969562590488
Fold 3 IBS: 0.17568508570553082
Fold 4 IBS: 0.1958388085038477
Fold 5 IBS: 0.18612204667403598
[I 2024-04-16 01:40:10,613] Trial 57 finished with value: 0.1794935663865284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.6746410572190499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.19693288454187685
Fold 2 IBS: 0.16031608536235142
Fold 3 IBS: 0.18209014838073903
Fold 4 IBS: 0.18830938207544887
Fold 5 IBS: 0.1722123575079718
[I 2024-04-16 01:40:30,924] Trial 58 finished with value: 0.1799721715736776 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.9493525765812034, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.033039474629030334}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17638204755824788
Fold 2 IBS: 0.14724121981954666
Fold 3 IBS: 0.18830472263321374
Fold 4 IBS: 0.18908125561308473
Fold 5 IBS: 0.17501568142226698
[I 2024-04-16 01:40:37,564] Trial 59 finished with value: 0.175204985409272 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.706317491452594, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.011952641009515354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17441654996325617
Fold 2 IBS: 0.16879198972806275
Fold 3 IBS: 0.1747308489003251
Fold 4 IBS: 0.19678299634235394
Fold 5 IBS: 0.18428329935051413
[I 2024-04-16 01:40:48,093] Trial 60 finished with value: 0.1798011368569024 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.4446079220615766, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13552790545628873}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1726966416095679
Fold 2 IBS: 0.14791648216625575
Fold 3 IBS: 0.18587926582625136
Fold 4 IBS: 0.19250544947641468
Fold 5 IBS: 0.1767138327798232
[I 2024-04-16 01:41:15,252] Trial 61 finished with value: 0.17514233437166257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.7350539425199517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15353880193597452}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1784711929725387
Fold 2 IBS: 0.14471049906571562
Fold 3 IBS: 0.19083362219368874
Fold 4 IBS: 0.19321298173368606

Fold 5 IBS: 0.17601995444169838
[I 2024-04-16 01:41:35,266] Trial 62 finished with value: 0.1766496500814655 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.6969767031486694, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11947149985769817}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17325965795999854
Fold 2 IBS: 0.16035062956465257
Fold 3 IBS: 0.17539882197990753
Fold 4 IBS: 0.193362443315604
Fold 5 IBS: 0.1796554283287958
[I 2024-04-16 01:42:00,389] Trial 63 finished with value: 0.17640539622979168 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 311, 'oob_score': True, 'max_samples': 0.6304198495967799, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16702154024396243}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17417602273955624
Fold 2 IBS: 0.1480464954861786
Fold 3 IBS: 0.1861637654245361
Fold 4 IBS: 0.19307278746213727
Fold 5 IBS: 0.17661238768457427
[I 2024-04-16 01:42:19,270] Trial 64 finished with value: 0.1756142917593965 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.8416513210854921, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16738759238643802}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1822613083064998
Fold 2 IBS: 0.1416365045076241
Fold 3 IBS: 0.1960788715196419
Fold 4 IBS: 0.19275645033338762
Fold 5 IBS: 0.1744182820015701
[I 2024-04-16 01:42:42,683] Trial 65 finished with value: 0.17743028333374472 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.7722883894951643, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0665684368743143}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17389086197303102
Fold 2 IBS: 0.16790129559912909
Fold 3 IBS: 0.1751507252355886
Fold 4 IBS: 0.19750324318227722
Fold 5 IBS: 0.18620949704754197
[I 2024-04-16 01:43:07,006] Trial 66 finished with value: 0.18013112460751357 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.5947629158546897, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20025339037463216}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17423384494498612
Fold 2 IBS: 0.14631335780890575
Fold 3 IBS: 0.18861958817402585
Fold 4 IBS: 0.19245950764813075
Fold 5 IBS: 0.175067247621942
[I 2024-04-16 01:43:50,636] Trial 67 finished with value: 0.1753387092395981 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.7217571884559283, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13013771636318264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17535705050457914
Fold 2 IBS: 0.15778179636614245
Fold 3 IBS: 0.17763073839385685
Fold 4 IBS: 0.19018833285814207
Fold 5 IBS: 0.17770479034207873
[I 2024-04-16 01:44:13,252] Trial 68 finished with value: 0.17573254169295985 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.5191868058797825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.047795726630053076}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17480337133090915
Fold 2 IBS: 0.16874159329787056
Fold 3 IBS: 0.17579652970954177
Fold 4 IBS: 0.1923367638029231
Fold 5 IBS: 0.18690613654154167
[I 2024-04-16 01:44:48,170] Trial 69 finished with value: 0.17971687893655724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.18576927332867577, 'max_features': 'log2', 'min_weight_fraction_leaf': 7.114682696795181e-05}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.20781268631997615
Fold 2 IBS: 0.13838860575441492
Fold 3 IBS: 0.21122911345717027
Fold 4 IBS: 0.19170717046621447
Fold 5 IBS: 0.16987800654423307
[I 2024-04-16 01:45:14,253] Trial 70 finished with value: 0.18380311650840175 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.8126013453538647, 'max_features': None, 'min_weight_fraction_leaf': 0.10415283732963354}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16897127550996938
Fold 2 IBS: 0.15333527019800122
Fold 3 IBS: 0.18108923812924368
Fold 4 IBS: 0.19125151911620464
Fold 5 IBS: 0.1804095239747975
[I 2024-04-16 01:45:36,931] Trial 71 finished with value: 0.17501136538564327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.5965842869794661, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04020616684856252}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16942384334835775
Fold 2 IBS: 0.1534316341977167
Fold 3 IBS: 0.18126076316917372
Fold 4 IBS: 0.1918304245116947
Fold 5 IBS: 0.1797086597106947
[I 2024-04-16 01:45:57,475] Trial 72 finished with value: 0.17513106498752753 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.64967240812612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042859490745800255}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17483538806839433
Fold 2 IBS: 0.15903414917848718
Fold 3 IBS: 0.178305987368802
Fold 4 IBS: 0.18895015857840794
Fold 5 IBS: 0.17674514740069427
[I 2024-04-16 01:46:21,763] Trial 73 finished with value: 0.17557416611895713 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 468, 'oob_score': False, 'max_samples': 0.614601651625123, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08656637647813382}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685354387079355
Fold 2 IBS: 0.1519242369397579
Fold 3 IBS: 0.18329403645197254
Fold 4 IBS: 0.19121480234741198
Fold 5 IBS: 0.17959179151928248
[I 2024-04-16 01:46:44,599] Trial 74 finished with value: 0.17491206119327207 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.564394176347414, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0639505821191327}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16870518179470842
Fold 2 IBS: 0.1524006924636778
Fold 3 IBS: 0.1824052463489283
Fold 4 IBS: 0.19198874945374883
Fold 5 IBS: 0.17971814686012724
[I 2024-04-16 01:47:10,986] Trial 75 finished with value: 0.1750436033842381 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.5549716215197416, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06244978633063567}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17388421751906138
Fold 2 IBS: 0.1679541870820109
Fold 3 IBS: 0.17539898304019086
Fold 4 IBS: 0.1953143658823387
Fold 5 IBS: 0.18647747737304407
[I 2024-04-16 01:47:33,801] Trial 76 finished with value: 0.1798058461793292 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.5288500192319384, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016585234890071264}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17761169418416847
Fold 2 IBS: 0.16895784550549822
Fold 3 IBS: 0.17542226135379532
Fold 4 IBS: 0.19549660202075014
Fold 5 IBS: 0.18743069872463708
[I 2024-04-16 01:47:54,493] Trial 77 finished with value: 0.18098382035776983 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.3800215746179153, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03735564012092016}. Best is trial 11 with value: 0.17074634120633253.

Fold 1 IBS: 0.16818314645426713
Fold 2 IBS: 0.15369061634554518
Fold 3 IBS: 0.18213459050433092
Fold 4 IBS: 0.19123211966917278
Fold 5 IBS: 0.17979973767912885
[I 2024-04-16 01:48:18,581] Trial 78 finished with value: 0.17500804213048896 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 487, 'oob_score': False, 'max_samples': 0.4897248144615137, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053996872945124036}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1682237549262069
Fold 2 IBS: 0.15295334400832536
Fold 3 IBS: 0.18214608764478374
Fold 4 IBS: 0.19238806563941324
Fold 5 IBS: 0.18028732465861996
[I 2024-04-16 01:48:37,043] Trial 79 finished with value: 0.17519971537546983 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.49575398669591153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06405554874562534}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17507598055558485
Fold 2 IBS: 0.16867091079334554
Fold 3 IBS: 0.1744565827712509
Fold 4 IBS: 0.1954950968251498
Fold 5 IBS: 0.18635102171872073
[I 2024-04-16 01:48:51,742] Trial 80 finished with value: 0.18000991853281037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.43759421275648835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0533463490707784}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1714174399032279
Fold 2 IBS: 0.14887499618081926
Fold 3 IBS: 0.1849640281040515
Fold 4 IBS: 0.1899572218408997
Fold 5 IBS: 0.17713400076306418
[I 2024-04-16 01:49:06,142] Trial 81 finished with value: 0.17446953735841247 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5784234487575245, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10829522154445037}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.16877649511183368
Fold 2 IBS: 0.1546883871779083
Fold 3 IBS: 0.18056083236056208
Fold 4 IBS: 0.19133957386634493
Fold 5 IBS: 0.18162520349661385
[I 2024-04-16 01:49:20,731] Trial 82 finished with value: 0.17539809840265258 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5722759399876282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10440976094597362}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1685240734239476
Fold 2 IBS: 0.15222241351006804
Fold 3 IBS: 0.1822020345828932
Fold 4 IBS: 0.19079185577835267
Fold 5 IBS: 0.17960640446910925
[I 2024-04-16 01:49:36,063] Trial 83 finished with value: 0.17466935635287414 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.5451307479888213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0724192455670338}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17338079162104056
Fold 2 IBS: 0.15920893592551924
Fold 3 IBS: 0.17825449140901586
Fold 4 IBS: 0.18925769833312683
Fold 5 IBS: 0.17742455682194408
[I 2024-04-16 01:49:47,937] Trial 84 finished with value: 0.17550529482212932 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.5442180702857965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07567351514027787}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.1690383568215189
Fold 2 IBS: 0.15230702588653305
Fold 3 IBS: 0.1822765777502009
Fold 4 IBS: 0.19170674176025757
Fold 5 IBS: 0.18006279876989542
[I 2024-04-16 01:50:00,939] Trial 85 finished with value: 0.17507830019768117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.5030563110008609, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09285296477077623}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17784444889141396
Fold 2 IBS: 0.14568494632276702
Fold 3 IBS: 0.18681231725936967
Fold 4 IBS: 0.18938575035357394
Fold 5 IBS: 0.17417653028434565
[I 2024-04-16 01:50:12,713] Trial 86 finished with value: 0.17478079862229406 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.6227373925109708, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11680143459253466}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17320771484108127
Fold 2 IBS: 0.1471439015418838
Fold 3 IBS: 0.1868119711290211
Fold 4 IBS: 0.191522355137527
Fold 5 IBS: 0.17549663792817793
[I 2024-04-16 01:50:24,707] Trial 87 finished with value: 0.17483651611553824 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.6363957788305546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1264522778930551}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.177279146128294
Fold 2 IBS: 0.14462990587422714
Fold 3 IBS: 0.18982364231541823
Fold 4 IBS: 0.19123959493668208
Fold 5 IBS: 0.17462972301152646
[I 2024-04-16 01:50:38,126] Trial 88 finished with value: 0.17552040245322958 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.643212285009443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11042020211203352}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18172829377621072
Fold 2 IBS: 0.15455308362712544
Fold 3 IBS: 0.18079631963918813
Fold 4 IBS: 0.1866909754534505
Fold 5 IBS: 0.17486062534932048
[I 2024-04-16 01:50:47,169] Trial 89 finished with value: 0.17572585956905906 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 379, 'oob_score': False, 'max_samples': 0.6745160130358284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13729294470437828}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17159615871766515
Fold 2 IBS: 0.1492340100734715
Fold 3 IBS: 0.18525391328974408
Fold 4 IBS: 0.19170238188043215
Fold 5 IBS: 0.17723852207113783
[I 2024-04-16 01:50:56,197] Trial 90 finished with value: 0.17500499720649015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6100442323266079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08381032204107067}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17439132896823156
Fold 2 IBS: 0.1476318214680082
Fold 3 IBS: 0.1865038949155308
Fold 4 IBS: 0.19098341263244506
Fold 5 IBS: 0.17516827480713895
[I 2024-04-16 01:51:09,908] Trial 91 finished with value: 0.17493574655827088 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.6220455817398846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12351605327621175}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17132240828700077
Fold 2 IBS: 0.14948366004568905
Fold 3 IBS: 0.1849774655279456
Fold 4 IBS: 0.19091977764974633
Fold 5 IBS: 0.17791613386648897
[I 2024-04-16 01:51:23,274] Trial 92 finished with value: 0.17492388907537415 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.5773252805729456, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1260508695586116}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17523723037867286
Fold 2 IBS: 0.1453570091149411
Fold 3 IBS: 0.18962747105019612
Fold 4 IBS: 0.19107181469212342

Fold 5 IBS: 0.1747309238915691
[I 2024-04-16 01:51:37,150] Trial 93 finished with value: 0.1752048898255005 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.5630698614554802, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0944985972942633}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17026943747099219
Fold 2 IBS: 0.15255352423829832
Fold 3 IBS: 0.18160069813968083
Fold 4 IBS: 0.19096533404342483
Fold 5 IBS: 0.1822030877543707
[I 2024-04-16 01:51:46,705] Trial 94 finished with value: 0.17551841632935336 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.5751544947591161, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14409687866880386}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.17475332961241374
Fold 2 IBS: 0.14521126379405494
Fold 3 IBS: 0.18914044635556457
Fold 4 IBS: 0.19026828870845303
Fold 5 IBS: 0.1744104734429843
[I 2024-04-16 01:52:01,650] Trial 95 finished with value: 0.1747567603826941 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.5892575789175918, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11211324848978509}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.21400356610903593
Fold 2 IBS: 0.22204327857369352
Fold 3 IBS: 0.20415553733700337
Fold 4 IBS: 0.2250379696399111
Fold 5 IBS: 0.21815296605159928
[I 2024-04-16 01:52:04,754] Trial 96 finished with value: 0.21667866354224863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.46700128900375126, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35031312034195705}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.173562295845494
Fold 2 IBS: 0.14742220750236526
Fold 3 IBS: 0.18545169450924154
Fold 4 IBS: 0.18866406353263676
Fold 5 IBS: 0.17639414796763403
[I 2024-04-16 01:52:17,554] Trial 97 finished with value: 0.1742988818714743 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.5401266728628165, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11341150154917841}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.179800528231758
Fold 2 IBS: 0.15504407580671617
Fold 3 IBS: 0.18062194922738495
Fold 4 IBS: 0.18693465453878075
Fold 5 IBS: 0.17539368811607456
[I 2024-04-16 01:52:29,452] Trial 98 finished with value: 0.1755589791841429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.5436809153821575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10940615561612807}. Best is trial 11 with value: 0.17074634120633253.
Fold 1 IBS: 0.18678959754522786
Fold 2 IBS: 0.14275774495321747
Fold 3 IBS: 0.19217915320067025
Fold 4 IBS: 0.18335908765764633
Fold 5 IBS: 0.17253698272333465
[I 2024-04-16 01:52:40,650] Trial 99 finished with value: 0.1755245132160193 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.694819405505868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07480505292477731}. Best is trial 11 with value: 0.17074634120633253.


* Best trial for IBS:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.17074634120633253], datetime_start=datetime.datetime(2024, 4, 16, 1, 27, 53, 199057), datetime_complete=datetime.datetime(2024, 4, 16, 1, 27, 53, 842232), params={'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=11, value=None)


* Best Score for IBS:
 0.17074634120633253

In [47]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.846
train_ibs:  0.171

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [50]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=12,
                     max_samples=0.48042970450395145, min_samples_leaf=1,
                     min_samples_split=4,
                     min_weight_fraction_leaf=0.0025914663927405594,
                     n_estimators=289, random_state=123, warm_start=True)

test_cindex:  0.602

RandomSurvivalForest(max_depth=1, max_features='auto', max_leaf_nodes=18,
                     max_samples=0.7351810575897255, min_samples_leaf=11,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.008231293935378081,
                     n_estimators=2, random_state=123)

test_ibs:  0.233

In [51]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [52]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:52:42,519] A new study created in memory with name: no-name-1e3f9b66-c586-48a8-85d7-5af9e09c8328

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:52:44,538] Trial 0 finished with value: 0.763120153205612 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:52:49,980] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:53:02,037] Trial 2 finished with value: 0.7549111845989632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:03,103] Trial 3 finished with value: 0.7581427541761773 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:53:07,603] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:53:12,635] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:53:14,862] Trial 6 finished with value: 0.7620861007898516 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:53:21,857] Trial 7 finished with value: 0.7433829385982176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.715962441314554
[I 2024-04-16 01:53:22,494] Trial 8 finished with value: 0.7526603922254165 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.6818181818181818
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7206572769953051
[I 2024-04-16 01:53:36,922] Trial 9 finished with value: 0.7327992570997183 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:53:42,827] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:53:45,316] Trial 11 finished with value: 0.7610279984130963 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.763120153205612.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:53:47,643] Trial 12 finished with value: 0.7656344262692516 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:53:51,027] Trial 13 finished with value: 0.7565522092481783 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:53:53,274] Trial 14 finished with value: 0.7616650689919885 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7794117647058824

Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 01:53:54,861] Trial 15 finished with value: 0.7545769177214963 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.676056338028169
[I 2024-04-16 01:53:58,548] Trial 16 finished with value: 0.7335270596877141 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:54:01,862] Trial 17 finished with value: 0.7591715308548418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:54:05,277] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7656344262692516.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:54:08,032] Trial 19 finished with value: 0.7663281634231028 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 01:54:10,728] Trial 20 finished with value: 0.746722729311177 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8975839614288115, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:54:13,080] Trial 21 finished with value: 0.7629692767153701 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9830051091386647, 'min_weight_fraction_leaf': 0.11961357903200062}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:54:15,425] Trial 22 finished with value: 0.7628892919669691 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8609656753336752, 'min_weight_fraction_leaf': 0.15663178852989545}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:54:17,713] Trial 23 finished with value: 0.7509593791567746 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.737236690052532, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:54:20,479] Trial 24 finished with value: 0.7611911126952604 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9222263146213784, 'min_weight_fraction_leaf': 0.08957779552546857}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.859375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 01:54:23,401] Trial 25 finished with value: 0.7561901306130971 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8274383615832067, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:54:38,004] Trial 26 finished with value: 0.7444877442865183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6539680943502474, 'min_weight_fraction_leaf': 0.04317449484749}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:54:40,460] Trial 27 finished with value: 0.7566253755185277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9365238772272462, 'min_weight_fraction_leaf': 0.14306800767196773}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8415178571428571
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:54:42,319] Trial 28 finished with value: 0.7600206204906962 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7383223503010752, 'min_weight_fraction_leaf': 0.20900889157295355}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:54:47,741] Trial 29 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4766061840882204, 'min_weight_fraction_leaf': 0.25297594889320807}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:54:51,429] Trial 30 finished with value: 0.7619426335421767 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.09166005683798992}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:54:53,948] Trial 31 finished with value: 0.7601328692954678 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9462932212483206, 'min_weight_fraction_leaf': 0.12021009726526694}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:54:57,217] Trial 32 finished with value: 0.760869569103513 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9864877695110971, 'min_weight_fraction_leaf': 0.06164320836318145}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:55:00,064] Trial 33 finished with value: 0.7624746237982056 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9301489258006082, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:55:01,511] Trial 34 finished with value: 0.7567330098622376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9912043386887608, 'min_weight_fraction_leaf': 0.02249172399095729}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:55:07,997] Trial 35 finished with value: 0.7529807806767499 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.766068607890644, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:55:10,315] Trial 36 finished with value: 0.7591886238684845 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8553115001753557, 'min_weight_fraction_leaf': 0.22873450590105582}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 01:55:12,652] Trial 37 finished with value: 0.7555796977821257 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6217761713512069, 'min_weight_fraction_leaf': 0.12934411260414114}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:55:27,005] Trial 38 finished with value: 0.7535108102301846 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 428, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.04910893285740458}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:55:28,170] Trial 39 finished with value: 0.7553157338682244 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8005826243516873, 'min_weight_fraction_leaf': 0.07469351697759873}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:55:30,066] Trial 40 finished with value: 0.7605112688643425 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9569519035429586, 'min_weight_fraction_leaf': 0.2757731212264245}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:55:32,100] Trial 41 finished with value: 0.7609843014176124 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8687619648747806, 'min_weight_fraction_leaf': 0.15295888294766263}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:55:34,440] Trial 42 finished with value: 0.7638303926085905 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.906955015046886, 'min_weight_fraction_leaf': 0.10454210976347417}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8370535714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:55:36,513] Trial 43 finished with value: 0.7591740994887395 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8217177439443847, 'min_weight_fraction_leaf': 0.10552735389681006}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:55:38,429] Trial 44 finished with value: 0.7612405402767923 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9989309278077574, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 19 with value: 0.7663281634231028.

Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:55:40,175] Trial 45 finished with value: 0.7628719194609885 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9091736520975473, 'min_weight_fraction_leaf': 0.0038012551219620827}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.7347417840375586
[I 2024-04-16 01:55:50,052] Trial 46 finished with value: 0.7501344600750558 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 359, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5368271784486555, 'min_weight_fraction_leaf': 0.10615317714605318}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 01:55:50,551] Trial 47 finished with value: 0.7516793229025998 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 31, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9594946112358607, 'min_weight_fraction_leaf': 0.17333335446497328}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:55:52,761] Trial 48 finished with value: 0.7562519939011765 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7685785296036635, 'min_weight_fraction_leaf': 0.13176023447811921}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5432900432900433
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.5738396624472574
Fold 5 C-index: 0.460093896713615
[I 2024-04-16 01:55:56,537] Trial 49 finished with value: 0.5820501126470459 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8880373878399398, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:55:59,622] Trial 50 finished with value: 0.7630008769419695 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7034625855110039, 'min_weight_fraction_leaf': 0.07304621552955944}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:56:03,005] Trial 51 finished with value: 0.7612490374113632 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7321671383859141, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:56:06,063] Trial 52 finished with value: 0.7629420794152763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6907063917898906, 'min_weight_fraction_leaf': 0.0661877659346652}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:56:10,146] Trial 53 finished with value: 0.7596563589778932 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 480, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9052538185294309, 'min_weight_fraction_leaf': 0.08508715956661925}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:56:12,290] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.577878588672621, 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 19 with value: 0.7663281634231028.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:56:14,123] Trial 55 finished with value: 0.7704458139436589 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7999514777179073, 'min_weight_fraction_leaf': 0.035270943770753044}. Best is trial 55 with value: 0.7704458139436589.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:56:16,243] Trial 56 finished with value: 0.771384781079809 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7991467335557068, 'min_weight_fraction_leaf': 0.027992113153361142}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:56:25,442] Trial 57 finished with value: 0.74717809865806 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 248, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.79672071864693, 'min_weight_fraction_leaf': 0.016889715164357902}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:56:27,602] Trial 58 finished with value: 0.7677971640851675 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.828019859852415, 'min_weight_fraction_leaf': 0.03447642547531156}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 01:56:29,851] Trial 59 finished with value: 0.7697165233781805 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8346072695502785, 'min_weight_fraction_leaf': 0.0002567835070198393}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:56:31,583] Trial 60 finished with value: 0.7674757615164577 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 321, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6391411801898657, 'min_weight_fraction_leaf': 0.03561049450086254}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:56:33,209] Trial 61 finished with value: 0.7665829043736004 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6492185512714621, 'min_weight_fraction_leaf': 0.03617201704474487}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:56:34,803] Trial 62 finished with value: 0.7674728962234336 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 319, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5312924276275225, 'min_weight_fraction_leaf': 0.040385592930900376}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:56:36,451] Trial 63 finished with value: 0.7710730622821746 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5292658633860801, 'min_weight_fraction_leaf': 0.03711866587371772}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:56:38,617] Trial 64 finished with value: 0.7657902697781489 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.39806376813911337, 'min_weight_fraction_leaf': 0.03599381902829695}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:56:40,545] Trial 65 finished with value: 0.7621709115338706 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5323188905088267, 'min_weight_fraction_leaf': 0.010814253491385636}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:56:42,190] Trial 66 finished with value: 0.7691537029891617 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.49002509944053235, 'min_weight_fraction_leaf': 0.053181149195751426}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:56:43,604] Trial 67 finished with value: 0.7604151188182366 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.43798216039712035, 'min_weight_fraction_leaf': 0.0010098437298928856}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:56:44,869] Trial 68 finished with value: 0.7683829874029711 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6113081575629796, 'min_weight_fraction_leaf': 0.057217831184053644}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:56:46,163] Trial 69 finished with value: 0.7639295695425288 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5915899101823151, 'min_weight_fraction_leaf': 0.05522041323530981}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:56:48,127] Trial 70 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 182, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47632910975325155, 'min_weight_fraction_leaf': 0.35980997926626934}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:56:49,889] Trial 71 finished with value: 0.768254027368253 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6101916618563699, 'min_weight_fraction_leaf': 0.024998041606770292}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:56:51,367] Trial 72 finished with value: 0.7628057101379913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.32440915793159353, 'min_weight_fraction_leaf': 0.018643504112019715}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:56:52,753] Trial 73 finished with value: 0.7656587582763213 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 272, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5609478284070107, 'min_weight_fraction_leaf': 0.05622629784226072}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:56:54,031] Trial 74 finished with value: 0.7584779347240282 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5118014483585279, 'min_weight_fraction_leaf': 0.02563279470181265}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:56:55,501] Trial 75 finished with value: 0.7573932258116945 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6069046410719314, 'min_weight_fraction_leaf': 0.08378422745274237}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:57:01,518] Trial 76 finished with value: 0.7521751447219839 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.497864611352535, 'min_weight_fraction_leaf': 0.06709163220470778}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:57:02,688] Trial 77 finished with value: 0.7620487699772043 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 196, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6683682203156043, 'min_weight_fraction_leaf': 0.011300445410194197}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:57:04,040] Trial 78 finished with value: 0.760363871557148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.42677810376705305, 'min_weight_fraction_leaf': 0.052012092584961866}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:57:05,499] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7173081556448422, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:57:07,140] Trial 80 finished with value: 0.7683639336867342 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.35277360385569917, 'min_weight_fraction_leaf': 0.02852600943088988}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:57:08,956] Trial 81 finished with value: 0.7691928560351028 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3390678218166532, 'min_weight_fraction_leaf': 0.03153990098917725}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:57:11,084] Trial 82 finished with value: 0.7646076128469184 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 224, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3230507568153901, 'min_weight_fraction_leaf': 0.0014394857922413185}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:57:12,630] Trial 83 finished with value: 0.7614147057143738 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.23361689093258667, 'min_weight_fraction_leaf': 0.019775489029462356}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:57:14,355] Trial 84 finished with value: 0.7495893806395312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 260, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27445260818266226, 'min_weight_fraction_leaf': 0.09592965050134614}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:57:16,430] Trial 85 finished with value: 0.758556238262173 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3862488114937627, 'min_weight_fraction_leaf': 0.04471114770202597}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:57:18,126] Trial 86 finished with value: 0.7708567082564886 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 201, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.36377499756925225, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:57:21,513] Trial 87 finished with value: 0.7565355685297506 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3759670482683807, 'min_weight_fraction_leaf': 0.0767440911470792}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:57:26,502] Trial 88 finished with value: 0.7609903537745347 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.46073886535297426, 'min_weight_fraction_leaf': 0.05833982872177459}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:57:28,342] Trial 89 finished with value: 0.7699832161020457 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.295955749271664, 'min_weight_fraction_leaf': 0.010964572281232194}. Best is trial 56 with value: 0.771384781079809.

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:57:29,190] Trial 90 finished with value: 0.75952694664796 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27944226981321685, 'min_weight_fraction_leaf': 0.012928542240062478}. Best is trial 56 with value: 0.771384781079809.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:57:31,078] Trial 91 finished with value: 0.7801238175459491 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3602425648795669, 'min_weight_fraction_leaf': 0.02981466940699433}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:57:32,899] Trial 92 finished with value: 0.7662740508689903 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.25077855422842626, 'min_weight_fraction_leaf': 0.04540069770937229}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:57:35,132] Trial 93 finished with value: 0.7619860192654835 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.34979442362410473, 'min_weight_fraction_leaf': 0.06734177243231611}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:57:36,433] Trial 94 finished with value: 0.7645085743822805 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.193678974775281, 'min_weight_fraction_leaf': 0.010805974584784796}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:57:38,656] Trial 95 finished with value: 0.7709939821242033 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30647854490295495, 'min_weight_fraction_leaf': 0.03078253598240698}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:57:40,917] Trial 96 finished with value: 0.7702698288265208 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3052686496163978, 'min_weight_fraction_leaf': 0.029515857916013147}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 01:57:44,155] Trial 97 finished with value: 0.7686062560974729 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.30685683165847666, 'min_weight_fraction_leaf': 0.03193125520570377}. Best is trial 91 with value: 0.7801238175459491.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 01:57:46,202] Trial 98 finished with value: 0.7910857462403429 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}. Best is trial 98 with value: 0.7910857462403429.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784

[I 2024-04-16 01:57:48,394] A new study created in memory with name: no-name-78b04681-5944-4e84-ab86-9c9df4e9fe0f

Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:57:48,378] Trial 99 finished with value: 0.7902101231341658 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21478988941660257, 'min_weight_fraction_leaf': 0.0040275983337470555}. Best is trial 98 with value: 0.7910857462403429.


* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.7910857462403429], datetime_start=datetime.datetime(2024, 4, 16, 1, 57, 44, 162561), datetime_complete=datetime.datetime(2024, 4, 16, 1, 57, 46, 201846), params={'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.21404335777324493, 'min_weight_fraction_leaf': 0.0013133682808468272}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for C-index:
 0.7910857462403429

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1894050222499581
Fold 2 IBS: 0.18197094047238005
Fold 3 IBS: 0.18636461603352758
Fold 4 IBS: 0.19277723911134473
Fold 5 IBS: 0.19455867868991514
[I 2024-04-16 01:57:57,887] Trial 0 finished with value: 0.1890152993114251 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-16 01:58:10,067] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20172405646713062
Fold 2 IBS: 0.2032359255005334
Fold 3 IBS: 0.19513408046545
Fold 4 IBS: 0.2118539452893589
Fold 5 IBS: 0.20729390842542533
[I 2024-04-16 01:58:20,160] Trial 2 finished with value: 0.20384838322957965 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20209415878470963
Fold 2 IBS: 0.20376840661760706
Fold 3 IBS: 0.19482805354546556
Fold 4 IBS: 0.21132760062349532
Fold 5 IBS: 0.2062713273884813
[I 2024-04-16 01:58:23,789] Trial 3 finished with value: 0.2036579093919518 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-16 01:58:31,285] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-16 01:58:35,926] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1904913206168486
Fold 2 IBS: 0.18444679148666562
Fold 3 IBS: 0.1856399244213203
Fold 4 IBS: 0.19570316353343864
Fold 5 IBS: 0.19484476324380895
[I 2024-04-16 01:58:45,121] Trial 6 finished with value: 0.19022519266041643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.19248537415224085
Fold 2 IBS: 0.19105800071812176
Fold 3 IBS: 0.19070595715673386
Fold 4 IBS: 0.2001633927865564
Fold 5 IBS: 0.20070302537730883
[I 2024-04-16 01:58:50,449] Trial 7 finished with value: 0.19502315003819234 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.20480968165568902
Fold 2 IBS: 0.20484102123135522
Fold 3 IBS: 0.1975354311772608
Fold 4 IBS: 0.21193929006953224
Fold 5 IBS: 0.20806725700632217
[I 2024-04-16 01:58:51,829] Trial 8 finished with value: 0.2054385362280319 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.2113464419407712
Fold 2 IBS: 0.2169269042702578
Fold 3 IBS: 0.2014624387193473
Fold 4 IBS: 0.2214616279249577
Fold 5 IBS: 0.21570168611580814
[I 2024-04-16 01:59:02,313] Trial 9 finished with value: 0.21337981979422843 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-16 01:59:10,176] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.1959863918798848
Fold 2 IBS: 0.19656167181968498
Fold 3 IBS: 0.19210822980372252
Fold 4 IBS: 0.2085074674907661
Fold 5 IBS: 0.20360120107474317
[I 2024-04-16 01:59:17,742] Trial 11 finished with value: 0.1993529924137603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.1890152993114251.
Fold 1 IBS: 0.18512904520321427
Fold 2 IBS: 0.1740527886135347
Fold 3 IBS: 0.1861816706148936
Fold 4 IBS: 0.1893061222535103
Fold 5 IBS: 0.18959027778216106
[I 2024-04-16 01:59:30,985] Trial 12 finished with value: 0.18485198089346278 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19581913848034474
Fold 2 IBS: 0.19606584700533666
Fold 3 IBS: 0.18996353898817178
Fold 4 IBS: 0.2052342771852341
Fold 5 IBS: 0.2042479606113508
[I 2024-04-16 01:59:41,122] Trial 13 finished with value: 0.19826615245408763 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19648331141303396
Fold 2 IBS: 0.1983397281797131
Fold 3 IBS: 0.19106070821891877
Fold 4 IBS: 0.20858865485637526
Fold 5 IBS: 0.20490088125230282
[I 2024-04-16 01:59:48,228] Trial 14 finished with value: 0.1998746567840688 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.18485198089346278.

Fold 1 IBS: 0.19593558348243098
Fold 2 IBS: 0.19875475852789654
Fold 3 IBS: 0.1903333352589917
Fold 4 IBS: 0.20748251302147644
Fold 5 IBS: 0.203704702028721
[I 2024-04-16 01:59:53,768] Trial 15 finished with value: 0.19924217846390332 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21249912881980682
Fold 2 IBS: 0.2205333193107399
Fold 3 IBS: 0.2035653160933136
Fold 4 IBS: 0.22350418932951804
Fold 5 IBS: 0.2173028001714802
[I 2024-04-16 02:00:03,848] Trial 16 finished with value: 0.21548095074497176 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.19183114805047974
Fold 2 IBS: 0.19128424686172338
Fold 3 IBS: 0.18814594086160835
Fold 4 IBS: 0.20499323686954313
Fold 5 IBS: 0.20021013474043506
[I 2024-04-16 02:00:12,546] Trial 17 finished with value: 0.1952929414767579 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-16 02:00:15,415] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.1938760896028742
Fold 2 IBS: 0.19481663520802522
Fold 3 IBS: 0.18987914648212936
Fold 4 IBS: 0.20616644798233227
Fold 5 IBS: 0.20329633873487413
[I 2024-04-16 02:00:24,281] Trial 19 finished with value: 0.19760693160204706 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.20735529929388963
Fold 2 IBS: 0.208787348599295
Fold 3 IBS: 0.20137982249029263
Fold 4 IBS: 0.22312888688520593
Fold 5 IBS: 0.21346429994402807
[I 2024-04-16 02:00:24,992] Trial 20 finished with value: 0.21082313144254225 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.190149663845766
Fold 2 IBS: 0.1836146541541013
Fold 3 IBS: 0.18617574190891484
Fold 4 IBS: 0.19484231855727627
Fold 5 IBS: 0.19454635613742202
[I 2024-04-16 02:00:34,321] Trial 21 finished with value: 0.18986574692069608 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.18788264608767696
Fold 2 IBS: 0.17893614961467227
Fold 3 IBS: 0.18648188730398177
Fold 4 IBS: 0.19163081844739127
Fold 5 IBS: 0.1923382065001444
[I 2024-04-16 02:00:44,240] Trial 22 finished with value: 0.18745394159077333 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.18485198089346278.
Fold 1 IBS: 0.182703884521614
Fold 2 IBS: 0.16927944395517258
Fold 3 IBS: 0.18708643964817723
Fold 4 IBS: 0.18405528016378853
Fold 5 IBS: 0.18780835196581747
[I 2024-04-16 02:00:52,671] Trial 23 finished with value: 0.18218668005091396 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1895746301789297
Fold 2 IBS: 0.18039920275165355
Fold 3 IBS: 0.18517396368706437
Fold 4 IBS: 0.1961580074360814
Fold 5 IBS: 0.195878956164384
[I 2024-04-16 02:01:01,042] Trial 24 finished with value: 0.1894369520436226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19405738204668507
Fold 2 IBS: 0.19184743202663856
Fold 3 IBS: 0.19007884771101807
Fold 4 IBS: 0.20222541889504655
Fold 5 IBS: 0.20019121612149113
[I 2024-04-16 02:01:08,468] Trial 25 finished with value: 0.19568005936017588 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1940402932834844
Fold 2 IBS: 0.19432298692911043
Fold 3 IBS: 0.1892928247871703
Fold 4 IBS: 0.20429929982391268
Fold 5 IBS: 0.2021205628117341
[I 2024-04-16 02:01:20,376] Trial 26 finished with value: 0.19681519352708238 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.19637495341237682
Fold 2 IBS: 0.1958296716242794
Fold 3 IBS: 0.19032854761836807
Fold 4 IBS: 0.20681694152044366
Fold 5 IBS: 0.2037201720927651
[I 2024-04-16 02:01:32,258] Trial 27 finished with value: 0.19861405725364661 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1975709578546784
Fold 2 IBS: 0.19829442573017972
Fold 3 IBS: 0.1915470690360173
Fold 4 IBS: 0.21031250675637114
Fold 5 IBS: 0.20365042057523824
[I 2024-04-16 02:01:39,075] Trial 28 finished with value: 0.20027507599049693 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.20387777006226956
Fold 2 IBS: 0.21044805665332703
Fold 3 IBS: 0.1968442774138352
Fold 4 IBS: 0.21672718054203935
Fold 5 IBS: 0.2104572520340109
[I 2024-04-16 02:01:43,322] Trial 29 finished with value: 0.20767090734109636 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.18218668005091396.

Fold 1 IBS: 0.18923073618097216
Fold 2 IBS: 0.17632006586851645
Fold 3 IBS: 0.18707067058836963
Fold 4 IBS: 0.19307240934736852
Fold 5 IBS: 0.19343354994654252
[I 2024-04-16 02:01:49,683] Trial 30 finished with value: 0.18782548638635385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1949036294792145
Fold 2 IBS: 0.1886371865011974
Fold 3 IBS: 0.19117863815442443
Fold 4 IBS: 0.2001198684681372
Fold 5 IBS: 0.19929856633981852
[I 2024-04-16 02:01:56,924] Trial 31 finished with value: 0.19482757778855841 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7284646777879923, 'min_weight_fraction_leaf': 0.03048718971899994}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.18836540230737153
Fold 2 IBS: 0.1781707184035029
Fold 3 IBS: 0.18564681721521098
Fold 4 IBS: 0.19277633701007463
Fold 5 IBS: 0.19331832607908583
[I 2024-04-16 02:02:04,512] Trial 32 finished with value: 0.18765552020304915 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8171100382086772, 'min_weight_fraction_leaf': 0.06242514513187879}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1837243286986642
Fold 2 IBS: 0.1726544375035722
Fold 3 IBS: 0.1857048039781507
Fold 4 IBS: 0.18788491866873833
Fold 5 IBS: 0.18954352546044614
[I 2024-04-16 02:02:13,818] Trial 33 finished with value: 0.18390240286191434 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.905569688846346, 'min_weight_fraction_leaf': 0.06699217911977255}. Best is trial 23 with value: 0.18218668005091396.
Fold 1 IBS: 0.1801276242273068
Fold 2 IBS: 0.16520339426201733
Fold 3 IBS: 0.18553268896786967
Fold 4 IBS: 0.1845750159169672
Fold 5 IBS: 0.1835692206281775
[I 2024-04-16 02:02:23,413] Trial 34 finished with value: 0.1798015888004677 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.10969593086442025}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18049877857539035
Fold 2 IBS: 0.16663989287720696
Fold 3 IBS: 0.18469182662740596
Fold 4 IBS: 0.18574114889368326
Fold 5 IBS: 0.18477116270355273
[I 2024-04-16 02:02:35,943] Trial 35 finished with value: 0.18046856193544786 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 457, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9462418908074179, 'min_weight_fraction_leaf': 0.11750983562787085}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18037101974860273
Fold 2 IBS: 0.1669625142647935
Fold 3 IBS: 0.18453294697417297
Fold 4 IBS: 0.18631688561897877
Fold 5 IBS: 0.18678549330288546
[I 2024-04-16 02:02:46,588] Trial 36 finished with value: 0.18099377198188668 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.923638047949589, 'min_weight_fraction_leaf': 0.1257504807357439}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17994058405266816
Fold 2 IBS: 0.1669807265270973
Fold 3 IBS: 0.18438556878610593
Fold 4 IBS: 0.18645614257107018
Fold 5 IBS: 0.18554286319286462
[I 2024-04-16 02:02:57,134] Trial 37 finished with value: 0.18066117702596124 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.927527615447799, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18898732734511295
Fold 2 IBS: 0.1878387228485354
Fold 3 IBS: 0.18584838878907442
Fold 4 IBS: 0.20176513401286975
Fold 5 IBS: 0.1980065946518465
[I 2024-04-16 02:03:06,573] Trial 38 finished with value: 0.1924892335294878 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 413, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.22752773294338688}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17998400007564072
Fold 2 IBS: 0.1668284973568401
Fold 3 IBS: 0.1844288585354833
Fold 4 IBS: 0.1864703671417796
Fold 5 IBS: 0.18549779412503536
[I 2024-04-16 02:03:15,989] Trial 39 finished with value: 0.1806419034469558 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 395, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9298380017873809, 'min_weight_fraction_leaf': 0.12443904045417477}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.19739525553280404
Fold 2 IBS: 0.1991580825645237
Fold 3 IBS: 0.1908160522932353
Fold 4 IBS: 0.2108648699893906
Fold 5 IBS: 0.20525415655389037
[I 2024-04-16 02:03:23,989] Trial 40 finished with value: 0.2006976833867688 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8393239125172784, 'min_weight_fraction_leaf': 0.2776601558023945}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.18022938402780667
Fold 2 IBS: 0.16672467510224806
Fold 3 IBS: 0.18478016395935146
Fold 4 IBS: 0.18505725419817942
Fold 5 IBS: 0.18499738141995034
[I 2024-04-16 02:03:34,996] Trial 41 finished with value: 0.1803577717415072 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9543142613189195, 'min_weight_fraction_leaf': 0.12203673286244354}. Best is trial 34 with value: 0.1798015888004677.
Fold 1 IBS: 0.17977178159556786
Fold 2 IBS: 0.1648846924548364
Fold 3 IBS: 0.18522486265052154
Fold 4 IBS: 0.18475497257812473
Fold 5 IBS: 0.18410321441673297
[I 2024-04-16 02:03:44,899] Trial 42 finished with value: 0.17974790473915667 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9452765507108519, 'min_weight_fraction_leaf': 0.11124594841889346}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.19434886045869684
Fold 2 IBS: 0.1937482656990757
Fold 3 IBS: 0.18774938995929302
Fold 4 IBS: 0.2069666602426304
Fold 5 IBS: 0.20174569854155797
[I 2024-04-16 02:03:54,066] Trial 43 finished with value: 0.1969117749802508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503494540371628, 'min_weight_fraction_leaf': 0.16912809120322597}. Best is trial 42 with value: 0.17974790473915667.
Fold 1 IBS: 0.17791881709956506
Fold 2 IBS: 0.16086621549432498
Fold 3 IBS: 0.1866107993369831
Fold 4 IBS: 0.18206826755641561
Fold 5 IBS: 0.18254737423971062
[I 2024-04-16 02:04:02,562] Trial 44 finished with value: 0.17800229474539986 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996789958831329, 'min_weight_fraction_leaf': 0.1062495666001656}. Best is trial 44 with value: 0.17800229474539986.

Fold 1 IBS: 0.18107213977138975
Fold 2 IBS: 0.17375539456626857
Fold 3 IBS: 0.18442566650093445
Fold 4 IBS: 0.19068424307356363
Fold 5 IBS: 0.18831741970696433
[I 2024-04-16 02:04:10,738] Trial 45 finished with value: 0.18365097272382416 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9992649320581628, 'min_weight_fraction_leaf': 0.15624439720920977}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.19953982633918327
Fold 2 IBS: 0.19967504623742535
Fold 3 IBS: 0.19245042867286613
Fold 4 IBS: 0.2085347403492104
Fold 5 IBS: 0.20542311562702958
[I 2024-04-16 02:04:21,336] Trial 46 finished with value: 0.20112463144514292 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 471, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8649488262826621, 'min_weight_fraction_leaf': 0.10003378636590125}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18628122203639155
Fold 2 IBS: 0.18394244229194334
Fold 3 IBS: 0.18418434284415144
Fold 4 IBS: 0.2000447066326781
Fold 5 IBS: 0.19669443529653688
[I 2024-04-16 02:04:30,878] Trial 47 finished with value: 0.19022942982034025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 328, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9498767799232638, 'min_weight_fraction_leaf': 0.20999351713918613}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.18671807379697955
Fold 2 IBS: 0.1852509952197599
Fold 3 IBS: 0.18550487325289164
Fold 4 IBS: 0.20047588792062881
Fold 5 IBS: 0.19727228734012894
[I 2024-04-16 02:04:42,470] Trial 48 finished with value: 0.19104442350607775 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.797873402462955, 'min_weight_fraction_leaf': 0.1860519578289726}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.1826607073352976
Fold 2 IBS: 0.175421589749594
Fold 3 IBS: 0.18312277636383603
Fold 4 IBS: 0.19167275635552322
Fold 5 IBS: 0.18980799753609187
[I 2024-04-16 02:04:53,404] Trial 49 finished with value: 0.18453716546806856 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 476, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.961215604578711, 'min_weight_fraction_leaf': 0.11365414847803179}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17958611811383737
Fold 2 IBS: 0.17743708698305577
Fold 3 IBS: 0.1852250945699171
Fold 4 IBS: 0.19623907958032022
Fold 5 IBS: 0.19263688422130817
[I 2024-04-16 02:04:56,574] Trial 50 finished with value: 0.18622485269368774 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7701980857578967, 'min_weight_fraction_leaf': 0.13552189689536387}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17789145417182875
Fold 2 IBS: 0.1616433832004363
Fold 3 IBS: 0.1864085525144377
Fold 4 IBS: 0.18238123808283335
Fold 5 IBS: 0.18355417475301875
[I 2024-04-16 02:05:05,861] Trial 51 finished with value: 0.17837576054451096 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 399, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9009463698475542, 'min_weight_fraction_leaf': 0.09217858789465802}. Best is trial 44 with value: 0.17800229474539986.
Fold 1 IBS: 0.17799920113623321
Fold 2 IBS: 0.1605144874097507
Fold 3 IBS: 0.18702940084671463
Fold 4 IBS: 0.1819808205423802
Fold 5 IBS: 0.18038337030867524
[I 2024-04-16 02:05:13,975] Trial 52 finished with value: 0.1775814560487508 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 354, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8951291579049074, 'min_weight_fraction_leaf': 0.08581751823710401}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17775260791357536
Fold 2 IBS: 0.16149694714321464
Fold 3 IBS: 0.18707407916258054
Fold 4 IBS: 0.18274340233986375
Fold 5 IBS: 0.18259760716876144
[I 2024-04-16 02:05:22,885] Trial 53 finished with value: 0.17833292874559917 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.09240390871992925}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17940640525802973
Fold 2 IBS: 0.16245697210383966
Fold 3 IBS: 0.1891181060291726
Fold 4 IBS: 0.18256414899356924
Fold 5 IBS: 0.18141515612084266
[I 2024-04-16 02:05:31,668] Trial 54 finished with value: 0.17899215770109078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8266050067672521, 'min_weight_fraction_leaf': 0.08824574600148365}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19512770880551733
Fold 2 IBS: 0.19505507233319871
Fold 3 IBS: 0.19092891056177175
Fold 4 IBS: 0.20445218046771954
Fold 5 IBS: 0.2016905007036287
[I 2024-04-16 02:05:39,608] Trial 55 finished with value: 0.19745087457436722 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8830194506473868, 'min_weight_fraction_leaf': 0.08551025986155897}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.19639982363347272
Fold 2 IBS: 0.19605394572022347
Fold 3 IBS: 0.19089762812749347
Fold 4 IBS: 0.2039025193177431
Fold 5 IBS: 0.20198750112683878
[I 2024-04-16 02:05:45,278] Trial 56 finished with value: 0.19784828358515433 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8305267551869411, 'min_weight_fraction_leaf': 0.08769411360825642}. Best is trial 52 with value: 0.1775814560487508.
Fold 1 IBS: 0.17994763927738225
Fold 2 IBS: 0.1548261798648236
Fold 3 IBS: 0.19395939238204377
Fold 4 IBS: 0.175460592586965
Fold 5 IBS: 0.1780360580615449
[I 2024-04-16 02:05:53,645] Trial 57 finished with value: 0.1764459724345519 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9047823438465082, 'min_weight_fraction_leaf': 0.052520359548060905}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.21397444187069029
Fold 2 IBS: 0.22136998164786137
Fold 3 IBS: 0.2048209672135687
Fold 4 IBS: 0.22466869218034594
Fold 5 IBS: 0.21857265758585154
[I 2024-04-16 02:06:00,950] Trial 58 finished with value: 0.21668134809966358 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8971095327680366, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17919617267498053
Fold 2 IBS: 0.15724293354129823
Fold 3 IBS: 0.18865418939534942
Fold 4 IBS: 0.17914737264855643
Fold 5 IBS: 0.17930084192384113
[I 2024-04-16 02:06:07,384] Trial 59 finished with value: 0.17670830203680515 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8551879186310293, 'min_weight_fraction_leaf': 0.052198438381039824}. Best is trial 57 with value: 0.1764459724345519.

Fold 1 IBS: 0.17659457791938485
Fold 2 IBS: 0.15948702371575116
Fold 3 IBS: 0.18725320428102982
Fold 4 IBS: 0.18157027728642194
Fold 5 IBS: 0.18138733472020935
[I 2024-04-16 02:06:15,406] Trial 60 finished with value: 0.17725848358455942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 346, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7897702249078459, 'min_weight_fraction_leaf': 0.017004106952235656}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17815851130122365
Fold 2 IBS: 0.15937759601308119
Fold 3 IBS: 0.18671233531081954
Fold 4 IBS: 0.18030514263303932
Fold 5 IBS: 0.18041925981213724
[I 2024-04-16 02:06:23,925] Trial 61 finished with value: 0.1769945690140602 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8618449302748573, 'min_weight_fraction_leaf': 0.05544116405394582}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.189985439243045
Fold 2 IBS: 0.18589864301215556
Fold 3 IBS: 0.1868011652028388
Fold 4 IBS: 0.1963593578324162
Fold 5 IBS: 0.19462526820614628
[I 2024-04-16 02:06:33,361] Trial 62 finished with value: 0.19073397469932035 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7867417360932117, 'min_weight_fraction_leaf': 0.05261239827242224}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17825665056431175
Fold 2 IBS: 0.15873188722190795
Fold 3 IBS: 0.18623232494405856
Fold 4 IBS: 0.1804776675580393
Fold 5 IBS: 0.18054470634521663
[I 2024-04-16 02:06:43,734] Trial 63 finished with value: 0.17684864732670685 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 370, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8646509137730156, 'min_weight_fraction_leaf': 0.021855538175638154}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17870866019509835
Fold 2 IBS: 0.15879041008416891
Fold 3 IBS: 0.1868471374565984
Fold 4 IBS: 0.17989027006562788
Fold 5 IBS: 0.18013032641306964
[I 2024-04-16 02:06:51,142] Trial 64 finished with value: 0.17687336084291264 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8648441638800866, 'min_weight_fraction_leaf': 0.01786212960035921}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17816324436800104
Fold 2 IBS: 0.16489393379706804
Fold 3 IBS: 0.18434438709838466
Fold 4 IBS: 0.1849311299136772
Fold 5 IBS: 0.18219012941004298
[I 2024-04-16 02:06:58,395] Trial 65 finished with value: 0.17890456491743478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 312, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.017748854587234637}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.17911936362446912
Fold 2 IBS: 0.16110107360924447
Fold 3 IBS: 0.18681685101625886
Fold 4 IBS: 0.18222885762114663
Fold 5 IBS: 0.18129003273610622
[I 2024-04-16 02:07:04,371] Trial 66 finished with value: 0.17811123572144505 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7615860595939867, 'min_weight_fraction_leaf': 0.01711923253055358}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19752620497233223
Fold 2 IBS: 0.1978697596463517
Fold 3 IBS: 0.19204767218293306
Fold 4 IBS: 0.20544650914067045
Fold 5 IBS: 0.20224204696962983
[I 2024-04-16 02:07:11,970] Trial 67 finished with value: 0.19902643858238345 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6948127421387615, 'min_weight_fraction_leaf': 0.0007645315715799281}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18980037835825866
Fold 2 IBS: 0.18504474080399536
Fold 3 IBS: 0.18675479711869114
Fold 4 IBS: 0.19583872452973888
Fold 5 IBS: 0.1964614031322392
[I 2024-04-16 02:07:19,243] Trial 68 finished with value: 0.19078000878858464 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7554408511314311, 'min_weight_fraction_leaf': 0.05091993963276509}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.19466218577890979
Fold 2 IBS: 0.19389682402255248
Fold 3 IBS: 0.1911241110746692
Fold 4 IBS: 0.2034533752298619
Fold 5 IBS: 0.20173582211641464
[I 2024-04-16 02:07:29,485] Trial 69 finished with value: 0.19697446364448162 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8049955125325536, 'min_weight_fraction_leaf': 0.06630598317301307}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.18081283621129376
Fold 2 IBS: 0.16107815895963368
Fold 3 IBS: 0.18537244320497517
Fold 4 IBS: 0.18258777899134426
Fold 5 IBS: 0.1815710558255509
[I 2024-04-16 02:07:34,857] Trial 70 finished with value: 0.17828445463855955 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8704614691107458, 'min_weight_fraction_leaf': 0.03817571210017591}. Best is trial 57 with value: 0.1764459724345519.
Fold 1 IBS: 0.1784816385243448
Fold 2 IBS: 0.15527940159437076
Fold 3 IBS: 0.189332198745705
Fold 4 IBS: 0.17821728855635274
Fold 5 IBS: 0.17857494171269278
[I 2024-04-16 02:07:43,529] Trial 71 finished with value: 0.17597709382669321 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8554024477419847, 'min_weight_fraction_leaf': 0.025336147177118625}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17798712426248403
Fold 2 IBS: 0.15484687758413454
Fold 3 IBS: 0.19067949460417397
Fold 4 IBS: 0.17810023131975267
Fold 5 IBS: 0.17841198739744782
[I 2024-04-16 02:07:51,141] Trial 72 finished with value: 0.1760051430335986 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8330512937031878, 'min_weight_fraction_leaf': 0.018742428478884406}. Best is trial 71 with value: 0.17597709382669321.
Fold 1 IBS: 0.17863483477490216
Fold 2 IBS: 0.1551139005400038
Fold 3 IBS: 0.18916719727949505
Fold 4 IBS: 0.17811149370150642
Fold 5 IBS: 0.1783525956517838
[I 2024-04-16 02:07:58,974] Trial 73 finished with value: 0.17587600438953827 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8535353080113882, 'min_weight_fraction_leaf': 0.02393524919371511}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17931869016352942
Fold 2 IBS: 0.15516920228584516
Fold 3 IBS: 0.19388065315077987
Fold 4 IBS: 0.17839512488731568
Fold 5 IBS: 0.17847323379272784
[I 2024-04-16 02:08:05,713] Trial 74 finished with value: 0.1770473808560396 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8501055473932629, 'min_weight_fraction_leaf': 0.028866969062217605}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.21400073415496554
Fold 2 IBS: 0.2208296768873117
Fold 3 IBS: 0.20504439468604338
Fold 4 IBS: 0.22482948519570425
Fold 5 IBS: 0.21793226667188703
[I 2024-04-16 02:08:12,466] Trial 75 finished with value: 0.21652731151918242 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.28939609623192764, 'min_weight_fraction_leaf': 0.38792353869222}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18092605908791307
Fold 2 IBS: 0.1626714178491272
Fold 3 IBS: 0.1886398695722679
Fold 4 IBS: 0.18093264680250482
Fold 5 IBS: 0.18045471816506836
[I 2024-04-16 02:08:17,896] Trial 76 finished with value: 0.17872494229537628 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827568227091456, 'min_weight_fraction_leaf': 0.07075108588012974}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17853049514002048
Fold 2 IBS: 0.1606985623136455
Fold 3 IBS: 0.18934483196588067
Fold 4 IBS: 0.18117152161929295
Fold 5 IBS: 0.18168995291214574
[I 2024-04-16 02:08:24,115] Trial 77 finished with value: 0.17828707279019707 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 253, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8619520401496605, 'min_weight_fraction_leaf': 0.0541974809924827}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19018486273820845
Fold 2 IBS: 0.18580998501512688
Fold 3 IBS: 0.18646870485036496
Fold 4 IBS: 0.20416606516994676
Fold 5 IBS: 0.1976686334381368
[I 2024-04-16 02:08:33,190] Trial 78 finished with value: 0.19285965024235677 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4023122117577047, 'min_weight_fraction_leaf': 0.011653305300887117}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18468957100688832
Fold 2 IBS: 0.16220991806931515
Fold 3 IBS: 0.18433081379618457
Fold 4 IBS: 0.17919815038465237
Fold 5 IBS: 0.18126334949504005
[I 2024-04-16 02:08:40,231] Trial 79 finished with value: 0.1783383605504161 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.03184523795085815}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17809409767141368
Fold 2 IBS: 0.16747623448062568
Fold 3 IBS: 0.18492844526895663
Fold 4 IBS: 0.18608517724457674
Fold 5 IBS: 0.18436399027788122
[I 2024-04-16 02:08:48,167] Trial 80 finished with value: 0.18018958898869078 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7484656416215983, 'min_weight_fraction_leaf': 0.04261824663727039}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17861172388733232
Fold 2 IBS: 0.15579353335819895
Fold 3 IBS: 0.1930699509858784
Fold 4 IBS: 0.17862157523488698
Fold 5 IBS: 0.17918780109521346
[I 2024-04-16 02:08:54,372] Trial 81 finished with value: 0.17705691691230202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 263, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8580633834636456, 'min_weight_fraction_leaf': 0.026226351015522897}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17739332474625047
Fold 2 IBS: 0.15403352099493925
Fold 3 IBS: 0.19030462796552475
Fold 4 IBS: 0.17855931327525473
Fold 5 IBS: 0.1790999880755793
[I 2024-04-16 02:09:01,466] Trial 82 finished with value: 0.1758781550115097 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8118689779244362, 'min_weight_fraction_leaf': 0.0010966926240786878}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1773851694171574
Fold 2 IBS: 0.16253921619926498
Fold 3 IBS: 0.18775729750357517
Fold 4 IBS: 0.1836022417123993
Fold 5 IBS: 0.18177710952263798
[I 2024-04-16 02:09:08,307] Trial 83 finished with value: 0.17861220687100693 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8057382985870164, 'min_weight_fraction_leaf': 0.009258817492808987}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1854433030470413
Fold 2 IBS: 0.17681758475146342
Fold 3 IBS: 0.18419070581251012
Fold 4 IBS: 0.19690664360230137
Fold 5 IBS: 0.19542658681834563
[I 2024-04-16 02:09:15,057] Trial 84 finished with value: 0.18775696480633236 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.00018800640948312233}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19527212215204012
Fold 2 IBS: 0.19258034396176488
Fold 3 IBS: 0.19043822340063868
Fold 4 IBS: 0.202063421121186
Fold 5 IBS: 0.2007148431354912
[I 2024-04-16 02:09:23,435] Trial 85 finished with value: 0.19621379075422415 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9164856547650563, 'min_weight_fraction_leaf': 0.04956990041330743}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1784741230904449
Fold 2 IBS: 0.16087953939758443
Fold 3 IBS: 0.1866329755757358
Fold 4 IBS: 0.18365448231497417
Fold 5 IBS: 0.1817122965130897
[I 2024-04-16 02:09:32,219] Trial 86 finished with value: 0.1782706833783658 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8799886531366731, 'min_weight_fraction_leaf': 0.0714128496838598}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.18097049161570794
Fold 2 IBS: 0.1577854964552635
Fold 3 IBS: 0.18632859616594455
Fold 4 IBS: 0.17862370973831698
Fold 5 IBS: 0.1800955319809405
[I 2024-04-16 02:09:39,754] Trial 87 finished with value: 0.17676076519123468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8197308829626436, 'min_weight_fraction_leaf': 0.02805135094342286}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.19437352689769452
Fold 2 IBS: 0.1865309874000275
Fold 3 IBS: 0.19048273944837096
Fold 4 IBS: 0.19874750141792227
Fold 5 IBS: 0.19780307418997603
[I 2024-04-16 02:09:47,202] Trial 88 finished with value: 0.19358756587079823 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 283, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8170223392194952, 'min_weight_fraction_leaf': 0.026015865108324397}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.1843070555126035
Fold 2 IBS: 0.16138922163775485
Fold 3 IBS: 0.184029881060334
Fold 4 IBS: 0.18094300604589247
Fold 5 IBS: 0.18208306151695186
[I 2024-04-16 02:09:52,012] Trial 89 finished with value: 0.17855044515470733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.709051290189657, 'min_weight_fraction_leaf': 0.03884059880747235}. Best is trial 73 with value: 0.17587600438953827.

Fold 1 IBS: 0.18417873567489768
Fold 2 IBS: 0.17215507074054423
Fold 3 IBS: 0.18759974758071274
Fold 4 IBS: 0.1889870504957803
Fold 5 IBS: 0.18950903071510605
[I 2024-04-16 02:09:59,065] Trial 90 finished with value: 0.1844859270414082 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 262, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9722689668575789, 'min_weight_fraction_leaf': 0.013698489831834436}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17828049657703648
Fold 2 IBS: 0.15670442146325114
Fold 3 IBS: 0.1885595963781235
Fold 4 IBS: 0.17837564239035944
Fold 5 IBS: 0.17924664597888262
[I 2024-04-16 02:10:06,505] Trial 91 finished with value: 0.17623336055753064 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396105042050885, 'min_weight_fraction_leaf': 0.053257094236011215}. Best is trial 73 with value: 0.17587600438953827.
Fold 1 IBS: 0.17808001067342502
Fold 2 IBS: 0.15510139507880186
Fold 3 IBS: 0.18938170342854968
Fold 4 IBS: 0.1775338584977204
Fold 5 IBS: 0.17890319352130446
[I 2024-04-16 02:10:13,563] Trial 92 finished with value: 0.17580003223996027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17659770951694037
Fold 2 IBS: 0.16139548906489803
Fold 3 IBS: 0.1883833499377513
Fold 4 IBS: 0.18122376165938103
Fold 5 IBS: 0.18108443878413408
[I 2024-04-16 02:10:20,540] Trial 93 finished with value: 0.17773694979262095 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7779337650340382, 'min_weight_fraction_leaf': 0.07493855611907659}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1788420501389833
Fold 2 IBS: 0.1563664608382856
Fold 3 IBS: 0.1914656292286683
Fold 4 IBS: 0.17846880498246692
Fold 5 IBS: 0.17925187035417264
[I 2024-04-16 02:10:26,275] Trial 94 finished with value: 0.17687896310851536 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8379618640137403, 'min_weight_fraction_leaf': 0.06135463764973173}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.18233221300286004
Fold 2 IBS: 0.1548941049902076
Fold 3 IBS: 0.1911036971629455
Fold 4 IBS: 0.17526110217876542
Fold 5 IBS: 0.17738838491733422
[I 2024-04-16 02:10:34,729] Trial 95 finished with value: 0.17619590045042255 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9112906365218221, 'min_weight_fraction_leaf': 0.035312691708068014}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.19307487236591833
Fold 2 IBS: 0.1896720972205889
Fold 3 IBS: 0.189921274941199
Fold 4 IBS: 0.19850258678674562
Fold 5 IBS: 0.19947771844377382
[I 2024-04-16 02:10:41,705] Trial 96 finished with value: 0.19412970995164514 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.915276824625892, 'min_weight_fraction_leaf': 0.043225362789876695}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.17892075643860444
Fold 2 IBS: 0.15510444608753537
Fold 3 IBS: 0.19306794455023804
Fold 4 IBS: 0.17799888388058782
Fold 5 IBS: 0.1791674987979104
[I 2024-04-16 02:10:49,612] Trial 97 finished with value: 0.17685190595097522 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6707252385790339, 'min_weight_fraction_leaf': 0.03691531290573905}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.20874228003675835
Fold 2 IBS: 0.21425684765888878
Fold 3 IBS: 0.19860629371051958
Fold 4 IBS: 0.21913583881591187
Fold 5 IBS: 0.21337794366871632
[I 2024-04-16 02:10:56,482] Trial 98 finished with value: 0.210823840778159 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 304, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7396489612918897, 'min_weight_fraction_leaf': 0.3157312701103638}. Best is trial 92 with value: 0.17580003223996027.
Fold 1 IBS: 0.1810496922027384
Fold 2 IBS: 0.15501841966956653
Fold 3 IBS: 0.19245123255364907
Fold 4 IBS: 0.17446547560484074
Fold 5 IBS: 0.17710424236035277
[I 2024-04-16 02:11:03,076] Trial 99 finished with value: 0.1760178124782295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8849892919469375, 'min_weight_fraction_leaf': 0.007259167100140962}. Best is trial 92 with value: 0.17580003223996027.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.17580003223996027], datetime_start=datetime.datetime(2024, 4, 16, 2, 10, 6, 513365), datetime_complete=datetime.datetime(2024, 4, 16, 2, 10, 13, 562289), params={'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8396800309305413, 'min_weight_fraction_leaf': 0.02494499808293557}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=92, value=None)


* Best Score for IBS:
 0.17580003223996027

In [53]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [54]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.176

#### Test

In [55]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [56]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=19, max_features=1, max_leaf_nodes=12,
                   max_samples=0.21404335777324493, min_samples_leaf=1,
                   min_samples_split=4,
                   min_weight_fraction_leaf=0.0013133682808468272,
                   n_estimators=405, random_state=123, warm_start=True)

C-index score: 0.572

ExtraSurvivalTrees(max_depth=14, max_features=None, max_leaf_nodes=6,
                   max_samples=0.8396800309305413, min_samples_leaf=5,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.02494499808293557,
                   n_estimators=305, oob_score=True, random_state=123)

IBS: 0.221

In [57]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [58]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 02:11:06,138] A new study created in memory with name: no-name-49783cdd-7073-4d27-a3fc-64fe44abf78a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:11:43,761] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:12:03,034] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:12:21,096] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:12:52,805] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:13:04,420] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:13:07,333] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:13:38,209] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:13:47,743] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:13:48,937] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 02:15:06,440] Trial 9 finished with value: 0.7610259439316011 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.7253521126760564
[I 2024-04-16 02:17:07,903] Trial 10 finished with value: 0.6762046627675529 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:19:20,142] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 02:21:11,605] Trial 12 finished with value: 0.7542227664538642 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:22:07,874] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:23:23,548] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:24:31,332] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:25:18,161] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:53,844] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:29:05,214] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:29:10,567] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:29:57,880] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 02:31:38,325] Trial 21 finished with value: 0.6762505605169181 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 02:33:08,349] Trial 22 finished with value: 0.713908524620727 and parameters: {'subsample': 0.8956069884856214, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2154325997461391, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.38657871816113815, 'max_features': 'auto', 'min_impurity_decrease': 5.581115247824534e-07, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:34:26,076] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7743503496065262, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.31930849090648333, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9663328483036315, 'min_weight_fraction_leaf': 0.441052304834414, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:35:23,077] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8969825748215434, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21976013005558012, 'n_estimators': 340, 'criterion': 'squared_error', 'ccp_alpha': 0.785180332493211, 'min_weight_fraction_leaf': 0.2669492013977464, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:36:31,346] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8840318412875596, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.27382248438555523, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 2.0183033060186855, 'min_weight_fraction_leaf': 0.33643534713187806, 'max_features': 'auto', 'min_impurity_decrease': 5.889654690360788e-06, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:37:42,113] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7565765917190008, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.4300954216773497, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6678836557349488, 'min_weight_fraction_leaf': 0.06207030473994396, 'max_features': 1, 'min_impurity_decrease': 7.622421032390112e-07, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:26,456] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.322970332048742, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 5.9472530603001, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 7.551787280023211e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:40:01,289] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.5232204998663266, 'n_estimators': 326, 'criterion': 'squared_error', 'ccp_alpha': 4.188554251555486, 'min_weight_fraction_leaf': 0.43612805409636834, 'max_features': 0.1, 'min_impurity_decrease': 3.2161459286083955e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:40:08,466] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.32499045544570565, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 2.694991982922698, 'min_weight_fraction_leaf': 0.37973053029520576, 'max_features': 'log2', 'min_impurity_decrease': 1.983769791843576e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:40:33,600] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.1618733123667288, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.29835074442775955, 'max_features': 'auto', 'min_impurity_decrease': 3.855449012555335e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:42:13,876] Trial 31 finished with value: 0.7183781009689083 and parameters: {'subsample': 0.9458857893837966, 'learning_rate': 0.016420196712320707, 'dropout_rate': 0.2035906465216125, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.36089352993330637, 'max_features': 'auto', 'min_impurity_decrease': 4.318534340206297e-07, 'validation_fraction': 0.9595045281115817, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 02:43:55,671] Trial 32 finished with value: 0.7475960929275194 and parameters: {'subsample': 0.8638126341310897, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.22569622133720652, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.019083703384414813, 'min_weight_fraction_leaf': 0.351646089861356, 'max_features': 'auto', 'min_impurity_decrease': 1.0352347378444166e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:45:32,778] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9565444847948921, 'learning_rate': 0.016942278074178134, 'dropout_rate': 0.26584476281814184, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.3586353681932053, 'max_features': 'auto', 'min_impurity_decrease': 1.3326513674306949e-07, 'validation_fraction': 0.8389914767654065, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:46:58,611] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7038358300021869, 'learning_rate': 0.026650337425697362, 'dropout_rate': 0.369220485987212, 'n_estimators': 472, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8672217172879074, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0420752279999204e-07, 'validation_fraction': 0.9169827663346786, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:48:12,063] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.8615302123878027, 'learning_rate': 0.016287667469869524, 'dropout_rate': 0.16621310899612352, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1524333738759642, 'min_weight_fraction_leaf': 0.16211724647631331, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:48:50,774] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6682496627875864, 'learning_rate': 0.030254735591726832, 'dropout_rate': 0.29166011812932907, 'n_estimators': 299, 'criterion': 'squared_error', 'ccp_alpha': 0.48701662298918014, 'min_weight_fraction_leaf': 0.24844276308137436, 'max_features': 'auto', 'min_impurity_decrease': 2.2923203534620568e-05, 'validation_fraction': 0.8152696073327098, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:49:24,375] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7883126136564298, 'learning_rate': 0.02225236619873, 'dropout_rate': 0.7511928761026783, 'n_estimators': 408, 'criterion': 'squared_error', 'ccp_alpha': 1.198246212835568, 'min_weight_fraction_leaf': 0.42198945643308866, 'max_features': None, 'min_impurity_decrease': 8.54824079758415e-06, 'validation_fraction': 0.36353542989298265, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:50:51,262] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0010786268484829992, 'dropout_rate': 0.4076069474884072, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.295727563116735, 'max_features': 'auto', 'min_impurity_decrease': 1.0214527419957568e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:52:10,847] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.041857701576065075, 'dropout_rate': 0.3444296796757608, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.49564059074376393, 'max_features': 1, 'min_impurity_decrease': 2.966650399906854e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:06,904] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5863013406787322, 'learning_rate': 0.007311607072090859, 'dropout_rate': 0.22290618957651392, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 0.5271854997531392, 'min_weight_fraction_leaf': 0.2674270064426415, 'max_features': 'auto', 'min_impurity_decrease': 2.2073664358493507e-07, 'validation_fraction': 0.6520524706411407, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 10}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6455399061032864
[I 2024-04-16 02:53:07,351] Trial 41 finished with value: 0.6429727820316606 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.01362396235680392, 'dropout_rate': 0.2062435369784147, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.01657550447328801, 'min_weight_fraction_leaf': 0.3505399688940837, 'max_features': 'auto', 'min_impurity_decrease': 3.2101990795082183e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6774891774891775
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7394366197183099
[I 2024-04-16 02:54:48,215] Trial 42 finished with value: 0.7155999282604174 and parameters: {'subsample': 0.8533107407997301, 'learning_rate': 0.007773927115663986, 'dropout_rate': 0.13112078909045524, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.002608770948556355, 'min_weight_fraction_leaf': 0.4128432753433128, 'max_features': 'auto', 'min_impurity_decrease': 5.944083612909987e-07, 'validation_fraction': 0.8846352497042296, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:56:39,837] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8537828670002746, 'learning_rate': 0.006387564095638705, 'dropout_rate': 0.14103084365529428, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.817694027019807, 'min_weight_fraction_leaf': 0.4055199685421495, 'max_features': 'auto', 'min_impurity_decrease': 1.0127188716001679e-07, 'validation_fraction': 0.8846775181555923, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:58:04,980] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9979692688170061, 'learning_rate': 0.018866368595143467, 'dropout_rate': 0.13470507680405208, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.1995459782383484, 'min_weight_fraction_leaf': 0.46282880746501454, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7785221066313981, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:59:42,421] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.9423581992051376, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.1841937912472535, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.415353860249426, 'min_weight_fraction_leaf': 0.21565594544774125, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.9726137478639892, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:59:52,690] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8422605515062627, 'learning_rate': 0.023740342140917903, 'dropout_rate': 0.9694253886674298, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 6.2946137459239395, 'min_weight_fraction_leaf': 0.32020062193032595, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0058604443673675e-07, 'validation_fraction': 0.8666993731020032, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:01:38,226] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.8213077858159359, 'learning_rate': 0.006066129837698666, 'dropout_rate': 0.2502078347914406, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 1.0929789618945918, 'min_weight_fraction_leaf': 0.37165158771817175, 'max_features': 'log2', 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.7292699872905781, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:02:17,169] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7434813106553043, 'learning_rate': 0.014252633864159536, 'dropout_rate': 0.10308804442602489, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 0.43583456106887075, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 'auto', 'min_impurity_decrease': 1.1669342789968816e-06, 'validation_fraction': 0.9922167438954732, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:02:33,937] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7918904765497661, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.46610361399140793, 'max_features': None, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8725986413596462, 'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:38,788] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9263228105960017, 'learning_rate': 0.03241286314321831, 'dropout_rate': 0.28503824367896063, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.3883012665777896, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 5.669547081135241e-07, 'validation_fraction': 0.21769072749948642, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7347417840375586
[I 2024-04-16 03:05:03,265] Trial 51 finished with value: 0.7185570650203711 and parameters: {'subsample': 0.8666208085311428, 'learning_rate': 0.010299237341157315, 'dropout_rate': 0.22486517268782114, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.01237319335130728, 'min_weight_fraction_leaf': 0.40520668278071015, 'max_features': 'auto', 'min_impurity_decrease': 4.3165690993230386e-07, 'validation_fraction': 0.9299180470052416, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.7279411764705882
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 03:06:24,502] Trial 52 finished with value: 0.7047318894129233 and parameters: {'subsample': 0.862657875185063, 'learning_rate': 0.008306104796295998, 'dropout_rate': 0.2416732200644876, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.03660243985093782, 'min_weight_fraction_leaf': 0.42223276607292903, 'max_features': 'auto', 'min_impurity_decrease': 1.9405719092810494e-07, 'validation_fraction': 0.9395823090270392, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:08:02,694] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.967375882472721, 'learning_rate': 0.001394900878889816, 'dropout_rate': 0.1429837848690379, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.45374308869283775, 'min_weight_fraction_leaf': 0.4108404544677715, 'max_features': 'auto', 'min_impurity_decrease': 4.0655981745194066e-07, 'validation_fraction': 0.8259835575505652, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:09:47,179] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8134129014758551, 'learning_rate': 0.019733381620994493, 'dropout_rate': 0.18641432881009587, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.9596523069530926, 'min_weight_fraction_leaf': 0.2970013736941614, 'max_features': 'auto', 'min_impurity_decrease': 1.1580334563112213e-06, 'validation_fraction': 0.8996663522529539, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:10:40,097] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9195938698764112, 'learning_rate': 0.015173363534313505, 'dropout_rate': 0.3034930079612927, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.35259963018802765, 'min_weight_fraction_leaf': 0.36508275980555405, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.9545460877946491, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:11:56,891] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.5150383761242161, 'learning_rate': 0.004332984500606809, 'dropout_rate': 0.23996644019536584, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6264958328369468, 'min_weight_fraction_leaf': 0.3385656815459147, 'max_features': 'auto', 'min_impurity_decrease': 5.479611541769766e-07, 'validation_fraction': 0.9991586611408243, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 03:13:33,977] Trial 57 finished with value: 0.7056496649292628 and parameters: {'subsample': 0.8773751542246392, 'learning_rate': 0.008949552280352413, 'dropout_rate': 0.35136020576582316, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.001936457287774803, 'min_weight_fraction_leaf': 0.46006445679681335, 'max_features': 1, 'min_impurity_decrease': 4.834524920287448e-06, 'validation_fraction': 0.5189236064802895, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:15:08,174] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.6843244921733918, 'learning_rate': 0.0253510504546932, 'dropout_rate': 0.12033118040350205, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 1.625653153563989, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'auto', 'min_impurity_decrease': 1.5983704938418812e-07, 'validation_fraction': 0.7886847055500306, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:16:02,637] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.021369220605781735, 'dropout_rate': 0.4274904250363094, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.4410912197424578, 'max_features': 0.1, 'min_impurity_decrease': 3.251577586017116e-07, 'validation_fraction': 0.8548774558884649, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:16:17,111] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.18796169351263226, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 2.934583742024675, 'min_weight_fraction_leaf': 0.22745666702108258, 'max_features': 'log2', 'min_impurity_decrease': 1.7635925207609514e-06, 'validation_fraction': 0.8928900471979833, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:17:40,124] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.9082876532055691, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.22106826324294734, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22580244780696104, 'min_weight_fraction_leaf': 0.39038531498517337, 'max_features': 'auto', 'min_impurity_decrease': 6.513707268856941e-07, 'validation_fraction': 0.9307105316317981, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:19:15,976] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.9763302214447585, 'learning_rate': 0.01082289338801184, 'dropout_rate': 0.16671702405067812, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.7562237450148781, 'min_weight_fraction_leaf': 0.4020635676726066, 'max_features': 'auto', 'min_impurity_decrease': 9.006731163870761e-07, 'validation_fraction': 0.9167969646120265, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.744131455399061
[I 2024-04-16 03:20:53,589] Trial 63 finished with value: 0.7378685391643164 and parameters: {'subsample': 0.8703294082808486, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.2614766602947102, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.37595194847909125, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.9646429973127362, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:22:26,991] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7961678718772995, 'learning_rate': 0.015415575577593231, 'dropout_rate': 0.262554001169913, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.2777045506790212, 'min_weight_fraction_leaf': 0.33434502833689206, 'max_features': 'auto', 'min_impurity_decrease': 3.33975749875224e-07, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:23:57,879] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8385594937622445, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.30265220308227164, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.29056375204041135, 'min_weight_fraction_leaf': 0.28320128906700315, 'max_features': 'auto', 'min_impurity_decrease': 1.5031409606569138e-07, 'validation_fraction': 0.962588947418926, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:25:23,487] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8825125214383175, 'learning_rate': 0.01896416177644482, 'dropout_rate': 0.3845297883432178, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 2.1083391199212573, 'min_weight_fraction_leaf': 0.37068365181765817, 'max_features': 'auto', 'min_impurity_decrease': 2.926750067783851e-07, 'validation_fraction': 0.8532835495181553, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:26:40,333] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4585158632928328, 'learning_rate': 0.014185974978345665, 'dropout_rate': 0.20713420518497186, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.31472432527464905, 'max_features': 'sqrt', 'min_impurity_decrease': 4.927665175660364e-07, 'validation_fraction': 0.9061207180731781, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:27:57,113] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.9444579521154932, 'learning_rate': 0.003984164164187884, 'dropout_rate': 0.3349732603740458, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 1.078654850128927, 'min_weight_fraction_leaf': 0.1817947096952169, 'max_features': 'auto', 'min_impurity_decrease': 1.3822768751381375e-06, 'validation_fraction': 0.9998779842696178, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:28:44,302] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7351244679725103, 'learning_rate': 0.021607496405331474, 'dropout_rate': 0.6578270843665299, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.41822793529640967, 'max_features': 'auto', 'min_impurity_decrease': 7.981891756908656e-06, 'validation_fraction': 0.8252701554197789, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7535211267605634
[I 2024-04-16 03:30:03,109] Trial 70 finished with value: 0.7431871031407425 and parameters: {'subsample': 0.7696833733505561, 'learning_rate': 0.009479076517851487, 'dropout_rate': 0.27892959003506596, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.010016393064755276, 'min_weight_fraction_leaf': 0.38115268230138605, 'max_features': None, 'min_impurity_decrease': 1.0506244573812146e-07, 'validation_fraction': 0.7475037972329144, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7065727699530516
[I 2024-04-16 03:31:16,717] Trial 71 finished with value: 0.722533881479949 and parameters: {'subsample': 0.7726307722867607, 'learning_rate': 0.009349407530944867, 'dropout_rate': 0.272889788803047, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.43478396682346765, 'max_features': None, 'min_impurity_decrease': 1.417211124243175e-07, 'validation_fraction': 0.6051329974465358, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:32:34,654] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7701057123127394, 'learning_rate': 0.009957649760499912, 'dropout_rate': 0.27848137285412433, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.7357633085189087, 'min_weight_fraction_leaf': 0.37805750469189997, 'max_features': None, 'min_impurity_decrease': 1.0230782331935316e-07, 'validation_fraction': 0.6095946706874, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:33:36,223] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.82176382526325, 'learning_rate': 0.05058817311100894, 'dropout_rate': 0.23811185280532784, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.35666680166132303, 'min_weight_fraction_leaf': 0.4363333364980036, 'max_features': None, 'min_impurity_decrease': 1.4978008424793533e-07, 'validation_fraction': 0.6393756125190079, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:34:38,511] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6354098366620761, 'learning_rate': 0.013009902635057455, 'dropout_rate': 0.3101706081176934, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7099066346200665, 'min_weight_fraction_leaf': 0.4804502891962041, 'max_features': None, 'min_impurity_decrease': 2.271616193402817e-07, 'validation_fraction': 0.6862699083190502, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:35:55,080] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9104967643697162, 'learning_rate': 0.01724034992100258, 'dropout_rate': 0.26334849962817525, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.5692251904189567, 'min_weight_fraction_leaf': 0.35851813148439854, 'max_features': None, 'min_impurity_decrease': 2.0843558415731406e-07, 'validation_fraction': 0.5063775748030491, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:37:15,358] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5556564275523779, 'learning_rate': 0.0033204528527945613, 'dropout_rate': 0.3636837900816117, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3042363908259532, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.2249424139094463e-07, 'validation_fraction': 0.561045056767258, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:38:43,145] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7208569038924214, 'learning_rate': 0.026256982803923905, 'dropout_rate': 0.2305409399859041, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.9525490995769573, 'min_weight_fraction_leaf': 0.398138662499872, 'max_features': None, 'min_impurity_decrease': 3.9802168951657813e-07, 'validation_fraction': 0.7435745226595007, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.7723004694835681
[I 2024-04-16 03:39:51,698] Trial 78 finished with value: 0.7520537875882294 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.012134054211554952, 'dropout_rate': 0.17020981110797495, 'n_estimators': 371, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25792648841120175, 'max_features': None, 'min_impurity_decrease': 0.0002607692087694095, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7610259439316011.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 03:40:07,372] Trial 79 finished with value: 0.7612651729154684 and parameters: {'subsample': 0.5770898503146864, 'learning_rate': 0.005718089536250872, 'dropout_rate': 0.8831816560103296, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.006784676195889549, 'min_weight_fraction_leaf': 0.26783577777991785, 'max_features': None, 'min_impurity_decrease': 0.00026754667959111344, 'validation_fraction': 0.45556658035861064, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:40:20,020] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.005715181757518938, 'dropout_rate': 0.8564920404565602, 'n_estimators': 301, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.2585934440223751, 'max_features': None, 'min_impurity_decrease': 0.00022588848940598272, 'validation_fraction': 0.4281000770625221, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 03:40:46,367] Trial 81 finished with value: 0.7574041343834572 and parameters: {'subsample': 0.573469759644561, 'learning_rate': 0.00917313652468523, 'dropout_rate': 0.7551006664918564, 'n_estimators': 378, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025432538716388925, 'min_weight_fraction_leaf': 0.2330447322703676, 'max_features': None, 'min_impurity_decrease': 0.0003172843737611832, 'validation_fraction': 0.47647246663093756, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:41:06,236] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.6061238477976733, 'learning_rate': 0.012604022944147218, 'dropout_rate': 0.8294471229873877, 'n_estimators': 356, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5341063025845167, 'min_weight_fraction_leaf': 0.19664785169557314, 'max_features': None, 'min_impurity_decrease': 0.0007825748634975355, 'validation_fraction': 0.3806000784667706, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:41:21,119] Trial 83 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6535018868517685, 'learning_rate': 0.0014826800610252661, 'dropout_rate': 0.8992417742346922, 'n_estimators': 369, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20169466462041857, 'min_weight_fraction_leaf': 0.22451223837031314, 'max_features': None, 'min_impurity_decrease': 0.0003609663069928288, 'validation_fraction': 0.4711031887993497, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:41:46,257] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.58189223841496, 'learning_rate': 0.008316297732970858, 'dropout_rate': 0.6818395627907664, 'n_estimators': 335, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.28172882309407266, 'max_features': None, 'min_impurity_decrease': 0.001202775121736422, 'validation_fraction': 0.38945203718855725, 'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 79 with value: 0.7612651729154684.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:42:05,639] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.6947678980383888, 'learning_rate': 0.06101724551624799, 'dropout_rate': 0.7652597742653805, 'n_estimators': 317, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5339563287597978, 'min_weight_fraction_leaf': 0.24506733493657065, 'max_features': None, 'min_impurity_decrease': 0.0001261040433430487, 'validation_fraction': 0.46765139398223676, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:42:24,496] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5329646889170038, 'learning_rate': 0.006001760143614843, 'dropout_rate': 0.8650393351469537, 'n_estimators': 381, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2772447793960837, 'min_weight_fraction_leaf': 0.2595916601449126, 'max_features': None, 'min_impurity_decrease': 8.277387430400139e-05, 'validation_fraction': 0.5331294902958005, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:43:08,412] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5772171688575647, 'learning_rate': 0.012297427382052604, 'dropout_rate': 0.5450508211122536, 'n_estimators': 389, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8948782241791482, 'min_weight_fraction_leaf': 0.30432090537719336, 'max_features': None, 'min_impurity_decrease': 0.000380077265080333, 'validation_fraction': 0.5815548971606083, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:43:13,896] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4900792232135173, 'learning_rate': 0.01688118268369649, 'dropout_rate': 0.9961303410511458, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 0.32151562869669414, 'min_weight_fraction_leaf': 0.22873481062830656, 'max_features': None, 'min_impurity_decrease': 0.0016050858690837527, 'validation_fraction': 0.47521875145819903, 'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 79 with value: 0.7612651729154684.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 03:43:38,072] Trial 89 finished with value: 0.7615428784886943 and parameters: {'subsample': 0.6088139660412204, 'learning_rate': 0.007354720529210388, 'dropout_rate': 0.7165927205059781, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019083182133763817, 'min_weight_fraction_leaf': 0.16713831321323547, 'max_features': None, 'min_impurity_decrease': 6.11919023761631e-05, 'validation_fraction': 0.33082778557332754, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:43:58,340] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.6135996513302981, 'learning_rate': 0.0030759059571325367, 'dropout_rate': 0.714239153071518, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5934237823972953, 'min_weight_fraction_leaf': 0.15409787484394483, 'max_features': 1, 'min_impurity_decrease': 0.00026420223842921306, 'validation_fraction': 0.3182942803078493, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6329113924050633
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 03:44:35,064] Trial 91 finished with value: 0.7168916928997893 and parameters: {'subsample': 0.6770337747529735, 'learning_rate': 0.007750641496074201, 'dropout_rate': 0.49424724681798277, 'n_estimators': 365, 'criterion': 'friedman_mse', 'ccp_alpha': 0.15430903718460776, 'min_weight_fraction_leaf': 0.16791051943811458, 'max_features': None, 'min_impurity_decrease': 0.00012772803486333308, 'validation_fraction': 0.2316993389350888, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:44:51,998] Trial 92 finished with value: 0.5281385281385281 and parameters: {'subsample': 0.6546522174060683, 'learning_rate': 0.009421883094809201, 'dropout_rate': 0.8281440643598538, 'n_estimators': 347, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20594179048085923, 'min_weight_fraction_leaf': 0.1883593742681352, 'max_features': None, 'min_impurity_decrease': 0.0006394831666927118, 'validation_fraction': 0.2857429575523451, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 89 with value: 0.7615428784886943.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 03:45:07,957] Trial 93 finished with value: 0.7646572367824584 and parameters: {'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:45:25,049] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.5329981668085512, 'learning_rate': 0.00588357274756517, 'dropout_rate': 0.9010663710372596, 'n_estimators': 398, 'criterion': 'friedman_mse', 'ccp_alpha': 0.795356671502603, 'min_weight_fraction_leaf': 0.2746770457528657, 'max_features': None, 'min_impurity_decrease': 4.317472301123062e-05, 'validation_fraction': 0.5341505661514357, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:45:39,959] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.6002877490535967, 'learning_rate': 0.0013964687008740234, 'dropout_rate': 0.913293216331538, 'n_estimators': 380, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4770423805467064, 'min_weight_fraction_leaf': 0.23547436381465842, 'max_features': 0.1, 'min_impurity_decrease': 6.5600170925824e-05, 'validation_fraction': 0.1768997582284634, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:45:53,463] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.5679830672067219, 'learning_rate': 0.014679960066405966, 'dropout_rate': 0.9491815550373798, 'n_estimators': 409, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0851736428778953, 'min_weight_fraction_leaf': 0.2093965001338856, 'max_features': 'log2', 'min_impurity_decrease': 0.0003929451723108634, 'validation_fraction': 0.4438191336127031, 'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 93 with value: 0.7646572367824584.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:46:17,053] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.6256579983686182, 'learning_rate': 0.019674657185705456, 'dropout_rate': 0.7920862318111374, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.09841883603325133, 'max_features': None, 'min_impurity_decrease': 0.0029478086506526746, 'validation_fraction': 0.4123056392425912, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:46:40,619] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5456143354363114, 'learning_rate': 0.012065355654311702, 'dropout_rate': 0.7084124127731201, 'n_estimators': 352, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8220715155379084, 'min_weight_fraction_leaf': 0.2513160795401591, 'max_features': None, 'min_impurity_decrease': 0.00015199016859086491, 'validation_fraction': 0.337785152154958, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 93 with value: 0.7646572367824584.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-16 03:46:43,464] A new study created in memory with name: no-name-ad121fe9-1ce9-48ac-9f31-7288ccb9b4eb

Fold 5 C-index: 0.5
[I 2024-04-16 03:46:43,437] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.599460814358584, 'learning_rate': 0.0043948047101492775, 'dropout_rate': 0.5980587986289647, 'n_estimators': 93, 'criterion': 'friedman_mse', 'ccp_alpha': 6.574588525520643, 'min_weight_fraction_leaf': 0.2853352301155438, 'max_features': None, 'min_impurity_decrease': 0.0002068890339707658, 'validation_fraction': 0.4936737452445755, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 93 with value: 0.7646572367824584.


* Best trial for C-index:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.7646572367824584], datetime_start=datetime.datetime(2024, 4, 16, 3, 44, 52, 3856), datetime_complete=datetime.datetime(2024, 4, 16, 3, 45, 7, 956337), params={'subsample': 0.6128161811459047, 'learning_rate': 0.005228819896792163, 'dropout_rate': 0.9141084507237711, 'n_estimators': 395, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046986154574499193, 'min_weight_fraction_leaf': 0.2724947676380759, 'max_features': None, 'min_impurity_decrease': 0.00017501601948817654, 'validation_fraction': 0.542037097833947, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=93, value=None)


* Best Score for C-index:
 0.7646572367824584

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:47:11,696] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:47:28,329] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:47:43,014] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:48:07,820] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:48:18,542] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:48:21,128] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:48:46,413] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:48:54,265] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:48:55,087] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21267714729986278
Fold 2 IBS: 0.21995458442119498
Fold 3 IBS: 0.2035491555712707
Fold 4 IBS: 0.22393486370134422
Fold 5 IBS: 0.21704380099016626
[I 2024-04-16 03:49:57,618] Trial 9 finished with value: 0.21543191039676776 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21361208429589837
Fold 2 IBS: 0.2211926211265032
Fold 3 IBS: 0.20422163542183314
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21784292940455638
[I 2024-04-16 03:51:30,774] Trial 10 finished with value: 0.21628654622010784 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:53:18,675] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21383702367729038
Fold 2 IBS: 0.22138950456459866
Fold 3 IBS: 0.20443495965406222
Fold 4 IBS: 0.22467340762574997
Fold 5 IBS: 0.21799662270999748
[I 2024-04-16 03:54:46,560] Trial 12 finished with value: 0.21646630364633973 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 03:55:30,377] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:56:45,365] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:57:50,557] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:58:23,762] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:59:46,005] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:00:35,424] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:00:43,217] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:02:06,932] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21372933425701268
Fold 2 IBS: 0.2215356606685715
Fold 3 IBS: 0.2044331250210804
Fold 4 IBS: 0.22465964732749286
Fold 5 IBS: 0.21808855196539592
[I 2024-04-16 04:03:35,154] Trial 21 finished with value: 0.2164892638479107 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21543191039676776.
Fold 1 IBS: 0.21261860662587898
Fold 2 IBS: 0.2196324435594265

Fold 3 IBS: 0.20356521623761553
Fold 4 IBS: 0.22397661990425946
Fold 5 IBS: 0.21681927203314136
[I 2024-04-16 04:05:04,350] Trial 22 finished with value: 0.21532243167206438 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:06:23,620] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:07:10,540] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:07:58,812] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:09:08,515] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:09:16,267] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:09:40,801] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:10:36,683] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:11:02,134] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2135108348694222
Fold 2 IBS: 0.221167731954742
Fold 3 IBS: 0.20422105908762206
Fold 4 IBS: 0.22456358064764176
Fold 5 IBS: 0.21787287595995244
[I 2024-04-16 04:12:11,072] Trial 31 finished with value: 0.2162672165038761 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21277031226041587
Fold 2 IBS: 0.21977571218645117
Fold 3 IBS: 0.2037868553635057
Fold 4 IBS: 0.22437947964183458
Fold 5 IBS: 0.2169740152088292
[I 2024-04-16 04:13:22,852] Trial 32 finished with value: 0.2155372749322073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:14:15,710] Trial 33 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9175730211318314, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.23558036461669868, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 2.2672612842512112e-05, 'validation_fraction': 0.8391863465064515, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:15:09,597] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6818728654527908, 'learning_rate': 0.014570474664799389, 'dropout_rate': 0.39687420252491534, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9857366581537508, 'min_weight_fraction_leaf': 0.2451263696303153, 'max_features': 'sqrt', 'min_impurity_decrease': 7.173213136739857e-06, 'validation_fraction': 0.9231140468377321, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:15:24,544] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7474352307553052, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.29459319086620417, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 7.199479090473024e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:16:28,465] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.3498267997183648, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.2894426185614589, 'max_features': 'auto', 'min_impurity_decrease': 6.773052750173388e-05, 'validation_fraction': 0.7819324141806283, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:16:30,612] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.23919145342953393, 'max_features': None, 'min_impurity_decrease': 2.5414170052989375e-06, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:17:08,005] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8670579303141319, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.1728262906688144, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42202283765123816, 'min_weight_fraction_leaf': 0.35239546646921105, 'max_features': 'auto', 'min_impurity_decrease': 0.00017081434930634308, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:17:39,441] Trial 39 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8154589849054708, 'learning_rate': 0.006878494063124208, 'dropout_rate': 0.5323261217237781, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 1.1477698683125066, 'min_weight_fraction_leaf': 0.11023361948341703, 'max_features': 1, 'min_impurity_decrease': 1.7677159455067355e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:18:38,297] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.22290618957651392, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.5274073849776741, 'min_weight_fraction_leaf': 0.2739610635014299, 'max_features': 'auto', 'min_impurity_decrease': 2.272398816394983e-07, 'validation_fraction': 0.8717079478922802, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 22 with value: 0.21532243167206438.
Fold 1 IBS: 0.2111176339922491
Fold 2 IBS: 0.21706325506301344
Fold 3 IBS: 0.20271114308166202
Fold 4 IBS: 0.22388756035618385
Fold 5 IBS: 0.21496756928312347
[I 2024-04-16 04:19:57,781] Trial 41 finished with value: 0.21394943235524638 and parameters: {'subsample': 0.993176118879571, 'learning_rate': 0.01271988915310228, 'dropout_rate': 0.152367046323752, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.19182471840022747, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21394943235524638.
Fold 1 IBS: 0.21089915783305027
Fold 2 IBS: 0.21498627855376068
Fold 3 IBS: 0.2034648608532915
Fold 4 IBS: 0.22110504116581475
Fold 5 IBS: 0.21385442301724614
[I 2024-04-16 04:21:29,474] Trial 42 finished with value: 0.21286195228463267 and parameters: {'subsample': 0.9646924257252548, 'learning_rate': 0.012507391626216524, 'dropout_rate': 0.10802959125648778, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327408119788757, 'min_weight_fraction_leaf': 0.13510597987400375, 'max_features': 'auto', 'min_impurity_decrease': 1.0593992090305253e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:23:01,050] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828284890903175, 'learning_rate': 0.011543268886217308, 'dropout_rate': 0.11584589616484722, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.09682559138790292, 'max_features': 'auto', 'min_impurity_decrease': 1.0125868029922384e-07, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:24:14,709] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992870370700113, 'learning_rate': 0.022847552015173876, 'dropout_rate': 0.1556807870961761, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.1403134453903068, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21224782790603694
Fold 2 IBS: 0.2189260608342495
Fold 3 IBS: 0.20307124042767
Fold 4 IBS: 0.22313607826909793
Fold 5 IBS: 0.216439921823279
[I 2024-04-16 04:24:41,214] Trial 45 finished with value: 0.2147642258520667 and parameters: {'subsample': 0.8888212863898438, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.20487736976615575, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.027893207681183953, 'min_weight_fraction_leaf': 0.06753391487815072, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9448766575733668, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:24:55,272] Trial 46 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.016684121596597847, 'dropout_rate': 0.10891325683572217, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.04784747079432074, 'max_features': 0.1, 'min_impurity_decrease': 2.0166271580558924e-07, 'validation_fraction': 0.24435732275143762, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:25:17,308] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7729061863940228, 'learning_rate': 0.02995584278149796, 'dropout_rate': 0.19790330487666663, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.05716507411653311, 'max_features': 0.1, 'min_impurity_decrease': 1.0699422270078741e-07, 'validation_fraction': 0.9565097869700105, 'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:25:48,568] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8446010144291817, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.14247687075474555, 'n_estimators': 294, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 0.1, 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.8246274171002186, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:26:12,353] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6917414996198523, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.2874751071933402, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.08230947204902768, 'max_features': 0.1, 'min_impurity_decrease': 1.8211699167585496e-07, 'validation_fraction': 0.6513576271964052, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 04:26:32,939] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.019482931131151772, 'dropout_rate': 0.6676032114338903, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.013701950422388753, 'max_features': 'log2', 'min_impurity_decrease': 7.041814507237016e-07, 'validation_fraction': 0.7324600365192867, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2125423492162011
Fold 2 IBS: 0.21917859422188082
Fold 3 IBS: 0.20326597997084148
Fold 4 IBS: 0.22346421338690958
Fold 5 IBS: 0.21658511688910384
[I 2024-04-16 04:27:45,762] Trial 51 finished with value: 0.21500725073698734 and parameters: {'subsample': 0.9574902141624301, 'learning_rate': 0.013974517784402708, 'dropout_rate': 0.19663405810878032, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288632756573364, 'min_weight_fraction_leaf': 0.1845530130003769, 'max_features': 'sqrt', 'min_impurity_decrease': 5.505988736711189e-07, 'validation_fraction': 0.8981152080635156, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:29:00,503] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8963301244448798, 'learning_rate': 0.014496942793188729, 'dropout_rate': 0.149261379708028, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.3267109398107992, 'min_weight_fraction_leaf': 0.19350109364955276, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0314361105633666e-07, 'validation_fraction': 0.8673271583656655, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:29:57,860] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.937858776808653, 'learning_rate': 0.01317678110087918, 'dropout_rate': 0.20949679348390188, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.9371275797883157, 'min_weight_fraction_leaf': 0.16718449303286065, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0035393968280476e-07, 'validation_fraction': 0.9639725916044029, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:30:05,883] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5502453589475278, 'learning_rate': 0.005289059095661144, 'dropout_rate': 0.16758744743711101, 'n_estimators': 147, 'criterion': 'squared_error', 'ccp_alpha': 0.6055238018097719, 'min_weight_fraction_leaf': 0.1222904374725215, 'max_features': 'sqrt', 'min_impurity_decrease': 8.119424084486158e-07, 'validation_fraction': 0.8019436577478607, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21151156199161855
Fold 2 IBS: 0.21784621797452874

Fold 3 IBS: 0.20286393718880646
Fold 4 IBS: 0.22391249179729633
Fold 5 IBS: 0.21519882725417372
[I 2024-04-16 04:31:11,191] Trial 55 finished with value: 0.21426660724128474 and parameters: {'subsample': 0.9703353679292269, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.2676210325613897, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.036860238643527846, 'min_weight_fraction_leaf': 0.21798842867076448, 'max_features': None, 'min_impurity_decrease': 4.086647023052284e-07, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:32:02,946] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9556274374724505, 'learning_rate': 0.022777236721630217, 'dropout_rate': 0.36674252455714285, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.3101553395317078, 'min_weight_fraction_leaf': 0.21445816437013876, 'max_features': None, 'min_impurity_decrease': 4.99089267664694e-07, 'validation_fraction': 0.8444326224317742, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21286195228463267.
Fold 1 IBS: 0.2111687028051771
Fold 2 IBS: 0.2144165092431595
Fold 3 IBS: 0.20113060921449374
Fold 4 IBS: 0.22322228050971296
Fold 5 IBS: 0.21261135031718192
[I 2024-04-16 04:32:04,131] Trial 57 finished with value: 0.21250989041794505 and parameters: {'subsample': 0.9885544496318819, 'learning_rate': 0.02570846317737359, 'dropout_rate': 0.11524078732039367, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.0019474604343284706, 'min_weight_fraction_leaf': 0.1539893411018015, 'max_features': None, 'min_impurity_decrease': 3.011740016899961e-07, 'validation_fraction': 0.8976605224112223, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:32:04,624] Trial 58 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9760257284010853, 'learning_rate': 0.044170756425452734, 'dropout_rate': 0.10695167335108825, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 0.7470878188226159, 'min_weight_fraction_leaf': 0.1623750980802567, 'max_features': None, 'min_impurity_decrease': 3.402621023187449e-07, 'validation_fraction': 0.8839190525574698, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:32:08,962] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8651178500686678, 'learning_rate': 0.031729459746086146, 'dropout_rate': 0.1294932593082019, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 2.4509996240950476, 'min_weight_fraction_leaf': 0.14999314729494934, 'max_features': None, 'min_impurity_decrease': 1.564084650521852e-07, 'validation_fraction': 0.996741201133535, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:32:16,136] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9167528164906635, 'learning_rate': 0.024844206422551217, 'dropout_rate': 0.10027142034172723, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 1.5027931264041994, 'min_weight_fraction_leaf': 0.1840765520407988, 'max_features': None, 'min_impurity_decrease': 0.026115039984674165, 'validation_fraction': 0.9013568181484788, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21273370328437058
Fold 2 IBS: 0.21868788641242787
Fold 3 IBS: 0.20291275785992635
Fold 4 IBS: 0.22394573517913938
Fold 5 IBS: 0.21633996486417809
[I 2024-04-16 04:33:30,484] Trial 61 finished with value: 0.21492400952000845 and parameters: {'subsample': 0.9931174804814122, 'learning_rate': 0.016529825628647618, 'dropout_rate': 0.1935981459085364, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.0813695010094894, 'min_weight_fraction_leaf': 0.12194954374946233, 'max_features': None, 'min_impurity_decrease': 1.1729202879091808e-06, 'validation_fraction': 0.9481060427790172, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:34:45,312] Trial 62 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9972168379620757, 'learning_rate': 0.028217399882747345, 'dropout_rate': 0.1806381271548384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.3084041748420949, 'min_weight_fraction_leaf': 0.12013391362008917, 'max_features': None, 'min_impurity_decrease': 1.1386618305709938e-06, 'validation_fraction': 0.9457754330032251, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21192094947972812
Fold 2 IBS: 0.21732792727914613
Fold 3 IBS: 0.20380983776958678
Fold 4 IBS: 0.22289315056880815
Fold 5 IBS: 0.21548234130166077
[I 2024-04-16 04:34:46,471] Trial 63 finished with value: 0.21428684127978598 and parameters: {'subsample': 0.9627141857439078, 'learning_rate': 0.019891228353589942, 'dropout_rate': 0.2615796624395084, 'n_estimators': 49, 'criterion': 'squared_error', 'ccp_alpha': 0.01736018686586977, 'min_weight_fraction_leaf': 0.04375001956932725, 'max_features': None, 'min_impurity_decrease': 2.9650355903328224e-07, 'validation_fraction': 0.9569907594316491, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:34:47,333] Trial 64 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9999396727165888, 'learning_rate': 0.018638455478477044, 'dropout_rate': 0.2603466948459836, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.002024697263514, 'min_weight_fraction_leaf': 0.044141253094182736, 'max_features': None, 'min_impurity_decrease': 2.608122256111053e-07, 'validation_fraction': 0.9599786586698028, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:34:49,044] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9663925144780658, 'learning_rate': 0.037231214360123326, 'dropout_rate': 0.32454189899564956, 'n_estimators': 65, 'criterion': 'squared_error', 'ccp_alpha': 0.35061828245011545, 'min_weight_fraction_leaf': 0.000243933620821285, 'max_features': None, 'min_impurity_decrease': 1.0838199976610403e-07, 'validation_fraction': 0.9980175670026158, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:34:49,351] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9019393211486977, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.14697195606329974, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.7042671412306138, 'min_weight_fraction_leaf': 0.07018529613097008, 'max_features': None, 'min_impurity_decrease': 3.137142110783047e-07, 'validation_fraction': 0.779814650235569, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 57 with value: 0.21250989041794505.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:34:55,036] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.922035492452401, 'learning_rate': 0.02138812894899817, 'dropout_rate': 0.2208120967013012, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.09999708192212713, 'max_features': None, 'min_impurity_decrease': 1.467292826198341e-07, 'validation_fraction': 0.8460725291615868, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:34:56,852] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8097361669626262, 'learning_rate': 0.01637373351805548, 'dropout_rate': 0.2712783926055171, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.1308191878488825, 'min_weight_fraction_leaf': 0.02994710580328633, 'max_features': None, 'min_impurity_decrease': 1.0530798801381977e-06, 'validation_fraction': 0.9163895657291438, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:34:57,746] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8571881441778102, 'learning_rate': 0.0012168162419408535, 'dropout_rate': 0.42050912513013483, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 3.9712948739952747, 'min_weight_fraction_leaf': 0.12752076636262508, 'max_features': None, 'min_impurity_decrease': 4.3978604154583156e-07, 'validation_fraction': 0.964953947287593, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 57 with value: 0.21250989041794505.
Fold 1 IBS: 0.21002215842803912
Fold 2 IBS: 0.21297063105779915
Fold 3 IBS: 0.20313255536155353
Fold 4 IBS: 0.21999212755417724
Fold 5 IBS: 0.21255973126676214
[I 2024-04-16 04:35:08,879] Trial 70 finished with value: 0.21173544073366624 and parameters: {'subsample': 0.9468320464736178, 'learning_rate': 0.025309924459591012, 'dropout_rate': 0.1674120259573768, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010011659889289447, 'min_weight_fraction_leaf': 0.09294987278666268, 'max_features': None, 'min_impurity_decrease': 5.705070769293452e-06, 'validation_fraction': 0.8209425786658539, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21072608333691198
Fold 2 IBS: 0.21401453478291746
Fold 3 IBS: 0.20284454754508327
Fold 4 IBS: 0.22338804279177132
Fold 5 IBS: 0.21335338822747257
[I 2024-04-16 04:35:20,038] Trial 71 finished with value: 0.21286531933683134 and parameters: {'subsample': 0.9476651528090181, 'learning_rate': 0.024411666195060494, 'dropout_rate': 0.17430063929290213, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.026599566986409653, 'min_weight_fraction_leaf': 0.09751530095580928, 'max_features': None, 'min_impurity_decrease': 4.532054889066385e-06, 'validation_fraction': 0.8665443299833158, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:35:31,564] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9366080309436607, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.13262889403233624, 'n_estimators': 169, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6884427794811623, 'min_weight_fraction_leaf': 0.09471989813086933, 'max_features': None, 'min_impurity_decrease': 6.727144219685939e-06, 'validation_fraction': 0.7986403101682931, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:35:51,092] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8857292786754678, 'learning_rate': 0.026134449034871034, 'dropout_rate': 0.16958042534169554, 'n_estimators': 242, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3564153148878991, 'min_weight_fraction_leaf': 0.0675437991522329, 'max_features': None, 'min_impurity_decrease': 1.2822715066526718e-05, 'validation_fraction': 0.8508580960070242, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:36:00,768] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9667167267229794, 'learning_rate': 0.03460218408739485, 'dropout_rate': 0.23922069132815701, 'n_estimators': 179, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9478289085025897, 'min_weight_fraction_leaf': 0.040648200160109275, 'max_features': None, 'min_impurity_decrease': 0.0004132854571878442, 'validation_fraction': 0.9118732389838691, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.2108264636051011
Fold 2 IBS: 0.21614741779802119
Fold 3 IBS: 0.20270071891532052
Fold 4 IBS: 0.22138908682592695
Fold 5 IBS: 0.21464613153207532
[I 2024-04-16 04:36:04,003] Trial 75 finished with value: 0.21314196373528901 and parameters: {'subsample': 0.9385875657011895, 'learning_rate': 0.03024192192848759, 'dropout_rate': 0.31026391284421334, 'n_estimators': 98, 'criterion': 'friedman_mse', 'ccp_alpha': 0.008766215704230302, 'min_weight_fraction_leaf': 0.088197239599825, 'max_features': 'log2', 'min_impurity_decrease': 2.34297511452969e-05, 'validation_fraction': 0.8182037482219422, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:36:17,072] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9478601603991035, 'learning_rate': 0.029703712882555727, 'dropout_rate': 0.30760503014637186, 'n_estimators': 217, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6031244247920138, 'min_weight_fraction_leaf': 0.08521606153633404, 'max_features': 'log2', 'min_impurity_decrease': 1.826805985778275e-05, 'validation_fraction': 0.7127838617807927, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 04:36:19,514] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.834194505922225, 'learning_rate': 0.023289065494024846, 'dropout_rate': 0.5946683576609367, 'n_estimators': 105, 'criterion': 'friedman_mse', 'ccp_alpha': 5.8752783688356525, 'min_weight_fraction_leaf': 0.10946812472698092, 'max_features': 'log2', 'min_impurity_decrease': 3.863869195457471e-05, 'validation_fraction': 0.8140600247331974, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 70 with value: 0.21173544073366624.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:36:21,979] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9202091045129451, 'learning_rate': 0.019797687069268054, 'dropout_rate': 0.12670174450467558, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2910342652485194, 'min_weight_fraction_leaf': 0.15713001580184646, 'max_features': 'log2', 'min_impurity_decrease': 6.996091386072907e-06, 'validation_fraction': 0.7499357618644306, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:36:23,295] Trial 79 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9732609597246192, 'learning_rate': 0.027328730151233487, 'dropout_rate': 0.26312746311148777, 'n_estimators': 53, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3668553929390492, 'min_weight_fraction_leaf': 0.13178723776048706, 'max_features': 1, 'min_impurity_decrease': 3.5229801834435753e-06, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:36:27,823] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9344911008533908, 'learning_rate': 0.010633768390963052, 'dropout_rate': 0.3607582604573143, 'n_estimators': 130, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 'log2', 'min_impurity_decrease': 4.704228580458697e-05, 'validation_fraction': 0.8794203590137769, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.21128104502826947
Fold 2 IBS: 0.2177939632602238
Fold 3 IBS: 0.202062918285923
Fold 4 IBS: 0.2220570307012409
Fold 5 IBS: 0.215203473940832
[I 2024-04-16 04:36:30,100] Trial 81 finished with value: 0.21367968624329783 and parameters: {'subsample': 0.883668494603156, 'learning_rate': 0.0320493886753143, 'dropout_rate': 0.22584451920971726, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038423779386081554, 'min_weight_fraction_leaf': 0.06634784234748042, 'max_features': 0.1, 'min_impurity_decrease': 1.4048004741754647e-05, 'validation_fraction': 0.9236349807357848, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 70 with value: 0.21173544073366624.
Fold 1 IBS: 0.20983058110579608
Fold 2 IBS: 0.21307838506839907
Fold 3 IBS: 0.20156611960689727
Fold 4 IBS: 0.22102813568136667
Fold 5 IBS: 0.21191457851765924
[I 2024-04-16 04:36:32,419] Trial 82 finished with value: 0.2114835599960237 and parameters: {'subsample': 0.9775351216671477, 'learning_rate': 0.03625251959157783, 'dropout_rate': 0.2304960144192588, 'n_estimators': 79, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017671076422469716, 'min_weight_fraction_leaf': 0.05682074279635106, 'max_features': None, 'min_impurity_decrease': 5.222380988059964e-06, 'validation_fraction': 0.8329660882357115, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:36:34,797] Trial 83 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.980690245556926, 'learning_rate': 0.031857704007181985, 'dropout_rate': 0.22968230522988387, 'n_estimators': 80, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8197918628434602, 'min_weight_fraction_leaf': 0.057928624179806834, 'max_features': None, 'min_impurity_decrease': 1.2599470077449364e-05, 'validation_fraction': 0.7797865611811227, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:36:39,308] Trial 84 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9075135722909342, 'learning_rate': 0.03559224920264127, 'dropout_rate': 0.16623286657907432, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.512352281665378, 'min_weight_fraction_leaf': 0.10287384413406744, 'max_features': 0.1, 'min_impurity_decrease': 5.529311462542002e-06, 'validation_fraction': 0.8246387147196982, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:36:47,597] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9399767088887255, 'learning_rate': 0.04090952135292814, 'dropout_rate': 0.15193033105151865, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3342330512314949, 'min_weight_fraction_leaf': 0.08669540229802705, 'max_features': 1, 'min_impurity_decrease': 1.6658136731423827e-05, 'validation_fraction': 0.8565340610034006, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 5}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:36:49,909] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.875251314446822, 'learning_rate': 0.054611780581555074, 'dropout_rate': 0.18611522621903143, 'n_estimators': 75, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23548502503527302, 'min_weight_fraction_leaf': 0.14949731859104587, 'max_features': None, 'min_impurity_decrease': 2.4419902202859148e-05, 'validation_fraction': 0.8919356176714629, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:36:50,502] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9722232383830184, 'learning_rate': 0.0372364299275435, 'dropout_rate': 0.3020378568783464, 'n_estimators': 28, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0716748672357443, 'min_weight_fraction_leaf': 0.17652784181036787, 'max_features': 'log2', 'min_impurity_decrease': 9.189811058262566e-06, 'validation_fraction': 0.9265266924948802, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:37:07,602] Trial 88 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.45521815335975935, 'learning_rate': 0.024635453467641497, 'dropout_rate': 0.22592407076200724, 'n_estimators': 225, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5932990711529844, 'min_weight_fraction_leaf': 0.05795880477433249, 'max_features': 0.1, 'min_impurity_decrease': 0.00010910005120952281, 'validation_fraction': 0.86583149343058, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 6}. Best is trial 82 with value: 0.2114835599960237.
Fold 1 IBS: 0.20406423720489414

Fold 2 IBS: 0.20607296701907554
Fold 3 IBS: 0.19811121797640907
Fold 4 IBS: 0.22011942798029224
Fold 5 IBS: 0.20776003972546755
[I 2024-04-16 04:37:11,639] Trial 89 finished with value: 0.2072255779812277 and parameters: {'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:37:15,568] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8590448841763807, 'learning_rate': 0.04392267936156322, 'dropout_rate': 0.13081530577107772, 'n_estimators': 94, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8187200341244589, 'min_weight_fraction_leaf': 0.1356329779047198, 'max_features': None, 'min_impurity_decrease': 6.919028711702198e-05, 'validation_fraction': 0.7579364095018994, 'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2139765219514961
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:37:20,717] Trial 91 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9464598565951264, 'learning_rate': 0.033436459700910935, 'dropout_rate': 0.1074479916910401, 'n_estimators': 111, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1567080004847236, 'min_weight_fraction_leaf': 0.21909447348643799, 'max_features': None, 'min_impurity_decrease': 3.232645761160545e-05, 'validation_fraction': 0.836686056082251, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:37:26,958] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9026696667848182, 'learning_rate': 0.028827888997212704, 'dropout_rate': 0.16259306451315403, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4965227315126272, 'min_weight_fraction_leaf': 0.22285254340641944, 'max_features': None, 'min_impurity_decrease': 0.00017018904827513644, 'validation_fraction': 0.796918264996305, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 04:37:29,053] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9798482306398367, 'learning_rate': 0.031825834623114814, 'dropout_rate': 0.2049131658034791, 'n_estimators': 69, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20667716682270093, 'min_weight_fraction_leaf': 0.2585203230729044, 'max_features': None, 'min_impurity_decrease': 3.0851445660062647e-06, 'validation_fraction': 0.9763122670150756, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.2101879570260367
Fold 2 IBS: 0.21250628812533257
Fold 3 IBS: 0.20007025298318656
Fold 4 IBS: 0.22265647904327204
Fold 5 IBS: 0.21257939770958625
[I 2024-04-16 04:37:32,177] Trial 94 finished with value: 0.21160007497748282 and parameters: {'subsample': 0.9310591269229673, 'learning_rate': 0.02763334095363912, 'dropout_rate': 0.12795712192217606, 'n_estimators': 86, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05749842893076747, 'min_weight_fraction_leaf': 0.11026254544432534, 'max_features': 'auto', 'min_impurity_decrease': 5.8091196946415505e-05, 'validation_fraction': 0.9026577264245155, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:37:35,075] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9218225521402408, 'learning_rate': 0.02753178161235845, 'dropout_rate': 0.12793297330846434, 'n_estimators': 85, 'criterion': 'friedman_mse', 'ccp_alpha': 1.235276138540849, 'min_weight_fraction_leaf': 0.11051958866648452, 'max_features': 'auto', 'min_impurity_decrease': 6.515583307515859e-05, 'validation_fraction': 0.7292708592638782, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 04:37:35,848] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7993135167464014, 'learning_rate': 0.03108695961488799, 'dropout_rate': 0.14512603486936382, 'n_estimators': 24, 'criterion': 'friedman_mse', 'ccp_alpha': 0.49652833519783807, 'min_weight_fraction_leaf': 0.08008525725013409, 'max_features': 'auto', 'min_impurity_decrease': 4.444264351736355e-06, 'validation_fraction': 0.9242462136422857, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 04:37:49,071] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.845660486112679, 'learning_rate': 0.038767353066908594, 'dropout_rate': 0.18221216046279998, 'n_estimators': 200, 'criterion': 'friedman_mse', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.09201897280645036, 'max_features': 'auto', 'min_impurity_decrease': 0.0002353321351929941, 'validation_fraction': 0.8287626512220347, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 04:37:53,563] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8944546679246258, 'learning_rate': 0.036127203223985056, 'dropout_rate': 0.10388522337492916, 'n_estimators': 103, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8167233797377258, 'min_weight_fraction_leaf': 0.19553165108199336, 'max_features': 'auto', 'min_impurity_decrease': 1.7492280036351012e-05, 'validation_fraction': 0.899014721584761, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.
Fold 1 IBS: 0.21406463377160456
Fold 2 IBS: 0.22130490881763304
Fold 3 IBS: 0.20441078654944964
Fold 4 IBS: 0.2243095706255849
Fold 5 IBS: 0.21724050836884118
[I 2024-04-16 04:37:53,833] Trial 99 finished with value: 0.21626608162662264 and parameters: {'subsample': 0.24110557495742024, 'learning_rate': 0.034155925108170324, 'dropout_rate': 0.12401586667496287, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004427324419918794, 'min_weight_fraction_leaf': 0.07004102983569523, 'max_features': 'auto', 'min_impurity_decrease': 3.069838649017234e-05, 'validation_fraction': 0.6766066266445131, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 89 with value: 0.2072255779812277.


* Best trial for IBS:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.2072255779812277], datetime_start=datetime.datetime(2024, 4, 16, 4, 37, 7, 609685), datetime_complete=datetime.datetime(2024, 4, 16, 4, 37, 11, 638570), params={'subsample': 0.9081334064688743, 'learning_rate': 0.032246585462716706, 'dropout_rate': 0.10084377376256726, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019065157478907357, 'min_weight_fraction_leaf': 0.21843803937299006, 'max_features': None, 'min_impurity_decrease': 6.552978044824526e-05, 'validation_fraction': 0.8292287698601738, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=89, value=None)


* Best Score for IBS:
 0.2072255779812277

In [59]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.765
train_ibs:  0.207

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.046986154574499193,
                                 dropout_rate=0.9141084507237711,
                                 learning_rate=0.005228819896792163,
                                 max_leaf_nodes=13,
                                 min_impurity_decrease=0.00017501601948817654,
                                 min_samples_leaf=15, min_samples_split=11,
                                 min_weight_fraction_leaf=0.2724947676380759,
                                 n_estimators=395, random_state=123,
                                 subsample=0.6128161811459047,
                                 validation_fraction=0.542037097833947)

C-index score: 0.579

GradientBoostingSurvivalAnalysis(ccp_alpha=0.019065157478907357,
                                 dropout_rate=0.10084377376256726,
                                 learning_rate=0.032246585462716706,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.552978044824526e-05,
                                 min_samples_leaf=9, min_samples_split=18,
                                 min_weight_fraction_leaf=0.21843803937299006,
                                 n_estimators=92, random_state=123,
                                 subsample=0.9081334064688743,
                                 validation_fraction=0.8292287698601738)

IBS: 0.218

In [63]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [64]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 04:37:57,028] A new study created in memory with name: no-name-9b2941b4-e901-4910-830a-76fe276abdef

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:37:58,395] Trial 0 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6877154599339533.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:07,005] Trial 1 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6877154599339533.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:08,731] Trial 2 finished with value: 0.6930248564198205 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6930248564198205.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:38:10,755] Trial 3 finished with value: 0.7093480670116958 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7093480670116958.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:38:14,387] Trial 4 finished with value: 0.7147138480264469 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7147138480264469.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:18,538] Trial 5 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7147138480264469.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:20,373] Trial 6 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7147138480264469.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:21,062] Trial 7 finished with value: 0.7046240415484173 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7147138480264469.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:23,485] Trial 8 finished with value: 0.6930248564198205 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7147138480264469.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:29,482] Trial 9 finished with value: 0.6914078459792805 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7147138480264469.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:38:33,696] Trial 10 finished with value: 0.7130773315744554 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 4 with value: 0.7147138480264469.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 04:38:38,599] Trial 11 finished with value: 0.7156992389818048 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7156992389818048.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:38:42,928] Trial 12 finished with value: 0.7163352639472296 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.2495649826842376, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.7163352639472296.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:48,582] Trial 13 finished with value: 0.6920444642629577 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.7163352639472296.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:38:53,946] Trial 14 finished with value: 0.7199695842534164 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24475605651992097, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:38:58,133] Trial 15 finished with value: 0.7041532618168906 and parameters: {'subsample': 0.2913523637503245, 'dropout_rate': 0.7439425643851582, 'n_estimators': 358, 'learning_rate': 0.08616677729964022}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:05,362] Trial 16 finished with value: 0.7147138480264469 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.27752360926296893, 'n_estimators': 427, 'learning_rate': 0.09672186349880336}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:39:10,903] Trial 17 finished with value: 0.6952148233156696 and parameters: {'subsample': 0.39930407886471125, 'dropout_rate': 0.6004730897368156, 'n_estimators': 413, 'learning_rate': 0.08485124701632729}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:15,638] Trial 18 finished with value: 0.7181769104666129 and parameters: {'subsample': 0.14033791495138467, 'dropout_rate': 0.33602353085084236, 'n_estimators': 269, 'learning_rate': 0.08436585602805469}. Best is trial 14 with value: 0.7199695842534164.

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:39:18,671] Trial 19 finished with value: 0.7094407392934968 and parameters: {'subsample': 0.34314044045637715, 'dropout_rate': 0.34721836740782674, 'n_estimators': 248, 'learning_rate': 0.08042171957478578}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:39:19,629] Trial 20 finished with value: 0.7129309990337566 and parameters: {'subsample': 0.26117394341526556, 'dropout_rate': 0.18935257499862457, 'n_estimators': 112, 'learning_rate': 0.06551866052750378}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:39:23,630] Trial 21 finished with value: 0.7164354864946351 and parameters: {'subsample': 0.1237887713514979, 'dropout_rate': 0.29673189571990694, 'n_estimators': 305, 'learning_rate': 0.09466708801336095}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:27,406] Trial 22 finished with value: 0.7137334558695841 and parameters: {'subsample': 0.1871378218475938, 'dropout_rate': 0.4271322077248344, 'n_estimators': 272, 'learning_rate': 0.09078304259934762}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:33,997] Trial 23 finished with value: 0.7145773377261243 and parameters: {'subsample': 0.15413466511556917, 'dropout_rate': 0.31057026239898944, 'n_estimators': 401, 'learning_rate': 0.08178533992595556}. Best is trial 14 with value: 0.7199695842534164.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:39:39,096] Trial 24 finished with value: 0.72094756341247 and parameters: {'subsample': 0.10033650067782662, 'dropout_rate': 0.19012024616538375, 'n_estimators': 328, 'learning_rate': 0.0997124061814819}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:39:42,035] Trial 25 finished with value: 0.7147138480264469 and parameters: {'subsample': 0.2270340505999587, 'dropout_rate': 0.2057291543015094, 'n_estimators': 238, 'learning_rate': 0.09940516132075465}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:39:49,344] Trial 26 finished with value: 0.7041532618168906 and parameters: {'subsample': 0.3136211746116928, 'dropout_rate': 0.5385121428680018, 'n_estimators': 448, 'learning_rate': 0.08004450663761903}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:39:54,582] Trial 27 finished with value: 0.7084822661458949 and parameters: {'subsample': 0.4165442201849727, 'dropout_rate': 0.18266996163231589, 'n_estimators': 329, 'learning_rate': 0.07564701452340858}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:40:01,385] Trial 28 finished with value: 0.7172281210900866 and parameters: {'subsample': 0.10065550845376418, 'dropout_rate': 0.36312307549477435, 'n_estimators': 379, 'learning_rate': 0.08810813337889915}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:40:05,778] Trial 29 finished with value: 0.6903128625313559 and parameters: {'subsample': 0.6309868389458547, 'dropout_rate': 0.4175950896276197, 'n_estimators': 341, 'learning_rate': 0.06046208382653473}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:40:06,743] Trial 30 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.8739790489864521, 'dropout_rate': 0.33388796998120235, 'n_estimators': 110, 'learning_rate': 0.09080911227773146}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:40:12,967] Trial 31 finished with value: 0.7181670882262369 and parameters: {'subsample': 0.10790601188583376, 'dropout_rate': 0.36873378293260156, 'n_estimators': 385, 'learning_rate': 0.09059459302484948}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:16,852] Trial 32 finished with value: 0.7153941633056082 and parameters: {'subsample': 0.20130326541777538, 'dropout_rate': 0.2116441024250308, 'n_estimators': 282, 'learning_rate': 0.09970323575973648}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:24,636] Trial 33 finished with value: 0.7164454497580487 and parameters: {'subsample': 0.16421744878182676, 'dropout_rate': 0.48095898939081394, 'n_estimators': 437, 'learning_rate': 0.07045407323181382}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:31,549] Trial 34 finished with value: 0.7183353397761965 and parameters: {'subsample': 0.24047973147361762, 'dropout_rate': 0.1507020036667595, 'n_estimators': 394, 'learning_rate': 0.09248685625059996}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:40:41,439] Trial 35 finished with value: 0.7201671640552038 and parameters: {'subsample': 0.24430564869860838, 'dropout_rate': 0.14318162185475786, 'n_estimators': 467, 'learning_rate': 0.078368711062396}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:40:49,947] Trial 36 finished with value: 0.719186771898341 and parameters: {'subsample': 0.24962036207237454, 'dropout_rate': 0.15244785837480912, 'n_estimators': 495, 'learning_rate': 0.07693114734778606}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:40:58,204] Trial 37 finished with value: 0.7138699661699068 and parameters: {'subsample': 0.3102241791872332, 'dropout_rate': 0.14952396947409985, 'n_estimators': 478, 'learning_rate': 0.07677405503763898}. Best is trial 24 with value: 0.72094756341247.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:41:07,852] Trial 38 finished with value: 0.7068871747146159 and parameters: {'subsample': 0.5602770145716328, 'dropout_rate': 0.10259791290657247, 'n_estimators': 497, 'learning_rate': 0.045945647492717415}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:41:16,281] Trial 39 finished with value: 0.7066555791346831 and parameters: {'subsample': 0.41312772203925596, 'dropout_rate': 0.23092838775300062, 'n_estimators': 464, 'learning_rate': 0.06709978541578802}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:26,881] Trial 40 finished with value: 0.7155796488922479 and parameters: {'subsample': 0.2741503094392867, 'dropout_rate': 0.1585668555692103, 'n_estimators': 449, 'learning_rate': 0.07255507912086517}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:41:33,765] Trial 41 finished with value: 0.7172062020808259 and parameters: {'subsample': 0.22867334483761115, 'dropout_rate': 0.1377723389704344, 'n_estimators': 409, 'learning_rate': 0.09344083160052742}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:41:39,551] Trial 42 finished with value: 0.7066555791346831 and parameters: {'subsample': 0.24278068481986254, 'dropout_rate': 0.9772717282714597, 'n_estimators': 491, 'learning_rate': 0.05885954671203755}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:41:44,032] Trial 43 finished with value: 0.7065409878436212 and parameters: {'subsample': 0.3565389936701586, 'dropout_rate': 0.17589327662127627, 'n_estimators': 345, 'learning_rate': 0.03466653478137604}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:41:44,255] Trial 44 finished with value: 0.6885812607997542 and parameters: {'subsample': 0.17310567598331533, 'dropout_rate': 0.1386436364290092, 'n_estimators': 3, 'learning_rate': 0.09356119847819881}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:41:50,175] Trial 45 finished with value: 0.7137334558695841 and parameters: {'subsample': 0.19324997541708086, 'dropout_rate': 0.25842856261139674, 'n_estimators': 395, 'learning_rate': 0.07748657095111648}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:41:59,147] Trial 46 finished with value: 0.7077529755804168 and parameters: {'subsample': 0.44672323358880894, 'dropout_rate': 0.22307239289782377, 'n_estimators': 461, 'learning_rate': 0.0845077561330867}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:42:07,095] Trial 47 finished with value: 0.7012535103670149 and parameters: {'subsample': 0.31842583668586294, 'dropout_rate': 0.2821598895508856, 'n_estimators': 429, 'learning_rate': 0.008209618821055878}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:42:13,442] Trial 48 finished with value: 0.7164769115153475 and parameters: {'subsample': 0.26284290143266775, 'dropout_rate': 0.10681230061837069, 'n_estimators': 374, 'learning_rate': 0.09507583269220529}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:42:18,833] Trial 49 finished with value: 0.7137597803590877 and parameters: {'subsample': 0.14828998222317988, 'dropout_rate': 0.1906830928654944, 'n_estimators': 355, 'learning_rate': 0.0885276758212577}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:42:26,577] Trial 50 finished with value: 0.7023704128242003 and parameters: {'subsample': 0.828152658586284, 'dropout_rate': 0.13176557897562985, 'n_estimators': 414, 'learning_rate': 0.06454190679725731}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:42:30,034] Trial 51 finished with value: 0.7164891467535328 and parameters: {'subsample': 0.14572037299572574, 'dropout_rate': 0.31650282646487976, 'n_estimators': 295, 'learning_rate': 0.08381757414270803}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:42:32,548] Trial 52 finished with value: 0.7174990081852608 and parameters: {'subsample': 0.20184568250920215, 'dropout_rate': 0.2460115455469515, 'n_estimators': 220, 'learning_rate': 0.086309115641337}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:42:33,934] Trial 53 finished with value: 0.711084806011093 and parameters: {'subsample': 0.22794261658076242, 'dropout_rate': 0.7058907913530005, 'n_estimators': 165, 'learning_rate': 0.07953733896668877}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:42:39,372] Trial 54 finished with value: 0.7173330286100728 and parameters: {'subsample': 0.15826338828854958, 'dropout_rate': 0.2809977242426289, 'n_estimators': 328, 'learning_rate': 0.096805253009052}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:42:43,461] Trial 55 finished with value: 0.7173232063696967 and parameters: {'subsample': 0.12961752121082376, 'dropout_rate': 0.16637826017904325, 'n_estimators': 261, 'learning_rate': 0.07173175058651478}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:42:46,815] Trial 56 finished with value: 0.7041532618168906 and parameters: {'subsample': 0.2897019199389133, 'dropout_rate': 0.7925598471459256, 'n_estimators': 310, 'learning_rate': 0.05470827387895179}. Best is trial 24 with value: 0.72094756341247.

Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:42:55,114] Trial 57 finished with value: 0.7200110092741289 and parameters: {'subsample': 0.1014884949542427, 'dropout_rate': 0.2100741480400332, 'n_estimators': 482, 'learning_rate': 0.09296104732840711}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:03,287] Trial 58 finished with value: 0.7121113081612489 and parameters: {'subsample': 0.36815195961621516, 'dropout_rate': 0.22233753044373641, 'n_estimators': 478, 'learning_rate': 0.09713584808836097}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:43:10,292] Trial 59 finished with value: 0.7182402544965862 and parameters: {'subsample': 0.10168355957253257, 'dropout_rate': 0.6201195299866996, 'n_estimators': 449, 'learning_rate': 0.0921178263259846}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:18,855] Trial 60 finished with value: 0.717267412605328 and parameters: {'subsample': 0.24852328879174362, 'dropout_rate': 0.19392764001861174, 'n_estimators': 424, 'learning_rate': 0.08736612391583265}. Best is trial 24 with value: 0.72094756341247.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:25,313] Trial 61 finished with value: 0.7210524709324564 and parameters: {'subsample': 0.11318597139525238, 'dropout_rate': 0.678202803264672, 'n_estimators': 454, 'learning_rate': 0.09189540685240782}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:32,948] Trial 62 finished with value: 0.7138699661699068 and parameters: {'subsample': 0.1803747484279757, 'dropout_rate': 0.8162431626223988, 'n_estimators': 491, 'learning_rate': 0.09891309085521113}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:43:40,720] Trial 63 finished with value: 0.714455196169458 and parameters: {'subsample': 0.1324531025005965, 'dropout_rate': 0.4912470373302627, 'n_estimators': 468, 'learning_rate': 0.0935341921926043}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:43:48,421] Trial 64 finished with value: 0.7129822462948453 and parameters: {'subsample': 0.2087610156505575, 'dropout_rate': 0.5954569447356767, 'n_estimators': 440, 'learning_rate': 0.08172914346369861}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:43:58,556] Trial 65 finished with value: 0.7193743909904519 and parameters: {'subsample': 0.13570387779110304, 'dropout_rate': 0.126659396726635, 'n_estimators': 478, 'learning_rate': 0.09020610345238743}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:44:06,307] Trial 66 finished with value: 0.7209378796413944 and parameters: {'subsample': 0.10040778826807041, 'dropout_rate': 0.7258490529522834, 'n_estimators': 499, 'learning_rate': 0.0875727770456628}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:44:12,893] Trial 67 finished with value: 0.7182402544965862 and parameters: {'subsample': 0.10388189387180286, 'dropout_rate': 0.7145656537196764, 'n_estimators': 455, 'learning_rate': 0.08942497809080774}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:44:20,821] Trial 68 finished with value: 0.7163255801761539 and parameters: {'subsample': 0.12625105207523732, 'dropout_rate': 0.6490242402650919, 'n_estimators': 478, 'learning_rate': 0.09623401885340815}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:44:27,575] Trial 69 finished with value: 0.7163601867188146 and parameters: {'subsample': 0.16769419559103227, 'dropout_rate': 0.8096308968727537, 'n_estimators': 474, 'learning_rate': 0.08325943030699069}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:44:33,523] Trial 70 finished with value: 0.7182449394691669 and parameters: {'subsample': 0.12852299719183097, 'dropout_rate': 0.7588526082008558, 'n_estimators': 426, 'learning_rate': 0.09979840577928892}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:44:41,318] Trial 71 finished with value: 0.7147357670357077 and parameters: {'subsample': 0.18049780067359228, 'dropout_rate': 0.6863374713902003, 'n_estimators': 492, 'learning_rate': 0.08657861500189791}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:44:51,720] Trial 72 finished with value: 0.72094756341247 and parameters: {'subsample': 0.14927358511679775, 'dropout_rate': 0.12219749960465746, 'n_estimators': 497, 'learning_rate': 0.07433073247557567}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:44:59,690] Trial 73 finished with value: 0.7185817563950002 and parameters: {'subsample': 0.1415099893227872, 'dropout_rate': 0.12375140418736845, 'n_estimators': 461, 'learning_rate': 0.08994544332306645}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:45:06,586] Trial 74 finished with value: 0.7191331116394434 and parameters: {'subsample': 0.10098303061383129, 'dropout_rate': 0.7491851429465153, 'n_estimators': 482, 'learning_rate': 0.07981102106448452}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:45:14,855] Trial 75 finished with value: 0.7145283624398073 and parameters: {'subsample': 0.154935541739727, 'dropout_rate': 0.5154917592158309, 'n_estimators': 436, 'learning_rate': 0.0953608406536325}. Best is trial 61 with value: 0.7210524709324564.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:45:25,360] Trial 76 finished with value: 0.7201520635239946 and parameters: {'subsample': 0.2098593852129816, 'dropout_rate': 0.10312153965332521, 'n_estimators': 496, 'learning_rate': 0.09044759680033072}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:45:34,699] Trial 77 finished with value: 0.7164620904764766 and parameters: {'subsample': 0.2152630102225307, 'dropout_rate': 0.172440933649476, 'n_estimators': 499, 'learning_rate': 0.09223845135503929}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:45:42,168] Trial 78 finished with value: 0.7166965513494332 and parameters: {'subsample': 0.5316220997215712, 'dropout_rate': 0.10408245195692009, 'n_estimators': 457, 'learning_rate': 0.08633094669835367}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:45:46,573] Trial 79 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.8749042812122334, 'n_estimators': 413, 'learning_rate': 0.09787123572449238}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:45:54,906] Trial 80 finished with value: 0.7146378164630737 and parameters: {'subsample': 0.1826690019737381, 'dropout_rate': 0.20501168416667842, 'n_estimators': 443, 'learning_rate': 0.07511177554841489}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:46:04,464] Trial 81 finished with value: 0.7184815338475947 and parameters: {'subsample': 0.12302281677648305, 'dropout_rate': 0.12467013918898769, 'n_estimators': 482, 'learning_rate': 0.08916739252971367}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:46:12,449] Trial 82 finished with value: 0.7163450861876056 and parameters: {'subsample': 0.15366391957764408, 'dropout_rate': 0.2530916787747679, 'n_estimators': 470, 'learning_rate': 0.09210236130267954}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:46:19,315] Trial 83 finished with value: 0.715674734171858 and parameters: {'subsample': 0.19439380128838435, 'dropout_rate': 0.5674169807327712, 'n_estimators': 489, 'learning_rate': 0.09502671064789274}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:46:28,641] Trial 84 finished with value: 0.7200817625466692 and parameters: {'subsample': 0.1243309498896608, 'dropout_rate': 0.15975928158648603, 'n_estimators': 497, 'learning_rate': 0.08369422750948607}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:46:38,722] Trial 85 finished with value: 0.7181209782329437 and parameters: {'subsample': 0.11239526298352262, 'dropout_rate': 0.167651919240961, 'n_estimators': 498, 'learning_rate': 0.0782883475503193}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:46:47,560] Trial 86 finished with value: 0.6922736468450814 and parameters: {'subsample': 0.992873343787547, 'dropout_rate': 0.19730089037417953, 'n_estimators': 500, 'learning_rate': 0.08246858353428832}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 04:46:55,384] Trial 87 finished with value: 0.7182063797414783 and parameters: {'subsample': 0.17057710634662065, 'dropout_rate': 0.23741508639030898, 'n_estimators': 465, 'learning_rate': 0.03538673247962338}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:46:59,545] Trial 88 finished with value: 0.7121383644383051 and parameters: {'subsample': 0.20784809355377437, 'dropout_rate': 0.6427421643450142, 'n_estimators': 363, 'learning_rate': 0.08414721979158817}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 04:47:05,195] Trial 89 finished with value: 0.7199671712556073 and parameters: {'subsample': 0.10060851403172243, 'dropout_rate': 0.15590358153956188, 'n_estimators': 387, 'learning_rate': 0.06920936690215575}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:47:13,056] Trial 90 finished with value: 0.7147357670357077 and parameters: {'subsample': 0.28194141146747653, 'dropout_rate': 0.21557121411203772, 'n_estimators': 447, 'learning_rate': 0.08092394586731211}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:47:18,022] Trial 91 finished with value: 0.7209988106735586 and parameters: {'subsample': 0.1201828425234532, 'dropout_rate': 0.15036238225928125, 'n_estimators': 341, 'learning_rate': 0.0699253281801714}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:47:22,832] Trial 92 finished with value: 0.7146112124812323 and parameters: {'subsample': 0.14664026778615447, 'dropout_rate': 0.17973849651046261, 'n_estimators': 342, 'learning_rate': 0.07257897914315135}. Best is trial 61 with value: 0.7210524709324564.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 04:47:27,654] Trial 93 finished with value: 0.7229400889758324 and parameters: {'subsample': 0.12128259300543114, 'dropout_rate': 0.1480636402691935, 'n_estimators': 322, 'learning_rate': 0.07459322757297186}. Best is trial 93 with value: 0.7229400889758324.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 04:47:31,115] Trial 94 finished with value: 0.715418668115555 and parameters: {'subsample': 0.12386245549556994, 'dropout_rate': 0.11556701467243907, 'n_estimators': 286, 'learning_rate': 0.07420747346391231}. Best is trial 93 with value: 0.7229400889758324.

Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:47:38,882] Trial 95 finished with value: 0.7171866960693741 and parameters: {'subsample': 0.16472272061277696, 'dropout_rate': 0.15184937274296273, 'n_estimators': 485, 'learning_rate': 0.0675482915204772}. Best is trial 93 with value: 0.7229400889758324.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:47:42,818] Trial 96 finished with value: 0.7190380263598332 and parameters: {'subsample': 0.18850146409225993, 'dropout_rate': 0.1348719093177541, 'n_estimators': 322, 'learning_rate': 0.06413325090254297}. Best is trial 93 with value: 0.7229400889758324.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:47:45,509] Trial 97 finished with value: 0.7156671839062535 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.1437665485108484, 'n_estimators': 240, 'learning_rate': 0.05810785621442836}. Best is trial 93 with value: 0.7229400889758324.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 04:47:46,965] Trial 98 finished with value: 0.7212545972375237 and parameters: {'subsample': 0.1217923505896462, 'dropout_rate': 0.18851626504980173, 'n_estimators': 139, 'learning_rate': 0.07046230459294225}. Best is trial 93 with value: 0.7229400889758324.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6877637130801688

[I 2024-04-16 04:47:48,395] A new study created in memory with name: no-name-d4ab93af-32ab-408b-bbfe-ed0d742a50d9

Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 04:47:48,381] Trial 99 finished with value: 0.7154280380607162 and parameters: {'subsample': 0.13684414392716196, 'dropout_rate': 0.10071074350470147, 'n_estimators': 138, 'learning_rate': 0.07058776473081085}. Best is trial 93 with value: 0.7229400889758324.


* Best trial for C-index:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.7229400889758324], datetime_start=datetime.datetime(2024, 4, 16, 4, 47, 22, 838664), datetime_complete=datetime.datetime(2024, 4, 16, 4, 47, 27, 654186), params={'subsample': 0.12128259300543114, 'dropout_rate': 0.1480636402691935, 'n_estimators': 322, 'learning_rate': 0.07459322757297186}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=93, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.12128259300543114, 'dropout_rate': 0.1480636402691935, 'n_estimators': 322, 'learning_rate': 0.07459322757297186}


* Best Score for C-index:
 0.7229400889758324

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2390629032911732
Fold 2 IBS: 0.21956170919192733
Fold 3 IBS: 0.20377285998622766
Fold 4 IBS: 0.26017942758755347
Fold 5 IBS: 0.2006754645153689
[I 2024-04-16 04:47:49,450] Trial 0 finished with value: 0.22465047291445012 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.3010964947715816
Fold 2 IBS: 0.32141602234375205
Fold 3 IBS: 0.3044709495587033
Fold 4 IBS: 0.30221309295028626
Fold 5 IBS: 0.2978808784319514
[I 2024-04-16 04:47:58,221] Trial 1 finished with value: 0.30541548761125487 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.25281739657888197
Fold 2 IBS: 0.28450082966659795
Fold 3 IBS: 0.23729933366856826
Fold 4 IBS: 0.2841935183364194
Fold 5 IBS: 0.25381941473064
[I 2024-04-16 04:47:59,882] Trial 2 finished with value: 0.26252609859622156 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.23285875309846318
Fold 2 IBS: 0.2870302271690719
Fold 3 IBS: 0.2421321640656608
Fold 4 IBS: 0.28260084573855476
Fold 5 IBS: 0.24642892465006408
[I 2024-04-16 04:48:02,002] Trial 3 finished with value: 0.25821018294436293 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.23227352971279008
Fold 2 IBS: 0.28982223782314726
Fold 3 IBS: 0.24144052774876293
Fold 4 IBS: 0.27549321215116807
Fold 5 IBS: 0.24420381344113484
[I 2024-04-16 04:48:04,868] Trial 4 finished with value: 0.2566466641754006 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.2829269097551455
Fold 2 IBS: 0.31641454579276374
Fold 3 IBS: 0.28631221226205067
Fold 4 IBS: 0.2833121260031273
Fold 5 IBS: 0.2868040704444742
[I 2024-04-16 04:48:08,937] Trial 5 finished with value: 0.29115397285151234 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.22927167337558443
Fold 2 IBS: 0.1949307831638688
Fold 3 IBS: 0.1896534296397517
Fold 4 IBS: 0.238032022543999
Fold 5 IBS: 0.1884627677032548
[I 2024-04-16 04:48:10,593] Trial 6 finished with value: 0.20807013528529175 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20807013528529175.
Fold 1 IBS: 0.19917207033538115
Fold 2 IBS: 0.18619054231616225
Fold 3 IBS: 0.18156673272749727
Fold 4 IBS: 0.21111695163998417
Fold 5 IBS: 0.1890480623996438
[I 2024-04-16 04:48:11,016] Trial 7 finished with value: 0.1934188718837337 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.2338249443889534
Fold 2 IBS: 0.2278866200430072
Fold 3 IBS: 0.20911434993713238
Fold 4 IBS: 0.26549673049645445
Fold 5 IBS: 0.2046786172434046
[I 2024-04-16 04:48:13,091] Trial 8 finished with value: 0.2282002524217904 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.2864326153342967
Fold 2 IBS: 0.3180120028377849
Fold 3 IBS: 0.28334598236314146
Fold 4 IBS: 0.28577599689770306
Fold 5 IBS: 0.2879112422050678
[I 2024-04-16 04:48:18,223] Trial 9 finished with value: 0.2922955679275988 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.2136348878836343
Fold 2 IBS: 0.22044150933225762
Fold 3 IBS: 0.20365345601250012
Fold 4 IBS: 0.22380783373623472
Fold 5 IBS: 0.21719294266426903
[I 2024-04-16 04:48:18,509] Trial 10 finished with value: 0.2157461259257792 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.2135816062238849
Fold 2 IBS: 0.22003714542377867
Fold 3 IBS: 0.20398398550737679
Fold 4 IBS: 0.22362308945768902
Fold 5 IBS: 0.21699330092763
[I 2024-04-16 04:48:18,740] Trial 11 finished with value: 0.21564382550807187 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.2267028133007011
Fold 2 IBS: 0.26677681406815873
Fold 3 IBS: 0.2296633997154796
Fold 4 IBS: 0.2779362184309732
Fold 5 IBS: 0.2252647947987649
[I 2024-04-16 04:48:19,478] Trial 12 finished with value: 0.24526880806281554 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.2529948298742377
Fold 2 IBS: 0.25996216627225793
Fold 3 IBS: 0.2262950834675201
Fold 4 IBS: 0.2802094450909461
Fold 5 IBS: 0.23293073779715276
[I 2024-04-16 04:48:22,508] Trial 13 finished with value: 0.25047845250042294 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.20922656916850566
Fold 2 IBS: 0.19345959218725786
Fold 3 IBS: 0.18606942412604216
Fold 4 IBS: 0.20876086066030902
Fold 5 IBS: 0.1957513308119005
[I 2024-04-16 04:48:23,210] Trial 14 finished with value: 0.19865355539080304 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.21059901048825336
Fold 2 IBS: 0.21387516914377427
Fold 3 IBS: 0.1988511004470261
Fold 4 IBS: 0.218989045225747
Fold 5 IBS: 0.2119060575601521
[I 2024-04-16 04:48:23,718] Trial 15 finished with value: 0.21084407657299056 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.20937813343837747
Fold 2 IBS: 0.20315511269787834
Fold 3 IBS: 0.19176436373007055
Fold 4 IBS: 0.2120006661308366
Fold 5 IBS: 0.2030730351658097
[I 2024-04-16 04:48:24,317] Trial 16 finished with value: 0.20387426223259456 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.23556129987958843
Fold 2 IBS: 0.20350612721326378
Fold 3 IBS: 0.19535944344133163
Fold 4 IBS: 0.24667676323830406
Fold 5 IBS: 0.19227886034547353
[I 2024-04-16 04:48:25,211] Trial 17 finished with value: 0.21467649882359224 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.2232353293056551
Fold 2 IBS: 0.20650441731229416
Fold 3 IBS: 0.19556193320399556
Fold 4 IBS: 0.25179170367334425
Fold 5 IBS: 0.19194587206602404
[I 2024-04-16 04:48:28,719] Trial 18 finished with value: 0.2138078511122626 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.1934188718837337.
Fold 1 IBS: 0.19937104115294618
Fold 2 IBS: 0.18116813157886066

Fold 3 IBS: 0.18031732971026723
Fold 4 IBS: 0.20229346331647807
Fold 5 IBS: 0.1878688249525523
[I 2024-04-16 04:48:29,183] Trial 19 finished with value: 0.19020375814222087 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.19939419686684173
Fold 2 IBS: 0.18424688129359548
Fold 3 IBS: 0.18006097443217292
Fold 4 IBS: 0.2042629169306646
Fold 5 IBS: 0.18919912970114436
[I 2024-04-16 04:48:29,658] Trial 20 finished with value: 0.19143281984488383 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.2020424213729644
Fold 2 IBS: 0.1900116559329881
Fold 3 IBS: 0.18492464173289203
Fold 4 IBS: 0.20602941149660942
Fold 5 IBS: 0.1924164075400163
[I 2024-04-16 04:48:29,986] Trial 21 finished with value: 0.19508490761509406 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.21338552058692323
Fold 2 IBS: 0.21933399873094075
Fold 3 IBS: 0.20322285782084254
Fold 4 IBS: 0.22243914910086565
Fold 5 IBS: 0.2163886938377446
[I 2024-04-16 04:48:30,227] Trial 22 finished with value: 0.21495404401546336 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.20393541250817102
Fold 2 IBS: 0.20968980978145624
Fold 3 IBS: 0.19648359124307865
Fold 4 IBS: 0.24431881915184
Fold 5 IBS: 0.18570946801113553
[I 2024-04-16 04:48:31,381] Trial 23 finished with value: 0.20802742013913628 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.2071739912913989
Fold 2 IBS: 0.18832650306524928
Fold 3 IBS: 0.18453808662869903
Fold 4 IBS: 0.22733180863751976
Fold 5 IBS: 0.1861398655361952
[I 2024-04-16 04:48:31,822] Trial 24 finished with value: 0.19870205103181243 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.20033564740882
Fold 2 IBS: 0.1860816354990258
Fold 3 IBS: 0.18212148841746387
Fold 4 IBS: 0.22436013924032724
Fold 5 IBS: 0.18559449874272788
[I 2024-04-16 04:48:32,423] Trial 25 finished with value: 0.19569868186167297 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.21315633542510082
Fold 2 IBS: 0.25862352927625054
Fold 3 IBS: 0.2452924422227973
Fold 4 IBS: 0.2423178117816412
Fold 5 IBS: 0.2201653634519706
[I 2024-04-16 04:48:33,484] Trial 26 finished with value: 0.23591109643155211 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.2288353667185937
Fold 2 IBS: 0.24648055623845147
Fold 3 IBS: 0.21829348193529963
Fold 4 IBS: 0.27181565497429794
Fold 5 IBS: 0.21131486160103566
[I 2024-04-16 04:48:35,406] Trial 27 finished with value: 0.23534798429353568 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.20455881107530136
Fold 2 IBS: 0.19651001791167638
Fold 3 IBS: 0.18742221917681784
Fold 4 IBS: 0.21017588226920286
Fold 5 IBS: 0.19899807575581946
[I 2024-04-16 04:48:35,986] Trial 28 finished with value: 0.19953300123776355 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.22673353498270413
Fold 2 IBS: 0.23444301564254197
Fold 3 IBS: 0.2108410128580654
Fold 4 IBS: 0.2692285297542766
Fold 5 IBS: 0.20529516481803547
[I 2024-04-16 04:48:36,930] Trial 29 finished with value: 0.22930825161112472 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.2112851014121081
Fold 2 IBS: 0.1953892688551536
Fold 3 IBS: 0.18722980589778018
Fold 4 IBS: 0.23311292436499081
Fold 5 IBS: 0.18718370059409814
[I 2024-04-16 04:48:37,619] Trial 30 finished with value: 0.20284016022482615 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.20041254231697617
Fold 2 IBS: 0.18474711194328966
Fold 3 IBS: 0.18184291915800088
Fold 4 IBS: 0.2052301531670166
Fold 5 IBS: 0.18775682293689602
[I 2024-04-16 04:48:38,118] Trial 31 finished with value: 0.19199790990443585 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.20210321671235515
Fold 2 IBS: 0.1917890524228542
Fold 3 IBS: 0.18254394116454759
Fold 4 IBS: 0.2042511855351357
Fold 5 IBS: 0.19271426707249079
[I 2024-04-16 04:48:38,476] Trial 32 finished with value: 0.19468033258147668 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.20344721031641888
Fold 2 IBS: 0.18006681119741277
Fold 3 IBS: 0.1802682426168824
Fold 4 IBS: 0.2155578995353783
Fold 5 IBS: 0.18188076743594142
[I 2024-04-16 04:48:39,166] Trial 33 finished with value: 0.19224418622040673 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.21253441991253832
Fold 2 IBS: 0.21383322459165252
Fold 3 IBS: 0.2016522371120436
Fold 4 IBS: 0.22096470012456693
Fold 5 IBS: 0.21368891629319034
[I 2024-04-16 04:48:39,490] Trial 34 finished with value: 0.21253469960679836 and parameters: {'subsample': 0.10904251030586302, 'dropout_rate': 0.8662195064551774, 'n_estimators': 3, 'learning_rate': 0.07766566220378217}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.22487850410480956
Fold 2 IBS: 0.25864185624078445
Fold 3 IBS: 0.22478373564263512
Fold 4 IBS: 0.27724687885313853
Fold 5 IBS: 0.22303794460402743
[I 2024-04-16 04:48:40,744] Trial 35 finished with value: 0.241717783889079 and parameters: {'subsample': 0.27868485453535496, 'dropout_rate': 0.9999743696114711, 'n_estimators': 141, 'learning_rate': 0.06694317131672249}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.2865293655503679
Fold 2 IBS: 0.3204400651121318
Fold 3 IBS: 0.25851422680998154
Fold 4 IBS: 0.2690291421651172
Fold 5 IBS: 0.27583433407783836
[I 2024-04-16 04:48:46,391] Trial 36 finished with value: 0.2820694267430874 and parameters: {'subsample': 0.16326559473518704, 'dropout_rate': 0.8736174627174981, 'n_estimators': 421, 'learning_rate': 0.07993410500556083}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.22129007622832683
Fold 2 IBS: 0.2611047454226877
Fold 3 IBS: 0.2272517255532448
Fold 4 IBS: 0.27757576330208716
Fold 5 IBS: 0.2194124159677134
[I 2024-04-16 04:48:47,927] Trial 37 finished with value: 0.24132694529481197 and parameters: {'subsample': 0.23660873470356106, 'dropout_rate': 0.7990281623991888, 'n_estimators': 170, 'learning_rate': 0.05621431261796065}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.19528660008377305
Fold 2 IBS: 0.17757129115746342
Fold 3 IBS: 0.18350343023175877

Fold 4 IBS: 0.22079633279247882
Fold 5 IBS: 0.18131480238918646
[I 2024-04-16 04:48:48,682] Trial 38 finished with value: 0.1916944913309321 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 82, 'learning_rate': 0.0684395247111694}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.20327132380175603
Fold 2 IBS: 0.1860646272976219
Fold 3 IBS: 0.18261300691930407
Fold 4 IBS: 0.22057437433061436
Fold 5 IBS: 0.17996732471500895
[I 2024-04-16 04:48:49,642] Trial 39 finished with value: 0.19449813141286104 and parameters: {'subsample': 0.167666800643059, 'dropout_rate': 0.11471626893495929, 'n_estimators': 100, 'learning_rate': 0.050430345636818495}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.21673605085523345
Fold 2 IBS: 0.20773333805344843
Fold 3 IBS: 0.1943367194227906
Fold 4 IBS: 0.25172158643558845
Fold 5 IBS: 0.19362593239547257
[I 2024-04-16 04:48:50,322] Trial 40 finished with value: 0.21283072543250672 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.27073406810212547, 'n_estimators': 78, 'learning_rate': 0.07230355488087334}. Best is trial 19 with value: 0.19020375814222087.
Fold 1 IBS: 0.1911140754484728
Fold 2 IBS: 0.17497898719575516
Fold 3 IBS: 0.1782878262763377
Fold 4 IBS: 0.20076781355078874
Fold 5 IBS: 0.17864143724459983
[I 2024-04-16 04:48:50,851] Trial 41 finished with value: 0.18475802794319085 and parameters: {'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 56, 'learning_rate': 0.06615161558436967}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20178709223595984
Fold 2 IBS: 0.1918028902260198
Fold 3 IBS: 0.18250719754438235
Fold 4 IBS: 0.20599307045430545
Fold 5 IBS: 0.19354205491491172
[I 2024-04-16 04:48:51,242] Trial 42 finished with value: 0.19512646107511583 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.19807687454956896, 'n_estimators': 25, 'learning_rate': 0.05946433946285823}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20135668776327942
Fold 2 IBS: 0.19145611338933421
Fold 3 IBS: 0.18309353279127083
Fold 4 IBS: 0.2375650751030165
Fold 5 IBS: 0.18650896866548233
[I 2024-04-16 04:48:51,734] Trial 43 finished with value: 0.19999607554247664 and parameters: {'subsample': 0.31451686904054643, 'dropout_rate': 0.286459714252547, 'n_estimators': 50, 'learning_rate': 0.08722773956368673}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2145209320698076
Fold 2 IBS: 0.2544962261781162
Fold 3 IBS: 0.2422018207642364
Fold 4 IBS: 0.2629344963630248
Fold 5 IBS: 0.21245270379214776
[I 2024-04-16 04:48:53,903] Trial 44 finished with value: 0.23732123583346657 and parameters: {'subsample': 0.13055820393157166, 'dropout_rate': 0.17293718310640144, 'n_estimators': 207, 'learning_rate': 0.06474202539730971}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.21649912710818864
Fold 2 IBS: 0.23456698454272545
Fold 3 IBS: 0.21538127673107232
Fold 4 IBS: 0.25621238834007126
Fold 5 IBS: 0.20465883518233177
[I 2024-04-16 04:48:54,796] Trial 45 finished with value: 0.2254637223808779 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.32993790334399276, 'n_estimators': 115, 'learning_rate': 0.07226468386460667}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20395167303046755
Fold 2 IBS: 0.1890118498272731
Fold 3 IBS: 0.182131300890417
Fold 4 IBS: 0.21730231131691294
Fold 5 IBS: 0.18254441802942406
[I 2024-04-16 04:48:55,423] Trial 46 finished with value: 0.19498831061889893 and parameters: {'subsample': 0.2002446053403005, 'dropout_rate': 0.20488129986163572, 'n_estimators': 80, 'learning_rate': 0.05378014293554952}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2190015423628283
Fold 2 IBS: 0.21556466756285259
Fold 3 IBS: 0.19872029662151056
Fold 4 IBS: 0.2544437779370119
Fold 5 IBS: 0.1958241681837921
[I 2024-04-16 04:48:56,948] Trial 47 finished with value: 0.2167108905335991 and parameters: {'subsample': 0.4539729299901746, 'dropout_rate': 0.1137868207525379, 'n_estimators': 178, 'learning_rate': 0.03623350794651181}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20534383834621087
Fold 2 IBS: 0.20011736164126762
Fold 3 IBS: 0.1894525589987643
Fold 4 IBS: 0.20799144065685587
Fold 5 IBS: 0.20195376644710936
[I 2024-04-16 04:48:57,251] Trial 48 finished with value: 0.20097179321804162 and parameters: {'subsample': 0.14176620493513847, 'dropout_rate': 0.23624837489749712, 'n_estimators': 18, 'learning_rate': 0.04963128845882498}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20913059174311785
Fold 2 IBS: 0.19483894257611842
Fold 3 IBS: 0.18703059953286108
Fold 4 IBS: 0.2090049359812372
Fold 5 IBS: 0.197084788125313
[I 2024-04-16 04:48:57,651] Trial 49 finished with value: 0.19941797159172953 and parameters: {'subsample': 0.7553314841676608, 'dropout_rate': 0.4477251063775791, 'n_estimators': 45, 'learning_rate': 0.027854287270829683}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.24699985178347886
Fold 2 IBS: 0.2896030778057612
Fold 3 IBS: 0.23880162708735178
Fold 4 IBS: 0.28047487440652136
Fold 5 IBS: 0.24617500700868203
[I 2024-04-16 04:48:59,316] Trial 50 finished with value: 0.26041088761835907 and parameters: {'subsample': 0.3116445257158518, 'dropout_rate': 0.9501582476866339, 'n_estimators': 230, 'learning_rate': 0.05744040508254814}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20535482554422785
Fold 2 IBS: 0.18077263064122356
Fold 3 IBS: 0.18049808759362615
Fold 4 IBS: 0.2123382650420431
Fold 5 IBS: 0.18269307062697357
[I 2024-04-16 04:48:59,796] Trial 51 finished with value: 0.19233137588961885 and parameters: {'subsample': 0.1037796415557007, 'dropout_rate': 0.9055146088732016, 'n_estimators': 60, 'learning_rate': 0.06727417418455452}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2031070500971631
Fold 2 IBS: 0.20026089487348672
Fold 3 IBS: 0.1888143398624426
Fold 4 IBS: 0.2256087409529685
Fold 5 IBS: 0.18783019731904707
[I 2024-04-16 04:49:00,360] Trial 52 finished with value: 0.2011242446210216 and parameters: {'subsample': 0.12783858791476446, 'dropout_rate': 0.8365358212171242, 'n_estimators': 75, 'learning_rate': 0.07041469798450695}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2658432308909655
Fold 2 IBS: 0.3095434542745772
Fold 3 IBS: 0.24837626498124776
Fold 4 IBS: 0.2660232311614936
Fold 5 IBS: 0.26022240078419223
[I 2024-04-16 04:49:03,065] Trial 53 finished with value: 0.27000171641849524 and parameters: {'subsample': 0.18479902345983845, 'dropout_rate': 0.7422242234921752, 'n_estimators': 276, 'learning_rate': 0.07799857986827735}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2025910069127024
Fold 2 IBS: 0.2016071455265028
Fold 3 IBS: 0.18876505754265135
Fold 4 IBS: 0.20798173981435256
Fold 5 IBS: 0.20313587097226882
[I 2024-04-16 04:49:03,383] Trial 54 finished with value: 0.20081616415369558 and parameters: {'subsample': 0.15551396623635025, 'dropout_rate': 0.1464738011208001, 'n_estimators': 15, 'learning_rate': 0.06395919407607914}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20490470825749074
Fold 2 IBS: 0.19467426781022992
Fold 3 IBS: 0.18616669809103487
Fold 4 IBS: 0.23299304995400635
Fold 5 IBS: 0.1867743360016876
[I 2024-04-16 04:49:04,322] Trial 55 finished with value: 0.2011026120228899 and parameters: {'subsample': 0.2200813218232155, 'dropout_rate': 0.957476987777337, 'n_estimators': 98, 'learning_rate': 0.046428364049978674}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19897933787317632
Fold 2 IBS: 0.1798940946400149
Fold 3 IBS: 0.17824905514020298
Fold 4 IBS: 0.20663804676187925
Fold 5 IBS: 0.18278299765058975
[I 2024-04-16 04:49:04,851] Trial 56 finished with value: 0.18930870641317266 and parameters: {'subsample': 0.13629518296961038, 'dropout_rate': 0.33203458853352996, 'n_estimators': 56, 'learning_rate': 0.05200376729332816}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19780944936172942
Fold 2 IBS: 0.18714628927386306
Fold 3 IBS: 0.18182170824400878

Fold 4 IBS: 0.21074415529612286
Fold 5 IBS: 0.1906046318704369
[I 2024-04-16 04:49:05,279] Trial 57 finished with value: 0.19362524680923224 and parameters: {'subsample': 0.28485371898030076, 'dropout_rate': 0.3370257678588191, 'n_estimators': 46, 'learning_rate': 0.04080281648872289}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20640882920127823
Fold 2 IBS: 0.21970370169967193
Fold 3 IBS: 0.20347320840945904
Fold 4 IBS: 0.24194717585947562
Fold 5 IBS: 0.19629748402177308
[I 2024-04-16 04:49:06,492] Trial 58 finished with value: 0.21356607983833156 and parameters: {'subsample': 0.19606868118391554, 'dropout_rate': 0.4330958753331916, 'n_estimators': 132, 'learning_rate': 0.052258567546562856}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2038886528943842
Fold 2 IBS: 0.1930918304872145
Fold 3 IBS: 0.18612714224929136
Fold 4 IBS: 0.20691981144697325
Fold 5 IBS: 0.19686372158553128
[I 2024-04-16 04:49:07,039] Trial 59 finished with value: 0.19737823173267893 and parameters: {'subsample': 0.13610206285037016, 'dropout_rate': 0.5065802886056728, 'n_estimators': 32, 'learning_rate': 0.035865148200113134}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2028144121778981
Fold 2 IBS: 0.1843732562662734
Fold 3 IBS: 0.18031436361980283
Fold 4 IBS: 0.21522093672387613
Fold 5 IBS: 0.1859074095411817
[I 2024-04-16 04:49:07,698] Trial 60 finished with value: 0.1937260756658064 and parameters: {'subsample': 0.3436490623188294, 'dropout_rate': 0.5729007954079746, 'n_estimators': 85, 'learning_rate': 0.031026604764965958}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.1955258220884635
Fold 2 IBS: 0.17946826098340762
Fold 3 IBS: 0.1792465641858841
Fold 4 IBS: 0.2046087442395433
Fold 5 IBS: 0.177395337913849
[I 2024-04-16 04:49:08,237] Trial 61 finished with value: 0.1872489458822295 and parameters: {'subsample': 0.10679744561442364, 'dropout_rate': 0.28856501571166426, 'n_estimators': 61, 'learning_rate': 0.06023293882453683}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19715917353686901
Fold 2 IBS: 0.1825871434596979
Fold 3 IBS: 0.18173775529478756
Fold 4 IBS: 0.20531468079877307
Fold 5 IBS: 0.1814680816297551
[I 2024-04-16 04:49:08,761] Trial 62 finished with value: 0.18965336694397653 and parameters: {'subsample': 0.13045617335374393, 'dropout_rate': 0.384205130207357, 'n_estimators': 63, 'learning_rate': 0.05918636209984516}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19706857170372397
Fold 2 IBS: 0.18257286803900086
Fold 3 IBS: 0.18063994329449037
Fold 4 IBS: 0.21313184028675794
Fold 5 IBS: 0.1812271998555686
[I 2024-04-16 04:49:09,506] Trial 63 finished with value: 0.19092808463590832 and parameters: {'subsample': 0.1413006091951437, 'dropout_rate': 0.3148485356592517, 'n_estimators': 67, 'learning_rate': 0.06009363847576362}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20998278776573326
Fold 2 IBS: 0.22032812545911237
Fold 3 IBS: 0.20112213799724796
Fold 4 IBS: 0.25051161890197693
Fold 5 IBS: 0.1980894920077834
[I 2024-04-16 04:49:10,467] Trial 64 finished with value: 0.21600683242637078 and parameters: {'subsample': 0.24731001152415089, 'dropout_rate': 0.37033144774094295, 'n_estimators': 107, 'learning_rate': 0.062049332343317054}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20405475022351138
Fold 2 IBS: 0.21358523816238711
Fold 3 IBS: 0.2023578690889885
Fold 4 IBS: 0.25351055401915956
Fold 5 IBS: 0.19502236539458467
[I 2024-04-16 04:49:12,026] Trial 65 finished with value: 0.21370615537772625 and parameters: {'subsample': 0.17644011205647003, 'dropout_rate': 0.3049263175877496, 'n_estimators': 157, 'learning_rate': 0.04629334565720654}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19935218061752483
Fold 2 IBS: 0.1808921376744384
Fold 3 IBS: 0.17844141230895305
Fold 4 IBS: 0.20790739104616948
Fold 5 IBS: 0.1820637906182816
[I 2024-04-16 04:49:12,595] Trial 66 finished with value: 0.18973138245307347 and parameters: {'subsample': 0.1376721186264562, 'dropout_rate': 0.3967096050573773, 'n_estimators': 57, 'learning_rate': 0.053026165568476155}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20190708760643458
Fold 2 IBS: 0.18664683176072908
Fold 3 IBS: 0.179781905234109
Fold 4 IBS: 0.2130975075319752
Fold 5 IBS: 0.18374207368985104
[I 2024-04-16 04:49:13,387] Trial 67 finished with value: 0.1930350811646198 and parameters: {'subsample': 0.21067079438353736, 'dropout_rate': 0.410189122539049, 'n_estimators': 64, 'learning_rate': 0.05934683193290041}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20558108489930854
Fold 2 IBS: 0.20592496446177241
Fold 3 IBS: 0.19481717001017776
Fold 4 IBS: 0.21273604138871488
Fold 5 IBS: 0.20697830318102947
[I 2024-04-16 04:49:13,722] Trial 68 finished with value: 0.20520751278820062 and parameters: {'subsample': 0.1298241304818003, 'dropout_rate': 0.23158452784464134, 'n_estimators': 11, 'learning_rate': 0.053989181853632676}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.23537181903041382
Fold 2 IBS: 0.217704540938004
Fold 3 IBS: 0.2027545579012953
Fold 4 IBS: 0.2590120300806659
Fold 5 IBS: 0.19951440775682602
[I 2024-04-16 04:49:14,795] Trial 69 finished with value: 0.222871471141441 and parameters: {'subsample': 0.688769098505249, 'dropout_rate': 0.3680197667171009, 'n_estimators': 119, 'learning_rate': 0.05181048869334336}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2588135372534692
Fold 2 IBS: 0.3127338619967369
Fold 3 IBS: 0.2502162322124793
Fold 4 IBS: 0.2640547312166586
Fold 5 IBS: 0.26456881297792956
[I 2024-04-16 04:49:20,762] Trial 70 finished with value: 0.27007743513145466 and parameters: {'subsample': 0.18018041725103612, 'dropout_rate': 0.3110642068888335, 'n_estimators': 408, 'learning_rate': 0.05875030375366056}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20032779771284356
Fold 2 IBS: 0.18544864965630772
Fold 3 IBS: 0.18166101776932114
Fold 4 IBS: 0.20503160251332625
Fold 5 IBS: 0.18870283923851044
[I 2024-04-16 04:49:21,254] Trial 71 finished with value: 0.1922343813780618 and parameters: {'subsample': 0.13228637899524676, 'dropout_rate': 0.48331603136351514, 'n_estimators': 41, 'learning_rate': 0.04423635630888599}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19623062123139304
Fold 2 IBS: 0.18104292070993105
Fold 3 IBS: 0.17848699711055035
Fold 4 IBS: 0.20592437752565312
Fold 5 IBS: 0.18209753695809805
[I 2024-04-16 04:49:21,871] Trial 72 finished with value: 0.18875649070712514 and parameters: {'subsample': 0.15754033689972852, 'dropout_rate': 0.34653211617604557, 'n_estimators': 61, 'learning_rate': 0.04914822572537582}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.1963858854147491
Fold 2 IBS: 0.1822642872719468
Fold 3 IBS: 0.17778068318980852
Fold 4 IBS: 0.21200137695502805
Fold 5 IBS: 0.18192012440439015
[I 2024-04-16 04:49:23,222] Trial 73 finished with value: 0.19007047144718453 and parameters: {'subsample': 0.14880104433181973, 'dropout_rate': 0.40215482952289044, 'n_estimators': 67, 'learning_rate': 0.04809056419549487}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20062741355631367
Fold 2 IBS: 0.1851598384787913
Fold 3 IBS: 0.1799259883784975
Fold 4 IBS: 0.2200597315486105
Fold 5 IBS: 0.18438186756773883
[I 2024-04-16 04:49:24,710] Trial 74 finished with value: 0.19403096790599034 and parameters: {'subsample': 0.2243346517220972, 'dropout_rate': 0.3889420006011026, 'n_estimators': 93, 'learning_rate': 0.03861832106381912}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19681939517785715
Fold 2 IBS: 0.1808890830617878
Fold 3 IBS: 0.17879195177144275
Fold 4 IBS: 0.20719583130777605
Fold 5 IBS: 0.18230855063572893
[I 2024-04-16 04:49:25,259] Trial 75 finished with value: 0.18920096239091852 and parameters: {'subsample': 0.1621028278145516, 'dropout_rate': 0.34163132072065266, 'n_estimators': 58, 'learning_rate': 0.04850847995266458}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.23239812093567871
Fold 2 IBS: 0.2942713734174749
Fold 3 IBS: 0.25040788148862925

Fold 4 IBS: 0.2655628587347858
Fold 5 IBS: 0.24910597908314874
[I 2024-04-16 04:49:29,166] Trial 76 finished with value: 0.2583492427319435 and parameters: {'subsample': 0.1646209356841326, 'dropout_rate': 0.34829268282242476, 'n_estimators': 327, 'learning_rate': 0.049901380557131274}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.1998737329020388
Fold 2 IBS: 0.1821880269405455
Fold 3 IBS: 0.17751263839597953
Fold 4 IBS: 0.20328626032175104
Fold 5 IBS: 0.18402116294409254
[I 2024-04-16 04:49:29,842] Trial 77 finished with value: 0.18937636430088148 and parameters: {'subsample': 0.19315658624676152, 'dropout_rate': 0.41228050639999003, 'n_estimators': 61, 'learning_rate': 0.04804835804038757}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20852668374519195
Fold 2 IBS: 0.23735501182444488
Fold 3 IBS: 0.21460136039744784
Fold 4 IBS: 0.25259421140638694
Fold 5 IBS: 0.19523514029924452
[I 2024-04-16 04:49:31,072] Trial 78 finished with value: 0.22166248153454324 and parameters: {'subsample': 0.19878203031407987, 'dropout_rate': 0.2504065124936709, 'n_estimators': 132, 'learning_rate': 0.06434399876214902}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2054602865189835
Fold 2 IBS: 0.20874906013264063
Fold 3 IBS: 0.19208257393885578
Fold 4 IBS: 0.24081813355272527
Fold 5 IBS: 0.18831713809161502
[I 2024-04-16 04:49:32,009] Trial 79 finished with value: 0.20708543844696403 and parameters: {'subsample': 0.25526388761510654, 'dropout_rate': 0.2685530192234324, 'n_estimators': 106, 'learning_rate': 0.054387157047844095}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20096338567340102
Fold 2 IBS: 0.1845233435492689
Fold 3 IBS: 0.18063510901557514
Fold 4 IBS: 0.2168409992545736
Fold 5 IBS: 0.18504131404573698
[I 2024-04-16 04:49:32,652] Trial 80 finished with value: 0.1936008303077111 and parameters: {'subsample': 0.29284300364250615, 'dropout_rate': 0.4745844592837749, 'n_estimators': 56, 'learning_rate': 0.04414229297870615}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20054022437812052
Fold 2 IBS: 0.19091779673402515
Fold 3 IBS: 0.18317831878340132
Fold 4 IBS: 0.20489358273261557
Fold 5 IBS: 0.19537447535566022
[I 2024-04-16 04:49:33,061] Trial 81 finished with value: 0.19498087959676455 and parameters: {'subsample': 0.152675976643256, 'dropout_rate': 0.4207570456056533, 'n_estimators': 32, 'learning_rate': 0.047878542071542324}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19472015591487593
Fold 2 IBS: 0.17914418211244984
Fold 3 IBS: 0.17923701493211155
Fold 4 IBS: 0.2039370577075127
Fold 5 IBS: 0.18169409939036396
[I 2024-04-16 04:49:33,734] Trial 82 finished with value: 0.18774650201146278 and parameters: {'subsample': 0.12072037153700343, 'dropout_rate': 0.3776141272286026, 'n_estimators': 71, 'learning_rate': 0.04822888015387897}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19540791676416447
Fold 2 IBS: 0.18058157105937853
Fold 3 IBS: 0.1807953588075537
Fold 4 IBS: 0.20515111682967307
Fold 5 IBS: 0.1815882015921587
[I 2024-04-16 04:49:34,450] Trial 83 finished with value: 0.18870483301058572 and parameters: {'subsample': 0.12200953932496786, 'dropout_rate': 0.3826967903478372, 'n_estimators': 73, 'learning_rate': 0.052617074717089}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19575675617118793
Fold 2 IBS: 0.1859008462228372
Fold 3 IBS: 0.18455842330869968
Fold 4 IBS: 0.20475547769650468
Fold 5 IBS: 0.1811449997735214
[I 2024-04-16 04:49:35,292] Trial 84 finished with value: 0.19042330063455018 and parameters: {'subsample': 0.1195935590681641, 'dropout_rate': 0.2925242872967888, 'n_estimators': 87, 'learning_rate': 0.05624724717726185}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2068045403879261
Fold 2 IBS: 0.20117404602849398
Fold 3 IBS: 0.1906201859833064
Fold 4 IBS: 0.21040873926660872
Fold 5 IBS: 0.20239744552242847
[I 2024-04-16 04:49:35,613] Trial 85 finished with value: 0.20228099143775274 and parameters: {'subsample': 0.18514228247893036, 'dropout_rate': 0.3616940225616209, 'n_estimators': 17, 'learning_rate': 0.050122239488867154}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20242099536303812
Fold 2 IBS: 0.18454340124451873
Fold 3 IBS: 0.1765275441916745
Fold 4 IBS: 0.21294819241448032
Fold 5 IBS: 0.18516376335416065
[I 2024-04-16 04:49:36,015] Trial 86 finished with value: 0.19232077931357444 and parameters: {'subsample': 0.22120554171826196, 'dropout_rate': 0.32669852183185116, 'n_estimators': 37, 'learning_rate': 0.06307910110547874}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19581516569555618
Fold 2 IBS: 0.18351737843916271
Fold 3 IBS: 0.18292268409590892
Fold 4 IBS: 0.20816208355905183
Fold 5 IBS: 0.18132374772734922
[I 2024-04-16 04:49:36,779] Trial 87 finished with value: 0.19034821190340576 and parameters: {'subsample': 0.11913503168191295, 'dropout_rate': 0.3798476890919854, 'n_estimators': 76, 'learning_rate': 0.057477858333394645}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20770792774418415
Fold 2 IBS: 0.23260271976182567
Fold 3 IBS: 0.21245255493172724
Fold 4 IBS: 0.25644232139998535
Fold 5 IBS: 0.20271442437018675
[I 2024-04-16 04:49:38,431] Trial 88 finished with value: 0.22238398964158185 and parameters: {'subsample': 0.169624635776763, 'dropout_rate': 0.4472174547490143, 'n_estimators': 192, 'learning_rate': 0.042758746294361986}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.2135246018423622
Fold 2 IBS: 0.22023960601369844
Fold 3 IBS: 0.20391236122773454
Fold 4 IBS: 0.22375878338513608
Fold 5 IBS: 0.21704820381057804
[I 2024-04-16 04:49:38,661] Trial 89 finished with value: 0.21569671125590184 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.3496565115487822, 'n_estimators': 1, 'learning_rate': 0.04680245577894845}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20958734057586487
Fold 2 IBS: 0.184890547642549
Fold 3 IBS: 0.1805585923379692
Fold 4 IBS: 0.21408155129139664
Fold 5 IBS: 0.1867862204088767
[I 2024-04-16 04:49:39,128] Trial 90 finished with value: 0.1951808504513313 and parameters: {'subsample': 0.4325048890578308, 'dropout_rate': 0.20230125851812022, 'n_estimators': 52, 'learning_rate': 0.05223948802536306}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19583195175510043
Fold 2 IBS: 0.1796221564127449
Fold 3 IBS: 0.1808102423205376
Fold 4 IBS: 0.2047426569410127
Fold 5 IBS: 0.18110381768315523
[I 2024-04-16 04:49:39,667] Trial 91 finished with value: 0.18842216502251014 and parameters: {'subsample': 0.12030423258025734, 'dropout_rate': 0.42883641151401564, 'n_estimators': 68, 'learning_rate': 0.05456089285979797}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19533325619441222
Fold 2 IBS: 0.18087488607181806
Fold 3 IBS: 0.1809679662072558
Fold 4 IBS: 0.20113845854618745
Fold 5 IBS: 0.17970604490784295
[I 2024-04-16 04:49:40,234] Trial 92 finished with value: 0.1876041223855033 and parameters: {'subsample': 0.12103897475399356, 'dropout_rate': 0.28790172385101864, 'n_estimators': 72, 'learning_rate': 0.054471205994865934}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19774887528819812
Fold 2 IBS: 0.18644923328915133
Fold 3 IBS: 0.18200810674316756
Fold 4 IBS: 0.21121377178453848
Fold 5 IBS: 0.17781252723454857
[I 2024-04-16 04:49:40,965] Trial 93 finished with value: 0.19104650286792083 and parameters: {'subsample': 0.10124784422162728, 'dropout_rate': 0.24914739590587986, 'n_estimators': 94, 'learning_rate': 0.055027291361053984}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20114194582253495
Fold 2 IBS: 0.19285473000793274
Fold 3 IBS: 0.18471993302025388
Fold 4 IBS: 0.22579266923504585
Fold 5 IBS: 0.18421229294945088
[I 2024-04-16 04:49:41,765] Trial 94 finished with value: 0.19774431420704366 and parameters: {'subsample': 0.1643798095164442, 'dropout_rate': 0.2852339966947825, 'n_estimators': 108, 'learning_rate': 0.049063522909236976}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.22091663880530082
Fold 2 IBS: 0.18657213840426012
Fold 3 IBS: 0.18458621378198437

Fold 4 IBS: 0.22455751043206135
Fold 5 IBS: 0.1864269492522418
[I 2024-04-16 04:49:42,311] Trial 95 finished with value: 0.20061189013516972 and parameters: {'subsample': 0.7904534140423415, 'dropout_rate': 0.47309863500802474, 'n_estimators': 73, 'learning_rate': 0.04523657899468575}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.1960426079693441
Fold 2 IBS: 0.18418750895722966
Fold 3 IBS: 0.18357522731713158
Fold 4 IBS: 0.2056289060119681
Fold 5 IBS: 0.180314304167688
[I 2024-04-16 04:49:43,033] Trial 96 finished with value: 0.1899497108846723 and parameters: {'subsample': 0.1206876526650317, 'dropout_rate': 0.33764757365017084, 'n_estimators': 89, 'learning_rate': 0.05220949056295454}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.20530136961518963
Fold 2 IBS: 0.19194160718916256
Fold 3 IBS: 0.18472656896670164
Fold 4 IBS: 0.20871255663478866
Fold 5 IBS: 0.19409039803864542
[I 2024-04-16 04:49:43,344] Trial 97 finished with value: 0.19695450008889762 and parameters: {'subsample': 0.5606440507914384, 'dropout_rate': 0.4245767866059678, 'n_estimators': 23, 'learning_rate': 0.0656297243537445}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19779899234565096
Fold 2 IBS: 0.18403206027078267
Fold 3 IBS: 0.17636378391024668
Fold 4 IBS: 0.20534405688771212
Fold 5 IBS: 0.1824274721133885
[I 2024-04-16 04:49:43,772] Trial 98 finished with value: 0.1891932731055562 and parameters: {'subsample': 0.20275196871448345, 'dropout_rate': 0.22396087436354034, 'n_estimators': 51, 'learning_rate': 0.06126308891451149}. Best is trial 41 with value: 0.18475802794319085.
Fold 1 IBS: 0.19445073052798223
Fold 2 IBS: 0.18124897228711667
Fold 3 IBS: 0.17435824682936316
Fold 4 IBS: 0.19919277336140775
Fold 5 IBS: 0.18587669761601053
[I 2024-04-16 04:49:44,186] Trial 99 finished with value: 0.18702548412437608 and parameters: {'subsample': 0.15240258621276287, 'dropout_rate': 0.21934256834977656, 'n_estimators': 42, 'learning_rate': 0.0613903313037644}. Best is trial 41 with value: 0.18475802794319085.


* Best trial for IBS:
 FrozenTrial(number=41, state=TrialState.COMPLETE, values=[0.18475802794319085], datetime_start=datetime.datetime(2024, 4, 16, 4, 48, 50, 326266), datetime_complete=datetime.datetime(2024, 4, 16, 4, 48, 50, 851251), params={'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 56, 'learning_rate': 0.06615161558436967}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=41, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 56, 'learning_rate': 0.06615161558436967}


* Best Score for IBS:
 0.18475802794319085

In [65]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.723
train_ibs:  0.185

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.1480636402691935,
                                              learning_rate=0.07459322757297186,
                                              n_estimators=322,
                                              random_state=123,
                                              subsample=0.12128259300543114)

C-index score: 0.565

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.24159494757459665,
                                              learning_rate=0.06615161558436967,
                                              n_estimators=56, random_state=123,
                                              subsample=0.10774190635914782)

IBS: 0.231

In [69]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [70]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.846   1.0
ExtraSurvivalTrees               0.791   2.0
GradientBoosting                 0.765   3.0
CoxElastic                       0.744   4.0
CoxLasso                         0.742   5.0
CoxPH                            0.741   6.0
CoxRidge                         0.723   7.5
ComponentwiseGradientBoosting    0.723   7.5

In [71]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.171   1.0
CoxPH                          0.175   3.0
CoxLasso                       0.175   3.0
CoxElastic                     0.175   3.0
ExtraSurvivalTrees             0.176   5.0
ComponentwiseGradientBoosting  0.185   6.0
GradientBoosting               0.207   7.0
CoxRidge                       0.217   8.0

In [72]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.602   1.0
GradientBoosting                 0.579   2.0
ExtraSurvivalTrees               0.572   3.0
CoxRidge                         0.570   4.0
ComponentwiseGradientBoosting    0.565   5.0
CoxLasso                         0.561   6.0
CoxPH                            0.560   7.5
CoxElastic                       0.560   7.5

In [73]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
GradientBoosting               0.218   1.0
CoxRidge                       0.221   2.5
ExtraSurvivalTrees             0.221   2.5
ComponentwiseGradientBoosting  0.231   4.0
Randomsurvivalforest           0.233   5.0
CoxLasso                       0.262   6.5
CoxElastic                     0.262   6.5
CoxPH                          0.264   8.0

In [76]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/yeojohnson/rent/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_yeojohnson_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [77]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-16