In [4]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import PowerTransformer

In [5]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [6]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [7]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [8]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [9]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [10]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [11]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [12]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [13]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [14]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [15]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [16]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

In [17]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [18]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [19]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [20]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

# Feature Selection

In [21]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"first_order_Maximum_CT",                            
"LBP_201_PET",                              
"LBP_102_PET",                                
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2",
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16",  
"LBP_003_PET",                 
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04"         
]

In [22]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [23]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Yeo-Johnson Transformation

In [24]:
# Copy the original X for later 
original_X = X.copy()

In [25]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [26]:
X_new

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04
0,1763.283818,0.000062,0.000000,0.000959,0.000416,0.000123,0.001395
1,1432.109636,0.000349,0.000000,0.002776,0.001753,0.000349,0.002345
2,1685.931373,0.000000,0.000034,0.001179,0.000230,0.000000,0.001105
3,1329.347515,0.000000,0.000000,0.002748,0.000711,0.000300,0.002088
4,1197.225910,0.000399,0.000199,0.002309,0.001033,0.000000,0.002042
...,...,...,...,...,...,...,...
134,1267.959716,0.000000,0.000000,0.001347,0.000226,0.000000,0.001878
135,1788.278096,0.000079,0.000000,0.000850,0.000183,0.000039,0.000770
136,1478.297861,0.000000,0.000000,0.001111,0.000621,0.000000,0.001743
137,1207.068493,0.000054,0.000000,0.000935,0.000265,0.000000,0.001283
138,1368.499199,0.000000,0.000000,0.000629,0.000421,0.000000,0.001413

In [27]:
X_new_std

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04
0,1.022943,-0.074611,-0.784694,-0.456825,-0.128003,1.042615,-0.301870
1,0.072727,1.689445,-0.784694,1.829690,1.761655,1.929439,1.172866
2,0.853782,-1.065926,0.236612,0.033412,-0.861897,-0.799521,-1.042887
3,-0.390532,-1.065926,-0.784694,1.814149,0.668885,1.846691,0.881234
4,-1.187658,1.782787,1.784568,1.522029,1.208077,-0.799521,0.822455
...,...,...,...,...,...,...,...
134,-0.727488,-1.065926,-0.784694,0.352487,-0.877225,-0.799521,0.592895
135,1.072604,0.138716,-0.784694,-0.735470,-1.082845,-0.000653,-2.156858
136,0.247868,-1.065926,-0.784694,-0.108155,0.464990,-0.799521,0.378812
137,-1.118344,-0.175482,-0.784694,-0.515193,-0.706059,-0.799521,-0.567395
138,-0.200688,-1.065926,-0.784694,-1.381293,-0.112899,-0.799521,-0.260764

In [28]:
MAASTRO_new

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04
0,1226.795917,0.000026,0.000026,0.000768,0.000241,0.000026,0.001101
1,1876.570382,0.000167,0.000167,0.001213,0.000621,0.000056,0.001861
2,1269.217095,0.000000,0.000057,0.001176,0.000327,0.000286,0.001353
3,1951.924395,0.000080,0.000000,0.001192,0.001419,0.000160,0.001420
4,1646.853670,0.000035,0.000000,0.000766,0.000165,0.000071,0.001340
...,...,...,...,...,...,...,...
94,2311.845731,0.000078,0.000000,0.001137,0.000739,0.000000,0.001765
95,1299.857157,0.000054,0.000000,0.000962,0.001130,0.000109,0.001594
96,1256.024949,0.000028,0.000000,0.000621,0.000226,0.000000,0.001435
97,1668.742962,0.000000,0.000000,0.000947,0.000296,0.000114,0.001167
98,1654.841840,0.000112,0.000000,0.001661,0.001394,0.000000,0.002038

In [29]:
MAASTRO_new_std

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04
0,-0.984802,-0.597387,0.033184,-0.960377,-0.811666,-0.238970,-1.054082
1,1.231237,0.946684,1.682719,0.101598,0.464229,0.263801,0.566401
2,-0.720051,-1.065926,0.693043,0.027699,-0.453072,1.817599,-0.397642
3,1.348682,0.152800,-0.784694,0.060650,1.579512,1.314752,-0.245977
4,0.758335,-0.453142,-0.784694,-0.967045,-1.171859,0.471935,-0.428826
...,...,...,...,...,...,...,...
94,1.750433,0.126817,-0.784694,-0.052777,0.727222,-0.799521,0.414211
95,-0.545966,-0.173978,-0.784694,-0.450240,1.322893,0.907497,0.110883
96,-0.799285,-0.565019,-0.784694,-1.409205,-0.877027,-0.799521,-0.214415
97,0.812692,-1.065926,-0.784694,-0.485449,-0.577241,0.962590,-0.869387
98,0.778442,0.498900,-0.784694,0.840017,1.561904,-0.799521,0.817194

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [30]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:30:44,582] A new study created in memory with name: no-name-72da8fdb-0417-4904-b0cb-76e6e5887dea

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6118143459915611

[I 2024-04-16 01:31:04,373] A new study created in memory with name: no-name-48b13c95-2cea-4ab5-87fd-47cfff6279ed

Fold 5 C-index: 0.6572769953051644
[I 2024-04-16 01:31:04,215] Trial 0 finished with value: 0.655724940018958 and parameters: {}. Best is trial 0 with value: 0.655724940018958.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.655724940018958], datetime_start=datetime.datetime(2024, 4, 16, 1, 30, 44, 721169), datetime_complete=datetime.datetime(2024, 4, 16, 1, 31, 4, 213597), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.655724940018958

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1969409117307865
Fold 2 IBS: 0.19322839929322455
Fold 3 IBS: 0.18516741534279244
Fold 4 IBS: 0.21493247358260703
Fold 5 IBS: 0.2410128885614412
[I 2024-04-16 01:31:06,938] Trial 0 finished with value: 0.20625641770217035 and parameters: {}. Best is trial 0 with value: 0.20625641770217035.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20625641770217035], datetime_start=datetime.datetime(2024, 4, 16, 1, 31, 4, 739152), datetime_complete=datetime.datetime(2024, 4, 16, 1, 31, 6, 937766), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20625641770217035

In [31]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [32]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.656
train_ibs:  0.206

#### Test

In [33]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [34]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.591
IBS score: 0.238

In [35]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [36]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [37]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:31:07,541] A new study created in memory with name: no-name-7835e9c1-e3c5-453e-9ceb-6cf5ffe68947

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5952380952380952
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7009803921568627

[I 2024-04-16 01:31:08,855] A new study created in memory with name: no-name-2787e164-89cb-4cda-8116-08cbebbd03fd

Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 01:31:08,840] Trial 0 finished with value: 0.6753341218819494 and parameters: {}. Best is trial 0 with value: 0.6753341218819494.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6753341218819494], datetime_start=datetime.datetime(2024, 4, 16, 1, 31, 7, 608955), datetime_complete=datetime.datetime(2024, 4, 16, 1, 31, 8, 840070), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6753341218819494

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651842800988
Fold 2 IBS: 0.2215779102658637
Fold 3 IBS: 0.20453594230284272
Fold 4 IBS: 0.22473803637388992
Fold 5 IBS: 0.2181243145661695
[I 2024-04-16 01:31:10,143] Trial 0 finished with value: 0.21659054438735512 and parameters: {}. Best is trial 0 with value: 0.21659054438735512.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054438735512], datetime_start=datetime.datetime(2024, 4, 16, 1, 31, 8, 948603), datetime_complete=datetime.datetime(2024, 4, 16, 1, 31, 10, 143210), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054438735512

In [38]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [39]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.675
train_ibs:  0.217

#### Test

In [40]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [41]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.616

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [42]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [43]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:31:10,775] A new study created in memory with name: no-name-aa49804d-348c-4bda-97f4-c315f9e3e208

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608

[I 2024-04-16 01:31:12,919] A new study created in memory with name: no-name-e7a16b48-7e34-4d90-b650-a9ff5b11ee18

Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:12,908] Trial 0 finished with value: 0.656846527448724 and parameters: {}. Best is trial 0 with value: 0.656846527448724.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.656846527448724], datetime_start=datetime.datetime(2024, 4, 16, 1, 31, 10, 854919), datetime_complete=datetime.datetime(2024, 4, 16, 1, 31, 12, 908363), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.656846527448724

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.19602106389596613
Fold 2 IBS: 0.19297396519554105
Fold 3 IBS: 0.18513419898365446
Fold 4 IBS: 0.2142933165670212
Fold 5 IBS: 0.24022040689201665
[I 2024-04-16 01:31:14,621] Trial 0 finished with value: 0.2057285903068399 and parameters: {}. Best is trial 0 with value: 0.2057285903068399.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2057285903068399], datetime_start=datetime.datetime(2024, 4, 16, 1, 31, 12, 960465), datetime_complete=datetime.datetime(2024, 4, 16, 1, 31, 14, 620758), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2057285903068399

In [44]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [45]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.657
train_ibs:  0.206

#### Test

In [46]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [47]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.59

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.237

In [48]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [49]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:31:15,429] A new study created in memory with name: no-name-5f29fad6-9da7-45d9-bc35-ff6d943f8a5e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:16,903] Trial 0 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:18,091] Trial 1 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:19,510] Trial 2 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:20,847] Trial 3 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:22,755] Trial 4 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:24,448] Trial 5 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:26,193] Trial 6 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:27,629] Trial 7 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:28,915] Trial 8 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:30,419] Trial 9 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:32,580] Trial 10 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:31:35,528] Trial 11 finished with value: 0.6568004174554309 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:31:37,672] Trial 12 finished with value: 0.6559075603125738 and parameters: {'l1_ratio': 0.21309581087335225}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:39,334] Trial 13 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.743964055575976}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:31:41,210] Trial 14 finished with value: 0.6559075603125738 and parameters: {'l1_ratio': 0.21599024455432275}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:42,891] Trial 15 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.820763570686791}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:44,638] Trial 16 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5880713606511995}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:46,363] Trial 17 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.35870521424355084}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:31:48,012] Trial 18 finished with value: 0.6569627551177686 and parameters: {'l1_ratio': 0.039318771596377255}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:49,949] Trial 19 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:51,694] Trial 20 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:54,661] Trial 21 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5622777690744459}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:57,508] Trial 22 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.3009019596824227}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:31:59,482] Trial 23 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.4865569413362957}. Best is trial 0 with value: 0.6577123283145249.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:01,280] Trial 24 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6776130739315861}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:03,852] Trial 25 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.8125286485497188}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:07,169] Trial 26 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5421167620714675}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:13,310] Trial 27 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.2976713250593102}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:16,613] Trial 28 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6342068365021416}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:32:19,765] Trial 29 finished with value: 0.6559075603125738 and parameters: {'l1_ratio': 0.18481656054890608}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:32:21,763] Trial 30 finished with value: 0.6568004174554309 and parameters: {'l1_ratio': 0.12339967209204172}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:24,786] Trial 31 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7574725530566742}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:29,507] Trial 32 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.458175553098962}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:32,634] Trial 33 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.9061337786354179}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:35,058] Trial 34 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.660618494567812}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:37,171] Trial 35 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7320335285284623}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:41,000] Trial 36 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5411641129675752}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:45,112] Trial 37 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.41127726993914593}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:47,773] Trial 38 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.33191384388765355}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:49,516] Trial 39 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7098130986581438}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:51,373] Trial 40 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.793304273599382}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:53,661] Trial 41 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.4287851816179317}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:55,691] Trial 42 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5144152599052498}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:32:57,581] Trial 43 finished with value: 0.6559075603125738 and parameters: {'l1_ratio': 0.25330979530211034}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:32:59,584] Trial 44 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.36689388384954924}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:02,251] Trial 45 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6219684827438303}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:33:05,363] Trial 46 finished with value: 0.6568004174554309 and parameters: {'l1_ratio': 0.12556540721097253}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:07,861] Trial 47 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.9012636151017558}. Best is trial 0 with value: 0.6577123283145249.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:11,235] Trial 48 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.45330460100324665}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:13,313] Trial 49 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.587848527895132}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:15,270] Trial 50 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5027665121167861}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:16,681] Trial 51 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.694004713951571}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:18,625] Trial 52 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7478912680033778}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:21,707] Trial 53 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6678161974576081}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:24,751] Trial 54 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.8430583174090551}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:26,627] Trial 55 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.7802203497183832}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:29,147] Trial 56 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5736232918831691}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:31,225] Trial 57 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:33,145] Trial 58 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.3684411570360776}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:35,147] Trial 59 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6530141946722856}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:37,082] Trial 60 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7073757579947153}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:39,125] Trial 61 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.4577454793817965}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:42,117] Trial 62 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.2583320804553656}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:44,029] Trial 63 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5384220114163092}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:46,872] Trial 64 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.4080339845545922}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:49,473] Trial 65 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.486051159158366}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:52,011] Trial 66 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.3169229839630441}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:54,471] Trial 67 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.9546530799943637}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:56,673] Trial 68 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5975340062034576}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:33:58,275] Trial 69 finished with value: 0.6559075603125738 and parameters: {'l1_ratio': 0.18942581039571943}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:33:59,954] Trial 70 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.844897554684938}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:02,540] Trial 71 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.4065421074393218}. Best is trial 0 with value: 0.6577123283145249.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:04,817] Trial 72 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.3433260444556416}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:07,094] Trial 73 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.2861490355881364}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:09,722] Trial 74 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.3898481847136749}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:12,749] Trial 75 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5236339451369274}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:15,811] Trial 76 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.47792229576091144}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:18,193] Trial 77 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.7743363529944591}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:20,424] Trial 78 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7283854796904858}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:22,504] Trial 79 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.44707136583780255}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:24,027] Trial 80 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6865272525760148}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:25,361] Trial 81 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5600212168693921}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:26,690] Trial 82 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.803394691222761}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:28,032] Trial 83 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.7189265167931088}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:29,935] Trial 84 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6588106083240816}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:31,875] Trial 85 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.7649059232193953}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:33,605] Trial 86 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.43088772431712613}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:35,834] Trial 87 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.3756652360553012}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:37,987] Trial 88 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6353097804875939}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:39,721] Trial 89 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.744749840110277}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:42,089] Trial 90 finished with value: 0.656846527448724 and parameters: {'l1_ratio': 0.8244362242058821}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:44,384] Trial 91 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.573980051949883}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:46,523] Trial 92 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6123358545755949}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:48,358] Trial 93 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5078319286031037}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:50,303] Trial 94 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6443073241211696}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:52,242] Trial 95 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5352425228383729}. Best is trial 0 with value: 0.6577123283145249.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:54,568] Trial 96 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.6890568386027802}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:57,454] Trial 97 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.46976896501542753}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:34:59,974] Trial 98 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5515024393031553}. Best is trial 0 with value: 0.6577123283145249.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608

[I 2024-04-16 01:35:02,197] A new study created in memory with name: no-name-9e3d0542-9e51-4386-b63c-c4c4693a280c

Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:35:02,158] Trial 99 finished with value: 0.6577123283145249 and parameters: {'l1_ratio': 0.5858129260267456}. Best is trial 0 with value: 0.6577123283145249.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6577123283145249], datetime_start=datetime.datetime(2024, 4, 16, 1, 31, 15, 461765), datetime_complete=datetime.datetime(2024, 4, 16, 1, 31, 16, 903225), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.6577123283145249

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19607426324452154
Fold 2 IBS: 0.19291796526379473
Fold 3 IBS: 0.18513414094859856
Fold 4 IBS: 0.2142802941958011
Fold 5 IBS: 0.24013371045108928
[I 2024-04-16 01:35:04,995] Trial 0 finished with value: 0.20570807482076106 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.20570807482076106.
Fold 1 IBS: 0.196178160147061
Fold 2 IBS: 0.19276640490872884
Fold 3 IBS: 0.18513928059360607
Fold 4 IBS: 0.21431143617525175
Fold 5 IBS: 0.23981444334062385
[I 2024-04-16 01:35:07,336] Trial 1 finished with value: 0.2056419450330543 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.2056419450330543.
Fold 1 IBS: 0.19617043924369143
Fold 2 IBS: 0.1927536401284449
Fold 3 IBS: 0.1851412757034659
Fold 4 IBS: 0.2142832189636069
Fold 5 IBS: 0.23966506215978026
[I 2024-04-16 01:35:10,032] Trial 2 finished with value: 0.20560272723979792 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.19612864791569834
Fold 2 IBS: 0.19288347180001747
Fold 3 IBS: 0.1851349578469668
Fold 4 IBS: 0.2142828746532766
Fold 5 IBS: 0.24003929403131533
[I 2024-04-16 01:35:12,843] Trial 3 finished with value: 0.20569384924945494 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.19607592687934813
Fold 2 IBS: 0.1929259688941429
Fold 3 IBS: 0.18513386617624453
Fold 4 IBS: 0.2142875366381616
Fold 5 IBS: 0.240076675362669
[I 2024-04-16 01:35:15,074] Trial 4 finished with value: 0.20569999479011325 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.19615017504133214
Fold 2 IBS: 0.19283406447699739
Fold 3 IBS: 0.18513645557741476
Fold 4 IBS: 0.21432518913259094
Fold 5 IBS: 0.23989950223342416
[I 2024-04-16 01:35:17,525] Trial 5 finished with value: 0.20566907729235187 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.196020307751351
Fold 2 IBS: 0.19297012783664202
Fold 3 IBS: 0.18513433354005127
Fold 4 IBS: 0.21428989454625721
Fold 5 IBS: 0.24020871157948026
[I 2024-04-16 01:35:19,689] Trial 6 finished with value: 0.20572467505075634 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.19607338145313138
Fold 2 IBS: 0.19291372032074539
Fold 3 IBS: 0.18513428956262346
Fold 4 IBS: 0.21427644887809374
Fold 5 IBS: 0.240121692153823
[I 2024-04-16 01:35:22,827] Trial 7 finished with value: 0.20570390647368336 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.19611107545025486
Fold 2 IBS: 0.19287391066261947
Fold 3 IBS: 0.18513642034514613
Fold 4 IBS: 0.2143046191696506
Fold 5 IBS: 0.2399214000530156
[I 2024-04-16 01:35:25,463] Trial 8 finished with value: 0.2056694851361373 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.19613121915043952
Fold 2 IBS: 0.19284259904031678
Fold 3 IBS: 0.18513746789666063
Fold 4 IBS: 0.21430304054573257
Fold 5 IBS: 0.23992552730339436
[I 2024-04-16 01:35:28,651] Trial 9 finished with value: 0.20566797078730875 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.20560272723979792.
Fold 1 IBS: 0.19626246759538338
Fold 2 IBS: 0.19265713767011713
Fold 3 IBS: 0.18514748819040472
Fold 4 IBS: 0.21429263323286793
Fold 5 IBS: 0.23950448275790923
[I 2024-04-16 01:35:32,044] Trial 10 finished with value: 0.20557284188933647 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.20557284188933647.
Fold 1 IBS: 0.21355449162837645
Fold 2 IBS: 0.22076022560160116
Fold 3 IBS: 0.20393910375396407
Fold 4 IBS: 0.22414493020805126
Fold 5 IBS: 0.2180471996323647
[I 2024-04-16 01:35:33,263] Trial 11 finished with value: 0.21608919016487152 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.20557284188933647.
Fold 1 IBS: 0.1962620220774823
Fold 2 IBS: 0.19265662162652028
Fold 3 IBS: 0.18514750582553013
Fold 4 IBS: 0.214292119158027
Fold 5 IBS: 0.23950303231338765
[I 2024-04-16 01:35:35,579] Trial 12 finished with value: 0.20557226020018948 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.20557226020018948.
Fold 1 IBS: 0.21386452051842889
Fold 2 IBS: 0.2213586691896521
Fold 3 IBS: 0.2043767047825539
Fold 4 IBS: 0.2245789104608679
Fold 5 IBS: 0.21810276976185058
[I 2024-04-16 01:35:37,055] Trial 13 finished with value: 0.21645631494267067 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.20557226020018948.
Fold 1 IBS: 0.19619332898601502
Fold 2 IBS: 0.19268283397034844
Fold 3 IBS: 0.18514306929251328
Fold 4 IBS: 0.21431994597147822
Fold 5 IBS: 0.23958263944934044
[I 2024-04-16 01:35:39,307] Trial 14 finished with value: 0.20558436353393908 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.20557226020018948.
Fold 1 IBS: 0.19619854243488166
Fold 2 IBS: 0.192689054480333
Fold 3 IBS: 0.1851428919007746
Fold 4 IBS: 0.21432557266583455
Fold 5 IBS: 0.23959992483023704
[I 2024-04-16 01:35:41,743] Trial 15 finished with value: 0.20559119726241218 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.20557226020018948.
Fold 1 IBS: 0.1962291818912243
Fold 2 IBS: 0.1926984040349273
Fold 3 IBS: 0.1851440257015728
Fold 4 IBS: 0.2142919295492764
Fold 5 IBS: 0.23962454781305195
[I 2024-04-16 01:35:43,994] Trial 16 finished with value: 0.20559761779801056 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.20557226020018948.
Fold 1 IBS: 0.19611556198439162
Fold 2 IBS: 0.19277232194196625
Fold 3 IBS: 0.18513908101007462
Fold 4 IBS: 0.21431662160448955
Fold 5 IBS: 0.23983045377522058
[I 2024-04-16 01:35:46,408] Trial 17 finished with value: 0.2056348080632285 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.20557226020018948.
Fold 1 IBS: 0.19627479083365804
Fold 2 IBS: 0.19263992095512278
Fold 3 IBS: 0.18514853240176352
Fold 4 IBS: 0.21429028636986602
Fold 5 IBS: 0.2394533224481656
[I 2024-04-16 01:35:48,913] Trial 18 finished with value: 0.2055613706017152 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.1960207894956766
Fold 2 IBS: 0.19297257282333286
Fold 3 IBS: 0.1851342476266908
Fold 4 IBS: 0.21429207515878057
Fold 5 IBS: 0.2402161641568296
[I 2024-04-16 01:35:50,996] Trial 19 finished with value: 0.2057271698522621 and parameters: {'l1_ratio': 0.9929377968859474}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19618715330082992
Fold 2 IBS: 0.19273369813386443
Fold 3 IBS: 0.18514048559768387
Fold 4 IBS: 0.21430279169876307
Fold 5 IBS: 0.23972545468556672
[I 2024-04-16 01:35:53,837] Trial 20 finished with value: 0.20561791668334156 and parameters: {'l1_ratio': 0.2388879688839749}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19626836244005408
Fold 2 IBS: 0.19266396506845312
Fold 3 IBS: 0.18514725891004266
Fold 4 IBS: 0.21429942992873885
Fold 5 IBS: 0.23952362749724782
[I 2024-04-16 01:35:56,129] Trial 21 finished with value: 0.20558052876890728 and parameters: {'l1_ratio': 0.08499433228302328}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19625088457257436
Fold 2 IBS: 0.19262728438726417
Fold 3 IBS: 0.1851487690120147
Fold 4 IBS: 0.21432575440369186
Fold 5 IBS: 0.23955317417828417
[I 2024-04-16 01:35:58,615] Trial 22 finished with value: 0.20558117331076584 and parameters: {'l1_ratio': 0.07181511589086235}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19618098729461783
Fold 2 IBS: 0.19273055692992444
Fold 3 IBS: 0.18514226681995175
Fold 4 IBS: 0.21427898920788593
Fold 5 IBS: 0.23971522206740958
[I 2024-04-16 01:36:00,856] Trial 23 finished with value: 0.20560960446395793 and parameters: {'l1_ratio': 0.1944040617022983}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19616031578405224
Fold 2 IBS: 0.19279224854965818
Fold 3 IBS: 0.18513792338078264
Fold 4 IBS: 0.2143115789104835
Fold 5 IBS: 0.23988378584672002
[I 2024-04-16 01:36:02,803] Trial 24 finished with value: 0.2056571704943393 and parameters: {'l1_ratio': 0.3389201479305571}. Best is trial 18 with value: 0.2055613706017152.

Fold 1 IBS: 0.19628000561567796
Fold 2 IBS: 0.19264591971385459
Fold 3 IBS: 0.18514833426583724
Fold 4 IBS: 0.21429629848935952
Fold 5 IBS: 0.23947026387589404
[I 2024-04-16 01:36:05,611] Trial 25 finished with value: 0.20556816439212464 and parameters: {'l1_ratio': 0.06766854141508033}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.21344889697661673
Fold 2 IBS: 0.22055908509104202
Fold 3 IBS: 0.2037910348514832
Fold 4 IBS: 0.22399916798848396
Fold 5 IBS: 0.2180296410983425
[I 2024-04-16 01:36:07,447] Trial 26 finished with value: 0.21596556520119367 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19606397051451482
Fold 2 IBS: 0.19289942457205242
Fold 3 IBS: 0.18513444210503735
Fold 4 IBS: 0.21429747009648822
Fold 5 IBS: 0.23999853978081567
[I 2024-04-16 01:36:09,923] Trial 27 finished with value: 0.2056787694137817 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19619516189222672
Fold 2 IBS: 0.19274770468460348
Fold 3 IBS: 0.1851416034140456
Fold 4 IBS: 0.21429556247492876
Fold 5 IBS: 0.23964657295584385
[I 2024-04-16 01:36:12,810] Trial 28 finished with value: 0.2056053210843297 and parameters: {'l1_ratio': 0.2025095518368651}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.1960159875826378
Fold 2 IBS: 0.1929713467922112
Fold 3 IBS: 0.18513513354490038
Fold 4 IBS: 0.2143284100591657
Fold 5 IBS: 0.24021576290625074
[I 2024-04-16 01:36:14,875] Trial 29 finished with value: 0.2057333281770332 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19614579800396412
Fold 2 IBS: 0.19280993776132938
Fold 3 IBS: 0.18513862229988867
Fold 4 IBS: 0.2142945560750869
Fold 5 IBS: 0.23983114977073394
[I 2024-04-16 01:36:17,292] Trial 30 finished with value: 0.20564401278220062 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.1962406247924908
Fold 2 IBS: 0.19264995453075404
Fold 3 IBS: 0.18514751670437174
Fold 4 IBS: 0.21433170074144742
Fold 5 IBS: 0.23948561752601724
[I 2024-04-16 01:36:21,650] Trial 31 finished with value: 0.2055710828590162 and parameters: {'l1_ratio': 0.09097907947672834}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19623773943208447
Fold 2 IBS: 0.19262848535414318
Fold 3 IBS: 0.18514713353655804
Fold 4 IBS: 0.21432005309796875
Fold 5 IBS: 0.2395576354054875
[I 2024-04-16 01:36:25,909] Trial 32 finished with value: 0.20557820936524843 and parameters: {'l1_ratio': 0.07922695094417607}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19619343899503225
Fold 2 IBS: 0.19268296523774953
Fold 3 IBS: 0.18514306549607257
Fold 4 IBS: 0.21432006478270105
Fold 5 IBS: 0.2395830044638512
[I 2024-04-16 01:36:29,663] Trial 33 finished with value: 0.2055845077950813 and parameters: {'l1_ratio': 0.14358749610091265}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.19617691290694228
Fold 2 IBS: 0.1927615442948234
Fold 3 IBS: 0.18514096229141092
Fold 4 IBS: 0.2142908094059546
Fold 5 IBS: 0.2396884858747092
[I 2024-04-16 01:36:32,685] Trial 34 finished with value: 0.20561174295476808 and parameters: {'l1_ratio': 0.2314284199378912}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.1962504574458707
Fold 2 IBS: 0.19266139174121824
Fold 3 IBS: 0.1851471013769531
Fold 4 IBS: 0.21428793679306216
Fold 5 IBS: 0.23951771700298205
[I 2024-04-16 01:36:35,747] Trial 35 finished with value: 0.20557292087201723 and parameters: {'l1_ratio': 0.09309939685392626}. Best is trial 18 with value: 0.2055613706017152.
Fold 1 IBS: 0.1962944221180483
Fold 2 IBS: 0.19261439730407545
Fold 3 IBS: 0.18515204182132922
Fold 4 IBS: 0.2142881513427703
Fold 5 IBS: 0.2393765636150463
[I 2024-04-16 01:36:38,170] Trial 36 finished with value: 0.20554511524025393 and parameters: {'l1_ratio': 0.043525712831569995}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19615463374727005
Fold 2 IBS: 0.19269865885296122
Fold 3 IBS: 0.18514202161597315
Fold 4 IBS: 0.21430606048340708
Fold 5 IBS: 0.23962757155108505
[I 2024-04-16 01:36:41,100] Trial 37 finished with value: 0.20558578925013932 and parameters: {'l1_ratio': 0.18080250866157638}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19614587862443497
Fold 2 IBS: 0.19276445921220464
Fold 3 IBS: 0.1851394866277082
Fold 4 IBS: 0.21427356665209166
Fold 5 IBS: 0.2396976695478177
[I 2024-04-16 01:36:43,652] Trial 38 finished with value: 0.20560421213285146 and parameters: {'l1_ratio': 0.25762236529737026}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21265955097113545
Fold 2 IBS: 0.1926242132936972
Fold 3 IBS: 0.18515187208060094
Fold 4 IBS: 0.2143026055980088
Fold 5 IBS: 0.2394035859124699
[I 2024-04-16 01:36:46,516] Trial 39 finished with value: 0.20882836557118245 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19601120585864498
Fold 2 IBS: 0.19294899207296234
Fold 3 IBS: 0.18513445130642214
Fold 4 IBS: 0.21430831430882752
Fold 5 IBS: 0.2401474838961764
[I 2024-04-16 01:36:48,797] Trial 40 finished with value: 0.20571008948860667 and parameters: {'l1_ratio': 0.7945008862812031}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19626252093156005
Fold 2 IBS: 0.19259920161194022
Fold 3 IBS: 0.18515070534535905
Fold 4 IBS: 0.21431824758286255
Fold 5 IBS: 0.23947637379172176
[I 2024-04-16 01:36:51,631] Trial 41 finished with value: 0.20556140985268873 and parameters: {'l1_ratio': 0.05116837163227956}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19630425969095983
Fold 2 IBS: 0.1926357885956864
Fold 3 IBS: 0.18515113328535396
Fold 4 IBS: 0.21430473377149348
Fold 5 IBS: 0.23943832488395755
[I 2024-04-16 01:36:55,142] Trial 42 finished with value: 0.20556684804549025 and parameters: {'l1_ratio': 0.0498437485348308}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21295554926278398
Fold 2 IBS: 0.21963693918499724
Fold 3 IBS: 0.1851521620378701
Fold 4 IBS: 0.22333157206759516
Fold 5 IBS: 0.23941792485657015
[I 2024-04-16 01:36:58,180] Trial 43 finished with value: 0.21609882948196332 and parameters: {'l1_ratio': 0.030714642624077103}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962278498961892
Fold 2 IBS: 0.1926968248866514
Fold 3 IBS: 0.1851440821631191
Fold 4 IBS: 0.21429037994742178
Fold 5 IBS: 0.23962016592246937
[I 2024-04-16 01:37:01,019] Trial 44 finished with value: 0.20559586056317017 and parameters: {'l1_ratio': 0.13417067255706908}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19631769856811168
Fold 2 IBS: 0.1925902893550734
Fold 3 IBS: 0.18515116008932708
Fold 4 IBS: 0.2143149050574917
Fold 5 IBS: 0.23945190949833747
[I 2024-04-16 01:37:04,894] Trial 45 finished with value: 0.20556519251366825 and parameters: {'l1_ratio': 0.045781824907922465}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21397187075972027
Fold 2 IBS: 0.22156878262442825
Fold 3 IBS: 0.20452932458491085
Fold 4 IBS: 0.22473141076154546
Fold 5 IBS: 0.21812340517945217
[I 2024-04-16 01:37:07,532] Trial 46 finished with value: 0.2165849587820114 and parameters: {'l1_ratio': 0.0001320392757033495}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19608892544237871
Fold 2 IBS: 0.19284572853967039
Fold 3 IBS: 0.18513606699010854
Fold 4 IBS: 0.21427855842400445
Fold 5 IBS: 0.23993321319165065
[I 2024-04-16 01:37:10,044] Trial 47 finished with value: 0.20565649851756254 and parameters: {'l1_ratio': 0.438689386637741}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19613113456931422
Fold 2 IBS: 0.19289196900804545
Fold 3 IBS: 0.18513467955676352
Fold 4 IBS: 0.21429065395554275
Fold 5 IBS: 0.23997537104667654
[I 2024-04-16 01:37:12,448] Trial 48 finished with value: 0.2056847616272685 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19620110685790468
Fold 2 IBS: 0.19266510872263454
Fold 3 IBS: 0.18514390881351814
Fold 4 IBS: 0.21431594093933018

Fold 5 IBS: 0.239531825454713
[I 2024-04-16 01:37:15,540] Trial 49 finished with value: 0.20557157815762012 and parameters: {'l1_ratio': 0.1254528423575577}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19621316397714889
Fold 2 IBS: 0.19269257717510702
Fold 3 IBS: 0.1851422206421247
Fold 4 IBS: 0.21430059784505248
Fold 5 IBS: 0.2396107519746553
[I 2024-04-16 01:37:18,750] Trial 50 finished with value: 0.20559186232281768 and parameters: {'l1_ratio': 0.1784034233166914}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21268742875213992
Fold 2 IBS: 0.21914754413479917
Fold 3 IBS: 0.18515228675934306
Fold 4 IBS: 0.2142901632238732
Fold 5 IBS: 0.23950700809034997
[I 2024-04-16 01:37:22,710] Trial 51 finished with value: 0.21415688619210105 and parameters: {'l1_ratio': 0.03940854054912912}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19629214695819314
Fold 2 IBS: 0.1926219527261495
Fold 3 IBS: 0.1851516072514167
Fold 4 IBS: 0.21429079485572597
Fold 5 IBS: 0.23939905538362793
[I 2024-04-16 01:37:27,080] Trial 52 finished with value: 0.20555111143502264 and parameters: {'l1_ratio': 0.04854315782189804}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19628016576232868
Fold 2 IBS: 0.19260826290777694
Fold 3 IBS: 0.18515210759310952
Fold 4 IBS: 0.21433171155451325
Fold 5 IBS: 0.23949919622690402
[I 2024-04-16 01:37:31,969] Trial 53 finished with value: 0.20557428880892648 and parameters: {'l1_ratio': 0.04731421064692989}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19623907515659997
Fold 2 IBS: 0.19268555933242118
Fold 3 IBS: 0.18514578231373036
Fold 4 IBS: 0.21429132822942054
Fold 5 IBS: 0.23958750034185303
[I 2024-04-16 01:37:36,716] Trial 54 finished with value: 0.20558984907480501 and parameters: {'l1_ratio': 0.11880778134858852}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19621075838716304
Fold 2 IBS: 0.19273315239146435
Fold 3 IBS: 0.18514232451895218
Fold 4 IBS: 0.2142977958998589
Fold 5 IBS: 0.23960212392214306
[I 2024-04-16 01:37:39,223] Trial 55 finished with value: 0.2055972310239163 and parameters: {'l1_ratio': 0.17719618394472306}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962209978935553
Fold 2 IBS: 0.192664237011343
Fold 3 IBS: 0.18514525836802104
Fold 4 IBS: 0.2143260835227797
Fold 5 IBS: 0.23952798525701413
[I 2024-04-16 01:37:45,972] Trial 56 finished with value: 0.2055769124105426 and parameters: {'l1_ratio': 0.11362989983418717}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1960683283695601
Fold 2 IBS: 0.19291690429688488
Fold 3 IBS: 0.1851339098423437
Fold 4 IBS: 0.214313415957687
Fold 5 IBS: 0.2400525286181124
[I 2024-04-16 01:37:48,212] Trial 57 finished with value: 0.20569701741691762 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21384777182007614
Fold 2 IBS: 0.22132601037482103
Fold 3 IBS: 0.2043529334494708
Fold 4 IBS: 0.2245552096752887
Fold 5 IBS: 0.21809961417430138
[I 2024-04-16 01:37:49,477] Trial 58 finished with value: 0.21643630789879165 and parameters: {'l1_ratio': 0.003680241884233326}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19629766723169353
Fold 2 IBS: 0.19264026385594263
Fold 3 IBS: 0.18515079075228896
Fold 4 IBS: 0.21430372686966062
Fold 5 IBS: 0.23945202737922372
[I 2024-04-16 01:37:52,969] Trial 59 finished with value: 0.2055688952177619 and parameters: {'l1_ratio': 0.05529549915046709}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19621579941616205
Fold 2 IBS: 0.19270963913284875
Fold 3 IBS: 0.18514339908471536
Fold 4 IBS: 0.21428962898097537
Fold 5 IBS: 0.23965741187102269
[I 2024-04-16 01:37:56,826] Trial 60 finished with value: 0.20560317569714487 and parameters: {'l1_ratio': 0.15219421982857506}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962511362210753
Fold 2 IBS: 0.1926126990220736
Fold 3 IBS: 0.18514674978521015
Fold 4 IBS: 0.21431925723958217
Fold 5 IBS: 0.23951394938987483
[I 2024-04-16 01:38:02,005] Trial 61 finished with value: 0.2055687583315632 and parameters: {'l1_ratio': 0.0634824217456714}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19621121139483536
Fold 2 IBS: 0.19263187252261146
Fold 3 IBS: 0.1851464846256756
Fold 4 IBS: 0.21430631830958036
Fold 5 IBS: 0.23956900313930174
[I 2024-04-16 01:38:05,528] Trial 62 finished with value: 0.20557297799840094 and parameters: {'l1_ratio': 0.09668545976943985}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1963080735469552
Fold 2 IBS: 0.19264014411889824
Fold 3 IBS: 0.18515099062805263
Fold 4 IBS: 0.21430911423560994
Fold 5 IBS: 0.23945066080632654
[I 2024-04-16 01:38:08,753] Trial 63 finished with value: 0.2055717966671685 and parameters: {'l1_ratio': 0.050266024209391566}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21307849525576222
Fold 2 IBS: 0.2198640814598225
Fold 3 IBS: 0.1851529781452346
Fold 4 IBS: 0.22349591468365562
Fold 5 IBS: 0.2393544591355599
[I 2024-04-16 01:38:10,765] Trial 64 finished with value: 0.21618918573600698 and parameters: {'l1_ratio': 0.02682070473795306}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19617537767778911
Fold 2 IBS: 0.19276269741050486
Fold 3 IBS: 0.18513897872940013
Fold 4 IBS: 0.2143081839359349
Fold 5 IBS: 0.23980440092745278
[I 2024-04-16 01:38:13,513] Trial 65 finished with value: 0.20563792773621636 and parameters: {'l1_ratio': 0.28352019148663904}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21396358870581297
Fold 2 IBS: 0.22155252372108022
Fold 3 IBS: 0.20451753403136413
Fold 4 IBS: 0.22471960883981876
Fold 5 IBS: 0.21812178795554543
[I 2024-04-16 01:38:14,962] Trial 66 finished with value: 0.21657500865072432 and parameters: {'l1_ratio': 0.00036732047771589893}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19622673722921052
Fold 2 IBS: 0.19265008075485013
Fold 3 IBS: 0.18514595778036438
Fold 4 IBS: 0.21432304196244098
Fold 5 IBS: 0.23948736451136735
[I 2024-04-16 01:38:17,953] Trial 67 finished with value: 0.20556663644764667 and parameters: {'l1_ratio': 0.10022359348974141}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1961671295636223
Fold 2 IBS: 0.19268129896942823
Fold 3 IBS: 0.18514281559410484
Fold 4 IBS: 0.2143052001518968
Fold 5 IBS: 0.23958019442266487
[I 2024-04-16 01:38:20,768] Trial 68 finished with value: 0.20557532774034343 and parameters: {'l1_ratio': 0.1578038024590922}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962144062561884
Fold 2 IBS: 0.1926564598021409
Fold 3 IBS: 0.18514547837893267
Fold 4 IBS: 0.21431898198597762
Fold 5 IBS: 0.2395061972087544
[I 2024-04-16 01:38:23,612] Trial 69 finished with value: 0.2055683047263988 and parameters: {'l1_ratio': 0.11184087124144768}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19614576684596027
Fold 2 IBS: 0.19272350339259559
Fold 3 IBS: 0.18514099111181143
Fold 4 IBS: 0.2143118955247984
Fold 5 IBS: 0.23969690742552427
[I 2024-04-16 01:38:25,923] Trial 70 finished with value: 0.20560381286013799 and parameters: {'l1_ratio': 0.2111506763461652}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962712651905603
Fold 2 IBS: 0.19263586428374146
Fold 3 IBS: 0.18514866972488622
Fold 4 IBS: 0.2142862168304218
Fold 5 IBS: 0.23944185243855726
[I 2024-04-16 01:38:28,141] Trial 71 finished with value: 0.2055567736936334 and parameters: {'l1_ratio': 0.06635090352271063}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19628252803469662
Fold 2 IBS: 0.19264882104184664
Fold 3 IBS: 0.1851482405399161
Fold 4 IBS: 0.2142992038594032
Fold 5 IBS: 0.2394784492604881
[I 2024-04-16 01:38:30,536] Trial 72 finished with value: 0.2055714485472701 and parameters: {'l1_ratio': 0.06805740508010429}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962659160145994
Fold 2 IBS: 0.19267584623422365
Fold 3 IBS: 0.18514661133109842
Fold 4 IBS: 0.21430228247736927
Fold 5 IBS: 0.2395582015980976
[I 2024-04-16 01:38:33,296] Trial 73 finished with value: 0.20558977153107766 and parameters: {'l1_ratio': 0.0959085331771818}. Best is trial 36 with value: 0.20554511524025393.

Fold 1 IBS: 0.196286739680928
Fold 2 IBS: 0.19265366490340924
Fold 3 IBS: 0.1851480871073592
Fold 4 IBS: 0.21430405096308916
Fold 5 IBS: 0.23949210283802028
[I 2024-04-16 01:38:35,511] Trial 74 finished with value: 0.20557692909856118 and parameters: {'l1_ratio': 0.06871556465927647}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21302139910858334
Fold 2 IBS: 0.21975838021497485
Fold 3 IBS: 0.18515340128832472
Fold 4 IBS: 0.2234194295456223
Fold 5 IBS: 0.2394523242845926
[I 2024-04-16 01:38:37,205] Trial 75 finished with value: 0.21616098688841956 and parameters: {'l1_ratio': 0.028621971113182047}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962105325667388
Fold 2 IBS: 0.19265188880986528
Fold 3 IBS: 0.18514561150929243
Fold 4 IBS: 0.21431480274146802
Fold 5 IBS: 0.23949387268473116
[I 2024-04-16 01:38:39,057] Trial 76 finished with value: 0.20556334166241913 and parameters: {'l1_ratio': 0.11081271262960429}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962229341589873
Fold 2 IBS: 0.1927181470770391
Fold 3 IBS: 0.18514307527993196
Fold 4 IBS: 0.21429793379819886
Fold 5 IBS: 0.23955785077889866
[I 2024-04-16 01:38:41,447] Trial 77 finished with value: 0.20558798821861118 and parameters: {'l1_ratio': 0.15513815511207182}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19625085461373198
Fold 2 IBS: 0.1926772122266592
Fold 3 IBS: 0.18514631032875192
Fold 4 IBS: 0.2142939752363172
Fold 5 IBS: 0.23956334244560548
[I 2024-04-16 01:38:43,405] Trial 78 finished with value: 0.20558633897021314 and parameters: {'l1_ratio': 0.10594404639219927}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1961492385998465
Fold 2 IBS: 0.1927277452962539
Fold 3 IBS: 0.18514085541314163
Fold 4 IBS: 0.21431567128418488
Fold 5 IBS: 0.23970854078831422
[I 2024-04-16 01:38:45,372] Trial 79 finished with value: 0.20560841027634819 and parameters: {'l1_ratio': 0.2132490291559958}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19601913512664607
Fold 2 IBS: 0.19296417375619518
Fold 3 IBS: 0.18513454541224833
Fold 4 IBS: 0.21428458044989374
Fold 5 IBS: 0.24019055016112242
[I 2024-04-16 01:38:47,279] Trial 80 finished with value: 0.20571859698122114 and parameters: {'l1_ratio': 0.9522923019327132}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21307701347455807
Fold 2 IBS: 0.21986133349696255
Fold 3 IBS: 0.1851529477863485
Fold 4 IBS: 0.2234939260902036
Fold 5 IBS: 0.23935715068548938
[I 2024-04-16 01:38:48,776] Trial 81 finished with value: 0.21618847430671245 and parameters: {'l1_ratio': 0.026867298002657712}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19612423950688937
Fold 2 IBS: 0.19286838004661688
Fold 3 IBS: 0.18513547239037592
Fold 4 IBS: 0.21432664430141693
Fold 5 IBS: 0.2399961027568216
[I 2024-04-16 01:38:50,590] Trial 82 finished with value: 0.20569016780042415 and parameters: {'l1_ratio': 0.5233803160109376}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19627822913414794
Fold 2 IBS: 0.19263031639952607
Fold 3 IBS: 0.1851480389852414
Fold 4 IBS: 0.21428767682192337
Fold 5 IBS: 0.2394249639171048
[I 2024-04-16 01:38:52,870] Trial 83 finished with value: 0.20555384505158872 and parameters: {'l1_ratio': 0.059665506483117824}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19626258603604374
Fold 2 IBS: 0.19265727485891315
Fold 3 IBS: 0.1851474835093821
Fold 4 IBS: 0.21429276988994322
Fold 5 IBS: 0.23950486832572726
[I 2024-04-16 01:38:54,740] Trial 84 finished with value: 0.2055729965240019 and parameters: {'l1_ratio': 0.08385051808398299}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19622320026578766
Fold 2 IBS: 0.19269131210723708
Fold 3 IBS: 0.18514428233444663
Fold 4 IBS: 0.21428496677548367
Fold 5 IBS: 0.23960485648109225
[I 2024-04-16 01:38:56,883] Trial 85 finished with value: 0.20558972359280947 and parameters: {'l1_ratio': 0.13257827709423287}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19611274061203826
Fold 2 IBS: 0.19281936765621127
Fold 3 IBS: 0.18513703074334104
Fold 4 IBS: 0.21427872072031687
Fold 5 IBS: 0.23985809648211867
[I 2024-04-16 01:38:59,803] Trial 86 finished with value: 0.20564119124280525 and parameters: {'l1_ratio': 0.36580272626819565}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19619512588912652
Fold 2 IBS: 0.19271437663566224
Fold 3 IBS: 0.18514303078887132
Fold 4 IBS: 0.21427954753640802
Fold 5 IBS: 0.23966988874821613
[I 2024-04-16 01:39:02,988] Trial 87 finished with value: 0.20560039391965682 and parameters: {'l1_ratio': 0.169698004287482}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21320660584939152
Fold 2 IBS: 0.2201026289952274
Fold 3 IBS: 0.1851527824679396
Fold 4 IBS: 0.22366857816857466
Fold 5 IBS: 0.23939418246847258
[I 2024-04-16 01:39:06,506] Trial 88 finished with value: 0.21630495558992116 and parameters: {'l1_ratio': 0.022823003121400738}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19623460178362834
Fold 2 IBS: 0.1926248483809715
Fold 3 IBS: 0.18514723331335298
Fold 4 IBS: 0.21431669119772356
Fold 5 IBS: 0.23954816325614559
[I 2024-04-16 01:39:10,918] Trial 89 finished with value: 0.20557430758636439 and parameters: {'l1_ratio': 0.07867502422887616}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1960755086469978
Fold 2 IBS: 0.19292395743288615
Fold 3 IBS: 0.18513393456538185
Fold 4 IBS: 0.2142857174244302
Fold 5 IBS: 0.24007047590208877
[I 2024-04-16 01:39:14,986] Trial 90 finished with value: 0.20569791879435698 and parameters: {'l1_ratio': 0.7135825642664739}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.21278025849625412
Fold 2 IBS: 0.21931607049053958
Fold 3 IBS: 0.18515218555230925
Fold 4 IBS: 0.2230995224319935
Fold 5 IBS: 0.23938920038745276
[I 2024-04-16 01:39:18,018] Trial 91 finished with value: 0.21594744747170985 and parameters: {'l1_ratio': 0.03636651131676408}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1962769510019655
Fold 2 IBS: 0.19261573827445888
Fold 3 IBS: 0.18515166482509837
Fold 4 IBS: 0.21433366951345062
Fold 5 IBS: 0.23951976799658817
[I 2024-04-16 01:39:20,388] Trial 92 finished with value: 0.20557955832231228 and parameters: {'l1_ratio': 0.05276287437630263}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19624651719794833
Fold 2 IBS: 0.19269433460401025
Fold 3 IBS: 0.18514443561168342
Fold 4 IBS: 0.2142999693917291
Fold 5 IBS: 0.2396119198720606
[I 2024-04-16 01:39:23,127] Trial 93 finished with value: 0.20559943533548633 and parameters: {'l1_ratio': 0.12106356174701773}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19626514860030878
Fold 2 IBS: 0.19261530874023142
Fold 3 IBS: 0.18515104911750752
Fold 4 IBS: 0.21432775365737272
Fold 5 IBS: 0.23951967744685515
[I 2024-04-16 01:39:26,075] Trial 94 finished with value: 0.2055757875124551 and parameters: {'l1_ratio': 0.057988088260893744}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19622316198495987
Fold 2 IBS: 0.19264588843293812
Fold 3 IBS: 0.185146075057872
Fold 4 IBS: 0.21431919711388725
Fold 5 IBS: 0.23947557761625757
[I 2024-04-16 01:39:28,238] Trial 95 finished with value: 0.20556198004118292 and parameters: {'l1_ratio': 0.09938873720355094}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19613770306722234
Fold 2 IBS: 0.19275438484991284
Fold 3 IBS: 0.18513980066216018
Fold 4 IBS: 0.21432107747036352
Fold 5 IBS: 0.23978165800297252
[I 2024-04-16 01:39:30,213] Trial 96 finished with value: 0.2056269248105263 and parameters: {'l1_ratio': 0.25119847919293065}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19623239952866084
Fold 2 IBS: 0.19265671959961483
Fold 3 IBS: 0.1851470613064003
Fold 4 IBS: 0.21432912366814105
Fold 5 IBS: 0.23950600660458668
[I 2024-04-16 01:39:32,104] Trial 97 finished with value: 0.20557426214148075 and parameters: {'l1_ratio': 0.10157151456632534}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.1960094941658717
Fold 2 IBS: 0.19294097020993423
Fold 3 IBS: 0.18513470955226863

Fold 4 IBS: 0.21430108421599545
Fold 5 IBS: 0.2401228436971971
[I 2024-04-16 01:39:33,705] Trial 98 finished with value: 0.2057018203682534 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 36 with value: 0.20554511524025393.
Fold 1 IBS: 0.19623831345492668
Fold 2 IBS: 0.1926636410581049
Fold 3 IBS: 0.18514364915749978
Fold 4 IBS: 0.21430253945348898
Fold 5 IBS: 0.23965438244574724
[I 2024-04-16 01:39:35,676] Trial 99 finished with value: 0.2056005051139535 and parameters: {'l1_ratio': 0.13788271573671446}. Best is trial 36 with value: 0.20554511524025393.


* Best trial for IBS:
 FrozenTrial(number=36, state=TrialState.COMPLETE, values=[0.20554511524025393], datetime_start=datetime.datetime(2024, 4, 16, 1, 36, 35, 754414), datetime_complete=datetime.datetime(2024, 4, 16, 1, 36, 38, 169171), params={'l1_ratio': 0.043525712831569995}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=36, value=None)


* Best Score for IBS:
 0.20554511524025393

In [50]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [51]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.658
train_ibs:  0.206

#### Test

In [52]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [53]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.59

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.043525712831569995)

test_ibs:  0.237

In [54]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [55]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 01:39:36,718] A new study created in memory with name: no-name-3b463807-d7aa-4eef-bc70-fa4fe2d90064

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.609704641350211
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 01:39:53,788] Trial 0 finished with value: 0.6435157425747653 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:40:03,950] Trial 1 finished with value: 0.634560882976507 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:40:13,480] Trial 2 finished with value: 0.6397429558056387 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:40:16,542] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:40:20,391] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.5949367088607594
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 01:40:37,919] Trial 5 finished with value: 0.6294790352485181 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:41:00,130] Trial 6 finished with value: 0.6337077696441062 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:41:11,189] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:41:42,076] Trial 8 finished with value: 0.5333333333333333 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6033755274261603
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 01:42:00,157] Trial 9 finished with value: 0.622850793301972 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:42:02,362] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 01:42:10,823] Trial 11 finished with value: 0.6372475954351984 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.9894300173846429, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17782839593648317, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:42:21,707] Trial 12 finished with value: 0.6383419881186077 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8243002603618976, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 0 with value: 0.6435157425747653.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.6901408450704225
[I 2024-04-16 01:42:46,816] Trial 13 finished with value: 0.6453870331581311 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 381, 'oob_score': False, 'max_samples': 0.7951627193746391, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19432384347385334, 'warm_start': False}. Best is trial 13 with value: 0.6453870331581311.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:43:01,351] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.7481926600574748, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.39544239501812417, 'warm_start': True}. Best is trial 13 with value: 0.6453870331581311.
Fold 1 C-index: 0.5476190476190477
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 01:43:37,827] Trial 15 finished with value: 0.6247754646518974 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 473, 'oob_score': False, 'max_samples': 0.4747428535255964, 'max_features': None, 'min_weight_fraction_leaf': 0.23048182024256944, 'warm_start': False}. Best is trial 13 with value: 0.6453870331581311.

Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6029411764705882
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 01:44:13,688] Trial 16 finished with value: 0.646283662170682 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.7515853579413085, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12025117221320178, 'warm_start': False}. Best is trial 16 with value: 0.646283662170682.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6029411764705882
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 01:44:49,382] Trial 17 finished with value: 0.6417351590306295 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.8174822258864815, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1174940313225995, 'warm_start': False}. Best is trial 16 with value: 0.646283662170682.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:45:00,673] Trial 18 finished with value: 0.7033184528207626 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.8442848204991592, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07958856082174798, 'warm_start': True}. Best is trial 18 with value: 0.7033184528207626.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 01:45:09,982] Trial 19 finished with value: 0.700547661405605 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 4, 'n_estimators': 418, 'oob_score': True, 'max_samples': 0.8863105730611309, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08129270120155188, 'warm_start': True}. Best is trial 18 with value: 0.7033184528207626.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 01:45:20,187] Trial 20 finished with value: 0.698913416928385 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.8926080278090712, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08111295422778507, 'warm_start': True}. Best is trial 18 with value: 0.7033184528207626.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7362869198312236
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 01:45:31,069] Trial 21 finished with value: 0.7030868572408299 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.88219485815417, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0587391455650732, 'warm_start': True}. Best is trial 18 with value: 0.7033184528207626.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:45:40,905] Trial 22 finished with value: 0.6953403097004374 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.9943978719283488, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004164794747489542, 'warm_start': True}. Best is trial 18 with value: 0.7033184528207626.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:45:53,104] Trial 23 finished with value: 0.7226788291857692 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9048681564101896, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07367749555819647, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-16 01:45:59,959] Trial 24 finished with value: 0.7061472762089811 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.665565318795521, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06382883315390633, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:46:07,738] Trial 25 finished with value: 0.7023811305750521 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1347892252805712, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 01:46:14,267] Trial 26 finished with value: 0.6855357590612381 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0707010267264864, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7206572769953051
[I 2024-04-16 01:46:15,240] Trial 27 finished with value: 0.7005325918029897 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 9, 'oob_score': True, 'max_samples': 0.7022703412313396, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02890346118457649, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:46:25,850] Trial 28 finished with value: 0.7138419831700327 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.8270017140062347, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09847266982448483, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6814345991561181
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 01:46:32,888] Trial 29 finished with value: 0.6849337473202217 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.5217232240509235, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14623135778226415, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 01:46:42,400] Trial 30 finished with value: 0.6900597917249203 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.6909753474084037, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21317518514411737, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 01:46:52,899] Trial 31 finished with value: 0.7127646860540031 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.8209031154082257, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09599093645659847, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:47:02,092] Trial 32 finished with value: 0.7096939204781249 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 284, 'oob_score': True, 'max_samples': 0.7868995414870705, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10311713102845695, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 01:47:09,938] Trial 33 finished with value: 0.7044256377407929 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.7683677965678036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10401753858581714, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:47:16,372] Trial 34 finished with value: 0.71643529155937 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 280, 'oob_score': True, 'max_samples': 0.9386044800596345, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15320941092105694, 'warm_start': True}. Best is trial 23 with value: 0.7226788291857692.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:47:25,969] Trial 35 finished with value: 0.7264732574580586 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.9472356140297418, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15522153797388627, 'warm_start': True}. Best is trial 35 with value: 0.7264732574580586.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:47:34,285] Trial 36 finished with value: 0.7326948760751971 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.9679514659592385, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14751298059369106, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 01:47:41,619] Trial 37 finished with value: 0.7279732636097276 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.9489501810580288, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1647245114603592, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7025316455696202
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 01:47:47,095] Trial 38 finished with value: 0.6958518828283675 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 182, 'oob_score': True, 'max_samples': 0.9561413970919131, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2442878918797503, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6983122362869199
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 01:47:50,251] Trial 39 finished with value: 0.6909848424126291 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 102, 'oob_score': True, 'max_samples': 0.9424724882584229, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.26481430405036266, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:47:56,435] Trial 40 finished with value: 0.7191938477363424 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 254, 'oob_score': True, 'max_samples': 0.9991194271915587, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1940333529848391, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 01:48:03,490] Trial 41 finished with value: 0.7173257357044182 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.9999190846319379, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20041942701751392, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:48:11,095] Trial 42 finished with value: 0.7103926961552705 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.8719962001642744, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17632305819030553, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 01:48:17,523] Trial 43 finished with value: 0.7189784405796225 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.9208985433164987, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16266836698854162, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 01:48:23,795] Trial 44 finished with value: 0.6915114133547876 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.9613135829295866, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28123237747956786, 'warm_start': True}. Best is trial 36 with value: 0.7326948760751971.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:48:28,730] Trial 45 finished with value: 0.74193352992342 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.9104218782867626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1296632281594257, 'warm_start': True}. Best is trial 45 with value: 0.74193352992342.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.6572769953051644
[I 2024-04-16 01:48:30,920] Trial 46 finished with value: 0.6723749458210488 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 128, 'oob_score': True, 'max_samples': 0.33531345149315517, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13026482705842524, 'warm_start': True}. Best is trial 45 with value: 0.74193352992342.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:48:32,596] Trial 47 finished with value: 0.8117453496901443 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.8580864817682552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.035494235386271944, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5822510822510822
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.6666666666666666
[I 2024-04-16 01:48:34,339] Trial 48 finished with value: 0.6812685646755825 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.8593063971491026, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37064157122944563, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 01:48:37,128] Trial 49 finished with value: 0.7009614249839388 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.9170017849380806, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2243232961999294, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:48:38,645] Trial 50 finished with value: 0.7957232746418719 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 66, 'oob_score': True, 'max_samples': 0.9602584943053311, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.040074624120161606, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:48:40,714] Trial 51 finished with value: 0.7561501851992845 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 61, 'oob_score': True, 'max_samples': 0.9633595530309013, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03524509169170249, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6985294117647058
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:48:42,182] Trial 52 finished with value: 0.7321664088413692 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 44, 'oob_score': True, 'max_samples': 0.9596971223109397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04155798497198057, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 01:48:43,536] Trial 53 finished with value: 0.7399456626602731 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 60, 'oob_score': True, 'max_samples': 0.9730557312063746, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03084756559351588, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.784037558685446
[I 2024-04-16 01:48:45,097] Trial 54 finished with value: 0.7443902116755226 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.8639845101890473, 'max_features': 'auto', 'min_weight_fraction_leaf': 7.410060651526565e-05, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.7887323943661971
[I 2024-04-16 01:48:46,000] Trial 55 finished with value: 0.7433876743617917 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 67, 'oob_score': False, 'max_samples': 0.8583318380759427, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0033444004601576784, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 01:48:49,001] Trial 56 finished with value: 0.6255485912496573 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 78, 'oob_score': False, 'max_samples': 0.7475925823445957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01449866353137377, 'warm_start': False}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.875
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:48:49,509] Trial 57 finished with value: 0.7788316475717502 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.8418746246604945, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04294155382598033, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.5759803921568627
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6737089201877934
[I 2024-04-16 01:48:49,864] Trial 58 finished with value: 0.6545752741079252 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7285459961920672, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002392023239296992, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.5738396624472574
Fold 5 C-index: 0.6572769953051644
[I 2024-04-16 01:48:51,276] Trial 59 finished with value: 0.6254488854083913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 28, 'oob_score': False, 'max_samples': 0.7821131178311989, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04830947461583209, 'warm_start': False}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 01:48:52,558] Trial 60 finished with value: 0.7673027725004328 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 120, 'oob_score': False, 'max_samples': 0.8538452387430214, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03912098750510451, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:48:53,855] Trial 61 finished with value: 0.7717165492673997 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 120, 'oob_score': False, 'max_samples': 0.8492967624873718, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01680242546555342, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.875
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:48:55,049] Trial 62 finished with value: 0.7579916841694132 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.6089095284527805, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04069739167155086, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:48:56,633] Trial 63 finished with value: 0.714347190115126 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.35714176923040714, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.046981122374956504, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:48:57,341] Trial 64 finished with value: 0.7887238782204724 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.5810930547498758, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03387896280284634, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:48:58,118] Trial 65 finished with value: 0.7475171376189174 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 26, 'oob_score': False, 'max_samples': 0.6282156254684211, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019224036418393896, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8450704225352113
[I 2024-04-16 01:48:59,423] Trial 66 finished with value: 0.768591559340474 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.5817311190795871, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.059345532545058616, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:49:00,500] Trial 67 finished with value: 0.765534780298933 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 87, 'oob_score': False, 'max_samples': 0.5668061789015015, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05477022813391753, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 01:49:01,649] Trial 68 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.4847626958227675, 'max_features': None, 'min_weight_fraction_leaf': 0.48797001480189905, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5735930735930735
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.6102941176470589
Fold 4 C-index: 0.5421940928270043
Fold 5 C-index: 0.6502347417840375
[I 2024-04-16 01:49:03,083] Trial 69 finished with value: 0.6074060623130919 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.20333731221955026, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0865346047062048, 'warm_start': False}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:49:03,590] Trial 70 finished with value: 0.7454615818514962 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 23, 'oob_score': False, 'max_samples': 0.5737793973421406, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06032132811340718, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:49:04,882] Trial 71 finished with value: 0.7441715649614195 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.5002128898385672, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06587272918998394, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 01:49:05,775] Trial 72 finished with value: 0.7541275879628502 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 80, 'oob_score': False, 'max_samples': 0.4068816330794687, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01950952060871049, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 01:49:07,281] Trial 73 finished with value: 0.7493092090075143 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.5637756064521773, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05620118792614036, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.8262910798122066
[I 2024-04-16 01:49:08,364] Trial 74 finished with value: 0.7679726273886919 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.42990482956557347, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027597508478566582, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7746478873239436
[I 2024-04-16 01:49:09,504] Trial 75 finished with value: 0.7148191604556374 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.43192925271620286, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025378451347192632, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:49:11,223] Trial 76 finished with value: 0.7632370048377541 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 164, 'oob_score': False, 'max_samples': 0.834637040010854, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08147145249102639, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.577922077922078
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:49:11,771] Trial 77 finished with value: 0.7229823212612165 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.37501011448338495, 'max_features': None, 'min_weight_fraction_leaf': 0.018009583129883523, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:49:12,619] Trial 78 finished with value: 0.7995382902913998 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 49, 'oob_score': False, 'max_samples': 0.8026781395378416, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038767590824696156, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7652582159624414
[I 2024-04-16 01:49:13,339] Trial 79 finished with value: 0.7202465015731248 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.8043337526563993, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11375693446991722, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 01:49:14,086] Trial 80 finished with value: 0.7782259002808567 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.6829648704230089, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07186561126212958, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 01:49:14,957] Trial 81 finished with value: 0.7540547037385759 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 53, 'oob_score': False, 'max_samples': 0.6621142259603215, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07379055281230015, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 01:49:15,821] Trial 82 finished with value: 0.8080052107473241 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 77, 'oob_score': False, 'max_samples': 0.5329902566458147, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032540361599660575, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6125541125541125
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 01:49:16,762] Trial 83 finished with value: 0.7083643246355091 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 33, 'oob_score': False, 'max_samples': 0.5945217584678836, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08686315234506276, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:49:17,637] Trial 84 finished with value: 0.7966252222375523 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 49, 'oob_score': False, 'max_samples': 0.7176828068441872, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013410647080785425, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:49:18,227] Trial 85 finished with value: 0.7981127865820796 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 9, 'oob_score': False, 'max_samples': 0.6957518562776038, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01215184477936608, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.863849765258216
[I 2024-04-16 01:49:18,654] Trial 86 finished with value: 0.7932034457813012 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.7118486988787678, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010280962874606323, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 01:49:19,563] Trial 87 finished with value: 0.6847697908723125 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 15, 'oob_score': False, 'max_samples': 0.7132065421524256, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012310809369380369, 'warm_start': False}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.5759803921568627
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 01:49:20,174] Trial 88 finished with value: 0.6977977538849378 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 6, 'oob_score': False, 'max_samples': 0.6387925943481064, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03542201405396528, 'warm_start': True}. Best is trial 47 with value: 0.8117453496901443.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8544600938967136
[I 2024-04-16 01:49:21,265] Trial 89 finished with value: 0.8221525028348753 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.7579598492672649, 'max_features': None, 'min_weight_fraction_leaf': 0.04896097755950776, 'warm_start': True}. Best is trial 89 with value: 0.8221525028348753.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8497652582159625
[I 2024-04-16 01:49:22,602] Trial 90 finished with value: 0.8238819736147429 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.7380344112473246, 'max_features': None, 'min_weight_fraction_leaf': 0.01303572075998231, 'warm_start': True}. Best is trial 90 with value: 0.8238819736147429.

Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:49:24,282] Trial 91 finished with value: 0.837691219861419 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.7669907243888413, 'max_features': None, 'min_weight_fraction_leaf': 0.01259491102422066, 'warm_start': True}. Best is trial 91 with value: 0.837691219861419.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.9285714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:49:25,657] Trial 92 finished with value: 0.8467135514637952 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7321959730404333, 'max_features': None, 'min_weight_fraction_leaf': 0.011048621886878659, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8779342723004695
[I 2024-04-16 01:49:27,449] Trial 93 finished with value: 0.8359186454043197 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 73, 'oob_score': False, 'max_samples': 0.7375995340645484, 'max_features': None, 'min_weight_fraction_leaf': 0.009658330367131436, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:49:29,171] Trial 94 finished with value: 0.8396622787107356 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.7390412644202021, 'max_features': None, 'min_weight_fraction_leaf': 0.007607294407874901, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 01:49:30,296] Trial 95 finished with value: 0.8382613110237044 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 76, 'oob_score': False, 'max_samples': 0.7796572109909043, 'max_features': None, 'min_weight_fraction_leaf': 0.029308468014020105, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:49:31,397] Trial 96 finished with value: 0.8379693777298598 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 77, 'oob_score': False, 'max_samples': 0.7650177960990333, 'max_features': None, 'min_weight_fraction_leaf': 0.00019739573650123104, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:49:32,729] Trial 97 finished with value: 0.8379693777298598 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 77, 'oob_score': False, 'max_samples': 0.7623019616368047, 'max_features': None, 'min_weight_fraction_leaf': 0.0012160749171805825, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8826291079812206
[I 2024-04-16 01:49:34,247] Trial 98 finished with value: 0.8354647884372959 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.7625550194004627, 'max_features': None, 'min_weight_fraction_leaf': 0.0006701339106091131, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9071729957805907

[I 2024-04-16 01:49:35,760] A new study created in memory with name: no-name-8bd7c0e5-a214-4ee0-a47c-13f0803a30ea

Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 01:49:35,722] Trial 99 finished with value: 0.841986031636921 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.7617621847649487, 'max_features': None, 'min_weight_fraction_leaf': 0.0006198870818653959, 'warm_start': True}. Best is trial 92 with value: 0.8467135514637952.


* Best trial for C-index:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.8467135514637952], datetime_start=datetime.datetime(2024, 4, 16, 1, 49, 24, 311450), datetime_complete=datetime.datetime(2024, 4, 16, 1, 49, 25, 653973), params={'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7321959730404333, 'max_features': None, 'min_weight_fraction_leaf': 0.011048621886878659, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=92, value=None)


* Best Score for C-index:
 0.8467135514637952

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21723421372913035
Fold 2 IBS: 0.19407560018388162
Fold 3 IBS: 0.19893977811995758
Fold 4 IBS: 0.22010881817722017
Fold 5 IBS: 0.21688357817959858
[I 2024-04-16 01:49:45,809] Trial 0 finished with value: 0.20944839767795767 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.20944839767795767.
Fold 1 IBS: 0.21053987448715922
Fold 2 IBS: 0.19974614487272824
Fold 3 IBS: 0.19828121458260722
Fold 4 IBS: 0.2159494789348576
Fold 5 IBS: 0.2144029056289341
[I 2024-04-16 01:49:48,460] Trial 1 finished with value: 0.20778392370125726 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20778392370125726.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-16 01:49:50,457] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20778392370125726.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-16 01:49:57,999] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20778392370125726.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-16 01:50:03,561] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20778392370125726.
Fold 1 IBS: 0.2098209630163391
Fold 2 IBS: 0.20312945593314344
Fold 3 IBS: 0.195671168295202
Fold 4 IBS: 0.21550736825687378
Fold 5 IBS: 0.21038477678227704
[I 2024-04-16 01:50:11,486] Trial 5 finished with value: 0.20690274645676707 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21378516429423722
Fold 2 IBS: 0.1953170945384056
Fold 3 IBS: 0.19667105156090298
Fold 4 IBS: 0.22021845093828638
Fold 5 IBS: 0.21705917401312358
[I 2024-04-16 01:50:19,012] Trial 6 finished with value: 0.20861018706899115 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.2128670948585199
Fold 2 IBS: 0.21836791768635366
Fold 3 IBS: 0.20396968153858935
Fold 4 IBS: 0.22349077878177243
Fold 5 IBS: 0.21654794180716755
[I 2024-04-16 01:50:27,700] Trial 7 finished with value: 0.2150486829344806 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-16 01:50:42,787] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21058269457526024
Fold 2 IBS: 0.20178880214243516
Fold 3 IBS: 0.20098275412057853
Fold 4 IBS: 0.21902872048739205
Fold 5 IBS: 0.21350231278795845
[I 2024-04-16 01:50:45,435] Trial 9 finished with value: 0.20917705682272486 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-16 01:50:58,203] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21222370160119955
Fold 2 IBS: 0.20880740070287515
Fold 3 IBS: 0.1997680779651534
Fold 4 IBS: 0.21627620873536613
Fold 5 IBS: 0.21660764546326397
[I 2024-04-16 01:51:02,507] Trial 11 finished with value: 0.21073660689357165 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.2088256741429784
Fold 2 IBS: 0.2080183064810144
Fold 3 IBS: 0.2000776344178533
Fold 4 IBS: 0.23043790297055683
Fold 5 IBS: 0.21338688831261773
[I 2024-04-16 01:51:03,312] Trial 12 finished with value: 0.21214928126500415 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21046781556424174
Fold 2 IBS: 0.20535012377604583
Fold 3 IBS: 0.19872887252954768
Fold 4 IBS: 0.21793010896488504
Fold 5 IBS: 0.21162872239727323
[I 2024-04-16 01:51:12,736] Trial 13 finished with value: 0.2088211286463987 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.6258340703868753, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1381576993491155}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21530972029655315
Fold 2 IBS: 0.20061404933917118
Fold 3 IBS: 0.19713201308867642
Fold 4 IBS: 0.21749606294019885
Fold 5 IBS: 0.2155010688335384
[I 2024-04-16 01:51:16,839] Trial 14 finished with value: 0.20921058289962763 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.3884265985399165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.2127115855805689
Fold 2 IBS: 0.2038090922382983
Fold 3 IBS: 0.19972381969054667
Fold 4 IBS: 0.21807371980382098
Fold 5 IBS: 0.21315262427854192
[I 2024-04-16 01:51:24,241] Trial 15 finished with value: 0.20949416831835538 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9873764111748721, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 5 with value: 0.20690274645676707.

Fold 1 IBS: 0.21007977658733928
Fold 2 IBS: 0.20576955654711135
Fold 3 IBS: 0.19971841654269498
Fold 4 IBS: 0.2193428734651011
Fold 5 IBS: 0.21138347139075161
[I 2024-04-16 01:51:35,538] Trial 16 finished with value: 0.20925881890659964 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.656467758901384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08168471258646942}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21208786612774885
Fold 2 IBS: 0.2025771858920601
Fold 3 IBS: 0.19950712452151423
Fold 4 IBS: 0.21530477681450427
Fold 5 IBS: 0.21706534944553213
[I 2024-04-16 01:51:38,038] Trial 17 finished with value: 0.20930846056027191 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.8368873118701377, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18378905803629209}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.20911799021943153
Fold 2 IBS: 0.21080170163835324
Fold 3 IBS: 0.19909118065913142
Fold 4 IBS: 0.21870274153790883
Fold 5 IBS: 0.21003453724255483
[I 2024-04-16 01:51:42,896] Trial 18 finished with value: 0.20954963025947598 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.21062982570611943, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08669635653155289}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21017968040711107
Fold 2 IBS: 0.20485192357336438
Fold 3 IBS: 0.19979980323862254
Fold 4 IBS: 0.21932960244520633
Fold 5 IBS: 0.21149346947086983
[I 2024-04-16 01:51:51,290] Trial 19 finished with value: 0.20913089582703487 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.44408982315616696, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16586735223467927}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.2092887779020067
Fold 2 IBS: 0.20684997661804702
Fold 3 IBS: 0.19961863269511568
Fold 4 IBS: 0.21910815663110297
Fold 5 IBS: 0.21162580126646116
[I 2024-04-16 01:52:05,737] Trial 20 finished with value: 0.20929826902254672 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 10, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.6287093569089685, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.2139308727756235
Fold 2 IBS: 0.19729380301427465
Fold 3 IBS: 0.1961008389160667
Fold 4 IBS: 0.2186918930477531
Fold 5 IBS: 0.2172311141958451
[I 2024-04-16 01:52:13,734] Trial 21 finished with value: 0.20864970438991262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.8350788407796254, 'max_features': None, 'min_weight_fraction_leaf': 0.3616621410396409}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.2124546157813591
Fold 2 IBS: 0.19272715893092726
Fold 3 IBS: 0.19707995189353694
Fold 4 IBS: 0.22090017778595308
Fold 5 IBS: 0.2163264615912607
[I 2024-04-16 01:52:20,936] Trial 22 finished with value: 0.2078976731966074 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.8312125363801888, 'max_features': None, 'min_weight_fraction_leaf': 0.33225456373445444}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.21711582458523618
Fold 2 IBS: 0.1904993575359507
Fold 3 IBS: 0.19674905134689888
Fold 4 IBS: 0.22450979645120095
Fold 5 IBS: 0.21807898687869615
[I 2024-04-16 01:52:23,250] Trial 23 finished with value: 0.20939060335959656 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 56, 'oob_score': False, 'max_samples': 0.9860261546212814, 'max_features': None, 'min_weight_fraction_leaf': 0.32641085145106374}. Best is trial 5 with value: 0.20690274645676707.
Fold 1 IBS: 0.20188790866600687
Fold 2 IBS: 0.20131460929301953
Fold 3 IBS: 0.19492524992534704
Fold 4 IBS: 0.2146357729268992
Fold 5 IBS: 0.2129126827649459
[I 2024-04-16 01:52:30,404] Trial 24 finished with value: 0.20513524471524375 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.7866243672793476, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05142191850593961}. Best is trial 24 with value: 0.20513524471524375.
Fold 1 IBS: 0.20494523622558328
Fold 2 IBS: 0.20692736877486617
Fold 3 IBS: 0.19325085114498794
Fold 4 IBS: 0.21382372055642035
Fold 5 IBS: 0.21082953581056146
[I 2024-04-16 01:52:39,066] Trial 25 finished with value: 0.20595534250248382 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 325, 'oob_score': False, 'max_samples': 0.6982066952731942, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04535661436578799}. Best is trial 24 with value: 0.20513524471524375.
Fold 1 IBS: 0.20547561791426305
Fold 2 IBS: 0.20966355552754887
Fold 3 IBS: 0.19164379841001464
Fold 4 IBS: 0.21208868414040963
Fold 5 IBS: 0.21229287531802815
[I 2024-04-16 01:52:50,511] Trial 26 finished with value: 0.20623290626205287 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.7272674688614905, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04132260309623461}. Best is trial 24 with value: 0.20513524471524375.
Fold 1 IBS: 0.20235318199229624
Fold 2 IBS: 0.21221569244329228
Fold 3 IBS: 0.19035600679366294
Fold 4 IBS: 0.20969240427587962
Fold 5 IBS: 0.21065004286592984
[I 2024-04-16 01:53:05,718] Trial 27 finished with value: 0.20505346567421218 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 395, 'oob_score': True, 'max_samples': 0.9219615727816426, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04654159022433275}. Best is trial 27 with value: 0.20505346567421218.
Fold 1 IBS: 0.1981929221725657
Fold 2 IBS: 0.21326152943698728
Fold 3 IBS: 0.19113635845491986
Fold 4 IBS: 0.21181957298953957
Fold 5 IBS: 0.21333844611220618
[I 2024-04-16 01:53:20,536] Trial 28 finished with value: 0.2055497658332437 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.9191567635541141, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0100645300587918}. Best is trial 27 with value: 0.20505346567421218.
Fold 1 IBS: 0.2118789181543481
Fold 2 IBS: 0.20573838051186513
Fold 3 IBS: 0.19608620450173153
Fold 4 IBS: 0.21349971716480032
Fold 5 IBS: 0.2132186479953038
[I 2024-04-16 01:53:35,496] Trial 29 finished with value: 0.20808437366560978 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 408, 'oob_score': True, 'max_samples': 0.9605394975530346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10995545390504982}. Best is trial 27 with value: 0.20505346567421218.
Fold 1 IBS: 0.1949116175231708
Fold 2 IBS: 0.20594935052810426
Fold 3 IBS: 0.19161210966261732
Fold 4 IBS: 0.21265105918731453
Fold 5 IBS: 0.21515776156220423
[I 2024-04-16 01:53:50,379] Trial 30 finished with value: 0.2040563796926822 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.7734199919077761, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.001988943264888958}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.19862341258716654
Fold 2 IBS: 0.21056409625900707
Fold 3 IBS: 0.18947335509722738
Fold 4 IBS: 0.21138291049034516

Fold 5 IBS: 0.21344899574141954
[I 2024-04-16 01:54:05,524] Trial 31 finished with value: 0.20469855403503315 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.8945361564514921, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.019207941499538344}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.19906422113284747
Fold 2 IBS: 0.206965012233294
Fold 3 IBS: 0.1928488518193958
Fold 4 IBS: 0.21332960673286458
Fold 5 IBS: 0.2178341182823558
[I 2024-04-16 01:54:22,910] Trial 32 finished with value: 0.20600836204015155 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.7842251850941289, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0029357598861563597}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.20408617163679496
Fold 2 IBS: 0.20572121446559288
Fold 3 IBS: 0.18943067493113697
Fold 4 IBS: 0.21112008748359298
Fold 5 IBS: 0.21070898026488086
[I 2024-04-16 01:54:37,598] Trial 33 finished with value: 0.20421342575639975 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.8862595596314129, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0526105394825465}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.2098930563954328
Fold 2 IBS: 0.20522873841751413
Fold 3 IBS: 0.19432133489531714
Fold 4 IBS: 0.21514711357697938
Fold 5 IBS: 0.21275101684939104
[I 2024-04-16 01:54:50,606] Trial 34 finished with value: 0.20746825202692692 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.9014127752595272, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09558144518649164}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.20771233160465052
Fold 2 IBS: 0.20834518246480568
Fold 3 IBS: 0.19523518642787524
Fold 4 IBS: 0.21222329020121986
Fold 5 IBS: 0.21119872140079868
[I 2024-04-16 01:55:06,661] Trial 35 finished with value: 0.20694294241987002 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.8872300829134362, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03299659181434132}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.20287451972210596
Fold 2 IBS: 0.21104480289534291
Fold 3 IBS: 0.19130387637100738
Fold 4 IBS: 0.21005215179563877
Fold 5 IBS: 0.21260834547533947
[I 2024-04-16 01:55:19,224] Trial 36 finished with value: 0.20557673925188688 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.9446204847950465, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05040634741407017}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.20213877743893247
Fold 2 IBS: 0.21174610785642764
Fold 3 IBS: 0.19211233023101373
Fold 4 IBS: 0.2116463124297013
Fold 5 IBS: 0.21037571634704133
[I 2024-04-16 01:55:33,334] Trial 37 finished with value: 0.20560384886062327 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 412, 'oob_score': True, 'max_samples': 0.8671448889230431, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003086895532848438}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.2071479712460966
Fold 2 IBS: 0.20605778461905175
Fold 3 IBS: 0.19468591193052906
Fold 4 IBS: 0.21121676058030686
Fold 5 IBS: 0.2140977298580715
[I 2024-04-16 01:55:46,912] Trial 38 finished with value: 0.20664123164681114 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 450, 'oob_score': True, 'max_samples': 0.7976128326746559, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0623162450061498}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.2146681752405211
Fold 2 IBS: 0.20660728559810312
Fold 3 IBS: 0.19732078783930937
Fold 4 IBS: 0.21444890567306713
Fold 5 IBS: 0.21250939677884761
[I 2024-04-16 01:56:02,131] Trial 39 finished with value: 0.20911091022596967 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.9427890914419594, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15107549479429358}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.21105932364672472
Fold 2 IBS: 0.20234402977251423
Fold 3 IBS: 0.19778510118554424
Fold 4 IBS: 0.2153895936107485
Fold 5 IBS: 0.2141165788676908
[I 2024-04-16 01:56:13,738] Trial 40 finished with value: 0.2081389254166445 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.5794083821032592, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0970417745830469}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.21400110457446228
Fold 2 IBS: 0.22139273768319268
Fold 3 IBS: 0.2048042626481111
Fold 4 IBS: 0.22458709832606621
Fold 5 IBS: 0.21866794212978125
[I 2024-04-16 01:56:21,666] Trial 41 finished with value: 0.21669062907232273 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.7975321259287105, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4941259839979722}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.20481423095298307
Fold 2 IBS: 0.20537676017165146
Fold 3 IBS: 0.1910786907134071
Fold 4 IBS: 0.21547273902058667
Fold 5 IBS: 0.21106722514971019
[I 2024-04-16 01:56:34,195] Trial 42 finished with value: 0.20556192920166766 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.8766449868842188, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06761593375204138}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.19705523720926363
Fold 2 IBS: 0.20892695766000657
Fold 3 IBS: 0.1905905321058386
Fold 4 IBS: 0.2119208998150777
Fold 5 IBS: 0.21455188890184895
[I 2024-04-16 01:56:43,886] Trial 43 finished with value: 0.2046091031384071 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.753540995987103, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0324908864237481}. Best is trial 30 with value: 0.2040563796926822.
Fold 1 IBS: 0.19873039026047157
Fold 2 IBS: 0.20607566452349402
Fold 3 IBS: 0.18862797516331906
Fold 4 IBS: 0.21281218857602865
Fold 5 IBS: 0.21332756821277143
[I 2024-04-16 01:56:52,855] Trial 44 finished with value: 0.20391475734721695 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.7402363290984701, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02971021224951611}. Best is trial 44 with value: 0.20391475734721695.
Fold 1 IBS: 0.19725975927099368
Fold 2 IBS: 0.20494506879042038
Fold 3 IBS: 0.19100872245508738
Fold 4 IBS: 0.21770872192044202
Fold 5 IBS: 0.21210782550269708
[I 2024-04-16 01:57:01,368] Trial 45 finished with value: 0.2046060195879281 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.7450451112692353, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02700128962731136}. Best is trial 44 with value: 0.20391475734721695.
Fold 1 IBS: 0.21226438289865954
Fold 2 IBS: 0.20432901016268015
Fold 3 IBS: 0.19793037065883526
Fold 4 IBS: 0.21790941583085302
Fold 5 IBS: 0.2130164839286761
[I 2024-04-16 01:57:09,839] Trial 46 finished with value: 0.20908993269594078 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.504699638430874, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10602076417876821}. Best is trial 44 with value: 0.20391475734721695.

Fold 1 IBS: 0.20104036243969675
Fold 2 IBS: 0.20536630217365237
Fold 3 IBS: 0.19037076567072828
Fold 4 IBS: 0.21572005633461494
Fold 5 IBS: 0.21011692141960442
[I 2024-04-16 01:57:21,742] Trial 47 finished with value: 0.20452288160765933 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.6977990144579234, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.025965903634064653}. Best is trial 44 with value: 0.20391475734721695.
Fold 1 IBS: 0.20728783436618
Fold 2 IBS: 0.2049967559036454
Fold 3 IBS: 0.19498736250827226
Fold 4 IBS: 0.2148072924530503
Fold 5 IBS: 0.21417413689935214
[I 2024-04-16 01:57:31,597] Trial 48 finished with value: 0.2072506764261 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 347, 'oob_score': True, 'max_samples': 0.7057566829089937, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06858815773505164}. Best is trial 44 with value: 0.20391475734721695.
Fold 1 IBS: 0.21399597921142877
Fold 2 IBS: 0.2213330691378535
Fold 3 IBS: 0.20481581674207747
Fold 4 IBS: 0.22469241759813482
Fold 5 IBS: 0.21858430747436294
[I 2024-04-16 01:57:41,006] Trial 49 finished with value: 0.2166843180327715 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 368, 'oob_score': True, 'max_samples': 0.5919312981558494, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4100286247036702}. Best is trial 44 with value: 0.20391475734721695.
Fold 1 IBS: 0.21001044026550456
Fold 2 IBS: 0.204880880301315
Fold 3 IBS: 0.19457947388277597
Fold 4 IBS: 0.2156197582204417
Fold 5 IBS: 0.2106710716054704
[I 2024-04-16 01:57:50,455] Trial 50 finished with value: 0.20715232485510154 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.6734152364767038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024783671076858353}. Best is trial 44 with value: 0.20391475734721695.
Fold 1 IBS: 0.19694518087372076
Fold 2 IBS: 0.20708298196829802
Fold 3 IBS: 0.18826271051327062
Fold 4 IBS: 0.2144642585124719
Fold 5 IBS: 0.21229771530262714
[I 2024-04-16 01:58:04,284] Trial 51 finished with value: 0.20381056943407766 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 344, 'oob_score': True, 'max_samples': 0.7472262275757567, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.026151489636597046}. Best is trial 51 with value: 0.20381056943407766.
Fold 1 IBS: 0.19708818952749427
Fold 2 IBS: 0.20668747811026236
Fold 3 IBS: 0.1874436748678268
Fold 4 IBS: 0.21491143502976587
Fold 5 IBS: 0.21158285688376774
[I 2024-04-16 01:58:16,810] Trial 52 finished with value: 0.20354272688382338 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.7441608177927838, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0024206399846087648}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.20114024220785523
Fold 2 IBS: 0.20691891404303822
Fold 3 IBS: 0.18888270342543811
Fold 4 IBS: 0.21443452737508129
Fold 5 IBS: 0.21013579654648862
[I 2024-04-16 01:58:29,477] Trial 53 finished with value: 0.20430243671958032 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.6932743445193371, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0019051815693979515}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.2009092445927416
Fold 2 IBS: 0.20692522555910042
Fold 3 IBS: 0.18949536960036542
Fold 4 IBS: 0.2137320903351184
Fold 5 IBS: 0.212849837002664
[I 2024-04-16 01:58:42,588] Trial 54 finished with value: 0.20478235341799794 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.6192864368650773, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.006944058886180646}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.21226824851609388
Fold 2 IBS: 0.20308783401620004
Fold 3 IBS: 0.19734932620712906
Fold 4 IBS: 0.2161556372303876
Fold 5 IBS: 0.21436112960314
[I 2024-04-16 01:58:54,905] Trial 55 finished with value: 0.20864443511459013 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.5297775222944199, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07609045432730055}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.2069162725854056
Fold 2 IBS: 0.20568861507208502
Fold 3 IBS: 0.1951226159623641
Fold 4 IBS: 0.21282440958027893
Fold 5 IBS: 0.2148977539310974
[I 2024-04-16 01:59:07,150] Trial 56 finished with value: 0.2070899334262462 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.6631576505593824, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002108157521543759}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.2121125496700103
Fold 2 IBS: 0.2030103101426556
Fold 3 IBS: 0.19865431859466895
Fold 4 IBS: 0.2182096679469643
Fold 5 IBS: 0.2113176393290204
[I 2024-04-16 01:59:18,371] Trial 57 finished with value: 0.20866089713666391 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 418, 'oob_score': True, 'max_samples': 0.8279135376226509, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.21123040881177615
Fold 2 IBS: 0.20560607845834447
Fold 3 IBS: 0.19779803348564268
Fold 4 IBS: 0.21532487217979457
Fold 5 IBS: 0.21450030352585953
[I 2024-04-16 01:59:31,694] Trial 58 finished with value: 0.2088919392922835 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.7622888554743997, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.059075773786667306}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.21381729887249487
Fold 2 IBS: 0.20535770762856664
Fold 3 IBS: 0.19807058606083927
Fold 4 IBS: 0.21520368223797953
Fold 5 IBS: 0.2137283760241675
[I 2024-04-16 01:59:44,054] Trial 59 finished with value: 0.20923553016480959 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 447, 'oob_score': True, 'max_samples': 0.808299194530753, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13145988191302957}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.21515430219086248
Fold 2 IBS: 0.20565542093692016
Fold 3 IBS: 0.1947520636699833
Fold 4 IBS: 0.2116624476263624
Fold 5 IBS: 0.23281418903017492
[I 2024-04-16 01:59:53,365] Trial 60 finished with value: 0.21200768469086065 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.7212945944307867, 'max_features': None, 'min_weight_fraction_leaf': 0.07991555533113298}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.20005789263237714
Fold 2 IBS: 0.20456258176706835
Fold 3 IBS: 0.18856618300964717
Fold 4 IBS: 0.21618234610043568
Fold 5 IBS: 0.21198474932144254
[I 2024-04-16 02:00:04,095] Trial 61 finished with value: 0.2042707505661942 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.7049533263735692, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.025992845125616157}. Best is trial 52 with value: 0.20354272688382338.
Fold 1 IBS: 0.2018945467021621
Fold 2 IBS: 0.2025821430727389
Fold 3 IBS: 0.18915693463932687
Fold 4 IBS: 0.21292260996768517

Fold 5 IBS: 0.20982282453299972
[I 2024-04-16 02:00:13,898] Trial 62 finished with value: 0.20327581178298254 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 265, 'oob_score': True, 'max_samples': 0.6858370874030949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04150152613199446}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20601281152111253
Fold 2 IBS: 0.20449414602624297
Fold 3 IBS: 0.1947762532232537
Fold 4 IBS: 0.21288218188391347
Fold 5 IBS: 0.20843731012181801
[I 2024-04-16 02:00:22,591] Trial 63 finished with value: 0.20532054055526813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.6346530024976436, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0365353414774943}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.2118991292296007
Fold 2 IBS: 0.20610835886660045
Fold 3 IBS: 0.19616656683389874
Fold 4 IBS: 0.2140864354348938
Fold 5 IBS: 0.2141748093428134
[I 2024-04-16 02:00:34,164] Trial 64 finished with value: 0.20848705994156144 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 368, 'oob_score': True, 'max_samples': 0.7694649248382401, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1159441647810947}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20229464670427733
Fold 2 IBS: 0.20488229762874297
Fold 3 IBS: 0.18950437436557682
Fold 4 IBS: 0.21501278704936264
Fold 5 IBS: 0.2122428786508927
[I 2024-04-16 02:00:41,058] Trial 65 finished with value: 0.2047873968797705 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.7327751865706557, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.050339861975513}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20788946438928443
Fold 2 IBS: 0.20301602778483724
Fold 3 IBS: 0.1969839079720465
Fold 4 IBS: 0.2155146511393292
Fold 5 IBS: 0.21128819312454605
[I 2024-04-16 02:00:49,001] Trial 66 finished with value: 0.20693844888200869 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.8554625512690849, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01993124526078217}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.21023446396378156
Fold 2 IBS: 0.20991581393715802
Fold 3 IBS: 0.19819066718096687
Fold 4 IBS: 0.21669920161821266
Fold 5 IBS: 0.2150495109224707
[I 2024-04-16 02:00:55,658] Trial 67 finished with value: 0.210017931524518 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.6672947846850041, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08716553542752103}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20846919112283588
Fold 2 IBS: 0.22237203505868353
Fold 3 IBS: 0.1870392730260939
Fold 4 IBS: 0.21309396139371256
Fold 5 IBS: 0.22447883237834795
[I 2024-04-16 02:01:03,086] Trial 68 finished with value: 0.21109065859593476 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.8213531673750081, 'max_features': None, 'min_weight_fraction_leaf': 0.04087221175225905}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.2028210018373583
Fold 2 IBS: 0.20596897078018567
Fold 3 IBS: 0.19256100645853455
Fold 4 IBS: 0.21422235425157482
Fold 5 IBS: 0.21191380573301888
[I 2024-04-16 02:01:12,522] Trial 69 finished with value: 0.20549742781213443 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 352, 'oob_score': True, 'max_samples': 0.8533779958602722, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06390481478102061}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20038460006350764
Fold 2 IBS: 0.20193691057270854
Fold 3 IBS: 0.19427876283754447
Fold 4 IBS: 0.21235939087687863
Fold 5 IBS: 0.21232941259236818
[I 2024-04-16 02:01:24,585] Trial 70 finished with value: 0.2042578153886015 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.5938982131777709, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022462411321900494}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20085146850347022
Fold 2 IBS: 0.2040167373959782
Fold 3 IBS: 0.1929186532126752
Fold 4 IBS: 0.21274395700832358
Fold 5 IBS: 0.2091757029202345
[I 2024-04-16 02:01:37,204] Trial 71 finished with value: 0.20394130380813635 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.6401561895870445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01582781079852144}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.19795672316707505
Fold 2 IBS: 0.20688793560840263
Fold 3 IBS: 0.1878563805531906
Fold 4 IBS: 0.21345578955944264
Fold 5 IBS: 0.21079116613078178
[I 2024-04-16 02:01:47,818] Trial 72 finished with value: 0.20338959900377854 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 398, 'oob_score': True, 'max_samples': 0.5951015440448161, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014789391401274318}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.1996218530968175
Fold 2 IBS: 0.20590339950173758
Fold 3 IBS: 0.18972439835845667
Fold 4 IBS: 0.21084571848022318
Fold 5 IBS: 0.21127472432157934
[I 2024-04-16 02:01:59,478] Trial 73 finished with value: 0.20347401875176283 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.628326284285878, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013825246431305234}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20028644206635818
Fold 2 IBS: 0.20580693538870007
Fold 3 IBS: 0.19359834540176496
Fold 4 IBS: 0.21014739478509298
Fold 5 IBS: 0.2106510586602567
[I 2024-04-16 02:02:11,653] Trial 74 finished with value: 0.2040980352604346 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.5493726436597474, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010996021302251576}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.2000044937639714
Fold 2 IBS: 0.21728545319188733
Fold 3 IBS: 0.1931250258717933
Fold 4 IBS: 0.21347725058332956
Fold 5 IBS: 0.21294419360172284
[I 2024-04-16 02:02:24,503] Trial 75 finished with value: 0.2073672834025409 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.5010859559732752, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01518580298420146}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.20122279063921844
Fold 2 IBS: 0.2052254249787787
Fold 3 IBS: 0.19356760235528858
Fold 4 IBS: 0.2103081231969785
Fold 5 IBS: 0.21156620754060385
[I 2024-04-16 02:02:38,149] Trial 76 finished with value: 0.20437802974217362 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 465, 'oob_score': True, 'max_samples': 0.6442783463230624, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.041069210931125304}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.1999928324301207
Fold 2 IBS: 0.20228653576114802
Fold 3 IBS: 0.19365671849510052
Fold 4 IBS: 0.21426607349293378
Fold 5 IBS: 0.20992273131015046
[I 2024-04-16 02:02:48,459] Trial 77 finished with value: 0.20402497829789068 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.6076115602872747, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04056345461260527}. Best is trial 62 with value: 0.20327581178298254.

Fold 1 IBS: 0.21397762546898652
Fold 2 IBS: 0.22147883751600755
Fold 3 IBS: 0.20486980135357746
Fold 4 IBS: 0.22464994266370494
Fold 5 IBS: 0.21845929256270377
[I 2024-04-16 02:03:00,599] Trial 78 finished with value: 0.21668709991299603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.5153355818628218, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28987424398930645}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.21153493071166155
Fold 2 IBS: 0.20333834370429396
Fold 3 IBS: 0.19871181332894533
Fold 4 IBS: 0.21447173484121768
Fold 5 IBS: 0.21412319034910962
[I 2024-04-16 02:03:11,572] Trial 79 finished with value: 0.20843600258704562 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.5747714627136549, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09619647815257315}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.21317549868174318
Fold 2 IBS: 0.20585674844443666
Fold 3 IBS: 0.19519849243390225
Fold 4 IBS: 0.21319150437370374
Fold 5 IBS: 0.23250749106642887
[I 2024-04-16 02:03:23,480] Trial 80 finished with value: 0.21198594700004297 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 401, 'oob_score': True, 'max_samples': 0.4670556917192612, 'max_features': None, 'min_weight_fraction_leaf': 0.052971691924105904}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.19779788227498904
Fold 2 IBS: 0.2067275840106519
Fold 3 IBS: 0.1882797925614045
Fold 4 IBS: 0.2120003950750004
Fold 5 IBS: 0.21220177335482615
[I 2024-04-16 02:03:36,640] Trial 81 finished with value: 0.20340148545537443 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.6146825747093705, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013713134003198138}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.19996420780839438
Fold 2 IBS: 0.20403379958301912
Fold 3 IBS: 0.19214788324389412
Fold 4 IBS: 0.2128399324121595
Fold 5 IBS: 0.21167181419601735
[I 2024-04-16 02:03:47,720] Trial 82 finished with value: 0.20413152744869692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 433, 'oob_score': True, 'max_samples': 0.6085349580303262, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.038295734744258986}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.2019604485560848
Fold 2 IBS: 0.21464224856143022
Fold 3 IBS: 0.1945835854022343
Fold 4 IBS: 0.20828042005802996
Fold 5 IBS: 0.21505816876493855
[I 2024-04-16 02:03:58,788] Trial 83 finished with value: 0.20690497426854354 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.568197258403114, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014931284903067625}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.21162429758132006
Fold 2 IBS: 0.20480120396191723
Fold 3 IBS: 0.19966170110353285
Fold 4 IBS: 0.21893836589018745
Fold 5 IBS: 0.21148633044159307
[I 2024-04-16 02:04:09,653] Trial 84 finished with value: 0.20930237979571015 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 484, 'oob_score': True, 'max_samples': 0.6426317665348479, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06915340203502321}. Best is trial 62 with value: 0.20327581178298254.
Fold 1 IBS: 0.19638893189496368
Fold 2 IBS: 0.20527746893893095
Fold 3 IBS: 0.19083730533884813
Fold 4 IBS: 0.2098289950238785
Fold 5 IBS: 0.21246652694972018
[I 2024-04-16 02:04:19,776] Trial 85 finished with value: 0.20295984562926828 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.6084827037288676, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03342457164243477}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.1993253133502721
Fold 2 IBS: 0.21107391374376316
Fold 3 IBS: 0.1868896892457709
Fold 4 IBS: 0.2154458656855588
Fold 5 IBS: 0.2147309807056846
[I 2024-04-16 02:04:24,429] Trial 86 finished with value: 0.2054931525462099 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 141, 'oob_score': True, 'max_samples': 0.6783886681668398, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016092652086678046}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.21185568064076968
Fold 2 IBS: 0.2047970058973361
Fold 3 IBS: 0.1971641736057152
Fold 4 IBS: 0.2183448092159702
Fold 5 IBS: 0.21438135687401766
[I 2024-04-16 02:04:34,127] Trial 87 finished with value: 0.2093086052467618 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 362, 'oob_score': True, 'max_samples': 0.6853601644739371, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0340288084542245}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.19844930258342455
Fold 2 IBS: 0.2138190785465442
Fold 3 IBS: 0.1967125838647589
Fold 4 IBS: 0.21320921073650356
Fold 5 IBS: 0.21637326919292282
[I 2024-04-16 02:04:44,896] Trial 88 finished with value: 0.2077126889848308 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.35277360385569917, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0008308848259983587}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.20959170753326595
Fold 2 IBS: 0.20365433468884245
Fold 3 IBS: 0.1977968387729299
Fold 4 IBS: 0.21693535220084392
Fold 5 IBS: 0.21228264150763856
[I 2024-04-16 02:04:55,516] Trial 89 finished with value: 0.20805217494070413 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.2300892777570771, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05632113707487603}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.2112789762666468
Fold 2 IBS: 0.20446528726919788
Fold 3 IBS: 0.19900650458962685
Fold 4 IBS: 0.21839396206717224
Fold 5 IBS: 0.21161433482670472
[I 2024-04-16 02:05:04,299] Trial 90 finished with value: 0.20895181300386972 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.6522730208922147, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1876642949650079}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.19855918112547877
Fold 2 IBS: 0.20213580278806534
Fold 3 IBS: 0.1926092738394594
Fold 4 IBS: 0.21364029719832267
Fold 5 IBS: 0.21038598610829548
[I 2024-04-16 02:05:14,067] Trial 91 finished with value: 0.20346610821192432 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 398, 'oob_score': True, 'max_samples': 0.6156349027498267, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04360070896452451}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.20077868446026337
Fold 2 IBS: 0.2038549999034212
Fold 3 IBS: 0.19127367117934688
Fold 4 IBS: 0.20997126409511754
Fold 5 IBS: 0.21123316123358704
[I 2024-04-16 02:05:26,061] Trial 92 finished with value: 0.2034223561743472 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 411, 'oob_score': True, 'max_samples': 0.554505321396254, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.026327374771004216}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.19947808428736089
Fold 2 IBS: 0.20408835087101088
Fold 3 IBS: 0.19272298691144701
Fold 4 IBS: 0.21264381617545072

Fold 5 IBS: 0.21386443466586402
[I 2024-04-16 02:05:38,316] Trial 93 finished with value: 0.2045595345822267 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.5498688861577421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029844645175168258}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.2095914999638493
Fold 2 IBS: 0.20254997001853908
Fold 3 IBS: 0.19693136056894167
Fold 4 IBS: 0.21511135614957475
Fold 5 IBS: 0.21430028358953207
[I 2024-04-16 02:05:49,271] Trial 94 finished with value: 0.20769689405808736 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.5904725395446608, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07562078772066635}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.2099450942179432
Fold 2 IBS: 0.20626071819604755
Fold 3 IBS: 0.2001364189092279
Fold 4 IBS: 0.21914601024687266
Fold 5 IBS: 0.21149628123419964
[I 2024-04-16 02:06:00,125] Trial 95 finished with value: 0.2093969045608582 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 19, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.620275671193273, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04832121173334747}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.20274027066544437
Fold 2 IBS: 0.20572534198326992
Fold 3 IBS: 0.19412062388553641
Fold 4 IBS: 0.21269611068612085
Fold 5 IBS: 0.21555384004314132
[I 2024-04-16 02:06:10,687] Trial 96 finished with value: 0.20616723745270255 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.5308626685462309, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030552095508053996}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.2114789109028932
Fold 2 IBS: 0.2080135008212799
Fold 3 IBS: 0.19650354529317113
Fold 4 IBS: 0.21460725669290634
Fold 5 IBS: 0.2163800140457081
[I 2024-04-16 02:06:14,747] Trial 97 finished with value: 0.20939664555119175 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.4693979321374093, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.058930029403229854}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.19995371491789696
Fold 2 IBS: 0.204392554020109
Fold 3 IBS: 0.18983278222232514
Fold 4 IBS: 0.21020290276822842
Fold 5 IBS: 0.21503742513794333
[I 2024-04-16 02:06:25,785] Trial 98 finished with value: 0.20388387581330053 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.7175441789165634, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010405819492596734}. Best is trial 85 with value: 0.20295984562926828.
Fold 1 IBS: 0.20160410943664786
Fold 2 IBS: 0.20472679347383285
Fold 3 IBS: 0.19002943305764908
Fold 4 IBS: 0.2159881593447927
Fold 5 IBS: 0.21260437269103177
[I 2024-04-16 02:06:34,988] Trial 99 finished with value: 0.20499057360079087 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.7135577842982994, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011499546487471875}. Best is trial 85 with value: 0.20295984562926828.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.20295984562926828], datetime_start=datetime.datetime(2024, 4, 16, 2, 4, 9, 661297), datetime_complete=datetime.datetime(2024, 4, 16, 2, 4, 19, 775674), params={'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.6084827037288676, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03342457164243477}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for IBS:
 0.20295984562926828

In [56]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [57]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.847
train_ibs:  0.203

#### Test

In [58]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [59]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=12, max_features=None, max_leaf_nodes=9,
                     max_samples=0.7321959730404333, min_samples_leaf=2,
                     min_samples_split=3,
                     min_weight_fraction_leaf=0.011048621886878659,
                     n_estimators=70, random_state=123, warm_start=True)

test_cindex:  0.613

RandomSurvivalForest(max_depth=6, max_leaf_nodes=13,
                     max_samples=0.6084827037288676, min_samples_leaf=2,
                     min_samples_split=3,
                     min_weight_fraction_leaf=0.03342457164243477,
                     n_estimators=397, oob_score=True, random_state=123)

test_ibs:  0.219

In [60]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [61]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [62]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 02:06:38,160] A new study created in memory with name: no-name-39a1d3d3-8211-4344-9c73-bc3c87220427

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 02:06:40,044] Trial 0 finished with value: 0.6880024605427189 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:06:44,692] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.5784313725490197
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6056338028169014
[I 2024-04-16 02:06:52,604] Trial 2 finished with value: 0.6398796414625755 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.5882352941176471
Fold 4 C-index: 0.5970464135021097
Fold 5 C-index: 0.5845070422535211
[I 2024-04-16 02:06:53,354] Trial 3 finished with value: 0.643649308416214 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:06:56,438] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:06:59,938] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 02:07:01,981] Trial 6 finished with value: 0.6842358228887756 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.5882352941176471
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.6572769953051644
[I 2024-04-16 02:07:06,609] Trial 7 finished with value: 0.626197778176085 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6385281385281385
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.5514705882352942
Fold 4 C-index: 0.6181434599156118
Fold 5 C-index: 0.5892018779342723
[I 2024-04-16 02:07:06,884] Trial 8 finished with value: 0.6209866700655204 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6341991341991342
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.5220588235294118
Fold 4 C-index: 0.5759493670886076
Fold 5 C-index: 0.5751173708920188
[I 2024-04-16 02:07:17,255] Trial 9 finished with value: 0.6052149391418344 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:07:21,097] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6603375527426161
Fold 5 C-index: 0.6150234741784038
[I 2024-04-16 02:07:23,443] Trial 11 finished with value: 0.6649716196953831 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.6880024605427189.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7230046948356808
[I 2024-04-16 02:07:26,071] Trial 12 finished with value: 0.7240013613915719 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6561181434599156
Fold 5 C-index: 0.6150234741784038
[I 2024-04-16 02:07:29,018] Trial 13 finished with value: 0.6642630192241242 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.5980392156862745
Fold 4 C-index: 0.6434599156118144
Fold 5 C-index: 0.6056338028169014
[I 2024-04-16 02:07:31,436] Trial 14 finished with value: 0.6619049418013531 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.5931372549019608

Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.596244131455399
[I 2024-04-16 02:07:33,051] Trial 15 finished with value: 0.6572996018372016 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6053921568627451
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.6032863849765259
[I 2024-04-16 02:07:35,487] Trial 16 finished with value: 0.6625717815773451 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.6103286384976526
[I 2024-04-16 02:07:37,420] Trial 17 finished with value: 0.6650014002424257 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:07:40,284] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.6009389671361502
[I 2024-04-16 02:07:42,697] Trial 19 finished with value: 0.6653093431978864 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:07:42,966] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6431924882629108
[I 2024-04-16 02:07:45,851] Trial 21 finished with value: 0.6859621463295443 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 02:07:47,943] Trial 22 finished with value: 0.697097647143267 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7240013613915719.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:07:50,126] Trial 23 finished with value: 0.727254849978047 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.727254849978047.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 02:07:52,374] Trial 24 finished with value: 0.6893214918587088 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.727254849978047.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.704225352112676
[I 2024-04-16 02:07:54,323] Trial 25 finished with value: 0.7049400208307768 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.727254849978047.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.5931372549019608
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6009389671361502
[I 2024-04-16 02:08:06,235] Trial 26 finished with value: 0.6454364976269767 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7226268366017338, 'min_weight_fraction_leaf': 0.14724522382749441}. Best is trial 23 with value: 0.727254849978047.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.5882352941176471
Fold 4 C-index: 0.6223628691983122
Fold 5 C-index: 0.6009389671361502
[I 2024-04-16 02:08:08,138] Trial 27 finished with value: 0.6528647853977813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.0910755188453143}. Best is trial 23 with value: 0.727254849978047.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.5637254901960784
Fold 4 C-index: 0.6139240506329114
Fold 5 C-index: 0.5938967136150235
[I 2024-04-16 02:08:10,363] Trial 28 finished with value: 0.6405917184212702 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9159590537617217, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.727254849978047.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 02:08:12,194] Trial 29 finished with value: 0.6892390915587617 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8201511224658254, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 23 with value: 0.727254849978047.

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:08:13,663] Trial 30 finished with value: 0.7371278793612779 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.05879574792157449}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 02:08:15,173] Trial 31 finished with value: 0.7241162639548113 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6298966865274057, 'min_weight_fraction_leaf': 0.05405927482118079}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:08:16,695] Trial 32 finished with value: 0.7278744044741836 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.722056772295139, 'min_weight_fraction_leaf': 0.06665303212999554}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 02:08:18,331] Trial 33 finished with value: 0.7056474216130966 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7504103077643619, 'min_weight_fraction_leaf': 0.07228058521385833}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6572769953051644
[I 2024-04-16 02:08:19,564] Trial 34 finished with value: 0.6895518942759198 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 218, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.699719011795045, 'min_weight_fraction_leaf': 0.1126902739511941}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6645569620253164
Fold 5 C-index: 0.6009389671361502
[I 2024-04-16 02:08:22,564] Trial 35 finished with value: 0.6592998479153083 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 282, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6215694472638225, 'min_weight_fraction_leaf': 0.16733609036803293}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 02:08:26,723] Trial 36 finished with value: 0.6529580952626111 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5190557919565845, 'min_weight_fraction_leaf': 0.05223373774757657}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.5882352941176471
Fold 4 C-index: 0.6603375527426161
Fold 5 C-index: 0.6056338028169014
[I 2024-04-16 02:08:27,934] Trial 37 finished with value: 0.6502244468185497 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 168, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8268387836003009, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.5955882352941176
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.6009389671361502
[I 2024-04-16 02:08:29,548] Trial 38 finished with value: 0.6562909602405608 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6034576762401722, 'min_weight_fraction_leaf': 0.22096529439752421}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.5882352941176471
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 02:08:34,923] Trial 39 finished with value: 0.6367783453921934 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5204645655829614, 'min_weight_fraction_leaf': 0.07994626083099707}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.5833333333333334
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6150234741784038
[I 2024-04-16 02:08:35,756] Trial 40 finished with value: 0.6522771892189347 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7462583966462045, 'min_weight_fraction_leaf': 0.027601004831219272}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:08:37,274] Trial 41 finished with value: 0.7306792116674868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6676760673731118, 'min_weight_fraction_leaf': 0.0019860067692131778}. Best is trial 30 with value: 0.7371278793612779.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:08:38,968] Trial 42 finished with value: 0.7428133842882199 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6725672668712916, 'min_weight_fraction_leaf': 0.06134016294643}. Best is trial 42 with value: 0.7428133842882199.
Fold 1 C-index: 0.5995670995670995
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.5955882352941176
Fold 4 C-index: 0.6687763713080169
Fold 5 C-index: 0.6197183098591549
[I 2024-04-16 02:08:40,366] Trial 43 finished with value: 0.6583371460628207 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 241, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6668644793057505, 'min_weight_fraction_leaf': 0.27764552944355786}. Best is trial 42 with value: 0.7428133842882199.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 02:08:42,359] Trial 44 finished with value: 0.737601383362791 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7759111622743924, 'min_weight_fraction_leaf': 0.020939392004228168}. Best is trial 42 with value: 0.7428133842882199.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:08:44,405] Trial 45 finished with value: 0.7407014414381775 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7992326082303076, 'min_weight_fraction_leaf': 0.017544745457266815}. Best is trial 42 with value: 0.7428133842882199.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 02:08:46,337] Trial 46 finished with value: 0.7442746896891628 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8374517334024905, 'min_weight_fraction_leaf': 0.016236230529503112}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6384976525821596
[I 2024-04-16 02:08:52,386] Trial 47 finished with value: 0.6446913761614794 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 337, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7849239207353804, 'min_weight_fraction_leaf': 0.021098279381249082}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 02:08:55,401] Trial 48 finished with value: 0.711141074770562 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8411222155096425, 'min_weight_fraction_leaf': 0.02396147939857703}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6197183098591549
[I 2024-04-16 02:08:57,172] Trial 49 finished with value: 0.6670938708470958 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9493868237918467, 'min_weight_fraction_leaf': 0.09131723435674605}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.6150234741784038
[I 2024-04-16 02:08:58,693] Trial 50 finished with value: 0.6694212591599145 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 261, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9280120630096638, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 02:09:00,350] Trial 51 finished with value: 0.7397527905309517 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.852942161098399, 'min_weight_fraction_leaf': 0.0006876237008103317}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:09:02,025] Trial 52 finished with value: 0.7423040831350611 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8502293105839545, 'min_weight_fraction_leaf': 0.022233568236218443}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7417840375586855
[I 2024-04-16 02:09:03,671] Trial 53 finished with value: 0.7414405542440318 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8548160480381581, 'min_weight_fraction_leaf': 0.016628923530392713}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:09:05,299] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8706643563795502, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7136150234741784
[I 2024-04-16 02:09:07,162] Trial 55 finished with value: 0.7291476435952751 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 371, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8533727095867945, 'min_weight_fraction_leaf': 0.014643856592889594}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7183098591549296
[I 2024-04-16 02:09:09,103] Trial 56 finished with value: 0.7329015514372819 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8027691184709107, 'min_weight_fraction_leaf': 0.0440022666017771}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6854460093896714
[I 2024-04-16 02:09:10,783] Trial 57 finished with value: 0.7001918336095683 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.917106156867945, 'min_weight_fraction_leaf': 0.005710115116937236}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:09:12,632] Trial 58 finished with value: 0.7243162567544077 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8905544306961753, 'min_weight_fraction_leaf': 0.08485695105073782}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.5822510822510822
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.5808823529411765
Fold 4 C-index: 0.6265822784810127
Fold 5 C-index: 0.6150234741784038
[I 2024-04-16 02:09:21,083] Trial 59 finished with value: 0.6291621232846207 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 361, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9593167823251865, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 46 with value: 0.7442746896891628.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 02:09:22,782] Trial 60 finished with value: 0.6820065619239479 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7881446161194676, 'min_weight_fraction_leaf': 0.02809633032318659}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:09:25,318] Trial 61 finished with value: 0.7414602012785212 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8485258435065398, 'min_weight_fraction_leaf': 0.018065269385643675}. Best is trial 46 with value: 0.7442746896891628.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.7699530516431925
[I 2024-04-16 02:09:27,033] Trial 62 finished with value: 0.7652954602317759 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8483150285425073, 'min_weight_fraction_leaf': 0.04455698715672468}. Best is trial 62 with value: 0.7652954602317759.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 02:09:29,104] Trial 63 finished with value: 0.7526301701656043 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8153424971876968, 'min_weight_fraction_leaf': 0.05777062742557772}. Best is trial 62 with value: 0.7652954602317759.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7605633802816901
[I 2024-04-16 02:09:31,812] Trial 64 finished with value: 0.7670879929955418 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 389, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9030275238323328, 'min_weight_fraction_leaf': 0.05414057060841304}. Best is trial 64 with value: 0.7670879929955418.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 02:09:34,521] Trial 65 finished with value: 0.7003385892193796 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 386, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9997828148687242, 'min_weight_fraction_leaf': 0.060749255963002895}. Best is trial 64 with value: 0.7670879929955418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 02:09:36,487] Trial 66 finished with value: 0.7201168440844303 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9116678681017002, 'min_weight_fraction_leaf': 0.10014252779245705}. Best is trial 64 with value: 0.7670879929955418.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 02:09:38,511] Trial 67 finished with value: 0.7055624406199376 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 399, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9518061735506921, 'min_weight_fraction_leaf': 0.04372529131843843}. Best is trial 64 with value: 0.7670879929955418.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7370892018779343
[I 2024-04-16 02:09:40,811] Trial 68 finished with value: 0.7439918468481412 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8249964956393689, 'min_weight_fraction_leaf': 0.0749646800894885}. Best is trial 64 with value: 0.7670879929955418.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 02:09:43,337] Trial 69 finished with value: 0.7174276868480904 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 443, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8116175962915894, 'min_weight_fraction_leaf': 0.07144862239167975}. Best is trial 64 with value: 0.7670879929955418.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 02:09:45,559] Trial 70 finished with value: 0.6706187371300163 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7507995260356715, 'min_weight_fraction_leaf': 0.15556754145439744}. Best is trial 64 with value: 0.7670879929955418.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7793427230046949
[I 2024-04-16 02:09:47,443] Trial 71 finished with value: 0.7709313965541483 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8798463281112558, 'min_weight_fraction_leaf': 0.05105341246916396}. Best is trial 71 with value: 0.7709313965541483.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 02:09:49,619] Trial 72 finished with value: 0.7857233094861958 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8886110509588371, 'min_weight_fraction_leaf': 0.04865148796524783}. Best is trial 72 with value: 0.7857233094861958.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6995305164319249
[I 2024-04-16 02:09:51,639] Trial 73 finished with value: 0.7184676400990387 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.887272512390999, 'min_weight_fraction_leaf': 0.11414279524890994}. Best is trial 72 with value: 0.7857233094861958.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8075117370892019
[I 2024-04-16 02:09:53,858] Trial 74 finished with value: 0.798193882489867 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 414, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9406113539397531, 'min_weight_fraction_leaf': 0.051766283827397126}. Best is trial 74 with value: 0.798193882489867.

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:09:56,114] Trial 75 finished with value: 0.7919284258542069 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 425, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9302589354914842, 'min_weight_fraction_leaf': 0.04544232839207828}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 02:10:06,860] Trial 76 finished with value: 0.6657310236449724 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 422, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9474150071538826, 'min_weight_fraction_leaf': 0.04523038539792365}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:10:09,129] Trial 77 finished with value: 0.7440886133380077 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9756497134879777, 'min_weight_fraction_leaf': 0.08945575936069623}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7323943661971831
[I 2024-04-16 02:10:11,527] Trial 78 finished with value: 0.721090113017281 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9057895811683444, 'min_weight_fraction_leaf': 0.03658987723033896}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 02:10:13,551] Trial 79 finished with value: 0.7009124860174382 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9351896473479294, 'min_weight_fraction_leaf': 0.1322967856628576}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 02:10:15,512] Trial 80 finished with value: 0.6762318498526982 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.2869597372530869, 'min_weight_fraction_leaf': 0.05503387761928645}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:10:17,770] Trial 81 finished with value: 0.7496301961683229 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9779437098172693, 'min_weight_fraction_leaf': 0.08294355378118813}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7089201877934272
[I 2024-04-16 02:10:20,018] Trial 82 finished with value: 0.7266185812726036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 438, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9714179165506742, 'min_weight_fraction_leaf': 0.10305979769311778}. Best is trial 74 with value: 0.798193882489867.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8356807511737089
[I 2024-04-16 02:10:22,540] Trial 83 finished with value: 0.8235342848625861 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9968229953545815, 'min_weight_fraction_leaf': 0.03500411641281186}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:10:25,001] Trial 84 finished with value: 0.7603737139436724 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8745292081972509, 'min_weight_fraction_leaf': 0.06978076530836103}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.755868544600939
[I 2024-04-16 02:10:27,258] Trial 85 finished with value: 0.7613616563661397 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8752516708990188, 'min_weight_fraction_leaf': 0.06654311469772003}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-16 02:10:29,822] Trial 86 finished with value: 0.7081700820006118 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8788554738567019, 'min_weight_fraction_leaf': 0.03545785949397051}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6150234741784038
[I 2024-04-16 02:10:32,778] Trial 87 finished with value: 0.6678582202504497 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9338597003552408, 'min_weight_fraction_leaf': 0.06862585052144277}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.6619718309859155
[I 2024-04-16 02:10:44,023] Trial 88 finished with value: 0.6631752228436392 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9961313077361209, 'min_weight_fraction_leaf': 0.09440407202760032}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 02:10:47,096] Trial 89 finished with value: 0.7899721880437616 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8723997873765906, 'min_weight_fraction_leaf': 0.05034050634583893}. Best is trial 83 with value: 0.8235342848625861.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8215962441314554
[I 2024-04-16 02:10:49,801] Trial 90 finished with value: 0.8046426912066954 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9174706440020196, 'min_weight_fraction_leaf': 0.05229809381774074}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7934272300469484
[I 2024-04-16 02:10:52,204] Trial 91 finished with value: 0.792681768934417 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9097343417070818, 'min_weight_fraction_leaf': 0.04751958776912153}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7981220657276995
[I 2024-04-16 02:10:54,673] Trial 92 finished with value: 0.7944594806593118 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9049411312014414, 'min_weight_fraction_leaf': 0.04903949421220949}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.812206572769953
[I 2024-04-16 02:10:57,223] Trial 93 finished with value: 0.7947884334936264 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9097938166241161, 'min_weight_fraction_leaf': 0.05286138576758156}. Best is trial 83 with value: 0.8235342848625861.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8732394366197183
[I 2024-04-16 02:10:59,549] Trial 94 finished with value: 0.8354445506382913 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9262205993297506, 'min_weight_fraction_leaf': 0.03407030655455595}. Best is trial 94 with value: 0.8354445506382913.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7464788732394366
[I 2024-04-16 02:11:01,962] Trial 95 finished with value: 0.7523202352952072 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9223037654995306, 'min_weight_fraction_leaf': 0.03264332276409167}. Best is trial 94 with value: 0.8354445506382913.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:11:04,318] Trial 96 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.16631853158382698, 'min_weight_fraction_leaf': 0.3157465264411285}. Best is trial 94 with value: 0.8354445506382913.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.8028169014084507
[I 2024-04-16 02:11:06,983] Trial 97 finished with value: 0.7800853806813898 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9670785018422641, 'min_weight_fraction_leaf': 0.0337661678405949}. Best is trial 94 with value: 0.8354445506382913.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.7511737089201878
[I 2024-04-16 02:11:09,639] Trial 98 finished with value: 0.7551249372177921 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9392629144294254, 'min_weight_fraction_leaf': 0.08081485110788234}. Best is trial 94 with value: 0.8354445506382913.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9156118143459916

[I 2024-04-16 02:11:12,113] A new study created in memory with name: no-name-c72f0a94-f9f6-4421-846a-26c751a9b15c

Fold 5 C-index: 0.8873239436619719
[I 2024-04-16 02:11:12,104] Trial 99 finished with value: 0.8466420280976455 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 470, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9069233738536542, 'min_weight_fraction_leaf': 0.010939301482941477}. Best is trial 99 with value: 0.8466420280976455.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.8466420280976455], datetime_start=datetime.datetime(2024, 4, 16, 2, 11, 9, 643639), datetime_complete=datetime.datetime(2024, 4, 16, 2, 11, 12, 104412), params={'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 470, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9069233738536542, 'min_weight_fraction_leaf': 0.010939301482941477}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=99, value=None)


* Best Score for C-index:
 0.8466420280976455

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.20887497255981563
Fold 2 IBS: 0.21621704503642306
Fold 3 IBS: 0.2024801053829135
Fold 4 IBS: 0.21947570842721104
Fold 5 IBS: 0.2162020107996032
[I 2024-04-16 02:11:18,702] Trial 0 finished with value: 0.21264996844119327 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-16 02:11:28,162] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21200166598001405
Fold 2 IBS: 0.21874427795694107
Fold 3 IBS: 0.20373336220202878
Fold 4 IBS: 0.22311371096781293
Fold 5 IBS: 0.2175962613075134
[I 2024-04-16 02:11:37,957] Trial 2 finished with value: 0.21503785568286204 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.2120015633607761
Fold 2 IBS: 0.22088329945789853
Fold 3 IBS: 0.20430168070482022
Fold 4 IBS: 0.22363607200231606
Fold 5 IBS: 0.21762185618389415
[I 2024-04-16 02:11:40,758] Trial 3 finished with value: 0.215688894341941 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-16 02:11:48,339] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-16 02:11:51,846] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21044196508615653
Fold 2 IBS: 0.21666665410429722
Fold 3 IBS: 0.20177941244677342
Fold 4 IBS: 0.22055475446003336
Fold 5 IBS: 0.21576714859843704
[I 2024-04-16 02:11:59,035] Trial 6 finished with value: 0.2130419869391395 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.2108677468322441
Fold 2 IBS: 0.21802765125699375
Fold 3 IBS: 0.20336566968195197
Fold 4 IBS: 0.2224239176618692
Fold 5 IBS: 0.21548066689163486
[I 2024-04-16 02:12:03,547] Trial 7 finished with value: 0.21403313046493877 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21230362071771564
Fold 2 IBS: 0.22048782059350058
Fold 3 IBS: 0.20356410047581658
Fold 4 IBS: 0.22424927661259103
Fold 5 IBS: 0.21772827042150147
[I 2024-04-16 02:12:04,462] Trial 8 finished with value: 0.21566661776422508 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21334158262310396
Fold 2 IBS: 0.22070421295505757
Fold 3 IBS: 0.2046306755151983
Fold 4 IBS: 0.22427053295441515
Fold 5 IBS: 0.21808468833874012
[I 2024-04-16 02:12:13,928] Trial 9 finished with value: 0.21620633847730303 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-16 02:12:21,708] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.21139020945695725
Fold 2 IBS: 0.21932872047248542
Fold 3 IBS: 0.2044811635815596
Fold 4 IBS: 0.22206426125642373
Fold 5 IBS: 0.21615141771186264
[I 2024-04-16 02:12:28,202] Trial 11 finished with value: 0.21468315449585776 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21264996844119327.
Fold 1 IBS: 0.20645458964572122
Fold 2 IBS: 0.21360045748488968
Fold 3 IBS: 0.2012530410374075
Fold 4 IBS: 0.21701205997278938
Fold 5 IBS: 0.2119879160383701
[I 2024-04-16 02:12:38,641] Trial 12 finished with value: 0.2100616128358356 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.2122280725773843
Fold 2 IBS: 0.21861429053937512
Fold 3 IBS: 0.20314800515302528
Fold 4 IBS: 0.22215683146399692
Fold 5 IBS: 0.2169622275403228
[I 2024-04-16 02:12:48,163] Trial 13 finished with value: 0.2146218854548209 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.21250882039364632
Fold 2 IBS: 0.21861738969054786
Fold 3 IBS: 0.2029900570836353
Fold 4 IBS: 0.22261700077331897
Fold 5 IBS: 0.2167544080870301
[I 2024-04-16 02:12:54,787] Trial 14 finished with value: 0.21469753520563567 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.2100616128358356.

Fold 1 IBS: 0.211970405663517
Fold 2 IBS: 0.2193450205023294
Fold 3 IBS: 0.20375861758747096
Fold 4 IBS: 0.22242897498925499
Fold 5 IBS: 0.21688985081859083
[I 2024-04-16 02:12:59,210] Trial 15 finished with value: 0.2148785739122326 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.21375883841123966
Fold 2 IBS: 0.22081077053545392
Fold 3 IBS: 0.20463751592784296
Fold 4 IBS: 0.22450321610968552
Fold 5 IBS: 0.21838240845419638
[I 2024-04-16 02:13:08,128] Trial 16 finished with value: 0.2164185498876837 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.21007564260529998
Fold 2 IBS: 0.21598412584938495
Fold 3 IBS: 0.20179592227970522
Fold 4 IBS: 0.21971533111862213
Fold 5 IBS: 0.2160481278961671
[I 2024-04-16 02:13:13,990] Trial 17 finished with value: 0.21272382994983588 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-16 02:13:16,612] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.21210012501185535
Fold 2 IBS: 0.2187797104133011
Fold 3 IBS: 0.2033005937373109
Fold 4 IBS: 0.2223379364608223
Fold 5 IBS: 0.21678440672407415
[I 2024-04-16 02:13:23,431] Trial 19 finished with value: 0.21466055446947277 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.214059763070043
Fold 2 IBS: 0.22169895585806657
Fold 3 IBS: 0.20441597820373575
Fold 4 IBS: 0.2258542405401879
Fold 5 IBS: 0.22061798201802002
[I 2024-04-16 02:13:23,830] Trial 20 finished with value: 0.21732938393801066 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.21045770378060433
Fold 2 IBS: 0.21596342851070546
Fold 3 IBS: 0.20212676836226834
Fold 4 IBS: 0.22023833929595876
Fold 5 IBS: 0.21594531104210862
[I 2024-04-16 02:13:29,162] Trial 21 finished with value: 0.2129463101983291 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6637755741118154, 'min_weight_fraction_leaf': 0.19547198867705698}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.21051038897277555
Fold 2 IBS: 0.21658169415199335
Fold 3 IBS: 0.2017416837151515
Fold 4 IBS: 0.2206961486187388
Fold 5 IBS: 0.2154792392285702
[I 2024-04-16 02:13:33,367] Trial 22 finished with value: 0.21300183093744587 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7318054513307203, 'min_weight_fraction_leaf': 0.22394977944335293}. Best is trial 12 with value: 0.2100616128358356.
Fold 1 IBS: 0.20845323553539372
Fold 2 IBS: 0.21077251413267958
Fold 3 IBS: 0.19824191984283848
Fold 4 IBS: 0.21659415741655375
Fold 5 IBS: 0.21498669141578183
[I 2024-04-16 02:13:41,237] Trial 23 finished with value: 0.20980970366864948 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8586225126451933, 'min_weight_fraction_leaf': 0.14892855232926483}. Best is trial 23 with value: 0.20980970366864948.
Fold 1 IBS: 0.19976739655769596
Fold 2 IBS: 0.20411315912222314
Fold 3 IBS: 0.1918612402798652
Fold 4 IBS: 0.20673434787209588
Fold 5 IBS: 0.21290926786124925
[I 2024-04-16 02:13:48,903] Trial 24 finished with value: 0.20307708233862587 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8808353985048918, 'min_weight_fraction_leaf': 0.03752123016483107}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.1984214965552098
Fold 2 IBS: 0.20552697542498816
Fold 3 IBS: 0.19000567515657896
Fold 4 IBS: 0.20514946240785498
Fold 5 IBS: 0.2174946612829704
[I 2024-04-16 02:13:56,486] Trial 25 finished with value: 0.20331965416552045 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9102757068498641, 'min_weight_fraction_leaf': 0.022865987525340803}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.19844492525724752
Fold 2 IBS: 0.2069776840841401
Fold 3 IBS: 0.19138270170175334
Fold 4 IBS: 0.20985533315932065
Fold 5 IBS: 0.21553097922227166
[I 2024-04-16 02:14:03,258] Trial 26 finished with value: 0.20443832468494666 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8621028183964272, 'min_weight_fraction_leaf': 0.037688029167239734}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.19690366595678283
Fold 2 IBS: 0.20733953686548828
Fold 3 IBS: 0.19081591538840909
Fold 4 IBS: 0.2086170588829637
Fold 5 IBS: 0.21669554679786157
[I 2024-04-16 02:14:09,551] Trial 27 finished with value: 0.20407434477830105 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 276, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.909985561991707, 'min_weight_fraction_leaf': 0.03541928269070217}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.19860866437328326
Fold 2 IBS: 0.20688068101544496
Fold 3 IBS: 0.19284464461683418
Fold 4 IBS: 0.20941834120270655
Fold 5 IBS: 0.21686047778740122
[I 2024-04-16 02:14:14,443] Trial 28 finished with value: 0.204922561799134 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 209, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9215424944163799, 'min_weight_fraction_leaf': 0.038085964870275116}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.2050563329183101
Fold 2 IBS: 0.2074171051178863
Fold 3 IBS: 0.1964082772506125
Fold 4 IBS: 0.20919591798644208
Fold 5 IBS: 0.21303435664764855
[I 2024-04-16 02:14:23,651] Trial 29 finished with value: 0.2062223979841799 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 414, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8028554517852617, 'min_weight_fraction_leaf': 0.07767681407101723}. Best is trial 24 with value: 0.20307708233862587.

Fold 1 IBS: 0.2079372669531199
Fold 2 IBS: 0.21242404225545655
Fold 3 IBS: 0.20045543323040851
Fold 4 IBS: 0.21635030239367528
Fold 5 IBS: 0.2147192598847946
[I 2024-04-16 02:14:30,037] Trial 30 finished with value: 0.210377260943491 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 283, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9203253020321057, 'min_weight_fraction_leaf': 0.10064443687249378}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.19727813448146547
Fold 2 IBS: 0.20858268136627384
Fold 3 IBS: 0.19133027071099074
Fold 4 IBS: 0.20961796894193035
Fold 5 IBS: 0.2168411172174772
[I 2024-04-16 02:14:37,816] Trial 31 finished with value: 0.2047300345436275 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8376685926746728, 'min_weight_fraction_leaf': 0.03524384862131948}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.2022262429646908
Fold 2 IBS: 0.20095393408214857
Fold 3 IBS: 0.19162540697872774
Fold 4 IBS: 0.2069692175581434
Fold 5 IBS: 0.21524579729250276
[I 2024-04-16 02:14:43,932] Trial 32 finished with value: 0.20340411977524267 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 233, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7296900339466866, 'min_weight_fraction_leaf': 0.03717955895517932}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.2094121689404591
Fold 2 IBS: 0.20865966182442425
Fold 3 IBS: 0.19705654502261138
Fold 4 IBS: 0.21574769664583576
Fold 5 IBS: 0.21230367949185994
[I 2024-04-16 02:14:49,841] Trial 33 finished with value: 0.20863595038503813 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 232, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7308255980635789, 'min_weight_fraction_leaf': 0.106220792392703}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.2021872746250637
Fold 2 IBS: 0.20537013891621947
Fold 3 IBS: 0.19519330324277503
Fold 4 IBS: 0.20916611286585107
Fold 5 IBS: 0.21193674644436603
[I 2024-04-16 02:14:53,551] Trial 34 finished with value: 0.20477071521885506 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 151, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6268660720519807, 'min_weight_fraction_leaf': 0.05338212516262128}. Best is trial 24 with value: 0.20307708233862587.
Fold 1 IBS: 0.20217563477397843
Fold 2 IBS: 0.2002011120726587
Fold 3 IBS: 0.19138992964812687
Fold 4 IBS: 0.20334311410398317
Fold 5 IBS: 0.21371389762697401
[I 2024-04-16 02:15:03,730] Trial 35 finished with value: 0.20216473764514423 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 452, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9232709855948563, 'min_weight_fraction_leaf': 0.020933349393938833}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20763324186403917
Fold 2 IBS: 0.2137237613728042
Fold 3 IBS: 0.20177585496437336
Fold 4 IBS: 0.21789160688026118
Fold 5 IBS: 0.21396071396261745
[I 2024-04-16 02:15:14,438] Trial 36 finished with value: 0.21099703580881907 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 455, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.932436875496941, 'min_weight_fraction_leaf': 0.08989546794598328}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21388154931435469
Fold 2 IBS: 0.22127715674546003
Fold 3 IBS: 0.20480823004200702
Fold 4 IBS: 0.22455815900397752
Fold 5 IBS: 0.2184427101956744
[I 2024-04-16 02:15:23,764] Trial 37 finished with value: 0.2165935610602947 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.48374185284453186, 'min_weight_fraction_leaf': 0.010480103796959938}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21257972761383165
Fold 2 IBS: 0.21945139579709608
Fold 3 IBS: 0.20372848147746603
Fold 4 IBS: 0.22350027469232484
Fold 5 IBS: 0.21773294887662817
[I 2024-04-16 02:15:34,251] Trial 38 finished with value: 0.21539856569146934 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 454, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6038536292804044, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.204727734507388
Fold 2 IBS: 0.20396777735691934
Fold 3 IBS: 0.19734411874071614
Fold 4 IBS: 0.20835336584453204
Fold 5 IBS: 0.21199191067970163
[I 2024-04-16 02:15:45,420] Trial 39 finished with value: 0.2052769814258514 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 410, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8303265348079809, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2115253873639437
Fold 2 IBS: 0.21923351829582519
Fold 3 IBS: 0.2034729962948836
Fold 4 IBS: 0.2225856361747085
Fold 5 IBS: 0.21681532779894244
[I 2024-04-16 02:15:49,424] Trial 40 finished with value: 0.21472657318566069 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 166, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.742351076630073, 'min_weight_fraction_leaf': 0.15722845677354416}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.1958889569053065
Fold 2 IBS: 0.20864642372301198
Fold 3 IBS: 0.1898994009827103
Fold 4 IBS: 0.2072490471058236
Fold 5 IBS: 0.21909673828492934
[I 2024-04-16 02:15:59,464] Trial 41 finished with value: 0.20415611340035636 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9381806229600564, 'min_weight_fraction_leaf': 0.02140327874776111}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20480168480053507
Fold 2 IBS: 0.2014237415707833
Fold 3 IBS: 0.19549709261482875
Fold 4 IBS: 0.20621757116801467
Fold 5 IBS: 0.21508140903228587
[I 2024-04-16 02:16:05,136] Trial 42 finished with value: 0.20460429983728953 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 236, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.052696214371951294}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19913292387736267
Fold 2 IBS: 0.20404449643299302
Fold 3 IBS: 0.19305548951438595
Fold 4 IBS: 0.20692602359173787
Fold 5 IBS: 0.21489110473353473
[I 2024-04-16 02:16:12,921] Trial 43 finished with value: 0.20361000763000284 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 351, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9441628326936257, 'min_weight_fraction_leaf': 0.025448597376430786}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2106446901851332
Fold 2 IBS: 0.21652207184961764
Fold 3 IBS: 0.2019572444875309
Fold 4 IBS: 0.22035850460185738
Fold 5 IBS: 0.21537970376055518
[I 2024-04-16 02:16:21,015] Trial 44 finished with value: 0.21297244297693885 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 346, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9500906806157486, 'min_weight_fraction_leaf': 0.27306018250858355}. Best is trial 35 with value: 0.20216473764514423.

Fold 1 IBS: 0.21211475811792724
Fold 2 IBS: 0.21925589796211187
Fold 3 IBS: 0.20366334205091433
Fold 4 IBS: 0.2230512764619915
Fold 5 IBS: 0.21727676286318043
[I 2024-04-16 02:16:31,582] Trial 45 finished with value: 0.21507240749122508 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7672440754515626, 'min_weight_fraction_leaf': 0.018436681014022648}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2122142774753628
Fold 2 IBS: 0.2180461080401636
Fold 3 IBS: 0.20407939074493567
Fold 4 IBS: 0.22242943441636348
Fold 5 IBS: 0.2162867488284483
[I 2024-04-16 02:16:40,820] Trial 46 finished with value: 0.2146111919010548 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.37464188710438373, 'min_weight_fraction_leaf': 0.0591629523322859}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2074867502556632
Fold 2 IBS: 0.21311782929106154
Fold 3 IBS: 0.20059368577373685
Fold 4 IBS: 0.21694905035414713
Fold 5 IBS: 0.215277910912542
[I 2024-04-16 02:16:48,529] Trial 47 finished with value: 0.21068504531743013 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9943597315317275, 'min_weight_fraction_leaf': 0.13139401941208892}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2112846708328047
Fold 2 IBS: 0.2170445321448218
Fold 3 IBS: 0.20233987767157013
Fold 4 IBS: 0.22135794217985805
Fold 5 IBS: 0.21594744348709394
[I 2024-04-16 02:16:55,409] Trial 48 finished with value: 0.21359489326322972 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9574691204764653, 'min_weight_fraction_leaf': 0.003021101449419878}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21397516150553247
Fold 2 IBS: 0.22138118288927558
Fold 3 IBS: 0.20483567758373236
Fold 4 IBS: 0.22466815600292053
Fold 5 IBS: 0.21853348739026904
[I 2024-04-16 02:17:02,649] Trial 49 finished with value: 0.21667873307434599 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 326, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8318752166007946, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19984393833288802
Fold 2 IBS: 0.2035448049357034
Fold 3 IBS: 0.19555003228130952
Fold 4 IBS: 0.2071758891802283
Fold 5 IBS: 0.21348171317107692
[I 2024-04-16 02:17:11,167] Trial 50 finished with value: 0.20391927558024125 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.025249698214072788}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20015505224925415
Fold 2 IBS: 0.20246219047292355
Fold 3 IBS: 0.19516573672329346
Fold 4 IBS: 0.2073213421267088
Fold 5 IBS: 0.21341826374271095
[I 2024-04-16 02:17:20,395] Trial 51 finished with value: 0.20370451706297818 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.524503602597301, 'min_weight_fraction_leaf': 0.026057651952811157}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20508554492439546
Fold 2 IBS: 0.20867859640056932
Fold 3 IBS: 0.19698715534462352
Fold 4 IBS: 0.21158868413049398
Fold 5 IBS: 0.2158563632732587
[I 2024-04-16 02:17:28,219] Trial 52 finished with value: 0.20763926881466815 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.38920782663893977, 'min_weight_fraction_leaf': 0.05145188597958649}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21049586735882692
Fold 2 IBS: 0.2174248005464627
Fold 3 IBS: 0.20220958305085224
Fold 4 IBS: 0.22119646001161364
Fold 5 IBS: 0.2167202674010604
[I 2024-04-16 02:17:34,092] Trial 53 finished with value: 0.21360939567376316 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 353, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5784916908553357, 'min_weight_fraction_leaf': 0.0814127395262452}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2139766305868946
Fold 2 IBS: 0.22146604798890115
Fold 3 IBS: 0.20486707838232107
Fold 4 IBS: 0.22466690012234047
Fold 5 IBS: 0.21845086503529498
[I 2024-04-16 02:17:43,221] Trial 54 finished with value: 0.21668550442315046 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5171968394189298, 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2073990396873742
Fold 2 IBS: 0.20679991325793912
Fold 3 IBS: 0.1977846966904625
Fold 4 IBS: 0.2130707420430219
Fold 5 IBS: 0.21397650485177658
[I 2024-04-16 02:17:51,131] Trial 55 finished with value: 0.20780617930611486 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8936754724648079, 'min_weight_fraction_leaf': 0.02011958414286339}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21204924268964292
Fold 2 IBS: 0.21868242416527342
Fold 3 IBS: 0.20357287292296944
Fold 4 IBS: 0.223031668301336
Fold 5 IBS: 0.21658323624520895
[I 2024-04-16 02:17:58,210] Trial 56 finished with value: 0.21478388886488617 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4571967720812072, 'min_weight_fraction_leaf': 0.0648387447623394}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.210442234949459
Fold 2 IBS: 0.21624724843812404
Fold 3 IBS: 0.20218638592191032
Fold 4 IBS: 0.22116268212920548
Fold 5 IBS: 0.21460293684872328
[I 2024-04-16 02:18:04,602] Trial 57 finished with value: 0.2129282976574844 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 366, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6859431566383477, 'min_weight_fraction_leaf': 0.006515571588517732}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21087597971199104
Fold 2 IBS: 0.21434881076370166
Fold 3 IBS: 0.2001484225786739
Fold 4 IBS: 0.21941893125305145
Fold 5 IBS: 0.21426207352943893
[I 2024-04-16 02:18:07,906] Trial 58 finished with value: 0.21181084356737143 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8753831828896583, 'min_weight_fraction_leaf': 0.11156035388666517}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2140253099164433
Fold 2 IBS: 0.22033415350903254
Fold 3 IBS: 0.20469607625158975
Fold 4 IBS: 0.22408137526724536
Fold 5 IBS: 0.21847339049728978
[I 2024-04-16 02:18:10,601] Trial 59 finished with value: 0.21632206108832017 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 115, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9016385507087822, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 35 with value: 0.20216473764514423.

Fold 1 IBS: 0.20305281534009662
Fold 2 IBS: 0.20585495766845885
Fold 3 IBS: 0.1955808964896082
Fold 4 IBS: 0.2074808706865538
Fold 5 IBS: 0.21451345880907943
[I 2024-04-16 02:18:17,678] Trial 60 finished with value: 0.2052965997987594 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 417, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7842199588841721, 'min_weight_fraction_leaf': 0.04700788452182417}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.1998780751185581
Fold 2 IBS: 0.20385564370285802
Fold 3 IBS: 0.19628236070807806
Fold 4 IBS: 0.20757349207763956
Fold 5 IBS: 0.2129679416601216
[I 2024-04-16 02:18:26,297] Trial 61 finished with value: 0.20411150265345107 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 494, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5321473845996627, 'min_weight_fraction_leaf': 0.028219245441125678}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19887798099844028
Fold 2 IBS: 0.2025283766456874
Fold 3 IBS: 0.19249220829979147
Fold 4 IBS: 0.20673348316778806
Fold 5 IBS: 0.21499803964430697
[I 2024-04-16 02:18:35,002] Trial 62 finished with value: 0.20312601775120281 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4244899187726855, 'min_weight_fraction_leaf': 0.02364681901406484}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20215938729550798
Fold 2 IBS: 0.20190647479207005
Fold 3 IBS: 0.19234994318698234
Fold 4 IBS: 0.20470771501804116
Fold 5 IBS: 0.21615826159366455
[I 2024-04-16 02:18:44,700] Trial 63 finished with value: 0.2034563563772532 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.40438530176006743, 'min_weight_fraction_leaf': 0.00027161979821937327}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20186011056351075
Fold 2 IBS: 0.2098179629520962
Fold 3 IBS: 0.19365599543311468
Fold 4 IBS: 0.20899910524017354
Fold 5 IBS: 0.2142934259908852
[I 2024-04-16 02:18:53,686] Trial 64 finished with value: 0.20572532003595606 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.27380269387783357, 'min_weight_fraction_leaf': 0.002059070107898145}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20993353171639859
Fold 2 IBS: 0.21435008140758774
Fold 3 IBS: 0.2012465456831393
Fold 4 IBS: 0.2183910742414935
Fold 5 IBS: 0.21442329507156255
[I 2024-04-16 02:19:01,458] Trial 65 finished with value: 0.21166890562403634 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 441, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.38520763258693147, 'min_weight_fraction_leaf': 0.09096952081464799}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21397145679118826
Fold 2 IBS: 0.22124047878802536
Fold 3 IBS: 0.20496101086886429
Fold 4 IBS: 0.22463679672950546
Fold 5 IBS: 0.2185297507914712
[I 2024-04-16 02:19:08,006] Trial 66 finished with value: 0.21666789879381093 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 382, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.43497415814945134, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20559402062078133
Fold 2 IBS: 0.20897101666271284
Fold 3 IBS: 0.1983170732623849
Fold 4 IBS: 0.21477882632067474
Fold 5 IBS: 0.2144963611083408
[I 2024-04-16 02:19:14,927] Trial 67 finished with value: 0.2084314595949789 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 312, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3440348544348428, 'min_weight_fraction_leaf': 0.042562433580597275}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2095812876237306
Fold 2 IBS: 0.2165611027971448
Fold 3 IBS: 0.20256959594283938
Fold 4 IBS: 0.22115094569850113
Fold 5 IBS: 0.21521654556133066
[I 2024-04-16 02:19:21,982] Trial 68 finished with value: 0.21301589552470931 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.18504146569474889, 'min_weight_fraction_leaf': 0.06816637774337742}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19688179928745903
Fold 2 IBS: 0.20967597404920454
Fold 3 IBS: 0.1925892168088487
Fold 4 IBS: 0.2089643108923111
Fold 5 IBS: 0.21587894332739
[I 2024-04-16 02:19:32,210] Trial 69 finished with value: 0.20479804887304268 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 486, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.42145456152683036, 'min_weight_fraction_leaf': 0.01601079652870223}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20288479653788713
Fold 2 IBS: 0.21315754505890838
Fold 3 IBS: 0.19725503436121827
Fold 4 IBS: 0.21337709668356947
Fold 5 IBS: 0.21487899254065201
[I 2024-04-16 02:19:39,316] Trial 70 finished with value: 0.20831069303644706 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 299, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.962983545209068, 'min_weight_fraction_leaf': 0.03986270241380998}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19814309276987327
Fold 2 IBS: 0.2015238773796174
Fold 3 IBS: 0.19029064068918788
Fold 4 IBS: 0.20732594582922154
Fold 5 IBS: 0.21571868944580702
[I 2024-04-16 02:19:48,262] Trial 71 finished with value: 0.20260044922274142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4897248144615137, 'min_weight_fraction_leaf': 0.027016760886840914}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19970791313039207
Fold 2 IBS: 0.20331968008932305
Fold 3 IBS: 0.1900059881812209
Fold 4 IBS: 0.20617393356174366
Fold 5 IBS: 0.2149121449062462
[I 2024-04-16 02:19:57,180] Trial 72 finished with value: 0.20282393197378515 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4683353830059733, 'min_weight_fraction_leaf': 0.0007479572258497526}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19757858737484085
Fold 2 IBS: 0.202558685365242
Fold 3 IBS: 0.19094965012169288
Fold 4 IBS: 0.20663164934425687
Fold 5 IBS: 0.2163726685047427
[I 2024-04-16 02:20:05,079] Trial 73 finished with value: 0.20281824814215504 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4776119469681418, 'min_weight_fraction_leaf': 0.0006627744824133366}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2059659307300818
Fold 2 IBS: 0.20811030634708563
Fold 3 IBS: 0.19668332360260352
Fold 4 IBS: 0.21282976394706019
Fold 5 IBS: 0.21361500207612968
[I 2024-04-16 02:20:12,641] Trial 74 finished with value: 0.2074408653405922 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 428, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4468454421915172, 'min_weight_fraction_leaf': 0.06217333396692078}. Best is trial 35 with value: 0.20216473764514423.

Fold 1 IBS: 0.2077943851976713
Fold 2 IBS: 0.2106473346735518
Fold 3 IBS: 0.19934131700455673
Fold 4 IBS: 0.2159624844050163
Fold 5 IBS: 0.21457731226181645
[I 2024-04-16 02:20:20,438] Trial 75 finished with value: 0.20966456670852254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4990384010791153, 'min_weight_fraction_leaf': 0.08585602005375931}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20827922933803078
Fold 2 IBS: 0.21779573671850924
Fold 3 IBS: 0.20254172574221596
Fold 4 IBS: 0.219528369978886
Fold 5 IBS: 0.21421783307752998
[I 2024-04-16 02:20:28,766] Trial 76 finished with value: 0.2124725789710344 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3307984153985737, 'min_weight_fraction_leaf': 0.03758210914369889}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.2104186408257315
Fold 2 IBS: 0.21719798144593283
Fold 3 IBS: 0.2028837584820569
Fold 4 IBS: 0.22081049287140547
Fold 5 IBS: 0.21586285649795567
[I 2024-04-16 02:20:35,569] Trial 77 finished with value: 0.21343474602461648 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.563154795085684, 'min_weight_fraction_leaf': 0.05136569914296}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20687331706982778
Fold 2 IBS: 0.20841785190809867
Fold 3 IBS: 0.19536809447484985
Fold 4 IBS: 0.21478823261760102
Fold 5 IBS: 0.21398948579353397
[I 2024-04-16 02:20:40,438] Trial 78 finished with value: 0.20788739637278225 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.47242573140635374, 'min_weight_fraction_leaf': 0.014733391647988606}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20897734864559758
Fold 2 IBS: 0.21679368417773592
Fold 3 IBS: 0.20186602827867234
Fold 4 IBS: 0.2202332594045996
Fold 5 IBS: 0.21375403360433343
[I 2024-04-16 02:20:46,092] Trial 79 finished with value: 0.2123248708221878 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 261, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6018148502617611, 'min_weight_fraction_leaf': 0.029248910580243273}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.21065700450588828
Fold 2 IBS: 0.21804282244097337
Fold 3 IBS: 0.20251641551382552
Fold 4 IBS: 0.2211659821505311
Fold 5 IBS: 0.21511069141015993
[I 2024-04-16 02:20:54,357] Trial 80 finished with value: 0.21349858320427564 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.47489034796628216, 'min_weight_fraction_leaf': 0.07433628464122868}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.20068257194438102
Fold 2 IBS: 0.2046628415834175
Fold 3 IBS: 0.19407163296642277
Fold 4 IBS: 0.20491394290782833
Fold 5 IBS: 0.21358368794143853
[I 2024-04-16 02:21:02,670] Trial 81 finished with value: 0.20358293546869763 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.42973476331773325, 'min_weight_fraction_leaf': 0.009330180827740136}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.19783242000640164
Fold 2 IBS: 0.20060458723399427
Fold 3 IBS: 0.19268965049881479
Fold 4 IBS: 0.2054443386146317
Fold 5 IBS: 0.21757549874318077
[I 2024-04-16 02:21:10,975] Trial 82 finished with value: 0.20282929901940464 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.505270927431307, 'min_weight_fraction_leaf': 0.0012408052805747832}. Best is trial 35 with value: 0.20216473764514423.
Fold 1 IBS: 0.1946108292522634
Fold 2 IBS: 0.20322073987305117
Fold 3 IBS: 0.190878958012148
Fold 4 IBS: 0.20200706292771348
Fold 5 IBS: 0.2156380007320922
[I 2024-04-16 02:21:19,671] Trial 83 finished with value: 0.20127111815945367 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6410631396472465, 'min_weight_fraction_leaf': 0.016675107870370562}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.19994509032887248
Fold 2 IBS: 0.20309651671660853
Fold 3 IBS: 0.1947756496310836
Fold 4 IBS: 0.20660356751121
Fold 5 IBS: 0.21440451726704812
[I 2024-04-16 02:21:28,222] Trial 84 finished with value: 0.20376506829096455 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.49863901981491127, 'min_weight_fraction_leaf': 0.00025345488923697937}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.19494870495844485
Fold 2 IBS: 0.20321565924506896
Fold 3 IBS: 0.1926319412694526
Fold 4 IBS: 0.20539644988244332
Fold 5 IBS: 0.21836357959328723
[I 2024-04-16 02:21:36,957] Trial 85 finished with value: 0.2029112669897394 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5854761959228917, 'min_weight_fraction_leaf': 0.016485465540755164}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.20042557295536603
Fold 2 IBS: 0.20167081802041853
Fold 3 IBS: 0.19481763609879324
Fold 4 IBS: 0.20769252053954887
Fold 5 IBS: 0.21297350681839608
[I 2024-04-16 02:21:46,917] Trial 86 finished with value: 0.20351601088650453 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5431473102411527, 'min_weight_fraction_leaf': 0.014165798675189818}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.19916437587853317
Fold 2 IBS: 0.20243782408556182
Fold 3 IBS: 0.19365385027776752
Fold 4 IBS: 0.2060313963919286
Fold 5 IBS: 0.214448487973352
[I 2024-04-16 02:21:55,983] Trial 87 finished with value: 0.2031471869214286 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 472, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6424578104871362, 'min_weight_fraction_leaf': 0.04673149698463977}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.21220457636886828
Fold 2 IBS: 0.21783499570674372
Fold 3 IBS: 0.20268319558505982
Fold 4 IBS: 0.22247591397233943
Fold 5 IBS: 0.2161886013613312
[I 2024-04-16 02:22:04,271] Trial 88 finished with value: 0.2142774565988685 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5974293941118125, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.20802100967756304
Fold 2 IBS: 0.21477780666172494
Fold 3 IBS: 0.20246363305878465
Fold 4 IBS: 0.21906994779957642
Fold 5 IBS: 0.21322371338879165
[I 2024-04-16 02:22:11,580] Trial 89 finished with value: 0.21151122211728818 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5057918365838058, 'min_weight_fraction_leaf': 0.03138544888174534}. Best is trial 83 with value: 0.20127111815945367.

Fold 1 IBS: 0.2111555446843108
Fold 2 IBS: 0.2169096073289264
Fold 3 IBS: 0.20194158452124114
Fold 4 IBS: 0.2208206600975687
Fold 5 IBS: 0.2149901028297518
[I 2024-04-16 02:22:19,223] Trial 90 finished with value: 0.21316349989235978 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5525058622907164, 'min_weight_fraction_leaf': 0.014172537425326079}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.1992255839628862
Fold 2 IBS: 0.20148460763610068
Fold 3 IBS: 0.1931898251383408
Fold 4 IBS: 0.20591756041570602
Fold 5 IBS: 0.2141239831125513
[I 2024-04-16 02:22:27,960] Trial 91 finished with value: 0.202788312053117 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6492801798040194, 'min_weight_fraction_leaf': 0.04695670968677439}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.20158206237463078
Fold 2 IBS: 0.203798513917082
Fold 3 IBS: 0.19633893501901384
Fold 4 IBS: 0.20942458022289245
Fold 5 IBS: 0.21285939222609349
[I 2024-04-16 02:22:35,964] Trial 92 finished with value: 0.2048006967519425 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5791915903820954, 'min_weight_fraction_leaf': 0.05890900507286195}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.19693725307990062
Fold 2 IBS: 0.20284782219214292
Fold 3 IBS: 0.19295622628844988
Fold 4 IBS: 0.207322220138095
Fold 5 IBS: 0.21297738649977024
[I 2024-04-16 02:22:44,984] Trial 93 finished with value: 0.20260818163967173 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6327695060118343, 'min_weight_fraction_leaf': 0.030087335786945873}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.19766694160574302
Fold 2 IBS: 0.20128596415531025
Fold 3 IBS: 0.19207548665127097
Fold 4 IBS: 0.20619671270622905
Fold 5 IBS: 0.2129872981801852
[I 2024-04-16 02:22:53,530] Trial 94 finished with value: 0.2020424806597477 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6663783788949234, 'min_weight_fraction_leaf': 0.03685739713985861}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.19747471705326947
Fold 2 IBS: 0.2021557275040954
Fold 3 IBS: 0.19223677611356288
Fold 4 IBS: 0.20558193088761909
Fold 5 IBS: 0.21374735238966583
[I 2024-04-16 02:23:02,131] Trial 95 finished with value: 0.20223930078964253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6550504992158168, 'min_weight_fraction_leaf': 0.010942186556555782}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.20963010372158122
Fold 2 IBS: 0.21444009925375673
Fold 3 IBS: 0.20116304045235323
Fold 4 IBS: 0.21938500886849016
Fold 5 IBS: 0.21513537009665895
[I 2024-04-16 02:23:10,306] Trial 96 finished with value: 0.21195072447856805 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6652054006162402, 'min_weight_fraction_leaf': 0.16582909065569107}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.2069444668408085
Fold 2 IBS: 0.2082237691381431
Fold 3 IBS: 0.198405173760778
Fold 4 IBS: 0.2149878343192732
Fold 5 IBS: 0.21335686376168347
[I 2024-04-16 02:23:18,019] Trial 97 finished with value: 0.20838362156413726 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 435, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.627904161167746, 'min_weight_fraction_leaf': 0.09717476939608155}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.20033468464291748
Fold 2 IBS: 0.20545407613122274
Fold 3 IBS: 0.19375506559266215
Fold 4 IBS: 0.2070796788627915
Fold 5 IBS: 0.21388842816695075
[I 2024-04-16 02:23:26,921] Trial 98 finished with value: 0.20410238667930888 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6873675586989676, 'min_weight_fraction_leaf': 0.04580481622981241}. Best is trial 83 with value: 0.20127111815945367.
Fold 1 IBS: 0.19789362776401528
Fold 2 IBS: 0.20248083672235204
Fold 3 IBS: 0.19249545741412483
Fold 4 IBS: 0.20581472517829802
Fold 5 IBS: 0.2149942532626815
[I 2024-04-16 02:23:34,325] Trial 99 finished with value: 0.20273578006829435 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 422, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6667306722547672, 'min_weight_fraction_leaf': 0.03263686200357049}. Best is trial 83 with value: 0.20127111815945367.


* Best trial for IBS:
 FrozenTrial(number=83, state=TrialState.COMPLETE, values=[0.20127111815945367], datetime_start=datetime.datetime(2024, 4, 16, 2, 21, 10, 981519), datetime_complete=datetime.datetime(2024, 4, 16, 2, 21, 19, 669411), params={'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6410631396472465, 'min_weight_fraction_leaf': 0.016675107870370562}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=83, value=None)


* Best Score for IBS:
 0.20127111815945367

In [63]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [64]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.847
train_ibs:  0.201

#### Test

In [65]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [66]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=16, max_features=None, max_leaf_nodes=16,
                   max_samples=0.9069233738536542, min_samples_leaf=2,
                   min_samples_split=3,
                   min_weight_fraction_leaf=0.010939301482941477,
                   n_estimators=470, random_state=123, warm_start=True)

C-index score: 0.618

ExtraSurvivalTrees(max_depth=7, max_features=None, max_leaf_nodes=18,
                   max_samples=0.6410631396472465, min_samples_split=2,
                   min_weight_fraction_leaf=0.016675107870370562,
                   n_estimators=481, random_state=123, warm_start=True)

IBS: 0.212

In [67]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [68]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 02:23:37,674] A new study created in memory with name: no-name-fcb5e641-f6d9-4667-8038-2cd304daca0f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:24:13,245] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:24:31,613] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:24:50,765] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:25:19,807] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:25:31,267] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:25:34,172] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:04,495] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:12,381] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:26:13,400] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6348039215686274
Fold 4 C-index: 0.6434599156118144
Fold 5 C-index: 0.6737089201877934
[I 2024-04-16 02:27:28,398] Trial 9 finished with value: 0.6608490969281925 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:29:24,939] Trial 10 finished with value: 0.5 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:30:43,499] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.8081282674845877, 'learning_rate': 0.03957576815132133, 'dropout_rate': 0.3592207054036807, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 9.74116027708086, 'min_weight_fraction_leaf': 0.365889927692422, 'max_features': 'log2', 'min_impurity_decrease': 1.459170836380829e-06, 'validation_fraction': 0.7986785049611014, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:31:55,619] Trial 12 finished with value: 0.5 and parameters: {'subsample': 0.3678235114093892, 'learning_rate': 0.04567946973839636, 'dropout_rate': 0.25727844951644346, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.3231056999503768, 'min_weight_fraction_leaf': 0.19696526950140963, 'max_features': 'auto', 'min_impurity_decrease': 1.6810148621356602e-06, 'validation_fraction': 0.8490366656238622, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:32:04,110] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.7784830438231676, 'learning_rate': 0.02439641670004065, 'dropout_rate': 0.4821375662037144, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 6.245821408640139, 'min_weight_fraction_leaf': 0.3469021849356369, 'max_features': 1, 'min_impurity_decrease': 0.002901900339595834, 'validation_fraction': 0.40492470595401014, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:33:15,472] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.5522283925781899, 'learning_rate': 0.010913227078192221, 'dropout_rate': 0.275468298707492, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.2209251544817152, 'max_features': 'log2', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.7267940764758692, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:34:33,260] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8321814107294574, 'learning_rate': 0.03462515781182537, 'dropout_rate': 0.10188162797857298, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 5.585208670000242, 'min_weight_fraction_leaf': 0.3203472576334258, 'max_features': 0.1, 'min_impurity_decrease': 9.84228208509291e-05, 'validation_fraction': 0.9508448160253733, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:34:39,228] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.41637694759398924, 'learning_rate': 0.05102954371215744, 'dropout_rate': 0.4800989647660596, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 9.356569787888832, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': None, 'min_impurity_decrease': 6.315552530348283e-07, 'validation_fraction': 0.6329472651499938, 'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:36:36,512] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.18427032297888507, 'learning_rate': 0.016160179473353013, 'dropout_rate': 0.2643467397617198, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 1.767647956851031, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 'auto', 'min_impurity_decrease': 9.756988906280483e-06, 'validation_fraction': 0.460466512261803, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:36:57,331] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.29960178961969325, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.480521228562659, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 6.571359927175668, 'min_weight_fraction_leaf': 0.3081685769690769, 'max_features': 'auto', 'min_impurity_decrease': 0.00017103826195115595, 'validation_fraction': 0.8334165513948124, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:37:18,490] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.6107103985877803, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.8022840901094805, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 4.726491220462886, 'min_weight_fraction_leaf': 0.23723421649302917, 'max_features': None, 'min_impurity_decrease': 0.005573123702146452, 'validation_fraction': 0.733318779116827, 'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:38:29,496] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.7486596812728094, 'learning_rate': 0.030015766309112166, 'dropout_rate': 0.41862843505834413, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 8.442374914253744, 'min_weight_fraction_leaf': 0.43152288390795446, 'max_features': 0.1, 'min_impurity_decrease': 5.093079199752527e-07, 'validation_fraction': 0.485777565058473, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 17}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:38:46,802] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.6645352255107654, 'learning_rate': 0.09848488597888547, 'dropout_rate': 0.7687435120123771, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.841872183700346, 'min_weight_fraction_leaf': 0.12726799092659097, 'max_features': 'sqrt', 'min_impurity_decrease': 4.129428860721829e-05, 'validation_fraction': 0.26781949045355996, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:08,908] Trial 22 finished with value: 0.5 and parameters: {'subsample': 0.473874743610687, 'learning_rate': 0.08064716128589619, 'dropout_rate': 0.7441459115178709, 'n_estimators': 319, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7836160564934809, 'min_weight_fraction_leaf': 0.08573145040193865, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6571343171562185e-05, 'validation_fraction': 0.3666637457155964, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:17,787] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9031806207514874, 'learning_rate': 0.05231237416288583, 'dropout_rate': 0.9933061120594999, 'n_estimators': 376, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9734842724745505, 'min_weight_fraction_leaf': 0.18816784942881926, 'max_features': 'sqrt', 'min_impurity_decrease': 5.564325269330583e-05, 'validation_fraction': 0.22191224417069177, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:28,344] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.6032411000441751, 'learning_rate': 0.08510490014384028, 'dropout_rate': 0.8499447592488185, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 2.564923335664723, 'min_weight_fraction_leaf': 0.2675376131769848, 'max_features': 'sqrt', 'min_impurity_decrease': 4.632626838690667e-06, 'validation_fraction': 0.5456395158226394, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:39:40,766] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7215349051479215, 'learning_rate': 0.04238950086330006, 'dropout_rate': 0.3050189841876249, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 4.1944004294560635, 'min_weight_fraction_leaf': 0.31435920289715347, 'max_features': 'log2', 'min_impurity_decrease': 0.00032844478717469067, 'validation_fraction': 0.005916255331971709, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:40:23,096] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8806073308147355, 'learning_rate': 0.022376976197093057, 'dropout_rate': 0.6881130985931054, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 2.7801390404743485, 'min_weight_fraction_leaf': 0.14826348238129222, 'max_features': 1, 'min_impurity_decrease': 3.2746646321179855e-06, 'validation_fraction': 0.654336976255422, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:41:22,937] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.6416570269538786, 'learning_rate': 0.08875752985571464, 'dropout_rate': 0.19627515205758927, 'n_estimators': 344, 'criterion': 'friedman_mse', 'ccp_alpha': 5.931957554140308, 'min_weight_fraction_leaf': 0.08440730068390215, 'max_features': 'sqrt', 'min_impurity_decrease': 4.19885324392308e-07, 'validation_fraction': 0.37029719014273693, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:41:39,633] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.497258076729488, 'learning_rate': 0.008892113552158437, 'dropout_rate': 0.5412836692874428, 'n_estimators': 228, 'criterion': 'squared_error', 'ccp_alpha': 7.112328377904401, 'min_weight_fraction_leaf': 0.22283394976693366, 'max_features': None, 'min_impurity_decrease': 0.0009606983262736196, 'validation_fraction': 0.7883279075003073, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:42:14,015] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6818794942229185, 'learning_rate': 0.05992326510937737, 'dropout_rate': 0.4279996334051157, 'n_estimators': 293, 'criterion': 'friedman_mse', 'ccp_alpha': 4.98367064023063, 'min_weight_fraction_leaf': 0.48609051334926223, 'max_features': 'auto', 'min_impurity_decrease': 2.7205182948043777e-05, 'validation_fraction': 0.8992753588751915, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:42:20,149] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.8339878628842677, 'learning_rate': 0.01736979095038719, 'dropout_rate': 0.9018920438096094, 'n_estimators': 205, 'criterion': 'friedman_mse', 'ccp_alpha': 8.526748409672111, 'min_weight_fraction_leaf': 0.061083375695457354, 'max_features': None, 'min_impurity_decrease': 4.064893428944893e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:42:37,036] Trial 31 finished with value: 0.5 and parameters: {'subsample': 0.7067650123833389, 'learning_rate': 0.010128712060556065, 'dropout_rate': 0.34778224400860064, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 5.487014966748448, 'min_weight_fraction_leaf': 0.39961580373240596, 'max_features': None, 'min_impurity_decrease': 1.0411120773977246e-05, 'validation_fraction': 0.308558812747987, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:42:48,075] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.6110503802842687, 'learning_rate': 0.027415486687298214, 'dropout_rate': 0.4231091261598614, 'n_estimators': 165, 'criterion': 'friedman_mse', 'ccp_alpha': 4.725664402361732, 'min_weight_fraction_leaf': 0.4578429432624628, 'max_features': None, 'min_impurity_decrease': 1.102268047930114e-07, 'validation_fraction': 0.6040860894665333, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:43:46,324] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.7527918357143221, 'learning_rate': 0.013800242549203569, 'dropout_rate': 0.21901675178661018, 'n_estimators': 343, 'criterion': 'friedman_mse', 'ccp_alpha': 4.336519464922468, 'min_weight_fraction_leaf': 0.49560720146678894, 'max_features': None, 'min_impurity_decrease': 0.00011658144802596447, 'validation_fraction': 0.5695864375011732, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:43:50,497] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.5550888124148649, 'learning_rate': 0.07031962025287278, 'dropout_rate': 0.609287527548691, 'n_estimators': 109, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1886879010945073, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': None, 'min_impurity_decrease': 1.4503905721935394e-05, 'validation_fraction': 0.1781977553519499, 'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:44:24,587] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6647484092740189, 'learning_rate': 0.03716684708129065, 'dropout_rate': 0.32199768169248655, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 6.677117818544033, 'min_weight_fraction_leaf': 0.0024719709736978485, 'max_features': None, 'min_impurity_decrease': 0.0003527658310127607, 'validation_fraction': 0.4303498724987228, 'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:44:41,640] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.5132724920534562, 'learning_rate': 0.05938980302581085, 'dropout_rate': 0.5454399629254872, 'n_estimators': 232, 'criterion': 'squared_error', 'ccp_alpha': 2.377008407008705, 'min_weight_fraction_leaf': 0.2560267496278468, 'max_features': 1, 'min_impurity_decrease': 1.611508696646605e-05, 'validation_fraction': 0.3206572028643662, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:45:00,632] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6133316469108037, 'learning_rate': 0.0192978405124231, 'dropout_rate': 0.3734539105394589, 'n_estimators': 209, 'criterion': 'squared_error', 'ccp_alpha': 7.974952733297302, 'min_weight_fraction_leaf': 0.2937726053633184, 'max_features': 'auto', 'min_impurity_decrease': 2.9025315549537875e-07, 'validation_fraction': 0.5215770496136994, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:45:41,991] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0055035268399332106, 'dropout_rate': 0.15548835641172376, 'n_estimators': 278, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8766250077556945, 'min_weight_fraction_leaf': 0.37706312078571214, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010896766592292972, 'validation_fraction': 0.6758418959443157, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:46:30,208] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.43972351129566345, 'learning_rate': 0.06600221935919671, 'dropout_rate': 0.2199359809739201, 'n_estimators': 311, 'criterion': 'squared_error', 'ccp_alpha': 3.728373112411028, 'min_weight_fraction_leaf': 0.4354213118859305, 'max_features': 0.1, 'min_impurity_decrease': 6.240626814101929e-05, 'validation_fraction': 0.15340933394972178, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:46:46,519] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.7968754596525256, 'learning_rate': 0.033357301502402015, 'dropout_rate': 0.6498448126467091, 'n_estimators': 250, 'criterion': 'friedman_mse', 'ccp_alpha': 5.281445352241334, 'min_weight_fraction_leaf': 0.3381586418579516, 'max_features': 'auto', 'min_impurity_decrease': 6.661303017365454e-06, 'validation_fraction': 0.07579960633039973, 'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:46:46,881] Trial 41 finished with value: 0.5 and parameters: {'subsample': 0.7127655796244947, 'learning_rate': 0.07428645893623183, 'dropout_rate': 0.70485161120415, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 9.861114809899185, 'min_weight_fraction_leaf': 0.12458170809215217, 'max_features': None, 'min_impurity_decrease': 1.662245720310093e-07, 'validation_fraction': 0.7267564157130575, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:47:32,320] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.7560260044979399, 'learning_rate': 0.025751385187231305, 'dropout_rate': 0.6346183377825835, 'n_estimators': 408, 'criterion': 'friedman_mse', 'ccp_alpha': 7.475073875167142, 'min_weight_fraction_leaf': 0.04609024675850246, 'max_features': None, 'min_impurity_decrease': 9.328966670608897e-07, 'validation_fraction': 0.6034991541241608, 'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:47:52,654] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5800218768698703, 'learning_rate': 0.060657130303905384, 'dropout_rate': 0.8315823321401684, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 9.052626765771977, 'min_weight_fraction_leaf': 0.11245484624078364, 'max_features': 'log2', 'min_impurity_decrease': 2.7032867367744606e-06, 'validation_fraction': 0.7627780727404674, 'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:48:43,610] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.650007501014019, 'learning_rate': 0.042999799171261954, 'dropout_rate': 0.6859431566383477, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 9.255798461541156, 'min_weight_fraction_leaf': 0.19508406829791197, 'max_features': None, 'min_impurity_decrease': 1.803850310358625e-07, 'validation_fraction': 0.4932258209212708, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 16}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:49:18,591] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8267526608162997, 'learning_rate': 0.013494375221622822, 'dropout_rate': 0.562451794592445, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 7.951274135957477, 'min_weight_fraction_leaf': 0.15414208319180517, 'max_features': None, 'min_impurity_decrease': 0.02254931450703544, 'validation_fraction': 0.6904472538348748, 'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:50:16,352] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.6929864855836454, 'learning_rate': 0.007563282406611266, 'dropout_rate': 0.29094189233267964, 'n_estimators': 357, 'criterion': 'squared_error', 'ccp_alpha': 6.2062474416489986, 'min_weight_fraction_leaf': 0.2757251898825701, 'max_features': 'auto', 'min_impurity_decrease': 0.00020148550328401993, 'validation_fraction': 0.5782346210702172, 'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:50:50,911] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5253005441150441, 'learning_rate': 0.04837065116276148, 'dropout_rate': 0.40371810493552335, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 0.424583130603446, 'min_weight_fraction_leaf': 0.24358906077310583, 'max_features': 1, 'min_impurity_decrease': 1.7170256007439695e-06, 'validation_fraction': 0.423183184019399, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:52:17,847] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.8553523642443996, 'learning_rate': 0.055123011100452285, 'dropout_rate': 0.11178105681173112, 'n_estimators': 398, 'criterion': 'friedman_mse', 'ccp_alpha': 8.808635181507519, 'min_weight_fraction_leaf': 0.2141846663477463, 'max_features': 0.1, 'min_impurity_decrease': 8.385166952734583e-07, 'validation_fraction': 0.8693234429106627, 'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:53:52,469] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.3427196246281643, 'learning_rate': 0.02181226739450172, 'dropout_rate': 0.25330085395937585, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 3.1260410279491686, 'min_weight_fraction_leaf': 0.09975982578242681, 'max_features': None, 'min_impurity_decrease': 3.2453997760645774e-07, 'validation_fraction': 0.64281654153714, 'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 15}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:54:04,363] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.12134026571324846, 'learning_rate': 0.030037341123185, 'dropout_rate': 0.476177268516495, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 2.002448222737427, 'min_weight_fraction_leaf': 0.1675014656774081, 'max_features': 'sqrt', 'min_impurity_decrease': 2.614633035612604e-05, 'validation_fraction': 0.3148019982511154, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:54:08,554] Trial 51 finished with value: 0.5 and parameters: {'subsample': 0.22560952991832442, 'learning_rate': 0.07096865200025802, 'dropout_rate': 0.7403990506884194, 'n_estimators': 105, 'criterion': 'friedman_mse', 'ccp_alpha': 3.6955183727273386, 'min_weight_fraction_leaf': 0.033756448345697854, 'max_features': None, 'min_impurity_decrease': 0.00034438274690092334, 'validation_fraction': 0.8185501989107483, 'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:54:29,902] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.4078669152596949, 'learning_rate': 0.07972542806076426, 'dropout_rate': 0.5885469293985746, 'n_estimators': 258, 'criterion': 'friedman_mse', 'ccp_alpha': 4.196656708934098, 'min_weight_fraction_leaf': 0.06070449344498474, 'max_features': None, 'min_impurity_decrease': 0.0006522112972854332, 'validation_fraction': 0.6875552859786656, 'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:54:56,036] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.5780503682164675, 'learning_rate': 0.06351565920160718, 'dropout_rate': 0.5268425864933246, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 5.912988737296398, 'min_weight_fraction_leaf': 0.2880138147880729, 'max_features': 'log2', 'min_impurity_decrease': 0.0023620162241031065, 'validation_fraction': 0.7386953311243849, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:55:13,973] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.771877515032402, 'learning_rate': 0.0879386461062289, 'dropout_rate': 0.6531928050964037, 'n_estimators': 243, 'criterion': 'friedman_mse', 'ccp_alpha': 6.749514129274708, 'min_weight_fraction_leaf': 0.010727427625077723, 'max_features': 'auto', 'min_impurity_decrease': 6.568909958494579e-05, 'validation_fraction': 0.5260231128653986, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:55:38,358] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.6352427224249186, 'learning_rate': 0.0018114229555726662, 'dropout_rate': 0.7780580098014175, 'n_estimators': 361, 'criterion': 'friedman_mse', 'ccp_alpha': 4.674374022230462, 'min_weight_fraction_leaf': 0.4028675241355946, 'max_features': None, 'min_impurity_decrease': 0.00015802436521782464, 'validation_fraction': 0.6116726877072444, 'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:55:47,882] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.7310159697721421, 'learning_rate': 0.09459281124929597, 'dropout_rate': 0.33513381234631495, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 9.504060286925714, 'min_weight_fraction_leaf': 0.07554400849922152, 'max_features': 'sqrt', 'min_impurity_decrease': 3.609461626813292e-05, 'validation_fraction': 0.45003037837116033, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:55:56,093] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.4496884297691718, 'learning_rate': 0.055717108591229025, 'dropout_rate': 0.7227843588112581, 'n_estimators': 184, 'criterion': 'friedman_mse', 'ccp_alpha': 3.477932962998816, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': None, 'min_impurity_decrease': 6.805459531517676e-06, 'validation_fraction': 0.7746725177759497, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:56:17,389] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.5390990270834256, 'learning_rate': 0.08228345726531958, 'dropout_rate': 0.3867389328769052, 'n_estimators': 217, 'criterion': 'friedman_mse', 'ccp_alpha': 7.96887264775278, 'min_weight_fraction_leaf': 0.025824097286407145, 'max_features': 'auto', 'min_impurity_decrease': 2.1217250957605284e-07, 'validation_fraction': 0.7085899837169293, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:56:57,387] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.26995457899931047, 'learning_rate': 0.07839400629330891, 'dropout_rate': 0.44277207988197187, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 5.190496612405482, 'min_weight_fraction_leaf': 0.18052310410291128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006646480686851006, 'validation_fraction': 0.36899118019789573, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:57:05,062] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.6821263907321534, 'learning_rate': 0.072006110155798, 'dropout_rate': 0.5000787935588615, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 2.878661154904403, 'min_weight_fraction_leaf': 0.13302043494927485, 'max_features': None, 'min_impurity_decrease': 1.6927874845319952e-05, 'validation_fraction': 0.649254298624334, 'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:57:09,593] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.47645185130049367, 'learning_rate': 0.06448712922727752, 'dropout_rate': 0.18066337573915892, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 9.986171866114088, 'min_weight_fraction_leaf': 0.3016342642588235, 'max_features': 'auto', 'min_impurity_decrease': 2.135935478598492e-06, 'validation_fraction': 0.39240181900023485, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:57:13,993] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.5808153861385129, 'learning_rate': 0.0681246585307992, 'dropout_rate': 0.23730162924900122, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 8.569241148604158, 'min_weight_fraction_leaf': 0.26373450314917496, 'max_features': 'auto', 'min_impurity_decrease': 7.545132996978128e-05, 'validation_fraction': 0.5445924537815071, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:57:49,064] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.6306507981955418, 'learning_rate': 0.05196613429356862, 'dropout_rate': 0.29459029024130556, 'n_estimators': 276, 'criterion': 'squared_error', 'ccp_alpha': 7.302937119968669, 'min_weight_fraction_leaf': 0.21346358926716819, 'max_features': 'auto', 'min_impurity_decrease': 8.99541018098363e-06, 'validation_fraction': 0.48617563689534593, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:59:20,110] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.6655843820171748, 'learning_rate': 0.0755078862846863, 'dropout_rate': 0.16477104886116545, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 1.4394908967284419, 'min_weight_fraction_leaf': 0.3561841078487707, 'max_features': 0.1, 'min_impurity_decrease': 0.00011982157410057435, 'validation_fraction': 0.26717204824424134, 'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 02:59:21,851] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.7929453548007699, 'learning_rate': 0.05703829829485283, 'dropout_rate': 0.26693346156697134, 'n_estimators': 40, 'criterion': 'friedman_mse', 'ccp_alpha': 9.622909679545497, 'min_weight_fraction_leaf': 0.3739817512639645, 'max_features': 1, 'min_impurity_decrease': 1.132537699639542e-06, 'validation_fraction': 0.5719114708143103, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:01:34,344] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.7297228220058729, 'learning_rate': 0.048039429864377176, 'dropout_rate': 0.13146807723463924, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 2.2139349489390074, 'min_weight_fraction_leaf': 0.22907689759626237, 'max_features': None, 'min_impurity_decrease': 3.649342411644349e-05, 'validation_fraction': 0.6184842144993817, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:02:00,680] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.5640799123153939, 'learning_rate': 0.013731811381943973, 'dropout_rate': 0.6010596795994926, 'n_estimators': 312, 'criterion': 'friedman_mse', 'ccp_alpha': 4.4267489755284135, 'min_weight_fraction_leaf': 0.24894174086156923, 'max_features': 'log2', 'min_impurity_decrease': 5.850812869882035e-07, 'validation_fraction': 0.20583470481171634, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:10,399] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6103857042426706, 'learning_rate': 0.004499506882329311, 'dropout_rate': 0.20156861633079565, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 7.575686101065674, 'min_weight_fraction_leaf': 0.3201448672949048, 'max_features': 'auto', 'min_impurity_decrease': 2.0511672586731725e-05, 'validation_fraction': 0.9734477789916156, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:33,049] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.38208631321852893, 'learning_rate': 0.019445173055985306, 'dropout_rate': 0.3471760689409496, 'n_estimators': 221, 'criterion': 'squared_error', 'ccp_alpha': 8.23137310474947, 'min_weight_fraction_leaf': 0.46019349583797037, 'max_features': 'sqrt', 'min_impurity_decrease': 5.25007498558406e-06, 'validation_fraction': 0.6668478041329834, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.5
Fold 3 C-index: 0.6495098039215687
Fold 4 C-index: 0.5168776371308017
Fold 5 C-index: 0.6220657276995305
[I 2024-04-16 03:03:38,704] Trial 70 finished with value: 0.5745737506334969 and parameters: {'subsample': 0.695791357845726, 'learning_rate': 0.0386121015837519, 'dropout_rate': 0.8772407730274028, 'n_estimators': 196, 'criterion': 'friedman_mse', 'ccp_alpha': 0.08521619959958793, 'min_weight_fraction_leaf': 0.2793514647088877, 'max_features': None, 'min_impurity_decrease': 1.0560662656413339e-07, 'validation_fraction': 0.4673552004275108, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:42,709] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.6953908543100885, 'learning_rate': 0.03743237534286249, 'dropout_rate': 0.9621327216313197, 'n_estimators': 198, 'criterion': 'friedman_mse', 'ccp_alpha': 0.15374641631577673, 'min_weight_fraction_leaf': 0.27657260116198973, 'max_features': None, 'min_impurity_decrease': 2.8920488173461134e-07, 'validation_fraction': 0.3339850543602635, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:49,642] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.6693434488547243, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.9021061225848414, 'n_estimators': 237, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6518397080948914, 'min_weight_fraction_leaf': 0.30089860849042194, 'max_features': None, 'min_impurity_decrease': 1.1606027609483291e-07, 'validation_fraction': 0.7490765541175108, 'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:03:54,822] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.7420556902526638, 'learning_rate': 0.03446255878761435, 'dropout_rate': 0.842247850975758, 'n_estimators': 164, 'criterion': 'friedman_mse', 'ccp_alpha': 1.27222591420132, 'min_weight_fraction_leaf': 0.23598753048020413, 'max_features': None, 'min_impurity_decrease': 1.55879459379031e-07, 'validation_fraction': 0.2508680771703865, 'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:04:00,168] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6407847417329294, 'learning_rate': 0.027234278844566435, 'dropout_rate': 0.8680349866283517, 'n_estimators': 184, 'criterion': 'friedman_mse', 'ccp_alpha': 8.952599299327895, 'min_weight_fraction_leaf': 0.26554541506545176, 'max_features': None, 'min_impurity_decrease': 1.0251502472109203e-07, 'validation_fraction': 0.2850419392236734, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5909090909090909
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6151960784313726
Fold 4 C-index: 0.6181434599156118
Fold 5 C-index: 0.6314553990610329
[I 2024-04-16 03:04:14,785] Trial 75 finished with value: 0.642926519949136 and parameters: {'subsample': 0.49605383018584304, 'learning_rate': 0.06741276323402065, 'dropout_rate': 0.8003972830508307, 'n_estimators': 296, 'criterion': 'friedman_mse', 'ccp_alpha': 0.08304534706000144, 'min_weight_fraction_leaf': 0.47835629989654377, 'max_features': None, 'min_impurity_decrease': 0.0002469950977072107, 'validation_fraction': 0.46406091324791776, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.43526785714285715
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6596244131455399
[I 2024-04-16 03:04:33,287] Trial 76 finished with value: 0.5932732582854695 and parameters: {'subsample': 0.31410999108550985, 'learning_rate': 0.04574117277556769, 'dropout_rate': 0.7628827130120311, 'n_estimators': 299, 'criterion': 'friedman_mse', 'ccp_alpha': 0.10179413563763529, 'min_weight_fraction_leaf': 0.48322374587938177, 'max_features': None, 'min_impurity_decrease': 0.0002155234609466344, 'validation_fraction': 0.4669980954945373, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:04:47,240] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7636926742441101, 'learning_rate': 0.04683137626817, 'dropout_rate': 0.8060826625310789, 'n_estimators': 296, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1204540963831401, 'min_weight_fraction_leaf': 0.4886312478929783, 'max_features': None, 'min_impurity_decrease': 0.00018014467270761062, 'validation_fraction': 0.45479088985861454, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:05:00,256] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.7126240797835157, 'learning_rate': 0.03866771774540286, 'dropout_rate': 0.7696992583170289, 'n_estimators': 268, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5562075267667846, 'min_weight_fraction_leaf': 0.44108285001317943, 'max_features': None, 'min_impurity_decrease': 0.00048603949189907753, 'validation_fraction': 0.34493979705070354, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:05:12,576] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.5915825661664962, 'learning_rate': 0.02377615162596504, 'dropout_rate': 0.8831816560103296, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8644379636521962, 'min_weight_fraction_leaf': 0.47533730868525637, 'max_features': None, 'min_impurity_decrease': 0.00026754667959111344, 'validation_fraction': 0.3975502888375885, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:05:34,387] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.15032773286356033, 'learning_rate': 0.044220046970848, 'dropout_rate': 0.8012542413818668, 'n_estimators': 348, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05615612216402271, 'min_weight_fraction_leaf': 0.47264436421233097, 'max_features': None, 'min_impurity_decrease': 2.3708130065662297e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:05:49,617] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.3458856991309244, 'learning_rate': 0.061880262920121366, 'dropout_rate': 0.6683098819549974, 'n_estimators': 252, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0641865265099684, 'min_weight_fraction_leaf': 0.448452505667851, 'max_features': None, 'min_impurity_decrease': 0.0014437277259298509, 'validation_fraction': 0.5858261663814373, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5168776371308017
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:07,630] Trial 82 finished with value: 0.5033755274261603 and parameters: {'subsample': 0.2979066859374864, 'learning_rate': 0.03192859199890033, 'dropout_rate': 0.7431338924278378, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 0.25619854049785146, 'min_weight_fraction_leaf': 0.4154239703802, 'max_features': None, 'min_impurity_decrease': 0.0006017716157596374, 'validation_fraction': 0.4734943895870986, 'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:26,381] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.18728973640084134, 'learning_rate': 0.03330792414298163, 'dropout_rate': 0.7362748870700768, 'n_estimators': 294, 'criterion': 'friedman_mse', 'ccp_alpha': 0.45015427190108215, 'min_weight_fraction_leaf': 0.41222450962239143, 'max_features': None, 'min_impurity_decrease': 0.0005484773067096504, 'validation_fraction': 0.47958183115384834, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:41,642] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.2845658432082305, 'learning_rate': 0.04081669734362587, 'dropout_rate': 0.821691123019113, 'n_estimators': 309, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6794510840916247, 'min_weight_fraction_leaf': 0.41828965104910665, 'max_features': None, 'min_impurity_decrease': 4.026918744152846e-07, 'validation_fraction': 0.4234978876665736, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:06:54,165] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.3286999719741053, 'learning_rate': 0.030988903051816365, 'dropout_rate': 0.7835055788285401, 'n_estimators': 268, 'criterion': 'friedman_mse', 'ccp_alpha': 0.36637580090608235, 'min_weight_fraction_leaf': 0.47537390714161937, 'max_features': None, 'min_impurity_decrease': 5.011899853561089e-05, 'validation_fraction': 0.5103256635243018, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:07:10,857] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.2614188055017745, 'learning_rate': 0.045388782330051294, 'dropout_rate': 0.7141718915119125, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5820304909263354, 'min_weight_fraction_leaf': 0.49165399924279257, 'max_features': None, 'min_impurity_decrease': 0.00023611116504182125, 'validation_fraction': 0.5510310673765155, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:07:34,150] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.24251315001966853, 'learning_rate': 0.016501644813831366, 'dropout_rate': 0.7576312694750015, 'n_estimators': 337, 'criterion': 'friedman_mse', 'ccp_alpha': 1.105952123672767, 'min_weight_fraction_leaf': 0.45037091777486393, 'max_features': 1, 'min_impurity_decrease': 9.437826649460271e-05, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:07:55,422] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.6520586662910131, 'learning_rate': 0.053489441535809173, 'dropout_rate': 0.6925885136491301, 'n_estimators': 316, 'criterion': 'friedman_mse', 'ccp_alpha': 0.863953681025809, 'min_weight_fraction_leaf': 0.42842611905779604, 'max_features': 'sqrt', 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.35196407528199913, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5606060606060606
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.5857843137254902
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 03:08:07,226] Trial 89 finished with value: 0.6323373057792138 and parameters: {'subsample': 0.29788879637206783, 'learning_rate': 0.035555720782382214, 'dropout_rate': 0.9289339524597527, 'n_estimators': 366, 'criterion': 'friedman_mse', 'ccp_alpha': 0.020086704993095825, 'min_weight_fraction_leaf': 0.4667949943266333, 'max_features': 0.1, 'min_impurity_decrease': 0.0008812423360306166, 'validation_fraction': 0.38186035290218956, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:08:19,577] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.03247374059041004, 'dropout_rate': 0.9304311564311895, 'n_estimators': 365, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2639930078446805, 'min_weight_fraction_leaf': 0.3908665766982689, 'max_features': 0.1, 'min_impurity_decrease': 0.0018867119413392888, 'validation_fraction': 0.29585084927667094, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:08:28,473] Trial 91 finished with value: 0.5 and parameters: {'subsample': 0.32341400997126246, 'learning_rate': 0.036327713844900564, 'dropout_rate': 0.9925454077948749, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3111522605524543, 'min_weight_fraction_leaf': 0.4678372823653073, 'max_features': 0.1, 'min_impurity_decrease': 0.000768945964951233, 'validation_fraction': 0.3894300048498697, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:08:49,688] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.2254273223766157, 'learning_rate': 0.027929847361018882, 'dropout_rate': 0.8562165450473785, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.051481042392730963, 'min_weight_fraction_leaf': 0.49621848794515483, 'max_features': 0.1, 'min_impurity_decrease': 0.0029747778240912224, 'validation_fraction': 0.43212573688223266, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:08:59,828] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.7014559397669213, 'learning_rate': 0.04941640219482665, 'dropout_rate': 0.938553646035921, 'n_estimators': 351, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6471317001475573, 'min_weight_fraction_leaf': 0.49950467747375193, 'max_features': 0.1, 'min_impurity_decrease': 0.00014898895401809737, 'validation_fraction': 0.4756960290383652, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:09:09,873] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.6243723676927855, 'learning_rate': 0.010640812705694017, 'dropout_rate': 0.8972373322063223, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 0.749126219889791, 'min_weight_fraction_leaf': 0.45578862178588564, 'max_features': None, 'min_impurity_decrease': 0.0010375628696626341, 'validation_fraction': 0.41115482329305547, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:09:56,542] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.3575417229044505, 'learning_rate': 0.03602414533125063, 'dropout_rate': 0.31555645359514173, 'n_estimators': 333, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2620042855552611, 'min_weight_fraction_leaf': 0.4830374674994227, 'max_features': None, 'min_impurity_decrease': 0.00044880034816871956, 'validation_fraction': 0.5042132949646849, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5865800865800865
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.6053921568627451
Fold 4 C-index: 0.6181434599156118
Fold 5 C-index: 0.6807511737089202
[I 2024-04-16 03:10:06,694] Trial 96 finished with value: 0.643709089699187 and parameters: {'subsample': 0.38768770746428227, 'learning_rate': 0.09228994112386232, 'dropout_rate': 0.815165927942691, 'n_estimators': 247, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0329344621321584, 'min_weight_fraction_leaf': 0.3309349122019748, 'max_features': None, 'min_impurity_decrease': 1.4894860335591788e-07, 'validation_fraction': 0.43791446522787536, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:10:13,208] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.39222767459068186, 'learning_rate': 0.09559539992853426, 'dropout_rate': 0.9250025476611926, 'n_estimators': 246, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4386059820040108, 'min_weight_fraction_leaf': 0.42699719679026016, 'max_features': 'log2', 'min_impurity_decrease': 0.004452254036847487, 'validation_fraction': 0.37371628758073683, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 03:10:22,952] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.427067537198888, 'learning_rate': 0.08984402570083139, 'dropout_rate': 0.8192282529527549, 'n_estimators': 224, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2503354049670562, 'min_weight_fraction_leaf': 0.36148411412968423, 'max_features': None, 'min_impurity_decrease': 0.0002882682632151261, 'validation_fraction': 0.43837016030823805, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5454545454545454
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6392405063291139

[I 2024-04-16 03:10:37,761] A new study created in memory with name: no-name-bbe4c4f7-fa2c-438b-8325-4e273793c1ca

Fold 5 C-index: 0.6713615023474179
[I 2024-04-16 03:10:37,716] Trial 99 finished with value: 0.6472442239914815 and parameters: {'subsample': 0.293918127029324, 'learning_rate': 0.09922718569465194, 'dropout_rate': 0.7939431243365798, 'n_estimators': 279, 'criterion': 'friedman_mse', 'ccp_alpha': 0.00443168890264431, 'min_weight_fraction_leaf': 0.34678735520439286, 'max_features': 'sqrt', 'min_impurity_decrease': 8.596034523879625e-05, 'validation_fraction': 0.3332285029879782, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.


* Best trial for C-index:
 FrozenTrial(number=9, state=TrialState.COMPLETE, values=[0.6608490969281925], datetime_start=datetime.datetime(2024, 4, 16, 2, 26, 13, 403839), datetime_complete=datetime.datetime(2024, 4, 16, 2, 27, 28, 397788), params={'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=9, value=None)


* Best Score for C-index:
 0.6608490969281925

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:11:08,981] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:11:28,104] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:11:45,694] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:12:12,445] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:12:25,361] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:12:28,273] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:12:54,882] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:13:02,676] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:13:03,589] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21389609169187893
Fold 2 IBS: 0.22151809570438574
Fold 3 IBS: 0.20434951031162685
Fold 4 IBS: 0.22469248319684446
Fold 5 IBS: 0.21805954250695855
[I 2024-04-16 03:14:13,743] Trial 9 finished with value: 0.2165031446823389 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:15:56,796] Trial 10 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:17:08,881] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8081282674845877, 'learning_rate': 0.03957576815132133, 'dropout_rate': 0.3592207054036807, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 9.74116027708086, 'min_weight_fraction_leaf': 0.365889927692422, 'max_features': 'log2', 'min_impurity_decrease': 1.459170836380829e-06, 'validation_fraction': 0.7986785049611014, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:18:14,105] Trial 12 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3678235114093892, 'learning_rate': 0.04567946973839636, 'dropout_rate': 0.25727844951644346, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.3231056999503768, 'min_weight_fraction_leaf': 0.19696526950140963, 'max_features': 'auto', 'min_impurity_decrease': 1.6810148621356602e-06, 'validation_fraction': 0.8490366656238622, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:18:21,865] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7784830438231676, 'learning_rate': 0.02439641670004065, 'dropout_rate': 0.4821375662037144, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 6.245821408640139, 'min_weight_fraction_leaf': 0.3469021849356369, 'max_features': 1, 'min_impurity_decrease': 0.002901900339595834, 'validation_fraction': 0.40492470595401014, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:19:24,731] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5522283925781899, 'learning_rate': 0.010913227078192221, 'dropout_rate': 0.275468298707492, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.2209251544817152, 'max_features': 'log2', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.7267940764758692, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:20:35,634] Trial 15 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8321814107294574, 'learning_rate': 0.03462515781182537, 'dropout_rate': 0.10188162797857298, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 5.585208670000242, 'min_weight_fraction_leaf': 0.3203472576334258, 'max_features': 0.1, 'min_impurity_decrease': 9.84228208509291e-05, 'validation_fraction': 0.9508448160253733, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:20:41,636] Trial 16 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.41637694759398924, 'learning_rate': 0.05102954371215744, 'dropout_rate': 0.4800989647660596, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 9.356569787888832, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': None, 'min_impurity_decrease': 6.315552530348283e-07, 'validation_fraction': 0.6329472651499938, 'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:22:23,455] Trial 17 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.18427032297888507, 'learning_rate': 0.016160179473353013, 'dropout_rate': 0.2643467397617198, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 1.767647956851031, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 'auto', 'min_impurity_decrease': 9.756988906280483e-06, 'validation_fraction': 0.460466512261803, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:22:42,948] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.29960178961969325, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.480521228562659, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 6.571359927175668, 'min_weight_fraction_leaf': 0.3081685769690769, 'max_features': 'auto', 'min_impurity_decrease': 0.00017103826195115595, 'validation_fraction': 0.8334165513948124, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 03:22:51,437] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.14079986349305024, 'learning_rate': 0.0022617590243428215, 'dropout_rate': 0.7517968453304719, 'n_estimators': 197, 'criterion': 'squared_error', 'ccp_alpha': 6.452074842928597, 'min_weight_fraction_leaf': 0.2587652353783316, 'max_features': 'auto', 'min_impurity_decrease': 0.005768680906957018, 'validation_fraction': 0.8786489241905744, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 1}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:23:25,118] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.24265872160421625, 'learning_rate': 0.09210641510546798, 'dropout_rate': 0.46523489726077377, 'n_estimators': 329, 'criterion': 'squared_error', 'ccp_alpha': 4.870804793608105, 'min_weight_fraction_leaf': 0.43152288390795446, 'max_features': 'auto', 'min_impurity_decrease': 0.0002304744011468318, 'validation_fraction': 0.48727408136805295, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:23:46,183] Trial 21 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6094950880850886, 'learning_rate': 0.008899729354740909, 'dropout_rate': 0.4156145778245767, 'n_estimators': 236, 'criterion': 'friedman_mse', 'ccp_alpha': 8.278621831249582, 'min_weight_fraction_leaf': 0.3155932474077326, 'max_features': 'auto', 'min_impurity_decrease': 4.694387394774905e-05, 'validation_fraction': 0.7547747052438045, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:23:56,392] Trial 22 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2871142790618468, 'learning_rate': 0.025093979402539022, 'dropout_rate': 0.2770995126593906, 'n_estimators': 146, 'criterion': 'friedman_mse', 'ccp_alpha': 6.835319645459137, 'min_weight_fraction_leaf': 0.30133732679009123, 'max_features': None, 'min_impurity_decrease': 0.0007773401372966076, 'validation_fraction': 0.6658472502317975, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:24:50,579] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.48769513568564904, 'learning_rate': 0.018456221083045135, 'dropout_rate': 0.53741894468906, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 8.817736687096165, 'min_weight_fraction_leaf': 0.3638156336905286, 'max_features': 'auto', 'min_impurity_decrease': 2.810229431824276e-05, 'validation_fraction': 0.8357013182292345, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 03:25:16,650] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7488754310335448, 'learning_rate': 0.03089952267930116, 'dropout_rate': 0.32879197402435767, 'n_estimators': 259, 'criterion': 'friedman_mse', 'ccp_alpha': 9.981120123612905, 'min_weight_fraction_leaf': 0.2164711289226942, 'max_features': 0.1, 'min_impurity_decrease': 5.42338990036805e-06, 'validation_fraction': 0.9143974560141267, 'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:26:10,181] Trial 25 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8874543522938172, 'learning_rate': 0.004761399604301435, 'dropout_rate': 0.18173309155533923, 'n_estimators': 341, 'criterion': 'friedman_mse', 'ccp_alpha': 5.542613074541842, 'min_weight_fraction_leaf': 0.40164299470943704, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9852194132056973e-07, 'validation_fraction': 0.7563954099792602, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:26:39,248] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.46277628442238006, 'learning_rate': 0.04325862603961612, 'dropout_rate': 0.43074917692858017, 'n_estimators': 290, 'criterion': 'friedman_mse', 'ccp_alpha': 7.668509356745217, 'min_weight_fraction_leaf': 0.25134084317387756, 'max_features': 1, 'min_impurity_decrease': 0.00015745431279058403, 'validation_fraction': 0.5603595903911948, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:26:43,666] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3193135166121804, 'learning_rate': 0.015536686124689843, 'dropout_rate': 0.9847790608248583, 'n_estimators': 225, 'criterion': 'friedman_mse', 'ccp_alpha': 4.424459452567016, 'min_weight_fraction_leaf': 0.3372212390713461, 'max_features': 'log2', 'min_impurity_decrease': 0.005020040981624099, 'validation_fraction': 0.6424430041225765, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:26:53,323] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6224481475710952, 'learning_rate': 0.027340808999678275, 'dropout_rate': 0.5232444267019107, 'n_estimators': 166, 'criterion': 'squared_error', 'ccp_alpha': 1.3579090466039423, 'min_weight_fraction_leaf': 0.1605065207620611, 'max_features': None, 'min_impurity_decrease': 3.3238057066467287e-06, 'validation_fraction': 0.7883279075003073, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:27:12,076] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7165866941586748, 'learning_rate': 0.037453335849444366, 'dropout_rate': 0.7130342804882008, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 4.144031624908622, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'sqrt', 'min_impurity_decrease': 2.7205182948043777e-05, 'validation_fraction': 0.3265002522472238, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:27:34,558] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.636031175896398, 'learning_rate': 0.008217970787439355, 'dropout_rate': 0.8423465978925959, 'n_estimators': 422, 'criterion': 'friedman_mse', 'ccp_alpha': 2.3899676108316683, 'min_weight_fraction_leaf': 0.23371629234007008, 'max_features': 'auto', 'min_impurity_decrease': 5.4690807820604754e-05, 'validation_fraction': 0.697941804171905, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 17}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.2139765219514961
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:27:57,842] Trial 31 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6704587435666225, 'learning_rate': 0.09868202705851985, 'dropout_rate': 0.7942968321130364, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6708317687116205, 'min_weight_fraction_leaf': 0.09254919790029942, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005916374005909833, 'validation_fraction': 0.2154459552955903, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:28:22,012] Trial 32 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7031549425639906, 'learning_rate': 0.0841909264193112, 'dropout_rate': 0.6396107081761062, 'n_estimators': 327, 'criterion': 'friedman_mse', 'ccp_alpha': 3.180606095131633, 'min_weight_fraction_leaf': 0.49702216690803946, 'max_features': 'sqrt', 'min_impurity_decrease': 8.538682201266657e-05, 'validation_fraction': 0.3709424400465384, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:28:47,540] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7319198255223508, 'learning_rate': 0.054169729844528294, 'dropout_rate': 0.6101705401317011, 'n_estimators': 313, 'criterion': 'friedman_mse', 'ccp_alpha': 2.876665224201397, 'min_weight_fraction_leaf': 0.47840362890298604, 'max_features': 'sqrt', 'min_impurity_decrease': 8.968491592950819e-05, 'validation_fraction': 0.3688154101045705, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:29:05,242] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5833432046167292, 'learning_rate': 0.07952157166524661, 'dropout_rate': 0.6439627277495299, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 5.427479405311726, 'min_weight_fraction_leaf': 0.45046287494052506, 'max_features': None, 'min_impurity_decrease': 0.001411350654717537, 'validation_fraction': 0.24963536181862767, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:29:52,415] Trial 35 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6759981312721777, 'learning_rate': 0.06142645602971149, 'dropout_rate': 0.32027248724159646, 'n_estimators': 343, 'criterion': 'friedman_mse', 'ccp_alpha': 4.129615069838275, 'min_weight_fraction_leaf': 0.4998924611243427, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2440446336188077e-05, 'validation_fraction': 0.5404012082537679, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:30:49,117] Trial 36 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5272918110993997, 'learning_rate': 0.06261578581596848, 'dropout_rate': 0.21517948211889956, 'n_estimators': 362, 'criterion': 'friedman_mse', 'ccp_alpha': 4.063848184083534, 'min_weight_fraction_leaf': 0.4963250705419947, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003129076691432843, 'validation_fraction': 0.4348133972223629, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:31:31,755] Trial 37 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.08444404399090331, 'dropout_rate': 0.5625381440734535, 'n_estimators': 415, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1379925153627317, 'min_weight_fraction_leaf': 0.4350557396734583, 'max_features': 'sqrt', 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.5464067179600798, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:32:14,950] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.845614406035329, 'learning_rate': 0.06824987522226218, 'dropout_rate': 0.32918341372879295, 'n_estimators': 339, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9635828477255348, 'min_weight_fraction_leaf': 0.47683179862026137, 'max_features': 'sqrt', 'min_impurity_decrease': 4.32232538916105e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 13}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:32:31,518] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6597097236895602, 'learning_rate': 0.05917897179340344, 'dropout_rate': 0.40168145360764357, 'n_estimators': 220, 'criterion': 'squared_error', 'ccp_alpha': 3.8498889793304736, 'min_weight_fraction_leaf': 0.38831552991944795, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0025382220080623e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:33:14,680] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7674106289123288, 'learning_rate': 0.07560432459160085, 'dropout_rate': 0.6757239331922499, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.9680569992941467, 'min_weight_fraction_leaf': 0.4599197939705914, 'max_features': 'auto', 'min_impurity_decrease': 2.8984969801345965e-07, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:33:45,353] Trial 41 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6905443471415563, 'learning_rate': 0.08991844550349633, 'dropout_rate': 0.3062177672417189, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 4.7678853782582475, 'min_weight_fraction_leaf': 0.2815316241639545, 'max_features': None, 'min_impurity_decrease': 1.5004604379229747e-05, 'validation_fraction': 0.570943263446734, 'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:34:28,198] Trial 42 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5727452533507132, 'learning_rate': 0.07249852124211806, 'dropout_rate': 0.21510431819480508, 'n_estimators': 319, 'criterion': 'friedman_mse', 'ccp_alpha': 7.2599793775059345, 'min_weight_fraction_leaf': 0.28888666819812236, 'max_features': 1, 'min_impurity_decrease': 0.00015834833648163015, 'validation_fraction': 0.37796771299239895, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:35:11,502] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4265790468278674, 'learning_rate': 0.020077866785162254, 'dropout_rate': 0.37018492375604106, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 5.960286004690163, 'min_weight_fraction_leaf': 0.49889273199542455, 'max_features': 'sqrt', 'min_impurity_decrease': 5.9638605394856106e-05, 'validation_fraction': 0.7029786985243873, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:35:38,162] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7973150053365794, 'learning_rate': 0.006337134606386357, 'dropout_rate': 0.15064482764363352, 'n_estimators': 247, 'criterion': 'friedman_mse', 'ccp_alpha': 3.381558950528815, 'min_weight_fraction_leaf': 0.3628684941350201, 'max_features': None, 'min_impurity_decrease': 1.0072469681841355e-05, 'validation_fraction': 0.5967195594051253, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 9}. Best is trial 9 with value: 0.2165031446823389.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:36:27,592] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5303064017076159, 'learning_rate': 0.013591809817627606, 'dropout_rate': 0.4506745791740544, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 2.5557833119257145, 'min_weight_fraction_leaf': 0.3344828403640176, 'max_features': 0.1, 'min_impurity_decrease': 0.02254931450703544, 'validation_fraction': 0.5042239156018957, 'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 14}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:36:57,635] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.042767734352667994, 'dropout_rate': 0.35811970946933236, 'n_estimators': 281, 'criterion': 'squared_error', 'ccp_alpha': 8.351912968810883, 'min_weight_fraction_leaf': 0.18996792578183735, 'max_features': 'log2', 'min_impurity_decrease': 0.000481840927394298, 'validation_fraction': 0.7889980344404982, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:37:08,013] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9461825771401899, 'learning_rate': 0.06195303328645835, 'dropout_rate': 0.5120167018154631, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 9.159235216571009, 'min_weight_fraction_leaf': 0.40375519491189016, 'max_features': 'auto', 'min_impurity_decrease': 2.531081899593294e-06, 'validation_fraction': 0.27559882629024807, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:37:08,500] Trial 48 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6409588871422276, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.5797126801998765, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.739609107328239, 'min_weight_fraction_leaf': 0.26407271071264776, 'max_features': 'auto', 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.98037867112525, 'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:38:04,590] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5894342645761806, 'learning_rate': 0.034101100960505684, 'dropout_rate': 0.30505113946900136, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 5.146711552010747, 'min_weight_fraction_leaf': 0.4399857804304742, 'max_features': 'sqrt', 'min_impurity_decrease': 6.203981222541818e-06, 'validation_fraction': 0.8372171681899604, 'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:39:00,642] Trial 50 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8328212088129892, 'learning_rate': 0.011750047838064437, 'dropout_rate': 0.22305695210880072, 'n_estimators': 358, 'criterion': 'squared_error', 'ccp_alpha': 6.882189904068126, 'min_weight_fraction_leaf': 0.31040829786124846, 'max_features': None, 'min_impurity_decrease': 7.50899650138145e-07, 'validation_fraction': 0.8962280884203246, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:39:16,547] Trial 51 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7357800616216513, 'learning_rate': 0.08274067108256297, 'dropout_rate': 0.8090617340394859, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 4.526907013943373, 'min_weight_fraction_leaf': 0.008974406259752363, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2968653187143025e-05, 'validation_fraction': 0.14802842495662882, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:39:25,907] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.679117430541056, 'learning_rate': 0.08852429820426559, 'dropout_rate': 0.8771304848138055, 'n_estimators': 268, 'criterion': 'friedman_mse', 'ccp_alpha': 2.185255366537462, 'min_weight_fraction_leaf': 0.12135448690030037, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00013766373531663148, 'validation_fraction': 0.3383251947958834, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:39:51,671] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6116904400168919, 'learning_rate': 0.001099142947171871, 'dropout_rate': 0.6671338375088499, 'n_estimators': 326, 'criterion': 'friedman_mse', 'ccp_alpha': 3.7461701959089693, 'min_weight_fraction_leaf': 0.22337481705087078, 'max_features': 'auto', 'min_impurity_decrease': 8.269015090875863e-05, 'validation_fraction': 0.44314541028163157, 'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:40:04,375] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.771877515032402, 'learning_rate': 0.09629805895453353, 'dropout_rate': 0.7237985203908401, 'n_estimators': 243, 'criterion': 'friedman_mse', 'ccp_alpha': 2.900081225715882, 'min_weight_fraction_leaf': 0.1946180352482926, 'max_features': 1, 'min_impurity_decrease': 0.000310545367295499, 'validation_fraction': 0.19540582298921147, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 03:40:07,244] Trial 55 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7086352508071794, 'learning_rate': 0.08496463063739257, 'dropout_rate': 0.6248605528903883, 'n_estimators': 89, 'criterion': 'friedman_mse', 'ccp_alpha': 5.946169893251803, 'min_weight_fraction_leaf': 0.16253399075243827, 'max_features': 0.1, 'min_impurity_decrease': 2.0745433473467182e-05, 'validation_fraction': 0.28365184351149203, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:40:29,344] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1173095704794419, 'learning_rate': 0.022797925457682687, 'dropout_rate': 0.2500192595896841, 'n_estimators': 209, 'criterion': 'squared_error', 'ccp_alpha': 1.515994978548666, 'min_weight_fraction_leaf': 0.04557038009296144, 'max_features': 'sqrt', 'min_impurity_decrease': 8.288990661784225e-06, 'validation_fraction': 0.6682715637714014, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.2138266015910569
Fold 2 IBS: 0.2215272504056153
Fold 3 IBS: 0.20423591913518002
Fold 4 IBS: 0.22463204530996436
Fold 5 IBS: 0.21804570777294438
[I 2024-04-16 03:40:45,904] Trial 57 finished with value: 0.2164535048429522 and parameters: {'subsample': 0.553868700002313, 'learning_rate': 0.07780886066105958, 'dropout_rate': 0.7575479273298723, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0636428366764088, 'min_weight_fraction_leaf': 0.2954895332892262, 'max_features': 'log2', 'min_impurity_decrease': 4.237895965249124e-05, 'validation_fraction': 0.7444606410682515, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 57 with value: 0.2164535048429522.
Fold 1 IBS: 0.21370262425465492
Fold 2 IBS: 0.22125556467347285
Fold 3 IBS: 0.20407028324181956
Fold 4 IBS: 0.22450242015826147
Fold 5 IBS: 0.21790890758884696
[I 2024-04-16 03:41:17,721] Trial 58 finished with value: 0.21628795998341116 and parameters: {'subsample': 0.5068380874811701, 'learning_rate': 0.07262285651752191, 'dropout_rate': 0.7041347398290517, 'n_estimators': 378, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03918644077746685, 'min_weight_fraction_leaf': 0.3501224417387053, 'max_features': 'log2', 'min_impurity_decrease': 4.18700542213e-05, 'validation_fraction': 0.7454328663550801, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 58 with value: 0.21628795998341116.
Fold 1 IBS: 0.21395452308986776
Fold 2 IBS: 0.22155139865150372
Fold 3 IBS: 0.2044760463600085
Fold 4 IBS: 0.22470927576438263
Fold 5 IBS: 0.2181152561009967
[I 2024-04-16 03:41:53,009] Trial 59 finished with value: 0.21656129999335186 and parameters: {'subsample': 0.3756731628300646, 'learning_rate': 0.0713336187568541, 'dropout_rate': 0.7116701148836264, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11427638256939372, 'min_weight_fraction_leaf': 0.2989130613985737, 'max_features': 'log2', 'min_impurity_decrease': 4.314426667063267e-05, 'validation_fraction': 0.7417723383986068, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 58 with value: 0.21628795998341116.
Fold 1 IBS: 0.21396673987143008
Fold 2 IBS: 0.22156965821607041
Fold 3 IBS: 0.2044959542031774
Fold 4 IBS: 0.22473062991489348
Fold 5 IBS: 0.21811277963187556
[I 2024-04-16 03:42:30,504] Trial 60 finished with value: 0.2165751523674894 and parameters: {'subsample': 0.352587285254757, 'learning_rate': 0.0759991473024008, 'dropout_rate': 0.7719154717054937, 'n_estimators': 461, 'criterion': 'friedman_mse', 'ccp_alpha': 0.12935509535102224, 'min_weight_fraction_leaf': 0.29577635182154743, 'max_features': 'log2', 'min_impurity_decrease': 0.00022374666447428864, 'validation_fraction': 0.7250691100626211, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 58 with value: 0.21628795998341116.
Fold 1 IBS: 0.21386832647701734
Fold 2 IBS: 0.22151812804487725
Fold 3 IBS: 0.204326778459994
Fold 4 IBS: 0.2246582900701499
Fold 5 IBS: 0.21804200264362525
[I 2024-04-16 03:43:21,287] Trial 61 finished with value: 0.21648270513913276 and parameters: {'subsample': 0.365140791655746, 'learning_rate': 0.07256692244824432, 'dropout_rate': 0.6998637630005794, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.29736911681242306, 'max_features': 'log2', 'min_impurity_decrease': 0.00025106852346533435, 'validation_fraction': 0.7571179766181859, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 58 with value: 0.21628795998341116.
Fold 1 IBS: 0.21363209005163925
Fold 2 IBS: 0.22111697823395574
Fold 3 IBS: 0.20407250676997135
Fold 4 IBS: 0.22447082025039022
Fold 5 IBS: 0.21785969343588263
[I 2024-04-16 03:43:59,533] Trial 62 finished with value: 0.21623041774836782 and parameters: {'subsample': 0.35162005527246953, 'learning_rate': 0.07162165893265986, 'dropout_rate': 0.7683459560011311, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022802443424669597, 'min_weight_fraction_leaf': 0.2983669388531223, 'max_features': 'log2', 'min_impurity_decrease': 0.0001919679928415339, 'validation_fraction': 0.8181036899378618, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.21623041774836782.
Fold 1 IBS: 0.21363899466448114
Fold 2 IBS: 0.22109332397683143
Fold 3 IBS: 0.20406859594311752
Fold 4 IBS: 0.2244621075022513
Fold 5 IBS: 0.2178545151761114
[I 2024-04-16 03:44:35,415] Trial 63 finished with value: 0.21622350745255856 and parameters: {'subsample': 0.3567446827796533, 'learning_rate': 0.07169892058573697, 'dropout_rate': 0.7775471917139705, 'n_estimators': 495, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01806705726143175, 'min_weight_fraction_leaf': 0.29353532528586684, 'max_features': 'log2', 'min_impurity_decrease': 0.0010116175104178482, 'validation_fraction': 0.7243004778427239, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-16 03:45:27,073] Trial 64 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.3886078974413502, 'learning_rate': 0.07144507176729598, 'dropout_rate': 0.7023821481980385, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.43348045602434143, 'min_weight_fraction_leaf': 0.27473389221902517, 'max_features': 'log2', 'min_impurity_decrease': 0.0009682656128507961, 'validation_fraction': 0.7627539202845117, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:45:51,124] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2673613405331815, 'learning_rate': 0.06567665087392267, 'dropout_rate': 0.9044904250308854, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.925332478660159, 'min_weight_fraction_leaf': 0.32166013263939586, 'max_features': 'log2', 'min_impurity_decrease': 0.0038325871299788386, 'validation_fraction': 0.8074879921001441, 'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21382194104848268
Fold 2 IBS: 0.22143055090883293
Fold 3 IBS: 0.2042112188973405
Fold 4 IBS: 0.2245855848801812
Fold 5 IBS: 0.21804746500054503
[I 2024-04-16 03:46:32,274] Trial 66 finished with value: 0.21641935214707647 and parameters: {'subsample': 0.4479841440927695, 'learning_rate': 0.07944842979211152, 'dropout_rate': 0.7558727638855666, 'n_estimators': 479, 'criterion': 'friedman_mse', 'ccp_alpha': 0.06581072581869334, 'min_weight_fraction_leaf': 0.24401127082290142, 'max_features': 'log2', 'min_impurity_decrease': 0.007856364367505055, 'validation_fraction': 0.8694699708304008, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:46:55,967] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.44533772449036413, 'learning_rate': 0.0814448088163274, 'dropout_rate': 0.8313520760085876, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5496755232313972, 'min_weight_fraction_leaf': 0.23846073397265538, 'max_features': 'log2', 'min_impurity_decrease': 0.0245829172127866, 'validation_fraction': 0.8751349059723512, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 03:47:33,837] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.49945879365729917, 'learning_rate': 0.07904961819884797, 'dropout_rate': 0.7519380649315037, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.8957585677593288, 'min_weight_fraction_leaf': 0.34957407691787235, 'max_features': 'log2', 'min_impurity_decrease': 0.013697139277504513, 'validation_fraction': 0.9123753116320972, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:48:05,889] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.32975856917620583, 'learning_rate': 0.06481359395677139, 'dropout_rate': 0.7746913930571027, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1637311364800136, 'min_weight_fraction_leaf': 0.2664740964846672, 'max_features': 'log2', 'min_impurity_decrease': 0.009633379913496559, 'validation_fraction': 0.6626736312675832, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:48:30,854] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.2082560982819609, 'learning_rate': 0.056100758346501266, 'dropout_rate': 0.8822399932671225, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010162627459860702, 'min_weight_fraction_leaf': 0.25337827716940275, 'max_features': 'log2', 'min_impurity_decrease': 0.042176472946749144, 'validation_fraction': 0.8082415325648188, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.2215779171866794
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:49:02,701] Trial 71 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39260950413966267, 'learning_rate': 0.07026974490651595, 'dropout_rate': 0.7335367340802712, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2698698998773895, 'min_weight_fraction_leaf': 0.33122858051664955, 'max_features': 'log2', 'min_impurity_decrease': 0.07623847919135997, 'validation_fraction': 0.7333696044027135, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:49:40,809] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.36137940306921024, 'learning_rate': 0.07365043020696545, 'dropout_rate': 0.6771558577713755, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6400766669093484, 'min_weight_fraction_leaf': 0.30089829515047245, 'max_features': 'log2', 'min_impurity_decrease': 0.00042689293034457433, 'validation_fraction': 0.7634619284628702, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:50:20,828] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.48151682839955934, 'learning_rate': 0.06817264381363343, 'dropout_rate': 0.7024988926880507, 'n_estimators': 471, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3657398885794429, 'min_weight_fraction_leaf': 0.24216909030592224, 'max_features': 'log2', 'min_impurity_decrease': 0.0021650937570782437, 'validation_fraction': 0.8641607956473496, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-16 03:50:52,000] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4215055568651348, 'learning_rate': 0.07810222356149038, 'dropout_rate': 0.8205209533828131, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7381991024391248, 'min_weight_fraction_leaf': 0.35369645882730016, 'max_features': 'log2', 'min_impurity_decrease': 4.6048213048729805e-05, 'validation_fraction': 0.9414144145640158, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 63 with value: 0.21622350745255856.
Fold 1 IBS: 0.21358131440597533
Fold 2 IBS: 0.2207766549922031
Fold 3 IBS: 0.2037823815478675
Fold 4 IBS: 0.22432032365931623
Fold 5 IBS: 0.21769163686419699
[I 2024-04-16 03:51:15,392] Trial 75 finished with value: 0.21603046229391182 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.7826693566389662, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.009365616677551508, 'min_weight_fraction_leaf': 0.2812508412156809, 'max_features': 'log2', 'min_impurity_decrease': 0.0008096076350961149, 'validation_fraction': 0.7004324115891782, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:51:36,785] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5316206971146037, 'learning_rate': 0.08789602466821712, 'dropout_rate': 0.7878921244358874, 'n_estimators': 376, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7129649228563721, 'min_weight_fraction_leaf': 0.2739615311557543, 'max_features': 'log2', 'min_impurity_decrease': 0.000870969610631372, 'validation_fraction': 0.708303200355191, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:52:01,910] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.44602496158905264, 'learning_rate': 0.09471995926608345, 'dropout_rate': 0.8416081500565789, 'n_estimators': 449, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1836750520365744, 'min_weight_fraction_leaf': 0.322243588217481, 'max_features': 'log2', 'min_impurity_decrease': 0.0006764533780293487, 'validation_fraction': 0.685260872290134, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.2136441274067703

Fold 2 IBS: 0.22103795223774314
Fold 3 IBS: 0.20401739251272527
Fold 4 IBS: 0.22443280508876015
Fold 5 IBS: 0.21789254751435055
[I 2024-04-16 03:52:27,130] Trial 78 finished with value: 0.21620496495206992 and parameters: {'subsample': 0.3352733938121141, 'learning_rate': 0.07411999177509665, 'dropout_rate': 0.8605229004531987, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.023234528924181166, 'min_weight_fraction_leaf': 0.20870378808533252, 'max_features': 'log2', 'min_impurity_decrease': 0.007686471270079544, 'validation_fraction': 0.6325076348170467, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21367567354444209
Fold 2 IBS: 0.22106789416004893
Fold 3 IBS: 0.20416799678888137
Fold 4 IBS: 0.22445627718920175
Fold 5 IBS: 0.2178911936966356
[I 2024-04-16 03:52:38,730] Trial 79 finished with value: 0.21625180707584196 and parameters: {'subsample': 0.33166032751272273, 'learning_rate': 0.07500771068641232, 'dropout_rate': 0.959151447197707, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.006098257907680538, 'min_weight_fraction_leaf': 0.1475995309958919, 'max_features': 'log2', 'min_impurity_decrease': 0.00794742620491249, 'validation_fraction': 0.8199692718327473, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:52:50,453] Trial 80 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.32209627148296655, 'learning_rate': 0.08110077633419584, 'dropout_rate': 0.9673309512711019, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.4189618906006418, 'min_weight_fraction_leaf': 0.1370057476341762, 'max_features': 'log2', 'min_impurity_decrease': 0.007576465474689223, 'validation_fraction': 0.7888212409638161, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.2137221393654882
Fold 2 IBS: 0.22121840279065938
Fold 3 IBS: 0.20410564257822464
Fold 4 IBS: 0.224499882725744
Fold 5 IBS: 0.2179043211476655
[I 2024-04-16 03:53:10,453] Trial 81 finished with value: 0.21629007772155634 and parameters: {'subsample': 0.2730789104176549, 'learning_rate': 0.07535038448871262, 'dropout_rate': 0.8907726644005417, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.025664346357114027, 'min_weight_fraction_leaf': 0.21347182296833242, 'max_features': 'log2', 'min_impurity_decrease': 0.0028792178882720604, 'validation_fraction': 0.8134622977427909, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:53:26,722] Trial 82 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.2443803359673073, 'learning_rate': 0.07515191280946948, 'dropout_rate': 0.9365742852061131, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.6846594891336125, 'min_weight_fraction_leaf': 0.2110761039955827, 'max_features': 'log2', 'min_impurity_decrease': 0.003770285603834295, 'validation_fraction': 0.8215587831404426, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-16 03:53:40,087] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2987744122181278, 'learning_rate': 0.07751714625692861, 'dropout_rate': 0.9517605425833411, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 1.1625030732953487, 'min_weight_fraction_leaf': 0.17683438341305044, 'max_features': 'log2', 'min_impurity_decrease': 0.013019692174691478, 'validation_fraction': 0.8425793687098613, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:53:55,714] Trial 84 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.272692965452795, 'learning_rate': 0.09218659555435788, 'dropout_rate': 0.9120677449246954, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.31345585885032023, 'min_weight_fraction_leaf': 0.1504169269634668, 'max_features': 'log2', 'min_impurity_decrease': 0.001310541261910843, 'validation_fraction': 0.77453385805827, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21346989435966807
Fold 2 IBS: 0.22092762821728795
Fold 3 IBS: 0.20383530568616193
Fold 4 IBS: 0.22434822229065068
Fold 5 IBS: 0.21780267413770252
[I 2024-04-16 03:54:13,503] Trial 85 finished with value: 0.21607674493829424 and parameters: {'subsample': 0.33629527130521414, 'learning_rate': 0.0870188009772593, 'dropout_rate': 0.8650736182476468, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.011442347425600019, 'min_weight_fraction_leaf': 0.20755679443331537, 'max_features': 'log2', 'min_impurity_decrease': 0.0023183056456774986, 'validation_fraction': 0.611401083754954, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:54:30,421] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.21963133741289753, 'learning_rate': 0.08691689895122054, 'dropout_rate': 0.8639328821805979, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.8595756716116553, 'min_weight_fraction_leaf': 0.2075199255789235, 'max_features': 'log2', 'min_impurity_decrease': 0.0024751974417942736, 'validation_fraction': 0.6298878350786835, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:54:38,497] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3402343884216612, 'learning_rate': 0.08193314615040609, 'dropout_rate': 0.9957728348703542, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.4303615780077674, 'min_weight_fraction_leaf': 0.10151778721521143, 'max_features': 'log2', 'min_impurity_decrease': 0.006334784831296356, 'validation_fraction': 0.5951116917871544, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:55:02,409] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.301968281614769, 'learning_rate': 0.09101353432453513, 'dropout_rate': 0.8588126669771299, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.5804172950325953, 'min_weight_fraction_leaf': 0.22570081451818483, 'max_features': 'log2', 'min_impurity_decrease': 0.003713652825592109, 'validation_fraction': 0.8637776054651919, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:55:22,520] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.40845912170347753, 'learning_rate': 0.07409455257113193, 'dropout_rate': 0.9031580025226588, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 1.426169496743956, 'min_weight_fraction_leaf': 0.17670307432796536, 'max_features': 'log2', 'min_impurity_decrease': 0.001833888378396466, 'validation_fraction': 0.7135149436193794, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473737834741545
Fold 5 IBS: 0.21812431525609557
[I 2024-04-16 03:55:42,259] Trial 90 finished with value: 0.21659041601237358 and parameters: {'subsample': 0.2452119153654136, 'learning_rate': 0.06690965498406037, 'dropout_rate': 0.8066291177301238, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.25226236647044514, 'min_weight_fraction_leaf': 0.2043087203480301, 'max_features': 'log2', 'min_impurity_decrease': 0.015893997542605183, 'validation_fraction': 0.6554569651844447, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21369951219102495
Fold 2 IBS: 0.22118052877364758
Fold 3 IBS: 0.2040041163800213
Fold 4 IBS: 0.22447322608301454
Fold 5 IBS: 0.21791529977885088
[I 2024-04-16 03:56:10,666] Trial 91 finished with value: 0.21625453664131186 and parameters: {'subsample': 0.4756341195439041, 'learning_rate': 0.0800252800386436, 'dropout_rate': 0.7652963456531969, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.03815642121067697, 'min_weight_fraction_leaf': 0.2460810079638242, 'max_features': 'log2', 'min_impurity_decrease': 0.0029462543097600468, 'validation_fraction': 0.8222999411247428, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:56:25,471] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4738692621675931, 'learning_rate': 0.08571120447983799, 'dropout_rate': 0.9279795412285471, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0329237742117718, 'min_weight_fraction_leaf': 0.24643635347261278, 'max_features': 'log2', 'min_impurity_decrease': 0.009212522759670414, 'validation_fraction': 0.6810950539045996, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21375595560866592
Fold 2 IBS: 0.2212597867101977
Fold 3 IBS: 0.20402276703472014
Fold 4 IBS: 0.22449433981223132
Fold 5 IBS: 0.21797533850179815
[I 2024-04-16 03:56:59,193] Trial 93 finished with value: 0.21630163753352263 and parameters: {'subsample': 0.502022316864097, 'learning_rate': 0.08011752117044743, 'dropout_rate': 0.738394230646288, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.04782056519286319, 'min_weight_fraction_leaf': 0.2319086524805259, 'max_features': 'log2', 'min_impurity_decrease': 0.004724206934754632, 'validation_fraction': 0.8956179143254437, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:57:23,369] Trial 94 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.3474996745904486, 'learning_rate': 0.06916682435148223, 'dropout_rate': 0.7863795201728742, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.5434180175655979, 'min_weight_fraction_leaf': 0.17702787860367203, 'max_features': 'log2', 'min_impurity_decrease': 0.00132591111872389, 'validation_fraction': 0.817381490179014, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-16 03:57:43,292] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5072126109779981, 'learning_rate': 0.09404126235069282, 'dropout_rate': 0.8526269567049083, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.7732662773015029, 'min_weight_fraction_leaf': 0.2319533947623919, 'max_features': 'log2', 'min_impurity_decrease': 0.002924808261158542, 'validation_fraction': 0.9258516255293189, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:58:01,103] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3103600726415323, 'learning_rate': 0.06406371557843682, 'dropout_rate': 0.8199827211243065, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 0.2396855828547869, 'min_weight_fraction_leaf': 0.261970915381811, 'max_features': 1, 'min_impurity_decrease': 0.005183152799306324, 'validation_fraction': 0.8996721903976425, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-16 03:58:31,083] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.28651805009091497, 'learning_rate': 0.0838006258575085, 'dropout_rate': 0.7414748169104224, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.299429272232856, 'min_weight_fraction_leaf': 0.22029404567890065, 'max_features': 0.1, 'min_impurity_decrease': 0.0032862083702029487, 'validation_fraction': 0.6089360683568277, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-16 03:58:47,878] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5129217027539859, 'learning_rate': 0.08060435391980184, 'dropout_rate': 0.8846093811473095, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.5371484454220302, 'min_weight_fraction_leaf': 0.20058461034167657, 'max_features': 'log2', 'min_impurity_decrease': 0.0011099956679015755, 'validation_fraction': 0.97208801308084, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.21603046229391182.
Fold 1 IBS: 0.21360379452388797
Fold 2 IBS: 0.2208074934973978
Fold 3 IBS: 0.20395142901174781
Fold 4 IBS: 0.224300806480348
Fold 5 IBS: 0.21792517713361603
[I 2024-04-16 03:58:57,563] Trial 99 finished with value: 0.21611774012939952 and parameters: {'subsample': 0.40639725945398314, 'learning_rate': 0.07562787330036341, 'dropout_rate': 0.97231310078209, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.0045100151809840325, 'min_weight_fraction_leaf': 0.14310707528126343, 'max_features': 'log2', 'min_impurity_decrease': 0.0005780747492707621, 'validation_fraction': 0.7834834248980211, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 75 with value: 0.21603046229391182.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.21603046229391182], datetime_start=datetime.datetime(2024, 4, 16, 3, 50, 52, 7344), datetime_complete=datetime.datetime(2024, 4, 16, 3, 51, 15, 391260), params={'subsample': 0.5200735929114648, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.7826693566389662, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.009365616677551508, 'min_weight_fraction_leaf': 0.2812508412156809, 'max_features': 'log2', 'min_impurity_decrease': 0.0008096076350961149, 'validation_fraction': 0.7004324115891782, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.21603046229391182

In [69]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [70]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.661
train_ibs:  0.216

#### Test

In [71]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [72]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.07426378544613033,
                                 criterion='squared_error',
                                 dropout_rate=0.28125955124323376,
                                 learning_rate=0.013102111413618,
                                 max_features='auto', max_leaf_nodes=16,
                                 min_impurity_decrease=1.4994028685178666e-07,
                                 min_samples_leaf=10,
                                 min_weight_fraction_leaf=0.27579636299120275,
                                 n_estimators=406, random_state=123,
                                 subsample=0.6059965408578151,
                                 validation_fraction=0.6359003593513561)

C-index score: 0.617

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009365616677551508,
                                 dropout_rate=0.7826693566389662,
                                 learning_rate=0.08843409287484169, max_depth=4,
                                 max_features='log2', max_leaf_nodes=14,
                                 min_impurity_decrease=0.0008096076350961149,
                                 min_samples_leaf=16, min_samples_split=19,
                                 min_weight_fraction_leaf=0.2812508412156809,
                                 n_estimators=403, random_state=123,
                                 subsample=0.5200735929114648,
                                 validation_fraction=0.7004324115891782)

IBS: 0.221

In [73]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [74]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [75]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 03:59:16,739] A new study created in memory with name: no-name-1673607a-f872-4908-9c63-8b9aa056f559

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:18,262] Trial 0 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:27,908] Trial 1 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:29,792] Trial 2 finished with value: 0.6805414605346831 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:32,363] Trial 3 finished with value: 0.6790391824082426 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:36,230] Trial 4 finished with value: 0.6783422264106538 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:41,696] Trial 5 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:43,965] Trial 6 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:44,660] Trial 7 finished with value: 0.683258591690943 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:47,499] Trial 8 finished with value: 0.683209616404626 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 03:59:56,709] Trial 9 finished with value: 0.6840534982611661 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:01,475] Trial 10 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 328, 'learning_rate': 0.0017980531969980576}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:05,832] Trial 11 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.756040755732822, 'n_estimators': 318, 'learning_rate': 0.01192895807324408}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:12,100] Trial 12 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.6475328937135156, 'n_estimators': 368, 'learning_rate': 0.00211473379798891}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:13,651] Trial 13 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8828571249279873, 'dropout_rate': 0.9845292840882569, 'n_estimators': 109, 'learning_rate': 0.021551885021979505}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:18,550] Trial 14 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.8303809418383279, 'dropout_rate': 0.3633325368639867, 'n_estimators': 312, 'learning_rate': 0.08842544557957996}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:19,134] Trial 15 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8500676869704417, 'dropout_rate': 0.7036446331147568, 'n_estimators': 30, 'learning_rate': 0.026008464594474617}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 04:00:28,799] Trial 16 finished with value: 0.6838884942135495 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.5672052413745938, 'n_estimators': 419, 'learning_rate': 0.0016507495863954742}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:33,107] Trial 17 finished with value: 0.6823657345480859 and parameters: {'subsample': 0.6438765164510524, 'dropout_rate': 0.10421921753457947, 'n_estimators': 261, 'learning_rate': 0.036669999020907625}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:35,027] Trial 18 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9017513432164477, 'dropout_rate': 0.800599759623587, 'n_estimators': 138, 'learning_rate': 0.0169316883078754}. Best is trial 6 with value: 0.6847608698173835.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:40,069] Trial 19 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.765021860726683, 'dropout_rate': 0.28451388926437, 'n_estimators': 299, 'learning_rate': 0.009486725203279353}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:46,870] Trial 20 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.6102628884762309, 'dropout_rate': 0.5936662553833888, 'n_estimators': 386, 'learning_rate': 0.039803505489267865}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:51,452] Trial 21 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9837835691847544, 'dropout_rate': 0.7782496125319235, 'n_estimators': 325, 'learning_rate': 0.013553592433121441}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:54,357] Trial 22 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9444894354323914, 'dropout_rate': 0.7240753153650541, 'n_estimators': 220, 'learning_rate': 0.00956395604408998}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:00:59,162] Trial 23 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.8044268000036454, 'dropout_rate': 0.4523929301550861, 'n_estimators': 298, 'learning_rate': 0.025243537220664847}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:07,072] Trial 24 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.909720259219588, 'dropout_rate': 0.8168861354051056, 'n_estimators': 415, 'learning_rate': 0.0015747884979969082}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:09,994] Trial 25 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9806380936668403, 'dropout_rate': 0.9550172423277872, 'n_estimators': 245, 'learning_rate': 0.017437187361754786}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:15,451] Trial 26 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.696402054151678, 'dropout_rate': 0.6240031701840147, 'n_estimators': 340, 'learning_rate': 0.03055277087836818}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:17,577] Trial 27 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8040602609666779, 'dropout_rate': 0.7438736652834751, 'n_estimators': 167, 'learning_rate': 0.010423584287077988}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-16 04:01:18,520] Trial 28 finished with value: 0.6830269961110103 and parameters: {'subsample': 0.5885506824599395, 'dropout_rate': 0.5144334224359576, 'n_estimators': 71, 'learning_rate': 0.02100249369375673}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:27,078] Trial 29 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.7266570943105202, 'dropout_rate': 0.3814659124470032, 'n_estimators': 421, 'learning_rate': 0.09808303187565434}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:28,394] Trial 30 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8753846646309973, 'dropout_rate': 0.26032219643226895, 'n_estimators': 103, 'learning_rate': 0.0071246912573001385}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:35,518] Trial 31 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9555524648105653, 'dropout_rate': 0.6478671362870704, 'n_estimators': 375, 'learning_rate': 0.0025729132723603426}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:41,167] Trial 32 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9971081113157667, 'dropout_rate': 0.6832267561059584, 'n_estimators': 344, 'learning_rate': 0.0064234648246977106}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:45,044] Trial 33 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9300606190734005, 'dropout_rate': 0.4143407329764668, 'n_estimators': 267, 'learning_rate': 0.014083188941607264}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:54,770] Trial 34 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.7635177244694447, 'dropout_rate': 0.5051054684842515, 'n_estimators': 443, 'learning_rate': 0.019205764804350253}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:01:56,689] Trial 35 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9948699873151601, 'dropout_rate': 0.8554198628220362, 'n_estimators': 169, 'learning_rate': 0.026347153881734295}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:00,523] Trial 36 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8486810924752858, 'dropout_rate': 0.7495910733397618, 'n_estimators': 283, 'learning_rate': 0.005872161004168533}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:03,612] Trial 37 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9252292506175763, 'dropout_rate': 0.6198740536882945, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 6 with value: 0.6847608698173835.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:10,367] Trial 38 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.7933691320344304, 'dropout_rate': 0.3000960517027121, 'n_estimators': 356, 'learning_rate': 0.013887612982787472}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:18,845] Trial 39 finished with value: 0.6841514488338002 and parameters: {'subsample': 0.3246512531312218, 'dropout_rate': 0.4491392168970607, 'n_estimators': 388, 'learning_rate': 0.04653270707709469}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:21,515] Trial 40 finished with value: 0.6822292242477632 and parameters: {'subsample': 0.7191514521403073, 'dropout_rate': 0.20013020077502125, 'n_estimators': 196, 'learning_rate': 0.07255507912086517}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:22,878] Trial 41 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8792885118422278, 'dropout_rate': 0.9593982871820748, 'n_estimators': 127, 'learning_rate': 0.022705071582575315}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:23,800] Trial 42 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.948004708741089, 'dropout_rate': 0.8979164212512727, 'n_estimators': 85, 'learning_rate': 0.03008335479976736}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:25,365] Trial 43 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8777555490455407, 'dropout_rate': 0.9950837425411467, 'n_estimators': 145, 'learning_rate': 0.034721110808958955}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:25,748] Trial 44 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8285886673541394, 'dropout_rate': 0.8401042819641488, 'n_estimators': 3, 'learning_rate': 0.012476987633421258}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:31,089] Trial 45 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8910866806612963, 'dropout_rate': 0.5701209079609209, 'n_estimators': 325, 'learning_rate': 0.004310866916365117}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:33,442] Trial 46 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9531765666478423, 'dropout_rate': 0.6968452248898738, 'n_estimators': 193, 'learning_rate': 0.017344981466567447}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:37,100] Trial 47 finished with value: 0.6848973801177062 and parameters: {'subsample': 0.527363285706077, 'dropout_rate': 0.7682051640937968, 'n_estimators': 232, 'learning_rate': 0.08063451221472408}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:40,826] Trial 48 finished with value: 0.6840534982611661 and parameters: {'subsample': 0.4347474441360432, 'dropout_rate': 0.7775650650074952, 'n_estimators': 229, 'learning_rate': 0.08205057028477633}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:44,451] Trial 49 finished with value: 0.6848973801177062 and parameters: {'subsample': 0.5142967488667298, 'dropout_rate': 0.8995673411857124, 'n_estimators': 280, 'learning_rate': 0.06615495649623622}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:47,915] Trial 50 finished with value: 0.6840534982611661 and parameters: {'subsample': 0.5169836498315967, 'dropout_rate': 0.8930958402192378, 'n_estimators': 287, 'learning_rate': 0.06333475403011146}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:51,964] Trial 51 finished with value: 0.683209616404626 and parameters: {'subsample': 0.43083736341534906, 'dropout_rate': 0.808963951792107, 'n_estimators': 272, 'learning_rate': 0.08186612941877527}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:02:57,345] Trial 52 finished with value: 0.6839169879608434 and parameters: {'subsample': 0.5690309943235562, 'dropout_rate': 0.6639389449339747, 'n_estimators': 325, 'learning_rate': 0.06894220767222058}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:00,499] Trial 53 finished with value: 0.683209616404626 and parameters: {'subsample': 0.44673107727090555, 'dropout_rate': 0.7208587925293667, 'n_estimators': 251, 'learning_rate': 0.077127854280814}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:04,807] Trial 54 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.6590017573206688, 'dropout_rate': 0.7769927675195814, 'n_estimators': 305, 'learning_rate': 0.05003905217668886}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:07,422] Trial 55 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.9427849869827579, 'n_estimators': 208, 'learning_rate': 0.0929093594804002}. Best is trial 47 with value: 0.6848973801177062.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:13,251] Trial 56 finished with value: 0.6841024735474831 and parameters: {'subsample': 0.35897821562986026, 'dropout_rate': 0.6359464082589685, 'n_estimators': 368, 'learning_rate': 0.05643784928858577}. Best is trial 47 with value: 0.6848973801177062.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-16 04:03:16,186] Trial 57 finished with value: 0.6854011878986185 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.594164009035948, 'n_estimators': 233, 'learning_rate': 0.06795033768066108}. Best is trial 57 with value: 0.6854011878986185.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 04:03:18,832] Trial 58 finished with value: 0.6828400730541329 and parameters: {'subsample': 0.16732601870079059, 'dropout_rate': 0.5316914271127542, 'n_estimators': 184, 'learning_rate': 0.06421915829879536}. Best is trial 57 with value: 0.6854011878986185.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 04:03:22,454] Trial 59 finished with value: 0.6855957639380815 and parameters: {'subsample': 0.19049801843746383, 'dropout_rate': 0.8270409232804834, 'n_estimators': 244, 'learning_rate': 0.07744714139435108}. Best is trial 59 with value: 0.6855957639380815.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 04:03:25,454] Trial 60 finished with value: 0.6816619600724454 and parameters: {'subsample': 0.1974339717152958, 'dropout_rate': 0.8738579802353442, 'n_estimators': 216, 'learning_rate': 0.07776858452728436}. Best is trial 59 with value: 0.6855957639380815.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 04:03:28,444] Trial 61 finished with value: 0.6835203883332941 and parameters: {'subsample': 0.11670084820748178, 'dropout_rate': 0.8305900561785673, 'n_estimators': 238, 'learning_rate': 0.08535773260439891}. Best is trial 59 with value: 0.6855957639380815.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:30,118] Trial 62 finished with value: 0.6817448101138703 and parameters: {'subsample': 0.24789643716334214, 'dropout_rate': 0.7391543483469142, 'n_estimators': 150, 'learning_rate': 0.06790415180753269}. Best is trial 59 with value: 0.6855957639380815.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:33,781] Trial 63 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.7825488165586719, 'n_estimators': 255, 'learning_rate': 0.07348907933203751}. Best is trial 59 with value: 0.6855957639380815.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 04:03:37,627] Trial 64 finished with value: 0.6828400730541329 and parameters: {'subsample': 0.14790777805800925, 'dropout_rate': 0.9220417025518083, 'n_estimators': 283, 'learning_rate': 0.06850193299865748}. Best is trial 59 with value: 0.6855957639380815.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6338028169014085
[I 2024-04-16 04:03:42,839] Trial 65 finished with value: 0.6816838790817061 and parameters: {'subsample': 0.2094575640357465, 'dropout_rate': 0.32153147444328267, 'n_estimators': 310, 'learning_rate': 0.08797944069922561}. Best is trial 59 with value: 0.6855957639380815.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:46,693] Trial 66 finished with value: 0.6867810449760545 and parameters: {'subsample': 0.29906581339440674, 'dropout_rate': 0.7618389561548465, 'n_estimators': 271, 'learning_rate': 0.07570315271300614}. Best is trial 66 with value: 0.6867810449760545.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:49,414] Trial 67 finished with value: 0.6877614371329173 and parameters: {'subsample': 0.3054811831292578, 'dropout_rate': 0.7166562602631428, 'n_estimators': 227, 'learning_rate': 0.07736008213803257}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:52,386] Trial 68 finished with value: 0.6841514488338002 and parameters: {'subsample': 0.3313128529432968, 'dropout_rate': 0.583662202262188, 'n_estimators': 228, 'learning_rate': 0.08013005350658634}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:54,458] Trial 69 finished with value: 0.6842764556834906 and parameters: {'subsample': 0.22670760492351902, 'dropout_rate': 0.8516819387525313, 'n_estimators': 178, 'learning_rate': 0.07616127065553653}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:03:57,502] Trial 70 finished with value: 0.6841514488338002 and parameters: {'subsample': 0.3113960398172684, 'dropout_rate': 0.6787809243661579, 'n_estimators': 206, 'learning_rate': 0.08625872082959897}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:01,164] Trial 71 finished with value: 0.683258591690943 and parameters: {'subsample': 0.40606303451634973, 'dropout_rate': 0.7178705789257822, 'n_estimators': 269, 'learning_rate': 0.07140286027994266}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 04:04:03,669] Trial 72 finished with value: 0.6869907215467265 and parameters: {'subsample': 0.29185290226096555, 'dropout_rate': 0.6134779412492984, 'n_estimators': 222, 'learning_rate': 0.06561994989015058}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:06,256] Trial 73 finished with value: 0.6851203375400308 and parameters: {'subsample': 0.2838096994546372, 'dropout_rate': 0.6078067051596978, 'n_estimators': 217, 'learning_rate': 0.06552555944095279}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:08,899] Trial 74 finished with value: 0.6851203375400308 and parameters: {'subsample': 0.2731493752169846, 'dropout_rate': 0.6128365123041772, 'n_estimators': 226, 'learning_rate': 0.06118808540896983}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:11,572] Trial 75 finished with value: 0.6861007296968935 and parameters: {'subsample': 0.2766989651425278, 'dropout_rate': 0.6049556650992312, 'n_estimators': 234, 'learning_rate': 0.06194831149028562}. Best is trial 67 with value: 0.6877614371329173.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:14,578] Trial 76 finished with value: 0.6851203375400308 and parameters: {'subsample': 0.28064358162123587, 'dropout_rate': 0.6057872655641577, 'n_estimators': 253, 'learning_rate': 0.05992326510937737}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:17,627] Trial 77 finished with value: 0.6851203375400308 and parameters: {'subsample': 0.27829551075174636, 'dropout_rate': 0.5528378993257163, 'n_estimators': 220, 'learning_rate': 0.0561564195057494}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:19,428] Trial 78 finished with value: 0.6842493994064343 and parameters: {'subsample': 0.2519181449679863, 'dropout_rate': 0.4828317854803734, 'n_estimators': 159, 'learning_rate': 0.06301590434476251}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:22,053] Trial 79 finished with value: 0.6877614371329173 and parameters: {'subsample': 0.29730929679022533, 'dropout_rate': 0.6065352860754915, 'n_estimators': 201, 'learning_rate': 0.07050278842494744}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:24,319] Trial 80 finished with value: 0.6841514488338002 and parameters: {'subsample': 0.30829664866836504, 'dropout_rate': 0.6570156007100658, 'n_estimators': 194, 'learning_rate': 0.07145844445388265}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:27,364] Trial 81 finished with value: 0.6841024735474831 and parameters: {'subsample': 0.36895695920658633, 'dropout_rate': 0.5918056828569579, 'n_estimators': 214, 'learning_rate': 0.05191285063438977}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 04:04:31,562] Trial 82 finished with value: 0.683634979624356 and parameters: {'subsample': 0.18063596320733685, 'dropout_rate': 0.6128624479989034, 'n_estimators': 241, 'learning_rate': 0.07575857912091358}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:34,003] Trial 83 finished with value: 0.6851203375400308 and parameters: {'subsample': 0.22853397242922496, 'dropout_rate': 0.537227369386051, 'n_estimators': 183, 'learning_rate': 0.0657327792957669}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:36,719] Trial 84 finished with value: 0.6860517544105763 and parameters: {'subsample': 0.29266071247177156, 'dropout_rate': 0.6422295170211368, 'n_estimators': 226, 'learning_rate': 0.06007285015058249}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-16 04:04:39,845] Trial 85 finished with value: 0.682725481763071 and parameters: {'subsample': 0.14392399741016249, 'dropout_rate': 0.694844527818052, 'n_estimators': 261, 'learning_rate': 0.05845685686157931}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 04:04:42,122] Trial 86 finished with value: 0.6850414406836334 and parameters: {'subsample': 0.3664546984370923, 'dropout_rate': 0.5641081762283938, 'n_estimators': 203, 'learning_rate': 0.069645091722765}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:44,923] Trial 87 finished with value: 0.6859152441102536 and parameters: {'subsample': 0.296562180735571, 'dropout_rate': 0.6335385883245235, 'n_estimators': 241, 'learning_rate': 0.05353856660204604}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:49,165] Trial 88 finished with value: 0.6849953306903404 and parameters: {'subsample': 0.34203363661123565, 'dropout_rate': 0.638303006279975, 'n_estimators': 295, 'learning_rate': 0.04647359430999269}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:52,133] Trial 89 finished with value: 0.6823657345480859 and parameters: {'subsample': 0.3984453754856289, 'dropout_rate': 0.5092363258287973, 'n_estimators': 241, 'learning_rate': 0.07868179842489689}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:55,560] Trial 90 finished with value: 0.6867810449760545 and parameters: {'subsample': 0.30289648202620323, 'dropout_rate': 0.6667673044374423, 'n_estimators': 272, 'learning_rate': 0.07452584433793191}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:04:58,794] Trial 91 finished with value: 0.6858392125468804 and parameters: {'subsample': 0.30756610027497333, 'dropout_rate': 0.6703918627327489, 'n_estimators': 271, 'learning_rate': 0.07423121733779613}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:05:02,765] Trial 92 finished with value: 0.6867810449760545 and parameters: {'subsample': 0.30438269313181077, 'dropout_rate': 0.6715208782570004, 'n_estimators': 272, 'learning_rate': 0.07469792265688464}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:05:06,678] Trial 93 finished with value: 0.6867810449760545 and parameters: {'subsample': 0.2979004597060828, 'dropout_rate': 0.671308842052766, 'n_estimators': 273, 'learning_rate': 0.07309744129654872}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:05:10,741] Trial 94 finished with value: 0.6859861384058316 and parameters: {'subsample': 0.2531922205179834, 'dropout_rate': 0.6407001060923753, 'n_estimators': 260, 'learning_rate': 0.0544504671862013}. Best is trial 67 with value: 0.6877614371329173.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:05:15,830] Trial 95 finished with value: 0.6850713622537136 and parameters: {'subsample': 0.24677293780172924, 'dropout_rate': 0.7024053996238759, 'n_estimators': 293, 'learning_rate': 0.083680513443133}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:05:19,058] Trial 96 finished with value: 0.6841024735474831 and parameters: {'subsample': 0.3446159623070308, 'dropout_rate': 0.6848323226859824, 'n_estimators': 260, 'learning_rate': 0.07494467986913943}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6291079812206573
[I 2024-04-16 04:05:22,778] Trial 97 finished with value: 0.6869031865327211 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.6545244010310142, 'n_estimators': 274, 'learning_rate': 0.07100583513828063}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-16 04:05:27,641] Trial 98 finished with value: 0.6851203375400308 and parameters: {'subsample': 0.2180058163318294, 'dropout_rate': 0.7311501433291913, 'n_estimators': 342, 'learning_rate': 0.07319361560194747}. Best is trial 67 with value: 0.6877614371329173.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7468354430379747

[I 2024-04-16 04:05:31,475] A new study created in memory with name: no-name-5bc2f9f1-2790-44dd-a32e-88ca0ac94bc8

Fold 5 C-index: 0.6197183098591549
[I 2024-04-16 04:05:31,460] Trial 99 finished with value: 0.6806318608417127 and parameters: {'subsample': 0.3903474418366681, 'dropout_rate': 0.649129888956636, 'n_estimators': 278, 'learning_rate': 0.07113078489247003}. Best is trial 67 with value: 0.6877614371329173.


* Best trial for C-index:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.6877614371329173], datetime_start=datetime.datetime(2024, 4, 16, 4, 3, 46, 699374), datetime_complete=datetime.datetime(2024, 4, 16, 4, 3, 49, 413947), params={'subsample': 0.3054811831292578, 'dropout_rate': 0.7166562602631428, 'n_estimators': 227, 'learning_rate': 0.07736008213803257}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=67, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.3054811831292578, 'dropout_rate': 0.7166562602631428, 'n_estimators': 227, 'learning_rate': 0.07736008213803257}


* Best Score for C-index:
 0.6877614371329173

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2224371243647886
Fold 2 IBS: 0.19317332913894678
Fold 3 IBS: 0.18175388084440755
Fold 4 IBS: 0.19244381929374016
Fold 5 IBS: 0.2895470556233037
[I 2024-04-16 04:05:32,947] Trial 0 finished with value: 0.21587104185303735 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.24671279381337202
Fold 2 IBS: 0.29825563341910016
Fold 3 IBS: 0.22274079495378193
Fold 4 IBS: 0.2992450056446656
Fold 5 IBS: 0.3807985230506669
[I 2024-04-16 04:05:44,032] Trial 1 finished with value: 0.28955055017631737 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.23108469847085208
Fold 2 IBS: 0.2336848295780041
Fold 3 IBS: 0.18494628590086665
Fold 4 IBS: 0.22195970987072647
Fold 5 IBS: 0.34828871064569805
[I 2024-04-16 04:05:46,094] Trial 2 finished with value: 0.24399284689322945 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.23157554398476274
Fold 2 IBS: 0.23143286367095128
Fold 3 IBS: 0.18256067353122335
Fold 4 IBS: 0.23846682563036353
Fold 5 IBS: 0.3508974125718185
[I 2024-04-16 04:05:48,761] Trial 3 finished with value: 0.2469866638778239 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.23265002745306723
Fold 2 IBS: 0.2357058090135899
Fold 3 IBS: 0.18205382773702086
Fold 4 IBS: 0.24417681732234447
Fold 5 IBS: 0.3535707429074288
[I 2024-04-16 04:05:52,791] Trial 4 finished with value: 0.24963144488669026 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.24128998792103662
Fold 2 IBS: 0.2762997787521807
Fold 3 IBS: 0.20025811559513157
Fold 4 IBS: 0.26546816179349464
Fold 5 IBS: 0.3725504924440945
[I 2024-04-16 04:05:58,196] Trial 5 finished with value: 0.2711733073011876 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.21068463318276223
Fold 2 IBS: 0.18684500549023667
Fold 3 IBS: 0.17566720250103562
Fold 4 IBS: 0.189966463145634
Fold 5 IBS: 0.2632777024308626
[I 2024-04-16 04:06:00,597] Trial 6 finished with value: 0.20528820135010623 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20528820135010623.
Fold 1 IBS: 0.19893358640106418
Fold 2 IBS: 0.19480655197258015
Fold 3 IBS: 0.17781694236500464
Fold 4 IBS: 0.2013110478330258
Fold 5 IBS: 0.22988057976140916
[I 2024-04-16 04:06:01,345] Trial 7 finished with value: 0.2005497416666168 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22411588363673707
Fold 2 IBS: 0.19395660599165604
Fold 3 IBS: 0.1838931084018872
Fold 4 IBS: 0.19659222258901207
Fold 5 IBS: 0.29713134944437064
[I 2024-04-16 04:06:04,529] Trial 8 finished with value: 0.21913783401273262 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.24215194796114747
Fold 2 IBS: 0.2795582542494505
Fold 3 IBS: 0.2021738805487265
Fold 4 IBS: 0.268679491816033
Fold 5 IBS: 0.37379244274565304
[I 2024-04-16 04:06:12,651] Trial 9 finished with value: 0.2732712034642021 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2133777392595339
Fold 2 IBS: 0.22075911663973774
Fold 3 IBS: 0.20362701953372184
Fold 4 IBS: 0.2240281500374084
Fold 5 IBS: 0.21809863906487453
[I 2024-04-16 04:06:13,324] Trial 10 finished with value: 0.21597813290705528 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21288380226283657
Fold 2 IBS: 0.22032322957937875
Fold 3 IBS: 0.2042745608511555
Fold 4 IBS: 0.22410217190422801
Fold 5 IBS: 0.21809281059218802
[I 2024-04-16 04:06:13,837] Trial 11 finished with value: 0.21593531503795735 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22944247263535614
Fold 2 IBS: 0.20765472579544875
Fold 3 IBS: 0.1855396229358887
Fold 4 IBS: 0.21344387061271705
Fold 5 IBS: 0.3318352940522482
[I 2024-04-16 04:06:15,155] Trial 12 finished with value: 0.23358319720633175 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2290028773230912
Fold 2 IBS: 0.21252645480254392
Fold 3 IBS: 0.1855329634191624
Fold 4 IBS: 0.2057484889693888
Fold 5 IBS: 0.326385787266454
[I 2024-04-16 04:06:20,186] Trial 13 finished with value: 0.23183931435612806 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2005833169532511
Fold 2 IBS: 0.2008374330432463
Fold 3 IBS: 0.18240897572139836
Fold 4 IBS: 0.20640866347396433
Fold 5 IBS: 0.2237482380656478
[I 2024-04-16 04:06:21,884] Trial 14 finished with value: 0.20279732545150156 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2100788008631381
Fold 2 IBS: 0.2165116314827259
Fold 3 IBS: 0.19904919834791537
Fold 4 IBS: 0.22105344434847998
Fold 5 IBS: 0.2181778394270942
[I 2024-04-16 04:06:22,850] Trial 15 finished with value: 0.2129741828938707 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2047752320765482
Fold 2 IBS: 0.20805178791278306
Fold 3 IBS: 0.1902278421564896
Fold 4 IBS: 0.21388284815653996
Fold 5 IBS: 0.21967933702448122
[I 2024-04-16 04:06:23,689] Trial 16 finished with value: 0.20732340946536837 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21549515107667103
Fold 2 IBS: 0.18788613695948134
Fold 3 IBS: 0.17820999898175136
Fold 4 IBS: 0.1900257147184032
Fold 5 IBS: 0.27413215537692803
[I 2024-04-16 04:06:25,263] Trial 17 finished with value: 0.20914983142264704 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21636303175596067
Fold 2 IBS: 0.18768401418830014
Fold 3 IBS: 0.1800307888892072
Fold 4 IBS: 0.19399500745388318
Fold 5 IBS: 0.276083877120051
[I 2024-04-16 04:06:30,449] Trial 18 finished with value: 0.21083134388148045 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.19866591004117384
Fold 2 IBS: 0.1961029749264994
Fold 3 IBS: 0.18014179003928876

Fold 4 IBS: 0.2080662242520272
Fold 5 IBS: 0.228727148642183
[I 2024-04-16 04:06:31,166] Trial 19 finished with value: 0.20234080958023443 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.19900268568861765
Fold 2 IBS: 0.19673124531818784
Fold 3 IBS: 0.18097673731541652
Fold 4 IBS: 0.20623445559536285
Fold 5 IBS: 0.22394152158247504
[I 2024-04-16 04:06:31,904] Trial 20 finished with value: 0.20137732910001196 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20102182120527576
Fold 2 IBS: 0.20177601792835187
Fold 3 IBS: 0.1880831686670229
Fold 4 IBS: 0.21737450486532756
Fold 5 IBS: 0.22131729031914832
[I 2024-04-16 04:06:32,593] Trial 21 finished with value: 0.20591456059702526 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2124646743569866
Fold 2 IBS: 0.22042523088546775
Fold 3 IBS: 0.2025909014053614
Fold 4 IBS: 0.2235691020770519
Fold 5 IBS: 0.21809103495193327
[I 2024-04-16 04:06:33,031] Trial 22 finished with value: 0.21542818873536018 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21862277197658694
Fold 2 IBS: 0.18332269702089818
Fold 3 IBS: 0.18399636284561172
Fold 4 IBS: 0.20418493060437545
Fold 5 IBS: 0.2808037945631659
[I 2024-04-16 04:06:34,797] Trial 23 finished with value: 0.21418611140212765 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20491067601921656
Fold 2 IBS: 0.18740598066657257
Fold 3 IBS: 0.17465020553120653
Fold 4 IBS: 0.1941870846020327
Fold 5 IBS: 0.24866689726201885
[I 2024-04-16 04:06:35,568] Trial 24 finished with value: 0.20196416881620943 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22216629666753407
Fold 2 IBS: 0.19060249929699566
Fold 3 IBS: 0.1817624831102358
Fold 4 IBS: 0.19525170860969823
Fold 5 IBS: 0.28582833839045163
[I 2024-04-16 04:06:36,518] Trial 25 finished with value: 0.21512226521498307 and parameters: {'subsample': 0.39649741038083114, 'dropout_rate': 0.9011181177707686, 'n_estimators': 70, 'learning_rate': 0.08579428551722094}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2292652379408988
Fold 2 IBS: 0.21328570806551253
Fold 3 IBS: 0.18524706089498968
Fold 4 IBS: 0.21037011829159993
Fold 5 IBS: 0.33075206466524854
[I 2024-04-16 04:06:38,178] Trial 26 finished with value: 0.2337840379716499 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.7428521025450486, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.24292657838565376
Fold 2 IBS: 0.2777091248270974
Fold 3 IBS: 0.1965459221233886
Fold 4 IBS: 0.27293041494917186
Fold 5 IBS: 0.3766083819755308
[I 2024-04-16 04:06:43,957] Trial 27 finished with value: 0.2733440844521685 and parameters: {'subsample': 0.25017268379052987, 'dropout_rate': 0.8368873118701377, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.23011061167903255
Fold 2 IBS: 0.2218173694627172
Fold 3 IBS: 0.1846219976211082
Fold 4 IBS: 0.21774372942926154
Fold 5 IBS: 0.33874338539432947
[I 2024-04-16 04:06:46,337] Trial 28 finished with value: 0.2386074187172898 and parameters: {'subsample': 0.32549498689313283, 'dropout_rate': 0.9187406138362325, 'n_estimators': 236, 'learning_rate': 0.046726352221374515}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22753595132167745
Fold 2 IBS: 0.20249716167749232
Fold 3 IBS: 0.18520370978507786
Fold 4 IBS: 0.19929228608349597
Fold 5 IBS: 0.31324840664297765
[I 2024-04-16 04:06:47,371] Trial 29 finished with value: 0.22555550310214426 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.528113503868086, 'n_estimators': 98, 'learning_rate': 0.08423642007181871}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2255559493354091
Fold 2 IBS: 0.18935357910399872
Fold 3 IBS: 0.1894267642776359
Fold 4 IBS: 0.21084453751232646
Fold 5 IBS: 0.30052403445526077
[I 2024-04-16 04:06:48,791] Trial 30 finished with value: 0.2231409729369262 and parameters: {'subsample': 0.18603736202301935, 'dropout_rate': 0.6813568533831397, 'n_estimators': 131, 'learning_rate': 0.05802531255595394}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.19833758538279453
Fold 2 IBS: 0.19444145674492944
Fold 3 IBS: 0.18459430443696237
Fold 4 IBS: 0.2096206578233813
Fold 5 IBS: 0.22666021808265216
[I 2024-04-16 04:06:49,518] Trial 31 finished with value: 0.20273084449414397 and parameters: {'subsample': 0.13178840570553013, 'dropout_rate': 0.974912474343522, 'n_estimators': 42, 'learning_rate': 0.04796619662341173}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.19895154376305535
Fold 2 IBS: 0.1971961089866832
Fold 3 IBS: 0.17946858446419894
Fold 4 IBS: 0.2055509964621163
Fold 5 IBS: 0.22679100620232656
[I 2024-04-16 04:06:50,169] Trial 32 finished with value: 0.20159164797567608 and parameters: {'subsample': 0.2663212387057611, 'dropout_rate': 0.791102993543661, 'n_estimators': 50, 'learning_rate': 0.035458087225080745}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20024695169682136
Fold 2 IBS: 0.18964712759312974
Fold 3 IBS: 0.17571446824416467
Fold 4 IBS: 0.20025143315267666
Fold 5 IBS: 0.23849736004290123
[I 2024-04-16 04:06:51,348] Trial 33 finished with value: 0.20087146814593876 and parameters: {'subsample': 0.28375960802245515, 'dropout_rate': 0.7724416054749447, 'n_estimators': 85, 'learning_rate': 0.031317710466820706}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20190374206513476
Fold 2 IBS: 0.18659988482318876
Fold 3 IBS: 0.17537182001884782
Fold 4 IBS: 0.20002486596442334
Fold 5 IBS: 0.24378253012810414
[I 2024-04-16 04:06:52,544] Trial 34 finished with value: 0.2015365685999398 and parameters: {'subsample': 0.2692662272345522, 'dropout_rate': 0.7720700330888676, 'n_estimators': 96, 'learning_rate': 0.032157467810215834}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2061573289314405
Fold 2 IBS: 0.18308063611650024
Fold 3 IBS: 0.17645812014909326
Fold 4 IBS: 0.1976608025630094
Fold 5 IBS: 0.25304005480349206
[I 2024-04-16 04:06:54,488] Trial 35 finished with value: 0.2032793885127071 and parameters: {'subsample': 0.23406275629450798, 'dropout_rate': 0.5856891687807478, 'n_estimators': 167, 'learning_rate': 0.023048782790281344}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.1995176120322553
Fold 2 IBS: 0.1916289417043371
Fold 3 IBS: 0.17634370275909048
Fold 4 IBS: 0.20064388725831098
Fold 5 IBS: 0.23452454352588636
[I 2024-04-16 04:06:55,451] Trial 36 finished with value: 0.20053173745597602 and parameters: {'subsample': 0.3079529125404247, 'dropout_rate': 0.7451770945587517, 'n_estimators': 91, 'learning_rate': 0.02664320713072585}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20613254936180075
Fold 2 IBS: 0.21070580029601446
Fold 3 IBS: 0.19201164359217274
Fold 4 IBS: 0.21530311678503808
Fold 5 IBS: 0.2190529350806702
[I 2024-04-16 04:06:55,980] Trial 37 finished with value: 0.20864120902313923 and parameters: {'subsample': 0.4453495437188899, 'dropout_rate': 0.48858816459860266, 'n_estimators': 22, 'learning_rate': 0.028811820403570124}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.19866470699133482
Fold 2 IBS: 0.19656092487140125
Fold 3 IBS: 0.1822935200256659
Fold 4 IBS: 0.2097335127069102

Fold 5 IBS: 0.22465026642731892
[I 2024-04-16 04:06:56,964] Trial 38 finished with value: 0.2023805862045262 and parameters: {'subsample': 0.17017303600682596, 'dropout_rate': 0.6744028301161138, 'n_estimators': 84, 'learning_rate': 0.02105811333204098}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.2293570713772131
Fold 2 IBS: 0.21090831309405633
Fold 3 IBS: 0.1854937460956396
Fold 4 IBS: 0.2135188317245189
Fold 5 IBS: 0.3310658823973223
[I 2024-04-16 04:06:59,215] Trial 39 finished with value: 0.23406876893775003 and parameters: {'subsample': 0.3439557983328422, 'dropout_rate': 0.844167451106476, 'n_estimators': 194, 'learning_rate': 0.051973238153326454}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.21206377067603904
Fold 2 IBS: 0.1864274650720211
Fold 3 IBS: 0.17644966324602238
Fold 4 IBS: 0.19294957610953867
Fold 5 IBS: 0.2664281407354722
[I 2024-04-16 04:07:00,751] Trial 40 finished with value: 0.20686372316781867 and parameters: {'subsample': 0.548888469715097, 'dropout_rate': 0.27073406810212547, 'n_estimators': 125, 'learning_rate': 0.03592906349335382}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.19870888593455063
Fold 2 IBS: 0.19592332852462746
Fold 3 IBS: 0.1801814151183319
Fold 4 IBS: 0.20547482085306887
Fold 5 IBS: 0.22780394191799094
[I 2024-04-16 04:07:01,759] Trial 41 finished with value: 0.20161847846971398 and parameters: {'subsample': 0.25669644622473264, 'dropout_rate': 0.7637125910183031, 'n_estimators': 96, 'learning_rate': 0.01975292785105187}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20838776678662158
Fold 2 IBS: 0.18458876507607672
Fold 3 IBS: 0.17622427787792194
Fold 4 IBS: 0.19577750517111836
Fold 5 IBS: 0.2592881055896767
[I 2024-04-16 04:07:03,654] Trial 42 finished with value: 0.20485328410028308 and parameters: {'subsample': 0.318913417614635, 'dropout_rate': 0.6954623000860509, 'n_estimators': 155, 'learning_rate': 0.026680268344183765}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20581884982167936
Fold 2 IBS: 0.21114132843751918
Fold 3 IBS: 0.19204077392894559
Fold 4 IBS: 0.21581842461339115
Fold 5 IBS: 0.2194124220515187
[I 2024-04-16 04:07:04,203] Trial 43 finished with value: 0.2088463597706108 and parameters: {'subsample': 0.27766830774246254, 'dropout_rate': 0.7378843308551086, 'n_estimators': 21, 'learning_rate': 0.03236373140691688}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.211373898868855
Fold 2 IBS: 0.18197417827746332
Fold 3 IBS: 0.1795094750790974
Fold 4 IBS: 0.20080705853626143
Fold 5 IBS: 0.26049311453387325
[I 2024-04-16 04:07:05,741] Trial 44 finished with value: 0.20683154505911006 and parameters: {'subsample': 0.29218877081350936, 'dropout_rate': 0.12176369536773762, 'n_estimators': 111, 'learning_rate': 0.04450424844427492}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.2081058656945365
Fold 2 IBS: 0.18342757569088866
Fold 3 IBS: 0.1803744362520886
Fold 4 IBS: 0.20369940084704236
Fold 5 IBS: 0.2529963370999858
[I 2024-04-16 04:07:06,694] Trial 45 finished with value: 0.2057207231169084 and parameters: {'subsample': 0.1595465697102985, 'dropout_rate': 0.810409547267725, 'n_estimators': 75, 'learning_rate': 0.05514452912306929}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.21244834619002742
Fold 2 IBS: 0.22002682487467506
Fold 3 IBS: 0.20230908770197017
Fold 4 IBS: 0.22323550260132452
Fold 5 IBS: 0.21808679037848674
[I 2024-04-16 04:07:07,176] Trial 46 finished with value: 0.21522131034929676 and parameters: {'subsample': 0.46900532967733044, 'dropout_rate': 0.6411889920335619, 'n_estimators': 3, 'learning_rate': 0.03359936538613975}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.1989674980171421
Fold 2 IBS: 0.19596922449831902
Fold 3 IBS: 0.17917972111143207
Fold 4 IBS: 0.20356056552271987
Fold 5 IBS: 0.22777485709313988
[I 2024-04-16 04:07:09,960] Trial 47 finished with value: 0.20109037324855059 and parameters: {'subsample': 0.3543985160964519, 'dropout_rate': 0.8704597969866263, 'n_estimators': 221, 'learning_rate': 0.008209618821055878}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.1988087509281216
Fold 2 IBS: 0.194809116140053
Fold 3 IBS: 0.1783178863545788
Fold 4 IBS: 0.20300899074823334
Fold 5 IBS: 0.22939290034831902
[I 2024-04-16 04:07:12,719] Trial 48 finished with value: 0.20086752890386114 and parameters: {'subsample': 0.34997900922070224, 'dropout_rate': 0.8583767544982763, 'n_estimators': 221, 'learning_rate': 0.008866449400387288}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20026714131029694
Fold 2 IBS: 0.19999508179627873
Fold 3 IBS: 0.18245881898731398
Fold 4 IBS: 0.20712070721836112
Fold 5 IBS: 0.22383992788618978
[I 2024-04-16 04:07:16,680] Trial 49 finished with value: 0.2027363354396881 and parameters: {'subsample': 0.360958249405207, 'dropout_rate': 0.8740409706839273, 'n_estimators': 272, 'learning_rate': 0.00524351186486742}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.1990464452126766
Fold 2 IBS: 0.19231535356119261
Fold 3 IBS: 0.17640198836658966
Fold 4 IBS: 0.20083441062240975
Fold 5 IBS: 0.23260537265893996
[I 2024-04-16 04:07:19,943] Trial 50 finished with value: 0.2002407140843617 and parameters: {'subsample': 0.4373334297322835, 'dropout_rate': 0.9260233690194004, 'n_estimators': 226, 'learning_rate': 0.009590101642146711}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.201300346521472
Fold 2 IBS: 0.20187803014855335
Fold 3 IBS: 0.1844251452029284
Fold 4 IBS: 0.20932018063125366
Fold 5 IBS: 0.2225022640449257
[I 2024-04-16 04:07:22,883] Trial 51 finished with value: 0.20388519330982663 and parameters: {'subsample': 0.43083736341534906, 'dropout_rate': 0.9404007957184433, 'n_estimators': 228, 'learning_rate': 0.005306046137852891}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20199374520220834
Fold 2 IBS: 0.18747252012943172
Fold 3 IBS: 0.17497519063844968
Fold 4 IBS: 0.19634461287889246
Fold 5 IBS: 0.24449705546360098
[I 2024-04-16 04:07:26,364] Trial 52 finished with value: 0.20105662486251666 and parameters: {'subsample': 0.3681476442942809, 'dropout_rate': 0.8660885032854598, 'n_estimators': 284, 'learning_rate': 0.010879916649294472}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20544662432868555
Fold 2 IBS: 0.18672034859852907
Fold 3 IBS: 0.17472120028561494
Fold 4 IBS: 0.19316436687777605
Fold 5 IBS: 0.2517371644954932
[I 2024-04-16 04:07:31,232] Trial 53 finished with value: 0.20235794091721973 and parameters: {'subsample': 0.48900242562477936, 'dropout_rate': 0.8299583658948217, 'n_estimators': 335, 'learning_rate': 0.010670184521637897}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21094194920642484
Fold 2 IBS: 0.18559765775758102
Fold 3 IBS: 0.17643861381451179
Fold 4 IBS: 0.19409856772983944
Fold 5 IBS: 0.26140960735797286
[I 2024-04-16 04:07:34,565] Trial 54 finished with value: 0.205697279173266 and parameters: {'subsample': 0.37369693855918124, 'dropout_rate': 0.944656111823258, 'n_estimators': 271, 'learning_rate': 0.015564937079776901}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21979660617383143
Fold 2 IBS: 0.1892262703859355
Fold 3 IBS: 0.18156404701635165
Fold 4 IBS: 0.19336168043363092
Fold 5 IBS: 0.28460738586913
[I 2024-04-16 04:07:39,119] Trial 55 finished with value: 0.2137111979757759 and parameters: {'subsample': 0.44271112931064716, 'dropout_rate': 0.7139725161317707, 'n_estimators': 291, 'learning_rate': 0.019874419509118953}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.209631736413387
Fold 2 IBS: 0.2155994032197187
Fold 3 IBS: 0.19791952673985064
Fold 4 IBS: 0.21979375188696387
Fold 5 IBS: 0.2182561011891302
[I 2024-04-16 04:07:43,699] Trial 56 finished with value: 0.21224010388981007 and parameters: {'subsample': 0.5030867670027215, 'dropout_rate': 0.8693983003771366, 'n_estimators': 320, 'learning_rate': 0.0010380687366828949}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19885615519176145
Fold 2 IBS: 0.19483646447298053
Fold 3 IBS: 0.17849049434659467
Fold 4 IBS: 0.20302608352234905

Fold 5 IBS: 0.22884938440987548
[I 2024-04-16 04:07:46,837] Trial 57 finished with value: 0.20081171638871226 and parameters: {'subsample': 0.31114891339062667, 'dropout_rate': 0.6489378315882792, 'n_estimators': 251, 'learning_rate': 0.007801704420672669}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.2180531959388824
Fold 2 IBS: 0.1850434781595872
Fold 3 IBS: 0.18125157795710164
Fold 4 IBS: 0.1957099312923242
Fold 5 IBS: 0.2808496755196348
[I 2024-04-16 04:07:49,240] Trial 58 finished with value: 0.21218157177350605 and parameters: {'subsample': 0.3221818826721476, 'dropout_rate': 0.5833347466815137, 'n_estimators': 202, 'learning_rate': 0.027679523779857756}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21120995027458148
Fold 2 IBS: 0.1838676821243201
Fold 3 IBS: 0.17761827785583964
Fold 4 IBS: 0.1945128293118185
Fold 5 IBS: 0.2635788119779368
[I 2024-04-16 04:07:52,935] Trial 59 finished with value: 0.20615751030889928 and parameters: {'subsample': 0.2996242069065176, 'dropout_rate': 0.6192368181246879, 'n_estimators': 251, 'learning_rate': 0.017802575785705377}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19866191713016035
Fold 2 IBS: 0.19513258472618417
Fold 3 IBS: 0.17997492062652226
Fold 4 IBS: 0.2040192033824718
Fold 5 IBS: 0.22715154123325396
[I 2024-04-16 04:07:56,679] Trial 60 finished with value: 0.2009880334197185 and parameters: {'subsample': 0.22455927919482993, 'dropout_rate': 0.5527446724622991, 'n_estimators': 248, 'learning_rate': 0.007693689744162442}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19860339599320959
Fold 2 IBS: 0.19277322392050603
Fold 3 IBS: 0.17858572035004985
Fold 4 IBS: 0.20247218732304564
Fold 5 IBS: 0.22925764913311597
[I 2024-04-16 04:08:00,508] Trial 61 finished with value: 0.20033843534398538 and parameters: {'subsample': 0.21909136776287286, 'dropout_rate': 0.5515385173674032, 'n_estimators': 253, 'learning_rate': 0.008495962988587152}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19845171225113126
Fold 2 IBS: 0.1910629687358273
Fold 3 IBS: 0.17791413908896317
Fold 4 IBS: 0.20292503438373793
Fold 5 IBS: 0.2316698048652442
[I 2024-04-16 04:08:03,010] Trial 62 finished with value: 0.20040473186498073 and parameters: {'subsample': 0.21070703060386461, 'dropout_rate': 0.6557587421398771, 'n_estimators': 186, 'learning_rate': 0.012461426370993078}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19886591799393769
Fold 2 IBS: 0.19197092646344488
Fold 3 IBS: 0.17935593489849153
Fold 4 IBS: 0.20584723623654588
Fold 5 IBS: 0.23159112578512311
[I 2024-04-16 04:08:06,632] Trial 63 finished with value: 0.20152622827550865 and parameters: {'subsample': 0.20588679456621525, 'dropout_rate': 0.48690852553985364, 'n_estimators': 190, 'learning_rate': 0.011860651098482533}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.1997988675056321
Fold 2 IBS: 0.19969392477830095
Fold 3 IBS: 0.18393590118546424
Fold 4 IBS: 0.20782967802948005
Fold 5 IBS: 0.22354896016586287
[I 2024-04-16 04:08:09,512] Trial 64 finished with value: 0.20296146633294804 and parameters: {'subsample': 0.23342109443253445, 'dropout_rate': 0.6507886461152487, 'n_estimators': 207, 'learning_rate': 0.007198457227495094}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.2082544146951382
Fold 2 IBS: 0.1857987113249321
Fold 3 IBS: 0.1754379980373742
Fold 4 IBS: 0.1940319026887006
Fold 5 IBS: 0.25732089858426943
[I 2024-04-16 04:08:13,292] Trial 65 finished with value: 0.20416878506608294 and parameters: {'subsample': 0.40423854941963694, 'dropout_rate': 0.4090085146335245, 'n_estimators': 252, 'learning_rate': 0.015547726269956158}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21002693489768112
Fold 2 IBS: 0.18653203943460253
Fold 3 IBS: 0.17611975023561272
Fold 4 IBS: 0.1915913950630139
Fold 5 IBS: 0.26106692097622824
[I 2024-04-16 04:08:15,417] Trial 66 finished with value: 0.2050674081214277 and parameters: {'subsample': 0.5848429462742089, 'dropout_rate': 0.5270149291863772, 'n_estimators': 176, 'learning_rate': 0.023923265831128443}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20128392263131167
Fold 2 IBS: 0.20237394700693265
Fold 3 IBS: 0.18491496967992743
Fold 4 IBS: 0.20942084643772668
Fold 5 IBS: 0.22212580277712735
[I 2024-04-16 04:08:19,613] Trial 67 finished with value: 0.20402389770660517 and parameters: {'subsample': 0.31050638296582034, 'dropout_rate': 0.6020968540766496, 'n_estimators': 305, 'learning_rate': 0.004095470231808003}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20446398643719982
Fold 2 IBS: 0.18543322916493926
Fold 3 IBS: 0.17488583619135797
Fold 4 IBS: 0.1961917165416571
Fold 5 IBS: 0.2494043859166099
[I 2024-04-16 04:08:25,738] Trial 68 finished with value: 0.20207583085035283 and parameters: {'subsample': 0.33866334601953496, 'dropout_rate': 0.5565926972957085, 'n_estimators': 371, 'learning_rate': 0.009516752179130228}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20246155364149607
Fold 2 IBS: 0.18563046233601388
Fold 3 IBS: 0.17792793232286447
Fold 4 IBS: 0.20039623000573417
Fold 5 IBS: 0.24089417213184716
[I 2024-04-16 04:08:28,781] Trial 69 finished with value: 0.20146207008759118 and parameters: {'subsample': 0.18890607008448618, 'dropout_rate': 0.7137138014562743, 'n_estimators': 238, 'learning_rate': 0.013349658981664611}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20310494865610662
Fold 2 IBS: 0.20545803800118573
Fold 3 IBS: 0.18764680603194414
Fold 4 IBS: 0.2120973096098445
Fold 5 IBS: 0.2206903037650552
[I 2024-04-16 04:08:31,629] Trial 70 finished with value: 0.20579948121282726 and parameters: {'subsample': 0.5149426969908794, 'dropout_rate': 0.4381668991259586, 'n_estimators': 214, 'learning_rate': 0.00444869463746881}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21297285427598092
Fold 2 IBS: 0.1832700979976667
Fold 3 IBS: 0.17824155147371212
Fold 4 IBS: 0.19494420413284244
Fold 5 IBS: 0.2677645276420483
[I 2024-04-16 04:08:35,058] Trial 71 finished with value: 0.2074386471044501 and parameters: {'subsample': 0.2894984083435091, 'dropout_rate': 0.751682582749187, 'n_estimators': 258, 'learning_rate': 0.018200871475118667}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20528071766658593
Fold 2 IBS: 0.1833412991029227
Fold 3 IBS: 0.17617838681427514
Fold 4 IBS: 0.19789257395688972
Fold 5 IBS: 0.2514689070781784
[I 2024-04-16 04:08:36,850] Trial 72 finished with value: 0.2028323769237704 and parameters: {'subsample': 0.2331530305885307, 'dropout_rate': 0.6605710023067495, 'n_estimators': 165, 'learning_rate': 0.02267661283593704}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.1992303488209824
Fold 2 IBS: 0.1967593108012993
Fold 3 IBS: 0.1792460116248184
Fold 4 IBS: 0.2039880228332894
Fold 5 IBS: 0.2272034025077404
[I 2024-04-16 04:08:38,329] Trial 73 finished with value: 0.20128541931762597 and parameters: {'subsample': 0.4220664300553503, 'dropout_rate': 0.6937026327658418, 'n_estimators': 133, 'learning_rate': 0.013039457571678612}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20968711596124293
Fold 2 IBS: 0.21561820248459318
Fold 3 IBS: 0.19793941128748843
Fold 4 IBS: 0.21956205385981584
Fold 5 IBS: 0.21827354636977914
[I 2024-04-16 04:08:41,083] Trial 74 finished with value: 0.21221606599258394 and parameters: {'subsample': 0.7948212261000067, 'dropout_rate': 0.7310121903861898, 'n_estimators': 221, 'learning_rate': 0.0014747019516563936}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.22515589313174209
Fold 2 IBS: 0.19522170174518336
Fold 3 IBS: 0.18464502393183305
Fold 4 IBS: 0.1978030335133637
Fold 5 IBS: 0.3001559917690526
[I 2024-04-16 04:08:43,174] Trial 75 finished with value: 0.22059632881823496 and parameters: {'subsample': 0.4630852672348673, 'dropout_rate': 0.8091944194128441, 'n_estimators': 185, 'learning_rate': 0.03845404879047214}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.22454456785401858
Fold 2 IBS: 0.18494220070116402
Fold 3 IBS: 0.1848064201941937
Fold 4 IBS: 0.20249002624406767

Fold 5 IBS: 0.29644781879545157
[I 2024-04-16 04:08:46,278] Trial 76 finished with value: 0.2186462067577791 and parameters: {'subsample': 0.2534219458429501, 'dropout_rate': 0.619685631002236, 'n_estimators': 236, 'learning_rate': 0.029611588065970945}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19966889046600855
Fold 2 IBS: 0.19925346497055635
Fold 3 IBS: 0.181090164247083
Fold 4 IBS: 0.20616955499619105
Fold 5 IBS: 0.224445533329019
[I 2024-04-16 04:08:47,521] Trial 77 finished with value: 0.20212552160177158 and parameters: {'subsample': 0.3885243355394725, 'dropout_rate': 0.7696332658571577, 'n_estimators': 61, 'learning_rate': 0.025174387951611213}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19976721983416995
Fold 2 IBS: 0.20024051454876698
Fold 3 IBS: 0.18479863559918963
Fold 4 IBS: 0.21154594555854472
Fold 5 IBS: 0.22205446508890664
[I 2024-04-16 04:08:49,001] Trial 78 finished with value: 0.2036813561259156 and parameters: {'subsample': 0.16322492887934456, 'dropout_rate': 0.51368023316918, 'n_estimators': 83, 'learning_rate': 0.017359823317159035}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.23199090818454793
Fold 2 IBS: 0.22970723570160334
Fold 3 IBS: 0.18249880027439583
Fold 4 IBS: 0.23346772045414727
Fold 5 IBS: 0.3528463300375872
[I 2024-04-16 04:08:53,558] Trial 79 finished with value: 0.24610219893045632 and parameters: {'subsample': 0.27953959952764496, 'dropout_rate': 0.5731559961911988, 'n_estimators': 278, 'learning_rate': 0.04873034355813268}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19879204665910194
Fold 2 IBS: 0.19274706654808196
Fold 3 IBS: 0.17647473708199682
Fold 4 IBS: 0.20172059201153625
Fold 5 IBS: 0.23115769966876726
[I 2024-04-16 04:08:58,205] Trial 80 finished with value: 0.20017842839389685 and parameters: {'subsample': 0.33475886913475816, 'dropout_rate': 0.6955063105380811, 'n_estimators': 307, 'learning_rate': 0.007039353779474462}. Best is trial 80 with value: 0.20017842839389685.
Fold 1 IBS: 0.20000656844881579
Fold 2 IBS: 0.18882098473332873
Fold 3 IBS: 0.1747862739972533
Fold 4 IBS: 0.19910227285014737
Fold 5 IBS: 0.23763167546945851
[I 2024-04-16 04:09:03,639] Trial 81 finished with value: 0.20006955509980076 and parameters: {'subsample': 0.3397359179742326, 'dropout_rate': 0.6833175045217887, 'n_estimators': 367, 'learning_rate': 0.007340195313518955}. Best is trial 81 with value: 0.20006955509980076.
Fold 1 IBS: 0.1991996730371552
Fold 2 IBS: 0.19061258530577402
Fold 3 IBS: 0.17588783289209417
Fold 4 IBS: 0.20030633328559347
Fold 5 IBS: 0.23413900412847238
[I 2024-04-16 04:09:09,965] Trial 82 finished with value: 0.20002908572981784 and parameters: {'subsample': 0.34792984378915526, 'dropout_rate': 0.6670685322563024, 'n_estimators': 365, 'learning_rate': 0.00664378402753306}. Best is trial 82 with value: 0.20002908572981784.
Fold 1 IBS: 0.19903180888621802
Fold 2 IBS: 0.19224735762606934
Fold 3 IBS: 0.175915311830189
Fold 4 IBS: 0.20038950021083846
Fold 5 IBS: 0.23259208014937127
[I 2024-04-16 04:09:16,403] Trial 83 finished with value: 0.2000352117405372 and parameters: {'subsample': 0.38290474521978124, 'dropout_rate': 0.677619926146453, 'n_estimators': 376, 'learning_rate': 0.005997543857983899}. Best is trial 82 with value: 0.20002908572981784.
Fold 1 IBS: 0.200912746038692
Fold 2 IBS: 0.20129190888869186
Fold 3 IBS: 0.18364066650842703
Fold 4 IBS: 0.20945156945779617
Fold 5 IBS: 0.22263628735118965
[I 2024-04-16 04:09:22,811] Trial 84 finished with value: 0.20358663564895935 and parameters: {'subsample': 0.3373262336993141, 'dropout_rate': 0.7019671594899369, 'n_estimators': 384, 'learning_rate': 0.0034028119865210033}. Best is trial 82 with value: 0.20002908572981784.
Fold 1 IBS: 0.19980528408099282
Fold 2 IBS: 0.1900963377136432
Fold 3 IBS: 0.174782016245765
Fold 4 IBS: 0.19822465557189303
Fold 5 IBS: 0.23708353535955742
[I 2024-04-16 04:09:30,522] Trial 85 finished with value: 0.1999983657943703 and parameters: {'subsample': 0.3809720890358673, 'dropout_rate': 0.5996805030994624, 'n_estimators': 409, 'learning_rate': 0.006325974352143995}. Best is trial 85 with value: 0.1999983657943703.
Fold 1 IBS: 0.20010642753256813
Fold 2 IBS: 0.18965812186234568
Fold 3 IBS: 0.17464067277103718
Fold 4 IBS: 0.19732540998074313
Fold 5 IBS: 0.2382215492123802
[I 2024-04-16 04:09:37,344] Trial 86 finished with value: 0.19999043627181487 and parameters: {'subsample': 0.3947888012341751, 'dropout_rate': 0.6736276479790769, 'n_estimators': 413, 'learning_rate': 0.006463099914676254}. Best is trial 86 with value: 0.19999043627181487.
Fold 1 IBS: 0.19935362908290935
Fold 2 IBS: 0.191056131187276
Fold 3 IBS: 0.17520616290332836
Fold 4 IBS: 0.19909290195001983
Fold 5 IBS: 0.2349851663856012
[I 2024-04-16 04:09:44,615] Trial 87 finished with value: 0.19993879830182695 and parameters: {'subsample': 0.38280123235103686, 'dropout_rate': 0.6037924030750854, 'n_estimators': 413, 'learning_rate': 0.0058831239400112265}. Best is trial 87 with value: 0.19993879830182695.
Fold 1 IBS: 0.19943731520674807
Fold 2 IBS: 0.19085721976663916
Fold 3 IBS: 0.17514246934826022
Fold 4 IBS: 0.19885524159426432
Fold 5 IBS: 0.23542129729302227
[I 2024-04-16 04:09:51,408] Trial 88 finished with value: 0.19994270864178681 and parameters: {'subsample': 0.38006143446524837, 'dropout_rate': 0.6085571552649838, 'n_estimators': 426, 'learning_rate': 0.005779184446717517}. Best is trial 87 with value: 0.19993879830182695.
Fold 1 IBS: 0.20399145880029984
Fold 2 IBS: 0.20702972794962157
Fold 3 IBS: 0.18864521430146713
Fold 4 IBS: 0.21294296667651075
Fold 5 IBS: 0.22011985649014484
[I 2024-04-16 04:09:59,179] Trial 89 finished with value: 0.20654584484360883 and parameters: {'subsample': 0.4039375185246939, 'dropout_rate': 0.603741761651037, 'n_estimators': 433, 'learning_rate': 0.002031391442837707}. Best is trial 87 with value: 0.19993879830182695.
Fold 1 IBS: 0.19915549952349776
Fold 2 IBS: 0.19171515586852814
Fold 3 IBS: 0.17555885162450585
Fold 4 IBS: 0.19975700085514286
Fold 5 IBS: 0.23370377178415982
[I 2024-04-16 04:10:05,994] Trial 90 finished with value: 0.19997805593116685 and parameters: {'subsample': 0.3799243953916448, 'dropout_rate': 0.6289350685014651, 'n_estimators': 409, 'learning_rate': 0.005696842141433989}. Best is trial 87 with value: 0.19993879830182695.
Fold 1 IBS: 0.2004685818733569
Fold 2 IBS: 0.18894978650603056
Fold 3 IBS: 0.17485562602441562
Fold 4 IBS: 0.19773296941218846
Fold 5 IBS: 0.23972172328515629
[I 2024-04-16 04:10:12,133] Trial 91 finished with value: 0.2003457374202296 and parameters: {'subsample': 0.37661407589785384, 'dropout_rate': 0.6779057045608204, 'n_estimators': 404, 'learning_rate': 0.006877004414566871}. Best is trial 87 with value: 0.19993879830182695.
Fold 1 IBS: 0.1997068700002599
Fold 2 IBS: 0.19087089687280429
Fold 3 IBS: 0.17482813511422507
Fold 4 IBS: 0.19811942511936104
Fold 5 IBS: 0.23596362759762746
[I 2024-04-16 04:10:19,670] Trial 92 finished with value: 0.19989779094085552 and parameters: {'subsample': 0.4508909392377546, 'dropout_rate': 0.630911383430701, 'n_estimators': 457, 'learning_rate': 0.005461916474307776}. Best is trial 92 with value: 0.19989779094085552.
Fold 1 IBS: 0.20039449087424205
Fold 2 IBS: 0.18966762693961356
Fold 3 IBS: 0.17443478597871914
Fold 4 IBS: 0.19687682164711615
Fold 5 IBS: 0.23831821665926145
[I 2024-04-16 04:10:27,059] Trial 93 finished with value: 0.19993838841979045 and parameters: {'subsample': 0.4627070216098863, 'dropout_rate': 0.6298525384386744, 'n_estimators': 456, 'learning_rate': 0.005887636043107294}. Best is trial 92 with value: 0.19989779094085552.
Fold 1 IBS: 0.2006392217952902
Fold 2 IBS: 0.1894394479399196
Fold 3 IBS: 0.17449474382004915
Fold 4 IBS: 0.19626808057350037
Fold 5 IBS: 0.23937626794619857
[I 2024-04-16 04:10:34,774] Trial 94 finished with value: 0.20004355241499158 and parameters: {'subsample': 0.47116554953139117, 'dropout_rate': 0.6281368369287272, 'n_estimators': 474, 'learning_rate': 0.005751546745815685}. Best is trial 92 with value: 0.19989779094085552.
Fold 1 IBS: 0.19892612443085128
Fold 2 IBS: 0.19430773864381432
Fold 3 IBS: 0.17723806902580683

Fold 4 IBS: 0.20119576053683905
Fold 5 IBS: 0.22983373825943978
[I 2024-04-16 04:10:42,992] Trial 95 finished with value: 0.20030028617935028 and parameters: {'subsample': 0.4757995705798828, 'dropout_rate': 0.6231094767303963, 'n_estimators': 479, 'learning_rate': 0.004160712641332346}. Best is trial 92 with value: 0.19989779094085552.
Fold 1 IBS: 0.19933033684879545
Fold 2 IBS: 0.19175290459754746
Fold 3 IBS: 0.17523641758102454
Fold 4 IBS: 0.19898064100110172
Fold 5 IBS: 0.23416739031725986
[I 2024-04-16 04:10:51,266] Trial 96 finished with value: 0.19989353806914578 and parameters: {'subsample': 0.4540175560315793, 'dropout_rate': 0.5727605083055514, 'n_estimators': 452, 'learning_rate': 0.005218799046830834}. Best is trial 96 with value: 0.19989353806914578.
Fold 1 IBS: 0.2016948797357464
Fold 2 IBS: 0.20332294880280635
Fold 3 IBS: 0.18477449173738422
Fold 4 IBS: 0.20962380699873429
Fold 5 IBS: 0.2218130841298247
[I 2024-04-16 04:10:59,566] Trial 97 finished with value: 0.2042458422808992 and parameters: {'subsample': 0.45556954055644505, 'dropout_rate': 0.572058248393014, 'n_estimators': 452, 'learning_rate': 0.0025694811346109597}. Best is trial 96 with value: 0.19989353806914578.
Fold 1 IBS: 0.21264121801154584
Fold 2 IBS: 0.18659428366337522
Fold 3 IBS: 0.17792634064575477
Fold 4 IBS: 0.19224180706549948
Fold 5 IBS: 0.26764997585475486
[I 2024-04-16 04:11:07,758] Trial 98 finished with value: 0.20741072504818603 and parameters: {'subsample': 0.42229204345434884, 'dropout_rate': 0.5978829943651781, 'n_estimators': 449, 'learning_rate': 0.010334843437931361}. Best is trial 96 with value: 0.19989353806914578.
Fold 1 IBS: 0.22621807999171556
Fold 2 IBS: 0.19919282512831127
Fold 3 IBS: 0.18489802344899234
Fold 4 IBS: 0.19777784684616304
Fold 5 IBS: 0.3048676521988783
[I 2024-04-16 04:11:16,827] Trial 99 finished with value: 0.22259088552281212 and parameters: {'subsample': 0.5139100971928297, 'dropout_rate': 0.5128032823691606, 'n_estimators': 498, 'learning_rate': 0.014923568640818837}. Best is trial 96 with value: 0.19989353806914578.


* Best trial for IBS:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.19989353806914578], datetime_start=datetime.datetime(2024, 4, 16, 4, 10, 42, 997607), datetime_complete=datetime.datetime(2024, 4, 16, 4, 10, 51, 265909), params={'subsample': 0.4540175560315793, 'dropout_rate': 0.5727605083055514, 'n_estimators': 452, 'learning_rate': 0.005218799046830834}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=96, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.4540175560315793, 'dropout_rate': 0.5727605083055514, 'n_estimators': 452, 'learning_rate': 0.005218799046830834}


* Best Score for IBS:
 0.19989353806914578

In [76]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [77]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.688
train_ibs:  0.2

#### Test

In [78]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [79]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7166562602631428,
                                              learning_rate=0.07736008213803257,
                                              n_estimators=227,
                                              random_state=123,
                                              subsample=0.3054811831292578)

C-index score: 0.634

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5727605083055514,
                                              learning_rate=0.005218799046830834,
                                              n_estimators=452,
                                              random_state=123,
                                              subsample=0.4540175560315793)

IBS: 0.206

In [80]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [81]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.847   1.5
ExtraSurvivalTrees               0.847   1.5
ComponentwiseGradientBoosting    0.688   3.0
CoxRidge                         0.675   4.0
GradientBoosting                 0.661   5.0
CoxElastic                       0.658   6.0
CoxLasso                         0.657   7.0
CoxPH                            0.656   8.0

In [82]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.200   1.0
ExtraSurvivalTrees             0.201   2.0
Randomsurvivalforest           0.203   3.0
CoxPH                          0.206   5.0
CoxLasso                       0.206   5.0
CoxElastic                     0.206   5.0
GradientBoosting               0.216   7.0
CoxRidge                       0.217   8.0

In [83]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.634   1.0
ExtraSurvivalTrees               0.618   2.0
GradientBoosting                 0.617   3.0
CoxRidge                         0.616   4.0
Randomsurvivalforest             0.613   5.0
CoxPH                            0.591   6.0
CoxLasso                         0.590   7.5
CoxElastic                       0.590   7.5

In [84]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.206   1.0
ExtraSurvivalTrees             0.212   2.0
Randomsurvivalforest           0.219   3.0
CoxRidge                       0.221   4.5
GradientBoosting               0.221   4.5
CoxLasso                       0.237   6.5
CoxElastic                     0.237   6.5
CoxPH                          0.238   8.0

In [85]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/os/yeojohnson/plsr/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_os_yeojohnson_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [86]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-16