In [1]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
    
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import PowerTransformer

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.00 0.95      0.08
SUVpeak                   0.29 0.59      0.76
TLG                       0.22 0.64      0.65
age                       1.60 0.21      2.28
cavum_oris                0.00 1.00      0.01
charlson                  0.07 0.79      0.34
female                    0.17 0.68      0.56
histgrade_high            1.26 0.26      1.93
hpv_related               4.31 0.04      4.72
hypopharynx               0.00 0.99      0.01
larynx                    0.00 0.98      0.02
oropharynx                0.00 0.99      0.02
pack_years                0.71 0.40      1.32
uicc8_III-IV              0.45 0.50      0.99

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.02 0.88      0.18
SUVpeak                   0.56 0.46      1.13
TLG                       0.06 0.81      0.30
age                       1.58 0.21      2.26
cavum_oris                0.08 0.77      0.37
charlson                  0.03 0.86      0.22
female                    0.35 0.56      0.85
histgrade_high            0.95 0.33      1.60
hpv_related               3.02 0.08      3.60
hypopharynx               0.10 0.75      0.41
larynx                    1.46 0.23      2.14
oropharynx                0.96 0.33      1.61
pack_years                0.39 0.53      0.92
uicc8_III-IV              0.08 0.78      0.36

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [18]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Yeo-Johnson Transformation

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
pt = PowerTransformer(method='yeo-johnson')
X_numeric_std = pt.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [28]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [29]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [30]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [31]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.785036,1,0,1,0,0,1,0.0,0,-1.533345,0.0,0.750782,0.080033,0.343545
1,-0.746998,0,0,0,0,1,0,0.0,1,0.397233,0.0,-1.213660,-1.722060,-1.657833
2,-0.175256,0,1,0,0,0,1,0.0,1,0.830437,1.0,-0.474112,0.735716,0.318631
3,1.371631,0,0,0,0,1,0,0.0,1,0.727938,0.0,-1.992620,-1.291020,-1.835650
4,0.987008,0,0,0,0,1,0,0.0,1,1.144253,0.0,-1.106304,-0.816679,-1.003396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.007949,0,0,1,0,0,1,1.0,0,-1.533345,0.0,-0.158214,-0.822461,-0.611074
135,1.111443,0,0,1,0,0,1,1.0,0,-1.533345,1.0,-0.632361,1.008070,0.474941
136,-0.370651,0,0,1,0,0,1,1.0,1,0.786825,0.0,0.658564,-0.170908,0.133612
137,0.696583,0,0,1,0,0,1,1.0,1,1.554125,1.0,-0.551725,0.574668,0.197985
138,0.169401,0,0,1,0,0,1,1.0,0,-1.110899,1.0,0.527960,0.086991,0.270290

In [32]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [33]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.688798,0,0,1,0,0,1,1,1,-1.533345,0,0.893634,1.188930,1.218887
1,-0.688798,0,0,1,0,0,0,0,0,0.104884,1,-0.254678,-0.307894,-0.335276
2,-0.688798,0,0,1,0,0,0,0,1,-0.713198,1,0.595996,0.059450,0.228548
3,0.081262,1,0,0,0,1,1,0,1,0.940197,1,-0.296877,0.076321,-0.145668
4,1.273609,0,0,1,0,0,1,1,1,1.285347,0,-0.058378,0.786849,0.519421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.738387,1,0,0,0,1,0,0,0,1.192311,1,2.645651,-0.219083,0.751363
95,0.342484,0,0,0,0,1,0,0,1,3.094727,1,0.526028,-0.033134,0.168333
96,0.342484,0,0,1,0,0,1,1,1,-1.533345,1,-0.230255,0.867254,0.481447
97,-0.815082,0,0,1,0,0,1,1,0,-1.533345,0,0.706707,0.336049,0.486335
98,0.211597,0,0,0,1,0,1,0,0,0.801315,1,0.064287,-0.873431,-0.544074

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [46]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:30:45,415] A new study created in memory with name: no-name-564c5fa8-92cb-4aa4-8bcd-58b5a937a3b4

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5465116279069767
Fold 3 C-index: 0.7106382978723405

[I 2024-04-13 17:30:46,040] A new study created in memory with name: no-name-5058bd04-2023-4ca5-84af-c521f7950c6c

Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 17:30:46,017] Trial 0 finished with value: 0.6185753302429834 and parameters: {}. Best is trial 0 with value: 0.6185753302429834.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6185753302429834], datetime_start=datetime.datetime(2024, 4, 13, 17, 30, 45, 449124), datetime_complete=datetime.datetime(2024, 4, 13, 17, 30, 46, 17128), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6185753302429834

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2535303072491698
Fold 2 IBS: 0.2701123265297601
Fold 3 IBS: 0.21505701313669706
Fold 4 IBS: 0.27439723254313414
Fold 5 IBS: 0.22842205561435375
[I 2024-04-13 17:30:46,819] Trial 0 finished with value: 0.24830378701462297 and parameters: {}. Best is trial 0 with value: 0.24830378701462297.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.24830378701462297], datetime_start=datetime.datetime(2024, 4, 13, 17, 30, 46, 77347), datetime_complete=datetime.datetime(2024, 4, 13, 17, 30, 46, 819440), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.24830378701462297

In [47]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.619
train_ibs:  0.248

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [52]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:30:59,275] A new study created in memory with name: no-name-8d1fb99d-8377-497c-8afd-0419723d3e1b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.5058139534883721
Fold 3 C-index: 0.5617021276595745

[I 2024-04-13 17:30:59,738] A new study created in memory with name: no-name-aaaa2556-736c-42bc-8684-ad6d045c167a

Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:30:59,719] Trial 0 finished with value: 0.5600203770775404 and parameters: {}. Best is trial 0 with value: 0.5600203770775404.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5600203770775404], datetime_start=datetime.datetime(2024, 4, 13, 17, 30, 59, 320413), datetime_complete=datetime.datetime(2024, 4, 13, 17, 30, 59, 718793), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5600203770775404

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709728729422
Fold 2 IBS: 0.23203988447801246
Fold 3 IBS: 0.2289818653708319
Fold 4 IBS: 0.24197477735363535
Fold 5 IBS: 0.2293955872908494
[I 2024-04-13 17:31:00,372] Trial 0 finished with value: 0.23592784235612468 and parameters: {}. Best is trial 0 with value: 0.23592784235612468.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784235612468], datetime_start=datetime.datetime(2024, 4, 13, 17, 30, 59, 793254), datetime_complete=datetime.datetime(2024, 4, 13, 17, 31, 0, 372562), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784235612468

In [55]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.56
train_ibs:  0.236

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [58]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.533

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [59]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:31:02,246] A new study created in memory with name: no-name-84346c83-93f3-4e8b-b106-143a424c44dc

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901

[I 2024-04-13 17:31:03,250] A new study created in memory with name: no-name-98241ac8-a62e-42eb-bd88-77d412b11dc3

Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:03,239] Trial 0 finished with value: 0.6303750707301188 and parameters: {}. Best is trial 0 with value: 0.6303750707301188.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6303750707301188], datetime_start=datetime.datetime(2024, 4, 13, 17, 31, 2, 334122), datetime_complete=datetime.datetime(2024, 4, 13, 17, 31, 3, 239222), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6303750707301188

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.25088041795120963
Fold 2 IBS: 0.2581733640424138
Fold 3 IBS: 0.2109028541228368
Fold 4 IBS: 0.2706797108128965
Fold 5 IBS: 0.22682720432557557
[I 2024-04-13 17:31:04,440] Trial 0 finished with value: 0.24349271025098645 and parameters: {}. Best is trial 0 with value: 0.24349271025098645.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.24349271025098645], datetime_start=datetime.datetime(2024, 4, 13, 17, 31, 3, 303823), datetime_complete=datetime.datetime(2024, 4, 13, 17, 31, 4, 439958), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.24349271025098645

In [61]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [62]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.63
train_ibs:  0.243

#### Test

In [63]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [64]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.571

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.279

In [65]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [66]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:31:06,475] A new study created in memory with name: no-name-037b0e20-3fce-494d-8881-cd3d01b01d63

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:07,348] Trial 0 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6288246831332196.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:08,449] Trial 1 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6288246831332196.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:09,406] Trial 2 finished with value: 0.6167875603066961 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6288246831332196.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:10,344] Trial 3 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6288246831332196.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:11,257] Trial 4 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6288246831332196.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:12,362] Trial 5 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6288246831332196.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:13,282] Trial 6 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:14,422] Trial 7 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:15,342] Trial 8 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:16,420] Trial 9 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:17,346] Trial 10 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:18,395] Trial 11 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:19,470] Trial 12 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:20,447] Trial 13 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:31:21,278] Trial 14 finished with value: 0.5695497646913756 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:23,168] Trial 15 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:25,405] Trial 16 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:27,061] Trial 17 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:28,951] Trial 18 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:30,427] Trial 19 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:31,752] Trial 20 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:33,355] Trial 21 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:34,775] Trial 22 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9952149413953396}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:36,138] Trial 23 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8898693182098678}. Best is trial 6 with value: 0.6303750707301188.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:37,508] Trial 24 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:38,898] Trial 25 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9368557715647121}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 17:31:39,655] Trial 26 finished with value: 0.5618472891287848 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:41,350] Trial 27 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.6022588122254688}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:42,856] Trial 28 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.6499747968454208}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:44,017] Trial 29 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9010792166439672}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:45,125] Trial 30 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8107108448948633}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:46,051] Trial 31 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9790160904460925}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:47,320] Trial 32 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9889509715055751}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:48,532] Trial 33 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9033942188713268}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:49,475] Trial 34 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9969906676119189}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:50,669] Trial 35 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9145273991086058}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:51,886] Trial 36 finished with value: 0.6167875603066961 and parameters: {'l1_ratio': 0.23789482035414378}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:53,050] Trial 37 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.7342815000174964}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:54,187] Trial 38 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8450450825036032}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:55,949] Trial 39 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:57,321] Trial 40 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.6762726602177129}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:58,387] Trial 41 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9440922341009589}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:31:59,372] Trial 42 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9508021678872735}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:00,555] Trial 43 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8119687552544277}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:01,621] Trial 44 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9305771147376857}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:02,914] Trial 45 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8746070404800059}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:04,148] Trial 46 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.4933969994831382}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:05,621] Trial 47 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9991045282580079}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008

Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:06,618] Trial 48 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:07,583] Trial 49 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8386679916089912}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:08,478] Trial 50 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.945704027694845}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:09,382] Trial 51 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.947113067248926}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:10,376] Trial 52 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8871531144268382}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:11,462] Trial 53 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9647303296134437}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:12,611] Trial 54 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9101963565788189}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:13,560] Trial 55 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8584736152002521}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:14,491] Trial 56 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9583038567719465}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:15,497] Trial 57 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9088458560426897}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:16,856] Trial 58 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.5410039830059447}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:17,858] Trial 59 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.7776014045307951}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:18,909] Trial 60 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8320809461721039}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:19,845] Trial 61 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.995042831172216}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:20,749] Trial 62 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9833336524256188}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:21,666] Trial 63 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9260812672003349}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:22,538] Trial 64 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9651321290795338}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:23,520] Trial 65 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8891583365337647}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:24,504] Trial 66 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9944626215764547}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:25,693] Trial 67 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.44627959226748903}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:26,918] Trial 68 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8787453958599145}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:28,210] Trial 69 finished with value: 0.5849090231649146 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:29,933] Trial 70 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.926199751086326}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:31,347] Trial 71 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9583211281444385}. Best is trial 6 with value: 0.6303750707301188.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:33,121] Trial 72 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9675780206021779}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:34,466] Trial 73 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9201870333114552}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:35,860] Trial 74 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9984463773526076}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:37,415] Trial 75 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9354982366369866}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:39,028] Trial 76 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8824734629144222}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:40,522] Trial 77 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8236759033518168}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:42,006] Trial 78 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9749829000406383}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:43,548] Trial 79 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.7120921418578845}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:45,464] Trial 80 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8582408686713943}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:46,579] Trial 81 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.941366388391376}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:47,483] Trial 82 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9709436318882778}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:48,423] Trial 83 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9046618858226455}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:49,405] Trial 84 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9667479326181698}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:50,634] Trial 85 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.33218847491866843}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:51,613] Trial 86 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9333679653567835}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:52,764] Trial 87 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9042332524858938}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:53,891] Trial 88 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.6259950488276012}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:55,323] Trial 89 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9793736278479597}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:56,552] Trial 90 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9983756146520648}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:57,673] Trial 91 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9498045734053079}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:58,675] Trial 92 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.975498238789646}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:32:59,787] Trial 93 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.9185266594488194}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:33:00,871] Trial 94 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8637568625677183}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:33:01,913] Trial 95 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9442153502210426}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008

Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:33:02,902] Trial 96 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9981810712843759}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5542635658914729
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:33:03,803] Trial 97 finished with value: 0.6288246831332196 and parameters: {'l1_ratio': 0.8890545167361409}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:33:04,791] Trial 98 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9774989882235288}. Best is trial 6 with value: 0.6303750707301188.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6768060836501901

[I 2024-04-13 17:33:05,731] A new study created in memory with name: no-name-ee26d034-9e5a-4ce5-a51c-4f714865d7c2

Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 17:33:05,720] Trial 99 finished with value: 0.6303750707301188 and parameters: {'l1_ratio': 0.9520347514443079}. Best is trial 6 with value: 0.6303750707301188.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.6303750707301188], datetime_start=datetime.datetime(2024, 4, 13, 17, 31, 12, 373772), datetime_complete=datetime.datetime(2024, 4, 13, 17, 31, 13, 282120), params={'l1_ratio': 0.980766121964777}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.6303750707301188

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2525836928556447
Fold 2 IBS: 0.2664404398563772
Fold 3 IBS: 0.21053233502960458
Fold 4 IBS: 0.2706211145594758
Fold 5 IBS: 0.22676170219108188
[I 2024-04-13 17:33:07,130] Trial 0 finished with value: 0.24538785689843684 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.24538785689843684.
Fold 1 IBS: 0.25253920525266704
Fold 2 IBS: 0.2662052808420901
Fold 3 IBS: 0.20996801490180272
Fold 4 IBS: 0.27074095333423953
Fold 5 IBS: 0.22672754258256947
[I 2024-04-13 17:33:08,400] Trial 1 finished with value: 0.2452361993826738 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.2452361993826738.
Fold 1 IBS: 0.25261539412518685
Fold 2 IBS: 0.2325812298093743
Fold 3 IBS: 0.20913119763580473
Fold 4 IBS: 0.27077104841709276
Fold 5 IBS: 0.22673601778495275
[I 2024-04-13 17:33:09,527] Trial 2 finished with value: 0.23836697755448227 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.2526019249404616
Fold 2 IBS: 0.2661992539028594
Fold 3 IBS: 0.21064243777387667
Fold 4 IBS: 0.27068388392199993
Fold 5 IBS: 0.22670798740360695
[I 2024-04-13 17:33:10,661] Trial 3 finished with value: 0.2453670975885609 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.2524914144826195
Fold 2 IBS: 0.266266050522108
Fold 3 IBS: 0.21045532137874493
Fold 4 IBS: 0.2706358323275706
Fold 5 IBS: 0.2267211052811516
[I 2024-04-13 17:33:12,026] Trial 4 finished with value: 0.24531394479843893 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.2524667359794851
Fold 2 IBS: 0.2663552692510122
Fold 3 IBS: 0.21056957830466747
Fold 4 IBS: 0.270715496744667
Fold 5 IBS: 0.22673238769555965
[I 2024-04-13 17:33:13,152] Trial 5 finished with value: 0.24536789359507827 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.2508703670253492
Fold 2 IBS: 0.25848676961044836
Fold 3 IBS: 0.21075283585777585
Fold 4 IBS: 0.2706722187800543
Fold 5 IBS: 0.22679346748920387
[I 2024-04-13 17:33:14,109] Trial 6 finished with value: 0.24351513175256634 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.2525693325172656
Fold 2 IBS: 0.266408409813695
Fold 3 IBS: 0.21067510044922722
Fold 4 IBS: 0.27069981017768535
Fold 5 IBS: 0.2267379548712124
[I 2024-04-13 17:33:15,286] Trial 7 finished with value: 0.24541812156581716 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.25248216519413264
Fold 2 IBS: 0.2663857488526804
Fold 3 IBS: 0.21058164470038845
Fold 4 IBS: 0.27070033662117216
Fold 5 IBS: 0.22670915797226784
[I 2024-04-13 17:33:16,419] Trial 8 finished with value: 0.24537181066812827 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.25243070388562056
Fold 2 IBS: 0.26618925357903195
Fold 3 IBS: 0.2105475870343153
Fold 4 IBS: 0.2706746661035389
Fold 5 IBS: 0.22672950304538103
[I 2024-04-13 17:33:17,926] Trial 9 finished with value: 0.24531434272957756 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.23836697755448227.
Fold 1 IBS: 0.24548430333408697
Fold 2 IBS: 0.2321507407258022
Fold 3 IBS: 0.2272708038442089
Fold 4 IBS: 0.24377982718435334
Fold 5 IBS: 0.22590001042317998
[I 2024-04-13 17:33:18,501] Trial 10 finished with value: 0.23491713710232628 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.24688558799654498
Fold 2 IBS: 0.23203747018650306
Fold 3 IBS: 0.22866547780355728
Fold 4 IBS: 0.24258385024376572
Fold 5 IBS: 0.22872556042627534
[I 2024-04-13 17:33:19,119] Trial 11 finished with value: 0.2357795893313293 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.24653523694170618
Fold 2 IBS: 0.23204483635394854
Fold 3 IBS: 0.22834422860937856
Fold 4 IBS: 0.24305222534143847
Fold 5 IBS: 0.228055795908042
[I 2024-04-13 17:33:19,600] Trial 12 finished with value: 0.23560646463090276 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.24716521465362304
Fold 2 IBS: 0.23203854826129833
Fold 3 IBS: 0.22891156996536546
Fold 4 IBS: 0.24212499649736227
Fold 5 IBS: 0.2292458916112592
[I 2024-04-13 17:33:20,096] Trial 13 finished with value: 0.23589724419778166 and parameters: {'l1_ratio': 0.002630198731852655}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.2527125600711567
Fold 2 IBS: 0.23238424023409054
Fold 3 IBS: 0.22628832794908776
Fold 4 IBS: 0.27082312333490144
Fold 5 IBS: 0.2266586980273644
[I 2024-04-13 17:33:21,078] Trial 14 finished with value: 0.24177338992332018 and parameters: {'l1_ratio': 0.1640712833693377}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.25280192032038445
Fold 2 IBS: 0.23226639482223657
Fold 3 IBS: 0.22670478972479927
Fold 4 IBS: 0.2708039006457428
Fold 5 IBS: 0.2265599631719742
[I 2024-04-13 17:33:22,087] Trial 15 finished with value: 0.24182739373702744 and parameters: {'l1_ratio': 0.12555451639526363}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.2528145316616673
Fold 2 IBS: 0.23223784740444067
Fold 3 IBS: 0.2268248847469234
Fold 4 IBS: 0.27083396962604295
Fold 5 IBS: 0.22647239992563037
[I 2024-04-13 17:33:23,181] Trial 16 finished with value: 0.24183672667294095 and parameters: {'l1_ratio': 0.11581492628181542}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.25247416652168125
Fold 2 IBS: 0.26618940475418734
Fold 3 IBS: 0.21034269042576154
Fold 4 IBS: 0.27071110411625243
Fold 5 IBS: 0.22674548975775563
[I 2024-04-13 17:33:24,527] Trial 17 finished with value: 0.24529257111512764 and parameters: {'l1_ratio': 0.3160042276805186}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.24591429525546907
Fold 2 IBS: 0.23208864701641113
Fold 3 IBS: 0.22773296776029753
Fold 4 IBS: 0.24360360380413656
Fold 5 IBS: 0.22681253371277663
[I 2024-04-13 17:33:25,081] Trial 18 finished with value: 0.2352304095098182 and parameters: {'l1_ratio': 0.05618708893326824}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.2508767686853172
Fold 2 IBS: 0.2585113466322559
Fold 3 IBS: 0.21085511845644028
Fold 4 IBS: 0.27067709442268506
Fold 5 IBS: 0.22681431926106338
[I 2024-04-13 17:33:26,283] Trial 19 finished with value: 0.24354692949155238 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.25267362224730305
Fold 2 IBS: 0.2324650140056997
Fold 3 IBS: 0.20834329589401052
Fold 4 IBS: 0.2707398914453792
Fold 5 IBS: 0.22672149746637227
[I 2024-04-13 17:33:28,006] Trial 20 finished with value: 0.23818866421175294 and parameters: {'l1_ratio': 0.1898127602758178}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.24569770331047722
Fold 2 IBS: 0.23211594755013953
Fold 3 IBS: 0.22750484354207035
Fold 4 IBS: 0.24371366652269316
Fold 5 IBS: 0.22635916831832295
[I 2024-04-13 17:33:28,538] Trial 21 finished with value: 0.23507826584874064 and parameters: {'l1_ratio': 0.06922839398387204}. Best is trial 10 with value: 0.23491713710232628.
Fold 1 IBS: 0.24537170596075647
Fold 2 IBS: 0.2321728044457158
Fold 3 IBS: 0.22714302901199507
Fold 4 IBS: 0.2437972840169686
Fold 5 IBS: 0.22565185906618823
[I 2024-04-13 17:33:29,181] Trial 22 finished with value: 0.23482733650032483 and parameters: {'l1_ratio': 0.09238794789130683}. Best is trial 22 with value: 0.23482733650032483.
Fold 1 IBS: 0.2525465759277034
Fold 2 IBS: 0.26612998759966533
Fold 3 IBS: 0.2099061163550942
Fold 4 IBS: 0.2707187514734171
Fold 5 IBS: 0.2266893155163495
[I 2024-04-13 17:33:30,967] Trial 23 finished with value: 0.24519814937444587 and parameters: {'l1_ratio': 0.27693381223632424}. Best is trial 22 with value: 0.23482733650032483.
Fold 1 IBS: 0.2453529276106168
Fold 2 IBS: 0.23217676239075155
Fold 3 IBS: 0.2271213987998604
Fold 4 IBS: 0.24379898659715724
Fold 5 IBS: 0.22561002673143418
[I 2024-04-13 17:33:31,566] Trial 24 finished with value: 0.23481202042596405 and parameters: {'l1_ratio': 0.09388196923015177}. Best is trial 24 with value: 0.23481202042596405.

Fold 1 IBS: 0.252624043135885
Fold 2 IBS: 0.23255883455393458
Fold 3 IBS: 0.20893882883297735
Fold 4 IBS: 0.27074736350160367
Fold 5 IBS: 0.22669900945256133
[I 2024-04-13 17:33:33,043] Trial 25 finished with value: 0.23831361589539238 and parameters: {'l1_ratio': 0.21973436884995384}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25246686300528276
Fold 2 IBS: 0.2661969101333031
Fold 3 IBS: 0.21068710549715425
Fold 4 IBS: 0.27069702623359165
Fold 5 IBS: 0.22669763552350894
[I 2024-04-13 17:33:34,500] Trial 26 finished with value: 0.24534910807856813 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25278223742816774
Fold 2 IBS: 0.23229046211821905
Fold 3 IBS: 0.22661042410447052
Fold 4 IBS: 0.270855222018163
Fold 5 IBS: 0.226626089871234
[I 2024-04-13 17:33:35,508] Trial 27 finished with value: 0.24183288710805084 and parameters: {'l1_ratio': 0.13360026443673156}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2528667687290983
Fold 2 IBS: 0.23217805950489975
Fold 3 IBS: 0.227114387009684
Fold 4 IBS: 0.24379946187598273
Fold 5 IBS: 0.22559647698240742
[I 2024-04-13 17:33:36,162] Trial 28 finished with value: 0.23631103082041446 and parameters: {'l1_ratio': 0.09436916766924414}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25264159526221686
Fold 2 IBS: 0.2663025355666523
Fold 3 IBS: 0.21061856917350394
Fold 4 IBS: 0.2706215219330596
Fold 5 IBS: 0.22676924106391388
[I 2024-04-13 17:33:37,535] Trial 29 finished with value: 0.24539069259986931 and parameters: {'l1_ratio': 0.5785000921271706}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25257644419765113
Fold 2 IBS: 0.2326486812353532
Fold 3 IBS: 0.2094493665015829
Fold 4 IBS: 0.27074042040947477
Fold 5 IBS: 0.22665982946638227
[I 2024-04-13 17:33:38,667] Trial 30 finished with value: 0.23841494836208885 and parameters: {'l1_ratio': 0.24880052779709597}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2454430753954445
Fold 2 IBS: 0.232158497680479
Fold 3 IBS: 0.2272243895217183
Fold 4 IBS: 0.24378764734099112
Fold 5 IBS: 0.22580966363476684
[I 2024-04-13 17:33:39,326] Trial 31 finished with value: 0.23488465471467998 and parameters: {'l1_ratio': 0.08688578663256911}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2526925518186352
Fold 2 IBS: 0.23242895925850002
Fold 3 IBS: 0.20797134043089055
Fold 4 IBS: 0.27079040230542195
Fold 5 IBS: 0.22665625906841416
[I 2024-04-13 17:33:40,899] Trial 32 finished with value: 0.23810790257637238 and parameters: {'l1_ratio': 0.17834376309767855}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24568471327955363
Fold 2 IBS: 0.23211782696653432
Fold 3 IBS: 0.22749087521120676
Fold 4 IBS: 0.24371890518829065
Fold 5 IBS: 0.22633159517636503
[I 2024-04-13 17:33:41,563] Trial 33 finished with value: 0.23506878316439012 and parameters: {'l1_ratio': 0.07006331392925823}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2526284844969818
Fold 2 IBS: 0.23254573710002216
Fold 3 IBS: 0.20884469759992128
Fold 4 IBS: 0.2707378351252284
Fold 5 IBS: 0.22667957842030548
[I 2024-04-13 17:33:43,223] Trial 34 finished with value: 0.2382872665484918 and parameters: {'l1_ratio': 0.21553914253693035}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25253230422785294
Fold 2 IBS: 0.26604771184224824
Fold 3 IBS: 0.21007927689034472
Fold 4 IBS: 0.2706764007995557
Fold 5 IBS: 0.22667691064273612
[I 2024-04-13 17:33:44,860] Trial 35 finished with value: 0.24520252088054756 and parameters: {'l1_ratio': 0.29666419984890746}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25262360139653606
Fold 2 IBS: 0.26636238011972124
Fold 3 IBS: 0.21070961554072762
Fold 4 IBS: 0.2706190203931969
Fold 5 IBS: 0.2268113310453649
[I 2024-04-13 17:33:46,210] Trial 36 finished with value: 0.24542518969910937 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2527091277734658
Fold 2 IBS: 0.23236249720229712
Fold 3 IBS: 0.22635754528357196
Fold 4 IBS: 0.27078781097540183
Fold 5 IBS: 0.2267024442209528
[I 2024-04-13 17:33:47,165] Trial 37 finished with value: 0.24178388509113793 and parameters: {'l1_ratio': 0.15709157802368975}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24555436837544908
Fold 2 IBS: 0.23213836073598978
Fold 3 IBS: 0.22734875747622565
Fold 4 IBS: 0.243762813481866
Fold 5 IBS: 0.22605227881081724
[I 2024-04-13 17:33:47,724] Trial 38 finished with value: 0.23497131577606956 and parameters: {'l1_ratio': 0.0788162861613429}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2524248614262227
Fold 2 IBS: 0.26626294381378546
Fold 3 IBS: 0.210575601221016
Fold 4 IBS: 0.27066803403158674
Fold 5 IBS: 0.2267211754146936
[I 2024-04-13 17:33:48,859] Trial 39 finished with value: 0.24533052318146092 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2525663661441389
Fold 2 IBS: 0.2663536940244987
Fold 3 IBS: 0.21070755473692734
Fold 4 IBS: 0.2706643806907982
Fold 5 IBS: 0.22673970552890912
[I 2024-04-13 17:33:49,985] Trial 40 finished with value: 0.24540634022505445 and parameters: {'l1_ratio': 0.5288175840778535}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2456181789798332
Fold 2 IBS: 0.23212791884401549
Fold 3 IBS: 0.2274187852526057
Fold 4 IBS: 0.2437432936722411
Fold 5 IBS: 0.22618963307217177
[I 2024-04-13 17:33:50,587] Trial 41 finished with value: 0.23501956196417345 and parameters: {'l1_ratio': 0.07444346186601063}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2461949392857145
Fold 2 IBS: 0.23206323519542785
Fold 3 IBS: 0.22801644537611487
Fold 4 IBS: 0.2433978137905143
Fold 5 IBS: 0.22738395843846687
[I 2024-04-13 17:33:51,063] Trial 42 finished with value: 0.23541127841724768 and parameters: {'l1_ratio': 0.04138932736548886}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25283155369832
Fold 2 IBS: 0.23222653127965615
Fold 3 IBS: 0.22687532185504783
Fold 4 IBS: 0.27080422807745314
Fold 5 IBS: 0.22643051820548546
[I 2024-04-13 17:33:51,932] Trial 43 finished with value: 0.24183363062319252 and parameters: {'l1_ratio': 0.11188058217026955}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24714087010682104
Fold 2 IBS: 0.23203823605917348
Fold 3 IBS: 0.2288905365661951
Fold 4 IBS: 0.2421686716547547
Fold 5 IBS: 0.22920119876170922
[I 2024-04-13 17:33:52,485] Trial 44 finished with value: 0.23588790262973075 and parameters: {'l1_ratio': 0.003427232604364533}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2525750532279249
Fold 2 IBS: 0.2326511837436
Fold 3 IBS: 0.20945250048145475
Fold 4 IBS: 0.2707426662448741
Fold 5 IBS: 0.22675147977258212
[I 2024-04-13 17:33:53,606] Trial 45 finished with value: 0.23843457669408719 and parameters: {'l1_ratio': 0.24961890069198156}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25262531838874186
Fold 2 IBS: 0.2662662327820923
Fold 3 IBS: 0.210579554480125
Fold 4 IBS: 0.2706687300780996
Fold 5 IBS: 0.22673116853214775
[I 2024-04-13 17:33:54,800] Trial 46 finished with value: 0.24537420085224132 and parameters: {'l1_ratio': 0.6392152456198857}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2524405677154646
Fold 2 IBS: 0.2660532071334398
Fold 3 IBS: 0.21056302839879248
Fold 4 IBS: 0.2707218473590335
Fold 5 IBS: 0.2267472387765701
[I 2024-04-13 17:33:57,048] Trial 47 finished with value: 0.2453051778766601 and parameters: {'l1_ratio': 0.3690718797203524}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2526927113522287
Fold 2 IBS: 0.26647285424189987
Fold 3 IBS: 0.21076836542102673
Fold 4 IBS: 0.27067963738244116
Fold 5 IBS: 0.22679569880154057
[I 2024-04-13 17:33:58,436] Trial 48 finished with value: 0.2454818534398274 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2527294491746882
Fold 2 IBS: 0.23234619601334477
Fold 3 IBS: 0.22641141012675528
Fold 4 IBS: 0.27076020916091803

Fold 5 IBS: 0.22666605038281498
[I 2024-04-13 17:33:59,362] Trial 49 finished with value: 0.24178266297170428 and parameters: {'l1_ratio': 0.1518326539107156}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25266240249412636
Fold 2 IBS: 0.23247632388876066
Fold 3 IBS: 0.20842985845168258
Fold 4 IBS: 0.2707546257420046
Fold 5 IBS: 0.22665258748020203
[I 2024-04-13 17:34:00,437] Trial 50 finished with value: 0.23819515961135526 and parameters: {'l1_ratio': 0.19340943531911486}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24544954020658022
Fold 2 IBS: 0.2321572574037747
Fold 3 IBS: 0.2272316951999604
Fold 4 IBS: 0.24378652935635142
Fold 5 IBS: 0.22582386876850116
[I 2024-04-13 17:34:01,051] Trial 51 finished with value: 0.2348897781870336 and parameters: {'l1_ratio': 0.08640058638065554}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24616826583690393
Fold 2 IBS: 0.2320652195968878
Fold 3 IBS: 0.22799004211711335
Fold 4 IBS: 0.24342043463827293
Fold 5 IBS: 0.22733035829859913
[I 2024-04-13 17:34:01,588] Trial 52 finished with value: 0.23539486409755545 and parameters: {'l1_ratio': 0.04270765069681875}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2528508014969374
Fold 2 IBS: 0.23220081074206875
Fold 3 IBS: 0.2269970212528343
Fold 4 IBS: 0.24380192267179038
Fold 5 IBS: 0.22537046701558675
[I 2024-04-13 17:34:02,189] Trial 53 finished with value: 0.2362442046358435 and parameters: {'l1_ratio': 0.10274109821572014}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2527733317288422
Fold 2 IBS: 0.2323016182877768
Fold 3 IBS: 0.22656854916240732
Fold 4 IBS: 0.2707794034235702
Fold 5 IBS: 0.22665279348498388
[I 2024-04-13 17:34:03,017] Trial 54 finished with value: 0.24181513921751607 and parameters: {'l1_ratio': 0.13728889309234446}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24702436965693625
Fold 2 IBS: 0.23203730186184965
Fold 3 IBS: 0.22878873302907068
Fold 4 IBS: 0.2423653870845098
Fold 5 IBS: 0.22898539945359633
[I 2024-04-13 17:34:03,693] Trial 55 finished with value: 0.23584023821719255 and parameters: {'l1_ratio': 0.007353391145091065}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24545672678482142
Fold 2 IBS: 0.23215588919968405
Fold 3 IBS: 0.22723980436604893
Fold 4 IBS: 0.24378523917176162
Fold 5 IBS: 0.2258396430120099
[I 2024-04-13 17:34:04,196] Trial 56 finished with value: 0.23489546050686522 and parameters: {'l1_ratio': 0.08586369634041277}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24621083500923907
Fold 2 IBS: 0.23206209278341214
Fold 3 IBS: 0.2280321287036867
Fold 4 IBS: 0.2433840265200181
Fold 5 IBS: 0.22741583314925115
[I 2024-04-13 17:34:04,735] Trial 57 finished with value: 0.2354209832331214 and parameters: {'l1_ratio': 0.040611762940001725}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2526891486072446
Fold 2 IBS: 0.2324342387624688
Fold 3 IBS: 0.2080203909833113
Fold 4 IBS: 0.2707976323192497
Fold 5 IBS: 0.22666565242859746
[I 2024-04-13 17:34:05,935] Trial 58 finished with value: 0.23812141262017436 and parameters: {'l1_ratio': 0.18002425303846548}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2528143634974115
Fold 2 IBS: 0.23223801108741116
Fold 3 IBS: 0.22682416780573306
Fold 4 IBS: 0.270834385838412
Fold 5 IBS: 0.22647183373928415
[I 2024-04-13 17:34:06,833] Trial 59 finished with value: 0.24183655239365037 and parameters: {'l1_ratio': 0.11587149691098564}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2525714046936015
Fold 2 IBS: 0.23265908892204631
Fold 3 IBS: 0.20950081611893864
Fold 4 IBS: 0.2707496661774993
Fold 5 IBS: 0.22667545549438475
[I 2024-04-13 17:34:07,908] Trial 60 finished with value: 0.23843128628129412 and parameters: {'l1_ratio': 0.2522076973038543}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2455462636882714
Fold 2 IBS: 0.23213974269663526
Fold 3 IBS: 0.2273397984793316
Fold 4 IBS: 0.2437650192707251
Fold 5 IBS: 0.22603474520735084
[I 2024-04-13 17:34:08,450] Trial 61 finished with value: 0.23496511386846283 and parameters: {'l1_ratio': 0.0793843839263613}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25287490360847487
Fold 2 IBS: 0.23218071356934508
Fold 3 IBS: 0.22710015508672243
Fold 4 IBS: 0.2438003116532586
Fold 5 IBS: 0.22556899126826724
[I 2024-04-13 17:34:09,061] Trial 62 finished with value: 0.23630501503721363 and parameters: {'l1_ratio': 0.09536242935261323}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24632416116674816
Fold 2 IBS: 0.2320547881386348
Fold 3 IBS: 0.22814285354334965
Fold 4 IBS: 0.2432790781326596
Fold 5 IBS: 0.22764164567651954
[I 2024-04-13 17:34:09,771] Trial 63 finished with value: 0.23548850533158233 and parameters: {'l1_ratio': 0.035235750936931653}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25277598986267097
Fold 2 IBS: 0.2322966721600859
Fold 3 IBS: 0.2265869771155284
Fold 4 IBS: 0.2707690684146143
Fold 5 IBS: 0.2266398598867967
[I 2024-04-13 17:34:10,734] Trial 64 finished with value: 0.24181371348793923 and parameters: {'l1_ratio': 0.13565639219125714}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24546748422508097
Fold 2 IBS: 0.2321538617421766
Fold 3 IBS: 0.22725191907341774
Fold 4 IBS: 0.24378321490379076
Fold 5 IBS: 0.22586322233470169
[I 2024-04-13 17:34:11,229] Trial 65 finished with value: 0.23490394045583357 and parameters: {'l1_ratio': 0.08506486773972674}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25266278019893623
Fold 2 IBS: 0.23247552540546387
Fold 3 IBS: 0.20842759679638642
Fold 4 IBS: 0.2707536080100026
Fold 5 IBS: 0.22673752485003676
[I 2024-04-13 17:34:12,362] Trial 66 finished with value: 0.23821140705216517 and parameters: {'l1_ratio': 0.1931554814060678}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2526189492884013
Fold 2 IBS: 0.2325715523509718
Fold 3 IBS: 0.20907324334222768
Fold 4 IBS: 0.2707609354360992
Fold 5 IBS: 0.22671828647660497
[I 2024-04-13 17:34:13,522] Trial 67 finished with value: 0.23834859337886094 and parameters: {'l1_ratio': 0.22381643368736384}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2458898541007761
Fold 2 IBS: 0.2320913667421581
Fold 3 IBS: 0.2277076568656438
Fold 4 IBS: 0.2436181572081217
Fold 5 IBS: 0.22676194730025998
[I 2024-04-13 17:34:14,018] Trial 68 finished with value: 0.23521379644339194 and parameters: {'l1_ratio': 0.057581186118410815}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2527257744938817
Fold 2 IBS: 0.23235106951740322
Fold 3 IBS: 0.22639512033354395
Fold 4 IBS: 0.27076864726251426
Fold 5 IBS: 0.22667599309067268
[I 2024-04-13 17:34:14,868] Trial 69 finished with value: 0.24178332093960314 and parameters: {'l1_ratio': 0.15340759965353867}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2528206533412578
Fold 2 IBS: 0.23223818351098005
Fold 3 IBS: 0.22682341295790576
Fold 4 IBS: 0.2708348228127466
Fold 5 IBS: 0.22647256429388557
[I 2024-04-13 17:34:15,769] Trial 70 finished with value: 0.24183792738335516 and parameters: {'l1_ratio': 0.11593107839484482}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24546842300257724
Fold 2 IBS: 0.23215368597385624
Fold 3 IBS: 0.22725297495451025
Fold 4 IBS: 0.2437830329684893
Fold 5 IBS: 0.2258652781951275
[I 2024-04-13 17:34:16,254] Trial 71 finished with value: 0.23490467901891213 and parameters: {'l1_ratio': 0.08499542840756195}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2466702138793613
Fold 2 IBS: 0.23204074164736443
Fold 3 IBS: 0.22846972741142652
Fold 4 IBS: 0.24288569735554547
Fold 5 IBS: 0.22831613457870117
[I 2024-04-13 17:34:16,770] Trial 72 finished with value: 0.23567650297447976 and parameters: {'l1_ratio': 0.020437338603424893}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24558127622394604
Fold 2 IBS: 0.2321338636463079
Fold 3 IBS: 0.2273783960829684
Fold 4 IBS: 0.24375504712656856
Fold 5 IBS: 0.22611034705209154
[I 2024-04-13 17:34:17,314] Trial 73 finished with value: 0.23499178602637646 and parameters: {'l1_ratio': 0.07695099840227157}. Best is trial 24 with value: 0.23481202042596405.

Fold 1 IBS: 0.252713111132158
Fold 2 IBS: 0.23239323708181045
Fold 3 IBS: 0.20770103603701506
Fold 4 IBS: 0.2707378309292403
Fold 5 IBS: 0.22667740702580663
[I 2024-04-13 17:34:18,596] Trial 74 finished with value: 0.2380445244412061 and parameters: {'l1_ratio': 0.16695008087283925}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2528601149267691
Fold 2 IBS: 0.23219255759525126
Fold 3 IBS: 0.22703843032528304
Fold 4 IBS: 0.24380222927085038
Fold 5 IBS: 0.22545003786977097
[I 2024-04-13 17:34:19,182] Trial 75 finished with value: 0.23626867399758494 and parameters: {'l1_ratio': 0.09973963884109015}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25277974872052894
Fold 2 IBS: 0.23229330708700294
Fold 3 IBS: 0.22659963895619875
Fold 4 IBS: 0.2707619785171471
Fold 5 IBS: 0.22663261267114376
[I 2024-04-13 17:34:20,068] Trial 76 finished with value: 0.2418134571904043 and parameters: {'l1_ratio': 0.13454314551947133}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2524697603069034
Fold 2 IBS: 0.26597994898317545
Fold 3 IBS: 0.21039606046826295
Fold 4 IBS: 0.2707204942653264
Fold 5 IBS: 0.2266751753536188
[I 2024-04-13 17:34:21,263] Trial 77 finished with value: 0.24524828787545738 and parameters: {'l1_ratio': 0.3210038304877163}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2508538519209331
Fold 2 IBS: 0.25842513328218
Fold 3 IBS: 0.21074924967737288
Fold 4 IBS: 0.2706608108568086
Fold 5 IBS: 0.22682260960216963
[I 2024-04-13 17:34:22,280] Trial 78 finished with value: 0.24350233106789285 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24596781088939754
Fold 2 IBS: 0.23208299106851302
Fold 3 IBS: 0.22778802492885283
Fold 4 IBS: 0.24356985187228208
Fold 5 IBS: 0.22692281689744134
[I 2024-04-13 17:34:22,795] Trial 79 finished with value: 0.23526629913129735 and parameters: {'l1_ratio': 0.053197661676740386}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2472283458715534
Fold 2 IBS: 0.2320395401244188
Fold 3 IBS: 0.22896582832137619
Fold 4 IBS: 0.24200962868937942
Fold 5 IBS: 0.22936139124216648
[I 2024-04-13 17:34:23,296] Trial 80 finished with value: 0.23592094684977888 and parameters: {'l1_ratio': 0.0005956158497426867}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24576289406727359
Fold 2 IBS: 0.2321069462578643
Fold 3 IBS: 0.22757443729610358
Fold 4 IBS: 0.24368503688188844
Fold 5 IBS: 0.22649686565297808
[I 2024-04-13 17:34:23,758] Trial 81 finished with value: 0.23512523603122162 and parameters: {'l1_ratio': 0.06513319947805568}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24535936495676017
Fold 2 IBS: 0.23217539622380318
Fold 3 IBS: 0.22712882456247752
Fold 4 IBS: 0.24379844240130763
Fold 5 IBS: 0.2256243822646991
[I 2024-04-13 17:34:24,254] Trial 82 finished with value: 0.23481728208180952 and parameters: {'l1_ratio': 0.09336755287871418}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.252644590250078
Fold 2 IBS: 0.23251287136315674
Fold 3 IBS: 0.20869157491497156
Fold 4 IBS: 0.27069993892442384
Fold 5 IBS: 0.22671603863978504
[I 2024-04-13 17:34:25,348] Trial 83 finished with value: 0.23825300281848305 and parameters: {'l1_ratio': 0.20504400594221323}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24539164268396893
Fold 2 IBS: 0.23216869221796066
Fold 3 IBS: 0.2271658899929966
Fold 4 IBS: 0.24379509446145134
Fold 5 IBS: 0.22569612689005247
[I 2024-04-13 17:34:26,115] Trial 84 finished with value: 0.23484348924928602 and parameters: {'l1_ratio': 0.0908233660426367}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2528500073105072
Fold 2 IBS: 0.23220141836769745
Fold 3 IBS: 0.2269940212470954
Fold 4 IBS: 0.24380185123636175
Fold 5 IBS: 0.22536470951716955
[I 2024-04-13 17:34:26,969] Trial 85 finished with value: 0.2362424015357663 and parameters: {'l1_ratio': 0.10296062453545904}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2527457423258363
Fold 2 IBS: 0.2323192864324302
Fold 3 IBS: 0.22650441771523963
Fold 4 IBS: 0.27081401607856415
Fold 5 IBS: 0.2266935821981611
[I 2024-04-13 17:34:28,526] Trial 86 finished with value: 0.2418154089500463 and parameters: {'l1_ratio': 0.1430867194584718}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2464140567241051
Fold 2 IBS: 0.2320499932536741
Fold 3 IBS: 0.22822936990432902
Fold 4 IBS: 0.24318745111511267
Fold 5 IBS: 0.22781903051770877
[I 2024-04-13 17:34:29,403] Trial 87 finished with value: 0.23553998030298592 and parameters: {'l1_ratio': 0.031168454630588004}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2526987610008001
Fold 2 IBS: 0.23241769442933832
Fold 3 IBS: 0.20793034880666084
Fold 4 IBS: 0.27077432824712955
Fold 5 IBS: 0.2267233295732867
[I 2024-04-13 17:34:31,293] Trial 88 finished with value: 0.2381088924114431 and parameters: {'l1_ratio': 0.17475579002324843}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25286644757253784
Fold 2 IBS: 0.23217894814440374
Fold 3 IBS: 0.22710960475759862
Fold 4 IBS: 0.24379976457575125
Fold 5 IBS: 0.22558723870345615
[I 2024-04-13 17:34:32,149] Trial 89 finished with value: 0.23630840075074952 and parameters: {'l1_ratio': 0.09470226860896458}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24594016416414974
Fold 2 IBS: 0.2320858623553347
Fold 3 IBS: 0.22775964343481017
Fold 4 IBS: 0.24358761165816611
Fold 5 IBS: 0.22686592480050255
[I 2024-04-13 17:34:32,806] Trial 90 finished with value: 0.23524784128259263 and parameters: {'l1_ratio': 0.05473139200790223}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2527986208840468
Fold 2 IBS: 0.23227001056545996
Fold 3 IBS: 0.22669023845243175
Fold 4 IBS: 0.2708121516216514
Fold 5 IBS: 0.2265690707093136
[I 2024-04-13 17:34:33,826] Trial 91 finished with value: 0.2418280184465807 and parameters: {'l1_ratio': 0.12677185332763558}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24645013054912024
Fold 2 IBS: 0.23204830536470114
Fold 3 IBS: 0.2282637706046892
Fold 4 IBS: 0.24314861594207862
Fold 5 IBS: 0.22788979129808778
[I 2024-04-13 17:34:34,391] Trial 92 finished with value: 0.23556012275173538 and parameters: {'l1_ratio': 0.02958239494358217}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24548812281005444
Fold 2 IBS: 0.2321500401934084
Fold 3 IBS: 0.22727508292151125
Fold 4 IBS: 0.24377902009854965
Fold 5 IBS: 0.2259083516006383
[I 2024-04-13 17:34:34,868] Trial 93 finished with value: 0.23492012352483244 and parameters: {'l1_ratio': 0.08354824086377516}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2527132587870329
Fold 2 IBS: 0.23239488898252916
Fold 3 IBS: 0.20771664692720138
Fold 4 IBS: 0.27074043646211826
Fold 5 IBS: 0.22668096409528854
[I 2024-04-13 17:34:35,918] Trial 94 finished with value: 0.23804923905083403 and parameters: {'l1_ratio': 0.1674781594328999}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25280906999189623
Fold 2 IBS: 0.23225099539002317
Fold 3 IBS: 0.22676837476487963
Fold 4 IBS: 0.27076711713297236
Fold 5 IBS: 0.2265125696316846
[I 2024-04-13 17:34:36,863] Trial 95 finished with value: 0.24182162538229118 and parameters: {'l1_ratio': 0.12033087903188724}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2466231616779273
Fold 2 IBS: 0.23204198108987611
Fold 3 IBS: 0.22842623597423756
Fold 4 IBS: 0.24294569992483792
Fold 5 IBS: 0.22822572204568212
[I 2024-04-13 17:34:37,399] Trial 96 finished with value: 0.2356525601425122 and parameters: {'l1_ratio': 0.022320093138964756}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.24578224629137027
Fold 2 IBS: 0.23210440875435098
Fold 3 IBS: 0.22759493759822283
Fold 4 IBS: 0.24367578974111
Fold 5 IBS: 0.22653752936846283
[I 2024-04-13 17:34:37,935] Trial 97 finished with value: 0.23513898235070338 and parameters: {'l1_ratio': 0.06394695398352836}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.25272304210471186
Fold 2 IBS: 0.23235571159563875
Fold 3 IBS: 0.22637975317363443
Fold 4 IBS: 0.27077654859413297

Fold 5 IBS: 0.22668719760261888
[I 2024-04-13 17:34:38,756] Trial 98 finished with value: 0.24178445061414738 and parameters: {'l1_ratio': 0.1549055492978006}. Best is trial 24 with value: 0.23481202042596405.
Fold 1 IBS: 0.2455139097004322
Fold 2 IBS: 0.2321453886883713
Fold 3 IBS: 0.22730388452260952
Fold 4 IBS: 0.24377320629239763
Fold 5 IBS: 0.2259645464095699
[I 2024-04-13 17:34:39,326] Trial 99 finished with value: 0.23494018712267611 and parameters: {'l1_ratio': 0.08168193521815892}. Best is trial 24 with value: 0.23481202042596405.


* Best trial for IBS:
 FrozenTrial(number=24, state=TrialState.COMPLETE, values=[0.23481202042596405], datetime_start=datetime.datetime(2024, 4, 13, 17, 33, 30, 972928), datetime_complete=datetime.datetime(2024, 4, 13, 17, 33, 31, 566163), params={'l1_ratio': 0.09388196923015177}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=24, value=None)


* Best Score for IBS:
 0.23481202042596405

In [67]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [68]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.63
train_ibs:  0.235

#### Test

In [69]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [70]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.980766121964777)

test_cindex : 0.572

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.09388196923015177)

test_ibs:  0.229

In [71]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [72]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:34:39,791] A new study created in memory with name: no-name-83fcad1d-88b4-4993-b722-a28710a37e62

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 17:34:47,352] Trial 0 finished with value: 0.6187977301006736 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6187977301006736.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6094420600858369
[I 2024-04-13 17:34:52,698] Trial 1 finished with value: 0.6237488136710192 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:34:59,146] Trial 2 finished with value: 0.6229733658988998 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:35:01,033] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:35:03,480] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:35:13,053] Trial 5 finished with value: 0.6218270216571679 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6094420600858369
[I 2024-04-13 17:35:23,293] Trial 6 finished with value: 0.5995723609793941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:35:27,501] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5214592274678111
[I 2024-04-13 17:35:40,884] Trial 8 finished with value: 0.5042918454935622 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:35:47,595] Trial 9 finished with value: 0.6124941831608247 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:35:48,362] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:35:53,825] Trial 11 finished with value: 0.6129332218211435 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.9250608990121825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 1 with value: 0.6237488136710192.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:36:00,250] Trial 12 finished with value: 0.6382167482744471 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8206827027986038, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13254323337687263, 'warm_start': False}. Best is trial 12 with value: 0.6382167482744471.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 17:36:03,589] Trial 13 finished with value: 0.6155259268666031 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12214947430735827, 'warm_start': False}. Best is trial 12 with value: 0.6382167482744471.
Fold 1 C-index: 0.5597609561752988
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.8021276595744681
Fold 4 C-index: 0.6406844106463878
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:04,537] Trial 14 finished with value: 0.661274162121231 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11396669613812715, 'warm_start': True}. Best is trial 14 with value: 0.661274162121231.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.687984496124031

Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:05,542] Trial 15 finished with value: 0.6815364844139735 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 32, 'oob_score': True, 'max_samples': 0.8219485202814404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': True}. Best is trial 15 with value: 0.6815364844139735.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:36:06,167] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.44827686549014745, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37909912926450273, 'warm_start': True}. Best is trial 15 with value: 0.6815364844139735.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 17:36:07,606] Trial 17 finished with value: 0.6895409260222489 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2138706147057923, 'warm_start': True}. Best is trial 17 with value: 0.6895409260222489.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:36:09,418] Trial 18 finished with value: 0.6896987117465925 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2171200473956938, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:11,133] Trial 19 finished with value: 0.6732099075929641 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.9946585698860816, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42883326307517006, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:36:13,441] Trial 20 finished with value: 0.6878047367558022 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9966629158836573, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2545762438232687, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:36:15,418] Trial 21 finished with value: 0.6895651366973921 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.9639969186184459, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2437877730150368, 'warm_start': True}. Best is trial 18 with value: 0.6896987117465925.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:36:16,908] Trial 22 finished with value: 0.6910745957879284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.8676148902984393, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22395371756309795, 'warm_start': True}. Best is trial 22 with value: 0.6910745957879284.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:36:19,564] Trial 23 finished with value: 0.6847876876921578 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 144, 'oob_score': True, 'max_samples': 0.8696699974194458, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27355128284391594, 'warm_start': True}. Best is trial 22 with value: 0.6910745957879284.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:36:20,924] Trial 24 finished with value: 0.7028777296239799 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.8666873301180216, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18247394618931245, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 17:36:22,290] Trial 25 finished with value: 0.6862431761238705 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.694473183989708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17899438960638397, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:27,122] Trial 26 finished with value: 0.6908180514604075 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.8603105664937221, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:36:32,102] Trial 27 finished with value: 0.690879607810116 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.8480603313960683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07826883989461175, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:36:34,420] Trial 28 finished with value: 0.6834080957400726 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.5100409687730639, 'max_features': None, 'min_weight_fraction_leaf': 0.08406288592069039, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:36:41,743] Trial 29 finished with value: 0.6995571701409032 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.06357526719965571, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:36:48,186] Trial 30 finished with value: 0.6883010388853158 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.6919164029113454, 'max_features': None, 'min_weight_fraction_leaf': 0.18416154592106396, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:36:54,686] Trial 31 finished with value: 0.6991838537239718 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.7425407774406056, 'max_features': None, 'min_weight_fraction_leaf': 0.06755614270828253, 'warm_start': True}. Best is trial 24 with value: 0.7028777296239799.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 17:37:01,659] Trial 32 finished with value: 0.71347233498625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.7213418356032232, 'max_features': None, 'min_weight_fraction_leaf': 0.005268431893676387, 'warm_start': True}. Best is trial 32 with value: 0.71347233498625.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 17:37:07,340] Trial 33 finished with value: 0.7143454416096479 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 497, 'oob_score': True, 'max_samples': 0.7317060450615778, 'max_features': None, 'min_weight_fraction_leaf': 0.00636445969534791, 'warm_start': True}. Best is trial 33 with value: 0.7143454416096479.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7253218884120172
[I 2024-04-13 17:37:13,982] Trial 34 finished with value: 0.7093070296808943 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.6498478551106737, 'max_features': None, 'min_weight_fraction_leaf': 0.0026718173907039787, 'warm_start': True}. Best is trial 33 with value: 0.7143454416096479.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:37:19,413] Trial 35 finished with value: 0.7184092367318795 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.5526064129655602, 'max_features': None, 'min_weight_fraction_leaf': 0.003679699406838821, 'warm_start': True}. Best is trial 35 with value: 0.7184092367318795.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:37:24,792] Trial 36 finished with value: 0.7185651249826217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.5549344736260913, 'max_features': None, 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.7185651249826217.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7811158798283262
[I 2024-04-13 17:37:30,153] Trial 37 finished with value: 0.7202887446059156 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.5814176605200219, 'max_features': None, 'min_weight_fraction_leaf': 0.0015943254569678817, 'warm_start': True}. Best is trial 37 with value: 0.7202887446059156.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:37:35,592] Trial 38 finished with value: 0.7226139021582083 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.5457909141571613, 'max_features': None, 'min_weight_fraction_leaf': 0.03880080650528065, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:37:39,610] Trial 39 finished with value: 0.7201288515882028 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.5368476716627143, 'max_features': None, 'min_weight_fraction_leaf': 0.038081261852135145, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 17:37:43,974] Trial 40 finished with value: 0.716032831744537 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 358, 'oob_score': True, 'max_samples': 0.40952146090981767, 'max_features': None, 'min_weight_fraction_leaf': 0.04061975291171849, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:37:48,663] Trial 41 finished with value: 0.712624555224156 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.551415472983159, 'max_features': None, 'min_weight_fraction_leaf': 0.03862016225559219, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:37:54,192] Trial 42 finished with value: 0.7192603005616668 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.5470571389584655, 'max_features': None, 'min_weight_fraction_leaf': 0.040547589426843215, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:37:58,960] Trial 43 finished with value: 0.7117951103449232 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.39343893459960555, 'max_features': None, 'min_weight_fraction_leaf': 0.037197106766703916, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:38:03,803] Trial 44 finished with value: 0.7068156485149109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.5037446232500291, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 38 with value: 0.7226139021582083.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:38:08,292] Trial 45 finished with value: 0.7377598119861252 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.6224391250822676, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.051293485724493715, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 17:38:18,727] Trial 46 finished with value: 0.6313385118971416 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.6010576387757552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14147922592542847, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:38:20,830] Trial 47 finished with value: 0.7280606226030029 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.5032144797599873, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05574216570821283, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:38:28,259] Trial 48 finished with value: 0.6202653504726628 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.6362652522405036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.058749933389336956, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 17:38:30,145] Trial 49 finished with value: 0.6868378352014417 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.32446222096768196, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09999547019922148, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 17:38:31,931] Trial 50 finished with value: 0.7215489646378563 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.49077652431354474, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022511395342881692, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:38:33,848] Trial 51 finished with value: 0.7197673695887684 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.4799716025166624, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023356353978444662, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 17:38:35,852] Trial 52 finished with value: 0.7119295230662075 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.4430397101533895, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05546859752674148, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:38:38,101] Trial 53 finished with value: 0.732052822868799 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.37699411471825023, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03181683271115842, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:38:40,205] Trial 54 finished with value: 0.7103906994788739 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.35484298072023907, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02439879662210201, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:38:42,492] Trial 55 finished with value: 0.6658561927484276 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.2601632974909122, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11812720872048674, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:38:49,865] Trial 56 finished with value: 0.6329785159428548 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.5939163004492594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07594467100316221, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:38:52,604] Trial 57 finished with value: 0.7077567855050916 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.417605389677477, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.022567886933550586, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:38:55,001] Trial 58 finished with value: 0.7084014179141025 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.36734352262627257, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0555217518283616, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:38:57,395] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.4820175814461636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3544232433893524, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:39:06,941] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.13319246988341354, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1478483729810709, 'warm_start': False}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 17:39:09,325] Trial 61 finished with value: 0.694601867113741 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.5242841615310458, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04056647502046609, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:39:11,515] Trial 62 finished with value: 0.7295239835677936 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.5989938697881527, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02024218059654313, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7811158798283262
[I 2024-04-13 17:39:13,495] Trial 63 finished with value: 0.7265215450419994 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.5800886465458086, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01592409160248775, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:39:15,813] Trial 64 finished with value: 0.7057723563934031 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.6306540419871571, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10134985371919171, 'warm_start': True}. Best is trial 45 with value: 0.7377598119861252.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:39:17,724] Trial 65 finished with value: 0.744372793830748 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.48772656128152925, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02153233090954807, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:39:19,935] Trial 66 finished with value: 0.7304619470428545 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.6592301391256026, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07213010958136569, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:39:22,308] Trial 67 finished with value: 0.7303245206618084 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.658332776835216, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0786225535507252, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:39:24,424] Trial 68 finished with value: 0.7350033461568455 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 324, 'oob_score': False, 'max_samples': 0.782951240419168, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:39:26,274] Trial 69 finished with value: 0.7114104838920958 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.7726300856584892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12841953214236906, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7253218884120172
[I 2024-04-13 17:39:28,701] Trial 70 finished with value: 0.7184151776246746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.8023071029509282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.088091229553206, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 17:39:30,917] Trial 71 finished with value: 0.7295204026438793 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.6597094598339149, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07494346044667374, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:39:32,929] Trial 72 finished with value: 0.7297450090921587 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.6507521187970767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06813374716595723, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 17:39:35,926] Trial 73 finished with value: 0.7321026717878453 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.6812499544043293, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07039581398771254, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 17:39:38,411] Trial 74 finished with value: 0.7171593761887324 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 255, 'oob_score': False, 'max_samples': 0.6687532229099372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0936898450129986, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:39:40,666] Trial 75 finished with value: 0.7369777367618064 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.706380565345059, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06787811748332337, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7339055793991416
[I 2024-04-13 17:39:42,700] Trial 76 finished with value: 0.7179195356062753 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.7085639969790332, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11414897284280093, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:39:44,583] Trial 77 finished with value: 0.7216353576071407 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.7541985504150174, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07972201398799938, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7851063829787234
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6416309012875536
[I 2024-04-13 17:39:46,620] Trial 78 finished with value: 0.6803721565923366 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.7127152729708048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.29205538265571684, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:39:49,712] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6228120642786297, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.41958947955878745, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:39:58,233] Trial 80 finished with value: 0.6172257451314318 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6720088970814889, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10386652069615948, 'warm_start': False}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 17:40:00,364] Trial 81 finished with value: 0.7320120642318223 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.7369273672792999, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06782159792325793, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7811158798283262
[I 2024-04-13 17:40:02,025] Trial 82 finished with value: 0.730229494509787 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.7952406802041782, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05094662429126583, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 17:40:04,901] Trial 83 finished with value: 0.6953812091002576 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 326, 'oob_score': False, 'max_samples': 0.7368333705955264, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1694628542086393, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:40:06,953] Trial 84 finished with value: 0.7392553812380884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.8406178075999796, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06813421705074371, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:40:09,245] Trial 85 finished with value: 0.7302622700611123 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'max_samples': 0.8306089170227028, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06578521283153765, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:40:11,553] Trial 86 finished with value: 0.7405771840680274 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.9236490757653891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04839348178619321, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 17:40:14,077] Trial 87 finished with value: 0.7440030583377307 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 276, 'oob_score': False, 'max_samples': 0.9426505941387808, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0458571199390998, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:40:15,923] Trial 88 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.9045286625545784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4978507265200673, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:40:17,331] Trial 89 finished with value: 0.7387263199915111 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9605688356486618, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04938248319171276, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.

Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:40:18,658] Trial 90 finished with value: 0.7357164327756954 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 191, 'oob_score': False, 'max_samples': 0.9509590620645423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04691631766264469, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-13 17:40:20,599] Trial 91 finished with value: 0.7350355708782796 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9470927951745665, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04725901659642619, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:40:22,074] Trial 92 finished with value: 0.7237357652900573 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.9504866379214324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053094099292765956, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:40:23,792] Trial 93 finished with value: 0.7350688972594961 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 198, 'oob_score': False, 'max_samples': 0.8969936953129258, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04367753331224559, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:40:25,428] Trial 94 finished with value: 0.7024901375378925 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 173, 'oob_score': False, 'max_samples': 0.9151949478759466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012193068752189541, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 17:40:27,014] Trial 95 finished with value: 0.7365314105381744 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.8802646337989153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04987709925035067, 'warm_start': True}. Best is trial 65 with value: 0.744372793830748.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:40:28,881] Trial 96 finished with value: 0.7521018842180724 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8757809738336038, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026360410334294093, 'warm_start': True}. Best is trial 96 with value: 0.7521018842180724.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:40:30,469] Trial 97 finished with value: 0.7529735758912052 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.9745319440587786, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02941204455344467, 'warm_start': True}. Best is trial 97 with value: 0.7529735758912052.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:40:35,767] Trial 98 finished with value: 0.6180562707587932 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 163, 'oob_score': False, 'max_samples': 0.9694692468947707, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027994915902686063, 'warm_start': False}. Best is trial 97 with value: 0.7529735758912052.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8022813688212928

[I 2024-04-13 17:40:38,615] A new study created in memory with name: no-name-13a7fe63-b5b3-45a9-8e37-0ea897646133

Fold 5 C-index: 0.8283261802575107
[I 2024-04-13 17:40:38,593] Trial 99 finished with value: 0.7595658029056476 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.9313711932374781, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011633867937315842, 'warm_start': True}. Best is trial 99 with value: 0.7595658029056476.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.7595658029056476], datetime_start=datetime.datetime(2024, 4, 13, 17, 40, 35, 774911), datetime_complete=datetime.datetime(2024, 4, 13, 17, 40, 38, 591866), params={'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.9313711932374781, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011633867937315842, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=99, value=None)


* Best Score for C-index:
 0.7595658029056476

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24174212688781635
Fold 2 IBS: 0.22837556031637174
Fold 3 IBS: 0.21925199037851104
Fold 4 IBS: 0.23387858646882115
Fold 5 IBS: 0.21192783289424028
[I 2024-04-13 17:40:49,331] Trial 0 finished with value: 0.2270352193891521 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.2270352193891521.
Fold 1 IBS: 0.24144275735387236
Fold 2 IBS: 0.22079642625239382
Fold 3 IBS: 0.2195858644892306
Fold 4 IBS: 0.2328787523585072
Fold 5 IBS: 0.21468068071692512
[I 2024-04-13 17:40:51,860] Trial 1 finished with value: 0.2258768962341858 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-13 17:40:53,620] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-13 17:41:00,555] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-13 17:41:05,581] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.2492022721662945
Fold 2 IBS: 0.2248156215657013
Fold 3 IBS: 0.21773271752809326
Fold 4 IBS: 0.2287247859937131
Fold 5 IBS: 0.21591178374347977
[I 2024-04-13 17:41:12,987] Trial 5 finished with value: 0.22727743619945642 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.2258768962341858.
Fold 1 IBS: 0.24345429173373118
Fold 2 IBS: 0.22177590887724122
Fold 3 IBS: 0.21900257819310728
Fold 4 IBS: 0.2300708478315454
Fold 5 IBS: 0.20857620825948778
[I 2024-04-13 17:41:20,200] Trial 6 finished with value: 0.2245759669790226 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24553997148168735
Fold 2 IBS: 0.23209632831596824
Fold 3 IBS: 0.22914599492354287
Fold 4 IBS: 0.24151189951584615
Fold 5 IBS: 0.22920646238220327
[I 2024-04-13 17:41:29,477] Trial 7 finished with value: 0.23550013132384956 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-13 17:41:44,848] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23795187102456028
Fold 2 IBS: 0.22068804877472178
Fold 3 IBS: 0.21736841990005548
Fold 4 IBS: 0.23483534153305224
Fold 5 IBS: 0.2166813748058101
[I 2024-04-13 17:41:48,141] Trial 9 finished with value: 0.22550501120764 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-13 17:42:03,259] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3251129986182119}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23821763800269524
Fold 2 IBS: 0.2206989405701499
Fold 3 IBS: 0.2183298733900689
Fold 4 IBS: 0.23435319377188557
Fold 5 IBS: 0.21624993612827711
[I 2024-04-13 17:42:06,856] Trial 11 finished with value: 0.22556991637261534 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.9904090680670613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.2390269025799132
Fold 2 IBS: 0.22093723784955296
Fold 3 IBS: 0.21614331470726378
Fold 4 IBS: 0.23568779668901688
Fold 5 IBS: 0.21706838561267935
[I 2024-04-13 17:42:10,566] Trial 12 finished with value: 0.2257727274876852 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9777827337837477, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3324053831839262}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.28429571858174646
Fold 2 IBS: 0.291976143238516
Fold 3 IBS: 0.25971605676138104
Fold 4 IBS: 0.2911448075888225
Fold 5 IBS: 0.2421484554746106
[I 2024-04-13 17:42:11,716] Trial 13 finished with value: 0.27385623632901535 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.8358240113413322, 'max_features': None, 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24072003207164025
Fold 2 IBS: 0.22931923287626255
Fold 3 IBS: 0.2206971081552678
Fold 4 IBS: 0.23441816780813163
Fold 5 IBS: 0.21155006913932226
[I 2024-04-13 17:42:20,459] Trial 14 finished with value: 0.22734092201012487 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.8213409911746509, 'max_features': None, 'min_weight_fraction_leaf': 0.2466431683648488}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24011905153998128
Fold 2 IBS: 0.22518763981988726
Fold 3 IBS: 0.22165869139663433
Fold 4 IBS: 0.2375480054269681
Fold 5 IBS: 0.21939984365433624
[I 2024-04-13 17:42:25,648] Trial 15 finished with value: 0.22878264636756143 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.8537410313073572, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3655886525927784}. Best is trial 6 with value: 0.2245759669790226.

Fold 1 IBS: 0.2392961564663636
Fold 2 IBS: 0.2209141876561904
Fold 3 IBS: 0.2197843622003885
Fold 4 IBS: 0.23449432140937404
Fold 5 IBS: 0.21510746016776658
[I 2024-04-13 17:42:28,173] Trial 16 finished with value: 0.2259192975800166 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.8978246151361277, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12075256052520705}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23788710888494208
Fold 2 IBS: 0.22243680052846054
Fold 3 IBS: 0.21523716494988468
Fold 4 IBS: 0.2354635803357212
Fold 5 IBS: 0.21631738782405596
[I 2024-04-13 17:42:37,262] Trial 17 finished with value: 0.2254684085046129 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.741685896826822, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23869855628325998
Fold 2 IBS: 0.22242767695758497
Fold 3 IBS: 0.2157055296703147
Fold 4 IBS: 0.23576281546540628
Fold 5 IBS: 0.2157448032649353
[I 2024-04-13 17:42:50,496] Trial 18 finished with value: 0.22566787632830027 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2742435840937791}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24632840137946754
Fold 2 IBS: 0.23215399476522983
Fold 3 IBS: 0.22955396254585125
Fold 4 IBS: 0.24150521854716006
Fold 5 IBS: 0.23021366118499692
[I 2024-04-13 17:43:02,524] Trial 19 finished with value: 0.23595104768454114 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.6099910227680899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3749437552159898}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24666575342744318
Fold 2 IBS: 0.23213825794648577
Fold 3 IBS: 0.2295175914696922
Fold 4 IBS: 0.24160807083199934
Fold 5 IBS: 0.23035609618327466
[I 2024-04-13 17:43:09,962] Trial 20 finished with value: 0.236057153971779 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.7619585591959509, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4532041395885572}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.24238904514874957
Fold 2 IBS: 0.23445593643522006
Fold 3 IBS: 0.22631622026231327
Fold 4 IBS: 0.24260320628868504
Fold 5 IBS: 0.21291028085045807
[I 2024-04-13 17:43:22,113] Trial 21 finished with value: 0.2317349377970852 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.9187552595429349, 'max_features': None, 'min_weight_fraction_leaf': 0.21197947565921343}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.23815659783121731
Fold 2 IBS: 0.22207749230002619
Fold 3 IBS: 0.21752970637890848
Fold 4 IBS: 0.23583123734864406
Fold 5 IBS: 0.2164629406223946
[I 2024-04-13 17:43:30,205] Trial 22 finished with value: 0.22601159489623815 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.8060035003385533, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3067334006568516}. Best is trial 6 with value: 0.2245759669790226.
Fold 1 IBS: 0.2365247351332946
Fold 2 IBS: 0.22050557618201566
Fold 3 IBS: 0.21512045407281427
Fold 4 IBS: 0.2337779971213356
Fold 5 IBS: 0.2161481181306821
[I 2024-04-13 17:43:37,782] Trial 23 finished with value: 0.22441537612802845 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9051753762122661, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23816787952025506}. Best is trial 23 with value: 0.22441537612802845.
Fold 1 IBS: 0.23561339472694814
Fold 2 IBS: 0.22133586039163214
Fold 3 IBS: 0.21447786302348743
Fold 4 IBS: 0.23400436966113364
Fold 5 IBS: 0.21612644313403398
[I 2024-04-13 17:43:44,017] Trial 24 finished with value: 0.22431158618744704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9299177072569818, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2520392540669227}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23734053455594875
Fold 2 IBS: 0.22238136978606352
Fold 3 IBS: 0.217109879798544
Fold 4 IBS: 0.23602786050229949
Fold 5 IBS: 0.21660878345157603
[I 2024-04-13 17:43:51,523] Trial 25 finished with value: 0.22589368561888637 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.9932624357183849, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.36562561378195096}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23719982212029692
Fold 2 IBS: 0.22044726520696664
Fold 3 IBS: 0.21486784959214336
Fold 4 IBS: 0.23273159700220875
Fold 5 IBS: 0.21646579110319986
[I 2024-04-13 17:43:58,041] Trial 26 finished with value: 0.2243424650049631 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.9058902641802971, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23696300699805542}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2437963229547316
Fold 2 IBS: 0.22276653565660226
Fold 3 IBS: 0.21454006940897422
Fold 4 IBS: 0.23541573435802962
Fold 5 IBS: 0.2144905314321996
[I 2024-04-13 17:44:04,456] Trial 27 finished with value: 0.22620183876210748 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.9377046402810433, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14696574200200033}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2466592970927268
Fold 2 IBS: 0.2322006384871181
Fold 3 IBS: 0.2298545910321478
Fold 4 IBS: 0.24133288058090815
Fold 5 IBS: 0.230048552619906
[I 2024-04-13 17:44:16,628] Trial 28 finished with value: 0.23601919196256138 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.26154064534881144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22590607990715106}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.23758412825426514
Fold 2 IBS: 0.22297538914957787
Fold 3 IBS: 0.21638228130409853
Fold 4 IBS: 0.2349760943144391
Fold 5 IBS: 0.21663197350890054
[I 2024-04-13 17:44:32,941] Trial 29 finished with value: 0.22570997330625625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.6859458752534023, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24558091355365722}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.24245047612298046
Fold 2 IBS: 0.22271929119513714
Fold 3 IBS: 0.2181117133635492
Fold 4 IBS: 0.23245730057613723
Fold 5 IBS: 0.2186082238373671
[I 2024-04-13 17:44:43,676] Trial 30 finished with value: 0.22686940101903424 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.4388997479034245, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11470501817805681}. Best is trial 24 with value: 0.22431158618744704.
Fold 1 IBS: 0.2399850896709501
Fold 2 IBS: 0.23006555677291446
Fold 3 IBS: 0.2217715118746403
Fold 4 IBS: 0.23484827509541154
Fold 5 IBS: 0.21133378408198586
[I 2024-04-13 17:44:51,265] Trial 31 finished with value: 0.22760084349918044 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 260, 'oob_score': False, 'max_samples': 0.8683795773714846, 'max_features': None, 'min_weight_fraction_leaf': 0.25607534090715667}. Best is trial 24 with value: 0.22431158618744704.

Fold 1 IBS: 0.2370347091364531
Fold 2 IBS: 0.21865616933268361
Fold 3 IBS: 0.2136904590169095
Fold 4 IBS: 0.2330616724900941
Fold 5 IBS: 0.21522492222501335
[I 2024-04-13 17:45:01,746] Trial 32 finished with value: 0.22353358644023075 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.8040571874379057, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18786523282060735}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.2369596498960518
Fold 2 IBS: 0.21919381104819285
Fold 3 IBS: 0.21367435784125732
Fold 4 IBS: 0.2331924481484345
Fold 5 IBS: 0.21510595787220624
[I 2024-04-13 17:45:10,702] Trial 33 finished with value: 0.22362524496122854 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.7910445247744765, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18809103319338225}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.23672523561114803
Fold 2 IBS: 0.21905100495993393
Fold 3 IBS: 0.21428207375878827
Fold 4 IBS: 0.23334334259045397
Fold 5 IBS: 0.21462924819781068
[I 2024-04-13 17:45:22,322] Trial 34 finished with value: 0.22360618102362695 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 377, 'oob_score': True, 'max_samples': 0.7912137176760294, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18558593432482404}. Best is trial 32 with value: 0.22353358644023075.
Fold 1 IBS: 0.23686591677724925
Fold 2 IBS: 0.21880215905099826
Fold 3 IBS: 0.21348650762243437
Fold 4 IBS: 0.23350536986447867
Fold 5 IBS: 0.21453876729002655
[I 2024-04-13 17:45:35,608] Trial 35 finished with value: 0.22343974412103745 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.7882412474357445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18410738872353652}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23712660831229618
Fold 2 IBS: 0.21936207956912226
Fold 3 IBS: 0.21377037949196134
Fold 4 IBS: 0.2353853780161964
Fold 5 IBS: 0.21604409087841447
[I 2024-04-13 17:45:50,437] Trial 36 finished with value: 0.22433770725359814 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.6319734188794576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18057866445401774}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23985764041755697
Fold 2 IBS: 0.2203910722203549
Fold 3 IBS: 0.21615232998036504
Fold 4 IBS: 0.2324242099038112
Fold 5 IBS: 0.21377035023694235
[I 2024-04-13 17:46:03,660] Trial 37 finished with value: 0.2245191205518061 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.7747419667382262, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14511659298967997}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.24676336973074187
Fold 2 IBS: 0.22400017565703165
Fold 3 IBS: 0.22050607510658007
Fold 4 IBS: 0.23160175255798512
Fold 5 IBS: 0.21460046142043543
[I 2024-04-13 17:46:19,654] Trial 38 finished with value: 0.22749436689455482 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.708969650791409, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07841760859950192}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.24122790903542682
Fold 2 IBS: 0.22126564420108252
Fold 3 IBS: 0.21500814519153294
Fold 4 IBS: 0.23088715452854772
Fold 5 IBS: 0.21505297571279228
[I 2024-04-13 17:46:37,123] Trial 39 finished with value: 0.22468836573387643 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.5567914809570165, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10107929772200888}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.2512512194499984
Fold 2 IBS: 0.23384119436207942
Fold 3 IBS: 0.21986209620007618
Fold 4 IBS: 0.2324052704281404
Fold 5 IBS: 0.21614780773365797
[I 2024-04-13 17:46:48,017] Trial 40 finished with value: 0.23070151763479047 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.6360911606111228, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04797053004225782}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.2364825751273401
Fold 2 IBS: 0.21926467455871407
Fold 3 IBS: 0.21319128346432453
Fold 4 IBS: 0.2332830275103288
Fold 5 IBS: 0.21513344099462875
[I 2024-04-13 17:47:00,028] Trial 41 finished with value: 0.2234710003310673 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.7910648434560368, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19044184409775022}. Best is trial 35 with value: 0.22343974412103745.
Fold 1 IBS: 0.23657216849211188
Fold 2 IBS: 0.21805180183232972
Fold 3 IBS: 0.2134098718971707
Fold 4 IBS: 0.2326760577782485
Fold 5 IBS: 0.21489772695679377
[I 2024-04-13 17:47:12,369] Trial 42 finished with value: 0.22312152539133093 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 363, 'oob_score': True, 'max_samples': 0.8069030132321051, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19162190380727356}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23945616928698815
Fold 2 IBS: 0.22072840117287257
Fold 3 IBS: 0.2138390608089632
Fold 4 IBS: 0.23224317279049148
Fold 5 IBS: 0.21446628607960228
[I 2024-04-13 17:47:26,254] Trial 43 finished with value: 0.22414661802778352 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.7256599857619218, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1528479024949021}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23649706067068324
Fold 2 IBS: 0.21941209208908452
Fold 3 IBS: 0.21295847947231347
Fold 4 IBS: 0.23594218559775645
Fold 5 IBS: 0.21615807717067265
[I 2024-04-13 17:47:44,161] Trial 44 finished with value: 0.2241935790001021 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 424, 'oob_score': True, 'max_samples': 0.6735879050942102, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2020053940682765}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23693251190244155
Fold 2 IBS: 0.2213288517310521
Fold 3 IBS: 0.21494689188039331
Fold 4 IBS: 0.23415254475273511
Fold 5 IBS: 0.21682890772894134
[I 2024-04-13 17:47:59,334] Trial 45 finished with value: 0.2248379415991127 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.5054965069088588, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16858288066901586}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24197332198213933
Fold 2 IBS: 0.22046487286415592
Fold 3 IBS: 0.21586457052819402
Fold 4 IBS: 0.23223394094427516
Fold 5 IBS: 0.2132292438608055
[I 2024-04-13 17:48:17,058] Trial 46 finished with value: 0.224753190035914 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.8105930895493332, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12622439487788628}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23556816618505033
Fold 2 IBS: 0.21943285786800518
Fold 3 IBS: 0.21472972925457443
Fold 4 IBS: 0.23233131562389348

Fold 5 IBS: 0.21452585999296125
[I 2024-04-13 17:48:30,337] Trial 47 finished with value: 0.22331758578489697 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.8648447148686852, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19908924320632904}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23571677073756844
Fold 2 IBS: 0.21862106487993588
Fold 3 IBS: 0.21456356649548577
Fold 4 IBS: 0.23300957311771886
Fold 5 IBS: 0.2147097776323396
[I 2024-04-13 17:48:43,141] Trial 48 finished with value: 0.2233241505726097 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.85048001681846, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21469064698337334}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23559067856645097
Fold 2 IBS: 0.21873875911929633
Fold 3 IBS: 0.21444282499967143
Fold 4 IBS: 0.2331433841346366
Fold 5 IBS: 0.21521373828133133
[I 2024-04-13 17:48:55,731] Trial 49 finished with value: 0.22342587702027733 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 349, 'oob_score': True, 'max_samples': 0.8608777099735355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21409963196930723}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2354720485014348
Fold 2 IBS: 0.21908483698682585
Fold 3 IBS: 0.21419738362473992
Fold 4 IBS: 0.23286928627582323
Fold 5 IBS: 0.21554847437687882
[I 2024-04-13 17:49:07,929] Trial 50 finished with value: 0.2234344059531405 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.8624774255144273, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2109347249153205}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23627193006876482
Fold 2 IBS: 0.21852946709881008
Fold 3 IBS: 0.2148469504923258
Fold 4 IBS: 0.23351001052284076
Fold 5 IBS: 0.21507169524249345
[I 2024-04-13 17:49:19,459] Trial 51 finished with value: 0.22364601068504694 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.8695358762760744, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21582255489884755}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23548356533028544
Fold 2 IBS: 0.218725010588746
Fold 3 IBS: 0.21451762386354145
Fold 4 IBS: 0.23286275629435157
Fold 5 IBS: 0.21475783585840155
[I 2024-04-13 17:49:31,443] Trial 52 finished with value: 0.22326935838706521 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.8462587816411291, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21547666896690265}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23613634094238448
Fold 2 IBS: 0.21848749437898204
Fold 3 IBS: 0.21292409617818456
Fold 4 IBS: 0.23567681901169757
Fold 5 IBS: 0.21518372968081823
[I 2024-04-13 17:49:44,133] Trial 53 finished with value: 0.22368169603841337 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2887922839794046}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23665761244588207
Fold 2 IBS: 0.22117302572817424
Fold 3 IBS: 0.21340438192039934
Fold 4 IBS: 0.2344340217943337
Fold 5 IBS: 0.21637287825154097
[I 2024-04-13 17:49:54,849] Trial 54 finished with value: 0.2244083840280661 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.8464063284466049, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2697118114658599}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23609369849161851
Fold 2 IBS: 0.22007777901922662
Fold 3 IBS: 0.215855484457008
Fold 4 IBS: 0.23438134550311407
Fold 5 IBS: 0.21573946841596092
[I 2024-04-13 17:50:04,593] Trial 55 finished with value: 0.2244295551773856 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.879833085890255, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21383320692792412}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24222956946122723
Fold 2 IBS: 0.22137697302616127
Fold 3 IBS: 0.21626516807485707
Fold 4 IBS: 0.23437496001734787
Fold 5 IBS: 0.21368603534260622
[I 2024-04-13 17:50:18,993] Trial 56 finished with value: 0.22558654118443994 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.9448123317517924, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15922434069943384}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23566710868723995
Fold 2 IBS: 0.21815687589456226
Fold 3 IBS: 0.21374824567704823
Fold 4 IBS: 0.23516414343276787
Fold 5 IBS: 0.2155717168434672
[I 2024-04-13 17:50:37,012] Trial 57 finished with value: 0.2236616181070171 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.8302783773614499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2212917621096384}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23597677041833393
Fold 2 IBS: 0.21966309894338662
Fold 3 IBS: 0.2147789356113197
Fold 4 IBS: 0.2346364915456495
Fold 5 IBS: 0.21544052695772373
[I 2024-04-13 17:50:50,267] Trial 58 finished with value: 0.22409916469528265 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.8822727605099482, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26404114905990445}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23687443879472495
Fold 2 IBS: 0.2196115034471744
Fold 3 IBS: 0.2144316176908922
Fold 4 IBS: 0.23394500800067253
Fold 5 IBS: 0.21552843402248026
[I 2024-04-13 17:51:03,533] Trial 59 finished with value: 0.22407820039118884 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.9619605093804899, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3043109475953167}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23648824629467255
Fold 2 IBS: 0.22035324074970292
Fold 3 IBS: 0.21311491690305986
Fold 4 IBS: 0.23558874827891282
Fold 5 IBS: 0.2147764365302421
[I 2024-04-13 17:51:18,179] Trial 60 finished with value: 0.22406431775131805 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.7432259190596778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23401215359777172}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23534762568590942
Fold 2 IBS: 0.21918131507767896
Fold 3 IBS: 0.21348843313052338
Fold 4 IBS: 0.2345139591305208
Fold 5 IBS: 0.2147806291992252
[I 2024-04-13 17:51:32,525] Trial 61 finished with value: 0.22346239244477153 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.8400984283316736, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20744391800378348}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23683459238973079
Fold 2 IBS: 0.2190589139081263
Fold 3 IBS: 0.21251768095507126
Fold 4 IBS: 0.23333473964097387
Fold 5 IBS: 0.21540218190074592
[I 2024-04-13 17:51:48,456] Trial 62 finished with value: 0.22342962175892964 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.7146112288426298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1673008720099634}. Best is trial 42 with value: 0.22312152539133093.

Fold 1 IBS: 0.24251844789708726
Fold 2 IBS: 0.2210411248095999
Fold 3 IBS: 0.2174884582534811
Fold 4 IBS: 0.23327796476633547
Fold 5 IBS: 0.21325865662478627
[I 2024-04-13 17:52:06,469] Trial 63 finished with value: 0.225516930470258 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.8434390256503708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13262761517233745}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24154578994370174
Fold 2 IBS: 0.22210454661611326
Fold 3 IBS: 0.21614753754341642
Fold 4 IBS: 0.23303912664616094
Fold 5 IBS: 0.21337979688122055
[I 2024-04-13 17:52:22,546] Trial 64 finished with value: 0.2252433595261226 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 421, 'oob_score': True, 'max_samples': 0.9071936553420485, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1668837494665743}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23578396984973268
Fold 2 IBS: 0.21982751985915058
Fold 3 IBS: 0.2127907655486023
Fold 4 IBS: 0.23611774962723142
Fold 5 IBS: 0.21593645923354832
[I 2024-04-13 17:52:38,951] Trial 65 finished with value: 0.22409129282365306 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.7091534179771193, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22490980526604287}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2465390297659536
Fold 2 IBS: 0.23217413632394113
Fold 3 IBS: 0.22957331555813507
Fold 4 IBS: 0.24145493115068345
Fold 5 IBS: 0.23026954015536694
[I 2024-04-13 17:52:50,407] Trial 66 finished with value: 0.236002190590816 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.7513910467079336, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4904781810386246}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2360357412254428
Fold 2 IBS: 0.2187126930774909
Fold 3 IBS: 0.21351408679377545
Fold 4 IBS: 0.2329566459809213
Fold 5 IBS: 0.2152135771982376
[I 2024-04-13 17:53:05,425] Trial 67 finished with value: 0.22328654885517357 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.8253291108475478, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20313220519951403}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24065133829818755
Fold 2 IBS: 0.22649622349010287
Fold 3 IBS: 0.22286450107823114
Fold 4 IBS: 0.23931283464708142
Fold 5 IBS: 0.22158590387862978
[I 2024-04-13 17:53:23,591] Trial 68 finished with value: 0.23018216027844657 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.23482143077480938, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10469307170592539}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23857197966111204
Fold 2 IBS: 0.21969954436291245
Fold 3 IBS: 0.21312219615211478
Fold 4 IBS: 0.23141791617263682
Fold 5 IBS: 0.21602934314344477
[I 2024-04-13 17:53:39,652] Trial 69 finished with value: 0.22376819589844418 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 347, 'oob_score': True, 'max_samples': 0.5927472377062504, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1379977256731293}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23885528352241767
Fold 2 IBS: 0.21953869680569335
Fold 3 IBS: 0.2148775976903492
Fold 4 IBS: 0.23345908200176593
Fold 5 IBS: 0.21438276633195175
[I 2024-04-13 17:54:02,561] Trial 70 finished with value: 0.22422268527043557 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.8292047043164549, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16367930540263453}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23680915897690014
Fold 2 IBS: 0.22008714306330915
Fold 3 IBS: 0.21622674732020958
Fold 4 IBS: 0.23269848004964874
Fold 5 IBS: 0.21476478864691187
[I 2024-04-13 17:54:21,025] Trial 71 finished with value: 0.2241172636113959 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.886809939325558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2018241978642696}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23602132741932083
Fold 2 IBS: 0.21929352463181243
Fold 3 IBS: 0.21479463231545
Fold 4 IBS: 0.23487972856446335
Fold 5 IBS: 0.21569292472186188
[I 2024-04-13 17:54:35,011] Trial 72 finished with value: 0.22413642753058172 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.8633059632266107, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24563240525389668}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23756080896385787
Fold 2 IBS: 0.2198709901179539
Fold 3 IBS: 0.21607716703164753
Fold 4 IBS: 0.23444739602719725
Fold 5 IBS: 0.21515728419865568
[I 2024-04-13 17:54:47,580] Trial 73 finished with value: 0.22462272926786242 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9365960110126715, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20402438062021583}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2439734659304091
Fold 2 IBS: 0.2178765152434605
Fold 3 IBS: 0.21637058574280912
Fold 4 IBS: 0.23265790035339595
Fold 5 IBS: 0.21509688786020262
[I 2024-04-13 17:54:51,055] Trial 74 finished with value: 0.22519507102605546 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.7690209890280151, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17482878175722952}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.24167367619307714
Fold 2 IBS: 0.2321091666317781
Fold 3 IBS: 0.2254096772934718
Fold 4 IBS: 0.2412558098040841
Fold 5 IBS: 0.2112087474135227
[I 2024-04-13 17:55:10,659] Trial 75 finished with value: 0.23033141546718677 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.9185869784489429, 'max_features': None, 'min_weight_fraction_leaf': 0.22786656653980156}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23643423760441268
Fold 2 IBS: 0.2189682190598761
Fold 3 IBS: 0.21316331155747148
Fold 4 IBS: 0.23551095785015766
Fold 5 IBS: 0.21530716431950858
[I 2024-04-13 17:55:24,357] Trial 76 finished with value: 0.22387677807828527 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.8145758924117495, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25894296074467726}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23649835615235615
Fold 2 IBS: 0.2202998367772717
Fold 3 IBS: 0.215849186186392
Fold 4 IBS: 0.23189510546241013
Fold 5 IBS: 0.21421820558824664
[I 2024-04-13 17:55:41,589] Trial 77 finished with value: 0.22375213803333532 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.8574304723771203, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19219578753985594}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23543043862820737
Fold 2 IBS: 0.21941172237656087
Fold 3 IBS: 0.21510969675644945
Fold 4 IBS: 0.23449274572109305

Fold 5 IBS: 0.21423498837277127
[I 2024-04-13 17:55:59,392] Trial 78 finished with value: 0.22373591837101642 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8854068847594949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23765891161800223}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23570867974207424
Fold 2 IBS: 0.22060193373952594
Fold 3 IBS: 0.2144464193518562
Fold 4 IBS: 0.23476296957407278
Fold 5 IBS: 0.21578644913062256
[I 2024-04-13 17:56:13,301] Trial 79 finished with value: 0.22426129030763034 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9991782770608287, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2796131771286568}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.25860616056552466
Fold 2 IBS: 0.247606837719613
Fold 3 IBS: 0.2319726248414201
Fold 4 IBS: 0.21372331996096558
Fold 5 IBS: 0.22292533572909917
[I 2024-04-13 17:56:14,039] Trial 80 finished with value: 0.23496685576332452 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 2, 'oob_score': True, 'max_samples': 0.7266137530392617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15138133095624934}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2424425528776856
Fold 2 IBS: 0.23603790633519647
Fold 3 IBS: 0.22385508599506115
Fold 4 IBS: 0.2408498337269256
Fold 5 IBS: 0.21319653378514064
[I 2024-04-13 17:56:35,886] Trial 81 finished with value: 0.2312763825440019 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.7784763388289013, 'max_features': None, 'min_weight_fraction_leaf': 0.1797361326491144}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.2359333065359587
Fold 2 IBS: 0.2177740535675139
Fold 3 IBS: 0.21340554055264466
Fold 4 IBS: 0.23325957841825662
Fold 5 IBS: 0.21578220466559705
[I 2024-04-13 17:56:56,065] Trial 82 finished with value: 0.22323093674799416 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.8175962542874978, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19766586115305992}. Best is trial 42 with value: 0.22312152539133093.
Fold 1 IBS: 0.23601034698653564
Fold 2 IBS: 0.21748305842766855
Fold 3 IBS: 0.21304430322253315
Fold 4 IBS: 0.23308271498728148
Fold 5 IBS: 0.21565089781052826
[I 2024-04-13 17:57:16,332] Trial 83 finished with value: 0.22305426428690941 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.8141450872491632, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1970991647731129}. Best is trial 83 with value: 0.22305426428690941.
Fold 1 IBS: 0.23612684478177634
Fold 2 IBS: 0.21748810056111387
Fold 3 IBS: 0.21296826834994675
Fold 4 IBS: 0.23300146461188564
Fold 5 IBS: 0.21553229839714166
[I 2024-04-13 17:57:37,052] Trial 84 finished with value: 0.22302339534037285 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.8096737689830545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19628098798162147}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23647255696644645
Fold 2 IBS: 0.21812077297319524
Fold 3 IBS: 0.21276820303695784
Fold 4 IBS: 0.23345302877262153
Fold 5 IBS: 0.2159040770659359
[I 2024-04-13 17:58:00,406] Trial 85 finished with value: 0.22334372776303138 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.811352649827629, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20105461655472903}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23613729090343752
Fold 2 IBS: 0.2179346998491405
Fold 3 IBS: 0.2129644243629255
Fold 4 IBS: 0.23394201782485338
Fold 5 IBS: 0.21572915695093184
[I 2024-04-13 17:58:20,535] Trial 86 finished with value: 0.22334151797825771 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 488, 'oob_score': True, 'max_samples': 0.8015324404528672, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19820833818823205}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23651644370953373
Fold 2 IBS: 0.2183132341743879
Fold 3 IBS: 0.2134129991132886
Fold 4 IBS: 0.2346203263183014
Fold 5 IBS: 0.21491522745649771
[I 2024-04-13 17:58:41,847] Trial 87 finished with value: 0.22355564615440188 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.7613285087560672, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19051696011006752}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23671103316078027
Fold 2 IBS: 0.22284517298984777
Fold 3 IBS: 0.21466085140706787
Fold 4 IBS: 0.23693276256284146
Fold 5 IBS: 0.21629400773876842
[I 2024-04-13 17:59:14,235] Trial 88 finished with value: 0.22548876557186115 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.6860019496673433, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2438001190871077}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.2463868285065531
Fold 2 IBS: 0.23214573353925852
Fold 3 IBS: 0.22952063623082164
Fold 4 IBS: 0.24149813996015929
Fold 5 IBS: 0.23026213720056213
[I 2024-04-13 17:59:37,340] Trial 89 finished with value: 0.23596269508747097 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.8149680975480039, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.41549217555832835}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23557602986231588
Fold 2 IBS: 0.21894288091688477
Fold 3 IBS: 0.21263728838237342
Fold 4 IBS: 0.23680776315197954
Fold 5 IBS: 0.2158104954061969
[I 2024-04-13 17:59:57,662] Trial 90 finished with value: 0.22395489154395012 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.7816843286867342, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.226633406438448}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.2361593385752497
Fold 2 IBS: 0.2180829122586363
Fold 3 IBS: 0.21264954315727935
Fold 4 IBS: 0.2333718311494117
Fold 5 IBS: 0.21516322407038282
[I 2024-04-13 18:00:24,924] Trial 91 finished with value: 0.22308536984219202 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.8383779120700723, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19824639992469062}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23813486363436617
Fold 2 IBS: 0.21841882418390748
Fold 3 IBS: 0.21525721526950065
Fold 4 IBS: 0.23385192469312954
Fold 5 IBS: 0.2144863105931356
[I 2024-04-13 18:00:52,291] Trial 92 finished with value: 0.2240298276748079 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.8371843344422779, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1793365451149834}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23656447575349918
Fold 2 IBS: 0.21820038163639136
Fold 3 IBS: 0.21281675876104583
Fold 4 IBS: 0.23387434885160996
Fold 5 IBS: 0.2155591110547076
[I 2024-04-13 18:01:13,352] Trial 93 finished with value: 0.22340301521145078 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.7957196161977251, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19569167078239133}. Best is trial 84 with value: 0.22302339534037285.

Fold 1 IBS: 0.2364707434109151
Fold 2 IBS: 0.21910149125141531
Fold 3 IBS: 0.21420284080337593
Fold 4 IBS: 0.23438012728527638
Fold 5 IBS: 0.21479897289302796
[I 2024-04-13 18:01:42,437] Trial 94 finished with value: 0.22379083512880213 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.892312681224388, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2167154554420358}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23950861114017571
Fold 2 IBS: 0.22006606579763324
Fold 3 IBS: 0.2159169717512573
Fold 4 IBS: 0.2336883258166932
Fold 5 IBS: 0.21371153072549798
[I 2024-04-13 18:02:05,824] Trial 95 finished with value: 0.22457830104625148 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 481, 'oob_score': True, 'max_samples': 0.8276360496389354, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15723641146991377}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23621930342339553
Fold 2 IBS: 0.2197693683012021
Fold 3 IBS: 0.212549877635375
Fold 4 IBS: 0.2356582021089957
Fold 5 IBS: 0.21528103181762887
[I 2024-04-13 18:02:22,441] Trial 96 finished with value: 0.22389555665731944 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.7367464108563165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23193902254984444}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.24624060350675028
Fold 2 IBS: 0.2322034277468248
Fold 3 IBS: 0.22948763066493197
Fold 4 IBS: 0.24145111666189772
Fold 5 IBS: 0.23035506563166086
[I 2024-04-13 18:02:45,812] Trial 97 finished with value: 0.23594756884241314 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.521538664132392, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.24008462634911135
Fold 2 IBS: 0.23017081780056728
Fold 3 IBS: 0.22347056715802682
Fold 4 IBS: 0.2395816781582648
Fold 5 IBS: 0.21173964829758143
[I 2024-04-13 18:03:05,822] Trial 98 finished with value: 0.22900946755271034 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.916008923653836, 'max_features': None, 'min_weight_fraction_leaf': 0.25397155497290275}. Best is trial 84 with value: 0.22302339534037285.
Fold 1 IBS: 0.23762169677462724
Fold 2 IBS: 0.21844353189407748
Fold 3 IBS: 0.2134302825507703
Fold 4 IBS: 0.2336034074556809
Fold 5 IBS: 0.2145271402918729
[I 2024-04-13 18:03:20,511] Trial 99 finished with value: 0.22352521179340573 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.7611936700803305, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1748800349642079}. Best is trial 84 with value: 0.22302339534037285.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.22302339534037285], datetime_start=datetime.datetime(2024, 4, 13, 17, 57, 16, 352891), datetime_complete=datetime.datetime(2024, 4, 13, 17, 57, 37, 48288), params={'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 453, 'oob_score': True, 'max_samples': 0.8096737689830545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19628098798162147}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.22302339534037285

In [73]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [74]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.76
train_ibs:  0.223

#### Test

In [75]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [76]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=5, max_leaf_nodes=8,
                     max_samples=0.9313711932374781, min_samples_split=12,
                     min_weight_fraction_leaf=0.011633867937315842,
                     n_estimators=214, random_state=123, warm_start=True)

test_cindex:  0.633

RandomSurvivalForest(max_depth=6, max_features='log2', max_leaf_nodes=20,
                     max_samples=0.8096737689830545, min_samples_leaf=2,
                     min_samples_split=11,
                     min_weight_fraction_leaf=0.19628098798162147,
                     n_estimators=453, oob_score=True, random_state=123)

test_ibs:  0.216

In [77]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [78]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [79]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:03:25,382] A new study created in memory with name: no-name-4ee4f212-f8a7-44b5-b1dd-4ef250669870

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 18:03:27,804] Trial 0 finished with value: 0.6810141068632278 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:03:34,198] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 18:03:47,619] Trial 2 finished with value: 0.6582254660871222 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 18:03:48,807] Trial 3 finished with value: 0.6744438961941063 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:03:54,200] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:00,262] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6810141068632278.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 18:04:03,273] Trial 6 finished with value: 0.6859283885370657 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 18:04:10,588] Trial 7 finished with value: 0.6556068669162063 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 18:04:11,098] Trial 8 finished with value: 0.6654991867539214 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 18:04:27,034] Trial 9 finished with value: 0.6603853489169398 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:33,461] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 18:04:38,578] Trial 11 finished with value: 0.6617606716684828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.6859283885370657.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 18:04:44,559] Trial 12 finished with value: 0.6867027610976928 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 18:04:51,006] Trial 13 finished with value: 0.6726878143099698 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:54,986] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:57,772] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.6867027610976928.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 18:05:01,924] Trial 16 finished with value: 0.6718042314769685 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 18:05:04,711] Trial 17 finished with value: 0.6672980040406395 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6375968992248062
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6373390557939914
[I 2024-04-13 18:05:05,893] Trial 18 finished with value: 0.6795670368174951 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 18:05:06,978] Trial 19 finished with value: 0.6806917145768351 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 18:05:09,553] Trial 20 finished with value: 0.6744556768014014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 18:05:12,730] Trial 21 finished with value: 0.6816626070383462 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 18:05:16,375] Trial 22 finished with value: 0.6768203176157102 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5833816310769062, 'min_weight_fraction_leaf': 0.10633258814265802}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 18:05:21,087] Trial 23 finished with value: 0.6861561520662033 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7310231778151053, 'min_weight_fraction_leaf': 0.013477785996217753}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 18:05:25,099] Trial 24 finished with value: 0.6783926045851235 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8534877389255904, 'min_weight_fraction_leaf': 0.013359081882411139}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 18:05:31,990] Trial 25 finished with value: 0.6823606592762896 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4743026143351115, 'min_weight_fraction_leaf': 0.05557982163590168}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 18:05:50,384] Trial 26 finished with value: 0.6371432881239313 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 410, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6941935959294678, 'min_weight_fraction_leaf': 0.026806923014800983}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 18:05:54,400] Trial 27 finished with value: 0.6759366077958741 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 443, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5973500072561096, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.6867027610976928.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 18:05:56,676] Trial 28 finished with value: 0.7175262582650991 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8562851117410581, 'min_weight_fraction_leaf': 0.07014867084326157}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7725321888412017
[I 2024-04-13 18:05:58,975] Trial 29 finished with value: 0.7156180788739028 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9207564519428275, 'min_weight_fraction_leaf': 0.07367160474295377}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 18:06:01,594] Trial 30 finished with value: 0.7115365161329625 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9237987532624947, 'min_weight_fraction_leaf': 0.08837761097303978}. Best is trial 28 with value: 0.7175262582650991.

Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 18:06:03,860] Trial 31 finished with value: 0.7161536582914563 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9402340730195752, 'min_weight_fraction_leaf': 0.07589392630375186}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 18:06:07,394] Trial 32 finished with value: 0.6961121726190391 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 207, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.855896173949004, 'min_weight_fraction_leaf': 0.08857520431614199}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7639484978540773
[I 2024-04-13 18:06:10,196] Trial 33 finished with value: 0.7153131837982872 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 199, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9327283887206919, 'min_weight_fraction_leaf': 0.07569748402462002}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6375968992248062
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.6802575107296137
[I 2024-04-13 18:06:12,565] Trial 34 finished with value: 0.6664666881360952 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.835970866549261, 'min_weight_fraction_leaf': 0.23372934022685896}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 18:06:15,566] Trial 35 finished with value: 0.6882634234693772 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 162, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9271457960024162, 'min_weight_fraction_leaf': 0.130853317292017}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.5736434108527132
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 18:06:19,992] Trial 36 finished with value: 0.6191913617370259 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 124, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9489017093297756, 'min_weight_fraction_leaf': 0.05781516413223613}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 18:06:22,005] Trial 37 finished with value: 0.6833092043963852 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8743715114186904, 'min_weight_fraction_leaf': 0.16627394422836966}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 18:06:23,748] Trial 38 finished with value: 0.6876697416391948 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.817264125566284, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.5697674418604651
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 18:06:27,918] Trial 39 finished with value: 0.6172171145531613 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 102, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9887286618847455, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 18:06:30,466] Trial 40 finished with value: 0.66414330845729 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7565046460320802, 'min_weight_fraction_leaf': 0.24430703768925296}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 18:06:32,627] Trial 41 finished with value: 0.7066368021144237 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9048172691384212, 'min_weight_fraction_leaf': 0.08914857859645303}. Best is trial 28 with value: 0.7175262582650991.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 18:06:35,007] Trial 42 finished with value: 0.743465329768543 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9365468593171198, 'min_weight_fraction_leaf': 0.041208379854996445}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 18:06:37,611] Trial 43 finished with value: 0.6963198668263061 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8038316611821256, 'min_weight_fraction_leaf': 0.04529341869060194}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 18:06:40,128] Trial 44 finished with value: 0.7313319298416705 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9992719988890266, 'min_weight_fraction_leaf': 0.06592612651601726}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6459227467811158
[I 2024-04-13 18:06:42,396] Trial 45 finished with value: 0.6673320498489252 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9991832238100966, 'min_weight_fraction_leaf': 0.2989643862163749}. Best is trial 42 with value: 0.743465329768543.

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 18:06:43,890] Trial 46 finished with value: 0.7383725397721712 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 132, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470561026828803, 'min_weight_fraction_leaf': 0.03640088498403455}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6630901287553648
[I 2024-04-13 18:06:46,751] Trial 47 finished with value: 0.6598696288076124 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 89, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9628659202725078, 'min_weight_fraction_leaf': 0.03266964081324999}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 18:06:50,904] Trial 48 finished with value: 0.6843049998761438 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 269, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8730259684417422, 'min_weight_fraction_leaf': 0.1266834798944097}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6330472103004292
[I 2024-04-13 18:06:52,231] Trial 49 finished with value: 0.6590145940458656 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957708632958839, 'min_weight_fraction_leaf': 0.027911042382701867}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 18:06:53,751] Trial 50 finished with value: 0.6897778948683545 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7837469252671783, 'min_weight_fraction_leaf': 0.1078843272541912}. Best is trial 42 with value: 0.743465329768543.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 18:06:56,093] Trial 51 finished with value: 0.7441605217818494 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 222, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9978368210677339, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 18:06:57,305] Trial 52 finished with value: 0.7320707671648804 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 81, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9693702623323143, 'min_weight_fraction_leaf': 0.05796340800499559}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-13 18:06:58,646] Trial 53 finished with value: 0.724572062991922 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 76, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9970270850713104, 'min_weight_fraction_leaf': 0.05198230424362128}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 18:06:59,640] Trial 54 finished with value: 0.7259167134190326 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 66, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9784142102515536, 'min_weight_fraction_leaf': 0.03905401729625176}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 18:07:00,769] Trial 55 finished with value: 0.7020258748504518 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 54, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9639066574288683, 'min_weight_fraction_leaf': 0.021327695456537624}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:01,513] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 25, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8965627067300803, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 18:07:01,977] Trial 57 finished with value: 0.6762686514862031 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 7, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.22469228024982557, 'min_weight_fraction_leaf': 0.05372431175834813}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 18:07:03,092] Trial 58 finished with value: 0.6970396573100552 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5320477532151755, 'min_weight_fraction_leaf': 0.03900243908413086}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 18:07:05,495] Trial 59 finished with value: 0.6519459902471118 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9630384668147912, 'min_weight_fraction_leaf': 6.788603062825999e-05}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 18:07:06,753] Trial 60 finished with value: 0.6413474338179449 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 143, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9882157961126447, 'min_weight_fraction_leaf': 0.38500894227855625}. Best is trial 51 with value: 0.7441605217818494.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 18:07:07,574] Trial 61 finished with value: 0.7225416362930333 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 66, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9943656688034969, 'min_weight_fraction_leaf': 0.04800870002967368}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 18:07:08,630] Trial 62 finished with value: 0.6897163220843844 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8946150126733304, 'min_weight_fraction_leaf': 0.10247641006595459}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7639484978540773
[I 2024-04-13 18:07:09,522] Trial 63 finished with value: 0.7196656386882508 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 38, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9438677546925018, 'min_weight_fraction_leaf': 0.024050857269544722}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 18:07:11,062] Trial 64 finished with value: 0.7327012293133587 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 125, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9946117477834561, 'min_weight_fraction_leaf': 0.056485434742474354}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7896995708154506
[I 2024-04-13 18:07:12,579] Trial 65 finished with value: 0.7433456281236541 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 122, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9063260887192888, 'min_weight_fraction_leaf': 0.012665422708896507}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:13,959] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8260977181471251, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7682403433476395
[I 2024-04-13 18:07:16,243] Trial 67 finished with value: 0.7327922342641481 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9104970128937423, 'min_weight_fraction_leaf': 0.007706755525859518}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7510729613733905
[I 2024-04-13 18:07:19,012] Trial 68 finished with value: 0.7224161877505806 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9198568568859149, 'min_weight_fraction_leaf': 0.00978704762960042}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7339055793991416
[I 2024-04-13 18:07:22,378] Trial 69 finished with value: 0.7244476068280288 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8797241290258244, 'min_weight_fraction_leaf': 0.01678703277254251}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 18:07:25,181] Trial 70 finished with value: 0.6745315468327391 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 253, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9113946680361682, 'min_weight_fraction_leaf': 0.03227851293056033}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 18:07:27,395] Trial 71 finished with value: 0.7075849752369485 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9418428735851675, 'min_weight_fraction_leaf': 0.06227247952613971}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 18:07:29,270] Trial 72 finished with value: 0.7027360570907633 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 171, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8489781434967721, 'min_weight_fraction_leaf': 0.08925369909603265}. Best is trial 51 with value: 0.7441605217818494.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 18:07:32,273] Trial 73 finished with value: 0.7683176307777926 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666978302306899, 'min_weight_fraction_leaf': 0.0007431171546460995}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 18:07:34,886] Trial 74 finished with value: 0.753464799313606 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 253, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8740760642487182, 'min_weight_fraction_leaf': 0.01305076334530337}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7639484978540773
[I 2024-04-13 18:07:37,637] Trial 75 finished with value: 0.7267661356567718 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4065884568013973, 'min_weight_fraction_leaf': 0.00029874484326093687}. Best is trial 73 with value: 0.7683176307777926.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 18:07:53,431] Trial 76 finished with value: 0.6416338194920268 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 331, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8799754466378142, 'min_weight_fraction_leaf': 0.01810709499481526}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8412017167381974
[I 2024-04-13 18:07:56,781] Trial 77 finished with value: 0.7543780132055444 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9240429179776719, 'min_weight_fraction_leaf': 0.012643822634965579}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 18:08:00,173] Trial 78 finished with value: 0.6958045178573318 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7594151082635523, 'min_weight_fraction_leaf': 0.015234469209567447}. Best is trial 73 with value: 0.7683176307777926.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 18:08:03,627] Trial 79 finished with value: 0.7697774108186687 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 250, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8442545000898158, 'min_weight_fraction_leaf': 0.0004457953818449434}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 18:08:06,521] Trial 80 finished with value: 0.7583547716816389 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 193, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8057269821925708, 'min_weight_fraction_leaf': 0.032477063707157354}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 18:08:08,940] Trial 81 finished with value: 0.7385651919069479 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.832112782603648, 'min_weight_fraction_leaf': 0.04071400179748555}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-13 18:08:12,029] Trial 82 finished with value: 0.7510098175054138 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294416952085367, 'min_weight_fraction_leaf': 0.02743234620004307}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8412017167381974
[I 2024-04-13 18:08:14,501] Trial 83 finished with value: 0.759259943171113 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 190, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8005603713498318, 'min_weight_fraction_leaf': 0.024887842810569518}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-13 18:08:16,727] Trial 84 finished with value: 0.7468373768005192 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6978238625237797, 'min_weight_fraction_leaf': 0.027202826299221203}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 18:08:18,763] Trial 85 finished with value: 0.6834829872526711 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7435224088611663, 'min_weight_fraction_leaf': 0.026900856768979266}. Best is trial 79 with value: 0.7697774108186687.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 18:08:21,814] Trial 86 finished with value: 0.7730627016264678 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6969352508494835, 'min_weight_fraction_leaf': 0.0016027914654294685}. Best is trial 86 with value: 0.7730627016264678.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8412017167381974
[I 2024-04-13 18:08:24,980] Trial 87 finished with value: 0.7744609253176357 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6910931457501369, 'min_weight_fraction_leaf': 0.0034957148487665163}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.5736434108527132
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 18:08:40,245] Trial 88 finished with value: 0.62249459003292 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 264, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6571074060623916, 'min_weight_fraction_leaf': 0.002587756834995009}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8025751072961373
[I 2024-04-13 18:08:43,807] Trial 89 finished with value: 0.7474274777067873 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6947330701336499, 'min_weight_fraction_leaf': 0.01811060590765391}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 18:08:46,922] Trial 90 finished with value: 0.6534956129908318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7833034071663476, 'min_weight_fraction_leaf': 0.2732759857764308}. Best is trial 87 with value: 0.7744609253176357.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-13 18:08:51,302] Trial 91 finished with value: 0.7442871889568908 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6338574910210881, 'min_weight_fraction_leaf': 0.018245084195721045}. Best is trial 87 with value: 0.7744609253176357.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 18:08:54,448] Trial 92 finished with value: 0.7783542380855362 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7127170027641319, 'min_weight_fraction_leaf': 0.007255594364833751}. Best is trial 92 with value: 0.7783542380855362.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 18:08:58,274] Trial 93 finished with value: 0.773012031469599 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7126345666181687, 'min_weight_fraction_leaf': 0.01132491050397371}. Best is trial 92 with value: 0.7783542380855362.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 18:09:01,549] Trial 94 finished with value: 0.7914071396177732 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8020091028727125, 'min_weight_fraction_leaf': 0.002435943155287043}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 18:09:04,369] Trial 95 finished with value: 0.7656779799204749 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.805459261539753, 'min_weight_fraction_leaf': 0.0014206283717166004}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 18:09:07,943] Trial 96 finished with value: 0.7792303748029571 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.803528354509956, 'min_weight_fraction_leaf': 0.0027490549087902}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 18:09:12,765] Trial 97 finished with value: 0.7488547526042695 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6615256729229535, 'min_weight_fraction_leaf': 0.003268318092994542}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7939914163090128
[I 2024-04-13 18:09:16,096] Trial 98 finished with value: 0.7498258990394505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6157099383260888, 'min_weight_fraction_leaf': 0.0006747748712030638}. Best is trial 94 with value: 0.7914071396177732.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7452471482889734

[I 2024-04-13 18:09:20,204] A new study created in memory with name: no-name-2cbe2e47-f840-4c38-b9b2-f3e4a5cea431

Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 18:09:20,182] Trial 99 finished with value: 0.6972890739296207 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7082106596673203, 'min_weight_fraction_leaf': 0.047918273005709944}. Best is trial 94 with value: 0.7914071396177732.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.7914071396177732], datetime_start=datetime.datetime(2024, 4, 13, 18, 8, 58, 279478), datetime_complete=datetime.datetime(2024, 4, 13, 18, 9, 1, 543591), params={'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8020091028727125, 'min_weight_fraction_leaf': 0.002435943155287043}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.7914071396177732

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2376731560632284
Fold 2 IBS: 0.21418439969357622
Fold 3 IBS: 0.20583073428188067
Fold 4 IBS: 0.22566432866025307
Fold 5 IBS: 0.20768742813444407
[I 2024-04-13 18:09:33,361] Trial 0 finished with value: 0.2182080093666765 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-13 18:09:55,262] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23822850327226391
Fold 2 IBS: 0.2206236163074506
Fold 3 IBS: 0.21714095783489826
Fold 4 IBS: 0.231585384136663
Fold 5 IBS: 0.21839284596456812
[I 2024-04-13 18:10:12,424] Trial 2 finished with value: 0.2251942615031688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23969391295516015
Fold 2 IBS: 0.22269581058919702
Fold 3 IBS: 0.21715327615258315
Fold 4 IBS: 0.23305972993486937
Fold 5 IBS: 0.21933565152070564
[I 2024-04-13 18:10:17,965] Trial 3 finished with value: 0.22638767623050304 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-13 18:10:32,106] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-13 18:10:39,314] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.2182080093666765.
Fold 1 IBS: 0.23749741627181767
Fold 2 IBS: 0.21452695445742026
Fold 3 IBS: 0.2056873183383438
Fold 4 IBS: 0.22461247201663356
Fold 5 IBS: 0.20853691895247092
[I 2024-04-13 18:10:52,144] Trial 6 finished with value: 0.21817221600733724 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24029204437738358
Fold 2 IBS: 0.21830289871526046
Fold 3 IBS: 0.21554373414859246
Fold 4 IBS: 0.22777980675313916
Fold 5 IBS: 0.2123884851749296
[I 2024-04-13 18:11:00,892] Trial 7 finished with value: 0.22286139383386105 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24089922857013013
Fold 2 IBS: 0.22202813660146767
Fold 3 IBS: 0.21893220102332406
Fold 4 IBS: 0.2316324273038109
Fold 5 IBS: 0.2195150868165958
[I 2024-04-13 18:11:02,697] Trial 8 finished with value: 0.2266014160630657 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24074052614629513
Fold 2 IBS: 0.2266612039122537
Fold 3 IBS: 0.22147987410714284
Fold 4 IBS: 0.23635902242741375
Fold 5 IBS: 0.22338299988114635
[I 2024-04-13 18:11:19,087] Trial 9 finished with value: 0.22972472529485036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24645397072894554
Fold 2 IBS: 0.23215165796624326
Fold 3 IBS: 0.2300072528605466
Fold 4 IBS: 0.24106162740477477
Fold 5 IBS: 0.23037976132987092
[I 2024-04-13 18:11:32,890] Trial 10 finished with value: 0.23601085405807623 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24194872801906908
Fold 2 IBS: 0.22653162527123616
Fold 3 IBS: 0.2214231768945529
Fold 4 IBS: 0.23736843207524794
Fold 5 IBS: 0.22258083713853571
[I 2024-04-13 18:11:44,478] Trial 11 finished with value: 0.22997055987972836 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24166386224310335
Fold 2 IBS: 0.21668275898081935
Fold 3 IBS: 0.21053766058256898
Fold 4 IBS: 0.22332329218058097
Fold 5 IBS: 0.20507124091541545
[I 2024-04-13 18:11:59,632] Trial 12 finished with value: 0.21945576298049763 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2351797092055412
Fold 2 IBS: 0.21809509235620259
Fold 3 IBS: 0.20720090287111972
Fold 4 IBS: 0.2272337876903696
Fold 5 IBS: 0.21352749156724554
[I 2024-04-13 18:12:11,864] Trial 13 finished with value: 0.22024739673809574 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24709076537787542
Fold 2 IBS: 0.23229758763044567
Fold 3 IBS: 0.22965399450652796
Fold 4 IBS: 0.2411751364309486
Fold 5 IBS: 0.23019081700505956
[I 2024-04-13 18:12:20,665] Trial 14 finished with value: 0.23608166019017146 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.2400719537573894
Fold 2 IBS: 0.21389198803292667
Fold 3 IBS: 0.20731598881412483
Fold 4 IBS: 0.2254024226576354
Fold 5 IBS: 0.2076527894088986
[I 2024-04-13 18:12:32,781] Trial 15 finished with value: 0.21886702853419499 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23503018438204812
Fold 2 IBS: 0.2154046167742676
Fold 3 IBS: 0.20556392106742435
Fold 4 IBS: 0.22806516746710437
Fold 5 IBS: 0.2112562209054064
[I 2024-04-13 18:12:43,399] Trial 16 finished with value: 0.2190640221192502 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.18687423911629308}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24669394452893645
Fold 2 IBS: 0.2321566246385927
Fold 3 IBS: 0.22939614692957794
Fold 4 IBS: 0.24141885307467398
Fold 5 IBS: 0.2302911553756569
[I 2024-04-13 18:12:49,473] Trial 17 finished with value: 0.23599134490948756 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5688392530311949, 'min_weight_fraction_leaf': 0.3862403774000863}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24801473011738637
Fold 2 IBS: 0.23336726698773866
Fold 3 IBS: 0.22984121679333408
Fold 4 IBS: 0.24176299307832128
Fold 5 IBS: 0.23015950059445994
[I 2024-04-13 18:12:50,951] Trial 18 finished with value: 0.23662914151424808 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.053773653856063974}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2464616995792693
Fold 2 IBS: 0.23218447499282707
Fold 3 IBS: 0.2297960999906114
Fold 4 IBS: 0.24126238252144364
Fold 5 IBS: 0.2299756977580421
[I 2024-04-13 18:12:54,784] Trial 19 finished with value: 0.2359360709684387 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4078786025735315, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2356021274854339
Fold 2 IBS: 0.21736519916854574
Fold 3 IBS: 0.20646952344066247
Fold 4 IBS: 0.2281727318804719
Fold 5 IBS: 0.21322795644159553
[I 2024-04-13 18:13:04,721] Trial 20 finished with value: 0.22016750768334195 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 17, 'n_estimators': 310, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8887988952213425, 'min_weight_fraction_leaf': 0.16483895863649992}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2390208829210001
Fold 2 IBS: 0.21477636398758923
Fold 3 IBS: 0.2077575615094621
Fold 4 IBS: 0.22444376825518106
Fold 5 IBS: 0.20787997219697457
[I 2024-04-13 18:13:16,935] Trial 21 finished with value: 0.21877570977404143 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7050862172818282, 'min_weight_fraction_leaf': 0.08156751747114571}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2371332546390252
Fold 2 IBS: 0.21451079091509603
Fold 3 IBS: 0.20658616237101907
Fold 4 IBS: 0.2261028080781042
Fold 5 IBS: 0.20871606880123938
[I 2024-04-13 18:13:29,902] Trial 22 finished with value: 0.21860981696089682 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.10600930066685874}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24192493047866456
Fold 2 IBS: 0.21692042280147458
Fold 3 IBS: 0.20634554837219973
Fold 4 IBS: 0.22627161207172614
Fold 5 IBS: 0.20726148438799455
[I 2024-04-13 18:13:44,380] Trial 23 finished with value: 0.21974479962241192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6015263103836297, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23659856282659097
Fold 2 IBS: 0.2153141906947614
Fold 3 IBS: 0.2047151307497504
Fold 4 IBS: 0.22602716181430646
Fold 5 IBS: 0.21120163992617527
[I 2024-04-13 18:13:59,802] Trial 24 finished with value: 0.21877133720231692 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5266956821498789, 'min_weight_fraction_leaf': 0.09390422583252539}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23844194453158782
Fold 2 IBS: 0.22105165705465776
Fold 3 IBS: 0.2170232482052371
Fold 4 IBS: 0.23092368220074286
Fold 5 IBS: 0.2182289218147539
[I 2024-04-13 18:14:11,544] Trial 25 finished with value: 0.22513389076139587 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8933482791661949, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23843041914620997
Fold 2 IBS: 0.21493453665123136
Fold 3 IBS: 0.2090168989775049
Fold 4 IBS: 0.2254910625046002
Fold 5 IBS: 0.20756991091332164
[I 2024-04-13 18:14:24,302] Trial 26 finished with value: 0.21908856563857357 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 347, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7414002668859774, 'min_weight_fraction_leaf': 0.026829572042154526}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2509863618363121
Fold 2 IBS: 0.22583805299486692
Fold 3 IBS: 0.21561349580190237
Fold 4 IBS: 0.23472261674578385
Fold 5 IBS: 0.20529371711830646
[I 2024-04-13 18:14:38,991] Trial 27 finished with value: 0.22649084889943433 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8390104664094136, 'min_weight_fraction_leaf': 0.10855414664475099}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2365772151298969
Fold 2 IBS: 0.22063815968102357
Fold 3 IBS: 0.2096147193508314
Fold 4 IBS: 0.23073997606593633
Fold 5 IBS: 0.21495122402474376
[I 2024-04-13 18:14:48,022] Trial 28 finished with value: 0.22250425885048636 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7007032081941286, 'min_weight_fraction_leaf': 0.26392524970352815}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24016407858058467
Fold 2 IBS: 0.2226945998414404
Fold 3 IBS: 0.1982935820263817
Fold 4 IBS: 0.22729610646127874
Fold 5 IBS: 0.20737931045192012
[I 2024-04-13 18:15:06,014] Trial 29 finished with value: 0.21916553547232112 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 410, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5262281274916285, 'min_weight_fraction_leaf': 0.17911878131541542}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.24654710532719232
Fold 2 IBS: 0.23226075421028072
Fold 3 IBS: 0.22941657391206893
Fold 4 IBS: 0.24156072638580853
Fold 5 IBS: 0.23017807225897458
[I 2024-04-13 18:15:13,493] Trial 30 finished with value: 0.235992646418865 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.46244718326068934, 'min_weight_fraction_leaf': 0.23846812660748434}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23751141455085345
Fold 2 IBS: 0.2151581315756588
Fold 3 IBS: 0.20565940925991258
Fold 4 IBS: 0.22542469872025206
Fold 5 IBS: 0.21030193870732267
[I 2024-04-13 18:15:28,140] Trial 31 finished with value: 0.2188111185627999 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5225620293165905, 'min_weight_fraction_leaf': 0.08868790596579997}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2381102203756688
Fold 2 IBS: 0.21526872502739017
Fold 3 IBS: 0.20815181349325143
Fold 4 IBS: 0.22568325207479042
Fold 5 IBS: 0.20752434700582614
[I 2024-04-13 18:15:41,798] Trial 32 finished with value: 0.2189476715953854 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6456061991595886, 'min_weight_fraction_leaf': 0.06162501081375873}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23538871189809704
Fold 2 IBS: 0.2182700935995022
Fold 3 IBS: 0.20730561342400977
Fold 4 IBS: 0.22803214159636556
Fold 5 IBS: 0.21291133753496125
[I 2024-04-13 18:15:56,158] Trial 33 finished with value: 0.22038157961058716 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 448, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3962727024860553, 'min_weight_fraction_leaf': 0.11192391268789204}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23769165649579538
Fold 2 IBS: 0.21962693726644614
Fold 3 IBS: 0.21516823698710888
Fold 4 IBS: 0.22823472000435138
Fold 5 IBS: 0.21587988525872873
[I 2024-04-13 18:16:10,075] Trial 34 finished with value: 0.22332028720248612 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.48343209841746304, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23862457868154657
Fold 2 IBS: 0.2142812234274352
Fold 3 IBS: 0.2071122831600512
Fold 4 IBS: 0.22647037485357482
Fold 5 IBS: 0.20820984278000723
[I 2024-04-13 18:16:21,319] Trial 35 finished with value: 0.218939660580523 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 394, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6000897439208172, 'min_weight_fraction_leaf': 0.0750146307727606}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23527534950071421
Fold 2 IBS: 0.21770457187441952
Fold 3 IBS: 0.20717349733261567
Fold 4 IBS: 0.22755601352686636
Fold 5 IBS: 0.21265069320216293
[I 2024-04-13 18:16:33,716] Trial 36 finished with value: 0.22007202508735574 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 442, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6131815692772876, 'min_weight_fraction_leaf': 0.1532744134723093}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24634031246577748
Fold 2 IBS: 0.23214260646544588
Fold 3 IBS: 0.2295950257561111
Fold 4 IBS: 0.24153927533138653
Fold 5 IBS: 0.2302443599910423
[I 2024-04-13 18:16:46,726] Trial 37 finished with value: 0.23597231600195262 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7619772249693068, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24216929138044868
Fold 2 IBS: 0.2271496608003459
Fold 3 IBS: 0.2224602263879355
Fold 4 IBS: 0.23789330129911662
Fold 5 IBS: 0.22532476564253662
[I 2024-04-13 18:17:03,707] Trial 38 finished with value: 0.23099944910207665 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6857951951640623, 'min_weight_fraction_leaf': 0.32409862457821353}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24627778387618462
Fold 2 IBS: 0.2322366961912888
Fold 3 IBS: 0.2296783065766575
Fold 4 IBS: 0.241413702842104
Fold 5 IBS: 0.2304581252108405
[I 2024-04-13 18:17:17,567] Trial 39 finished with value: 0.23601292293941506 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.2617193500766202, 'min_weight_fraction_leaf': 0.4166327790117036}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24943554696253312
Fold 2 IBS: 0.2275875045421105
Fold 3 IBS: 0.21215397389232193
Fold 4 IBS: 0.22982351135831186
Fold 5 IBS: 0.20097345883924955
[I 2024-04-13 18:17:26,922] Trial 40 finished with value: 0.22399479911890538 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 340, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5581919117237532, 'min_weight_fraction_leaf': 0.017165868694093697}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23914122142491184
Fold 2 IBS: 0.2147947351479995
Fold 3 IBS: 0.20776744684188206
Fold 4 IBS: 0.22457253880359845
Fold 5 IBS: 0.20865162921459607
[I 2024-04-13 18:17:38,783] Trial 41 finished with value: 0.2189855142865976 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 416, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7054883344953605, 'min_weight_fraction_leaf': 0.0896503362548107}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24271681884333898
Fold 2 IBS: 0.21620524856789322
Fold 3 IBS: 0.20723319617238797
Fold 4 IBS: 0.22507744594615037
Fold 5 IBS: 0.20484080364572635
[I 2024-04-13 18:17:50,644] Trial 42 finished with value: 0.21921470263509937 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0480179528132343}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23614234446632862
Fold 2 IBS: 0.2146862138202214
Fold 3 IBS: 0.20617547040696596
Fold 4 IBS: 0.226976210049578
Fold 5 IBS: 0.2094767772998351
[I 2024-04-13 18:18:03,542] Trial 43 finished with value: 0.21869140320858582 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7262220752056259, 'min_weight_fraction_leaf': 0.12503295394556485}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23675493441717185
Fold 2 IBS: 0.2143052777671278
Fold 3 IBS: 0.20680963951540962
Fold 4 IBS: 0.22648948216139728
Fold 5 IBS: 0.20900398384520574
[I 2024-04-13 18:18:14,058] Trial 44 finished with value: 0.21867266354126244 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7563092184910359, 'min_weight_fraction_leaf': 0.12319485729503299}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23579057506686668
Fold 2 IBS: 0.21781214726067985
Fold 3 IBS: 0.2066254011517932
Fold 4 IBS: 0.22753811203645144
Fold 5 IBS: 0.2131782901601682
[I 2024-04-13 18:18:24,406] Trial 45 finished with value: 0.22018890513519188 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7526038702156265, 'min_weight_fraction_leaf': 0.19723066794982302}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23864304620933718
Fold 2 IBS: 0.2216376067444548
Fold 3 IBS: 0.21798786862601383
Fold 4 IBS: 0.2317000936375164
Fold 5 IBS: 0.21855619191514636
[I 2024-04-13 18:18:41,842] Trial 46 finished with value: 0.2257049614264937 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8402191071167949, 'min_weight_fraction_leaf': 0.12410909471677475}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23563878904947858
Fold 2 IBS: 0.21424725828314625
Fold 3 IBS: 0.20539301573051336
Fold 4 IBS: 0.22686230831823445
Fold 5 IBS: 0.21106465433851035
[I 2024-04-13 18:18:51,539] Trial 47 finished with value: 0.2186412051439766 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9648698685623813, 'min_weight_fraction_leaf': 0.16386048493715183}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23608296665281833
Fold 2 IBS: 0.21410238497896242
Fold 3 IBS: 0.20759570708434993
Fold 4 IBS: 0.22790237489945422
Fold 5 IBS: 0.21118066940259758
[I 2024-04-13 18:18:59,096] Trial 48 finished with value: 0.2193728206036365 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 188, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.964673069944489, 'min_weight_fraction_leaf': 0.15970031084197556}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23586798809596576
Fold 2 IBS: 0.2171901907305398
Fold 3 IBS: 0.20638917135134097
Fold 4 IBS: 0.22790269105933317
Fold 5 IBS: 0.2131331876876173
[I 2024-04-13 18:19:08,158] Trial 49 finished with value: 0.2200966457849594 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 257, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9370518091082483, 'min_weight_fraction_leaf': 0.2212372080269228}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23566720165017685
Fold 2 IBS: 0.21702158501775817
Fold 3 IBS: 0.20777305870793225
Fold 4 IBS: 0.2289923684746406
Fold 5 IBS: 0.2123285283685948
[I 2024-04-13 18:19:12,895] Trial 50 finished with value: 0.22035654844382052 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 131, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7996006309622741, 'min_weight_fraction_leaf': 0.17451620167795343}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23643320426918235
Fold 2 IBS: 0.21452872036487017
Fold 3 IBS: 0.2061667514710548
Fold 4 IBS: 0.22716532577885723
Fold 5 IBS: 0.2093136543684702
[I 2024-04-13 18:19:26,556] Trial 51 finished with value: 0.21872153125048693 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7348857113190044, 'min_weight_fraction_leaf': 0.12368563758615428}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23641193294091017
Fold 2 IBS: 0.21396216666253828
Fold 3 IBS: 0.205078775294875
Fold 4 IBS: 0.22790849339614294
Fold 5 IBS: 0.2096794545069518
[I 2024-04-13 18:19:36,059] Trial 52 finished with value: 0.21860816456028367 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 326, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8372294381144086, 'min_weight_fraction_leaf': 0.13938540553402562}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23760005782394428
Fold 2 IBS: 0.21366875869042135
Fold 3 IBS: 0.2069623183595147
Fold 4 IBS: 0.22721569193756555
Fold 5 IBS: 0.20902507159737838
[I 2024-04-13 18:19:50,057] Trial 53 finished with value: 0.21889437968176484 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.918667808078992, 'min_weight_fraction_leaf': 0.14156648297373461}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23620472019948477
Fold 2 IBS: 0.21446966517909544
Fold 3 IBS: 0.20562206377402104
Fold 4 IBS: 0.22725639394503946
Fold 5 IBS: 0.20996519098311808
[I 2024-04-13 18:19:59,450] Trial 54 finished with value: 0.21870360681615178 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8358880541378728, 'min_weight_fraction_leaf': 0.1455563484516374}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23778194706641292
Fold 2 IBS: 0.21478977024089968
Fold 3 IBS: 0.20765830208854946
Fold 4 IBS: 0.22627231039017479
Fold 5 IBS: 0.2078669168201539
[I 2024-04-13 18:20:10,786] Trial 55 finished with value: 0.21887384932123818 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7851303591277253, 'min_weight_fraction_leaf': 0.06284510067118923}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.238318805600092
Fold 2 IBS: 0.22036985262615907
Fold 3 IBS: 0.2165992463216147
Fold 4 IBS: 0.2309266992996685
Fold 5 IBS: 0.21739689485405828
[I 2024-04-13 18:20:23,922] Trial 56 finished with value: 0.2247222997403185 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 355, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8589971174200165, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23762260324765577
Fold 2 IBS: 0.21419387527655073
Fold 3 IBS: 0.20857668730339252
Fold 4 IBS: 0.22634390477297547
Fold 5 IBS: 0.20826155026277154
[I 2024-04-13 18:20:33,574] Trial 57 finished with value: 0.2189997241726692 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9941137040048004, 'min_weight_fraction_leaf': 0.10935256889677493}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24142086672900914
Fold 2 IBS: 0.2243832837390074
Fold 3 IBS: 0.20244005121729616
Fold 4 IBS: 0.22860275074756728
Fold 5 IBS: 0.20676442441603726
[I 2024-04-13 18:20:45,500] Trial 58 finished with value: 0.22072227536978345 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6659973923607253, 'min_weight_fraction_leaf': 0.19865253699408333}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23558756630217798
Fold 2 IBS: 0.21872232455633453
Fold 3 IBS: 0.20756590838487826
Fold 4 IBS: 0.2282798830709085
Fold 5 IBS: 0.21390900413228608
[I 2024-04-13 18:20:52,889] Trial 59 finished with value: 0.2208129372893171 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9225473764084263, 'min_weight_fraction_leaf': 0.28011468219630264}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23905204688392212
Fold 2 IBS: 0.2187928517163343
Fold 3 IBS: 0.2102452041922602
Fold 4 IBS: 0.22890896945323644
Fold 5 IBS: 0.21433456345556318
[I 2024-04-13 18:20:56,190] Trial 60 finished with value: 0.22226672714026327 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9528336631358474, 'min_weight_fraction_leaf': 0.23484468684942653}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23541239037810044
Fold 2 IBS: 0.2157600681640186
Fold 3 IBS: 0.20665073702737224
Fold 4 IBS: 0.22705259747647938
Fold 5 IBS: 0.2114858383168534
[I 2024-04-13 18:21:09,766] Trial 61 finished with value: 0.21927232627256482 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6192920945584268, 'min_weight_fraction_leaf': 0.13261707538267872}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23553068478795697
Fold 2 IBS: 0.21690255883493398
Fold 3 IBS: 0.20634487576033259
Fold 4 IBS: 0.227390495160599
Fold 5 IBS: 0.21190307127879016
[I 2024-04-13 18:21:23,749] Trial 62 finished with value: 0.21961433716452256 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 444, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7228469890997942, 'min_weight_fraction_leaf': 0.16736170087898403}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23652120509947278
Fold 2 IBS: 0.21376852115432401
Fold 3 IBS: 0.20590736185366215
Fold 4 IBS: 0.22699281211564268
Fold 5 IBS: 0.2094937208444956
[I 2024-04-13 18:21:33,799] Trial 63 finished with value: 0.2185367242135195 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6675371718016896, 'min_weight_fraction_leaf': 0.10480172755123676}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23556228893011497
Fold 2 IBS: 0.22097929403924785
Fold 3 IBS: 0.20991652841690608
Fold 4 IBS: 0.2296617728771541
Fold 5 IBS: 0.21512411988151653
[I 2024-04-13 18:21:44,981] Trial 64 finished with value: 0.22224880082898793 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6610936151946805, 'min_weight_fraction_leaf': 0.09922302854842845}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23828246171159492
Fold 2 IBS: 0.21557851298857106
Fold 3 IBS: 0.20938151683259248
Fold 4 IBS: 0.22533438744263723
Fold 5 IBS: 0.20920540651145889
[I 2024-04-13 18:21:52,588] Trial 65 finished with value: 0.21955645709737087 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 242, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.823446469666347, 'min_weight_fraction_leaf': 0.07059854704611815}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2364200039869531
Fold 2 IBS: 0.21438646307876086
Fold 3 IBS: 0.20573630300522222
Fold 4 IBS: 0.22702368533407957
Fold 5 IBS: 0.20961076514490226
[I 2024-04-13 18:22:03,552] Trial 66 finished with value: 0.2186354441099836 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5869176122888681, 'min_weight_fraction_leaf': 0.05075696238467242}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23639124735172928
Fold 2 IBS: 0.2145484268675974
Fold 3 IBS: 0.20522813470743728
Fold 4 IBS: 0.22671398387649164
Fold 5 IBS: 0.20934855998582716
[I 2024-04-13 18:22:14,860] Trial 67 finished with value: 0.21844607055781656 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 326, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6356340227566255, 'min_weight_fraction_leaf': 0.03968181972003887}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23657271370449404
Fold 2 IBS: 0.21804029729496446
Fold 3 IBS: 0.21045719072119984
Fold 4 IBS: 0.2270147984171555
Fold 5 IBS: 0.213512706028707
[I 2024-04-13 18:22:26,170] Trial 68 finished with value: 0.22111954123330416 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.574503516485792, 'min_weight_fraction_leaf': 0.0441948101443752}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23598252320933685
Fold 2 IBS: 0.21474373579441428
Fold 3 IBS: 0.20474033641872114
Fold 4 IBS: 0.22554630026453992
Fold 5 IBS: 0.21094491625082956
[I 2024-04-13 18:22:37,460] Trial 69 finished with value: 0.21839156238756835 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5838727235518294, 'min_weight_fraction_leaf': 0.024189353275833377}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23541761150477072
Fold 2 IBS: 0.21830744523559634
Fold 3 IBS: 0.2065414367985132
Fold 4 IBS: 0.22779205930266125
Fold 5 IBS: 0.21304401731614925
[I 2024-04-13 18:22:49,472] Trial 70 finished with value: 0.22022051403153814 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5116435605570427, 'min_weight_fraction_leaf': 0.025472119814750907}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2358050847465658
Fold 2 IBS: 0.21505617907633484
Fold 3 IBS: 0.20632041460134462
Fold 4 IBS: 0.2262324750390269
Fold 5 IBS: 0.20987569816898008
[I 2024-04-13 18:23:03,422] Trial 71 finished with value: 0.21865797032645046 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6369371661585259, 'min_weight_fraction_leaf': 0.011093571416785707}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23555223944807405
Fold 2 IBS: 0.21551046958229766
Fold 3 IBS: 0.2060538064107946
Fold 4 IBS: 0.2274823152167951
Fold 5 IBS: 0.21116980752977293
[I 2024-04-13 18:23:20,888] Trial 72 finished with value: 0.21915372763754687 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5939045307255605, 'min_weight_fraction_leaf': 0.034792886918428814}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23670318238684077
Fold 2 IBS: 0.2153132925145203
Fold 3 IBS: 0.20537237654935647
Fold 4 IBS: 0.2261310221764691
Fold 5 IBS: 0.21018749868962947
[I 2024-04-13 18:23:32,994] Trial 73 finished with value: 0.2187414744633632 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 304, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5785149488517107, 'min_weight_fraction_leaf': 0.05575349496200409}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23543448543686032
Fold 2 IBS: 0.21561006254005735
Fold 3 IBS: 0.20561005286053105
Fold 4 IBS: 0.22653019867698856
Fold 5 IBS: 0.21093122079808987
[I 2024-04-13 18:23:44,821] Trial 74 finished with value: 0.2188232040625054 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5392437858799007, 'min_weight_fraction_leaf': 0.020895543222114732}. Best is trial 6 with value: 0.21817221600733724.

Fold 1 IBS: 0.23749669116970254
Fold 2 IBS: 0.21417891364052918
Fold 3 IBS: 0.2066472918191204
Fold 4 IBS: 0.22577332010612122
Fold 5 IBS: 0.20791194308464916
[I 2024-04-13 18:23:57,508] Trial 75 finished with value: 0.2184016319640245 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6413926717278569, 'min_weight_fraction_leaf': 0.0007388507314896667}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23958121408927258
Fold 2 IBS: 0.21329051656876732
Fold 3 IBS: 0.20685348469946407
Fold 4 IBS: 0.2243628744610485
Fold 5 IBS: 0.2076885994354418
[I 2024-04-13 18:24:22,115] Trial 76 finished with value: 0.21835533785079883 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 356, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6743039221296488, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24100163497067753
Fold 2 IBS: 0.21650889905387713
Fold 3 IBS: 0.21047274820869846
Fold 4 IBS: 0.22336649691832314
Fold 5 IBS: 0.20606715188435837
[I 2024-04-13 18:24:38,554] Trial 77 finished with value: 0.2194833862071869 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 358, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.632010203513251, 'min_weight_fraction_leaf': 0.001409785112660406}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23901813243753778
Fold 2 IBS: 0.21420034022703563
Fold 3 IBS: 0.20592138789952324
Fold 4 IBS: 0.2261656080238036
Fold 5 IBS: 0.20847447185713558
[I 2024-04-13 18:24:54,590] Trial 78 finished with value: 0.21875598808900715 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 323, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6857241761843896, 'min_weight_fraction_leaf': 0.0754366403965388}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23824458885708127
Fold 2 IBS: 0.21347939433681554
Fold 3 IBS: 0.2058991068238864
Fold 4 IBS: 0.2257803593854211
Fold 5 IBS: 0.20757894565473192
[I 2024-04-13 18:25:09,961] Trial 79 finished with value: 0.21819647901158726 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6608586112588376, 'min_weight_fraction_leaf': 0.08475815384047584}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.2388143640724499
Fold 2 IBS: 0.21348020253653477
Fold 3 IBS: 0.20624726345211883
Fold 4 IBS: 0.22435505289042332
Fold 5 IBS: 0.208351275464022
[I 2024-04-13 18:25:25,582] Trial 80 finished with value: 0.2182496316831098 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 349, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5516495369043533, 'min_weight_fraction_leaf': 0.03371312562357193}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.24069746455152283
Fold 2 IBS: 0.21539743059063785
Fold 3 IBS: 0.20826874922746164
Fold 4 IBS: 0.22473981003915017
Fold 5 IBS: 0.20649625442496652
[I 2024-04-13 18:25:41,762] Trial 81 finished with value: 0.21911994176674782 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 347, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6667332489251124, 'min_weight_fraction_leaf': 0.03652699788238737}. Best is trial 6 with value: 0.21817221600733724.
Fold 1 IBS: 0.23772500283463666
Fold 2 IBS: 0.21351832416489283
Fold 3 IBS: 0.20551287071766666
Fold 4 IBS: 0.22528179451336483
Fold 5 IBS: 0.20855127007502566
[I 2024-04-13 18:26:00,144] Trial 82 finished with value: 0.2181178524611173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 348, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4957463321896789, 'min_weight_fraction_leaf': 0.06535039686542465}. Best is trial 82 with value: 0.2181178524611173.
Fold 1 IBS: 0.24006097861784914
Fold 2 IBS: 0.21351296780007356
Fold 3 IBS: 0.20665204769701515
Fold 4 IBS: 0.22153407083328364
Fold 5 IBS: 0.20571739381784554
[I 2024-04-13 18:26:15,424] Trial 83 finished with value: 0.21749549175321342 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 351, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44903497421134486, 'min_weight_fraction_leaf': 0.018023565445760347}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.24023569962199984
Fold 2 IBS: 0.21363622543199387
Fold 3 IBS: 0.2069585793435229
Fold 4 IBS: 0.2235635832191918
Fold 5 IBS: 0.2050944469518296
[I 2024-04-13 18:26:30,407] Trial 84 finished with value: 0.21789770691370763 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 354, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44193402534807985, 'min_weight_fraction_leaf': 0.01787990099131466}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23894349587532945
Fold 2 IBS: 0.21620007594047472
Fold 3 IBS: 0.20751928103028916
Fold 4 IBS: 0.22372208334469412
Fold 5 IBS: 0.20582866480542367
[I 2024-04-13 18:26:44,828] Trial 85 finished with value: 0.2184427201992422 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 355, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.3945684829871626, 'min_weight_fraction_leaf': 0.018652438671265613}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23559845633067017
Fold 2 IBS: 0.21576618470285996
Fold 3 IBS: 0.20576607771200886
Fold 4 IBS: 0.22613316143073034
Fold 5 IBS: 0.21134237173993053
[I 2024-04-13 18:27:01,800] Trial 86 finished with value: 0.21892125038323998 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44101859255864206, 'min_weight_fraction_leaf': 0.08385023506766573}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23685696539925846
Fold 2 IBS: 0.21480550862098527
Fold 3 IBS: 0.20596316091401243
Fold 4 IBS: 0.22582554770569668
Fold 5 IBS: 0.2089870418983674
[I 2024-04-13 18:27:17,286] Trial 87 finished with value: 0.2184876449076641 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 420, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.49032987293693886, 'min_weight_fraction_leaf': 0.06537420951395731}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.2372362315378745
Fold 2 IBS: 0.2141070051769487
Fold 3 IBS: 0.20515302733265592
Fold 4 IBS: 0.2254353766941232
Fold 5 IBS: 0.20982062489373873
[I 2024-04-13 18:27:27,695] Trial 88 finished with value: 0.2183504531270682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 299, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.45867249639615437, 'min_weight_fraction_leaf': 0.055491708389874855}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23930793105990758
Fold 2 IBS: 0.21398355058184887
Fold 3 IBS: 0.2034152708638187
Fold 4 IBS: 0.22450497150068674
Fold 5 IBS: 0.20720970388342935
[I 2024-04-13 18:27:38,625] Trial 89 finished with value: 0.21768428557793826 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4321447624251241, 'min_weight_fraction_leaf': 0.05093978805292204}. Best is trial 83 with value: 0.21749549175321342.

Fold 1 IBS: 0.23843719064657817
Fold 2 IBS: 0.22064066243477068
Fold 3 IBS: 0.216117076423818
Fold 4 IBS: 0.23057174337958733
Fold 5 IBS: 0.21778600564999445
[I 2024-04-13 18:27:49,269] Trial 90 finished with value: 0.22471053570694974 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.42143690848778903, 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23636584853089593
Fold 2 IBS: 0.2160409129934387
Fold 3 IBS: 0.20518796152371307
Fold 4 IBS: 0.22686151762465062
Fold 5 IBS: 0.21138354158709388
[I 2024-04-13 18:28:00,342] Trial 91 finished with value: 0.21916795645195847 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.37885824272597207, 'min_weight_fraction_leaf': 0.0831355986175214}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23869477691909374
Fold 2 IBS: 0.21407356247574796
Fold 3 IBS: 0.2063518174852807
Fold 4 IBS: 0.22368052234862068
Fold 5 IBS: 0.20756617101134753
[I 2024-04-13 18:28:11,746] Trial 92 finished with value: 0.2180733700480181 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4717145746375765, 'min_weight_fraction_leaf': 0.031712424866108854}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23869477691909374
Fold 2 IBS: 0.21407356247574796
Fold 3 IBS: 0.2063518174852807
Fold 4 IBS: 0.2237085330935343
Fold 5 IBS: 0.20694772259468203
[I 2024-04-13 18:28:22,616] Trial 93 finished with value: 0.21795528251366775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4672728524116875, 'min_weight_fraction_leaf': 0.011059612031062777}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23858095515316086
Fold 2 IBS: 0.21975164781209036
Fold 3 IBS: 0.21722961929030632
Fold 4 IBS: 0.23057130141512497
Fold 5 IBS: 0.21784545833330082
[I 2024-04-13 18:28:34,713] Trial 94 finished with value: 0.22479579640079664 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.34867843816025107, 'min_weight_fraction_leaf': 0.013031969056652583}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23786209898582975
Fold 2 IBS: 0.2150246994268266
Fold 3 IBS: 0.20529156517436606
Fold 4 IBS: 0.2250763776849818
Fold 5 IBS: 0.20845810397098258
[I 2024-04-13 18:28:46,713] Trial 95 finished with value: 0.21834256904859733 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4856085412705134, 'min_weight_fraction_leaf': 0.030125050021992245}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.25267952707924435
Fold 2 IBS: 0.22364036179533292
Fold 3 IBS: 0.21566522864655932
Fold 4 IBS: 0.2292360749986461
Fold 5 IBS: 0.20654056894732276
[I 2024-04-13 18:28:58,000] Trial 96 finished with value: 0.22555235229342108 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.432713162272765, 'min_weight_fraction_leaf': 0.038949501159838834}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23908189486059475
Fold 2 IBS: 0.21347457197868566
Fold 3 IBS: 0.2065066620897382
Fold 4 IBS: 0.22345877259235025
Fold 5 IBS: 0.20703900436678677
[I 2024-04-13 18:29:08,513] Trial 97 finished with value: 0.21791218117763114 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 245, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5036752163248778, 'min_weight_fraction_leaf': 0.009154320648984412}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.24118706264822834
Fold 2 IBS: 0.21292192130006443
Fold 3 IBS: 0.20750976633197557
Fold 4 IBS: 0.22523921978728415
Fold 5 IBS: 0.20766529155252064
[I 2024-04-13 18:29:15,330] Trial 98 finished with value: 0.21890465232401463 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 175, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5009566699282665, 'min_weight_fraction_leaf': 0.011093124694056673}. Best is trial 83 with value: 0.21749549175321342.
Fold 1 IBS: 0.23852012019920124
Fold 2 IBS: 0.2149463648078171
Fold 3 IBS: 0.20528180370133903
Fold 4 IBS: 0.22528602680304402
Fold 5 IBS: 0.20818529472185981
[I 2024-04-13 18:29:24,142] Trial 99 finished with value: 0.21844392204665222 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 241, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4667379070625426, 'min_weight_fraction_leaf': 0.04638622319247108}. Best is trial 83 with value: 0.21749549175321342.


* Best trial for IBS:
 FrozenTrial(number=83, state=TrialState.COMPLETE, values=[0.21749549175321342], datetime_start=datetime.datetime(2024, 4, 13, 18, 26, 0, 155542), datetime_complete=datetime.datetime(2024, 4, 13, 18, 26, 15, 423334), params={'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 351, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.44903497421134486, 'min_weight_fraction_leaf': 0.018023565445760347}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=83, value=None)


* Best Score for IBS:
 0.21749549175321342

In [80]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [81]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.217

#### Test

In [82]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [83]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=13, max_features=None, max_leaf_nodes=16,
                   max_samples=0.8020091028727125, min_samples_leaf=1,
                   min_samples_split=5,
                   min_weight_fraction_leaf=0.002435943155287043,
                   n_estimators=277, random_state=123, warm_start=True)

C-index score: 0.584

ExtraSurvivalTrees(max_depth=6, max_features='auto', max_leaf_nodes=16,
                   max_samples=0.44903497421134486, min_samples_leaf=4,
                   min_samples_split=9,
                   min_weight_fraction_leaf=0.018023565445760347,
                   n_estimators=351, oob_score=True, random_state=123)

IBS: 0.223

In [84]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [85]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:29:28,226] A new study created in memory with name: no-name-6ba7c145-2849-4b24-9b7a-a8cadeb49aa0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:30:30,370] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:31:08,521] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:31:41,785] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:32:31,259] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:32:53,928] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:32:59,884] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:33:49,549] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:34:02,996] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:34:04,488] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 18:36:04,217] Trial 9 finished with value: 0.6015092457236193 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:39:15,888] Trial 10 finished with value: 0.5915509861883201 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:42:50,777] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6015092457236193.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.5950570342205324
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 18:45:40,746] Trial 12 finished with value: 0.6059172111077464 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:47:07,806] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:49:06,380] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:50:52,417] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:52:00,679] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:54:22,274] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:57:42,014] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:57:51,812] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:59:10,067] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:02:01,642] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6059172111077464.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.6182170542635659
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 19:04:53,463] Trial 22 finished with value: 0.6190116704947725 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:07:04,794] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:09:00,779] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:10:08,102] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:12:40,567] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:15:15,029] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:17:26,854] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:19:12,565] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:21:13,048] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:24:57,023] Trial 31 finished with value: 0.5071713147410358 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:28:36,882] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:31:03,329] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:34:27,929] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:35:08,301] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:38:34,219] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:38:39,639] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.6190116704947725.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:39:53,010] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:41:47,555] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:12:19,876] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 20:12:20,291] Trial 41 finished with value: 0.6039152174760968 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.6190116704947725.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 20:12:35,572] Trial 42 finished with value: 0.624004230389207 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:12:36,277] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:13:19,768] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.624004230389207.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6520912547528517
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 20:13:36,683] Trial 45 finished with value: 0.6250855089268532 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:13:40,372] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.9097609675058456, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.14203864492290658, 'max_features': 0.1, 'min_impurity_decrease': 2.8410487814192134e-06, 'validation_fraction': 0.7106683919659889, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:14:06,404] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7952252972868074, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.20821540657294882, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.38084444238994586, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.8268165634838988, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:14:13,736] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.5738829075301064, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.2606631581830996, 'max_features': 0.1, 'min_impurity_decrease': 1.7788082392529892e-06, 'validation_fraction': 0.9003040994071866, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 17}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:14:14,260] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.84002245104845, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.17475217298119933, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.21302024967189928, 'max_features': 0.1, 'min_impurity_decrease': 5.682612317450774e-06, 'validation_fraction': 0.8796670771312719, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 45 with value: 0.6250855089268532.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:14:16,867] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.9569410534968725, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.1405973314616702, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.34344615267586504, 'max_features': 'log2', 'min_impurity_decrease': 1.89164645743038e-07, 'validation_fraction': 0.9611752371540778, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 45 with value: 0.6250855089268532.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:14:32,350] Trial 51 finished with value: 0.6344575916797196 and parameters: {'subsample': 0.4994582407940605, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.25361909697654017, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.30447335075613347, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4617573739462015e-07, 'validation_fraction': 0.6627564435796373, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6520912547528517
Fold 5 C-index: 0.5815450643776824
[I 2024-04-13 20:14:43,559] Trial 52 finished with value: 0.6158557441321629 and parameters: {'subsample': 0.44756554166704604, 'learning_rate': 0.008555924871488166, 'dropout_rate': 0.22725206143365784, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.3136607614940329, 'max_features': 'sqrt', 'min_impurity_decrease': 2.38579101418113e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:14:56,628] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.45456603531105677, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.26583914946975784, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.322074381929077, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0763963055081505e-06, 'validation_fraction': 0.6719316415566533, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:15:05,204] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.3984239460158819, 'learning_rate': 0.04823958197178553, 'dropout_rate': 0.37643214321044394, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.3013557556478156, 'max_features': 'sqrt', 'min_impurity_decrease': 2.871532477136697e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:15:17,188] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.5149754707590405, 'learning_rate': 0.006385731999605383, 'dropout_rate': 0.6373222391006226, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.22397272730341306, 'max_features': 'sqrt', 'min_impurity_decrease': 4.865634973369653e-07, 'validation_fraction': 0.7914357885759697, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:15:45,435] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.3411127486659095, 'learning_rate': 0.0223321562225781, 'dropout_rate': 0.23958844776950744, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.2741716094683543, 'max_features': 'sqrt', 'min_impurity_decrease': 2.219911700968688e-06, 'validation_fraction': 0.6090555519050711, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 51 with value: 0.6344575916797196.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 20:15:49,294] Trial 57 finished with value: 0.6424069440095804 and parameters: {'subsample': 0.569175138136116, 'learning_rate': 0.09542136158814303, 'dropout_rate': 0.43613571687055647, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.36743918461462793, 'max_features': 'sqrt', 'min_impurity_decrease': 5.255459802548745e-07, 'validation_fraction': 0.7087056989518657, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:15:52,205] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.5648293474899495, 'learning_rate': 0.09980513755713626, 'dropout_rate': 0.5821753276684661, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.33458212087172423, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.5649807819209639, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:16:04,651] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.43657835102234843, 'learning_rate': 0.08992223472821356, 'dropout_rate': 0.45063277335330026, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.8838088337816697, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': 'sqrt', 'min_impurity_decrease': 6.123519561880064e-07, 'validation_fraction': 0.7025023924419704, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:16:09,790] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.49892638282698937, 'learning_rate': 0.0441252798316586, 'dropout_rate': 0.5171243893297963, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.3630725265151832, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6800306990539567e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:16:12,292] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.2369113884490353, 'learning_rate': 0.08271570541393714, 'dropout_rate': 0.21451691891174118, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.2307646041947069, 'min_weight_fraction_leaf': 0.26954907827809993, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1677029771075378e-06, 'validation_fraction': 0.7413035176238272, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6178707224334601
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 20:16:24,809] Trial 62 finished with value: 0.6243825724756604 and parameters: {'subsample': 0.5324319523145695, 'learning_rate': 0.01643486305639612, 'dropout_rate': 0.3264939129108728, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.24162423168473884, 'max_features': 'sqrt', 'min_impurity_decrease': 5.949284725634976e-07, 'validation_fraction': 0.7732655768872577, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6254752851711026
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 20:16:35,805] Trial 63 finished with value: 0.6275044157901222 and parameters: {'subsample': 0.5420606625212961, 'learning_rate': 0.018319064135809617, 'dropout_rate': 0.3312179790226355, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.2368022589799896, 'max_features': 'sqrt', 'min_impurity_decrease': 4.941106122111233e-07, 'validation_fraction': 0.7618939807885664, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:16:49,590] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.5922191157066728, 'learning_rate': 0.017442858716414014, 'dropout_rate': 0.3280178810362676, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 0.3667438715407871, 'min_weight_fraction_leaf': 0.19573629323082295, 'max_features': 'sqrt', 'min_impurity_decrease': 5.391394394336536e-07, 'validation_fraction': 0.6858072881143848, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:17:19,933] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.48392926174632367, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.3644612457920643, 'n_estimators': 225, 'criterion': 'squared_error', 'ccp_alpha': 0.8992306864937782, 'min_weight_fraction_leaf': 0.2385628804937077, 'max_features': 'sqrt', 'min_impurity_decrease': 3.55046666349273e-07, 'validation_fraction': 0.6309388168212643, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:17:23,481] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.5415215192588256, 'learning_rate': 0.032278253162939315, 'dropout_rate': 0.2844754557689118, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.407601455379467, 'min_weight_fraction_leaf': 0.2510619510668375, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.7825933436627104, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:17:44,438] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.6358167678362362, 'learning_rate': 0.052737313658130634, 'dropout_rate': 0.4387694424787056, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4545757099622538, 'max_features': None, 'min_impurity_decrease': 1.818488684973112e-07, 'validation_fraction': 0.5736474971004745, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:18:30,255] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.5249117222273245, 'learning_rate': 0.02490094836729529, 'dropout_rate': 0.3029637523703682, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.761492090851228, 'min_weight_fraction_leaf': 0.4129240385085172, 'max_features': 1, 'min_impurity_decrease': 7.239759479397451e-07, 'validation_fraction': 0.845785642913146, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:18:49,772] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.4231153746657399, 'learning_rate': 0.08902302640166725, 'dropout_rate': 0.40768620718532717, 'n_estimators': 166, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2840361129928317, 'min_weight_fraction_leaf': 0.1815547729555989, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2923196091933695e-06, 'validation_fraction': 0.7183772506352457, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.5643776824034334
[I 2024-04-13 20:18:54,584] Trial 70 finished with value: 0.6131109792873616 and parameters: {'subsample': 0.33926313482601156, 'learning_rate': 0.019557263454050858, 'dropout_rate': 0.49890266623764207, 'n_estimators': 82, 'criterion': 'squared_error', 'ccp_alpha': 0.010011659094920826, 'min_weight_fraction_leaf': 0.2259853620596431, 'max_features': 0.1, 'min_impurity_decrease': 1.094279318090133e-06, 'validation_fraction': 0.6723348434604305, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.5793991416309013
[I 2024-04-13 20:19:05,898] Trial 71 finished with value: 0.6343473918763494 and parameters: {'subsample': 0.37769079309242687, 'learning_rate': 0.00898995266126416, 'dropout_rate': 0.18684567840646416, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.2872834031528035, 'max_features': 'sqrt', 'min_impurity_decrease': 2.080456918420355e-07, 'validation_fraction': 0.7690867806326959, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:19:18,519] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.37701900413921136, 'learning_rate': 0.016833919347681435, 'dropout_rate': 0.18636370764084237, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.6310212945452622, 'min_weight_fraction_leaf': 0.2884483320093426, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0402177319970213e-07, 'validation_fraction': 0.7660591402491591, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:19:32,907] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.5806779434269143, 'learning_rate': 0.009384484820913017, 'dropout_rate': 0.2682030763817523, 'n_estimators': 135, 'criterion': 'squared_error', 'ccp_alpha': 0.3563872779387915, 'min_weight_fraction_leaf': 0.259787767977606, 'max_features': 'sqrt', 'min_impurity_decrease': 4.1043899443022785e-07, 'validation_fraction': 0.8108999742101972, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:19:43,577] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6195349553052544, 'learning_rate': 0.01136765941654159, 'dropout_rate': 0.12372380197953392, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 1.1402294929472836, 'min_weight_fraction_leaf': 0.37161644050250525, 'max_features': 'log2', 'min_impurity_decrease': 1.932478849268343e-07, 'validation_fraction': 0.7239713755732545, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5278884462151394
Fold 2 C-index: 0.5872093023255814
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5722433460076045
Fold 5 C-index: 0.5493562231759657
[I 2024-04-13 20:20:03,318] Trial 75 finished with value: 0.5681905273746455 and parameters: {'subsample': 0.481615373319732, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.3420562942089014, 'n_estimators': 159, 'criterion': 'squared_error', 'ccp_alpha': 0.008766214931211122, 'min_weight_fraction_leaf': 0.47835629989654377, 'max_features': 'sqrt', 'min_impurity_decrease': 5.88233573662372e-07, 'validation_fraction': 0.8876968664466519, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:22,505] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5506572145582509, 'learning_rate': 0.005104240606853081, 'dropout_rate': 0.19147377223567788, 'n_estimators': 146, 'criterion': 'squared_error', 'ccp_alpha': 0.6753331414033272, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 1.568348033519598e-07, 'validation_fraction': 0.6381650425348908, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:27,547] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.256547470779639, 'learning_rate': 0.02789039050974412, 'dropout_rate': 0.2363063686780326, 'n_estimators': 69, 'criterion': 'squared_error', 'ccp_alpha': 0.32932872552363307, 'min_weight_fraction_leaf': 0.34020173052241, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0905215746242485e-07, 'validation_fraction': 0.8500050308736237, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:31,947] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.17121169705944425, 'learning_rate': 0.022303437932065042, 'dropout_rate': 0.16630563053057534, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.9868372140949613, 'min_weight_fraction_leaf': 0.28173667841308647, 'max_features': None, 'min_impurity_decrease': 1.436695348567125e-06, 'validation_fraction': 0.7954229312058925, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:35,479] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.6599350427093886, 'learning_rate': 0.013036654559152646, 'dropout_rate': 0.8831816560103296, 'n_estimators': 93, 'criterion': 'squared_error', 'ccp_alpha': 1.6751129651593017, 'min_weight_fraction_leaf': 0.441581660587461, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7645264662223318, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:05,876] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.29977879304875465, 'learning_rate': 0.006859503090223374, 'dropout_rate': 0.3089173374536066, 'n_estimators': 202, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 1, 'min_impurity_decrease': 5.0310685705020145e-06, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 20:21:18,692] Trial 81 finished with value: 0.6360661153873227 and parameters: {'subsample': 0.4294410193691395, 'learning_rate': 0.010148818964253115, 'dropout_rate': 0.23189880344496897, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.025429683198128432, 'min_weight_fraction_leaf': 0.30380613582651383, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4552322822660376e-07, 'validation_fraction': 0.7348375063409944, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:31,135] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.41270161792979404, 'learning_rate': 0.02035005618998148, 'dropout_rate': 0.2741217489218166, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.243253320453856, 'min_weight_fraction_leaf': 0.2674089734554558, 'max_features': 'sqrt', 'min_impurity_decrease': 4.57052340801651e-07, 'validation_fraction': 0.6937562552377796, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:59,397] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.5052537047036201, 'learning_rate': 0.010871661810425969, 'dropout_rate': 0.21433250003236387, 'n_estimators': 180, 'criterion': 'squared_error', 'ccp_alpha': 0.6352435481431712, 'min_weight_fraction_leaf': 0.24349664772118904, 'max_features': 'sqrt', 'min_impurity_decrease': 8.314878942494555e-07, 'validation_fraction': 0.6632105320618724, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:14,835] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.46801301624877634, 'learning_rate': 0.007281884918593935, 'dropout_rate': 0.386804997704391, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.2606549578206887, 'min_weight_fraction_leaf': 0.2996691407738805, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5246790132091148e-07, 'validation_fraction': 0.818415857489097, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 20:22:28,642] Trial 85 finished with value: 0.6408591126992382 and parameters: {'subsample': 0.5964612356115859, 'learning_rate': 0.015720448140553796, 'dropout_rate': 0.13380585132498796, 'n_estimators': 123, 'criterion': 'squared_error', 'ccp_alpha': 0.011079581402843635, 'min_weight_fraction_leaf': 0.3295331769680571, 'max_features': 'sqrt', 'min_impurity_decrease': 3.208077039170617e-07, 'validation_fraction': 0.919249699407904, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:43,723] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.3685613574811818, 'learning_rate': 0.014486753241218515, 'dropout_rate': 0.11824930345826798, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 0.6245182410574106, 'min_weight_fraction_leaf': 0.35109736831509497, 'max_features': 'sqrt', 'min_impurity_decrease': 2.86238317813556e-07, 'validation_fraction': 0.7634725122712285, 'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:45,424] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.6044611085530311, 'learning_rate': 0.01765378612903628, 'dropout_rate': 0.1306535468432557, 'n_estimators': 29, 'criterion': 'squared_error', 'ccp_alpha': 3.8278844875001683, 'min_weight_fraction_leaf': 0.3290577310546589, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3023259584270306e-07, 'validation_fraction': 0.7251193103463489, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:51,421] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.7305989887750208, 'learning_rate': 0.07565138947019595, 'dropout_rate': 0.16203184683029326, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 0.8448837855218826, 'min_weight_fraction_leaf': 0.3098036049135862, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1424217279362014e-07, 'validation_fraction': 0.8675111855922717, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:00,391] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.5376836855244629, 'learning_rate': 0.0401442321523931, 'dropout_rate': 0.24626353925068137, 'n_estimators': 101, 'criterion': 'squared_error', 'ccp_alpha': 6.012071113382355, 'min_weight_fraction_leaf': 0.3790584148504035, 'max_features': 'sqrt', 'min_impurity_decrease': 5.180798001423693e-07, 'validation_fraction': 0.6163739621016452, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:14,230] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.5603501314738726, 'learning_rate': 0.07155480696569975, 'dropout_rate': 0.19017023137156536, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.25113716915357387, 'min_weight_fraction_leaf': 0.29008477768989605, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8289185301981673, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 20:23:33,830] Trial 91 finished with value: 0.6369144725686089 and parameters: {'subsample': 0.5200014916305844, 'learning_rate': 0.004782889478178922, 'dropout_rate': 0.14625013043369223, 'n_estimators': 149, 'criterion': 'squared_error', 'ccp_alpha': 0.037948504220536555, 'min_weight_fraction_leaf': 0.32163517901334265, 'max_features': 0.1, 'min_impurity_decrease': 4.203506068959824e-07, 'validation_fraction': 0.928897907788923, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:46,576] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.516333042411373, 'learning_rate': 0.0032327242416098677, 'dropout_rate': 0.10130537225057253, 'n_estimators': 113, 'criterion': 'squared_error', 'ccp_alpha': 0.4942608677057209, 'min_weight_fraction_leaf': 0.31821001183548514, 'max_features': 0.1, 'min_impurity_decrease': 3.888780909297809e-07, 'validation_fraction': 0.9024177997549866, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5677290836653387
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 20:24:05,775] Trial 93 finished with value: 0.6306456063981358 and parameters: {'subsample': 0.4359031361693476, 'learning_rate': 0.004895517972361572, 'dropout_rate': 0.1441526685325705, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.047810054628039236, 'min_weight_fraction_leaf': 0.36100788200483613, 'max_features': 0.1, 'min_impurity_decrease': 7.26101398801591e-07, 'validation_fraction': 0.917180608138582, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:26,138] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.43676774220572834, 'learning_rate': 0.0014283823252091835, 'dropout_rate': 0.14353500981177236, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.23509570298593757, 'min_weight_fraction_leaf': 0.35954699845952287, 'max_features': 0.1, 'min_impurity_decrease': 9.183247049719965e-07, 'validation_fraction': 0.9236151177312523, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:33,645] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5903496783457474, 'learning_rate': 0.005099830953329844, 'dropout_rate': 0.162877773773529, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 1.2276086602633303, 'min_weight_fraction_leaf': 0.29823606696595584, 'max_features': 0.1, 'min_impurity_decrease': 1.9705823014691884e-06, 'validation_fraction': 0.6868552600932708, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:58,333] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.48032209804466314, 'learning_rate': 0.009204991859439446, 'dropout_rate': 0.22878123115737428, 'n_estimators': 176, 'criterion': 'squared_error', 'ccp_alpha': 0.49661607876323316, 'min_weight_fraction_leaf': 0.335851906616388, 'max_features': 0.1, 'min_impurity_decrease': 6.786376565092662e-07, 'validation_fraction': 0.1680801488969631, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.5234042553191489
Fold 4 C-index: 0.5532319391634981
Fold 5 C-index: 0.5
[I 2024-04-13 20:25:17,365] Trial 97 finished with value: 0.5331566962608705 and parameters: {'subsample': 0.35982713220118606, 'learning_rate': 0.012532616836197621, 'dropout_rate': 0.2558374395640585, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.16939533233444498, 'min_weight_fraction_leaf': 0.22889025888481507, 'max_features': 0.1, 'min_impurity_decrease': 1.3919863121994274e-06, 'validation_fraction': 0.42127972174310685, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 57 with value: 0.6424069440095804.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:25:27,242] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.3929305772442687, 'learning_rate': 0.006887776697371318, 'dropout_rate': 0.19837547852725088, 'n_estimators': 102, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9847646950448454, 'min_weight_fraction_leaf': 0.2740519671350756, 'max_features': 0.1, 'min_impurity_decrease': 3.145177514431871e-06, 'validation_fraction': 0.9698443216047068, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 57 with value: 0.6424069440095804.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6330798479087453

[I 2024-04-13 20:25:40,196] A new study created in memory with name: no-name-2a52ac0f-c829-44aa-9478-6374aefabeed

Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 20:25:40,166] Trial 99 finished with value: 0.6324701656733438 and parameters: {'subsample': 0.5315382628188576, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.3597460411167791, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.004509101673084638, 'min_weight_fraction_leaf': 0.3464439813387543, 'max_features': 0.1, 'min_impurity_decrease': 0.006030292379694477, 'validation_fraction': 0.5851189485426918, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 57 with value: 0.6424069440095804.


* Best trial for C-index:
 FrozenTrial(number=57, state=TrialState.COMPLETE, values=[0.6424069440095804], datetime_start=datetime.datetime(2024, 4, 13, 20, 15, 45, 441591), datetime_complete=datetime.datetime(2024, 4, 13, 20, 15, 49, 292582), params={'subsample': 0.569175138136116, 'learning_rate': 0.09542136158814303, 'dropout_rate': 0.43613571687055647, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.36743918461462793, 'max_features': 'sqrt', 'min_impurity_decrease': 5.255459802548745e-07, 'validation_fraction': 0.7087056989518657, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 20}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=57, value=None)


* Best Score for C-index:
 0.6424069440095804

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:26:33,338] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:27:03,596] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:27:36,958] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:28:23,714] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:28:43,805] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:28:48,825] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:29:35,275] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:29:48,891] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:29:50,609] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.2468985899268434
Fold 2 IBS: 0.23174237938551043
Fold 3 IBS: 0.22871218710228966
Fold 4 IBS: 0.24178909744475294
Fold 5 IBS: 0.22900564758396305
[I 2024-04-13 20:31:48,396] Trial 9 finished with value: 0.23562958028867192 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24711653291675975
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-13 20:35:00,353] Trial 10 finished with value: 0.23588805903156138 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:39:06,842] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24719666836842055
Fold 2 IBS: 0.23199892761841134
Fold 3 IBS: 0.2289405059322678
Fold 4 IBS: 0.24195423740028718
Fold 5 IBS: 0.22934315929810337
[I 2024-04-13 20:42:02,205] Trial 12 finished with value: 0.23588669972349807 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:43:22,599] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:45:15,188] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:46:52,718] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:47:58,020] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:50:12,474] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:53:33,092] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:53:41,832] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:54:51,554] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:57:27,166] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23562958028867192.
Fold 1 IBS: 0.24675967400526397
Fold 2 IBS: 0.23120128338106113

Fold 3 IBS: 0.22848569735194738
Fold 4 IBS: 0.24150141767716396
Fold 5 IBS: 0.22845766625525668
[I 2024-04-13 20:59:43,021] Trial 22 finished with value: 0.23528114773413863 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:01:26,533] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 21:03:06,132] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:04:10,565] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:06:16,128] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:08:21,110] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:09:58,763] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:11:05,429] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:12:21,696] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24723811107199292
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:14:47,081] Trial 31 finished with value: 0.23592604563741132 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:17:04,667] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:18:41,834] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:20:59,359] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:21:24,249] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:23:35,072] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:23:38,890] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:24:23,475] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:25:30,483] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:27:19,281] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.2472010209971281
Fold 2 IBS: 0.23197319933729893
Fold 3 IBS: 0.22887452934644678
Fold 4 IBS: 0.24191861956639799
Fold 5 IBS: 0.2293015642651888
[I 2024-04-13 21:27:19,738] Trial 41 finished with value: 0.23585378670249213 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528114773413863.
Fold 1 IBS: 0.2459047520616606
Fold 2 IBS: 0.23020388607917422
Fold 3 IBS: 0.22657568837307415
Fold 4 IBS: 0.24022980115273948
Fold 5 IBS: 0.22694242307333995
[I 2024-04-13 21:27:32,374] Trial 42 finished with value: 0.2339713101479977 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:27:33,200] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:28:07,569] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24678393645753394
Fold 2 IBS: 0.23045362112354736
Fold 3 IBS: 0.22798640772703402
Fold 4 IBS: 0.24133177588235574
Fold 5 IBS: 0.22819468131537443
[I 2024-04-13 21:28:19,968] Trial 45 finished with value: 0.2349500845011691 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:28:23,117] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.3747732962598691, 'max_features': 0.1, 'min_impurity_decrease': 2.6164901943280044e-07, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:28:45,448] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.3462595663974316, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:28:51,091] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.26066789839492466, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:28:51,876] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5232490206634685, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.3097478284829108, 'max_features': 0.1, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8421492954769574, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:28:53,721] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.14893065487391582, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.4771102452497172, 'max_features': 'log2', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24710183923742374
Fold 2 IBS: 0.23175516862597736
Fold 3 IBS: 0.22872726460533319
Fold 4 IBS: 0.24175918635636237
Fold 5 IBS: 0.22914324520488263
[I 2024-04-13 21:29:06,647] Trial 51 finished with value: 0.23569734080599586 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.22002902120871776, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0321764873923598e-06, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.2467504042903887
Fold 2 IBS: 0.23152649383902565
Fold 3 IBS: 0.2284064999332893
Fold 4 IBS: 0.2415574346408676
Fold 5 IBS: 0.22865959236570862
[I 2024-04-13 21:29:16,255] Trial 52 finished with value: 0.23538008501385596 and parameters: {'subsample': 0.7293363088819711, 'learning_rate': 0.021613492744160495, 'dropout_rate': 0.21988140341808987, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.21454208459463384, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968003047339178e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:26,840] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7286313887376499, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.285096973056326, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.2260580293041923, 'max_features': 'sqrt', 'min_impurity_decrease': 9.58735442301899e-07, 'validation_fraction': 0.810021403108459, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:35,725] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6569229035185145, 'learning_rate': 0.04372807230380943, 'dropout_rate': 0.21137526606647042, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.15200254659099177, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:55,213] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.804828042321909, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.23926982708415356, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.2779066644542128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:30:19,051] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6106355356441384, 'learning_rate': 0.0175381503002972, 'dropout_rate': 0.1840399348615831, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.21267322167989086, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6036201699627165e-06, 'validation_fraction': 0.6710340937437342, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:30:22,201] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7251306188899954, 'learning_rate': 0.031631325965124225, 'dropout_rate': 0.36858678707018233, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.8632300312068857, 'min_weight_fraction_leaf': 0.25226351016663784, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8530056448822852e-06, 'validation_fraction': 0.6117070368402964, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.2456293079267213
Fold 2 IBS: 0.23038922499302464
Fold 3 IBS: 0.22713476978355554
Fold 4 IBS: 0.24079478344550373
Fold 5 IBS: 0.22706044770206701
[I 2024-04-13 21:30:33,926] Trial 58 finished with value: 0.23420170677017443 and parameters: {'subsample': 0.8372135933826973, 'learning_rate': 0.0933118263896949, 'dropout_rate': 0.2698372192490325, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03851666886580376, 'min_weight_fraction_leaf': 0.19014956845126402, 'max_features': 'sqrt', 'min_impurity_decrease': 5.557667048245938e-07, 'validation_fraction': 0.8240957175887902, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:00,537] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8351680604992443, 'learning_rate': 0.09222489059205219, 'dropout_rate': 0.32342587723509275, 'n_estimators': 216, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.20200402270044698, 'max_features': None, 'min_impurity_decrease': 5.478860708687417e-07, 'validation_fraction': 0.7661283095999878, 'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:12,579] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9139271726204243, 'learning_rate': 0.09814896745797415, 'dropout_rate': 0.2791298710059678, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.7777615027127565, 'min_weight_fraction_leaf': 0.18715715168296215, 'max_features': 'sqrt', 'min_impurity_decrease': 2.755622066697515e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:18,662] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7785463441250284, 'learning_rate': 0.08303647143365385, 'dropout_rate': 0.22635143149642775, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.13431472354808824, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24566332108161124
Fold 2 IBS: 0.2296487832881736
Fold 3 IBS: 0.22657619429377132
Fold 4 IBS: 0.2401398958324181
Fold 5 IBS: 0.22612790182462805
[I 2024-04-13 21:31:29,031] Trial 62 finished with value: 0.23363121926412048 and parameters: {'subsample': 0.8243414389621114, 'learning_rate': 0.09071124103540035, 'dropout_rate': 0.27251764057548483, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.2309588671101351, 'max_features': 'sqrt', 'min_impurity_decrease': 5.801680351688828e-07, 'validation_fraction': 0.7943107726663929, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:31:35,894] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8543251428514922, 'learning_rate': 0.09031916747519456, 'dropout_rate': 0.4465947499448344, 'n_estimators': 113, 'criterion': 'squared_error', 'ccp_alpha': 0.31975094212728505, 'min_weight_fraction_leaf': 0.2681954377550372, 'max_features': 'sqrt', 'min_impurity_decrease': 5.414928507269899e-07, 'validation_fraction': 0.7758979815787878, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:56,611] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8301134299030771, 'learning_rate': 0.089407762408853, 'dropout_rate': 0.2603466948459836, 'n_estimators': 184, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.1898937646969936, 'max_features': 'sqrt', 'min_impurity_decrease': 1.69586486321652e-07, 'validation_fraction': 0.7972553997617144, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 62 with value: 0.23363121926412048.
Fold 1 IBS: 0.245287081913879
Fold 2 IBS: 0.2284909088203171
Fold 3 IBS: 0.22546650692785086
Fold 4 IBS: 0.2392357717231768
Fold 5 IBS: 0.2267792173870292
[I 2024-04-13 21:32:10,786] Trial 65 finished with value: 0.2330518973544506 and parameters: {'subsample': 0.7342676747848801, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.18564802790799603, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 0.0027779871092218425, 'min_weight_fraction_leaf': 0.23644250991622312, 'max_features': 1, 'min_impurity_decrease': 2.467126073460528e-06, 'validation_fraction': 0.6850220941695035, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:32:28,093] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7279386202897999, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.12777796849617917, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.4111498627316026, 'min_weight_fraction_leaf': 0.23517339076530247, 'max_features': 1, 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.6772907402354433, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:32:30,499] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8919877355885673, 'learning_rate': 0.08526801927485488, 'dropout_rate': 0.1968183597819077, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 2.319190851430798, 'min_weight_fraction_leaf': 0.15676195463630516, 'max_features': 1, 'min_impurity_decrease': 2.2029012366645964e-06, 'validation_fraction': 0.8599691724113316, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:33:08,707] Trial 68 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6777349272083631, 'learning_rate': 0.09580178908012703, 'dropout_rate': 0.17115105391870955, 'n_estimators': 231, 'criterion': 'squared_error', 'ccp_alpha': 1.05959995392391, 'min_weight_fraction_leaf': 0.09188917533116, 'max_features': 1, 'min_impurity_decrease': 6.249998507081008e-07, 'validation_fraction': 0.8273349120190413, 'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:33:22,246] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7597991740864205, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.3768812120719428, 'n_estimators': 171, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2840361129928317, 'min_weight_fraction_leaf': 0.18119508212683702, 'max_features': 1, 'min_impurity_decrease': 3.259077755824971e-06, 'validation_fraction': 0.5558704457196845, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.2457156227613367
Fold 2 IBS: 0.2288747857381832
Fold 3 IBS: 0.225909093321197
Fold 4 IBS: 0.23949137658530797
Fold 5 IBS: 0.22670374234424326
[I 2024-04-13 21:33:27,829] Trial 70 finished with value: 0.23333892415005364 and parameters: {'subsample': 0.9323981201987828, 'learning_rate': 0.07861759448846455, 'dropout_rate': 0.12174461012962215, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 0.010268271623930566, 'min_weight_fraction_leaf': 0.29906629929043166, 'max_features': 0.1, 'min_impurity_decrease': 1.3730886680414553e-06, 'validation_fraction': 0.7403543339118751, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.2460308029540508
Fold 2 IBS: 0.23075747711272837
Fold 3 IBS: 0.22719882472016173
Fold 4 IBS: 0.24096869520763853
Fold 5 IBS: 0.22665684264377603
[I 2024-04-13 21:33:40,515] Trial 71 finished with value: 0.2343225285276711 and parameters: {'subsample': 0.942796279417179, 'learning_rate': 0.07656513395335908, 'dropout_rate': 0.12688691191107251, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.30325824379899113, 'max_features': 0.1, 'min_impurity_decrease': 1.7123721653367992e-06, 'validation_fraction': 0.7399374904297116, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 21:33:46,344] Trial 72 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.958795520357544, 'learning_rate': 0.07365043020696545, 'dropout_rate': 0.12090349350270674, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.739835755767842, 'min_weight_fraction_leaf': 0.29749032069002146, 'max_features': 0.1, 'min_impurity_decrease': 1.3599018494932217e-06, 'validation_fraction': 0.7791089756643332, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:34:25,298] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9298981705927085, 'learning_rate': 0.08058367392340021, 'dropout_rate': 0.16799910589376849, 'n_estimators': 271, 'criterion': 'squared_error', 'ccp_alpha': 0.3563872779387915, 'min_weight_fraction_leaf': 0.3350043101424622, 'max_features': 0.1, 'min_impurity_decrease': 5.28840107794154e-06, 'validation_fraction': 0.7118987767425609, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:34:38,358] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8916344680923031, 'learning_rate': 0.08793435060481841, 'dropout_rate': 0.10110413499313342, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.955935636717823, 'min_weight_fraction_leaf': 0.3070562089185398, 'max_features': 0.1, 'min_impurity_decrease': 1.6710911545904498e-05, 'validation_fraction': 0.9115868102366969, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 12}. Best is trial 65 with value: 0.2330518973544506.
Fold 1 IBS: 0.24452621315746922
Fold 2 IBS: 0.22810872891299785
Fold 3 IBS: 0.2241439542595457
Fold 4 IBS: 0.23949321798155498
Fold 5 IBS: 0.2257119410390271
[I 2024-04-13 21:34:51,845] Trial 75 finished with value: 0.23239681107011897 and parameters: {'subsample': 0.9998829056403309, 'learning_rate': 0.09420039979456486, 'dropout_rate': 0.1333613034046263, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.008911991304216094, 'min_weight_fraction_leaf': 0.2444025476799629, 'max_features': 0.1, 'min_impurity_decrease': 2.4912576060277585e-06, 'validation_fraction': 0.6909543967814417, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:34:54,961] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9458222668472541, 'learning_rate': 0.07906848506975149, 'dropout_rate': 0.14266874960530737, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.6031748128205076, 'min_weight_fraction_leaf': 0.2411911402976509, 'max_features': 0.1, 'min_impurity_decrease': 2.563792903899382e-06, 'validation_fraction': 0.6884030004704251, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:08,068] Trial 77 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9912462777341369, 'learning_rate': 0.09452937387896818, 'dropout_rate': 0.13177704633811047, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 1.5888723787914292, 'min_weight_fraction_leaf': 0.2769591062921376, 'max_features': 0.1, 'min_impurity_decrease': 9.102476550268499e-06, 'validation_fraction': 0.6136526230702399, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 75 with value: 0.23239681107011897.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:29,990] Trial 78 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9982285661999424, 'learning_rate': 0.09191504218778693, 'dropout_rate': 0.15698726385072695, 'n_estimators': 197, 'criterion': 'squared_error', 'ccp_alpha': 0.24807516981478814, 'min_weight_fraction_leaf': 0.20156232220196313, 'max_features': 0.1, 'min_impurity_decrease': 1.657879625668623e-05, 'validation_fraction': 0.743279291715464, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24690614034739003
Fold 2 IBS: 0.23156150181893284
Fold 3 IBS: 0.22844484931909595
Fold 4 IBS: 0.24167312234765576
Fold 5 IBS: 0.22876368497640898
[I 2024-04-13 21:35:33,047] Trial 79 finished with value: 0.23546985976189672 and parameters: {'subsample': 0.8578713422305235, 'learning_rate': 0.0970337469468135, 'dropout_rate': 0.8831816560103296, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 0.00580501385319391, 'min_weight_fraction_leaf': 0.3274569717263011, 'max_features': 0.1, 'min_impurity_decrease': 1.7968062948599964e-06, 'validation_fraction': 0.567470377276655, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:37,195] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9640129259774958, 'learning_rate': 0.07781759349237542, 'dropout_rate': 0.684566586558272, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 0.7103134936897181, 'min_weight_fraction_leaf': 0.2530944848473559, 'max_features': 0.1, 'min_impurity_decrease': 4.17669457184032e-06, 'validation_fraction': 0.6634556365644301, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:53,512] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9095916255797919, 'learning_rate': 0.06970654000824406, 'dropout_rate': 0.18983665066947678, 'n_estimators': 161, 'criterion': 'squared_error', 'ccp_alpha': 0.23038409491076217, 'min_weight_fraction_leaf': 0.36124689664050524, 'max_features': 0.1, 'min_impurity_decrease': 7.661014914528512e-07, 'validation_fraction': 0.8089217409847281, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:06,407] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9338187920159751, 'learning_rate': 0.09334088664924992, 'dropout_rate': 0.16946680359086888, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 0.528502047033471, 'min_weight_fraction_leaf': 0.22951409277417695, 'max_features': 'log2', 'min_impurity_decrease': 2.9556370206003056e-07, 'validation_fraction': 0.8432783558982909, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:11,631] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.883398032137881, 'learning_rate': 0.05042245528279666, 'dropout_rate': 0.12497508422054361, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 0.19969398360318116, 'min_weight_fraction_leaf': 0.2656518803329823, 'max_features': 0.1, 'min_impurity_decrease': 1.4194947389027638e-06, 'validation_fraction': 0.633183021479895, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:29,556] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8552741665580803, 'learning_rate': 0.06709189419275205, 'dropout_rate': 0.23596409865551865, 'n_estimators': 177, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.2944874209342843, 'max_features': None, 'min_impurity_decrease': 7.691172257857441e-07, 'validation_fraction': 0.6968576998921013, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:36,292] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8223616874820779, 'learning_rate': 0.08843920709680371, 'dropout_rate': 0.10332840309562857, 'n_estimators': 98, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9490091297259651, 'min_weight_fraction_leaf': 0.24536912526579052, 'max_features': 0.1, 'min_impurity_decrease': 3.7435209342302184e-07, 'validation_fraction': 0.8704001971002521, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:00,533] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9096448812228937, 'learning_rate': 0.07363090940287254, 'dropout_rate': 0.1771840613769105, 'n_estimators': 199, 'criterion': 'squared_error', 'ccp_alpha': 1.2822592490338325, 'min_weight_fraction_leaf': 0.4080356436151848, 'max_features': 1, 'min_impurity_decrease': 3.0373401514275998e-06, 'validation_fraction': 0.49985049424795125, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.2466123733468312
Fold 2 IBS: 0.2308311526549613
Fold 3 IBS: 0.2278158354955089
Fold 4 IBS: 0.24119742239323982
Fold 5 IBS: 0.22757911535557646
[I 2024-04-13 21:37:03,185] Trial 87 finished with value: 0.23480717984922356 and parameters: {'subsample': 0.9651104076885627, 'learning_rate': 0.08682198289446316, 'dropout_rate': 0.26100822710445604, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.017727608136126588, 'min_weight_fraction_leaf': 0.2841999178157146, 'max_features': 0.1, 'min_impurity_decrease': 1.0918108718029517e-06, 'validation_fraction': 0.7910600961676841, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:05,848] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9779973422636488, 'learning_rate': 0.08293741938674638, 'dropout_rate': 0.3068106697632987, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.5807061908097002, 'min_weight_fraction_leaf': 0.28610769971029604, 'max_features': 0.1, 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.7618563886319779, 'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:07,197] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9483409389571185, 'learning_rate': 0.08684995291290751, 'dropout_rate': 0.261199231115212, 'n_estimators': 33, 'criterion': 'squared_error', 'ccp_alpha': 0.262026471967215, 'min_weight_fraction_leaf': 0.30628737845191195, 'max_features': 0.1, 'min_impurity_decrease': 6.315494653924259e-06, 'validation_fraction': 0.7881463591488752, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:37:17,412] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9683729112775776, 'learning_rate': 0.09017482809200965, 'dropout_rate': 0.3433400840232137, 'n_estimators': 130, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 0.1, 'min_impurity_decrease': 1.8289805873296154e-06, 'validation_fraction': 0.7322157194498431, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:25,518] Trial 91 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9249680605301084, 'learning_rate': 0.09924448444168336, 'dropout_rate': 0.20864759543371797, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 5.764943688998855, 'min_weight_fraction_leaf': 0.26522934614572513, 'max_features': 0.1, 'min_impurity_decrease': 1.0288742383976442e-06, 'validation_fraction': 0.8977628160008819, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.2451397278492685
Fold 2 IBS: 0.2300786103624261
Fold 3 IBS: 0.22666393768691476
Fold 4 IBS: 0.24040348182140334
Fold 5 IBS: 0.2268793016048305
[I 2024-04-13 21:37:30,272] Trial 92 finished with value: 0.23383301186496866 and parameters: {'subsample': 0.873531926988483, 'learning_rate': 0.061855558095227366, 'dropout_rate': 0.15093910401977667, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.04541226279610616, 'min_weight_fraction_leaf': 0.33303097856460795, 'max_features': 'log2', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.8296323120743014, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24512293945752534
Fold 2 IBS: 0.23019011787590957
Fold 3 IBS: 0.22745233212008534
Fold 4 IBS: 0.2407062153709357
Fold 5 IBS: 0.22743511430929209
[I 2024-04-13 21:37:35,282] Trial 93 finished with value: 0.23418134382674963 and parameters: {'subsample': 0.8748499727077871, 'learning_rate': 0.061988251437343184, 'dropout_rate': 0.13470215178905942, 'n_estimators': 79, 'criterion': 'squared_error', 'ccp_alpha': 0.04707905003515399, 'min_weight_fraction_leaf': 0.3395270240874814, 'max_features': 'log2', 'min_impurity_decrease': 1.9022958194070687e-07, 'validation_fraction': 0.8312538979092482, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:41,774] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7897088889184067, 'learning_rate': 0.0614181390618931, 'dropout_rate': 0.14297431919224673, 'n_estimators': 82, 'criterion': 'squared_error', 'ccp_alpha': 0.4431921498459426, 'min_weight_fraction_leaf': 0.3709400302504709, 'max_features': 'log2', 'min_impurity_decrease': 2.0363582833272814e-07, 'validation_fraction': 0.8286157671013741, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:44,223] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8731203767321374, 'learning_rate': 0.05536040983667881, 'dropout_rate': 0.1240871979011556, 'n_estimators': 51, 'criterion': 'squared_error', 'ccp_alpha': 0.7753599411924459, 'min_weight_fraction_leaf': 0.33956869589479877, 'max_features': 'log2', 'min_impurity_decrease': 1.5672686530530854e-07, 'validation_fraction': 0.8067764812355601, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:45,282] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8504494801502642, 'learning_rate': 0.049177216429585946, 'dropout_rate': 0.16179906586528384, 'n_estimators': 25, 'criterion': 'squared_error', 'ccp_alpha': 0.2411230962228951, 'min_weight_fraction_leaf': 0.33128063878378733, 'max_features': 'log2', 'min_impurity_decrease': 1.3361955454797523e-07, 'validation_fraction': 0.18910891405175134, 'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:51,969] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9456655169820907, 'learning_rate': 0.09471262982827017, 'dropout_rate': 0.1384749743969657, 'n_estimators': 95, 'criterion': 'squared_error', 'ccp_alpha': 1.0633542811136496, 'min_weight_fraction_leaf': 0.31666557556149805, 'max_features': 'log2', 'min_impurity_decrease': 4.764875181793167e-07, 'validation_fraction': 0.7602248674870157, 'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:56,466] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8985855612192725, 'learning_rate': 0.04236620589530157, 'dropout_rate': 0.10133681434331297, 'n_estimators': 71, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.3508714202084142, 'max_features': 'log2', 'min_impurity_decrease': 2.1425287177415118e-07, 'validation_fraction': 0.846288087406783, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 75 with value: 0.23239681107011897.
Fold 1 IBS: 0.24494631432468708
Fold 2 IBS: 0.228838334401351
Fold 3 IBS: 0.22532457276154536
Fold 4 IBS: 0.24000051436574654
Fold 5 IBS: 0.22609554166201715
[I 2024-04-13 21:38:04,174] Trial 99 finished with value: 0.23304105550306944 and parameters: {'subsample': 0.9788274478205877, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.18468364581870436, 'n_estimators': 106, 'criterion': 'squared_error', 'ccp_alpha': 0.004542076222843278, 'min_weight_fraction_leaf': 0.30062558075883816, 'max_features': 'log2', 'min_impurity_decrease': 3.1109850934465047e-07, 'validation_fraction': 0.8728143595545029, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 75 with value: 0.23239681107011897.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.23239681107011897], datetime_start=datetime.datetime(2024, 4, 13, 21, 34, 38, 364151), datetime_complete=datetime.datetime(2024, 4, 13, 21, 34, 51, 844175), params={'subsample': 0.9998829056403309, 'learning_rate': 0.09420039979456486, 'dropout_rate': 0.1333613034046263, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.008911991304216094, 'min_weight_fraction_leaf': 0.2444025476799629, 'max_features': 0.1, 'min_impurity_decrease': 2.4912576060277585e-06, 'validation_fraction': 0.6909543967814417, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 14}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.23239681107011897

In [86]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [87]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.642
train_ibs:  0.232

#### Test

In [88]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [89]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0019473494055538935,
                                 criterion='squared_error',
                                 dropout_rate=0.43613571687055647,
                                 learning_rate=0.09542136158814303,
                                 max_depth=20, max_features='sqrt',
                                 max_leaf_nodes=20,
                                 min_impurity_decrease=5.255459802548745e-07,
                                 min_samples_leaf=15, min_samples_split=10,
                                 min_weight_fraction_leaf=0.36743918461462793,
                                 n_estimators=66, random_state=123,
                                 subsample=0.569175138136116,
                                 validation_fraction=0.7087056989518657)

C-index score: 0.669

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008911991304216094,
                                 criterion='squared_error',
                                 dropout_rate=0.1333613034046263,
                                 learning_rate=0.09420039979456486,
                                 max_depth=14, max_features=0.1,
                                 max_leaf_nodes=19,
                                 min_impurity_decrease=2.4912576060277585e-06,
                                 min_samples_leaf=17, min_samples_split=7,
                                 min_weight_fraction_leaf=0.2444025476799629,
                                 n_estimators=141, random_state=123,
                                 subsample=0.9998829056403309,
                                 validation_fraction=0.6909543967814417)

IBS: 0.224

In [90]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [91]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [92]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 21:38:07,710] A new study created in memory with name: no-name-cbb1b423-0a8d-471c-82c8-73246b0d72e2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:38:09,659] Trial 0 finished with value: 0.5866142624492122 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:38:23,849] Trial 1 finished with value: 0.576446015578343 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:38:27,075] Trial 2 finished with value: 0.5809712199713649 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:38:31,511] Trial 3 finished with value: 0.5800896533816691 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:38:38,098] Trial 4 finished with value: 0.5877425333632083 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.5877425333632083.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:38:46,155] Trial 5 finished with value: 0.5755876464796306 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.5877425333632083.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:38:49,324] Trial 6 finished with value: 0.5755876464796306 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.5877425333632083.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:38:50,138] Trial 7 finished with value: 0.5833345326779854 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.5877425333632083.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:38:54,145] Trial 8 finished with value: 0.578591938325124 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.5877425333632083.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:39:05,230] Trial 9 finished with value: 0.5781664064102304 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.5877425333632083.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:39:12,707] Trial 10 finished with value: 0.5924732905302543 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.5924732905302543.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:39:22,259] Trial 11 finished with value: 0.6041381502991474 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6041381502991474.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:39:32,179] Trial 12 finished with value: 0.6048986065729117 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:39:43,106] Trial 13 finished with value: 0.574723627563861 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:39:51,647] Trial 14 finished with value: 0.6030265473888973 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:39:59,285] Trial 15 finished with value: 0.5953517509649073 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:40:14,255] Trial 16 finished with value: 0.597061734723298 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:40:26,158] Trial 17 finished with value: 0.5917969434797918 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:40:31,326] Trial 18 finished with value: 0.5829943054336748 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.6048986065729117.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5406976744186046
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:40:33,205] Trial 19 finished with value: 0.5937662023400497 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:40:47,113] Trial 20 finished with value: 0.5909949216328471 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:40:55,229] Trial 21 finished with value: 0.6021681782901848 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.7075879968118339, 'n_estimators': 348, 'learning_rate': 0.09588015704350664}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:41:01,519] Trial 22 finished with value: 0.5932658281043564 and parameters: {'subsample': 0.17037433318378448, 'dropout_rate': 0.764223918656215, 'n_estimators': 305, 'learning_rate': 0.09979249643444077}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:41:09,965] Trial 23 finished with value: 0.5941605536783087 and parameters: {'subsample': 0.1882001920901971, 'dropout_rate': 0.5767392416088596, 'n_estimators': 339, 'learning_rate': 0.09228487500058613}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:41:18,239] Trial 24 finished with value: 0.6014908973166834 and parameters: {'subsample': 0.10032123431548137, 'dropout_rate': 0.9684931648209879, 'n_estimators': 388, 'learning_rate': 0.0802723125714484}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:41:24,942] Trial 25 finished with value: 0.5835390219985771 and parameters: {'subsample': 0.3985041788703955, 'dropout_rate': 0.8139553387854312, 'n_estimators': 275, 'learning_rate': 0.06443481180783918}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:41:32,909] Trial 26 finished with value: 0.5862468206901484 and parameters: {'subsample': 0.30121747670186905, 'dropout_rate': 0.5707562654379044, 'n_estimators': 326, 'learning_rate': 0.089961888949938}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:41:38,061] Trial 27 finished with value: 0.5697806617843932 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.6421033114316845, 'n_estimators': 234, 'learning_rate': 0.04133902891970489}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:41:50,906] Trial 28 finished with value: 0.5922552013124134 and parameters: {'subsample': 0.20841538978394863, 'dropout_rate': 0.3080593480767576, 'n_estimators': 398, 'learning_rate': 0.014116661098438898}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:42:03,959] Trial 29 finished with value: 0.5738652584651485 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 443, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:42:06,500] Trial 30 finished with value: 0.5781664064102304 and parameters: {'subsample': 0.6496340242271839, 'dropout_rate': 0.16903977002361698, 'n_estimators': 133, 'learning_rate': 0.09303893229955305}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:42:14,669] Trial 31 finished with value: 0.6032080593571644 and parameters: {'subsample': 0.12927234629827838, 'dropout_rate': 0.7034575210854656, 'n_estimators': 348, 'learning_rate': 0.09363272084063057}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:42:20,979] Trial 32 finished with value: 0.5948847804636681 and parameters: {'subsample': 0.1554638386266163, 'dropout_rate': 0.7838509603078516, 'n_estimators': 294, 'learning_rate': 0.07998357406035848}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:42:29,633] Trial 33 finished with value: 0.5890864121860937 and parameters: {'subsample': 0.22307046077094378, 'dropout_rate': 0.4945623569173444, 'n_estimators': 347, 'learning_rate': 0.07050364648271915}. Best is trial 12 with value: 0.6048986065729117.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 21:42:30,124] Trial 34 finished with value: 0.6200383792472979 and parameters: {'subsample': 0.14154027296706004, 'dropout_rate': 0.644905787703748, 'n_estimators': 5, 'learning_rate': 0.09966139122330783}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:42:31,114] Trial 35 finished with value: 0.5841172354497576 and parameters: {'subsample': 0.2948496020489133, 'dropout_rate': 0.6287630133161572, 'n_estimators': 49, 'learning_rate': 0.07461987923632134}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:42:35,916] Trial 36 finished with value: 0.5976700270913309 and parameters: {'subsample': 0.15392899343129082, 'dropout_rate': 0.47827037248752946, 'n_estimators': 224, 'learning_rate': 0.091653872156113}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5321888412017167
[I 2024-04-13 21:42:36,404] Trial 37 finished with value: 0.5634488139682478 and parameters: {'subsample': 0.23690750281044962, 'dropout_rate': 0.8374055765137145, 'n_estimators': 1, 'learning_rate': 0.08398598098613289}. Best is trial 34 with value: 0.6200383792472979.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:42:37,840] Trial 38 finished with value: 0.5855527998084764 and parameters: {'subsample': 0.3139010416420267, 'dropout_rate': 0.297543464189074, 'n_estimators': 75, 'learning_rate': 0.07586972024157643}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:42:41,255] Trial 39 finished with value: 0.57893416795292 and parameters: {'subsample': 0.41872364564821285, 'dropout_rate': 0.5267513165392328, 'n_estimators': 159, 'learning_rate': 0.06892741183938003}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:42:48,753] Trial 40 finished with value: 0.5811670456212614 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.20013020077502125, 'n_estimators': 280, 'learning_rate': 0.09217068984316273}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:42:57,404] Trial 41 finished with value: 0.6039685156309286 and parameters: {'subsample': 0.13508836081899125, 'dropout_rate': 0.6875395326119147, 'n_estimators': 373, 'learning_rate': 0.0993939723603888}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5465116279069767
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:43:09,756] Trial 42 finished with value: 0.5980687309577293 and parameters: {'subsample': 0.15805964805992748, 'dropout_rate': 0.6132750054890997, 'n_estimators': 453, 'learning_rate': 0.09450142153621131}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:43:19,164] Trial 43 finished with value: 0.5969858646919605 and parameters: {'subsample': 0.13840274528511398, 'dropout_rate': 0.6828026328922265, 'n_estimators': 378, 'learning_rate': 0.08824261028176188}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:43:27,754] Trial 44 finished with value: 0.598416169683466 and parameters: {'subsample': 0.21887765388422142, 'dropout_rate': 0.13928344550648972, 'n_estimators': 322, 'learning_rate': 0.0963689949419925}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5174418604651163
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:43:31,125] Trial 45 finished with value: 0.587416365826857 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.9103264922802464, 'n_estimators': 189, 'learning_rate': 0.08346333852743308}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:43:39,353] Trial 46 finished with value: 0.5949210099520729 and parameters: {'subsample': 0.1850824085756943, 'dropout_rate': 0.7538924887760036, 'n_estimators': 367, 'learning_rate': 0.09913426791682374}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:43:44,202] Trial 47 finished with value: 0.6041100902000418 and parameters: {'subsample': 0.1311305982000336, 'dropout_rate': 0.6760801922171721, 'n_estimators': 244, 'learning_rate': 0.08846294453291483}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:43:48,944] Trial 48 finished with value: 0.5841855965077725 and parameters: {'subsample': 0.32680125991222236, 'dropout_rate': 0.6604314111556595, 'n_estimators': 244, 'learning_rate': 0.08826369202694169}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 21:43:49,477] Trial 49 finished with value: 0.585364242050707 and parameters: {'subsample': 0.19052763727317648, 'dropout_rate': 0.37489609338112606, 'n_estimators': 3, 'learning_rate': 0.07979658786776442}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:02,816] Trial 50 finished with value: 0.5886009024619208 and parameters: {'subsample': 0.2621631459165674, 'dropout_rate': 0.5983199448946451, 'n_estimators': 479, 'learning_rate': 0.08609095161059174}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:44:08,858] Trial 51 finished with value: 0.5945696757405887 and parameters: {'subsample': 0.14073320592421057, 'dropout_rate': 0.6788262019001075, 'n_estimators': 286, 'learning_rate': 0.09570993541362999}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:44:18,139] Trial 52 finished with value: 0.6047653283799326 and parameters: {'subsample': 0.1300455347257199, 'dropout_rate': 0.7442400087777848, 'n_estimators': 400, 'learning_rate': 0.08996672745116664}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:19,524] Trial 53 finished with value: 0.596754376817812 and parameters: {'subsample': 0.12235314965386802, 'dropout_rate': 0.804369322270398, 'n_estimators': 81, 'learning_rate': 0.08971428449773018}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:44:33,378] Trial 54 finished with value: 0.5985753420019014 and parameters: {'subsample': 0.19079403411043777, 'dropout_rate': 0.1199791728353166, 'n_estimators': 399, 'learning_rate': 0.09919211099272132}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:44:42,233] Trial 55 finished with value: 0.5981519062579922 and parameters: {'subsample': 0.10775071783618476, 'dropout_rate': 0.7475000628557074, 'n_estimators': 322, 'learning_rate': 0.08414616159150336}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:44:50,028] Trial 56 finished with value: 0.5957646415261 and parameters: {'subsample': 0.1688083954094651, 'dropout_rate': 0.5194091093440398, 'n_estimators': 262, 'learning_rate': 0.03662307623828449}. Best is trial 34 with value: 0.6200383792472979.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:45:03,953] Trial 57 finished with value: 0.5909949216328471 and parameters: {'subsample': 0.23861908434523887, 'dropout_rate': 0.5827415309274364, 'n_estimators': 439, 'learning_rate': 0.020570994628935912}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:45:16,045] Trial 58 finished with value: 0.5874726315479247 and parameters: {'subsample': 0.8150856000048525, 'dropout_rate': 0.878552334844019, 'n_estimators': 498, 'learning_rate': 0.05448254825409158}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:45:28,208] Trial 59 finished with value: 0.6065537884206281 and parameters: {'subsample': 0.10183265607410649, 'dropout_rate': 0.20704245528611398, 'n_estimators': 407, 'learning_rate': 0.09674362917618633}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:43,147] Trial 60 finished with value: 0.5926718494179527 and parameters: {'subsample': 0.2011068710343859, 'dropout_rate': 0.21040922160821865, 'n_estimators': 413, 'learning_rate': 0.07200825617838875}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:45:55,978] Trial 61 finished with value: 0.6047432855863221 and parameters: {'subsample': 0.13226338582400193, 'dropout_rate': 0.15916090783934952, 'n_estimators': 381, 'learning_rate': 0.0969806589518593}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:46:11,529] Trial 62 finished with value: 0.6017152069087415 and parameters: {'subsample': 0.10637687141780292, 'dropout_rate': 0.13781193441296968, 'n_estimators': 457, 'learning_rate': 0.09598877500601484}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:46:24,064] Trial 63 finished with value: 0.5974673200155655 and parameters: {'subsample': 0.16333228096348423, 'dropout_rate': 0.2652608648342137, 'n_estimators': 399, 'learning_rate': 0.09113692491123555}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6738197424892703
[I 2024-04-13 21:46:34,568] Trial 64 finished with value: 0.6075863642186825 and parameters: {'subsample': 0.10197413109462203, 'dropout_rate': 0.10314352524088966, 'n_estimators': 359, 'learning_rate': 0.08599784914924309}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:46:45,893] Trial 65 finished with value: 0.5886009024619208 and parameters: {'subsample': 0.2772316852523673, 'dropout_rate': 0.17026153335936856, 'n_estimators': 361, 'learning_rate': 0.04841446942458946}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:46:55,400] Trial 66 finished with value: 0.6092664490846464 and parameters: {'subsample': 0.10044908429402967, 'dropout_rate': 0.11043116324348753, 'n_estimators': 339, 'learning_rate': 0.09694888056744547}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:47:07,290] Trial 67 finished with value: 0.6065755343580175 and parameters: {'subsample': 0.10275069621685502, 'dropout_rate': 0.12519307034451777, 'n_estimators': 383, 'learning_rate': 0.09731693095116589}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:47:16,311] Trial 68 finished with value: 0.6059238771020409 and parameters: {'subsample': 0.1027231089451419, 'dropout_rate': 0.19634236995093982, 'n_estimators': 332, 'learning_rate': 0.09404698851143008}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:47:25,293] Trial 69 finished with value: 0.6033849992943084 and parameters: {'subsample': 0.17356487021643507, 'dropout_rate': 0.10156035072402259, 'n_estimators': 335, 'learning_rate': 0.09273641430580547}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:47:33,372] Trial 70 finished with value: 0.6033560750748288 and parameters: {'subsample': 0.10624120683751472, 'dropout_rate': 0.19285031082674842, 'n_estimators': 305, 'learning_rate': 0.06473690093408466}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:47:46,871] Trial 71 finished with value: 0.60089349114149 and parameters: {'subsample': 0.1542607812936044, 'dropout_rate': 0.22588319628538198, 'n_estimators': 423, 'learning_rate': 0.08587151245122639}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:47:58,885] Trial 72 finished with value: 0.6049819088600095 and parameters: {'subsample': 0.10278153622092179, 'dropout_rate': 0.1249523374353379, 'n_estimators': 389, 'learning_rate': 0.09997606614593385}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:48:08,099] Trial 73 finished with value: 0.6068651246447949 and parameters: {'subsample': 0.10320652347912251, 'dropout_rate': 0.1316633953104513, 'n_estimators': 341, 'learning_rate': 0.09710747692753213}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:48:18,085] Trial 74 finished with value: 0.6067746440756069 and parameters: {'subsample': 0.10141398565585663, 'dropout_rate': 0.13514047324338285, 'n_estimators': 356, 'learning_rate': 0.09734389838622101}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:48:28,106] Trial 75 finished with value: 0.5905821248591534 and parameters: {'subsample': 0.21561833780053427, 'dropout_rate': 0.2674439731372109, 'n_estimators': 360, 'learning_rate': 0.09368455480816681}. Best is trial 34 with value: 0.6200383792472979.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:48:37,438] Trial 76 finished with value: 0.6000425542985378 and parameters: {'subsample': 0.17643693739889343, 'dropout_rate': 0.15052634746448162, 'n_estimators': 340, 'learning_rate': 0.09736396773670239}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:48:47,113] Trial 77 finished with value: 0.6066843333758052 and parameters: {'subsample': 0.10010995182095893, 'dropout_rate': 0.17771784288698328, 'n_estimators': 317, 'learning_rate': 0.09439652311871655}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:48:57,394] Trial 78 finished with value: 0.6007628523988139 and parameters: {'subsample': 0.14782451437733712, 'dropout_rate': 0.23519966420336075, 'n_estimators': 319, 'learning_rate': 0.08234011808287832}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:49:07,704] Trial 79 finished with value: 0.5790247755089428 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.17316663113923902, 'n_estimators': 356, 'learning_rate': 0.09673624476597197}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:49:14,520] Trial 80 finished with value: 0.5885229362595987 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.13513221392418417, 'n_estimators': 296, 'learning_rate': 0.09120001508832987}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:49:22,738] Trial 81 finished with value: 0.5991151965943567 and parameters: {'subsample': 0.1269944206615514, 'dropout_rate': 0.18606648855202423, 'n_estimators': 329, 'learning_rate': 0.0944003282388674}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:49:32,386] Trial 82 finished with value: 0.6058185320213326 and parameters: {'subsample': 0.1025260812473107, 'dropout_rate': 0.2176438773206018, 'n_estimators': 371, 'learning_rate': 0.09410557186871348}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5329457364341085
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:49:42,060] Trial 83 finished with value: 0.6022442513902446 and parameters: {'subsample': 0.1514564168981855, 'dropout_rate': 0.30041751871331024, 'n_estimators': 344, 'learning_rate': 0.09785823475878958}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:49:51,678] Trial 84 finished with value: 0.5801875662066174 and parameters: {'subsample': 0.5584624909113933, 'dropout_rate': 0.1565436158097517, 'n_estimators': 310, 'learning_rate': 0.08657185098391303}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:50:04,060] Trial 85 finished with value: 0.5977315834410394 and parameters: {'subsample': 0.18503146629519968, 'dropout_rate': 0.11736496646893764, 'n_estimators': 409, 'learning_rate': 0.09438653313197391}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:50:14,409] Trial 86 finished with value: 0.5976668700104727 and parameters: {'subsample': 0.1312548615080103, 'dropout_rate': 0.42245060996076056, 'n_estimators': 388, 'learning_rate': 0.004148395637752787}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:50:21,016] Trial 87 finished with value: 0.6025956188010646 and parameters: {'subsample': 0.100869387808568, 'dropout_rate': 0.195938986382015, 'n_estimators': 275, 'learning_rate': 0.09766718897712195}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:50:34,227] Trial 88 finished with value: 0.604952857653695 and parameters: {'subsample': 0.15112640603513067, 'dropout_rate': 0.10101092894787654, 'n_estimators': 433, 'learning_rate': 0.09133838576388381}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 21:50:38,359] Trial 89 finished with value: 0.5899739262786198 and parameters: {'subsample': 0.20214023475335738, 'dropout_rate': 0.3254935072210337, 'n_estimators': 209, 'learning_rate': 0.09996801740225515}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:50:51,174] Trial 90 finished with value: 0.6009471913923823 and parameters: {'subsample': 0.12000560884029994, 'dropout_rate': 0.24988363295437988, 'n_estimators': 354, 'learning_rate': 0.08841067191046771}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:51:01,896] Trial 91 finished with value: 0.6000962545494299 and parameters: {'subsample': 0.1218724912329607, 'dropout_rate': 0.21727292115040195, 'n_estimators': 381, 'learning_rate': 0.09463574087052912}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:51:11,639] Trial 92 finished with value: 0.6024581924200184 and parameters: {'subsample': 0.1724772293520134, 'dropout_rate': 0.14436218585256516, 'n_estimators': 370, 'learning_rate': 0.09291268696300492}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:51:20,876] Trial 93 finished with value: 0.6058548884965723 and parameters: {'subsample': 0.10118441993837322, 'dropout_rate': 0.18107824469981904, 'n_estimators': 365, 'learning_rate': 0.09535638870532377}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5931558935361216

Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:51:28,628] Trial 94 finished with value: 0.600321555248697 and parameters: {'subsample': 0.1505464569004875, 'dropout_rate': 0.1703667743313485, 'n_estimators': 333, 'learning_rate': 0.09012862286314505}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:51:36,364] Trial 95 finished with value: 0.6009471913923823 and parameters: {'subsample': 0.12108957325422298, 'dropout_rate': 0.2786887530635508, 'n_estimators': 348, 'learning_rate': 0.09766020444438038}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:51:43,110] Trial 96 finished with value: 0.6048447793351847 and parameters: {'subsample': 0.13894857356692658, 'dropout_rate': 0.12556776118877908, 'n_estimators': 288, 'learning_rate': 0.0860629163825204}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 22:03:47,097] Trial 97 finished with value: 0.5697806617843932 and parameters: {'subsample': 0.9939501164643185, 'dropout_rate': 0.18231486663210175, 'n_estimators': 318, 'learning_rate': 0.05810785621442836}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 22:03:52,999] Trial 98 finished with value: 0.5964929227120275 and parameters: {'subsample': 0.22934912335168844, 'dropout_rate': 0.15828380020467475, 'n_estimators': 338, 'learning_rate': 0.08163149506623345}. Best is trial 34 with value: 0.6200383792472979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6121673003802282

[I 2024-04-13 22:04:00,904] A new study created in memory with name: no-name-1f622349-28b8-433a-9e6a-b0bfa5778ee3

Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 22:04:00,892] Trial 99 finished with value: 0.6049965193978599 and parameters: {'subsample': 0.10060881198071323, 'dropout_rate': 0.1165709580019774, 'n_estimators': 407, 'learning_rate': 0.07780243440139546}. Best is trial 34 with value: 0.6200383792472979.


* Best trial for C-index:
 FrozenTrial(number=34, state=TrialState.COMPLETE, values=[0.6200383792472979], datetime_start=datetime.datetime(2024, 4, 13, 21, 42, 29, 639765), datetime_complete=datetime.datetime(2024, 4, 13, 21, 42, 30, 124084), params={'subsample': 0.14154027296706004, 'dropout_rate': 0.644905787703748, 'n_estimators': 5, 'learning_rate': 0.09966139122330783}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=34, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.14154027296706004, 'dropout_rate': 0.644905787703748, 'n_estimators': 5, 'learning_rate': 0.09966139122330783}


* Best Score for C-index:
 0.6200383792472979

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2764983757259828
Fold 2 IBS: 0.25827328872655125
Fold 3 IBS: 0.2681918537299111
Fold 4 IBS: 0.25164204958791786
Fold 5 IBS: 0.23049650269649638
[I 2024-04-13 22:04:02,180] Trial 0 finished with value: 0.2570204140933719 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3324786566928669
Fold 2 IBS: 0.3788072699032086
Fold 3 IBS: 0.32206673578733985
Fold 4 IBS: 0.3101839972428508
Fold 5 IBS: 0.339376702626222
[I 2024-04-13 22:04:11,632] Trial 1 finished with value: 0.33658267245049767 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3080969081334638
Fold 2 IBS: 0.33679097151835613
Fold 3 IBS: 0.29794642580347785
Fold 4 IBS: 0.2970348516964966
Fold 5 IBS: 0.3098400786191256
[I 2024-04-13 22:04:13,589] Trial 2 finished with value: 0.309941847154184 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3064767874727317
Fold 2 IBS: 0.3619250483768896
Fold 3 IBS: 0.29817515853010107
Fold 4 IBS: 0.315877561499707
Fold 5 IBS: 0.266324370012311
[I 2024-04-13 22:03:55,886] Trial 3 finished with value: 0.3097557851783481 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.30482111083138314
Fold 2 IBS: 0.3648225665978812
Fold 3 IBS: 0.2990044094427698
Fold 4 IBS: 0.332431016434036
Fold 5 IBS: 0.27802626492667293
[I 2024-04-13 22:04:02,311] Trial 4 finished with value: 0.31582107364654866 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3330915321934708
Fold 2 IBS: 0.37508609294519507
Fold 3 IBS: 0.3171124043871855
Fold 4 IBS: 0.3137047618879898
Fold 5 IBS: 0.33923818447315957
[I 2024-04-13 22:04:06,996] Trial 5 finished with value: 0.33564659517740014 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.2582524703242828
Fold 2 IBS: 0.24410448346165017
Fold 3 IBS: 0.2489984543833783
Fold 4 IBS: 0.24105975122742593
Fold 5 IBS: 0.21760040361445157
[I 2024-04-13 22:04:09,092] Trial 6 finished with value: 0.24200311260223778 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.24200311260223778.
Fold 1 IBS: 0.24405440410530252
Fold 2 IBS: 0.2313144095096795
Fold 3 IBS: 0.2264872598945243
Fold 4 IBS: 0.2396665980161307
Fold 5 IBS: 0.21378036357257543
[I 2024-04-13 22:04:09,682] Trial 7 finished with value: 0.23106060701964246 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2721670320379247
Fold 2 IBS: 0.26349028676887165
Fold 3 IBS: 0.27256269344805145
Fold 4 IBS: 0.26295637706133196
Fold 5 IBS: 0.22443103181808433
[I 2024-04-13 22:04:17,641] Trial 8 finished with value: 0.25912148422685277 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.3247548329286031
Fold 2 IBS: 0.37802658126398786
Fold 3 IBS: 0.31858508252734163
Fold 4 IBS: 0.34094438731066296
Fold 5 IBS: 0.3390006997862931
[I 2024-04-13 22:07:50,059] Trial 9 finished with value: 0.34026231676337776 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.2320380130694877
Fold 3 IBS: 0.22856386796454758
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22906264846898927
[I 2024-04-13 22:07:50,568] Trial 10 finished with value: 0.2356827908284253 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24639976969987745
Fold 2 IBS: 0.23211191483262145
Fold 3 IBS: 0.22735462180753221
Fold 4 IBS: 0.24087071384643838
Fold 5 IBS: 0.2279748608955893
[I 2024-04-13 22:07:51,565] Trial 11 finished with value: 0.23494237621641179 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24224696569287882
Fold 2 IBS: 0.2411784713196448
Fold 3 IBS: 0.24105385824654812
Fold 4 IBS: 0.2660920323680352
Fold 5 IBS: 0.19773729473785187
[I 2024-04-13 22:07:52,434] Trial 12 finished with value: 0.23766172447299178 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24595650697573987
Fold 2 IBS: 0.23159750511026025
Fold 3 IBS: 0.22650743980304022
Fold 4 IBS: 0.2402759194782458
Fold 5 IBS: 0.2271234075322375
[I 2024-04-13 22:07:52,779] Trial 13 finished with value: 0.23429215577990475 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24578997040449777
Fold 2 IBS: 0.23848258024250096
Fold 3 IBS: 0.23923657468396856
Fold 4 IBS: 0.24712698608446457
Fold 5 IBS: 0.2057521648238833
[I 2024-04-13 22:07:53,958] Trial 14 finished with value: 0.23527765524786304 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.273062339353825
Fold 2 IBS: 0.2917310339898808
Fold 3 IBS: 0.2797674129217372
Fold 4 IBS: 0.27749936521479274
Fold 5 IBS: 0.22053219586335662
[I 2024-04-13 22:07:55,043] Trial 15 finished with value: 0.2685184694687185 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2872704124983099
Fold 2 IBS: 0.31661203946416167
Fold 3 IBS: 0.2727136606712885
Fold 4 IBS: 0.29594843425015543
Fold 5 IBS: 0.2113553851949947
[I 2024-04-13 22:07:58,396] Trial 16 finished with value: 0.27677998641578205 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24417753569669493
Fold 2 IBS: 0.23250586456391067
Fold 3 IBS: 0.22353591901388314
Fold 4 IBS: 0.2373942868900049
Fold 5 IBS: 0.22198742696468415
[I 2024-04-13 22:07:59,115] Trial 17 finished with value: 0.2319202066258356 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2546743281324155
Fold 2 IBS: 0.2466299808965928
Fold 3 IBS: 0.24423165608646885
Fold 4 IBS: 0.23899157625792516
Fold 5 IBS: 0.21624465931312048
[I 2024-04-13 22:08:03,823] Trial 18 finished with value: 0.24015444013730453 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24376155682470516
Fold 2 IBS: 0.23602577631297375

Fold 3 IBS: 0.23449904393194607
Fold 4 IBS: 0.243477517914051
Fold 5 IBS: 0.20898654378339646
[I 2024-04-13 22:08:05,334] Trial 19 finished with value: 0.23335008775341448 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.244476360186189
Fold 2 IBS: 0.2305472199436817
Fold 3 IBS: 0.22377140228384404
Fold 4 IBS: 0.2386766254699274
Fold 5 IBS: 0.22296335334244682
[I 2024-04-13 22:08:06,287] Trial 20 finished with value: 0.23208699224521778 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24513654608372853
Fold 2 IBS: 0.23094110628575634
Fold 3 IBS: 0.22464827063854145
Fold 4 IBS: 0.23926825072734292
Fold 5 IBS: 0.22475950483168106
[I 2024-04-13 22:08:07,060] Trial 21 finished with value: 0.23295073571341005 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24410368410205424
Fold 2 IBS: 0.23269100476640445
Fold 3 IBS: 0.22348442285008668
Fold 4 IBS: 0.23709008023572514
Fold 5 IBS: 0.2214330028375883
[I 2024-04-13 22:08:07,855] Trial 22 finished with value: 0.23176043895837178 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.7601905131808098, 'n_estimators': 57, 'learning_rate': 0.019334429052945145}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.27667017123091864
Fold 2 IBS: 0.26065061447392923
Fold 3 IBS: 0.26926155221797393
Fold 4 IBS: 0.2515347857203304
Fold 5 IBS: 0.24492971400337946
[I 2024-04-13 22:08:09,578] Trial 23 finished with value: 0.26060936752930636 and parameters: {'subsample': 0.8557281003254902, 'dropout_rate': 0.618865896035061, 'n_estimators': 150, 'learning_rate': 0.04186582141545488}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2440565511099749
Fold 2 IBS: 0.2333802807049335
Fold 3 IBS: 0.22381547481112268
Fold 4 IBS: 0.23631803336762525
Fold 5 IBS: 0.21989798922004192
[I 2024-04-13 22:08:10,340] Trial 24 finished with value: 0.23149366584273964 and parameters: {'subsample': 0.8736292350257677, 'dropout_rate': 0.9758883725345413, 'n_estimators': 56, 'learning_rate': 0.02427957701685606}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24363637213093994
Fold 2 IBS: 0.22964026459903003
Fold 3 IBS: 0.22364396916543722
Fold 4 IBS: 0.2400612844951756
Fold 5 IBS: 0.22076487111843845
[I 2024-04-13 22:08:10,977] Trial 25 finished with value: 0.23154935230180423 and parameters: {'subsample': 0.19468056412788132, 'dropout_rate': 0.9897789595635863, 'n_estimators': 40, 'learning_rate': 0.025002990823540957}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2448054095620852
Fold 2 IBS: 0.24089291457583237
Fold 3 IBS: 0.2422738795952799
Fold 4 IBS: 0.25647044007770636
Fold 5 IBS: 0.20292878970886452
[I 2024-04-13 22:08:14,183] Trial 26 finished with value: 0.23747428670395365 and parameters: {'subsample': 0.20966372435124492, 'dropout_rate': 0.9922976382051985, 'n_estimators': 92, 'learning_rate': 0.04553017387255954}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24315202579827286
Fold 2 IBS: 0.2296084891350833
Fold 3 IBS: 0.22297590716818474
Fold 4 IBS: 0.23944512448046287
Fold 5 IBS: 0.2201695165369695
[I 2024-04-13 22:08:14,924] Trial 27 finished with value: 0.23107021262379462 and parameters: {'subsample': 0.1957599112234488, 'dropout_rate': 0.9027419458320135, 'n_estimators': 35, 'learning_rate': 0.030307532796347948}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.267917851786008
Fold 2 IBS: 0.26933662189470964
Fold 3 IBS: 0.27564189612563983
Fold 4 IBS: 0.2691584475147244
Fold 5 IBS: 0.21790152434343574
[I 2024-04-13 22:08:17,464] Trial 28 finished with value: 0.2599912683329035 and parameters: {'subsample': 0.3829307089339019, 'dropout_rate': 0.9027419284965903, 'n_estimators': 226, 'learning_rate': 0.031981052358301974}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2792943097862194
Fold 2 IBS: 0.28556931713569095
Fold 3 IBS: 0.2821505463677021
Fold 4 IBS: 0.2767789833828095
Fold 5 IBS: 0.24243798706988048
[I 2024-04-13 22:08:18,938] Trial 29 finished with value: 0.27324622874846044 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.9065003057392301, 'n_estimators': 140, 'learning_rate': 0.06046208382653473}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24357693108568484
Fold 2 IBS: 0.24218272939230343
Fold 3 IBS: 0.24132125231604815
Fold 4 IBS: 0.25626701394258955
Fold 5 IBS: 0.20311620665004249
[I 2024-04-13 22:08:20,161] Trial 30 finished with value: 0.23729282667733367 and parameters: {'subsample': 0.19125168606591758, 'dropout_rate': 0.9409563623068649, 'n_estimators': 101, 'learning_rate': 0.04485591768174857}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24382549002608528
Fold 2 IBS: 0.22953741962639834
Fold 3 IBS: 0.22450248316098118
Fold 4 IBS: 0.23997590216291612
Fold 5 IBS: 0.2222267718560459
[I 2024-04-13 22:08:20,586] Trial 31 finished with value: 0.23201361336648535 and parameters: {'subsample': 0.28768044353640015, 'dropout_rate': 0.9934257769141778, 'n_estimators': 33, 'learning_rate': 0.027169563775584778}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24442487990305464
Fold 2 IBS: 0.22976183796621014
Fold 3 IBS: 0.22422539471726535
Fold 4 IBS: 0.23997184219231105
Fold 5 IBS: 0.2231569206031685
[I 2024-04-13 22:08:21,136] Trial 32 finished with value: 0.23230817507640192 and parameters: {'subsample': 0.19923791107667865, 'dropout_rate': 0.8492527565348026, 'n_estimators': 27, 'learning_rate': 0.02793143079798597}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24110172799394564
Fold 2 IBS: 0.23373373800635697
Fold 3 IBS: 0.2310089031480139
Fold 4 IBS: 0.25287602791181585
Fold 5 IBS: 0.20784812386345733
[I 2024-04-13 22:08:22,050] Trial 33 finished with value: 0.23331370418471792 and parameters: {'subsample': 0.25742548040487423, 'dropout_rate': 0.93574363487606, 'n_estimators': 82, 'learning_rate': 0.03613730268932275}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24354545464654423
Fold 2 IBS: 0.230168026458085
Fold 3 IBS: 0.22181857390015516
Fold 4 IBS: 0.24184184816789828
Fold 5 IBS: 0.2235185893072166
[I 2024-04-13 22:08:22,586] Trial 34 finished with value: 0.23217849849597988 and parameters: {'subsample': 0.13933416921115738, 'dropout_rate': 0.8122986313485964, 'n_estimators': 34, 'learning_rate': 0.020684756718428673}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24492143123864568
Fold 2 IBS: 0.2306174794818292
Fold 3 IBS: 0.22461884757145872
Fold 4 IBS: 0.24018027793155752
Fold 5 IBS: 0.22466717788798585
[I 2024-04-13 22:08:24,102] Trial 35 finished with value: 0.23300104282229536 and parameters: {'subsample': 0.44531889703598726, 'dropout_rate': 0.43975685710717877, 'n_estimators': 124, 'learning_rate': 0.004697598524347563}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2480128966846807
Fold 2 IBS: 0.24628511782972265
Fold 3 IBS: 0.24905290371698377
Fold 4 IBS: 0.26066683076060415
Fold 5 IBS: 0.20151446591935052
[I 2024-04-13 22:08:26,446] Trial 36 finished with value: 0.24110644298226838 and parameters: {'subsample': 0.22337163278162336, 'dropout_rate': 0.27769842371348924, 'n_estimators': 167, 'learning_rate': 0.02959804373282659}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24706099184494482
Fold 2 IBS: 0.2320394729244317
Fold 3 IBS: 0.22863918393203933
Fold 4 IBS: 0.24182619639717903
Fold 5 IBS: 0.22885466011167735
[I 2024-04-13 22:08:26,822] Trial 37 finished with value: 0.23568410104205445 and parameters: {'subsample': 0.5474487054361804, 'dropout_rate': 0.8700704650738815, 'n_estimators': 1, 'learning_rate': 0.059207327336158105}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.3622150499425198
Fold 2 IBS: 0.37871010991683224

Fold 3 IBS: 0.31041839361900425
Fold 4 IBS: 0.38439222893604497
Fold 5 IBS: 0.32738236379645497
[I 2024-04-13 22:08:34,730] Trial 38 finished with value: 0.3526236292421712 and parameters: {'subsample': 0.3278854808520768, 'dropout_rate': 0.13272164755980653, 'n_estimators': 381, 'learning_rate': 0.06814074928034364}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.29827692610119566
Fold 2 IBS: 0.282045562042545
Fold 3 IBS: 0.28301041532740556
Fold 4 IBS: 0.26637593036008284
Fold 5 IBS: 0.2779967799215671
[I 2024-04-13 22:08:36,613] Trial 39 finished with value: 0.2815411227505592 and parameters: {'subsample': 0.7834569849171229, 'dropout_rate': 0.9408456886999991, 'n_estimators': 179, 'learning_rate': 0.04617617206708862}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.324806407871569
Fold 2 IBS: 0.37786223186541407
Fold 3 IBS: 0.31482812552937167
Fold 4 IBS: 0.3227925487415433
Fold 5 IBS: 0.33867925222488654
[I 2024-04-13 22:08:45,435] Trial 40 finished with value: 0.3357937132465569 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.3088273722813278, 'n_estimators': 434, 'learning_rate': 0.050636797211465814}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24426723281547894
Fold 2 IBS: 0.23289853016280082
Fold 3 IBS: 0.2236295983081787
Fold 4 IBS: 0.23756689296906455
Fold 5 IBS: 0.22251206897375211
[I 2024-04-13 22:08:46,152] Trial 41 finished with value: 0.23217486464585502 and parameters: {'subsample': 0.9302231447488093, 'dropout_rate': 0.7621679356392955, 'n_estimators': 46, 'learning_rate': 0.020445248172885094}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24404669820941147
Fold 2 IBS: 0.2318665416872482
Fold 3 IBS: 0.22371420092809038
Fold 4 IBS: 0.23658177286474136
Fold 5 IBS: 0.219826097029707
[I 2024-04-13 22:08:47,115] Trial 42 finished with value: 0.2312070621438397 and parameters: {'subsample': 0.7983473089265306, 'dropout_rate': 0.6739144313604599, 'n_estimators': 78, 'learning_rate': 0.01738680387882011}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24395934002070968
Fold 2 IBS: 0.23247320402372404
Fold 3 IBS: 0.2235643785085121
Fold 4 IBS: 0.23687974185616034
Fold 5 IBS: 0.22028480691939
[I 2024-04-13 22:08:48,174] Trial 43 finished with value: 0.23143229426569922 and parameters: {'subsample': 0.7274191096933933, 'dropout_rate': 0.6477050821751402, 'n_estimators': 81, 'learning_rate': 0.015784958545820633}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24503355625506523
Fold 2 IBS: 0.23144795793581027
Fold 3 IBS: 0.22480585140346335
Fold 4 IBS: 0.2390059050966199
Fold 5 IBS: 0.22503657405473362
[I 2024-04-13 22:08:49,264] Trial 44 finished with value: 0.23306596894913847 and parameters: {'subsample': 0.7026509113834132, 'dropout_rate': 0.5020020877800176, 'n_estimators': 80, 'learning_rate': 0.007158437147656269}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2466623979801434
Fold 2 IBS: 0.2350654077614837
Fold 3 IBS: 0.23074437315281196
Fold 4 IBS: 0.23583894566508765
Fold 5 IBS: 0.21477857761048127
[I 2024-04-13 22:08:51,516] Trial 45 finished with value: 0.23261794043400158 and parameters: {'subsample': 0.775376097968604, 'dropout_rate': 0.6835074879866615, 'n_estimators': 153, 'learning_rate': 0.016418174530887893}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2548981692435651
Fold 2 IBS: 0.24181688927489273
Fold 3 IBS: 0.2456426727097321
Fold 4 IBS: 0.23898229189559322
Fold 5 IBS: 0.21541606321664913
[I 2024-04-13 22:08:52,946] Trial 46 finished with value: 0.23935121726808645 and parameters: {'subsample': 0.8165962063929625, 'dropout_rate': 0.6545891613433089, 'n_estimators': 116, 'learning_rate': 0.03359936538613975}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24462290978717607
Fold 2 IBS: 0.2310092867654879
Fold 3 IBS: 0.22463093093892436
Fold 4 IBS: 0.23883974510732903
Fold 5 IBS: 0.22463593339655108
[I 2024-04-13 22:08:53,441] Trial 47 finished with value: 0.2327477611990937 and parameters: {'subsample': 0.7240469426312591, 'dropout_rate': 0.7544111241433573, 'n_estimators': 16, 'learning_rate': 0.038652914223555324}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.25398032708319745
Fold 2 IBS: 0.24014020550590992
Fold 3 IBS: 0.24191606673918797
Fold 4 IBS: 0.23865906031083994
Fold 5 IBS: 0.21543305305389587
[I 2024-04-13 22:08:57,274] Trial 48 finished with value: 0.23802574253860623 and parameters: {'subsample': 0.9242479708427813, 'dropout_rate': 0.19701471782839963, 'n_estimators': 252, 'learning_rate': 0.01476220338770533}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.246152844649467
Fold 2 IBS: 0.2319907731815496
Fold 3 IBS: 0.226862010560269
Fold 4 IBS: 0.24059122245481523
Fold 5 IBS: 0.22753354166824832
[I 2024-04-13 22:10:41,224] Trial 49 finished with value: 0.23462607850286982 and parameters: {'subsample': 0.9418733601172077, 'dropout_rate': 0.5429236279246814, 'n_estimators': 81, 'learning_rate': 0.002964842317001738}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24898341818965988
Fold 2 IBS: 0.2384984014925951
Fold 3 IBS: 0.23729217921381884
Fold 4 IBS: 0.23761031571466212
Fold 5 IBS: 0.21370796359379096
[I 2024-04-13 22:10:42,494] Trial 50 finished with value: 0.23521845564090543 and parameters: {'subsample': 0.6810146883629442, 'dropout_rate': 0.5750286304571173, 'n_estimators': 106, 'learning_rate': 0.030091193360355515}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24304542427294154
Fold 2 IBS: 0.2302372902837267
Fold 3 IBS: 0.22302940674145172
Fold 4 IBS: 0.2419403736725874
Fold 5 IBS: 0.22086120855968697
[I 2024-04-13 22:10:43,108] Trial 51 finished with value: 0.2318227407060789 and parameters: {'subsample': 0.15463761508570414, 'dropout_rate': 0.6693418225991328, 'n_estimators': 38, 'learning_rate': 0.025887949018790976}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24553824136795213
Fold 2 IBS: 0.23079200406797137
Fold 3 IBS: 0.2257476126863363
Fold 4 IBS: 0.24063830467887706
Fold 5 IBS: 0.22602251225037961
[I 2024-04-13 22:10:43,584] Trial 52 finished with value: 0.23374773501030327 and parameters: {'subsample': 0.26154064534881144, 'dropout_rate': 0.9600633898082516, 'n_estimators': 20, 'learning_rate': 0.02183744524477562}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24397833488491502
Fold 2 IBS: 0.23118895191415523
Fold 3 IBS: 0.22350302503384625
Fold 4 IBS: 0.23746057747035523
Fold 5 IBS: 0.2205179367422004
[I 2024-04-13 22:10:44,203] Trial 53 finished with value: 0.23132976520909443 and parameters: {'subsample': 0.5140963857474901, 'dropout_rate': 0.907387615447933, 'n_estimators': 48, 'learning_rate': 0.02506723139711774}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2439685994256231
Fold 2 IBS: 0.2313080267137135
Fold 3 IBS: 0.22350298751291695
Fold 4 IBS: 0.23763094896604667
Fold 5 IBS: 0.22064484485600097
[I 2024-04-13 22:10:45,070] Trial 54 finished with value: 0.23141108149486023 and parameters: {'subsample': 0.5203264211745005, 'dropout_rate': 0.901092757680949, 'n_estimators': 72, 'learning_rate': 0.016538691332657496}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24372327135909228
Fold 2 IBS: 0.231811125825063
Fold 3 IBS: 0.226962681194465
Fold 4 IBS: 0.237871118683485
Fold 5 IBS: 0.2144779807707751
[I 2024-04-13 22:10:47,341] Trial 55 finished with value: 0.23096923556657606 and parameters: {'subsample': 0.4535959536237394, 'dropout_rate': 0.7382908715511307, 'n_estimators': 203, 'learning_rate': 0.010141673944727505}. Best is trial 55 with value: 0.23096923556657606.
Fold 1 IBS: 0.24383188291104219
Fold 2 IBS: 0.23171604361696976
Fold 3 IBS: 0.22480182864284456
Fold 4 IBS: 0.23768014300993978
Fold 5 IBS: 0.21741664003361508
[I 2024-04-13 22:10:51,848] Trial 56 finished with value: 0.2310893076428823 and parameters: {'subsample': 0.5226036504379501, 'dropout_rate': 0.736600926840097, 'n_estimators': 205, 'learning_rate': 0.008245690973017488}. Best is trial 55 with value: 0.23096923556657606.
Fold 1 IBS: 0.24367381871693775
Fold 2 IBS: 0.23171283299220616
Fold 3 IBS: 0.22678023470869738

Fold 4 IBS: 0.23784017371297209
Fold 5 IBS: 0.21485810066702843
[I 2024-04-13 22:10:53,952] Trial 57 finished with value: 0.23097303215956835 and parameters: {'subsample': 0.455497864682559, 'dropout_rate': 0.727615869586519, 'n_estimators': 198, 'learning_rate': 0.010247024954642935}. Best is trial 55 with value: 0.23096923556657606.
Fold 1 IBS: 0.24352828586762612
Fold 2 IBS: 0.2308324022950569
Fold 3 IBS: 0.22450011836087874
Fold 4 IBS: 0.23758666795918215
Fold 5 IBS: 0.217482896231864
[I 2024-04-13 22:10:56,345] Trial 58 finished with value: 0.23078607414292157 and parameters: {'subsample': 0.4626553192113092, 'dropout_rate': 0.7303672304395288, 'n_estimators': 204, 'learning_rate': 0.007862561293053814}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.24417328945183361
Fold 2 IBS: 0.23043766192154386
Fold 3 IBS: 0.22362240990011897
Fold 4 IBS: 0.23864400560218796
Fold 5 IBS: 0.22198895903862992
[I 2024-04-13 22:10:58,889] Trial 59 finished with value: 0.23177326518286287 and parameters: {'subsample': 0.45488158451395233, 'dropout_rate': 0.7270830532880908, 'n_estimators': 207, 'learning_rate': 0.004491323108595809}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.24392385334924088
Fold 2 IBS: 0.2322764507406139
Fold 3 IBS: 0.22918334171691965
Fold 4 IBS: 0.23972891630700452
Fold 5 IBS: 0.21311672058702
[I 2024-04-13 22:11:02,328] Trial 60 finished with value: 0.2316458565401598 and parameters: {'subsample': 0.432858414286227, 'dropout_rate': 0.8216282776289219, 'n_estimators': 281, 'learning_rate': 0.008326946733370966}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.24470726494855266
Fold 2 IBS: 0.2333054308270637
Fold 3 IBS: 0.23057462966327621
Fold 4 IBS: 0.23901861783901446
Fold 5 IBS: 0.21269225629823368
[I 2024-04-13 22:11:05,011] Trial 61 finished with value: 0.23205963991522816 and parameters: {'subsample': 0.477125199296295, 'dropout_rate': 0.7708521854884218, 'n_estimators': 225, 'learning_rate': 0.011214655875406286}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.2429021771458493
Fold 2 IBS: 0.2315935634669122
Fold 3 IBS: 0.2268386463774016
Fold 4 IBS: 0.23961518166685983
Fold 5 IBS: 0.21330998892776806
[I 2024-04-13 22:11:07,196] Trial 62 finished with value: 0.2308519115169582 and parameters: {'subsample': 0.365725926598657, 'dropout_rate': 0.7239220288645943, 'n_estimators': 192, 'learning_rate': 0.011072225602391269}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.24630147076884942
Fold 2 IBS: 0.2315190903239987
Fold 3 IBS: 0.227088576841753
Fold 4 IBS: 0.24097424882483512
Fold 5 IBS: 0.22777278189024497
[I 2024-04-13 22:11:09,450] Trial 63 finished with value: 0.23473123372993623 and parameters: {'subsample': 0.5756097758499169, 'dropout_rate': 0.7289657639078007, 'n_estimators': 193, 'learning_rate': 0.0010688465088750819}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.24342854896178023
Fold 2 IBS: 0.23338586009746928
Fold 3 IBS: 0.23031930862820332
Fold 4 IBS: 0.24070866276800731
Fold 5 IBS: 0.21096702031679987
[I 2024-04-13 22:11:12,519] Trial 64 finished with value: 0.231761880154452 and parameters: {'subsample': 0.36292988192999437, 'dropout_rate': 0.7059467142696543, 'n_estimators': 239, 'learning_rate': 0.010732091546214175}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.2427829519155512
Fold 2 IBS: 0.23165056250196492
Fold 3 IBS: 0.2277906582406018
Fold 4 IBS: 0.23964250057184744
Fold 5 IBS: 0.21349855761887526
[I 2024-04-13 22:11:16,477] Trial 65 finished with value: 0.23107304616976815 and parameters: {'subsample': 0.408657445465784, 'dropout_rate': 0.7826681310745337, 'n_estimators': 301, 'learning_rate': 0.007200318304061353}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.3181059450103985
Fold 2 IBS: 0.37325120115235383
Fold 3 IBS: 0.3095353511097871
Fold 4 IBS: 0.32473995380006865
Fold 5 IBS: 0.33161663184564766
[I 2024-04-13 22:11:20,871] Trial 66 finished with value: 0.33144981658365114 and parameters: {'subsample': 0.4115665797504302, 'dropout_rate': 0.7877262423512951, 'n_estimators': 317, 'learning_rate': 0.054949393573763966}. Best is trial 58 with value: 0.23078607414292157.
Fold 1 IBS: 0.2425019585663978
Fold 2 IBS: 0.23072197911998302
Fold 3 IBS: 0.2255791465132325
Fold 4 IBS: 0.23940044804755095
Fold 5 IBS: 0.2144198505164033
[I 2024-04-13 22:11:25,741] Trial 67 finished with value: 0.2305246765527135 and parameters: {'subsample': 0.35814936289595134, 'dropout_rate': 0.604986146999221, 'n_estimators': 310, 'learning_rate': 0.006338930484056821}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.2427026098219161
Fold 2 IBS: 0.22988296146960918
Fold 3 IBS: 0.22313269791467563
Fold 4 IBS: 0.23936142014507536
Fold 5 IBS: 0.2184524617435681
[I 2024-04-13 22:11:29,256] Trial 68 finished with value: 0.2307064302189689 and parameters: {'subsample': 0.2927387568792692, 'dropout_rate': 0.6150916209055994, 'n_estimators': 255, 'learning_rate': 0.0054938213952834105}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.3344010101655214
Fold 2 IBS: 0.37825428760543983
Fold 3 IBS: 0.3131907286744586
Fold 4 IBS: 0.36125547728570645
Fold 5 IBS: 0.3317708577900307
[I 2024-04-13 22:11:33,328] Trial 69 finished with value: 0.3437744723042314 and parameters: {'subsample': 0.29626331402698675, 'dropout_rate': 0.6060903085911246, 'n_estimators': 255, 'learning_rate': 0.08403050744828938}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24880075129239915
Fold 2 IBS: 0.2437415689665589
Fold 3 IBS: 0.24969912949562142
Fold 4 IBS: 0.25056673944052404
Fold 5 IBS: 0.20473994022901743
[I 2024-04-13 22:11:39,375] Trial 70 finished with value: 0.23950962588482422 and parameters: {'subsample': 0.35428244080878746, 'dropout_rate': 0.6314893487349578, 'n_estimators': 345, 'learning_rate': 0.012954900416772192}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.2430171551348362
Fold 2 IBS: 0.23006885913009276
Fold 3 IBS: 0.22366832731867745
Fold 4 IBS: 0.2389455307217085
Fold 5 IBS: 0.2184002424806333
[I 2024-04-13 22:11:43,338] Trial 71 finished with value: 0.23082002295718965 and parameters: {'subsample': 0.37104298081980164, 'dropout_rate': 0.5615985854211485, 'n_estimators': 266, 'learning_rate': 0.005163036601524486}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24262811629529932
Fold 2 IBS: 0.2300718221116769
Fold 3 IBS: 0.22349494280025423
Fold 4 IBS: 0.2392698101539137
Fold 5 IBS: 0.2175760233718199
[I 2024-04-13 22:11:47,605] Trial 72 finished with value: 0.2306081429465928 and parameters: {'subsample': 0.313800374284032, 'dropout_rate': 0.5783257812820497, 'n_estimators': 280, 'learning_rate': 0.005448564631377113}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24319427516504843
Fold 2 IBS: 0.22990708061293527
Fold 3 IBS: 0.22324580562386573
Fold 4 IBS: 0.23910856139363634
Fold 5 IBS: 0.2194459031511584
[I 2024-04-13 22:11:51,638] Trial 73 finished with value: 0.23098032518932884 and parameters: {'subsample': 0.30872502062298757, 'dropout_rate': 0.569295603524688, 'n_estimators': 271, 'learning_rate': 0.004495925134887183}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24298919923216314
Fold 2 IBS: 0.23037349455349165
Fold 3 IBS: 0.2238912469926725
Fold 4 IBS: 0.23876883992235332
Fold 5 IBS: 0.21779024457960047
[I 2024-04-13 22:12:36,508] Trial 74 finished with value: 0.2307626050560562 and parameters: {'subsample': 0.3787505640355472, 'dropout_rate': 0.5018065521020472, 'n_estimators': 233, 'learning_rate': 0.006310731334993578}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.242901942693904
Fold 2 IBS: 0.23042137613405883
Fold 3 IBS: 0.2239488311001659
Fold 4 IBS: 0.23964398396284492
Fold 5 IBS: 0.21716223592185127
[I 2024-04-13 22:12:39,589] Trial 75 finished with value: 0.230815673962565 and parameters: {'subsample': 0.34555346445628665, 'dropout_rate': 0.5031488132234821, 'n_estimators': 232, 'learning_rate': 0.0066395271357698495}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24320023160826354
Fold 2 IBS: 0.23013484460370975
Fold 3 IBS: 0.22377029236884888

Fold 4 IBS: 0.24011681767071918
Fold 5 IBS: 0.2180561497748414
[I 2024-04-13 22:12:45,001] Trial 76 finished with value: 0.23105566720527654 and parameters: {'subsample': 0.3447701607161631, 'dropout_rate': 0.44910581572830965, 'n_estimators': 235, 'learning_rate': 0.006014704236887859}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24517753021026703
Fold 2 IBS: 0.23065498965579573
Fold 3 IBS: 0.22488935552274253
Fold 4 IBS: 0.24047333252997696
Fold 5 IBS: 0.22503321076794347
[I 2024-04-13 22:12:49,832] Trial 77 finished with value: 0.23324568373734517 and parameters: {'subsample': 0.37306059300005784, 'dropout_rate': 0.48805498613846665, 'n_estimators': 303, 'learning_rate': 0.0017196299707487941}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.2440642480926844
Fold 2 IBS: 0.23788853785096567
Fold 3 IBS: 0.23708487980427928
Fold 4 IBS: 0.24926958370506158
Fold 5 IBS: 0.2050083932524473
[I 2024-04-13 22:12:53,715] Trial 78 finished with value: 0.23466312854108767 and parameters: {'subsample': 0.23637568910856077, 'dropout_rate': 0.40941545734655177, 'n_estimators': 266, 'learning_rate': 0.013681344796131267}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24351179342040893
Fold 2 IBS: 0.2299283988341639
Fold 3 IBS: 0.2229507770748589
Fold 4 IBS: 0.23974317638031392
Fold 5 IBS: 0.22110111541834618
[I 2024-04-13 22:12:56,965] Trial 79 finished with value: 0.23144705222561837 and parameters: {'subsample': 0.2836399643579865, 'dropout_rate': 0.5770549444080577, 'n_estimators': 221, 'learning_rate': 0.004673460921974206}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.25701514968453215
Fold 2 IBS: 0.2582609022695186
Fold 3 IBS: 0.2634203543932934
Fold 4 IBS: 0.26413563353401764
Fold 5 IBS: 0.20477815413444034
[I 2024-04-13 22:13:02,317] Trial 80 finished with value: 0.2495220388031604 and parameters: {'subsample': 0.3258590512771457, 'dropout_rate': 0.5179212274926552, 'n_estimators': 323, 'learning_rate': 0.01895817805243849}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24431327676669423
Fold 2 IBS: 0.23586688244419246
Fold 3 IBS: 0.23586702897681647
Fold 4 IBS: 0.24262624858205278
Fold 5 IBS: 0.20903034943159618
[I 2024-04-13 22:13:05,982] Trial 81 finished with value: 0.23354075724027043 and parameters: {'subsample': 0.3887101358985985, 'dropout_rate': 0.526254762713732, 'n_estimators': 246, 'learning_rate': 0.012735527966965764}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.2430683063216259
Fold 2 IBS: 0.23057598221740183
Fold 3 IBS: 0.22490697179205002
Fold 4 IBS: 0.23883500870580862
Fold 5 IBS: 0.2165158957300214
[I 2024-04-13 22:13:08,509] Trial 82 finished with value: 0.23078043295338152 and parameters: {'subsample': 0.4371092102813388, 'dropout_rate': 0.47820034240419074, 'n_estimators': 189, 'learning_rate': 0.00914853174361647}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24526571698942362
Fold 2 IBS: 0.23077254375402476
Fold 3 IBS: 0.2249037137246224
Fold 4 IBS: 0.24024624107893916
Fold 5 IBS: 0.22518935976085908
[I 2024-04-13 22:13:11,058] Trial 83 finished with value: 0.23327551506157382 and parameters: {'subsample': 0.4267790142949473, 'dropout_rate': 0.46745278430097376, 'n_estimators': 186, 'learning_rate': 0.002802137685402943}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24291144044955196
Fold 2 IBS: 0.23013728006299994
Fold 3 IBS: 0.2239970319529376
Fold 4 IBS: 0.24031880752572288
Fold 5 IBS: 0.21724950268666557
[I 2024-04-13 22:13:16,170] Trial 84 finished with value: 0.23092281253557562 and parameters: {'subsample': 0.340898093725495, 'dropout_rate': 0.4185442640848225, 'n_estimators': 282, 'learning_rate': 0.005410314251585534}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24320853625891553
Fold 2 IBS: 0.2301537775348745
Fold 3 IBS: 0.22335438528336607
Fold 4 IBS: 0.23897229721122137
Fold 5 IBS: 0.21942204410959293
[I 2024-04-13 22:13:18,849] Trial 85 finished with value: 0.23102220807959406 and parameters: {'subsample': 0.37422506614521606, 'dropout_rate': 0.5096494932033888, 'n_estimators': 161, 'learning_rate': 0.007544684032298379}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24406478398239922
Fold 2 IBS: 0.23307654552015553
Fold 3 IBS: 0.230208348379897
Fold 4 IBS: 0.2396112781365801
Fold 5 IBS: 0.21278879242721382
[I 2024-04-13 22:13:22,871] Trial 86 finished with value: 0.23194994968924912 and parameters: {'subsample': 0.47866600725521646, 'dropout_rate': 0.5567740372435235, 'n_estimators': 266, 'learning_rate': 0.009313476604200871}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24576529048908613
Fold 2 IBS: 0.2310663340203712
Fold 3 IBS: 0.2261354326743808
Fold 4 IBS: 0.2409763407992363
Fold 5 IBS: 0.2266216087604238
[I 2024-04-13 22:13:25,990] Trial 87 finished with value: 0.23411300134869967 and parameters: {'subsample': 0.2743342358201541, 'dropout_rate': 0.5935629478136775, 'n_estimators': 220, 'learning_rate': 0.0015207070358501645}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.243017835901318
Fold 2 IBS: 0.23098562365559758
Fold 3 IBS: 0.22651742718387882
Fold 4 IBS: 0.24112901640959244
Fold 5 IBS: 0.2132286963104368
[I 2024-04-13 22:13:28,488] Trial 88 finished with value: 0.23097571989216475 and parameters: {'subsample': 0.30710737013961914, 'dropout_rate': 0.3571185667848573, 'n_estimators': 174, 'learning_rate': 0.011972256352063079}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.2590128595803287
Fold 2 IBS: 0.26399135252092465
Fold 3 IBS: 0.26351215648285803
Fold 4 IBS: 0.2719102507965516
Fold 5 IBS: 0.20899588597859006
[I 2024-04-13 22:13:35,270] Trial 89 finished with value: 0.2534845010718506 and parameters: {'subsample': 0.2429886574528911, 'dropout_rate': 0.48934947543783713, 'n_estimators': 368, 'learning_rate': 0.018002425083028666}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24580972558397626
Fold 2 IBS: 0.23687997526547955
Fold 3 IBS: 0.2396423092179829
Fold 4 IBS: 0.24599650368691564
Fold 5 IBS: 0.20896801538013382
[I 2024-04-13 22:13:38,898] Trial 90 finished with value: 0.2354593058268976 and parameters: {'subsample': 0.398273409101327, 'dropout_rate': 0.47042475312508, 'n_estimators': 236, 'learning_rate': 0.014509780941175554}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24338216886057223
Fold 2 IBS: 0.23006711732955235
Fold 3 IBS: 0.2235989773503989
Fold 4 IBS: 0.2400538903712163
Fold 5 IBS: 0.21861337462536973
[I 2024-04-13 22:13:43,780] Trial 91 finished with value: 0.2311431057074219 and parameters: {'subsample': 0.34482826820750606, 'dropout_rate': 0.4221702347155337, 'n_estimators': 290, 'learning_rate': 0.004593957677047768}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24304823906055986
Fold 2 IBS: 0.2301665331315235
Fold 3 IBS: 0.22479735928762373
Fold 4 IBS: 0.2407210874787482
Fold 5 IBS: 0.21572977291455842
[I 2024-04-13 22:19:05,965] Trial 92 finished with value: 0.23089259837460271 and parameters: {'subsample': 0.3283110433403148, 'dropout_rate': 0.3930045772890858, 'n_estimators': 282, 'learning_rate': 0.006100282349099543}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24307133805410439
Fold 2 IBS: 0.23082731405085705
Fold 3 IBS: 0.226596999754198
Fold 4 IBS: 0.23960340352798856
Fold 5 IBS: 0.21461619829728296
[I 2024-04-13 22:19:11,369] Trial 93 finished with value: 0.2309430507368862 and parameters: {'subsample': 0.41701224508704154, 'dropout_rate': 0.3609499145344804, 'n_estimators': 314, 'learning_rate': 0.006466379855276053}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24259057145122304
Fold 2 IBS: 0.23173612851574527
Fold 3 IBS: 0.226182966756832
Fold 4 IBS: 0.2405779048402392
Fold 5 IBS: 0.21316547744349307
[I 2024-04-13 22:19:15,311] Trial 94 finished with value: 0.23085060980150654 and parameters: {'subsample': 0.32625849813237434, 'dropout_rate': 0.6166605905600888, 'n_estimators': 256, 'learning_rate': 0.008484393912422145}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24295098917669627
Fold 2 IBS: 0.23237826135588247
Fold 3 IBS: 0.22826143788767156

Fold 4 IBS: 0.240096804175716
Fold 5 IBS: 0.21220295505386813
[I 2024-04-13 22:19:18,632] Trial 95 finished with value: 0.23117808952996688 and parameters: {'subsample': 0.3683350446497741, 'dropout_rate': 0.6195112110508696, 'n_estimators': 256, 'learning_rate': 0.009118931904905743}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24257214724086992
Fold 2 IBS: 0.2343278228700067
Fold 3 IBS: 0.23143612426238616
Fold 4 IBS: 0.24257936688981685
Fold 5 IBS: 0.20909399543337767
[I 2024-04-13 22:19:21,579] Trial 96 finished with value: 0.23200189133929144 and parameters: {'subsample': 0.308291704410664, 'dropout_rate': 0.6432020013429081, 'n_estimators': 243, 'learning_rate': 0.011917866704154519}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24444085952060532
Fold 2 IBS: 0.2300912445266555
Fold 3 IBS: 0.2240606885107319
Fold 4 IBS: 0.24047891143824324
Fold 5 IBS: 0.22366696464055894
[I 2024-04-13 22:19:24,356] Trial 97 finished with value: 0.23254773372735899 and parameters: {'subsample': 0.2692616789599147, 'dropout_rate': 0.5519205703012934, 'n_estimators': 214, 'learning_rate': 0.003275458217408939}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24342600399552383
Fold 2 IBS: 0.23091569629466177
Fold 3 IBS: 0.22421951085086234
Fold 4 IBS: 0.23762441965078554
Fold 5 IBS: 0.21811644623334167
[I 2024-04-13 22:19:26,769] Trial 98 finished with value: 0.23086041540503502 and parameters: {'subsample': 0.5035057892719108, 'dropout_rate': 0.5923942600058895, 'n_estimators': 189, 'learning_rate': 0.008082935128422}. Best is trial 67 with value: 0.2305246765527135.
Fold 1 IBS: 0.24471188849326997
Fold 2 IBS: 0.24021276559328944
Fold 3 IBS: 0.24171707142187002
Fold 4 IBS: 0.24931861170201133
Fold 5 IBS: 0.20564861304282947
[I 2024-04-13 22:19:30,039] Trial 99 finished with value: 0.23632179005065407 and parameters: {'subsample': 0.29047002057420257, 'dropout_rate': 0.5399952676454306, 'n_estimators': 257, 'learning_rate': 0.015440636921384858}. Best is trial 67 with value: 0.2305246765527135.


* Best trial for IBS:
 FrozenTrial(number=67, state=TrialState.COMPLETE, values=[0.2305246765527135], datetime_start=datetime.datetime(2024, 4, 13, 22, 11, 20, 885187), datetime_complete=datetime.datetime(2024, 4, 13, 22, 11, 25, 740729), params={'subsample': 0.35814936289595134, 'dropout_rate': 0.604986146999221, 'n_estimators': 310, 'learning_rate': 0.006338930484056821}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=67, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.35814936289595134, 'dropout_rate': 0.604986146999221, 'n_estimators': 310, 'learning_rate': 0.006338930484056821}


* Best Score for IBS:
 0.2305246765527135

In [93]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [94]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.62
train_ibs:  0.231

#### Test

In [95]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [96]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.644905787703748,
                                              learning_rate=0.09966139122330783,
                                              n_estimators=5, random_state=123,
                                              subsample=0.14154027296706004)

C-index score: 0.543

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.604986146999221,
                                              learning_rate=0.006338930484056821,
                                              n_estimators=310,
                                              random_state=123,
                                              subsample=0.35814936289595134)

IBS: 0.235

In [97]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [98]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.791   1.0
Randomsurvivalforest             0.760   2.0
GradientBoosting                 0.642   3.0
CoxLasso                         0.630   4.5
CoxElastic                       0.630   4.5
ComponentwiseGradientBoosting    0.620   6.0
CoxPH                            0.619   7.0
CoxRidge                         0.560   8.0

In [99]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.217   1.0
Randomsurvivalforest           0.223   2.0
ComponentwiseGradientBoosting  0.231   3.0
GradientBoosting               0.232   4.0
CoxElastic                     0.235   5.0
CoxRidge                       0.236   6.0
CoxLasso                       0.243   7.0
CoxPH                          0.248   8.0

In [100]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.669   1.0
Randomsurvivalforest             0.633   2.0
ExtraSurvivalTrees               0.584   3.0
CoxElastic                       0.572   4.0
CoxLasso                         0.571   5.0
ComponentwiseGradientBoosting    0.543   6.0
CoxRidge                         0.533   7.0

In [101]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.216   1.0
ExtraSurvivalTrees             0.223   2.0
GradientBoosting               0.224   3.0
CoxRidge                       0.229   4.5
CoxElastic                     0.229   4.5
ComponentwiseGradientBoosting  0.235   6.0
CoxLasso                       0.279   7.0

In [102]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/yeojohnson/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_yeojohnson_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [103]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-13