In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
    
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import PowerTransformer

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, DFS, DFS_event]
Index: []

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [14]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [15]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [16]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [17]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

# Feature Selection: RENT

In [18]:
# Choose features from the result of RENT 
selected_features = ["hpv_related",
"pack_years",
"uicc8_III-IV",
"oropharynx",
"cavum_oris",
"TLG"]

In [19]:
X_rent = X.loc[:, selected_features]
X_new = X_rent.copy()

In [20]:
list(X_new)

['hpv_related',
 'pack_years',
 'uicc8_III-IV',
 'oropharynx',
 'cavum_oris',
 'TLG']

In [21]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Yeo-Johnson Transformation

In [22]:
# Copy the original X for later 
original_X = X.copy()

In [28]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)
X_new_std = X_new_std[X_new.columns]

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [29]:
X_new

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0            0.0    0.000000           0.0           1           0   86.228420
1            0.0   27.404795           0.0           0           0    7.040100
2            0.0   41.019178           1.0           0           1   83.569669
3            0.0   37.500000           0.0           0           0    5.567091
4            0.0   53.000000           0.0           0           0   16.150550
..           ...         ...           ...         ...         ...         ...
134          1.0    0.000000           0.0           1           0   26.280140
135          1.0    0.000000           1.0           1           0  101.754834
136          1.0   39.498630           0.0           1           0   66.273201
137          1.0   71.527397           1.0           1           0   71.832443
138          1.0    2.250000           1.0           1           0   78.647696

[139 rows x 6 columns]

In [30]:
X_new_std

     hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0            0.0   -1.533345           0.0           1           0  0.343545
1            0.0    0.397233           0.0           0           0 -1.657833
2            0.0    0.830437           1.0           0           1  0.318631
3            0.0    0.727938           0.0           0           0 -1.835650
4            0.0    1.144253           0.0           0           0 -1.003396
..           ...         ...           ...         ...         ...       ...
134          1.0   -1.533345           0.0           1           0 -0.611074
135          1.0   -1.533345           1.0           1           0  0.474941
136          1.0    0.786825           0.0           1           0  0.133612
137          1.0    1.554125           1.0           1           0  0.197985
138          1.0   -1.110899           1.0           1           0  0.270290

[139 rows x 6 columns]

In [31]:
MAASTRO_new

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris         TLG
0             1           0             0           1           0  263.611623
1             0          20             1           1           0   36.980700
2             0           6             1           1           0   74.636342
3             0          45             1           0           0   46.791979
4             1          59             0           1           0  107.637514
..          ...         ...           ...         ...         ...         ...
94            0          55             1           0           0  144.490782
95            0         174             1           0           0   69.214868
96            1           0             1           1           0  102.594274
97            1           0             0           1           0  103.229492
98            0          40             1           0           0   28.553212

[99 rows x 6 columns]

In [32]:
MAASTRO_new_std

    hpv_related  pack_years  uicc8_III-IV  oropharynx  cavum_oris       TLG
0             1   -1.533345             0           1           0  1.218887
1             0    0.104884             1           1           0 -0.335276
2             0   -0.713198             1           1           0  0.228548
3             0    0.940197             1           0           0 -0.145668
4             1    1.285347             0           1           0  0.519421
..          ...         ...           ...         ...         ...       ...
94            0    1.192311             1           0           0  0.751363
95            0    3.094727             1           0           0  0.168333
96            1   -1.533345             1           1           0  0.481447
97            1   -1.533345             0           1           0  0.486335
98            0    0.801315             1           0           0 -0.544074

[99 rows x 6 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [33]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:35:37,492] A new study created in memory with name: no-name-c21d4a16-d53e-47e9-b572-13ba4b06217d

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6806083650190115

[I 2024-04-13 17:35:50,385] A new study created in memory with name: no-name-df6360cb-1d3f-4d55-a0bb-8392e95d614f

Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:35:50,371] Trial 0 finished with value: 0.6377041251337131 and parameters: {}. Best is trial 0 with value: 0.6377041251337131.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6377041251337131], datetime_start=datetime.datetime(2024, 4, 13, 17, 35, 37, 608765), datetime_complete=datetime.datetime(2024, 4, 13, 17, 35, 50, 371165), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6377041251337131

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2400498117827728
Fold 2 IBS: 0.25100737618728725
Fold 3 IBS: 0.17791096375880883
Fold 4 IBS: 0.2621949716521241
Fold 5 IBS: 0.20430826926374088
[I 2024-04-13 17:35:51,624] Trial 0 finished with value: 0.22709427852894676 and parameters: {}. Best is trial 0 with value: 0.22709427852894676.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.22709427852894676], datetime_start=datetime.datetime(2024, 4, 13, 17, 35, 50, 427960), datetime_complete=datetime.datetime(2024, 4, 13, 17, 35, 51, 621400), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.22709427852894676

In [34]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [35]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.638
train_ibs:  0.227

#### Test

In [36]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [37]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.566
IBS score: 0.262

In [38]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [39]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [40]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:35:52,166] A new study created in memory with name: no-name-b8e0c031-8ab5-43dc-8ace-6914b063e9e8

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.5058139534883721
Fold 3 C-index: 0.5617021276595745

[I 2024-04-13 17:35:52,778] A new study created in memory with name: no-name-eefa01eb-afa3-49a6-869a-e30f083d63c8

Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:35:52,766] Trial 0 finished with value: 0.5924623092785654 and parameters: {}. Best is trial 0 with value: 0.5924623092785654.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5924623092785654], datetime_start=datetime.datetime(2024, 4, 13, 17, 35, 52, 199145), datetime_complete=datetime.datetime(2024, 4, 13, 17, 35, 52, 765804), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5924623092785654

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709674441997
Fold 2 IBS: 0.23203988447801246
Fold 3 IBS: 0.2289818653708319
Fold 4 IBS: 0.24197477208488385
Fold 5 IBS: 0.22939558600665344
[I 2024-04-13 17:35:53,352] Trial 0 finished with value: 0.2359278409369603 and parameters: {}. Best is trial 0 with value: 0.2359278409369603.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2359278409369603], datetime_start=datetime.datetime(2024, 4, 13, 17, 35, 52, 812056), datetime_complete=datetime.datetime(2024, 4, 13, 17, 35, 53, 351748), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2359278409369603

In [41]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [42]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.592
train_ibs:  0.236

#### Test

In [43]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [44]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.533

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [45]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [46]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:35:53,654] A new study created in memory with name: no-name-47bef6a1-04b0-4de9-84a4-bf4312bf7d38

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115

[I 2024-04-13 17:35:54,980] A new study created in memory with name: no-name-ddd554fa-54e0-43a8-b1a7-1d0194d54633

Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:35:54,971] Trial 0 finished with value: 0.6368384507660754 and parameters: {}. Best is trial 0 with value: 0.6368384507660754.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6368384507660754], datetime_start=datetime.datetime(2024, 4, 13, 17, 35, 53, 699911), datetime_complete=datetime.datetime(2024, 4, 13, 17, 35, 54, 970577), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6368384507660754

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.23952972737617964
Fold 2 IBS: 0.24887322452368552
Fold 3 IBS: 0.17930689607847744
Fold 4 IBS: 0.26095544845313173
Fold 5 IBS: 0.20425265437196208
[I 2024-04-13 17:35:56,962] Trial 0 finished with value: 0.22658359016068727 and parameters: {}. Best is trial 0 with value: 0.22658359016068727.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.22658359016068727], datetime_start=datetime.datetime(2024, 4, 13, 17, 35, 55, 350086), datetime_complete=datetime.datetime(2024, 4, 13, 17, 35, 56, 961201), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.22658359016068727

In [47]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.637
train_ibs:  0.227

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [50]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.567

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.259

In [51]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [52]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:35:57,919] A new study created in memory with name: no-name-127cc9e9-89e3-455e-9a12-115c6d4dbace

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:35:58,940] Trial 0 finished with value: 0.6376752009142335 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6376752009142335.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:35:59,962] Trial 1 finished with value: 0.6370015008646465 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6376752009142335.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:00,860] Trial 2 finished with value: 0.6304339725283791 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6376752009142335.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:01,873] Trial 3 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:02,977] Trial 4 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:04,406] Trial 5 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:05,505] Trial 6 finished with value: 0.6368384507660754 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:06,712] Trial 7 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:07,780] Trial 8 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:08,951] Trial 9 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:36:09,357] Trial 10 finished with value: 0.5961217840276631 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:10,446] Trial 11 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5750964404641357}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:11,825] Trial 12 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5968468753861893}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:12,647] Trial 13 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.8831798862691105}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:14,009] Trial 14 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.587875868972022}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:15,265] Trial 15 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.8333485572500325}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 17:36:15,773] Trial 16 finished with value: 0.5951403022295337 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:16,916] Trial 17 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5698747240965845}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:18,277] Trial 18 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.3332542090687166}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:19,595] Trial 19 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.8059549337998971}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:20,664] Trial 20 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.48243407062044524}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:36:22,027] Trial 21 finished with value: 0.6369615634654924 and parameters: {'l1_ratio': 0.6018578610622224}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:23,449] Trial 22 finished with value: 0.6378199325642048 and parameters: {'l1_ratio': 0.5687286667427376}. Best is trial 3 with value: 0.6385951263626544.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103

[I 2024-04-13 17:36:24,921] Trial 23 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.651954326927192}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:36:26,199] Trial 24 finished with value: 0.6377583762144964 and parameters: {'l1_ratio': 0.7687494836451149}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:28,144] Trial 25 finished with value: 0.6386167453132088 and parameters: {'l1_ratio': 0.6633833508070742}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:29,740] Trial 26 finished with value: 0.6368384507660754 and parameters: {'l1_ratio': 0.9167426588025347}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:31,095] Trial 27 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.681867443256391}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:32,282] Trial 28 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7467529633091712}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:33,309] Trial 29 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.5108050853931967}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:34,510] Trial 30 finished with value: 0.6386167453132088 and parameters: {'l1_ratio': 0.6604222013728371}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:35,362] Trial 31 finished with value: 0.6386167453132088 and parameters: {'l1_ratio': 0.6714605163735983}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:36,278] Trial 32 finished with value: 0.6386167453132088 and parameters: {'l1_ratio': 0.6549389735988309}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:37,458] Trial 33 finished with value: 0.6386167453132088 and parameters: {'l1_ratio': 0.6588000818275165}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:38,802] Trial 34 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.808461741611184}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:39,807] Trial 35 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7453777066712262}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:40,870] Trial 36 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6380776935198499}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:41,932] Trial 37 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.4165058851094211}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:43,063] Trial 38 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.6324245069874874}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:44,440] Trial 39 finished with value: 0.6304339725283791 and parameters: {'l1_ratio': 0.2157328220487701}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:45,585] Trial 40 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:46,475] Trial 41 finished with value: 0.6376752009142335 and parameters: {'l1_ratio': 0.7014357977650674}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:47,688] Trial 42 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7159862956960181}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:48,785] Trial 43 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6445310163985674}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:49,634] Trial 44 finished with value: 0.6378199325642048 and parameters: {'l1_ratio': 0.6254469504930085}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:50,593] Trial 45 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:51,586] Trial 46 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.8644244220180649}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682

Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:52,420] Trial 47 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.4461628541794258}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:36:53,463] Trial 48 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:54,431] Trial 49 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6350137484940073}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:36:55,683] Trial 50 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7217880160329924}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:56,724] Trial 51 finished with value: 0.6378199325642048 and parameters: {'l1_ratio': 0.6176827099955424}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:57,664] Trial 52 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.5482813960905941}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:58,787] Trial 53 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6412310641774053}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:36:59,724] Trial 54 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.4683516979738161}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:00,780] Trial 55 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.592169259712791}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:01,567] Trial 56 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6364821943719783}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:02,494] Trial 57 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5542983820605372}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:03,261] Trial 58 finished with value: 0.6376752009142335 and parameters: {'l1_ratio': 0.7018035204686177}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:03,984] Trial 59 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.3635438827822911}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:37:04,863] Trial 60 finished with value: 0.6369615634654924 and parameters: {'l1_ratio': 0.6097637962339882}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:05,656] Trial 61 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.648912470081683}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:06,479] Trial 62 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6333880541408756}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:07,369] Trial 63 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7427984043298578}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:37:08,359] Trial 64 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.7918870856024915}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:09,320] Trial 65 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.5041146520503832}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:10,349] Trial 66 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5756554494142562}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:11,237] Trial 67 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.6828158661114051}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:12,178] Trial 68 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6430794619961013}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:37:13,043] Trial 69 finished with value: 0.6368384507660754 and parameters: {'l1_ratio': 0.9521436965777794}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:14,049] Trial 70 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7335406656748615}. Best is trial 23 with value: 0.6393919391116584.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:14,990] Trial 71 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6329871309596264}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:15,780] Trial 72 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5858492033614904}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:16,790] Trial 73 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.6805233069388251}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:17,578] Trial 74 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6382653025227067}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:37:18,348] Trial 75 finished with value: 0.6360416380170715 and parameters: {'l1_ratio': 0.8253254989575621}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:37:19,089] Trial 76 finished with value: 0.6369615634654924 and parameters: {'l1_ratio': 0.6043955138768317}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:37:19,913] Trial 77 finished with value: 0.638533570012946 and parameters: {'l1_ratio': 0.7662271285015285}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:20,669] Trial 78 finished with value: 0.6376752009142335 and parameters: {'l1_ratio': 0.6988967427161563}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:21,469] Trial 79 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.5306077767310583}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:22,339] Trial 80 finished with value: 0.6378199325642048 and parameters: {'l1_ratio': 0.5646190942701348}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:23,354] Trial 81 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6504678211704914}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:24,230] Trial 82 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6485281703048251}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:25,040] Trial 83 finished with value: 0.6378199325642048 and parameters: {'l1_ratio': 0.6182631790425592}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:25,968] Trial 84 finished with value: 0.6386167453132088 and parameters: {'l1_ratio': 0.6706875061735498}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:26,764] Trial 85 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7087998960237182}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:27,730] Trial 86 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5988120446139796}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:28,538] Trial 87 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.5435907875386358}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:29,261] Trial 88 finished with value: 0.6377983136136505 and parameters: {'l1_ratio': 0.49440809974916394}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:37:30,070] Trial 89 finished with value: 0.6377583762144964 and parameters: {'l1_ratio': 0.7588382994721679}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:31,246] Trial 90 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6445823021180832}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:32,055] Trial 91 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.6326838888298593}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:33,012] Trial 92 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.6889649575323649}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:37:33,982] Trial 93 finished with value: 0.6369000071157839 and parameters: {'l1_ratio': 0.7190124367317589}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:34,834] Trial 94 finished with value: 0.6385951263626544 and parameters: {'l1_ratio': 0.5764563071532146}. Best is trial 23 with value: 0.6393919391116584.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:35,614] Trial 95 finished with value: 0.6378199325642048 and parameters: {'l1_ratio': 0.6211224680788917}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:36,331] Trial 96 finished with value: 0.6386167453132088 and parameters: {'l1_ratio': 0.6764295097708855}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:37,033] Trial 97 finished with value: 0.6296371597793751 and parameters: {'l1_ratio': 0.2367441530189508}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:37:37,855] Trial 98 finished with value: 0.6393919391116584 and parameters: {'l1_ratio': 0.6489150709087037}. Best is trial 23 with value: 0.6393919391116584.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 17:37:38,689] Trial 99 finished with value: 0.6369615634654924 and parameters: {'l1_ratio': 0.6047737139138171}. Best is trial 23 with value: 0.6393919391116584.

[I 2024-04-13 17:37:38,735] A new study created in memory with name: no-name-c9a7c950-6369-48b9-a089-db7a9c2e132e

* Best trial for C-index:
 FrozenTrial(number=23, state=TrialState.COMPLETE, values=[0.6393919391116584], datetime_start=datetime.datetime(2024, 4, 13, 17, 36, 23, 454975), datetime_complete=datetime.datetime(2024, 4, 13, 17, 36, 24, 861621), params={'l1_ratio': 0.651954326927192}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=23, value=None)


* Best Score for C-index:
 0.6393919391116584

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2399316357515028
Fold 2 IBS: 0.24869689058088437
Fold 3 IBS: 0.17922908696999248
Fold 4 IBS: 0.26102159508422307
Fold 5 IBS: 0.20415166361804699
[I 2024-04-13 17:37:39,657] Trial 0 finished with value: 0.22660617440092995 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.22660617440092995.
Fold 1 IBS: 0.24065183691727052
Fold 2 IBS: 0.24875197100872162
Fold 3 IBS: 0.1792132921209873
Fold 4 IBS: 0.26110143013070647
Fold 5 IBS: 0.20399045974317612
[I 2024-04-13 17:37:40,769] Trial 1 finished with value: 0.22674179798417238 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.22660617440092995.
Fold 1 IBS: 0.240768303616732
Fold 2 IBS: 0.2325812298093743
Fold 3 IBS: 0.17916710097142027
Fold 4 IBS: 0.26109267593358537
Fold 5 IBS: 0.20395622685142237
[I 2024-04-13 17:37:41,620] Trial 2 finished with value: 0.22351310743650687 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24017235731133843
Fold 2 IBS: 0.2487909727499755
Fold 3 IBS: 0.17923887486586385
Fold 4 IBS: 0.2610438327586362
Fold 5 IBS: 0.20409930458441083
[I 2024-04-13 17:37:42,527] Trial 3 finished with value: 0.22666906845404497 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.23989821611046996
Fold 2 IBS: 0.24877024192019875
Fold 3 IBS: 0.1793411115843481
Fold 4 IBS: 0.26104626017360133
Fold 5 IBS: 0.20416293027150903
[I 2024-04-13 17:37:43,515] Trial 4 finished with value: 0.2266437520120254 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24039389681769752
Fold 2 IBS: 0.24879831046427556
Fold 3 IBS: 0.17928806031658498
Fold 4 IBS: 0.2611350212904997
Fold 5 IBS: 0.20406295251226797
[I 2024-04-13 17:37:44,460] Trial 5 finished with value: 0.22673564828026516 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.23954957137334246
Fold 2 IBS: 0.24884890890229552
Fold 3 IBS: 0.17931589241944904
Fold 4 IBS: 0.261053035906198
Fold 5 IBS: 0.20424668236616791
[I 2024-04-13 17:37:45,357] Trial 6 finished with value: 0.22660281819349057 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.23996041168299673
Fold 2 IBS: 0.24884497037718653
Fold 3 IBS: 0.17923824887769865
Fold 4 IBS: 0.26100850582681534
Fold 5 IBS: 0.20414569404467217
[I 2024-04-13 17:37:46,215] Trial 7 finished with value: 0.22663956616187386 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24029247271788265
Fold 2 IBS: 0.24869242301700117
Fold 3 IBS: 0.1792016079172637
Fold 4 IBS: 0.2610379816743811
Fold 5 IBS: 0.2040680535173366
[I 2024-04-13 17:37:47,147] Trial 8 finished with value: 0.226658507768773 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24046122278277676
Fold 2 IBS: 0.24864764643085277
Fold 3 IBS: 0.1792177300868669
Fold 4 IBS: 0.2610724113145841
Fold 5 IBS: 0.20403506934542404
[I 2024-04-13 17:37:48,163] Trial 9 finished with value: 0.2266868159921009 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24508330766171335
Fold 2 IBS: 0.2321507407258022
Fold 3 IBS: 0.2272708038442089
Fold 4 IBS: 0.24262599315990863
Fold 5 IBS: 0.2253112333454335
[I 2024-04-13 17:37:48,605] Trial 10 finished with value: 0.23448841574741333 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.2396156673997955
Fold 2 IBS: 0.24889009423171432
Fold 3 IBS: 0.17934665219595156
Fold 4 IBS: 0.2610090542876449
Fold 5 IBS: 0.20422637216118333
[I 2024-04-13 17:37:49,555] Trial 11 finished with value: 0.22661756805525793 and parameters: {'l1_ratio': 0.9201080639320232}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.23953974705918085
Fold 2 IBS: 0.24885174445013244
Fold 3 IBS: 0.17931142512960221
Fold 4 IBS: 0.26105943136217663
Fold 5 IBS: 0.2042496469591661
[I 2024-04-13 17:37:50,467] Trial 12 finished with value: 0.22660239899205165 and parameters: {'l1_ratio': 0.9902263164082913}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24622603858979555
Fold 2 IBS: 0.23205097825953303
Fold 3 IBS: 0.22821037574677688
Fold 4 IBS: 0.242204698468503
Fold 5 IBS: 0.2274677457994349
[I 2024-04-13 17:37:50,862] Trial 13 finished with value: 0.23523196737280866 and parameters: {'l1_ratio': 0.032051700885313394}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24072551751104745
Fold 2 IBS: 0.23265450101318136
Fold 3 IBS: 0.17920134550170552
Fold 4 IBS: 0.26108362942784497
Fold 5 IBS: 0.20396654520448665
[I 2024-04-13 17:37:51,919] Trial 14 finished with value: 0.22352630773165316 and parameters: {'l1_ratio': 0.2507045659058569}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24079448269975887
Fold 2 IBS: 0.23255754402560552
Fold 3 IBS: 0.17919563832876945
Fold 4 IBS: 0.2611579604110677
Fold 5 IBS: 0.20397235655551807
[I 2024-04-13 17:37:52,770] Trial 15 finished with value: 0.2235355964041439 and parameters: {'l1_ratio': 0.21932062545639627}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.2408164078949507
Fold 2 IBS: 0.2325378942219362
Fold 3 IBS: 0.17922050537232873
Fold 4 IBS: 0.26113241895745143
Fold 5 IBS: 0.20396111098054134
[I 2024-04-13 17:37:53,864] Trial 16 finished with value: 0.22353366748544165 and parameters: {'l1_ratio': 0.21303081021895065}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24093816061902856
Fold 2 IBS: 0.2322979618956508
Fold 3 IBS: 0.22658215110053206
Fold 4 IBS: 0.24304141449000044
Fold 5 IBS: 0.22382810308079787
[I 2024-04-13 17:37:54,489] Trial 17 finished with value: 0.23333755823720193 and parameters: {'l1_ratio': 0.1360825059390146}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24056660787612222
Fold 2 IBS: 0.24873418475074552
Fold 3 IBS: 0.17920294583963145
Fold 4 IBS: 0.2611475997323465
Fold 5 IBS: 0.20402828043804327
[I 2024-04-13 17:37:56,047] Trial 18 finished with value: 0.22673592372737783 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 2 with value: 0.22351310743650687.
Fold 1 IBS: 0.24086831960280167
Fold 2 IBS: 0.23240037006239445
Fold 3 IBS: 0.179191092262902
Fold 4 IBS: 0.2611156401364302
Fold 5 IBS: 0.20392914619380348
[I 2024-04-13 17:37:57,310] Trial 19 finished with value: 0.22350091365166636 and parameters: {'l1_ratio': 0.16922934881357457}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24094942875945863
Fold 2 IBS: 0.23231703888884483
Fold 3 IBS: 0.22651243407637883
Fold 4 IBS: 0.24308901548873696
Fold 5 IBS: 0.2236813186484153
[I 2024-04-13 17:37:57,833] Trial 20 finished with value: 0.2333098471723669 and parameters: {'l1_ratio': 0.1423518953289899}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2406858497029621
Fold 2 IBS: 0.24867687176938097
Fold 3 IBS: 0.17924706783906014
Fold 4 IBS: 0.26116165008360315
Fold 5 IBS: 0.20400133853453464
[I 2024-04-13 17:37:58,774] Trial 21 finished with value: 0.2267545555859082 and parameters: {'l1_ratio': 0.2744134734897308}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2463874154536326
Fold 2 IBS: 0.23204516227770292
Fold 3 IBS: 0.2283359574808616
Fold 4 IBS: 0.2421602791830433
Fold 5 IBS: 0.22777072815869875
[I 2024-04-13 17:37:59,239] Trial 22 finished with value: 0.23533990851078782 and parameters: {'l1_ratio': 0.026309945026381343}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24095055740399243
Fold 2 IBS: 0.23231634434573725
Fold 3 IBS: 0.22651491945631486
Fold 4 IBS: 0.24308729993026854
Fold 5 IBS: 0.22368654268139904
[I 2024-04-13 17:37:59,756] Trial 23 finished with value: 0.23331113276354243 and parameters: {'l1_ratio': 0.1421246663572635}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24080097768914643
Fold 2 IBS: 0.2325514277279443
Fold 3 IBS: 0.1792032957617194
Fold 4 IBS: 0.2611501540615162
Fold 5 IBS: 0.20396891700391162
[I 2024-04-13 17:38:00,509] Trial 24 finished with value: 0.22353495444884758 and parameters: {'l1_ratio': 0.21736087814603194}. Best is trial 19 with value: 0.22350091365166636.

Fold 1 IBS: 0.24015153650452095
Fold 2 IBS: 0.24882041004327032
Fold 3 IBS: 0.17922565256396153
Fold 4 IBS: 0.2610612525070375
Fold 5 IBS: 0.20410709163785418
[I 2024-04-13 17:38:01,482] Trial 25 finished with value: 0.2266731886513289 and parameters: {'l1_ratio': 0.5634871043246708}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24056048373465547
Fold 2 IBS: 0.24868366867195896
Fold 3 IBS: 0.1792199757947934
Fold 4 IBS: 0.2611287203583251
Fold 5 IBS: 0.20401989073831767
[I 2024-04-13 17:38:02,546] Trial 26 finished with value: 0.22672254785961013 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2448965928225129
Fold 2 IBS: 0.2321793735856304
Fold 3 IBS: 0.2271073213455378
Fold 4 IBS: 0.24271598902448063
Fold 5 IBS: 0.22495295734399848
[I 2024-04-13 17:38:02,989] Trial 27 finished with value: 0.23437044682443203 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24041936854179066
Fold 2 IBS: 0.24873556632094435
Fold 3 IBS: 0.17919348629418033
Fold 4 IBS: 0.26111181538014716
Fold 5 IBS: 0.20405258564482276
[I 2024-04-13 17:38:03,846] Trial 28 finished with value: 0.22670256443637707 and parameters: {'l1_ratio': 0.41114725307159555}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24082826021579604
Fold 2 IBS: 0.23249618299985944
Fold 3 IBS: 0.1791600669245945
Fold 4 IBS: 0.26116923735984554
Fold 5 IBS: 0.20396335704744942
[I 2024-04-13 17:38:05,286] Trial 29 finished with value: 0.223523420909509 and parameters: {'l1_ratio': 0.1997281316681165}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24713860297051285
Fold 2 IBS: 0.23203840946793625
Fold 3 IBS: 0.22890255378948915
Fold 4 IBS: 0.24199358144651173
Fold 5 IBS: 0.22918945585908268
[I 2024-04-13 17:38:06,129] Trial 30 finished with value: 0.2358525207067065 and parameters: {'l1_ratio': 0.002971280312000113}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2408352924371009
Fold 2 IBS: 0.23248996998292532
Fold 3 IBS: 0.17916855783102154
Fold 4 IBS: 0.2611605738087654
Fold 5 IBS: 0.203959526233508
[I 2024-04-13 17:38:08,433] Trial 31 finished with value: 0.22352278405866421 and parameters: {'l1_ratio': 0.19775064105879728}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24062682221676251
Fold 2 IBS: 0.2487117799980985
Fold 3 IBS: 0.1791619831329915
Fold 4 IBS: 0.26115781237615543
Fold 5 IBS: 0.20401542702541148
[I 2024-04-13 17:38:10,212] Trial 32 finished with value: 0.22673476494988387 and parameters: {'l1_ratio': 0.30578552234538414}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24479542750360414
Fold 2 IBS: 0.2321967450227215
Fold 3 IBS: 0.22701726432181346
Fold 4 IBS: 0.24276778548167277
Fold 5 IBS: 0.2247573789250733
[I 2024-04-13 17:38:10,680] Trial 33 finished with value: 0.23430692025097705 and parameters: {'l1_ratio': 0.10126717549079667}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24084686551595832
Fold 2 IBS: 0.23244735025276356
Fold 3 IBS: 0.17923121600165204
Fold 4 IBS: 0.2610965528988294
Fold 5 IBS: 0.20396221256277083
[I 2024-04-13 17:38:11,607] Trial 34 finished with value: 0.22351683944639483 and parameters: {'l1_ratio': 0.18419558903905753}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2409015164712796
Fold 2 IBS: 0.23237626440093534
Fold 3 IBS: 0.22631338474724444
Fold 4 IBS: 0.26116787544001624
Fold 5 IBS: 0.20394243821737656
[I 2024-04-13 17:38:12,615] Trial 35 finished with value: 0.2329402958553704 and parameters: {'l1_ratio': 0.16151497307428134}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2404798864517345
Fold 2 IBS: 0.24873584499920895
Fold 3 IBS: 0.17924987925638342
Fold 4 IBS: 0.2611343609223668
Fold 5 IBS: 0.20404154190138987
[I 2024-04-13 17:38:13,716] Trial 36 finished with value: 0.22672830270621672 and parameters: {'l1_ratio': 0.3749239727663831}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24034443251382992
Fold 2 IBS: 0.24877123767525192
Fold 3 IBS: 0.17923875326677988
Fold 4 IBS: 0.26109357049547666
Fold 5 IBS: 0.20406767922814964
[I 2024-04-13 17:38:14,989] Trial 37 finished with value: 0.22670313463589759 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2401509198739728
Fold 2 IBS: 0.24882181553407934
Fold 3 IBS: 0.17922525985544324
Fold 4 IBS: 0.2610617699079048
Fold 5 IBS: 0.20410732446132898
[I 2024-04-13 17:38:15,925] Trial 38 finished with value: 0.2266734179265458 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24066961942588852
Fold 2 IBS: 0.24872140774055276
Fold 3 IBS: 0.17923069223952032
Fold 4 IBS: 0.2610827970190539
Fold 5 IBS: 0.20398188195268474
[I 2024-04-13 17:38:16,951] Trial 39 finished with value: 0.22673727967554003 and parameters: {'l1_ratio': 0.27998268125243814}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24557129129838565
Fold 2 IBS: 0.23209402046396968
Fold 3 IBS: 0.22768361516193533
Fold 4 IBS: 0.24242121244169604
Fold 5 IBS: 0.22623662723078639
[I 2024-04-13 17:38:17,539] Trial 40 finished with value: 0.23480135331935462 and parameters: {'l1_ratio': 0.058917163471709555}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2408636768060815
Fold 2 IBS: 0.23240378517548507
Fold 3 IBS: 0.179185290437271
Fold 4 IBS: 0.2611215671424447
Fold 5 IBS: 0.20393175134128533
[I 2024-04-13 17:38:18,596] Trial 41 finished with value: 0.2235012141805135 and parameters: {'l1_ratio': 0.17031974064034827}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24086230726773547
Fold 2 IBS: 0.23243530774770274
Fold 3 IBS: 0.17913497152615393
Fold 4 IBS: 0.26117280553900196
Fold 5 IBS: 0.20395417588409276
[I 2024-04-13 17:38:19,619] Trial 42 finished with value: 0.22351191359293737 and parameters: {'l1_ratio': 0.18036444641568772}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24088638868980597
Fold 2 IBS: 0.2323872872149612
Fold 3 IBS: 0.22627885406628315
Fold 4 IBS: 0.26118687168830845
Fold 5 IBS: 0.2039508144931295
[I 2024-04-13 17:38:20,468] Trial 43 finished with value: 0.23293804323049766 and parameters: {'l1_ratio': 0.16504678302400444}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.23980075556956176
Fold 2 IBS: 0.24877625976252365
Fold 3 IBS: 0.17928948619365007
Fold 4 IBS: 0.26100872015918924
Fold 5 IBS: 0.20418394534381895
[I 2024-04-13 17:38:21,329] Trial 44 finished with value: 0.22661183340574875 and parameters: {'l1_ratio': 0.7906814170029204}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24073750041647488
Fold 2 IBS: 0.2326429092683929
Fold 3 IBS: 0.17921391807524625
Fold 4 IBS: 0.2611660959399901
Fold 5 IBS: 0.20398896679510928
[I 2024-04-13 17:38:22,171] Trial 45 finished with value: 0.22354987809904267 and parameters: {'l1_ratio': 0.24691503883654228}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24483209085647126
Fold 2 IBS: 0.23219029044264147
Fold 3 IBS: 0.2270500287019407
Fold 4 IBS: 0.24274875247952712
Fold 5 IBS: 0.22482839289336295
[I 2024-04-13 17:38:22,557] Trial 46 finished with value: 0.23432991107478868 and parameters: {'l1_ratio': 0.0989084093894868}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24052390569737486
Fold 2 IBS: 0.24863863913817147
Fold 3 IBS: 0.17917544952890166
Fold 4 IBS: 0.261091475650645
Fold 5 IBS: 0.2040224651158336
[I 2024-04-13 17:38:23,456] Trial 47 finished with value: 0.2266903870261853 and parameters: {'l1_ratio': 0.3561392578416232}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24088189147692818
Fold 2 IBS: 0.23242006875466656
Fold 3 IBS: 0.17915859745676865
Fold 4 IBS: 0.26114882632962616
Fold 5 IBS: 0.20394353485434383
[I 2024-04-13 17:38:24,436] Trial 48 finished with value: 0.2235105837744667 and parameters: {'l1_ratio': 0.17551234163449647}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24064022296765217
Fold 2 IBS: 0.24867587837432198
Fold 3 IBS: 0.17917409853079974
Fold 4 IBS: 0.26114437936585555
Fold 5 IBS: 0.204009468053264
[I 2024-04-13 17:38:25,364] Trial 49 finished with value: 0.22672880945837867 and parameters: {'l1_ratio': 0.3008929384227096}. Best is trial 19 with value: 0.22350091365166636.

Fold 1 IBS: 0.24544072408015
Fold 2 IBS: 0.23210687205360228
Fold 3 IBS: 0.22757503093079218
Fold 4 IBS: 0.24247202223273837
Fold 5 IBS: 0.22599013520701253
[I 2024-04-13 17:38:25,878] Trial 50 finished with value: 0.2347169569008591 and parameters: {'l1_ratio': 0.065098722293608}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2407294014440355
Fold 2 IBS: 0.23265072945724835
Fold 3 IBS: 0.17920540061813206
Fold 4 IBS: 0.26107913266507865
Fold 5 IBS: 0.2039928030830184
[I 2024-04-13 17:38:26,752] Trial 51 finished with value: 0.2235314934535026 and parameters: {'l1_ratio': 0.24947029881331234}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2408801241466323
Fold 2 IBS: 0.23242139750253155
Fold 3 IBS: 0.17915648712745033
Fold 4 IBS: 0.2611508438114237
Fold 5 IBS: 0.20394448468930906
[I 2024-04-13 17:38:27,829] Trial 52 finished with value: 0.22351066745546938 and parameters: {'l1_ratio': 0.17593565645109632}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24445844541010597
Fold 2 IBS: 0.23226546308661872
Fold 3 IBS: 0.22670856200364503
Fold 4 IBS: 0.24295781783201162
Fold 5 IBS: 0.22409562652165582
[I 2024-04-13 17:38:28,327] Trial 53 finished with value: 0.23409718297080745 and parameters: {'l1_ratio': 0.12524028653045186}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24004130760521725
Fold 2 IBS: 0.24867926603844642
Fold 3 IBS: 0.17928509973581616
Fold 4 IBS: 0.26104441704264403
Fold 5 IBS: 0.20413077061576132
[I 2024-04-13 17:38:29,132] Trial 54 finished with value: 0.226636172207577 and parameters: {'l1_ratio': 0.6304504906551746}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24073725493719605
Fold 2 IBS: 0.23261018580753698
Fold 3 IBS: 0.17925106337132407
Fold 4 IBS: 0.2611280437540778
Fold 5 IBS: 0.2039721746272795
[I 2024-04-13 17:38:29,986] Trial 55 finished with value: 0.22353974449948288 and parameters: {'l1_ratio': 0.23627686709170845}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24589225479600105
Fold 2 IBS: 0.23206875454808681
Fold 3 IBS: 0.22794534962294657
Fold 4 IBS: 0.24230748416178427
Fold 5 IBS: 0.22684067530413246
[I 2024-04-13 17:38:30,344] Trial 56 finished with value: 0.23501090368659025 and parameters: {'l1_ratio': 0.044966111222468325}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24088940882927767
Fold 2 IBS: 0.23241444991887
Fold 3 IBS: 0.1791676320401287
Fold 4 IBS: 0.2611396018934388
Fold 5 IBS: 0.2039396915221398
[I 2024-04-13 17:38:31,316] Trial 57 finished with value: 0.223510156840771 and parameters: {'l1_ratio': 0.17372166697675745}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2445561908254457
Fold 2 IBS: 0.2322436645595431
Fold 3 IBS: 0.22679961676523616
Fold 4 IBS: 0.2428997179098888
Fold 5 IBS: 0.2242895082761744
[I 2024-04-13 17:38:31,730] Trial 58 finished with value: 0.23415773966725767 and parameters: {'l1_ratio': 0.11781983803153451}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24088051466248822
Fold 2 IBS: 0.2324211036419245
Fold 3 IBS: 0.17915695298861245
Fold 4 IBS: 0.26115036817638204
Fold 5 IBS: 0.2039442749996006
[I 2024-04-13 17:38:32,709] Trial 59 finished with value: 0.22351064289380157 and parameters: {'l1_ratio': 0.17584204235203196}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24070769968492936
Fold 2 IBS: 0.2486155896404672
Fold 3 IBS: 0.1791509194456473
Fold 4 IBS: 0.26113868233281284
Fold 5 IBS: 0.20399117671781924
[I 2024-04-13 17:38:33,909] Trial 60 finished with value: 0.2267208135643352 and parameters: {'l1_ratio': 0.26708188996798005}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24087956910068906
Fold 2 IBS: 0.2323921863473675
Fold 3 IBS: 0.17920529968935503
Fold 4 IBS: 0.26110112298039145
Fold 5 IBS: 0.20395442679140918
[I 2024-04-13 17:38:35,080] Trial 61 finished with value: 0.22350652098184245 and parameters: {'l1_ratio': 0.16661410660158454}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24093555210314963
Fold 2 IBS: 0.23235305639709633
Fold 3 IBS: 0.22638852534057122
Fold 4 IBS: 0.26112512157486095
Fold 5 IBS: 0.20392356828422858
[I 2024-04-13 17:38:35,846] Trial 62 finished with value: 0.23294516473998134 and parameters: {'l1_ratio': 0.1540490008119354}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24526802565569786
Fold 2 IBS: 0.2321263954323
Fold 3 IBS: 0.22742937135061678
Fold 4 IBS: 0.24254358279444443
Fold 5 IBS: 0.22566301037708664
[I 2024-04-13 17:38:36,436] Trial 63 finished with value: 0.23460607712202913 and parameters: {'l1_ratio': 0.07379266927564629}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24080632096575544
Fold 2 IBS: 0.23254671652437478
Fold 3 IBS: 0.17920927892576138
Fold 4 IBS: 0.2611440536105945
Fold 5 IBS: 0.20396623063507716
[I 2024-04-13 17:38:37,382] Trial 64 finished with value: 0.22353452013231262 and parameters: {'l1_ratio': 0.21585257724133897}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24705296508120325
Fold 2 IBS: 0.2320376462945332
Fold 3 IBS: 0.22883935270131964
Fold 4 IBS: 0.24200954611618675
Fold 5 IBS: 0.22902686090112792
[I 2024-04-13 17:38:37,814] Trial 65 finished with value: 0.23579327421887414 and parameters: {'l1_ratio': 0.005387072257824671}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24442717215206658
Fold 2 IBS: 0.23227279192579092
Fold 3 IBS: 0.2266791384539238
Fold 4 IBS: 0.2429769680232201
Fold 5 IBS: 0.22403319212086015
[I 2024-04-13 17:38:38,321] Trial 66 finished with value: 0.23407785253517233 and parameters: {'l1_ratio': 0.12770607849850543}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.24083046522961266
Fold 2 IBS: 0.2324943416520838
Fold 3 IBS: 0.1791625670254273
Fold 4 IBS: 0.2611666865936859
Fold 5 IBS: 0.20396222887201373
[I 2024-04-13 17:38:39,515] Trial 67 finished with value: 0.22352325787456467 and parameters: {'l1_ratio': 0.19914198785101972}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2405848636211618
Fold 2 IBS: 0.2486170900588971
Fold 3 IBS: 0.17924243900131273
Fold 4 IBS: 0.2611038109301683
Fold 5 IBS: 0.2040088413892147
[I 2024-04-13 17:38:40,877] Trial 68 finished with value: 0.22671140900015097 and parameters: {'l1_ratio': 0.3216291311561653}. Best is trial 19 with value: 0.22350091365166636.
Fold 1 IBS: 0.2408727320429779
Fold 2 IBS: 0.23239714483806684
Fold 3 IBS: 0.1791966394442192
Fold 4 IBS: 0.2611099725626747
Fold 5 IBS: 0.20392665628614512
[I 2024-04-13 17:38:41,940] Trial 69 finished with value: 0.2235006290348167 and parameters: {'l1_ratio': 0.16819908030225064}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.2407414804560824
Fold 2 IBS: 0.2326061885263003
Fold 3 IBS: 0.1791388062304789
Fold 4 IBS: 0.26112319079534635
Fold 5 IBS: 0.20397003685378817
[I 2024-04-13 17:38:43,098] Trial 70 finished with value: 0.22351594057239926 and parameters: {'l1_ratio': 0.23498298021944547}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.240935495151649
Fold 2 IBS: 0.23235309433749837
Fold 3 IBS: 0.22638839966364369
Fold 4 IBS: 0.26112519516005556
Fold 5 IBS: 0.2039236005930296
[I 2024-04-13 17:38:43,923] Trial 71 finished with value: 0.23294515698117527 and parameters: {'l1_ratio': 0.15406124489846618}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24084296324993915
Fold 2 IBS: 0.23245043126961898
Fold 3 IBS: 0.17922638253540676
Fold 4 IBS: 0.26110149142105926
Fold 5 IBS: 0.2039334075098216
[I 2024-04-13 17:38:44,993] Trial 72 finished with value: 0.22351093519716914 and parameters: {'l1_ratio': 0.1851754871550513}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.2446281695310589
Fold 2 IBS: 0.23222862861290192
Fold 3 IBS: 0.22686584096773357
Fold 4 IBS: 0.24285854992669195
Fold 5 IBS: 0.22443118389111177
[I 2024-04-13 17:38:45,475] Trial 73 finished with value: 0.23420247458589963 and parameters: {'l1_ratio': 0.11261337206936062}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24067655399139307
Fold 2 IBS: 0.24870247942244844
Fold 3 IBS: 0.17923765116630963
Fold 4 IBS: 0.2610750814371028
Fold 5 IBS: 0.20397847745234152
[I 2024-04-13 17:38:46,726] Trial 74 finished with value: 0.22673404869391905 and parameters: {'l1_ratio': 0.2775899921373308}. Best is trial 69 with value: 0.2235006290348167.

Fold 1 IBS: 0.2408832088972797
Fold 2 IBS: 0.23238956578423497
Fold 3 IBS: 0.17920977092986604
Fold 4 IBS: 0.2610963777414903
Fold 5 IBS: 0.2039525027840345
[I 2024-04-13 17:38:48,116] Trial 75 finished with value: 0.2235062852273811 and parameters: {'l1_ratio': 0.16577591058395885}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24094936744845338
Fold 2 IBS: 0.23231707665139043
Fold 3 IBS: 0.22651229905598805
Fold 4 IBS: 0.2430891087275657
Fold 5 IBS: 0.2236810348665296
[I 2024-04-13 17:38:48,703] Trial 76 finished with value: 0.23330977734998543 and parameters: {'l1_ratio': 0.1423642477817916}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24511885091084448
Fold 2 IBS: 0.23214576160364095
Fold 3 IBS: 0.22730154999830518
Fold 4 IBS: 0.24260964197293514
Fold 5 IBS: 0.22537910377810255
[I 2024-04-13 17:38:49,092] Trial 77 finished with value: 0.23451098165276565 and parameters: {'l1_ratio': 0.08183241515980826}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.2396942727782378
Fold 2 IBS: 0.24874383807974912
Fold 3 IBS: 0.17925084188816684
Fold 4 IBS: 0.2610644011048088
Fold 5 IBS: 0.2042095083975169
[I 2024-04-13 17:38:49,976] Trial 78 finished with value: 0.2265925724496959 and parameters: {'l1_ratio': 0.8540978696988386}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.2407727917988323
Fold 2 IBS: 0.23257712253724577
Fold 3 IBS: 0.1791719270174971
Fold 4 IBS: 0.26108732359289
Fold 5 IBS: 0.20398301752995482
[I 2024-04-13 17:38:51,131] Trial 79 finished with value: 0.22351843649528397 and parameters: {'l1_ratio': 0.22560716508846312}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24623160880789174
Fold 2 IBS: 0.23205074855588517
Fold 3 IBS: 0.22821474055403035
Fold 4 IBS: 0.2422031086027022
Fold 5 IBS: 0.22747821147905967
[I 2024-04-13 17:38:51,549] Trial 80 finished with value: 0.23523568359991381 and parameters: {'l1_ratio': 0.03184825617478093}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24087940414557021
Fold 2 IBS: 0.23239230542492528
Fold 3 IBS: 0.17920508980822683
Fold 4 IBS: 0.26110133747002534
Fold 5 IBS: 0.20395451377317395
[I 2024-04-13 17:38:52,629] Trial 81 finished with value: 0.22350653012438432 and parameters: {'l1_ratio': 0.16665218489026146}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24081394299345124
Fold 2 IBS: 0.23250825423511134
Fold 3 IBS: 0.17914400787861948
Fold 4 IBS: 0.26109205980846845
Fold 5 IBS: 0.20397060796831037
[I 2024-04-13 17:38:53,626] Trial 82 finished with value: 0.2235057745767922 and parameters: {'l1_ratio': 0.20357256082023142}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24079675210548115
Fold 2 IBS: 0.232523017104443
Fold 3 IBS: 0.17924037428494496
Fold 4 IBS: 0.26111214850422054
Fold 5 IBS: 0.20394961722795485
[I 2024-04-13 17:38:54,833] Trial 83 finished with value: 0.2235243818454089 and parameters: {'l1_ratio': 0.2082796556672187}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24094174550141215
Fold 2 IBS: 0.23229585331484826
Fold 3 IBS: 0.22659004882310677
Fold 4 IBS: 0.2430360899128489
Fold 5 IBS: 0.2238447640600699
[I 2024-04-13 17:38:55,923] Trial 84 finished with value: 0.23334170032245716 and parameters: {'l1_ratio': 0.13538569510887843}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24492653276190737
Fold 2 IBS: 0.23217449107241692
Fold 3 IBS: 0.22713376777622024
Fold 4 IBS: 0.24270107875073973
Fold 5 IBS: 0.22501062649995432
[I 2024-04-13 17:38:56,522] Trial 85 finished with value: 0.2343892993722477 and parameters: {'l1_ratio': 0.09302599180084405}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24022869419970722
Fold 2 IBS: 0.2486584344082518
Fold 3 IBS: 0.1792759788212211
Fold 4 IBS: 0.2610997773304401
Fold 5 IBS: 0.2040961132740241
[I 2024-04-13 17:38:57,688] Trial 86 finished with value: 0.22667179960672884 and parameters: {'l1_ratio': 0.5196302291802515}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24070548003701311
Fold 2 IBS: 0.248621886484399
Fold 3 IBS: 0.1791487902953291
Fold 4 IBS: 0.26114104344439204
Fold 5 IBS: 0.2039922205038244
[I 2024-04-13 17:38:58,788] Trial 87 finished with value: 0.22672188415299152 and parameters: {'l1_ratio': 0.2678182346284702}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24086306123887452
Fold 2 IBS: 0.23246736607807444
Fold 3 IBS: 0.17920083458471
Fold 4 IBS: 0.2611277656952423
Fold 5 IBS: 0.20394497784502738
[I 2024-04-13 17:39:00,012] Trial 88 finished with value: 0.22352080108838573 and parameters: {'l1_ratio': 0.19056069711492576}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24062287799436816
Fold 2 IBS: 0.2486440730328618
Fold 3 IBS: 0.1791853013418662
Fold 4 IBS: 0.26113247165612136
Fold 5 IBS: 0.20400419120329105
[I 2024-04-13 17:39:01,400] Trial 89 finished with value: 0.22671778304570173 and parameters: {'l1_ratio': 0.29667979402847944}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24466876947748384
Fold 2 IBS: 0.23222050739003192
Fold 3 IBS: 0.22690290407669012
Fold 4 IBS: 0.2428359040359619
Fold 5 IBS: 0.2245107294006352
[I 2024-04-13 17:39:01,916] Trial 90 finished with value: 0.23422776287616057 and parameters: {'l1_ratio': 0.10976619269198881}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24089802638924462
Fold 2 IBS: 0.23240807379828013
Fold 3 IBS: 0.1791781070876601
Fold 4 IBS: 0.26112890443426756
Fold 5 IBS: 0.2039349781554647
[I 2024-04-13 17:39:03,020] Trial 91 finished with value: 0.2235096179729834 and parameters: {'l1_ratio': 0.1716883048644842}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24089949806891636
Fold 2 IBS: 0.23237799842266973
Fold 3 IBS: 0.22630790500512526
Fold 4 IBS: 0.2611709191988476
Fold 5 IBS: 0.20394377944865325
[I 2024-04-13 17:39:03,887] Trial 92 finished with value: 0.23294002002884243 and parameters: {'l1_ratio': 0.16207110397685423}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.24071673784048989
Fold 2 IBS: 0.23266307805334524
Fold 3 IBS: 0.17919224814639745
Fold 4 IBS: 0.2610928368887903
Fold 5 IBS: 0.20397095060563172
[I 2024-04-13 17:39:04,992] Trial 93 finished with value: 0.22352717030693095 and parameters: {'l1_ratio': 0.25351619949966864}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.2407955487747045
Fold 2 IBS: 0.23252406165100714
Fold 3 IBS: 0.1792389524716731
Fold 4 IBS: 0.26111359934945005
Fold 5 IBS: 0.20395025767872635
[I 2024-04-13 17:39:06,120] Trial 94 finished with value: 0.2235244839851122 and parameters: {'l1_ratio': 0.20861297276894075}. Best is trial 69 with value: 0.2235006290348167.
Fold 1 IBS: 0.2408754946073748
Fold 2 IBS: 0.23239513564265232
Fold 3 IBS: 0.17920012911712627
Fold 4 IBS: 0.26110640679845787
Fold 5 IBS: 0.2039250903620044
[I 2024-04-13 17:39:07,433] Trial 95 finished with value: 0.22350045130552312 and parameters: {'l1_ratio': 0.16755699923996967}. Best is trial 95 with value: 0.22350045130552312.
Fold 1 IBS: 0.24573302083714427
Fold 2 IBS: 0.23208021503135384
Fold 3 IBS: 0.2278163894137745
Fold 4 IBS: 0.2423619864890622
Fold 5 IBS: 0.22654124971253686
[I 2024-04-13 17:39:07,906] Trial 96 finished with value: 0.2349065722967743 and parameters: {'l1_ratio': 0.051680107562030314}. Best is trial 95 with value: 0.22350045130552312.
Fold 1 IBS: 0.24095950987754472
Fold 2 IBS: 0.2323108758594504
Fold 3 IBS: 0.22653462433269883
Fold 4 IBS: 0.24307374733858622
Fold 5 IBS: 0.22372798307640848
[I 2024-04-13 17:39:08,538] Trial 97 finished with value: 0.23332134809693775 and parameters: {'l1_ratio': 0.1403330049889729}. Best is trial 95 with value: 0.22350045130552312.
Fold 1 IBS: 0.24077104606078956
Fold 2 IBS: 0.2325787178000495
Fold 3 IBS: 0.17917004666161704
Fold 4 IBS: 0.26108940904640066
Fold 5 IBS: 0.203954828104311
[I 2024-04-13 17:39:09,488] Trial 98 finished with value: 0.22351280953463357 and parameters: {'l1_ratio': 0.22612035461339727}. Best is trial 95 with value: 0.22350045130552312.
Fold 1 IBS: 0.24507905325007132
Fold 2 IBS: 0.23215134645707305
Fold 3 IBS: 0.22726711587425577
Fold 4 IBS: 0.24262796657953078
Fold 5 IBS: 0.2253031030366484
[I 2024-04-13 17:39:10,018] Trial 99 finished with value: 0.23448571703951587 and parameters: {'l1_ratio': 0.0840682884807769}. Best is trial 95 with value: 0.22350045130552312.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.22350045130552312], datetime_start=datetime.datetime(2024, 4, 13, 17, 39, 6, 149661), datetime_complete=datetime.datetime(2024, 4, 13, 17, 39, 7, 432028), params={'l1_ratio': 0.16755699923996967}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=95, value=None)


* Best Score for IBS:
 0.22350045130552312

In [53]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [54]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.639
train_ibs:  0.224

#### Test

In [55]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [56]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.651954326927192)

test_cindex : 0.567

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.16755699923996967)

test_ibs:  0.229

In [57]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [58]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:39:10,465] A new study created in memory with name: no-name-c9d4914a-99f4-4ed9-a311-b888ad08b3f4

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:39:18,418] Trial 0 finished with value: 0.6177885807850675 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6177885807850675.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 17:39:24,060] Trial 1 finished with value: 0.6402989429173871 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 17:39:28,945] Trial 2 finished with value: 0.6393357242915708 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:39:30,722] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:39:32,893] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6402989429173871.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:39:42,781] Trial 5 finished with value: 0.6471658831186169 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 17:39:52,128] Trial 6 finished with value: 0.6344921146735147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:39:56,970] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 17:40:09,997] Trial 8 finished with value: 0.5180257510729614 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.5944206008583691
[I 2024-04-13 17:40:17,090] Trial 9 finished with value: 0.6262562593650948 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:40:17,937] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 17:40:21,600] Trial 11 finished with value: 0.640537452234508 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 5 with value: 0.6471658831186169.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 17:40:24,575] Trial 12 finished with value: 0.6472725256821195 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8064195611120726, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 12 with value: 0.6472725256821195.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6127659574468085
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 17:40:25,074] Trial 13 finished with value: 0.6354800902960902 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 7, 'oob_score': False, 'max_samples': 0.4941394758404661, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 12 with value: 0.6472725256821195.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:40:26,911] Trial 14 finished with value: 0.7002369632470599 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 120, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10429920715486261, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6453488372093024

Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:40:29,226] Trial 15 finished with value: 0.6757811535432272 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 120, 'oob_score': True, 'max_samples': 0.9847369290686088, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17574628605071868, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 17:40:31,397] Trial 16 finished with value: 0.6771580986582885 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.962365055520953, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19037781478052387, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6416309012875536
[I 2024-04-13 17:40:33,968] Trial 17 finished with value: 0.6714707475493069 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.8699768148803853, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20705158222188405, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 17:40:35,313] Trial 18 finished with value: 0.6567223411334931 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 58, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6373390557939914
[I 2024-04-13 17:40:39,046] Trial 19 finished with value: 0.671915912796344 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.7093777033655436, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07770947342327489, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 17:40:41,124] Trial 20 finished with value: 0.68201262766852 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.8574334183065578, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16825759122066408, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6459227467811158
[I 2024-04-13 17:40:42,570] Trial 21 finished with value: 0.6828780051799364 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 65, 'oob_score': True, 'max_samples': 0.8574739496774684, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 17:40:44,002] Trial 22 finished with value: 0.6954786045995129 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.8339758748294697, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14609188473654175, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 17:40:44,605] Trial 23 finished with value: 0.6999767612780623 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 21, 'oob_score': True, 'max_samples': 0.7847143847565936, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13226034227314248, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6872340425531915
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 17:40:45,056] Trial 24 finished with value: 0.6577607816323275 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.7775916898124314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25150584936274806, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6545064377682404
[I 2024-04-13 17:40:46,028] Trial 25 finished with value: 0.6783623065010328 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13486370381501434, 'warm_start': True}. Best is trial 14 with value: 0.7002369632470599.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6974248927038627
[I 2024-04-13 17:40:47,689] Trial 26 finished with value: 0.7005252977723723 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 91, 'oob_score': True, 'max_samples': 0.5349306463888053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06566365555656244, 'warm_start': True}. Best is trial 26 with value: 0.7005252977723723.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 17:40:49,229] Trial 27 finished with value: 0.7061005790200177 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.5366581083873809, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06208957998994368, 'warm_start': True}. Best is trial 27 with value: 0.7061005790200177.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6845493562231759
[I 2024-04-13 17:40:52,614] Trial 28 finished with value: 0.6887400143879626 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.41379803894855116, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07805190635410612, 'warm_start': True}. Best is trial 27 with value: 0.7061005790200177.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.7253218884120172
[I 2024-04-13 17:40:55,545] Trial 29 finished with value: 0.7116053815973882 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.5248192039443108, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0554252254423035, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 17:40:58,272] Trial 30 finished with value: 0.7010446660346952 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.5345414788093061, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03755841239520112, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 17:41:00,832] Trial 31 finished with value: 0.7000756268928836 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.5019192620095752, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.050771418210883164, 'warm_start': True}. Best is trial 29 with value: 0.7116053815973882.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 17:41:03,954] Trial 32 finished with value: 0.7177295061567273 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.563642711374241, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05266275392679234, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.721030042918455
[I 2024-04-13 17:41:07,616] Trial 33 finished with value: 0.7049756930439305 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.35232498791610145, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00379084860293024, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:41:11,297] Trial 34 finished with value: 0.7010699790361788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.3828093578201666, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0026062845432726807, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 17:41:14,096] Trial 35 finished with value: 0.6556598127697459 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.26793001302903535, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0862146443224848, 'warm_start': True}. Best is trial 32 with value: 0.7177295061567273.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-13 17:41:18,773] Trial 36 finished with value: 0.7288309903966594 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.3445095149903548, 'max_features': None, 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.7288309903966594.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:41:24,393] Trial 37 finished with value: 0.7549756456347672 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.5874006073245895, 'max_features': None, 'min_weight_fraction_leaf': 0.051378997578725064, 'warm_start': True}. Best is trial 37 with value: 0.7549756456347672.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7982832618025751
[I 2024-04-13 17:41:30,460] Trial 38 finished with value: 0.7411193039013269 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.42872870036644545, 'max_features': None, 'min_weight_fraction_leaf': 0.03685839885089406, 'warm_start': True}. Best is trial 37 with value: 0.7549756456347672.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:41:37,416] Trial 39 finished with value: 0.7764777161516213 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.5898221765815288, 'max_features': None, 'min_weight_fraction_leaf': 0.0280794008099322, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:41:42,640] Trial 40 finished with value: 0.7453537247989861 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.44424040796819986, 'max_features': None, 'min_weight_fraction_leaf': 0.029813810847214628, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:41:49,720] Trial 41 finished with value: 0.767706324749998 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.42993466896213306, 'max_features': None, 'min_weight_fraction_leaf': 0.02699423331352132, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 17:41:54,744] Trial 42 finished with value: 0.7558493030880561 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.43835115795914964, 'max_features': None, 'min_weight_fraction_leaf': 0.03261747288898426, 'warm_start': True}. Best is trial 39 with value: 0.7764777161516213.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:42:00,726] Trial 43 finished with value: 0.7805052982197098 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.6182013697142779, 'max_features': None, 'min_weight_fraction_leaf': 0.02680908937928254, 'warm_start': True}. Best is trial 43 with value: 0.7805052982197098.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 17:42:06,961] Trial 44 finished with value: 0.7199270020227763 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.6260162353120974, 'max_features': None, 'min_weight_fraction_leaf': 0.09652293104879651, 'warm_start': True}. Best is trial 43 with value: 0.7805052982197098.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:42:09,831] Trial 45 finished with value: 0.7876297777014609 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.6932069026339767, 'max_features': None, 'min_weight_fraction_leaf': 0.02673421337104168, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.5858369098712446
[I 2024-04-13 17:42:23,166] Trial 46 finished with value: 0.6175266138918902 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.713175685335591, 'max_features': None, 'min_weight_fraction_leaf': 0.02263809195586287, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:42:26,226] Trial 47 finished with value: 0.7024716099360828 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.6640283145362862, 'max_features': None, 'min_weight_fraction_leaf': 0.11937729206282155, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:33,278] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.4725841795598701, 'max_features': None, 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 17:42:36,785] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.2076878129262199, 'max_features': None, 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6492248062015504
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:42:41,696] Trial 50 finished with value: 0.649042644861519 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.679318106876105, 'max_features': None, 'min_weight_fraction_leaf': 0.2758707435072836, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:42:45,587] Trial 51 finished with value: 0.7637338414488053 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.5821155504207499, 'max_features': None, 'min_weight_fraction_leaf': 0.02422764197259524, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:42:49,139] Trial 52 finished with value: 0.7637338414488053 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.5780114655400654, 'max_features': None, 'min_weight_fraction_leaf': 0.019612908407631094, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.759656652360515
[I 2024-04-13 17:42:53,090] Trial 53 finished with value: 0.7330142244474321 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.58647202928343, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014895484544909543, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8497854077253219
[I 2024-04-13 17:42:56,566] Trial 54 finished with value: 0.7502209765566825 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.7451532491332802, 'max_features': None, 'min_weight_fraction_leaf': 0.08067250770106202, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:42:59,163] Trial 55 finished with value: 0.7747108750614803 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.6202755843283627, 'max_features': None, 'min_weight_fraction_leaf': 0.022470717574527028, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.5836909871244635
[I 2024-04-13 17:43:07,620] Trial 56 finished with value: 0.617244798143204 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.6429003803329312, 'max_features': None, 'min_weight_fraction_leaf': 0.22757335863523978, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8326180257510729
[I 2024-04-13 17:43:10,772] Trial 57 finished with value: 0.7539260229172815 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.6226007657277326, 'max_features': None, 'min_weight_fraction_leaf': 0.038788044099769756, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 17:43:14,014] Trial 58 finished with value: 0.7099977128256824 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.6932738670326789, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10056372049643875, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:43:16,685] Trial 59 finished with value: 0.7596304057836407 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 290, 'oob_score': False, 'max_samples': 0.7323761414424763, 'max_features': None, 'min_weight_fraction_leaf': 0.06672040150433087, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.5815450643776824
[I 2024-04-13 17:43:29,375] Trial 60 finished with value: 0.6241729860798608 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.4903074221697629, 'max_features': None, 'min_weight_fraction_leaf': 0.11959785503226739, 'warm_start': False}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:43:33,323] Trial 61 finished with value: 0.7804185419955325 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.5775531242934729, 'max_features': None, 'min_weight_fraction_leaf': 0.014771588904444915, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:43:37,005] Trial 62 finished with value: 0.7818313762245508 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.6120312661504053, 'max_features': None, 'min_weight_fraction_leaf': 0.01656914948618143, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:43:40,444] Trial 63 finished with value: 0.7763007762144775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.6357815970769084, 'max_features': None, 'min_weight_fraction_leaf': 0.04354887768929718, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:43:43,666] Trial 64 finished with value: 0.7579098162543703 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.6127459487402497, 'max_features': None, 'min_weight_fraction_leaf': 0.04650833605121199, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8283261802575107
[I 2024-04-13 17:43:47,958] Trial 65 finished with value: 0.7444188242864717 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.6523889675617967, 'max_features': None, 'min_weight_fraction_leaf': 0.06842934943082835, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:43:51,657] Trial 66 finished with value: 0.7867565440912282 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.6881590145066517, 'max_features': None, 'min_weight_fraction_leaf': 0.011806153077869749, 'warm_start': True}. Best is trial 45 with value: 0.7876297777014609.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8798283261802575
[I 2024-04-13 17:43:55,153] Trial 67 finished with value: 0.7896209612521833 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.7631123974277301, 'max_features': None, 'min_weight_fraction_leaf': 0.0022885590177692122, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:43:58,940] Trial 68 finished with value: 0.7837247575028984 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.7615347181121479, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0024769456224402846, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:44:02,208] Trial 69 finished with value: 0.7778975587933437 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 417, 'oob_score': False, 'max_samples': 0.7726300856584892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01088116997697249, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:44:05,831] Trial 70 finished with value: 0.7838043518792469 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.9016742863309287, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007729052885137196, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:44:10,516] Trial 71 finished with value: 0.7838875271795097 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.9017461575502412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0068241563825637295, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:44:18,706] Trial 72 finished with value: 0.7790161865505592 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 495, 'oob_score': False, 'max_samples': 0.9009406869567084, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0021418267435436436, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-13 17:44:26,464] Trial 73 finished with value: 0.7830148443991681 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 456, 'oob_score': False, 'max_samples': 0.9085841532130327, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0030802629542528654, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8755364806866953
[I 2024-04-13 17:44:38,334] Trial 74 finished with value: 0.7831886272554539 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.9228420326396749, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005019150622141426, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:44:43,575] Trial 75 finished with value: 0.7757963034243145 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9457439444265902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0018763322411427912, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:44:46,760] Trial 76 finished with value: 0.7417173037889626 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.8983343226238335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06474782967395624, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:44:50,538] Trial 77 finished with value: 0.7632234783399822 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8332435855398501, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.048186815269347504, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:44:54,115] Trial 78 finished with value: 0.7813702683223316 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.9259409338032202, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0014115169159075848, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 17:44:57,489] Trial 79 finished with value: 0.6518913485226081 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8671236023505134, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34696749792453063, 'warm_start': True}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 17:45:09,205] Trial 80 finished with value: 0.6287361870740857 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.7963493279897067, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03726915892555499, 'warm_start': False}. Best is trial 67 with value: 0.7896209612521833.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:45:12,227] Trial 81 finished with value: 0.7898421579172852 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9937352645069003, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014733302673387358, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-13 17:45:15,157] Trial 82 finished with value: 0.787557081185243 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9926689295251143, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012807159371837533, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:45:18,850] Trial 83 finished with value: 0.7827942427178591 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9750237459208526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01606804819012205, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:45:21,732] Trial 84 finished with value: 0.7401126651112803 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.9913824226489636, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08946868256617803, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8454935622317596
[I 2024-04-13 17:45:24,700] Trial 85 finished with value: 0.7636828908699766 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.9447103169089868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0557070761228824, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:45:28,649] Trial 86 finished with value: 0.7779481019633775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.9606973339596948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03905413442222396, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 17:45:32,282] Trial 87 finished with value: 0.6830016680735692 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.883088751579364, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0725768406343007, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-13 17:45:36,598] Trial 88 finished with value: 0.7756663092990286 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.8207971016698734, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012051717505267413, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 17:45:40,857] Trial 89 finished with value: 0.7675503095124208 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.9996188810038052, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030894883442076228, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 17:45:44,161] Trial 90 finished with value: 0.7444043407354559 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 413, 'oob_score': False, 'max_samples': 0.7655917999374031, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.059853014276037855, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8798283261802575
[I 2024-04-13 17:45:48,049] Trial 91 finished with value: 0.7880273357541754 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.8546671993080971, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00043463511590633407, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7723404255319148
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 17:45:51,682] Trial 92 finished with value: 0.7014810841424285 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.9327128334728044, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013208403993555372, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:45:55,807] Trial 93 finished with value: 0.7802990266542915 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.8426290761275549, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030993362135028464, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-13 17:45:59,065] Trial 94 finished with value: 0.7714547788810922 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.9169001665130876, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04427068760850137, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-13 17:46:02,668] Trial 95 finished with value: 0.7826429100639786 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 464, 'oob_score': False, 'max_samples': 0.9695736653081121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02200415575270175, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.6647286821705426
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 17:46:05,803] Trial 96 finished with value: 0.6667466867766902 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8866673994678815, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00010254419006395848, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 17:46:08,922] Trial 97 finished with value: 0.6585055548372436 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.743952091363973, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012121939934777472, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 17:46:20,383] Trial 98 finished with value: 0.627071900642681 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8087130156519865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032634018282811726, 'warm_start': False}. Best is trial 81 with value: 0.7898421579172852.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7870722433460076

[I 2024-04-13 17:46:23,940] A new study created in memory with name: no-name-de53b32f-0824-4998-b168-ae409bc9991e

Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 17:46:23,905] Trial 99 finished with value: 0.7500076372617474 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.6902938777535903, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04784650401125385, 'warm_start': True}. Best is trial 81 with value: 0.7898421579172852.


* Best trial for C-index:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.7898421579172852], datetime_start=datetime.datetime(2024, 4, 13, 17, 45, 9, 220291), datetime_complete=datetime.datetime(2024, 4, 13, 17, 45, 12, 226623), params={'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9937352645069003, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014733302673387358, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=81, value=None)


* Best Score for C-index:
 0.7898421579172852

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23819032549148034
Fold 2 IBS: 0.23121788001563107
Fold 3 IBS: 0.21979369823749267
Fold 4 IBS: 0.2318228322973839
Fold 5 IBS: 0.21024821548260486
[I 2024-04-13 17:46:36,175] Trial 0 finished with value: 0.22625459030491854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.22625459030491854.
Fold 1 IBS: 0.2327303554970621
Fold 2 IBS: 0.22773051352570262
Fold 3 IBS: 0.21684304094654686
Fold 4 IBS: 0.2287850855661341
Fold 5 IBS: 0.21336280816660322
[I 2024-04-13 17:46:38,449] Trial 1 finished with value: 0.22389036074040977 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-13 17:46:40,174] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-13 17:46:46,962] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-13 17:46:51,971] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.24195276719924078
Fold 2 IBS: 0.23158306192048977
Fold 3 IBS: 0.21085268504232352
Fold 4 IBS: 0.22590092577347623
Fold 5 IBS: 0.2158343974194969
[I 2024-04-13 17:46:59,613] Trial 5 finished with value: 0.22522476747100542 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.22389036074040977.
Fold 1 IBS: 0.23967841421337877
Fold 2 IBS: 0.22235525504764858
Fold 3 IBS: 0.21859475882848345
Fold 4 IBS: 0.2286576795074638
Fold 5 IBS: 0.2076537454704683
[I 2024-04-13 17:47:06,501] Trial 6 finished with value: 0.22338797061348856 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.24345153214227594
Fold 2 IBS: 0.23065480198027405
Fold 3 IBS: 0.22931062857448625
Fold 4 IBS: 0.2384177765763348
Fold 5 IBS: 0.22787014183210574
[I 2024-04-13 17:47:15,843] Trial 7 finished with value: 0.2339409762210954 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-13 17:47:32,682] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.22338797061348856.
Fold 1 IBS: 0.2320102439831575
Fold 2 IBS: 0.22451454416835206
Fold 3 IBS: 0.2177950757126267
Fold 4 IBS: 0.22911956144415363
Fold 5 IBS: 0.2109401120435157
[I 2024-04-13 17:47:35,796] Trial 9 finished with value: 0.2228759074703611 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-13 17:47:40,880] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1655981152594652}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.26024444970570754
Fold 2 IBS: 0.2216356331948992
Fold 3 IBS: 0.20646208866549096
Fold 4 IBS: 0.2236987194979317
Fold 5 IBS: 0.20823816667941644
[I 2024-04-13 17:47:41,439] Trial 11 finished with value: 0.22405581154868917 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9904090680670613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31430530876132207}. Best is trial 9 with value: 0.2228759074703611.
Fold 1 IBS: 0.23302253676596166
Fold 2 IBS: 0.22350006799707825
Fold 3 IBS: 0.2117261996244006
Fold 4 IBS: 0.23014872528096708
Fold 5 IBS: 0.21131996892731336
[I 2024-04-13 17:47:47,632] Trial 12 finished with value: 0.2219434997191442 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9777827337837477, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3324053831839262}. Best is trial 12 with value: 0.2219434997191442.
Fold 1 IBS: 0.2334167482692937
Fold 2 IBS: 0.22462815107178444
Fold 3 IBS: 0.21415254610318984
Fold 4 IBS: 0.22735181638107305
Fold 5 IBS: 0.20943018161274876
[I 2024-04-13 17:47:52,515] Trial 13 finished with value: 0.221795888687618 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.9736995438315953, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21818725312797213}. Best is trial 13 with value: 0.221795888687618.
Fold 1 IBS: 0.23281845581582267
Fold 2 IBS: 0.22270871101965733
Fold 3 IBS: 0.21190072211209907
Fold 4 IBS: 0.22954507565286003
Fold 5 IBS: 0.2097789741690662
[I 2024-04-13 17:47:58,239] Trial 14 finished with value: 0.22135038775390106 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8117746868873079, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2645968579224677}. Best is trial 14 with value: 0.22135038775390106.
Fold 1 IBS: 0.23363330111712122
Fold 2 IBS: 0.22772251294499274
Fold 3 IBS: 0.21313363370892885
Fold 4 IBS: 0.2311943990289551
Fold 5 IBS: 0.2118872809428859
[I 2024-04-13 17:48:05,297] Trial 15 finished with value: 0.22351422554857675 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.8199794929905286, 'max_features': 'auto', 'min_weight_fraction_leaf': 9.233281859852283e-05}. Best is trial 14 with value: 0.22135038775390106.

Fold 1 IBS: 0.23309849867702975
Fold 2 IBS: 0.2238801862611814
Fold 3 IBS: 0.20957498925944693
Fold 4 IBS: 0.22916161954772554
Fold 5 IBS: 0.20966367383054058
[I 2024-04-13 17:48:12,908] Trial 16 finished with value: 0.22107579351518486 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.7702473623171299, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25854433873892946}. Best is trial 16 with value: 0.22107579351518486.
Fold 1 IBS: 0.23207571367115706
Fold 2 IBS: 0.22301648270111882
Fold 3 IBS: 0.20929958475920116
Fold 4 IBS: 0.22683443304818943
Fold 5 IBS: 0.20959031967828567
[I 2024-04-13 17:48:27,729] Trial 17 finished with value: 0.2201633067715904 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.7723653893351333, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26653765665911155}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2463404995719331
Fold 2 IBS: 0.2321448856668435
Fold 3 IBS: 0.22959259113294117
Fold 4 IBS: 0.2415266314104949
Fold 5 IBS: 0.23024189043397938
[I 2024-04-13 17:48:44,285] Trial 18 finished with value: 0.2359692996432384 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.7546903089061138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38366131019449645}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23303888011332288
Fold 2 IBS: 0.22300960933547007
Fold 3 IBS: 0.20920134919025463
Fold 4 IBS: 0.22816759153382105
Fold 5 IBS: 0.21046314793606172
[I 2024-04-13 17:48:53,825] Trial 19 finished with value: 0.22077611562178606 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.6166062996487705, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13117892225993338}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23835822553986638
Fold 2 IBS: 0.22799957337023416
Fold 3 IBS: 0.2255839289968672
Fold 4 IBS: 0.2347799777347254
Fold 5 IBS: 0.22413835268072815
[I 2024-04-13 17:49:07,593] Trial 20 finished with value: 0.23017201166448426 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.36221293246103303, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11290492399019064}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23174517627510863
Fold 2 IBS: 0.22311183326872192
Fold 3 IBS: 0.2134752532935891
Fold 4 IBS: 0.22849974415037372
Fold 5 IBS: 0.21356235141371618
[I 2024-04-13 17:49:17,284] Trial 21 finished with value: 0.22207887168030188 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.6196799597483587, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2567596687243825}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2332544171438238
Fold 2 IBS: 0.22319768331574052
Fold 3 IBS: 0.20996383118108564
Fold 4 IBS: 0.22670496467093834
Fold 5 IBS: 0.2102618867189479
[I 2024-04-13 17:49:25,186] Trial 22 finished with value: 0.22067655660610724 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 1, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.4546238642538813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13974116057386782}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2310699507275024
Fold 2 IBS: 0.22303094537287663
Fold 3 IBS: 0.21098495554623686
Fold 4 IBS: 0.22669642139137772
Fold 5 IBS: 0.2112926777812192
[I 2024-04-13 17:49:37,375] Trial 23 finished with value: 0.22061499016384256 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.2322016436936384
Fold 2 IBS: 0.22349336637777067
Fold 3 IBS: 0.21006996461569238
Fold 4 IBS: 0.22527052958323776
Fold 5 IBS: 0.21049333696088765
[I 2024-04-13 17:49:49,824] Trial 24 finished with value: 0.2203057682462454 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.46113861699976405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020430563448902872}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.22991354874075207
Fold 2 IBS: 0.22444368768443465
Fold 3 IBS: 0.21207565297554787
Fold 4 IBS: 0.2262663752096743
Fold 5 IBS: 0.21145135976011514
[I 2024-04-13 17:50:00,494] Trial 25 finished with value: 0.22083012487410478 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.2381911851795994, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.036226389884873186}. Best is trial 17 with value: 0.2201633067715904.
Fold 1 IBS: 0.23060883914260805
Fold 2 IBS: 0.22297755155674684
Fold 3 IBS: 0.2101589513975745
Fold 4 IBS: 0.22604712726802575
Fold 5 IBS: 0.21099290824592037
[I 2024-04-13 17:50:16,772] Trial 26 finished with value: 0.22015707552217512 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.4704864355905733, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0010277467041755056}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23046923596128613
Fold 2 IBS: 0.2240015491036018
Fold 3 IBS: 0.21086502402097726
Fold 4 IBS: 0.226142024960214
Fold 5 IBS: 0.21088248515587224
[I 2024-04-13 17:50:33,381] Trial 27 finished with value: 0.22047206384039025 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.27394238361068307, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.013617435329595393}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23471452628920897
Fold 2 IBS: 0.22673547857955847
Fold 3 IBS: 0.21103982953561207
Fold 4 IBS: 0.22446765617728826
Fold 5 IBS: 0.21450015223615418
[I 2024-04-13 17:50:53,068] Trial 28 finished with value: 0.2222915285635644 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.48498687769327536, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0641292220811886}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23136991564996087
Fold 2 IBS: 0.22204971565032036
Fold 3 IBS: 0.21300464981609682
Fold 4 IBS: 0.22675182096688823
Fold 5 IBS: 0.21182202421691915
[I 2024-04-13 17:51:12,332] Trial 29 finished with value: 0.22099962526003708 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.3571755626038756, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03807390698388844}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24606642350611257
Fold 2 IBS: 0.2321923882606996
Fold 3 IBS: 0.22988609347650055
Fold 4 IBS: 0.2412002464153435
Fold 5 IBS: 0.23034386795139541
[I 2024-04-13 17:51:25,697] Trial 30 finished with value: 0.2359378039220103 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.2172618637182342, 'max_features': None, 'min_weight_fraction_leaf': 0.19986328912293344}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23160771794643292
Fold 2 IBS: 0.22646129177037175
Fold 3 IBS: 0.21045869707390338
Fold 4 IBS: 0.22410007258120104

Fold 5 IBS: 0.2108108318582224
[I 2024-04-13 17:51:40,922] Trial 31 finished with value: 0.2206877222460263 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.2868712535426494, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.021231453689495153}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24659836091991297
Fold 2 IBS: 0.23212875696426277
Fold 3 IBS: 0.23013831975076382
Fold 4 IBS: 0.24109773536375373
Fold 5 IBS: 0.22997643124737513
[I 2024-04-13 17:51:53,573] Trial 32 finished with value: 0.23598792084921366 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.15457524910822473, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004932622259272009}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23197141083929648
Fold 2 IBS: 0.22199313349588728
Fold 3 IBS: 0.2125662998256947
Fold 4 IBS: 0.2269154171060468
Fold 5 IBS: 0.2125401699948321
[I 2024-04-13 17:52:11,004] Trial 33 finished with value: 0.22119728625235147 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.3835202498388115, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09218354615163335}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23217381359662775
Fold 2 IBS: 0.22448808064455156
Fold 3 IBS: 0.20986169319903394
Fold 4 IBS: 0.22593776518550224
Fold 5 IBS: 0.210892650964984
[I 2024-04-13 17:52:26,229] Trial 34 finished with value: 0.22067080071813988 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 408, 'oob_score': True, 'max_samples': 0.5426821039862857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04500199428375251}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23289853012973177
Fold 2 IBS: 0.228024993142558
Fold 3 IBS: 0.21255692441217353
Fold 4 IBS: 0.22694758734723536
Fold 5 IBS: 0.21091359093683118
[I 2024-04-13 17:52:43,807] Trial 35 finished with value: 0.22226832519370596 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.6981514158760593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16320167359786183}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2350546735426517
Fold 2 IBS: 0.236789743880471
Fold 3 IBS: 0.22212188563214683
Fold 4 IBS: 0.23185305826049626
Fold 5 IBS: 0.21752491954865782
[I 2024-04-13 17:53:04,270] Trial 36 finished with value: 0.22866885617288474 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.49714834826170234, 'max_features': None, 'min_weight_fraction_leaf': 0.09979466708192791}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24022913171172267
Fold 2 IBS: 0.22874946375008556
Fold 3 IBS: 0.21290965440875198
Fold 4 IBS: 0.22557654547485015
Fold 5 IBS: 0.21565985272908825
[I 2024-04-13 17:53:21,948] Trial 37 finished with value: 0.22462492961489972 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.6134779412492984, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.053624327533504934}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2325547869295493
Fold 2 IBS: 0.225529082398541
Fold 3 IBS: 0.21138715556254012
Fold 4 IBS: 0.22282613113953292
Fold 5 IBS: 0.21014751804243587
[I 2024-04-13 17:53:36,576] Trial 38 finished with value: 0.22048893481451987 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.29184797119319694, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017087153731481407}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23561025683041087
Fold 2 IBS: 0.22941932225139652
Fold 3 IBS: 0.21631460646944745
Fold 4 IBS: 0.23234709305478357
Fold 5 IBS: 0.21076474347276042
[I 2024-04-13 17:53:56,839] Trial 39 finished with value: 0.22489120441575977 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.40430675587035536, 'max_features': None, 'min_weight_fraction_leaf': 0.08714563166723727}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24678613059437637
Fold 2 IBS: 0.2321725909539564
Fold 3 IBS: 0.22944195803388415
Fold 4 IBS: 0.24150527562231744
Fold 5 IBS: 0.230370380894624
[I 2024-04-13 17:54:09,554] Trial 40 finished with value: 0.23605526721983167 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.5739995513235784, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41526515128052643}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23321286691758872
Fold 2 IBS: 0.2279849928934213
Fold 3 IBS: 0.2117308992197816
Fold 4 IBS: 0.2242204616828136
Fold 5 IBS: 0.20935348900548092
[I 2024-04-13 17:54:24,939] Trial 41 finished with value: 0.22130054194381726 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.315246808599681, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02048652160594618}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2316766890229806
Fold 2 IBS: 0.22411125621421446
Fold 3 IBS: 0.21036674914110157
Fold 4 IBS: 0.22434994497665503
Fold 5 IBS: 0.21106333692808993
[I 2024-04-13 17:54:42,209] Trial 42 finished with value: 0.22031359525660835 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.26574428925186755, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019168305255890875}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2459242180260377
Fold 2 IBS: 0.23217022029472845
Fold 3 IBS: 0.2300031028267955
Fold 4 IBS: 0.24121482096141833
Fold 5 IBS: 0.23030067078583316
[I 2024-04-13 17:54:59,176] Trial 43 finished with value: 0.23592260657896263 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.22277971365249755, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24631410665989734
Fold 2 IBS: 0.23210802473720302
Fold 3 IBS: 0.2302521611117555
Fold 4 IBS: 0.2410435305102926
Fold 5 IBS: 0.23003859251113234
[I 2024-04-13 17:55:14,331] Trial 44 finished with value: 0.23595128310605612 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.1383644314551697, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0686728787591377}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24617592132985935
Fold 2 IBS: 0.2322080714687311
Fold 3 IBS: 0.2295331673330916
Fold 4 IBS: 0.2414957007697489
Fold 5 IBS: 0.23031590144856742
[I 2024-04-13 17:55:32,701] Trial 45 finished with value: 0.23594575246999966 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.5172890166610269, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30571763583075945}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23995673698361222
Fold 2 IBS: 0.22972034149382584
Fold 3 IBS: 0.2273789621853455
Fold 4 IBS: 0.2372388025033728
Fold 5 IBS: 0.2259009708948768
[I 2024-04-13 17:55:52,311] Trial 46 finished with value: 0.23203916281220663 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.1873692143114088, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03681920016521466}. Best is trial 26 with value: 0.22015707552217512.

Fold 1 IBS: 0.23103878287252402
Fold 2 IBS: 0.22628918231285983
Fold 3 IBS: 0.2133979486579942
Fold 4 IBS: 0.22430579562693312
Fold 5 IBS: 0.21153361401748674
[I 2024-04-13 17:56:10,149] Trial 47 finished with value: 0.22131306469755957 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.43491671167283275, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07826676341691717}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2461442212529148
Fold 2 IBS: 0.23226781881803804
Fold 3 IBS: 0.22981312479103597
Fold 4 IBS: 0.24139414747597257
Fold 5 IBS: 0.2304782442201671
[I 2024-04-13 17:56:28,307] Trial 48 finished with value: 0.23601951131162568 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 447, 'oob_score': False, 'max_samples': 0.2751094610735481, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24643065427838096
Fold 2 IBS: 0.23223464296746826
Fold 3 IBS: 0.22968175844773792
Fold 4 IBS: 0.2413651638178947
Fold 5 IBS: 0.23015719969071047
[I 2024-04-13 17:56:48,893] Trial 49 finished with value: 0.23597388384043844 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.3426311861680858, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37411897805446126}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23653547645771292
Fold 2 IBS: 0.23891649468883286
Fold 3 IBS: 0.22623605262377863
Fold 4 IBS: 0.23760952706404054
Fold 5 IBS: 0.21274600173139968
[I 2024-04-13 17:57:01,496] Trial 50 finished with value: 0.23040871051315293 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': None, 'min_weight_fraction_leaf': 0.0023139662763776523}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23205733305111126
Fold 2 IBS: 0.22540170926715883
Fold 3 IBS: 0.21136019029919015
Fold 4 IBS: 0.2235188735459925
Fold 5 IBS: 0.2104011228556449
[I 2024-04-13 17:57:17,514] Trial 51 finished with value: 0.22054784580381953 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.28310200045220396, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018168221852795943}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2467425883724255
Fold 2 IBS: 0.23229207390802017
Fold 3 IBS: 0.229806458577059
Fold 4 IBS: 0.24117087537338566
Fold 5 IBS: 0.23029838496464933
[I 2024-04-13 17:57:31,795] Trial 52 finished with value: 0.23606207623910797 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.31519339436661903, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23722810776929834}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23448850473409952
Fold 2 IBS: 0.22628680170858836
Fold 3 IBS: 0.2110553567502054
Fold 4 IBS: 0.2248272006707438
Fold 5 IBS: 0.21045438124734223
[I 2024-04-13 17:57:48,141] Trial 53 finished with value: 0.22142244902219588 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.25208751122540896, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028071010742289564}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2457543637764612
Fold 2 IBS: 0.23215641755689168
Fold 3 IBS: 0.23000347609635255
Fold 4 IBS: 0.24126499095998308
Fold 5 IBS: 0.2304832070970648
[I 2024-04-13 17:58:07,803] Trial 54 finished with value: 0.23593249109735065 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.1944118385287112, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00865239972784028}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2468623556579978
Fold 2 IBS: 0.23219151424480894
Fold 3 IBS: 0.23027924136404326
Fold 4 IBS: 0.24093725814526556
Fold 5 IBS: 0.22930915051617384
[I 2024-04-13 17:58:18,544] Trial 55 finished with value: 0.23591590398565784 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.10569714025611779, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.058450491403396476}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24642872356499093
Fold 2 IBS: 0.23205942594736154
Fold 3 IBS: 0.22994434058519342
Fold 4 IBS: 0.24150107878356789
Fold 5 IBS: 0.23008272411407127
[I 2024-04-13 17:58:20,659] Trial 56 finished with value: 0.23600325859903698 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 51, 'oob_score': False, 'max_samples': 0.569633571031224, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28766369733548897}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2464642877720641
Fold 2 IBS: 0.23233994540501388
Fold 3 IBS: 0.22968667048933009
Fold 4 IBS: 0.24135786670781292
Fold 5 IBS: 0.23035458313442783
[I 2024-04-13 17:58:29,956] Trial 57 finished with value: 0.2360406707017298 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.40454378901615895, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23177764488631825}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23328570910599059
Fold 2 IBS: 0.22482997301632762
Fold 3 IBS: 0.21090048079749318
Fold 4 IBS: 0.2254130957827992
Fold 5 IBS: 0.21047905455719065
[I 2024-04-13 17:58:41,796] Trial 58 finished with value: 0.2209816626519603 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.4555194020493191, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.045806106324310286}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24638937856742066
Fold 2 IBS: 0.23217903444274132
Fold 3 IBS: 0.22957970746983006
Fold 4 IBS: 0.24149329059953806
Fold 5 IBS: 0.23023771602212853
[I 2024-04-13 17:59:01,810] Trial 59 finished with value: 0.23597582542033174 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.6547993209148422, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2306118363998221
Fold 2 IBS: 0.22306141635246116
Fold 3 IBS: 0.21072669348877712
Fold 4 IBS: 0.22625181384713736
Fold 5 IBS: 0.21133732898704416
[I 2024-04-13 17:59:28,410] Trial 60 finished with value: 0.22039781781504839 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.48271442117986096, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.178446120167478}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2311701429638268
Fold 2 IBS: 0.22477774454018215
Fold 3 IBS: 0.21109067313133456
Fold 4 IBS: 0.22467051654837508
Fold 5 IBS: 0.2120682587473275
[I 2024-04-13 17:59:50,936] Trial 61 finished with value: 0.22075546718620923 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.5026627705946465, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14529793469682825}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.2461928599463436
Fold 2 IBS: 0.23221691568783104
Fold 3 IBS: 0.22947567562670096
Fold 4 IBS: 0.24151671023331148

Fold 5 IBS: 0.23018854152461504
[I 2024-04-13 18:00:13,196] Trial 62 finished with value: 0.23591814060376043 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.4677262455345284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2827349986373208}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.24652405780792855
Fold 2 IBS: 0.2322152403880562
Fold 3 IBS: 0.22946718005561817
Fold 4 IBS: 0.2414651127800749
Fold 5 IBS: 0.23031058287471998
[I 2024-04-13 18:00:46,151] Trial 63 finished with value: 0.23599643478127957 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.36524236153301975, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19147391488941964}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23373423023692633
Fold 2 IBS: 0.22521393950806748
Fold 3 IBS: 0.2191306507991317
Fold 4 IBS: 0.23014767984329243
Fold 5 IBS: 0.22006146132051893
[I 2024-04-13 18:01:05,294] Trial 64 finished with value: 0.2256575923415874 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.341317344596171, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024163948190701435}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23110813901378655
Fold 2 IBS: 0.22625593796332996
Fold 3 IBS: 0.21344254276833136
Fold 4 IBS: 0.22403890746089866
Fold 5 IBS: 0.21112293233311893
[I 2024-04-13 18:01:34,972] Trial 65 finished with value: 0.2211936919078931 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 484, 'oob_score': True, 'max_samples': 0.4293920185141239, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10772017538104399}. Best is trial 26 with value: 0.22015707552217512.
Fold 1 IBS: 0.23510485461556999
Fold 2 IBS: 0.2248386961406159
Fold 3 IBS: 0.20438305318368702
Fold 4 IBS: 0.22161474102841908
Fold 5 IBS: 0.20865703395071367
[I 2024-04-13 18:01:54,244] Trial 66 finished with value: 0.2189196757838011 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7277222032902713, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00012424788420031775}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23501226850054138
Fold 2 IBS: 0.22471431254299942
Fold 3 IBS: 0.20593000096178582
Fold 4 IBS: 0.22343494979422188
Fold 5 IBS: 0.20949072806237073
[I 2024-04-13 18:02:10,742] Trial 67 finished with value: 0.21971645197238385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.7290936220221548, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07569575991727365}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23233804701309263
Fold 2 IBS: 0.22733944531132327
Fold 3 IBS: 0.2130366337153433
Fold 4 IBS: 0.22697606576675997
Fold 5 IBS: 0.21055795261271074
[I 2024-04-13 18:02:27,904] Trial 68 finished with value: 0.222049628883846 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 465, 'oob_score': False, 'max_samples': 0.738982857579614, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17948323116159026}. Best is trial 66 with value: 0.2189196757838011.
Fold 1 IBS: 0.23738739866957145
Fold 2 IBS: 0.22468686012438713
Fold 3 IBS: 0.20171388324594125
Fold 4 IBS: 0.22142509500072
Fold 5 IBS: 0.20594012888505892
[I 2024-04-13 18:02:45,092] Trial 69 finished with value: 0.21823067318513573 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.7966473717734156, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.000754910732434978}. Best is trial 69 with value: 0.21823067318513573.
Fold 1 IBS: 0.23640466205485558
Fold 2 IBS: 0.22511627601864978
Fold 3 IBS: 0.20496467553113637
Fold 4 IBS: 0.22127678503888615
Fold 5 IBS: 0.20729334433212973
[I 2024-04-13 18:02:59,986] Trial 70 finished with value: 0.21901114859513152 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.7903378056871502, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0691368647018997}. Best is trial 69 with value: 0.21823067318513573.
Fold 1 IBS: 0.23750818984851968
Fold 2 IBS: 0.22426265927695213
Fold 3 IBS: 0.2016674228960865
Fold 4 IBS: 0.2211677375711476
Fold 5 IBS: 0.20609431335638406
[I 2024-04-13 18:03:14,006] Trial 71 finished with value: 0.21814006458981802 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.785271119394671, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.074256882937306e-05}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23838492585055007
Fold 2 IBS: 0.22507214558163305
Fold 3 IBS: 0.20143767144413025
Fold 4 IBS: 0.22268918756548908
Fold 5 IBS: 0.2068563072044347
[I 2024-04-13 18:03:27,029] Trial 72 finished with value: 0.2188880475292474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8036876381737409, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0015918352811246476}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23843558191669362
Fold 2 IBS: 0.22493582433312012
Fold 3 IBS: 0.20129183641750387
Fold 4 IBS: 0.22279078455344045
Fold 5 IBS: 0.20681700555549176
[I 2024-04-13 18:03:40,577] Trial 73 finished with value: 0.21885420655524995 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.7999498893948669, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005099629334644618}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23664162395062918
Fold 2 IBS: 0.2241356454982757
Fold 3 IBS: 0.20519783897054078
Fold 4 IBS: 0.22110736731436786
Fold 5 IBS: 0.2073382645860624
[I 2024-04-13 18:03:52,650] Trial 74 finished with value: 0.21888414806397516 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.8194617003412593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0712695999375732}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23537805440745527
Fold 2 IBS: 0.22434344368362777
Fold 3 IBS: 0.20738548248880273
Fold 4 IBS: 0.22180433731709842
Fold 5 IBS: 0.20889031390025767
[I 2024-04-13 18:04:06,619] Trial 75 finished with value: 0.21956032635944833 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.8133524942001209, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08127549167715468}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23545525573147905
Fold 2 IBS: 0.22153659942623385
Fold 3 IBS: 0.2075449303933778
Fold 4 IBS: 0.2231528926555171
Fold 5 IBS: 0.2079749514693718
[I 2024-04-13 18:04:18,554] Trial 76 finished with value: 0.2191329259351959 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.8231686578176318, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05240500541214905}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23575461528483777
Fold 2 IBS: 0.22187847432867439
Fold 3 IBS: 0.20868891108618615
Fold 4 IBS: 0.22380403297644932
Fold 5 IBS: 0.2079961384411151
[I 2024-04-13 18:04:30,950] Trial 77 finished with value: 0.21962443442345253 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.8554946968969933, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.052809045001292264}. Best is trial 71 with value: 0.21814006458981802.

Fold 1 IBS: 0.24217247193439537
Fold 2 IBS: 0.2278793635566358
Fold 3 IBS: 0.20080078124083145
Fold 4 IBS: 0.22310960096298033
Fold 5 IBS: 0.2079672399605948
[I 2024-04-13 18:04:51,792] Trial 78 finished with value: 0.22038589153108754 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.7742508336660989, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.033857990321958055}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2355555064593619
Fold 2 IBS: 0.22224942419207222
Fold 3 IBS: 0.20877935998830383
Fold 4 IBS: 0.22444536984656233
Fold 5 IBS: 0.2081228365598182
[I 2024-04-13 18:05:05,919] Trial 79 finished with value: 0.21983049940922367 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.8561349620215079, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005195865801855532}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24241429583579838
Fold 2 IBS: 0.22789447806360993
Fold 3 IBS: 0.20467685675034264
Fold 4 IBS: 0.22288907337161928
Fold 5 IBS: 0.20750330171816853
[I 2024-04-13 18:05:18,684] Trial 80 finished with value: 0.22107560114790772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.7908246314613915, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04549184809342783}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23643091434190627
Fold 2 IBS: 0.2245035140221752
Fold 3 IBS: 0.2054229767526827
Fold 4 IBS: 0.22079340395882704
Fold 5 IBS: 0.20720357309992168
[I 2024-04-13 18:05:39,187] Trial 81 finished with value: 0.2188708764351026 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.82389908631297, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06682100879850736}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23784943286734053
Fold 2 IBS: 0.22299626441699782
Fold 3 IBS: 0.2051875205309834
Fold 4 IBS: 0.2219151954315832
Fold 5 IBS: 0.20639160499029274
[I 2024-04-13 18:05:53,873] Trial 82 finished with value: 0.21886800364743958 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.907696191161797, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0649269059958972}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23481648213378556
Fold 2 IBS: 0.22399470395223586
Fold 3 IBS: 0.20839589700096056
Fold 4 IBS: 0.2246777750739523
Fold 5 IBS: 0.21000594947142526
[I 2024-04-13 18:06:12,036] Trial 83 finished with value: 0.22037816152647194 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9163341718713127, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12259108267136748}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2334939533679607
Fold 2 IBS: 0.22607705247059665
Fold 3 IBS: 0.20757402674496309
Fold 4 IBS: 0.22531097361703065
Fold 5 IBS: 0.2109776338102316
[I 2024-04-13 18:06:25,440] Trial 84 finished with value: 0.22068672800215655 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.6964735539602778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0983502057538686}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24168961801227365
Fold 2 IBS: 0.22720531732946742
Fold 3 IBS: 0.2073627488337626
Fold 4 IBS: 0.22321443955217113
Fold 5 IBS: 0.20933627466281343
[I 2024-04-13 18:06:39,801] Trial 85 finished with value: 0.22176167967809762 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.8852611846969818, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06716376200543844}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2501102112818779
Fold 2 IBS: 0.23109915986172933
Fold 3 IBS: 0.2015627722369633
Fold 4 IBS: 0.22179451257247865
Fold 5 IBS: 0.21066046744033398
[I 2024-04-13 18:06:53,351] Trial 86 finished with value: 0.2230454246786766 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.9556515545432857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032457057200294154}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23570787321457648
Fold 2 IBS: 0.22130640184705208
Fold 3 IBS: 0.2058533403920595
Fold 4 IBS: 0.2271720358186151
Fold 5 IBS: 0.20822086095930034
[I 2024-04-13 18:07:08,458] Trial 87 finished with value: 0.21965210244632072 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 486, 'oob_score': False, 'max_samples': 0.8392358634429405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012615689337359539}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23506041233177796
Fold 2 IBS: 0.22676854768655463
Fold 3 IBS: 0.21426008705017613
Fold 4 IBS: 0.22869053791418748
Fold 5 IBS: 0.21289985376952034
[I 2024-04-13 18:07:22,595] Trial 88 finished with value: 0.22353588775044334 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8803049631865397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14660532598550163}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23714953265947813
Fold 2 IBS: 0.22436316613074966
Fold 3 IBS: 0.2020631925894465
Fold 4 IBS: 0.22124274581523004
Fold 5 IBS: 0.20620465624668038
[I 2024-04-13 18:07:37,549] Trial 89 finished with value: 0.21820465868831693 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 456, 'oob_score': False, 'max_samples': 0.7896846867879517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03627962366130027}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23580014606596647
Fold 2 IBS: 0.2218875639554552
Fold 3 IBS: 0.20867976067748017
Fold 4 IBS: 0.22627294211995028
Fold 5 IBS: 0.20840927695622002
[I 2024-04-13 18:07:55,456] Trial 90 finished with value: 0.22020993795501442 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.93720899494118, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03869745358932866}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2354589984552326
Fold 2 IBS: 0.22524001219031592
Fold 3 IBS: 0.20569095963108802
Fold 4 IBS: 0.22140761560731112
Fold 5 IBS: 0.20777808554956137
[I 2024-04-13 18:08:12,540] Trial 91 finished with value: 0.2191151342867018 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 452, 'oob_score': False, 'max_samples': 0.7965806938790612, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06322946729450632}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.24160797692372046
Fold 2 IBS: 0.22877573588171754
Fold 3 IBS: 0.20349956847846673
Fold 4 IBS: 0.22172366432250362
Fold 5 IBS: 0.20728746219361785
[I 2024-04-13 18:08:27,976] Trial 92 finished with value: 0.22057888156000524 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.7550788603038648, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01093866522527464}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23805383943188022
Fold 2 IBS: 0.22443950723251976
Fold 3 IBS: 0.20085521312077026
Fold 4 IBS: 0.22152045897596737

Fold 5 IBS: 0.2069805372099246
[I 2024-04-13 18:08:45,488] Trial 93 finished with value: 0.21836991119421248 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.7876680525303928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02818336790921719}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2481959844323671
Fold 2 IBS: 0.23173657169109757
Fold 3 IBS: 0.20201510994966232
Fold 4 IBS: 0.22255626189257152
Fold 5 IBS: 0.21061654425734486
[I 2024-04-13 18:09:03,380] Trial 94 finished with value: 0.22302409444460863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.8362507108284499, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027504161893380293}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23915650996574608
Fold 2 IBS: 0.2234245394350635
Fold 3 IBS: 0.21293758807164273
Fold 4 IBS: 0.23523772004345975
Fold 5 IBS: 0.21283134069782997
[I 2024-04-13 18:09:21,051] Trial 95 finished with value: 0.2247175396427484 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.8837943797775261, 'max_features': None, 'min_weight_fraction_leaf': 0.012755690371205977}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23636458888864972
Fold 2 IBS: 0.22548005093935128
Fold 3 IBS: 0.20289781330297618
Fold 4 IBS: 0.22194388354495065
Fold 5 IBS: 0.20659782587399886
[I 2024-04-13 18:09:36,454] Trial 96 finished with value: 0.2186568325099853 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.7047963450216371, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042649479114857974}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.2368435830144382
Fold 2 IBS: 0.22787196721859507
Fold 3 IBS: 0.21053102229260984
Fold 4 IBS: 0.22497427988410976
Fold 5 IBS: 0.21388075327377432
[I 2024-04-13 18:09:52,813] Trial 97 finished with value: 0.2228203211367054 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.695234381023326, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08812518101550153}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23461443359372502
Fold 2 IBS: 0.22206420895541035
Fold 3 IBS: 0.20600949221006296
Fold 4 IBS: 0.2225105168375799
Fold 5 IBS: 0.20798613510831773
[I 2024-04-13 18:10:10,223] Trial 98 finished with value: 0.21863695734101918 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 429, 'oob_score': False, 'max_samples': 0.7518465351355723, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04566737589752622}. Best is trial 71 with value: 0.21814006458981802.
Fold 1 IBS: 0.23487790054634475
Fold 2 IBS: 0.22192356266132915
Fold 3 IBS: 0.206872333232792
Fold 4 IBS: 0.22206365342237452
Fold 5 IBS: 0.20811521327808374
[I 2024-04-13 18:10:25,035] Trial 99 finished with value: 0.21877053262818486 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 426, 'oob_score': False, 'max_samples': 0.7658401698686866, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04554148579618334}. Best is trial 71 with value: 0.21814006458981802.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.21814006458981802], datetime_start=datetime.datetime(2024, 4, 13, 18, 2, 59, 992384), datetime_complete=datetime.datetime(2024, 4, 13, 18, 3, 14, 5375), params={'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 444, 'oob_score': False, 'max_samples': 0.785271119394671, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.074256882937306e-05}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.21814006458981802

In [59]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.79
train_ibs:  0.218

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=20, max_features='auto', max_leaf_nodes=12,
                     max_samples=0.9937352645069003, min_samples_leaf=1,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.014733302673387358,
                     n_estimators=435, random_state=123, warm_start=True)

test_cindex:  0.603

RandomSurvivalForest(max_depth=13, max_features='log2', max_leaf_nodes=3,
                     max_samples=0.785271119394671, min_samples_leaf=4,
                     min_samples_split=2,
                     min_weight_fraction_leaf=8.074256882937306e-05,
                     n_estimators=444, random_state=123)

test_ibs:  0.215

In [63]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [64]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [65]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:10:31,065] A new study created in memory with name: no-name-ad38897a-9a17-4961-9c85-ce24e608d10a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 18:10:33,939] Trial 0 finished with value: 0.6851000777443397 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:10:41,899] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 18:10:56,694] Trial 2 finished with value: 0.6471738109279814 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 18:10:58,303] Trial 3 finished with value: 0.6721233889975948 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:03,677] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:09,339] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 18:11:12,790] Trial 6 finished with value: 0.6775544862150437 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.575107296137339
[I 2024-04-13 18:11:20,824] Trial 7 finished with value: 0.6410571220283957 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 18:11:21,337] Trial 8 finished with value: 0.6602715482412723 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.5901287553648069
[I 2024-04-13 18:11:37,623] Trial 9 finished with value: 0.6387388839144454 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:43,259] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 18:11:46,847] Trial 11 finished with value: 0.6702180836908557 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.6851000777443397.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 18:11:51,189] Trial 12 finished with value: 0.6881534529891422 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 18:11:55,221] Trial 13 finished with value: 0.6646828847295456 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.7
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 18:11:58,872] Trial 14 finished with value: 0.6594415746090991 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6374501992031872

Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 18:12:01,427] Trial 15 finished with value: 0.6707959967448854 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.6094420600858369
[I 2024-04-13 18:12:05,372] Trial 16 finished with value: 0.656032749497523 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5717131474103586
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6223175965665236
[I 2024-04-13 18:12:08,019] Trial 17 finished with value: 0.6664734494891689 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:12:12,523] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6502145922746781
[I 2024-04-13 18:12:15,762] Trial 19 finished with value: 0.6644257554322603 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 18:12:16,142] Trial 20 finished with value: 0.6567802711331774 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 18:12:19,890] Trial 21 finished with value: 0.6792348679372288 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 18:12:23,509] Trial 22 finished with value: 0.686029107776449 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.6881534529891422.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-13 18:12:26,914] Trial 23 finished with value: 0.6906324467750945 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 18:12:30,419] Trial 24 finished with value: 0.6711203403150813 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 18:12:33,596] Trial 25 finished with value: 0.6858499860979521 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.572961373390558
[I 2024-04-13 18:12:51,673] Trial 26 finished with value: 0.6413704991472602 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6569767441860465
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 18:12:55,688] Trial 27 finished with value: 0.675049805218149 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.7042553191489361
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6673819742489271
[I 2024-04-13 18:12:58,419] Trial 28 finished with value: 0.6584670168145277 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 18:13:00,417] Trial 29 finished with value: 0.655897752553135 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.6906324467750945.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6763565891472868
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 18:13:03,448] Trial 30 finished with value: 0.6821700950953665 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 18:13:06,756] Trial 31 finished with value: 0.6850747922995026 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6357896182918609, 'min_weight_fraction_leaf': 0.043457520259011145}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 18:13:09,957] Trial 32 finished with value: 0.6748268325865853 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.48963031975436294, 'min_weight_fraction_leaf': 0.054624644214656966}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:13:13,558] Trial 33 finished with value: 0.6546886869454311 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.527493679418052, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 18:13:17,160] Trial 34 finished with value: 0.6855672055264954 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9202590430146967, 'min_weight_fraction_leaf': 0.07949057080337707}. Best is trial 23 with value: 0.6906324467750945.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 18:13:24,725] Trial 35 finished with value: 0.6957388726363694 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.678814039070356, 'min_weight_fraction_leaf': 0.028560781966745094}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.625968992248062
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 18:13:42,591] Trial 36 finished with value: 0.6460431015306448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 487, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7202769479752608, 'min_weight_fraction_leaf': 0.1272251175690979}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6531007751937985
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 18:13:50,857] Trial 37 finished with value: 0.6535992249876296 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8198785636142412, 'min_weight_fraction_leaf': 0.029014014591284436}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 18:13:58,054] Trial 38 finished with value: 0.655251518254536 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.002361340929773935}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.6787072243346007
Fold 5 C-index: 0.6180257510729614
[I 2024-04-13 18:14:13,826] Trial 39 finished with value: 0.645723528384093 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7691351859887788, 'min_weight_fraction_leaf': 0.06720870867946066}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:14:19,483] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5982912816250927, 'min_weight_fraction_leaf': 0.4492877633512613}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 18:14:23,340] Trial 41 finished with value: 0.6880044461642689 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6598304746211209, 'min_weight_fraction_leaf': 0.053447973833735035}. Best is trial 35 with value: 0.6957388726363694.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 18:14:31,308] Trial 42 finished with value: 0.7030860499704138 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 473, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5313336913856148, 'min_weight_fraction_leaf': 0.025352461449765364}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 18:14:40,612] Trial 43 finished with value: 0.679926602167664 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5364184962117242, 'min_weight_fraction_leaf': 0.05972934366832378}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 18:14:48,500] Trial 44 finished with value: 0.6845185041435788 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.687551258169526, 'min_weight_fraction_leaf': 0.09604207143003154}. Best is trial 42 with value: 0.7030860499704138.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.723175965665236
[I 2024-04-13 18:14:52,964] Trial 45 finished with value: 0.6928271133771465 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 144, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5586473886674701, 'min_weight_fraction_leaf': 0.021758007763963413}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 18:14:56,432] Trial 46 finished with value: 0.6806840283474052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 138, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4276865318481037, 'min_weight_fraction_leaf': 0.017191498668975277}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.6863117870722434
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 18:15:00,289] Trial 47 finished with value: 0.6406747019951217 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 93, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.36005786284820956, 'min_weight_fraction_leaf': 0.022894100109012182}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7124463519313304
[I 2024-04-13 18:15:04,083] Trial 48 finished with value: 0.6975026836324872 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.94082830351897, 'min_weight_fraction_leaf': 0.0031941216647066936}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:15:08,189] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5011407247227364, 'min_weight_fraction_leaf': 0.358441712753887}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 18:15:11,532] Trial 50 finished with value: 0.6804367470765946 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 171, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9312077054760161, 'min_weight_fraction_leaf': 0.12266310822518021}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 18:15:14,565] Trial 51 finished with value: 0.6746377989463979 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 170, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.0007314361594816486}. Best is trial 42 with value: 0.7030860499704138.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.759656652360515
[I 2024-04-13 18:15:18,917] Trial 52 finished with value: 0.7033308262791091 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8076761414867076, 'min_weight_fraction_leaf': 0.02370651531262462}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 18:15:22,301] Trial 53 finished with value: 0.6854416959540812 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 195, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7882374110234983, 'min_weight_fraction_leaf': 0.07355615073523727}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 18:15:26,087] Trial 54 finished with value: 0.6912653578936234 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 236, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8462634635234857, 'min_weight_fraction_leaf': 0.027695920994629177}. Best is trial 52 with value: 0.7033308262791091.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-13 18:15:30,180] Trial 55 finished with value: 0.7304019052983591 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 237, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8431949607994742, 'min_weight_fraction_leaf': 0.019689561001487742}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 18:15:35,112] Trial 56 finished with value: 0.6852121772640821 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 288, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8359750908740874, 'min_weight_fraction_leaf': 0.09275039490290456}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7339055793991416
[I 2024-04-13 18:15:39,980] Trial 57 finished with value: 0.7080313014605807 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 278, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.912592990524893, 'min_weight_fraction_leaf': 0.0210885099116659}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 18:15:45,079] Trial 58 finished with value: 0.6555053283777668 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 292, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9091926669480035, 'min_weight_fraction_leaf': 0.2526413207446905}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5515021459227468
[I 2024-04-13 18:15:55,704] Trial 59 finished with value: 0.612482459269093 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.943040394432692, 'min_weight_fraction_leaf': 0.040329046437081434}. Best is trial 55 with value: 0.7304019052983591.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 18:16:00,384] Trial 60 finished with value: 0.6883778093095436 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.879697866755957, 'min_weight_fraction_leaf': 0.055451281420183546}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7081545064377682
[I 2024-04-13 18:16:02,899] Trial 61 finished with value: 0.6882180229986123 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 131, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.801988873777292, 'min_weight_fraction_leaf': 0.017439688996287176}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7360515021459227
[I 2024-04-13 18:16:04,579] Trial 62 finished with value: 0.7109694649252425 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8617770804754492, 'min_weight_fraction_leaf': 0.014415763584492182}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7317596566523605
[I 2024-04-13 18:16:06,021] Trial 63 finished with value: 0.7183475356629161 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 59, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002705850447878577}. Best is trial 55 with value: 0.7304019052983591.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8133047210300429
[I 2024-04-13 18:16:07,421] Trial 64 finished with value: 0.7483307845911831 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.0017689713740798967}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7510638297872341
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7060085836909872
[I 2024-04-13 18:16:08,902] Trial 65 finished with value: 0.6998208548490268 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 61, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9996385846525305, 'min_weight_fraction_leaf': 0.04725744918321939}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:16:09,567] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 9, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8621588892289783, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5796812749003984
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6716738197424893
[I 2024-04-13 18:16:10,585] Trial 67 finished with value: 0.6849489036736089 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 36, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8924168531245312, 'min_weight_fraction_leaf': 0.07024991347750792}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7382978723404255
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6952789699570815
[I 2024-04-13 18:16:12,499] Trial 68 finished with value: 0.6860272317441234 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 94, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7570760952920621, 'min_weight_fraction_leaf': 0.08592463964216505}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7661596958174905
Fold 5 C-index: 0.6759656652360515
[I 2024-04-13 18:16:14,018] Trial 69 finished with value: 0.6949112962080065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 62, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9037622964369387, 'min_weight_fraction_leaf': 0.014330365794333477}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-13 18:16:15,074] Trial 70 finished with value: 0.6910631381543316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 34, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8093114050677033, 'min_weight_fraction_leaf': 0.03979626985401667}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6724806201550387
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7017167381974249
[I 2024-04-13 18:16:16,559] Trial 71 finished with value: 0.6957600898208183 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 70, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9952461586716469, 'min_weight_fraction_leaf': 0.05244870419935619}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8154506437768241
[I 2024-04-13 18:16:18,805] Trial 72 finished with value: 0.732867519325721 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9729286202250643, 'min_weight_fraction_leaf': 0.0007501905752557436}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 18:16:21,175] Trial 73 finished with value: 0.7128904943815512 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9537142578281173, 'min_weight_fraction_leaf': 0.012418975853445025}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7467811158798283
[I 2024-04-13 18:16:23,583] Trial 74 finished with value: 0.7191746692395198 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9697396627525858, 'min_weight_fraction_leaf': 0.011122539757406865}. Best is trial 64 with value: 0.7483307845911831.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7965779467680608
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 18:16:25,736] Trial 75 finished with value: 0.7129593862942667 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9611088438541834, 'min_weight_fraction_leaf': 0.00026629033599147274}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.5643776824034334
[I 2024-04-13 18:16:30,135] Trial 76 finished with value: 0.6073724889462218 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9582643703114411, 'min_weight_fraction_leaf': 0.015367528693973603}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 18:16:32,724] Trial 77 finished with value: 0.7128288110450078 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 126, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9494217636188305, 'min_weight_fraction_leaf': 0.0016737005937686057}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-13 18:16:35,010] Trial 78 finished with value: 0.7319548991462254 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 123, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9642227434197009, 'min_weight_fraction_leaf': 0.0021058685030657335}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7553191489361702
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7381974248927039
[I 2024-04-13 18:16:37,580] Trial 79 finished with value: 0.6999093844652243 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 117, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9695872781720767, 'min_weight_fraction_leaf': 0.03777743761503083}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7103004291845494
[I 2024-04-13 18:16:40,441] Trial 80 finished with value: 0.6889680415739856 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 159, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9748962504778398, 'min_weight_fraction_leaf': 0.06439560013397327}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-13 18:16:42,958] Trial 81 finished with value: 0.7112568044975542 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 124, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9489094481266604, 'min_weight_fraction_leaf': 0.00837226306600549}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7489270386266095
[I 2024-04-13 18:16:44,889] Trial 82 finished with value: 0.7151598166699424 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 103, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8869701624411807, 'min_weight_fraction_leaf': 0.0009826312409484343}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.703862660944206
[I 2024-04-13 18:16:46,561] Trial 83 finished with value: 0.70260361739942 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 91, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9252815070211524, 'min_weight_fraction_leaf': 0.034454055596569985}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 18:16:49,217] Trial 84 finished with value: 0.664443908687675 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 108, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8873964455419806, 'min_weight_fraction_leaf': 0.0001876274131405089}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7167381974248928
[I 2024-04-13 18:16:52,706] Trial 85 finished with value: 0.6873669920373484 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 151, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9765072725804504, 'min_weight_fraction_leaf': 0.013004742095931136}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6608527131782945
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6716738197424893
[I 2024-04-13 18:16:54,221] Trial 86 finished with value: 0.6868914200866229 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 78, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8698782711480478, 'min_weight_fraction_leaf': 0.03289779563895275}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.7595744680851064
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6995708154506438
[I 2024-04-13 18:16:55,731] Trial 87 finished with value: 0.6948891539842074 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 50, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8345993194987964, 'min_weight_fraction_leaf': 0.051343068837458844}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.5910852713178295
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.5579399141630901
[I 2024-04-13 18:17:03,355] Trial 88 finished with value: 0.6097028070712147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 194, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.924420980029357, 'min_weight_fraction_leaf': 0.010350197621313917}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6337209302325582
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 18:17:04,143] Trial 89 finished with value: 0.6469835494137881 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 16, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9991858125788121, 'min_weight_fraction_leaf': 0.28976495050632306}. Best is trial 64 with value: 0.7483307845911831.

Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8175965665236051
[I 2024-04-13 18:17:07,136] Trial 90 finished with value: 0.729087779708108 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 168, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9119141145095422, 'min_weight_fraction_leaf': 0.03045835615518719}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8261802575107297
[I 2024-04-13 18:17:10,246] Trial 91 finished with value: 0.7301061688113683 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 172, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8965986548546552, 'min_weight_fraction_leaf': 0.032382398081057265}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6453488372093024
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6137339055793991
[I 2024-04-13 18:17:13,443] Trial 92 finished with value: 0.6654765723248192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 175, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.25077855422842626, 'min_weight_fraction_leaf': 0.030475090955934078}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8218884120171673
[I 2024-04-13 18:17:17,022] Trial 93 finished with value: 0.723349516226648 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9007665079653875, 'min_weight_fraction_leaf': 0.04421727446740081}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8347639484978541
[I 2024-04-13 18:17:20,094] Trial 94 finished with value: 0.721176946423143 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 178, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.904130167714226, 'min_weight_fraction_leaf': 0.047285012436125234}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.7145922746781116
[I 2024-04-13 18:17:23,344] Trial 95 finished with value: 0.6926264721782838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8559824051953817, 'min_weight_fraction_leaf': 0.10749281596606977}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8369098712446352
[I 2024-04-13 18:17:26,084] Trial 96 finished with value: 0.7234863166632615 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 157, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9080663630381983, 'min_weight_fraction_leaf': 0.04614615882777642}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7553648068669528
[I 2024-04-13 18:17:28,965] Trial 97 finished with value: 0.7052353107898245 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 158, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9058530674494015, 'min_weight_fraction_leaf': 0.07474995134491569}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.7145922746781116
[I 2024-04-13 18:17:32,439] Trial 98 finished with value: 0.6808130386420753 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 205, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9313032187014408, 'min_weight_fraction_leaf': 0.16576392984791938}. Best is trial 64 with value: 0.7483307845911831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8060836501901141

[I 2024-04-13 18:17:35,278] A new study created in memory with name: no-name-695c0486-1237-41c7-a313-9228fc4b7ac8

Fold 5 C-index: 0.8240343347639485
[I 2024-04-13 18:17:35,260] Trial 99 finished with value: 0.7281519399606781 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 144, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9026987353436134, 'min_weight_fraction_leaf': 0.044978112106174015}. Best is trial 64 with value: 0.7483307845911831.


* Best trial for C-index:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.7483307845911831], datetime_start=datetime.datetime(2024, 4, 13, 18, 16, 6, 28902), datetime_complete=datetime.datetime(2024, 4, 13, 18, 16, 7, 420386), params={'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.0017689713740798967}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=64, value=None)


* Best Score for C-index:
 0.7483307845911831

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23871639392045876
Fold 2 IBS: 0.22089740641981764
Fold 3 IBS: 0.20855935712684537
Fold 4 IBS: 0.22380699271581075
Fold 5 IBS: 0.20613806594659023
[I 2024-04-13 18:17:45,762] Trial 0 finished with value: 0.21962364322590452 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-13 18:18:00,725] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.2374084409354485
Fold 2 IBS: 0.21892351729489093
Fold 3 IBS: 0.21059085303920796
Fold 4 IBS: 0.22616820231302934
Fold 5 IBS: 0.21204655703132755
[I 2024-04-13 18:18:13,465] Trial 2 finished with value: 0.22102751412278088 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.23741407895783967
Fold 2 IBS: 0.21927599702285203
Fold 3 IBS: 0.21030069175680202
Fold 4 IBS: 0.22586626034487578
Fold 5 IBS: 0.21193073251533748
[I 2024-04-13 18:18:17,686] Trial 3 finished with value: 0.2209575521195414 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-13 18:18:29,209] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-13 18:18:39,958] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21962364322590452.
Fold 1 IBS: 0.23795541765613862
Fold 2 IBS: 0.21992985069618104
Fold 3 IBS: 0.2077002925377932
Fold 4 IBS: 0.2240482117618494
Fold 5 IBS: 0.20618770446779255
[I 2024-04-13 18:18:54,021] Trial 6 finished with value: 0.21916429542395094 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23973193218549388
Fold 2 IBS: 0.21988145192818526
Fold 3 IBS: 0.20667039410505023
Fold 4 IBS: 0.22443830719746974
Fold 5 IBS: 0.20774030799163096
[I 2024-04-13 18:19:03,312] Trial 7 finished with value: 0.21969247868156602 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2351732133658275
Fold 2 IBS: 0.22119237000388278
Fold 3 IBS: 0.21167563307535375
Fold 4 IBS: 0.22835359884410014
Fold 5 IBS: 0.21499909110450102
[I 2024-04-13 18:19:05,243] Trial 8 finished with value: 0.22227878127873302 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23678701345213632
Fold 2 IBS: 0.2224692190085653
Fold 3 IBS: 0.2128128925717937
Fold 4 IBS: 0.22932300899141547
Fold 5 IBS: 0.21680976991247256
[I 2024-04-13 18:19:23,191] Trial 9 finished with value: 0.22364038078727666 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.24645397072894554
Fold 2 IBS: 0.23215165796624326
Fold 3 IBS: 0.2300072528605466
Fold 4 IBS: 0.24106162740477477
Fold 5 IBS: 0.23037976132987092
[I 2024-04-13 18:19:36,070] Trial 10 finished with value: 0.23601085405807623 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2407112632523052
Fold 2 IBS: 0.22449406567870364
Fold 3 IBS: 0.21923219608031602
Fold 4 IBS: 0.23410601748321572
Fold 5 IBS: 0.22172302798577018
[I 2024-04-13 18:19:52,881] Trial 11 finished with value: 0.22805331409606217 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.2426583592791501
Fold 2 IBS: 0.22250934168617267
Fold 3 IBS: 0.2073988772356009
Fold 4 IBS: 0.22320546282719067
Fold 5 IBS: 0.20374832919376581
[I 2024-04-13 18:20:10,312] Trial 12 finished with value: 0.219904074044376 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 6 with value: 0.21916429542395094.
Fold 1 IBS: 0.23681056601352704
Fold 2 IBS: 0.21942788812788447
Fold 3 IBS: 0.20647992664043885
Fold 4 IBS: 0.2235208106455191
Fold 5 IBS: 0.20836329684199373
[I 2024-04-13 18:20:21,407] Trial 13 finished with value: 0.21892049765387264 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6381530978163132, 'min_weight_fraction_leaf': 0.10302250602390595}. Best is trial 13 with value: 0.21892049765387264.
Fold 1 IBS: 0.24709076537787542
Fold 2 IBS: 0.23229758763044567
Fold 3 IBS: 0.22965399450652796
Fold 4 IBS: 0.2411751364309486
Fold 5 IBS: 0.23019081700505956
[I 2024-04-13 18:20:28,930] Trial 14 finished with value: 0.23608166019017146 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 13 with value: 0.21892049765387264.

Fold 1 IBS: 0.2364263642187732
Fold 2 IBS: 0.21964078635235235
Fold 3 IBS: 0.20489859443298694
Fold 4 IBS: 0.22388210534010178
Fold 5 IBS: 0.2090644999060323
[I 2024-04-13 18:20:43,083] Trial 15 finished with value: 0.2187824700500493 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6285201358789383, 'min_weight_fraction_leaf': 0.19381386025401764}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.24660428287886507
Fold 2 IBS: 0.2321257226396559
Fold 3 IBS: 0.22935330291437783
Fold 4 IBS: 0.24160728594857112
Fold 5 IBS: 0.23025975275058844
[I 2024-04-13 18:20:48,249] Trial 16 finished with value: 0.2359900694264117 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6923965021963807, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.23684403651136585
Fold 2 IBS: 0.21959841448705122
Fold 3 IBS: 0.2056560421573172
Fold 4 IBS: 0.2233658304235327
Fold 5 IBS: 0.20846802289450317
[I 2024-04-13 18:21:00,359] Trial 17 finished with value: 0.21878646929475404 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 386, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6497544745873196, 'min_weight_fraction_leaf': 0.18481627132564235}. Best is trial 15 with value: 0.2187824700500493.
Fold 1 IBS: 0.23687920380677704
Fold 2 IBS: 0.21931414244607947
Fold 3 IBS: 0.20607205787956004
Fold 4 IBS: 0.22297392805924535
Fold 5 IBS: 0.2081887101022801
[I 2024-04-13 18:21:13,957] Trial 18 finished with value: 0.2186856084587884 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 20, 'n_estimators': 306, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8990048819755062, 'min_weight_fraction_leaf': 0.2019796911225918}. Best is trial 18 with value: 0.2186856084587884.
Fold 1 IBS: 0.23948146297755277
Fold 2 IBS: 0.22291910324934316
Fold 3 IBS: 0.21703121250088622
Fold 4 IBS: 0.23627081582775644
Fold 5 IBS: 0.2207432460911561
[I 2024-04-13 18:21:18,373] Trial 19 finished with value: 0.22728916812933891 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 111, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8794499855344343, 'min_weight_fraction_leaf': 0.4027720168515806}. Best is trial 18 with value: 0.2186856084587884.
Fold 1 IBS: 0.23688471445852777
Fold 2 IBS: 0.21913272259306837
Fold 3 IBS: 0.2059111669673491
Fold 4 IBS: 0.22283459872246641
Fold 5 IBS: 0.20816131265171223
[I 2024-04-13 18:21:29,719] Trial 20 finished with value: 0.21858490307862474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9051233789152774, 'min_weight_fraction_leaf': 0.2509729370060225}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23689478020829297
Fold 2 IBS: 0.21939083507476845
Fold 3 IBS: 0.20544637636114435
Fold 4 IBS: 0.22331937617631895
Fold 5 IBS: 0.20823609391962125
[I 2024-04-13 18:21:40,764] Trial 21 finished with value: 0.2186574923480292 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8936004056067098, 'min_weight_fraction_leaf': 0.2584106737011842}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23702655392249034
Fold 2 IBS: 0.21934691338037202
Fold 3 IBS: 0.20599414039818612
Fold 4 IBS: 0.2232183658358969
Fold 5 IBS: 0.20818608847087738
[I 2024-04-13 18:21:52,733] Trial 22 finished with value: 0.21875441240156457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 315, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9078735647156028, 'min_weight_fraction_leaf': 0.25581625155530263}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2370523143627765
Fold 2 IBS: 0.2196008201014214
Fold 3 IBS: 0.2036559885615786
Fold 4 IBS: 0.22413209063537776
Fold 5 IBS: 0.20904466830379478
[I 2024-04-13 18:22:01,461] Trial 23 finished with value: 0.21869717639298983 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 233, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8927030957052547, 'min_weight_fraction_leaf': 0.2990139029425277}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.24203440231995213
Fold 2 IBS: 0.22554360580458416
Fold 3 IBS: 0.20628337998076055
Fold 4 IBS: 0.2289849237284239
Fold 5 IBS: 0.20599130514353636
[I 2024-04-13 18:22:11,430] Trial 24 finished with value: 0.22176752339545142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 19, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8693046937847292, 'min_weight_fraction_leaf': 0.24639043366252525}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23623063868086489
Fold 2 IBS: 0.22005171287892328
Fold 3 IBS: 0.20422974897888901
Fold 4 IBS: 0.2262320541568372
Fold 5 IBS: 0.21001474317155738
[I 2024-04-13 18:22:19,565] Trial 25 finished with value: 0.21935177957341434 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 231, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.996738340265135, 'min_weight_fraction_leaf': 0.3690600107806249}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23675440837764497
Fold 2 IBS: 0.22076702165491713
Fold 3 IBS: 0.20849128508971132
Fold 4 IBS: 0.22924365118701112
Fold 5 IBS: 0.2124099236622402
[I 2024-04-13 18:22:30,539] Trial 26 finished with value: 0.22153325799430493 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7243128593918586, 'min_weight_fraction_leaf': 0.2941984778571687}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2371660771729202
Fold 2 IBS: 0.2191483603239057
Fold 3 IBS: 0.20641747737853533
Fold 4 IBS: 0.22240690608445848
Fold 5 IBS: 0.20799076460934937
[I 2024-04-13 18:22:39,719] Trial 27 finished with value: 0.21862591711383378 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 261, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8361953498806727, 'min_weight_fraction_leaf': 0.22280258441739995}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2463193986283167
Fold 2 IBS: 0.23207829291467785
Fold 3 IBS: 0.22966403015817585
Fold 4 IBS: 0.24154609978869193
Fold 5 IBS: 0.23030134578230163
[I 2024-04-13 18:22:44,113] Trial 28 finished with value: 0.2359818334544328 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 114, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8280204053136692, 'min_weight_fraction_leaf': 0.4367390598534441}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.23713924585846832
Fold 2 IBS: 0.21931758118462666
Fold 3 IBS: 0.20367479460476934
Fold 4 IBS: 0.22408618002403552
Fold 5 IBS: 0.20895070313530809
[I 2024-04-13 18:22:53,396] Trial 29 finished with value: 0.21863370096144158 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 260, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7271476705971293, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 20 with value: 0.21858490307862474.

Fold 1 IBS: 0.23738806550248728
Fold 2 IBS: 0.21993578889192347
Fold 3 IBS: 0.21089498091706652
Fold 4 IBS: 0.2272048730326933
Fold 5 IBS: 0.2132773803587104
[I 2024-04-13 18:23:00,560] Trial 30 finished with value: 0.2217402177405762 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 206, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7311100810851326, 'min_weight_fraction_leaf': 0.16969817682654836}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2371472983744441
Fold 2 IBS: 0.2192317816045922
Fold 3 IBS: 0.2066273024000569
Fold 4 IBS: 0.2223268600858535
Fold 5 IBS: 0.20805506169911736
[I 2024-04-13 18:23:12,145] Trial 31 finished with value: 0.21867766083281284 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3, 'n_estimators': 259, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8479425058967354, 'min_weight_fraction_leaf': 0.22878903104829593}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.24223910593371958
Fold 2 IBS: 0.2264118903341529
Fold 3 IBS: 0.20731329208194677
Fold 4 IBS: 0.2287610862946042
Fold 5 IBS: 0.20611174516637162
[I 2024-04-13 18:23:25,559] Trial 32 finished with value: 0.22216742396215902 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9446205451617458, 'min_weight_fraction_leaf': 0.2661809737444116}. Best is trial 20 with value: 0.21858490307862474.
Fold 1 IBS: 0.2370219997072243
Fold 2 IBS: 0.2193941053757161
Fold 3 IBS: 0.20373501168298777
Fold 4 IBS: 0.22393480585520856
Fold 5 IBS: 0.208682475587371
[I 2024-04-13 18:23:36,543] Trial 33 finished with value: 0.21855367964170153 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7377604544275241, 'min_weight_fraction_leaf': 0.22731537286697645}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23710344518730503
Fold 2 IBS: 0.2193601565250112
Fold 3 IBS: 0.20377799030194124
Fold 4 IBS: 0.2240022784938735
Fold 5 IBS: 0.20864844068886612
[I 2024-04-13 18:23:46,447] Trial 34 finished with value: 0.21857846223939942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 271, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7374664327129382, 'min_weight_fraction_leaf': 0.23191073374208002}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23764750710635235
Fold 2 IBS: 0.22052485431514102
Fold 3 IBS: 0.2086989128573178
Fold 4 IBS: 0.22954355044719715
Fold 5 IBS: 0.21248255472686303
[I 2024-04-13 18:23:54,379] Trial 35 finished with value: 0.22177947589057428 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 212, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8058295418292518, 'min_weight_fraction_leaf': 0.3249726897940118}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23783380527100748
Fold 2 IBS: 0.2211380677742572
Fold 3 IBS: 0.21185207127663558
Fold 4 IBS: 0.22796138018690684
Fold 5 IBS: 0.2144294358021491
[I 2024-04-13 18:24:07,778] Trial 36 finished with value: 0.22264295206219123 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5117163187171705, 'min_weight_fraction_leaf': 0.1607072150760065}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23677886144704816
Fold 2 IBS: 0.21955413132469867
Fold 3 IBS: 0.2059952807810265
Fold 4 IBS: 0.22795770153840889
Fold 5 IBS: 0.21078869878851952
[I 2024-04-13 18:24:22,604] Trial 37 finished with value: 0.22021493477594034 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 166, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5977432205420752, 'min_weight_fraction_leaf': 0.2121573650483426}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.24300840277727823
Fold 2 IBS: 0.22638067512276036
Fold 3 IBS: 0.20873415213457244
Fold 4 IBS: 0.22741267505514887
Fold 5 IBS: 0.20459574979480916
[I 2024-04-13 18:24:37,403] Trial 38 finished with value: 0.2220263309769138 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6852629549788185, 'min_weight_fraction_leaf': 0.11814667951535995}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23763664595441686
Fold 2 IBS: 0.21963674238171244
Fold 3 IBS: 0.20765975936600614
Fold 4 IBS: 0.22271331629056146
Fold 5 IBS: 0.20771351346868874
[I 2024-04-13 18:24:44,708] Trial 39 finished with value: 0.21907199549227713 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9480058935053208, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23944651370037162
Fold 2 IBS: 0.22439860558737096
Fold 3 IBS: 0.21824376490286634
Fold 4 IBS: 0.2342014368701815
Fold 5 IBS: 0.22112013449236526
[I 2024-04-13 18:24:56,079] Trial 40 finished with value: 0.22748209111063114 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7703151429728522, 'min_weight_fraction_leaf': 0.3250233317588423}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23712006600581267
Fold 2 IBS: 0.21925666827113804
Fold 3 IBS: 0.20438121866317888
Fold 4 IBS: 0.22426221223278658
Fold 5 IBS: 0.2089755505545177
[I 2024-04-13 18:25:06,961] Trial 41 finished with value: 0.21879914314548676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7128779131299335, 'min_weight_fraction_leaf': 0.22502514085583183}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23636287267696218
Fold 2 IBS: 0.21965157568819133
Fold 3 IBS: 0.20429145447374908
Fold 4 IBS: 0.2262599855613196
Fold 5 IBS: 0.21087596893375274
[I 2024-04-13 18:25:19,815] Trial 42 finished with value: 0.21948837146679495 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 276, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7533545355944256, 'min_weight_fraction_leaf': 0.27846129528158403}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.2366430134802846
Fold 2 IBS: 0.2194294067711963
Fold 3 IBS: 0.20575727644969144
Fold 4 IBS: 0.22313820960120131
Fold 5 IBS: 0.20834548638251957
[I 2024-04-13 18:25:34,571] Trial 43 finished with value: 0.21866267853697866 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 338, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8281942894155514, 'min_weight_fraction_leaf': 0.2362690293240371}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.2372930246571929
Fold 2 IBS: 0.22118755709584256
Fold 3 IBS: 0.21148108493389597
Fold 4 IBS: 0.22832759817438522
Fold 5 IBS: 0.21477380864590534
[I 2024-04-13 18:25:45,364] Trial 44 finished with value: 0.2226126147014444 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 244, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7654866467245561, 'min_weight_fraction_leaf': 0.1765984915124157}. Best is trial 33 with value: 0.21855367964170153.

Fold 1 IBS: 0.24647150063770518
Fold 2 IBS: 0.2324005238674857
Fold 3 IBS: 0.2295165680261027
Fold 4 IBS: 0.2413350176086155
Fold 5 IBS: 0.23048981014618952
[I 2024-04-13 18:25:55,751] Trial 45 finished with value: 0.2360426840572197 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.42889080150309455, 'min_weight_fraction_leaf': 0.30395190085793466}. Best is trial 33 with value: 0.21855367964170153.
Fold 1 IBS: 0.23684554782082465
Fold 2 IBS: 0.21919333404974234
Fold 3 IBS: 0.2053013505980981
Fold 4 IBS: 0.22292477589597334
Fold 5 IBS: 0.20836678612341789
[I 2024-04-13 18:26:08,878] Trial 46 finished with value: 0.21852635889761127 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8006072320599792, 'min_weight_fraction_leaf': 0.13827431215955044}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2399589768301317
Fold 2 IBS: 0.21880138930071588
Fold 3 IBS: 0.20629667242484592
Fold 4 IBS: 0.22636534251393303
Fold 5 IBS: 0.20974876234700723
[I 2024-04-13 18:26:10,636] Trial 47 finished with value: 0.22023422868332676 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 5, 'n_estimators': 31, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9475835682044488, 'min_weight_fraction_leaf': 0.14470027059329618}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23734004410610962
Fold 2 IBS: 0.22033178260287098
Fold 3 IBS: 0.21077176125721195
Fold 4 IBS: 0.22656543896147213
Fold 5 IBS: 0.21330307068589224
[I 2024-04-13 18:26:24,178] Trial 48 finished with value: 0.2216624195227114 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7986195780539649, 'min_weight_fraction_leaf': 0.04617548779812293}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23625124939716474
Fold 2 IBS: 0.21928917010690835
Fold 3 IBS: 0.2063591757019585
Fold 4 IBS: 0.22331625230525182
Fold 5 IBS: 0.20765154418716986
[I 2024-04-13 18:26:39,775] Trial 49 finished with value: 0.21857347833969065 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 424, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6815323326726881, 'min_weight_fraction_leaf': 0.09131723435674605}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2371187672752822
Fold 2 IBS: 0.21915942871564578
Fold 3 IBS: 0.20721255481618547
Fold 4 IBS: 0.22373050792840368
Fold 5 IBS: 0.20722944561545947
[I 2024-04-13 18:27:00,279] Trial 50 finished with value: 0.21889014087019532 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5949002626903728, 'min_weight_fraction_leaf': 0.09564369461405195}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23657837413281252
Fold 2 IBS: 0.21921373961408827
Fold 3 IBS: 0.20641430152871024
Fold 4 IBS: 0.22325153046230709
Fold 5 IBS: 0.20771396879094767
[I 2024-04-13 18:27:15,184] Trial 51 finished with value: 0.21863438290577314 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 418, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6711715875812826, 'min_weight_fraction_leaf': 0.12567164193121433}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2357343048159532
Fold 2 IBS: 0.21949424689270622
Fold 3 IBS: 0.2062245962595048
Fold 4 IBS: 0.22302319513557203
Fold 5 IBS: 0.2082914380694619
[I 2024-04-13 18:27:29,843] Trial 52 finished with value: 0.21855355623463962 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 436, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8355484780724112, 'min_weight_fraction_leaf': 0.06356770563405467}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23588775448783578
Fold 2 IBS: 0.21960499379966134
Fold 3 IBS: 0.20560863855751482
Fold 4 IBS: 0.22328194893439646
Fold 5 IBS: 0.20844111520648279
[I 2024-04-13 18:27:46,564] Trial 53 finished with value: 0.21856489019717823 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7933316926807014, 'min_weight_fraction_leaf': 0.0745088611285212}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2459142809877375
Fold 2 IBS: 0.23209907466514498
Fold 3 IBS: 0.23006719908315112
Fold 4 IBS: 0.2412636990636345
Fold 5 IBS: 0.22997918328901845
[I 2024-04-13 18:28:03,008] Trial 54 finished with value: 0.23586468741773733 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 471, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.1465843595834484, 'min_weight_fraction_leaf': 0.0717996537719882}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23562563262770414
Fold 2 IBS: 0.22039354813161444
Fold 3 IBS: 0.20584972692935538
Fold 4 IBS: 0.22772502361054814
Fold 5 IBS: 0.21102864376883282
[I 2024-04-13 18:28:18,538] Trial 55 finished with value: 0.220124515013611 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 447, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6195893286059789, 'min_weight_fraction_leaf': 0.020919354828291575}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23563295735954615
Fold 2 IBS: 0.21981277016407383
Fold 3 IBS: 0.204989658791369
Fold 4 IBS: 0.22532191283924616
Fold 5 IBS: 0.20939381856897557
[I 2024-04-13 18:28:35,063] Trial 56 finished with value: 0.21903022354464213 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 446, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6675798400299233, 'min_weight_fraction_leaf': 0.05410607583171402}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.235618718908947
Fold 2 IBS: 0.21973289084248274
Fold 3 IBS: 0.20557239685044001
Fold 4 IBS: 0.2237231663542185
Fold 5 IBS: 0.20836154108703234
[I 2024-04-13 18:28:48,249] Trial 57 finished with value: 0.21860174280862413 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 415, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5287318340211359, 'min_weight_fraction_leaf': 0.07961343183750659}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.236519319875315
Fold 2 IBS: 0.21950443141544193
Fold 3 IBS: 0.2063407204825024
Fold 4 IBS: 0.22283999560765866
Fold 5 IBS: 0.2081772921338352
[I 2024-04-13 18:29:02,414] Trial 58 finished with value: 0.21867635190295065 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 378, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.803287559716288, 'min_weight_fraction_leaf': 0.027007649016910218}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2354748473353207
Fold 2 IBS: 0.21970210525532657
Fold 3 IBS: 0.20440838433289102
Fold 4 IBS: 0.22472430202794327
Fold 5 IBS: 0.20891913786948146
[I 2024-04-13 18:29:20,143] Trial 59 finished with value: 0.2186457553641926 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 489, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7473762466460354, 'min_weight_fraction_leaf': 0.1132881773249865}. Best is trial 46 with value: 0.21852635889761127.

Fold 1 IBS: 0.2427874690307322
Fold 2 IBS: 0.22051307489638503
Fold 3 IBS: 0.21103171261194614
Fold 4 IBS: 0.22387533549578809
Fold 5 IBS: 0.2083271491005745
[I 2024-04-13 18:29:22,448] Trial 60 finished with value: 0.22130694822708522 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 74, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7017596527420207, 'min_weight_fraction_leaf': 0.09966382421080089}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23644800149579903
Fold 2 IBS: 0.2195369287078321
Fold 3 IBS: 0.20653996690015303
Fold 4 IBS: 0.22236489358251474
Fold 5 IBS: 0.20806793260763023
[I 2024-04-13 18:29:35,128] Trial 61 finished with value: 0.21859154465878583 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 357, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8453989714566266, 'min_weight_fraction_leaf': 0.0854881672929427}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23643029999972073
Fold 2 IBS: 0.21967560573705663
Fold 3 IBS: 0.20695855958876064
Fold 4 IBS: 0.22295379459110656
Fold 5 IBS: 0.20740851343462946
[I 2024-04-13 18:29:49,646] Trial 62 finished with value: 0.2186853546702548 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7864119714099438, 'min_weight_fraction_leaf': 0.03355471126999637}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23662020640249384
Fold 2 IBS: 0.22044682985730565
Fold 3 IBS: 0.2110430430738999
Fold 4 IBS: 0.22659401764816547
Fold 5 IBS: 0.21345170889609122
[I 2024-04-13 18:30:06,643] Trial 63 finished with value: 0.22163116117559117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 452, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9253967049917359, 'min_weight_fraction_leaf': 0.13189925217057735}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23588117694688576
Fold 2 IBS: 0.21950400748600946
Fold 3 IBS: 0.20743744610362147
Fold 4 IBS: 0.2227219004724267
Fold 5 IBS: 0.20797214307427977
[I 2024-04-13 18:30:26,083] Trial 64 finished with value: 0.21870333481664464 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8760174816172069, 'min_weight_fraction_leaf': 0.19634298369623576}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.24293657429451518
Fold 2 IBS: 0.22609344656173974
Fold 3 IBS: 0.20815359502812622
Fold 4 IBS: 0.22908562033306976
Fold 5 IBS: 0.20580516572696153
[I 2024-04-13 18:30:43,396] Trial 65 finished with value: 0.2224148803888825 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.06484834781781368}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.246326123904824
Fold 2 IBS: 0.2321429620809124
Fold 3 IBS: 0.2296037213979481
Fold 4 IBS: 0.24153389713884624
Fold 5 IBS: 0.2302471952197853
[I 2024-04-13 18:31:01,463] Trial 66 finished with value: 0.23597077994846322 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 462, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7546667172212993, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23707512834232153
Fold 2 IBS: 0.21930013195726877
Fold 3 IBS: 0.20789588893960737
Fold 4 IBS: 0.22277962404199228
Fold 5 IBS: 0.20734369610194425
[I 2024-04-13 18:31:19,767] Trial 67 finished with value: 0.21887889387662685 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 430, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8170420213592718, 'min_weight_fraction_leaf': 0.1494978367406185}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2462463594686935
Fold 2 IBS: 0.23217393417283155
Fold 3 IBS: 0.229993630453562
Fold 4 IBS: 0.24115987912128561
Fold 5 IBS: 0.23020109107235417
[I 2024-04-13 18:31:33,366] Trial 68 finished with value: 0.23595497885774538 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.10857553018551594}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2368310555074388
Fold 2 IBS: 0.21920878877902486
Fold 3 IBS: 0.20679480272253697
Fold 4 IBS: 0.22280458336806014
Fold 5 IBS: 0.2080990839318608
[I 2024-04-13 18:31:46,734] Trial 69 finished with value: 0.21874766286178432 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9150371780503119, 'min_weight_fraction_leaf': 0.15865717014764769}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23586697340396454
Fold 2 IBS: 0.22032829223579578
Fold 3 IBS: 0.20643967315282094
Fold 4 IBS: 0.22766226779737594
Fold 5 IBS: 0.21151359247240697
[I 2024-04-13 18:31:56,466] Trial 70 finished with value: 0.22036215981247284 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6977835794345164, 'min_weight_fraction_leaf': 0.269542416852923}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.2364558746726569
Fold 2 IBS: 0.2194623320684367
Fold 3 IBS: 0.20706917788988619
Fold 4 IBS: 0.22248122115912292
Fold 5 IBS: 0.20803169557605336
[I 2024-04-13 18:32:09,628] Trial 71 finished with value: 0.21870006027323124 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8654671343704606, 'min_weight_fraction_leaf': 0.07738198203736042}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23647397626404196
Fold 2 IBS: 0.2193778137976921
Fold 3 IBS: 0.2067575067362915
Fold 4 IBS: 0.22269242363774733
Fold 5 IBS: 0.20796186727425015
[I 2024-04-13 18:32:21,329] Trial 72 finished with value: 0.2186527175420046 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 350, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8467228912812281, 'min_weight_fraction_leaf': 0.09173299321647771}. Best is trial 46 with value: 0.21852635889761127.
Fold 1 IBS: 0.23670700550925744
Fold 2 IBS: 0.2192987886199061
Fold 3 IBS: 0.20442982953084754
Fold 4 IBS: 0.223141013709078
Fold 5 IBS: 0.2083234731520686
[I 2024-04-13 18:32:33,851] Trial 73 finished with value: 0.21838002210423152 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7842377375661996, 'min_weight_fraction_leaf': 0.04843949872109438}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23699285632626652
Fold 2 IBS: 0.2193550533373929
Fold 3 IBS: 0.20452511359216702
Fold 4 IBS: 0.2231256237020124
Fold 5 IBS: 0.2084643072267637
[I 2024-04-13 18:32:46,843] Trial 74 finished with value: 0.2184925908369205 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7811091062956046, 'min_weight_fraction_leaf': 0.04068939245007144}. Best is trial 73 with value: 0.21838002210423152.

Fold 1 IBS: 0.23757083460058645
Fold 2 IBS: 0.21936835681341144
Fold 3 IBS: 0.2050586023900099
Fold 4 IBS: 0.2231460133461373
Fold 5 IBS: 0.20844072705559955
[I 2024-04-13 18:32:56,062] Trial 75 finished with value: 0.21871690684114892 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 220, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7803578114864529, 'min_weight_fraction_leaf': 0.017478919548903803}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23640141704565878
Fold 2 IBS: 0.2197885256064894
Fold 3 IBS: 0.20318516882698215
Fold 4 IBS: 0.22544681939994865
Fold 5 IBS: 0.20897452087659646
[I 2024-04-13 18:33:08,302] Trial 76 finished with value: 0.21875929035113512 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7310311308084682, 'min_weight_fraction_leaf': 0.053169984941233435}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23741868189676912
Fold 2 IBS: 0.21959001344865917
Fold 3 IBS: 0.20405006070074652
Fold 4 IBS: 0.2243018125512366
Fold 5 IBS: 0.20899734290866995
[I 2024-04-13 18:33:18,144] Trial 77 finished with value: 0.21887158230121626 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 268, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.643528798832142, 'min_weight_fraction_leaf': 0.0035897778567450314}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2371288491562036
Fold 2 IBS: 0.21921237425444545
Fold 3 IBS: 0.20589294929880203
Fold 4 IBS: 0.22345690243536823
Fold 5 IBS: 0.20790079002157127
[I 2024-04-13 18:33:28,519] Trial 78 finished with value: 0.21871837303327815 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 242, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7399586324559952, 'min_weight_fraction_leaf': 0.036709963240196763}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23718809155484707
Fold 2 IBS: 0.22092106114932006
Fold 3 IBS: 0.21060969393168538
Fold 4 IBS: 0.22820373722606627
Fold 5 IBS: 0.21420368130993808
[I 2024-04-13 18:33:35,617] Trial 79 finished with value: 0.22222525303437135 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 194, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7825507541105653, 'min_weight_fraction_leaf': 0.06153431383484739}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23685165015175644
Fold 2 IBS: 0.22068620321605817
Fold 3 IBS: 0.21160479990748687
Fold 4 IBS: 0.2270351319118709
Fold 5 IBS: 0.21394471822408284
[I 2024-04-13 18:33:53,109] Trial 80 finished with value: 0.22202450068225105 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 498, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8206233780498613, 'min_weight_fraction_leaf': 0.01586721934758055}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23680935988687354
Fold 2 IBS: 0.21919210664973693
Fold 3 IBS: 0.2062865708031109
Fold 4 IBS: 0.22287903889466332
Fold 5 IBS: 0.20798592164828278
[I 2024-04-13 18:34:03,000] Trial 81 finished with value: 0.2186305995765335 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 286, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9683267170659943, 'min_weight_fraction_leaf': 0.24820532660386305}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.24167770220133805
Fold 2 IBS: 0.2258829783356682
Fold 3 IBS: 0.20506103877881593
Fold 4 IBS: 0.22848023645111828
Fold 5 IBS: 0.20603856384248168
[I 2024-04-13 18:34:13,628] Trial 82 finished with value: 0.22142810392188444 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8081851033669109, 'min_weight_fraction_leaf': 0.2131921119494233}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.237582647636615
Fold 2 IBS: 0.21884473486373132
Fold 3 IBS: 0.20742387029349543
Fold 4 IBS: 0.22292165310774673
Fold 5 IBS: 0.2070931524860315
[I 2024-04-13 18:34:22,382] Trial 83 finished with value: 0.21877321167752398 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8844309504688548, 'min_weight_fraction_leaf': 0.04798854332402432}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.241147785841093
Fold 2 IBS: 0.22383836423992348
Fold 3 IBS: 0.2177963735816699
Fold 4 IBS: 0.23542582564536244
Fold 5 IBS: 0.21963595295530872
[I 2024-04-13 18:34:32,909] Trial 84 finished with value: 0.2275688604526715 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 251, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6787600211894828, 'min_weight_fraction_leaf': 0.30903976828584095}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23734464582042714
Fold 2 IBS: 0.21899391617714345
Fold 3 IBS: 0.2064153028397821
Fold 4 IBS: 0.2224135340583663
Fold 5 IBS: 0.20678778466052464
[I 2024-04-13 18:34:43,973] Trial 85 finished with value: 0.21839103671124876 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7180827163665513, 'min_weight_fraction_leaf': 0.13602688437706084}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23705812324052997
Fold 2 IBS: 0.21938000194478852
Fold 3 IBS: 0.20530300805717408
Fold 4 IBS: 0.22311578502650944
Fold 5 IBS: 0.20780067210384995
[I 2024-04-13 18:34:54,325] Trial 86 finished with value: 0.21853151807457039 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 302, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7162022295222917, 'min_weight_fraction_leaf': 0.1842957273625047}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23798090366751265
Fold 2 IBS: 0.21947291839956856
Fold 3 IBS: 0.2072184272517321
Fold 4 IBS: 0.22385467669715983
Fold 5 IBS: 0.20690325084134892
[I 2024-04-13 18:35:04,268] Trial 87 finished with value: 0.2190860353714644 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 298, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7693492945351396, 'min_weight_fraction_leaf': 0.13025024094881313}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2368388275008215
Fold 2 IBS: 0.2193855222635841
Fold 3 IBS: 0.20536349150839933
Fold 4 IBS: 0.22301598241068915
Fold 5 IBS: 0.20804959246559787
[I 2024-04-13 18:35:13,003] Trial 88 finished with value: 0.2185306832298184 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7116913427696117, 'min_weight_fraction_leaf': 0.19026372034651004}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23694872131026606
Fold 2 IBS: 0.21935524065357095
Fold 3 IBS: 0.20576763462390152
Fold 4 IBS: 0.22301199290133028
Fold 5 IBS: 0.20810669911009236
[I 2024-04-13 18:35:21,324] Trial 89 finished with value: 0.21863805771983227 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7139844393284589, 'min_weight_fraction_leaf': 0.18909187879978934}. Best is trial 73 with value: 0.21838002210423152.

Fold 1 IBS: 0.237217800059635
Fold 2 IBS: 0.219560418627486
Fold 3 IBS: 0.2055584995526966
Fold 4 IBS: 0.22351950054338868
Fold 5 IBS: 0.20798078328178596
[I 2024-04-13 18:35:29,118] Trial 90 finished with value: 0.21876740041299841 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6578960771293777, 'min_weight_fraction_leaf': 0.16477439734294264}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.236951540585596
Fold 2 IBS: 0.21950546902732596
Fold 3 IBS: 0.20504430850227562
Fold 4 IBS: 0.22315671121676062
Fold 5 IBS: 0.20782359042139878
[I 2024-04-13 18:35:36,215] Trial 91 finished with value: 0.21849632395067142 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6954217194025099, 'min_weight_fraction_leaf': 0.18407738961451633}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.2366590015736694
Fold 2 IBS: 0.21937029886615486
Fold 3 IBS: 0.20566183543415947
Fold 4 IBS: 0.22301451578556367
Fold 5 IBS: 0.20767409548411542
[I 2024-04-13 18:35:44,238] Trial 92 finished with value: 0.21847594942873255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7009588430592851, 'min_weight_fraction_leaf': 0.178489497157845}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23687600031261338
Fold 2 IBS: 0.21924088383926293
Fold 3 IBS: 0.2054016930393524
Fold 4 IBS: 0.22302835737032672
Fold 5 IBS: 0.2077489452850229
[I 2024-04-13 18:35:52,238] Trial 93 finished with value: 0.2184591759693157 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7172196194520072, 'min_weight_fraction_leaf': 0.18587233706768527}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23703019354236293
Fold 2 IBS: 0.21948639464154246
Fold 3 IBS: 0.2047505157929676
Fold 4 IBS: 0.2235047542533873
Fold 5 IBS: 0.20855863469046315
[I 2024-04-13 18:36:03,424] Trial 94 finished with value: 0.2186660985841447 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6219714175446479, 'min_weight_fraction_leaf': 0.18072151749890458}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23692361705128714
Fold 2 IBS: 0.21966953779580314
Fold 3 IBS: 0.20471111021867852
Fold 4 IBS: 0.22299044301485235
Fold 5 IBS: 0.20816654210822538
[I 2024-04-13 18:36:11,766] Trial 95 finished with value: 0.21849225003776934 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7079376941574543, 'min_weight_fraction_leaf': 0.205035720310988}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23653137028059623
Fold 2 IBS: 0.2197358793548492
Fold 3 IBS: 0.20502556689280826
Fold 4 IBS: 0.22583981363051878
Fold 5 IBS: 0.20976127923417956
[I 2024-04-13 18:36:20,137] Trial 96 finished with value: 0.2193787818785904 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5801992264153996, 'min_weight_fraction_leaf': 0.2036293513522096}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23691132713166155
Fold 2 IBS: 0.21934888168734706
Fold 3 IBS: 0.2060353520597031
Fold 4 IBS: 0.2230362471179694
Fold 5 IBS: 0.20779263064091014
[I 2024-04-13 18:36:28,446] Trial 97 finished with value: 0.21862488772751826 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.705642847473056, 'min_weight_fraction_leaf': 0.17148295318003226}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.237230513240583
Fold 2 IBS: 0.2192840978709365
Fold 3 IBS: 0.20624346451793507
Fold 4 IBS: 0.2233785003281718
Fold 5 IBS: 0.20807621679976449
[I 2024-04-13 18:36:38,057] Trial 98 finished with value: 0.21884255855147816 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6399955222854865, 'min_weight_fraction_leaf': 0.1529848101895856}. Best is trial 73 with value: 0.21838002210423152.
Fold 1 IBS: 0.23707199815043145
Fold 2 IBS: 0.21927691514345446
Fold 3 IBS: 0.20538898879208908
Fold 4 IBS: 0.2230658739211438
Fold 5 IBS: 0.20786983407137138
[I 2024-04-13 18:36:46,478] Trial 99 finished with value: 0.21853472201569804 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 279, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7197685650294967, 'min_weight_fraction_leaf': 0.18553539660920623}. Best is trial 73 with value: 0.21838002210423152.


* Best trial for IBS:
 FrozenTrial(number=73, state=TrialState.COMPLETE, values=[0.21838002210423152], datetime_start=datetime.datetime(2024, 4, 13, 18, 32, 21, 334273), datetime_complete=datetime.datetime(2024, 4, 13, 18, 32, 33, 850353), params={'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7842377375661996, 'min_weight_fraction_leaf': 0.04843949872109438}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=73, value=None)


* Best Score for IBS:
 0.21838002210423152

In [66]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.748
train_ibs:  0.218

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=11, max_leaf_nodes=17,
                   max_samples=0.8662742964997368, min_samples_leaf=1,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.0017689713740798967,
                   n_estimators=54, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.585

ExtraSurvivalTrees(max_depth=2, max_features='auto', max_leaf_nodes=20,
                   max_samples=0.7842377375661996, min_samples_leaf=19,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.04843949872109438,
                   n_estimators=291, oob_score=True, random_state=123)

IBS: 0.213

In [70]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [71]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:36:48,867] A new study created in memory with name: no-name-b681894a-23c4-4b5d-acc5-5368af7afc90

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:37:43,345] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:16,602] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:38:50,177] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:39:42,069] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:01,687] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:06,036] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:40:55,828] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:09,234] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:41:11,057] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5796812749003984
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 18:43:08,581] Trial 9 finished with value: 0.6172849274886952 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.5
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 18:46:03,975] Trial 10 finished with value: 0.5915509861883201 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:49:26,006] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6172849274886952.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 18:52:12,731] Trial 12 finished with value: 0.6288581469840132 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:53:32,518] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:55:23,983] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:57:08,472] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:58:22,169] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:01:00,919] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:04:49,471] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:04:59,156] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:06:13,915] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:09:04,428] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6182170542635659
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 19:11:42,756] Trial 22 finished with value: 0.6233941406142943 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:13:47,124] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:15:49,375] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:17:06,504] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:20:11,506] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:23:04,134] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:25:29,346] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:11,852] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:29:09,422] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:32:53,657] Trial 31 finished with value: 0.5071713147410358 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:36:35,342] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:39:10,517] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:59:31,106] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:59:52,612] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:13:34,158] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:13:38,374] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 12 with value: 0.6288581469840132.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:14:37,824] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:16:04,173] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:18:20,332] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 20:18:20,810] Trial 41 finished with value: 0.6039152174760968 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6008583690987125
[I 2024-04-13 20:18:36,635] Trial 42 finished with value: 0.624004230389207 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:18:37,710] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:19:19,788] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 12 with value: 0.6288581469840132.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 20:19:33,520] Trial 45 finished with value: 0.636916827084602 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:19:37,140] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 130, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.2621149519999694, 'max_features': 0.1, 'min_impurity_decrease': 1.8213591543920705e-06, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:19:57,866] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:03,862] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.27951884808649285, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 1.4079486283020177, 'min_weight_fraction_leaf': 0.21342970007180673, 'max_features': 0.1, 'min_impurity_decrease': 2.4988708934303504e-06, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:22,335] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.5312512417393443, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3775922041148432, 'min_weight_fraction_leaf': 0.2316969754016241, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.8162506488425402, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 45 with value: 0.636916827084602.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:33,557] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.052706271754983484, 'dropout_rate': 0.3787195779305788, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.077209816707269, 'min_weight_fraction_leaf': 0.31040829786124846, 'max_features': 0.1, 'min_impurity_decrease': 1.0106089337747014e-06, 'validation_fraction': 0.8835479481377899, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 45 with value: 0.636916827084602.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6298449612403101
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 20:20:35,683] Trial 51 finished with value: 0.6419284038560863 and parameters: {'subsample': 0.9156545266266123, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1404019935798118, 'n_estimators': 32, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.377285576216956, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1936100454733836e-07, 'validation_fraction': 0.855037228249073, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:39,441] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.7977865301378425, 'learning_rate': 0.07102079283153598, 'dropout_rate': 0.11294952687164567, 'n_estimators': 48, 'criterion': 'squared_error', 'ccp_alpha': 0.5430622755642927, 'min_weight_fraction_leaf': 0.36469952190521415, 'max_features': 'sqrt', 'min_impurity_decrease': 2.38579101418113e-07, 'validation_fraction': 0.7433547121677936, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6414728682170543
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.655893536121673
Fold 5 C-index: 0.5944206008583691
[I 2024-04-13 20:20:41,075] Trial 53 finished with value: 0.6383590963856938 and parameters: {'subsample': 0.7305170806182099, 'learning_rate': 0.05877903849297955, 'dropout_rate': 0.2158120114915196, 'n_estimators': 28, 'criterion': 'squared_error', 'ccp_alpha': 0.009781579144263263, 'min_weight_fraction_leaf': 0.33111548353893067, 'max_features': 'sqrt', 'min_impurity_decrease': 5.215208696037137e-07, 'validation_fraction': 0.8384582646351804, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:43,182] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.7254872738354575, 'learning_rate': 0.059834764453264265, 'dropout_rate': 0.22627998975411026, 'n_estimators': 34, 'criterion': 'squared_error', 'ccp_alpha': 1.6707664312736628, 'min_weight_fraction_leaf': 0.3401457696750657, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.8695162647266814, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:20:48,620] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8980684211151492, 'learning_rate': 0.04709963647359185, 'dropout_rate': 0.18274261049965285, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.3370690002239194, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8331902741865593, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:16,739] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.9221605118409517, 'learning_rate': 0.04145334122676535, 'dropout_rate': 0.13064667596279733, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 1.0261239696798017, 'min_weight_fraction_leaf': 0.37038285680105903, 'max_features': 'sqrt', 'min_impurity_decrease': 6.554786161716051e-07, 'validation_fraction': 0.9052955846887007, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6914893617021277
Fold 4 C-index: 0.6254752851711026
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 20:21:23,748] Trial 57 finished with value: 0.6248260205783842 and parameters: {'subsample': 0.870116595720937, 'learning_rate': 0.05952554251828951, 'dropout_rate': 0.2654836627375681, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.4506484646379062, 'max_features': 'sqrt', 'min_impurity_decrease': 5.171295766128041e-06, 'validation_fraction': 0.7918559073771259, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:32,228] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.7860091128392402, 'learning_rate': 0.05676463368504374, 'dropout_rate': 0.24877801421911805, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.26934786002389455, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6503518520592255e-05, 'validation_fraction': 0.6918134851314997, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:34,324] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.8553450495189544, 'learning_rate': 0.07051651042781107, 'dropout_rate': 0.16583013538010005, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 8.349136570200802, 'min_weight_fraction_leaf': 0.47402646750752947, 'max_features': 'sqrt', 'min_impurity_decrease': 4.916228088258153e-06, 'validation_fraction': 0.779738812956857, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:38,292] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.8311606032672914, 'learning_rate': 0.049337793762293414, 'dropout_rate': 0.10027170450231424, 'n_estimators': 50, 'criterion': 'squared_error', 'ccp_alpha': 1.3119841524585854, 'min_weight_fraction_leaf': 0.3074767130493653, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4188603560320107e-06, 'validation_fraction': 0.8209142444316069, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:47,120] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8807242730119922, 'learning_rate': 0.06060509917723852, 'dropout_rate': 0.21540975433556148, 'n_estimators': 97, 'criterion': 'squared_error', 'ccp_alpha': 0.34104023788856364, 'min_weight_fraction_leaf': 0.4431847862340273, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.889211406935275, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.655893536121673
Fold 5 C-index: 0.6115879828326181
[I 2024-04-13 20:21:52,353] Trial 62 finished with value: 0.6283268841578284 and parameters: {'subsample': 0.9543961448103062, 'learning_rate': 0.06789146011220368, 'dropout_rate': 0.3264939129108728, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.41165895476319747, 'max_features': 'sqrt', 'min_impurity_decrease': 5.069407900080354e-07, 'validation_fraction': 0.7859949287628765, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.6027131782945736
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.6444866920152091
Fold 5 C-index: 0.5965665236051502
[I 2024-04-13 20:22:03,679] Trial 63 finished with value: 0.6235672145293628 and parameters: {'subsample': 0.9469443427613207, 'learning_rate': 0.06801311498216697, 'dropout_rate': 0.32617131802248245, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.38230472306828395, 'max_features': 'sqrt', 'min_impurity_decrease': 5.596696905911145e-07, 'validation_fraction': 0.7322540972531445, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:09,183] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9999291885743816, 'learning_rate': 0.06351690862369143, 'dropout_rate': 0.2603466948459836, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.4231489714125428, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7375428501365761e-06, 'validation_fraction': 0.7799232691405718, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:12,658] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.731372773241202, 'learning_rate': 0.08483859461035387, 'dropout_rate': 0.42946028164369743, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.3522642153414066, 'min_weight_fraction_leaf': 0.4089858346066107, 'max_features': 'sqrt', 'min_impurity_decrease': 2.3880040801001446e-07, 'validation_fraction': 0.6774643261598785, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:13,758] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9270510971818493, 'learning_rate': 0.07831921552372668, 'dropout_rate': 0.3690035704996783, 'n_estimators': 20, 'criterion': 'squared_error', 'ccp_alpha': 0.8895257611291668, 'min_weight_fraction_leaf': 0.38130779234883155, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014974488025406402, 'validation_fraction': 0.8426595838965568, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:30,536] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8509816424016059, 'learning_rate': 0.09201698812616743, 'dropout_rate': 0.2891948392773582, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.32926871585157824, 'max_features': None, 'min_impurity_decrease': 1.805737910528395e-07, 'validation_fraction': 0.7952722655013678, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:41,796] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6619865463398119, 'learning_rate': 0.07383151588968451, 'dropout_rate': 0.1853296855049907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.8385719579981664, 'min_weight_fraction_leaf': 0.47751000784675207, 'max_features': 1, 'min_impurity_decrease': 1.2986365360837672e-06, 'validation_fraction': 0.7538502794470011, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:56,736] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7692672682208916, 'learning_rate': 0.05773952075160269, 'dropout_rate': 0.2343529795568311, 'n_estimators': 135, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7491404886634039, 'min_weight_fraction_leaf': 0.20015949879955452, 'max_features': 'sqrt', 'min_impurity_decrease': 5.368270720109542e-07, 'validation_fraction': 0.9581706893807749, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 15}. Best is trial 51 with value: 0.6419284038560863.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.6444866920152091
Fold 5 C-index: 0.6266094420600858
[I 2024-04-13 20:23:04,225] Trial 70 finished with value: 0.6431464077499045 and parameters: {'subsample': 0.9672353591832252, 'learning_rate': 0.050642884595621745, 'dropout_rate': 0.13785096073945516, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 0.010067956580931684, 'min_weight_fraction_leaf': 0.3551802773828724, 'max_features': 0.1, 'min_impurity_decrease': 7.713426989240967e-06, 'validation_fraction': 0.6901517483986648, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 70 with value: 0.6431464077499045.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.6829787234042554
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.628755364806867
[I 2024-04-13 20:23:10,243] Trial 71 finished with value: 0.647978353455525 and parameters: {'subsample': 0.9736544653699906, 'learning_rate': 0.05317196534413593, 'dropout_rate': 0.14303111133639826, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 0.1, 'min_impurity_decrease': 7.356647091617949e-06, 'validation_fraction': 0.6117331205297228, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:16,710] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9701687645962381, 'learning_rate': 0.055147872123398556, 'dropout_rate': 0.14962137828220934, 'n_estimators': 80, 'criterion': 'squared_error', 'ccp_alpha': 0.30517658758579036, 'min_weight_fraction_leaf': 0.35173646760424715, 'max_features': 0.1, 'min_impurity_decrease': 7.987219995224915e-06, 'validation_fraction': 0.6095946706874, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:21,225] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9050782920628282, 'learning_rate': 0.05199322380390804, 'dropout_rate': 0.17409435305677468, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 1.253410092850479, 'min_weight_fraction_leaf': 0.39707509838374494, 'max_features': 0.1, 'min_impurity_decrease': 1.5194516956030065e-05, 'validation_fraction': 0.6804519242126394, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:23,655] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8170901637275931, 'learning_rate': 0.04465970891926194, 'dropout_rate': 0.2733411451160021, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 2.2209618984123054, 'min_weight_fraction_leaf': 0.28881136217710557, 'max_features': 0.1, 'min_impurity_decrease': 4.209901591206505e-06, 'validation_fraction': 0.565571701048534, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:30,946] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9660009158555741, 'learning_rate': 0.06623664860709609, 'dropout_rate': 0.20553427844193914, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.6610020768545956, 'min_weight_fraction_leaf': 0.4147865725732959, 'max_features': 0.1, 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.7190500576027261, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:31,516] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9260563831456721, 'learning_rate': 0.06047528137822334, 'dropout_rate': 0.13950292138275533, 'n_estimators': 3, 'criterion': 'squared_error', 'ccp_alpha': 0.30518351178979397, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 3.0635242894652526e-06, 'validation_fraction': 0.6370726022286737, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:32,770] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.6292281998520165, 'learning_rate': 0.05024404952833331, 'dropout_rate': 0.3126086948156713, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.9547062307580542, 'min_weight_fraction_leaf': 0.3510321193946014, 'max_features': 0.1, 'min_impurity_decrease': 1.081678973071488e-05, 'validation_fraction': 0.7602747720774515, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 20:23:36,185] Trial 78 finished with value: 0.6353126486594283 and parameters: {'subsample': 0.8691738049495636, 'learning_rate': 0.06172743517601075, 'dropout_rate': 0.23315454705919414, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.022575408770505685, 'min_weight_fraction_leaf': 0.3057970079002221, 'max_features': 0.1, 'min_impurity_decrease': 1.7520953196534605e-06, 'validation_fraction': 0.5037268926902503, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:38,655] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.88956690114416, 'learning_rate': 0.04130686635403637, 'dropout_rate': 0.8831816560103296, 'n_estimators': 57, 'criterion': 'squared_error', 'ccp_alpha': 0.5632856474666742, 'min_weight_fraction_leaf': 0.2996503291930464, 'max_features': 0.1, 'min_impurity_decrease': 2.4463737680399873e-06, 'validation_fraction': 0.4716515115237929, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:07,165] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.05535894045369185, 'dropout_rate': 0.684566586558272, 'n_estimators': 281, 'criterion': 'friedman_mse', 'ccp_alpha': 5.788139805041061, 'min_weight_fraction_leaf': 0.2499517824138018, 'max_features': 0.1, 'min_impurity_decrease': 1.796522128313966e-06, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6072961373390557
[I 2024-04-13 20:24:09,675] Trial 81 finished with value: 0.6307781380800804 and parameters: {'subsample': 0.8577485699653032, 'learning_rate': 0.061637170413557506, 'dropout_rate': 0.22634568349167175, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.025375439967122704, 'min_weight_fraction_leaf': 0.3176895770453635, 'max_features': 0.1, 'min_impurity_decrease': 7.578956130507077e-06, 'validation_fraction': 0.3975706744446108, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:12,958] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9813148642262436, 'learning_rate': 0.062245123119526666, 'dropout_rate': 0.22245189647227442, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.24494931030471306, 'min_weight_fraction_leaf': 0.28129167307655356, 'max_features': 0.1, 'min_impurity_decrease': 2.116701877304566e-05, 'validation_fraction': 0.40489648109304005, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:14,050] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9499142623758436, 'learning_rate': 0.06606682685789786, 'dropout_rate': 0.1294422134091702, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.20222023273899953, 'min_weight_fraction_leaf': 0.3184434511931986, 'max_features': 0.1, 'min_impurity_decrease': 8.590576083527748e-06, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:16,184] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9162531840390775, 'learning_rate': 0.06921777347051267, 'dropout_rate': 0.16964850157537764, 'n_estimators': 33, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3317427757671296, 'max_features': 'log2', 'min_impurity_decrease': 3.8673317929388064e-05, 'validation_fraction': 0.40427407950001876, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:25,983] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.073450036806534, 'dropout_rate': 0.24007045832787577, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 0.7090566148541139, 'min_weight_fraction_leaf': 0.29987641169357954, 'max_features': 0.1, 'min_impurity_decrease': 8.743573121519345e-07, 'validation_fraction': 0.37827224876251, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:24:31,428] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.8229463564083213, 'learning_rate': 0.05354154925209642, 'dropout_rate': 0.18105225920404389, 'n_estimators': 69, 'criterion': 'squared_error', 'ccp_alpha': 1.4515009042573248, 'min_weight_fraction_leaf': 0.22575436425055093, 'max_features': 0.1, 'min_impurity_decrease': 4.6532667290211476e-07, 'validation_fraction': 0.4763814174163325, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:25:25,716] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7337132044406884, 'learning_rate': 0.0483078966674454, 'dropout_rate': 0.2072955347245793, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4342246419942306, 'min_weight_fraction_leaf': 0.341665255032293, 'max_features': 0.1, 'min_impurity_decrease': 3.4533033574953447e-06, 'validation_fraction': 0.5553002617274752, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:25:51,233] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4281147617989565, 'learning_rate': 0.057668292702843474, 'dropout_rate': 0.29991250599365193, 'n_estimators': 173, 'criterion': 'squared_error', 'ccp_alpha': 1.1038407677376183, 'min_weight_fraction_leaf': 0.2720384326960418, 'max_features': 0.1, 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.43622932617902443, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5755813953488372
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6158798283261803
[I 2024-04-13 20:25:52,209] Trial 89 finished with value: 0.6178740227922591 and parameters: {'subsample': 0.8869756572783157, 'learning_rate': 0.04455455099426123, 'dropout_rate': 0.1354867390651922, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.018791586505192352, 'min_weight_fraction_leaf': 0.25406844321469574, 'max_features': None, 'min_impurity_decrease': 3.2164803778484834e-07, 'validation_fraction': 0.5865831845086661, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:26:29,477] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.781156318466977, 'learning_rate': 0.006695820304041528, 'dropout_rate': 0.3320445224709127, 'n_estimators': 239, 'criterion': 'squared_error', 'ccp_alpha': 0.837158352801002, 'min_weight_fraction_leaf': 0.37074107443236604, 'max_features': 1, 'min_impurity_decrease': 1.2352569883229447e-06, 'validation_fraction': 0.29585084927667094, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6030042918454935
[I 2024-04-13 20:26:37,022] Trial 91 finished with value: 0.6331036326328527 and parameters: {'subsample': 0.9353573941382942, 'learning_rate': 0.06264501502966024, 'dropout_rate': 0.27046977102493674, 'n_estimators': 87, 'criterion': 'squared_error', 'ccp_alpha': 0.03786111729139331, 'min_weight_fraction_leaf': 0.35574723998417634, 'max_features': 'sqrt', 'min_impurity_decrease': 5.380131049753413e-06, 'validation_fraction': 0.7054955710261992, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:26:40,258] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.9692777812882016, 'learning_rate': 0.061855558095227366, 'dropout_rate': 0.35143637013904355, 'n_estimators': 54, 'criterion': 'squared_error', 'ccp_alpha': 0.20072657092263457, 'min_weight_fraction_leaf': 0.36014647758482426, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3975982326313562e-05, 'validation_fraction': 0.6999911594682504, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:26:51,143] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9369616346923534, 'learning_rate': 0.06630023579051483, 'dropout_rate': 0.2355177689627272, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.5295497507503906, 'min_weight_fraction_leaf': 0.32195077645631737, 'max_features': 0.1, 'min_impurity_decrease': 5.784089080997864e-06, 'validation_fraction': 0.6211860587757073, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:26:53,357] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.49488295095968804, 'learning_rate': 0.07808338686371585, 'dropout_rate': 0.19914486856709368, 'n_estimators': 41, 'criterion': 'squared_error', 'ccp_alpha': 0.17721823221162922, 'min_weight_fraction_leaf': 0.3452780203306576, 'max_features': 'log2', 'min_impurity_decrease': 2.406520527524238e-06, 'validation_fraction': 0.6609732454629287, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:26:59,093] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.9088674838000037, 'learning_rate': 0.051473564556910295, 'dropout_rate': 0.15864268967517714, 'n_estimators': 73, 'criterion': 'squared_error', 'ccp_alpha': 0.5662134543657839, 'min_weight_fraction_leaf': 0.3087279762860713, 'max_features': 'sqrt', 'min_impurity_decrease': 7.802177640457686e-06, 'validation_fraction': 0.734306853058186, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:27:07,425] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.993220298193821, 'learning_rate': 0.06386578790331472, 'dropout_rate': 0.2728557965516078, 'n_estimators': 94, 'criterion': 'squared_error', 'ccp_alpha': 0.23611518017692762, 'min_weight_fraction_leaf': 0.398118898214648, 'max_features': 0.1, 'min_impurity_decrease': 6.932932254500803e-07, 'validation_fraction': 0.32386831053055254, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:27:09,132] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8439950412703551, 'learning_rate': 0.07169891244281298, 'dropout_rate': 0.25309805821661835, 'n_estimators': 32, 'criterion': 'friedman_mse', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.33178189795581936, 'max_features': 'sqrt', 'min_impurity_decrease': 3.941232420298443e-06, 'validation_fraction': 0.6710136077506228, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 71 with value: 0.647978353455525.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:27:14,898] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8752955195522896, 'learning_rate': 0.05568154932630848, 'dropout_rate': 0.21717204178559688, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.37049554846771593, 'max_features': 0.1, 'min_impurity_decrease': 2.02393880274831e-06, 'validation_fraction': 0.5229378594864895, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 19}. Best is trial 71 with value: 0.647978353455525.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 20:27:15,720] Trial 99 finished with value: 0.6104297972213892 and parameters: {'subsample': 0.9501601982199268, 'learning_rate': 0.0684597170667179, 'dropout_rate': 0.11764001599415652, 'n_estimators': 5, 'criterion': 'squared_error', 'ccp_alpha': 0.004454392542064083, 'min_weight_fraction_leaf': 0.2967257830934646, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0344011415681455e-06, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 14}. Best is trial 71 with value: 0.647978353455525.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.647978353455525], datetime_start=datetime.datetime(2024, 4, 13, 20, 23, 4, 236268), datetime_complete=datetime.datetime(2024, 4, 13, 20, 23, 10, 241741), params={'subsample': 0.9736544653699906, 'learning_rate': 0.05317196534413593, 'dropout_rate': 0.14303111133639826, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 0.1, 'min_impurity_decrease': 7.356647091617949e-06, 'validation_fraction': 0.6117331205297228, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 19}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=71, value=None)


* Best Score for C-index:
 0.647978353455525

[I 2024-04-13 20:27:15,770] A new study created in memory with name: no-name-59a2a650-1931-418a-9971-f680c1dce292

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:28:14,115] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:28:45,675] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:29:15,829] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:30:01,112] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:30:19,639] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:30:24,456] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:31:09,760] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:31:23,508] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:31:25,290] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24685581184618258
Fold 2 IBS: 0.23174237938551043
Fold 3 IBS: 0.22869576829949326
Fold 4 IBS: 0.24182307569018754
Fold 5 IBS: 0.22901409570517067
[I 2024-04-13 20:33:28,676] Trial 9 finished with value: 0.2356262261853089 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24711653291675975
Fold 2 IBS: 0.23202162954629
Fold 3 IBS: 0.2289556964425975
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293716647928885
[I 2024-04-13 20:36:45,723] Trial 10 finished with value: 0.23588805903156138 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:40:43,685] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24719577573761148
Fold 2 IBS: 0.23199892761841134
Fold 3 IBS: 0.2289405059322678
Fold 4 IBS: 0.2419573801021639
Fold 5 IBS: 0.22934247219234205
[I 2024-04-13 20:43:22,852] Trial 12 finished with value: 0.23588701231655934 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:44:47,118] Trial 13 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:46:27,579] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:48:08,135] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:49:11,209] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:51:35,761] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:54:48,194] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 20:54:56,160] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:56:05,781] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 20:58:39,591] Trial 21 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2356262261853089.
Fold 1 IBS: 0.24675710728069802
Fold 2 IBS: 0.23120128338106113

Fold 3 IBS: 0.22848569735194738
Fold 4 IBS: 0.24150141767716396
Fold 5 IBS: 0.22845766625525668
[I 2024-04-13 21:00:47,958] Trial 22 finished with value: 0.23528063438922545 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:02:32,076] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 21:04:15,354] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:05:16,241] Trial 25 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:07:20,841] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:09:21,246] Trial 27 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:10:56,259] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:12:01,935] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:13:19,635] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24723811107199292
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:15:38,469] Trial 31 finished with value: 0.23592604563741132 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:18:00,897] Trial 32 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:19:39,244] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:21:54,224] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:22:21,104] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:24:25,411] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:24:29,106] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:25:11,710] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:26:17,210] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:28:07,591] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.2472010209971281
Fold 2 IBS: 0.23197319933729893
Fold 3 IBS: 0.22887452934644678
Fold 4 IBS: 0.24191861956639799
Fold 5 IBS: 0.2293015642651888
[I 2024-04-13 21:28:08,065] Trial 41 finished with value: 0.23585378670249213 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23528063438922545.
Fold 1 IBS: 0.2459047520616606
Fold 2 IBS: 0.23020388607917422
Fold 3 IBS: 0.22657568837307415
Fold 4 IBS: 0.24022980115273948
Fold 5 IBS: 0.22694242307333995
[I 2024-04-13 21:28:22,139] Trial 42 finished with value: 0.2339713101479977 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:28:23,043] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:00,526] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 42 with value: 0.2339713101479977.
Fold 1 IBS: 0.24456420494605938
Fold 2 IBS: 0.2296322307721539
Fold 3 IBS: 0.22573775856516912
Fold 4 IBS: 0.23975108534236433
Fold 5 IBS: 0.22653026890442532
[I 2024-04-13 21:29:12,855] Trial 45 finished with value: 0.2332431097060344 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:16,478] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.3747732962598691, 'max_features': 0.1, 'min_impurity_decrease': 2.6164901943280044e-07, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:36,582] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.19790330487666663, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.3462595663974316, 'max_features': 0.1, 'min_impurity_decrease': 9.138461248752069e-07, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:29:42,380] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 0.443834316760607, 'min_weight_fraction_leaf': 0.26066789839492466, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:29:43,622] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5232490206634685, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 1.370081088125734, 'min_weight_fraction_leaf': 0.3097478284829108, 'max_features': 0.1, 'min_impurity_decrease': 2.368978679128857e-06, 'validation_fraction': 0.8421492954769574, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:29:46,008] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.07076395585024155, 'dropout_rate': 0.14893065487391582, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.7468603849227415, 'min_weight_fraction_leaf': 0.4771102452497172, 'max_features': 'log2', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24691186517673142
Fold 2 IBS: 0.23166083157852174
Fold 3 IBS: 0.22854484375938985
Fold 4 IBS: 0.24160811245105418
Fold 5 IBS: 0.2289571734476567
[I 2024-04-13 21:29:58,643] Trial 51 finished with value: 0.23553656528267078 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.22002902120871776, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0321764873923598e-06, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24623497694375837
Fold 2 IBS: 0.23110463228852685
Fold 3 IBS: 0.22789301004466875
Fold 4 IBS: 0.24144064404347787
Fold 5 IBS: 0.22815882228252543
[I 2024-04-13 21:30:08,226] Trial 52 finished with value: 0.23496641712059146 and parameters: {'subsample': 0.7293363088819711, 'learning_rate': 0.021613492744160495, 'dropout_rate': 0.21988140341808987, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.03659945835027755, 'min_weight_fraction_leaf': 0.21454208459463384, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968003047339178e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:30:17,836] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7286313887376499, 'learning_rate': 0.057410108721501936, 'dropout_rate': 0.285096973056326, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.4512041233232864, 'min_weight_fraction_leaf': 0.2260580293041923, 'max_features': 'sqrt', 'min_impurity_decrease': 9.58735442301899e-07, 'validation_fraction': 0.810021403108459, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:30:25,692] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6569229035185145, 'learning_rate': 0.04372807230380943, 'dropout_rate': 0.21137526606647042, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 1.035069386526868, 'min_weight_fraction_leaf': 0.15200254659099177, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9827268139860795e-07, 'validation_fraction': 0.7420090012406269, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:30:41,914] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.804828042321909, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.23926982708415356, 'n_estimators': 162, 'criterion': 'squared_error', 'ccp_alpha': 0.40074886285106287, 'min_weight_fraction_leaf': 0.2779066644542128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:04,906] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6106355356441384, 'learning_rate': 0.0175381503002972, 'dropout_rate': 0.1840399348615831, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.21267322167989086, 'max_features': 'sqrt', 'min_impurity_decrease': 4.6036201699627165e-06, 'validation_fraction': 0.6710340937437342, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:08,088] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7251306188899954, 'learning_rate': 0.031631325965124225, 'dropout_rate': 0.36858678707018233, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 0.8632300312068857, 'min_weight_fraction_leaf': 0.25226351016663784, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8530056448822852e-06, 'validation_fraction': 0.6117070368402964, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 45 with value: 0.2332431097060344.
Fold 1 IBS: 0.2443681907556647
Fold 2 IBS: 0.22957645244381633
Fold 3 IBS: 0.22623065748764107
Fold 4 IBS: 0.24012884639533771
Fold 5 IBS: 0.2254898421162855
[I 2024-04-13 21:31:19,681] Trial 58 finished with value: 0.23315879783974905 and parameters: {'subsample': 0.8372135933826973, 'learning_rate': 0.0933118263896949, 'dropout_rate': 0.2698372192490325, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03851666886580376, 'min_weight_fraction_leaf': 0.19014956845126402, 'max_features': 'sqrt', 'min_impurity_decrease': 5.557667048245938e-07, 'validation_fraction': 0.8240957175887902, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:33,462] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7770131468684633, 'learning_rate': 0.09661144110789328, 'dropout_rate': 0.13071901615025144, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.8838088337816697, 'min_weight_fraction_leaf': 0.20200402270044698, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1058318453300297e-05, 'validation_fraction': 0.7834472079756201, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:31:56,806] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8387622269560421, 'learning_rate': 0.09288013525153278, 'dropout_rate': 0.4315539960531031, 'n_estimators': 222, 'criterion': 'squared_error', 'ccp_alpha': 7.88888123252141, 'min_weight_fraction_leaf': 0.18715715168296215, 'max_features': 'sqrt', 'min_impurity_decrease': 5.658911777133895e-07, 'validation_fraction': 0.8258586719391796, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:32:01,843] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8935334956662829, 'learning_rate': 0.08303647143365385, 'dropout_rate': 0.31926072944032013, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.13431472354808824, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1489427281229002e-06, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 58 with value: 0.23315879783974905.
Fold 1 IBS: 0.24428122846636707
Fold 2 IBS: 0.22873125379430995
Fold 3 IBS: 0.22501463857482426
Fold 4 IBS: 0.23913988463506086
Fold 5 IBS: 0.22514732721679961
[I 2024-04-13 21:32:11,552] Trial 62 finished with value: 0.23246286653747233 and parameters: {'subsample': 0.8243414389621114, 'learning_rate': 0.09071124103540035, 'dropout_rate': 0.27251764057548483, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.2309588671101351, 'max_features': 'sqrt', 'min_impurity_decrease': 2.89800118435477e-07, 'validation_fraction': 0.876556500915509, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 62 with value: 0.23246286653747233.
Fold 1 IBS: 0.24427652287227705
Fold 2 IBS: 0.22837518871279563
Fold 3 IBS: 0.22481597447693613
Fold 4 IBS: 0.2386106110830185
Fold 5 IBS: 0.22511230961028517
[I 2024-04-13 21:32:21,183] Trial 63 finished with value: 0.23223812135106253 and parameters: {'subsample': 0.8336599603007587, 'learning_rate': 0.09031916747519456, 'dropout_rate': 0.2663787938573428, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 0.017289191017379774, 'min_weight_fraction_leaf': 0.1951981514595036, 'max_features': 'sqrt', 'min_impurity_decrease': 5.414928507269899e-07, 'validation_fraction': 0.8926228431876313, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:32:45,901] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8427195777663575, 'learning_rate': 0.08784542374582861, 'dropout_rate': 0.2603466948459836, 'n_estimators': 183, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.18631742994510192, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8821254066618343e-07, 'validation_fraction': 0.8718245332193061, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:32:54,348] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.09901078905928126, 'dropout_rate': 0.33807906387606884, 'n_estimators': 111, 'criterion': 'squared_error', 'ccp_alpha': 0.2833036261479952, 'min_weight_fraction_leaf': 0.15643365485923125, 'max_features': 'sqrt', 'min_impurity_decrease': 4.917940757661372e-07, 'validation_fraction': 0.7588166620798954, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:33:08,123] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9043457557527063, 'learning_rate': 0.08720647345857328, 'dropout_rate': 0.27193939046019544, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.4111498627316026, 'min_weight_fraction_leaf': 0.23517339076530247, 'max_features': 'sqrt', 'min_impurity_decrease': 6.086951842225704e-07, 'validation_fraction': 0.9127218528145804, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:33:10,017] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8250695857763196, 'learning_rate': 0.0911086342832341, 'dropout_rate': 0.3723000690397865, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 2.319190851430798, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': None, 'min_impurity_decrease': 2.261430377187218e-06, 'validation_fraction': 0.8216731421530759, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:33:48,703] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8643375099509361, 'learning_rate': 0.0792574273284101, 'dropout_rate': 0.17115105391870955, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.2964654702152873, 'min_weight_fraction_leaf': 0.2042624403156238, 'max_features': 1, 'min_impurity_decrease': 1.613957524750281e-07, 'validation_fraction': 0.8530531167865556, 'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:33:52,349] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7567410978430598, 'learning_rate': 0.049761024237604506, 'dropout_rate': 0.23019100638335152, 'n_estimators': 72, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7461388176327838, 'min_weight_fraction_leaf': 0.2677621074656332, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012116389221552239, 'validation_fraction': 0.7845892214091239, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24444133138826799
Fold 2 IBS: 0.22896095650109377
Fold 3 IBS: 0.22503353478571886
Fold 4 IBS: 0.23870623781069059
Fold 5 IBS: 0.22611346338092578
[I 2024-04-13 21:34:02,907] Trial 70 finished with value: 0.23265110477333942 and parameters: {'subsample': 0.7270958059780266, 'learning_rate': 0.09025955125786853, 'dropout_rate': 0.2983051130696582, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.010268271623930566, 'min_weight_fraction_leaf': 0.17606622950083872, 'max_features': 0.1, 'min_impurity_decrease': 2.9199125301850487e-07, 'validation_fraction': 0.9704707284830002, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24458360687718095
Fold 2 IBS: 0.2299707901134013
Fold 3 IBS: 0.2261844041470423
Fold 4 IBS: 0.23998297132336502
Fold 5 IBS: 0.22661245458746127
[I 2024-04-13 21:34:13,014] Trial 71 finished with value: 0.23346684540969015 and parameters: {'subsample': 0.7304805982333465, 'learning_rate': 0.0892848077436604, 'dropout_rate': 0.30534098323418335, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.17968197273495315, 'max_features': 0.1, 'min_impurity_decrease': 3.204485364940275e-07, 'validation_fraction': 0.9097007997790482, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24433296043098846
Fold 2 IBS: 0.22891833926886082
Fold 3 IBS: 0.2251270028353668
Fold 4 IBS: 0.23873976524316162
Fold 5 IBS: 0.22617521331304977
[I 2024-04-13 21:34:24,584] Trial 72 finished with value: 0.23265865621828546 and parameters: {'subsample': 0.7283770413521057, 'learning_rate': 0.08910556443694609, 'dropout_rate': 0.30374750627529123, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.004871280381427739, 'min_weight_fraction_leaf': 0.18085760075572085, 'max_features': 0.1, 'min_impurity_decrease': 2.066775254108449e-07, 'validation_fraction': 0.968044786321844, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:34:34,265] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6821762273698422, 'learning_rate': 0.09045775488747818, 'dropout_rate': 0.3019452359314178, 'n_estimators': 136, 'criterion': 'squared_error', 'ccp_alpha': 0.6105532472732402, 'min_weight_fraction_leaf': 0.17703318401139306, 'max_features': 0.1, 'min_impurity_decrease': 2.0200798514974308e-07, 'validation_fraction': 0.9701149300219802, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:34:46,711] Trial 74 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7101241528292079, 'learning_rate': 0.09937320265602623, 'dropout_rate': 0.3524831319725679, 'n_estimators': 148, 'criterion': 'squared_error', 'ccp_alpha': 0.9837183244747926, 'min_weight_fraction_leaf': 0.1523796655343799, 'max_features': 0.1, 'min_impurity_decrease': 1.0461061192135599e-07, 'validation_fraction': 0.9135026133191511, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 8}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:00,129] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7910155215343213, 'learning_rate': 0.08588418227292206, 'dropout_rate': 0.39919431914091363, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.4044325808748982, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 0.1, 'min_impurity_decrease': 2.4870550227046503e-07, 'validation_fraction': 0.963542393044741, 'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:20,052] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6388870613170881, 'learning_rate': 0.09471280191500378, 'dropout_rate': 0.26923993869351254, 'n_estimators': 199, 'criterion': 'squared_error', 'ccp_alpha': 0.30266244779681034, 'min_weight_fraction_leaf': 0.10381952675877999, 'max_features': 0.1, 'min_impurity_decrease': 1.4510472528097585e-06, 'validation_fraction': 0.8960664882855555, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:24,390] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7428517276581355, 'learning_rate': 0.07706989744762442, 'dropout_rate': 0.4476209058480567, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 1.5888723787914292, 'min_weight_fraction_leaf': 0.16206442611838873, 'max_features': 0.1, 'min_impurity_decrease': 3.33671674086432e-07, 'validation_fraction': 0.9402673106586569, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:35:34,532] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7715268987373948, 'learning_rate': 0.08985503754923349, 'dropout_rate': 0.5106424386694343, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.6998187558649429, 'min_weight_fraction_leaf': 0.1441624791990044, 'max_features': 0.1, 'min_impurity_decrease': 6.786191098123249e-07, 'validation_fraction': 0.867999843487921, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24716969285660575
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22894393483975858
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:35:38,475] Trial 79 finished with value: 0.23590477534833018 and parameters: {'subsample': 0.8256021281450457, 'learning_rate': 0.08314261144569621, 'dropout_rate': 0.8831816560103296, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 0.00580501385319391, 'min_weight_fraction_leaf': 0.19542362826311155, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982863294620272, 'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 7}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809254
[I 2024-04-13 21:35:45,083] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6683452738089981, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.684566586558272, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.17162624287712744, 'max_features': 0.1, 'min_impurity_decrease': 1.7025620478865608e-07, 'validation_fraction': 0.8367688563996566, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:35:52,023] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7212629717230318, 'learning_rate': 0.09648863423607545, 'dropout_rate': 0.32380628722047555, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.23038409491076217, 'min_weight_fraction_leaf': 0.2340042122326562, 'max_features': 0.1, 'min_impurity_decrease': 4.883007455581965e-07, 'validation_fraction': 0.9187926479398427, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 63 with value: 0.23223812135106253.
Fold 1 IBS: 0.24390862233245375
Fold 2 IBS: 0.22838292702570365
Fold 3 IBS: 0.22427728469643368
Fold 4 IBS: 0.23883806806788913
Fold 5 IBS: 0.22487611642069374
[I 2024-04-13 21:36:00,455] Trial 82 finished with value: 0.23205660370863482 and parameters: {'subsample': 0.7424094275541511, 'learning_rate': 0.09321912358204075, 'dropout_rate': 0.2934062535264489, 'n_estimators': 114, 'criterion': 'squared_error', 'ccp_alpha': 0.01778369806197142, 'min_weight_fraction_leaf': 0.21126686784700288, 'max_features': 'log2', 'min_impurity_decrease': 3.4224047595443053e-07, 'validation_fraction': 0.9694941758991367, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-13 21:36:05,669] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6936370685985978, 'learning_rate': 0.07973196831123328, 'dropout_rate': 0.28615445184158467, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 1.129152915921092, 'min_weight_fraction_leaf': 0.18903520337674806, 'max_features': 'log2', 'min_impurity_decrease': 2.9795925135078545e-07, 'validation_fraction': 0.9720656242622133, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:08,249] Trial 84 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7766180104167335, 'learning_rate': 0.09249006200550622, 'dropout_rate': 0.305574256636177, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.6566133054967586, 'min_weight_fraction_leaf': 0.24759719188654067, 'max_features': 'log2', 'min_impurity_decrease': 1.3396039034492153e-07, 'validation_fraction': 0.892099453138701, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:22,770] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8541716599279708, 'learning_rate': 0.08839641653849994, 'dropout_rate': 0.24521378095924606, 'n_estimators': 156, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3309010043491877, 'min_weight_fraction_leaf': 0.17837522472890427, 'max_features': 'log2', 'min_impurity_decrease': 8.040870911608097e-07, 'validation_fraction': 0.9314770718841436, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:28,129] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8087595997030689, 'learning_rate': 0.08488131639682682, 'dropout_rate': 0.3757108201252311, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 0.8619058019946999, 'min_weight_fraction_leaf': 0.034374369575269015, 'max_features': 'log2', 'min_impurity_decrease': 1.9734264215079192e-07, 'validation_fraction': 0.8644333526627775, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:35,320] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7460732631507769, 'learning_rate': 0.09440704087578497, 'dropout_rate': 0.34429888870538994, 'n_estimators': 117, 'criterion': 'squared_error', 'ccp_alpha': 0.23605873926111243, 'min_weight_fraction_leaf': 0.20611127721053588, 'max_features': 0.1, 'min_impurity_decrease': 3.605164135559099e-07, 'validation_fraction': 0.9533190908371042, 'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:36:53,058] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6413430388178152, 'learning_rate': 0.0973528090376961, 'dropout_rate': 0.26912242502602596, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 0.5807061908097002, 'min_weight_fraction_leaf': 0.16723537370276506, 'max_features': 0.1, 'min_impurity_decrease': 1.190634063232502e-06, 'validation_fraction': 0.8005899065401637, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 82 with value: 0.23205660370863482.
Fold 1 IBS: 0.24220714862378384
Fold 2 IBS: 0.22705284477038132
Fold 3 IBS: 0.22374120154251026
Fold 4 IBS: 0.23761138561741843
Fold 5 IBS: 0.22312495335199894
[I 2024-04-13 21:37:06,408] Trial 89 finished with value: 0.23074750678121858 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.08109800836387941, 'dropout_rate': 0.18122999434960108, 'n_estimators': 146, 'criterion': 'squared_error', 'ccp_alpha': 0.018794864735403906, 'min_weight_fraction_leaf': 0.14130782512257434, 'max_features': None, 'min_impurity_decrease': 6.04312953486063e-07, 'validation_fraction': 0.9728621916133924, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23074750678121858.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:37:33,743] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4301287904403204, 'learning_rate': 0.08064135841350613, 'dropout_rate': 0.18182381147209734, 'n_estimators': 216, 'criterion': 'squared_error', 'ccp_alpha': 5.797253839038365, 'min_weight_fraction_leaf': 0.11344111466651854, 'max_features': 1, 'min_impurity_decrease': 2.7530646126399795e-06, 'validation_fraction': 0.9992764821735842, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.23074750678121858.
Fold 1 IBS: 0.2409482065148207
Fold 2 IBS: 0.22548074688500788
Fold 3 IBS: 0.22218016838847504
Fold 4 IBS: 0.23628101146650415
Fold 5 IBS: 0.22161830859386844
[I 2024-04-13 21:37:48,861] Trial 91 finished with value: 0.22930168836973525 and parameters: {'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24720356529080675
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:38:03,593] Trial 92 finished with value: 0.23591913648117407 and parameters: {'subsample': 0.37023851203307184, 'learning_rate': 0.08893737188983004, 'dropout_rate': 0.20172874940955723, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.25929761360970466, 'min_weight_fraction_leaf': 0.14091910204137698, 'max_features': None, 'min_impurity_decrease': 1.670575123081423e-06, 'validation_fraction': 0.9646916032715627, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:38:16,178] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3393392217612321, 'learning_rate': 0.08484939828620154, 'dropout_rate': 0.1330785179258292, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.5271800261864423, 'min_weight_fraction_leaf': 0.22342629975429745, 'max_features': None, 'min_impurity_decrease': 6.529634824832721e-07, 'validation_fraction': 0.9250469615937894, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:38:22,623] Trial 94 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.30155497875372905, 'learning_rate': 0.09226836699183699, 'dropout_rate': 0.16486788507480765, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 4.0703783464897505, 'min_weight_fraction_leaf': 0.08717516087188838, 'max_features': None, 'min_impurity_decrease': 4.324897116213418e-07, 'validation_fraction': 0.902599975518271, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:38:31,215] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.22711241501967083, 'learning_rate': 0.09399734029654892, 'dropout_rate': 0.23424050775181726, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.2155841604325495, 'min_weight_fraction_leaf': 0.1987273188587709, 'max_features': None, 'min_impurity_decrease': 0.0002775108319921543, 'validation_fraction': 0.9754822510610521, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24720275004054537
Fold 2 IBS: 0.23200270748604027
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:38:46,828] Trial 96 finished with value: 0.23591153802074527 and parameters: {'subsample': 0.5095341352345704, 'learning_rate': 0.08725364328306122, 'dropout_rate': 0.3223450290700977, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.1763548129966652, 'min_weight_fraction_leaf': 0.18056333859719206, 'max_features': None, 'min_impurity_decrease': 8.711621987475722e-07, 'validation_fraction': 0.9501887884981254, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:39:04,309] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38054192896008343, 'learning_rate': 0.0907069703578099, 'dropout_rate': 0.29952255515083975, 'n_estimators': 185, 'criterion': 'squared_error', 'ccp_alpha': 0.8146747487056372, 'min_weight_fraction_leaf': 0.12179773041599615, 'max_features': None, 'min_impurity_decrease': 2.402128990085841e-07, 'validation_fraction': 0.8821221020751453, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-13 21:39:26,363] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.46077614751832996, 'learning_rate': 0.09701740438937595, 'dropout_rate': 0.25455243694522434, 'n_estimators': 199, 'criterion': 'friedman_mse', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.14615364156535707, 'max_features': None, 'min_impurity_decrease': 1.4006375376158358e-07, 'validation_fraction': 0.9833042102806464, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 6}. Best is trial 91 with value: 0.22930168836973525.
Fold 1 IBS: 0.24343373022583664
Fold 2 IBS: 0.2272980963057972
Fold 3 IBS: 0.22299173682453308

Fold 4 IBS: 0.23852342496708018
Fold 5 IBS: 0.22486084489133845
[I 2024-04-13 21:39:40,076] Trial 99 finished with value: 0.23142156664291713 and parameters: {'subsample': 0.40791967441342253, 'learning_rate': 0.07712333235501795, 'dropout_rate': 0.19859974199600133, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.004426170739568851, 'min_weight_fraction_leaf': 0.16314282359709542, 'max_features': 'log2', 'min_impurity_decrease': 5.353566353972388e-07, 'validation_fraction': 0.1604355124738367, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 91 with value: 0.22930168836973525.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.22930168836973525], datetime_start=datetime.datetime(2024, 4, 13, 21, 37, 33, 748497), datetime_complete=datetime.datetime(2024, 4, 13, 21, 37, 48, 859878), params={'subsample': 0.3646963250854607, 'learning_rate': 0.09255241886126767, 'dropout_rate': 0.12363276406693596, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 0.03832008885345805, 'min_weight_fraction_leaf': 0.14198218649980035, 'max_features': None, 'min_impurity_decrease': 6.12703415921239e-07, 'validation_fraction': 0.965806971606102, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.22930168836973525

In [72]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [73]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.648
train_ibs:  0.229

#### Test

In [74]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [75]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.02647951541473475,
                                 criterion='squared_error',
                                 dropout_rate=0.14303111133639826,
                                 learning_rate=0.05317196534413593,
                                 max_depth=19, max_features=0.1,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=7.356647091617949e-06,
                                 min_samples_leaf=17, min_samples_split=19,
                                 min_weight_fraction_leaf=0.35066087197674667,
                                 n_estimators=78, random_state=123,
                                 subsample=0.9736544653699906,
                                 validation_fraction=0.6117331205297228)

C-index score: 0.639

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03832008885345805,
                                 criterion='squared_error',
                                 dropout_rate=0.12363276406693596,
                                 learning_rate=0.09255241886126767, max_depth=4,
                                 max_leaf_nodes=15,
                                 min_impurity_decrease=6.12703415921239e-07,
                                 min_samples_leaf=16, min_samples_split=13,
                                 min_weight_fraction_leaf=0.14198218649980035,
                                 n_estimators=143, random_state=123,
                                 subsample=0.3646963250854607,
                                 validation_fraction=0.965806971606102)

IBS: 0.221

In [76]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [77]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [78]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold( n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 21:39:44,118] A new study created in memory with name: no-name-ccd8a36d-73e0-4c21-b396-77d556801cfe

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:39:45,847] Trial 0 finished with value: 0.5866142624492122 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:39:59,513] Trial 1 finished with value: 0.576446015578343 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:40:02,224] Trial 2 finished with value: 0.5809712199713649 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:40:06,272] Trial 3 finished with value: 0.5800896533816691 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.5866142624492122.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:40:13,215] Trial 4 finished with value: 0.5882586728341248 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.5882586728341248.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:40:19,715] Trial 5 finished with value: 0.5755876464796306 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.5882586728341248.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:40:22,478] Trial 6 finished with value: 0.5755876464796306 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.5882586728341248.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:40:23,085] Trial 7 finished with value: 0.5833345326779854 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.5882586728341248.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:40:26,516] Trial 8 finished with value: 0.578591938325124 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.5882586728341248.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:40:35,984] Trial 9 finished with value: 0.5781664064102304 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.5882586728341248.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:40:43,736] Trial 10 finished with value: 0.5947419574096829 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.5947419574096829.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:40:51,999] Trial 11 finished with value: 0.6067372964931583 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6067372964931583.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:40:59,470] Trial 12 finished with value: 0.6083561218656349 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:41:09,162] Trial 13 finished with value: 0.574723627563861 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 21:41:16,718] Trial 14 finished with value: 0.6000597282048038 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:41:25,452] Trial 15 finished with value: 0.5908044320677265 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:41:38,823] Trial 16 finished with value: 0.599040514459728 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:41:51,860] Trial 17 finished with value: 0.5867082852372256 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:41:57,455] Trial 18 finished with value: 0.5867334851116943 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.6083561218656349.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:41:59,173] Trial 19 finished with value: 0.5981530941547009 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:42:11,429] Trial 20 finished with value: 0.5940715578620506 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:42:18,748] Trial 21 finished with value: 0.6009180973035162 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.7075879968118339, 'n_estimators': 348, 'learning_rate': 0.09588015704350664}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5765957446808511
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:42:25,333] Trial 22 finished with value: 0.5939593313554732 and parameters: {'subsample': 0.1832027123877466, 'dropout_rate': 0.6797578358009322, 'n_estimators': 323, 'learning_rate': 0.09071436663555825}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:42:30,467] Trial 23 finished with value: 0.5961919121675934 and parameters: {'subsample': 0.1529963084044875, 'dropout_rate': 0.8293972968657299, 'n_estimators': 288, 'learning_rate': 0.06498100052925637}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:42:37,786] Trial 24 finished with value: 0.58919278497734 and parameters: {'subsample': 0.30767755488363746, 'dropout_rate': 0.9639676260548358, 'n_estimators': 388, 'learning_rate': 0.07829757657217368}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:42:42,826] Trial 25 finished with value: 0.5898774982066015 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.5515081710932523, 'n_estimators': 231, 'learning_rate': 0.09163056701298726}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:42:50,165] Trial 26 finished with value: 0.5847163465165396 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.5707562654379044, 'n_estimators': 334, 'learning_rate': 0.08146277028320098}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:43:03,274] Trial 27 finished with value: 0.6008346680295836 and parameters: {'subsample': 0.10013177971822461, 'dropout_rate': 0.3060837787360696, 'n_estimators': 453, 'learning_rate': 0.04133902891970489}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:43:07,778] Trial 28 finished with value: 0.578591938325124 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.7802936418316316, 'n_estimators': 276, 'learning_rate': 0.09352800640830385}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:43:17,009] Trial 29 finished with value: 0.574723627563861 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.610605952426544, 'n_estimators': 394, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:43:19,011] Trial 30 finished with value: 0.5888525577330295 and parameters: {'subsample': 0.21797436717278929, 'dropout_rate': 0.3892024351052794, 'n_estimators': 129, 'learning_rate': 0.016814619253793885}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:43:32,112] Trial 31 finished with value: 0.6008346680295836 and parameters: {'subsample': 0.10788469758427235, 'dropout_rate': 0.31552207224123663, 'n_estimators': 451, 'learning_rate': 0.038020387978666075}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:43:47,920] Trial 32 finished with value: 0.5934266121625568 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.16292220425617515, 'n_estimators': 494, 'learning_rate': 0.042584030841756326}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:00,402] Trial 33 finished with value: 0.5968002045356261 and parameters: {'subsample': 0.10118727716270738, 'dropout_rate': 0.4658432799279118, 'n_estimators': 449, 'learning_rate': 0.06992697841465893}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 21:44:08,312] Trial 34 finished with value: 0.5891024313949869 and parameters: {'subsample': 0.2300700298745233, 'dropout_rate': 0.29838327548056925, 'n_estimators': 341, 'learning_rate': 0.03125760756680494}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:12,944] Trial 35 finished with value: 0.5972878436301194 and parameters: {'subsample': 0.16710472630778297, 'dropout_rate': 0.19242557819860076, 'n_estimators': 237, 'learning_rate': 0.09381151266795838}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5271317829457365
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:44:24,136] Trial 36 finished with value: 0.5923694302024761 and parameters: {'subsample': 0.3141493025161577, 'dropout_rate': 0.13352827544179913, 'n_estimators': 393, 'learning_rate': 0.07158461284458016}. Best is trial 12 with value: 0.6083561218656349.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 21:44:24,499] Trial 37 finished with value: 0.63135676757979 and parameters: {'subsample': 0.14187696914743586, 'dropout_rate': 0.3917773398227318, 'n_estimators': 1, 'learning_rate': 0.05621431261796065}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:44:25,731] Trial 38 finished with value: 0.5907125428274955 and parameters: {'subsample': 0.2765053049871465, 'dropout_rate': 0.49675407246821296, 'n_estimators': 46, 'learning_rate': 0.07843779087354608}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:44:28,499] Trial 39 finished with value: 0.584290814601646 and parameters: {'subsample': 0.4186552843670305, 'dropout_rate': 0.4122412566560423, 'n_estimators': 159, 'learning_rate': 0.05598015324329953}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:44:29,749] Trial 40 finished with value: 0.5866142624492122 and parameters: {'subsample': 0.7867781413542204, 'dropout_rate': 0.20013020077502125, 'n_estimators': 78, 'learning_rate': 0.09984551151794506}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 21:44:36,626] Trial 41 finished with value: 0.5930937839746704 and parameters: {'subsample': 0.13920009866686117, 'dropout_rate': 0.43438444790071074, 'n_estimators': 298, 'learning_rate': 0.04304908705186268}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:44:37,135] Trial 42 finished with value: 0.6126245805223757 and parameters: {'subsample': 0.17105705523013376, 'dropout_rate': 0.28675590381203225, 'n_estimators': 11, 'learning_rate': 0.04866598082075101}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:44:37,720] Trial 43 finished with value: 0.6014243212718128 and parameters: {'subsample': 0.19140322346524258, 'dropout_rate': 0.369858527743824, 'n_estimators': 21, 'learning_rate': 0.055825768503472484}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6634980988593155
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 21:44:38,193] Trial 44 finished with value: 0.585364242050707 and parameters: {'subsample': 0.19014631843905178, 'dropout_rate': 0.3728303402102903, 'n_estimators': 3, 'learning_rate': 0.050379873075262045}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:44:38,801] Trial 45 finished with value: 0.5848225715153503 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.5028371582629666, 'n_estimators': 23, 'learning_rate': 0.04892233066253526}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:41,126] Trial 46 finished with value: 0.5847923435347122 and parameters: {'subsample': 0.3146299784349317, 'dropout_rate': 0.28471093453813157, 'n_estimators': 74, 'learning_rate': 0.0575523325533853}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6075697211155379
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.5987124463519313
[I 2024-04-13 21:44:41,730] Trial 47 finished with value: 0.5938019740125934 and parameters: {'subsample': 0.19598228689905128, 'dropout_rate': 0.14103414386440358, 'n_estimators': 5, 'learning_rate': 0.06513631207818486}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5387596899224806
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:44:43,581] Trial 48 finished with value: 0.6003375412582544 and parameters: {'subsample': 0.14527182024086607, 'dropout_rate': 0.2531899235661427, 'n_estimators': 84, 'learning_rate': 0.029987301889198528}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:44,972] Trial 49 finished with value: 0.5805456880564714 and parameters: {'subsample': 0.42310111380942905, 'dropout_rate': 0.21753125771684506, 'n_estimators': 47, 'learning_rate': 0.010538169385121338}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:44:45,873] Trial 50 finished with value: 0.5860922134879389 and parameters: {'subsample': 0.25269319898361897, 'dropout_rate': 0.3532519390939622, 'n_estimators': 31, 'learning_rate': 0.04784440895245933}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.5329457364341085
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:44:46,425] Trial 51 finished with value: 0.6042924600094607 and parameters: {'subsample': 0.14620431764658126, 'dropout_rate': 0.11057714702883631, 'n_estimators': 23, 'learning_rate': 0.06547698978630012}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6276595744680851
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6652360515021459
[I 2024-04-13 21:44:47,838] Trial 52 finished with value: 0.6083807675062193 and parameters: {'subsample': 0.13637380813559394, 'dropout_rate': 0.11379938110810188, 'n_estimators': 65, 'learning_rate': 0.06368925384651636}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:49,473] Trial 53 finished with value: 0.6019812696489785 and parameters: {'subsample': 0.14907566998318839, 'dropout_rate': 0.10201589593983289, 'n_estimators': 95, 'learning_rate': 0.06197138714804373}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 21:44:50,183] Trial 54 finished with value: 0.5941113253918183 and parameters: {'subsample': 0.13757872206165236, 'dropout_rate': 0.14514560534262816, 'n_estimators': 42, 'learning_rate': 0.06678607226498563}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:44:51,139] Trial 55 finished with value: 0.5807415137063677 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.18226800835487564, 'n_estimators': 62, 'learning_rate': 0.07493135984351246}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:54,051] Trial 56 finished with value: 0.5947415335666267 and parameters: {'subsample': 0.18022329642874463, 'dropout_rate': 0.12035524124489141, 'n_estimators': 145, 'learning_rate': 0.037171777834429084}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5193798449612403
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:44:58,548] Trial 57 finished with value: 0.5867482226363798 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.2670376806268556, 'n_estimators': 198, 'learning_rate': 0.05305288545313308}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5135658914728682
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:45:00,646] Trial 58 finished with value: 0.5914489871234998 and parameters: {'subsample': 0.23363241149901381, 'dropout_rate': 0.22037157727939666, 'n_estimators': 106, 'learning_rate': 0.0605456807418216}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:01,781] Trial 59 finished with value: 0.5794503074238365 and parameters: {'subsample': 0.6869904791039767, 'dropout_rate': 0.16256099098724258, 'n_estimators': 61, 'learning_rate': 0.08322655251020356}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.6191489361702127
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:45:02,289] Trial 60 finished with value: 0.5997603722826862 and parameters: {'subsample': 0.13534087564234862, 'dropout_rate': 0.11354955299577604, 'n_estimators': 19, 'learning_rate': 0.07425766903307461}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.6191489361702127
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 21:45:03,910] Trial 61 finished with value: 0.6021294123534778 and parameters: {'subsample': 0.13294430744277427, 'dropout_rate': 0.10823365520816174, 'n_estimators': 90, 'learning_rate': 0.06188461037752872}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5232558139534884
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:45:11,667] Trial 62 finished with value: 0.5974028033744987 and parameters: {'subsample': 0.13047467302375332, 'dropout_rate': 0.1003221333020151, 'n_estimators': 317, 'learning_rate': 0.04630335409130657}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:12,071] Trial 63 finished with value: 0.6031243870941528 and parameters: {'subsample': 0.1774136494024078, 'dropout_rate': 0.16476602500283072, 'n_estimators': 6, 'learning_rate': 0.052087148941014565}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5290697674418605
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:45:12,512] Trial 64 finished with value: 0.5855472656619926 and parameters: {'subsample': 0.20929995946112884, 'dropout_rate': 0.15912073711759742, 'n_estimators': 9, 'learning_rate': 0.0531684552723658}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:45:13,138] Trial 65 finished with value: 0.596313022483525 and parameters: {'subsample': 0.17226063411855955, 'dropout_rate': 0.19152079334472727, 'n_estimators': 33, 'learning_rate': 0.08874412651372245}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:45:14,226] Trial 66 finished with value: 0.5960327398491579 and parameters: {'subsample': 0.17881900681359358, 'dropout_rate': 0.22938455683546322, 'n_estimators': 66, 'learning_rate': 0.05772080357763175}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6235059760956175
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6596958174904943
Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:45:14,761] Trial 67 finished with value: 0.5936765077645288 and parameters: {'subsample': 0.2187994851655431, 'dropout_rate': 0.16716863716781255, 'n_estimators': 4, 'learning_rate': 0.06663483217776751}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:24,356] Trial 68 finished with value: 0.5794503074238365 and parameters: {'subsample': 0.6099875522212969, 'dropout_rate': 0.26925479806804564, 'n_estimators': 371, 'learning_rate': 0.03798424881808041}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5155038759689923
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:29,843] Trial 69 finished with value: 0.5883271106097023 and parameters: {'subsample': 0.35117356559290447, 'dropout_rate': 0.32941102752965035, 'n_estimators': 259, 'learning_rate': 0.052595847243253016}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6482889733840305
Fold 5 C-index: 0.6244635193133047
[I 2024-04-13 21:45:37,313] Trial 70 finished with value: 0.574723627563861 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.1314991615217315, 'n_estimators': 283, 'learning_rate': 0.046242565941295964}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6609442060085837
[I 2024-04-13 21:45:38,056] Trial 71 finished with value: 0.6079056869324939 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.151117463899618, 'n_estimators': 34, 'learning_rate': 0.06291649109551006}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5426356589147286
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:45:38,769] Trial 72 finished with value: 0.6230287768828793 and parameters: {'subsample': 0.11936979043109645, 'dropout_rate': 0.20594758017900425, 'n_estimators': 30, 'learning_rate': 0.05903772221535725}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:45:39,767] Trial 73 finished with value: 0.6165166950746767 and parameters: {'subsample': 0.11100485126820124, 'dropout_rate': 0.2034179144446979, 'n_estimators': 36, 'learning_rate': 0.06369935058655073}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:40,975] Trial 74 finished with value: 0.6086435937366582 and parameters: {'subsample': 0.11578056377669708, 'dropout_rate': 0.20749618257848298, 'n_estimators': 55, 'learning_rate': 0.057656890825242765}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:45:41,885] Trial 75 finished with value: 0.6029455380622837 and parameters: {'subsample': 0.10163330992087008, 'dropout_rate': 0.2129112703000903, 'n_estimators': 51, 'learning_rate': 0.06916981145995393}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:45:42,914] Trial 76 finished with value: 0.6067791257232245 and parameters: {'subsample': 0.12209766492198151, 'dropout_rate': 0.24785011657647843, 'n_estimators': 38, 'learning_rate': 0.05992326510937737}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:44,884] Trial 77 finished with value: 0.5947415335666267 and parameters: {'subsample': 0.15791154414712263, 'dropout_rate': 0.28756803413266274, 'n_estimators': 112, 'learning_rate': 0.05593345775154633}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6566523605150214
[I 2024-04-13 21:45:46,054] Trial 78 finished with value: 0.6131138340680113 and parameters: {'subsample': 0.11863105085825669, 'dropout_rate': 0.20046038935402893, 'n_estimators': 52, 'learning_rate': 0.07121632275952519}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5174418604651163
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:47,368] Trial 79 finished with value: 0.5920647117472928 and parameters: {'subsample': 0.2080440387125822, 'dropout_rate': 0.23777003572261127, 'n_estimators': 63, 'learning_rate': 0.07178035481014644}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:50,188] Trial 80 finished with value: 0.5964979123069843 and parameters: {'subsample': 0.16226905061975858, 'dropout_rate': 0.19764371587586999, 'n_estimators': 133, 'learning_rate': 0.05869912620485801}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-13 21:45:50,842] Trial 81 finished with value: 0.6233142686151872 and parameters: {'subsample': 0.11935930037739542, 'dropout_rate': 0.1476977443526841, 'n_estimators': 18, 'learning_rate': 0.06410686612842544}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:45:51,638] Trial 82 finished with value: 0.6123097160500821 and parameters: {'subsample': 0.12482555191816715, 'dropout_rate': 0.17911291165858503, 'n_estimators': 49, 'learning_rate': 0.06821556470884046}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:45:52,533] Trial 83 finished with value: 0.6174128625190074 and parameters: {'subsample': 0.1137253938554455, 'dropout_rate': 0.18184738326200484, 'n_estimators': 52, 'learning_rate': 0.06808690615532906}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.6063829787234043
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:45:53,096] Trial 84 finished with value: 0.6068844708039327 and parameters: {'subsample': 0.1181399773898554, 'dropout_rate': 0.2766544922955371, 'n_estimators': 20, 'learning_rate': 0.06779294924512375}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:45:53,979] Trial 85 finished with value: 0.6029455380622837 and parameters: {'subsample': 0.10269958198389634, 'dropout_rate': 0.20529355154590012, 'n_estimators': 51, 'learning_rate': 0.07000460797664394}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:45:55,169] Trial 86 finished with value: 0.5990299251231095 and parameters: {'subsample': 0.16629661748396354, 'dropout_rate': 0.3197437150599388, 'n_estimators': 77, 'learning_rate': 0.07496094243600174}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5893617021276596
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.648068669527897
[I 2024-04-13 21:45:57,077] Trial 87 finished with value: 0.5965125228448349 and parameters: {'subsample': 0.19293435065901648, 'dropout_rate': 0.17971650523934474, 'n_estimators': 96, 'learning_rate': 0.07226396598226621}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5251937984496124
Fold 3 C-index: 0.5723404255319149
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:57,962] Trial 88 finished with value: 0.5917860076533549 and parameters: {'subsample': 0.24629396301839718, 'dropout_rate': 0.2493339131508072, 'n_estimators': 53, 'learning_rate': 0.0550566146777322}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:45:58,436] Trial 89 finished with value: 0.5786898511500722 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.3520859486343014, 'n_estimators': 14, 'learning_rate': 0.07744563506647177}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5213178294573644
Fold 3 C-index: 0.6106382978723405
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6695278969957081
[I 2024-04-13 21:45:59,118] Trial 90 finished with value: 0.606199884561506 and parameters: {'subsample': 0.12462033231171393, 'dropout_rate': 0.295247635541479, 'n_estimators': 33, 'learning_rate': 0.04983757431249405}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6437768240343348
[I 2024-04-13 21:46:00,461] Trial 91 finished with value: 0.6051428199050447 and parameters: {'subsample': 0.15079969654801856, 'dropout_rate': 0.22854706433541658, 'n_estimators': 68, 'learning_rate': 0.06346337776713165}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5348837209302325
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6781115879828327
[I 2024-04-13 21:46:01,256] Trial 92 finished with value: 0.6043916809669065 and parameters: {'subsample': 0.12816725472577012, 'dropout_rate': 0.17905397516416072, 'n_estimators': 28, 'learning_rate': 0.06504467872292474}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.597872340425532
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6351931330472103
[I 2024-04-13 21:46:02,114] Trial 93 finished with value: 0.5964727124325158 and parameters: {'subsample': 0.15503139388934215, 'dropout_rate': 0.1365499812478257, 'n_estimators': 42, 'learning_rate': 0.06342785462045782}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.630901287553648
[I 2024-04-13 21:46:03,060] Trial 94 finished with value: 0.6051289940586283 and parameters: {'subsample': 0.1019339266672185, 'dropout_rate': 0.2165015753252632, 'n_estimators': 53, 'learning_rate': 0.05928022349678612}. Best is trial 37 with value: 0.63135676757979.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6523605150214592
[I 2024-04-13 21:46:04,299] Trial 95 finished with value: 0.5957051207592126 and parameters: {'subsample': 0.19986193523835377, 'dropout_rate': 0.19740024462212413, 'n_estimators': 81, 'learning_rate': 0.06842995594499052}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.6319148936170212
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-13 21:46:05,192] Trial 96 finished with value: 0.6017855103977539 and parameters: {'subsample': 0.13539218203313957, 'dropout_rate': 0.13038599126251973, 'n_estimators': 58, 'learning_rate': 0.057425548394441216}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6051502145922747
[I 2024-04-13 21:46:05,675] Trial 97 finished with value: 0.5762319267561336 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.2634689828700472, 'n_estimators': 20, 'learning_rate': 0.07631718819240524}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.49806201550387597
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.592274678111588
[I 2024-04-13 21:46:06,070] Trial 98 finished with value: 0.575465981350222 and parameters: {'subsample': 0.18224094885007322, 'dropout_rate': 0.17917721450099294, 'n_estimators': 1, 'learning_rate': 0.08062035216684603}. Best is trial 37 with value: 0.63135676757979.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.5553191489361702
Fold 4 C-index: 0.623574144486692

[I 2024-04-13 21:46:07,532] A new study created in memory with name: no-name-4103ab49-d4fb-429b-ba95-75414db9364c

Fold 5 C-index: 0.6201716738197425
[I 2024-04-13 21:46:07,512] Trial 99 finished with value: 0.5689222926856807 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.61604509220462, 'n_estimators': 102, 'learning_rate': 0.06389622294829299}. Best is trial 37 with value: 0.63135676757979.


* Best trial for C-index:
 FrozenTrial(number=37, state=TrialState.COMPLETE, values=[0.63135676757979], datetime_start=datetime.datetime(2024, 4, 13, 21, 44, 24, 143692), datetime_complete=datetime.datetime(2024, 4, 13, 21, 44, 24, 498403), params={'subsample': 0.14187696914743586, 'dropout_rate': 0.3917773398227318, 'n_estimators': 1, 'learning_rate': 0.05621431261796065}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=37, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.14187696914743586, 'dropout_rate': 0.3917773398227318, 'n_estimators': 1, 'learning_rate': 0.05621431261796065}


* Best Score for C-index:
 0.63135676757979

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2764983757259828
Fold 2 IBS: 0.25827328872655125
Fold 3 IBS: 0.2681918537299111
Fold 4 IBS: 0.25164204958791786
Fold 5 IBS: 0.23049650269649638
[I 2024-04-13 21:46:09,251] Trial 0 finished with value: 0.2570204140933719 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3324786566928669
Fold 2 IBS: 0.3788072699032086
Fold 3 IBS: 0.32206673578733985
Fold 4 IBS: 0.3101839972428508
Fold 5 IBS: 0.339376702626222
[I 2024-04-13 21:46:23,547] Trial 1 finished with value: 0.33658267245049767 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3080969081334638
Fold 2 IBS: 0.33679097151835613
Fold 3 IBS: 0.29794642580347785
Fold 4 IBS: 0.2970348516964966
Fold 5 IBS: 0.3098400786191256
[I 2024-04-13 21:46:26,339] Trial 2 finished with value: 0.309941847154184 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3064767874727317
Fold 2 IBS: 0.3619250483768896
Fold 3 IBS: 0.29817515853010107
Fold 4 IBS: 0.31682966574196564
Fold 5 IBS: 0.266324370012311
[I 2024-04-13 21:46:30,042] Trial 3 finished with value: 0.3099462060267998 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.30482111083138314
Fold 2 IBS: 0.3648225665978812
Fold 3 IBS: 0.2967876341327154
Fold 4 IBS: 0.33090214854017697
Fold 5 IBS: 0.27970342485733457
[I 2024-04-13 21:46:35,907] Trial 4 finished with value: 0.3154073769918983 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.3330915321934708
Fold 2 IBS: 0.37508609294519507
Fold 3 IBS: 0.3171124043871855
Fold 4 IBS: 0.3137047618879898
Fold 5 IBS: 0.33923818447315957
[I 2024-04-13 21:46:43,309] Trial 5 finished with value: 0.33564659517740014 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2570204140933719.
Fold 1 IBS: 0.2582524703242828
Fold 2 IBS: 0.24410448346165017
Fold 3 IBS: 0.2489984543833783
Fold 4 IBS: 0.24105975122742593
Fold 5 IBS: 0.21760040361445157
[I 2024-04-13 21:46:46,622] Trial 6 finished with value: 0.24200311260223778 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.24200311260223778.
Fold 1 IBS: 0.24405440410530252
Fold 2 IBS: 0.2313144095096795
Fold 3 IBS: 0.2264872598945243
Fold 4 IBS: 0.2396665980161307
Fold 5 IBS: 0.21378036357257543
[I 2024-04-13 21:46:47,279] Trial 7 finished with value: 0.23106060701964246 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2721670320379247
Fold 2 IBS: 0.26349028676887165
Fold 3 IBS: 0.27256269344805145
Fold 4 IBS: 0.26295637706133196
Fold 5 IBS: 0.22443103181808433
[I 2024-04-13 21:46:50,906] Trial 8 finished with value: 0.25912148422685277 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.3247548329286031
Fold 2 IBS: 0.37802658126398786
Fold 3 IBS: 0.31858508252734163
Fold 4 IBS: 0.34033930403036083
Fold 5 IBS: 0.3390006997862931
[I 2024-04-13 21:47:01,339] Trial 9 finished with value: 0.34014130010731736 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.2320380130694877
Fold 3 IBS: 0.22856386796454758
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22906264846898927
[I 2024-04-13 21:47:01,947] Trial 10 finished with value: 0.2356827908284253 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24639976969987745
Fold 2 IBS: 0.23211191483262145
Fold 3 IBS: 0.22735462180753221
Fold 4 IBS: 0.24087071384643838
Fold 5 IBS: 0.2279748608955893
[I 2024-04-13 21:47:02,350] Trial 11 finished with value: 0.23494237621641179 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24224696569287882
Fold 2 IBS: 0.2415471907175228
Fold 3 IBS: 0.24134666183647926
Fold 4 IBS: 0.2645169933823727
Fold 5 IBS: 0.19659950167553716
[I 2024-04-13 21:47:03,185] Trial 12 finished with value: 0.23725146266095815 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24595650697573987
Fold 2 IBS: 0.23159750511026025
Fold 3 IBS: 0.22650743980304022
Fold 4 IBS: 0.2402759194782458
Fold 5 IBS: 0.2271234075322375
[I 2024-04-13 21:47:03,633] Trial 13 finished with value: 0.23429215577990475 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24578997040449777
Fold 2 IBS: 0.23848258024250096
Fold 3 IBS: 0.23923657468396856
Fold 4 IBS: 0.24712698608446457
Fold 5 IBS: 0.2057521648238833
[I 2024-04-13 21:47:05,437] Trial 14 finished with value: 0.23527765524786304 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.273062339353825
Fold 2 IBS: 0.2917310339898808
Fold 3 IBS: 0.2797674129217372
Fold 4 IBS: 0.27749936521479274
Fold 5 IBS: 0.2222306166387489
[I 2024-04-13 21:47:06,914] Trial 15 finished with value: 0.26885815362379695 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2850596201683694
Fold 2 IBS: 0.3165534004517282
Fold 3 IBS: 0.26962430967935924
Fold 4 IBS: 0.2862217453626214
Fold 5 IBS: 0.20911528821633776
[I 2024-04-13 21:47:11,747] Trial 16 finished with value: 0.2733148727756832 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24417753569669493
Fold 2 IBS: 0.23250586456391067
Fold 3 IBS: 0.22353591901388314
Fold 4 IBS: 0.2373942868900049
Fold 5 IBS: 0.22198742696468415
[I 2024-04-13 21:47:12,789] Trial 17 finished with value: 0.2319202066258356 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2546743281324155
Fold 2 IBS: 0.2466299808965928
Fold 3 IBS: 0.24423165608646885
Fold 4 IBS: 0.23899157625792516
Fold 5 IBS: 0.21624465931312048
[I 2024-04-13 21:47:19,750] Trial 18 finished with value: 0.24015444013730453 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24376155682470516
Fold 2 IBS: 0.23602577631297375

Fold 3 IBS: 0.23443639398619098
Fold 4 IBS: 0.24374854938649268
Fold 5 IBS: 0.20898654378339646
[I 2024-04-13 21:47:21,591] Trial 19 finished with value: 0.2333917640587518 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.244476360186189
Fold 2 IBS: 0.2305472199436817
Fold 3 IBS: 0.22377140228384404
Fold 4 IBS: 0.2386766254699274
Fold 5 IBS: 0.22296335334244682
[I 2024-04-13 21:47:22,527] Trial 20 finished with value: 0.23208699224521778 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24513654608372853
Fold 2 IBS: 0.23094110628575634
Fold 3 IBS: 0.22464827063854145
Fold 4 IBS: 0.23926825072734292
Fold 5 IBS: 0.22475950483168106
[I 2024-04-13 21:47:23,406] Trial 21 finished with value: 0.23295073571341005 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24410368410205424
Fold 2 IBS: 0.23269100476640445
Fold 3 IBS: 0.22348442285008668
Fold 4 IBS: 0.23709008023572514
Fold 5 IBS: 0.2214330028375883
[I 2024-04-13 21:47:24,264] Trial 22 finished with value: 0.23176043895837178 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.7601905131808098, 'n_estimators': 57, 'learning_rate': 0.019334429052945145}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.27667017123091864
Fold 2 IBS: 0.26065061447392923
Fold 3 IBS: 0.26926155221797393
Fold 4 IBS: 0.2515347857203304
Fold 5 IBS: 0.24492971400337946
[I 2024-04-13 21:47:26,622] Trial 23 finished with value: 0.26060936752930636 and parameters: {'subsample': 0.8557281003254902, 'dropout_rate': 0.618865896035061, 'n_estimators': 150, 'learning_rate': 0.04186582141545488}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2440565511099749
Fold 2 IBS: 0.2333802807049335
Fold 3 IBS: 0.22381547481112268
Fold 4 IBS: 0.23631803336762525
Fold 5 IBS: 0.21989798922004192
[I 2024-04-13 21:47:27,554] Trial 24 finished with value: 0.23149366584273964 and parameters: {'subsample': 0.8736292350257677, 'dropout_rate': 0.9758883725345413, 'n_estimators': 56, 'learning_rate': 0.02427957701685606}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24363637213093994
Fold 2 IBS: 0.22964026459903003
Fold 3 IBS: 0.2222644494549489
Fold 4 IBS: 0.23973298860834963
Fold 5 IBS: 0.22076487111843845
[I 2024-04-13 21:47:28,347] Trial 25 finished with value: 0.23120778918234142 and parameters: {'subsample': 0.19468056412788132, 'dropout_rate': 0.9897789595635863, 'n_estimators': 40, 'learning_rate': 0.025002990823540957}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.2448054095620852
Fold 2 IBS: 0.24089291457583237
Fold 3 IBS: 0.2405397644738199
Fold 4 IBS: 0.2570730601436595
Fold 5 IBS: 0.20292878970886452
[I 2024-04-13 21:47:29,631] Trial 26 finished with value: 0.2372479876928523 and parameters: {'subsample': 0.20966372435124492, 'dropout_rate': 0.9922976382051985, 'n_estimators': 92, 'learning_rate': 0.04553017387255954}. Best is trial 7 with value: 0.23106060701964246.
Fold 1 IBS: 0.24315202579827286
Fold 2 IBS: 0.2296084891350833
Fold 3 IBS: 0.22200653425010497
Fold 4 IBS: 0.23944512448046287
Fold 5 IBS: 0.2201695165369695
[I 2024-04-13 21:47:30,391] Trial 27 finished with value: 0.23087633804017868 and parameters: {'subsample': 0.1957599112234488, 'dropout_rate': 0.9027419458320135, 'n_estimators': 35, 'learning_rate': 0.030307532796347948}. Best is trial 27 with value: 0.23087633804017868.
Fold 1 IBS: 0.2573991047049186
Fold 2 IBS: 0.27258595177362654
Fold 3 IBS: 0.2642472632863359
Fold 4 IBS: 0.2759082204379633
Fold 5 IBS: 0.20650296356630185
[I 2024-04-13 21:47:33,930] Trial 28 finished with value: 0.25532870075382924 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.9027419284965903, 'n_estimators': 226, 'learning_rate': 0.031981052358301974}. Best is trial 27 with value: 0.23087633804017868.
Fold 1 IBS: 0.2701205542877407
Fold 2 IBS: 0.2718228322697603
Fold 3 IBS: 0.27619632549182793
Fold 4 IBS: 0.2697529828966249
Fold 5 IBS: 0.22912475988694875
[I 2024-04-13 21:47:35,457] Trial 29 finished with value: 0.2634034909665805 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.9065003057392301, 'n_estimators': 123, 'learning_rate': 0.06046208382653473}. Best is trial 27 with value: 0.23087633804017868.
Fold 1 IBS: 0.24465701862852837
Fold 2 IBS: 0.22988630833417179
Fold 3 IBS: 0.22370749254678077
Fold 4 IBS: 0.24000784541540324
Fold 5 IBS: 0.22297351910444194
[I 2024-04-13 21:47:36,130] Trial 30 finished with value: 0.2322464368058652 and parameters: {'subsample': 0.2544227872032339, 'dropout_rate': 0.9282511838266186, 'n_estimators': 28, 'learning_rate': 0.027842347268350807}. Best is trial 27 with value: 0.23087633804017868.
Fold 1 IBS: 0.24269379368080135
Fold 2 IBS: 0.2306427681968945
Fold 3 IBS: 0.22058930480292438
Fold 4 IBS: 0.23919463768232538
Fold 5 IBS: 0.21657001016740546
[I 2024-04-13 21:47:36,921] Trial 31 finished with value: 0.22993810290607022 and parameters: {'subsample': 0.1642548972610388, 'dropout_rate': 0.9934257769141778, 'n_estimators': 33, 'learning_rate': 0.04375362682378537}. Best is trial 31 with value: 0.22993810290607022.
Fold 1 IBS: 0.24270802017529158
Fold 2 IBS: 0.23036986155336894
Fold 3 IBS: 0.22215095810751617
Fold 4 IBS: 0.2382189808472928
Fold 5 IBS: 0.22028742891424777
[I 2024-04-13 21:47:37,534] Trial 32 finished with value: 0.23074704991954342 and parameters: {'subsample': 0.1823374077872404, 'dropout_rate': 0.8466020367236368, 'n_estimators': 24, 'learning_rate': 0.04494727255588112}. Best is trial 31 with value: 0.22993810290607022.
Fold 1 IBS: 0.2521772018190524
Fold 2 IBS: 0.2580205345884183
Fold 3 IBS: 0.2520309906596739
Fold 4 IBS: 0.2723957619425764
Fold 5 IBS: 0.20343373979694343
[I 2024-04-13 21:47:40,046] Trial 33 finished with value: 0.24761164576133293 and parameters: {'subsample': 0.15400402688810244, 'dropout_rate': 0.7882041442222055, 'n_estimators': 147, 'learning_rate': 0.043942081495779856}. Best is trial 31 with value: 0.22993810290607022.
Fold 1 IBS: 0.24630357131942598
Fold 2 IBS: 0.23146124966545564
Fold 3 IBS: 0.22774649516359757
Fold 4 IBS: 0.24053981115246043
Fold 5 IBS: 0.22812767511192403
[I 2024-04-13 21:47:40,648] Trial 34 finished with value: 0.23483576048257274 and parameters: {'subsample': 0.2726652412636189, 'dropout_rate': 0.8485051228764354, 'n_estimators': 3, 'learning_rate': 0.05688116043539708}. Best is trial 31 with value: 0.22993810290607022.
Fold 1 IBS: 0.2504291854289503
Fold 2 IBS: 0.24893095057842016
Fold 3 IBS: 0.2533639726793715
Fold 4 IBS: 0.25077045575234225
Fold 5 IBS: 0.20864134330595183
[I 2024-04-13 21:47:42,197] Trial 35 finished with value: 0.2424271815490072 and parameters: {'subsample': 0.41006550861805074, 'dropout_rate': 0.8466800774122824, 'n_estimators': 102, 'learning_rate': 0.046976531028194955}. Best is trial 31 with value: 0.22993810290607022.
Fold 1 IBS: 0.24403628300868618
Fold 2 IBS: 0.2351699465534994
Fold 3 IBS: 0.23568280072485964
Fold 4 IBS: 0.2463736885513991
Fold 5 IBS: 0.2098235751420586
[I 2024-04-13 21:47:43,389] Trial 36 finished with value: 0.23421725879610059 and parameters: {'subsample': 0.31527768870466144, 'dropout_rate': 0.9389838701653996, 'n_estimators': 82, 'learning_rate': 0.03767113612647347}. Best is trial 31 with value: 0.22993810290607022.
Fold 1 IBS: 0.2413494522452083
Fold 2 IBS: 0.23045111982440822
Fold 3 IBS: 0.21947506742206493
Fold 4 IBS: 0.24068661781576536
Fold 5 IBS: 0.21125697092801926
[I 2024-04-13 21:47:44,119] Trial 37 finished with value: 0.22864384564709322 and parameters: {'subsample': 0.1597953218917586, 'dropout_rate': 0.47096246897520044, 'n_estimators': 32, 'learning_rate': 0.06738480132106772}. Best is trial 37 with value: 0.22864384564709322.
Fold 1 IBS: 0.2996472974341713
Fold 2 IBS: 0.34379287262856223

Fold 3 IBS: 0.26639509455111465
Fold 4 IBS: 0.2932421765596226
Fold 5 IBS: 0.21878189898179665
[I 2024-04-13 21:47:47,574] Trial 38 finished with value: 0.28437186803105347 and parameters: {'subsample': 0.10133044273581891, 'dropout_rate': 0.29839135236038283, 'n_estimators': 180, 'learning_rate': 0.07288612365177065}. Best is trial 37 with value: 0.22864384564709322.
Fold 1 IBS: 0.24367533970078817
Fold 2 IBS: 0.230581843797866
Fold 3 IBS: 0.22426510493646246
Fold 4 IBS: 0.24086016296070725
Fold 5 IBS: 0.21485542180084868
[I 2024-04-13 21:47:48,346] Trial 39 finished with value: 0.2308475746393345 and parameters: {'subsample': 0.23574838842029588, 'dropout_rate': 0.44092575231554404, 'n_estimators': 31, 'learning_rate': 0.06528568864007542}. Best is trial 37 with value: 0.22864384564709322.
Fold 1 IBS: 0.38495903085339733
Fold 2 IBS: 0.37839237180942703
Fold 3 IBS: 0.31605836309462204
Fold 4 IBS: 0.3964877229235561
Fold 5 IBS: 0.33876619173980255
[I 2024-04-13 21:48:00,309] Trial 40 finished with value: 0.36293273608416105 and parameters: {'subsample': 0.24868424899023683, 'dropout_rate': 0.4615618352119887, 'n_estimators': 434, 'learning_rate': 0.06707913177650868}. Best is trial 37 with value: 0.22864384564709322.
Fold 1 IBS: 0.23877678258033766
Fold 2 IBS: 0.23320908202640503
Fold 3 IBS: 0.2226601986699706
Fold 4 IBS: 0.2460141561256072
Fold 5 IBS: 0.20631157436706155
[I 2024-04-13 21:48:01,211] Trial 41 finished with value: 0.2293943587538764 and parameters: {'subsample': 0.16275106363035888, 'dropout_rate': 0.5066004657831531, 'n_estimators': 35, 'learning_rate': 0.08229165873203476}. Best is trial 37 with value: 0.22864384564709322.
Fold 1 IBS: 0.24341129361062072
Fold 2 IBS: 0.22972991908489984
Fold 3 IBS: 0.22099965618059145
Fold 4 IBS: 0.23736823345029712
Fold 5 IBS: 0.21439524935042115
[I 2024-04-13 21:48:01,782] Trial 42 finished with value: 0.22918087033536608 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.39783037447919617, 'n_estimators': 20, 'learning_rate': 0.0792130872942141}. Best is trial 37 with value: 0.22864384564709322.
Fold 1 IBS: 0.24197741562227687
Fold 2 IBS: 0.22905371862313562
Fold 3 IBS: 0.2184388665292217
Fold 4 IBS: 0.2386044594910095
Fold 5 IBS: 0.2114188152009225
[I 2024-04-13 21:48:02,398] Trial 43 finished with value: 0.22789865509331322 and parameters: {'subsample': 0.15059393391736864, 'dropout_rate': 0.3731933165715856, 'n_estimators': 21, 'learning_rate': 0.0844491597917184}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2525241361454453
Fold 2 IBS: 0.25693024865735714
Fold 3 IBS: 0.2482776388773168
Fold 4 IBS: 0.2690733484725458
Fold 5 IBS: 0.19617927837233926
[I 2024-04-13 21:48:03,663] Trial 44 finished with value: 0.2445969301050009 and parameters: {'subsample': 0.13407799732857442, 'dropout_rate': 0.35795094080665946, 'n_estimators': 80, 'learning_rate': 0.08217100206906833}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24404892668243822
Fold 2 IBS: 0.22938621721358454
Fold 3 IBS: 0.22293078901318866
Fold 4 IBS: 0.2391963660192634
Fold 5 IBS: 0.2218927379792537
[I 2024-04-13 21:48:04,158] Trial 45 finished with value: 0.2314910073815457 and parameters: {'subsample': 0.28969183059230424, 'dropout_rate': 0.22436841778456168, 'n_estimators': 12, 'learning_rate': 0.07819151324912664}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.28006509479631736
Fold 2 IBS: 0.31264750415136405
Fold 3 IBS: 0.2728304477045035
Fold 4 IBS: 0.29313821491812475
Fold 5 IBS: 0.22656368641776034
[I 2024-04-13 21:48:06,014] Trial 46 finished with value: 0.2770489895976139 and parameters: {'subsample': 0.14293658419752656, 'dropout_rate': 0.4063470550139794, 'n_estimators': 122, 'learning_rate': 0.0882342970461842}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.29458658493606243
Fold 2 IBS: 0.3271350870498729
Fold 3 IBS: 0.27726909564384733
Fold 4 IBS: 0.3099511962863054
Fold 5 IBS: 0.25674486767083105
[I 2024-04-13 21:48:08,514] Trial 47 finished with value: 0.29313736631738385 and parameters: {'subsample': 0.16128745332718092, 'dropout_rate': 0.51275387442083, 'n_estimators': 151, 'learning_rate': 0.07721407921704267}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.255671515665091
Fold 2 IBS: 0.2607199118856626
Fold 3 IBS: 0.25378623370487646
Fold 4 IBS: 0.2770115935466857
Fold 5 IBS: 0.20232979154953218
[I 2024-04-13 21:48:09,582] Trial 48 finished with value: 0.2499038092703696 and parameters: {'subsample': 0.23632628632985528, 'dropout_rate': 0.26663078692492104, 'n_estimators': 75, 'learning_rate': 0.09227376308051477}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24335983475281445
Fold 2 IBS: 0.2292142257044064
Fold 3 IBS: 0.2233550696775054
Fold 4 IBS: 0.23855014286789653
Fold 5 IBS: 0.2183221868335904
[I 2024-04-13 21:48:10,134] Trial 49 finished with value: 0.23056029196724265 and parameters: {'subsample': 0.4393566952292698, 'dropout_rate': 0.332262703432113, 'n_estimators': 19, 'learning_rate': 0.07427288587815248}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24304010409987237
Fold 2 IBS: 0.2339897684806897
Fold 3 IBS: 0.23369417490372746
Fold 4 IBS: 0.2473435295031823
Fold 5 IBS: 0.20691140117201237
[I 2024-04-13 21:48:10,813] Trial 50 finished with value: 0.23299579563189682 and parameters: {'subsample': 0.34829858647260875, 'dropout_rate': 0.4877094867656469, 'n_estimators': 36, 'learning_rate': 0.08487374018822923}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2470196649791225
Fold 2 IBS: 0.2320421226164359
Fold 3 IBS: 0.2285631902025967
Fold 4 IBS: 0.2417946862003668
Fold 5 IBS: 0.22873340973682177
[I 2024-04-13 21:48:11,198] Trial 51 finished with value: 0.23563061474706873 and parameters: {'subsample': 0.5477515719614294, 'dropout_rate': 0.331363005711254, 'n_estimators': 1, 'learning_rate': 0.07259520665127517}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24297576574424376
Fold 2 IBS: 0.22901412638659538
Fold 3 IBS: 0.22067726826077952
Fold 4 IBS: 0.23912264814494794
Fold 5 IBS: 0.21656877528115276
[I 2024-04-13 21:48:11,699] Trial 52 finished with value: 0.22967171676354387 and parameters: {'subsample': 0.1309562924329757, 'dropout_rate': 0.41469351097561474, 'n_estimators': 17, 'learning_rate': 0.0781180519693154}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2411435378292264
Fold 2 IBS: 0.23706401371037847
Fold 3 IBS: 0.22394613135209768
Fold 4 IBS: 0.24358820557006677
Fold 5 IBS: 0.20466927336393145
[I 2024-04-13 21:48:12,435] Trial 53 finished with value: 0.23008223236514014 and parameters: {'subsample': 0.12131014313904565, 'dropout_rate': 0.4193360809492056, 'n_estimators': 43, 'learning_rate': 0.0812543565997996}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.23964015952543422
Fold 2 IBS: 0.2394972582916394
Fold 3 IBS: 0.23229502638392646
Fold 4 IBS: 0.2522545964800224
Fold 5 IBS: 0.20088407863384902
[I 2024-04-13 21:48:13,331] Trial 54 finished with value: 0.2329142238629743 and parameters: {'subsample': 0.16563565554888304, 'dropout_rate': 0.5671338012766567, 'n_estimators': 45, 'learning_rate': 0.09034604449785032}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.38569785827814934
Fold 2 IBS: 0.3783965259537852
Fold 3 IBS: 0.29985055489699086
Fold 4 IBS: 0.38271433783085107
Fold 5 IBS: 0.3271427316695924
[I 2024-04-13 21:48:19,148] Trial 55 finished with value: 0.3547604017258738 and parameters: {'subsample': 0.22598996870953802, 'dropout_rate': 0.15105403923216587, 'n_estimators': 265, 'learning_rate': 0.094294012625532}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24265530196104837
Fold 2 IBS: 0.22969195631069156
Fold 3 IBS: 0.2227637481680039
Fold 4 IBS: 0.23773044016949282
Fold 5 IBS: 0.21885392749380464
[I 2024-04-13 21:48:19,686] Trial 56 finished with value: 0.23033907482060828 and parameters: {'subsample': 0.3107802670473057, 'dropout_rate': 0.3777125392670061, 'n_estimators': 17, 'learning_rate': 0.06933376515445122}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.41602279972773754
Fold 2 IBS: 0.37852588166442935

Fold 3 IBS: 0.2967856756039888
Fold 4 IBS: 0.38328944705560486
Fold 5 IBS: 0.3356135313416512
[I 2024-04-13 21:48:27,782] Trial 57 finished with value: 0.3620474670786823 and parameters: {'subsample': 0.1024539420046288, 'dropout_rate': 0.49346965615517374, 'n_estimators': 337, 'learning_rate': 0.08172067337182386}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.25416538597195026
Fold 2 IBS: 0.25706955072107596
Fold 3 IBS: 0.23764359423215053
Fold 4 IBS: 0.2677073268135179
Fold 5 IBS: 0.1957637741799054
[I 2024-04-13 21:48:29,507] Trial 58 finished with value: 0.24246992638372 and parameters: {'subsample': 0.16049662250408656, 'dropout_rate': 0.2210250116180224, 'n_estimators': 104, 'learning_rate': 0.06332357776860716}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24278576940412266
Fold 2 IBS: 0.23400445256009053
Fold 3 IBS: 0.2332137098103916
Fold 4 IBS: 0.24553977005200386
Fold 5 IBS: 0.20644973367875002
[I 2024-04-13 21:48:30,564] Trial 59 finished with value: 0.23239868710107175 and parameters: {'subsample': 0.2856593217259263, 'dropout_rate': 0.4370315801388946, 'n_estimators': 62, 'learning_rate': 0.05017360542645471}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2557474620622263
Fold 2 IBS: 0.26676271381217553
Fold 3 IBS: 0.26140173158677144
Fold 4 IBS: 0.2717077137957627
Fold 5 IBS: 0.20128741011390378
[I 2024-04-13 21:48:31,951] Trial 60 finished with value: 0.25138140627416794 and parameters: {'subsample': 0.2194084575391064, 'dropout_rate': 0.5481956683520264, 'n_estimators': 86, 'learning_rate': 0.07754719366079171}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2420011985933228
Fold 2 IBS: 0.24031994042954588
Fold 3 IBS: 0.23095603452701696
Fold 4 IBS: 0.2524755118134594
Fold 5 IBS: 0.20267232287906214
[I 2024-04-13 21:48:32,858] Trial 61 finished with value: 0.23368500164848144 and parameters: {'subsample': 0.12658202552594072, 'dropout_rate': 0.3799506603197498, 'n_estimators': 52, 'learning_rate': 0.0808976866625252}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24150446870137668
Fold 2 IBS: 0.23795311669825875
Fold 3 IBS: 0.22257534072479834
Fold 4 IBS: 0.24303704858751943
Fold 5 IBS: 0.20467221285465503
[I 2024-04-13 21:48:33,629] Trial 62 finished with value: 0.22994843751332167 and parameters: {'subsample': 0.12366722263410923, 'dropout_rate': 0.4134024474385516, 'n_estimators': 41, 'learning_rate': 0.08577013614236206}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24197300554888818
Fold 2 IBS: 0.22916924097339889
Fold 3 IBS: 0.22277760409098146
Fold 4 IBS: 0.23810726854353723
Fold 5 IBS: 0.21625316320364063
[I 2024-04-13 21:48:34,177] Trial 63 finished with value: 0.22965605647208925 and parameters: {'subsample': 0.17497023466179118, 'dropout_rate': 0.31445654276865265, 'n_estimators': 20, 'learning_rate': 0.0853684489970889}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24298903717918258
Fold 2 IBS: 0.22962188431143377
Fold 3 IBS: 0.22334506736159745
Fold 4 IBS: 0.2363740249805359
Fold 5 IBS: 0.21530719900140743
[I 2024-04-13 21:48:34,812] Trial 64 finished with value: 0.22952744256683144 and parameters: {'subsample': 0.18545600333452622, 'dropout_rate': 0.47186629248068557, 'n_estimators': 18, 'learning_rate': 0.0983235573918466}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2459198257449579
Fold 2 IBS: 0.23086591384410382
Fold 3 IBS: 0.22579175470330007
Fold 4 IBS: 0.23965901989295632
Fold 5 IBS: 0.226690091111804
[I 2024-04-13 21:48:35,242] Trial 65 finished with value: 0.23378532105942443 and parameters: {'subsample': 0.19782162873985523, 'dropout_rate': 0.4719166693768256, 'n_estimators': 4, 'learning_rate': 0.09727100383740692}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24104557227832138
Fold 2 IBS: 0.23107336824877422
Fold 3 IBS: 0.21958419406209376
Fold 4 IBS: 0.23923521763781627
Fold 5 IBS: 0.21629232087957928
[I 2024-04-13 21:48:35,797] Trial 66 finished with value: 0.22944613462131697 and parameters: {'subsample': 0.21665930041367717, 'dropout_rate': 0.516244847230179, 'n_estimators': 18, 'learning_rate': 0.09916858510177345}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.25533414741905774
Fold 2 IBS: 0.2671179469948825
Fold 3 IBS: 0.2599133450751458
Fold 4 IBS: 0.26940357996420217
Fold 5 IBS: 0.2017291011920124
[I 2024-04-13 21:48:36,987] Trial 67 finished with value: 0.2506996241290601 and parameters: {'subsample': 0.18282915165150299, 'dropout_rate': 0.5768161146412227, 'n_estimators': 74, 'learning_rate': 0.09490401293367616}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.4185368498112488
Fold 2 IBS: 0.3783537568518698
Fold 3 IBS: 0.31874415758391156
Fold 4 IBS: 0.4042384990370935
Fold 5 IBS: 0.33928643902151157
[I 2024-04-13 21:48:50,229] Trial 68 finished with value: 0.37183194046112705 and parameters: {'subsample': 0.249949822585511, 'dropout_rate': 0.511406283248025, 'n_estimators': 423, 'learning_rate': 0.08796272311287341}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.26792349156179573
Fold 2 IBS: 0.2561708312874702
Fold 3 IBS: 0.26110030057218425
Fold 4 IBS: 0.2475404179949169
Fold 5 IBS: 0.22868996527564453
[I 2024-04-13 21:48:51,369] Trial 69 finished with value: 0.2522850013384023 and parameters: {'subsample': 0.709634274734494, 'dropout_rate': 0.6632434004695467, 'n_estimators': 58, 'learning_rate': 0.09766967113482893}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24294912792326734
Fold 2 IBS: 0.23035074058012478
Fold 3 IBS: 0.22418550560316988
Fold 4 IBS: 0.24004838513965793
Fold 5 IBS: 0.21301336801048015
[I 2024-04-13 21:48:52,005] Trial 70 finished with value: 0.23010942545134 and parameters: {'subsample': 0.2165082095424452, 'dropout_rate': 0.3425373986452601, 'n_estimators': 21, 'learning_rate': 0.091236942944688}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24242846301652188
Fold 2 IBS: 0.2289800529381118
Fold 3 IBS: 0.22259488234319405
Fold 4 IBS: 0.2378959352649694
Fold 5 IBS: 0.2145510537750013
[I 2024-04-13 21:48:52,647] Trial 71 finished with value: 0.2292900774675597 and parameters: {'subsample': 0.1763557549629841, 'dropout_rate': 0.30455493023135205, 'n_estimators': 18, 'learning_rate': 0.0995874301128694}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2473666321053147
Fold 2 IBS: 0.23203741910158512
Fold 3 IBS: 0.2285214764028105
Fold 4 IBS: 0.24076912174282739
Fold 5 IBS: 0.22710119975704357
[I 2024-04-13 21:48:53,132] Trial 72 finished with value: 0.23515916982191626 and parameters: {'subsample': 0.177272687208617, 'dropout_rate': 0.2985717856439981, 'n_estimators': 1, 'learning_rate': 0.0998844103792359}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24705829998350026
Fold 2 IBS: 0.2422883354622418
Fold 3 IBS: 0.24962562704651414
Fold 4 IBS: 0.2537477442501165
Fold 5 IBS: 0.19939581481790858
[I 2024-04-13 21:48:54,231] Trial 73 finished with value: 0.2384231643120563 and parameters: {'subsample': 0.2744082168083983, 'dropout_rate': 0.29100831297117224, 'n_estimators': 50, 'learning_rate': 0.09429289658078817}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24318291977130777
Fold 2 IBS: 0.23125200590465525
Fold 3 IBS: 0.2214133402884659
Fold 4 IBS: 0.24431633451382842
Fold 5 IBS: 0.21060364086359468
[I 2024-04-13 21:48:54,935] Trial 74 finished with value: 0.23015364826837043 and parameters: {'subsample': 0.20489930003133902, 'dropout_rate': 0.22221181419435482, 'n_estimators': 29, 'learning_rate': 0.09024142257538133}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2497771485108315
Fold 2 IBS: 0.25146754475534777
Fold 3 IBS: 0.24567230126511647
Fold 4 IBS: 0.27407993368090905
Fold 5 IBS: 0.1954560127431118
[I 2024-04-13 21:48:56,119] Trial 75 finished with value: 0.24329058819106328 and parameters: {'subsample': 0.14850198140016627, 'dropout_rate': 0.5154917592158309, 'n_estimators': 70, 'learning_rate': 0.08575788873909043}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2443617715618355
Fold 2 IBS: 0.23041823531125408
Fold 3 IBS: 0.2235639110704624
Fold 4 IBS: 0.2369210597362608
Fold 5 IBS: 0.2212800472265086
[I 2024-04-13 21:48:56,964] Trial 76 finished with value: 0.23130900498126428 and parameters: {'subsample': 0.18190748713828728, 'dropout_rate': 0.449350356472916, 'n_estimators': 12, 'learning_rate': 0.08383283937402089}. Best is trial 43 with value: 0.22789865509331322.

Fold 1 IBS: 0.24614517653453177
Fold 2 IBS: 0.23173156309822698
Fold 3 IBS: 0.22767587336332618
Fold 4 IBS: 0.2363604585844503
Fold 5 IBS: 0.21236293144974608
[I 2024-04-13 21:48:57,687] Trial 77 finished with value: 0.2308552006060563 and parameters: {'subsample': 0.7888221964587577, 'dropout_rate': 0.17771784288698328, 'n_estimators': 28, 'learning_rate': 0.08836993630729562}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.3464250655392121
Fold 2 IBS: 0.37879980708527167
Fold 3 IBS: 0.30975364865243243
Fold 4 IBS: 0.38010482401937984
Fold 5 IBS: 0.3347877068439646
[I 2024-04-13 21:49:02,854] Trial 78 finished with value: 0.34997421042805216 and parameters: {'subsample': 0.2643775590636606, 'dropout_rate': 0.3702237451622687, 'n_estimators': 226, 'learning_rate': 0.09936039441108106}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24592889853108682
Fold 2 IBS: 0.2405319338011287
Fold 3 IBS: 0.2395407535809336
Fold 4 IBS: 0.25411025908718043
Fold 5 IBS: 0.2010524846741989
[I 2024-04-13 21:49:03,676] Trial 79 finished with value: 0.2362328659349057 and parameters: {'subsample': 0.21699405180810233, 'dropout_rate': 0.30977015938153585, 'n_estimators': 46, 'learning_rate': 0.09290293977195775}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.27579009085044176
Fold 2 IBS: 0.29470199810208186
Fold 3 IBS: 0.27982685425310977
Fold 4 IBS: 0.2819061498870967
Fold 5 IBS: 0.21766732435390404
[I 2024-04-13 21:49:05,049] Trial 80 finished with value: 0.2699784834893268 and parameters: {'subsample': 0.3010424672237505, 'dropout_rate': 0.5341760423064104, 'n_estimators': 92, 'learning_rate': 0.09579212446930241}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24465433367537656
Fold 2 IBS: 0.22957305991553767
Fold 3 IBS: 0.2203293205811695
Fold 4 IBS: 0.23758356905720815
Fold 5 IBS: 0.21789302803440397
[I 2024-04-13 21:49:05,654] Trial 81 finished with value: 0.23000666225273916 and parameters: {'subsample': 0.13747597591596195, 'dropout_rate': 0.39601139573881966, 'n_estimators': 15, 'learning_rate': 0.07066089346831898}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2444824350239825
Fold 2 IBS: 0.23088435453799921
Fold 3 IBS: 0.22495290372475477
Fold 4 IBS: 0.23665788064707582
Fold 5 IBS: 0.21713355540694662
[I 2024-04-13 21:49:06,240] Trial 82 finished with value: 0.23082222586815176 and parameters: {'subsample': 0.6042938600627025, 'dropout_rate': 0.4292233031664473, 'n_estimators': 23, 'learning_rate': 0.07575857912091358}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24373527114262614
Fold 2 IBS: 0.22993365202901414
Fold 3 IBS: 0.22359090587942387
Fold 4 IBS: 0.2409381781653894
Fold 5 IBS: 0.22077756204964116
[I 2024-04-13 21:49:06,692] Trial 83 finished with value: 0.2317951138532189 and parameters: {'subsample': 0.11572899363992925, 'dropout_rate': 0.2625892803711813, 'n_estimators': 12, 'learning_rate': 0.07814521471644965}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24206337855330798
Fold 2 IBS: 0.2434172355152666
Fold 3 IBS: 0.23324186017783008
Fold 4 IBS: 0.25670580282241773
Fold 5 IBS: 0.19661472817635564
[I 2024-04-13 21:49:07,680] Trial 84 finished with value: 0.2344086010490356 and parameters: {'subsample': 0.14886619960595618, 'dropout_rate': 0.4613263453779789, 'n_estimators': 61, 'learning_rate': 0.08010891269437226}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24038394003113536
Fold 2 IBS: 0.230825601651535
Fold 3 IBS: 0.22250675745977258
Fold 4 IBS: 0.24436382705958978
Fold 5 IBS: 0.2078988598765849
[I 2024-04-13 21:49:08,406] Trial 85 finished with value: 0.22919579721572353 and parameters: {'subsample': 0.1736345476617814, 'dropout_rate': 0.3512079240733256, 'n_estimators': 32, 'learning_rate': 0.08750079785112011}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2423226379042396
Fold 2 IBS: 0.23423204739096137
Fold 3 IBS: 0.23121694867485765
Fold 4 IBS: 0.24604298070783698
Fold 5 IBS: 0.20645374375121828
[I 2024-04-13 21:49:09,171] Trial 86 finished with value: 0.23205367168582275 and parameters: {'subsample': 0.18153607338390532, 'dropout_rate': 0.3418860375379552, 'n_estimators': 41, 'learning_rate': 0.08866548444334713}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.2455096002399582
Fold 2 IBS: 0.23473925977857243
Fold 3 IBS: 0.2315222244431154
Fold 4 IBS: 0.2470766764984333
Fold 5 IBS: 0.20686382190366207
[I 2024-04-13 21:49:09,815] Trial 87 finished with value: 0.23314231657274828 and parameters: {'subsample': 0.2374557017368046, 'dropout_rate': 0.32006734309810114, 'n_estimators': 34, 'learning_rate': 0.09664236756337174}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24671037025000495
Fold 2 IBS: 0.24357702391469133
Fold 3 IBS: 0.2475902227067812
Fold 4 IBS: 0.2628382100600492
Fold 5 IBS: 0.2009428152298118
[I 2024-04-13 21:49:10,779] Trial 88 finished with value: 0.2403317284322677 and parameters: {'subsample': 0.2021246804685069, 'dropout_rate': 0.35607746994466966, 'n_estimators': 54, 'learning_rate': 0.09308684767642393}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.32419079496805747
Fold 2 IBS: 0.3786190418698508
Fold 3 IBS: 0.3174781912801493
Fold 4 IBS: 0.342966276662568
Fold 5 IBS: 0.3379632923052972
[I 2024-04-13 21:49:16,838] Trial 89 finished with value: 0.34024351941718456 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.2808992567956313, 'n_estimators': 298, 'learning_rate': 0.08368896661244217}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.242675023749974
Fold 2 IBS: 0.2381102684216589
Fold 3 IBS: 0.22281044079246615
Fold 4 IBS: 0.25179654956843117
Fold 5 IBS: 0.20022795237776023
[I 2024-04-13 21:49:17,917] Trial 90 finished with value: 0.23112404698205807 and parameters: {'subsample': 0.16605431611983018, 'dropout_rate': 0.10184332440552968, 'n_estimators': 72, 'learning_rate': 0.05763730333913292}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24476349279547888
Fold 2 IBS: 0.22981985488303
Fold 3 IBS: 0.22258647351678226
Fold 4 IBS: 0.2383778755108706
Fold 5 IBS: 0.22101978433368596
[I 2024-04-13 21:49:18,404] Trial 91 finished with value: 0.23131349620796957 and parameters: {'subsample': 0.13760960102277206, 'dropout_rate': 0.39736730269755427, 'n_estimators': 10, 'learning_rate': 0.07516468005683535}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24045330987803817
Fold 2 IBS: 0.23318660065411242
Fold 3 IBS: 0.21677074347274095
Fold 4 IBS: 0.2446333312265917
Fold 5 IBS: 0.21004386300809869
[I 2024-04-13 21:49:19,025] Trial 92 finished with value: 0.22901756964791636 and parameters: {'subsample': 0.12016596440114338, 'dropout_rate': 0.48687766185181147, 'n_estimators': 27, 'learning_rate': 0.08723625100961188}. Best is trial 43 with value: 0.22789865509331322.
Fold 1 IBS: 0.24144616461246945
Fold 2 IBS: 0.22883461323300827
Fold 3 IBS: 0.21381114383919772
Fold 4 IBS: 0.24442939824404386
Fold 5 IBS: 0.20744710121948887
[I 2024-04-13 21:49:19,692] Trial 93 finished with value: 0.22719368422964165 and parameters: {'subsample': 0.10264100081255319, 'dropout_rate': 0.4919818027787326, 'n_estimators': 27, 'learning_rate': 0.08765048610038624}. Best is trial 93 with value: 0.22719368422964165.
Fold 1 IBS: 0.24046715010361103
Fold 2 IBS: 0.2324967724310923
Fold 3 IBS: 0.2141899092013505
Fold 4 IBS: 0.24512517581605772
Fold 5 IBS: 0.2033580219337908
[I 2024-04-13 21:49:20,408] Trial 94 finished with value: 0.22712740589718047 and parameters: {'subsample': 0.10171168776080142, 'dropout_rate': 0.48871873206907923, 'n_estimators': 35, 'learning_rate': 0.0877888965872639}. Best is trial 94 with value: 0.22712740589718047.
Fold 1 IBS: 0.24046931616893527
Fold 2 IBS: 0.23245336760492621
Fold 3 IBS: 0.21418106952273938
Fold 4 IBS: 0.24506946619701647
Fold 5 IBS: 0.20253644147012068
[I 2024-04-13 21:49:21,121] Trial 95 finished with value: 0.22694193219274764 and parameters: {'subsample': 0.10055436608530686, 'dropout_rate': 0.4952232489349569, 'n_estimators': 35, 'learning_rate': 0.08744198973781114}. Best is trial 95 with value: 0.22694193219274764.
Fold 1 IBS: 0.24056136508559312

Fold 2 IBS: 0.23283374383732752
Fold 3 IBS: 0.214629733795403
Fold 4 IBS: 0.24479707089702957
Fold 5 IBS: 0.20252984019637682
[I 2024-04-13 21:49:21,834] Trial 96 finished with value: 0.22707035076234602 and parameters: {'subsample': 0.10431216939439927, 'dropout_rate': 0.4866966976769669, 'n_estimators': 36, 'learning_rate': 0.08781069522287915}. Best is trial 95 with value: 0.22694193219274764.
Fold 1 IBS: 0.24226623933078084
Fold 2 IBS: 0.23689506425405096
Fold 3 IBS: 0.23668323797670957
Fold 4 IBS: 0.2663621823478399
Fold 5 IBS: 0.19962959656722443
[I 2024-04-13 21:49:22,671] Trial 97 finished with value: 0.2363672640953211 and parameters: {'subsample': 0.10863299078416362, 'dropout_rate': 0.5772422505268303, 'n_estimators': 50, 'learning_rate': 0.08730182830746808}. Best is trial 95 with value: 0.22694193219274764.
Fold 1 IBS: 0.2668207214584027
Fold 2 IBS: 0.29605961251296825
Fold 3 IBS: 0.24890800068026245
Fold 4 IBS: 0.2820742952494582
Fold 5 IBS: 0.2013620297024855
[I 2024-04-13 21:49:24,275] Trial 98 finished with value: 0.2590449319207154 and parameters: {'subsample': 0.10609243369203872, 'dropout_rate': 0.4904314032552653, 'n_estimators': 108, 'learning_rate': 0.08991417306147119}. Best is trial 95 with value: 0.22694193219274764.
Fold 1 IBS: 0.24135574825440095
Fold 2 IBS: 0.23111309773996533
Fold 3 IBS: 0.2141759606462713
Fold 4 IBS: 0.24287820508011682
Fold 5 IBS: 0.20605848085930994
[I 2024-04-13 21:49:24,921] Trial 99 finished with value: 0.2271162985160129 and parameters: {'subsample': 0.1034933590438787, 'dropout_rate': 0.45124125345927873, 'n_estimators': 32, 'learning_rate': 0.08367351152431032}. Best is trial 95 with value: 0.22694193219274764.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.22694193219274764], datetime_start=datetime.datetime(2024, 4, 13, 21, 49, 20, 440824), datetime_complete=datetime.datetime(2024, 4, 13, 21, 49, 21, 120494), params={'subsample': 0.10055436608530686, 'dropout_rate': 0.4952232489349569, 'n_estimators': 35, 'learning_rate': 0.08744198973781114}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=95, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10055436608530686, 'dropout_rate': 0.4952232489349569, 'n_estimators': 35, 'learning_rate': 0.08744198973781114}


* Best Score for IBS:
 0.22694193219274764

In [79]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [80]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.631
train_ibs:  0.227

#### Test

In [81]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [82]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3917773398227318,
                                              learning_rate=0.05621431261796065,
                                              n_estimators=1, random_state=123,
                                              subsample=0.14187696914743586)

C-index score: 0.51

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.4952232489349569,
                                              learning_rate=0.08744198973781114,
                                              n_estimators=35, random_state=123,
                                              subsample=0.10055436608530686)

IBS: 0.233

In [83]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [84]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.790   1.0
ExtraSurvivalTrees               0.748   2.0
GradientBoosting                 0.648   3.0
CoxElastic                       0.639   4.0
CoxPH                            0.638   5.0
CoxLasso                         0.637   6.0
ComponentwiseGradientBoosting    0.631   7.0
CoxRidge                         0.592   8.0

In [85]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.218   1.5
ExtraSurvivalTrees             0.218   1.5
CoxElastic                     0.224   3.0
CoxPH                          0.227   5.0
CoxLasso                       0.227   5.0
ComponentwiseGradientBoosting  0.227   5.0
GradientBoosting               0.229   7.0
CoxRidge                       0.236   8.0

In [86]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.639   1.0
Randomsurvivalforest             0.603   2.0
ExtraSurvivalTrees               0.585   3.0
CoxLasso                         0.567   4.5
CoxElastic                       0.567   4.5
CoxPH                            0.566   6.0
CoxRidge                         0.533   7.0
ComponentwiseGradientBoosting    0.510   8.0

In [87]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.213   1.0
Randomsurvivalforest           0.215   2.0
GradientBoosting               0.221   3.0
CoxRidge                       0.229   4.5
CoxElastic                     0.229   4.5
ComponentwiseGradientBoosting  0.233   6.0
CoxLasso                       0.259   7.0
CoxPH                          0.262   8.0

In [89]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/dfs/yeojohnson/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_dfs_yeojohnson_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [90]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-13