In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import PowerTransformer

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [7]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.08
LBP_003_PET                                                      0.00 0.99      0.01
LBP_012_CT                                                       0.01 0.91      0.13
LBP_012_PET                                                      0.00 0.98      0.03
LBP_021_CT                                                       0.01 0.94      0.09
LBP_021_PET                                                      0.02 0.90      0.16
LBP_030_CT                                                       0.00 0.97      0.04
LBP_030_PET                                                      0.00 0.99      0.01
LBP_102_CT                                                       0.00 0.96      0.07
LBP_102_PET                                                      0.02 0.88      0.19
LBP_111_CT                                                       0.01 0.93      0.10
LBP_111_PET                                                      0.07 0.79      0.33
LBP_120_CT                                                       0.01 0.91      0.14
LBP_120_PET                                                      0.00 0.96      0.07
LBP_201_CT                                                       0.00 0.97      0.04
LBP_201_PET                                                      0.00 0.95      0.08
LBP_210_CT                                                       0.00 1.00      0.00
LBP_210_PET                                                      0.00 0.96      0.06
LBP_300_CT                                                       0.00 0.98      0.03
LBP_300_PET                                                      0.01 0.94      0.09
first_order_10Percentile_CT                                      0.01 0.94      0.09
first_order_10Percentile_PET                                     0.00 1.00      0.01
first_order_90Percentile_CT                                      0.00 0.98      0.03
first_order_90Percentile_PET                                     0.00 0.99      0.01
first_order_Energy_CT                                            0.00 1.00      0.00
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 0.98      0.03
first_order_Entropy_CT_c16                                       0.00 0.98      0.03
first_order_Entropy_PET_b2                                       0.00 0.99      0.01
first_order_Entropy_PET_c04                                      0.00 0.96      0.06
first_order_InterquartileRange_CT                                0.00 0.94      0.08
first_order_InterquartileRange_PET                               0.00 1.00      0.00
first_order_Kurtosis_CT                                          0.00 0.99      0.02
first_order_Kurtosis_PET                                         0.01 0.93      0.10
first_order_Maximum_CT                                           0.01 0.93      0.11
first_order_Maximum_PET                                          0.00 1.00      0.01
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.01
first_order_MeanAbsoluteDeviation_PET                            0.00 1.00      0.00
first_order_Mean_CT                                              0.00 0.99      0.01
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 1.00      0.01
first_order_Median_PET                                           0.00 1.00      0.00
first_order_Minimum_CT                                           0.00 0.98      0.03
first_order_Minimum_PET                                          0.02 0.89      0.17
first_order_Range_CT                                             0.00 0.96      0.06
first_order_Range_PET                                            0.00 0.99      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.95      0.08
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 0.99      0.02
first_order_RootMeanSquared_CT                                   0.00 0.99      0.01
first_order_RootMeanSquared_PET                                  0.00 1.00      0.00
first_order_Skewness_CT                                          0.05 0.83      0.27
first_order_Skewness_PET                                         0.00 0.95      0.07
first_order_TotalEnergy_CT                                       0.00 1.00      0.00
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.95      0.07
first_order_Uniformity_CT_c16                                    0.00 0.98      0.03
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 0.99      0.02
first_order_Variance_CT                                          0.00 0.99      0.02
first_order_Variance_PET                                         0.00 0.99      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.98      0.02
glcm_ClusterProminence_d_1_CT_b20                                0.00 0.98      0.02
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.95      0.07
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.98      0.03
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.95      0.07
glcm_ClusterShade_d_1_CT_c16                                     0.01 0.93      0.10
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.95      0.08
glcm_ClusterShade_d_1_PET_c04                                    0.01 0.94      0.10
glcm_ClusterTendency_d_1_CT_b20                                  0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.98      0.03
glcm_ClusterTendency_d_1_PET_b2                                  0.00 1.00      0.00
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.98      0.03
glcm_Contrast_d_1_CT_b20                                         0.00 0.97      0.04
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 0.99      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.96      0.06
glcm_Correlation_d_1_CT_c16                                      0.01 0.92      0.13
glcm_Correlation_d_1_PET_b2                                      0.00 0.99      0.02
glcm_Correlation_d_1_PET_c04                                     0.00 0.95      0.07
glcm_DifferenceAverage_d_1_CT_b20                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.98      0.03
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.99      0.02
glcm_Id_d_1_CT_b20                                               0.00 1.00      0.00
glcm_Id_d_1_CT_c16                                               0.00 0.98      0.02
glcm_Id_d_1_PET_b2                                               0.00 0.99      0.02
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_c16                                              0.00 0.98      0.03
glcm_Idm_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Idmn_d_1_CT_c16                                             0.00 0.98      0.03
glcm_Idmn_d_1_PET_b2                                             0.00 0.96      0.05
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idn_d_1_CT_c16                                              0.00 0.98      0.03
glcm_Idn_d_1_PET_b2                                              0.00 0.98      0.03
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_b20                                             0.01 0.93      0.10
glcm_Imc1_d_1_CT_c16                                             0.00 1.00      0.01
glcm_Imc1_d_1_PET_b2                                             0.00 0.95      0.08
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Imc2_d_1_CT_b20                                             0.01 0.92      0.12
glcm_Imc2_d_1_CT_c16                                             0.01 0.94      0.10
glcm_Imc2_d_1_PET_b2                                             0.00 0.98      0.03
glcm_Imc2_d_1_PET_c04                                            0.00 0.97      0.04
glcm_InverseVariance_d_1_CT_b20                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_PET_b2                                  0.00 0.97      0.04
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.00
glcm_JointAverage_d_1_CT_b20                                     0.00 0.98      0.03
glcm_JointAverage_d_1_CT_c16                                     0.00 1.00      0.00
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 0.99      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.99      0.02
glcm_JointEnergy_d_1_CT_c16                                      0.00 0.99      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.00 0.99      0.01
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_CT_b20                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.98      0.03
glcm_MCC_d_1_CT_b20                                              0.02 0.89      0.16
glcm_MCC_d_1_CT_c16                                              0.00 0.96      0.06
glcm_MCC_d_1_PET_b2                                              0.00 0.97      0.05
glcm_MCC_d_1_PET_c04                                             0.00 0.97      0.05
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.97      0.05
glcm_MaximumProbability_d_1_CT_c16                               0.00 0.98      0.03
glcm_MaximumProbability_d_1_PET_b2                               0.01 0.91      0.14
glcm_MaximumProbability_d_1_PET_c04                              0.01 0.92      0.12
glcm_SumAverage_d_1_CT_b20                                       0.00 0.98      0.03
glcm_SumAverage_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.99      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.97      0.05
glcm_SumSquares_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumSquares_d_1_CT_c16                                       0.00 0.98      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumSquares_d_1_PET_c04                                      0.00 0.98      0.03
gldm_DependenceEntropy_d_1_CT_b20                                0.01 0.94      0.09
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.98      0.02
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.98      0.04
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.00
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.98      0.02
gldm_DependenceVariance_d_1_CT_c16                               0.00 0.96      0.06
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.97      0.05
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.95      0.07
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.97      0.04
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.95      0.08
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.99      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.03
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.96      0.05
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.01 0.94      0.09
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.96      0.06
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.98      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.97      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.01 0.94      0.09
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.95      0.08
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.96      0.06
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.96      0.05
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.01 0.92      0.13
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.02 0.90      0.15
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.02 0.89      0.17
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.97      0.04
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.96      0.06
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.95      0.07
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.98      0.04
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.99      0.01
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.97      0.04
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.01
glrlm_GrayLevelVariance_PET_c04                                  0.00 0.97      0.05
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.00 1.00      0.00
glrlm_HighGrayLevelRunEmphasis_CT_c16                            0.00 1.00      0.01
glrlm_HighGrayLevelRunEmphasis_PET_b2                            0.00 0.99      0.02
glrlm_HighGrayLevelRunEmphasis_PET_c04                           0.00 0.96      0.06
glrlm_LongRunEmphasis_CT_b20                                     0.00 1.00      0.00
glrlm_LongRunEmphasis_CT_c16                                     0.00 0.96      0.06

In [8]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [9]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic      p  -log2(p)
LBP_003_CT                                                       0.20   0.65      0.62
LBP_003_PET                                                      0.43   0.51      0.96
LBP_012_CT                                                       0.19   0.66      0.59
LBP_012_PET                                                      0.18   0.67      0.57
LBP_021_CT                                                       0.94   0.33      1.59
LBP_021_PET                                                      0.01   0.93      0.10
LBP_030_CT                                                       0.00   0.94      0.08
LBP_030_PET                                                      0.03   0.86      0.21
LBP_102_CT                                                       0.05   0.83      0.27
LBP_102_PET                                                      0.09   0.77      0.38
LBP_111_CT                                                       0.14   0.71      0.49
LBP_111_PET                                                      0.38   0.54      0.89
LBP_120_CT                                                       0.27   0.61      0.72
LBP_120_PET                                                      0.09   0.76      0.40
LBP_201_CT                                                       0.30   0.58      0.78
LBP_201_PET                                                      0.58   0.45      1.16
LBP_210_CT                                                       0.69   0.41      1.30
LBP_210_PET                                                      0.00   0.97      0.04
LBP_300_CT                                                       0.20   0.66      0.60
LBP_300_PET                                                      0.00   0.94      0.08
first_order_10Percentile_CT                                      0.00   0.95      0.08
first_order_10Percentile_PET                                     0.08   0.77      0.37
first_order_90Percentile_CT                                      2.85   0.09      3.46
first_order_90Percentile_PET                                     0.00   0.95      0.07
first_order_Energy_CT                                            0.01   0.93      0.11
first_order_Energy_PET                                           0.08   0.77      0.37
first_order_Entropy_CT_b20                                       0.00   0.99      0.01
first_order_Entropy_CT_c16                                       0.08   0.78      0.37
first_order_Entropy_PET_b2                                       0.00   0.99      0.01
first_order_Entropy_PET_c04                                      0.01   0.93      0.11
first_order_InterquartileRange_CT                                0.79   0.37      1.42
first_order_InterquartileRange_PET                               0.00   0.97      0.04
first_order_Kurtosis_CT                                          0.30   0.58      0.77
first_order_Kurtosis_PET                                         0.04   0.84      0.26
first_order_Maximum_CT                                           0.13   0.72      0.48
first_order_Maximum_PET                                          0.00   0.95      0.08
first_order_MeanAbsoluteDeviation_CT                             0.06   0.81      0.30
first_order_MeanAbsoluteDeviation_PET                            0.00   0.95      0.07
first_order_Mean_CT                                              0.01   0.93      0.10
first_order_Mean_PET                                             0.01   0.94      0.09
first_order_Median_CT                                            0.19   0.66      0.59
first_order_Median_PET                                           0.01   0.92      0.12
first_order_Minimum_CT                                           0.06   0.81      0.31
first_order_Minimum_PET                                          0.64   0.42      1.24
first_order_Range_CT                                             0.16   0.69      0.55
first_order_Range_PET                                            0.00   0.98      0.03
first_order_RobustMeanAbsoluteDeviation_CT                       0.11   0.74      0.43
first_order_RobustMeanAbsoluteDeviation_PET                      0.00   0.96      0.07
first_order_RootMeanSquared_CT                                   0.02   0.89      0.17
first_order_RootMeanSquared_PET                                  0.00   0.97      0.05
first_order_Skewness_CT                                          0.10   0.76      0.40
first_order_Skewness_PET                                         0.00   0.95      0.08
first_order_TotalEnergy_CT                                       0.01   0.93      0.11
first_order_TotalEnergy_PET                                      0.08   0.77      0.37
first_order_Uniformity_CT_b20                                    0.01   0.93      0.10
first_order_Uniformity_CT_c16                                    0.03   0.85      0.23
first_order_Uniformity_PET_b2                                    0.13   0.72      0.47
first_order_Uniformity_PET_c04                                   0.07   0.79      0.34
first_order_Variance_CT                                          0.01   0.94      0.09
first_order_Variance_PET                                         0.00   0.96      0.06
glcm_Autocorrelation_d_1_CT_b20                                  0.13   0.72      0.48
glcm_Autocorrelation_d_1_CT_c16                                  0.00   0.99      0.02
glcm_Autocorrelation_d_1_PET_b2                                  0.03   0.86      0.22
glcm_Autocorrelation_d_1_PET_c04                                 0.01   0.93      0.10
glcm_ClusterProminence_d_1_CT_b20                                0.03   0.86      0.22
glcm_ClusterProminence_d_1_CT_c16                                0.00   0.98      0.02
glcm_ClusterProminence_d_1_PET_b2                                0.15   0.69      0.53
glcm_ClusterProminence_d_1_PET_c04                               0.21   0.65      0.62
glcm_ClusterShade_d_1_CT_b20                                     1.58   0.21      2.26
glcm_ClusterShade_d_1_CT_c16                                     0.00   0.96      0.06
glcm_ClusterShade_d_1_PET_b2                                     0.35   0.55      0.85
glcm_ClusterShade_d_1_PET_c04                                    0.17   0.68      0.55
glcm_ClusterTendency_d_1_CT_b20                                  0.01   0.93      0.10
glcm_ClusterTendency_d_1_CT_c16                                  0.03   0.86      0.21
glcm_ClusterTendency_d_1_PET_b2                                  0.01   0.94      0.09
glcm_ClusterTendency_d_1_PET_c04                                 0.09   0.76      0.39
glcm_Contrast_d_1_CT_b20                                         0.02   0.89      0.17
glcm_Contrast_d_1_CT_c16                                         0.03   0.86      0.22
glcm_Contrast_d_1_PET_b2                                         0.01   0.92      0.13
glcm_Contrast_d_1_PET_c04                                        0.01   0.93      0.10
glcm_Correlation_d_1_CT_b20                                      0.61   0.43      1.20
glcm_Correlation_d_1_CT_c16                                      0.67   0.41      1.27
glcm_Correlation_d_1_PET_b2                                      0.03   0.85      0.23
glcm_Correlation_d_1_PET_c04                                     0.00   0.96      0.06
glcm_DifferenceAverage_d_1_CT_b20                                0.00   0.99      0.01
glcm_DifferenceAverage_d_1_CT_c16                                0.00   0.98      0.04
glcm_DifferenceAverage_d_1_PET_b2                                0.00   0.96      0.07
glcm_DifferenceAverage_d_1_PET_c04                               0.00   0.96      0.06
glcm_DifferenceEntropy_d_1_CT_b20                                0.00   0.96      0.06
glcm_DifferenceEntropy_d_1_CT_c16                                0.01   0.93      0.11
glcm_DifferenceEntropy_d_1_PET_b2                                0.03   0.85      0.23
glcm_DifferenceEntropy_d_1_PET_c04                               0.18   0.67      0.57
glcm_DifferenceVariance_d_1_CT_b20                               0.04   0.84      0.25
glcm_DifferenceVariance_d_1_CT_c16                               0.05   0.82      0.29
glcm_DifferenceVariance_d_1_PET_b2                               0.08   0.78      0.35
glcm_DifferenceVariance_d_1_PET_c04                              0.12   0.73      0.45
glcm_Id_d_1_CT_b20                                               0.00   0.95      0.07
glcm_Id_d_1_CT_c16                                               0.00   0.98      0.03
glcm_Id_d_1_PET_b2                                               0.02   0.90      0.15
glcm_Id_d_1_PET_c04                                              0.01   0.90      0.15
glcm_Idm_d_1_CT_b20                                              0.00   0.95      0.07
glcm_Idm_d_1_CT_c16                                              0.00   0.99      0.01
glcm_Idm_d_1_PET_b2                                              0.01   0.92      0.12
glcm_Idm_d_1_PET_c04                                             0.01   0.92      0.11
glcm_Idmn_d_1_CT_b20                                             0.03   0.87      0.20
glcm_Idmn_d_1_CT_c16                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_b2                                             0.08   0.78      0.35
glcm_Idmn_d_1_PET_c04                                            0.01   0.94      0.09
glcm_Idn_d_1_CT_b20                                              0.02   0.89      0.16
glcm_Idn_d_1_CT_c16                                              0.00   0.99      0.01
glcm_Idn_d_1_PET_b2                                              0.17   0.68      0.56
glcm_Idn_d_1_PET_c04                                             0.01   0.94      0.09
glcm_Imc1_d_1_CT_b20                                             0.87   0.35      1.51
glcm_Imc1_d_1_CT_c16                                             0.02   0.88      0.18
glcm_Imc1_d_1_PET_b2                                             0.06   0.80      0.32
glcm_Imc1_d_1_PET_c04                                            0.08   0.78      0.36
glcm_Imc2_d_1_CT_b20                                             0.06   0.81      0.30
glcm_Imc2_d_1_CT_c16                                             0.60   0.44      1.19
glcm_Imc2_d_1_PET_b2                                             0.09   0.76      0.39
glcm_Imc2_d_1_PET_c04                                            0.02   0.88      0.19
glcm_InverseVariance_d_1_CT_b20                                  0.13   0.72      0.47
glcm_InverseVariance_d_1_CT_c16                                  0.05   0.83      0.27
glcm_InverseVariance_d_1_PET_b2                                  0.07   0.80      0.33
glcm_InverseVariance_d_1_PET_c04                                 0.07   0.79      0.34
glcm_JointAverage_d_1_CT_b20                                     0.08   0.78      0.36
glcm_JointAverage_d_1_CT_c16                                     0.02   0.89      0.16
glcm_JointAverage_d_1_PET_b2                                     0.01   0.90      0.15
glcm_JointAverage_d_1_PET_c04                                    0.00   0.95      0.08
glcm_JointEnergy_d_1_CT_b20                                      0.03   0.87      0.20
glcm_JointEnergy_d_1_CT_c16                                      0.03   0.87      0.21
glcm_JointEnergy_d_1_PET_b2                                      0.18   0.67      0.57
glcm_JointEnergy_d_1_PET_c04                                     0.01   0.92      0.12
glcm_JointEntropy_d_1_CT_b20                                     0.00   0.95      0.07
glcm_JointEntropy_d_1_CT_c16                                     0.07   0.78      0.35
glcm_JointEntropy_d_1_PET_b2                                     0.00   0.98      0.02
glcm_JointEntropy_d_1_PET_c04                                    0.00   0.97      0.04
glcm_MCC_d_1_CT_b20                                              0.00   0.99      0.02
glcm_MCC_d_1_CT_c16                                              0.10   0.75      0.41
glcm_MCC_d_1_PET_b2                                              0.01   0.93      0.10
glcm_MCC_d_1_PET_c04                                             0.02   0.88      0.19
glcm_MaximumProbability_d_1_CT_b20                               0.02   0.89      0.17
glcm_MaximumProbability_d_1_CT_c16                               0.10   0.75      0.42
glcm_MaximumProbability_d_1_PET_b2                               0.14   0.71      0.49
glcm_MaximumProbability_d_1_PET_c04                              0.03   0.86      0.22
glcm_SumAverage_d_1_CT_b20                                       0.08   0.78      0.36
glcm_SumAverage_d_1_CT_c16                                       0.02   0.89      0.16
glcm_SumAverage_d_1_PET_b2                                       0.01   0.90      0.15
glcm_SumAverage_d_1_PET_c04                                      0.00   0.95      0.08
glcm_SumEntropy_d_1_CT_b20                                       0.00   0.95      0.08
glcm_SumEntropy_d_1_CT_c16                                       0.08   0.78      0.36
glcm_SumEntropy_d_1_PET_b2                                       0.00   0.99      0.02
glcm_SumEntropy_d_1_PET_c04                                      0.00   0.96      0.06
glcm_SumSquares_d_1_CT_b20                                       0.00   0.95      0.08
glcm_SumSquares_d_1_CT_c16                                       0.02   0.89      0.17
glcm_SumSquares_d_1_PET_b2                                       0.01   0.94      0.09
glcm_SumSquares_d_1_PET_c04                                      0.09   0.77      0.39
gldm_DependenceEntropy_d_1_CT_b20                                0.14   0.71      0.49
gldm_DependenceEntropy_d_1_CT_c16                                0.18   0.67      0.58
gldm_DependenceEntropy_d_1_PET_b2                                0.03   0.87      0.19
gldm_DependenceEntropy_d_1_PET_c04                               0.04   0.84      0.26
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.12   0.73      0.45
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.08   0.78      0.37
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.38   0.54      0.90
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.18   0.67      0.57
gldm_DependenceNonUniformity_d_1_CT_b20                          0.03   0.87      0.20
gldm_DependenceNonUniformity_d_1_CT_c16                          2.71   0.10      3.33
gldm_DependenceNonUniformity_d_1_PET_b2                          0.04   0.85      0.23
gldm_DependenceNonUniformity_d_1_PET_c04                         0.15   0.70      0.51
gldm_DependenceVariance_d_1_CT_b20                               0.31   0.57      0.80
gldm_DependenceVariance_d_1_CT_c16                               0.21   0.65      0.63
gldm_DependenceVariance_d_1_PET_b2                               0.80   0.37      1.43
gldm_DependenceVariance_d_1_PET_c04                              1.04   0.31      1.70
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.42   0.52      0.96
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.33   0.57      0.82
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.27   0.61      0.72
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00   0.97      0.04
gldm_GrayLevelVariance_d_1_CT_b20                                0.01   0.94      0.09
gldm_GrayLevelVariance_d_1_CT_c16                                0.00   0.97      0.05
gldm_GrayLevelVariance_d_1_PET_b2                                0.00   0.96      0.06
gldm_GrayLevelVariance_d_1_PET_c04                               0.05   0.82      0.28
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.14   0.70      0.51
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00   0.99      0.02
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.03   0.86      0.22
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.02   0.89      0.16
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.02   0.90      0.16
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.04   0.84      0.25
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.10   0.75      0.41
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.02   0.88      0.19
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.77   0.38      1.40
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.04   0.84      0.25
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.13   0.72      0.48
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00   0.99      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.05   0.82      0.29
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.04   0.85      0.24
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.12   0.73      0.45
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.56   0.45      1.14
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.06   0.81      0.30
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00   1.00      0.00
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.01   0.94      0.09
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.50   0.48      1.07
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.02   0.88      0.19
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.10   0.75      0.41
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.05   0.83      0.27
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.02   0.89      0.17
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.39   0.53      0.91
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.05   0.82      0.29
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.09   0.77      0.38
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01   0.93      0.10
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00   0.95      0.07
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.18   0.67      0.57
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.14   0.70      0.51
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00   0.98      0.03
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.02   0.89      0.17
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.59   0.44      1.18
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.02   0.89      0.16
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.03   0.86      0.22
glrlm_GrayLevelNonUniformity_CT_b20                              0.02   0.90      0.15
glrlm_GrayLevelNonUniformity_CT_c16                              1.03   0.31      1.68
glrlm_GrayLevelNonUniformity_PET_b2                              0.06   0.80      0.31
glrlm_GrayLevelNonUniformity_PET_c04                             0.01   0.94      0.09
glrlm_GrayLevelVariance_CT_b20                                   0.06   0.80      0.32
glrlm_GrayLevelVariance_CT_c16                                   0.04   0.85      0.24
glrlm_GrayLevelVariance_PET_b2                                   0.01   0.91      0.13
glrlm_GrayLevelVariance_PET_c04                                  0.04   0.85      0.24
glrlm_HighGrayLevelRunEmphasis_CT_b20                            0.07   0.79      0.34

In [10]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['glszm_GrayLevelNonUniformity_PET_c04',
       'glszm_LargeAreaEmphasis_CT_c16',
       'glszm_LargeAreaLowGrayLevelEmphasis_CT_c16',
       'glszm_ZoneVariance_CT_c16', 'ngtdm_Busyness_d_1_PET_b2'],
      dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [11]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [12]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [13]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [14]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [15]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [16]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [17]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [18]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [19]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [20]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [21]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

In [22]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data[vif_data['VIF'] > 100000]

                           feature           VIF
0                 shape_Elongation  2.096355e+11
1                   shape_Flatness  3.609232e+11
2            shape_LeastAxisLength  2.691126e+12
3            shape_MajorAxisLength  7.524811e+12
4    shape_Maximum2DDiameterColumn  2.124339e+13
..                             ...           ...
369                    LBP_111_PET  5.922282e+11
370                    LBP_120_PET  3.305758e+11
371                    LBP_201_PET  1.508996e+12
372                    LBP_210_PET  1.369708e+12
373                    LBP_300_PET  7.392136e+09

[374 rows x 2 columns]

# Yeo-Johnson Transformation

In [23]:
original_X = X.copy()

In [24]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

# Standardize non-categorical and then concat with the categorical
pt = PowerTransformer(method='yeo-johnson')
X_std = pt.fit_transform(X)
X_std = pd.DataFrame(X_std, columns=X_columns, index=X_index)

In [25]:
# Standardize the numeric part 
X_MAASTRO_column = X_MAASTRO.columns
X_MAASTRO_index = X_MAASTRO.index

X_MAASTRO_std = pt.transform(X_MAASTRO)

# Change the standardized part into a dataframe 
X_MAASTRO_std = pd.DataFrame(X_MAASTRO_std, columns=X_MAASTRO_column, index=X_MAASTRO_index)

In [26]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [27]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:59:58,280] A new study created in memory with name: no-name-9356ed6b-3a51-4dc3-b783-0b2438c9cd00

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-15 14:00:00,321] Trial 0 failed with parameters: {} because of the following error: LinAlgError('Matrix is singular.').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_68893/3148227347.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 449, in fit
    delta = solve(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 220, in solve
    _solve_check(n, info)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[W 2024-04-15 14:00:00,328] Trial 0 failed with value None.

LinAlgError: Matrix is singular.

In [28]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [29]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [30]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [31]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

LinAlgError: Matrix is singular.

In [32]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [33]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [34]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:02:31,947] A new study created in memory with name: no-name-327504a9-fba3-466b-acc5-3cc6e5183d04

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6653992395437263

[I 2024-04-15 14:02:39,309] A new study created in memory with name: no-name-f7a3d3a2-0edb-4cc0-aa25-1c86b396262c

Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 14:02:39,298] Trial 0 finished with value: 0.635065183651369 and parameters: {}. Best is trial 0 with value: 0.635065183651369.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.635065183651369], datetime_start=datetime.datetime(2024, 4, 15, 14, 2, 31, 983955), datetime_complete=datetime.datetime(2024, 4, 15, 14, 2, 39, 297405), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.635065183651369

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709663544278
Fold 2 IBS: 0.23203988184644345
Fold 3 IBS: 0.22898186778522736
Fold 4 IBS: 0.24197476559442144
Fold 5 IBS: 0.22939558964342896
[I 2024-04-15 14:02:47,032] Trial 0 finished with value: 0.23592784030099279 and parameters: {}. Best is trial 0 with value: 0.23592784030099279.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784030099279], datetime_start=datetime.datetime(2024, 4, 15, 14, 2, 39, 348088), datetime_complete=datetime.datetime(2024, 4, 15, 14, 2, 47, 31931), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784030099279

In [35]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [36]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.635
train_ibs:  0.236

#### Test

In [37]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [38]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.53

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [39]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [40]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:02:47,272] A new study created in memory with name: no-name-b704c195-c903-4a42-a43c-03fc841c099c

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.37446808510638296
Fold 4 C-index: 0.6387832699619772

[I 2024-04-15 14:02:57,922] A new study created in memory with name: no-name-6a4700b5-4577-4498-bae0-debcf5571b72

Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 14:02:57,909] Trial 0 finished with value: 0.5624523575406387 and parameters: {}. Best is trial 0 with value: 0.5624523575406387.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5624523575406387], datetime_start=datetime.datetime(2024, 4, 15, 14, 2, 47, 307345), datetime_complete=datetime.datetime(2024, 4, 15, 14, 2, 57, 909033), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5624523575406387

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.38515817356172605
Fold 2 IBS: 0.31542055044032496
Fold 3 IBS: 0.46463727872638066
Fold 4 IBS: 0.27876072700041465
Fold 5 IBS: 0.2803374283965891
[I 2024-04-15 14:03:09,129] Trial 0 finished with value: 0.34486283162508713 and parameters: {}. Best is trial 0 with value: 0.34486283162508713.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.34486283162508713], datetime_start=datetime.datetime(2024, 4, 15, 14, 2, 57, 954561), datetime_complete=datetime.datetime(2024, 4, 15, 14, 3, 9, 128136), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.34486283162508713

In [41]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [42]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.562
train_ibs:  0.345

#### Test

In [43]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [44]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.477

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.464

In [45]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [46]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:03:11,098] A new study created in memory with name: no-name-882406fa-a761-41fe-950f-1a87d291847d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.39148936170212767
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 14:03:20,751] Trial 0 finished with value: 0.5566073306242119 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.5566073306242119.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.46382978723404256
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:03:30,879] Trial 1 finished with value: 0.5752287818146227 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.5752287818146227.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.46808510638297873
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:03:38,799] Trial 2 finished with value: 0.5753193893706456 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.4127659574468085
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:03:47,171] Trial 3 finished with value: 0.555807047503867 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.39148936170212767
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 14:03:55,772] Trial 4 finished with value: 0.5573062305482679 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.4425531914893617
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:04:05,157] Trial 5 finished with value: 0.5624522376356624 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.37446808510638296
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 14:04:14,217] Trial 6 finished with value: 0.5592978820959481 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.3829787234042553
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 14:04:22,759] Trial 7 finished with value: 0.5556656592384017 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.425531914893617
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:04:31,046] Trial 8 finished with value: 0.5583386200426743 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.4425531914893617
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.592274678111588
[I 2024-04-15 14:04:39,305] Trial 9 finished with value: 0.5632742502591351 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.5753193893706456.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:04:46,459] Trial 10 finished with value: 0.6213950858555679 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.6213950858555679.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:04:53,790] Trial 11 finished with value: 0.6342027595164134 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.6342027595164134.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:05:04,952] Trial 12 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:05:14,739] Trial 13 finished with value: 0.6326818469688849 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 14:05:24,388] Trial 14 finished with value: 0.6011676615395484 and parameters: {'l1_ratio': 0.14337364566668}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:05:33,124] Trial 15 finished with value: 0.6342027595164134 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.4723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:05:41,332] Trial 16 finished with value: 0.5753736404514289 and parameters: {'l1_ratio': 0.21332970570491078}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.451063829787234
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.592274678111588
[I 2024-04-15 14:05:49,352] Trial 17 finished with value: 0.572773503150209 and parameters: {'l1_ratio': 0.31307066649676046}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:05:57,237] Trial 18 finished with value: 0.6230614243040552 and parameters: {'l1_ratio': 0.12120380780234859}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:06:05,462] Trial 19 finished with value: 0.6213950858555679 and parameters: {'l1_ratio': 0.09170436955756033}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.3829787234042553
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 14:06:14,675] Trial 20 finished with value: 0.562655191603239 and parameters: {'l1_ratio': 0.9656427853442138}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 14:06:21,805] Trial 21 finished with value: 0.633344390417701 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:06:30,412] Trial 22 finished with value: 0.6364841283377062 and parameters: {'l1_ratio': 0.018997068950600285}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5779467680608364

Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:06:39,042] Trial 23 finished with value: 0.5870532612611276 and parameters: {'l1_ratio': 0.17128591911951985}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.4553191489361702
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5965665236051502
[I 2024-04-15 14:06:48,302] Trial 24 finished with value: 0.575243392352473 and parameters: {'l1_ratio': 0.31612098478358897}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:06:58,854] Trial 25 finished with value: 0.6213950858555679 and parameters: {'l1_ratio': 0.08890608406899088}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.46808510638297873
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:07:10,630] Trial 26 finished with value: 0.5753193893706456 and parameters: {'l1_ratio': 0.23521758130887002}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.3829787234042553
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 14:07:21,033] Trial 27 finished with value: 0.5579434471357801 and parameters: {'l1_ratio': 0.8345729974660353}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:07:28,317] Trial 28 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.05293907552049415}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.4127659574468085
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:07:36,808] Trial 29 finished with value: 0.5565527662529459 and parameters: {'l1_ratio': 0.5967051388615063}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:07:44,103] Trial 30 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.07886834045222822}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:07:51,306] Trial 31 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.07093726598033048}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:08:00,122] Trial 32 finished with value: 0.5886105302838958 and parameters: {'l1_ratio': 0.17854043677240342}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:08:08,024] Trial 33 finished with value: 0.6213950858555679 and parameters: {'l1_ratio': 0.09236731347950938}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.4723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5836909871244635
[I 2024-04-15 14:08:15,923] Trial 34 finished with value: 0.5745152713527164 and parameters: {'l1_ratio': 0.2670118969882481}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:08:23,204] Trial 35 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.07062783658587385}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.592274678111588
[I 2024-04-15 14:08:30,946] Trial 36 finished with value: 0.5863907178123113 and parameters: {'l1_ratio': 0.16484949113566097}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.4553191489361702
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.592274678111588
[I 2024-04-15 14:08:39,302] Trial 37 finished with value: 0.5635244539766496 and parameters: {'l1_ratio': 0.3555864451592204}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.4723404255319149
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:08:47,113] Trial 38 finished with value: 0.5753736404514289 and parameters: {'l1_ratio': 0.21345741747882396}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:08:54,517] Trial 39 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.05331572033525481}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.4340425531914894
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.592274678111588
[I 2024-04-15 14:09:04,069] Trial 40 finished with value: 0.5608627603257215 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:09:11,642] Trial 41 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.055795670722385074}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 14:09:19,209] Trial 42 finished with value: 0.6011676615395484 and parameters: {'l1_ratio': 0.142072907757915}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:09:27,497] Trial 43 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:09:35,847] Trial 44 finished with value: 0.6230250678288156 and parameters: {'l1_ratio': 0.11928638663970342}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:09:44,056] Trial 45 finished with value: 0.6388270535087074 and parameters: {'l1_ratio': 0.05096393726684451}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.4723404255319149
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5836909871244635
[I 2024-04-15 14:09:52,757] Trial 46 finished with value: 0.5745516278279561 and parameters: {'l1_ratio': 0.24463993240891824}. Best is trial 12 with value: 0.6412790481054278.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:10:04,022] Trial 47 finished with value: 0.6387654971589989 and parameters: {'l1_ratio': 0.04717599012383908}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:10:20,680] Trial 48 finished with value: 0.5886105302838958 and parameters: {'l1_ratio': 0.18099861440113463}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:10:28,888] Trial 49 finished with value: 0.6230250678288156 and parameters: {'l1_ratio': 0.11759647636835038}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.4127659574468085
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:10:39,312] Trial 50 finished with value: 0.555807047503867 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:10:47,988] Trial 51 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.058762334777661504}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:10:56,660] Trial 52 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.037346638052424476}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:11:06,516] Trial 53 finished with value: 0.6319213906951207 and parameters: {'l1_ratio': 0.0014696408789656515}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:11:15,648] Trial 54 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.03867999387703695}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:11:24,114] Trial 55 finished with value: 0.6222646115550512 and parameters: {'l1_ratio': 0.12564635692044196}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:11:32,757] Trial 56 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.02711845110068599}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:11:41,068] Trial 57 finished with value: 0.6396602227329511 and parameters: {'l1_ratio': 0.023599491568367097}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:11:50,720] Trial 58 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.024110360057232313}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:11:59,696] Trial 59 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.025357214430526864}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:12:08,116] Trial 60 finished with value: 0.6319213906951207 and parameters: {'l1_ratio': 0.001957467310368475}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:12:16,067] Trial 61 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.030660176022709602}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:12:23,608] Trial 62 finished with value: 0.6213335295058593 and parameters: {'l1_ratio': 0.10382019160326969}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:12:31,149] Trial 63 finished with value: 0.6396602227329511 and parameters: {'l1_ratio': 0.02345291711363017}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 14:12:39,051] Trial 64 finished with value: 0.6011676615395484 and parameters: {'l1_ratio': 0.14264777196750908}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:12:46,561] Trial 65 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.024647254063567346}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:12:54,559] Trial 66 finished with value: 0.58937098655766 and parameters: {'l1_ratio': 0.1884946985790945}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.4
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 14:13:03,441] Trial 67 finished with value: 0.5614603528045626 and parameters: {'l1_ratio': 0.7392393754397737}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:13:11,677] Trial 68 finished with value: 0.6221918986045718 and parameters: {'l1_ratio': 0.09624225638539338}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:13:19,988] Trial 69 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.0251945596997986}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5703422053231939

Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 14:13:29,106] Trial 70 finished with value: 0.6011676615395484 and parameters: {'l1_ratio': 0.14231247530518187}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:13:38,576] Trial 71 finished with value: 0.6405185918316635 and parameters: {'l1_ratio': 0.02411011666500801}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:13:50,026] Trial 72 finished with value: 0.6326818469688849 and parameters: {'l1_ratio': 0.0027544773989909427}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:14:01,354] Trial 73 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.08237725153243887}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:14:12,876] Trial 74 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.02754317077662522}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:14:23,928] Trial 75 finished with value: 0.6221918986045718 and parameters: {'l1_ratio': 0.09826005710950056}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:14:37,906] Trial 76 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.07566725561662913}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:14:56,232] Trial 77 finished with value: 0.6404822353564239 and parameters: {'l1_ratio': 0.03455297461745894}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6201550387596899
Fold 3 C-index: 0.37446808510638296
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 14:15:22,712] Trial 78 finished with value: 0.5601094323696375 and parameters: {'l1_ratio': 0.9230252052685165}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 14:15:43,859] Trial 79 finished with value: 0.6018665614636042 and parameters: {'l1_ratio': 0.1577251472741602}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:16:05,500] Trial 80 finished with value: 0.6205730732320951 and parameters: {'l1_ratio': 0.10974415902822598}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:16:23,654] Trial 81 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.029745851153293923}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:16:43,564] Trial 82 finished with value: 0.6319213906951207 and parameters: {'l1_ratio': 0.0005008864687343108}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:17:05,963] Trial 83 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.03255748856971051}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:17:28,354] Trial 84 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06366949303606506}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:17:51,307] Trial 85 finished with value: 0.6389249663336555 and parameters: {'l1_ratio': 0.08084163182680379}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:18:18,508] Trial 86 finished with value: 0.6396238662577114 and parameters: {'l1_ratio': 0.036403628067167834}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:18:40,053] Trial 87 finished with value: 0.6222646115550512 and parameters: {'l1_ratio': 0.12659798094433036}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:19:02,558] Trial 88 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06943249355110245}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.4765957446808511
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 14:19:21,726] Trial 89 finished with value: 0.5746674352584479 and parameters: {'l1_ratio': 0.20628973708016896}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:19:38,991] Trial 90 finished with value: 0.6412790481054278 and parameters: {'l1_ratio': 0.03295405144472199}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:19:52,395] Trial 91 finished with value: 0.6387654971589989 and parameters: {'l1_ratio': 0.04378321692183785}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:20:03,787] Trial 92 finished with value: 0.6388634099839471 and parameters: {'l1_ratio': 0.023103419286485582}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.39574468085106385
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.592274678111588
[I 2024-04-15 14:20:19,021] Trial 93 finished with value: 0.5579545873022896 and parameters: {'l1_ratio': 0.6547273520711029}. Best is trial 12 with value: 0.6412790481054278.

Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:20:35,582] Trial 94 finished with value: 0.6205367167568554 and parameters: {'l1_ratio': 0.09484814672270839}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:20:49,538] Trial 95 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.05507538830695932}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:21:03,717] Trial 96 finished with value: 0.6381029537101828 and parameters: {'l1_ratio': 0.021805441409783247}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:21:18,032] Trial 97 finished with value: 0.6230250678288156 and parameters: {'l1_ratio': 0.11529391500413624}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:21:34,163] Trial 98 finished with value: 0.6380665972349431 and parameters: {'l1_ratio': 0.06979830150965477}. Best is trial 12 with value: 0.6412790481054278.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049

[I 2024-04-15 14:21:45,349] A new study created in memory with name: no-name-901125f4-3aca-476f-a390-22c463bb8ebf

Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:21:45,320] Trial 99 finished with value: 0.6319213906951207 and parameters: {'l1_ratio': 0.0007152740616381027}. Best is trial 12 with value: 0.6412790481054278.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.6412790481054278], datetime_start=datetime.datetime(2024, 4, 15, 14, 4, 53, 796532), datetime_complete=datetime.datetime(2024, 4, 15, 14, 5, 4, 951850), params={'l1_ratio': 0.025939717088620355}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=12, value=None)


* Best Score for C-index:
 0.6412790481054278

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.3918623450099054
Fold 2 IBS: 0.3054662030003641
Fold 3 IBS: 0.40752625572323914
Fold 4 IBS: 0.2666150439066279
Fold 5 IBS: 0.28293007057112657
[I 2024-04-15 14:21:58,198] Trial 0 finished with value: 0.33087998364225263 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.33087998364225263.
Fold 1 IBS: 0.3998476080259402
Fold 2 IBS: 0.2265618087310044
Fold 3 IBS: 0.3475303299925298
Fold 4 IBS: 0.29710817476625395
Fold 5 IBS: 0.27023143183001885
[I 2024-04-15 14:22:12,053] Trial 1 finished with value: 0.30825587066914945 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.30825587066914945.
Fold 1 IBS: 0.4005990952555494
Fold 2 IBS: 0.22741753924120442
Fold 3 IBS: 0.33864421758995367
Fold 4 IBS: 0.2993388587877366
Fold 5 IBS: 0.2634908243326706
[I 2024-04-15 14:22:24,959] Trial 2 finished with value: 0.30589810704142295 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3935215747680156
Fold 2 IBS: 0.2983594847944659
Fold 3 IBS: 0.38943749100702924
Fold 4 IBS: 0.27635481704190074
Fold 5 IBS: 0.2809443721326059
[I 2024-04-15 14:22:39,412] Trial 3 finished with value: 0.3277235479488035 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3914220644384262
Fold 2 IBS: 0.30655166416271346
Fold 3 IBS: 0.40986560167923236
Fold 4 IBS: 0.2666381023884826
Fold 5 IBS: 0.2832583829554355
[I 2024-04-15 14:22:56,776] Trial 4 finished with value: 0.331547163124858 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3971836165090346
Fold 2 IBS: 0.2916350122506727
Fold 3 IBS: 0.36924717884708086
Fold 4 IBS: 0.2889828314700134
Fold 5 IBS: 0.27745380146116627
[I 2024-04-15 14:23:11,911] Trial 5 finished with value: 0.32490048810759353 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3858032604129014
Fold 2 IBS: 0.3134225544926733
Fold 3 IBS: 0.459606018370073
Fold 4 IBS: 0.276305179148977
Fold 5 IBS: 0.2777529094978766
[I 2024-04-15 14:23:27,544] Trial 6 finished with value: 0.34257798438450027 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3923524486359432
Fold 2 IBS: 0.30497321373602937
Fold 3 IBS: 0.40669199309065557
Fold 4 IBS: 0.2667815967729089
Fold 5 IBS: 0.28242405825753025
[I 2024-04-15 14:23:43,541] Trial 7 finished with value: 0.3306446620986135 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3960012355200325
Fold 2 IBS: 0.29457075498399704
Fold 3 IBS: 0.3782599515075044
Fold 4 IBS: 0.28446474634726826
Fold 5 IBS: 0.27964506754788737
[I 2024-04-15 14:24:01,969] Trial 8 finished with value: 0.32658835118133794 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3981083774222351
Fold 2 IBS: 0.28997609886813486
Fold 3 IBS: 0.36369661646277585
Fold 4 IBS: 0.29089564524540706
Fold 5 IBS: 0.27578355825555456
[I 2024-04-15 14:24:18,719] Trial 9 finished with value: 0.32369205925082145 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.30589810704142295.
Fold 1 IBS: 0.3902680462263894
Fold 2 IBS: 0.23002167333173965
Fold 3 IBS: 0.22879704273681675
Fold 4 IBS: 0.23820909547246252
Fold 5 IBS: 0.22706312714542584
[I 2024-04-15 14:24:30,845] Trial 10 finished with value: 0.2628717969825668 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.2628717969825668.
Fold 1 IBS: 0.2468026820151547
Fold 2 IBS: 0.23171540001686725
Fold 3 IBS: 0.22894823619879978
Fold 4 IBS: 0.24126790542394344
Fold 5 IBS: 0.22899299963786818
[I 2024-04-15 14:24:47,388] Trial 11 finished with value: 0.23554544465852664 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.23554544465852664.
Fold 1 IBS: 0.24635438713032382
Fold 2 IBS: 0.23136622083619354
Fold 3 IBS: 0.22891360354458717
Fold 4 IBS: 0.24054637311783691
Fold 5 IBS: 0.22857493048709526
[I 2024-04-15 14:25:08,810] Trial 12 finished with value: 0.23515110302320735 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.2470774174000138
Fold 2 IBS: 0.2319186287389119
Fold 3 IBS: 0.22896914138963123
Fold 4 IBS: 0.2417093661502819
Fold 5 IBS: 0.22924306240682518
[I 2024-04-15 14:25:33,722] Trial 13 finished with value: 0.2357835232171328 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.3967682368572136
Fold 2 IBS: 0.2288302894133305
Fold 3 IBS: 0.22871971754050402
Fold 4 IBS: 0.299961433300825
Fold 5 IBS: 0.22580614705939556
[I 2024-04-15 14:26:03,571] Trial 14 finished with value: 0.2760171648342537 and parameters: {'l1_ratio': 0.14337364566668}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.24700380473252995
Fold 2 IBS: 0.23186513246037796
Fold 3 IBS: 0.22896358610284331
Fold 4 IBS: 0.24159162501985137
Fold 5 IBS: 0.22917630066438024
[I 2024-04-15 14:26:25,570] Trial 15 finished with value: 0.23572008979599657 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.4003612365251516
Fold 2 IBS: 0.22762971181087308
Fold 3 IBS: 0.33634892949793804
Fold 4 IBS: 0.2993086413203233
Fold 5 IBS: 0.26198011314766617
[I 2024-04-15 14:26:45,096] Trial 16 finished with value: 0.3051257264603905 and parameters: {'l1_ratio': 0.21332970570491078}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.39915817004764925
Fold 2 IBS: 0.2262075379083341
Fold 3 IBS: 0.35291233570180397
Fold 4 IBS: 0.2969509946267417
Fold 5 IBS: 0.27179841448854825
[I 2024-04-15 14:27:12,320] Trial 17 finished with value: 0.3094054905546154 and parameters: {'l1_ratio': 0.31307066649676046}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.39509108108975083
Fold 2 IBS: 0.22925367116567535
Fold 3 IBS: 0.22874408394796358
Fold 4 IBS: 0.2371550117840688
Fold 5 IBS: 0.22624782676386518
[I 2024-04-15 14:27:41,234] Trial 18 finished with value: 0.2632983349502648 and parameters: {'l1_ratio': 0.12120380780234859}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.3918321258189944
Fold 2 IBS: 0.2298538025614321
Fold 3 IBS: 0.2287845533218799
Fold 4 IBS: 0.23796625886665873
Fold 5 IBS: 0.226882896873239
[I 2024-04-15 14:28:09,102] Trial 19 finished with value: 0.2630639274884408 and parameters: {'l1_ratio': 0.09170436955756033}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.3879203832901907
Fold 2 IBS: 0.3116720171350131
Fold 3 IBS: 0.4547508380099367
Fold 4 IBS: 0.2755280989413205
Fold 5 IBS: 0.27657688802833946
[I 2024-04-15 14:28:41,082] Trial 20 finished with value: 0.34128964508096005 and parameters: {'l1_ratio': 0.9656427853442138}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.24691227592009013
Fold 2 IBS: 0.23179785491571117
Fold 3 IBS: 0.2289566521237541
Fold 4 IBS: 0.24144547098197222
Fold 5 IBS: 0.22909278979404155
[I 2024-04-15 14:29:03,820] Trial 21 finished with value: 0.23564100874711383 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.2465763050941007
Fold 2 IBS: 0.2315418408025978
Fold 3 IBS: 0.22893081478850097
Fold 4 IBS: 0.2409084373886345
Fold 5 IBS: 0.22878344685247903
[I 2024-04-15 14:29:23,354] Trial 22 finished with value: 0.23534816898526262 and parameters: {'l1_ratio': 0.018997068950600285}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.39854179702240106
Fold 2 IBS: 0.22832798771922305
Fold 3 IBS: 0.2286956726158764
Fold 4 IBS: 0.3001359164776192
Fold 5 IBS: 0.25653124703827374
[I 2024-04-15 14:29:56,327] Trial 23 finished with value: 0.2824465241746787 and parameters: {'l1_ratio': 0.17128591911951985}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.399160796059422
Fold 2 IBS: 0.22616850997652677
Fold 3 IBS: 0.35322386272084044
Fold 4 IBS: 0.2964676261262955
Fold 5 IBS: 0.27207657214168784
[I 2024-04-15 14:30:19,657] Trial 24 finished with value: 0.3094194734049545 and parameters: {'l1_ratio': 0.31612098478358897}. Best is trial 12 with value: 0.23515110302320735.

Fold 1 IBS: 0.3913430452965101
Fold 2 IBS: 0.22991305573774998
Fold 3 IBS: 0.22878890533246202
Fold 4 IBS: 0.23805110419288075
Fold 5 IBS: 0.22694636185590233
[I 2024-04-15 14:30:41,877] Trial 25 finished with value: 0.263008494483101 and parameters: {'l1_ratio': 0.08890608406899088}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.4008483195893078
Fold 2 IBS: 0.22729127829046636
Fold 3 IBS: 0.3396431684651452
Fold 4 IBS: 0.2992938684480467
Fold 5 IBS: 0.26441776623072394
[I 2024-04-15 14:31:08,281] Trial 26 finished with value: 0.306298880204738 and parameters: {'l1_ratio': 0.23521758130887002}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.39309430990207567
Fold 2 IBS: 0.3100160996593142
Fold 3 IBS: 0.4236545872482596
Fold 4 IBS: 0.2695880122170518
Fold 5 IBS: 0.2826521039656795
[I 2024-04-15 14:31:36,996] Trial 27 finished with value: 0.3358010225984761 and parameters: {'l1_ratio': 0.8345729974660353}. Best is trial 12 with value: 0.23515110302320735.
Fold 1 IBS: 0.24558302947229363
Fold 2 IBS: 0.2307136324356008
Fold 3 IBS: 0.22885352264482775
Fold 4 IBS: 0.23933987118637368
Fold 5 IBS: 0.22782502820921666
[I 2024-04-15 14:31:55,193] Trial 28 finished with value: 0.2344630167896625 and parameters: {'l1_ratio': 0.05293907552049415}. Best is trial 28 with value: 0.2344630167896625.
Fold 1 IBS: 0.3929148796513781
Fold 2 IBS: 0.30080591500451437
Fold 3 IBS: 0.39605112408615334
Fold 4 IBS: 0.2711877459238189
Fold 5 IBS: 0.2811676026968435
[I 2024-04-15 14:32:10,481] Trial 29 finished with value: 0.32842545347254165 and parameters: {'l1_ratio': 0.5967051388615063}. Best is trial 28 with value: 0.2344630167896625.
Fold 1 IBS: 0.24494849865754695
Fold 2 IBS: 0.2301290908554374
Fold 3 IBS: 0.22880529056390944
Fold 4 IBS: 0.23836859800709898
Fold 5 IBS: 0.22717918075098062
[I 2024-04-15 14:32:24,350] Trial 30 finished with value: 0.2338861317669947 and parameters: {'l1_ratio': 0.07886834045222822}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24513344427327466
Fold 2 IBS: 0.23030374269744422
Fold 3 IBS: 0.2288191175119713
Fold 4 IBS: 0.238649165846887
Fold 5 IBS: 0.22736926005937755
[I 2024-04-15 14:32:42,627] Trial 31 finished with value: 0.23405494607779093 and parameters: {'l1_ratio': 0.07093726598033048}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39883469868559057
Fold 2 IBS: 0.22820269243168786
Fold 3 IBS: 0.22869054385665208
Fold 4 IBS: 0.29982952280930963
Fold 5 IBS: 0.25743386785441524
[I 2024-04-15 14:33:04,309] Trial 32 finished with value: 0.28259826512753106 and parameters: {'l1_ratio': 0.17854043677240342}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39191529122953767
Fold 2 IBS: 0.22983982594679325
Fold 3 IBS: 0.2287835358209031
Fold 4 IBS: 0.23794638018681338
Fold 5 IBS: 0.22686794975252397
[I 2024-04-15 14:33:24,670] Trial 33 finished with value: 0.26307059658731424 and parameters: {'l1_ratio': 0.09236731347950938}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.40033763378593307
Fold 2 IBS: 0.22682729328210544
Fold 3 IBS: 0.3444665262503959
Fold 4 IBS: 0.29812365920113787
Fold 5 IBS: 0.26804572644100205
[I 2024-04-15 14:33:38,361] Trial 34 finished with value: 0.30756016779211487 and parameters: {'l1_ratio': 0.2670118969882481}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24514081219715708
Fold 2 IBS: 0.23031062911015235
Fold 3 IBS: 0.2288196731147191
Fold 4 IBS: 0.23866044405898912
Fold 5 IBS: 0.2273768019382597
[I 2024-04-15 14:33:55,398] Trial 35 finished with value: 0.23406167208385548 and parameters: {'l1_ratio': 0.07062783658587385}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.3976578920131247
Fold 2 IBS: 0.22858679309236377
Fold 3 IBS: 0.22870737903742697
Fold 4 IBS: 0.3001669491062015
Fold 5 IBS: 0.22555431098068296
[I 2024-04-15 14:34:12,140] Trial 36 finished with value: 0.27613466484596 and parameters: {'l1_ratio': 0.15667645398767704}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39795210523927244
Fold 2 IBS: 0.2902612278025915
Fold 3 IBS: 0.3642273149705805
Fold 4 IBS: 0.29041418815652487
Fold 5 IBS: 0.27595976555215224
[I 2024-04-15 14:34:44,082] Trial 37 finished with value: 0.32376292034422427 and parameters: {'l1_ratio': 0.3955428254204711}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24528716536175832
Fold 2 IBS: 0.23044626408677757
Fold 3 IBS: 0.2288307746727856
Fold 4 IBS: 0.2388847319879204
Fold 5 IBS: 0.22752661044601727
[I 2024-04-15 14:35:10,267] Trial 38 finished with value: 0.23419510931105184 and parameters: {'l1_ratio': 0.06458318408815164}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39914598538641183
Fold 2 IBS: 0.28726780735516816
Fold 3 IBS: 0.3576033008763088
Fold 4 IBS: 0.29422519742406394
Fold 5 IBS: 0.2738440640657252
[I 2024-04-15 14:35:29,574] Trial 39 finished with value: 0.32241727102153556 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4003711790220968
Fold 2 IBS: 0.22753731969410154
Fold 3 IBS: 0.33733656931101164
Fold 4 IBS: 0.29911648718275274
Fold 5 IBS: 0.2627937872601373
[I 2024-04-15 14:35:44,039] Trial 40 finished with value: 0.30543106849402 and parameters: {'l1_ratio': 0.21920161056929305}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24531025293335787
Fold 2 IBS: 0.2304674589760935
Fold 3 IBS: 0.22883253645209783
Fold 4 IBS: 0.2389201621472317
Fold 5 IBS: 0.22755011712049822
[I 2024-04-15 14:35:56,255] Trial 41 finished with value: 0.23421610552585587 and parameters: {'l1_ratio': 0.0636471141894898}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.3955860386296037
Fold 2 IBS: 0.22911090071764498
Fold 3 IBS: 0.22873546522679292
Fold 4 IBS: 0.236973588290887
Fold 5 IBS: 0.22609852596778068
[I 2024-04-15 14:36:10,450] Trial 42 finished with value: 0.26330090376654186 and parameters: {'l1_ratio': 0.1285481398109456}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24531684568268494
Fold 2 IBS: 0.2304735010807529
Fold 3 IBS: 0.2288330400145277
Fold 4 IBS: 0.2389302818717552
Fold 5 IBS: 0.22755682269301714
[I 2024-04-15 14:36:22,851] Trial 43 finished with value: 0.2342220982685476 and parameters: {'l1_ratio': 0.06338068170878226}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39876755999347274
Fold 2 IBS: 0.22825259346733603
Fold 3 IBS: 0.22869254361956873
Fold 4 IBS: 0.2998945918674026
Fold 5 IBS: 0.2570152134521699
[I 2024-04-15 14:36:34,861] Trial 44 finished with value: 0.28252450047999 and parameters: {'l1_ratio': 0.17563667169234978}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24540662920129078
Fold 2 IBS: 0.23055533327316544
Fold 3 IBS: 0.22883991768292566
Fold 4 IBS: 0.23906821143794535
Fold 5 IBS: 0.22764784004142619
[I 2024-04-15 14:36:48,050] Trial 45 finished with value: 0.23430358632735068 and parameters: {'l1_ratio': 0.05979028836034311}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4005184525548335
Fold 2 IBS: 0.22691591342092246
Fold 3 IBS: 0.3436483713176691
Fold 4 IBS: 0.2984235240153847
Fold 5 IBS: 0.26763344162487696
[I 2024-04-15 14:37:02,617] Trial 46 finished with value: 0.30742794058673734 and parameters: {'l1_ratio': 0.2607709884409519}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.3963599923902143
Fold 2 IBS: 0.29356022493910977
Fold 3 IBS: 0.37523959293935394
Fold 4 IBS: 0.2857723123381934
Fold 5 IBS: 0.2787402784270799
[I 2024-04-15 14:37:17,234] Trial 47 finished with value: 0.3259344802067902 and parameters: {'l1_ratio': 0.4610482911707774}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39435807864316713
Fold 2 IBS: 0.22941110776485876
Fold 3 IBS: 0.22875404803782304
Fold 4 IBS: 0.2373599253115474
Fold 5 IBS: 0.22641323638175584
[I 2024-04-15 14:37:29,480] Trial 48 finished with value: 0.26325927922783043 and parameters: {'l1_ratio': 0.11325460052799155}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.4003573314594183
Fold 2 IBS: 0.22764020964966272
Fold 3 IBS: 0.33617393117748867
Fold 4 IBS: 0.2992434723300194
Fold 5 IBS: 0.26193915559599695
[I 2024-04-15 14:37:43,918] Trial 49 finished with value: 0.30507082004251723 and parameters: {'l1_ratio': 0.21266731725822757}. Best is trial 30 with value: 0.2338861317669947.

Fold 1 IBS: 0.39322003858934845
Fold 2 IBS: 0.2987344065368188
Fold 3 IBS: 0.39044818172621804
Fold 4 IBS: 0.27570374849433044
Fold 5 IBS: 0.28089377377571967
[I 2024-04-15 14:37:58,697] Trial 50 finished with value: 0.3278000298244871 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24527167584214757
Fold 2 IBS: 0.23043201333842706
Fold 3 IBS: 0.22882959418766094
Fold 4 IBS: 0.23886096933818587
Fold 5 IBS: 0.2275108188111229
[I 2024-04-15 14:38:11,697] Trial 51 finished with value: 0.23418101430350885 and parameters: {'l1_ratio': 0.06521384802113693}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24563902210807548
Fold 2 IBS: 0.23076318528471024
Fold 3 IBS: 0.228857861655577
Fold 4 IBS: 0.23942629816028696
Fold 5 IBS: 0.22788081987002892
[I 2024-04-15 14:38:24,597] Trial 52 finished with value: 0.2345134374157357 and parameters: {'l1_ratio': 0.05081950410384198}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.39527302947893933
Fold 2 IBS: 0.22920966718361796
Fold 3 IBS: 0.22874138478163542
Fold 4 IBS: 0.23709865971363686
Fold 5 IBS: 0.22620182493461968
[I 2024-04-15 14:38:38,893] Trial 53 finished with value: 0.2633049132184898 and parameters: {'l1_ratio': 0.12345350764209984}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24588206482898078
Fold 2 IBS: 0.2309743489968181
Fold 3 IBS: 0.22887677129367584
Fold 4 IBS: 0.2398026976439158
Fold 5 IBS: 0.22812049573090087
[I 2024-04-15 14:38:55,009] Trial 54 finished with value: 0.2347312756988583 and parameters: {'l1_ratio': 0.04191802294631253}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.3993929059146672
Fold 2 IBS: 0.22800891739207346
Fold 3 IBS: 0.22868332539730385
Fold 4 IBS: 0.2993203874253769
Fold 5 IBS: 0.25878969697975396
[I 2024-04-15 14:39:12,229] Trial 55 finished with value: 0.28283904662183507 and parameters: {'l1_ratio': 0.19000268981738272}. Best is trial 30 with value: 0.2338861317669947.
Fold 1 IBS: 0.24487630117444
Fold 2 IBS: 0.23005998909999223
Fold 3 IBS: 0.22879996205090686
Fold 4 IBS: 0.23826561048773492
Fold 5 IBS: 0.22710445523870026
[I 2024-04-15 14:39:29,529] Trial 56 finished with value: 0.23382126361035485 and parameters: {'l1_ratio': 0.0820512824935705}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.39357439332427663
Fold 2 IBS: 0.22957821255734792
Fold 3 IBS: 0.22876513907897691
Fold 4 IBS: 0.2375833449213778
Fold 5 IBS: 0.22658966414192405
[I 2024-04-15 14:39:44,755] Trial 57 finished with value: 0.26321815080478067 and parameters: {'l1_ratio': 0.10498380549952754}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.3973810620864378
Fold 2 IBS: 0.22869123089454899
Fold 3 IBS: 0.22871251684974334
Fold 4 IBS: 0.30010619705427427
Fold 5 IBS: 0.22566213037685862
[I 2024-04-15 14:40:02,225] Trial 58 finished with value: 0.27611062745237264 and parameters: {'l1_ratio': 0.15091949362265406}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.24696119391640517
Fold 2 IBS: 0.23183391703362632
Fold 3 IBS: 0.22896036158195493
Fold 4 IBS: 0.2415235813263066
Fold 5 IBS: 0.22913749166918668
[I 2024-04-15 14:40:18,478] Trial 59 finished with value: 0.2356833091054959 and parameters: {'l1_ratio': 0.007735984288532609}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.39162383017741226
Fold 2 IBS: 0.305975702795548
Fold 3 IBS: 0.40859199673637503
Fold 4 IBS: 0.26658300441746396
Fold 5 IBS: 0.28303845271595574
[I 2024-04-15 14:40:33,791] Trial 60 finished with value: 0.331162597368551 and parameters: {'l1_ratio': 0.7056326782501279}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.2449544685049419
Fold 2 IBS: 0.23013478176355218
Fold 3 IBS: 0.22880573302077792
Fold 4 IBS: 0.2383771415952901
Fold 5 IBS: 0.22718534603689539
[I 2024-04-15 14:40:46,111] Trial 61 finished with value: 0.2338914941842915 and parameters: {'l1_ratio': 0.0786073560111757}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.39194640337794073
Fold 2 IBS: 0.22983354113184987
Fold 3 IBS: 0.22878307941541867
Fold 4 IBS: 0.2379374579712239
Fold 5 IBS: 0.22686123133842037
[I 2024-04-15 14:41:01,192] Trial 62 finished with value: 0.2630723426469707 and parameters: {'l1_ratio': 0.09266577790133239}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.3964545986809386
Fold 2 IBS: 0.2289096970007676
Fold 3 IBS: 0.2287240105943408
Fold 4 IBS: 0.29980585122205633
Fold 5 IBS: 0.2258886362141153
[I 2024-04-15 14:41:20,199] Trial 63 finished with value: 0.2759565587424437 and parameters: {'l1_ratio': 0.13912461982063118}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.24614213304821814
Fold 2 IBS: 0.2311931601074125
Fold 3 IBS: 0.22889706483937514
Fold 4 IBS: 0.24020806072796752
Fold 5 IBS: 0.2283725372934332
[I 2024-04-15 14:41:33,345] Trial 64 finished with value: 0.23496259120328128 and parameters: {'l1_ratio': 0.0329116162908697}. Best is trial 56 with value: 0.23382126361035485.
Fold 1 IBS: 0.24486542637889328
Fold 2 IBS: 0.2300495363842797
Fold 3 IBS: 0.22879916314344928
Fold 4 IBS: 0.238250151672611
Fold 5 IBS: 0.22709317337996893
[I 2024-04-15 14:41:46,780] Trial 65 finished with value: 0.2338114901918404 and parameters: {'l1_ratio': 0.08253500705829862}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.2472294817360726
Fold 2 IBS: 0.23202742671939489
Fold 3 IBS: 0.2289805519729031
Fold 4 IBS: 0.2419476118616087
Fold 5 IBS: 0.22937984332126538
[I 2024-04-15 14:41:57,708] Trial 66 finished with value: 0.23591298312224893 and parameters: {'l1_ratio': 0.00046316324187258007}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39116286547091644
Fold 2 IBS: 0.3090977436629136
Fold 3 IBS: 0.4193345078079495
Fold 4 IBS: 0.2686099344481483
Fold 5 IBS: 0.28332980763810445
[I 2024-04-15 14:42:12,266] Trial 67 finished with value: 0.3343069718056064 and parameters: {'l1_ratio': 0.7965604964350725}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39052486574780915
Fold 2 IBS: 0.2299983271442161
Fold 3 IBS: 0.22879527638559358
Fold 4 IBS: 0.23817486276027341
Fold 5 IBS: 0.22703798152095866
[I 2024-04-15 14:42:24,015] Trial 68 finished with value: 0.2629062627117702 and parameters: {'l1_ratio': 0.084913469611982}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39973444942582353
Fold 2 IBS: 0.2279107459848376
Fold 3 IBS: 0.333227352879262
Fold 4 IBS: 0.29923755493645154
Fold 5 IBS: 0.25980866160848154
[I 2024-04-15 14:42:35,993] Trial 69 finished with value: 0.3039837529669712 and parameters: {'l1_ratio': 0.19592562383994028}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.4006245100994061
Fold 2 IBS: 0.22704226979070136
Fold 3 IBS: 0.3422799709032668
Fold 4 IBS: 0.29915279891074026
Fold 5 IBS: 0.2662044425810115
[I 2024-04-15 14:42:49,623] Trial 70 finished with value: 0.30706079845702516 and parameters: {'l1_ratio': 0.25201254783065224}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24524831401051891
Fold 2 IBS: 0.2304104737544906
Fold 3 IBS: 0.22882781616090025
Fold 4 IBS: 0.23882514248722972
Fold 5 IBS: 0.22748700513163977
[I 2024-04-15 14:43:03,491] Trial 71 finished with value: 0.23415975030895586 and parameters: {'l1_ratio': 0.06616903992478125}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.2461529633894722
Fold 2 IBS: 0.231202110978217
Fold 3 IBS: 0.2288979097876805
Fold 4 IBS: 0.24022500767108396
Fold 5 IBS: 0.22838293577212765
[I 2024-04-15 14:43:16,055] Trial 72 finished with value: 0.23497218551971627 and parameters: {'l1_ratio': 0.0325477863280557}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39723433831561145
Fold 2 IBS: 0.22874143621723084
Fold 3 IBS: 0.22871506956265172
Fold 4 IBS: 0.29990202757738693
Fold 5 IBS: 0.2257140636868955
[I 2024-04-15 14:43:28,724] Trial 73 finished with value: 0.2760613870719553 and parameters: {'l1_ratio': 0.14817957619214692}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.3938658126819628
Fold 2 IBS: 0.22952597100043157
Fold 3 IBS: 0.22876161553527383
Fold 4 IBS: 0.23751281846843927
Fold 5 IBS: 0.2265344060477725
[I 2024-04-15 14:43:40,853] Trial 74 finished with value: 0.263240124746776 and parameters: {'l1_ratio': 0.1075513701449365}. Best is trial 65 with value: 0.2338114901918404.

Fold 1 IBS: 0.24502298791627394
Fold 2 IBS: 0.23019984637955831
Fold 3 IBS: 0.22881083058401447
Fold 4 IBS: 0.23848030996038092
Fold 5 IBS: 0.22725595943412547
[I 2024-04-15 14:43:53,869] Trial 75 finished with value: 0.23395398685487062 and parameters: {'l1_ratio': 0.07563581400941731}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39566788032604905
Fold 2 IBS: 0.22905991597084543
Fold 3 IBS: 0.22873248532776408
Fold 4 IBS: 0.2369097692969695
Fold 5 IBS: 0.2260452207998657
[I 2024-04-15 14:44:05,861] Trial 76 finished with value: 0.2632830543442988 and parameters: {'l1_ratio': 0.13120285166575224}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.399514089081406
Fold 2 IBS: 0.2263144117931058
Fold 3 IBS: 0.3514093726185773
Fold 4 IBS: 0.2973571561270843
Fold 5 IBS: 0.27140764137209317
[I 2024-04-15 14:44:19,159] Trial 77 finished with value: 0.3092005341984533 and parameters: {'l1_ratio': 0.3048122805041498}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39133805278465356
Fold 2 IBS: 0.2299136541773637
Fold 3 IBS: 0.22878894960195015
Fold 4 IBS: 0.23805196586516209
Fold 5 IBS: 0.22694700365147447
[I 2024-04-15 14:44:30,700] Trial 78 finished with value: 0.2630079252161208 and parameters: {'l1_ratio': 0.08887792272875211}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24624359124824416
Fold 2 IBS: 0.2312765043185076
Fold 3 IBS: 0.2289049767182452
Fold 4 IBS: 0.24036820381747587
Fold 5 IBS: 0.2284696479753556
[I 2024-04-15 14:44:41,451] Trial 79 finished with value: 0.2350525848155657 and parameters: {'l1_ratio': 0.029537618413726166}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.3925329327965967
Fold 2 IBS: 0.30293135984926206
Fold 3 IBS: 0.40204802973268233
Fold 4 IBS: 0.26867719386417943
Fold 5 IBS: 0.28188853862183366
[I 2024-04-15 14:44:53,883] Trial 80 finished with value: 0.3296156109729108 and parameters: {'l1_ratio': 0.641468837353442}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24515065232860303
Fold 2 IBS: 0.23031981754355155
Fold 3 IBS: 0.2288204156650724
Fold 4 IBS: 0.238675508445124
Fold 5 IBS: 0.22738686932854985
[I 2024-04-15 14:45:04,887] Trial 81 finished with value: 0.23407065266218016 and parameters: {'l1_ratio': 0.07021535375765953}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.39806534881421707
Fold 2 IBS: 0.2284608459022606
Fold 3 IBS: 0.22870149737516768
Fold 4 IBS: 0.3004535730514154
Fold 5 IBS: 0.22542464334452236
[I 2024-04-15 14:45:17,422] Trial 82 finished with value: 0.27622118169751664 and parameters: {'l1_ratio': 0.16372407392678778}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.2450098475667694
Fold 2 IBS: 0.23018740480544045
Fold 3 IBS: 0.2288098503165454
Fold 4 IBS: 0.23846020707890095
Fold 5 IBS: 0.2272424388038213
[I 2024-04-15 14:45:27,865] Trial 83 finished with value: 0.23394194971429552 and parameters: {'l1_ratio': 0.07620228344148919}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.3947271997297105
Fold 2 IBS: 0.22935996975968273
Fold 3 IBS: 0.2287507593190964
Fold 4 IBS: 0.23729278948660673
Fold 5 IBS: 0.22635942785332522
[I 2024-04-15 14:45:39,087] Trial 84 finished with value: 0.2632980292296843 and parameters: {'l1_ratio': 0.11581970513962662}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.245070914203763
Fold 2 IBS: 0.23024507741977812
Fold 3 IBS: 0.2288144161808295
Fold 4 IBS: 0.23855365628101657
Fold 5 IBS: 0.22730521970613052
[I 2024-04-15 14:45:51,223] Trial 85 finished with value: 0.23399785675830356 and parameters: {'l1_ratio': 0.0735833348347236}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24605330959186697
Fold 2 IBS: 0.23111926323241658
Fold 3 IBS: 0.22889013320742585
Fold 4 IBS: 0.240069279929389
Fold 5 IBS: 0.22828696300794135
[I 2024-04-15 14:46:04,227] Trial 86 finished with value: 0.23488378979380795 and parameters: {'l1_ratio': 0.03592901511061927}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.3993432863677698
Fold 2 IBS: 0.2280402739083491
Fold 3 IBS: 0.22868443382099882
Fold 4 IBS: 0.29943858035164905
Fold 5 IBS: 0.2585747609665989
[I 2024-04-15 14:46:21,916] Trial 87 finished with value: 0.2828162670830731 and parameters: {'l1_ratio': 0.18812747562021762}. Best is trial 65 with value: 0.2338114901918404.
Fold 1 IBS: 0.24485796940712803
Fold 2 IBS: 0.23004236218331026
Fold 3 IBS: 0.22879861590151068
Fold 4 IBS: 0.23823955951440573
Fold 5 IBS: 0.22708543331173908
[I 2024-04-15 14:46:35,375] Trial 88 finished with value: 0.2338047880636188 and parameters: {'l1_ratio': 0.08286735522305856}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.3938544294666409
Fold 2 IBS: 0.22952829696027713
Fold 3 IBS: 0.22876177133432515
Fold 4 IBS: 0.23751594517841412
Fold 5 IBS: 0.2265368642759217
[I 2024-04-15 14:46:50,739] Trial 89 finished with value: 0.26323946144311583 and parameters: {'l1_ratio': 0.10743670615366892}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.3910165365989333
Fold 2 IBS: 0.3098405676002889
Fold 3 IBS: 0.4461940134343879
Fold 4 IBS: 0.27422320983245213
Fold 5 IBS: 0.27661540684553465
[I 2024-04-15 14:47:04,602] Trial 90 finished with value: 0.3395779468623194 and parameters: {'l1_ratio': 0.9345250358538123}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.2450529620213023
Fold 2 IBS: 0.23022816184128844
Fold 3 IBS: 0.22881307122854827
Fold 4 IBS: 0.23852617747302599
Fold 5 IBS: 0.22728676309883497
[I 2024-04-15 14:47:16,719] Trial 91 finished with value: 0.2339814271326 and parameters: {'l1_ratio': 0.07434965932755738}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.3965675754346674
Fold 2 IBS: 0.2288556104020036
Fold 3 IBS: 0.22872107230154076
Fold 4 IBS: 0.2998773621109167
Fold 5 IBS: 0.2258324302422724
[I 2024-04-15 14:47:28,768] Trial 92 finished with value: 0.2759708100982802 and parameters: {'l1_ratio': 0.14201406309306291}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.24653407405367828
Fold 2 IBS: 0.23150883900276614
Fold 3 IBS: 0.2289275481669748
Fold 4 IBS: 0.24083958522406043
Fold 5 IBS: 0.22874400522700003
[I 2024-04-15 14:47:41,493] Trial 93 finished with value: 0.23531081033489593 and parameters: {'l1_ratio': 0.02029171095338489}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.24579052639803933
Fold 2 IBS: 0.2308955700653028
Fold 3 IBS: 0.22886963796329246
Fold 4 IBS: 0.23966068067617854
Fold 5 IBS: 0.22803069901035003
[I 2024-04-15 14:47:52,483] Trial 94 finished with value: 0.23464942282263263 and parameters: {'l1_ratio': 0.04521438120033323}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.3910601607874717
Fold 2 IBS: 0.22993940507304436
Fold 3 IBS: 0.22879086047024366
Fold 4 IBS: 0.23808913493674821
Fold 5 IBS: 0.22697463596229936
[I 2024-04-15 14:48:06,560] Trial 95 finished with value: 0.26297083944596145 and parameters: {'l1_ratio': 0.08766803257022107}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.395416404645614
Fold 2 IBS: 0.2291828809241768
Fold 3 IBS: 0.22873976031593662
Fold 4 IBS: 0.23706454827739398
Fold 5 IBS: 0.22617394584411757
[I 2024-04-15 14:48:18,900] Trial 96 finished with value: 0.2633155080014479 and parameters: {'l1_ratio': 0.12482900348100745}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.24567585887422888
Fold 2 IBS: 0.23079560157484277
Fold 3 IBS: 0.22886072056657633
Fold 4 IBS: 0.23948321316747923
Fold 5 IBS: 0.22791740649183762
[I 2024-04-15 14:48:30,007] Trial 97 finished with value: 0.23454656013499298 and parameters: {'l1_ratio': 0.04943931135909188}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.39837016468593534
Fold 2 IBS: 0.22836491712647833
Fold 3 IBS: 0.22869725209951716
Fold 4 IBS: 0.30030140536896843
Fold 5 IBS: 0.2562523686327016
[I 2024-04-15 14:48:43,927] Trial 98 finished with value: 0.2823972215827202 and parameters: {'l1_ratio': 0.1691706843036525}. Best is trial 88 with value: 0.2338047880636188.
Fold 1 IBS: 0.247199841363947
Fold 2 IBS: 0.23200639962237068
Fold 3 IBS: 0.22897833500605416
Fold 4 IBS: 0.24190171038601244
Fold 5 IBS: 0.2293533012639731
[I 2024-04-15 14:48:54,753] Trial 99 finished with value: 0.23588791752847146 and parameters: {'l1_ratio': 0.0012462919331408112}. Best is trial 88 with value: 0.2338047880636188.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.2338047880636188], datetime_start=datetime.datetime(2024, 4, 15, 14, 46, 21, 922965), datetime_complete=datetime.datetime(2024, 4, 15, 14, 46, 35, 374398), params={'l1_ratio': 0.08286735522305856}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.2338047880636188

In [47]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.641
train_ibs:  0.234

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [50]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.025939717088620355)

test_cindex : 0.527

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08286735522305856)

test_ibs:  0.229

In [51]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [52]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:48:55,041] A new study created in memory with name: no-name-b2f6658c-f680-4909-8747-2cebd9dd5d81

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 14:49:33,673] Trial 0 finished with value: 0.676580931087897 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5278969957081545
[I 2024-04-15 14:49:40,582] Trial 1 finished with value: 0.6145677177800518 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5579399141630901
[I 2024-04-15 14:49:48,970] Trial 2 finished with value: 0.6308271798641135 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:49:50,529] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:49:53,306] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5665236051502146
[I 2024-04-15 14:50:08,022] Trial 5 finished with value: 0.622775959906744 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:50:44,180] Trial 6 finished with value: 0.6579539434813163 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:50:47,036] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.4978540772532189
[I 2024-04-15 14:50:57,988] Trial 8 finished with value: 0.49957081545064375 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5536480686695279
[I 2024-04-15 14:51:05,186] Trial 9 finished with value: 0.6104647324062334 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:51:05,843] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 14:51:28,975] Trial 11 finished with value: 0.6380986965147648 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:51:38,811] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 0 with value: 0.676580931087897.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 14:51:54,070] Trial 13 finished with value: 0.6817713699215188 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 13 with value: 0.6817713699215188.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:51:55,163] Trial 14 finished with value: 0.7086971170202203 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17530903073562382, 'warm_start': True}. Best is trial 14 with value: 0.7086971170202203.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7224334600760456

Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 14:51:56,218] Trial 15 finished with value: 0.7109217554965979 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.8147833133306369, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2047601680710191, 'warm_start': True}. Best is trial 15 with value: 0.7109217554965979.
Fold 1 C-index: 0.3804780876494024
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7936170212765957
Fold 4 C-index: 0.5836501901140685
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 14:51:56,561] Trial 16 finished with value: 0.6406031902934244 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.8484814588885312, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3777228897992014, 'warm_start': True}. Best is trial 15 with value: 0.7109217554965979.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 14:51:57,758] Trial 17 finished with value: 0.7155779596484929 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 107, 'oob_score': True, 'max_samples': 0.9817072304699028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10458249310616385, 'warm_start': True}. Best is trial 17 with value: 0.7155779596484929.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.5965665236051502
[I 2024-04-15 14:51:59,274] Trial 18 finished with value: 0.6632701708683197 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09529552899934571, 'warm_start': True}. Best is trial 17 with value: 0.7155779596484929.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 14:52:00,136] Trial 19 finished with value: 0.7020033533743641 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.9945705745432233, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24472699218520227, 'warm_start': True}. Best is trial 17 with value: 0.7155779596484929.
Fold 1 C-index: 0.5517928286852589
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.7489270386266095
[I 2024-04-15 14:52:00,497] Trial 20 finished with value: 0.7328268614402537 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.8574334183065578, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07885915209462858, 'warm_start': True}. Best is trial 20 with value: 0.7328268614402537.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7170212765957447
Fold 4 C-index: 0.6368821292775665
Fold 5 C-index: 0.7618025751072961
[I 2024-04-15 14:52:00,844] Trial 21 finished with value: 0.6632690568465429 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.8545770614457692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09753632164229144, 'warm_start': True}. Best is trial 20 with value: 0.7328268614402537.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 14:52:02,142] Trial 22 finished with value: 0.7608017484332823 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.8604261826280419, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08663018400156977, 'warm_start': True}. Best is trial 22 with value: 0.7608017484332823.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 14:52:03,743] Trial 23 finished with value: 0.7690660772280372 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 143, 'oob_score': True, 'max_samples': 0.9111182603715849, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06775827262990264, 'warm_start': True}. Best is trial 23 with value: 0.7690660772280372.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 14:52:05,687] Trial 24 finished with value: 0.7440693913894477 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 191, 'oob_score': True, 'max_samples': 0.7068738515617914, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06115139138000203, 'warm_start': True}. Best is trial 23 with value: 0.7690660772280372.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 14:52:07,740] Trial 25 finished with value: 0.735486376947699 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 209, 'oob_score': True, 'max_samples': 0.6708962013511481, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0017411537171054953, 'warm_start': True}. Best is trial 23 with value: 0.7690660772280372.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 14:52:09,686] Trial 26 finished with value: 0.7721338228968404 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 167, 'oob_score': True, 'max_samples': 0.7144410113537528, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 14:52:11,399] Trial 27 finished with value: 0.7476542281578183 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 157, 'oob_score': True, 'max_samples': 0.5528028338055412, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04810535800309272, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 14:52:13,981] Trial 28 finished with value: 0.7592273219385095 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.8976414176869512, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13041139349208092, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7467811158798283
[I 2024-04-15 14:52:16,017] Trial 29 finished with value: 0.7370554139892926 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.7263542747152932, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18410661850855684, 'warm_start': True}. Best is trial 26 with value: 0.7721338228968404.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 14:52:17,457] Trial 30 finished with value: 0.7767046870461737 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.6865809791097957, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03407840564085754, 'warm_start': True}. Best is trial 30 with value: 0.7767046870461737.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 14:52:19,087] Trial 31 finished with value: 0.7783309446744106 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 128, 'oob_score': True, 'max_samples': 0.6864172872570439, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03390831993382872, 'warm_start': True}. Best is trial 31 with value: 0.7783309446744106.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 14:52:20,348] Trial 32 finished with value: 0.8018360760420356 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.6860834762921624, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003201421386592976, 'warm_start': True}. Best is trial 32 with value: 0.8018360760420356.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 14:52:21,262] Trial 33 finished with value: 0.805697747786916 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.6828915837605897, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0037369805268133924, 'warm_start': True}. Best is trial 33 with value: 0.805697747786916.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 14:52:22,152] Trial 34 finished with value: 0.7792583288268815 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.542088684219824, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0026049394827949023, 'warm_start': True}. Best is trial 33 with value: 0.805697747786916.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 14:52:22,726] Trial 35 finished with value: 0.7858857842084914 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 47, 'oob_score': False, 'max_samples': 0.5555279946718963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.001812981934077619, 'warm_start': True}. Best is trial 33 with value: 0.805697747786916.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 14:52:23,236] Trial 36 finished with value: 0.8075337373378838 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.5580112420241825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 14:52:23,840] Trial 37 finished with value: 0.7911337353360948 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 38, 'oob_score': False, 'max_samples': 0.5346071202976119, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0015659966401229835, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 14:52:24,507] Trial 38 finished with value: 0.7097937461377273 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 77, 'oob_score': False, 'max_samples': 0.49592272736753257, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13661004358388135, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 14:52:24,992] Trial 39 finished with value: 0.7523069216002374 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.3660594506190667, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01464079927542979, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 14:52:25,788] Trial 40 finished with value: 0.7978554397858052 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 76, 'oob_score': False, 'max_samples': 0.630075046347036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.032995406893159815, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 14:52:26,236] Trial 41 finished with value: 0.7954545391890099 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6089301708150049, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03239043057256452, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 14:52:26,934] Trial 42 finished with value: 0.7900284630218224 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.6236464814282915, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04019337508392253, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 14:52:27,395] Trial 43 finished with value: 0.7968528898670126 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.5833432046167292, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0672059269880178, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 14:52:28,078] Trial 44 finished with value: 0.7956563985786629 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.592324540739651, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0698334924574171, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 14:52:28,520] Trial 45 finished with value: 0.7787873435446434 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 24, 'oob_score': False, 'max_samples': 0.6535784977460134, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11176553291943035, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.48068669527896996
[I 2024-04-15 14:52:30,715] Trial 46 finished with value: 0.6019647246667115 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.49745394949188, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01840181593129722, 'warm_start': False}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 14:52:31,304] Trial 47 finished with value: 0.7920508675682754 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 58, 'oob_score': False, 'max_samples': 0.39353418519468975, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05831156231976059, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.5493562231759657
[I 2024-04-15 14:52:39,624] Trial 48 finished with value: 0.6212283825700716 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.7485926717501767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025057546057149736, 'warm_start': False}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7854077253218884
[I 2024-04-15 14:52:40,362] Trial 49 finished with value: 0.7499632029110537 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 96, 'oob_score': False, 'max_samples': 0.44115969234395064, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07830679890132161, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5278969957081545
[I 2024-04-15 14:52:40,677] Trial 50 finished with value: 0.634974394907875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.5750261144135627, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2842118200978194, 'warm_start': True}. Best is trial 36 with value: 0.8075337373378838.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8454935622317596
[I 2024-04-15 14:52:41,360] Trial 51 finished with value: 0.8103215750536024 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 64, 'oob_score': False, 'max_samples': 0.6518086495175582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06690852785164401, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-15 14:52:41,935] Trial 52 finished with value: 0.7414732765608105 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.6411231404770097, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1564447852352071, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 14:52:42,741] Trial 53 finished with value: 0.788946918859357 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 87, 'oob_score': False, 'max_samples': 0.7860889554493278, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.123351058509179, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 14:52:43,279] Trial 54 finished with value: 0.782875907006704 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 46, 'oob_score': False, 'max_samples': 0.5150686738177901, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053088835715916965, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:52:43,642] Trial 55 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.6361416430949213, 'max_features': None, 'min_weight_fraction_leaf': 0.3351189537838004, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.4978540772532189
[I 2024-04-15 14:52:46,110] Trial 56 finished with value: 0.6034429601570507 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.5881468887320035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02222550540296471, 'warm_start': False}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8841201716738197
[I 2024-04-15 14:52:48,848] Trial 57 finished with value: 0.8086048191505656 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.7551123413533153, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08480065168490414, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 14:52:50,866] Trial 58 finished with value: 0.8045488801271503 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 260, 'oob_score': False, 'max_samples': 0.7600961767539095, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09207383624105397, 'warm_start': True}. Best is trial 51 with value: 0.8103215750536024.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8927038626609443
[I 2024-04-15 14:53:04,713] Trial 59 finished with value: 0.8256990555886009 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.750348183174299, 'max_features': None, 'min_weight_fraction_leaf': 0.09298348876429541, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 14:54:18,747] Trial 60 finished with value: 0.6442124609537101 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.8199593234466896, 'max_features': None, 'min_weight_fraction_leaf': 0.0919394379990903, 'warm_start': False}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 14:54:28,079] Trial 61 finished with value: 0.8164789015817648 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.747371871755714, 'max_features': None, 'min_weight_fraction_leaf': 0.15822689229615128, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 14:54:37,588] Trial 62 finished with value: 0.8106113416299996 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.7508496958357301, 'max_features': None, 'min_weight_fraction_leaf': 0.16362054636651252, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 14:54:48,449] Trial 63 finished with value: 0.8115712044775746 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.7999745159041743, 'max_features': None, 'min_weight_fraction_leaf': 0.1633521636265725, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 14:54:57,169] Trial 64 finished with value: 0.7974621961967492 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.8114338741724807, 'max_features': None, 'min_weight_fraction_leaf': 0.22569702962880955, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 14:55:07,154] Trial 65 finished with value: 0.8071636949746172 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.7388230594642389, 'max_features': None, 'min_weight_fraction_leaf': 0.17201508827628242, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 14:55:22,194] Trial 66 finished with value: 0.8098870984103786 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.7914494461409277, 'max_features': None, 'min_weight_fraction_leaf': 0.1566811915615436, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 14:55:37,705] Trial 67 finished with value: 0.8082681460510669 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.7957500332085724, 'max_features': None, 'min_weight_fraction_leaf': 0.15586517360511226, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 14:55:47,487] Trial 68 finished with value: 0.8059464159875638 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.8874038406594102, 'max_features': None, 'min_weight_fraction_leaf': 0.18482051372177483, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 14:55:58,567] Trial 69 finished with value: 0.8016545869282632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.9454077003760599, 'max_features': None, 'min_weight_fraction_leaf': 0.21033678746200793, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 14:56:09,498] Trial 70 finished with value: 0.801561500108108 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.8334615557424903, 'max_features': None, 'min_weight_fraction_leaf': 0.23015303679951366, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8669527896995708
[I 2024-04-15 14:56:26,191] Trial 71 finished with value: 0.8073659882213546 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.7819388953984404, 'max_features': None, 'min_weight_fraction_leaf': 0.16118102881068472, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-15 14:56:44,053] Trial 72 finished with value: 0.8099629684417163 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.8068219116706009, 'max_features': None, 'min_weight_fraction_leaf': 0.15407145216490215, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 14:57:02,610] Trial 73 finished with value: 0.8175612834163142 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.7256003056056536, 'max_features': None, 'min_weight_fraction_leaf': 0.12137920431643712, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 14:57:20,365] Trial 74 finished with value: 0.816083889191854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.7174141590887053, 'max_features': None, 'min_weight_fraction_leaf': 0.12120920520274087, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 14:57:38,739] Trial 75 finished with value: 0.8136066947206648 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.7201088555626758, 'max_features': None, 'min_weight_fraction_leaf': 0.11957211852477087, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 14:57:58,657] Trial 76 finished with value: 0.7947253493979941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.7187465920082139, 'max_features': None, 'min_weight_fraction_leaf': 0.11137236004826448, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 14:58:14,845] Trial 77 finished with value: 0.8180614974658367 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 446, 'oob_score': False, 'max_samples': 0.7070247918663345, 'max_features': None, 'min_weight_fraction_leaf': 0.14086452948561107, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:58:17,043] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.13573153603784233, 'max_features': None, 'min_weight_fraction_leaf': 0.1254707213967799, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 14:58:33,592] Trial 79 finished with value: 0.8088334709259224 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 461, 'oob_score': False, 'max_samples': 0.7055544636254668, 'max_features': None, 'min_weight_fraction_leaf': 0.1438720473833855, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 15:00:06,183] Trial 80 finished with value: 0.6725169483906671 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.7358185782998974, 'max_features': None, 'min_weight_fraction_leaf': 0.14042977991983294, 'warm_start': False}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8197424892703863
[I 2024-04-15 15:00:17,280] Trial 81 finished with value: 0.7854052107108721 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.6631147653826805, 'max_features': None, 'min_weight_fraction_leaf': 0.1904717547052109, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 15:00:37,441] Trial 82 finished with value: 0.8127192744156378 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 477, 'oob_score': False, 'max_samples': 0.7037801351415406, 'max_features': None, 'min_weight_fraction_leaf': 0.11857594294537367, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 15:00:58,684] Trial 83 finished with value: 0.8174957323136635 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.7740013537175402, 'max_features': None, 'min_weight_fraction_leaf': 0.11819437402906258, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 15:01:19,032] Trial 84 finished with value: 0.8208785121033545 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.7036421072362206, 'max_features': None, 'min_weight_fraction_leaf': 0.1042771231927323, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 15:01:37,637] Trial 85 finished with value: 0.8150733561874102 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.7011682877791858, 'max_features': None, 'min_weight_fraction_leaf': 0.12093318207567501, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 15:01:57,590] Trial 86 finished with value: 0.7907013482538201 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.768478848703175, 'max_features': None, 'min_weight_fraction_leaf': 0.09728336363025743, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 15:02:16,387] Trial 87 finished with value: 0.8159639335732953 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.6734418984579824, 'max_features': None, 'min_weight_fraction_leaf': 0.10951503187780728, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8755364806866953
[I 2024-04-15 15:02:36,872] Trial 88 finished with value: 0.8168223026720078 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.6840555102318722, 'max_features': None, 'min_weight_fraction_leaf': 0.10827303094470545, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 15:02:54,799] Trial 89 finished with value: 0.8168079889903787 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.6709910468612088, 'max_features': None, 'min_weight_fraction_leaf': 0.1045774891959252, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8884120171673819
[I 2024-04-15 15:03:16,011] Trial 90 finished with value: 0.8168658374293377 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.838525259855138, 'max_features': None, 'min_weight_fraction_leaf': 0.13447535807610542, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8927038626609443
[I 2024-04-15 15:03:35,371] Trial 91 finished with value: 0.8185062817523688 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8357079391333091, 'max_features': None, 'min_weight_fraction_leaf': 0.1364606565599496, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8969957081545065
[I 2024-04-15 15:03:56,653] Trial 92 finished with value: 0.8153188873352564 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 418, 'oob_score': False, 'max_samples': 0.8775642867911538, 'max_features': None, 'min_weight_fraction_leaf': 0.10265171206389755, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8927038626609443
[I 2024-04-15 15:04:17,058] Trial 93 finished with value: 0.8177094690033648 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.8394095427190678, 'max_features': None, 'min_weight_fraction_leaf': 0.1364458020046664, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.871244635193133
[I 2024-04-15 15:04:32,571] Trial 94 finished with value: 0.8013608143135451 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.824344684327448, 'max_features': None, 'min_weight_fraction_leaf': 0.13770030876187686, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 15:05:03,957] Trial 95 finished with value: 0.7844615394050323 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9288120518629511, 'max_features': None, 'min_weight_fraction_leaf': 0.07821825258479492, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8884120171673819
[I 2024-04-15 15:05:23,979] Trial 96 finished with value: 0.8192014573314138 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.8514625493035038, 'max_features': None, 'min_weight_fraction_leaf': 0.13414945701968128, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 15:05:34,494] Trial 97 finished with value: 0.7489816005463226 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8434868595158881, 'max_features': None, 'min_weight_fraction_leaf': 0.14492739581576755, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 15:05:44,689] Trial 98 finished with value: 0.7602419102840589 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.8738054139469061, 'max_features': None, 'min_weight_fraction_leaf': 0.17836759932331153, 'warm_start': True}. Best is trial 59 with value: 0.8256990555886009.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7376425855513308

[I 2024-04-15 15:07:07,015] A new study created in memory with name: no-name-a6292578-6968-404a-862f-a5c67d03818d

Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 15:07:06,990] Trial 99 finished with value: 0.6869965240260854 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.9620550310373028, 'max_features': None, 'min_weight_fraction_leaf': 0.19969443485488828, 'warm_start': False}. Best is trial 59 with value: 0.8256990555886009.


* Best trial for C-index:
 FrozenTrial(number=59, state=TrialState.COMPLETE, values=[0.8256990555886009], datetime_start=datetime.datetime(2024, 4, 15, 14, 52, 50, 872355), datetime_complete=datetime.datetime(2024, 4, 15, 14, 53, 4, 711844), params={'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.750348183174299, 'max_features': None, 'min_weight_fraction_leaf': 0.09298348876429541, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=59, value=None)


* Best Score for C-index:
 0.8256990555886009

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23245200278670178
Fold 2 IBS: 0.18828390646958612
Fold 3 IBS: 0.23334467461111885
Fold 4 IBS: 0.21778957635724466
Fold 5 IBS: 0.21705588757529487
[I 2024-04-15 15:07:51,647] Trial 0 finished with value: 0.21778520955998926 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.25592429781872555
Fold 2 IBS: 0.20485946689623255
Fold 3 IBS: 0.20325171229153138
Fold 4 IBS: 0.24041573411367198
Fold 5 IBS: 0.25038826226064514
[I 2024-04-15 15:07:53,571] Trial 1 finished with value: 0.2309678946761613 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-15 15:07:54,752] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-15 15:07:58,913] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-15 15:08:02,817] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.25997212633964667
Fold 2 IBS: 0.20744288918642237
Fold 3 IBS: 0.2026423630798751
Fold 4 IBS: 0.24621003177873702
Fold 5 IBS: 0.237011163115402
[I 2024-04-15 15:08:12,874] Trial 5 finished with value: 0.2306557147000166 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.23236003007728315
Fold 2 IBS: 0.19904794428914027
Fold 3 IBS: 0.2494015884645073
Fold 4 IBS: 0.23109264114474826
Fold 5 IBS: 0.22160234738320955
[I 2024-04-15 15:08:46,338] Trial 6 finished with value: 0.22670091027177772 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24628707455739712
Fold 2 IBS: 0.22937877730479375
Fold 3 IBS: 0.22655238574634068
Fold 4 IBS: 0.24172342609580938
Fold 5 IBS: 0.23189500202696955
[I 2024-04-15 15:08:54,562] Trial 7 finished with value: 0.2351673331462621 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-15 15:09:09,680] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.25810294443230747
Fold 2 IBS: 0.2105121842174571
Fold 3 IBS: 0.20852352181394615
Fold 4 IBS: 0.24808816916849533
Fold 5 IBS: 0.24280046557837362
[I 2024-04-15 15:09:13,938] Trial 9 finished with value: 0.2336054570421159 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-15 15:09:29,723] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.22732835810482938
Fold 2 IBS: 0.19079277733443636
Fold 3 IBS: 0.2460778769636713
Fold 4 IBS: 0.2245008378197277
Fold 5 IBS: 0.2215817428686409
[I 2024-04-15 15:10:18,053] Trial 11 finished with value: 0.22205631861826114 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.9485893528798968, 'max_features': None, 'min_weight_fraction_leaf': 0.34713111632234195}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.22928305075941044
Fold 2 IBS: 0.18390550450704865
Fold 3 IBS: 0.24184864739150974
Fold 4 IBS: 0.22721384125903
Fold 5 IBS: 0.2215142296748877
[I 2024-04-15 15:11:35,924] Trial 12 finished with value: 0.2207530547183773 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.99460329717513, 'max_features': None, 'min_weight_fraction_leaf': 0.3273519300270286}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2508721712006982
Fold 2 IBS: 0.18403052310984114
Fold 3 IBS: 0.22524806555157315
Fold 4 IBS: 0.2215375179423824
Fold 5 IBS: 0.21525449299601435
[I 2024-04-15 15:13:08,927] Trial 13 finished with value: 0.21938855416010186 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.7795899048785642, 'max_features': None, 'min_weight_fraction_leaf': 0.16534086975223722}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2516414806872797
Fold 2 IBS: 0.207919811215394
Fold 3 IBS: 0.20785133968101643
Fold 4 IBS: 0.24817665948778048
Fold 5 IBS: 0.24584658651359093
[I 2024-04-15 15:13:21,063] Trial 14 finished with value: 0.2322871755170123 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.7714173351535261, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1619227173876303}. Best is trial 0 with value: 0.21778520955998926.
Fold 1 IBS: 0.2675562059035232
Fold 2 IBS: 0.2029191070252219
Fold 3 IBS: 0.21176889229056248
Fold 4 IBS: 0.2393182562209325
Fold 5 IBS: 0.22264059167098002
[I 2024-04-15 15:14:44,621] Trial 15 finished with value: 0.22884061062224403 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.7857370506104712, 'max_features': None, 'min_weight_fraction_leaf': 9.381036713218549e-05}. Best is trial 0 with value: 0.21778520955998926.

Fold 1 IBS: 0.23154807585127796
Fold 2 IBS: 0.1879172902903685
Fold 3 IBS: 0.23486102549308419
Fold 4 IBS: 0.21616191576692922
Fold 5 IBS: 0.21737749792431385
[I 2024-04-15 15:15:27,382] Trial 16 finished with value: 0.21757316106519475 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.7160627225800851, 'max_features': None, 'min_weight_fraction_leaf': 0.2245547459670535}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.23450516079975595
Fold 2 IBS: 0.19048662251174223
Fold 3 IBS: 0.2339738904395174
Fold 4 IBS: 0.23100926323007592
Fold 5 IBS: 0.22282971688978198
[I 2024-04-15 15:16:05,774] Trial 17 finished with value: 0.22256093077417466 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.6871243940599472, 'max_features': None, 'min_weight_fraction_leaf': 0.2285855344271941}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.2544410854280207
Fold 2 IBS: 0.2117548681497262
Fold 3 IBS: 0.21266590914826713
Fold 4 IBS: 0.2556574634571033
Fold 5 IBS: 0.24120325516243565
[I 2024-04-15 15:16:13,374] Trial 18 finished with value: 0.2351445162691106 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08924573043815814}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.254758121825725
Fold 2 IBS: 0.21417743305921627
Fold 3 IBS: 0.21411301096749435
Fold 4 IBS: 0.25657503763721423
Fold 5 IBS: 0.24360746349718543
[I 2024-04-15 15:16:17,712] Trial 19 finished with value: 0.23664621339736708 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.6061595584833309, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22791611456767383}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.24668838755067432
Fold 2 IBS: 0.2323223694774956
Fold 3 IBS: 0.22952287763530818
Fold 4 IBS: 0.24145505906170697
Fold 5 IBS: 0.23037434075470525
[I 2024-04-15 15:16:25,164] Trial 20 finished with value: 0.23607260689597806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.4458729287336371, 'max_features': None, 'min_weight_fraction_leaf': 0.3007687013181908}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.2600372893651329
Fold 2 IBS: 0.18660694396206917
Fold 3 IBS: 0.22280211686218124
Fold 4 IBS: 0.22733720642931526
Fold 5 IBS: 0.2142115361440169
[I 2024-04-15 15:18:16,800] Trial 21 finished with value: 0.2221990185525431 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.7968542041631069, 'max_features': None, 'min_weight_fraction_leaf': 0.14088312030047453}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.24129503101406552
Fold 2 IBS: 0.18675635766667778
Fold 3 IBS: 0.22479751637881812
Fold 4 IBS: 0.23492723723713654
Fold 5 IBS: 0.22502053471551914
[I 2024-04-15 15:19:34,606] Trial 22 finished with value: 0.2225593354024434 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.7333978805634859, 'max_features': None, 'min_weight_fraction_leaf': 0.2049420412000723}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.26293055578958485
Fold 2 IBS: 0.19090188804613092
Fold 3 IBS: 0.22069752168236184
Fold 4 IBS: 0.23410928124121494
Fold 5 IBS: 0.21916676212266545
[I 2024-04-15 15:21:15,759] Trial 23 finished with value: 0.22556120177639158 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8558877999962695, 'max_features': None, 'min_weight_fraction_leaf': 0.12237281401289234}. Best is trial 16 with value: 0.21757316106519475.
Fold 1 IBS: 0.22563558164705028
Fold 2 IBS: 0.18227352293648272
Fold 3 IBS: 0.23768446836088766
Fold 4 IBS: 0.21655250003019877
Fold 5 IBS: 0.2164162038266061
[I 2024-04-15 15:22:31,931] Trial 24 finished with value: 0.2157124553602451 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8436689400574193, 'max_features': None, 'min_weight_fraction_leaf': 0.244242289743401}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.2255150380761434
Fold 2 IBS: 0.183222039023694
Fold 3 IBS: 0.24116960170707816
Fold 4 IBS: 0.21501969498726592
Fold 5 IBS: 0.21539376411213979
[I 2024-04-15 15:23:46,840] Trial 25 finished with value: 0.21606402758126425 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.8781861106771913, 'max_features': None, 'min_weight_fraction_leaf': 0.25578130205333305}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.22614078469457516
Fold 2 IBS: 0.1833696404798902
Fold 3 IBS: 0.24200095974014624
Fold 4 IBS: 0.21359509347332828
Fold 5 IBS: 0.21445882005066608
[I 2024-04-15 15:25:16,521] Trial 26 finished with value: 0.21591305968772118 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8790368112638932, 'max_features': None, 'min_weight_fraction_leaf': 0.25879667379312365}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.2520590907345142
Fold 2 IBS: 0.21140680302204304
Fold 3 IBS: 0.2135506894174242
Fold 4 IBS: 0.25062056418219003
Fold 5 IBS: 0.24445478891921904
[I 2024-04-15 15:25:31,498] Trial 27 finished with value: 0.2344183872550781 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 463, 'oob_score': True, 'max_samples': 0.8959637112797967, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2611199851941091}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.24813242490959445
Fold 2 IBS: 0.20755477056701319
Fold 3 IBS: 0.21299031512560426
Fold 4 IBS: 0.246653939670713
Fold 5 IBS: 0.24277921161361501
[I 2024-04-15 15:25:46,728] Trial 28 finished with value: 0.231622132377308 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.957086450216675, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3146636471285875}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.2342715209035425
Fold 2 IBS: 0.20354279932350952
Fold 3 IBS: 0.25561389987555283
Fold 4 IBS: 0.23678875016407627
Fold 5 IBS: 0.22653209465985072
[I 2024-04-15 15:26:29,101] Trial 29 finished with value: 0.23134981298530638 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.8498266742400898, 'max_features': None, 'min_weight_fraction_leaf': 0.37494346942158263}. Best is trial 24 with value: 0.2157124553602451.
Fold 1 IBS: 0.22979863524090197
Fold 2 IBS: 0.18212512500007025
Fold 3 IBS: 0.23579662743958177
Fold 4 IBS: 0.21698273620013098
Fold 5 IBS: 0.21134554976530948
[I 2024-04-15 15:27:44,957] Trial 30 finished with value: 0.21520973472919888 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9975403100242013, 'max_features': None, 'min_weight_fraction_leaf': 0.2599744768668571}. Best is trial 30 with value: 0.21520973472919888.
Fold 1 IBS: 0.22767673562456642
Fold 2 IBS: 0.18250151839395365
Fold 3 IBS: 0.2346862111366068
Fold 4 IBS: 0.21417509966385215
Fold 5 IBS: 0.21210846579813294
[I 2024-04-15 15:28:48,890] Trial 31 finished with value: 0.2142296061234224 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.9626750941879966, 'max_features': None, 'min_weight_fraction_leaf': 0.26115274999390314}. Best is trial 31 with value: 0.2142296061234224.

Fold 1 IBS: 0.223671117899065
Fold 2 IBS: 0.18242513973526725
Fold 3 IBS: 0.2389733570256732
Fold 4 IBS: 0.21132681423071092
Fold 5 IBS: 0.2129200403370242
[I 2024-04-15 15:29:42,584] Trial 32 finished with value: 0.2138632938455481 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9673759674409311, 'max_features': None, 'min_weight_fraction_leaf': 0.27417727195073677}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2573672754798652
Fold 2 IBS: 0.1902152831375234
Fold 3 IBS: 0.2272585883751577
Fold 4 IBS: 0.22496428138050273
Fold 5 IBS: 0.2133258411787376
[I 2024-04-15 15:30:53,755] Trial 33 finished with value: 0.2226262539103573 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.9964442664551478, 'max_features': None, 'min_weight_fraction_leaf': 0.1855920796843306}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22522414670411478
Fold 2 IBS: 0.18326674769112986
Fold 3 IBS: 0.2387346895291688
Fold 4 IBS: 0.2137747409250764
Fold 5 IBS: 0.2165670671101404
[I 2024-04-15 15:31:31,660] Trial 34 finished with value: 0.21551347839192606 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.9279710918176601, 'max_features': None, 'min_weight_fraction_leaf': 0.2867300145495075}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.251659132950299
Fold 2 IBS: 0.21573975281463745
Fold 3 IBS: 0.21830007825376807
Fold 4 IBS: 0.2471377111202043
Fold 5 IBS: 0.24099856704491995
[I 2024-04-15 15:31:38,617] Trial 35 finished with value: 0.2347670484367658 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9536728448516014, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3909359479764509}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2334362354514201
Fold 2 IBS: 0.21078608255075681
Fold 3 IBS: 0.2561650954496425
Fold 4 IBS: 0.2412311316030896
Fold 5 IBS: 0.23143582224241235
[I 2024-04-15 15:31:54,269] Trial 36 finished with value: 0.2346108734594643 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.9283967702859293, 'max_features': None, 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24997063012030987
Fold 2 IBS: 0.2078386271594619
Fold 3 IBS: 0.20989448943460737
Fold 4 IBS: 0.24318967810983624
Fold 5 IBS: 0.238822753205723
[I 2024-04-15 15:32:02,166] Trial 37 finished with value: 0.2299432356059877 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.9519656907534663, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2901382904665285}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2242535688456211
Fold 2 IBS: 0.1835976049907044
Fold 3 IBS: 0.24006744858339077
Fold 4 IBS: 0.2235128017867808
Fold 5 IBS: 0.22345167433335356
[I 2024-04-15 15:32:36,767] Trial 38 finished with value: 0.21897661970797017 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.9965207390496469, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23157459496934288
Fold 2 IBS: 0.18765821400732335
Fold 3 IBS: 0.23782361687183054
Fold 4 IBS: 0.22923755805304355
Fold 5 IBS: 0.2226986259210817
[I 2024-04-15 15:33:11,781] Trial 39 finished with value: 0.22179852196452438 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 315, 'oob_score': True, 'max_samples': 0.8226899286526288, 'max_features': None, 'min_weight_fraction_leaf': 0.27840143846809673}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24772435188079012
Fold 2 IBS: 0.23218742086626878
Fold 3 IBS: 0.23060758736791892
Fold 4 IBS: 0.24175508770731288
Fold 5 IBS: 0.23204474443418183
[I 2024-04-15 15:33:12,985] Trial 40 finished with value: 0.2368638384512945 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.16382436256125943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36813487751721063}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22646081504264082
Fold 2 IBS: 0.18352119126570954
Fold 3 IBS: 0.23607995696737102
Fold 4 IBS: 0.21251526662938883
Fold 5 IBS: 0.21424323342983828
[I 2024-04-15 15:34:15,473] Trial 41 finished with value: 0.2145640926669897 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9105281334242562, 'max_features': None, 'min_weight_fraction_leaf': 0.24475563110472928}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22512255917446478
Fold 2 IBS: 0.18727107285974057
Fold 3 IBS: 0.23758193335679487
Fold 4 IBS: 0.22054856422751146
Fold 5 IBS: 0.21988197787741465
[I 2024-04-15 15:34:59,502] Trial 42 finished with value: 0.21808122149918527 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.9045942155546295, 'max_features': None, 'min_weight_fraction_leaf': 0.293296028878736}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22785829875013436
Fold 2 IBS: 0.1842888166183638
Fold 3 IBS: 0.23563786567766842
Fold 4 IBS: 0.21517434047682332
Fold 5 IBS: 0.21460776387587385
[I 2024-04-15 15:35:44,767] Trial 43 finished with value: 0.21551341707977273 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 226, 'oob_score': True, 'max_samples': 0.9160948796372946, 'max_features': None, 'min_weight_fraction_leaf': 0.2388357123656987}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23810518869034208
Fold 2 IBS: 0.1843721717295676
Fold 3 IBS: 0.23342725534028747
Fold 4 IBS: 0.21779527198626983
Fold 5 IBS: 0.21338570246212432
[I 2024-04-15 15:36:47,899] Trial 44 finished with value: 0.21741711804171823 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9988079160976218, 'max_features': None, 'min_weight_fraction_leaf': 0.23133379029564993}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24904499381879106
Fold 2 IBS: 0.20204509565526388
Fold 3 IBS: 0.20022838751714556
Fold 4 IBS: 0.23851054900878854
Fold 5 IBS: 0.23279491046703293
[I 2024-04-15 15:36:55,463] Trial 45 finished with value: 0.22452478729340442 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.9588472996756688, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18865904360845076}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24662415636936666
Fold 2 IBS: 0.23216017809371517
Fold 3 IBS: 0.22953538377216462
Fold 4 IBS: 0.24149330032507219
Fold 5 IBS: 0.23025831018946888
[I 2024-04-15 15:37:03,752] Trial 46 finished with value: 0.23601426574995749 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.8112705796698418, 'max_features': None, 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.25552189189917673
Fold 2 IBS: 0.21243741065140562
Fold 3 IBS: 0.20983624353493957
Fold 4 IBS: 0.2501169181827278
Fold 5 IBS: 0.24162763102811574
[I 2024-04-15 15:37:10,032] Trial 47 finished with value: 0.2339080190592731 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.5997619529984042, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20625108164370973}. Best is trial 32 with value: 0.2138632938455481.

Fold 1 IBS: 0.23136140224576346
Fold 2 IBS: 0.1874927380948624
Fold 3 IBS: 0.2417750554443432
Fold 4 IBS: 0.2265069844402473
Fold 5 IBS: 0.2218959262967509
[I 2024-04-15 15:37:54,995] Trial 48 finished with value: 0.22180642130439346 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.9047670799898727, 'max_features': None, 'min_weight_fraction_leaf': 0.31310643491678164}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23542420632037062
Fold 2 IBS: 0.21022618815946087
Fold 3 IBS: 0.24786241576097612
Fold 4 IBS: 0.24693634633915879
Fold 5 IBS: 0.2275366959349153
[I 2024-04-15 15:38:03,793] Trial 49 finished with value: 0.23359717050297632 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 126, 'oob_score': True, 'max_samples': 0.7434493023402162, 'max_features': None, 'min_weight_fraction_leaf': 0.34264283218926966}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23364784563499447
Fold 2 IBS: 0.18098882068519936
Fold 3 IBS: 0.2350992433083844
Fold 4 IBS: 0.21486677801910797
Fold 5 IBS: 0.2122163265393306
[I 2024-04-15 15:38:57,678] Trial 50 finished with value: 0.21536380283740336 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.966289849683488, 'max_features': None, 'min_weight_fraction_leaf': 0.24268176580480855}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22436028360824464
Fold 2 IBS: 0.18390356277663142
Fold 3 IBS: 0.24040787615783354
Fold 4 IBS: 0.2104444204732873
Fold 5 IBS: 0.2135145412249106
[I 2024-04-15 15:39:45,045] Trial 51 finished with value: 0.2145261368481815 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.9661981965193748, 'max_features': None, 'min_weight_fraction_leaf': 0.27303633084997875}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2252632186123346
Fold 2 IBS: 0.18280170060531284
Fold 3 IBS: 0.2396686796063755
Fold 4 IBS: 0.21225825839404486
Fold 5 IBS: 0.21297157585520618
[I 2024-04-15 15:40:36,403] Trial 52 finished with value: 0.2145926866146548 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.9702010352389128, 'max_features': None, 'min_weight_fraction_leaf': 0.26818547406558596}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22521714505468243
Fold 2 IBS: 0.182881821769254
Fold 3 IBS: 0.23887251200621484
Fold 4 IBS: 0.21098252365766934
Fold 5 IBS: 0.21218782440315603
[I 2024-04-15 15:41:33,477] Trial 53 finished with value: 0.2140283653781953 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': None, 'min_weight_fraction_leaf': 0.2659202981850255}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2288718138261306
Fold 2 IBS: 0.18971765755649445
Fold 3 IBS: 0.2436361411190432
Fold 4 IBS: 0.22404777390437705
Fold 5 IBS: 0.22115647006408712
[I 2024-04-15 15:42:07,741] Trial 54 finished with value: 0.22148597129402647 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.8733859823018522, 'max_features': None, 'min_weight_fraction_leaf': 0.3170010700434733}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24707867175507572
Fold 2 IBS: 0.20400595446700628
Fold 3 IBS: 0.20812199158224806
Fold 4 IBS: 0.24190537559582556
Fold 5 IBS: 0.23834032306907496
[I 2024-04-15 15:42:19,810] Trial 55 finished with value: 0.22789046329384616 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.9265797304840281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27178576234176444}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23358367222638146
Fold 2 IBS: 0.18201458388431307
Fold 3 IBS: 0.23354682388930173
Fold 4 IBS: 0.21827492745636595
Fold 5 IBS: 0.2174501839109653
[I 2024-04-15 15:43:06,662] Trial 56 finished with value: 0.2169740382734655 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.8271936729281781, 'max_features': None, 'min_weight_fraction_leaf': 0.21285363084866435}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24664286749698494
Fold 2 IBS: 0.23225796139026453
Fold 3 IBS: 0.23001805269887293
Fold 4 IBS: 0.2412163600405613
Fold 5 IBS: 0.23037050773431045
[I 2024-04-15 15:43:13,095] Trial 57 finished with value: 0.23610114987219885 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 253, 'oob_score': True, 'max_samples': 0.26646127666984304, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17410739253633356}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.21999582778399657
Fold 2 IBS: 0.18387448686713245
Fold 3 IBS: 0.2408870330246256
Fold 4 IBS: 0.2166454642557191
Fold 5 IBS: 0.21730499351649227
[I 2024-04-15 15:44:04,037] Trial 58 finished with value: 0.2157415610895932 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.9686958687236764, 'max_features': None, 'min_weight_fraction_leaf': 0.30665516095412265}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24647772834133322
Fold 2 IBS: 0.23233396372684292
Fold 3 IBS: 0.2294105260186355
Fold 4 IBS: 0.24141830856202007
Fold 5 IBS: 0.23032989167367704
[I 2024-04-15 15:44:08,256] Trial 59 finished with value: 0.23599408366450175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.46177802758610575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.276444308199004}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23433608338988485
Fold 2 IBS: 0.18086918993235046
Fold 3 IBS: 0.23079999563465167
Fold 4 IBS: 0.21893548105514982
Fold 5 IBS: 0.21460155169943457
[I 2024-04-15 15:44:50,034] Trial 60 finished with value: 0.21590846034229427 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.88571367758948, 'max_features': None, 'min_weight_fraction_leaf': 0.21876290259338138}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2271430274533492
Fold 2 IBS: 0.1825162975453381
Fold 3 IBS: 0.23705040332469834
Fold 4 IBS: 0.21597892749853137
Fold 5 IBS: 0.21278677650981948
[I 2024-04-15 15:45:48,398] Trial 61 finished with value: 0.21509508646634729 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.9830894754716849, 'max_features': None, 'min_weight_fraction_leaf': 0.2553034187460287}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2292111984043628
Fold 2 IBS: 0.18182025355984485
Fold 3 IBS: 0.2362968817681646
Fold 4 IBS: 0.21421475225136127
Fold 5 IBS: 0.21149289369260849
[I 2024-04-15 15:46:45,811] Trial 62 finished with value: 0.21460719593526845 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.9708671292273213, 'max_features': None, 'min_weight_fraction_leaf': 0.243826357699726}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.26397277962706595
Fold 2 IBS: 0.19043375797576154
Fold 3 IBS: 0.22492565723072697
Fold 4 IBS: 0.23088387847598388
Fold 5 IBS: 0.2172622642768575
[I 2024-04-15 15:48:14,466] Trial 63 finished with value: 0.22549566751727917 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.9279480291246802, 'max_features': None, 'min_weight_fraction_leaf': 0.14120968912579035}. Best is trial 32 with value: 0.2138632938455481.

Fold 1 IBS: 0.23011155909129694
Fold 2 IBS: 0.18057364325153813
Fold 3 IBS: 0.23750151803668482
Fold 4 IBS: 0.21433948253554103
Fold 5 IBS: 0.21274097244510462
[I 2024-04-15 15:48:59,831] Trial 64 finished with value: 0.2150534350720331 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.9368121127684691, 'max_features': None, 'min_weight_fraction_leaf': 0.24195064098385735}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22994947133324334
Fold 2 IBS: 0.1928070595691341
Fold 3 IBS: 0.24608508712178995
Fold 4 IBS: 0.22580322695561086
Fold 5 IBS: 0.2205885428532394
[I 2024-04-15 15:49:32,387] Trial 65 finished with value: 0.2230466775666035 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.8670083844909762, 'max_features': None, 'min_weight_fraction_leaf': 0.32908421267758453}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22282130602573708
Fold 2 IBS: 0.1825701777954383
Fold 3 IBS: 0.24054010901980605
Fold 4 IBS: 0.21149946893211913
Fold 5 IBS: 0.21290931251383843
[I 2024-04-15 15:50:19,243] Trial 66 finished with value: 0.21406807485738782 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.9739982448849115, 'max_features': None, 'min_weight_fraction_leaf': 0.27071128725769533}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22590163939661623
Fold 2 IBS: 0.18763036929293417
Fold 3 IBS: 0.23854879484973543
Fold 4 IBS: 0.22056476346670456
Fold 5 IBS: 0.22367179941618776
[I 2024-04-15 15:51:01,735] Trial 67 finished with value: 0.21926347328443568 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.9017852762499756, 'max_features': None, 'min_weight_fraction_leaf': 0.29638943195223827}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23136468046650185
Fold 2 IBS: 0.19058356934507797
Fold 3 IBS: 0.23833656743867954
Fold 4 IBS: 0.2260246145182696
Fold 5 IBS: 0.22338377590240932
[I 2024-04-15 15:51:31,750] Trial 68 finished with value: 0.22193864153418766 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.7696006508928359, 'max_features': None, 'min_weight_fraction_leaf': 0.26921258161170186}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2527256482936472
Fold 2 IBS: 0.21679849351270158
Fold 3 IBS: 0.21558977655347453
Fold 4 IBS: 0.24870257487026431
Fold 5 IBS: 0.24051841598268586
[I 2024-04-15 15:51:38,370] Trial 69 finished with value: 0.2348669818425547 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 241, 'oob_score': True, 'max_samples': 0.8533920767500149, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3499623676247436}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.25019298453625666
Fold 2 IBS: 0.20750360226472647
Fold 3 IBS: 0.20963562065872504
Fold 4 IBS: 0.24625738052286109
Fold 5 IBS: 0.245388802984381
[I 2024-04-15 15:51:47,178] Trial 70 finished with value: 0.23179567819339003 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.9455441938181584, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19781823294342465}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23916946073214723
Fold 2 IBS: 0.1832292263840008
Fold 3 IBS: 0.23266918697690725
Fold 4 IBS: 0.21704804409245781
Fold 5 IBS: 0.2114516013799994
[I 2024-04-15 15:52:45,020] Trial 71 finished with value: 0.2167135039131025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.9723894444805646, 'max_features': None, 'min_weight_fraction_leaf': 0.22155373862891511}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22202847435988357
Fold 2 IBS: 0.18246590811570426
Fold 3 IBS: 0.24166105453781217
Fold 4 IBS: 0.212036850127337
Fold 5 IBS: 0.21320739007819955
[I 2024-04-15 15:53:30,340] Trial 72 finished with value: 0.2142799354437873 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.9699475769300351, 'max_features': None, 'min_weight_fraction_leaf': 0.28091267570651296}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22381886258218625
Fold 2 IBS: 0.18341926141721807
Fold 3 IBS: 0.23660704072083516
Fold 4 IBS: 0.212065367907901
Fold 5 IBS: 0.2141596670219456
[I 2024-04-15 15:54:04,759] Trial 73 finished with value: 0.21401403993001722 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 209, 'oob_score': True, 'max_samples': 0.9437791774466985, 'max_features': None, 'min_weight_fraction_leaf': 0.2821774369800084}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22477243133843341
Fold 2 IBS: 0.18774509568370273
Fold 3 IBS: 0.23965261185226014
Fold 4 IBS: 0.21922686154498106
Fold 5 IBS: 0.21886501300305408
[I 2024-04-15 15:54:38,519] Trial 74 finished with value: 0.21805240268448628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.895983842618794, 'max_features': None, 'min_weight_fraction_leaf': 0.28336470892687904}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22159535901907498
Fold 2 IBS: 0.18203242370099715
Fold 3 IBS: 0.2396122755727472
Fold 4 IBS: 0.2119122627533289
Fold 5 IBS: 0.22253785258960063
[I 2024-04-15 15:54:49,108] Trial 75 finished with value: 0.21553803472714977 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.9389659866027312, 'max_features': None, 'min_weight_fraction_leaf': 0.3050734094630049}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2264441828875602
Fold 2 IBS: 0.1853863661466383
Fold 3 IBS: 0.2359088651478127
Fold 4 IBS: 0.213294084617616
Fold 5 IBS: 0.21449974952765222
[I 2024-04-15 15:55:26,437] Trial 76 finished with value: 0.2151066496654559 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.9176234080585466, 'max_features': None, 'min_weight_fraction_leaf': 0.25300132487456545}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22821719305891985
Fold 2 IBS: 0.19508870828251132
Fold 3 IBS: 0.24578664455005625
Fold 4 IBS: 0.23032276258951812
Fold 5 IBS: 0.22195983270626185
[I 2024-04-15 15:55:52,104] Trial 77 finished with value: 0.2242750282374535 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.8309240388435434, 'max_features': None, 'min_weight_fraction_leaf': 0.3232036043987994}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22380265214933034
Fold 2 IBS: 0.1828661444783246
Fold 3 IBS: 0.23976935208368666
Fold 4 IBS: 0.21451776173442463
Fold 5 IBS: 0.21232014327526896
[I 2024-04-15 15:56:52,778] Trial 78 finished with value: 0.21465521074420707 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.9974834884011105, 'max_features': None, 'min_weight_fraction_leaf': 0.285120853971619}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.24662475161103709
Fold 2 IBS: 0.23221194862348535
Fold 3 IBS: 0.2293559897432884
Fold 4 IBS: 0.24148847398075313
Fold 5 IBS: 0.23037769738743746
[I 2024-04-15 15:56:56,567] Trial 79 finished with value: 0.23601177226920028 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.5136803098501763, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2997540729188399}. Best is trial 32 with value: 0.2138632938455481.

Fold 1 IBS: 0.23374541142463764
Fold 2 IBS: 0.19941476694876598
Fold 3 IBS: 0.24370640781635464
Fold 4 IBS: 0.23069544004770481
Fold 5 IBS: 0.2221664668271361
[I 2024-04-15 15:57:22,555] Trial 80 finished with value: 0.22594569861291985 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.6585925147157417, 'max_features': None, 'min_weight_fraction_leaf': 0.2649590538103387}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.22301744452662423
Fold 2 IBS: 0.18261690178298304
Fold 3 IBS: 0.24046916847175354
Fold 4 IBS: 0.21144194863813523
Fold 5 IBS: 0.21301702675170428
[I 2024-04-15 15:58:10,653] Trial 81 finished with value: 0.21411249803424007 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 273, 'oob_score': True, 'max_samples': 0.9753152468491701, 'max_features': None, 'min_weight_fraction_leaf': 0.2752380404753649}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.23432065838648555
Fold 2 IBS: 0.17935299106705255
Fold 3 IBS: 0.23287366162210554
Fold 4 IBS: 0.21357871998202235
Fold 5 IBS: 0.2127544406967326
[I 2024-04-15 15:59:09,218] Trial 82 finished with value: 0.21457609435087974 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.9421283607559255, 'max_features': None, 'min_weight_fraction_leaf': 0.2317891236270332}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2217481350639258
Fold 2 IBS: 0.1833441422718802
Fold 3 IBS: 0.24075077787234164
Fold 4 IBS: 0.21240573900177895
Fold 5 IBS: 0.212962145560917
[I 2024-04-15 15:59:50,422] Trial 83 finished with value: 0.21424218795416872 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.975128242811779, 'max_features': None, 'min_weight_fraction_leaf': 0.2805682898149209}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2303654148623288
Fold 2 IBS: 0.18632824544920742
Fold 3 IBS: 0.2418858668034646
Fold 4 IBS: 0.22539197899863944
Fold 5 IBS: 0.22219697313636344
[I 2024-04-15 16:00:18,103] Trial 84 finished with value: 0.2212336958500007 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.976393308446703, 'max_features': None, 'min_weight_fraction_leaf': 0.34127480974218166}. Best is trial 32 with value: 0.2138632938455481.
Fold 1 IBS: 0.2217260340853898
Fold 2 IBS: 0.18277239975247972
Fold 3 IBS: 0.23833388730571414
Fold 4 IBS: 0.21017761467579527
Fold 5 IBS: 0.21345934539251293
[I 2024-04-15 16:00:58,067] Trial 85 finished with value: 0.21329385624237837 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.9536038002194676, 'max_features': None, 'min_weight_fraction_leaf': 0.28476239825926203}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.23346654290971627
Fold 2 IBS: 0.2002991033036751
Fold 3 IBS: 0.2512808526691761
Fold 4 IBS: 0.2347653219215522
Fold 5 IBS: 0.22181496462461447
[I 2024-04-15 16:01:15,387] Trial 86 finished with value: 0.2283253570857468 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.878162296740506, 'max_features': None, 'min_weight_fraction_leaf': 0.3634165889388582}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.2223728654927925
Fold 2 IBS: 0.18294920002029924
Fold 3 IBS: 0.2389860108327765
Fold 4 IBS: 0.21502599980642048
Fold 5 IBS: 0.21482469988941083
[I 2024-04-15 16:01:48,365] Trial 87 finished with value: 0.21483175520833991 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.9460445626426491, 'max_features': None, 'min_weight_fraction_leaf': 0.29153530938454547}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.25189061751540737
Fold 2 IBS: 0.21341558529621427
Fold 3 IBS: 0.2142420257944259
Fold 4 IBS: 0.2482136617352358
Fold 5 IBS: 0.24599208057977232
[I 2024-04-15 16:01:53,019] Trial 88 finished with value: 0.23475079418421113 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.9990689395046066, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31471651143310175}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.2500584415952907
Fold 2 IBS: 0.2031681904585751
Fold 3 IBS: 0.20589935356803593
Fold 4 IBS: 0.2415552908214951
Fold 5 IBS: 0.23589468400039715
[I 2024-04-15 16:01:58,481] Trial 89 finished with value: 0.22731519208875878 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.9170021204025709, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.25666952715359104}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.22122037857176746
Fold 2 IBS: 0.18393521442358685
Fold 3 IBS: 0.2391260037900019
Fold 4 IBS: 0.21395254322224747
Fold 5 IBS: 0.2134193298258829
[I 2024-04-15 16:02:34,387] Trial 90 finished with value: 0.2143306939666973 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.9820252833893551, 'max_features': None, 'min_weight_fraction_leaf': 0.2818679584030278}. Best is trial 85 with value: 0.21329385624237837.
Fold 1 IBS: 0.21897748548504423
Fold 2 IBS: 0.18188133545279256
Fold 3 IBS: 0.24000841253595037
Fold 4 IBS: 0.21074024798269958
Fold 5 IBS: 0.21382333454548527
[I 2024-04-15 16:03:11,059] Trial 91 finished with value: 0.21308616320039436 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9824332970054127, 'max_features': None, 'min_weight_fraction_leaf': 0.296758543375246}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.22239428604592235
Fold 2 IBS: 0.18362529902872812
Fold 3 IBS: 0.2380366548108467
Fold 4 IBS: 0.21518991075013066
Fold 5 IBS: 0.21578530509812716
[I 2024-04-15 16:03:46,855] Trial 92 finished with value: 0.21500629114675102 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.9578561789486436, 'max_features': None, 'min_weight_fraction_leaf': 0.30080999173299644}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.22288421426915914
Fold 2 IBS: 0.18356297300725574
Fold 3 IBS: 0.24008642933734997
Fold 4 IBS: 0.21300636044035706
Fold 5 IBS: 0.21479301188940397
[I 2024-04-15 16:04:34,251] Trial 93 finished with value: 0.21486659778870515 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 311, 'oob_score': True, 'max_samples': 0.9355442766768195, 'max_features': None, 'min_weight_fraction_leaf': 0.2800908308674908}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.28145174414363894
Fold 2 IBS: 0.19567185164243353
Fold 3 IBS: 0.2208118929008425
Fold 4 IBS: 0.2577007636885228
Fold 5 IBS: 0.23128096437104487
[I 2024-04-15 16:06:48,705] Trial 94 finished with value: 0.2373834433492965 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.8922990907187959, 'max_features': None, 'min_weight_fraction_leaf': 0.03451598429298541}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.2287195348815148
Fold 2 IBS: 0.185333284394746
Fold 3 IBS: 0.2407456148569622
Fold 4 IBS: 0.22444917263154276
Fold 5 IBS: 0.22301098555165416
[I 2024-04-15 16:07:22,964] Trial 95 finished with value: 0.22045171846328399 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.9810881228054685, 'max_features': None, 'min_weight_fraction_leaf': 0.3378600017645348}. Best is trial 91 with value: 0.21308616320039436.

Fold 1 IBS: 0.23083721945133412
Fold 2 IBS: 0.18442690744496573
Fold 3 IBS: 0.2372912055911599
Fold 4 IBS: 0.22822622495739184
Fold 5 IBS: 0.22366315254862057
[I 2024-04-15 16:07:51,287] Trial 96 finished with value: 0.22088894199869444 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 231, 'oob_score': True, 'max_samples': 0.9522685325324347, 'max_features': None, 'min_weight_fraction_leaf': 0.32080383117786954}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.2265678317463007
Fold 2 IBS: 0.18314595561796107
Fold 3 IBS: 0.2376073017283759
Fold 4 IBS: 0.21337826003109
Fold 5 IBS: 0.21787901230329237
[I 2024-04-15 16:08:15,497] Trial 97 finished with value: 0.21571567228540403 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.9189184529013809, 'max_features': None, 'min_weight_fraction_leaf': 0.2643468339626171}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.22122707712088582
Fold 2 IBS: 0.1831407811386645
Fold 3 IBS: 0.23729164843763267
Fold 4 IBS: 0.21684432910179788
Fold 5 IBS: 0.2181910343145583
[I 2024-04-15 16:08:49,310] Trial 98 finished with value: 0.21533897402270785 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.9822414266350423, 'max_features': None, 'min_weight_fraction_leaf': 0.3083148619586106}. Best is trial 91 with value: 0.21308616320039436.
Fold 1 IBS: 0.2469573580849604
Fold 2 IBS: 0.23227887605176312
Fold 3 IBS: 0.2296871483873879
Fold 4 IBS: 0.2412464104562029
Fold 5 IBS: 0.23029875993927082
[I 2024-04-15 16:08:54,616] Trial 99 finished with value: 0.236093710583917 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.3740305964247548, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2907257900715026}. Best is trial 91 with value: 0.21308616320039436.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.21308616320039436], datetime_start=datetime.datetime(2024, 4, 15, 16, 2, 34, 395701), datetime_complete=datetime.datetime(2024, 4, 15, 16, 3, 11, 58086), params={'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9824332970054127, 'max_features': None, 'min_weight_fraction_leaf': 0.296758543375246}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=91, value=None)


* Best Score for IBS:
 0.21308616320039436

In [53]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [54]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.213

#### Test

In [55]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [56]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=10,
                     max_samples=0.750348183174299, min_samples_leaf=2,
                     min_samples_split=16,
                     min_weight_fraction_leaf=0.09298348876429541,
                     n_estimators=267, random_state=123, warm_start=True)

test_cindex:  0.516

RandomSurvivalForest(max_depth=5, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9824332970054127, min_samples_split=10,
                     min_weight_fraction_leaf=0.296758543375246,
                     n_estimators=236, oob_score=True, random_state=123)

test_ibs:  0.258

In [57]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [58]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [59]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 16:09:26,885] A new study created in memory with name: no-name-82172fa8-bf44-48af-920d-28a3f3d9d084

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 16:09:28,593] Trial 0 finished with value: 0.6917221983343996 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.6917221983343996.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:09:33,600] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.6917221983343996.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5321888412017167
[I 2024-04-15 16:09:42,783] Trial 2 finished with value: 0.5962293873367364 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.6917221983343996.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 16:09:43,767] Trial 3 finished with value: 0.7116124583117144 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:09:46,827] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:09:50,151] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 16:09:52,096] Trial 6 finished with value: 0.6995413025653047 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.4866920152091255
Fold 5 C-index: 0.44206008583690987
[I 2024-04-15 16:09:56,372] Trial 7 finished with value: 0.5323002394051266 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.7116124583117144.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 16:09:56,710] Trial 8 finished with value: 0.7123582035090831 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.4206008583690987
[I 2024-04-15 16:10:05,637] Trial 9 finished with value: 0.5601421749368429 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:10:06,219] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.26413466171660194, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:10:06,824] Trial 11 finished with value: 0.6860067758400761 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:10:07,801] Trial 12 finished with value: 0.6935371374703161 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 147, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.630901287553648
[I 2024-04-15 16:10:08,607] Trial 13 finished with value: 0.682899730638463 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:10:08,998] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 24, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:10:10,113] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 193, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.40889055344541997}. Best is trial 8 with value: 0.7123582035090831.

Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:10:10,824] Trial 16 finished with value: 0.678961934888575 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.884183184043622, 'min_weight_fraction_leaf': 0.10581506507448754}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:10:11,795] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.37217752523657055, 'min_weight_fraction_leaf': 0.19947678741058694}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.4978540772532189
[I 2024-04-15 16:10:18,016] Trial 18 finished with value: 0.5851562203756214 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6674013857794929, 'min_weight_fraction_leaf': 0.0023155280568105674}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5665236051502146
[I 2024-04-15 16:10:18,679] Trial 19 finished with value: 0.639680291939225 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 61, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.35588501080184637}. Best is trial 8 with value: 0.7123582035090831.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 16:10:19,015] Trial 20 finished with value: 0.7286697682430041 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7140167187076433, 'min_weight_fraction_leaf': 0.28881891871571913}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.5930232558139535
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6931330472103004
[I 2024-04-15 16:10:19,400] Trial 21 finished with value: 0.6281398340612074 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 1, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.72756654854298, 'min_weight_fraction_leaf': 0.2803571345451082}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5622317596566524
[I 2024-04-15 16:10:20,443] Trial 22 finished with value: 0.6463647316394202 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 126, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5949128885273827, 'min_weight_fraction_leaf': 0.21042356171274518}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-15 16:10:21,039] Trial 23 finished with value: 0.6393477164536583 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 20, 'n_estimators': 42, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.838041538709398, 'min_weight_fraction_leaf': 0.3244245165936095}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 16:10:22,390] Trial 24 finished with value: 0.6624368746572411 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6696269191810152, 'min_weight_fraction_leaf': 0.07834890281902418}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.6705426356589147
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6266094420600858
[I 2024-04-15 16:10:23,116] Trial 25 finished with value: 0.6530529611997009 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 80, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9355023621313151, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.48406374501992033
Fold 2 C-index: 0.5310077519379846
Fold 3 C-index: 0.2936170212765957
Fold 4 C-index: 0.43346007604562736
Fold 5 C-index: 0.4742489270386266
[I 2024-04-15 16:10:23,750] Trial 26 finished with value: 0.4432795042637509 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 10, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7635558184229367, 'min_weight_fraction_leaf': 0.28408553405121756}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:10:24,257] Trial 27 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 52, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6191211952156661, 'min_weight_fraction_leaf': 0.37494346942158263}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.5836909871244635
[I 2024-04-15 16:10:25,736] Trial 28 finished with value: 0.6872248373859204 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4809640343327969, 'min_weight_fraction_leaf': 0.1961828142250625}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5836909871244635
[I 2024-04-15 16:10:26,908] Trial 29 finished with value: 0.6455250442442004 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 123, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7417740935442027, 'min_weight_fraction_leaf': 0.12619621560869665}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:10:28,276] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8156771314324496, 'min_weight_fraction_leaf': 0.4834576132281108}. Best is trial 20 with value: 0.7286697682430041.

Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:10:30,260] Trial 31 finished with value: 0.6801145932920232 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5225620293165905, 'min_weight_fraction_leaf': 0.0017285001202470562}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:10:32,469] Trial 32 finished with value: 0.6731579798996079 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.40903497082495127, 'min_weight_fraction_leaf': 0.04964430400379123}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6180257510729614
[I 2024-04-15 16:10:35,348] Trial 33 finished with value: 0.6707561487837669 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 496, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5725190768430576, 'min_weight_fraction_leaf': 0.09286432163882712}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5665236051502146
[I 2024-04-15 16:10:39,018] Trial 34 finished with value: 0.651579065949819 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 311, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.692312467902129, 'min_weight_fraction_leaf': 0.2580540326462687}. Best is trial 20 with value: 0.7286697682430041.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9098712446351931
[I 2024-04-15 16:10:42,045] Trial 35 finished with value: 0.8273038477014083 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6139772671629777, 'min_weight_fraction_leaf': 0.031778205287574995}. Best is trial 35 with value: 0.8273038477014083.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6437768240343348
[I 2024-04-15 16:10:54,765] Trial 36 finished with value: 0.6480077574259477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6351952857540998, 'min_weight_fraction_leaf': 0.03700974784326052}. Best is trial 35 with value: 0.8273038477014083.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9055793991416309
[I 2024-04-15 16:10:57,438] Trial 37 finished with value: 0.8314649783704071 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9232804028192897, 'min_weight_fraction_leaf': 0.07315854643139896}. Best is trial 37 with value: 0.8314649783704071.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9184549356223176
[I 2024-04-15 16:11:01,191] Trial 38 finished with value: 0.8435364145387766 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.0720411751470438}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6094420600858369
[I 2024-04-15 16:11:21,166] Trial 39 finished with value: 0.6593295748203326 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 395, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9312981316255384, 'min_weight_fraction_leaf': 0.07199443797246757}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-15 16:11:26,363] Trial 40 finished with value: 0.8372310545873379 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8565277718167947, 'min_weight_fraction_leaf': 0.025228712838995082}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-15 16:11:32,937] Trial 41 finished with value: 0.8427438869787027 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9314016557131928, 'min_weight_fraction_leaf': 0.02357229400551586}. Best is trial 38 with value: 0.8435364145387766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:11:38,507] Trial 42 finished with value: 0.8452322380506629 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9931832032289135, 'min_weight_fraction_leaf': 0.021857102585575633}. Best is trial 42 with value: 0.8452322380506629.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:11:43,666] Trial 43 finished with value: 0.845177419705727 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 336, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9418670280136737, 'min_weight_fraction_leaf': 0.02619307363235266}. Best is trial 42 with value: 0.8452322380506629.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.944206008583691
[I 2024-04-15 16:11:48,843] Trial 44 finished with value: 0.8475319253205553 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9996718065698121, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 44 with value: 0.8475319253205553.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:11:53,273] Trial 45 finished with value: 0.8554052970665053 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9994357381031855, 'min_weight_fraction_leaf': 0.05293553566639882}. Best is trial 45 with value: 0.8554052970665053.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9356223175965666
[I 2024-04-15 16:11:57,899] Trial 46 finished with value: 0.8460640087589031 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9959608873895133, 'min_weight_fraction_leaf': 0.05633429748553375}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 16:12:12,391] Trial 47 finished with value: 0.6726723699158018 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 384, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9960245199191953, 'min_weight_fraction_leaf': 0.10909382046675528}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:12:20,046] Trial 48 finished with value: 0.8538116715684974 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 427, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9987007340889653, 'min_weight_fraction_leaf': 0.05223913002386616}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.927038626609442
[I 2024-04-15 16:12:27,541] Trial 49 finished with value: 0.8443804699558598 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9838637316061305, 'min_weight_fraction_leaf': 0.055846795385322806}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9356223175965666
[I 2024-04-15 16:12:36,149] Trial 50 finished with value: 0.8468392025573527 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9969024404165039, 'min_weight_fraction_leaf': 0.05441612766959897}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9055793991416309
[I 2024-04-15 16:12:42,699] Trial 51 finished with value: 0.8426018949867666 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 450, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9988785512322712, 'min_weight_fraction_leaf': 0.09586311629563926}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.927038626609442
[I 2024-04-15 16:12:48,660] Trial 52 finished with value: 0.8460499654852054 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 408, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9603679595472577, 'min_weight_fraction_leaf': 0.06068477683436807}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-15 16:12:54,604] Trial 53 finished with value: 0.8493455916559528 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8984329851688493, 'min_weight_fraction_leaf': 0.05734643060318976}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8454935622317596
[I 2024-04-15 16:12:59,735] Trial 54 finished with value: 0.7972039323711585 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8997172683692978, 'min_weight_fraction_leaf': 0.15252836878533196}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 16:13:03,670] Trial 55 finished with value: 0.6622275124096364 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9099574607745866, 'min_weight_fraction_leaf': 0.11358880135617166}. Best is trial 45 with value: 0.8554052970665053.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9484978540772532
[I 2024-04-15 16:13:10,956] Trial 56 finished with value: 0.8564559108911997 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9671125170349901, 'min_weight_fraction_leaf': 0.05014189723990748}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 16:13:15,709] Trial 57 finished with value: 0.7420733376800305 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 497, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8480419506123976, 'min_weight_fraction_leaf': 0.08434869363890837}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9527896995708155
[I 2024-04-15 16:13:23,383] Trial 58 finished with value: 0.8562924469636007 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9618123713667476, 'min_weight_fraction_leaf': 0.04422578178543493}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.5321888412017167
[I 2024-04-15 16:13:36,608] Trial 59 finished with value: 0.5983611985032647 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9640017924847067, 'min_weight_fraction_leaf': 0.010404728780784564}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9527896995708155
[I 2024-04-15 16:13:45,835] Trial 60 finished with value: 0.8549743684786726 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8853359821635006, 'min_weight_fraction_leaf': 0.04449622014546582}. Best is trial 56 with value: 0.8564559108911997.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.944206008583691
[I 2024-04-15 16:13:52,470] Trial 61 finished with value: 0.8485600725085831 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 427, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8869448008091242, 'min_weight_fraction_leaf': 0.04303373540903084}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8798283261802575
[I 2024-04-15 16:13:57,908] Trial 62 finished with value: 0.8236094248173009 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 427, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8809845326168647, 'min_weight_fraction_leaf': 0.0946809905397768}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.944206008583691
[I 2024-04-15 16:14:05,189] Trial 63 finished with value: 0.8524213039761458 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9613756594129235, 'min_weight_fraction_leaf': 0.04313732124940366}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-15 16:14:11,753] Trial 64 finished with value: 0.849139303656273 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 468, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9643305378246444, 'min_weight_fraction_leaf': 0.040999627212704635}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9055793991416309
[I 2024-04-15 16:14:17,884] Trial 65 finished with value: 0.8299214721993768 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 480, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8332638017309197, 'min_weight_fraction_leaf': 0.009769007432165765}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7510729613733905
[I 2024-04-15 16:14:22,653] Trial 66 finished with value: 0.7410452410661378 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 460, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.06559182297622389}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.5879828326180258
[I 2024-04-15 16:14:26,665] Trial 67 finished with value: 0.6577298855923839 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 415, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9579652192705116, 'min_weight_fraction_leaf': 0.14244476766374436}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 16:14:31,518] Trial 68 finished with value: 0.743033894778593 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7943070081319523, 'min_weight_fraction_leaf': 0.08362003429822154}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 16:14:35,599] Trial 69 finished with value: 0.7347432644495872 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 386, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9076237691477275, 'min_weight_fraction_leaf': 0.11232995852145324}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:14:41,282] Trial 70 finished with value: 0.8469223778576156 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8593570128906675, 'min_weight_fraction_leaf': 0.04617252859484205}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9313304721030042
[I 2024-04-15 16:14:48,910] Trial 71 finished with value: 0.8524822994819349 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 463, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9564301458275928, 'min_weight_fraction_leaf': 0.04053709699857146}. Best is trial 56 with value: 0.8564559108911997.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9429657794676806
Fold 5 C-index: 0.9527896995708155
[I 2024-04-15 16:14:58,941] Trial 72 finished with value: 0.8585484724893282 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9533554910566981, 'min_weight_fraction_leaf': 0.01276054813110837}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:15:07,778] Trial 73 finished with value: 0.8516425292537818 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 486, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.953199330453136, 'min_weight_fraction_leaf': 0.000811259515634365}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.9186046511627907
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.9527896995708155
[I 2024-04-15 16:15:18,631] Trial 74 finished with value: 0.8489293113396391 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 457, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9540701793746674, 'min_weight_fraction_leaf': 0.018624119914381707}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9570815450643777
[I 2024-04-15 16:15:27,048] Trial 75 finished with value: 0.8547603778153011 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 489, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9193672578433386, 'min_weight_fraction_leaf': 0.03687267406592508}. Best is trial 72 with value: 0.8585484724893282.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 16:15:55,347] Trial 76 finished with value: 0.649409325772972 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 488, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9158386587581989, 'min_weight_fraction_leaf': 0.0343251877694847}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9055793991416309
[I 2024-04-15 16:16:02,148] Trial 77 finished with value: 0.829830864643354 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8258345559974801, 'min_weight_fraction_leaf': 0.01395770005472189}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:16:06,329] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8681542805446814, 'min_weight_fraction_leaf': 0.4401997700779695}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.6434108527131783
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.5209125475285171
Fold 5 C-index: 0.5150214592274678
[I 2024-04-15 16:16:10,060] Trial 79 finished with value: 0.5769641655871446 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.2054681425917101, 'min_weight_fraction_leaf': 0.07414727613797192}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8884120171673819
[I 2024-04-15 16:16:16,742] Trial 80 finished with value: 0.8328267085854719 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 483, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9737878727725551, 'min_weight_fraction_leaf': 0.10081614006934195}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9570815450643777
[I 2024-04-15 16:16:25,547] Trial 81 finished with value: 0.857947628811317 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9353221320314016, 'min_weight_fraction_leaf': 0.03644151510428387}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.9108527131782945
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.9484978540772532
[I 2024-04-15 16:16:34,573] Trial 82 finished with value: 0.8569333714618624 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9351113009157849, 'min_weight_fraction_leaf': 0.03389522493578406}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-15 16:16:42,141] Trial 83 finished with value: 0.8436158654940284 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9244943232738438, 'min_weight_fraction_leaf': 0.0645148338511949}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.944206008583691
[I 2024-04-15 16:16:49,119] Trial 84 finished with value: 0.8388929744398268 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7689103930415312, 'min_weight_fraction_leaf': 0.031240511172206175}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9098712446351931
[I 2024-04-15 16:16:55,668] Trial 85 finished with value: 0.8418707703412766 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9360008079217836, 'min_weight_fraction_leaf': 0.08022431143441006}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.944206008583691
[I 2024-04-15 16:17:00,114] Trial 86 finished with value: 0.8268296912264951 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 452, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8956736273636096, 'min_weight_fraction_leaf': 0.0021008342672814567}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-15 16:17:06,441] Trial 87 finished with value: 0.8542139122049083 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 393, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9757492788830231, 'min_weight_fraction_leaf': 0.013177844731090037}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.51931330472103
[I 2024-04-15 16:17:15,933] Trial 88 finished with value: 0.6020819734957581 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 401, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.869230052481604, 'min_weight_fraction_leaf': 0.013527919217184471}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9484978540772532
[I 2024-04-15 16:17:25,969] Trial 89 finished with value: 0.8573032503759761 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 489, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9796761451834832, 'min_weight_fraction_leaf': 0.029477074249114846}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8927038626609443
[I 2024-04-15 16:17:34,157] Trial 90 finished with value: 0.801853783072581 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 491, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9148186606025017, 'min_weight_fraction_leaf': 0.026231482250007713}. Best is trial 72 with value: 0.8585484724893282.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9484978540772532
[I 2024-04-15 16:17:41,986] Trial 91 finished with value: 0.851631796496067 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 476, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.977330549698534, 'min_weight_fraction_leaf': 0.034170399509268666}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9527896995708155
[I 2024-04-15 16:17:49,609] Trial 92 finished with value: 0.8428668726912847 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 454, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9372815834366508, 'min_weight_fraction_leaf': 0.013175088098699696}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.944206008583691
[I 2024-04-15 16:17:57,608] Trial 93 finished with value: 0.8524498043525692 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 467, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9806300653083163, 'min_weight_fraction_leaf': 0.04785150205265768}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:18:04,007] Trial 94 finished with value: 0.8539749920749997 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9370811219597744, 'min_weight_fraction_leaf': 0.020386589499688558}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-15 16:18:11,196] Trial 95 finished with value: 0.849139303656273 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8886989249819622, 'min_weight_fraction_leaf': 0.06855096582137163}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 16:18:15,636] Trial 96 finished with value: 0.6975795340855144 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 416, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9719284600548868, 'min_weight_fraction_leaf': 0.3157465264411285}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9055793991416309
[I 2024-04-15 16:18:22,069] Trial 97 finished with value: 0.8395632269725679 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 441, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9434948894242242, 'min_weight_fraction_leaf': 0.08853389895678439}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9313304721030042
[I 2024-04-15 16:18:28,982] Trial 98 finished with value: 0.8444815398616662 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 484, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9141730094207001, 'min_weight_fraction_leaf': 0.058717588979820705}. Best is trial 72 with value: 0.8585484724893282.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289

[I 2024-04-15 16:18:36,441] A new study created in memory with name: no-name-7eee249e-7b00-4ca9-a7f1-ddf776615f71

Fold 5 C-index: 0.9399141630901288
[I 2024-04-15 16:18:36,428] Trial 99 finished with value: 0.8444564769880605 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 405, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8453744927035851, 'min_weight_fraction_leaf': 0.03335954291144526}. Best is trial 72 with value: 0.8585484724893282.


* Best trial for C-index:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.8585484724893282], datetime_start=datetime.datetime(2024, 4, 15, 16, 14, 48, 916459), datetime_complete=datetime.datetime(2024, 4, 15, 16, 14, 58, 939721), params={'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9533554910566981, 'min_weight_fraction_leaf': 0.01276054813110837}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=72, value=None)


* Best Score for C-index:
 0.8585484724893282

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2516164991390209
Fold 2 IBS: 0.21850178124833985
Fold 3 IBS: 0.22086347781939733
Fold 4 IBS: 0.25088267027111183
Fold 5 IBS: 0.24153593571525953
[I 2024-04-15 16:18:41,954] Trial 0 finished with value: 0.23668007283862588 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.23668007283862588.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-15 16:18:50,257] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 1 with value: 0.2359075685671228.
Fold 1 IBS: 0.250106789783813
Fold 2 IBS: 0.21284765330505998
Fold 3 IBS: 0.21432751401307024
Fold 4 IBS: 0.24895944813780088
Fold 5 IBS: 0.2434714195977076
[I 2024-04-15 16:18:57,543] Trial 2 finished with value: 0.23394256496749036 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.25014536571335444
Fold 2 IBS: 0.2113825578010961
Fold 3 IBS: 0.2134335092754675
Fold 4 IBS: 0.25164350041840367
Fold 5 IBS: 0.2449472628259721
[I 2024-04-15 16:19:00,226] Trial 3 finished with value: 0.23431043920685876 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-15 16:19:06,486] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-15 16:19:10,338] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.25064410298449685
Fold 2 IBS: 0.21757261651937224
Fold 3 IBS: 0.21918674755082743
Fold 4 IBS: 0.24972493455649708
Fold 5 IBS: 0.24144716407743633
[I 2024-04-15 16:19:17,411] Trial 6 finished with value: 0.23571511313772597 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.2479608891120626
Fold 2 IBS: 0.22976152459854426
Fold 3 IBS: 0.22811801807306573
Fold 4 IBS: 0.24587396817268928
Fold 5 IBS: 0.2330748936121747
[I 2024-04-15 16:19:21,669] Trial 7 finished with value: 0.23695785871370728 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.2513075212583926
Fold 2 IBS: 0.21665466723740523
Fold 3 IBS: 0.2264150377759085
Fold 4 IBS: 0.24248571033147254
Fold 5 IBS: 0.24134107470803876
[I 2024-04-15 16:19:22,955] Trial 8 finished with value: 0.23564080226224351 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.2461078943343972
Fold 2 IBS: 0.23137874592699662
Fold 3 IBS: 0.22925096730946307
Fold 4 IBS: 0.24170305166953843
Fold 5 IBS: 0.23068341476751855
[I 2024-04-15 16:19:33,587] Trial 9 finished with value: 0.23582481480158277 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24599657914821219
Fold 2 IBS: 0.2321657424483506
Fold 3 IBS: 0.22973713994824324
Fold 4 IBS: 0.24123229752265593
Fold 5 IBS: 0.2305361660938366
[I 2024-04-15 16:19:44,904] Trial 10 finished with value: 0.2359335850322597 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24910663464632776
Fold 2 IBS: 0.21511500290964194
Fold 3 IBS: 0.21734691382471302
Fold 4 IBS: 0.2533192917655032
Fold 5 IBS: 0.24122186829493705
[I 2024-04-15 16:19:47,250] Trial 11 finished with value: 0.2352219422882246 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.25020483090588064
Fold 2 IBS: 0.2135745158819406
Fold 3 IBS: 0.21597697745716077
Fold 4 IBS: 0.2500325282615297
Fold 5 IBS: 0.24036191068102103
[I 2024-04-15 16:19:50,718] Trial 12 finished with value: 0.23403015263750654 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.23394256496749036.
Fold 1 IBS: 0.24742900358706432
Fold 2 IBS: 0.2296101524085416
Fold 3 IBS: 0.22194366434060078
Fold 4 IBS: 0.23373705912685125
Fold 5 IBS: 0.23557268199165743
[I 2024-04-15 16:19:51,285] Trial 13 finished with value: 0.2336585122909431 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.06483165374536849}. Best is trial 13 with value: 0.2336585122909431.
Fold 1 IBS: 0.24738256882467896
Fold 2 IBS: 0.2320970408821112
Fold 3 IBS: 0.22943176061214976
Fold 4 IBS: 0.24177377883723775
Fold 5 IBS: 0.22985649095814709
[I 2024-04-15 16:19:51,999] Trial 14 finished with value: 0.23610832802286494 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.3027798907108762, 'min_weight_fraction_leaf': 0.19322689159720335}. Best is trial 13 with value: 0.2336585122909431.

Fold 1 IBS: 0.247026504078842
Fold 2 IBS: 0.2195206957705492
Fold 3 IBS: 0.2123172789815588
Fold 4 IBS: 0.2479867211511746
Fold 5 IBS: 0.2387573651090091
[I 2024-04-15 16:19:56,865] Trial 15 finished with value: 0.23312171301822673 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 268, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3482433053809723, 'min_weight_fraction_leaf': 0.004357064532752621}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24701033455749313
Fold 2 IBS: 0.2322992796906955
Fold 3 IBS: 0.22982735187201522
Fold 4 IBS: 0.24119172674202158
Fold 5 IBS: 0.23034831988724866
[I 2024-04-15 16:20:01,068] Trial 16 finished with value: 0.23613540254989482 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.34033861208912675, 'min_weight_fraction_leaf': 0.010320253267333261}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24753685844322235
Fold 2 IBS: 0.23209067824437812
Fold 3 IBS: 0.22941552751394542
Fold 4 IBS: 0.24137850216356824
Fold 5 IBS: 0.23006657825042381
[I 2024-04-15 16:20:03,044] Trial 17 finished with value: 0.2360976289231076 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 97, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.13353756561046431, 'min_weight_fraction_leaf': 0.4058065513996202}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24661438736241653
Fold 2 IBS: 0.23234201038304025
Fold 3 IBS: 0.22985935061537058
Fold 4 IBS: 0.2412142155510644
Fold 5 IBS: 0.23028965352741476
[I 2024-04-15 16:20:10,021] Trial 18 finished with value: 0.2360639234878613 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.3062501142134034, 'min_weight_fraction_leaf': 0.16590566942711585}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24625016006407022
Fold 2 IBS: 0.2294322066721454
Fold 3 IBS: 0.22885619585099656
Fold 4 IBS: 0.24190838192064892
Fold 5 IBS: 0.23156021011301853
[I 2024-04-15 16:20:13,888] Trial 19 finished with value: 0.23560143092417593 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 224, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.38202098659284595, 'min_weight_fraction_leaf': 0.046399006012705586}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24701935315672957
Fold 2 IBS: 0.24163403136964587
Fold 3 IBS: 0.22856287289614435
Fold 4 IBS: 0.2454158941909801
Fold 5 IBS: 0.22954960363738028
[I 2024-04-15 16:20:14,350] Trial 20 finished with value: 0.23843635105017605 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.22426994530779043, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2526987825761896
Fold 2 IBS: 0.20999617961817782
Fold 3 IBS: 0.2128012813411989
Fold 4 IBS: 0.24657290453581146
Fold 5 IBS: 0.24462337536444018
[I 2024-04-15 16:20:19,671] Trial 21 finished with value: 0.2333385046871636 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 298, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.07272507805207075}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2506668391572938
Fold 2 IBS: 0.21369268617763446
Fold 3 IBS: 0.21491668461840335
Fold 4 IBS: 0.24630407943716084
Fold 5 IBS: 0.24359099128644837
[I 2024-04-15 16:20:25,035] Trial 22 finished with value: 0.23383425613538816 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 307, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.43242783612550895, 'min_weight_fraction_leaf': 0.0870783750535344}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24639083235051112
Fold 2 IBS: 0.22875193272128705
Fold 3 IBS: 0.22701295893713738
Fold 4 IBS: 0.24158101805780013
Fold 5 IBS: 0.23075841301544256
[I 2024-04-15 16:20:31,725] Trial 23 finished with value: 0.23489903101643567 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 378, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.242935508884002, 'min_weight_fraction_leaf': 0.017058739448196664}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2466493632370186
Fold 2 IBS: 0.23218552875928486
Fold 3 IBS: 0.23035547489183533
Fold 4 IBS: 0.24089209066138523
Fold 5 IBS: 0.22931154604505666
[I 2024-04-15 16:20:37,375] Trial 24 finished with value: 0.2358788007189161 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 296, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.10658832795558945, 'min_weight_fraction_leaf': 0.09530734460374185}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.2467045001129852
Fold 2 IBS: 0.23155617370579895
Fold 3 IBS: 0.22842966261666695
Fold 4 IBS: 0.2422095447426687
Fold 5 IBS: 0.2309733003608245
[I 2024-04-15 16:20:41,276] Trial 25 finished with value: 0.23597463630778887 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 229, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.04225085916833678}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24769388743290444
Fold 2 IBS: 0.223306248864412
Fold 3 IBS: 0.2234714023372094
Fold 4 IBS: 0.2483602602835835
Fold 5 IBS: 0.2343651435093372
[I 2024-04-15 16:20:44,661] Trial 26 finished with value: 0.2354393884854893 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5144377302955965, 'min_weight_fraction_leaf': 0.1711529803703364}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24655735930845069
Fold 2 IBS: 0.2322899069166581
Fold 3 IBS: 0.22962367540212245
Fold 4 IBS: 0.24142631754770405
Fold 5 IBS: 0.23015599331072079
[I 2024-04-15 16:20:50,611] Trial 27 finished with value: 0.23601065049713119 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.3606369716299986, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 15 with value: 0.23312171301822673.
Fold 1 IBS: 0.24743161351882595
Fold 2 IBS: 0.2105713848998565
Fold 3 IBS: 0.20850503871762688
Fold 4 IBS: 0.2464580313440729
Fold 5 IBS: 0.23766007235751133
[I 2024-04-15 16:20:55,839] Trial 28 finished with value: 0.2301252281675787 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 282, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4073796738200135, 'min_weight_fraction_leaf': 0.11808925884789895}. Best is trial 28 with value: 0.2301252281675787.
Fold 1 IBS: 0.23563608464325242
Fold 2 IBS: 0.19755231981376395
Fold 3 IBS: 0.20491272478230244
Fold 4 IBS: 0.22191144397261592
Fold 5 IBS: 0.22534015775427496
[I 2024-04-15 16:21:04,322] Trial 29 finished with value: 0.21707054619324193 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.1053491006372442}. Best is trial 29 with value: 0.21707054619324193.

Fold 1 IBS: 0.23497354688702718
Fold 2 IBS: 0.1976009711176378
Fold 3 IBS: 0.20496554854896726
Fold 4 IBS: 0.22195679558988315
Fold 5 IBS: 0.22437156955219212
[I 2024-04-15 16:21:13,544] Trial 30 finished with value: 0.21677368633914149 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 351, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8683525444021144, 'min_weight_fraction_leaf': 0.10877158322577073}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23741283004501632
Fold 2 IBS: 0.19660814788429976
Fold 3 IBS: 0.208320965032862
Fold 4 IBS: 0.22424875267364808
Fold 5 IBS: 0.22365262373167072
[I 2024-04-15 16:21:22,207] Trial 31 finished with value: 0.2180486638734994 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8840623748471775, 'min_weight_fraction_leaf': 0.11910827766006235}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23867714353974298
Fold 2 IBS: 0.19613128503421842
Fold 3 IBS: 0.2065931615501951
Fold 4 IBS: 0.22620631569035407
Fold 5 IBS: 0.2244866720296608
[I 2024-04-15 16:21:32,844] Trial 32 finished with value: 0.2184189155688343 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 345, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9077709187790539, 'min_weight_fraction_leaf': 0.12326015484904061}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23750771451305383
Fold 2 IBS: 0.19887399124028698
Fold 3 IBS: 0.20802968662686863
Fold 4 IBS: 0.2321566030510833
Fold 5 IBS: 0.22656014841579197
[I 2024-04-15 16:21:41,682] Trial 33 finished with value: 0.22062562876941696 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 342, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8925851586807815, 'min_weight_fraction_leaf': 0.2177627113802293}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.23602386733728492
Fold 2 IBS: 0.19703622328171574
Fold 3 IBS: 0.2080201955186778
Fold 4 IBS: 0.22565993281913133
Fold 5 IBS: 0.2264791911765019
[I 2024-04-15 16:21:52,758] Trial 34 finished with value: 0.21864388202666235 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.867135793861854, 'min_weight_fraction_leaf': 0.1628359603566048}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.239828670509377
Fold 2 IBS: 0.19423711438702101
Fold 3 IBS: 0.20557458285988647
Fold 4 IBS: 0.2221757496887524
Fold 5 IBS: 0.2277228560229509
[I 2024-04-15 16:22:06,191] Trial 35 finished with value: 0.21790779469359758 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8859357847621543, 'min_weight_fraction_leaf': 0.10801386112857586}. Best is trial 30 with value: 0.21677368633914149.
Fold 1 IBS: 0.236846255147437
Fold 2 IBS: 0.19741593771399701
Fold 3 IBS: 0.20176247981803738
Fold 4 IBS: 0.22648215967510524
Fold 5 IBS: 0.22131281080369278
[I 2024-04-15 16:22:18,768] Trial 36 finished with value: 0.2167639286316539 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 367, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7298125752042516, 'min_weight_fraction_leaf': 0.1067447453344346}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.24883806926954466
Fold 2 IBS: 0.22058928037323192
Fold 3 IBS: 0.2236201837711479
Fold 4 IBS: 0.24969298739504742
Fold 5 IBS: 0.23941939594400463
[I 2024-04-15 16:22:28,127] Trial 37 finished with value: 0.23643198335059532 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 448, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7251034382726446, 'min_weight_fraction_leaf': 0.09932761153057225}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.24254225881644262
Fold 2 IBS: 0.20924537127093926
Fold 3 IBS: 0.21388826462529725
Fold 4 IBS: 0.24163914739217005
Fold 5 IBS: 0.23436529764135527
[I 2024-04-15 16:22:38,323] Trial 38 finished with value: 0.2283360679492409 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8329175102327004, 'min_weight_fraction_leaf': 0.271489448036016}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23623751781761546
Fold 2 IBS: 0.19762564906135713
Fold 3 IBS: 0.20376748048384277
Fold 4 IBS: 0.2329799057171115
Fold 5 IBS: 0.2239426849990595
[I 2024-04-15 16:22:48,973] Trial 39 finished with value: 0.2189106476157973 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 395, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7214836794390458, 'min_weight_fraction_leaf': 0.15059751625410336}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23581677499948878
Fold 2 IBS: 0.20071634171128946
Fold 3 IBS: 0.20905634885165603
Fold 4 IBS: 0.23169075913239115
Fold 5 IBS: 0.22957242789722054
[I 2024-04-15 16:22:59,875] Trial 40 finished with value: 0.2213705305184092 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9262907745467319, 'min_weight_fraction_leaf': 0.22713324232248497}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.234951517307267
Fold 2 IBS: 0.2009582778749222
Fold 3 IBS: 0.20481196017912617
Fold 4 IBS: 0.2213589391492352
Fold 5 IBS: 0.22329994132329942
[I 2024-04-15 16:23:08,753] Trial 41 finished with value: 0.21707612716677 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8538474652324489, 'min_weight_fraction_leaf': 0.1108816675075643}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23472132563835466
Fold 2 IBS: 0.19810232111644868
Fold 3 IBS: 0.2078448660289595
Fold 4 IBS: 0.22651608628151707
Fold 5 IBS: 0.2252022991722336
[I 2024-04-15 16:23:17,419] Trial 42 finished with value: 0.21847737964750272 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8346872721633387, 'min_weight_fraction_leaf': 0.18586114486156524}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23676367561248174
Fold 2 IBS: 0.19660880411130277
Fold 3 IBS: 0.20141730960350246
Fold 4 IBS: 0.22944095726074634
Fold 5 IBS: 0.2205473063642598
[I 2024-04-15 16:23:27,271] Trial 43 finished with value: 0.2169556105904586 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 360, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7414559808390317, 'min_weight_fraction_leaf': 0.09878426797929674}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2500123198027997
Fold 2 IBS: 0.22061417393937463
Fold 3 IBS: 0.2226746084800549
Fold 4 IBS: 0.24928716600585524
Fold 5 IBS: 0.23925280304851704
[I 2024-04-15 16:23:39,939] Trial 44 finished with value: 0.23636821425532029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 404, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9992966624466928, 'min_weight_fraction_leaf': 0.05800083397743003}. Best is trial 36 with value: 0.2167639286316539.

Fold 1 IBS: 0.23322825812700776
Fold 2 IBS: 0.19980996308476648
Fold 3 IBS: 0.20366753393387363
Fold 4 IBS: 0.23327551134614005
Fold 5 IBS: 0.2261815525696507
[I 2024-04-15 16:23:53,942] Trial 45 finished with value: 0.2192325638122877 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 369, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7548177510477919, 'min_weight_fraction_leaf': 0.13669728117144694}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2465213089401209
Fold 2 IBS: 0.23046298845066793
Fold 3 IBS: 0.22971391168769142
Fold 4 IBS: 0.24253981917172043
Fold 5 IBS: 0.23157320473775703
[I 2024-04-15 16:24:02,634] Trial 46 finished with value: 0.23616224659759152 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8165105316363324, 'min_weight_fraction_leaf': 0.09410347152882448}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2392285685744128
Fold 2 IBS: 0.20301532499210856
Fold 3 IBS: 0.21068375666229217
Fold 4 IBS: 0.233734811370916
Fold 5 IBS: 0.23077502902161473
[I 2024-04-15 16:24:17,529] Trial 47 finished with value: 0.22348749812426885 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6150842738658111, 'min_weight_fraction_leaf': 0.14204359491488883}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2505808877528506
Fold 2 IBS: 0.21787837074644673
Fold 3 IBS: 0.21955621291869448
Fold 4 IBS: 0.2479106478038418
Fold 5 IBS: 0.24079437785769506
[I 2024-04-15 16:24:27,995] Trial 48 finished with value: 0.23534409941590573 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 423, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.698306943286806, 'min_weight_fraction_leaf': 0.02988689193434292}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.24656651844666427
Fold 2 IBS: 0.1973040995587005
Fold 3 IBS: 0.2000632083680002
Fold 4 IBS: 0.23461042669889007
Fold 5 IBS: 0.22362250203152442
[I 2024-04-15 16:24:46,600] Trial 49 finished with value: 0.2204333510207559 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7809927058547124, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23490052998563946
Fold 2 IBS: 0.19727678918732186
Fold 3 IBS: 0.20205967319247634
Fold 4 IBS: 0.22662398315892893
Fold 5 IBS: 0.22361282902817
[I 2024-04-15 16:24:57,256] Trial 50 finished with value: 0.21689476091050733 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 282, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9532766072292076, 'min_weight_fraction_leaf': 0.18032639031378228}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.23322434497515637
Fold 2 IBS: 0.19675858311595756
Fold 3 IBS: 0.20434076674333107
Fold 4 IBS: 0.2270264675864422
Fold 5 IBS: 0.22363090695751162
[I 2024-04-15 16:25:09,592] Trial 51 finished with value: 0.21699621387567974 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 317, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.18156728352333845}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2358482394775375
Fold 2 IBS: 0.1993862869046167
Fold 3 IBS: 0.20591034366560787
Fold 4 IBS: 0.22644548764098435
Fold 5 IBS: 0.22426799582500884
[I 2024-04-15 16:25:18,339] Trial 52 finished with value: 0.21837167070275107 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 243, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.956892699604465, 'min_weight_fraction_leaf': 0.208464530420868}. Best is trial 36 with value: 0.2167639286316539.
Fold 1 IBS: 0.2347102601084114
Fold 2 IBS: 0.19492132792654773
Fold 3 IBS: 0.20372340864817398
Fold 4 IBS: 0.22451053611946223
Fold 5 IBS: 0.22574160580247377
[I 2024-04-15 16:25:28,409] Trial 53 finished with value: 0.21672142772101383 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.17857938204264587}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2507202946006097
Fold 2 IBS: 0.21425933646897768
Fold 3 IBS: 0.22023122312992002
Fold 4 IBS: 0.24896399653157794
Fold 5 IBS: 0.24243791934696968
[I 2024-04-15 16:25:35,502] Trial 54 finished with value: 0.23532255401561103 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9561942993760734, 'min_weight_fraction_leaf': 0.18508357462091207}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24252706399447918
Fold 2 IBS: 0.2072249626266686
Fold 3 IBS: 0.21255447229272564
Fold 4 IBS: 0.23701845963835796
Fold 5 IBS: 0.23702019287199932
[I 2024-04-15 16:25:42,856] Trial 55 finished with value: 0.22726903028484613 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 201, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9239898991962526, 'min_weight_fraction_leaf': 0.2797861686064933}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2466322813274835
Fold 2 IBS: 0.22690874233166022
Fold 3 IBS: 0.22703003374851932
Fold 4 IBS: 0.24446208681134918
Fold 5 IBS: 0.23232754049354626
[I 2024-04-15 16:25:49,959] Trial 56 finished with value: 0.23547213694251173 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 287, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9759496491827552, 'min_weight_fraction_leaf': 0.3230607190970375}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23737375961186943
Fold 2 IBS: 0.19791239976321015
Fold 3 IBS: 0.20367326309929848
Fold 4 IBS: 0.22278621870777932
Fold 5 IBS: 0.22534031507623634
[I 2024-04-15 16:25:58,485] Trial 57 finished with value: 0.21741719125167874 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9332290664977184, 'min_weight_fraction_leaf': 0.1574532042482963}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24655767659985756
Fold 2 IBS: 0.23216890541138882
Fold 3 IBS: 0.22956973979229836
Fold 4 IBS: 0.2414720097528081
Fold 5 IBS: 0.23027659366606912
[I 2024-04-15 16:26:05,919] Trial 58 finished with value: 0.23600898504448437 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 324, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7570423536286393, 'min_weight_fraction_leaf': 0.47632691903364677}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24451651620865986
Fold 2 IBS: 0.21029443193844233
Fold 3 IBS: 0.21268401432755918
Fold 4 IBS: 0.241118850609694
Fold 5 IBS: 0.23692605047125703
[I 2024-04-15 16:26:11,872] Trial 59 finished with value: 0.22910797271112243 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 202, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7892943400374715, 'min_weight_fraction_leaf': 0.2531462312418419}. Best is trial 53 with value: 0.21672142772101383.

Fold 1 IBS: 0.24675120399960646
Fold 2 IBS: 0.2238312246331017
Fold 3 IBS: 0.22373605345231745
Fold 4 IBS: 0.24763583159134048
Fold 5 IBS: 0.2361001387256771
[I 2024-04-15 16:26:18,683] Trial 60 finished with value: 0.23561089048040867 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 259, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5876523474241502, 'min_weight_fraction_leaf': 0.18336534674120722}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24544383395694797
Fold 2 IBS: 0.19103401818321838
Fold 3 IBS: 0.1977979215082493
Fold 4 IBS: 0.2360015957855052
Fold 5 IBS: 0.22738640071735247
[I 2024-04-15 16:26:38,480] Trial 61 finished with value: 0.21953275403025466 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 363, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9817888741599827, 'min_weight_fraction_leaf': 0.08034824287701624}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23702043041145554
Fold 2 IBS: 0.1982882587017249
Fold 3 IBS: 0.20404836661294448
Fold 4 IBS: 0.22738765999634022
Fold 5 IBS: 0.22466910472549614
[I 2024-04-15 16:26:52,645] Trial 62 finished with value: 0.21828276408959227 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 309, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8169431607503741, 'min_weight_fraction_leaf': 0.14045762430272518}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23528690602923447
Fold 2 IBS: 0.20067887083049787
Fold 3 IBS: 0.20619313061129296
Fold 4 IBS: 0.22935101641955274
Fold 5 IBS: 0.22778974684575007
[I 2024-04-15 16:27:07,833] Trial 63 finished with value: 0.21985993414726565 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 384, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8541325292759324, 'min_weight_fraction_leaf': 0.20634205490826563}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24785243089638537
Fold 2 IBS: 0.191819411621147
Fold 3 IBS: 0.19595373736651736
Fold 4 IBS: 0.23396960581056234
Fold 5 IBS: 0.22817124135051
[I 2024-04-15 16:27:23,619] Trial 64 finished with value: 0.21955328540902438 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9474372485784143, 'min_weight_fraction_leaf': 0.05967166684837456}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2482913412046415
Fold 2 IBS: 0.2200836170862754
Fold 3 IBS: 0.22300947282774128
Fold 4 IBS: 0.24894456005276414
Fold 5 IBS: 0.23878529350646063
[I 2024-04-15 16:27:32,735] Trial 65 finished with value: 0.2358228569355766 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 335, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9068094061449172, 'min_weight_fraction_leaf': 0.23316652574301272}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23342652751464346
Fold 2 IBS: 0.20244094695682738
Fold 3 IBS: 0.2105886037120247
Fold 4 IBS: 0.2334597367833201
Fold 5 IBS: 0.23125038856804886
[I 2024-04-15 16:27:43,073] Trial 66 finished with value: 0.22223324070697292 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 355, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6873372044383822, 'min_weight_fraction_leaf': 0.17618672192654974}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.235741181115283
Fold 2 IBS: 0.19600302220181715
Fold 3 IBS: 0.20506229623259442
Fold 4 IBS: 0.22552096551242218
Fold 5 IBS: 0.22527819459965537
[I 2024-04-15 16:27:51,780] Trial 67 finished with value: 0.21752113193235445 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8641466001482349, 'min_weight_fraction_leaf': 0.16024471468098603}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2380009615179774
Fold 2 IBS: 0.2053057958310263
Fold 3 IBS: 0.20693833652356367
Fold 4 IBS: 0.23343099085304939
Fold 5 IBS: 0.23051644642343777
[I 2024-04-15 16:28:02,448] Trial 68 finished with value: 0.2228385062298109 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 313, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7454821099429565, 'min_weight_fraction_leaf': 0.1315028130600445}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23667050870598896
Fold 2 IBS: 0.19707337732587207
Fold 3 IBS: 0.20506243352245881
Fold 4 IBS: 0.22989927387001974
Fold 5 IBS: 0.2247802288452282
[I 2024-04-15 16:28:11,568] Trial 69 finished with value: 0.21869716445391357 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 227, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9115851507518807, 'min_weight_fraction_leaf': 0.19881342365516072}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24755217694573514
Fold 2 IBS: 0.23067103498005345
Fold 3 IBS: 0.22919268224306755
Fold 4 IBS: 0.24330350374086074
Fold 5 IBS: 0.23206289633690777
[I 2024-04-15 16:28:17,433] Trial 70 finished with value: 0.2365564588493249 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 296, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9734470555075896, 'min_weight_fraction_leaf': 0.1037315705497979}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23557800438634688
Fold 2 IBS: 0.19925421339611335
Fold 3 IBS: 0.2043473925891944
Fold 4 IBS: 0.22213902871913044
Fold 5 IBS: 0.2235128361033631
[I 2024-04-15 16:28:34,873] Trial 71 finished with value: 0.21696629503882964 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8402458676885415, 'min_weight_fraction_leaf': 0.11593845358143434}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23358834179947885
Fold 2 IBS: 0.19925797694578165
Fold 3 IBS: 0.20631707475676808
Fold 4 IBS: 0.22712164828983641
Fold 5 IBS: 0.22686739135241812
[I 2024-04-15 16:28:49,015] Trial 72 finished with value: 0.2186304866288566 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 359, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8022020419002074, 'min_weight_fraction_leaf': 0.12654108414074106}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23989628535126872
Fold 2 IBS: 0.19504918561347076
Fold 3 IBS: 0.20766848585539088
Fold 4 IBS: 0.2243318781250735
Fold 5 IBS: 0.2254076136840937
[I 2024-04-15 16:29:04,429] Trial 73 finished with value: 0.21847068972585953 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8883744161104976, 'min_weight_fraction_leaf': 0.08624238462675754}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24330205884039094
Fold 2 IBS: 0.1960859798288803
Fold 3 IBS: 0.20204615415341717
Fold 4 IBS: 0.22282852954588567
Fold 5 IBS: 0.22527092770084384
[I 2024-04-15 16:29:21,065] Trial 74 finished with value: 0.21790673001388358 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.868573691117867, 'min_weight_fraction_leaf': 0.11520344080447015}. Best is trial 53 with value: 0.21672142772101383.

Fold 1 IBS: 0.23878866729576506
Fold 2 IBS: 0.19862339947767513
Fold 3 IBS: 0.20582989519828723
Fold 4 IBS: 0.2244448023517984
Fold 5 IBS: 0.2249714920857591
[I 2024-04-15 16:29:31,292] Trial 75 finished with value: 0.218531651281857 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 284, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8355109212222066, 'min_weight_fraction_leaf': 0.1496381039654338}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24638426866097177
Fold 2 IBS: 0.22911008901873028
Fold 3 IBS: 0.22825388044344033
Fold 4 IBS: 0.2429147576831134
Fold 5 IBS: 0.2310867513895085
[I 2024-04-15 16:29:40,630] Trial 76 finished with value: 0.23554994943915286 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 402, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9497940527687874, 'min_weight_fraction_leaf': 0.3913116453285941}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23745526394695224
Fold 2 IBS: 0.19742171438125147
Fold 3 IBS: 0.20372559975892518
Fold 4 IBS: 0.22904263568439634
Fold 5 IBS: 0.22173120591021678
[I 2024-04-15 16:29:54,928] Trial 77 finished with value: 0.2178752839363484 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 416, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7166829789978312, 'min_weight_fraction_leaf': 0.050744524856922685}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24927476126128845
Fold 2 IBS: 0.208231400065323
Fold 3 IBS: 0.21411329384109026
Fold 4 IBS: 0.249376195146158
Fold 5 IBS: 0.24369864008356293
[I 2024-04-15 16:30:02,416] Trial 78 finished with value: 0.23293885807948453 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 341, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9995929035384165, 'min_weight_fraction_leaf': 0.08440337592244582}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24494208697141254
Fold 2 IBS: 0.2116349766712215
Fold 3 IBS: 0.21075545248518937
Fold 4 IBS: 0.24418992316803034
Fold 5 IBS: 0.23595455504395807
[I 2024-04-15 16:30:09,929] Trial 79 finished with value: 0.22949539886796236 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 260, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.03438361115836926}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2487177645255871
Fold 2 IBS: 0.2182024376115983
Fold 3 IBS: 0.22324181474860025
Fold 4 IBS: 0.24889042191015426
Fold 5 IBS: 0.2404752027074224
[I 2024-04-15 16:30:17,317] Trial 80 finished with value: 0.2359055283006725 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 303, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8351802467114298, 'min_weight_fraction_leaf': 0.17374014764047482}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2343225314915598
Fold 2 IBS: 0.20080169245493515
Fold 3 IBS: 0.2040616253448912
Fold 4 IBS: 0.2209705540772439
Fold 5 IBS: 0.22381309225452964
[I 2024-04-15 16:30:26,756] Trial 81 finished with value: 0.21679389912463196 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8534956380037706, 'min_weight_fraction_leaf': 0.10880420004471991}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23759152349495194
Fold 2 IBS: 0.19592371029252753
Fold 3 IBS: 0.2072471173483897
Fold 4 IBS: 0.22594602303280678
Fold 5 IBS: 0.22405057142534987
[I 2024-04-15 16:30:38,961] Trial 82 finished with value: 0.21815178911880512 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8879430516495728, 'min_weight_fraction_leaf': 0.09459448625969206}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.239412006571268
Fold 2 IBS: 0.19774448699778083
Fold 3 IBS: 0.20522840650133722
Fold 4 IBS: 0.22445007414910306
Fold 5 IBS: 0.2261834150707348
[I 2024-04-15 16:30:50,865] Trial 83 finished with value: 0.21860367785804477 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 319, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9171078906725617, 'min_weight_fraction_leaf': 0.1052694178484323}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23361013902960837
Fold 2 IBS: 0.2015645158386313
Fold 3 IBS: 0.20413401003241938
Fold 4 IBS: 0.2321092758761283
Fold 5 IBS: 0.22764703849196896
[I 2024-04-15 16:31:02,699] Trial 84 finished with value: 0.21981299585375128 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 389, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7724021984938093, 'min_weight_fraction_leaf': 0.12058904937847048}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23757837283796351
Fold 2 IBS: 0.19324227600096808
Fold 3 IBS: 0.20280434329037092
Fold 4 IBS: 0.22354307385378738
Fold 5 IBS: 0.22801046653333804
[I 2024-04-15 16:31:14,060] Trial 85 finished with value: 0.21703570650328557 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9360967058275064, 'min_weight_fraction_leaf': 0.07268375412116553}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.25429852555911403
Fold 2 IBS: 0.21033125981735631
Fold 3 IBS: 0.2144457109771278
Fold 4 IBS: 0.25078928838120385
Fold 5 IBS: 0.244029243928168
[I 2024-04-15 16:31:21,102] Trial 86 finished with value: 0.234778805732594 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 330, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9642478723292717, 'min_weight_fraction_leaf': 0.020071342516688462}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.23900122947698701
Fold 2 IBS: 0.19238827530037164
Fold 3 IBS: 0.20210857686800815
Fold 4 IBS: 0.22317247828149858
Fold 5 IBS: 0.22737872525252992
[I 2024-04-15 16:31:30,479] Trial 87 finished with value: 0.21680985703587904 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 287, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9378062713463992, 'min_weight_fraction_leaf': 0.06921252518565787}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24066267374743672
Fold 2 IBS: 0.20005464365592593
Fold 3 IBS: 0.20543574720731855
Fold 4 IBS: 0.22529042844516578
Fold 5 IBS: 0.2226325847112706
[I 2024-04-15 16:31:40,997] Trial 88 finished with value: 0.21881521555342354 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 270, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8097938703537855, 'min_weight_fraction_leaf': 0.13303674175829286}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2397255226432569
Fold 2 IBS: 0.19674577421997944
Fold 3 IBS: 0.2025535870258632
Fold 4 IBS: 0.2233994107103644
Fold 5 IBS: 0.22740149185929429
[I 2024-04-15 16:31:51,538] Trial 89 finished with value: 0.21796515729175164 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9038411335483634, 'min_weight_fraction_leaf': 0.14792768782183083}. Best is trial 53 with value: 0.21672142772101383.

Fold 1 IBS: 0.23711736196146355
Fold 2 IBS: 0.20354697260954158
Fold 3 IBS: 0.20782994592008056
Fold 4 IBS: 0.235467444322929
Fold 5 IBS: 0.23168859841356962
[I 2024-04-15 16:31:59,043] Trial 90 finished with value: 0.22313006464551685 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6267661705142946, 'min_weight_fraction_leaf': 0.049594043056366624}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24102633692552217
Fold 2 IBS: 0.19520843787050352
Fold 3 IBS: 0.20356979583511886
Fold 4 IBS: 0.2204498673203032
Fold 5 IBS: 0.22696028171118432
[I 2024-04-15 16:32:10,721] Trial 91 finished with value: 0.21744294393252642 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 304, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8764516242063105, 'min_weight_fraction_leaf': 0.06949247400851687}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2394456581845208
Fold 2 IBS: 0.19363296608081376
Fold 3 IBS: 0.20277200709317306
Fold 4 IBS: 0.22459551055765914
Fold 5 IBS: 0.22830612979748444
[I 2024-04-15 16:32:22,620] Trial 92 finished with value: 0.21775045434273022 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 318, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9282849654122768, 'min_weight_fraction_leaf': 0.09312093974775566}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24107663649118255
Fold 2 IBS: 0.19451636127706823
Fold 3 IBS: 0.1965711492060419
Fold 4 IBS: 0.22584943389286724
Fold 5 IBS: 0.22823990209005682
[I 2024-04-15 16:32:37,313] Trial 93 finished with value: 0.21725069659144336 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 364, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9366248318254733, 'min_weight_fraction_leaf': 0.07652785525625173}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24105686216374922
Fold 2 IBS: 0.19505291248840148
Fold 3 IBS: 0.19640882194624412
Fold 4 IBS: 0.2288940107406708
Fold 5 IBS: 0.22369797769916688
[I 2024-04-15 16:32:50,596] Trial 94 finished with value: 0.2170221170076465 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9884082516680452, 'min_weight_fraction_leaf': 0.0623917804702583}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24521510672904306
Fold 2 IBS: 0.19763188756514105
Fold 3 IBS: 0.19644604520830475
Fold 4 IBS: 0.22987163229002092
Fold 5 IBS: 0.22005226494605112
[I 2024-04-15 16:32:59,663] Trial 95 finished with value: 0.2178433873477122 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 217, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9876449779297782, 'min_weight_fraction_leaf': 0.05978166741958252}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.25390879773808833
Fold 2 IBS: 0.20687842930434625
Fold 3 IBS: 0.2105713027702558
Fold 4 IBS: 0.24770741927210513
Fold 5 IBS: 0.23922035669807637
[I 2024-04-15 16:33:07,731] Trial 96 finished with value: 0.23165726115657437 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9703508162412989, 'min_weight_fraction_leaf': 0.11329960994550745}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24645066542896663
Fold 2 IBS: 0.2314637521915939
Fold 3 IBS: 0.22914834885622082
Fold 4 IBS: 0.24244123532590717
Fold 5 IBS: 0.23154120313830437
[I 2024-04-15 16:33:14,179] Trial 97 finished with value: 0.2362090409881986 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8954049778074968, 'min_weight_fraction_leaf': 0.222319312129305}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.2515735242888121
Fold 2 IBS: 0.22016600057696184
Fold 3 IBS: 0.22601740987096489
Fold 4 IBS: 0.24872270235850708
Fold 5 IBS: 0.2409968879406772
[I 2024-04-15 16:33:21,417] Trial 98 finished with value: 0.23749530500718463 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9456683815838285, 'min_weight_fraction_leaf': 0.024625018226061307}. Best is trial 53 with value: 0.21672142772101383.
Fold 1 IBS: 0.24664731493553269
Fold 2 IBS: 0.23211622389871048
Fold 3 IBS: 0.2295272988305809
Fold 4 IBS: 0.24142243220002224
Fold 5 IBS: 0.22985380863864716
[I 2024-04-15 16:33:23,975] Trial 99 finished with value: 0.2359134157006987 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 101, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4622293227685943, 'min_weight_fraction_leaf': 0.260015152988917}. Best is trial 53 with value: 0.21672142772101383.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.21672142772101383], datetime_start=datetime.datetime(2024, 4, 15, 16, 25, 18, 347946), datetime_complete=datetime.datetime(2024, 4, 15, 16, 25, 28, 408480), params={'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.17857938204264587}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=53, value=None)


* Best Score for IBS:
 0.21672142772101383

In [60]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.859
train_ibs:  0.217

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=13, max_features=None, max_leaf_nodes=19,
                   max_samples=0.9533554910566981,
                   min_weight_fraction_leaf=0.01276054813110837,
                   n_estimators=487, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.506

ExtraSurvivalTrees(max_depth=6, max_features=None, max_leaf_nodes=18,
                   max_samples=0.9463423717095281, min_samples_leaf=4,
                   min_samples_split=14,
                   min_weight_fraction_leaf=0.17857938204264587,
                   n_estimators=273, oob_score=True, random_state=123)

IBS: 0.245

In [64]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 16:33:34,409] A new study created in memory with name: no-name-ba565b4f-4594-476b-a7c6-dc8233edf8c9

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:34:24,189] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:34:48,259] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:35:16,975] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:36:20,233] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:36:43,588] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:36:48,894] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:37:19,236] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:37:27,768] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:37:28,845] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 16:39:12,163] Trial 9 finished with value: 0.6859109422281264 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 16:41:55,853] Trial 10 finished with value: 0.670852196836783 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:44:47,213] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 16:47:09,399] Trial 12 finished with value: 0.685273555299404 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:48:05,999] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:49:30,155] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:51:05,055] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:51:52,738] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:53:35,073] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:56:07,470] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:56:17,493] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 16:57:21,236] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 16:59:25,268] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5987124463519313
[I 2024-04-15 17:01:13,468] Trial 22 finished with value: 0.6138909350684226 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:03:01,319] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:04:21,682] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:05:52,605] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:06:28,988] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:08:08,036] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:08:13,211] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:09:12,169] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:09:32,642] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5228136882129277
Fold 5 C-index: 0.6351931330472103
[I 2024-04-15 17:10:54,012] Trial 31 finished with value: 0.6148509290802949 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5836909871244635
[I 2024-04-15 17:12:27,259] Trial 32 finished with value: 0.5167381974248928 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.01975114074478268, 'dropout_rate': 0.17764317230563348, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.49980582609797874, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:13:28,996] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.6760798631992874, 'learning_rate': 0.016733063081788083, 'dropout_rate': 0.32837909362399287, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.42989559468897276, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:14:20,524] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6141580711713768, 'learning_rate': 0.010212728719320904, 'dropout_rate': 0.22658656718653286, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6478790211492356, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7336723985898187, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:15:09,191] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9093298201937425, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.15867077544658675, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 1.263860610757792, 'min_weight_fraction_leaf': 0.36922342323313606, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.90817362499676, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:16:18,291] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7085026268591493, 'learning_rate': 0.0070965351182087025, 'dropout_rate': 0.39089708764550957, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.452111635340179, 'max_features': 'auto', 'min_impurity_decrease': 8.009608651276614e-06, 'validation_fraction': 0.5741608239655631, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:16:59,753] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6150384198855655, 'learning_rate': 0.02319411108605052, 'dropout_rate': 0.518754641115737, 'n_estimators': 397, 'criterion': 'squared_error', 'ccp_alpha': 9.043731037372849, 'min_weight_fraction_leaf': 0.40980674893510094, 'max_features': None, 'min_impurity_decrease': 1.1019559650868866e-07, 'validation_fraction': 0.6250400217604171, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:17:17,834] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.7981565979476395, 'learning_rate': 0.015044404820943004, 'dropout_rate': 0.7673236646699829, 'n_estimators': 302, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5437276444738438, 'min_weight_fraction_leaf': 0.4820963556426466, 'max_features': 'auto', 'min_impurity_decrease': 2.617381555138236e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:17:59,615] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9493559030245647, 'learning_rate': 0.03768032434341392, 'dropout_rate': 0.2987814397752575, 'n_estimators': 359, 'criterion': 'squared_error', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.3277651563969065, 'max_features': 1, 'min_impurity_decrease': 9.83157196897088e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:19:44,749] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.8741100230454082, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 1.1160120003737553, 'min_weight_fraction_leaf': 0.2956774610913858, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.2951344544764216, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5170212765957447
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.5965665236051502
[I 2024-04-15 17:21:04,427] Trial 41 finished with value: 0.6053907873126554 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.007986867821304467, 'dropout_rate': 0.20634597744974018, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.45606967048955926, 'max_features': 'auto', 'min_impurity_decrease': 3.8623524982852286e-07, 'validation_fraction': 0.941559602035689, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:22:22,578] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.012554593902792077, 'dropout_rate': 0.21228719021921444, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.434317240875134, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:23:47,869] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.006577526474875964, 'dropout_rate': 0.3530314967142242, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.47972082857650694, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8059232630259225, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:24:04,908] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.0259748376463175, 'dropout_rate': 0.6859431566383477, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4067118597267765, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:25:16,507] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.7354678955974852, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.14371429216714185, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.14716081727614433, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.48497854077253216
[I 2024-04-15 17:25:26,570] Trial 46 finished with value: 0.605323983519897 and parameters: {'subsample': 0.8425251610032892, 'learning_rate': 0.0053639186505709605, 'dropout_rate': 0.9694253886674298, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.2574882493705594, 'max_features': 'log2', 'min_impurity_decrease': 1.016919779492087e-07, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:26:12,118] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.9243504330346544, 'learning_rate': 0.0011967557478414943, 'dropout_rate': 0.26105839347264326, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.09478753269749979, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0900852926156961e-06, 'validation_fraction': 0.885979815139411, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:26:12,657] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.6629098068705582, 'learning_rate': 0.03206553467408159, 'dropout_rate': 0.4306027387774125, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 1.649438874428751, 'min_weight_fraction_leaf': 0.4531732166106651, 'max_features': None, 'min_impurity_decrease': 1.3827158635733464e-05, 'validation_fraction': 0.9933742654917034, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:27:31,204] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.5594663300427036, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.20150817069458604, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 0.37876808539513185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 2.4898164587398135e-06, 'validation_fraction': 0.8334504114679286, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:28:58,102] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8200406111838637, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.1332989943240106, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 3.941625975561508, 'min_weight_fraction_leaf': 0.19624715321365332, 'max_features': 'auto', 'min_impurity_decrease': 5.669547081135241e-07, 'validation_fraction': 0.4330566028790252, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 17:30:09,137] Trial 51 finished with value: 0.6018179418009 and parameters: {'subsample': 0.9104229481605087, 'learning_rate': 0.008746876340866865, 'dropout_rate': 0.21819919656654377, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04663074560267056, 'min_weight_fraction_leaf': 0.4658711277635662, 'max_features': 'auto', 'min_impurity_decrease': 3.7719550144765347e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:31:31,299] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.8779706491076079, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.2964247652315011, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.938875857608422, 'min_weight_fraction_leaf': 0.4498850843205848, 'max_features': 'auto', 'min_impurity_decrease': 2.069194057796043e-07, 'validation_fraction': 0.9290323568738834, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:32:51,726] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.8000935140072126, 'learning_rate': 0.011589642842612286, 'dropout_rate': 0.18159949067544315, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.35651077580386414, 'min_weight_fraction_leaf': 0.37041988544171633, 'max_features': 'auto', 'min_impurity_decrease': 3.9659385891088e-07, 'validation_fraction': 0.871716173290517, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:33:15,716] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9719469162642941, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.8266353856620614, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.3650290068083506, 'min_weight_fraction_leaf': 0.4054310128883196, 'max_features': 'auto', 'min_impurity_decrease': 0.009274431072766336, 'validation_fraction': 0.9110985556757252, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:34:34,103] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9036490757662792, 'learning_rate': 0.004559295521962164, 'dropout_rate': 0.2464144102989256, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 2.0967888913642825, 'min_weight_fraction_leaf': 0.44190432010777553, 'max_features': 'auto', 'min_impurity_decrease': 1.193431534143351e-06, 'validation_fraction': 0.7942250610339133, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:35:30,127] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8543724704763108, 'learning_rate': 0.0012362877185655196, 'dropout_rate': 0.19475454848391177, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.924263075836695, 'min_weight_fraction_leaf': 0.4778661374912658, 'max_features': 1, 'min_impurity_decrease': 1.6304555456718902e-07, 'validation_fraction': 0.9992342826522478, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.75
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6587982832618026
[I 2024-04-15 17:35:59,331] Trial 57 finished with value: 0.6603913832851868 and parameters: {'subsample': 0.9387462021362047, 'learning_rate': 0.013448102685141811, 'dropout_rate': 0.5891903890315894, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 0.0019551426651700787, 'min_weight_fraction_leaf': 0.4208222206696523, 'max_features': 'auto', 'min_impurity_decrease': 6.36446366123735e-07, 'validation_fraction': 0.8907139307996623, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:36:11,205] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.9577150108799986, 'learning_rate': 0.09671804411942064, 'dropout_rate': 0.6195846181212514, 'n_estimators': 283, 'criterion': 'squared_error', 'ccp_alpha': 0.44937133507930177, 'min_weight_fraction_leaf': 0.33458212087172423, 'max_features': 0.1, 'min_impurity_decrease': 6.523326131696827e-07, 'validation_fraction': 0.8852115531926663, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:36:32,631] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9323642065585147, 'learning_rate': 0.04692015604549857, 'dropout_rate': 0.5460527407257292, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 1.5096456306059212, 'min_weight_fraction_leaf': 0.28930456038905916, 'max_features': 'log2', 'min_impurity_decrease': 1.6927224987120254e-07, 'validation_fraction': 0.6759708730248685, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:36:37,724] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.019818701956304124, 'dropout_rate': 0.6506047265765441, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.7976673158326983, 'min_weight_fraction_leaf': 0.42349373681810587, 'max_features': 'auto', 'min_impurity_decrease': 2.260183580683562e-06, 'validation_fraction': 0.9643361967122663, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:37:42,258] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.9892683986696426, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.12609792583962923, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 0.22783102537036656, 'min_weight_fraction_leaf': 0.38482014716301177, 'max_features': 'auto', 'min_impurity_decrease': 3.121762528354459e-07, 'validation_fraction': 0.9345303802773877, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 17:38:25,949] Trial 62 finished with value: 0.5973525260391381 and parameters: {'subsample': 0.8958668704209188, 'learning_rate': 0.013709338127145103, 'dropout_rate': 0.2719048491375873, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.4675490501789938, 'max_features': 'auto', 'min_impurity_decrease': 4.99059031535833e-07, 'validation_fraction': 0.9609388942489451, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:39:03,775] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.5099147728251798, 'learning_rate': 0.0047635225598756225, 'dropout_rate': 0.727101025098758, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.733686110808502, 'min_weight_fraction_leaf': 0.2162503097374653, 'max_features': 'auto', 'min_impurity_decrease': 0.00014811012865046226, 'validation_fraction': 0.7684320660585116, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:40:08,516] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7725061675644463, 'learning_rate': 0.01632247935160366, 'dropout_rate': 0.36503843263594504, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.30086752542772716, 'min_weight_fraction_leaf': 0.40104192592323706, 'max_features': 'auto', 'min_impurity_decrease': 8.287392060214126e-07, 'validation_fraction': 0.9093711333441808, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:40:47,729] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.9311291803826592, 'learning_rate': 0.009066186689461582, 'dropout_rate': 0.5697334421431232, 'n_estimators': 387, 'criterion': 'squared_error', 'ccp_alpha': 1.122844774015951, 'min_weight_fraction_leaf': 0.4962117179962737, 'max_features': 'auto', 'min_impurity_decrease': 4.054579781585349e-06, 'validation_fraction': 0.8558728454820717, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:41:38,234] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8365620544513689, 'learning_rate': 0.022681518299337303, 'dropout_rate': 0.16537519129703201, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.407723936090512, 'min_weight_fraction_leaf': 0.36517701571895683, 'max_features': 'sqrt', 'min_impurity_decrease': 3.241998861905611e-07, 'validation_fraction': 0.8185744726344024, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:42:38,286] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.44818442084795884, 'learning_rate': 0.02921952990739149, 'dropout_rate': 0.2271926570620947, 'n_estimators': 467, 'criterion': 'friedman_mse', 'ccp_alpha': 2.0384900012151963, 'min_weight_fraction_leaf': 0.4211338177916157, 'max_features': 'auto', 'min_impurity_decrease': 1.4298913454728315e-06, 'validation_fraction': 0.9660497725288214, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:43:00,380] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8579390753189435, 'learning_rate': 0.012783334675124321, 'dropout_rate': 0.499258057656232, 'n_estimators': 312, 'criterion': 'squared_error', 'ccp_alpha': 0.830279801910747, 'min_weight_fraction_leaf': 0.4607084781284311, 'max_features': 'auto', 'min_impurity_decrease': 1.3568513606672929e-07, 'validation_fraction': 0.8925211397709236, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:43:39,192] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.786466176479288, 'learning_rate': 0.004018882145822068, 'dropout_rate': 0.42050912513013483, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 8.536647141347391, 'min_weight_fraction_leaf': 0.3485339928251229, 'max_features': None, 'min_impurity_decrease': 5.412716052848312e-07, 'validation_fraction': 0.7027283531430607, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:44:32,037] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.15767213087481324, 'learning_rate': 0.007763574063312924, 'dropout_rate': 0.25122666812491895, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.010224165039626776, 'min_weight_fraction_leaf': 0.4372642442127546, 'max_features': 'auto', 'min_impurity_decrease': 1.8015545575134766e-07, 'validation_fraction': 0.9975125715299878, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.49356223175965663
[I 2024-04-15 17:44:38,939] Trial 71 finished with value: 0.6004387694866352 and parameters: {'subsample': 0.8358376197961069, 'learning_rate': 0.004078027515854746, 'dropout_rate': 0.983511325860669, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.22910735706669474, 'max_features': 'log2', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9238748566717793, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:45,745] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9375804576067359, 'learning_rate': 0.0058069950532190755, 'dropout_rate': 0.16033065274696134, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6374908647868113, 'min_weight_fraction_leaf': 0.25925643779102236, 'max_features': 'log2', 'min_impurity_decrease': 1.043158296301398e-07, 'validation_fraction': 0.8408360882819792, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:57,003] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8663908775735847, 'learning_rate': 0.011688605820590949, 'dropout_rate': 0.9088405719505623, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.35065330932074357, 'min_weight_fraction_leaf': 0.24913433692567943, 'max_features': 'log2', 'min_impurity_decrease': 2.3764830721846887e-07, 'validation_fraction': 0.7766959064031379, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:46:08,410] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8954410632257164, 'learning_rate': 0.014713787785871615, 'dropout_rate': 0.8981498158391491, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.2548318594901287, 'min_weight_fraction_leaf': 0.17777174503118776, 'max_features': 'log2', 'min_impurity_decrease': 1.0237452134280835e-07, 'validation_fraction': 0.8712977301815288, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:46:59,970] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9693250170531542, 'learning_rate': 0.01944317613486205, 'dropout_rate': 0.3038950153557599, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.6002519915120403, 'min_weight_fraction_leaf': 0.27549593099040687, 'max_features': 'log2', 'min_impurity_decrease': 3.6437095962407636e-07, 'validation_fraction': 0.9333459733339855, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:47:20,782] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.8173404738572, 'learning_rate': 0.0014971421569913942, 'dropout_rate': 0.7985729747352956, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.2619251873249981, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 8.414265888676054e-07, 'validation_fraction': 0.9767098938730961, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:47:55,533] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7148940452980046, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.18937615988954143, 'n_estimators': 354, 'criterion': 'friedman_mse', 'ccp_alpha': 5.674168126071088, 'min_weight_fraction_leaf': 0.31372829413515113, 'max_features': 1, 'min_impurity_decrease': 2.0331516960635478e-07, 'validation_fraction': 0.8511405274059844, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:48:56,021] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.9972717132364954, 'learning_rate': 0.007518224603684854, 'dropout_rate': 0.10395224545815006, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 0.9954262036399765, 'min_weight_fraction_leaf': 0.20635279622001615, 'max_features': 'auto', 'min_impurity_decrease': 1.5953477935293164e-06, 'validation_fraction': 0.6208576267160641, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:49:43,396] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.640991020374617, 'learning_rate': 0.011217338838150685, 'dropout_rate': 0.3451514745217959, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.7138964750214933, 'min_weight_fraction_leaf': 0.2677913041979459, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8952644729851477, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:50:51,235] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.9241882336726334, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.20677435633856203, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.5902338753800525, 'min_weight_fraction_leaf': 0.4829675934647317, 'max_features': 'auto', 'min_impurity_decrease': 5.164460817361601e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6072961373390557
[I 2024-04-15 17:51:52,837] Trial 81 finished with value: 0.6053868642702614 and parameters: {'subsample': 0.9108542466963718, 'learning_rate': 0.009036269358876279, 'dropout_rate': 0.2796761891642441, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.4662820828873332, 'max_features': 'auto', 'min_impurity_decrease': 2.9616670039909406e-07, 'validation_fraction': 0.9436075044523529, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:52:59,597] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.8954792239433687, 'learning_rate': 0.004994374572973224, 'dropout_rate': 0.28119692682400105, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.2056104964041935, 'min_weight_fraction_leaf': 0.4154239703802, 'max_features': 'auto', 'min_impurity_decrease': 2.9347899125300254e-07, 'validation_fraction': 0.9415229967670153, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:54:06,242] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9453772015100563, 'learning_rate': 0.009142733646143604, 'dropout_rate': 0.22968230522988387, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.2036067284143, 'min_weight_fraction_leaf': 0.4480797785663371, 'max_features': 'auto', 'min_impurity_decrease': 2.4573289499864505e-07, 'validation_fraction': 0.8223778282619079, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:55:21,497] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.5840337378720031, 'learning_rate': 0.015683881096783557, 'dropout_rate': 0.3151491574193926, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.7892822718895267, 'min_weight_fraction_leaf': 0.43172585763109367, 'max_features': 'auto', 'min_impurity_decrease': 7.293866823339784e-05, 'validation_fraction': 0.9793171369033844, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5513307984790875

Fold 5 C-index: 0.5278969957081545
[I 2024-04-15 17:56:26,250] Trial 85 finished with value: 0.5817146767908369 and parameters: {'subsample': 0.8381406217696484, 'learning_rate': 0.06093323136306206, 'dropout_rate': 0.1485334587119987, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.011704477637461151, 'min_weight_fraction_leaf': 0.4720691906397277, 'max_features': 'sqrt', 'min_impurity_decrease': 9.978332296088644e-07, 'validation_fraction': 0.8663419975882438, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:56:31,642] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9706110926288294, 'learning_rate': 0.006257959338637904, 'dropout_rate': 0.3709658975304737, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.4978431536243799, 'min_weight_fraction_leaf': 0.45571733166164224, 'max_features': 'auto', 'min_impurity_decrease': 6.864266251098488e-07, 'validation_fraction': 0.9093181873424959, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:56:55,306] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.8719223063133476, 'learning_rate': 0.002880550222483567, 'dropout_rate': 0.2586755827269289, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 1.4238187376704579, 'min_weight_fraction_leaf': 0.3956887351012149, 'max_features': 'auto', 'min_impurity_decrease': 4.4582432432077124e-07, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:57:14,809] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.6830569710663442, 'learning_rate': 0.013709264558994303, 'dropout_rate': 0.8329903830094019, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 7.594079981917785, 'min_weight_fraction_leaf': 0.4856994098099038, 'max_features': 'auto', 'min_impurity_decrease': 1.3753252796604584e-07, 'validation_fraction': 0.9437956828508486, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:58:10,169] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.9129716272996254, 'learning_rate': 0.01699516784590996, 'dropout_rate': 0.18087235155064957, 'n_estimators': 414, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0191863395708485, 'min_weight_fraction_leaf': 0.15271636525917553, 'max_features': None, 'min_impurity_decrease': 1.947282338748394e-07, 'validation_fraction': 0.9659767731435556, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:59:04,755] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3551831112058997, 'learning_rate': 0.025984012094512135, 'dropout_rate': 0.12431503564534369, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.46673345025014124, 'min_weight_fraction_leaf': 0.24508638469664973, 'max_features': 'log2', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.29585084927667094, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:59:56,638] Trial 91 finished with value: 0.5 and parameters: {'subsample': 0.9121196916160231, 'learning_rate': 0.00897631455122704, 'dropout_rate': 0.21471821026192198, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.15965147655044054, 'min_weight_fraction_leaf': 0.46014660015317294, 'max_features': 'auto', 'min_impurity_decrease': 4.686018614915845e-07, 'validation_fraction': 0.3711905229919747, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:00:40,303] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.9534560134117849, 'learning_rate': 0.010356392157077806, 'dropout_rate': 0.2434088678374627, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.4415538255516217, 'max_features': 'auto', 'min_impurity_decrease': 3.39700671440376e-07, 'validation_fraction': 0.9391344731614609, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:01:18,958] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8926387307309837, 'learning_rate': 0.02102195955922062, 'dropout_rate': 0.21937611154635933, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.740874637434609, 'min_weight_fraction_leaf': 0.46926642495244203, 'max_features': 'auto', 'min_impurity_decrease': 1.3508552154161032e-07, 'validation_fraction': 0.9813983205957684, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:02:08,437] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.7555668093579782, 'learning_rate': 0.006490504575483759, 'dropout_rate': 0.17187474927510435, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.45248827707479033, 'min_weight_fraction_leaf': 0.4920238106734352, 'max_features': 'auto', 'min_impurity_decrease': 0.0015502959014071815, 'validation_fraction': 0.9010561440394491, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 8}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 18:02:56,538] Trial 95 finished with value: 0.6210137072528205 and parameters: {'subsample': 0.8523472503218436, 'learning_rate': 0.001063095567599786, 'dropout_rate': 0.32831410504800185, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.10883007468655126, 'min_weight_fraction_leaf': 0.4282230464947944, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:03:40,310] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.8435591355754584, 'learning_rate': 0.001251397162175833, 'dropout_rate': 0.3220878484956735, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.1977179096404618, 'min_weight_fraction_leaf': 0.4298592452698292, 'max_features': 1, 'min_impurity_decrease': 0.013680622942575243, 'validation_fraction': 0.9282173289832502, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:04:36,892] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8016053705978137, 'learning_rate': 0.003043162873853767, 'dropout_rate': 0.28303211035592896, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.2266992831326749, 'min_weight_fraction_leaf': 0.38392378237476354, 'max_features': 'auto', 'min_impurity_decrease': 0.0032862083702029487, 'validation_fraction': 0.9760032356861055, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6859109422281264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:04:59,806] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8807317856071605, 'learning_rate': 0.00486407919341159, 'dropout_rate': 0.7211132442775035, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.876834202811247, 'min_weight_fraction_leaf': 0.4141510024046317, 'max_features': 0.1, 'min_impurity_decrease': 0.02298105889633881, 'validation_fraction': 0.9988710478147662, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.6859109422281264.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.7112403100775194
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.5190114068441065

[I 2024-04-15 18:05:46,630] A new study created in memory with name: no-name-349cc23a-adf3-48a4-be2f-d59c12af673f

Fold 5 C-index: 0.5901287553648069
[I 2024-04-15 18:05:46,608] Trial 99 finished with value: 0.5931411109869128 and parameters: {'subsample': 0.976275086451668, 'learning_rate': 0.012543335169828506, 'dropout_rate': 0.4577965489047534, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.00445672697292614, 'min_weight_fraction_leaf': 0.44456609279565923, 'max_features': 'auto', 'min_impurity_decrease': 0.0006104601971180063, 'validation_fraction': 0.9508877900290706, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 2}. Best is trial 9 with value: 0.6859109422281264.


* Best trial for C-index:
 FrozenTrial(number=9, state=TrialState.COMPLETE, values=[0.6859109422281264], datetime_start=datetime.datetime(2024, 4, 15, 16, 37, 28, 850456), datetime_complete=datetime.datetime(2024, 4, 15, 16, 39, 12, 161696), params={'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=9, value=None)


* Best Score for C-index:
 0.6859109422281264

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:06:05,921] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:06:13,944] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:06:24,608] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:06:48,925] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:06:57,744] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:07:00,049] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:07:12,201] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:07:15,636] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:07:16,147] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24609430579024427
Fold 2 IBS: 0.23040965656253537
Fold 3 IBS: 0.22864821526489268
Fold 4 IBS: 0.24089718710215188
Fold 5 IBS: 0.22863384669808964
[I 2024-04-15 18:07:55,386] Trial 9 finished with value: 0.2349366422835828 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316615258034594
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164904353219824
Fold 5 IBS: 0.2291762528827903
[I 2024-04-15 18:08:52,003] Trial 10 finished with value: 0.2356345378562359 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:09:54,895] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.247138870216024
Fold 2 IBS: 0.23184986270655478
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.2418709994354467
Fold 5 IBS: 0.22931420379900197
[I 2024-04-15 18:10:47,946] Trial 12 finished with value: 0.23582580107138096 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:11:08,825] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:11:58,210] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:12:31,143] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:12:50,810] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:13:35,863] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:14:01,438] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:14:06,433] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:14:56,391] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24707615266280916
Fold 2 IBS: 0.2319847418263816
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.24189505261981767
Fold 5 IBS: 0.22923216203360366
[I 2024-04-15 18:15:49,690] Trial 21 finished with value: 0.23582195939603873 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24649489189484391
Fold 2 IBS: 0.23082360160625934
Fold 3 IBS: 0.2287726368290018

Fold 4 IBS: 0.24123178555157707
Fold 5 IBS: 0.22878244652881227
[I 2024-04-15 18:16:50,527] Trial 22 finished with value: 0.2352210724820989 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-15 18:17:45,747] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:18:21,916] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:18:57,292] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:19:26,453] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:19:30,156] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:19:39,025] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:20:16,144] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:21:14,645] Trial 30 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24669405450794213
Fold 2 IBS: 0.23161054906241668
Fold 3 IBS: 0.22885749682655868
Fold 4 IBS: 0.2415375526987621
Fold 5 IBS: 0.22900046780800146
[I 2024-04-15 18:22:13,993] Trial 31 finished with value: 0.23554002418073622 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2349366422835828.
Fold 1 IBS: 0.24558927769654496
Fold 2 IBS: 0.23023682871310253
Fold 3 IBS: 0.22940781736456844
Fold 4 IBS: 0.24024202122958146
Fold 5 IBS: 0.22844870595001
[I 2024-04-15 18:23:17,472] Trial 32 finished with value: 0.2347849301907615 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115

Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:23:58,502] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:24:41,331] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:24:56,408] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:25:47,294] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:25:53,513] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:26:12,683] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:26:40,680] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:27:16,258] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 32 with value: 0.2347849301907615.
Fold 1 IBS: 0.24564975054404245
Fold 2 IBS: 0.22980985720122352
Fold 3 IBS: 0.22862944699148766
Fold 4 IBS: 0.24021072098294424
Fold 5 IBS: 0.228413740712783
[I 2024-04-15 18:28:22,199] Trial 41 finished with value: 0.23454270328649618 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.2457772971067935
Fold 2 IBS: 0.23000299564240484
Fold 3 IBS: 0.2283274561934457
Fold 4 IBS: 0.24023228941042038
Fold 5 IBS: 0.22843286628628326
[I 2024-04-15 18:29:25,069] Trial 42 finished with value: 0.23455458092786952 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:30:43,487] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711

Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:31:48,134] Trial 44 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:32:07,979] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24711544189088316
Fold 2 IBS: 0.23191168662951947
Fold 3 IBS: 0.22890472697929887
Fold 4 IBS: 0.24185408977590042
Fold 5 IBS: 0.22932654563425428
[I 2024-04-15 18:32:55,985] Trial 46 finished with value: 0.23582249818197126 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:33:21,653] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:33:21,960] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:33:33,962] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:34:07,259] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24627850817996183
Fold 2 IBS: 0.2309014040449158
Fold 3 IBS: 0.22910566527183993
Fold 4 IBS: 0.24089118983895721
Fold 5 IBS: 0.22880091863597468
[I 2024-04-15 18:35:00,913] Trial 51 finished with value: 0.2351955371943299 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24650271358250436
Fold 2 IBS: 0.23102415345536428
Fold 3 IBS: 0.22863853234442286
Fold 4 IBS: 0.2411028633234996
Fold 5 IBS: 0.22892194464198923
[I 2024-04-15 18:35:50,512] Trial 52 finished with value: 0.23523804146955607 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:36:37,643] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:37:25,485] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118

Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:38:05,268] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:38:36,279] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:39:08,600] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:39:44,954] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:40:14,335] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:40:39,140] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.246792274967983
Fold 2 IBS: 0.23161964216377484
Fold 3 IBS: 0.22888176928337703
Fold 4 IBS: 0.24155890986096298
Fold 5 IBS: 0.22907544730443408
[I 2024-04-15 18:41:33,664] Trial 61 finished with value: 0.2355856087161064 and parameters: {'subsample': 0.9918985385533109, 'learning_rate': 0.005743016439014149, 'dropout_rate': 0.28747233681343587, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.16038675829082302, 'max_features': 'auto', 'min_impurity_decrease': 2.9513412376244623e-06, 'validation_fraction': 0.9751691260171886, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23454270328649618.
Fold 1 IBS: 0.24556197891151196
Fold 2 IBS: 0.22971971502308358
Fold 3 IBS: 0.2284720848338911
Fold 4 IBS: 0.23983435075087522
Fold 5 IBS: 0.22821110501120903
[I 2024-04-15 18:42:27,884] Trial 62 finished with value: 0.2343598469061142 and parameters: {'subsample': 0.9574333176186867, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.18564670695369828, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 7.301362864132341e-06, 'validation_fraction': 0.9275594296798731, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:42:42,823] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9611556459137681, 'learning_rate': 0.009885633504393494, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.40714661625851756, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:43:21,162] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9996724029846231, 'learning_rate': 0.02055321577299183, 'dropout_rate': 0.19552211208698841, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.21641604442433082, 'max_features': 'log2', 'min_impurity_decrease': 7.250192360253865e-06, 'validation_fraction': 0.9272295835693174, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:44:14,529] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.919652344200739, 'learning_rate': 0.014473083324943868, 'dropout_rate': 0.16799591889422819, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.351957844105687, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118

Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:45:00,080] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8489175059797514, 'learning_rate': 0.008448226967076113, 'dropout_rate': 0.12725750793823018, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.893877768639663, 'min_weight_fraction_leaf': 0.2702972473075093, 'max_features': 'auto', 'min_impurity_decrease': 7.586810829424823e-05, 'validation_fraction': 0.8971088342813041, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:45:36,166] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9594402941587806, 'learning_rate': 0.0039206688180527, 'dropout_rate': 0.25338876644885766, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1787054950134963, 'min_weight_fraction_leaf': 0.29081789854917856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.005146223539456e-06, 'validation_fraction': 0.9662549030476638, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:46:23,202] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.885928079608526, 'learning_rate': 0.01958784726286755, 'dropout_rate': 0.3188313005563145, 'n_estimators': 463, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.24383256255051056, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.99982951588149, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.24724158711521824
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:47:06,623] Trial 69 finished with value: 0.23592674084605642 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.011561561592981577, 'dropout_rate': 0.2251092355441408, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.30419922755720963, 'min_weight_fraction_leaf': 0.1929901790072115, 'max_features': 'auto', 'min_impurity_decrease': 1.6729804035130242e-06, 'validation_fraction': 0.8450602738806452, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 62 with value: 0.2343598469061142.
Fold 1 IBS: 0.2451491152796615
Fold 2 IBS: 0.22927148757582394
Fold 3 IBS: 0.22855190516165128
Fold 4 IBS: 0.23973639516624012
Fold 5 IBS: 0.2277940457619145
[I 2024-04-15 18:47:40,803] Trial 70 finished with value: 0.2341005897890583 and parameters: {'subsample': 0.7327319228005876, 'learning_rate': 0.016866948400001296, 'dropout_rate': 0.17898373444054652, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.01005746855001105, 'min_weight_fraction_leaf': 0.3640638074298326, 'max_features': None, 'min_impurity_decrease': 9.787021311876353e-06, 'validation_fraction': 0.7926074734474466, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24549206821547404
Fold 2 IBS: 0.23024967197031007
Fold 3 IBS: 0.22871431230048478
Fold 4 IBS: 0.2407512171757705
Fold 5 IBS: 0.22802577910859287
[I 2024-04-15 18:48:14,559] Trial 71 finished with value: 0.23464660975412643 and parameters: {'subsample': 0.6580825781997457, 'learning_rate': 0.016629440896307336, 'dropout_rate': 0.17328978363215145, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.4078164122376511, 'max_features': None, 'min_impurity_decrease': 3.981143358338061e-06, 'validation_fraction': 0.9287047300321795, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.2455926669408777
Fold 2 IBS: 0.23018285219722445
Fold 3 IBS: 0.2286735121245035
Fold 4 IBS: 0.24063817521529354
Fold 5 IBS: 0.22817935594806837
[I 2024-04-15 18:48:41,986] Trial 72 finished with value: 0.2346533124851935 and parameters: {'subsample': 0.6433252951647072, 'learning_rate': 0.015406216424115876, 'dropout_rate': 0.174165060267479, 'n_estimators': 372, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.4068999670923105, 'max_features': None, 'min_impurity_decrease': 9.143853678722166e-06, 'validation_fraction': 0.8050869160635631, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:49:13,668] Trial 73 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6415805639130162, 'learning_rate': 0.016957190070749008, 'dropout_rate': 0.1022557442615895, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.7340527434897883, 'min_weight_fraction_leaf': 0.41441154927232665, 'max_features': None, 'min_impurity_decrease': 2.8366918098535655e-05, 'validation_fraction': 0.8120762455660575, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:49:43,893] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5890037439982243, 'learning_rate': 0.02388572819447024, 'dropout_rate': 0.14309816759091956, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.33550183960235097, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': None, 'min_impurity_decrease': 1.1962100920927531e-05, 'validation_fraction': 0.6568048355299513, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:50:10,995] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6875143177223235, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.18219557324018512, 'n_estimators': 365, 'criterion': 'squared_error', 'ccp_alpha': 0.6626240923578504, 'min_weight_fraction_leaf': 0.3667876525646178, 'max_features': None, 'min_impurity_decrease': 8.996538110684365e-06, 'validation_fraction': 0.7854387247082943, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:50:38,469] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6310903661182281, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.16070017323462005, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.43428922098282363, 'max_features': None, 'min_impurity_decrease': 4.880048865700701e-06, 'validation_fraction': 0.7567620429516432, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:50:58,258] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7234820637720293, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.19884799526452568, 'n_estimators': 302, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.4027406894595495, 'max_features': None, 'min_impurity_decrease': 5.35591590419612e-07, 'validation_fraction': 0.8758106078120852, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.2341005897890583.

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:51:21,236] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6708593402641205, 'learning_rate': 0.02742354559286264, 'dropout_rate': 0.12642193192647372, 'n_estimators': 329, 'criterion': 'squared_error', 'ccp_alpha': 0.2456295975030462, 'min_weight_fraction_leaf': 0.3629864105918121, 'max_features': None, 'min_impurity_decrease': 0.00015140034318578482, 'validation_fraction': 0.6173345703129903, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 70 with value: 0.2341005897890583.
Fold 1 IBS: 0.2422361212718552
Fold 2 IBS: 0.22571122387519038
Fold 3 IBS: 0.22923653706299701
Fold 4 IBS: 0.2398268927530749
Fold 5 IBS: 0.2262157333144423
[I 2024-04-15 18:51:54,864] Trial 79 finished with value: 0.23264530165551198 and parameters: {'subsample': 0.6068487747881667, 'learning_rate': 0.08690058608305122, 'dropout_rate': 0.2202274723306249, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 0.0067848986270052205, 'min_weight_fraction_leaf': 0.442958513823715, 'max_features': None, 'min_impurity_decrease': 3.159003046563375e-05, 'validation_fraction': 0.6916250922837899, 'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.23264530165551198.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:52:28,809] Trial 80 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7431452433208791, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.22085807342340602, 'n_estimators': 416, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0208718228969498, 'min_weight_fraction_leaf': 0.4578321580005691, 'max_features': None, 'min_impurity_decrease': 6.219311571999601e-05, 'validation_fraction': 0.8063818584332632, 'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 1}. Best is trial 79 with value: 0.23264530165551198.
Fold 1 IBS: 0.24125284361122407
Fold 2 IBS: 0.22420513730110872
Fold 3 IBS: 0.22885288425326455
Fold 4 IBS: 0.23690618478087347
Fold 5 IBS: 0.22511743194475423
[I 2024-04-15 18:53:00,575] Trial 81 finished with value: 0.23126689637824502 and parameters: {'subsample': 0.6143582554906275, 'learning_rate': 0.09196546766753708, 'dropout_rate': 0.17154122956253648, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.025343486133480444, 'min_weight_fraction_leaf': 0.422923580742715, 'max_features': None, 'min_impurity_decrease': 3.0516618185477245e-05, 'validation_fraction': 0.6839523176227551, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:53:19,775] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6156671358096751, 'learning_rate': 0.09024426530842436, 'dropout_rate': 0.17324784818426983, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.5340758841421452, 'min_weight_fraction_leaf': 0.44660441203015316, 'max_features': None, 'min_impurity_decrease': 3.596173256287884e-05, 'validation_fraction': 0.6862764853454645, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:53:51,269] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.59035693752921, 'learning_rate': 0.08769222490327029, 'dropout_rate': 0.13695127070120913, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.29851318725213727, 'min_weight_fraction_leaf': 0.4224884983147852, 'max_features': None, 'min_impurity_decrease': 1.7043338510624665e-05, 'validation_fraction': 0.708718433392457, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:54:20,864] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5692772731117001, 'learning_rate': 0.09337007500374273, 'dropout_rate': 0.19406549234317277, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 0.7908292561402825, 'min_weight_fraction_leaf': 0.3834871581332913, 'max_features': None, 'min_impurity_decrease': 2.8122570662289344e-05, 'validation_fraction': 0.9095186934735143, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.2424477259260394
Fold 2 IBS: 0.22638240973032056
Fold 3 IBS: 0.22825860156887076
Fold 4 IBS: 0.23805120772877988
Fold 5 IBS: 0.22643734649583214
[I 2024-04-15 18:54:24,651] Trial 85 finished with value: 0.23231545828996855 and parameters: {'subsample': 0.6445419753261435, 'learning_rate': 0.06087928731142127, 'dropout_rate': 0.24518342938103005, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.011216734292662366, 'min_weight_fraction_leaf': 0.4043905469812696, 'max_features': None, 'min_impurity_decrease': 1.493590751470447e-05, 'validation_fraction': 0.5742595190050698, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:54:29,002] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5345448615448432, 'learning_rate': 0.06299476346040861, 'dropout_rate': 0.16060697827295928, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.62448544277789, 'min_weight_fraction_leaf': 0.4834818041059262, 'max_features': None, 'min_impurity_decrease': 1.4511890623038534e-05, 'validation_fraction': 0.531307128627143, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24212442159072736
Fold 2 IBS: 0.22535780949238718
Fold 3 IBS: 0.22839243624354327
Fold 4 IBS: 0.2376426744658837
Fold 5 IBS: 0.22566811629124223
[I 2024-04-15 18:54:53,546] Trial 87 finished with value: 0.23183709161675675 and parameters: {'subsample': 0.6482886513725954, 'learning_rate': 0.08056151243791008, 'dropout_rate': 0.2600398597942537, 'n_estimators': 374, 'criterion': 'squared_error', 'ccp_alpha': 0.01745937818789605, 'min_weight_fraction_leaf': 0.40356411913419793, 'max_features': None, 'min_impurity_decrease': 9.949241277389102e-06, 'validation_fraction': 0.5582433992805256, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:54:56,313] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6879348852579991, 'learning_rate': 0.08209035744510738, 'dropout_rate': 0.24522201083374043, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.2983993026610602, 'min_weight_fraction_leaf': 0.3774672254272644, 'max_features': None, 'min_impurity_decrease': 5.4011226362110275e-06, 'validation_fraction': 0.568843188657281, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:55:01,193] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6555693108457097, 'learning_rate': 0.08348043724232247, 'dropout_rate': 0.1018982518393906, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.3922659564335438, 'max_features': None, 'min_impurity_decrease': 1.84353439530822e-05, 'validation_fraction': 0.4550485507485021, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:55:08,517] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6142534760575815, 'learning_rate': 0.07977183656340979, 'dropout_rate': 0.21675268812215465, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.43931856433894717, 'max_features': None, 'min_impurity_decrease': 4.509029295159726e-05, 'validation_fraction': 0.6255054030515286, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 8}. Best is trial 81 with value: 0.23126689637824502.
Fold 1 IBS: 0.24098581972087948
Fold 2 IBS: 0.22316717801046412
Fold 3 IBS: 0.22816422552337945
Fold 4 IBS: 0.23597578008775205
Fold 5 IBS: 0.22473523040311924
[I 2024-04-15 18:55:38,364] Trial 91 finished with value: 0.23060564674911882 and parameters: {'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24718434152159066
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22893463205005193
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22935673483794422
[I 2024-04-15 18:55:58,364] Trial 92 finished with value: 0.23589807288135617 and parameters: {'subsample': 0.5057005214243391, 'learning_rate': 0.09883062819528839, 'dropout_rate': 0.2685922627272655, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.19747740396734947, 'min_weight_fraction_leaf': 0.4679716753672616, 'max_features': None, 'min_impurity_decrease': 1.0671241077127033e-05, 'validation_fraction': 0.5950373519486988, 'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:56:22,855] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5538299448336005, 'learning_rate': 0.0868661642219975, 'dropout_rate': 0.20334468934521452, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.5267007889739713, 'min_weight_fraction_leaf': 0.42336750014808644, 'max_features': None, 'min_impurity_decrease': 8.867094040313709e-05, 'validation_fraction': 0.520690018337254, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:56:27,947] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5702665640439277, 'learning_rate': 0.09449632562825357, 'dropout_rate': 0.13870793304287105, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.8492587817200913, 'min_weight_fraction_leaf': 0.348550363613902, 'max_features': None, 'min_impurity_decrease': 6.826272330503328e-06, 'validation_fraction': 0.5659130589721448, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:56:45,902] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7076939032161012, 'learning_rate': 0.09136733918164754, 'dropout_rate': 0.18672112900745633, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.561945255260577, 'min_weight_fraction_leaf': 0.40234945062950195, 'max_features': None, 'min_impurity_decrease': 2.5588389290979514e-05, 'validation_fraction': 0.4537896994588092, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:57:02,102] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6655863757457166, 'learning_rate': 0.08941626520289533, 'dropout_rate': 0.2411336203156454, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.23565160101206817, 'min_weight_fraction_leaf': 0.42995214161407835, 'max_features': None, 'min_impurity_decrease': 3.937366373268103e-06, 'validation_fraction': 0.6733503587022674, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 16}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:57:02,552] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5830397464244746, 'learning_rate': 0.09649030637314325, 'dropout_rate': 0.1548001251941624, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 1.0632556006826448, 'min_weight_fraction_leaf': 0.4466142202394081, 'max_features': 1, 'min_impurity_decrease': 9.319522810040033e-06, 'validation_fraction': 0.49048790135092346, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:57:21,756] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6220799571230118, 'learning_rate': 0.08529012031921517, 'dropout_rate': 0.2588962329024949, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3323104826759427, 'min_weight_fraction_leaf': 0.4570033067989539, 'max_features': None, 'min_impurity_decrease': 1.5778942534009964e-05, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 3}. Best is trial 91 with value: 0.23060564674911882.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:57:28,227] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.07813501740629669, 'dropout_rate': 0.30318261654818046, 'n_estimators': 242, 'criterion': 'squared_error', 'ccp_alpha': 1.7079733343503498, 'min_weight_fraction_leaf': 0.32269779176244495, 'max_features': 0.1, 'min_impurity_decrease': 1.276230329676773e-06, 'validation_fraction': 0.36954438153697, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.23060564674911882.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.23060564674911882], datetime_start=datetime.datetime(2024, 4, 15, 18, 55, 8, 520009), datetime_complete=datetime.datetime(2024, 4, 15, 18, 55, 38, 363798), params={'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.23060564674911882

In [66]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.686
train_ibs:  0.231

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.07426378544613033,
                                 criterion='squared_error',
                                 dropout_rate=0.28125955124323376,
                                 learning_rate=0.013102111413618,
                                 max_features='auto', max_leaf_nodes=16,
                                 min_impurity_decrease=1.4994028685178666e-07,
                                 min_samples_leaf=10,
                                 min_weight_fraction_leaf=0.27579636299120275,
                                 n_estimators=406, random_state=123,
                                 subsample=0.6059965408578151,
                                 validation_fraction=0.6359003593513561)

C-index score: 0.518

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03787089343697578,
                                 criterion='squared_error',
                                 dropout_rate=0.18479264516541616,
                                 learning_rate=0.09426091382038485, max_depth=2,
                                 max_leaf_nodes=6,
                                 min_impurity_decrease=7.4293259533530295e-06,
                                 min_samples_leaf=7, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4036747584607865,
                                 n_estimators=390, random_state=123,
                                 subsample=0.579213280645811,
                                 validation_fraction=0.5325834925366492)

IBS: 0.23

In [70]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [71]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [72]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 18:57:37,696] A new study created in memory with name: no-name-1e259526-e221-47c2-aac1-135ce1d52b5d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:57:43,325] Trial 0 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6423526693826518.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:58:00,042] Trial 1 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:58:07,000] Trial 2 finished with value: 0.6398895181851605 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:58:14,638] Trial 3 finished with value: 0.6410622977559646 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:58:23,645] Trial 4 finished with value: 0.6410296656257357 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:58:34,643] Trial 5 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:58:41,224] Trial 6 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:58:44,930] Trial 7 finished with value: 0.6499035318694023 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:58:52,728] Trial 8 finished with value: 0.6438735819301804 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:59:06,659] Trial 9 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:59:09,890] Trial 10 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:59:24,064] Trial 11 finished with value: 0.6410912219754442 and parameters: {'subsample': 0.1913192016083392, 'dropout_rate': 0.653844054640545, 'n_estimators': 479, 'learning_rate': 0.09497904560009218}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:59:35,023] Trial 12 finished with value: 0.6413056364818717 and parameters: {'subsample': 0.3353880007200528, 'dropout_rate': 0.7264534851333669, 'n_estimators': 349, 'learning_rate': 0.03172136900447732}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:59:38,283] Trial 13 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.9449452743225262, 'dropout_rate': 0.5772994600940633, 'n_estimators': 5, 'learning_rate': 0.09434482881678866}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 18:59:50,208] Trial 14 finished with value: 0.6443978613258662 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.8070186117174272, 'n_estimators': 378, 'learning_rate': 0.07350404709311845}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:59:56,132] Trial 15 finished with value: 0.6419534424060024 and parameters: {'subsample': 0.3793977474066647, 'dropout_rate': 0.5432207672870106, 'n_estimators': 89, 'learning_rate': 0.03777863375701947}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:00:05,992] Trial 16 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.8245070470446283, 'dropout_rate': 0.9733961081825167, 'n_estimators': 300, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:00:19,182] Trial 17 finished with value: 0.6463367331276717 and parameters: {'subsample': 0.6278318159798674, 'dropout_rate': 0.44488289175405504, 'n_estimators': 423, 'learning_rate': 0.04142804288610771}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:00:33,233] Trial 18 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.6223271642238412, 'dropout_rate': 0.2484669514167454, 'n_estimators': 430, 'learning_rate': 0.03935603162728128}. Best is trial 7 with value: 0.6499035318694023.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:00:37,932] Trial 19 finished with value: 0.6443942804019518 and parameters: {'subsample': 0.38793667853472646, 'dropout_rate': 0.7077875554849441, 'n_estimators': 85, 'learning_rate': 0.04269105711861253}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:00:47,921] Trial 20 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6004927729383457, 'dropout_rate': 0.608992508329216, 'n_estimators': 310, 'learning_rate': 0.02073176682253709}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:01:01,294] Trial 21 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6024584846948889, 'dropout_rate': 0.617775702073121, 'n_estimators': 410, 'learning_rate': 0.02243634436579768}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:01:10,894] Trial 22 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.5584709618699464, 'dropout_rate': 0.6014397310146338, 'n_estimators': 307, 'learning_rate': 0.017446813011032656}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:01:20,697] Trial 23 finished with value: 0.6436924938049693 and parameters: {'subsample': 0.43791928961446275, 'dropout_rate': 0.8014372139995105, 'n_estimators': 311, 'learning_rate': 0.008919877679902218}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 19:01:29,079] Trial 24 finished with value: 0.6460354189759705 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.6537883290687992, 'n_estimators': 252, 'learning_rate': 0.019745129742150442}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:01:38,766] Trial 25 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.5821550035835038, 'dropout_rate': 0.7920018989193829, 'n_estimators': 311, 'learning_rate': 0.013287182579533728}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:01:44,766] Trial 26 finished with value: 0.6448885335306227 and parameters: {'subsample': 0.867224185897017, 'dropout_rate': 0.524159118998949, 'n_estimators': 140, 'learning_rate': 0.030380762890188803}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:01:54,644] Trial 27 finished with value: 0.6436924938049693 and parameters: {'subsample': 0.4283418725935132, 'dropout_rate': 0.6054847715047298, 'n_estimators': 276, 'learning_rate': 0.0018982151266466758}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:02:02,593] Trial 28 finished with value: 0.6395234906028925 and parameters: {'subsample': 0.23131169694169362, 'dropout_rate': 0.6759556339789096, 'n_estimators': 226, 'learning_rate': 0.01722458658460315}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:14,009] Trial 29 finished with value: 0.6423890258578916 and parameters: {'subsample': 0.5445078393070778, 'dropout_rate': 0.39009335662541156, 'n_estimators': 345, 'learning_rate': 0.025782557435654437}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:18,369] Trial 30 finished with value: 0.6487271713746836 and parameters: {'subsample': 0.740594251581977, 'dropout_rate': 0.7457374535389898, 'n_estimators': 47, 'learning_rate': 0.04533396343210069}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:22,351] Trial 31 finished with value: 0.6486908148994439 and parameters: {'subsample': 0.6672644585179881, 'dropout_rate': 0.7515705829262332, 'n_estimators': 54, 'learning_rate': 0.06132980546832587}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:26,207] Trial 32 finished with value: 0.6487271713746836 and parameters: {'subsample': 0.7327275461586737, 'dropout_rate': 0.7664797479900043, 'n_estimators': 50, 'learning_rate': 0.062230833336482765}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:30,363] Trial 33 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.7052899554363676, 'dropout_rate': 0.7535878954485298, 'n_estimators': 63, 'learning_rate': 0.0647797242442408}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:34,088] Trial 34 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.7962466562568574, 'dropout_rate': 0.8730575581455766, 'n_estimators': 47, 'learning_rate': 0.08157053839647124}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:39,816] Trial 35 finished with value: 0.6448521770553829 and parameters: {'subsample': 0.689136943535989, 'dropout_rate': 0.9381981821357201, 'n_estimators': 131, 'learning_rate': 0.06090286210752555}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:44,531] Trial 36 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.8850788886344975, 'dropout_rate': 0.8497284849319764, 'n_estimators': 97, 'learning_rate': 0.047740198862003314}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:48,179] Trial 37 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.7465974928938772, 'dropout_rate': 0.762528132423257, 'n_estimators': 41, 'learning_rate': 0.05621431261796065}. Best is trial 7 with value: 0.6499035318694023.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:51,001] Trial 38 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.7910265829012886, 'dropout_rate': 0.8201500943507289, 'n_estimators': 1, 'learning_rate': 0.0802388198308747}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:02:58,657] Trial 39 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6483381968153921, 'dropout_rate': 0.6826761322925258, 'n_estimators': 159, 'learning_rate': 0.04656913718567279}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:02,753] Trial 40 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.7217274689422681, 'dropout_rate': 0.8887286631915676, 'n_estimators': 67, 'learning_rate': 0.056831039369223575}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:07,851] Trial 41 finished with value: 0.6447431076296637 and parameters: {'subsample': 0.5499101555113013, 'dropout_rate': 0.7437832936105103, 'n_estimators': 114, 'learning_rate': 0.06632641686558935}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:11,385] Trial 42 finished with value: 0.6392017748618757 and parameters: {'subsample': 0.5017415876482066, 'dropout_rate': 0.6416417766093212, 'n_estimators': 38, 'learning_rate': 0.05134611734790604}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:14,730] Trial 43 finished with value: 0.6502480839222122 and parameters: {'subsample': 0.6688819035008029, 'dropout_rate': 0.6964999563725005, 'n_estimators': 21, 'learning_rate': 0.0692844085215762}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:17,918] Trial 44 finished with value: 0.6463730896029115 and parameters: {'subsample': 0.7759951791574855, 'dropout_rate': 0.6951159000675758, 'n_estimators': 18, 'learning_rate': 0.06972781553702145}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:22,112] Trial 45 finished with value: 0.6448885335306227 and parameters: {'subsample': 0.856068539007671, 'dropout_rate': 0.4938268622013002, 'n_estimators': 67, 'learning_rate': 0.07719198392856119}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:27,165] Trial 46 finished with value: 0.6487271713746836 and parameters: {'subsample': 0.6784742045939507, 'dropout_rate': 0.7675812228380298, 'n_estimators': 109, 'learning_rate': 0.060899749572876916}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:30,486] Trial 47 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.7439187554546609, 'dropout_rate': 0.8319581886344798, 'n_estimators': 25, 'learning_rate': 0.05462436851714732}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:35,644] Trial 48 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6581550458916713, 'dropout_rate': 0.7770084027642782, 'n_estimators': 108, 'learning_rate': 0.08692259516675999}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:40,310] Trial 49 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.9362857595964282, 'dropout_rate': 0.9312088199153865, 'n_estimators': 81, 'learning_rate': 0.06977049657841096}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:47,156] Trial 50 finished with value: 0.6456126333291472 and parameters: {'subsample': 0.7212803665834485, 'dropout_rate': 0.5694009859561241, 'n_estimators': 178, 'learning_rate': 0.036450919161848463}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:51,209] Trial 51 finished with value: 0.6486908148994439 and parameters: {'subsample': 0.6732576368661897, 'dropout_rate': 0.7323084196301786, 'n_estimators': 54, 'learning_rate': 0.0616255895146821}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:03:55,182] Trial 52 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.820418921570172, 'dropout_rate': 0.7289927847727031, 'n_estimators': 25, 'learning_rate': 0.05984777875916728}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:04:01,418] Trial 53 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.6821912327729229, 'dropout_rate': 0.7717844713363854, 'n_estimators': 138, 'learning_rate': 0.0455458456849779}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 19:04:06,066] Trial 54 finished with value: 0.6411670920067818 and parameters: {'subsample': 0.6335813528459866, 'dropout_rate': 0.1464738011208001, 'n_estimators': 71, 'learning_rate': 0.06485852546285992}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:04:08,806] Trial 55 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.7684220673327675, 'dropout_rate': 0.6875305359978694, 'n_estimators': 2, 'learning_rate': 0.05114560278593602}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:04:13,973] Trial 56 finished with value: 0.6431858386068956 and parameters: {'subsample': 0.5773668103492899, 'dropout_rate': 0.6555870719053609, 'n_estimators': 100, 'learning_rate': 0.07275479081141786}. Best is trial 43 with value: 0.6502480839222122.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 19:04:17,397] Trial 57 finished with value: 0.6489542848067353 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.8409230984897413, 'n_estimators': 37, 'learning_rate': 0.05761113460853838}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 19:04:20,808] Trial 58 finished with value: 0.6426848474734521 and parameters: {'subsample': 0.14355287033064457, 'dropout_rate': 0.8391889566760888, 'n_estimators': 25, 'learning_rate': 0.04318968365732964}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 19:04:26,605] Trial 59 finished with value: 0.6452897002268916 and parameters: {'subsample': 0.2586938494047239, 'dropout_rate': 0.9245581590175167, 'n_estimators': 124, 'learning_rate': 0.05836681970001922}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:04:31,139] Trial 60 finished with value: 0.6457014726940404 and parameters: {'subsample': 0.16366811369319273, 'dropout_rate': 0.968436204354046, 'n_estimators': 82, 'learning_rate': 0.03506760456906887}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 19:04:34,745] Trial 61 finished with value: 0.6498887943447169 and parameters: {'subsample': 0.2139386702656443, 'dropout_rate': 0.7994213125826732, 'n_estimators': 45, 'learning_rate': 0.05350194010762867}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 19:04:38,229] Trial 62 finished with value: 0.6451442743259328 and parameters: {'subsample': 0.20292513243647062, 'dropout_rate': 0.8085138770459752, 'n_estimators': 39, 'learning_rate': 0.05272223912680717}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:04:41,134] Trial 63 finished with value: 0.6436777562802839 and parameters: {'subsample': 0.33911313564425927, 'dropout_rate': 0.8670588481727701, 'n_estimators': 13, 'learning_rate': 0.047067936806341526}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:04:47,124] Trial 64 finished with value: 0.6403707031008341 and parameters: {'subsample': 0.11398076199642557, 'dropout_rate': 0.7114695268325248, 'n_estimators': 158, 'learning_rate': 0.04928206785826176}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:04:50,470] Trial 65 finished with value: 0.6499719696449797 and parameters: {'subsample': 0.2926173825922429, 'dropout_rate': 0.7933264854805802, 'n_estimators': 35, 'learning_rate': 0.05447341001108784}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:04:55,154] Trial 66 finished with value: 0.6499719696449797 and parameters: {'subsample': 0.2917389960977984, 'dropout_rate': 0.7976094751219412, 'n_estimators': 55, 'learning_rate': 0.041839335063339554}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:04:59,046] Trial 67 finished with value: 0.6499719696449797 and parameters: {'subsample': 0.29121921398342737, 'dropout_rate': 0.8914707434039268, 'n_estimators': 40, 'learning_rate': 0.04087325894113451}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:02,478] Trial 68 finished with value: 0.6499719696449797 and parameters: {'subsample': 0.29392153058990794, 'dropout_rate': 0.8961501940030975, 'n_estimators': 35, 'learning_rate': 0.0267624773650322}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:05:06,695] Trial 69 finished with value: 0.6387878103605409 and parameters: {'subsample': 0.29735488532752563, 'dropout_rate': 0.9936663958598406, 'n_estimators': 77, 'learning_rate': 0.027621373237613895}. Best is trial 43 with value: 0.6502480839222122.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:09,646] Trial 70 finished with value: 0.6563248526864572 and parameters: {'subsample': 0.3635202871111, 'dropout_rate': 0.9054029905658174, 'n_estimators': 16, 'learning_rate': 0.03293159547302169}. Best is trial 70 with value: 0.6563248526864572.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:12,752] Trial 71 finished with value: 0.6506960694435043 and parameters: {'subsample': 0.37104298081980164, 'dropout_rate': 0.9011443703226787, 'n_estimators': 15, 'learning_rate': 0.03267147157166253}. Best is trial 70 with value: 0.6563248526864572.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:15,853] Trial 72 finished with value: 0.6563248526864572 and parameters: {'subsample': 0.36605376192694195, 'dropout_rate': 0.9040943309498741, 'n_estimators': 15, 'learning_rate': 0.03980453556878082}. Best is trial 70 with value: 0.6563248526864572.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:18,924] Trial 73 finished with value: 0.6524203833177858 and parameters: {'subsample': 0.41442942823291107, 'dropout_rate': 0.8941423172992564, 'n_estimators': 14, 'learning_rate': 0.03441991256301824}. Best is trial 70 with value: 0.6563248526864572.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:21,994] Trial 74 finished with value: 0.640613617983685 and parameters: {'subsample': 0.4155547034298735, 'dropout_rate': 0.953051878664331, 'n_estimators': 14, 'learning_rate': 0.03925715277574589}. Best is trial 70 with value: 0.6563248526864572.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:24,896] Trial 75 finished with value: 0.6570194774356111 and parameters: {'subsample': 0.35660691782094656, 'dropout_rate': 0.9192044262556913, 'n_estimators': 3, 'learning_rate': 0.034467086607900405}. Best is trial 75 with value: 0.6570194774356111.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:27,845] Trial 76 finished with value: 0.6479087396751253 and parameters: {'subsample': 0.35802466784498843, 'dropout_rate': 0.9162670704227818, 'n_estimators': 11, 'learning_rate': 0.031137390416300727}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:30,585] Trial 77 finished with value: 0.6544836132876403 and parameters: {'subsample': 0.3901733929212714, 'dropout_rate': 0.9853071138632854, 'n_estimators': 4, 'learning_rate': 0.034382277716078116}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:33,706] Trial 78 finished with value: 0.6393108442875948 and parameters: {'subsample': 0.45784770877107944, 'dropout_rate': 0.9900767600312439, 'n_estimators': 23, 'learning_rate': 0.03449190190054415}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:36,376] Trial 79 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.3947382388327982, 'dropout_rate': 0.9688860881179893, 'n_estimators': 2, 'learning_rate': 0.029080073133321296}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:43,019] Trial 80 finished with value: 0.6431131256564161 and parameters: {'subsample': 0.5133490791295597, 'dropout_rate': 0.9496133991430871, 'n_estimators': 199, 'learning_rate': 0.02415330033175113}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:05:46,170] Trial 81 finished with value: 0.6452065249266288 and parameters: {'subsample': 0.3226454341713434, 'dropout_rate': 0.8786049818501851, 'n_estimators': 27, 'learning_rate': 0.03335403156276549}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:49,004] Trial 82 finished with value: 0.6501753709717327 and parameters: {'subsample': 0.4619232636748426, 'dropout_rate': 0.907773991249692, 'n_estimators': 11, 'learning_rate': 0.037196347238014994}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:52,204] Trial 83 finished with value: 0.6393108442875948 and parameters: {'subsample': 0.4575424187950529, 'dropout_rate': 0.9177329658991508, 'n_estimators': 11, 'learning_rate': 0.038873322781888583}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:55,927] Trial 84 finished with value: 0.653977652340554 and parameters: {'subsample': 0.37270876403105657, 'dropout_rate': 0.8981598095527075, 'n_estimators': 3, 'learning_rate': 0.03676729332536198}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:05:59,050] Trial 85 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.40265872860879515, 'dropout_rate': 0.26205027511777046, 'n_estimators': 3, 'learning_rate': 0.03209389097430766}. Best is trial 75 with value: 0.6570194774356111.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:02,218] Trial 86 finished with value: 0.6570853089602215 and parameters: {'subsample': 0.3656280733701871, 'dropout_rate': 0.8636766938181732, 'n_estimators': 17, 'learning_rate': 0.03590948741962575}. Best is trial 86 with value: 0.6570853089602215.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:06:06,458] Trial 87 finished with value: 0.6434743549535309 and parameters: {'subsample': 0.359530650923223, 'dropout_rate': 0.8577050114534388, 'n_estimators': 62, 'learning_rate': 0.0297674543171535}. Best is trial 86 with value: 0.6570853089602215.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:09,654] Trial 88 finished with value: 0.6444158993525062 and parameters: {'subsample': 0.37693427198787965, 'dropout_rate': 0.9456256731372071, 'n_estimators': 22, 'learning_rate': 0.03569601029903016}. Best is trial 86 with value: 0.6570853089602215.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:12,500] Trial 89 finished with value: 0.6699472340896035 and parameters: {'subsample': 0.2552050789105039, 'dropout_rate': 0.9810542276440395, 'n_estimators': 1, 'learning_rate': 0.02469841671276124}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:06:16,320] Trial 90 finished with value: 0.6403419223024509 and parameters: {'subsample': 0.26859331465546027, 'dropout_rate': 0.10184332440552968, 'n_estimators': 57, 'learning_rate': 0.020565345597117667}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:19,044] Trial 91 finished with value: 0.6699472340896035 and parameters: {'subsample': 0.3404179440547933, 'dropout_rate': 0.9693988378587445, 'n_estimators': 1, 'learning_rate': 0.0993942176514741}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:22,288] Trial 92 finished with value: 0.6436917995539817 and parameters: {'subsample': 0.3424053678529621, 'dropout_rate': 0.9789269743473995, 'n_estimators': 30, 'learning_rate': 0.025412037431077977}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:25,265] Trial 93 finished with value: 0.6374627234629087 and parameters: {'subsample': 0.4266870680553344, 'dropout_rate': 0.9987223461456418, 'n_estimators': 15, 'learning_rate': 0.03382943526474715}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:28,206] Trial 94 finished with value: 0.6552804260366443 and parameters: {'subsample': 0.3699035391682784, 'dropout_rate': 0.9548044734603575, 'n_estimators': 10, 'learning_rate': 0.0376115207874597}. Best is trial 89 with value: 0.6699472340896035.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 19:06:31,940] Trial 95 finished with value: 0.6389947926112083 and parameters: {'subsample': 0.39757894906550256, 'dropout_rate': 0.9362254370521794, 'n_estimators': 48, 'learning_rate': 0.03785400508989082}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:34,676] Trial 96 finished with value: 0.6433165269831691 and parameters: {'subsample': 0.3158905548021381, 'dropout_rate': 0.9542032638114772, 'n_estimators': 3, 'learning_rate': 0.02820037220806718}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 19:06:37,925] Trial 97 finished with value: 0.6482630875463712 and parameters: {'subsample': 0.23727296358971306, 'dropout_rate': 0.9673892077827166, 'n_estimators': 29, 'learning_rate': 0.09818110835358405}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:40,858] Trial 98 finished with value: 0.6699472340896035 and parameters: {'subsample': 0.3381996878613835, 'dropout_rate': 0.8733946903252942, 'n_estimators': 1, 'learning_rate': 0.023228312766200628}. Best is trial 89 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654

[I 2024-04-15 19:06:43,670] A new study created in memory with name: no-name-4def2a94-c3d3-4047-ba1b-d8ece805ce91

Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 19:06:43,666] Trial 99 finished with value: 0.6467414807478551 and parameters: {'subsample': 0.26525544900187503, 'dropout_rate': 0.8713525195123779, 'n_estimators': 3, 'learning_rate': 0.0233915883643472}. Best is trial 89 with value: 0.6699472340896035.


* Best trial for C-index:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.6699472340896035], datetime_start=datetime.datetime(2024, 4, 15, 19, 6, 9, 656185), datetime_complete=datetime.datetime(2024, 4, 15, 19, 6, 12, 500128), params={'subsample': 0.2552050789105039, 'dropout_rate': 0.9810542276440395, 'n_estimators': 1, 'learning_rate': 0.02469841671276124}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=89, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.2552050789105039, 'dropout_rate': 0.9810542276440395, 'n_estimators': 1, 'learning_rate': 0.02469841671276124}


* Best Score for C-index:
 0.6699472340896035

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2535208184290341
Fold 2 IBS: 0.23694039312201395
Fold 3 IBS: 0.3183278645100559
Fold 4 IBS: 0.2785272332047015
Fold 5 IBS: 0.26959701773388006
[I 2024-04-15 19:06:49,237] Trial 0 finished with value: 0.27138266539993705 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.4379931381955231
Fold 2 IBS: 0.38220982923025065
Fold 3 IBS: 0.3920321662913435
Fold 4 IBS: 0.3412768011671995
Fold 5 IBS: 0.33941908574786966
[I 2024-04-15 19:07:04,549] Trial 1 finished with value: 0.3785862041264373 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.3324678077695315
Fold 2 IBS: 0.277934644896449
Fold 3 IBS: 0.37028973305297364
Fold 4 IBS: 0.29747016904097373
Fold 5 IBS: 0.30753782579260386
[I 2024-04-15 19:07:11,172] Trial 2 finished with value: 0.31714003611050634 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.31819805240780114
Fold 2 IBS: 0.2752541423102686
Fold 3 IBS: 0.37171315150390805
Fold 4 IBS: 0.2766993729668638
Fold 5 IBS: 0.3220161766839568
[I 2024-04-15 19:07:18,483] Trial 3 finished with value: 0.3127761791745597 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.32511222009503676
Fold 2 IBS: 0.2802616619160303
Fold 3 IBS: 0.37647097763017984
Fold 4 IBS: 0.2831367343962378
Fold 5 IBS: 0.3211661754469021
[I 2024-04-15 19:07:27,182] Trial 4 finished with value: 0.31722955389687735 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.43183877461465453
Fold 2 IBS: 0.3462655068788492
Fold 3 IBS: 0.3901822518832906
Fold 4 IBS: 0.3158040918671078
Fold 5 IBS: 0.3240588862506669
[I 2024-04-15 19:07:37,938] Trial 5 finished with value: 0.36162990229891384 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.23162026538239194
Fold 2 IBS: 0.2130450924041672
Fold 3 IBS: 0.2929798151511939
Fold 4 IBS: 0.2602468384417057
Fold 5 IBS: 0.24596662301082522
[I 2024-04-15 19:07:44,504] Trial 6 finished with value: 0.2487717268780568 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2487717268780568.
Fold 1 IBS: 0.2219624571251742
Fold 2 IBS: 0.20191698224064816
Fold 3 IBS: 0.2554464703379466
Fold 4 IBS: 0.22028035730313134
Fold 5 IBS: 0.21397872069101548
[I 2024-04-15 19:07:48,154] Trial 7 finished with value: 0.22271699753958316 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.26135001657957846
Fold 2 IBS: 0.24282456049458448
Fold 3 IBS: 0.326134406423236
Fold 4 IBS: 0.27402360123646585
Fold 5 IBS: 0.2768152873434484
[I 2024-04-15 19:07:56,404] Trial 8 finished with value: 0.27622957441546264 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.438775036769916
Fold 2 IBS: 0.35568555286291453
Fold 3 IBS: 0.390909578851063
Fold 4 IBS: 0.31218235322033017
Fold 5 IBS: 0.32722373811786437
[I 2024-04-15 19:08:11,428] Trial 9 finished with value: 0.3649552519644176 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.2460224099705921
Fold 2 IBS: 0.23086098108808756
Fold 3 IBS: 0.2288453379547681
Fold 4 IBS: 0.24136765896018506
Fold 5 IBS: 0.2281543805010059
[I 2024-04-15 19:08:14,776] Trial 10 finished with value: 0.23505015369492774 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.24222241773116046
Fold 2 IBS: 0.22722173122509534
Fold 3 IBS: 0.2286593447825781
Fold 4 IBS: 0.2395148036138026
Fold 5 IBS: 0.22443221144275918
[I 2024-04-15 19:08:17,792] Trial 11 finished with value: 0.23241010175907917 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.24176148728318728
Fold 2 IBS: 0.21717807870202094
Fold 3 IBS: 0.30499365850510085
Fold 4 IBS: 0.23549965533952483
Fold 5 IBS: 0.24475205448274662
[I 2024-04-15 19:08:21,865] Trial 12 finished with value: 0.24883698686251612 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.23944832000588395
Fold 2 IBS: 0.22451123143312443
Fold 3 IBS: 0.22879762094537542
Fold 4 IBS: 0.23820765139553346
Fold 5 IBS: 0.22173810615143869
[I 2024-04-15 19:08:24,645] Trial 13 finished with value: 0.23054058598627117 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22826207452412578
Fold 2 IBS: 0.20708009192406637
Fold 3 IBS: 0.2838897565833488
Fold 4 IBS: 0.2304990846646447
Fold 5 IBS: 0.23613357206494798
[I 2024-04-15 19:08:29,448] Trial 14 finished with value: 0.23717291595222673 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.275392871065553
Fold 2 IBS: 0.2585619199470001
Fold 3 IBS: 0.34359360523637944
Fold 4 IBS: 0.2695300185359706
Fold 5 IBS: 0.2900236218757005
[I 2024-04-15 19:08:34,153] Trial 15 finished with value: 0.28742040733212076 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.2992664945570406
Fold 2 IBS: 0.2747928451682891
Fold 3 IBS: 0.3545755333528485
Fold 4 IBS: 0.27769123663346346
Fold 5 IBS: 0.30449340223416854
[I 2024-04-15 19:08:42,947] Trial 16 finished with value: 0.3021639023891621 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22571204260462702
Fold 2 IBS: 0.21029571932609178
Fold 3 IBS: 0.23477013659701168
Fold 4 IBS: 0.23294813806507536
Fold 5 IBS: 0.2112667744029953
[I 2024-04-15 19:08:46,843] Trial 17 finished with value: 0.2229985621991602 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22749628705840008
Fold 2 IBS: 0.208593559309439
Fold 3 IBS: 0.2860837988705294
Fold 4 IBS: 0.255694330022353
Fold 5 IBS: 0.23961625820762958
[I 2024-04-15 19:08:58,324] Trial 18 finished with value: 0.24349684669367022 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22458664776493728
Fold 2 IBS: 0.20232195896375377

Fold 3 IBS: 0.27412770407771303
Fold 4 IBS: 0.2250727043053573
Fold 5 IBS: 0.2280063139706162
[I 2024-04-15 19:09:03,969] Trial 19 finished with value: 0.23082306581647552 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22813963029627435
Fold 2 IBS: 0.21261919492535192
Fold 3 IBS: 0.2328032377684259
Fold 4 IBS: 0.23177471930860935
Fold 5 IBS: 0.21241390693232276
[I 2024-04-15 19:09:08,457] Trial 20 finished with value: 0.22355013784619687 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.23294882482388735
Fold 2 IBS: 0.2172731528360657
Fold 3 IBS: 0.23037554967791973
Fold 4 IBS: 0.23393962524579212
Fold 5 IBS: 0.21554329357937044
[I 2024-04-15 19:09:12,801] Trial 21 finished with value: 0.22601608923260708 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22457381812654392
Fold 2 IBS: 0.20893564288887
Fold 3 IBS: 0.23611424341865672
Fold 4 IBS: 0.23267189537604366
Fold 5 IBS: 0.21078105893610707
[I 2024-04-15 19:09:16,879] Trial 22 finished with value: 0.22261533174924425 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.7601905131808098, 'n_estimators': 57, 'learning_rate': 0.019334429052945145}. Best is trial 22 with value: 0.22261533174924425.
Fold 1 IBS: 0.2719235052333098
Fold 2 IBS: 0.23764489493573734
Fold 3 IBS: 0.3193018171397408
Fold 4 IBS: 0.2836424571696349
Fold 5 IBS: 0.2702613255072474
[I 2024-04-15 19:09:23,072] Trial 23 finished with value: 0.27655479999713406 and parameters: {'subsample': 0.8557281003254902, 'dropout_rate': 0.618865896035061, 'n_estimators': 150, 'learning_rate': 0.04186582141545488}. Best is trial 22 with value: 0.22261533174924425.
Fold 1 IBS: 0.22147474510826237
Fold 2 IBS: 0.2056747916191557
Fold 3 IBS: 0.24049201615940596
Fold 4 IBS: 0.23256814236182405
Fold 5 IBS: 0.21033940163812648
[I 2024-04-15 19:09:26,835] Trial 24 finished with value: 0.22210981937735488 and parameters: {'subsample': 0.8736292350257677, 'dropout_rate': 0.9758883725345413, 'n_estimators': 56, 'learning_rate': 0.02427957701685606}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.2294989380094321
Fold 2 IBS: 0.21183471759672118
Fold 3 IBS: 0.23574856019681506
Fold 4 IBS: 0.22643183601188832
Fold 5 IBS: 0.21142162434179954
[I 2024-04-15 19:09:30,287] Trial 25 finished with value: 0.22298713523133123 and parameters: {'subsample': 0.19468056412788132, 'dropout_rate': 0.9897789595635863, 'n_estimators': 40, 'learning_rate': 0.025002990823540957}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.23333397090317404
Fold 2 IBS: 0.21300462246331686
Fold 3 IBS: 0.2919265248430093
Fold 4 IBS: 0.26141154567737246
Fold 5 IBS: 0.24514756200998605
[I 2024-04-15 19:09:34,780] Trial 26 finished with value: 0.24896484517937173 and parameters: {'subsample': 0.9043940009344528, 'dropout_rate': 0.9033888277148059, 'n_estimators': 92, 'learning_rate': 0.04553017387255954}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.23638591525082767
Fold 2 IBS: 0.21516306172620478
Fold 3 IBS: 0.2951885661305264
Fold 4 IBS: 0.2637815004845914
Fold 5 IBS: 0.2478693530817822
[I 2024-04-15 19:09:40,516] Trial 27 finished with value: 0.25167767933478646 and parameters: {'subsample': 0.8218236648644409, 'dropout_rate': 0.7846036392151594, 'n_estimators': 145, 'learning_rate': 0.030307532796347948}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.24064419834309675
Fold 2 IBS: 0.22415587169214657
Fold 3 IBS: 0.22881420079591844
Fold 4 IBS: 0.23693120040178806
Fold 5 IBS: 0.22166322813485473
[I 2024-04-15 19:09:47,901] Trial 28 finished with value: 0.2304417398735609 and parameters: {'subsample': 0.3907993998263619, 'dropout_rate': 0.9279548799256215, 'n_estimators': 233, 'learning_rate': 0.001303388577036546}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.21842977369684194
Fold 2 IBS: 0.2011107725842906
Fold 3 IBS: 0.25384448921376923
Fold 4 IBS: 0.232211579011124
Fold 5 IBS: 0.2157044751662694
[I 2024-04-15 19:09:53,158] Trial 29 finished with value: 0.22426021793445905 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.7695165335542838, 'n_estimators': 108, 'learning_rate': 0.01903980772031594}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.22163880438788114
Fold 2 IBS: 0.2060581683786993
Fold 3 IBS: 0.2396778541303928
Fold 4 IBS: 0.22756268731638724
Fold 5 IBS: 0.21031352296982186
[I 2024-04-15 19:09:57,318] Trial 30 finished with value: 0.22105020743663645 and parameters: {'subsample': 0.7079769658545929, 'dropout_rate': 0.8498048136204235, 'n_estimators': 29, 'learning_rate': 0.046221173886982825}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2200724127940874
Fold 2 IBS: 0.20420688373140491
Fold 3 IBS: 0.2434279631041286
Fold 4 IBS: 0.23088381472023015
Fold 5 IBS: 0.2107203802256644
[I 2024-04-15 19:10:00,647] Trial 31 finished with value: 0.22186229091510307 and parameters: {'subsample': 0.7782166094867763, 'dropout_rate': 0.8526511128221191, 'n_estimators': 26, 'learning_rate': 0.05869348626309983}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2220192442415896
Fold 2 IBS: 0.20656029859231154
Fold 3 IBS: 0.23956067627789562
Fold 4 IBS: 0.23254630069491217
Fold 5 IBS: 0.21031393154503805
[I 2024-04-15 19:10:03,866] Trial 32 finished with value: 0.22220009027034937 and parameters: {'subsample': 0.7878845579666447, 'dropout_rate': 0.8560240225148643, 'n_estimators': 22, 'learning_rate': 0.05967077858339052}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2291078679995047
Fold 2 IBS: 0.21341140636860573
Fold 3 IBS: 0.23192802809417654
Fold 4 IBS: 0.23402147506607907
Fold 5 IBS: 0.21317832146276416
[I 2024-04-15 19:10:07,282] Trial 33 finished with value: 0.22432941979822604 and parameters: {'subsample': 0.7794604399156984, 'dropout_rate': 0.9504625799325089, 'n_estimators': 13, 'learning_rate': 0.06055914650999865}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.25430560739242225
Fold 2 IBS: 0.2284133753114856
Fold 3 IBS: 0.3090625406037944
Fold 4 IBS: 0.2732154551860483
Fold 5 IBS: 0.2621904177585131
[I 2024-04-15 19:10:12,041] Trial 34 finished with value: 0.2654374792504527 and parameters: {'subsample': 0.6982462018109117, 'dropout_rate': 0.8639367030524437, 'n_estimators': 84, 'learning_rate': 0.0649821776613948}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21768018948179807
Fold 2 IBS: 0.20112990863142238
Fold 3 IBS: 0.2547679190320581
Fold 4 IBS: 0.2359778319362916
Fold 5 IBS: 0.21519795791889573
[I 2024-04-15 19:10:15,432] Trial 35 finished with value: 0.22495076140009318 and parameters: {'subsample': 0.7880243815860887, 'dropout_rate': 0.999943957221368, 'n_estimators': 27, 'learning_rate': 0.07675979779302834}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2977141155977322
Fold 2 IBS: 0.24775644913124664
Fold 3 IBS: 0.3306511114108861
Fold 4 IBS: 0.2923888275212842
Fold 5 IBS: 0.28032513089432576
[I 2024-04-15 19:10:20,860] Trial 36 finished with value: 0.28976712691109496 and parameters: {'subsample': 0.9189450187030327, 'dropout_rate': 0.8476672993402941, 'n_estimators': 129, 'learning_rate': 0.05573723451692966}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.3811658445880461
Fold 2 IBS: 0.2758127038773145
Fold 3 IBS: 0.36709218055056614
Fold 4 IBS: 0.30550730104285034
Fold 5 IBS: 0.3067044688141932
[I 2024-04-15 19:10:27,128] Trial 37 finished with value: 0.3272564997745941 and parameters: {'subsample': 0.739264920272442, 'dropout_rate': 0.8927843858195293, 'n_estimators': 169, 'learning_rate': 0.06888028701406422}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2264971103333118
Fold 2 IBS: 0.20135233326855248
Fold 3 IBS: 0.2526241904073602

Fold 4 IBS: 0.22761235729593224
Fold 5 IBS: 0.21391136761511492
[I 2024-04-15 19:10:30,476] Trial 38 finished with value: 0.22439947178405434 and parameters: {'subsample': 0.9323458933659868, 'dropout_rate': 0.13272164755980653, 'n_estimators': 28, 'learning_rate': 0.0802388198308747}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22935008117918856
Fold 2 IBS: 0.21153618549256686
Fold 3 IBS: 0.29072451950301204
Fold 4 IBS: 0.2586656669929489
Fold 5 IBS: 0.24321840787686647
[I 2024-04-15 19:10:34,716] Trial 39 finished with value: 0.24669897220891657 and parameters: {'subsample': 0.7076071631229807, 'dropout_rate': 0.36113352605756727, 'n_estimators': 75, 'learning_rate': 0.05598015324329953}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.4295827306814518
Fold 2 IBS: 0.33729766730917193
Fold 3 IBS: 0.38924638966253877
Fold 4 IBS: 0.31325291352447
Fold 5 IBS: 0.32175848063875884
[I 2024-04-15 19:10:47,759] Trial 40 finished with value: 0.35822763636327826 and parameters: {'subsample': 0.8123581601061346, 'dropout_rate': 0.27073406810212547, 'n_estimators': 434, 'learning_rate': 0.050770250632636425}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21843232747192648
Fold 2 IBS: 0.20124696623375102
Fold 3 IBS: 0.26589789731233937
Fold 4 IBS: 0.23953030936979589
Fold 5 IBS: 0.22339485398021788
[I 2024-04-15 19:10:51,291] Trial 41 finished with value: 0.22970047087360612 and parameters: {'subsample': 0.7485948672215855, 'dropout_rate': 0.827821271771765, 'n_estimators': 44, 'learning_rate': 0.06100155441044479}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.24545977554153506
Fold 2 IBS: 0.2302404349481251
Fold 3 IBS: 0.228814223366646
Fold 4 IBS: 0.24097498117887786
Fold 5 IBS: 0.22762304438597
[I 2024-04-15 19:10:54,605] Trial 42 finished with value: 0.2346224918842308 and parameters: {'subsample': 0.6600001822368337, 'dropout_rate': 0.7512215971522175, 'n_estimators': 1, 'learning_rate': 0.06911254892370094}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2177286772534359
Fold 2 IBS: 0.20073314902484793
Fold 3 IBS: 0.2599125036038046
Fold 4 IBS: 0.23844492228389882
Fold 5 IBS: 0.21818700490217124
[I 2024-04-15 19:10:58,876] Trial 43 finished with value: 0.2270012514136317 and parameters: {'subsample': 0.8163078290274218, 'dropout_rate': 0.939553917830419, 'n_estimators': 49, 'learning_rate': 0.047734596204521335}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.23079869739063893
Fold 2 IBS: 0.21524619860909036
Fold 3 IBS: 0.23135881430740626
Fold 4 IBS: 0.23215245196525136
Fold 5 IBS: 0.21397390753677142
[I 2024-04-15 19:11:02,027] Trial 44 finished with value: 0.22470601396183168 and parameters: {'subsample': 0.5793955243729101, 'dropout_rate': 0.8902546449865933, 'n_estimators': 25, 'learning_rate': 0.02941573453153995}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.23463938291343403
Fold 2 IBS: 0.21378641058446565
Fold 3 IBS: 0.2936585740423683
Fold 4 IBS: 0.2623275744743812
Fold 5 IBS: 0.24681085413233397
[I 2024-04-15 19:11:06,994] Trial 45 finished with value: 0.2502445592293966 and parameters: {'subsample': 0.9427673116011092, 'dropout_rate': 0.817057053206203, 'n_estimators': 116, 'learning_rate': 0.0370342562578839}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.40086920822949945
Fold 2 IBS: 0.28091448436473726
Fold 3 IBS: 0.3720791128836979
Fold 4 IBS: 0.307109292579857
Fold 5 IBS: 0.308674520431342
[I 2024-04-15 19:11:13,643] Trial 46 finished with value: 0.3339293236978267 and parameters: {'subsample': 0.8772929906687839, 'dropout_rate': 0.9519780159701515, 'n_estimators': 194, 'learning_rate': 0.06489928133343151}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.232466351187792
Fold 2 IBS: 0.21715839919246133
Fold 3 IBS: 0.23045465132815326
Fold 4 IBS: 0.23505329955231874
Fold 5 IBS: 0.21545322244115622
[I 2024-04-15 19:11:17,746] Trial 47 finished with value: 0.22611718474037631 and parameters: {'subsample': 0.7741938008338972, 'dropout_rate': 0.7343720546814592, 'n_estimators': 75, 'learning_rate': 0.008209618821055878}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21928772309722075
Fold 2 IBS: 0.20290025316680066
Fold 3 IBS: 0.24625852536625306
Fold 4 IBS: 0.22756184240178828
Fold 5 IBS: 0.21155714687356678
[I 2024-04-15 19:11:21,074] Trial 48 finished with value: 0.2215130981811259 and parameters: {'subsample': 0.6902001509321368, 'dropout_rate': 0.6604314111556595, 'n_estimators': 33, 'learning_rate': 0.052217916997002886}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22864268464482704
Fold 2 IBS: 0.20618701072642076
Fold 3 IBS: 0.23974348161514325
Fold 4 IBS: 0.22902300059149802
Fold 5 IBS: 0.21031693369470345
[I 2024-04-15 19:11:24,298] Trial 49 finished with value: 0.22278262225451853 and parameters: {'subsample': 0.5246256412363035, 'dropout_rate': 0.444654827003804, 'n_estimators': 26, 'learning_rate': 0.05201530493205449}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.4256560799384403
Fold 2 IBS: 0.3151221688354275
Fold 3 IBS: 0.3860413488667417
Fold 4 IBS: 0.3089178353626252
Fold 5 IBS: 0.317098910141038
[I 2024-04-15 19:11:36,440] Trial 50 finished with value: 0.3505672686288545 and parameters: {'subsample': 0.6713843248996562, 'dropout_rate': 0.6491522181398676, 'n_estimators': 379, 'learning_rate': 0.04745080772448178}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2192431668518127
Fold 2 IBS: 0.20189468163918148
Fold 3 IBS: 0.26982441152732806
Fold 4 IBS: 0.23613925370649705
Fold 5 IBS: 0.2256653604972261
[I 2024-04-15 19:11:40,316] Trial 51 finished with value: 0.23055337484440908 and parameters: {'subsample': 0.7172193716930169, 'dropout_rate': 0.6709427179664875, 'n_estimators': 48, 'learning_rate': 0.05997708252875927}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2410305123087452
Fold 2 IBS: 0.2195671978090868
Fold 3 IBS: 0.2993407314297869
Fold 4 IBS: 0.26849472696514515
Fold 5 IBS: 0.25209231830194867
[I 2024-04-15 19:11:44,718] Trial 52 finished with value: 0.25610509736294257 and parameters: {'subsample': 0.8289606252433972, 'dropout_rate': 0.7512811922273754, 'n_estimators': 84, 'learning_rate': 0.05632002652421048}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.24612203266949853
Fold 2 IBS: 0.23087751124769623
Fold 3 IBS: 0.22885621209387846
Fold 4 IBS: 0.24139543456033377
Fold 5 IBS: 0.22821141204302334
[I 2024-04-15 19:11:47,483] Trial 53 finished with value: 0.23509252052288607 and parameters: {'subsample': 0.9644210790375523, 'dropout_rate': 0.6894833612317082, 'n_estimators': 1, 'learning_rate': 0.04185368229372562}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22818239059764914
Fold 2 IBS: 0.20984620997622416
Fold 3 IBS: 0.2867822539050355
Fold 4 IBS: 0.25462805104656905
Fold 5 IBS: 0.24007539469996075
[I 2024-04-15 19:11:51,294] Trial 54 finished with value: 0.2439028600450877 and parameters: {'subsample': 0.7754401293458196, 'dropout_rate': 0.8581787213295002, 'n_estimators': 59, 'learning_rate': 0.06494770180873123}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22257503395436767
Fold 2 IBS: 0.20677739071945617
Fold 3 IBS: 0.23796734142055684
Fold 4 IBS: 0.22680201011024181
Fold 5 IBS: 0.2103640282316372
[I 2024-04-15 19:11:55,481] Trial 55 finished with value: 0.22089716088725195 and parameters: {'subsample': 0.6046650456267857, 'dropout_rate': 0.8107431542120329, 'n_estimators': 36, 'learning_rate': 0.035281924830240646}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2341460554286086
Fold 2 IBS: 0.21898083332700824
Fold 3 IBS: 0.22984714409801585
Fold 4 IBS: 0.23206905279076265
Fold 5 IBS: 0.21732092597900418
[I 2024-04-15 19:11:58,782] Trial 56 finished with value: 0.2264728023246799 and parameters: {'subsample': 0.6148929150329211, 'dropout_rate': 0.9112147525268226, 'n_estimators': 16, 'learning_rate': 0.033986625231595756}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.28505309347602925
Fold 2 IBS: 0.24760499505067732
Fold 3 IBS: 0.3301622822216491
Fold 4 IBS: 0.2894327690728538

Fold 5 IBS: 0.28019979914084864
[I 2024-04-15 19:12:07,498] Trial 57 finished with value: 0.28649058779241166 and parameters: {'subsample': 0.6825327446543555, 'dropout_rate': 0.5208726510676236, 'n_estimators': 282, 'learning_rate': 0.025565265724993874}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2214507245251379
Fold 2 IBS: 0.20506568938296435
Fold 3 IBS: 0.24075353489551313
Fold 4 IBS: 0.2288359521484131
Fold 5 IBS: 0.2104012829571286
[I 2024-04-15 19:12:10,872] Trial 58 finished with value: 0.22130143678183142 and parameters: {'subsample': 0.5793765216559574, 'dropout_rate': 0.869359581862351, 'n_estimators': 38, 'learning_rate': 0.03754893539001649}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22332388143407295
Fold 2 IBS: 0.20363163283585628
Fold 3 IBS: 0.24449748198927226
Fold 4 IBS: 0.22907918428885007
Fold 5 IBS: 0.21077017722074096
[I 2024-04-15 19:12:14,443] Trial 59 finished with value: 0.22226047155375853 and parameters: {'subsample': 0.4535266512643318, 'dropout_rate': 0.9611194785854935, 'n_estimators': 40, 'learning_rate': 0.038908657923000085}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2426474010909224
Fold 2 IBS: 0.22436959888835237
Fold 3 IBS: 0.3051332800511575
Fold 4 IBS: 0.26525378607334044
Fold 5 IBS: 0.25799073524428723
[I 2024-04-15 19:12:19,521] Trial 60 finished with value: 0.25907896026961197 and parameters: {'subsample': 0.5592773031153138, 'dropout_rate': 0.805892721742462, 'n_estimators': 118, 'learning_rate': 0.04300303133619651}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23322262418938672
Fold 2 IBS: 0.21780502341126942
Fold 3 IBS: 0.23021413524283157
Fold 4 IBS: 0.2317083947092564
Fold 5 IBS: 0.21648635752240689
[I 2024-04-15 19:12:22,589] Trial 61 finished with value: 0.22588730701503024 and parameters: {'subsample': 0.6197162239153043, 'dropout_rate': 0.897755135761733, 'n_estimators': 18, 'learning_rate': 0.033093783201145574}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22321650757486647
Fold 2 IBS: 0.2028003645937837
Fold 3 IBS: 0.24711601825710883
Fold 4 IBS: 0.22957583498652415
Fold 5 IBS: 0.2113955496138467
[I 2024-04-15 19:12:25,991] Trial 62 finished with value: 0.22282085500522597 and parameters: {'subsample': 0.5148326884231843, 'dropout_rate': 0.8753399354683069, 'n_estimators': 35, 'learning_rate': 0.048706108725934165}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21864755972668926
Fold 2 IBS: 0.2016225251367432
Fold 3 IBS: 0.2509189112353247
Fold 4 IBS: 0.23100076284482912
Fold 5 IBS: 0.2136479732966466
[I 2024-04-15 19:12:30,040] Trial 63 finished with value: 0.22316754644804657 and parameters: {'subsample': 0.6487668076796561, 'dropout_rate': 0.8232768248813066, 'n_estimators': 70, 'learning_rate': 0.027357634359371004}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22030711444046622
Fold 2 IBS: 0.2028872132298813
Fold 3 IBS: 0.2723990807024937
Fold 4 IBS: 0.23234983693422795
Fold 5 IBS: 0.22892547385548054
[I 2024-04-15 19:12:33,782] Trial 64 finished with value: 0.23137374383250994 and parameters: {'subsample': 0.5975058672190523, 'dropout_rate': 0.7823037659988256, 'n_estimators': 56, 'learning_rate': 0.05410979520775479}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2246485985201335
Fold 2 IBS: 0.2058825400782259
Fold 3 IBS: 0.2824399132357561
Fold 4 IBS: 0.23828761615189975
Fold 5 IBS: 0.23650207193611295
[I 2024-04-15 19:12:38,205] Trial 65 finished with value: 0.23755214798442564 and parameters: {'subsample': 0.45888887591206007, 'dropout_rate': 0.9190970086086071, 'n_estimators': 90, 'learning_rate': 0.038689837069848146}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23273965002953717
Fold 2 IBS: 0.21725871845559455
Fold 3 IBS: 0.23057552835557654
Fold 4 IBS: 0.2346983844695266
Fold 5 IBS: 0.21547730446319574
[I 2024-04-15 19:12:41,110] Trial 66 finished with value: 0.22614991715468613 and parameters: {'subsample': 0.7326959870204457, 'dropout_rate': 0.8441970079444766, 'n_estimators': 14, 'learning_rate': 0.04501243637315829}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2531769237494069
Fold 2 IBS: 0.23296920068260224
Fold 3 IBS: 0.3140245626406833
Fold 4 IBS: 0.2699122978070452
Fold 5 IBS: 0.26615389994000355
[I 2024-04-15 19:12:45,696] Trial 67 finished with value: 0.2672473769639482 and parameters: {'subsample': 0.5471917580520336, 'dropout_rate': 0.9769821442118126, 'n_estimators': 99, 'learning_rate': 0.057929390501509886}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2182645606215572
Fold 2 IBS: 0.20076151212811258
Fold 3 IBS: 0.26082805345729165
Fold 4 IBS: 0.23236316881117391
Fold 5 IBS: 0.21885563811795794
[I 2024-04-15 19:12:48,988] Trial 68 finished with value: 0.22621458662721866 and parameters: {'subsample': 0.6946889669430717, 'dropout_rate': 0.583662202262188, 'n_estimators': 34, 'learning_rate': 0.07261636225834231}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2205185249303166
Fold 2 IBS: 0.2039865579628996
Fold 3 IBS: 0.24377138068999496
Fold 4 IBS: 0.2298605380624899
Fold 5 IBS: 0.2109444943185319
[I 2024-04-15 19:12:53,405] Trial 69 finished with value: 0.2218162991928466 and parameters: {'subsample': 0.6454763362460977, 'dropout_rate': 0.720522833073103, 'n_estimators': 72, 'learning_rate': 0.021510860950056627}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22195649096735395
Fold 2 IBS: 0.2057796473545906
Fold 3 IBS: 0.24047621118241896
Fold 4 IBS: 0.22883745019976204
Fold 5 IBS: 0.21040296604701988
[I 2024-04-15 19:12:58,178] Trial 70 finished with value: 0.22149055315022909 and parameters: {'subsample': 0.5867802742615672, 'dropout_rate': 0.7164929446280183, 'n_estimators': 74, 'learning_rate': 0.01836623067581729}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2224574115110653
Fold 2 IBS: 0.20624684542359964
Fold 3 IBS: 0.23963014108905373
Fold 4 IBS: 0.22900785656242212
Fold 5 IBS: 0.210325868066254
[I 2024-04-15 19:13:02,294] Trial 71 finished with value: 0.22153362453047895 and parameters: {'subsample': 0.5943758778419203, 'dropout_rate': 0.7178705789257822, 'n_estimators': 75, 'learning_rate': 0.01747576819572829}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21907570074462793
Fold 2 IBS: 0.20169546621039425
Fold 3 IBS: 0.25033163822633475
Fold 4 IBS: 0.23075068452470274
Fold 5 IBS: 0.213686630109571
[I 2024-04-15 19:13:06,846] Trial 72 finished with value: 0.2231080239631261 and parameters: {'subsample': 0.5766850407934205, 'dropout_rate': 0.6867676859247152, 'n_estimators': 90, 'learning_rate': 0.02089435843239119}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21942878302413968
Fold 2 IBS: 0.20183778716815864
Fold 3 IBS: 0.2501366496560795
Fold 4 IBS: 0.2315135061719935
Fold 5 IBS: 0.21360678712048178
[I 2024-04-15 19:13:12,411] Trial 73 finished with value: 0.22330470262817062 and parameters: {'subsample': 0.6350981564062819, 'dropout_rate': 0.724091326177061, 'n_estimators': 144, 'learning_rate': 0.013043210125809303}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23786360690225444
Fold 2 IBS: 0.22245402837048767
Fold 3 IBS: 0.22903028955483665
Fold 4 IBS: 0.23621957174006056
Fold 5 IBS: 0.21976820761106206
[I 2024-04-15 19:13:16,536] Trial 74 finished with value: 0.22906714083574026 and parameters: {'subsample': 0.601523470567797, 'dropout_rate': 0.6566427706952908, 'n_estimators': 74, 'learning_rate': 0.005080429459703627}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2214943627310797
Fold 2 IBS: 0.20164308069300232
Fold 3 IBS: 0.25169555993234316
Fold 4 IBS: 0.22841371586916473
Fold 5 IBS: 0.21416681676848298
[I 2024-04-15 19:13:21,377] Trial 75 finished with value: 0.22348270719881458 and parameters: {'subsample': 0.49319069081038364, 'dropout_rate': 0.7076570957071591, 'n_estimators': 105, 'learning_rate': 0.01824490640855918}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2328946499056936
Fold 2 IBS: 0.2170979257337216
Fold 3 IBS: 0.23040550426683937
Fold 4 IBS: 0.2332389132664599

Fold 5 IBS: 0.2156801492109445
[I 2024-04-15 19:13:24,845] Trial 76 finished with value: 0.2258634284767318 and parameters: {'subsample': 0.6388046490330901, 'dropout_rate': 0.618911653541915, 'n_estimators': 42, 'learning_rate': 0.014880869357715765}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22462298117263793
Fold 2 IBS: 0.2073982536472491
Fold 3 IBS: 0.28361457332876805
Fold 4 IBS: 0.24675247717794
Fold 5 IBS: 0.2381675349082399
[I 2024-04-15 19:13:30,812] Trial 77 finished with value: 0.240111164046967 and parameters: {'subsample': 0.541487090871485, 'dropout_rate': 0.7704979082473631, 'n_estimators': 165, 'learning_rate': 0.02189762732192369}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22365763185049595
Fold 2 IBS: 0.20591143440013582
Fold 3 IBS: 0.280976248290565
Fold 4 IBS: 0.24848562445786387
Fold 5 IBS: 0.23615081501710733
[I 2024-04-15 19:13:35,987] Trial 78 finished with value: 0.2390363508032336 and parameters: {'subsample': 0.6733814576309736, 'dropout_rate': 0.7358591929789065, 'n_estimators': 128, 'learning_rate': 0.02725879214599771}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22811684389438022
Fold 2 IBS: 0.21004117151133037
Fold 3 IBS: 0.23552715888942047
Fold 4 IBS: 0.22642754442179203
Fold 5 IBS: 0.2109726578133541
[I 2024-04-15 19:13:39,881] Trial 79 finished with value: 0.22221707530605544 and parameters: {'subsample': 0.4590324206086437, 'dropout_rate': 0.5730916522393441, 'n_estimators': 62, 'learning_rate': 0.016584715438210443}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21914807252926094
Fold 2 IBS: 0.20152400712862856
Fold 3 IBS: 0.2680973864145784
Fold 4 IBS: 0.2372703504251833
Fold 5 IBS: 0.22464173105960364
[I 2024-04-15 19:13:49,734] Trial 80 finished with value: 0.23013630951145098 and parameters: {'subsample': 0.5700298173994884, 'dropout_rate': 0.7963649913222645, 'n_estimators': 327, 'learning_rate': 0.008427919156244693}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22077348750169198
Fold 2 IBS: 0.20465087956377137
Fold 3 IBS: 0.24199806863414064
Fold 4 IBS: 0.22642953767379848
Fold 5 IBS: 0.2105996070892919
[I 2024-04-15 19:13:53,811] Trial 81 finished with value: 0.2208903160925389 and parameters: {'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2181890289575755
Fold 2 IBS: 0.20085037679728737
Fold 3 IBS: 0.2628056745478857
Fold 4 IBS: 0.2329689235642938
Fold 5 IBS: 0.22111819009301079
[I 2024-04-15 19:13:58,905] Trial 82 finished with value: 0.22718643879201061 and parameters: {'subsample': 0.591713415609599, 'dropout_rate': 0.8271461226738561, 'n_estimators': 81, 'learning_rate': 0.03066131851432999}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.23796348921996144
Fold 2 IBS: 0.22231306926597583
Fold 3 IBS: 0.22917826331147176
Fold 4 IBS: 0.23592312507334565
Fold 5 IBS: 0.2199694633866284
[I 2024-04-15 19:14:01,936] Trial 83 finished with value: 0.22906948205147662 and parameters: {'subsample': 0.5104385117001161, 'dropout_rate': 0.8678063293886515, 'n_estimators': 11, 'learning_rate': 0.03618620932286212}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22381030523700307
Fold 2 IBS: 0.20720978403751017
Fold 3 IBS: 0.237911829205767
Fold 4 IBS: 0.22792947965938568
Fold 5 IBS: 0.2104040102787604
[I 2024-04-15 19:14:05,590] Trial 84 finished with value: 0.22145308168368527 and parameters: {'subsample': 0.6572552519386883, 'dropout_rate': 0.6327349414747185, 'n_estimators': 44, 'learning_rate': 0.028170869846693994}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21850846200789092
Fold 2 IBS: 0.20113172065685006
Fold 3 IBS: 0.25393815497147415
Fold 4 IBS: 0.2312989153770497
Fold 5 IBS: 0.2150707094266202
[I 2024-04-15 19:14:11,135] Trial 85 finished with value: 0.22398959248797704 and parameters: {'subsample': 0.6586093577814823, 'dropout_rate': 0.6202710354222771, 'n_estimators': 64, 'learning_rate': 0.032423376680946865}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22379912941339913
Fold 2 IBS: 0.2076089237823684
Fold 3 IBS: 0.23713925842702915
Fold 4 IBS: 0.22881038613184393
Fold 5 IBS: 0.21049278014865697
[I 2024-04-15 19:14:16,048] Trial 86 finished with value: 0.22157009558065952 and parameters: {'subsample': 0.6201193355845069, 'dropout_rate': 0.6727758765974591, 'n_estimators': 44, 'learning_rate': 0.027328093031043253}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2227310338564416
Fold 2 IBS: 0.2064729770871324
Fold 3 IBS: 0.2387097684726459
Fold 4 IBS: 0.22860683668930395
Fold 5 IBS: 0.21031777945117824
[I 2024-04-15 19:14:19,836] Trial 87 finished with value: 0.22136767911134042 and parameters: {'subsample': 0.6137923043677187, 'dropout_rate': 0.6578608395909092, 'n_estimators': 46, 'learning_rate': 0.028228844589449218}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.3155249490793188
Fold 2 IBS: 0.2640250973483872
Fold 3 IBS: 0.35150740047903567
Fold 4 IBS: 0.29465926108505686
Fold 5 IBS: 0.29664399307292966
[I 2024-04-15 19:14:27,730] Trial 88 finished with value: 0.30447214021294566 and parameters: {'subsample': 0.5563453956745567, 'dropout_rate': 0.635509892730024, 'n_estimators': 227, 'learning_rate': 0.041042651352224235}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21882804040039408
Fold 2 IBS: 0.2021257239375794
Fold 3 IBS: 0.2488925553100117
Fold 4 IBS: 0.2299136957400707
Fold 5 IBS: 0.21258997349908584
[I 2024-04-15 19:14:31,464] Trial 89 finished with value: 0.22246999777742835 and parameters: {'subsample': 0.7174443932842023, 'dropout_rate': 0.5932177411632202, 'n_estimators': 52, 'learning_rate': 0.03497836260796343}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22508455000645972
Fold 2 IBS: 0.2093506081973267
Fold 3 IBS: 0.23545916578671205
Fold 4 IBS: 0.2296620341827449
Fold 5 IBS: 0.210956430784988
[I 2024-04-15 19:14:34,975] Trial 90 finished with value: 0.22210255779164628 and parameters: {'subsample': 0.6885792506232654, 'dropout_rate': 0.5581493449312643, 'n_estimators': 36, 'learning_rate': 0.030149768812526692}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22350570792154217
Fold 2 IBS: 0.20710675637673007
Fold 3 IBS: 0.2377890064398362
Fold 4 IBS: 0.22866334718906384
Fold 5 IBS: 0.2103837931115841
[I 2024-04-15 19:14:38,658] Trial 91 finished with value: 0.2214897222077513 and parameters: {'subsample': 0.6252518157333167, 'dropout_rate': 0.6768103250965768, 'n_estimators': 45, 'learning_rate': 0.027532898640914117}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2413589052700756
Fold 2 IBS: 0.22663761168748628
Fold 3 IBS: 0.22866863477272367
Fold 4 IBS: 0.23745690563602184
Fold 5 IBS: 0.2237298644365178
[I 2024-04-15 19:14:41,609] Trial 92 finished with value: 0.23157038436056504 and parameters: {'subsample': 0.6080039360699264, 'dropout_rate': 0.6989466017172343, 'n_estimators': 9, 'learning_rate': 0.024367473936345387}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22723131937890337
Fold 2 IBS: 0.2113640306874193
Fold 3 IBS: 0.23373445637933926
Fold 4 IBS: 0.22846157368512096
Fold 5 IBS: 0.21172162311351986
[I 2024-04-15 19:14:44,823] Trial 93 finished with value: 0.22250260064886057 and parameters: {'subsample': 0.5869718752556726, 'dropout_rate': 0.515780662916985, 'n_estimators': 26, 'learning_rate': 0.03696817721869061}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22073632727273912
Fold 2 IBS: 0.20388324986594278
Fold 3 IBS: 0.2433710156727303
Fold 4 IBS: 0.22887009757913981
Fold 5 IBS: 0.2108449986568362
[I 2024-04-15 19:14:48,611] Trial 94 finished with value: 0.22154113780947765 and parameters: {'subsample': 0.632517730042522, 'dropout_rate': 0.6542832786756084, 'n_estimators': 53, 'learning_rate': 0.02920357901679212}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22798047230982416
Fold 2 IBS: 0.21148788850219047
Fold 3 IBS: 0.23356421385825749
Fold 4 IBS: 0.23007244409198496
Fold 5 IBS: 0.2120154922159216
[I 2024-04-15 19:14:52,118] Trial 95 finished with value: 0.22302410219563576 and parameters: {'subsample': 0.6639608403709552, 'dropout_rate': 0.7566876692486192, 'n_estimators': 36, 'learning_rate': 0.026071370321176603}. Best is trial 81 with value: 0.2208903160925389.

Fold 1 IBS: 0.2179012967955125
Fold 2 IBS: 0.20078159037918683
Fold 3 IBS: 0.26110289322293423
Fold 4 IBS: 0.23412808505560326
Fold 5 IBS: 0.21973897733190245
[I 2024-04-15 19:14:57,131] Trial 96 finished with value: 0.22673056855702786 and parameters: {'subsample': 0.7054650333977128, 'dropout_rate': 0.6262161752789943, 'n_estimators': 61, 'learning_rate': 0.03998698220337849}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21963880593620028
Fold 2 IBS: 0.20092268436766023
Fold 3 IBS: 0.2648475542088438
Fold 4 IBS: 0.2331055121729352
Fold 5 IBS: 0.22220093036998428
[I 2024-04-15 19:15:02,102] Trial 97 finished with value: 0.22814309741112476 and parameters: {'subsample': 0.531829760385333, 'dropout_rate': 0.6847533776104763, 'n_estimators': 79, 'learning_rate': 0.03223905987322316}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2466414230044532
Fold 2 IBS: 0.23146700010719856
Fold 3 IBS: 0.2289119634694628
Fold 4 IBS: 0.24164291053866815
Fold 5 IBS: 0.2288108925224838
[I 2024-04-15 19:15:04,942] Trial 98 finished with value: 0.2354948379284533 and parameters: {'subsample': 0.5618605706633095, 'dropout_rate': 0.2002801186536965, 'n_estimators': 1, 'learning_rate': 0.022985459193691663}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21844021664292554
Fold 2 IBS: 0.2014998540928507
Fold 3 IBS: 0.25108301890771456
Fold 4 IBS: 0.2341234904146111
Fold 5 IBS: 0.21405157380858064
[I 2024-04-15 19:15:09,654] Trial 99 finished with value: 0.2238396307733365 and parameters: {'subsample': 0.7589069007873921, 'dropout_rate': 0.8823172392191718, 'n_estimators': 97, 'learning_rate': 0.01992182696731529}. Best is trial 81 with value: 0.2208903160925389.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2208903160925389], datetime_start=datetime.datetime(2024, 4, 15, 19, 13, 49, 736509), datetime_complete=datetime.datetime(2024, 4, 15, 19, 13, 53, 811592), params={'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}


* Best Score for IBS:
 0.2208903160925389

In [73]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [74]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.67
train_ibs:  0.221

#### Test

In [75]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [76]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9810542276440395,
                                              learning_rate=0.02469841671276124,
                                              n_estimators=1, random_state=123,
                                              subsample=0.2552050789105039)

C-index score: 0.521

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8767395889398294,
                                              learning_rate=0.030725485144314495,
                                              n_estimators=48, random_state=123,
                                              subsample=0.5967091670188371)

IBS: 0.239

In [77]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [78]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.859   1.0
Randomsurvivalforest             0.826   2.0
GradientBoosting                 0.686   3.0
ComponentwiseGradientBoosting    0.670   4.0
CoxElastic                       0.641   5.0
CoxRidge                         0.635   6.0
CoxLasso                         0.562   7.0

In [79]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.213   1.0
ExtraSurvivalTrees             0.217   2.0
ComponentwiseGradientBoosting  0.221   3.0
GradientBoosting               0.231   4.0
CoxElastic                     0.234   5.0
CoxRidge                       0.236   6.0
CoxLasso                       0.345   7.0

In [80]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
CoxRidge                         0.530   1.0
CoxElastic                       0.527   2.0
ComponentwiseGradientBoosting    0.521   3.0
GradientBoosting                 0.518   4.0
Randomsurvivalforest             0.516   5.0
ExtraSurvivalTrees               0.506   6.0
CoxLasso                         0.477   7.0

In [81]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
CoxElastic                     0.229   1.5
GradientBoosting               0.230   3.0
ComponentwiseGradientBoosting  0.239   4.0
ExtraSurvivalTrees             0.245   5.0
Randomsurvivalforest           0.258   6.0
CoxLasso                       0.464   7.0

In [82]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/yeojohnson/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_yeojohnson_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [83]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-15