In [84]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import PowerTransformer

In [85]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [86]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [87]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [88]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [89]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [90]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [91]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [92]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [93]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [94]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [95]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [96]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [97]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [98]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [99]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [100]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

# Feature Selection

In [101]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"shape_Elongation",
"shape_MajorAxisLength",
"shape_Sphericity",
"shape_SurfaceVolumeRatio",
"shape_Flatness",
"glszm_SmallAreaLowGrayLevelEmphasis_CT_c16"
]

In [102]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [103]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Yeo-Johnson Transformation

In [104]:
# Copy the original X for later 
original_X = X.copy()

In [105]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [106]:
X_new

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16
0,0.600926,42.073251,0.761164,0.251218,0.535140,0.029425
1,0.841579,24.613845,0.697049,0.489853,0.367109,0.037915
2,0.772821,48.030294,0.565792,0.278467,0.597785,0.008009
3,0.847727,25.589900,0.684364,0.474018,0.405730,0.018398
4,0.831483,34.684750,0.503142,0.563135,0.442406,0.013051
...,...,...,...,...,...,...
134,0.680294,33.069705,0.742102,0.322021,0.523608,0.014938
135,0.758193,41.043692,0.722918,0.227705,0.735524,0.011441
136,0.770113,36.618802,0.652963,0.298398,0.648063,0.020431
137,0.628897,45.870392,0.724255,0.252893,0.492193,0.019663
138,0.892637,30.363259,0.722633,0.290461,0.756267,0.013864

In [107]:
X_new_std

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16
0,-0.735252,0.072022,1.124852,-0.476515,0.067055,1.294944
1,1.029207,-1.421627,0.161153,1.471846,-1.298903,1.828126
2,0.480839,0.444135,-1.401990,-0.164875,0.581443,-1.587057
3,1.080021,-1.314128,-0.012817,1.384484,-0.986786,0.180452
4,0.946400,-0.468644,-1.982774,1.825476,-0.689355,-0.617219
...,...,...,...,...,...,...
134,-0.200607,-0.601731,0.823106,0.274152,-0.027337,-0.311625
135,0.368838,0.002519,0.532655,-0.771682,1.721586,-0.901174
136,0.459982,-0.316986,-0.421265,0.044444,0.996190,0.433122
137,-0.551976,0.314722,0.552472,-0.456457,-0.284014,0.340615
138,1.460258,-0.839594,0.528431,-0.037139,1.894328,-0.482091

In [108]:
MAASTRO_new

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16
0,0.765178,50.002093,0.668072,0.215184,0.610062,0.010495
1,0.776540,41.753334,0.669961,0.276092,0.504616,0.035018
2,0.697164,44.375483,0.624081,0.298887,0.478604,0.012819
3,0.574636,46.115989,0.577624,0.361096,0.446059,0.029974
4,0.633419,54.394967,0.630933,0.251519,0.480378,0.013458
...,...,...,...,...,...,...
94,0.882411,34.218615,0.671754,0.307574,0.577884,0.039092
95,0.535802,51.046869,0.632189,0.289922,0.455642,0.015831
96,0.716610,50.417953,0.645548,0.228184,0.631485,0.011031
97,0.665145,44.901412,0.727488,0.223872,0.628338,0.019801
98,0.616262,36.574294,0.672838,0.347373,0.469139,0.015813

In [109]:
MAASTRO_new_std

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16
0,0.422117,0.557388,-0.228627,-0.939751,0.682565,-1.078945
1,0.509566,0.050605,-0.204032,-0.190837,-0.182599,1.669991
2,-0.081096,0.221607,-0.770221,0.049387,-0.394828,-0.656860
3,-0.902489,0.329735,-1.281223,0.615142,-0.659672,1.336360
4,-0.521824,0.794695,-0.689674,-0.472901,-0.380366,-0.548839
...,...,...,...,...,...,...
94,1.372275,-0.506427,-0.180591,0.135942,0.417742,1.886364
95,-1.140744,0.615633,-0.674760,-0.042764,-0.581768,-0.176666
96,0.059266,0.580714,-0.513250,-0.765405,0.859251,-0.977202
97,-0.306155,0.254712,0.600661,-0.822284,0.833281,0.357476
98,-0.635450,-0.320388,-0.166374,0.500549,-0.471932,-0.179243

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [110]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:26:25,411] A new study created in memory with name: no-name-8e4d94b6-7934-4852-adf3-a7e93ec7ccb7

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.714828897338403

[I 2024-04-15 17:26:25,806] A new study created in memory with name: no-name-4d56ea40-d88b-4927-8e1c-207c1424d40d

Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:25,796] Trial 0 finished with value: 0.6751603929238369 and parameters: {}. Best is trial 0 with value: 0.6751603929238369.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6751603929238369], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 25, 453372), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 25, 796514), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6751603929238369

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2518617933470256
Fold 2 IBS: 0.18864185825386184
Fold 3 IBS: 0.2305846597429618
Fold 4 IBS: 0.2244901345824116
Fold 5 IBS: 0.20899645104594913
[I 2024-04-15 17:26:26,281] Trial 0 finished with value: 0.220914979394442 and parameters: {}. Best is trial 0 with value: 0.220914979394442.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.220914979394442], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 25, 857949), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 26, 281442), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.220914979394442

In [111]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [112]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.675
train_ibs:  0.221

#### Test

In [113]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [114]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.498
IBS score: 0.281

In [115]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [116]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [117]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:26:26,508] A new study created in memory with name: no-name-14ad2f4e-8db6-452e-866f-61ec523c9e25

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7262357414448669

[I 2024-04-15 17:26:26,969] A new study created in memory with name: no-name-1dfda8aa-6aae-4f71-be94-a85ccea5eca9

Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 17:26:26,960] Trial 0 finished with value: 0.6492262593069082 and parameters: {}. Best is trial 0 with value: 0.6492262593069082.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6492262593069082], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 26, 543298), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 26, 959929), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6492262593069082

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709252196547
Fold 2 IBS: 0.2320398736627342
Fold 3 IBS: 0.22898186761465514
Fold 4 IBS: 0.24197475887753253
Fold 5 IBS: 0.22939558519938744
[I 2024-04-15 17:26:27,310] Trial 0 finished with value: 0.23592783557525493 and parameters: {}. Best is trial 0 with value: 0.23592783557525493.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783557525493], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 27, 8548), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 27, 309933), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783557525493

In [118]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [119]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.649
train_ibs:  0.236

#### Test

In [120]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [121]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [122]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [123]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:26:27,594] A new study created in memory with name: no-name-030724bd-ffba-4282-80e6-0ff409784d7b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6212765957446809

[I 2024-04-15 17:26:28,145] A new study created in memory with name: no-name-337f0fbb-2a6c-499e-b5d6-fc4168cf5670

Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:28,125] Trial 0 finished with value: 0.6734435277395772 and parameters: {}. Best is trial 0 with value: 0.6734435277395772.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6734435277395772], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 27, 628110), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 28, 125497), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6734435277395772

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2515309590238497
Fold 2 IBS: 0.1885602195226402
Fold 3 IBS: 0.2296957276388316
Fold 4 IBS: 0.22310595642466954
Fold 5 IBS: 0.20623729181941608
[I 2024-04-15 17:26:28,851] Trial 0 finished with value: 0.21982603088588143 and parameters: {}. Best is trial 0 with value: 0.21982603088588143.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21982603088588143], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 28, 188966), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 28, 851153), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21982603088588143

In [124]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [125]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.673
train_ibs:  0.22

#### Test

In [126]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [127]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.497

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.279

In [128]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [129]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:26:29,155] A new study created in memory with name: no-name-aca920ca-0277-485b-89af-976529085ac4

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:29,651] Trial 0 finished with value: 0.6742945915693643 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6742945915693643.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:30,143] Trial 1 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:30,676] Trial 2 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:31,256] Trial 3 finished with value: 0.6742945915693643 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:31,865] Trial 4 finished with value: 0.6734435277395772 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:32,315] Trial 5 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:32,783] Trial 6 finished with value: 0.6734435277395772 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:33,256] Trial 7 finished with value: 0.6742945915693643 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:33,778] Trial 8 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:34,833] Trial 9 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.6750914043183683.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:35,391] Trial 10 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 10 with value: 0.6759424681481556.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:26:35,861] Trial 11 finished with value: 0.6473957707030884 and parameters: {'l1_ratio': 0.016444541243212374}. Best is trial 10 with value: 0.6759424681481556.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:36,525] Trial 12 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.0873928389796849}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:26:36,921] Trial 13 finished with value: 0.6465989579540844 and parameters: {'l1_ratio': 0.003240751291247554}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:37,690] Trial 14 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.14334023675256088}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:38,407] Trial 15 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.14686204034367636}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:38,957] Trial 16 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.29492929565472803}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:39,505] Trial 17 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.1278697437099071}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:40,070] Trial 18 finished with value: 0.6606233192119854 and parameters: {'l1_ratio': 0.06764452452390808}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:40,645] Trial 19 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:41,440] Trial 20 finished with value: 0.6734435277395772 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:42,571] Trial 21 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.16870552103067943}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:43,446] Trial 22 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.10290429070558606}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:44,138] Trial 23 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.3543524189329308}. Best is trial 12 with value: 0.6767935319779428.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:44,631] Trial 24 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.21623254971460304}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:45,252] Trial 25 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.0853699617771228}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:45,814] Trial 26 finished with value: 0.6606233192119854 and parameters: {'l1_ratio': 0.059959030692121}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:46,357] Trial 27 finished with value: 0.6742945915693643 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:46,974] Trial 28 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.34373848137600943}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:47,618] Trial 29 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.20411849442670896}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:48,112] Trial 30 finished with value: 0.6606233192119854 and parameters: {'l1_ratio': 0.07176923518743349}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:26:48,392] Trial 31 finished with value: 0.6465989579540844 and parameters: {'l1_ratio': 0.00014301329506632987}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:49,093] Trial 32 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.15693004255950438}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:49,701] Trial 33 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.302448470141613}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:50,429] Trial 34 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.10677812392561507}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:51,253] Trial 35 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.2503833329651749}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:51,897] Trial 36 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.16431227060928094}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:52,486] Trial 37 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.07596372847182481}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:26:52,975] Trial 38 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.04616204595636416}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:53,569] Trial 39 finished with value: 0.6734435277395772 and parameters: {'l1_ratio': 0.8205172079302314}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:54,306] Trial 40 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:55,034] Trial 41 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.10781062447408256}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:55,791] Trial 42 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.1913971906650564}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:26:56,256] Trial 43 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.04256976462451839}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:57,087] Trial 44 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.0878003128446574}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:57,713] Trial 45 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08580040042998084}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:58,383] Trial 46 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.2646096239453598}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:26:58,678] Trial 47 finished with value: 0.6473957707030884 and parameters: {'l1_ratio': 0.022347042785744203}. Best is trial 12 with value: 0.6767935319779428.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:26:59,338] Trial 48 finished with value: 0.6742945915693643 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:00,007] Trial 49 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08054512980432653}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:00,708] Trial 50 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.18492352527069114}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:01,367] Trial 51 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08811220081174974}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:02,085] Trial 52 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.1328356726558727}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:02,506] Trial 53 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.04753895436920112}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:03,024] Trial 54 finished with value: 0.6742945915693643 and parameters: {'l1_ratio': 0.6304504906551746}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:03,737] Trial 55 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.12308495793069338}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:04,416] Trial 56 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08181849605361631}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:05,131] Trial 57 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.2223306031540743}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:05,397] Trial 58 finished with value: 0.6465989579540844 and parameters: {'l1_ratio': 0.003680241884233326}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:06,086] Trial 59 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.15264586783121997}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:06,368] Trial 60 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.035578561178972574}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:07,006] Trial 61 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08581853831986397}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:07,636] Trial 62 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08330567284960837}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:08,230] Trial 63 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.1260937276874145}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:08,913] Trial 64 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.18471304524617654}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:09,608] Trial 65 finished with value: 0.6606233192119854 and parameters: {'l1_ratio': 0.07236148029400408}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:09,970] Trial 66 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.028538621908627798}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:10,527] Trial 67 finished with value: 0.6734435277395772 and parameters: {'l1_ratio': 0.7392393754397737}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:11,233] Trial 68 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.30676704496346463}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:11,772] Trial 69 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.10731942653259821}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:12,369] Trial 70 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.2351430882761184}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244

Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:12,870] Trial 71 finished with value: 0.6606233192119854 and parameters: {'l1_ratio': 0.06379312836662333}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:13,371] Trial 72 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08921762169429782}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:13,845] Trial 73 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.14681271880353555}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:14,271] Trial 74 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.1687992366288067}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:14,736] Trial 75 finished with value: 0.6606233192119854 and parameters: {'l1_ratio': 0.06853156162975486}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:15,198] Trial 76 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.11529911270882556}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:15,410] Trial 77 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.025356817101024554}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:15,853] Trial 78 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.20773235007165586}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:16,221] Trial 79 finished with value: 0.6734435277395772 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:16,450] Trial 80 finished with value: 0.6465989579540844 and parameters: {'l1_ratio': 0.0005773505799185757}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:16,916] Trial 81 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.09679318198153261}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:17,384] Trial 82 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.09003484947804323}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:17,680] Trial 83 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.05263140221154804}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:18,150] Trial 84 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.13497361930435753}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:18,689] Trial 85 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.168057845175398}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:19,151] Trial 86 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.5196302291802515}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:19,643] Trial 87 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08042102311245085}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:20,084] Trial 88 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.4267760832492539}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:20,379] Trial 89 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.0513087996137776}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:20,847] Trial 90 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.11584842290519062}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:21,346] Trial 91 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.07959529149778204}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:21,819] Trial 92 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.14456403564943693}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:22,078] Trial 93 finished with value: 0.6473957707030884 and parameters: {'l1_ratio': 0.0230113520575482}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:22,588] Trial 94 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.10635427570541062}. Best is trial 12 with value: 0.6767935319779428.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:23,058] Trial 95 finished with value: 0.6767935319779428 and parameters: {'l1_ratio': 0.08326155853334134}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:27:23,361] Trial 96 finished with value: 0.6482468345328757 and parameters: {'l1_ratio': 0.045491659518159096}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:23,818] Trial 97 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.19630184676846454}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:24,275] Trial 98 finished with value: 0.6750914043183683 and parameters: {'l1_ratio': 0.2693647570253769}. Best is trial 12 with value: 0.6767935319779428.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6297872340425532

[I 2024-04-15 17:27:24,788] A new study created in memory with name: no-name-283207f5-9f0c-4dda-8e23-a44591a31414

Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:27:24,778] Trial 99 finished with value: 0.6759424681481556 and parameters: {'l1_ratio': 0.1315403372981412}. Best is trial 12 with value: 0.6767935319779428.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.6767935319779428], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 35, 866892), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 36, 525241), params={'l1_ratio': 0.0873928389796849}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=12, value=None)


* Best Score for C-index:
 0.6767935319779428

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2515901749755985
Fold 2 IBS: 0.18858261003685164
Fold 3 IBS: 0.2292920841299743
Fold 4 IBS: 0.22309648532344112
Fold 5 IBS: 0.20605265728959898
[I 2024-04-15 17:27:25,275] Trial 0 finished with value: 0.21972280235109293 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.21972280235109293.
Fold 1 IBS: 0.2516047274950201
Fold 2 IBS: 0.18861654294846003
Fold 3 IBS: 0.22828249837494724
Fold 4 IBS: 0.22300001654003024
Fold 5 IBS: 0.20725123192572797
[I 2024-04-15 17:27:25,831] Trial 1 finished with value: 0.21975100345683712 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.21972280235109293.
Fold 1 IBS: 0.2515771273750895
Fold 2 IBS: 0.18856022235091993
Fold 3 IBS: 0.22808587657282242
Fold 4 IBS: 0.22299628787333223
Fold 5 IBS: 0.20718466250448006
[I 2024-04-15 17:27:26,313] Trial 2 finished with value: 0.21968083533532884 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.2515744050705731
Fold 2 IBS: 0.18857841138888595
Fold 3 IBS: 0.22903274880552443
Fold 4 IBS: 0.22298228538918438
Fold 5 IBS: 0.20731883568212658
[I 2024-04-15 17:27:26,763] Trial 3 finished with value: 0.21989733726725888 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.25161408451006606
Fold 2 IBS: 0.18857086705333614
Fold 3 IBS: 0.22934452358550703
Fold 4 IBS: 0.2231104069171783
Fold 5 IBS: 0.20610293999761817
[I 2024-04-15 17:27:27,206] Trial 4 finished with value: 0.21974856441274113 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.251610950297687
Fold 2 IBS: 0.18860165513847751
Fold 3 IBS: 0.22873802097558302
Fold 4 IBS: 0.22296505588076254
Fold 5 IBS: 0.2073068116302705
[I 2024-04-15 17:27:27,670] Trial 5 finished with value: 0.2198444987845561 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.25159925282092155
Fold 2 IBS: 0.18856583908101104
Fold 3 IBS: 0.2296790103289237
Fold 4 IBS: 0.2230994019671484
Fold 5 IBS: 0.20622975500057683
[I 2024-04-15 17:27:28,098] Trial 6 finished with value: 0.21983465183971634 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.2515774777201374
Fold 2 IBS: 0.1885888409313501
Fold 3 IBS: 0.22927519120097056
Fold 4 IBS: 0.22308908862558124
Fold 5 IBS: 0.20602564808848914
[I 2024-04-15 17:27:28,536] Trial 7 finished with value: 0.21971124931330568 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.2515489042024141
Fold 2 IBS: 0.18854300723139536
Fold 3 IBS: 0.22887645641246013
Fold 4 IBS: 0.22304281808577445
Fold 5 IBS: 0.20724978251305193
[I 2024-04-15 17:27:29,011] Trial 8 finished with value: 0.21985219368901915 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.2516169708823745
Fold 2 IBS: 0.18863979217389565
Fold 3 IBS: 0.22863462136308926
Fold 4 IBS: 0.223051556268181
Fold 5 IBS: 0.20720355077114125
[I 2024-04-15 17:27:29,451] Trial 9 finished with value: 0.2198292982917363 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.21968083533532884.
Fold 1 IBS: 0.25161614395211945
Fold 2 IBS: 0.1885138546982977
Fold 3 IBS: 0.22739558905593202
Fold 4 IBS: 0.22313321621820506
Fold 5 IBS: 0.2070698217055598
[I 2024-04-15 17:27:30,164] Trial 10 finished with value: 0.2195457251260228 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.2195457251260228.
Fold 1 IBS: 0.2463189012100822
Fold 2 IBS: 0.23076928444675943
Fold 3 IBS: 0.22893135995041689
Fold 4 IBS: 0.24050152270088854
Fold 5 IBS: 0.22846962603103566
[I 2024-04-15 17:27:30,440] Trial 11 finished with value: 0.23499813886783655 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.2195457251260228.
Fold 1 IBS: 0.25161555030579147
Fold 2 IBS: 0.18851448442627086
Fold 3 IBS: 0.2273941494816625
Fold 4 IBS: 0.2231323703793489
Fold 5 IBS: 0.20706831324158548
[I 2024-04-15 17:27:30,959] Trial 12 finished with value: 0.21954497356693184 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.24699665666847723
Fold 2 IBS: 0.2316961720445208
Fold 3 IBS: 0.22896767322158146
Fold 4 IBS: 0.24157714214518183
Fold 5 IBS: 0.2291470506236988
[I 2024-04-15 17:27:31,216] Trial 13 finished with value: 0.235676938940692 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.25159926443667063
Fold 2 IBS: 0.18846727482113265
Fold 3 IBS: 0.22764635263824007
Fold 4 IBS: 0.22307449594761158
Fold 5 IBS: 0.20717359128426674
[I 2024-04-15 17:27:31,987] Trial 14 finished with value: 0.21959219582558434 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.25161000831771807
Fold 2 IBS: 0.18845980078712618
Fold 3 IBS: 0.22766865842239475
Fold 4 IBS: 0.2230838091176294
Fold 5 IBS: 0.2071942452896997
[I 2024-04-15 17:27:32,618] Trial 15 finished with value: 0.2196033043869136 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.2516183749255835
Fold 2 IBS: 0.1884404495272348
Fold 3 IBS: 0.2276615229569738
Fold 4 IBS: 0.22314715014541311
Fold 5 IBS: 0.2070955450420239
[I 2024-04-15 17:27:33,302] Trial 16 finished with value: 0.21959260851944581 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.2516168739457462
Fold 2 IBS: 0.1886077859236059
Fold 3 IBS: 0.22830614915158362
Fold 4 IBS: 0.2230083004234658
Fold 5 IBS: 0.207155155336771
[I 2024-04-15 17:27:34,077] Trial 17 finished with value: 0.21973885295623452 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.2517722361695688
Fold 2 IBS: 0.18851872910411022
Fold 3 IBS: 0.22881018948817416
Fold 4 IBS: 0.22316935974268695
Fold 5 IBS: 0.20713834622273647
[I 2024-04-15 17:27:34,666] Trial 18 finished with value: 0.2198817721454553 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.25152552888599294
Fold 2 IBS: 0.18856225946136823
Fold 3 IBS: 0.22968965916076853
Fold 4 IBS: 0.22310357774683215
Fold 5 IBS: 0.2062255420539672
[I 2024-04-15 17:27:35,230] Trial 19 finished with value: 0.21982131346178582 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.2516339247783821
Fold 2 IBS: 0.18862851904227126
Fold 3 IBS: 0.22815955283632552
Fold 4 IBS: 0.223026714376196
Fold 5 IBS: 0.20713591855700675
[I 2024-04-15 17:27:35,760] Trial 20 finished with value: 0.21971692591803632 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.2515975211729727
Fold 2 IBS: 0.18849596099815272
Fold 3 IBS: 0.22754448090911072
Fold 4 IBS: 0.2231046661580643
Fold 5 IBS: 0.2071658019850713
[I 2024-04-15 17:27:36,385] Trial 21 finished with value: 0.21958168624467436 and parameters: {'l1_ratio': 0.10825799833043775}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.2516321744178892
Fold 2 IBS: 0.188468521793367
Fold 3 IBS: 0.2274496490101723
Fold 4 IBS: 0.22317059781141152
Fold 5 IBS: 0.20708041337825864
[I 2024-04-15 17:27:37,067] Trial 22 finished with value: 0.21956027128221972 and parameters: {'l1_ratio': 0.10159828709381563}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.25157456162752195
Fold 2 IBS: 0.18853458293026157
Fold 3 IBS: 0.22801705881662365
Fold 4 IBS: 0.22306143361969943
Fold 5 IBS: 0.2071701460009309
[I 2024-04-15 17:27:37,658] Trial 23 finished with value: 0.2196715565990075 and parameters: {'l1_ratio': 0.20521786879010379}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.25158056641790105
Fold 2 IBS: 0.1886186942431977
Fold 3 IBS: 0.22847344086229351
Fold 4 IBS: 0.22295713180192345
Fold 5 IBS: 0.20724246176614888
[I 2024-04-15 17:27:38,262] Trial 24 finished with value: 0.2197744590182929 and parameters: {'l1_ratio': 0.3389201479305571}. Best is trial 12 with value: 0.21954497356693184.

Fold 1 IBS: 0.2517558250797045
Fold 2 IBS: 0.22831284027786944
Fold 3 IBS: 0.2288517859642901
Fold 4 IBS: 0.2376370340824302
Fold 5 IBS: 0.22662832135964203
[I 2024-04-15 17:27:38,731] Trial 25 finished with value: 0.23463716135278725 and parameters: {'l1_ratio': 0.03981317955666948}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.25158208088435086
Fold 2 IBS: 0.18851476319883065
Fold 3 IBS: 0.22786796404123397
Fold 4 IBS: 0.22300557477574828
Fold 5 IBS: 0.2071728242046949
[I 2024-04-15 17:27:39,571] Trial 26 finished with value: 0.21962864142097174 and parameters: {'l1_ratio': 0.18783928730207888}. Best is trial 12 with value: 0.21954497356693184.
Fold 1 IBS: 0.25160373191034385
Fold 2 IBS: 0.18851369676515642
Fold 3 IBS: 0.2273527594397358
Fold 4 IBS: 0.22315496471016386
Fold 5 IBS: 0.2070486022039014
[I 2024-04-15 17:27:40,431] Trial 27 finished with value: 0.21953475100586023 and parameters: {'l1_ratio': 0.07505393448412474}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515765351689792
Fold 2 IBS: 0.18853538185081606
Fold 3 IBS: 0.22916018390512669
Fold 4 IBS: 0.22303857298238947
Fold 5 IBS: 0.20734850968205926
[I 2024-04-15 17:27:40,880] Trial 28 finished with value: 0.21993183671787414 and parameters: {'l1_ratio': 0.6145983886185702}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516039495649914
Fold 2 IBS: 0.1885044096839334
Fold 3 IBS: 0.2295417580420553
Fold 4 IBS: 0.22306176396260377
Fold 5 IBS: 0.2061631515946513
[I 2024-04-15 17:27:41,346] Trial 29 finished with value: 0.21977500656964705 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516187507411122
Fold 2 IBS: 0.18864761954336792
Fold 3 IBS: 0.22839522577295332
Fold 4 IBS: 0.22306095622358285
Fold 5 IBS: 0.20717375011067218
[I 2024-04-15 17:27:41,987] Trial 30 finished with value: 0.21977926047833768 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516242651687462
Fold 2 IBS: 0.18852309972022385
Fold 3 IBS: 0.2274210940995219
Fold 4 IBS: 0.2232085098206134
Fold 5 IBS: 0.20707592732917204
[I 2024-04-15 17:27:42,901] Trial 31 finished with value: 0.2195705792276555 and parameters: {'l1_ratio': 0.09232011433900482}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516155368448421
Fold 2 IBS: 0.18848148592383698
Fold 3 IBS: 0.22880620089765477
Fold 4 IBS: 0.22322198577054203
Fold 5 IBS: 0.20710098970245264
[I 2024-04-15 17:27:43,619] Trial 32 finished with value: 0.21984523982786572 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515542713526758
Fold 2 IBS: 0.1884658656030139
Fold 3 IBS: 0.22791967983547234
Fold 4 IBS: 0.2231075815524371
Fold 5 IBS: 0.20712804389264258
[I 2024-04-15 17:27:44,255] Trial 33 finished with value: 0.21963508844724836 and parameters: {'l1_ratio': 0.18182479242429683}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25159353764498843
Fold 2 IBS: 0.18854864656737869
Fold 3 IBS: 0.2281102065397275
Fold 4 IBS: 0.22300820932610846
Fold 5 IBS: 0.2072125464937422
[I 2024-04-15 17:27:44,850] Trial 34 finished with value: 0.21969462931438904 and parameters: {'l1_ratio': 0.23148463885526435}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.24714044850659217
Fold 2 IBS: 0.23189351976008712
Fold 3 IBS: 0.2289757768177997
Fold 4 IBS: 0.24180544204101134
Fold 5 IBS: 0.22928987295983994
[I 2024-04-15 17:27:45,130] Trial 35 finished with value: 0.23582101201706607 and parameters: {'l1_ratio': 0.0013526982279536137}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25155708073893945
Fold 2 IBS: 0.18855676769828172
Fold 3 IBS: 0.2282651932037952
Fold 4 IBS: 0.22296678975997522
Fold 5 IBS: 0.20717627949832942
[I 2024-04-15 17:27:45,648] Trial 36 finished with value: 0.21970442217986422 and parameters: {'l1_ratio': 0.26966204197246835}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25161217587230994
Fold 2 IBS: 0.18852099660068106
Fold 3 IBS: 0.22737600684927334
Fold 4 IBS: 0.22323370206742169
Fold 5 IBS: 0.2070588250025122
[I 2024-04-15 17:27:46,467] Trial 37 finished with value: 0.21956034127843962 and parameters: {'l1_ratio': 0.08289550773699635}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515971225716062
Fold 2 IBS: 0.18856582011435247
Fold 3 IBS: 0.22861782337980582
Fold 4 IBS: 0.22300859812786727
Fold 5 IBS: 0.20726104653519928
[I 2024-04-15 17:27:46,947] Trial 38 finished with value: 0.2198100821457662 and parameters: {'l1_ratio': 0.3752900822742875}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25158097607246954
Fold 2 IBS: 0.18857127043398167
Fold 3 IBS: 0.22879279578770315
Fold 4 IBS: 0.2230054221640003
Fold 5 IBS: 0.207280486970528
[I 2024-04-15 17:27:47,443] Trial 39 finished with value: 0.21984619028573654 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516180863305236
Fold 2 IBS: 0.18859869651792063
Fold 3 IBS: 0.22898537961470034
Fold 4 IBS: 0.222955632729996
Fold 5 IBS: 0.20736721612874018
[I 2024-04-15 17:27:47,970] Trial 40 finished with value: 0.21990500226437612 and parameters: {'l1_ratio': 0.5256815907636119}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25159946542120953
Fold 2 IBS: 0.18852074032704527
Fold 3 IBS: 0.22733307392536437
Fold 4 IBS: 0.22314538450984725
Fold 5 IBS: 0.2071484284005849
[I 2024-04-15 17:27:49,500] Trial 41 finished with value: 0.21954941851681026 and parameters: {'l1_ratio': 0.07419373672571489}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516331593760254
Fold 2 IBS: 0.18845685367647605
Fold 3 IBS: 0.22767754359314898
Fold 4 IBS: 0.22308747959652778
Fold 5 IBS: 0.20708341909612796
[I 2024-04-15 17:27:50,317] Trial 42 finished with value: 0.2195876910676612 and parameters: {'l1_ratio': 0.14624639012866353}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2517482900486442
Fold 2 IBS: 0.22817120105752814
Fold 3 IBS: 0.22884806549327094
Fold 4 IBS: 0.2374713396804501
Fold 5 IBS: 0.2265201035285112
[I 2024-04-15 17:27:50,760] Trial 43 finished with value: 0.2345517999616809 and parameters: {'l1_ratio': 0.041583247277212944}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516164798879633
Fold 2 IBS: 0.18848199157730966
Fold 3 IBS: 0.22758103314413802
Fold 4 IBS: 0.22312327908527133
Fold 5 IBS: 0.20707626866320314
[I 2024-04-15 17:27:51,483] Trial 44 finished with value: 0.2195758104715771 and parameters: {'l1_ratio': 0.11095503291865386}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25163611771941036
Fold 2 IBS: 0.18847733574030626
Fold 3 IBS: 0.22788858123602035
Fold 4 IBS: 0.22309590127449846
Fold 5 IBS: 0.20710481540133382
[I 2024-04-15 17:27:52,140] Trial 45 finished with value: 0.2196405502743138 and parameters: {'l1_ratio': 0.17847078855209234}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25154596318989
Fold 2 IBS: 0.188528258167401
Fold 3 IBS: 0.2294709802396596
Fold 4 IBS: 0.22303113423620896
Fold 5 IBS: 0.20616530622503002
[I 2024-04-15 17:27:52,756] Trial 46 finished with value: 0.21974832841163788 and parameters: {'l1_ratio': 0.8167652444349325}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2517641770863354
Fold 2 IBS: 0.22754437152115484
Fold 3 IBS: 0.22883291667977118
Fold 4 IBS: 0.23673755131845065
Fold 5 IBS: 0.22603854105507099
[I 2024-04-15 17:27:53,347] Trial 47 finished with value: 0.2341835115321566 and parameters: {'l1_ratio': 0.04968988578514158}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516004573012397
Fold 2 IBS: 0.18847832906050263
Fold 3 IBS: 0.22779609494652767
Fold 4 IBS: 0.22313683514603136
Fold 5 IBS: 0.20718773179707028
[I 2024-04-15 17:27:53,989] Trial 48 finished with value: 0.21963988965027434 and parameters: {'l1_ratio': 0.15834401796106617}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25155303739828716
Fold 2 IBS: 0.18855944494228366
Fold 3 IBS: 0.22825797337027137
Fold 4 IBS: 0.22296406762022083
Fold 5 IBS: 0.20716788852941234
[I 2024-04-15 17:27:54,732] Trial 49 finished with value: 0.21970048237209508 and parameters: {'l1_ratio': 0.268381443520631}. Best is trial 27 with value: 0.21953475100586023.

Fold 1 IBS: 0.25157283476309095
Fold 2 IBS: 0.188518438507461
Fold 3 IBS: 0.2274894350667155
Fold 4 IBS: 0.2231905141924281
Fold 5 IBS: 0.20711743659256523
[I 2024-04-15 17:27:55,448] Trial 50 finished with value: 0.21957773182445214 and parameters: {'l1_ratio': 0.10438246262749007}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25161313178751893
Fold 2 IBS: 0.1885009692084376
Fold 3 IBS: 0.2273845031216082
Fold 4 IBS: 0.2231742041630635
Fold 5 IBS: 0.20707753492010803
[I 2024-04-15 17:27:56,131] Trial 51 finished with value: 0.2195500686401472 and parameters: {'l1_ratio': 0.07683940226987503}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.24559521233044804
Fold 2 IBS: 0.2297823454798514
Fold 3 IBS: 0.22889621945120459
Fold 4 IBS: 0.2393529615265275
Fold 5 IBS: 0.2277379394307792
[I 2024-04-15 17:27:56,544] Trial 52 finished with value: 0.23427293564376214 and parameters: {'l1_ratio': 0.022665207963687185}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516110372458361
Fold 2 IBS: 0.18844582503848947
Fold 3 IBS: 0.2276379862493684
Fold 4 IBS: 0.223140428183463
Fold 5 IBS: 0.20708152202076033
[I 2024-04-15 17:27:57,316] Trial 53 finished with value: 0.21958335974758345 and parameters: {'l1_ratio': 0.1332942954625656}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25176219850331744
Fold 2 IBS: 0.22692878918094708
Fold 3 IBS: 0.22882027000142438
Fold 4 IBS: 0.23601629734582583
Fold 5 IBS: 0.2255614771863888
[I 2024-04-15 17:27:57,720] Trial 54 finished with value: 0.2338178064435807 and parameters: {'l1_ratio': 0.058113193716779116}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25164206469822087
Fold 2 IBS: 0.18858213924070316
Fold 3 IBS: 0.22802612219751403
Fold 4 IBS: 0.22309942969570987
Fold 5 IBS: 0.20713617774590193
[I 2024-04-15 17:27:58,474] Trial 55 finished with value: 0.21969718671560998 and parameters: {'l1_ratio': 0.21880590526227123}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25156635000927763
Fold 2 IBS: 0.18852094460753463
Fold 3 IBS: 0.22747862669812496
Fold 4 IBS: 0.2231851561311877
Fold 5 IBS: 0.20710962325650775
[I 2024-04-15 17:27:59,218] Trial 56 finished with value: 0.21957214014052653 and parameters: {'l1_ratio': 0.10361946090422008}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.24676188617856978
Fold 2 IBS: 0.23137491968110918
Fold 3 IBS: 0.22895474901477075
Fold 4 IBS: 0.2412045519233964
Fold 5 IBS: 0.22891323224641047
[I 2024-04-15 17:27:59,511] Trial 57 finished with value: 0.23544186780885132 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516236282824228
Fold 2 IBS: 0.1884511032892353
Fold 3 IBS: 0.2276197214837043
Fold 4 IBS: 0.22313251639453888
Fold 5 IBS: 0.20718561252774165
[I 2024-04-15 17:28:00,105] Trial 58 finished with value: 0.21960251639552858 and parameters: {'l1_ratio': 0.13178546969215243}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2517715121109756
Fold 2 IBS: 0.18852188013881593
Fold 3 IBS: 0.2288105277552922
Fold 4 IBS: 0.22316501694920263
Fold 5 IBS: 0.20713100540986437
[I 2024-04-15 17:28:00,684] Trial 59 finished with value: 0.21987998847283013 and parameters: {'l1_ratio': 0.06653443322542048}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515434438067849
Fold 2 IBS: 0.18855153634734748
Fold 3 IBS: 0.22911235028664667
Fold 4 IBS: 0.22301748069224928
Fold 5 IBS: 0.20604295921935212
[I 2024-04-15 17:28:01,221] Trial 60 finished with value: 0.2196535540704761 and parameters: {'l1_ratio': 0.5892984254164416}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515608101372645
Fold 2 IBS: 0.18850570000221792
Fold 3 IBS: 0.22741435978616745
Fold 4 IBS: 0.22314417149238797
Fold 5 IBS: 0.20708945015344643
[I 2024-04-15 17:28:01,966] Trial 61 finished with value: 0.21954289831429685 and parameters: {'l1_ratio': 0.08497028745341434}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25156467000880584
Fold 2 IBS: 0.18844940023182957
Fold 3 IBS: 0.22788708801531482
Fold 4 IBS: 0.22305331517159274
Fold 5 IBS: 0.20713770737747905
[I 2024-04-15 17:28:02,635] Trial 62 finished with value: 0.21961843616100438 and parameters: {'l1_ratio': 0.16710130692917768}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2447771647396264
Fold 2 IBS: 0.22866932076233487
Fold 3 IBS: 0.22886161002851596
Fold 4 IBS: 0.23805384448607866
Fold 5 IBS: 0.22689970549319102
[I 2024-04-15 17:28:03,018] Trial 63 finished with value: 0.23345232910194938 and parameters: {'l1_ratio': 0.035453949085886734}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516185355318589
Fold 2 IBS: 0.1885099439010188
Fold 3 IBS: 0.22740456099903808
Fold 4 IBS: 0.22313846962798647
Fold 5 IBS: 0.2070792727054537
[I 2024-04-15 17:28:03,698] Trial 64 finished with value: 0.21955015655307117 and parameters: {'l1_ratio': 0.08437179296307856}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516248528224957
Fold 2 IBS: 0.1884864808652223
Fold 3 IBS: 0.22763315057565398
Fold 4 IBS: 0.22308664688078453
Fold 5 IBS: 0.2070982005443986
[I 2024-04-15 17:28:04,347] Trial 65 finished with value: 0.219585866337711 and parameters: {'l1_ratio': 0.12362971823759578}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25176755658347477
Fold 2 IBS: 0.1885195201774315
Fold 3 IBS: 0.22881801057902912
Fold 4 IBS: 0.23587115983991183
Fold 5 IBS: 0.20711009190091423
[I 2024-04-15 17:28:04,977] Trial 66 finished with value: 0.2224172678161523 and parameters: {'l1_ratio': 0.05986649514948058}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25156268857105635
Fold 2 IBS: 0.18854315781680256
Fold 3 IBS: 0.22799422445230952
Fold 4 IBS: 0.22305284689471597
Fold 5 IBS: 0.20715090481408377
[I 2024-04-15 17:28:05,606] Trial 67 finished with value: 0.2196607645097936 and parameters: {'l1_ratio': 0.20236320980065475}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25157692690837347
Fold 2 IBS: 0.18860017309458144
Fold 3 IBS: 0.22815574362221872
Fold 4 IBS: 0.22305320776616888
Fold 5 IBS: 0.207195257139859
[I 2024-04-15 17:28:06,234] Trial 68 finished with value: 0.2197162617062403 and parameters: {'l1_ratio': 0.2502180814795709}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515994871294253
Fold 2 IBS: 0.18853739868477928
Fold 3 IBS: 0.2274559250384038
Fold 4 IBS: 0.2232133344716385
Fold 5 IBS: 0.2071431885922309
[I 2024-04-15 17:28:06,947] Trial 69 finished with value: 0.21958986678329556 and parameters: {'l1_ratio': 0.08072819111759641}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.24523328291214036
Fold 2 IBS: 0.22928965418703187
Fold 3 IBS: 0.22888019680461616
Fold 4 IBS: 0.2387783524315844
Fold 5 IBS: 0.22736859264587883
[I 2024-04-15 17:28:07,351] Trial 70 finished with value: 0.23391001579625031 and parameters: {'l1_ratio': 0.028179134247833}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516177164475923
Fold 2 IBS: 0.18853320778344268
Fold 3 IBS: 0.2273977931225704
Fold 4 IBS: 0.22319617974769812
Fold 5 IBS: 0.20705311684271668
[I 2024-04-15 17:28:08,234] Trial 71 finished with value: 0.21955960278880404 and parameters: {'l1_ratio': 0.09082080375317397}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25163233529348494
Fold 2 IBS: 0.18846838410711514
Fold 3 IBS: 0.22782635510548493
Fold 4 IBS: 0.22302861554217202
Fold 5 IBS: 0.20708910661989233
[I 2024-04-15 17:28:08,887] Trial 72 finished with value: 0.2196089593336299 and parameters: {'l1_ratio': 0.1611293110149502}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516190179056847
Fold 2 IBS: 0.18853189223095357
Fold 3 IBS: 0.22740080542621446
Fold 4 IBS: 0.2231977844828994
Fold 5 IBS: 0.2070562161121248
[I 2024-04-15 17:28:09,500] Trial 73 finished with value: 0.21956114323157538 and parameters: {'l1_ratio': 0.09101333674958942}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.24691508557106825
Fold 2 IBS: 0.2315842102016128
Fold 3 IBS: 0.22896313273486155
Fold 4 IBS: 0.24144762732053593
Fold 5 IBS: 0.2290658815491321
[I 2024-04-15 17:28:09,826] Trial 74 finished with value: 0.2355951874754421 and parameters: {'l1_ratio': 0.0042570768228992195}. Best is trial 27 with value: 0.21953475100586023.

Fold 1 IBS: 0.2516216316778847
Fold 2 IBS: 0.18848965387137187
Fold 3 IBS: 0.22762467780633341
Fold 4 IBS: 0.22308259673228695
Fold 5 IBS: 0.20709200183655982
[I 2024-04-15 17:28:10,551] Trial 75 finished with value: 0.21958211238488734 and parameters: {'l1_ratio': 0.12295487228655186}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25156666498020597
Fold 2 IBS: 0.1885402793435447
Fold 3 IBS: 0.22800189108248853
Fold 4 IBS: 0.2230557257181538
Fold 5 IBS: 0.2071577454926291
[I 2024-04-15 17:28:11,155] Trial 76 finished with value: 0.2196644613234044 and parameters: {'l1_ratio': 0.20331332808738323}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25161289049064667
Fold 2 IBS: 0.1885199340137061
Fold 3 IBS: 0.2273776537442294
Fold 4 IBS: 0.22323460298163733
Fold 5 IBS: 0.20706055936917897
[I 2024-04-15 17:28:11,768] Trial 77 finished with value: 0.21956112811987966 and parameters: {'l1_ratio': 0.08299419528943816}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515692393769224
Fold 2 IBS: 0.1885969715102877
Fold 3 IBS: 0.22833535329554383
Fold 4 IBS: 0.22301851751626553
Fold 5 IBS: 0.20718221540770043
[I 2024-04-15 17:28:12,709] Trial 78 finished with value: 0.219740459421344 and parameters: {'l1_ratio': 0.2962049386068516}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2516065491007318
Fold 2 IBS: 0.18857456863281882
Fold 3 IBS: 0.22933353791271094
Fold 4 IBS: 0.22310602121346443
Fold 5 IBS: 0.2060826351034052
[I 2024-04-15 17:28:13,386] Trial 79 finished with value: 0.21974066239262627 and parameters: {'l1_ratio': 0.7120921418578845}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2517527024707115
Fold 2 IBS: 0.22779683568075712
Fold 3 IBS: 0.22883875353538166
Fold 4 IBS: 0.2370331858931906
Fold 5 IBS: 0.22623301296840176
[I 2024-04-15 17:28:13,851] Trial 80 finished with value: 0.23433089810968855 and parameters: {'l1_ratio': 0.04636997257316786}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25156862982637823
Fold 2 IBS: 0.18851941722037305
Fold 3 IBS: 0.22748230814885984
Fold 4 IBS: 0.22318698552367333
Fold 5 IBS: 0.20711321850289505
[I 2024-04-15 17:28:14,539] Trial 81 finished with value: 0.21957411184443593 and parameters: {'l1_ratio': 0.10387879028206692}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25161294468691686
Fold 2 IBS: 0.1884578388214353
Fold 3 IBS: 0.22767456777976522
Fold 4 IBS: 0.22308625275852859
Fold 5 IBS: 0.20719463204897148
[I 2024-04-15 17:28:15,316] Trial 82 finished with value: 0.2196052472191235 and parameters: {'l1_ratio': 0.14598729530222154}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25163086231953086
Fold 2 IBS: 0.18850115825014166
Fold 3 IBS: 0.22880837790338066
Fold 4 IBS: 0.2231929005408743
Fold 5 IBS: 0.20705114421951865
[I 2024-04-15 17:28:15,955] Trial 83 finished with value: 0.2198368886466892 and parameters: {'l1_ratio': 0.06879295166686587}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.245346680211898
Fold 2 IBS: 0.22944396934180222
Fold 3 IBS: 0.22888509952971353
Fold 4 IBS: 0.2389584072816043
Fold 5 IBS: 0.22748456719351712
[I 2024-04-15 17:28:16,366] Trial 84 finished with value: 0.23402374471170706 and parameters: {'l1_ratio': 0.026427820436960583}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515672390452638
Fold 2 IBS: 0.1884680866798261
Fold 3 IBS: 0.22751287138996004
Fold 4 IBS: 0.22314404658564224
Fold 5 IBS: 0.20711600506929975
[I 2024-04-15 17:28:17,093] Trial 85 finished with value: 0.21956164975399836 and parameters: {'l1_ratio': 0.11411691335244145}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515882663830264
Fold 2 IBS: 0.1885101927447586
Fold 3 IBS: 0.227881206622052
Fold 4 IBS: 0.22301053225889308
Fold 5 IBS: 0.20718377512467245
[I 2024-04-15 17:28:17,906] Trial 86 finished with value: 0.2196347946266805 and parameters: {'l1_ratio': 0.1892710067763575}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25156148713734783
Fold 2 IBS: 0.18850457853018016
Fold 3 IBS: 0.22741696020200922
Fold 4 IBS: 0.22314567841657998
Fold 5 IBS: 0.20709215472741252
[I 2024-04-15 17:28:18,599] Trial 87 finished with value: 0.21954417180270594 and parameters: {'l1_ratio': 0.08512979784768594}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25159089941929397
Fold 2 IBS: 0.18842175788131194
Fold 3 IBS: 0.227776330619422
Fold 4 IBS: 0.2231292835374098
Fold 5 IBS: 0.2071711877635907
[I 2024-04-15 17:28:19,410] Trial 88 finished with value: 0.2196178918442057 and parameters: {'l1_ratio': 0.15651318424310018}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25175672856918824
Fold 2 IBS: 0.22772115518935904
Fold 3 IBS: 0.22883696559954747
Fold 4 IBS: 0.2369445763280204
Fold 5 IBS: 0.22617478942951388
[I 2024-04-15 17:28:19,867] Trial 89 finished with value: 0.2342868430231258 and parameters: {'l1_ratio': 0.047357249187864006}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25158246317724775
Fold 2 IBS: 0.18849696319714868
Fold 3 IBS: 0.22743684927260294
Fold 4 IBS: 0.223157117535737
Fold 5 IBS: 0.20710969821863498
[I 2024-04-15 17:28:20,638] Trial 90 finished with value: 0.21955661828027426 and parameters: {'l1_ratio': 0.08635927701883364}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25156191690039764
Fold 2 IBS: 0.18849696413055073
Fold 3 IBS: 0.22739052712846503
Fold 4 IBS: 0.22317967452265458
Fold 5 IBS: 0.20708698591709687
[I 2024-04-15 17:28:21,389] Trial 91 finished with value: 0.21954321371983299 and parameters: {'l1_ratio': 0.07736175498535955}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25176352790507145
Fold 2 IBS: 0.18848618515701782
Fold 3 IBS: 0.22881375828547595
Fold 4 IBS: 0.2355784771114414
Fold 5 IBS: 0.20706827954360757
[I 2024-04-15 17:28:21,929] Trial 92 finished with value: 0.22234204560052281 and parameters: {'l1_ratio': 0.06346458348789051}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25158529553653836
Fold 2 IBS: 0.1884664979944722
Fold 3 IBS: 0.22757626033504205
Fold 4 IBS: 0.22311328972180391
Fold 5 IBS: 0.20714883196511819
[I 2024-04-15 17:28:22,580] Trial 93 finished with value: 0.21957803511059493 and parameters: {'l1_ratio': 0.1282478702593809}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2454081701417589
Fold 2 IBS: 0.22952766577607675
Fold 3 IBS: 0.22888780330287065
Fold 4 IBS: 0.23905603331690511
Fold 5 IBS: 0.22754735736999585
[I 2024-04-15 17:28:22,918] Trial 94 finished with value: 0.23408540598152144 and parameters: {'l1_ratio': 0.025487327471097103}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.25163557401947373
Fold 2 IBS: 0.18847776755573759
Fold 3 IBS: 0.22788731349848843
Fold 4 IBS: 0.22309542545937114
Fold 5 IBS: 0.20710330824782996
[I 2024-04-15 17:28:23,550] Trial 95 finished with value: 0.21963987775618019 and parameters: {'l1_ratio': 0.17833651479843549}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.251568590593565
Fold 2 IBS: 0.18855443613106537
Fold 3 IBS: 0.2293932880279429
Fold 4 IBS: 0.22299685422199053
Fold 5 IBS: 0.20617468263805408
[I 2024-04-15 17:28:24,095] Trial 96 finished with value: 0.21973757032252358 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515939224020422
Fold 2 IBS: 0.18852992101595664
Fold 3 IBS: 0.22880479407585863
Fold 4 IBS: 0.22324151977770343
Fold 5 IBS: 0.20713208115962986
[I 2024-04-15 17:28:24,645] Trial 97 finished with value: 0.21986044768623816 and parameters: {'l1_ratio': 0.07310061926189142}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.2515534439379948
Fold 2 IBS: 0.18858468660942954
Fold 3 IBS: 0.22957793136583768
Fold 4 IBS: 0.22307737869197009
Fold 5 IBS: 0.20624679144258007
[I 2024-04-15 17:28:25,142] Trial 98 finished with value: 0.21980804640956242 and parameters: {'l1_ratio': 0.921180749160908}. Best is trial 27 with value: 0.21953475100586023.
Fold 1 IBS: 0.24713709060144126
Fold 2 IBS: 0.2318889113868662
Fold 3 IBS: 0.22897558614450098
Fold 4 IBS: 0.24180011072330745
Fold 5 IBS: 0.2292865414641665
[I 2024-04-15 17:28:25,418] Trial 99 finished with value: 0.2358176480640565 and parameters: {'l1_ratio': 0.0013955119867413573}. Best is trial 27 with value: 0.21953475100586023.


* Best trial for IBS:
 FrozenTrial(number=27, state=TrialState.COMPLETE, values=[0.21953475100586023], datetime_start=datetime.datetime(2024, 4, 15, 17, 27, 39, 578707), datetime_complete=datetime.datetime(2024, 4, 15, 17, 27, 40, 430956), params={'l1_ratio': 0.07505393448412474}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=27, value=None)


* Best Score for IBS:
 0.21953475100586023

In [130]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [131]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.677
train_ibs:  0.22

#### Test

In [132]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [133]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.0873928389796849)

test_cindex : 0.497

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.07505393448412474)

test_ibs:  0.28

In [134]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [135]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:28:25,738] A new study created in memory with name: no-name-3f7e6d6c-4735-40bf-970e-d7be9d3a4e6a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:28:29,597] Trial 0 finished with value: 0.710731406254408 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.710731406254408.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 17:28:32,489] Trial 1 finished with value: 0.7115081949165625 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 17:28:34,727] Trial 2 finished with value: 0.7106704536611954 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:28:35,450] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:28:36,464] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:28:40,661] Trial 5 finished with value: 0.7069036810815015 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 17:28:44,537] Trial 6 finished with value: 0.6987195403755375 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:28:46,517] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:28:51,449] Trial 8 finished with value: 0.5356223175965665 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:28:54,122] Trial 9 finished with value: 0.698594318474868 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:28:54,482] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:28:55,662] Trial 11 finished with value: 0.6988496482635135 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.7819966138938776, 'max_features': None, 'min_weight_fraction_leaf': 0.1515177331819183, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:28:59,092] Trial 12 finished with value: 0.7112435076480323 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 398, 'oob_score': False, 'max_samples': 0.7986766477402025, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 1 with value: 0.7115081949165625.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 17:29:03,381] Trial 13 finished with value: 0.7164050222621745 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.8173543613589794, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12214947430735827, 'warm_start': False}. Best is trial 13 with value: 0.7164050222621745.
Fold 1 C-index: 0.651394422310757
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:05,862] Trial 14 finished with value: 0.7644780997346508 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 486, 'oob_score': True, 'max_samples': 0.9747583455834168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10847258743516168, 'warm_start': True}. Best is trial 14 with value: 0.7644780997346508.
Fold 1 C-index: 0.651394422310757

Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:08,230] Trial 15 finished with value: 0.7621525183393019 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.9914273801490951, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08807762154599924, 'warm_start': True}. Best is trial 14 with value: 0.7644780997346508.
Fold 1 C-index: 0.6633466135458167
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8155893536121673
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:11,245] Trial 16 finished with value: 0.7730522904564694 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.9631819737604822, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07564936776297793, 'warm_start': True}. Best is trial 16 with value: 0.7730522904564694.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8307984790874525
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:13,600] Trial 17 finished with value: 0.7759639944394057 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 439, 'oob_score': True, 'max_samples': 0.8933326563995619, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07106737380607278, 'warm_start': True}. Best is trial 17 with value: 0.7759639944394057.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:29:15,979] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.4897565861062015, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 17 with value: 0.7759639944394057.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:18,200] Trial 19 finished with value: 0.779878642525784 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.8603781166255321, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004005574773297965, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:19,079] Trial 20 finished with value: 0.7761848633185293 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 150, 'oob_score': True, 'max_samples': 0.8704040169883509, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012082993453436212, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:29:19,908] Trial 21 finished with value: 0.7745703131209545 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.8668664038029777, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002824367985562128, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:29:21,063] Trial 22 finished with value: 0.7645194362854836 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.6889849263379537, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04363019487768074, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8269961977186312
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 17:29:21,342] Trial 23 finished with value: 0.7646083181752001 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 21, 'oob_score': True, 'max_samples': 0.8661193629395622, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:21,996] Trial 24 finished with value: 0.7762412803729618 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.8514848199136371, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06454142840041813, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:22,554] Trial 25 finished with value: 0.7670932549825156 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.5148664808265674, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.050522250648174956, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8422053231939164
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:23,478] Trial 26 finished with value: 0.7733047036658599 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.8274176498198703, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20019523340636225, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:29:24,014] Trial 27 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 66, 'oob_score': True, 'max_samples': 0.7050102269043423, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.44630070067056304, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:29:24,986] Trial 28 finished with value: 0.7614661741676958 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.40296049098965725, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12394163557645654, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:29:26,278] Trial 29 finished with value: 0.7592210184005463 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.7451346443596092, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25087036098392035, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.

Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:29:27,032] Trial 30 finished with value: 0.7672139351461436 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 125, 'oob_score': True, 'max_samples': 0.6865450555598549, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2124753462487393, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:29:28,656] Trial 31 finished with value: 0.7751743303140853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8836899167485477, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06547059381404674, 'warm_start': True}. Best is trial 19 with value: 0.779878642525784.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:30,661] Trial 32 finished with value: 0.7813963979924544 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.9202642763321326, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08653979922868149, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:31,808] Trial 33 finished with value: 0.7719501720129386 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 238, 'oob_score': True, 'max_samples': 0.9192489093379577, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030658669633152946, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:29:33,392] Trial 34 finished with value: 0.7676882254118033 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.7640795053413063, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09768885646703014, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7703862660944206
[I 2024-04-15 17:29:33,574] Trial 35 finished with value: 0.7447419310730222 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.8487240260712599, 'max_features': None, 'min_weight_fraction_leaf': 0.0006567218019456963, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:35,432] Trial 36 finished with value: 0.7695153777707742 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.9435204690335075, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16633547129873963, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:29:36,517] Trial 37 finished with value: 0.7699950474455595 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 205, 'oob_score': True, 'max_samples': 0.7354909877351024, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12575369296783914, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 17:29:38,888] Trial 38 finished with value: 0.7748031457309299 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.6475925530300135, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.034147082140338667, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:29:40,362] Trial 39 finished with value: 0.7698295338814428 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.5584624909113933, 'max_features': None, 'min_weight_fraction_leaf': 0.08073083517270106, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 17:29:42,869] Trial 40 finished with value: 0.7748293537825441 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.9984846610843052, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05453211554010593, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:45,329] Trial 41 finished with value: 0.7784267185837241 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 449, 'oob_score': True, 'max_samples': 0.9119374397431992, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14162463422645327, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:47,730] Trial 42 finished with value: 0.7782091469964385 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.9012171439784962, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13213834082893647, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:49,999] Trial 43 finished with value: 0.7784267185837241 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 465, 'oob_score': True, 'max_samples': 0.9134886122766903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13915311695370064, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:29:52,299] Trial 44 finished with value: 0.7774555721485432 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 461, 'oob_score': True, 'max_samples': 0.9237895859439657, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1491821714913389, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:29:53,321] Trial 45 finished with value: 0.7655042185855676 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.7992703886846485, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18901901573350227, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 17:29:58,895] Trial 46 finished with value: 0.7186683694910888 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 467, 'oob_score': True, 'max_samples': 0.9186212785318524, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23641707903060583, 'warm_start': False}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:30:00,194] Trial 47 finished with value: 0.7633331807051343 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.9498264765716475, 'max_features': None, 'min_weight_fraction_leaf': 0.28110191352737646, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:30:05,068] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.2089180401928531, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14245364790954446, 'warm_start': False}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 17:30:07,493] Trial 49 finished with value: 0.7759850593499522 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 473, 'oob_score': True, 'max_samples': 0.8205329433517567, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10441275010079185, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:30:08,512] Trial 50 finished with value: 0.7767165914042369 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.7708212816735263, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17148603247038066, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:11,053] Trial 51 finished with value: 0.7789696032702027 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.906425480047823, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13884309808080356, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:13,353] Trial 52 finished with value: 0.7783608870591137 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 447, 'oob_score': True, 'max_samples': 0.969229888067673, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13413355478559338, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:15,836] Trial 53 finished with value: 0.7767277480050078 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.9752174207668408, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2232694709341223, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:18,310] Trial 54 finished with value: 0.780766062830811 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.9499867529836574, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15981527384609598, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:30:20,586] Trial 55 finished with value: 0.7776047059602514 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 402, 'oob_score': True, 'max_samples': 0.8956908841260508, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19000411205960466, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 17:30:27,471] Trial 56 finished with value: 0.7195483575403556 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 480, 'oob_score': True, 'max_samples': 0.9399839761692668, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10493636470549184, 'warm_start': False}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:30:29,516] Trial 57 finished with value: 0.7747609160069666 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 366, 'oob_score': True, 'max_samples': 0.9987535269475917, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1620041132389804, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:30:32,124] Trial 58 finished with value: 0.7759561351304726 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 419, 'oob_score': True, 'max_samples': 0.8321431103581917, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08389839323962983, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:30:32,991] Trial 59 finished with value: 0.7758732302381411 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.7877893923820578, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1499998444214115, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 17:30:38,373] Trial 60 finished with value: 0.7178137083031257 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.889027953302921, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11070844936873359, 'warm_start': False}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:41,590] Trial 61 finished with value: 0.7797516784945213 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 5, 'n_estimators': 438, 'oob_score': True, 'max_samples': 0.964846934975246, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18453199509503088, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:44,895] Trial 62 finished with value: 0.7783066359783304 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 5, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.9548094169788613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20900205678044423, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:47,806] Trial 63 finished with value: 0.7774339531979889 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 427, 'oob_score': True, 'max_samples': 0.8512105225186636, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18273395536373468, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 17:30:50,590] Trial 64 finished with value: 0.7769108586827717 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.9363303081788291, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15879530840628941, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:30:53,106] Trial 65 finished with value: 0.7767536421304642 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.9045586427364749, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23363542614511368, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:30:55,786] Trial 66 finished with value: 0.7776299058347201 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 479, 'oob_score': True, 'max_samples': 0.8662308115115174, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11900088989820741, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:30:57,869] Trial 67 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.3745280899612011, 'max_features': None, 'min_weight_fraction_leaf': 0.3355807148136194, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:31:00,045] Trial 68 finished with value: 0.7798170861760756 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 350, 'oob_score': True, 'max_samples': 0.9734106784993845, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26475829677780865, 'warm_start': True}. Best is trial 32 with value: 0.7813963979924544.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:31:02,076] Trial 69 finished with value: 0.7822254190286311 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 349, 'oob_score': True, 'max_samples': 0.9805420780206322, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2725745032335037, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:31:04,111] Trial 70 finished with value: 0.7791472374583344 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.9815491156961419, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28279132974838184, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:31:05,873] Trial 71 finished with value: 0.7807951140371256 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.9830878312069359, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28433311098476777, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:31:07,672] Trial 72 finished with value: 0.7807045064811026 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.972248594717361, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2724491033006262, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:31:09,265] Trial 73 finished with value: 0.769314923317358 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.9585304801423761, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3136324910319987, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:31:11,161] Trial 74 finished with value: 0.7782234606780676 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.9749100212322762, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2646006220378129, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:31:12,717] Trial 75 finished with value: 0.7742005776279374 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 256, 'oob_score': True, 'max_samples': 0.9980669718902726, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3078907468239062, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:31:14,643] Trial 76 finished with value: 0.7433316921364377 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 350, 'oob_score': True, 'max_samples': 0.9499196432118692, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3808353622830714, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:31:16,809] Trial 77 finished with value: 0.7798712102700238 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.9384096157933446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26750867179558074, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:31:17,769] Trial 78 finished with value: 0.7758626409015228 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.9324430398941591, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2733159216945681, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:31:19,847] Trial 79 finished with value: 0.7791360808575634 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.8802164968910117, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2492771080659749, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7889733840304183
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 17:31:24,234] Trial 80 finished with value: 0.7073832969460849 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.8451052278433803, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2908684081837041, 'warm_start': False}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.8269961977186312
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:31:26,386] Trial 81 finished with value: 0.7571813931935338 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.969010896403188, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.340568119339383, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:31:28,457] Trial 82 finished with value: 0.7789369711399738 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.9340149322949857, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25373358750815256, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:31:30,896] Trial 83 finished with value: 0.7692858721110434 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.98421151737541, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31915088144272974, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:31:33,091] Trial 84 finished with value: 0.7734715084035233 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 14, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.956865248007064, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24098877684987097, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6912350597609562
Fold 2 C-index: 0.8275193798449613
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:31:34,726] Trial 85 finished with value: 0.7662267699438681 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.9999360877761, 'max_features': None, 'min_weight_fraction_leaf': 0.29644369823968103, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:31:36,985] Trial 86 finished with value: 0.7744679981342694 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.9236490757653891, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.263466140996877, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 17:31:39,517] Trial 87 finished with value: 0.7744061713766296 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.8807880482150929, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22370530923682658, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.8384030418250951
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:31:41,716] Trial 88 finished with value: 0.7659424656664703 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 358, 'oob_score': True, 'max_samples': 0.9704002987330667, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3291212820255483, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 17:31:44,156] Trial 89 finished with value: 0.7287503023798154 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.8078509477636951, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3649756281746879, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.

Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:31:46,659] Trial 90 finished with value: 0.7775756547539369 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 411, 'oob_score': True, 'max_samples': 0.9422466821088742, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27294474464277046, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:31:48,603] Trial 91 finished with value: 0.7806433739744503 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.9710783638443833, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.29336260715091966, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.8269961977186312
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:31:50,680] Trial 92 finished with value: 0.7637839126883732 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 15, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.9178335886390463, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30724054046172317, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:31:52,806] Trial 93 finished with value: 0.7782129983282842 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.9765830204945397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.287024099650475, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.811787072243346
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:31:54,884] Trial 94 finished with value: 0.745410890852036 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 358, 'oob_score': True, 'max_samples': 0.897570367240941, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.35873851291545034, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:31:56,975] Trial 95 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.12272153158540089, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2718642595216468, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:31:57,817] Trial 96 finished with value: 0.775137279587858 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.9559867458275024, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014530988352961516, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 17:32:01,557] Trial 97 finished with value: 0.7146268975844274 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9280236824666266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2978573631689368, 'warm_start': False}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:32:03,465] Trial 98 finished with value: 0.7549796319727345 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 14, 'n_estimators': 375, 'oob_score': True, 'max_samples': 0.5918185512727777, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20001920088899483, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8403041825095057

[I 2024-04-15 17:32:05,258] A new study created in memory with name: no-name-1c5daef5-97b5-4ba9-8118-1034236987f4

Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:32:05,239] Trial 99 finished with value: 0.7773003781487885 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.8672120149366647, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25483727907416354, 'warm_start': True}. Best is trial 69 with value: 0.7822254190286311.


* Best trial for C-index:
 FrozenTrial(number=69, state=TrialState.COMPLETE, values=[0.7822254190286311], datetime_start=datetime.datetime(2024, 4, 15, 17, 31, 0, 55100), datetime_complete=datetime.datetime(2024, 4, 15, 17, 31, 2, 75615), params={'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 349, 'oob_score': True, 'max_samples': 0.9805420780206322, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2725745032335037, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=69, value=None)


* Best Score for C-index:
 0.7822254190286311

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21257719674662326
Fold 2 IBS: 0.18398794233444962
Fold 3 IBS: 0.24115863718781586
Fold 4 IBS: 0.20462806754200724
Fold 5 IBS: 0.21548153759481706
[I 2024-04-15 17:32:09,239] Trial 0 finished with value: 0.21156667628114262 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21156667628114262.
Fold 1 IBS: 0.2182423570973683
Fold 2 IBS: 0.19052803317567504
Fold 3 IBS: 0.22650891342938945
Fold 4 IBS: 0.19746718575237876
Fold 5 IBS: 0.20271818374336714
[I 2024-04-15 17:32:10,356] Trial 1 finished with value: 0.20709293463963574 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-15 17:32:10,944] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-15 17:32:13,545] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-15 17:32:15,601] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.23394547961962123
Fold 2 IBS: 0.1937000409366542
Fold 3 IBS: 0.22629873828635783
Fold 4 IBS: 0.18175312867404605
Fold 5 IBS: 0.19984130360465496
[I 2024-04-15 17:32:18,456] Trial 5 finished with value: 0.20710773822426684 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.2105781079197662
Fold 2 IBS: 0.19520741280503734
Fold 3 IBS: 0.2539054626067449
Fold 4 IBS: 0.20281838308140923
Fold 5 IBS: 0.21783990352252658
[I 2024-04-15 17:32:21,140] Trial 6 finished with value: 0.21606985398709683 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.24019163902400478
Fold 2 IBS: 0.22714862444768746
Fold 3 IBS: 0.2276535034944022
Fold 4 IBS: 0.23447823721247205
Fold 5 IBS: 0.22347918211586645
[I 2024-04-15 17:32:24,416] Trial 7 finished with value: 0.23059023725888655 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-15 17:32:29,799] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.2213823275153312
Fold 2 IBS: 0.18965705253317364
Fold 3 IBS: 0.21336390827447985
Fold 4 IBS: 0.20439902780858185
Fold 5 IBS: 0.20874307784383053
[I 2024-04-15 17:32:30,859] Trial 9 finished with value: 0.20750907879507943 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-15 17:32:32,492] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.16702313936856283
Fold 2 IBS: 0.21598263853358704
Fold 3 IBS: 0.25958384079254265
Fold 4 IBS: 0.2257880305518168
Fold 5 IBS: 0.24054822368474593
[I 2024-04-15 17:32:32,669] Trial 11 finished with value: 0.221785174586251 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 1 with value: 0.20709293463963574.
Fold 1 IBS: 0.23073306807088928
Fold 2 IBS: 0.19074344451775943
Fold 3 IBS: 0.21939209190030753
Fold 4 IBS: 0.18400698569459417
Fold 5 IBS: 0.1960749139489405
[I 2024-04-15 17:32:35,553] Trial 12 finished with value: 0.2041901008264982 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11583591034272536}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.22859599710500828
Fold 2 IBS: 0.18667914588450446
Fold 3 IBS: 0.2222120973543907
Fold 4 IBS: 0.18909655873502665
Fold 5 IBS: 0.1989916472780389
[I 2024-04-15 17:32:37,536] Trial 13 finished with value: 0.20511508927139382 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1500889029036846}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.2169150809341789
Fold 2 IBS: 0.19138403314094124
Fold 3 IBS: 0.22464076933265154
Fold 4 IBS: 0.19520798424309047
Fold 5 IBS: 0.20691900878851352
[I 2024-04-15 17:32:39,839] Trial 14 finished with value: 0.20701337528787517 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.9495341510893635, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2812321272168262}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.24091755327306158
Fold 2 IBS: 0.19100758605343104
Fold 3 IBS: 0.22355914787441317
Fold 4 IBS: 0.18679639754254324
Fold 5 IBS: 0.19876652834081698
[I 2024-04-15 17:32:42,076] Trial 15 finished with value: 0.2082094426168532 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 165, 'oob_score': False, 'max_samples': 0.8145452663200455, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08745406506274991}. Best is trial 12 with value: 0.2041901008264982.

Fold 1 IBS: 0.2395808329353907
Fold 2 IBS: 0.19374342263270897
Fold 3 IBS: 0.22363517522107063
Fold 4 IBS: 0.1803227406212177
Fold 5 IBS: 0.19820543789370149
[I 2024-04-15 17:32:47,747] Trial 16 finished with value: 0.2070975218608179 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12075256052520705}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.23738933831002879
Fold 2 IBS: 0.19700239211577708
Fold 3 IBS: 0.21367682532380514
Fold 4 IBS: 0.19151330901869923
Fold 5 IBS: 0.2002249779027475
[I 2024-04-15 17:32:51,768] Trial 17 finished with value: 0.20796136853421152 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8076169183570886, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008930026627508747}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.21689786528123065
Fold 2 IBS: 0.1934083206928193
Fold 3 IBS: 0.22169030773002818
Fold 4 IBS: 0.1979722292179608
Fold 5 IBS: 0.20694952936451252
[I 2024-04-15 17:32:54,918] Trial 18 finished with value: 0.20738365045731028 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.7929259088439878, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24613176016258595}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.21701162863390008
Fold 2 IBS: 0.1933175075151711
Fold 3 IBS: 0.22174587804944487
Fold 4 IBS: 0.19141069078394765
Fold 5 IBS: 0.2027194824532865
[I 2024-04-15 17:32:58,432] Trial 19 finished with value: 0.20524103748715006 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.61983522247769, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17887143804406985}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.216633868848479
Fold 2 IBS: 0.19315547242745565
Fold 3 IBS: 0.22298961211316834
Fold 4 IBS: 0.19755625873293692
Fold 5 IBS: 0.2071340270764462
[I 2024-04-15 17:33:00,766] Trial 20 finished with value: 0.2074938478396972 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.9896627645374068, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3184109663462648}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.2165067777195507
Fold 2 IBS: 0.19426602722031538
Fold 3 IBS: 0.22345277892399243
Fold 4 IBS: 0.1948637741118911
Fold 5 IBS: 0.20394368858932982
[I 2024-04-15 17:33:04,557] Trial 21 finished with value: 0.2066066093130159 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 409, 'oob_score': False, 'max_samples': 0.5934683841410309, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1777372518975414}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.22030367938022785
Fold 2 IBS: 0.19577532135036657
Fold 3 IBS: 0.2205675591726556
Fold 4 IBS: 0.19879450689534872
Fold 5 IBS: 0.2032304405627535
[I 2024-04-15 17:33:09,351] Trial 22 finished with value: 0.20773430147227043 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.40446394428723687, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11724335523521127}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.21971923207751018
Fold 2 IBS: 0.19552054768806834
Fold 3 IBS: 0.21730137610331468
Fold 4 IBS: 0.20273950762823595
Fold 5 IBS: 0.2044699777024888
[I 2024-04-15 17:33:13,207] Trial 23 finished with value: 0.20795012823992357 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.6435198653021434, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21106350745469335}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.23444599453101114
Fold 2 IBS: 0.1907325179408185
Fold 3 IBS: 0.2223061160766117
Fold 4 IBS: 0.18330872541209006
Fold 5 IBS: 0.1995756754415504
[I 2024-04-15 17:33:16,661] Trial 24 finished with value: 0.20607380588041635 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.872695842890043, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13524249629896928}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.21703401253166968
Fold 2 IBS: 0.19782598410287708
Fold 3 IBS: 0.2228501342163535
Fold 4 IBS: 0.19917706540493793
Fold 5 IBS: 0.20765017328944108
[I 2024-04-15 17:33:18,207] Trial 25 finished with value: 0.20890747390905587 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 149, 'oob_score': False, 'max_samples': 0.7525415879931654, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24020694158155206}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.2278528872209523
Fold 2 IBS: 0.2109307354195749
Fold 3 IBS: 0.2264002995968333
Fold 4 IBS: 0.21462110123766845
Fold 5 IBS: 0.2114109798735705
[I 2024-04-15 17:33:20,544] Trial 26 finished with value: 0.21824320066971986 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 5, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.4704864355905733, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04277631919037671}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.21405108057872077
Fold 2 IBS: 0.19141668136844153
Fold 3 IBS: 0.22453883357208512
Fold 4 IBS: 0.1977158450241192
Fold 5 IBS: 0.2050353433139227
[I 2024-04-15 17:33:21,279] Trial 27 finished with value: 0.2065515567714579 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.625873742088694, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18184651180637382}. Best is trial 12 with value: 0.2041901008264982.
Fold 1 IBS: 0.22514266901365382
Fold 2 IBS: 0.18840052090055528
Fold 3 IBS: 0.21546306043245098
Fold 4 IBS: 0.1912619878256766
Fold 5 IBS: 0.19953633746292376
[I 2024-04-15 17:33:24,892] Trial 28 finished with value: 0.2039609151270521 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.27487888259278787, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.059745129186282386}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2290234556731903
Fold 2 IBS: 0.19793216896887506
Fold 3 IBS: 0.2121071697132408
Fold 4 IBS: 0.2017776355758101
Fold 5 IBS: 0.20477314505268296
[I 2024-04-15 17:33:28,305] Trial 29 finished with value: 0.20912271499675983 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 366, 'oob_score': False, 'max_samples': 0.1495897230999219, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03512426120851289}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2236171776970423
Fold 2 IBS: 0.2024576728303072
Fold 3 IBS: 0.21983749285124332
Fold 4 IBS: 0.20870249760898452
Fold 5 IBS: 0.20455777633247008
[I 2024-04-15 17:33:32,393] Trial 30 finished with value: 0.21183452346400947 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.248038082278575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09616326651706666}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2377854341110714
Fold 2 IBS: 0.19139505894180328
Fold 3 IBS: 0.22494123884531728
Fold 4 IBS: 0.1801406586177039
Fold 5 IBS: 0.19851927887057197
[I 2024-04-15 17:33:35,729] Trial 31 finished with value: 0.20655633387729355 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.7009946946472989, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05091959330034321}. Best is trial 28 with value: 0.2039609151270521.

Fold 1 IBS: 0.24607569530270887
Fold 2 IBS: 0.2322534676033703
Fold 3 IBS: 0.23000152640707228
Fold 4 IBS: 0.24129488323806544
Fold 5 IBS: 0.23027107814262227
[I 2024-04-15 17:33:39,022] Trial 32 finished with value: 0.23597933013876782 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.2693933566356703, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16572038773562736}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.25666234269640353
Fold 2 IBS: 0.1921775892275604
Fold 3 IBS: 0.24131762851690544
Fold 4 IBS: 0.20035119005884414
Fold 5 IBS: 0.20538433727508362
[I 2024-04-15 17:33:43,097] Trial 33 finished with value: 0.21917861755495943 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.7422917748630138, 'max_features': None, 'min_weight_fraction_leaf': 0.12032836631045307}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.21587383197265342
Fold 2 IBS: 0.19458032881853532
Fold 3 IBS: 0.22264232879107862
Fold 4 IBS: 0.20166762262483962
Fold 5 IBS: 0.20856789378752014
[I 2024-04-15 17:33:46,220] Trial 34 finished with value: 0.20866640119892543 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.4728660265427002, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1526443633893062}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.23541831869582394
Fold 2 IBS: 0.1900896805610531
Fold 3 IBS: 0.22243765397288626
Fold 4 IBS: 0.1782388325648827
Fold 5 IBS: 0.19827195028002378
[I 2024-04-15 17:33:52,180] Trial 35 finished with value: 0.20489128721493394 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.6958024881475661, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09838182504220966}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2398647194781202
Fold 2 IBS: 0.1922693961324222
Fold 3 IBS: 0.22535256204023918
Fold 4 IBS: 0.17859178207894352
Fold 5 IBS: 0.20094489142711772
[I 2024-04-15 17:33:57,586] Trial 36 finished with value: 0.20740467023136855 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8663215323127738, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0971643808856393}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.23786277014702817
Fold 2 IBS: 0.19087420176111955
Fold 3 IBS: 0.2223279772263498
Fold 4 IBS: 0.17957604214493378
Fold 5 IBS: 0.19838070049749867
[I 2024-04-15 17:34:03,800] Trial 37 finished with value: 0.20580433835538597 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.6865635455562653, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06969432056719083}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2647567030826211
Fold 2 IBS: 0.19503826791721382
Fold 3 IBS: 0.2333476129869416
Fold 4 IBS: 0.1983253431680655
Fold 5 IBS: 0.19907177720315974
[I 2024-04-15 17:34:06,973] Trial 38 finished with value: 0.21810794087160038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.7866444459952668, 'max_features': None, 'min_weight_fraction_leaf': 0.04112547832939156}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2243972225585172
Fold 2 IBS: 0.1858262523619156
Fold 3 IBS: 0.2203306220645826
Fold 4 IBS: 0.188333461121934
Fold 5 IBS: 0.20135264901975777
[I 2024-04-15 17:34:10,571] Trial 39 finished with value: 0.20404804142534144 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 292, 'oob_score': True, 'max_samples': 0.5380737415869913, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10389391366777193}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.23586576005353135
Fold 2 IBS: 0.19195265742531933
Fold 3 IBS: 0.22072456914474772
Fold 4 IBS: 0.1823930886381884
Fold 5 IBS: 0.19910158028935473
[I 2024-04-15 17:34:14,138] Trial 40 finished with value: 0.2060075311102283 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.5063046032569182, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023839316359410723}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.21971954925613413
Fold 2 IBS: 0.19292602489827573
Fold 3 IBS: 0.21968569918274722
Fold 4 IBS: 0.19463249776988528
Fold 5 IBS: 0.20326053449865558
[I 2024-04-15 17:34:17,206] Trial 41 finished with value: 0.20604486112113957 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.3678479930846238, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10094088254123768}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2215619021253483
Fold 2 IBS: 0.20344954066501142
Fold 3 IBS: 0.21532110544708002
Fold 4 IBS: 0.20686001457871472
Fold 5 IBS: 0.20449473550739103
[I 2024-04-15 17:34:19,464] Trial 42 finished with value: 0.2103374596647091 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.20847983713127596, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06615629742136314}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2464208649312086
Fold 2 IBS: 0.23221147056181904
Fold 3 IBS: 0.22953511643765565
Fold 4 IBS: 0.24146068364317153
Fold 5 IBS: 0.23021164432420735
[I 2024-04-15 17:34:23,534] Trial 43 finished with value: 0.23596795597961245 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.5685253031793158, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.23261823147117625
Fold 2 IBS: 0.18874016793577425
Fold 3 IBS: 0.21840187359712543
Fold 4 IBS: 0.18501889974693178
Fold 5 IBS: 0.19987538393263812
[I 2024-04-15 17:34:26,783] Trial 44 finished with value: 0.20493091133672917 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.8393666794966143, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13222561468915417}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.2704140583508629
Fold 2 IBS: 0.19558128111333037
Fold 3 IBS: 0.24155882807218174
Fold 4 IBS: 0.19406818622893615
Fold 5 IBS: 0.1995293029043793
[I 2024-04-15 17:34:31,130] Trial 45 finished with value: 0.22023033133393807 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 334, 'oob_score': True, 'max_samples': 0.9094476331954031, 'max_features': None, 'min_weight_fraction_leaf': 0.13381736925839086}. Best is trial 28 with value: 0.2039609151270521.
Fold 1 IBS: 0.22123314001787947
Fold 2 IBS: 0.18988136892920218
Fold 3 IBS: 0.2128346668445425
Fold 4 IBS: 0.19576203373385317
Fold 5 IBS: 0.19881761969604983
[I 2024-04-15 17:34:33,996] Trial 46 finished with value: 0.20370576584430547 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.3274139443887121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07958240492879463}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2216187853703478
Fold 2 IBS: 0.18910187074629262
Fold 3 IBS: 0.2143066714287192
Fold 4 IBS: 0.19459505611593667
Fold 5 IBS: 0.20059814408523557
[I 2024-04-15 17:34:37,194] Trial 47 finished with value: 0.20404410554930638 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.32361788855909257, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07563119634026265}. Best is trial 46 with value: 0.20370576584430547.

Fold 1 IBS: 0.2469763086874542
Fold 2 IBS: 0.23230185713276866
Fold 3 IBS: 0.22972040438907473
Fold 4 IBS: 0.2411735138843142
Fold 5 IBS: 0.23026842457986174
[I 2024-04-15 17:34:40,955] Trial 48 finished with value: 0.2360881017346947 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.33846670341980367, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.39308816597832114}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2259877395146257
Fold 2 IBS: 0.19108809720640413
Fold 3 IBS: 0.20774889959066922
Fold 4 IBS: 0.2003727390941353
Fold 5 IBS: 0.20342585963506513
[I 2024-04-15 17:34:43,742] Trial 49 finished with value: 0.2057246670081799 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.2725130585270163, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006514903508432604}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22503938625580064
Fold 2 IBS: 0.19838736858194297
Fold 3 IBS: 0.2175003704983331
Fold 4 IBS: 0.20566442195422197
Fold 5 IBS: 0.20497097840561787
[I 2024-04-15 17:34:46,624] Trial 50 finished with value: 0.2103125051391833 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.1909411851756303, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06226194205781568}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2223725935311747
Fold 2 IBS: 0.19104086237590884
Fold 3 IBS: 0.21296095076225505
Fold 4 IBS: 0.19472101860876292
Fold 5 IBS: 0.1999171874719562
[I 2024-04-15 17:34:50,152] Trial 51 finished with value: 0.20420252255001153 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.31779404896040087, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07669022174929015}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22252539682634787
Fold 2 IBS: 0.19068891589982678
Fold 3 IBS: 0.2134847353815808
Fold 4 IBS: 0.19481766552112662
Fold 5 IBS: 0.19992101190522124
[I 2024-04-15 17:34:53,517] Trial 52 finished with value: 0.20428754510682068 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 275, 'oob_score': True, 'max_samples': 0.3171498594984932, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07952010188076152}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2319100755532219
Fold 2 IBS: 0.18649123227261108
Fold 3 IBS: 0.21812324230422053
Fold 4 IBS: 0.18902525488802424
Fold 5 IBS: 0.2034856785390441
[I 2024-04-15 17:34:56,604] Trial 53 finished with value: 0.20580709671142436 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 255, 'oob_score': True, 'max_samples': 0.41199474465646296, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022409056453020437}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.21949216913643393
Fold 2 IBS: 0.197668613576542
Fold 3 IBS: 0.220115143069781
Fold 4 IBS: 0.199236133397287
Fold 5 IBS: 0.20441426357710388
[I 2024-04-15 17:35:00,751] Trial 54 finished with value: 0.20818526455142955 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.36280848993599263, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10969474365856834}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22298789483842643
Fold 2 IBS: 0.19270449444981455
Fold 3 IBS: 0.21921651044078314
Fold 4 IBS: 0.19883579159828227
Fold 5 IBS: 0.20221795267651732
[I 2024-04-15 17:35:04,165] Trial 55 finished with value: 0.20719252880076472 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.2913967710455128, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07905201308546356}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22551282665199346
Fold 2 IBS: 0.20601405116755728
Fold 3 IBS: 0.21693620828064825
Fold 4 IBS: 0.20915128751249487
Fold 5 IBS: 0.20421212513874992
[I 2024-04-15 17:35:07,250] Trial 56 finished with value: 0.21236529975028878 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.21127771299865206, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06316640677447392}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.24654788530820357
Fold 2 IBS: 0.23230668370818272
Fold 3 IBS: 0.22950577224379984
Fold 4 IBS: 0.2415181421918243
Fold 5 IBS: 0.23042665791234268
[I 2024-04-15 17:35:10,140] Trial 57 finished with value: 0.23606102827287062 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.4498320727301371, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4483396318142452}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.23235414413178274
Fold 2 IBS: 0.18561114522199226
Fold 3 IBS: 0.2157299983183201
Fold 4 IBS: 0.18396001005006046
Fold 5 IBS: 0.2015210994956195
[I 2024-04-15 17:35:13,678] Trial 58 finished with value: 0.203835279443555 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.3744323905004405, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04882070954997948}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.24386713177755898
Fold 2 IBS: 0.19567653598498064
Fold 3 IBS: 0.21611532402040362
Fold 4 IBS: 0.18422637103912168
Fold 5 IBS: 0.1939421572303147
[I 2024-04-15 17:35:17,425] Trial 59 finished with value: 0.2067655040104759 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.518767543934845, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025731127316813193}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.25205308893526973
Fold 2 IBS: 0.19386802611434772
Fold 3 IBS: 0.23517737409870057
Fold 4 IBS: 0.1902002631630101
Fold 5 IBS: 0.20504398672028007
[I 2024-04-15 17:35:21,496] Trial 60 finished with value: 0.21526854780632165 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 347, 'oob_score': True, 'max_samples': 0.38164756875660333, 'max_features': None, 'min_weight_fraction_leaf': 0.05403520392091444}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2209107260938599
Fold 2 IBS: 0.19278777254085
Fold 3 IBS: 0.21802578716908955
Fold 4 IBS: 0.1927348583837054
Fold 5 IBS: 0.20172621900566143
[I 2024-04-15 17:35:24,564] Trial 61 finished with value: 0.20523707263863328 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.33609427490932514, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08368516988707789}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.23310063716340082
Fold 2 IBS: 0.18680674621710638
Fold 3 IBS: 0.21538193920290016
Fold 4 IBS: 0.1874096151564953
Fold 5 IBS: 0.19945833731781903
[I 2024-04-15 17:35:27,864] Trial 62 finished with value: 0.2044314550115443 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.31057904109142204, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.044977647035109765}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22671593624377293
Fold 2 IBS: 0.21337624091476354
Fold 3 IBS: 0.2235719861355586
Fold 4 IBS: 0.21946902889017525

Fold 5 IBS: 0.20917003156588318
[I 2024-04-15 17:35:30,402] Trial 63 finished with value: 0.2184606447500307 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.2325243517835534, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11132771366310104}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2308036001809005
Fold 2 IBS: 0.19285062563411273
Fold 3 IBS: 0.20338231310806063
Fold 4 IBS: 0.20244527646462443
Fold 5 IBS: 0.20372242165671908
[I 2024-04-15 17:35:33,187] Trial 64 finished with value: 0.2066408474088835 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.1715834543920205, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0022361848547431257}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.24611925529321832
Fold 2 IBS: 0.23212379718153284
Fold 3 IBS: 0.23013145470590418
Fold 4 IBS: 0.24119451715985793
Fold 5 IBS: 0.22989885886072642
[I 2024-04-15 17:35:36,804] Trial 65 finished with value: 0.23589357664024796 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.14056733251300402, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.27164116177235653}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22596180453302692
Fold 2 IBS: 0.1848959804118253
Fold 3 IBS: 0.22017224999708376
Fold 4 IBS: 0.18914072315906108
Fold 5 IBS: 0.20305908154902222
[I 2024-04-15 17:35:38,945] Trial 66 finished with value: 0.20464596793000384 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.434159580816968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08605947205022761}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.246623992593082
Fold 2 IBS: 0.23240365497147739
Fold 3 IBS: 0.22976316732017435
Fold 4 IBS: 0.24133375041247668
Fold 5 IBS: 0.23027754942303355
[I 2024-04-15 17:35:42,611] Trial 67 finished with value: 0.2360804229440488 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.39843029149146686, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20757248173595344}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2467013909802893
Fold 2 IBS: 0.2322190701706874
Fold 3 IBS: 0.23005277141057162
Fold 4 IBS: 0.24120288397110126
Fold 5 IBS: 0.23034367453347637
[I 2024-04-15 17:35:44,742] Trial 68 finished with value: 0.23610395821322516 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 265, 'oob_score': False, 'max_samples': 0.26747283821099427, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03063678741531728}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2218723070697466
Fold 2 IBS: 0.20449777229539706
Fold 3 IBS: 0.22033515559214706
Fold 4 IBS: 0.2080291850006832
Fold 5 IBS: 0.207003434917355
[I 2024-04-15 17:35:48,831] Trial 69 finished with value: 0.2123475709750658 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.3560539957553884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1400846715003256}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.21776033475048706
Fold 2 IBS: 0.1952111072893217
Fold 3 IBS: 0.2201376076287725
Fold 4 IBS: 0.20186757286231405
Fold 5 IBS: 0.2066981779483998
[I 2024-04-15 17:35:51,325] Trial 70 finished with value: 0.208334960095859 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.4879619520247406, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15807578474935124}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22259736568187957
Fold 2 IBS: 0.1911372029289564
Fold 3 IBS: 0.21435803668140005
Fold 4 IBS: 0.19402423796354845
Fold 5 IBS: 0.20258162068608646
[I 2024-04-15 17:35:54,286] Trial 71 finished with value: 0.20493969278837415 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.3157247867745793, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07872731788571019}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2235374424999989
Fold 2 IBS: 0.19358789162655668
Fold 3 IBS: 0.21625670707853398
Fold 4 IBS: 0.19335836376772728
Fold 5 IBS: 0.20274938601122552
[I 2024-04-15 17:35:57,048] Trial 72 finished with value: 0.20589795819680848 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 279, 'oob_score': True, 'max_samples': 0.2411640531958078, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05443903678900466}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22264416096273743
Fold 2 IBS: 0.19344962946503333
Fold 3 IBS: 0.21951826691688278
Fold 4 IBS: 0.20030183192393788
Fold 5 IBS: 0.20311018023998026
[I 2024-04-15 17:36:00,284] Trial 73 finished with value: 0.20780481390171435 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.29187448039080444, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07327518445246396}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22172266328136056
Fold 2 IBS: 0.20291029667512392
Fold 3 IBS: 0.21906908186884577
Fold 4 IBS: 0.20813393749029505
Fold 5 IBS: 0.20700172055679908
[I 2024-04-15 17:36:03,296] Trial 74 finished with value: 0.2117675399744849 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.328805676289732, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11987513104878934}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22099932346957527
Fold 2 IBS: 0.19116499808785933
Fold 3 IBS: 0.21867554367644626
Fold 4 IBS: 0.19195769288497275
Fold 5 IBS: 0.20108726177284778
[I 2024-04-15 17:36:06,125] Trial 75 finished with value: 0.20477696397834028 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.394472099449373, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0915313544590033}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.24688241980968478
Fold 2 IBS: 0.23226499390469085
Fold 3 IBS: 0.22983418669356528
Fold 4 IBS: 0.24116929339883575
Fold 5 IBS: 0.23036479110022526
[I 2024-04-15 17:36:07,946] Trial 76 finished with value: 0.2361031369814004 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.29514581851914834, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.32041444551979115}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22784527364297308
Fold 2 IBS: 0.18546208306539955
Fold 3 IBS: 0.2229276398727979
Fold 4 IBS: 0.18828218260506768
Fold 5 IBS: 0.2020401965251059
[I 2024-04-15 17:36:10,931] Trial 77 finished with value: 0.2053114751422688 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.5629198845457468, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10608065268584921}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.2500095610244279
Fold 2 IBS: 0.19163219356552968
Fold 3 IBS: 0.21375066305378862
Fold 4 IBS: 0.21143782414353976
Fold 5 IBS: 0.20900686638017946
[I 2024-04-15 17:36:12,680] Trial 78 finished with value: 0.21516742163349306 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.3536872023497069, 'max_features': None, 'min_weight_fraction_leaf': 0.017248960979189897}. Best is trial 46 with value: 0.20370576584430547.
Fold 1 IBS: 0.22175818775505846

Fold 2 IBS: 0.181186571358148
Fold 3 IBS: 0.21658784650405408
Fold 4 IBS: 0.19184268124137188
Fold 5 IBS: 0.1925984231888799
[I 2024-04-15 17:36:13,106] Trial 79 finished with value: 0.20079474200950248 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.658103911048427, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1264213492372395}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.14621065223036303
Fold 2 IBS: 0.21835543795889995
Fold 3 IBS: 0.2614037742945736
Fold 4 IBS: 0.22042199270046206
Fold 5 IBS: 0.2424449916206397
[I 2024-04-15 17:36:13,313] Trial 80 finished with value: 0.2177673697609877 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 2, 'oob_score': True, 'max_samples': 0.6070678390359827, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13087324504203068}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22229439529248238
Fold 2 IBS: 0.19390149624984573
Fold 3 IBS: 0.21892887578723189
Fold 4 IBS: 0.186624265489618
Fold 5 IBS: 0.19876160721940636
[I 2024-04-15 17:36:14,453] Trial 81 finished with value: 0.20410212800771688 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 100, 'oob_score': True, 'max_samples': 0.6673331442182682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03875722179494085}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22669318038792
Fold 2 IBS: 0.19113938620381113
Fold 3 IBS: 0.21861297361237036
Fold 4 IBS: 0.1809662878368811
Fold 5 IBS: 0.19820402326918762
[I 2024-04-15 17:36:15,391] Trial 82 finished with value: 0.20312317026203405 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.660020317193595, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0375053418394423}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22905571019935947
Fold 2 IBS: 0.20895892502690008
Fold 3 IBS: 0.2277966126284892
Fold 4 IBS: 0.19060133775513555
Fold 5 IBS: 0.19898003914168433
[I 2024-04-15 17:36:15,773] Trial 83 finished with value: 0.2110785249503137 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 22, 'oob_score': True, 'max_samples': 0.681519994785607, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.041587155396297544}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22743750471141788
Fold 2 IBS: 0.19117347832883866
Fold 3 IBS: 0.21840146372763788
Fold 4 IBS: 0.18549897752367067
Fold 5 IBS: 0.20456622275264433
[I 2024-04-15 17:36:16,980] Trial 84 finished with value: 0.20541552940884192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.656210021309656, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.034590342577110036}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22993650724011108
Fold 2 IBS: 0.18859629692778362
Fold 3 IBS: 0.23269294209836752
Fold 4 IBS: 0.18309339506201788
Fold 5 IBS: 0.20281553187967694
[I 2024-04-15 17:36:17,823] Trial 85 finished with value: 0.20742693464159143 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.7191119469719931, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.055675399009790995}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.2218470455419141
Fold 2 IBS: 0.2163239812010234
Fold 3 IBS: 0.21584741068005145
Fold 4 IBS: 0.18577532242520042
Fold 5 IBS: 0.1933925444147065
[I 2024-04-15 17:36:18,313] Trial 86 finished with value: 0.2066372608525792 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.7751390440375987, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013391629553714958}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22591965301490835
Fold 2 IBS: 0.20101903728370502
Fold 3 IBS: 0.2215112658383989
Fold 4 IBS: 0.20988128868433
Fold 5 IBS: 0.21036622050840323
[I 2024-04-15 17:36:19,307] Trial 87 finished with value: 0.21373949306594908 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.6450242360915458, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23270154165056978}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.21932028100626555
Fold 2 IBS: 0.18999555069979543
Fold 3 IBS: 0.22122291660357044
Fold 4 IBS: 0.1979665579053727
Fold 5 IBS: 0.20450528789404995
[I 2024-04-15 17:36:20,237] Trial 88 finished with value: 0.2066021188218108 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.5914281019902156, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16845366648326512}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.23147494924412607
Fold 2 IBS: 0.19081626511364277
Fold 3 IBS: 0.22187169444527557
Fold 4 IBS: 0.18847851851312933
Fold 5 IBS: 0.198114867126135
[I 2024-04-15 17:36:21,625] Trial 89 finished with value: 0.20615125888846175 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.7285757689976209, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05830969934274739}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.23863295943025659
Fold 2 IBS: 0.20723873854920485
Fold 3 IBS: 0.23516471986310156
Fold 4 IBS: 0.18717812336287898
Fold 5 IBS: 0.19172935508944805
[I 2024-04-15 17:36:22,047] Trial 90 finished with value: 0.211988779258978 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 19, 'oob_score': True, 'max_samples': 0.7694108202899131, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09264196905485238}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.2218608276701066
Fold 2 IBS: 0.18125721013058405
Fold 3 IBS: 0.23852843300122328
Fold 4 IBS: 0.19012292728963665
Fold 5 IBS: 0.21050548253187193
[I 2024-04-15 17:36:22,869] Trial 91 finished with value: 0.2084549761246845 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 60, 'oob_score': True, 'max_samples': 0.6671722299657248, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0697382129062882}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.2329191394205307
Fold 2 IBS: 0.19616506354906146
Fold 3 IBS: 0.21791851987394553
Fold 4 IBS: 0.18871351815359
Fold 5 IBS: 0.20042845263926776
[I 2024-04-15 17:36:25,582] Trial 92 finished with value: 0.20722893872727907 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 252, 'oob_score': True, 'max_samples': 0.5396609869212142, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04411492969263121}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.23210686268446468
Fold 2 IBS: 0.18940741335957448
Fold 3 IBS: 0.22287725920541235
Fold 4 IBS: 0.18577994009263485
Fold 5 IBS: 0.20267254583110256
[I 2024-04-15 17:36:26,052] Trial 93 finished with value: 0.20656880423463778 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 30, 'oob_score': True, 'max_samples': 0.759019695209399, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10264459646198915}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.23701312315264092
Fold 2 IBS: 0.19604897062283916
Fold 3 IBS: 0.2222027771286405
Fold 4 IBS: 0.1837912162722193
Fold 5 IBS: 0.19907431113664567
[I 2024-04-15 17:36:26,684] Trial 94 finished with value: 0.20762607966259713 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.7032284085491868, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0329960733959276}. Best is trial 79 with value: 0.20079474200950248.

Fold 1 IBS: 0.23035635370923183
Fold 2 IBS: 0.19074321594876992
Fold 3 IBS: 0.2194527294610163
Fold 4 IBS: 0.18915063569781565
Fold 5 IBS: 0.19826232609117034
[I 2024-04-15 17:36:28,186] Trial 95 finished with value: 0.20559305218160082 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.8075223534134511, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12608769469565542}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.23556491153783007
Fold 2 IBS: 0.19006041623205322
Fold 3 IBS: 0.2223584908159212
Fold 4 IBS: 0.1864963500371157
Fold 5 IBS: 0.197686962784186
[I 2024-04-15 17:36:30,070] Trial 96 finished with value: 0.20643342628142122 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 182, 'oob_score': True, 'max_samples': 0.5972550179693354, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06549336427379024}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22443089429351343
Fold 2 IBS: 0.20162994377277607
Fold 3 IBS: 0.21955687792596162
Fold 4 IBS: 0.2043529954985394
Fold 5 IBS: 0.20878881908589259
[I 2024-04-15 17:36:31,214] Trial 97 finished with value: 0.21175190611533665 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 110, 'oob_score': True, 'max_samples': 0.434945304320631, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14457922132332046}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.2106666761851736
Fold 2 IBS: 0.18275076354211098
Fold 3 IBS: 0.24045452990539332
Fold 4 IBS: 0.20505713662151454
Fold 5 IBS: 0.2169566793484335
[I 2024-04-15 17:36:34,800] Trial 98 finished with value: 0.21117715712052515 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.6207965155808232, 'max_features': None, 'min_weight_fraction_leaf': 0.18942704575079522}. Best is trial 79 with value: 0.20079474200950248.
Fold 1 IBS: 0.22415963127469155
Fold 2 IBS: 0.20252535404207592
Fold 3 IBS: 0.21736435933714773
Fold 4 IBS: 0.20536346337282366
Fold 5 IBS: 0.20472207371283777
[I 2024-04-15 17:36:35,821] Trial 99 finished with value: 0.2108269763479153 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.2568890290232936, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08596002652152478}. Best is trial 79 with value: 0.20079474200950248.


* Best trial for IBS:
 FrozenTrial(number=79, state=TrialState.COMPLETE, values=[0.20079474200950248], datetime_start=datetime.datetime(2024, 4, 15, 17, 36, 12, 704752), datetime_complete=datetime.datetime(2024, 4, 15, 17, 36, 13, 105631), params={'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.658103911048427, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1264213492372395}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=79, value=None)


* Best Score for IBS:
 0.20079474200950248

In [136]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [137]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.782
train_ibs:  0.201

#### Test

In [138]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [139]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=11, max_features='log2', max_leaf_nodes=14,
                     max_samples=0.9805420780206322, min_samples_leaf=16,
                     min_samples_split=11,
                     min_weight_fraction_leaf=0.2725745032335037,
                     n_estimators=349, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.512

RandomSurvivalForest(max_depth=14, max_features='auto', max_leaf_nodes=10,
                     max_samples=0.658103911048427, min_samples_leaf=2,
                     min_samples_split=17,
                     min_weight_fraction_leaf=0.1264213492372395,
                     n_estimators=25, oob_score=True, random_state=123)

test_ibs:  0.256

In [140]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [141]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [142]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:36:36,843] A new study created in memory with name: no-name-a568dac9-a2f7-4405-bdbd-8851879ad937

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7854077253218884
[I 2024-04-15 17:36:37,581] Trial 0 finished with value: 0.7560648740319208 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:36:39,577] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.759656652360515
[I 2024-04-15 17:36:43,283] Trial 2 finished with value: 0.7168587698439415 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7553648068669528
[I 2024-04-15 17:36:43,622] Trial 3 finished with value: 0.7292311904392678 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:36:45,203] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:36:46,830] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:36:47,733] Trial 6 finished with value: 0.7531024998921156 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 17:36:49,706] Trial 7 finished with value: 0.6983332272931635 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 17:36:49,842] Trial 8 finished with value: 0.6922940536648037 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 17:36:53,749] Trial 9 finished with value: 0.6881371211223316 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:36:55,131] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:36:55,898] Trial 11 finished with value: 0.7515783638650573 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7560648740319208.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:36:56,922] Trial 12 finished with value: 0.7574661942157834 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 17:36:57,869] Trial 13 finished with value: 0.75094127426438 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 17:36:58,629] Trial 14 finished with value: 0.7484354524299325 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:36:59,157] Trial 15 finished with value: 0.7515281839499164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7574661942157834.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 17:37:00,122] Trial 16 finished with value: 0.7166118298571261 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 17:37:00,766] Trial 17 finished with value: 0.7513074288334827 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:37:01,854] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:02,614] Trial 19 finished with value: 0.7542663754844983 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.7131474103585658
Fold 2 C-index: 0.7306201550387597
Fold 3 C-index: 0.5468085106382978
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7103004291845494
[I 2024-04-15 17:37:02,734] Trial 20 finished with value: 0.6861829056067721 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:03,507] Trial 21 finished with value: 0.7534516681299506 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8822585639692264, 'min_weight_fraction_leaf': 0.11961357903200062}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:37:04,338] Trial 22 finished with value: 0.7503254226537519 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.891399217000056, 'min_weight_fraction_leaf': 0.15663178852989545}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 17:37:05,025] Trial 23 finished with value: 0.7483412639499951 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8095024948236286, 'min_weight_fraction_leaf': 0.028083898670301616}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 17:37:05,654] Trial 24 finished with value: 0.7435069176626288 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7425210261294792, 'min_weight_fraction_leaf': 0.08957779552546857}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:06,161] Trial 25 finished with value: 0.7327861643897762 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 215, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9128448809634693, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7553648068669528
[I 2024-04-15 17:37:10,559] Trial 26 finished with value: 0.7167215368484021 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6539680943502474, 'min_weight_fraction_leaf': 0.04317449484749}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:37:11,434] Trial 27 finished with value: 0.7483585471374842 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 371, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8435977690846584, 'min_weight_fraction_leaf': 0.14306800767196773}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:37:12,351] Trial 28 finished with value: 0.7569282125565228 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.94126425282106, 'min_weight_fraction_leaf': 0.20900889157295355}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 17:37:14,199] Trial 29 finished with value: 0.7486563245191729 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9429878658017256, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:37:14,988] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 415, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4637709746735863, 'min_weight_fraction_leaf': 0.2917886569515737}. Best is trial 12 with value: 0.7574661942157834.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 17:37:15,956] Trial 31 finished with value: 0.7511625701966765 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9462932212483206, 'min_weight_fraction_leaf': 0.2256775992503665}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:16,849] Trial 32 finished with value: 0.7522521303133161 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8366845330876531, 'min_weight_fraction_leaf': 0.16355247650398969}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:37:17,630] Trial 33 finished with value: 0.7445950186751016 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7636458768938535, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 12 with value: 0.7574661942157834.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:37:18,324] Trial 34 finished with value: 0.7579011440048482 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7154339819750474, 'min_weight_fraction_leaf': 0.07406182802753365}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 17:37:20,504] Trial 35 finished with value: 0.7088015502866888 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 294, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6031842176907916, 'min_weight_fraction_leaf': 0.06551177069857136}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:37:21,216] Trial 36 finished with value: 0.7561448922513254 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7300072049327524, 'min_weight_fraction_leaf': 0.031243121234821793}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:21,709] Trial 37 finished with value: 0.7553150070947747 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 221, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7121336251999504, 'min_weight_fraction_leaf': 0.030440421568832744}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:37:22,401] Trial 38 finished with value: 0.7442638758454118 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.0156219371253985}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 17:37:23,842] Trial 39 finished with value: 0.7035148398324138 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 149, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5219408153812318, 'min_weight_fraction_leaf': 0.05775443217052276}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:37:24,700] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6249972148105445, 'min_weight_fraction_leaf': 0.42733722871780283}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:37:25,403] Trial 41 finished with value: 0.7561577909826895 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 351, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.73059832058764, 'min_weight_fraction_leaf': 0.0011517308049273528}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 17:37:26,022] Trial 42 finished with value: 0.751363295058024 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7461151196577749, 'min_weight_fraction_leaf': 0.001641417311992733}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:26,912] Trial 43 finished with value: 0.7485639046181184 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8344443605748126, 'min_weight_fraction_leaf': 0.0970825890240695}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:27,626] Trial 44 finished with value: 0.7513663251520473 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5888308660191697, 'min_weight_fraction_leaf': 0.04186743348201184}. Best is trial 34 with value: 0.7579011440048482.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:37:28,419] Trial 45 finished with value: 0.7630327268580404 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6622547351739604, 'min_weight_fraction_leaf': 0.004167683530715366}. Best is trial 45 with value: 0.7630327268580404.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:37:29,302] Trial 46 finished with value: 0.7415635024947032 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 435, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5368271784486555, 'min_weight_fraction_leaf': 0.017191498668975277}. Best is trial 45 with value: 0.7630327268580404.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7424892703862661
[I 2024-04-15 17:37:32,008] Trial 47 finished with value: 0.7082799641784231 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 397, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.949096623171761, 'min_weight_fraction_leaf': 0.27317862948464683}. Best is trial 45 with value: 0.7630327268580404.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:37:33,841] Trial 48 finished with value: 0.76697199433059 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 472, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6516378673353315, 'min_weight_fraction_leaf': 0.002396401120071114}. Best is trial 48 with value: 0.76697199433059.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7811158798283262
[I 2024-04-15 17:37:35,703] Trial 49 finished with value: 0.7498748876538895 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 476, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.647895437588795, 'min_weight_fraction_leaf': 0.07421351537598227}. Best is trial 48 with value: 0.76697199433059.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:37:37,540] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 455, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.676989799366243, 'min_weight_fraction_leaf': 0.35014708507164105}. Best is trial 48 with value: 0.76697199433059.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:37:39,667] Trial 51 finished with value: 0.7685044873219458 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5022920655252021, 'min_weight_fraction_leaf': 0.0006361438556942846}. Best is trial 51 with value: 0.7685044873219458.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:37:41,777] Trial 52 finished with value: 0.7570390505611249 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 486, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.38920782663893977, 'min_weight_fraction_leaf': 0.050950490950656055}. Best is trial 51 with value: 0.7685044873219458.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:37:43,837] Trial 53 finished with value: 0.7593135379565485 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 486, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.41859456108995274, 'min_weight_fraction_leaf': 0.05432590607847455}. Best is trial 51 with value: 0.7685044873219458.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:37:45,649] Trial 54 finished with value: 0.762988921692779 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5099688882260554, 'min_weight_fraction_leaf': 0.022415816807863594}. Best is trial 51 with value: 0.7685044873219458.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:37:47,380] Trial 55 finished with value: 0.7612331102165739 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4972638169201667, 'min_weight_fraction_leaf': 0.08036231386140458}. Best is trial 51 with value: 0.7685044873219458.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7854077253218884
[I 2024-04-15 17:37:49,084] Trial 56 finished with value: 0.7594143110061339 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 430, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.50197811122431, 'min_weight_fraction_leaf': 0.05129486953077068}. Best is trial 51 with value: 0.7685044873219458.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:37:50,656] Trial 57 finished with value: 0.7735022411522677 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 391, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4994568373156456, 'min_weight_fraction_leaf': 0.02492463986357664}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:37:52,244] Trial 58 finished with value: 0.7686344814472317 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5733720763660073, 'min_weight_fraction_leaf': 0.020153848534975916}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-15 17:37:55,784] Trial 59 finished with value: 0.7115492188743535 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 399, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5649379733524792, 'min_weight_fraction_leaf': 0.02005389901726501}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:37:57,302] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 389, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.36027563269646956, 'min_weight_fraction_leaf': 0.489249749751184}. Best is trial 57 with value: 0.7735022411522677.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:37:58,907] Trial 61 finished with value: 0.7678309306934551 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 419, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4639523436567415, 'min_weight_fraction_leaf': 0.02202612424804292}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:00,673] Trial 62 finished with value: 0.7669904562002862 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 455, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4566239550777419, 'min_weight_fraction_leaf': 0.022406404671997896}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:38:02,407] Trial 63 finished with value: 0.7554779302065109 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4546195977333023, 'min_weight_fraction_leaf': 6.691098306529312e-05}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:38:03,808] Trial 64 finished with value: 0.7561195489557602 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 365, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.2874751071933402, 'min_weight_fraction_leaf': 0.039265837471405}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 17:38:05,378] Trial 65 finished with value: 0.7657517016837752 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 409, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5470110986042935, 'min_weight_fraction_leaf': 0.017791140033549372}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:38:07,131] Trial 66 finished with value: 0.7511222354027559 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 452, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.47952174060747327, 'min_weight_fraction_leaf': 0.10819861655062171}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:08,880] Trial 67 finished with value: 0.762825744607373 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4292070175325556, 'min_weight_fraction_leaf': 0.03329649918145562}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:10,159] Trial 68 finished with value: 0.7587764166018954 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 323, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5645084566860479, 'min_weight_fraction_leaf': 0.016087954355615504}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:38:11,946] Trial 69 finished with value: 0.7513312402059762 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5417732046940608, 'min_weight_fraction_leaf': 0.08270883875272832}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7854077253218884
[I 2024-04-15 17:38:13,430] Trial 70 finished with value: 0.7572451686914183 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 380, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.602646676554382, 'min_weight_fraction_leaf': 0.06165455703095525}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:14,999] Trial 71 finished with value: 0.7564765859109064 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6303628856636149, 'min_weight_fraction_leaf': 0.017428719599136284}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:16,684] Trial 72 finished with value: 0.7661610113210533 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 443, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.48142091922216923, 'min_weight_fraction_leaf': 0.035199654495496495}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:38:18,525] Trial 73 finished with value: 0.7686635326535461 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 483, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4476268389928765, 'min_weight_fraction_leaf': 0.03463234906521451}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:20,474] Trial 74 finished with value: 0.7587268645390702 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 481, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.3797499520654964, 'min_weight_fraction_leaf': 0.0457495274155265}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:22,432] Trial 75 finished with value: 0.7660308902089324 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 498, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.47263193634870243, 'min_weight_fraction_leaf': 0.03401419471408856}. Best is trial 57 with value: 0.7735022411522677.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7381974248927039
[I 2024-04-15 17:38:26,278] Trial 76 finished with value: 0.7169028125486111 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 442, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4344034613428522, 'min_weight_fraction_leaf': 0.06705368289482433}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 17:38:28,086] Trial 77 finished with value: 0.7525281882059052 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 467, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.34109483550047087, 'min_weight_fraction_leaf': 0.09636023158111073}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 17:38:29,789] Trial 78 finished with value: 0.7405390632174247 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4849618139869374, 'min_weight_fraction_leaf': 0.031286793893637616}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:31,571] Trial 79 finished with value: 0.7644341076300664 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 458, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4489836079662487, 'min_weight_fraction_leaf': 0.04309311120477498}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7896995708154506
[I 2024-04-15 17:38:34,082] Trial 80 finished with value: 0.740771492234372 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 417, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.2869597372530869, 'min_weight_fraction_leaf': 0.12685528642168645}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:38:39,579] Trial 81 finished with value: 0.7628837200331671 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 498, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.46068382345987235, 'min_weight_fraction_leaf': 0.029818448829053927}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:38:42,752] Trial 82 finished with value: 0.7695297578510749 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 486, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5257053451735714, 'min_weight_fraction_leaf': 0.009712033142402562}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:38:45,230] Trial 83 finished with value: 0.7622901651898196 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 480, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5256383112084416, 'min_weight_fraction_leaf': 0.011279711028931083}. Best is trial 57 with value: 0.7735022411522677.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 17:38:47,660] Trial 84 finished with value: 0.7774065835341042 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5794933849835422, 'min_weight_fraction_leaf': 0.00022047637333624456}. Best is trial 84 with value: 0.7774065835341042.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 17:38:50,534] Trial 85 finished with value: 0.7782576473638915 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 467, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5751644785662164, 'min_weight_fraction_leaf': 0.004576574165007147}. Best is trial 85 with value: 0.7782576473638915.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:38:55,133] Trial 86 finished with value: 0.7677407469804882 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5742552285325079, 'min_weight_fraction_leaf': 0.011664040215327387}. Best is trial 85 with value: 0.7782576473638915.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7854077253218884
[I 2024-04-15 17:38:57,689] Trial 87 finished with value: 0.753916783403607 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 488, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5941452037053011, 'min_weight_fraction_leaf': 0.0593067135233609}. Best is trial 85 with value: 0.7782576473638915.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7510729613733905
[I 2024-04-15 17:39:03,447] Trial 88 finished with value: 0.7184085031402349 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 470, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.573111072011879, 'min_weight_fraction_leaf': 0.006724980474834726}. Best is trial 85 with value: 0.7782576473638915.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:39:06,296] Trial 89 finished with value: 0.7486841306446086 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 433, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5317643909605851, 'min_weight_fraction_leaf': 0.049620934383406354}. Best is trial 85 with value: 0.7782576473638915.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 17:39:07,022] Trial 90 finished with value: 0.7827852571778544 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6304917869687612, 'min_weight_fraction_leaf': 0.013077698163416425}. Best is trial 90 with value: 0.7827852571778544.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 17:39:07,567] Trial 91 finished with value: 0.7862831501470496 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 65, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6185952507107914, 'min_weight_fraction_leaf': 0.01600512355214787}. Best is trial 91 with value: 0.7862831501470496.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7553648068669528
[I 2024-04-15 17:39:08,005] Trial 92 finished with value: 0.7640754694210072 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 51, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6058404453816314, 'min_weight_fraction_leaf': 0.024729669722693227}. Best is trial 91 with value: 0.7862831501470496.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8111587982832618
[I 2024-04-15 17:39:08,661] Trial 93 finished with value: 0.7902855323406692 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.619821757838549, 'min_weight_fraction_leaf': 0.013053701374631141}. Best is trial 93 with value: 0.7902855323406692.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 17:39:09,277] Trial 94 finished with value: 0.7910028777001596 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 101, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6321905190335297, 'min_weight_fraction_leaf': 0.009478700458801217}. Best is trial 94 with value: 0.7910028777001596.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 17:39:10,322] Trial 95 finished with value: 0.7531384931124625 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 101, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6334265797699447, 'min_weight_fraction_leaf': 0.0687787405991436}. Best is trial 94 with value: 0.7910028777001596.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:39:10,966] Trial 96 finished with value: 0.7711341602606994 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 98, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6844762029674046, 'min_weight_fraction_leaf': 0.041874737899679465}. Best is trial 94 with value: 0.7910028777001596.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:39:11,627] Trial 97 finished with value: 0.7758564940647765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 99, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6847303965128372, 'min_weight_fraction_leaf': 0.042524173168855824}. Best is trial 94 with value: 0.7910028777001596.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.776824034334764
[I 2024-04-15 17:39:12,304] Trial 98 finished with value: 0.7636005751509296 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 103, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.699448106588176, 'min_weight_fraction_leaf': 0.0454282906956431}. Best is trial 94 with value: 0.7910028777001596.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7319148936170212

[I 2024-04-15 17:39:12,947] A new study created in memory with name: no-name-e470f7dc-4c1c-4c47-abb2-da101952615c

Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.759656652360515
[I 2024-04-15 17:39:12,921] Trial 99 finished with value: 0.7482250326764471 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 87, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6736186482098723, 'min_weight_fraction_leaf': 0.08470227625879802}. Best is trial 94 with value: 0.7910028777001596.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.7910028777001596], datetime_start=datetime.datetime(2024, 4, 15, 17, 39, 8, 677794), datetime_complete=datetime.datetime(2024, 4, 15, 17, 39, 9, 276957), params={'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 101, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6321905190335297, 'min_weight_fraction_leaf': 0.009478700458801217}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.7910028777001596

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23262063372538005
Fold 2 IBS: 0.21449790825275872
Fold 3 IBS: 0.2194925175874855
Fold 4 IBS: 0.21452942759848914
Fold 5 IBS: 0.2073632682376272
[I 2024-04-15 17:39:16,115] Trial 0 finished with value: 0.21770075108034814 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-15 17:39:20,532] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.23919752154458432
Fold 2 IBS: 0.22295830407263553
Fold 3 IBS: 0.22456981771696907
Fold 4 IBS: 0.23014004656492892
Fold 5 IBS: 0.21975413324708154
[I 2024-04-15 17:39:23,967] Trial 2 finished with value: 0.2273239646292399 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.239176708282145
Fold 2 IBS: 0.22098384182944475
Fold 3 IBS: 0.2242789940058911
Fold 4 IBS: 0.22907420961649527
Fold 5 IBS: 0.22050094096701978
[I 2024-04-15 17:39:25,123] Trial 3 finished with value: 0.22680293894019918 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-15 17:39:28,168] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-15 17:39:29,749] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.23397457751286213
Fold 2 IBS: 0.21434477355494305
Fold 3 IBS: 0.21997728166923142
Fold 4 IBS: 0.2142331011898318
Fold 5 IBS: 0.20795216560877666
[I 2024-04-15 17:39:32,874] Trial 6 finished with value: 0.218096379907129 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.23478242241161393
Fold 2 IBS: 0.2172834527536503
Fold 3 IBS: 0.22194904003758842
Fold 4 IBS: 0.22136021656576274
Fold 5 IBS: 0.21542376913303213
[I 2024-04-15 17:39:34,801] Trial 7 finished with value: 0.2221597801803295 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.24307916748921965
Fold 2 IBS: 0.22258815303123397
Fold 3 IBS: 0.22568603941681162
Fold 4 IBS: 0.23412727720806475
Fold 5 IBS: 0.22302861930063894
[I 2024-04-15 17:39:35,226] Trial 8 finished with value: 0.2297018512891938 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.24358484884641388
Fold 2 IBS: 0.22903066546532033
Fold 3 IBS: 0.22858892778105022
Fold 4 IBS: 0.23906467487608862
Fold 5 IBS: 0.22742244188851435
[I 2024-04-15 17:39:39,631] Trial 9 finished with value: 0.2335383117714775 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-15 17:39:44,082] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.23727046989261671
Fold 2 IBS: 0.2211680545570006
Fold 3 IBS: 0.22490825306054432
Fold 4 IBS: 0.22623668078223655
Fold 5 IBS: 0.2182493496837769
[I 2024-04-15 17:39:47,339] Trial 11 finished with value: 0.225566561595235 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21770075108034814.
Fold 1 IBS: 0.23144825013295048
Fold 2 IBS: 0.20694256233624791
Fold 3 IBS: 0.21397510057936817
Fold 4 IBS: 0.21063834650261326
Fold 5 IBS: 0.20325794201383188
[I 2024-04-15 17:39:52,390] Trial 12 finished with value: 0.21325244031300236 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.23531659331214314
Fold 2 IBS: 0.21805127466159296
Fold 3 IBS: 0.22285393131993408
Fold 4 IBS: 0.22502949744898376
Fold 5 IBS: 0.21408710363776215
[I 2024-04-15 17:39:57,199] Trial 13 finished with value: 0.22306768007608319 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.2354669531135936
Fold 2 IBS: 0.22078153412539875
Fold 3 IBS: 0.2228665000713134
Fold 4 IBS: 0.22581615086031648
Fold 5 IBS: 0.21652905440115908
[I 2024-04-15 17:40:00,406] Trial 14 finished with value: 0.22429203851435625 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.21325244031300236.

Fold 1 IBS: 0.23678761998403722
Fold 2 IBS: 0.22008128902997878
Fold 3 IBS: 0.2238795200441661
Fold 4 IBS: 0.22566185407498282
Fold 5 IBS: 0.21550823307152653
[I 2024-04-15 17:40:02,687] Trial 15 finished with value: 0.2243837032409383 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.24551858038977462
Fold 2 IBS: 0.2314905837252376
Fold 3 IBS: 0.22935852605054602
Fold 4 IBS: 0.2407088291929315
Fold 5 IBS: 0.22937213024648323
[I 2024-04-15 17:40:10,491] Trial 16 finished with value: 0.23528972992099456 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.22657659427268886
Fold 2 IBS: 0.21150301570118363
Fold 3 IBS: 0.21970522902643283
Fold 4 IBS: 0.2164785356799947
Fold 5 IBS: 0.21021726479090136
[I 2024-04-15 17:40:14,175] Trial 17 finished with value: 0.2168961278942403 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-15 17:40:16,270] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.3502979118045926}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.23163251242671562
Fold 2 IBS: 0.21865011524169967
Fold 3 IBS: 0.22324658673772318
Fold 4 IBS: 0.22639390974444276
Fold 5 IBS: 0.21496539726272915
[I 2024-04-15 17:40:19,572] Trial 19 finished with value: 0.2229777042826621 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.65748867033357, 'min_weight_fraction_leaf': 0.22705178291101535}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.2233602885865423
Fold 2 IBS: 0.22015326968301757
Fold 3 IBS: 0.23916695052531736
Fold 4 IBS: 0.2326974151294969
Fold 5 IBS: 0.20868525216346176
[I 2024-04-15 17:40:19,772] Trial 20 finished with value: 0.22481263521756717 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.888442198150298, 'min_weight_fraction_leaf': 0.16209852212373996}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.23248145680690227
Fold 2 IBS: 0.21238316252924436
Fold 3 IBS: 0.21779696024904355
Fold 4 IBS: 0.21355935619519087
Fold 5 IBS: 0.2074433921867989
[I 2024-04-15 17:40:24,836] Trial 21 finished with value: 0.21673286559343602 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7602097210753835, 'min_weight_fraction_leaf': 0.08966234512149224}. Best is trial 12 with value: 0.21325244031300236.
Fold 1 IBS: 0.23021616241757473
Fold 2 IBS: 0.20643022142708073
Fold 3 IBS: 0.21197177958431054
Fold 4 IBS: 0.20577949295373
Fold 5 IBS: 0.19996305842798048
[I 2024-04-15 17:40:29,245] Trial 22 finished with value: 0.21087214296213533 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.036794155679279135}. Best is trial 22 with value: 0.21087214296213533.
Fold 1 IBS: 0.23067598774281833
Fold 2 IBS: 0.20375926020301174
Fold 3 IBS: 0.21292302078763622
Fold 4 IBS: 0.2055435233812828
Fold 5 IBS: 0.20003523800160156
[I 2024-04-15 17:40:33,482] Trial 23 finished with value: 0.21058740602327014 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 413, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8682085636310637, 'min_weight_fraction_leaf': 0.0410105687080863}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23179168732917052
Fold 2 IBS: 0.20610617429571423
Fold 3 IBS: 0.2130902295497064
Fold 4 IBS: 0.20861293276043735
Fold 5 IBS: 0.2051175440497943
[I 2024-04-15 17:40:36,983] Trial 24 finished with value: 0.21294371359696457 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9202078722466613, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23272461405208733
Fold 2 IBS: 0.20707027422762675
Fold 3 IBS: 0.21498200039070717
Fold 4 IBS: 0.21060260903435474
Fold 5 IBS: 0.2041977456962019
[I 2024-04-15 17:40:40,731] Trial 25 finished with value: 0.21391544868019557 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8669369020505482, 'min_weight_fraction_leaf': 0.051754463568227216}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23413967591858406
Fold 2 IBS: 0.2152545460675856
Fold 3 IBS: 0.22112806228329734
Fold 4 IBS: 0.21936760222225493
Fold 5 IBS: 0.2122813155416666
[I 2024-04-15 17:40:45,043] Trial 26 finished with value: 0.2204342404066777 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9185812533915134, 'min_weight_fraction_leaf': 0.1323161771587018}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23143184173981493
Fold 2 IBS: 0.2031746432267918
Fold 3 IBS: 0.2130229497682585
Fold 4 IBS: 0.20764759655778703
Fold 5 IBS: 0.2022255496670944
[I 2024-04-15 17:40:49,753] Trial 27 finished with value: 0.21150051619194934 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.03529681125944531}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23556451571226233
Fold 2 IBS: 0.21910757849741566
Fold 3 IBS: 0.22270170153404856
Fold 4 IBS: 0.2218449687464398
Fold 5 IBS: 0.21642879953999616
[I 2024-04-15 17:40:51,529] Trial 28 finished with value: 0.22312951280603252 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8133066651810554, 'min_weight_fraction_leaf': 0.037545173529623}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23373550747666455
Fold 2 IBS: 0.21325168235477907
Fold 3 IBS: 0.21876921962430826
Fold 4 IBS: 0.21304676768515685
Fold 5 IBS: 0.2064226938575001
[I 2024-04-15 17:40:54,298] Trial 29 finished with value: 0.21704517419968178 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7347942097316961, 'min_weight_fraction_leaf': 0.08818032836216137}. Best is trial 23 with value: 0.21058740602327014.

Fold 1 IBS: 0.24516664882076875
Fold 2 IBS: 0.23125368314974099
Fold 3 IBS: 0.2293568925972559
Fold 4 IBS: 0.24026892015315723
Fold 5 IBS: 0.2284688763963705
[I 2024-04-15 17:40:57,764] Trial 30 finished with value: 0.2349030042234587 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6124736134433101, 'min_weight_fraction_leaf': 0.2917886569515737}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23047082448431727
Fold 2 IBS: 0.20246891396287392
Fold 3 IBS: 0.21289749096154267
Fold 4 IBS: 0.20606546111822555
Fold 5 IBS: 0.20284535946507126
[I 2024-04-15 17:41:01,248] Trial 31 finished with value: 0.21094960999840615 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8361347137992726, 'min_weight_fraction_leaf': 0.03501609599805008}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23186135655290802
Fold 2 IBS: 0.20807130827241002
Fold 3 IBS: 0.21621828236726157
Fold 4 IBS: 0.21183364435514496
Fold 5 IBS: 0.20435881794117025
[I 2024-04-15 17:41:05,442] Trial 32 finished with value: 0.21446868189777896 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8201064111842001, 'min_weight_fraction_leaf': 0.06986230996670711}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.24013309466551597
Fold 2 IBS: 0.22787347509441294
Fold 3 IBS: 0.22730662261512422
Fold 4 IBS: 0.23475603544288606
Fold 5 IBS: 0.22392160240432116
[I 2024-04-15 17:41:09,495] Trial 33 finished with value: 0.23079816604445208 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.718477421945693, 'min_weight_fraction_leaf': 0.025954136349888905}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23598465714590056
Fold 2 IBS: 0.22098086067446338
Fold 3 IBS: 0.2244338040981471
Fold 4 IBS: 0.22572345965184598
Fold 5 IBS: 0.2177110863833976
[I 2024-04-15 17:41:13,604] Trial 34 finished with value: 0.22496677359075093 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 406, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.47644913459202465, 'min_weight_fraction_leaf': 0.11296202404910355}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23720999318194194
Fold 2 IBS: 0.2195851660369273
Fold 3 IBS: 0.2221557548895528
Fold 4 IBS: 0.22429544133846352
Fold 5 IBS: 0.21651855788561725
[I 2024-04-15 17:41:18,434] Trial 35 finished with value: 0.22395298266650054 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 466, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8444130732122076, 'min_weight_fraction_leaf': 0.06127298323509586}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23629222682453177
Fold 2 IBS: 0.22116305254644525
Fold 3 IBS: 0.22415651065188286
Fold 4 IBS: 0.22640876022987147
Fold 5 IBS: 0.21646091343570567
[I 2024-04-15 17:41:21,181] Trial 36 finished with value: 0.2248962927376874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 362, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6469410804775977, 'min_weight_fraction_leaf': 0.15033911892764495}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.2463238521426889
Fold 2 IBS: 0.23213215809602944
Fold 3 IBS: 0.22956692732239173
Fold 4 IBS: 0.24156586424367174
Fold 5 IBS: 0.23018881683036485
[I 2024-04-15 17:41:24,264] Trial 37 finished with value: 0.23595552372702935 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9374906428960106, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.2336863572046514
Fold 2 IBS: 0.21149937906649338
Fold 3 IBS: 0.21674809490294666
Fold 4 IBS: 0.21088234152875324
Fold 5 IBS: 0.20523828690360826
[I 2024-04-15 17:41:26,504] Trial 38 finished with value: 0.2156108919212906 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5299108954298116, 'min_weight_fraction_leaf': 0.023210932334159107}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.2403724833791105
Fold 2 IBS: 0.22562505737000732
Fold 3 IBS: 0.2257335752896879
Fold 4 IBS: 0.23193339632104917
Fold 5 IBS: 0.2216111733097502
[I 2024-04-15 17:41:30,716] Trial 39 finished with value: 0.22905513713392103 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 472, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6056469778207588, 'min_weight_fraction_leaf': 0.12426285476200608}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23587289256484834
Fold 2 IBS: 0.21278692107973238
Fold 3 IBS: 0.22295101954600394
Fold 4 IBS: 0.2179741061306819
Fold 5 IBS: 0.21029584409389018
[I 2024-04-15 17:41:32,654] Trial 40 finished with value: 0.21997615668303133 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7514179603615019, 'min_weight_fraction_leaf': 0.05364065704818009}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23423604199977652
Fold 2 IBS: 0.21096892648335755
Fold 3 IBS: 0.2172530897071665
Fold 4 IBS: 0.21618347712927788
Fold 5 IBS: 0.21000545015664235
[I 2024-04-15 17:41:36,051] Trial 41 finished with value: 0.21772939709524416 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 428, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9215210793148375, 'min_weight_fraction_leaf': 0.07380824055516946}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23362871930168927
Fold 2 IBS: 0.20692128987232267
Fold 3 IBS: 0.21477986706865795
Fold 4 IBS: 0.21023452713737997
Fold 5 IBS: 0.20399265771844066
[I 2024-04-15 17:41:39,972] Trial 42 finished with value: 0.21391141221969812 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 435, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8291203686449198, 'min_weight_fraction_leaf': 0.028954072511129886}. Best is trial 23 with value: 0.21058740602327014.
Fold 1 IBS: 0.23060559633866898
Fold 2 IBS: 0.1997997172612395
Fold 3 IBS: 0.20949042808727011
Fold 4 IBS: 0.19914039074902343
Fold 5 IBS: 0.19676393342751303
[I 2024-04-15 17:41:44,045] Trial 43 finished with value: 0.207160013172743 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 477, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9533925599091754, 'min_weight_fraction_leaf': 0.015488144706192027}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.2325304480873737
Fold 2 IBS: 0.2115395579223014
Fold 3 IBS: 0.21709316627975284
Fold 4 IBS: 0.21187238763165125
Fold 5 IBS: 0.20604732001014317
[I 2024-04-15 17:41:48,829] Trial 44 finished with value: 0.21581657598624449 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7886255575767039, 'min_weight_fraction_leaf': 0.019257302791554038}. Best is trial 43 with value: 0.207160013172743.

Fold 1 IBS: 0.23464572254213412
Fold 2 IBS: 0.19994116107207244
Fold 3 IBS: 0.2110451082896479
Fold 4 IBS: 0.20480646084800908
Fold 5 IBS: 0.19826938161562588
[I 2024-04-15 17:41:50,368] Trial 45 finished with value: 0.20974156687349788 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 144, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9550453481916195, 'min_weight_fraction_leaf': 0.0043820704059355925}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.2352188360353779
Fold 2 IBS: 0.21012288416075062
Fold 3 IBS: 0.22006135263039905
Fold 4 IBS: 0.21420786948504866
Fold 5 IBS: 0.2046943511292496
[I 2024-04-15 17:41:51,759] Trial 46 finished with value: 0.2168610586881652 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9569178639389964, 'min_weight_fraction_leaf': 0.1097357424811503}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.2328410981904401
Fold 2 IBS: 0.21166854195220677
Fold 3 IBS: 0.2237235564296547
Fold 4 IBS: 0.21752956676163976
Fold 5 IBS: 0.20871049555091417
[I 2024-04-15 17:41:52,646] Trial 47 finished with value: 0.21889465177697112 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 93, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9947866748705748, 'min_weight_fraction_leaf': 0.059275520773950825}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.2309105146051548
Fold 2 IBS: 0.21206216853758633
Fold 3 IBS: 0.2166341746041588
Fold 4 IBS: 0.2119678196165596
Fold 5 IBS: 0.20428871035473983
[I 2024-04-15 17:41:56,411] Trial 48 finished with value: 0.21517267754363986 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8642499100263487, 'min_weight_fraction_leaf': 0.002826498272954064}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.23365410985251547
Fold 2 IBS: 0.2107914844331297
Fold 3 IBS: 0.21519283945743578
Fold 4 IBS: 0.21147002980768217
Fold 5 IBS: 0.20128395875069438
[I 2024-04-15 17:41:57,819] Trial 49 finished with value: 0.21447848446029152 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 169, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.954200626034364, 'min_weight_fraction_leaf': 0.005174552654121366}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.2371805999312355
Fold 2 IBS: 0.2191139163355276
Fold 3 IBS: 0.22316827855674118
Fold 4 IBS: 0.22407876215247177
Fold 5 IBS: 0.21658738752697612
[I 2024-04-15 17:41:59,948] Trial 50 finished with value: 0.2240257889005904 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 281, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9043838080799372, 'min_weight_fraction_leaf': 0.09553104757553799}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.23187612601121613
Fold 2 IBS: 0.21094170466721227
Fold 3 IBS: 0.2170315891901739
Fold 4 IBS: 0.21511265748983482
Fold 5 IBS: 0.20728448176322448
[I 2024-04-15 17:42:03,990] Trial 51 finished with value: 0.2164493118243323 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3820485816229619, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.2301531145986488
Fold 2 IBS: 0.20130493574883987
Fold 3 IBS: 0.21041072664566776
Fold 4 IBS: 0.20105995728492157
Fold 5 IBS: 0.19595215352506604
[I 2024-04-15 17:42:07,460] Trial 52 finished with value: 0.20777617756062877 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 417, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8487225482574863, 'min_weight_fraction_leaf': 0.02146483375345237}. Best is trial 43 with value: 0.207160013172743.
Fold 1 IBS: 0.2303301566136489
Fold 2 IBS: 0.20226791497013155
Fold 3 IBS: 0.20743542384868086
Fold 4 IBS: 0.19804755057908077
Fold 5 IBS: 0.1949171413914531
[I 2024-04-15 17:42:10,219] Trial 53 finished with value: 0.20659963748059904 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.955445025749567, 'min_weight_fraction_leaf': 0.016479019020140564}. Best is trial 53 with value: 0.20659963748059904.
Fold 1 IBS: 0.23077134730165705
Fold 2 IBS: 0.20203124478377463
Fold 3 IBS: 0.2091474702749256
Fold 4 IBS: 0.1986442078507676
Fold 5 IBS: 0.19396658221956084
[I 2024-04-15 17:42:12,956] Trial 54 finished with value: 0.20691217048613714 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 331, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9603547787825705, 'min_weight_fraction_leaf': 0.018653332450634125}. Best is trial 53 with value: 0.20659963748059904.
Fold 1 IBS: 0.230464282209045
Fold 2 IBS: 0.20345751905175277
Fold 3 IBS: 0.20679216912362725
Fold 4 IBS: 0.19538285453627113
Fold 5 IBS: 0.19400691755003222
[I 2024-04-15 17:42:15,748] Trial 55 finished with value: 0.2060207484941457 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9982391105866282, 'min_weight_fraction_leaf': 0.014274825176148894}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.23252076525949544
Fold 2 IBS: 0.20343095714064605
Fold 3 IBS: 0.20705742784865114
Fold 4 IBS: 0.19549565956598303
Fold 5 IBS: 0.19310446561578504
[I 2024-04-15 17:42:18,438] Trial 56 finished with value: 0.20632185508611212 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9988783695821659, 'min_weight_fraction_leaf': 0.008582264745741445}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.23296006220484428
Fold 2 IBS: 0.2051317230159284
Fold 3 IBS: 0.20952808095199124
Fold 4 IBS: 0.1943684005417122
Fold 5 IBS: 0.19228272702760685
[I 2024-04-15 17:42:20,974] Trial 57 finished with value: 0.20685419874841662 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9958184344878003, 'min_weight_fraction_leaf': 0.01775693316270821}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.23129756211803315
Fold 2 IBS: 0.2093708982507217
Fold 3 IBS: 0.21649578179440507
Fold 4 IBS: 0.21088757127933763
Fold 5 IBS: 0.20255443332592235
[I 2024-04-15 17:42:23,420] Trial 58 finished with value: 0.21412124935368398 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9983615259634832, 'min_weight_fraction_leaf': 0.07899880488818417}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.2431571006760828
Fold 2 IBS: 0.22958900836989787
Fold 3 IBS: 0.2290557829758658
Fold 4 IBS: 0.23687674515819504
Fold 5 IBS: 0.22633893569429683
[I 2024-04-15 17:42:26,657] Trial 59 finished with value: 0.23300351457486768 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9663068424305646, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 55 with value: 0.2060207484941457.

Fold 1 IBS: 0.23661847734506994
Fold 2 IBS: 0.22366715614035915
Fold 3 IBS: 0.2242603393930627
Fold 4 IBS: 0.22833423638241543
Fold 5 IBS: 0.2179281861428918
[I 2024-04-15 17:42:28,926] Trial 60 finished with value: 0.22616167908075982 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 296, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9882475281225217, 'min_weight_fraction_leaf': 0.2583710069782479}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.2293695725263114
Fold 2 IBS: 0.20363219479344702
Fold 3 IBS: 0.2088236286171769
Fold 4 IBS: 0.1987984694721575
Fold 5 IBS: 0.19493278055546723
[I 2024-04-15 17:42:32,002] Trial 61 finished with value: 0.207111329192912 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9488211841450735, 'min_weight_fraction_leaf': 0.01559165714905905}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.2312799417340269
Fold 2 IBS: 0.20461656084310967
Fold 3 IBS: 0.2086064943504001
Fold 4 IBS: 0.1961815300622319
Fold 5 IBS: 0.1929211583106367
[I 2024-04-15 17:42:34,698] Trial 62 finished with value: 0.20672113706008105 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 309, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9284521347314073, 'min_weight_fraction_leaf': 0.013333996823446215}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.23690606635291805
Fold 2 IBS: 0.20474604437507832
Fold 3 IBS: 0.20904463033864656
Fold 4 IBS: 0.1924779334478491
Fold 5 IBS: 0.1922325102618623
[I 2024-04-15 17:42:37,218] Trial 63 finished with value: 0.20708143695527087 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9136332002827972, 'min_weight_fraction_leaf': 8.112079479937265e-05}. Best is trial 55 with value: 0.2060207484941457.
Fold 1 IBS: 0.23443273134372497
Fold 2 IBS: 0.20353356004201775
Fold 3 IBS: 0.2056579528742388
Fold 4 IBS: 0.19367644611388637
Fold 5 IBS: 0.19123518456513303
[I 2024-04-15 17:42:39,895] Trial 64 finished with value: 0.2057071749878002 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9183889354438057, 'min_weight_fraction_leaf': 0.0017390275642744837}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23059347341415323
Fold 2 IBS: 0.20512398934456846
Fold 3 IBS: 0.21201460436741995
Fold 4 IBS: 0.20415796341039913
Fold 5 IBS: 0.19794359696332012
[I 2024-04-15 17:42:42,359] Trial 65 finished with value: 0.2099667254999722 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 269, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9996466685965416, 'min_weight_fraction_leaf': 0.053355598595893304}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.2306297337654848
Fold 2 IBS: 0.20909359312798012
Fold 3 IBS: 0.2159324718742143
Fold 4 IBS: 0.21061442318811097
Fold 5 IBS: 0.20162199510116985
[I 2024-04-15 17:42:44,333] Trial 66 finished with value: 0.213578443411392 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 243, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8954225536667554, 'min_weight_fraction_leaf': 0.06955197265225385}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.22953316337507737
Fold 2 IBS: 0.20804246746032623
Fold 3 IBS: 0.21355524072313783
Fold 4 IBS: 0.2073379794513997
Fold 5 IBS: 0.1993354907044866
[I 2024-04-15 17:42:46,754] Trial 67 finished with value: 0.21156086834288557 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9298061308708262, 'min_weight_fraction_leaf': 0.045093598415738685}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.228042744729218
Fold 2 IBS: 0.20988639756447056
Fold 3 IBS: 0.21504036394142378
Fold 4 IBS: 0.20860682020226928
Fold 5 IBS: 0.20095174846540936
[I 2024-04-15 17:42:49,298] Trial 68 finished with value: 0.2125056149805582 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8828822900838962, 'min_weight_fraction_leaf': 0.019255484232267077}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23005231752451555
Fold 2 IBS: 0.2100319338751095
Fold 3 IBS: 0.21522077606562937
Fold 4 IBS: 0.2114340568648705
Fold 5 IBS: 0.20229988571347898
[I 2024-04-15 17:42:51,929] Trial 69 finished with value: 0.21380779400872077 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9717840343217774, 'min_weight_fraction_leaf': 0.08584196341511345}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23023462311401716
Fold 2 IBS: 0.2033219970752445
Fold 3 IBS: 0.20951187981573394
Fold 4 IBS: 0.19854214269606324
Fold 5 IBS: 0.19504851561588524
[I 2024-04-15 17:42:54,135] Trial 70 finished with value: 0.2073318316633888 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.932903593459742, 'min_weight_fraction_leaf': 0.034843138475406876}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23754004172471016
Fold 2 IBS: 0.20467966577383553
Fold 3 IBS: 0.2087426676237042
Fold 4 IBS: 0.19228743521752367
Fold 5 IBS: 0.1934568047405669
[I 2024-04-15 17:42:56,781] Trial 71 finished with value: 0.20734132301606806 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 321, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9058806537563127, 'min_weight_fraction_leaf': 0.00560017574724335}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23223635381811542
Fold 2 IBS: 0.20515730712514632
Fold 3 IBS: 0.21108840484700084
Fold 4 IBS: 0.19368383313409093
Fold 5 IBS: 0.1909374830271599
[I 2024-04-15 17:42:58,969] Trial 72 finished with value: 0.20662067639030268 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9733016122490538, 'min_weight_fraction_leaf': 0.0005977822156702922}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23217415740245365
Fold 2 IBS: 0.20321236307998738
Fold 3 IBS: 0.21054686046340995
Fold 4 IBS: 0.19774629302063906
Fold 5 IBS: 0.1942479560049539
[I 2024-04-15 17:43:01,240] Trial 73 finished with value: 0.20758552599428878 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 267, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9741664464834033, 'min_weight_fraction_leaf': 0.025954301546075777}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.22896424517713543
Fold 2 IBS: 0.20674404403552388
Fold 3 IBS: 0.21434712637451123
Fold 4 IBS: 0.20280464976050894
Fold 5 IBS: 0.1964878673495973
[I 2024-04-15 17:43:03,142] Trial 74 finished with value: 0.20986958653945537 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9996928616815097, 'min_weight_fraction_leaf': 0.043769448998003654}. Best is trial 64 with value: 0.2057071749878002.

Fold 1 IBS: 0.23880493280560305
Fold 2 IBS: 0.22211084601176734
Fold 3 IBS: 0.22536872182721576
Fold 4 IBS: 0.22893705950842794
Fold 5 IBS: 0.21910939176460062
[I 2024-04-15 17:43:05,285] Trial 75 finished with value: 0.2268661903835229 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.23212254840913404, 'min_weight_fraction_leaf': 0.06322380085514831}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.24495500676299287
Fold 2 IBS: 0.23109350863163353
Fold 3 IBS: 0.22939694619359435
Fold 4 IBS: 0.24024660193684408
Fold 5 IBS: 0.2282876800438737
[I 2024-04-15 17:43:08,582] Trial 76 finished with value: 0.2347959487137877 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9383198739513575, 'min_weight_fraction_leaf': 0.42652948565502746}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.2293465669733154
Fold 2 IBS: 0.20496133639756886
Fold 3 IBS: 0.2127818885967299
Fold 4 IBS: 0.20170950374788527
Fold 5 IBS: 0.19706507807896634
[I 2024-04-15 17:43:12,544] Trial 77 finished with value: 0.20917287475889318 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9730800034728183, 'min_weight_fraction_leaf': 0.01922694298496893}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.22791999462305987
Fold 2 IBS: 0.2067170630028421
Fold 3 IBS: 0.2133014660199157
Fold 4 IBS: 0.20528664193509374
Fold 5 IBS: 0.19769201746473175
[I 2024-04-15 17:43:14,827] Trial 78 finished with value: 0.21018343660912864 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 229, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8875505325101326, 'min_weight_fraction_leaf': 0.044241554695636676}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23675252590039003
Fold 2 IBS: 0.1970247360548132
Fold 3 IBS: 0.2195873948071469
Fold 4 IBS: 0.19061887165112917
Fold 5 IBS: 0.19342257169510813
[I 2024-04-15 17:43:17,962] Trial 79 finished with value: 0.20748122002171748 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 353, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8588855846122465, 'min_weight_fraction_leaf': 0.012790333832156112}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.22865997078707623
Fold 2 IBS: 0.2028131567121528
Fold 3 IBS: 0.21006438363627453
Fold 4 IBS: 0.2001639073966863
Fold 5 IBS: 0.19704709283743022
[I 2024-04-15 17:43:21,255] Trial 80 finished with value: 0.20774970227392403 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 386, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9325404898178582, 'min_weight_fraction_leaf': 0.032532439145835756}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.2371062946229352
Fold 2 IBS: 0.20469299341941147
Fold 3 IBS: 0.20933313150733304
Fold 4 IBS: 0.19205109888554203
Fold 5 IBS: 0.19182603401376494
[I 2024-04-15 17:43:23,588] Trial 81 finished with value: 0.20700191048979732 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9115723723662662, 'min_weight_fraction_leaf': 0.004380820692277101}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23075894325477359
Fold 2 IBS: 0.20583805725549406
Fold 3 IBS: 0.21161449155649628
Fold 4 IBS: 0.20048376649344601
Fold 5 IBS: 0.19839238254815666
[I 2024-04-15 17:43:26,301] Trial 82 finished with value: 0.2094175282216733 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9737464448518401, 'min_weight_fraction_leaf': 0.0009422622743578291}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.22675213542375489
Fold 2 IBS: 0.20347999683846554
Fold 3 IBS: 0.2111321596053072
Fold 4 IBS: 0.19995231148838127
Fold 5 IBS: 0.19432672008010873
[I 2024-04-15 17:43:28,580] Trial 83 finished with value: 0.20712866468720353 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9031313235648333, 'min_weight_fraction_leaf': 0.029762686973132037}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23578878852465154
Fold 2 IBS: 0.2215546383620386
Fold 3 IBS: 0.2242252803721046
Fold 4 IBS: 0.22772156004687014
Fold 5 IBS: 0.21689670439466663
[I 2024-04-15 17:43:31,754] Trial 84 finished with value: 0.22523739434006634 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9451263881018451, 'min_weight_fraction_leaf': 0.015120390051039465}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.2338272585019149
Fold 2 IBS: 0.2177368126971471
Fold 3 IBS: 0.22121293571945527
Fold 4 IBS: 0.2206511690496407
Fold 5 IBS: 0.2138055379546603
[I 2024-04-15 17:43:33,673] Trial 85 finished with value: 0.22144674278456367 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9201697799783898, 'min_weight_fraction_leaf': 0.0607611593675708}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.22884788646938345
Fold 2 IBS: 0.20375496094258697
Fold 3 IBS: 0.21285101781887839
Fold 4 IBS: 0.19860548593341823
Fold 5 IBS: 0.1966236720814989
[I 2024-04-15 17:43:35,866] Trial 86 finished with value: 0.20813660464915315 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9731868578598892, 'min_weight_fraction_leaf': 0.043962588673107345}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23121802472268346
Fold 2 IBS: 0.20452460165097655
Fold 3 IBS: 0.21062049001869904
Fold 4 IBS: 0.20162303700131115
Fold 5 IBS: 0.19631287905882985
[I 2024-04-15 17:43:38,233] Trial 87 finished with value: 0.2088598064905 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8006945317034183, 'min_weight_fraction_leaf': 0.011539974168207387}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23604192200852606
Fold 2 IBS: 0.2241815714292428
Fold 3 IBS: 0.22466562523349662
Fold 4 IBS: 0.22788845163765445
Fold 5 IBS: 0.2183788902483614
[I 2024-04-15 17:43:41,862] Trial 88 finished with value: 0.22623129211145626 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 318, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8760025207855067, 'min_weight_fraction_leaf': 0.21681424356325293}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23970297834793616
Fold 2 IBS: 0.22662186055954806
Fold 3 IBS: 0.22673443937139603
Fold 4 IBS: 0.23380569546002644
Fold 5 IBS: 0.22432409187039046
[I 2024-04-15 17:43:44,086] Trial 89 finished with value: 0.23023781312185942 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9529652927111821, 'min_weight_fraction_leaf': 0.3316965630817691}. Best is trial 64 with value: 0.2057071749878002.

Fold 1 IBS: 0.2288522415361709
Fold 2 IBS: 0.20354231400911754
Fold 3 IBS: 0.21065867348158182
Fold 4 IBS: 0.19846433877057512
Fold 5 IBS: 0.19526700958232354
[I 2024-04-15 17:43:47,455] Trial 90 finished with value: 0.20735691547595375 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 373, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9849096047855805, 'min_weight_fraction_leaf': 0.028193081489496362}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23693605369947957
Fold 2 IBS: 0.2044148977534312
Fold 3 IBS: 0.20934155605387997
Fold 4 IBS: 0.19204742285057097
Fold 5 IBS: 0.19182732197423547
[I 2024-04-15 17:43:50,221] Trial 91 finished with value: 0.20691345046631943 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 303, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9114585887308614, 'min_weight_fraction_leaf': 0.0026364361089883104}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23393017236552022
Fold 2 IBS: 0.20044967965302923
Fold 3 IBS: 0.2078593968466562
Fold 4 IBS: 0.1944720222275392
Fold 5 IBS: 0.1925306926434143
[I 2024-04-15 17:43:53,927] Trial 92 finished with value: 0.20584839274723182 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9156279209229512, 'min_weight_fraction_leaf': 0.010667271784339112}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23215673923481242
Fold 2 IBS: 0.21466963900514552
Fold 3 IBS: 0.22044423900634072
Fold 4 IBS: 0.21450710072591148
Fold 5 IBS: 0.20905066292466098
[I 2024-04-15 17:43:57,327] Trial 93 finished with value: 0.2181656761793742 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8413226147468642, 'min_weight_fraction_leaf': 0.015730199989503736}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.22690485404106572
Fold 2 IBS: 0.2040225905488943
Fold 3 IBS: 0.21057479498611767
Fold 4 IBS: 0.20120375973071006
Fold 5 IBS: 0.19333718607158906
[I 2024-04-15 17:44:00,294] Trial 94 finished with value: 0.20720863707567533 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8845980125149194, 'min_weight_fraction_leaf': 0.02898753092614771}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.2338814101871045
Fold 2 IBS: 0.21644481619135583
Fold 3 IBS: 0.22076954471901286
Fold 4 IBS: 0.21970249532058234
Fold 5 IBS: 0.21251169101361667
[I 2024-04-15 17:44:03,483] Trial 95 finished with value: 0.22066199148633445 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9591341913532253, 'min_weight_fraction_leaf': 0.04896591479201633}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23478076041915277
Fold 2 IBS: 0.1965265593810577
Fold 3 IBS: 0.21684294805947257
Fold 4 IBS: 0.19147301452561113
Fold 5 IBS: 0.19655166891999445
[I 2024-04-15 17:44:06,781] Trial 96 finished with value: 0.20723499026105774 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9378867837353213, 'min_weight_fraction_leaf': 0.03796002421721704}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.23321171143798983
Fold 2 IBS: 0.21555113906657272
Fold 3 IBS: 0.22141379145170773
Fold 4 IBS: 0.21868387901264677
Fold 5 IBS: 0.2123994304894378
[I 2024-04-15 17:44:09,008] Trial 97 finished with value: 0.22025199029167095 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4216462167271724, 'min_weight_fraction_leaf': 0.0758273697891223}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.2340656447475648
Fold 2 IBS: 0.20346651944015864
Fold 3 IBS: 0.20991678138081316
Fold 4 IBS: 0.19274230708278223
Fold 5 IBS: 0.18983139652248143
[I 2024-04-15 17:44:11,695] Trial 98 finished with value: 0.20600452983476006 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9822475391637099, 'min_weight_fraction_leaf': 0.0006908609239351451}. Best is trial 64 with value: 0.2057071749878002.
Fold 1 IBS: 0.2291741216776064
Fold 2 IBS: 0.21039197219139855
Fold 3 IBS: 0.2152072605754578
Fold 4 IBS: 0.20889863901095143
Fold 5 IBS: 0.2059957667530803
[I 2024-04-15 17:44:14,999] Trial 99 finished with value: 0.21393355204169887 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.998911047184745, 'min_weight_fraction_leaf': 0.0140622123730909}. Best is trial 64 with value: 0.2057071749878002.


* Best trial for IBS:
 FrozenTrial(number=64, state=TrialState.COMPLETE, values=[0.2057071749878002], datetime_start=datetime.datetime(2024, 4, 15, 17, 42, 37, 223505), datetime_complete=datetime.datetime(2024, 4, 15, 17, 42, 39, 893843), params={'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9183889354438057, 'min_weight_fraction_leaf': 0.0017390275642744837}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=64, value=None)


* Best Score for IBS:
 0.2057071749878002

In [143]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [144]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.206

#### Test

In [145]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [146]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=18, max_leaf_nodes=14,
                   max_samples=0.6321905190335297, min_samples_leaf=1,
                   min_samples_split=8,
                   min_weight_fraction_leaf=0.009478700458801217,
                   n_estimators=101, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.485

ExtraSurvivalTrees(max_depth=15, max_features='auto', max_leaf_nodes=20,
                   max_samples=0.9183889354438057, min_samples_leaf=1,
                   min_samples_split=18,
                   min_weight_fraction_leaf=0.0017390275642744837,
                   n_estimators=313, random_state=123, warm_start=True)

IBS: 0.254

In [147]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [148]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:44:16,212] A new study created in memory with name: no-name-1feb84ca-550b-4b6d-a826-dee457c6bc66

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:44:34,479] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:44:43,920] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:44:52,593] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:05,277] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:11,171] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:12,836] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:25,183] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:29,174] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:45:29,641] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 17:46:06,380] Trial 9 finished with value: 0.70205736041358 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 17:46:59,522] Trial 10 finished with value: 0.6727533375211936 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:47:58,438] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 17:48:55,366] Trial 12 finished with value: 0.6915084901128223 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.70205736041358.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:49:23,408] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:50:01,501] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:50:33,634] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:50:54,768] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:51:40,288] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:52:55,065] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:52:57,528] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:53:24,199] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 17:54:19,958] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 17:55:14,487] Trial 22 finished with value: 0.6443581285716469 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:56:05,109] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:56:37,556] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:57:16,846] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:57:32,987] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:58:20,312] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:58:23,056] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:58:54,337] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 17:59:03,346] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-15 17:59:39,920] Trial 31 finished with value: 0.6101958569131466 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:00:19,838] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:00:48,200] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:01:16,274] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 18:01:35,136] Trial 35 finished with value: 0.6743933936379024 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:01:51,004] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-15 18:02:02,231] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:02:10,912] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:02:20,548] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:02:31,512] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6072961373390557
[I 2024-04-15 18:03:11,982] Trial 41 finished with value: 0.637733354361669 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:03:42,558] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:04:20,612] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:04:32,121] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:05:13,615] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.70205736041358.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.7381974248927039
[I 2024-04-15 18:05:18,623] Trial 46 finished with value: 0.7177433139318685 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7177433139318685.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:05:26,652] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7177433139318685.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:05:26,812] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.7177433139318685.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:05:31,364] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.7177433139318685.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:05:54,292] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.7177433139318685.
Fold 1 C-index: 0.6553784860557769
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 18:06:16,233] Trial 51 finished with value: 0.6888783206531184 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7177433139318685.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:06:28,060] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7177433139318685.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 18:06:53,409] Trial 53 finished with value: 0.719214253977509 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:07:14,295] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:07:18,454] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:07:38,674] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 18:07:41,763] Trial 57 finished with value: 0.7134313645347635 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:07:45,504] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:07:51,048] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:07:55,952] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 53 with value: 0.719214253977509.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:08:01,850] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 53 with value: 0.719214253977509.

Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 18:08:14,221] Trial 62 finished with value: 0.7203198269937945 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 18:08:25,160] Trial 63 finished with value: 0.7144382337823598 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:08:37,075] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.4297477654076297, 'learning_rate': 0.03167082341067062, 'dropout_rate': 0.8340106690810649, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4320841878399444, 'min_weight_fraction_leaf': 0.262263288003764, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9077599801548327, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:08:45,614] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.30781242416514565, 'learning_rate': 0.04403843282374086, 'dropout_rate': 0.9070553557876073, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9229393860301199, 'min_weight_fraction_leaf': 0.309698162609194, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0017887993094304819, 'validation_fraction': 0.9980996520608811, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:08:55,566] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.4940796114228873, 'learning_rate': 0.035347527077929, 'dropout_rate': 0.8595655519672745, 'n_estimators': 458, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5356537836856377, 'min_weight_fraction_leaf': 0.2862767894594348, 'max_features': 'sqrt', 'min_impurity_decrease': 0.012061434840147687, 'validation_fraction': 0.3085811036906729, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:08,614] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4210285565476828, 'learning_rate': 0.050089102888303386, 'dropout_rate': 0.7306956719066184, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.26956754513635534, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00610717642726731, 'validation_fraction': 0.7699846612598108, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:14,612] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.36755564370451066, 'learning_rate': 0.02012145930359608, 'dropout_rate': 0.9624657416538887, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1963333375412561, 'min_weight_fraction_leaf': 0.24702341213277396, 'max_features': 1, 'min_impurity_decrease': 0.021693222709295752, 'validation_fraction': 0.715818151257265, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:29,011] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.4580799169024674, 'learning_rate': 0.04243487065654221, 'dropout_rate': 0.798114398171325, 'n_estimators': 497, 'criterion': 'friedman_mse', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.22161177753979142, 'max_features': 'log2', 'min_impurity_decrease': 0.001581139753892363, 'validation_fraction': 0.9661547589426094, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 62 with value: 0.7203198269937945.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7553648068669528
[I 2024-04-15 18:09:36,158] Trial 70 finished with value: 0.7230577139805714 and parameters: {'subsample': 0.5134787621027924, 'learning_rate': 0.03815415454699774, 'dropout_rate': 0.9284284423267337, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010011726187714272, 'min_weight_fraction_leaf': 0.3011740807021421, 'max_features': 0.1, 'min_impurity_decrease': 0.042176472946749144, 'validation_fraction': 0.8042843145134158, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 70 with value: 0.7230577139805714.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.8231939163498099
Fold 5 C-index: 0.7467811158798283
[I 2024-04-15 18:09:37,650] Trial 71 finished with value: 0.7282221026791705 and parameters: {'subsample': 0.5131192378371329, 'learning_rate': 0.03727507508877366, 'dropout_rate': 0.9228694642191336, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.30209681644390535, 'max_features': 0.1, 'min_impurity_decrease': 0.07623847919135997, 'validation_fraction': 0.8184047274043963, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 71 with value: 0.7282221026791705.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7381974248927039
[I 2024-04-15 18:09:38,869] Trial 72 finished with value: 0.7294572459776856 and parameters: {'subsample': 0.5113292744810009, 'learning_rate': 0.03769488430329127, 'dropout_rate': 0.91502503958971, 'n_estimators': 151, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0048717552527591836, 'min_weight_fraction_leaf': 0.3032600022438751, 'max_features': 0.1, 'min_impurity_decrease': 0.09932930546575598, 'validation_fraction': 0.7524856089234744, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:40,230] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.48745899160328254, 'learning_rate': 0.03488711013986941, 'dropout_rate': 0.9207027707058856, 'n_estimators': 166, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7397736803977201, 'min_weight_fraction_leaf': 0.30503417699651847, 'max_features': 0.1, 'min_impurity_decrease': 0.05304956394458357, 'validation_fraction': 0.8120762455660575, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 72 with value: 0.7294572459776856.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:41,331] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5142486143767481, 'learning_rate': 0.03893854896571226, 'dropout_rate': 0.8830262522349845, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3282745678695592, 'min_weight_fraction_leaf': 0.3221351699358789, 'max_features': 0.1, 'min_impurity_decrease': 0.03307073029227666, 'validation_fraction': 0.7592577607349541, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 18:09:41,953] Trial 75 finished with value: 0.7214493548036698 and parameters: {'subsample': 0.5742452691833468, 'learning_rate': 0.03334572331738648, 'dropout_rate': 0.9649674582324527, 'n_estimators': 99, 'criterion': 'friedman_mse', 'ccp_alpha': 0.008879065905147206, 'min_weight_fraction_leaf': 0.29852358510326127, 'max_features': 0.1, 'min_impurity_decrease': 0.096813277833116, 'validation_fraction': 0.8584385362155433, 'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:42,986] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.574150395990174, 'learning_rate': 0.027463310919689433, 'dropout_rate': 0.8463341728501959, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 0.909207312853643, 'min_weight_fraction_leaf': 0.29203448999627785, 'max_features': 0.1, 'min_impurity_decrease': 0.0852933973434153, 'validation_fraction': 0.8669306200363046, 'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:43,466] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5424404888658997, 'learning_rate': 0.037336906291853156, 'dropout_rate': 0.9380257217549791, 'n_estimators': 71, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5589177281911889, 'min_weight_fraction_leaf': 0.34663852778439663, 'max_features': 0.1, 'min_impurity_decrease': 0.04888898306282359, 'validation_fraction': 0.9245622717270865, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:44,701] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.45366564794134967, 'learning_rate': 0.033325100118557605, 'dropout_rate': 0.9716425111114492, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28678334291474916, 'min_weight_fraction_leaf': 0.32324164305502207, 'max_features': 0.1, 'min_impurity_decrease': 0.015832270182665708, 'validation_fraction': 0.8989236128299398, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 18:09:45,283] Trial 79 finished with value: 0.7242820854846121 and parameters: {'subsample': 0.5089247178740638, 'learning_rate': 0.02879538621992717, 'dropout_rate': 0.8880756346487753, 'n_estimators': 76, 'criterion': 'friedman_mse', 'ccp_alpha': 0.006881367522992329, 'min_weight_fraction_leaf': 0.28189763106059557, 'max_features': 0.1, 'min_impurity_decrease': 0.04092235077014568, 'validation_fraction': 0.794851868223685, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:45,884] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.5769427664458449, 'learning_rate': 0.027972204104443642, 'dropout_rate': 0.8790127643704845, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 5.796520641928455, 'min_weight_fraction_leaf': 0.2997081168892121, 'max_features': 0.1, 'min_impurity_decrease': 0.0358325028031739, 'validation_fraction': 0.7383774868511407, 'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 9}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:09:46,566] Trial 81 finished with value: 0.7067327887439342 and parameters: {'subsample': 0.4334168478350933, 'learning_rate': 0.030383370398124023, 'dropout_rate': 0.8969099250965981, 'n_estimators': 90, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025557079673147583, 'min_weight_fraction_leaf': 0.2792394931449018, 'max_features': 0.1, 'min_impurity_decrease': 0.0967897628084889, 'validation_fraction': 0.7970605268245392, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:48,395] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.5035107145537238, 'learning_rate': 0.025151282858900878, 'dropout_rate': 0.9257442908039857, 'n_estimators': 206, 'criterion': 'friedman_mse', 'ccp_alpha': 0.29093310545892165, 'min_weight_fraction_leaf': 0.2776830351973235, 'max_features': 0.1, 'min_impurity_decrease': 0.008499830800622027, 'validation_fraction': 0.8520851342828201, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:48,753] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.4777045218808249, 'learning_rate': 0.046708165123813046, 'dropout_rate': 0.8211596995689314, 'n_estimators': 41, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6371924903356401, 'min_weight_fraction_leaf': 0.31261084504523506, 'max_features': 0.1, 'min_impurity_decrease': 0.05069376948199788, 'validation_fraction': 0.7066576135314336, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:49,854] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.517347233965865, 'learning_rate': 0.039985185181237316, 'dropout_rate': 0.9364256108305966, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2622208926429443, 'min_weight_fraction_leaf': 0.2537009245614157, 'max_features': 0.1, 'min_impurity_decrease': 0.023021026868211072, 'validation_fraction': 0.7860545778870955, 'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:50,461] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.5403649043936768, 'learning_rate': 0.033606227774279324, 'dropout_rate': 0.9757164865575928, 'n_estimators': 101, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.38338275524240367, 'max_features': 0.1, 'min_impurity_decrease': 0.06503020800833678, 'validation_fraction': 0.8705333866806247, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 72 with value: 0.7294572459776856.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:51,802] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.6365738405156823, 'learning_rate': 0.0425288521433015, 'dropout_rate': 0.7830607846587125, 'n_estimators': 126, 'criterion': 'friedman_mse', 'ccp_alpha': 1.352686864561732, 'min_weight_fraction_leaf': 0.3615778077904656, 'max_features': 0.1, 'min_impurity_decrease': 0.03971862584267303, 'validation_fraction': 0.8297524885007292, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:54,762] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.4745189509816943, 'learning_rate': 0.03700965128477396, 'dropout_rate': 0.8672645332885421, 'n_estimators': 247, 'criterion': 'friedman_mse', 'ccp_alpha': 0.598937287016192, 'min_weight_fraction_leaf': 0.3387245510594008, 'max_features': 0.1, 'min_impurity_decrease': 0.023371472873195284, 'validation_fraction': 0.6680285608353984, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:55,180] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.5846812888650746, 'learning_rate': 0.04715135099387363, 'dropout_rate': 0.8979575801071908, 'n_estimators': 60, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8429615048171984, 'min_weight_fraction_leaf': 0.2693806923298396, 'max_features': 0.1, 'min_impurity_decrease': 0.015247821974880593, 'validation_fraction': 0.9405076325063558, 'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 7}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:09:55,478] Trial 89 finished with value: 0.7065008424991028 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.0291127768811808, 'dropout_rate': 0.5046132436074291, 'n_estimators': 28, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019083182133763817, 'min_weight_fraction_leaf': 0.2980965136087394, 'max_features': 0.1, 'min_impurity_decrease': 0.09511853682533954, 'validation_fraction': 0.23411107196799597, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:09:57,412] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.1430413165132784, 'learning_rate': 0.0244288481994098, 'dropout_rate': 0.9477330042752554, 'n_estimators': 230, 'criterion': 'friedman_mse', 'ccp_alpha': 0.470159127925516, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 0.1, 'min_impurity_decrease': 0.06222701204256068, 'validation_fraction': 0.8996077312692432, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 18:09:58,394] Trial 91 finished with value: 0.7131741562503368 and parameters: {'subsample': 0.4151202450888264, 'learning_rate': 0.05100992370161866, 'dropout_rate': 0.9995918232131338, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038324466824448115, 'min_weight_fraction_leaf': 0.23203247428708706, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003326983296751487, 'validation_fraction': 0.8170318870815041, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:10:01,396] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.4362907934340635, 'learning_rate': 0.05141591622174496, 'dropout_rate': 0.44384990665331314, 'n_estimators': 146, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2689793172520216, 'min_weight_fraction_leaf': 0.31766388372758325, 'max_features': 'log2', 'min_impurity_decrease': 0.02881494066255111, 'validation_fraction': 0.759858064546031, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:10:06,168] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.40557920771368, 'learning_rate': 0.04329401985156921, 'dropout_rate': 0.9770240631682349, 'n_estimators': 468, 'criterion': 'friedman_mse', 'ccp_alpha': 0.46530276553929395, 'min_weight_fraction_leaf': 0.2527005558600451, 'max_features': 0.1, 'min_impurity_decrease': 3.672195771778603e-05, 'validation_fraction': 0.8380645637832662, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.5965665236051502
[I 2024-04-15 18:10:06,925] Trial 94 finished with value: 0.6355205583820182 and parameters: {'subsample': 0.3474996745904486, 'learning_rate': 0.03303232431979841, 'dropout_rate': 0.9265618996884103, 'n_estimators': 100, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1773994490697906, 'min_weight_fraction_leaf': 0.33475293501633135, 'max_features': 1, 'min_impurity_decrease': 0.0002963124812907417, 'validation_fraction': 0.9705278098015683, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:10:07,561] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.5556732803988387, 'learning_rate': 0.055629084034103854, 'dropout_rate': 0.9059325570265766, 'n_estimators': 85, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7659076746632735, 'min_weight_fraction_leaf': 0.2816282029261978, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04527805134430205, 'validation_fraction': 0.8067764812355601, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6212765957446809
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 18:10:17,564] Trial 96 finished with value: 0.7010561678190841 and parameters: {'subsample': 0.3135761086551203, 'learning_rate': 0.02188837457698108, 'dropout_rate': 0.8476343681400277, 'n_estimators': 457, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03064184256540073, 'min_weight_fraction_leaf': 0.30188082654908116, 'max_features': 'sqrt', 'min_impurity_decrease': 0.010509784128624949, 'validation_fraction': 0.867716918746646, 'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:10:23,923] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.5276397648894067, 'learning_rate': 0.0383926534998034, 'dropout_rate': 0.9575907438207372, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0520971192154476, 'min_weight_fraction_leaf': 0.24303505528997738, 'max_features': 0.1, 'min_impurity_decrease': 0.06368385804912063, 'validation_fraction': 0.7441685072726025, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 72 with value: 0.7294572459776856.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 18:10:24,539] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.4455733277584748, 'learning_rate': 0.06065076232609097, 'dropout_rate': 0.8094391899083884, 'n_estimators': 58, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.35001278572419203, 'max_features': 'log2', 'min_impurity_decrease': 0.0168212553908044, 'validation_fraction': 0.7801653173977179, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 6}. Best is trial 72 with value: 0.7294572459776856.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-15 18:10:26,501] A new study created in memory with name: no-name-aa582391-8ef1-498e-838f-0d941afac5fa

Fold 5 C-index: 0.5
[I 2024-04-15 18:10:26,486] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.4947106725007675, 'learning_rate': 0.03566645000969104, 'dropout_rate': 0.6345584081586646, 'n_estimators': 117, 'criterion': 'friedman_mse', 'ccp_alpha': 1.687141841503839, 'min_weight_fraction_leaf': 0.2717934261823665, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010262263774722573, 'validation_fraction': 0.8891022384409022, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 72 with value: 0.7294572459776856.


* Best trial for C-index:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.7294572459776856], datetime_start=datetime.datetime(2024, 4, 15, 18, 9, 37, 655784), datetime_complete=datetime.datetime(2024, 4, 15, 18, 9, 38, 869190), params={'subsample': 0.5113292744810009, 'learning_rate': 0.03769488430329127, 'dropout_rate': 0.91502503958971, 'n_estimators': 151, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0048717552527591836, 'min_weight_fraction_leaf': 0.3032600022438751, 'max_features': 0.1, 'min_impurity_decrease': 0.09932930546575598, 'validation_fraction': 0.7524856089234744, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=72, value=None)


* Best Score for C-index:
 0.7294572459776856

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:10:38,958] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:10:45,398] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:10:51,382] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:11:00,825] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:11:04,876] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:11:05,942] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:11:15,798] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:11:18,908] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:11:19,287] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24599690320017423
Fold 2 IBS: 0.23037320047743615
Fold 3 IBS: 0.22866399971848883
Fold 4 IBS: 0.24084522441316789
Fold 5 IBS: 0.22855937522449543
[I 2024-04-15 18:11:44,736] Trial 9 finished with value: 0.23488774060675252 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316615258034594
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-15 18:12:24,794] Trial 10 finished with value: 0.2356345447701623 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:13:11,008] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24715496002116139
Fold 2 IBS: 0.23184677797440564
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-15 18:13:51,221] Trial 12 finished with value: 0.23582736637047277 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:14:11,018] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:14:44,918] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:15:14,660] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:15:30,978] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:16:10,305] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:16:30,244] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:16:33,514] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:17:08,817] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24711009086064675
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-15 18:17:48,426] Trial 21 finished with value: 0.2358286550709061 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23488774060675252.
Fold 1 IBS: 0.24593277151572374
Fold 2 IBS: 0.23011380010187196

Fold 3 IBS: 0.2285706566070161
Fold 4 IBS: 0.24065109811212707
Fold 5 IBS: 0.2284896896086154
[I 2024-04-15 18:18:32,954] Trial 22 finished with value: 0.23475160318907085 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:19:11,610] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:19:34,990] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:19:58,679] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:20:32,305] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:20:35,738] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:20:48,484] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:21:19,595] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:21:32,383] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.2469488707078328
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-15 18:22:12,682] Trial 31 finished with value: 0.23566408867478444 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.2459158024546861
Fold 2 IBS: 0.23026000114478867
Fold 3 IBS: 0.22854503604847085
Fold 4 IBS: 0.2406482123830189
Fold 5 IBS: 0.22852595657457914
[I 2024-04-15 18:22:55,622] Trial 32 finished with value: 0.23477900172110874 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:23:25,017] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:24:01,497] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:24:09,666] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:24:53,354] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:24:54,798] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:25:16,731] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:25:47,201] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:26:14,458] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24639762298206533
Fold 2 IBS: 0.23085588721262176
Fold 3 IBS: 0.22864682158818475
Fold 4 IBS: 0.24109346243789703
Fold 5 IBS: 0.22881532954741768
[I 2024-04-15 18:26:50,882] Trial 41 finished with value: 0.23516182475363728 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24597874502450626
Fold 2 IBS: 0.2303635373562148
Fold 3 IBS: 0.22848042477653244
Fold 4 IBS: 0.2407198640459751
Fold 5 IBS: 0.22851822138866804
[I 2024-04-15 18:27:30,344] Trial 42 finished with value: 0.23481215851837933 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:28:14,648] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:28:43,468] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24692612071754597
Fold 2 IBS: 0.23153409869843258
Fold 3 IBS: 0.2287718371755271
Fold 4 IBS: 0.24150807216564213
Fold 5 IBS: 0.22908959541576482
[I 2024-04-15 18:29:12,164] Trial 45 finished with value: 0.2355659448345825 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:29:38,687] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:29:50,519] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:29:50,725] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:29:57,345] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:30:36,182] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24695451791550146
Fold 2 IBS: 0.23155811871567236
Fold 3 IBS: 0.22879587750691563
Fold 4 IBS: 0.24151430558593232
Fold 5 IBS: 0.22907951632725373
[I 2024-04-15 18:31:06,451] Trial 51 finished with value: 0.2355804672102551 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:31:42,715] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.2464516919325978
Fold 2 IBS: 0.23062466277160285
Fold 3 IBS: 0.22849134472380853
Fold 4 IBS: 0.24062487500047663
Fold 5 IBS: 0.2284758011577283
[I 2024-04-15 18:32:14,073] Trial 53 finished with value: 0.23493367511724284 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:32:45,423] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:33:13,916] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:33:40,952] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:34:07,437] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:34:45,084] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:35:14,141] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:35:27,577] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:35:48,925] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.246857007064065
Fold 2 IBS: 0.2312172540805443
Fold 3 IBS: 0.228720138777521
Fold 4 IBS: 0.24121709506061287
Fold 5 IBS: 0.22888539322971113
[I 2024-04-15 18:36:07,401] Trial 62 finished with value: 0.23537937764249084 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:36:27,768] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24653374809378162
Fold 2 IBS: 0.23060654551210855
Fold 3 IBS: 0.22835483628646305
Fold 4 IBS: 0.24111869429930435
Fold 5 IBS: 0.22890119380415408
[I 2024-04-15 18:36:45,299] Trial 64 finished with value: 0.2351030035991623 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-15 18:37:03,571] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:37:23,412] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:37:35,651] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:38:04,616] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:38:30,632] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:38:48,286] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24688597390892708
Fold 2 IBS: 0.2312589868889756
Fold 3 IBS: 0.22869668776014807
Fold 4 IBS: 0.24124782655980948
Fold 5 IBS: 0.22891518571788028
[I 2024-04-15 18:39:06,701] Trial 71 finished with value: 0.2354009321671481 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24700057611358014
Fold 2 IBS: 0.2315539527282102
Fold 3 IBS: 0.22880896369553697
Fold 4 IBS: 0.2415229151224228
Fold 5 IBS: 0.2290797592196454
[I 2024-04-15 18:39:20,609] Trial 72 finished with value: 0.2355932333758791 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:39:22,956] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:40:00,811] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:40:16,912] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:40:37,812] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:41:05,820] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:41:17,822] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:41:46,584] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:42:00,693] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24688150285294977
Fold 2 IBS: 0.23123211288735615
Fold 3 IBS: 0.22868585018793217
Fold 4 IBS: 0.2412229481295521
Fold 5 IBS: 0.22885703055999884
[I 2024-04-15 18:42:19,086] Trial 81 finished with value: 0.23537588892355782 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:42:37,301] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:42:59,967] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898178857692084
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939292849858364
[I 2024-04-15 18:43:11,872] Trial 84 finished with value: 0.2359272947038577 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.23475160318907085.
Fold 1 IBS: 0.24486591103849437
Fold 2 IBS: 0.22798704816757207
Fold 3 IBS: 0.2269378367231564
Fold 4 IBS: 0.23782990840035811
Fold 5 IBS: 0.22651921703825845
[I 2024-04-15 18:43:40,013] Trial 85 finished with value: 0.23282798427356788 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:44:11,541] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8921917646046833, 'learning_rate': 0.03493887873396886, 'dropout_rate': 0.20248417164561996, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.02811592341251499, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:44:22,857] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9521381251132186, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:44:56,051] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8783477148356468, 'learning_rate': 0.019145642246983192, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.11068414611763369, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:45:26,700] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9225585795675643, 'learning_rate': 0.0028206049164217276, 'dropout_rate': 0.16604269499086277, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 1.572109186144046, 'min_weight_fraction_leaf': 0.27088299579805813, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.905787363075094, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:45:58,943] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.09273837444215938, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8657908240711146, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24628585066070857
Fold 2 IBS: 0.23023491367026225
Fold 3 IBS: 0.22815923551373563
Fold 4 IBS: 0.2407508200444184
Fold 5 IBS: 0.22854619713045807
[I 2024-04-15 18:46:29,960] Trial 91 finished with value: 0.23479540340391658 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.021129279003315533, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.9309517539709111, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:47:00,033] Trial 92 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.02241134247478034, 'dropout_rate': 0.2583752131981347, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.4943670196310161, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 9.135609514383116e-07, 'validation_fraction': 0.929257109542098, 'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 18:47:24,613] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9562310140378132, 'learning_rate': 0.017182645082053097, 'dropout_rate': 0.30303355573944185, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.20362952808416507, 'min_weight_fraction_leaf': 0.06487551572722715, 'max_features': 'auto', 'min_impurity_decrease': 2.2745718823187047e-07, 'validation_fraction': 0.979813726530939, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:47:48,245] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9803432784281702, 'learning_rate': 0.011448180194224972, 'dropout_rate': 0.28058975756978766, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.6843293477116347, 'min_weight_fraction_leaf': 0.1982598024964269, 'max_features': None, 'min_impurity_decrease': 5.981184732872339e-07, 'validation_fraction': 0.9454695844953723, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:48:21,333] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9455952167309377, 'learning_rate': 0.03849480232107322, 'dropout_rate': 0.3201948574529592, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.9601205383555245, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 3.7935126700511503e-07, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24557381697553923
Fold 2 IBS: 0.22843322557847542
Fold 3 IBS: 0.22857721621066904
Fold 4 IBS: 0.2400598315906517
Fold 5 IBS: 0.2279355389988583
[I 2024-04-15 18:48:42,450] Trial 96 finished with value: 0.23411592587083874 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.02041047784766359, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.2253662010001949, 'max_features': 'auto', 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.32386831053055254, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:49:07,220] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.026783144722107532, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 0.43549519886063537, 'min_weight_fraction_leaf': 0.22023393103598612, 'max_features': 'auto', 'min_impurity_decrease': 1.3568805622065066e-07, 'validation_fraction': 0.31617010634192105, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:49:24,010] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7743094980751969, 'learning_rate': 0.020410071578111352, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 1.1387001784940558, 'min_weight_fraction_leaf': 0.22558745505753475, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.1600852440936258, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23282798427356788.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 18:49:51,313] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.25443633448028735, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.2223066295281712, 'min_weight_fraction_leaf': 0.25005462596245476, 'max_features': 'auto', 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.4189919199463679, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.23282798427356788.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23282798427356788], datetime_start=datetime.datetime(2024, 4, 15, 18, 43, 11, 876328), datetime_complete=datetime.datetime(2024, 4, 15, 18, 43, 40, 12891), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23282798427356788

In [149]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [150]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.729
train_ibs:  0.233

#### Test

In [151]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [152]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0048717552527591836,
                                 dropout_rate=0.91502503958971,
                                 learning_rate=0.03769488430329127, max_depth=6,
                                 max_features=0.1, max_leaf_nodes=11,
                                 min_impurity_decrease=0.09932930546575598,
                                 min_samples_leaf=12, min_samples_split=18,
                                 min_weight_fraction_leaf=0.3032600022438751,
                                 n_estimators=151, random_state=123,
                                 subsample=0.5113292744810009,
                                 validation_fraction=0.7524856089234744)

C-index score: 0.499

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.229

In [153]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [154]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [155]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 18:49:57,943] A new study created in memory with name: no-name-ccbd4d30-ef76-43fe-b979-ea736700f5e7

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:49:58,485] Trial 0 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6423526693826518.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:02,504] Trial 1 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:03,267] Trial 2 finished with value: 0.6398895181851605 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:04,260] Trial 3 finished with value: 0.6410622977559646 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:05,796] Trial 4 finished with value: 0.6410296656257357 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:07,592] Trial 5 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:08,435] Trial 6 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:50:08,634] Trial 7 finished with value: 0.6499035318694023 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:09,636] Trial 8 finished with value: 0.6438735819301804 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:12,318] Trial 9 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:12,493] Trial 10 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:15,921] Trial 11 finished with value: 0.6458177039675884 and parameters: {'subsample': 0.1913192016083392, 'dropout_rate': 0.653844054640545, 'n_estimators': 479, 'learning_rate': 0.09497904560009218}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:50:17,919] Trial 12 finished with value: 0.6484222863130964 and parameters: {'subsample': 0.11615582976955166, 'dropout_rate': 0.7156669644400785, 'n_estimators': 341, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:50:19,776] Trial 13 finished with value: 0.6476470925146468 and parameters: {'subsample': 0.11036933079077518, 'dropout_rate': 0.7302564728030555, 'n_estimators': 339, 'learning_rate': 0.09856277651579823}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:20,027] Trial 14 finished with value: 0.6458647932005428 and parameters: {'subsample': 0.34544676001457536, 'dropout_rate': 0.6361246097272036, 'n_estimators': 55, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:21,742] Trial 15 finished with value: 0.6412440801321633 and parameters: {'subsample': 0.3316968574353417, 'dropout_rate': 0.8137734084975752, 'n_estimators': 308, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.6499035318694023.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:50:23,985] Trial 16 finished with value: 0.657004876911789 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 400, 'learning_rate': 0.040259456601039204}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:26,460] Trial 17 finished with value: 0.6444313311281792 and parameters: {'subsample': 0.3651265887647699, 'dropout_rate': 0.9126380154354596, 'n_estimators': 431, 'learning_rate': 0.03849448589154982}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:26,797] Trial 18 finished with value: 0.6450827179762243 and parameters: {'subsample': 0.24128157828721308, 'dropout_rate': 0.9647461872134607, 'n_estimators': 94, 'learning_rate': 0.014749859187971195}. Best is trial 16 with value: 0.657004876911789.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:28,655] Trial 19 finished with value: 0.6436924938049693 and parameters: {'subsample': 0.403731145647275, 'dropout_rate': 0.9947981608913361, 'n_estimators': 400, 'learning_rate': 0.04269105711861253}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:29,739] Trial 20 finished with value: 0.6471335458766757 and parameters: {'subsample': 0.6102628884762309, 'dropout_rate': 0.7933084651006226, 'n_estimators': 258, 'learning_rate': 0.023714096641497005}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:50:32,395] Trial 21 finished with value: 0.6508306191656519 and parameters: {'subsample': 0.11014863416226671, 'dropout_rate': 0.6080226687634136, 'n_estimators': 410, 'learning_rate': 0.044072832784268275}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:50:35,074] Trial 22 finished with value: 0.6411059595001296 and parameters: {'subsample': 0.19248201672248066, 'dropout_rate': 0.5885616331304216, 'n_estimators': 410, 'learning_rate': 0.0436632312634945}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:50:36,674] Trial 23 finished with value: 0.6460967049177475 and parameters: {'subsample': 0.15125113481629013, 'dropout_rate': 0.5245405015036182, 'n_estimators': 298, 'learning_rate': 0.025604021649257045}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:38,959] Trial 24 finished with value: 0.642728636204452 and parameters: {'subsample': 0.2701868884063052, 'dropout_rate': 0.6286197680521202, 'n_estimators': 380, 'learning_rate': 0.04561177121422356}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:41,528] Trial 25 finished with value: 0.6436924938049693 and parameters: {'subsample': 0.4107976229299747, 'dropout_rate': 0.79766074843426, 'n_estimators': 433, 'learning_rate': 0.013287182579533728}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:42,111] Trial 26 finished with value: 0.6417012825346068 and parameters: {'subsample': 0.877159049230894, 'dropout_rate': 0.3131916215957328, 'n_estimators': 137, 'learning_rate': 0.05789019405404601}. Best is trial 16 with value: 0.657004876911789.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:42,227] Trial 27 finished with value: 0.6699472340896035 and parameters: {'subsample': 0.19718036296309377, 'dropout_rate': 0.6979039748471498, 'n_estimators': 1, 'learning_rate': 0.030307532796347948}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:43,921] Trial 28 finished with value: 0.6442532730969914 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.45691787023529357, 'n_estimators': 290, 'learning_rate': 0.031981052358301974}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:46,892] Trial 29 finished with value: 0.6427502551550064 and parameters: {'subsample': 0.2795457981709511, 'dropout_rate': 0.7559203903957843, 'n_estimators': 453, 'learning_rate': 0.016491021939899028}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 18:50:47,025] Trial 30 finished with value: 0.6662099630075701 and parameters: {'subsample': 0.1118897916027584, 'dropout_rate': 0.8500242507999418, 'n_estimators': 5, 'learning_rate': 0.06354770598840508}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 18:50:47,436] Trial 31 finished with value: 0.6467055481156715 and parameters: {'subsample': 0.10838542207494216, 'dropout_rate': 0.8520483924589783, 'n_estimators': 99, 'learning_rate': 0.062795268442302}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:47,590] Trial 32 finished with value: 0.6513196501661136 and parameters: {'subsample': 0.17447953751280512, 'dropout_rate': 0.9387013663234357, 'n_estimators': 19, 'learning_rate': 0.06673620494867692}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:47,736] Trial 33 finished with value: 0.6450672862005513 and parameters: {'subsample': 0.20706627502642933, 'dropout_rate': 0.9467717165832947, 'n_estimators': 11, 'learning_rate': 0.08198592699051854}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:47,867] Trial 34 finished with value: 0.637837021360774 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.8768432942839997, 'n_estimators': 2, 'learning_rate': 0.06961889414248804}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:48,133] Trial 35 finished with value: 0.6494821351123073 and parameters: {'subsample': 0.16955676601561037, 'dropout_rate': 0.9999429048432434, 'n_estimators': 63, 'learning_rate': 0.07717353058256372}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:48,676] Trial 36 finished with value: 0.6404688863337136 and parameters: {'subsample': 0.2876997424343593, 'dropout_rate': 0.9378415869226606, 'n_estimators': 131, 'learning_rate': 0.06650716000662588}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:48,993] Trial 37 finished with value: 0.6434527360029765 and parameters: {'subsample': 0.1574001051965189, 'dropout_rate': 0.8374055765137145, 'n_estimators': 75, 'learning_rate': 0.05621431261796065}. Best is trial 27 with value: 0.6699472340896035.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:50:49,203] Trial 38 finished with value: 0.6461656935232163 and parameters: {'subsample': 0.30366897196288706, 'dropout_rate': 0.13272164755980653, 'n_estimators': 35, 'learning_rate': 0.04918505031160733}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:50,626] Trial 39 finished with value: 0.6410080466751813 and parameters: {'subsample': 0.23052838497416736, 'dropout_rate': 0.8890898259545601, 'n_estimators': 227, 'learning_rate': 0.0605670628016505}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:51,422] Trial 40 finished with value: 0.6412656990827176 and parameters: {'subsample': 0.43583700272141335, 'dropout_rate': 0.7825497504780614, 'n_estimators': 162, 'learning_rate': 0.05279313488926278}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:50:51,587] Trial 41 finished with value: 0.6490972478778237 and parameters: {'subsample': 0.13669966216924315, 'dropout_rate': 0.6875395326119147, 'n_estimators': 6, 'learning_rate': 0.0387571754393424}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 18:50:51,866] Trial 42 finished with value: 0.6443076776128993 and parameters: {'subsample': 0.10340394629892727, 'dropout_rate': 0.5829669700795875, 'n_estimators': 36, 'learning_rate': 0.07198300959242822}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:50:52,401] Trial 43 finished with value: 0.6418516782492084 and parameters: {'subsample': 0.16143503916850604, 'dropout_rate': 0.41035779262395466, 'n_estimators': 87, 'learning_rate': 0.027633234880330062}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:50:55,366] Trial 44 finished with value: 0.6394576590782821 and parameters: {'subsample': 0.21795904257380533, 'dropout_rate': 0.5020020877800176, 'n_estimators': 368, 'learning_rate': 0.06523605428553468}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:50:55,997] Trial 45 finished with value: 0.6439462948806598 and parameters: {'subsample': 0.5599008816333128, 'dropout_rate': 0.9193789815814094, 'n_estimators': 119, 'learning_rate': 0.04745778489796225}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 18:50:59,433] Trial 46 finished with value: 0.6467376294160093 and parameters: {'subsample': 0.1455842946258062, 'dropout_rate': 0.8332122643620747, 'n_estimators': 494, 'learning_rate': 0.029977864542511785}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:01,210] Trial 47 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.749942117166262, 'n_estimators': 338, 'learning_rate': 0.02011782838490002}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 18:51:01,380] Trial 48 finished with value: 0.6592466051901489 and parameters: {'subsample': 0.1004359647341087, 'dropout_rate': 0.19701471782839963, 'n_estimators': 24, 'learning_rate': 0.039295843194964826}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:01,565] Trial 49 finished with value: 0.6477229625459844 and parameters: {'subsample': 0.18273141978102397, 'dropout_rate': 0.17019576693077848, 'n_estimators': 24, 'learning_rate': 0.03850572076571382}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:01,829] Trial 50 finished with value: 0.6442711677025349 and parameters: {'subsample': 0.3137695620610963, 'dropout_rate': 0.2461975150016868, 'n_estimators': 55, 'learning_rate': 0.007949712324643067}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:02,008] Trial 51 finished with value: 0.655190522745637 and parameters: {'subsample': 0.1035895232640987, 'dropout_rate': 0.5986270749263469, 'n_estimators': 25, 'learning_rate': 0.03378645178031582}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:02,195] Trial 52 finished with value: 0.6442859052272203 and parameters: {'subsample': 0.246876407657029, 'dropout_rate': 0.6793182054640541, 'n_estimators': 32, 'learning_rate': 0.032569097347603285}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:02,313] Trial 53 finished with value: 0.6699472340896035 and parameters: {'subsample': 0.1402528357391214, 'dropout_rate': 0.33925630195803175, 'n_estimators': 1, 'learning_rate': 0.03506940455389224}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 18:51:02,541] Trial 54 finished with value: 0.64676710446538 and parameters: {'subsample': 0.12844477283169595, 'dropout_rate': 0.25439476577609554, 'n_estimators': 44, 'learning_rate': 0.03485270095984073}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:02,861] Trial 55 finished with value: 0.6498773673360145 and parameters: {'subsample': 0.14212906916737422, 'dropout_rate': 0.31740876936767465, 'n_estimators': 72, 'learning_rate': 0.03668854224144564}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.562015503875969
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6008583690987125
[I 2024-04-15 18:51:02,995] Trial 56 finished with value: 0.6307982837618928 and parameters: {'subsample': 0.10971428599325941, 'dropout_rate': 0.3756962807652878, 'n_estimators': 1, 'learning_rate': 0.040858088290391045}. Best is trial 27 with value: 0.6699472340896035.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:03,246] Trial 57 finished with value: 0.6426775422045269 and parameters: {'subsample': 0.20753382543348137, 'dropout_rate': 0.16948193907535794, 'n_estimators': 50, 'learning_rate': 0.020570994628935912}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:03,726] Trial 58 finished with value: 0.6382595362119127 and parameters: {'subsample': 0.6810537336561748, 'dropout_rate': 0.10823881394124338, 'n_estimators': 107, 'learning_rate': 0.02843584262564445}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:04,076] Trial 59 finished with value: 0.6450463615009845 and parameters: {'subsample': 0.2531582378681703, 'dropout_rate': 0.5659376368797568, 'n_estimators': 81, 'learning_rate': 0.05238163388639053}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:04,268] Trial 60 finished with value: 0.6548547637309224 and parameters: {'subsample': 0.13627773860806836, 'dropout_rate': 0.2182480603163226, 'n_estimators': 23, 'learning_rate': 0.03418310924815257}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 18:51:04,489] Trial 61 finished with value: 0.6524422826902999 and parameters: {'subsample': 0.1354470525417838, 'dropout_rate': 0.2113197658439001, 'n_estimators': 20, 'learning_rate': 0.03260410401773385}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 18:51:04,811] Trial 62 finished with value: 0.6497546784796537 and parameters: {'subsample': 0.17597455013714625, 'dropout_rate': 0.2067938909241616, 'n_estimators': 59, 'learning_rate': 0.042009895009131215}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 18:51:05,025] Trial 63 finished with value: 0.6494038950980607 and parameters: {'subsample': 0.10657217798062563, 'dropout_rate': 0.2205178594196074, 'n_estimators': 33, 'learning_rate': 0.025381765759709678}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:05,184] Trial 64 finished with value: 0.649725330417118 and parameters: {'subsample': 0.203077695547079, 'dropout_rate': 0.2841729436533881, 'n_estimators': 15, 'learning_rate': 0.035490122184347335}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:05,483] Trial 65 finished with value: 0.6499463559414831 and parameters: {'subsample': 0.13589933517932656, 'dropout_rate': 0.3182503716024589, 'n_estimators': 47, 'learning_rate': 0.045496242426745416}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 18:51:06,932] Trial 66 finished with value: 0.6569905632301597 and parameters: {'subsample': 0.10177849527539361, 'dropout_rate': 0.42691400830139714, 'n_estimators': 239, 'learning_rate': 0.03988314962457415}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 18:51:07,780] Trial 67 finished with value: 0.6578705512794267 and parameters: {'subsample': 0.10382598522662699, 'dropout_rate': 0.4141256487367654, 'n_estimators': 170, 'learning_rate': 0.04067379291719353}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 18:51:08,814] Trial 68 finished with value: 0.6474001728648253 and parameters: {'subsample': 0.17827726452478615, 'dropout_rate': 0.42783706615923556, 'n_estimators': 200, 'learning_rate': 0.0480853336948571}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 18:51:10,100] Trial 69 finished with value: 0.6489574418875936 and parameters: {'subsample': 0.15849565641667118, 'dropout_rate': 0.46258815859314956, 'n_estimators': 238, 'learning_rate': 0.040540514500080616}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:11,615] Trial 70 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.5230627782030943, 'n_estimators': 269, 'learning_rate': 0.029701657165883383}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 18:51:12,317] Trial 71 finished with value: 0.65792480236021 and parameters: {'subsample': 0.10686417463160529, 'dropout_rate': 0.35724042315957477, 'n_estimators': 154, 'learning_rate': 0.03726414095357562}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 18:51:13,086] Trial 72 finished with value: 0.65792480236021 and parameters: {'subsample': 0.10280810182976342, 'dropout_rate': 0.38138256283402633, 'n_estimators': 149, 'learning_rate': 0.03726157841972152}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:13,918] Trial 73 finished with value: 0.6466399869989925 and parameters: {'subsample': 0.1954553613091294, 'dropout_rate': 0.34424127919336855, 'n_estimators': 165, 'learning_rate': 0.04396136454554976}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:14,600] Trial 74 finished with value: 0.6491896240127297 and parameters: {'subsample': 0.12914164974282455, 'dropout_rate': 0.35808739748425206, 'n_estimators': 143, 'learning_rate': 0.03790908733460835}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.714828897338403

Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:15,583] Trial 75 finished with value: 0.6529702864309966 and parameters: {'subsample': 0.1572438949655824, 'dropout_rate': 0.40480719234240864, 'n_estimators': 190, 'learning_rate': 0.05153089532985127}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:16,771] Trial 76 finished with value: 0.6441589411959575 and parameters: {'subsample': 0.21854844987239208, 'dropout_rate': 0.28706859079448677, 'n_estimators': 216, 'learning_rate': 0.04600551196823061}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:17,637] Trial 77 finished with value: 0.6545818065345481 and parameters: {'subsample': 0.1001113329159704, 'dropout_rate': 0.9726539182455299, 'n_estimators': 177, 'learning_rate': 0.02178928202600048}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 18:51:18,347] Trial 78 finished with value: 0.6528723736060484 and parameters: {'subsample': 0.16859680469049393, 'dropout_rate': 0.3494458838065849, 'n_estimators': 149, 'learning_rate': 0.05534042847651925}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:18,888] Trial 79 finished with value: 0.6523004377132554 and parameters: {'subsample': 0.125291626960004, 'dropout_rate': 0.44943325389932615, 'n_estimators': 118, 'learning_rate': 0.049793732566284624}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:20,902] Trial 80 finished with value: 0.6418775723746648 and parameters: {'subsample': 0.25647575579785614, 'dropout_rate': 0.3753778706678197, 'n_estimators': 314, 'learning_rate': 0.02577934587559958}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:22,549] Trial 81 finished with value: 0.649898986286569 and parameters: {'subsample': 0.15105741703771358, 'dropout_rate': 0.4327236250903558, 'n_estimators': 285, 'learning_rate': 0.041119390704349355}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 18:51:23,874] Trial 82 finished with value: 0.6521630113322093 and parameters: {'subsample': 0.12377252653497668, 'dropout_rate': 0.47441778196281653, 'n_estimators': 246, 'learning_rate': 0.030345604513808983}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 18:51:24,580] Trial 83 finished with value: 0.6483424115147882 and parameters: {'subsample': 0.185822400715643, 'dropout_rate': 0.3962554612430957, 'n_estimators': 154, 'learning_rate': 0.03931225583609592}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:25,698] Trial 84 finished with value: 0.6545275554537648 and parameters: {'subsample': 0.11644910182542231, 'dropout_rate': 0.33536438453088335, 'n_estimators': 214, 'learning_rate': 0.043016849696362214}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 18:51:26,705] Trial 85 finished with value: 0.6570121821807142 and parameters: {'subsample': 0.102496990913917, 'dropout_rate': 0.2922629382635262, 'n_estimators': 193, 'learning_rate': 0.035021118131419796}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:27,694] Trial 86 finished with value: 0.6481934046899149 and parameters: {'subsample': 0.22124689935653374, 'dropout_rate': 0.3797893332373065, 'n_estimators': 201, 'learning_rate': 0.05912924596533803}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:28,625] Trial 87 finished with value: 0.6521803551078617 and parameters: {'subsample': 0.15366485952498626, 'dropout_rate': 0.27791884703392206, 'n_estimators': 182, 'learning_rate': 0.03538673247962338}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:29,100] Trial 88 finished with value: 0.6410080466751813 and parameters: {'subsample': 0.1719335542643201, 'dropout_rate': 0.3002940596357345, 'n_estimators': 100, 'learning_rate': 0.031791996454200146}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:29,778] Trial 89 finished with value: 0.640613617983685 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.23755511703679705, 'n_estimators': 129, 'learning_rate': 0.03686351004054085}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:30,070] Trial 90 finished with value: 0.648147009707948 and parameters: {'subsample': 0.12024447840261701, 'dropout_rate': 0.8937356560314051, 'n_estimators': 67, 'learning_rate': 0.028522636306985226}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:31,345] Trial 91 finished with value: 0.6537376241306299 and parameters: {'subsample': 0.14399260537753372, 'dropout_rate': 0.42007313431963905, 'n_estimators': 228, 'learning_rate': 0.039204734512455944}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:32,883] Trial 92 finished with value: 0.6514493738834681 and parameters: {'subsample': 0.11063719854784933, 'dropout_rate': 0.49681028751941886, 'n_estimators': 263, 'learning_rate': 0.04533548980626254}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 18:51:33,730] Trial 93 finished with value: 0.6571100950056623 and parameters: {'subsample': 0.10132068409009924, 'dropout_rate': 0.3609499145344804, 'n_estimators': 166, 'learning_rate': 0.03146669390488651}. Best is trial 27 with value: 0.6699472340896035.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 18:51:34,503] Trial 94 finished with value: 0.6483167877972633 and parameters: {'subsample': 0.19113015207763034, 'dropout_rate': 0.36546073037280785, 'n_estimators': 159, 'learning_rate': 0.025057063827088732}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 18:51:35,507] Trial 95 finished with value: 0.6467234427212151 and parameters: {'subsample': 0.10055205436378417, 'dropout_rate': 0.18873110265345241, 'n_estimators': 191, 'learning_rate': 0.03171025199447267}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 18:51:36,202] Trial 96 finished with value: 0.6471699023519155 and parameters: {'subsample': 0.5793526440822916, 'dropout_rate': 0.8590094793081559, 'n_estimators': 174, 'learning_rate': 0.08791879465920027}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 18:51:36,369] Trial 97 finished with value: 0.6455326251237709 and parameters: {'subsample': 0.13145967612871778, 'dropout_rate': 0.3199293209700993, 'n_estimators': 9, 'learning_rate': 0.01771954471064362}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 18:51:37,060] Trial 98 finished with value: 0.6514346363587827 and parameters: {'subsample': 0.15865554114204874, 'dropout_rate': 0.27493563261224097, 'n_estimators': 139, 'learning_rate': 0.027345061993103333}. Best is trial 27 with value: 0.6699472340896035.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383

[I 2024-04-15 18:51:37,848] A new study created in memory with name: no-name-5d340588-3e21-4098-8db5-15d5dfc2e648

Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 18:51:37,843] Trial 99 finished with value: 0.6418048594241853 and parameters: {'subsample': 0.23307106422809312, 'dropout_rate': 0.6579543997265371, 'n_estimators': 167, 'learning_rate': 0.037007717510352166}. Best is trial 27 with value: 0.6699472340896035.


* Best trial for C-index:
 FrozenTrial(number=27, state=TrialState.COMPLETE, values=[0.6699472340896035], datetime_start=datetime.datetime(2024, 4, 15, 18, 50, 42, 113668), datetime_complete=datetime.datetime(2024, 4, 15, 18, 50, 42, 227097), params={'subsample': 0.19718036296309377, 'dropout_rate': 0.6979039748471498, 'n_estimators': 1, 'learning_rate': 0.030307532796347948}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=27, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.19718036296309377, 'dropout_rate': 0.6979039748471498, 'n_estimators': 1, 'learning_rate': 0.030307532796347948}


* Best Score for C-index:
 0.6699472340896035

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2535208184290341
Fold 2 IBS: 0.23694039312201395
Fold 3 IBS: 0.3183278645100559
Fold 4 IBS: 0.2785272332047015
Fold 5 IBS: 0.26959701773388006
[I 2024-04-15 18:51:38,436] Trial 0 finished with value: 0.27138266539993705 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.4379931381955231
Fold 2 IBS: 0.38220982923025065
Fold 3 IBS: 0.3920321662913435
Fold 4 IBS: 0.3412768011671995
Fold 5 IBS: 0.33941908574786966
[I 2024-04-15 18:51:42,311] Trial 1 finished with value: 0.3785862041264373 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.3324678077695315
Fold 2 IBS: 0.277934644896449
Fold 3 IBS: 0.37028973305297364
Fold 4 IBS: 0.29747016904097373
Fold 5 IBS: 0.30753782579260386
[I 2024-04-15 18:51:43,080] Trial 2 finished with value: 0.31714003611050634 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.31819805240780114
Fold 2 IBS: 0.2752541423102686
Fold 3 IBS: 0.37171315150390805
Fold 4 IBS: 0.2766993729668638
Fold 5 IBS: 0.32392753761654436
[I 2024-04-15 18:51:44,099] Trial 3 finished with value: 0.3131584513610772 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.32511222009503676
Fold 2 IBS: 0.28095889098768023
Fold 3 IBS: 0.37647097763017984
Fold 4 IBS: 0.27532283726309925
Fold 5 IBS: 0.32310002134289806
[I 2024-04-15 18:51:45,628] Trial 4 finished with value: 0.31619298946377883 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.43183877461465453
Fold 2 IBS: 0.3462655068788492
Fold 3 IBS: 0.3901822518832906
Fold 4 IBS: 0.3158040918671078
Fold 5 IBS: 0.3240588862506669
[I 2024-04-15 18:51:47,649] Trial 5 finished with value: 0.36162990229891384 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.23162026538239194
Fold 2 IBS: 0.2130450924041672
Fold 3 IBS: 0.2929798151511939
Fold 4 IBS: 0.2602468384417057
Fold 5 IBS: 0.24596662301082522
[I 2024-04-15 18:51:48,465] Trial 6 finished with value: 0.2487717268780568 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2487717268780568.
Fold 1 IBS: 0.2219624571251742
Fold 2 IBS: 0.20191698224064816
Fold 3 IBS: 0.2554464703379466
Fold 4 IBS: 0.22028035730313134
Fold 5 IBS: 0.21397872069101548
[I 2024-04-15 18:51:48,702] Trial 7 finished with value: 0.22271699753958316 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.26135001657957846
Fold 2 IBS: 0.24282456049458448
Fold 3 IBS: 0.326134406423236
Fold 4 IBS: 0.27402360123646585
Fold 5 IBS: 0.2768152873434484
[I 2024-04-15 18:51:49,825] Trial 8 finished with value: 0.27622957441546264 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.438775036769916
Fold 2 IBS: 0.35568555286291453
Fold 3 IBS: 0.390909578851063
Fold 4 IBS: 0.31218235322033017
Fold 5 IBS: 0.32722373811786437
[I 2024-04-15 18:51:53,468] Trial 9 finished with value: 0.3649552519644176 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.2460224099705921
Fold 2 IBS: 0.23086098108808756
Fold 3 IBS: 0.2288453379547681
Fold 4 IBS: 0.24136765896018506
Fold 5 IBS: 0.2281543805010059
[I 2024-04-15 18:51:53,779] Trial 10 finished with value: 0.23505015369492774 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.24222241773116046
Fold 2 IBS: 0.22722173122509534
Fold 3 IBS: 0.2286593447825781
Fold 4 IBS: 0.2395148036138026
Fold 5 IBS: 0.22443221144275918
[I 2024-04-15 18:51:53,974] Trial 11 finished with value: 0.23241010175907917 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.24103596366815974
Fold 2 IBS: 0.21481009289866906
Fold 3 IBS: 0.30499365850510085
Fold 4 IBS: 0.22665926260480357
Fold 5 IBS: 0.24808858483619964
[I 2024-04-15 18:51:54,327] Trial 12 finished with value: 0.24711751250258657 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.23944832000588395
Fold 2 IBS: 0.22451123143312443
Fold 3 IBS: 0.22879762094537542
Fold 4 IBS: 0.23820765139553346
Fold 5 IBS: 0.22173810615143869
[I 2024-04-15 18:51:54,523] Trial 13 finished with value: 0.23054058598627117 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22826207452412578
Fold 2 IBS: 0.20708009192406637
Fold 3 IBS: 0.2838897565833488
Fold 4 IBS: 0.2304990846646447
Fold 5 IBS: 0.23724799446889894
[I 2024-04-15 18:51:55,063] Trial 14 finished with value: 0.23739580043301692 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.275392871065553
Fold 2 IBS: 0.2585619199470001
Fold 3 IBS: 0.34359360523637944
Fold 4 IBS: 0.26893592353517226
Fold 5 IBS: 0.29228774764528515
[I 2024-04-15 18:51:55,612] Trial 15 finished with value: 0.287754413485878 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.29706394157149196
Fold 2 IBS: 0.2724055701705109
Fold 3 IBS: 0.3535154729969376
Fold 4 IBS: 0.24863741322529886
Fold 5 IBS: 0.316457108751701
[I 2024-04-15 18:51:57,600] Trial 16 finished with value: 0.29761590134318805 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22571204260462702
Fold 2 IBS: 0.21029571932609178
Fold 3 IBS: 0.23477013659701168
Fold 4 IBS: 0.23294813806507536
Fold 5 IBS: 0.2112667744029953
[I 2024-04-15 18:51:57,893] Trial 17 finished with value: 0.2229985621991602 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22749628705840008
Fold 2 IBS: 0.208593559309439
Fold 3 IBS: 0.2860837988705294
Fold 4 IBS: 0.255694330022353
Fold 5 IBS: 0.23961625820762958
[I 2024-04-15 18:51:59,781] Trial 18 finished with value: 0.24349684669367022 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22458664776493728
Fold 2 IBS: 0.20232195896375377
Fold 3 IBS: 0.27412770407771303
Fold 4 IBS: 0.2250727043053573

Fold 5 IBS: 0.22885900132307044
[I 2024-04-15 18:52:00,349] Trial 19 finished with value: 0.23099360328696633 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22813963029627435
Fold 2 IBS: 0.21261919492535192
Fold 3 IBS: 0.2328032377684259
Fold 4 IBS: 0.23177471930860935
Fold 5 IBS: 0.21241390693232276
[I 2024-04-15 18:52:00,669] Trial 20 finished with value: 0.22355013784619687 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.23294882482388735
Fold 2 IBS: 0.2172731528360657
Fold 3 IBS: 0.23037554967791973
Fold 4 IBS: 0.23393962524579212
Fold 5 IBS: 0.21554329357937044
[I 2024-04-15 18:52:00,976] Trial 21 finished with value: 0.22601608923260708 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 7 with value: 0.22271699753958316.
Fold 1 IBS: 0.22457381812654392
Fold 2 IBS: 0.20893564288887
Fold 3 IBS: 0.23611424341865672
Fold 4 IBS: 0.23267189537604366
Fold 5 IBS: 0.21078105893610707
[I 2024-04-15 18:52:01,241] Trial 22 finished with value: 0.22261533174924425 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.7601905131808098, 'n_estimators': 57, 'learning_rate': 0.019334429052945145}. Best is trial 22 with value: 0.22261533174924425.
Fold 1 IBS: 0.2719235052333098
Fold 2 IBS: 0.23764489493573734
Fold 3 IBS: 0.3193018171397408
Fold 4 IBS: 0.2836424571696349
Fold 5 IBS: 0.2702613255072474
[I 2024-04-15 18:52:01,892] Trial 23 finished with value: 0.27655479999713406 and parameters: {'subsample': 0.8557281003254902, 'dropout_rate': 0.618865896035061, 'n_estimators': 150, 'learning_rate': 0.04186582141545488}. Best is trial 22 with value: 0.22261533174924425.
Fold 1 IBS: 0.22147474510826237
Fold 2 IBS: 0.2056747916191557
Fold 3 IBS: 0.24049201615940596
Fold 4 IBS: 0.23256814236182405
Fold 5 IBS: 0.21033940163812648
[I 2024-04-15 18:52:02,155] Trial 24 finished with value: 0.22210981937735488 and parameters: {'subsample': 0.8736292350257677, 'dropout_rate': 0.9758883725345413, 'n_estimators': 56, 'learning_rate': 0.02427957701685606}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.2294989380094321
Fold 2 IBS: 0.21197456891857033
Fold 3 IBS: 0.23574856019681506
Fold 4 IBS: 0.2257154796263744
Fold 5 IBS: 0.21156767240983257
[I 2024-04-15 18:52:02,391] Trial 25 finished with value: 0.2229010438322049 and parameters: {'subsample': 0.19468056412788132, 'dropout_rate': 0.9897789595635863, 'n_estimators': 40, 'learning_rate': 0.025002990823540957}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.23333397090317404
Fold 2 IBS: 0.21300462246331686
Fold 3 IBS: 0.2919265248430093
Fold 4 IBS: 0.26141154567737246
Fold 5 IBS: 0.24514756200998605
[I 2024-04-15 18:52:02,752] Trial 26 finished with value: 0.24896484517937173 and parameters: {'subsample': 0.9043940009344528, 'dropout_rate': 0.9033888277148059, 'n_estimators': 92, 'learning_rate': 0.04553017387255954}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.23638591525082767
Fold 2 IBS: 0.21516306172620478
Fold 3 IBS: 0.2951885661305264
Fold 4 IBS: 0.2637815004845914
Fold 5 IBS: 0.2478693530817822
[I 2024-04-15 18:52:03,317] Trial 27 finished with value: 0.25167767933478646 and parameters: {'subsample': 0.8218236648644409, 'dropout_rate': 0.7846036392151594, 'n_estimators': 145, 'learning_rate': 0.030307532796347948}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.24064419834309675
Fold 2 IBS: 0.22415587169214657
Fold 3 IBS: 0.22881420079591844
Fold 4 IBS: 0.23691192893868948
Fold 5 IBS: 0.22161208522226886
[I 2024-04-15 18:52:04,278] Trial 28 finished with value: 0.23042765699842405 and parameters: {'subsample': 0.3907993998263619, 'dropout_rate': 0.9279548799256215, 'n_estimators': 233, 'learning_rate': 0.001303388577036546}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.21842977369684194
Fold 2 IBS: 0.2011107725842906
Fold 3 IBS: 0.25384448921376923
Fold 4 IBS: 0.232211579011124
Fold 5 IBS: 0.2157044751662694
[I 2024-04-15 18:52:04,757] Trial 29 finished with value: 0.22426021793445905 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.7695165335542838, 'n_estimators': 108, 'learning_rate': 0.01903980772031594}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.22163880438788114
Fold 2 IBS: 0.2060581683786993
Fold 3 IBS: 0.2396778541303928
Fold 4 IBS: 0.22756268731638724
Fold 5 IBS: 0.21031352296982186
[I 2024-04-15 18:52:04,956] Trial 30 finished with value: 0.22105020743663645 and parameters: {'subsample': 0.7079769658545929, 'dropout_rate': 0.8498048136204235, 'n_estimators': 29, 'learning_rate': 0.046221173886982825}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2200724127940874
Fold 2 IBS: 0.20420688373140491
Fold 3 IBS: 0.2434279631041286
Fold 4 IBS: 0.23088381472023015
Fold 5 IBS: 0.2107203802256644
[I 2024-04-15 18:52:05,146] Trial 31 finished with value: 0.22186229091510307 and parameters: {'subsample': 0.7782166094867763, 'dropout_rate': 0.8526511128221191, 'n_estimators': 26, 'learning_rate': 0.05869348626309983}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2220192442415896
Fold 2 IBS: 0.20656029859231154
Fold 3 IBS: 0.23956067627789562
Fold 4 IBS: 0.23254630069491217
Fold 5 IBS: 0.21031393154503805
[I 2024-04-15 18:52:05,386] Trial 32 finished with value: 0.22220009027034937 and parameters: {'subsample': 0.7878845579666447, 'dropout_rate': 0.8560240225148643, 'n_estimators': 22, 'learning_rate': 0.05967077858339052}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2291078679995047
Fold 2 IBS: 0.21341140636860573
Fold 3 IBS: 0.23192802809417654
Fold 4 IBS: 0.23402147506607907
Fold 5 IBS: 0.21317832146276416
[I 2024-04-15 18:52:05,553] Trial 33 finished with value: 0.22432941979822604 and parameters: {'subsample': 0.7794604399156984, 'dropout_rate': 0.9504625799325089, 'n_estimators': 13, 'learning_rate': 0.06055914650999865}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.25430560739242225
Fold 2 IBS: 0.2284133753114856
Fold 3 IBS: 0.3090625406037944
Fold 4 IBS: 0.2732154551860483
Fold 5 IBS: 0.2621904177585131
[I 2024-04-15 18:52:05,930] Trial 34 finished with value: 0.2654374792504527 and parameters: {'subsample': 0.6982462018109117, 'dropout_rate': 0.8639367030524437, 'n_estimators': 84, 'learning_rate': 0.0649821776613948}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21768018948179807
Fold 2 IBS: 0.20112990863142238
Fold 3 IBS: 0.2547679190320581
Fold 4 IBS: 0.2359778319362916
Fold 5 IBS: 0.21519795791889573
[I 2024-04-15 18:52:06,121] Trial 35 finished with value: 0.22495076140009318 and parameters: {'subsample': 0.7880243815860887, 'dropout_rate': 0.999943957221368, 'n_estimators': 27, 'learning_rate': 0.07675979779302834}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2977141155977322
Fold 2 IBS: 0.24775644913124664
Fold 3 IBS: 0.3306511114108861
Fold 4 IBS: 0.2923888275212842
Fold 5 IBS: 0.28032513089432576
[I 2024-04-15 18:52:06,623] Trial 36 finished with value: 0.28976712691109496 and parameters: {'subsample': 0.9189450187030327, 'dropout_rate': 0.8476672993402941, 'n_estimators': 129, 'learning_rate': 0.05573723451692966}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.3811658445880461
Fold 2 IBS: 0.2758127038773145
Fold 3 IBS: 0.36709218055056614
Fold 4 IBS: 0.30550730104285034
Fold 5 IBS: 0.3067044688141932
[I 2024-04-15 18:52:07,272] Trial 37 finished with value: 0.3272564997745941 and parameters: {'subsample': 0.739264920272442, 'dropout_rate': 0.8927843858195293, 'n_estimators': 169, 'learning_rate': 0.06888028701406422}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2264971103333118
Fold 2 IBS: 0.20135233326855248
Fold 3 IBS: 0.2526241904073602
Fold 4 IBS: 0.22761235729593224
Fold 5 IBS: 0.21391136761511492
[I 2024-04-15 18:52:07,467] Trial 38 finished with value: 0.22439947178405434 and parameters: {'subsample': 0.9323458933659868, 'dropout_rate': 0.13272164755980653, 'n_estimators': 28, 'learning_rate': 0.0802388198308747}. Best is trial 30 with value: 0.22105020743663645.

Fold 1 IBS: 0.22935008117918856
Fold 2 IBS: 0.21153618549256686
Fold 3 IBS: 0.29072451950301204
Fold 4 IBS: 0.2586656669929489
Fold 5 IBS: 0.24321840787686647
[I 2024-04-15 18:52:07,797] Trial 39 finished with value: 0.24669897220891657 and parameters: {'subsample': 0.7076071631229807, 'dropout_rate': 0.36113352605756727, 'n_estimators': 75, 'learning_rate': 0.05598015324329953}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.4295827306814518
Fold 2 IBS: 0.33729766730917193
Fold 3 IBS: 0.38924638966253877
Fold 4 IBS: 0.31325291352447
Fold 5 IBS: 0.32175848063875884
[I 2024-04-15 18:52:11,340] Trial 40 finished with value: 0.35822763636327826 and parameters: {'subsample': 0.8123581601061346, 'dropout_rate': 0.27073406810212547, 'n_estimators': 434, 'learning_rate': 0.050770250632636425}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21843232747192648
Fold 2 IBS: 0.20124696623375102
Fold 3 IBS: 0.26589789731233937
Fold 4 IBS: 0.23953030936979589
Fold 5 IBS: 0.22339485398021788
[I 2024-04-15 18:52:11,602] Trial 41 finished with value: 0.22970047087360612 and parameters: {'subsample': 0.7485948672215855, 'dropout_rate': 0.827821271771765, 'n_estimators': 44, 'learning_rate': 0.06100155441044479}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.24545977554153506
Fold 2 IBS: 0.2302404349481251
Fold 3 IBS: 0.228814223366646
Fold 4 IBS: 0.24097498117887786
Fold 5 IBS: 0.22762304438597
[I 2024-04-15 18:52:11,757] Trial 42 finished with value: 0.2346224918842308 and parameters: {'subsample': 0.6600001822368337, 'dropout_rate': 0.7512215971522175, 'n_estimators': 1, 'learning_rate': 0.06911254892370094}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2177286772534359
Fold 2 IBS: 0.20073314902484793
Fold 3 IBS: 0.2599125036038046
Fold 4 IBS: 0.23844492228389882
Fold 5 IBS: 0.21818700490217124
[I 2024-04-15 18:52:12,006] Trial 43 finished with value: 0.2270012514136317 and parameters: {'subsample': 0.8163078290274218, 'dropout_rate': 0.939553917830419, 'n_estimators': 49, 'learning_rate': 0.047734596204521335}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.23079869739063893
Fold 2 IBS: 0.21524619860909036
Fold 3 IBS: 0.23135881430740626
Fold 4 IBS: 0.23215245196525136
Fold 5 IBS: 0.21397390753677142
[I 2024-04-15 18:52:12,235] Trial 44 finished with value: 0.22470601396183168 and parameters: {'subsample': 0.5793955243729101, 'dropout_rate': 0.8902546449865933, 'n_estimators': 25, 'learning_rate': 0.02941573453153995}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.23463938291343403
Fold 2 IBS: 0.21378641058446565
Fold 3 IBS: 0.2936585740423683
Fold 4 IBS: 0.2623275744743812
Fold 5 IBS: 0.24681085413233397
[I 2024-04-15 18:52:12,770] Trial 45 finished with value: 0.2502445592293966 and parameters: {'subsample': 0.9427673116011092, 'dropout_rate': 0.817057053206203, 'n_estimators': 116, 'learning_rate': 0.0370342562578839}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.40086920822949945
Fold 2 IBS: 0.28091448436473726
Fold 3 IBS: 0.3720791128836979
Fold 4 IBS: 0.307109292579857
Fold 5 IBS: 0.308674520431342
[I 2024-04-15 18:52:13,592] Trial 46 finished with value: 0.3339293236978267 and parameters: {'subsample': 0.8772929906687839, 'dropout_rate': 0.9519780159701515, 'n_estimators': 194, 'learning_rate': 0.06489928133343151}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.232466351187792
Fold 2 IBS: 0.21715839919246133
Fold 3 IBS: 0.23045465132815326
Fold 4 IBS: 0.23505329955231874
Fold 5 IBS: 0.21545322244115622
[I 2024-04-15 18:52:13,949] Trial 47 finished with value: 0.22611718474037631 and parameters: {'subsample': 0.7741938008338972, 'dropout_rate': 0.7343720546814592, 'n_estimators': 75, 'learning_rate': 0.008209618821055878}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.21928772309722075
Fold 2 IBS: 0.20290025316680066
Fold 3 IBS: 0.24625852536625306
Fold 4 IBS: 0.22756184240178828
Fold 5 IBS: 0.21155714687356678
[I 2024-04-15 18:52:14,209] Trial 48 finished with value: 0.2215130981811259 and parameters: {'subsample': 0.6902001509321368, 'dropout_rate': 0.6604314111556595, 'n_estimators': 33, 'learning_rate': 0.052217916997002886}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22864268464482704
Fold 2 IBS: 0.20618701072642076
Fold 3 IBS: 0.23974348161514325
Fold 4 IBS: 0.22902300059149802
Fold 5 IBS: 0.21031693369470345
[I 2024-04-15 18:52:14,438] Trial 49 finished with value: 0.22278262225451853 and parameters: {'subsample': 0.5246256412363035, 'dropout_rate': 0.444654827003804, 'n_estimators': 26, 'learning_rate': 0.05201530493205449}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.4256560799384403
Fold 2 IBS: 0.3151221688354275
Fold 3 IBS: 0.3860413488667417
Fold 4 IBS: 0.3089178353626252
Fold 5 IBS: 0.317098910141038
[I 2024-04-15 18:52:16,888] Trial 50 finished with value: 0.3505672686288545 and parameters: {'subsample': 0.6713843248996562, 'dropout_rate': 0.6491522181398676, 'n_estimators': 379, 'learning_rate': 0.04745080772448178}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2192431668518127
Fold 2 IBS: 0.20189468163918148
Fold 3 IBS: 0.26982441152732806
Fold 4 IBS: 0.23613925370649705
Fold 5 IBS: 0.2256653604972261
[I 2024-04-15 18:52:17,137] Trial 51 finished with value: 0.23055337484440908 and parameters: {'subsample': 0.7172193716930169, 'dropout_rate': 0.6709427179664875, 'n_estimators': 48, 'learning_rate': 0.05997708252875927}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.2410305123087452
Fold 2 IBS: 0.2195671978090868
Fold 3 IBS: 0.2993407314297869
Fold 4 IBS: 0.26849472696514515
Fold 5 IBS: 0.25209231830194867
[I 2024-04-15 18:52:17,550] Trial 52 finished with value: 0.25610509736294257 and parameters: {'subsample': 0.8289606252433972, 'dropout_rate': 0.7512811922273754, 'n_estimators': 84, 'learning_rate': 0.05632002652421048}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.24612203266949853
Fold 2 IBS: 0.23087751124769623
Fold 3 IBS: 0.22885621209387846
Fold 4 IBS: 0.24139543456033377
Fold 5 IBS: 0.22821141204302334
[I 2024-04-15 18:52:17,715] Trial 53 finished with value: 0.23509252052288607 and parameters: {'subsample': 0.9644210790375523, 'dropout_rate': 0.6894833612317082, 'n_estimators': 1, 'learning_rate': 0.04185368229372562}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22818239059764914
Fold 2 IBS: 0.20984620997622416
Fold 3 IBS: 0.2867822539050355
Fold 4 IBS: 0.25462805104656905
Fold 5 IBS: 0.24007539469996075
[I 2024-04-15 18:52:18,021] Trial 54 finished with value: 0.2439028600450877 and parameters: {'subsample': 0.7754401293458196, 'dropout_rate': 0.8581787213295002, 'n_estimators': 59, 'learning_rate': 0.06494770180873123}. Best is trial 30 with value: 0.22105020743663645.
Fold 1 IBS: 0.22257503395436767
Fold 2 IBS: 0.20677739071945617
Fold 3 IBS: 0.23796734142055684
Fold 4 IBS: 0.22680201011024181
Fold 5 IBS: 0.2103640282316372
[I 2024-04-15 18:52:18,268] Trial 55 finished with value: 0.22089716088725195 and parameters: {'subsample': 0.6046650456267857, 'dropout_rate': 0.8107431542120329, 'n_estimators': 36, 'learning_rate': 0.035281924830240646}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2341460554286086
Fold 2 IBS: 0.21898083332700824
Fold 3 IBS: 0.22984714409801585
Fold 4 IBS: 0.23206905279076265
Fold 5 IBS: 0.21732092597900418
[I 2024-04-15 18:52:18,465] Trial 56 finished with value: 0.2264728023246799 and parameters: {'subsample': 0.6148929150329211, 'dropout_rate': 0.9112147525268226, 'n_estimators': 16, 'learning_rate': 0.033986625231595756}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.28505309347602925
Fold 2 IBS: 0.24760499505067732
Fold 3 IBS: 0.3301622822216491
Fold 4 IBS: 0.2894327690728538
Fold 5 IBS: 0.28019979914084864
[I 2024-04-15 18:52:20,106] Trial 57 finished with value: 0.28649058779241166 and parameters: {'subsample': 0.6825327446543555, 'dropout_rate': 0.5208726510676236, 'n_estimators': 282, 'learning_rate': 0.025565265724993874}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2214507245251379
Fold 2 IBS: 0.20506568938296435
Fold 3 IBS: 0.24075353489551313
Fold 4 IBS: 0.2288359521484131

Fold 5 IBS: 0.2104012829571286
[I 2024-04-15 18:52:20,336] Trial 58 finished with value: 0.22130143678183142 and parameters: {'subsample': 0.5793765216559574, 'dropout_rate': 0.869359581862351, 'n_estimators': 38, 'learning_rate': 0.03754893539001649}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22332388143407295
Fold 2 IBS: 0.20363163283585628
Fold 3 IBS: 0.24449748198927226
Fold 4 IBS: 0.22907918428885007
Fold 5 IBS: 0.21077017722074096
[I 2024-04-15 18:52:20,572] Trial 59 finished with value: 0.22226047155375853 and parameters: {'subsample': 0.4535266512643318, 'dropout_rate': 0.9611194785854935, 'n_estimators': 40, 'learning_rate': 0.038908657923000085}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2426474010909224
Fold 2 IBS: 0.22436959888835237
Fold 3 IBS: 0.3051332800511575
Fold 4 IBS: 0.26525378607334044
Fold 5 IBS: 0.25799073524428723
[I 2024-04-15 18:52:21,140] Trial 60 finished with value: 0.25907896026961197 and parameters: {'subsample': 0.5592773031153138, 'dropout_rate': 0.805892721742462, 'n_estimators': 118, 'learning_rate': 0.04300303133619651}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23322262418938672
Fold 2 IBS: 0.21780502341126942
Fold 3 IBS: 0.23021413524283157
Fold 4 IBS: 0.2317083947092564
Fold 5 IBS: 0.21648635752240689
[I 2024-04-15 18:52:21,336] Trial 61 finished with value: 0.22588730701503024 and parameters: {'subsample': 0.6197162239153043, 'dropout_rate': 0.897755135761733, 'n_estimators': 18, 'learning_rate': 0.033093783201145574}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22321650757486647
Fold 2 IBS: 0.2028003645937837
Fold 3 IBS: 0.24711601825710883
Fold 4 IBS: 0.22957583498652415
Fold 5 IBS: 0.2113955496138467
[I 2024-04-15 18:52:21,584] Trial 62 finished with value: 0.22282085500522597 and parameters: {'subsample': 0.5148326884231843, 'dropout_rate': 0.8753399354683069, 'n_estimators': 35, 'learning_rate': 0.048706108725934165}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21864755972668926
Fold 2 IBS: 0.2016225251367432
Fold 3 IBS: 0.2509189112353247
Fold 4 IBS: 0.23100076284482912
Fold 5 IBS: 0.2136479732966466
[I 2024-04-15 18:52:21,924] Trial 63 finished with value: 0.22316754644804657 and parameters: {'subsample': 0.6487668076796561, 'dropout_rate': 0.8232768248813066, 'n_estimators': 70, 'learning_rate': 0.027357634359371004}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22030711444046622
Fold 2 IBS: 0.2028872132298813
Fold 3 IBS: 0.2723990807024937
Fold 4 IBS: 0.23234983693422795
Fold 5 IBS: 0.22892547385548054
[I 2024-04-15 18:52:22,221] Trial 64 finished with value: 0.23137374383250994 and parameters: {'subsample': 0.5975058672190523, 'dropout_rate': 0.7823037659988256, 'n_estimators': 56, 'learning_rate': 0.05410979520775479}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2246485985201335
Fold 2 IBS: 0.2058825400782259
Fold 3 IBS: 0.2824399132357561
Fold 4 IBS: 0.23828761615189975
Fold 5 IBS: 0.23650207193611295
[I 2024-04-15 18:52:22,585] Trial 65 finished with value: 0.23755214798442564 and parameters: {'subsample': 0.45888887591206007, 'dropout_rate': 0.9190970086086071, 'n_estimators': 90, 'learning_rate': 0.038689837069848146}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23273965002953717
Fold 2 IBS: 0.21725871845559455
Fold 3 IBS: 0.23057552835557654
Fold 4 IBS: 0.2346983844695266
Fold 5 IBS: 0.21547730446319574
[I 2024-04-15 18:52:22,755] Trial 66 finished with value: 0.22614991715468613 and parameters: {'subsample': 0.7326959870204457, 'dropout_rate': 0.8441970079444766, 'n_estimators': 14, 'learning_rate': 0.04501243637315829}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2531769237494069
Fold 2 IBS: 0.23296920068260224
Fold 3 IBS: 0.3140245626406833
Fold 4 IBS: 0.2699122978070452
Fold 5 IBS: 0.26615389994000355
[I 2024-04-15 18:52:23,181] Trial 67 finished with value: 0.2672473769639482 and parameters: {'subsample': 0.5471917580520336, 'dropout_rate': 0.9769821442118126, 'n_estimators': 99, 'learning_rate': 0.057929390501509886}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2182645606215572
Fold 2 IBS: 0.20076151212811258
Fold 3 IBS: 0.26082805345729165
Fold 4 IBS: 0.23236316881117391
Fold 5 IBS: 0.21885563811795794
[I 2024-04-15 18:52:23,412] Trial 68 finished with value: 0.22621458662721866 and parameters: {'subsample': 0.6946889669430717, 'dropout_rate': 0.583662202262188, 'n_estimators': 34, 'learning_rate': 0.07261636225834231}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2205185249303166
Fold 2 IBS: 0.2039865579628996
Fold 3 IBS: 0.24377138068999496
Fold 4 IBS: 0.2298605380624899
Fold 5 IBS: 0.2109444943185319
[I 2024-04-15 18:52:23,792] Trial 69 finished with value: 0.2218162991928466 and parameters: {'subsample': 0.6454763362460977, 'dropout_rate': 0.720522833073103, 'n_estimators': 72, 'learning_rate': 0.021510860950056627}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22195649096735395
Fold 2 IBS: 0.2057796473545906
Fold 3 IBS: 0.24047621118241896
Fold 4 IBS: 0.22883745019976204
Fold 5 IBS: 0.21040296604701988
[I 2024-04-15 18:52:24,134] Trial 70 finished with value: 0.22149055315022909 and parameters: {'subsample': 0.5867802742615672, 'dropout_rate': 0.7164929446280183, 'n_estimators': 74, 'learning_rate': 0.01836623067581729}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2224574115110653
Fold 2 IBS: 0.20624684542359964
Fold 3 IBS: 0.23963014108905373
Fold 4 IBS: 0.22900785656242212
Fold 5 IBS: 0.210325868066254
[I 2024-04-15 18:52:24,490] Trial 71 finished with value: 0.22153362453047895 and parameters: {'subsample': 0.5943758778419203, 'dropout_rate': 0.7178705789257822, 'n_estimators': 75, 'learning_rate': 0.01747576819572829}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21907570074462793
Fold 2 IBS: 0.20169546621039425
Fold 3 IBS: 0.25033163822633475
Fold 4 IBS: 0.23075068452470274
Fold 5 IBS: 0.213686630109571
[I 2024-04-15 18:52:24,901] Trial 72 finished with value: 0.2231080239631261 and parameters: {'subsample': 0.5766850407934205, 'dropout_rate': 0.6867676859247152, 'n_estimators': 90, 'learning_rate': 0.02089435843239119}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21942878302413968
Fold 2 IBS: 0.20183778716815864
Fold 3 IBS: 0.2501366496560795
Fold 4 IBS: 0.2315135061719935
Fold 5 IBS: 0.21360678712048178
[I 2024-04-15 18:52:25,565] Trial 73 finished with value: 0.22330470262817062 and parameters: {'subsample': 0.6350981564062819, 'dropout_rate': 0.724091326177061, 'n_estimators': 144, 'learning_rate': 0.013043210125809303}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.23786360690225444
Fold 2 IBS: 0.22245402837048767
Fold 3 IBS: 0.22903028955483665
Fold 4 IBS: 0.23621957174006056
Fold 5 IBS: 0.21976820761106206
[I 2024-04-15 18:52:25,916] Trial 74 finished with value: 0.22906714083574026 and parameters: {'subsample': 0.601523470567797, 'dropout_rate': 0.6566427706952908, 'n_estimators': 74, 'learning_rate': 0.005080429459703627}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2214943627310797
Fold 2 IBS: 0.20164308069300232
Fold 3 IBS: 0.25169555993234316
Fold 4 IBS: 0.22841371586916473
Fold 5 IBS: 0.21416681676848298
[I 2024-04-15 18:52:26,392] Trial 75 finished with value: 0.22348270719881458 and parameters: {'subsample': 0.49319069081038364, 'dropout_rate': 0.7076570957071591, 'n_estimators': 105, 'learning_rate': 0.01824490640855918}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.2328946499056936
Fold 2 IBS: 0.2170979257337216
Fold 3 IBS: 0.23040550426683937
Fold 4 IBS: 0.2332389132664599
Fold 5 IBS: 0.2156801492109445
[I 2024-04-15 18:52:26,658] Trial 76 finished with value: 0.2258634284767318 and parameters: {'subsample': 0.6388046490330901, 'dropout_rate': 0.618911653541915, 'n_estimators': 42, 'learning_rate': 0.014880869357715765}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22462298117263793
Fold 2 IBS: 0.2073982536472491
Fold 3 IBS: 0.28361457332876805
Fold 4 IBS: 0.24675247717794
Fold 5 IBS: 0.2381675349082399
[I 2024-04-15 18:52:27,517] Trial 77 finished with value: 0.240111164046967 and parameters: {'subsample': 0.541487090871485, 'dropout_rate': 0.7704979082473631, 'n_estimators': 165, 'learning_rate': 0.02189762732192369}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22365763185049595

Fold 2 IBS: 0.20591143440013582
Fold 3 IBS: 0.280976248290565
Fold 4 IBS: 0.24848562445786387
Fold 5 IBS: 0.23615081501710733
[I 2024-04-15 18:52:28,090] Trial 78 finished with value: 0.2390363508032336 and parameters: {'subsample': 0.6733814576309736, 'dropout_rate': 0.7358591929789065, 'n_estimators': 128, 'learning_rate': 0.02725879214599771}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22811684389438022
Fold 2 IBS: 0.21004117151133037
Fold 3 IBS: 0.23552715888942047
Fold 4 IBS: 0.22642754442179203
Fold 5 IBS: 0.2109726578133541
[I 2024-04-15 18:52:28,432] Trial 79 finished with value: 0.22221707530605544 and parameters: {'subsample': 0.4590324206086437, 'dropout_rate': 0.5730916522393441, 'n_estimators': 62, 'learning_rate': 0.016584715438210443}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.21914807252926094
Fold 2 IBS: 0.20152400712862856
Fold 3 IBS: 0.2680973864145784
Fold 4 IBS: 0.2372703504251833
Fold 5 IBS: 0.22464173105960364
[I 2024-04-15 18:52:30,265] Trial 80 finished with value: 0.23013630951145098 and parameters: {'subsample': 0.5700298173994884, 'dropout_rate': 0.7963649913222645, 'n_estimators': 327, 'learning_rate': 0.008427919156244693}. Best is trial 55 with value: 0.22089716088725195.
Fold 1 IBS: 0.22077348750169198
Fold 2 IBS: 0.20465087956377137
Fold 3 IBS: 0.24199806863414064
Fold 4 IBS: 0.22642953767379848
Fold 5 IBS: 0.2105996070892919
[I 2024-04-15 18:52:30,537] Trial 81 finished with value: 0.2208903160925389 and parameters: {'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2181890289575755
Fold 2 IBS: 0.20085037679728737
Fold 3 IBS: 0.2628056745478857
Fold 4 IBS: 0.2329689235642938
Fold 5 IBS: 0.22111819009301079
[I 2024-04-15 18:52:30,907] Trial 82 finished with value: 0.22718643879201061 and parameters: {'subsample': 0.591713415609599, 'dropout_rate': 0.8271461226738561, 'n_estimators': 81, 'learning_rate': 0.03066131851432999}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.23796348921996144
Fold 2 IBS: 0.22231306926597583
Fold 3 IBS: 0.22917826331147176
Fold 4 IBS: 0.23592312507334565
Fold 5 IBS: 0.2199694633866284
[I 2024-04-15 18:52:31,101] Trial 83 finished with value: 0.22906948205147662 and parameters: {'subsample': 0.5104385117001161, 'dropout_rate': 0.8678063293886515, 'n_estimators': 11, 'learning_rate': 0.03618620932286212}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22381030523700307
Fold 2 IBS: 0.20720978403751017
Fold 3 IBS: 0.237911829205767
Fold 4 IBS: 0.22792947965938568
Fold 5 IBS: 0.2104040102787604
[I 2024-04-15 18:52:31,389] Trial 84 finished with value: 0.22145308168368527 and parameters: {'subsample': 0.6572552519386883, 'dropout_rate': 0.6327349414747185, 'n_estimators': 44, 'learning_rate': 0.028170869846693994}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21850846200789092
Fold 2 IBS: 0.20113172065685006
Fold 3 IBS: 0.25393815497147415
Fold 4 IBS: 0.2312989153770497
Fold 5 IBS: 0.2150707094266202
[I 2024-04-15 18:52:31,728] Trial 85 finished with value: 0.22398959248797704 and parameters: {'subsample': 0.6586093577814823, 'dropout_rate': 0.6202710354222771, 'n_estimators': 64, 'learning_rate': 0.032423376680946865}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22379912941339913
Fold 2 IBS: 0.2076089237823684
Fold 3 IBS: 0.23713925842702915
Fold 4 IBS: 0.22881038613184393
Fold 5 IBS: 0.21049278014865697
[I 2024-04-15 18:52:32,007] Trial 86 finished with value: 0.22157009558065952 and parameters: {'subsample': 0.6201193355845069, 'dropout_rate': 0.6727758765974591, 'n_estimators': 44, 'learning_rate': 0.027328093031043253}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2227310338564416
Fold 2 IBS: 0.2064729770871324
Fold 3 IBS: 0.2387097684726459
Fold 4 IBS: 0.22860683668930395
Fold 5 IBS: 0.21031777945117824
[I 2024-04-15 18:52:32,321] Trial 87 finished with value: 0.22136767911134042 and parameters: {'subsample': 0.6137923043677187, 'dropout_rate': 0.6578608395909092, 'n_estimators': 46, 'learning_rate': 0.028228844589449218}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.3155249490793188
Fold 2 IBS: 0.2640250973483872
Fold 3 IBS: 0.35150740047903567
Fold 4 IBS: 0.29465926108505686
Fold 5 IBS: 0.29664399307292966
[I 2024-04-15 18:52:33,514] Trial 88 finished with value: 0.30447214021294566 and parameters: {'subsample': 0.5563453956745567, 'dropout_rate': 0.635509892730024, 'n_estimators': 227, 'learning_rate': 0.041042651352224235}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21882804040039408
Fold 2 IBS: 0.2021257239375794
Fold 3 IBS: 0.2488925553100117
Fold 4 IBS: 0.2299136957400707
Fold 5 IBS: 0.21258997349908584
[I 2024-04-15 18:52:33,824] Trial 89 finished with value: 0.22246999777742835 and parameters: {'subsample': 0.7174443932842023, 'dropout_rate': 0.5932177411632202, 'n_estimators': 52, 'learning_rate': 0.03497836260796343}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22508455000645972
Fold 2 IBS: 0.2093506081973267
Fold 3 IBS: 0.23545916578671205
Fold 4 IBS: 0.2296620341827449
Fold 5 IBS: 0.210956430784988
[I 2024-04-15 18:52:34,072] Trial 90 finished with value: 0.22210255779164628 and parameters: {'subsample': 0.6885792506232654, 'dropout_rate': 0.5581493449312643, 'n_estimators': 36, 'learning_rate': 0.030149768812526692}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22350570792154217
Fold 2 IBS: 0.20710675637673007
Fold 3 IBS: 0.2377890064398362
Fold 4 IBS: 0.22866334718906384
Fold 5 IBS: 0.2103837931115841
[I 2024-04-15 18:52:34,325] Trial 91 finished with value: 0.2214897222077513 and parameters: {'subsample': 0.6252518157333167, 'dropout_rate': 0.6768103250965768, 'n_estimators': 45, 'learning_rate': 0.027532898640914117}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2413589052700756
Fold 2 IBS: 0.22663761168748628
Fold 3 IBS: 0.22866863477272367
Fold 4 IBS: 0.23745690563602184
Fold 5 IBS: 0.2237298644365178
[I 2024-04-15 18:52:34,483] Trial 92 finished with value: 0.23157038436056504 and parameters: {'subsample': 0.6080039360699264, 'dropout_rate': 0.6989466017172343, 'n_estimators': 9, 'learning_rate': 0.024367473936345387}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22723131937890337
Fold 2 IBS: 0.2113640306874193
Fold 3 IBS: 0.23373445637933926
Fold 4 IBS: 0.22846157368512096
Fold 5 IBS: 0.21172162311351986
[I 2024-04-15 18:52:34,695] Trial 93 finished with value: 0.22250260064886057 and parameters: {'subsample': 0.5869718752556726, 'dropout_rate': 0.515780662916985, 'n_estimators': 26, 'learning_rate': 0.03696817721869061}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22073632727273912
Fold 2 IBS: 0.20388324986594278
Fold 3 IBS: 0.2433710156727303
Fold 4 IBS: 0.22887009757913981
Fold 5 IBS: 0.2108449986568362
[I 2024-04-15 18:52:34,962] Trial 94 finished with value: 0.22154113780947765 and parameters: {'subsample': 0.632517730042522, 'dropout_rate': 0.6542832786756084, 'n_estimators': 53, 'learning_rate': 0.02920357901679212}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.22798047230982416
Fold 2 IBS: 0.21148788850219047
Fold 3 IBS: 0.23356421385825749
Fold 4 IBS: 0.23007244409198496
Fold 5 IBS: 0.2120154922159216
[I 2024-04-15 18:52:35,228] Trial 95 finished with value: 0.22302410219563576 and parameters: {'subsample': 0.6639608403709552, 'dropout_rate': 0.7566876692486192, 'n_estimators': 36, 'learning_rate': 0.026071370321176603}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2179012967955125
Fold 2 IBS: 0.20078159037918683
Fold 3 IBS: 0.26110289322293423
Fold 4 IBS: 0.23412808505560326
Fold 5 IBS: 0.21973897733190245
[I 2024-04-15 18:52:35,545] Trial 96 finished with value: 0.22673056855702786 and parameters: {'subsample': 0.7054650333977128, 'dropout_rate': 0.6262161752789943, 'n_estimators': 61, 'learning_rate': 0.03998698220337849}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21963880593620028
Fold 2 IBS: 0.20092268436766023
Fold 3 IBS: 0.2648475542088438
Fold 4 IBS: 0.2331055121729352

Fold 5 IBS: 0.22220093036998428
[I 2024-04-15 18:52:35,920] Trial 97 finished with value: 0.22814309741112476 and parameters: {'subsample': 0.531829760385333, 'dropout_rate': 0.6847533776104763, 'n_estimators': 79, 'learning_rate': 0.03223905987322316}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.2466414230044532
Fold 2 IBS: 0.23146700010719856
Fold 3 IBS: 0.2289119634694628
Fold 4 IBS: 0.24164291053866815
Fold 5 IBS: 0.2288108925224838
[I 2024-04-15 18:52:36,104] Trial 98 finished with value: 0.2354948379284533 and parameters: {'subsample': 0.5618605706633095, 'dropout_rate': 0.2002801186536965, 'n_estimators': 1, 'learning_rate': 0.022985459193691663}. Best is trial 81 with value: 0.2208903160925389.
Fold 1 IBS: 0.21844021664292554
Fold 2 IBS: 0.2014998540928507
Fold 3 IBS: 0.25108301890771456
Fold 4 IBS: 0.2341234904146111
Fold 5 IBS: 0.21405157380858064
[I 2024-04-15 18:52:36,520] Trial 99 finished with value: 0.2238396307733365 and parameters: {'subsample': 0.7589069007873921, 'dropout_rate': 0.8823172392191718, 'n_estimators': 97, 'learning_rate': 0.01992182696731529}. Best is trial 81 with value: 0.2208903160925389.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2208903160925389], datetime_start=datetime.datetime(2024, 4, 15, 18, 52, 30, 267737), datetime_complete=datetime.datetime(2024, 4, 15, 18, 52, 30, 536771), params={'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.5967091670188371, 'dropout_rate': 0.8767395889398294, 'n_estimators': 48, 'learning_rate': 0.030725485144314495}


* Best Score for IBS:
 0.2208903160925389

In [156]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [157]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.67
train_ibs:  0.221

#### Test

In [158]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [159]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6979039748471498,
                                              learning_rate=0.030307532796347948,
                                              n_estimators=1, random_state=123,
                                              subsample=0.19718036296309377)

C-index score: 0.521

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8767395889398294,
                                              learning_rate=0.030725485144314495,
                                              n_estimators=48, random_state=123,
                                              subsample=0.5967091670188371)

IBS: 0.239

In [160]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [161]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.791   1.0
Randomsurvivalforest             0.782   2.0
GradientBoosting                 0.729   3.0
CoxElastic                       0.677   4.0
CoxPH                            0.675   5.0
CoxLasso                         0.673   6.0
ComponentwiseGradientBoosting    0.670   7.0
CoxRidge                         0.649   8.0

In [162]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.201   1.0
ExtraSurvivalTrees             0.206   2.0
CoxLasso                       0.220   3.5
CoxElastic                     0.220   3.5
CoxPH                          0.221   5.5
ComponentwiseGradientBoosting  0.221   5.5
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [163]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
CoxRidge                         0.534   1.0
ComponentwiseGradientBoosting    0.521   2.0
Randomsurvivalforest             0.512   3.0
GradientBoosting                 0.499   4.0
CoxPH                            0.498   5.0
CoxLasso                         0.497   6.5
CoxElastic                       0.497   6.5
ExtraSurvivalTrees               0.485   8.0

In [164]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ComponentwiseGradientBoosting  0.239   3.0
ExtraSurvivalTrees             0.254   4.0
Randomsurvivalforest           0.256   5.0
CoxLasso                       0.279   6.0
CoxElastic                     0.280   7.0
CoxPH                          0.281   8.0

In [165]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/yeojohnson/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_yeojohnson_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [166]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-15