In [1]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import PowerTransformer

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [14]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Yeo-Johnson Transformation

In [16]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [17]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [18]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,1.124852,0.125487,0.072022,-0.784694
1,0.161153,-0.358143,-1.421627,-0.784694
2,-1.401990,0.250624,0.444135,0.236612
3,-0.012817,-0.946686,-1.314128,-0.784694
4,-1.982774,1.502519,-0.468644,1.784568
...,...,...,...,...
134,0.823106,-0.175124,-0.601731,-0.784694
135,0.532655,1.517088,0.002519,-0.784694
136,-0.421265,-0.622476,-0.316986,-0.784694
137,0.552472,1.639161,0.314722,-0.784694
138,0.528431,1.187641,-0.839594,-0.784694

In [19]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [20]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,-0.228627,0.816980,0.557388,0.033184
1,-0.204032,-1.995319,0.050605,1.682719
2,-0.770221,-0.736265,0.221607,0.693043
3,-1.281223,-1.151240,0.329735,-0.784694
4,-0.689674,-0.085023,0.794695,-0.784694
...,...,...,...,...
94,-0.180591,0.304443,-0.506427,-0.784694
95,-0.674760,-0.848664,0.615633,-0.784694
96,-0.513250,-1.682811,0.580714,-0.784694
97,0.600661,-0.466149,0.254712,-0.784694
98,-0.166374,-1.007217,-0.320388,-0.784694

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [21]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:51:03,448] A new study created in memory with name: no-name-9aa7761f-bdac-4252-b3ab-0d271a65f648

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318

[I 2024-04-15 13:51:08,541] A new study created in memory with name: no-name-238395e6-6ee1-4fcf-921f-854ce4e14b71

Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:08,526] Trial 0 finished with value: 0.6859016206049102 and parameters: {}. Best is trial 0 with value: 0.6859016206049102.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6859016206049102], datetime_start=datetime.datetime(2024, 4, 15, 13, 51, 3, 520655), datetime_complete=datetime.datetime(2024, 4, 15, 13, 51, 8, 526528), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6859016206049102

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24820982416811707
Fold 2 IBS: 0.19413929368245514
Fold 3 IBS: 0.21817979235636706
Fold 4 IBS: 0.19747087662809215
Fold 5 IBS: 0.20028642283459286
[I 2024-04-15 13:51:08,829] Trial 0 finished with value: 0.21165724193392482 and parameters: {}. Best is trial 0 with value: 0.21165724193392482.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21165724193392482], datetime_start=datetime.datetime(2024, 4, 15, 13, 51, 8, 613313), datetime_complete=datetime.datetime(2024, 4, 15, 13, 51, 8, 829612), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21165724193392482

In [22]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [23]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.686
train_ibs:  0.212

#### Test

In [24]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [25]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.524
IBS score: 0.292

In [26]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [27]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [28]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:51:09,051] A new study created in memory with name: no-name-6d9b7526-b008-468f-b50f-d86eaebb1445

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-15 13:51:09,403] A new study created in memory with name: no-name-9f2fc26d-3d8b-451b-be5e-0025fddb1747

Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6802575107296137
[I 2024-04-15 13:51:09,389] Trial 0 finished with value: 0.6592742098498834 and parameters: {}. Best is trial 0 with value: 0.6592742098498834.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6592742098498834], datetime_start=datetime.datetime(2024, 4, 15, 13, 51, 9, 135480), datetime_complete=datetime.datetime(2024, 4, 15, 13, 51, 9, 389072), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6592742098498834

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.247247092638399
Fold 2 IBS: 0.2320398751219593
Fold 3 IBS: 0.22898186742616655
Fold 4 IBS: 0.24197475878533212
Fold 5 IBS: 0.22939558471523763
[I 2024-04-15 13:51:09,614] Trial 0 finished with value: 0.2359278357374189 and parameters: {}. Best is trial 0 with value: 0.2359278357374189.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2359278357374189], datetime_start=datetime.datetime(2024, 4, 15, 13, 51, 9, 437856), datetime_complete=datetime.datetime(2024, 4, 15, 13, 51, 9, 614294), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2359278357374189

In [29]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [30]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.659
train_ibs:  0.236

#### Test

In [31]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [32]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [33]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [34]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:51:09,809] A new study created in memory with name: no-name-dee45ae6-6415-4abe-b979-3f84f2f44f37

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734

[I 2024-04-15 13:51:10,240] A new study created in memory with name: no-name-da890083-0514-4a0e-8598-0918dd7c9d5a

Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:10,233] Trial 0 finished with value: 0.6850505567751229 and parameters: {}. Best is trial 0 with value: 0.6850505567751229.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6850505567751229], datetime_start=datetime.datetime(2024, 4, 15, 13, 51, 9, 851776), datetime_complete=datetime.datetime(2024, 4, 15, 13, 51, 10, 233742), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6850505567751229

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24713202318432798
Fold 2 IBS: 0.19357514296294234
Fold 3 IBS: 0.21802432702977978
Fold 4 IBS: 0.1974050690265357
Fold 5 IBS: 0.2001300462867355
[I 2024-04-15 13:51:10,640] Trial 0 finished with value: 0.21125332169806427 and parameters: {}. Best is trial 0 with value: 0.21125332169806427.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21125332169806427], datetime_start=datetime.datetime(2024, 4, 15, 13, 51, 10, 267556), datetime_complete=datetime.datetime(2024, 4, 15, 13, 51, 10, 640199), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21125332169806427

In [35]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [36]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.685
train_ibs:  0.211

#### Test

In [37]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [38]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.523

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.29

In [39]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [40]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:51:10,876] A new study created in memory with name: no-name-6ebf34f3-17e8-45c3-b277-a3eaa53df025

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:11,262] Trial 0 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6850505567751229.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:11,685] Trial 1 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:12,098] Trial 2 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:12,510] Trial 3 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:12,842] Trial 4 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:13,209] Trial 5 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:13,572] Trial 6 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:13,979] Trial 7 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:14,334] Trial 8 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:14,638] Trial 9 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.6859016206049102.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:15,106] Trial 10 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:15,391] Trial 11 finished with value: 0.6552522060821804 and parameters: {'l1_ratio': 0.016444541243212374}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:15,938] Trial 12 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.0873928389796849}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:16,117] Trial 13 finished with value: 0.6544553933331765 and parameters: {'l1_ratio': 0.003240751291247554}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:16,531] Trial 14 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.14334023675256088}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:16,923] Trial 15 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.14686204034367636}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:17,307] Trial 16 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.29492929565472803}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:17,761] Trial 17 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.1278697437099071}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:18,127] Trial 18 finished with value: 0.6639473200436716 and parameters: {'l1_ratio': 0.06764452452390808}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:18,732] Trial 19 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:19,097] Trial 20 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.9172268540480069}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:19,481] Trial 21 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.16870552103067943}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:19,980] Trial 22 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.10290429070558606}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:20,323] Trial 23 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.3543524189329308}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318

Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:20,653] Trial 24 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.21623254971460304}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:21,299] Trial 25 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.0853699617771228}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:21,783] Trial 26 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.17284350892750144}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:22,195] Trial 27 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.3231390668536532}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:22,434] Trial 28 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.05006338150545889}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:22,803] Trial 29 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.5551663189851536}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:23,201] Trial 30 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.2052530265626114}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:23,499] Trial 31 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:23,909] Trial 32 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.11271530900654927}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:24,082] Trial 33 finished with value: 0.6552522060821804 and parameters: {'l1_ratio': 0.0062661184216923765}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:24,433] Trial 34 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.2816935819767384}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:24,803] Trial 35 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.2503833329651749}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:25,217] Trial 36 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.13597853931319773}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:25,584] Trial 37 finished with value: 0.6639473200436716 and parameters: {'l1_ratio': 0.07029520243320188}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:25,979] Trial 38 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.6666890374280088}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:26,321] Trial 39 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:26,698] Trial 40 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.3396351837644522}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:27,223] Trial 41 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.15059499069998564}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:27,714] Trial 42 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.20174720161408186}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:28,154] Trial 43 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.11692006402374093}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:28,454] Trial 44 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.04418503916867171}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:29,053] Trial 45 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.5582592206819572}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:29,576] Trial 46 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.8167652444349325}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:30,147] Trial 47 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.23971145636476637}. Best is trial 10 with value: 0.6866984333539141.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:31,101] Trial 48 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.28913086771769636}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:31,785] Trial 49 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.3881372941956815}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:31,955] Trial 50 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.02973857144887264}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:32,429] Trial 51 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.09341981770248678}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:32,983] Trial 52 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.11808598218536519}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:33,398] Trial 53 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.17866943309481953}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:33,809] Trial 54 finished with value: 0.6639473200436716 and parameters: {'l1_ratio': 0.07825083075748601}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:34,179] Trial 55 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.1365746259992281}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:34,492] Trial 56 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.04505307244004128}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:34,883] Trial 57 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.1975874823265805}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:35,145] Trial 58 finished with value: 0.6544553933331765 and parameters: {'l1_ratio': 0.003680241884233326}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:35,641] Trial 59 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.260736073675212}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:36,025] Trial 60 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.0995538393393992}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:36,427] Trial 61 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.08688366872297473}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:36,820] Trial 62 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.16468879508904338}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:37,134] Trial 63 finished with value: 0.6586241261273218 and parameters: {'l1_ratio': 0.05676125198151548}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:37,548] Trial 64 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.22554411409826314}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:38,019] Trial 65 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.13280784301151036}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:38,403] Trial 66 finished with value: 0.6639473200436716 and parameters: {'l1_ratio': 0.07983151805391166}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:38,727] Trial 67 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.18858124250968142}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:38,965] Trial 68 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.03726549416212274}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:39,502] Trial 69 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:39,989] Trial 70 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.6190167670320361}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:40,352] Trial 71 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.1647661632337235}. Best is trial 10 with value: 0.6866984333539141.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:40,744] Trial 72 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.10032054904299781}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:41,143] Trial 73 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.12420054405329062}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:41,558] Trial 74 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.21635329381620316}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:41,994] Trial 75 finished with value: 0.6639473200436716 and parameters: {'l1_ratio': 0.06774205064505716}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:42,249] Trial 76 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.025766413017043355}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:42,608] Trial 77 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.32126976245724526}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:42,995] Trial 78 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.15809014479709957}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:43,368] Trial 79 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:43,701] Trial 80 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.27123201130079877}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:44,047] Trial 81 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.11005405567934316}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:44,423] Trial 82 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.117019910418831}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:44,834] Trial 83 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.18378856155589132}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:45,167] Trial 84 finished with value: 0.6639473200436716 and parameters: {'l1_ratio': 0.06738612489893264}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:45,389] Trial 85 finished with value: 0.6552522060821804 and parameters: {'l1_ratio': 0.0014101392479932279}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:45,798] Trial 86 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.14740443287333116}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:46,179] Trial 87 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.09412054537280083}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:46,550] Trial 88 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.2319989480545938}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:46,955] Trial 89 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.8683435408509753}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:47,179] Trial 90 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.04465422221678385}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:47,633] Trial 91 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.14051330070661444}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:47,986] Trial 92 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.12100302187202937}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:48,404] Trial 93 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.2036782206232114}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:48,785] Trial 94 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.16829739832706325}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:49,185] Trial 95 finished with value: 0.6866984333539141 and parameters: {'l1_ratio': 0.08808773250101792}. Best is trial 10 with value: 0.6866984333539141.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:49,543] Trial 96 finished with value: 0.6850505567751229 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:49,916] Trial 97 finished with value: 0.6859016206049102 and parameters: {'l1_ratio': 0.4965881146918674}. Best is trial 10 with value: 0.6866984333539141.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:51:50,180] Trial 98 finished with value: 0.6586241261273218 and parameters: {'l1_ratio': 0.06380596279297047}. Best is trial 10 with value: 0.6866984333539141.

[I 2024-04-15 13:51:50,442] A new study created in memory with name: no-name-10a67573-b430-440f-b079-70324040bd0e

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 13:51:50,424] Trial 99 finished with value: 0.6560490188311844 and parameters: {'l1_ratio': 0.026275776277425847}. Best is trial 10 with value: 0.6866984333539141.


* Best trial for C-index:
 FrozenTrial(number=10, state=TrialState.COMPLETE, values=[0.6866984333539141], datetime_start=datetime.datetime(2024, 4, 15, 13, 51, 14, 643841), datetime_complete=datetime.datetime(2024, 4, 15, 13, 51, 15, 105650), params={'l1_ratio': 0.09799455604980911}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=10, value=None)


* Best Score for C-index:
 0.6866984333539141

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24711400402245015
Fold 2 IBS: 0.1936255360028472
Fold 3 IBS: 0.21775302705493618
Fold 4 IBS: 0.19733991812882137
Fold 5 IBS: 0.20014875551269515
[I 2024-04-15 13:51:51,038] Trial 0 finished with value: 0.21119624814434998 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.21119624814434998.
Fold 1 IBS: 0.2471842830612004
Fold 2 IBS: 0.19368615252951107
Fold 3 IBS: 0.21708862067855675
Fold 4 IBS: 0.19718100727416427
Fold 5 IBS: 0.20018061988835872
[I 2024-04-15 13:51:51,516] Trial 1 finished with value: 0.21106413668635823 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.21106413668635823.
Fold 1 IBS: 0.24723347067992624
Fold 2 IBS: 0.19367590819513153
Fold 3 IBS: 0.21686033606483
Fold 4 IBS: 0.19715383356207036
Fold 5 IBS: 0.20019099705145302
[I 2024-04-15 13:51:52,002] Trial 2 finished with value: 0.21102290911068225 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.24712147005335597
Fold 2 IBS: 0.19363675969418
Fold 3 IBS: 0.21756852784619024
Fold 4 IBS: 0.19729573249955396
Fold 5 IBS: 0.2001558927757256
[I 2024-04-15 13:51:52,475] Trial 3 finished with value: 0.21115567657380113 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.24712582248866186
Fold 2 IBS: 0.19358338507832024
Fold 3 IBS: 0.21778282931405582
Fold 4 IBS: 0.197347116894656
Fold 5 IBS: 0.20014921606867422
[I 2024-04-15 13:51:53,197] Trial 4 finished with value: 0.21119767396887362 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.24719655027413365
Fold 2 IBS: 0.19363685276521034
Fold 3 IBS: 0.21733169337210145
Fold 4 IBS: 0.19725713961136446
Fold 5 IBS: 0.20016149722940238
[I 2024-04-15 13:51:53,883] Trial 5 finished with value: 0.21111674665044244 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.2471264557293496
Fold 2 IBS: 0.19357299785962562
Fold 3 IBS: 0.21801013164432992
Fold 4 IBS: 0.19740163103130542
Fold 5 IBS: 0.20012981587572365
[I 2024-04-15 13:51:54,618] Trial 6 finished with value: 0.21124820642806683 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.24710775267359267
Fold 2 IBS: 0.1936232996121534
Fold 3 IBS: 0.2177372032983022
Fold 4 IBS: 0.19733609926514534
Fold 5 IBS: 0.20014851423574673
[I 2024-04-15 13:51:55,250] Trial 7 finished with value: 0.21119057381698805 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.24716005504278046
Fold 2 IBS: 0.19361484096885687
Fold 3 IBS: 0.21748136893620465
Fold 4 IBS: 0.19727501819376
Fold 5 IBS: 0.2001636573803264
[I 2024-04-15 13:51:56,046] Trial 8 finished with value: 0.2111389881043857 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.24716067120182542
Fold 2 IBS: 0.1936229134410979
Fold 3 IBS: 0.21731661550665632
Fold 4 IBS: 0.1972355339995169
Fold 5 IBS: 0.20016949345823526
[I 2024-04-15 13:51:56,956] Trial 9 finished with value: 0.21110104552146636 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.2473427537331677
Fold 2 IBS: 0.22584288653138707
Fold 3 IBS: 0.21645031721116903
Fold 4 IBS: 0.19702844021704516
Fold 5 IBS: 0.2002146264782074
[I 2024-04-15 13:51:57,575] Trial 10 finished with value: 0.21737580483419525 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.21102290911068225.
Fold 1 IBS: 0.24721775603570045
Fold 2 IBS: 0.19371249125143933
Fold 3 IBS: 0.21683427788701165
Fold 4 IBS: 0.1971202224935298
Fold 5 IBS: 0.2001942387094685
[I 2024-04-15 13:51:58,282] Trial 11 finished with value: 0.21101579727542993 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 11 with value: 0.21101579727542993.
Fold 1 IBS: 0.24734225350905303
Fold 2 IBS: 0.2281038359719376
Fold 3 IBS: 0.22875536817922185
Fold 4 IBS: 0.23683139947841114
Fold 5 IBS: 0.22594530484730066
[I 2024-04-15 13:51:58,676] Trial 12 finished with value: 0.23339563239718486 and parameters: {'l1_ratio': 0.04835900598617554}. Best is trial 11 with value: 0.21101579727542993.
Fold 1 IBS: 0.24727896496331545
Fold 2 IBS: 0.19369858721887676
Fold 3 IBS: 0.21687078874723542
Fold 4 IBS: 0.1971288530316949
Fold 5 IBS: 0.2001895433644604
[I 2024-04-15 13:51:59,309] Trial 13 finished with value: 0.21103334746511657 and parameters: {'l1_ratio': 0.2114475350243538}. Best is trial 11 with value: 0.21101579727542993.
Fold 1 IBS: 0.2472719941832664
Fold 2 IBS: 0.19369104490749958
Fold 3 IBS: 0.2169632880495531
Fold 4 IBS: 0.19715097790051658
Fold 5 IBS: 0.20018512039303116
[I 2024-04-15 13:51:59,997] Trial 14 finished with value: 0.21105248508677335 and parameters: {'l1_ratio': 0.24307964185836162}. Best is trial 11 with value: 0.21101579727542993.
Fold 1 IBS: 0.24727954637371616
Fold 2 IBS: 0.19370711975976498
Fold 3 IBS: 0.21668039070973846
Fold 4 IBS: 0.1970832621080991
Fold 5 IBS: 0.20019689883631794
[I 2024-04-15 13:52:00,635] Trial 15 finished with value: 0.21098944355752733 and parameters: {'l1_ratio': 0.15965289527445112}. Best is trial 15 with value: 0.21098944355752733.
Fold 1 IBS: 0.24694422877221495
Fold 2 IBS: 0.2316735734965143
Fold 3 IBS: 0.22895714418167656
Fold 4 IBS: 0.24148279194384986
Fold 5 IBS: 0.22907153186466708
[I 2024-04-15 13:52:00,930] Trial 16 finished with value: 0.23562585405178452 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 15 with value: 0.21098944355752733.
Fold 1 IBS: 0.24724424140309895
Fold 2 IBS: 0.19373275712469865
Fold 3 IBS: 0.21664745674112887
Fold 4 IBS: 0.19707558850484289
Fold 5 IBS: 0.20020469771227067
[I 2024-04-15 13:52:01,565] Trial 17 finished with value: 0.21098094829720798 and parameters: {'l1_ratio': 0.13260147423242452}. Best is trial 17 with value: 0.21098094829720798.
Fold 1 IBS: 0.24726401755205174
Fold 2 IBS: 0.19370459336916607
Fold 3 IBS: 0.21669532516567194
Fold 4 IBS: 0.19708717045233318
Fold 5 IBS: 0.20020536307975034
[I 2024-04-15 13:52:02,115] Trial 18 finished with value: 0.21099129392379465 and parameters: {'l1_ratio': 0.13659466528206826}. Best is trial 17 with value: 0.21098094829720798.
Fold 1 IBS: 0.2471821344874105
Fold 2 IBS: 0.19363833622854237
Fold 3 IBS: 0.21721949375344965
Fold 4 IBS: 0.19721235851057373
Fold 5 IBS: 0.20017562290232183
[I 2024-04-15 13:52:02,591] Trial 19 finished with value: 0.21108558917645964 and parameters: {'l1_ratio': 0.33927168351271464}. Best is trial 17 with value: 0.21098094829720798.
Fold 1 IBS: 0.24714967816348193
Fold 2 IBS: 0.1936021674014335
Fold 3 IBS: 0.2176393742390485
Fold 4 IBS: 0.19731284422073014
Fold 5 IBS: 0.20015696533806926
[I 2024-04-15 13:52:02,978] Trial 20 finished with value: 0.21117220587255264 and parameters: {'l1_ratio': 0.5907721950510736}. Best is trial 17 with value: 0.21098094829720798.
Fold 1 IBS: 0.24732892423346226
Fold 2 IBS: 0.193736483487368
Fold 3 IBS: 0.21658406057369922
Fold 4 IBS: 0.19706040934041588
Fold 5 IBS: 0.20020743430409416
[I 2024-04-15 13:52:03,413] Trial 21 finished with value: 0.2109834623878079 and parameters: {'l1_ratio': 0.1173078187696212}. Best is trial 17 with value: 0.21098094829720798.
Fold 1 IBS: 0.24726694043669442
Fold 2 IBS: 0.19370900659189147
Fold 3 IBS: 0.21663348051564507
Fold 4 IBS: 0.19707236266241676
Fold 5 IBS: 0.20020811337387331
[I 2024-04-15 13:52:03,837] Trial 22 finished with value: 0.2109779807161042 and parameters: {'l1_ratio': 0.12086435085739156}. Best is trial 22 with value: 0.2109779807161042.
Fold 1 IBS: 0.24726756080163376
Fold 2 IBS: 0.19371221675892944
Fold 3 IBS: 0.216572402100162
Fold 4 IBS: 0.19705772617446876
Fold 5 IBS: 0.20021055988787367
[I 2024-04-15 13:52:04,273] Trial 23 finished with value: 0.2109640931446135 and parameters: {'l1_ratio': 0.10698380598395887}. Best is trial 23 with value: 0.2109640931446135.
Fold 1 IBS: 0.24674558816251432
Fold 2 IBS: 0.2314309883759839
Fold 3 IBS: 0.22894109569804805
Fold 4 IBS: 0.2411587817289007
Fold 5 IBS: 0.22885750442513395
[I 2024-04-15 13:52:04,496] Trial 24 finished with value: 0.23542679167811617 and parameters: {'l1_ratio': 0.006604028856537492}. Best is trial 23 with value: 0.2109640931446135.
Fold 1 IBS: 0.2472382040500399
Fold 2 IBS: 0.1936666533313974

Fold 3 IBS: 0.21713038174854807
Fold 4 IBS: 0.19719086208313805
Fold 5 IBS: 0.20017435708736836
[I 2024-04-15 13:52:04,795] Trial 25 finished with value: 0.2110800916600984 and parameters: {'l1_ratio': 0.31702325556753097}. Best is trial 23 with value: 0.2109640931446135.
Fold 1 IBS: 0.24710976507231067
Fold 2 IBS: 0.19356657811592767
Fold 3 IBS: 0.21796758095923752
Fold 4 IBS: 0.19739133670018458
Fold 5 IBS: 0.20014120372422037
[I 2024-04-15 13:52:05,154] Trial 26 finished with value: 0.21123529291437615 and parameters: {'l1_ratio': 0.9272212602815642}. Best is trial 23 with value: 0.2109640931446135.
Fold 1 IBS: 0.2472852642692684
Fold 2 IBS: 0.1937243410615861
Fold 3 IBS: 0.21650645308338287
Fold 4 IBS: 0.19704202120529382
Fold 5 IBS: 0.20021538935636174
[I 2024-04-15 13:52:05,547] Trial 27 finished with value: 0.21095469379517856 and parameters: {'l1_ratio': 0.08658554700947207}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24735434592823255
Fold 2 IBS: 0.22679503144787758
Fold 3 IBS: 0.22870486006986232
Fold 4 IBS: 0.19701439950057928
Fold 5 IBS: 0.20021858622036193
[I 2024-04-15 13:52:05,974] Trial 28 finished with value: 0.22001744463338274 and parameters: {'l1_ratio': 0.06804077757005324}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.2471743057614904
Fold 2 IBS: 0.1936825431114651
Fold 3 IBS: 0.21706401384235394
Fold 4 IBS: 0.19717506908626894
Fold 5 IBS: 0.200180273932807
[I 2024-04-15 13:52:06,416] Trial 29 finished with value: 0.21105524114687707 and parameters: {'l1_ratio': 0.281133460437211}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24716894155528818
Fold 2 IBS: 0.19362611954767178
Fold 3 IBS: 0.2173372010203377
Fold 4 IBS: 0.19724050639318735
Fold 5 IBS: 0.2001697951943415
[I 2024-04-15 13:52:06,848] Trial 30 finished with value: 0.2111085127421653 and parameters: {'l1_ratio': 0.3989239121633671}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24727292088279618
Fold 2 IBS: 0.19370450765419392
Fold 3 IBS: 0.21666286705241664
Fold 4 IBS: 0.1971106107018832
Fold 5 IBS: 0.20019667291844176
[I 2024-04-15 13:52:07,279] Trial 31 finished with value: 0.2109895158419463 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24729106806220733
Fold 2 IBS: 0.19372148457095936
Fold 3 IBS: 0.21662906194056966
Fold 4 IBS: 0.19707145522266348
Fold 5 IBS: 0.20021135686454963
[I 2024-04-15 13:52:07,714] Trial 32 finished with value: 0.2109848853321899 and parameters: {'l1_ratio': 0.11072580806002986}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24719865334921812
Fold 2 IBS: 0.1936570200833962
Fold 3 IBS: 0.21700066463711476
Fold 4 IBS: 0.19715999903508333
Fold 5 IBS: 0.20018564109326667
[I 2024-04-15 13:52:08,170] Trial 33 finished with value: 0.2110403956396158 and parameters: {'l1_ratio': 0.24949937619062534}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24731314147181926
Fold 2 IBS: 0.22856771237951104
Fold 3 IBS: 0.2287767783785854
Fold 4 IBS: 0.23742097215140825
Fold 5 IBS: 0.22634839367445406
[I 2024-04-15 13:52:08,456] Trial 34 finished with value: 0.2336853996111556 and parameters: {'l1_ratio': 0.041878367132729036}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24723537866199777
Fold 2 IBS: 0.19368145124158623
Fold 3 IBS: 0.21687728322445515
Fold 4 IBS: 0.197130620931129
Fold 5 IBS: 0.2001948435808572
[I 2024-04-15 13:52:08,887] Trial 35 finished with value: 0.21102391552800506 and parameters: {'l1_ratio': 0.19631609988412568}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24733108011000532
Fold 2 IBS: 0.1937424834581103
Fold 3 IBS: 0.2164711170946795
Fold 4 IBS: 0.19703336314352782
Fold 5 IBS: 0.20021218353005965
[I 2024-04-15 13:52:09,310] Trial 36 finished with value: 0.21095804546727653 and parameters: {'l1_ratio': 0.09252482626463483}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.2472966598766668
Fold 2 IBS: 0.2261585115374966
Fold 3 IBS: 0.228686283195737
Fold 4 IBS: 0.19703737764358448
Fold 5 IBS: 0.2002176158982732
[I 2024-04-15 13:52:09,639] Trial 37 finished with value: 0.21987928963035158 and parameters: {'l1_ratio': 0.07844440965335264}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24708583218738278
Fold 2 IBS: 0.1936059812539121
Fold 3 IBS: 0.2179066934853507
Fold 4 IBS: 0.1973766350976458
Fold 5 IBS: 0.20014024786980514
[I 2024-04-15 13:52:10,011] Trial 38 finished with value: 0.21122307797881928 and parameters: {'l1_ratio': 0.8598478847078105}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24717396155548038
Fold 2 IBS: 0.19363516144537588
Fold 3 IBS: 0.21719924653541503
Fold 4 IBS: 0.1972074674151818
Fold 5 IBS: 0.20017532987755982
[I 2024-04-15 13:52:10,418] Trial 39 finished with value: 0.21107823336580261 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24714658850007848
Fold 2 IBS: 0.1936096298695853
Fold 3 IBS: 0.21744767483117455
Fold 4 IBS: 0.19726687771995996
Fold 5 IBS: 0.20016315045552435
[I 2024-04-15 13:52:10,815] Trial 40 finished with value: 0.21112678427526452 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24727952834839856
Fold 2 IBS: 0.19370711264955828
Fold 3 IBS: 0.21668034303015124
Fold 4 IBS: 0.19708325062953758
Fold 5 IBS: 0.2001968982176449
[I 2024-04-15 13:52:11,269] Trial 41 finished with value: 0.21098942657505812 and parameters: {'l1_ratio': 0.15964825493321597}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24726543161525114
Fold 2 IBS: 0.19371137896922036
Fold 3 IBS: 0.21656727076264276
Fold 4 IBS: 0.19705648446754162
Fold 5 IBS: 0.20021048923347762
[I 2024-04-15 13:52:11,739] Trial 42 finished with value: 0.2109622110096267 and parameters: {'l1_ratio': 0.10665675763066282}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24678557989502223
Fold 2 IBS: 0.2314798455364142
Fold 3 IBS: 0.2289443028143783
Fold 4 IBS: 0.24122398972444947
Fold 5 IBS: 0.2289006232012591
[I 2024-04-15 13:52:11,938] Trial 43 finished with value: 0.23546686823430468 and parameters: {'l1_ratio': 0.006063778256745658}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24728097657092338
Fold 2 IBS: 0.19372019816398772
Fold 3 IBS: 0.21654784273960012
Fold 4 IBS: 0.19705191740488842
Fold 5 IBS: 0.20021322353866833
[I 2024-04-15 13:52:12,577] Trial 44 finished with value: 0.21096283168361357 and parameters: {'l1_ratio': 0.09675214817866275}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.247370174441858
Fold 2 IBS: 0.22715759989840076
Fold 3 IBS: 0.228717278671587
Fold 4 IBS: 0.23564315737904853
Fold 5 IBS: 0.20022068780398297
[I 2024-04-15 13:52:12,949] Trial 45 finished with value: 0.22782177963897543 and parameters: {'l1_ratio': 0.06236861641046257}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.2472558124233085
Fold 2 IBS: 0.1936793918578265
Fold 3 IBS: 0.21704250708496198
Fold 4 IBS: 0.19716988395945034
Fold 5 IBS: 0.20017997619719144
[I 2024-04-15 13:52:13,372] Trial 46 finished with value: 0.21106551430454776 and parameters: {'l1_ratio': 0.27683532195580673}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24728380023672097
Fold 2 IBS: 0.1937004955384037
Fold 3 IBS: 0.21688367003229383
Fold 4 IBS: 0.19713195993578136
Fold 5 IBS: 0.20018971901153235
[I 2024-04-15 13:52:13,767] Trial 47 finished with value: 0.21103792895094645 and parameters: {'l1_ratio': 0.21326539855647839}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24713415214973372
Fold 2 IBS: 0.1935961704558354
Fold 3 IBS: 0.21760030513542422
Fold 4 IBS: 0.19730340186137757
Fold 5 IBS: 0.20015636821464047
[I 2024-04-15 13:52:14,232] Trial 48 finished with value: 0.21115807956340227 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24728508687669204
Fold 2 IBS: 0.19370535475283843
Fold 3 IBS: 0.21678635549322983
Fold 4 IBS: 0.1971086573145688
Fold 5 IBS: 0.20019358531086626
[I 2024-04-15 13:52:14,640] Trial 49 finished with value: 0.2110158079496391 and parameters: {'l1_ratio': 0.1849402787437627}. Best is trial 27 with value: 0.21095469379517856.

Fold 1 IBS: 0.24733058201948163
Fold 2 IBS: 0.19374228550558356
Fold 3 IBS: 0.21646981442818783
Fold 4 IBS: 0.19703304865849025
Fold 5 IBS: 0.20021216636339284
[I 2024-04-15 13:52:15,049] Trial 50 finished with value: 0.2109575793950272 and parameters: {'l1_ratio': 0.09245607769603169}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24733608628168227
Fold 2 IBS: 0.19374447388546562
Fold 3 IBS: 0.2164842109301202
Fold 4 IBS: 0.19703652520186807
Fold 5 IBS: 0.20021235699329745
[I 2024-04-15 13:52:15,506] Trial 51 finished with value: 0.21096273065848675 and parameters: {'l1_ratio': 0.09322127061868946}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24737783516167797
Fold 2 IBS: 0.22828951614611498
Fold 3 IBS: 0.22876373450842225
Fold 4 IBS: 0.23706684221599025
Fold 5 IBS: 0.22610653553141913
[I 2024-04-15 13:52:15,872] Trial 52 finished with value: 0.23352089271272494 and parameters: {'l1_ratio': 0.04573584965321713}. Best is trial 27 with value: 0.21095469379517856.
Fold 1 IBS: 0.24731593200940744
Fold 2 IBS: 0.1937364701991184
Fold 3 IBS: 0.2164315087535123
Fold 4 IBS: 0.19702380903887545
Fold 5 IBS: 0.20021166879908345
[I 2024-04-15 13:52:16,304] Trial 53 finished with value: 0.21094387775999937 and parameters: {'l1_ratio': 0.09047684364202117}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24493181128284305
Fold 2 IBS: 0.22916024436164703
Fold 3 IBS: 0.22880648835939432
Fold 4 IBS: 0.23818068406730386
Fold 5 IBS: 0.22686469053999195
[I 2024-04-15 13:52:16,528] Trial 54 finished with value: 0.23358878372223604 and parameters: {'l1_ratio': 0.03394009136783404}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2471839942078613
Fold 2 IBS: 0.19369124607477092
Fold 3 IBS: 0.21696465288189995
Fold 4 IBS: 0.19715130706669934
Fold 5 IBS: 0.20018513917593952
[I 2024-04-15 13:52:16,952] Trial 55 finished with value: 0.21103526788143423 and parameters: {'l1_ratio': 0.24330849221540093}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24726758949589417
Fold 2 IBS: 0.1937024084817008
Fold 3 IBS: 0.21664877367100227
Fold 4 IBS: 0.1971074732630551
Fold 5 IBS: 0.2002025927071373
[I 2024-04-15 13:52:17,345] Trial 56 finished with value: 0.21098576752375794 and parameters: {'l1_ratio': 0.15663108595987923}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2471710936660471
Fold 2 IBS: 0.19361046310445745
Fold 3 IBS: 0.21764615472719595
Fold 4 IBS: 0.19732589520395952
Fold 5 IBS: 0.20014716996199317
[I 2024-04-15 13:52:17,685] Trial 57 finished with value: 0.21118015533273066 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24715073183224362
Fold 2 IBS: 0.19359299934297544
Fold 3 IBS: 0.21784590845497484
Fold 4 IBS: 0.19736238106399523
Fold 5 IBS: 0.2001389331405286
[I 2024-04-15 13:52:18,011] Trial 58 finished with value: 0.21121819076694354 and parameters: {'l1_ratio': 0.7734026256905541}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24728217600847618
Fold 2 IBS: 0.19370420565788354
Fold 3 IBS: 0.21677862890913407
Fold 4 IBS: 0.19710679484243626
Fold 5 IBS: 0.20019348200200618
[I 2024-04-15 13:52:18,368] Trial 59 finished with value: 0.21101305748398724 and parameters: {'l1_ratio': 0.18403141814003715}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24729578476712716
Fold 2 IBS: 0.2266717396732225
Fold 3 IBS: 0.22870093276180634
Fold 4 IBS: 0.19702662177196983
Fold 5 IBS: 0.2002192718652681
[I 2024-04-15 13:52:18,696] Trial 60 finished with value: 0.21998287016787882 and parameters: {'l1_ratio': 0.07001056770890576}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24734658659597214
Fold 2 IBS: 0.1937486538342746
Fold 3 IBS: 0.216511681342662
Fold 4 IBS: 0.1970431649456174
Fold 5 IBS: 0.20021272629644524
[I 2024-04-15 13:52:19,122] Trial 61 finished with value: 0.21097256260299427 and parameters: {'l1_ratio': 0.09471512955374492}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24732118705148812
Fold 2 IBS: 0.19373044733817874
Fold 3 IBS: 0.2166321418179148
Fold 4 IBS: 0.19707188800428987
Fold 5 IBS: 0.20020448946424937
[I 2024-04-15 13:52:19,563] Trial 62 finished with value: 0.21099203073522416 and parameters: {'l1_ratio': 0.13137041453871987}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24723607338459258
Fold 2 IBS: 0.23202658548175817
Fold 3 IBS: 0.22898095944549568
Fold 4 IBS: 0.2419568722714141
Fold 5 IBS: 0.22938382391742587
[I 2024-04-15 13:52:19,816] Trial 63 finished with value: 0.2359168629001373 and parameters: {'l1_ratio': 0.0001413011655347074}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24731251437125884
Fold 2 IBS: 0.19373266527003405
Fold 3 IBS: 0.21647891976356523
Fold 4 IBS: 0.19703514803671035
Fold 5 IBS: 0.20020931238182402
[I 2024-04-15 13:52:20,264] Trial 64 finished with value: 0.2109537119646785 and parameters: {'l1_ratio': 0.10130917585998378}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2450258944135618
Fold 2 IBS: 0.2292806503780303
Fold 3 IBS: 0.2288128303750763
Fold 4 IBS: 0.23833595999730778
Fold 5 IBS: 0.22696979661119276
[I 2024-04-15 13:52:20,501] Trial 65 finished with value: 0.23368502635503377 and parameters: {'l1_ratio': 0.03237131840649944}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24728079092916094
Fold 2 IBS: 0.19371120063198563
Fold 3 IBS: 0.21660092224140848
Fold 4 IBS: 0.1970970141306863
Fold 5 IBS: 0.200200158531277
[I 2024-04-15 13:52:21,017] Trial 66 finished with value: 0.21097801729290366 and parameters: {'l1_ratio': 0.1401658495817201}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.247325444765977
Fold 2 IBS: 0.19374024474885335
Fold 3 IBS: 0.21645638000946135
Fold 4 IBS: 0.19702980641243467
Fold 5 IBS: 0.20021199028102252
[I 2024-04-15 13:52:21,420] Trial 67 finished with value: 0.21095277324354975 and parameters: {'l1_ratio': 0.09175267377184114}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24723435983563308
Fold 2 IBS: 0.19367625654446427
Fold 3 IBS: 0.21686271108396132
Fold 4 IBS: 0.19715436092936925
Fold 5 IBS: 0.20019102875483888
[I 2024-04-15 13:52:21,742] Trial 68 finished with value: 0.21102374342965335 and parameters: {'l1_ratio': 0.2272781871952837}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24721331938869565
Fold 2 IBS: 0.19371087777696389
Fold 3 IBS: 0.2168234528104415
Fold 4 IBS: 0.19711760801527478
Fold 5 IBS: 0.20019408921162368
[I 2024-04-15 13:52:22,092] Trial 69 finished with value: 0.21101186944059988 and parameters: {'l1_ratio': 0.18942581039571943}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.245000554084283
Fold 2 IBS: 0.22924824807892646
Fold 3 IBS: 0.2288111139108598
Fold 4 IBS: 0.23829414426609888
Fold 5 IBS: 0.22694150533891438
[I 2024-04-15 13:52:22,324] Trial 70 finished with value: 0.2336591131358165 and parameters: {'l1_ratio': 0.03279205744926333}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2472760695993222
Fold 2 IBS: 0.19371826390998634
Fold 3 IBS: 0.21653603800691468
Fold 4 IBS: 0.1970490586980285
Fold 5 IBS: 0.2002130598303706
[I 2024-04-15 13:52:22,869] Trial 71 finished with value: 0.21095849800892444 and parameters: {'l1_ratio': 0.09607810213697428}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24733608693263642
Fold 2 IBS: 0.19374202491646228
Fold 3 IBS: 0.21654068838331816
Fold 4 IBS: 0.19705005632841446
Fold 5 IBS: 0.20021012727123874
[I 2024-04-15 13:52:23,297] Trial 72 finished with value: 0.210975796766414 and parameters: {'l1_ratio': 0.10499245105020383}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24735218996396954
Fold 2 IBS: 0.22631369619743416
Fold 3 IBS: 0.2286904165327812
Fold 4 IBS: 0.19702321016597926
Fold 5 IBS: 0.2002168145477526
[I 2024-04-15 13:52:23,593] Trial 73 finished with value: 0.21991926548158336 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24731531328827128
Fold 2 IBS: 0.19372811681200103
Fold 3 IBS: 0.2166166779428893
Fold 4 IBS: 0.19706815398056393
Fold 5 IBS: 0.20020428136343607
[I 2024-04-15 13:52:23,988] Trial 74 finished with value: 0.21098650867743235 and parameters: {'l1_ratio': 0.130149232258403}. Best is trial 53 with value: 0.21094387775999937.

Fold 1 IBS: 0.2473003630703882
Fold 2 IBS: 0.19371534452480685
Fold 3 IBS: 0.21673547099250093
Fold 4 IBS: 0.19709653799375557
Fold 5 IBS: 0.20019762802244337
[I 2024-04-15 13:52:24,477] Trial 75 finished with value: 0.211009068920779 and parameters: {'l1_ratio': 0.16519036404979054}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2452490121428647
Fold 2 IBS: 0.22956505914115263
Fold 3 IBS: 0.2288281989762864
Fold 4 IBS: 0.2387039274036472
Fold 5 IBS: 0.2272183201218906
[I 2024-04-15 13:52:24,817] Trial 76 finished with value: 0.23391290355716832 and parameters: {'l1_ratio': 0.02872279649413431}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24731727540725035
Fold 2 IBS: 0.22745251816434017
Fold 3 IBS: 0.22872829921003118
Fold 4 IBS: 0.2360114074589735
Fold 5 IBS: 0.20022292848895276
[I 2024-04-15 13:52:25,127] Trial 77 finished with value: 0.22794648574590962 and parameters: {'l1_ratio': 0.05788272087021253}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24732735049008386
Fold 2 IBS: 0.19373585817690867
Fold 3 IBS: 0.21657992671006385
Fold 4 IBS: 0.19705941062383017
Fold 5 IBS: 0.20020737856403717
[I 2024-04-15 13:52:25,563] Trial 78 finished with value: 0.21098198491298475 and parameters: {'l1_ratio': 0.1170193195267912}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24732403835951425
Fold 2 IBS: 0.22597478935318033
Fold 3 IBS: 0.21640146136632613
Fold 4 IBS: 0.1970166475341095
Fold 5 IBS: 0.20021398737016746
[I 2024-04-15 13:52:26,024] Trial 79 finished with value: 0.21738618479665953 and parameters: {'l1_ratio': 0.08155896298589378}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24725709129082343
Fold 2 IBS: 0.1936982786586913
Fold 3 IBS: 0.21675443399049754
Fold 4 IBS: 0.19710129882907515
Fold 5 IBS: 0.2002022275502138
[I 2024-04-15 13:52:26,444] Trial 80 finished with value: 0.21100266606386026 and parameters: {'l1_ratio': 0.1540666096915633}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24731509521147316
Fold 2 IBS: 0.1937336883180864
Fold 3 IBS: 0.21648568035116497
Fold 4 IBS: 0.1970367777999527
Fold 5 IBS: 0.20020939976458924
[I 2024-04-15 13:52:26,921] Trial 81 finished with value: 0.2109561282890533 and parameters: {'l1_ratio': 0.10170032437154218}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2473222868151327
Fold 2 IBS: 0.19373384722446246
Fold 3 IBS: 0.2165666269198186
Fold 4 IBS: 0.19705619868285915
Fold 5 IBS: 0.20020720034698014
[I 2024-04-15 13:52:27,479] Trial 82 finished with value: 0.21097723199785062 and parameters: {'l1_ratio': 0.11610020623684614}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24735049231934061
Fold 2 IBS: 0.22727140721186315
Fold 3 IBS: 0.2287214361405744
Fold 4 IBS: 0.23578503627131414
Fold 5 IBS: 0.2002200039659285
[I 2024-04-15 13:52:27,931] Trial 83 finished with value: 0.22786967518180418 and parameters: {'l1_ratio': 0.06062423194262612}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24722284805640857
Fold 2 IBS: 0.19367175031031664
Fold 3 IBS: 0.21694814998500828
Fold 4 IBS: 0.19714753741785784
Fold 5 IBS: 0.20019062177562005
[I 2024-04-15 13:52:28,320] Trial 84 finished with value: 0.2110361815090423 and parameters: {'l1_ratio': 0.22283287163521492}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24723999557202317
Fold 2 IBS: 0.19368761434631998
Fold 3 IBS: 0.2167964628140033
Fold 4 IBS: 0.1971112750768579
Fold 5 IBS: 0.20019846927127563
[I 2024-04-15 13:52:28,715] Trial 85 finished with value: 0.211006763416096 and parameters: {'l1_ratio': 0.17176426312191045}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24719282803459156
Fold 2 IBS: 0.19362756914319887
Fold 3 IBS: 0.21750393967602466
Fold 4 IBS: 0.19728017399498335
Fold 5 IBS: 0.2001549547969101
[I 2024-04-15 13:52:29,148] Trial 86 finished with value: 0.2111518931291417 and parameters: {'l1_ratio': 0.5196302291802515}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2472544718275623
Fold 2 IBS: 0.1937008406226132
Fold 3 IBS: 0.21667221768800066
Fold 4 IBS: 0.19708157655572223
Fold 5 IBS: 0.2002050391529005
[I 2024-04-15 13:52:29,599] Trial 87 finished with value: 0.2109828291693598 and parameters: {'l1_ratio': 0.13463888261616913}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24600059248466208
Fold 2 IBS: 0.2305112615470273
Fold 3 IBS: 0.22888299437828533
Fold 4 IBS: 0.2399400381248883
Fold 5 IBS: 0.22804767761343833
[I 2024-04-15 13:52:29,843] Trial 88 finished with value: 0.23467651282966026 and parameters: {'l1_ratio': 0.017131014574704492}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24729452708829694
Fold 2 IBS: 0.1937255466813435
Fold 3 IBS: 0.21658044163618684
Fold 4 IBS: 0.19705981930933983
Fold 5 IBS: 0.20021368258823352
[I 2024-04-15 13:52:30,196] Trial 89 finished with value: 0.21097480346068012 and parameters: {'l1_ratio': 0.0986609998291813}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2472184556933679
Fold 2 IBS: 0.1936647479831103
Fold 3 IBS: 0.21704932403489327
Fold 4 IBS: 0.19717176433426697
Fold 5 IBS: 0.20018633860907484
[I 2024-04-15 13:52:30,589] Trial 90 finished with value: 0.21105812613094263 and parameters: {'l1_ratio': 0.25835961648725553}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24730245562683786
Fold 2 IBS: 0.226120496665109
Fold 3 IBS: 0.2286853109721361
Fold 4 IBS: 0.19704074810573813
Fold 5 IBS: 0.20021781111031606
[I 2024-04-15 13:52:30,914] Trial 91 finished with value: 0.21987336449602743 and parameters: {'l1_ratio': 0.07908461750430693}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24737387638299754
Fold 2 IBS: 0.2279511284502493
Fold 3 IBS: 0.2287486978957546
Fold 4 IBS: 0.23663832071047117
Fold 5 IBS: 0.22581282334731936
[I 2024-04-15 13:52:31,168] Trial 92 finished with value: 0.23330496935735842 and parameters: {'l1_ratio': 0.05054623551349102}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2472774012483725
Fold 2 IBS: 0.19371878867577802
Fold 3 IBS: 0.21653924146784556
Fold 4 IBS: 0.197049834323874
Fold 5 IBS: 0.200213104123312
[I 2024-04-15 13:52:31,632] Trial 93 finished with value: 0.2109596739678364 and parameters: {'l1_ratio': 0.09626013597519838}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24731453081329535
Fold 2 IBS: 0.19372454591508545
Fold 3 IBS: 0.2166899435250324
Fold 4 IBS: 0.19708570144737708
Fold 5 IBS: 0.20020133087420555
[I 2024-04-15 13:52:32,042] Trial 94 finished with value: 0.21100321051499912 and parameters: {'l1_ratio': 0.14792037842544747}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24723231181189356
Fold 2 IBS: 0.19368024990396762
Fold 3 IBS: 0.21686979818668406
Fold 4 IBS: 0.1971288097438888
Fold 5 IBS: 0.20019473704660273
[I 2024-04-15 13:52:32,436] Trial 95 finished with value: 0.21102118133860737 and parameters: {'l1_ratio': 0.19532952863488207}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24729446315170972
Fold 2 IBS: 0.1937228260746243
Fold 3 IBS: 0.21649358399443405
Fold 4 IBS: 0.19707344142962346
Fold 5 IBS: 0.20021147455099828
[I 2024-04-15 13:52:32,847] Trial 96 finished with value: 0.21095915784027794 and parameters: {'l1_ratio': 0.11128706146989246}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.24733496130134178
Fold 2 IBS: 0.22776491275302305
Fold 3 IBS: 0.2287408279543756
Fold 4 IBS: 0.23640355609874567
Fold 5 IBS: 0.22565141693007051
[I 2024-04-15 13:52:33,250] Trial 97 finished with value: 0.23317913500751128 and parameters: {'l1_ratio': 0.05325075318240604}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2472964958570734
Fold 2 IBS: 0.19372877581356698
Fold 3 IBS: 0.21653342505306447
Fold 4 IBS: 0.19704855831628798
Fold 5 IBS: 0.20021576672779168
[I 2024-04-15 13:52:33,655] Trial 98 finished with value: 0.2109646043535569 and parameters: {'l1_ratio': 0.08797281975755124}. Best is trial 53 with value: 0.21094387775999937.
Fold 1 IBS: 0.2472686618742264
Fold 2 IBS: 0.19370968417631454
Fold 3 IBS: 0.2166376382954628
Fold 4 IBS: 0.1970733694707773
Fold 5 IBS: 0.20020817157316495
[I 2024-04-15 13:52:34,051] Trial 99 finished with value: 0.21097950507798918 and parameters: {'l1_ratio': 0.12117292526232518}. Best is trial 53 with value: 0.21094387775999937.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.21094387775999937], datetime_start=datetime.datetime(2024, 4, 15, 13, 52, 15, 878265), datetime_complete=datetime.datetime(2024, 4, 15, 13, 52, 16, 303566), params={'l1_ratio': 0.09047684364202117}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=53, value=None)


* Best Score for IBS:
 0.21094387775999937

In [41]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [42]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.687
train_ibs:  0.211

#### Test

In [43]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [44]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.09799455604980911)

test_cindex : 0.523

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.09047684364202117)

test_ibs:  0.29

In [45]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [46]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:52:34,369] A new study created in memory with name: no-name-42e6c84b-8d72-46b7-b68c-1688080d3762

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 13:52:40,148] Trial 0 finished with value: 0.6977075894586338 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6977075894586338.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:52:45,304] Trial 1 finished with value: 0.7128781680014569 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:52:47,504] Trial 2 finished with value: 0.7078951516958202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:52:48,218] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:52:49,069] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:52:52,863] Trial 5 finished with value: 0.7140624838621864 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:52:57,240] Trial 6 finished with value: 0.7101780788884746 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:52:59,621] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-15 13:53:05,029] Trial 8 finished with value: 0.5257510729613734 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:53:07,975] Trial 9 finished with value: 0.7039036721293016 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:53:08,401] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:53:10,236] Trial 11 finished with value: 0.7271736918163124 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:53:12,011] Trial 12 finished with value: 0.7217535824914708 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8064195611120726, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:53:13,228] Trial 13 finished with value: 0.7230396596037402 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.8350722272141606, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13041468920781069, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6845493562231759
[I 2024-04-15 13:53:14,402] Trial 14 finished with value: 0.7401429490839831 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9806297626114981, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18121651510792322, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383

Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:53:15,419] Trial 15 finished with value: 0.7359974816455777 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9916077098875709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2050785814281292, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7060085836909872
[I 2024-04-15 13:53:15,662] Trial 16 finished with value: 0.7424649927687818 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.9632036286697128, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19855793167729388, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 13:53:15,811] Trial 17 finished with value: 0.7187276534642637 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.9920927723346319, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6115879828326181
[I 2024-04-15 13:53:16,042] Trial 18 finished with value: 0.6821795609651563 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.4733682176858589, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18440565612965779, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6394849785407726
[I 2024-04-15 13:53:16,477] Trial 19 finished with value: 0.6909365199154465 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.8996903695627709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3933604732001355, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6974248927038627
[I 2024-04-15 13:53:17,634] Trial 20 finished with value: 0.731849318014498 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.7099567102313042, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2573277491349737, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:53:18,400] Trial 21 finished with value: 0.7351391125468653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9578709493710758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19090506657387685, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:53:18,977] Trial 22 finished with value: 0.7341648725242437 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.9967334344648481, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22971555033034935, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:53:19,988] Trial 23 finished with value: 0.7461784934529897 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.8688645990573083, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1729801266340484, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:53:21,205] Trial 24 finished with value: 0.7410139181199299 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.866350879679609, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07068946136637579, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 13:53:22,524] Trial 25 finished with value: 0.7568542957468967 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.8561321352006472, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07248837432829829, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:53:23,837] Trial 26 finished with value: 0.7469421068076121 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.766734838708136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07999208951911986, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 13:53:24,985] Trial 27 finished with value: 0.7510925047188961 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.7750769539334444, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06326441457712315, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:53:26,344] Trial 28 finished with value: 0.7651955962327717 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.6847169156044919, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003364807635412012, 'warm_start': True}. Best is trial 28 with value: 0.7651955962327717.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 13:53:28,612] Trial 29 finished with value: 0.7751733627229969 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.04113891562651206, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 13:53:30,594] Trial 30 finished with value: 0.7736629125252518 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.6833587310905035, 'max_features': None, 'min_weight_fraction_leaf': 0.008532800179007469, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:53:32,788] Trial 31 finished with value: 0.7735002862697369 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.6547593902381754, 'max_features': None, 'min_weight_fraction_leaf': 0.01653304213676029, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:53:34,867] Trial 32 finished with value: 0.7726671170454932 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.7011070731694715, 'max_features': None, 'min_weight_fraction_leaf': 0.002655419277963856, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-15 13:53:36,905] Trial 33 finished with value: 0.761951377352432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.4871505413082745, 'max_features': None, 'min_weight_fraction_leaf': 0.0037092008636243484, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:53:39,411] Trial 34 finished with value: 0.7772994105576999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5424853541641252, 'max_features': None, 'min_weight_fraction_leaf': 0.04005993867513943, 'warm_start': True}. Best is trial 34 with value: 0.7772994105576999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:53:42,001] Trial 35 finished with value: 0.7939453846462785 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5281329979576042, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.7939453846462785.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-15 13:53:44,663] Trial 36 finished with value: 0.7988094200063037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5475428261493075, 'max_features': None, 'min_weight_fraction_leaf': 0.04248766950155104, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8081395348837209
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:53:47,340] Trial 37 finished with value: 0.7438212214010235 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.537628436907505, 'max_features': None, 'min_weight_fraction_leaf': 0.13505191950972878, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:53:50,559] Trial 38 finished with value: 0.7773251612620597 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4079124058970714, 'max_features': None, 'min_weight_fraction_leaf': 0.043050318879278446, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:53:54,513] Trial 39 finished with value: 0.734846885715039 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': None, 'min_weight_fraction_leaf': 0.10012332890216755, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7381974248927039
[I 2024-04-15 13:53:58,077] Trial 40 finished with value: 0.7649536724571295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.38596283150687494, 'max_features': None, 'min_weight_fraction_leaf': 0.04061455540701541, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 13:54:01,545] Trial 41 finished with value: 0.7941370621081079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.5853104884542844, 'max_features': None, 'min_weight_fraction_leaf': 0.045291071200096567, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:54:05,037] Trial 42 finished with value: 0.736998260411046 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 466, 'oob_score': True, 'max_samples': 0.5547327087340422, 'max_features': None, 'min_weight_fraction_leaf': 0.15119679094835453, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:54:07,934] Trial 43 finished with value: 0.7838881672008012 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.43155969103520636, 'max_features': None, 'min_weight_fraction_leaf': 0.043472744875657617, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:54:09,914] Trial 44 finished with value: 0.7399894649828315 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.4005082288778946, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:54:11,101] Trial 45 finished with value: 0.7241222823816911 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.25182885979889597, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08391169894605255, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:54:16,310] Trial 46 finished with value: 0.7058457110259935 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.43126650753033136, 'max_features': None, 'min_weight_fraction_leaf': 0.05341940290949464, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 13:54:17,960] Trial 47 finished with value: 0.761821383227146 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.30342154143659733, 'max_features': None, 'min_weight_fraction_leaf': 0.03559822522548907, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:54:24,236] Trial 48 finished with value: 0.7117273483913299 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 435, 'oob_score': True, 'max_samples': 0.5993264662444304, 'max_features': None, 'min_weight_fraction_leaf': 0.1243065372654003, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:54:27,974] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.5188442477983979, 'max_features': None, 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:54:28,959] Trial 50 finished with value: 0.737899316580976 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.5847268231512849, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15227204260709018, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 13:54:31,499] Trial 51 finished with value: 0.7814971781238983 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.43199709338607994, 'max_features': None, 'min_weight_fraction_leaf': 0.03149759470389267, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 13:54:35,115] Trial 52 finished with value: 0.7567762597419098 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4387556889483383, 'max_features': None, 'min_weight_fraction_leaf': 0.09297907262518232, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-15 13:54:37,487] Trial 53 finished with value: 0.7986572561005724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.4978232271491865, 'max_features': None, 'min_weight_fraction_leaf': 0.033781036150152696, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:54:39,673] Trial 54 finished with value: 0.8175044273559141 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.4961608781156207, 'max_features': None, 'min_weight_fraction_leaf': 0.025003317155411986, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.759656652360515
[I 2024-04-15 13:54:43,360] Trial 55 finished with value: 0.7750834494179615 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.5021698171984055, 'max_features': None, 'min_weight_fraction_leaf': 0.06062440846922696, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 13:54:48,280] Trial 56 finished with value: 0.692159003960772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.6431467441559697, 'max_features': None, 'min_weight_fraction_leaf': 0.021762770810368127, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7725321888412017
[I 2024-04-15 13:54:51,401] Trial 57 finished with value: 0.7775457629433687 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.5757175357123006, 'max_features': None, 'min_weight_fraction_leaf': 0.05830794943324037, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:54:53,100] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.4648579376135416, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.30295661673067836, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:54:54,097] Trial 59 finished with value: 0.742832764389526 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.34319505493069397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08248014261229168, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:55:02,352] Trial 60 finished with value: 0.7094998068077641 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.6211328199713557, 'max_features': None, 'min_weight_fraction_leaf': 0.11070844936873359, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8068669527896996
[I 2024-04-15 13:55:06,791] Trial 61 finished with value: 0.8036986552407976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.5153677562911374, 'max_features': None, 'min_weight_fraction_leaf': 0.031485629345332306, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:55:10,625] Trial 62 finished with value: 0.8182757698225179 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.5112289023564809, 'max_features': None, 'min_weight_fraction_leaf': 0.02095528969051655, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:55:13,756] Trial 63 finished with value: 0.8111521115785895 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.5100900270084606, 'max_features': None, 'min_weight_fraction_leaf': 0.018150109857069722, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7510729613733905
[I 2024-04-15 13:55:16,672] Trial 64 finished with value: 0.7700709580629541 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.4955086388573719, 'max_features': None, 'min_weight_fraction_leaf': 0.06782578020859786, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:55:19,140] Trial 65 finished with value: 0.8185942843287751 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.572806842914682, 'max_features': None, 'min_weight_fraction_leaf': 0.02226915354245074, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:55:21,464] Trial 66 finished with value: 0.8160847545835782 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.5576081908424206, 'max_features': None, 'min_weight_fraction_leaf': 0.016475143309745643, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:55:23,533] Trial 67 finished with value: 0.8101126972372172 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.561957978855049, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.018288170265703986, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:55:25,336] Trial 68 finished with value: 0.8183234527679148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.6097336917403036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02099611885947379, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8454935622317596
[I 2024-04-15 13:55:27,001] Trial 69 finished with value: 0.8272146463529724 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7318335045229435, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017419775688352082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8283261802575107
[I 2024-04-15 13:55:28,568] Trial 70 finished with value: 0.8158063208975717 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.6243013523451256, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020464714362005143, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:55:30,302] Trial 71 finished with value: 0.824114421989065 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.7330924737377311, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016575501718897302, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:55:32,071] Trial 72 finished with value: 0.8125646918339378 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7326351452640015, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0027592484745489945, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:55:33,800] Trial 73 finished with value: 0.8078669641918867 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 262, 'oob_score': True, 'max_samples': 0.6560932996857387, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01505215827140816, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8369098712446352
[I 2024-04-15 13:55:35,742] Trial 74 finished with value: 0.8229478737470439 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.8040957518239317, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024607026709667742, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6931330472103004
[I 2024-04-15 13:55:37,740] Trial 75 finished with value: 0.7297534394801531 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.8244077376700942, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2738762867283342, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8154506437768241
[I 2024-04-15 13:55:41,061] Trial 76 finished with value: 0.8005224502929792 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.7779027631332152, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06198954175038082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:55:44,031] Trial 77 finished with value: 0.8054911364827252 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.7444363178817063, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00391494572036042, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7639484978540773
[I 2024-04-15 13:55:47,023] Trial 78 finished with value: 0.7766506135263602 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.7964582770234238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08072526041027032, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 13:55:48,111] Trial 79 finished with value: 0.7952779202339323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.618087421106259, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02724887288178213, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6716738197424893
[I 2024-04-15 13:55:51,737] Trial 80 finished with value: 0.7109603094858263 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.6608918473113886, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22754786457763954, 'warm_start': False}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:55:53,809] Trial 81 finished with value: 0.823191212472951 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 334, 'oob_score': True, 'max_samples': 0.7181496469643299, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01833632174034757, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:55:56,178] Trial 82 finished with value: 0.8055458278408263 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.718648090454236, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05194443679311898, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:55:58,442] Trial 83 finished with value: 0.812684350596275 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.7502215626294254, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011526440379393736, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8412017167381974
[I 2024-04-15 13:56:00,827] Trial 84 finished with value: 0.8232844098456795 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.8395867498100796, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024617503790133055, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-15 13:56:03,341] Trial 85 finished with value: 0.7921991713994829 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 368, 'oob_score': True, 'max_samples': 0.8857836580094625, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07264997820097252, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:56:05,647] Trial 86 finished with value: 0.8224086969713147 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9236490757653891, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05091910924778117, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:56:07,939] Trial 87 finished with value: 0.7444219877257969 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.8360547528312109, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05159081964644253, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:56:11,218] Trial 88 finished with value: 0.8299957447925681 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6373390557939914
[I 2024-04-15 13:56:13,672] Trial 89 finished with value: 0.6984552187416074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9606865260369674, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42980933716176023, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8583690987124464
[I 2024-04-15 13:56:15,857] Trial 90 finished with value: 0.8168638261621636 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.8970982407350513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0033122441195345426, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8497854077253219
[I 2024-04-15 13:56:17,710] Trial 91 finished with value: 0.8288039966760785 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.8500705105869577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02769924772148816, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-15 13:56:19,828] Trial 92 finished with value: 0.828952436236799 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.9318910170313084, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03466207519046283, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8326180257510729
[I 2024-04-15 13:56:22,058] Trial 93 finished with value: 0.8246721711870638 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.9237402520498113, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051627897348460114, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7682403433476395
[I 2024-04-15 13:56:23,910] Trial 94 finished with value: 0.7774842065936604 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.9315755472196319, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09044268069913194, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-15 13:56:25,868] Trial 95 finished with value: 0.8149658464044028 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.9428489419934195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05519942461860093, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 13:56:27,592] Trial 96 finished with value: 0.7343217686472692 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 18, 'n_estimators': 255, 'oob_score': True, 'max_samples': 0.8550701905177472, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07090475670535565, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7553648068669528
[I 2024-04-15 13:56:28,616] Trial 97 finished with value: 0.7709719977986227 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.9118193987076412, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.035787567288930885, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:56:30,360] Trial 98 finished with value: 0.7298807893419987 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9222109032849816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04727690829808437, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415

[I 2024-04-15 13:56:35,791] A new study created in memory with name: no-name-87099163-5fab-49c2-9a05-7931897f2883

Fold 5 C-index: 0.6759656652360515
[I 2024-04-15 13:56:35,773] Trial 99 finished with value: 0.7070161831399606 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.9759793763474963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3521412865651261, 'warm_start': False}. Best is trial 88 with value: 0.8299957447925681.


* Best trial for C-index:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.8299957447925681], datetime_start=datetime.datetime(2024, 4, 15, 13, 56, 7, 946371), datetime_complete=datetime.datetime(2024, 4, 15, 13, 56, 11, 218020), params={'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=88, value=None)


* Best Score for C-index:
 0.8299957447925681

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22407713995563355
Fold 2 IBS: 0.17470488039835566
Fold 3 IBS: 0.2398383923527903
Fold 4 IBS: 0.20906561324773706
Fold 5 IBS: 0.2195728796491891
[I 2024-04-15 13:56:40,072] Trial 0 finished with value: 0.21345178112074117 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21345178112074117.
Fold 1 IBS: 0.21616660020333003
Fold 2 IBS: 0.17486525786616586
Fold 3 IBS: 0.2107106205384323
Fold 4 IBS: 0.20216950628891073
Fold 5 IBS: 0.21532298657498944
[I 2024-04-15 13:56:41,068] Trial 1 finished with value: 0.20384699429436565 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-15 13:56:41,747] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-15 13:56:44,318] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-15 13:56:46,538] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24936759596080646
Fold 2 IBS: 0.17264271046131205
Fold 3 IBS: 0.20421070451417014
Fold 4 IBS: 0.21666312222005965
Fold 5 IBS: 0.21221582754312004
[I 2024-04-15 13:56:49,856] Trial 5 finished with value: 0.2110199921398937 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21621830894948232
Fold 2 IBS: 0.18912437295998735
Fold 3 IBS: 0.25661481391845226
Fold 4 IBS: 0.20519890764061255
Fold 5 IBS: 0.21737176566006436
[I 2024-04-15 13:56:52,542] Trial 6 finished with value: 0.21690563382571976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.239725565259837
Fold 2 IBS: 0.22117477833066543
Fold 3 IBS: 0.22403481418923998
Fold 4 IBS: 0.2325927375141085
Fold 5 IBS: 0.22473498221278954
[I 2024-04-15 13:56:57,544] Trial 7 finished with value: 0.22845257550132808 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-15 13:57:05,028] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22659514067603376
Fold 2 IBS: 0.17851765630325647
Fold 3 IBS: 0.2013246121030424
Fold 4 IBS: 0.20963921105379285
Fold 5 IBS: 0.2203202485023523
[I 2024-04-15 13:57:06,504] Trial 9 finished with value: 0.2072793737276956 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-15 13:57:08,570] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2540107203940081
Fold 2 IBS: 0.19018193572283806
Fold 3 IBS: 0.2693108522338297
Fold 4 IBS: 0.2204494801684996
Fold 5 IBS: 0.22801293569526146
[I 2024-04-15 13:57:08,882] Trial 11 finished with value: 0.23239318484288743 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9899815471614337, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23986882649245242
Fold 2 IBS: 0.17667107107700725
Fold 3 IBS: 0.19675890006825608
Fold 4 IBS: 0.21136980755566645
Fold 5 IBS: 0.21659638264865502
[I 2024-04-15 13:57:10,981] Trial 12 finished with value: 0.20825299756840746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.838341657174724, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007007532608717559}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22478082430068405
Fold 2 IBS: 0.17185450852530715
Fold 3 IBS: 0.21027987039395774
Fold 4 IBS: 0.20018219852324562
Fold 5 IBS: 0.21753825326760137
[I 2024-04-15 13:57:12,359] Trial 13 finished with value: 0.2049271310021592 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.964999799603621, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2691953450690723}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21998167437826233
Fold 2 IBS: 0.18978207675252776
Fold 3 IBS: 0.2156881327568739
Fold 4 IBS: 0.20498945225014242
Fold 5 IBS: 0.2158332545660207
[I 2024-04-15 13:57:13,145] Trial 14 finished with value: 0.2092549181407654 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7347591488544951, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2812321272168262}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24379041704605284
Fold 2 IBS: 0.16804912162483507
Fold 3 IBS: 0.2051845606137616
Fold 4 IBS: 0.20906885042686352
Fold 5 IBS: 0.2130970650630231
[I 2024-04-15 13:57:15,265] Trial 15 finished with value: 0.20783800295490723 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9966433181385008, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13541305845514623}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.24681956605569497
Fold 2 IBS: 0.23227093172764388
Fold 3 IBS: 0.22941903729651647
Fold 4 IBS: 0.24121738904572626
Fold 5 IBS: 0.2302321253386658
[I 2024-04-15 13:57:17,416] Trial 16 finished with value: 0.2359918098928495 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 162, 'oob_score': False, 'max_samples': 0.32587405036023415, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3357318242102959}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2231111330848275
Fold 2 IBS: 0.17656419065238982
Fold 3 IBS: 0.20901589415087424
Fold 4 IBS: 0.20307733734686217
Fold 5 IBS: 0.21545535438507316
[I 2024-04-15 13:57:22,630] Trial 17 finished with value: 0.20544478192400537 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8324456438302156, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2527008941020278}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23532815608885377
Fold 2 IBS: 0.1837655560742492
Fold 3 IBS: 0.20262687562645237
Fold 4 IBS: 0.2122206984989701
Fold 5 IBS: 0.2166747901565821
[I 2024-04-15 13:57:23,365] Trial 18 finished with value: 0.21012321528902148 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.6751019433313558, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11276726622420546}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22863054693293589
Fold 2 IBS: 0.1963315773237213
Fold 3 IBS: 0.21471249390143013
Fold 4 IBS: 0.219881142418457
Fold 5 IBS: 0.22152453289806817
[I 2024-04-15 13:57:23,597] Trial 19 finished with value: 0.21621605869492252 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.756071359635432, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32595449578288455}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22537941330506062
Fold 2 IBS: 0.19227308793145745
Fold 3 IBS: 0.21265991721222577
Fold 4 IBS: 0.20917597176350836
Fold 5 IBS: 0.21687868662201695
[I 2024-04-15 13:57:24,639] Trial 20 finished with value: 0.21127341536685385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.6036734235439312, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23857721033918533}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22324770605725813
Fold 2 IBS: 0.18253846781709399
Fold 3 IBS: 0.2045169037430424
Fold 4 IBS: 0.20783876653003266
Fold 5 IBS: 0.2175938501921847
[I 2024-04-15 13:57:29,452] Trial 21 finished with value: 0.20714713886792238 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.8230570050888841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2722629100041059}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24383129660582778
Fold 2 IBS: 0.16931429481145502
Fold 3 IBS: 0.20516950235518827
Fold 4 IBS: 0.20489042671888189
Fold 5 IBS: 0.21168593869445076
[I 2024-04-15 13:57:33,980] Trial 22 finished with value: 0.20697829183716077 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.9080266581136552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1738640799325239}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22798058234299892
Fold 2 IBS: 0.17066187178067507
Fold 3 IBS: 0.20762316176929713
Fold 4 IBS: 0.20163711855316047
Fold 5 IBS: 0.21357666387653937
[I 2024-04-15 13:57:37,171] Trial 23 finished with value: 0.20429587966453416 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.918144892067728, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22593418563490295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2333417951219333
Fold 2 IBS: 0.1700982573355749
Fold 3 IBS: 0.20661966502631599
Fold 4 IBS: 0.20215860951935866
Fold 5 IBS: 0.21369121522055837
[I 2024-04-15 13:57:40,310] Trial 24 finished with value: 0.20518190844474823 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.9261452409044857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2150416825146331}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2302095064014022
Fold 2 IBS: 0.20489193018995322
Fold 3 IBS: 0.22229468418463336
Fold 4 IBS: 0.22315856362376232
Fold 5 IBS: 0.22270247922464476
[I 2024-04-15 13:57:42,651] Trial 25 finished with value: 0.22065143272487914 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7754756321225551, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37858736351418476}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622588582203958
Fold 2 IBS: 0.23225616799196488
Fold 3 IBS: 0.22961130014021525
Fold 4 IBS: 0.24150610351006122
Fold 5 IBS: 0.23015340332834447
[I 2024-04-15 13:57:47,474] Trial 26 finished with value: 0.23595057215852505 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 410, 'oob_score': True, 'max_samples': 0.44732517583857423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30573135880353774}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24371312366354173
Fold 2 IBS: 0.17009470168949176
Fold 3 IBS: 0.20387614537935278
Fold 4 IBS: 0.2063297018706307
Fold 5 IBS: 0.21225767577269047
[I 2024-04-15 13:57:50,878] Trial 27 finished with value: 0.20725426967514146 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.9264498293472653, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16408374861729386}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24230033744905524
Fold 2 IBS: 0.1700083907734053
Fold 3 IBS: 0.20307970499577657
Fold 4 IBS: 0.21056222306350966
Fold 5 IBS: 0.21225464745768113
[I 2024-04-15 13:57:53,272] Trial 28 finished with value: 0.20764106074788558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.6539680943502474, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11167707604899824}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24611993726989195
Fold 2 IBS: 0.23218890990534718
Fold 3 IBS: 0.23048044870725193
Fold 4 IBS: 0.2410683146218637
Fold 5 IBS: 0.2299160122305334
[I 2024-04-15 13:57:58,840] Trial 29 finished with value: 0.23595472454697766 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.11354273074199811, 'max_features': None, 'min_weight_fraction_leaf': 0.23506901120045084}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22660818914056846
Fold 2 IBS: 0.17199394890259848
Fold 3 IBS: 0.20974235645980502
Fold 4 IBS: 0.20527990803227994
Fold 5 IBS: 0.2142164886689667
[I 2024-04-15 13:58:00,627] Trial 30 finished with value: 0.2055681782408437 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 164, 'oob_score': False, 'max_samples': 0.7841568813969919, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19739729582328963}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23708578217070322
Fold 2 IBS: 0.17051603032060797
Fold 3 IBS: 0.2048697308529193
Fold 4 IBS: 0.20307497656561538
Fold 5 IBS: 0.21255249060044212
[I 2024-04-15 13:58:03,903] Trial 31 finished with value: 0.20561980210205758 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 339, 'oob_score': False, 'max_samples': 0.9431792460514251, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20474531091370285}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.22612682993385486
Fold 2 IBS: 0.17223298934748948
Fold 3 IBS: 0.20782358499736456
Fold 4 IBS: 0.20181112716562463
Fold 5 IBS: 0.21350833459590543
[I 2024-04-15 13:58:06,586] Trial 32 finished with value: 0.2043005732080478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.8753375341925101, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2230974552568295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22177687649658975
Fold 2 IBS: 0.17630377861515312
Fold 3 IBS: 0.2122309287307206
Fold 4 IBS: 0.2017574245411477
Fold 5 IBS: 0.21470545803951144
[I 2024-04-15 13:58:09,301] Trial 33 finished with value: 0.20535489328462447 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.8780403780133842, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26554839348030423}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2347950025150411
Fold 2 IBS: 0.16799406158735225
Fold 3 IBS: 0.2119268936202999
Fold 4 IBS: 0.1995017747896286
Fold 5 IBS: 0.21645738910312
[I 2024-04-15 13:58:10,328] Trial 34 finished with value: 0.2061350243230884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.9713620300267395, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22449252311835874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2184171866823885
Fold 2 IBS: 0.18340292802030164
Fold 3 IBS: 0.24622741065146023
Fold 4 IBS: 0.21030733491515133
Fold 5 IBS: 0.218874594617978
[I 2024-04-15 13:58:12,281] Trial 35 finished with value: 0.21544589097745592 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.8006724007383993, 'max_features': None, 'min_weight_fraction_leaf': 0.2991859225334826}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24658618602469104
Fold 2 IBS: 0.2321884009769192
Fold 3 IBS: 0.2295721257429426
Fold 4 IBS: 0.24149932745394134
Fold 5 IBS: 0.23037083343869663
[I 2024-04-15 13:58:14,585] Trial 36 finished with value: 0.23604337472743814 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.7142345385665702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24597601805501332
Fold 2 IBS: 0.16679544014249023
Fold 3 IBS: 0.2291560830967934
Fold 4 IBS: 0.21774129632473188
Fold 5 IBS: 0.21808816775530818
[I 2024-04-15 13:58:17,954] Trial 37 finished with value: 0.21555140107486742 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.8893387526179963, 'max_features': None, 'min_weight_fraction_leaf': 0.05558599763353947}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22361789070615487
Fold 2 IBS: 0.17833589878764333
Fold 3 IBS: 0.20797628674399748
Fold 4 IBS: 0.20706581092390064
Fold 5 IBS: 0.21475624911298768
[I 2024-04-15 13:58:22,450] Trial 38 finished with value: 0.2063504272549368 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.48823423037203917, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10676050487618188}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2465964694944807
Fold 2 IBS: 0.23221073187531344
Fold 3 IBS: 0.22950988130319463
Fold 4 IBS: 0.241408499161141
Fold 5 IBS: 0.23022625655373033
[I 2024-04-15 13:58:24,940] Trial 39 finished with value: 0.235990367677572 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.5771239750792474, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3646319374122424}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21647863712170887
Fold 2 IBS: 0.17199966700669284
Fold 3 IBS: 0.19869719848871478
Fold 4 IBS: 0.20796789999763218
Fold 5 IBS: 0.21625226939504177
[I 2024-04-15 13:58:25,340] Trial 40 finished with value: 0.2022791344019581 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.7017810474930685, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15131446570826318}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22134427216375058
Fold 2 IBS: 0.1760712729646329
Fold 3 IBS: 0.19474566426704223
Fold 4 IBS: 0.21163414366897387
Fold 5 IBS: 0.21799528858603973
[I 2024-04-15 13:58:25,730] Trial 41 finished with value: 0.20435812833008785 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6851330046079013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1415472492884433}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21730762926082742
Fold 2 IBS: 0.17880052942015828
Fold 3 IBS: 0.19466820609343688
Fold 4 IBS: 0.20919417870986243
Fold 5 IBS: 0.2175415352637051
[I 2024-04-15 13:58:26,092] Trial 42 finished with value: 0.20350241574959801 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.6932739851311275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14781080589948162}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2266914017789978
Fold 2 IBS: 0.18902598179814228
Fold 3 IBS: 0.1886797492652457
Fold 4 IBS: 0.21746952054591362
Fold 5 IBS: 0.21485690053973838
[I 2024-04-15 13:58:26,443] Trial 43 finished with value: 0.20734471078560754 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 26, 'oob_score': False, 'max_samples': 0.6230606164996372, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17300117076396285}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2263300301352394
Fold 2 IBS: 0.17228759968501195
Fold 3 IBS: 0.20727538565975506
Fold 4 IBS: 0.20619156167481315
Fold 5 IBS: 0.2151350980475268
[I 2024-04-15 13:58:27,253] Trial 44 finished with value: 0.20544393504046926 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.5383399306130238, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07137280133151601}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2195259426238762
Fold 2 IBS: 0.17176930604867915
Fold 3 IBS: 0.21264489605286027
Fold 4 IBS: 0.2026960468857599
Fold 5 IBS: 0.2155061220972602
[I 2024-04-15 13:58:27,896] Trial 45 finished with value: 0.20442846274168716 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7211266599729008, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08955966829076284}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.24664109906894663
Fold 2 IBS: 0.23211151536965932
Fold 3 IBS: 0.22921725039634813
Fold 4 IBS: 0.24155332248199884
Fold 5 IBS: 0.2300252715829934
[I 2024-04-15 13:58:29,350] Trial 46 finished with value: 0.23590969177998927 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.4955610125060993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22677458805979425
Fold 2 IBS: 0.18128534484285147
Fold 3 IBS: 0.20359451039074664
Fold 4 IBS: 0.21860313764199735
Fold 5 IBS: 0.21528256346964708
[I 2024-04-15 13:58:29,643] Trial 47 finished with value: 0.20910802888100735 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.6381469780315093, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15711696604627562}. Best is trial 40 with value: 0.2022791344019581.

Fold 1 IBS: 0.23790435513187447
Fold 2 IBS: 0.16917310562036944
Fold 3 IBS: 0.2032724536335342
Fold 4 IBS: 0.20275263571784216
Fold 5 IBS: 0.21198800508925086
[I 2024-04-15 13:58:32,786] Trial 48 finished with value: 0.20501811103857426 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.862646612475437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18882619674434536}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21643739431200149
Fold 2 IBS: 0.18002210069568697
Fold 3 IBS: 0.20963559196115233
Fold 4 IBS: 0.20201711337877098
Fold 5 IBS: 0.21711926927169345
[I 2024-04-15 13:58:33,458] Trial 49 finished with value: 0.20504629392386103 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.712240935894755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03279359667752256}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21970666197039673
Fold 2 IBS: 0.17845771406023855
Fold 3 IBS: 0.20885143473324186
Fold 4 IBS: 0.20319913155933902
Fold 5 IBS: 0.2153595741585475
[I 2024-04-15 13:58:35,644] Trial 50 finished with value: 0.2051149032963527 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.581277730850803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13970814386185937}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21850000381456347
Fold 2 IBS: 0.17736923091725895
Fold 3 IBS: 0.20498374840747066
Fold 4 IBS: 0.2021359588037073
Fold 5 IBS: 0.21987202711845588
[I 2024-04-15 13:58:36,097] Trial 51 finished with value: 0.20457219381229125 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.6824265755354791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13000278013180866}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21997861326285056
Fold 2 IBS: 0.17510133496874586
Fold 3 IBS: 0.20782135929983414
Fold 4 IBS: 0.20318340455059253
Fold 5 IBS: 0.21807100804623603
[I 2024-04-15 13:58:36,698] Trial 52 finished with value: 0.20483114402565183 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 39, 'oob_score': False, 'max_samples': 0.7595422741248538, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1492553835770421}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.20187641777839058
Fold 2 IBS: 0.21697708771949703
Fold 3 IBS: 0.2594495566549233
Fold 4 IBS: 0.2052587865188469
Fold 5 IBS: 0.22918402151273276
[I 2024-04-15 13:58:36,894] Trial 53 finished with value: 0.22254917403687813 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7063377467137641, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12053402761378912}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2163446023224957
Fold 2 IBS: 0.17212550764211373
Fold 3 IBS: 0.21160944290207245
Fold 4 IBS: 0.20512480185219015
Fold 5 IBS: 0.2160354664693132
[I 2024-04-15 13:58:37,524] Trial 54 finished with value: 0.20424796423763705 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.6746935555292785, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0904689651104114}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22967201163797166
Fold 2 IBS: 0.17176959330058167
Fold 3 IBS: 0.20224897452635443
Fold 4 IBS: 0.20289718637619525
Fold 5 IBS: 0.21350582751457162
[I 2024-04-15 13:58:38,749] Trial 55 finished with value: 0.2040187186711349 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 135, 'oob_score': False, 'max_samples': 0.8028424541436651, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18708342016220178}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2329914623588844
Fold 2 IBS: 0.1709218692606976
Fold 3 IBS: 0.2022628895427006
Fold 4 IBS: 0.2037428253059489
Fold 5 IBS: 0.21379783296488847
[I 2024-04-15 13:58:40,056] Trial 56 finished with value: 0.204743375886624 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.8015891614775278, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08443475399948225}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22222933862075872
Fold 2 IBS: 0.17307243696245472
Fold 3 IBS: 0.2076841617030592
Fold 4 IBS: 0.20227550999755373
Fold 5 IBS: 0.21586625145405466
[I 2024-04-15 13:58:41,314] Trial 57 finished with value: 0.2042255397475762 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.6308231363037688, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04742769018003304}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2456168604122806
Fold 2 IBS: 0.1720780186944042
Fold 3 IBS: 0.1939891166776255
Fold 4 IBS: 0.21652289584699036
Fold 5 IBS: 0.21111767529637926
[I 2024-04-15 13:58:42,618] Trial 58 finished with value: 0.207864913385536 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.6079842908829092, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04294499138204588}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22124664269345137
Fold 2 IBS: 0.17562069103113492
Fold 3 IBS: 0.2089041573304958
Fold 4 IBS: 0.20473650596918874
Fold 5 IBS: 0.2141094172536013
[I 2024-04-15 13:58:44,690] Trial 59 finished with value: 0.20492348285557443 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.6538044546332764, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02711344752535265}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2181513360924439
Fold 2 IBS: 0.17768472605175628
Fold 3 IBS: 0.21223044737111443
Fold 4 IBS: 0.20136958313815562
Fold 5 IBS: 0.21615046674907337
[I 2024-04-15 13:58:45,721] Trial 60 finished with value: 0.20511731188050875 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 84, 'oob_score': True, 'max_samples': 0.7478284186818124, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006650389537996307}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23118626942195483
Fold 2 IBS: 0.1702053994866854
Fold 3 IBS: 0.2129030925098888
Fold 4 IBS: 0.19903740475703263
Fold 5 IBS: 0.2136572303984417
[I 2024-04-15 13:58:46,449] Trial 61 finished with value: 0.20539787931480066 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.830509938904831, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1023742346219489}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2205940046318535
Fold 2 IBS: 0.17584334134448318
Fold 3 IBS: 0.20675620555477245
Fold 4 IBS: 0.20426009333569892
Fold 5 IBS: 0.216570869801864
[I 2024-04-15 13:58:47,679] Trial 62 finished with value: 0.20480490293373438 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 102, 'oob_score': True, 'max_samples': 0.6818329215138573, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18242157905770487}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23169425244220557
Fold 2 IBS: 0.17140668425310054
Fold 3 IBS: 0.19908163234934842
Fold 4 IBS: 0.20893662933440016

Fold 5 IBS: 0.21281753768850425
[I 2024-04-15 13:58:48,997] Trial 63 finished with value: 0.20478734721351177 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.5771231216606082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05763095148942208}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21904071817956408
Fold 2 IBS: 0.17322770907939164
Fold 3 IBS: 0.21071337338690455
Fold 4 IBS: 0.20198953222034577
Fold 5 IBS: 0.21531568867352077
[I 2024-04-15 13:58:49,737] Trial 64 finished with value: 0.20405740430794536 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.6331344922813995, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1612709153840626}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2211019166635484
Fold 2 IBS: 0.17526371579768263
Fold 3 IBS: 0.20774379356238173
Fold 4 IBS: 0.20424362266236684
Fold 5 IBS: 0.21480184651012801
[I 2024-04-15 13:58:50,858] Trial 65 finished with value: 0.2046309790392215 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.6350728460096916, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1631502901267459}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22198736886877768
Fold 2 IBS: 0.19061491871912364
Fold 3 IBS: 0.21827968226635633
Fold 4 IBS: 0.2052006534517124
Fold 5 IBS: 0.21613440335803383
[I 2024-04-15 13:58:51,729] Trial 66 finished with value: 0.21044340533280076 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.5218576422719642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19995250145835095}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2179075292069881
Fold 2 IBS: 0.18413396774995214
Fold 3 IBS: 0.20963049043297036
Fold 4 IBS: 0.20746418192466917
Fold 5 IBS: 0.21676539015107638
[I 2024-04-15 13:58:52,315] Trial 67 finished with value: 0.20718031189313124 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 52, 'oob_score': False, 'max_samples': 0.6169103339039868, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0952902999587806}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2265700266034037
Fold 2 IBS: 0.18276032311436483
Fold 3 IBS: 0.2042864418492306
Fold 4 IBS: 0.20936741747437496
Fold 5 IBS: 0.21564455337157445
[I 2024-04-15 13:58:52,611] Trial 68 finished with value: 0.20772575248258968 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.7428544401290184, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07523325642012642}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2317749634162734
Fold 2 IBS: 0.1684381693450842
Fold 3 IBS: 0.23424060778843453
Fold 4 IBS: 0.21328093521325694
Fold 5 IBS: 0.21962511519703135
[I 2024-04-15 13:58:53,795] Trial 69 finished with value: 0.2134719581920161 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.6630802195286096, 'max_features': None, 'min_weight_fraction_leaf': 0.12509688782986045}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21940762796898436
Fold 2 IBS: 0.17406140071679074
Fold 3 IBS: 0.21074986909040594
Fold 4 IBS: 0.20255362262736462
Fold 5 IBS: 0.2145647222877615
[I 2024-04-15 13:58:54,659] Trial 70 finished with value: 0.20426744853826145 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.6927913414061104, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1491330560760582}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22012016394475659
Fold 2 IBS: 0.17475427785134492
Fold 3 IBS: 0.21014966656305184
Fold 4 IBS: 0.20376747945979912
Fold 5 IBS: 0.21541417348684497
[I 2024-04-15 13:58:55,548] Trial 71 finished with value: 0.2048411522611595 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.6845803813000064, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1523838280114369}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2216865262329327
Fold 2 IBS: 0.17268198910660865
Fold 3 IBS: 0.21309572839002539
Fold 4 IBS: 0.20002188205239937
Fold 5 IBS: 0.2166664932944772
[I 2024-04-15 13:58:56,251] Trial 72 finished with value: 0.20483052381528868 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7721996477240339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17006714738018724}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2204717268372329
Fold 2 IBS: 0.18965023421922483
Fold 3 IBS: 0.21023281503750718
Fold 4 IBS: 0.20732383670369434
Fold 5 IBS: 0.21359155179608108
[I 2024-04-15 13:58:56,781] Trial 73 finished with value: 0.20825403291874806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 44, 'oob_score': False, 'max_samples': 0.60377148666791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12161104496600006}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2191586477412759
Fold 2 IBS: 0.17078013242114562
Fold 3 IBS: 0.20927963366535351
Fold 4 IBS: 0.20258237972300233
Fold 5 IBS: 0.2149257258484936
[I 2024-04-15 13:58:57,541] Trial 74 finished with value: 0.2033453038798542 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7304174393685703, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18556210671805792}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21830414363737688
Fold 2 IBS: 0.17720271112298439
Fold 3 IBS: 0.20697150533408146
Fold 4 IBS: 0.20250876743216076
Fold 5 IBS: 0.2152601673419393
[I 2024-04-15 13:58:58,558] Trial 75 finished with value: 0.20404945897370858 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.6468801596739339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18546007907051182}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22430380108574707
Fold 2 IBS: 0.18306897497858327
Fold 3 IBS: 0.20464475027408288
Fold 4 IBS: 0.21223544052441004
Fold 5 IBS: 0.21727837802511207
[I 2024-04-15 13:58:59,959] Trial 76 finished with value: 0.20830626897758706 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.7294723925670973, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24992337115768753}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22302173389184585
Fold 2 IBS: 0.1887176942510202
Fold 3 IBS: 0.20967732423927182
Fold 4 IBS: 0.20791001510644727
Fold 5 IBS: 0.21680578739397888
[I 2024-04-15 13:59:01,046] Trial 77 finished with value: 0.2092265109765128 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2128668242174557}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2239900710700344
Fold 2 IBS: 0.1698615839561287
Fold 3 IBS: 0.2095547190098964
Fold 4 IBS: 0.2012069680997044
Fold 5 IBS: 0.21613576683580699
[I 2024-04-15 13:59:02,007] Trial 78 finished with value: 0.20414982179431415 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.798025512896543, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.187406229874218}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22242518635376562
Fold 2 IBS: 0.17356537149199874

Fold 3 IBS: 0.19348965127184473
Fold 4 IBS: 0.20729301862706373
Fold 5 IBS: 0.21518309439089522
[I 2024-04-15 13:59:02,366] Trial 79 finished with value: 0.2023912644271136 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.7940170614934956, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19696931079449848}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2449767955817733
Fold 2 IBS: 0.172095460075217
Fold 3 IBS: 0.21463433607213933
Fold 4 IBS: 0.21510140082957746
Fold 5 IBS: 0.21527266884222518
[I 2024-04-15 13:59:02,784] Trial 80 finished with value: 0.21241613228018644 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 28, 'oob_score': False, 'max_samples': 0.8170871700419534, 'max_features': None, 'min_weight_fraction_leaf': 0.21125680575069572}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22348296120259534
Fold 2 IBS: 0.16980207668047606
Fold 3 IBS: 0.21009370900921706
Fold 4 IBS: 0.20191156961895484
Fold 5 IBS: 0.21613576683580699
[I 2024-04-15 13:59:03,530] Trial 81 finished with value: 0.20428521666941007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7971516901362177, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18138610915926726}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2561856444522722
Fold 2 IBS: 0.1673967931519715
Fold 3 IBS: 0.20047088391888304
Fold 4 IBS: 0.21074651924541707
Fold 5 IBS: 0.2099772553369716
[I 2024-04-15 13:59:03,767] Trial 82 finished with value: 0.20895541922110308 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.8399824689482805, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19201377617331056}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22426305056629034
Fold 2 IBS: 0.18300755389928863
Fold 3 IBS: 0.20718971819956258
Fold 4 IBS: 0.20479720064549958
Fold 5 IBS: 0.21619343342523623
[I 2024-04-15 13:59:04,302] Trial 83 finished with value: 0.20709019134717543 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.7653436422440136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24531020078321944}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22467801181967628
Fold 2 IBS: 0.17100965075590382
Fold 3 IBS: 0.20899248385281644
Fold 4 IBS: 0.20131690199114788
Fold 5 IBS: 0.21546837157592233
[I 2024-04-15 13:59:05,100] Trial 84 finished with value: 0.20429308399909335 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.7307213180337556, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16397999497171722}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22483109101566637
Fold 2 IBS: 0.17542630441342943
Fold 3 IBS: 0.207300694612249
Fold 4 IBS: 0.20406653897060492
Fold 5 IBS: 0.2158305961193959
[I 2024-04-15 13:59:06,325] Trial 85 finished with value: 0.2054910450262691 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.7826456215522579, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22924983418535252}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22386484118726915
Fold 2 IBS: 0.17019457614889205
Fold 3 IBS: 0.19033990305706086
Fold 4 IBS: 0.20853944070357402
Fold 5 IBS: 0.21728171951643854
[I 2024-04-15 13:59:06,756] Trial 86 finished with value: 0.20204409612264693 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.20601078792005195
Fold 2 IBS: 0.21451972742974615
Fold 3 IBS: 0.24528820767892662
Fold 4 IBS: 0.22453641785090767
Fold 5 IBS: 0.23206174675939142
[I 2024-04-15 13:59:06,941] Trial 87 finished with value: 0.22448337752780478 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.6512094554417259, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20485933323937144}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.24762671522415539
Fold 2 IBS: 0.1715658463060267
Fold 3 IBS: 0.19148117469966647
Fold 4 IBS: 0.20997063572215197
Fold 5 IBS: 0.2129063439446945
[I 2024-04-15 13:59:07,313] Trial 88 finished with value: 0.206710143179339 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.7081631748214322, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.135797779820887}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.25058563680774437
Fold 2 IBS: 0.2338641464063254
Fold 3 IBS: 0.22952356547794778
Fold 4 IBS: 0.24193138867022507
Fold 5 IBS: 0.23265095037320685
[I 2024-04-15 13:59:07,608] Trial 89 finished with value: 0.2377111375470899 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.15094844814066605, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25791328124207724}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22061007889537348
Fold 2 IBS: 0.1708591714745691
Fold 3 IBS: 0.21077158373683536
Fold 4 IBS: 0.20117937734899835
Fold 5 IBS: 0.2131852975039104
[I 2024-04-15 13:59:08,239] Trial 90 finished with value: 0.20332110179193735 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7073303179127854, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17438023467720193}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22104227565411022
Fold 2 IBS: 0.1722308353188776
Fold 3 IBS: 0.21218986505215992
Fold 4 IBS: 0.2005308528950858
Fold 5 IBS: 0.21558296667096527
[I 2024-04-15 13:59:08,889] Trial 91 finished with value: 0.20431535911823975 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.7458306090358743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17711861957316688}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2188852968200289
Fold 2 IBS: 0.1741200249949188
Fold 3 IBS: 0.2102249823823517
Fold 4 IBS: 0.20502686094713804
Fold 5 IBS: 0.21682970835459212
[I 2024-04-15 13:59:09,625] Trial 92 finished with value: 0.20501737469980594 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.6974990002375354, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16157211463362758}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22524471349246272
Fold 2 IBS: 0.18187848730423692
Fold 3 IBS: 0.20172697428993133
Fold 4 IBS: 0.20497913158718492
Fold 5 IBS: 0.2205671313428573
[I 2024-04-15 13:59:10,198] Trial 93 finished with value: 0.20687928760333466 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.6611862408590626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1916422380825528}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22083768503980603
Fold 2 IBS: 0.1797588530429119
Fold 3 IBS: 0.2079648062250091
Fold 4 IBS: 0.20291373702977164
Fold 5 IBS: 0.21635495382740025
[I 2024-04-15 13:59:11,605] Trial 94 finished with value: 0.2055660070329798 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.713903532939743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22122568041634558}. Best is trial 86 with value: 0.20204409612264693.

Fold 1 IBS: 0.26932513184118945
Fold 2 IBS: 0.1697323509215535
Fold 3 IBS: 0.20905255797983618
Fold 4 IBS: 0.2258672184082545
Fold 5 IBS: 0.2152407835992728
[I 2024-04-15 13:59:12,243] Trial 95 finished with value: 0.21784360855002127 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.8547756485942715, 'max_features': None, 'min_weight_fraction_leaf': 0.17594983744388534}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22065985212578162
Fold 2 IBS: 0.1724043068676393
Fold 3 IBS: 0.212876495767763
Fold 4 IBS: 0.20196603399913246
Fold 5 IBS: 0.21590968295775706
[I 2024-04-15 13:59:13,436] Trial 96 finished with value: 0.2047632743436147 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.7614906038154946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.140922870660813}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2124870890419155
Fold 2 IBS: 0.1839728942989018
Fold 3 IBS: 0.20401760145240125
Fold 4 IBS: 0.2083031273260043
Fold 5 IBS: 0.2181106808859397
[I 2024-04-15 13:59:14,330] Trial 97 finished with value: 0.20537827860103253 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.6469848321883379, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20645813530532972}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.21598257747339383
Fold 2 IBS: 0.19029660089884604
Fold 3 IBS: 0.21934243199729314
Fold 4 IBS: 0.20794860179398514
Fold 5 IBS: 0.21465156821990095
[I 2024-04-15 13:59:15,486] Trial 98 finished with value: 0.2096443560766838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.5974486750517274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2337807792851884}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22905634179711468
Fold 2 IBS: 0.16952063124242736
Fold 3 IBS: 0.20512675662267585
Fold 4 IBS: 0.2057771072122423
Fold 5 IBS: 0.21371077936387817
[I 2024-04-15 13:59:17,284] Trial 99 finished with value: 0.20463832324766768 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 185, 'oob_score': False, 'max_samples': 0.7373842810679355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15101502561347407}. Best is trial 86 with value: 0.20204409612264693.


* Best trial for IBS:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.20204409612264693], datetime_start=datetime.datetime(2024, 4, 15, 13, 59, 6, 342843), datetime_complete=datetime.datetime(2024, 4, 15, 13, 59, 6, 756003), params={'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=86, value=None)


* Best Score for IBS:
 0.20204409612264693

In [47]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.83
train_ibs:  0.202

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [50]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=18, max_leaf_nodes=11,
                     max_samples=0.9059465751594485, min_samples_leaf=1,
                     min_weight_fraction_leaf=0.029068528038335394,
                     n_estimators=318, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.544

RandomSurvivalForest(max_depth=13, max_features='log2', max_leaf_nodes=11,
                     max_samples=0.7105780352803006, min_samples_leaf=11,
                     min_samples_split=13,
                     min_weight_fraction_leaf=0.2021626029496649,
                     n_estimators=31, random_state=123)

test_ibs:  0.247

In [51]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [52]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 13:59:18,402] A new study created in memory with name: no-name-b9f4eb6e-664c-49e6-80f0-382afbebbe1e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:19,201] Trial 0 finished with value: 0.7329375617815092 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:21,069] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:24,873] Trial 2 finished with value: 0.7178460229393517 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.8
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 13:59:25,218] Trial 3 finished with value: 0.7317208004250113 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:26,614] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:28,326] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:29,245] Trial 6 finished with value: 0.7321370246874943 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 13:59:31,432] Trial 7 finished with value: 0.7075673219865799 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 13:59:31,564] Trial 8 finished with value: 0.7362139149697521 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6545064377682404
[I 2024-04-15 13:59:36,063] Trial 9 finished with value: 0.6956580572700294 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:36,302] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.26413466171660194, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6802575107296137
[I 2024-04-15 13:59:36,410] Trial 11 finished with value: 0.7002022988770951 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 5, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:59:36,729] Trial 12 finished with value: 0.7233216044410213 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 108, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.21197644982784386}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:59:37,521] Trial 13 finished with value: 0.7227860885168853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 336, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7132669067566587, 'min_weight_fraction_leaf': 0.09682728258065251}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.7538759689922481
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.648068669527897
[I 2024-04-15 13:59:38,460] Trial 14 finished with value: 0.6875118831760492 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.3790277944184374}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:38,747] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.25853971878279847, 'min_weight_fraction_leaf': 0.1136143317234711}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 13:59:39,571] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.12362405012814498, 'min_weight_fraction_leaf': 0.18949444225079395}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:40,484] Trial 17 finished with value: 0.7333650628805521 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8640754037508087, 'min_weight_fraction_leaf': 0.08300984976320161}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:43,373] Trial 18 finished with value: 0.7138187212932231 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.893843387841617, 'min_weight_fraction_leaf': 0.0012901863864347718}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6587982832618026
[I 2024-04-15 13:59:43,888] Trial 19 finished with value: 0.7057594207270395 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 173, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6462028944794036, 'min_weight_fraction_leaf': 0.24752940142621416}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:59:44,514] Trial 20 finished with value: 0.7323582709861934 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 214, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9046520586847226, 'min_weight_fraction_leaf': 0.15604495917089234}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:59:45,433] Trial 21 finished with value: 0.733056653279694 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8264846465847887, 'min_weight_fraction_leaf': 0.06531032832143097}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:46,330] Trial 22 finished with value: 0.7346870590959979 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8554939338437892, 'min_weight_fraction_leaf': 0.05912077213864973}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:47,748] Trial 23 finished with value: 0.7352841948632597 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 487, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6813559412681637, 'min_weight_fraction_leaf': 0.03807965277622394}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:49,031] Trial 24 finished with value: 0.7320605873920041 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7101858188995143, 'min_weight_fraction_leaf': 0.03414106493059247}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 13:59:50,189] Trial 25 finished with value: 0.727965007825656 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:59:55,077] Trial 26 finished with value: 0.7097917064892874 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7363157908211037, 'min_weight_fraction_leaf': 0.030609355115257964}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 13:59:56,124] Trial 27 finished with value: 0.7289930115925871 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.05966804358984962}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 13:59:57,611] Trial 28 finished with value: 0.727700523625848 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9547761993685097, 'min_weight_fraction_leaf': 0.18010884975569444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6716738197424893
[I 2024-04-15 13:59:57,945] Trial 29 finished with value: 0.7278903944963211 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 53, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6672466493035638, 'min_weight_fraction_leaf': 0.09570676535902678}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 13:59:59,134] Trial 30 finished with value: 0.7283637613256518 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.21525035641182588}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 14:00:00,261] Trial 31 finished with value: 0.7301852441402965 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8780867392507613, 'min_weight_fraction_leaf': 0.08053342835298444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 14:00:01,787] Trial 32 finished with value: 0.7270669981840107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8465161672872993, 'min_weight_fraction_leaf': 0.13728708040036253}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:00:02,785] Trial 33 finished with value: 0.7291276715364954 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7791575185731888, 'min_weight_fraction_leaf': 0.08782522649871717}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:00:03,759] Trial 34 finished with value: 0.732991669441196 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.0321950347302904}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 14:00:05,875] Trial 35 finished with value: 0.7285589865120596 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 462, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7484887897698851, 'min_weight_fraction_leaf': 0.11179394316240188}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 14:00:07,045] Trial 36 finished with value: 0.704782939479291 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 120, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5819516222091663, 'min_weight_fraction_leaf': 0.05929252020100452}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:00:07,603] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6894294877112123, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:00:08,325] Trial 38 finished with value: 0.6969977793569042 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6176423630852546, 'min_weight_fraction_leaf': 0.27842662148070446}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:00:10,443] Trial 39 finished with value: 0.7145032975216214 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4114486681290081, 'min_weight_fraction_leaf': 0.006316515579589441}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:00:11,261] Trial 40 finished with value: 0.7394420414645654 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.070818312691936}. Best is trial 40 with value: 0.7394420414645654.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:00:12,235] Trial 41 finished with value: 0.7402388542135694 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7929235954297236, 'min_weight_fraction_leaf': 0.06753409188567513}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 14:00:13,237] Trial 42 finished with value: 0.7385473158906132 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7814167764920316, 'min_weight_fraction_leaf': 0.053138807692614115}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.721030042918455
[I 2024-04-15 14:00:14,148] Trial 43 finished with value: 0.7526793316239683 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 342, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.0237916514620877}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:00:15,024] Trial 44 finished with value: 0.7517156174445475 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7903494194560798, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 14:00:15,992] Trial 45 finished with value: 0.75724249310961 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9975014761881965, 'min_weight_fraction_leaf': 0.01820664676789947}. Best is trial 45 with value: 0.75724249310961.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:16,783] Trial 46 finished with value: 0.7516108231937302 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9833287122666867, 'min_weight_fraction_leaf': 0.02167204729301097}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:00:19,610] Trial 47 finished with value: 0.7072551380763006 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 277, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9938409184868892, 'min_weight_fraction_leaf': 0.012424414465270794}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:00:21,175] Trial 48 finished with value: 0.736994195055912 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 315, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9943389290512517, 'min_weight_fraction_leaf': 0.024122723628498613}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6201716738197425
[I 2024-04-15 14:00:21,977] Trial 49 finished with value: 0.6871506500322846 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.943836768280026, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 14:00:22,706] Trial 50 finished with value: 0.738757879065195 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9218905769996524, 'min_weight_fraction_leaf': 0.017081546823995417}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:23,671] Trial 51 finished with value: 0.7587815706706135 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8006618362151878, 'min_weight_fraction_leaf': 0.0006942403087633227}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:24,549] Trial 52 finished with value: 0.7475219816321547 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7294591746589625, 'min_weight_fraction_leaf': 0.0016358111792067614}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:25,413] Trial 53 finished with value: 0.7566629550916705 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5353674654541881, 'min_weight_fraction_leaf': 0.0026771789807350996}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 14:00:26,230] Trial 54 finished with value: 0.7352011465498318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5280559833057176, 'min_weight_fraction_leaf': 0.039551718738544406}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 14:00:27,173] Trial 55 finished with value: 0.7336828402532702 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3722344587434572, 'min_weight_fraction_leaf': 0.019345288070128742}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 14:00:27,855] Trial 56 finished with value: 0.7370042171283777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5400588998582563, 'min_weight_fraction_leaf': 0.04313419866698206}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 14:00:28,789] Trial 57 finished with value: 0.7325789664550014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5822470231276546, 'min_weight_fraction_leaf': 0.10820490172022261}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 14:00:29,564] Trial 58 finished with value: 0.7420782648330935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.47947757991973655, 'min_weight_fraction_leaf': 0.019676870735375367}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:00:34,516] Trial 59 finished with value: 0.7082120978166874 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 402, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9629602149520176, 'min_weight_fraction_leaf': 5.104770246312437e-05}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:00:35,234] Trial 60 finished with value: 0.7315255752386033 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 266, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.04917170213673687}. Best is trial 51 with value: 0.7587815706706135.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-15 14:00:36,126] Trial 61 finished with value: 0.7467905765647049 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7262478375780741, 'min_weight_fraction_leaf': 0.0014391069076949321}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:37,126] Trial 62 finished with value: 0.7475583381073945 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8176070633016336, 'min_weight_fraction_leaf': 0.017513460534447932}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:38,000] Trial 63 finished with value: 0.7466925367529218 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9048655808252274, 'min_weight_fraction_leaf': 0.026324306931491667}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 14:00:38,961] Trial 64 finished with value: 0.7370190980741596 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8235728807014974, 'min_weight_fraction_leaf': 0.07647889290633725}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:39,786] Trial 65 finished with value: 0.7475730756320799 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8717939599515069, 'min_weight_fraction_leaf': 0.046903678085942646}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:00:40,551] Trial 66 finished with value: 0.7482897431748442 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8797774907667472, 'min_weight_fraction_leaf': 0.048960653209137665}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:00:41,165] Trial 67 finished with value: 0.7393805115631469 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9729538475019345, 'min_weight_fraction_leaf': 0.09677508382156286}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 14:00:41,921] Trial 68 finished with value: 0.7053000937674134 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9142124434676113, 'min_weight_fraction_leaf': 0.3293312145420018}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 14:00:42,730] Trial 69 finished with value: 0.7350965386026626 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8817438215622965, 'min_weight_fraction_leaf': 0.034436173984274676}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7381974248927039
[I 2024-04-15 14:00:43,657] Trial 70 finished with value: 0.7613284744465487 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470771316919997, 'min_weight_fraction_leaf': 0.05299254826291741}. Best is trial 70 with value: 0.7613284744465487.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7424892703862661
[I 2024-04-15 14:00:44,593] Trial 71 finished with value: 0.7638673522542814 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:00:45,652] Trial 72 finished with value: 0.7530816328485426 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9438070806786616, 'min_weight_fraction_leaf': 0.0719219098849957}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:00:46,758] Trial 73 finished with value: 0.7529399312925945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9476534872163854, 'min_weight_fraction_leaf': 0.07948506430889707}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 14:00:47,872] Trial 74 finished with value: 0.7416078997115878 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9315744574283523, 'min_weight_fraction_leaf': 0.12730293993691283}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:00:48,881] Trial 75 finished with value: 0.7537662190909693 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9538212906403223, 'min_weight_fraction_leaf': 0.07947418064331738}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 14:00:54,032] Trial 76 finished with value: 0.7089732912239908 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503206330661996, 'min_weight_fraction_leaf': 0.08332855281149479}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:00:55,115] Trial 77 finished with value: 0.736222548982041 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9563764400770771, 'min_weight_fraction_leaf': 0.15158139627292644}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:00:56,502] Trial 78 finished with value: 0.7474677305513714 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9184606416275723, 'min_weight_fraction_leaf': 0.10966234237102679}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:00:57,666] Trial 79 finished with value: 0.7513105165834996 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8509706901999897, 'min_weight_fraction_leaf': 0.07437080570205526}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 14:00:58,958] Trial 80 finished with value: 0.7250348087736878 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9986660238693948, 'min_weight_fraction_leaf': 0.16662237313004993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 14:01:00,939] Trial 81 finished with value: 0.7572071277415792 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9698042200030538, 'min_weight_fraction_leaf': 0.059098984023617004}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:01:02,527] Trial 82 finished with value: 0.7514553752203057 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9681006428937893, 'min_weight_fraction_leaf': 0.09188576940897883}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 14:01:04,073] Trial 83 finished with value: 0.7580508863024411 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.900953067564881, 'min_weight_fraction_leaf': 0.06238575631317688}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 14:01:05,638] Trial 84 finished with value: 0.7603690354420299 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981565134422631, 'min_weight_fraction_leaf': 0.055911383060435194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7167381974248928
[I 2024-04-15 14:01:06,918] Trial 85 finished with value: 0.7514701127449911 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8908313295588716, 'min_weight_fraction_leaf': 0.05754237849545954}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 14:01:08,016] Trial 86 finished with value: 0.7604986057242595 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9139139944038005, 'min_weight_fraction_leaf': 0.06479300875481753}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 14:01:09,195] Trial 87 finished with value: 0.7619731232898213 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.908648262335172, 'min_weight_fraction_leaf': 0.055676683204352095}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:01:16,082] Trial 88 finished with value: 0.7081331135870429 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 457, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8593524715534154, 'min_weight_fraction_leaf': 0.20522107340967194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 14:01:17,895] Trial 89 finished with value: 0.7612669180968402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9096225926270616, 'min_weight_fraction_leaf': 0.06086475861021993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:01:19,545] Trial 90 finished with value: 0.7482861622509297 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9036341058690905, 'min_weight_fraction_leaf': 0.10323471635782432}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7296137339055794
[I 2024-04-15 14:01:20,838] Trial 91 finished with value: 0.7579312275401037 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.930984837991578, 'min_weight_fraction_leaf': 0.06281312587463944}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-15 14:01:22,267] Trial 92 finished with value: 0.7465445210352575 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.837687225987731, 'min_weight_fraction_leaf': 0.03575880044104557}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 14:01:23,921] Trial 93 finished with value: 0.7562581510868437 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9274363792849041, 'min_weight_fraction_leaf': 0.0661014687608754}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7339055793991416
[I 2024-04-15 14:01:25,458] Trial 94 finished with value: 0.7581413668716293 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8978558580565509, 'min_weight_fraction_leaf': 0.04353249947872927}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.703862660944206
[I 2024-04-15 14:01:26,737] Trial 95 finished with value: 0.7464935540221674 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8979178686532339, 'min_weight_fraction_leaf': 0.09188808281710414}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:01:28,044] Trial 96 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8782096526369123, 'min_weight_fraction_leaf': 0.4423900052068913}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 14:01:29,239] Trial 97 finished with value: 0.707119307000758 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 467, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7568822772464855, 'min_weight_fraction_leaf': 0.12390809358298693}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7253218884120172
[I 2024-04-15 14:01:30,515] Trial 98 finished with value: 0.7595501798994153 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8379792984882093, 'min_weight_fraction_leaf': 0.04873278208701805}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7756653992395437

[I 2024-04-15 14:01:31,811] A new study created in memory with name: no-name-2bd9ffaa-ef28-4389-8543-2c974ec2e7d0

Fold 5 C-index: 0.6995708154506438
[I 2024-04-15 14:01:31,801] Trial 99 finished with value: 0.7454360752058654 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8115869270579641, 'min_weight_fraction_leaf': 0.046153664833883515}. Best is trial 71 with value: 0.7638673522542814.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.7638673522542814], datetime_start=datetime.datetime(2024, 4, 15, 14, 0, 43, 663995), datetime_complete=datetime.datetime(2024, 4, 15, 14, 0, 44, 592831), params={'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for C-index:
 0.7638673522542814

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23536610912753758
Fold 2 IBS: 0.20145762246413637
Fold 3 IBS: 0.20393081537250338
Fold 4 IBS: 0.21602715770992703
Fold 5 IBS: 0.2123183673596273
[I 2024-04-15 14:01:36,278] Trial 0 finished with value: 0.21382001440674636 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-15 14:01:42,890] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24081748643654036
Fold 2 IBS: 0.21713451086140778
Fold 3 IBS: 0.21706845078329945
Fold 4 IBS: 0.22785653322218774
Fold 5 IBS: 0.2212935208368412
[I 2024-04-15 14:01:47,802] Trial 2 finished with value: 0.22483410042805532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24130149411697235
Fold 2 IBS: 0.2155958186901399
Fold 3 IBS: 0.21794780991257648
Fold 4 IBS: 0.2281735359031675
Fold 5 IBS: 0.2213413510348227
[I 2024-04-15 14:01:49,417] Trial 3 finished with value: 0.22487200193153578 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-15 14:01:53,075] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-15 14:01:54,838] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23588196908877218
Fold 2 IBS: 0.20300039081654195
Fold 3 IBS: 0.2032173161135722
Fold 4 IBS: 0.21660656247722504
Fold 5 IBS: 0.21313591685519812
[I 2024-04-15 14:01:58,485] Trial 6 finished with value: 0.21436843107026188 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23825239046762217
Fold 2 IBS: 0.20781792017117767
Fold 3 IBS: 0.20896423148161078
Fold 4 IBS: 0.2197851504145311
Fold 5 IBS: 0.21653670443025383
[I 2024-04-15 14:02:00,796] Trial 7 finished with value: 0.2182712793930391 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23441021296278977
Fold 2 IBS: 0.21668396635030526
Fold 3 IBS: 0.22051379811268176
Fold 4 IBS: 0.22841790837130418
Fold 5 IBS: 0.21971786351985503
[I 2024-04-15 14:02:01,280] Trial 8 finished with value: 0.2239487498633872 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24426590657878128
Fold 2 IBS: 0.22769375627843935
Fold 3 IBS: 0.22591830688186657
Fold 4 IBS: 0.23810899013034692
Fold 5 IBS: 0.22806252164373667
[I 2024-04-15 14:02:06,073] Trial 9 finished with value: 0.23280989630263416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-15 14:02:09,800] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.2366414313349858
Fold 2 IBS: 0.21027597932345765
Fold 3 IBS: 0.21371008388168403
Fold 4 IBS: 0.22126964028612253
Fold 5 IBS: 0.2183525448310651
[I 2024-04-15 14:02:12,994] Trial 11 finished with value: 0.22004993593146302 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23579256852371847
Fold 2 IBS: 0.19568412454984113
Fold 3 IBS: 0.20040747067699977
Fold 4 IBS: 0.21186400025265303
Fold 5 IBS: 0.20966969871024252
[I 2024-04-15 14:02:16,962] Trial 12 finished with value: 0.210683572542691 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2370011165638282
Fold 2 IBS: 0.21123276228104673
Fold 3 IBS: 0.21121286711017057
Fold 4 IBS: 0.2241696763859363
Fold 5 IBS: 0.21822141136063145
[I 2024-04-15 14:02:20,787] Trial 13 finished with value: 0.22036756674032265 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23685780568086942
Fold 2 IBS: 0.2126468337858846
Fold 3 IBS: 0.2143772281757236
Fold 4 IBS: 0.22443452861645802
Fold 5 IBS: 0.21899252589159815
[I 2024-04-15 14:02:24,071] Trial 14 finished with value: 0.22146178443010672 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.210683572542691.

Fold 1 IBS: 0.23656743298208832
Fold 2 IBS: 0.21264947915533935
Fold 3 IBS: 0.21321328704497466
Fold 4 IBS: 0.22340910553399146
Fold 5 IBS: 0.21947803887476586
[I 2024-04-15 14:02:26,559] Trial 15 finished with value: 0.22106346871823193 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24483198345747628
Fold 2 IBS: 0.2302859276502996
Fold 3 IBS: 0.2285602592982639
Fold 4 IBS: 0.24045635643173324
Fold 5 IBS: 0.22930909941169325
[I 2024-04-15 14:02:30,789] Trial 16 finished with value: 0.23468872524989326 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2357109983223001
Fold 2 IBS: 0.20494805543099556
Fold 3 IBS: 0.21371005693600734
Fold 4 IBS: 0.21914551084001152
Fold 5 IBS: 0.21764479743708764
[I 2024-04-15 14:02:33,806] Trial 17 finished with value: 0.21823188379328046 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-15 14:02:35,362] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23569889105742511
Fold 2 IBS: 0.21036165282675318
Fold 3 IBS: 0.2110188939735362
Fold 4 IBS: 0.2231729444607325
Fold 5 IBS: 0.21764713763142923
[I 2024-04-15 14:02:39,376] Trial 19 finished with value: 0.21957990398997523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2260422981383027
Fold 2 IBS: 0.21628115911706547
Fold 3 IBS: 0.22894435879157846
Fold 4 IBS: 0.22705631591030262
Fold 5 IBS: 0.2234837877858094
[I 2024-04-15 14:02:39,679] Trial 20 finished with value: 0.22436158394861172 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23626217363246013
Fold 2 IBS: 0.20265333339770739
Fold 3 IBS: 0.2030759075715199
Fold 4 IBS: 0.21605001910251603
Fold 5 IBS: 0.2129636719520293
[I 2024-04-15 14:02:43,880] Trial 21 finished with value: 0.21420102113124656 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23496608578657435
Fold 2 IBS: 0.1999430054098381
Fold 3 IBS: 0.201275593836101
Fold 4 IBS: 0.21418253302811457
Fold 5 IBS: 0.21127196072648274
[I 2024-04-15 14:02:48,777] Trial 22 finished with value: 0.21232783575742217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23555557011049139
Fold 2 IBS: 0.19236878946561603
Fold 3 IBS: 0.19926908881992766
Fold 4 IBS: 0.21084942333238568
Fold 5 IBS: 0.2081240396802252
[I 2024-04-15 14:02:54,044] Trial 23 finished with value: 0.20923338228172916 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23607695303226134
Fold 2 IBS: 0.203493581017792
Fold 3 IBS: 0.20360358222095004
Fold 4 IBS: 0.21361938713575862
Fold 5 IBS: 0.2127155595148638
[I 2024-04-15 14:02:59,501] Trial 24 finished with value: 0.21390181258432514 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23810448610418447
Fold 2 IBS: 0.20850297794887437
Fold 3 IBS: 0.20884091287918746
Fold 4 IBS: 0.21832663743927483
Fold 5 IBS: 0.2167935048771244
[I 2024-04-15 14:03:04,452] Trial 25 finished with value: 0.2181137038497291 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2366073194702186
Fold 2 IBS: 0.2094968403110053
Fold 3 IBS: 0.20963379712724098
Fold 4 IBS: 0.2223187457140648
Fold 5 IBS: 0.21676394473697067
[I 2024-04-15 14:03:11,909] Trial 26 finished with value: 0.21896412947190008 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23608107276763018
Fold 2 IBS: 0.21036141351373328
Fold 3 IBS: 0.21169155072466916
Fold 4 IBS: 0.22331018888988935
Fold 5 IBS: 0.2177506938697703
[I 2024-04-15 14:03:16,807] Trial 27 finished with value: 0.21983898395313844 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23715637039941884
Fold 2 IBS: 0.2120572412765648
Fold 3 IBS: 0.21620854589832805
Fold 4 IBS: 0.2250681900188581
Fold 5 IBS: 0.22134392576904316
[I 2024-04-15 14:03:20,780] Trial 28 finished with value: 0.22236685467244258 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24167838631766778
Fold 2 IBS: 0.22069051827263042
Fold 3 IBS: 0.22031739328406955
Fold 4 IBS: 0.23288818140652423
Fold 5 IBS: 0.22471508602895093
[I 2024-04-15 14:03:23,863] Trial 29 finished with value: 0.22805791306196857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.2369623605519169
Fold 2 IBS: 0.2015664827514855
Fold 3 IBS: 0.2044196732107329
Fold 4 IBS: 0.2152719150958778
Fold 5 IBS: 0.2123358137500061
[I 2024-04-15 14:03:28,387] Trial 30 finished with value: 0.21411124907200385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23451695205118067
Fold 2 IBS: 0.19751010562426458
Fold 3 IBS: 0.2027198084019687
Fold 4 IBS: 0.21411412044401185
Fold 5 IBS: 0.2111761169753505
[I 2024-04-15 14:03:32,623] Trial 31 finished with value: 0.21200742069935527 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.923666057752446, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2351025999648965
Fold 2 IBS: 0.1949158359424477
Fold 3 IBS: 0.20111115549804756
Fold 4 IBS: 0.21180546961424107
Fold 5 IBS: 0.20942511704648153
[I 2024-04-15 14:03:36,577] Trial 32 finished with value: 0.2104720356132229 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.939007534925735, 'min_weight_fraction_leaf': 0.056106269226335825}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2359807363001553
Fold 2 IBS: 0.20390144524422224
Fold 3 IBS: 0.20692223621119946
Fold 4 IBS: 0.2180339829065641
Fold 5 IBS: 0.21348267427916112
[I 2024-04-15 14:03:40,435] Trial 33 finished with value: 0.21566421498826044 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9138848353483187, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23760045008166628
Fold 2 IBS: 0.1836854003772293
Fold 3 IBS: 0.20658859037809638
Fold 4 IBS: 0.21356225516393262
Fold 5 IBS: 0.2080473806120064
[I 2024-04-15 14:03:45,169] Trial 34 finished with value: 0.2098968153225862 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.06204686171902169}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23705554587631616
Fold 2 IBS: 0.18409383187630057
Fold 3 IBS: 0.20774926569595484
Fold 4 IBS: 0.21266700404602018
Fold 5 IBS: 0.20816809551656013
[I 2024-04-15 14:03:50,981] Trial 35 finished with value: 0.2099467486022304 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8327847526324277, 'min_weight_fraction_leaf': 0.055940476394666754}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23566967538262615
Fold 2 IBS: 0.18498818375621254
Fold 3 IBS: 0.2076181431218228
Fold 4 IBS: 0.21248969655065036
Fold 5 IBS: 0.20727223939702627
[I 2024-04-15 14:03:56,996] Trial 36 finished with value: 0.20960758764166765 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827098326399153, 'min_weight_fraction_leaf': 0.07015937717166007}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2322804097655011
Fold 2 IBS: 0.1904595107494953
Fold 3 IBS: 0.20654496901893055
Fold 4 IBS: 0.21029065871150715
Fold 5 IBS: 0.20940168079092789
[I 2024-04-15 14:04:03,578] Trial 37 finished with value: 0.20979544580727238 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8333567609683693, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23402986510699297
Fold 2 IBS: 0.20551834233097463
Fold 3 IBS: 0.21448459324894656
Fold 4 IBS: 0.21983535419793537
Fold 5 IBS: 0.21738979632924899
[I 2024-04-15 14:04:08,364] Trial 38 finished with value: 0.2182515902428197 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 349, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.823414916934049, 'min_weight_fraction_leaf': 0.22365568672391764}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23303653525127266
Fold 2 IBS: 0.19614443640526336
Fold 3 IBS: 0.20759014709806334
Fold 4 IBS: 0.21278979581525073
Fold 5 IBS: 0.2115153572009253
[I 2024-04-15 14:04:13,833] Trial 39 finished with value: 0.21221525435415506 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7688812089462244, 'min_weight_fraction_leaf': 0.13832319540130408}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24085544671476855
Fold 2 IBS: 0.21881433431452443
Fold 3 IBS: 0.2205550472397075
Fold 4 IBS: 0.23189796849220526
Fold 5 IBS: 0.22387717931221346
[I 2024-04-15 14:04:19,715] Trial 40 finished with value: 0.22719999521468384 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7387886455857571, 'min_weight_fraction_leaf': 0.2794340971992336}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23558729160195155
Fold 2 IBS: 0.18499721054651033
Fold 3 IBS: 0.2078176191769497
Fold 4 IBS: 0.21254959703326678
Fold 5 IBS: 0.20740208695361273
[I 2024-04-15 14:04:25,489] Trial 41 finished with value: 0.20967076106245824 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 459, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8304297502532995, 'min_weight_fraction_leaf': 0.06567312882813131}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23638956396269079
Fold 2 IBS: 0.18490789291091672
Fold 3 IBS: 0.20644644482157795
Fold 4 IBS: 0.21257693995308247
Fold 5 IBS: 0.20732761178411305
[I 2024-04-15 14:04:31,190] Trial 42 finished with value: 0.20952969068647617 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 450, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7982039779530783, 'min_weight_fraction_leaf': 0.07186658790260646}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23274337848255236
Fold 2 IBS: 0.1929272244249927
Fold 3 IBS: 0.20732501652108193
Fold 4 IBS: 0.21144242883441275
Fold 5 IBS: 0.20983249626579628
[I 2024-04-15 14:04:36,764] Trial 43 finished with value: 0.21085410890576722 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 440, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.1211117088142}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2410193325812047
Fold 2 IBS: 0.2226476644714021
Fold 3 IBS: 0.22105022637397118
Fold 4 IBS: 0.23115256969605635
Fold 5 IBS: 0.2240981533222132
[I 2024-04-15 14:04:42,267] Trial 44 finished with value: 0.2279935892889695 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6979907483981592, 'min_weight_fraction_leaf': 0.16526223863734468}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.23247724033039832
Fold 2 IBS: 0.18748554961121114
Fold 3 IBS: 0.2090170455982855
Fold 4 IBS: 0.207742375469341
Fold 5 IBS: 0.20889347688505747
[I 2024-04-15 14:04:44,234] Trial 45 finished with value: 0.2091231375788587 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8505483502716148, 'min_weight_fraction_leaf': 0.09794633817349793}. Best is trial 45 with value: 0.2091231375788587.
Fold 1 IBS: 0.2314286160573986
Fold 2 IBS: 0.1860889745854672
Fold 3 IBS: 0.20638267011548084
Fold 4 IBS: 0.20884587453459477
Fold 5 IBS: 0.20805701088484838
[I 2024-04-15 14:04:46,111] Trial 46 finished with value: 0.20816062923555795 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7709286828220481, 'min_weight_fraction_leaf': 0.07995724348415684}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23766776108374213
Fold 2 IBS: 0.21002348979145327
Fold 3 IBS: 0.21765068090817657
Fold 4 IBS: 0.22280193059668152
Fold 5 IBS: 0.21940264282312605
[I 2024-04-15 14:04:47,843] Trial 47 finished with value: 0.22150930104063588 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 127, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7682715671327377, 'min_weight_fraction_leaf': 0.08646740062265149}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23713247312937227
Fold 2 IBS: 0.1864152472719121
Fold 3 IBS: 0.20569921628056348
Fold 4 IBS: 0.21202213139980625
Fold 5 IBS: 0.2062034346638877
[I 2024-04-15 14:04:50,279] Trial 48 finished with value: 0.20949450054910837 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 186, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8579998757196492, 'min_weight_fraction_leaf': 0.022631912267245}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2401019704407054
Fold 2 IBS: 0.20664694277509515
Fold 3 IBS: 0.20269468295254925
Fold 4 IBS: 0.2190769330154152
Fold 5 IBS: 0.21529320315539308
[I 2024-04-15 14:04:52,671] Trial 49 finished with value: 0.2167627464678316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 176, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.535541626399398, 'min_weight_fraction_leaf': 0.02410725915835375}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23775614182380903
Fold 2 IBS: 0.20743414808900665
Fold 3 IBS: 0.20687718864416932
Fold 4 IBS: 0.21905338149069295
Fold 5 IBS: 0.21496321205066113
[I 2024-04-15 14:04:54,197] Trial 50 finished with value: 0.21721681441966784 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 90, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8724086164488271, 'min_weight_fraction_leaf': 0.04430715227744478}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23333408320563848
Fold 2 IBS: 0.18618334408777154
Fold 3 IBS: 0.2054922876895997
Fold 4 IBS: 0.2095428614888614
Fold 5 IBS: 0.2081255374544523
[I 2024-04-15 14:04:57,547] Trial 51 finished with value: 0.2085356227852647 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 157, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7607239465677439, 'min_weight_fraction_leaf': 0.0768704777706238}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23294009669574758
Fold 2 IBS: 0.18886644911422001
Fold 3 IBS: 0.20450870840640553
Fold 4 IBS: 0.2098663013569692
Fold 5 IBS: 0.2093242311139224
[I 2024-04-15 14:05:02,618] Trial 52 finished with value: 0.2091011573374529 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 215, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6812726944311738, 'min_weight_fraction_leaf': 0.0924784870388018}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23340127695530247
Fold 2 IBS: 0.19037609007747622
Fold 3 IBS: 0.20443462122815134
Fold 4 IBS: 0.20971338145144297
Fold 5 IBS: 0.20931781265162946
[I 2024-04-15 14:05:06,166] Trial 53 finished with value: 0.2094486364728005 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 224, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6963870551875947, 'min_weight_fraction_leaf': 0.10563773255020543}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23338966290283988
Fold 2 IBS: 0.19138513453127515
Fold 3 IBS: 0.20331794017233815
Fold 4 IBS: 0.21130675152530337
Fold 5 IBS: 0.2105461957704023
[I 2024-04-15 14:05:09,789] Trial 54 finished with value: 0.20998913698043178 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6719877047239909, 'min_weight_fraction_leaf': 0.0997398012429799}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23593555870849725
Fold 2 IBS: 0.20801826761705877
Fold 3 IBS: 0.20827021219395564
Fold 4 IBS: 0.21956943852396218
Fold 5 IBS: 0.21586303213321972
[I 2024-04-15 14:05:13,226] Trial 55 finished with value: 0.21753130183533873 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7290878996075589, 'min_weight_fraction_leaf': 0.1329691849961646}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24666819701072148
Fold 2 IBS: 0.23210773115939679
Fold 3 IBS: 0.22932364190291274
Fold 4 IBS: 0.24152405514050876
Fold 5 IBS: 0.2303157661686399
[I 2024-04-15 14:05:15,900] Trial 56 finished with value: 0.23598787827643591 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5975963219999111, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23492638070785768
Fold 2 IBS: 0.21240221048192362
Fold 3 IBS: 0.2168912407987811
Fold 4 IBS: 0.22754745889623634
Fold 5 IBS: 0.22089364796872285
[I 2024-04-15 14:05:18,013] Trial 57 finished with value: 0.22253218777070433 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 128, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6735255380721511, 'min_weight_fraction_leaf': 0.18708850621022327}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23531750054242687
Fold 2 IBS: 0.2077683628397722
Fold 3 IBS: 0.21364739027613322
Fold 4 IBS: 0.21979565810435922
Fold 5 IBS: 0.21840068135164575
[I 2024-04-15 14:05:21,995] Trial 58 finished with value: 0.21898591862286745 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 238, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.15746351073381912}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24661384524722246
Fold 2 IBS: 0.23215291198462218
Fold 3 IBS: 0.22952739882394438
Fold 4 IBS: 0.24152565273881768
Fold 5 IBS: 0.2303053694496521
[I 2024-04-15 14:05:26,305] Trial 59 finished with value: 0.23602503564885174 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.75796811576398, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 46 with value: 0.20816062923555795.

Fold 1 IBS: 0.2376464824369693
Fold 2 IBS: 0.21593994734134395
Fold 3 IBS: 0.22177987321764975
Fold 4 IBS: 0.22790863488656224
Fold 5 IBS: 0.2205529164521157
[I 2024-04-15 14:05:27,604] Trial 60 finished with value: 0.22476557086692814 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 74, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6041879821929975, 'min_weight_fraction_leaf': 0.1056236625824671}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23781793031064252
Fold 2 IBS: 0.1862495208476139
Fold 3 IBS: 0.20248456745784213
Fold 4 IBS: 0.21234711020159586
Fold 5 IBS: 0.2076972639565933
[I 2024-04-15 14:05:30,932] Trial 61 finished with value: 0.20931927855485752 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 197, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7101126073432302, 'min_weight_fraction_leaf': 0.013226300887269365}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2382367270174128
Fold 2 IBS: 0.18483164704435992
Fold 3 IBS: 0.20455018380786597
Fold 4 IBS: 0.2115954964542311
Fold 5 IBS: 0.20832518097782782
[I 2024-04-15 14:05:33,979] Trial 62 finished with value: 0.20950784706033954 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7066561911530848, 'min_weight_fraction_leaf': 0.012902964688040898}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23653797420874464
Fold 2 IBS: 0.18352585769961322
Fold 3 IBS: 0.20365755657663714
Fold 4 IBS: 0.20917655609037722
Fold 5 IBS: 0.20729793495414095
[I 2024-04-15 14:05:36,142] Trial 63 finished with value: 0.20803917590590265 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 148, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6435418239181828, 'min_weight_fraction_leaf': 0.046981576659506384}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.2376440714946851
Fold 2 IBS: 0.18154571059609376
Fold 3 IBS: 0.20148827866234856
Fold 4 IBS: 0.21485752658604737
Fold 5 IBS: 0.21193720419679402
[I 2024-04-15 14:05:38,177] Trial 64 finished with value: 0.20949455830719374 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6558453673842368, 'min_weight_fraction_leaf': 0.0017360883857289438}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24069140178630108
Fold 2 IBS: 0.21023884738343832
Fold 3 IBS: 0.20819592567054473
Fold 4 IBS: 0.22032685614631106
Fold 5 IBS: 0.2181378139835771
[I 2024-04-15 14:05:40,144] Trial 65 finished with value: 0.21951816899403448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6369381520536594, 'min_weight_fraction_leaf': 0.04630739996813268}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24662572908345176
Fold 2 IBS: 0.2321190214638095
Fold 3 IBS: 0.22943780141623776
Fold 4 IBS: 0.2415441728621753
Fold 5 IBS: 0.2302929916244345
[I 2024-04-15 14:05:42,600] Trial 66 finished with value: 0.23600394329002175 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 190, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7534591387104144, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23761253968101
Fold 2 IBS: 0.19333058518344354
Fold 3 IBS: 0.19763843228218964
Fold 4 IBS: 0.2100557032515617
Fold 5 IBS: 0.208391029584297
[I 2024-04-15 14:05:44,174] Trial 67 finished with value: 0.20940565799650038 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 111, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7140591797427468, 'min_weight_fraction_leaf': 0.0380146506503018}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23568784825771597
Fold 2 IBS: 0.19836028806772887
Fold 3 IBS: 0.20225664393852164
Fold 4 IBS: 0.21479439327398367
Fold 5 IBS: 0.21109075078575282
[I 2024-04-15 14:05:46,432] Trial 68 finished with value: 0.21243798486474058 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 168, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7866638182428198, 'min_weight_fraction_leaf': 0.08748663516762165}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23356744505088914
Fold 2 IBS: 0.1834363879714103
Fold 3 IBS: 0.207688591468538
Fold 4 IBS: 0.20411915061999797
Fold 5 IBS: 0.21081229591952125
[I 2024-04-15 14:05:47,635] Trial 69 finished with value: 0.20792477420607133 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 78, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6633577858466918, 'min_weight_fraction_leaf': 0.05378179190948057}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23425832559812115
Fold 2 IBS: 0.1874883919439577
Fold 3 IBS: 0.20956087508825158
Fold 4 IBS: 0.20966146089051388
Fold 5 IBS: 0.21197029878987708
[I 2024-04-15 14:05:48,437] Trial 70 finished with value: 0.21058787046214428 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 46, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.609138718062076, 'min_weight_fraction_leaf': 0.08081693575379295}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23180288969924676
Fold 2 IBS: 0.18284953833260828
Fold 3 IBS: 0.20816697020659303
Fold 4 IBS: 0.20634477989340283
Fold 5 IBS: 0.2066720406825964
[I 2024-04-15 14:05:49,442] Trial 71 finished with value: 0.20716724376288945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24034476073822214
Fold 2 IBS: 0.18987915865551205
Fold 3 IBS: 0.2035631310131893
Fold 4 IBS: 0.21033288060199645
Fold 5 IBS: 0.20723055719361239
[I 2024-04-15 14:05:50,425] Trial 72 finished with value: 0.21027009764050644 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 64, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5683034340032609, 'min_weight_fraction_leaf': 0.04646174961182159}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2299054630450867
Fold 2 IBS: 0.19773469146740125
Fold 3 IBS: 0.19034097643724923
Fold 4 IBS: 0.22944964628361184
Fold 5 IBS: 0.2389286128541861
[I 2024-04-15 14:05:50,667] Trial 73 finished with value: 0.217271878017507 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.054429859852659815}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2303167286243434
Fold 2 IBS: 0.19516700665987674
Fold 3 IBS: 0.20660685643983331
Fold 4 IBS: 0.20899892281373353
Fold 5 IBS: 0.2066488418873486
[I 2024-04-15 14:05:51,286] Trial 74 finished with value: 0.20954767128502713 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 29, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7480880522886367, 'min_weight_fraction_leaf': 0.07511258593340842}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23693321208405524
Fold 2 IBS: 0.19000973925047765
Fold 3 IBS: 0.20243881773088923
Fold 4 IBS: 0.2110667431713562
Fold 5 IBS: 0.20765848231427028
[I 2024-04-15 14:05:52,816] Trial 75 finished with value: 0.20962139891020973 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.49599352625156035, 'min_weight_fraction_leaf': 0.03138093454428739}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2375162774090104
Fold 2 IBS: 0.21696007860868566
Fold 3 IBS: 0.2199964189465905
Fold 4 IBS: 0.2298197447784768
Fold 5 IBS: 0.2208032877666601
[I 2024-04-15 14:05:54,020] Trial 76 finished with value: 0.2250191615018847 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 81, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6498539620686062, 'min_weight_fraction_leaf': 0.1107936452967258}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.234645557683981
Fold 2 IBS: 0.19308386846985393
Fold 3 IBS: 0.21042866351417217
Fold 4 IBS: 0.213955157478479
Fold 5 IBS: 0.20941746392682734
[I 2024-04-15 14:05:55,074] Trial 77 finished with value: 0.21230614221466268 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 53, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6219886854752814, 'min_weight_fraction_leaf': 0.0881530598041391}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23208979344503086
Fold 2 IBS: 0.19134551959096457
Fold 3 IBS: 0.20969730607101159
Fold 4 IBS: 0.21155535213663088
Fold 5 IBS: 0.21094666727963496
[I 2024-04-15 14:05:57,413] Trial 78 finished with value: 0.21112692770465458 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8975377298130277, 'min_weight_fraction_leaf': 0.05792949206602531}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24656769908913287
Fold 2 IBS: 0.23207473314584195
Fold 3 IBS: 0.22956209752209408
Fold 4 IBS: 0.24131766392563656
Fold 5 IBS: 0.22974225690563504
[I 2024-04-15 14:05:59,356] Trial 79 finished with value: 0.2358528901176681 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.15079098086778978}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23398194286521523
Fold 2 IBS: 0.2042478759118354
Fold 3 IBS: 0.2149027538028443
Fold 4 IBS: 0.21138634120370936
Fold 5 IBS: 0.21509744244742898
[I 2024-04-15 14:06:00,100] Trial 80 finished with value: 0.21592327124620664 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 34, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.680202266270148, 'min_weight_fraction_leaf': 0.13027280080194392}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23821133340721135
Fold 2 IBS: 0.18697626156811917
Fold 3 IBS: 0.2025556131339658
Fold 4 IBS: 0.21248041803374165
Fold 5 IBS: 0.21006237384648405
[I 2024-04-15 14:06:02,646] Trial 81 finished with value: 0.2100571999979044 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7059723708255974, 'min_weight_fraction_leaf': 0.011081957753211642}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2354434465673004
Fold 2 IBS: 0.18590060696281396
Fold 3 IBS: 0.20237660521219805
Fold 4 IBS: 0.21289282208945418
Fold 5 IBS: 0.2079334303868527
[I 2024-04-15 14:06:05,505] Trial 82 finished with value: 0.20890938224372385 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7322939853383122, 'min_weight_fraction_leaf': 0.030199179896950257}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2391213827919915
Fold 2 IBS: 0.18339377899057588
Fold 3 IBS: 0.20630651107397327
Fold 4 IBS: 0.21414237142238046
Fold 5 IBS: 0.20709539863236437
[I 2024-04-15 14:06:08,815] Trial 83 finished with value: 0.2100118885822571 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 249, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8082167579651034, 'min_weight_fraction_leaf': 0.030688122459232033}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2338134437703758
Fold 2 IBS: 0.18585229495562317
Fold 3 IBS: 0.20232554114967682
Fold 4 IBS: 0.20935878852735582
Fold 5 IBS: 0.20693004752390112
[I 2024-04-15 14:06:11,259] Trial 84 finished with value: 0.20765602318538656 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7722055241934203, 'min_weight_fraction_leaf': 0.06706989383850837}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2325404292841733
Fold 2 IBS: 0.2037796259632883
Fold 3 IBS: 0.21285222741885748
Fold 4 IBS: 0.21748519543805853
Fold 5 IBS: 0.21558014668487166
[I 2024-04-15 14:06:14,000] Trial 85 finished with value: 0.21644752495784986 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 209, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8080700094351241, 'min_weight_fraction_leaf': 0.07313973736441735}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23185610825625882
Fold 2 IBS: 0.1883838499173774
Fold 3 IBS: 0.2069558256748436
Fold 4 IBS: 0.2056460896941882
Fold 5 IBS: 0.20834833869947297
[I 2024-04-15 14:06:16,450] Trial 86 finished with value: 0.2082380424484282 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 179, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7797829686997926, 'min_weight_fraction_leaf': 0.0930692046392031}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23732262587143452
Fold 2 IBS: 0.18516284894711776
Fold 3 IBS: 0.20293194154297275
Fold 4 IBS: 0.20976950466294828
Fold 5 IBS: 0.20684702854669929
[I 2024-04-15 14:06:18,865] Trial 87 finished with value: 0.2084067899142345 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 182, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7347045490916186, 'min_weight_fraction_leaf': 0.0569064501216709}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23610457243620386
Fold 2 IBS: 0.1843646040116617
Fold 3 IBS: 0.2038780530044773
Fold 4 IBS: 0.2105249290335657
Fold 5 IBS: 0.20647024537168604
[I 2024-04-15 14:06:21,242] Trial 88 finished with value: 0.20826848077151894 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7454117372266992, 'min_weight_fraction_leaf': 0.05974548060098256}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23977374886110586
Fold 2 IBS: 0.20834445745005828
Fold 3 IBS: 0.2081295030562698
Fold 4 IBS: 0.22184631620912326
Fold 5 IBS: 0.21759905094032755
[I 2024-04-15 14:06:23,622] Trial 89 finished with value: 0.21913861530337697 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7540347885452335, 'min_weight_fraction_leaf': 0.06459414509901623}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23900229487413618
Fold 2 IBS: 0.1829989350900894
Fold 3 IBS: 0.20504008460974205
Fold 4 IBS: 0.21135329415618298
Fold 5 IBS: 0.20658610615550185
[I 2024-04-15 14:06:25,010] Trial 90 finished with value: 0.20899614297713048 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 95, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7812194815989179, 'min_weight_fraction_leaf': 0.052583924158953604}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23336269917153504
Fold 2 IBS: 0.18793910685243745
Fold 3 IBS: 0.20227191981491185
Fold 4 IBS: 0.2126322523584538
Fold 5 IBS: 0.20891055719221097
[I 2024-04-15 14:06:28,444] Trial 91 finished with value: 0.2090233070779098 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7343789509732842, 'min_weight_fraction_leaf': 0.034512973636926236}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23849245554801698
Fold 2 IBS: 0.18514480626810045
Fold 3 IBS: 0.2021086406752317
Fold 4 IBS: 0.21479834430066197
Fold 5 IBS: 0.20909254443799166
[I 2024-04-15 14:06:31,091] Trial 92 finished with value: 0.20992735824600056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7636505288647887, 'min_weight_fraction_leaf': 0.022561082303242087}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23712661813293098
Fold 2 IBS: 0.1851768236866079
Fold 3 IBS: 0.20432880761759306
Fold 4 IBS: 0.2118089074273193
Fold 5 IBS: 0.20725293903536335
[I 2024-04-15 14:06:33,871] Trial 93 finished with value: 0.20913881917996288 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 195, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.780594325886568, 'min_weight_fraction_leaf': 0.06660760570218983}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23313202103339004
Fold 2 IBS: 0.19197759007192453
Fold 3 IBS: 0.2044094595924962
Fold 4 IBS: 0.20966584275861216
Fold 5 IBS: 0.211313413556971
[I 2024-04-15 14:06:35,592] Trial 94 finished with value: 0.21009966540267877 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 120, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5855639769841374, 'min_weight_fraction_leaf': 0.08355403368257994}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23520267938727427
Fold 2 IBS: 0.20116425107298522
Fold 3 IBS: 0.20510259876427595
Fold 4 IBS: 0.2176827586444227
Fold 5 IBS: 0.21292731974141504
[I 2024-04-15 14:06:38,485] Trial 95 finished with value: 0.21441592152207462 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8103082949117716, 'min_weight_fraction_leaf': 0.11381886996294271}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2366963489001733
Fold 2 IBS: 0.1837117121259892
Fold 3 IBS: 0.20226694531049833
Fold 4 IBS: 0.21335021541537497
Fold 5 IBS: 0.20661189736952593
[I 2024-04-15 14:06:41,143] Trial 96 finished with value: 0.20852742382431236 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7312350213287773, 'min_weight_fraction_leaf': 0.04898698424961209}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23608027081908015
Fold 2 IBS: 0.1835953504200279
Fold 3 IBS: 0.20150615985904316
Fold 4 IBS: 0.2102069690328971
Fold 5 IBS: 0.20748897405413733
[I 2024-04-15 14:06:43,553] Trial 97 finished with value: 0.20777554483703714 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 153, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6968965471814753, 'min_weight_fraction_leaf': 0.0505916256520447}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23389009461942958
Fold 2 IBS: 0.18577086451211336
Fold 3 IBS: 0.20307358104865128
Fold 4 IBS: 0.2086430242358467
Fold 5 IBS: 0.2076497222974857
[I 2024-04-15 14:06:45,810] Trial 98 finished with value: 0.20780545734270534 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6887726496402962, 'min_weight_fraction_leaf': 0.04771137682412141}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2434837934214731
Fold 2 IBS: 0.2272775037538945
Fold 3 IBS: 0.2265372467505086
Fold 4 IBS: 0.23746702398923994
Fold 5 IBS: 0.22710567134340368
[I 2024-04-15 14:06:47,969] Trial 99 finished with value: 0.23237424785170396 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 137, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6897878932245053, 'min_weight_fraction_leaf': 0.3195640033653079}. Best is trial 71 with value: 0.20716724376288945.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.20716724376288945], datetime_start=datetime.datetime(2024, 4, 15, 14, 5, 48, 442852), datetime_complete=datetime.datetime(2024, 4, 15, 14, 5, 49, 441692), params={'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.20716724376288945

In [53]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [54]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.764
train_ibs:  0.207

#### Test

In [55]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [56]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_features=None, max_leaf_nodes=13,
                   max_samples=0.9529576562335005, min_samples_split=15,
                   min_weight_fraction_leaf=0.05156899271012762,
                   n_estimators=376, random_state=123, warm_start=True)

C-index score: 0.543

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=17,
                   max_samples=0.6638490929451707, min_samples_leaf=2,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.052914450220883674,
                   n_estimators=60, oob_score=True, random_state=123)

IBS: 0.256

In [57]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [58]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 14:06:49,326] A new study created in memory with name: no-name-0c40934b-131e-4e3d-8667-ea42258a92d0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:17,403] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:28,172] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:38,403] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:07:54,749] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:02,655] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:04,483] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:20,552] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:25,245] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:08:25,805] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 14:09:09,128] Trial 9 finished with value: 0.7079199845805899 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-15 14:10:32,890] Trial 10 finished with value: 0.6677145778312712 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:12:03,059] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 14:13:08,164] Trial 12 finished with value: 0.6859221467184631 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:13:48,980] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:15:12,754] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:17:02,618] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:18:30,323] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:20:31,939] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:22:46,178] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:22:52,237] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:23:42,005] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 14:26:19,256] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6137339055793991
[I 2024-04-15 14:29:23,612] Trial 22 finished with value: 0.658086559263577 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:32:17,056] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:33:56,729] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:36:04,423] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:36:44,298] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:38:41,477] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:38:50,500] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:40:24,127] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:40:47,647] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-15 14:42:26,071] Trial 31 finished with value: 0.6020563220294257 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:44:08,970] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:45:16,110] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:46:32,231] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-15 14:47:23,258] Trial 35 finished with value: 0.6743933936379024 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:48:03,496] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:48:33,638] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:48:55,177] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:49:20,390] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:49:50,766] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-15 14:51:38,055] Trial 41 finished with value: 0.6433893503184027 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:52:46,434] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:54:07,134] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:54:32,546] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:56:01,274] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 14:56:13,463] Trial 46 finished with value: 0.6994229841114794 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:56:33,692] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:56:34,049] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:56:44,938] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:57:35,230] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 14:58:28,912] Trial 51 finished with value: 0.6921806327884186 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 14:59:00,556] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6952789699570815
[I 2024-04-15 15:00:02,978] Trial 53 finished with value: 0.7081084979356779 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:00:56,597] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:01:05,884] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:01:55,927] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6416309012875536
[I 2024-04-15 15:02:03,100] Trial 57 finished with value: 0.7057479712796905 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:02:10,797] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:02:23,806] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:02:34,648] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:02:49,257] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 15:03:20,690] Trial 62 finished with value: 0.712727180870049 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6630901287553648
[I 2024-04-15 15:03:47,331] Trial 63 finished with value: 0.7108187349167132 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:04:16,824] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.4297477654076297, 'learning_rate': 0.043910428099002294, 'dropout_rate': 0.8352402756430523, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4263511298787651, 'min_weight_fraction_leaf': 0.3160966031078735, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9463535838530875, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6416309012875536
[I 2024-04-15 15:04:56,868] Trial 65 finished with value: 0.6902478805446599 and parameters: {'subsample': 0.30781242416514565, 'learning_rate': 0.05113323137902576, 'dropout_rate': 0.7239851485767856, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0027463439227063506, 'min_weight_fraction_leaf': 0.26877432545564617, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0017887993094304819, 'validation_fraction': 0.761339316000577, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:05:13,782] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.48922080655608885, 'learning_rate': 0.035347527077929, 'dropout_rate': 0.8893092269739165, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5356537836856377, 'min_weight_fraction_leaf': 0.29863354085488475, 'max_features': 'sqrt', 'min_impurity_decrease': 0.012061434840147687, 'validation_fraction': 0.9051978098851384, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:05:40,529] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4210285565476828, 'learning_rate': 0.06591045167415374, 'dropout_rate': 0.8060412975360456, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7762639994874865, 'min_weight_fraction_leaf': 0.25473199100313054, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00610717642726731, 'validation_fraction': 0.8093169248034847, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:05:53,063] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.36755564370451066, 'learning_rate': 0.05068902572826714, 'dropout_rate': 0.9726834213374217, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1308236536377811, 'min_weight_fraction_leaf': 0.3065580571022596, 'max_features': 'sqrt', 'min_impurity_decrease': 0.021693222709295752, 'validation_fraction': 0.715818151257265, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:06:12,482] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5142803470563067, 'learning_rate': 0.03243373478476426, 'dropout_rate': 0.9137837647742049, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28985235680036014, 'min_weight_fraction_leaf': 0.4054829396615446, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001581139753892363, 'validation_fraction': 0.329118980782965, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:06:37,418] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.45559432833731667, 'learning_rate': 0.0700250470025932, 'dropout_rate': 0.8524549437406417, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6643601052078473, 'min_weight_fraction_leaf': 0.2388136010393243, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00031481444052736005, 'validation_fraction': 0.9166648433104408, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6373390557939914
[I 2024-04-15 15:07:16,420] Trial 71 finished with value: 0.6914213405066317 and parameters: {'subsample': 0.3096152191637527, 'learning_rate': 0.05014029765368843, 'dropout_rate': 0.72942553198655, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027173150322083957, 'min_weight_fraction_leaf': 0.28439521854539385, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002459385698607316, 'validation_fraction': 0.9631122514300272, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:08:09,774] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.2984794016129376, 'learning_rate': 0.04184406116938292, 'dropout_rate': 0.6550072165726977, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791436061459352, 'min_weight_fraction_leaf': 0.28556030062342436, 'max_features': 'sqrt', 'min_impurity_decrease': 4.3401892914387e-05, 'validation_fraction': 0.9667204228379752, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:08:20,786] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.24177977569589332, 'learning_rate': 0.06081438305266998, 'dropout_rate': 0.7352912026497521, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3565493126455575, 'min_weight_fraction_leaf': 0.2641618003854867, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005565263987110645, 'validation_fraction': 0.8591928424609534, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:08:53,845] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.41766913987966564, 'learning_rate': 0.04837445328457708, 'dropout_rate': 0.7848778465425879, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9796884706123067, 'min_weight_fraction_leaf': 0.3487238233672823, 'max_features': 0.1, 'min_impurity_decrease': 0.060142707029694174, 'validation_fraction': 0.9742035251830021, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:09:28,531] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.14697123662254313, 'learning_rate': 0.056288895309512615, 'dropout_rate': 0.9249274443508626, 'n_estimators': 491, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3014105775868996, 'min_weight_fraction_leaf': 0.2756234570388064, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5125842579708578e-05, 'validation_fraction': 0.9436471609372878, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:10:51,590] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.33597481611005453, 'learning_rate': 0.03785525432874416, 'dropout_rate': 0.5640100673453201, 'n_estimators': 465, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6095307820420031, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 0.009484910777116757, 'validation_fraction': 0.9018697914265744, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:12:20,519] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.3970316343863033, 'learning_rate': 0.02702816788183442, 'dropout_rate': 0.44124671276745586, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.38254401959264994, 'max_features': 1, 'min_impurity_decrease': 0.0031143423876080715, 'validation_fraction': 0.9903409642142473, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6545064377682404
[I 2024-04-15 15:13:44,610] Trial 78 finished with value: 0.6992944115505685 and parameters: {'subsample': 0.22930387168853233, 'learning_rate': 0.05145553889741248, 'dropout_rate': 0.5044517635709308, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.24788146923782178, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010045782837561419, 'validation_fraction': 0.8244464183531952, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:15:21,205] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.5787844954317829, 'learning_rate': 0.046320469166095994, 'dropout_rate': 0.4903660577547442, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8369274241395267, 'min_weight_fraction_leaf': 0.3217471182217138, 'max_features': 'sqrt', 'min_impurity_decrease': 6.262467662262306e-05, 'validation_fraction': 0.822046932546052, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:16:33,199] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.6081624319156314, 'n_estimators': 427, 'criterion': 'friedman_mse', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.20197769506016003, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010150765068526006, 'validation_fraction': 0.7818118403834172, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:17:39,295] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.18443408707190798, 'learning_rate': 0.05259966681355033, 'dropout_rate': 0.6449369275082966, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23050623823206434, 'min_weight_fraction_leaf': 0.25144155938407586, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013502467549795782, 'validation_fraction': 0.8730600269587929, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:19:09,550] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.21084564139781542, 'learning_rate': 0.0557198718851306, 'dropout_rate': 0.5142046015087244, 'n_estimators': 464, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017868752517803354, 'min_weight_fraction_leaf': 0.22672177077398445, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00028049277519258663, 'validation_fraction': 0.9277470449701044, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:19:57,107] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.4945458790853893, 'learning_rate': 0.05895862835575055, 'dropout_rate': 0.7558273871774451, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.501498258850682, 'min_weight_fraction_leaf': 0.28306768635206997, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04144166385519717, 'validation_fraction': 0.8951513356732839, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5708154506437768
[I 2024-04-15 15:21:15,050] Trial 84 finished with value: 0.5444860535940432 and parameters: {'subsample': 0.3659778071469274, 'learning_rate': 0.0502270627847683, 'dropout_rate': 0.6818395627907664, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2606567709484204, 'min_weight_fraction_leaf': 0.2982881980338302, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006662326950079798, 'validation_fraction': 0.8368533116927852, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:22:24,980] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.26399210031385845, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.5847508382404618, 'n_estimators': 406, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9671659583078602, 'min_weight_fraction_leaf': 0.24391254579161395, 'max_features': 'log2', 'min_impurity_decrease': 0.000147849817010694, 'validation_fraction': 0.9991453937475061, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:22:31,674] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10060967717953817, 'learning_rate': 0.020768593047903114, 'dropout_rate': 0.4508818797021682, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.625182110561999, 'min_weight_fraction_leaf': 0.2761510567632799, 'max_features': 1, 'min_impurity_decrease': 0.0023479607608161597, 'validation_fraction': 0.7423283408922972, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5319148936170213
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5708154506437768
[I 2024-04-15 15:24:42,614] Trial 87 finished with value: 0.5635118483198402 and parameters: {'subsample': 0.43950121810340115, 'learning_rate': 0.0648732804536445, 'dropout_rate': 0.34957168713474945, 'n_estimators': 475, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2369430535237365, 'min_weight_fraction_leaf': 0.3096474641971687, 'max_features': 0.1, 'min_impurity_decrease': 4.850175263275894e-05, 'validation_fraction': 0.951557506428991, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:25:12,802] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.21193910478383937, 'learning_rate': 0.06177410341848358, 'dropout_rate': 0.8846843251251039, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.2807191828912141, 'min_weight_fraction_leaf': 0.36091713798964337, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0185550531810504e-05, 'validation_fraction': 0.8545724907452001, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:26:02,460] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.3182195088282702, 'learning_rate': 0.038485790496188235, 'dropout_rate': 0.5004748125823506, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5179293303896771, 'min_weight_fraction_leaf': 0.3315564489154308, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00046699939753012373, 'validation_fraction': 0.9294234431035183, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:27:15,685] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.2762755336662733, 'learning_rate': 0.05273046932737523, 'dropout_rate': 0.5437417743878508, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.8405822272736876, 'min_weight_fraction_leaf': 0.43576713073659407, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8767498848039622, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6459227467811158
[I 2024-04-15 15:28:13,731] Trial 91 finished with value: 0.6948185874130767 and parameters: {'subsample': 0.3126184078929269, 'learning_rate': 0.051134988454074756, 'dropout_rate': 0.7292690956696949, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03786277950879616, 'min_weight_fraction_leaf': 0.2673649069566119, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009910717111428719, 'validation_fraction': 0.7562406049799346, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6673819742489271
[I 2024-04-15 15:28:35,803] Trial 92 finished with value: 0.6989359122811389 and parameters: {'subsample': 0.335844111701364, 'learning_rate': 0.05038873458029908, 'dropout_rate': 0.9571283850291226, 'n_estimators': 449, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046820443269266425, 'min_weight_fraction_leaf': 0.2690679137012573, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0008839215080019705, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:28:54,465] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.33719220910486725, 'learning_rate': 0.05705464633480763, 'dropout_rate': 0.9535384595922254, 'n_estimators': 458, 'criterion': 'friedman_mse', 'ccp_alpha': 0.46107702292048336, 'min_weight_fraction_leaf': 0.21683645486742856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.862155169827754e-06, 'validation_fraction': 0.6649080237925696, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5665236051502146
[I 2024-04-15 15:29:08,168] Trial 94 finished with value: 0.5133047210300429 and parameters: {'subsample': 0.3795391698153348, 'learning_rate': 0.05424992354992036, 'dropout_rate': 0.998020448184449, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.25606469361498857, 'min_weight_fraction_leaf': 0.41683364220226815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002584853980433294, 'validation_fraction': 0.7006781615049952, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:29:27,998] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8984320859036168, 'learning_rate': 0.04600776760199582, 'dropout_rate': 0.9375007175299167, 'n_estimators': 432, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6620944039517677, 'min_weight_fraction_leaf': 0.25977850599919555, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001020092546254454, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:29:45,623] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.9444669238877774, 'learning_rate': 0.03476407177203711, 'dropout_rate': 0.9688789578178828, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5985394199987468, 'min_weight_fraction_leaf': 0.4570304925648464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009757952163430444, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 15:30:12,222] Trial 97 finished with value: 0.6983542268255716 and parameters: {'subsample': 0.40802503425948106, 'learning_rate': 0.060600248591443, 'dropout_rate': 0.8994280356510341, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.16755337346680707, 'min_weight_fraction_leaf': 0.24511190648995798, 'max_features': 'sqrt', 'min_impurity_decrease': 8.96572949971136e-05, 'validation_fraction': 0.627628127325836, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-15 15:30:36,792] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.40520020589260825, 'learning_rate': 0.06969431851683794, 'dropout_rate': 0.852867621588153, 'n_estimators': 377, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.23289524687485436, 'max_features': 'sqrt', 'min_impurity_decrease': 9.215043781245307e-05, 'validation_fraction': 0.6236577327109031, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-15 15:30:59,401] A new study created in memory with name: no-name-834809fb-30d1-473b-b910-f68c272dd9ad

Fold 5 C-index: 0.5
[I 2024-04-15 15:30:59,378] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.04234673286327711, 'dropout_rate': 0.8983226388952166, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.0709913910444209, 'min_weight_fraction_leaf': 0.25005718600704474, 'max_features': 'log2', 'min_impurity_decrease': 0.0001309255892076454, 'validation_fraction': 0.6560219357259244, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.


* Best trial for C-index:
 FrozenTrial(number=62, state=TrialState.COMPLETE, values=[0.712727180870049], datetime_start=datetime.datetime(2024, 4, 15, 15, 2, 49, 265753), datetime_complete=datetime.datetime(2024, 4, 15, 15, 3, 20, 688855), params={'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=62, value=None)


* Best Score for C-index:
 0.712727180870049

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:31:39,613] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:32:00,796] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:32:19,560] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:32:52,358] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:33:04,204] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:33:07,535] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:33:48,033] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:33:57,823] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:33:59,096] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24603560357944756
Fold 2 IBS: 0.2303451757578765
Fold 3 IBS: 0.22864210229423013
Fold 4 IBS: 0.24084923849388645
Fold 5 IBS: 0.22856534560034253
[I 2024-04-15 15:35:32,511] Trial 9 finished with value: 0.2348874931451566 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316595760132136
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-15 15:37:44,925] Trial 10 finished with value: 0.2356341548121131 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 15:40:10,352] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24715496002116139
Fold 2 IBS: 0.23184438819341896
Fold 3 IBS: 0.2289550256511867
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-15 15:42:18,444] Trial 12 finished with value: 0.23582687970453725 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:43:16,414] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:44:58,417] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:46:27,059] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:47:18,061] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:49:13,260] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:50:09,420] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:50:18,624] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:51:59,983] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24711009086064675
Fold 2 IBS: 0.23198651484788396
Fold 3 IBS: 0.22892152217671352
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-15 15:53:52,714] Trial 21 finished with value: 0.23582876076562656 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.2461444810014907
Fold 2 IBS: 0.2300302068927662
Fold 3 IBS: 0.22866943981867105

Fold 4 IBS: 0.24076805673249593
Fold 5 IBS: 0.2286244137483669
[I 2024-04-15 15:56:04,071] Trial 22 finished with value: 0.23484731963875816 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:57:46,824] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:58:56,158] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 15:59:56,994] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:01:19,904] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:01:28,296] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:01:58,825] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:03:11,514] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:03:44,186] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2469488707078328
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-15 16:05:24,429] Trial 31 finished with value: 0.23566408867478444 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2462866194872135
Fold 2 IBS: 0.23015814957230293
Fold 3 IBS: 0.22867627879341337
Fold 4 IBS: 0.24075894829353398
Fold 5 IBS: 0.22871397901804405
[I 2024-04-15 16:07:02,918] Trial 32 finished with value: 0.23491879503290156 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:08:20,305] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:09:49,991] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:10:07,926] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:12:02,479] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:12:05,524] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:13:00,576] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:14:07,803] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:15:18,036] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24665512418855506
Fold 2 IBS: 0.23079937875838777
Fold 3 IBS: 0.22859112956406855
Fold 4 IBS: 0.2411732320853091
Fold 5 IBS: 0.2289343835210694
[I 2024-04-15 16:17:02,779] Trial 41 finished with value: 0.23523064962347795 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24633993932293982
Fold 2 IBS: 0.23025272242517308
Fold 3 IBS: 0.22801274485299367
Fold 4 IBS: 0.24081637601730027
Fold 5 IBS: 0.22872083072116958
[I 2024-04-15 16:18:52,999] Trial 42 finished with value: 0.2348285226679153 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:20:49,268] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:22:16,384] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24693882344056556
Fold 2 IBS: 0.23145350422053343
Fold 3 IBS: 0.22860307836669258
Fold 4 IBS: 0.24146437703078477
Fold 5 IBS: 0.22909817747073397
[I 2024-04-15 16:23:32,258] Trial 45 finished with value: 0.23551159210586206 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:25:07,284] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:25:44,592] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:25:45,137] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:26:04,261] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:28:05,024] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24695366408679845
Fold 2 IBS: 0.23146997904187452
Fold 3 IBS: 0.2285885733926773
Fold 4 IBS: 0.24149615706388644
Fold 5 IBS: 0.22910431519663427
[I 2024-04-15 16:29:47,928] Trial 51 finished with value: 0.2355225377563742 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:31:32,684] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24641855308804925
Fold 2 IBS: 0.23048568622584525
Fold 3 IBS: 0.2278623120416157
Fold 4 IBS: 0.24068876716298668
Fold 5 IBS: 0.22857688144644517
[I 2024-04-15 16:32:56,593] Trial 53 finished with value: 0.2348064399929884 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:34:32,534] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:35:56,530] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:37:14,476] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:38:25,306] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:40:23,058] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:41:55,530] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:42:41,293] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:43:45,677] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2468810203480293
Fold 2 IBS: 0.2311990963376084
Fold 3 IBS: 0.228454108036685
Fold 4 IBS: 0.24124096112643856
Fold 5 IBS: 0.22895207624265332
[I 2024-04-15 16:44:42,419] Trial 62 finished with value: 0.23534545241828292 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:45:46,198] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2465043054793762
Fold 2 IBS: 0.23031643211780425
Fold 3 IBS: 0.2279578986949742
Fold 4 IBS: 0.24045858876874635
Fold 5 IBS: 0.22854526131961184
[I 2024-04-15 16:46:40,692] Trial 64 finished with value: 0.23475649727610257 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-15 16:47:26,874] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:48:20,074] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:48:55,524] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:50:11,172] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:51:18,632] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:52:11,073] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.2469128753364667
Fold 2 IBS: 0.23120680886119857
Fold 3 IBS: 0.2284490521729702
Fold 4 IBS: 0.2412928489959067
Fold 5 IBS: 0.22897078571077217
[I 2024-04-15 16:53:04,768] Trial 71 finished with value: 0.23536647421546286 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24699640897951017
Fold 2 IBS: 0.23151620221444727
Fold 3 IBS: 0.22861416387399014
Fold 4 IBS: 0.24155860571648258
Fold 5 IBS: 0.22912133061238216
[I 2024-04-15 16:53:44,953] Trial 72 finished with value: 0.23556134227936246 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:53:51,533] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:55:50,199] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:56:45,995] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:57:42,812] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 16:58:59,965] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 16:59:32,166] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:00:47,015] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:01:16,592] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24689956409794034
Fold 2 IBS: 0.23118732433711728
Fold 3 IBS: 0.22843302311048683
Fold 4 IBS: 0.24126338444926765
Fold 5 IBS: 0.22894778512748845
[I 2024-04-15 17:02:02,444] Trial 81 finished with value: 0.23534621622446011 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:02:50,311] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:03:46,537] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898150255235122
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293932698055425
[I 2024-04-15 17:04:15,695] Trial 84 finished with value: 0.23592730576033555 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24536364898371674
Fold 2 IBS: 0.22661035397022303
Fold 3 IBS: 0.226596757813156
Fold 4 IBS: 0.2389442424082662
Fold 5 IBS: 0.22754912881625142
[I 2024-04-15 17:05:21,945] Trial 85 finished with value: 0.23301282639832266 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:06:32,274] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8908016266221349, 'learning_rate': 0.020782252048892114, 'dropout_rate': 0.20248417164561996, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.025928909209021245, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:06:59,387] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953409887733455, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:08:12,791] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.0030671608519508686, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.27772784044341225, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:09:18,135] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9240076064991638, 'learning_rate': 0.036372907201929795, 'dropout_rate': 0.16604269499086277, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.6288732373244443, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.8456629128553931, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:10:18,182] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.22333957383529762, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24648485188041894
Fold 2 IBS: 0.2305073947731919
Fold 3 IBS: 0.22795134549192056
Fold 4 IBS: 0.24057179186781263
Fold 5 IBS: 0.22853359304710397
[I 2024-04-15 17:11:18,140] Trial 91 finished with value: 0.23480979541208963 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.01642165444052923, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.901410266511097, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:12:20,794] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.012238074680872561, 'dropout_rate': 0.2583752131981347, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 2.0262506829884978e-07, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:13:19,098] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9444060832329966, 'learning_rate': 0.017856303491279684, 'dropout_rate': 0.30303355573944185, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.011908761872398903, 'max_features': 'auto', 'min_impurity_decrease': 6.055732421263935e-07, 'validation_fraction': 0.864284511598723, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:14:06,139] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8821760782294449, 'learning_rate': 0.005785552173633914, 'dropout_rate': 0.28058975756978766, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.8506324992317083, 'min_weight_fraction_leaf': 0.04622694094641695, 'max_features': None, 'min_impurity_decrease': 1.3402986834437386e-07, 'validation_fraction': 0.8985100287316004, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 17:15:04,427] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9761707513926794, 'learning_rate': 0.019567902784876703, 'dropout_rate': 0.3201948574529592, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.0386964570043107, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9417888137501867, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24641425402466968
Fold 2 IBS: 0.22943554006463165
Fold 3 IBS: 0.22871680820224374
Fold 4 IBS: 0.24077011514188554
Fold 5 IBS: 0.22840019828947677
[I 2024-04-15 17:15:51,430] Trial 96 finished with value: 0.2347473831445815 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.01055205151962401, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.09708890262536518, 'max_features': 'auto', 'min_impurity_decrease': 3.7395479538673736e-07, 'validation_fraction': 0.992337544991608, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:16:37,341] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.010954886262406833, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 1.603167122698403, 'min_weight_fraction_leaf': 0.06013220413302209, 'max_features': 'auto', 'min_impurity_decrease': 3.972456306049239e-07, 'validation_fraction': 0.9976245698846969, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-15 17:17:13,137] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8505038223267275, 'learning_rate': 0.013402809510359784, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 0.25666428673598457, 'min_weight_fraction_leaf': 0.1129024126904408, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.9625603744870045, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-15 17:18:06,617] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.06808689488183181, 'dropout_rate': 0.25443633448028735, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5386043790221791, 'min_weight_fraction_leaf': 0.03403879613376609, 'max_features': 'auto', 'min_impurity_decrease': 8.69596280226011e-07, 'validation_fraction': 0.9221483446288596, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23301282639832266], datetime_start=datetime.datetime(2024, 4, 15, 17, 4, 15, 706328), datetime_complete=datetime.datetime(2024, 4, 15, 17, 5, 21, 943873), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23301282639832266

In [59]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [60]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.713
train_ibs:  0.233

#### Test

In [61]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [62]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.022737959076050005,
                                 dropout_rate=0.8285090704895912,
                                 learning_rate=0.0513322635401625, max_depth=2,
                                 max_features='sqrt', max_leaf_nodes=10,
                                 min_impurity_decrease=0.002070496973827786,
                                 min_samples_leaf=15, min_samples_split=19,
                                 min_weight_fraction_leaf=0.3101145382804477,
                                 n_estimators=485, random_state=123,
                                 subsample=0.45214538811231725,
                                 validation_fraction=0.9071319756271838)

C-index score: 0.532

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.229

In [63]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [64]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-15 17:18:22,069] A new study created in memory with name: no-name-31a20e10-2829-42ef-96f6-d75b2b3070d8

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:23,014] Trial 0 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6423526693826518.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:30,065] Trial 1 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:31,514] Trial 2 finished with value: 0.6398895181851605 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:18:33,380] Trial 3 finished with value: 0.640287103957515 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:18:36,698] Trial 4 finished with value: 0.641083916706519 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:41,412] Trial 5 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:43,346] Trial 6 finished with value: 0.6456489898043869 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 1 with value: 0.6456489898043869.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 17:18:43,781] Trial 7 finished with value: 0.6483531442725031 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.6483531442725031.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:45,961] Trial 8 finished with value: 0.6438735819301804 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.6483531442725031.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:51,329] Trial 9 finished with value: 0.6423526693826518 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.6483531442725031.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:51,634] Trial 10 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.6483531442725031.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:18:58,663] Trial 11 finished with value: 0.6466687677973757 and parameters: {'subsample': 0.1913192016083392, 'dropout_rate': 0.653844054640545, 'n_estimators': 479, 'learning_rate': 0.09497904560009218}. Best is trial 7 with value: 0.6483531442725031.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 17:19:02,920] Trial 12 finished with value: 0.6514894382694572 and parameters: {'subsample': 0.11615582976955166, 'dropout_rate': 0.7156669644400785, 'n_estimators': 341, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6514894382694572.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 17:19:06,667] Trial 13 finished with value: 0.6499685257219285 and parameters: {'subsample': 0.11036933079077518, 'dropout_rate': 0.7302564728030555, 'n_estimators': 339, 'learning_rate': 0.09856277651579823}. Best is trial 12 with value: 0.6514894382694572.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 17:19:10,383] Trial 14 finished with value: 0.652286251018461 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7758323406306332, 'n_estimators': 342, 'learning_rate': 0.09980514090256132}. Best is trial 14 with value: 0.652286251018461.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:19:14,260] Trial 15 finished with value: 0.6532531222787401 and parameters: {'subsample': 0.10123497548852628, 'dropout_rate': 0.8253440414394401, 'n_estimators': 377, 'learning_rate': 0.08616677729964022}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:19:18,288] Trial 16 finished with value: 0.6404688863337136 and parameters: {'subsample': 0.29391461974521166, 'dropout_rate': 0.9733961081825167, 'n_estimators': 417, 'learning_rate': 0.08773503543448663}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:19:20,666] Trial 17 finished with value: 0.6436561373297296 and parameters: {'subsample': 0.3607822558916775, 'dropout_rate': 0.8384493320704152, 'n_estimators': 274, 'learning_rate': 0.08256412174149105}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 17:19:24,994] Trial 18 finished with value: 0.6419422858052315 and parameters: {'subsample': 0.21167221488611937, 'dropout_rate': 0.8224385347909192, 'n_estimators': 396, 'learning_rate': 0.08278758209333262}. Best is trial 15 with value: 0.6532531222787401.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:19:27,563] Trial 19 finished with value: 0.6444529500787335 and parameters: {'subsample': 0.3743552574085504, 'dropout_rate': 0.9964748437560931, 'n_estimators': 303, 'learning_rate': 0.08697733590757546}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:19:33,228] Trial 20 finished with value: 0.6443294235502888 and parameters: {'subsample': 0.179916923106687, 'dropout_rate': 0.6101927969129244, 'n_estimators': 422, 'learning_rate': 0.06631423193408584}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 17:19:36,924] Trial 21 finished with value: 0.652286251018461 and parameters: {'subsample': 0.11005837821082129, 'dropout_rate': 0.7702372780117805, 'n_estimators': 342, 'learning_rate': 0.09637734603701122}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 17:19:40,542] Trial 22 finished with value: 0.6515436893502404 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.7887959786588337, 'n_estimators': 307, 'learning_rate': 0.09976065163760366}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 17:19:45,427] Trial 23 finished with value: 0.6436086242537188 and parameters: {'subsample': 0.26367183029498054, 'dropout_rate': 0.77090886810623, 'n_estimators': 391, 'learning_rate': 0.08764943782473954}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:19:51,329] Trial 24 finished with value: 0.6443510425008431 and parameters: {'subsample': 0.16994277825585596, 'dropout_rate': 0.5785041304872882, 'n_estimators': 431, 'learning_rate': 0.07856089888556002}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:19:54,077] Trial 25 finished with value: 0.6440917207816187 and parameters: {'subsample': 0.9684217810899436, 'dropout_rate': 0.9105411323806067, 'n_estimators': 310, 'learning_rate': 0.09135966095585035}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 17:19:57,834] Trial 26 finished with value: 0.6436086242537188 and parameters: {'subsample': 0.30245901630708794, 'dropout_rate': 0.9105869577335487, 'n_estimators': 367, 'learning_rate': 0.08005170012801176}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:00,055] Trial 27 finished with value: 0.6428809435312799 and parameters: {'subsample': 0.42274241295760984, 'dropout_rate': 0.6510059664789519, 'n_estimators': 251, 'learning_rate': 0.09122531457830381}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:20:05,339] Trial 28 finished with value: 0.6463730896029115 and parameters: {'subsample': 0.6095590802808257, 'dropout_rate': 0.7996037563345703, 'n_estimators': 453, 'learning_rate': 0.03942446417028639}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:20:09,291] Trial 29 finished with value: 0.6448885335306227 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.528113503868086, 'n_estimators': 351, 'learning_rate': 0.06046208382653473}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 17:20:10,204] Trial 30 finished with value: 0.6435142923526851 and parameters: {'subsample': 0.23709443482121922, 'dropout_rate': 0.7457374535389898, 'n_estimators': 123, 'learning_rate': 0.016814619253793885}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 17:20:13,274] Trial 31 finished with value: 0.6523947531800276 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.856568301468149, 'n_estimators': 302, 'learning_rate': 0.09787732715264892}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 17:20:16,493] Trial 32 finished with value: 0.6467450616717694 and parameters: {'subsample': 0.153281184867041, 'dropout_rate': 0.8665197717680801, 'n_estimators': 299, 'learning_rate': 0.09964887223210685}. Best is trial 15 with value: 0.6532531222787401.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 17:20:18,601] Trial 33 finished with value: 0.653749331561292 and parameters: {'subsample': 0.14640475436912043, 'dropout_rate': 0.9273560528371623, 'n_estimators': 232, 'learning_rate': 0.09227289487369508}. Best is trial 33 with value: 0.653749331561292.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:20,479] Trial 34 finished with value: 0.6466036305237528 and parameters: {'subsample': 0.22509252178670863, 'dropout_rate': 0.9482452651205635, 'n_estimators': 230, 'learning_rate': 0.07455031407762674}. Best is trial 33 with value: 0.653749331561292.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 17:20:21,611] Trial 35 finished with value: 0.6459846053980052 and parameters: {'subsample': 0.16409845249239785, 'dropout_rate': 0.9158529252744986, 'n_estimators': 150, 'learning_rate': 0.09059423578303503}. Best is trial 33 with value: 0.653749331561292.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:24,117] Trial 36 finished with value: 0.6442711677025349 and parameters: {'subsample': 0.3126254996824502, 'dropout_rate': 0.8596151515184938, 'n_estimators': 274, 'learning_rate': 0.0693670679209284}. Best is trial 33 with value: 0.653749331561292.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:20:26,486] Trial 37 finished with value: 0.656117456606762 and parameters: {'subsample': 0.14137358150210924, 'dropout_rate': 0.47096246897520044, 'n_estimators': 237, 'learning_rate': 0.07677405503763898}. Best is trial 37 with value: 0.656117456606762.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:28,713] Trial 38 finished with value: 0.6434311170524222 and parameters: {'subsample': 0.23557094034920928, 'dropout_rate': 0.29839135236038283, 'n_estimators': 221, 'learning_rate': 0.0775915195100935}. Best is trial 37 with value: 0.656117456606762.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:20:30,168] Trial 39 finished with value: 0.6577474385800097 and parameters: {'subsample': 0.16797447968278584, 'dropout_rate': 0.48271147924203567, 'n_estimators': 174, 'learning_rate': 0.06892741183938003}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:20:30,745] Trial 40 finished with value: 0.6376081493638677 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.3687262312492404, 'n_estimators': 78, 'learning_rate': 0.06254821700272431}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 17:20:32,479] Trial 41 finished with value: 0.6452310305501099 and parameters: {'subsample': 0.16051712667347232, 'dropout_rate': 0.5131235103944057, 'n_estimators': 187, 'learning_rate': 0.0699971933144608}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 17:20:33,783] Trial 42 finished with value: 0.6536402621355728 and parameters: {'subsample': 0.15689150922315742, 'dropout_rate': 0.42742242638340083, 'n_estimators': 155, 'learning_rate': 0.08348848252538535}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:35,253] Trial 43 finished with value: 0.6442279298014262 and parameters: {'subsample': 0.2608536778382206, 'dropout_rate': 0.4387041410922028, 'n_estimators': 178, 'learning_rate': 0.07403423987427098}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:20:36,603] Trial 44 finished with value: 0.6491103000443126 and parameters: {'subsample': 0.19321763353403956, 'dropout_rate': 0.4354859672285588, 'n_estimators': 157, 'learning_rate': 0.057377043685135895}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:37,855] Trial 45 finished with value: 0.6403598169079945 and parameters: {'subsample': 0.32757241947277393, 'dropout_rate': 0.30608091648882185, 'n_estimators': 125, 'learning_rate': 0.08480813312566247}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:38,675] Trial 46 finished with value: 0.641083916706519 and parameters: {'subsample': 0.43192870655555626, 'dropout_rate': 0.14648424644002478, 'n_estimators': 86, 'learning_rate': 0.06631073785618792}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:20:41,400] Trial 47 finished with value: 0.6530392750364652 and parameters: {'subsample': 0.15068300896722953, 'dropout_rate': 0.48779442034524007, 'n_estimators': 240, 'learning_rate': 0.07667501159012721}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:43,719] Trial 48 finished with value: 0.6373032542882521 and parameters: {'subsample': 0.712841739844065, 'dropout_rate': 0.19701471782839963, 'n_estimators': 200, 'learning_rate': 0.08236647396455765}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6566523605150214
[I 2024-04-15 17:20:45,319] Trial 49 finished with value: 0.6466799243981466 and parameters: {'subsample': 0.202036514236033, 'dropout_rate': 0.4722470414359242, 'n_estimators': 149, 'learning_rate': 0.04679008159506039}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-15 17:20:47,176] Trial 50 finished with value: 0.6467814181470091 and parameters: {'subsample': 0.14573008200358212, 'dropout_rate': 0.5823492275525686, 'n_estimators': 206, 'learning_rate': 0.0923360832084614}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:20:49,645] Trial 51 finished with value: 0.65695420675492 and parameters: {'subsample': 0.1425070841265581, 'dropout_rate': 0.4001528554040831, 'n_estimators': 242, 'learning_rate': 0.07672564537412481}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:20:52,471] Trial 52 finished with value: 0.6554401756332606 and parameters: {'subsample': 0.13500797101461148, 'dropout_rate': 0.4035444268941795, 'n_estimators': 247, 'learning_rate': 0.07227746777460695}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:20:55,201] Trial 53 finished with value: 0.6418807294555229 and parameters: {'subsample': 0.262903795108719, 'dropout_rate': 0.39893030064337187, 'n_estimators': 255, 'learning_rate': 0.06395518418091885}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:20:57,519] Trial 54 finished with value: 0.6568926504052116 and parameters: {'subsample': 0.13663971138966197, 'dropout_rate': 0.32766376391188967, 'n_estimators': 227, 'learning_rate': 0.07194995077612379}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:21:00,633] Trial 55 finished with value: 0.6465967490978837 and parameters: {'subsample': 0.21557147393209286, 'dropout_rate': 0.32610192893068957, 'n_estimators': 277, 'learning_rate': 0.053343545412390905}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:21:02,958] Trial 56 finished with value: 0.6514603870631426 and parameters: {'subsample': 0.13710531929544742, 'dropout_rate': 0.19791869979234933, 'n_estimators': 224, 'learning_rate': 0.057881114786678234}. Best is trial 39 with value: 0.6577474385800097.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:21:05,013] Trial 57 finished with value: 0.6473719428963334 and parameters: {'subsample': 0.19170339276066936, 'dropout_rate': 0.34920478401965377, 'n_estimators': 198, 'learning_rate': 0.07116818308763594}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:21:07,353] Trial 58 finished with value: 0.6403598169079945 and parameters: {'subsample': 0.28386757733934376, 'dropout_rate': 0.39776454709906567, 'n_estimators': 240, 'learning_rate': 0.07381207419466763}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:21:10,646] Trial 59 finished with value: 0.6546360576153314 and parameters: {'subsample': 0.13100404727348794, 'dropout_rate': 0.2635083386672942, 'n_estimators': 263, 'learning_rate': 0.08049185195141417}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:21:15,043] Trial 60 finished with value: 0.6418807294555229 and parameters: {'subsample': 0.3392122843755879, 'dropout_rate': 0.28019080841720423, 'n_estimators': 325, 'learning_rate': 0.0675116615249533}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:21:18,131] Trial 61 finished with value: 0.6539882516912007 and parameters: {'subsample': 0.13243763781322052, 'dropout_rate': 0.2340450327369581, 'n_estimators': 268, 'learning_rate': 0.07677908466371873}. Best is trial 39 with value: 0.6577474385800097.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:21:21,779] Trial 62 finished with value: 0.6604274506795376 and parameters: {'subsample': 0.12924519330357495, 'dropout_rate': 0.10133462572129326, 'n_estimators': 285, 'learning_rate': 0.07994592657997299}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 17:21:25,325] Trial 63 finished with value: 0.6572479452297646 and parameters: {'subsample': 0.18223164739664777, 'dropout_rate': 0.11489640033339366, 'n_estimators': 288, 'learning_rate': 0.0798345104091864}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:21:28,773] Trial 64 finished with value: 0.6548539260588384 and parameters: {'subsample': 0.24009114521342884, 'dropout_rate': 0.1007217394872019, 'n_estimators': 284, 'learning_rate': 0.07071923716816372}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:21:32,532] Trial 65 finished with value: 0.6562232255305265 and parameters: {'subsample': 0.1851636289937339, 'dropout_rate': 0.1097674362445598, 'n_estimators': 287, 'learning_rate': 0.06594308578038652}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:21:36,427] Trial 66 finished with value: 0.6517210695647021 and parameters: {'subsample': 0.20757840705861835, 'dropout_rate': 0.12016314411777446, 'n_estimators': 286, 'learning_rate': 0.07961263063931259}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:21:41,670] Trial 67 finished with value: 0.6499031180403743 and parameters: {'subsample': 0.18104626767334434, 'dropout_rate': 0.17526239333138746, 'n_estimators': 324, 'learning_rate': 0.06444189418725386}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:21:46,648] Trial 68 finished with value: 0.638838904360466 and parameters: {'subsample': 0.40036477885961574, 'dropout_rate': 0.2307008753520174, 'n_estimators': 324, 'learning_rate': 0.06111799964360847}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:21:49,070] Trial 69 finished with value: 0.6525509382869912 and parameters: {'subsample': 0.17826263055965458, 'dropout_rate': 0.14529995075578864, 'n_estimators': 213, 'learning_rate': 0.08765549190319478}. Best is trial 62 with value: 0.6604274506795376.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:21:53,062] Trial 70 finished with value: 0.6636725336802511 and parameters: {'subsample': 0.10832939724965542, 'dropout_rate': 0.10222075562837932, 'n_estimators': 290, 'learning_rate': 0.07704376427520507}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:21:57,078] Trial 71 finished with value: 0.6606627898855318 and parameters: {'subsample': 0.109805489388209, 'dropout_rate': 0.11978799866725322, 'n_estimators': 292, 'learning_rate': 0.07548645756672888}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:22:00,674] Trial 72 finished with value: 0.662129578339112 and parameters: {'subsample': 0.10292373174096839, 'dropout_rate': 0.1052101189010294, 'n_estimators': 292, 'learning_rate': 0.06768208111220904}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:22:04,915] Trial 73 finished with value: 0.6636725336802511 and parameters: {'subsample': 0.10341614153997622, 'dropout_rate': 0.1307406665066339, 'n_estimators': 315, 'learning_rate': 0.07480345476734877}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:22:09,052] Trial 74 finished with value: 0.6619557954828262 and parameters: {'subsample': 0.10141577740240718, 'dropout_rate': 0.13020314117454196, 'n_estimators': 315, 'learning_rate': 0.08115141671643768}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456

Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:22:13,970] Trial 75 finished with value: 0.6611589827338222 and parameters: {'subsample': 0.10152438745152188, 'dropout_rate': 0.13545994812322865, 'n_estimators': 359, 'learning_rate': 0.08231946544940025}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:22:19,062] Trial 76 finished with value: 0.6588918006073237 and parameters: {'subsample': 0.10195111287335283, 'dropout_rate': 0.17845723620045542, 'n_estimators': 356, 'learning_rate': 0.08528792727717033}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 17:22:24,899] Trial 77 finished with value: 0.6629878204509895 and parameters: {'subsample': 0.100110480737478, 'dropout_rate': 0.16747094123277959, 'n_estimators': 378, 'learning_rate': 0.08486078610090507}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:22:30,702] Trial 78 finished with value: 0.6604274506795376 and parameters: {'subsample': 0.10950957601599798, 'dropout_rate': 0.1452658537879476, 'n_estimators': 380, 'learning_rate': 0.08903976577115041}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:22:37,735] Trial 79 finished with value: 0.6589354623514886 and parameters: {'subsample': 0.11668140984872319, 'dropout_rate': 0.17011310170754945, 'n_estimators': 395, 'learning_rate': 0.0821784327813037}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-15 17:22:43,322] Trial 80 finished with value: 0.6448521770553829 and parameters: {'subsample': 0.8321289633684164, 'dropout_rate': 0.2126814526933153, 'n_estimators': 341, 'learning_rate': 0.007039353779474462}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:22:49,550] Trial 81 finished with value: 0.6611879069533018 and parameters: {'subsample': 0.10948371536224444, 'dropout_rate': 0.13584006842315466, 'n_estimators': 375, 'learning_rate': 0.08916739252971367}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:22:54,821] Trial 82 finished with value: 0.6603837889353726 and parameters: {'subsample': 0.10248522731136026, 'dropout_rate': 0.13246738852651121, 'n_estimators': 371, 'learning_rate': 0.0853500448087891}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6909871244635193
[I 2024-04-15 17:23:01,816] Trial 83 finished with value: 0.6629809390251206 and parameters: {'subsample': 0.11687876360728788, 'dropout_rate': 0.1618966593576853, 'n_estimators': 439, 'learning_rate': 0.09502150594070144}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:23:10,373] Trial 84 finished with value: 0.6604890070292461 and parameters: {'subsample': 0.12200031263913508, 'dropout_rate': 0.15869627283628482, 'n_estimators': 494, 'learning_rate': 0.09505494537154666}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:23:16,933] Trial 85 finished with value: 0.661242158034085 and parameters: {'subsample': 0.10228331257134306, 'dropout_rate': 0.1318652086237005, 'n_estimators': 409, 'learning_rate': 0.09308775924596777}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:23:22,925] Trial 86 finished with value: 0.6514603870631426 and parameters: {'subsample': 0.16338876735167893, 'dropout_rate': 0.23232856056123916, 'n_estimators': 413, 'learning_rate': 0.09375536437833044}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:23:29,692] Trial 87 finished with value: 0.6621005271327975 and parameters: {'subsample': 0.10085899865477647, 'dropout_rate': 0.2072900429957874, 'n_estimators': 446, 'learning_rate': 0.08872622030163933}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:23:36,750] Trial 88 finished with value: 0.6539991378840402 and parameters: {'subsample': 0.16506256892213622, 'dropout_rate': 0.20446372048915498, 'n_estimators': 452, 'learning_rate': 0.09672595229917913}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6523605150214592
[I 2024-04-15 17:23:45,377] Trial 89 finished with value: 0.641083916706519 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.18405310197817268, 'n_estimators': 448, 'learning_rate': 0.09016733641089943}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:23:53,579] Trial 90 finished with value: 0.6491858996677189 and parameters: {'subsample': 0.223265940097236, 'dropout_rate': 0.15806466218360715, 'n_estimators': 465, 'learning_rate': 0.08808356114406508}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6781115879828327
[I 2024-04-15 17:24:00,109] Trial 91 finished with value: 0.6612637769846395 and parameters: {'subsample': 0.12232339965946021, 'dropout_rate': 0.1339773241626516, 'n_estimators': 407, 'learning_rate': 0.09358815753640348}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:24:07,105] Trial 92 finished with value: 0.6596448246253278 and parameters: {'subsample': 0.12038850786774134, 'dropout_rate': 0.21960750470691695, 'n_estimators': 408, 'learning_rate': 0.09410339704658359}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:24:14,537] Trial 93 finished with value: 0.6562732014364079 and parameters: {'subsample': 0.15301044243312817, 'dropout_rate': 0.13567818978666563, 'n_estimators': 431, 'learning_rate': 0.0899814667834966}. Best is trial 70 with value: 0.6636725336802511.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:24:20,533] Trial 94 finished with value: 0.6621952828768876 and parameters: {'subsample': 0.12514967286818043, 'dropout_rate': 0.1633221255536427, 'n_estimators': 385, 'learning_rate': 0.09726212284214504}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-15 17:24:29,220] Trial 95 finished with value: 0.6514351871886739 and parameters: {'subsample': 0.19879669801378733, 'dropout_rate': 0.1678537635046468, 'n_estimators': 479, 'learning_rate': 0.0964983786368335}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6866952789699571
[I 2024-04-15 17:24:36,635] Trial 96 finished with value: 0.6589606622259574 and parameters: {'subsample': 0.12580746759482828, 'dropout_rate': 0.18818052488976597, 'n_estimators': 426, 'learning_rate': 0.086570582753011}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:24:45,358] Trial 97 finished with value: 0.6514309120137719 and parameters: {'subsample': 0.15379123414878026, 'dropout_rate': 0.25465854986785086, 'n_estimators': 439, 'learning_rate': 0.09847945618605286}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6738197424892703
[I 2024-04-15 17:24:52,503] Trial 98 finished with value: 0.6507362872646181 and parameters: {'subsample': 0.24394875558768292, 'dropout_rate': 0.1583786439896771, 'n_estimators': 399, 'learning_rate': 0.09264177511085828}. Best is trial 70 with value: 0.6636725336802511.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392

[I 2024-04-15 17:24:58,725] A new study created in memory with name: no-name-608834d6-92ad-4f3d-8861-37d5fca521a9

Fold 5 C-index: 0.6824034334763949
[I 2024-04-15 17:24:58,715] Trial 99 finished with value: 0.6540102944848112 and parameters: {'subsample': 0.16720082446942383, 'dropout_rate': 0.12030874286826995, 'n_estimators': 386, 'learning_rate': 0.08399138629274774}. Best is trial 70 with value: 0.6636725336802511.


* Best trial for C-index:
 FrozenTrial(number=70, state=TrialState.COMPLETE, values=[0.6636725336802511], datetime_start=datetime.datetime(2024, 4, 15, 17, 21, 49, 85800), datetime_complete=datetime.datetime(2024, 4, 15, 17, 21, 53, 61167), params={'subsample': 0.10832939724965542, 'dropout_rate': 0.10222075562837932, 'n_estimators': 290, 'learning_rate': 0.07704376427520507}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=70, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10832939724965542, 'dropout_rate': 0.10222075562837932, 'n_estimators': 290, 'learning_rate': 0.07704376427520507}


* Best Score for C-index:
 0.6636725336802511

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2535208184290341
Fold 2 IBS: 0.23694039312201395
Fold 3 IBS: 0.3183278645100559
Fold 4 IBS: 0.2785272332047015
Fold 5 IBS: 0.26959701773388006
[I 2024-04-15 17:24:59,792] Trial 0 finished with value: 0.27138266539993705 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.4379931381955231
Fold 2 IBS: 0.38220982923025065
Fold 3 IBS: 0.3920321662913435
Fold 4 IBS: 0.3412768011671995
Fold 5 IBS: 0.33941908574786966
[I 2024-04-15 17:25:07,609] Trial 1 finished with value: 0.3785862041264373 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.3324678077695315
Fold 2 IBS: 0.277934644896449
Fold 3 IBS: 0.37028973305297364
Fold 4 IBS: 0.29747016904097373
Fold 5 IBS: 0.30753782579260386
[I 2024-04-15 17:25:09,310] Trial 2 finished with value: 0.31714003611050634 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.3184671128013938
Fold 2 IBS: 0.276517277228012
Fold 3 IBS: 0.37171315150390805
Fold 4 IBS: 0.2766993729668638
Fold 5 IBS: 0.32392753761654436
[I 2024-04-15 17:25:11,443] Trial 3 finished with value: 0.3134648904233444 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.32631801671576277
Fold 2 IBS: 0.2737223862745123
Fold 3 IBS: 0.3766738420399361
Fold 4 IBS: 0.2720299629576596
Fold 5 IBS: 0.3223149275469591
[I 2024-04-15 17:25:14,752] Trial 4 finished with value: 0.314211827106966 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.43183877461465453
Fold 2 IBS: 0.3462655068788492
Fold 3 IBS: 0.3901822518832906
Fold 4 IBS: 0.3158040918671078
Fold 5 IBS: 0.3240588862506669
[I 2024-04-15 17:25:19,058] Trial 5 finished with value: 0.36162990229891384 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.27138266539993705.
Fold 1 IBS: 0.23162026538239194
Fold 2 IBS: 0.2130450924041672
Fold 3 IBS: 0.2929798151511939
Fold 4 IBS: 0.2602468384417057
Fold 5 IBS: 0.24596662301082522
[I 2024-04-15 17:25:20,835] Trial 6 finished with value: 0.2487717268780568 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2487717268780568.
Fold 1 IBS: 0.2219624571251742
Fold 2 IBS: 0.20124848068903073
Fold 3 IBS: 0.2554464703379466
Fold 4 IBS: 0.22028035730313134
Fold 5 IBS: 0.21397872069101548
[I 2024-04-15 17:25:21,248] Trial 7 finished with value: 0.22258329722925968 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.26135001657957846
Fold 2 IBS: 0.24282456049458448
Fold 3 IBS: 0.326134406423236
Fold 4 IBS: 0.27402360123646585
Fold 5 IBS: 0.2768152873434484
[I 2024-04-15 17:25:23,312] Trial 8 finished with value: 0.27622957441546264 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.438775036769916
Fold 2 IBS: 0.35568555286291453
Fold 3 IBS: 0.390909578851063
Fold 4 IBS: 0.31218235322033017
Fold 5 IBS: 0.32722373811786437
[I 2024-04-15 17:25:28,776] Trial 9 finished with value: 0.3649552519644176 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.2460224099705921
Fold 2 IBS: 0.23086098108808756
Fold 3 IBS: 0.2288453379547681
Fold 4 IBS: 0.24136765896018506
Fold 5 IBS: 0.2281543805010059
[I 2024-04-15 17:25:29,118] Trial 10 finished with value: 0.23505015369492774 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.24222241773116046
Fold 2 IBS: 0.22722173122509534
Fold 3 IBS: 0.2286593447825781
Fold 4 IBS: 0.2395148036138026
Fold 5 IBS: 0.22443221144275918
[I 2024-04-15 17:25:29,389] Trial 11 finished with value: 0.23241010175907917 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.24246744390679062
Fold 2 IBS: 0.21305801372637204
Fold 3 IBS: 0.2967949999001774
Fold 4 IBS: 0.2283189562904766
Fold 5 IBS: 0.2425730377160065
[I 2024-04-15 17:25:29,934] Trial 12 finished with value: 0.24464249030796462 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.23944832000588395
Fold 2 IBS: 0.22451123143312443
Fold 3 IBS: 0.22879762094537542
Fold 4 IBS: 0.23820765139553346
Fold 5 IBS: 0.22173810615143869
[I 2024-04-15 17:25:30,238] Trial 13 finished with value: 0.23054058598627117 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.22826207452412578
Fold 2 IBS: 0.20671443688800192
Fold 3 IBS: 0.2838897565833488
Fold 4 IBS: 0.2304990846646447
Fold 5 IBS: 0.23724799446889894
[I 2024-04-15 17:25:31,056] Trial 14 finished with value: 0.23732266942580402 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.275392871065553
Fold 2 IBS: 0.25587915351862944
Fold 3 IBS: 0.34359360523637944
Fold 4 IBS: 0.26893592353517226
Fold 5 IBS: 0.29228774764528515
[I 2024-04-15 17:25:31,922] Trial 15 finished with value: 0.2872178602002039 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.2982726581292542
Fold 2 IBS: 0.2587141416930005
Fold 3 IBS: 0.3446079803152651
Fold 4 IBS: 0.2416951132692991
Fold 5 IBS: 0.30981663250359587
[I 2024-04-15 17:25:34,967] Trial 16 finished with value: 0.2906213051820829 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.22571204260462702
Fold 2 IBS: 0.21029571932609178
Fold 3 IBS: 0.23477013659701168
Fold 4 IBS: 0.23294813806507536
Fold 5 IBS: 0.2112667744029953
[I 2024-04-15 17:25:35,517] Trial 17 finished with value: 0.2229985621991602 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.22749628705840008
Fold 2 IBS: 0.208593559309439
Fold 3 IBS: 0.2860837988705294
Fold 4 IBS: 0.255694330022353
Fold 5 IBS: 0.23961625820762958
[I 2024-04-15 17:25:39,948] Trial 18 finished with value: 0.24349684669367022 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.22458664776493728
Fold 2 IBS: 0.20224835545019668

Fold 3 IBS: 0.27412770407771303
Fold 4 IBS: 0.2250727043053573
Fold 5 IBS: 0.22804546200325004
[I 2024-04-15 17:25:41,198] Trial 19 finished with value: 0.23081617472029087 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.22813963029627435
Fold 2 IBS: 0.21261919492535192
Fold 3 IBS: 0.2328032377684259
Fold 4 IBS: 0.23177471930860935
Fold 5 IBS: 0.21241390693232276
[I 2024-04-15 17:25:42,171] Trial 20 finished with value: 0.22355013784619687 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.23294882482388735
Fold 2 IBS: 0.2172731528360657
Fold 3 IBS: 0.23037554967791973
Fold 4 IBS: 0.23393962524579212
Fold 5 IBS: 0.21554329357937044
[I 2024-04-15 17:25:42,935] Trial 21 finished with value: 0.22601608923260708 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.22457381812654392
Fold 2 IBS: 0.20893564288887
Fold 3 IBS: 0.23611424341865672
Fold 4 IBS: 0.23267189537604366
Fold 5 IBS: 0.21078105893610707
[I 2024-04-15 17:25:43,562] Trial 22 finished with value: 0.22261533174924425 and parameters: {'subsample': 0.8615610863035676, 'dropout_rate': 0.7601905131808098, 'n_estimators': 57, 'learning_rate': 0.019334429052945145}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.2719235052333098
Fold 2 IBS: 0.23764489493573734
Fold 3 IBS: 0.3193018171397408
Fold 4 IBS: 0.2836424571696349
Fold 5 IBS: 0.2702613255072474
[I 2024-04-15 17:25:45,171] Trial 23 finished with value: 0.27655479999713406 and parameters: {'subsample': 0.8557281003254902, 'dropout_rate': 0.618865896035061, 'n_estimators': 150, 'learning_rate': 0.04186582141545488}. Best is trial 7 with value: 0.22258329722925968.
Fold 1 IBS: 0.22147474510826237
Fold 2 IBS: 0.2056747916191557
Fold 3 IBS: 0.24049201615940596
Fold 4 IBS: 0.23256814236182405
Fold 5 IBS: 0.21033940163812648
[I 2024-04-15 17:25:45,752] Trial 24 finished with value: 0.22210981937735488 and parameters: {'subsample': 0.8736292350257677, 'dropout_rate': 0.9758883725345413, 'n_estimators': 56, 'learning_rate': 0.02427957701685606}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.2294989380094321
Fold 2 IBS: 0.2099824153827439
Fold 3 IBS: 0.23574856019681506
Fold 4 IBS: 0.22595992491113648
Fold 5 IBS: 0.21123756273226652
[I 2024-04-15 17:25:46,288] Trial 25 finished with value: 0.2224854802464788 and parameters: {'subsample': 0.19468056412788132, 'dropout_rate': 0.9897789595635863, 'n_estimators': 40, 'learning_rate': 0.025002990823540957}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.2322614941690023
Fold 2 IBS: 0.20634960697834218
Fold 3 IBS: 0.293244355342229
Fold 4 IBS: 0.23139018053165933
Fold 5 IBS: 0.23983016494558368
[I 2024-04-15 17:25:47,248] Trial 26 finished with value: 0.24061516039336328 and parameters: {'subsample': 0.20966372435124492, 'dropout_rate': 0.9922976382051985, 'n_estimators': 92, 'learning_rate': 0.04553017387255954}. Best is trial 24 with value: 0.22210981937735488.
Fold 1 IBS: 0.2289587867115224
Fold 2 IBS: 0.20808365799299086
Fold 3 IBS: 0.23587267887970362
Fold 4 IBS: 0.2236284857048249
Fold 5 IBS: 0.21094836018492705
[I 2024-04-15 17:25:47,768] Trial 27 finished with value: 0.22149839389479378 and parameters: {'subsample': 0.1957599112234488, 'dropout_rate': 0.9027419458320135, 'n_estimators': 35, 'learning_rate': 0.030307532796347948}. Best is trial 27 with value: 0.22149839389479378.
Fold 1 IBS: 0.25734463190270546
Fold 2 IBS: 0.23888815932058247
Fold 3 IBS: 0.3255086702641682
Fold 4 IBS: 0.23931305439069492
Fold 5 IBS: 0.267751531479734
[I 2024-04-15 17:25:49,785] Trial 28 finished with value: 0.265761209471577 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.9375919429058303, 'n_estimators': 226, 'learning_rate': 0.029519964358367873}. Best is trial 27 with value: 0.22149839389479378.
Fold 1 IBS: 0.2242773778117604
Fold 2 IBS: 0.20347431711760902
Fold 3 IBS: 0.27644641384757823
Fold 4 IBS: 0.23538705027752083
Fold 5 IBS: 0.23172572018976656
[I 2024-04-15 17:25:50,680] Trial 29 finished with value: 0.234262175848847 and parameters: {'subsample': 0.42998431516305374, 'dropout_rate': 0.927286410998384, 'n_estimators': 123, 'learning_rate': 0.025782557435654437}. Best is trial 27 with value: 0.22149839389479378.
Fold 1 IBS: 0.2446005120962175
Fold 2 IBS: 0.22859296039604643
Fold 3 IBS: 0.2286867229848354
Fold 4 IBS: 0.2392156906696232
Fold 5 IBS: 0.22622108196361204
[I 2024-04-15 17:25:51,033] Trial 30 finished with value: 0.23346339362206692 and parameters: {'subsample': 0.2544227872032339, 'dropout_rate': 0.8714644301078432, 'n_estimators': 28, 'learning_rate': 0.004298613699110613}. Best is trial 27 with value: 0.22149839389479378.
Fold 1 IBS: 0.22768704710386217
Fold 2 IBS: 0.20794357806715316
Fold 3 IBS: 0.23915191946251055
Fold 4 IBS: 0.21962277259177673
Fold 5 IBS: 0.21058831635314107
[I 2024-04-15 17:25:51,437] Trial 31 finished with value: 0.22099872671568876 and parameters: {'subsample': 0.1642548972610388, 'dropout_rate': 0.9934257769141778, 'n_estimators': 33, 'learning_rate': 0.03479765769380795}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.22380326971399786
Fold 2 IBS: 0.19838664904519562
Fold 3 IBS: 0.27266220447024664
Fold 4 IBS: 0.21570586466293817
Fold 5 IBS: 0.2192445276292213
[I 2024-04-15 17:25:52,144] Trial 32 finished with value: 0.22596050310431992 and parameters: {'subsample': 0.1823374077872404, 'dropout_rate': 0.9883076180722741, 'n_estimators': 88, 'learning_rate': 0.034813085173865374}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.23139664081414563
Fold 2 IBS: 0.20801724838185884
Fold 3 IBS: 0.29231633282957525
Fold 4 IBS: 0.22831209477343067
Fold 5 IBS: 0.24121520022564358
[I 2024-04-15 17:25:53,283] Trial 33 finished with value: 0.2402515034049308 and parameters: {'subsample': 0.27671374354153455, 'dropout_rate': 0.9229161518071803, 'n_estimators': 147, 'learning_rate': 0.027997278046075002}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.23511206363156492
Fold 2 IBS: 0.21548727930344208
Fold 3 IBS: 0.2308708252582198
Fold 4 IBS: 0.22721884809722498
Fold 5 IBS: 0.21685213366721248
[I 2024-04-15 17:25:53,701] Trial 34 finished with value: 0.22510822999153285 and parameters: {'subsample': 0.16723990561535457, 'dropout_rate': 0.8453694903966474, 'n_estimators': 30, 'learning_rate': 0.020684756718428673}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.23787370285057755
Fold 2 IBS: 0.21714429505784283
Fold 3 IBS: 0.23025254874495477
Fold 4 IBS: 0.22854298362928344
Fold 5 IBS: 0.21725395077984477
[I 2024-04-15 17:25:53,969] Trial 35 finished with value: 0.22621349621250064 and parameters: {'subsample': 0.24430564869860838, 'dropout_rate': 0.9999397033924764, 'n_estimators': 9, 'learning_rate': 0.061333517978478365}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.36577991372565133
Fold 2 IBS: 0.2886726570144008
Fold 3 IBS: 0.38272018580748274
Fold 4 IBS: 0.29455240002912136
Fold 5 IBS: 0.322663330683905
[I 2024-04-15 17:25:59,069] Trial 36 finished with value: 0.33087769745211226 and parameters: {'subsample': 0.29764645512407023, 'dropout_rate': 0.9337508122491033, 'n_estimators': 421, 'learning_rate': 0.03755471269142438}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.3063321868333615
Fold 2 IBS: 0.2584549161481036
Fold 3 IBS: 0.34259310813017946
Fold 4 IBS: 0.2920730369354221
Fold 5 IBS: 0.29090854728101256
[I 2024-04-15 17:26:00,578] Trial 37 finished with value: 0.2980723590656158 and parameters: {'subsample': 0.5820694569830719, 'dropout_rate': 0.8881536252337234, 'n_estimators': 170, 'learning_rate': 0.04881460059329259}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.22281200447803512
Fold 2 IBS: 0.20075632893285386
Fold 3 IBS: 0.25941370640598865

Fold 4 IBS: 0.23024202553473688
Fold 5 IBS: 0.2195522967050084
[I 2024-04-15 17:26:01,345] Trial 38 finished with value: 0.22655527241132453 and parameters: {'subsample': 0.7340144528858092, 'dropout_rate': 0.13272164755980653, 'n_estimators': 83, 'learning_rate': 0.030782657817155126}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.2332317850992294
Fold 2 IBS: 0.2182381217008508
Fold 3 IBS: 0.2300773630902979
Fold 4 IBS: 0.23503197229669454
Fold 5 IBS: 0.216451746174902
[I 2024-04-15 17:26:01,802] Trial 39 finished with value: 0.22660619767239493 and parameters: {'subsample': 0.7926935273119843, 'dropout_rate': 0.7752839243709247, 'n_estimators': 33, 'learning_rate': 0.01715036845928685}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.2602657323081961
Fold 2 IBS: 0.2421911304010384
Fold 3 IBS: 0.3269201446440632
Fold 4 IBS: 0.26764332948211106
Fold 5 IBS: 0.27728378008086335
[I 2024-04-15 17:26:02,992] Trial 40 finished with value: 0.27486082338325446 and parameters: {'subsample': 0.4109818263854602, 'dropout_rate': 0.27073406810212547, 'n_estimators': 128, 'learning_rate': 0.05619185952061703}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.2240130395831805
Fold 2 IBS: 0.20244608540723918
Fold 3 IBS: 0.24847249439404437
Fold 4 IBS: 0.22205644796325658
Fold 5 IBS: 0.21114519450463792
[I 2024-04-15 17:26:03,433] Trial 41 finished with value: 0.2216266523704717 and parameters: {'subsample': 0.36680465681911656, 'dropout_rate': 0.9483868813208481, 'n_estimators': 41, 'learning_rate': 0.04305510856404134}. Best is trial 31 with value: 0.22099872671568876.
Fold 1 IBS: 0.23316485016569014
Fold 2 IBS: 0.20460946003578975
Fold 3 IBS: 0.2332377201312376
Fold 4 IBS: 0.21698869589814138
Fold 5 IBS: 0.20956214694695516
[I 2024-04-15 17:26:03,933] Trial 42 finished with value: 0.21951257463556278 and parameters: {'subsample': 0.10490536079056777, 'dropout_rate': 0.9495881903187781, 'n_estimators': 39, 'learning_rate': 0.03362577110353394}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22734434979921062
Fold 2 IBS: 0.19747304405921667
Fold 3 IBS: 0.27534536474577254
Fold 4 IBS: 0.21465418747414622
Fold 5 IBS: 0.22405699769551327
[I 2024-04-15 17:26:04,616] Trial 43 finished with value: 0.22777478875477186 and parameters: {'subsample': 0.13063721175964121, 'dropout_rate': 0.8275585860839022, 'n_estimators': 77, 'learning_rate': 0.044809750792882914}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2455781401032844
Fold 2 IBS: 0.22977066579824554
Fold 3 IBS: 0.2286950281461665
Fold 4 IBS: 0.2399410758575014
Fold 5 IBS: 0.22812889107110912
[I 2024-04-15 17:26:04,931] Trial 44 finished with value: 0.2344227601952614 and parameters: {'subsample': 0.10345695773991653, 'dropout_rate': 0.9521609362749961, 'n_estimators': 3, 'learning_rate': 0.033795897462489996}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2507352775315491
Fold 2 IBS: 0.23430951705084443
Fold 3 IBS: 0.31867853218416703
Fold 4 IBS: 0.2458811958733822
Fold 5 IBS: 0.26601162966602193
[I 2024-04-15 17:26:05,884] Trial 45 finished with value: 0.26312323046119296 and parameters: {'subsample': 0.23412363901238495, 'dropout_rate': 0.8898632551487502, 'n_estimators': 114, 'learning_rate': 0.05367082760743848}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22140199140895467
Fold 2 IBS: 0.2030824253780379
Fold 3 IBS: 0.24657696705457927
Fold 4 IBS: 0.230459217946316
Fold 5 IBS: 0.21148356060530699
[I 2024-04-15 17:26:06,380] Trial 46 finished with value: 0.22260083247863896 and parameters: {'subsample': 0.5396018936273262, 'dropout_rate': 0.8960830951190915, 'n_estimators': 43, 'learning_rate': 0.03904949427048994}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22959888860043107
Fold 2 IBS: 0.20855088338752084
Fold 3 IBS: 0.23779287137896932
Fold 4 IBS: 0.22018579908134542
Fold 5 IBS: 0.2109248681012541
[I 2024-04-15 17:26:06,814] Trial 47 finished with value: 0.22141066210990418 and parameters: {'subsample': 0.15279143633747583, 'dropout_rate': 0.9540737794713248, 'n_estimators': 23, 'learning_rate': 0.04926221030432518}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22783431757290748
Fold 2 IBS: 0.20632800842394022
Fold 3 IBS: 0.24113740297422434
Fold 4 IBS: 0.21886586593134008
Fold 5 IBS: 0.2101396298367815
[I 2024-04-15 17:26:07,183] Trial 48 finished with value: 0.2208610449478387 and parameters: {'subsample': 0.15145384798566433, 'dropout_rate': 0.415839155364984, 'n_estimators': 19, 'learning_rate': 0.06836817801132411}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22709008243162576
Fold 2 IBS: 0.2050528609969348
Fold 3 IBS: 0.2431442005359697
Fold 4 IBS: 0.21764879980658716
Fold 5 IBS: 0.20976111462441818
[I 2024-04-15 17:26:07,549] Trial 49 finished with value: 0.22053941167910712 and parameters: {'subsample': 0.14926593560989637, 'dropout_rate': 0.414511571454463, 'n_estimators': 19, 'learning_rate': 0.07389525005693605}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22916785904990697
Fold 2 IBS: 0.20571204828796724
Fold 3 IBS: 0.23878541122931002
Fold 4 IBS: 0.22035765064105417
Fold 5 IBS: 0.21125988204220675
[I 2024-04-15 17:26:07,921] Trial 50 finished with value: 0.221056570250089 and parameters: {'subsample': 0.15106612114079368, 'dropout_rate': 0.42732372125147283, 'n_estimators': 16, 'learning_rate': 0.07107774798498834}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22703462357155393
Fold 2 IBS: 0.20407670123313673
Fold 3 IBS: 0.24769066512791954
Fold 4 IBS: 0.21310724128298825
Fold 5 IBS: 0.2086605476670122
[I 2024-04-15 17:26:08,351] Trial 51 finished with value: 0.22011395577652215 and parameters: {'subsample': 0.1591822424744946, 'dropout_rate': 0.4238692185538518, 'n_estimators': 22, 'learning_rate': 0.07629241959049295}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.23048597430488638
Fold 2 IBS: 0.20287117659211273
Fold 3 IBS: 0.24072406698808904
Fold 4 IBS: 0.22212761099945522
Fold 5 IBS: 0.2098893606065326
[I 2024-04-15 17:26:08,748] Trial 52 finished with value: 0.2212196378982152 and parameters: {'subsample': 0.13934578583302556, 'dropout_rate': 0.42442064699063087, 'n_estimators': 16, 'learning_rate': 0.07767478491248025}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2466419883568276
Fold 2 IBS: 0.22988709738539187
Fold 3 IBS: 0.2287639775038001
Fold 4 IBS: 0.23962547714123997
Fold 5 IBS: 0.22745586868979856
[I 2024-04-15 17:26:09,073] Trial 53 finished with value: 0.2344748818154116 and parameters: {'subsample': 0.23132700406205736, 'dropout_rate': 0.33516226143176175, 'n_estimators': 1, 'learning_rate': 0.06992655054544837}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.24136942435676384
Fold 2 IBS: 0.21355211188066386
Fold 3 IBS: 0.3057917018445721
Fold 4 IBS: 0.22770951318399466
Fold 5 IBS: 0.2507778615324913
[I 2024-04-15 17:26:09,832] Trial 54 finished with value: 0.24784012255969717 and parameters: {'subsample': 0.1283198360712249, 'dropout_rate': 0.46502988014748375, 'n_estimators': 68, 'learning_rate': 0.0817406969690033}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.33704487871770744
Fold 2 IBS: 0.2717710528826749
Fold 3 IBS: 0.3641036920150662
Fold 4 IBS: 0.24539194847713128
Fold 5 IBS: 0.32224387175711766
[I 2024-04-15 17:26:13,169] Trial 55 finished with value: 0.3081110887699395 and parameters: {'subsample': 0.10736721118708424, 'dropout_rate': 0.4975888273022048, 'n_estimators': 265, 'learning_rate': 0.06477535470253355}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22684305064306826
Fold 2 IBS: 0.2049004889086507
Fold 3 IBS: 0.24063347128791554
Fold 4 IBS: 0.218979279659072
Fold 5 IBS: 0.20943479464516299
[I 2024-04-15 17:26:13,527] Trial 56 finished with value: 0.22015821702877386 and parameters: {'subsample': 0.30024528784369914, 'dropout_rate': 0.3380757651788332, 'n_estimators': 19, 'learning_rate': 0.07474010092086214}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2671010050502332
Fold 2 IBS: 0.24072952432593725
Fold 3 IBS: 0.3332939421793399
Fold 4 IBS: 0.25730328079224113

Fold 5 IBS: 0.28393992071489904
[I 2024-04-15 17:26:14,646] Trial 57 finished with value: 0.2764735346125301 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.3333949349209909, 'n_estimators': 102, 'learning_rate': 0.07586937026396535}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2459075656523321
Fold 2 IBS: 0.20109168779305825
Fold 3 IBS: 0.2909620806928277
Fold 4 IBS: 0.21878444537392763
Fold 5 IBS: 0.23150502717743096
[I 2024-04-15 17:26:15,379] Trial 58 finished with value: 0.23765016133791533 and parameters: {'subsample': 0.22421139413625618, 'dropout_rate': 0.1983473170754516, 'n_estimators': 51, 'learning_rate': 0.08704357466884936}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.4024929155383612
Fold 2 IBS: 0.32055960805224804
Fold 3 IBS: 0.3911151691769955
Fold 4 IBS: 0.2590462193700875
Fold 5 IBS: 0.3349029305354637
[I 2024-04-15 17:26:20,808] Trial 59 finished with value: 0.3416233685346312 and parameters: {'subsample': 0.1616220754173696, 'dropout_rate': 0.3783825622239444, 'n_estimators': 372, 'learning_rate': 0.08087170926391614}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.24422195598782917
Fold 2 IBS: 0.2124583510726786
Fold 3 IBS: 0.30133188412079726
Fold 4 IBS: 0.23193978705764148
Fold 5 IBS: 0.25205379240173403
[I 2024-04-15 17:26:21,678] Trial 60 finished with value: 0.24840115412813613 and parameters: {'subsample': 0.31402346729349156, 'dropout_rate': 0.2907575899484439, 'n_estimators': 77, 'learning_rate': 0.0658825712632195}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2250484294285184
Fold 2 IBS: 0.2065409050666494
Fold 3 IBS: 0.24270912603517175
Fold 4 IBS: 0.21830232464878618
Fold 5 IBS: 0.20918864828165162
[I 2024-04-15 17:26:22,188] Trial 61 finished with value: 0.22035788669215545 and parameters: {'subsample': 0.1635416093926001, 'dropout_rate': 0.4299643888759822, 'n_estimators': 19, 'learning_rate': 0.07160971793068377}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.23140981387360118
Fold 2 IBS: 0.2036116767934629
Fold 3 IBS: 0.2881953545227118
Fold 4 IBS: 0.20844929796555042
Fold 5 IBS: 0.22466462652658498
[I 2024-04-15 17:26:23,064] Trial 62 finished with value: 0.23126615393638222 and parameters: {'subsample': 0.17727372310542552, 'dropout_rate': 0.51325633676466, 'n_estimators': 51, 'learning_rate': 0.07261091171838063}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22792275826713837
Fold 2 IBS: 0.20815439570764718
Fold 3 IBS: 0.23768121015419771
Fold 4 IBS: 0.2208195717867943
Fold 5 IBS: 0.21026016085666768
[I 2024-04-15 17:26:23,444] Trial 63 finished with value: 0.22096761935448903 and parameters: {'subsample': 0.2675273969344081, 'dropout_rate': 0.4052852349084601, 'n_estimators': 20, 'learning_rate': 0.05928377620609686}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2293874316145535
Fold 2 IBS: 0.20907726990684425
Fold 3 IBS: 0.23589397388520036
Fold 4 IBS: 0.221084511718484
Fold 5 IBS: 0.21165839312889081
[I 2024-04-15 17:26:23,788] Trial 64 finished with value: 0.2214203160507946 and parameters: {'subsample': 0.267498122129594, 'dropout_rate': 0.41828270180344995, 'n_estimators': 17, 'learning_rate': 0.06089013370653119}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.23534898532564905
Fold 2 IBS: 0.21296442954908948
Fold 3 IBS: 0.2946886264393929
Fold 4 IBS: 0.22891110694483613
Fold 5 IBS: 0.24705847697485264
[I 2024-04-15 17:26:24,482] Trial 65 finished with value: 0.24379432504676407 and parameters: {'subsample': 0.3413760032353245, 'dropout_rate': 0.38256599891921417, 'n_estimators': 68, 'learning_rate': 0.06606523178784873}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2300970127450158
Fold 2 IBS: 0.21084220223268196
Fold 3 IBS: 0.23374950159568333
Fold 4 IBS: 0.22228721941396928
Fold 5 IBS: 0.21525321433444983
[I 2024-04-15 17:26:24,933] Trial 66 finished with value: 0.22244583006436006 and parameters: {'subsample': 0.2098706106847209, 'dropout_rate': 0.5615610344365004, 'n_estimators': 14, 'learning_rate': 0.058855527326948466}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.4114775478495499
Fold 2 IBS: 0.3434825683178054
Fold 3 IBS: 0.39025211055402687
Fold 4 IBS: 0.3013112548176609
Fold 5 IBS: 0.3259370644845777
[I 2024-04-15 17:26:29,263] Trial 67 finished with value: 0.3544921092047241 and parameters: {'subsample': 0.4590303067651391, 'dropout_rate': 0.35021251364269124, 'n_estimators': 302, 'learning_rate': 0.07870559048371892}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.42161859169559585
Fold 2 IBS: 0.3222027612111774
Fold 3 IBS: 0.38859253526670523
Fold 4 IBS: 0.2669371447983459
Fold 5 IBS: 0.3339713719063884
[I 2024-04-15 17:26:39,598] Trial 68 finished with value: 0.34666448097564256 and parameters: {'subsample': 0.12182898319404331, 'dropout_rate': 0.3107082453275345, 'n_estimators': 496, 'learning_rate': 0.08734957510605876}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.27130863331971955
Fold 2 IBS: 0.229828855146875
Fold 3 IBS: 0.3239444377077993
Fold 4 IBS: 0.23603448075041722
Fold 5 IBS: 0.274663933861954
[I 2024-04-15 17:26:40,639] Trial 69 finished with value: 0.26715606815735293 and parameters: {'subsample': 0.2148208168559494, 'dropout_rate': 0.21157540401717592, 'n_estimators': 105, 'learning_rate': 0.07451141466375089}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.2320471726135753
Fold 2 IBS: 0.20458964572166227
Fold 3 IBS: 0.2916722034074478
Fold 4 IBS: 0.23092463321548776
Fold 5 IBS: 0.2359071997537316
[I 2024-04-15 17:26:41,610] Trial 70 finished with value: 0.23902817094238094 and parameters: {'subsample': 0.2515922380974621, 'dropout_rate': 0.44376319371267514, 'n_estimators': 49, 'learning_rate': 0.08384040257023583}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22355596885984744
Fold 2 IBS: 0.1985322464241219
Fold 3 IBS: 0.2623916226999861
Fold 4 IBS: 0.21233112225342768
Fold 5 IBS: 0.21057680311797014
[I 2024-04-15 17:26:42,513] Trial 71 finished with value: 0.22147755267107067 and parameters: {'subsample': 0.17434440598332268, 'dropout_rate': 0.46993436226327695, 'n_estimators': 33, 'learning_rate': 0.06894834940015668}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.24601105083099187
Fold 2 IBS: 0.22957254948546518
Fold 3 IBS: 0.22880021958522284
Fold 4 IBS: 0.240362509587123
Fold 5 IBS: 0.22702308041433625
[I 2024-04-15 17:26:42,875] Trial 72 finished with value: 0.23435388198062782 and parameters: {'subsample': 0.1520069772581267, 'dropout_rate': 0.40272952098673587, 'n_estimators': 1, 'learning_rate': 0.06337031741556744}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22345441632422072
Fold 2 IBS: 0.20000789575455574
Fold 3 IBS: 0.25061262968939696
Fold 4 IBS: 0.21563715655823532
Fold 5 IBS: 0.20807796760227698
[I 2024-04-15 17:26:43,598] Trial 73 finished with value: 0.21955801318573717 and parameters: {'subsample': 0.19050012642937825, 'dropout_rate': 0.36805666413335814, 'n_estimators': 25, 'learning_rate': 0.07366226015063637}. Best is trial 42 with value: 0.21951257463556278.
Fold 1 IBS: 0.22997352348491193
Fold 2 IBS: 0.20086448380772756
Fold 3 IBS: 0.23244914864498278
Fold 4 IBS: 0.21746925747986334
Fold 5 IBS: 0.20938818076249163
[I 2024-04-15 17:26:44,092] Trial 74 finished with value: 0.21802891883599546 and parameters: {'subsample': 0.10090556122023636, 'dropout_rate': 0.3788374747846416, 'n_estimators': 22, 'learning_rate': 0.07386328482560535}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.23807005991180671
Fold 2 IBS: 0.20155403485021783
Fold 3 IBS: 0.28038958332147706
Fold 4 IBS: 0.20955284843566355
Fold 5 IBS: 0.23205031702337806
[I 2024-04-15 17:26:44,745] Trial 75 finished with value: 0.23232336870850862 and parameters: {'subsample': 0.10397072126748086, 'dropout_rate': 0.3708713588045184, 'n_estimators': 62, 'learning_rate': 0.0766419144142094}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.22211397341156733
Fold 2 IBS: 0.19883057118300138
Fold 3 IBS: 0.2625200145507092
Fold 4 IBS: 0.21366831519768303

Fold 5 IBS: 0.21153802617953904
[I 2024-04-15 17:26:45,210] Trial 76 finished with value: 0.2217341801045 and parameters: {'subsample': 0.18496931802695063, 'dropout_rate': 0.31169806189512894, 'n_estimators': 26, 'learning_rate': 0.09087507715614321}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.23097652216923997
Fold 2 IBS: 0.19214396438491765
Fold 3 IBS: 0.26995098233323767
Fold 4 IBS: 0.21648924342245823
Fold 5 IBS: 0.21382651114907483
[I 2024-04-15 17:26:45,823] Trial 77 finished with value: 0.2246774446917857 and parameters: {'subsample': 0.1250123010159347, 'dropout_rate': 0.23331782495639364, 'n_estimators': 44, 'learning_rate': 0.07309219922663512}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2426433538820121
Fold 2 IBS: 0.21530675860757498
Fold 3 IBS: 0.30748030302386065
Fold 4 IBS: 0.23702690393356035
Fold 5 IBS: 0.2505278119797517
[I 2024-04-15 17:26:46,647] Trial 78 finished with value: 0.25059702628535196 and parameters: {'subsample': 0.21237539524459476, 'dropout_rate': 0.4441910212883944, 'n_estimators': 79, 'learning_rate': 0.06750196121547801}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2332274651030988
Fold 2 IBS: 0.2093893883126958
Fold 3 IBS: 0.2341035312764809
Fold 4 IBS: 0.2265355201840657
Fold 5 IBS: 0.21272110237228148
[I 2024-04-15 17:26:47,132] Trial 79 finished with value: 0.22319540144972452 and parameters: {'subsample': 0.14237108392194037, 'dropout_rate': 0.3514637182348411, 'n_estimators': 11, 'learning_rate': 0.07954442524668488}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.3512239436838076
Fold 2 IBS: 0.28427556746443716
Fold 3 IBS: 0.38351352171421454
Fold 4 IBS: 0.26128859778170727
Fold 5 IBS: 0.32474949724562224
[I 2024-04-15 17:26:49,432] Trial 80 finished with value: 0.3210102255779578 and parameters: {'subsample': 0.1905958786262341, 'dropout_rate': 0.569629946992423, 'n_estimators': 199, 'learning_rate': 0.08401276211402568}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.22351353576130037
Fold 2 IBS: 0.20127176655911724
Fold 3 IBS: 0.24824995443583472
Fold 4 IBS: 0.21302974557538853
Fold 5 IBS: 0.20974389537122495
[I 2024-04-15 17:26:49,874] Trial 81 finished with value: 0.21916177954057314 and parameters: {'subsample': 0.26447649597182676, 'dropout_rate': 0.4072247962416464, 'n_estimators': 25, 'learning_rate': 0.07033190189860032}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2242167980495715
Fold 2 IBS: 0.19970043784850078
Fold 3 IBS: 0.2699122223708821
Fold 4 IBS: 0.21093566828462715
Fold 5 IBS: 0.2137521523590791
[I 2024-04-15 17:26:50,535] Trial 82 finished with value: 0.22370345578253215 and parameters: {'subsample': 0.16343446860570662, 'dropout_rate': 0.489679588874498, 'n_estimators': 37, 'learning_rate': 0.07183736015806111}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.23005919157990556
Fold 2 IBS: 0.19092124167881577
Fold 3 IBS: 0.2718161938068239
Fold 4 IBS: 0.21453879778501875
Fold 5 IBS: 0.2141636161735287
[I 2024-04-15 17:26:51,288] Trial 83 finished with value: 0.2242998082048185 and parameters: {'subsample': 0.10373830412871735, 'dropout_rate': 0.525418335005675, 'n_estimators': 48, 'learning_rate': 0.0747115517498492}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.22531848652645
Fold 2 IBS: 0.2013625648883208
Fold 3 IBS: 0.2494143766001984
Fold 4 IBS: 0.21648981436184975
Fold 5 IBS: 0.21193386570828496
[I 2024-04-15 17:26:51,752] Trial 84 finished with value: 0.2209038216170208 and parameters: {'subsample': 0.3084108155074231, 'dropout_rate': 0.3940884341948294, 'n_estimators': 27, 'learning_rate': 0.06855780736049233}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.4470325305191807
Fold 2 IBS: 0.3732809190202329
Fold 3 IBS: 0.39188545790594737
Fold 4 IBS: 0.2866229588318424
Fold 5 IBS: 0.3352496669501178
[I 2024-04-15 17:27:01,397] Trial 85 finished with value: 0.3668143066454642 and parameters: {'subsample': 0.24155237148457143, 'dropout_rate': 0.44902582421572335, 'n_estimators': 475, 'learning_rate': 0.08311844784518185}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.23523961473172464
Fold 2 IBS: 0.20505876451918148
Fold 3 IBS: 0.29517127780360525
Fold 4 IBS: 0.22266444892503356
Fold 5 IBS: 0.23696774412131807
[I 2024-04-15 17:27:02,210] Trial 86 finished with value: 0.2390203700201726 and parameters: {'subsample': 0.131130138035424, 'dropout_rate': 0.3637853376879819, 'n_estimators': 61, 'learning_rate': 0.0771990372421008}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2290919288952266
Fold 2 IBS: 0.20614404458714813
Fold 3 IBS: 0.2384964013079186
Fold 4 IBS: 0.22210882514564773
Fold 5 IBS: 0.2108300096484128
[I 2024-04-15 17:27:02,629] Trial 87 finished with value: 0.22133424191687076 and parameters: {'subsample': 0.1964426878269729, 'dropout_rate': 0.2683102029419525, 'n_estimators': 13, 'learning_rate': 0.09094496933763835}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.22422510861707665
Fold 2 IBS: 0.20023170079263877
Fold 3 IBS: 0.2504954402979843
Fold 4 IBS: 0.2154380946501585
Fold 5 IBS: 0.2109019303731004
[I 2024-04-15 17:27:03,091] Trial 88 finished with value: 0.22025845494619173 and parameters: {'subsample': 0.2812229414645135, 'dropout_rate': 0.3177590661135568, 'n_estimators': 27, 'learning_rate': 0.07120581179920576}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2638373084125338
Fold 2 IBS: 0.24038769503847504
Fold 3 IBS: 0.3266569846224234
Fold 4 IBS: 0.2505410870983154
Fold 5 IBS: 0.27772236925319854
[I 2024-04-15 17:27:04,161] Trial 89 finished with value: 0.2718290888849892 and parameters: {'subsample': 0.33720257023410416, 'dropout_rate': 0.29595977091731385, 'n_estimators': 92, 'learning_rate': 0.07986941904185671}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2237810382577003
Fold 2 IBS: 0.19631557641550787
Fold 3 IBS: 0.26244621401328067
Fold 4 IBS: 0.21781728239736436
Fold 5 IBS: 0.2164623457138435
[I 2024-04-15 17:27:04,677] Trial 90 finished with value: 0.2233644913595393 and parameters: {'subsample': 0.2825696333046569, 'dropout_rate': 0.3312094150845817, 'n_estimators': 39, 'learning_rate': 0.06395308772119339}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2453214375424264
Fold 2 IBS: 0.23005174640944645
Fold 3 IBS: 0.2288109338697402
Fold 4 IBS: 0.24091555157621758
Fold 5 IBS: 0.22728644398387407
[I 2024-04-15 17:27:05,079] Trial 91 finished with value: 0.2344772226763409 and parameters: {'subsample': 0.6873688859467479, 'dropout_rate': 0.6721431980032739, 'n_estimators': 1, 'learning_rate': 0.07122356335894309}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.2227621699842151
Fold 2 IBS: 0.19944694041236954
Fold 3 IBS: 0.2487870496514642
Fold 4 IBS: 0.21541068492627188
Fold 5 IBS: 0.20876921728174916
[I 2024-04-15 17:27:05,503] Trial 92 finished with value: 0.219035212451214 and parameters: {'subsample': 0.22346150143255283, 'dropout_rate': 0.42379721749458377, 'n_estimators': 24, 'learning_rate': 0.0746611969005367}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.22536890752617486
Fold 2 IBS: 0.20043458370823025
Fold 3 IBS: 0.2530905346576004
Fold 4 IBS: 0.22230525880042015
Fold 5 IBS: 0.2126690585894278
[I 2024-04-15 17:27:05,997] Trial 93 finished with value: 0.2227736686563707 and parameters: {'subsample': 0.37920057305616217, 'dropout_rate': 0.24463101231006923, 'n_estimators': 28, 'learning_rate': 0.07417669100353304}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.23600752792560234
Fold 2 IBS: 0.21532873117421505
Fold 3 IBS: 0.2969004275589595
Fold 4 IBS: 0.24510491757074304
Fold 5 IBS: 0.24819681949616673
[I 2024-04-15 17:27:06,679] Trial 94 finished with value: 0.2483076847451373 and parameters: {'subsample': 0.5143282301365409, 'dropout_rate': 0.3870403883668605, 'n_estimators': 60, 'learning_rate': 0.0762789512416128}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.24181032492977908
Fold 2 IBS: 0.21124696997027104
Fold 3 IBS: 0.30362250724450607
Fold 4 IBS: 0.2238200313420951
Fold 5 IBS: 0.24686384273490708
[I 2024-04-15 17:27:07,416] Trial 95 finished with value: 0.24547273524431165 and parameters: {'subsample': 0.22916652621219064, 'dropout_rate': 0.47549331043704346, 'n_estimators': 72, 'learning_rate': 0.07065869330294651}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.22179179410127348

Fold 2 IBS: 0.19781108710453746
Fold 3 IBS: 0.26824641091261114
Fold 4 IBS: 0.2219303508164059
Fold 5 IBS: 0.21776871147453294
[I 2024-04-15 17:27:07,946] Trial 96 finished with value: 0.22550967088187218 and parameters: {'subsample': 0.25417895487176095, 'dropout_rate': 0.4365555547853381, 'n_estimators': 40, 'learning_rate': 0.06750679905117915}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.23012845095006443
Fold 2 IBS: 0.21146558867865006
Fold 3 IBS: 0.23279549174045716
Fold 4 IBS: 0.22266577695527393
Fold 5 IBS: 0.21241427656033215
[I 2024-04-15 17:27:08,329] Trial 97 finished with value: 0.22189391697695554 and parameters: {'subsample': 0.33846670341980367, 'dropout_rate': 0.31372183756474226, 'n_estimators': 11, 'learning_rate': 0.08189974172037857}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.22449452686444515
Fold 2 IBS: 0.19899271420825793
Fold 3 IBS: 0.2512552344527812
Fold 4 IBS: 0.21747374636329503
Fold 5 IBS: 0.20877722392455747
[I 2024-04-15 17:27:08,841] Trial 98 finished with value: 0.22019868916266735 and parameters: {'subsample': 0.19941874740011878, 'dropout_rate': 0.3556195933220295, 'n_estimators': 22, 'learning_rate': 0.08555738256831025}. Best is trial 74 with value: 0.21802891883599546.
Fold 1 IBS: 0.24058676893054592
Fold 2 IBS: 0.21214578251740948
Fold 3 IBS: 0.30322489395782787
Fold 4 IBS: 0.2281071867431335
Fold 5 IBS: 0.24342847739839374
[I 2024-04-15 17:27:09,609] Trial 99 finished with value: 0.2454986219094621 and parameters: {'subsample': 0.19477055311559938, 'dropout_rate': 0.35304414851199056, 'n_estimators': 52, 'learning_rate': 0.09809807095013201}. Best is trial 74 with value: 0.21802891883599546.


* Best trial for IBS:
 FrozenTrial(number=74, state=TrialState.COMPLETE, values=[0.21802891883599546], datetime_start=datetime.datetime(2024, 4, 15, 17, 26, 43, 600821), datetime_complete=datetime.datetime(2024, 4, 15, 17, 26, 44, 92144), params={'subsample': 0.10090556122023636, 'dropout_rate': 0.3788374747846416, 'n_estimators': 22, 'learning_rate': 0.07386328482560535}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=74, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10090556122023636, 'dropout_rate': 0.3788374747846416, 'n_estimators': 22, 'learning_rate': 0.07386328482560535}


* Best Score for IBS:
 0.21802891883599546

In [65]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.664
train_ibs:  0.218

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10222075562837932,
                                              learning_rate=0.07704376427520507,
                                              n_estimators=290,
                                              random_state=123,
                                              subsample=0.10832939724965542)

C-index score: 0.528

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3788374747846416,
                                              learning_rate=0.07386328482560535,
                                              n_estimators=22, random_state=123,
                                              subsample=0.10090556122023636)

IBS: 0.239

In [69]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [70]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.830   1.0
ExtraSurvivalTrees               0.764   2.0
GradientBoosting                 0.713   3.0
CoxElastic                       0.687   4.0
CoxPH                            0.686   5.0
CoxLasso                         0.685   6.0
ComponentwiseGradientBoosting    0.664   7.0
CoxRidge                         0.659   8.0

In [71]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.202   1.0
ExtraSurvivalTrees             0.207   2.0
CoxLasso                       0.211   3.5
CoxElastic                     0.211   3.5
CoxPH                          0.212   5.0
ComponentwiseGradientBoosting  0.218   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [72]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.544   1.0
ExtraSurvivalTrees               0.543   2.0
CoxRidge                         0.534   3.0
GradientBoosting                 0.532   4.0
ComponentwiseGradientBoosting    0.528   5.0
CoxPH                            0.524   6.0
CoxLasso                         0.523   7.5
CoxElastic                       0.523   7.5

In [73]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ComponentwiseGradientBoosting  0.239   3.0
Randomsurvivalforest           0.247   4.0
ExtraSurvivalTrees             0.256   5.0
CoxLasso                       0.290   6.5
CoxElastic                     0.290   6.5
CoxPH                          0.292   8.0

In [74]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/yeojohnson/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_yeojohnson_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [75]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-15