In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D3 
clinical_train.isnull().sum().sum()

0

### COX assumption in Train data

In [6]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.97      0.05
LBP_003_PET                                                      0.00 0.97      0.05
LBP_012_CT                                                       0.00 0.96      0.06
LBP_012_PET                                                      0.01 0.94      0.09
LBP_021_CT                                                       0.00 0.98      0.04
LBP_021_PET                                                      0.01 0.94      0.10
LBP_030_CT                                                       0.00 0.99      0.02
LBP_030_PET                                                      0.00 0.98      0.02
LBP_102_CT                                                       0.00 0.96      0.05
LBP_102_PET                                                      0.01 0.92      0.12
LBP_111_CT                                                       0.00 0.95      0.07
LBP_111_PET                                                      0.00 1.00      0.00
LBP_120_CT                                                       0.00 0.98      0.03
LBP_120_PET                                                      0.00 0.99      0.02
LBP_201_CT                                                       0.00 0.97      0.04
LBP_201_PET                                                      0.00 0.97      0.04
LBP_210_CT                                                       0.00 1.00      0.01
LBP_210_PET                                                      0.00 1.00      0.00
LBP_300_CT                                                       0.00 0.97      0.04
LBP_300_PET                                                      0.01 0.94      0.09
MTV                                                              0.00 0.98      0.04
SUVpeak                                                          0.00 0.98      0.02
TLG                                                              0.00 0.99      0.02
age                                                              0.00 0.97      0.05
cavum_oris                                                       0.00 0.99      0.02
charlson                                                         0.02 0.90      0.15
female                                                           0.00 0.96      0.06
first_order_10Percentile_CT                                      0.00 0.98      0.03
first_order_10Percentile_PET                                     0.00 1.00      0.01
first_order_90Percentile_CT                                      0.00 0.98      0.04
first_order_90Percentile_PET                                     0.00 0.99      0.01
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 1.00      0.00
first_order_Entropy_CT_c16                                       0.00 1.00      0.00
first_order_Entropy_PET_b2                                       0.00 1.00      0.00
first_order_Entropy_PET_c04                                      0.00 1.00      0.00
first_order_InterquartileRange_CT                                0.00 0.97      0.04
first_order_InterquartileRange_PET                               0.00 0.99      0.01
first_order_Kurtosis_CT                                          0.00 0.95      0.08
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.00 0.99      0.02
first_order_Maximum_PET                                          0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_PET                            0.00 0.99      0.02
first_order_Mean_CT                                              0.00 0.99      0.02
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.98      0.03
first_order_Median_PET                                           0.00 0.99      0.01
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.01 0.94      0.09
first_order_Range_CT                                             0.00 0.99      0.01
first_order_Range_PET                                            0.00 0.99      0.02
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.98      0.04
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 1.00      0.00
first_order_RootMeanSquared_CT                                   0.00 0.98      0.03
first_order_RootMeanSquared_PET                                  0.00 0.99      0.01
first_order_Skewness_CT                                          0.00 0.98      0.03
first_order_Skewness_PET                                         0.00 1.00      0.00
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.97      0.05
first_order_Uniformity_CT_c16                                    0.00 0.99      0.01
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 1.00      0.00
first_order_Variance_CT                                          0.00 1.00      0.01
first_order_Variance_PET                                         0.00 1.00      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_CT_c16                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.99      0.01
glcm_ClusterProminence_d_1_CT_b20                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.98      0.03
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.97      0.05
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.97      0.04
glcm_ClusterShade_d_1_CT_c16                                     0.00 1.00      0.01
glcm_ClusterShade_d_1_PET_b2                                     0.01 0.93      0.11
glcm_ClusterShade_d_1_PET_c04                                    0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.99      0.02
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.99      0.01
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.01
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 1.00      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.99      0.02
glcm_Correlation_d_1_CT_c16                                      0.00 0.95      0.07
glcm_Correlation_d_1_PET_b2                                      0.00 0.98      0.03
glcm_Correlation_d_1_PET_c04                                     0.00 0.99      0.02
glcm_DifferenceAverage_d_1_CT_b20                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_c16                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_PET_b2                                0.00 1.00      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceVariance_d_1_CT_b20                               0.00 1.00      0.01
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_b2                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.98      0.02
glcm_Id_d_1_CT_b20                                               0.00 0.99      0.02
glcm_Id_d_1_CT_c16                                               0.00 1.00      0.00
glcm_Id_d_1_PET_b2                                               0.00 1.00      0.01
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idm_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00 1.00      0.01
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Idmn_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_c16                                             0.00 0.99      0.01
glcm_Idmn_d_1_PET_b2                                             0.00 1.00      0.01
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 0.98      0.03
glcm_Idn_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.01
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Imc1_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_c16                                             0.01 0.94      0.10
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Imc2_d_1_CT_b20                                             0.00 1.00      0.01
glcm_Imc2_d_1_CT_c16                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.98      0.02
glcm_InverseVariance_d_1_CT_b20                                  0.00 1.00      0.00
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_PET_b2                                  0.00 1.00      0.01
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.01
glcm_JointAverage_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointAverage_d_1_PET_b2                                     0.00 1.00      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 0.99      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.97      0.04
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_b2                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.97      0.04
glcm_MCC_d_1_CT_c16                                              0.00 0.95      0.07
glcm_MCC_d_1_PET_b2                                              0.00 0.99      0.01
glcm_MCC_d_1_PET_c04                                             0.00 0.98      0.02
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.96      0.06
glcm_MaximumProbability_d_1_CT_c16                               0.00 1.00      0.00
glcm_MaximumProbability_d_1_PET_b2                               0.00 0.99      0.01
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.99      0.01
glcm_SumAverage_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumAverage_d_1_PET_b2                                       0.00 1.00      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.99      0.02
glcm_SumSquares_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumSquares_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumSquares_d_1_PET_c04                                      0.00 0.99      0.01
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 1.00      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.04
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.97      0.05
gldm_DependenceVariance_d_1_CT_c16                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 1.00      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.03
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 1.00      0.00
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 1.00      0.00
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.00
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.02
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.01 0.93      0.10
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.99      0.01
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.98      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_b20                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_c16                                   0.00 1.00      0.01
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.01

In [7]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [8]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.07
LBP_003_PET                                                      0.08 0.77      0.37
LBP_012_CT                                                       0.00 0.95      0.07
LBP_012_PET                                                      0.18 0.67      0.57
LBP_021_CT                                                       0.15 0.69      0.53
LBP_021_PET                                                      0.01 0.94      0.09
LBP_030_CT                                                       0.00 0.99      0.01
LBP_030_PET                                                      0.03 0.86      0.21
LBP_102_CT                                                       0.02 0.89      0.17
LBP_102_PET                                                      0.69 0.41      1.30
LBP_111_CT                                                       0.01 0.93      0.11
LBP_111_PET                                                      0.00 0.98      0.03
LBP_120_CT                                                       0.01 0.92      0.12
LBP_120_PET                                                      0.01 0.91      0.14
LBP_201_CT                                                       0.04 0.84      0.25
LBP_201_PET                                                      1.08 0.30      1.74
LBP_210_CT                                                       0.13 0.72      0.47
LBP_210_PET                                                      0.06 0.81      0.30
LBP_300_CT                                                       0.03 0.87      0.19
LBP_300_PET                                                      0.23 0.63      0.67
MTV                                                              0.00 0.98      0.03
SUVpeak                                                          0.01 0.91      0.14
TLG                                                              0.00 0.97      0.05
age                                                              0.11 0.74      0.43
cavum_oris                                                       0.35 0.55      0.85
charlson                                                         1.37 0.24      2.05
female                                                           2.09 0.15      2.76
first_order_10Percentile_CT                                      0.16 0.69      0.54
first_order_10Percentile_PET                                     0.00 0.96      0.06
first_order_90Percentile_CT                                      0.28 0.60      0.74
first_order_90Percentile_PET                                     0.01 0.94      0.08
first_order_Energy_CT                                            0.00 0.95      0.07
first_order_Energy_PET                                           0.02 0.89      0.17
first_order_Entropy_CT_b20                                       0.00 0.95      0.08
first_order_Entropy_CT_c16                                       0.01 0.94      0.09
first_order_Entropy_PET_b2                                       0.00 0.99      0.01
first_order_Entropy_PET_c04                                      0.00 0.99      0.02
first_order_InterquartileRange_CT                                0.00 0.99      0.02
first_order_InterquartileRange_PET                               0.04 0.85      0.23
first_order_Kurtosis_CT                                          0.00 0.95      0.07
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.04 0.83      0.26
first_order_Maximum_PET                                          0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_CT                             0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_PET                            0.00 0.97      0.04
first_order_Mean_CT                                              0.01 0.93      0.11
first_order_Mean_PET                                             0.01 0.92      0.11
first_order_Median_CT                                            0.20 0.65      0.61
first_order_Median_PET                                           0.01 0.93      0.11
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.02 0.88      0.19
first_order_Range_CT                                             0.03 0.87      0.20
first_order_Range_PET                                            0.01 0.93      0.10
first_order_RobustMeanAbsoluteDeviation_CT                       0.18 0.67      0.57
first_order_RobustMeanAbsoluteDeviation_PET                      0.02 0.88      0.18
first_order_RootMeanSquared_CT                                   0.01 0.91      0.13
first_order_RootMeanSquared_PET                                  0.01 0.93      0.11
first_order_Skewness_CT                                          0.04 0.84      0.25
first_order_Skewness_PET                                         0.00 0.99      0.02
first_order_TotalEnergy_CT                                       0.00 0.95      0.07
first_order_TotalEnergy_PET                                      0.02 0.89      0.17
first_order_Uniformity_CT_b20                                    0.00 0.97      0.04
first_order_Uniformity_CT_c16                                    0.00 0.97      0.04
first_order_Uniformity_PET_b2                                    0.02 0.90      0.15
first_order_Uniformity_PET_c04                                   0.01 0.93      0.10
first_order_Variance_CT                                          0.00 1.00      0.00
first_order_Variance_PET                                         0.00 0.95      0.07
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.97      0.05
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.95      0.07
glcm_ClusterProminence_d_1_CT_b20                                0.03 0.86      0.22
glcm_ClusterProminence_d_1_CT_c16                                0.01 0.93      0.11
glcm_ClusterProminence_d_1_PET_b2                                0.02 0.88      0.19
glcm_ClusterProminence_d_1_PET_c04                               0.03 0.86      0.22
glcm_ClusterShade_d_1_CT_b20                                     0.11 0.74      0.42
glcm_ClusterShade_d_1_CT_c16                                     0.02 0.89      0.16
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.99      0.01
glcm_ClusterShade_d_1_PET_c04                                    0.06 0.81      0.31
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.96      0.06
glcm_ClusterTendency_d_1_CT_c16                                  0.01 0.91      0.14
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.95      0.08
glcm_ClusterTendency_d_1_PET_c04                                 0.08 0.78      0.36
glcm_Contrast_d_1_CT_b20                                         0.00 0.98      0.02
glcm_Contrast_d_1_CT_c16                                         0.02 0.89      0.17
glcm_Contrast_d_1_PET_b2                                         0.00 0.97      0.04
glcm_Contrast_d_1_PET_c04                                        0.00 0.98      0.04
glcm_Correlation_d_1_CT_b20                                      0.05 0.82      0.28
glcm_Correlation_d_1_CT_c16                                      0.29 0.59      0.77
glcm_Correlation_d_1_PET_b2                                      0.00 0.97      0.04
glcm_Correlation_d_1_PET_c04                                     0.00 0.96      0.05
glcm_DifferenceAverage_d_1_CT_b20                                0.01 0.92      0.13
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.95      0.08
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.96      0.06
glcm_DifferenceAverage_d_1_PET_c04                               0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_b20                                0.01 0.93      0.10
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.97      0.05
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.95      0.07
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_c16                               0.02 0.88      0.18
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.99      0.02
glcm_Id_d_1_CT_b20                                               0.05 0.83      0.27
glcm_Id_d_1_CT_c16                                               0.00 0.96      0.05
glcm_Id_d_1_PET_b2                                               0.01 0.93      0.11
glcm_Id_d_1_PET_c04                                              0.00 0.96      0.06
glcm_Idm_d_1_CT_b20                                              0.05 0.83      0.27
glcm_Idm_d_1_CT_c16                                              0.00 0.97      0.04
glcm_Idm_d_1_PET_b2                                              0.01 0.94      0.09
glcm_Idm_d_1_PET_c04                                             0.00 0.97      0.05
glcm_Idmn_d_1_CT_b20                                             0.02 0.90      0.15
glcm_Idmn_d_1_CT_c16                                             0.02 0.90      0.15
glcm_Idmn_d_1_PET_b2                                             0.01 0.93      0.11
glcm_Idmn_d_1_PET_c04                                            0.00 0.98      0.03
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.01
glcm_Idn_d_1_CT_c16                                              0.00 0.96      0.06
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idn_d_1_PET_c04                                             0.00 0.97      0.04
glcm_Imc1_d_1_CT_b20                                             0.04 0.85      0.24
glcm_Imc1_d_1_CT_c16                                             0.34 0.56      0.84
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc1_d_1_PET_c04                                            0.00 0.96      0.07
glcm_Imc2_d_1_CT_b20                                             0.09 0.77      0.38
glcm_Imc2_d_1_CT_c16                                             0.13 0.72      0.48
glcm_Imc2_d_1_PET_b2                                             0.01 0.94      0.09
glcm_Imc2_d_1_PET_c04                                            0.01 0.93      0.11
glcm_InverseVariance_d_1_CT_b20                                  0.18 0.67      0.58
glcm_InverseVariance_d_1_CT_c16                                  0.01 0.91      0.14
glcm_InverseVariance_d_1_PET_b2                                  0.03 0.87      0.20
glcm_InverseVariance_d_1_PET_c04                                 0.01 0.91      0.13
glcm_JointAverage_d_1_CT_b20                                     0.00 0.98      0.02
glcm_JointAverage_d_1_CT_c16                                     0.00 0.97      0.04
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.01 0.93      0.10
glcm_JointEnergy_d_1_CT_b20                                      0.01 0.93      0.11
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.03 0.86      0.22
glcm_JointEnergy_d_1_PET_c04                                     0.02 0.90      0.16
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.02 0.90      0.15
glcm_JointEntropy_d_1_PET_b2                                     0.00 0.97      0.05
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.96      0.06
glcm_MCC_d_1_CT_c16                                              0.01 0.94      0.08
glcm_MCC_d_1_PET_b2                                              0.00 1.00      0.00
glcm_MCC_d_1_PET_c04                                             0.00 0.99      0.01
glcm_MaximumProbability_d_1_CT_b20                               0.01 0.92      0.11
glcm_MaximumProbability_d_1_CT_c16                               0.02 0.89      0.17
glcm_MaximumProbability_d_1_PET_b2                               0.04 0.85      0.23
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.95      0.07
glcm_SumAverage_d_1_CT_b20                                       0.00 0.98      0.02
glcm_SumAverage_d_1_CT_c16                                       0.00 0.97      0.04
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.01 0.93      0.10
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.95      0.08
glcm_SumEntropy_d_1_CT_c16                                       0.01 0.91      0.14
glcm_SumEntropy_d_1_PET_b2                                       0.00 0.96      0.05
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.98      0.03
glcm_SumSquares_d_1_CT_b20                                       0.00 0.96      0.05
glcm_SumSquares_d_1_CT_c16                                       0.01 0.93      0.11
glcm_SumSquares_d_1_PET_b2                                       0.00 0.95      0.08
glcm_SumSquares_d_1_PET_c04                                      0.08 0.78      0.36
gldm_DependenceEntropy_d_1_CT_b20                                0.11 0.74      0.44
gldm_DependenceEntropy_d_1_CT_c16                                0.05 0.83      0.27
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.95      0.07
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.10 0.75      0.42
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.02
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.01 0.92      0.12
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_PET_b2                          0.01 0.90      0.15
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 0.99      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.52 0.47      1.09
gldm_DependenceVariance_d_1_CT_c16                               0.17 0.68      0.55
gldm_DependenceVariance_d_1_PET_b2                               0.07 0.80      0.33
gldm_DependenceVariance_d_1_PET_c04                              0.07 0.78      0.35
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.97      0.05
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.01 0.94      0.09
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.94      0.08
gldm_GrayLevelVariance_d_1_PET_c04                               0.05 0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.02
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.95      0.07
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.02 0.88      0.18
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.03 0.86      0.22
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.01 0.92      0.11
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.03 0.86      0.22
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.01 0.94      0.09
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.03 0.86      0.22
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.08
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.06 0.81      0.30
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.03 0.86      0.21
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.94      0.08
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.02 0.89      0.17
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.01 0.91      0.13
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.07 0.79      0.33
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.96      0.06
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.02 0.89      0.16
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01 0.92      0.13
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.01 0.94      0.08
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.03 0.86      0.22
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.22 0.64      0.65
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 1.00      0.00
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.95      0.08
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.96      0.06
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 1.00      0.01
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.95      0.07
glrlm_GrayLevelNonUniformity_CT_c16                              0.06 0.81      0.30
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.99      0.01
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.95      0.08
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.96      0.06
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.96      0.06

In [9]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

## Test dataset: MAASTRO

In [10]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [11]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [12]:
# Need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [13]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [14]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [15]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [16]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [17]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [18]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [19]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [20]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = StandardScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [23]:
# Divide the X_MAASTRO into numerical part and categorical part 
X_MAASTRO_categorical = X_MAASTRO[categorical_columns]
X_MAASTRO_numeric = X_MAASTRO.drop(categorical_columns, axis=1)

# Save the column name and index of the numeric part
X_MAASTRO_numeric_columns = X_MAASTRO_numeric.columns
X_MAASTRO_numeric_index = X_MAASTRO_numeric.index

In [24]:
# Standardize the numeric part 
X_MAASTRO_numeric_std = scaler.transform(X_MAASTRO_numeric)

# Change the standardized part into a dataframe 
X_MAASTRO_numeric_std = pd.DataFrame(X_MAASTRO_numeric_std, columns=X_MAASTRO_numeric_columns, index=X_MAASTRO_numeric_index)

# Concat the standardized part with the categorical part 
X_MAASTRO_std = pd.concat([X_MAASTRO_categorical, X_MAASTRO_numeric_std], axis=1)

# Change the column order of X_MAASTRO_std
X_MAASTRO_std = X_MAASTRO_std[original_X.columns]

In [25]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [26]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:21:21,188] A new study created in memory with name: no-name-1eafe64e-80fa-49fe-923c-6250eb9ed44b

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-18 03:21:24,913] Trial 0 failed with parameters: {} because of the following error: ValueError('search direction contains NaN or infinite values').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_5821/4028431732.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 454, in fit
    raise ValueError("search direction contains NaN or infinite values")
ValueError: search direction contains NaN or infinite values
[W 2024-04-18 03:21:24,934] Trial 0 failed with value None.

ValueError: search direction contains NaN or infinite values

In [27]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [28]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [29]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [30]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [32]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [33]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [34]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:21:50,599] A new study created in memory with name: no-name-85fb53e0-215a-4ec0-bc95-d4aaeee61c21

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7151898734177216

[I 2024-04-18 03:21:51,717] A new study created in memory with name: no-name-84dd02ae-cf28-4dca-888c-58b25d977e8a

Fold 5 C-index: 0.7488262910798122
[I 2024-04-18 03:21:51,707] Trial 0 finished with value: 0.7118794997698913 and parameters: {}. Best is trial 0 with value: 0.7118794997698913.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7118794997698913], datetime_start=datetime.datetime(2024, 4, 18, 3, 21, 50, 636093), datetime_complete=datetime.datetime(2024, 4, 18, 3, 21, 51, 706705), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7118794997698913

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651743727053
Fold 2 IBS: 0.2215779111122035
Fold 3 IBS: 0.20453593920513286
Fold 4 IBS: 0.22473803623356947
Fold 5 IBS: 0.2181243076466848
[I 2024-04-18 03:21:53,588] Trial 0 finished with value: 0.21659054232697222 and parameters: {}. Best is trial 0 with value: 0.21659054232697222.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054232697222], datetime_start=datetime.datetime(2024, 4, 18, 3, 21, 51, 887444), datetime_complete=datetime.datetime(2024, 4, 18, 3, 21, 53, 587551), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054232697222

In [35]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [36]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.712
train_ibs:  0.217

#### Test

In [37]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [38]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.586

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [39]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [40]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:21:54,849] A new study created in memory with name: no-name-347bfd13-7989-4411-a02b-5e003dea5b82

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.4955357142857143
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.5780590717299579

[I 2024-04-18 03:22:05,383] A new study created in memory with name: no-name-9b4d6b8c-b0a2-4a53-96c3-aecaa1e2f08e

Fold 5 C-index: 0.6197183098591549
[I 2024-04-18 03:22:05,227] Trial 0 finished with value: 0.5920494284441277 and parameters: {}. Best is trial 0 with value: 0.5920494284441277.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5920494284441277], datetime_start=datetime.datetime(2024, 4, 18, 3, 21, 54, 985019), datetime_complete=datetime.datetime(2024, 4, 18, 3, 22, 5, 227131), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5920494284441277

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.3648427575285378
Fold 2 IBS: 0.42988623278732496
Fold 3 IBS: 0.26853768956994967
Fold 4 IBS: 0.4100303033162769
Fold 5 IBS: 0.3361171766744235
[I 2024-04-18 03:22:15,149] Trial 0 finished with value: 0.3618828319753026 and parameters: {}. Best is trial 0 with value: 0.3618828319753026.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.3618828319753026], datetime_start=datetime.datetime(2024, 4, 18, 3, 22, 5, 505386), datetime_complete=datetime.datetime(2024, 4, 18, 3, 22, 15, 148499), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.3618828319753026

In [41]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [42]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.592
train_ibs:  0.362

#### Test

In [43]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [44]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.541

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.442

In [45]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [46]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:22:21,293] A new study created in memory with name: no-name-4a814e57-b168-4f5f-9106-23c5b4876d2e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6033755274261603
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:22:29,251] Trial 0 finished with value: 0.6153421048073681 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6153421048073681.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:22:34,678] Trial 1 finished with value: 0.6387915675759923 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6387915675759923.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:22:40,616] Trial 2 finished with value: 0.644162485858539 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.5267857142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:22:46,491] Trial 3 finished with value: 0.619559242115297 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.5991561181434599
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:22:52,001] Trial 4 finished with value: 0.6135592558146779 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.5491071428571429
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:22:58,128] Trial 5 finished with value: 0.628184419077928 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.49107142857142855
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.5738396624472574
Fold 5 C-index: 0.6056338028169014
[I 2024-04-18 03:23:05,861] Trial 6 finished with value: 0.5922831575295315 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:23:12,406] Trial 7 finished with value: 0.6161859866639082 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.5357142857142857
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:23:19,567] Trial 8 finished with value: 0.6190184792048393 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5535714285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:23:25,827] Trial 9 finished with value: 0.6333843615405286 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.644162485858539.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:23:31,470] Trial 10 finished with value: 0.6651069005131672 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.6651069005131672.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 03:23:33,019] Trial 11 finished with value: 0.7107811229728604 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.7107811229728604.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 03:23:36,608] Trial 12 finished with value: 0.7281116435293545 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:23:37,632] Trial 13 finished with value: 0.7154345336328991 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:23:42,948] Trial 14 finished with value: 0.6544083086483431 and parameters: {'l1_ratio': 0.14548740545758646}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 03:23:43,949] Trial 15 finished with value: 0.7191367419186024 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:23:48,885] Trial 16 finished with value: 0.6433456602790552 and parameters: {'l1_ratio': 0.21667088249320593}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.5625
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:23:54,795] Trial 17 finished with value: 0.6405283065753895 and parameters: {'l1_ratio': 0.305421948361187}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:23:58,879] Trial 18 finished with value: 0.662445563121276 and parameters: {'l1_ratio': 0.10592027039041071}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.49107142857142855
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.5780590717299579
Fold 5 C-index: 0.6197183098591549
[I 2024-04-18 03:24:09,194] Trial 19 finished with value: 0.5921369634581332 and parameters: {'l1_ratio': 0.9947379076423366}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:24:14,567] Trial 20 finished with value: 0.6478110338853446 and parameters: {'l1_ratio': 0.1697322474598469}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 03:24:16,039] Trial 21 finished with value: 0.7182928600620623 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 03:24:17,571] Trial 22 finished with value: 0.7191367419186024 and parameters: {'l1_ratio': 0.008242879725625268}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:24:23,234] Trial 23 finished with value: 0.6659870701226243 and parameters: {'l1_ratio': 0.097070668839174}. Best is trial 12 with value: 0.7281116435293545.

Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:24:30,462] Trial 24 finished with value: 0.6387915675759923 and parameters: {'l1_ratio': 0.28996492542517793}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:24:35,465] Trial 25 finished with value: 0.6653090268182347 and parameters: {'l1_ratio': 0.07330522822697523}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:24:40,629] Trial 26 finished with value: 0.6496353078987475 and parameters: {'l1_ratio': 0.16177229800289714}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.53125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5864978902953587
Fold 5 C-index: 0.6197183098591549
[I 2024-04-18 03:24:48,887] Trial 27 finished with value: 0.6067624022412414 and parameters: {'l1_ratio': 0.8851865202969101}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:24:56,005] Trial 28 finished with value: 0.644162485858539 and parameters: {'l1_ratio': 0.22613053077404888}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:25:01,763] Trial 29 finished with value: 0.6682036410003149 and parameters: {'l1_ratio': 0.06519122510965338}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:25:09,109] Trial 30 finished with value: 0.616090901384298 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:25:10,067] Trial 31 finished with value: 0.7135565993605987 and parameters: {'l1_ratio': 0.0001717239846378768}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6160714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:25:13,822] Trial 32 finished with value: 0.6827945089930817 and parameters: {'l1_ratio': 0.04851434258493281}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:25:18,536] Trial 33 finished with value: 0.6553282220682565 and parameters: {'l1_ratio': 0.1348754910720846}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:25:24,802] Trial 34 finished with value: 0.6387915675759923 and parameters: {'l1_ratio': 0.35160256301788523}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:25:30,008] Trial 35 finished with value: 0.6451843030361142 and parameters: {'l1_ratio': 0.19767878430456537}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6160714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:25:33,627] Trial 36 finished with value: 0.6827945089930817 and parameters: {'l1_ratio': 0.04883113685208405}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:25:39,253] Trial 37 finished with value: 0.6432454377316495 and parameters: {'l1_ratio': 0.24331018780836453}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:25:44,176] Trial 38 finished with value: 0.6591132803953849 and parameters: {'l1_ratio': 0.12680893872224136}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.53125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5864978902953587
Fold 5 C-index: 0.6291079812206573
[I 2024-04-18 03:25:51,369] Trial 39 finished with value: 0.6121035399767454 and parameters: {'l1_ratio': 0.8205172079302314}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.5267857142857143
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:25:58,051] Trial 40 finished with value: 0.6193081405239125 and parameters: {'l1_ratio': 0.521459452147164}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 03:25:59,343] Trial 41 finished with value: 0.7191367419186024 and parameters: {'l1_ratio': 0.008501596444785927}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:26:02,968] Trial 42 finished with value: 0.6928799099908688 and parameters: {'l1_ratio': 0.03862793461981657}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:26:03,918] Trial 43 finished with value: 0.7181977747824522 and parameters: {'l1_ratio': 0.005906628534833862}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:26:08,425] Trial 44 finished with value: 0.6659727013789681 and parameters: {'l1_ratio': 0.09217620771285319}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.6205357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:26:12,752] Trial 45 finished with value: 0.6864311012740402 and parameters: {'l1_ratio': 0.04543643724785823}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:26:17,674] Trial 46 finished with value: 0.6496842831850644 and parameters: {'l1_ratio': 0.1676122733044054}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:26:22,797] Trial 47 finished with value: 0.662445563121276 and parameters: {'l1_ratio': 0.10522896812691351}. Best is trial 12 with value: 0.7281116435293545.

Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.5625
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:26:28,801] Trial 48 finished with value: 0.6423525805887923 and parameters: {'l1_ratio': 0.2607230626544604}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.5357142857142857
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6431924882629108
[I 2024-04-18 03:26:35,286] Trial 49 finished with value: 0.6208964134771398 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.5223214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:26:41,341] Trial 50 finished with value: 0.6179151753977009 and parameters: {'l1_ratio': 0.5938078108685914}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:26:43,677] Trial 51 finished with value: 0.7214875854554208 and parameters: {'l1_ratio': 0.016262980638619595}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:26:44,633] Trial 52 finished with value: 0.7144955664967488 and parameters: {'l1_ratio': 0.002958203119263654}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:26:49,068] Trial 53 finished with value: 0.6928799099908688 and parameters: {'l1_ratio': 0.03827215295187866}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:26:53,947] Trial 54 finished with value: 0.6642140433703101 and parameters: {'l1_ratio': 0.07832257389437013}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:27:00,642] Trial 55 finished with value: 0.6591132803953849 and parameters: {'l1_ratio': 0.12689591389537605}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:27:03,111] Trial 56 finished with value: 0.7205071932985581 and parameters: {'l1_ratio': 0.023230044437482722}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:27:11,500] Trial 57 finished with value: 0.6451843030361142 and parameters: {'l1_ratio': 0.187594590475137}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:27:17,122] Trial 58 finished with value: 0.6617889865309323 and parameters: {'l1_ratio': 0.1161724440656101}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:27:22,136] Trial 59 finished with value: 0.6653090268182347 and parameters: {'l1_ratio': 0.07525408693482417}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:27:28,744] Trial 60 finished with value: 0.6405744165686826 and parameters: {'l1_ratio': 0.3256911195945203}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:27:31,649] Trial 61 finished with value: 0.726119117965992 and parameters: {'l1_ratio': 0.027795400234820567}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:27:35,244] Trial 62 finished with value: 0.7224922094561094 and parameters: {'l1_ratio': 0.032945635777306616}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:27:38,959] Trial 63 finished with value: 0.6929213350115813 and parameters: {'l1_ratio': 0.04038475730639342}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:27:44,249] Trial 64 finished with value: 0.6524475243346176 and parameters: {'l1_ratio': 0.1497330272006944}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:27:49,388] Trial 65 finished with value: 0.6661748276840356 and parameters: {'l1_ratio': 0.07250083806317134}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 03:27:52,240] Trial 66 finished with value: 0.7253091108645601 and parameters: {'l1_ratio': 0.030171721340265453}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:27:55,666] Trial 67 finished with value: 0.7233850665989665 and parameters: {'l1_ratio': 0.03432146587868362}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:28:00,744] Trial 68 finished with value: 0.661601681264736 and parameters: {'l1_ratio': 0.1006690588489025}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:28:04,881] Trial 69 finished with value: 0.6928799099908688 and parameters: {'l1_ratio': 0.038141718546898656}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5625
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:28:11,471] Trial 70 finished with value: 0.6442914458932572 and parameters: {'l1_ratio': 0.1983756163019485}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 03:28:14,748] Trial 71 finished with value: 0.7261749117303609 and parameters: {'l1_ratio': 0.030605859297383898}. Best is trial 12 with value: 0.7281116435293545.

Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:28:18,974] Trial 72 finished with value: 0.6718355483086927 and parameters: {'l1_ratio': 0.057373733996563925}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:28:21,754] Trial 73 finished with value: 0.726119117965992 and parameters: {'l1_ratio': 0.02851368898058473}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:28:27,047] Trial 74 finished with value: 0.6659727013789681 and parameters: {'l1_ratio': 0.09013924801250651}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:28:32,887] Trial 75 finished with value: 0.6544083086483431 and parameters: {'l1_ratio': 0.14395981248444145}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:28:38,114] Trial 76 finished with value: 0.6682036410003149 and parameters: {'l1_ratio': 0.06371149021473063}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:28:42,919] Trial 77 finished with value: 0.6626328683874724 and parameters: {'l1_ratio': 0.11485322310111488}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.5178571428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.5949367088607594
Fold 5 C-index: 0.6291079812206573
[I 2024-04-18 03:28:50,312] Trial 78 finished with value: 0.6100177488133294 and parameters: {'l1_ratio': 0.761194642033675}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:28:55,264] Trial 79 finished with value: 0.7233850665989665 and parameters: {'l1_ratio': 0.03438244918970636}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:28:58,744] Trial 80 finished with value: 0.725226260823135 and parameters: {'l1_ratio': 0.02924141187656099}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.704225352112676
[I 2024-04-18 03:29:02,147] Trial 81 finished with value: 0.7252676858438475 and parameters: {'l1_ratio': 0.029745851153293923}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:29:07,259] Trial 82 finished with value: 0.6682036410003149 and parameters: {'l1_ratio': 0.06314920914441391}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:29:14,083] Trial 83 finished with value: 0.6669530935358309 and parameters: {'l1_ratio': 0.09302430912612952}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:29:17,319] Trial 84 finished with value: 0.7233850665989665 and parameters: {'l1_ratio': 0.033857812435703245}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:29:18,416] Trial 85 finished with value: 0.7135565993605987 and parameters: {'l1_ratio': 0.0006226466083436265}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5669642857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:29:24,505] Trial 86 finished with value: 0.6458916745923317 and parameters: {'l1_ratio': 0.1754571607436689}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.5803571428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:29:30,353] Trial 87 finished with value: 0.6591132803953849 and parameters: {'l1_ratio': 0.12656432328525027}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5982142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:29:36,380] Trial 88 finished with value: 0.6709426911658356 and parameters: {'l1_ratio': 0.059696488360547015}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:29:42,257] Trial 89 finished with value: 0.6651069005131672 and parameters: {'l1_ratio': 0.08279249171128998}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:29:44,430] Trial 90 finished with value: 0.7195268011416953 and parameters: {'l1_ratio': 0.02421173164778529}. Best is trial 12 with value: 0.7281116435293545.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 03:29:47,550] Trial 91 finished with value: 0.7289774443951553 and parameters: {'l1_ratio': 0.02638395621436353}. Best is trial 91 with value: 0.7289774443951553.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 03:29:50,441] Trial 92 finished with value: 0.7281116435293545 and parameters: {'l1_ratio': 0.024831745028928418}. Best is trial 91 with value: 0.7289774443951553.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.6071428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:29:55,358] Trial 93 finished with value: 0.67272840545155 and parameters: {'l1_ratio': 0.05558351793827965}. Best is trial 91 with value: 0.7289774443951553.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 03:29:57,796] Trial 94 finished with value: 0.722426552591571 and parameters: {'l1_ratio': 0.019789010610388902}. Best is trial 91 with value: 0.7289774443951553.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.5267857142857143
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.5864978902953587
Fold 5 C-index: 0.6244131455399061
[I 2024-04-18 03:30:06,142] Trial 95 finished with value: 0.6058281200776718 and parameters: {'l1_ratio': 0.9190946752122768}. Best is trial 91 with value: 0.7289774443951553.

Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.59375
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.647887323943662
[I 2024-04-18 03:30:10,823] Trial 96 finished with value: 0.662445563121276 and parameters: {'l1_ratio': 0.10624270857673294}. Best is trial 91 with value: 0.7289774443951553.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6026785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:30:15,290] Trial 97 finished with value: 0.6651069005131672 and parameters: {'l1_ratio': 0.07976277520484326}. Best is trial 91 with value: 0.7289774443951553.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:30:16,354] Trial 98 finished with value: 0.7135565993605987 and parameters: {'l1_ratio': 0.0015287255159762633}. Best is trial 91 with value: 0.7289774443951553.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.5714285714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6624472573839663

[I 2024-04-18 03:30:22,065] A new study created in memory with name: no-name-d37a8fa3-fc98-4c37-be5e-7e7ea89fe10a

Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 03:30:22,047] Trial 99 finished with value: 0.6524475243346176 and parameters: {'l1_ratio': 0.15149941445488746}. Best is trial 91 with value: 0.7289774443951553.


* Best trial for C-index:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.7289774443951553], datetime_start=datetime.datetime(2024, 4, 18, 3, 29, 44, 458947), datetime_complete=datetime.datetime(2024, 4, 18, 3, 29, 47, 549791), params={'l1_ratio': 0.02638395621436353}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=91, value=None)


* Best Score for C-index:
 0.7289774443951553

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.3475140168979067
Fold 2 IBS: 0.41225365552385507
Fold 3 IBS: 0.26947453727312354
Fold 4 IBS: 0.38254539171702573
Fold 5 IBS: 0.3114004088282101
[I 2024-04-18 03:30:28,858] Trial 0 finished with value: 0.3446376020480242 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.3446376020480242.
Fold 1 IBS: 0.3154714056953797
Fold 2 IBS: 0.36488183728952245
Fold 3 IBS: 0.2557645179781991
Fold 4 IBS: 0.2914563347249407
Fold 5 IBS: 0.27936066808237664
[I 2024-04-18 03:30:34,437] Trial 1 finished with value: 0.3013869527540837 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.3013869527540837.
Fold 1 IBS: 0.3069941616433161
Fold 2 IBS: 0.3526868276074873
Fold 3 IBS: 0.25055644185398335
Fold 4 IBS: 0.2761780781844828
Fold 5 IBS: 0.2756358845465405
[I 2024-04-18 03:30:40,143] Trial 2 finished with value: 0.292410278767162 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.3440361004170627
Fold 2 IBS: 0.39637275293842433
Fold 3 IBS: 0.2666481982195387
Fold 4 IBS: 0.3489420861502092
Fold 5 IBS: 0.29823816052736674
[I 2024-04-18 03:30:48,129] Trial 3 finished with value: 0.3308474596505203 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.3475101428080367
Fold 2 IBS: 0.41494640113004294
Fold 3 IBS: 0.26869492865579603
Fold 4 IBS: 0.38806746602472153
Fold 5 IBS: 0.3125790878300808
[I 2024-04-18 03:30:56,819] Trial 4 finished with value: 0.34635960528973564 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.33268990224432216
Fold 2 IBS: 0.38277194338147374
Fold 3 IBS: 0.26308524585568005
Fold 4 IBS: 0.3235020481716347
Fold 5 IBS: 0.28775676882789836
[I 2024-04-18 03:31:04,200] Trial 5 finished with value: 0.3179611816962018 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.367676010561494
Fold 2 IBS: 0.43168766690673377
Fold 3 IBS: 0.2624060914664081
Fold 4 IBS: 0.40435866274644333
Fold 5 IBS: 0.3316804457247221
[I 2024-04-18 03:31:14,359] Trial 6 finished with value: 0.35956177548116025 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.34667221825003974
Fold 2 IBS: 0.4107998613987207
Fold 3 IBS: 0.2695827753622959
Fold 4 IBS: 0.3800469563159163
Fold 5 IBS: 0.31055197050687433
[I 2024-04-18 03:31:21,934] Trial 7 finished with value: 0.3435307563667694 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.3386636148925243
Fold 2 IBS: 0.3880987160953174
Fold 3 IBS: 0.26492736849886855
Fold 4 IBS: 0.3349431777828714
Fold 5 IBS: 0.29243367258368713
[I 2024-04-18 03:31:29,509] Trial 8 finished with value: 0.3238133099706538 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.3293126665521063
Fold 2 IBS: 0.3796624468932736
Fold 3 IBS: 0.26177082589553086
Fold 4 IBS: 0.31635265043294836
Fold 5 IBS: 0.28566474405609293
[I 2024-04-18 03:31:36,126] Trial 9 finished with value: 0.3145526667659904 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.292410278767162.
Fold 1 IBS: 0.2760008972856869
Fold 2 IBS: 0.2823177745110473
Fold 3 IBS: 0.20882628039727932
Fold 4 IBS: 0.2371451772894567
Fold 5 IBS: 0.2592455603581987
[I 2024-04-18 03:31:41,493] Trial 10 finished with value: 0.2527071379683338 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.2527071379683338.
Fold 1 IBS: 0.2134534664413671
Fold 2 IBS: 0.2208538501197217
Fold 3 IBS: 0.20362276527350207
Fold 4 IBS: 0.22412788393999766
Fold 5 IBS: 0.23003877098905523
[I 2024-04-18 03:31:43,686] Trial 11 finished with value: 0.21841934735272878 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.21841934735272878.
Fold 1 IBS: 0.2557191044252729
Fold 2 IBS: 0.22009320043528469
Fold 3 IBS: 0.1644252031183548
Fold 4 IBS: 0.22349806245306297
Fold 5 IBS: 0.24229070758028373
[I 2024-04-18 03:31:47,170] Trial 12 finished with value: 0.22120525560245183 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 11 with value: 0.21841934735272878.
Fold 1 IBS: 0.21377613493095837
Fold 2 IBS: 0.2213050087179155
Fold 3 IBS: 0.2041797714639946
Fold 4 IBS: 0.224506646460254
Fold 5 IBS: 0.217786003979026
[I 2024-04-18 03:31:48,602] Trial 13 finished with value: 0.21631071311042968 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 13 with value: 0.21631071311042968.
Fold 1 IBS: 0.2943543504200792
Fold 2 IBS: 0.32554874145331353
Fold 3 IBS: 0.23831336543209788
Fold 4 IBS: 0.25544040586514777
Fold 5 IBS: 0.26876642642848886
[I 2024-04-18 03:31:54,740] Trial 14 finished with value: 0.27648465791982546 and parameters: {'l1_ratio': 0.15622422014607515}. Best is trial 13 with value: 0.21631071311042968.
Fold 1 IBS: 0.21368960624212088
Fold 2 IBS: 0.2211850894199105
Fold 3 IBS: 0.20402844221238625
Fold 4 IBS: 0.22440535427663955
Fold 5 IBS: 0.217639531309917
[I 2024-04-18 03:31:56,614] Trial 15 finished with value: 0.21618960469219486 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 15 with value: 0.21618960469219486.
Fold 1 IBS: 0.31534891933857034
Fold 2 IBS: 0.3646448926453357
Fold 3 IBS: 0.25571438073806685
Fold 4 IBS: 0.2911425654063693
Fold 5 IBS: 0.2793402892707273
[I 2024-04-18 03:32:03,610] Trial 16 finished with value: 0.3012382094798139 and parameters: {'l1_ratio': 0.28499627491162527}. Best is trial 15 with value: 0.21618960469219486.
Fold 1 IBS: 0.294451832649953
Fold 2 IBS: 0.3258186535710008
Fold 3 IBS: 0.23851144740530533
Fold 4 IBS: 0.2555836386135543
Fold 5 IBS: 0.2688289970109782
[I 2024-04-18 03:32:09,726] Trial 17 finished with value: 0.2766389138501584 and parameters: {'l1_ratio': 0.15671420368983202}. Best is trial 15 with value: 0.21618960469219486.
Fold 1 IBS: 0.36731794615571023
Fold 2 IBS: 0.430355560501928
Fold 3 IBS: 0.2634045554824357
Fold 4 IBS: 0.40562930895258537
Fold 5 IBS: 0.3330176137144963
[I 2024-04-18 03:32:20,248] Trial 18 finished with value: 0.3599449969614311 and parameters: {'l1_ratio': 0.9862904274960449}. Best is trial 15 with value: 0.21618960469219486.
Fold 1 IBS: 0.2868554186429981
Fold 2 IBS: 0.3080178582354654
Fold 3 IBS: 0.22814710552041023
Fold 4 IBS: 0.24628720702408963
Fold 5 IBS: 0.2647364791765204
[I 2024-04-18 03:32:26,260] Trial 19 finished with value: 0.26680881371989673 and parameters: {'l1_ratio': 0.12363244492728864}. Best is trial 15 with value: 0.21618960469219486.
Fold 1 IBS: 0.32045242927078393
Fold 2 IBS: 0.36945032337702505
Fold 3 IBS: 0.2582079703454048
Fold 4 IBS: 0.2985103680972603
Fold 5 IBS: 0.2808915687247699
[I 2024-04-18 03:32:32,156] Trial 20 finished with value: 0.3055025319630488 and parameters: {'l1_ratio': 0.31598698424339017}. Best is trial 15 with value: 0.21618960469219486.
Fold 1 IBS: 0.21358239609218785
Fold 2 IBS: 0.2210347011157296
Fold 3 IBS: 0.20384296798260026
Fold 4 IBS: 0.22427865733220848
Fold 5 IBS: 0.21745765299369654
[I 2024-04-18 03:32:33,853] Trial 21 finished with value: 0.21603927510328452 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21361840419233846
Fold 2 IBS: 0.2210854378815241
Fold 3 IBS: 0.2039050144715136
Fold 4 IBS: 0.22432136014122375
Fold 5 IBS: 0.21751879223517026
[I 2024-04-18 03:32:35,582] Trial 22 finished with value: 0.21608980178435405 and parameters: {'l1_ratio': 0.008242879725625268}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.28007518273028253
Fold 2 IBS: 0.2922578607363206
Fold 3 IBS: 0.21703239927716947
Fold 4 IBS: 0.24007794373905528
Fold 5 IBS: 0.2613954437450481
[I 2024-04-18 03:32:40,551] Trial 23 finished with value: 0.2581677660455752 and parameters: {'l1_ratio': 0.09818312885617073}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.30186626820020473
Fold 2 IBS: 0.34302812634207996
Fold 3 IBS: 0.24640915529247248
Fold 4 IBS: 0.2676147742696195
Fold 5 IBS: 0.2731398210448074
[I 2024-04-18 03:32:45,793] Trial 24 finished with value: 0.28641162902983686 and parameters: {'l1_ratio': 0.19718036319431986}. Best is trial 21 with value: 0.21603927510328452.

Fold 1 IBS: 0.27670167178087807
Fold 2 IBS: 0.28393290173634916
Fold 3 IBS: 0.2101634344854492
Fold 4 IBS: 0.2375103669674679
Fold 5 IBS: 0.2595429910302284
[I 2024-04-18 03:32:50,349] Trial 25 finished with value: 0.2535702732000745 and parameters: {'l1_ratio': 0.08591305360046901}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.3087210843663218
Fold 2 IBS: 0.3552070916196057
Fold 3 IBS: 0.2516074332897404
Fold 4 IBS: 0.27912515979376534
Fold 5 IBS: 0.27639597165810637
[I 2024-04-18 03:32:58,260] Trial 26 finished with value: 0.2942113481455079 and parameters: {'l1_ratio': 0.2369889061037231}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.3562609544733586
Fold 2 IBS: 0.43176165133392436
Fold 3 IBS: 0.26160556353498415
Fold 4 IBS: 0.40132749907226434
Fold 5 IBS: 0.3193968786274274
[I 2024-04-18 03:33:09,290] Trial 27 finished with value: 0.35407050940839174 and parameters: {'l1_ratio': 0.8410447076604634}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.26559812631181745
Fold 2 IBS: 0.2560450499503743
Fold 3 IBS: 0.18594838450712267
Fold 4 IBS: 0.22246540762805683
Fold 5 IBS: 0.25322532549966686
[I 2024-04-18 03:33:13,781] Trial 28 finished with value: 0.23665645877940764 and parameters: {'l1_ratio': 0.0509782299725429}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2961301904376688
Fold 2 IBS: 0.3295969303014792
Fold 3 IBS: 0.24024086151087937
Fold 4 IBS: 0.25784906268126706
Fold 5 IBS: 0.269599216953909
[I 2024-04-18 03:33:19,075] Trial 29 finished with value: 0.27868325237704067 and parameters: {'l1_ratio': 0.16449178959130645}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.323999413641621
Fold 2 IBS: 0.3737925715438823
Fold 3 IBS: 0.2597819272034746
Fold 4 IBS: 0.3058500958678592
Fold 5 IBS: 0.2829106180688475
[I 2024-04-18 03:33:25,081] Trial 30 finished with value: 0.3092669252651369 and parameters: {'l1_ratio': 0.346795168157318}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21397085422867324
Fold 2 IBS: 0.22157028797311415
Fold 3 IBS: 0.20452576194342553
Fold 4 IBS: 0.22473155609858803
Fold 5 IBS: 0.21811476107957953
[I 2024-04-18 03:33:26,303] Trial 31 finished with value: 0.2165826442646761 and parameters: {'l1_ratio': 0.00012562645093619398}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.27225907889604495
Fold 2 IBS: 0.2732835664473901
Fold 3 IBS: 0.20073934885177863
Fold 4 IBS: 0.23509013597313913
Fold 5 IBS: 0.25726334617372965
[I 2024-04-18 03:33:30,471] Trial 32 finished with value: 0.24772709526841646 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2138074791587558
Fold 2 IBS: 0.22134813431045475
Fold 3 IBS: 0.2042349535964269
Fold 4 IBS: 0.22454313080075414
Fold 5 IBS: 0.21783899933959353
[I 2024-04-18 03:33:31,491] Trial 33 finished with value: 0.21635453944119704 and parameters: {'l1_ratio': 0.0038119440586082136}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.3076117338732958
Fold 2 IBS: 0.35347025337778776
Fold 3 IBS: 0.250895697450227
Fold 4 IBS: 0.2771481013573193
Fold 5 IBS: 0.2758895249099628
[I 2024-04-18 03:33:36,545] Trial 34 finished with value: 0.2930030621937186 and parameters: {'l1_ratio': 0.23026639169144428}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2863383018335068
Fold 2 IBS: 0.3064423669227787
Fold 3 IBS: 0.22710003205238324
Fold 4 IBS: 0.24556867669193255
Fold 5 IBS: 0.26433813090377367
[I 2024-04-18 03:33:41,663] Trial 35 finished with value: 0.265957501680875 and parameters: {'l1_ratio': 0.12096304120315786}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.34666704288964956
Fold 2 IBS: 0.4054919638187621
Fold 3 IBS: 0.2693012096590123
Fold 4 IBS: 0.36857612265386847
Fold 5 IBS: 0.3063790747667835
[I 2024-04-18 03:33:47,977] Trial 36 finished with value: 0.33928308275761515 and parameters: {'l1_ratio': 0.6356169048248501}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.26693397885709624
Fold 2 IBS: 0.25955879519620656
Fold 3 IBS: 0.1887768677944709
Fold 4 IBS: 0.23259082980793377
Fold 5 IBS: 0.2540517791921987
[I 2024-04-18 03:33:52,063] Trial 37 finished with value: 0.2403824501695812 and parameters: {'l1_ratio': 0.054687817523133446}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.3058985632312213
Fold 2 IBS: 0.3504229929345377
Fold 3 IBS: 0.24956059859412896
Fold 4 IBS: 0.27402224734470276
Fold 5 IBS: 0.27506639043480247
[I 2024-04-18 03:33:57,629] Trial 38 finished with value: 0.29099415850787863 and parameters: {'l1_ratio': 0.21931160616991263}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.34427128575161986
Fold 2 IBS: 0.396969031824275
Fold 3 IBS: 0.26681147938385696
Fold 4 IBS: 0.35028800502214746
Fold 5 IBS: 0.29869004028083274
[I 2024-04-18 03:34:04,497] Trial 39 finished with value: 0.33140596845254644 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.31361202237112695
Fold 2 IBS: 0.3620088606906553
Fold 3 IBS: 0.2547297462241702
Fold 4 IBS: 0.28752949198659555
Fold 5 IBS: 0.278519735566506
[I 2024-04-18 03:34:10,606] Trial 40 finished with value: 0.2992799713678108 and parameters: {'l1_ratio': 0.2705989592091768}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2563164944576996
Fold 2 IBS: 0.2200274607203067
Fold 3 IBS: 0.16552860151022758
Fold 4 IBS: 0.22344414403621596
Fold 5 IBS: 0.24311369010897593
[I 2024-04-18 03:34:14,598] Trial 41 finished with value: 0.22168607816668517 and parameters: {'l1_ratio': 0.027162904551683964}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2888634523787618
Fold 2 IBS: 0.31282187034909475
Fold 3 IBS: 0.23111010621495556
Fold 4 IBS: 0.2484442038222898
Fold 5 IBS: 0.2658821332915675
[I 2024-04-18 03:34:20,659] Trial 42 finished with value: 0.2694243532113339 and parameters: {'l1_ratio': 0.13179451112728766}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2138921799998999
Fold 2 IBS: 0.2214638529760292
Fold 3 IBS: 0.2043850508608162
Fold 4 IBS: 0.22464117953227672
Fold 5 IBS: 0.21798205730686096
[I 2024-04-18 03:34:21,814] Trial 43 finished with value: 0.21647286413517658 and parameters: {'l1_ratio': 0.0018849190134430063}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2694233879474618
Fold 2 IBS: 0.26588059732052755
Fold 3 IBS: 0.19428226037293245
Fold 4 IBS: 0.2336899988428614
Fold 5 IBS: 0.25563053167144284
[I 2024-04-18 03:34:26,874] Trial 44 finished with value: 0.2437813552310452 and parameters: {'l1_ratio': 0.062069898702991955}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2988242939090895
Fold 2 IBS: 0.3365101768681706
Fold 3 IBS: 0.24379314378918376
Fold 4 IBS: 0.2626504206284691
Fold 5 IBS: 0.27142469348634174
[I 2024-04-18 03:34:32,131] Trial 45 finished with value: 0.28264054573625097 and parameters: {'l1_ratio': 0.18074152502476082}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2139708892293933
Fold 2 IBS: 0.22157033510263346
Fold 3 IBS: 0.20452582482260337
Fold 4 IBS: 0.22473159615863092
Fold 5 IBS: 0.21811482008317712
[I 2024-04-18 03:34:33,276] Trial 46 finished with value: 0.21658269307928765 and parameters: {'l1_ratio': 0.0001248501968914512}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.28168375697242326
Fold 2 IBS: 0.2959775417245305
Fold 3 IBS: 0.21983931358006428
Fold 4 IBS: 0.2413800712751579
Fold 5 IBS: 0.26212140811677054
[I 2024-04-18 03:34:38,870] Trial 47 finished with value: 0.2602004183337893 and parameters: {'l1_ratio': 0.10400500229453774}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.3516117256313314
Fold 2 IBS: 0.4258518519590235
Fold 3 IBS: 0.26513008276556904
Fold 4 IBS: 0.39915462665587886
Fold 5 IBS: 0.31696196065542287
[I 2024-04-18 03:34:48,146] Trial 48 finished with value: 0.3517420495334451 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.26708703128571115
Fold 2 IBS: 0.25989107316989046
Fold 3 IBS: 0.1890946400155125
Fold 4 IBS: 0.23265187943505203
Fold 5 IBS: 0.2541325889759823
[I 2024-04-18 03:34:54,036] Trial 49 finished with value: 0.24057144257642968 and parameters: {'l1_ratio': 0.05508628707157073}. Best is trial 21 with value: 0.21603927510328452.

Fold 1 IBS: 0.33778802019174287
Fold 2 IBS: 0.38741820423743006
Fold 3 IBS: 0.264810289756514
Fold 4 IBS: 0.3331631620960283
Fold 5 IBS: 0.29170859924633696
[I 2024-04-18 03:35:02,186] Trial 50 finished with value: 0.3229776551056104 and parameters: {'l1_ratio': 0.47241766561900594}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21371258737198034
Fold 2 IBS: 0.22121706409767253
Fold 3 IBS: 0.20406849034599145
Fold 4 IBS: 0.2244323393541318
Fold 5 IBS: 0.21767845909598596
[I 2024-04-18 03:35:03,871] Trial 51 finished with value: 0.21622178805315243 and parameters: {'l1_ratio': 0.006012844952470507}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.260653224914918
Fold 2 IBS: 0.24077638305525004
Fold 3 IBS: 0.17468089270319162
Fold 4 IBS: 0.22301401999923057
Fold 5 IBS: 0.24877391215848496
[I 2024-04-18 03:35:09,150] Trial 52 finished with value: 0.22957968656621502 and parameters: {'l1_ratio': 0.03723966440107636}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2789214391285436
Fold 2 IBS: 0.2893414372963976
Fold 3 IBS: 0.21447983485391123
Fold 4 IBS: 0.23905398139814546
Fold 5 IBS: 0.26072395818351224
[I 2024-04-18 03:35:14,188] Trial 53 finished with value: 0.25650413017210205 and parameters: {'l1_ratio': 0.09371920078344177}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.29054477686558305
Fold 2 IBS: 0.31654193579571077
Fold 3 IBS: 0.23337339118403078
Fold 4 IBS: 0.2504275410247261
Fold 5 IBS: 0.2667232299641647
[I 2024-04-18 03:35:19,928] Trial 54 finished with value: 0.27152217496684306 and parameters: {'l1_ratio': 0.13863039144986744}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2577415404391538
Fold 2 IBS: 0.21986549291673582
Fold 3 IBS: 0.16821609491776604
Fold 4 IBS: 0.22331164046867635
Fold 5 IBS: 0.2450509242644062
[I 2024-04-18 03:35:22,792] Trial 55 finished with value: 0.22283713860134763 and parameters: {'l1_ratio': 0.030205929359710455}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2791946189745129
Fold 2 IBS: 0.28993988221434885
Fold 3 IBS: 0.21504396689848052
Fold 4 IBS: 0.23929293929755618
Fold 5 IBS: 0.26089377281665926
[I 2024-04-18 03:35:27,080] Trial 56 finished with value: 0.2568730360403116 and parameters: {'l1_ratio': 0.09475513312872548}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.26191614801376073
Fold 2 IBS: 0.24474023325651018
Fold 3 IBS: 0.17760000750309066
Fold 4 IBS: 0.22287840457087352
Fold 5 IBS: 0.25023635929170857
[I 2024-04-18 03:35:31,486] Trial 57 finished with value: 0.2314742305271887 and parameters: {'l1_ratio': 0.040539611099824444}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.3004895169317333
Fold 2 IBS: 0.3405407813046012
Fold 3 IBS: 0.24528731597339293
Fold 4 IBS: 0.2655442018844567
Fold 5 IBS: 0.27248959226071684
[I 2024-04-18 03:35:38,022] Trial 58 finished with value: 0.28487028167098016 and parameters: {'l1_ratio': 0.19023456833118246}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.27469365085008707
Fold 2 IBS: 0.2790776415578619
Fold 3 IBS: 0.20590769208690582
Fold 4 IBS: 0.23642083948236856
Fold 5 IBS: 0.25851043729809325
[I 2024-04-18 03:35:42,893] Trial 59 finished with value: 0.25092205225506337 and parameters: {'l1_ratio': 0.07926849318546804}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2883610997166579
Fold 2 IBS: 0.3113113572095683
Fold 3 IBS: 0.230233428880392
Fold 4 IBS: 0.2477549646646059
Fold 5 IBS: 0.2655189147545598
[I 2024-04-18 03:35:47,921] Trial 60 finished with value: 0.26863595304515675 and parameters: {'l1_ratio': 0.1291766213414157}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21390047282806365
Fold 2 IBS: 0.22147511923284544
Fold 3 IBS: 0.20439982381907307
Fold 4 IBS: 0.22465073718749395
Fold 5 IBS: 0.2179960527485901
[I 2024-04-18 03:35:49,527] Trial 61 finished with value: 0.21648444116321325 and parameters: {'l1_ratio': 0.0016981035410079612}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2588249097374782
Fold 2 IBS: 0.2197353219066839
Fold 3 IBS: 0.1704961640221786
Fold 4 IBS: 0.22320549541336998
Fold 5 IBS: 0.24647119477687157
[I 2024-04-18 03:35:53,530] Trial 62 finished with value: 0.22374661717131644 and parameters: {'l1_ratio': 0.032682404126619644}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21397018179082378
Fold 2 IBS: 0.2215693824774351
Fold 3 IBS: 0.20452455394987254
Fold 4 IBS: 0.22473078643528197
Fold 5 IBS: 0.21811362749014643
[I 2024-04-18 03:35:55,002] Trial 63 finished with value: 0.21658170642871197 and parameters: {'l1_ratio': 0.00014054103048385946}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.27011422508759186
Fold 2 IBS: 0.26775466322536545
Fold 3 IBS: 0.19592278493637344
Fold 4 IBS: 0.2340259843887775
Fold 5 IBS: 0.25606944250724245
[I 2024-04-18 03:35:59,677] Trial 64 finished with value: 0.24477742002907016 and parameters: {'l1_ratio': 0.06435058671593123}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.28252414322997527
Fold 2 IBS: 0.29771816935841794
Fold 3 IBS: 0.2210788597243336
Fold 4 IBS: 0.24203016915456999
Fold 5 IBS: 0.26239137971329135
[I 2024-04-18 03:36:04,807] Trial 65 finished with value: 0.2611485442361176 and parameters: {'l1_ratio': 0.10676645561206867}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2560625239847248
Fold 2 IBS: 0.22005703040764027
Fold 3 IBS: 0.1650453335206106
Fold 4 IBS: 0.22346838661625618
Fold 5 IBS: 0.2427489149385408
[I 2024-04-18 03:36:07,986] Trial 66 finished with value: 0.22147643789355453 and parameters: {'l1_ratio': 0.02661187218765282}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.37044268122328555
Fold 2 IBS: 0.44056084051633715
Fold 3 IBS: 0.25859237561915943
Fold 4 IBS: 0.40029362403706875
Fold 5 IBS: 0.3253291681320267
[I 2024-04-18 03:36:16,292] Trial 67 finished with value: 0.35904373790557553 and parameters: {'l1_ratio': 0.9415445204645163}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.29678972847597695
Fold 2 IBS: 0.33081014733687897
Fold 3 IBS: 0.24086435769266556
Fold 4 IBS: 0.258648216878878
Fold 5 IBS: 0.26993120553118755
[I 2024-04-18 03:36:21,386] Trial 68 finished with value: 0.2794087311831174 and parameters: {'l1_ratio': 0.16718805987390054}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2727739181646616
Fold 2 IBS: 0.27438499466693483
Fold 3 IBS: 0.2016231764230389
Fold 4 IBS: 0.23533447383887335
Fold 5 IBS: 0.2575056963398518
[I 2024-04-18 03:36:26,023] Trial 69 finished with value: 0.24832445188667213 and parameters: {'l1_ratio': 0.07275981535153914}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.29262352819650045
Fold 2 IBS: 0.3214219357823847
Fold 3 IBS: 0.23598153160703061
Fold 4 IBS: 0.2529878166319173
Fold 5 IBS: 0.2677766329380722
[I 2024-04-18 03:36:30,756] Trial 70 finished with value: 0.274158289031181 and parameters: {'l1_ratio': 0.14778121697033292}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21338409261902286
Fold 2 IBS: 0.2207480663010568
Fold 3 IBS: 0.20351114236533724
Fold 4 IBS: 0.22403962496484123
Fold 5 IBS: 0.23213508753922424
[I 2024-04-18 03:36:32,574] Trial 71 finished with value: 0.21876360275789647 and parameters: {'l1_ratio': 0.014114435350334686}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21387371107356837
Fold 2 IBS: 0.22143872154533345
Fold 3 IBS: 0.2043521997927291
Fold 4 IBS: 0.2246198669485791
Fold 5 IBS: 0.21795088135385898
[I 2024-04-18 03:36:33,861] Trial 72 finished with value: 0.2164470761428138 and parameters: {'l1_ratio': 0.0023021530505712125}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2635356879087939
Fold 2 IBS: 0.25001600330055396
Fold 3 IBS: 0.18146721192939524
Fold 4 IBS: 0.22269152832186745
Fold 5 IBS: 0.25182917693366386
[I 2024-04-18 03:36:37,447] Trial 73 finished with value: 0.23390792167885488 and parameters: {'l1_ratio': 0.04518867411261723}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.2745695220822521
Fold 2 IBS: 0.27887523557386434
Fold 3 IBS: 0.2056821963490773
Fold 4 IBS: 0.2363371109297547

Fold 5 IBS: 0.2584616505371973
[I 2024-04-18 03:36:42,531] Trial 74 finished with value: 0.2507851430944291 and parameters: {'l1_ratio': 0.07892043023845302}. Best is trial 21 with value: 0.21603927510328452.
Fold 1 IBS: 0.21313182047046095
Fold 2 IBS: 0.22037736475237674
Fold 3 IBS: 0.16010920074470453
Fold 4 IBS: 0.2237320569494287
Fold 5 IBS: 0.23836461838323328
[I 2024-04-18 03:36:45,006] Trial 75 finished with value: 0.21114301226004079 and parameters: {'l1_ratio': 0.02072955188453046}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.3287530218967289
Fold 2 IBS: 0.37917617700959977
Fold 3 IBS: 0.26158106589941843
Fold 4 IBS: 0.31501595513424246
Fold 5 IBS: 0.2853694495234786
[I 2024-04-18 03:36:50,825] Trial 76 finished with value: 0.31397913389269366 and parameters: {'l1_ratio': 0.3870355975595541}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.28530342871988335
Fold 2 IBS: 0.3040168330578237
Fold 3 IBS: 0.225551220727241
Fold 4 IBS: 0.24451903227608202
Fold 5 IBS: 0.26372429652729984
[I 2024-04-18 03:36:57,139] Trial 77 finished with value: 0.264622962261666 and parameters: {'l1_ratio': 0.11687019786377956}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.2674331254373499
Fold 2 IBS: 0.26086954425496356
Fold 3 IBS: 0.1899238109334652
Fold 4 IBS: 0.23279865210759174
Fold 5 IBS: 0.2543528433502278
[I 2024-04-18 03:37:01,704] Trial 78 finished with value: 0.24107559521671967 and parameters: {'l1_ratio': 0.056154594426113154}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.34569310402154846
Fold 2 IBS: 0.40089434496661586
Fold 3 IBS: 0.26836635111101675
Fold 4 IBS: 0.35877145998965243
Fold 5 IBS: 0.3023470582975639
[I 2024-04-18 03:37:08,222] Trial 79 finished with value: 0.3352144636772795 and parameters: {'l1_ratio': 0.5933865341035967}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.25533086826308266
Fold 2 IBS: 0.22014065791153833
Fold 3 IBS: 0.16369981145972856
Fold 4 IBS: 0.22353703595723193
Fold 5 IBS: 0.24168603125145627
[I 2024-04-18 03:37:11,443] Trial 80 finished with value: 0.22087888096860758 and parameters: {'l1_ratio': 0.025060916383491588}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.21388725265444866
Fold 2 IBS: 0.22145715359365042
Fold 3 IBS: 0.20437627977836728
Fold 4 IBS: 0.22463549714218725
Fold 5 IBS: 0.21797374075919249
[I 2024-04-18 03:37:12,744] Trial 81 finished with value: 0.21646598478556922 and parameters: {'l1_ratio': 0.0019960740418129216}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.25712373944188543
Fold 2 IBS: 0.21994185005989428
Fold 3 IBS: 0.1669300945284154
Fold 4 IBS: 0.22337404731384927
Fold 5 IBS: 0.24414234245964048
[I 2024-04-18 03:37:15,761] Trial 82 finished with value: 0.22230241476073695 and parameters: {'l1_ratio': 0.028766098158872135}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.2756370407829565
Fold 2 IBS: 0.2813867724570479
Fold 3 IBS: 0.20799917346001393
Fold 4 IBS: 0.23690753318581576
Fold 5 IBS: 0.2590378268684592
[I 2024-04-18 03:37:20,176] Trial 83 finished with value: 0.2521936693508587 and parameters: {'l1_ratio': 0.08253043634945632}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.2671794155514875
Fold 2 IBS: 0.26018990260911123
Fold 3 IBS: 0.18936140954289093
Fold 4 IBS: 0.23269044707469463
Fold 5 IBS: 0.2541960205860743
[I 2024-04-18 03:37:24,342] Trial 84 finished with value: 0.24072343907285174 and parameters: {'l1_ratio': 0.055415715149052025}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.21395303397495746
Fold 2 IBS: 0.22154626704157782
Fold 3 IBS: 0.20449378002408458
Fold 4 IBS: 0.22471114308169146
Fold 5 IBS: 0.218084716254104
[I 2024-04-18 03:37:25,859] Trial 85 finished with value: 0.21655778807528306 and parameters: {'l1_ratio': 0.0005215840835063783}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.2642450413291615
Fold 2 IBS: 0.2523362324888313
Fold 3 IBS: 0.18316770319023895
Fold 4 IBS: 0.22260882999985301
Fold 5 IBS: 0.2523325407100105
[I 2024-04-18 03:37:29,796] Trial 86 finished with value: 0.23493806954361904 and parameters: {'l1_ratio': 0.04728480024208365}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.28343398929270225
Fold 2 IBS: 0.2997007458925723
Fold 3 IBS: 0.2226465726700436
Fold 4 IBS: 0.24281386304794914
Fold 5 IBS: 0.26277449521780033
[I 2024-04-18 03:37:34,492] Trial 87 finished with value: 0.26227393322421355 and parameters: {'l1_ratio': 0.11004887489614375}. Best is trial 75 with value: 0.21114301226004079.
Fold 1 IBS: 0.2131383117105851
Fold 2 IBS: 0.22038710786138424
Fold 3 IBS: 0.15998330693231183
Fold 4 IBS: 0.2237401069144564
Fold 5 IBS: 0.23818272716955363
[I 2024-04-18 03:37:36,764] Trial 88 finished with value: 0.21108631211765821 and parameters: {'l1_ratio': 0.020553093448131873}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.2764701313909446
Fold 2 IBS: 0.28337620635916266
Fold 3 IBS: 0.2097334239744273
Fold 4 IBS: 0.23737478475337767
Fold 5 IBS: 0.25945665306232574
[I 2024-04-18 03:37:41,489] Trial 89 finished with value: 0.25328223990804755 and parameters: {'l1_ratio': 0.08519659805878614}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.3476351293476806
Fold 2 IBS: 0.41403860921945
Fold 3 IBS: 0.26902876895675476
Fold 4 IBS: 0.3867934670123063
Fold 5 IBS: 0.3125013269681464
[I 2024-04-18 03:37:48,348] Trial 90 finished with value: 0.34599946030086765 and parameters: {'l1_ratio': 0.7135825642664739}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.2130958517255582
Fold 2 IBS: 0.22032322254860767
Fold 3 IBS: 0.16089857342129668
Fold 4 IBS: 0.22368735636015044
Fold 5 IBS: 0.2391475499624867
[I 2024-04-18 03:37:50,970] Trial 91 finished with value: 0.21143051080361994 and parameters: {'l1_ratio': 0.02171273205163586}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.21307738016388553
Fold 2 IBS: 0.22029531595677943
Fold 3 IBS: 0.16132081398375323
Fold 4 IBS: 0.22366433796656082
Fold 5 IBS: 0.23949334322501797
[I 2024-04-18 03:37:53,795] Trial 92 finished with value: 0.21157023825919938 and parameters: {'l1_ratio': 0.022221226479958906}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.2580875725861631
Fold 2 IBS: 0.2198242013575131
Fold 3 IBS: 0.16895765873686566
Fold 4 IBS: 0.22327793700040133
Fold 5 IBS: 0.24550605244661655
[I 2024-04-18 03:37:57,149] Trial 93 finished with value: 0.22313068442551195 and parameters: {'l1_ratio': 0.030988484291188605}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.2708459849581269
Fold 2 IBS: 0.2694548447500341
Fold 3 IBS: 0.19733165184931253
Fold 4 IBS: 0.2343410313645373
Fold 5 IBS: 0.25648491278720326
[I 2024-04-18 03:38:01,867] Trial 94 finished with value: 0.24569168514184284 and parameters: {'l1_ratio': 0.06651785262449127}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.21306989770131532
Fold 2 IBS: 0.22028399173801444
Fold 3 IBS: 0.16150723421810084
Fold 4 IBS: 0.2236550015280832
Fold 5 IBS: 0.2396937534212824
[I 2024-04-18 03:38:05,126] Trial 95 finished with value: 0.21164197572135923 and parameters: {'l1_ratio': 0.0224279062034072}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.2640915226577296
Fold 2 IBS: 0.2516148664172907
Fold 3 IBS: 0.18262422221026672
Fold 4 IBS: 0.22263270382262523
Fold 5 IBS: 0.25217592352724805
[I 2024-04-18 03:38:11,005] Trial 96 finished with value: 0.2346278477270321 and parameters: {'l1_ratio': 0.04667719156676619}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.2813126692044909
Fold 2 IBS: 0.2952501542774153
Fold 3 IBS: 0.21931395043702856
Fold 4 IBS: 0.2411031326787469
Fold 5 IBS: 0.26199649569759054
[I 2024-04-18 03:38:17,495] Trial 97 finished with value: 0.2597952804590545 and parameters: {'l1_ratio': 0.10291900626358978}. Best is trial 88 with value: 0.21108631211765821.
Fold 1 IBS: 0.2934935874360798
Fold 2 IBS: 0.323243088403449
Fold 3 IBS: 0.23702056614392356
Fold 4 IBS: 0.2540554750291846
Fold 5 IBS: 0.26818845702427474
[I 2024-04-18 03:38:22,777] Trial 98 finished with value: 0.2752002348073823 and parameters: {'l1_ratio': 0.15142750572372754}. Best is trial 88 with value: 0.21108631211765821.

Fold 1 IBS: 0.25619755604275585
Fold 2 IBS: 0.22004430756398247
Fold 3 IBS: 0.1652534368350093
Fold 4 IBS: 0.223457953868103
Fold 5 IBS: 0.2429068906694106
[I 2024-04-18 03:38:26,163] Trial 99 finished with value: 0.2215720289958522 and parameters: {'l1_ratio': 0.02684879348673712}. Best is trial 88 with value: 0.21108631211765821.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.21108631211765821], datetime_start=datetime.datetime(2024, 4, 18, 3, 37, 34, 498429), datetime_complete=datetime.datetime(2024, 4, 18, 3, 37, 36, 763722), params={'l1_ratio': 0.020553093448131873}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.21108631211765821

In [47]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [48]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.729
train_ibs:  0.211

#### Test

In [49]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [50]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.02638395621436353)

test_cindex : 0.59

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.020553093448131873)

test_ibs:  0.221

In [51]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [52]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:38:27,556] A new study created in memory with name: no-name-ca1bf25d-a49b-4901-b0b0-eb18e25d48f0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:40:01,892] Trial 0 finished with value: 0.7366032203169602 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:40:17,272] Trial 1 finished with value: 0.7181620567966567 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 03:40:29,047] Trial 2 finished with value: 0.7150860129299454 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:40:30,830] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:40:33,428] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 03:40:55,521] Trial 5 finished with value: 0.7100749491193421 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 03:42:18,543] Trial 6 finished with value: 0.727952663180055 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:42:24,824] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6056338028169014
[I 2024-04-18 03:42:45,462] Trial 8 finished with value: 0.5211267605633803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.704225352112676
[I 2024-04-18 03:43:01,392] Trial 9 finished with value: 0.7080431320407382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:43:02,826] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:43:54,915] Trial 11 finished with value: 0.7380484783177279 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 11 with value: 0.7380484783177279.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 03:45:26,596] Trial 12 finished with value: 0.7438602547617209 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4617373338142137, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 03:46:21,529] Trial 13 finished with value: 0.7433165908059199 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.430322282186733, 'max_features': None, 'min_weight_fraction_leaf': 0.1716937452680298, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:46:30,873] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.4652312819220314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3866899818434614, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:46:54,813] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.27229846028530913, 'max_features': None, 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.

Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6032863849765259
[I 2024-04-18 03:47:01,812] Trial 16 finished with value: 0.6633327721070438 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': None, 'min_weight_fraction_leaf': 0.1048543527585735, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:47:21,017] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.1424705672746025, 'max_features': None, 'min_weight_fraction_leaf': 0.20205510510599584, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:47:32,023] Trial 18 finished with value: 0.7335541813688149 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5392320730567087, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07958856082174798, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.5892018779342723
[I 2024-04-18 03:47:33,360] Trial 19 finished with value: 0.6638449108877411 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.5137509360533721, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16593096906146954, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:47:54,889] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8114307622571267, 'max_features': None, 'min_weight_fraction_leaf': 0.41597694280469266, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 03:48:44,851] Trial 21 finished with value: 0.7398700280611442 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.3990347915810166, 'max_features': None, 'min_weight_fraction_leaf': 0.14443114491291786, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:49:06,534] Trial 22 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.21351240485158024, 'max_features': None, 'min_weight_fraction_leaf': 0.2441929681165364, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 03:49:50,245] Trial 23 finished with value: 0.7271164711934142 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.3756805451824067, 'max_features': None, 'min_weight_fraction_leaf': 0.13775089899883528, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:50:23,404] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36406078817327137, 'max_features': None, 'min_weight_fraction_leaf': 0.1822392883483817, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:50:41,809] Trial 25 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.4837577457111593, 'max_features': None, 'min_weight_fraction_leaf': 0.27111099648458864, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7981220657276995
[I 2024-04-18 03:50:54,742] Trial 26 finished with value: 0.7952997362091728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.425133711322363, 'max_features': None, 'min_weight_fraction_leaf': 0.07929595127017089, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 03:51:02,294] Trial 27 finished with value: 0.7439785302441695 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.5634050049825258, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07348058796691775, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:51:07,666] Trial 28 finished with value: 0.7606780234987396 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.5671295227568508, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002810616935067567, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7981220657276995
[I 2024-04-18 03:51:13,148] Trial 29 finished with value: 0.7861497989039858 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06647154253337151, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7981220657276995
[I 2024-04-18 03:51:17,874] Trial 30 finished with value: 0.7826158421682422 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.670660906330469, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008496584402552174, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8571428571428571

Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 03:51:23,228] Trial 31 finished with value: 0.7936613975238874 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.7258118850709611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020186907613437947, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8169014084507042
[I 2024-04-18 03:51:27,117] Trial 32 finished with value: 0.7892741864327053 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 149, 'oob_score': True, 'max_samples': 0.7060378252364139, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04618667534698639, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 03:51:31,120] Trial 33 finished with value: 0.8006493236932368 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 155, 'oob_score': True, 'max_samples': 0.7605972338377621, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046274896708941554, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:51:34,821] Trial 34 finished with value: 0.7998566890977854 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.7633408434752601, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04380970481841874, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8356807511737089
[I 2024-04-18 03:51:37,151] Trial 35 finished with value: 0.803331848306836 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.7948212261000067, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10423395463781872, 'warm_start': True}. Best is trial 35 with value: 0.803331848306836.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:51:38,896] Trial 36 finished with value: 0.81388019672447 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8091332552149437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10837446978579603, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 03:51:40,685] Trial 37 finished with value: 0.8138484554748331 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.8220720793755758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09608472875949194, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8075117370892019
[I 2024-04-18 03:51:42,626] Trial 38 finished with value: 0.794834129497761 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8537902740382926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09525205057743304, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.863849765258216
[I 2024-04-18 03:51:44,501] Trial 39 finished with value: 0.8134528027162501 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9833072699349469, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10393928454601242, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 03:51:46,146] Trial 40 finished with value: 0.8193359257510359 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 79, 'oob_score': False, 'max_samples': 0.9974049101283982, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11156682941225779, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 03:51:47,779] Trial 41 finished with value: 0.8034774490599819 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9999220055692117, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12045420312726329, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:51:49,465] Trial 42 finished with value: 0.809391720026152 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.9881165529835445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12443985149382927, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8685446009389671
[I 2024-04-18 03:51:50,754] Trial 43 finished with value: 0.8118099200814217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.9912995656748597, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12253835631192889, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7535211267605634
[I 2024-04-18 03:51:51,535] Trial 44 finished with value: 0.7512725179741098 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.9192360586272437, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09432875921172784, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.8169014084507042
[I 2024-04-18 03:51:52,534] Trial 45 finished with value: 0.7805310602984772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 35, 'oob_score': False, 'max_samples': 0.8671059553512112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22329822046282632, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 03:51:54,692] Trial 46 finished with value: 0.7374183107739604 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 123, 'oob_score': False, 'max_samples': 0.9536184653009308, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1531269560181571, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 03:51:56,028] Trial 47 finished with value: 0.821440909099989 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.8733003039936599, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12467981297687225, 'warm_start': True}. Best is trial 47 with value: 0.821440909099989.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 03:51:58,192] Trial 48 finished with value: 0.8304915258944628 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.8813820217761629, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06296378903734845, 'warm_start': True}. Best is trial 48 with value: 0.8304915258944628.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 03:52:00,856] Trial 49 finished with value: 0.8329500051937337 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.8805367238926652, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057195379787481515, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 03:52:03,564] Trial 50 finished with value: 0.8314528643350888 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.9009010945275224, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.054961351160765004, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 03:52:07,136] Trial 51 finished with value: 0.8313163540347663 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.8934638023278324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03450702765653768, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 03:52:10,809] Trial 52 finished with value: 0.8320214536162119 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.8797580746407682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024666679991640003, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 03:52:13,463] Trial 53 finished with value: 0.829623312030853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 118, 'oob_score': False, 'max_samples': 0.8886913182351664, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038639798107064416, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 03:52:17,412] Trial 54 finished with value: 0.8269793471449424 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.8943965597615428, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02658068365989562, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 03:52:20,399] Trial 55 finished with value: 0.8314821925869167 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.9394960211783968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03414063784444427, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 03:52:24,763] Trial 56 finished with value: 0.8291458931503687 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.9464163990983746, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05957529961744705, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8967136150234741
[I 2024-04-18 03:52:28,181] Trial 57 finished with value: 0.837497279418745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8375194335284916, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028965413024752612, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8732394366197183
[I 2024-04-18 03:52:32,049] Trial 58 finished with value: 0.8257460337171384 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.8473410457317984, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023049662318096596, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 03:52:36,299] Trial 59 finished with value: 0.8490112951451346 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9190157687794943, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013504221373780535, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 03:52:41,935] Trial 60 finished with value: 0.8462284069610924 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9302291542086784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020986391606638635, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 03:52:47,510] Trial 61 finished with value: 0.8471575518568665 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9319335934099356, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0028492650677599558, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 03:52:52,993] Trial 62 finished with value: 0.8424040571187227 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.9488273152669577, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006993125885435061, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 03:52:59,886] Trial 63 finished with value: 0.8459918151364014 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.9558680489418835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00656722209863304, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 03:53:07,022] Trial 64 finished with value: 0.8560377835959099 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9511852166403515, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006787286025552868, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 03:53:14,035] Trial 65 finished with value: 0.8543281008735688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.959702372838177, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0021045537516321865, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9436619718309859
[I 2024-04-18 03:53:21,582] Trial 66 finished with value: 0.846986714506221 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9606657832305625, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009645713200115154, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 03:53:28,827] Trial 67 finished with value: 0.8422965637980504 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 282, 'oob_score': False, 'max_samples': 0.9696946680213249, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015463863160716843, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 03:53:36,833] Trial 68 finished with value: 0.8400810425063071 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.9226346461200242, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013757163062800108, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 03:53:40,351] Trial 69 finished with value: 0.735120849138696 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9207461742012929, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3619470610261025, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:53:44,072] Trial 70 finished with value: 0.7199549229649882 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.9621462391123464, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4708820505432424, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 03:53:49,969] Trial 71 finished with value: 0.8477117723943335 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.95365805085536, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006547106868712814, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 03:53:58,404] Trial 72 finished with value: 0.8468137779836808 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.9218265096398339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002129212342459046, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9014084507042254
[I 2024-04-18 03:54:05,195] Trial 73 finished with value: 0.8355677775332243 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.7855691032277902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015061828643737101, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-18 03:54:09,961] Trial 74 finished with value: 0.8441728577198884 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9254876714681857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0812631651455817, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 03:54:17,897] Trial 75 finished with value: 0.8362371866524855 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.9681737785400921, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015964899054660966, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 03:54:25,218] Trial 76 finished with value: 0.84313576068201 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.8305113746650353, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0426275461746545, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 03:54:30,878] Trial 77 finished with value: 0.8568403814547748 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.9144336511700586, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01595057842588041, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-18 03:54:36,247] Trial 78 finished with value: 0.8419192289956712 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9116776901842412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07343560570014901, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 03:54:42,189] Trial 79 finished with value: 0.8328178212078037 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.8605744759700164, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023396832105227285, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 03:54:47,055] Trial 80 finished with value: 0.7687749931412297 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.969349688986363, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2986900237576432, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 03:54:53,928] Trial 81 finished with value: 0.8508482566919376 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9412070505938585, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01576257355000931, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 03:55:00,922] Trial 82 finished with value: 0.8416282042647364 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.9068065686971891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.016797956013047826, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8732394366197183
[I 2024-04-18 03:55:06,327] Trial 83 finished with value: 0.8318825303180803 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.6153744430709406, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04832190639289941, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 03:55:12,459] Trial 84 finished with value: 0.8433724935297382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.9399975078027157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0345364942691951, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-18 03:55:17,632] Trial 85 finished with value: 0.8358557576420413 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9737845589861637, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01634294636489071, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-18 03:55:24,165] Trial 86 finished with value: 0.8377019506647049 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.8518058828861286, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05107482426381401, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 03:55:49,696] Trial 87 finished with value: 0.7178329643580474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.9965938454935799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.034448975293513207, 'warm_start': False}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 03:55:57,265] Trial 88 finished with value: 0.8457089722953801 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.9085692767397662, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0697346803584661, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 03:56:06,580] Trial 89 finished with value: 0.836101128647378 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 375, 'oob_score': False, 'max_samples': 0.7981108690303841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012687139847991694, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 03:56:12,718] Trial 90 finished with value: 0.858196741029675 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9399104719362167, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04454154696608814, 'warm_start': True}. Best is trial 90 with value: 0.858196741029675.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 03:56:19,062] Trial 91 finished with value: 0.8594063157686616 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.9393175331158453, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0004448382541777079, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 03:56:24,845] Trial 92 finished with value: 0.8504093975391417 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.9511651006370562, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023794967159176263, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 03:56:30,473] Trial 93 finished with value: 0.8507722251285642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.9393138993988948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04166845875792434, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 03:56:36,382] Trial 94 finished with value: 0.864047670519609 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-18 03:56:41,703] Trial 95 finished with value: 0.8462994805857642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 226, 'oob_score': False, 'max_samples': 0.9851260930666599, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0877741788827067, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 03:56:46,139] Trial 96 finished with value: 0.8456767787505284 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.9046678790431277, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05908913791760474, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8169014084507042
[I 2024-04-18 03:56:49,636] Trial 97 finished with value: 0.7824887018130806 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.9994611759628653, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04096131539525037, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 03:57:12,439] Trial 98 finished with value: 0.7022847020297285 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9435261125804136, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025743264975163525, 'warm_start': False}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9240506329113924

[I 2024-04-18 03:57:16,419] A new study created in memory with name: no-name-f99f3231-919a-4861-bfb0-4ebb10217a59

Fold 5 C-index: 0.9061032863849765
[I 2024-04-18 03:57:16,384] Trial 99 finished with value: 0.8374434398307532 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8689674666549045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04663818112580286, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.864047670519609], datetime_start=datetime.datetime(2024, 4, 18, 3, 56, 30, 489890), datetime_complete=datetime.datetime(2024, 4, 18, 3, 56, 36, 381467), params={'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=94, value=None)


* Best Score for C-index:
 0.864047670519609

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18324615167630967
Fold 2 IBS: 0.1973414798718171
Fold 3 IBS: 0.16795049053724004
Fold 4 IBS: 0.18912813741469703
Fold 5 IBS: 0.2061164871654968
[I 2024-04-18 03:58:43,166] Trial 0 finished with value: 0.18875654933311214 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20345329363741022
Fold 2 IBS: 0.1866704968763983
Fold 3 IBS: 0.18211060269283327
Fold 4 IBS: 0.18446935355917493
Fold 5 IBS: 0.20613420199922336
[I 2024-04-18 03:58:47,586] Trial 1 finished with value: 0.19256758975300803 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-18 03:58:50,085] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-18 03:58:59,869] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-18 03:59:07,438] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20630791540283333
Fold 2 IBS: 0.18077183063689325
Fold 3 IBS: 0.18637698687972554
Fold 4 IBS: 0.15939882886870535
Fold 5 IBS: 0.2113504541273204
[I 2024-04-18 03:59:24,992] Trial 5 finished with value: 0.18884120318309558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.18286701090322455
Fold 2 IBS: 0.18771259904008297
Fold 3 IBS: 0.1679729459105892
Fold 4 IBS: 0.19488974663997188
Fold 5 IBS: 0.2131586526955741
[I 2024-04-18 04:00:13,027] Trial 6 finished with value: 0.18932019103788852 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20907943912609248
Fold 2 IBS: 0.2142874391649597
Fold 3 IBS: 0.20035786531447508
Fold 4 IBS: 0.22002960031246824
Fold 5 IBS: 0.21626779318082703
[I 2024-04-18 04:00:24,439] Trial 7 finished with value: 0.2120044274197645 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-18 04:00:41,569] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20357073593273053
Fold 2 IBS: 0.18780891594621849
Fold 3 IBS: 0.18460304549691883
Fold 4 IBS: 0.1856640301109529
Fold 5 IBS: 0.20794919209811308
[I 2024-04-18 04:00:46,332] Trial 9 finished with value: 0.19391918391698676 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-18 04:01:06,378] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20470418186342312
Fold 2 IBS: 0.20409550521820866
Fold 3 IBS: 0.19035125570755929
Fold 4 IBS: 0.20279707515139048
Fold 5 IBS: 0.2139020077116487
[I 2024-04-18 04:01:20,167] Trial 11 finished with value: 0.203170005130446 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20586437433035337
Fold 2 IBS: 0.18045352650478874
Fold 3 IBS: 0.18471158232105125
Fold 4 IBS: 0.1564532839984733
Fold 5 IBS: 0.21278485149213985
[I 2024-04-18 04:01:42,915] Trial 12 finished with value: 0.1880535237293613 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9944667777599061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10294337889507951}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.21738156589672325
Fold 2 IBS: 0.18148498524761636
Fold 3 IBS: 0.20328771782225072
Fold 4 IBS: 0.16200397997147525
Fold 5 IBS: 0.20246860054845137
[I 2024-04-18 04:05:07,797] Trial 13 finished with value: 0.1933253698973034 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.9694270540157217, 'max_features': None, 'min_weight_fraction_leaf': 0.1530029930440125}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19707033841317873
Fold 2 IBS: 0.1876771636325187
Fold 3 IBS: 0.1818736950861829
Fold 4 IBS: 0.179566358950222
Fold 5 IBS: 0.2109513215570391
[I 2024-04-18 04:05:23,688] Trial 14 finished with value: 0.19142777552782828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.7631177214580046, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21229864789095249}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.22655147877004286
Fold 2 IBS: 0.18326284905513224
Fold 3 IBS: 0.2097169134350128
Fold 4 IBS: 0.16586651259722404
Fold 5 IBS: 0.20952385709991683
[I 2024-04-18 04:07:09,824] Trial 15 finished with value: 0.19898432219146575 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.9970673523205843, 'max_features': None, 'min_weight_fraction_leaf': 0.09604984749674861}. Best is trial 12 with value: 0.1880535237293613.

Fold 1 IBS: 0.20378808796262518
Fold 2 IBS: 0.19365995427708668
Fold 3 IBS: 0.1882413702928391
Fold 4 IBS: 0.19759396434280763
Fold 5 IBS: 0.21553362503994042
[I 2024-04-18 04:07:26,913] Trial 16 finished with value: 0.19976340038305979 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8184724465806228, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31376919111755797}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20035161627096812
Fold 2 IBS: 0.18410251599192942
Fold 3 IBS: 0.18211883476245105
Fold 4 IBS: 0.18801743258981968
Fold 5 IBS: 0.21327804714656015
[I 2024-04-18 04:07:37,258] Trial 17 finished with value: 0.19357368935234567 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.3060837787360696, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005619770510688432}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19808389265211931
Fold 2 IBS: 0.18205953021252363
Fold 3 IBS: 0.185875813422921
Fold 4 IBS: 0.17434571756518558
Fold 5 IBS: 0.212414509617453
[I 2024-04-18 04:07:58,686] Trial 18 finished with value: 0.19055589269404052 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.680642613858846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12812974712655775}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19002039864329462
Fold 2 IBS: 0.18942385941547232
Fold 3 IBS: 0.18799087691719493
Fold 4 IBS: 0.18284504372921612
Fold 5 IBS: 0.20840823704233402
[I 2024-04-18 04:08:47,584] Trial 19 finished with value: 0.1917376831495024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.8923233540949727, 'max_features': None, 'min_weight_fraction_leaf': 0.22336599579981053}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20241484728756806
Fold 2 IBS: 0.19065053491089928
Fold 3 IBS: 0.18779471719312824
Fold 4 IBS: 0.19480082717000774
Fold 5 IBS: 0.21868104809372813
[I 2024-04-18 04:08:57,964] Trial 20 finished with value: 0.19886839493106628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.7871968885021372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34030385853489}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20741632570728089
Fold 2 IBS: 0.1780845098687536
Fold 3 IBS: 0.1846122378972077
Fold 4 IBS: 0.1564868201189816
Fold 5 IBS: 0.21131308248390057
[I 2024-04-18 04:09:16,504] Trial 21 finished with value: 0.18758259521522488 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.6541307441098512, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06381773403573333}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21885274316469258
Fold 2 IBS: 0.17828077601342465
Fold 3 IBS: 0.1880861120963736
Fold 4 IBS: 0.15017691808187725
Fold 5 IBS: 0.208661756520607
[I 2024-04-18 04:09:38,605] Trial 22 finished with value: 0.18881166117539502 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6139693116960656, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04453049413403026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19871040202258342
Fold 2 IBS: 0.184765649243245
Fold 3 IBS: 0.18498703463344066
Fold 4 IBS: 0.18599311903171908
Fold 5 IBS: 0.21143993706602787
[I 2024-04-18 04:09:48,267] Trial 23 finished with value: 0.1931792283994032 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20038924075539685
Fold 2 IBS: 0.18852724912576502
Fold 3 IBS: 0.1847265574388743
Fold 4 IBS: 0.19388302387911258
Fold 5 IBS: 0.21617210096544462
[I 2024-04-18 04:10:02,028] Trial 24 finished with value: 0.1967396344329187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.4295396819868078, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16813485936717243}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.23819448878865138
Fold 2 IBS: 0.18859860435971892
Fold 3 IBS: 0.19682793240255014
Fold 4 IBS: 0.15957526364066002
Fold 5 IBS: 0.20198931781322124
[I 2024-04-18 04:14:31,413] Trial 25 finished with value: 0.19703712140096036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.7297972378004723, 'max_features': None, 'min_weight_fraction_leaf': 0.04981104107775003}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.2010034177138824
Fold 2 IBS: 0.182735296255063
Fold 3 IBS: 0.18466236755017185
Fold 4 IBS: 0.17246211363358033
Fold 5 IBS: 0.21643410204328975
[I 2024-04-18 04:14:43,249] Trial 26 finished with value: 0.19145945943919745 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.8472363371748154, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10973545356505882}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.1964328885601889
Fold 2 IBS: 0.18809613601862848
Fold 3 IBS: 0.1818420692920181
Fold 4 IBS: 0.17399619732336324
Fold 5 IBS: 0.2111836724460323
[I 2024-04-18 04:15:03,359] Trial 27 finished with value: 0.19031019272804622 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9331113837900542, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2386001330983712}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19854249756198333
Fold 2 IBS: 0.18810793646188287
Fold 3 IBS: 0.18308123282699756
Fold 4 IBS: 0.18681900970293147
Fold 5 IBS: 0.21245937503700765
[I 2024-04-18 04:15:15,774] Trial 28 finished with value: 0.19380201031816058 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.5883566242401418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1845919041664691}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19840416643063166
Fold 2 IBS: 0.18537155668553762
Fold 3 IBS: 0.18344052151498125
Fold 4 IBS: 0.17492059658908363
Fold 5 IBS: 0.21086762605161444
[I 2024-04-18 04:15:32,946] Trial 29 finished with value: 0.19060089345436973 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.6774353138386819, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.22252593046960736
Fold 2 IBS: 0.1888838348535354
Fold 3 IBS: 0.19671883214571217
Fold 4 IBS: 0.162697984958246
Fold 5 IBS: 0.1971675681434196
[I 2024-04-18 04:16:32,401] Trial 30 finished with value: 0.19359883011410411 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.04202783134992163}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.218645817549917
Fold 2 IBS: 0.17984916123604971
Fold 3 IBS: 0.18930240115766292
Fold 4 IBS: 0.1502748627436339
Fold 5 IBS: 0.20680109594224744
[I 2024-04-18 04:16:54,685] Trial 31 finished with value: 0.18897466772590218 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6145656696996076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028279638075097074}. Best is trial 21 with value: 0.18758259521522488.

Fold 1 IBS: 0.20444739845582136
Fold 2 IBS: 0.17446698341767913
Fold 3 IBS: 0.1910994493903993
Fold 4 IBS: 0.1668825886510828
Fold 5 IBS: 0.21103427734544067
[I 2024-04-18 04:17:08,298] Trial 32 finished with value: 0.18958613945208463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.6325115094238634, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0760629688237641}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21394095082970305
Fold 2 IBS: 0.18957239420831615
Fold 3 IBS: 0.18237897227425182
Fold 4 IBS: 0.17846689832832333
Fold 5 IBS: 0.2185435449686763
[I 2024-04-18 04:17:09,958] Trial 33 finished with value: 0.19658055212185413 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.7088178154422675, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12510702348081404}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21814598296546053
Fold 2 IBS: 0.1806418667764422
Fold 3 IBS: 0.185193327742374
Fold 4 IBS: 0.14930927407248543
Fold 5 IBS: 0.20730315585697304
[I 2024-04-18 04:17:32,104] Trial 34 finished with value: 0.18811872148274703 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.5179281521096981, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03287535020826214}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20068393107082932
Fold 2 IBS: 0.18004564547293722
Fold 3 IBS: 0.1813279250878163
Fold 4 IBS: 0.16606271502196493
Fold 5 IBS: 0.2133678565084531
[I 2024-04-18 04:17:47,149] Trial 35 finished with value: 0.1882976146324002 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.5205069556471076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08931012896561974}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19921865381139617
Fold 2 IBS: 0.1879147544934006
Fold 3 IBS: 0.18415951307165418
Fold 4 IBS: 0.17928295771289782
Fold 5 IBS: 0.21187622162524927
[I 2024-04-18 04:17:57,709] Trial 36 finished with value: 0.19249042014291962 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.34556748843479757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08517804478502394}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20689459020742101
Fold 2 IBS: 0.18578195800005948
Fold 3 IBS: 0.18062395532410724
Fold 4 IBS: 0.16979980454141178
Fold 5 IBS: 0.20913380244139584
[I 2024-04-18 04:18:10,191] Trial 37 finished with value: 0.19044682210287905 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.19350535662381702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02562193860216446}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20164172687027268
Fold 2 IBS: 0.179042406474406
Fold 3 IBS: 0.18484112426907948
Fold 4 IBS: 0.15977140249838878
Fold 5 IBS: 0.2120612409546842
[I 2024-04-18 04:18:27,980] Trial 38 finished with value: 0.18747158021336624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.5607171176186949, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06539515726225846}. Best is trial 38 with value: 0.18747158021336624.
Fold 1 IBS: 0.20421151305171514
Fold 2 IBS: 0.17932735612158596
Fold 3 IBS: 0.17928162605465459
Fold 4 IBS: 0.16526541395746405
Fold 5 IBS: 0.2090081959308534
[I 2024-04-18 04:18:44,982] Trial 39 finished with value: 0.18741882102325463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.3617667691015132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052772428028015156}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2022159312451902
Fold 2 IBS: 0.1848488680529207
Fold 3 IBS: 0.17740255174053524
Fold 4 IBS: 0.1726825614136245
Fold 5 IBS: 0.213121743730351
[I 2024-04-18 04:18:59,326] Trial 40 finished with value: 0.19005433123652432 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.3736866960473132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05524155311927098}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.22304701735374977
Fold 2 IBS: 0.19262749474927982
Fold 3 IBS: 0.18617094771467074
Fold 4 IBS: 0.16090440652263122
Fold 5 IBS: 0.2060830161959264
[I 2024-04-18 04:19:17,273] Trial 41 finished with value: 0.1937665765072516 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.26471791598500466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008610506287772067}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.19780135900892157
Fold 2 IBS: 0.1857789376740191
Fold 3 IBS: 0.1799971131723769
Fold 4 IBS: 0.1804099527573313
Fold 5 IBS: 0.21177881228015194
[I 2024-04-18 04:19:35,264] Trial 42 finished with value: 0.19115323497856015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.5034748057992058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13666482964507704}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21400092589198996
Fold 2 IBS: 0.2214210103976947
Fold 3 IBS: 0.2048692155883072
Fold 4 IBS: 0.22463234501283708
Fold 5 IBS: 0.2185873987821863
[I 2024-04-18 04:19:44,617] Trial 43 finished with value: 0.21670217913460305 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.4788775563231737, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20231241634002334
Fold 2 IBS: 0.18036495206092895
Fold 3 IBS: 0.1818599860701185
Fold 4 IBS: 0.16340196628946066
Fold 5 IBS: 0.21378560467248073
[I 2024-04-18 04:20:02,673] Trial 44 finished with value: 0.18834498508660244 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.5506248755449263, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0721857441783233}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1973845412708107
Fold 2 IBS: 0.18124870301190693
Fold 3 IBS: 0.1810814354603528
Fold 4 IBS: 0.1707551433320944
Fold 5 IBS: 0.2119250973889522
[I 2024-04-18 04:20:23,275] Trial 45 finished with value: 0.18847898409282343 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.5775224127982328, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10537693884726008}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21070983930823925
Fold 2 IBS: 0.18608759362092114
Fold 3 IBS: 0.18204123382213788
Fold 4 IBS: 0.16642669368966861
Fold 5 IBS: 0.21219350314332874
[I 2024-04-18 04:20:44,675] Trial 46 finished with value: 0.19149177271685913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.26128950045955984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02835891103553452}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20296038593675553
Fold 2 IBS: 0.1835795355330322
Fold 3 IBS: 0.18270515601508316
Fold 4 IBS: 0.17696688246148076
Fold 5 IBS: 0.2124434684430158
[I 2024-04-18 04:20:58,261] Trial 47 finished with value: 0.19173108567787348 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.39724110016399944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06776177948204519}. Best is trial 39 with value: 0.18741882102325463.

Fold 1 IBS: 0.21397545241919333
Fold 2 IBS: 0.22060585341756236
Fold 3 IBS: 0.20519466411613427
Fold 4 IBS: 0.2248054198587066
Fold 5 IBS: 0.21758241895615993
[I 2024-04-18 04:21:11,054] Trial 48 finished with value: 0.2164327617535513 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.1840472657347053, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20733215663048163
Fold 2 IBS: 0.19840873877308707
Fold 3 IBS: 0.1896647344947966
Fold 4 IBS: 0.2057146078926162
Fold 5 IBS: 0.2152447795126918
[I 2024-04-18 04:21:19,158] Trial 49 finished with value: 0.20327300346073468 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.4611544071310423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02536063881705921}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.204879944056226
Fold 2 IBS: 0.18198982906903266
Fold 3 IBS: 0.1813060638484819
Fold 4 IBS: 0.16283844353857155
Fold 5 IBS: 0.21363299219754156
[I 2024-04-18 04:21:34,770] Trial 50 finished with value: 0.18892945454197077 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.5416005248904892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0034087820600749476}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2004109367454522
Fold 2 IBS: 0.18404020643987526
Fold 3 IBS: 0.18234193379348762
Fold 4 IBS: 0.17143012200567861
Fold 5 IBS: 0.21239169444633466
[I 2024-04-18 04:21:47,828] Trial 51 finished with value: 0.19012297868616568 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.5290774243115414, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09439815236719598}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20363791714493526
Fold 2 IBS: 0.18084498958548437
Fold 3 IBS: 0.1865787886727044
Fold 4 IBS: 0.15958133230330762
Fold 5 IBS: 0.21346890098280094
[I 2024-04-18 04:22:05,765] Trial 52 finished with value: 0.18882238573784652 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.646747773042784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08961848913350215}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20381819322938977
Fold 2 IBS: 0.18114674744033232
Fold 3 IBS: 0.18113417018982886
Fold 4 IBS: 0.1618949090102553
Fold 5 IBS: 0.21456765862332783
[I 2024-04-18 04:22:27,117] Trial 53 finished with value: 0.18851233569862683 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.5080082016246513, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06630490839370301}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2042758448261322
Fold 2 IBS: 0.18877763887578689
Fold 3 IBS: 0.18209755324442445
Fold 4 IBS: 0.19391559310720333
Fold 5 IBS: 0.2159060762300408
[I 2024-04-18 04:22:41,393] Trial 54 finished with value: 0.1969945412567175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.38392655290485045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1447625548982195}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2034151090750003
Fold 2 IBS: 0.18176049250213502
Fold 3 IBS: 0.1857336365331899
Fold 4 IBS: 0.1788179124206326
Fold 5 IBS: 0.2129610073834551
[I 2024-04-18 04:22:55,174] Trial 55 finished with value: 0.1925376315828826 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.5872802927086659, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046825551317268566}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20422176706868694
Fold 2 IBS: 0.1924062351097664
Fold 3 IBS: 0.18544969707631245
Fold 4 IBS: 0.1984840238620755
Fold 5 IBS: 0.21497590518150314
[I 2024-04-18 04:23:06,779] Trial 56 finished with value: 0.19910752565966888 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.4154965081431159, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18037694403417448}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2059789858573675
Fold 2 IBS: 0.1967683996639164
Fold 3 IBS: 0.18831908034352698
Fold 4 IBS: 0.20147608897626476
Fold 5 IBS: 0.21654528774605497
[I 2024-04-18 04:23:15,921] Trial 57 finished with value: 0.20181756851742616 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7776350329623957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3781865060679536}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20703604925067237
Fold 2 IBS: 0.18243435974189295
Fold 3 IBS: 0.18268181766890698
Fold 4 IBS: 0.20149520002925903
Fold 5 IBS: 0.21479477144824155
[I 2024-04-18 04:23:20,231] Trial 58 finished with value: 0.1976884396277946 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.32208030951555616, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11116699744055775}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21121978023043514
Fold 2 IBS: 0.17834386764399476
Fold 3 IBS: 0.18431619963737042
Fold 4 IBS: 0.15794559160168345
Fold 5 IBS: 0.211915583151784
[I 2024-04-18 04:23:44,993] Trial 59 finished with value: 0.18874820445305357 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.706317491452594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06164379588338738}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1966264720209345
Fold 2 IBS: 0.18597478555674649
Fold 3 IBS: 0.1786448987547083
Fold 4 IBS: 0.16171860015636114
Fold 5 IBS: 0.20668689381001223
[I 2024-04-18 04:25:10,334] Trial 60 finished with value: 0.18593033005975254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.4446079220615766, 'max_features': None, 'min_weight_fraction_leaf': 0.09271318262887082}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2024856806183152
Fold 2 IBS: 0.18195716111018798
Fold 3 IBS: 0.18480931433897935
Fold 4 IBS: 0.16237325049629045
Fold 5 IBS: 0.20714210552628523
[I 2024-04-18 04:26:36,558] Trial 61 finished with value: 0.18775350241801164 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 306, 'oob_score': True, 'max_samples': 0.44685465277095665, 'max_features': None, 'min_weight_fraction_leaf': 0.08682673693183435}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2284531812120082
Fold 2 IBS: 0.1948622570457934
Fold 3 IBS: 0.18812485157230974
Fold 4 IBS: 0.16088214458625358
Fold 5 IBS: 0.20190289439703843
[I 2024-04-18 04:29:01,603] Trial 62 finished with value: 0.19484506576268068 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.4515303316200064, 'max_features': None, 'min_weight_fraction_leaf': 0.037039554766136004}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2252402779389061
Fold 2 IBS: 0.1862300882985594
Fold 3 IBS: 0.18602106947089103
Fold 4 IBS: 0.17312433407761857
Fold 5 IBS: 0.1889042172268272
[I 2024-04-18 04:31:20,304] Trial 63 finished with value: 0.19190399740256042 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.41265009702186795, 'max_features': None, 'min_weight_fraction_leaf': 0.016364606682246152}. Best is trial 60 with value: 0.18593033005975254.

Fold 1 IBS: 0.18697650055709675
Fold 2 IBS: 0.18964751614322145
Fold 3 IBS: 0.17157067951262514
Fold 4 IBS: 0.17048079186700552
Fold 5 IBS: 0.20812563312237994
[I 2024-04-18 04:32:18,923] Trial 64 finished with value: 0.18536022424046578 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.36087148528744895, 'max_features': None, 'min_weight_fraction_leaf': 0.10501492814170305}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.185980269157479
Fold 2 IBS: 0.18929665176523391
Fold 3 IBS: 0.17261558628019577
Fold 4 IBS: 0.17528863593015434
Fold 5 IBS: 0.20987976574068176
[I 2024-04-18 04:33:07,704] Trial 65 finished with value: 0.18661218177474898 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.35503340896452096, 'max_features': None, 'min_weight_fraction_leaf': 0.10944245403951429}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18694115431926822
Fold 2 IBS: 0.1908501583998164
Fold 3 IBS: 0.17205632092618067
Fold 4 IBS: 0.18203552427470343
Fold 5 IBS: 0.21326387492637428
[I 2024-04-18 04:33:56,679] Trial 66 finished with value: 0.1890294065692686 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.3614405881665075, 'max_features': None, 'min_weight_fraction_leaf': 0.12510407630083206}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397879618526044
Fold 2 IBS: 0.22095626300254492
Fold 3 IBS: 0.2049272671362546
Fold 4 IBS: 0.2246487203312697
Fold 5 IBS: 0.21797754042983516
[I 2024-04-18 04:34:12,873] Trial 67 finished with value: 0.21649771741703297 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.277566908191509, 'max_features': None, 'min_weight_fraction_leaf': 0.16326642133899677}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18701806869001636
Fold 2 IBS: 0.19002615779169066
Fold 3 IBS: 0.17109529332077666
Fold 4 IBS: 0.17558286313646593
Fold 5 IBS: 0.20866467885193285
[I 2024-04-18 04:35:03,513] Trial 68 finished with value: 0.1864774123581765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.3339648956191334, 'max_features': None, 'min_weight_fraction_leaf': 0.10534737249789848}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.213990042339758
Fold 2 IBS: 0.22081844148187832
Fold 3 IBS: 0.2049164994171005
Fold 4 IBS: 0.22451019970461408
Fold 5 IBS: 0.2178161153197119
[I 2024-04-18 04:35:15,774] Trial 69 finished with value: 0.21641025965261257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.22058879264036, 'max_features': None, 'min_weight_fraction_leaf': 0.14500630501117967}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397438613021721
Fold 2 IBS: 0.22116611565870514
Fold 3 IBS: 0.20499774371165358
Fold 4 IBS: 0.22471498188046043
Fold 5 IBS: 0.21823664145637212
[I 2024-04-18 04:35:27,010] Trial 70 finished with value: 0.21661797376748168 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.34596416260173934, 'max_features': None, 'min_weight_fraction_leaf': 0.2703111919415455}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18924036720156343
Fold 2 IBS: 0.18779280930051329
Fold 3 IBS: 0.17209448151288856
Fold 4 IBS: 0.17958207486087677
Fold 5 IBS: 0.211566257073253
[I 2024-04-18 04:36:12,126] Trial 71 finished with value: 0.18805519798981898 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.31453931029426085, 'max_features': None, 'min_weight_fraction_leaf': 0.1045230982104525}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19657952397027323
Fold 2 IBS: 0.19022838128535594
Fold 3 IBS: 0.1708771341601037
Fold 4 IBS: 0.17168544722624235
Fold 5 IBS: 0.20713375074665116
[I 2024-04-18 04:36:59,909] Trial 72 finished with value: 0.1873008474777253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.2926475761323768, 'max_features': None, 'min_weight_fraction_leaf': 0.07798192572483449}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19885306195698255
Fold 2 IBS: 0.18210548225096054
Fold 3 IBS: 0.17731375226506932
Fold 4 IBS: 0.16883406032672896
Fold 5 IBS: 0.20809348652266163
[I 2024-04-18 04:37:39,336] Trial 73 finished with value: 0.18703996866448058 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.2870778190236743, 'max_features': None, 'min_weight_fraction_leaf': 0.05561809788206867}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.193787788585605
Fold 2 IBS: 0.18733247875335163
Fold 3 IBS: 0.17837994780791747
Fold 4 IBS: 0.1744246643744868
Fold 5 IBS: 0.21343920626735596
[I 2024-04-18 04:38:15,658] Trial 74 finished with value: 0.1894728171577434 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.22588589287949842, 'max_features': None, 'min_weight_fraction_leaf': 0.05443689708608288}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18723429594597044
Fold 2 IBS: 0.18527389087754653
Fold 3 IBS: 0.17197014707614233
Fold 4 IBS: 0.1772724521433817
Fold 5 IBS: 0.21429754155065364
[I 2024-04-18 04:38:52,819] Trial 75 finished with value: 0.1872096655187389 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.2998143519691557, 'max_features': None, 'min_weight_fraction_leaf': 0.1075330144825516}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1941066110336133
Fold 2 IBS: 0.18509351343143435
Fold 3 IBS: 0.17110131699959152
Fold 4 IBS: 0.18270444973194716
Fold 5 IBS: 0.21156937371299012
[I 2024-04-18 04:39:23,098] Trial 76 finished with value: 0.1889150529819153 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.28316698675748087, 'max_features': None, 'min_weight_fraction_leaf': 0.12059869029554741}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397695237476239
Fold 2 IBS: 0.22118615223089322
Fold 3 IBS: 0.2050313552835387
Fold 4 IBS: 0.2247532956416355
Fold 5 IBS: 0.21820980850510233
[I 2024-04-18 04:39:34,655] Trial 77 finished with value: 0.21663151280718643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.3371898508848934, 'max_features': None, 'min_weight_fraction_leaf': 0.2048303246846501}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.195733817221237
Fold 2 IBS: 0.18784802284526486
Fold 3 IBS: 0.1763445138354909
Fold 4 IBS: 0.17500708454376265
Fold 5 IBS: 0.20952700605055732
[I 2024-04-18 04:40:25,905] Trial 78 finished with value: 0.18889208889926254 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.29504437594758753, 'max_features': None, 'min_weight_fraction_leaf': 0.07587622273136602}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21396670472446544
Fold 2 IBS: 0.22085379157505564
Fold 3 IBS: 0.20493941845669997
Fold 4 IBS: 0.22470262306501207
Fold 5 IBS: 0.21714959439503256
[I 2024-04-18 04:40:39,280] Trial 79 finished with value: 0.21632242644325314 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.13307661238331164, 'max_features': None, 'min_weight_fraction_leaf': 0.11597487641803922}. Best is trial 64 with value: 0.18536022424046578.

Fold 1 IBS: 0.2139852535910293
Fold 2 IBS: 0.22079135086710738
Fold 3 IBS: 0.2049571432154721
Fold 4 IBS: 0.22449984942587378
Fold 5 IBS: 0.21784420818016068
[I 2024-04-18 04:40:52,063] Trial 80 finished with value: 0.21641556105592863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.23317876663764808, 'max_features': None, 'min_weight_fraction_leaf': 0.13195032778351135}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18698963922132994
Fold 2 IBS: 0.19117908340974094
Fold 3 IBS: 0.1716425830420473
Fold 4 IBS: 0.1706227695034198
Fold 5 IBS: 0.20890166136319582
[I 2024-04-18 04:41:41,408] Trial 81 finished with value: 0.1858671473079468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.3619448678095568, 'max_features': None, 'min_weight_fraction_leaf': 0.10057070644705586}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1890967403784016
Fold 2 IBS: 0.18652324224983566
Fold 3 IBS: 0.17238080905282963
Fold 4 IBS: 0.16710329314707312
Fold 5 IBS: 0.209650785925764
[I 2024-04-18 04:42:33,775] Trial 82 finished with value: 0.18495097415078082 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.3624030825154118, 'max_features': None, 'min_weight_fraction_leaf': 0.09714741335387223}. Best is trial 82 with value: 0.18495097415078082.
Fold 1 IBS: 0.1869379635607008
Fold 2 IBS: 0.1840979377124555
Fold 3 IBS: 0.1723208864840007
Fold 4 IBS: 0.16624305438296152
Fold 5 IBS: 0.20739680918357425
[I 2024-04-18 04:43:33,503] Trial 83 finished with value: 0.18339933026473856 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.39234117831739307, 'max_features': None, 'min_weight_fraction_leaf': 0.09956600887465704}. Best is trial 83 with value: 0.18339933026473856.
Fold 1 IBS: 0.1886542770417182
Fold 2 IBS: 0.18606078762892803
Fold 3 IBS: 0.17038230752313355
Fold 4 IBS: 0.1646204973275064
Fold 5 IBS: 0.20651428479641726
[I 2024-04-18 04:44:34,233] Trial 84 finished with value: 0.1832464308635407 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19155628917728368
Fold 2 IBS: 0.1801885982714529
Fold 3 IBS: 0.17804730003931615
Fold 4 IBS: 0.1693620308491127
Fold 5 IBS: 0.20783919776163526
[I 2024-04-18 04:45:21,540] Trial 85 finished with value: 0.18539868321976014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.3968957116262019, 'max_features': None, 'min_weight_fraction_leaf': 0.095219664847033}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18538493455740376
Fold 2 IBS: 0.18576229943013492
Fold 3 IBS: 0.17402978107752123
Fold 4 IBS: 0.18507755128123915
Fold 5 IBS: 0.21358478244911275
[I 2024-04-18 04:45:51,560] Trial 86 finished with value: 0.18876786975908236 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.38638292055767265, 'max_features': None, 'min_weight_fraction_leaf': 0.17872796639110672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19006306497707842
Fold 2 IBS: 0.1859568983552553
Fold 3 IBS: 0.17526064526770588
Fold 4 IBS: 0.16110281294560094
Fold 5 IBS: 0.20520872126963988
[I 2024-04-18 04:46:53,926] Trial 87 finished with value: 0.18351842856305606 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.4051015506296675, 'max_features': None, 'min_weight_fraction_leaf': 0.09713693453540154}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19767011171898427
Fold 2 IBS: 0.17964734520295073
Fold 3 IBS: 0.1836195742480708
Fold 4 IBS: 0.1667956970154799
Fold 5 IBS: 0.2070890710759274
[I 2024-04-18 04:47:41,583] Trial 88 finished with value: 0.1869643598522826 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.4334251281469186, 'max_features': None, 'min_weight_fraction_leaf': 0.09492515708957672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18447989656323524
Fold 2 IBS: 0.1882071335854152
Fold 3 IBS: 0.17009416602918556
Fold 4 IBS: 0.18175070837886942
Fold 5 IBS: 0.21200575266539284
[I 2024-04-18 04:48:18,035] Trial 89 finished with value: 0.18730753144441964 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.40662933261411155, 'max_features': None, 'min_weight_fraction_leaf': 0.14538592818664145}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18291200990480525
Fold 2 IBS: 0.18829799983042705
Fold 3 IBS: 0.174582652991839
Fold 4 IBS: 0.1734065332761776
Fold 5 IBS: 0.2073726719246909
[I 2024-04-18 04:49:19,094] Trial 90 finished with value: 0.18531437358558794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.46906936332717275, 'max_features': None, 'min_weight_fraction_leaf': 0.1301923106019002}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18483018153750577
Fold 2 IBS: 0.18822465780769382
Fold 3 IBS: 0.1731074140071581
Fold 4 IBS: 0.17188948389568984
Fold 5 IBS: 0.20714468645851628
[I 2024-04-18 04:50:23,295] Trial 91 finished with value: 0.18503928474131276 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.47678737384020253, 'max_features': None, 'min_weight_fraction_leaf': 0.1325172709355868}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18950832462950518
Fold 2 IBS: 0.18701656820376608
Fold 3 IBS: 0.17893499023469356
Fold 4 IBS: 0.17722915182580176
Fold 5 IBS: 0.20663881973138198
[I 2024-04-18 04:51:14,783] Trial 92 finished with value: 0.18786557092502973 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.49169288583702514, 'max_features': None, 'min_weight_fraction_leaf': 0.13392414841790756}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19861247726074407
Fold 2 IBS: 0.17973057843635412
Fold 3 IBS: 0.185421278409284
Fold 4 IBS: 0.16412850305110133
Fold 5 IBS: 0.20541831001893
[I 2024-04-18 04:52:37,871] Trial 93 finished with value: 0.1866622294352827 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4745011682049886, 'max_features': None, 'min_weight_fraction_leaf': 0.09685737891379577}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19722640593255503
Fold 2 IBS: 0.18658267818572852
Fold 3 IBS: 0.17931575780016162
Fold 4 IBS: 0.15937059058391914
Fold 5 IBS: 0.20605274303785986
[I 2024-04-18 04:53:48,653] Trial 94 finished with value: 0.1857096351080448 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.4244190509544878, 'max_features': None, 'min_weight_fraction_leaf': 0.08390492642221409}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18486260175817798
Fold 2 IBS: 0.18637157071560814
Fold 3 IBS: 0.17201029045136673
Fold 4 IBS: 0.18278192459752535
Fold 5 IBS: 0.21486338860156232
[I 2024-04-18 04:54:24,027] Trial 95 finished with value: 0.1881779552248481 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.3768152460146832, 'max_features': None, 'min_weight_fraction_leaf': 0.16125627455265384}. Best is trial 84 with value: 0.1832464308635407.

Fold 1 IBS: 0.19987889711029083
Fold 2 IBS: 0.18568352389906653
Fold 3 IBS: 0.18380646487398802
Fold 4 IBS: 0.16033813976360883
Fold 5 IBS: 0.20642365546571148
[I 2024-04-18 04:55:41,254] Trial 96 finished with value: 0.18722613622253315 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 363, 'oob_score': False, 'max_samples': 0.4255182801365352, 'max_features': None, 'min_weight_fraction_leaf': 0.08056036420837291}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19365837237754394
Fold 2 IBS: 0.183435405665406
Fold 3 IBS: 0.18008910470800357
Fold 4 IBS: 0.17339462295545943
Fold 5 IBS: 0.20781358095494984
[I 2024-04-18 04:56:30,417] Trial 97 finished with value: 0.18767821733227258 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4693979321374093, 'max_features': None, 'min_weight_fraction_leaf': 0.1201270975782226}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18503478594867145
Fold 2 IBS: 0.1888913820526276
Fold 3 IBS: 0.1708577577733008
Fold 4 IBS: 0.18063206055766248
Fold 5 IBS: 0.214156204168513
[I 2024-04-18 04:57:05,245] Trial 98 finished with value: 0.18791443810015507 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.3850920531360686, 'max_features': None, 'min_weight_fraction_leaf': 0.1315399576273898}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.20344124949745349
Fold 2 IBS: 0.18698507294354125
Fold 3 IBS: 0.1879934856478453
Fold 4 IBS: 0.1880278288749208
Fold 5 IBS: 0.2133922668795308
[I 2024-04-18 04:57:16,902] Trial 99 finished with value: 0.19596798076865835 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.40653139828572354, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08424550739812792}. Best is trial 84 with value: 0.1832464308635407.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.1832464308635407], datetime_start=datetime.datetime(2024, 4, 18, 4, 43, 33, 539720), datetime_complete=datetime.datetime(2024, 4, 18, 4, 44, 34, 232270), params={'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.1832464308635407

In [53]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [54]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.864
train_ibs:  0.183

#### Test

In [55]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [56]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=11, max_features='auto', max_leaf_nodes=15,
                     max_samples=0.9847467855272036, min_samples_leaf=4,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.04749646122417352,
                     n_estimators=230, random_state=123, warm_start=True)

test_cindex:  0.629

RandomSurvivalForest(max_depth=2, max_features=None, max_leaf_nodes=7,
                     max_samples=0.3902292236281065, min_samples_leaf=4,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.0959966989881746,
                     n_estimators=344, random_state=123)

test_ibs:  0.205

In [57]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [58]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [59]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 04:57:36,508] A new study created in memory with name: no-name-6ba76334-c459-42d6-99e6-ddaa904995a0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 04:57:39,249] Trial 0 finished with value: 0.7784578545189774 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:57:46,063] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 04:58:01,003] Trial 2 finished with value: 0.7601142724144229 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 04:58:02,446] Trial 3 finished with value: 0.802961090796227 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:58:07,917] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:58:14,292] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 04:58:18,031] Trial 6 finished with value: 0.7670018279196149 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6150234741784038
[I 2024-04-18 04:58:26,593] Trial 7 finished with value: 0.6820130047188975 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 04:58:27,326] Trial 8 finished with value: 0.7996535923726207 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.5539906103286385
[I 2024-04-18 04:58:43,788] Trial 9 finished with value: 0.6684380652697066 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:58:46,312] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 04:58:46,922] Trial 11 finished with value: 0.7252477001554444 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 04:58:47,940] Trial 12 finished with value: 0.7795687852038334 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 04:58:49,515] Trial 13 finished with value: 0.7859770734903794 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:58:51,230] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:58:52,110] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.40889055344541997}. Best is trial 3 with value: 0.802961090796227.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 04:58:54,024] Trial 16 finished with value: 0.7903520467896392 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.884183184043622, 'min_weight_fraction_leaf': 0.10581506507448754}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:58:56,391] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.37217752523657055, 'min_weight_fraction_leaf': 0.19947678741058694}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 04:58:57,869] Trial 18 finished with value: 0.7422562391542786 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 21, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6674013857794929, 'min_weight_fraction_leaf': 0.0023155280568105674}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 04:58:59,717] Trial 19 finished with value: 0.7919172217583121 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 177, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.35588501080184637}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 04:59:00,896] Trial 20 finished with value: 0.7884100418072868 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7140167187076433, 'min_weight_fraction_leaf': 0.28881891871571913}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 04:59:03,579] Trial 21 finished with value: 0.7828532818336494 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8819344617828546, 'min_weight_fraction_leaf': 0.3430677365625254}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-18 04:59:05,502] Trial 22 finished with value: 0.7949143304625697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8606079420302547, 'min_weight_fraction_leaf': 0.37164871595060495}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:59:07,144] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8095519124644711, 'min_weight_fraction_leaf': 0.44720270469880896}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:59:09,321] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6043934042800692, 'min_weight_fraction_leaf': 0.3984329214033346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7181372549019608
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6455399061032864
[I 2024-04-18 04:59:10,481] Trial 25 finished with value: 0.7173359925057237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9355023621313151, 'min_weight_fraction_leaf': 0.21828153747802176}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 04:59:17,440] Trial 26 finished with value: 0.75455954833675 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 172, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7429676103800898, 'min_weight_fraction_leaf': 0.2902550218399806}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 04:59:18,290] Trial 27 finished with value: 0.7870695134161543 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 32, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.07430019929598344}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:59:19,732] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 110, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6203838276523786, 'min_weight_fraction_leaf': 0.49397030324411406}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 04:59:22,906] Trial 29 finished with value: 0.7664099905509458 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7463806142458222, 'min_weight_fraction_leaf': 0.12619621560869665}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 04:59:25,131] Trial 30 finished with value: 0.7959507907686649 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9444316884960255, 'min_weight_fraction_leaf': 0.10548580221002543}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8392857142857143

Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 04:59:27,290] Trial 31 finished with value: 0.8023701302106281 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9175308644810205, 'min_weight_fraction_leaf': 0.1088935662786611}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 04:59:29,506] Trial 32 finished with value: 0.7950579336258078 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 211, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9467713628420997, 'min_weight_fraction_leaf': 0.08138167552522578}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:59:32,065] Trial 33 finished with value: 0.8061356825263047 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.937124800917338, 'min_weight_fraction_leaf': 0.10798501652350923}. Best is trial 33 with value: 0.8061356825263047.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:59:37,186] Trial 34 finished with value: 0.8069410046551562 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9924586053612823, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 34 with value: 0.8069410046551562.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 04:59:43,791] Trial 35 finished with value: 0.8337706480426819 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 307, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.99537727544732, 'min_weight_fraction_leaf': 0.04956730948759107}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 05:00:01,103] Trial 36 finished with value: 0.7482461120884926 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9947891025922952, 'min_weight_fraction_leaf': 0.040945703784245044}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 05:00:10,212] Trial 37 finished with value: 0.847904896492382 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.989290011992841, 'min_weight_fraction_leaf': 0.02856480473176247}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 05:00:18,878] Trial 38 finished with value: 0.8469659293562317 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9932170620443503, 'min_weight_fraction_leaf': 0.050004592573005685}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 05:00:43,403] Trial 39 finished with value: 0.7495415406312282 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9915601275040028, 'min_weight_fraction_leaf': 0.03663352433082424}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 05:00:54,203] Trial 40 finished with value: 0.8357412545967835 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.02508749840989511}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 05:01:04,800] Trial 41 finished with value: 0.8293587936722526 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47059202334413597, 'min_weight_fraction_leaf': 0.028824885734288947}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:01:16,181] Trial 42 finished with value: 0.8460265073711295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47951227685883335, 'min_weight_fraction_leaf': 0.013760080445973905}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 05:01:24,361] Trial 43 finished with value: 0.818279225092199 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3956943544905941, 'min_weight_fraction_leaf': 0.06238579527271516}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 05:01:33,749] Trial 44 finished with value: 0.8360856192344845 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 443, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4206894066469547, 'min_weight_fraction_leaf': 0.022459821558201455}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.8967136150234741
[I 2024-04-18 05:01:45,781] Trial 45 finished with value: 0.8420095331119368 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5190626877291048, 'min_weight_fraction_leaf': 0.009502780876316706}. Best is trial 37 with value: 0.847904896492382.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8028169014084507
[I 2024-04-18 05:01:55,246] Trial 46 finished with value: 0.8220544611789512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.517469689795079, 'min_weight_fraction_leaf': 0.07841045931780831}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 05:02:27,318] Trial 47 finished with value: 0.7254847827232809 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 414, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.32086266244117334, 'min_weight_fraction_leaf': 0.01763716368072068}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 05:02:36,949] Trial 48 finished with value: 0.8350464295509287 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 460, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4023308297410664, 'min_weight_fraction_leaf': 0.003079257502260936}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 05:02:45,157] Trial 49 finished with value: 0.8397048390094625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 368, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5566958033733842, 'min_weight_fraction_leaf': 0.05919578966108157}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 05:02:52,182] Trial 50 finished with value: 0.8168300522124603 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 355, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5346285785794207, 'min_weight_fraction_leaf': 0.05949010437559907}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:03:02,252] Trial 51 finished with value: 0.8426559761897272 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4307713618159553, 'min_weight_fraction_leaf': 0.0006143407440005848}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.863849765258216
[I 2024-04-18 05:03:11,005] Trial 52 finished with value: 0.8261414109558636 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.2944027889978438, 'min_weight_fraction_leaf': 0.0025196302934173548}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 05:03:18,288] Trial 53 finished with value: 0.7977685626836676 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.17582352730772366, 'min_weight_fraction_leaf': 0.061407856338507316}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 05:03:26,823] Trial 54 finished with value: 0.7531047646128582 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 473, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.44561277075368966, 'min_weight_fraction_leaf': 0.08811499948097072}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 05:03:37,388] Trial 55 finished with value: 0.8665875045053596 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5744229763504507, 'min_weight_fraction_leaf': 0.016027842870494274}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 05:03:45,044] Trial 56 finished with value: 0.6951645058986333 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.015257524234107825}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 05:03:55,879] Trial 57 finished with value: 0.8481318045459971 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6103451470664683, 'min_weight_fraction_leaf': 0.047571291705527236}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 05:04:03,211] Trial 58 finished with value: 0.7701604423354131 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.59366729390164, 'min_weight_fraction_leaf': 0.14674774348708902}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 05:04:36,090] Trial 59 finished with value: 0.758267844731695 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6716331483015671, 'min_weight_fraction_leaf': 0.04950449980370537}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 05:04:45,418] Trial 60 finished with value: 0.8025306955794198 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6374430422021584, 'min_weight_fraction_leaf': 0.16819923331696962}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 05:04:57,891] Trial 61 finished with value: 0.8267317399171535 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49232023541877573, 'min_weight_fraction_leaf': 0.00145953757858059}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 05:05:06,061] Trial 62 finished with value: 0.8414621270800418 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 402, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4565775326135385, 'min_weight_fraction_leaf': 0.0216071430745067}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 05:05:17,379] Trial 63 finished with value: 0.8515511699906788 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.574595322070414, 'min_weight_fraction_leaf': 0.04569685903621326}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 05:05:28,180] Trial 64 finished with value: 0.8397072520072715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5869227943626324, 'min_weight_fraction_leaf': 0.04476269499363313}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.784037558685446
[I 2024-04-18 05:05:37,548] Trial 65 finished with value: 0.8070528716762316 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5714061896889552, 'min_weight_fraction_leaf': 0.09443804061211797}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 05:05:47,209] Trial 66 finished with value: 0.8117060028439325 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4269898374784659, 'min_weight_fraction_leaf': 0.06693452124581281}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 05:05:54,484] Trial 67 finished with value: 0.8090148375189878 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 375, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8415815579585453, 'min_weight_fraction_leaf': 0.03102886731531589}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 05:06:03,039] Trial 68 finished with value: 0.724330800854678 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6969921866106945, 'min_weight_fraction_leaf': 0.08996201441410404}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8685446009389671
[I 2024-04-18 05:06:11,933] Trial 69 finished with value: 0.8410235474195836 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6336109184394701, 'min_weight_fraction_leaf': 0.04462823296429158}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 05:06:19,356] Trial 70 finished with value: 0.7949235593846933 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9130147369001846, 'min_weight_fraction_leaf': 0.25717771363652614}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 05:06:32,331] Trial 71 finished with value: 0.8504560046599232 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5168055835891595, 'min_weight_fraction_leaf': 0.012986169067804712}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8967136150234741
[I 2024-04-18 05:06:42,766] Trial 72 finished with value: 0.8519584263631383 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5366958727104124, 'min_weight_fraction_leaf': 0.016031857840163272}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8028169014084507
[I 2024-04-18 05:06:52,428] Trial 73 finished with value: 0.8207791294121825 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5266040099828285, 'min_weight_fraction_leaf': 0.07379071659454789}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 05:07:04,450] Trial 74 finished with value: 0.8657901849373276 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.556218611994605, 'min_weight_fraction_leaf': 0.026708566480428787}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 05:07:11,926] Trial 75 finished with value: 0.8181142885767413 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.569175138136116, 'min_weight_fraction_leaf': 0.049779903595510204}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 05:07:40,034] Trial 76 finished with value: 0.7457830837322044 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.61013169816922, 'min_weight_fraction_leaf': 0.032654970370419666}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 05:07:48,708] Trial 77 finished with value: 0.813252260011932 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6556499931697389, 'min_weight_fraction_leaf': 0.11468485034119792}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 05:07:57,678] Trial 78 finished with value: 0.8054529568030716 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5407839514816556, 'min_weight_fraction_leaf': 0.13017998804408376}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:08:10,027] Trial 79 finished with value: 0.8680221676184047 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9631780533456042, 'min_weight_fraction_leaf': 0.022603700176597446}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 05:08:19,156] Trial 80 finished with value: 0.796736053008863 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5088492830088868, 'min_weight_fraction_leaf': 0.02502911966074306}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:08:30,777] Trial 81 finished with value: 0.882207251893772 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9615950289600182, 'min_weight_fraction_leaf': 0.03679139394563669}. Best is trial 81 with value: 0.882207251893772.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9436619718309859
[I 2024-04-18 05:08:41,307] Trial 82 finished with value: 0.8858022781309804 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9436619718309859
[I 2024-04-18 05:08:52,266] Trial 83 finished with value: 0.8652682964140128 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9609090906034798, 'min_weight_fraction_leaf': 0.01406330393712882}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 05:09:04,140] Trial 84 finished with value: 0.8614808250890755 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9134206211086566, 'min_weight_fraction_leaf': 0.01387175275139686}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 05:09:10,286] Trial 85 finished with value: 0.8498449433258773 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9573743509441937, 'min_weight_fraction_leaf': 0.037220356101627605}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-18 05:09:17,457] Trial 86 finished with value: 0.8063147993763705 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9691139339019299, 'min_weight_fraction_leaf': 0.013557733109048805}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:09:26,055] Trial 87 finished with value: 0.8606583123370746 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9145533784322645, 'min_weight_fraction_leaf': 0.07241658060725681}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 05:09:50,426] Trial 88 finished with value: 0.7577736506359624 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.91048505123246, 'min_weight_fraction_leaf': 0.07341369185217136}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 05:09:56,676] Trial 89 finished with value: 0.7985598378397373 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8690506465331735, 'min_weight_fraction_leaf': 0.189066433472832}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 05:10:03,039] Trial 90 finished with value: 0.7685681160339142 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8972668164493001, 'min_weight_fraction_leaf': 0.31515481216778163}. Best is trial 82 with value: 0.8858022781309804.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9483568075117371
[I 2024-04-18 05:10:14,876] Trial 91 finished with value: 0.862597275251046 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9707802904512073, 'min_weight_fraction_leaf': 0.024021851910904807}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 05:10:26,208] Trial 92 finished with value: 0.8605776934106274 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9280981755055671, 'min_weight_fraction_leaf': 0.023404006766994168}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 05:10:35,237] Trial 93 finished with value: 0.8582896374728435 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 320, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499587877144377, 'min_weight_fraction_leaf': 0.03127381290624083}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9014084507042254
[I 2024-04-18 05:10:45,371] Trial 94 finished with value: 0.8665655880498362 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666217297893754, 'min_weight_fraction_leaf': 0.058324374733458}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 05:10:55,637] Trial 95 finished with value: 0.8664219797791237 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9706033105898769, 'min_weight_fraction_leaf': 0.06930608338875063}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 05:11:01,925] Trial 96 finished with value: 0.7713977049757649 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9653170534920801, 'min_weight_fraction_leaf': 0.05657719832813177}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 05:11:09,593] Trial 97 finished with value: 0.8459290116474474 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9660782335192536, 'min_weight_fraction_leaf': 0.10022719516204912}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 05:11:19,834] Trial 98 finished with value: 0.8772114347448893 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470976294421786, 'min_weight_fraction_leaf': 0.037342531882997666}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907

[I 2024-04-18 05:11:29,094] A new study created in memory with name: no-name-4912070d-7026-4765-841a-a9e7c739b5f4

Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:11:29,080] Trial 99 finished with value: 0.8535852615977915 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9441404618918096, 'min_weight_fraction_leaf': 0.08095118320482457}. Best is trial 82 with value: 0.8858022781309804.


* Best trial for C-index:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.8858022781309804], datetime_start=datetime.datetime(2024, 4, 18, 5, 8, 30, 792986), datetime_complete=datetime.datetime(2024, 4, 18, 5, 8, 41, 306660), params={'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for C-index:
 0.8858022781309804

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19573874032428965
Fold 2 IBS: 0.19215300245103015
Fold 3 IBS: 0.18577123192698092
Fold 4 IBS: 0.18877405090465085
Fold 5 IBS: 0.2108069355911196
[I 2024-04-18 05:11:40,744] Trial 0 finished with value: 0.19464879223961423 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-18 05:11:58,389] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.18661490821092397
Fold 2 IBS: 0.18849796485994302
Fold 3 IBS: 0.16935693688351927
Fold 4 IBS: 0.16616413385030462
Fold 5 IBS: 0.21353095384309942
[I 2024-04-18 05:12:14,423] Trial 2 finished with value: 0.18483297952955807 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18461528870168228
Fold 2 IBS: 0.19204843106240665
Fold 3 IBS: 0.16690491265843854
Fold 4 IBS: 0.1668314734874405
Fold 5 IBS: 0.21495543742143608
[I 2024-04-18 05:12:20,369] Trial 3 finished with value: 0.18507110866628082 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-18 05:12:33,565] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-18 05:12:40,120] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19873722451693057
Fold 2 IBS: 0.19705874496937723
Fold 3 IBS: 0.1849295300703863
Fold 4 IBS: 0.19065127758534944
Fold 5 IBS: 0.21038780527035808
[I 2024-04-18 05:12:54,372] Trial 6 finished with value: 0.1963529164824803 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2092186818635856
Fold 2 IBS: 0.2146879015458582
Fold 3 IBS: 0.2003062385248317
Fold 4 IBS: 0.21667734530345348
Fold 5 IBS: 0.2164099945650469
[I 2024-04-18 05:13:02,840] Trial 7 finished with value: 0.2114600323605552 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18257976996986042
Fold 2 IBS: 0.19411505967038614
Fold 3 IBS: 0.17136720904530045
Fold 4 IBS: 0.17268722966186423
Fold 5 IBS: 0.21366089922807047
[I 2024-04-18 05:13:04,850] Trial 8 finished with value: 0.18688203351509633 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21317294453259816
Fold 2 IBS: 0.21979053165324058
Fold 3 IBS: 0.20367290529718618
Fold 4 IBS: 0.22322856514743522
Fold 5 IBS: 0.21829561184880927
[I 2024-04-18 05:13:22,772] Trial 9 finished with value: 0.2156321116958539 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2139727346768592
Fold 2 IBS: 0.2213120202940904
Fold 3 IBS: 0.20503568053719107
Fold 4 IBS: 0.2245613118501098
Fold 5 IBS: 0.21766314539351875
[I 2024-04-18 05:13:42,556] Trial 10 finished with value: 0.21650897855035384 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19343732165265656
Fold 2 IBS: 0.18906543074097565
Fold 3 IBS: 0.17814248070868705
Fold 4 IBS: 0.17824816439818994
Fold 5 IBS: 0.2121006857387383
[I 2024-04-18 05:13:46,809] Trial 11 finished with value: 0.1901988166478495 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1889048827611632
Fold 2 IBS: 0.19557019296937925
Fold 3 IBS: 0.1711785441540699
Fold 4 IBS: 0.1739105142666198
Fold 5 IBS: 0.21378813670908908
[I 2024-04-18 05:13:53,356] Trial 12 finished with value: 0.18867045417206424 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21602403915542812
Fold 2 IBS: 0.22135942967444958
Fold 3 IBS: 0.207522129090302
Fold 4 IBS: 0.22681102026289354
Fold 5 IBS: 0.2196363896884173
[I 2024-04-18 05:13:54,231] Trial 13 finished with value: 0.21827060157429812 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.1768405475625161}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1908749026630227
Fold 2 IBS: 0.1928239743663976
Fold 3 IBS: 0.16705801079598037
Fold 4 IBS: 0.15060359337075535
Fold 5 IBS: 0.22085198243745763
[I 2024-04-18 05:13:59,848] Trial 14 finished with value: 0.18444249272672272 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8615610863035676, 'min_weight_fraction_leaf': 0.00662188941038383}. Best is trial 14 with value: 0.18444249272672272.

Fold 1 IBS: 0.18383586845275063
Fold 2 IBS: 0.2000835973214874
Fold 3 IBS: 0.15349960014749967
Fold 4 IBS: 0.13669669509253474
Fold 5 IBS: 0.23424660843190576
[I 2024-04-18 05:14:14,939] Trial 15 finished with value: 0.18167247388923563 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.0023088139988564262}. Best is trial 15 with value: 0.18167247388923563.
Fold 1 IBS: 0.1860236953856494
Fold 2 IBS: 0.2016030715036904
Fold 3 IBS: 0.155469005191737
Fold 4 IBS: 0.13731033566044606
Fold 5 IBS: 0.22747010982683524
[I 2024-04-18 05:14:30,133] Trial 16 finished with value: 0.1815752435136716 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8957765840335672, 'min_weight_fraction_leaf': 0.010191311991891749}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17998535045197436
Fold 2 IBS: 0.18813498335112747
Fold 3 IBS: 0.17047606760378545
Fold 4 IBS: 0.18020967518371683
Fold 5 IBS: 0.21407585022837167
[I 2024-04-18 05:14:39,403] Trial 17 finished with value: 0.18657638536379517 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9042785918294833, 'min_weight_fraction_leaf': 0.42038595995868033}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.21392851730727483
Fold 2 IBS: 0.2203112302740686
Fold 3 IBS: 0.20531706619567533
Fold 4 IBS: 0.22509036885374237
Fold 5 IBS: 0.21706040157641074
[I 2024-04-18 05:14:52,124] Trial 18 finished with value: 0.21634151684143438 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 312, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.22508105757456376}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1780064255903332
Fold 2 IBS: 0.1911276300331187
Fold 3 IBS: 0.16786438905278223
Fold 4 IBS: 0.1726113214449123
Fold 5 IBS: 0.21667391270579664
[I 2024-04-18 05:15:02,540] Trial 19 finished with value: 0.18525673576538862 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895543806821031, 'min_weight_fraction_leaf': 0.3097789443945588}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17575403131452658
Fold 2 IBS: 0.20366539827290087
Fold 3 IBS: 0.1659331777904529
Fold 4 IBS: 0.16662123172048018
Fold 5 IBS: 0.2231823176617039
[I 2024-04-18 05:15:15,647] Trial 20 finished with value: 0.18703123135201288 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8867517870122669, 'min_weight_fraction_leaf': 0.3678346055590361}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18848376456042643
Fold 2 IBS: 0.18922500536261308
Fold 3 IBS: 0.1744885363823047
Fold 4 IBS: 0.16595205181867084
Fold 5 IBS: 0.2141373046342922
[I 2024-04-18 05:15:20,234] Trial 21 finished with value: 0.18645733255166147 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8638184920383039, 'min_weight_fraction_leaf': 0.006217904257385862}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18773929580856016
Fold 2 IBS: 0.18598260697487606
Fold 3 IBS: 0.16906412373747556
Fold 4 IBS: 0.16368622468310087
Fold 5 IBS: 0.21228289069902992
[I 2024-04-18 05:15:30,057] Trial 22 finished with value: 0.18375102838060853 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9916304513453179, 'min_weight_fraction_leaf': 0.04142928400152037}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18853550770642435
Fold 2 IBS: 0.18431558910147325
Fold 3 IBS: 0.1692342266159003
Fold 4 IBS: 0.161355478193544
Fold 5 IBS: 0.21536507583817294
[I 2024-04-18 05:15:40,557] Trial 23 finished with value: 0.18376117549110296 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.971566349397283, 'min_weight_fraction_leaf': 0.048431151398292585}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18850231376560317
Fold 2 IBS: 0.18839766190435636
Fold 3 IBS: 0.17219466449743842
Fold 4 IBS: 0.169776646003973
Fold 5 IBS: 0.21215306500728826
[I 2024-04-18 05:15:48,026] Trial 24 finished with value: 0.18620487023573185 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9955995613709457, 'min_weight_fraction_leaf': 0.09809641655746978}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1921961203281156
Fold 2 IBS: 0.18453047987592264
Fold 3 IBS: 0.16816775310750728
Fold 4 IBS: 0.16025534556804477
Fold 5 IBS: 0.21319844694890142
[I 2024-04-18 05:16:00,998] Trial 25 finished with value: 0.18366962916569834 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8862362117578689, 'min_weight_fraction_leaf': 0.041224153446454304}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17583280457561398
Fold 2 IBS: 0.22475673220665077
Fold 3 IBS: 0.15629098950451684
Fold 4 IBS: 0.1521771664224135
Fold 5 IBS: 0.23338728904188227
[I 2024-04-18 05:16:20,995] Trial 26 finished with value: 0.1884889963502155 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 360, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7252723068238901, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.20101808740413787
Fold 2 IBS: 0.19364223596866614
Fold 3 IBS: 0.1581801817697089
Fold 4 IBS: 0.13490957896358
Fold 5 IBS: 0.22061607552916476
[I 2024-04-18 05:16:47,179] Trial 27 finished with value: 0.18167323192705154 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.845241798302616, 'min_weight_fraction_leaf': 0.027493332139652292}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18622176253816625
Fold 2 IBS: 0.1999255042061287
Fold 3 IBS: 0.15584044840112993
Fold 4 IBS: 0.13526516764544533
Fold 5 IBS: 0.22802733572495915
[I 2024-04-18 05:17:10,691] Trial 28 finished with value: 0.18105604370316586 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8292254352883182, 'min_weight_fraction_leaf': 0.0850371679063824}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.17657957905072683
Fold 2 IBS: 0.22919795735904133
Fold 3 IBS: 0.15929222778603266
Fold 4 IBS: 0.15524572509143825
Fold 5 IBS: 0.23445783766810277
[I 2024-04-18 05:17:26,560] Trial 29 finished with value: 0.19095466539106837 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7274266056837884, 'min_weight_fraction_leaf': 0.10433587359666342}. Best is trial 28 with value: 0.18105604370316586.

Fold 1 IBS: 0.18973195855840097
Fold 2 IBS: 0.19901752012782084
Fold 3 IBS: 0.1553163395473765
Fold 4 IBS: 0.13719070606611738
Fold 5 IBS: 0.22779776404493374
[I 2024-04-18 05:17:44,336] Trial 30 finished with value: 0.18181085766892985 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 305, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8220971907615917, 'min_weight_fraction_leaf': 0.076444606879153}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.2164877455822723
Fold 2 IBS: 0.18827035681808446
Fold 3 IBS: 0.16565039781780372
Fold 4 IBS: 0.1417428766421557
Fold 5 IBS: 0.21575647924950747
[I 2024-04-18 05:18:22,650] Trial 31 finished with value: 0.18558157122196473 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 394, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9184090898444338, 'min_weight_fraction_leaf': 0.024048041704110457}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.19225590417182326
Fold 2 IBS: 0.19791478229895018
Fold 3 IBS: 0.15389649317000442
Fold 4 IBS: 0.13656122267395734
Fold 5 IBS: 0.2252432881883185
[I 2024-04-18 05:18:41,891] Trial 32 finished with value: 0.18117433810061073 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 339, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8398341558075527, 'min_weight_fraction_leaf': 0.07586243370778376}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.190099017520626
Fold 2 IBS: 0.19508386306537273
Fold 3 IBS: 0.15693141894064483
Fold 4 IBS: 0.1365814363126798
Fold 5 IBS: 0.2242513991199539
[I 2024-04-18 05:19:00,182] Trial 33 finished with value: 0.18058942699185546 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 328, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7393625680125055, 'min_weight_fraction_leaf': 0.0754095802252665}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1755388893326841
Fold 2 IBS: 0.22138923578766054
Fold 3 IBS: 0.15690295668954182
Fold 4 IBS: 0.1534002161724209
Fold 5 IBS: 0.23198506769187896
[I 2024-04-18 05:19:14,130] Trial 34 finished with value: 0.18784327313483729 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6411042409555412, 'min_weight_fraction_leaf': 0.1529713735680485}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18263254865306666
Fold 2 IBS: 0.20049141147500113
Fold 3 IBS: 0.1589092797218102
Fold 4 IBS: 0.13938245171749084
Fold 5 IBS: 0.22964090743188564
[I 2024-04-18 05:19:39,973] Trial 35 finished with value: 0.1822113197998509 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7381816364515512, 'min_weight_fraction_leaf': 0.09309533777806683}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20497295855599004
Fold 2 IBS: 0.20576214803730022
Fold 3 IBS: 0.19198391113255453
Fold 4 IBS: 0.20085090326245184
Fold 5 IBS: 0.21341213707903006
[I 2024-04-18 05:19:50,889] Trial 36 finished with value: 0.2033964116134653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 329, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6138083294843051, 'min_weight_fraction_leaf': 0.0629620770536272}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19527602912356506
Fold 2 IBS: 0.19485558505510198
Fold 3 IBS: 0.18174564019749553
Fold 4 IBS: 0.1886871891677721
Fold 5 IBS: 0.21159832776451956
[I 2024-04-18 05:20:04,752] Trial 37 finished with value: 0.19443255426169087 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 415, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5042351390354268, 'min_weight_fraction_leaf': 0.11525786573963492}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.2123324981539864
Fold 2 IBS: 0.21873675502636114
Fold 3 IBS: 0.2026801887391686
Fold 4 IBS: 0.2224371860221609
Fold 5 IBS: 0.2175210624415119
[I 2024-04-18 05:20:12,275] Trial 38 finished with value: 0.21474153807663776 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7775660926270328, 'min_weight_fraction_leaf': 0.20133705660393178}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396615975925184
Fold 2 IBS: 0.22136475473478168
Fold 3 IBS: 0.2049150370158522
Fold 4 IBS: 0.22458804795980403
Fold 5 IBS: 0.21835431962555002
[I 2024-04-18 05:20:31,285] Trial 39 finished with value: 0.21663766381904798 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 8, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3933070032512962, 'min_weight_fraction_leaf': 0.26079682823609596}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19711707736031672
Fold 2 IBS: 0.19196214561471756
Fold 3 IBS: 0.18237907022466343
Fold 4 IBS: 0.1838407369325067
Fold 5 IBS: 0.21066154976207546
[I 2024-04-18 05:20:42,853] Trial 40 finished with value: 0.19319211597885597 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.06421109758861666}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18187508975758154
Fold 2 IBS: 0.20470571701119905
Fold 3 IBS: 0.15462214843892588
Fold 4 IBS: 0.13791700485858222
Fold 5 IBS: 0.23199241229585657
[I 2024-04-18 05:20:58,338] Trial 41 finished with value: 0.18222247447242906 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 287, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9487776860553198, 'min_weight_fraction_leaf': 0.0012764688125286236}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18083474896839194
Fold 2 IBS: 0.20655297055486127
Fold 3 IBS: 0.1560859878078812
Fold 4 IBS: 0.13735104264690487
Fold 5 IBS: 0.2318981646914065
[I 2024-04-18 05:21:20,088] Trial 42 finished with value: 0.18254458293388914 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 410, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9263396365475575, 'min_weight_fraction_leaf': 0.07533198780818874}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.179220247667936
Fold 2 IBS: 0.20803479971941155
Fold 3 IBS: 0.15642984958925052
Fold 4 IBS: 0.1381823380575358
Fold 5 IBS: 0.23098585177667733
[I 2024-04-18 05:21:33,244] Trial 43 finished with value: 0.18257061736216224 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8260902726928496, 'min_weight_fraction_leaf': 0.12086835806486591}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20295458389503712
Fold 2 IBS: 0.18760128987987226
Fold 3 IBS: 0.16259754916275176
Fold 4 IBS: 0.13943881701142766
Fold 5 IBS: 0.21929671791406735
[I 2024-04-18 05:21:50,335] Trial 44 finished with value: 0.18237779157263123 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 269, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.755115496265169, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.21196016007242774
Fold 2 IBS: 0.21737810285668177
Fold 3 IBS: 0.20221519268515586
Fold 4 IBS: 0.21985834792032022
Fold 5 IBS: 0.21707100228614096
[I 2024-04-18 05:21:58,129] Trial 45 finished with value: 0.21369656116414532 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 226, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5998350649536632, 'min_weight_fraction_leaf': 0.05464331917294846}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18076053104236317
Fold 2 IBS: 0.2172100382529918
Fold 3 IBS: 0.15472808053026357
Fold 4 IBS: 0.14511587127121353
Fold 5 IBS: 0.2339666086051307
[I 2024-04-18 05:22:08,073] Trial 46 finished with value: 0.18635622594039253 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8402810693773478, 'min_weight_fraction_leaf': 0.144161655351996}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18818806948138703
Fold 2 IBS: 0.18585276291120573
Fold 3 IBS: 0.16931029735325712
Fold 4 IBS: 0.16495818665843412
Fold 5 IBS: 0.21221551295471194
[I 2024-04-18 05:22:18,938] Trial 47 finished with value: 0.1841049658717992 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9302813606785956, 'min_weight_fraction_leaf': 0.08930568525499841}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18928681061078317
Fold 2 IBS: 0.19449353516562573
Fold 3 IBS: 0.15782262613968703
Fold 4 IBS: 0.13927270133528777
Fold 5 IBS: 0.22728509464662824
[I 2024-04-18 05:22:41,559] Trial 48 finished with value: 0.1816321535796024 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 374, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7058374194287877, 'min_weight_fraction_leaf': 0.021185992511726287}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20695865791961138
Fold 2 IBS: 0.18446003189676
Fold 3 IBS: 0.1637203264374506
Fold 4 IBS: 0.14167171912108306
Fold 5 IBS: 0.21852048251093703
[I 2024-04-18 05:23:07,953] Trial 49 finished with value: 0.18306624357716844 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6944137175640025, 'min_weight_fraction_leaf': 0.023748345961229673}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20395296501568036
Fold 2 IBS: 0.20356332435883023
Fold 3 IBS: 0.19198232817565247
Fold 4 IBS: 0.20503408115744123
Fold 5 IBS: 0.212977623601451
[I 2024-04-18 05:23:27,367] Trial 50 finished with value: 0.20350206446181107 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.1282263128781066}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1892478776386835
Fold 2 IBS: 0.1985691975751118
Fold 3 IBS: 0.1551366953595447
Fold 4 IBS: 0.13797047291334816
Fold 5 IBS: 0.2247976743236853
[I 2024-04-18 05:23:47,461] Trial 51 finished with value: 0.18114438356207468 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7991896596470566, 'min_weight_fraction_leaf': 0.020902281449632076}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18966875407315306
Fold 2 IBS: 0.20026668125593905
Fold 3 IBS: 0.1581902551783595
Fold 4 IBS: 0.1446898271378981
Fold 5 IBS: 0.22398935878186912
[I 2024-04-18 05:24:07,280] Trial 52 finished with value: 0.18336097528544376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7963262944115481, 'min_weight_fraction_leaf': 0.06178807863600248}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1808545696000534
Fold 2 IBS: 0.2092001659472061
Fold 3 IBS: 0.1569134957561024
Fold 4 IBS: 0.14354275776617909
Fold 5 IBS: 0.23138632547295945
[I 2024-04-18 05:24:24,750] Trial 53 finished with value: 0.1843794629085001 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6795691608327338, 'min_weight_fraction_leaf': 0.028449876548026755}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18963311160047724
Fold 2 IBS: 0.20900009168815242
Fold 3 IBS: 0.15966211681395587
Fold 4 IBS: 0.14477830095268193
Fold 5 IBS: 0.2227272285777302
[I 2024-04-18 05:24:46,059] Trial 54 finished with value: 0.18516016992659953 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8793032020733721, 'min_weight_fraction_leaf': 0.07859078488282405}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1844153405050917
Fold 2 IBS: 0.20329447035960194
Fold 3 IBS: 0.156445527494686
Fold 4 IBS: 0.1385632327057539
Fold 5 IBS: 0.2286479785748904
[I 2024-04-18 05:25:05,936] Trial 55 finished with value: 0.18227330992800478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615617181298988, 'min_weight_fraction_leaf': 0.0463333928046309}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21398416445233792
Fold 2 IBS: 0.22128642959017203
Fold 3 IBS: 0.20479170826088208
Fold 4 IBS: 0.22465474077969866
Fold 5 IBS: 0.21866500422066165
[I 2024-04-18 05:25:22,482] Trial 56 finished with value: 0.21667640946075045 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7048250986458913, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19154362908633138
Fold 2 IBS: 0.19025716940029977
Fold 3 IBS: 0.164641271809976
Fold 4 IBS: 0.1535983543533534
Fold 5 IBS: 0.21130984092669008
[I 2024-04-18 05:25:36,913] Trial 57 finished with value: 0.18227005311533012 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6509352527427404, 'min_weight_fraction_leaf': 0.01668177754116703}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1834614522490023
Fold 2 IBS: 0.20274762979546487
Fold 3 IBS: 0.1558259112444169
Fold 4 IBS: 0.13699785208498225
Fold 5 IBS: 0.227941946402463
[I 2024-04-18 05:25:58,920] Trial 58 finished with value: 0.18139495835526587 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 361, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8149000200033439, 'min_weight_fraction_leaf': 0.1073613839314761}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18264043127662102
Fold 2 IBS: 0.20563295068882514
Fold 3 IBS: 0.15774830297383735
Fold 4 IBS: 0.1409283130574975
Fold 5 IBS: 0.2302026151594693
[I 2024-04-18 05:26:25,603] Trial 59 finished with value: 0.18343052263125006 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 433, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.806842099370764, 'min_weight_fraction_leaf': 0.11194912742691053}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.1940353275621495
Fold 2 IBS: 0.19268012360689624
Fold 3 IBS: 0.18110607070067974
Fold 4 IBS: 0.18845548212963192
Fold 5 IBS: 0.2126254989546211
[I 2024-04-18 05:26:38,244] Trial 60 finished with value: 0.1937805005907957 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 305, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8575527275336559, 'min_weight_fraction_leaf': 0.18982981109623043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1881809892682945
Fold 2 IBS: 0.19390719781855054
Fold 3 IBS: 0.1588739037458674
Fold 4 IBS: 0.1367801254919651
Fold 5 IBS: 0.2266847482237021
[I 2024-04-18 05:26:59,622] Trial 61 finished with value: 0.18088539290967592 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615189086372551, 'min_weight_fraction_leaf': 0.04095649181576018}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1876754810451395
Fold 2 IBS: 0.19768374549602719
Fold 3 IBS: 0.15918815613876297
Fold 4 IBS: 0.13767028389195304
Fold 5 IBS: 0.22732368447379522
[I 2024-04-18 05:27:21,083] Trial 62 finished with value: 0.18190827020913558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 354, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7661278291112643, 'min_weight_fraction_leaf': 0.08934183246037483}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18158763535398614
Fold 2 IBS: 0.2058728330109782
Fold 3 IBS: 0.15634716717840097
Fold 4 IBS: 0.1393411349809578
Fold 5 IBS: 0.2305445348222664
[I 2024-04-18 05:27:43,850] Trial 63 finished with value: 0.18273866106931788 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8238233376692735, 'min_weight_fraction_leaf': 0.05246336243742043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17660125627972975
Fold 2 IBS: 0.19950632480062638
Fold 3 IBS: 0.16593947035609424
Fold 4 IBS: 0.1676045776632834
Fold 5 IBS: 0.2238259008995345
[I 2024-04-18 05:28:00,708] Trial 64 finished with value: 0.18669550599985366 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8942985122180038, 'min_weight_fraction_leaf': 0.3739424140604035}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17841559751185995
Fold 2 IBS: 0.2181576301923148
Fold 3 IBS: 0.15699607135742621
Fold 4 IBS: 0.14279995324086395
Fold 5 IBS: 0.23321351389303
[I 2024-04-18 05:28:17,405] Trial 65 finished with value: 0.185916553239099 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 321, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.157443472337933}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396919511710527
Fold 2 IBS: 0.22118312582133598
Fold 3 IBS: 0.20498660484161652
Fold 4 IBS: 0.22465182954726737
Fold 5 IBS: 0.218115813183982
[I 2024-04-18 05:28:30,773] Trial 66 finished with value: 0.21658131370226147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18873872659716473
Fold 2 IBS: 0.18791922078055107
Fold 3 IBS: 0.16453860462735764
Fold 4 IBS: 0.15207602931399142
Fold 5 IBS: 0.20920273391154215
[I 2024-04-18 05:28:45,810] Trial 67 finished with value: 0.18049506304612142 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7471014922297948, 'min_weight_fraction_leaf': 0.03879604091198421}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.18615572700917984
Fold 2 IBS: 0.1920922899342238
Fold 3 IBS: 0.1645126632956227
Fold 4 IBS: 0.15374635033745812
Fold 5 IBS: 0.21328354527729806
[I 2024-04-18 05:29:00,506] Trial 68 finished with value: 0.1819581151707565 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7411630198194591, 'min_weight_fraction_leaf': 0.0741944771835793}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.19221322343005157
Fold 2 IBS: 0.18747725704463866
Fold 3 IBS: 0.16271946974327306
Fold 4 IBS: 0.14893868190888562
Fold 5 IBS: 0.21053329237786875
[I 2024-04-18 05:29:14,526] Trial 69 finished with value: 0.18037638490094354 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873531668221723, 'min_weight_fraction_leaf': 0.03743740450038523}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19123449448406776
Fold 2 IBS: 0.18634187192427262
Fold 3 IBS: 0.16568962439316362
Fold 4 IBS: 0.14733219858236207
Fold 5 IBS: 0.2124042387639548
[I 2024-04-18 05:29:28,536] Trial 70 finished with value: 0.18060048562956416 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7884602797651743, 'min_weight_fraction_leaf': 0.03984902133772039}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19415415468436753
Fold 2 IBS: 0.1861415676999523
Fold 3 IBS: 0.16573890197473515
Fold 4 IBS: 0.14488999289270504
Fold 5 IBS: 0.2125204407894076
[I 2024-04-18 05:29:43,430] Trial 71 finished with value: 0.18068901160823353 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7819431269555398, 'min_weight_fraction_leaf': 0.03595825517448436}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.18984009710041735
Fold 2 IBS: 0.18778536549020883
Fold 3 IBS: 0.16555752286430367
Fold 4 IBS: 0.15132302702120518
Fold 5 IBS: 0.21187635057748866
[I 2024-04-18 05:30:00,042] Trial 72 finished with value: 0.18127647261072471 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 379, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7158237789595601, 'min_weight_fraction_leaf': 0.038892933150377174}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19217054361716007
Fold 2 IBS: 0.18605477551854072
Fold 3 IBS: 0.1657195529075007
Fold 4 IBS: 0.1499033271314654
Fold 5 IBS: 0.21296314297306798
[I 2024-04-18 05:30:14,929] Trial 73 finished with value: 0.18136226842954697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7776848187295278, 'min_weight_fraction_leaf': 0.041701970157165584}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.1919591413798442
Fold 2 IBS: 0.18680709380802085
Fold 3 IBS: 0.16611125142067912
Fold 4 IBS: 0.14880604710483025
Fold 5 IBS: 0.20779386416865475
[I 2024-04-18 05:30:28,727] Trial 74 finished with value: 0.18029547957640585 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 297, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7429251540613239, 'min_weight_fraction_leaf': 0.034122782806489685}. Best is trial 74 with value: 0.18029547957640585.

Fold 1 IBS: 0.20438643925191893
Fold 2 IBS: 0.1844312624795873
Fold 3 IBS: 0.17002168747641047
Fold 4 IBS: 0.14791525733420058
Fold 5 IBS: 0.21362624602582111
[I 2024-04-18 05:30:41,627] Trial 75 finished with value: 0.18407617851358768 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651148142523113, 'min_weight_fraction_leaf': 0.0005666053087619444}. Best is trial 74 with value: 0.18029547957640585.
Fold 1 IBS: 0.19306514020322818
Fold 2 IBS: 0.1842925536567217
Fold 3 IBS: 0.16281493341095712
Fold 4 IBS: 0.15026196851923793
Fold 5 IBS: 0.20907571723485416
[I 2024-04-18 05:30:52,874] Trial 76 finished with value: 0.1799020626049998 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6121072626884605, 'min_weight_fraction_leaf': 0.0375652827686181}. Best is trial 76 with value: 0.1799020626049998.
Fold 1 IBS: 0.19533191990808643
Fold 2 IBS: 0.18454077801628752
Fold 3 IBS: 0.16320484107502187
Fold 4 IBS: 0.14544314028091127
Fold 5 IBS: 0.2072692252418508
[I 2024-04-18 05:31:04,496] Trial 77 finished with value: 0.17915798090443158 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6024939881120506, 'min_weight_fraction_leaf': 0.03546615930788915}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18979383260600338
Fold 2 IBS: 0.18481018797624196
Fold 3 IBS: 0.16409936588525315
Fold 4 IBS: 0.1553259082203432
Fold 5 IBS: 0.21243305321372438
[I 2024-04-18 05:31:14,463] Trial 78 finished with value: 0.18129246958031323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.06309017855153265}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.1918516718483265
Fold 2 IBS: 0.18449081490872005
Fold 3 IBS: 0.1634428327969914
Fold 4 IBS: 0.14997364872576785
Fold 5 IBS: 0.20763662708758918
[I 2024-04-18 05:31:25,623] Trial 79 finished with value: 0.17947911907347897 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5944767216434486, 'min_weight_fraction_leaf': 0.03643432579651321}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19348005656430173
Fold 2 IBS: 0.18296399211241365
Fold 3 IBS: 0.16491035077279387
Fold 4 IBS: 0.1455645707584685
Fold 5 IBS: 0.21079082139142424
[I 2024-04-18 05:31:37,246] Trial 80 finished with value: 0.1795419583198804 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5738838339262928, 'min_weight_fraction_leaf': 0.01238447949116667}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19385166663658865
Fold 2 IBS: 0.1878440819583883
Fold 3 IBS: 0.165800948446184
Fold 4 IBS: 0.1476511958697635
Fold 5 IBS: 0.21025560153134265
[I 2024-04-18 05:31:48,467] Trial 81 finished with value: 0.1810806988884534 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5619354088357825, 'min_weight_fraction_leaf': 0.01565582556320865}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18524833693093437
Fold 2 IBS: 0.19165170252652822
Fold 3 IBS: 0.16392769525776144
Fold 4 IBS: 0.15846496418540476
Fold 5 IBS: 0.2094683241817906
[I 2024-04-18 05:31:58,084] Trial 82 finished with value: 0.1817522046164839 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 232, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4638072011147492, 'min_weight_fraction_leaf': 0.05201742843067371}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19237185503026552
Fold 2 IBS: 0.18676559841777626
Fold 3 IBS: 0.16407017518328942
Fold 4 IBS: 0.1449765914249507
Fold 5 IBS: 0.20892364253609055
[I 2024-04-18 05:32:11,059] Trial 83 finished with value: 0.1794215725184745 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5992998998564371, 'min_weight_fraction_leaf': 0.011892575602326625}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19394142912089907
Fold 2 IBS: 0.18287172537269059
Fold 3 IBS: 0.16363670208229797
Fold 4 IBS: 0.14366900591399753
Fold 5 IBS: 0.20892071259321834
[I 2024-04-18 05:32:22,570] Trial 84 finished with value: 0.1786079150166207 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 255, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5921978094028723, 'min_weight_fraction_leaf': 0.010779734440848038}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1934701576048722
Fold 2 IBS: 0.18356601291714442
Fold 3 IBS: 0.16350384856124178
Fold 4 IBS: 0.14362897455716736
Fold 5 IBS: 0.20935617313715904
[I 2024-04-18 05:32:33,238] Trial 85 finished with value: 0.17870503335551696 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 250, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.595683013252236, 'min_weight_fraction_leaf': 0.005599104949055786}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.191846570784011
Fold 2 IBS: 0.18680840183499514
Fold 3 IBS: 0.1640377893844091
Fold 4 IBS: 0.14812980552665286
Fold 5 IBS: 0.21175031324864774
[I 2024-04-18 05:32:43,872] Trial 86 finished with value: 0.18051457615574318 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 254, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5360572837412131, 'min_weight_fraction_leaf': 0.01185351158382457}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-18 05:32:55,462] Trial 87 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5878837691778286, 'min_weight_fraction_leaf': 0.008079079463688634}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1914457217244506
Fold 2 IBS: 0.18052086391051203
Fold 3 IBS: 0.16215789222067095
Fold 4 IBS: 0.15081933866613106
Fold 5 IBS: 0.20784710369879605
[I 2024-04-18 05:33:06,781] Trial 88 finished with value: 0.1785581840441121 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-18 05:33:18,376] Trial 89 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.585692212182858, 'min_weight_fraction_leaf': 0.0008838182441561699}. Best is trial 88 with value: 0.1785581840441121.

Fold 1 IBS: 0.19250257566167933
Fold 2 IBS: 0.18261531719008467
Fold 3 IBS: 0.16180974496548703
Fold 4 IBS: 0.14890218044290915
Fold 5 IBS: 0.2130135609453814
[I 2024-04-18 05:33:26,965] Trial 90 finished with value: 0.1797686758411083 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 202, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5935532822743834, 'min_weight_fraction_leaf': 0.007362099342399538}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19466401388017032
Fold 2 IBS: 0.18486336673650017
Fold 3 IBS: 0.16588446237479346
Fold 4 IBS: 0.1465134541216928
Fold 5 IBS: 0.21287370502296324
[I 2024-04-18 05:33:35,228] Trial 91 finished with value: 0.18095980042722398 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 197, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5826023797451899, 'min_weight_fraction_leaf': 0.00862038165347273}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19077050579200147
Fold 2 IBS: 0.18831329801859226
Fold 3 IBS: 0.16406961249991853
Fold 4 IBS: 0.14929003357858256
Fold 5 IBS: 0.21018706108863028
[I 2024-04-18 05:33:45,528] Trial 92 finished with value: 0.18052610219554502 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 252, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5070555008286651, 'min_weight_fraction_leaf': 0.009333694056201223}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.1942451581816268
Fold 2 IBS: 0.1830703742457603
Fold 3 IBS: 0.16097178413138724
Fold 4 IBS: 0.14654845241459755
Fold 5 IBS: 0.2121967833645088
[I 2024-04-18 05:33:54,756] Trial 93 finished with value: 0.17940651046757616 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 221, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5934768503177845, 'min_weight_fraction_leaf': 0.014878777313562812}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19736082973729024
Fold 2 IBS: 0.18309515782891686
Fold 3 IBS: 0.16366471911833752
Fold 4 IBS: 0.14526303100181923
Fold 5 IBS: 0.21417837651704477
[I 2024-04-18 05:34:02,125] Trial 94 finished with value: 0.18071242284068173 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 165, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6349033637819771, 'min_weight_fraction_leaf': 0.019343000331144743}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18578897328440416
Fold 2 IBS: 0.19239898124845878
Fold 3 IBS: 0.1616809082216946
Fold 4 IBS: 0.15362867068252217
Fold 5 IBS: 0.21229660365479858
[I 2024-04-18 05:34:11,482] Trial 95 finished with value: 0.18115882741837566 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 217, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5448232910672774, 'min_weight_fraction_leaf': 0.025610081517443647}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18377286728444794
Fold 2 IBS: 0.18906137730159184
Fold 3 IBS: 0.162592162450128
Fold 4 IBS: 0.15646349234384718
Fold 5 IBS: 0.21273640937582883
[I 2024-04-18 05:34:20,283] Trial 96 finished with value: 0.18092526175116874 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 200, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5166375602788441, 'min_weight_fraction_leaf': 0.01004295110119176}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19320716981789404
Fold 2 IBS: 0.1833817504678623
Fold 3 IBS: 0.16276222353530903
Fold 4 IBS: 0.15005917812838457
Fold 5 IBS: 0.21149567165602431
[I 2024-04-18 05:34:30,138] Trial 97 finished with value: 0.18018119872109484 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 230, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5810941412605699, 'min_weight_fraction_leaf': 0.028715470907523112}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19665218645247226
Fold 2 IBS: 0.18461786549962422
Fold 3 IBS: 0.16585865869273442
Fold 4 IBS: 0.14468826763530046
Fold 5 IBS: 0.20808627775303898
[I 2024-04-18 05:34:41,797] Trial 98 finished with value: 0.17998065120663406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.558904433592998, 'min_weight_fraction_leaf': 0.0007593749444425981}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19225977892006962
Fold 2 IBS: 0.19011577254533654
Fold 3 IBS: 0.1738613054687569
Fold 4 IBS: 0.1638041351036002
Fold 5 IBS: 0.2130479662700931
[I 2024-04-18 05:34:47,853] Trial 99 finished with value: 0.18661779166157128 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4718103481231686, 'min_weight_fraction_leaf': 0.013594026171513878}. Best is trial 88 with value: 0.1785581840441121.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.1785581840441121], datetime_start=datetime.datetime(2024, 4, 18, 5, 32, 55, 486936), datetime_complete=datetime.datetime(2024, 4, 18, 5, 33, 6, 780797), params={'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.1785581840441121

In [60]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.886
train_ibs:  0.179

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=9, max_features=None, max_leaf_nodes=14,
                   max_samples=0.965941994806725, min_samples_split=7,
                   min_weight_fraction_leaf=0.017267854864073284,
                   n_estimators=336, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.662

ExtraSurvivalTrees(max_depth=9, max_features=0.1, max_leaf_nodes=20,
                   max_samples=0.5945245081220258, min_samples_leaf=4,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.006841645987133443,
                   n_estimators=279, oob_score=True, random_state=123,
                   warm_start=True)

IBS: 0.2

In [64]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 05:34:57,954] A new study created in memory with name: no-name-20fd8a33-03ad-4893-b8ff-07651b076ae8

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:36:19,958] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:36:58,996] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:37:43,727] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:39:21,146] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:39:56,844] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:40:06,132] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:41:05,519] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:41:20,502] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:41:22,511] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 05:44:24,864] Trial 9 finished with value: 0.7375077219334873 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 05:49:04,642] Trial 10 finished with value: 0.6769991466942861 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:54:09,190] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.715962441314554
[I 2024-04-18 05:58:27,990] Trial 12 finished with value: 0.7180894810070741 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:00:29,139] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:03:19,073] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:06:24,265] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:08:02,239] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:11:29,035] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:16:21,080] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:16:36,459] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:18:34,092] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 06:22:35,933] Trial 21 finished with value: 0.6596743990023763 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7447257383966245
Fold 5 C-index: 0.6830985915492958
[I 2024-04-18 06:26:38,133] Trial 22 finished with value: 0.7577518089481858 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:29:47,097] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:33:19,145] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:35:14,126] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 06:38:28,768] Trial 26 finished with value: 0.5295120936590003 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:41:42,716] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:44:25,599] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:46:24,248] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:48:52,643] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 06:53:28,579] Trial 31 finished with value: 0.6975838362663174 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:58:03,212] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9113568740147856, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.1444594228310892, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 1.6183832787391992, 'min_weight_fraction_leaf': 0.4304319218036696, 'max_features': 'auto', 'min_impurity_decrease': 1.0277484189219154e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:01:48,365] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9728428556912192, 'learning_rate': 0.015742740923125064, 'dropout_rate': 0.30020186346124766, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.4958404435609285, 'max_features': 'auto', 'min_impurity_decrease': 2.2786499479002052e-07, 'validation_fraction': 0.8344453462672722, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:04:30,482] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.8496036715186095, 'learning_rate': 0.009253864701923034, 'dropout_rate': 0.22658656718653286, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.641857272630336, 'min_weight_fraction_leaf': 0.43629024868714544, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9168532630851701, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:05:12,340] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6806458891075314, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.4078621112435248, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3706867126320781, 'max_features': None, 'min_impurity_decrease': 7.8587698841458e-07, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:08:55,055] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.9551502281749775, 'learning_rate': 0.026078126474550274, 'dropout_rate': 0.34789169882120996, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.40891402270131877, 'min_weight_fraction_leaf': 0.2325827619040188, 'max_features': 'auto', 'min_impurity_decrease': 7.145093229830912e-06, 'validation_fraction': 0.6747809687204889, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:09:10,650] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7371581418455209, 'learning_rate': 0.0145417341576766, 'dropout_rate': 0.16172130996739253, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.3174537146690439, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.9548743578197549, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:10:15,169] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.8063221166350547, 'learning_rate': 0.006424315075939495, 'dropout_rate': 0.7673236646699829, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 9.162989248724866, 'min_weight_fraction_leaf': 0.14601082900734919, 'max_features': 'auto', 'min_impurity_decrease': 1.1529415174162498e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:12:59,082] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.8852748015168422, 'learning_rate': 0.02975783779377629, 'dropout_rate': 0.2673592786040255, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1216454788806307, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 8.588272604740831e-07, 'validation_fraction': 0.7628102853958754, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:15:16,217] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5809866593286652, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.20816102573612866, 'n_estimators': 353, 'criterion': 'squared_error', 'ccp_alpha': 3.7898554763179284, 'min_weight_fraction_leaf': 0.4711996214427754, 'max_features': 'auto', 'min_impurity_decrease': 2.3584088371991464e-07, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 07:15:17,023] Trial 41 finished with value: 0.6152707311185872 and parameters: {'subsample': 0.9964498482283193, 'learning_rate': 0.004158109708816752, 'dropout_rate': 0.13644226542045526, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4011310798872364, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.9993318631652353, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:19:40,162] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.10858843727097561, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.415120560514267, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:21:15,998] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.919916216831853, 'learning_rate': 0.0016321845585985228, 'dropout_rate': 0.16429624388711278, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.471921644995546, 'min_weight_fraction_leaf': 0.3704175909956657, 'max_features': 'auto', 'min_impurity_decrease': 0.0009050261380449993, 'validation_fraction': 0.8779568222622545, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:23:43,571] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.015327765728784649, 'dropout_rate': 0.6859431566383477, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.2679892492803537, 'min_weight_fraction_leaf': 0.2706416993480579, 'max_features': 'auto', 'min_impurity_decrease': 8.738793222106795e-07, 'validation_fraction': 0.9744834265061879, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.6126760563380281
[I 2024-04-18 07:26:24,356] Trial 45 finished with value: 0.7169525524273146 and parameters: {'subsample': 0.8612793275132423, 'learning_rate': 0.008591203396202965, 'dropout_rate': 0.20237082649972205, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.09266970930573763, 'min_weight_fraction_leaf': 0.4478112124993417, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.798828420958444, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:26:44,446] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8576868620948644, 'learning_rate': 0.021769927230194788, 'dropout_rate': 0.9694253886674298, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.45430295635160706, 'max_features': 0.1, 'min_impurity_decrease': 2.0131584568637675e-06, 'validation_fraction': 0.7976029227783121, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:27:32,741] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7056873961179977, 'learning_rate': 0.00929853233926034, 'dropout_rate': 0.3140351257259953, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.49464896810642006, 'max_features': 0.1, 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.6179698437276481, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:30:19,076] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7837245323509484, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.21043558082214228, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.4617743734350054, 'min_weight_fraction_leaf': 0.45246089314517907, 'max_features': 0.1, 'min_impurity_decrease': 4.221379974644956e-07, 'validation_fraction': 0.863214331971344, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:31:43,956] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.6507081753968225, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.26780621294484797, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 1.378218906104398, 'min_weight_fraction_leaf': 0.2916489694540698, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6845184717076465, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:34:18,598] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.03353370774351387, 'dropout_rate': 0.3787195779305788, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.7561621193902213, 'min_weight_fraction_leaf': 0.47814765735031256, 'max_features': 0.1, 'min_impurity_decrease': 1.6961878462023105e-07, 'validation_fraction': 0.8310153288008191, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6244131455399061
[I 2024-04-18 07:38:30,075] Trial 51 finished with value: 0.6982448681347772 and parameters: {'subsample': 0.9590755303360702, 'learning_rate': 0.001263628446733103, 'dropout_rate': 0.13293847894616523, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 07:42:32,441] Trial 52 finished with value: 0.7007875648598147 and parameters: {'subsample': 0.9309483691931049, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.1309992574789837, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.036615235505588, 'min_weight_fraction_leaf': 0.4052806656624778, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8184597843569143e-07, 'validation_fraction': 0.8992446934973449, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:45:38,335] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9119792149240027, 'learning_rate': 0.0011619738930768678, 'dropout_rate': 0.12019527221159815, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.33436888398209985, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0912509934146174e-06, 'validation_fraction': 0.7204767494493249, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:46:40,809] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9422391559777883, 'learning_rate': 0.006469543850280348, 'dropout_rate': 0.8266353856620614, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.46449392886564433, 'min_weight_fraction_leaf': 0.20818644825744925, 'max_features': 'sqrt', 'min_impurity_decrease': 3.17346833824979e-07, 'validation_fraction': 0.8741639290304148, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:49:33,231] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8715328822130523, 'learning_rate': 0.011790338191706525, 'dropout_rate': 0.23926982708415356, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.4008945876330496, 'min_weight_fraction_leaf': 0.44051010658711054, 'max_features': 'sqrt', 'min_impurity_decrease': 5.615119149330365e-07, 'validation_fraction': 0.7887577239921508, 'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:53:01,149] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8015434219726096, 'learning_rate': 0.04061736247319854, 'dropout_rate': 0.1937709311352404, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.037591557618962, 'min_weight_fraction_leaf': 0.41307911755286036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.854323715915516e-06, 'validation_fraction': 0.907633472782051, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 07:54:18,611] Trial 57 finished with value: 0.694941105261048 and parameters: {'subsample': 0.47167111494444647, 'learning_rate': 0.018997287630538016, 'dropout_rate': 0.5891903890315894, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.007297661499282945, 'min_weight_fraction_leaf': 0.37949114392069716, 'max_features': 'sqrt', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.5599065409082953, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:57:44,113] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8972461919118405, 'learning_rate': 0.09671804411942064, 'dropout_rate': 0.10627978332234836, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.7590888481670788, 'min_weight_fraction_leaf': 0.25730821949204663, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9487716255435797, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:00:25,945] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.8358264770513102, 'learning_rate': 0.022823901724539096, 'dropout_rate': 0.28631447973846014, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.429314535364776, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': None, 'min_impurity_decrease': 5.131055724938468e-07, 'validation_fraction': 0.8437837761372522, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:01:41,331] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.0056069075336912105, 'dropout_rate': 0.3357871821335161, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 2.523299286625464, 'min_weight_fraction_leaf': 0.339521597129798, 'max_features': 'sqrt', 'min_impurity_decrease': 2.9638541699067996e-07, 'validation_fraction': 0.6410967521884806, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:03:31,775] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.1843386992247676, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.22729228144381666, 'min_weight_fraction_leaf': 0.4037400789999268, 'max_features': 1, 'min_impurity_decrease': 1.310082490250357e-07, 'validation_fraction': 0.9622895789424137, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 08:05:15,800] Trial 62 finished with value: 0.7272773109470696 and parameters: {'subsample': 0.9756177414915416, 'learning_rate': 0.00487963758524286, 'dropout_rate': 0.14510716910347804, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.023608499803350655, 'min_weight_fraction_leaf': 0.22961838496572504, 'max_features': 0.1, 'min_impurity_decrease': 1.6297128321880156e-07, 'validation_fraction': 0.8969787245486088, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:06:56,551] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.9288654416933328, 'learning_rate': 0.013829624766460978, 'dropout_rate': 0.13653478929605453, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.7247405887368557, 'min_weight_fraction_leaf': 0.22479730957902153, 'max_features': 0.1, 'min_impurity_decrease': 5.575423017349267e-07, 'validation_fraction': 0.8936351824952593, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:08:28,492] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.3944303299889498, 'learning_rate': 0.005756823204408979, 'dropout_rate': 0.2327252655551748, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.30460031424817835, 'min_weight_fraction_leaf': 0.1885535376775951, 'max_features': 0.1, 'min_impurity_decrease': 3.354219995894836e-07, 'validation_fraction': 0.9295137020256315, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 08:10:11,733] Trial 65 finished with value: 0.7220969706866847 and parameters: {'subsample': 0.8628229894737177, 'learning_rate': 0.008827661920605995, 'dropout_rate': 0.19214391420812213, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.002774143765696062, 'min_weight_fraction_leaf': 0.19849959041931706, 'max_features': 0.1, 'min_impurity_decrease': 2.5741032571081618e-06, 'validation_fraction': 0.81580153800389, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:12:14,668] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.7758851752296808, 'learning_rate': 0.009751888770788269, 'dropout_rate': 0.19122550095328222, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.898614500640199, 'min_weight_fraction_leaf': 0.15180913487925937, 'max_features': 0.1, 'min_impurity_decrease': 2.693782393576339e-06, 'validation_fraction': 0.8022828972461258, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:13:50,894] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8737277188190908, 'learning_rate': 0.017575803118928604, 'dropout_rate': 0.24650681062055632, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.184288941522344, 'min_weight_fraction_leaf': 0.20306006951316619, 'max_features': 0.1, 'min_impurity_decrease': 1.2046523007672827e-06, 'validation_fraction': 0.7485906145710193, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:15:13,001] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.819932305524277, 'learning_rate': 0.09136620662883123, 'dropout_rate': 0.21544296697082643, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5667792373547914, 'min_weight_fraction_leaf': 0.24594914856187006, 'max_features': 0.1, 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.8633504402260139, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:16:24,490] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5360295416604122, 'learning_rate': 0.026072943824179864, 'dropout_rate': 0.15995252701068877, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 6.315803860540386, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 0.1, 'min_impurity_decrease': 4.676506095993518e-06, 'validation_fraction': 0.8221337964376644, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:17:35,898] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.7391884515801697, 'learning_rate': 0.0131539926632262, 'dropout_rate': 0.4370458221877003, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.3030856819564138, 'min_weight_fraction_leaf': 0.04227011624339991, 'max_features': 'log2', 'min_impurity_decrease': 4.094308088527539e-05, 'validation_fraction': 0.7311035029930464, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:19:38,448] Trial 71 finished with value: 0.7057455222887223 and parameters: {'subsample': 0.8958059912610585, 'learning_rate': 0.00404243977738313, 'dropout_rate': 0.13685925262610546, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.27174017051065336, 'max_features': 0.1, 'min_impurity_decrease': 1.6903767334797878e-07, 'validation_fraction': 0.893021390165449, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 08:21:14,754] Trial 72 finished with value: 0.7255383448051743 and parameters: {'subsample': 0.9033994568982797, 'learning_rate': 0.008576558002904872, 'dropout_rate': 0.1796601786158867, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.0049265702435675185, 'min_weight_fraction_leaf': 0.2698684133835347, 'max_features': 0.1, 'min_impurity_decrease': 2.520131654025212e-07, 'validation_fraction': 0.9039347234285049, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:22:39,352] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9030072931863139, 'learning_rate': 0.00868732713600762, 'dropout_rate': 0.2744775845272275, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8157217970730618, 'min_weight_fraction_leaf': 0.2706425923382264, 'max_features': 0.1, 'min_impurity_decrease': 1.5060083036338323e-07, 'validation_fraction': 0.8429645916964783, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:22:47,260] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8551098377950185, 'learning_rate': 0.017852326043636436, 'dropout_rate': 0.18670893655691517, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.3282745678695592, 'min_weight_fraction_leaf': 0.2216310042184134, 'max_features': 0.1, 'min_impurity_decrease': 0.00020700246413734948, 'validation_fraction': 0.7700706578571286, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:23:52,210] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.8885953564344566, 'learning_rate': 0.003923453373901735, 'dropout_rate': 0.25497810906198315, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 4.774324490228468, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 1.0309115243736615e-07, 'validation_fraction': 0.9298417275031959, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:25:17,220] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9671878335188347, 'learning_rate': 0.010137963140872869, 'dropout_rate': 0.1720967582787876, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.6017992226500892, 'min_weight_fraction_leaf': 0.2343670795832099, 'max_features': 0.1, 'min_impurity_decrease': 4.1389285578024635e-07, 'validation_fraction': 0.4666209889121972, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:26:35,087] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7817997136792754, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.21878505744240392, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 2.226175878213271, 'min_weight_fraction_leaf': 0.11673456101680679, 'max_features': 0.1, 'min_impurity_decrease': 2.278338706941225e-07, 'validation_fraction': 0.8870735397490029, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:27:29,405] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.85971117635256, 'learning_rate': 0.020702169760542934, 'dropout_rate': 0.10184607865359452, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 1.1613144933398152, 'min_weight_fraction_leaf': 0.28827493961902323, 'max_features': 0.1, 'min_impurity_decrease': 1.0554012317973208e-06, 'validation_fraction': 0.7800831726807022, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:28:24,634] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7085303006120247, 'learning_rate': 0.007203573027836778, 'dropout_rate': 0.3309372439616984, 'n_estimators': 405, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7098465234455584, 'min_weight_fraction_leaf': 0.16909333970802584, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9874471393466349, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:29:45,519] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.43152853207212877, 'learning_rate': 0.012535821130981227, 'dropout_rate': 0.28829477813771426, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.29587735180979763, 'min_weight_fraction_leaf': 0.1932252614573767, 'max_features': None, 'min_impurity_decrease': 2.607076310858583e-06, 'validation_fraction': 0.2486636150723724, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 08:31:21,235] Trial 81 finished with value: 0.7232266055095437 and parameters: {'subsample': 0.9310152909641193, 'learning_rate': 0.004901464536992707, 'dropout_rate': 0.14649845200705908, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.0401224705257143, 'min_weight_fraction_leaf': 0.2140884860716641, 'max_features': 0.1, 'min_impurity_decrease': 3.294643059864092e-07, 'validation_fraction': 0.9215349695607397, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:32:56,224] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9804673759889536, 'learning_rate': 0.003705242334357205, 'dropout_rate': 0.15221754469070822, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.6905373562188476, 'min_weight_fraction_leaf': 0.214345215244296, 'max_features': 0.1, 'min_impurity_decrease': 1.535249456479472e-07, 'validation_fraction': 0.9202835513583518, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:34:16,921] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9176538987097111, 'learning_rate': 0.0076523566881114835, 'dropout_rate': 0.22968230522988387, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.20240849843431086, 'min_weight_fraction_leaf': 0.2383259127009152, 'max_features': 0.1, 'min_impurity_decrease': 4.399657878596901e-07, 'validation_fraction': 0.9767059181287342, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:35:31,575] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8255635604133957, 'learning_rate': 0.0036977258275946636, 'dropout_rate': 0.20402072590631012, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5198465206932167, 'min_weight_fraction_leaf': 0.15653086076945935, 'max_features': 0.1, 'min_impurity_decrease': 7.178610075896741e-07, 'validation_fraction': 0.8482804900297096, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7745098039215687

Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:37:26,938] Trial 85 finished with value: 0.7189891256993891 and parameters: {'subsample': 0.8918331608196582, 'learning_rate': 0.015605784733698558, 'dropout_rate': 0.14750634204389826, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.30357930249568654, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9997678373401905, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:39:05,105] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10092948452566086, 'learning_rate': 0.01532810679048379, 'dropout_rate': 0.17099114695337342, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.876197483648788, 'min_weight_fraction_leaf': 0.3015328988188304, 'max_features': 'auto', 'min_impurity_decrease': 1.6482137590771691e-06, 'validation_fraction': 0.9342270075718234, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:39:38,514] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5929593460046293, 'learning_rate': 0.016822571784752067, 'dropout_rate': 0.19867600397015794, 'n_estimators': 263, 'criterion': 'squared_error', 'ccp_alpha': 0.23496207633721847, 'min_weight_fraction_leaf': 0.24832976306734728, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.9659857207632909, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:41:13,634] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9310702721088772, 'learning_rate': 0.009959700506785971, 'dropout_rate': 0.2555430411709441, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 8.088457238075051, 'min_weight_fraction_leaf': 0.22631747365745694, 'max_features': 'auto', 'min_impurity_decrease': 2.710852350800199e-07, 'validation_fraction': 0.7056533437856146, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:42:49,517] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.975612460964084, 'learning_rate': 0.012850444381300855, 'dropout_rate': 0.11846749927359909, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 1.425464889112629, 'min_weight_fraction_leaf': 0.1784633449883898, 'max_features': 'auto', 'min_impurity_decrease': 5.921522228604161e-07, 'validation_fraction': 0.9996319172531741, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:44:25,960] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.34045768877643007, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.15210696274519644, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9372956395735829, 'min_weight_fraction_leaf': 0.13514216761654674, 'max_features': 1, 'min_impurity_decrease': 3.412090206574042e-07, 'validation_fraction': 0.5798720476990769, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 08:46:12,746] Trial 91 finished with value: 0.7299130919568267 and parameters: {'subsample': 0.8979069506313946, 'learning_rate': 0.008101193305888026, 'dropout_rate': 0.14427259297048306, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.05667376231617895, 'min_weight_fraction_leaf': 0.2662831727524566, 'max_features': 'auto', 'min_impurity_decrease': 2.2001283077718922e-07, 'validation_fraction': 0.8878992829265958, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:47:50,879] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8025284770642525, 'learning_rate': 0.008198746448650564, 'dropout_rate': 0.17658024519117366, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4944517626406935, 'min_weight_fraction_leaf': 0.281932786781083, 'max_features': 'auto', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.8240961218884286, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:49:33,374] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.866078324832748, 'learning_rate': 0.011107826666625974, 'dropout_rate': 0.15001558634639325, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.20618034747646607, 'min_weight_fraction_leaf': 0.26022589277342434, 'max_features': 'auto', 'min_impurity_decrease': 1.2653383309827397e-07, 'validation_fraction': 0.8676712222376753, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:50:55,014] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.8418316701841008, 'learning_rate': 0.006152062924759251, 'dropout_rate': 0.2291019421217302, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.6324588657889718, 'min_weight_fraction_leaf': 0.4804568203093911, 'max_features': 'auto', 'min_impurity_decrease': 9.38303925215205e-07, 'validation_fraction': 0.9086059943821162, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:52:46,957] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.87747934958027, 'learning_rate': 0.0012139304758565887, 'dropout_rate': 0.12498646666495616, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.3715046104772777, 'min_weight_fraction_leaf': 0.208961689017974, 'max_features': 'auto', 'min_impurity_decrease': 2.382313770891545e-07, 'validation_fraction': 0.3818872933371859, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6446078431372549
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 08:54:24,558] Trial 96 finished with value: 0.696510102322911 and parameters: {'subsample': 0.94218553177403, 'learning_rate': 0.020033817173644677, 'dropout_rate': 0.3058190228136884, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.030434277972844224, 'min_weight_fraction_leaf': 0.19188954018236168, 'max_features': 'auto', 'min_impurity_decrease': 3.679493950049724e-07, 'validation_fraction': 0.9459755275340084, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:54:45,589] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.9071107405480169, 'learning_rate': 0.013884656270412483, 'dropout_rate': 0.8479620532477699, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 1.069614033248094, 'min_weight_fraction_leaf': 0.32699666489884094, 'max_features': 'log2', 'min_impurity_decrease': 5.25058355616678e-07, 'validation_fraction': 0.8836386308311208, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:56:00,732] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.9531544060001753, 'learning_rate': 0.008555926298082998, 'dropout_rate': 0.20235805532585233, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 0.7543795415309705, 'min_weight_fraction_leaf': 0.30398885673134707, 'max_features': 'auto', 'min_impurity_decrease': 1.0466185221530527e-07, 'validation_fraction': 0.9694358139640935, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.5654008438818565

[I 2024-04-18 08:57:31,735] A new study created in memory with name: no-name-0ec6b29c-643e-4681-9f90-0c7ee12cb2eb

Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 08:57:31,655] Trial 99 finished with value: 0.6663823683373736 and parameters: {'subsample': 0.9976459171012907, 'learning_rate': 0.024328086787534252, 'dropout_rate': 0.36361374787631456, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.004395791161995251, 'min_weight_fraction_leaf': 0.353628504086837, 'max_features': 'auto', 'min_impurity_decrease': 1.5812750205075571e-07, 'validation_fraction': 0.8128875839784486, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.


* Best trial for C-index:
 FrozenTrial(number=22, state=TrialState.COMPLETE, values=[0.7577518089481858], datetime_start=datetime.datetime(2024, 4, 18, 6, 22, 35, 939249), datetime_complete=datetime.datetime(2024, 4, 18, 6, 26, 38, 132513), params={'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=22, value=None)


* Best Score for C-index:
 0.7577518089481858

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:58:03,216] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:58:18,033] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:58:35,200] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:59:16,247] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:59:30,674] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:59:34,660] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:59:57,070] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:00:03,301] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:00:04,355] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21278960135067226
Fold 2 IBS: 0.22075148425471117
Fold 3 IBS: 0.20356154640252785
Fold 4 IBS: 0.22366437810992945
Fold 5 IBS: 0.2175108694850557
[I 2024-04-18 09:01:12,964] Trial 9 finished with value: 0.2156555759205793 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21360363678959007
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.20421474792063551
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21803455300047256
[I 2024-04-18 09:02:57,779] Trial 10 finished with value: 0.21637936117854983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:04:53,099] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2138334609344149
Fold 2 IBS: 0.22151322501680365
Fold 3 IBS: 0.20446062477316612
Fold 4 IBS: 0.2246559027106978
Fold 5 IBS: 0.2180563962052136
[I 2024-04-18 09:06:34,690] Trial 12 finished with value: 0.2165039219280592 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 09:07:16,347] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:08:50,716] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:09:55,748] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:10:32,679] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:11:58,822] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:12:46,323] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:12:55,800] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:14:13,613] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21367586546116044
Fold 2 IBS: 0.22153601357644734
Fold 3 IBS: 0.20438542163118117
Fold 4 IBS: 0.22463472155111044
Fold 5 IBS: 0.2180079529732588
[I 2024-04-18 09:15:36,573] Trial 21 finished with value: 0.21644799503863163 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21300133805358812
Fold 2 IBS: 0.22092783506924327

Fold 3 IBS: 0.20392740109457028
Fold 4 IBS: 0.22400556985244785
Fold 5 IBS: 0.2175786554209321
[I 2024-04-18 09:16:50,868] Trial 22 finished with value: 0.2158881598981563 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:17:57,939] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:18:39,761] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:19:18,488] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:19:52,137] Trial 26 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:19:56,875] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:20:07,279] Trial 28 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:20:49,101] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:21:54,097] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2132673053926921
Fold 2 IBS: 0.22138150435074114
Fold 3 IBS: 0.20416936232206076
Fold 4 IBS: 0.224409146213765
Fold 5 IBS: 0.2177869543616682
[I 2024-04-18 09:23:00,873] Trial 31 finished with value: 0.2162028545281854 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21250908818560812
Fold 2 IBS: 0.22112061913596615
Fold 3 IBS: 0.20357254804690844
Fold 4 IBS: 0.22431509484129145
Fold 5 IBS: 0.21754679795245008
[I 2024-04-18 09:24:14,204] Trial 32 finished with value: 0.2158128296324448 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:24:59,870] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:25:50,663] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:26:07,637] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:27:02,176] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:27:08,425] Trial 37 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:27:29,893] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:28:04,065] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:28:46,147] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21343873621972445
Fold 2 IBS: 0.22049446029877326
Fold 3 IBS: 0.20337828484272225
Fold 4 IBS: 0.22303639527565466
Fold 5 IBS: 0.21729676723732877
[I 2024-04-18 09:29:50,124] Trial 41 finished with value: 0.21552892877484067 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.2131030184453258
Fold 2 IBS: 0.22050327285628324
Fold 3 IBS: 0.2033673824751969
Fold 4 IBS: 0.22363217726195525
Fold 5 IBS: 0.21724767258898225
[I 2024-04-18 09:30:51,863] Trial 42 finished with value: 0.2155707047255487 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:32:03,007] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:33:00,917] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:33:16,689] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21368294038898764
Fold 2 IBS: 0.22138561655450684
Fold 3 IBS: 0.2042880559361189
Fold 4 IBS: 0.22453830345531042
Fold 5 IBS: 0.21794750132893198
[I 2024-04-18 09:34:01,683] Trial 46 finished with value: 0.21636848353277113 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:34:26,774] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:34:27,066] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:34:38,750] Trial 49 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 09:35:10,383] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21305615407340403
Fold 2 IBS: 0.22124588111973337
Fold 3 IBS: 0.20390302508767316
Fold 4 IBS: 0.22446365006496424
Fold 5 IBS: 0.21777819332443837
[I 2024-04-18 09:36:02,760] Trial 51 finished with value: 0.21608938073404263 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21352169783850614
Fold 2 IBS: 0.22120550026908148
Fold 3 IBS: 0.20396949286236565
Fold 4 IBS: 0.22452441731877534
Fold 5 IBS: 0.2178146994022686
[I 2024-04-18 09:36:55,737] Trial 52 finished with value: 0.21620716153819944 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:37:44,192] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:38:33,109] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:39:12,999] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:39:43,404] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:40:17,797] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:40:57,738] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:41:28,068] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:41:53,513] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:42:47,024] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9319260511303565, 'learning_rate': 0.006981217524957076, 'dropout_rate': 0.2694290399109642, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.2266262530125842, 'min_weight_fraction_leaf': 0.2262208916321135, 'max_features': 'auto', 'min_impurity_decrease': 6.393438969585487e-06, 'validation_fraction': 0.968342815685117, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21261827944826023
Fold 2 IBS: 0.2212835131478303
Fold 3 IBS: 0.20384635335083123
Fold 4 IBS: 0.22428599240586905
Fold 5 IBS: 0.21722666261844198
[I 2024-04-18 09:43:37,309] Trial 62 finished with value: 0.21585216019424655 and parameters: {'subsample': 0.9972198040262032, 'learning_rate': 0.008659221224759001, 'dropout_rate': 0.18470289302046516, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.022476866600004634, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 3.745982455886227e-06, 'validation_fraction': 0.9275220875852723, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:43:54,154] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9899309662352432, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:44:39,396] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9658825052862857, 'learning_rate': 0.010845363858236992, 'dropout_rate': 0.13571080979315037, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.3681339382709387, 'min_weight_fraction_leaf': 0.15534331606940482, 'max_features': 'log2', 'min_impurity_decrease': 8.60046486145071e-06, 'validation_fraction': 0.9205869937759958, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21299720012323184
Fold 2 IBS: 0.22115174939969934
Fold 3 IBS: 0.2038040121811597
Fold 4 IBS: 0.2242157275656328
Fold 5 IBS: 0.21734625390047366
[I 2024-04-18 09:45:33,600] Trial 65 finished with value: 0.21590298863403948 and parameters: {'subsample': 0.9661607708539444, 'learning_rate': 0.008868026173365113, 'dropout_rate': 0.17835638219464384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.002725826040487267, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:46:15,986] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9998769833869746, 'learning_rate': 0.003967598379054899, 'dropout_rate': 0.17654958266634313, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.8981368148483696, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'auto', 'min_impurity_decrease': 7.140027633149786e-05, 'validation_fraction': 0.6362228335648394, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:46:53,008] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8945386029541793, 'learning_rate': 0.01494075298406419, 'dropout_rate': 0.209071801122636, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1837261226658302, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5552258602982892e-05, 'validation_fraction': 0.7259068897097584, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-18 09:47:54,978] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.843502945752621, 'learning_rate': 0.02075147594960792, 'dropout_rate': 0.16252263519114862, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.057901034918407895, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.6846740503948187, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:48:38,013] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.01037165919107231, 'dropout_rate': 0.19004731427008625, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.34303232955200197, 'min_weight_fraction_leaf': 0.3579731281150166, 'max_features': 'auto', 'min_impurity_decrease': 0.00014344627836102727, 'validation_fraction': 0.7769648880006281, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:49:28,557] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6499145948799803, 'learning_rate': 0.008667614598934925, 'dropout_rate': 0.2379061541841675, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.6762661413605899, 'min_weight_fraction_leaf': 0.2053436289550881, 'max_features': None, 'min_impurity_decrease': 2.7112245092072337e-05, 'validation_fraction': 0.5272974695233066, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21365379061917414
Fold 2 IBS: 0.22138264547298084
Fold 3 IBS: 0.2043021502572646
Fold 4 IBS: 0.22456249898531583
Fold 5 IBS: 0.2178752609515109
[I 2024-04-18 09:50:22,069] Trial 71 finished with value: 0.21635526925724924 and parameters: {'subsample': 0.9554665295189709, 'learning_rate': 0.004772306432110387, 'dropout_rate': 0.30773217080297294, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.019537053946387287, 'max_features': 'auto', 'min_impurity_decrease': 3.603782675882374e-06, 'validation_fraction': 0.8818766703918308, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21009179135163386
Fold 2 IBS: 0.21999119714274143
Fold 3 IBS: 0.2019997974702572
Fold 4 IBS: 0.22308677215739936
Fold 5 IBS: 0.2164934631302429
[I 2024-04-18 09:51:18,767] Trial 72 finished with value: 0.21433260425045497 and parameters: {'subsample': 0.9233416329717381, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.12211037740366137, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004815836437462028, 'min_weight_fraction_leaf': 0.2452551786385524, 'max_features': 'auto', 'min_impurity_decrease': 1.5300590715832769e-06, 'validation_fraction': 0.974284387349558, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:51:30,025] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.916509573532907, 'learning_rate': 0.01366625897147706, 'dropout_rate': 0.10211108319082117, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.35137810274202946, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'auto', 'min_impurity_decrease': 5.253021283264037e-07, 'validation_fraction': 0.9862680394354211, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:52:18,712] Trial 74 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.98093897605085, 'learning_rate': 0.01711555655405715, 'dropout_rate': 0.13243922080536136, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.7083433911466146, 'min_weight_fraction_leaf': 0.24361782259873882, 'max_features': 'auto', 'min_impurity_decrease': 1.0928587879200682e-06, 'validation_fraction': 0.8125486143795312, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.20063679042123642
Fold 2 IBS: 0.2148812250636474
Fold 3 IBS: 0.19380589049848737
Fold 4 IBS: 0.21616853881208678
Fold 5 IBS: 0.21227770638433743
[I 2024-04-18 09:52:59,591] Trial 75 finished with value: 0.20755403023595909 and parameters: {'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:53:38,455] Trial 76 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8704877196117842, 'learning_rate': 0.0916936247639216, 'dropout_rate': 0.13042337037884444, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2722270315020332, 'max_features': 'auto', 'min_impurity_decrease': 1.6370541352867706e-06, 'validation_fraction': 0.9218092808039015, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:54:08,984] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7865219593038091, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.25073094184082545, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.2846220433570537, 'min_weight_fraction_leaf': 0.32348748582358233, 'max_features': 1, 'min_impurity_decrease': 2.1196884133822008e-06, 'validation_fraction': 0.854746843935587, 'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:54:31,463] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.74450491092411, 'learning_rate': 0.08426314282635561, 'dropout_rate': 0.21845035750510394, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 0.3013998603131079, 'min_weight_fraction_leaf': 0.28488038648314357, 'max_features': 'auto', 'min_impurity_decrease': 4.969807589794284e-06, 'validation_fraction': 0.5953526855291732, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:55:10,148] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.07449175092046981, 'dropout_rate': 0.10061598571006734, 'n_estimators': 422, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8368147401670278, 'min_weight_fraction_leaf': 0.3103740193108716, 'max_features': 0.1, 'min_impurity_decrease': 1.5059537626102993e-07, 'validation_fraction': 0.8973370541013407, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-18 09:55:53,197] Trial 80 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8235918523200412, 'learning_rate': 0.04033855340571721, 'dropout_rate': 0.16425961502490374, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 1.694844319118747, 'min_weight_fraction_leaf': 0.2647465108562044, 'max_features': 'log2', 'min_impurity_decrease': 2.9198051926565164e-07, 'validation_fraction': 0.9949359598698552, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21270616661412084
Fold 2 IBS: 0.22114894326985232
Fold 3 IBS: 0.2033654110159561
Fold 4 IBS: 0.2242783032190139
Fold 5 IBS: 0.21754308206787823
[I 2024-04-18 09:56:53,740] Trial 81 finished with value: 0.21580838123736426 and parameters: {'subsample': 0.9683433550626522, 'learning_rate': 0.008693963960519305, 'dropout_rate': 0.1932014858120802, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2888444623370858, 'max_features': 'auto', 'min_impurity_decrease': 1.789620202740983e-05, 'validation_fraction': 0.938473425448535, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:57:46,983] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9762052388738753, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.19741538666007516, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.534138531195614, 'min_weight_fraction_leaf': 0.24700237584705395, 'max_features': 'auto', 'min_impurity_decrease': 7.152609841250385e-06, 'validation_fraction': 0.9388911144407316, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:58:47,462] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8945279252278314, 'learning_rate': 0.012088994568921815, 'dropout_rate': 0.154422708294762, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.1988546603429769, 'min_weight_fraction_leaf': 0.2902454191677818, 'max_features': 'auto', 'min_impurity_decrease': 3.133577694489401e-05, 'validation_fraction': 0.8395709442103857, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:59:32,342] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9340088491306221, 'learning_rate': 0.020145328722091006, 'dropout_rate': 0.23069098430626017, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5566102523015541, 'min_weight_fraction_leaf': 0.3043408977845187, 'max_features': 'auto', 'min_impurity_decrease': 5.245144153489441e-06, 'validation_fraction': 0.961947672530741, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:00:21,520] Trial 85 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.003151086314395833, 'dropout_rate': 0.12604720621824386, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 1.0429257766218587, 'min_weight_fraction_leaf': 0.13299714491615983, 'max_features': 'auto', 'min_impurity_decrease': 9.411442401014158e-06, 'validation_fraction': 0.9351152476505527, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:01:01,302] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.998032487033103, 'learning_rate': 0.015189890476328648, 'dropout_rate': 0.1929808152262999, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.25850792206277284, 'min_weight_fraction_leaf': 0.19547135211860373, 'max_features': 'sqrt', 'min_impurity_decrease': 7.182497909387456e-07, 'validation_fraction': 0.9008555229787725, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 10:01:30,056] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.586845457594135, 'learning_rate': 0.007791310814930576, 'dropout_rate': 0.2576203464314456, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 0.5970165508324569, 'min_weight_fraction_leaf': 0.3246889883811851, 'max_features': 'auto', 'min_impurity_decrease': 1.2915207513275362e-06, 'validation_fraction': 0.7941466165973634, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 10:02:00,818] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9047974654661481, 'learning_rate': 0.053489441535809173, 'dropout_rate': 0.15111205819257206, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 0.8515398041309932, 'min_weight_fraction_leaf': 0.21790404115359022, 'max_features': 'auto', 'min_impurity_decrease': 2.7145979471070252e-06, 'validation_fraction': 0.8752408074269059, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:02:45,245] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8838515048108662, 'learning_rate': 0.01150450588881658, 'dropout_rate': 0.3106345257277401, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.181177839559219, 'max_features': 'auto', 'min_impurity_decrease': 1.2718861827092477e-05, 'validation_fraction': 0.9760648785366552, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 10:03:44,156] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.960313946457138, 'learning_rate': 0.02326628275454888, 'dropout_rate': 0.2094619744215954, 'n_estimators': 470, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.16213094006522927, 'max_features': None, 'min_impurity_decrease': 8.384298759153104e-07, 'validation_fraction': 0.8362867621481024, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21278867450434957
Fold 2 IBS: 0.22123796611209143
Fold 3 IBS: 0.20385360063526636
Fold 4 IBS: 0.22428500781668678
Fold 5 IBS: 0.2173590980603734
[I 2024-04-18 10:04:38,227] Trial 91 finished with value: 0.21590486942575354 and parameters: {'subsample': 0.974845880068985, 'learning_rate': 0.008764883268716819, 'dropout_rate': 0.18635760945321272, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.2754894562810546, 'max_features': 'auto', 'min_impurity_decrease': 4.2012810231263196e-05, 'validation_fraction': 0.6282967667391103, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:05:32,192] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9396947823626011, 'learning_rate': 0.004368164180849998, 'dropout_rate': 0.1759357421598699, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.25915463409396067, 'min_weight_fraction_leaf': 0.25965914250337996, 'max_features': 'auto', 'min_impurity_decrease': 8.321039301525785e-05, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20443254583780004
Fold 2 IBS: 0.21704992653232766
Fold 3 IBS: 0.20021814328282203
Fold 4 IBS: 0.21936269502578284
Fold 5 IBS: 0.2126381390950113
[I 2024-04-18 10:06:24,267] Trial 93 finished with value: 0.2107402899547488 and parameters: {'subsample': 0.9636218550527925, 'learning_rate': 0.08324257203844727, 'dropout_rate': 0.22319965814002635, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.04690043062719928, 'min_weight_fraction_leaf': 0.23684277621975902, 'max_features': 'auto', 'min_impurity_decrease': 1.548140174949508e-05, 'validation_fraction': 0.7388312145266367, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 10:07:14,418] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9216100363199584, 'learning_rate': 0.08937987875028564, 'dropout_rate': 0.2226719596812821, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.5370821041135924, 'min_weight_fraction_leaf': 0.23931318130410523, 'max_features': 'auto', 'min_impurity_decrease': 1.9804047777777935e-05, 'validation_fraction': 0.9344757106941509, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 10:08:10,784] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9505720618597318, 'learning_rate': 0.08804335553847131, 'dropout_rate': 0.2858426054482697, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.3311905561863823, 'min_weight_fraction_leaf': 0.1453679981012504, 'max_features': 'auto', 'min_impurity_decrease': 9.665752514196455e-06, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:08:57,868] Trial 96 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9806046119279813, 'learning_rate': 0.08726220388438458, 'dropout_rate': 0.2508258253233333, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.0842424782139257, 'min_weight_fraction_leaf': 0.2509877726726459, 'max_features': 'auto', 'min_impurity_decrease': 4.132954919887874e-06, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:09:34,679] Trial 97 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9139721535827401, 'learning_rate': 0.0956243686002578, 'dropout_rate': 0.11551248506043046, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.20602145594384874, 'min_weight_fraction_leaf': 0.21288677009944212, 'max_features': 1, 'min_impurity_decrease': 5.099166934714435e-07, 'validation_fraction': 0.6982085459927765, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:10:27,812] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.881458897433829, 'learning_rate': 0.0818716069302554, 'dropout_rate': 0.1602397729595261, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.7476516282703678, 'min_weight_fraction_leaf': 0.29398452840523387, 'max_features': 'auto', 'min_impurity_decrease': 2.2015056170379928e-06, 'validation_fraction': 0.9116047571236726, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20960061935285024
Fold 2 IBS: 0.21745644638172798

Fold 3 IBS: 0.20030580413616672
Fold 4 IBS: 0.21827950204883104
Fold 5 IBS: 0.2160767264619057
[I 2024-04-18 10:11:08,159] Trial 99 finished with value: 0.21234381967629634 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.07921297533010697, 'dropout_rate': 0.36361374787631456, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.004455045338579978, 'min_weight_fraction_leaf': 0.23447872920034368, 'max_features': 0.1, 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.4378698142708704, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.20755403023595909], datetime_start=datetime.datetime(2024, 4, 18, 9, 52, 18, 716336), datetime_complete=datetime.datetime(2024, 4, 18, 9, 52, 59, 590900), params={'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.20755403023595909

In [66]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.208

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0339977959383996,
                                 criterion='squared_error',
                                 dropout_rate=0.2075412325353082,
                                 learning_rate=0.010706280861824496,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=3.3602815261835675e-07,
                                 min_samples_leaf=13, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4472167339801619,
                                 n_estimators=445, random_state=123,
                                 subsample=0.9030031356045858,
                                 validation_fraction=0.9350158433232643)

C-index score: 0.618

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008810810992982535,
                                 criterion='squared_error',
                                 dropout_rate=0.1693875032679634,
                                 learning_rate=0.08843409287484169,
                                 max_features='auto', max_leaf_nodes=15,
                                 min_impurity_decrease=5.157320437854681e-06,
                                 min_samples_leaf=16, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29044798941528627,
                                 n_estimators=403, random_state=123,
                                 subsample=0.8646743646205938,
                                 validation_fraction=0.7489142536117352)

IBS: 0.213

In [70]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [71]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [72]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 10:11:27,834] A new study created in memory with name: no-name-46918a9a-8ed8-473f-ac8c-cb2f72667a3d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:11:32,183] Trial 0 finished with value: 0.6925028294272052 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:11:52,562] Trial 1 finished with value: 0.6915224372703425 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6925028294272052.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:11:59,514] Trial 2 finished with value: 0.6951295602764356 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6951295602764356.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:12:07,178] Trial 3 finished with value: 0.7014095241250523 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7014095241250523.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:12:18,008] Trial 4 finished with value: 0.7040610392765674 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7040610392765674.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:12:32,151] Trial 5 finished with value: 0.6866204764860286 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7040610392765674.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:12:38,977] Trial 6 finished with value: 0.689561652956617 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7040610392765674.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:12:40,807] Trial 7 finished with value: 0.698014942982655 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7040610392765674.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:12:49,048] Trial 8 finished with value: 0.6924614044064927 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7040610392765674.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:13:07,945] Trial 9 finished with value: 0.6952660705767583 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7040610392765674.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:13:20,083] Trial 10 finished with value: 0.7031145218748126 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 4 with value: 0.7040610392765674.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 10:13:33,247] Trial 11 finished with value: 0.7307806313500943 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:13:45,852] Trial 12 finished with value: 0.7163341735014888 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.2495649826842376, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:14:01,468] Trial 13 finished with value: 0.6972390901286689 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:14:18,098] Trial 14 finished with value: 0.7162362229288546 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24475605651992097, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:14:30,738] Trial 15 finished with value: 0.6952027265467849 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.6858923927618094, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 10:14:48,761] Trial 16 finished with value: 0.7255555933130313 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.10222885325126996, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.784037558685446
[I 2024-04-18 10:15:08,146] Trial 17 finished with value: 0.7159921810018032 and parameters: {'subsample': 0.2738903405395941, 'dropout_rate': 0.1019684592707394, 'n_estimators': 445, 'learning_rate': 0.0834370349684546}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:15:25,323] Trial 18 finished with value: 0.6989539101188053 and parameters: {'subsample': 0.34810348568738264, 'dropout_rate': 0.7033122086799477, 'n_estimators': 430, 'learning_rate': 0.08279335722009089}. Best is trial 11 with value: 0.7307806313500943.

Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:15:41,605] Trial 19 finished with value: 0.7083923155803433 and parameters: {'subsample': 0.19816662555708264, 'dropout_rate': 0.34721836740782674, 'n_estimators': 400, 'learning_rate': 0.08909215792368923}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:15:51,644] Trial 20 finished with value: 0.6970241352671638 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.1874011856184571, 'n_estimators': 258, 'learning_rate': 0.06551866052750378}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:16:04,784] Trial 21 finished with value: 0.7160536026352389 and parameters: {'subsample': 0.12432193929457189, 'dropout_rate': 0.20979895038784535, 'n_estimators': 318, 'learning_rate': 0.0929934357366757}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:16:22,048] Trial 22 finished with value: 0.7091630311665339 and parameters: {'subsample': 0.19546557137710827, 'dropout_rate': 0.2970189594128161, 'n_estimators': 414, 'learning_rate': 0.07877249753813559}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 10:16:35,743] Trial 23 finished with value: 0.724553282146908 and parameters: {'subsample': 0.22497808398272548, 'dropout_rate': 0.10003957846278239, 'n_estimators': 339, 'learning_rate': 0.09323355252515839}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 10:16:51,556] Trial 24 finished with value: 0.7104333641348076 and parameters: {'subsample': 0.23680049380004198, 'dropout_rate': 0.15513967349209856, 'n_estimators': 388, 'learning_rate': 0.09020357878151809}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:17:05,962] Trial 25 finished with value: 0.7040311177064871 and parameters: {'subsample': 0.342177607764483, 'dropout_rate': 0.11261425324062513, 'n_estimators': 348, 'learning_rate': 0.07863489086649084}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:17:24,853] Trial 26 finished with value: 0.6988393188277435 and parameters: {'subsample': 0.4154241705504771, 'dropout_rate': 0.18115044620320617, 'n_estimators': 454, 'learning_rate': 0.03953731298141484}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:17:33,394] Trial 27 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.9861686560685959, 'n_estimators': 234, 'learning_rate': 0.06071884280131438}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:17:44,790] Trial 28 finished with value: 0.7092581164461441 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.3101570144170164, 'n_estimators': 290, 'learning_rate': 0.09185025747795333}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:17:50,434] Trial 29 finished with value: 0.6934417965633555 and parameters: {'subsample': 0.5845394212326824, 'dropout_rate': 0.4175950896276197, 'n_estimators': 152, 'learning_rate': 0.07495502018549609}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:17:53,953] Trial 30 finished with value: 0.6846596921723032 and parameters: {'subsample': 0.8739790489864521, 'dropout_rate': 0.3147724236933673, 'n_estimators': 93, 'learning_rate': 0.016814619253793885}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 10:18:08,304] Trial 31 finished with value: 0.7306389837819761 and parameters: {'subsample': 0.1232592101340109, 'dropout_rate': 0.10343939945411366, 'n_estimators': 348, 'learning_rate': 0.09708894599274794}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:18:22,520] Trial 32 finished with value: 0.7261123996511845 and parameters: {'subsample': 0.10223331352781442, 'dropout_rate': 0.10085034875741614, 'n_estimators': 343, 'learning_rate': 0.08459270312706267}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:18:43,010] Trial 33 finished with value: 0.7143997136772665 and parameters: {'subsample': 0.10120060489936013, 'dropout_rate': 0.19272461439884953, 'n_estimators': 485, 'learning_rate': 0.0687303685240307}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:18:59,612] Trial 34 finished with value: 0.71990455645945 and parameters: {'subsample': 0.14154027296706004, 'dropout_rate': 0.16038673520060953, 'n_estimators': 394, 'learning_rate': 0.07882597684583167}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:19:10,344] Trial 35 finished with value: 0.7066607138487415 and parameters: {'subsample': 0.17024068531133396, 'dropout_rate': 0.5333294823429767, 'n_estimators': 275, 'learning_rate': 0.08614487475647208}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:19:27,790] Trial 36 finished with value: 0.7031411258566539 and parameters: {'subsample': 0.2897225007233907, 'dropout_rate': 0.1427176072125974, 'n_estimators': 421, 'learning_rate': 0.07409061991008009}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:19:40,948] Trial 37 finished with value: 0.7021802397112429 and parameters: {'subsample': 0.3002008918522374, 'dropout_rate': 0.21936489381599394, 'n_estimators': 331, 'learning_rate': 0.0942551407730424}. Best is trial 11 with value: 0.7307806313500943.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:19:56,209] Trial 38 finished with value: 0.7013363578547028 and parameters: {'subsample': 0.23339141148458184, 'dropout_rate': 0.3720991365773877, 'n_estimators': 376, 'learning_rate': 0.05887691176315654}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:20:14,043] Trial 39 finished with value: 0.6970028095761555 and parameters: {'subsample': 0.4274786379279678, 'dropout_rate': 0.7545555141153719, 'n_estimators': 454, 'learning_rate': 0.06892741183938003}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:20:23,464] Trial 40 finished with value: 0.710170027305238 and parameters: {'subsample': 0.15794461461304163, 'dropout_rate': 0.280971539366882, 'n_estimators': 245, 'learning_rate': 0.08467297149335681}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.784037558685446
[I 2024-04-18 10:20:37,560] Trial 41 finished with value: 0.7218775760113605 and parameters: {'subsample': 0.22712824450766206, 'dropout_rate': 0.10193785412647183, 'n_estimators': 342, 'learning_rate': 0.09536189075695126}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 10:20:50,866] Trial 42 finished with value: 0.7094212307283082 and parameters: {'subsample': 0.222240386976347, 'dropout_rate': 0.14870606959247784, 'n_estimators': 333, 'learning_rate': 0.09075141716721255}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:21:02,406] Trial 43 finished with value: 0.7082759046097247 and parameters: {'subsample': 0.15004552831309048, 'dropout_rate': 0.21364649737564864, 'n_estimators': 284, 'learning_rate': 0.09964378505277027}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:21:02,677] Trial 44 finished with value: 0.7031628680905578 and parameters: {'subsample': 0.3193403818323205, 'dropout_rate': 0.1444908677826617, 'n_estimators': 3, 'learning_rate': 0.08127314437419977}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:21:16,855] Trial 45 finished with value: 0.6915224372703425 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.6219587265298226, 'n_estimators': 364, 'learning_rate': 0.08728293554150966}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:21:33,341] Trial 46 finished with value: 0.7084435628414317 and parameters: {'subsample': 0.1717026689714639, 'dropout_rate': 0.4765982863175019, 'n_estimators': 410, 'learning_rate': 0.09541081568053421}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:21:41,803] Trial 47 finished with value: 0.7267685239463133 and parameters: {'subsample': 0.10125734891084931, 'dropout_rate': 0.1240463473883398, 'n_estimators': 220, 'learning_rate': 0.07649118411458425}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:21:50,182] Trial 48 finished with value: 0.7162851982151717 and parameters: {'subsample': 0.10140694592231314, 'dropout_rate': 0.25836548949139937, 'n_estimators': 217, 'learning_rate': 0.06863089732485125}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:21:56,729] Trial 49 finished with value: 0.6995362748253324 and parameters: {'subsample': 0.7180092556560971, 'dropout_rate': 0.1304931000922671, 'n_estimators': 165, 'learning_rate': 0.07376951860699396}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:22:02,166] Trial 50 finished with value: 0.7153509160516018 and parameters: {'subsample': 0.13333120581820768, 'dropout_rate': 0.1708585019469942, 'n_estimators': 143, 'learning_rate': 0.05378378517676694}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 10:22:09,457] Trial 51 finished with value: 0.7219726612909707 and parameters: {'subsample': 0.24774739677832328, 'dropout_rate': 0.10128185135623688, 'n_estimators': 189, 'learning_rate': 0.08768574787673414}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:22:21,737] Trial 52 finished with value: 0.7058555327429274 and parameters: {'subsample': 0.1936344186313584, 'dropout_rate': 0.22081954846158997, 'n_estimators': 311, 'learning_rate': 0.09695623292667468}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:22:32,764] Trial 53 finished with value: 0.7215335226458368 and parameters: {'subsample': 0.13971048146087944, 'dropout_rate': 0.13260012950010353, 'n_estimators': 272, 'learning_rate': 0.08152773384700819}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:22:47,941] Trial 54 finished with value: 0.7074482111763976 and parameters: {'subsample': 0.2011912922631306, 'dropout_rate': 0.19125641900973073, 'n_estimators': 371, 'learning_rate': 0.09116697558643283}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 10:23:00,304] Trial 55 finished with value: 0.711421306557275 and parameters: {'subsample': 0.2605029959970905, 'dropout_rate': 0.12352453256561395, 'n_estimators': 300, 'learning_rate': 0.07724345362341684}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:23:08,608] Trial 56 finished with value: 0.7171975613694804 and parameters: {'subsample': 0.1096250605308845, 'dropout_rate': 0.23863311043472657, 'n_estimators': 218, 'learning_rate': 0.08520724607985052}. Best is trial 11 with value: 0.7307806313500943.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:23:26,833] Trial 57 finished with value: 0.7153509160516018 and parameters: {'subsample': 0.17785038738245568, 'dropout_rate': 0.17088125676906357, 'n_estimators': 437, 'learning_rate': 0.09971861556008405}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:23:48,191] Trial 58 finished with value: 0.7154413163586316 and parameters: {'subsample': 0.14179971236473837, 'dropout_rate': 0.10181500938916374, 'n_estimators': 498, 'learning_rate': 0.043370918967722674}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:23:58,188] Trial 59 finished with value: 0.7084384255736363 and parameters: {'subsample': 0.20245072606763964, 'dropout_rate': 0.26457901509278003, 'n_estimators': 251, 'learning_rate': 0.09339322934480054}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:24:10,957] Trial 60 finished with value: 0.6979003516915931 and parameters: {'subsample': 0.5189632954980922, 'dropout_rate': 0.3447091869450074, 'n_estimators': 324, 'learning_rate': 0.0900031169168506}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.784037558685446
[I 2024-04-18 10:24:18,366] Trial 61 finished with value: 0.715850533433685 and parameters: {'subsample': 0.24707969665865606, 'dropout_rate': 0.1076326130738862, 'n_estimators': 194, 'learning_rate': 0.08216252998497638}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:24:23,126] Trial 62 finished with value: 0.7031653168406863 and parameters: {'subsample': 0.31048452740239474, 'dropout_rate': 0.16417624139567938, 'n_estimators': 125, 'learning_rate': 0.08852495479025066}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 10:24:30,973] Trial 63 finished with value: 0.711501291305676 and parameters: {'subsample': 0.2671075152873865, 'dropout_rate': 0.1332942086143597, 'n_estimators': 200, 'learning_rate': 0.0877306960090755}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:24:45,636] Trial 64 finished with value: 0.7133537055156589 and parameters: {'subsample': 0.1227411792395213, 'dropout_rate': 0.18680135310525137, 'n_estimators': 353, 'learning_rate': 0.08447359488201481}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:24:54,928] Trial 65 finished with value: 0.7200191477505118 and parameters: {'subsample': 0.16349301302627323, 'dropout_rate': 0.13283899373874214, 'n_estimators': 233, 'learning_rate': 0.09686409890052881}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:25:15,169] Trial 66 finished with value: 0.716231537956274 and parameters: {'subsample': 0.10130958076037336, 'dropout_rate': 0.20907461082273537, 'n_estimators': 469, 'learning_rate': 0.07666526350844838}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:25:26,510] Trial 67 finished with value: 0.6998197109846063 and parameters: {'subsample': 0.3810857111822015, 'dropout_rate': 0.8326075750999824, 'n_estimators': 302, 'learning_rate': 0.08052421266770941}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:25:33,272] Trial 68 finished with value: 0.7050558001770864 and parameters: {'subsample': 0.22879547471220837, 'dropout_rate': 0.15451397275177287, 'n_estimators': 178, 'learning_rate': 0.0267624773650322}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 10:25:48,790] Trial 69 finished with value: 0.7147847397682878 and parameters: {'subsample': 0.20597481398295686, 'dropout_rate': 0.1054161258618466, 'n_estimators': 381, 'learning_rate': 0.07182974044787087}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:25:52,021] Trial 70 finished with value: 0.7055973331811533 and parameters: {'subsample': 0.17266115690901634, 'dropout_rate': 0.19045670994993433, 'n_estimators': 86, 'learning_rate': 0.008127880939407618}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:26:06,070] Trial 71 finished with value: 0.7173458546127733 and parameters: {'subsample': 0.2248575292991628, 'dropout_rate': 0.11698135902838636, 'n_estimators': 340, 'learning_rate': 0.09409541883431859}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 10:26:20,210] Trial 72 finished with value: 0.7150359798289726 and parameters: {'subsample': 0.34157166542357265, 'dropout_rate': 0.10530586652369955, 'n_estimators': 352, 'learning_rate': 0.09636121546765124}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:26:36,944] Trial 73 finished with value: 0.7188924230529502 and parameters: {'subsample': 0.1340051423728994, 'dropout_rate': 0.15884476914860357, 'n_estimators': 401, 'learning_rate': 0.09179768058720972}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:26:46,986] Trial 74 finished with value: 0.7029970652907267 and parameters: {'subsample': 0.2831233757759253, 'dropout_rate': 0.22866163414522334, 'n_estimators': 260, 'learning_rate': 0.08692635147420757}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7934272300469484
[I 2024-04-18 10:27:01,165] Trial 75 finished with value: 0.7237284540066047 and parameters: {'subsample': 0.24984304789366782, 'dropout_rate': 0.1022640338340257, 'n_estimators': 344, 'learning_rate': 0.0971144796337399}. Best is trial 11 with value: 0.7307806313500943.

Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 10:27:12,372] Trial 76 finished with value: 0.7105065304051571 and parameters: {'subsample': 0.2552173429240417, 'dropout_rate': 0.14075848429451382, 'n_estimators': 286, 'learning_rate': 0.08913721965143313}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:27:25,006] Trial 77 finished with value: 0.6995633311023886 and parameters: {'subsample': 0.43624034575953075, 'dropout_rate': 0.17629353184919394, 'n_estimators': 320, 'learning_rate': 0.08458339025235229}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:27:39,152] Trial 78 finished with value: 0.696212587978513 and parameters: {'subsample': 0.8440943704206645, 'dropout_rate': 0.20432053435192785, 'n_estimators': 358, 'learning_rate': 0.09782638304170042}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:27:55,164] Trial 79 finished with value: 0.7243313703380507 and parameters: {'subsample': 0.1594137164676687, 'dropout_rate': 0.1275340754221122, 'n_estimators': 387, 'learning_rate': 0.09294115164305988}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:28:10,582] Trial 80 finished with value: 0.7109948554455412 and parameters: {'subsample': 0.1557523637865393, 'dropout_rate': 0.5761395811228207, 'n_estimators': 385, 'learning_rate': 0.09292193641661042}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:28:28,270] Trial 81 finished with value: 0.7288020222351733 and parameters: {'subsample': 0.12688095425495413, 'dropout_rate': 0.11949477031809864, 'n_estimators': 426, 'learning_rate': 0.09997643838350857}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:28:45,821] Trial 82 finished with value: 0.7234655694722499 and parameters: {'subsample': 0.12138318750308096, 'dropout_rate': 0.1280319383470524, 'n_estimators': 418, 'learning_rate': 0.09456908962308308}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:29:02,270] Trial 83 finished with value: 0.7162409079014351 and parameters: {'subsample': 0.18556585961275068, 'dropout_rate': 0.15711146558967404, 'n_estimators': 396, 'learning_rate': 0.09951896630824049}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:29:17,389] Trial 84 finished with value: 0.7206947780570923 and parameters: {'subsample': 0.15720942385343906, 'dropout_rate': 0.12858906776157297, 'n_estimators': 368, 'learning_rate': 0.09146378807346654}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:29:35,161] Trial 85 finished with value: 0.7181094722285744 and parameters: {'subsample': 0.11872594268461546, 'dropout_rate': 0.1759147292530131, 'n_estimators': 430, 'learning_rate': 0.09753747651002517}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:29:52,185] Trial 86 finished with value: 0.714830849761581 and parameters: {'subsample': 0.21579266343798084, 'dropout_rate': 0.14645400330372263, 'n_estimators': 407, 'learning_rate': 0.09430122943936055}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:30:11,637] Trial 87 finished with value: 0.7305002015068819 and parameters: {'subsample': 0.10086498081695955, 'dropout_rate': 0.12415273133062231, 'n_estimators': 451, 'learning_rate': 0.08957846538957111}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:30:30,636] Trial 88 finished with value: 0.7092748981876094 and parameters: {'subsample': 0.14189722462323, 'dropout_rate': 0.2841978993020756, 'n_estimators': 456, 'learning_rate': 0.07962406770838117}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:30:51,034] Trial 89 finished with value: 0.7171434488153678 and parameters: {'subsample': 0.10061357616763471, 'dropout_rate': 0.23986045085759167, 'n_estimators': 480, 'learning_rate': 0.0825931511963985}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:31:09,541] Trial 90 finished with value: 0.7109845809099503 and parameters: {'subsample': 0.12547068737762085, 'dropout_rate': 0.434249547185394, 'n_estimators': 444, 'learning_rate': 0.09146293569226428}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:31:23,172] Trial 91 finished with value: 0.7198779524776084 and parameters: {'subsample': 0.18075163813239453, 'dropout_rate': 0.11995097308360905, 'n_estimators': 340, 'learning_rate': 0.0892945568692372}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 10:31:42,934] Trial 92 finished with value: 0.7279776463900849 and parameters: {'subsample': 0.14276155678889968, 'dropout_rate': 0.10154469665685646, 'n_estimators': 464, 'learning_rate': 0.09697851024460136}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:32:03,127] Trial 93 finished with value: 0.7161486879148489 and parameters: {'subsample': 0.15275165946797373, 'dropout_rate': 0.15684861688665627, 'n_estimators': 469, 'learning_rate': 0.08686184986341759}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 10:32:20,614] Trial 94 finished with value: 0.7278677400716036 and parameters: {'subsample': 0.12691203804794637, 'dropout_rate': 0.1260789509040807, 'n_estimators': 423, 'learning_rate': 0.09530223430293491}. Best is trial 11 with value: 0.7307806313500943.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:32:39,228] Trial 95 finished with value: 0.7171290800717116 and parameters: {'subsample': 0.1209848220517555, 'dropout_rate': 0.2043816298169483, 'n_estimators': 448, 'learning_rate': 0.09531714419817171}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:32:57,586] Trial 96 finished with value: 0.7133732115271108 and parameters: {'subsample': 0.10076610468979086, 'dropout_rate': 0.17470115021321636, 'n_estimators': 427, 'learning_rate': 0.06413325090254297}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:33:15,895] Trial 97 finished with value: 0.7188168437847919 and parameters: {'subsample': 0.13834151411322843, 'dropout_rate': 0.1437665485108484, 'n_estimators': 439, 'learning_rate': 0.09828491086976622}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:33:35,170] Trial 98 finished with value: 0.7180755974734664 and parameters: {'subsample': 0.18110644127357575, 'dropout_rate': 0.12099373308413147, 'n_estimators': 458, 'learning_rate': 0.08963675080441326}. Best is trial 11 with value: 0.7307806313500943.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6919831223628692

[I 2024-04-18 10:33:56,466] A new study created in memory with name: no-name-fed21687-b596-42d4-ba7a-c51aaecc582d

Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:33:56,459] Trial 99 finished with value: 0.711226451025474 and parameters: {'subsample': 0.20601540087766917, 'dropout_rate': 0.10041090748912196, 'n_estimators': 494, 'learning_rate': 0.04932061074271092}. Best is trial 11 with value: 0.7307806313500943.


* Best trial for C-index:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.7307806313500943], datetime_start=datetime.datetime(2024, 4, 18, 10, 13, 20, 86633), datetime_complete=datetime.datetime(2024, 4, 18, 10, 13, 33, 247488), params={'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=11, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}


* Best Score for C-index:
 0.7307806313500943

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24692977896599883
Fold 2 IBS: 0.23367124240111953
Fold 3 IBS: 0.18592983540335206
Fold 4 IBS: 0.2632765971484762
Fold 5 IBS: 0.2101930209796324
[I 2024-04-18 10:34:00,771] Trial 0 finished with value: 0.2280000949797158 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.3168791384838904
Fold 2 IBS: 0.3218948725307976
Fold 3 IBS: 0.27592959166775866
Fold 4 IBS: 0.315408539471182
Fold 5 IBS: 0.30438829249434424
[I 2024-04-18 10:34:21,085] Trial 1 finished with value: 0.3069000869295946 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2753019447545149
Fold 2 IBS: 0.2982356241179488
Fold 3 IBS: 0.23068334408596278
Fold 4 IBS: 0.27397829249360633
Fold 5 IBS: 0.25684924696430295
[I 2024-04-18 10:34:27,656] Trial 2 finished with value: 0.26700969048326717 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2786819074278709
Fold 2 IBS: 0.2600472138747981
Fold 3 IBS: 0.23882358787102978
Fold 4 IBS: 0.2592722986281111
Fold 5 IBS: 0.2225859207530073
[I 2024-04-18 10:34:35,224] Trial 3 finished with value: 0.2518821857109634 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.2789680361121065
Fold 2 IBS: 0.2854872443291161
Fold 3 IBS: 0.23948666083462447
Fold 4 IBS: 0.2562837019187784
Fold 5 IBS: 0.23290610435793277
[I 2024-04-18 10:34:45,605] Trial 4 finished with value: 0.25862634951051167 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.30156654310213465
Fold 2 IBS: 0.3204353433554115
Fold 3 IBS: 0.2623263101041928
Fold 4 IBS: 0.3038662427158054
Fold 5 IBS: 0.2972845037916553
[I 2024-04-18 10:34:59,923] Trial 5 finished with value: 0.29709578861383995 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2280000949797158.
Fold 1 IBS: 0.23284347689671558
Fold 2 IBS: 0.202874467602479
Fold 3 IBS: 0.17322347591450493
Fold 4 IBS: 0.24151316943928927
Fold 5 IBS: 0.1909058630290115
[I 2024-04-18 10:35:06,644] Trial 6 finished with value: 0.20827209057640003 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20827209057640003.
Fold 1 IBS: 0.20841359719195401
Fold 2 IBS: 0.18500570168858935
Fold 3 IBS: 0.17412783878300364
Fold 4 IBS: 0.20964581935767979
Fold 5 IBS: 0.18557256212482354
[I 2024-04-18 10:35:08,469] Trial 7 finished with value: 0.19255310382921006 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.2500273900096136
Fold 2 IBS: 0.24252428811376492
Fold 3 IBS: 0.19169795532346123
Fold 4 IBS: 0.26800891557035394
Fold 5 IBS: 0.2071713040887332
[I 2024-04-18 10:35:16,796] Trial 8 finished with value: 0.2318859706211854 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.3046029224708627
Fold 2 IBS: 0.32082834695628154
Fold 3 IBS: 0.26733861086225763
Fold 4 IBS: 0.3050114978922588
Fold 5 IBS: 0.2891835646808364
[I 2024-04-18 10:35:35,038] Trial 9 finished with value: 0.2973929885724994 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.21341107818060095
Fold 2 IBS: 0.22041244256787032
Fold 3 IBS: 0.20358827659270148
Fold 4 IBS: 0.22376802174886082
Fold 5 IBS: 0.2171830253408078
[I 2024-04-18 10:35:36,059] Trial 10 finished with value: 0.21567256888616831 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.2131898560857691
Fold 2 IBS: 0.22000460296162738
Fold 3 IBS: 0.20348419225803208
Fold 4 IBS: 0.22352663518317686
Fold 5 IBS: 0.2169388510633896
[I 2024-04-18 10:35:36,320] Trial 11 finished with value: 0.215428827510399 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.2649085487462804
Fold 2 IBS: 0.27750555267605553
Fold 3 IBS: 0.21547582765233256
Fold 4 IBS: 0.269516915435845
Fold 5 IBS: 0.218257449444187
[I 2024-04-18 10:35:40,222] Trial 12 finished with value: 0.24913285879094013 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.26365849597545205
Fold 2 IBS: 0.27755786474823224
Fold 3 IBS: 0.21375266267140264
Fold 4 IBS: 0.27739729053928086
Fold 5 IBS: 0.24947493405031224
[I 2024-04-18 10:35:51,679] Trial 13 finished with value: 0.25636824959693605 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.20569427667469156
Fold 2 IBS: 0.19327418056505236
Fold 3 IBS: 0.18069024590527896
Fold 4 IBS: 0.2080995790312972
Fold 5 IBS: 0.19490230571351805
[I 2024-04-18 10:35:55,469] Trial 14 finished with value: 0.19653211757796762 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.210409804816474
Fold 2 IBS: 0.21349058556283512
Fold 3 IBS: 0.1985155340163065
Fold 4 IBS: 0.21856174646948462
Fold 5 IBS: 0.21176579623888744
[I 2024-04-18 10:35:58,413] Trial 15 finished with value: 0.21054869342079754 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.20630685620006517
Fold 2 IBS: 0.20273931524283226
Fold 3 IBS: 0.18919005657291543
Fold 4 IBS: 0.21127743577400432
Fold 5 IBS: 0.20267124736055916
[I 2024-04-18 10:36:00,703] Trial 16 finished with value: 0.20243698223007528 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.23835959803032003
Fold 2 IBS: 0.21402340081247587
Fold 3 IBS: 0.17953828231829627
Fold 4 IBS: 0.25047212321042694
Fold 5 IBS: 0.19743222117495793
[I 2024-04-18 10:36:05,449] Trial 17 finished with value: 0.2159651251092954 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.23992452095154856
Fold 2 IBS: 0.21471857497068447
Fold 3 IBS: 0.18009687426129353
Fold 4 IBS: 0.24881181915281447
Fold 5 IBS: 0.19020851533379485
[I 2024-04-18 10:36:18,379] Trial 18 finished with value: 0.21475206093402716 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19255310382921006.
Fold 1 IBS: 0.2021259476312318

Fold 2 IBS: 0.17924472193393295
Fold 3 IBS: 0.17484421871598207
Fold 4 IBS: 0.19182158774709396
Fold 5 IBS: 0.18517059625171137
[I 2024-04-18 10:36:20,319] Trial 19 finished with value: 0.18664141445599042 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.20385002842262298
Fold 2 IBS: 0.17898541076661173
Fold 3 IBS: 0.177518113027334
Fold 4 IBS: 0.1979575811954832
Fold 5 IBS: 0.18798127523636654
[I 2024-04-18 10:36:22,058] Trial 20 finished with value: 0.18925848172968368 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.20069110092838113
Fold 2 IBS: 0.1892544406321917
Fold 3 IBS: 0.18218745670213524
Fold 4 IBS: 0.20090706949452952
Fold 5 IBS: 0.19341752476488996
[I 2024-04-18 10:36:23,395] Trial 21 finished with value: 0.1932915185044255 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.21289135072667675
Fold 2 IBS: 0.2192362843041557
Fold 3 IBS: 0.20256314478108844
Fold 4 IBS: 0.22230805658932015
Fold 5 IBS: 0.21635372756130705
[I 2024-04-18 10:36:23,665] Trial 22 finished with value: 0.21467051279250962 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.23708682933847808
Fold 2 IBS: 0.20385714154758022
Fold 3 IBS: 0.18521649133151546
Fold 4 IBS: 0.2291838940176639
Fold 5 IBS: 0.1801242701652537
[I 2024-04-18 10:36:29,215] Trial 23 finished with value: 0.2070937252800983 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.22412270848810453
Fold 2 IBS: 0.1908952941916656
Fold 3 IBS: 0.17076790246118903
Fold 4 IBS: 0.23054053553396578
Fold 5 IBS: 0.17962396392219857
[I 2024-04-18 10:36:31,365] Trial 24 finished with value: 0.19919008091942472 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.22104049859904298
Fold 2 IBS: 0.1845697626181813
Fold 3 IBS: 0.171869292415374
Fold 4 IBS: 0.21655359416191086
Fold 5 IBS: 0.18002285778425875
[I 2024-04-18 10:36:34,306] Trial 25 finished with value: 0.1948112011157536 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.26243792510556835
Fold 2 IBS: 0.2483094873904
Fold 3 IBS: 0.2316722640314743
Fold 4 IBS: 0.2247010894155808
Fold 5 IBS: 0.22905587489702545
[I 2024-04-18 10:36:39,819] Trial 26 finished with value: 0.2392353281680098 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.25537532111682654
Fold 2 IBS: 0.24616377577681198
Fold 3 IBS: 0.20330381468053177
Fold 4 IBS: 0.26509675916293274
Fold 5 IBS: 0.20895531852025304
[I 2024-04-18 10:36:48,876] Trial 27 finished with value: 0.23577899785147122 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.20527495893711703
Fold 2 IBS: 0.1923192977101289
Fold 3 IBS: 0.18569841819626018
Fold 4 IBS: 0.2063890017855301
Fold 5 IBS: 0.19858083613604766
[I 2024-04-18 10:36:50,524] Trial 28 finished with value: 0.19765250255301678 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.25186522298741737
Fold 2 IBS: 0.24845492076238285
Fold 3 IBS: 0.19440108192909572
Fold 4 IBS: 0.27098179405615386
Fold 5 IBS: 0.20392403254079125
[I 2024-04-18 10:36:55,097] Trial 29 finished with value: 0.23392541045516818 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.2330665600388519
Fold 2 IBS: 0.1896692549397342
Fold 3 IBS: 0.17562341060021416
Fold 4 IBS: 0.2231198608530349
Fold 5 IBS: 0.18111074079217584
[I 2024-04-18 10:36:58,942] Trial 30 finished with value: 0.20051796544480222 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.20099528887376109
Fold 2 IBS: 0.18308690562421903
Fold 3 IBS: 0.1779752579597176
Fold 4 IBS: 0.1984841468259268
Fold 5 IBS: 0.18834061918297867
[I 2024-04-18 10:37:00,289] Trial 31 finished with value: 0.1897764436933206 and parameters: {'subsample': 0.10849767566207504, 'dropout_rate': 0.961860592675692, 'n_estimators': 33, 'learning_rate': 0.0562781123341657}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.2034563655600113
Fold 2 IBS: 0.18856273040501406
Fold 3 IBS: 0.1813864736795483
Fold 4 IBS: 0.2000636457137027
Fold 5 IBS: 0.1915280367568049
[I 2024-04-18 10:37:01,432] Trial 32 finished with value: 0.19299945042301628 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.9389584836732486, 'n_estimators': 27, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.21866270441789398
Fold 2 IBS: 0.16866491177272497
Fold 3 IBS: 0.17262054106672534
Fold 4 IBS: 0.20131559423696158
Fold 5 IBS: 0.1777391506961698
[I 2024-04-18 10:37:03,826] Trial 33 finished with value: 0.1878005804380951 and parameters: {'subsample': 0.10124175077360453, 'dropout_rate': 0.8598326511213237, 'n_estimators': 63, 'learning_rate': 0.06694265963579746}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.21134490777110404
Fold 2 IBS: 0.21620392958500384
Fold 3 IBS: 0.19947910525310025
Fold 4 IBS: 0.2188565718064687
Fold 5 IBS: 0.21362043912965564
[I 2024-04-18 10:37:04,128] Trial 34 finished with value: 0.21190099070906648 and parameters: {'subsample': 0.10904251030586302, 'dropout_rate': 0.8662195064551774, 'n_estimators': 3, 'learning_rate': 0.07766566220378217}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.26215924412786523
Fold 2 IBS: 0.25965408097866455
Fold 3 IBS: 0.21333959381290407
Fold 4 IBS: 0.26840863359298894
Fold 5 IBS: 0.21872231610389728
[I 2024-04-18 10:37:09,292] Trial 35 finished with value: 0.24445677372326405 and parameters: {'subsample': 0.27868485453535496, 'dropout_rate': 0.9999743696114711, 'n_estimators': 141, 'learning_rate': 0.06694317131672249}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.31801903549259186
Fold 2 IBS: 0.3188091302902034
Fold 3 IBS: 0.2761228634482283
Fold 4 IBS: 0.26980865571559215
Fold 5 IBS: 0.2707361194141128
[I 2024-04-18 10:37:25,627] Trial 36 finished with value: 0.2906991608721457 and parameters: {'subsample': 0.16326559473518704, 'dropout_rate': 0.8736174627174981, 'n_estimators': 421, 'learning_rate': 0.07993410500556083}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.26123034714252413
Fold 2 IBS: 0.2609067973308416
Fold 3 IBS: 0.21321387061292466
Fold 4 IBS: 0.2671551183060875
Fold 5 IBS: 0.21942013938279548
[I 2024-04-18 10:37:32,031] Trial 37 finished with value: 0.24438525455503468 and parameters: {'subsample': 0.23660873470356106, 'dropout_rate': 0.7990281623991888, 'n_estimators': 170, 'learning_rate': 0.05621431261796065}. Best is trial 19 with value: 0.18664141445599042.
Fold 1 IBS: 0.2190285825827486

Fold 2 IBS: 0.15485293035522857
Fold 3 IBS: 0.17659534672985133
Fold 4 IBS: 0.19361973277327194
Fold 5 IBS: 0.17914968729881123
[I 2024-04-18 10:37:35,129] Trial 38 finished with value: 0.18464925594798232 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 82, 'learning_rate': 0.0684395247111694}. Best is trial 38 with value: 0.18464925594798232.
Fold 1 IBS: 0.23100212050865962
Fold 2 IBS: 0.17227303252924875
Fold 3 IBS: 0.17930071263516983
Fold 4 IBS: 0.2078210507886513
Fold 5 IBS: 0.178426760992233
[I 2024-04-18 10:37:38,249] Trial 39 finished with value: 0.19376473549079248 and parameters: {'subsample': 0.1669627464432204, 'dropout_rate': 0.11471626893495929, 'n_estimators': 82, 'learning_rate': 0.06892741183938003}. Best is trial 38 with value: 0.18464925594798232.
Fold 1 IBS: 0.26293391629537805
Fold 2 IBS: 0.26589096377274146
Fold 3 IBS: 0.21048479246800744
Fold 4 IBS: 0.27413065442020285
Fold 5 IBS: 0.2161561283186412
[I 2024-04-18 10:37:42,555] Trial 40 finished with value: 0.2459192910549942 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.27073406810212547, 'n_estimators': 112, 'learning_rate': 0.08603457614657108}. Best is trial 38 with value: 0.18464925594798232.
Fold 1 IBS: 0.21657432289526377
Fold 2 IBS: 0.16749931505110885
Fold 3 IBS: 0.16847198520346957
Fold 4 IBS: 0.18845842106744945
Fold 5 IBS: 0.17270787200620508
[I 2024-04-18 10:37:44,916] Trial 41 finished with value: 0.18274238324469935 and parameters: {'subsample': 0.10774190635914782, 'dropout_rate': 0.24159494757459665, 'n_estimators': 58, 'learning_rate': 0.06842845994744125}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21551477796088228
Fold 2 IBS: 0.16785429486434575
Fold 3 IBS: 0.1724394783630873
Fold 4 IBS: 0.20468544573293634
Fold 5 IBS: 0.17526498786966035
[I 2024-04-18 10:37:47,413] Trial 42 finished with value: 0.1871517969581824 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.19807687454956896, 'n_estimators': 64, 'learning_rate': 0.06911254892370094}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2770772575961889
Fold 2 IBS: 0.2567553603812298
Fold 3 IBS: 0.2368193391542929
Fold 4 IBS: 0.24636007415842195
Fold 5 IBS: 0.22894892764850583
[I 2024-04-18 10:37:55,351] Trial 43 finished with value: 0.24919219178772786 and parameters: {'subsample': 0.20979862666572763, 'dropout_rate': 0.21348524642098904, 'n_estimators': 198, 'learning_rate': 0.0726352652201749}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.22625132285378743
Fold 2 IBS: 0.18034915709182123
Fold 3 IBS: 0.17298789638889028
Fold 4 IBS: 0.21623897902897427
Fold 5 IBS: 0.1762998286547805
[I 2024-04-18 10:37:58,141] Trial 44 finished with value: 0.19442543680365074 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.20101401396422397, 'n_estimators': 63, 'learning_rate': 0.06523605428553468}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.250703248932126
Fold 2 IBS: 0.2327276200368743
Fold 3 IBS: 0.19102860976344163
Fold 4 IBS: 0.261793899680034
Fold 5 IBS: 0.1950622481081611
[I 2024-04-18 10:38:01,982] Trial 45 finished with value: 0.22626312530412745 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.295844522167053, 'n_estimators': 96, 'learning_rate': 0.07358829455007394}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2584890253735572
Fold 2 IBS: 0.22294287025925624
Fold 3 IBS: 0.2204453011029163
Fold 4 IBS: 0.2360638286867385
Fold 5 IBS: 0.21391685952834774
[I 2024-04-18 10:38:06,766] Trial 46 finished with value: 0.23037157699016322 and parameters: {'subsample': 0.14485404068604799, 'dropout_rate': 0.3312246704393865, 'n_estimators': 127, 'learning_rate': 0.08365083008051383}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.25976380582220054
Fold 2 IBS: 0.21384336223388178
Fold 3 IBS: 0.21921046069651312
Fold 4 IBS: 0.22761610599545978
Fold 5 IBS: 0.20481901037891456
[I 2024-04-18 10:38:13,691] Trial 47 finished with value: 0.22505054902539395 and parameters: {'subsample': 0.24463732973960714, 'dropout_rate': 0.13911133506878087, 'n_estimators': 175, 'learning_rate': 0.0622210649734474}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20021878793394893
Fold 2 IBS: 0.18474559038593646
Fold 3 IBS: 0.18018416932297632
Fold 4 IBS: 0.19624241914207188
Fold 5 IBS: 0.1906808699100309
[I 2024-04-18 10:38:14,562] Trial 48 finished with value: 0.1904143673389929 and parameters: {'subsample': 0.10041210259629582, 'dropout_rate': 0.19701471782839963, 'n_estimators': 18, 'learning_rate': 0.09182402211019655}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2270096326523487
Fold 2 IBS: 0.1831184285000648
Fold 3 IBS: 0.1717703118423226
Fold 4 IBS: 0.2188258026165814
Fold 5 IBS: 0.17913259215674163
[I 2024-04-18 10:38:17,562] Trial 49 finished with value: 0.1959713535536118 and parameters: {'subsample': 0.317047365475798, 'dropout_rate': 0.4402540309495773, 'n_estimators': 75, 'learning_rate': 0.051717833751605366}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2868131802922175
Fold 2 IBS: 0.24721217475420146
Fold 3 IBS: 0.24834035813593552
Fold 4 IBS: 0.23734922639688621
Fold 5 IBS: 0.2387918963183962
[I 2024-04-18 10:38:26,610] Trial 50 finished with value: 0.25170136717952735 and parameters: {'subsample': 0.1830774219227035, 'dropout_rate': 0.17538138388138197, 'n_estimators': 230, 'learning_rate': 0.07966264522754796}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21472188476186624
Fold 2 IBS: 0.1664682707221826
Fold 3 IBS: 0.17009001084105163
Fold 4 IBS: 0.19135749942698865
Fold 5 IBS: 0.18143910906576896
[I 2024-04-18 10:38:28,622] Trial 51 finished with value: 0.18481535496357163 and parameters: {'subsample': 0.1422401972634589, 'dropout_rate': 0.10079252980319817, 'n_estimators': 49, 'learning_rate': 0.07018211474264216}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21883947972569368
Fold 2 IBS: 0.16777984402915233
Fold 3 IBS: 0.1713276011503002
Fold 4 IBS: 0.1889780574679045
Fold 5 IBS: 0.17721389647037286
[I 2024-04-18 10:38:30,972] Trial 52 finished with value: 0.18482777576868473 and parameters: {'subsample': 0.13494378844422814, 'dropout_rate': 0.10510137537932576, 'n_estimators': 59, 'learning_rate': 0.06926018955996141}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2803863602824494
Fold 2 IBS: 0.20978903030431711
Fold 3 IBS: 0.2478087124322531
Fold 4 IBS: 0.21443616292096518
Fold 5 IBS: 0.24117901195269406
[I 2024-04-18 10:38:42,098] Trial 53 finished with value: 0.23871985557853576 and parameters: {'subsample': 0.14863982748363808, 'dropout_rate': 0.10187914564083042, 'n_estimators': 276, 'learning_rate': 0.0705232778594808}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.22650981409016682
Fold 2 IBS: 0.1809635201008418
Fold 3 IBS: 0.17140755864102677
Fold 4 IBS: 0.2273582210462487
Fold 5 IBS: 0.1755758773667964
[I 2024-04-18 10:38:44,063] Trial 54 finished with value: 0.1963629982490161 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.1495897230999219, 'n_estimators': 49, 'learning_rate': 0.07714657691990995}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20178002616214782
Fold 2 IBS: 0.19749953235815193
Fold 3 IBS: 0.18454601878492333
Fold 4 IBS: 0.20570465598987955
Fold 5 IBS: 0.1995013265108247
[I 2024-04-18 10:38:44,914] Trial 55 finished with value: 0.19780631196118542 and parameters: {'subsample': 0.19569917361738964, 'dropout_rate': 0.25712307227065867, 'n_estimators': 18, 'learning_rate': 0.058792439227992585}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.25122204884813254
Fold 2 IBS: 0.1967966708575003
Fold 3 IBS: 0.20438501795951314
Fold 4 IBS: 0.21600676881230166
Fold 5 IBS: 0.19691399824041494
[I 2024-04-18 10:38:48,979] Trial 56 finished with value: 0.2130649009435725 and parameters: {'subsample': 0.1389398085182404, 'dropout_rate': 0.23034344131063678, 'n_estimators': 103, 'learning_rate': 0.09032997715983931}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2386697075784122

Fold 2 IBS: 0.18988711900964794
Fold 3 IBS: 0.18367267394166958
Fold 4 IBS: 0.2230944303345007
Fold 5 IBS: 0.17950851621397682
[I 2024-04-18 10:38:52,034] Trial 57 finished with value: 0.20296648941564147 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.16382075159292628, 'n_estimators': 81, 'learning_rate': 0.07586937026396535}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20634292358637418
Fold 2 IBS: 0.17337935278269065
Fold 3 IBS: 0.17241359892116032
Fold 4 IBS: 0.20871385178528976
Fold 5 IBS: 0.18044495600331506
[I 2024-04-18 10:38:53,941] Trial 58 finished with value: 0.188258936615766 and parameters: {'subsample': 0.23747712467318813, 'dropout_rate': 0.12541109823464971, 'n_estimators': 48, 'learning_rate': 0.06314379319286169}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20480041983690422
Fold 2 IBS: 0.20390707070173544
Fold 3 IBS: 0.19195122718180715
Fold 4 IBS: 0.21034367609481147
Fold 5 IBS: 0.2052520861846158
[I 2024-04-18 10:38:54,712] Trial 59 finished with value: 0.2032508959999748 and parameters: {'subsample': 0.1414512573936176, 'dropout_rate': 0.33799719021891794, 'n_estimators': 15, 'learning_rate': 0.04739254727118543}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.25075372969213366
Fold 2 IBS: 0.22032136926567789
Fold 3 IBS: 0.2061338052146449
Fold 4 IBS: 0.21766339555255132
Fold 5 IBS: 0.19822023368930092
[I 2024-04-18 10:39:00,176] Trial 60 finished with value: 0.21861850668286173 and parameters: {'subsample': 0.17737200154075605, 'dropout_rate': 0.23691479339743635, 'n_estimators': 134, 'learning_rate': 0.07018729343441713}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2098610684488183
Fold 2 IBS: 0.15994361314450345
Fold 3 IBS: 0.17371802287590823
Fold 4 IBS: 0.20249781736357833
Fold 5 IBS: 0.17465913731165042
[I 2024-04-18 10:39:02,662] Trial 61 finished with value: 0.18413593182889174 and parameters: {'subsample': 0.12412751215332855, 'dropout_rate': 0.17157804364515114, 'n_estimators': 64, 'learning_rate': 0.06622321266742605}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2158276559796518
Fold 2 IBS: 0.1637033059641003
Fold 3 IBS: 0.1755720635774005
Fold 4 IBS: 0.19910627403772732
Fold 5 IBS: 0.177402404516405
[I 2024-04-18 10:39:05,316] Trial 62 finished with value: 0.186322340815057 and parameters: {'subsample': 0.13014054645688122, 'dropout_rate': 0.17387134679643484, 'n_estimators': 66, 'learning_rate': 0.07275892105863323}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.230443077154835
Fold 2 IBS: 0.1706179878807673
Fold 3 IBS: 0.18626986491067532
Fold 4 IBS: 0.21123885345069682
Fold 5 IBS: 0.1823916474479526
[I 2024-04-18 10:39:08,747] Trial 63 finished with value: 0.1961922861689854 and parameters: {'subsample': 0.1277375930647463, 'dropout_rate': 0.1789611209146567, 'n_estimators': 89, 'learning_rate': 0.0737068174232921}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2083717997214503
Fold 2 IBS: 0.16551362924298296
Fold 3 IBS: 0.17217381769936008
Fold 4 IBS: 0.19891007544143505
Fold 5 IBS: 0.1794361304703944
[I 2024-04-18 10:39:10,245] Trial 64 finished with value: 0.18488109051512455 and parameters: {'subsample': 0.20847418802896328, 'dropout_rate': 0.1014007673360085, 'n_estimators': 36, 'learning_rate': 0.08254679911822728}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21450844329547666
Fold 2 IBS: 0.17025493143840517
Fold 3 IBS: 0.17132019201531
Fold 4 IBS: 0.19402172406389004
Fold 5 IBS: 0.18009578335375184
[I 2024-04-18 10:39:11,700] Trial 65 finished with value: 0.18604021483336677 and parameters: {'subsample': 0.20862771646674866, 'dropout_rate': 0.13362798468456988, 'n_estimators': 35, 'learning_rate': 0.08254556029157334}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21080186459747924
Fold 2 IBS: 0.17158263022327253
Fold 3 IBS: 0.17455534661927036
Fold 4 IBS: 0.19226660513055374
Fold 5 IBS: 0.18443243167498746
[I 2024-04-18 10:39:12,819] Trial 66 finished with value: 0.18672777564911267 and parameters: {'subsample': 0.21995641524120108, 'dropout_rate': 0.13515518146247796, 'n_estimators': 25, 'learning_rate': 0.09865900576192115}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.30172651529717337
Fold 2 IBS: 0.23380738899153833
Fold 3 IBS: 0.26184502876794047
Fold 4 IBS: 0.2368478091361797
Fold 5 IBS: 0.2586280623445004
[I 2024-04-18 10:39:25,778] Trial 67 finished with value: 0.2585709609074665 and parameters: {'subsample': 0.1966838365000182, 'dropout_rate': 0.1060128908354952, 'n_estimators': 321, 'learning_rate': 0.08301164757501235}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21276679704468363
Fold 2 IBS: 0.21872627089632152
Fold 3 IBS: 0.202546384571557
Fold 4 IBS: 0.22200033468305125
Fold 5 IBS: 0.2161686650700266
[I 2024-04-18 10:39:26,007] Trial 68 finished with value: 0.21444169045312797 and parameters: {'subsample': 0.2611102871934394, 'dropout_rate': 0.13074151149938334, 'n_estimators': 1, 'learning_rate': 0.08923970289763425}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21504708165959094
Fold 2 IBS: 0.1868583288275312
Fold 3 IBS: 0.17240178583671936
Fold 4 IBS: 0.20630919225899946
Fold 5 IBS: 0.18366928429032212
[I 2024-04-18 10:39:27,388] Trial 69 finished with value: 0.19285713457463263 and parameters: {'subsample': 0.37099887409006427, 'dropout_rate': 0.28002836414714494, 'n_estimators': 32, 'learning_rate': 0.07937088341668852}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21831401781445603
Fold 2 IBS: 0.17350816917570044
Fold 3 IBS: 0.17150489080008327
Fold 4 IBS: 0.2082493002559466
Fold 5 IBS: 0.1768011818786599
[I 2024-04-18 10:39:29,061] Trial 70 finished with value: 0.18967551198496924 and parameters: {'subsample': 0.32616677464604515, 'dropout_rate': 0.14958198460133657, 'n_estimators': 41, 'learning_rate': 0.0828608852485162}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21251396502984748
Fold 2 IBS: 0.15766467058626749
Fold 3 IBS: 0.17476107996989199
Fold 4 IBS: 0.20398278941468684
Fold 5 IBS: 0.17882478498748058
[I 2024-04-18 10:39:31,768] Trial 71 finished with value: 0.18554945799763486 and parameters: {'subsample': 0.1222292066458504, 'dropout_rate': 0.16846746652817096, 'n_estimators': 70, 'learning_rate': 0.06459588188931031}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21247991216904086
Fold 2 IBS: 0.18258490039234654
Fold 3 IBS: 0.17087344118625059
Fold 4 IBS: 0.1973262603691105
Fold 5 IBS: 0.1805420354598957
[I 2024-04-18 10:39:33,754] Trial 72 finished with value: 0.18876130991532883 and parameters: {'subsample': 0.18525815338996277, 'dropout_rate': 0.23073990396161775, 'n_estimators': 51, 'learning_rate': 0.058994688574399226}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.23046024125183262
Fold 2 IBS: 0.16588705974008025
Fold 3 IBS: 0.18438381412712623
Fold 4 IBS: 0.19159301129800185
Fold 5 IBS: 0.1815331681085751
[I 2024-04-18 10:39:37,802] Trial 73 finished with value: 0.1907714589051232 and parameters: {'subsample': 0.12518928081260391, 'dropout_rate': 0.10552636025337211, 'n_estimators': 105, 'learning_rate': 0.06538142077437695}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.29419283411158037
Fold 2 IBS: 0.3169376555509431
Fold 3 IBS: 0.2565243921120244
Fold 4 IBS: 0.292906768595851
Fold 5 IBS: 0.26096648837698533
[I 2024-04-18 10:39:53,649] Trial 74 finished with value: 0.2843056277494768 and parameters: {'subsample': 0.7948212261000067, 'dropout_rate': 0.15465871157024105, 'n_estimators': 386, 'learning_rate': 0.052963558596525434}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2611064444801387
Fold 2 IBS: 0.21661345981768176
Fold 3 IBS: 0.22579836843162185
Fold 4 IBS: 0.2193188014405319
Fold 5 IBS: 0.2179034783639422
[I 2024-04-18 10:40:00,206] Trial 75 finished with value: 0.2281481105067833 and parameters: {'subsample': 0.16474431352208974, 'dropout_rate': 0.18039715265941558, 'n_estimators': 160, 'learning_rate': 0.0763202122099443}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.23851415707934473

Fold 2 IBS: 0.17890097671682756
Fold 3 IBS: 0.19536496805641376
Fold 4 IBS: 0.21719928241327136
Fold 5 IBS: 0.18349965984241834
[I 2024-04-18 10:40:04,627] Trial 76 finished with value: 0.20269580882165514 and parameters: {'subsample': 0.22021500853091197, 'dropout_rate': 0.1008354138446842, 'n_estimators': 117, 'learning_rate': 0.0643383103937687}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.24744280167222407
Fold 2 IBS: 0.22862663422765966
Fold 3 IBS: 0.18728302309225137
Fold 4 IBS: 0.25910034960984574
Fold 5 IBS: 0.18874406010330383
[I 2024-04-18 10:40:07,434] Trial 77 finished with value: 0.22223937374105693 and parameters: {'subsample': 0.5460655482305514, 'dropout_rate': 0.30077557647360864, 'n_estimators': 74, 'learning_rate': 0.08757704932309289}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20798081275670857
Fold 2 IBS: 0.1734898627587147
Fold 3 IBS: 0.1721656544303873
Fold 4 IBS: 0.18867276746479647
Fold 5 IBS: 0.18207785958983425
[I 2024-04-18 10:40:09,147] Trial 78 finished with value: 0.18487739140008824 and parameters: {'subsample': 0.12830903093683488, 'dropout_rate': 0.21479998057844538, 'n_estimators': 38, 'learning_rate': 0.06719882402777246}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20301192221540806
Fold 2 IBS: 0.20066845682897044
Fold 3 IBS: 0.18978399013827169
Fold 4 IBS: 0.20661600026721727
Fold 5 IBS: 0.20151435259453646
[I 2024-04-18 10:40:09,816] Trial 79 finished with value: 0.2003189444088808 and parameters: {'subsample': 0.12663847680176757, 'dropout_rate': 0.24810144195381617, 'n_estimators': 13, 'learning_rate': 0.0675797342320268}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2299257284132334
Fold 2 IBS: 0.18731630969023752
Fold 3 IBS: 0.17850362228398556
Fold 4 IBS: 0.21034817749540835
Fold 5 IBS: 0.17719164673968021
[I 2024-04-18 10:40:13,438] Trial 80 finished with value: 0.196657096924509 and parameters: {'subsample': 0.1642447757921439, 'dropout_rate': 0.21625393265522744, 'n_estimators': 94, 'learning_rate': 0.05939168154420546}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2009265681654403
Fold 2 IBS: 0.16943117433885913
Fold 3 IBS: 0.17312788757378864
Fold 4 IBS: 0.18929574933606813
Fold 5 IBS: 0.18370383969688883
[I 2024-04-18 10:40:14,974] Trial 81 finished with value: 0.18329704382220902 and parameters: {'subsample': 0.11751769733053564, 'dropout_rate': 0.12494005203793415, 'n_estimators': 37, 'learning_rate': 0.06961174970330175}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20756664684315548
Fold 2 IBS: 0.15910832866947228
Fold 3 IBS: 0.172534186436786
Fold 4 IBS: 0.20041897725892355
Fold 5 IBS: 0.1755005682066174
[I 2024-04-18 10:40:17,138] Trial 82 finished with value: 0.18302574148299094 and parameters: {'subsample': 0.1259169381669261, 'dropout_rate': 0.19718664746532225, 'n_estimators': 55, 'learning_rate': 0.07070406160015724}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2126150907045733
Fold 2 IBS: 0.16028973708614472
Fold 3 IBS: 0.17289372467098912
Fold 4 IBS: 0.19427855472360467
Fold 5 IBS: 0.1768893277974488
[I 2024-04-18 10:40:19,332] Trial 83 finished with value: 0.1833932869965521 and parameters: {'subsample': 0.1022824556934966, 'dropout_rate': 0.19205257028215844, 'n_estimators': 57, 'learning_rate': 0.0692402614218835}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.314811129128064
Fold 2 IBS: 0.30236864595017454
Fold 3 IBS: 0.27331907754983087
Fold 4 IBS: 0.24597940086963438
Fold 5 IBS: 0.2619813661187944
[I 2024-04-18 10:40:40,242] Trial 84 finished with value: 0.27969192392329967 and parameters: {'subsample': 0.1492145635538761, 'dropout_rate': 0.1953987727678687, 'n_estimators': 494, 'learning_rate': 0.07120157128485054}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2151104704081691
Fold 2 IBS: 0.17210310616132568
Fold 3 IBS: 0.17159868805795075
Fold 4 IBS: 0.18943209251474535
Fold 5 IBS: 0.17709649946447154
[I 2024-04-18 10:40:42,578] Trial 85 finished with value: 0.18506817132133252 and parameters: {'subsample': 0.11162862285140873, 'dropout_rate': 0.3790019535348362, 'n_estimators': 57, 'learning_rate': 0.06868688620686979}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.22983428775346432
Fold 2 IBS: 0.19448375574294327
Fold 3 IBS: 0.1830778676364074
Fold 4 IBS: 0.21230135864508634
Fold 5 IBS: 0.1809177881278236
[I 2024-04-18 10:40:45,850] Trial 86 finished with value: 0.20012301158114498 and parameters: {'subsample': 0.17453775921296422, 'dropout_rate': 0.22070112000289366, 'n_estimators': 85, 'learning_rate': 0.07439492892944843}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.30630684761232174
Fold 2 IBS: 0.28164949529820726
Fold 3 IBS: 0.264211126697855
Fold 4 IBS: 0.23896537672841572
Fold 5 IBS: 0.2566132253924063
[I 2024-04-18 10:41:06,094] Trial 87 finished with value: 0.2695492143458412 and parameters: {'subsample': 0.10108685694468394, 'dropout_rate': 0.3053581187990048, 'n_estimators': 472, 'learning_rate': 0.06102757815226058}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.2163944629618701
Fold 2 IBS: 0.17285455003299374
Fold 3 IBS: 0.17338019041045852
Fold 4 IBS: 0.19194155895791737
Fold 5 IBS: 0.1760423609484188
[I 2024-04-18 10:41:08,249] Trial 88 finished with value: 0.18612262466233168 and parameters: {'subsample': 0.14757588447433856, 'dropout_rate': 0.27179751729411666, 'n_estimators': 55, 'learning_rate': 0.06677876993166124}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.19921849106938283
Fold 2 IBS: 0.1817447025642902
Fold 3 IBS: 0.1787845804504237
Fold 4 IBS: 0.2045449094849751
Fold 5 IBS: 0.19129005832937776
[I 2024-04-18 10:41:09,350] Trial 89 finished with value: 0.1911165483796899 and parameters: {'subsample': 0.12427008340735567, 'dropout_rate': 0.1531084903888203, 'n_estimators': 25, 'learning_rate': 0.07161714364271923}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.22239526730989972
Fold 2 IBS: 0.18503360016459933
Fold 3 IBS: 0.1707304842213745
Fold 4 IBS: 0.2183491202550978
Fold 5 IBS: 0.1759649334193279
[I 2024-04-18 10:41:11,157] Trial 90 finished with value: 0.19449468107405984 and parameters: {'subsample': 0.5137142772195739, 'dropout_rate': 0.19096786691411238, 'n_estimators': 44, 'learning_rate': 0.07501407788997974}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.20552311084701758
Fold 2 IBS: 0.1735059761797674
Fold 3 IBS: 0.17234604821170185
Fold 4 IBS: 0.20043217837601449
Fold 5 IBS: 0.18099728957797295
[I 2024-04-18 10:41:12,668] Trial 91 finished with value: 0.18656092063849483 and parameters: {'subsample': 0.19176293742026304, 'dropout_rate': 0.12601851290186392, 'n_estimators': 36, 'learning_rate': 0.07785438400302604}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.205561552785052
Fold 2 IBS: 0.2045762620758311
Fold 3 IBS: 0.1916206652466707
Fold 4 IBS: 0.20847793650522572
Fold 5 IBS: 0.20884034626864031
[I 2024-04-18 10:41:13,222] Trial 92 finished with value: 0.20381535257628394 and parameters: {'subsample': 0.15096941818034873, 'dropout_rate': 0.11957703453224162, 'n_estimators': 10, 'learning_rate': 0.06924164854216225}. Best is trial 41 with value: 0.18274238324469935.
Fold 1 IBS: 0.21372410654951762
Fold 2 IBS: 0.1670240178968644
Fold 3 IBS: 0.1687678549855829
Fold 4 IBS: 0.1873801388956979
Fold 5 IBS: 0.1758613752096379
[I 2024-04-18 10:41:15,820] Trial 93 finished with value: 0.18255149870746018 and parameters: {'subsample': 0.10192538954917617, 'dropout_rate': 0.20721101622638877, 'n_estimators': 64, 'learning_rate': 0.06253585066540067}. Best is trial 93 with value: 0.18255149870746018.
Fold 1 IBS: 0.21536046761177843
Fold 2 IBS: 0.16486509652431344
Fold 3 IBS: 0.16967824737723444
Fold 4 IBS: 0.1977165493953684
Fold 5 IBS: 0.17499013244971903
[I 2024-04-18 10:41:18,653] Trial 94 finished with value: 0.18452209867168276 and parameters: {'subsample': 0.10169871171063773, 'dropout_rate': 0.21138505274077363, 'n_estimators': 74, 'learning_rate': 0.057140104902774075}. Best is trial 93 with value: 0.18255149870746018.
Fold 1 IBS: 0.2109430096817562

Fold 2 IBS: 0.17190807267658803
Fold 3 IBS: 0.17273953146414783
Fold 4 IBS: 0.18418892924429342
Fold 5 IBS: 0.17339219691878366
[I 2024-04-18 10:41:21,610] Trial 95 finished with value: 0.1826343479971138 and parameters: {'subsample': 0.10055428912475185, 'dropout_rate': 0.255316498372642, 'n_estimators': 78, 'learning_rate': 0.05738254220979494}. Best is trial 93 with value: 0.18255149870746018.
Fold 1 IBS: 0.22219594223226996
Fold 2 IBS: 0.16732409973069712
Fold 3 IBS: 0.1737554070832707
Fold 4 IBS: 0.19390980198895558
Fold 5 IBS: 0.17438128613481677
[I 2024-04-18 10:41:25,443] Trial 96 finished with value: 0.186313307434002 and parameters: {'subsample': 0.1009094963377387, 'dropout_rate': 0.23698793453295677, 'n_estimators': 101, 'learning_rate': 0.054487916689644846}. Best is trial 93 with value: 0.18255149870746018.
Fold 1 IBS: 0.21781474091983286
Fold 2 IBS: 0.17670930555589828
Fold 3 IBS: 0.17432999009881028
Fold 4 IBS: 0.19666863451181552
Fold 5 IBS: 0.17220960871465493
[I 2024-04-18 10:41:28,358] Trial 97 finished with value: 0.18754645596020236 and parameters: {'subsample': 0.16484489435977595, 'dropout_rate': 0.25722879205355936, 'n_estimators': 75, 'learning_rate': 0.05810785621442836}. Best is trial 93 with value: 0.18255149870746018.
Fold 1 IBS: 0.24602051374380035
Fold 2 IBS: 0.2303434017869567
Fold 3 IBS: 0.1846031519469023
Fold 4 IBS: 0.2621556209640574
Fold 5 IBS: 0.2076400466121024
[I 2024-04-18 10:41:32,969] Trial 98 finished with value: 0.22615254701076384 and parameters: {'subsample': 0.6256495106817341, 'dropout_rate': 0.4429518977207014, 'n_estimators': 121, 'learning_rate': 0.050476352342096784}. Best is trial 93 with value: 0.18255149870746018.
Fold 1 IBS: 0.23184118908835216
Fold 2 IBS: 0.18140920840967706
Fold 3 IBS: 0.17902054838458506
Fold 4 IBS: 0.2114783875163553
Fold 5 IBS: 0.17792373263623162
[I 2024-04-18 10:41:36,042] Trial 99 finished with value: 0.19633461320704024 and parameters: {'subsample': 0.11763203700731269, 'dropout_rate': 0.5045357370668048, 'n_estimators': 81, 'learning_rate': 0.06310358997724173}. Best is trial 93 with value: 0.18255149870746018.


* Best trial for IBS:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.18255149870746018], datetime_start=datetime.datetime(2024, 4, 18, 10, 41, 13, 225276), datetime_complete=datetime.datetime(2024, 4, 18, 10, 41, 15, 820373), params={'subsample': 0.10192538954917617, 'dropout_rate': 0.20721101622638877, 'n_estimators': 64, 'learning_rate': 0.06253585066540067}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=93, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10192538954917617, 'dropout_rate': 0.20721101622638877, 'n_estimators': 64, 'learning_rate': 0.06253585066540067}


* Best Score for IBS:
 0.18255149870746018

In [73]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [74]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.731
train_ibs:  0.183

#### Test

In [75]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [76]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10580803679784617,
                                              learning_rate=0.08933703080421439,
                                              n_estimators=324,
                                              random_state=123,
                                              subsample=0.11557957726835853)

C-index score: 0.586

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.20721101622638877,
                                              learning_rate=0.06253585066540067,
                                              n_estimators=64, random_state=123,
                                              subsample=0.10192538954917617)

IBS: 0.232

In [77]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [78]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.886   1.0
Randomsurvivalforest             0.864   2.0
GradientBoosting                 0.758   3.0
ComponentwiseGradientBoosting    0.731   4.0
CoxElastic                       0.729   5.0
CoxRidge                         0.712   6.0
CoxLasso                         0.592   7.0

In [79]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.179   1.0
Randomsurvivalforest           0.183   2.5
ComponentwiseGradientBoosting  0.183   2.5
GradientBoosting               0.208   4.0
CoxElastic                     0.211   5.0
CoxRidge                       0.217   6.0
CoxLasso                       0.362   7.0

In [80]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.662   1.0
Randomsurvivalforest             0.629   2.0
GradientBoosting                 0.618   3.0
CoxElastic                       0.590   4.0
CoxRidge                         0.586   5.5
ComponentwiseGradientBoosting    0.586   5.5
CoxLasso                         0.541   7.0

In [81]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.200   1.0
Randomsurvivalforest           0.205   2.0
GradientBoosting               0.213   3.0
CoxRidge                       0.221   4.5
CoxElastic                     0.221   4.5
ComponentwiseGradientBoosting  0.232   6.0
CoxLasso                       0.442   7.0

In [82]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/standard/no_selection/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_standard_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [83]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-18