In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [9]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [12]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [13]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [14]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [15]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [16]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

### COX PLSR

In [20]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"uicc8_III-IV",
"cavum_oris",
"hpv_related",
"charlson",
"hypopharynx",
"shape_MajorAxisLength",
"LBP_120_PET"   
]

In [21]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [22]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [23]:
# Copy the original X for later 
original_X = X.copy()

In [24]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [25]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [26]:
X_new

,uicc8_III-IV,cavum_oris,hpv_related,charlson,hypopharynx,shape_MajorAxisLength,LBP_120_PET
0,0.0,0,0.0,0,0,42.073251,0.140311
1,0.0,0,0.0,1,0,24.613845,0.191058
2,1.0,1,0.0,1,0,48.030294,0.126531
3,0.0,0,0.0,1,0,25.589900,0.192388
4,0.0,0,0.0,1,0,34.684750,0.202073
...,...,...,...,...,...,...,...
134,0.0,0,1.0,0,0,33.069705,0.152626
135,1.0,0,1.0,0,0,41.043692,0.142778
136,0.0,0,1.0,1,0,36.618802,0.140582
137,1.0,0,1.0,1,0,45.870392,0.156640
138,1.0,0,1.0,0,0,30.363259,0.147644

In [27]:
X_new_std

,uicc8_III-IV,cavum_oris,hpv_related,charlson,hypopharynx,shape_MajorAxisLength,LBP_120_PET
0,0.0,0,0.0,0,0,-0.098422,-0.476493
1,0.0,0,0.0,1,0,-1.209119,1.084993
2,1.0,1,0.0,1,0,0.280542,-0.900502
3,0.0,0,0.0,1,0,-1.147026,1.125919
4,0.0,0,0.0,1,0,-0.568449,1.423898
...,...,...,...,...,...,...,...
134,0.0,0,1.0,0,0,-0.671191,-0.097562
135,1.0,0,1.0,0,0,-0.163918,-0.400566
136,0.0,0,1.0,1,0,-0.445412,-0.468144
137,1.0,0,1.0,1,0,0.143137,0.025938
138,1.0,0,1.0,0,0,-0.843364,-0.250857

In [28]:
MAASTRO_new

,uicc8_III-IV,cavum_oris,hpv_related,charlson,hypopharynx,shape_MajorAxisLength,LBP_120_PET
0,0,0,1,1,0,50.002093,0.122209
1,1,0,0,0,0,41.753334,0.128976
2,1,0,0,1,0,44.375483,0.137282
3,1,0,0,1,0,46.115989,0.171595
4,0,0,1,1,0,54.394967,0.128134
...,...,...,...,...,...,...,...
94,1,0,0,0,0,34.218615,0.137194
95,1,0,0,1,0,51.046869,0.137620
96,1,0,1,1,0,50.417953,0.115099
97,0,0,1,0,0,44.901412,0.117654
98,1,0,0,0,1,36.574294,0.156924

In [29]:
MAASTRO_new_std

,uicc8_III-IV,cavum_oris,hpv_related,charlson,hypopharynx,shape_MajorAxisLength,LBP_120_PET
0,0,0,1,1,0,0.405980,-1.033478
1,1,0,0,0,0,-0.118774,-0.825249
2,1,0,0,1,0,0.048037,-0.569695
3,1,0,0,1,0,0.158761,0.486120
4,0,0,1,1,0,0.685437,-0.851180
...,...,...,...,...,...,...,...
94,1,0,0,0,0,-0.598102,-0.572399
95,1,0,0,1,0,0.472444,-0.559284
96,1,0,1,1,0,0.432435,-1.252248
97,0,0,1,0,0,0.081495,-1.173644
98,1,0,0,0,1,-0.448243,0.034704

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [30]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:19:43,616] A new study created in memory with name: no-name-3d30eda4-3c50-425e-99ae-8c505c81cec0
python(7352) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8059071729957806

[I 2024-04-18 03:19:51,799] A new study created in memory with name: no-name-efdd777f-1870-47bb-ae30-5097ad05994c

Fold 5 C-index: 0.704225352112676
[I 2024-04-18 03:19:51,644] Trial 0 finished with value: 0.7784525299771281 and parameters: {}. Best is trial 0 with value: 0.7784525299771281.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7784525299771281], datetime_start=datetime.datetime(2024, 4, 18, 3, 19, 43, 805461), datetime_complete=datetime.datetime(2024, 4, 18, 3, 19, 51, 642687), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7784525299771281

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16762996230119587
Fold 2 IBS: 0.16471344311707362
Fold 3 IBS: 0.12271184148213712
Fold 4 IBS: 0.15606953244496122
Fold 5 IBS: 0.23145868866366215
[I 2024-04-18 03:19:53,146] Trial 0 finished with value: 0.168516693601806 and parameters: {}. Best is trial 0 with value: 0.168516693601806.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.168516693601806], datetime_start=datetime.datetime(2024, 4, 18, 3, 19, 51, 853954), datetime_complete=datetime.datetime(2024, 4, 18, 3, 19, 53, 145691), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.168516693601806

In [31]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [32]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.778
train_ibs:  0.169

#### Test

In [33]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [34]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.62
IBS score: 0.232

In [35]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [36]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [37]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:19:53,935] A new study created in memory with name: no-name-caa722ee-449e-4b9e-a709-2579d62d5ab8

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5692640692640693
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6643192488262911
[I 2024-04-18 03:19:54,569] Trial 0 finished with value: 0.6813317754856039 and parameters: {}. Best is trial 0 with value: 0.6813317754856039.

[I 2024-04-18 03:19:54,644] A new study created in memory with name: no-name-619f2f12-db38-407b-848c-13bdfcc54a72

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6813317754856039], datetime_start=datetime.datetime(2024, 4, 18, 3, 19, 54, 211271), datetime_complete=datetime.datetime(2024, 4, 18, 3, 19, 54, 564333), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6813317754856039

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.213976519404854
Fold 2 IBS: 0.22157790763480684
Fold 3 IBS: 0.20453594247607443
Fold 4 IBS: 0.22473803447097768
Fold 5 IBS: 0.21812430841953245
[I 2024-04-18 03:19:55,089] Trial 0 finished with value: 0.21659054248124904 and parameters: {}. Best is trial 0 with value: 0.21659054248124904.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054248124904], datetime_start=datetime.datetime(2024, 4, 18, 3, 19, 54, 698874), datetime_complete=datetime.datetime(2024, 4, 18, 3, 19, 55, 88817), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054248124904

In [38]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [39]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.681
train_ibs:  0.217

#### Test

In [40]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [41]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.578

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [42]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [43]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:19:55,641] A new study created in memory with name: no-name-0ed37a46-4fae-4f04-a0c1-1bad96c68fa1

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272

[I 2024-04-18 03:19:56,694] A new study created in memory with name: no-name-9ae24dd1-c760-4c8c-b002-ba2ea66da00e

[I 2024-04-18 03:19:56,633] Trial 0 finished with value: 0.7787548788296013 and parameters: {}. Best is trial 0 with value: 0.7787548788296013.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7787548788296013], datetime_start=datetime.datetime(2024, 4, 18, 3, 19, 55, 837424), datetime_complete=datetime.datetime(2024, 4, 18, 3, 19, 56, 628172), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7787548788296013

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16849796886747778
Fold 2 IBS: 0.1659079675044365
Fold 3 IBS: 0.12315202765362111
Fold 4 IBS: 0.15530953920397786
Fold 5 IBS: 0.2301462993017957
[I 2024-04-18 03:19:58,210] Trial 0 finished with value: 0.1686027605062618 and parameters: {}. Best is trial 0 with value: 0.1686027605062618.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1686027605062618], datetime_start=datetime.datetime(2024, 4, 18, 3, 19, 56, 878079), datetime_complete=datetime.datetime(2024, 4, 18, 3, 19, 58, 209721), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1686027605062618

In [44]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [45]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.779
train_ibs:  0.169

#### Test

In [46]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [47]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.623

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.23

In [48]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [49]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:19:58,978] A new study created in memory with name: no-name-98610998-ad5a-44f7-95db-7003182888bc

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:19:59,928] Trial 0 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:00,877] Trial 1 finished with value: 0.7777744866727385 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:01,695] Trial 2 finished with value: 0.7786402875385393 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:02,221] Trial 3 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:02,704] Trial 4 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:03,206] Trial 5 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:04,196] Trial 6 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:05,045] Trial 7 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:05,656] Trial 8 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:07,307] Trial 9 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:08,303] Trial 10 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:09,755] Trial 11 finished with value: 0.7795331446813965 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:10,667] Trial 12 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6978253640763652}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:11,466] Trial 13 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6189362712539238}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:12,252] Trial 14 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.8403787283021946}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:13,265] Trial 15 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5892251114089379}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:14,058] Trial 16 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.8361111870922124}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:14,925] Trial 17 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5632480038685016}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:16,053] Trial 18 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:17,313] Trial 19 finished with value: 0.7786402875385393 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:19,609] Trial 20 finished with value: 0.7786402875385393 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:21,762] Trial 21 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7501344475278824}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:23,667] Trial 22 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5339346419626306}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:25,545] Trial 23 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.651954326927192}. Best is trial 0 with value: 0.7796477359724584.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:27,667] Trial 24 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7602371709740536}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:29,429] Trial 25 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.891573855041803}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:31,428] Trial 26 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4514399534035586}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:33,188] Trial 27 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7284175098086105}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:34,870] Trial 28 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:36,456] Trial 29 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5124352690792928}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:38,714] Trial 30 finished with value: 0.7777744866727385 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:40,597] Trial 31 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4334765079491672}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:42,129] Trial 32 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.581548935880325}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:43,643] Trial 33 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6422195303308569}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:45,710] Trial 34 finished with value: 0.7786402875385393 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:47,094] Trial 35 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.8983450253651932}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:48,494] Trial 36 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.3943060631899279}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:50,301] Trial 37 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.46903042572039566}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:51,789] Trial 38 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6738682445636226}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:53,002] Trial 39 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:54,803] Trial 40 finished with value: 0.7786402875385393 and parameters: {'l1_ratio': 0.2705989592091768}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:56,234] Trial 41 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7030105763086383}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:57,475] Trial 42 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7827902122822616}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:20:58,948] Trial 43 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6180367694054894}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:00,126] Trial 44 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5113612245785202}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:01,653] Trial 45 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.901056443031998}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:02,674] Trial 46 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6817738480131094}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:03,820] Trial 47 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6172977577965739}. Best is trial 0 with value: 0.7796477359724584.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:04,969] Trial 48 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.40176254986805804}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:06,151] Trial 49 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.8313598689405559}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:07,357] Trial 50 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7120258016641781}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:08,736] Trial 51 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4722972713246425}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:10,033] Trial 52 finished with value: 0.7777744866727385 and parameters: {'l1_ratio': 0.3283531492596409}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:11,089] Trial 53 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5491522307742125}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:12,169] Trial 54 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7861368442620134}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:13,144] Trial 55 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4869847395037336}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:14,207] Trial 56 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5921973417269037}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:21:14,650] Trial 57 finished with value: 0.6818827456832424 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:15,706] Trial 58 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.41962963118866753}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:16,657] Trial 59 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.3635438827822911}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:17,761] Trial 60 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7391257615529055}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:18,906] Trial 61 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.667356569484989}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:20,240] Trial 62 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6337675904679029}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:22,555] Trial 63 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5934987209281829}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:23,786] Trial 64 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.8667587619507223}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:25,083] Trial 65 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7670647797109651}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:26,405] Trial 66 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6973035696814532}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:27,309] Trial 67 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.9546530799943637}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:28,085] Trial 68 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5277275595022933}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:29,384] Trial 69 finished with value: 0.7786402875385393 and parameters: {'l1_ratio': 0.18942581039571943}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:30,351] Trial 70 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4480138814991342}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:31,603] Trial 71 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6626998967886925}. Best is trial 0 with value: 0.7796477359724584.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:32,704] Trial 72 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7240388219208541}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:34,217] Trial 73 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5735196896559691}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:36,029] Trial 74 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6183094102771696}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:37,118] Trial 75 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.806353235851837}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:38,461] Trial 76 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5374826755773051}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:40,077] Trial 77 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6484973250495103}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:41,461] Trial 78 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.496020322222786}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:42,816] Trial 79 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7396517497367692}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:44,245] Trial 80 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6874268704643649}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:45,743] Trial 81 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.8557701214912001}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:47,074] Trial 82 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.8152949729690657}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:48,544] Trial 83 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5950201763917966}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:49,767] Trial 84 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.713993622024526}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:51,358] Trial 85 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7576311672712572}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:52,926] Trial 86 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.9346304162749919}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:55,805] Trial 87 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6326214735656623}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:57,485] Trial 88 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.43715641771561975}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:21:58,996] Trial 89 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5651145889402991}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:00,723] Trial 90 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.7797464722784435}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:02,501] Trial 91 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5248601844416229}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:04,288] Trial 92 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.4763757789448801}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:06,092] Trial 93 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6097930352815754}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:07,557] Trial 94 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6749073042731822}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:08,983] Trial 95 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.647048561691711}. Best is trial 0 with value: 0.7796477359724584.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:10,244] Trial 96 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.6947055605210477}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:11,836] Trial 97 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5549395198142241}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:13,672] Trial 98 finished with value: 0.7787548788296013 and parameters: {'l1_ratio': 0.37364139398534685}. Best is trial 0 with value: 0.7796477359724584.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8059071729957806

[I 2024-04-18 03:22:15,595] A new study created in memory with name: no-name-f265670b-1634-42da-a4c7-b2eca0443b96

Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:22:15,585] Trial 99 finished with value: 0.7796477359724584 and parameters: {'l1_ratio': 0.5050651579887039}. Best is trial 0 with value: 0.7796477359724584.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7796477359724584], datetime_start=datetime.datetime(2024, 4, 18, 3, 19, 59, 80983), datetime_complete=datetime.datetime(2024, 4, 18, 3, 19, 59, 927942), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.7796477359724584

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16844173638213747
Fold 2 IBS: 0.16515999724040445
Fold 3 IBS: 0.1230674092004973
Fold 4 IBS: 0.15532968544182732
Fold 5 IBS: 0.22987092445957294
[I 2024-04-18 03:22:17,948] Trial 0 finished with value: 0.16837395054488788 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.16837395054488788.
Fold 1 IBS: 0.16840948858106042
Fold 2 IBS: 0.1637108842507164
Fold 3 IBS: 0.12290243936655076
Fold 4 IBS: 0.15552587898929446
Fold 5 IBS: 0.2290849133112781
[I 2024-04-18 03:22:19,800] Trial 1 finished with value: 0.16792672089978003 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.16792672089978003.
Fold 1 IBS: 0.16837583795884792
Fold 2 IBS: 0.1634444033419204
Fold 3 IBS: 0.12285330672189478
Fold 4 IBS: 0.15553401964446517
Fold 5 IBS: 0.2289892533206302
[I 2024-04-18 03:22:22,068] Trial 2 finished with value: 0.1678393641975517 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.1684426111133879
Fold 2 IBS: 0.16471216317308093
Fold 3 IBS: 0.12300209747126599
Fold 4 IBS: 0.15537717066080473
Fold 5 IBS: 0.22972151113713862
[I 2024-04-18 03:22:25,067] Trial 3 finished with value: 0.16825111071113566 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.1685133135338509
Fold 2 IBS: 0.16521561008991986
Fold 3 IBS: 0.12306681075762275
Fold 4 IBS: 0.15534174166153036
Fold 5 IBS: 0.22983982433451866
[I 2024-04-18 03:22:26,973] Trial 4 finished with value: 0.1683954600754885 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.168391024247977
Fold 2 IBS: 0.16423289024780807
Fold 3 IBS: 0.12295316501834902
Fold 4 IBS: 0.15546009344998865
Fold 5 IBS: 0.22955613329787614
[I 2024-04-18 03:22:28,482] Trial 5 finished with value: 0.16811866125239977 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.16850340666567318
Fold 2 IBS: 0.16587779884402945
Fold 3 IBS: 0.12315167252582741
Fold 4 IBS: 0.1553034680459839
Fold 5 IBS: 0.2301219483386651
[I 2024-04-18 03:22:30,039] Trial 6 finished with value: 0.1685916588840358 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.16844714498147056
Fold 2 IBS: 0.16513076896228976
Fold 3 IBS: 0.12306779867581441
Fold 4 IBS: 0.15539202469667468
Fold 5 IBS: 0.22984876107804925
[I 2024-04-18 03:22:31,394] Trial 7 finished with value: 0.16837729967885973 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.16841615740374896
Fold 2 IBS: 0.16445636450228945
Fold 3 IBS: 0.1229760998075704
Fold 4 IBS: 0.15545036827168424
Fold 5 IBS: 0.2296247688985018
[I 2024-04-18 03:22:32,956] Trial 8 finished with value: 0.16818475177675898 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.1684207344807494
Fold 2 IBS: 0.16412504166254455
Fold 3 IBS: 0.12295914677736673
Fold 4 IBS: 0.15548785285738184
Fold 5 IBS: 0.22951221335124944
[I 2024-04-18 03:22:35,793] Trial 9 finished with value: 0.16810099782585838 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.1678393641975517.
Fold 1 IBS: 0.16830526998851492
Fold 2 IBS: 0.1628070283838867
Fold 3 IBS: 0.1227805315260259
Fold 4 IBS: 0.155630047612653
Fold 5 IBS: 0.22836387614434236
[I 2024-04-18 03:22:38,412] Trial 10 finished with value: 0.1675773507310846 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.1675773507310846.
Fold 1 IBS: 0.2136672748522475
Fold 2 IBS: 0.22041884867376527
Fold 3 IBS: 0.2039479234872786
Fold 4 IBS: 0.22389602090634644
Fold 5 IBS: 0.21729604601900276
[I 2024-04-18 03:22:39,015] Trial 11 finished with value: 0.2158452227877281 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.1675773507310846.
Fold 1 IBS: 0.16830580705484557
Fold 2 IBS: 0.1628049481054348
Fold 3 IBS: 0.12278067006026366
Fold 4 IBS: 0.15562961576118123
Fold 5 IBS: 0.2283608063163539
[I 2024-04-18 03:22:40,825] Trial 12 finished with value: 0.16757636945961585 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.16757636945961585.
Fold 1 IBS: 0.21389528364346674
Fold 2 IBS: 0.22127326093277078
Fold 3 IBS: 0.2043814342840862
Fold 4 IBS: 0.22451702134741316
Fold 5 IBS: 0.21790636332258345
[I 2024-04-18 03:22:41,520] Trial 13 finished with value: 0.21639467270606408 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.16757636945961585.
Fold 1 IBS: 0.16833480278510815
Fold 2 IBS: 0.1630054487861678
Fold 3 IBS: 0.12282175904847836
Fold 4 IBS: 0.1555857349521048
Fold 5 IBS: 0.22873985009554096
[I 2024-04-18 03:22:43,167] Trial 14 finished with value: 0.16769751913348002 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.16757636945961585.
Fold 1 IBS: 0.16832830688819256
Fold 2 IBS: 0.16303293501134694
Fold 3 IBS: 0.12281998918968354
Fold 4 IBS: 0.15559135446834804
Fold 5 IBS: 0.228549661341333
[I 2024-04-18 03:22:45,264] Trial 15 finished with value: 0.1676644493797808 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.16757636945961585.
Fold 1 IBS: 0.16830484877100088
Fold 2 IBS: 0.1630130090565506
Fold 3 IBS: 0.1228099105305425
Fold 4 IBS: 0.1556051333622068
Fold 5 IBS: 0.22855320602964813
[I 2024-04-18 03:22:47,057] Trial 16 finished with value: 0.1676572215499898 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.16757636945961585.
Fold 1 IBS: 0.16840273763649205
Fold 2 IBS: 0.16374021439195957
Fold 3 IBS: 0.12290080513749405
Fold 4 IBS: 0.15553189115073468
Fold 5 IBS: 0.22913180289190238
[I 2024-04-18 03:22:48,544] Trial 17 finished with value: 0.16794149024171656 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.16757636945961585.
Fold 1 IBS: 0.16825081347707369
Fold 2 IBS: 0.16266309499155635
Fold 3 IBS: 0.12277748908289499
Fold 4 IBS: 0.1556211565654125
Fold 5 IBS: 0.22845049627130656
[I 2024-04-18 03:22:50,176] Trial 18 finished with value: 0.16755261007764882 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.16849994253415612
Fold 2 IBS: 0.16589701434072943
Fold 3 IBS: 0.12315189264817471
Fold 4 IBS: 0.1553073387249016
Fold 5 IBS: 0.23013746247115846
[I 2024-04-18 03:22:51,643] Trial 19 finished with value: 0.1685987301438241 and parameters: {'l1_ratio': 0.9929377968859474}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.1683524442013696
Fold 2 IBS: 0.16344383247412866
Fold 3 IBS: 0.12287108706289256
Fold 4 IBS: 0.15555521892639304
Fold 5 IBS: 0.2289363075573098
[I 2024-04-18 03:22:53,657] Trial 20 finished with value: 0.16783177804441873 and parameters: {'l1_ratio': 0.2388879688839749}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.1682981659299283
Fold 2 IBS: 0.16282714004703266
Fold 3 IBS: 0.12277872223836825
Fold 4 IBS: 0.15559116621946872
Fold 5 IBS: 0.22840451022192945
[I 2024-04-18 03:22:55,870] Trial 21 finished with value: 0.16757994093134548 and parameters: {'l1_ratio': 0.08499433228302328}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.16827035742850044
Fold 2 IBS: 0.16280573051039543
Fold 3 IBS: 0.12278488791731727
Fold 4 IBS: 0.15560778956531293
Fold 5 IBS: 0.228408739668583
[I 2024-04-18 03:22:57,865] Trial 22 finished with value: 0.16757550101802182 and parameters: {'l1_ratio': 0.07181511589086235}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.2139161902415964
Fold 2 IBS: 0.2213516545644368
Fold 3 IBS: 0.2044211953598678
Fold 4 IBS: 0.22457391204951418
Fold 5 IBS: 0.21796242726226187
[I 2024-04-18 03:22:58,654] Trial 23 finished with value: 0.2164450758955354 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.16835640110431602
Fold 2 IBS: 0.16335034198861328
Fold 3 IBS: 0.12284214390041247
Fold 4 IBS: 0.1555415205035003
Fold 5 IBS: 0.2288984916651116
[I 2024-04-18 03:23:00,589] Trial 24 finished with value: 0.16779777983239072 and parameters: {'l1_ratio': 0.20495632796046423}. Best is trial 18 with value: 0.16755261007764882.

Fold 1 IBS: 0.16843339228982424
Fold 2 IBS: 0.16406705615949221
Fold 3 IBS: 0.12293161703222383
Fold 4 IBS: 0.15547587210092845
Fold 5 IBS: 0.22941697359956037
[I 2024-04-18 03:23:01,903] Trial 25 finished with value: 0.1680649822364058 and parameters: {'l1_ratio': 0.3804525958179419}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.1684177900660573
Fold 2 IBS: 0.16384957460920266
Fold 3 IBS: 0.12291520963379016
Fold 4 IBS: 0.15547621667156794
Fold 5 IBS: 0.22933803752905746
[I 2024-04-18 03:23:03,325] Trial 26 finished with value: 0.1679993657019351 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.16827995765183623
Fold 2 IBS: 0.16276847565567504
Fold 3 IBS: 0.1227702439018671
Fold 4 IBS: 0.15559926529038748
Fold 5 IBS: 0.228353856203132
[I 2024-04-18 03:23:05,063] Trial 27 finished with value: 0.16755435974057958 and parameters: {'l1_ratio': 0.07046652721581821}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.1683417380950058
Fold 2 IBS: 0.16325270359226243
Fold 3 IBS: 0.12283278339923773
Fold 4 IBS: 0.15554600641349664
Fold 5 IBS: 0.22879774699379202
[I 2024-04-18 03:23:06,917] Trial 28 finished with value: 0.16775419569875893 and parameters: {'l1_ratio': 0.1840952093317843}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.16844980550205438
Fold 2 IBS: 0.16570575306343396
Fold 3 IBS: 0.1231506545231384
Fold 4 IBS: 0.15526832761703716
Fold 5 IBS: 0.23004362054193198
[I 2024-04-18 03:23:08,318] Trial 29 finished with value: 0.16852363224951916 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.1682919692440584
Fold 2 IBS: 0.16285122775534028
Fold 3 IBS: 0.12277717875226972
Fold 4 IBS: 0.15559665790444102
Fold 5 IBS: 0.2284400033560213
[I 2024-04-18 03:23:10,561] Trial 30 finished with value: 0.16759140740242615 and parameters: {'l1_ratio': 0.08603677952870634}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.16829193546905763
Fold 2 IBS: 0.16285135910299037
Fold 3 IBS: 0.12277717042906042
Fold 4 IBS: 0.1555966877835709
Fold 5 IBS: 0.22844019693009934
[I 2024-04-18 03:23:12,815] Trial 31 finished with value: 0.1675914699429557 and parameters: {'l1_ratio': 0.08604252528991772}. Best is trial 18 with value: 0.16755261007764882.
Fold 1 IBS: 0.16824915982000838
Fold 2 IBS: 0.16273295259534115
Fold 3 IBS: 0.12277405366140513
Fold 4 IBS: 0.15561661751335573
Fold 5 IBS: 0.22834328323661834
[I 2024-04-18 03:23:14,960] Trial 32 finished with value: 0.16754321336534575 and parameters: {'l1_ratio': 0.05413792748818495}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16838957601753532
Fold 2 IBS: 0.1635795960175191
Fold 3 IBS: 0.1228884184075424
Fold 4 IBS: 0.15553215731965753
Fold 5 IBS: 0.22893860630160429
[I 2024-04-18 03:23:17,310] Trial 33 finished with value: 0.1678656708127717 and parameters: {'l1_ratio': 0.2557928465940727}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16831066332107802
Fold 2 IBS: 0.1632375297459001
Fold 3 IBS: 0.12284115460516343
Fold 4 IBS: 0.1555665428268627
Fold 5 IBS: 0.22881711195237314
[I 2024-04-18 03:23:19,966] Trial 34 finished with value: 0.16775460049027546 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16848191055694178
Fold 2 IBS: 0.16491897083974802
Fold 3 IBS: 0.12303281753718409
Fold 4 IBS: 0.15535415375089745
Fold 5 IBS: 0.22979050225065603
[I 2024-04-18 03:23:21,665] Trial 35 finished with value: 0.16831567098708547 and parameters: {'l1_ratio': 0.6179848099431686}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16840335532823275
Fold 2 IBS: 0.16373752448120715
Fold 3 IBS: 0.12290095244347092
Fold 4 IBS: 0.15553133257555338
Fold 5 IBS: 0.22912750893025355
[I 2024-04-18 03:23:23,475] Trial 36 finished with value: 0.16794013475174357 and parameters: {'l1_ratio': 0.2901961606553578}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16827250937147137
Fold 2 IBS: 0.16264273174175387
Fold 3 IBS: 0.122764077108632
Fold 4 IBS: 0.15564003671734286
Fold 5 IBS: 0.22846150756275027
[I 2024-04-18 03:23:26,190] Trial 37 finished with value: 0.16755617250039007 and parameters: {'l1_ratio': 0.05172410716345872}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16821761954992706
Fold 2 IBS: 0.1626810137102924
Fold 3 IBS: 0.12275895101380628
Fold 4 IBS: 0.22241092170423624
Fold 5 IBS: 0.22832099873082995
[I 2024-04-18 03:23:28,682] Trial 38 finished with value: 0.18087790094181838 and parameters: {'l1_ratio': 0.03443724315719897}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.168471289071241
Fold 2 IBS: 0.16549711984658075
Fold 3 IBS: 0.123106371494439
Fold 4 IBS: 0.1553171977047893
Fold 5 IBS: 0.22994618821665333
[I 2024-04-18 03:23:30,922] Trial 39 finished with value: 0.1684676332667407 and parameters: {'l1_ratio': 0.8205172079302314}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16846371701104645
Fold 2 IBS: 0.16460426306851245
Fold 3 IBS: 0.1230048681939673
Fold 4 IBS: 0.15541942076309861
Fold 5 IBS: 0.22964120724924572
[I 2024-04-18 03:23:32,583] Trial 40 finished with value: 0.16822669525717412 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16827016479332782
Fold 2 IBS: 0.16265906341892436
Fold 3 IBS: 0.12276344290772874
Fold 4 IBS: 0.15564194122235506
Fold 5 IBS: 0.2284739429868624
[I 2024-04-18 03:23:34,975] Trial 41 finished with value: 0.16756171106583967 and parameters: {'l1_ratio': 0.05195754820287199}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.1683082192274298
Fold 2 IBS: 0.16299875129472938
Fold 3 IBS: 0.12281080779525021
Fold 4 IBS: 0.15560222661904013
Fold 5 IBS: 0.228532184556805
[I 2024-04-18 03:23:37,566] Trial 42 finished with value: 0.16765043789865092 and parameters: {'l1_ratio': 0.13368894569195386}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.1682533489454123
Fold 2 IBS: 0.16276306355839562
Fold 3 IBS: 0.12277682730298385
Fold 4 IBS: 0.1556157777130361
Fold 5 IBS: 0.22837485178236505
[I 2024-04-18 03:23:39,694] Trial 43 finished with value: 0.1675567738604386 and parameters: {'l1_ratio': 0.05972357949836352}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16832191368462454
Fold 2 IBS: 0.16294270830169205
Fold 3 IBS: 0.12281444883871608
Fold 4 IBS: 0.15559074712785956
Fold 5 IBS: 0.22868441260045075
[I 2024-04-18 03:23:42,110] Trial 44 finished with value: 0.16767084611066857 and parameters: {'l1_ratio': 0.1300870547726771}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16834408858317976
Fold 2 IBS: 0.16340224622184238
Fold 3 IBS: 0.12286180398138491
Fold 4 IBS: 0.15555335450618377
Fold 5 IBS: 0.22897659908091508
[I 2024-04-18 03:23:43,931] Trial 45 finished with value: 0.16782761847470118 and parameters: {'l1_ratio': 0.21054652805990076}. Best is trial 32 with value: 0.16754321336534575.
Fold 1 IBS: 0.16824382030475352
Fold 2 IBS: 0.1627114493690455
Fold 3 IBS: 0.12277124501302049
Fold 4 IBS: 0.1556187393001642
Fold 5 IBS: 0.22832330472611556
[I 2024-04-18 03:23:45,971] Trial 46 finished with value: 0.16753371174261983 and parameters: {'l1_ratio': 0.04924745599434909}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.21343463798071374
Fold 2 IBS: 0.21954783071678566
Fold 3 IBS: 0.2035057364739897
Fold 4 IBS: 0.22326125538804595
Fold 5 IBS: 0.22828432313353814
[I 2024-04-18 03:23:46,990] Trial 47 finished with value: 0.21760675673861463 and parameters: {'l1_ratio': 0.02165315041644714}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16826878458703584
Fold 2 IBS: 0.16295973404227418
Fold 3 IBS: 0.12279362186385316
Fold 4 IBS: 0.1555803985582538
Fold 5 IBS: 0.22853200967683251
[I 2024-04-18 03:23:49,063] Trial 48 finished with value: 0.16762690974564992 and parameters: {'l1_ratio': 0.11384370862911156}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16830539112186144
Fold 2 IBS: 0.16326004791403181
Fold 3 IBS: 0.12283961774747018
Fold 4 IBS: 0.15557146616863612

Fold 5 IBS: 0.2288503907654318
[I 2024-04-18 03:23:51,034] Trial 49 finished with value: 0.16776538274348626 and parameters: {'l1_ratio': 0.1739865498896483}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16823956884471547
Fold 2 IBS: 0.16265775015630018
Fold 3 IBS: 0.12276745593861005
Fold 4 IBS: 0.22201778171735595
Fold 5 IBS: 0.22826456696892697
[I 2024-04-18 03:23:52,897] Trial 50 finished with value: 0.18078942472518172 and parameters: {'l1_ratio': 0.040430207194092474}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16827235241940472
Fold 2 IBS: 0.16256633572583526
Fold 3 IBS: 0.1227614155405021
Fold 4 IBS: 0.2219109704942683
Fold 5 IBS: 0.22837743103018027
[I 2024-04-18 03:23:55,180] Trial 51 finished with value: 0.18077770104203814 and parameters: {'l1_ratio': 0.04206766761484858}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16829044602227222
Fold 2 IBS: 0.16286944216161936
Fold 3 IBS: 0.122799437559214
Fold 4 IBS: 0.15560740966940576
Fold 5 IBS: 0.22863713734705338
[I 2024-04-18 03:23:56,881] Trial 52 finished with value: 0.16764077455191295 and parameters: {'l1_ratio': 0.10884694855756122}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.21393668476865607
Fold 2 IBS: 0.22142850924702845
Fold 3 IBS: 0.2044601745033847
Fold 4 IBS: 0.22462967367690656
Fold 5 IBS: 0.218017403454496
[I 2024-04-18 03:23:57,572] Trial 53 finished with value: 0.21649448913009434 and parameters: {'l1_ratio': 0.0015663374604940744}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16824177732357706
Fold 2 IBS: 0.16276155575318688
Fold 3 IBS: 0.122771961756545
Fold 4 IBS: 0.15562317072752851
Fold 5 IBS: 0.2283854651289123
[I 2024-04-18 03:23:59,603] Trial 54 finished with value: 0.16755678613794994 and parameters: {'l1_ratio': 0.054944409721118324}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16829421739993844
Fold 2 IBS: 0.16317551863430982
Fold 3 IBS: 0.12283168280768123
Fold 4 IBS: 0.1555743941269051
Fold 5 IBS: 0.22876186080083008
[I 2024-04-18 03:24:02,365] Trial 55 finished with value: 0.16772753475393293 and parameters: {'l1_ratio': 0.1563329050219546}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.1683961225968966
Fold 2 IBS: 0.16355145009366628
Fold 3 IBS: 0.12286527950679627
Fold 4 IBS: 0.15552625204279746
Fold 5 IBS: 0.2290971399793796
[I 2024-04-18 03:24:04,144] Trial 56 finished with value: 0.16788724884390724 and parameters: {'l1_ratio': 0.2521350387902013}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16830115650379932
Fold 2 IBS: 0.16297945847787393
Fold 3 IBS: 0.12280251103415173
Fold 4 IBS: 0.15559806462509618
Fold 5 IBS: 0.2285753657674299
[I 2024-04-18 03:24:06,385] Trial 57 finished with value: 0.1676513112816702 and parameters: {'l1_ratio': 0.10649984020235259}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16826623696165227
Fold 2 IBS: 0.162763628106726
Fold 3 IBS: 0.12278224382953776
Fold 4 IBS: 0.15560750052905764
Fold 5 IBS: 0.22836221110942861
[I 2024-04-18 03:24:08,990] Trial 58 finished with value: 0.16755636410728045 and parameters: {'l1_ratio': 0.06484179259299064}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16843107518871273
Fold 2 IBS: 0.16440046379510673
Fold 3 IBS: 0.12297851327559772
Fold 4 IBS: 0.1554350583882286
Fold 5 IBS: 0.22956849083668668
[I 2024-04-18 03:24:11,451] Trial 59 finished with value: 0.16816272029686646 and parameters: {'l1_ratio': 0.46223632357501726}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.1683264644402861
Fold 2 IBS: 0.16337280830164463
Fold 3 IBS: 0.12285714749742907
Fold 4 IBS: 0.15556935618742984
Fold 5 IBS: 0.22888282588067263
[I 2024-04-18 03:24:13,480] Trial 60 finished with value: 0.16780172046149247 and parameters: {'l1_ratio': 0.21893485990806422}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.1682752847648443
Fold 2 IBS: 0.16273631965772187
Fold 3 IBS: 0.1227675185477984
Fold 4 IBS: 0.15559943371272808
Fold 5 IBS: 0.22831054741384404
[I 2024-04-18 03:24:15,957] Trial 61 finished with value: 0.16753782081938734 and parameters: {'l1_ratio': 0.06369989068284279}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16828955184840735
Fold 2 IBS: 0.16294250102761695
Fold 3 IBS: 0.12279658911834732
Fold 4 IBS: 0.15560326662371424
Fold 5 IBS: 0.22854342101464195
[I 2024-04-18 03:24:18,722] Trial 62 finished with value: 0.1676350659265456 and parameters: {'l1_ratio': 0.0969677795063906}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.21397360375751634
Fold 2 IBS: 0.22156697177495344
Fold 3 IBS: 0.20453039648459592
Fold 4 IBS: 0.22473010408515315
Fold 5 IBS: 0.2181164814231973
[I 2024-04-18 03:24:19,542] Trial 63 finished with value: 0.21658351150508323 and parameters: {'l1_ratio': 0.00011460075029621347}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16828462891782783
Fold 2 IBS: 0.16275788576204472
Fold 3 IBS: 0.12277142115997824
Fold 4 IBS: 0.15559510065082638
Fold 5 IBS: 0.22832718855573228
[I 2024-04-18 03:24:22,267] Trial 64 finished with value: 0.16754724500928192 and parameters: {'l1_ratio': 0.06982693536654624}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16830525315694989
Fold 2 IBS: 0.16313073688013002
Fold 3 IBS: 0.1228140437343266
Fold 4 IBS: 0.1555642203776003
Fold 5 IBS: 0.22869394147997466
[I 2024-04-18 03:24:24,565] Trial 65 finished with value: 0.1677016391257963 and parameters: {'l1_ratio': 0.15270915914545236}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16824574215015595
Fold 2 IBS: 0.16260220962542987
Fold 3 IBS: 0.12275234656048023
Fold 4 IBS: 0.22230366654575048
Fold 5 IBS: 0.22819702021065655
[I 2024-04-18 03:24:27,590] Trial 66 finished with value: 0.1808201970184946 and parameters: {'l1_ratio': 0.03606695572689615}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16832310234994544
Fold 2 IBS: 0.1633301881650948
Fold 3 IBS: 0.12284999124545254
Fold 4 IBS: 0.1555631962770422
Fold 5 IBS: 0.22891406509097276
[I 2024-04-18 03:24:29,869] Trial 67 finished with value: 0.16779610862570155 and parameters: {'l1_ratio': 0.19162018262818542}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16831021457103368
Fold 2 IBS: 0.1630262849192932
Fold 3 IBS: 0.12280794164636782
Fold 4 IBS: 0.1555955889527099
Fold 5 IBS: 0.22863197535632623
[I 2024-04-18 03:24:32,150] Trial 68 finished with value: 0.16767440108914616 and parameters: {'l1_ratio': 0.11785936247079534}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16826444127380027
Fold 2 IBS: 0.16282869800599228
Fold 3 IBS: 0.12278307204945815
Fold 4 IBS: 0.15561301948093434
Fold 5 IBS: 0.22844261375048436
[I 2024-04-18 03:24:34,453] Trial 69 finished with value: 0.16758636891213388 and parameters: {'l1_ratio': 0.07266989761093624}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16848132169369387
Fold 2 IBS: 0.1649218667952413
Fold 3 IBS: 0.12303276402856314
Fold 4 IBS: 0.15535480385807388
Fold 5 IBS: 0.22979271558186165
[I 2024-04-18 03:24:36,394] Trial 70 finished with value: 0.16831669439148675 and parameters: {'l1_ratio': 0.6190167670320361}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16829812850064668
Fold 2 IBS: 0.16275969016256983
Fold 3 IBS: 0.12277670325372499
Fold 4 IBS: 0.15563197756897923
Fold 5 IBS: 0.2283237121077715
[I 2024-04-18 03:24:38,646] Trial 71 finished with value: 0.16755804231873844 and parameters: {'l1_ratio': 0.07597204675116165}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.21324921307035855
Fold 2 IBS: 0.21885396431283352
Fold 3 IBS: 0.1227520364438065
Fold 4 IBS: 0.2227543465787968
Fold 5 IBS: 0.2283660031875574
[I 2024-04-18 03:24:40,142] Trial 72 finished with value: 0.20119511271867055 and parameters: {'l1_ratio': 0.029245201948524646}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16825238674338527
Fold 2 IBS: 0.16266265801158178
Fold 3 IBS: 0.12277796341469019
Fold 4 IBS: 0.15561976908228267
Fold 5 IBS: 0.2284414783689906
[I 2024-04-18 03:24:42,204] Trial 73 finished with value: 0.1675508511241861 and parameters: {'l1_ratio': 0.0666640235520193}. Best is trial 46 with value: 0.16753371174261983.

Fold 1 IBS: 0.16832861518122158
Fold 2 IBS: 0.1630316298309345
Fold 3 IBS: 0.12282007224328821
Fold 4 IBS: 0.15559108824572546
Fold 5 IBS: 0.22854773723235974
[I 2024-04-18 03:24:44,747] Trial 74 finished with value: 0.16766382854670592 and parameters: {'l1_ratio': 0.14538128014992321}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16827616054249042
Fold 2 IBS: 0.16293598838646187
Fold 3 IBS: 0.1227955705921141
Fold 4 IBS: 0.15557344374701365
Fold 5 IBS: 0.2284861248858399
[I 2024-04-18 03:24:46,946] Trial 75 finished with value: 0.167613457630784 and parameters: {'l1_ratio': 0.11207878786036493}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16843090599960045
Fold 2 IBS: 0.16385845830158044
Fold 3 IBS: 0.1229180903008412
Fold 4 IBS: 0.15551921419809686
Fold 5 IBS: 0.22924594837427384
[I 2024-04-18 03:24:48,997] Trial 76 finished with value: 0.16799452343487856 and parameters: {'l1_ratio': 0.32134083380611417}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.21343454870366424
Fold 2 IBS: 0.21954749656938674
Fold 3 IBS: 0.20350556678731188
Fold 4 IBS: 0.22326101154108766
Fold 5 IBS: 0.22828479435744942
[I 2024-04-18 03:24:50,125] Trial 77 finished with value: 0.21760668359177998 and parameters: {'l1_ratio': 0.02165678236857626}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16826457965458433
Fold 2 IBS: 0.16280748522841204
Fold 3 IBS: 0.12278713395437899
Fold 4 IBS: 0.15562043761992272
Fold 5 IBS: 0.22859621121067217
[I 2024-04-18 03:24:52,492] Trial 78 finished with value: 0.16761516953359407 and parameters: {'l1_ratio': 0.09089919034642774}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16834999304685716
Fold 2 IBS: 0.1632174872877466
Fold 3 IBS: 0.12283479478301783
Fold 4 IBS: 0.1555383454867728
Fold 5 IBS: 0.2287457361064163
[I 2024-04-18 03:24:55,745] Trial 79 finished with value: 0.16773727134216215 and parameters: {'l1_ratio': 0.18089347720433796}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.1682650850219503
Fold 2 IBS: 0.16276809788908647
Fold 3 IBS: 0.1227818806634882
Fold 4 IBS: 0.15560852461180527
Fold 5 IBS: 0.22836879553196351
[I 2024-04-18 03:24:58,833] Trial 80 finished with value: 0.16755847674365876 and parameters: {'l1_ratio': 0.06498986434192307}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16825065014913262
Fold 2 IBS: 0.1627735482303647
Fold 3 IBS: 0.12277598961609797
Fold 4 IBS: 0.15561817086124016
Fold 5 IBS: 0.22839028435484418
[I 2024-04-18 03:25:01,498] Trial 81 finished with value: 0.16756172864233593 and parameters: {'l1_ratio': 0.060047173272383805}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.21340463767202505
Fold 2 IBS: 0.21943554937591117
Fold 3 IBS: 0.2034487155349194
Fold 4 IBS: 0.22317930267950725
Fold 5 IBS: 0.2281821427153845
[I 2024-04-18 03:25:02,720] Trial 82 finished with value: 0.2175300695955495 and parameters: {'l1_ratio': 0.022874870795248105}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.1683190355262347
Fold 2 IBS: 0.1629530514646672
Fold 3 IBS: 0.12281376313406221
Fold 4 IBS: 0.1555928776096724
Fold 5 IBS: 0.22869860865783326
[I 2024-04-18 03:25:04,735] Trial 83 finished with value: 0.16767546727849397 and parameters: {'l1_ratio': 0.13073898939867148}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16830512721444882
Fold 2 IBS: 0.16280758143258175
Fold 3 IBS: 0.12278049473909615
Fold 4 IBS: 0.15563016239471777
Fold 5 IBS: 0.22836469228435075
[I 2024-04-18 03:25:07,215] Trial 84 finished with value: 0.16757761161303905 and parameters: {'l1_ratio': 0.08385051808398299}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16827005643923632
Fold 2 IBS: 0.16265948126421656
Fold 3 IBS: 0.12276341371062695
Fold 4 IBS: 0.15564202917945733
Fold 5 IBS: 0.2284745178033121
[I 2024-04-18 03:25:09,855] Trial 85 finished with value: 0.16756189967936985 and parameters: {'l1_ratio': 0.05196838309966061}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16830595633156348
Fold 2 IBS: 0.16312774796541085
Fold 3 IBS: 0.12281421723140332
Fold 4 IBS: 0.15556355624362198
Fold 5 IBS: 0.2286895290947538
[I 2024-04-18 03:25:11,967] Trial 86 finished with value: 0.16770020137335068 and parameters: {'l1_ratio': 0.15247876033258365}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.21396671572354395
Fold 2 IBS: 0.22154113701708167
Fold 3 IBS: 0.20451729458617088
Fold 4 IBS: 0.22471136845490042
Fold 5 IBS: 0.21809799203060312
[I 2024-04-18 03:25:12,718] Trial 87 finished with value: 0.21656690156246 and parameters: {'l1_ratio': 0.00038518801973273786}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16829540598411535
Fold 2 IBS: 0.1629195726325091
Fold 3 IBS: 0.12279833048540147
Fold 4 IBS: 0.15559812505656886
Fold 5 IBS: 0.2285097601092218
[I 2024-04-18 03:25:14,646] Trial 88 finished with value: 0.1676242388535633 and parameters: {'l1_ratio': 0.09583414770735746}. Best is trial 46 with value: 0.16753371174261983.
Fold 1 IBS: 0.16824405154258404
Fold 2 IBS: 0.16271055382525648
Fold 3 IBS: 0.12277131833801316
Fold 4 IBS: 0.1556185333285208
Fold 5 IBS: 0.22832198560093883
[I 2024-04-18 03:25:16,797] Trial 89 finished with value: 0.16753328852706267 and parameters: {'l1_ratio': 0.04922481027815988}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.16822341882178693
Fold 2 IBS: 0.16268753158732913
Fold 3 IBS: 0.12276155099712553
Fold 4 IBS: 0.2221980616836496
Fold 5 IBS: 0.22831729281328286
[I 2024-04-18 03:25:18,763] Trial 90 finished with value: 0.18083757118063482 and parameters: {'l1_ratio': 0.03767544076144083}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.16824611727229896
Fold 2 IBS: 0.1626827191060219
Fold 3 IBS: 0.12277608764341782
Fold 4 IBS: 0.15562520885771705
Fold 5 IBS: 0.22847743149801086
[I 2024-04-18 03:25:21,067] Trial 91 finished with value: 0.1675615128754933 and parameters: {'l1_ratio': 0.0675199916123736}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.16830919247251014
Fold 2 IBS: 0.16288847523803673
Fold 3 IBS: 0.12280764985033532
Fold 4 IBS: 0.15559647955174066
Fold 5 IBS: 0.2286378780578924
[I 2024-04-18 03:25:23,220] Trial 92 finished with value: 0.16764793503410305 and parameters: {'l1_ratio': 0.11810412089827158}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.21352841984671514
Fold 2 IBS: 0.21989888391672027
Fold 3 IBS: 0.20368398639284999
Fold 4 IBS: 0.22351729820180194
Fold 5 IBS: 0.21692534239751052
[I 2024-04-18 03:25:24,187] Trial 93 finished with value: 0.21551078615111957 and parameters: {'l1_ratio': 0.01785010660358423}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.16848067634815803
Fold 2 IBS: 0.16544535508950314
Fold 3 IBS: 0.12310653314260593
Fold 4 IBS: 0.1553063221428522
Fold 5 IBS: 0.22997272040390315
[I 2024-04-18 03:25:26,217] Trial 94 finished with value: 0.1684623214254045 and parameters: {'l1_ratio': 0.7957156066164938}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.1682358741717678
Fold 2 IBS: 0.1627422177900656
Fold 3 IBS: 0.12276896666207428
Fold 4 IBS: 0.15562580080095192
Fold 5 IBS: 0.22836867141826372
[I 2024-04-18 03:25:28,568] Trial 95 finished with value: 0.16754830616862465 and parameters: {'l1_ratio': 0.05003738817426033}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.16826826875817402
Fold 2 IBS: 0.16279287400863546
Fold 3 IBS: 0.12278812436436458
Fold 4 IBS: 0.15561740133124422
Fold 5 IBS: 0.22857615395513153
[I 2024-04-18 03:25:30,647] Trial 96 finished with value: 0.16760856448350997 and parameters: {'l1_ratio': 0.09024849590134996}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.1682472503458236
Fold 2 IBS: 0.16265982047338973
Fold 3 IBS: 0.12275482892948401
Fold 4 IBS: 0.22178019186271988
Fold 5 IBS: 0.2282579228863886
[I 2024-04-18 03:25:32,611] Trial 97 finished with value: 0.18074000289956116 and parameters: {'l1_ratio': 0.044078006890434694}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.16831763671468974
Fold 2 IBS: 0.16295895669572175
Fold 3 IBS: 0.12281337443305897

Fold 4 IBS: 0.15559409221063014
Fold 5 IBS: 0.22870671398377174
[I 2024-04-18 03:25:34,590] Trial 98 finished with value: 0.16767815480757448 and parameters: {'l1_ratio': 0.13111375797605596}. Best is trial 89 with value: 0.16753328852706267.
Fold 1 IBS: 0.16831714561719655
Fold 2 IBS: 0.1632108507105827
Fold 3 IBS: 0.12282163960669765
Fold 4 IBS: 0.15556068379359772
Fold 5 IBS: 0.22877769998936398
[I 2024-04-18 03:25:36,681] Trial 99 finished with value: 0.16773760394348775 and parameters: {'l1_ratio': 0.16965192632929055}. Best is trial 89 with value: 0.16753328852706267.


* Best trial for IBS:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.16753328852706267], datetime_start=datetime.datetime(2024, 4, 18, 3, 25, 14, 653064), datetime_complete=datetime.datetime(2024, 4, 18, 3, 25, 16, 797317), params={'l1_ratio': 0.04922481027815988}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=89, value=None)


* Best Score for IBS:
 0.16753328852706267

In [50]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [51]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.78
train_ibs:  0.168

#### Test

In [52]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [53]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.623

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.04922481027815988)

test_ibs:  0.229

In [54]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [55]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:25:37,580] A new study created in memory with name: no-name-f3282b91-65d2-495b-b373-83ef2f0c25fd

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:25:52,637] Trial 0 finished with value: 0.7526036901818866 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7526036901818866.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 03:26:03,923] Trial 1 finished with value: 0.7690368743406535 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7690368743406535.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6830985915492958
[I 2024-04-18 03:26:13,072] Trial 2 finished with value: 0.7679230653103394 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7690368743406535.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:26:15,857] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7690368743406535.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:26:20,092] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7690368743406535.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:26:35,115] Trial 5 finished with value: 0.7863244983563694 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 03:26:52,408] Trial 6 finished with value: 0.7826705889004008 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:27:02,503] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6408450704225352
[I 2024-04-18 03:27:31,046] Trial 8 finished with value: 0.528169014084507 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:27:43,676] Trial 9 finished with value: 0.7742314712640109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:27:45,260] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7394366197183099
[I 2024-04-18 03:27:51,679] Trial 11 finished with value: 0.7747975011330649 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.4557494463783111, 'max_features': None, 'min_weight_fraction_leaf': 0.018281586236884743, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 03:28:19,964] Trial 12 finished with value: 0.7689594101307681 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.47265100602672383, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6549295774647887
[I 2024-04-18 03:28:41,094] Trial 13 finished with value: 0.7717928956498076 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.40856226559381104, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 5 with value: 0.7863244983563694.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.744131455399061
[I 2024-04-18 03:28:48,442] Trial 14 finished with value: 0.796537467034659 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.5468697215995818, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10307193292566577, 'warm_start': True}. Best is trial 14 with value: 0.796537467034659.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.875

Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 03:28:58,539] Trial 15 finished with value: 0.7983302951806827 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.8284238710883769, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17583629499904482, 'warm_start': True}. Best is trial 15 with value: 0.7983302951806827.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 03:29:03,536] Trial 16 finished with value: 0.7961202315088663 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 175, 'oob_score': True, 'max_samples': 0.8042262963180606, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19044970067978945, 'warm_start': True}. Best is trial 15 with value: 0.7983302951806827.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:29:15,071] Trial 17 finished with value: 0.7999301592628495 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.8699768148803853, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15363155950246649, 'warm_start': True}. Best is trial 17 with value: 0.7999301592628495.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 03:29:25,755] Trial 18 finished with value: 0.7861626717251999 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 17 with value: 0.7999301592628495.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.7394366197183099
[I 2024-04-18 03:29:38,637] Trial 19 finished with value: 0.7967263618603246 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.8500813278003009, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1638836020583787, 'warm_start': True}. Best is trial 17 with value: 0.7999301592628495.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6784037558685446
[I 2024-04-18 03:29:48,539] Trial 20 finished with value: 0.795095287989586 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.705181926217295, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24858261413121135, 'warm_start': True}. Best is trial 17 with value: 0.7999301592628495.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.744131455399061
[I 2024-04-18 03:30:00,197] Trial 21 finished with value: 0.7994896030098777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.8491453344865547, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 17 with value: 0.7999301592628495.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:30:09,869] Trial 22 finished with value: 0.8083879081138606 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.8290800554863174, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14609188473654175, 'warm_start': True}. Best is trial 22 with value: 0.8083879081138606.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:30:20,013] Trial 23 finished with value: 0.7956269420035635 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.9859933897340725, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12745649043111246, 'warm_start': True}. Best is trial 22 with value: 0.8083879081138606.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:30:29,732] Trial 24 finished with value: 0.8088098490421306 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 449, 'oob_score': True, 'max_samples': 0.8801110327745552, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06983432434752933, 'warm_start': True}. Best is trial 24 with value: 0.8088098490421306.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:30:38,700] Trial 25 finished with value: 0.8129754232768164 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 435, 'oob_score': True, 'max_samples': 0.9065436541533849, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06798711216807118, 'warm_start': True}. Best is trial 25 with value: 0.8129754232768164.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7394366197183099
[I 2024-04-18 03:30:50,100] Trial 26 finished with value: 0.8066479167883948 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.7529761625268641, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 25 with value: 0.8129754232768164.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:31:02,553] Trial 27 finished with value: 0.8146361307128405 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.9278408273498996, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08004248467255283, 'warm_start': True}. Best is trial 27 with value: 0.8146361307128405.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:31:12,777] Trial 28 finished with value: 0.8155652756086147 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.9976713124341267, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08456394858325358, 'warm_start': True}. Best is trial 28 with value: 0.8155652756086147.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:31:21,064] Trial 29 finished with value: 0.8155527265445148 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.9415871049044248, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08395824031953503, 'warm_start': True}. Best is trial 28 with value: 0.8155652756086147.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 03:31:29,001] Trial 30 finished with value: 0.8040514945422894 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.9958344170463831, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20001380215328324, 'warm_start': True}. Best is trial 28 with value: 0.8155652756086147.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:31:37,377] Trial 31 finished with value: 0.8183090107467159 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 362, 'oob_score': True, 'max_samples': 0.9452517320699256, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07638528446866957, 'warm_start': True}. Best is trial 31 with value: 0.8183090107467159.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:31:47,030] Trial 32 finished with value: 0.8172191645665867 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 380, 'oob_score': True, 'max_samples': 0.9395390170058006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08967287712437312, 'warm_start': True}. Best is trial 31 with value: 0.8183090107467159.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:31:52,848] Trial 33 finished with value: 0.8145653774403001 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.7669547089150025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11550091018015887, 'warm_start': True}. Best is trial 31 with value: 0.8183090107467159.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:32:03,731] Trial 34 finished with value: 0.8175088258856599 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.9416219261631492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08700697720898533, 'warm_start': True}. Best is trial 31 with value: 0.8183090107467159.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6924882629107981
[I 2024-04-18 03:32:08,439] Trial 35 finished with value: 0.8002453954077133 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.7155111940209397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2162261993312639, 'warm_start': True}. Best is trial 31 with value: 0.8183090107467159.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:32:18,346] Trial 36 finished with value: 0.8163896514537029 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 393, 'oob_score': True, 'max_samples': 0.9508900424183993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.042163225365865975, 'warm_start': True}. Best is trial 31 with value: 0.8183090107467159.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7934272300469484
[I 2024-04-18 03:32:22,949] Trial 37 finished with value: 0.8343032276444833 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 282, 'oob_score': False, 'max_samples': 0.6723788047810191, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.044210918180831504, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:32:26,751] Trial 38 finished with value: 0.8040100695215768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.6475925530300135, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12604863418565332, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:32:29,798] Trial 39 finished with value: 0.8165013774517409 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.6780223132762756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0432025163533139, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:32:33,937] Trial 40 finished with value: 0.8135872572582089 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.7548574861621926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002493708078648779, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:32:37,615] Trial 41 finished with value: 0.8137922488563003 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.5764130546260958, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.040662041203491865, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:32:39,568] Trial 42 finished with value: 0.8174017848602025 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 155, 'oob_score': False, 'max_samples': 0.6690801009591556, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04927835244726446, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 03:32:41,441] Trial 43 finished with value: 0.8219179534323657 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 139, 'oob_score': False, 'max_samples': 0.7949935571252613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06403802850323136, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7934272300469484
[I 2024-04-18 03:32:43,187] Trial 44 finished with value: 0.8316496172935535 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.7949617056196056, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05717732231663539, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7489451476793249
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:32:44,205] Trial 45 finished with value: 0.723337057902141 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 53, 'oob_score': False, 'max_samples': 0.7971119328836928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38375137618138855, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 03:32:50,350] Trial 46 finished with value: 0.7822840095697269 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.7906720295639957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.029070641028617797, 'warm_start': False}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 03:32:51,934] Trial 47 finished with value: 0.8069243645042257 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.8887184740957137, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12912163694101375, 'warm_start': True}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:33:07,120] Trial 48 finished with value: 0.773832496944709 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 223, 'oob_score': False, 'max_samples': 0.531839605189211, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0633106289239907, 'warm_start': False}. Best is trial 37 with value: 0.8343032276444833.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:33:10,399] Trial 49 finished with value: 0.8454175412364983 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.6116128556170777, 'max_features': None, 'min_weight_fraction_leaf': 0.0020608792712853846, 'warm_start': True}. Best is trial 49 with value: 0.8454175412364983.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 03:33:13,313] Trial 50 finished with value: 0.8481612763745995 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 191, 'oob_score': False, 'max_samples': 0.6031853800360653, 'max_features': None, 'min_weight_fraction_leaf': 0.006793503047480287, 'warm_start': True}. Best is trial 50 with value: 0.8481612763745995.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:33:16,193] Trial 51 finished with value: 0.8382327644991772 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 205, 'oob_score': False, 'max_samples': 0.6270633277712119, 'max_features': None, 'min_weight_fraction_leaf': 0.0014047817079391595, 'warm_start': True}. Best is trial 50 with value: 0.8481612763745995.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 03:33:19,002] Trial 52 finished with value: 0.8547269483572617 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.6101354912642183, 'max_features': None, 'min_weight_fraction_leaf': 0.00292920588368519, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 03:33:21,901] Trial 53 finished with value: 0.8405178524269561 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.6091950141355604, 'max_features': None, 'min_weight_fraction_leaf': 0.0034577014637121742, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 03:33:24,655] Trial 54 finished with value: 0.8460150064742343 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.6019310935078064, 'max_features': None, 'min_weight_fraction_leaf': 4.978357408229241e-05, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8356807511737089
[I 2024-04-18 03:33:27,232] Trial 55 finished with value: 0.8342805425140931 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.5146544888889404, 'max_features': None, 'min_weight_fraction_leaf': 0.003343395792776767, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:33:35,430] Trial 56 finished with value: 0.7795303795516164 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.5937999047868031, 'max_features': None, 'min_weight_fraction_leaf': 0.0218496660426568, 'warm_start': False}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 03:33:37,626] Trial 57 finished with value: 0.8378779817491105 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 163, 'oob_score': False, 'max_samples': 0.6202362840379292, 'max_features': None, 'min_weight_fraction_leaf': 0.019015252723892265, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8732394366197183
[I 2024-04-18 03:33:40,666] Trial 58 finished with value: 0.8435779938890093 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.49028292326728556, 'max_features': None, 'min_weight_fraction_leaf': 0.00239548779616611, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 03:33:42,368] Trial 59 finished with value: 0.8393698468706596 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.39834436468867795, 'max_features': None, 'min_weight_fraction_leaf': 0.029318986373619165, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:33:51,916] Trial 60 finished with value: 0.7721831241289202 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.5685956211455405, 'max_features': None, 'min_weight_fraction_leaf': 0.016835061621379547, 'warm_start': False}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 03:33:53,418] Trial 61 finished with value: 0.8412315927197472 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.37341354651845093, 'max_features': None, 'min_weight_fraction_leaf': 0.029376749824158443, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:33:55,944] Trial 62 finished with value: 0.8002844443179302 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 185, 'oob_score': False, 'max_samples': 0.2653055294468287, 'max_features': None, 'min_weight_fraction_leaf': 0.0017482401819946102, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.5541125541125541
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 03:33:56,541] Trial 63 finished with value: 0.7663071045976211 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 6, 'oob_score': False, 'max_samples': 0.4873575401781829, 'max_features': None, 'min_weight_fraction_leaf': 0.032977270887152056, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:33:58,391] Trial 64 finished with value: 0.8430703739461067 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 116, 'oob_score': False, 'max_samples': 0.4380980855173893, 'max_features': None, 'min_weight_fraction_leaf': 0.02248106080442111, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:34:00,438] Trial 65 finished with value: 0.8334850426256176 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.3279180432099762, 'max_features': None, 'min_weight_fraction_leaf': 0.02553413452267196, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:34:02,159] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 118, 'oob_score': False, 'max_samples': 0.4387828511174194, 'max_features': None, 'min_weight_fraction_leaf': 0.48319510296987256, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 03:34:03,232] Trial 67 finished with value: 0.8333140668056718 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.40540158600840737, 'max_features': None, 'min_weight_fraction_leaf': 0.01391049932172694, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7535211267605634
[I 2024-04-18 03:34:05,258] Trial 68 finished with value: 0.7901610610207876 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 171, 'oob_score': False, 'max_samples': 0.362635633755095, 'max_features': None, 'min_weight_fraction_leaf': 0.10341042945154397, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:34:07,018] Trial 69 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.4998312488233768, 'max_features': None, 'min_weight_fraction_leaf': 0.2860861101248542, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8215962441314554
[I 2024-04-18 03:34:09,010] Trial 70 finished with value: 0.8201905012397995 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.446949892989797, 'max_features': None, 'min_weight_fraction_leaf': 0.05475910028758361, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:34:11,896] Trial 71 finished with value: 0.8473905990944652 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.5491545446421586, 'max_features': None, 'min_weight_fraction_leaf': 0.015266077405547673, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:34:16,136] Trial 72 finished with value: 0.8424003332025366 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.5319769235754814, 'max_features': None, 'min_weight_fraction_leaf': 0.03209704657522406, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8356807511737089
[I 2024-04-18 03:34:19,803] Trial 73 finished with value: 0.8342419827864045 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.558350145742507, 'max_features': None, 'min_weight_fraction_leaf': 0.013975744259002582, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 03:34:23,249] Trial 74 finished with value: 0.833400372904636 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.5324146085306538, 'max_features': None, 'min_weight_fraction_leaf': 0.03466541947750544, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:34:26,554] Trial 75 finished with value: 0.836865848342611 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.47420738096742965, 'max_features': None, 'min_weight_fraction_leaf': 0.018444398501245574, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 03:34:29,484] Trial 76 finished with value: 0.8306682822402045 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.646991123512679, 'max_features': None, 'min_weight_fraction_leaf': 0.0719438074387708, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:34:32,239] Trial 77 finished with value: 0.8280392768624655 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.5982227821087488, 'max_features': None, 'min_weight_fraction_leaf': 0.05440864350802245, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7934272300469484
[I 2024-04-18 03:34:34,240] Trial 78 finished with value: 0.8196662854107428 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.5443198592419901, 'max_features': None, 'min_weight_fraction_leaf': 0.04166752165937045, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:34:36,820] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.6938934804570732, 'max_features': None, 'min_weight_fraction_leaf': 0.34696749792453063, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.7347417840375586
[I 2024-04-18 03:34:50,842] Trial 80 finished with value: 0.7753497720341318 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.5836122663769806, 'max_features': None, 'min_weight_fraction_leaf': 0.014147810982010022, 'warm_start': False}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 03:34:55,267] Trial 81 finished with value: 0.8451440683406378 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.5112929433055626, 'max_features': None, 'min_weight_fraction_leaf': 0.03211260554684412, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:34:58,541] Trial 82 finished with value: 0.8362148613152776 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.5080653358543864, 'max_features': None, 'min_weight_fraction_leaf': 0.0380293905621526, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:35:01,808] Trial 83 finished with value: 0.8395392825033869 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 188, 'oob_score': False, 'max_samples': 0.43090051979198907, 'max_features': None, 'min_weight_fraction_leaf': 0.013845373435287392, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:35:06,682] Trial 84 finished with value: 0.7995930330510784 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.4624694484345503, 'max_features': None, 'min_weight_fraction_leaf': 0.09401995408917525, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 03:35:09,383] Trial 85 finished with value: 0.8368929046196673 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.5570512285847514, 'max_features': None, 'min_weight_fraction_leaf': 0.002610530165685054, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.8215962441314554
[I 2024-04-18 03:35:11,747] Trial 86 finished with value: 0.8236070462237309 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.5182962279467025, 'max_features': None, 'min_weight_fraction_leaf': 0.0602825969917434, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.8356807511737089
[I 2024-04-18 03:35:14,300] Trial 87 finished with value: 0.8289879277696913 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.6317619023170126, 'max_features': None, 'min_weight_fraction_leaf': 0.02711587415850411, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 03:35:18,372] Trial 88 finished with value: 0.8279188165160551 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.4826638290783741, 'max_features': None, 'min_weight_fraction_leaf': 0.048804175543920816, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:35:21,244] Trial 89 finished with value: 0.8299032946863246 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.7311728104330791, 'max_features': None, 'min_weight_fraction_leaf': 0.07480895234380272, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:35:23,736] Trial 90 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.14203113507342713, 'max_features': None, 'min_weight_fraction_leaf': 0.2513921457170648, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 03:35:25,482] Trial 91 finished with value: 0.8376970426657511 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.3732694497916078, 'max_features': None, 'min_weight_fraction_leaf': 0.032414941793507575, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 03:35:26,778] Trial 92 finished with value: 0.8473098442524549 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.5360295416604122, 'max_features': None, 'min_weight_fraction_leaf': 0.023607460602106833, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:35:30,229] Trial 93 finished with value: 0.8506174836990988 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 221, 'oob_score': False, 'max_samples': 0.5387876307202797, 'max_features': None, 'min_weight_fraction_leaf': 0.011816606518950359, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8685446009389671
[I 2024-04-18 03:35:31,137] Trial 94 finished with value: 0.8496202714947143 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.5816510283493093, 'max_features': None, 'min_weight_fraction_leaf': 0.010446979801429291, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.6515151515151515
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.7910798122065728
[I 2024-04-18 03:35:31,794] Trial 95 finished with value: 0.7642050899680445 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 4, 'oob_score': False, 'max_samples': 0.5722081583272028, 'max_features': None, 'min_weight_fraction_leaf': 0.01239125580287388, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8504464285714286
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:35:32,574] Trial 96 finished with value: 0.7599118590976804 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 24, 'oob_score': False, 'max_samples': 0.6136535984079456, 'max_features': None, 'min_weight_fraction_leaf': 0.00012566897383599167, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8685446009389671
[I 2024-04-18 03:35:33,704] Trial 97 finished with value: 0.8511059089027271 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.5848595834378778, 'max_features': None, 'min_weight_fraction_leaf': 0.01017415272606545, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7253521126760564
[I 2024-04-18 03:35:36,891] Trial 98 finished with value: 0.7699984000553333 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 30, 'oob_score': False, 'max_samples': 0.6619311115964273, 'max_features': None, 'min_weight_fraction_leaf': 0.04542345652416228, 'warm_start': False}. Best is trial 52 with value: 0.8547269483572617.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8970588235294118

[I 2024-04-18 03:35:38,351] A new study created in memory with name: no-name-fe2cf773-b503-46cf-aca8-ef59da7fc358

Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 03:35:38,281] Trial 99 finished with value: 0.8471157205082068 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.5780480014255376, 'max_features': None, 'min_weight_fraction_leaf': 0.011566069862627605, 'warm_start': True}. Best is trial 52 with value: 0.8547269483572617.


* Best trial for C-index:
 FrozenTrial(number=52, state=TrialState.COMPLETE, values=[0.8547269483572617], datetime_start=datetime.datetime(2024, 4, 18, 3, 33, 16, 196972), datetime_complete=datetime.datetime(2024, 4, 18, 3, 33, 19, 1729), params={'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.6101354912642183, 'max_features': None, 'min_weight_fraction_leaf': 0.00292920588368519, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=52, value=None)


* Best Score for C-index:
 0.8547269483572617

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17432280028285926
Fold 2 IBS: 0.2006813659286043
Fold 3 IBS: 0.15533531880169518
Fold 4 IBS: 0.15195911088051248
Fold 5 IBS: 0.212315715039292
[I 2024-04-18 03:35:54,644] Trial 0 finished with value: 0.17892286218659265 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.17892286218659265.
Fold 1 IBS: 0.17301116909018519
Fold 2 IBS: 0.1817348791108214
Fold 3 IBS: 0.16206548582053415
Fold 4 IBS: 0.1586849125345364
Fold 5 IBS: 0.2085275440348435
[I 2024-04-18 03:35:58,301] Trial 1 finished with value: 0.17680479811818411 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.17680479811818411.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-18 03:36:01,003] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.17680479811818411.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-18 03:36:11,705] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.17680479811818411.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-18 03:36:19,294] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.17680479811818411.
Fold 1 IBS: 0.1775350998344488
Fold 2 IBS: 0.17268313404241536
Fold 3 IBS: 0.15489494699395592
Fold 4 IBS: 0.14341756961216387
Fold 5 IBS: 0.20668801394045683
[I 2024-04-18 03:36:30,311] Trial 5 finished with value: 0.17104375288468815 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.17790345722649678
Fold 2 IBS: 0.1965272685476368
Fold 3 IBS: 0.16112200723346068
Fold 4 IBS: 0.16269206929716898
Fold 5 IBS: 0.2178149975416176
[I 2024-04-18 03:36:41,583] Trial 6 finished with value: 0.18321195996927617 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.2117245055920345
Fold 2 IBS: 0.21715780916568633
Fold 3 IBS: 0.20090753630706465
Fold 4 IBS: 0.21948688173821643
Fold 5 IBS: 0.2155915746070692
[I 2024-04-18 03:36:54,947] Trial 7 finished with value: 0.21297366148201421 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-18 03:37:15,900] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.1715478692476039
Fold 2 IBS: 0.1841236864286879
Fold 3 IBS: 0.16362500039767222
Fold 4 IBS: 0.16007485354576811
Fold 5 IBS: 0.20800869316735476
[I 2024-04-18 03:37:19,868] Trial 9 finished with value: 0.17747602055741737 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-18 03:37:41,637] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.17951075922824541
Fold 2 IBS: 0.17368929373724368
Fold 3 IBS: 0.1648718402987931
Fold 4 IBS: 0.16088899414505065
Fold 5 IBS: 0.20322861904323372
[I 2024-04-18 03:37:47,185] Trial 11 finished with value: 0.17643790129051332 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.18348245397603796
Fold 2 IBS: 0.1712636387397596
Fold 3 IBS: 0.1658727827747381
Fold 4 IBS: 0.16090400897582507
Fold 5 IBS: 0.20121079620985316
[I 2024-04-18 03:37:54,263] Trial 12 finished with value: 0.1765467361352428 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.7702835685563957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10911904675719894}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.1803295085927232
Fold 2 IBS: 0.17150826839622924
Fold 3 IBS: 0.1566215629941073
Fold 4 IBS: 0.14516684070606306
Fold 5 IBS: 0.207369273538545
[I 2024-04-18 03:38:09,424] Trial 13 finished with value: 0.1721990908455336 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.9282504676473301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12374300016371276}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.1842225852461467
Fold 2 IBS: 0.19317628789562033
Fold 3 IBS: 0.14326580100642589
Fold 4 IBS: 0.14359132300608848
Fold 5 IBS: 0.20677438731766776
[I 2024-04-18 03:38:23,443] Trial 14 finished with value: 0.1742060768943898 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.9251470726314446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 5 with value: 0.17104375288468815.
Fold 1 IBS: 0.17260791773487638
Fold 2 IBS: 0.18417351073603846
Fold 3 IBS: 0.1625660709006057
Fold 4 IBS: 0.161909577218114
Fold 5 IBS: 0.20736978456712454
[I 2024-04-18 03:38:39,284] Trial 15 finished with value: 0.17772537223135182 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 349, 'oob_score': False, 'max_samples': 0.9965570573958813, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 5 with value: 0.17104375288468815.

Fold 1 IBS: 0.17970672904514542
Fold 2 IBS: 0.17027540409579162
Fold 3 IBS: 0.15654147285342387
Fold 4 IBS: 0.14236509886130494
Fold 5 IBS: 0.20608096332846523
[I 2024-04-18 03:38:49,530] Trial 16 finished with value: 0.17099393363682625 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.8234447119724944, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09668995910437887}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17750852877513895
Fold 2 IBS: 0.17132861571804714
Fold 3 IBS: 0.15769275345386496
Fold 4 IBS: 0.15012057331931083
Fold 5 IBS: 0.2062175667919279
[I 2024-04-18 03:38:59,380] Trial 17 finished with value: 0.17257360761165796 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06831595455922632}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17701197178731462
Fold 2 IBS: 0.17557730171939878
Fold 3 IBS: 0.16223217983330354
Fold 4 IBS: 0.1552423244281697
Fold 5 IBS: 0.20379736628803732
[I 2024-04-18 03:39:08,158] Trial 18 finished with value: 0.1747722288112448 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.8057152920773529, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16329824626140826}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17311663394924395
Fold 2 IBS: 0.17014928389691775
Fold 3 IBS: 0.15743374096005405
Fold 4 IBS: 0.15924793659612185
Fold 5 IBS: 0.19835588915088992
[I 2024-04-18 03:39:09,121] Trial 19 finished with value: 0.17166069691064548 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.4386108822397098, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0609880983110333}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.2139824603476573
Fold 2 IBS: 0.22076301546750526
Fold 3 IBS: 0.2049758106558972
Fold 4 IBS: 0.2244757018551852
Fold 5 IBS: 0.2178416315818093
[I 2024-04-18 03:39:21,810] Trial 20 finished with value: 0.21640772398161084 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.23419761201309758, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17796183938463656
Fold 2 IBS: 0.16968932103504233
Fold 3 IBS: 0.1601523367292968
Fold 4 IBS: 0.16026382504894057
Fold 5 IBS: 0.19368118183186095
[I 2024-04-18 03:39:22,650] Trial 21 finished with value: 0.17234970080595544 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 7, 'oob_score': False, 'max_samples': 0.42504221478450555, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06336248059083428}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17356440118569855
Fold 2 IBS: 0.17968969335381346
Fold 3 IBS: 0.15747898849039987
Fold 4 IBS: 0.1659472724727291
Fold 5 IBS: 0.20094573059680096
[I 2024-04-18 03:39:23,678] Trial 22 finished with value: 0.1755252172198884 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.4063791952194803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.009956757895680707}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17715477595442
Fold 2 IBS: 0.1723690318864778
Fold 3 IBS: 0.15955490652392423
Fold 4 IBS: 0.1509419244109627
Fold 5 IBS: 0.20581136009217943
[I 2024-04-18 03:39:32,548] Trial 23 finished with value: 0.17316639977359283 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.6126658112372655, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09022630723104608}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.1745079864535986
Fold 2 IBS: 0.18211987803189605
Fold 3 IBS: 0.1623710772941786
Fold 4 IBS: 0.17027023138587988
Fold 5 IBS: 0.20430847149758302
[I 2024-04-18 03:39:35,440] Trial 24 finished with value: 0.17871552893262724 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 79, 'oob_score': False, 'max_samples': 0.4938357936295485, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15990380035887097}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17556573537645587
Fold 2 IBS: 0.17428479734065422
Fold 3 IBS: 0.1587260103730713
Fold 4 IBS: 0.1517149445372683
Fold 5 IBS: 0.20418008236649787
[I 2024-04-18 03:39:45,936] Trial 25 finished with value: 0.17289431399878952 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.2988517774381766, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04874951847370966}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17777694198046762
Fold 2 IBS: 0.17363139881433293
Fold 3 IBS: 0.15815474943382182
Fold 4 IBS: 0.15006732895498495
Fold 5 IBS: 0.20698168406525022
[I 2024-04-18 03:40:07,203] Trial 26 finished with value: 0.1733224206497715 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 476, 'oob_score': True, 'max_samples': 0.8219220523482779, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13480147594200903}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.1730639557557264
Fold 2 IBS: 0.18243740652428672
Fold 3 IBS: 0.16155757113883212
Fold 4 IBS: 0.16054630364974284
Fold 5 IBS: 0.20509557207712412
[I 2024-04-18 03:40:13,933] Trial 27 finished with value: 0.17654016182914245 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 189, 'oob_score': False, 'max_samples': 0.6767226787475958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1848211474281298}. Best is trial 16 with value: 0.17099393363682625.
Fold 1 IBS: 0.17528983496869716
Fold 2 IBS: 0.16909938585915346
Fold 3 IBS: 0.15616169248939848
Fold 4 IBS: 0.14094746176806686
Fold 5 IBS: 0.208032258762365
[I 2024-04-18 03:40:18,454] Trial 28 finished with value: 0.16990612676953618 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.5983696686089446, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04831248814320596}. Best is trial 28 with value: 0.16990612676953618.
Fold 1 IBS: 0.17705065149323665
Fold 2 IBS: 0.1701433065466141
Fold 3 IBS: 0.1583344729653253
Fold 4 IBS: 0.14392457747170861
Fold 5 IBS: 0.20810062161187415
[I 2024-04-18 03:40:22,756] Trial 29 finished with value: 0.17151072601775177 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.7137403943754692, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09494028655145086}. Best is trial 28 with value: 0.16990612676953618.
Fold 1 IBS: 0.18151028631259342
Fold 2 IBS: 0.19100771648812856
Fold 3 IBS: 0.16635735117279463
Fold 4 IBS: 0.17380626288576334
Fold 5 IBS: 0.20838787145326873
[I 2024-04-18 03:40:30,375] Trial 30 finished with value: 0.18421389766250976 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 245, 'oob_score': False, 'max_samples': 0.6004128561703262, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21824325749115198}. Best is trial 28 with value: 0.16990612676953618.
Fold 1 IBS: 0.17854997685628718
Fold 2 IBS: 0.16956170749586177
Fold 3 IBS: 0.1585611073977436
Fold 4 IBS: 0.14439889476662063

Fold 5 IBS: 0.20606070459603618
[I 2024-04-18 03:40:35,649] Trial 31 finished with value: 0.17142647822250986 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7191779197966834, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0953426015021738}. Best is trial 28 with value: 0.16990612676953618.
Fold 1 IBS: 0.18250138852812883
Fold 2 IBS: 0.17113429637227343
Fold 3 IBS: 0.14623517642012188
Fold 4 IBS: 0.1363752556022476
Fold 5 IBS: 0.20606526324852095
[I 2024-04-18 03:40:41,859] Trial 32 finished with value: 0.16846227603425853 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 177, 'oob_score': False, 'max_samples': 0.7002017603582902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.037741041052811355}. Best is trial 32 with value: 0.16846227603425853.
Fold 1 IBS: 0.18202492847751467
Fold 2 IBS: 0.17352991864272319
Fold 3 IBS: 0.14805676546531768
Fold 4 IBS: 0.13729863900654585
Fold 5 IBS: 0.20734109730972275
[I 2024-04-18 03:40:48,116] Trial 33 finished with value: 0.16965026978036482 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.6506759459401269, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03983031219338032}. Best is trial 32 with value: 0.16846227603425853.
Fold 1 IBS: 0.182007102212863
Fold 2 IBS: 0.16911548370839807
Fold 3 IBS: 0.15650338429443955
Fold 4 IBS: 0.14644687622280647
Fold 5 IBS: 0.2034776448409133
[I 2024-04-18 03:40:54,681] Trial 34 finished with value: 0.1715100982558841 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 177, 'oob_score': False, 'max_samples': 0.7677590098746963, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03146472047090974}. Best is trial 32 with value: 0.16846227603425853.
Fold 1 IBS: 0.21617132294089053
Fold 2 IBS: 0.17902318452740637
Fold 3 IBS: 0.1636968304344599
Fold 4 IBS: 0.14237605469256134
Fold 5 IBS: 0.1991390461985105
[I 2024-04-18 03:40:59,524] Trial 35 finished with value: 0.18008128775876572 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 81, 'oob_score': True, 'max_samples': 0.5128073742508867, 'max_features': None, 'min_weight_fraction_leaf': 0.03863245785049326}. Best is trial 32 with value: 0.16846227603425853.
Fold 1 IBS: 0.18116394796022914
Fold 2 IBS: 0.17690274714631918
Fold 3 IBS: 0.15071607322829184
Fold 4 IBS: 0.1403311901509947
Fold 5 IBS: 0.1914315077726891
[I 2024-04-18 03:41:01,633] Trial 36 finished with value: 0.1681090932517048 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 49, 'oob_score': False, 'max_samples': 0.5763668360241782, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007750736023967503}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.19145630742611153
Fold 2 IBS: 0.19202794233087261
Fold 3 IBS: 0.14528979838897937
Fold 4 IBS: 0.1474291971723275
Fold 5 IBS: 0.1969755653326385
[I 2024-04-18 03:41:04,227] Trial 37 finished with value: 0.1746357621301859 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.5690972663682833, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.005417920898763515}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.21435878786799
Fold 2 IBS: 0.16668235947164708
Fold 3 IBS: 0.1675336494397426
Fold 4 IBS: 0.1457930805319192
Fold 5 IBS: 0.199920450941313
[I 2024-04-18 03:41:06,153] Trial 38 finished with value: 0.17885766565052238 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.4797161635200389, 'max_features': None, 'min_weight_fraction_leaf': 0.0014760892526849865}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.21440128774106526
Fold 2 IBS: 0.2127240801135452
Fold 3 IBS: 0.19648449969852647
Fold 4 IBS: 0.2186382088432412
Fold 5 IBS: 0.21868198213160003
[I 2024-04-18 03:41:11,068] Trial 39 finished with value: 0.21218601170559565 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 104, 'oob_score': True, 'max_samples': 0.6691454218975617, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33228094235869554}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1749628618833177
Fold 2 IBS: 0.17021687070109442
Fold 3 IBS: 0.15884819566587624
Fold 4 IBS: 0.1401983876284967
Fold 5 IBS: 0.20408479674255947
[I 2024-04-18 03:41:15,548] Trial 40 finished with value: 0.1696622225242689 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 118, 'oob_score': False, 'max_samples': 0.5726855054748385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04420597355465883}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1728576398465139
Fold 2 IBS: 0.16866591058153557
Fold 3 IBS: 0.15955875780665055
Fold 4 IBS: 0.14138663471206678
Fold 5 IBS: 0.2049139403781731
[I 2024-04-18 03:41:19,574] Trial 41 finished with value: 0.169476576664988 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.5432743507188259, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03919743521455694}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17958222167635124
Fold 2 IBS: 0.16585405110901014
Fold 3 IBS: 0.16240255766844297
Fold 4 IBS: 0.1497070092915767
Fold 5 IBS: 0.19360072526574915
[I 2024-04-18 03:41:21,663] Trial 42 finished with value: 0.17022931300222605 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 43, 'oob_score': False, 'max_samples': 0.5479540080333131, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03468981849767226}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.21403568612926072
Fold 2 IBS: 0.2216110373757573
Fold 3 IBS: 0.2048250818629514
Fold 4 IBS: 0.2247603387818673
Fold 5 IBS: 0.21855106466972882
[I 2024-04-18 03:41:29,199] Trial 43 finished with value: 0.21675664176391313 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.653863137347239, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1775254266055598
Fold 2 IBS: 0.16444186154680948
Fold 3 IBS: 0.16043671992563005
Fold 4 IBS: 0.14706810521177968
Fold 5 IBS: 0.2061992959858679
[I 2024-04-18 03:41:34,856] Trial 44 finished with value: 0.1711342818551294 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.5593489786564455, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07190804718693572}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17615082386970493
Fold 2 IBS: 0.1818101471067841
Fold 3 IBS: 0.16418646328253964
Fold 4 IBS: 0.1722293962501012
Fold 5 IBS: 0.20114485441274257
[I 2024-04-18 03:41:37,149] Trial 45 finished with value: 0.17910433698437447 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 62, 'oob_score': False, 'max_samples': 0.46003862628586406, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.139133134500834}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.19404934873846166
Fold 2 IBS: 0.16905379759190214
Fold 3 IBS: 0.16405638797073627
Fold 4 IBS: 0.14665718841448488
Fold 5 IBS: 0.20208750120696412
[I 2024-04-18 03:41:41,138] Trial 46 finished with value: 0.1751808447845098 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.3652137153949424, 'max_features': None, 'min_weight_fraction_leaf': 0.02421565578880429}. Best is trial 36 with value: 0.1681090932517048.

Fold 1 IBS: 0.2140121718199979
Fold 2 IBS: 0.22149935338683438
Fold 3 IBS: 0.2047666373465207
Fold 4 IBS: 0.22488209831535308
Fold 5 IBS: 0.2183757411797355
[I 2024-04-18 03:41:47,185] Trial 47 finished with value: 0.21670720040968833 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 130, 'oob_score': True, 'max_samples': 0.5234170058690094, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38143282767559583}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.2139972127669122
Fold 2 IBS: 0.22124358236933428
Fold 3 IBS: 0.2047527974187217
Fold 4 IBS: 0.22464662730656376
Fold 5 IBS: 0.2185790125333401
[I 2024-04-18 03:41:50,388] Trial 48 finished with value: 0.2166438464789744 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6960402324901204, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.18093311832953088
Fold 2 IBS: 0.19327339747555697
Fold 3 IBS: 0.16660455777517189
Fold 4 IBS: 0.17671885362984516
Fold 5 IBS: 0.20710836341989913
[I 2024-04-18 03:41:56,812] Trial 49 finished with value: 0.18492765812600082 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.6310709435011317, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.110018627706295}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17385334636396446
Fold 2 IBS: 0.18081012499435198
Fold 3 IBS: 0.16211319796290766
Fold 4 IBS: 0.15917625631026688
Fold 5 IBS: 0.20365449925612095
[I 2024-04-18 03:42:02,739] Trial 50 finished with value: 0.1759214849775224 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.5842844308689883, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05087430077175225}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17387977772112667
Fold 2 IBS: 0.17444132593271255
Fold 3 IBS: 0.15122743088397955
Fold 4 IBS: 0.13382316473493042
Fold 5 IBS: 0.20985615339171332
[I 2024-04-18 03:42:07,373] Trial 51 finished with value: 0.1686455705328925 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.7480562057451934, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.046443293330720774}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17642619091650108
Fold 2 IBS: 0.1723514757104842
Fold 3 IBS: 0.15020661546295289
Fold 4 IBS: 0.13576195499924226
Fold 5 IBS: 0.20757352001175405
[I 2024-04-18 03:42:11,987] Trial 52 finished with value: 0.16846395142018689 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.7558313049825359, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02326186340257988}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.18334590964069045
Fold 2 IBS: 0.1832071594369267
Fold 3 IBS: 0.15110372822730533
Fold 4 IBS: 0.14520178142852394
Fold 5 IBS: 0.20851135164244058
[I 2024-04-18 03:42:13,792] Trial 53 finished with value: 0.17427398607517738 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 34, 'oob_score': False, 'max_samples': 0.7670628606362005, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018773679794660967}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17791261933620836
Fold 2 IBS: 0.1740397464422404
Fold 3 IBS: 0.1513406781054756
Fold 4 IBS: 0.1386905577856325
Fold 5 IBS: 0.20675798429012407
[I 2024-04-18 03:42:16,853] Trial 54 finished with value: 0.16974831719193617 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 71, 'oob_score': False, 'max_samples': 0.8820414246399852, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07480814018533534}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17759020880569407
Fold 2 IBS: 0.16775586862616937
Fold 3 IBS: 0.15536687404003147
Fold 4 IBS: 0.1390454514177599
Fold 5 IBS: 0.20818254562586966
[I 2024-04-18 03:42:21,056] Trial 55 finished with value: 0.1695881897031049 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.7554486449918063, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021057433542374365}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1771267522108156
Fold 2 IBS: 0.16932688056278278
Fold 3 IBS: 0.1540974937169809
Fold 4 IBS: 0.14015169723414994
Fold 5 IBS: 0.20823778180026092
[I 2024-04-18 03:42:24,540] Trial 56 finished with value: 0.16978812110499802 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.7595924216922594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002456224753917373}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.173453794185439
Fold 2 IBS: 0.18639230970140092
Fold 3 IBS: 0.1614952933386796
Fold 4 IBS: 0.16272914737273322
Fold 5 IBS: 0.2057585299192617
[I 2024-04-18 03:42:29,926] Trial 57 finished with value: 0.17796581490350288 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.7312351998580664, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01978427187460409}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1786202121404072
Fold 2 IBS: 0.17204822463662076
Fold 3 IBS: 0.15610477118018798
Fold 4 IBS: 0.14131696086577022
Fold 5 IBS: 0.2069431335623666
[I 2024-04-18 03:42:31,485] Trial 58 finished with value: 0.17100666047707053 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 28, 'oob_score': False, 'max_samples': 0.8491003336494423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08202371447367077}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17908819249623995
Fold 2 IBS: 0.1721345371493133
Fold 3 IBS: 0.15306773563616574
Fold 4 IBS: 0.14062504196253273
Fold 5 IBS: 0.196914917298641
[I 2024-04-18 03:42:34,516] Trial 59 finished with value: 0.16836608490857852 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.9625340458355495, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05866557442768695}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.21463244766087508
Fold 2 IBS: 0.1754849731430422
Fold 3 IBS: 0.17600409626435298
Fold 4 IBS: 0.14882352465148077
Fold 5 IBS: 0.2042402060417914
[I 2024-04-18 03:42:37,622] Trial 60 finished with value: 0.18383704955230848 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.9414041382529451, 'max_features': None, 'min_weight_fraction_leaf': 0.11865577446314957}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17687852434154777
Fold 2 IBS: 0.17304377963275822
Fold 3 IBS: 0.15496233556120056
Fold 4 IBS: 0.1413636254723574
Fold 5 IBS: 0.20555200447683158
[I 2024-04-18 03:42:42,490] Trial 61 finished with value: 0.17036005389693912 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 99, 'oob_score': True, 'max_samples': 0.9706873314530691, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05907891264937369}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.18438911214122927
Fold 2 IBS: 0.17867327799290353
Fold 3 IBS: 0.14536377431011266
Fold 4 IBS: 0.14088527326926767
Fold 5 IBS: 0.21122446693247196
[I 2024-04-18 03:42:44,265] Trial 62 finished with value: 0.17210718092919702 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.8750238525723645, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026348917677077782}. Best is trial 36 with value: 0.1681090932517048.

Fold 1 IBS: 0.1766842532379171
Fold 2 IBS: 0.1698257997704228
Fold 3 IBS: 0.15680662914587148
Fold 4 IBS: 0.14176388782718463
Fold 5 IBS: 0.20453883734596576
[I 2024-04-18 03:42:48,352] Trial 63 finished with value: 0.16992388146547238 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 82, 'oob_score': True, 'max_samples': 0.7967542684659779, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06784168011112049}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.18432304609942296
Fold 2 IBS: 0.17230962226867122
Fold 3 IBS: 0.15160216224521647
Fold 4 IBS: 0.1391825722296759
Fold 5 IBS: 0.2017956551731704
[I 2024-04-18 03:42:51,873] Trial 64 finished with value: 0.16984261160323139 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.8456585073090606, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0007181934743661321}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.2140196571846823
Fold 2 IBS: 0.22038704346496749
Fold 3 IBS: 0.20639509883012647
Fold 4 IBS: 0.22955024364530058
Fold 5 IBS: 0.2262875094292232
[I 2024-04-18 03:42:52,533] Trial 65 finished with value: 0.21932791051086 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 1, 'oob_score': False, 'max_samples': 0.7970901189784103, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08087921163428681}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17361842480416634
Fold 2 IBS: 0.1729323962168809
Fold 3 IBS: 0.16046698450139374
Fold 4 IBS: 0.13975067012990078
Fold 5 IBS: 0.20730513191171443
[I 2024-04-18 03:42:57,927] Trial 66 finished with value: 0.17081472151281124 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.7495956248163956, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018925133674274553}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.18097892507538202
Fold 2 IBS: 0.1794702386506798
Fold 3 IBS: 0.14721536052665635
Fold 4 IBS: 0.13804751939985616
Fold 5 IBS: 0.2095326633743413
[I 2024-04-18 03:43:04,178] Trial 67 finished with value: 0.17104894140538313 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 134, 'oob_score': True, 'max_samples': 0.9073893430191249, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.048421079770112216}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1847005067440449
Fold 2 IBS: 0.16688881434926162
Fold 3 IBS: 0.1597418241471375
Fold 4 IBS: 0.15014593394266745
Fold 5 IBS: 0.19655370111846882
[I 2024-04-18 03:43:06,522] Trial 68 finished with value: 0.17160615606031607 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 52, 'oob_score': False, 'max_samples': 0.6942022441076907, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10420304208035429}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1774960643967032
Fold 2 IBS: 0.1684678656769401
Fold 3 IBS: 0.15278588165359427
Fold 4 IBS: 0.14136188776210465
Fold 5 IBS: 0.20852528836056203
[I 2024-04-18 03:43:15,120] Trial 69 finished with value: 0.16972739756998087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.617566390593802, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.059218936356063706}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.18013832406818914
Fold 2 IBS: 0.16698644975199545
Fold 3 IBS: 0.15449932330473085
Fold 4 IBS: 0.1409349913184949
Fold 5 IBS: 0.2070564761032307
[I 2024-04-18 03:43:21,851] Trial 70 finished with value: 0.1699231129093282 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.6917414996198523, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.034872278578711086}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1800930647826443
Fold 2 IBS: 0.1736387610322269
Fold 3 IBS: 0.1507147943824891
Fold 4 IBS: 0.1349120230089097
Fold 5 IBS: 0.20775826480563445
[I 2024-04-18 03:43:28,005] Trial 71 finished with value: 0.16942338160238088 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 151, 'oob_score': False, 'max_samples': 0.6401561895870445, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03717722812158214}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.18264038612071484
Fold 2 IBS: 0.17388770742525148
Fold 3 IBS: 0.14952406721646827
Fold 4 IBS: 0.13655035774944596
Fold 5 IBS: 0.20638737909527496
[I 2024-04-18 03:43:33,872] Trial 72 finished with value: 0.1697979795214311 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.6391601681414784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020828148715159523}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17742735942329269
Fold 2 IBS: 0.1700803242476587
Fold 3 IBS: 0.1564632004853038
Fold 4 IBS: 0.13788139509529437
Fold 5 IBS: 0.21056997354023585
[I 2024-04-18 03:43:39,465] Trial 73 finished with value: 0.1704844505583571 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 127, 'oob_score': False, 'max_samples': 0.7281020316799526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.055246446508912486}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.17521473586456338
Fold 2 IBS: 0.17076723344674996
Fold 3 IBS: 0.15984492637217784
Fold 4 IBS: 0.14882139902948405
Fold 5 IBS: 0.2067198557760357
[I 2024-04-18 03:43:44,410] Trial 74 finished with value: 0.1722736300978022 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.5358038004036295, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08644047687602452}. Best is trial 36 with value: 0.1681090932517048.
Fold 1 IBS: 0.1749122557638621
Fold 2 IBS: 0.17336302282315733
Fold 3 IBS: 0.14857514101490524
Fold 4 IBS: 0.13547725582763748
Fold 5 IBS: 0.20424094880848753
[I 2024-04-18 03:43:48,640] Trial 75 finished with value: 0.16731372484760992 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.7880751381267705, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010141521629227908}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.17755406737708335
Fold 2 IBS: 0.16991880750698207
Fold 3 IBS: 0.15607448097308194
Fold 4 IBS: 0.14469989539854713
Fold 5 IBS: 0.20373768362252886
[I 2024-04-18 03:44:01,522] Trial 76 finished with value: 0.17039698697564468 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.7908561309812306, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.011359902488224577}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.1844361906795916
Fold 2 IBS: 0.1806068336895798
Fold 3 IBS: 0.15335858576810127
Fold 4 IBS: 0.14020655605956023
Fold 5 IBS: 0.20805971851005087
[I 2024-04-18 03:44:08,013] Trial 77 finished with value: 0.17333357694137677 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.8245623118408627, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03582821032188176}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.21397559631456245
Fold 2 IBS: 0.22122946191474388
Fold 3 IBS: 0.20469300107034638
Fold 4 IBS: 0.22466789866684478
Fold 5 IBS: 0.2180572038005507
[I 2024-04-18 03:44:14,432] Trial 78 finished with value: 0.21652463235340963 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.4981877286523601, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.28987424398930645}. Best is trial 75 with value: 0.16731372484760992.

Fold 1 IBS: 0.20024801689348162
Fold 2 IBS: 0.2057130041741153
Fold 3 IBS: 0.1962060834371484
Fold 4 IBS: 0.21051437171900578
Fold 5 IBS: 0.20833522870797178
[I 2024-04-18 03:44:16,812] Trial 79 finished with value: 0.20420334098634457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04303701256971175}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.22003650915905537
Fold 2 IBS: 0.17780026433656795
Fold 3 IBS: 0.17858928964906395
Fold 4 IBS: 0.1469680858174885
Fold 5 IBS: 0.20607478690239545
[I 2024-04-18 03:44:26,806] Trial 80 finished with value: 0.18589378717291424 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.9999277178523378, 'max_features': None, 'min_weight_fraction_leaf': 0.14011820077961568}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.17711539529868295
Fold 2 IBS: 0.17019128130023292
Fold 3 IBS: 0.15294346497713865
Fold 4 IBS: 0.13979480783248263
Fold 5 IBS: 0.20735494305570604
[I 2024-04-18 03:44:31,870] Trial 81 finished with value: 0.16947997849284863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.6664037893612326, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014285426484566889}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.18189630458037284
Fold 2 IBS: 0.17482548080420665
Fold 3 IBS: 0.14961566182450417
Fold 4 IBS: 0.14033808738381656
Fold 5 IBS: 0.19999677513013034
[I 2024-04-18 03:44:35,126] Trial 82 finished with value: 0.16933446194460613 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.6691157200893793, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007611563064758395}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.17458335768432162
Fold 2 IBS: 0.1793118590100365
Fold 3 IBS: 0.13622316913786414
Fold 4 IBS: 0.1432253509865797
Fold 5 IBS: 0.20863821044030575
[I 2024-04-18 03:44:36,651] Trial 83 finished with value: 0.16839638945182153 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7106576916737541, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03210380013622877}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.19617396170041976
Fold 2 IBS: 0.19339991364529074
Fold 3 IBS: 0.1312057178645974
Fold 4 IBS: 0.1428425237141314
Fold 5 IBS: 0.22912630795885144
[I 2024-04-18 03:44:38,082] Trial 84 finished with value: 0.17854968497665816 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 22, 'oob_score': False, 'max_samples': 0.708472461867885, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002159126310801276}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.18892867319097634
Fold 2 IBS: 0.1818120590348582
Fold 3 IBS: 0.14557245864500812
Fold 4 IBS: 0.13936243667036455
Fold 5 IBS: 0.20446685587069097
[I 2024-04-18 03:44:39,502] Trial 85 finished with value: 0.17202849668237966 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 15, 'oob_score': False, 'max_samples': 0.6805505376375054, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.030266318096609787}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.1777063926325626
Fold 2 IBS: 0.1654246093877602
Fold 3 IBS: 0.15917547476177152
Fold 4 IBS: 0.1425206046224599
Fold 5 IBS: 0.19703268513197814
[I 2024-04-18 03:44:42,342] Trial 86 finished with value: 0.16837195330730648 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 52, 'oob_score': False, 'max_samples': 0.6018200742002654, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05989516394997697}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.17482820810449096
Fold 2 IBS: 0.16619130582928082
Fold 3 IBS: 0.1565055008732945
Fold 4 IBS: 0.14271083034901283
Fold 5 IBS: 0.19791046161359468
[I 2024-04-18 03:44:45,448] Trial 87 finished with value: 0.16762926135393477 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 62, 'oob_score': False, 'max_samples': 0.6056949882125103, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06298678673147812}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.17355607544922472
Fold 2 IBS: 0.16883777443558387
Fold 3 IBS: 0.16378491650908017
Fold 4 IBS: 0.14608609698586192
Fold 5 IBS: 0.19571643968957048
[I 2024-04-18 03:44:47,897] Trial 88 finished with value: 0.16959626061386426 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.607777006280668, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06762856486025606}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.1790050889889775
Fold 2 IBS: 0.17269730336086744
Fold 3 IBS: 0.15865238649892563
Fold 4 IBS: 0.14605282283566126
Fold 5 IBS: 0.19832322750477308
[I 2024-04-18 03:44:51,238] Trial 89 finished with value: 0.17094616583784097 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 56, 'oob_score': False, 'max_samples': 0.711881953706759, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09384160268959234}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.1798543472979729
Fold 2 IBS: 0.1675793445238802
Fold 3 IBS: 0.14310293669014448
Fold 4 IBS: 0.13972934882435228
Fold 5 IBS: 0.20653436605153888
[I 2024-04-18 03:44:53,853] Trial 90 finished with value: 0.16736006867757774 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 14, 'oob_score': True, 'max_samples': 0.5795863901139069, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05301608689235721}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.1772909528815579
Fold 2 IBS: 0.16804432300764346
Fold 3 IBS: 0.147188552355611
Fold 4 IBS: 0.13927483725517617
Fold 5 IBS: 0.2153062731479444
[I 2024-04-18 03:44:55,671] Trial 91 finished with value: 0.16942098772958658 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 12, 'oob_score': True, 'max_samples': 0.586738597164626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05584424617104539}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.18106253501452346
Fold 2 IBS: 0.1750015033084707
Fold 3 IBS: 0.16016855427665247
Fold 4 IBS: 0.14283278204021993
Fold 5 IBS: 0.20462465388551437
[I 2024-04-18 03:44:58,804] Trial 92 finished with value: 0.17273800570507616 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 31, 'oob_score': True, 'max_samples': 0.5576882674389484, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04874927112218723}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.17556003198795678
Fold 2 IBS: 0.16881821956857523
Fold 3 IBS: 0.1551360824406135
Fold 4 IBS: 0.14375918256666922
Fold 5 IBS: 0.2025894851776773
[I 2024-04-18 03:45:03,392] Trial 93 finished with value: 0.1691726003482984 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.623082616745604, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06972763014279589}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.18149035530916807
Fold 2 IBS: 0.163294091088014
Fold 3 IBS: 0.15690140435541775
Fold 4 IBS: 0.14970546693553755
Fold 5 IBS: 0.1958823828389738
[I 2024-04-18 03:45:06,687] Trial 94 finished with value: 0.16945474010542222 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 46, 'oob_score': True, 'max_samples': 0.6510330851440451, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08340709829554152}. Best is trial 75 with value: 0.16731372484760992.

Fold 1 IBS: 0.19197606811810808
Fold 2 IBS: 0.15832469275331668
Fold 3 IBS: 0.15508398644550617
Fold 4 IBS: 0.17886741180476176
Fold 5 IBS: 0.1922677833948585
[I 2024-04-18 03:45:07,889] Trial 95 finished with value: 0.17530398850331025 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.785839145990297, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10722424812745346}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.17318005344396062
Fold 2 IBS: 0.18079748347172456
Fold 3 IBS: 0.14761255568940362
Fold 4 IBS: 0.13827071021934526
Fold 5 IBS: 0.20015023689231282
[I 2024-04-18 03:45:12,765] Trial 96 finished with value: 0.16800220794334936 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 92, 'oob_score': False, 'max_samples': 0.5947494725419651, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03101741053094137}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.1746006936436532
Fold 2 IBS: 0.18444844482293382
Fold 3 IBS: 0.14576604245763658
Fold 4 IBS: 0.1345129521534403
Fold 5 IBS: 0.21384139720738918
[I 2024-04-18 03:45:14,759] Trial 97 finished with value: 0.17063390605701062 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.5819760819747651, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03116088199105258}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.22994391704446174
Fold 2 IBS: 0.19193004585915127
Fold 3 IBS: 0.17347695122359616
Fold 4 IBS: 0.15621805551005194
Fold 5 IBS: 0.2004423671943246
[I 2024-04-18 03:45:20,512] Trial 98 finished with value: 0.19040226736631716 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 94, 'oob_score': True, 'max_samples': 0.6075227539473252, 'max_features': None, 'min_weight_fraction_leaf': 0.014470255170349403}. Best is trial 75 with value: 0.16731372484760992.
Fold 1 IBS: 0.1756726320090515
Fold 2 IBS: 0.16635479218102295
Fold 3 IBS: 0.15785591478835945
Fold 4 IBS: 0.14260920881680997
Fold 5 IBS: 0.196642896187843
[I 2024-04-18 03:45:24,043] Trial 99 finished with value: 0.1678270887966174 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 65, 'oob_score': False, 'max_samples': 0.5288491597598475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06287039217444472}. Best is trial 75 with value: 0.16731372484760992.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.16731372484760992], datetime_start=datetime.datetime(2024, 4, 18, 3, 43, 44, 426268), datetime_complete=datetime.datetime(2024, 4, 18, 3, 43, 48, 638603), params={'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.7880751381267705, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.010141521629227908}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=75, value=None)


* Best Score for IBS:
 0.16731372484760992

In [56]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [57]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.855
train_ibs:  0.167

#### Test

In [58]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [59]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=18, max_features=None, max_leaf_nodes=11,
                     max_samples=0.6101354912642183, min_samples_leaf=2,
                     min_weight_fraction_leaf=0.00292920588368519,
                     n_estimators=193, random_state=123, warm_start=True)

test_cindex:  0.601

RandomSurvivalForest(max_depth=10, max_features='auto', max_leaf_nodes=19,
                     max_samples=0.7880751381267705, min_samples_leaf=5,
                     min_samples_split=3,
                     min_weight_fraction_leaf=0.010141521629227908,
                     n_estimators=93, random_state=123)

test_ibs:  0.218

In [60]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [61]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [62]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:45:26,787] A new study created in memory with name: no-name-9f680ce1-eba5-4ad3-9562-031e47730219

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:45:30,079] Trial 0 finished with value: 0.7997948270865746 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:45:38,748] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 03:45:56,020] Trial 2 finished with value: 0.7748176841685961 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:45:57,698] Trial 3 finished with value: 0.790110956415176 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:46:03,809] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:46:12,010] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:46:16,149] Trial 6 finished with value: 0.7980580880871774 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-18 03:46:26,637] Trial 7 finished with value: 0.7676064467424599 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.7857142857142857
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 03:46:27,237] Trial 8 finished with value: 0.7938208910324693 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6408450704225352
[I 2024-04-18 03:46:48,090] Trial 9 finished with value: 0.7700152332971634 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:46:55,402] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7997948270865746.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 03:46:59,449] Trial 11 finished with value: 0.8000676439557491 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 11 with value: 0.8000676439557491.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.636150234741784
[I 2024-04-18 03:47:02,796] Trial 12 finished with value: 0.7794613537403486 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.17085174271948028, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 11 with value: 0.8000676439557491.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.828125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6197183098591549
[I 2024-04-18 03:47:06,633] Trial 13 finished with value: 0.7767400782944014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 11 with value: 0.8000676439557491.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:47:10,320] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3469585144995889, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 11 with value: 0.8000676439557491.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8227848101265823

Fold 5 C-index: 0.7018779342723005
[I 2024-04-18 03:47:12,591] Trial 15 finished with value: 0.802352653285175 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 191, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9428730581718685, 'min_weight_fraction_leaf': 0.10116500366378353}. Best is trial 15 with value: 0.802352653285175.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:47:14,198] Trial 16 finished with value: 0.7748663575464383 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 122, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9902353348396513, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 15 with value: 0.802352653285175.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:47:16,475] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 202, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.13194823174834824, 'min_weight_fraction_leaf': 0.13041806082748592}. Best is trial 15 with value: 0.802352653285175.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:47:18,192] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.37698225012457987, 'min_weight_fraction_leaf': 0.20942828309906508}. Best is trial 15 with value: 0.802352653285175.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 03:47:19,823] Trial 19 finished with value: 0.8018289161399499 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.03206339697953203}. Best is trial 15 with value: 0.802352653285175.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:47:21,022] Trial 20 finished with value: 0.7776054077119592 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 76, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8863532757005667, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 15 with value: 0.802352653285175.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 03:47:23,248] Trial 21 finished with value: 0.8008928142968237 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 192, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9104915743159242, 'min_weight_fraction_leaf': 0.04716588401379651}. Best is trial 15 with value: 0.802352653285175.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:47:25,852] Trial 22 finished with value: 0.8030607257003515 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 205, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8954132904841188, 'min_weight_fraction_leaf': 0.08655573062655376}. Best is trial 22 with value: 0.8030607257003515.
Fold 1 C-index: 0.7813852813852814
Fold 2 C-index: 0.8370535714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 03:47:27,503] Trial 23 finished with value: 0.7956598112956264 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.678797536912676, 'min_weight_fraction_leaf': 0.10970007112438171}. Best is trial 22 with value: 0.8030607257003515.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.875
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6549295774647887
[I 2024-04-18 03:47:29,354] Trial 24 finished with value: 0.7920796740550708 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 155, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8882418658193099, 'min_weight_fraction_leaf': 0.16581940671944723}. Best is trial 22 with value: 0.8030607257003515.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 03:47:32,216] Trial 25 finished with value: 0.8026578384883184 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 222, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7004569451710407, 'min_weight_fraction_leaf': 0.06694749011505387}. Best is trial 22 with value: 0.8030607257003515.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6502347417840375
[I 2024-04-18 03:47:44,148] Trial 26 finished with value: 0.7810588087971861 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 239, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6818060766530107, 'min_weight_fraction_leaf': 0.0873936179240901}. Best is trial 22 with value: 0.8030607257003515.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:47:46,869] Trial 27 finished with value: 0.7858082811156522 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 244, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8389745479394377, 'min_weight_fraction_leaf': 0.24081146708616177}. Best is trial 22 with value: 0.8030607257003515.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6431924882629108
[I 2024-04-18 03:47:49,920] Trial 28 finished with value: 0.7861160830480752 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9556158318301919, 'min_weight_fraction_leaf': 0.15791177329969786}. Best is trial 22 with value: 0.8030607257003515.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:47:52,411] Trial 29 finished with value: 0.8037877034312647 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 222, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7100680506168338, 'min_weight_fraction_leaf': 0.08340352485925032}. Best is trial 29 with value: 0.8037877034312647.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:47:55,215] Trial 30 finished with value: 0.8046315852878049 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7156936401685365, 'min_weight_fraction_leaf': 0.07846912416680743}. Best is trial 30 with value: 0.8046315852878049.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:47:57,953] Trial 31 finished with value: 0.8054973861536057 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7168475888391835, 'min_weight_fraction_leaf': 0.07589392630375186}. Best is trial 31 with value: 0.8054973861536057.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8549107142857143
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.687793427230047
[I 2024-04-18 03:48:00,127] Trial 32 finished with value: 0.7939169810657534 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 159, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6057936876454643, 'min_weight_fraction_leaf': 0.08392766595693793}. Best is trial 31 with value: 0.8054973861536057.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6830985915492958
[I 2024-04-18 03:48:03,250] Trial 33 finished with value: 0.7930134610773919 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 263, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7509589093602197, 'min_weight_fraction_leaf': 0.11530138651050185}. Best is trial 31 with value: 0.8054973861536057.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:48:05,600] Trial 34 finished with value: 0.8089530030313881 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 174, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7312854175900365, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 34 with value: 0.8089530030313881.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:48:09,766] Trial 35 finished with value: 0.8096529653450386 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 169, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7318686321241198, 'min_weight_fraction_leaf': 0.04498528481039678}. Best is trial 35 with value: 0.8096529653450386.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6784037558685446
[I 2024-04-18 03:48:18,243] Trial 36 finished with value: 0.7688319230348584 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 169, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5100231321714351, 'min_weight_fraction_leaf': 0.039290310785258006}. Best is trial 35 with value: 0.8096529653450386.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:48:21,383] Trial 37 finished with value: 0.8156936065727608 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6363503953184377, 'min_weight_fraction_leaf': 0.018959619334712893}. Best is trial 37 with value: 0.8156936065727608.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:48:24,514] Trial 38 finished with value: 0.8190450814841892 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 130, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6065355368718542, 'min_weight_fraction_leaf': 0.01996421689039931}. Best is trial 38 with value: 0.8190450814841892.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:48:29,259] Trial 39 finished with value: 0.7650200569944181 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 83, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.632157236595463, 'min_weight_fraction_leaf': 0.02810565657768191}. Best is trial 38 with value: 0.8190450814841892.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:48:32,268] Trial 40 finished with value: 0.8002312369217448 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 128, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.46799886052388073, 'min_weight_fraction_leaf': 0.05363318980657328}. Best is trial 38 with value: 0.8190450814841892.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:48:35,403] Trial 41 finished with value: 0.821618152074522 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 143, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.584717208470466, 'min_weight_fraction_leaf': 0.025025389969347875}. Best is trial 41 with value: 0.821618152074522.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:48:37,473] Trial 42 finished with value: 0.8159404774730197 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 83, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6116228551621374, 'min_weight_fraction_leaf': 0.019576003585959977}. Best is trial 41 with value: 0.821618152074522.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.784037558685446
[I 2024-04-18 03:48:39,562] Trial 43 finished with value: 0.8304703312952922 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6016058414925255, 'min_weight_fraction_leaf': 0.012524279113161611}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8638392857142857
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6502347417840375
[I 2024-04-18 03:48:40,238] Trial 44 finished with value: 0.7652326495072331 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 5, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5423019570629846, 'min_weight_fraction_leaf': 0.015724850985212667}. Best is trial 43 with value: 0.8304703312952922.

Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7347417840375586
[I 2024-04-18 03:48:41,925] Trial 45 finished with value: 0.8075569155359513 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 62, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5994299976670169, 'min_weight_fraction_leaf': 0.003593831218718726}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7535211267605634
[I 2024-04-18 03:48:44,458] Trial 46 finished with value: 0.8079344361936414 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 99, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.43411672050638433, 'min_weight_fraction_leaf': 0.02057326162563852}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8897058823529411
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:48:46,994] Trial 47 finished with value: 0.7853252681321803 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 47, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5527338015346479, 'min_weight_fraction_leaf': 0.056259210983507515}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:48:50,296] Trial 48 finished with value: 0.8218433814716182 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 136, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6502495196108777, 'min_weight_fraction_leaf': 0.0029707544774587834}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:48:51,754] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 38, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5870354043557596, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:48:55,491] Trial 50 finished with value: 0.784375185855311 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 140, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5231344519466996, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:48:58,202] Trial 51 finished with value: 0.8229373218598125 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 83, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6422948049901943, 'min_weight_fraction_leaf': 0.0006404109019635951}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7018779342723005
[I 2024-04-18 03:49:00,687] Trial 52 finished with value: 0.7993556316917275 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 91, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6592613872038365, 'min_weight_fraction_leaf': 0.004496205730554054}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6971830985915493
[I 2024-04-18 03:49:02,657] Trial 53 finished with value: 0.8001899688139895 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 76, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.41859456108995274, 'min_weight_fraction_leaf': 0.059055839298276465}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.715962441314554
[I 2024-04-18 03:49:04,122] Trial 54 finished with value: 0.8032608280268946 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 58, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4843213314880235, 'min_weight_fraction_leaf': 0.024990823415360013}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:49:06,670] Trial 55 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 104, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6202817501359641, 'min_weight_fraction_leaf': 0.31525249693090607}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:49:09,887] Trial 56 finished with value: 0.8194800257580139 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 142, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5749011980179051, 'min_weight_fraction_leaf': 0.005571180329296155}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:49:13,052] Trial 57 finished with value: 0.8271468192375899 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.79756170766832, 'min_weight_fraction_leaf': 0.004939537955850866}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6502347417840375
[I 2024-04-18 03:49:17,235] Trial 58 finished with value: 0.7905068385844751 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 145, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8241293645590788, 'min_weight_fraction_leaf': 0.05947541671177334}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 03:49:19,203] Trial 59 finished with value: 0.7657539119393361 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7795431284383922, 'min_weight_fraction_leaf': 4.136453507535241e-05}. Best is trial 43 with value: 0.8304703312952922.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:49:21,951] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 114, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6679278898397465, 'min_weight_fraction_leaf': 0.3913401900023197}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 03:49:24,986] Trial 61 finished with value: 0.8174968726935499 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5742075757897485, 'min_weight_fraction_leaf': 0.03688799942358214}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:49:28,737] Trial 62 finished with value: 0.8221626913946505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 183, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5130129653991434, 'min_weight_fraction_leaf': 0.00308261355942617}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 03:49:32,030] Trial 63 finished with value: 0.8112397747231601 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 155, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5109877862710762, 'min_weight_fraction_leaf': 0.0002703342731493648}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:49:36,059] Trial 64 finished with value: 0.8048675908879573 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 194, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.555884813421661, 'min_weight_fraction_leaf': 0.04017954668703061}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:49:39,996] Trial 65 finished with value: 0.7815379358440404 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 178, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.41102696379124554, 'min_weight_fraction_leaf': 0.0999149762435798}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:49:42,417] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 99, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 03:49:44,334] Trial 67 finished with value: 0.7980767547703695 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 65, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45573378133306947, 'min_weight_fraction_leaf': 0.06530831090521912}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 03:49:47,199] Trial 68 finished with value: 0.8085744841462411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5246828255200692, 'min_weight_fraction_leaf': 0.02875919753043055}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 03:49:50,637] Trial 69 finished with value: 0.8152567912608891 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 148, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8041316684751971, 'min_weight_fraction_leaf': 0.012382904670817487}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 03:50:02,246] Trial 70 finished with value: 0.7928934260700828 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6463573575633167, 'min_weight_fraction_leaf': 0.047134287230972974}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 03:50:06,790] Trial 71 finished with value: 0.8100508492185996 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4897248144615137, 'min_weight_fraction_leaf': 0.020820278837338096}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:50:11,292] Trial 72 finished with value: 0.8137115348740835 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 183, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5808837647384466, 'min_weight_fraction_leaf': 0.013472083672092718}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6784037558685446
[I 2024-04-18 03:50:15,721] Trial 73 finished with value: 0.7965207689990208 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 161, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5392493325532582, 'min_weight_fraction_leaf': 0.06966271761896553}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7535211267605634
[I 2024-04-18 03:50:19,382] Trial 74 finished with value: 0.812921836792546 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 141, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.75628356511038, 'min_weight_fraction_leaf': 0.04488544089021608}. Best is trial 43 with value: 0.8304703312952922.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 03:50:24,046] Trial 75 finished with value: 0.8087991202250848 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 206, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6692661379783827, 'min_weight_fraction_leaf': 0.03199149098864598}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6549295774647887
[I 2024-04-18 03:50:29,297] Trial 76 finished with value: 0.7706917575536025 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 94, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.692627350198696, 'min_weight_fraction_leaf': 0.20464799434168496}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 03:50:32,178] Trial 77 finished with value: 0.8066679488696888 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 125, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6259740537195462, 'min_weight_fraction_leaf': 0.010906382332953183}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.875
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:50:34,032] Trial 78 finished with value: 0.7947680472941214 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 71, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5980986566216576, 'min_weight_fraction_leaf': 0.098002850977016}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 03:50:36,404] Trial 79 finished with value: 0.7853679701633162 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 107, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5705466847782656, 'min_weight_fraction_leaf': 0.029240794202754238}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 03:50:41,071] Trial 80 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 210, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4924206900094474, 'min_weight_fraction_leaf': 0.2578980132057934}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 03:50:44,016] Trial 81 finished with value: 0.811172477508159 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 129, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5692071826531844, 'min_weight_fraction_leaf': 0.037339993969184734}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:50:47,308] Trial 82 finished with value: 0.8179757420967059 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 141, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6499667059175003, 'min_weight_fraction_leaf': 0.0007899658639793304}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:50:51,104] Trial 83 finished with value: 0.8182450759522272 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 167, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6401963765428813, 'min_weight_fraction_leaf': 0.01503985473573173}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:50:55,493] Trial 84 finished with value: 0.8201892195475251 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 161, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6031488169996558, 'min_weight_fraction_leaf': 0.01568038763370377}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 03:51:05,192] Trial 85 finished with value: 0.8072918796199657 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 499, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5985742735338552, 'min_weight_fraction_leaf': 0.05290341124630053}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 03:51:09,426] Trial 86 finished with value: 0.8109696194155388 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 181, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6820499215231494, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 03:51:17,535] Trial 87 finished with value: 0.80346316061717 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 393, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7323932503199633, 'min_weight_fraction_leaf': 0.06994805526397783}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 03:51:22,367] Trial 88 finished with value: 0.7711053735826816 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 83, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5371551715772509, 'min_weight_fraction_leaf': 0.013780218642592263}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8700980392156863
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:51:25,938] Trial 89 finished with value: 0.7859233760604194 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 153, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6149890855597281, 'min_weight_fraction_leaf': 0.18706131497555706}. Best is trial 43 with value: 0.8304703312952922.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.704225352112676
[I 2024-04-18 03:51:31,392] Trial 90 finished with value: 0.801045790526457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 257, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5068390164935013, 'min_weight_fraction_leaf': 0.0473008466519714}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:51:34,782] Trial 91 finished with value: 0.8176211452019502 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 160, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8625575224781323, 'min_weight_fraction_leaf': 0.013587913470930524}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 03:51:38,371] Trial 92 finished with value: 0.8138935618494468 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 169, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6373000685979969, 'min_weight_fraction_leaf': 0.022804396108616565}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:51:41,342] Trial 93 finished with value: 0.8194525171857429 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5851043588908041, 'min_weight_fraction_leaf': 0.00745476875040829}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 03:51:44,116] Trial 94 finished with value: 0.8236580125737388 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 121, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5535538903579934, 'min_weight_fraction_leaf': 0.002903500519959225}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:51:46,699] Trial 95 finished with value: 0.8238090300870182 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 109, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5647633995880907, 'min_weight_fraction_leaf': 0.0014169779641675685}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.704225352112676
[I 2024-04-18 03:51:48,799] Trial 96 finished with value: 0.8019303676023968 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 88, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5521785261662469, 'min_weight_fraction_leaf': 0.034357936683974306}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 03:51:50,358] Trial 97 finished with value: 0.818445382577738 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 48, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.46867258349776253, 'min_weight_fraction_leaf': 0.002588432956909031}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:51:52,785] Trial 98 finished with value: 0.8170582416746015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 107, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5286644155895797, 'min_weight_fraction_leaf': 0.000694474114639943}. Best is trial 43 with value: 0.8304703312952922.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8396624472573839

[I 2024-04-18 03:51:55,656] A new study created in memory with name: no-name-20f6d039-82a3-4fc4-8789-bbe2d70694f9

Fold 5 C-index: 0.704225352112676
[I 2024-04-18 03:51:55,630] Trial 99 finished with value: 0.8018813923160797 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5573025965933702, 'min_weight_fraction_leaf': 0.028995098661993637}. Best is trial 43 with value: 0.8304703312952922.


* Best trial for C-index:
 FrozenTrial(number=43, state=TrialState.COMPLETE, values=[0.8304703312952922], datetime_start=datetime.datetime(2024, 4, 18, 3, 48, 37, 478936), datetime_complete=datetime.datetime(2024, 4, 18, 3, 48, 39, 561884), params={'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 79, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6016058414925255, 'min_weight_fraction_leaf': 0.012524279113161611}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=43, value=None)


* Best Score for C-index:
 0.8304703312952922

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16918598884148406
Fold 2 IBS: 0.18788248816039377
Fold 3 IBS: 0.1598307922502509
Fold 4 IBS: 0.15844396605448918
Fold 5 IBS: 0.22429759986605563
[I 2024-04-18 03:52:09,340] Trial 0 finished with value: 0.17992816703453468 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-18 03:52:29,385] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.18441019518979865
Fold 2 IBS: 0.19753375242936927
Fold 3 IBS: 0.17673329905633042
Fold 4 IBS: 0.1868703503610961
Fold 5 IBS: 0.217081296074932
[I 2024-04-18 03:52:47,067] Trial 2 finished with value: 0.1925257786223053 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.18709737318418565
Fold 2 IBS: 0.2005447928961497
Fold 3 IBS: 0.1803466717230611
Fold 4 IBS: 0.1923613344336822
Fold 5 IBS: 0.21582174155896613
[I 2024-04-18 03:52:52,949] Trial 3 finished with value: 0.19523438275920896 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-18 03:53:07,750] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-18 03:53:15,313] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.17020455606473264
Fold 2 IBS: 0.18798647027096044
Fold 3 IBS: 0.16152262074375745
Fold 4 IBS: 0.16022337902183154
Fold 5 IBS: 0.2223840397863593
[I 2024-04-18 03:53:29,743] Trial 6 finished with value: 0.18046421317752825 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.17163791978835916
Fold 2 IBS: 0.18779981711231605
Fold 3 IBS: 0.16671229205581845
Fold 4 IBS: 0.16452527383287793
Fold 5 IBS: 0.2207926579736869
[I 2024-04-18 03:53:38,662] Trial 7 finished with value: 0.1822935921526117 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.19105960341132802
Fold 2 IBS: 0.19957646883807545
Fold 3 IBS: 0.18296344892198232
Fold 4 IBS: 0.19786591508445328
Fold 5 IBS: 0.21738535915668378
[I 2024-04-18 03:53:40,792] Trial 8 finished with value: 0.19777015908250456 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.19029519145208112
Fold 2 IBS: 0.20698033422306653
Fold 3 IBS: 0.18448430648349484
Fold 4 IBS: 0.1986866490792407
Fold 5 IBS: 0.2155033538627093
[I 2024-04-18 03:54:01,799] Trial 9 finished with value: 0.19918996702011854 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-18 03:54:15,760] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.1760406766803302
Fold 2 IBS: 0.1924094004949609
Fold 3 IBS: 0.16937513973883292
Fold 4 IBS: 0.17509392850382027
Fold 5 IBS: 0.21985297535104792
[I 2024-04-18 03:54:29,415] Trial 11 finished with value: 0.18655442415379841 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.17992816703453468.
Fold 1 IBS: 0.16569446122876505
Fold 2 IBS: 0.18738719468371112
Fold 3 IBS: 0.15455644745370856
Fold 4 IBS: 0.14778745664456663
Fold 5 IBS: 0.22852484561018765
[I 2024-04-18 03:54:47,511] Trial 12 finished with value: 0.17679008112418781 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17227537697552062
Fold 2 IBS: 0.19488463266219844
Fold 3 IBS: 0.16822801998824163
Fold 4 IBS: 0.17206769514384399
Fold 5 IBS: 0.22082599125144317
[I 2024-04-18 03:55:06,564] Trial 13 finished with value: 0.18565634320424956 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17330006281310753
Fold 2 IBS: 0.19555397627418367
Fold 3 IBS: 0.16939639661857653
Fold 4 IBS: 0.17340647175564658
Fold 5 IBS: 0.22145536135489116
[I 2024-04-18 03:55:19,906] Trial 14 finished with value: 0.1866224537632811 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.17679008112418781.

Fold 1 IBS: 0.1744098177356725
Fold 2 IBS: 0.19364275635843878
Fold 3 IBS: 0.1677711085360639
Fold 4 IBS: 0.17142155730910086
Fold 5 IBS: 0.22108657427269993
[I 2024-04-18 03:55:29,169] Trial 15 finished with value: 0.1856663628423952 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.1981503668898294
Fold 2 IBS: 0.21135022038195758
Fold 3 IBS: 0.19244467326071515
Fold 4 IBS: 0.21191267611580691
Fold 5 IBS: 0.2142159346192936
[I 2024-04-18 03:55:46,576] Trial 16 finished with value: 0.2056147742535205 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17168515396024797
Fold 2 IBS: 0.2230219638476665
Fold 3 IBS: 0.16557586149525366
Fold 4 IBS: 0.1594896117566465
Fold 5 IBS: 0.24008284354224438
[I 2024-04-18 03:55:57,841] Trial 17 finished with value: 0.1919710869204118 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-18 03:56:02,876] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17286991259491397
Fold 2 IBS: 0.19460212684635905
Fold 3 IBS: 0.16813958455560085
Fold 4 IBS: 0.1725792834117131
Fold 5 IBS: 0.2222904027324105
[I 2024-04-18 03:56:17,514] Trial 19 finished with value: 0.1860962620281995 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.20073774402048752
Fold 2 IBS: 0.2111100989990656
Fold 3 IBS: 0.17816491740602142
Fold 4 IBS: 0.2072082669303203
Fold 5 IBS: 0.21929505935765672
[I 2024-04-18 03:56:18,636] Trial 20 finished with value: 0.20330321734271034 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17037423978944718
Fold 2 IBS: 0.18893045571203582
Fold 3 IBS: 0.16146921075947185
Fold 4 IBS: 0.16000831617252195
Fold 5 IBS: 0.22287226553354128
[I 2024-04-18 03:56:34,436] Trial 21 finished with value: 0.1807308975934036 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.1696771811446361
Fold 2 IBS: 0.18787688162633676
Fold 3 IBS: 0.16214496500931705
Fold 4 IBS: 0.16076412455406688
Fold 5 IBS: 0.22256725234448735
[I 2024-04-18 03:56:50,868] Trial 22 finished with value: 0.18060608093576883 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.16842985630865043
Fold 2 IBS: 0.188528888683153
Fold 3 IBS: 0.16016195758031004
Fold 4 IBS: 0.1580492003874325
Fold 5 IBS: 0.22523150612460863
[I 2024-04-18 03:57:06,184] Trial 23 finished with value: 0.18008028181683094 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.16980463951706012
Fold 2 IBS: 0.18873312460555186
Fold 3 IBS: 0.1604610577774981
Fold 4 IBS: 0.15908396257705096
Fold 5 IBS: 0.22527475083605716
[I 2024-04-18 03:57:20,194] Trial 24 finished with value: 0.18067150706264362 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17523730363716913
Fold 2 IBS: 0.19119219735044649
Fold 3 IBS: 0.16954500076726528
Fold 4 IBS: 0.16975425792078358
Fold 5 IBS: 0.21995046768073367
[I 2024-04-18 03:57:30,293] Trial 25 finished with value: 0.18513584547127965 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17131703649401148
Fold 2 IBS: 0.19350337891685335
Fold 3 IBS: 0.16776468402944478
Fold 4 IBS: 0.1714131015457866
Fold 5 IBS: 0.22296077165353662
[I 2024-04-18 03:57:48,697] Trial 26 finished with value: 0.18539179452792656 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8454924050883471, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17283693523726262
Fold 2 IBS: 0.19551801537770386
Fold 3 IBS: 0.16947409384574683
Fold 4 IBS: 0.17478614495263264
Fold 5 IBS: 0.21951160654683138
[I 2024-04-18 03:57:56,267] Trial 27 finished with value: 0.18642535919203546 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17138832509678015
Fold 2 IBS: 0.23083673071257468
Fold 3 IBS: 0.16686972473937522
Fold 4 IBS: 0.16134876796753175
Fold 5 IBS: 0.23725733880152786
[I 2024-04-18 03:58:12,243] Trial 28 finished with value: 0.19354017746355795 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.10561943508937117}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.17522332587608877
Fold 2 IBS: 0.19688264851508755
Fold 3 IBS: 0.17074427609971254
Fold 4 IBS: 0.1824127839503421
Fold 5 IBS: 0.21297905384195961
[I 2024-04-18 03:58:26,088] Trial 29 finished with value: 0.18764841765663812 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.17679008112418781.

Fold 1 IBS: 0.1738388739675036
Fold 2 IBS: 0.1937875067454993
Fold 3 IBS: 0.17016113736228763
Fold 4 IBS: 0.17482337575841608
Fold 5 IBS: 0.21988648152779725
[I 2024-04-18 03:58:41,393] Trial 30 finished with value: 0.18649947507230077 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.16823529544726903
Fold 2 IBS: 0.18935174649578138
Fold 3 IBS: 0.15723319929201915
Fold 4 IBS: 0.15395943956271183
Fold 5 IBS: 0.22622416365588105
[I 2024-04-18 03:58:56,543] Trial 31 finished with value: 0.1790007688907325 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362712139580162, 'min_weight_fraction_leaf': 0.0012002559281581464}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.16894780939535428
Fold 2 IBS: 0.18918481316283356
Fold 3 IBS: 0.156882992020694
Fold 4 IBS: 0.15557020272448238
Fold 5 IBS: 0.2245847000013006
[I 2024-04-18 03:59:11,252] Trial 32 finished with value: 0.17903410346093296 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6227992821807525, 'min_weight_fraction_leaf': 0.07179554342829253}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.18354787739872835
Fold 2 IBS: 0.19675419304801617
Fold 3 IBS: 0.17600135471140363
Fold 4 IBS: 0.18317769538796339
Fold 5 IBS: 0.21738658616667275
[I 2024-04-18 03:59:25,422] Trial 33 finished with value: 0.19137354134255685 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 417, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6246674823350934, 'min_weight_fraction_leaf': 0.04929766610098481}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.1712528874066102
Fold 2 IBS: 0.18973233357707187
Fold 3 IBS: 0.16412753065121136
Fold 4 IBS: 0.1651739940503168
Fold 5 IBS: 0.22101860021560346
[I 2024-04-18 03:59:40,510] Trial 34 finished with value: 0.18226106918016274 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8180483921418293, 'min_weight_fraction_leaf': 0.12662220369343266}. Best is trial 12 with value: 0.17679008112418781.
Fold 1 IBS: 0.165587691268604
Fold 2 IBS: 0.18564686257813395
Fold 3 IBS: 0.15158820218023322
Fold 4 IBS: 0.14902730856767396
Fold 5 IBS: 0.22547149821834786
[I 2024-04-18 03:59:50,463] Trial 35 finished with value: 0.1754643125625986 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 292, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.525544897367368, 'min_weight_fraction_leaf': 0.03874252122688228}. Best is trial 35 with value: 0.1754643125625986.
Fold 1 IBS: 0.16268562577702858
Fold 2 IBS: 0.18587987502414804
Fold 3 IBS: 0.15273248212240872
Fold 4 IBS: 0.14876712376569648
Fold 5 IBS: 0.2250194044327497
[I 2024-04-18 04:00:00,822] Trial 36 finished with value: 0.1750169022244063 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 292, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.39581174032589594, 'min_weight_fraction_leaf': 0.031238193058764258}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.1630219985558621
Fold 2 IBS: 0.18561158285339774
Fold 3 IBS: 0.15268360789576751
Fold 4 IBS: 0.15178997698604496
Fold 5 IBS: 0.22482808546930438
[I 2024-04-18 04:00:08,507] Trial 37 finished with value: 0.17558705035207534 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 216, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3907069630963366, 'min_weight_fraction_leaf': 0.030440421568832744}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.16420578573456218
Fold 2 IBS: 0.1830398487218173
Fold 3 IBS: 0.16035493695201658
Fold 4 IBS: 0.1571733940704436
Fold 5 IBS: 0.22053178971253345
[I 2024-04-18 04:00:15,407] Trial 38 finished with value: 0.1770611510382746 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 199, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40232445463607813, 'min_weight_fraction_leaf': 0.022216332318415407}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.18137282896296122
Fold 2 IBS: 0.1918259525969045
Fold 3 IBS: 0.173181268885679
Fold 4 IBS: 0.17986530515296223
Fold 5 IBS: 0.21774486590364378
[I 2024-04-18 04:00:21,522] Trial 39 finished with value: 0.18879804430043015 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.28424052756646667, 'min_weight_fraction_leaf': 0.03401048379052402}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.17247453140524902
Fold 2 IBS: 0.1957861267813087
Fold 3 IBS: 0.1692586397412332
Fold 4 IBS: 0.17504426017697342
Fold 5 IBS: 0.2203444868566896
[I 2024-04-18 04:00:29,297] Trial 40 finished with value: 0.1865816089922908 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 228, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4201868988545198, 'min_weight_fraction_leaf': 0.11561130788218002}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.1698318934055905
Fold 2 IBS: 0.1897706754030277
Fold 3 IBS: 0.16607206764301313
Fold 4 IBS: 0.16785034843764804
Fold 5 IBS: 0.2217576490188733
[I 2024-04-18 04:00:35,230] Trial 41 finished with value: 0.18305652678163054 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 176, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.38238592390037096, 'min_weight_fraction_leaf': 0.05785299024344398}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.1722661537896605
Fold 2 IBS: 0.18944193753060473
Fold 3 IBS: 0.1679424328048274
Fold 4 IBS: 0.17279849774615133
Fold 5 IBS: 0.21732816636178853
[I 2024-04-18 04:00:43,315] Trial 42 finished with value: 0.1839554376466065 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 242, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.49736600647348106, 'min_weight_fraction_leaf': 0.02693484924204851}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.1709160265753365
Fold 2 IBS: 0.18396096130363762
Fold 3 IBS: 0.16314564370090187
Fold 4 IBS: 0.16351764730048224
Fold 5 IBS: 0.22009498281842152
[I 2024-04-18 04:00:52,584] Trial 43 finished with value: 0.18032705233975596 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 283, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.19479216130414256, 'min_weight_fraction_leaf': 0.02619033998019891}. Best is trial 36 with value: 0.1750169022244063.
Fold 1 IBS: 0.18833558186883168
Fold 2 IBS: 0.2015540425316065
Fold 3 IBS: 0.18086917372001235
Fold 4 IBS: 0.19250937174536772
Fold 5 IBS: 0.2179769195816427
[I 2024-04-18 04:00:59,663] Trial 44 finished with value: 0.19624901788949217 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 181, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.33846670341980367, 'min_weight_fraction_leaf': 0.06344865736374401}. Best is trial 36 with value: 0.1750169022244063.

Fold 1 IBS: 0.16171040091818872
Fold 2 IBS: 0.1779507308726674
Fold 3 IBS: 0.1493687731616471
Fold 4 IBS: 0.14594036648959846
Fold 5 IBS: 0.2240383700080252
[I 2024-04-18 04:01:04,773] Trial 45 finished with value: 0.17180172829002538 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 139, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5296598554254506, 'min_weight_fraction_leaf': 0.022410036988178828}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1700981308082937
Fold 2 IBS: 0.18865396833856346
Fold 3 IBS: 0.16455531273130072
Fold 4 IBS: 0.1659095570486116
Fold 5 IBS: 0.22131350481069362
[I 2024-04-18 04:01:08,961] Trial 46 finished with value: 0.18210609474749262 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 117, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5368271784486555, 'min_weight_fraction_leaf': 0.08918003228725331}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.17615408399468008
Fold 2 IBS: 0.19878825047895954
Fold 3 IBS: 0.17290464239325043
Fold 4 IBS: 0.18315809177235928
Fold 5 IBS: 0.21634489798474935
[I 2024-04-18 04:01:12,404] Trial 47 finished with value: 0.18946999332479975 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 93, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4385991761959246, 'min_weight_fraction_leaf': 0.15203659778952378}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.2140052302581741
Fold 2 IBS: 0.22141338407928593
Fold 3 IBS: 0.2048967522536628
Fold 4 IBS: 0.22482420413649695
Fold 5 IBS: 0.21849485548070363
[I 2024-04-18 04:01:24,124] Trial 48 finished with value: 0.2167268852416647 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.550325602710743, 'min_weight_fraction_leaf': 0.4232459400228781}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.186878883095045
Fold 2 IBS: 0.19712227779861613
Fold 3 IBS: 0.17939989268419435
Fold 4 IBS: 0.18984413431352437
Fold 5 IBS: 0.21476399960272854
[I 2024-04-18 04:01:27,126] Trial 49 finished with value: 0.19360183749882165 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 76, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33602406206607516, 'min_weight_fraction_leaf': 0.047548352706612465}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.21398529530209198
Fold 2 IBS: 0.2216115856391737
Fold 3 IBS: 0.20492778049073762
Fold 4 IBS: 0.22489238121174818
Fold 5 IBS: 0.21830433242162908
[I 2024-04-18 04:01:33,115] Trial 50 finished with value: 0.21674427501307608 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 151, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5184867426047409, 'min_weight_fraction_leaf': 0.3163091534745454}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.169144264978356
Fold 2 IBS: 0.18864681027496963
Fold 3 IBS: 0.16973086385812264
Fold 4 IBS: 0.17215805647088403
Fold 5 IBS: 0.2146934683244035
[I 2024-04-18 04:01:40,002] Trial 51 finished with value: 0.18287469278134716 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 208, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4011447164270757, 'min_weight_fraction_leaf': 0.0007364537868510303}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1649737650294961
Fold 2 IBS: 0.1842466581569849
Fold 3 IBS: 0.15967293974997865
Fold 4 IBS: 0.15813841510808466
Fold 5 IBS: 0.22132113455256214
[I 2024-04-18 04:01:46,010] Trial 52 finished with value: 0.17767058251942128 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 180, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.45046128931810375, 'min_weight_fraction_leaf': 0.023834498380572697}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1652627135745755
Fold 2 IBS: 0.18604149306418818
Fold 3 IBS: 0.1532054794017368
Fold 4 IBS: 0.14745186936596127
Fold 5 IBS: 0.2221394452351352
[I 2024-04-18 04:01:55,971] Trial 53 finished with value: 0.1748202001283194 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 310, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5836460098544125, 'min_weight_fraction_leaf': 0.019864003481657694}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1703615814366805
Fold 2 IBS: 0.19072959952195043
Fold 3 IBS: 0.16338588569621537
Fold 4 IBS: 0.16597771927945887
Fold 5 IBS: 0.22119400309659062
[I 2024-04-18 04:02:05,153] Trial 54 finished with value: 0.18232975780617916 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 312, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.46814324952995756, 'min_weight_fraction_leaf': 0.07797907736473855}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.17065205969985422
Fold 2 IBS: 0.18884553919451003
Fold 3 IBS: 0.16505226793166589
Fold 4 IBS: 0.16607981697584215
Fold 5 IBS: 0.22190384201096555
[I 2024-04-18 04:02:15,056] Trial 55 finished with value: 0.1825067051625676 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 326, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.26876574494145145, 'min_weight_fraction_leaf': 0.04477533944452787}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.175841335449117
Fold 2 IBS: 0.19039766617545165
Fold 3 IBS: 0.16707473343241364
Fold 4 IBS: 0.16821257391750294
Fold 5 IBS: 0.21842343935614295
[I 2024-04-18 04:02:22,723] Trial 56 finished with value: 0.18398994966612564 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 239, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5781048408879157, 'min_weight_fraction_leaf': 0.01901277520900361}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.17038008200030905
Fold 2 IBS: 0.2085321219793057
Fold 3 IBS: 0.15377283612251935
Fold 4 IBS: 0.15332328915629118
Fold 5 IBS: 0.23992458536091338
[I 2024-04-18 04:02:30,898] Trial 57 finished with value: 0.18518658292386775 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 269, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6859431566383477, 'min_weight_fraction_leaf': 0.06242331345538628}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.20194444838324613
Fold 2 IBS: 0.21198943027658212
Fold 3 IBS: 0.19237556763015373
Fold 4 IBS: 0.20624473587554865
Fold 5 IBS: 0.21481506239788234
[I 2024-04-18 04:02:33,109] Trial 58 finished with value: 0.2054738489126826 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 46, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.36579387896516147, 'min_weight_fraction_leaf': 0.09072208637799424}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16571713381833755
Fold 2 IBS: 0.18460102462772066
Fold 3 IBS: 0.1562592270705456
Fold 4 IBS: 0.15386362891869143
Fold 5 IBS: 0.22373319586047602
[I 2024-04-18 04:02:42,177] Trial 59 finished with value: 0.17683484205915426 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 301, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.24884303031169952, 'min_weight_fraction_leaf': 6.235606634781218e-05}. Best is trial 45 with value: 0.17180172829002538.

Fold 1 IBS: 0.21398909457010623
Fold 2 IBS: 0.2207070361479251
Fold 3 IBS: 0.20528417601196522
Fold 4 IBS: 0.22484479482398192
Fold 5 IBS: 0.21754868037310363
[I 2024-04-18 04:02:51,810] Trial 60 finished with value: 0.21647475638541644 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 344, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.16250765016205834, 'min_weight_fraction_leaf': 0.1227005732829336}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1642444466187744
Fold 2 IBS: 0.18371870561213746
Fold 3 IBS: 0.15486687513782893
Fold 4 IBS: 0.15128927567511535
Fold 5 IBS: 0.22489309120820142
[I 2024-04-18 04:03:01,753] Trial 61 finished with value: 0.1758024788504115 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 305, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2873000864550046, 'min_weight_fraction_leaf': 0.014314329081957459}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16587658988765933
Fold 2 IBS: 0.18393643577962762
Fold 3 IBS: 0.15940715290645768
Fold 4 IBS: 0.15699582616342853
Fold 5 IBS: 0.22249075683964958
[I 2024-04-18 04:03:09,536] Trial 62 finished with value: 0.17774135231536456 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 262, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.20574846931010704, 'min_weight_fraction_leaf': 0.013098776194031162}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16886917177103072
Fold 2 IBS: 0.18597504998338893
Fold 3 IBS: 0.16082376894075381
Fold 4 IBS: 0.15802633879034556
Fold 5 IBS: 0.22572815514456623
[I 2024-04-18 04:03:20,135] Trial 63 finished with value: 0.17988449692601705 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 336, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2898197014459506, 'min_weight_fraction_leaf': 0.03375738913769649}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.170898485518771
Fold 2 IBS: 0.18737042384245353
Fold 3 IBS: 0.1659569848707606
Fold 4 IBS: 0.16837692713655675
Fold 5 IBS: 0.22188903043867916
[I 2024-04-18 04:03:29,519] Trial 64 finished with value: 0.18289837036144418 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 313, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.30418802458930233, 'min_weight_fraction_leaf': 0.05354803200490721}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16847630125709834
Fold 2 IBS: 0.190201100715351
Fold 3 IBS: 0.15582847105282802
Fold 4 IBS: 0.1546444681899774
Fold 5 IBS: 0.22399002984198785
[I 2024-04-18 04:03:37,231] Trial 65 finished with value: 0.17862807421144855 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 224, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6000795783191708, 'min_weight_fraction_leaf': 0.03716317541265715}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.21397656857303046
Fold 2 IBS: 0.2211488404119977
Fold 3 IBS: 0.20504806285378432
Fold 4 IBS: 0.22478703689697782
Fold 5 IBS: 0.21825032816454937
[I 2024-04-18 04:03:48,689] Trial 66 finished with value: 0.21664216738006795 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 364, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.35254237756803697, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.17334369805867195
Fold 2 IBS: 0.1954460795429889
Fold 3 IBS: 0.16908127656675426
Fold 4 IBS: 0.17351486940462335
Fold 5 IBS: 0.22110842626733612
[I 2024-04-18 04:03:58,839] Trial 67 finished with value: 0.1864988699680749 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 296, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.43798216039712035, 'min_weight_fraction_leaf': 0.0750609747343094}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16945236723081292
Fold 2 IBS: 0.18594136338550507
Fold 3 IBS: 0.16553067097873253
Fold 4 IBS: 0.1651054249886244
Fold 5 IBS: 0.2212889762929029
[I 2024-04-18 04:04:08,337] Trial 68 finished with value: 0.18146376057531555 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 275, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3189718110286007, 'min_weight_fraction_leaf': 0.01585730682009008}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.17553457804762407
Fold 2 IBS: 0.19888143670084
Fold 3 IBS: 0.1429009132211786
Fold 4 IBS: 0.14020203140810866
Fold 5 IBS: 0.24087337430139746
[I 2024-04-18 04:04:19,067] Trial 69 finished with value: 0.17967846673582974 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 254, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9493649915013874, 'min_weight_fraction_leaf': 0.10221438004802702}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.20035652986094807
Fold 2 IBS: 0.21133288630565272
Fold 3 IBS: 0.1919567962918352
Fold 4 IBS: 0.21370084403011208
Fold 5 IBS: 0.2159680866332911
[I 2024-04-18 04:04:23,510] Trial 70 finished with value: 0.20666302862436786 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 124, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5253452037595682, 'min_weight_fraction_leaf': 0.22236521646156077}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1712019819463723
Fold 2 IBS: 0.18625613755179538
Fold 3 IBS: 0.1621519508297846
Fold 4 IBS: 0.1652484112885757
Fold 5 IBS: 0.22014787285944276
[I 2024-04-18 04:04:33,392] Trial 71 finished with value: 0.18100127089519416 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 301, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.15502392958885614, 'min_weight_fraction_leaf': 0.005598609093548764}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16252103804987666
Fold 2 IBS: 0.18657811293256138
Fold 3 IBS: 0.15120681159422888
Fold 4 IBS: 0.14026531769894984
Fold 5 IBS: 0.22332583976982506
[I 2024-04-18 04:04:43,437] Trial 72 finished with value: 0.17277942400908836 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 302, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.22925822557955383, 'min_weight_fraction_leaf': 0.0009052543547795056}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16859870665364393
Fold 2 IBS: 0.18379137514600516
Fold 3 IBS: 0.1629438143640951
Fold 4 IBS: 0.16384032165613877
Fold 5 IBS: 0.22199649465246668
[I 2024-04-18 04:04:55,917] Trial 73 finished with value: 0.18023414249446992 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 382, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2130920999825938, 'min_weight_fraction_leaf': 0.03318285295334779}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16262739178491478
Fold 2 IBS: 0.18221207315721374
Fold 3 IBS: 0.15267738808747128
Fold 4 IBS: 0.14757127469382128
Fold 5 IBS: 0.22360348653951664
[I 2024-04-18 04:05:06,314] Trial 74 finished with value: 0.17373832285258756 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 330, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.263382986904778, 'min_weight_fraction_leaf': 0.01502177582878543}. Best is trial 45 with value: 0.17180172829002538.

Fold 1 IBS: 0.16041964816322132
Fold 2 IBS: 0.18472776804985028
Fold 3 IBS: 0.15455347708913214
Fold 4 IBS: 0.1521283030894658
Fold 5 IBS: 0.22321385657424175
[I 2024-04-18 04:05:16,537] Trial 75 finished with value: 0.17500861059318226 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 326, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2316710953741802, 'min_weight_fraction_leaf': 0.014344014173231634}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.19571061751658791
Fold 2 IBS: 0.20845642677508575
Fold 3 IBS: 0.18827483427372838
Fold 4 IBS: 0.20583148739593302
Fold 5 IBS: 0.21471598101862793
[I 2024-04-18 04:05:26,779] Trial 76 finished with value: 0.20259786939599259 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 331, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.13665036121683571, 'min_weight_fraction_leaf': 0.051118239523347694}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.21398616649550461
Fold 2 IBS: 0.22062810747649717
Fold 3 IBS: 0.20503942629148733
Fold 4 IBS: 0.22466609245799327
Fold 5 IBS: 0.21787466788596205
[I 2024-04-18 04:05:37,036] Trial 77 finished with value: 0.2164388921214889 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 345, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2390733286198803, 'min_weight_fraction_leaf': 0.2838903270801565}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16797678404509347
Fold 2 IBS: 0.188073342721582
Fold 3 IBS: 0.15559011556313956
Fold 4 IBS: 0.15018285980702462
Fold 5 IBS: 0.2254664871770527
[I 2024-04-18 04:05:47,012] Trial 78 finished with value: 0.17745791786277848 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 322, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.667680853486823, 'min_weight_fraction_leaf': 0.062396983012128274}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1759395732561108
Fold 2 IBS: 0.19353789052609507
Fold 3 IBS: 0.17149348391011518
Fold 4 IBS: 0.17446752893402648
Fold 5 IBS: 0.21993953726239684
[I 2024-04-18 04:05:56,134] Trial 79 finished with value: 0.18707560277774887 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 288, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.18168402393028585, 'min_weight_fraction_leaf': 0.04169893123596291}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16523906206421965
Fold 2 IBS: 0.18219398010086174
Fold 3 IBS: 0.15603075062237165
Fold 4 IBS: 0.15377395067910737
Fold 5 IBS: 0.22451894842810843
[I 2024-04-18 04:06:08,172] Trial 80 finished with value: 0.17635133837893377 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 354, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.24991069492632645, 'min_weight_fraction_leaf': 0.02502911966074306}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16629676993141707
Fold 2 IBS: 0.18369986221209855
Fold 3 IBS: 0.15795489794154963
Fold 4 IBS: 0.1571101541021674
Fold 5 IBS: 0.22353907114164653
[I 2024-04-18 04:06:18,658] Trial 81 finished with value: 0.17772015106577582 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 310, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2259146903612274, 'min_weight_fraction_leaf': 0.01179737274978947}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16167503255542073
Fold 2 IBS: 0.1824314452830435
Fold 3 IBS: 0.15186318835327808
Fold 4 IBS: 0.14812098823611297
Fold 5 IBS: 0.22501214658074073
[I 2024-04-18 04:06:30,417] Trial 82 finished with value: 0.1738205602017192 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 373, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2673967617414203, 'min_weight_fraction_leaf': 0.01520328547656152}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16798316607213185
Fold 2 IBS: 0.1840608086610555
Fold 3 IBS: 0.15928241389564435
Fold 4 IBS: 0.15793640822640706
Fold 5 IBS: 0.22457761861720998
[I 2024-04-18 04:06:41,711] Trial 83 finished with value: 0.17876808309448977 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 369, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2626130243333929, 'min_weight_fraction_leaf': 0.03421641931602017}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16290514193645603
Fold 2 IBS: 0.1829633409759052
Fold 3 IBS: 0.15226548133767137
Fold 4 IBS: 0.14715005806948653
Fold 5 IBS: 0.22256988111014078
[I 2024-04-18 04:06:54,889] Trial 84 finished with value: 0.17357078068593196 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 389, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5550252214877613, 'min_weight_fraction_leaf': 0.018609696088874795}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16930022051770302
Fold 2 IBS: 0.18979482593708022
Fold 3 IBS: 0.16088254297799598
Fold 4 IBS: 0.1588154104263178
Fold 5 IBS: 0.22288113384185793
[I 2024-04-18 04:07:07,254] Trial 85 finished with value: 0.18033482674019097 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 390, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6020872268155516, 'min_weight_fraction_leaf': 0.06958644909818024}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.2139866833498882
Fold 2 IBS: 0.22131443245705226
Fold 3 IBS: 0.2048723595043007
Fold 4 IBS: 0.22467347394267492
Fold 5 IBS: 0.2184739178570213
[I 2024-04-18 04:07:20,154] Trial 86 finished with value: 0.21666417342218747 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 398, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.553766340064649, 'min_weight_fraction_leaf': 0.381622326839403}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16208876621554213
Fold 2 IBS: 0.18401628010437332
Fold 3 IBS: 0.15305928760339121
Fold 4 IBS: 0.14794509586012183
Fold 5 IBS: 0.22319303206834926
[I 2024-04-18 04:07:33,462] Trial 87 finished with value: 0.17406049237035556 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 344, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4758939390467283, 'min_weight_fraction_leaf': 0.013964860212081287}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1622574649658
Fold 2 IBS: 0.18412745778385622
Fold 3 IBS: 0.1526664156399693
Fold 4 IBS: 0.14739966494062787
Fold 5 IBS: 0.22286671808521755
[I 2024-04-18 04:07:47,825] Trial 88 finished with value: 0.1738635442830942 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 338, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.49439439113248385, 'min_weight_fraction_leaf': 0.013378092740282701}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.165611743691081
Fold 2 IBS: 0.1850996032537852
Fold 3 IBS: 0.15460056090994853
Fold 4 IBS: 0.15138995899245494
Fold 5 IBS: 0.22390453822611944
[I 2024-04-18 04:08:02,010] Trial 89 finished with value: 0.17612128101467783 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4810127750587175, 'min_weight_fraction_leaf': 0.008604991434222813}. Best is trial 45 with value: 0.17180172829002538.

Fold 1 IBS: 0.17277862124715318
Fold 2 IBS: 0.19027413414581626
Fold 3 IBS: 0.16904162603184877
Fold 4 IBS: 0.1735710939445359
Fold 5 IBS: 0.21703125661873038
[I 2024-04-18 04:08:16,750] Trial 90 finished with value: 0.18453934639761688 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 372, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4950957244555919, 'min_weight_fraction_leaf': 0.02038605216364302}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16656609819937618
Fold 2 IBS: 0.18778421598577213
Fold 3 IBS: 0.15585313805423273
Fold 4 IBS: 0.15189212933628532
Fold 5 IBS: 0.2232984092102556
[I 2024-04-18 04:08:30,282] Trial 91 finished with value: 0.17707879815718439 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5754410685633853, 'min_weight_fraction_leaf': 0.05109998725505631}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16134125467204627
Fold 2 IBS: 0.18302509930568434
Fold 3 IBS: 0.15282969880971647
Fold 4 IBS: 0.14736263453362197
Fold 5 IBS: 0.22126717019272427
[I 2024-04-18 04:08:42,812] Trial 92 finished with value: 0.17316517150275867 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 324, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.46562056597133483, 'min_weight_fraction_leaf': 0.010115094323930637}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16363577313575642
Fold 2 IBS: 0.18570814709417435
Fold 3 IBS: 0.1529174839110677
Fold 4 IBS: 0.14835576936293998
Fold 5 IBS: 0.22372223350540793
[I 2024-04-18 04:08:56,379] Trial 93 finished with value: 0.1748678814018693 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 327, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5144396867571481, 'min_weight_fraction_leaf': 0.0092003956970385}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16491121086032365
Fold 2 IBS: 0.18600801347681756
Fold 3 IBS: 0.15936746523796272
Fold 4 IBS: 0.15773097363379437
Fold 5 IBS: 0.22181904075888373
[I 2024-04-18 04:09:14,360] Trial 94 finished with value: 0.17796734079355642 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4636886208566103, 'min_weight_fraction_leaf': 0.002581230254652847}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.16681165425606412
Fold 2 IBS: 0.1838383722643589
Fold 3 IBS: 0.15862479893106993
Fold 4 IBS: 0.15699598812547524
Fold 5 IBS: 0.22062895790248788
[I 2024-04-18 04:09:30,304] Trial 95 finished with value: 0.1773799542958912 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 374, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.519444661184095, 'min_weight_fraction_leaf': 0.02216450876418415}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.17072757832677282
Fold 2 IBS: 0.1979815554599436
Fold 3 IBS: 0.16818996016824192
Fold 4 IBS: 0.16986425854146275
Fold 5 IBS: 0.22077054826445947
[I 2024-04-18 04:09:44,941] Trial 96 finished with value: 0.18550678015217614 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 356, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5387334633122143, 'min_weight_fraction_leaf': 0.04171491022671421}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.184956559996335
Fold 2 IBS: 0.1965270671810551
Fold 3 IBS: 0.1766446631539478
Fold 4 IBS: 0.1854118208314401
Fold 5 IBS: 0.21648619628829788
[I 2024-04-18 04:09:58,857] Trial 97 finished with value: 0.19200526149021518 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5633437809306986, 'min_weight_fraction_leaf': 0.08449260192147198}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1682888331204751
Fold 2 IBS: 0.1894078701160002
Fold 3 IBS: 0.15500376603060476
Fold 4 IBS: 0.15022151759261013
Fold 5 IBS: 0.2256909849470176
[I 2024-04-18 04:10:12,065] Trial 98 finished with value: 0.17772259436134155 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5951208765981927, 'min_weight_fraction_leaf': 0.0008042045457470857}. Best is trial 45 with value: 0.17180172829002538.
Fold 1 IBS: 0.1686689642115878
Fold 2 IBS: 0.18457939731786832
Fold 3 IBS: 0.16276988053167035
Fold 4 IBS: 0.15982470920711642
Fold 5 IBS: 0.22025649511403947
[I 2024-04-18 04:10:27,562] Trial 99 finished with value: 0.1792198892764565 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 387, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5053820702587086, 'min_weight_fraction_leaf': 0.025705484175497288}. Best is trial 45 with value: 0.17180172829002538.


* Best trial for IBS:
 FrozenTrial(number=45, state=TrialState.COMPLETE, values=[0.17180172829002538], datetime_start=datetime.datetime(2024, 4, 18, 4, 0, 59, 670202), datetime_complete=datetime.datetime(2024, 4, 18, 4, 1, 4, 772492), params={'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 139, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5296598554254506, 'min_weight_fraction_leaf': 0.022410036988178828}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=45, value=None)


* Best Score for IBS:
 0.17180172829002538

In [63]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [64]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.83
train_ibs:  0.172

#### Test

In [65]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [66]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=4, max_features=None, max_leaf_nodes=13,
                   max_samples=0.6016058414925255, min_samples_leaf=2,
                   min_samples_split=9,
                   min_weight_fraction_leaf=0.012524279113161611,
                   n_estimators=79, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.629

ExtraSurvivalTrees(max_depth=18, max_leaf_nodes=5,
                   max_samples=0.5296598554254506, min_samples_leaf=2,
                   min_samples_split=8,
                   min_weight_fraction_leaf=0.022410036988178828,
                   n_estimators=139, random_state=123)

IBS: 0.213

In [67]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [68]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 04:10:28,933] A new study created in memory with name: no-name-d3036d4f-db00-4649-96ee-3df31035c35f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:11:34,777] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:12:09,881] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:12:46,055] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:13:43,036] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:14:06,065] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:14:11,870] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:15:09,757] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:15:25,810] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:15:27,531] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7433035714285714
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6830985915492958
[I 2024-04-18 04:17:56,169] Trial 9 finished with value: 0.75875287105312 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 04:21:43,827] Trial 10 finished with value: 0.6989250862300543 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:25:56,343] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 04:29:26,390] Trial 12 finished with value: 0.7461534891108423 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:31:10,696] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:33:29,698] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:35:39,357] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:37:06,075] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:40:10,270] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:44:20,369] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:44:30,813] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:46:04,274] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 04:49:18,713] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 04:52:23,218] Trial 22 finished with value: 0.7412410929055004 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:54:49,978] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:57:02,567] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 04:58:23,063] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 05:01:18,783] Trial 26 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:04:11,636] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:06:39,960] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:08:23,146] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:10:23,381] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 05:14:15,822] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:17:58,892] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:20:27,500] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:23:53,635] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:24:32,432] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:27:46,434] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:27:51,348] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.75875287105312.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:28:57,347] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:30:43,012] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:33:35,570] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-18 05:33:36,126] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6502347417840375
[I 2024-04-18 05:33:55,091] Trial 42 finished with value: 0.7338182267185549 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:34:15,916] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:35:05,749] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:35:27,733] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:35:45,727] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:37:05,813] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:37:39,287] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:39:07,279] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:39:13,592] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 05:39:14,502] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:39:15,746] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 05:39:31,337] Trial 53 finished with value: 0.7493195034055049 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:39:44,500] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:39:47,465] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:43:35,551] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:43:49,766] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:44:18,011] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:47:35,135] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:48:41,524] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:48:47,233] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753

Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 05:49:18,564] Trial 62 finished with value: 0.6997689680865944 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:49:56,553] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.13592280861310782, 'n_estimators': 192, 'criterion': 'squared_error', 'ccp_alpha': 0.733686110808502, 'min_weight_fraction_leaf': 0.25062495105887606, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.9944542811487016, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:50:27,800] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9187783486953396, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 178, 'criterion': 'squared_error', 'ccp_alpha': 0.36688086798361713, 'min_weight_fraction_leaf': 0.35183901814733526, 'max_features': 'auto', 'min_impurity_decrease': 3.299702263155327e-07, 'validation_fraction': 0.9264223190540628, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 05:50:43,927] Trial 65 finished with value: 0.7018786727279446 and parameters: {'subsample': 0.9664785962080902, 'learning_rate': 0.011722172098720455, 'dropout_rate': 0.1011352011272833, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.002720474374027445, 'min_weight_fraction_leaf': 0.3770484241588561, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8800483891911463, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:51:34,764] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.885696821597521, 'learning_rate': 0.016950546740898867, 'dropout_rate': 0.10421110317491636, 'n_estimators': 225, 'criterion': 'squared_error', 'ccp_alpha': 0.8254786252963416, 'min_weight_fraction_leaf': 0.45906723804378347, 'max_features': 'auto', 'min_impurity_decrease': 0.0001571311880544454, 'validation_fraction': 0.8763260736370284, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.75875287105312.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 05:51:48,539] Trial 67 finished with value: 0.7686457973114529 and parameters: {'subsample': 0.9449634937948884, 'learning_rate': 0.022450060078644873, 'dropout_rate': 0.4308859881762669, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.04366182843696066, 'min_weight_fraction_leaf': 0.4203837252588317, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002929228884372661, 'validation_fraction': 0.6847776431749146, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 67 with value: 0.7686457973114529.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:52:02,563] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8508914266547543, 'learning_rate': 0.0271877376773079, 'dropout_rate': 0.4587925300849697, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4064170808897855, 'min_weight_fraction_leaf': 0.42082481983216546, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003862592715164256, 'validation_fraction': 0.6927602784856939, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 67 with value: 0.7686457973114529.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:52:12,528] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.8117437406527579, 'learning_rate': 0.021732361644044403, 'dropout_rate': 0.32707285953985127, 'n_estimators': 101, 'criterion': 'squared_error', 'ccp_alpha': 2.165381857742337, 'min_weight_fraction_leaf': 0.4008202205161851, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003807366321009408, 'validation_fraction': 0.4814297515359772, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 67 with value: 0.7686457973114529.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:52:23,522] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.9588179877977443, 'learning_rate': 0.03404571509920987, 'dropout_rate': 0.5164505989784269, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 1.1547936717217182, 'min_weight_fraction_leaf': 0.23609717988742163, 'max_features': 'sqrt', 'min_impurity_decrease': 9.903776966049311e-05, 'validation_fraction': 0.6007139278650676, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 67 with value: 0.7686457973114529.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6596244131455399
[I 2024-04-18 05:52:32,094] Trial 71 finished with value: 0.7667781421147205 and parameters: {'subsample': 0.9998058628904551, 'learning_rate': 0.012217196514323809, 'dropout_rate': 0.272889788803047, 'n_estimators': 90, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.37665810495618246, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0007202807121114636, 'validation_fraction': 0.7901595950688891, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 67 with value: 0.7686457973114529.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:52:39,240] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.9044139888705314, 'learning_rate': 0.012179198274788102, 'dropout_rate': 0.4337945478119803, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 0.2919408922724437, 'min_weight_fraction_leaf': 0.3583073377101208, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000654957772418829, 'validation_fraction': 0.6255625028149949, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 67 with value: 0.7686457973114529.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:52:56,285] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9648647232705697, 'learning_rate': 0.018544888734491664, 'dropout_rate': 0.3840392496719551, 'n_estimators': 145, 'criterion': 'squared_error', 'ccp_alpha': 0.7317858789979383, 'min_weight_fraction_leaf': 0.33547968716778687, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012138641204268545, 'validation_fraction': 0.7472232153782647, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 67 with value: 0.7686457973114529.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:53:03,341] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.9372578852362602, 'learning_rate': 0.013894133166299519, 'dropout_rate': 0.27304995305013646, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2685355623284117, 'min_weight_fraction_leaf': 0.4794532356771624, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0015770193056312545, 'validation_fraction': 0.6862699083190502, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 67 with value: 0.7686457973114529.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8799019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6643192488262911
[I 2024-04-18 05:53:05,750] Trial 75 finished with value: 0.7905059083148 and parameters: {'subsample': 0.6001028949487068, 'learning_rate': 0.023239756862861477, 'dropout_rate': 0.6757649295445344, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.008819927083844869, 'min_weight_fraction_leaf': 0.1942611713172168, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0021237516252394237, 'validation_fraction': 0.7847712019774569, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:53:07,559] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5878712745727869, 'learning_rate': 0.022147062407290335, 'dropout_rate': 0.6243222457264906, 'n_estimators': 41, 'criterion': 'squared_error', 'ccp_alpha': 0.6031429897420305, 'min_weight_fraction_leaf': 0.2068351704428001, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0035277422265958588, 'validation_fraction': 0.7993048924737626, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:53:10,055] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5357913465602108, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.758978120963316, 'n_estimators': 59, 'criterion': 'squared_error', 'ccp_alpha': 0.9646030158291333, 'min_weight_fraction_leaf': 0.18921739871886467, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002999937798485588, 'validation_fraction': 0.7387915108714895, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:53:12,185] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.6708593402641205, 'learning_rate': 0.04479053769496956, 'dropout_rate': 0.638335760687531, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 1.406985156632589, 'min_weight_fraction_leaf': 0.22324854378798265, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01123762072699069, 'validation_fraction': 0.6870714509747361, 'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:53:14,470] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.48483411726905057, 'learning_rate': 0.024257161323518392, 'dropout_rate': 0.8479916513561038, 'n_estimators': 59, 'criterion': 'friedman_mse', 'ccp_alpha': 1.812067956922833, 'min_weight_fraction_leaf': 0.16909333970802584, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7749694068106482, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 9}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:53:21,181] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6431481526757131, 'learning_rate': 0.009039793267160097, 'dropout_rate': 0.684566586558272, 'n_estimators': 112, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.18502266407543982, 'max_features': None, 'min_impurity_decrease': 0.0020012217758738067, 'validation_fraction': 0.8312616498046783, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6690140845070423
[I 2024-04-18 05:53:35,717] Trial 81 finished with value: 0.760471079143014 and parameters: {'subsample': 0.9039357395720827, 'learning_rate': 0.016412003133033586, 'dropout_rate': 0.235339636468323, 'n_estimators': 122, 'criterion': 'squared_error', 'ccp_alpha': 0.02521776434594261, 'min_weight_fraction_leaf': 0.43294529918678526, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005704051848755918, 'validation_fraction': 0.8571795971165943, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:53:51,406] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.6137454684751019, 'learning_rate': 0.015676364815988084, 'dropout_rate': 0.5603615855034783, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.2451713250089625, 'min_weight_fraction_leaf': 0.1521377130243636, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005515193402134184, 'validation_fraction': 0.8566748455657475, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:54:00,804] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9027681881288449, 'learning_rate': 0.01822534426227402, 'dropout_rate': 0.23612530486703057, 'n_estimators': 89, 'criterion': 'squared_error', 'ccp_alpha': 0.6434011455925561, 'min_weight_fraction_leaf': 0.4535984691770081, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012304179362636906, 'validation_fraction': 0.7995996886618921, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:55:38,121] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.19323478605220312, 'learning_rate': 0.027444520178208, 'dropout_rate': 0.6818395627907664, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.4701678092057134, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012453998142192364, 'validation_fraction': 0.7122301629842086, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6549295774647887
[I 2024-04-18 05:55:39,915] Trial 85 finished with value: 0.770888786883171 and parameters: {'subsample': 0.7371540479848577, 'learning_rate': 0.03342214021657085, 'dropout_rate': 0.2995405522798756, 'n_estimators': 29, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.4252299956617621, 'max_features': 1, 'min_impurity_decrease': 0.0002644011718832551, 'validation_fraction': 0.5539761240279264, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:55:42,393] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5884601342315053, 'learning_rate': 0.040138798831481366, 'dropout_rate': 0.30893486797722186, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 0.47555134849711456, 'min_weight_fraction_leaf': 0.4364165414676263, 'max_features': 1, 'min_impurity_decrease': 7.875370120501562e-05, 'validation_fraction': 0.5578771254458135, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:55:44,066] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7385740014789494, 'learning_rate': 0.0312585002522818, 'dropout_rate': 0.34702434797629267, 'n_estimators': 28, 'criterion': 'squared_error', 'ccp_alpha': 0.2573732802753831, 'min_weight_fraction_leaf': 0.42552427194253917, 'max_features': 1, 'min_impurity_decrease': 0.00046483208476230805, 'validation_fraction': 0.5194095572435395, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:55:48,371] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.8144964035305952, 'learning_rate': 0.01892201466815226, 'dropout_rate': 0.26657671560049273, 'n_estimators': 60, 'criterion': 'squared_error', 'ccp_alpha': 1.1132554775232983, 'min_weight_fraction_leaf': 0.40413170006799326, 'max_features': 1, 'min_impurity_decrease': 0.0002424717222698867, 'validation_fraction': 0.5645759290645115, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:58:24,215] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.6891977708878514, 'learning_rate': 0.0224547626143628, 'dropout_rate': 0.2836120574219838, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.6289674109876843, 'min_weight_fraction_leaf': 0.27088299579805813, 'max_features': 1, 'min_impurity_decrease': 0.000303780768720358, 'validation_fraction': 0.6355737074700468, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:58:30,579] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.8640340113061721, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.32536772451946044, 'n_estimators': 76, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8512083959536265, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 0.1, 'min_impurity_decrease': 0.0007297148480119136, 'validation_fraction': 0.6732774756210603, 'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 05:58:49,723] Trial 91 finished with value: 0.7485765469415696 and parameters: {'subsample': 0.940543807018674, 'learning_rate': 0.009567024476933025, 'dropout_rate': 0.22710075500504756, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.03760721937190585, 'min_weight_fraction_leaf': 0.4178541230198032, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009910717111428719, 'validation_fraction': 0.9197960790172954, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:59:02,119] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.924651475781888, 'learning_rate': 0.010356392157077806, 'dropout_rate': 0.2232733649777798, 'n_estimators': 104, 'criterion': 'squared_error', 'ccp_alpha': 0.20594179048085923, 'min_weight_fraction_leaf': 0.43386698908744314, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002573681751392315, 'validation_fraction': 0.9680316212431762, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:59:09,947] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.7678131035383085, 'learning_rate': 0.007776290790885781, 'dropout_rate': 0.30303355573944185, 'n_estimators': 86, 'criterion': 'squared_error', 'ccp_alpha': 0.4610108941546788, 'min_weight_fraction_leaf': 0.41645906098318164, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012431389762873359, 'validation_fraction': 0.9065369938983409, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:59:11,758] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.5171830029999889, 'learning_rate': 0.0040166651424204955, 'dropout_rate': 0.3807313546610083, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.17457432007548962, 'min_weight_fraction_leaf': 0.48614852982593815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000244482530540027, 'validation_fraction': 0.9292904570302956, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:02:43,390] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8773563262480757, 'learning_rate': 0.02532898715676993, 'dropout_rate': 0.2528468518834252, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.5672123325935469, 'min_weight_fraction_leaf': 0.4613801112278463, 'max_features': 'sqrt', 'min_impurity_decrease': 0.004351478423019476, 'validation_fraction': 0.45070104952373863, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6572769953051644
[I 2024-04-18 06:05:56,349] Trial 96 finished with value: 0.7574905887410476 and parameters: {'subsample': 0.8405253503495475, 'learning_rate': 0.016377171831941345, 'dropout_rate': 0.20374332906527465, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.031157726907107337, 'min_weight_fraction_leaf': 0.4485286950695694, 'max_features': 'log2', 'min_impurity_decrease': 0.0008739967635656416, 'validation_fraction': 0.7602436149101085, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 16}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:06:03,432] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.836158306860711, 'learning_rate': 0.01621127932999071, 'dropout_rate': 0.8479620532477699, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.4456457753678166, 'max_features': 'log2', 'min_impurity_decrease': 0.0009336689160945996, 'validation_fraction': 0.7598751254996176, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 12}. Best is trial 75 with value: 0.7905059083148.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:06:04,197] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.7344061665966882, 'learning_rate': 0.020410071578111352, 'dropout_rate': 0.2839093344920812, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.3996467995504147, 'max_features': 'log2', 'min_impurity_decrease': 0.00047224200123682086, 'validation_fraction': 0.827056945015729, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 18}. Best is trial 75 with value: 0.7905059083148.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.7932489451476793

[I 2024-04-18 06:07:44,374] A new study created in memory with name: no-name-424e8ba8-0773-4920-94e8-f7780fe3f0e6

Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 06:07:44,354] Trial 99 finished with value: 0.7705194696802853 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.35892734289616185, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 0.004507602823243077, 'min_weight_fraction_leaf': 0.21338193670151887, 'max_features': 'log2', 'min_impurity_decrease': 0.0018373817798183923, 'validation_fraction': 0.7282328797470141, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 75 with value: 0.7905059083148.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.7905059083148], datetime_start=datetime.datetime(2024, 4, 18, 5, 53, 3, 347229), datetime_complete=datetime.datetime(2024, 4, 18, 5, 53, 5, 748609), params={'subsample': 0.6001028949487068, 'learning_rate': 0.023239756862861477, 'dropout_rate': 0.6757649295445344, 'n_estimators': 53, 'criterion': 'squared_error', 'ccp_alpha': 0.008819927083844869, 'min_weight_fraction_leaf': 0.1942611713172168, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0021237516252394237, 'validation_fraction': 0.7847712019774569, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for C-index:
 0.7905059083148

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:08:48,901] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:09:22,624] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:09:55,367] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:10:46,967] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:11:08,814] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:11:14,281] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:12:06,407] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:12:21,858] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:12:23,695] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21268052044682917
Fold 2 IBS: 0.22067373662659223
Fold 3 IBS: 0.20350542889008158
Fold 4 IBS: 0.2231764930709189
Fold 5 IBS: 0.2176406915459263
[I 2024-04-18 06:14:45,473] Trial 9 finished with value: 0.21553537411606963 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443048985744143
Fold 5 IBS: 0.21803455300047256
[I 2024-04-18 06:18:25,425] Trial 10 finished with value: 0.21634130830268453 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 06:22:22,466] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21383641111136248
Fold 2 IBS: 0.22149689711703552
Fold 3 IBS: 0.20443482423916606
Fold 4 IBS: 0.22455454418948897
Fold 5 IBS: 0.21808680588487855
[I 2024-04-18 06:25:49,026] Trial 12 finished with value: 0.21648189650838628 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 06:27:34,888] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:30:29,768] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:32:59,459] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:34:22,854] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:37:39,050] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:39:24,849] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:39:42,028] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:42:46,904] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21373110319832214
Fold 2 IBS: 0.22152908047801065
Fold 3 IBS: 0.2044398850544662
Fold 4 IBS: 0.22470638007273172
Fold 5 IBS: 0.21807877811120815
[I 2024-04-18 06:46:13,121] Trial 21 finished with value: 0.21649704538294778 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21553537411606963.
Fold 1 IBS: 0.21260280417137592
Fold 2 IBS: 0.22077508526060716

Fold 3 IBS: 0.20352317540286535
Fold 4 IBS: 0.22294843126640776
Fold 5 IBS: 0.21766902548369965
[I 2024-04-18 06:49:54,890] Trial 22 finished with value: 0.21550370431699117 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 06:52:57,172] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:54:53,972] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:56:44,475] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 06:59:30,133] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 06:59:47,414] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:00:48,237] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:03:16,386] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 07:04:13,282] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.2135093106849736
Fold 2 IBS: 0.22139977250283238
Fold 3 IBS: 0.20422680488437314
Fold 4 IBS: 0.2244144325480169
Fold 5 IBS: 0.21802056137064452
[I 2024-04-18 07:07:07,182] Trial 31 finished with value: 0.2163141763981681 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21283443105017621
Fold 2 IBS: 0.22123509240257067
Fold 3 IBS: 0.203701511518681
Fold 4 IBS: 0.22313315677292173
Fold 5 IBS: 0.2178119202332009
[I 2024-04-18 07:09:59,002] Trial 32 finished with value: 0.2157432223955101 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:11:58,055] Trial 33 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9175730211318314, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.23558036461669868, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 2.2672612842512112e-05, 'validation_fraction': 0.8391863465064515, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 07:14:02,999] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6818728654527908, 'learning_rate': 0.014570474664799389, 'dropout_rate': 0.39687420252491534, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9857366581537508, 'min_weight_fraction_leaf': 0.2451263696303153, 'max_features': 'sqrt', 'min_impurity_decrease': 7.173213136739857e-06, 'validation_fraction': 0.9231140468377321, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:14:40,260] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7474352307553052, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.29459319086620417, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 7.199479090473024e-07, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:17:16,982] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.3498267997183648, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.2894426185614589, 'max_features': 'auto', 'min_impurity_decrease': 6.773052750173388e-05, 'validation_fraction': 0.7819324141806283, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:17:21,767] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.23919145342953393, 'max_features': None, 'min_impurity_decrease': 2.5414170052989375e-06, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 07:18:50,673] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8670579303141319, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.1728262906688144, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42202283765123816, 'min_weight_fraction_leaf': 0.35239546646921105, 'max_features': 'auto', 'min_impurity_decrease': 0.00017081434930634308, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:20:12,618] Trial 39 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8154589849054708, 'learning_rate': 0.006878494063124208, 'dropout_rate': 0.5323261217237781, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 1.1477698683125066, 'min_weight_fraction_leaf': 0.11023361948341703, 'max_features': 1, 'min_impurity_decrease': 1.7677159455067355e-06, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 07:22:29,661] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.22290618957651392, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.5274073849776741, 'min_weight_fraction_leaf': 0.2739610635014299, 'max_features': 'auto', 'min_impurity_decrease': 2.272398816394983e-07, 'validation_fraction': 0.8717079478922802, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 22 with value: 0.21550370431699117.
Fold 1 IBS: 0.21124266704296785
Fold 2 IBS: 0.22026553296373474
Fold 3 IBS: 0.2024366872388908
Fold 4 IBS: 0.22127520965371827
Fold 5 IBS: 0.2171200751081455
[I 2024-04-18 07:25:38,850] Trial 41 finished with value: 0.21446803440149145 and parameters: {'subsample': 0.993176118879571, 'learning_rate': 0.01271988915310228, 'dropout_rate': 0.152367046323752, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.19182471840022747, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21446803440149145.
Fold 1 IBS: 0.21101685954645263
Fold 2 IBS: 0.2182555945271751
Fold 3 IBS: 0.20160348611112858
Fold 4 IBS: 0.21967164489036323
Fold 5 IBS: 0.2161244488766688
[I 2024-04-18 07:29:10,375] Trial 42 finished with value: 0.21333440679035767 and parameters: {'subsample': 0.9646924257252548, 'learning_rate': 0.012507391626216524, 'dropout_rate': 0.10802959125648778, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327408119788757, 'min_weight_fraction_leaf': 0.13510597987400375, 'max_features': 'auto', 'min_impurity_decrease': 1.0593992090305253e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 07:33:00,440] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828284890903175, 'learning_rate': 0.011543268886217308, 'dropout_rate': 0.11584589616484722, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.09682559138790292, 'max_features': 'auto', 'min_impurity_decrease': 1.0125868029922384e-07, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-18 07:35:58,509] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992870370700113, 'learning_rate': 0.022847552015173876, 'dropout_rate': 0.1556807870961761, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.1403134453903068, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21266963391512192
Fold 2 IBS: 0.220226363872871
Fold 3 IBS: 0.20319998528341784
Fold 4 IBS: 0.22260228978618746
Fold 5 IBS: 0.21744807253949516
[I 2024-04-18 07:37:12,247] Trial 45 finished with value: 0.2152292690794187 and parameters: {'subsample': 0.8888212863898438, 'learning_rate': 0.01524983211078064, 'dropout_rate': 0.20487736976615575, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.027893207681183953, 'min_weight_fraction_leaf': 0.06753391487815072, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.9448766575733668, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 07:37:50,011] Trial 46 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.016684121596597847, 'dropout_rate': 0.10891325683572217, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.04784747079432074, 'max_features': 0.1, 'min_impurity_decrease': 2.0166271580558924e-07, 'validation_fraction': 0.24435732275143762, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 07:38:40,797] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7729061863940228, 'learning_rate': 0.02995584278149796, 'dropout_rate': 0.19790330487666663, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.05716507411653311, 'max_features': 0.1, 'min_impurity_decrease': 1.0699422270078741e-07, 'validation_fraction': 0.9565097869700105, 'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 07:40:00,528] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8446010144291817, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.14247687075474555, 'n_estimators': 294, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 0.1, 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.8246274171002186, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 07:40:55,041] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6917414996198523, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.2874751071933402, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.08230947204902768, 'max_features': 0.1, 'min_impurity_decrease': 1.8211699167585496e-07, 'validation_fraction': 0.6513576271964052, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 07:41:44,306] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.019482931131151772, 'dropout_rate': 0.6676032114338903, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.013701950422388753, 'max_features': 'log2', 'min_impurity_decrease': 7.041814507237016e-07, 'validation_fraction': 0.7324600365192867, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21265180077205456
Fold 2 IBS: 0.22009020934447315
Fold 3 IBS: 0.20323045281592161
Fold 4 IBS: 0.22276475895041742
Fold 5 IBS: 0.21753185070458886
[I 2024-04-18 07:44:59,250] Trial 51 finished with value: 0.2152538145174911 and parameters: {'subsample': 0.9574902141624301, 'learning_rate': 0.013974517784402708, 'dropout_rate': 0.19663405810878032, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288632756573364, 'min_weight_fraction_leaf': 0.1845530130003769, 'max_features': 'sqrt', 'min_impurity_decrease': 5.505988736711189e-07, 'validation_fraction': 0.8981152080635156, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 07:48:20,629] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8963301244448798, 'learning_rate': 0.014496942793188729, 'dropout_rate': 0.149261379708028, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.3267109398107992, 'min_weight_fraction_leaf': 0.19350109364955276, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0314361105633666e-07, 'validation_fraction': 0.8673271583656655, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 07:50:44,879] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.937858776808653, 'learning_rate': 0.01317678110087918, 'dropout_rate': 0.20949679348390188, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.9371275797883157, 'min_weight_fraction_leaf': 0.16718449303286065, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0035393968280476e-07, 'validation_fraction': 0.9639725916044029, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 07:51:04,932] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5502453589475278, 'learning_rate': 0.005289059095661144, 'dropout_rate': 0.16758744743711101, 'n_estimators': 147, 'criterion': 'squared_error', 'ccp_alpha': 0.6055238018097719, 'min_weight_fraction_leaf': 0.1222904374725215, 'max_features': 'sqrt', 'min_impurity_decrease': 8.119424084486158e-07, 'validation_fraction': 0.8019436577478607, 'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21149115656929574
Fold 2 IBS: 0.22061155778446703

Fold 3 IBS: 0.20287635124596737
Fold 4 IBS: 0.22157930195318806
Fold 5 IBS: 0.21757113828505154
[I 2024-04-18 07:53:44,855] Trial 55 finished with value: 0.21482590116759398 and parameters: {'subsample': 0.9703353679292269, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.2676210325613897, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.036860238643527846, 'min_weight_fraction_leaf': 0.21798842867076448, 'max_features': None, 'min_impurity_decrease': 4.086647023052284e-07, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:55:48,588] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9556274374724505, 'learning_rate': 0.022777236721630217, 'dropout_rate': 0.36674252455714285, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.3101553395317078, 'min_weight_fraction_leaf': 0.21445816437013876, 'max_features': None, 'min_impurity_decrease': 4.99089267664694e-07, 'validation_fraction': 0.8444326224317742, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.2111687028051771
Fold 2 IBS: 0.2192670012219273
Fold 3 IBS: 0.20113060921449374
Fold 4 IBS: 0.21823429253204232
Fold 5 IBS: 0.21737983024811217
[I 2024-04-18 07:55:51,215] Trial 57 finished with value: 0.21343608720435053 and parameters: {'subsample': 0.9885544496318819, 'learning_rate': 0.02570846317737359, 'dropout_rate': 0.11524078732039367, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.0019474604343284706, 'min_weight_fraction_leaf': 0.1539893411018015, 'max_features': None, 'min_impurity_decrease': 3.011740016899961e-07, 'validation_fraction': 0.8976605224112223, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:55:52,209] Trial 58 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9760257284010853, 'learning_rate': 0.044170756425452734, 'dropout_rate': 0.10695167335108825, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 0.7470878188226159, 'min_weight_fraction_leaf': 0.1623750980802567, 'max_features': None, 'min_impurity_decrease': 3.402621023187449e-07, 'validation_fraction': 0.8839190525574698, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 07:56:00,522] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8651178500686678, 'learning_rate': 0.031729459746086146, 'dropout_rate': 0.1294932593082019, 'n_estimators': 91, 'criterion': 'squared_error', 'ccp_alpha': 2.4509996240950476, 'min_weight_fraction_leaf': 0.14999314729494934, 'max_features': None, 'min_impurity_decrease': 1.564084650521852e-07, 'validation_fraction': 0.996741201133535, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 07:56:19,391] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9167528164906635, 'learning_rate': 0.024844206422551217, 'dropout_rate': 0.10027142034172723, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 1.5027931264041994, 'min_weight_fraction_leaf': 0.1840765520407988, 'max_features': None, 'min_impurity_decrease': 0.026115039984674165, 'validation_fraction': 0.9013568181484788, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21273370328437058
Fold 2 IBS: 0.2209400117762394
Fold 3 IBS: 0.20291275785992635
Fold 4 IBS: 0.2221801252368877
Fold 5 IBS: 0.21772394248518598
[I 2024-04-18 07:59:17,220] Trial 61 finished with value: 0.215298108128522 and parameters: {'subsample': 0.9931174804814122, 'learning_rate': 0.016529825628647618, 'dropout_rate': 0.1935981459085364, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.0813695010094894, 'min_weight_fraction_leaf': 0.12194954374946233, 'max_features': None, 'min_impurity_decrease': 1.1729202879091808e-06, 'validation_fraction': 0.9481060427790172, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:01:38,909] Trial 62 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9972168379620757, 'learning_rate': 0.028217399882747345, 'dropout_rate': 0.1806381271548384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.3084041748420949, 'min_weight_fraction_leaf': 0.12013391362008917, 'max_features': None, 'min_impurity_decrease': 1.1386618305709938e-06, 'validation_fraction': 0.9457754330032251, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21199538046555141
Fold 2 IBS: 0.2194242104741012
Fold 3 IBS: 0.20224071177058792
Fold 4 IBS: 0.22058703644615904
Fold 5 IBS: 0.2169447689273305
[I 2024-04-18 08:01:40,622] Trial 63 finished with value: 0.21423842161674603 and parameters: {'subsample': 0.9627141857439078, 'learning_rate': 0.019891228353589942, 'dropout_rate': 0.2615796624395084, 'n_estimators': 49, 'criterion': 'squared_error', 'ccp_alpha': 0.01736018686586977, 'min_weight_fraction_leaf': 0.04375001956932725, 'max_features': None, 'min_impurity_decrease': 2.9650355903328224e-07, 'validation_fraction': 0.9569907594316491, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:01:41,802] Trial 64 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9587518146305004, 'learning_rate': 0.019802180649912862, 'dropout_rate': 0.2603466948459836, 'n_estimators': 40, 'criterion': 'squared_error', 'ccp_alpha': 1.002024697263514, 'min_weight_fraction_leaf': 0.044285609862845736, 'max_features': None, 'min_impurity_decrease': 2.720232704210543e-07, 'validation_fraction': 0.9023407544716895, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 08:01:43,513] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8951181311729837, 'learning_rate': 0.037231214360123326, 'dropout_rate': 0.32454189899564956, 'n_estimators': 48, 'criterion': 'squared_error', 'ccp_alpha': 0.4113923217247418, 'min_weight_fraction_leaf': 0.00011246718145094259, 'max_features': None, 'min_impurity_decrease': 1.381949767966752e-07, 'validation_fraction': 0.8558515608716643, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-18 08:01:44,053] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9342515202646464, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.2288776012135632, 'n_estimators': 7, 'criterion': 'squared_error', 'ccp_alpha': 0.7042671412306138, 'min_weight_fraction_leaf': 0.0708576995244338, 'max_features': None, 'min_impurity_decrease': 5.049204052683285e-07, 'validation_fraction': 0.779814650235569, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 08:01:49,990] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9699873838014033, 'learning_rate': 0.012103946738880062, 'dropout_rate': 0.14222380728521514, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.030567908908384282, 'max_features': 'sqrt', 'min_impurity_decrease': 1.094611645458025e-07, 'validation_fraction': 0.8187342892372662, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 08:01:50,969] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8066950165330748, 'learning_rate': 0.023377362681528607, 'dropout_rate': 0.15894248115081894, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 1.0894868734364265, 'min_weight_fraction_leaf': 0.09777832680789011, 'max_features': 1, 'min_impurity_decrease': 3.2013908424881626e-07, 'validation_fraction': 0.9728405359487509, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:01:52,937] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8529548190627155, 'learning_rate': 0.0012168162419408535, 'dropout_rate': 0.42050912513013483, 'n_estimators': 61, 'criterion': 'squared_error', 'ccp_alpha': 0.7384649181664461, 'min_weight_fraction_leaf': 0.2085136183735176, 'max_features': None, 'min_impurity_decrease': 1.7154437160377624e-07, 'validation_fraction': 0.9083572843679635, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21217762853314587
Fold 2 IBS: 0.21967121269008016
Fold 3 IBS: 0.2026770528762532
Fold 4 IBS: 0.22188113949959457
Fold 5 IBS: 0.2173287577125384
[I 2024-04-18 08:01:56,839] Trial 70 finished with value: 0.21474715826232244 and parameters: {'subsample': 0.9256610134215202, 'learning_rate': 0.027187396607684697, 'dropout_rate': 0.2698281084334899, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01011709803992732, 'min_weight_fraction_leaf': 0.15633989047262453, 'max_features': 0.1, 'min_impurity_decrease': 6.342045680536371e-07, 'validation_fraction': 0.9963961862738748, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21242098945195984
Fold 2 IBS: 0.22004328146692484
Fold 3 IBS: 0.2029298193227108
Fold 4 IBS: 0.22231927580784877
Fold 5 IBS: 0.2174180375190823
[I 2024-04-18 08:01:59,811] Trial 71 finished with value: 0.21502628071370533 and parameters: {'subsample': 0.9191145215668692, 'learning_rate': 0.028803620179149808, 'dropout_rate': 0.308958719403514, 'n_estimators': 77, 'criterion': 'friedman_mse', 'ccp_alpha': 0.026599566986409653, 'min_weight_fraction_leaf': 0.15399848016813225, 'max_features': 0.1, 'min_impurity_decrease': 5.855723294143886e-07, 'validation_fraction': 0.9916810781214654, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.2112125802220465
Fold 2 IBS: 0.21858054849645234
Fold 3 IBS: 0.20158955103503978
Fold 4 IBS: 0.22033916691027644
Fold 5 IBS: 0.2169681884998046
[I 2024-04-18 08:02:03,599] Trial 72 finished with value: 0.21373800703272394 and parameters: {'subsample': 0.9163996694308585, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.2700967141743007, 'n_estimators': 87, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791400710493756, 'min_weight_fraction_leaf': 0.155227755776175, 'max_features': 0.1, 'min_impurity_decrease': 2.7153758955492077e-07, 'validation_fraction': 0.9936760144532607, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:02:06,991] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9288897705401948, 'learning_rate': 0.03411408397308106, 'dropout_rate': 0.2722486347578293, 'n_estimators': 77, 'criterion': 'friedman_mse', 'ccp_alpha': 0.35137250856599767, 'min_weight_fraction_leaf': 0.1495872461746581, 'max_features': 0.1, 'min_impurity_decrease': 7.270118939912425e-07, 'validation_fraction': 0.9925633875202848, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 08:02:13,774] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9126870857191455, 'learning_rate': 0.04271327854752515, 'dropout_rate': 0.3083593342668366, 'n_estimators': 120, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6348591831690735, 'min_weight_fraction_leaf': 0.15810053074507613, 'max_features': 0.1, 'min_impurity_decrease': 3.626343412672233e-07, 'validation_fraction': 0.979557353406547, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-18 08:02:15,912] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8293713781851788, 'learning_rate': 0.02908256354003201, 'dropout_rate': 0.37158886582886624, 'n_estimators': 64, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3272014920640867, 'min_weight_fraction_leaf': 0.20024829748849934, 'max_features': 0.1, 'min_impurity_decrease': 1.290830214046723e-06, 'validation_fraction': 0.964167888344054, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 6}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 08:02:19,395] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9737708379828696, 'learning_rate': 0.040314448903926776, 'dropout_rate': 0.3433203488764059, 'n_estimators': 89, 'criterion': 'friedman_mse', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.17163640619790976, 'max_features': 0.1, 'min_impurity_decrease': 3.1330804284170225e-06, 'validation_fraction': 0.9291290438093902, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:02:20,352] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8782627345221757, 'learning_rate': 0.05513764082997855, 'dropout_rate': 0.3076595483575353, 'n_estimators': 30, 'criterion': 'friedman_mse', 'ccp_alpha': 5.8752783688356525, 'min_weight_fraction_leaf': 0.1353755115318474, 'max_features': 0.1, 'min_impurity_decrease': 4.688347284022185e-06, 'validation_fraction': 0.995904541155469, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 08:02:22,759] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9362147727385395, 'learning_rate': 0.02736082926046323, 'dropout_rate': 0.26541734467806316, 'n_estimators': 77, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2910342652485194, 'min_weight_fraction_leaf': 0.22600697495173297, 'max_features': 'log2', 'min_impurity_decrease': 2.73345967920419e-07, 'validation_fraction': 0.9235701874070005, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 08:02:29,382] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9100835469049136, 'learning_rate': 0.036156542494890344, 'dropout_rate': 0.23372149213636637, 'n_estimators': 115, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8315019131728741, 'min_weight_fraction_leaf': 0.09644449915291103, 'max_features': 0.1, 'min_impurity_decrease': 1.678382435082819e-06, 'validation_fraction': 0.5192981078121236, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 08:02:31,035] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9699827601278878, 'learning_rate': 0.04790733894070888, 'dropout_rate': 0.49040987944703684, 'n_estimators': 50, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.18340034254353382, 'max_features': None, 'min_impurity_decrease': 0.000321859747788374, 'validation_fraction': 0.9690149558573901, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21248026239091455
Fold 2 IBS: 0.22006614875350688
Fold 3 IBS: 0.20328941459668323
Fold 4 IBS: 0.2226329241471308
Fold 5 IBS: 0.2175209508018884
[I 2024-04-18 08:02:44,080] Trial 81 finished with value: 0.21519794013802476 and parameters: {'subsample': 0.8927745843584889, 'learning_rate': 0.020283778850589053, 'dropout_rate': 0.21396485912215418, 'n_estimators': 171, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038423779386081554, 'min_weight_fraction_leaf': 0.1296287192043128, 'max_features': 0.1, 'min_impurity_decrease': 1.6509092118135291e-07, 'validation_fraction': 0.9511936913819414, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 08:02:55,903] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992895000371431, 'learning_rate': 0.03131648789474262, 'dropout_rate': 0.2787973145632071, 'n_estimators': 170, 'criterion': 'friedman_mse', 'ccp_alpha': 0.24497157691877675, 'min_weight_fraction_leaf': 0.10781763151993767, 'max_features': 0.1, 'min_impurity_decrease': 1.4088820839585875e-07, 'validation_fraction': 0.881236309062741, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:02:59,042] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9416208266682318, 'learning_rate': 0.02046176101071548, 'dropout_rate': 0.22968230522988387, 'n_estimators': 78, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6304609381011949, 'min_weight_fraction_leaf': 0.12701458223262946, 'max_features': 0.1, 'min_impurity_decrease': 2.467230236178666e-07, 'validation_fraction': 0.9556913884882147, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:03:04,482] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8827806521124008, 'learning_rate': 0.025580788654234535, 'dropout_rate': 0.1317416331806406, 'n_estimators': 104, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20867829471494329, 'min_weight_fraction_leaf': 0.19792214821940654, 'max_features': 0.1, 'min_impurity_decrease': 4.5154989125437026e-07, 'validation_fraction': 0.9228706249202399, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21157463482205044
Fold 2 IBS: 0.21898567682324332
Fold 3 IBS: 0.2022521539732213
Fold 4 IBS: 0.2210172208265184
Fold 5 IBS: 0.2169811173125744
[I 2024-04-18 08:03:12,683] Trial 85 finished with value: 0.21416216075152156 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.02419472142884856, 'dropout_rate': 0.17335098613381442, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.011135359211459884, 'min_weight_fraction_leaf': 0.1527623055490464, 'max_features': 0.1, 'min_impurity_decrease': 9.018508338129106e-07, 'validation_fraction': 0.9998929617405277, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 16}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:03:14,405] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8536382100022728, 'learning_rate': 0.02439010922408882, 'dropout_rate': 0.5994503938995064, 'n_estimators': 57, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9972188157319429, 'min_weight_fraction_leaf': 0.15620210526908096, 'max_features': 1, 'min_impurity_decrease': 8.539058389634627e-07, 'validation_fraction': 0.8449130230293593, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 17}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:03:14,784] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9558532541539936, 'learning_rate': 0.03243361261628032, 'dropout_rate': 0.17266786976924853, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 0.43268662254187046, 'min_weight_fraction_leaf': 0.17652784181036787, 'max_features': 0.1, 'min_impurity_decrease': 6.799272531707803e-07, 'validation_fraction': 0.9991134226558199, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 17}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:03:15,362] Trial 88 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9215996575589526, 'learning_rate': 0.01829740803300135, 'dropout_rate': 0.2562255112313207, 'n_estimators': 15, 'criterion': 'friedman_mse', 'ccp_alpha': 0.57329106413285, 'min_weight_fraction_leaf': 0.21750351834816006, 'max_features': None, 'min_impurity_decrease': 1.0592768076345631e-07, 'validation_fraction': 0.9722178875553694, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:03:24,338] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828049683854578, 'learning_rate': 0.0401442321523931, 'dropout_rate': 0.12508897364625737, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1917037663435968, 'min_weight_fraction_leaf': 0.1418992381857624, 'max_features': 'log2', 'min_impurity_decrease': 4.784822523408194e-07, 'validation_fraction': 0.9230642450597242, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-18 08:03:25,429] Trial 90 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7850349664677921, 'learning_rate': 0.027950629726663057, 'dropout_rate': 0.31820750523530705, 'n_estimators': 31, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9091571660170535, 'min_weight_fraction_leaf': 0.19397767470644814, 'max_features': 0.1, 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.892274892205536, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 19}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21263570740885449
Fold 2 IBS: 0.22023114446221936
Fold 3 IBS: 0.20331768430181946
Fold 4 IBS: 0.22265569341480396
Fold 5 IBS: 0.2175156908432328
[I 2024-04-18 08:03:37,084] Trial 91 finished with value: 0.215271184086186 and parameters: {'subsample': 0.823319209692186, 'learning_rate': 0.02064538678416143, 'dropout_rate': 0.22018504687862775, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03758513454012713, 'min_weight_fraction_leaf': 0.15948846308650855, 'max_features': 0.1, 'min_impurity_decrease': 2.3953669414570884e-07, 'validation_fraction': 0.9480189777814622, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 14}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:03:49,662] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.899044085441203, 'learning_rate': 0.010070688898499163, 'dropout_rate': 0.16259306451315403, 'n_estimators': 172, 'criterion': 'friedman_mse', 'ccp_alpha': 0.19747742321360495, 'min_weight_fraction_leaf': 0.12840328466578887, 'max_features': 0.1, 'min_impurity_decrease': 1.5940199995745892e-07, 'validation_fraction': 0.9698012905243838, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21300559933850885
Fold 2 IBS: 0.22045848715217442
Fold 3 IBS: 0.20360548830835337
Fold 4 IBS: 0.22332792870600493
Fold 5 IBS: 0.21752036396925298
[I 2024-04-18 08:04:16,904] Trial 93 finished with value: 0.21558357349485888 and parameters: {'subsample': 0.9501627220500388, 'learning_rate': 0.01645417172713602, 'dropout_rate': 0.1914387139946294, 'n_estimators': 244, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046899368200999374, 'min_weight_fraction_leaf': 0.08761112540033375, 'max_features': 0.1, 'min_impurity_decrease': 3.568315338115539e-07, 'validation_fraction': 0.9373056502737855, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 08:04:38,300] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8659550324353585, 'learning_rate': 0.02254693274371298, 'dropout_rate': 0.25076937975436003, 'n_estimators': 226, 'criterion': 'friedman_mse', 'ccp_alpha': 0.43911386534828034, 'min_weight_fraction_leaf': 0.17346024854408915, 'max_features': 0.1, 'min_impurity_decrease': 2.1796808466181916e-07, 'validation_fraction': 0.98189469988689, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-18 08:04:42,466] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9134308609631109, 'learning_rate': 0.026294968825765572, 'dropout_rate': 0.2817749152567438, 'n_estimators': 85, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5595491942059729, 'min_weight_fraction_leaf': 0.13389522874548684, 'max_features': 'auto', 'min_impurity_decrease': 9.902197570678398e-07, 'validation_fraction': 0.8687504499179839, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 08:04:47,352] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.48032209804466314, 'learning_rate': 0.01868218284689483, 'dropout_rate': 0.20585440991282042, 'n_estimators': 100, 'criterion': 'friedman_mse', 'ccp_alpha': 1.604197609470562, 'min_weight_fraction_leaf': 0.11184810291785854, 'max_features': None, 'min_impurity_decrease': 1.291160244288722e-07, 'validation_fraction': 0.9053925528013446, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 08:04:50,753] Trial 97 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9798655897126933, 'learning_rate': 0.030999428328934167, 'dropout_rate': 0.1448908205449383, 'n_estimators': 70, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2272247781104705, 'min_weight_fraction_leaf': 0.14559658852579252, 'max_features': 0.1, 'min_impurity_decrease': 3.0732872579929027e-07, 'validation_fraction': 0.9980654848531771, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 08:04:59,832] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9452537879486875, 'learning_rate': 0.034342050082719074, 'dropout_rate': 0.1800622166118938, 'n_estimators': 127, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7916130678928162, 'min_weight_fraction_leaf': 0.2595277411602728, 'max_features': 'auto', 'min_impurity_decrease': 5.855964803954401e-07, 'validation_fraction': 0.9505863900239235, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 42 with value: 0.21333440679035767.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 08:06:18,077] Trial 99 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.24286963781937687, 'learning_rate': 0.06087517452189459, 'dropout_rate': 0.29326439595252435, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 0.024886107812659396, 'min_weight_fraction_leaf': 0.22244511091184427, 'max_features': None, 'min_impurity_decrease': 1.9888370412270107e-06, 'validation_fraction': 0.8600288241788306, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 42 with value: 0.21333440679035767.


* Best trial for IBS:
 FrozenTrial(number=42, state=TrialState.COMPLETE, values=[0.21333440679035767], datetime_start=datetime.datetime(2024, 4, 18, 7, 25, 38, 861122), datetime_complete=datetime.datetime(2024, 4, 18, 7, 29, 10, 375027), params={'subsample': 0.9646924257252548, 'learning_rate': 0.012507391626216524, 'dropout_rate': 0.10802959125648778, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327408119788757, 'min_weight_fraction_leaf': 0.13510597987400375, 'max_features': 'auto', 'min_impurity_decrease': 1.0593992090305253e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=42, value=None)


* Best Score for IBS:
 0.21333440679035767

In [69]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [70]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.791
train_ibs:  0.213

#### Test

In [71]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [72]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008819927083844869,
                                 criterion='squared_error',
                                 dropout_rate=0.6757649295445344,
                                 learning_rate=0.023239756862861477,
                                 max_depth=1, max_features='sqrt',
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=0.0021237516252394237,
                                 min_samples_leaf=18, min_samples_split=17,
                                 min_weight_fraction_leaf=0.1942611713172168,
                                 n_estimators=53, random_state=123,
                                 subsample=0.6001028949487068,
                                 validation_fraction=0.7847712019774569)

C-index score: 0.647

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008327408119788757,
                                 criterion='squared_error',
                                 dropout_rate=0.10802959125648778,
                                 learning_rate=0.012507391626216524,
                                 max_depth=2, max_features='auto',
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.0593992090305253e-07,
                                 min_samples_leaf=13, min_samples_split=19,
                                 min_weight_fraction_leaf=0.13510597987400375,
                                 n_estimators=481, random_state=123,
                                 subsample=0.9646924257252548,
                                 validation_fraction=0.9483244851205971)

IBS: 0.219

In [73]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [74]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [75]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 08:06:40,446] A new study created in memory with name: no-name-df9e9486-c7a3-49de-995d-7e9e5893d061

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:06:41,643] Trial 0 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:06:51,502] Trial 1 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:06:53,643] Trial 2 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.6818827456832424.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:06:56,615] Trial 3 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6836684599689566.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:00,957] Trial 4 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:05,834] Trial 5 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:08,464] Trial 6 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:09,007] Trial 7 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:11,774] Trial 8 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:19,543] Trial 9 finished with value: 0.6827756028260995 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6864345664115337.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:25,245] Trial 10 finished with value: 0.6882202806972479 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6882202806972479.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:07:31,371] Trial 11 finished with value: 0.7115715778118246 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7115715778118246.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 08:07:36,950] Trial 12 finished with value: 0.7116176878051177 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:43,961] Trial 13 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:07:49,926] Trial 14 finished with value: 0.6973447955496239 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:07:55,530] Trial 15 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:08:04,964] Trial 16 finished with value: 0.6991575661123945 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:08:14,342] Trial 17 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:08:18,433] Trial 18 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.7116176878051177.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:08:19,734] Trial 19 finished with value: 0.6964058284134736 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 08:08:29,177] Trial 20 finished with value: 0.6863884564182405 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:08:39,305] Trial 21 finished with value: 0.6965740799634332 and parameters: {'subsample': 0.19686631492543752, 'dropout_rate': 0.12395834975058428, 'n_estimators': 431, 'learning_rate': 0.09000255639604265}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:08:45,056] Trial 22 finished with value: 0.6928200310983889 and parameters: {'subsample': 0.19525739351764543, 'dropout_rate': 0.10643415732680922, 'n_estimators': 323, 'learning_rate': 0.06478804138779268}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 08:08:52,673] Trial 23 finished with value: 0.6911171668540996 and parameters: {'subsample': 0.15450687211748398, 'dropout_rate': 0.342599622069399, 'n_estimators': 392, 'learning_rate': 0.09234244435311825}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:02,690] Trial 24 finished with value: 0.6873274235543908 and parameters: {'subsample': 0.29008587221754845, 'dropout_rate': 0.19210379926904825, 'n_estimators': 454, 'learning_rate': 0.08024945981885076}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:09:08,720] Trial 25 finished with value: 0.6891592478333981 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.2822107476217279, 'n_estimators': 332, 'learning_rate': 0.08776715920115916}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:12,549] Trial 26 finished with value: 0.6863470313975281 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.18335657306839728, 'n_estimators': 256, 'learning_rate': 0.09286780169440613}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:09:16,050] Trial 27 finished with value: 0.7010037591350581 and parameters: {'subsample': 0.10030892385244675, 'dropout_rate': 0.9861686560685959, 'n_estimators': 297, 'learning_rate': 0.08003642459794733}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:09:20,235] Trial 28 finished with value: 0.7000694769714885 and parameters: {'subsample': 0.10146809971965022, 'dropout_rate': 0.8178252892822001, 'n_estimators': 290, 'learning_rate': 0.07770957646628725}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:23,164] Trial 29 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.5985349208985528, 'n_estimators': 215, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:26,612] Trial 30 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6496340242271839, 'dropout_rate': 0.3892024351052794, 'n_estimators': 233, 'learning_rate': 0.04416682601499452}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:09:30,492] Trial 31 finished with value: 0.7010037591350581 and parameters: {'subsample': 0.10793925840929003, 'dropout_rate': 0.9925382852879747, 'n_estimators': 297, 'learning_rate': 0.07741756299708473}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:09:33,876] Trial 32 finished with value: 0.6892467828474038 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.9882537962971631, 'n_estimators': 294, 'learning_rate': 0.07042499548083488}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:38,220] Trial 33 finished with value: 0.6919178040103706 and parameters: {'subsample': 0.14413020655935896, 'dropout_rate': 0.9635828859485037, 'n_estimators': 341, 'learning_rate': 0.06631150531355927}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:43,720] Trial 34 finished with value: 0.6854541742546709 and parameters: {'subsample': 0.31478192981222664, 'dropout_rate': 0.9247935163675527, 'n_estimators': 386, 'learning_rate': 0.07667511157009024}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:47,058] Trial 35 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.24430564869860838, 'dropout_rate': 0.8260367824882531, 'n_estimators': 275, 'learning_rate': 0.07264491128155415}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 08:09:48,600] Trial 36 finished with value: 0.688349240731966 and parameters: {'subsample': 0.1472799886091495, 'dropout_rate': 0.4898227408931724, 'n_estimators': 129, 'learning_rate': 0.0814321234828091}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:48,788] Trial 37 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.22876685034739064, 'dropout_rate': 0.7769088643081956, 'n_estimators': 1, 'learning_rate': 0.0942551407730424}. Best is trial 12 with value: 0.7116176878051177.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 08:09:50,447] Trial 38 finished with value: 0.698435094024968 and parameters: {'subsample': 0.10130603260320498, 'dropout_rate': 0.9265417979312904, 'n_estimators': 154, 'learning_rate': 0.06034311549365794}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:53,499] Trial 39 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.6100491404460081, 'dropout_rate': 0.6000657611403288, 'n_estimators': 233, 'learning_rate': 0.08287173573083674}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:09:57,543] Trial 40 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.8819292429430127, 'n_estimators': 280, 'learning_rate': 0.07255507912086517}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 08:10:02,041] Trial 41 finished with value: 0.7010959791216443 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.8485815795854617, 'n_estimators': 309, 'learning_rate': 0.07697345233756062}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:06,113] Trial 42 finished with value: 0.6873274235543908 and parameters: {'subsample': 0.17364627952543454, 'dropout_rate': 0.9951966897341563, 'n_estimators': 317, 'learning_rate': 0.06911254892370094}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:11,670] Trial 43 finished with value: 0.6910249468675135 and parameters: {'subsample': 0.13705153275053283, 'dropout_rate': 0.9348703907663215, 'n_estimators': 350, 'learning_rate': 0.09546413769326056}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:14,817] Trial 44 finished with value: 0.6854541742546709 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.8472746127845155, 'n_estimators': 238, 'learning_rate': 0.08458805485836358}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:18,634] Trial 45 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.7637307430138534, 'n_estimators': 309, 'learning_rate': 0.02274904980797578}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:22,959] Trial 46 finished with value: 0.6873274235543908 and parameters: {'subsample': 0.1850824085756943, 'dropout_rate': 0.9617844883175679, 'n_estimators': 367, 'learning_rate': 0.05378014293554952}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:25,128] Trial 47 finished with value: 0.6873274235543908 and parameters: {'subsample': 0.22920504196885155, 'dropout_rate': 0.29499500251304, 'n_estimators': 191, 'learning_rate': 0.09856885210116671}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:10:28,490] Trial 48 finished with value: 0.693749628289378 and parameters: {'subsample': 0.12952420033323772, 'dropout_rate': 0.8847847500519427, 'n_estimators': 268, 'learning_rate': 0.07506276970926945}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:10:35,705] Trial 49 finished with value: 0.6882663906905411 and parameters: {'subsample': 0.1803255415386682, 'dropout_rate': 0.45900105537588515, 'n_estimators': 394, 'learning_rate': 0.00524351186486742}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:40,353] Trial 50 finished with value: 0.6854541742546709 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.633091953438621, 'n_estimators': 326, 'learning_rate': 0.09110417865390581}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:10:43,962] Trial 51 finished with value: 0.7000233669781953 and parameters: {'subsample': 0.10369901111351108, 'dropout_rate': 0.8210934751301505, 'n_estimators': 286, 'learning_rate': 0.07950816240860382}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:48,281] Trial 52 finished with value: 0.6926960698621658 and parameters: {'subsample': 0.12731509681782968, 'dropout_rate': 0.6888062189991595, 'n_estimators': 304, 'learning_rate': 0.07653114284553496}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:10:52,882] Trial 53 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.24503892608309863, 'dropout_rate': 0.8091298089210199, 'n_estimators': 346, 'learning_rate': 0.08606357660195475}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:10:58,852] Trial 54 finished with value: 0.691990517985505 and parameters: {'subsample': 0.17685353092735365, 'dropout_rate': 0.1464738011208001, 'n_estimators': 296, 'learning_rate': 0.06500877653278476}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:11:01,152] Trial 55 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.8636327119412204, 'n_estimators': 211, 'learning_rate': 0.056773941095059816}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:11:04,667] Trial 56 finished with value: 0.6973909055429169 and parameters: {'subsample': 0.1100090876556084, 'dropout_rate': 0.5194091093440398, 'n_estimators': 251, 'learning_rate': 0.09000973833457038}. Best is trial 12 with value: 0.7116176878051177.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:11:09,787] Trial 57 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.20505074926602512, 'dropout_rate': 0.9033865534794092, 'n_estimators': 331, 'learning_rate': 0.08042314476009517}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:11:15,248] Trial 58 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.26259879601440506, 'dropout_rate': 0.9628960782316449, 'n_estimators': 376, 'learning_rate': 0.09772966121712592}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 08:11:19,438] Trial 59 finished with value: 0.6919714642692683 and parameters: {'subsample': 0.14651722397810862, 'dropout_rate': 0.21780602777587757, 'n_estimators': 271, 'learning_rate': 0.047267601674035827}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:11:24,877] Trial 60 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.9718433307655755, 'dropout_rate': 0.7234662927499835, 'n_estimators': 359, 'learning_rate': 0.03723183452431825}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:11:28,711] Trial 61 finished with value: 0.7000233669781953 and parameters: {'subsample': 0.10680929775336306, 'dropout_rate': 0.8073504229571691, 'n_estimators': 287, 'learning_rate': 0.08038781000817144}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:11:32,352] Trial 62 finished with value: 0.7009623341143456 and parameters: {'subsample': 0.10637687141780292, 'dropout_rate': 0.7808014699196044, 'n_estimators': 288, 'learning_rate': 0.07806284183922058}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:11:36,752] Trial 63 finished with value: 0.6863470313975281 and parameters: {'subsample': 0.16437732826628937, 'dropout_rate': 0.7477046987916964, 'n_estimators': 311, 'learning_rate': 0.08809505389911947}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 08:11:41,126] Trial 64 finished with value: 0.6911661421404167 and parameters: {'subsample': 0.1991546381636114, 'dropout_rate': 0.14814178386748486, 'n_estimators': 262, 'learning_rate': 0.0736703958247263}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:11:46,102] Trial 65 finished with value: 0.691830268996365 and parameters: {'subsample': 0.13317870980865773, 'dropout_rate': 0.777111353276567, 'n_estimators': 328, 'learning_rate': 0.06889303242647618}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 08:11:49,284] Trial 66 finished with value: 0.7001155869647816 and parameters: {'subsample': 0.10044908429402967, 'dropout_rate': 0.6965555724278545, 'n_estimators': 239, 'learning_rate': 0.08401063464168246}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 08:11:52,458] Trial 67 finished with value: 0.6872813135610977 and parameters: {'subsample': 0.16228882416005383, 'dropout_rate': 0.67729623574334, 'n_estimators': 241, 'learning_rate': 0.08451755000146183}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:12:03,505] Trial 68 finished with value: 0.6900636084268875 and parameters: {'subsample': 0.13048834071231694, 'dropout_rate': 0.583662202262188, 'n_estimators': 496, 'learning_rate': 0.09222449768422104}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:12:05,900] Trial 69 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.2130395911423627, 'dropout_rate': 0.634473314288703, 'n_estimators': 165, 'learning_rate': 0.08875752985571464}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:12:08,978] Trial 70 finished with value: 0.6882663906905411 and parameters: {'subsample': 0.15320234779982592, 'dropout_rate': 0.7083333653080106, 'n_estimators': 223, 'learning_rate': 0.09348087536317318}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:12:12,665] Trial 71 finished with value: 0.6946201141277595 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.8367527122419222, 'n_estimators': 293, 'learning_rate': 0.07855764607931269}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:12:16,114] Trial 72 finished with value: 0.6991766198286313 and parameters: {'subsample': 0.1028727139714761, 'dropout_rate': 0.7926483405853367, 'n_estimators': 253, 'learning_rate': 0.08218266872297025}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:12:20,491] Trial 73 finished with value: 0.6854541742546709 and parameters: {'subsample': 0.18174562511340475, 'dropout_rate': 0.8576746241390056, 'n_estimators': 338, 'learning_rate': 0.07090449728338004}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:12:23,919] Trial 74 finished with value: 0.6909593308627687 and parameters: {'subsample': 0.1318310706409178, 'dropout_rate': 0.9502334734690494, 'n_estimators': 304, 'learning_rate': 0.08534129442553227}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:12:27,849] Trial 75 finished with value: 0.6982376526924811 and parameters: {'subsample': 0.10156550722415118, 'dropout_rate': 0.9008636994612975, 'n_estimators': 278, 'learning_rate': 0.07726556411934064}. Best is trial 12 with value: 0.7116176878051177.

Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:12:31,639] Trial 76 finished with value: 0.6883078157112535 and parameters: {'subsample': 0.15764335494086937, 'dropout_rate': 0.9976468773191501, 'n_estimators': 319, 'learning_rate': 0.06694592908360744}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:12:39,882] Trial 77 finished with value: 0.6846074271051068 and parameters: {'subsample': 0.5946801499269, 'dropout_rate': 0.11644773895813654, 'n_estimators': 407, 'learning_rate': 0.0739016826717655}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:12:43,538] Trial 78 finished with value: 0.6864345664115337 and parameters: {'subsample': 0.23957179565357356, 'dropout_rate': 0.6468509753854194, 'n_estimators': 266, 'learning_rate': 0.09667690629324206}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:12:44,333] Trial 79 finished with value: 0.6882663906905411 and parameters: {'subsample': 0.20848653992749835, 'dropout_rate': 0.8803384724169618, 'n_estimators': 79, 'learning_rate': 0.08362420320383378}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:12:46,458] Trial 80 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.5096899904392703, 'dropout_rate': 0.7561247329151636, 'n_estimators': 199, 'learning_rate': 0.08763365164769323}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:12:49,894] Trial 81 finished with value: 0.691830268996365 and parameters: {'subsample': 0.1281703870845423, 'dropout_rate': 0.8379046691777832, 'n_estimators': 285, 'learning_rate': 0.07978270020357127}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 08:12:53,949] Trial 82 finished with value: 0.7000233669781953 and parameters: {'subsample': 0.10253823920214977, 'dropout_rate': 0.8170110504728879, 'n_estimators': 292, 'learning_rate': 0.07575857912091358}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 08:12:57,225] Trial 83 finished with value: 0.6883002654456488 and parameters: {'subsample': 0.1515769896379502, 'dropout_rate': 0.9331640285025862, 'n_estimators': 246, 'learning_rate': 0.07861645938401178}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:13:01,851] Trial 84 finished with value: 0.6863470313975281 and parameters: {'subsample': 0.1778729428879251, 'dropout_rate': 0.7415247991072516, 'n_estimators': 315, 'learning_rate': 0.07121024669623024}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:13:08,141] Trial 85 finished with value: 0.6937272569849022 and parameters: {'subsample': 0.12976536751706028, 'dropout_rate': 0.40023366790278014, 'n_estimators': 350, 'learning_rate': 0.06274390460459597}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 08:13:11,367] Trial 86 finished with value: 0.6863884564182405 and parameters: {'subsample': 0.18722056749114702, 'dropout_rate': 0.9830227175287795, 'n_estimators': 282, 'learning_rate': 0.08256954056663622}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:13:13,762] Trial 87 finished with value: 0.6836684599689566 and parameters: {'subsample': 0.4477200052981951, 'dropout_rate': 0.7810258019246846, 'n_estimators': 226, 'learning_rate': 0.09170164272547444}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:13:18,080] Trial 88 finished with value: 0.6946201141277595 and parameters: {'subsample': 0.12033804221369884, 'dropout_rate': 0.7013997521589629, 'n_estimators': 305, 'learning_rate': 0.0859444535613489}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:13:22,468] Trial 89 finished with value: 0.7039910455989394 and parameters: {'subsample': 0.10063486911613191, 'dropout_rate': 0.16689331308725722, 'n_estimators': 263, 'learning_rate': 0.094533289692637}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 08:13:27,930] Trial 90 finished with value: 0.6818827456832424 and parameters: {'subsample': 0.7147405584008215, 'dropout_rate': 0.21111934212317293, 'n_estimators': 339, 'learning_rate': 0.09543331751370338}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:13:32,197] Trial 91 finished with value: 0.6947393903914019 and parameters: {'subsample': 0.1450079087427171, 'dropout_rate': 0.1435742442817984, 'n_estimators': 260, 'learning_rate': 0.09984467676651752}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:13:36,711] Trial 92 finished with value: 0.7059471449400843 and parameters: {'subsample': 0.1198158238649216, 'dropout_rate': 0.11450000896450802, 'n_estimators': 274, 'learning_rate': 0.08966716850964933}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 08:13:41,835] Trial 93 finished with value: 0.6927421798554589 and parameters: {'subsample': 0.16364923574770984, 'dropout_rate': 0.16221907768462301, 'n_estimators': 277, 'learning_rate': 0.0939719771778297}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:13:48,362] Trial 94 finished with value: 0.7087179363552419 and parameters: {'subsample': 0.12407976174838918, 'dropout_rate': 0.1260789509040807, 'n_estimators': 319, 'learning_rate': 0.08809245682289989}. Best is trial 12 with value: 0.7116176878051177.

Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:13:55,050] Trial 95 finished with value: 0.7087179363552419 and parameters: {'subsample': 0.12094113808983019, 'dropout_rate': 0.12381368197367143, 'n_estimators': 322, 'learning_rate': 0.08839758178559988}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 08:14:01,136] Trial 96 finished with value: 0.6974859908225273 and parameters: {'subsample': 0.19613366221760675, 'dropout_rate': 0.12720954690258146, 'n_estimators': 322, 'learning_rate': 0.08863218395889488}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 08:14:09,663] Trial 97 finished with value: 0.6956812228205761 and parameters: {'subsample': 0.22570028642335044, 'dropout_rate': 0.12609953868133764, 'n_estimators': 377, 'learning_rate': 0.09713096619651705}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 08:14:17,436] Trial 98 finished with value: 0.7012105704127062 and parameters: {'subsample': 0.12082568982911768, 'dropout_rate': 0.17690317640867337, 'n_estimators': 360, 'learning_rate': 0.09041541572802629}. Best is trial 12 with value: 0.7116176878051177.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6962025316455697

[I 2024-04-18 08:14:24,681] A new study created in memory with name: no-name-7587161f-05c6-438c-80c6-a536c5e8a06d

Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 08:14:24,565] Trial 99 finished with value: 0.6827294928328064 and parameters: {'subsample': 0.9255589012900443, 'dropout_rate': 0.10038744294819149, 'n_estimators': 361, 'learning_rate': 0.09046954994473323}. Best is trial 12 with value: 0.7116176878051177.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.7116176878051177], datetime_start=datetime.datetime(2024, 4, 18, 8, 7, 31, 408030), datetime_complete=datetime.datetime(2024, 4, 18, 8, 7, 36, 949935), params={'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=12, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}


* Best Score for C-index:
 0.7116176878051177

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24692977896599883
Fold 2 IBS: 0.14100123517243607
Fold 3 IBS: 0.1880250783838741
Fold 4 IBS: 0.16820105601641033
Fold 5 IBS: 0.17905313474573403
[I 2024-04-18 08:14:26,016] Trial 0 finished with value: 0.18464205665689068 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.18464205665689068.
Fold 1 IBS: 0.3168791384838904
Fold 2 IBS: 0.2030802708652265
Fold 3 IBS: 0.26841849514165816
Fold 4 IBS: 0.2308912756337829
Fold 5 IBS: 0.2245274969999254
[I 2024-04-18 08:14:36,692] Trial 1 finished with value: 0.24875933542489664 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.18464205665689068.
Fold 1 IBS: 0.2753019447545149
Fold 2 IBS: 0.1604880744082936
Fold 3 IBS: 0.2301926387588787
Fold 4 IBS: 0.18976351360939325
Fold 5 IBS: 0.1964160299910194
[I 2024-04-18 08:14:38,783] Trial 2 finished with value: 0.21043244030442 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.18464205665689068.
Fold 1 IBS: 0.2786819074278709
Fold 2 IBS: 0.15958277115529845
Fold 3 IBS: 0.2368181124229354
Fold 4 IBS: 0.19305804819206035
Fold 5 IBS: 0.1986140645673611
[I 2024-04-18 08:14:41,383] Trial 3 finished with value: 0.21335098075310524 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.18464205665689068.
Fold 1 IBS: 0.279609328489835
Fold 2 IBS: 0.16092445706018813
Fold 3 IBS: 0.23283988262699706
Fold 4 IBS: 0.19173360454087396
Fold 5 IBS: 0.19929028403150847
[I 2024-04-18 08:14:45,907] Trial 4 finished with value: 0.21287951134988053 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.18464205665689068.
Fold 1 IBS: 0.30156654310213465
Fold 2 IBS: 0.18973773181040562
Fold 3 IBS: 0.258408956688429
Fold 4 IBS: 0.21479553347955327
Fold 5 IBS: 0.21596809958257804
[I 2024-04-18 08:14:51,536] Trial 5 finished with value: 0.23609537293262012 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.18464205665689068.
Fold 1 IBS: 0.23284347689671558
Fold 2 IBS: 0.13985573614470903
Fold 3 IBS: 0.17487245474686242
Fold 4 IBS: 0.16496023006899552
Fold 5 IBS: 0.1728687714076619
[I 2024-04-18 08:14:54,181] Trial 6 finished with value: 0.17708013385298887 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.2094417944305012
Fold 2 IBS: 0.1594423478282019
Fold 3 IBS: 0.174257639652186
Fold 4 IBS: 0.17647985301403105
Fold 5 IBS: 0.17922856726834632
[I 2024-04-18 08:14:55,345] Trial 7 finished with value: 0.1797700404386533 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.2500273900096136
Fold 2 IBS: 0.14086777557383368
Fold 3 IBS: 0.1940458545563511
Fold 4 IBS: 0.16973742521134863
Fold 5 IBS: 0.18197983370368676
[I 2024-04-18 08:14:58,197] Trial 8 finished with value: 0.18733165581096675 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.3046029224708627
Fold 2 IBS: 0.18879417699026205
Fold 3 IBS: 0.26054874310112364
Fold 4 IBS: 0.21799302453410474
Fold 5 IBS: 0.21714447310156704
[I 2024-04-18 08:15:05,347] Trial 9 finished with value: 0.23781666803958404 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.20753801562899382
Fold 2 IBS: 0.1992407217422468
Fold 3 IBS: 0.1925559940808459
Fold 4 IBS: 0.20739540643308532
Fold 5 IBS: 0.2016948735020121
[I 2024-04-18 08:15:12,380] Trial 10 finished with value: 0.2016850022774368 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 328, 'learning_rate': 0.0017980531969980576}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.2132850691785392
Fold 2 IBS: 0.2186769331762444
Fold 3 IBS: 0.20349124979478508
Fold 4 IBS: 0.22264615812553304
Fold 5 IBS: 0.21681736633432214
[I 2024-04-18 08:15:12,767] Trial 11 finished with value: 0.21498335532188478 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.23750800709711103
Fold 2 IBS: 0.13802764866881614
Fold 3 IBS: 0.1800175429511785
Fold 4 IBS: 0.16541793997662613
Fold 5 IBS: 0.17596264942171488
[I 2024-04-18 08:15:13,869] Trial 12 finished with value: 0.17938675762308934 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.2679467451203346
Fold 2 IBS: 0.15240166584573128
Fold 3 IBS: 0.22031756577002837
Fold 4 IBS: 0.18280344248982852
Fold 5 IBS: 0.1929542549146904
[I 2024-04-18 08:15:15,463] Trial 13 finished with value: 0.20328473482812265 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.4001159443378324, 'n_estimators': 109, 'learning_rate': 0.09856277651579823}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.2664170877777922
Fold 2 IBS: 0.15158119606113526
Fold 3 IBS: 0.2194074489133718
Fold 4 IBS: 0.18171498890365262
Fold 5 IBS: 0.19244385232214975
[I 2024-04-18 08:15:16,413] Trial 14 finished with value: 0.20231291479562033 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 102, 'learning_rate': 0.09964553963945819}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.20866129120669294
Fold 2 IBS: 0.2098938742920915
Fold 3 IBS: 0.19592433243706928
Fold 4 IBS: 0.21359185550636317
Fold 5 IBS: 0.2094875029408041
[I 2024-04-18 08:15:17,111] Trial 15 finished with value: 0.20751177127660422 and parameters: {'subsample': 0.10294255497547983, 'dropout_rate': 0.29557448514938967, 'n_estimators': 49, 'learning_rate': 0.00882614648800595}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.2419163615134226
Fold 2 IBS: 0.13693100925641374
Fold 3 IBS: 0.18165410161783543
Fold 4 IBS: 0.16620875405333807
Fold 5 IBS: 0.17758147936978042
[I 2024-04-18 08:15:20,785] Trial 16 finished with value: 0.18085834116215807 and parameters: {'subsample': 0.29391461974521166, 'dropout_rate': 0.7899949638176231, 'n_estimators': 271, 'learning_rate': 0.02047377291427832}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.27252090512787397
Fold 2 IBS: 0.15231085796114247
Fold 3 IBS: 0.22750013572095168
Fold 4 IBS: 0.18661577691093853
Fold 5 IBS: 0.19511849955001256
[I 2024-04-18 08:15:22,715] Trial 17 finished with value: 0.20681323505418386 and parameters: {'subsample': 0.6340507845187373, 'dropout_rate': 0.10421921753457947, 'n_estimators': 165, 'learning_rate': 0.08223463771239999}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.21036717503733576
Fold 2 IBS: 0.20974648687374103
Fold 3 IBS: 0.19793208855046884
Fold 4 IBS: 0.2154872531508152
Fold 5 IBS: 0.20989290549206738
[I 2024-04-18 08:15:23,114] Trial 18 finished with value: 0.20868518182088563 and parameters: {'subsample': 0.8187174952613757, 'dropout_rate': 0.5643051003990627, 'n_estimators': 7, 'learning_rate': 0.04217501697666381}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.3088335456509054

Fold 2 IBS: 0.1806549522812558
Fold 3 IBS: 0.2626642449139272
Fold 4 IBS: 0.22142266311808342
Fold 5 IBS: 0.21718912459536338
[I 2024-04-18 08:15:29,453] Trial 19 finished with value: 0.23815290611190704 and parameters: {'subsample': 0.38793667853472646, 'dropout_rate': 0.22827203020188386, 'n_estimators': 324, 'learning_rate': 0.08697733590757546}. Best is trial 6 with value: 0.17708013385298887.
Fold 1 IBS: 0.21571820396955296
Fold 2 IBS: 0.1504945945870415
Fold 3 IBS: 0.1720434961065403
Fold 4 IBS: 0.1707499999148482
Fold 5 IBS: 0.1731189833324429
[I 2024-04-18 08:15:31,399] Trial 20 finished with value: 0.17642505558208518 and parameters: {'subsample': 0.6102628884762309, 'dropout_rate': 0.5558690358940764, 'n_estimators': 149, 'learning_rate': 0.017331004877487094}. Best is trial 20 with value: 0.17642505558208518.
Fold 1 IBS: 0.21422382295710835
Fold 2 IBS: 0.15300561222318346
Fold 3 IBS: 0.17291484540313803
Fold 4 IBS: 0.17228920130049374
Fold 5 IBS: 0.17394906275993324
[I 2024-04-18 08:15:32,717] Trial 21 finished with value: 0.1772765089287714 and parameters: {'subsample': 0.6165496196241105, 'dropout_rate': 0.9754161103921428, 'n_estimators': 142, 'learning_rate': 0.016867151673453804}. Best is trial 20 with value: 0.17642505558208518.
Fold 1 IBS: 0.22575387569882605
Fold 2 IBS: 0.14255266830900062
Fold 3 IBS: 0.17199918299786499
Fold 4 IBS: 0.16613004504024306
Fold 5 IBS: 0.17177503367652044
[I 2024-04-18 08:15:35,389] Trial 22 finished with value: 0.17564216114449105 and parameters: {'subsample': 0.637312396919241, 'dropout_rate': 0.9832511198723066, 'n_estimators': 221, 'learning_rate': 0.01557109179501204}. Best is trial 22 with value: 0.17564216114449105.
Fold 1 IBS: 0.2526338832093575
Fold 2 IBS: 0.1430605884397998
Fold 3 IBS: 0.19678217082812216
Fold 4 IBS: 0.1711293392980561
Fold 5 IBS: 0.1837972289615487
[I 2024-04-18 08:15:38,508] Trial 23 finished with value: 0.18948064214737684 and parameters: {'subsample': 0.8112423090302406, 'dropout_rate': 0.37293535681418793, 'n_estimators': 220, 'learning_rate': 0.03310431104757328}. Best is trial 22 with value: 0.17564216114449105.
Fold 1 IBS: 0.22780546174833385
Fold 2 IBS: 0.14148603901974316
Fold 3 IBS: 0.17257310015405247
Fold 4 IBS: 0.16553967895875601
Fold 5 IBS: 0.17193448335169711
[I 2024-04-18 08:15:41,323] Trial 24 finished with value: 0.17586775264651652 and parameters: {'subsample': 0.5954984634734557, 'dropout_rate': 0.9859451830394055, 'n_estimators': 252, 'learning_rate': 0.01448783706935496}. Best is trial 22 with value: 0.17564216114449105.
Fold 1 IBS: 0.22330670091983987
Fold 2 IBS: 0.1439440040739575
Fold 3 IBS: 0.17168346685340596
Fold 4 IBS: 0.16684464604972554
Fold 5 IBS: 0.17178859556890788
[I 2024-04-18 08:15:44,272] Trial 25 finished with value: 0.17551348269316736 and parameters: {'subsample': 0.607884101176659, 'dropout_rate': 0.9916995260298861, 'n_estimators': 242, 'learning_rate': 0.013287182579533728}. Best is trial 25 with value: 0.17551348269316736.
Fold 1 IBS: 0.21839185290840044
Fold 2 IBS: 0.14742483412137497
Fold 3 IBS: 0.17166963740680663
Fold 4 IBS: 0.16941750494494903
Fold 5 IBS: 0.1730238685178229
[I 2024-04-18 08:15:47,785] Trial 26 finished with value: 0.1759855395798708 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9923627109552451, 'n_estimators': 304, 'learning_rate': 0.009165620361301537}. Best is trial 25 with value: 0.17551348269316736.
Fold 1 IBS: 0.20693642209028565
Fold 2 IBS: 0.19653294472696506
Fold 3 IBS: 0.1910835541192406
Fold 4 IBS: 0.20529134799224716
Fold 5 IBS: 0.19978938732362433
[I 2024-04-18 08:15:52,887] Trial 27 finished with value: 0.19992673125047253 and parameters: {'subsample': 0.5737541797093635, 'dropout_rate': 0.8996088646720516, 'n_estimators': 393, 'learning_rate': 0.0017143233546836716}. Best is trial 25 with value: 0.17551348269316736.
Fold 1 IBS: 0.22303954267491094
Fold 2 IBS: 0.14393623495126381
Fold 3 IBS: 0.17177368916483476
Fold 4 IBS: 0.16672627997918968
Fold 5 IBS: 0.17178359689996417
[I 2024-04-18 08:15:56,279] Trial 28 finished with value: 0.17545186873403268 and parameters: {'subsample': 0.6711314027892421, 'dropout_rate': 0.8231192771151936, 'n_estimators': 243, 'learning_rate': 0.013252654394293913}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.2724764945261554
Fold 2 IBS: 0.1573233114465332
Fold 3 IBS: 0.22760254735104432
Fold 4 IBS: 0.1867918976347646
Fold 5 IBS: 0.195936652419097
[I 2024-04-18 08:16:00,011] Trial 29 finished with value: 0.2080261806755189 and parameters: {'subsample': 0.703988900382532, 'dropout_rate': 0.8303450471528143, 'n_estimators': 291, 'learning_rate': 0.03981939157015678}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.21467265873757443
Fold 2 IBS: 0.1523462630413524
Fold 3 IBS: 0.17257742443129007
Fold 4 IBS: 0.17179626331002779
Fold 5 IBS: 0.17379521231136333
[I 2024-04-18 08:16:02,519] Trial 30 finished with value: 0.17703756436632162 and parameters: {'subsample': 0.8740749317122405, 'dropout_rate': 0.9287448837244532, 'n_estimators': 230, 'learning_rate': 0.01065102813229351}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.22142549290500477
Fold 2 IBS: 0.14532961964705254
Fold 3 IBS: 0.17159731115911858
Fold 4 IBS: 0.1677353473345828
Fold 5 IBS: 0.17195447832180533
[I 2024-04-18 08:16:05,236] Trial 31 finished with value: 0.17560844987351282 and parameters: {'subsample': 0.6750057743051725, 'dropout_rate': 0.9984662387895484, 'n_estimators': 246, 'learning_rate': 0.012338516566793597}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.24428439710035585
Fold 2 IBS: 0.14040689804098264
Fold 3 IBS: 0.186222888024671
Fold 4 IBS: 0.16715272307333567
Fold 5 IBS: 0.17849762642708475
[I 2024-04-18 08:16:08,530] Trial 32 finished with value: 0.183312906533286 and parameters: {'subsample': 0.6820353279444507, 'dropout_rate': 0.7933236343517561, 'n_estimators': 239, 'learning_rate': 0.02424595990113742}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.21279045400146324
Fold 2 IBS: 0.15490016319115144
Fold 3 IBS: 0.1733129315465723
Fold 4 IBS: 0.17369669256590353
Fold 5 IBS: 0.17487858163225906
[I 2024-04-18 08:16:13,667] Trial 33 finished with value: 0.1779157645874699 and parameters: {'subsample': 0.7443076133594272, 'dropout_rate': 0.9400325463168487, 'n_estimators': 358, 'learning_rate': 0.006353618717647971}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.25898560085418515
Fold 2 IBS: 0.14557702375182172
Fold 3 IBS: 0.20745492567229518
Fold 4 IBS: 0.1755161705374986
Fold 5 IBS: 0.1876054906456792
[I 2024-04-18 08:16:17,631] Trial 34 finished with value: 0.19502784229229597 and parameters: {'subsample': 0.5120619260663193, 'dropout_rate': 0.8419723253096957, 'n_estimators': 287, 'learning_rate': 0.029517939071893647}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.2508402141802261
Fold 2 IBS: 0.14225813011599034
Fold 3 IBS: 0.19371402503110363
Fold 4 IBS: 0.17018377334928264
Fold 5 IBS: 0.18217052486855667
[I 2024-04-18 08:16:19,585] Trial 35 finished with value: 0.1878333335090319 and parameters: {'subsample': 0.5410763754159423, 'dropout_rate': 0.9999315635622426, 'n_estimators': 187, 'learning_rate': 0.03657436163177362}. Best is trial 28 with value: 0.17545186873403268.
Fold 1 IBS: 0.22280511090811736
Fold 2 IBS: 0.14407060000443286
Fold 3 IBS: 0.17173604636821208
Fold 4 IBS: 0.16684645409073273
Fold 5 IBS: 0.17179810231865672
[I 2024-04-18 08:16:22,993] Trial 36 finished with value: 0.17545126273803033 and parameters: {'subsample': 0.6689949239769296, 'dropout_rate': 0.7803451305864744, 'n_estimators': 251, 'learning_rate': 0.012746071877375342}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.28461950496379945
Fold 2 IBS: 0.1715637963832196
Fold 3 IBS: 0.24359169081257856
Fold 4 IBS: 0.1985022649593517
Fold 5 IBS: 0.20400593299098083
[I 2024-04-18 08:16:26,715] Trial 37 finished with value: 0.22045663802198603 and parameters: {'subsample': 0.7720395186820249, 'dropout_rate': 0.7621022900062648, 'n_estimators': 259, 'learning_rate': 0.059207327336158105}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2616486283968891

Fold 2 IBS: 0.14792185158467971
Fold 3 IBS: 0.21099096752400537
Fold 4 IBS: 0.17749683277884493
Fold 5 IBS: 0.18951087472922412
[I 2024-04-18 08:16:33,263] Trial 38 finished with value: 0.19751383100272865 and parameters: {'subsample': 0.672433369611978, 'dropout_rate': 0.8916907706526339, 'n_estimators': 406, 'learning_rate': 0.02207087345824238}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.23420785619175652
Fold 2 IBS: 0.13885849523121738
Fold 3 IBS: 0.17671673311532535
Fold 4 IBS: 0.16499092522728498
Fold 5 IBS: 0.173610528604103
[I 2024-04-18 08:16:37,581] Trial 39 finished with value: 0.17767690767393746 and parameters: {'subsample': 0.44350783452649856, 'dropout_rate': 0.8560401235471927, 'n_estimators': 337, 'learning_rate': 0.013270934894443748}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.205387901723201
Fold 2 IBS: 0.18350743788057733
Fold 3 IBS: 0.1849715526954976
Fold 4 IBS: 0.19513263070538195
Fold 5 IBS: 0.19071458823853912
[I 2024-04-18 08:16:40,176] Trial 40 finished with value: 0.1919428222486394 and parameters: {'subsample': 0.7088154249836619, 'dropout_rate': 0.9399824483131813, 'n_estimators': 200, 'learning_rate': 0.005328400219800716}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.233846945766924
Fold 2 IBS: 0.13975279515773215
Fold 3 IBS: 0.1751879327775663
Fold 4 IBS: 0.1649559068346676
Fold 5 IBS: 0.17323843629430907
[I 2024-04-18 08:16:42,532] Trial 41 finished with value: 0.17739640336623985 and parameters: {'subsample': 0.6323404739822789, 'dropout_rate': 0.9501094790763067, 'n_estimators': 242, 'learning_rate': 0.017815984603248545}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21853634076787049
Fold 2 IBS: 0.1476274443952224
Fold 3 IBS: 0.17166052113081198
Fold 4 IBS: 0.16878750862511693
Fold 5 IBS: 0.1726171631589831
[I 2024-04-18 08:16:45,120] Trial 42 finished with value: 0.17584579561560099 and parameters: {'subsample': 0.5510215808208185, 'dropout_rate': 0.883131172876095, 'n_estimators': 210, 'learning_rate': 0.013416976705539938}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2527866520823466
Fold 2 IBS: 0.1431726928503301
Fold 3 IBS: 0.19772638990152858
Fold 4 IBS: 0.17125603313155485
Fold 5 IBS: 0.18389146473746573
[I 2024-04-18 08:16:48,432] Trial 43 finished with value: 0.18976664654064518 and parameters: {'subsample': 0.7864157475514798, 'dropout_rate': 0.7898710555099768, 'n_estimators': 276, 'learning_rate': 0.026086302319731823}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20609964875788067
Fold 2 IBS: 0.172362127022325
Fold 3 IBS: 0.1796626302275083
Fold 4 IBS: 0.18638364876439872
Fold 5 IBS: 0.1838302791492613
[I 2024-04-18 08:16:52,252] Trial 44 finished with value: 0.1856676667842748 and parameters: {'subsample': 0.6498427951767871, 'dropout_rate': 0.8290941515204971, 'n_estimators': 306, 'learning_rate': 0.004749264138799706}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.22612830846182955
Fold 2 IBS: 0.1419514921090817
Fold 3 IBS: 0.1724904830702952
Fold 4 IBS: 0.1657296883980035
Fold 5 IBS: 0.17184498255574357
[I 2024-04-18 08:16:54,725] Trial 45 finished with value: 0.1756289909189907 and parameters: {'subsample': 0.7162739766263253, 'dropout_rate': 0.7211101091126945, 'n_estimators': 181, 'learning_rate': 0.019596902743912525}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.22743962774873977
Fold 2 IBS: 0.14133335422363874
Fold 3 IBS: 0.17292580337511973
Fold 4 IBS: 0.16545253434656473
Fold 5 IBS: 0.17198942757702998
[I 2024-04-18 08:16:56,881] Trial 46 finished with value: 0.1758281494542186 and parameters: {'subsample': 0.7133269465452006, 'dropout_rate': 0.7334277722736385, 'n_estimators': 167, 'learning_rate': 0.02204152496426229}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20581299430909686
Fold 2 IBS: 0.17432819777548506
Fold 3 IBS: 0.18039360929870743
Fold 4 IBS: 0.18759235447464465
Fold 5 IBS: 0.18471066285260268
[I 2024-04-18 08:16:58,267] Trial 47 finished with value: 0.1865675637421073 and parameters: {'subsample': 0.8900383311093698, 'dropout_rate': 0.67010030869509, 'n_estimators': 130, 'learning_rate': 0.010652107341816578}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21983303626754333
Fold 2 IBS: 0.14660091727384336
Fold 3 IBS: 0.17168968485976555
Fold 4 IBS: 0.16805005792859942
Fold 5 IBS: 0.1725668003080758
[I 2024-04-18 08:16:59,361] Trial 48 finished with value: 0.1757480993275655 and parameters: {'subsample': 0.5728195977448529, 'dropout_rate': 0.46836307650003633, 'n_estimators': 88, 'learning_rate': 0.03302159192010344}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.26404658333404396
Fold 2 IBS: 0.14971052954390093
Fold 3 IBS: 0.21536508989877162
Fold 4 IBS: 0.1796433704142625
Fold 5 IBS: 0.19109889457239232
[I 2024-04-18 08:17:01,612] Trial 49 finished with value: 0.19997289355267425 and parameters: {'subsample': 0.7425717610352343, 'dropout_rate': 0.7065404161117167, 'n_estimators': 195, 'learning_rate': 0.04897928524498507}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21108658763633512
Fold 2 IBS: 0.2125315306549399
Fold 3 IBS: 0.19956814181607255
Fold 4 IBS: 0.21788594583021745
Fold 5 IBS: 0.2117600596718478
[I 2024-04-18 08:17:04,107] Trial 50 finished with value: 0.21056645312188257 and parameters: {'subsample': 0.47670374152096184, 'dropout_rate': 0.6111462911173788, 'n_estimators': 174, 'learning_rate': 0.001318740643247624}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.23447638167471446
Fold 2 IBS: 0.13963666487887982
Fold 3 IBS: 0.1756621070339448
Fold 4 IBS: 0.16496122754491077
Fold 5 IBS: 0.17351013937976825
[I 2024-04-18 08:17:07,075] Trial 51 finished with value: 0.17764930410244362 and parameters: {'subsample': 0.6686865339262029, 'dropout_rate': 0.9239845078050664, 'n_estimators': 232, 'learning_rate': 0.018963281128964324}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2914940932402354
Fold 2 IBS: 0.17905340146137785
Fold 3 IBS: 0.24954283249448309
Fold 4 IBS: 0.2043844509975199
Fold 5 IBS: 0.20879720607403512
[I 2024-04-18 08:17:09,950] Trial 52 finished with value: 0.22665439685353025 and parameters: {'subsample': 0.6869178778540165, 'dropout_rate': 0.9600633898082516, 'n_estimators': 257, 'learning_rate': 0.06897169590691814}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2189601367971568
Fold 2 IBS: 0.14722720319293517
Fold 3 IBS: 0.17163264243454482
Fold 4 IBS: 0.16863759180545565
Fold 5 IBS: 0.17237124319393582
[I 2024-04-18 08:17:12,568] Trial 53 finished with value: 0.17576576348480566 and parameters: {'subsample': 0.5848239967468922, 'dropout_rate': 0.8665394999501789, 'n_estimators': 205, 'learning_rate': 0.013979506086591167}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.25554380171974966
Fold 2 IBS: 0.144409846486206
Fold 3 IBS: 0.2019808079552318
Fold 4 IBS: 0.17303733173631736
Fold 5 IBS: 0.1857162979095392
[I 2024-04-18 08:17:16,304] Trial 54 finished with value: 0.1921376171614088 and parameters: {'subsample': 0.6502757456693204, 'dropout_rate': 0.7544687380403234, 'n_estimators': 277, 'learning_rate': 0.027933567749548693}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20765757930301112
Fold 2 IBS: 0.16568962131397333
Fold 3 IBS: 0.17697650587351582
Fold 4 IBS: 0.18114463671666725
Fold 5 IBS: 0.18009321362133368
[I 2024-04-18 08:17:18,691] Trial 55 finished with value: 0.18231231136570022 and parameters: {'subsample': 0.7660608425749214, 'dropout_rate': 0.8100463053967247, 'n_estimators': 216, 'learning_rate': 0.007925228731791406}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21475313400019028
Fold 2 IBS: 0.15181411675299272
Fold 3 IBS: 0.17238821853543243
Fold 4 IBS: 0.17149221050697508
Fold 5 IBS: 0.17362561262996784
[I 2024-04-18 08:17:20,547] Trial 56 finished with value: 0.17681465848511166 and parameters: {'subsample': 0.8136933520185717, 'dropout_rate': 0.5194091093440398, 'n_estimators': 153, 'learning_rate': 0.016115206811229563}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.24791547157336888

Fold 2 IBS: 0.14136069617897423
Fold 3 IBS: 0.19077540790490488
Fold 4 IBS: 0.1685716554770952
Fold 5 IBS: 0.18079976141115142
[I 2024-04-18 08:17:24,578] Trial 57 finished with value: 0.18588459850909891 and parameters: {'subsample': 0.722713662188781, 'dropout_rate': 0.910417632083181, 'n_estimators': 310, 'learning_rate': 0.020570994628935912}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21269836118729812
Fold 2 IBS: 0.15512924316813698
Fold 3 IBS: 0.17363497274043274
Fold 4 IBS: 0.17400050761889904
Fold 5 IBS: 0.17502156774388983
[I 2024-04-18 08:17:26,458] Trial 58 finished with value: 0.17809693049173134 and parameters: {'subsample': 0.6249882398313333, 'dropout_rate': 0.9713770012669294, 'n_estimators': 184, 'learning_rate': 0.012229054440115003}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20550726620803447
Fold 2 IBS: 0.17740120082704586
Fold 3 IBS: 0.18179949438193768
Fold 4 IBS: 0.1901135316676914
Fold 5 IBS: 0.1871967533189637
[I 2024-04-18 08:17:29,563] Trial 59 finished with value: 0.1884036492807346 and parameters: {'subsample': 0.5214943866846296, 'dropout_rate': 0.6082575631815648, 'n_estimators': 225, 'learning_rate': 0.005687592209530899}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.24875306866019722
Fold 2 IBS: 0.14174209446015432
Fold 3 IBS: 0.19206169715593646
Fold 4 IBS: 0.16914048963878275
Fold 5 IBS: 0.18147553230747204
[I 2024-04-18 08:17:32,913] Trial 60 finished with value: 0.18663457644450857 and parameters: {'subsample': 0.8451462898480937, 'dropout_rate': 0.8789154375563654, 'n_estimators': 256, 'learning_rate': 0.025466153792787872}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20738603736918942
Fold 2 IBS: 0.166965350604845
Fold 3 IBS: 0.1781137639076077
Fold 4 IBS: 0.1815679539761091
Fold 5 IBS: 0.1814447758213318
[I 2024-04-18 08:17:33,963] Trial 61 finished with value: 0.18309557633581658 and parameters: {'subsample': 0.5596829318409458, 'dropout_rate': 0.3258271951933139, 'n_estimators': 86, 'learning_rate': 0.019406374192800176}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21988748867572785
Fold 2 IBS: 0.14689177270576298
Fold 3 IBS: 0.1716857332620628
Fold 4 IBS: 0.1680627336049118
Fold 5 IBS: 0.1726264314235802
[I 2024-04-18 08:17:35,110] Trial 62 finished with value: 0.17583083193440913 and parameters: {'subsample': 0.5995647237767003, 'dropout_rate': 0.44330243013043774, 'n_estimators': 89, 'learning_rate': 0.03288463236048392}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.228326016825651
Fold 2 IBS: 0.14121812371900708
Fold 3 IBS: 0.17321539033726965
Fold 4 IBS: 0.16534598614673646
Fold 5 IBS: 0.17215572370613988
[I 2024-04-18 08:17:36,413] Trial 63 finished with value: 0.1760522481469608 and parameters: {'subsample': 0.6507331372180714, 'dropout_rate': 0.702496577850376, 'n_estimators': 125, 'learning_rate': 0.030080343217445536}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21509559909005968
Fold 2 IBS: 0.15157212074318754
Fold 3 IBS: 0.17253300873545194
Fold 4 IBS: 0.17166589148179978
Fold 5 IBS: 0.1739758619528077
[I 2024-04-18 08:17:39,893] Trial 64 finished with value: 0.1769684964006613 and parameters: {'subsample': 0.5763352838930249, 'dropout_rate': 0.4988567405402422, 'n_estimators': 243, 'learning_rate': 0.010177248161205351}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20552444694267466
Fold 2 IBS: 0.175985375257829
Fold 3 IBS: 0.1808184758304314
Fold 4 IBS: 0.18911527778884057
Fold 5 IBS: 0.18585829040232726
[I 2024-04-18 08:17:40,366] Trial 65 finished with value: 0.1874603732444206 and parameters: {'subsample': 0.6929123326101084, 'dropout_rate': 0.6443401692103621, 'n_estimators': 35, 'learning_rate': 0.037391021790861234}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.27844822156067306
Fold 2 IBS: 0.16378392154960042
Fold 3 IBS: 0.23489056953383
Fold 4 IBS: 0.1921794317369274
Fold 5 IBS: 0.19968576224670376
[I 2024-04-18 08:17:44,808] Trial 66 finished with value: 0.2137975813255469 and parameters: {'subsample': 0.617830605996405, 'dropout_rate': 0.40663128383759806, 'n_estimators': 288, 'learning_rate': 0.046705443501648895}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.23460655673149472
Fold 2 IBS: 0.13917436822663684
Fold 3 IBS: 0.17627998533471623
Fold 4 IBS: 0.16497074072332363
Fold 5 IBS: 0.17338337377733415
[I 2024-04-18 08:17:49,065] Trial 67 finished with value: 0.1776830049587011 and parameters: {'subsample': 0.4590303067651391, 'dropout_rate': 0.4574474815027163, 'n_estimators': 270, 'learning_rate': 0.016624524781173832}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.22865662052340777
Fold 2 IBS: 0.14103329907364467
Fold 3 IBS: 0.17322821957058654
Fold 4 IBS: 0.16528035570060198
Fold 5 IBS: 0.17208995680780953
[I 2024-04-18 08:17:59,606] Trial 68 finished with value: 0.1760576903352101 and parameters: {'subsample': 0.7421724963837376, 'dropout_rate': 0.583662202262188, 'n_estimators': 496, 'learning_rate': 0.0076260334588802246}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2374780572566278
Fold 2 IBS: 0.13497001878635037
Fold 3 IBS: 0.17493190423972282
Fold 4 IBS: 0.16482262774843645
Fold 5 IBS: 0.1761884485076789
[I 2024-04-18 08:18:02,419] Trial 69 finished with value: 0.17767821130776326 and parameters: {'subsample': 0.18890607008448618, 'dropout_rate': 0.997476704761639, 'n_estimators': 219, 'learning_rate': 0.022640312867198413}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2603156454432008
Fold 2 IBS: 0.14724409904357
Fold 3 IBS: 0.2069514869902639
Fold 4 IBS: 0.17637058315937992
Fold 5 IBS: 0.18815911251604853
[I 2024-04-18 08:18:04,043] Trial 70 finished with value: 0.19580818543049264 and parameters: {'subsample': 0.5084977031220654, 'dropout_rate': 0.967577570148886, 'n_estimators': 158, 'learning_rate': 0.05474597229332904}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.22119389679318882
Fold 2 IBS: 0.14528002641686158
Fold 3 IBS: 0.17162386817779765
Fold 4 IBS: 0.16752284838326825
Fold 5 IBS: 0.17197854382439215
[I 2024-04-18 08:18:06,427] Trial 71 finished with value: 0.1755198367191017 and parameters: {'subsample': 0.5800741294699391, 'dropout_rate': 0.864091162260344, 'n_estimators': 203, 'learning_rate': 0.015128283822233236}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21980330242735066
Fold 2 IBS: 0.14625774602917396
Fold 3 IBS: 0.17159729493232148
Fold 4 IBS: 0.16795584650822204
Fold 5 IBS: 0.1723005070853183
[I 2024-04-18 08:18:09,258] Trial 72 finished with value: 0.1755829393964773 and parameters: {'subsample': 0.5466126216372752, 'dropout_rate': 0.7697743279466096, 'n_estimators': 192, 'learning_rate': 0.015300594792960453}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2128038965748019
Fold 2 IBS: 0.15445506675651885
Fold 3 IBS: 0.1730063242286206
Fold 4 IBS: 0.17310550778963923
Fold 5 IBS: 0.17517635318109753
[I 2024-04-18 08:18:11,583] Trial 73 finished with value: 0.17770942970613562 and parameters: {'subsample': 0.5409594684160941, 'dropout_rate': 0.7633291684337107, 'n_estimators': 192, 'learning_rate': 0.011942340517572442}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20574060782599765
Fold 2 IBS: 0.1885701728742647
Fold 3 IBS: 0.1870766941889136
Fold 4 IBS: 0.19891022074891432
Fold 5 IBS: 0.1941643954133883
[I 2024-04-18 08:18:15,148] Trial 74 finished with value: 0.1948924182102957 and parameters: {'subsample': 0.65808944841084, 'dropout_rate': 0.8287824228632, 'n_estimators': 236, 'learning_rate': 0.0038380807009503384}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21745672799803045
Fold 2 IBS: 0.14860858403319308
Fold 3 IBS: 0.17180478006518726
Fold 4 IBS: 0.16938795743031176
Fold 5 IBS: 0.17270899721473612
[I 2024-04-18 08:18:17,094] Trial 75 finished with value: 0.17599340934829172 and parameters: {'subsample': 0.6882223870109341, 'dropout_rate': 0.9130984463844224, 'n_estimators': 175, 'learning_rate': 0.015490758659062303}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.23897806742107064

Fold 2 IBS: 0.13955997775414206
Fold 3 IBS: 0.1807687133909246
Fold 4 IBS: 0.16556961812830692
Fold 5 IBS: 0.175676217950483
[I 2024-04-18 08:18:19,747] Trial 76 finished with value: 0.18011051892898547 and parameters: {'subsample': 0.6018652093062146, 'dropout_rate': 0.8548910278043131, 'n_estimators': 209, 'learning_rate': 0.024235900006421195}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20536765150306427
Fold 2 IBS: 0.18014952635091636
Fold 3 IBS: 0.183023785063995
Fold 4 IBS: 0.19223726439760763
Fold 5 IBS: 0.18830661932475276
[I 2024-04-18 08:18:21,050] Trial 77 finished with value: 0.1898169693280672 and parameters: {'subsample': 0.6241144322095822, 'dropout_rate': 0.8105208156539707, 'n_estimators': 141, 'learning_rate': 0.008359784620781453}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2374025235368971
Fold 2 IBS: 0.13948712259061768
Fold 3 IBS: 0.1789264161523359
Fold 4 IBS: 0.16528306816225447
Fold 5 IBS: 0.1748234198685515
[I 2024-04-18 08:18:24,407] Trial 78 finished with value: 0.17918451006213135 and parameters: {'subsample': 0.7835149545313702, 'dropout_rate': 0.7356714267781426, 'n_estimators': 245, 'learning_rate': 0.019593513896557644}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2178380962592654
Fold 2 IBS: 0.14849481475424472
Fold 3 IBS: 0.17186114706460975
Fold 4 IBS: 0.16948155005422186
Fold 5 IBS: 0.17259850736693585
[I 2024-04-18 08:18:26,298] Trial 79 finished with value: 0.1760548230998555 and parameters: {'subsample': 0.7306460692991882, 'dropout_rate': 0.9456669166827321, 'n_estimators': 197, 'learning_rate': 0.013900639165746409}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21941640462332523
Fold 2 IBS: 0.1467654282726585
Fold 3 IBS: 0.1716233736876645
Fold 4 IBS: 0.16836352442601
Fold 5 IBS: 0.17222712526846806
[I 2024-04-18 08:18:30,281] Trial 80 finished with value: 0.17567917125562527 and parameters: {'subsample': 0.7066973880335033, 'dropout_rate': 0.7775354516227033, 'n_estimators': 263, 'learning_rate': 0.010980464731558733}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20568488920477843
Fold 2 IBS: 0.18796783018353427
Fold 3 IBS: 0.18685004344608916
Fold 4 IBS: 0.19854829105066216
Fold 5 IBS: 0.193867776213655
[I 2024-04-18 08:18:33,487] Trial 81 finished with value: 0.1945837660197438 and parameters: {'subsample': 0.6419484838106376, 'dropout_rate': 0.7667668175741065, 'n_estimators': 265, 'learning_rate': 0.0034829521578378184}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2176580042675807
Fold 2 IBS: 0.14852999516311843
Fold 3 IBS: 0.17178544808402105
Fold 4 IBS: 0.16942620956975318
Fold 5 IBS: 0.17264997725183107
[I 2024-04-18 08:18:36,231] Trial 82 finished with value: 0.17600992686726089 and parameters: {'subsample': 0.7099348186623953, 'dropout_rate': 0.6935406114357077, 'n_estimators': 232, 'learning_rate': 0.011776109198709075}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.22828428699654107
Fold 2 IBS: 0.14115865275171224
Fold 3 IBS: 0.17311833727705653
Fold 4 IBS: 0.16533788933477025
Fold 5 IBS: 0.1720403430684168
[I 2024-04-18 08:18:39,007] Trial 83 finished with value: 0.1759879018856994 and parameters: {'subsample': 0.7593393564759855, 'dropout_rate': 0.7996906931881717, 'n_estimators': 224, 'learning_rate': 0.016635361466314266}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2156763236700085
Fold 2 IBS: 0.15089163516223517
Fold 3 IBS: 0.17217789147191037
Fold 4 IBS: 0.17093962911550922
Fold 5 IBS: 0.17339255172190493
[I 2024-04-18 08:18:43,232] Trial 84 finished with value: 0.17661560622831363 and parameters: {'subsample': 0.6672247388188236, 'dropout_rate': 0.7387851369702363, 'n_estimators': 299, 'learning_rate': 0.00851024531106618}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.24237858860872646
Fold 2 IBS: 0.14002598466913488
Fold 3 IBS: 0.18399373252484688
Fold 4 IBS: 0.16632504923341399
Fold 5 IBS: 0.17745823420671353
[I 2024-04-18 08:18:46,472] Trial 85 finished with value: 0.18203631784856716 and parameters: {'subsample': 0.605381148249432, 'dropout_rate': 0.8964533074797122, 'n_estimators': 254, 'learning_rate': 0.021789205122951162}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.24427478289672075
Fold 2 IBS: 0.14018641516879085
Fold 3 IBS: 0.18629647168693408
Fold 4 IBS: 0.16701701915803638
Fold 5 IBS: 0.1784224868272325
[I 2024-04-18 08:18:50,286] Trial 86 finished with value: 0.1832394351475429 and parameters: {'subsample': 0.5615804566216691, 'dropout_rate': 0.7870138983598058, 'n_estimators': 322, 'learning_rate': 0.01813466186989581}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.3192446475885533
Fold 2 IBS: 0.20222138834149514
Fold 3 IBS: 0.2704006245435982
Fold 4 IBS: 0.23405515515458486
Fold 5 IBS: 0.22530658100861864
[I 2024-04-18 08:18:59,099] Trial 87 finished with value: 0.25024567932737 and parameters: {'subsample': 0.49205438109527067, 'dropout_rate': 0.8371732265849307, 'n_estimators': 472, 'learning_rate': 0.07823986277139501}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2208150602709649
Fold 2 IBS: 0.14537310589423852
Fold 3 IBS: 0.17160166992515213
Fold 4 IBS: 0.1676622145784082
Fold 5 IBS: 0.17211948572363678
[I 2024-04-18 08:19:02,847] Trial 88 finished with value: 0.1755143072784801 and parameters: {'subsample': 0.5300609737918551, 'dropout_rate': 0.8706362607677022, 'n_estimators': 278, 'learning_rate': 0.010900972676247678}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2177304678090218
Fold 2 IBS: 0.14802540809731987
Fold 3 IBS: 0.1719066305891292
Fold 4 IBS: 0.16941222732084524
Fold 5 IBS: 0.17296582630342672
[I 2024-04-18 08:19:05,036] Trial 89 finished with value: 0.17600811202394856 and parameters: {'subsample': 0.5333362047646266, 'dropout_rate': 0.9294107219485171, 'n_estimators': 184, 'learning_rate': 0.01478765888022868}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.3055541288334449
Fold 2 IBS: 0.1889659329210266
Fold 3 IBS: 0.26142024280615456
Fold 4 IBS: 0.21906068924799293
Fold 5 IBS: 0.21745813831016794
[I 2024-04-18 08:19:08,645] Trial 90 finished with value: 0.23849182642375738 and parameters: {'subsample': 0.4592875721986819, 'dropout_rate': 0.8709204688294995, 'n_estimators': 277, 'learning_rate': 0.08895693358209904}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21095311288159033
Fold 2 IBS: 0.15800363336180157
Fold 3 IBS: 0.1740842259482107
Fold 4 IBS: 0.175593776476648
Fold 5 IBS: 0.17618200743802453
[I 2024-04-18 08:19:11,220] Trial 91 finished with value: 0.17896335122125503 and parameters: {'subsample': 0.589555562448569, 'dropout_rate': 0.7804712704898428, 'n_estimators': 213, 'learning_rate': 0.009903811318361096}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2234430205258879
Fold 2 IBS: 0.14362063946010012
Fold 3 IBS: 0.17183477820073997
Fold 4 IBS: 0.16661781942842602
Fold 5 IBS: 0.1717658468654695
[I 2024-04-18 08:19:14,669] Trial 92 finished with value: 0.1754564208961247 and parameters: {'subsample': 0.6387308459521087, 'dropout_rate': 0.8182054266482846, 'n_estimators': 263, 'learning_rate': 0.012434997438625691}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.22498572137926615
Fold 2 IBS: 0.14268046218025113
Fold 3 IBS: 0.17212111097050423
Fold 4 IBS: 0.1661509265593604
Fold 5 IBS: 0.1717610406629388
[I 2024-04-18 08:19:17,519] Trial 93 finished with value: 0.17553985235046415 and parameters: {'subsample': 0.6382000440974231, 'dropout_rate': 0.8540920034010585, 'n_estimators': 249, 'learning_rate': 0.013720425511831776}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.2274954933297866
Fold 2 IBS: 0.14150422665182638
Fold 3 IBS: 0.17284830412071275
Fold 4 IBS: 0.16551140095291972
Fold 5 IBS: 0.17193307658408025
[I 2024-04-18 08:19:21,052] Trial 94 finished with value: 0.17585850032786512 and parameters: {'subsample': 0.6714601389310578, 'dropout_rate': 0.8161620770375514, 'n_estimators': 281, 'learning_rate': 0.013021083504677101}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20804320486997557

Fold 2 IBS: 0.16478959838439622
Fold 3 IBS: 0.17653755878235672
Fold 4 IBS: 0.1805950354677507
Fold 5 IBS: 0.17998076390593717
[I 2024-04-18 08:19:24,893] Trial 95 finished with value: 0.18198923228208327 and parameters: {'subsample': 0.5198280584984859, 'dropout_rate': 0.8486478738783642, 'n_estimators': 294, 'learning_rate': 0.006037141349276085}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.23515216169778982
Fold 2 IBS: 0.13954617558808188
Fold 3 IBS: 0.17705832296971719
Fold 4 IBS: 0.16501460559381048
Fold 5 IBS: 0.17386940040131596
[I 2024-04-18 08:19:28,193] Trial 96 finished with value: 0.17812813325014307 and parameters: {'subsample': 0.6271111992646494, 'dropout_rate': 0.892295025185902, 'n_estimators': 249, 'learning_rate': 0.018198796414258485}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.21259560893410287
Fold 2 IBS: 0.15514525884910346
Fold 3 IBS: 0.17326490031645939
Fold 4 IBS: 0.1738706026163926
Fold 5 IBS: 0.1751375875495752
[I 2024-04-18 08:19:33,253] Trial 97 finished with value: 0.1780027916531267 and parameters: {'subsample': 0.5606440507914384, 'dropout_rate': 0.8178741138334622, 'n_estimators': 342, 'learning_rate': 0.006639951642837932}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.20693997978746867
Fold 2 IBS: 0.1968239751130939
Fold 3 IBS: 0.19098089125488407
Fold 4 IBS: 0.20504772982739192
Fold 5 IBS: 0.19973365667181198
[I 2024-04-18 08:19:37,020] Trial 98 finished with value: 0.19990524653093011 and parameters: {'subsample': 0.5857591505175948, 'dropout_rate': 0.2002801186536965, 'n_estimators': 240, 'learning_rate': 0.0028008148140343976}. Best is trial 36 with value: 0.17545126273803033.
Fold 1 IBS: 0.23592694578240203
Fold 2 IBS: 0.13950678582093226
Fold 3 IBS: 0.1775200783836256
Fold 4 IBS: 0.1650848452666046
Fold 5 IBS: 0.1741186976353095
[I 2024-04-18 08:19:41,018] Trial 99 finished with value: 0.1784314705777748 and parameters: {'subsample': 0.6840447181752907, 'dropout_rate': 0.8664450665747747, 'n_estimators': 311, 'learning_rate': 0.014831504489878378}. Best is trial 36 with value: 0.17545126273803033.


* Best trial for IBS:
 FrozenTrial(number=36, state=TrialState.COMPLETE, values=[0.17545126273803033], datetime_start=datetime.datetime(2024, 4, 18, 8, 16, 19, 641127), datetime_complete=datetime.datetime(2024, 4, 18, 8, 16, 22, 993425), params={'subsample': 0.6689949239769296, 'dropout_rate': 0.7803451305864744, 'n_estimators': 251, 'learning_rate': 0.012746071877375342}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=36, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6689949239769296, 'dropout_rate': 0.7803451305864744, 'n_estimators': 251, 'learning_rate': 0.012746071877375342}


* Best Score for IBS:
 0.17545126273803033

In [76]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [77]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.712
train_ibs:  0.175

#### Test

In [78]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [79]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10707700162921632,
                                              learning_rate=0.09635955935176935,
                                              n_estimators=311,
                                              random_state=123,
                                              subsample=0.11211713718471546)

C-index score: 0.598

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7803451305864744,
                                              learning_rate=0.012746071877375342,
                                              n_estimators=251,
                                              random_state=123,
                                              subsample=0.6689949239769296)

IBS: 0.231

In [80]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [81]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.855   1.0
ExtraSurvivalTrees               0.830   2.0
GradientBoosting                 0.791   3.0
CoxElastic                       0.780   4.0
CoxLasso                         0.779   5.0
CoxPH                            0.778   6.0
ComponentwiseGradientBoosting    0.712   7.0
CoxRidge                         0.681   8.0

In [82]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.167   1.0
CoxElastic                     0.168   2.0
CoxPH                          0.169   3.5
CoxLasso                       0.169   3.5
ExtraSurvivalTrees             0.172   5.0
ComponentwiseGradientBoosting  0.175   6.0
GradientBoosting               0.213   7.0
CoxRidge                       0.217   8.0

In [83]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.647   1.0
ExtraSurvivalTrees               0.629   2.0
CoxLasso                         0.623   3.5
CoxElastic                       0.623   3.5
CoxPH                            0.620   5.0
Randomsurvivalforest             0.601   6.0
ComponentwiseGradientBoosting    0.598   7.0
CoxRidge                         0.578   8.0

In [84]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.213   1.0
Randomsurvivalforest           0.218   2.0
GradientBoosting               0.219   3.0
CoxRidge                       0.221   4.0
CoxElastic                     0.229   5.0
CoxLasso                       0.230   6.0
ComponentwiseGradientBoosting  0.231   7.0
CoxPH                          0.232   8.0

In [85]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/standard/plsr/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_standard_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [86]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-18